/* Logic Gates Lab: UI strings. Keys are identical in all 12 languages.
   Gate names (AND, OR, NOT, NAND, NOR, XOR, XNOR), variables (A–E) and signs stay in Latin script,
   as in Indian textbooks. Shared words (reset, print, next, score …) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Logic Gates Lab',
    intro: 'Flip switches to see how logic gates work, turn Boolean expressions into truth tables and circuits, check laws like De Morgan’s, and practise.',
    tab_gates: 'Gates', tab_expr: 'Expression lab', tab_adders: 'Adders', tab_practice: 'Practice',
    choose_gate: 'Gate', inputs: 'Inputs', n_inputs: '{n} inputs', one_input: '1 input', gate_name: '{g} gate',
    tap_switch: 'Tap a switch to flip it between 0 and 1. Tap a row of the table to jump to it.',
    kbd_hint: 'On a keyboard, press A, B or C to flip the inputs.',
    expression: 'Boolean expression', rule: 'Rule', real_life: 'Real-life example', truth_table: 'Truth table',
    rule_and: 'Y is 1 only when all inputs are 1.',
    rule_or: 'Y is 1 when at least one input is 1.',
    rule_not: 'Y is the opposite of the input: 0 becomes 1 and 1 becomes 0.',
    rule_nand: 'NOT + AND: Y is 0 only when all inputs are 1.',
    rule_nor: 'NOT + OR: Y is 1 only when all inputs are 0.',
    rule_xor: 'Y is 1 when an odd number of inputs are 1. With two inputs: when they are different.',
    rule_xnor: 'NOT + XOR: Y is 1 when an even number of inputs are 1. With two inputs: when they are the same.',
    life_and: 'A ceiling fan runs only when the main switch AND the fan switch are both on.',
    life_or: 'The school bell rings when the office OR the staff room presses its button.',
    life_not: 'A home inverter turns on when there is NOT any mains power (during a power cut).',
    life_nand: 'A car’s seat-belt alarm keeps beeping until both front seat belts are fastened.',
    life_nor: 'The water pump fills the overhead tank only when the tank is not full and the voltage is not low.',
    life_xor: 'A staircase light with two switches: flipping either switch, upstairs or downstairs, changes the light.',
    life_xnor: 'An answer checker: the green light glows when your answer and the correct answer are the same.',
    universal: 'NAND and NOR are called universal gates: any circuit can be built using only NAND gates, or only NOR gates.',
    all_gates: 'All gates at a glance',
    all_gates_hint: 'The highlighted row matches switches A and B. Tap a row to change them.',
    sw_aria: 'Input {v} is {x}. Press to change.',
    out_aria: 'Output {v} is {x}',
    expr_label: 'Type a Boolean expression',
    expr_help: 'Use the variables A to E with AND, OR, NOT, XOR, NAND, NOR, XNOR or the signs · + \' ⊕ and brackets. AB means A·B.',
    examples: 'Examples', backspace: 'Delete one character', copy_link: 'Copy link',
    circuit: 'Circuit diagram',
    circuit_hint: 'Tap an input (A, B…) in the diagram or the buttons above it to flip it. Green wires carry 1, grey wires carry 0.',
    too_big: 'This expression is too big to draw neatly. The truth table still works.',
    no_inputs: 'No variables: the output never changes.',
    show_steps: 'Show step columns',
    row_hint: 'Tap a row to set all the inputs at once.',
    always_1: 'Y is always 1 (a tautology).',
    always_0: 'Y is always 0 (a contradiction).',
    ones_in: 'Y is 1 in {k} of {n} rows:',
    err_empty: 'Type an expression to begin, for example A·B + C.',
    err_unknown: 'Unknown letter “{ch}”. Use only the variables A, B, C, D and E.',
    err_symbol: 'The sign “{ch}” at position {n} is not understood.',
    err_close: 'The bracket opened at position {n} is never closed. Add a “)”.',
    err_extra_close: 'There is an extra “)” at position {n}.',
    err_operand: 'Something is missing at position {n}. Put a variable, 0, 1 or “(” there.',
    err_end: 'The expression ends too early. Add a variable after the last sign.',
    err_too_long: 'The expression is too long. Keep it under {n} characters.',
    equiv_title: 'Are two expressions equal?',
    equiv_intro: 'Type two expressions or pick a law. The app checks every row of the truth table.',
    try_law: 'Try a law:',
    law_dm1: 'De Morgan’s law 1', law_dm2: 'De Morgan’s law 2',
    law_abs1: 'Absorption law', law_abs2: 'Absorption law (dual)',
    law_dist1: 'Distributive law', law_dist2: 'Distributive law (dual)',
    law_xor: 'XOR with AND, OR, NOT', law_dneg: 'Double NOT', law_nand: 'NOT from a NAND gate', law_mistake: 'A common mistake',
    expr1: 'First expression', expr2: 'Second expression', check: 'Check',
    equiv_yes: 'Equivalent ✓ Both give the same output in all {n} rows.',
    equiv_no: 'Not equivalent ✗',
    equiv_detail: 'Counterexample: when {vals}, the first gives {a} but the second gives {b}.',
    col_first: 'First', col_second: 'Second', same: 'Same?',
    half_adder: 'Half adder', full_adder: 'Full adder', four_bit: '4-bit adder',
    ha_desc: 'A half adder adds two bits, A and B. It gives a Sum bit (S) and a Carry bit (C).',
    legend_ha: 'S = Sum, C = Carry',
    why_carry: 'Why a carry? In binary, 1 + 1 = 10. We write 0 and carry 1 to the next place, just like 5 + 5 = 10 in decimal.',
    fa_desc: 'A full adder adds three bits: A, B and the carry-in (Cin) from the previous place. It is built from two half adders and an OR gate.',
    legend_fa: 'Cin = Carry in, S = Sum, Cout = Carry out',
    fa_how: 'Cout is 1 when at least two of the three inputs are 1.',
    read_bin: 'Read carry and sum together as one binary number: {bin} = {d} in decimal.',
    four_desc: 'Four full adders in a chain add two 4-bit numbers (0 to 15). Each carry moves to the next place on the left, like a ripple.',
    place_val: 'Place value', carry_row: 'Carry',
    bit_aria: '{v}, bit for {p}, is {x}. Press to change.',
    final_carry: 'The last carry becomes the fifth bit of the answer.',
    tap_bits: 'Tap the bits of A and B to change the numbers.',
    mode_fill: 'Complete the table', mode_name: 'Name the gate',
    level: 'Level', easy: 'Easy', medium: 'Medium', hard: 'Hard', streak: 'Streak', best: 'Best',
    fill_q: 'Fill the output column Y for:',
    tap_cells: 'Tap each ? to choose 0 or 1, then press Check.',
    cell_aria: 'Row {n}: output Y is {x}. Press to change.',
    show_answer: 'Show answer', new_question: 'New question',
    fill_all: 'Fill every row first.',
    all_right: 'All {n} rows are right. Well done!',
    some_wrong: '{k} of {n} rows are right. Fix the red ones and check again.',
    answer_shown: 'Here is the answer. Study it, then try a new question.',
    name_q: 'Which gate gives this truth table?',
    name_right: 'Yes! This is the {g} gate.',
    name_wrong: 'Not quite. This is the {g} gate.',
    ws_hint: 'Print 8 truth-table questions at this level, with an answer key.',
    print_ws: 'Print worksheet', ws_title: 'Logic gates worksheet',
    ws_intro: 'Complete the output column Y of each truth table.',
    ws_name: 'Name', ws_class: 'Class', ws_date: 'Date', answer_key: 'Answer key',
    help_title: 'How to use / Ideas for the classroom',
    help_1: 'Gates: pick a gate and tap the switches. The lamp shows the output Y and the matching row of the truth table lights up.',
    help_2: 'Expression lab: type something like (A + B)·C\' or NOT (A AND B). You get the truth table with step columns and a circuit you can test live.',
    help_3: 'Use “Are two expressions equal?” to prove De Morgan’s laws. If two expressions are not equal, the app shows a row where they differ.',
    help_4: 'Adders: see how a computer adds binary numbers with half adders and full adders, then add two 4-bit numbers.',
    help_5: 'Classroom activity, “human logic gate”: two students are inputs A and B (hand up = 1). A third student is the gate and raises a hand only when the rule gives 1. The class checks on the smartboard.',
    help_6: 'Teachers: in Practice, choose a level and press “Print worksheet” to get 8 questions with an answer key.'
  },

  hi: {
    app_title: 'लॉजिक गेट लैब',
    intro: 'स्विच दबाकर देखिए कि लॉजिक गेट कैसे काम करते हैं, बूलियन एक्सप्रेशन से ट्रुथ टेबल और सर्किट बनाइए, डी मॉर्गन जैसे नियम जाँचिए और अभ्यास कीजिए।',
    tab_gates: 'गेट', tab_expr: 'एक्सप्रेशन लैब', tab_adders: 'ऐडर', tab_practice: 'अभ्यास',
    choose_gate: 'गेट', inputs: 'इनपुट', n_inputs: '{n} इनपुट', one_input: '1 इनपुट', gate_name: '{g} गेट',
    tap_switch: 'स्विच को छूकर 0 और 1 के बीच बदलें। टेबल की किसी पंक्ति को छूकर सीधे उस पर जाएँ।',
    kbd_hint: 'कीबोर्ड पर A, B या C दबाकर भी इनपुट बदल सकते हैं।',
    expression: 'बूलियन एक्सप्रेशन', rule: 'नियम', real_life: 'असली ज़िंदगी में उदाहरण', truth_table: 'ट्रुथ टेबल (सत्य सारणी)',
    rule_and: 'Y तभी 1 होता है जब सारे इनपुट 1 हों।',
    rule_or: 'Y तब 1 होता है जब कम से कम एक इनपुट 1 हो।',
    rule_not: 'Y इनपुट का उल्टा होता है: 0 बनता है 1, और 1 बनता है 0।',
    rule_nand: 'NOT + AND: Y सिर्फ़ तब 0 होता है जब सारे इनपुट 1 हों।',
    rule_nor: 'NOT + OR: Y सिर्फ़ तब 1 होता है जब सारे इनपुट 0 हों।',
    rule_xor: 'Y तब 1 होता है जब विषम संख्या में इनपुट 1 हों। दो इनपुट में: जब दोनों अलग-अलग हों।',
    rule_xnor: 'NOT + XOR: Y तब 1 होता है जब सम संख्या में इनपुट 1 हों। दो इनपुट में: जब दोनों एक जैसे हों।',
    life_and: 'छत का पंखा तभी चलता है जब मेन स्विच और पंखे का स्विच, दोनों ON हों।',
    life_or: 'स्कूल की घंटी तब बजती है जब ऑफ़िस या स्टाफ़ रूम में से कोई भी अपना बटन दबाए।',
    life_not: 'घर का इन्वर्टर तब चालू होता है जब बिजली नहीं होती (लाइट जाने पर)।',
    life_nand: 'कार का सीट-बेल्ट अलार्म तब तक बजता रहता है जब तक आगे की दोनों सीट बेल्ट न लग जाएँ।',
    life_nor: 'पानी की मोटर छत की टंकी तभी भरती है जब टंकी भरी न हो और वोल्टेज कम न हो।',
    life_xor: 'सीढ़ी की लाइट में दो स्विच होते हैं: ऊपर या नीचे, कोई भी एक स्विच बदलने से लाइट बदल जाती है।',
    life_xnor: 'उत्तर जाँचने वाली मशीन: जब आपका उत्तर और सही उत्तर एक जैसे हों, तब हरी बत्ती जलती है।',
    universal: 'NAND और NOR को यूनिवर्सल गेट कहते हैं: सिर्फ़ NAND गेट से (या सिर्फ़ NOR गेट से) कोई भी सर्किट बनाया जा सकता है।',
    all_gates: 'सभी गेट एक नज़र में',
    all_gates_hint: 'हाइलाइट वाली पंक्ति स्विच A और B से मेल खाती है। बदलने के लिए किसी पंक्ति को छुएँ।',
    sw_aria: 'इनपुट {v} अभी {x} है। बदलने के लिए दबाएँ।',
    out_aria: 'आउटपुट {v} अभी {x} है',
    expr_label: 'बूलियन एक्सप्रेशन लिखें',
    expr_help: 'वेरिएबल A से E तक लें, साथ में AND, OR, NOT, XOR, NAND, NOR, XNOR या चिह्न · + \' ⊕ और कोष्ठक। AB का मतलब है A·B।',
    examples: 'उदाहरण', backspace: 'एक अक्षर मिटाएँ', copy_link: 'लिंक कॉपी करें',
    circuit: 'सर्किट डायग्राम',
    circuit_hint: 'डायग्राम में किसी इनपुट (A, B…) को या ऊपर के बटन को छूकर बदलें। हरे तार में 1 है, स्लेटी तार में 0।',
    too_big: 'यह एक्सप्रेशन साफ़-साफ़ बनाने के लिए बहुत बड़ा है। ट्रुथ टेबल फिर भी काम करती है।',
    no_inputs: 'कोई वेरिएबल नहीं है: आउटपुट कभी नहीं बदलेगा।',
    show_steps: 'बीच के स्टेप वाले कॉलम दिखाएँ',
    row_hint: 'किसी पंक्ति को छूकर सारे इनपुट एक साथ सेट करें।',
    always_1: 'Y हमेशा 1 है (टॉटोलॉजी)।',
    always_0: 'Y हमेशा 0 है (कॉन्ट्राडिक्शन)।',
    ones_in: '{n} में से {k} पंक्तियों में Y = 1:',
    err_empty: 'शुरू करने के लिए एक्सप्रेशन लिखें, जैसे A·B + C।',
    err_unknown: 'अनजाना अक्षर “{ch}”। सिर्फ़ A, B, C, D और E वेरिएबल लें।',
    err_symbol: 'स्थान {n} पर चिह्न “{ch}” समझ नहीं आया।',
    err_close: 'स्थान {n} पर खुला कोष्ठक बंद नहीं हुआ। “)” जोड़ें।',
    err_extra_close: 'स्थान {n} पर एक “)” ज़्यादा है।',
    err_operand: 'स्थान {n} पर कुछ छूट गया है। वहाँ कोई वेरिएबल, 0, 1 या “(” लिखें।',
    err_end: 'एक्सप्रेशन अधूरा रह गया। आख़िरी चिह्न के बाद एक वेरिएबल जोड़ें।',
    err_too_long: 'एक्सप्रेशन बहुत लंबा है। इसे {n} अक्षरों से छोटा रखें।',
    equiv_title: 'क्या दो एक्सप्रेशन बराबर हैं?',
    equiv_intro: 'दो एक्सप्रेशन लिखें या कोई नियम चुनें। ऐप ट्रुथ टेबल की हर पंक्ति जाँचता है।',
    try_law: 'कोई नियम आज़माएँ:',
    law_dm1: 'डी मॉर्गन का नियम 1', law_dm2: 'डी मॉर्गन का नियम 2',
    law_abs1: 'अवशोषण नियम', law_abs2: 'अवशोषण नियम (द्वैत)',
    law_dist1: 'वितरण नियम', law_dist2: 'वितरण नियम (द्वैत)',
    law_xor: 'AND, OR, NOT से XOR', law_dneg: 'दोहरा NOT', law_nand: 'NAND गेट से NOT', law_mistake: 'एक आम ग़लती',
    expr1: 'पहला एक्सप्रेशन', expr2: 'दूसरा एक्सप्रेशन', check: 'जाँचें',
    equiv_yes: 'बराबर हैं ✓ सभी {n} पंक्तियों में दोनों का आउटपुट एक जैसा है।',
    equiv_no: 'बराबर नहीं हैं ✗',
    equiv_detail: 'उल्टा उदाहरण: जब {vals}, तब पहला {a} देता है लेकिन दूसरा {b} देता है।',
    col_first: 'पहला', col_second: 'दूसरा', same: 'एक जैसे?',
    half_adder: 'हाफ़ ऐडर', full_adder: 'फ़ुल ऐडर', four_bit: '4-बिट ऐडर',
    ha_desc: 'हाफ़ ऐडर दो बिट A और B को जोड़ता है। यह एक योग बिट (S) और एक कैरी बिट (C) देता है।',
    legend_ha: 'S = योग (Sum), C = कैरी या हासिल (Carry)',
    why_carry: 'कैरी क्यों? बाइनरी में 1 + 1 = 10 होता है। हम 0 लिखते हैं और 1 अगले स्थान पर ले जाते हैं, ठीक वैसे ही जैसे दशमलव में 5 + 5 = 10।',
    fa_desc: 'फ़ुल ऐडर तीन बिट जोड़ता है: A, B और पिछले स्थान से आया कैरी (Cin)। यह दो हाफ़ ऐडर और एक OR गेट से बनता है।',
    legend_fa: 'Cin = आने वाला कैरी, S = योग, Cout = जाने वाला कैरी',
    fa_how: 'तीन में से कम से कम दो इनपुट 1 हों, तो Cout = 1 होता है।',
    read_bin: 'कैरी और योग को साथ पढ़ें, यह एक बाइनरी संख्या है: {bin} = दशमलव में {d}।',
    four_desc: 'चार फ़ुल ऐडर की एक कड़ी दो 4-बिट संख्याएँ (0 से 15) जोड़ती है। हर कैरी बाईं ओर के अगले स्थान पर जाता है, लहर की तरह।',
    place_val: 'स्थानीय मान', carry_row: 'कैरी',
    bit_aria: '{v} का {p} वाला बिट {x} है। बदलने के लिए दबाएँ।',
    final_carry: 'आख़िरी कैरी उत्तर का पाँचवाँ बिट बन जाता है।',
    tap_bits: 'संख्याएँ बदलने के लिए A और B के बिट छुएँ।',
    mode_fill: 'टेबल पूरी करें', mode_name: 'गेट पहचानें',
    level: 'स्तर', easy: 'आसान', medium: 'मध्यम', hard: 'कठिन', streak: 'लगातार सही', best: 'सबसे अच्छा',
    fill_q: 'इसके लिए आउटपुट कॉलम Y भरें:',
    tap_cells: 'हर ? को छूकर 0 या 1 चुनें, फिर “जाँचें” दबाएँ।',
    cell_aria: 'पंक्ति {n}: आउटपुट Y अभी {x} है। बदलने के लिए दबाएँ।',
    show_answer: 'उत्तर दिखाएँ', new_question: 'नया सवाल',
    fill_all: 'पहले हर पंक्ति भरें।',
    all_right: 'सभी {n} पंक्तियाँ सही हैं। शाबाश!',
    some_wrong: '{n} में से {k} पंक्तियाँ सही हैं। लाल वाली ठीक करके फिर जाँचें।',
    answer_shown: 'यह रहा उत्तर। इसे ध्यान से देखें, फिर नया सवाल करें।',
    name_q: 'कौन-सा गेट यह ट्रुथ टेबल देता है?',
    name_right: 'हाँ! यह {g} गेट है।',
    name_wrong: 'ठीक नहीं। यह {g} गेट है।',
    ws_hint: 'इस स्तर के 8 ट्रुथ टेबल सवाल उत्तर-कुंजी के साथ प्रिंट करें।',
    print_ws: 'वर्कशीट प्रिंट करें', ws_title: 'लॉजिक गेट वर्कशीट',
    ws_intro: 'हर ट्रुथ टेबल का आउटपुट कॉलम Y पूरा करें।',
    ws_name: 'नाम', ws_class: 'कक्षा', ws_date: 'तारीख़', answer_key: 'उत्तर-कुंजी',
    help_title: 'कैसे इस्तेमाल करें / कक्षा के लिए सुझाव',
    help_1: 'गेट: कोई गेट चुनें और स्विच छुएँ। बल्ब आउटपुट Y दिखाता है और ट्रुथ टेबल की मिलती-जुलती पंक्ति चमकती है।',
    help_2: 'एक्सप्रेशन लैब: (A + B)·C\' या NOT (A AND B) जैसा कुछ लिखें। आपको स्टेप कॉलम वाली ट्रुथ टेबल और एक सर्किट मिलेगा जिसे आप तुरंत जाँच सकते हैं।',
    help_3: '“क्या दो एक्सप्रेशन बराबर हैं?” से डी मॉर्गन के नियम साबित करें। अगर दोनों बराबर नहीं हैं, तो ऐप वह पंक्ति दिखाता है जहाँ वे अलग हैं।',
    help_4: 'ऐडर: देखें कि कंप्यूटर हाफ़ ऐडर और फ़ुल ऐडर से बाइनरी संख्याएँ कैसे जोड़ता है, फिर दो 4-बिट संख्याएँ जोड़ें।',
    help_5: 'कक्षा गतिविधि “इंसानी लॉजिक गेट”: दो विद्यार्थी इनपुट A और B बनें (हाथ ऊपर = 1)। तीसरा विद्यार्थी गेट बने और तभी हाथ उठाए जब नियम 1 कहे। पूरी कक्षा स्मार्टबोर्ड पर जाँचे।',
    help_6: 'शिक्षकों के लिए: अभ्यास में स्तर चुनें और “वर्कशीट प्रिंट करें” दबाएँ, 8 सवाल उत्तर-कुंजी के साथ मिलेंगे।'
  },

  bn: {
    app_title: 'লজিক গেট ল্যাব',
    intro: 'সুইচ টিপে দেখুন লজিক গেট কীভাবে কাজ করে, বুলিয়ান এক্সপ্রেশন থেকে ট্রুথ টেবিল ও সার্কিট তৈরি করুন, ডি মরগানের মতো নিয়ম যাচাই করুন এবং অনুশীলন করুন।',
    tab_gates: 'গেট', tab_expr: 'এক্সপ্রেশন ল্যাব', tab_adders: 'অ্যাডার', tab_practice: 'অনুশীলন',
    choose_gate: 'গেট', inputs: 'ইনপুট', n_inputs: '{n}টি ইনপুট', one_input: '1টি ইনপুট', gate_name: '{g} গেট',
    tap_switch: 'সুইচ ছুঁয়ে 0 আর 1-এর মধ্যে বদলান। টেবিলের কোনো সারি ছুঁলে সরাসরি সেখানে যাবে।',
    kbd_hint: 'কিবোর্ডে A, B বা C চেপেও ইনপুট বদলাতে পারেন।',
    expression: 'বুলিয়ান এক্সপ্রেশন', rule: 'নিয়ম', real_life: 'বাস্তব জীবনের উদাহরণ', truth_table: 'ট্রুথ টেবিল (সত্যসারণি)',
    rule_and: 'সব ইনপুট 1 হলে তবেই Y = 1 হয়।',
    rule_or: 'অন্তত একটি ইনপুট 1 হলে Y = 1 হয়।',
    rule_not: 'Y হলো ইনপুটের উল্টো: 0 হয়ে যায় 1, আর 1 হয়ে যায় 0।',
    rule_nand: 'NOT + AND: সব ইনপুট 1 হলে শুধু তখনই Y = 0 হয়।',
    rule_nor: 'NOT + OR: সব ইনপুট 0 হলে শুধু তখনই Y = 1 হয়।',
    rule_xor: 'বিজোড় সংখ্যক ইনপুট 1 হলে Y = 1 হয়। দুটি ইনপুটে: যখন দুটি আলাদা।',
    rule_xnor: 'NOT + XOR: জোড় সংখ্যক ইনপুট 1 হলে Y = 1 হয়। দুটি ইনপুটে: যখন দুটি একই।',
    life_and: 'সিলিং ফ্যান তখনই চলে যখন মেইন সুইচ আর ফ্যানের সুইচ দুটোই অন থাকে।',
    life_or: 'অফিস বা স্টাফ রুম, যে-কেউ বোতাম টিপলেই স্কুলের ঘণ্টা বাজে।',
    life_not: 'বাড়ির ইনভার্টার তখন চালু হয় যখন কারেন্ট থাকে না (লোডশেডিংয়ের সময়)।',
    life_nand: 'গাড়ির সিট-বেল্ট অ্যালার্ম বাজতেই থাকে, যতক্ষণ না সামনের দুটো সিট বেল্টই বাঁধা হয়।',
    life_nor: 'জলের পাম্প ছাদের ট্যাংক তখনই ভরে যখন ট্যাংক ভর্তি নয় এবং ভোল্টেজ কম নয়।',
    life_xor: 'সিঁড়ির আলোর দুটি সুইচ: ওপরে বা নিচে, যেকোনো একটা সুইচ বদলালেই আলো বদলে যায়।',
    life_xnor: 'উত্তর যাচাই যন্ত্র: আপনার উত্তর আর সঠিক উত্তর একই হলে সবুজ আলো জ্বলে।',
    universal: 'NAND আর NOR-কে ইউনিভার্সাল গেট বলে: শুধু NAND গেট (বা শুধু NOR গেট) দিয়েই যেকোনো সার্কিট বানানো যায়।',
    all_gates: 'সব গেট এক নজরে',
    all_gates_hint: 'হাইলাইট করা সারিটি সুইচ A আর B-এর সঙ্গে মেলে। বদলাতে কোনো সারি ছুঁয়ে দিন।',
    sw_aria: 'ইনপুট {v} এখন {x}। বদলাতে চাপুন।',
    out_aria: 'আউটপুট {v} এখন {x}',
    expr_label: 'একটি বুলিয়ান এক্সপ্রেশন লিখুন',
    expr_help: 'A থেকে E ভেরিয়েবল নিন, সঙ্গে AND, OR, NOT, XOR, NAND, NOR, XNOR বা চিহ্ন · + \' ⊕ আর বন্ধনী। AB মানে A·B।',
    examples: 'উদাহরণ', backspace: 'একটি অক্ষর মুছুন', copy_link: 'লিংক কপি করুন',
    circuit: 'সার্কিট ডায়াগ্রাম',
    circuit_hint: 'ডায়াগ্রামে কোনো ইনপুট (A, B…) বা ওপরের বোতাম ছুঁয়ে বদলান। সবুজ তারে 1, ধূসর তারে 0।',
    too_big: 'এক্সপ্রেশনটি গুছিয়ে আঁকার পক্ষে খুব বড়। ট্রুথ টেবিল তবুও কাজ করবে।',
    no_inputs: 'কোনো ভেরিয়েবল নেই: আউটপুট কখনো বদলাবে না।',
    show_steps: 'মাঝের ধাপের কলাম দেখান',
    row_hint: 'কোনো সারি ছুঁয়ে সব ইনপুট একসঙ্গে বসান।',
    always_1: 'Y সবসময় 1 (টটোলজি)।',
    always_0: 'Y সবসময় 0 (কন্ট্রাডিকশন)।',
    ones_in: '{n}টি সারির মধ্যে {k}টিতে Y = 1:',
    err_empty: 'শুরু করতে একটি এক্সপ্রেশন লিখুন, যেমন A·B + C।',
    err_unknown: 'অচেনা অক্ষর “{ch}”। শুধু A, B, C, D আর E ভেরিয়েবল ব্যবহার করুন।',
    err_symbol: '{n} নম্বর জায়গার চিহ্ন “{ch}” বোঝা গেল না।',
    err_close: '{n} নম্বর জায়গায় খোলা বন্ধনী বন্ধ হয়নি। একটি “)” যোগ করুন।',
    err_extra_close: '{n} নম্বর জায়গায় একটি “)” বেশি আছে।',
    err_operand: '{n} নম্বর জায়গায় কিছু বাদ পড়েছে। সেখানে একটি ভেরিয়েবল, 0, 1 বা “(” দিন।',
    err_end: 'এক্সপ্রেশন অসম্পূর্ণ। শেষ চিহ্নের পরে একটি ভেরিয়েবল যোগ করুন।',
    err_too_long: 'এক্সপ্রেশনটি খুব লম্বা। {n} অক্ষরের মধ্যে রাখুন।',
    equiv_title: 'দুটি এক্সপ্রেশন কি সমান?',
    equiv_intro: 'দুটি এক্সপ্রেশন লিখুন বা একটি নিয়ম বেছে নিন। অ্যাপ ট্রুথ টেবিলের প্রতিটি সারি যাচাই করে।',
    try_law: 'একটি নিয়ম চেষ্টা করুন:',
    law_dm1: 'ডি মরগানের সূত্র 1', law_dm2: 'ডি মরগানের সূত্র 2',
    law_abs1: 'শোষণ সূত্র', law_abs2: 'শোষণ সূত্র (দ্বৈত)',
    law_dist1: 'বণ্টন সূত্র', law_dist2: 'বণ্টন সূত্র (দ্বৈত)',
    law_xor: 'AND, OR, NOT দিয়ে XOR', law_dneg: 'দুবার NOT', law_nand: 'NAND গেট দিয়ে NOT', law_mistake: 'একটি সাধারণ ভুল',
    expr1: 'প্রথম এক্সপ্রেশন', expr2: 'দ্বিতীয় এক্সপ্রেশন', check: 'যাচাই করুন',
    equiv_yes: 'সমান ✓ সব {n}টি সারিতে দুটোর আউটপুট একই।',
    equiv_no: 'সমান নয় ✗',
    equiv_detail: 'বিপরীত উদাহরণ: যখন {vals}, প্রথমটি দেয় {a} কিন্তু দ্বিতীয়টি দেয় {b}।',
    col_first: 'প্রথম', col_second: 'দ্বিতীয়', same: 'একই?',
    half_adder: 'হাফ অ্যাডার', full_adder: 'ফুল অ্যাডার', four_bit: '4-বিট অ্যাডার',
    ha_desc: 'হাফ অ্যাডার দুটি বিট, A আর B, যোগ করে। এটি একটি যোগফল বিট (S) আর একটি ক্যারি বিট (C) দেয়।',
    legend_ha: 'S = যোগফল (Sum), C = ক্যারি বা হাতে (Carry)',
    why_carry: 'ক্যারি কেন? বাইনারিতে 1 + 1 = 10। আমরা 0 লিখি আর 1 পরের ঘরে নিয়ে যাই, ঠিক যেমন দশমিকে 5 + 5 = 10।',
    fa_desc: 'ফুল অ্যাডার তিনটি বিট যোগ করে: A, B আর আগের ঘর থেকে আসা ক্যারি (Cin)। এটি দুটি হাফ অ্যাডার আর একটি OR গেট দিয়ে তৈরি।',
    legend_fa: 'Cin = আসা ক্যারি, S = যোগফল, Cout = যাওয়া ক্যারি',
    fa_how: 'তিনটি ইনপুটের অন্তত দুটি 1 হলে Cout = 1 হয়।',
    read_bin: 'ক্যারি আর যোগফল একসঙ্গে একটি বাইনারি সংখ্যা হিসেবে পড়ুন: {bin} = দশমিকে {d}।',
    four_desc: 'চারটি ফুল অ্যাডারের একটি শিকল দুটি 4-বিট সংখ্যা (0 থেকে 15) যোগ করে। প্রতিটি ক্যারি বাঁদিকের পরের ঘরে যায়, ঢেউয়ের মতো।',
    place_val: 'স্থানীয় মান', carry_row: 'ক্যারি',
    bit_aria: '{v}-এর {p}-এর ঘরের বিট {x}। বদলাতে চাপুন।',
    final_carry: 'শেষ ক্যারিটি উত্তরের পঞ্চম বিট হয়ে যায়।',
    tap_bits: 'সংখ্যা বদলাতে A আর B-এর বিট ছুঁয়ে দিন।',
    mode_fill: 'টেবিল পূরণ করুন', mode_name: 'গেট চিনুন',
    level: 'স্তর', easy: 'সহজ', medium: 'মাঝারি', hard: 'কঠিন', streak: 'টানা সঠিক', best: 'সেরা',
    fill_q: 'এর আউটপুট কলাম Y পূরণ করুন:',
    tap_cells: 'প্রতিটি ? ছুঁয়ে 0 বা 1 বেছে নিন, তারপর “যাচাই করুন” চাপুন।',
    cell_aria: 'সারি {n}: আউটপুট Y এখন {x}। বদলাতে চাপুন।',
    show_answer: 'উত্তর দেখান', new_question: 'নতুন প্রশ্ন',
    fill_all: 'আগে প্রতিটি সারি পূরণ করুন।',
    all_right: 'সব {n}টি সারি সঠিক। দারুণ!',
    some_wrong: '{n}টির মধ্যে {k}টি সারি সঠিক। লালগুলো ঠিক করে আবার যাচাই করুন।',
    answer_shown: 'এই হলো উত্তর। ভালো করে দেখুন, তারপর নতুন প্রশ্ন নিন।',
    name_q: 'কোন গেট এই ট্রুথ টেবিল দেয়?',
    name_right: 'হ্যাঁ! এটি {g} গেট।',
    name_wrong: 'ঠিক হয়নি। এটি {g} গেট।',
    ws_hint: 'এই স্তরের 8টি ট্রুথ টেবিল প্রশ্ন উত্তরমালা সহ প্রিন্ট করুন।',
    print_ws: 'ওয়ার্কশিট প্রিন্ট করুন', ws_title: 'লজিক গেট ওয়ার্কশিট',
    ws_intro: 'প্রতিটি ট্রুথ টেবিলের আউটপুট কলাম Y পূরণ করুন।',
    ws_name: 'নাম', ws_class: 'শ্রেণি', ws_date: 'তারিখ', answer_key: 'উত্তরমালা',
    help_title: 'কীভাবে ব্যবহার করবেন / ক্লাসের জন্য আইডিয়া',
    help_1: 'গেট: একটি গেট বেছে নিয়ে সুইচ ছুঁয়ে দিন। বাতি আউটপুট Y দেখায় আর ট্রুথ টেবিলের মিলে যাওয়া সারিটি জ্বলে ওঠে।',
    help_2: 'এক্সপ্রেশন ল্যাব: (A + B)·C\' বা NOT (A AND B)-এর মতো কিছু লিখুন। ধাপের কলাম সহ ট্রুথ টেবিল আর একটি সার্কিট পাবেন, যা সঙ্গে সঙ্গে পরীক্ষা করা যায়।',
    help_3: '“দুটি এক্সপ্রেশন কি সমান?” দিয়ে ডি মরগানের সূত্র প্রমাণ করুন। সমান না হলে অ্যাপ সেই সারিটি দেখায় যেখানে দুটো আলাদা।',
    help_4: 'অ্যাডার: দেখুন কম্পিউটার হাফ অ্যাডার আর ফুল অ্যাডার দিয়ে কীভাবে বাইনারি সংখ্যা যোগ করে, তারপর দুটি 4-বিট সংখ্যা যোগ করুন।',
    help_5: 'ক্লাসের খেলা “মানুষ লজিক গেট”: দুজন ছাত্রছাত্রী ইনপুট A আর B (হাত ওপরে = 1)। তৃতীয়জন গেট, নিয়ম 1 বললে তবেই হাত তোলে। পুরো ক্লাস স্মার্টবোর্ডে মিলিয়ে দেখে।',
    help_6: 'শিক্ষকদের জন্য: অনুশীলনে স্তর বেছে “ওয়ার্কশিট প্রিন্ট করুন” চাপুন, উত্তরমালা সহ 8টি প্রশ্ন পাবেন।'
  },

  mr: {
    app_title: 'लॉजिक गेट लॅब',
    intro: 'स्विच दाबून लॉजिक गेट कसे काम करतात ते पाहा, बूलियन एक्सप्रेशनपासून ट्रुथ टेबल आणि सर्किट बनवा, डी मॉर्गनसारखे नियम तपासा आणि सराव करा.',
    tab_gates: 'गेट', tab_expr: 'एक्सप्रेशन लॅब', tab_adders: 'ॲडर', tab_practice: 'सराव',
    choose_gate: 'गेट', inputs: 'इनपुट', n_inputs: '{n} इनपुट', one_input: '1 इनपुट', gate_name: '{g} गेट',
    tap_switch: 'स्विचला स्पर्श करून तो 0 आणि 1 मध्ये बदला. टेबलमधील ओळीला स्पर्श करून थेट त्या ओळीवर जा.',
    kbd_hint: 'कीबोर्डवर A, B किंवा C दाबूनही इनपुट बदलता येतात.',
    expression: 'बूलियन एक्सप्रेशन', rule: 'नियम', real_life: 'रोजच्या जीवनातील उदाहरण', truth_table: 'ट्रुथ टेबल (सत्यता सारणी)',
    rule_and: 'सर्व इनपुट 1 असतील तेव्हाच Y = 1 होतो.',
    rule_or: 'किमान एक इनपुट 1 असेल तर Y = 1 होतो.',
    rule_not: 'Y हा इनपुटच्या उलट असतो: 0 चा 1 होतो आणि 1 चा 0 होतो.',
    rule_nand: 'NOT + AND: सर्व इनपुट 1 असतील तेव्हाच Y = 0 होतो.',
    rule_nor: 'NOT + OR: सर्व इनपुट 0 असतील तेव्हाच Y = 1 होतो.',
    rule_xor: 'विषम संख्येने इनपुट 1 असतील तर Y = 1. दोन इनपुटमध्ये: दोन्ही वेगळे असतील तेव्हा.',
    rule_xnor: 'NOT + XOR: सम संख्येने इनपुट 1 असतील तर Y = 1. दोन इनपुटमध्ये: दोन्ही सारखे असतील तेव्हा.',
    life_and: 'छतावरचा पंखा तेव्हाच चालतो जेव्हा मेन स्विच आणि पंख्याचा स्विच दोन्ही चालू असतात.',
    life_or: 'ऑफिस किंवा स्टाफ रूम, कोणीही बटण दाबले तरी शाळेची घंटा वाजते.',
    life_not: 'घरातील इन्व्हर्टर वीज नसताना (लाईट गेल्यावर) सुरू होतो.',
    life_nand: 'गाडीचा सीट-बेल्ट अलार्म पुढचे दोन्ही सीट बेल्ट लावेपर्यंत वाजत राहतो.',
    life_nor: 'पाण्याची मोटर गच्चीवरची टाकी तेव्हाच भरते जेव्हा टाकी भरलेली नसते आणि व्होल्टेज कमी नसतो.',
    life_xor: 'जिन्यातील दिव्याला दोन स्विच असतात: वर किंवा खाली, कोणताही एक स्विच बदलला की दिवा बदलतो.',
    life_xnor: 'उत्तर तपासणारे यंत्र: तुमचे उत्तर आणि बरोबर उत्तर सारखे असले की हिरवा दिवा लागतो.',
    universal: 'NAND आणि NOR यांना युनिव्हर्सल गेट म्हणतात: फक्त NAND गेट (किंवा फक्त NOR गेट) वापरून कोणतेही सर्किट बनवता येते.',
    all_gates: 'सर्व गेट एका नजरेत',
    all_gates_hint: 'ठळक केलेली ओळ स्विच A आणि B शी जुळते. बदलण्यासाठी ओळीला स्पर्श करा.',
    sw_aria: 'इनपुट {v} आत्ता {x} आहे. बदलण्यासाठी दाबा.',
    out_aria: 'आउटपुट {v} आत्ता {x} आहे',
    expr_label: 'बूलियन एक्सप्रेशन लिहा',
    expr_help: 'A ते E हे व्हेरिएबल वापरा, सोबत AND, OR, NOT, XOR, NAND, NOR, XNOR किंवा चिन्हे · + \' ⊕ आणि कंस. AB म्हणजे A·B.',
    examples: 'उदाहरणे', backspace: 'एक अक्षर पुसा', copy_link: 'लिंक कॉपी करा',
    circuit: 'सर्किट आकृती',
    circuit_hint: 'आकृतीतील इनपुट (A, B…) किंवा वरच्या बटणाला स्पर्श करून बदला. हिरव्या तारेत 1, राखाडी तारेत 0 असतो.',
    too_big: 'हे एक्सप्रेशन नीट काढण्यासाठी खूप मोठे आहे. ट्रुथ टेबल तरीही चालते.',
    no_inputs: 'एकही व्हेरिएबल नाही: आउटपुट कधीच बदलणार नाही.',
    show_steps: 'मधल्या पायऱ्यांचे कॉलम दाखवा',
    row_hint: 'ओळीला स्पर्श करून सर्व इनपुट एकदम सेट करा.',
    always_1: 'Y नेहमी 1 असतो (टॉटोलॉजी).',
    always_0: 'Y नेहमी 0 असतो (कॉन्ट्राडिक्शन).',
    ones_in: '{n} पैकी {k} ओळींमध्ये Y = 1:',
    err_empty: 'सुरू करण्यासाठी एक्सप्रेशन लिहा, उदा. A·B + C.',
    err_unknown: 'अनोळखी अक्षर “{ch}”. फक्त A, B, C, D आणि E हे व्हेरिएबल वापरा.',
    err_symbol: 'जागा {n} वरील “{ch}” हे चिन्ह समजले नाही.',
    err_close: 'जागा {n} वर उघडलेला कंस बंद झाला नाही. “)” जोडा.',
    err_extra_close: 'जागा {n} वर एक “)” जास्त आहे.',
    err_operand: 'जागा {n} वर काहीतरी राहिले आहे. तिथे व्हेरिएबल, 0, 1 किंवा “(” लिहा.',
    err_end: 'एक्सप्रेशन अर्धवट आहे. शेवटच्या चिन्हानंतर एक व्हेरिएबल जोडा.',
    err_too_long: 'एक्सप्रेशन खूप लांब आहे. ते {n} अक्षरांपेक्षा लहान ठेवा.',
    equiv_title: 'दोन एक्सप्रेशन समान आहेत का?',
    equiv_intro: 'दोन एक्सप्रेशन लिहा किंवा एखादा नियम निवडा. ॲप ट्रुथ टेबलची प्रत्येक ओळ तपासते.',
    try_law: 'एखादा नियम वापरून पाहा:',
    law_dm1: 'डी मॉर्गनचा नियम 1', law_dm2: 'डी मॉर्गनचा नियम 2',
    law_abs1: 'शोषण नियम', law_abs2: 'शोषण नियम (द्वैत)',
    law_dist1: 'वितरण नियम', law_dist2: 'वितरण नियम (द्वैत)',
    law_xor: 'AND, OR, NOT ने XOR', law_dneg: 'दुहेरी NOT', law_nand: 'NAND गेटने NOT', law_mistake: 'एक नेहमीची चूक',
    expr1: 'पहिले एक्सप्रेशन', expr2: 'दुसरे एक्सप्रेशन', check: 'तपासा',
    equiv_yes: 'समान ✓ सर्व {n} ओळींमध्ये दोघांचा आउटपुट सारखा आहे.',
    equiv_no: 'समान नाहीत ✗',
    equiv_detail: 'प्रतिउदाहरण: जेव्हा {vals}, तेव्हा पहिले {a} देते पण दुसरे {b} देते.',
    col_first: 'पहिले', col_second: 'दुसरे', same: 'सारखे?',
    half_adder: 'हाफ ॲडर', full_adder: 'फुल ॲडर', four_bit: '4-बिट ॲडर',
    ha_desc: 'हाफ ॲडर A आणि B हे दोन बिट जोडतो. तो एक बेरीज बिट (S) आणि एक हातचा बिट (C) देतो.',
    legend_ha: 'S = बेरीज (Sum), C = हातचा (Carry)',
    why_carry: 'हातचा का? बायनरीमध्ये 1 + 1 = 10. आपण 0 लिहितो आणि 1 पुढच्या स्थानावर नेतो, अगदी दशमानमध्ये 5 + 5 = 10 सारखे.',
    fa_desc: 'फुल ॲडर तीन बिट जोडतो: A, B आणि मागच्या स्थानावरून आलेला हातचा (Cin). तो दोन हाफ ॲडर आणि एक OR गेट यांपासून बनतो.',
    legend_fa: 'Cin = येणारा हातचा, S = बेरीज, Cout = जाणारा हातचा',
    fa_how: 'तीनपैकी किमान दोन इनपुट 1 असतील तर Cout = 1 होतो.',
    read_bin: 'हातचा आणि बेरीज एकत्र एक बायनरी संख्या म्हणून वाचा: {bin} = दशमानमध्ये {d}.',
    four_desc: 'चार फुल ॲडरची साखळी दोन 4-बिट संख्या (0 ते 15) जोडते. प्रत्येक हातचा डावीकडच्या पुढच्या स्थानावर जातो, लाटेसारखा.',
    place_val: 'स्थानिक किंमत', carry_row: 'हातचा',
    bit_aria: '{v} मधील {p} चा बिट {x} आहे. बदलण्यासाठी दाबा.',
    final_carry: 'शेवटचा हातचा उत्तराचा पाचवा बिट बनतो.',
    tap_bits: 'संख्या बदलण्यासाठी A आणि B च्या बिटला स्पर्श करा.',
    mode_fill: 'टेबल पूर्ण करा', mode_name: 'गेट ओळखा',
    level: 'पातळी', easy: 'सोपे', medium: 'मध्यम', hard: 'कठीण', streak: 'सलग बरोबर', best: 'सर्वोत्तम',
    fill_q: 'यासाठी आउटपुट कॉलम Y भरा:',
    tap_cells: 'प्रत्येक ? ला स्पर्श करून 0 किंवा 1 निवडा, मग “तपासा” दाबा.',
    cell_aria: 'ओळ {n}: आउटपुट Y आत्ता {x} आहे. बदलण्यासाठी दाबा.',
    show_answer: 'उत्तर दाखवा', new_question: 'नवीन प्रश्न',
    fill_all: 'आधी प्रत्येक ओळ भरा.',
    all_right: 'सर्व {n} ओळी बरोबर आहेत. छान!',
    some_wrong: '{n} पैकी {k} ओळी बरोबर आहेत. लाल ओळी दुरुस्त करून पुन्हा तपासा.',
    answer_shown: 'हे घ्या उत्तर. नीट पाहा, मग नवीन प्रश्न सोडवा.',
    name_q: 'कोणता गेट हे ट्रुथ टेबल देतो?',
    name_right: 'हो! हा {g} गेट आहे.',
    name_wrong: 'बरोबर नाही. हा {g} गेट आहे.',
    ws_hint: 'या पातळीचे 8 ट्रुथ टेबल प्रश्न उत्तरसूचीसह प्रिंट करा.',
    print_ws: 'वर्कशीट प्रिंट करा', ws_title: 'लॉजिक गेट वर्कशीट',
    ws_intro: 'प्रत्येक ट्रुथ टेबलचा आउटपुट कॉलम Y पूर्ण करा.',
    ws_name: 'नाव', ws_class: 'इयत्ता', ws_date: 'दिनांक', answer_key: 'उत्तरसूची',
    help_title: 'कसे वापरावे / वर्गासाठी कल्पना',
    help_1: 'गेट: एखादा गेट निवडा आणि स्विचला स्पर्श करा. दिवा आउटपुट Y दाखवतो आणि ट्रुथ टेबलमधील जुळणारी ओळ उजळते.',
    help_2: 'एक्सप्रेशन लॅब: (A + B)·C\' किंवा NOT (A AND B) असे काहीतरी लिहा. पायऱ्यांच्या कॉलमसह ट्रुथ टेबल आणि लगेच तपासता येणारे सर्किट मिळेल.',
    help_3: '“दोन एक्सप्रेशन समान आहेत का?” वापरून डी मॉर्गनचे नियम सिद्ध करा. समान नसल्यास ॲप ती ओळ दाखवते जिथे ते वेगळे आहेत.',
    help_4: 'ॲडर: संगणक हाफ ॲडर आणि फुल ॲडरने बायनरी संख्या कशा जोडतो ते पाहा, मग दोन 4-बिट संख्या जोडा.',
    help_5: 'वर्गातील उपक्रम “माणूस लॉजिक गेट”: दोन विद्यार्थी इनपुट A आणि B बनतात (हात वर = 1). तिसरा विद्यार्थी गेट बनतो आणि नियमानुसार 1 असेल तेव्हाच हात वर करतो. सगळा वर्ग स्मार्टबोर्डवर तपासतो.',
    help_6: 'शिक्षकांसाठी: सरावमध्ये पातळी निवडा आणि “वर्कशीट प्रिंट करा” दाबा, उत्तरसूचीसह 8 प्रश्न मिळतील.'
  },

  gu: {
    app_title: 'લૉજિક ગેટ લૅબ',
    intro: 'સ્વિચ દબાવીને જુઓ કે લૉજિક ગેટ કેવી રીતે કામ કરે છે, બુલિયન એક્સપ્રેશનમાંથી ટ્રુથ ટેબલ અને સર્કિટ બનાવો, ડી મોર્ગન જેવા નિયમો ચકાસો અને મહાવરો કરો.',
    tab_gates: 'ગેટ', tab_expr: 'એક્સપ્રેશન લૅબ', tab_adders: 'ઍડર', tab_practice: 'મહાવરો',
    choose_gate: 'ગેટ', inputs: 'ઇનપુટ', n_inputs: '{n} ઇનપુટ', one_input: '1 ઇનપુટ', gate_name: '{g} ગેટ',
    tap_switch: 'સ્વિચને સ્પર્શ કરીને 0 અને 1 વચ્ચે બદલો. ટેબલની કોઈ હરોળને સ્પર્શ કરીને સીધા ત્યાં જાઓ.',
    kbd_hint: 'કીબોર્ડ પર A, B કે C દબાવીને પણ ઇનપુટ બદલી શકાય છે.',
    expression: 'બુલિયન એક્સપ્રેશન', rule: 'નિયમ', real_life: 'રોજિંદા જીવનનું ઉદાહરણ', truth_table: 'ટ્રુથ ટેબલ (સત્યાર્થ કોષ્ટક)',
    rule_and: 'બધા ઇનપુટ 1 હોય ત્યારે જ Y = 1 થાય છે.',
    rule_or: 'ઓછામાં ઓછો એક ઇનપુટ 1 હોય તો Y = 1 થાય છે.',
    rule_not: 'Y ઇનપુટથી ઊલટો હોય છે: 0 નો 1 થાય અને 1 નો 0 થાય.',
    rule_nand: 'NOT + AND: બધા ઇનપુટ 1 હોય ત્યારે જ Y = 0 થાય છે.',
    rule_nor: 'NOT + OR: બધા ઇનપુટ 0 હોય ત્યારે જ Y = 1 થાય છે.',
    rule_xor: 'એકી સંખ્યામાં ઇનપુટ 1 હોય તો Y = 1. બે ઇનપુટમાં: બંને જુદા હોય ત્યારે.',
    rule_xnor: 'NOT + XOR: બેકી સંખ્યામાં ઇનપુટ 1 હોય તો Y = 1. બે ઇનપુટમાં: બંને સરખા હોય ત્યારે.',
    life_and: 'છતનો પંખો ત્યારે જ ચાલે જ્યારે મેઇન સ્વિચ અને પંખાની સ્વિચ બંને ચાલુ હોય.',
    life_or: 'ઑફિસ કે સ્ટાફ રૂમ, કોઈ પણ બટન દબાવે તો શાળાનો ઘંટ વાગે છે.',
    life_not: 'ઘરનું ઇન્વર્ટર ત્યારે ચાલુ થાય જ્યારે વીજળી ન હોય (લાઇટ જાય ત્યારે).',
    life_nand: 'કારનું સીટ-બેલ્ટ એલાર્મ આગળના બંને સીટ બેલ્ટ બંધાય નહીં ત્યાં સુધી વાગતું રહે છે.',
    life_nor: 'પાણીની મોટર અગાસી પરની ટાંકી ત્યારે જ ભરે જ્યારે ટાંકી ભરેલી ન હોય અને વોલ્ટેજ ઓછો ન હોય.',
    life_xor: 'દાદરની લાઇટમાં બે સ્વિચ હોય છે: ઉપર કે નીચે, કોઈ પણ એક સ્વિચ બદલો તો લાઇટ બદલાય.',
    life_xnor: 'જવાબ ચકાસતું યંત્ર: તમારો જવાબ અને સાચો જવાબ સરખા હોય ત્યારે લીલી લાઇટ થાય.',
    universal: 'NAND અને NOR ને યુનિવર્સલ ગેટ કહે છે: ફક્ત NAND ગેટ (અથવા ફક્ત NOR ગેટ) વાપરીને કોઈ પણ સર્કિટ બનાવી શકાય.',
    all_gates: 'બધા ગેટ એક નજરે',
    all_gates_hint: 'હાઇલાઇટ કરેલી હરોળ સ્વિચ A અને B સાથે મેળ ખાય છે. બદલવા માટે હરોળને સ્પર્શ કરો.',
    sw_aria: 'ઇનપુટ {v} હમણાં {x} છે. બદલવા દબાવો.',
    out_aria: 'આઉટપુટ {v} હમણાં {x} છે',
    expr_label: 'બુલિયન એક્સપ્રેશન લખો',
    expr_help: 'A થી E ચલ વાપરો, સાથે AND, OR, NOT, XOR, NAND, NOR, XNOR અથવા ચિહ્નો · + \' ⊕ અને કૌંસ. AB એટલે A·B.',
    examples: 'ઉદાહરણો', backspace: 'એક અક્ષર ભૂંસો', copy_link: 'લિંક કૉપિ કરો',
    circuit: 'સર્કિટ આકૃતિ',
    circuit_hint: 'આકૃતિમાં કોઈ ઇનપુટ (A, B…) કે ઉપરના બટનને સ્પર્શ કરીને બદલો. લીલા તારમાં 1, રાખોડી તારમાં 0 હોય છે.',
    too_big: 'આ એક્સપ્રેશન વ્યવસ્થિત દોરવા માટે બહુ મોટું છે. ટ્રુથ ટેબલ તો પણ કામ કરે છે.',
    no_inputs: 'કોઈ ચલ નથી: આઉટપુટ ક્યારેય બદલાશે નહીં.',
    show_steps: 'વચ્ચેનાં પગલાંનાં કૉલમ બતાવો',
    row_hint: 'હરોળને સ્પર્શ કરીને બધા ઇનપુટ એકસાથે ગોઠવો.',
    always_1: 'Y હંમેશાં 1 છે (ટોટોલોજી).',
    always_0: 'Y હંમેશાં 0 છે (કૉન્ટ્રાડિક્શન).',
    ones_in: '{n} માંથી {k} હરોળમાં Y = 1:',
    err_empty: 'શરૂ કરવા એક્સપ્રેશન લખો, જેમ કે A·B + C.',
    err_unknown: 'અજાણ્યો અક્ષર “{ch}”. ફક્ત A, B, C, D અને E ચલ વાપરો.',
    err_symbol: 'સ્થાન {n} પરનું ચિહ્ન “{ch}” સમજાયું નહીં.',
    err_close: 'સ્થાન {n} પર ખૂલેલો કૌંસ બંધ થયો નથી. “)” ઉમેરો.',
    err_extra_close: 'સ્થાન {n} પર એક “)” વધારાનો છે.',
    err_operand: 'સ્થાન {n} પર કંઈક ખૂટે છે. ત્યાં ચલ, 0, 1 કે “(” લખો.',
    err_end: 'એક્સપ્રેશન અધૂરું છે. છેલ્લા ચિહ્ન પછી એક ચલ ઉમેરો.',
    err_too_long: 'એક્સપ્રેશન બહુ લાંબું છે. તેને {n} અક્ષરથી ઓછું રાખો.',
    equiv_title: 'શું બે એક્સપ્રેશન સરખાં છે?',
    equiv_intro: 'બે એક્સપ્રેશન લખો અથવા કોઈ નિયમ પસંદ કરો. ઍપ ટ્રુથ ટેબલની દરેક હરોળ ચકાસે છે.',
    try_law: 'કોઈ નિયમ અજમાવો:',
    law_dm1: 'ડી મોર્ગનનો નિયમ 1', law_dm2: 'ડી મોર્ગનનો નિયમ 2',
    law_abs1: 'શોષણ નિયમ', law_abs2: 'શોષણ નિયમ (દ્વૈત)',
    law_dist1: 'વિભાજન નિયમ', law_dist2: 'વિભાજન નિયમ (દ્વૈત)',
    law_xor: 'AND, OR, NOT વડે XOR', law_dneg: 'બેવડો NOT', law_nand: 'NAND ગેટ વડે NOT', law_mistake: 'એક સામાન્ય ભૂલ',
    expr1: 'પહેલું એક્સપ્રેશન', expr2: 'બીજું એક્સપ્રેશન', check: 'ચકાસો',
    equiv_yes: 'સરખાં છે ✓ બધી {n} હરોળમાં બંનેનો આઉટપુટ સરખો છે.',
    equiv_no: 'સરખાં નથી ✗',
    equiv_detail: 'પ્રતિ-ઉદાહરણ: જ્યારે {vals}, ત્યારે પહેલું {a} આપે છે પણ બીજું {b} આપે છે.',
    col_first: 'પહેલું', col_second: 'બીજું', same: 'સરખું?',
    half_adder: 'હાફ ઍડર', full_adder: 'ફુલ ઍડર', four_bit: '4-બિટ ઍડર',
    ha_desc: 'હાફ ઍડર બે બિટ A અને B નો સરવાળો કરે છે. તે સરવાળાનો બિટ (S) અને વદ્દીનો બિટ (C) આપે છે.',
    legend_ha: 'S = સરવાળો (Sum), C = વદ્દી (Carry)',
    why_carry: 'વદ્દી કેમ? બાઇનરીમાં 1 + 1 = 10. આપણે 0 લખીએ અને 1 આગળના સ્થાને લઈ જઈએ, બરાબર દશાંશમાં 5 + 5 = 10 જેવું.',
    fa_desc: 'ફુલ ઍડર ત્રણ બિટનો સરવાળો કરે છે: A, B અને પાછલા સ્થાનેથી આવેલી વદ્દી (Cin). તે બે હાફ ઍડર અને એક OR ગેટથી બને છે.',
    legend_fa: 'Cin = આવતી વદ્દી, S = સરવાળો, Cout = જતી વદ્દી',
    fa_how: 'ત્રણમાંથી ઓછામાં ઓછા બે ઇનપુટ 1 હોય તો Cout = 1 થાય.',
    read_bin: 'વદ્દી અને સરવાળો સાથે એક બાઇનરી સંખ્યા તરીકે વાંચો: {bin} = દશાંશમાં {d}.',
    four_desc: 'ચાર ફુલ ઍડરની સાંકળ બે 4-બિટ સંખ્યાઓ (0 થી 15) નો સરવાળો કરે છે. દરેક વદ્દી ડાબી બાજુના આગળના સ્થાને જાય છે, લહેરની જેમ.',
    place_val: 'સ્થાનકિંમત', carry_row: 'વદ્દી',
    bit_aria: '{v} માં {p} નો બિટ {x} છે. બદલવા દબાવો.',
    final_carry: 'છેલ્લી વદ્દી જવાબનો પાંચમો બિટ બને છે.',
    tap_bits: 'સંખ્યાઓ બદલવા A અને B ના બિટને સ્પર્શ કરો.',
    mode_fill: 'ટેબલ પૂરું કરો', mode_name: 'ગેટ ઓળખો',
    level: 'સ્તર', easy: 'સહેલું', medium: 'મધ્યમ', hard: 'અઘરું', streak: 'સતત સાચા', best: 'શ્રેષ્ઠ',
    fill_q: 'આના માટે આઉટપુટ કૉલમ Y ભરો:',
    tap_cells: 'દરેક ? ને સ્પર્શ કરીને 0 કે 1 પસંદ કરો, પછી “ચકાસો” દબાવો.',
    cell_aria: 'હરોળ {n}: આઉટપુટ Y હમણાં {x} છે. બદલવા દબાવો.',
    show_answer: 'જવાબ બતાવો', new_question: 'નવો પ્રશ્ન',
    fill_all: 'પહેલાં દરેક હરોળ ભરો.',
    all_right: 'બધી {n} હરોળ સાચી છે. શાબાશ!',
    some_wrong: '{n} માંથી {k} હરોળ સાચી છે. લાલ હરોળ સુધારીને ફરી ચકાસો.',
    answer_shown: 'આ રહ્યો જવાબ. ધ્યાનથી જુઓ, પછી નવો પ્રશ્ન કરો.',
    name_q: 'કયો ગેટ આ ટ્રુથ ટેબલ આપે છે?',
    name_right: 'હા! આ {g} ગેટ છે.',
    name_wrong: 'બરાબર નથી. આ {g} ગેટ છે.',
    ws_hint: 'આ સ્તરના 8 ટ્રુથ ટેબલ પ્રશ્નો જવાબ-સૂચિ સાથે પ્રિન્ટ કરો.',
    print_ws: 'વર્કશીટ પ્રિન્ટ કરો', ws_title: 'લૉજિક ગેટ વર્કશીટ',
    ws_intro: 'દરેક ટ્રુથ ટેબલનો આઉટપુટ કૉલમ Y પૂરો કરો.',
    ws_name: 'નામ', ws_class: 'ધોરણ', ws_date: 'તારીખ', answer_key: 'જવાબ-સૂચિ',
    help_title: 'કેવી રીતે વાપરવું / વર્ગખંડ માટે વિચારો',
    help_1: 'ગેટ: કોઈ ગેટ પસંદ કરો અને સ્વિચને સ્પર્શ કરો. બલ્બ આઉટપુટ Y બતાવે છે અને ટ્રુથ ટેબલની મળતી હરોળ ચમકે છે.',
    help_2: 'એક્સપ્રેશન લૅબ: (A + B)·C\' કે NOT (A AND B) જેવું કંઈક લખો. પગલાંનાં કૉલમ સાથે ટ્રુથ ટેબલ અને તરત ચકાસી શકાય એવી સર્કિટ મળશે.',
    help_3: '“શું બે એક્સપ્રેશન સરખાં છે?” વડે ડી મોર્ગનના નિયમો સાબિત કરો. સરખાં ન હોય તો ઍપ એ હરોળ બતાવે છે જ્યાં તેઓ જુદાં પડે છે.',
    help_4: 'ઍડર: કમ્પ્યુટર હાફ ઍડર અને ફુલ ઍડર વડે બાઇનરી સંખ્યાઓનો સરવાળો કેવી રીતે કરે છે તે જુઓ, પછી બે 4-બિટ સંખ્યાઓ ઉમેરો.',
    help_5: 'વર્ગ પ્રવૃત્તિ “માનવ લૉજિક ગેટ”: બે વિદ્યાર્થીઓ ઇનપુટ A અને B બને (હાથ ઊંચો = 1). ત્રીજો વિદ્યાર્થી ગેટ બને અને નિયમ 1 કહે ત્યારે જ હાથ ઊંચો કરે. આખો વર્ગ સ્માર્ટબોર્ડ પર ચકાસે.',
    help_6: 'શિક્ષકો માટે: મહાવરામાં સ્તર પસંદ કરો અને “વર્કશીટ પ્રિન્ટ કરો” દબાવો, જવાબ-સૂચિ સાથે 8 પ્રશ્નો મળશે.'
  },

  pa: {
    app_title: 'ਲੌਜਿਕ ਗੇਟ ਲੈਬ',
    intro: 'ਸਵਿੱਚ ਦਬਾ ਕੇ ਵੇਖੋ ਕਿ ਲੌਜਿਕ ਗੇਟ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਨ, ਬੂਲੀਅਨ ਐਕਸਪ੍ਰੈਸ਼ਨ ਤੋਂ ਟਰੁੱਥ ਟੇਬਲ ਅਤੇ ਸਰਕਟ ਬਣਾਓ, ਡੀ ਮੌਰਗਨ ਵਰਗੇ ਨਿਯਮ ਜਾਂਚੋ ਅਤੇ ਅਭਿਆਸ ਕਰੋ।',
    tab_gates: 'ਗੇਟ', tab_expr: 'ਐਕਸਪ੍ਰੈਸ਼ਨ ਲੈਬ', tab_adders: 'ਐਡਰ', tab_practice: 'ਅਭਿਆਸ',
    choose_gate: 'ਗੇਟ', inputs: 'ਇਨਪੁੱਟ', n_inputs: '{n} ਇਨਪੁੱਟ', one_input: '1 ਇਨਪੁੱਟ', gate_name: '{g} ਗੇਟ',
    tap_switch: 'ਸਵਿੱਚ ਨੂੰ ਛੂਹ ਕੇ 0 ਅਤੇ 1 ਵਿਚਕਾਰ ਬਦਲੋ। ਟੇਬਲ ਦੀ ਕਿਸੇ ਕਤਾਰ ਨੂੰ ਛੂਹ ਕੇ ਸਿੱਧਾ ਉੱਥੇ ਜਾਓ।',
    kbd_hint: 'ਕੀਬੋਰਡ ’ਤੇ A, B ਜਾਂ C ਦਬਾ ਕੇ ਵੀ ਇਨਪੁੱਟ ਬਦਲ ਸਕਦੇ ਹੋ।',
    expression: 'ਬੂਲੀਅਨ ਐਕਸਪ੍ਰੈਸ਼ਨ', rule: 'ਨਿਯਮ', real_life: 'ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੀ ਉਦਾਹਰਨ', truth_table: 'ਟਰੁੱਥ ਟੇਬਲ (ਸੱਚ ਸਾਰਣੀ)',
    rule_and: 'ਸਾਰੇ ਇਨਪੁੱਟ 1 ਹੋਣ ਤਾਂ ਹੀ Y = 1 ਹੁੰਦਾ ਹੈ।',
    rule_or: 'ਘੱਟੋ-ਘੱਟ ਇੱਕ ਇਨਪੁੱਟ 1 ਹੋਵੇ ਤਾਂ Y = 1 ਹੁੰਦਾ ਹੈ।',
    rule_not: 'Y ਇਨਪੁੱਟ ਦਾ ਉਲਟ ਹੁੰਦਾ ਹੈ: 0 ਬਣਦਾ ਹੈ 1, ਅਤੇ 1 ਬਣਦਾ ਹੈ 0।',
    rule_nand: 'NOT + AND: ਸਾਰੇ ਇਨਪੁੱਟ 1 ਹੋਣ ਤਾਂ ਹੀ Y = 0 ਹੁੰਦਾ ਹੈ।',
    rule_nor: 'NOT + OR: ਸਾਰੇ ਇਨਪੁੱਟ 0 ਹੋਣ ਤਾਂ ਹੀ Y = 1 ਹੁੰਦਾ ਹੈ।',
    rule_xor: 'ਟਾਂਕ ਗਿਣਤੀ ਵਿੱਚ ਇਨਪੁੱਟ 1 ਹੋਣ ਤਾਂ Y = 1। ਦੋ ਇਨਪੁੱਟ ਵਿੱਚ: ਜਦੋਂ ਦੋਵੇਂ ਵੱਖਰੇ ਹੋਣ।',
    rule_xnor: 'NOT + XOR: ਜਿਸਤ ਗਿਣਤੀ ਵਿੱਚ ਇਨਪੁੱਟ 1 ਹੋਣ ਤਾਂ Y = 1। ਦੋ ਇਨਪੁੱਟ ਵਿੱਚ: ਜਦੋਂ ਦੋਵੇਂ ਇੱਕੋ ਜਿਹੇ ਹੋਣ।',
    life_and: 'ਛੱਤ ਵਾਲਾ ਪੱਖਾ ਤਾਂ ਹੀ ਚੱਲਦਾ ਹੈ ਜਦੋਂ ਮੇਨ ਸਵਿੱਚ ਅਤੇ ਪੱਖੇ ਦਾ ਸਵਿੱਚ ਦੋਵੇਂ ਚਾਲੂ ਹੋਣ।',
    life_or: 'ਦਫ਼ਤਰ ਜਾਂ ਸਟਾਫ਼ ਰੂਮ, ਕੋਈ ਵੀ ਬਟਨ ਦਬਾਏ ਤਾਂ ਸਕੂਲ ਦੀ ਘੰਟੀ ਵੱਜਦੀ ਹੈ।',
    life_not: 'ਘਰ ਦਾ ਇਨਵਰਟਰ ਉਦੋਂ ਚਾਲੂ ਹੁੰਦਾ ਹੈ ਜਦੋਂ ਬਿਜਲੀ ਨਹੀਂ ਹੁੰਦੀ (ਬਿਜਲੀ ਜਾਣ ’ਤੇ)।',
    life_nand: 'ਕਾਰ ਦਾ ਸੀਟ-ਬੈਲਟ ਅਲਾਰਮ ਉਦੋਂ ਤੱਕ ਵੱਜਦਾ ਰਹਿੰਦਾ ਹੈ ਜਦੋਂ ਤੱਕ ਅਗਲੀਆਂ ਦੋਵੇਂ ਸੀਟ ਬੈਲਟਾਂ ਨਾ ਲੱਗ ਜਾਣ।',
    life_nor: 'ਪਾਣੀ ਦੀ ਮੋਟਰ ਛੱਤ ਵਾਲੀ ਟੈਂਕੀ ਤਾਂ ਹੀ ਭਰਦੀ ਹੈ ਜਦੋਂ ਟੈਂਕੀ ਭਰੀ ਨਾ ਹੋਵੇ ਅਤੇ ਵੋਲਟੇਜ ਘੱਟ ਨਾ ਹੋਵੇ।',
    life_xor: 'ਪੌੜੀਆਂ ਦੀ ਲਾਈਟ ਦੇ ਦੋ ਸਵਿੱਚ: ਉੱਪਰ ਜਾਂ ਹੇਠਾਂ, ਕੋਈ ਵੀ ਇੱਕ ਸਵਿੱਚ ਬਦਲੋ ਤਾਂ ਲਾਈਟ ਬਦਲ ਜਾਂਦੀ ਹੈ।',
    life_xnor: 'ਜਵਾਬ ਜਾਂਚਣ ਵਾਲੀ ਮਸ਼ੀਨ: ਜਦੋਂ ਤੁਹਾਡਾ ਜਵਾਬ ਅਤੇ ਸਹੀ ਜਵਾਬ ਇੱਕੋ ਜਿਹੇ ਹੋਣ, ਹਰੀ ਬੱਤੀ ਜਗਦੀ ਹੈ।',
    universal: 'NAND ਅਤੇ NOR ਨੂੰ ਯੂਨੀਵਰਸਲ ਗੇਟ ਕਹਿੰਦੇ ਹਨ: ਸਿਰਫ਼ NAND ਗੇਟਾਂ (ਜਾਂ ਸਿਰਫ਼ NOR ਗੇਟਾਂ) ਨਾਲ ਕੋਈ ਵੀ ਸਰਕਟ ਬਣ ਸਕਦਾ ਹੈ।',
    all_gates: 'ਸਾਰੇ ਗੇਟ ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ',
    all_gates_hint: 'ਹਾਈਲਾਈਟ ਕੀਤੀ ਕਤਾਰ ਸਵਿੱਚ A ਅਤੇ B ਨਾਲ ਮਿਲਦੀ ਹੈ। ਬਦਲਣ ਲਈ ਕਤਾਰ ਨੂੰ ਛੂਹੋ।',
    sw_aria: 'ਇਨਪੁੱਟ {v} ਹੁਣ {x} ਹੈ। ਬਦਲਣ ਲਈ ਦਬਾਓ।',
    out_aria: 'ਆਉਟਪੁੱਟ {v} ਹੁਣ {x} ਹੈ',
    expr_label: 'ਬੂਲੀਅਨ ਐਕਸਪ੍ਰੈਸ਼ਨ ਲਿਖੋ',
    expr_help: 'A ਤੋਂ E ਤੱਕ ਵੇਰੀਏਬਲ ਲਓ, ਨਾਲ AND, OR, NOT, XOR, NAND, NOR, XNOR ਜਾਂ ਚਿੰਨ੍ਹ · + \' ⊕ ਅਤੇ ਬਰੈਕਟ। AB ਦਾ ਮਤਲਬ ਹੈ A·B।',
    examples: 'ਉਦਾਹਰਨਾਂ', backspace: 'ਇੱਕ ਅੱਖਰ ਮਿਟਾਓ', copy_link: 'ਲਿੰਕ ਕਾਪੀ ਕਰੋ',
    circuit: 'ਸਰਕਟ ਡਾਇਗ੍ਰਾਮ',
    circuit_hint: 'ਡਾਇਗ੍ਰਾਮ ਵਿੱਚ ਕਿਸੇ ਇਨਪੁੱਟ (A, B…) ਜਾਂ ਉੱਪਰਲੇ ਬਟਨ ਨੂੰ ਛੂਹ ਕੇ ਬਦਲੋ। ਹਰੀ ਤਾਰ ਵਿੱਚ 1, ਸਲੇਟੀ ਤਾਰ ਵਿੱਚ 0 ਹੁੰਦਾ ਹੈ।',
    too_big: 'ਇਹ ਐਕਸਪ੍ਰੈਸ਼ਨ ਸਾਫ਼ ਬਣਾਉਣ ਲਈ ਬਹੁਤ ਵੱਡਾ ਹੈ। ਟਰੁੱਥ ਟੇਬਲ ਫਿਰ ਵੀ ਕੰਮ ਕਰਦੀ ਹੈ।',
    no_inputs: 'ਕੋਈ ਵੇਰੀਏਬਲ ਨਹੀਂ: ਆਉਟਪੁੱਟ ਕਦੇ ਨਹੀਂ ਬਦਲੇਗਾ।',
    show_steps: 'ਵਿਚਕਾਰਲੇ ਕਦਮਾਂ ਦੇ ਕਾਲਮ ਦਿਖਾਓ',
    row_hint: 'ਕਤਾਰ ਨੂੰ ਛੂਹ ਕੇ ਸਾਰੇ ਇਨਪੁੱਟ ਇੱਕੋ ਵਾਰ ਸੈੱਟ ਕਰੋ।',
    always_1: 'Y ਹਮੇਸ਼ਾ 1 ਹੈ (ਟੌਟੋਲੋਜੀ)।',
    always_0: 'Y ਹਮੇਸ਼ਾ 0 ਹੈ (ਕੰਟਰਾਡਿਕਸ਼ਨ)।',
    ones_in: '{n} ਵਿੱਚੋਂ {k} ਕਤਾਰਾਂ ਵਿੱਚ Y = 1:',
    err_empty: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਐਕਸਪ੍ਰੈਸ਼ਨ ਲਿਖੋ, ਜਿਵੇਂ A·B + C।',
    err_unknown: 'ਅਣਜਾਣ ਅੱਖਰ “{ch}”। ਸਿਰਫ਼ A, B, C, D ਅਤੇ E ਵੇਰੀਏਬਲ ਵਰਤੋ।',
    err_symbol: 'ਥਾਂ {n} ’ਤੇ ਚਿੰਨ੍ਹ “{ch}” ਸਮਝ ਨਹੀਂ ਆਇਆ।',
    err_close: 'ਥਾਂ {n} ’ਤੇ ਖੁੱਲ੍ਹੀ ਬਰੈਕਟ ਬੰਦ ਨਹੀਂ ਹੋਈ। “)” ਜੋੜੋ।',
    err_extra_close: 'ਥਾਂ {n} ’ਤੇ ਇੱਕ “)” ਵਾਧੂ ਹੈ।',
    err_operand: 'ਥਾਂ {n} ’ਤੇ ਕੁਝ ਰਹਿ ਗਿਆ ਹੈ। ਉੱਥੇ ਵੇਰੀਏਬਲ, 0, 1 ਜਾਂ “(” ਲਿਖੋ।',
    err_end: 'ਐਕਸਪ੍ਰੈਸ਼ਨ ਅਧੂਰਾ ਹੈ। ਆਖ਼ਰੀ ਚਿੰਨ੍ਹ ਤੋਂ ਬਾਅਦ ਇੱਕ ਵੇਰੀਏਬਲ ਜੋੜੋ।',
    err_too_long: 'ਐਕਸਪ੍ਰੈਸ਼ਨ ਬਹੁਤ ਲੰਮਾ ਹੈ। ਇਸਨੂੰ {n} ਅੱਖਰਾਂ ਤੋਂ ਛੋਟਾ ਰੱਖੋ।',
    equiv_title: 'ਕੀ ਦੋ ਐਕਸਪ੍ਰੈਸ਼ਨ ਬਰਾਬਰ ਹਨ?',
    equiv_intro: 'ਦੋ ਐਕਸਪ੍ਰੈਸ਼ਨ ਲਿਖੋ ਜਾਂ ਕੋਈ ਨਿਯਮ ਚੁਣੋ। ਐਪ ਟਰੁੱਥ ਟੇਬਲ ਦੀ ਹਰ ਕਤਾਰ ਜਾਂਚਦੀ ਹੈ।',
    try_law: 'ਕੋਈ ਨਿਯਮ ਅਜ਼ਮਾਓ:',
    law_dm1: 'ਡੀ ਮੌਰਗਨ ਦਾ ਨਿਯਮ 1', law_dm2: 'ਡੀ ਮੌਰਗਨ ਦਾ ਨਿਯਮ 2',
    law_abs1: 'ਸੋਖਣ ਨਿਯਮ', law_abs2: 'ਸੋਖਣ ਨਿਯਮ (ਦੋਹਰਾ ਰੂਪ)',
    law_dist1: 'ਵੰਡ ਨਿਯਮ', law_dist2: 'ਵੰਡ ਨਿਯਮ (ਦੋਹਰਾ ਰੂਪ)',
    law_xor: 'AND, OR, NOT ਨਾਲ XOR', law_dneg: 'ਦੋਹਰਾ NOT', law_nand: 'NAND ਗੇਟ ਨਾਲ NOT', law_mistake: 'ਇੱਕ ਆਮ ਗ਼ਲਤੀ',
    expr1: 'ਪਹਿਲਾ ਐਕਸਪ੍ਰੈਸ਼ਨ', expr2: 'ਦੂਜਾ ਐਕਸਪ੍ਰੈਸ਼ਨ', check: 'ਜਾਂਚੋ',
    equiv_yes: 'ਬਰਾਬਰ ਹਨ ✓ ਸਾਰੀਆਂ {n} ਕਤਾਰਾਂ ਵਿੱਚ ਦੋਵਾਂ ਦਾ ਆਉਟਪੁੱਟ ਇੱਕੋ ਹੈ।',
    equiv_no: 'ਬਰਾਬਰ ਨਹੀਂ ✗',
    equiv_detail: 'ਉਲਟ ਉਦਾਹਰਨ: ਜਦੋਂ {vals}, ਪਹਿਲਾ {a} ਦਿੰਦਾ ਹੈ ਪਰ ਦੂਜਾ {b} ਦਿੰਦਾ ਹੈ।',
    col_first: 'ਪਹਿਲਾ', col_second: 'ਦੂਜਾ', same: 'ਇੱਕੋ?',
    half_adder: 'ਹਾਫ਼ ਐਡਰ', full_adder: 'ਫੁੱਲ ਐਡਰ', four_bit: '4-ਬਿੱਟ ਐਡਰ',
    ha_desc: 'ਹਾਫ਼ ਐਡਰ ਦੋ ਬਿੱਟ, A ਅਤੇ B, ਜੋੜਦਾ ਹੈ। ਇਹ ਇੱਕ ਜੋੜ ਬਿੱਟ (S) ਅਤੇ ਇੱਕ ਹਾਸਲ ਬਿੱਟ (C) ਦਿੰਦਾ ਹੈ।',
    legend_ha: 'S = ਜੋੜ (Sum), C = ਹਾਸਲ (Carry)',
    why_carry: 'ਹਾਸਲ ਕਿਉਂ? ਬਾਈਨਰੀ ਵਿੱਚ 1 + 1 = 10। ਅਸੀਂ 0 ਲਿਖਦੇ ਹਾਂ ਅਤੇ 1 ਅਗਲੀ ਥਾਂ ’ਤੇ ਲੈ ਜਾਂਦੇ ਹਾਂ, ਬਿਲਕੁਲ ਦਸ਼ਮਲਵ ਵਿੱਚ 5 + 5 = 10 ਵਾਂਗ।',
    fa_desc: 'ਫੁੱਲ ਐਡਰ ਤਿੰਨ ਬਿੱਟ ਜੋੜਦਾ ਹੈ: A, B ਅਤੇ ਪਿਛਲੀ ਥਾਂ ਤੋਂ ਆਇਆ ਹਾਸਲ (Cin)। ਇਹ ਦੋ ਹਾਫ਼ ਐਡਰਾਂ ਅਤੇ ਇੱਕ OR ਗੇਟ ਨਾਲ ਬਣਦਾ ਹੈ।',
    legend_fa: 'Cin = ਆਉਣ ਵਾਲਾ ਹਾਸਲ, S = ਜੋੜ, Cout = ਜਾਣ ਵਾਲਾ ਹਾਸਲ',
    fa_how: 'ਤਿੰਨਾਂ ਵਿੱਚੋਂ ਘੱਟੋ-ਘੱਟ ਦੋ ਇਨਪੁੱਟ 1 ਹੋਣ ਤਾਂ Cout = 1 ਹੁੰਦਾ ਹੈ।',
    read_bin: 'ਹਾਸਲ ਅਤੇ ਜੋੜ ਨੂੰ ਇਕੱਠੇ ਇੱਕ ਬਾਈਨਰੀ ਸੰਖਿਆ ਵਜੋਂ ਪੜ੍ਹੋ: {bin} = ਦਸ਼ਮਲਵ ਵਿੱਚ {d}।',
    four_desc: 'ਚਾਰ ਫੁੱਲ ਐਡਰਾਂ ਦੀ ਲੜੀ ਦੋ 4-ਬਿੱਟ ਸੰਖਿਆਵਾਂ (0 ਤੋਂ 15) ਜੋੜਦੀ ਹੈ। ਹਰ ਹਾਸਲ ਖੱਬੇ ਪਾਸੇ ਦੀ ਅਗਲੀ ਥਾਂ ’ਤੇ ਜਾਂਦਾ ਹੈ, ਲਹਿਰ ਵਾਂਗ।',
    place_val: 'ਥਾਂ ਮੁੱਲ', carry_row: 'ਹਾਸਲ',
    bit_aria: '{v} ਵਿੱਚ {p} ਵਾਲਾ ਬਿੱਟ {x} ਹੈ। ਬਦਲਣ ਲਈ ਦਬਾਓ।',
    final_carry: 'ਆਖ਼ਰੀ ਹਾਸਲ ਜਵਾਬ ਦਾ ਪੰਜਵਾਂ ਬਿੱਟ ਬਣ ਜਾਂਦਾ ਹੈ।',
    tap_bits: 'ਸੰਖਿਆਵਾਂ ਬਦਲਣ ਲਈ A ਅਤੇ B ਦੇ ਬਿੱਟ ਛੂਹੋ।',
    mode_fill: 'ਟੇਬਲ ਪੂਰੀ ਕਰੋ', mode_name: 'ਗੇਟ ਪਛਾਣੋ',
    level: 'ਪੱਧਰ', easy: 'ਆਸਾਨ', medium: 'ਦਰਮਿਆਨਾ', hard: 'ਔਖਾ', streak: 'ਲਗਾਤਾਰ ਸਹੀ', best: 'ਸਭ ਤੋਂ ਵਧੀਆ',
    fill_q: 'ਇਸ ਲਈ ਆਉਟਪੁੱਟ ਕਾਲਮ Y ਭਰੋ:',
    tap_cells: 'ਹਰ ? ਨੂੰ ਛੂਹ ਕੇ 0 ਜਾਂ 1 ਚੁਣੋ, ਫਿਰ “ਜਾਂਚੋ” ਦਬਾਓ।',
    cell_aria: 'ਕਤਾਰ {n}: ਆਉਟਪੁੱਟ Y ਹੁਣ {x} ਹੈ। ਬਦਲਣ ਲਈ ਦਬਾਓ।',
    show_answer: 'ਜਵਾਬ ਦਿਖਾਓ', new_question: 'ਨਵਾਂ ਸਵਾਲ',
    fill_all: 'ਪਹਿਲਾਂ ਹਰ ਕਤਾਰ ਭਰੋ।',
    all_right: 'ਸਾਰੀਆਂ {n} ਕਤਾਰਾਂ ਸਹੀ ਹਨ। ਸ਼ਾਬਾਸ਼!',
    some_wrong: '{n} ਵਿੱਚੋਂ {k} ਕਤਾਰਾਂ ਸਹੀ ਹਨ। ਲਾਲ ਵਾਲੀਆਂ ਠੀਕ ਕਰਕੇ ਫਿਰ ਜਾਂਚੋ।',
    answer_shown: 'ਇਹ ਰਿਹਾ ਜਵਾਬ। ਧਿਆਨ ਨਾਲ ਵੇਖੋ, ਫਿਰ ਨਵਾਂ ਸਵਾਲ ਕਰੋ।',
    name_q: 'ਕਿਹੜਾ ਗੇਟ ਇਹ ਟਰੁੱਥ ਟੇਬਲ ਦਿੰਦਾ ਹੈ?',
    name_right: 'ਹਾਂ! ਇਹ {g} ਗੇਟ ਹੈ।',
    name_wrong: 'ਠੀਕ ਨਹੀਂ। ਇਹ {g} ਗੇਟ ਹੈ।',
    ws_hint: 'ਇਸ ਪੱਧਰ ਦੇ 8 ਟਰੁੱਥ ਟੇਬਲ ਸਵਾਲ ਉੱਤਰ-ਕੁੰਜੀ ਸਮੇਤ ਪ੍ਰਿੰਟ ਕਰੋ।',
    print_ws: 'ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ', ws_title: 'ਲੌਜਿਕ ਗੇਟ ਵਰਕਸ਼ੀਟ',
    ws_intro: 'ਹਰ ਟਰੁੱਥ ਟੇਬਲ ਦਾ ਆਉਟਪੁੱਟ ਕਾਲਮ Y ਪੂਰਾ ਕਰੋ।',
    ws_name: 'ਨਾਮ', ws_class: 'ਜਮਾਤ', ws_date: 'ਤਾਰੀਖ਼', answer_key: 'ਉੱਤਰ-ਕੁੰਜੀ',
    help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ / ਜਮਾਤ ਲਈ ਸੁਝਾਅ',
    help_1: 'ਗੇਟ: ਕੋਈ ਗੇਟ ਚੁਣੋ ਅਤੇ ਸਵਿੱਚ ਛੂਹੋ। ਬੱਲਬ ਆਉਟਪੁੱਟ Y ਦਿਖਾਉਂਦਾ ਹੈ ਅਤੇ ਟਰੁੱਥ ਟੇਬਲ ਦੀ ਮਿਲਦੀ ਕਤਾਰ ਚਮਕਦੀ ਹੈ।',
    help_2: 'ਐਕਸਪ੍ਰੈਸ਼ਨ ਲੈਬ: (A + B)·C\' ਜਾਂ NOT (A AND B) ਵਰਗਾ ਕੁਝ ਲਿਖੋ। ਤੁਹਾਨੂੰ ਕਦਮਾਂ ਵਾਲੇ ਕਾਲਮਾਂ ਸਮੇਤ ਟਰੁੱਥ ਟੇਬਲ ਅਤੇ ਤੁਰੰਤ ਜਾਂਚਿਆ ਜਾਣ ਵਾਲਾ ਸਰਕਟ ਮਿਲੇਗਾ।',
    help_3: '“ਕੀ ਦੋ ਐਕਸਪ੍ਰੈਸ਼ਨ ਬਰਾਬਰ ਹਨ?” ਨਾਲ ਡੀ ਮੌਰਗਨ ਦੇ ਨਿਯਮ ਸਾਬਤ ਕਰੋ। ਜੇ ਬਰਾਬਰ ਨਹੀਂ, ਤਾਂ ਐਪ ਉਹ ਕਤਾਰ ਦਿਖਾਉਂਦੀ ਹੈ ਜਿੱਥੇ ਉਹ ਵੱਖਰੇ ਹਨ।',
    help_4: 'ਐਡਰ: ਵੇਖੋ ਕਿ ਕੰਪਿਊਟਰ ਹਾਫ਼ ਐਡਰ ਅਤੇ ਫੁੱਲ ਐਡਰ ਨਾਲ ਬਾਈਨਰੀ ਸੰਖਿਆਵਾਂ ਕਿਵੇਂ ਜੋੜਦਾ ਹੈ, ਫਿਰ ਦੋ 4-ਬਿੱਟ ਸੰਖਿਆਵਾਂ ਜੋੜੋ।',
    help_5: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ “ਮਨੁੱਖੀ ਲੌਜਿਕ ਗੇਟ”: ਦੋ ਵਿਦਿਆਰਥੀ ਇਨਪੁੱਟ A ਅਤੇ B ਬਣਨ (ਹੱਥ ਉੱਪਰ = 1)। ਤੀਜਾ ਵਿਦਿਆਰਥੀ ਗੇਟ ਬਣੇ ਅਤੇ ਤਾਂ ਹੀ ਹੱਥ ਚੁੱਕੇ ਜਦੋਂ ਨਿਯਮ 1 ਕਹੇ। ਸਾਰੀ ਜਮਾਤ ਸਮਾਰਟਬੋਰਡ ’ਤੇ ਜਾਂਚੇ।',
    help_6: 'ਅਧਿਆਪਕਾਂ ਲਈ: ਅਭਿਆਸ ਵਿੱਚ ਪੱਧਰ ਚੁਣੋ ਅਤੇ “ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ” ਦਬਾਓ, ਉੱਤਰ-ਕੁੰਜੀ ਸਮੇਤ 8 ਸਵਾਲ ਮਿਲਣਗੇ।'
  },

  or: {
    app_title: 'ଲଜିକ୍ ଗେଟ୍ ଲ୍ୟାବ୍',
    intro: 'ସୁଇଚ୍ ଦବାଇ ଦେଖନ୍ତୁ ଲଜିକ୍ ଗେଟ୍ କିପରି କାମ କରେ, ବୁଲିଆନ୍ ଏକ୍ସପ୍ରେସନ୍‌ରୁ ଟ୍ରୁଥ୍ ଟେବୁଲ୍ ଓ ସର୍କିଟ୍ ତିଆରି କରନ୍ତୁ, ଡି ମର୍ଗାନ୍‌ଙ୍କ ପରି ନିୟମ ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ଅଭ୍ୟାସ କରନ୍ତୁ।',
    tab_gates: 'ଗେଟ୍', tab_expr: 'ଏକ୍ସପ୍ରେସନ୍ ଲ୍ୟାବ୍', tab_adders: 'ଆଡର୍', tab_practice: 'ଅଭ୍ୟାସ',
    choose_gate: 'ଗେଟ୍', inputs: 'ଇନପୁଟ୍', n_inputs: '{n}ଟି ଇନପୁଟ୍', one_input: '1ଟି ଇନପୁଟ୍', gate_name: '{g} ଗେଟ୍',
    tap_switch: 'ସୁଇଚ୍ ଛୁଇଁ 0 ଓ 1 ମଧ୍ୟରେ ବଦଳାନ୍ତୁ। ଟେବୁଲ୍‌ର କୌଣସି ଧାଡ଼ି ଛୁଇଁ ସିଧା ସେଠାକୁ ଯାଆନ୍ତୁ।',
    kbd_hint: 'କିବୋର୍ଡ୍‌ରେ A, B କିମ୍ବା C ଦବାଇ ମଧ୍ୟ ଇନପୁଟ୍ ବଦଳାଇ ପାରିବେ।',
    expression: 'ବୁଲିଆନ୍ ଏକ୍ସପ୍ରେସନ୍', rule: 'ନିୟମ', real_life: 'ବାସ୍ତବ ଜୀବନର ଉଦାହରଣ', truth_table: 'ଟ୍ରୁଥ୍ ଟେବୁଲ୍ (ସତ୍ୟ ସାରଣୀ)',
    rule_and: 'ସବୁ ଇନପୁଟ୍ 1 ହେଲେ ହିଁ Y = 1 ହୁଏ।',
    rule_or: 'ଅତି କମରେ ଗୋଟିଏ ଇନପୁଟ୍ 1 ହେଲେ Y = 1 ହୁଏ।',
    rule_not: 'Y ଇନପୁଟ୍‌ର ଓଲଟା: 0 ହୁଏ 1, ଏବଂ 1 ହୁଏ 0।',
    rule_nand: 'NOT + AND: ସବୁ ଇନପୁଟ୍ 1 ହେଲେ କେବଳ Y = 0 ହୁଏ।',
    rule_nor: 'NOT + OR: ସବୁ ଇନପୁଟ୍ 0 ହେଲେ କେବଳ Y = 1 ହୁଏ।',
    rule_xor: 'ଅଯୁଗ୍ମ ସଂଖ୍ୟକ ଇନପୁଟ୍ 1 ହେଲେ Y = 1। ଦୁଇଟି ଇନପୁଟ୍‌ରେ: ଯେତେବେଳେ ଦୁହେଁ ଅଲଗା।',
    rule_xnor: 'NOT + XOR: ଯୁଗ୍ମ ସଂଖ୍ୟକ ଇନପୁଟ୍ 1 ହେଲେ Y = 1। ଦୁଇଟି ଇନପୁଟ୍‌ରେ: ଯେତେବେଳେ ଦୁହେଁ ସମାନ।',
    life_and: 'ଛାତ ପଙ୍ଖା କେବଳ ସେତେବେଳେ ଚାଲେ ଯେତେବେଳେ ମେନ୍ ସୁଇଚ୍ ଓ ପଙ୍ଖା ସୁଇଚ୍ ଦୁହେଁ ଅନ୍ ଥାଏ।',
    life_or: 'ଅଫିସ୍ କିମ୍ବା ଷ୍ଟାଫ୍ ରୁମ୍, ଯିଏ ବି ବଟନ୍ ଦବାଏ, ସ୍କୁଲ ଘଣ୍ଟି ବାଜେ।',
    life_not: 'ଘରର ଇନଭର୍ଟର୍ ସେତେବେଳେ ଚାଲୁ ହୁଏ ଯେତେବେଳେ ବିଜୁଳି ନଥାଏ (କରେଣ୍ଟ ଗଲେ)।',
    life_nand: 'କାର୍‌ର ସିଟ୍-ବେଲ୍ଟ ଆଲାର୍ମ ସାମ୍ନା ଦୁଇଟି ସିଟ୍ ବେଲ୍ଟ ନ ବାନ୍ଧିବା ପର୍ଯ୍ୟନ୍ତ ବାଜୁଥାଏ।',
    life_nor: 'ପାଣି ମୋଟର ଛାତ ଉପର ଟାଙ୍କି କେବଳ ସେତେବେଳେ ଭରେ ଯେତେବେଳେ ଟାଙ୍କି ପୂରା ନଥାଏ ଓ ଭୋଲଟେଜ୍ କମ୍ ନଥାଏ।',
    life_xor: 'ସିଡ଼ି ଆଲୁଅର ଦୁଇଟି ସୁଇଚ୍: ଉପରେ କି ତଳେ, ଯେକୌଣସି ଗୋଟିଏ ସୁଇଚ୍ ବଦଳାଇଲେ ଆଲୁଅ ବଦଳିଯାଏ।',
    life_xnor: 'ଉତ୍ତର ଯାଞ୍ଚ ଯନ୍ତ୍ର: ଆପଣଙ୍କ ଉତ୍ତର ଓ ଠିକ୍ ଉତ୍ତର ସମାନ ହେଲେ ସବୁଜ ଆଲୁଅ ଜଳେ।',
    universal: 'NAND ଓ NOR କୁ ୟୁନିଭର୍ସାଲ୍ ଗେଟ୍ କୁହାଯାଏ: କେବଳ NAND ଗେଟ୍ (କିମ୍ବା କେବଳ NOR ଗେଟ୍) ଦେଇ ଯେକୌଣସି ସର୍କିଟ୍ ତିଆରି ହୋଇପାରେ।',
    all_gates: 'ସବୁ ଗେଟ୍ ଗୋଟିଏ ନଜରରେ',
    all_gates_hint: 'ହାଇଲାଇଟ୍ ଧାଡ଼ିଟି ସୁଇଚ୍ A ଓ B ସହ ମେଳ ଖାଏ। ବଦଳାଇବାକୁ ଧାଡ଼ି ଛୁଅନ୍ତୁ।',
    sw_aria: 'ଇନପୁଟ୍ {v} ଏବେ {x}। ବଦଳାଇବାକୁ ଦବାନ୍ତୁ।',
    out_aria: 'ଆଉଟପୁଟ୍ {v} ଏବେ {x}',
    expr_label: 'ଏକ ବୁଲିଆନ୍ ଏକ୍ସପ୍ରେସନ୍ ଲେଖନ୍ତୁ',
    expr_help: 'A ରୁ E ଭେରିଏବଲ୍ ନିଅନ୍ତୁ, ସାଙ୍ଗରେ AND, OR, NOT, XOR, NAND, NOR, XNOR କିମ୍ବା ଚିହ୍ନ · + \' ⊕ ଓ ବନ୍ଧନୀ। AB ର ଅର୍ଥ A·B।',
    examples: 'ଉଦାହରଣ', backspace: 'ଗୋଟିଏ ଅକ୍ଷର ଲିଭାନ୍ତୁ', copy_link: 'ଲିଙ୍କ୍ କପି କରନ୍ତୁ',
    circuit: 'ସର୍କିଟ୍ ଚିତ୍ର',
    circuit_hint: 'ଚିତ୍ରରେ କୌଣସି ଇନପୁଟ୍ (A, B…) କିମ୍ବା ଉପର ବଟନ୍ ଛୁଇଁ ବଦଳାନ୍ତୁ। ସବୁଜ ତାରରେ 1, ଧୂସର ତାରରେ 0।',
    too_big: 'ଏହି ଏକ୍ସପ୍ରେସନ୍ ସଫା ଆଙ୍କିବା ପାଇଁ ବହୁତ ବଡ଼। ଟ୍ରୁଥ୍ ଟେବୁଲ୍ ତଥାପି କାମ କରେ।',
    no_inputs: 'କୌଣସି ଭେରିଏବଲ୍ ନାହିଁ: ଆଉଟପୁଟ୍ କେବେ ବଦଳିବ ନାହିଁ।',
    show_steps: 'ମଝି ପାହାଚର ସ୍ତମ୍ଭ ଦେଖାନ୍ତୁ',
    row_hint: 'ଧାଡ଼ି ଛୁଇଁ ସବୁ ଇନପୁଟ୍ ଏକାଥରେ ସେଟ୍ କରନ୍ତୁ।',
    always_1: 'Y ସବୁବେଳେ 1 (ଟଟୋଲୋଜି)।',
    always_0: 'Y ସବୁବେଳେ 0 (କଣ୍ଟ୍ରାଡିକ୍ସନ୍)।',
    ones_in: '{n}ଟି ଧାଡ଼ି ମଧ୍ୟରୁ {k}ଟିରେ Y = 1:',
    err_empty: 'ଆରମ୍ଭ କରିବାକୁ ଏକ ଏକ୍ସପ୍ରେସନ୍ ଲେଖନ୍ତୁ, ଯେପରି A·B + C।',
    err_unknown: 'ଅଜଣା ଅକ୍ଷର “{ch}”। କେବଳ A, B, C, D ଓ E ଭେରିଏବଲ୍ ବ୍ୟବହାର କରନ୍ତୁ।',
    err_symbol: 'ସ୍ଥାନ {n} ରେ ଥିବା ଚିହ୍ନ “{ch}” ବୁଝାପଡ଼ିଲା ନାହିଁ।',
    err_close: 'ସ୍ଥାନ {n} ରେ ଖୋଲା ବନ୍ଧନୀ ବନ୍ଦ ହୋଇନାହିଁ। ଏକ “)” ଯୋଡ଼ନ୍ତୁ।',
    err_extra_close: 'ସ୍ଥାନ {n} ରେ ଗୋଟିଏ “)” ଅଧିକ ଅଛି।',
    err_operand: 'ସ୍ଥାନ {n} ରେ କିଛି ବାଦ ପଡ଼ିଛି। ସେଠାରେ ଭେରିଏବଲ୍, 0, 1 କିମ୍ବା “(” ଲେଖନ୍ତୁ।',
    err_end: 'ଏକ୍ସପ୍ରେସନ୍ ଅଧା ରହିଗଲା। ଶେଷ ଚିହ୍ନ ପରେ ଏକ ଭେରିଏବଲ୍ ଯୋଡ଼ନ୍ତୁ।',
    err_too_long: 'ଏକ୍ସପ୍ରେସନ୍ ବହୁତ ଲମ୍ବା। ଏହାକୁ {n} ଅକ୍ଷରରୁ କମ୍ ରଖନ୍ତୁ।',
    equiv_title: 'ଦୁଇଟି ଏକ୍ସପ୍ରେସନ୍ କ’ଣ ସମାନ?',
    equiv_intro: 'ଦୁଇଟି ଏକ୍ସପ୍ରେସନ୍ ଲେଖନ୍ତୁ କିମ୍ବା ଏକ ନିୟମ ବାଛନ୍ତୁ। ଆପ୍ ଟ୍ରୁଥ୍ ଟେବୁଲ୍‌ର ପ୍ରତ୍ୟେକ ଧାଡ଼ି ଯାଞ୍ଚ କରେ।',
    try_law: 'ଏକ ନିୟମ ଚେଷ୍ଟା କରନ୍ତୁ:',
    law_dm1: 'ଡି ମର୍ଗାନ୍ ନିୟମ 1', law_dm2: 'ଡି ମର୍ଗାନ୍ ନିୟମ 2',
    law_abs1: 'ଶୋଷଣ ନିୟମ', law_abs2: 'ଶୋଷଣ ନିୟମ (ଦ୍ୱୈତ)',
    law_dist1: 'ବଣ୍ଟନ ନିୟମ', law_dist2: 'ବଣ୍ଟନ ନିୟମ (ଦ୍ୱୈତ)',
    law_xor: 'AND, OR, NOT ରେ XOR', law_dneg: 'ଦୁଇଥର NOT', law_nand: 'NAND ଗେଟ୍‌ରୁ NOT', law_mistake: 'ଏକ ସାଧାରଣ ଭୁଲ',
    expr1: 'ପ୍ରଥମ ଏକ୍ସପ୍ରେସନ୍', expr2: 'ଦ୍ୱିତୀୟ ଏକ୍ସପ୍ରେସନ୍', check: 'ଯାଞ୍ଚ କରନ୍ତୁ',
    equiv_yes: 'ସମାନ ✓ ସବୁ {n}ଟି ଧାଡ଼ିରେ ଦୁହିଁଙ୍କ ଆଉଟପୁଟ୍ ସମାନ।',
    equiv_no: 'ସମାନ ନୁହେଁ ✗',
    equiv_detail: 'ପ୍ରତି-ଉଦାହରଣ: ଯେତେବେଳେ {vals}, ପ୍ରଥମଟି {a} ଦିଏ କିନ୍ତୁ ଦ୍ୱିତୀୟଟି {b} ଦିଏ।',
    col_first: 'ପ୍ରଥମ', col_second: 'ଦ୍ୱିତୀୟ', same: 'ସମାନ?',
    half_adder: 'ହାଫ୍ ଆଡର୍', full_adder: 'ଫୁଲ୍ ଆଡର୍', four_bit: '4-ବିଟ୍ ଆଡର୍',
    ha_desc: 'ହାଫ୍ ଆଡର୍ ଦୁଇଟି ବିଟ୍ A ଓ B ଯୋଗ କରେ। ଏହା ଏକ ଯୋଗଫଳ ବିଟ୍ (S) ଓ ଏକ କ୍ୟାରି ବିଟ୍ (C) ଦିଏ।',
    legend_ha: 'S = ଯୋଗଫଳ (Sum), C = କ୍ୟାରି (Carry)',
    why_carry: 'କ୍ୟାରି କାହିଁକି? ବାଇନାରୀରେ 1 + 1 = 10। ଆମେ 0 ଲେଖୁ ଏବଂ 1 ପରବର୍ତ୍ତୀ ସ୍ଥାନକୁ ନେଉ, ଠିକ୍ ଦଶମିକରେ 5 + 5 = 10 ପରି।',
    fa_desc: 'ଫୁଲ୍ ଆଡର୍ ତିନୋଟି ବିଟ୍ ଯୋଗ କରେ: A, B ଓ ପୂର୍ବ ସ୍ଥାନରୁ ଆସିଥିବା କ୍ୟାରି (Cin)। ଏହା ଦୁଇଟି ହାଫ୍ ଆଡର୍ ଓ ଗୋଟିଏ OR ଗେଟ୍‌ରେ ତିଆରି।',
    legend_fa: 'Cin = ଆସୁଥିବା କ୍ୟାରି, S = ଯୋଗଫଳ, Cout = ଯାଉଥିବା କ୍ୟାରି',
    fa_how: 'ତିନୋଟି ମଧ୍ୟରୁ ଅତି କମରେ ଦୁଇଟି ଇନପୁଟ୍ 1 ହେଲେ Cout = 1 ହୁଏ।',
    read_bin: 'କ୍ୟାରି ଓ ଯୋଗଫଳକୁ ଏକାଠି ଏକ ବାଇନାରୀ ସଂଖ୍ୟା ଭାବେ ପଢ଼ନ୍ତୁ: {bin} = ଦଶମିକରେ {d}।',
    four_desc: 'ଚାରୋଟି ଫୁଲ୍ ଆଡର୍‌ର ଏକ ଶିକୁଳି ଦୁଇଟି 4-ବିଟ୍ ସଂଖ୍ୟା (0 ରୁ 15) ଯୋଗ କରେ। ପ୍ରତ୍ୟେକ କ୍ୟାରି ବାମ ପଟର ପରବର୍ତ୍ତୀ ସ୍ଥାନକୁ ଯାଏ, ଢେଉ ପରି।',
    place_val: 'ସ୍ଥାନୀୟ ମାନ', carry_row: 'କ୍ୟାରି',
    bit_aria: '{v} ର {p} ସ୍ଥାନର ବିଟ୍ {x}। ବଦଳାଇବାକୁ ଦବାନ୍ତୁ।',
    final_carry: 'ଶେଷ କ୍ୟାରି ଉତ୍ତରର ପଞ୍ଚମ ବିଟ୍ ହୋଇଯାଏ।',
    tap_bits: 'ସଂଖ୍ୟା ବଦଳାଇବାକୁ A ଓ B ର ବିଟ୍ ଛୁଅନ୍ତୁ।',
    mode_fill: 'ଟେବୁଲ୍ ପୂରଣ କରନ୍ତୁ', mode_name: 'ଗେଟ୍ ଚିହ୍ନନ୍ତୁ',
    level: 'ସ୍ତର', easy: 'ସହଜ', medium: 'ମଧ୍ୟମ', hard: 'କଠିନ', streak: 'ଲଗାତାର ଠିକ୍', best: 'ସର୍ବୋତ୍ତମ',
    fill_q: 'ଏହା ପାଇଁ ଆଉଟପୁଟ୍ ସ୍ତମ୍ଭ Y ପୂରଣ କରନ୍ତୁ:',
    tap_cells: 'ପ୍ରତ୍ୟେକ ? ଛୁଇଁ 0 କିମ୍ବା 1 ବାଛନ୍ତୁ, ତା’ପରେ “ଯାଞ୍ଚ କରନ୍ତୁ” ଦବାନ୍ତୁ।',
    cell_aria: 'ଧାଡ଼ି {n}: ଆଉଟପୁଟ୍ Y ଏବେ {x}। ବଦଳାଇବାକୁ ଦବାନ୍ତୁ।',
    show_answer: 'ଉତ୍ତର ଦେଖାନ୍ତୁ', new_question: 'ନୂଆ ପ୍ରଶ୍ନ',
    fill_all: 'ପ୍ରଥମେ ପ୍ରତ୍ୟେକ ଧାଡ଼ି ପୂରଣ କରନ୍ତୁ।',
    all_right: 'ସବୁ {n}ଟି ଧାଡ଼ି ଠିକ୍। ବହୁତ ଭଲ!',
    some_wrong: '{n}ଟି ମଧ୍ୟରୁ {k}ଟି ଧାଡ଼ି ଠିକ୍। ନାଲି ଧାଡ଼ିଗୁଡ଼ିକ ସୁଧାରି ପୁଣି ଯାଞ୍ଚ କରନ୍ତୁ।',
    answer_shown: 'ଏହା ହେଉଛି ଉତ୍ତର। ଭଲ କରି ଦେଖନ୍ତୁ, ତା’ପରେ ନୂଆ ପ୍ରଶ୍ନ କରନ୍ତୁ।',
    name_q: 'କେଉଁ ଗେଟ୍ ଏହି ଟ୍ରୁଥ୍ ଟେବୁଲ୍ ଦିଏ?',
    name_right: 'ହଁ! ଏହା {g} ଗେଟ୍।',
    name_wrong: 'ଠିକ୍ ନୁହେଁ। ଏହା {g} ଗେଟ୍।',
    ws_hint: 'ଏହି ସ୍ତରର 8ଟି ଟ୍ରୁଥ୍ ଟେବୁଲ୍ ପ୍ରଶ୍ନ ଉତ୍ତର ତାଲିକା ସହ ପ୍ରିଣ୍ଟ କରନ୍ତୁ।',
    print_ws: 'ୱର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ', ws_title: 'ଲଜିକ୍ ଗେଟ୍ ୱର୍କସିଟ୍',
    ws_intro: 'ପ୍ରତ୍ୟେକ ଟ୍ରୁଥ୍ ଟେବୁଲ୍‌ର ଆଉଟପୁଟ୍ ସ୍ତମ୍ଭ Y ପୂରଣ କରନ୍ତୁ।',
    ws_name: 'ନାମ', ws_class: 'ଶ୍ରେଣୀ', ws_date: 'ତାରିଖ', answer_key: 'ଉତ୍ତର ତାଲିକା',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ଶ୍ରେଣୀ ପାଇଁ ଧାରଣା',
    help_1: 'ଗେଟ୍: ଏକ ଗେଟ୍ ବାଛନ୍ତୁ ଓ ସୁଇଚ୍ ଛୁଅନ୍ତୁ। ବଲ୍‌ବ ଆଉଟପୁଟ୍ Y ଦେଖାଏ ଏବଂ ଟ୍ରୁଥ୍ ଟେବୁଲ୍‌ର ମେଳ ଖାଉଥିବା ଧାଡ଼ି ଚମକେ।',
    help_2: 'ଏକ୍ସପ୍ରେସନ୍ ଲ୍ୟାବ୍: (A + B)·C\' କିମ୍ବା NOT (A AND B) ପରି କିଛି ଲେଖନ୍ତୁ। ପାହାଚ ସ୍ତମ୍ଭ ସହ ଟ୍ରୁଥ୍ ଟେବୁଲ୍ ଓ ତୁରନ୍ତ ପରୀକ୍ଷା କରିହେବା ଭଳି ସର୍କିଟ୍ ମିଳିବ।',
    help_3: '“ଦୁଇଟି ଏକ୍ସପ୍ରେସନ୍ କ’ଣ ସମାନ?” ଦ୍ୱାରା ଡି ମର୍ଗାନ୍ ନିୟମ ପ୍ରମାଣ କରନ୍ତୁ। ସମାନ ନହେଲେ ଆପ୍ ସେହି ଧାଡ଼ି ଦେଖାଏ ଯେଉଁଠି ସେମାନେ ଅଲଗା।',
    help_4: 'ଆଡର୍: ଦେଖନ୍ତୁ କମ୍ପ୍ୟୁଟର ହାଫ୍ ଆଡର୍ ଓ ଫୁଲ୍ ଆଡର୍ ଦ୍ୱାରା ବାଇନାରୀ ସଂଖ୍ୟା କିପରି ଯୋଗ କରେ, ତା’ପରେ ଦୁଇଟି 4-ବିଟ୍ ସଂଖ୍ୟା ଯୋଗ କରନ୍ତୁ।',
    help_5: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ “ମଣିଷ ଲଜିକ୍ ଗେଟ୍”: ଦୁଇଜଣ ଛାତ୍ରଛାତ୍ରୀ ଇନପୁଟ୍ A ଓ B (ହାତ ଉପରେ = 1)। ତୃତୀୟ ଜଣେ ଗେଟ୍ ହୁଅନ୍ତି ଓ ନିୟମ 1 କହିଲେ ହିଁ ହାତ ଟେକନ୍ତି। ପୂରା ଶ୍ରେଣୀ ସ୍ମାର୍ଟବୋର୍ଡ୍‌ରେ ଯାଞ୍ଚ କରେ।',
    help_6: 'ଶିକ୍ଷକଙ୍କ ପାଇଁ: ଅଭ୍ୟାସରେ ସ୍ତର ବାଛି “ୱର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ” ଦବାନ୍ତୁ, ଉତ୍ତର ତାଲିକା ସହ 8ଟି ପ୍ରଶ୍ନ ମିଳିବ।'
  },

  ta: {
    app_title: 'லாஜிக் கேட் ஆய்வகம்',
    intro: 'ஸ்விட்சுகளை அழுத்தி லாஜிக் கேட்கள் எப்படி வேலை செய்கின்றன என்று பாருங்கள், பூலியன் கோவைகளிலிருந்து உண்மை அட்டவணையும் சர்க்யூட்டும் உருவாக்குங்கள், டி மார்கன் போன்ற விதிகளைச் சரிபாருங்கள், பயிற்சி செய்யுங்கள்.',
    tab_gates: 'கேட்கள்', tab_expr: 'கோவை ஆய்வகம்', tab_adders: 'கூட்டிகள்', tab_practice: 'பயிற்சி',
    choose_gate: 'கேட்', inputs: 'உள்ளீடுகள்', n_inputs: '{n} உள்ளீடுகள்', one_input: '1 உள்ளீடு', gate_name: '{g} கேட்',
    tap_switch: 'ஸ்விட்சைத் தொட்டு 0, 1 இடையே மாற்றுங்கள். அட்டவணையின் ஒரு வரிசையைத் தொட்டால் நேராக அதற்குச் செல்லும்.',
    kbd_hint: 'விசைப்பலகையில் A, B அல்லது C அழுத்தியும் உள்ளீடுகளை மாற்றலாம்.',
    expression: 'பூலியன் கோவை', rule: 'விதி', real_life: 'அன்றாட வாழ்க்கை உதாரணம்', truth_table: 'உண்மை அட்டவணை',
    rule_and: 'எல்லா உள்ளீடுகளும் 1 ஆக இருந்தால் மட்டுமே Y = 1.',
    rule_or: 'குறைந்தது ஒரு உள்ளீடு 1 ஆக இருந்தால் Y = 1.',
    rule_not: 'Y என்பது உள்ளீட்டின் எதிர்: 0 என்பது 1 ஆகும், 1 என்பது 0 ஆகும்.',
    rule_nand: 'NOT + AND: எல்லா உள்ளீடுகளும் 1 ஆக இருக்கும்போது மட்டுமே Y = 0.',
    rule_nor: 'NOT + OR: எல்லா உள்ளீடுகளும் 0 ஆக இருக்கும்போது மட்டுமே Y = 1.',
    rule_xor: 'ஒற்றை எண்ணிக்கையில் உள்ளீடுகள் 1 ஆக இருந்தால் Y = 1. இரண்டு உள்ளீடுகளில்: இரண்டும் வேறுபட்டால்.',
    rule_xnor: 'NOT + XOR: இரட்டை எண்ணிக்கையில் உள்ளீடுகள் 1 ஆக இருந்தால் Y = 1. இரண்டு உள்ளீடுகளில்: இரண்டும் ஒன்றாக இருந்தால்.',
    life_and: 'மெயின் ஸ்விட்சும் மின்விசிறி ஸ்விட்சும் இரண்டும் ஆன் ஆக இருந்தால் மட்டுமே மின்விசிறி சுழலும்.',
    life_or: 'அலுவலகமோ ஆசிரியர் அறையோ, யார் பொத்தானை அழுத்தினாலும் பள்ளி மணி அடிக்கும்.',
    life_not: 'மின்சாரம் இல்லாதபோது (மின்வெட்டின்போது) வீட்டு இன்வெர்ட்டர் இயங்கத் தொடங்கும்.',
    life_nand: 'முன் இருக்கைகளின் இரண்டு சீட் பெல்ட்களும் போடப்படும் வரை காரின் சீட் பெல்ட் அலாரம் ஒலித்துக்கொண்டே இருக்கும்.',
    life_nor: 'தொட்டி நிரம்பவில்லை, மின்னழுத்தமும் குறைவாக இல்லை என்றால் மட்டுமே நீர் மோட்டார் மாடித் தொட்டியை நிரப்பும்.',
    life_xor: 'படிக்கட்டு விளக்கில் இரண்டு ஸ்விட்சுகள்: மேலோ கீழோ, எந்த ஒரு ஸ்விட்சை மாற்றினாலும் விளக்கு மாறும்.',
    life_xnor: 'விடை சரிபார்க்கும் கருவி: உங்கள் விடையும் சரியான விடையும் ஒன்றாக இருந்தால் பச்சை விளக்கு எரியும்.',
    universal: 'NAND, NOR ஆகியவை யுனிவர்சல் கேட்கள்: NAND கேட்களை மட்டும் (அல்லது NOR கேட்களை மட்டும்) வைத்து எந்த சர்க்யூட்டையும் உருவாக்கலாம்.',
    all_gates: 'எல்லா கேட்களும் ஒரே பார்வையில்',
    all_gates_hint: 'ஒளிரும் வரிசை ஸ்விட்ச் A, B உடன் பொருந்துகிறது. மாற்ற ஒரு வரிசையைத் தொடுங்கள்.',
    sw_aria: 'உள்ளீடு {v} இப்போது {x}. மாற்ற அழுத்துங்கள்.',
    out_aria: 'வெளியீடு {v} இப்போது {x}',
    expr_label: 'ஒரு பூலியன் கோவையைத் தட்டச்சு செய்யுங்கள்',
    expr_help: 'A முதல் E வரையிலான மாறிகளுடன் AND, OR, NOT, XOR, NAND, NOR, XNOR அல்லது · + \' ⊕ குறிகளும் அடைப்புக்குறிகளும் பயன்படுத்துங்கள். AB என்றால் A·B.',
    examples: 'உதாரணங்கள்', backspace: 'ஓர் எழுத்தை அழி', copy_link: 'இணைப்பை நகலெடு',
    circuit: 'சர்க்யூட் வரைபடம்',
    circuit_hint: 'வரைபடத்தில் ஒரு உள்ளீட்டை (A, B…) அல்லது மேலே உள்ள பொத்தானைத் தொட்டு மாற்றுங்கள். பச்சைக் கம்பியில் 1, சாம்பல் கம்பியில் 0.',
    too_big: 'இந்தக் கோவை தெளிவாக வரைய மிகப் பெரியது. உண்மை அட்டவணை இருந்தாலும் வேலை செய்யும்.',
    no_inputs: 'மாறிகள் இல்லை: வெளியீடு ஒருபோதும் மாறாது.',
    show_steps: 'இடைப்பட்ட படி நெடுவரிசைகளைக் காட்டு',
    row_hint: 'ஒரு வரிசையைத் தொட்டு எல்லா உள்ளீடுகளையும் ஒரே நேரத்தில் அமையுங்கள்.',
    always_1: 'Y எப்போதும் 1 (டாட்டாலஜி).',
    always_0: 'Y எப்போதும் 0 (முரண்பாடு).',
    ones_in: '{n} வரிசைகளில் {k} இல் Y = 1:',
    err_empty: 'தொடங்க ஒரு கோவையைத் தட்டச்சு செய்யுங்கள், எ.கா. A·B + C.',
    err_unknown: 'தெரியாத எழுத்து “{ch}”. A, B, C, D, E மாறிகளை மட்டும் பயன்படுத்துங்கள்.',
    err_symbol: 'இடம் {n} இல் உள்ள “{ch}” குறி புரியவில்லை.',
    err_close: 'இடம் {n} இல் திறந்த அடைப்புக்குறி மூடப்படவில்லை. ஒரு “)” சேருங்கள்.',
    err_extra_close: 'இடம் {n} இல் ஒரு “)” கூடுதலாக உள்ளது.',
    err_operand: 'இடம் {n} இல் ஏதோ விடுபட்டுள்ளது. அங்கே ஒரு மாறி, 0, 1 அல்லது “(” இடுங்கள்.',
    err_end: 'கோவை முழுமையடையவில்லை. கடைசிக் குறிக்குப் பின் ஒரு மாறியைச் சேருங்கள்.',
    err_too_long: 'கோவை மிக நீளமாக உள்ளது. {n} எழுத்துகளுக்குள் வையுங்கள்.',
    equiv_title: 'இரண்டு கோவைகள் சமமா?',
    equiv_intro: 'இரண்டு கோவைகளைத் தட்டச்சு செய்யுங்கள் அல்லது ஒரு விதியைத் தேர்ந்தெடுங்கள். செயலி உண்மை அட்டவணையின் ஒவ்வொரு வரிசையையும் சரிபார்க்கும்.',
    try_law: 'ஒரு விதியை முயலுங்கள்:',
    law_dm1: 'டி மார்கன் விதி 1', law_dm2: 'டி மார்கன் விதி 2',
    law_abs1: 'உட்கவர் விதி', law_abs2: 'உட்கவர் விதி (இருமை)',
    law_dist1: 'பங்கீட்டு விதி', law_dist2: 'பங்கீட்டு விதி (இருமை)',
    law_xor: 'AND, OR, NOT கொண்டு XOR', law_dneg: 'இரட்டை NOT', law_nand: 'NAND கேட்டிலிருந்து NOT', law_mistake: 'ஒரு பொதுவான தவறு',
    expr1: 'முதல் கோவை', expr2: 'இரண்டாம் கோவை', check: 'சரிபார்',
    equiv_yes: 'சமம் ✓ எல்லா {n} வரிசைகளிலும் இரண்டும் ஒரே வெளியீட்டைத் தருகின்றன.',
    equiv_no: 'சமம் இல்லை ✗',
    equiv_detail: 'எதிர் உதாரணம்: {vals} ஆக இருக்கும்போது, முதலாவது {a} தருகிறது, ஆனால் இரண்டாவது {b} தருகிறது.',
    col_first: 'முதல்', col_second: 'இரண்டாம்', same: 'ஒன்றா?',
    half_adder: 'அரைக் கூட்டி', full_adder: 'முழுக் கூட்டி', four_bit: '4-பிட் கூட்டி',
    ha_desc: 'அரைக் கூட்டி A, B என்ற இரண்டு பிட்களைக் கூட்டுகிறது. அது ஒரு கூட்டுத்தொகை பிட் (S), ஒரு கேரி பிட் (C) தருகிறது.',
    legend_ha: 'S = கூட்டுத்தொகை (Sum), C = கேரி (Carry)',
    why_carry: 'கேரி ஏன்? பைனரியில் 1 + 1 = 10. நாம் 0 எழுதி 1-ஐ அடுத்த இடத்துக்குக் கொண்டு செல்கிறோம், தசம எண்ணில் 5 + 5 = 10 போலவே.',
    fa_desc: 'முழுக் கூட்டி மூன்று பிட்களைக் கூட்டுகிறது: A, B மற்றும் முந்தைய இடத்திலிருந்து வரும் கேரி (Cin). இது இரண்டு அரைக் கூட்டிகளாலும் ஒரு OR கேட்டாலும் ஆனது.',
    legend_fa: 'Cin = வரும் கேரி, S = கூட்டுத்தொகை, Cout = வெளிச்செல்லும் கேரி',
    fa_how: 'மூன்றில் குறைந்தது இரண்டு உள்ளீடுகள் 1 ஆக இருந்தால் Cout = 1.',
    read_bin: 'கேரியையும் கூட்டுத்தொகையையும் சேர்த்து ஒரு பைனரி எண்ணாகப் படியுங்கள்: {bin} = தசமத்தில் {d}.',
    four_desc: 'நான்கு முழுக் கூட்டிகளின் சங்கிலி இரண்டு 4-பிட் எண்களை (0 முதல் 15) கூட்டுகிறது. ஒவ்வொரு கேரியும் இடப்பக்கம் உள்ள அடுத்த இடத்துக்கு அலை போலச் செல்கிறது.',
    place_val: 'இட மதிப்பு', carry_row: 'கேரி',
    bit_aria: '{v}-இல் {p}-க்கான பிட் {x}. மாற்ற அழுத்துங்கள்.',
    final_carry: 'கடைசி கேரி விடையின் ஐந்தாவது பிட்டாக மாறுகிறது.',
    tap_bits: 'எண்களை மாற்ற A, B பிட்களைத் தொடுங்கள்.',
    mode_fill: 'அட்டவணையை நிரப்பு', mode_name: 'கேட்டைக் கண்டுபிடி',
    level: 'நிலை', easy: 'எளிது', medium: 'நடுத்தரம்', hard: 'கடினம்', streak: 'தொடர் சரி', best: 'சிறந்தது',
    fill_q: 'இதற்கான வெளியீட்டு நெடுவரிசை Y-ஐ நிரப்புங்கள்:',
    tap_cells: 'ஒவ்வொரு ?-ஐயும் தொட்டு 0 அல்லது 1 தேர்ந்தெடுங்கள், பிறகு “சரிபார்” அழுத்துங்கள்.',
    cell_aria: 'வரிசை {n}: வெளியீடு Y இப்போது {x}. மாற்ற அழுத்துங்கள்.',
    show_answer: 'விடையைக் காட்டு', new_question: 'புதிய கேள்வி',
    fill_all: 'முதலில் எல்லா வரிசைகளையும் நிரப்புங்கள்.',
    all_right: 'எல்லா {n} வரிசைகளும் சரி. அருமை!',
    some_wrong: '{n} வரிசைகளில் {k} சரி. சிவப்பு வரிசைகளைத் திருத்தி மீண்டும் சரிபாருங்கள்.',
    answer_shown: 'இதோ விடை. கவனமாகப் பாருங்கள், பிறகு புதிய கேள்வியை முயலுங்கள்.',
    name_q: 'எந்த கேட் இந்த உண்மை அட்டவணையைத் தருகிறது?',
    name_right: 'ஆம்! இது {g} கேட்.',
    name_wrong: 'சரியில்லை. இது {g} கேட்.',
    ws_hint: 'இந்த நிலையில் 8 உண்மை அட்டவணைக் கேள்விகளை விடைக் குறிப்புடன் அச்சிடுங்கள்.',
    print_ws: 'பயிற்சித்தாளை அச்சிடு', ws_title: 'லாஜிக் கேட் பயிற்சித்தாள்',
    ws_intro: 'ஒவ்வொரு உண்மை அட்டவணையிலும் வெளியீட்டு நெடுவரிசை Y-ஐ நிரப்புங்கள்.',
    ws_name: 'பெயர்', ws_class: 'வகுப்பு', ws_date: 'தேதி', answer_key: 'விடைக் குறிப்பு',
    help_title: 'எப்படிப் பயன்படுத்துவது / வகுப்பறைக்கான யோசனைகள்',
    help_1: 'கேட்கள்: ஒரு கேட்டைத் தேர்ந்தெடுத்து ஸ்விட்சுகளைத் தொடுங்கள். விளக்கு வெளியீடு Y-ஐக் காட்டும், உண்மை அட்டவணையின் பொருந்தும் வரிசை ஒளிரும்.',
    help_2: 'கோவை ஆய்வகம்: (A + B)·C\' அல்லது NOT (A AND B) போன்ற ஒன்றைத் தட்டச்சு செய்யுங்கள். படி நெடுவரிசைகளுடன் உண்மை அட்டவணையும், உடனே சோதிக்கக்கூடிய சர்க்யூட்டும் கிடைக்கும்.',
    help_3: '“இரண்டு கோவைகள் சமமா?” மூலம் டி மார்கன் விதிகளை நிரூபியுங்கள். சமம் இல்லையெனில், அவை வேறுபடும் வரிசையைச் செயலி காட்டும்.',
    help_4: 'கூட்டிகள்: கணினி அரைக் கூட்டி, முழுக் கூட்டி மூலம் பைனரி எண்களை எப்படிக் கூட்டுகிறது என்று பாருங்கள், பிறகு இரண்டு 4-பிட் எண்களைக் கூட்டுங்கள்.',
    help_5: 'வகுப்பறைச் செயல்பாடு “மனித லாஜிக் கேட்”: இரண்டு மாணவர்கள் உள்ளீடுகள் A, B (கை உயர்த்தினால் = 1). மூன்றாவது மாணவர் கேட் ஆகி, விதி 1 என்று சொல்லும்போது மட்டும் கையை உயர்த்துவார். வகுப்பு முழுவதும் ஸ்மார்ட்போர்டில் சரிபார்க்கும்.',
    help_6: 'ஆசிரியர்களுக்கு: பயிற்சியில் ஒரு நிலையைத் தேர்ந்தெடுத்து “பயிற்சித்தாளை அச்சிடு” அழுத்தினால், விடைக் குறிப்புடன் 8 கேள்விகள் கிடைக்கும்.'
  },

  te: {
    app_title: 'లాజిక్ గేట్ ల్యాబ్',
    intro: 'స్విచ్‌లు నొక్కి లాజిక్ గేట్‌లు ఎలా పనిచేస్తాయో చూడండి, బూలియన్ ఎక్స్‌ప్రెషన్‌ల నుంచి ట్రూత్ టేబుల్, సర్క్యూట్ తయారు చేయండి, డి మోర్గాన్ వంటి నియమాలు సరిచూడండి, సాధన చేయండి.',
    tab_gates: 'గేట్‌లు', tab_expr: 'ఎక్స్‌ప్రెషన్ ల్యాబ్', tab_adders: 'యాడర్‌లు', tab_practice: 'సాధన',
    choose_gate: 'గేట్', inputs: 'ఇన్‌పుట్‌లు', n_inputs: '{n} ఇన్‌పుట్‌లు', one_input: '1 ఇన్‌పుట్', gate_name: '{g} గేట్',
    tap_switch: 'స్విచ్‌ను తాకి 0, 1 మధ్య మార్చండి. టేబుల్‌లో ఏదైనా వరుసను తాకితే నేరుగా దానికి వెళ్తుంది.',
    kbd_hint: 'కీబోర్డ్‌పై A, B లేదా C నొక్కి కూడా ఇన్‌పుట్‌లు మార్చవచ్చు.',
    expression: 'బూలియన్ ఎక్స్‌ప్రెషన్', rule: 'నియమం', real_life: 'నిజ జీవిత ఉదాహరణ', truth_table: 'ట్రూత్ టేబుల్ (సత్య పట్టిక)',
    rule_and: 'అన్ని ఇన్‌పుట్‌లు 1 అయితేనే Y = 1.',
    rule_or: 'కనీసం ఒక ఇన్‌పుట్ 1 అయితే Y = 1.',
    rule_not: 'Y ఇన్‌పుట్‌కు వ్యతిరేకం: 0 అయితే 1, 1 అయితే 0.',
    rule_nand: 'NOT + AND: అన్ని ఇన్‌పుట్‌లు 1 అయినప్పుడు మాత్రమే Y = 0.',
    rule_nor: 'NOT + OR: అన్ని ఇన్‌పుట్‌లు 0 అయినప్పుడు మాత్రమే Y = 1.',
    rule_xor: 'బేసి సంఖ్యలో ఇన్‌పుట్‌లు 1 అయితే Y = 1. రెండు ఇన్‌పుట్‌లలో: రెండూ వేరుగా ఉన్నప్పుడు.',
    rule_xnor: 'NOT + XOR: సరి సంఖ్యలో ఇన్‌పుట్‌లు 1 అయితే Y = 1. రెండు ఇన్‌పుట్‌లలో: రెండూ ఒకేలా ఉన్నప్పుడు.',
    life_and: 'మెయిన్ స్విచ్, ఫ్యాన్ స్విచ్ రెండూ ఆన్‌లో ఉంటేనే సీలింగ్ ఫ్యాన్ తిరుగుతుంది.',
    life_or: 'ఆఫీసు గానీ స్టాఫ్ రూమ్ గానీ, ఎవరు బటన్ నొక్కినా బడి గంట మోగుతుంది.',
    life_not: 'కరెంటు లేనప్పుడు (పవర్ కట్ సమయంలో) ఇంటి ఇన్వర్టర్ ఆన్ అవుతుంది.',
    life_nand: 'ముందు రెండు సీట్ బెల్ట్‌లు పెట్టుకునే వరకు కారు సీట్-బెల్ట్ అలారం మోగుతూనే ఉంటుంది.',
    life_nor: 'ట్యాంక్ నిండలేదు, వోల్టేజ్ తక్కువగా లేదు అయినప్పుడే నీటి మోటార్ డాబా మీది ట్యాంక్‌ను నింపుతుంది.',
    life_xor: 'మెట్ల లైట్‌కు రెండు స్విచ్‌లు: పైన గానీ కింద గానీ, ఏ ఒక్క స్విచ్ మార్చినా లైట్ మారుతుంది.',
    life_xnor: 'సమాధానం సరిచూసే యంత్రం: మీ సమాధానం, సరైన సమాధానం ఒకటే అయితే ఆకుపచ్చ లైట్ వెలుగుతుంది.',
    universal: 'NAND, NOR లను యూనివర్సల్ గేట్‌లు అంటారు: కేవలం NAND గేట్‌లతో (లేదా కేవలం NOR గేట్‌లతో) ఏ సర్క్యూట్‌నైనా తయారు చేయవచ్చు.',
    all_gates: 'అన్ని గేట్‌లు ఒకే చూపులో',
    all_gates_hint: 'హైలైట్ చేసిన వరుస స్విచ్ A, B తో సరిపోతుంది. మార్చడానికి ఏదైనా వరుసను తాకండి.',
    sw_aria: 'ఇన్‌పుట్ {v} ఇప్పుడు {x}. మార్చడానికి నొక్కండి.',
    out_aria: 'అవుట్‌పుట్ {v} ఇప్పుడు {x}',
    expr_label: 'బూలియన్ ఎక్స్‌ప్రెషన్ టైప్ చేయండి',
    expr_help: 'A నుంచి E వరకు చరరాశులతో AND, OR, NOT, XOR, NAND, NOR, XNOR లేదా · + \' ⊕ గుర్తులు, బ్రాకెట్‌లు వాడండి. AB అంటే A·B.',
    examples: 'ఉదాహరణలు', backspace: 'ఒక అక్షరం తొలగించు', copy_link: 'లింక్ కాపీ చేయండి',
    circuit: 'సర్క్యూట్ చిత్రం',
    circuit_hint: 'చిత్రంలో ఏదైనా ఇన్‌పుట్‌ను (A, B…) లేదా పైన ఉన్న బటన్‌ను తాకి మార్చండి. ఆకుపచ్చ తీగలో 1, బూడిద తీగలో 0.',
    too_big: 'ఈ ఎక్స్‌ప్రెషన్ చక్కగా గీయడానికి చాలా పెద్దది. ట్రూత్ టేబుల్ అయినా పనిచేస్తుంది.',
    no_inputs: 'చరరాశులు లేవు: అవుట్‌పుట్ ఎప్పటికీ మారదు.',
    show_steps: 'మధ్య దశల నిలువు వరుసలు చూపించు',
    row_hint: 'ఒక వరుసను తాకి అన్ని ఇన్‌పుట్‌లు ఒకేసారి సెట్ చేయండి.',
    always_1: 'Y ఎప్పుడూ 1 (టాటాలజీ).',
    always_0: 'Y ఎప్పుడూ 0 (వైరుధ్యం).',
    ones_in: '{n} వరుసలలో {k} వరుసల్లో Y = 1:',
    err_empty: 'మొదలుపెట్టడానికి ఒక ఎక్స్‌ప్రెషన్ టైప్ చేయండి, ఉదా. A·B + C.',
    err_unknown: 'తెలియని అక్షరం “{ch}”. A, B, C, D, E చరరాశులను మాత్రమే వాడండి.',
    err_symbol: 'స్థానం {n} వద్ద ఉన్న “{ch}” గుర్తు అర్థం కాలేదు.',
    err_close: 'స్థానం {n} వద్ద తెరిచిన బ్రాకెట్ మూయలేదు. ఒక “)” చేర్చండి.',
    err_extra_close: 'స్థానం {n} వద్ద ఒక “)” ఎక్కువగా ఉంది.',
    err_operand: 'స్థానం {n} వద్ద ఏదో తప్పిపోయింది. అక్కడ చరరాశి, 0, 1 లేదా “(” పెట్టండి.',
    err_end: 'ఎక్స్‌ప్రెషన్ అసంపూర్ణంగా ఉంది. చివరి గుర్తు తర్వాత ఒక చరరాశిని చేర్చండి.',
    err_too_long: 'ఎక్స్‌ప్రెషన్ చాలా పొడవుగా ఉంది. దాన్ని {n} అక్షరాల లోపు ఉంచండి.',
    equiv_title: 'రెండు ఎక్స్‌ప్రెషన్‌లు సమానమా?',
    equiv_intro: 'రెండు ఎక్స్‌ప్రెషన్‌లు టైప్ చేయండి లేదా ఒక నియమాన్ని ఎంచుకోండి. యాప్ ట్రూత్ టేబుల్‌లోని ప్రతి వరుసను సరిచూస్తుంది.',
    try_law: 'ఒక నియమాన్ని ప్రయత్నించండి:',
    law_dm1: 'డి మోర్గాన్ నియమం 1', law_dm2: 'డి మోర్గాన్ నియమం 2',
    law_abs1: 'శోషణ నియమం', law_abs2: 'శోషణ నియమం (ద్వంద్వ)',
    law_dist1: 'విభాగ నియమం', law_dist2: 'విభాగ నియమం (ద్వంద్వ)',
    law_xor: 'AND, OR, NOT తో XOR', law_dneg: 'రెండుసార్లు NOT', law_nand: 'NAND గేట్‌తో NOT', law_mistake: 'ఒక సాధారణ పొరపాటు',
    expr1: 'మొదటి ఎక్స్‌ప్రెషన్', expr2: 'రెండవ ఎక్స్‌ప్రెషన్', check: 'సరిచూడు',
    equiv_yes: 'సమానం ✓ అన్ని {n} వరుసల్లో రెండూ ఒకే అవుట్‌పుట్ ఇస్తాయి.',
    equiv_no: 'సమానం కాదు ✗',
    equiv_detail: 'ప్రత్యుదాహరణ: {vals} అయినప్పుడు, మొదటిది {a} ఇస్తుంది కానీ రెండవది {b} ఇస్తుంది.',
    col_first: 'మొదటిది', col_second: 'రెండవది', same: 'ఒకటేనా?',
    half_adder: 'హాఫ్ యాడర్', full_adder: 'ఫుల్ యాడర్', four_bit: '4-బిట్ యాడర్',
    ha_desc: 'హాఫ్ యాడర్ A, B అనే రెండు బిట్‌లను కలుపుతుంది. ఇది ఒక మొత్తం బిట్ (S), ఒక క్యారీ బిట్ (C) ఇస్తుంది.',
    legend_ha: 'S = మొత్తం (Sum), C = క్యారీ (Carry)',
    why_carry: 'క్యారీ ఎందుకు? బైనరీలో 1 + 1 = 10. మనం 0 రాసి 1ని తర్వాతి స్థానానికి తీసుకెళ్తాం, దశాంశంలో 5 + 5 = 10 లాగే.',
    fa_desc: 'ఫుల్ యాడర్ మూడు బిట్‌లను కలుపుతుంది: A, B, ఇంకా వెనుక స్థానం నుంచి వచ్చిన క్యారీ (Cin). ఇది రెండు హాఫ్ యాడర్‌లు, ఒక OR గేట్‌తో తయారవుతుంది.',
    legend_fa: 'Cin = వచ్చే క్యారీ, S = మొత్తం, Cout = వెళ్లే క్యారీ',
    fa_how: 'మూడింటిలో కనీసం రెండు ఇన్‌పుట్‌లు 1 అయితే Cout = 1.',
    read_bin: 'క్యారీ, మొత్తం కలిపి ఒక బైనరీ సంఖ్యగా చదవండి: {bin} = దశాంశంలో {d}.',
    four_desc: 'నాలుగు ఫుల్ యాడర్‌ల గొలుసు రెండు 4-బిట్ సంఖ్యలను (0 నుంచి 15) కలుపుతుంది. ప్రతి క్యారీ ఎడమవైపు తర్వాతి స్థానానికి అలలా వెళ్తుంది.',
    place_val: 'స్థాన విలువ', carry_row: 'క్యారీ',
    bit_aria: '{v}లో {p} స్థానపు బిట్ {x}. మార్చడానికి నొక్కండి.',
    final_carry: 'చివరి క్యారీ సమాధానంలో ఐదవ బిట్ అవుతుంది.',
    tap_bits: 'సంఖ్యలు మార్చడానికి A, B బిట్‌లను తాకండి.',
    mode_fill: 'టేబుల్ నింపండి', mode_name: 'గేట్‌ను గుర్తించండి',
    level: 'స్థాయి', easy: 'సులభం', medium: 'మధ్యస్థం', hard: 'కఠినం', streak: 'వరుసగా సరి', best: 'ఉత్తమం',
    fill_q: 'దీనికి అవుట్‌పుట్ నిలువు వరుస Y నింపండి:',
    tap_cells: 'ప్రతి ?ను తాకి 0 లేదా 1 ఎంచుకోండి, తర్వాత “సరిచూడు” నొక్కండి.',
    cell_aria: 'వరుస {n}: అవుట్‌పుట్ Y ఇప్పుడు {x}. మార్చడానికి నొక్కండి.',
    show_answer: 'సమాధానం చూపించు', new_question: 'కొత్త ప్రశ్న',
    fill_all: 'ముందుగా అన్ని వరుసలు నింపండి.',
    all_right: 'అన్ని {n} వరుసలు సరైనవి. భేష్!',
    some_wrong: '{n} వరుసలలో {k} సరైనవి. ఎరుపు వాటిని సరిచేసి మళ్లీ చూడండి.',
    answer_shown: 'ఇదిగో సమాధానం. జాగ్రత్తగా చూడండి, తర్వాత కొత్త ప్రశ్న ప్రయత్నించండి.',
    name_q: 'ఏ గేట్ ఈ ట్రూత్ టేబుల్ ఇస్తుంది?',
    name_right: 'అవును! ఇది {g} గేట్.',
    name_wrong: 'సరి కాదు. ఇది {g} గేట్.',
    ws_hint: 'ఈ స్థాయిలో 8 ట్రూత్ టేబుల్ ప్రశ్నలను జవాబుల పట్టికతో ప్రింట్ చేయండి.',
    print_ws: 'వర్క్‌షీట్ ప్రింట్ చేయండి', ws_title: 'లాజిక్ గేట్ వర్క్‌షీట్',
    ws_intro: 'ప్రతి ట్రూత్ టేబుల్‌లో అవుట్‌పుట్ నిలువు వరుస Y నింపండి.',
    ws_name: 'పేరు', ws_class: 'తరగతి', ws_date: 'తేదీ', answer_key: 'జవాబుల పట్టిక',
    help_title: 'ఎలా వాడాలి / తరగతి గది కోసం ఆలోచనలు',
    help_1: 'గేట్‌లు: ఒక గేట్‌ను ఎంచుకుని స్విచ్‌లను తాకండి. బల్బు అవుట్‌పుట్ Yని చూపిస్తుంది, ట్రూత్ టేబుల్‌లో సరిపోయే వరుస వెలుగుతుంది.',
    help_2: 'ఎక్స్‌ప్రెషన్ ల్యాబ్: (A + B)·C\' లేదా NOT (A AND B) లాంటిది టైప్ చేయండి. దశల నిలువు వరుసలతో ట్రూత్ టేబుల్, వెంటనే పరీక్షించగల సర్క్యూట్ వస్తాయి.',
    help_3: '“రెండు ఎక్స్‌ప్రెషన్‌లు సమానమా?” తో డి మోర్గాన్ నియమాలను నిరూపించండి. సమానం కాకపోతే, అవి వేరుపడే వరుసను యాప్ చూపిస్తుంది.',
    help_4: 'యాడర్‌లు: కంప్యూటర్ హాఫ్ యాడర్, ఫుల్ యాడర్‌లతో బైనరీ సంఖ్యలను ఎలా కలుపుతుందో చూడండి, తర్వాత రెండు 4-బిట్ సంఖ్యలను కలపండి.',
    help_5: 'తరగతి కార్యకలాపం “మనిషి లాజిక్ గేట్”: ఇద్దరు విద్యార్థులు ఇన్‌పుట్‌లు A, B (చేయి పైకి = 1). మూడో విద్యార్థి గేట్‌గా ఉండి, నియమం 1 అన్నప్పుడే చేయి ఎత్తాలి. తరగతి మొత్తం స్మార్ట్‌బోర్డ్‌పై సరిచూస్తుంది.',
    help_6: 'ఉపాధ్యాయులకు: సాధనలో స్థాయిని ఎంచుకుని “వర్క్‌షీట్ ప్రింట్ చేయండి” నొక్కితే, జవాబుల పట్టికతో 8 ప్రశ్నలు వస్తాయి.'
  },

  kn: {
    app_title: 'ಲಾಜಿಕ್ ಗೇಟ್ ಲ್ಯಾಬ್',
    intro: 'ಸ್ವಿಚ್ ಒತ್ತಿ ಲಾಜಿಕ್ ಗೇಟ್‌ಗಳು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತವೆ ಎಂದು ನೋಡಿ, ಬೂಲಿಯನ್ ಎಕ್ಸ್‌ಪ್ರೆಶನ್‌ಗಳಿಂದ ಟ್ರುತ್ ಟೇಬಲ್ ಮತ್ತು ಸರ್ಕ್ಯೂಟ್ ಮಾಡಿ, ಡಿ ಮಾರ್ಗನ್‌ನಂತಹ ನಿಯಮಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ ಮತ್ತು ಅಭ್ಯಾಸ ಮಾಡಿ.',
    tab_gates: 'ಗೇಟ್‌ಗಳು', tab_expr: 'ಎಕ್ಸ್‌ಪ್ರೆಶನ್ ಲ್ಯಾಬ್', tab_adders: 'ಆಡರ್‌ಗಳು', tab_practice: 'ಅಭ್ಯಾಸ',
    choose_gate: 'ಗೇಟ್', inputs: 'ಇನ್‌ಪುಟ್‌ಗಳು', n_inputs: '{n} ಇನ್‌ಪುಟ್‌ಗಳು', one_input: '1 ಇನ್‌ಪುಟ್', gate_name: '{g} ಗೇಟ್',
    tap_switch: 'ಸ್ವಿಚ್ ಮುಟ್ಟಿ 0 ಮತ್ತು 1 ನಡುವೆ ಬದಲಿಸಿ. ಟೇಬಲ್‌ನ ಯಾವುದೇ ಸಾಲನ್ನು ಮುಟ್ಟಿದರೆ ನೇರವಾಗಿ ಅಲ್ಲಿಗೆ ಹೋಗುತ್ತದೆ.',
    kbd_hint: 'ಕೀಬೋರ್ಡ್‌ನಲ್ಲಿ A, B ಅಥವಾ C ಒತ್ತಿಯೂ ಇನ್‌ಪುಟ್ ಬದಲಿಸಬಹುದು.',
    expression: 'ಬೂಲಿಯನ್ ಎಕ್ಸ್‌ಪ್ರೆಶನ್', rule: 'ನಿಯಮ', real_life: 'ನಿಜ ಜೀವನದ ಉದಾಹರಣೆ', truth_table: 'ಟ್ರುತ್ ಟೇಬಲ್ (ಸತ್ಯ ಕೋಷ್ಟಕ)',
    rule_and: 'ಎಲ್ಲಾ ಇನ್‌ಪುಟ್‌ಗಳು 1 ಆಗಿದ್ದರೆ ಮಾತ್ರ Y = 1.',
    rule_or: 'ಕನಿಷ್ಠ ಒಂದು ಇನ್‌ಪುಟ್ 1 ಆಗಿದ್ದರೆ Y = 1.',
    rule_not: 'Y ಇನ್‌ಪುಟ್‌ನ ವಿರುದ್ಧ: 0 ಆದರೆ 1, 1 ಆದರೆ 0.',
    rule_nand: 'NOT + AND: ಎಲ್ಲಾ ಇನ್‌ಪುಟ್‌ಗಳು 1 ಆಗಿದ್ದಾಗ ಮಾತ್ರ Y = 0.',
    rule_nor: 'NOT + OR: ಎಲ್ಲಾ ಇನ್‌ಪುಟ್‌ಗಳು 0 ಆಗಿದ್ದಾಗ ಮಾತ್ರ Y = 1.',
    rule_xor: 'ಬೆಸ ಸಂಖ್ಯೆಯ ಇನ್‌ಪುಟ್‌ಗಳು 1 ಆಗಿದ್ದರೆ Y = 1. ಎರಡು ಇನ್‌ಪುಟ್‌ಗಳಲ್ಲಿ: ಎರಡೂ ಬೇರೆಯಾಗಿದ್ದಾಗ.',
    rule_xnor: 'NOT + XOR: ಸಮ ಸಂಖ್ಯೆಯ ಇನ್‌ಪುಟ್‌ಗಳು 1 ಆಗಿದ್ದರೆ Y = 1. ಎರಡು ಇನ್‌ಪುಟ್‌ಗಳಲ್ಲಿ: ಎರಡೂ ಒಂದೇ ಆಗಿದ್ದಾಗ.',
    life_and: 'ಮೇನ್ ಸ್ವಿಚ್ ಮತ್ತು ಫ್ಯಾನ್ ಸ್ವಿಚ್ ಎರಡೂ ಆನ್ ಇದ್ದರೆ ಮಾತ್ರ ಸೀಲಿಂಗ್ ಫ್ಯಾನ್ ತಿರುಗುತ್ತದೆ.',
    life_or: 'ಕಚೇರಿ ಅಥವಾ ಸ್ಟಾಫ್ ರೂಮ್, ಯಾರೇ ಬಟನ್ ಒತ್ತಿದರೂ ಶಾಲೆಯ ಗಂಟೆ ಬಾರಿಸುತ್ತದೆ.',
    life_not: 'ವಿದ್ಯುತ್ ಇಲ್ಲದಿದ್ದಾಗ (ಪವರ್ ಕಟ್ ಆದಾಗ) ಮನೆಯ ಇನ್ವರ್ಟರ್ ಆನ್ ಆಗುತ್ತದೆ.',
    life_nand: 'ಮುಂದಿನ ಎರಡೂ ಸೀಟ್ ಬೆಲ್ಟ್ ಹಾಕುವವರೆಗೆ ಕಾರಿನ ಸೀಟ್-ಬೆಲ್ಟ್ ಅಲಾರಂ ಸದ್ದು ಮಾಡುತ್ತಲೇ ಇರುತ್ತದೆ.',
    life_nor: 'ಟ್ಯಾಂಕ್ ತುಂಬಿಲ್ಲ ಮತ್ತು ವೋಲ್ಟೇಜ್ ಕಡಿಮೆ ಇಲ್ಲ ಎಂದಾಗ ಮಾತ್ರ ನೀರಿನ ಮೋಟಾರ್ ಮೇಲಿನ ಟ್ಯಾಂಕ್ ತುಂಬಿಸುತ್ತದೆ.',
    life_xor: 'ಮೆಟ್ಟಿಲಿನ ದೀಪಕ್ಕೆ ಎರಡು ಸ್ವಿಚ್‌ಗಳು: ಮೇಲೆ ಅಥವಾ ಕೆಳಗೆ, ಯಾವುದೇ ಒಂದು ಸ್ವಿಚ್ ಬದಲಿಸಿದರೂ ದೀಪ ಬದಲಾಗುತ್ತದೆ.',
    life_xnor: 'ಉತ್ತರ ಪರೀಕ್ಷಿಸುವ ಯಂತ್ರ: ನಿಮ್ಮ ಉತ್ತರ ಮತ್ತು ಸರಿಯಾದ ಉತ್ತರ ಒಂದೇ ಆದಾಗ ಹಸಿರು ದೀಪ ಉರಿಯುತ್ತದೆ.',
    universal: 'NAND ಮತ್ತು NOR ಅನ್ನು ಯೂನಿವರ್ಸಲ್ ಗೇಟ್‌ಗಳು ಎನ್ನುತ್ತಾರೆ: ಕೇವಲ NAND ಗೇಟ್‌ಗಳಿಂದ (ಅಥವಾ ಕೇವಲ NOR ಗೇಟ್‌ಗಳಿಂದ) ಯಾವುದೇ ಸರ್ಕ್ಯೂಟ್ ಮಾಡಬಹುದು.',
    all_gates: 'ಎಲ್ಲಾ ಗೇಟ್‌ಗಳು ಒಂದೇ ನೋಟದಲ್ಲಿ',
    all_gates_hint: 'ಹೈಲೈಟ್ ಮಾಡಿದ ಸಾಲು ಸ್ವಿಚ್ A ಮತ್ತು B ಗೆ ಹೊಂದುತ್ತದೆ. ಬದಲಿಸಲು ಯಾವುದೇ ಸಾಲನ್ನು ಮುಟ್ಟಿ.',
    sw_aria: 'ಇನ್‌ಪುಟ್ {v} ಈಗ {x}. ಬದಲಿಸಲು ಒತ್ತಿ.',
    out_aria: 'ಔಟ್‌ಪುಟ್ {v} ಈಗ {x}',
    expr_label: 'ಬೂಲಿಯನ್ ಎಕ್ಸ್‌ಪ್ರೆಶನ್ ಟೈಪ್ ಮಾಡಿ',
    expr_help: 'A ಯಿಂದ E ವರೆಗಿನ ಚರಗಳೊಂದಿಗೆ AND, OR, NOT, XOR, NAND, NOR, XNOR ಅಥವಾ · + \' ⊕ ಚಿಹ್ನೆಗಳು ಮತ್ತು ಆವರಣಗಳನ್ನು ಬಳಸಿ. AB ಎಂದರೆ A·B.',
    examples: 'ಉದಾಹರಣೆಗಳು', backspace: 'ಒಂದು ಅಕ್ಷರ ಅಳಿಸಿ', copy_link: 'ಲಿಂಕ್ ನಕಲಿಸಿ',
    circuit: 'ಸರ್ಕ್ಯೂಟ್ ಚಿತ್ರ',
    circuit_hint: 'ಚಿತ್ರದಲ್ಲಿನ ಯಾವುದೇ ಇನ್‌ಪುಟ್ (A, B…) ಅಥವಾ ಮೇಲಿನ ಬಟನ್ ಮುಟ್ಟಿ ಬದಲಿಸಿ. ಹಸಿರು ತಂತಿಯಲ್ಲಿ 1, ಬೂದು ತಂತಿಯಲ್ಲಿ 0.',
    too_big: 'ಈ ಎಕ್ಸ್‌ಪ್ರೆಶನ್ ಅಚ್ಚುಕಟ್ಟಾಗಿ ಚಿತ್ರಿಸಲು ತುಂಬಾ ದೊಡ್ಡದು. ಟ್ರುತ್ ಟೇಬಲ್ ಆದರೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
    no_inputs: 'ಯಾವುದೇ ಚರಗಳಿಲ್ಲ: ಔಟ್‌ಪುಟ್ ಎಂದಿಗೂ ಬದಲಾಗುವುದಿಲ್ಲ.',
    show_steps: 'ನಡುವಿನ ಹಂತಗಳ ಕಾಲಮ್‌ಗಳನ್ನು ತೋರಿಸಿ',
    row_hint: 'ಯಾವುದೇ ಸಾಲು ಮುಟ್ಟಿ ಎಲ್ಲಾ ಇನ್‌ಪುಟ್‌ಗಳನ್ನು ಒಮ್ಮೆಲೇ ಹೊಂದಿಸಿ.',
    always_1: 'Y ಯಾವಾಗಲೂ 1 (ಟಾಟಾಲಜಿ).',
    always_0: 'Y ಯಾವಾಗಲೂ 0 (ವಿರೋಧಾಭಾಸ).',
    ones_in: '{n} ಸಾಲುಗಳ ಪೈಕಿ {k} ಸಾಲುಗಳಲ್ಲಿ Y = 1:',
    err_empty: 'ಆರಂಭಿಸಲು ಒಂದು ಎಕ್ಸ್‌ಪ್ರೆಶನ್ ಟೈಪ್ ಮಾಡಿ, ಉದಾ. A·B + C.',
    err_unknown: 'ಗೊತ್ತಿಲ್ಲದ ಅಕ್ಷರ “{ch}”. A, B, C, D, E ಚರಗಳನ್ನು ಮಾತ್ರ ಬಳಸಿ.',
    err_symbol: 'ಸ್ಥಾನ {n} ನಲ್ಲಿರುವ “{ch}” ಚಿಹ್ನೆ ಅರ್ಥವಾಗಲಿಲ್ಲ.',
    err_close: 'ಸ್ಥಾನ {n} ನಲ್ಲಿ ತೆರೆದ ಆವರಣ ಮುಚ್ಚಿಲ್ಲ. ಒಂದು “)” ಸೇರಿಸಿ.',
    err_extra_close: 'ಸ್ಥಾನ {n} ನಲ್ಲಿ ಒಂದು “)” ಹೆಚ್ಚಾಗಿದೆ.',
    err_operand: 'ಸ್ಥಾನ {n} ನಲ್ಲಿ ಏನೋ ಬಿಟ್ಟುಹೋಗಿದೆ. ಅಲ್ಲಿ ಒಂದು ಚರ, 0, 1 ಅಥವಾ “(” ಹಾಕಿ.',
    err_end: 'ಎಕ್ಸ್‌ಪ್ರೆಶನ್ ಅಪೂರ್ಣವಾಗಿದೆ. ಕೊನೆಯ ಚಿಹ್ನೆಯ ನಂತರ ಒಂದು ಚರ ಸೇರಿಸಿ.',
    err_too_long: 'ಎಕ್ಸ್‌ಪ್ರೆಶನ್ ತುಂಬಾ ಉದ್ದವಾಗಿದೆ. ಅದನ್ನು {n} ಅಕ್ಷರಗಳೊಳಗೆ ಇಡಿ.',
    equiv_title: 'ಎರಡು ಎಕ್ಸ್‌ಪ್ರೆಶನ್‌ಗಳು ಸಮವೇ?',
    equiv_intro: 'ಎರಡು ಎಕ್ಸ್‌ಪ್ರೆಶನ್‌ಗಳನ್ನು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಒಂದು ನಿಯಮ ಆಯ್ಕೆ ಮಾಡಿ. ಆ್ಯಪ್ ಟ್ರುತ್ ಟೇಬಲ್‌ನ ಪ್ರತಿಯೊಂದು ಸಾಲನ್ನೂ ಪರೀಕ್ಷಿಸುತ್ತದೆ.',
    try_law: 'ಒಂದು ನಿಯಮ ಪ್ರಯತ್ನಿಸಿ:',
    law_dm1: 'ಡಿ ಮಾರ್ಗನ್ ನಿಯಮ 1', law_dm2: 'ಡಿ ಮಾರ್ಗನ್ ನಿಯಮ 2',
    law_abs1: 'ಹೀರಿಕೆ ನಿಯಮ', law_abs2: 'ಹೀರಿಕೆ ನಿಯಮ (ದ್ವಂದ್ವ)',
    law_dist1: 'ವಿತರಣಾ ನಿಯಮ', law_dist2: 'ವಿತರಣಾ ನಿಯಮ (ದ್ವಂದ್ವ)',
    law_xor: 'AND, OR, NOT ಬಳಸಿ XOR', law_dneg: 'ಎರಡು ಬಾರಿ NOT', law_nand: 'NAND ಗೇಟ್‌ನಿಂದ NOT', law_mistake: 'ಒಂದು ಸಾಮಾನ್ಯ ತಪ್ಪು',
    expr1: 'ಮೊದಲ ಎಕ್ಸ್‌ಪ್ರೆಶನ್', expr2: 'ಎರಡನೇ ಎಕ್ಸ್‌ಪ್ರೆಶನ್', check: 'ಪರೀಕ್ಷಿಸಿ',
    equiv_yes: 'ಸಮ ✓ ಎಲ್ಲಾ {n} ಸಾಲುಗಳಲ್ಲಿ ಎರಡೂ ಒಂದೇ ಔಟ್‌ಪುಟ್ ಕೊಡುತ್ತವೆ.',
    equiv_no: 'ಸಮವಲ್ಲ ✗',
    equiv_detail: 'ಪ್ರತ್ಯುದಾಹರಣೆ: {vals} ಆದಾಗ, ಮೊದಲನೆಯದು {a} ಕೊಡುತ್ತದೆ ಆದರೆ ಎರಡನೆಯದು {b} ಕೊಡುತ್ತದೆ.',
    col_first: 'ಮೊದಲ', col_second: 'ಎರಡನೇ', same: 'ಒಂದೇ?',
    half_adder: 'ಹಾಫ್ ಆಡರ್', full_adder: 'ಫುಲ್ ಆಡರ್', four_bit: '4-ಬಿಟ್ ಆಡರ್',
    ha_desc: 'ಹಾಫ್ ಆಡರ್ A ಮತ್ತು B ಎಂಬ ಎರಡು ಬಿಟ್‌ಗಳನ್ನು ಕೂಡಿಸುತ್ತದೆ. ಅದು ಒಂದು ಮೊತ್ತದ ಬಿಟ್ (S) ಮತ್ತು ಒಂದು ಕ್ಯಾರಿ ಬಿಟ್ (C) ಕೊಡುತ್ತದೆ.',
    legend_ha: 'S = ಮೊತ್ತ (Sum), C = ಕ್ಯಾರಿ (Carry)',
    why_carry: 'ಕ್ಯಾರಿ ಏಕೆ? ಬೈನರಿಯಲ್ಲಿ 1 + 1 = 10. ನಾವು 0 ಬರೆದು 1 ಅನ್ನು ಮುಂದಿನ ಸ್ಥಾನಕ್ಕೆ ಒಯ್ಯುತ್ತೇವೆ, ದಶಮಾಂಶದಲ್ಲಿ 5 + 5 = 10 ಇದ್ದಂತೆ.',
    fa_desc: 'ಫುಲ್ ಆಡರ್ ಮೂರು ಬಿಟ್‌ಗಳನ್ನು ಕೂಡಿಸುತ್ತದೆ: A, B ಮತ್ತು ಹಿಂದಿನ ಸ್ಥಾನದಿಂದ ಬಂದ ಕ್ಯಾರಿ (Cin). ಇದು ಎರಡು ಹಾಫ್ ಆಡರ್ ಮತ್ತು ಒಂದು OR ಗೇಟ್‌ನಿಂದ ಆಗಿದೆ.',
    legend_fa: 'Cin = ಬರುವ ಕ್ಯಾರಿ, S = ಮೊತ್ತ, Cout = ಹೋಗುವ ಕ್ಯಾರಿ',
    fa_how: 'ಮೂರರಲ್ಲಿ ಕನಿಷ್ಠ ಎರಡು ಇನ್‌ಪುಟ್‌ಗಳು 1 ಆಗಿದ್ದರೆ Cout = 1.',
    read_bin: 'ಕ್ಯಾರಿ ಮತ್ತು ಮೊತ್ತವನ್ನು ಒಟ್ಟಿಗೆ ಒಂದು ಬೈನರಿ ಸಂಖ್ಯೆಯಾಗಿ ಓದಿ: {bin} = ದಶಮಾಂಶದಲ್ಲಿ {d}.',
    four_desc: 'ನಾಲ್ಕು ಫುಲ್ ಆಡರ್‌ಗಳ ಸರಪಳಿ ಎರಡು 4-ಬಿಟ್ ಸಂಖ್ಯೆಗಳನ್ನು (0 ರಿಂದ 15) ಕೂಡಿಸುತ್ತದೆ. ಪ್ರತಿ ಕ್ಯಾರಿ ಎಡಬದಿಯ ಮುಂದಿನ ಸ್ಥಾನಕ್ಕೆ ಅಲೆಯಂತೆ ಹೋಗುತ್ತದೆ.',
    place_val: 'ಸ್ಥಾನ ಬೆಲೆ', carry_row: 'ಕ್ಯಾರಿ',
    bit_aria: '{v} ನಲ್ಲಿ {p} ಸ್ಥಾನದ ಬಿಟ್ {x}. ಬದಲಿಸಲು ಒತ್ತಿ.',
    final_carry: 'ಕೊನೆಯ ಕ್ಯಾರಿ ಉತ್ತರದ ಐದನೇ ಬಿಟ್ ಆಗುತ್ತದೆ.',
    tap_bits: 'ಸಂಖ್ಯೆಗಳನ್ನು ಬದಲಿಸಲು A ಮತ್ತು B ಬಿಟ್‌ಗಳನ್ನು ಮುಟ್ಟಿ.',
    mode_fill: 'ಟೇಬಲ್ ಪೂರ್ಣಗೊಳಿಸಿ', mode_name: 'ಗೇಟ್ ಗುರುತಿಸಿ',
    level: 'ಮಟ್ಟ', easy: 'ಸುಲಭ', medium: 'ಮಧ್ಯಮ', hard: 'ಕಠಿಣ', streak: 'ಸತತ ಸರಿ', best: 'ಅತ್ಯುತ್ತಮ',
    fill_q: 'ಇದಕ್ಕೆ ಔಟ್‌ಪುಟ್ ಕಾಲಮ್ Y ತುಂಬಿ:',
    tap_cells: 'ಪ್ರತಿ ? ಮುಟ್ಟಿ 0 ಅಥವಾ 1 ಆಯ್ಕೆ ಮಾಡಿ, ನಂತರ “ಪರೀಕ್ಷಿಸಿ” ಒತ್ತಿ.',
    cell_aria: 'ಸಾಲು {n}: ಔಟ್‌ಪುಟ್ Y ಈಗ {x}. ಬದಲಿಸಲು ಒತ್ತಿ.',
    show_answer: 'ಉತ್ತರ ತೋರಿಸಿ', new_question: 'ಹೊಸ ಪ್ರಶ್ನೆ',
    fill_all: 'ಮೊದಲು ಪ್ರತಿ ಸಾಲನ್ನೂ ತುಂಬಿ.',
    all_right: 'ಎಲ್ಲಾ {n} ಸಾಲುಗಳು ಸರಿ. ಭೇಷ್!',
    some_wrong: '{n} ಸಾಲುಗಳಲ್ಲಿ {k} ಸರಿ. ಕೆಂಪು ಸಾಲುಗಳನ್ನು ಸರಿಪಡಿಸಿ ಮತ್ತೆ ಪರೀಕ್ಷಿಸಿ.',
    answer_shown: 'ಇಲ್ಲಿದೆ ಉತ್ತರ. ಗಮನವಿಟ್ಟು ನೋಡಿ, ನಂತರ ಹೊಸ ಪ್ರಶ್ನೆ ಪ್ರಯತ್ನಿಸಿ.',
    name_q: 'ಯಾವ ಗೇಟ್ ಈ ಟ್ರುತ್ ಟೇಬಲ್ ಕೊಡುತ್ತದೆ?',
    name_right: 'ಹೌದು! ಇದು {g} ಗೇಟ್.',
    name_wrong: 'ಸರಿಯಲ್ಲ. ಇದು {g} ಗೇಟ್.',
    ws_hint: 'ಈ ಮಟ್ಟದ 8 ಟ್ರುತ್ ಟೇಬಲ್ ಪ್ರಶ್ನೆಗಳನ್ನು ಉತ್ತರ ಸೂಚಿಯೊಂದಿಗೆ ಮುದ್ರಿಸಿ.',
    print_ws: 'ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ', ws_title: 'ಲಾಜಿಕ್ ಗೇಟ್ ವರ್ಕ್‌ಶೀಟ್',
    ws_intro: 'ಪ್ರತಿ ಟ್ರುತ್ ಟೇಬಲ್‌ನ ಔಟ್‌ಪುಟ್ ಕಾಲಮ್ Y ತುಂಬಿ.',
    ws_name: 'ಹೆಸರು', ws_class: 'ತರಗತಿ', ws_date: 'ದಿನಾಂಕ', answer_key: 'ಉತ್ತರ ಸೂಚಿ',
    help_title: 'ಹೇಗೆ ಬಳಸುವುದು / ತರಗತಿಗೆ ಐಡಿಯಾಗಳು',
    help_1: 'ಗೇಟ್‌ಗಳು: ಒಂದು ಗೇಟ್ ಆಯ್ಕೆ ಮಾಡಿ ಸ್ವಿಚ್‌ಗಳನ್ನು ಮುಟ್ಟಿ. ಬಲ್ಬ್ ಔಟ್‌ಪುಟ್ Y ತೋರಿಸುತ್ತದೆ ಮತ್ತು ಟ್ರುತ್ ಟೇಬಲ್‌ನ ಹೊಂದುವ ಸಾಲು ಬೆಳಗುತ್ತದೆ.',
    help_2: 'ಎಕ್ಸ್‌ಪ್ರೆಶನ್ ಲ್ಯಾಬ್: (A + B)·C\' ಅಥವಾ NOT (A AND B) ನಂತಹದ್ದನ್ನು ಟೈಪ್ ಮಾಡಿ. ಹಂತಗಳ ಕಾಲಮ್‌ಗಳಿರುವ ಟ್ರುತ್ ಟೇಬಲ್ ಮತ್ತು ತಕ್ಷಣ ಪರೀಕ್ಷಿಸಬಹುದಾದ ಸರ್ಕ್ಯೂಟ್ ಸಿಗುತ್ತದೆ.',
    help_3: '“ಎರಡು ಎಕ್ಸ್‌ಪ್ರೆಶನ್‌ಗಳು ಸಮವೇ?” ಬಳಸಿ ಡಿ ಮಾರ್ಗನ್ ನಿಯಮಗಳನ್ನು ಸಾಬೀತುಪಡಿಸಿ. ಸಮವಲ್ಲದಿದ್ದರೆ, ಅವು ಬೇರೆಯಾಗುವ ಸಾಲನ್ನು ಆ್ಯಪ್ ತೋರಿಸುತ್ತದೆ.',
    help_4: 'ಆಡರ್‌ಗಳು: ಕಂಪ್ಯೂಟರ್ ಹಾಫ್ ಆಡರ್ ಮತ್ತು ಫುಲ್ ಆಡರ್‌ಗಳಿಂದ ಬೈನರಿ ಸಂಖ್ಯೆಗಳನ್ನು ಹೇಗೆ ಕೂಡಿಸುತ್ತದೆ ಎಂದು ನೋಡಿ, ನಂತರ ಎರಡು 4-ಬಿಟ್ ಸಂಖ್ಯೆಗಳನ್ನು ಕೂಡಿಸಿ.',
    help_5: 'ತರಗತಿ ಚಟುವಟಿಕೆ “ಮಾನವ ಲಾಜಿಕ್ ಗೇಟ್”: ಇಬ್ಬರು ವಿದ್ಯಾರ್ಥಿಗಳು ಇನ್‌ಪುಟ್ A ಮತ್ತು B (ಕೈ ಮೇಲೆ = 1). ಮೂರನೆಯವರು ಗೇಟ್ ಆಗಿ, ನಿಯಮ 1 ಎಂದಾಗ ಮಾತ್ರ ಕೈ ಎತ್ತುತ್ತಾರೆ. ಇಡೀ ತರಗತಿ ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಪರೀಕ್ಷಿಸುತ್ತದೆ.',
    help_6: 'ಶಿಕ್ಷಕರಿಗೆ: ಅಭ್ಯಾಸದಲ್ಲಿ ಮಟ್ಟ ಆಯ್ಕೆ ಮಾಡಿ “ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ” ಒತ್ತಿದರೆ, ಉತ್ತರ ಸೂಚಿಯೊಂದಿಗೆ 8 ಪ್ರಶ್ನೆಗಳು ಸಿಗುತ್ತವೆ.'
  },

  ml: {
    app_title: 'ലോജിക് ഗേറ്റ് ലാബ്',
    intro: 'സ്വിച്ചുകൾ അമർത്തി ലോജിക് ഗേറ്റുകൾ എങ്ങനെ പ്രവർത്തിക്കുന്നു എന്ന് കാണൂ, ബൂളിയൻ എക്സ്പ്രഷനുകളിൽ നിന്ന് ട്രൂത്ത് ടേബിളും സർക്യൂട്ടും ഉണ്ടാക്കൂ, ഡി മോർഗൻ പോലുള്ള നിയമങ്ങൾ പരിശോധിക്കൂ, പരിശീലിക്കൂ.',
    tab_gates: 'ഗേറ്റുകൾ', tab_expr: 'എക്സ്പ്രഷൻ ലാബ്', tab_adders: 'ആഡറുകൾ', tab_practice: 'പരിശീലനം',
    choose_gate: 'ഗേറ്റ്', inputs: 'ഇൻപുട്ടുകൾ', n_inputs: '{n} ഇൻപുട്ടുകൾ', one_input: '1 ഇൻപുട്ട്', gate_name: '{g} ഗേറ്റ്',
    tap_switch: 'സ്വിച്ചിൽ തൊട്ട് 0, 1 എന്നിവയ്ക്കിടയിൽ മാറ്റൂ. ടേബിളിലെ ഒരു വരിയിൽ തൊട്ടാൽ നേരെ അവിടേക്ക് പോകും.',
    kbd_hint: 'കീബോർഡിൽ A, B അല്ലെങ്കിൽ C അമർത്തിയും ഇൻപുട്ട് മാറ്റാം.',
    expression: 'ബൂളിയൻ എക്സ്പ്രഷൻ', rule: 'നിയമം', real_life: 'യഥാർഥ ജീവിതത്തിലെ ഉദാഹരണം', truth_table: 'ട്രൂത്ത് ടേബിൾ (സത്യ പട്ടിക)',
    rule_and: 'എല്ലാ ഇൻപുട്ടുകളും 1 ആണെങ്കിൽ മാത്രം Y = 1.',
    rule_or: 'കുറഞ്ഞത് ഒരു ഇൻപുട്ട് 1 ആണെങ്കിൽ Y = 1.',
    rule_not: 'Y ഇൻപുട്ടിന്റെ വിപരീതമാണ്: 0 ആണെങ്കിൽ 1, 1 ആണെങ്കിൽ 0.',
    rule_nand: 'NOT + AND: എല്ലാ ഇൻപുട്ടുകളും 1 ആകുമ്പോൾ മാത്രം Y = 0.',
    rule_nor: 'NOT + OR: എല്ലാ ഇൻപുട്ടുകളും 0 ആകുമ്പോൾ മാത്രം Y = 1.',
    rule_xor: 'ഒറ്റ എണ്ണം ഇൻപുട്ടുകൾ 1 ആണെങ്കിൽ Y = 1. രണ്ട് ഇൻപുട്ടുകളിൽ: രണ്ടും വ്യത്യസ്തമാകുമ്പോൾ.',
    rule_xnor: 'NOT + XOR: ഇരട്ട എണ്ണം ഇൻപുട്ടുകൾ 1 ആണെങ്കിൽ Y = 1. രണ്ട് ഇൻപുട്ടുകളിൽ: രണ്ടും ഒന്നാകുമ്പോൾ.',
    life_and: 'മെയിൻ സ്വിച്ചും ഫാൻ സ്വിച്ചും രണ്ടും ഓൺ ആണെങ്കിൽ മാത്രമേ സീലിങ് ഫാൻ കറങ്ങൂ.',
    life_or: 'ഓഫീസോ സ്റ്റാഫ് റൂമോ, ആര് ബട്ടൺ അമർത്തിയാലും സ്കൂൾ ബെൽ അടിക്കും.',
    life_not: 'കറന്റ് ഇല്ലാത്തപ്പോൾ (പവർ കട്ട് സമയത്ത്) വീട്ടിലെ ഇൻവെർട്ടർ ഓണാകും.',
    life_nand: 'മുന്നിലെ രണ്ട് സീറ്റ് ബെൽറ്റും ഇടുന്നതുവരെ കാറിന്റെ സീറ്റ്-ബെൽറ്റ് അലാറം അടിച്ചുകൊണ്ടിരിക്കും.',
    life_nor: 'ടാങ്ക് നിറഞ്ഞിട്ടില്ല, വോൾട്ടേജ് കുറവുമല്ല എങ്കിൽ മാത്രമേ വെള്ളത്തിന്റെ മോട്ടോർ മുകളിലെ ടാങ്ക് നിറയ്ക്കൂ.',
    life_xor: 'കോണിപ്പടിയിലെ ലൈറ്റിന് രണ്ട് സ്വിച്ചുകൾ: മുകളിലോ താഴെയോ, ഏതെങ്കിലും ഒരു സ്വിച്ച് മാറ്റിയാൽ ലൈറ്റ് മാറും.',
    life_xnor: 'ഉത്തരം പരിശോധിക്കുന്ന യന്ത്രം: നിങ്ങളുടെ ഉത്തരവും ശരിയുത്തരവും ഒന്നാകുമ്പോൾ പച്ച ലൈറ്റ് തെളിയും.',
    universal: 'NAND, NOR എന്നിവയെ യൂണിവേഴ്സൽ ഗേറ്റുകൾ എന്ന് വിളിക്കുന്നു: NAND ഗേറ്റുകൾ മാത്രം (അല്ലെങ്കിൽ NOR ഗേറ്റുകൾ മാത്രം) ഉപയോഗിച്ച് ഏത് സർക്യൂട്ടും ഉണ്ടാക്കാം.',
    all_gates: 'എല്ലാ ഗേറ്റുകളും ഒറ്റനോട്ടത്തിൽ',
    all_gates_hint: 'ഹൈലൈറ്റ് ചെയ്ത വരി സ്വിച്ച് A, B എന്നിവയുമായി യോജിക്കുന്നു. മാറ്റാൻ ഒരു വരിയിൽ തൊടൂ.',
    sw_aria: 'ഇൻപുട്ട് {v} ഇപ്പോൾ {x}. മാറ്റാൻ അമർത്തൂ.',
    out_aria: 'ഔട്ട്പുട്ട് {v} ഇപ്പോൾ {x}',
    expr_label: 'ഒരു ബൂളിയൻ എക്സ്പ്രഷൻ ടൈപ്പ് ചെയ്യൂ',
    expr_help: 'A മുതൽ E വരെയുള്ള ചരങ്ങൾക്കൊപ്പം AND, OR, NOT, XOR, NAND, NOR, XNOR അല്ലെങ്കിൽ · + \' ⊕ ചിഹ്നങ്ങളും ബ്രാക്കറ്റുകളും ഉപയോഗിക്കൂ. AB എന്നാൽ A·B.',
    examples: 'ഉദാഹരണങ്ങൾ', backspace: 'ഒരു അക്ഷരം മായ്ക്കുക', copy_link: 'ലിങ്ക് കോപ്പി ചെയ്യൂ',
    circuit: 'സർക്യൂട്ട് ചിത്രം',
    circuit_hint: 'ചിത്രത്തിലെ ഒരു ഇൻപുട്ടിലോ (A, B…) മുകളിലെ ബട്ടണിലോ തൊട്ട് മാറ്റൂ. പച്ച വയറിൽ 1, ചാര വയറിൽ 0.',
    too_big: 'ഈ എക്സ്പ്രഷൻ ഭംഗിയായി വരയ്ക്കാൻ വളരെ വലുതാണ്. ട്രൂത്ത് ടേബിൾ എന്നാലും പ്രവർത്തിക്കും.',
    no_inputs: 'ചരങ്ങൾ ഇല്ല: ഔട്ട്പുട്ട് ഒരിക്കലും മാറില്ല.',
    show_steps: 'ഇടയ്ക്കുള്ള ഘട്ടങ്ങളുടെ കോളങ്ങൾ കാണിക്കൂ',
    row_hint: 'ഒരു വരിയിൽ തൊട്ട് എല്ലാ ഇൻപുട്ടുകളും ഒറ്റയടിക്ക് സെറ്റ് ചെയ്യൂ.',
    always_1: 'Y എപ്പോഴും 1 (ടോട്ടോളജി).',
    always_0: 'Y എപ്പോഴും 0 (വൈരുധ്യം).',
    ones_in: '{n} വരികളിൽ {k} എണ്ണത്തിൽ Y = 1:',
    err_empty: 'തുടങ്ങാൻ ഒരു എക്സ്പ്രഷൻ ടൈപ്പ് ചെയ്യൂ, ഉദാ. A·B + C.',
    err_unknown: 'അറിയാത്ത അക്ഷരം “{ch}”. A, B, C, D, E എന്നീ ചരങ്ങൾ മാത്രം ഉപയോഗിക്കൂ.',
    err_symbol: 'സ്ഥാനം {n}-ലെ “{ch}” എന്ന ചിഹ്നം മനസ്സിലായില്ല.',
    err_close: 'സ്ഥാനം {n}-ൽ തുറന്ന ബ്രാക്കറ്റ് അടച്ചിട്ടില്ല. ഒരു “)” ചേർക്കൂ.',
    err_extra_close: 'സ്ഥാനം {n}-ൽ ഒരു “)” അധികമാണ്.',
    err_operand: 'സ്ഥാനം {n}-ൽ എന്തോ വിട്ടുപോയി. അവിടെ ഒരു ചരം, 0, 1 അല്ലെങ്കിൽ “(” ചേർക്കൂ.',
    err_end: 'എക്സ്പ്രഷൻ പൂർത്തിയായിട്ടില്ല. അവസാന ചിഹ്നത്തിന് ശേഷം ഒരു ചരം ചേർക്കൂ.',
    err_too_long: 'എക്സ്പ്രഷൻ വളരെ നീളമുള്ളതാണ്. {n} അക്ഷരങ്ങൾക്കുള്ളിൽ ഒതുക്കൂ.',
    equiv_title: 'രണ്ട് എക്സ്പ്രഷനുകൾ തുല്യമാണോ?',
    equiv_intro: 'രണ്ട് എക്സ്പ്രഷനുകൾ ടൈപ്പ് ചെയ്യൂ അല്ലെങ്കിൽ ഒരു നിയമം തിരഞ്ഞെടുക്കൂ. ആപ്പ് ട്രൂത്ത് ടേബിളിലെ ഓരോ വരിയും പരിശോധിക്കും.',
    try_law: 'ഒരു നിയമം പരീക്ഷിക്കൂ:',
    law_dm1: 'ഡി മോർഗൻ നിയമം 1', law_dm2: 'ഡി മോർഗൻ നിയമം 2',
    law_abs1: 'അബ്സോർപ്ഷൻ നിയമം', law_abs2: 'അബ്സോർപ്ഷൻ നിയമം (ദ്വൈതം)',
    law_dist1: 'വിതരണ നിയമം', law_dist2: 'വിതരണ നിയമം (ദ്വൈതം)',
    law_xor: 'AND, OR, NOT കൊണ്ട് XOR', law_dneg: 'ഇരട്ട NOT', law_nand: 'NAND ഗേറ്റിൽ നിന്ന് NOT', law_mistake: 'ഒരു സാധാരണ തെറ്റ്',
    expr1: 'ആദ്യ എക്സ്പ്രഷൻ', expr2: 'രണ്ടാം എക്സ്പ്രഷൻ', check: 'പരിശോധിക്കൂ',
    equiv_yes: 'തുല്യം ✓ എല്ലാ {n} വരികളിലും രണ്ടിനും ഒരേ ഔട്ട്പുട്ട്.',
    equiv_no: 'തുല്യമല്ല ✗',
    equiv_detail: 'എതിർ ഉദാഹരണം: {vals} ആകുമ്പോൾ, ആദ്യത്തേത് {a} നൽകുന്നു, പക്ഷേ രണ്ടാമത്തേത് {b} നൽകുന്നു.',
    col_first: 'ആദ്യത്തേത്', col_second: 'രണ്ടാമത്തേത്', same: 'ഒന്നാണോ?',
    half_adder: 'ഹാഫ് ആഡർ', full_adder: 'ഫുൾ ആഡർ', four_bit: '4-ബിറ്റ് ആഡർ',
    ha_desc: 'ഹാഫ് ആഡർ A, B എന്നീ രണ്ട് ബിറ്റുകൾ കൂട്ടുന്നു. ഇത് ഒരു തുക ബിറ്റും (S) ഒരു ക്യാരി ബിറ്റും (C) നൽകുന്നു.',
    legend_ha: 'S = തുക (Sum), C = ക്യാരി (Carry)',
    why_carry: 'ക്യാരി എന്തിന്? ബൈനറിയിൽ 1 + 1 = 10. നമ്മൾ 0 എഴുതി 1 അടുത്ത സ്ഥാനത്തേക്ക് കൊണ്ടുപോകുന്നു, ദശാംശത്തിൽ 5 + 5 = 10 പോലെ.',
    fa_desc: 'ഫുൾ ആഡർ മൂന്ന് ബിറ്റുകൾ കൂട്ടുന്നു: A, B, പിന്നെ മുൻ സ്ഥാനത്ത് നിന്ന് വരുന്ന ക്യാരി (Cin). രണ്ട് ഹാഫ് ആഡറുകളും ഒരു OR ഗേറ്റും ചേർന്നതാണ് ഇത്.',
    legend_fa: 'Cin = വരുന്ന ക്യാരി, S = തുക, Cout = പോകുന്ന ക്യാരി',
    fa_how: 'മൂന്നിൽ കുറഞ്ഞത് രണ്ട് ഇൻപുട്ടുകൾ 1 ആണെങ്കിൽ Cout = 1.',
    read_bin: 'ക്യാരിയും തുകയും ചേർത്ത് ഒരു ബൈനറി സംഖ്യയായി വായിക്കൂ: {bin} = ദശാംശത്തിൽ {d}.',
    four_desc: 'നാല് ഫുൾ ആഡറുകളുടെ ഒരു ചങ്ങല രണ്ട് 4-ബിറ്റ് സംഖ്യകൾ (0 മുതൽ 15 വരെ) കൂട്ടുന്നു. ഓരോ ക്യാരിയും ഇടതുവശത്തെ അടുത്ത സ്ഥാനത്തേക്ക് ഒരു തിര പോലെ പോകുന്നു.',
    place_val: 'സ്ഥാന വില', carry_row: 'ക്യാരി',
    bit_aria: '{v}-ൽ {p}-ന്റെ ബിറ്റ് {x}. മാറ്റാൻ അമർത്തൂ.',
    final_carry: 'അവസാനത്തെ ക്യാരി ഉത്തരത്തിന്റെ അഞ്ചാമത്തെ ബിറ്റ് ആകുന്നു.',
    tap_bits: 'സംഖ്യകൾ മാറ്റാൻ A, B ബിറ്റുകളിൽ തൊടൂ.',
    mode_fill: 'ടേബിൾ പൂരിപ്പിക്കൂ', mode_name: 'ഗേറ്റ് തിരിച്ചറിയൂ',
    level: 'നില', easy: 'എളുപ്പം', medium: 'ഇടത്തരം', hard: 'കഠിനം', streak: 'തുടർച്ചയായി ശരി', best: 'മികച്ചത്',
    fill_q: 'ഇതിനുള്ള ഔട്ട്പുട്ട് കോളം Y പൂരിപ്പിക്കൂ:',
    tap_cells: 'ഓരോ ?-യിലും തൊട്ട് 0 അല്ലെങ്കിൽ 1 തിരഞ്ഞെടുക്കൂ, തുടർന്ന് “പരിശോധിക്കൂ” അമർത്തൂ.',
    cell_aria: 'വരി {n}: ഔട്ട്പുട്ട് Y ഇപ്പോൾ {x}. മാറ്റാൻ അമർത്തൂ.',
    show_answer: 'ഉത്തരം കാണിക്കൂ', new_question: 'പുതിയ ചോദ്യം',
    fill_all: 'ആദ്യം എല്ലാ വരികളും പൂരിപ്പിക്കൂ.',
    all_right: 'എല്ലാ {n} വരികളും ശരിയാണ്. മിടുക്ക്!',
    some_wrong: '{n} വരികളിൽ {k} എണ്ണം ശരി. ചുവന്നവ തിരുത്തി വീണ്ടും പരിശോധിക്കൂ.',
    answer_shown: 'ഇതാ ഉത്തരം. ശ്രദ്ധിച്ച് നോക്കൂ, എന്നിട്ട് പുതിയ ചോദ്യം ശ്രമിക്കൂ.',
    name_q: 'ഏത് ഗേറ്റാണ് ഈ ട്രൂത്ത് ടേബിൾ നൽകുന്നത്?',
    name_right: 'അതെ! ഇത് {g} ഗേറ്റ് ആണ്.',
    name_wrong: 'ശരിയല്ല. ഇത് {g} ഗേറ്റ് ആണ്.',
    ws_hint: 'ഈ നിലയിലെ 8 ട്രൂത്ത് ടേബിൾ ചോദ്യങ്ങൾ ഉത്തരസൂചികയോടെ പ്രിന്റ് ചെയ്യൂ.',
    print_ws: 'വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യൂ', ws_title: 'ലോജിക് ഗേറ്റ് വർക്ക്ഷീറ്റ്',
    ws_intro: 'ഓരോ ട്രൂത്ത് ടേബിളിന്റെയും ഔട്ട്പുട്ട് കോളം Y പൂരിപ്പിക്കൂ.',
    ws_name: 'പേര്', ws_class: 'ക്ലാസ്', ws_date: 'തീയതി', answer_key: 'ഉത്തരസൂചിക',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ക്ലാസ്മുറിക്കുള്ള ആശയങ്ങൾ',
    help_1: 'ഗേറ്റുകൾ: ഒരു ഗേറ്റ് തിരഞ്ഞെടുത്ത് സ്വിച്ചുകളിൽ തൊടൂ. ബൾബ് ഔട്ട്പുട്ട് Y കാണിക്കും, ട്രൂത്ത് ടേബിളിലെ യോജിക്കുന്ന വരി തെളിയും.',
    help_2: 'എക്സ്പ്രഷൻ ലാബ്: (A + B)·C\' അല്ലെങ്കിൽ NOT (A AND B) പോലെ എന്തെങ്കിലും ടൈപ്പ് ചെയ്യൂ. ഘട്ടങ്ങളുടെ കോളങ്ങളുള്ള ട്രൂത്ത് ടേബിളും ഉടനെ പരീക്ഷിക്കാവുന്ന സർക്യൂട്ടും കിട്ടും.',
    help_3: '“രണ്ട് എക്സ്പ്രഷനുകൾ തുല്യമാണോ?” ഉപയോഗിച്ച് ഡി മോർഗൻ നിയമങ്ങൾ തെളിയിക്കൂ. തുല്യമല്ലെങ്കിൽ, അവ വ്യത്യാസപ്പെടുന്ന വരി ആപ്പ് കാണിക്കും.',
    help_4: 'ആഡറുകൾ: കമ്പ്യൂട്ടർ ഹാഫ് ആഡറും ഫുൾ ആഡറും ഉപയോഗിച്ച് ബൈനറി സംഖ്യകൾ എങ്ങനെ കൂട്ടുന്നു എന്ന് കാണൂ, പിന്നെ രണ്ട് 4-ബിറ്റ് സംഖ്യകൾ കൂട്ടൂ.',
    help_5: 'ക്ലാസ് പ്രവർത്തനം “മനുഷ്യ ലോജിക് ഗേറ്റ്”: രണ്ട് വിദ്യാർഥികൾ ഇൻപുട്ടുകൾ A, B (കൈ ഉയർത്തിയാൽ = 1). മൂന്നാമത്തെയാൾ ഗേറ്റ് ആയി, നിയമം 1 എന്ന് പറയുമ്പോൾ മാത്രം കൈ ഉയർത്തും. ക്ലാസ് മുഴുവൻ സ്മാർട്ട്ബോർഡിൽ പരിശോധിക്കും.',
    help_6: 'അധ്യാപകർക്ക്: പരിശീലനത്തിൽ ഒരു നില തിരഞ്ഞെടുത്ത് “വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യൂ” അമർത്തിയാൽ, ഉത്തരസൂചികയോടെ 8 ചോദ്യങ്ങൾ കിട്ടും.'
  },

  ur: {
    app_title: 'لاجک گیٹ لیب',
    intro: 'سوئچ دبا کر دیکھیں کہ لاجک گیٹ کیسے کام کرتے ہیں، بولین ایکسپریشن سے ٹروتھ ٹیبل اور سرکٹ بنائیں، ڈی مورگن جیسے قوانین جانچیں اور مشق کریں۔',
    tab_gates: 'گیٹ', tab_expr: 'ایکسپریشن لیب', tab_adders: 'ایڈر', tab_practice: 'مشق',
    choose_gate: 'گیٹ', inputs: 'اِن پٹ', n_inputs: '{n} اِن پٹ', one_input: '1 اِن پٹ', gate_name: '{g} گیٹ',
    tap_switch: 'سوئچ کو چھو کر 0 اور 1 کے درمیان بدلیں۔ ٹیبل کی کسی قطار کو چھو کر سیدھے وہاں جائیں۔',
    kbd_hint: 'کی بورڈ پر A، B یا C دبا کر بھی اِن پٹ بدل سکتے ہیں۔',
    expression: 'بولین ایکسپریشن', rule: 'قاعدہ', real_life: 'روزمرہ زندگی کی مثال', truth_table: 'ٹروتھ ٹیبل (صداقتی جدول)',
    rule_and: 'Y تبھی 1 ہوتا ہے جب سارے اِن پٹ 1 ہوں۔',
    rule_or: 'کم از کم ایک اِن پٹ 1 ہو تو Y = 1 ہوتا ہے۔',
    rule_not: 'Y اِن پٹ کا اُلٹ ہوتا ہے: 0 بنتا ہے 1، اور 1 بنتا ہے 0۔',
    rule_nand: 'NOT + AND: صرف تب Y = 0 ہوتا ہے جب سارے اِن پٹ 1 ہوں۔',
    rule_nor: 'NOT + OR: صرف تب Y = 1 ہوتا ہے جب سارے اِن پٹ 0 ہوں۔',
    rule_xor: 'طاق تعداد میں اِن پٹ 1 ہوں تو Y = 1۔ دو اِن پٹ میں: جب دونوں الگ ہوں۔',
    rule_xnor: 'NOT + XOR: جفت تعداد میں اِن پٹ 1 ہوں تو Y = 1۔ دو اِن پٹ میں: جب دونوں ایک جیسے ہوں۔',
    life_and: 'چھت کا پنکھا تبھی چلتا ہے جب مین سوئچ اور پنکھے کا سوئچ دونوں آن ہوں۔',
    life_or: 'دفتر یا اسٹاف روم، کوئی بھی بٹن دبائے تو اسکول کی گھنٹی بجتی ہے۔',
    life_not: 'گھر کا انورٹر تب چالو ہوتا ہے جب بجلی نہیں ہوتی (بجلی جانے پر)۔',
    life_nand: 'کار کا سیٹ بیلٹ الارم تب تک بجتا رہتا ہے جب تک آگے کی دونوں سیٹ بیلٹ نہ لگ جائیں۔',
    life_nor: 'پانی کی موٹر چھت کی ٹنکی تبھی بھرتی ہے جب ٹنکی بھری نہ ہو اور وولٹیج کم نہ ہو۔',
    life_xor: 'سیڑھی کی بتی کے دو سوئچ: اوپر یا نیچے، کوئی بھی ایک سوئچ بدلیں تو بتی بدل جاتی ہے۔',
    life_xnor: 'جواب جانچنے والی مشین: جب آپ کا جواب اور صحیح جواب ایک جیسے ہوں تو ہری بتی جلتی ہے۔',
    universal: 'NAND اور NOR کو یونیورسل گیٹ کہتے ہیں: صرف NAND گیٹ (یا صرف NOR گیٹ) سے کوئی بھی سرکٹ بنایا جا سکتا ہے۔',
    all_gates: 'سبھی گیٹ ایک نظر میں',
    all_gates_hint: 'نمایاں قطار سوئچ A اور B سے ملتی ہے۔ بدلنے کے لیے کسی قطار کو چھوئیں۔',
    sw_aria: 'اِن پٹ {v} ابھی {x} ہے۔ بدلنے کے لیے دبائیں۔',
    out_aria: 'آؤٹ پٹ {v} ابھی {x} ہے',
    expr_label: 'بولین ایکسپریشن لکھیں',
    expr_help: 'A سے E تک کے متغیر لیں، ساتھ میں AND، OR، NOT، XOR، NAND، NOR، XNOR یا علامتیں · + \' ⊕ اور قوسین۔ AB کا مطلب ہے A·B۔',
    examples: 'مثالیں', backspace: 'ایک حرف مٹائیں', copy_link: 'لنک کاپی کریں',
    circuit: 'سرکٹ ڈایاگرام',
    circuit_hint: 'ڈایاگرام میں کسی اِن پٹ (A، B…) یا اوپر والے بٹن کو چھو کر بدلیں۔ ہرے تار میں 1، سلیٹی تار میں 0 ہے۔',
    too_big: 'یہ ایکسپریشن صاف بنانے کے لیے بہت بڑا ہے۔ ٹروتھ ٹیبل پھر بھی کام کرتا ہے۔',
    no_inputs: 'کوئی متغیر نہیں: آؤٹ پٹ کبھی نہیں بدلے گا۔',
    show_steps: 'درمیانی مراحل کے کالم دکھائیں',
    row_hint: 'کسی قطار کو چھو کر سارے اِن پٹ ایک ساتھ سیٹ کریں۔',
    always_1: 'Y ہمیشہ 1 ہے (ٹاٹولوجی)۔',
    always_0: 'Y ہمیشہ 0 ہے (تضاد)۔',
    ones_in: '{n} میں سے {k} قطاروں میں Y = 1:',
    err_empty: 'شروع کرنے کے لیے ایکسپریشن لکھیں، جیسے A·B + C۔',
    err_unknown: 'انجان حرف “{ch}”۔ صرف A، B، C، D اور E متغیر استعمال کریں۔',
    err_symbol: 'جگہ {n} پر علامت “{ch}” سمجھ نہیں آئی۔',
    err_close: 'جگہ {n} پر کھلی قوس بند نہیں ہوئی۔ ایک “)” لگائیں۔',
    err_extra_close: 'جگہ {n} پر ایک “)” زیادہ ہے۔',
    err_operand: 'جگہ {n} پر کچھ چھوٹ گیا ہے۔ وہاں متغیر، 0، 1 یا “(” لکھیں۔',
    err_end: 'ایکسپریشن ادھورا ہے۔ آخری علامت کے بعد ایک متغیر لگائیں۔',
    err_too_long: 'ایکسپریشن بہت لمبا ہے۔ اسے {n} حروف سے کم رکھیں۔',
    equiv_title: 'کیا دو ایکسپریشن برابر ہیں؟',
    equiv_intro: 'دو ایکسپریشن لکھیں یا کوئی قانون چنیں۔ ایپ ٹروتھ ٹیبل کی ہر قطار جانچتی ہے۔',
    try_law: 'کوئی قانون آزمائیں:',
    law_dm1: 'ڈی مورگن کا قانون 1', law_dm2: 'ڈی مورگن کا قانون 2',
    law_abs1: 'جذب کا قانون', law_abs2: 'جذب کا قانون (دوہرا)',
    law_dist1: 'تقسیمی قانون', law_dist2: 'تقسیمی قانون (دوہرا)',
    law_xor: 'AND، OR، NOT سے XOR', law_dneg: 'دوہرا NOT', law_nand: 'NAND گیٹ سے NOT', law_mistake: 'ایک عام غلطی',
    expr1: 'پہلا ایکسپریشن', expr2: 'دوسرا ایکسپریشن', check: 'جانچیں',
    equiv_yes: 'برابر ہیں ✓ تمام {n} قطاروں میں دونوں کا آؤٹ پٹ ایک جیسا ہے۔',
    equiv_no: 'برابر نہیں ✗',
    equiv_detail: 'اُلٹی مثال: جب {vals}، تو پہلا {a} دیتا ہے لیکن دوسرا {b} دیتا ہے۔',
    col_first: 'پہلا', col_second: 'دوسرا', same: 'ایک جیسے؟',
    half_adder: 'ہاف ایڈر', full_adder: 'فُل ایڈر', four_bit: '4-بِٹ ایڈر',
    ha_desc: 'ہاف ایڈر دو بِٹ، A اور B، جوڑتا ہے۔ یہ ایک جمع بِٹ (S) اور ایک حاصل بِٹ (C) دیتا ہے۔',
    legend_ha: 'S = جمع (Sum)، C = حاصل (Carry)',
    why_carry: 'حاصل کیوں؟ بائنری میں 1 + 1 = 10۔ ہم 0 لکھتے ہیں اور 1 اگلی جگہ لے جاتے ہیں، بالکل ویسے جیسے اعشاری میں 5 + 5 = 10۔',
    fa_desc: 'فُل ایڈر تین بِٹ جوڑتا ہے: A، B اور پچھلی جگہ سے آیا حاصل (Cin)۔ یہ دو ہاف ایڈر اور ایک OR گیٹ سے بنتا ہے۔',
    legend_fa: 'Cin = آنے والا حاصل، S = جمع، Cout = جانے والا حاصل',
    fa_how: 'تین میں سے کم از کم دو اِن پٹ 1 ہوں تو Cout = 1 ہوتا ہے۔',
    read_bin: 'حاصل اور جمع کو ساتھ ملا کر ایک بائنری عدد کی طرح پڑھیں: {bin} = اعشاری میں {d}۔',
    four_desc: 'چار فُل ایڈر کی ایک زنجیر دو 4-بِٹ اعداد (0 سے 15) جوڑتی ہے۔ ہر حاصل بائیں طرف کی اگلی جگہ پر لہر کی طرح جاتا ہے۔',
    place_val: 'مقامی قیمت', carry_row: 'حاصل',
    bit_aria: '{v} میں {p} والا بِٹ {x} ہے۔ بدلنے کے لیے دبائیں۔',
    final_carry: 'آخری حاصل جواب کا پانچواں بِٹ بن جاتا ہے۔',
    tap_bits: 'اعداد بدلنے کے لیے A اور B کے بِٹ چھوئیں۔',
    mode_fill: 'ٹیبل مکمل کریں', mode_name: 'گیٹ پہچانیں',
    level: 'سطح', easy: 'آسان', medium: 'درمیانہ', hard: 'مشکل', streak: 'لگاتار صحیح', best: 'بہترین',
    fill_q: 'اس کے لیے آؤٹ پٹ کالم Y بھریں:',
    tap_cells: 'ہر ? کو چھو کر 0 یا 1 چنیں، پھر “جانچیں” دبائیں۔',
    cell_aria: 'قطار {n}: آؤٹ پٹ Y ابھی {x} ہے۔ بدلنے کے لیے دبائیں۔',
    show_answer: 'جواب دکھائیں', new_question: 'نیا سوال',
    fill_all: 'پہلے ہر قطار بھریں۔',
    all_right: 'تمام {n} قطاریں صحیح ہیں۔ شاباش!',
    some_wrong: '{n} میں سے {k} قطاریں صحیح ہیں۔ لال والی ٹھیک کر کے پھر جانچیں۔',
    answer_shown: 'یہ رہا جواب۔ اسے غور سے دیکھیں، پھر نیا سوال کریں۔',
    name_q: 'کون سا گیٹ یہ ٹروتھ ٹیبل دیتا ہے؟',
    name_right: 'ہاں! یہ {g} گیٹ ہے۔',
    name_wrong: 'ٹھیک نہیں۔ یہ {g} گیٹ ہے۔',
    ws_hint: 'اس سطح کے 8 ٹروتھ ٹیبل سوال جوابی کلید کے ساتھ پرنٹ کریں۔',
    print_ws: 'ورک شیٹ پرنٹ کریں', ws_title: 'لاجک گیٹ ورک شیٹ',
    ws_intro: 'ہر ٹروتھ ٹیبل کا آؤٹ پٹ کالم Y مکمل کریں۔',
    ws_name: 'نام', ws_class: 'جماعت', ws_date: 'تاریخ', answer_key: 'جوابی کلید',
    help_title: 'استعمال کا طریقہ / کلاس کے لیے خیالات',
    help_1: 'گیٹ: کوئی گیٹ چنیں اور سوئچ چھوئیں۔ بلب آؤٹ پٹ Y دکھاتا ہے اور ٹروتھ ٹیبل کی ملتی جلتی قطار چمکتی ہے۔',
    help_2: 'ایکسپریشن لیب: (A + B)·C\' یا NOT (A AND B) جیسا کچھ لکھیں۔ آپ کو مراحل کے کالم والا ٹروتھ ٹیبل اور ایک سرکٹ ملے گا جسے آپ فوراً جانچ سکتے ہیں۔',
    help_3: '“کیا دو ایکسپریشن برابر ہیں؟” سے ڈی مورگن کے قوانین ثابت کریں۔ اگر برابر نہیں تو ایپ وہ قطار دکھاتی ہے جہاں وہ الگ ہیں۔',
    help_4: 'ایڈر: دیکھیں کہ کمپیوٹر ہاف ایڈر اور فُل ایڈر سے بائنری اعداد کیسے جوڑتا ہے، پھر دو 4-بِٹ اعداد جوڑیں۔',
    help_5: 'کلاس سرگرمی “انسانی لاجک گیٹ”: دو طالب علم اِن پٹ A اور B بنیں (ہاتھ اوپر = 1)۔ تیسرا طالب علم گیٹ بنے اور تبھی ہاتھ اٹھائے جب قاعدہ 1 کہے۔ پوری کلاس اسمارٹ بورڈ پر جانچے۔',
    help_6: 'اساتذہ کے لیے: مشق میں سطح چنیں اور “ورک شیٹ پرنٹ کریں” دبائیں، جوابی کلید کے ساتھ 8 سوال ملیں گے۔'
  }
};
