/* AI Basics Quiz: UI strings. Keys are identical in all 12 languages.
   Shared words (next, previous, pause, resume, correct, wrong, fullscreen, ...) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'AI Basics Quiz',
    intro: 'Practise the basics of Artificial Intelligence: AI, ML and DL, AI domains, the AI project cycle, types of learning, evaluation, AI ethics and generative AI. Based on the CBSE AI (417) syllabus.',
    choose_mode: 'Choose a mode',
    mode_practice: 'Practice',
    mode_practice_d: 'See the right answer and explanation after every question.',
    mode_test: 'Test',
    mode_test_d: 'Timed test. Score, review and certificate at the end.',
    mode_class: 'Projector quiz',
    mode_class_d: 'Big-screen quiz for the whole class with team scores.',
    topics: 'Topics',
    all_topics: 'All topics',
    topic_basics: 'What is AI?',
    topic_domains: 'AI domains',
    topic_cycle: 'AI project cycle',
    topic_learning: 'How machines learn',
    topic_eval: 'Evaluation',
    topic_ethics: 'AI ethics',
    topic_genai: 'Generative AI',
    n_available: '{n} questions',
    pick_topic: 'Pick at least one topic to start.',
    num_questions: 'Number of questions',
    all_n: 'All ({n})',
    time_limit: 'Time limit',
    time_per_q: '{s} seconds per question',
    no_limit: 'No time limit',
    total_time: 'Total time: {t}',
    q_timer: 'Timer for each question',
    sec_n: '{s} seconds',
    timer_off: 'No timer',
    num_teams: 'Number of teams',
    team_n: 'Team {n}',
    team_name_label: 'Name of team {n}',
    shuffle_q: 'Shuffle questions',
    shuffle_o: 'Shuffle options',
    start_quiz: 'Start quiz',
    print_paper: 'Print question paper',
    resume_title: 'Unfinished quiz ({mode}): question {n} of {total}.',
    discard: 'Discard',
    help_title: 'How to use / Ideas for the classroom',
    help_1: 'Practice shows the right answer and a short explanation after every question. Test hides the answers until the end and has a timer. Projector quiz is for the whole class on a smartboard or TV.',
    help_2: 'Tap the topic buttons to revise one chapter at a time, for example only "Evaluation" before a unit test.',
    help_3: 'Classroom activity: divide the class into 2 to 4 teams (your school houses work well). Show a question on the projector, give teams 30 seconds to discuss, then press Reveal and give +1 to every team that got it right.',
    help_4: 'Keyboard: press 1–4 or A–D to choose an option and Enter for the next question. In the projector quiz press R to reveal, T to pause the timer and F for full screen.',
    help_5: 'Print a question paper with an answer key for a quick class test, or print a certificate for each student after the test.',
    help_6: 'Results are saved only on this device. No sign-up, no ads, and it works offline after the first visit.',
    formula_title: 'Quick formula card (Evaluation)',
    f_accuracy: 'Accuracy',
    f_precision: 'Precision',
    f_recall: 'Recall',
    f_f1: 'F1 score',
    f_note: 'TP = true positive, TN = true negative, FP = false positive, FN = false negative, P = precision, R = recall.',
    history_title: 'Your recent results',
    history_empty: 'No results yet. Finish a practice or a test to see your scores here.',
    best_score: 'Best: {pct}%',
    see_last: 'Show last result',
    reset_all: 'Reset everything',
    reset_done: 'Everything has been reset.',
    q_of: 'Question {n} of {total}',
    score_n: 'Score: {n}/{total}',
    question_list: 'Questions',
    jump_to: 'Go to question {n}',
    read_aloud: 'Read aloud',
    explanation: 'Explanation',
    correct_was: 'The right answer is {a}',
    next_q: 'Next question',
    see_result: 'See my result',
    submit_test: 'Submit test',
    quit: 'Quit',
    confirm_quit: 'Stop this quiz? Your progress in this quiz will be lost.',
    confirm_submit: 'Questions not answered yet: {n}. Submit the test anyway?',
    time_left: 'Time left',
    times_up: 'Time’s up!',
    kbd_hint: 'Tip: press 1–4 to answer and Enter for the next question.',
    result_title: 'Your result',
    msg_90: 'Outstanding! You really know your AI basics.',
    msg_75: 'Great work! Revise the few you missed.',
    msg_50: 'Good start. Read the explanations and try again.',
    msg_0: 'Keep practising. Every expert was once a beginner!',
    n_correct: 'Correct: {n}',
    n_wrong: 'Wrong: {n}',
    n_skipped: 'Not answered: {n}',
    time_taken: 'Time: {t}',
    by_topic: 'Score by topic',
    revise_tip: 'Revise these topics again: {list}',
    practice_mistakes: 'Practise my mistakes',
    new_quiz: 'New quiz',
    back_setup: 'Back to start',
    cert_section: 'Your certificate',
    your_name: 'Your name',
    name_ph: 'e.g. Ananya Sharma',
    school_label: 'School and class (optional)',
    school_ph: 'e.g. Class 9 B, Government High School, Pune',
    cert_hint: 'Tip: choose "Save as PDF" in the print window to keep it on your phone.',
    cert_title: 'Certificate of Achievement',
    cert_certify: 'This is to certify that',
    cert_body: 'scored {score} out of {total} ({pct}%) in the AI Basics Quiz.',
    cert_topics: 'Topics: {list}',
    cert_date: 'Date: {d}',
    cert_sign: 'Teacher’s signature',
    badge_star: 'AI Star',
    badge_explorer: 'AI Explorer',
    badge_learner: 'AI Learner',
    badge_starter: 'AI Beginner',
    print_cert: 'Print certificate',
    review: 'Review your answers',
    only_wrong: 'Show only mistakes',
    your_answer: 'Your answer',
    not_answered: 'Not answered',
    no_mistakes: 'No mistakes. Full marks!',
    reveal: 'Reveal answer',
    answer_is: 'Answer: {a}',
    class_finish: 'Finish quiz',
    restart_timer: 'Restart timer',
    plus_point: '+1 point for {team}',
    minus_point: '−1 point for {team}',
    class_tip: 'Let the teams discuss, then press Reveal. Tap +1 for every team that got it right.',
    winner: '{team} wins!',
    tie: 'It’s a tie! Well played, everyone.',
    final_scores: 'Final scores',
    play_again: 'Play again',
    paper_title: 'AI Basics: Question Paper',
    n_questions: '{n} questions',
    paper_name: 'Name: ____________________',
    paper_class: 'Class: ________',
    paper_date: 'Date: ____________',
    paper_marks: 'Marks: ______ / {total}',
    paper_instr: 'Choose the correct option for each question. Each question carries 1 mark.',
    answer_key: 'Answer key (for the teacher)',
    made_with: 'Made with AI Pathshala Apps: free for every school.'
  },

  hi: {
    app_title: 'AI बेसिक्स क्विज़',
    intro: 'आर्टिफ़िशियल इंटेलिजेंस (AI) की बुनियादी बातों का अभ्यास करें: AI, ML और DL, AI के क्षेत्र, AI प्रोजेक्ट साइकिल, मशीनें कैसे सीखती हैं, मूल्यांकन, AI नैतिकता और जनरेटिव AI। CBSE AI (417) सिलेबस पर आधारित।',
    choose_mode: 'मोड चुनें',
    mode_practice: 'अभ्यास',
    mode_practice_d: 'हर सवाल के बाद सही जवाब और उसकी व्याख्या देखें।',
    mode_test: 'टेस्ट',
    mode_test_d: 'समय वाला टेस्ट। अंत में अंक, जवाबों की जाँच और सर्टिफ़िकेट।',
    mode_class: 'प्रोजेक्टर क्विज़',
    mode_class_d: 'पूरी कक्षा के लिए बड़ी स्क्रीन पर क्विज़, टीम स्कोर के साथ।',
    topics: 'विषय',
    all_topics: 'सभी विषय',
    topic_basics: 'AI क्या है?',
    topic_domains: 'AI के क्षेत्र',
    topic_cycle: 'AI प्रोजेक्ट साइकिल',
    topic_learning: 'मशीनें कैसे सीखती हैं',
    topic_eval: 'मूल्यांकन',
    topic_ethics: 'AI नैतिकता',
    topic_genai: 'जनरेटिव AI',
    n_available: '{n} सवाल',
    pick_topic: 'शुरू करने के लिए कम से कम एक विषय चुनें।',
    num_questions: 'सवालों की संख्या',
    all_n: 'सभी ({n})',
    time_limit: 'समय सीमा',
    time_per_q: 'हर सवाल के लिए {s} सेकंड',
    no_limit: 'कोई समय सीमा नहीं',
    total_time: 'कुल समय: {t}',
    q_timer: 'हर सवाल का टाइमर',
    sec_n: '{s} सेकंड',
    timer_off: 'टाइमर नहीं',
    num_teams: 'टीमों की संख्या',
    team_n: 'टीम {n}',
    team_name_label: 'टीम {n} का नाम',
    shuffle_q: 'सवाल मिलाएँ',
    shuffle_o: 'विकल्प मिलाएँ',
    start_quiz: 'क्विज़ शुरू करें',
    print_paper: 'प्रश्न-पत्र प्रिंट करें',
    resume_title: 'अधूरा क्विज़ ({mode}): सवाल {n} / {total}।',
    discard: 'हटाएँ',
    help_title: 'कैसे इस्तेमाल करें / कक्षा के लिए सुझाव',
    help_1: 'अभ्यास में हर सवाल के बाद सही जवाब और छोटी व्याख्या दिखती है। टेस्ट में जवाब अंत तक छिपे रहते हैं और टाइमर चलता है। प्रोजेक्टर क्विज़ स्मार्टबोर्ड या TV पर पूरी कक्षा के लिए है।',
    help_2: 'एक बार में एक अध्याय दोहराने के लिए विषय के बटन दबाएँ, जैसे यूनिट टेस्ट से पहले सिर्फ़ "मूल्यांकन"।',
    help_3: 'कक्षा गतिविधि: कक्षा को 2 से 4 टीमों में बाँटें (स्कूल के हाउस भी चलेंगे)। प्रोजेक्टर पर सवाल दिखाएँ, टीमों को 30 सेकंड चर्चा करने दें, फिर "जवाब दिखाएँ" दबाएँ और सही जवाब वाली हर टीम को +1 दें।',
    help_4: 'कीबोर्ड: विकल्प चुनने के लिए 1–4 या A–D दबाएँ और अगले सवाल के लिए Enter। प्रोजेक्टर क्विज़ में जवाब दिखाने के लिए R, टाइमर रोकने के लिए T और पूरी स्क्रीन के लिए F दबाएँ।',
    help_5: 'झटपट क्लास टेस्ट के लिए उत्तर-कुंजी के साथ प्रश्न-पत्र प्रिंट करें, या टेस्ट के बाद हर विद्यार्थी का सर्टिफ़िकेट प्रिंट करें।',
    help_6: 'नतीजे सिर्फ़ इसी डिवाइस पर सेव होते हैं। कोई साइन-अप नहीं, कोई विज्ञापन नहीं, और पहली बार खोलने के बाद यह बिना इंटरनेट भी चलता है।',
    formula_title: 'झटपट फ़ॉर्मूला कार्ड (मूल्यांकन)',
    f_accuracy: 'सटीकता (Accuracy)',
    f_precision: 'प्रिसिज़न (Precision)',
    f_recall: 'रिकॉल (Recall)',
    f_f1: 'F1 स्कोर',
    f_note: 'TP = ट्रू पॉज़िटिव, TN = ट्रू नेगेटिव, FP = फ़ॉल्स पॉज़िटिव, FN = फ़ॉल्स नेगेटिव, P = प्रिसिज़न, R = रिकॉल।',
    history_title: 'आपके हाल के नतीजे',
    history_empty: 'अभी कोई नतीजा नहीं। अभ्यास या टेस्ट पूरा करें, आपके अंक यहाँ दिखेंगे।',
    best_score: 'सबसे अच्छा: {pct}%',
    see_last: 'पिछला नतीजा देखें',
    reset_all: 'सब कुछ रीसेट करें',
    reset_done: 'सब कुछ रीसेट हो गया।',
    q_of: 'सवाल {n} / {total}',
    score_n: 'अंक: {n}/{total}',
    question_list: 'सवाल',
    jump_to: 'सवाल {n} पर जाएँ',
    read_aloud: 'पढ़कर सुनाएँ',
    explanation: 'व्याख्या',
    correct_was: 'सही जवाब है {a}',
    next_q: 'अगला सवाल',
    see_result: 'मेरा नतीजा देखें',
    submit_test: 'टेस्ट जमा करें',
    quit: 'छोड़ें',
    confirm_quit: 'यह क्विज़ बंद करें? इस क्विज़ की प्रगति मिट जाएगी।',
    confirm_submit: 'बिना जवाब वाले सवाल: {n}। फिर भी टेस्ट जमा करें?',
    time_left: 'बचा हुआ समय',
    times_up: 'समय खत्म!',
    kbd_hint: 'सुझाव: जवाब के लिए 1–4 दबाएँ और अगले सवाल के लिए Enter।',
    result_title: 'आपका नतीजा',
    msg_90: 'शानदार! आपको AI की बुनियादी बातें सच में अच्छी तरह आती हैं।',
    msg_75: 'बहुत बढ़िया! जो थोड़े छूट गए, उन्हें दोहरा लें।',
    msg_50: 'अच्छी शुरुआत। व्याख्याएँ पढ़ें और फिर कोशिश करें।',
    msg_0: 'अभ्यास करते रहें। हर एक्सपर्ट कभी नौसिखिया था!',
    n_correct: 'सही: {n}',
    n_wrong: 'गलत: {n}',
    n_skipped: 'बिना जवाब: {n}',
    time_taken: 'समय: {t}',
    by_topic: 'विषय के अनुसार अंक',
    revise_tip: 'इन विषयों को फिर से पढ़ें: {list}',
    practice_mistakes: 'मेरी गलतियों का अभ्यास',
    new_quiz: 'नया क्विज़',
    back_setup: 'शुरुआत पर वापस',
    cert_section: 'आपका सर्टिफ़िकेट',
    your_name: 'आपका नाम',
    name_ph: 'जैसे: अनन्या शर्मा',
    school_label: 'स्कूल और कक्षा (ज़रूरी नहीं)',
    school_ph: 'जैसे: कक्षा 9 B, राजकीय उच्च विद्यालय, पुणे',
    cert_hint: 'सुझाव: फ़ोन में रखने के लिए प्रिंट विंडो में PDF के रूप में सेव करें।',
    cert_title: 'उपलब्धि प्रमाण-पत्र',
    cert_certify: 'प्रमाणित किया जाता है कि',
    cert_body: 'ने AI बेसिक्स क्विज़ में {total} में से {score} अंक ({pct}%) प्राप्त किए।',
    cert_topics: 'विषय: {list}',
    cert_date: 'तारीख: {d}',
    cert_sign: 'शिक्षक के हस्ताक्षर',
    badge_star: 'AI स्टार',
    badge_explorer: 'AI एक्सप्लोरर',
    badge_learner: 'AI लर्नर',
    badge_starter: 'AI शुरुआती',
    print_cert: 'सर्टिफ़िकेट प्रिंट करें',
    review: 'अपने जवाब जाँचें',
    only_wrong: 'सिर्फ़ गलतियाँ दिखाएँ',
    your_answer: 'आपका जवाब',
    not_answered: 'जवाब नहीं दिया',
    no_mistakes: 'कोई गलती नहीं। पूरे अंक!',
    reveal: 'जवाब दिखाएँ',
    answer_is: 'जवाब: {a}',
    class_finish: 'क्विज़ खत्म करें',
    restart_timer: 'टाइमर फिर से शुरू करें',
    plus_point: '{team} को +1 अंक',
    minus_point: '{team} का −1 अंक',
    class_tip: 'टीमों को चर्चा करने दें, फिर "जवाब दिखाएँ" दबाएँ। सही जवाब वाली हर टीम को +1 दें।',
    winner: '{team} जीती!',
    tie: 'मुकाबला बराबर! सबने अच्छा खेला।',
    final_scores: 'अंतिम अंक',
    play_again: 'फिर से खेलें',
    paper_title: 'AI बेसिक्स: प्रश्न-पत्र',
    n_questions: '{n} सवाल',
    paper_name: 'नाम: ____________________',
    paper_class: 'कक्षा: ________',
    paper_date: 'तारीख: ____________',
    paper_marks: 'अंक: ______ / {total}',
    paper_instr: 'हर सवाल का सही विकल्प चुनें। हर सवाल 1 अंक का है।',
    answer_key: 'उत्तर-कुंजी (शिक्षक के लिए)',
    made_with: 'AI की पाठशाला ऐप्स से बना: हर स्कूल के लिए मुफ़्त।'
  },

  bn: {
    app_title: 'AI বেসিক্স কুইজ',
    intro: 'আর্টিফিশিয়াল ইন্টেলিজেন্স (AI)-এর মূল বিষয়গুলো অনুশীলন করুন: AI, ML ও DL, AI-এর ক্ষেত্র, AI প্রজেক্ট সাইকেল, মেশিন কীভাবে শেখে, মূল্যায়ন, AI নৈতিকতা আর জেনারেটিভ AI। CBSE AI (417) সিলেবাস অনুযায়ী।',
    choose_mode: 'মোড বেছে নিন',
    mode_practice: 'অনুশীলন',
    mode_practice_d: 'প্রতিটি প্রশ্নের পরেই সঠিক উত্তর ও ব্যাখ্যা দেখুন।',
    mode_test: 'টেস্ট',
    mode_test_d: 'সময় ধরে টেস্ট। শেষে নম্বর, উত্তর যাচাই ও সার্টিফিকেট।',
    mode_class: 'প্রজেক্টর কুইজ',
    mode_class_d: 'পুরো ক্লাসের জন্য বড় স্ক্রিনে কুইজ, দলের স্কোর সহ।',
    topics: 'বিষয়',
    all_topics: 'সব বিষয়',
    topic_basics: 'AI কী?',
    topic_domains: 'AI-এর ক্ষেত্র',
    topic_cycle: 'AI প্রজেক্ট সাইকেল',
    topic_learning: 'মেশিন কীভাবে শেখে',
    topic_eval: 'মূল্যায়ন',
    topic_ethics: 'AI নৈতিকতা',
    topic_genai: 'জেনারেটিভ AI',
    n_available: '{n}টি প্রশ্ন',
    pick_topic: 'শুরু করতে অন্তত একটি বিষয় বেছে নিন।',
    num_questions: 'প্রশ্নের সংখ্যা',
    all_n: 'সব ({n})',
    time_limit: 'সময়সীমা',
    time_per_q: 'প্রতি প্রশ্নে {s} সেকেন্ড',
    no_limit: 'কোনো সময়সীমা নেই',
    total_time: 'মোট সময়: {t}',
    q_timer: 'প্রতি প্রশ্নের টাইমার',
    sec_n: '{s} সেকেন্ড',
    timer_off: 'টাইমার নেই',
    num_teams: 'দলের সংখ্যা',
    team_n: 'দল {n}',
    team_name_label: 'দল {n}-এর নাম',
    shuffle_q: 'প্রশ্ন এলোমেলো করুন',
    shuffle_o: 'বিকল্প এলোমেলো করুন',
    start_quiz: 'কুইজ শুরু করুন',
    print_paper: 'প্রশ্নপত্র প্রিন্ট করুন',
    resume_title: 'অসমাপ্ত কুইজ ({mode}): প্রশ্ন {n} / {total}।',
    discard: 'বাদ দিন',
    help_title: 'কীভাবে ব্যবহার করবেন / ক্লাসের জন্য আইডিয়া',
    help_1: 'অনুশীলনে প্রতিটি প্রশ্নের পরে সঠিক উত্তর ও ছোট ব্যাখ্যা দেখা যায়। টেস্টে উত্তর শেষ পর্যন্ত লুকানো থাকে আর টাইমার চলে। প্রজেক্টর কুইজ স্মার্টবোর্ড বা TV-তে পুরো ক্লাসের জন্য।',
    help_2: 'একবারে একটি অধ্যায় ঝালিয়ে নিতে বিষয়ের বোতাম চাপুন, যেমন ইউনিট টেস্টের আগে শুধু "মূল্যায়ন"।',
    help_3: 'ক্লাসের কাজ: ক্লাসকে 2 থেকে 4টি দলে ভাগ করুন (স্কুলের হাউসও চলবে)। প্রজেক্টরে প্রশ্ন দেখান, দলগুলোকে 30 সেকেন্ড আলোচনা করতে দিন, তারপর "উত্তর দেখান" চাপুন আর যারা ঠিক বলেছে সেই প্রতিটি দলকে +1 দিন।',
    help_4: 'কিবোর্ড: বিকল্প বাছতে 1–4 বা A–D চাপুন আর পরের প্রশ্নের জন্য Enter। প্রজেক্টর কুইজে উত্তর দেখাতে R, টাইমার থামাতে T আর পুরো স্ক্রিনের জন্য F চাপুন।',
    help_5: 'চটজলদি ক্লাস টেস্টের জন্য উত্তরমালা সহ প্রশ্নপত্র প্রিন্ট করুন, বা টেস্টের পরে প্রত্যেক ছাত্রছাত্রীর সার্টিফিকেট প্রিন্ট করুন।',
    help_6: 'ফলাফল শুধু এই ডিভাইসেই সেভ থাকে। সাইন-আপ নেই, বিজ্ঞাপন নেই, আর প্রথমবার খোলার পরে ইন্টারনেট ছাড়াও চলে।',
    formula_title: 'চটজলদি সূত্র কার্ড (মূল্যায়ন)',
    f_accuracy: 'নির্ভুলতা (Accuracy)',
    f_precision: 'প্রিসিশন (Precision)',
    f_recall: 'রিকল (Recall)',
    f_f1: 'F1 স্কোর',
    f_note: 'TP = ট্রু পজিটিভ, TN = ট্রু নেগেটিভ, FP = ফলস পজিটিভ, FN = ফলস নেগেটিভ, P = প্রিসিশন, R = রিকল।',
    history_title: 'আপনার সাম্প্রতিক ফলাফল',
    history_empty: 'এখনও কোনো ফলাফল নেই। একটি অনুশীলন বা টেস্ট শেষ করুন, আপনার নম্বর এখানে দেখা যাবে।',
    best_score: 'সেরা: {pct}%',
    see_last: 'শেষ ফলাফল দেখুন',
    reset_all: 'সব রিসেট করুন',
    reset_done: 'সব রিসেট করা হয়েছে।',
    q_of: 'প্রশ্ন {n} / {total}',
    score_n: 'নম্বর: {n}/{total}',
    question_list: 'প্রশ্নগুলো',
    jump_to: 'প্রশ্ন {n}-এ যান',
    read_aloud: 'জোরে পড়ে শোনান',
    explanation: 'ব্যাখ্যা',
    correct_was: 'সঠিক উত্তর {a}',
    next_q: 'পরের প্রশ্ন',
    see_result: 'আমার ফলাফল দেখুন',
    submit_test: 'টেস্ট জমা দিন',
    quit: 'বেরিয়ে যান',
    confirm_quit: 'এই কুইজ বন্ধ করবেন? এই কুইজের অগ্রগতি মুছে যাবে।',
    confirm_submit: 'উত্তর না দেওয়া প্রশ্ন: {n}। তবুও টেস্ট জমা দেবেন?',
    time_left: 'বাকি সময়',
    times_up: 'সময় শেষ!',
    kbd_hint: 'টিপ: উত্তর দিতে 1–4 চাপুন আর পরের প্রশ্নের জন্য Enter।',
    result_title: 'আপনার ফলাফল',
    msg_90: 'অসাধারণ! AI-এর মূল বিষয়গুলো আপনি সত্যিই ভালো জানেন।',
    msg_75: 'খুব ভালো! যে কয়েকটি ভুল হয়েছে সেগুলো আবার দেখে নিন।',
    msg_50: 'ভালো শুরু। ব্যাখ্যাগুলো পড়ুন আর আবার চেষ্টা করুন।',
    msg_0: 'অনুশীলন চালিয়ে যান। প্রত্যেক বিশেষজ্ঞই একসময় নতুন ছিলেন!',
    n_correct: 'সঠিক: {n}',
    n_wrong: 'ভুল: {n}',
    n_skipped: 'উত্তর দেওয়া হয়নি: {n}',
    time_taken: 'সময়: {t}',
    by_topic: 'বিষয় অনুযায়ী নম্বর',
    revise_tip: 'এই বিষয়গুলো আবার পড়ুন: {list}',
    practice_mistakes: 'আমার ভুলগুলো অনুশীলন করি',
    new_quiz: 'নতুন কুইজ',
    back_setup: 'শুরুতে ফিরুন',
    cert_section: 'আপনার সার্টিফিকেট',
    your_name: 'আপনার নাম',
    name_ph: 'যেমন: অনন্যা দত্ত',
    school_label: 'স্কুল ও শ্রেণি (ঐচ্ছিক)',
    school_ph: 'যেমন: নবম শ্রেণি B, সরকারি উচ্চ বিদ্যালয়, কলকাতা',
    cert_hint: 'টিপ: ফোনে রাখতে প্রিন্ট উইন্ডোতে PDF হিসেবে সেভ করুন।',
    cert_title: 'কৃতিত্বের শংসাপত্র',
    cert_certify: 'এই মর্মে প্রত্যয়িত করা হচ্ছে যে',
    cert_body: 'AI বেসিক্স কুইজে {total}-এর মধ্যে {score} নম্বর ({pct}%) পেয়েছে।',
    cert_topics: 'বিষয়: {list}',
    cert_date: 'তারিখ: {d}',
    cert_sign: 'শিক্ষকের স্বাক্ষর',
    badge_star: 'AI স্টার',
    badge_explorer: 'AI এক্সপ্লোরার',
    badge_learner: 'AI লার্নার',
    badge_starter: 'AI নবীন',
    print_cert: 'সার্টিফিকেট প্রিন্ট করুন',
    review: 'আপনার উত্তরগুলো যাচাই করুন',
    only_wrong: 'শুধু ভুলগুলো দেখান',
    your_answer: 'আপনার উত্তর',
    not_answered: 'উত্তর দেওয়া হয়নি',
    no_mistakes: 'কোনো ভুল নেই। পুরো নম্বর!',
    reveal: 'উত্তর দেখান',
    answer_is: 'উত্তর: {a}',
    class_finish: 'কুইজ শেষ করুন',
    restart_timer: 'টাইমার আবার চালু করুন',
    plus_point: '{team}-কে +1 পয়েন্ট',
    minus_point: '{team}-এর −1 পয়েন্ট',
    class_tip: 'দলগুলোকে আলোচনা করতে দিন, তারপর "উত্তর দেখান" চাপুন। যে দলগুলো ঠিক বলেছে, প্রত্যেককে +1 দিন।',
    winner: '{team} জিতেছে!',
    tie: 'সমান সমান! সবাই দারুণ খেলেছে।',
    final_scores: 'চূড়ান্ত স্কোর',
    play_again: 'আবার খেলুন',
    paper_title: 'AI বেসিক্স: প্রশ্নপত্র',
    n_questions: '{n}টি প্রশ্ন',
    paper_name: 'নাম: ____________________',
    paper_class: 'শ্রেণি: ________',
    paper_date: 'তারিখ: ____________',
    paper_marks: 'নম্বর: ______ / {total}',
    paper_instr: 'প্রতিটি প্রশ্নের সঠিক বিকল্পটি বেছে নিন। প্রতিটি প্রশ্নে 1 নম্বর।',
    answer_key: 'উত্তরমালা (শিক্ষকের জন্য)',
    made_with: 'AI পাঠশালা অ্যাপস দিয়ে তৈরি: প্রতিটি স্কুলের জন্য বিনামূল্যে।'
  },

  mr: {
    app_title: 'AI बेसिक्स क्विझ',
    intro: 'आर्टिफिशियल इंटेलिजन्स (AI) च्या मूलभूत गोष्टींचा सराव करा: AI, ML आणि DL, AI ची क्षेत्रे, AI प्रोजेक्ट सायकल, मशीन कसे शिकते, मूल्यमापन, AI नैतिकता आणि जनरेटिव्ह AI. CBSE AI (417) अभ्यासक्रमावर आधारित.',
    choose_mode: 'मोड निवडा',
    mode_practice: 'सराव',
    mode_practice_d: 'प्रत्येक प्रश्नानंतर बरोबर उत्तर आणि स्पष्टीकरण पाहा.',
    mode_test: 'चाचणी',
    mode_test_d: 'वेळेची चाचणी. शेवटी गुण, उत्तरांची तपासणी आणि प्रमाणपत्र.',
    mode_class: 'प्रोजेक्टर क्विझ',
    mode_class_d: 'संपूर्ण वर्गासाठी मोठ्या स्क्रीनवर क्विझ, संघांच्या गुणांसह.',
    topics: 'विषय',
    all_topics: 'सर्व विषय',
    topic_basics: 'AI म्हणजे काय?',
    topic_domains: 'AI ची क्षेत्रे',
    topic_cycle: 'AI प्रोजेक्ट सायकल',
    topic_learning: 'मशीन कसे शिकते',
    topic_eval: 'मूल्यमापन',
    topic_ethics: 'AI नैतिकता',
    topic_genai: 'जनरेटिव्ह AI',
    n_available: '{n} प्रश्न',
    pick_topic: 'सुरू करण्यासाठी किमान एक विषय निवडा.',
    num_questions: 'प्रश्नांची संख्या',
    all_n: 'सर्व ({n})',
    time_limit: 'वेळेची मर्यादा',
    time_per_q: 'प्रत्येक प्रश्नासाठी {s} सेकंद',
    no_limit: 'वेळेची मर्यादा नाही',
    total_time: 'एकूण वेळ: {t}',
    q_timer: 'प्रत्येक प्रश्नाचा टायमर',
    sec_n: '{s} सेकंद',
    timer_off: 'टायमर नाही',
    num_teams: 'संघांची संख्या',
    team_n: 'संघ {n}',
    team_name_label: 'संघ {n} चे नाव',
    shuffle_q: 'प्रश्न मिसळा',
    shuffle_o: 'पर्याय मिसळा',
    start_quiz: 'क्विझ सुरू करा',
    print_paper: 'प्रश्नपत्रिका प्रिंट करा',
    resume_title: 'अपूर्ण क्विझ ({mode}): प्रश्न {n} / {total}.',
    discard: 'काढून टाका',
    help_title: 'कसे वापरावे / वर्गासाठी कल्पना',
    help_1: 'सरावात प्रत्येक प्रश्नानंतर बरोबर उत्तर आणि छोटे स्पष्टीकरण दिसते. चाचणीत उत्तरे शेवटपर्यंत लपलेली राहतात आणि टायमर चालू असतो. प्रोजेक्टर क्विझ स्मार्टबोर्ड किंवा TV वर संपूर्ण वर्गासाठी आहे.',
    help_2: 'एका वेळी एकच धडा उजळणी करण्यासाठी विषयांची बटणे दाबा, उदा. घटक चाचणीपूर्वी फक्त "मूल्यमापन".',
    help_3: 'वर्ग उपक्रम: वर्गाचे 2 ते 4 संघ करा (शाळेची हाउसेसही चालतील). प्रोजेक्टरवर प्रश्न दाखवा, संघांना 30 सेकंद चर्चा करू द्या, मग "उत्तर दाखवा" दाबा आणि बरोबर उत्तर देणाऱ्या प्रत्येक संघाला +1 द्या.',
    help_4: 'कीबोर्ड: पर्याय निवडण्यासाठी 1–4 किंवा A–D दाबा आणि पुढील प्रश्नासाठी Enter. प्रोजेक्टर क्विझमध्ये उत्तर दाखवण्यासाठी R, टायमर थांबवण्यासाठी T आणि पूर्ण स्क्रीनसाठी F दाबा.',
    help_5: 'झटपट वर्ग चाचणीसाठी उत्तरसूचीसह प्रश्नपत्रिका प्रिंट करा, किंवा चाचणीनंतर प्रत्येक विद्यार्थ्याचे प्रमाणपत्र प्रिंट करा.',
    help_6: 'निकाल फक्त याच डिव्हाइसवर सेव्ह होतात. साइन-अप नाही, जाहिराती नाहीत, आणि पहिल्या भेटीनंतर इंटरनेटशिवायही चालते.',
    formula_title: 'झटपट सूत्र कार्ड (मूल्यमापन)',
    f_accuracy: 'अचूकता (Accuracy)',
    f_precision: 'प्रिसिजन (Precision)',
    f_recall: 'रिकॉल (Recall)',
    f_f1: 'F1 स्कोअर',
    f_note: 'TP = ट्रू पॉझिटिव्ह, TN = ट्रू निगेटिव्ह, FP = फॉल्स पॉझिटिव्ह, FN = फॉल्स निगेटिव्ह, P = प्रिसिजन, R = रिकॉल.',
    history_title: 'तुमचे अलीकडील निकाल',
    history_empty: 'अजून निकाल नाहीत. सराव किंवा चाचणी पूर्ण करा, तुमचे गुण इथे दिसतील.',
    best_score: 'सर्वोत्तम: {pct}%',
    see_last: 'मागील निकाल पाहा',
    reset_all: 'सर्व रीसेट करा',
    reset_done: 'सर्व काही रीसेट झाले.',
    q_of: 'प्रश्न {n} / {total}',
    score_n: 'गुण: {n}/{total}',
    question_list: 'प्रश्न',
    jump_to: 'प्रश्न {n} वर जा',
    read_aloud: 'मोठ्याने वाचून दाखवा',
    explanation: 'स्पष्टीकरण',
    correct_was: 'बरोबर उत्तर आहे {a}',
    next_q: 'पुढील प्रश्न',
    see_result: 'माझा निकाल पाहा',
    submit_test: 'चाचणी सबमिट करा',
    quit: 'बाहेर पडा',
    confirm_quit: 'ही क्विझ थांबवायची? या क्विझमधील प्रगती पुसली जाईल.',
    confirm_submit: 'उत्तर न दिलेले प्रश्न: {n}. तरीही चाचणी सबमिट करायची?',
    time_left: 'उरलेला वेळ',
    times_up: 'वेळ संपली!',
    kbd_hint: 'टीप: उत्तरासाठी 1–4 दाबा आणि पुढील प्रश्नासाठी Enter.',
    result_title: 'तुमचा निकाल',
    msg_90: 'उत्कृष्ट! तुम्हाला AI च्या मूलभूत गोष्टी खरोखर चांगल्या येतात.',
    msg_75: 'छान काम! चुकलेले थोडे प्रश्न पुन्हा पाहा.',
    msg_50: 'चांगली सुरुवात. स्पष्टीकरणे वाचा आणि पुन्हा प्रयत्न करा.',
    msg_0: 'सराव करत राहा. प्रत्येक तज्ज्ञ कधीतरी नवशिका होता!',
    n_correct: 'बरोबर: {n}',
    n_wrong: 'चूक: {n}',
    n_skipped: 'उत्तर नाही: {n}',
    time_taken: 'वेळ: {t}',
    by_topic: 'विषयानुसार गुण',
    revise_tip: 'हे विषय पुन्हा वाचा: {list}',
    practice_mistakes: 'माझ्या चुकांचा सराव',
    new_quiz: 'नवीन क्विझ',
    back_setup: 'सुरुवातीला परत',
    cert_section: 'तुमचे प्रमाणपत्र',
    your_name: 'तुमचे नाव',
    name_ph: 'उदा. अनन्या देशमुख',
    school_label: 'शाळा आणि इयत्ता (ऐच्छिक)',
    school_ph: 'उदा. इयत्ता 9 B, शासकीय माध्यमिक शाळा, पुणे',
    cert_hint: 'टीप: फोनवर ठेवण्यासाठी प्रिंट विंडोमध्ये PDF म्हणून सेव्ह करा.',
    cert_title: 'गौरव प्रमाणपत्र',
    cert_certify: 'प्रमाणित करण्यात येते की',
    cert_body: 'यांनी AI बेसिक्स क्विझमध्ये {total} पैकी {score} गुण ({pct}%) मिळवले आहेत.',
    cert_topics: 'विषय: {list}',
    cert_date: 'दिनांक: {d}',
    cert_sign: 'शिक्षकांची स्वाक्षरी',
    badge_star: 'AI स्टार',
    badge_explorer: 'AI एक्सप्लोरर',
    badge_learner: 'AI लर्नर',
    badge_starter: 'AI नवशिके',
    print_cert: 'प्रमाणपत्र प्रिंट करा',
    review: 'तुमची उत्तरे तपासा',
    only_wrong: 'फक्त चुका दाखवा',
    your_answer: 'तुमचे उत्तर',
    not_answered: 'उत्तर दिले नाही',
    no_mistakes: 'एकही चूक नाही. पूर्ण गुण!',
    reveal: 'उत्तर दाखवा',
    answer_is: 'उत्तर: {a}',
    class_finish: 'क्विझ संपवा',
    restart_timer: 'टायमर पुन्हा सुरू करा',
    plus_point: '{team} ला +1 गुण',
    minus_point: '{team} चा −1 गुण',
    class_tip: 'संघांना चर्चा करू द्या, मग "उत्तर दाखवा" दाबा. बरोबर उत्तर देणाऱ्या प्रत्येक संघाला +1 द्या.',
    winner: '{team} जिंकला!',
    tie: 'बरोबरी! सर्वांनी छान खेळ केला.',
    final_scores: 'अंतिम गुण',
    play_again: 'पुन्हा खेळा',
    paper_title: 'AI बेसिक्स: प्रश्नपत्रिका',
    n_questions: '{n} प्रश्न',
    paper_name: 'नाव: ____________________',
    paper_class: 'इयत्ता: ________',
    paper_date: 'दिनांक: ____________',
    paper_marks: 'गुण: ______ / {total}',
    paper_instr: 'प्रत्येक प्रश्नासाठी बरोबर पर्याय निवडा. प्रत्येक प्रश्नाला 1 गुण आहे.',
    answer_key: 'उत्तरसूची (शिक्षकांसाठी)',
    made_with: 'AI की पाठशाला ॲप्सने बनवले: प्रत्येक शाळेसाठी मोफत.'
  },

  gu: {
    app_title: 'AI બેઝિક્સ ક્વિઝ',
    intro: 'આર્ટિફિશિયલ ઇન્ટેલિજન્સ (AI)ની મૂળભૂત બાબતોનો અભ્યાસ કરો: AI, ML અને DL, AIનાં ક્ષેત્રો, AI પ્રોજેક્ટ સાયકલ, મશીન કેવી રીતે શીખે છે, મૂલ્યાંકન, AI નૈતિકતા અને જનરેટિવ AI. CBSE AI (417) અભ્યાસક્રમ પર આધારિત.',
    choose_mode: 'મોડ પસંદ કરો',
    mode_practice: 'અભ્યાસ',
    mode_practice_d: 'દરેક પ્રશ્ન પછી સાચો જવાબ અને સમજૂતી જુઓ.',
    mode_test: 'ટેસ્ટ',
    mode_test_d: 'સમયબદ્ધ ટેસ્ટ. અંતે ગુણ, જવાબોની ચકાસણી અને પ્રમાણપત્ર.',
    mode_class: 'પ્રોજેક્ટર ક્વિઝ',
    mode_class_d: 'આખા વર્ગ માટે મોટી સ્ક્રીન પર ક્વિઝ, ટીમના સ્કોર સાથે.',
    topics: 'વિષયો',
    all_topics: 'બધા વિષયો',
    topic_basics: 'AI એટલે શું?',
    topic_domains: 'AIનાં ક્ષેત્રો',
    topic_cycle: 'AI પ્રોજેક્ટ સાયકલ',
    topic_learning: 'મશીન કેવી રીતે શીખે છે',
    topic_eval: 'મૂલ્યાંકન',
    topic_ethics: 'AI નૈતિકતા',
    topic_genai: 'જનરેટિવ AI',
    n_available: '{n} પ્રશ્નો',
    pick_topic: 'શરૂ કરવા ઓછામાં ઓછો એક વિષય પસંદ કરો.',
    num_questions: 'પ્રશ્નોની સંખ્યા',
    all_n: 'બધા ({n})',
    time_limit: 'સમય મર્યાદા',
    time_per_q: 'દરેક પ્રશ્ન માટે {s} સેકન્ડ',
    no_limit: 'કોઈ સમય મર્યાદા નહીં',
    total_time: 'કુલ સમય: {t}',
    q_timer: 'દરેક પ્રશ્નનું ટાઇમર',
    sec_n: '{s} સેકન્ડ',
    timer_off: 'ટાઇમર નહીં',
    num_teams: 'ટીમોની સંખ્યા',
    team_n: 'ટીમ {n}',
    team_name_label: 'ટીમ {n}નું નામ',
    shuffle_q: 'પ્રશ્નો ભેળવો',
    shuffle_o: 'વિકલ્પો ભેળવો',
    start_quiz: 'ક્વિઝ શરૂ કરો',
    print_paper: 'પ્રશ્નપત્ર પ્રિન્ટ કરો',
    resume_title: 'અધૂરી ક્વિઝ ({mode}): પ્રશ્ન {n} / {total}.',
    discard: 'કાઢી નાખો',
    help_title: 'કેવી રીતે વાપરવું / વર્ગ માટે વિચારો',
    help_1: 'અભ્યાસમાં દરેક પ્રશ્ન પછી સાચો જવાબ અને ટૂંકી સમજૂતી દેખાય છે. ટેસ્ટમાં જવાબો અંત સુધી છુપાયેલા રહે છે અને ટાઇમર ચાલે છે. પ્રોજેક્ટર ક્વિઝ સ્માર્ટબોર્ડ કે TV પર આખા વર્ગ માટે છે.',
    help_2: 'એક સમયે એક પ્રકરણનું પુનરાવર્તન કરવા વિષયનાં બટન દબાવો, જેમ કે એકમ કસોટી પહેલાં ફક્ત "મૂલ્યાંકન".',
    help_3: 'વર્ગ પ્રવૃત્તિ: વર્ગને 2 થી 4 ટીમોમાં વહેંચો (શાળાનાં હાઉસ પણ ચાલશે). પ્રોજેક્ટર પર પ્રશ્ન બતાવો, ટીમોને 30 સેકન્ડ ચર્ચા કરવા દો, પછી "જવાબ બતાવો" દબાવો અને સાચો જવાબ આપનાર દરેક ટીમને +1 આપો.',
    help_4: 'કીબોર્ડ: વિકલ્પ પસંદ કરવા 1–4 અથવા A–D દબાવો અને આગલા પ્રશ્ન માટે Enter. પ્રોજેક્ટર ક્વિઝમાં જવાબ બતાવવા R, ટાઇમર રોકવા T અને પૂરી સ્ક્રીન માટે F દબાવો.',
    help_5: 'ઝડપી વર્ગ ટેસ્ટ માટે જવાબ-ચાવી સાથે પ્રશ્નપત્ર પ્રિન્ટ કરો, અથવા ટેસ્ટ પછી દરેક વિદ્યાર્થીનું પ્રમાણપત્ર પ્રિન્ટ કરો.',
    help_6: 'પરિણામો ફક્ત આ જ ડિવાઇસ પર સેવ થાય છે. કોઈ સાઇન-અપ નહીં, કોઈ જાહેરાત નહીં, અને પહેલી વાર ખોલ્યા પછી ઇન્ટરનેટ વગર પણ ચાલે છે.',
    formula_title: 'ઝડપી સૂત્ર કાર્ડ (મૂલ્યાંકન)',
    f_accuracy: 'ચોકસાઈ (Accuracy)',
    f_precision: 'પ્રિસિઝન (Precision)',
    f_recall: 'રિકૉલ (Recall)',
    f_f1: 'F1 સ્કોર',
    f_note: 'TP = ટ્રુ પૉઝિટિવ, TN = ટ્રુ નેગેટિવ, FP = ફૉલ્સ પૉઝિટિવ, FN = ફૉલ્સ નેગેટિવ, P = પ્રિસિઝન, R = રિકૉલ.',
    history_title: 'તમારાં તાજેતરનાં પરિણામો',
    history_empty: 'હજી કોઈ પરિણામ નથી. અભ્યાસ કે ટેસ્ટ પૂરો કરો, તમારા ગુણ અહીં દેખાશે.',
    best_score: 'શ્રેષ્ઠ: {pct}%',
    see_last: 'છેલ્લું પરિણામ જુઓ',
    reset_all: 'બધું રીસેટ કરો',
    reset_done: 'બધું રીસેટ થઈ ગયું.',
    q_of: 'પ્રશ્ન {n} / {total}',
    score_n: 'ગુણ: {n}/{total}',
    question_list: 'પ્રશ્નો',
    jump_to: 'પ્રશ્ન {n} પર જાઓ',
    read_aloud: 'મોટેથી વાંચી સંભળાવો',
    explanation: 'સમજૂતી',
    correct_was: 'સાચો જવાબ છે {a}',
    next_q: 'આગલો પ્રશ્ન',
    see_result: 'મારું પરિણામ જુઓ',
    submit_test: 'ટેસ્ટ સબમિટ કરો',
    quit: 'બહાર નીકળો',
    confirm_quit: 'આ ક્વિઝ બંધ કરવી છે? આ ક્વિઝની પ્રગતિ ભૂંસાઈ જશે.',
    confirm_submit: 'જવાબ વગરના પ્રશ્નો: {n}. છતાં ટેસ્ટ સબમિટ કરવો છે?',
    time_left: 'બાકી સમય',
    times_up: 'સમય પૂરો!',
    kbd_hint: 'ટિપ: જવાબ માટે 1–4 દબાવો અને આગલા પ્રશ્ન માટે Enter.',
    result_title: 'તમારું પરિણામ',
    msg_90: 'અદ્ભુત! તમને AIની મૂળભૂત બાબતો ખરેખર સારી રીતે આવડે છે.',
    msg_75: 'ખૂબ સરસ! જે થોડા ચૂકી ગયા તે ફરી જોઈ લો.',
    msg_50: 'સારી શરૂઆત. સમજૂતીઓ વાંચો અને ફરી પ્રયાસ કરો.',
    msg_0: 'અભ્યાસ ચાલુ રાખો. દરેક નિષ્ણાત ક્યારેક શિખાઉ હતો!',
    n_correct: 'સાચા: {n}',
    n_wrong: 'ખોટા: {n}',
    n_skipped: 'જવાબ નથી આપ્યો: {n}',
    time_taken: 'સમય: {t}',
    by_topic: 'વિષય પ્રમાણે ગુણ',
    revise_tip: 'આ વિષયો ફરીથી વાંચો: {list}',
    practice_mistakes: 'મારી ભૂલોનો અભ્યાસ',
    new_quiz: 'નવી ક્વિઝ',
    back_setup: 'શરૂઆત પર પાછા',
    cert_section: 'તમારું પ્રમાણપત્ર',
    your_name: 'તમારું નામ',
    name_ph: 'જેમ કે: અનન્યા પટેલ',
    school_label: 'શાળા અને ધોરણ (વૈકલ્પિક)',
    school_ph: 'જેમ કે: ધોરણ 9 B, સરકારી માધ્યમિક શાળા, અમદાવાદ',
    cert_hint: 'ટિપ: ફોનમાં રાખવા માટે પ્રિન્ટ વિન્ડોમાં PDF તરીકે સેવ કરો.',
    cert_title: 'સિદ્ધિ પ્રમાણપત્ર',
    cert_certify: 'આથી પ્રમાણિત કરવામાં આવે છે કે',
    cert_body: 'એ AI બેઝિક્સ ક્વિઝમાં {total}માંથી {score} ગુણ ({pct}%) મેળવ્યા છે.',
    cert_topics: 'વિષયો: {list}',
    cert_date: 'તારીખ: {d}',
    cert_sign: 'શિક્ષકની સહી',
    badge_star: 'AI સ્ટાર',
    badge_explorer: 'AI એક્સપ્લોરર',
    badge_learner: 'AI લર્નર',
    badge_starter: 'AI શિખાઉ',
    print_cert: 'પ્રમાણપત્ર પ્રિન્ટ કરો',
    review: 'તમારા જવાબો તપાસો',
    only_wrong: 'ફક્ત ભૂલો બતાવો',
    your_answer: 'તમારો જવાબ',
    not_answered: 'જવાબ નથી આપ્યો',
    no_mistakes: 'એક પણ ભૂલ નહીં. પૂરા ગુણ!',
    reveal: 'જવાબ બતાવો',
    answer_is: 'જવાબ: {a}',
    class_finish: 'ક્વિઝ પૂરી કરો',
    restart_timer: 'ટાઇમર ફરી શરૂ કરો',
    plus_point: '{team}ને +1 પોઇન્ટ',
    minus_point: '{team}નો −1 પોઇન્ટ',
    class_tip: 'ટીમોને ચર્ચા કરવા દો, પછી "જવાબ બતાવો" દબાવો. સાચો જવાબ આપનાર દરેક ટીમને +1 આપો.',
    winner: '{team} જીતી!',
    tie: 'બરાબરી! બધાએ સરસ રમત રમી.',
    final_scores: 'અંતિમ સ્કોર',
    play_again: 'ફરી રમો',
    paper_title: 'AI બેઝિક્સ: પ્રશ્નપત્ર',
    n_questions: '{n} પ્રશ્નો',
    paper_name: 'નામ: ____________________',
    paper_class: 'ધોરણ: ________',
    paper_date: 'તારીખ: ____________',
    paper_marks: 'ગુણ: ______ / {total}',
    paper_instr: 'દરેક પ્રશ્ન માટે સાચો વિકલ્પ પસંદ કરો. દરેક પ્રશ્નનો 1 ગુણ છે.',
    answer_key: 'જવાબ-ચાવી (શિક્ષક માટે)',
    made_with: 'AI પાઠશાળા ઍપ્સથી બનાવેલું: દરેક શાળા માટે મફત.'
  },

  pa: {
    app_title: 'AI ਬੇਸਿਕਸ ਕੁਇਜ਼',
    intro: 'ਆਰਟੀਫ਼ੀਸ਼ੀਅਲ ਇੰਟੈਲੀਜੈਂਸ (AI) ਦੀਆਂ ਮੁੱਢਲੀਆਂ ਗੱਲਾਂ ਦਾ ਅਭਿਆਸ ਕਰੋ: AI, ML ਅਤੇ DL, AI ਦੇ ਖੇਤਰ, AI ਪ੍ਰੋਜੈਕਟ ਸਾਈਕਲ, ਮਸ਼ੀਨ ਕਿਵੇਂ ਸਿੱਖਦੀ ਹੈ, ਮੁਲਾਂਕਣ, AI ਨੈਤਿਕਤਾ ਅਤੇ ਜਨਰੇਟਿਵ AI। CBSE AI (417) ਸਿਲੇਬਸ ਉੱਤੇ ਆਧਾਰਿਤ।',
    choose_mode: 'ਮੋਡ ਚੁਣੋ',
    mode_practice: 'ਅਭਿਆਸ',
    mode_practice_d: 'ਹਰ ਸਵਾਲ ਤੋਂ ਬਾਅਦ ਸਹੀ ਜਵਾਬ ਅਤੇ ਵਿਆਖਿਆ ਵੇਖੋ।',
    mode_test: 'ਟੈਸਟ',
    mode_test_d: 'ਸਮੇਂ ਵਾਲਾ ਟੈਸਟ। ਅਖੀਰ ਵਿੱਚ ਅੰਕ, ਜਵਾਬਾਂ ਦੀ ਜਾਂਚ ਅਤੇ ਸਰਟੀਫਿਕੇਟ।',
    mode_class: 'ਪ੍ਰੋਜੈਕਟਰ ਕੁਇਜ਼',
    mode_class_d: 'ਪੂਰੀ ਕਲਾਸ ਲਈ ਵੱਡੀ ਸਕਰੀਨ ਉੱਤੇ ਕੁਇਜ਼, ਟੀਮ ਸਕੋਰਾਂ ਨਾਲ।',
    topics: 'ਵਿਸ਼ੇ',
    all_topics: 'ਸਾਰੇ ਵਿਸ਼ੇ',
    topic_basics: 'AI ਕੀ ਹੈ?',
    topic_domains: 'AI ਦੇ ਖੇਤਰ',
    topic_cycle: 'AI ਪ੍ਰੋਜੈਕਟ ਸਾਈਕਲ',
    topic_learning: 'ਮਸ਼ੀਨ ਕਿਵੇਂ ਸਿੱਖਦੀ ਹੈ',
    topic_eval: 'ਮੁਲਾਂਕਣ',
    topic_ethics: 'AI ਨੈਤਿਕਤਾ',
    topic_genai: 'ਜਨਰੇਟਿਵ AI',
    n_available: '{n} ਸਵਾਲ',
    pick_topic: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਵਿਸ਼ਾ ਚੁਣੋ।',
    num_questions: 'ਸਵਾਲਾਂ ਦੀ ਗਿਣਤੀ',
    all_n: 'ਸਾਰੇ ({n})',
    time_limit: 'ਸਮਾਂ ਸੀਮਾ',
    time_per_q: 'ਹਰ ਸਵਾਲ ਲਈ {s} ਸਕਿੰਟ',
    no_limit: 'ਕੋਈ ਸਮਾਂ ਸੀਮਾ ਨਹੀਂ',
    total_time: 'ਕੁੱਲ ਸਮਾਂ: {t}',
    q_timer: 'ਹਰ ਸਵਾਲ ਦਾ ਟਾਈਮਰ',
    sec_n: '{s} ਸਕਿੰਟ',
    timer_off: 'ਟਾਈਮਰ ਨਹੀਂ',
    num_teams: 'ਟੀਮਾਂ ਦੀ ਗਿਣਤੀ',
    team_n: 'ਟੀਮ {n}',
    team_name_label: 'ਟੀਮ {n} ਦਾ ਨਾਮ',
    shuffle_q: 'ਸਵਾਲ ਰਲਾਓ',
    shuffle_o: 'ਵਿਕਲਪ ਰਲਾਓ',
    start_quiz: 'ਕੁਇਜ਼ ਸ਼ੁਰੂ ਕਰੋ',
    print_paper: 'ਪ੍ਰਸ਼ਨ ਪੱਤਰ ਪ੍ਰਿੰਟ ਕਰੋ',
    resume_title: 'ਅਧੂਰਾ ਕੁਇਜ਼ ({mode}): ਸਵਾਲ {n} / {total}।',
    discard: 'ਹਟਾਓ',
    help_title: 'ਕਿਵੇਂ ਵਰਤੀਏ / ਕਲਾਸ ਲਈ ਸੁਝਾਅ',
    help_1: 'ਅਭਿਆਸ ਵਿੱਚ ਹਰ ਸਵਾਲ ਤੋਂ ਬਾਅਦ ਸਹੀ ਜਵਾਬ ਅਤੇ ਛੋਟੀ ਵਿਆਖਿਆ ਦਿਸਦੀ ਹੈ। ਟੈਸਟ ਵਿੱਚ ਜਵਾਬ ਅਖੀਰ ਤੱਕ ਲੁਕੇ ਰਹਿੰਦੇ ਹਨ ਅਤੇ ਟਾਈਮਰ ਚੱਲਦਾ ਹੈ। ਪ੍ਰੋਜੈਕਟਰ ਕੁਇਜ਼ ਸਮਾਰਟਬੋਰਡ ਜਾਂ TV ਉੱਤੇ ਪੂਰੀ ਕਲਾਸ ਲਈ ਹੈ।',
    help_2: 'ਇੱਕ ਵਾਰ ਵਿੱਚ ਇੱਕ ਪਾਠ ਦੁਹਰਾਉਣ ਲਈ ਵਿਸ਼ੇ ਦੇ ਬਟਨ ਦਬਾਓ, ਜਿਵੇਂ ਯੂਨਿਟ ਟੈਸਟ ਤੋਂ ਪਹਿਲਾਂ ਸਿਰਫ਼ "ਮੁਲਾਂਕਣ"।',
    help_3: 'ਕਲਾਸ ਗਤੀਵਿਧੀ: ਕਲਾਸ ਨੂੰ 2 ਤੋਂ 4 ਟੀਮਾਂ ਵਿੱਚ ਵੰਡੋ (ਸਕੂਲ ਦੇ ਹਾਊਸ ਵੀ ਚੱਲਣਗੇ)। ਪ੍ਰੋਜੈਕਟਰ ਉੱਤੇ ਸਵਾਲ ਵਿਖਾਓ, ਟੀਮਾਂ ਨੂੰ 30 ਸਕਿੰਟ ਚਰਚਾ ਕਰਨ ਦਿਓ, ਫਿਰ "ਜਵਾਬ ਵਿਖਾਓ" ਦਬਾਓ ਅਤੇ ਸਹੀ ਜਵਾਬ ਵਾਲੀ ਹਰ ਟੀਮ ਨੂੰ +1 ਦਿਓ।',
    help_4: 'ਕੀਬੋਰਡ: ਵਿਕਲਪ ਚੁਣਨ ਲਈ 1–4 ਜਾਂ A–D ਦਬਾਓ ਅਤੇ ਅਗਲੇ ਸਵਾਲ ਲਈ Enter। ਪ੍ਰੋਜੈਕਟਰ ਕੁਇਜ਼ ਵਿੱਚ ਜਵਾਬ ਵਿਖਾਉਣ ਲਈ R, ਟਾਈਮਰ ਰੋਕਣ ਲਈ T ਅਤੇ ਪੂਰੀ ਸਕਰੀਨ ਲਈ F ਦਬਾਓ।',
    help_5: 'ਝਟਪਟ ਕਲਾਸ ਟੈਸਟ ਲਈ ਉੱਤਰ-ਕੁੰਜੀ ਸਮੇਤ ਪ੍ਰਸ਼ਨ ਪੱਤਰ ਪ੍ਰਿੰਟ ਕਰੋ, ਜਾਂ ਟੈਸਟ ਤੋਂ ਬਾਅਦ ਹਰ ਵਿਦਿਆਰਥੀ ਦਾ ਸਰਟੀਫਿਕੇਟ ਪ੍ਰਿੰਟ ਕਰੋ।',
    help_6: 'ਨਤੀਜੇ ਸਿਰਫ਼ ਇਸੇ ਡਿਵਾਈਸ ਉੱਤੇ ਸੇਵ ਹੁੰਦੇ ਹਨ। ਕੋਈ ਸਾਈਨ-ਅੱਪ ਨਹੀਂ, ਕੋਈ ਇਸ਼ਤਿਹਾਰ ਨਹੀਂ, ਅਤੇ ਪਹਿਲੀ ਵਾਰ ਖੋਲ੍ਹਣ ਤੋਂ ਬਾਅਦ ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਵੀ ਚੱਲਦਾ ਹੈ।',
    formula_title: 'ਝਟਪਟ ਫ਼ਾਰਮੂਲਾ ਕਾਰਡ (ਮੁਲਾਂਕਣ)',
    f_accuracy: 'ਸ਼ੁੱਧਤਾ (Accuracy)',
    f_precision: 'ਪ੍ਰਿਸੀਜ਼ਨ (Precision)',
    f_recall: 'ਰੀਕਾਲ (Recall)',
    f_f1: 'F1 ਸਕੋਰ',
    f_note: 'TP = ਟਰੂ ਪਾਜ਼ਿਟਿਵ, TN = ਟਰੂ ਨੈਗੇਟਿਵ, FP = ਫਾਲਸ ਪਾਜ਼ਿਟਿਵ, FN = ਫਾਲਸ ਨੈਗੇਟਿਵ, P = ਪ੍ਰਿਸੀਜ਼ਨ, R = ਰੀਕਾਲ।',
    history_title: 'ਤੁਹਾਡੇ ਹਾਲੀਆ ਨਤੀਜੇ',
    history_empty: 'ਅਜੇ ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ। ਅਭਿਆਸ ਜਾਂ ਟੈਸਟ ਪੂਰਾ ਕਰੋ, ਤੁਹਾਡੇ ਅੰਕ ਇੱਥੇ ਦਿਸਣਗੇ।',
    best_score: 'ਸਭ ਤੋਂ ਵਧੀਆ: {pct}%',
    see_last: 'ਪਿਛਲਾ ਨਤੀਜਾ ਵੇਖੋ',
    reset_all: 'ਸਭ ਕੁਝ ਰੀਸੈੱਟ ਕਰੋ',
    reset_done: 'ਸਭ ਕੁਝ ਰੀਸੈੱਟ ਹੋ ਗਿਆ।',
    q_of: 'ਸਵਾਲ {n} / {total}',
    score_n: 'ਅੰਕ: {n}/{total}',
    question_list: 'ਸਵਾਲ',
    jump_to: 'ਸਵਾਲ {n} ਉੱਤੇ ਜਾਓ',
    read_aloud: 'ਪੜ੍ਹ ਕੇ ਸੁਣਾਓ',
    explanation: 'ਵਿਆਖਿਆ',
    correct_was: 'ਸਹੀ ਜਵਾਬ ਹੈ {a}',
    next_q: 'ਅਗਲਾ ਸਵਾਲ',
    see_result: 'ਮੇਰਾ ਨਤੀਜਾ ਵੇਖੋ',
    submit_test: 'ਟੈਸਟ ਜਮ੍ਹਾਂ ਕਰੋ',
    quit: 'ਛੱਡੋ',
    confirm_quit: 'ਇਹ ਕੁਇਜ਼ ਬੰਦ ਕਰਨਾ ਹੈ? ਇਸ ਕੁਇਜ਼ ਦੀ ਤਰੱਕੀ ਮਿਟ ਜਾਵੇਗੀ।',
    confirm_submit: 'ਬਿਨਾਂ ਜਵਾਬ ਵਾਲੇ ਸਵਾਲ: {n}। ਫਿਰ ਵੀ ਟੈਸਟ ਜਮ੍ਹਾਂ ਕਰਨਾ ਹੈ?',
    time_left: 'ਬਾਕੀ ਸਮਾਂ',
    times_up: 'ਸਮਾਂ ਖ਼ਤਮ!',
    kbd_hint: 'ਸੁਝਾਅ: ਜਵਾਬ ਲਈ 1–4 ਦਬਾਓ ਅਤੇ ਅਗਲੇ ਸਵਾਲ ਲਈ Enter।',
    result_title: 'ਤੁਹਾਡਾ ਨਤੀਜਾ',
    msg_90: 'ਸ਼ਾਨਦਾਰ! ਤੁਹਾਨੂੰ AI ਦੀਆਂ ਮੁੱਢਲੀਆਂ ਗੱਲਾਂ ਸੱਚਮੁੱਚ ਚੰਗੀ ਤਰ੍ਹਾਂ ਆਉਂਦੀਆਂ ਹਨ।',
    msg_75: 'ਬਹੁਤ ਵਧੀਆ! ਜਿਹੜੇ ਥੋੜ੍ਹੇ ਰਹਿ ਗਏ, ਉਹ ਦੁਹਰਾ ਲਓ।',
    msg_50: 'ਚੰਗੀ ਸ਼ੁਰੂਆਤ। ਵਿਆਖਿਆਵਾਂ ਪੜ੍ਹੋ ਅਤੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    msg_0: 'ਅਭਿਆਸ ਕਰਦੇ ਰਹੋ। ਹਰ ਮਾਹਿਰ ਕਦੇ ਨਵਾਂ ਸਿੱਖਣ ਵਾਲਾ ਸੀ!',
    n_correct: 'ਸਹੀ: {n}',
    n_wrong: 'ਗਲਤ: {n}',
    n_skipped: 'ਜਵਾਬ ਨਹੀਂ ਦਿੱਤਾ: {n}',
    time_taken: 'ਸਮਾਂ: {t}',
    by_topic: 'ਵਿਸ਼ੇ ਅਨੁਸਾਰ ਅੰਕ',
    revise_tip: 'ਇਹ ਵਿਸ਼ੇ ਦੁਬਾਰਾ ਪੜ੍ਹੋ: {list}',
    practice_mistakes: 'ਮੇਰੀਆਂ ਗਲਤੀਆਂ ਦਾ ਅਭਿਆਸ',
    new_quiz: 'ਨਵਾਂ ਕੁਇਜ਼',
    back_setup: 'ਸ਼ੁਰੂਆਤ ਉੱਤੇ ਵਾਪਸ',
    cert_section: 'ਤੁਹਾਡਾ ਸਰਟੀਫਿਕੇਟ',
    your_name: 'ਤੁਹਾਡਾ ਨਾਮ',
    name_ph: 'ਜਿਵੇਂ: ਸਿਮਰਨ ਕੌਰ',
    school_label: 'ਸਕੂਲ ਅਤੇ ਜਮਾਤ (ਲਾਜ਼ਮੀ ਨਹੀਂ)',
    school_ph: 'ਜਿਵੇਂ: ਜਮਾਤ 9 B, ਸਰਕਾਰੀ ਸੀਨੀਅਰ ਸੈਕੰਡਰੀ ਸਕੂਲ, ਲੁਧਿਆਣਾ',
    cert_hint: 'ਸੁਝਾਅ: ਫ਼ੋਨ ਵਿੱਚ ਰੱਖਣ ਲਈ ਪ੍ਰਿੰਟ ਵਿੰਡੋ ਵਿੱਚ PDF ਵਜੋਂ ਸੇਵ ਕਰੋ।',
    cert_title: 'ਪ੍ਰਾਪਤੀ ਸਰਟੀਫਿਕੇਟ',
    cert_certify: 'ਪ੍ਰਮਾਣਿਤ ਕੀਤਾ ਜਾਂਦਾ ਹੈ ਕਿ',
    cert_body: 'ਨੇ AI ਬੇਸਿਕਸ ਕੁਇਜ਼ ਵਿੱਚ {total} ਵਿੱਚੋਂ {score} ਅੰਕ ({pct}%) ਪ੍ਰਾਪਤ ਕੀਤੇ।',
    cert_topics: 'ਵਿਸ਼ੇ: {list}',
    cert_date: 'ਮਿਤੀ: {d}',
    cert_sign: 'ਅਧਿਆਪਕ ਦੇ ਦਸਤਖ਼ਤ',
    badge_star: 'AI ਸਟਾਰ',
    badge_explorer: 'AI ਐਕਸਪਲੋਰਰ',
    badge_learner: 'AI ਲਰਨਰ',
    badge_starter: 'AI ਸ਼ੁਰੂਆਤੀ',
    print_cert: 'ਸਰਟੀਫਿਕੇਟ ਪ੍ਰਿੰਟ ਕਰੋ',
    review: 'ਆਪਣੇ ਜਵਾਬ ਜਾਂਚੋ',
    only_wrong: 'ਸਿਰਫ਼ ਗਲਤੀਆਂ ਵਿਖਾਓ',
    your_answer: 'ਤੁਹਾਡਾ ਜਵਾਬ',
    not_answered: 'ਜਵਾਬ ਨਹੀਂ ਦਿੱਤਾ',
    no_mistakes: 'ਕੋਈ ਗਲਤੀ ਨਹੀਂ। ਪੂਰੇ ਅੰਕ!',
    reveal: 'ਜਵਾਬ ਵਿਖਾਓ',
    answer_is: 'ਜਵਾਬ: {a}',
    class_finish: 'ਕੁਇਜ਼ ਖ਼ਤਮ ਕਰੋ',
    restart_timer: 'ਟਾਈਮਰ ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ',
    plus_point: '{team} ਨੂੰ +1 ਅੰਕ',
    minus_point: '{team} ਦਾ −1 ਅੰਕ',
    class_tip: 'ਟੀਮਾਂ ਨੂੰ ਚਰਚਾ ਕਰਨ ਦਿਓ, ਫਿਰ "ਜਵਾਬ ਵਿਖਾਓ" ਦਬਾਓ। ਸਹੀ ਜਵਾਬ ਵਾਲੀ ਹਰ ਟੀਮ ਨੂੰ +1 ਦਿਓ।',
    winner: '{team} ਜਿੱਤ ਗਈ!',
    tie: 'ਮੁਕਾਬਲਾ ਬਰਾਬਰ! ਸਭ ਨੇ ਵਧੀਆ ਖੇਡਿਆ।',
    final_scores: 'ਅੰਤਿਮ ਸਕੋਰ',
    play_again: 'ਫਿਰ ਖੇਡੋ',
    paper_title: 'AI ਬੇਸਿਕਸ: ਪ੍ਰਸ਼ਨ ਪੱਤਰ',
    n_questions: '{n} ਸਵਾਲ',
    paper_name: 'ਨਾਮ: ____________________',
    paper_class: 'ਜਮਾਤ: ________',
    paper_date: 'ਮਿਤੀ: ____________',
    paper_marks: 'ਅੰਕ: ______ / {total}',
    paper_instr: 'ਹਰ ਸਵਾਲ ਦਾ ਸਹੀ ਵਿਕਲਪ ਚੁਣੋ। ਹਰ ਸਵਾਲ 1 ਅੰਕ ਦਾ ਹੈ।',
    answer_key: 'ਉੱਤਰ-ਕੁੰਜੀ (ਅਧਿਆਪਕ ਲਈ)',
    made_with: 'AI ਪਾਠਸ਼ਾਲਾ ਐਪਸ ਨਾਲ ਬਣਾਇਆ: ਹਰ ਸਕੂਲ ਲਈ ਮੁਫ਼ਤ।'
  },

  or: {
    app_title: 'AI ବେସିକ୍ସ କୁଇଜ୍',
    intro: 'ଆର୍ଟିଫିସିଆଲ ଇଣ୍ଟେଲିଜେନ୍ସ (AI)ର ମୂଳ କଥାଗୁଡ଼ିକ ଅଭ୍ୟାସ କରନ୍ତୁ: AI, ML ଓ DL, AIର କ୍ଷେତ୍ର, AI ପ୍ରୋଜେକ୍ଟ ସାଇକେଲ୍, ମେସିନ୍ କିପରି ଶିଖେ, ମୂଲ୍ୟାଙ୍କନ, AI ନୈତିକତା ଓ ଜେନେରେଟିଭ୍ AI। CBSE AI (417) ପାଠ୍ୟକ୍ରମ ଆଧାରିତ।',
    choose_mode: 'ମୋଡ୍ ବାଛନ୍ତୁ',
    mode_practice: 'ଅଭ୍ୟାସ',
    mode_practice_d: 'ପ୍ରତ୍ୟେକ ପ୍ରଶ୍ନ ପରେ ଠିକ୍ ଉତ୍ତର ଓ ବ୍ୟାଖ୍ୟା ଦେଖନ୍ତୁ।',
    mode_test: 'ଟେଷ୍ଟ',
    mode_test_d: 'ସମୟବଦ୍ଧ ଟେଷ୍ଟ। ଶେଷରେ ନମ୍ବର, ଉତ୍ତର ଯାଞ୍ଚ ଓ ସାର୍ଟିଫିକେଟ୍।',
    mode_class: 'ପ୍ରୋଜେକ୍ଟର କୁଇଜ୍',
    mode_class_d: 'ପୂରା ଶ୍ରେଣୀ ପାଇଁ ବଡ଼ ସ୍କ୍ରିନରେ କୁଇଜ୍, ଦଳର ସ୍କୋର ସହିତ।',
    topics: 'ବିଷୟ',
    all_topics: 'ସବୁ ବିଷୟ',
    topic_basics: 'AI କ’ଣ?',
    topic_domains: 'AIର କ୍ଷେତ୍ର',
    topic_cycle: 'AI ପ୍ରୋଜେକ୍ଟ ସାଇକେଲ୍',
    topic_learning: 'ମେସିନ୍ କିପରି ଶିଖେ',
    topic_eval: 'ମୂଲ୍ୟାଙ୍କନ',
    topic_ethics: 'AI ନୈତିକତା',
    topic_genai: 'ଜେନେରେଟିଭ୍ AI',
    n_available: '{n}ଟି ପ୍ରଶ୍ନ',
    pick_topic: 'ଆରମ୍ଭ କରିବାକୁ ଅତି କମରେ ଗୋଟିଏ ବିଷୟ ବାଛନ୍ତୁ।',
    num_questions: 'ପ୍ରଶ୍ନ ସଂଖ୍ୟା',
    all_n: 'ସବୁ ({n})',
    time_limit: 'ସମୟ ସୀମା',
    time_per_q: 'ପ୍ରତି ପ୍ରଶ୍ନ ପାଇଁ {s} ସେକେଣ୍ଡ',
    no_limit: 'କୌଣସି ସମୟ ସୀମା ନାହିଁ',
    total_time: 'ମୋଟ ସମୟ: {t}',
    q_timer: 'ପ୍ରତି ପ୍ରଶ୍ନର ଟାଇମର',
    sec_n: '{s} ସେକେଣ୍ଡ',
    timer_off: 'ଟାଇମର ନାହିଁ',
    num_teams: 'ଦଳ ସଂଖ୍ୟା',
    team_n: 'ଦଳ {n}',
    team_name_label: 'ଦଳ {n}ର ନାମ',
    shuffle_q: 'ପ୍ରଶ୍ନ ମିଶାନ୍ତୁ',
    shuffle_o: 'ବିକଳ୍ପ ମିଶାନ୍ତୁ',
    start_quiz: 'କୁଇଜ୍ ଆରମ୍ଭ କରନ୍ତୁ',
    print_paper: 'ପ୍ରଶ୍ନପତ୍ର ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    resume_title: 'ଅସମ୍ପୂର୍ଣ୍ଣ କୁଇଜ୍ ({mode}): ପ୍ରଶ୍ନ {n} / {total}।',
    discard: 'ବାଦ ଦିଅନ୍ତୁ',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ଶ୍ରେଣୀ ପାଇଁ ପରାମର୍ଶ',
    help_1: 'ଅଭ୍ୟାସରେ ପ୍ରତ୍ୟେକ ପ୍ରଶ୍ନ ପରେ ଠିକ୍ ଉତ୍ତର ଓ ଛୋଟ ବ୍ୟାଖ୍ୟା ଦେଖାଯାଏ। ଟେଷ୍ଟରେ ଉତ୍ତର ଶେଷ ପର୍ଯ୍ୟନ୍ତ ଲୁଚି ରହେ ଏବଂ ଟାଇମର ଚାଲେ। ପ୍ରୋଜେକ୍ଟର କୁଇଜ୍ ସ୍ମାର୍ଟବୋର୍ଡ ବା TVରେ ପୂରା ଶ୍ରେଣୀ ପାଇଁ।',
    help_2: 'ଥରକେ ଗୋଟିଏ ଅଧ୍ୟାୟ ଦୋହରାଇବାକୁ ବିଷୟ ବଟନ୍ ଦବାନ୍ତୁ, ଯେପରି ୟୁନିଟ୍ ଟେଷ୍ଟ ପୂର୍ବରୁ କେବଳ "ମୂଲ୍ୟାଙ୍କନ"।',
    help_3: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ: ଶ୍ରେଣୀକୁ 2 ରୁ 4ଟି ଦଳରେ ଭାଗ କରନ୍ତୁ (ସ୍କୁଲର ହାଉସ୍ ମଧ୍ୟ ଚଳିବ)। ପ୍ରୋଜେକ୍ଟରରେ ପ୍ରଶ୍ନ ଦେଖାନ୍ତୁ, ଦଳଗୁଡ଼ିକୁ 30 ସେକେଣ୍ଡ ଆଲୋଚନା କରିବାକୁ ଦିଅନ୍ତୁ, ତା’ପରେ "ଉତ୍ତର ଦେଖାନ୍ତୁ" ଦବାନ୍ତୁ ଏବଂ ଠିକ୍ ଉତ୍ତର ଦେଇଥିବା ପ୍ରତ୍ୟେକ ଦଳକୁ +1 ଦିଅନ୍ତୁ।',
    help_4: 'କିବୋର୍ଡ: ବିକଳ୍ପ ବାଛିବାକୁ 1–4 ବା A–D ଦବାନ୍ତୁ ଏବଂ ପରବର୍ତ୍ତୀ ପ୍ରଶ୍ନ ପାଇଁ Enter। ପ୍ରୋଜେକ୍ଟର କୁଇଜରେ ଉତ୍ତର ଦେଖାଇବାକୁ R, ଟାଇମର ରୋକିବାକୁ T ଏବଂ ପୂରା ସ୍କ୍ରିନ ପାଇଁ F ଦବାନ୍ତୁ।',
    help_5: 'ଶୀଘ୍ର ଶ୍ରେଣୀ ଟେଷ୍ଟ ପାଇଁ ଉତ୍ତର-ତାଲିକା ସହ ପ୍ରଶ୍ନପତ୍ର ପ୍ରିଣ୍ଟ କରନ୍ତୁ, କିମ୍ବା ଟେଷ୍ଟ ପରେ ପ୍ରତ୍ୟେକ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ସାର୍ଟିଫିକେଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ।',
    help_6: 'ଫଳାଫଳ କେବଳ ଏହି ଡିଭାଇସରେ ସେଭ୍ ହୁଏ। ସାଇନ୍-ଅପ୍ ନାହିଁ, ବିଜ୍ଞାପନ ନାହିଁ, ଏବଂ ପ୍ରଥମ ଥର ଖୋଲିବା ପରେ ଇଣ୍ଟରନେଟ୍ ବିନା ମଧ୍ୟ ଚାଲେ।',
    formula_title: 'ଶୀଘ୍ର ସୂତ୍ର କାର୍ଡ (ମୂଲ୍ୟାଙ୍କନ)',
    f_accuracy: 'ସଠିକତା (Accuracy)',
    f_precision: 'ପ୍ରିସିଜନ୍ (Precision)',
    f_recall: 'ରିକଲ୍ (Recall)',
    f_f1: 'F1 ସ୍କୋର',
    f_note: 'TP = ଟ୍ରୁ ପଜିଟିଭ୍, TN = ଟ୍ରୁ ନେଗେଟିଭ୍, FP = ଫଲ୍ସ ପଜିଟିଭ୍, FN = ଫଲ୍ସ ନେଗେଟିଭ୍, P = ପ୍ରିସିଜନ୍, R = ରିକଲ୍।',
    history_title: 'ଆପଣଙ୍କ ସାମ୍ପ୍ରତିକ ଫଳାଫଳ',
    history_empty: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫଳାଫଳ ନାହିଁ। ଅଭ୍ୟାସ ବା ଟେଷ୍ଟ ଶେଷ କରନ୍ତୁ, ଆପଣଙ୍କ ନମ୍ବର ଏଠାରେ ଦେଖାଯିବ।',
    best_score: 'ସର୍ବୋତ୍ତମ: {pct}%',
    see_last: 'ଶେଷ ଫଳାଫଳ ଦେଖନ୍ତୁ',
    reset_all: 'ସବୁକିଛି ରିସେଟ୍ କରନ୍ତୁ',
    reset_done: 'ସବୁକିଛି ରିସେଟ୍ ହୋଇଗଲା।',
    q_of: 'ପ୍ରଶ୍ନ {n} / {total}',
    score_n: 'ନମ୍ବର: {n}/{total}',
    question_list: 'ପ୍ରଶ୍ନଗୁଡ଼ିକ',
    jump_to: 'ପ୍ରଶ୍ନ {n}କୁ ଯାଆନ୍ତୁ',
    read_aloud: 'ପଢ଼ି ଶୁଣାନ୍ତୁ',
    explanation: 'ବ୍ୟାଖ୍ୟା',
    correct_was: 'ଠିକ୍ ଉତ୍ତର ହେଉଛି {a}',
    next_q: 'ପରବର୍ତ୍ତୀ ପ୍ରଶ୍ନ',
    see_result: 'ମୋ ଫଳାଫଳ ଦେଖନ୍ତୁ',
    submit_test: 'ଟେଷ୍ଟ ଦାଖଲ କରନ୍ତୁ',
    quit: 'ବାହାରନ୍ତୁ',
    confirm_quit: 'ଏହି କୁଇଜ୍ ବନ୍ଦ କରିବେ? ଏହି କୁଇଜର ପ୍ରଗତି ଲିଭିଯିବ।',
    confirm_submit: 'ଉତ୍ତର ଦିଆଯାଇନଥିବା ପ୍ରଶ୍ନ: {n}। ତଥାପି ଟେଷ୍ଟ ଦାଖଲ କରିବେ?',
    time_left: 'ବାକି ସମୟ',
    times_up: 'ସମୟ ସରିଗଲା!',
    kbd_hint: 'ଟିପ୍: ଉତ୍ତର ପାଇଁ 1–4 ଦବାନ୍ତୁ ଏବଂ ପରବର୍ତ୍ତୀ ପ୍ରଶ୍ନ ପାଇଁ Enter।',
    result_title: 'ଆପଣଙ୍କ ଫଳାଫଳ',
    msg_90: 'ଚମତ୍କାର! AIର ମୂଳ କଥା ଆପଣ ସତରେ ଭଲ ଜାଣନ୍ତି।',
    msg_75: 'ବହୁତ ଭଲ! ଯେଉଁ କେଇଟା ଭୁଲ ହେଲା, ସେଗୁଡ଼ିକ ପୁଣି ଦେଖନ୍ତୁ।',
    msg_50: 'ଭଲ ଆରମ୍ଭ। ବ୍ୟାଖ୍ୟାଗୁଡ଼ିକ ପଢ଼ନ୍ତୁ ଏବଂ ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
    msg_0: 'ଅଭ୍ୟାସ ଜାରି ରଖନ୍ତୁ। ପ୍ରତ୍ୟେକ ବିଶେଷଜ୍ଞ ଦିନେ ନୂଆ ଶିକ୍ଷାର୍ଥୀ ଥିଲେ!',
    n_correct: 'ଠିକ୍: {n}',
    n_wrong: 'ଭୁଲ: {n}',
    n_skipped: 'ଉତ୍ତର ଦିଆଯାଇନାହିଁ: {n}',
    time_taken: 'ସମୟ: {t}',
    by_topic: 'ବିଷୟ ଅନୁସାରେ ନମ୍ବର',
    revise_tip: 'ଏହି ବିଷୟଗୁଡ଼ିକ ପୁଣି ପଢ଼ନ୍ତୁ: {list}',
    practice_mistakes: 'ମୋ ଭୁଲଗୁଡ଼ିକର ଅଭ୍ୟାସ',
    new_quiz: 'ନୂଆ କୁଇଜ୍',
    back_setup: 'ଆରମ୍ଭକୁ ଫେରନ୍ତୁ',
    cert_section: 'ଆପଣଙ୍କ ସାର୍ଟିଫିକେଟ୍',
    your_name: 'ଆପଣଙ୍କ ନାମ',
    name_ph: 'ଯେପରି: ଅନନ୍ୟା ମହାନ୍ତି',
    school_label: 'ସ୍କୁଲ ଓ ଶ୍ରେଣୀ (ଇଚ୍ଛାଧୀନ)',
    school_ph: 'ଯେପରି: ନବମ ଶ୍ରେଣୀ B, ସରକାରୀ ଉଚ୍ଚ ବିଦ୍ୟାଳୟ, କଟକ',
    cert_hint: 'ଟିପ୍: ଫୋନରେ ରଖିବାକୁ ପ୍ରିଣ୍ଟ ୱିଣ୍ଡୋରେ PDF ଭାବେ ସେଭ୍ କରନ୍ତୁ।',
    cert_title: 'କୃତିତ୍ୱ ପ୍ରମାଣପତ୍ର',
    cert_certify: 'ଏହା ପ୍ରମାଣିତ କରାଯାଉଛି ଯେ',
    cert_body: 'AI ବେସିକ୍ସ କୁଇଜରେ {total}ରୁ {score} ନମ୍ବର ({pct}%) ପାଇଛନ୍ତି।',
    cert_topics: 'ବିଷୟ: {list}',
    cert_date: 'ତାରିଖ: {d}',
    cert_sign: 'ଶିକ୍ଷକଙ୍କ ସ୍ୱାକ୍ଷର',
    badge_star: 'AI ଷ୍ଟାର',
    badge_explorer: 'AI ଏକ୍ସପ୍ଲୋରର',
    badge_learner: 'AI ଲର୍ନର',
    badge_starter: 'AI ନୂଆ ଶିକ୍ଷାର୍ଥୀ',
    print_cert: 'ସାର୍ଟିଫିକେଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    review: 'ଆପଣଙ୍କ ଉତ୍ତର ଯାଞ୍ଚ କରନ୍ତୁ',
    only_wrong: 'କେବଳ ଭୁଲଗୁଡ଼ିକ ଦେଖାନ୍ତୁ',
    your_answer: 'ଆପଣଙ୍କ ଉତ୍ତର',
    not_answered: 'ଉତ୍ତର ଦିଆଯାଇନାହିଁ',
    no_mistakes: 'କୌଣସି ଭୁଲ ନାହିଁ। ପୂରା ନମ୍ବର!',
    reveal: 'ଉତ୍ତର ଦେଖାନ୍ତୁ',
    answer_is: 'ଉତ୍ତର: {a}',
    class_finish: 'କୁଇଜ୍ ଶେଷ କରନ୍ତୁ',
    restart_timer: 'ଟାଇମର ପୁଣି ଆରମ୍ଭ କରନ୍ତୁ',
    plus_point: '{team}କୁ +1 ପଏଣ୍ଟ',
    minus_point: '{team}ର −1 ପଏଣ୍ଟ',
    class_tip: 'ଦଳଗୁଡ଼ିକୁ ଆଲୋଚନା କରିବାକୁ ଦିଅନ୍ତୁ, ତା’ପରେ "ଉତ୍ତର ଦେଖାନ୍ତୁ" ଦବାନ୍ତୁ। ଠିକ୍ ଉତ୍ତର ଦେଇଥିବା ପ୍ରତ୍ୟେକ ଦଳକୁ +1 ଦିଅନ୍ତୁ।',
    winner: '{team} ଜିତିଲା!',
    tie: 'ସମାନ ସମାନ! ସମସ୍ତେ ବଢ଼ିଆ ଖେଳିଲେ।',
    final_scores: 'ଶେଷ ସ୍କୋର',
    play_again: 'ପୁଣି ଖେଳନ୍ତୁ',
    paper_title: 'AI ବେସିକ୍ସ: ପ୍ରଶ୍ନପତ୍ର',
    n_questions: '{n}ଟି ପ୍ରଶ୍ନ',
    paper_name: 'ନାମ: ____________________',
    paper_class: 'ଶ୍ରେଣୀ: ________',
    paper_date: 'ତାରିଖ: ____________',
    paper_marks: 'ନମ୍ବର: ______ / {total}',
    paper_instr: 'ପ୍ରତ୍ୟେକ ପ୍ରଶ୍ନର ଠିକ୍ ବିକଳ୍ପ ବାଛନ୍ତୁ। ପ୍ରତ୍ୟେକ ପ୍ରଶ୍ନ 1 ନମ୍ବରର।',
    answer_key: 'ଉତ୍ତର-ତାଲିକା (ଶିକ୍ଷକଙ୍କ ପାଇଁ)',
    made_with: 'AI ପାଠଶାଳା ଆପ୍ସରେ ତିଆରି: ପ୍ରତ୍ୟେକ ସ୍କୁଲ ପାଇଁ ମାଗଣା।'
  },

  ta: {
    app_title: 'AI அடிப்படை வினாடி வினா',
    intro: 'செயற்கை நுண்ணறிவின் (AI) அடிப்படைகளைப் பயிற்சி செய்யுங்கள்: AI, ML, DL, AI துறைகள், AI திட்டச் சுழற்சி, இயந்திரங்கள் எப்படிக் கற்கின்றன, மதிப்பீடு, AI நெறிமுறைகள், ஜெனரேட்டிவ் AI. CBSE AI (417) பாடத்திட்டத்தை அடிப்படையாகக் கொண்டது.',
    choose_mode: 'முறையைத் தேர்ந்தெடுங்கள்',
    mode_practice: 'பயிற்சி',
    mode_practice_d: 'ஒவ்வொரு கேள்விக்குப் பிறகும் சரியான விடையையும் விளக்கத்தையும் பாருங்கள்.',
    mode_test: 'தேர்வு',
    mode_test_d: 'நேரக் கட்டுப்பாட்டுடன் தேர்வு. இறுதியில் மதிப்பெண், சரிபார்ப்பு, சான்றிதழ்.',
    mode_class: 'புரொஜெக்டர் வினாடி வினா',
    mode_class_d: 'முழு வகுப்புக்கும் பெரிய திரையில் வினாடி வினா, அணி மதிப்பெண்களுடன்.',
    topics: 'தலைப்புகள்',
    all_topics: 'எல்லாத் தலைப்புகளும்',
    topic_basics: 'AI என்றால் என்ன?',
    topic_domains: 'AI துறைகள்',
    topic_cycle: 'AI திட்டச் சுழற்சி',
    topic_learning: 'இயந்திரங்கள் எப்படிக் கற்கின்றன',
    topic_eval: 'மதிப்பீடு',
    topic_ethics: 'AI நெறிமுறைகள்',
    topic_genai: 'ஜெனரேட்டிவ் AI',
    n_available: '{n} கேள்விகள்',
    pick_topic: 'தொடங்க குறைந்தது ஒரு தலைப்பைத் தேர்ந்தெடுங்கள்.',
    num_questions: 'கேள்விகளின் எண்ணிக்கை',
    all_n: 'அனைத்தும் ({n})',
    time_limit: 'நேர வரம்பு',
    time_per_q: 'ஒரு கேள்விக்கு {s} வினாடிகள்',
    no_limit: 'நேர வரம்பு இல்லை',
    total_time: 'மொத்த நேரம்: {t}',
    q_timer: 'ஒவ்வொரு கேள்விக்கும் டைமர்',
    sec_n: '{s} வினாடிகள்',
    timer_off: 'டைமர் இல்லை',
    num_teams: 'அணிகளின் எண்ணிக்கை',
    team_n: 'அணி {n}',
    team_name_label: 'அணி {n} பெயர்',
    shuffle_q: 'கேள்விகளைக் கலக்கவும்',
    shuffle_o: 'விருப்பங்களைக் கலக்கவும்',
    start_quiz: 'வினாடி வினாவைத் தொடங்கு',
    print_paper: 'வினாத்தாள் அச்சிடு',
    resume_title: 'முடிக்காத வினாடி வினா ({mode}): கேள்வி {n} / {total}.',
    discard: 'நீக்கு',
    help_title: 'பயன்படுத்துவது எப்படி / வகுப்பறைக்கான யோசனைகள்',
    help_1: 'பயிற்சியில் ஒவ்வொரு கேள்விக்குப் பிறகும் சரியான விடையும் சிறு விளக்கமும் தெரியும். தேர்வில் விடைகள் இறுதிவரை மறைந்திருக்கும், டைமரும் ஓடும். புரொஜெக்டர் வினாடி வினா ஸ்மார்ட்போர்டு அல்லது TV-யில் முழு வகுப்புக்கானது.',
    help_2: 'ஒரு நேரத்தில் ஒரு பாடத்தை மீள்பார்வை செய்ய தலைப்புப் பொத்தான்களை அழுத்துங்கள், எ.கா. அலகுத் தேர்வுக்கு முன் "மதிப்பீடு" மட்டும்.',
    help_3: 'வகுப்புச் செயல்பாடு: வகுப்பை 2 முதல் 4 அணிகளாகப் பிரியுங்கள் (பள்ளி இல்லங்களும் சரி). புரொஜெக்டரில் கேள்வியைக் காட்டுங்கள், அணிகள் 30 வினாடிகள் கலந்துரையாடட்டும், பிறகு "விடையைக் காட்டு" அழுத்தி சரியாகச் சொன்ன ஒவ்வொரு அணிக்கும் +1 கொடுங்கள்.',
    help_4: 'விசைப்பலகை: விருப்பத்தைத் தேர்வு செய்ய 1–4 அல்லது A–D, அடுத்த கேள்விக்கு Enter. புரொஜெக்டர் வினாடி வினாவில் விடையைக் காட்ட R, டைமரை நிறுத்த T, முழுத் திரைக்கு F அழுத்துங்கள்.',
    help_5: 'விரைவான வகுப்புத் தேர்வுக்கு விடைக் குறிப்புடன் வினாத்தாளை அச்சிடுங்கள், அல்லது தேர்வுக்குப் பின் ஒவ்வொரு மாணவருக்கும் சான்றிதழ் அச்சிடுங்கள்.',
    help_6: 'முடிவுகள் இந்தச் சாதனத்தில் மட்டுமே சேமிக்கப்படும். பதிவு தேவையில்லை, விளம்பரம் இல்லை, முதல் முறைக்குப் பிறகு இணையம் இல்லாமலும் இயங்கும்.',
    formula_title: 'விரைவு சூத்திர அட்டை (மதிப்பீடு)',
    f_accuracy: 'துல்லியம் (Accuracy)',
    f_precision: 'பிரிசிஷன் (Precision)',
    f_recall: 'ரீகால் (Recall)',
    f_f1: 'F1 மதிப்பெண்',
    f_note: 'TP = உண்மை நேர்மறை, TN = உண்மை எதிர்மறை, FP = தவறான நேர்மறை, FN = தவறான எதிர்மறை, P = பிரிசிஷன், R = ரீகால்.',
    history_title: 'உங்கள் சமீபத்திய முடிவுகள்',
    history_empty: 'இன்னும் முடிவுகள் இல்லை. ஒரு பயிற்சி அல்லது தேர்வை முடியுங்கள், உங்கள் மதிப்பெண்கள் இங்கே தெரியும்.',
    best_score: 'சிறந்தது: {pct}%',
    see_last: 'கடைசி முடிவைக் காட்டு',
    reset_all: 'அனைத்தையும் மீட்டமை',
    reset_done: 'அனைத்தும் மீட்டமைக்கப்பட்டது.',
    q_of: 'கேள்வி {n} / {total}',
    score_n: 'மதிப்பெண்: {n}/{total}',
    question_list: 'கேள்விகள்',
    jump_to: 'கேள்வி {n}-க்குச் செல்',
    read_aloud: 'உரக்கப் படி',
    explanation: 'விளக்கம்',
    correct_was: 'சரியான விடை {a}',
    next_q: 'அடுத்த கேள்வி',
    see_result: 'என் முடிவைப் பார்',
    submit_test: 'தேர்வைச் சமர்ப்பி',
    quit: 'வெளியேறு',
    confirm_quit: 'இந்த வினாடி வினாவை நிறுத்தவா? இதில் உள்ள முன்னேற்றம் அழிந்துவிடும்.',
    confirm_submit: 'விடையளிக்காத கேள்விகள்: {n}. இருந்தாலும் தேர்வைச் சமர்ப்பிக்கவா?',
    time_left: 'மீதமுள்ள நேரம்',
    times_up: 'நேரம் முடிந்தது!',
    kbd_hint: 'குறிப்பு: விடையளிக்க 1–4, அடுத்த கேள்விக்கு Enter அழுத்துங்கள்.',
    result_title: 'உங்கள் முடிவு',
    msg_90: 'அருமை! AI அடிப்படைகள் உங்களுக்கு நன்றாகத் தெரிகின்றன.',
    msg_75: 'மிக நன்று! தவறிய சிலவற்றை மீண்டும் படியுங்கள்.',
    msg_50: 'நல்ல தொடக்கம். விளக்கங்களைப் படித்து மீண்டும் முயலுங்கள்.',
    msg_0: 'தொடர்ந்து பயிற்சி செய்யுங்கள். ஒவ்வொரு நிபுணரும் ஒரு காலத்தில் தொடக்கநிலையாளர்தான்!',
    n_correct: 'சரி: {n}',
    n_wrong: 'தவறு: {n}',
    n_skipped: 'விடையளிக்கவில்லை: {n}',
    time_taken: 'நேரம்: {t}',
    by_topic: 'தலைப்பு வாரியான மதிப்பெண்',
    revise_tip: 'இந்தத் தலைப்புகளை மீண்டும் படியுங்கள்: {list}',
    practice_mistakes: 'என் தவறுகளைப் பயிற்சி செய்',
    new_quiz: 'புதிய வினாடி வினா',
    back_setup: 'தொடக்கத்துக்குத் திரும்பு',
    cert_section: 'உங்கள் சான்றிதழ்',
    your_name: 'உங்கள் பெயர்',
    name_ph: 'எ.கா. அனன்யா ராஜன்',
    school_label: 'பள்ளி மற்றும் வகுப்பு (விருப்பம்)',
    school_ph: 'எ.கா. 9 B வகுப்பு, அரசு மேல்நிலைப் பள்ளி, மதுரை',
    cert_hint: 'குறிப்பு: தொலைபேசியில் வைத்துக்கொள்ள அச்சு சாளரத்தில் PDF ஆகச் சேமியுங்கள்.',
    cert_title: 'சாதனைச் சான்றிதழ்',
    cert_certify: 'இச்சான்றிதழ் பெறுபவர்',
    cert_body: 'AI அடிப்படை வினாடி வினாவில் {total}-க்கு {score} மதிப்பெண்கள் ({pct}%) பெற்றுள்ளார்.',
    cert_topics: 'தலைப்புகள்: {list}',
    cert_date: 'தேதி: {d}',
    cert_sign: 'ஆசிரியர் கையொப்பம்',
    badge_star: 'AI நட்சத்திரம்',
    badge_explorer: 'AI ஆய்வாளர்',
    badge_learner: 'AI கற்பவர்',
    badge_starter: 'AI தொடக்கநிலையாளர்',
    print_cert: 'சான்றிதழ் அச்சிடு',
    review: 'உங்கள் விடைகளைச் சரிபாருங்கள்',
    only_wrong: 'தவறுகளை மட்டும் காட்டு',
    your_answer: 'உங்கள் விடை',
    not_answered: 'விடையளிக்கவில்லை',
    no_mistakes: 'தவறே இல்லை. முழு மதிப்பெண்!',
    reveal: 'விடையைக் காட்டு',
    answer_is: 'விடை: {a}',
    class_finish: 'வினாடி வினாவை முடி',
    restart_timer: 'டைமரை மீண்டும் தொடங்கு',
    plus_point: '{team}-க்கு +1 புள்ளி',
    minus_point: '{team}-க்கு −1 புள்ளி',
    class_tip: 'அணிகள் கலந்துரையாடட்டும், பிறகு "விடையைக் காட்டு" அழுத்துங்கள். சரியாகச் சொன்ன ஒவ்வொரு அணிக்கும் +1 கொடுங்கள்.',
    winner: '{team} வெற்றி!',
    tie: 'சமநிலை! அனைவரும் நன்றாக விளையாடினீர்கள்.',
    final_scores: 'இறுதி மதிப்பெண்கள்',
    play_again: 'மீண்டும் விளையாடு',
    paper_title: 'AI அடிப்படைகள்: வினாத்தாள்',
    n_questions: '{n} கேள்விகள்',
    paper_name: 'பெயர்: ____________________',
    paper_class: 'வகுப்பு: ________',
    paper_date: 'தேதி: ____________',
    paper_marks: 'மதிப்பெண்: ______ / {total}',
    paper_instr: 'ஒவ்வொரு கேள்விக்கும் சரியான விருப்பத்தைத் தேர்ந்தெடுங்கள். ஒவ்வொரு கேள்விக்கும் 1 மதிப்பெண்.',
    answer_key: 'விடைக் குறிப்பு (ஆசிரியருக்கு)',
    made_with: 'AI பாடசாலை செயலிகளால் உருவாக்கப்பட்டது: ஒவ்வொரு பள்ளிக்கும் இலவசம்.'
  },

  te: {
    app_title: 'AI ప్రాథమికాంశాల క్విజ్',
    intro: 'ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ (AI) ప్రాథమికాంశాలను సాధన చేయండి: AI, ML, DL, AI రంగాలు, AI ప్రాజెక్ట్ సైకిల్, యంత్రాలు ఎలా నేర్చుకుంటాయి, మూల్యాంకనం, AI నైతికత, జనరేటివ్ AI. CBSE AI (417) సిలబస్ ఆధారంగా.',
    choose_mode: 'మోడ్ ఎంచుకోండి',
    mode_practice: 'సాధన',
    mode_practice_d: 'ప్రతి ప్రశ్న తర్వాత సరైన జవాబు, వివరణ చూడండి.',
    mode_test: 'టెస్ట్',
    mode_test_d: 'సమయంతో కూడిన టెస్ట్. చివర్లో మార్కులు, సమీక్ష, సర్టిఫికెట్.',
    mode_class: 'ప్రొజెక్టర్ క్విజ్',
    mode_class_d: 'మొత్తం తరగతికి పెద్ద తెరపై క్విజ్, జట్ల స్కోర్లతో.',
    topics: 'అంశాలు',
    all_topics: 'అన్ని అంశాలు',
    topic_basics: 'AI అంటే ఏమిటి?',
    topic_domains: 'AI రంగాలు',
    topic_cycle: 'AI ప్రాజెక్ట్ సైకిల్',
    topic_learning: 'యంత్రాలు ఎలా నేర్చుకుంటాయి',
    topic_eval: 'మూల్యాంకనం',
    topic_ethics: 'AI నైతికత',
    topic_genai: 'జనరేటివ్ AI',
    n_available: '{n} ప్రశ్నలు',
    pick_topic: 'ప్రారంభించడానికి కనీసం ఒక అంశాన్ని ఎంచుకోండి.',
    num_questions: 'ప్రశ్నల సంఖ్య',
    all_n: 'అన్నీ ({n})',
    time_limit: 'సమయ పరిమితి',
    time_per_q: 'ఒక్కో ప్రశ్నకు {s} సెకన్లు',
    no_limit: 'సమయ పరిమితి లేదు',
    total_time: 'మొత్తం సమయం: {t}',
    q_timer: 'ఒక్కో ప్రశ్నకు టైమర్',
    sec_n: '{s} సెకన్లు',
    timer_off: 'టైమర్ లేదు',
    num_teams: 'జట్ల సంఖ్య',
    team_n: 'జట్టు {n}',
    team_name_label: 'జట్టు {n} పేరు',
    shuffle_q: 'ప్రశ్నలను కలపండి',
    shuffle_o: 'ఎంపికలను కలపండి',
    start_quiz: 'క్విజ్ ప్రారంభించండి',
    print_paper: 'ప్రశ్నాపత్రం ప్రింట్ చేయండి',
    resume_title: 'పూర్తికాని క్విజ్ ({mode}): ప్రశ్న {n} / {total}.',
    discard: 'తీసివేయండి',
    help_title: 'ఎలా వాడాలి / తరగతి గదికి ఆలోచనలు',
    help_1: 'సాధనలో ప్రతి ప్రశ్న తర్వాత సరైన జవాబు, చిన్న వివరణ కనిపిస్తాయి. టెస్ట్‌లో జవాబులు చివరి వరకు దాగి ఉంటాయి, టైమర్ నడుస్తుంది. ప్రొజెక్టర్ క్విజ్ స్మార్ట్‌బోర్డ్ లేదా TV పై మొత్తం తరగతి కోసం.',
    help_2: 'ఒకసారి ఒక పాఠాన్ని పునశ్చరణ చేయడానికి అంశం బటన్లను నొక్కండి, ఉదా. యూనిట్ టెస్ట్‌కు ముందు "మూల్యాంకనం" మాత్రమే.',
    help_3: 'తరగతి కార్యకలాపం: తరగతిని 2 నుండి 4 జట్లుగా విభజించండి (పాఠశాల హౌస్‌లు కూడా సరిపోతాయి). ప్రొజెక్టర్‌పై ప్రశ్న చూపించండి, జట్లకు 30 సెకన్లు చర్చించే సమయం ఇవ్వండి, తర్వాత "జవాబు చూపించు" నొక్కి సరిగ్గా చెప్పిన ప్రతి జట్టుకు +1 ఇవ్వండి.',
    help_4: 'కీబోర్డ్: ఎంపిక కోసం 1–4 లేదా A–D, తదుపరి ప్రశ్నకు Enter నొక్కండి. ప్రొజెక్టర్ క్విజ్‌లో జవాబు చూపడానికి R, టైమర్ ఆపడానికి T, పూర్తి తెరకు F నొక్కండి.',
    help_5: 'త్వరిత క్లాస్ టెస్ట్ కోసం జవాబుల కీతో ప్రశ్నాపత్రాన్ని ప్రింట్ చేయండి, లేదా టెస్ట్ తర్వాత ప్రతి విద్యార్థికి సర్టిఫికెట్ ప్రింట్ చేయండి.',
    help_6: 'ఫలితాలు ఈ పరికరంలో మాత్రమే సేవ్ అవుతాయి. సైన్-అప్ లేదు, ప్రకటనలు లేవు, మొదటిసారి తెరిచిన తర్వాత ఇంటర్నెట్ లేకుండా కూడా పనిచేస్తుంది.',
    formula_title: 'త్వరిత సూత్రాల కార్డ్ (మూల్యాంకనం)',
    f_accuracy: 'ఖచ్చితత్వం (Accuracy)',
    f_precision: 'ప్రెసిషన్ (Precision)',
    f_recall: 'రీకాల్ (Recall)',
    f_f1: 'F1 స్కోర్',
    f_note: 'TP = ట్రూ పాజిటివ్, TN = ట్రూ నెగెటివ్, FP = ఫాల్స్ పాజిటివ్, FN = ఫాల్స్ నెగెటివ్, P = ప్రెసిషన్, R = రీకాల్.',
    history_title: 'మీ ఇటీవలి ఫలితాలు',
    history_empty: 'ఇంకా ఫలితాలు లేవు. ఒక సాధన లేదా టెస్ట్ పూర్తి చేయండి, మీ మార్కులు ఇక్కడ కనిపిస్తాయి.',
    best_score: 'ఉత్తమం: {pct}%',
    see_last: 'చివరి ఫలితం చూపించు',
    reset_all: 'అన్నీ రీసెట్ చేయండి',
    reset_done: 'అన్నీ రీసెట్ అయ్యాయి.',
    q_of: 'ప్రశ్న {n} / {total}',
    score_n: 'మార్కులు: {n}/{total}',
    question_list: 'ప్రశ్నలు',
    jump_to: 'ప్రశ్న {n}కి వెళ్లండి',
    read_aloud: 'గట్టిగా చదివి వినిపించు',
    explanation: 'వివరణ',
    correct_was: 'సరైన జవాబు {a}',
    next_q: 'తదుపరి ప్రశ్న',
    see_result: 'నా ఫలితం చూడండి',
    submit_test: 'టెస్ట్ సమర్పించండి',
    quit: 'నిష్క్రమించు',
    confirm_quit: 'ఈ క్విజ్ ఆపాలా? ఈ క్విజ్‌లోని పురోగతి పోతుంది.',
    confirm_submit: 'జవాబు ఇవ్వని ప్రశ్నలు: {n}. అయినా టెస్ట్ సమర్పించాలా?',
    time_left: 'మిగిలిన సమయం',
    times_up: 'సమయం అయిపోయింది!',
    kbd_hint: 'చిట్కా: జవాబుకు 1–4, తదుపరి ప్రశ్నకు Enter నొక్కండి.',
    result_title: 'మీ ఫలితం',
    msg_90: 'అద్భుతం! AI ప్రాథమికాంశాలు మీకు నిజంగా బాగా తెలుసు.',
    msg_75: 'చాలా బాగుంది! తప్పిన కొన్నింటిని మళ్లీ చూసుకోండి.',
    msg_50: 'మంచి ప్రారంభం. వివరణలు చదివి మళ్లీ ప్రయత్నించండి.',
    msg_0: 'సాధన కొనసాగించండి. ప్రతి నిపుణుడూ ఒకప్పుడు కొత్తగా నేర్చుకున్నవారే!',
    n_correct: 'సరైనవి: {n}',
    n_wrong: 'తప్పులు: {n}',
    n_skipped: 'జవాబు ఇవ్వనివి: {n}',
    time_taken: 'సమయం: {t}',
    by_topic: 'అంశాల వారీగా మార్కులు',
    revise_tip: 'ఈ అంశాలను మళ్లీ చదవండి: {list}',
    practice_mistakes: 'నా తప్పులను సాధన చేయి',
    new_quiz: 'కొత్త క్విజ్',
    back_setup: 'ప్రారంభానికి వెనక్కి',
    cert_section: 'మీ సర్టిఫికెట్',
    your_name: 'మీ పేరు',
    name_ph: 'ఉదా. అనన్య రెడ్డి',
    school_label: 'పాఠశాల, తరగతి (ఐచ్ఛికం)',
    school_ph: 'ఉదా. 9వ తరగతి B, ప్రభుత్వ ఉన్నత పాఠశాల, విజయవాడ',
    cert_hint: 'చిట్కా: ఫోన్‌లో ఉంచుకోవడానికి ప్రింట్ విండోలో PDFగా సేవ్ చేయండి.',
    cert_title: 'ప్రశంసా పత్రం',
    cert_certify: 'ఇందుమూలంగా ధృవీకరించడమేమనగా',
    cert_body: 'AI ప్రాథమికాంశాల క్విజ్‌లో {total}కి {score} మార్కులు ({pct}%) సాధించారు.',
    cert_topics: 'అంశాలు: {list}',
    cert_date: 'తేదీ: {d}',
    cert_sign: 'ఉపాధ్యాయుల సంతకం',
    badge_star: 'AI స్టార్',
    badge_explorer: 'AI ఎక్స్‌ప్లోరర్',
    badge_learner: 'AI లెర్నర్',
    badge_starter: 'AI ప్రారంభకులు',
    print_cert: 'సర్టిఫికెట్ ప్రింట్ చేయండి',
    review: 'మీ జవాబులను సమీక్షించండి',
    only_wrong: 'తప్పులు మాత్రమే చూపించు',
    your_answer: 'మీ జవాబు',
    not_answered: 'జవాబు ఇవ్వలేదు',
    no_mistakes: 'ఒక్క తప్పు కూడా లేదు. పూర్తి మార్కులు!',
    reveal: 'జవాబు చూపించు',
    answer_is: 'జవాబు: {a}',
    class_finish: 'క్విజ్ ముగించు',
    restart_timer: 'టైమర్ మళ్లీ ప్రారంభించు',
    plus_point: '{team}కి +1 పాయింట్',
    minus_point: '{team}కి −1 పాయింట్',
    class_tip: 'జట్లను చర్చించనివ్వండి, తర్వాత "జవాబు చూపించు" నొక్కండి. సరిగ్గా చెప్పిన ప్రతి జట్టుకు +1 ఇవ్వండి.',
    winner: '{team} గెలిచింది!',
    tie: 'సమానం! అందరూ బాగా ఆడారు.',
    final_scores: 'తుది స్కోర్లు',
    play_again: 'మళ్లీ ఆడండి',
    paper_title: 'AI ప్రాథమికాంశాలు: ప్రశ్నాపత్రం',
    n_questions: '{n} ప్రశ్నలు',
    paper_name: 'పేరు: ____________________',
    paper_class: 'తరగతి: ________',
    paper_date: 'తేదీ: ____________',
    paper_marks: 'మార్కులు: ______ / {total}',
    paper_instr: 'ప్రతి ప్రశ్నకు సరైన ఎంపికను ఎంచుకోండి. ప్రతి ప్రశ్నకు 1 మార్కు.',
    answer_key: 'జవాబుల కీ (ఉపాధ్యాయుల కోసం)',
    made_with: 'AI పాఠశాల యాప్‌లతో తయారైంది: ప్రతి పాఠశాలకు ఉచితం.'
  },

  kn: {
    app_title: 'AI ಮೂಲಾಂಶಗಳ ಕ್ವಿಜ್',
    intro: 'ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆಯ (AI) ಮೂಲಾಂಶಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ: AI, ML ಮತ್ತು DL, AI ಕ್ಷೇತ್ರಗಳು, AI ಪ್ರಾಜೆಕ್ಟ್ ಸೈಕಲ್, ಯಂತ್ರಗಳು ಹೇಗೆ ಕಲಿಯುತ್ತವೆ, ಮೌಲ್ಯಮಾಪನ, AI ನೈತಿಕತೆ ಮತ್ತು ಜನರೇಟಿವ್ AI. CBSE AI (417) ಪಠ್ಯಕ್ರಮ ಆಧಾರಿತ.',
    choose_mode: 'ಮೋಡ್ ಆಯ್ಕೆಮಾಡಿ',
    mode_practice: 'ಅಭ್ಯಾಸ',
    mode_practice_d: 'ಪ್ರತಿ ಪ್ರಶ್ನೆಯ ನಂತರ ಸರಿಯಾದ ಉತ್ತರ ಮತ್ತು ವಿವರಣೆ ನೋಡಿ.',
    mode_test: 'ಪರೀಕ್ಷೆ',
    mode_test_d: 'ಸಮಯದ ಪರೀಕ್ಷೆ. ಕೊನೆಯಲ್ಲಿ ಅಂಕ, ಪರಿಶೀಲನೆ ಮತ್ತು ಪ್ರಮಾಣಪತ್ರ.',
    mode_class: 'ಪ್ರೊಜೆಕ್ಟರ್ ಕ್ವಿಜ್',
    mode_class_d: 'ಇಡೀ ತರಗತಿಗೆ ದೊಡ್ಡ ಪರದೆಯ ಮೇಲೆ ಕ್ವಿಜ್, ತಂಡದ ಅಂಕಗಳೊಂದಿಗೆ.',
    topics: 'ವಿಷಯಗಳು',
    all_topics: 'ಎಲ್ಲಾ ವಿಷಯಗಳು',
    topic_basics: 'AI ಎಂದರೇನು?',
    topic_domains: 'AI ಕ್ಷೇತ್ರಗಳು',
    topic_cycle: 'AI ಪ್ರಾಜೆಕ್ಟ್ ಸೈಕಲ್',
    topic_learning: 'ಯಂತ್ರಗಳು ಹೇಗೆ ಕಲಿಯುತ್ತವೆ',
    topic_eval: 'ಮೌಲ್ಯಮಾಪನ',
    topic_ethics: 'AI ನೈತಿಕತೆ',
    topic_genai: 'ಜನರೇಟಿವ್ AI',
    n_available: '{n} ಪ್ರಶ್ನೆಗಳು',
    pick_topic: 'ಪ್ರಾರಂಭಿಸಲು ಕನಿಷ್ಠ ಒಂದು ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ.',
    num_questions: 'ಪ್ರಶ್ನೆಗಳ ಸಂಖ್ಯೆ',
    all_n: 'ಎಲ್ಲಾ ({n})',
    time_limit: 'ಸಮಯ ಮಿತಿ',
    time_per_q: 'ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ {s} ಸೆಕೆಂಡ್',
    no_limit: 'ಸಮಯ ಮಿತಿ ಇಲ್ಲ',
    total_time: 'ಒಟ್ಟು ಸಮಯ: {t}',
    q_timer: 'ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ ಟೈಮರ್',
    sec_n: '{s} ಸೆಕೆಂಡ್',
    timer_off: 'ಟೈಮರ್ ಇಲ್ಲ',
    num_teams: 'ತಂಡಗಳ ಸಂಖ್ಯೆ',
    team_n: 'ತಂಡ {n}',
    team_name_label: 'ತಂಡ {n} ಹೆಸರು',
    shuffle_q: 'ಪ್ರಶ್ನೆಗಳನ್ನು ಬೆರೆಸಿ',
    shuffle_o: 'ಆಯ್ಕೆಗಳನ್ನು ಬೆರೆಸಿ',
    start_quiz: 'ಕ್ವಿಜ್ ಪ್ರಾರಂಭಿಸಿ',
    print_paper: 'ಪ್ರಶ್ನೆಪತ್ರಿಕೆ ಮುದ್ರಿಸಿ',
    resume_title: 'ಅಪೂರ್ಣ ಕ್ವಿಜ್ ({mode}): ಪ್ರಶ್ನೆ {n} / {total}.',
    discard: 'ತೆಗೆದುಹಾಕಿ',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ / ತರಗತಿಗೆ ಐಡಿಯಾಗಳು',
    help_1: 'ಅಭ್ಯಾಸದಲ್ಲಿ ಪ್ರತಿ ಪ್ರಶ್ನೆಯ ನಂತರ ಸರಿಯಾದ ಉತ್ತರ ಮತ್ತು ಚಿಕ್ಕ ವಿವರಣೆ ಕಾಣುತ್ತದೆ. ಪರೀಕ್ಷೆಯಲ್ಲಿ ಉತ್ತರಗಳು ಕೊನೆಯವರೆಗೆ ಮರೆಯಾಗಿರುತ್ತವೆ ಮತ್ತು ಟೈಮರ್ ಓಡುತ್ತದೆ. ಪ್ರೊಜೆಕ್ಟರ್ ಕ್ವಿಜ್ ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್ ಅಥವಾ TV ಮೇಲೆ ಇಡೀ ತರಗತಿಗೆ.',
    help_2: 'ಒಮ್ಮೆಗೆ ಒಂದು ಅಧ್ಯಾಯ ಪುನರಾವರ್ತಿಸಲು ವಿಷಯದ ಬಟನ್‌ಗಳನ್ನು ಒತ್ತಿ, ಉದಾ. ಘಟಕ ಪರೀಕ್ಷೆಗೆ ಮುನ್ನ "ಮೌಲ್ಯಮಾಪನ" ಮಾತ್ರ.',
    help_3: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ತರಗತಿಯನ್ನು 2 ರಿಂದ 4 ತಂಡಗಳಾಗಿ ವಿಂಗಡಿಸಿ (ಶಾಲೆಯ ಹೌಸ್‌ಗಳೂ ಆಗುತ್ತವೆ). ಪ್ರೊಜೆಕ್ಟರ್‌ನಲ್ಲಿ ಪ್ರಶ್ನೆ ತೋರಿಸಿ, ತಂಡಗಳಿಗೆ 30 ಸೆಕೆಂಡ್ ಚರ್ಚಿಸಲು ಬಿಡಿ, ನಂತರ "ಉತ್ತರ ತೋರಿಸಿ" ಒತ್ತಿ ಸರಿಯಾಗಿ ಹೇಳಿದ ಪ್ರತಿ ತಂಡಕ್ಕೆ +1 ಕೊಡಿ.',
    help_4: 'ಕೀಬೋರ್ಡ್: ಆಯ್ಕೆಗೆ 1–4 ಅಥವಾ A–D, ಮುಂದಿನ ಪ್ರಶ್ನೆಗೆ Enter ಒತ್ತಿ. ಪ್ರೊಜೆಕ್ಟರ್ ಕ್ವಿಜ್‌ನಲ್ಲಿ ಉತ್ತರ ತೋರಿಸಲು R, ಟೈಮರ್ ನಿಲ್ಲಿಸಲು T, ಪೂರ್ಣ ಪರದೆಗೆ F ಒತ್ತಿ.',
    help_5: 'ತ್ವರಿತ ತರಗತಿ ಪರೀಕ್ಷೆಗಾಗಿ ಉತ್ತರ ಸೂಚಿಯೊಂದಿಗೆ ಪ್ರಶ್ನೆಪತ್ರಿಕೆ ಮುದ್ರಿಸಿ, ಅಥವಾ ಪರೀಕ್ಷೆಯ ನಂತರ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಗೆ ಪ್ರಮಾಣಪತ್ರ ಮುದ್ರಿಸಿ.',
    help_6: 'ಫಲಿತಾಂಶಗಳು ಈ ಸಾಧನದಲ್ಲಿ ಮಾತ್ರ ಉಳಿಯುತ್ತವೆ. ಸೈನ್-ಅಪ್ ಇಲ್ಲ, ಜಾಹೀರಾತು ಇಲ್ಲ, ಮೊದಲ ಬಾರಿ ತೆರೆದ ನಂತರ ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
    formula_title: 'ತ್ವರಿತ ಸೂತ್ರ ಕಾರ್ಡ್ (ಮೌಲ್ಯಮಾಪನ)',
    f_accuracy: 'ನಿಖರತೆ (Accuracy)',
    f_precision: 'ಪ್ರಿಸಿಷನ್ (Precision)',
    f_recall: 'ರಿಕಾಲ್ (Recall)',
    f_f1: 'F1 ಸ್ಕೋರ್',
    f_note: 'TP = ಟ್ರೂ ಪಾಸಿಟಿವ್, TN = ಟ್ರೂ ನೆಗೆಟಿವ್, FP = ಫಾಲ್ಸ್ ಪಾಸಿಟಿವ್, FN = ಫಾಲ್ಸ್ ನೆಗೆಟಿವ್, P = ಪ್ರಿಸಿಷನ್, R = ರಿಕಾಲ್.',
    history_title: 'ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಫಲಿತಾಂಶಗಳು',
    history_empty: 'ಇನ್ನೂ ಫಲಿತಾಂಶಗಳಿಲ್ಲ. ಒಂದು ಅಭ್ಯಾಸ ಅಥವಾ ಪರೀಕ್ಷೆ ಮುಗಿಸಿ, ನಿಮ್ಮ ಅಂಕಗಳು ಇಲ್ಲಿ ಕಾಣುತ್ತವೆ.',
    best_score: 'ಅತ್ಯುತ್ತಮ: {pct}%',
    see_last: 'ಕೊನೆಯ ಫಲಿತಾಂಶ ತೋರಿಸಿ',
    reset_all: 'ಎಲ್ಲವನ್ನೂ ಮರುಹೊಂದಿಸಿ',
    reset_done: 'ಎಲ್ಲವನ್ನೂ ಮರುಹೊಂದಿಸಲಾಗಿದೆ.',
    q_of: 'ಪ್ರಶ್ನೆ {n} / {total}',
    score_n: 'ಅಂಕ: {n}/{total}',
    question_list: 'ಪ್ರಶ್ನೆಗಳು',
    jump_to: 'ಪ್ರಶ್ನೆ {n}ಕ್ಕೆ ಹೋಗಿ',
    read_aloud: 'ಗಟ್ಟಿಯಾಗಿ ಓದಿ',
    explanation: 'ವಿವರಣೆ',
    correct_was: 'ಸರಿಯಾದ ಉತ್ತರ {a}',
    next_q: 'ಮುಂದಿನ ಪ್ರಶ್ನೆ',
    see_result: 'ನನ್ನ ಫಲಿತಾಂಶ ನೋಡಿ',
    submit_test: 'ಪರೀಕ್ಷೆ ಸಲ್ಲಿಸಿ',
    quit: 'ನಿರ್ಗಮಿಸಿ',
    confirm_quit: 'ಈ ಕ್ವಿಜ್ ನಿಲ್ಲಿಸಬೇಕೆ? ಈ ಕ್ವಿಜ್‌ನ ಪ್ರಗತಿ ಅಳಿಸಿಹೋಗುತ್ತದೆ.',
    confirm_submit: 'ಉತ್ತರಿಸದ ಪ್ರಶ್ನೆಗಳು: {n}. ಆದರೂ ಪರೀಕ್ಷೆ ಸಲ್ಲಿಸಬೇಕೆ?',
    time_left: 'ಉಳಿದ ಸಮಯ',
    times_up: 'ಸಮಯ ಮುಗಿಯಿತು!',
    kbd_hint: 'ಸಲಹೆ: ಉತ್ತರಕ್ಕೆ 1–4, ಮುಂದಿನ ಪ್ರಶ್ನೆಗೆ Enter ಒತ್ತಿ.',
    result_title: 'ನಿಮ್ಮ ಫಲಿತಾಂಶ',
    msg_90: 'ಅದ್ಭುತ! AI ಮೂಲಾಂಶಗಳು ನಿಮಗೆ ಚೆನ್ನಾಗಿ ತಿಳಿದಿವೆ.',
    msg_75: 'ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ! ತಪ್ಪಿದ ಕೆಲವನ್ನು ಮತ್ತೆ ನೋಡಿ.',
    msg_50: 'ಒಳ್ಳೆಯ ಆರಂಭ. ವಿವರಣೆಗಳನ್ನು ಓದಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    msg_0: 'ಅಭ್ಯಾಸ ಮುಂದುವರಿಸಿ. ಪ್ರತಿಯೊಬ್ಬ ಪರಿಣತರೂ ಒಮ್ಮೆ ಹೊಸಬರೇ ಆಗಿದ್ದರು!',
    n_correct: 'ಸರಿ: {n}',
    n_wrong: 'ತಪ್ಪು: {n}',
    n_skipped: 'ಉತ್ತರಿಸಿಲ್ಲ: {n}',
    time_taken: 'ಸಮಯ: {t}',
    by_topic: 'ವಿಷಯವಾರು ಅಂಕಗಳು',
    revise_tip: 'ಈ ವಿಷಯಗಳನ್ನು ಮತ್ತೆ ಓದಿ: {list}',
    practice_mistakes: 'ನನ್ನ ತಪ್ಪುಗಳ ಅಭ್ಯಾಸ',
    new_quiz: 'ಹೊಸ ಕ್ವಿಜ್',
    back_setup: 'ಆರಂಭಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    cert_section: 'ನಿಮ್ಮ ಪ್ರಮಾಣಪತ್ರ',
    your_name: 'ನಿಮ್ಮ ಹೆಸರು',
    name_ph: 'ಉದಾ. ಅನನ್ಯಾ ಗೌಡ',
    school_label: 'ಶಾಲೆ ಮತ್ತು ತರಗತಿ (ಐಚ್ಛಿಕ)',
    school_ph: 'ಉದಾ. 9ನೇ ತರಗತಿ B, ಸರ್ಕಾರಿ ಪ್ರೌಢಶಾಲೆ, ಮೈಸೂರು',
    cert_hint: 'ಸಲಹೆ: ಫೋನ್‌ನಲ್ಲಿ ಇಟ್ಟುಕೊಳ್ಳಲು ಮುದ್ರಣ ವಿಂಡೋದಲ್ಲಿ PDF ಆಗಿ ಉಳಿಸಿ.',
    cert_title: 'ಸಾಧನೆಯ ಪ್ರಮಾಣಪತ್ರ',
    cert_certify: 'ಈ ಪ್ರಮಾಣಪತ್ರವನ್ನು',
    cert_body: 'ಅವರಿಗೆ AI ಮೂಲಾಂಶಗಳ ಕ್ವಿಜ್‌ನಲ್ಲಿ {total}ಕ್ಕೆ {score} ಅಂಕ ({pct}%) ಗಳಿಸಿದ್ದಕ್ಕಾಗಿ ನೀಡಲಾಗಿದೆ.',
    cert_topics: 'ವಿಷಯಗಳು: {list}',
    cert_date: 'ದಿನಾಂಕ: {d}',
    cert_sign: 'ಶಿಕ್ಷಕರ ಸಹಿ',
    badge_star: 'AI ಸ್ಟಾರ್',
    badge_explorer: 'AI ಅನ್ವೇಷಕ',
    badge_learner: 'AI ಕಲಿಕಾರ್ಥಿ',
    badge_starter: 'AI ಆರಂಭಿಕ',
    print_cert: 'ಪ್ರಮಾಣಪತ್ರ ಮುದ್ರಿಸಿ',
    review: 'ನಿಮ್ಮ ಉತ್ತರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    only_wrong: 'ತಪ್ಪುಗಳನ್ನು ಮಾತ್ರ ತೋರಿಸಿ',
    your_answer: 'ನಿಮ್ಮ ಉತ್ತರ',
    not_answered: 'ಉತ್ತರಿಸಿಲ್ಲ',
    no_mistakes: 'ಒಂದೂ ತಪ್ಪಿಲ್ಲ. ಪೂರ್ಣ ಅಂಕಗಳು!',
    reveal: 'ಉತ್ತರ ತೋರಿಸಿ',
    answer_is: 'ಉತ್ತರ: {a}',
    class_finish: 'ಕ್ವಿಜ್ ಮುಗಿಸಿ',
    restart_timer: 'ಟೈಮರ್ ಮರುಪ್ರಾರಂಭಿಸಿ',
    plus_point: '{team}ಗೆ +1 ಅಂಕ',
    minus_point: '{team}ಗೆ −1 ಅಂಕ',
    class_tip: 'ತಂಡಗಳು ಚರ್ಚಿಸಲಿ, ನಂತರ "ಉತ್ತರ ತೋರಿಸಿ" ಒತ್ತಿ. ಸರಿಯಾಗಿ ಹೇಳಿದ ಪ್ರತಿ ತಂಡಕ್ಕೆ +1 ಕೊಡಿ.',
    winner: '{team} ಗೆದ್ದಿತು!',
    tie: 'ಸಮಬಲ! ಎಲ್ಲರೂ ಚೆನ್ನಾಗಿ ಆಡಿದಿರಿ.',
    final_scores: 'ಅಂತಿಮ ಅಂಕಗಳು',
    play_again: 'ಮತ್ತೆ ಆಡಿ',
    paper_title: 'AI ಮೂಲಾಂಶಗಳು: ಪ್ರಶ್ನೆಪತ್ರಿಕೆ',
    n_questions: '{n} ಪ್ರಶ್ನೆಗಳು',
    paper_name: 'ಹೆಸರು: ____________________',
    paper_class: 'ತರಗತಿ: ________',
    paper_date: 'ದಿನಾಂಕ: ____________',
    paper_marks: 'ಅಂಕ: ______ / {total}',
    paper_instr: 'ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ ಸರಿಯಾದ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ. ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ 1 ಅಂಕ.',
    answer_key: 'ಉತ್ತರ ಸೂಚಿ (ಶಿಕ್ಷಕರಿಗೆ)',
    made_with: 'AI ಪಾಠಶಾಲೆ ಆ್ಯಪ್‌ಗಳಿಂದ ತಯಾರಿಸಲಾಗಿದೆ: ಪ್ರತಿ ಶಾಲೆಗೂ ಉಚಿತ.'
  },

  ml: {
    app_title: 'AI അടിസ്ഥാന ക്വിസ്',
    intro: 'നിർമ്മിതബുദ്ധിയുടെ (AI) അടിസ്ഥാനങ്ങൾ പരിശീലിക്കൂ: AI, ML, DL, AI മേഖലകൾ, AI പ്രോജക്ട് സൈക്കിൾ, യന്ത്രങ്ങൾ എങ്ങനെ പഠിക്കുന്നു, മൂല്യനിർണയം, AI ധാർമ്മികത, ജനറേറ്റീവ് AI. CBSE AI (417) സിലബസ് അടിസ്ഥാനമാക്കി.',
    choose_mode: 'മോഡ് തിരഞ്ഞെടുക്കുക',
    mode_practice: 'പരിശീലനം',
    mode_practice_d: 'ഓരോ ചോദ്യത്തിനും ശേഷം ശരിയുത്തരവും വിശദീകരണവും കാണുക.',
    mode_test: 'ടെസ്റ്റ്',
    mode_test_d: 'സമയബന്ധിത ടെസ്റ്റ്. അവസാനം മാർക്ക്, പുനഃപരിശോധന, സർട്ടിഫിക്കറ്റ്.',
    mode_class: 'പ്രൊജക്ടർ ക്വിസ്',
    mode_class_d: 'മുഴുവൻ ക്ലാസിനും വലിയ സ്ക്രീനിൽ ക്വിസ്, ടീം സ്കോറുകളോടെ.',
    topics: 'വിഷയങ്ങൾ',
    all_topics: 'എല്ലാ വിഷയങ്ങളും',
    topic_basics: 'AI എന്താണ്?',
    topic_domains: 'AI മേഖലകൾ',
    topic_cycle: 'AI പ്രോജക്ട് സൈക്കിൾ',
    topic_learning: 'യന്ത്രങ്ങൾ എങ്ങനെ പഠിക്കുന്നു',
    topic_eval: 'മൂല്യനിർണയം',
    topic_ethics: 'AI ധാർമ്മികത',
    topic_genai: 'ജനറേറ്റീവ് AI',
    n_available: '{n} ചോദ്യങ്ങൾ',
    pick_topic: 'തുടങ്ങാൻ കുറഞ്ഞത് ഒരു വിഷയമെങ്കിലും തിരഞ്ഞെടുക്കുക.',
    num_questions: 'ചോദ്യങ്ങളുടെ എണ്ണം',
    all_n: 'എല്ലാം ({n})',
    time_limit: 'സമയപരിധി',
    time_per_q: 'ഓരോ ചോദ്യത്തിനും {s} സെക്കൻഡ്',
    no_limit: 'സമയപരിധി ഇല്ല',
    total_time: 'ആകെ സമയം: {t}',
    q_timer: 'ഓരോ ചോദ്യത്തിനും ടൈമർ',
    sec_n: '{s} സെക്കൻഡ്',
    timer_off: 'ടൈമർ ഇല്ല',
    num_teams: 'ടീമുകളുടെ എണ്ണം',
    team_n: 'ടീം {n}',
    team_name_label: 'ടീം {n}-ന്റെ പേര്',
    shuffle_q: 'ചോദ്യങ്ങൾ കലർത്തുക',
    shuffle_o: 'ഓപ്ഷനുകൾ കലർത്തുക',
    start_quiz: 'ക്വിസ് തുടങ്ങുക',
    print_paper: 'ചോദ്യപേപ്പർ പ്രിന്റ് ചെയ്യുക',
    resume_title: 'പൂർത്തിയാകാത്ത ക്വിസ് ({mode}): ചോദ്യം {n} / {total}.',
    discard: 'ഒഴിവാക്കുക',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ക്ലാസ്മുറിക്കുള്ള ആശയങ്ങൾ',
    help_1: 'പരിശീലനത്തിൽ ഓരോ ചോദ്യത്തിനും ശേഷം ശരിയുത്തരവും ചെറിയ വിശദീകരണവും കാണാം. ടെസ്റ്റിൽ ഉത്തരങ്ങൾ അവസാനം വരെ മറഞ്ഞിരിക്കും, ടൈമറും ഓടും. പ്രൊജക്ടർ ക്വിസ് സ്മാർട്ട്ബോർഡിലോ TV-യിലോ മുഴുവൻ ക്ലാസിനുമുള്ളതാണ്.',
    help_2: 'ഒരു സമയം ഒരു അധ്യായം റിവൈസ് ചെയ്യാൻ വിഷയ ബട്ടണുകൾ അമർത്തുക, ഉദാ. യൂണിറ്റ് ടെസ്റ്റിന് മുമ്പ് "മൂല്യനിർണയം" മാത്രം.',
    help_3: 'ക്ലാസ് പ്രവർത്തനം: ക്ലാസിനെ 2 മുതൽ 4 വരെ ടീമുകളാക്കുക (സ്കൂൾ ഹൗസുകളും മതി). പ്രൊജക്ടറിൽ ചോദ്യം കാണിക്കുക, ടീമുകൾക്ക് 30 സെക്കൻഡ് ചർച്ച ചെയ്യാൻ നൽകുക, പിന്നെ "ഉത്തരം കാണിക്കുക" അമർത്തി ശരിയായി പറഞ്ഞ ഓരോ ടീമിനും +1 നൽകുക.',
    help_4: 'കീബോർഡ്: ഓപ്ഷൻ തിരഞ്ഞെടുക്കാൻ 1–4 അല്ലെങ്കിൽ A–D, അടുത്ത ചോദ്യത്തിന് Enter. പ്രൊജക്ടർ ക്വിസിൽ ഉത്തരം കാണിക്കാൻ R, ടൈമർ നിർത്താൻ T, ഫുൾ സ്ക്രീനിന് F അമർത്തുക.',
    help_5: 'പെട്ടെന്നുള്ള ക്ലാസ് ടെസ്റ്റിന് ഉത്തരസൂചികയോടെ ചോദ്യപേപ്പർ പ്രിന്റ് ചെയ്യുക, അല്ലെങ്കിൽ ടെസ്റ്റിന് ശേഷം ഓരോ വിദ്യാർത്ഥിക്കും സർട്ടിഫിക്കറ്റ് പ്രിന്റ് ചെയ്യുക.',
    help_6: 'ഫലങ്ങൾ ഈ ഉപകരണത്തിൽ മാത്രമേ സേവ് ആകൂ. സൈൻ-അപ്പ് ഇല്ല, പരസ്യങ്ങളില്ല, ആദ്യ തവണയ്ക്ക് ശേഷം ഇന്റർനെറ്റ് ഇല്ലാതെയും പ്രവർത്തിക്കും.',
    formula_title: 'പെട്ടെന്നുള്ള ഫോർമുല കാർഡ് (മൂല്യനിർണയം)',
    f_accuracy: 'കൃത്യത (Accuracy)',
    f_precision: 'പ്രിസിഷൻ (Precision)',
    f_recall: 'റീകോൾ (Recall)',
    f_f1: 'F1 സ്കോർ',
    f_note: 'TP = ട്രൂ പോസിറ്റീവ്, TN = ട്രൂ നെഗറ്റീവ്, FP = ഫോൾസ് പോസിറ്റീവ്, FN = ഫോൾസ് നെഗറ്റീവ്, P = പ്രിസിഷൻ, R = റീകോൾ.',
    history_title: 'നിങ്ങളുടെ സമീപകാല ഫലങ്ങൾ',
    history_empty: 'ഇതുവരെ ഫലങ്ങളില്ല. ഒരു പരിശീലനമോ ടെസ്റ്റോ പൂർത്തിയാക്കൂ, നിങ്ങളുടെ മാർക്ക് ഇവിടെ കാണാം.',
    best_score: 'മികച്ചത്: {pct}%',
    see_last: 'അവസാന ഫലം കാണിക്കുക',
    reset_all: 'എല്ലാം റീസെറ്റ് ചെയ്യുക',
    reset_done: 'എല്ലാം റീസെറ്റ് ചെയ്തു.',
    q_of: 'ചോദ്യം {n} / {total}',
    score_n: 'മാർക്ക്: {n}/{total}',
    question_list: 'ചോദ്യങ്ങൾ',
    jump_to: 'ചോദ്യം {n}-ലേക്ക് പോകുക',
    read_aloud: 'ഉറക്കെ വായിക്കുക',
    explanation: 'വിശദീകരണം',
    correct_was: 'ശരിയുത്തരം {a}',
    next_q: 'അടുത്ത ചോദ്യം',
    see_result: 'എന്റെ ഫലം കാണുക',
    submit_test: 'ടെസ്റ്റ് സമർപ്പിക്കുക',
    quit: 'പുറത്തുകടക്കുക',
    confirm_quit: 'ഈ ക്വിസ് നിർത്തണോ? ഇതിലെ പുരോഗതി നഷ്ടമാകും.',
    confirm_submit: 'ഉത്തരം നൽകാത്ത ചോദ്യങ്ങൾ: {n}. എന്നാലും ടെസ്റ്റ് സമർപ്പിക്കണോ?',
    time_left: 'ബാക്കി സമയം',
    times_up: 'സമയം കഴിഞ്ഞു!',
    kbd_hint: 'സൂചന: ഉത്തരത്തിന് 1–4, അടുത്ത ചോദ്യത്തിന് Enter അമർത്തുക.',
    result_title: 'നിങ്ങളുടെ ഫലം',
    msg_90: 'ഗംഭീരം! AI അടിസ്ഥാനങ്ങൾ നിങ്ങൾക്ക് നന്നായി അറിയാം.',
    msg_75: 'വളരെ നല്ലത്! തെറ്റിയ കുറച്ചെണ്ണം വീണ്ടും നോക്കൂ.',
    msg_50: 'നല്ല തുടക്കം. വിശദീകരണങ്ങൾ വായിച്ച് വീണ്ടും ശ്രമിക്കൂ.',
    msg_0: 'പരിശീലനം തുടരൂ. ഓരോ വിദഗ്ധരും ഒരിക്കൽ തുടക്കക്കാരായിരുന്നു!',
    n_correct: 'ശരി: {n}',
    n_wrong: 'തെറ്റ്: {n}',
    n_skipped: 'ഉത്തരം നൽകിയില്ല: {n}',
    time_taken: 'സമയം: {t}',
    by_topic: 'വിഷയം തിരിച്ചുള്ള മാർക്ക്',
    revise_tip: 'ഈ വിഷയങ്ങൾ വീണ്ടും പഠിക്കൂ: {list}',
    practice_mistakes: 'എന്റെ തെറ്റുകൾ പരിശീലിക്കുക',
    new_quiz: 'പുതിയ ക്വിസ്',
    back_setup: 'തുടക്കത്തിലേക്ക് മടങ്ങുക',
    cert_section: 'നിങ്ങളുടെ സർട്ടിഫിക്കറ്റ്',
    your_name: 'നിങ്ങളുടെ പേര്',
    name_ph: 'ഉദാ. അനന്യ നായർ',
    school_label: 'സ്കൂളും ക്ലാസും (നിർബന്ധമില്ല)',
    school_ph: 'ഉദാ. 9 B ക്ലാസ്, ഗവ. ഹയർ സെക്കൻഡറി സ്കൂൾ, കോഴിക്കോട്',
    cert_hint: 'സൂചന: ഫോണിൽ സൂക്ഷിക്കാൻ പ്രിന്റ് വിൻഡോയിൽ PDF ആയി സേവ് ചെയ്യുക.',
    cert_title: 'നേട്ട സർട്ടിഫിക്കറ്റ്',
    cert_certify: 'ഈ സർട്ടിഫിക്കറ്റ് സമ്മാനിക്കുന്നത്',
    cert_body: 'AI അടിസ്ഥാന ക്വിസിൽ {total}-ൽ {score} മാർക്ക് ({pct}%) നേടിയതിന്.',
    cert_topics: 'വിഷയങ്ങൾ: {list}',
    cert_date: 'തീയതി: {d}',
    cert_sign: 'അധ്യാപകരുടെ ഒപ്പ്',
    badge_star: 'AI സ്റ്റാർ',
    badge_explorer: 'AI എക്സ്പ്ലോറർ',
    badge_learner: 'AI ലേണർ',
    badge_starter: 'AI തുടക്കക്കാർ',
    print_cert: 'സർട്ടിഫിക്കറ്റ് പ്രിന്റ് ചെയ്യുക',
    review: 'നിങ്ങളുടെ ഉത്തരങ്ങൾ പരിശോധിക്കുക',
    only_wrong: 'തെറ്റുകൾ മാത്രം കാണിക്കുക',
    your_answer: 'നിങ്ങളുടെ ഉത്തരം',
    not_answered: 'ഉത്തരം നൽകിയില്ല',
    no_mistakes: 'ഒരു തെറ്റുമില്ല. മുഴുവൻ മാർക്ക്!',
    reveal: 'ഉത്തരം കാണിക്കുക',
    answer_is: 'ഉത്തരം: {a}',
    class_finish: 'ക്വിസ് അവസാനിപ്പിക്കുക',
    restart_timer: 'ടൈമർ വീണ്ടും തുടങ്ങുക',
    plus_point: '{team}-ന് +1 പോയിന്റ്',
    minus_point: '{team}-ന് −1 പോയിന്റ്',
    class_tip: 'ടീമുകൾ ചർച്ച ചെയ്യട്ടെ, പിന്നെ "ഉത്തരം കാണിക്കുക" അമർത്തുക. ശരിയായി പറഞ്ഞ ഓരോ ടീമിനും +1 നൽകുക.',
    winner: '{team} ജയിച്ചു!',
    tie: 'സമനില! എല്ലാവരും നന്നായി കളിച്ചു.',
    final_scores: 'അന്തിമ സ്കോറുകൾ',
    play_again: 'വീണ്ടും കളിക്കുക',
    paper_title: 'AI അടിസ്ഥാനങ്ങൾ: ചോദ്യപേപ്പർ',
    n_questions: '{n} ചോദ്യങ്ങൾ',
    paper_name: 'പേര്: ____________________',
    paper_class: 'ക്ലാസ്: ________',
    paper_date: 'തീയതി: ____________',
    paper_marks: 'മാർക്ക്: ______ / {total}',
    paper_instr: 'ഓരോ ചോദ്യത്തിനും ശരിയായ ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക. ഓരോ ചോദ്യത്തിനും 1 മാർക്ക്.',
    answer_key: 'ഉത്തരസൂചിക (അധ്യാപകർക്ക്)',
    made_with: 'AI പാഠശാല ആപ്പുകൾ ഉപയോഗിച്ച് നിർമ്മിച്ചത്: എല്ലാ സ്കൂളുകൾക്കും സൗജന്യം.'
  },

  ur: {
    app_title: 'AI بنیادی معلومات کوئز',
    intro: 'مصنوعی ذہانت (AI) کی بنیادی باتوں کی مشق کریں: AI، ML اور DL، AI کے شعبے، AI پروجیکٹ سائیکل، مشینیں کیسے سیکھتی ہیں، جانچ، AI اخلاقیات اور جنریٹو AI۔ CBSE AI (417) نصاب پر مبنی۔',
    choose_mode: 'موڈ منتخب کریں',
    mode_practice: 'مشق',
    mode_practice_d: 'ہر سوال کے بعد صحیح جواب اور وضاحت دیکھیں۔',
    mode_test: 'ٹیسٹ',
    mode_test_d: 'وقت والا ٹیسٹ۔ آخر میں نمبر، جوابات کی جانچ اور سرٹیفکیٹ۔',
    mode_class: 'پروجیکٹر کوئز',
    mode_class_d: 'پوری کلاس کے لیے بڑی اسکرین پر کوئز، ٹیم اسکور کے ساتھ۔',
    topics: 'موضوعات',
    all_topics: 'تمام موضوعات',
    topic_basics: 'AI کیا ہے؟',
    topic_domains: 'AI کے شعبے',
    topic_cycle: 'AI پروجیکٹ سائیکل',
    topic_learning: 'مشینیں کیسے سیکھتی ہیں',
    topic_eval: 'جانچ',
    topic_ethics: 'AI اخلاقیات',
    topic_genai: 'جنریٹو AI',
    n_available: '{n} سوالات',
    pick_topic: 'شروع کرنے کے لیے کم از کم ایک موضوع منتخب کریں۔',
    num_questions: 'سوالات کی تعداد',
    all_n: 'تمام ({n})',
    time_limit: 'وقت کی حد',
    time_per_q: 'ہر سوال کے لیے {s} سیکنڈ',
    no_limit: 'وقت کی کوئی حد نہیں',
    total_time: 'کل وقت: {t}',
    q_timer: 'ہر سوال کا ٹائمر',
    sec_n: '{s} سیکنڈ',
    timer_off: 'ٹائمر نہیں',
    num_teams: 'ٹیموں کی تعداد',
    team_n: 'ٹیم {n}',
    team_name_label: 'ٹیم {n} کا نام',
    shuffle_q: 'سوالات ملائیں',
    shuffle_o: 'اختیارات ملائیں',
    start_quiz: 'کوئز شروع کریں',
    print_paper: 'سوالنامہ پرنٹ کریں',
    resume_title: 'ادھورا کوئز ({mode}): سوال {n} / {total}۔',
    discard: 'ختم کریں',
    help_title: 'کیسے استعمال کریں / کلاس کے لیے مشورے',
    help_1: 'مشق میں ہر سوال کے بعد صحیح جواب اور مختصر وضاحت دکھائی دیتی ہے۔ ٹیسٹ میں جوابات آخر تک چھپے رہتے ہیں اور ٹائمر چلتا ہے۔ پروجیکٹر کوئز اسمارٹ بورڈ یا TV پر پوری کلاس کے لیے ہے۔',
    help_2: 'ایک وقت میں ایک باب دہرانے کے لیے موضوع کے بٹن دبائیں، مثلاً یونٹ ٹیسٹ سے پہلے صرف "جانچ"۔',
    help_3: 'کلاس سرگرمی: کلاس کو 2 سے 4 ٹیموں میں بانٹیں (اسکول کے ہاؤس بھی چلیں گے)۔ پروجیکٹر پر سوال دکھائیں، ٹیموں کو 30 سیکنڈ بات کرنے دیں، پھر "جواب دکھائیں" دبائیں اور صحیح جواب دینے والی ہر ٹیم کو +1 دیں۔',
    help_4: 'کی بورڈ: جواب چننے کے لیے 1–4 یا A–D دبائیں اور اگلے سوال کے لیے Enter۔ پروجیکٹر کوئز میں جواب دکھانے کے لیے R، ٹائمر روکنے کے لیے T اور پوری اسکرین کے لیے F دبائیں۔',
    help_5: 'فوری کلاس ٹیسٹ کے لیے جوابی کلید کے ساتھ سوالنامہ پرنٹ کریں، یا ٹیسٹ کے بعد ہر طالب علم کا سرٹیفکیٹ پرنٹ کریں۔',
    help_6: 'نتائج صرف اسی ڈیوائس پر محفوظ ہوتے ہیں۔ کوئی سائن اپ نہیں، کوئی اشتہار نہیں، اور پہلی بار کھولنے کے بعد انٹرنیٹ کے بغیر بھی چلتا ہے۔',
    formula_title: 'فوری فارمولا کارڈ (جانچ)',
    f_accuracy: 'درستی (Accuracy)',
    f_precision: 'پریسیژن (Precision)',
    f_recall: 'ریکال (Recall)',
    f_f1: 'F1 اسکور',
    f_note: 'TP = ٹرو پازیٹو، TN = ٹرو نیگیٹو، FP = فالس پازیٹو، FN = فالس نیگیٹو، P = پریسیژن، R = ریکال۔',
    history_title: 'آپ کے حالیہ نتائج',
    history_empty: 'ابھی کوئی نتیجہ نہیں۔ مشق یا ٹیسٹ مکمل کریں، آپ کے نمبر یہاں دکھائی دیں گے۔',
    best_score: 'بہترین: {pct}%',
    see_last: 'پچھلا نتیجہ دیکھیں',
    reset_all: 'سب کچھ ری سیٹ کریں',
    reset_done: 'سب کچھ ری سیٹ ہو گیا۔',
    q_of: 'سوال {n} / {total}',
    score_n: 'نمبر: {n}/{total}',
    question_list: 'سوالات',
    jump_to: 'سوال {n} پر جائیں',
    read_aloud: 'پڑھ کر سنائیں',
    explanation: 'وضاحت',
    correct_was: 'صحیح جواب ہے {a}',
    next_q: 'اگلا سوال',
    see_result: 'میرا نتیجہ دیکھیں',
    submit_test: 'ٹیسٹ جمع کریں',
    quit: 'چھوڑیں',
    confirm_quit: 'یہ کوئز بند کریں؟ اس کوئز کی پیش رفت مٹ جائے گی۔',
    confirm_submit: 'بغیر جواب والے سوالات: {n}۔ پھر بھی ٹیسٹ جمع کریں؟',
    time_left: 'باقی وقت',
    times_up: 'وقت ختم!',
    kbd_hint: 'مشورہ: جواب کے لیے 1–4 دبائیں اور اگلے سوال کے لیے Enter۔',
    result_title: 'آپ کا نتیجہ',
    msg_90: 'شاندار! آپ کو AI کی بنیادی باتیں واقعی اچھی طرح آتی ہیں۔',
    msg_75: 'بہت خوب! جو تھوڑے رہ گئے، انہیں دہرا لیں۔',
    msg_50: 'اچھی شروعات۔ وضاحتیں پڑھیں اور پھر کوشش کریں۔',
    msg_0: 'مشق جاری رکھیں۔ ہر ماہر کبھی نیا سیکھنے والا تھا!',
    n_correct: 'صحیح: {n}',
    n_wrong: 'غلط: {n}',
    n_skipped: 'جواب نہیں دیا: {n}',
    time_taken: 'وقت: {t}',
    by_topic: 'موضوع کے لحاظ سے نمبر',
    revise_tip: 'یہ موضوعات دوبارہ پڑھیں: {list}',
    practice_mistakes: 'میری غلطیوں کی مشق',
    new_quiz: 'نیا کوئز',
    back_setup: 'شروع پر واپس',
    cert_section: 'آپ کا سرٹیفکیٹ',
    your_name: 'آپ کا نام',
    name_ph: 'مثلاً: عائشہ خان',
    school_label: 'اسکول اور جماعت (اختیاری)',
    school_ph: 'مثلاً: جماعت 9 B، سرکاری ہائی اسکول، لکھنؤ',
    cert_hint: 'مشورہ: فون میں رکھنے کے لیے پرنٹ ونڈو میں PDF کے طور پر محفوظ کریں۔',
    cert_title: 'سندِ کامیابی',
    cert_certify: 'تصدیق کی جاتی ہے کہ',
    cert_body: 'نے AI بنیادی معلومات کوئز میں {total} میں سے {score} نمبر ({pct}%) حاصل کیے۔',
    cert_topics: 'موضوعات: {list}',
    cert_date: 'تاریخ: {d}',
    cert_sign: 'استاد کے دستخط',
    badge_star: 'AI اسٹار',
    badge_explorer: 'AI ایکسپلورر',
    badge_learner: 'AI لرنر',
    badge_starter: 'AI نوآموز',
    print_cert: 'سرٹیفکیٹ پرنٹ کریں',
    review: 'اپنے جوابات جانچیں',
    only_wrong: 'صرف غلطیاں دکھائیں',
    your_answer: 'آپ کا جواب',
    not_answered: 'جواب نہیں دیا',
    no_mistakes: 'کوئی غلطی نہیں۔ پورے نمبر!',
    reveal: 'جواب دکھائیں',
    answer_is: 'جواب: {a}',
    class_finish: 'کوئز ختم کریں',
    restart_timer: 'ٹائمر دوبارہ شروع کریں',
    plus_point: '{team} کو +1 نمبر',
    minus_point: '{team} کا −1 نمبر',
    class_tip: 'ٹیموں کو بات کرنے دیں، پھر "جواب دکھائیں" دبائیں۔ صحیح جواب دینے والی ہر ٹیم کو +1 دیں۔',
    winner: '{team} جیت گئی!',
    tie: 'مقابلہ برابر! سب نے اچھا کھیلا۔',
    final_scores: 'آخری اسکور',
    play_again: 'دوبارہ کھیلیں',
    paper_title: 'AI بنیادی معلومات: سوالنامہ',
    n_questions: '{n} سوالات',
    paper_name: 'نام: ____________________',
    paper_class: 'جماعت: ________',
    paper_date: 'تاریخ: ____________',
    paper_marks: 'نمبر: ______ / {total}',
    paper_instr: 'ہر سوال کا صحیح جواب منتخب کریں۔ ہر سوال 1 نمبر کا ہے۔',
    answer_key: 'جوابی کلید (استاد کے لیے)',
    made_with: 'AI پاٹھ شالہ ایپس سے بنایا گیا: ہر اسکول کے لیے مفت۔'
  }
};
