/* Festival Poster Maker: UI strings. Keys are identical in all 12 languages.
   Greetings, occasion names, offer ideas and the example shop are in content.js. */
window.APP_STRINGS = {
  en: {
    app_title: 'Festival Greeting & Offer Poster',
    intro: 'Make festival wishes and shop offer posters with your name, logo, photo and UPI QR code, ready for WhatsApp, Instagram or print.',
    privacy: 'Your photos, logo and details never leave this device. Nothing is uploaded.',
    occ_title: 'Occasion', occ_search_ph: 'Search: Diwali, Eid, sale…', occ_fest: 'Festivals, by date', occ_biz: 'For your shop, any day',
    when_today: 'Today', when_now: 'On now', when_tomorrow: 'Tomorrow', when_in: 'In {n} days', when_unknown: 'Date not set', no_match: 'Nothing found. Try another word.',
    dates_btn: 'Fix festival dates', dates_title: 'Festival dates', dates_help: 'Many festivals follow the moon, so the date changes every year. Check your local calendar and correct any date here.', dates_reset: 'Use built-in dates',
    size_title: 'Size', size_story: 'WhatsApp status', size_insta: 'Instagram post', size_square: 'Square post', size_fb: 'Facebook post', size_a4: 'A4 print', size_a5: 'A5 flyer',
    preview_aria: 'Poster preview. Click the greeting, name or offer on the poster to edit it.', making: 'Making the poster…',
    dl_png: 'Download PNG', dl_jpg: 'Download JPG', share_btn: 'Send on WhatsApp',
    share_none: 'This browser cannot send pictures directly, so the poster was downloaded. Send it from your gallery or Downloads.',
    saved_file: 'Saved {name}', shortcut: 'Shortcut: Ctrl + S downloads the PNG.',
    multi_title: 'Make it in 3 languages at once', multi_help: 'Pick up to 3 languages. The greeting changes language; your name, offer and address stay as you typed them.',
    multi_max: 'You can pick up to 3 languages.', multi_make: 'Make {n} posters', multi_dl: 'Download all', multi_share: 'Share all',
    text_title: 'Greeting', poster_lang: 'Poster language', greet_label: 'Big greeting', wish_label: 'Wish line (optional)', text_reset: 'Use the suggested text',
    biz_title: 'Your business', example_note: 'This is an example shop. Type your own details or clear them.', example_clear: 'Clear example',
    name_label: 'Business name or your name', offer_label: 'Offer line (optional)', offer_ideas: 'Ideas:', phone_label: 'Phone / WhatsApp number', address_label: 'Address', handle_label: 'Instagram, Facebook or website',
    logo_label: 'Logo', logo_add: 'Add logo', photo_label: 'Photo of you, your shop or a product', photo_add: 'Add photo', img_remove: 'Remove', logo_plate: 'White circle behind the logo',
    photo_shape: 'Photo shape', shape_circle: 'Circle', shape_arch: 'Arch', shape_round: 'Rounded', photo_zoom: 'Zoom', photo_hint: 'Drag the photo on the poster to move it.',
    img_bad: 'This file could not be opened. Please choose a JPG or PNG picture.', img_unsaved: 'The picture is too big to remember after you close this page, but you can use it now.',
    low_res: 'This picture is small ({w} × {h} pixels) for this size, so it may look blurry. Use a bigger picture if you can.',
    qr_title: 'QR code', qr_none: 'No QR', qr_upi: 'UPI payment', qr_wa: 'WhatsApp chat', qr_link: 'Website link', upi_label: 'UPI ID',
    upi_bad: 'This does not look like a UPI ID. It looks like name@bank, for example sharmasweets@oksbi.', upi_ok: 'Customers can scan this with any UPI app to pay {name}.',
    wa_need: 'First type your 10-digit mobile number in "Phone / WhatsApp number" above.', wa_ok: 'Customers can scan this to start a WhatsApp chat with {phone}.',
    link_label: 'Link', link_bad: 'Type a full link that starts with https://', qr_long: 'This is too long for a QR code. Use a shorter link.',
    qr_check: 'Always scan the QR code once with your own phone before you share or print the poster.',
    style_title: 'Style', colours: 'Colours', colour_n: 'Colour set {n}', font_label: 'Font', font_simple: 'Simple', font_festive: 'Festive',
    font_note: 'The festive font downloads once from the internet. Without internet, the simple font is used.', font_loading: 'Downloading the festive font…',
    font_failed: 'Could not download the festive font, so the simple font is used.', shuffle: 'Try another look',
    help_title: 'How to use / Ideas for your business',
    tip1: 'Pick the occasion, then type your shop name, offer and phone number. The poster changes as you type.',
    tip2: 'Choose "WhatsApp status" for status updates, "Instagram post" for your feed, and "A4 print" or "A5 flyer" for the shop counter and pamphlets.',
    tip3: 'Add a UPI QR code so customers can pay straight from the poster. Scan it once with your own phone before you share it.',
    tip4: 'Make the same poster in 3 languages at once: Hindi for one group, Tamil or Bengali for another, and English for Instagram.',
    tip5: 'Post festival wishes 1–2 days before the festival and the offer poster on the morning of the festival.',
    tip6: 'Your photos, logo and details stay on this phone or computer. Nothing is uploaded, so it also works without internet.'
  },
  hi: {
    app_title: 'त्योहार शुभकामना और ऑफ़र पोस्टर',
    intro: 'अपने नाम, लोगो, फ़ोटो और UPI QR के साथ त्योहार की शुभकामना और दुकान के ऑफ़र वाले पोस्टर बनाइए, WhatsApp, Instagram या प्रिंट के लिए तैयार।',
    privacy: 'आपकी फ़ोटो, लोगो और जानकारी इसी डिवाइस में रहती हैं। कुछ भी अपलोड नहीं होता।',
    occ_title: 'मौका चुनें', occ_search_ph: 'खोजें: दिवाली, ईद, सेल…', occ_fest: 'त्योहार, तारीख के हिसाब से', occ_biz: 'दुकान के लिए, किसी भी दिन',
    when_today: 'आज', when_tomorrow: 'कल', when_now: 'अभी चल रहा है', when_in: '{n} दिन बाद', when_unknown: 'तारीख तय नहीं', no_match: 'कुछ नहीं मिला। कोई दूसरा शब्द लिखकर देखें।',
    dates_btn: 'त्योहार की तारीख ठीक करें', dates_title: 'त्योहारों की तारीखें', dates_help: 'कई त्योहार चाँद के हिसाब से होते हैं, इसलिए हर साल तारीख बदलती है। अपना कैलेंडर देखकर कोई भी तारीख यहाँ ठीक करें।', dates_reset: 'पहले से दी गई तारीखें लगाएँ',
    size_title: 'साइज़', size_story: 'WhatsApp स्टेटस', size_insta: 'Instagram पोस्ट', size_square: 'चौकोर पोस्ट', size_fb: 'Facebook पोस्ट', size_a4: 'A4 प्रिंट', size_a5: 'A5 पर्चा',
    preview_aria: 'पोस्टर का प्रीव्यू। बदलने के लिए पोस्टर पर शुभकामना, नाम या ऑफ़र पर क्लिक करें।', making: 'पोस्टर बन रहा है…',
    dl_png: 'PNG डाउनलोड करें', dl_jpg: 'JPG डाउनलोड करें', share_btn: 'WhatsApp पर भेजें',
    share_none: 'यह ब्राउज़र सीधे तस्वीर नहीं भेज सकता, इसलिए पोस्टर डाउनलोड हो गया है। इसे गैलरी या Downloads से भेजें।',
    saved_file: 'सेव हुआ: {name}', shortcut: 'शॉर्टकट: Ctrl + S दबाने पर PNG डाउनलोड होता है।',
    multi_title: 'एक साथ 3 भाषाओं में बनाएँ', multi_help: '3 भाषाएँ तक चुनें। शुभकामना की भाषा बदलेगी; आपका नाम, ऑफ़र और पता वैसे ही रहेंगे जैसे आपने लिखे।',
    multi_max: 'आप 3 भाषाएँ तक चुन सकते हैं।', multi_make: '{n} पोस्टर बनाएँ', multi_dl: 'सब डाउनलोड करें', multi_share: 'सब शेयर करें',
    text_title: 'शुभकामना', poster_lang: 'पोस्टर की भाषा', greet_label: 'बड़ी शुभकामना', wish_label: 'शुभकामना संदेश (चाहें तो)', text_reset: 'सुझाया गया टेक्स्ट लगाएँ',
    biz_title: 'आपका कारोबार', example_note: 'यह एक उदाहरण दुकान है। अपनी जानकारी लिखें या इसे हटा दें।', example_clear: 'उदाहरण हटाएँ',
    name_label: 'दुकान/कंपनी का नाम या आपका नाम', offer_label: 'ऑफ़र (चाहें तो)', offer_ideas: 'सुझाव:', phone_label: 'फ़ोन / WhatsApp नंबर', address_label: 'पता', handle_label: 'Instagram, Facebook या वेबसाइट',
    logo_label: 'लोगो', logo_add: 'लोगो जोड़ें', photo_label: 'आपकी, दुकान की या सामान की फ़ोटो', photo_add: 'फ़ोटो जोड़ें', img_remove: 'हटाएँ', logo_plate: 'लोगो के पीछे सफ़ेद गोला',
    photo_shape: 'फ़ोटो का आकार', shape_circle: 'गोल', shape_arch: 'मेहराब', shape_round: 'गोल कोने', photo_zoom: 'ज़ूम', photo_hint: 'फ़ोटो को खिसकाने के लिए पोस्टर पर उसे खींचें।',
    img_bad: 'यह फ़ाइल नहीं खुल सकी। कृपया JPG या PNG तस्वीर चुनें।', img_unsaved: 'तस्वीर बहुत बड़ी है, इसलिए पेज बंद करने के बाद याद नहीं रहेगी। अभी आप इसे इस्तेमाल कर सकते हैं।',
    low_res: 'इस साइज़ के लिए यह तस्वीर छोटी है ({w} × {h} पिक्सेल), इसलिए धुँधली दिख सकती है। हो सके तो बड़ी तस्वीर लगाएँ।',
    qr_title: 'QR कोड', qr_none: 'QR नहीं', qr_upi: 'UPI पेमेंट', qr_wa: 'WhatsApp चैट', qr_link: 'वेबसाइट लिंक', upi_label: 'UPI ID',
    upi_bad: 'यह UPI ID जैसी नहीं लगती। यह name@bank जैसी होती है, जैसे sharmasweets@oksbi।', upi_ok: 'ग्राहक किसी भी UPI ऐप से इसे स्कैन करके {name} को पेमेंट कर सकते हैं।',
    wa_need: 'पहले ऊपर "फ़ोन / WhatsApp नंबर" में अपना 10 अंकों का मोबाइल नंबर लिखें।', wa_ok: 'ग्राहक इसे स्कैन करके {phone} से WhatsApp पर बात शुरू कर सकते हैं।',
    link_label: 'लिंक', link_bad: 'https:// से शुरू होने वाला पूरा लिंक लिखें।', qr_long: 'QR कोड के लिए यह बहुत लंबा है। छोटा लिंक इस्तेमाल करें।',
    qr_check: 'पोस्टर शेयर या प्रिंट करने से पहले QR कोड को अपने फ़ोन से एक बार स्कैन करके ज़रूर देखें।',
    style_title: 'डिज़ाइन', colours: 'रंग', colour_n: 'रंग सेट {n}', font_label: 'फ़ॉन्ट', font_simple: 'सादा', font_festive: 'त्योहारी',
    font_note: 'त्योहारी फ़ॉन्ट एक बार इंटरनेट से डाउनलोड होता है। इंटरनेट न हो तो सादा फ़ॉन्ट लगता है।', font_loading: 'त्योहारी फ़ॉन्ट डाउनलोड हो रहा है…',
    font_failed: 'त्योहारी फ़ॉन्ट डाउनलोड नहीं हो सका, इसलिए सादा फ़ॉन्ट लगाया गया है।', shuffle: 'दूसरा डिज़ाइन देखें',
    help_title: 'कैसे इस्तेमाल करें / कारोबार के लिए सुझाव',
    tip1: 'मौका चुनें, फिर अपनी दुकान का नाम, ऑफ़र और फ़ोन नंबर लिखें। लिखते ही पोस्टर बदल जाता है।',
    tip2: 'स्टेटस के लिए "WhatsApp स्टेटस", फ़ीड के लिए "Instagram पोस्ट", और काउंटर या पर्चों के लिए "A4 प्रिंट" या "A5 पर्चा" चुनें।',
    tip3: 'UPI QR जोड़ें ताकि ग्राहक पोस्टर से ही पेमेंट कर सकें। शेयर करने से पहले उसे अपने फ़ोन से एक बार स्कैन करें।',
    tip4: 'एक ही पोस्टर एक साथ 3 भाषाओं में बनाएँ: एक ग्रुप के लिए हिंदी, दूसरे के लिए तमिल या बांग्ला, और Instagram के लिए अंग्रेज़ी।',
    tip5: 'त्योहार की शुभकामना 1–2 दिन पहले और ऑफ़र वाला पोस्टर त्योहार की सुबह पोस्ट करें।',
    tip6: 'आपकी फ़ोटो, लोगो और जानकारी इसी फ़ोन या कंप्यूटर में रहती हैं। कुछ भी अपलोड नहीं होता, इसलिए यह बिना इंटरनेट भी चलता है।'
  },
  bn: {
    app_title: 'উৎসবের শুভেচ্ছা ও অফার পোস্টার',
    intro: 'নিজের নাম, লোগো, ছবি আর UPI QR দিয়ে উৎসবের শুভেচ্ছা ও দোকানের অফারের পোস্টার বানান, WhatsApp, Instagram বা প্রিন্টের জন্য তৈরি।',
    privacy: 'আপনার ছবি, লোগো আর তথ্য এই ডিভাইসেই থাকে। কিছুই আপলোড হয় না।',
    occ_title: 'উপলক্ষ বেছে নিন', occ_search_ph: 'খুঁজুন: দীপাবলি, ঈদ, সেল…', occ_fest: 'উৎসব, তারিখ অনুযায়ী', occ_biz: 'দোকানের জন্য, যেকোনো দিন',
    when_today: 'আজ', when_now: 'এখন চলছে', when_tomorrow: 'আগামীকাল', when_in: '{n} দিন পরে', when_unknown: 'তারিখ ঠিক করা নেই', no_match: 'কিছু পাওয়া যায়নি। অন্য শব্দ লিখে দেখুন।',
    dates_btn: 'উৎসবের তারিখ ঠিক করুন', dates_title: 'উৎসবের তারিখ', dates_help: 'অনেক উৎসব চাঁদের হিসেবে হয়, তাই প্রতি বছর তারিখ বদলায়। নিজের পঞ্জিকা দেখে যেকোনো তারিখ এখানে ঠিক করুন।', dates_reset: 'আগে থেকে দেওয়া তারিখ ব্যবহার করুন',
    size_title: 'মাপ', size_story: 'WhatsApp স্ট্যাটাস', size_insta: 'Instagram পোস্ট', size_square: 'বর্গাকার পোস্ট', size_fb: 'Facebook পোস্ট', size_a4: 'A4 প্রিন্ট', size_a5: 'A5 লিফলেট',
    preview_aria: 'পোস্টারের প্রিভিউ। বদলাতে পোস্টারে শুভেচ্ছা, নাম বা অফারে ক্লিক করুন।', making: 'পোস্টার তৈরি হচ্ছে…',
    dl_png: 'PNG ডাউনলোড করুন', dl_jpg: 'JPG ডাউনলোড করুন', share_btn: 'WhatsApp-এ পাঠান',
    share_none: 'এই ব্রাউজার সরাসরি ছবি পাঠাতে পারে না, তাই পোস্টার ডাউনলোড হয়েছে। গ্যালারি বা Downloads থেকে পাঠান।',
    saved_file: 'সেভ হয়েছে: {name}', shortcut: 'শর্টকাট: Ctrl + S চাপলে PNG ডাউনলোড হয়।',
    multi_title: 'একসাথে 3টি ভাষায় বানান', multi_help: '3টি পর্যন্ত ভাষা বেছে নিন। শুভেচ্ছার ভাষা বদলাবে; আপনার নাম, অফার আর ঠিকানা যেমন লিখেছেন তেমনই থাকবে।',
    multi_max: '3টি পর্যন্ত ভাষা বেছে নিতে পারেন।', multi_make: '{n}টি পোস্টার বানান', multi_dl: 'সব ডাউনলোড করুন', multi_share: 'সব শেয়ার করুন',
    text_title: 'শুভেচ্ছা', poster_lang: 'পোস্টারের ভাষা', greet_label: 'বড় শুভেচ্ছা', wish_label: 'শুভেচ্ছা বার্তা (ইচ্ছে হলে)', text_reset: 'প্রস্তাবিত লেখা বসান',
    biz_title: 'আপনার ব্যবসা', example_note: 'এটি একটি উদাহরণ দোকান। নিজের তথ্য লিখুন বা মুছে দিন।', example_clear: 'উদাহরণ মুছুন',
    name_label: 'দোকান বা প্রতিষ্ঠানের নাম, বা আপনার নাম', offer_label: 'অফার (ইচ্ছে হলে)', offer_ideas: 'আইডিয়া:', phone_label: 'ফোন / WhatsApp নম্বর', address_label: 'ঠিকানা', handle_label: 'Instagram, Facebook বা ওয়েবসাইট',
    logo_label: 'লোগো', logo_add: 'লোগো যোগ করুন', photo_label: 'আপনার, দোকানের বা জিনিসের ছবি', photo_add: 'ছবি যোগ করুন', img_remove: 'সরান', logo_plate: 'লোগোর পেছনে সাদা গোল',
    photo_shape: 'ছবির আকার', shape_circle: 'গোল', shape_arch: 'খিলান', shape_round: 'গোল কোণ', photo_zoom: 'জুম', photo_hint: 'ছবি সরাতে পোস্টারের উপর টেনে নিন।',
    img_bad: 'এই ফাইলটি খোলা গেল না। দয়া করে JPG বা PNG ছবি বেছে নিন।', img_unsaved: 'ছবিটি অনেক বড়, তাই পেজ বন্ধ করলে মনে থাকবে না। এখন ব্যবহার করতে পারেন।',
    low_res: 'এই মাপের জন্য ছবিটি ছোট ({w} × {h} পিক্সেল), তাই ঝাপসা দেখাতে পারে। পারলে বড় ছবি দিন।',
    qr_title: 'QR কোড', qr_none: 'QR নেই', qr_upi: 'UPI পেমেন্ট', qr_wa: 'WhatsApp চ্যাট', qr_link: 'ওয়েবসাইট লিংক', upi_label: 'UPI ID',
    upi_bad: 'এটি UPI ID-র মতো লাগছে না। এটি name@bank ধরনের হয়, যেমন sharmasweets@oksbi।', upi_ok: 'গ্রাহকরা যেকোনো UPI অ্যাপে এটি স্ক্যান করে {name}-কে পেমেন্ট করতে পারবেন।',
    wa_need: 'আগে উপরে "ফোন / WhatsApp নম্বর"-এ আপনার 10 সংখ্যার মোবাইল নম্বর লিখুন।', wa_ok: 'গ্রাহকরা এটি স্ক্যান করে {phone}-এর সঙ্গে WhatsApp-এ কথা শুরু করতে পারবেন।',
    link_label: 'লিংক', link_bad: 'https:// দিয়ে শুরু হওয়া পুরো লিংক লিখুন।', qr_long: 'QR কোডের জন্য এটি খুব লম্বা। ছোট লিংক ব্যবহার করুন।',
    qr_check: 'পোস্টার শেয়ার বা প্রিন্ট করার আগে নিজের ফোনে QR কোড একবার স্ক্যান করে দেখে নিন।',
    style_title: 'ডিজাইন', colours: 'রং', colour_n: 'রঙের সেট {n}', font_label: 'ফন্ট', font_simple: 'সাধারণ', font_festive: 'উৎসবের',
    font_note: 'উৎসবের ফন্ট একবার ইন্টারনেট থেকে ডাউনলোড হয়। ইন্টারনেট না থাকলে সাধারণ ফন্ট ব্যবহার হয়।', font_loading: 'উৎসবের ফন্ট ডাউনলোড হচ্ছে…',
    font_failed: 'উৎসবের ফন্ট ডাউনলোড করা গেল না, তাই সাধারণ ফন্ট ব্যবহার হচ্ছে।', shuffle: 'অন্য ডিজাইন দেখুন',
    help_title: 'কীভাবে ব্যবহার করবেন / ব্যবসার জন্য আইডিয়া',
    tip1: 'উপলক্ষ বেছে নিন, তারপর দোকানের নাম, অফার আর ফোন নম্বর লিখুন। লেখার সঙ্গে সঙ্গে পোস্টার বদলে যায়।',
    tip2: 'স্ট্যাটাসের জন্য "WhatsApp স্ট্যাটাস", ফিডের জন্য "Instagram পোস্ট", আর কাউন্টার বা লিফলেটের জন্য "A4 প্রিন্ট" বা "A5 লিফলেট" বেছে নিন।',
    tip3: 'UPI QR যোগ করুন, যাতে গ্রাহক পোস্টার থেকেই পেমেন্ট করতে পারেন। শেয়ার করার আগে নিজের ফোনে একবার স্ক্যান করুন।',
    tip4: 'একই পোস্টার একসাথে 3টি ভাষায় বানান: এক গ্রুপের জন্য বাংলা, আরেকটির জন্য হিন্দি, আর Instagram-এর জন্য ইংরেজি।',
    tip5: 'উৎসবের শুভেচ্ছা 1–2 দিন আগে, আর অফারের পোস্টার উৎসবের দিন সকালে পোস্ট করুন।',
    tip6: 'আপনার ছবি, লোগো আর তথ্য এই ফোন বা কম্পিউটারেই থাকে। কিছুই আপলোড হয় না, তাই ইন্টারনেট ছাড়াও চলে।'
  },
  mr: {
    app_title: 'सणाच्या शुभेच्छा आणि ऑफर पोस्टर',
    intro: 'तुमचे नाव, लोगो, फोटो आणि UPI QR सह सणाच्या शुभेच्छा आणि दुकानाच्या ऑफरचे पोस्टर बनवा, WhatsApp, Instagram किंवा प्रिंटसाठी तयार.',
    privacy: 'तुमचे फोटो, लोगो आणि माहिती याच डिव्हाइसवर राहते. काहीही अपलोड होत नाही.',
    occ_title: 'प्रसंग निवडा', occ_search_ph: 'शोधा: दिवाळी, ईद, सेल…', occ_fest: 'सण, तारखेनुसार', occ_biz: 'दुकानासाठी, कोणत्याही दिवशी',
    when_today: 'आज', when_tomorrow: 'उद्या', when_now: 'सध्या सुरू आहे', when_in: '{n} दिवसांनी', when_unknown: 'तारीख ठरलेली नाही', no_match: 'काहीही सापडले नाही. दुसरा शब्द लिहून पाहा.',
    dates_btn: 'सणांच्या तारखा दुरुस्त करा', dates_title: 'सणांच्या तारखा', dates_help: 'अनेक सण चंद्रानुसार येतात, त्यामुळे दरवर्षी तारीख बदलते. तुमचे कॅलेंडर पाहून कोणतीही तारीख इथे दुरुस्त करा.', dates_reset: 'आधी दिलेल्या तारखा वापरा',
    size_title: 'आकार', size_story: 'WhatsApp स्टेटस', size_insta: 'Instagram पोस्ट', size_square: 'चौरस पोस्ट', size_fb: 'Facebook पोस्ट', size_a4: 'A4 प्रिंट', size_a5: 'A5 पत्रक',
    preview_aria: 'पोस्टरचे पूर्वावलोकन. बदलण्यासाठी पोस्टरवरील शुभेच्छा, नाव किंवा ऑफरवर क्लिक करा.', making: 'पोस्टर तयार होत आहे…',
    dl_png: 'PNG डाउनलोड करा', dl_jpg: 'JPG डाउनलोड करा', share_btn: 'WhatsApp वर पाठवा',
    share_none: 'हा ब्राउझर थेट चित्र पाठवू शकत नाही, म्हणून पोस्टर डाउनलोड झाले आहे. गॅलरी किंवा Downloads मधून पाठवा.',
    saved_file: 'सेव्ह झाले: {name}', shortcut: 'शॉर्टकट: Ctrl + S दाबल्यावर PNG डाउनलोड होते.',
    multi_title: 'एकाच वेळी 3 भाषांमध्ये बनवा', multi_help: '3 भाषांपर्यंत निवडा. शुभेच्छांची भाषा बदलेल; तुमचे नाव, ऑफर आणि पत्ता तुम्ही लिहिल्याप्रमाणेच राहतील.',
    multi_max: 'तुम्ही 3 भाषांपर्यंत निवडू शकता.', multi_make: '{n} पोस्टर बनवा', multi_dl: 'सर्व डाउनलोड करा', multi_share: 'सर्व शेअर करा',
    text_title: 'शुभेच्छा', poster_lang: 'पोस्टरची भाषा', greet_label: 'मोठ्या अक्षरातील शुभेच्छा', wish_label: 'शुभेच्छा संदेश (हवे असल्यास)', text_reset: 'सुचवलेला मजकूर वापरा',
    biz_title: 'तुमचा व्यवसाय', example_note: 'हे एक उदाहरण दुकान आहे. तुमची माहिती लिहा किंवा ते काढून टाका.', example_clear: 'उदाहरण काढा',
    name_label: 'दुकान/कंपनीचे नाव किंवा तुमचे नाव', offer_label: 'ऑफर (हवे असल्यास)', offer_ideas: 'कल्पना:', phone_label: 'फोन / WhatsApp नंबर', address_label: 'पत्ता', handle_label: 'Instagram, Facebook किंवा वेबसाइट',
    logo_label: 'लोगो', logo_add: 'लोगो जोडा', photo_label: 'तुमचा, दुकानाचा किंवा वस्तूचा फोटो', photo_add: 'फोटो जोडा', img_remove: 'काढा', logo_plate: 'लोगोमागे पांढरे वर्तुळ',
    photo_shape: 'फोटोचा आकार', shape_circle: 'गोल', shape_arch: 'कमान', shape_round: 'गोल कोपरे', photo_zoom: 'झूम', photo_hint: 'फोटो हलवण्यासाठी तो पोस्टरवर ओढा.',
    img_bad: 'ही फाइल उघडता आली नाही. कृपया JPG किंवा PNG चित्र निवडा.', img_unsaved: 'चित्र खूप मोठे आहे, त्यामुळे पेज बंद केल्यावर लक्षात राहणार नाही. आत्ता तुम्ही ते वापरू शकता.',
    low_res: 'या आकारासाठी हे चित्र लहान आहे ({w} × {h} पिक्सेल), त्यामुळे धूसर दिसू शकते. शक्य असल्यास मोठे चित्र वापरा.',
    qr_title: 'QR कोड', qr_none: 'QR नको', qr_upi: 'UPI पेमेंट', qr_wa: 'WhatsApp चॅट', qr_link: 'वेबसाइट लिंक', upi_label: 'UPI ID',
    upi_bad: 'हा UPI ID सारखा दिसत नाही. तो name@bank असा असतो, उदा. sharmasweets@oksbi.', upi_ok: 'ग्राहक कोणत्याही UPI ॲपने हा स्कॅन करून {name} ला पैसे देऊ शकतात.',
    wa_need: 'आधी वर "फोन / WhatsApp नंबर" मध्ये तुमचा 10 अंकी मोबाइल नंबर लिहा.', wa_ok: 'ग्राहक हा स्कॅन करून {phone} शी WhatsApp वर बोलणे सुरू करू शकतात.',
    link_label: 'लिंक', link_bad: 'https:// ने सुरू होणारी पूर्ण लिंक लिहा.', qr_long: 'QR कोडसाठी हे खूप लांब आहे. लहान लिंक वापरा.',
    qr_check: 'पोस्टर शेअर किंवा प्रिंट करण्याआधी QR कोड तुमच्या फोनने एकदा स्कॅन करून नक्की पाहा.',
    style_title: 'डिझाइन', colours: 'रंग', colour_n: 'रंगसंच {n}', font_label: 'फॉन्ट', font_simple: 'साधा', font_festive: 'सणासुदीचा',
    font_note: 'सणासुदीचा फॉन्ट एकदा इंटरनेटवरून डाउनलोड होतो. इंटरनेट नसेल तर साधा फॉन्ट वापरला जातो.', font_loading: 'सणासुदीचा फॉन्ट डाउनलोड होत आहे…',
    font_failed: 'सणासुदीचा फॉन्ट डाउनलोड झाला नाही, म्हणून साधा फॉन्ट वापरला आहे.', shuffle: 'दुसरे डिझाइन पाहा',
    help_title: 'कसे वापरावे / व्यवसायासाठी कल्पना',
    tip1: 'प्रसंग निवडा, मग तुमच्या दुकानाचे नाव, ऑफर आणि फोन नंबर लिहा. लिहिताच पोस्टर बदलते.',
    tip2: 'स्टेटससाठी "WhatsApp स्टेटस", फीडसाठी "Instagram पोस्ट", आणि काउंटर किंवा पत्रकांसाठी "A4 प्रिंट" किंवा "A5 पत्रक" निवडा.',
    tip3: 'UPI QR जोडा, म्हणजे ग्राहक पोस्टरवरूनच पैसे देऊ शकतील. शेअर करण्याआधी तो तुमच्या फोनने एकदा स्कॅन करा.',
    tip4: 'एकच पोस्टर एकाच वेळी 3 भाषांमध्ये बनवा: एका ग्रुपसाठी मराठी, दुसऱ्यासाठी हिंदी आणि Instagram साठी इंग्रजी.',
    tip5: 'सणाच्या शुभेच्छा 1–2 दिवस आधी आणि ऑफरचे पोस्टर सणाच्या दिवशी सकाळी पोस्ट करा.',
    tip6: 'तुमचे फोटो, लोगो आणि माहिती याच फोन किंवा कॉम्प्युटरवर राहते. काहीही अपलोड होत नाही, त्यामुळे इंटरनेटशिवायही चालते.'
  },
  gu: {
    app_title: 'તહેવારની શુભેચ્છા અને ઑફર પોસ્ટર',
    intro: 'તમારા નામ, લોગો, ફોટો અને UPI QR સાથે તહેવારની શુભેચ્છા અને દુકાનની ઑફરનાં પોસ્ટર બનાવો, WhatsApp, Instagram કે પ્રિન્ટ માટે તૈયાર.',
    privacy: 'તમારા ફોટો, લોગો અને માહિતી આ જ ડિવાઇસમાં રહે છે. કંઈ પણ અપલોડ થતું નથી.',
    occ_title: 'પ્રસંગ પસંદ કરો', occ_search_ph: 'શોધો: દિવાળી, ઈદ, સેલ…', occ_fest: 'તહેવારો, તારીખ પ્રમાણે', occ_biz: 'દુકાન માટે, કોઈ પણ દિવસે',
    when_today: 'આજે', when_now: 'હાલ ચાલુ છે', when_tomorrow: 'આવતીકાલે', when_in: '{n} દિવસ પછી', when_unknown: 'તારીખ નક્કી નથી', no_match: 'કંઈ મળ્યું નહીં. બીજો શબ્દ લખીને જુઓ.',
    dates_btn: 'તહેવારની તારીખો સુધારો', dates_title: 'તહેવારોની તારીખો', dates_help: 'ઘણા તહેવારો ચંદ્ર પ્રમાણે આવે છે, તેથી દર વર્ષે તારીખ બદલાય છે. તમારું પંચાંગ જોઈને કોઈ પણ તારીખ અહીં સુધારો.', dates_reset: 'પહેલેથી આપેલી તારીખો વાપરો',
    size_title: 'માપ', size_story: 'WhatsApp સ્ટેટસ', size_insta: 'Instagram પોસ્ટ', size_square: 'ચોરસ પોસ્ટ', size_fb: 'Facebook પોસ્ટ', size_a4: 'A4 પ્રિન્ટ', size_a5: 'A5 પત્રિકા',
    preview_aria: 'પોસ્ટરનું પ્રિવ્યૂ. બદલવા માટે પોસ્ટર પર શુભેચ્છા, નામ કે ઑફર પર ક્લિક કરો.', making: 'પોસ્ટર બની રહ્યું છે…',
    dl_png: 'PNG ડાઉનલોડ કરો', dl_jpg: 'JPG ડાઉનલોડ કરો', share_btn: 'WhatsApp પર મોકલો',
    share_none: 'આ બ્રાઉઝર સીધું ચિત્ર મોકલી શકતું નથી, તેથી પોસ્ટર ડાઉનલોડ થયું છે. તેને ગૅલેરી કે Downloads માંથી મોકલો.',
    saved_file: 'સેવ થયું: {name}', shortcut: 'શૉર્ટકટ: Ctrl + S દબાવવાથી PNG ડાઉનલોડ થાય છે.',
    multi_title: 'એક સાથે 3 ભાષામાં બનાવો', multi_help: '3 ભાષા સુધી પસંદ કરો. શુભેચ્છાની ભાષા બદલાશે; તમારું નામ, ઑફર અને સરનામું તમે લખ્યું એવું જ રહેશે.',
    multi_max: 'તમે 3 ભાષા સુધી પસંદ કરી શકો છો.', multi_make: '{n} પોસ્ટર બનાવો', multi_dl: 'બધાં ડાઉનલોડ કરો', multi_share: 'બધાં શેર કરો',
    text_title: 'શુભેચ્છા', poster_lang: 'પોસ્ટરની ભાષા', greet_label: 'મોટી શુભેચ્છા', wish_label: 'શુભેચ્છા સંદેશ (ઇચ્છો તો)', text_reset: 'સૂચવેલું લખાણ વાપરો',
    biz_title: 'તમારો વ્યવસાય', example_note: 'આ એક ઉદાહરણ દુકાન છે. તમારી માહિતી લખો અથવા તેને દૂર કરો.', example_clear: 'ઉદાહરણ દૂર કરો',
    name_label: 'દુકાન/કંપનીનું નામ અથવા તમારું નામ', offer_label: 'ઑફર (ઇચ્છો તો)', offer_ideas: 'સૂચનો:', phone_label: 'ફોન / WhatsApp નંબર', address_label: 'સરનામું', handle_label: 'Instagram, Facebook કે વેબસાઇટ',
    logo_label: 'લોગો', logo_add: 'લોગો ઉમેરો', photo_label: 'તમારો, દુકાનનો કે વસ્તુનો ફોટો', photo_add: 'ફોટો ઉમેરો', img_remove: 'દૂર કરો', logo_plate: 'લોગો પાછળ સફેદ વર્તુળ',
    photo_shape: 'ફોટોનો આકાર', shape_circle: 'ગોળ', shape_arch: 'કમાન', shape_round: 'ગોળ ખૂણા', photo_zoom: 'ઝૂમ', photo_hint: 'ફોટો ખસેડવા માટે તેને પોસ્ટર પર ખેંચો.',
    img_bad: 'આ ફાઇલ ખૂલી નહીં. કૃપા કરીને JPG કે PNG ચિત્ર પસંદ કરો.', img_unsaved: 'ચિત્ર બહુ મોટું છે, તેથી પેજ બંધ કર્યા પછી યાદ નહીં રહે. અત્યારે તમે તેને વાપરી શકો છો.',
    low_res: 'આ માપ માટે ચિત્ર નાનું છે ({w} × {h} પિક્સેલ), તેથી ઝાંખું દેખાઈ શકે. શક્ય હોય તો મોટું ચિત્ર વાપરો.',
    qr_title: 'QR કોડ', qr_none: 'QR નહીં', qr_upi: 'UPI પેમેન્ટ', qr_wa: 'WhatsApp ચૅટ', qr_link: 'વેબસાઇટ લિંક', upi_label: 'UPI ID',
    upi_bad: 'આ UPI ID જેવું લાગતું નથી. તે name@bank જેવું હોય છે, જેમ કે sharmasweets@oksbi.', upi_ok: 'ગ્રાહકો કોઈ પણ UPI ઍપથી આ સ્કૅન કરીને {name} ને ચુકવણી કરી શકે છે.',
    wa_need: 'પહેલાં ઉપર "ફોન / WhatsApp નંબર" માં તમારો 10 અંકનો મોબાઇલ નંબર લખો.', wa_ok: 'ગ્રાહકો આ સ્કૅન કરીને {phone} સાથે WhatsApp પર વાત શરૂ કરી શકે છે.',
    link_label: 'લિંક', link_bad: 'https:// થી શરૂ થતી પૂરી લિંક લખો.', qr_long: 'QR કોડ માટે આ બહુ લાંબું છે. ટૂંકી લિંક વાપરો.',
    qr_check: 'પોસ્ટર શેર કે પ્રિન્ટ કરતાં પહેલાં QR કોડ તમારા ફોનથી એક વાર સ્કૅન કરીને જરૂર જુઓ.',
    style_title: 'ડિઝાઇન', colours: 'રંગો', colour_n: 'રંગ સેટ {n}', font_label: 'ફૉન્ટ', font_simple: 'સાદો', font_festive: 'તહેવારી',
    font_note: 'તહેવારી ફૉન્ટ એક વાર ઇન્ટરનેટ પરથી ડાઉનલોડ થાય છે. ઇન્ટરનેટ ન હોય તો સાદો ફૉન્ટ વપરાય છે.', font_loading: 'તહેવારી ફૉન્ટ ડાઉનલોડ થઈ રહ્યો છે…',
    font_failed: 'તહેવારી ફૉન્ટ ડાઉનલોડ ન થયો, તેથી સાદો ફૉન્ટ વપરાયો છે.', shuffle: 'બીજી ડિઝાઇન જુઓ',
    help_title: 'કેવી રીતે વાપરવું / વ્યવસાય માટે સૂચનો',
    tip1: 'પ્રસંગ પસંદ કરો, પછી તમારી દુકાનનું નામ, ઑફર અને ફોન નંબર લખો. લખતાં જ પોસ્ટર બદલાય છે.',
    tip2: 'સ્ટેટસ માટે "WhatsApp સ્ટેટસ", ફીડ માટે "Instagram પોસ્ટ", અને કાઉન્ટર કે પત્રિકા માટે "A4 પ્રિન્ટ" કે "A5 પત્રિકા" પસંદ કરો.',
    tip3: 'UPI QR ઉમેરો જેથી ગ્રાહકો પોસ્ટર પરથી જ ચુકવણી કરી શકે. શેર કરતાં પહેલાં તેને તમારા ફોનથી એક વાર સ્કૅન કરો.',
    tip4: 'એક જ પોસ્ટર એક સાથે 3 ભાષામાં બનાવો: એક ગ્રુપ માટે ગુજરાતી, બીજા માટે હિન્દી અને Instagram માટે અંગ્રેજી.',
    tip5: 'તહેવારની શુભેચ્છા 1–2 દિવસ પહેલાં અને ઑફરનું પોસ્ટર તહેવારની સવારે પોસ્ટ કરો.',
    tip6: 'તમારા ફોટો, લોગો અને માહિતી આ જ ફોન કે કમ્પ્યુટરમાં રહે છે. કંઈ અપલોડ થતું નથી, તેથી ઇન્ટરનેટ વગર પણ ચાલે છે.'
  },
  pa: {
    app_title: 'ਤਿਉਹਾਰ ਵਧਾਈ ਅਤੇ ਆਫ਼ਰ ਪੋਸਟਰ',
    intro: 'ਆਪਣੇ ਨਾਮ, ਲੋਗੋ, ਫ਼ੋਟੋ ਅਤੇ UPI QR ਨਾਲ ਤਿਉਹਾਰ ਦੀਆਂ ਵਧਾਈਆਂ ਅਤੇ ਦੁਕਾਨ ਦੇ ਆਫ਼ਰ ਵਾਲੇ ਪੋਸਟਰ ਬਣਾਓ, WhatsApp, Instagram ਜਾਂ ਪ੍ਰਿੰਟ ਲਈ ਤਿਆਰ।',
    privacy: 'ਤੁਹਾਡੀਆਂ ਫ਼ੋਟੋਆਂ, ਲੋਗੋ ਅਤੇ ਜਾਣਕਾਰੀ ਇਸੇ ਡਿਵਾਈਸ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ। ਕੁਝ ਵੀ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ।',
    occ_title: 'ਮੌਕਾ ਚੁਣੋ', occ_search_ph: 'ਖੋਜੋ: ਦੀਵਾਲੀ, ਈਦ, ਸੇਲ…', occ_fest: 'ਤਿਉਹਾਰ, ਤਾਰੀਖ਼ ਮੁਤਾਬਕ', occ_biz: 'ਦੁਕਾਨ ਲਈ, ਕਿਸੇ ਵੀ ਦਿਨ',
    when_today: 'ਅੱਜ', when_now: 'ਹੁਣ ਚੱਲ ਰਿਹਾ ਹੈ', when_tomorrow: 'ਕੱਲ੍ਹ', when_in: '{n} ਦਿਨਾਂ ਬਾਅਦ', when_unknown: 'ਤਾਰੀਖ਼ ਤੈਅ ਨਹੀਂ', no_match: 'ਕੁਝ ਨਹੀਂ ਮਿਲਿਆ। ਕੋਈ ਹੋਰ ਸ਼ਬਦ ਲਿਖ ਕੇ ਦੇਖੋ।',
    dates_btn: 'ਤਿਉਹਾਰਾਂ ਦੀਆਂ ਤਾਰੀਖ਼ਾਂ ਠੀਕ ਕਰੋ', dates_title: 'ਤਿਉਹਾਰਾਂ ਦੀਆਂ ਤਾਰੀਖ਼ਾਂ', dates_help: 'ਕਈ ਤਿਉਹਾਰ ਚੰਨ ਦੇ ਹਿਸਾਬ ਨਾਲ ਆਉਂਦੇ ਹਨ, ਇਸ ਲਈ ਹਰ ਸਾਲ ਤਾਰੀਖ਼ ਬਦਲਦੀ ਹੈ। ਆਪਣਾ ਕੈਲੰਡਰ ਦੇਖ ਕੇ ਕੋਈ ਵੀ ਤਾਰੀਖ਼ ਇੱਥੇ ਠੀਕ ਕਰੋ।', dates_reset: 'ਪਹਿਲਾਂ ਦਿੱਤੀਆਂ ਤਾਰੀਖ਼ਾਂ ਵਰਤੋ',
    size_title: 'ਸਾਈਜ਼', size_story: 'WhatsApp ਸਟੇਟਸ', size_insta: 'Instagram ਪੋਸਟ', size_square: 'ਚੌਰਸ ਪੋਸਟ', size_fb: 'Facebook ਪੋਸਟ', size_a4: 'A4 ਪ੍ਰਿੰਟ', size_a5: 'A5 ਪਰਚਾ',
    preview_aria: 'ਪੋਸਟਰ ਦਾ ਪ੍ਰੀਵਿਊ। ਬਦਲਣ ਲਈ ਪੋਸਟਰ ਤੇ ਵਧਾਈ, ਨਾਮ ਜਾਂ ਆਫ਼ਰ ਤੇ ਕਲਿੱਕ ਕਰੋ।', making: 'ਪੋਸਟਰ ਬਣ ਰਿਹਾ ਹੈ…',
    dl_png: 'PNG ਡਾਊਨਲੋਡ ਕਰੋ', dl_jpg: 'JPG ਡਾਊਨਲੋਡ ਕਰੋ', share_btn: 'WhatsApp ਤੇ ਭੇਜੋ',
    share_none: 'ਇਹ ਬ੍ਰਾਊਜ਼ਰ ਸਿੱਧੀ ਤਸਵੀਰ ਨਹੀਂ ਭੇਜ ਸਕਦਾ, ਇਸ ਲਈ ਪੋਸਟਰ ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ ਹੈ। ਇਸਨੂੰ ਗੈਲਰੀ ਜਾਂ Downloads ਤੋਂ ਭੇਜੋ।',
    saved_file: 'ਸੇਵ ਹੋਇਆ: {name}', shortcut: 'ਸ਼ਾਰਟਕੱਟ: Ctrl + S ਦਬਾਉਣ ਨਾਲ PNG ਡਾਊਨਲੋਡ ਹੁੰਦਾ ਹੈ।',
    multi_title: 'ਇੱਕੋ ਵਾਰ 3 ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਬਣਾਓ', multi_help: '3 ਭਾਸ਼ਾਵਾਂ ਤੱਕ ਚੁਣੋ। ਵਧਾਈ ਦੀ ਭਾਸ਼ਾ ਬਦਲੇਗੀ; ਤੁਹਾਡਾ ਨਾਮ, ਆਫ਼ਰ ਅਤੇ ਪਤਾ ਉਵੇਂ ਹੀ ਰਹਿਣਗੇ ਜਿਵੇਂ ਤੁਸੀਂ ਲਿਖੇ।',
    multi_max: 'ਤੁਸੀਂ 3 ਭਾਸ਼ਾਵਾਂ ਤੱਕ ਚੁਣ ਸਕਦੇ ਹੋ।', multi_make: '{n} ਪੋਸਟਰ ਬਣਾਓ', multi_dl: 'ਸਾਰੇ ਡਾਊਨਲੋਡ ਕਰੋ', multi_share: 'ਸਾਰੇ ਸਾਂਝੇ ਕਰੋ',
    text_title: 'ਵਧਾਈ', poster_lang: 'ਪੋਸਟਰ ਦੀ ਭਾਸ਼ਾ', greet_label: 'ਵੱਡੀ ਵਧਾਈ', wish_label: 'ਵਧਾਈ ਸੁਨੇਹਾ (ਚਾਹੋ ਤਾਂ)', text_reset: 'ਸੁਝਾਇਆ ਟੈਕਸਟ ਲਗਾਓ',
    biz_title: 'ਤੁਹਾਡਾ ਕਾਰੋਬਾਰ', example_note: 'ਇਹ ਇੱਕ ਉਦਾਹਰਨ ਦੁਕਾਨ ਹੈ। ਆਪਣੀ ਜਾਣਕਾਰੀ ਲਿਖੋ ਜਾਂ ਇਸਨੂੰ ਹਟਾ ਦਿਓ।', example_clear: 'ਉਦਾਹਰਨ ਹਟਾਓ',
    name_label: 'ਦੁਕਾਨ/ਕੰਪਨੀ ਦਾ ਨਾਮ ਜਾਂ ਤੁਹਾਡਾ ਨਾਮ', offer_label: 'ਆਫ਼ਰ (ਚਾਹੋ ਤਾਂ)', offer_ideas: 'ਸੁਝਾਅ:', phone_label: 'ਫ਼ੋਨ / WhatsApp ਨੰਬਰ', address_label: 'ਪਤਾ', handle_label: 'Instagram, Facebook ਜਾਂ ਵੈੱਬਸਾਈਟ',
    logo_label: 'ਲੋਗੋ', logo_add: 'ਲੋਗੋ ਜੋੜੋ', photo_label: 'ਤੁਹਾਡੀ, ਦੁਕਾਨ ਦੀ ਜਾਂ ਸਾਮਾਨ ਦੀ ਫ਼ੋਟੋ', photo_add: 'ਫ਼ੋਟੋ ਜੋੜੋ', img_remove: 'ਹਟਾਓ', logo_plate: 'ਲੋਗੋ ਦੇ ਪਿੱਛੇ ਚਿੱਟਾ ਗੋਲਾ',
    photo_shape: 'ਫ਼ੋਟੋ ਦੀ ਸ਼ਕਲ', shape_circle: 'ਗੋਲ', shape_arch: 'ਮਹਿਰਾਬ', shape_round: 'ਗੋਲ ਕੋਨੇ', photo_zoom: 'ਜ਼ੂਮ', photo_hint: 'ਫ਼ੋਟੋ ਖਿਸਕਾਉਣ ਲਈ ਉਸਨੂੰ ਪੋਸਟਰ ਤੇ ਖਿੱਚੋ।',
    img_bad: 'ਇਹ ਫ਼ਾਈਲ ਨਹੀਂ ਖੁੱਲ੍ਹੀ। ਕਿਰਪਾ ਕਰਕੇ JPG ਜਾਂ PNG ਤਸਵੀਰ ਚੁਣੋ।', img_unsaved: 'ਤਸਵੀਰ ਬਹੁਤ ਵੱਡੀ ਹੈ, ਇਸ ਲਈ ਪੇਜ ਬੰਦ ਕਰਨ ਤੋਂ ਬਾਅਦ ਯਾਦ ਨਹੀਂ ਰਹੇਗੀ। ਹੁਣ ਤੁਸੀਂ ਇਸਨੂੰ ਵਰਤ ਸਕਦੇ ਹੋ।',
    low_res: 'ਇਸ ਸਾਈਜ਼ ਲਈ ਇਹ ਤਸਵੀਰ ਛੋਟੀ ਹੈ ({w} × {h} ਪਿਕਸਲ), ਇਸ ਲਈ ਧੁੰਦਲੀ ਦਿਖ ਸਕਦੀ ਹੈ। ਹੋ ਸਕੇ ਤਾਂ ਵੱਡੀ ਤਸਵੀਰ ਲਗਾਓ।',
    qr_title: 'QR ਕੋਡ', qr_none: 'QR ਨਹੀਂ', qr_upi: 'UPI ਭੁਗਤਾਨ', qr_wa: 'WhatsApp ਚੈਟ', qr_link: 'ਵੈੱਬਸਾਈਟ ਲਿੰਕ', upi_label: 'UPI ID',
    upi_bad: 'ਇਹ UPI ID ਵਰਗੀ ਨਹੀਂ ਲੱਗਦੀ। ਇਹ name@bank ਵਰਗੀ ਹੁੰਦੀ ਹੈ, ਜਿਵੇਂ sharmasweets@oksbi।', upi_ok: 'ਗਾਹਕ ਕਿਸੇ ਵੀ UPI ਐਪ ਨਾਲ ਇਸਨੂੰ ਸਕੈਨ ਕਰਕੇ {name} ਨੂੰ ਭੁਗਤਾਨ ਕਰ ਸਕਦੇ ਹਨ।',
    wa_need: 'ਪਹਿਲਾਂ ਉੱਪਰ "ਫ਼ੋਨ / WhatsApp ਨੰਬਰ" ਵਿੱਚ ਆਪਣਾ 10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਲਿਖੋ।', wa_ok: 'ਗਾਹਕ ਇਸਨੂੰ ਸਕੈਨ ਕਰਕੇ {phone} ਨਾਲ WhatsApp ਤੇ ਗੱਲ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹਨ।',
    link_label: 'ਲਿੰਕ', link_bad: 'https:// ਨਾਲ ਸ਼ੁਰੂ ਹੋਣ ਵਾਲਾ ਪੂਰਾ ਲਿੰਕ ਲਿਖੋ।', qr_long: 'QR ਕੋਡ ਲਈ ਇਹ ਬਹੁਤ ਲੰਬਾ ਹੈ। ਛੋਟਾ ਲਿੰਕ ਵਰਤੋ।',
    qr_check: 'ਪੋਸਟਰ ਸਾਂਝਾ ਜਾਂ ਪ੍ਰਿੰਟ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ QR ਕੋਡ ਨੂੰ ਆਪਣੇ ਫ਼ੋਨ ਨਾਲ ਇੱਕ ਵਾਰ ਸਕੈਨ ਕਰਕੇ ਜ਼ਰੂਰ ਦੇਖੋ।',
    style_title: 'ਡਿਜ਼ਾਈਨ', colours: 'ਰੰਗ', colour_n: 'ਰੰਗ ਸੈੱਟ {n}', font_label: 'ਫ਼ੌਂਟ', font_simple: 'ਸਾਦਾ', font_festive: 'ਤਿਉਹਾਰੀ',
    font_note: 'ਤਿਉਹਾਰੀ ਫ਼ੌਂਟ ਇੱਕ ਵਾਰ ਇੰਟਰਨੈੱਟ ਤੋਂ ਡਾਊਨਲੋਡ ਹੁੰਦਾ ਹੈ। ਇੰਟਰਨੈੱਟ ਨਾ ਹੋਵੇ ਤਾਂ ਸਾਦਾ ਫ਼ੌਂਟ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।', font_loading: 'ਤਿਉਹਾਰੀ ਫ਼ੌਂਟ ਡਾਊਨਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
    font_failed: 'ਤਿਉਹਾਰੀ ਫ਼ੌਂਟ ਡਾਊਨਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ, ਇਸ ਲਈ ਸਾਦਾ ਫ਼ੌਂਟ ਲਗਾਇਆ ਗਿਆ ਹੈ।', shuffle: 'ਹੋਰ ਡਿਜ਼ਾਈਨ ਦੇਖੋ',
    help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ / ਕਾਰੋਬਾਰ ਲਈ ਸੁਝਾਅ',
    tip1: 'ਮੌਕਾ ਚੁਣੋ, ਫਿਰ ਆਪਣੀ ਦੁਕਾਨ ਦਾ ਨਾਮ, ਆਫ਼ਰ ਅਤੇ ਫ਼ੋਨ ਨੰਬਰ ਲਿਖੋ। ਲਿਖਦੇ ਹੀ ਪੋਸਟਰ ਬਦਲ ਜਾਂਦਾ ਹੈ।',
    tip2: 'ਸਟੇਟਸ ਲਈ "WhatsApp ਸਟੇਟਸ", ਫ਼ੀਡ ਲਈ "Instagram ਪੋਸਟ", ਅਤੇ ਕਾਊਂਟਰ ਜਾਂ ਪਰਚਿਆਂ ਲਈ "A4 ਪ੍ਰਿੰਟ" ਜਾਂ "A5 ਪਰਚਾ" ਚੁਣੋ।',
    tip3: 'UPI QR ਜੋੜੋ ਤਾਂ ਜੋ ਗਾਹਕ ਪੋਸਟਰ ਤੋਂ ਹੀ ਭੁਗਤਾਨ ਕਰ ਸਕਣ। ਸਾਂਝਾ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਇਸਨੂੰ ਆਪਣੇ ਫ਼ੋਨ ਨਾਲ ਇੱਕ ਵਾਰ ਸਕੈਨ ਕਰੋ।',
    tip4: 'ਇੱਕੋ ਪੋਸਟਰ ਇੱਕੋ ਵਾਰ 3 ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਬਣਾਓ: ਇੱਕ ਗਰੁੱਪ ਲਈ ਪੰਜਾਬੀ, ਦੂਜੇ ਲਈ ਹਿੰਦੀ ਅਤੇ Instagram ਲਈ ਅੰਗਰੇਜ਼ੀ।',
    tip5: 'ਤਿਉਹਾਰ ਦੀ ਵਧਾਈ 1–2 ਦਿਨ ਪਹਿਲਾਂ ਅਤੇ ਆਫ਼ਰ ਵਾਲਾ ਪੋਸਟਰ ਤਿਉਹਾਰ ਦੀ ਸਵੇਰ ਪੋਸਟ ਕਰੋ।',
    tip6: 'ਤੁਹਾਡੀਆਂ ਫ਼ੋਟੋਆਂ, ਲੋਗੋ ਅਤੇ ਜਾਣਕਾਰੀ ਇਸੇ ਫ਼ੋਨ ਜਾਂ ਕੰਪਿਊਟਰ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ। ਕੁਝ ਵੀ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ, ਇਸ ਲਈ ਇਹ ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਵੀ ਚੱਲਦਾ ਹੈ।'
  },
  or: {
    app_title: 'ପର୍ବ ଶୁଭେଚ୍ଛା ଓ ଅଫର୍ ପୋଷ୍ଟର',
    intro: 'ନିଜ ନାମ, ଲୋଗୋ, ଫଟୋ ଓ UPI QR ସହ ପର୍ବର ଶୁଭେଚ୍ଛା ଓ ଦୋକାନ ଅଫରର ପୋଷ୍ଟର ତିଆରି କରନ୍ତୁ, WhatsApp, Instagram ବା ପ୍ରିଣ୍ଟ ପାଇଁ ପ୍ରସ୍ତୁତ।',
    privacy: 'ଆପଣଙ୍କ ଫଟୋ, ଲୋଗୋ ଓ ତଥ୍ୟ ଏହି ଡିଭାଇସରେ ହିଁ ରହେ। କିଛି ବି ଅପଲୋଡ୍ ହୁଏ ନାହିଁ।',
    occ_title: 'ଅବସର ବାଛନ୍ତୁ', occ_search_ph: 'ଖୋଜନ୍ତୁ: ଦୀପାବଳି, ଇଦ୍, ସେଲ୍…', occ_fest: 'ପର୍ବ, ତାରିଖ ଅନୁସାରେ', occ_biz: 'ଦୋକାନ ପାଇଁ, ଯେକୌଣସି ଦିନ',
    when_today: 'ଆଜି', when_now: 'ଏବେ ଚାଲିଛି', when_tomorrow: 'କାଲି', when_in: '{n} ଦିନ ପରେ', when_unknown: 'ତାରିଖ ଠିକ୍ ହୋଇନାହିଁ', no_match: 'କିଛି ମିଳିଲା ନାହିଁ। ଅନ୍ୟ ଶବ୍ଦ ଲେଖି ଦେଖନ୍ତୁ।',
    dates_btn: 'ପର୍ବ ତାରିଖ ଠିକ୍ କରନ୍ତୁ', dates_title: 'ପର୍ବର ତାରିଖ', dates_help: 'ଅନେକ ପର୍ବ ଚନ୍ଦ୍ର ଅନୁସାରେ ହୁଏ, ତେଣୁ ପ୍ରତିବର୍ଷ ତାରିଖ ବଦଳେ। ନିଜ ପାଞ୍ଜି ଦେଖି ଯେକୌଣସି ତାରିଖ ଏଠାରେ ଠିକ୍ କରନ୍ତୁ।', dates_reset: 'ପୂର୍ବରୁ ଦିଆଯାଇଥିବା ତାରିଖ ବ୍ୟବହାର କରନ୍ତୁ',
    size_title: 'ଆକାର', size_story: 'WhatsApp ଷ୍ଟାଟସ୍', size_insta: 'Instagram ପୋଷ୍ଟ', size_square: 'ବର୍ଗାକାର ପୋଷ୍ଟ', size_fb: 'Facebook ପୋଷ୍ଟ', size_a4: 'A4 ପ୍ରିଣ୍ଟ', size_a5: 'A5 ପାମ୍ପଲେଟ୍',
    preview_aria: 'ପୋଷ୍ଟରର ପ୍ରିଭ୍ୟୁ। ବଦଳାଇବା ପାଇଁ ପୋଷ୍ଟରରେ ଶୁଭେଚ୍ଛା, ନାମ ବା ଅଫର ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ।', making: 'ପୋଷ୍ଟର ତିଆରି ହେଉଛି…',
    dl_png: 'PNG ଡାଉନଲୋଡ୍ କରନ୍ତୁ', dl_jpg: 'JPG ଡାଉନଲୋଡ୍ କରନ୍ତୁ', share_btn: 'WhatsApp ରେ ପଠାନ୍ତୁ',
    share_none: 'ଏହି ବ୍ରାଉଜର ସିଧାସଳଖ ଛବି ପଠାଇପାରେ ନାହିଁ, ତେଣୁ ପୋଷ୍ଟର ଡାଉନଲୋଡ୍ ହୋଇଛି। ଗ୍ୟାଲେରି ବା Downloads ରୁ ପଠାନ୍ତୁ।',
    saved_file: 'ସେଭ୍ ହେଲା: {name}', shortcut: 'ସର୍ଟକଟ୍: Ctrl + S ଦବାଇଲେ PNG ଡାଉନଲୋଡ୍ ହୁଏ।',
    multi_title: 'ଏକାସାଙ୍ଗରେ 3ଟି ଭାଷାରେ ତିଆରି କରନ୍ତୁ', multi_help: '3ଟି ପର୍ଯ୍ୟନ୍ତ ଭାଷା ବାଛନ୍ତୁ। ଶୁଭେଚ୍ଛାର ଭାଷା ବଦଳିବ; ଆପଣଙ୍କ ନାମ, ଅଫର ଓ ଠିକଣା ଯେମିତି ଲେଖିଛନ୍ତି ସେମିତି ରହିବ।',
    multi_max: 'ଆପଣ 3ଟି ପର୍ଯ୍ୟନ୍ତ ଭାଷା ବାଛିପାରିବେ।', multi_make: '{n}ଟି ପୋଷ୍ଟର ତିଆରି କରନ୍ତୁ', multi_dl: 'ସବୁ ଡାଉନଲୋଡ୍ କରନ୍ତୁ', multi_share: 'ସବୁ ସେୟାର କରନ୍ତୁ',
    text_title: 'ଶୁଭେଚ୍ଛା', poster_lang: 'ପୋଷ୍ଟରର ଭାଷା', greet_label: 'ବଡ଼ ଶୁଭେଚ୍ଛା', wish_label: 'ଶୁଭେଚ୍ଛା ବାର୍ତ୍ତା (ଇଚ୍ଛା ହେଲେ)', text_reset: 'ପରାମର୍ଶିତ ଲେଖା ବ୍ୟବହାର କରନ୍ତୁ',
    biz_title: 'ଆପଣଙ୍କ ବ୍ୟବସାୟ', example_note: 'ଏହା ଏକ ଉଦାହରଣ ଦୋକାନ। ନିଜ ତଥ୍ୟ ଲେଖନ୍ତୁ ବା ଏହାକୁ ହଟାନ୍ତୁ।', example_clear: 'ଉଦାହରଣ ହଟାନ୍ତୁ',
    name_label: 'ଦୋକାନ/କମ୍ପାନୀର ନାମ ବା ଆପଣଙ୍କ ନାମ', offer_label: 'ଅଫର (ଇଚ୍ଛା ହେଲେ)', offer_ideas: 'ପରାମର୍ଶ:', phone_label: 'ଫୋନ୍ / WhatsApp ନମ୍ବର', address_label: 'ଠିକଣା', handle_label: 'Instagram, Facebook ବା ୱେବସାଇଟ୍',
    logo_label: 'ଲୋଗୋ', logo_add: 'ଲୋଗୋ ଯୋଡ଼ନ୍ତୁ', photo_label: 'ଆପଣଙ୍କ, ଦୋକାନର ବା ଜିନିଷର ଫଟୋ', photo_add: 'ଫଟୋ ଯୋଡ଼ନ୍ତୁ', img_remove: 'ହଟାନ୍ତୁ', logo_plate: 'ଲୋଗୋ ପଛରେ ଧଳା ଗୋଲ',
    photo_shape: 'ଫଟୋର ଆକାର', shape_circle: 'ଗୋଲ', shape_arch: 'ଖିଲାନ', shape_round: 'ଗୋଲ କୋଣ', photo_zoom: 'ଜୁମ୍', photo_hint: 'ଫଟୋ ଘୁଞ୍ଚାଇବା ପାଇଁ ପୋଷ୍ଟର ଉପରେ ଟାଣନ୍ତୁ।',
    img_bad: 'ଏହି ଫାଇଲ୍ ଖୋଲିଲା ନାହିଁ। ଦୟାକରି JPG ବା PNG ଛବି ବାଛନ୍ତୁ।', img_unsaved: 'ଛବିଟି ବହୁତ ବଡ଼, ତେଣୁ ପେଜ୍ ବନ୍ଦ କଲା ପରେ ମନେ ରହିବ ନାହିଁ। ଏବେ ଆପଣ ଏହାକୁ ବ୍ୟବହାର କରିପାରିବେ।',
    low_res: 'ଏହି ଆକାର ପାଇଁ ଛବିଟି ଛୋଟ ({w} × {h} ପିକ୍ସେଲ୍), ତେଣୁ ଅସ୍ପଷ୍ଟ ଦେଖାଯାଇପାରେ। ସମ୍ଭବ ହେଲେ ବଡ଼ ଛବି ଦିଅନ୍ତୁ।',
    qr_title: 'QR କୋଡ୍', qr_none: 'QR ନାହିଁ', qr_upi: 'UPI ପେମେଣ୍ଟ', qr_wa: 'WhatsApp ଚାଟ୍', qr_link: 'ୱେବସାଇଟ୍ ଲିଙ୍କ', upi_label: 'UPI ID',
    upi_bad: 'ଏହା UPI ID ପରି ଲାଗୁନାହିଁ। ଏହା name@bank ପରି ହୁଏ, ଯେପରି sharmasweets@oksbi।', upi_ok: 'ଗ୍ରାହକମାନେ ଯେକୌଣସି UPI ଆପରେ ଏହାକୁ ସ୍କାନ୍ କରି {name} କୁ ପେମେଣ୍ଟ କରିପାରିବେ।',
    wa_need: 'ପ୍ରଥମେ ଉପରେ "ଫୋନ୍ / WhatsApp ନମ୍ବର" ରେ ଆପଣଙ୍କ 10 ଅଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର ଲେଖନ୍ତୁ।', wa_ok: 'ଗ୍ରାହକମାନେ ଏହାକୁ ସ୍କାନ୍ କରି {phone} ସହ WhatsApp ରେ କଥା ଆରମ୍ଭ କରିପାରିବେ।',
    link_label: 'ଲିଙ୍କ', link_bad: 'https:// ରୁ ଆରମ୍ଭ ହେଉଥିବା ପୂରା ଲିଙ୍କ ଲେଖନ୍ତୁ।', qr_long: 'QR କୋଡ୍ ପାଇଁ ଏହା ବହୁତ ଲମ୍ବା। ଛୋଟ ଲିଙ୍କ ବ୍ୟବହାର କରନ୍ତୁ।',
    qr_check: 'ପୋଷ୍ଟର ସେୟାର ବା ପ୍ରିଣ୍ଟ କରିବା ପୂର୍ବରୁ QR କୋଡ୍‌କୁ ନିଜ ଫୋନରେ ଥରେ ସ୍କାନ୍ କରି ନିଶ୍ଚୟ ଦେଖନ୍ତୁ।',
    style_title: 'ଡିଜାଇନ୍', colours: 'ରଙ୍ଗ', colour_n: 'ରଙ୍ଗ ସେଟ୍ {n}', font_label: 'ଫଣ୍ଟ', font_simple: 'ସାଧାରଣ', font_festive: 'ପର୍ବର',
    font_note: 'ପର୍ବର ଫଣ୍ଟ ଥରେ ଇଣ୍ଟରନେଟରୁ ଡାଉନଲୋଡ୍ ହୁଏ। ଇଣ୍ଟରନେଟ ନ ଥିଲେ ସାଧାରଣ ଫଣ୍ଟ ବ୍ୟବହାର ହୁଏ।', font_loading: 'ପର୍ବର ଫଣ୍ଟ ଡାଉନଲୋଡ୍ ହେଉଛି…',
    font_failed: 'ପର୍ବର ଫଣ୍ଟ ଡାଉନଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ, ତେଣୁ ସାଧାରଣ ଫଣ୍ଟ ବ୍ୟବହାର ହେଉଛି।', shuffle: 'ଅନ୍ୟ ଡିଜାଇନ୍ ଦେଖନ୍ତୁ',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ବ୍ୟବସାୟ ପାଇଁ ପରାମର୍ଶ',
    tip1: 'ଅବସର ବାଛନ୍ତୁ, ତା ପରେ ଦୋକାନର ନାମ, ଅଫର ଓ ଫୋନ୍ ନମ୍ବର ଲେଖନ୍ତୁ। ଲେଖୁ ଲେଖୁ ପୋଷ୍ଟର ବଦଳିଯାଏ।',
    tip2: 'ଷ୍ଟାଟସ୍ ପାଇଁ "WhatsApp ଷ୍ଟାଟସ୍", ଫିଡ୍ ପାଇଁ "Instagram ପୋଷ୍ଟ", ଓ କାଉଣ୍ଟର ବା ପାମ୍ପଲେଟ୍ ପାଇଁ "A4 ପ୍ରିଣ୍ଟ" ବା "A5 ପାମ୍ପଲେଟ୍" ବାଛନ୍ତୁ।',
    tip3: 'UPI QR ଯୋଡ଼ନ୍ତୁ, ଯାହାଦ୍ୱାରା ଗ୍ରାହକ ପୋଷ୍ଟରରୁ ହିଁ ପେମେଣ୍ଟ କରିପାରିବେ। ସେୟାର କରିବା ପୂର୍ବରୁ ନିଜ ଫୋନରେ ଥରେ ସ୍କାନ୍ କରନ୍ତୁ।',
    tip4: 'ଗୋଟିଏ ପୋଷ୍ଟର ଏକାସାଙ୍ଗରେ 3ଟି ଭାଷାରେ ତିଆରି କରନ୍ତୁ: ଗୋଟିଏ ଗ୍ରୁପ୍ ପାଇଁ ଓଡ଼ିଆ, ଆଉ ଗୋଟିଏ ପାଇଁ ହିନ୍ଦୀ ଓ Instagram ପାଇଁ ଇଂରାଜୀ।',
    tip5: 'ପର୍ବର ଶୁଭେଚ୍ଛା 1–2 ଦିନ ଆଗରୁ ଓ ଅଫର ପୋଷ୍ଟର ପର୍ବ ଦିନ ସକାଳେ ପୋଷ୍ଟ କରନ୍ତୁ।',
    tip6: 'ଆପଣଙ୍କ ଫଟୋ, ଲୋଗୋ ଓ ତଥ୍ୟ ଏହି ଫୋନ୍ ବା କମ୍ପ୍ୟୁଟରରେ ହିଁ ରହେ। କିଛି ଅପଲୋଡ୍ ହୁଏ ନାହିଁ, ତେଣୁ ଇଣ୍ଟରନେଟ ବିନା ମଧ୍ୟ ଚାଲେ।'
  },
  ta: {
    app_title: 'பண்டிகை வாழ்த்து & சலுகை போஸ்டர்',
    intro: 'உங்கள் பெயர், லோகோ, புகைப்படம், UPI QR உடன் பண்டிகை வாழ்த்து மற்றும் கடை சலுகை போஸ்டர்களை உருவாக்குங்கள், WhatsApp, Instagram அல்லது அச்சுக்குத் தயார்.',
    privacy: 'உங்கள் புகைப்படங்கள், லோகோ, விவரங்கள் இந்தச் சாதனத்திலேயே இருக்கும். எதுவும் பதிவேற்றப்படாது.',
    occ_title: 'சந்தர்ப்பம்', occ_search_ph: 'தேடுங்கள்: தீபாவளி, ரம்ஜான், சேல்…', occ_fest: 'பண்டிகைகள், தேதி வாரியாக', occ_biz: 'கடைக்கு, எந்த நாளிலும்',
    when_today: 'இன்று', when_now: 'இப்போது நடக்கிறது', when_tomorrow: 'நாளை', when_in: '{n} நாட்களில்', when_unknown: 'தேதி அமைக்கவில்லை', no_match: 'எதுவும் கிடைக்கவில்லை. வேறு சொல்லைத் தட்டச்சு செய்து பாருங்கள்.',
    dates_btn: 'பண்டிகை தேதிகளைத் திருத்து', dates_title: 'பண்டிகை தேதிகள்', dates_help: 'பல பண்டிகைகள் நிலவைப் பொறுத்து வருவதால் ஒவ்வொரு ஆண்டும் தேதி மாறும். உங்கள் நாட்காட்டியைப் பார்த்து எந்தத் தேதியையும் இங்கே திருத்துங்கள்.', dates_reset: 'முன்பே உள்ள தேதிகளைப் பயன்படுத்து',
    size_title: 'அளவு', size_story: 'WhatsApp ஸ்டேட்டஸ்', size_insta: 'Instagram பதிவு', size_square: 'சதுரப் பதிவு', size_fb: 'Facebook பதிவு', size_a4: 'A4 அச்சு', size_a5: 'A5 துண்டுப் பிரசுரம்',
    preview_aria: 'போஸ்டர் முன்னோட்டம். மாற்ற, போஸ்டரில் உள்ள வாழ்த்து, பெயர் அல்லது சலுகையைக் கிளிக் செய்யுங்கள்.', making: 'போஸ்டர் உருவாகிறது…',
    dl_png: 'PNG பதிவிறக்கு', dl_jpg: 'JPG பதிவிறக்கு', share_btn: 'WhatsApp-இல் அனுப்பு',
    share_none: 'இந்த உலாவியால் நேரடியாகப் படம் அனுப்ப முடியாது, எனவே போஸ்டர் பதிவிறக்கப்பட்டது. கேலரி அல்லது Downloads-இலிருந்து அனுப்புங்கள்.',
    saved_file: 'சேமிக்கப்பட்டது: {name}', shortcut: 'குறுக்குவழி: Ctrl + S அழுத்தினால் PNG பதிவிறக்கமாகும்.',
    multi_title: 'ஒரே நேரத்தில் 3 மொழிகளில் உருவாக்கு', multi_help: '3 மொழிகள் வரை தேர்ந்தெடுங்கள். வாழ்த்தின் மொழி மாறும்; உங்கள் பெயர், சலுகை, முகவரி நீங்கள் எழுதியபடியே இருக்கும்.',
    multi_max: '3 மொழிகள் வரை தேர்ந்தெடுக்கலாம்.', multi_make: '{n} போஸ்டர்களை உருவாக்கு', multi_dl: 'அனைத்தையும் பதிவிறக்கு', multi_share: 'அனைத்தையும் பகிர்',
    text_title: 'வாழ்த்து', poster_lang: 'போஸ்டர் மொழி', greet_label: 'பெரிய வாழ்த்து', wish_label: 'வாழ்த்துச் செய்தி (விருப்பம்)', text_reset: 'பரிந்துரைத்த உரையைப் பயன்படுத்து',
    biz_title: 'உங்கள் வணிகம்', example_note: 'இது ஒரு மாதிரிக் கடை. உங்கள் விவரங்களை எழுதுங்கள் அல்லது இதை அழியுங்கள்.', example_clear: 'மாதிரியை அழி',
    name_label: 'கடை/நிறுவனப் பெயர் அல்லது உங்கள் பெயர்', offer_label: 'சலுகை (விருப்பம்)', offer_ideas: 'யோசனைகள்:', phone_label: 'தொலைபேசி / WhatsApp எண்', address_label: 'முகவரி', handle_label: 'Instagram, Facebook அல்லது இணையதளம்',
    logo_label: 'லோகோ', logo_add: 'லோகோ சேர்', photo_label: 'உங்கள், கடையின் அல்லது பொருளின் புகைப்படம்', photo_add: 'புகைப்படம் சேர்', img_remove: 'நீக்கு', logo_plate: 'லோகோவுக்குப் பின்னால் வெள்ளை வட்டம்',
    photo_shape: 'புகைப்பட வடிவம்', shape_circle: 'வட்டம்', shape_arch: 'வளைவு', shape_round: 'வளைந்த மூலைகள்', photo_zoom: 'பெரிதாக்கு', photo_hint: 'புகைப்படத்தை நகர்த்த போஸ்டரில் அதை இழுங்கள்.',
    img_bad: 'இந்தக் கோப்பைத் திறக்க முடியவில்லை. JPG அல்லது PNG படத்தைத் தேர்ந்தெடுங்கள்.', img_unsaved: 'படம் மிகப் பெரியது, எனவே பக்கத்தை மூடிய பிறகு நினைவில் இருக்காது. இப்போது பயன்படுத்தலாம்.',
    low_res: 'இந்த அளவுக்கு இந்தப் படம் சிறியது ({w} × {h} பிக்சல்), எனவே மங்கலாகத் தெரியலாம். முடிந்தால் பெரிய படத்தைப் பயன்படுத்துங்கள்.',
    qr_title: 'QR குறியீடு', qr_none: 'QR வேண்டாம்', qr_upi: 'UPI கட்டணம்', qr_wa: 'WhatsApp உரையாடல்', qr_link: 'இணையதள இணைப்பு', upi_label: 'UPI ID',
    upi_bad: 'இது UPI ID போலத் தெரியவில்லை. இது name@bank போல இருக்கும், உதாரணம் sharmasweets@oksbi.', upi_ok: 'வாடிக்கையாளர்கள் எந்த UPI செயலியிலும் இதை ஸ்கேன் செய்து {name}-க்குப் பணம் செலுத்தலாம்.',
    wa_need: 'முதலில் மேலே "தொலைபேசி / WhatsApp எண்" பகுதியில் உங்கள் 10 இலக்க மொபைல் எண்ணை எழுதுங்கள்.', wa_ok: 'வாடிக்கையாளர்கள் இதை ஸ்கேன் செய்து {phone} உடன் WhatsApp-இல் பேசத் தொடங்கலாம்.',
    link_label: 'இணைப்பு', link_bad: 'https:// என்று தொடங்கும் முழு இணைப்பை எழுதுங்கள்.', qr_long: 'QR குறியீட்டுக்கு இது மிக நீளம். சிறிய இணைப்பைப் பயன்படுத்துங்கள்.',
    qr_check: 'போஸ்டரைப் பகிரும் அல்லது அச்சிடும் முன் QR குறியீட்டை உங்கள் தொலைபேசியில் ஒருமுறை ஸ்கேன் செய்து பாருங்கள்.',
    style_title: 'வடிவமைப்பு', colours: 'வண்ணங்கள்', colour_n: 'வண்ணத் தொகுப்பு {n}', font_label: 'எழுத்துரு', font_simple: 'எளிய', font_festive: 'பண்டிகை',
    font_note: 'பண்டிகை எழுத்துரு ஒருமுறை இணையத்திலிருந்து பதிவிறக்கமாகும். இணையம் இல்லையென்றால் எளிய எழுத்துரு பயன்படும்.', font_loading: 'பண்டிகை எழுத்துரு பதிவிறக்கமாகிறது…',
    font_failed: 'பண்டிகை எழுத்துருவைப் பதிவிறக்க முடியவில்லை, எனவே எளிய எழுத்துரு பயன்படுகிறது.', shuffle: 'வேறு வடிவமைப்பைப் பார்',
    help_title: 'எப்படிப் பயன்படுத்துவது / வணிகத்துக்கான யோசனைகள்',
    tip1: 'சந்தர்ப்பத்தைத் தேர்ந்தெடுத்து, உங்கள் கடைப் பெயர், சலுகை, தொலைபேசி எண்ணை எழுதுங்கள். எழுதும்போதே போஸ்டர் மாறும்.',
    tip2: 'ஸ்டேட்டஸுக்கு "WhatsApp ஸ்டேட்டஸ்", ஃபீடுக்கு "Instagram பதிவு", கவுண்டர் அல்லது துண்டுப் பிரசுரங்களுக்கு "A4 அச்சு" அல்லது "A5 துண்டுப் பிரசுரம்" தேர்ந்தெடுங்கள்.',
    tip3: 'வாடிக்கையாளர்கள் போஸ்டரிலிருந்தே பணம் செலுத்த UPI QR சேருங்கள். பகிரும் முன் உங்கள் தொலைபேசியில் ஒருமுறை ஸ்கேன் செய்யுங்கள்.',
    tip4: 'ஒரே போஸ்டரை ஒரே நேரத்தில் 3 மொழிகளில் உருவாக்குங்கள்: ஒரு குழுவுக்குத் தமிழ், இன்னொன்றுக்கு இந்தி, Instagram-க்கு ஆங்கிலம்.',
    tip5: 'பண்டிகை வாழ்த்தை 1–2 நாள் முன்பும், சலுகை போஸ்டரைப் பண்டிகை அன்று காலையிலும் பதிவிடுங்கள்.',
    tip6: 'உங்கள் புகைப்படங்கள், லோகோ, விவரங்கள் இந்தத் தொலைபேசி அல்லது கணினியிலேயே இருக்கும். எதுவும் பதிவேற்றப்படாது, எனவே இணையம் இல்லாமலும் இயங்கும்.'
  },
  te: {
    app_title: 'పండుగ శుభాకాంక్షలు & ఆఫర్ పోస్టర్',
    intro: 'మీ పేరు, లోగో, ఫోటో, UPI QRతో పండుగ శుభాకాంక్షలు, షాప్ ఆఫర్ పోస్టర్లు తయారు చేయండి, WhatsApp, Instagram లేదా ప్రింట్ కోసం సిద్ధం.',
    privacy: 'మీ ఫోటోలు, లోగో, వివరాలు ఈ పరికరంలోనే ఉంటాయి. ఏదీ అప్‌లోడ్ కాదు.',
    occ_title: 'సందర్భం ఎంచుకోండి', occ_search_ph: 'వెతకండి: దీపావళి, రంజాన్, సేల్…', occ_fest: 'పండుగలు, తేదీ ప్రకారం', occ_biz: 'షాప్ కోసం, ఏ రోజైనా',
    when_today: 'ఈ రోజు', when_now: 'ఇప్పుడు జరుగుతోంది', when_tomorrow: 'రేపు', when_in: '{n} రోజుల్లో', when_unknown: 'తేదీ పెట్టలేదు', no_match: 'ఏమీ దొరకలేదు. వేరే పదం టైప్ చేసి చూడండి.',
    dates_btn: 'పండుగ తేదీలు సరిచేయండి', dates_title: 'పండుగ తేదీలు', dates_help: 'చాలా పండుగలు చంద్రుడిని బట్టి వస్తాయి, అందుకే ప్రతి ఏటా తేదీ మారుతుంది. మీ పంచాంగం చూసి ఏ తేదీనైనా ఇక్కడ సరిచేయండి.', dates_reset: 'ముందే ఉన్న తేదీలు వాడండి',
    size_title: 'సైజు', size_story: 'WhatsApp స్టేటస్', size_insta: 'Instagram పోస్ట్', size_square: 'చతురస్ర పోస్ట్', size_fb: 'Facebook పోస్ట్', size_a4: 'A4 ప్రింట్', size_a5: 'A5 కరపత్రం',
    preview_aria: 'పోస్టర్ ప్రివ్యూ. మార్చడానికి పోస్టర్‌పై శుభాకాంక్షలు, పేరు లేదా ఆఫర్‌ను క్లిక్ చేయండి.', making: 'పోస్టర్ తయారవుతోంది…',
    dl_png: 'PNG డౌన్‌లోడ్ చేయండి', dl_jpg: 'JPG డౌన్‌లోడ్ చేయండి', share_btn: 'WhatsAppలో పంపండి',
    share_none: 'ఈ బ్రౌజర్ నేరుగా చిత్రం పంపలేదు, అందుకే పోస్టర్ డౌన్‌లోడ్ అయింది. గ్యాలరీ లేదా Downloads నుంచి పంపండి.',
    saved_file: 'సేవ్ అయింది: {name}', shortcut: 'షార్ట్‌కట్: Ctrl + S నొక్కితే PNG డౌన్‌లోడ్ అవుతుంది.',
    multi_title: 'ఒకేసారి 3 భాషల్లో తయారు చేయండి', multi_help: '3 భాషల వరకు ఎంచుకోండి. శుభాకాంక్షల భాష మారుతుంది; మీ పేరు, ఆఫర్, చిరునామా మీరు రాసినట్లే ఉంటాయి.',
    multi_max: 'మీరు 3 భాషల వరకు ఎంచుకోవచ్చు.', multi_make: '{n} పోస్టర్లు తయారు చేయండి', multi_dl: 'అన్నీ డౌన్‌లోడ్ చేయండి', multi_share: 'అన్నీ షేర్ చేయండి',
    text_title: 'శుభాకాంక్షలు', poster_lang: 'పోస్టర్ భాష', greet_label: 'పెద్ద శుభాకాంక్షలు', wish_label: 'శుభాకాంక్షల సందేశం (కావాలంటే)', text_reset: 'సూచించిన పాఠ్యం వాడండి',
    biz_title: 'మీ వ్యాపారం', example_note: 'ఇది ఒక ఉదాహరణ షాప్. మీ వివరాలు రాయండి లేదా దీన్ని తొలగించండి.', example_clear: 'ఉదాహరణ తొలగించండి',
    name_label: 'షాప్/సంస్థ పేరు లేదా మీ పేరు', offer_label: 'ఆఫర్ (కావాలంటే)', offer_ideas: 'ఐడియాలు:', phone_label: 'ఫోన్ / WhatsApp నంబర్', address_label: 'చిరునామా', handle_label: 'Instagram, Facebook లేదా వెబ్‌సైట్',
    logo_label: 'లోగో', logo_add: 'లోగో జోడించండి', photo_label: 'మీ, మీ షాప్ లేదా వస్తువు ఫోటో', photo_add: 'ఫోటో జోడించండి', img_remove: 'తొలగించండి', logo_plate: 'లోగో వెనుక తెల్లని వృత్తం',
    photo_shape: 'ఫోటో ఆకారం', shape_circle: 'వృత్తం', shape_arch: 'ఆర్చ్', shape_round: 'గుండ్రని మూలలు', photo_zoom: 'జూమ్', photo_hint: 'ఫోటోను జరపడానికి పోస్టర్‌పై దాన్ని లాగండి.',
    img_bad: 'ఈ ఫైల్ తెరవలేకపోయాం. దయచేసి JPG లేదా PNG చిత్రం ఎంచుకోండి.', img_unsaved: 'చిత్రం చాలా పెద్దది, అందుకే పేజీ మూసిన తర్వాత గుర్తుండదు. ఇప్పుడు వాడుకోవచ్చు.',
    low_res: 'ఈ సైజుకు ఈ చిత్రం చిన్నది ({w} × {h} పిక్సెల్స్), అందుకే మసకగా కనిపించవచ్చు. వీలైతే పెద్ద చిత్రం వాడండి.',
    qr_title: 'QR కోడ్', qr_none: 'QR వద్దు', qr_upi: 'UPI చెల్లింపు', qr_wa: 'WhatsApp చాట్', qr_link: 'వెబ్‌సైట్ లింక్', upi_label: 'UPI ID',
    upi_bad: 'ఇది UPI IDలా కనిపించడం లేదు. ఇది name@bank లాగా ఉంటుంది, ఉదా. sharmasweets@oksbi.', upi_ok: 'కస్టమర్లు ఏ UPI యాప్‌తోనైనా దీన్ని స్కాన్ చేసి {name}కి చెల్లించవచ్చు.',
    wa_need: 'ముందుగా పైన "ఫోన్ / WhatsApp నంబర్"లో మీ 10 అంకెల మొబైల్ నంబర్ రాయండి.', wa_ok: 'కస్టమర్లు దీన్ని స్కాన్ చేసి {phone}తో WhatsAppలో మాట్లాడటం మొదలుపెట్టవచ్చు.',
    link_label: 'లింక్', link_bad: 'https://తో మొదలయ్యే పూర్తి లింక్ రాయండి.', qr_long: 'QR కోడ్‌కు ఇది చాలా పొడవు. చిన్న లింక్ వాడండి.',
    qr_check: 'పోస్టర్ షేర్ లేదా ప్రింట్ చేసే ముందు QR కోడ్‌ను మీ ఫోన్‌తో ఒకసారి స్కాన్ చేసి చూడండి.',
    style_title: 'డిజైన్', colours: 'రంగులు', colour_n: 'రంగుల సెట్ {n}', font_label: 'ఫాంట్', font_simple: 'సాధారణ', font_festive: 'పండుగ',
    font_note: 'పండుగ ఫాంట్ ఒకసారి ఇంటర్నెట్ నుంచి డౌన్‌లోడ్ అవుతుంది. ఇంటర్నెట్ లేకపోతే సాధారణ ఫాంట్ వాడతాం.', font_loading: 'పండుగ ఫాంట్ డౌన్‌లోడ్ అవుతోంది…',
    font_failed: 'పండుగ ఫాంట్ డౌన్‌లోడ్ కాలేదు, అందుకే సాధారణ ఫాంట్ వాడుతున్నాం.', shuffle: 'వేరే డిజైన్ చూడండి',
    help_title: 'ఎలా వాడాలి / వ్యాపారానికి ఐడియాలు',
    tip1: 'సందర్భం ఎంచుకుని, మీ షాప్ పేరు, ఆఫర్, ఫోన్ నంబర్ రాయండి. రాస్తుండగానే పోస్టర్ మారుతుంది.',
    tip2: 'స్టేటస్ కోసం "WhatsApp స్టేటస్", ఫీడ్ కోసం "Instagram పోస్ట్", కౌంటర్ లేదా కరపత్రాల కోసం "A4 ప్రింట్" లేదా "A5 కరపత్రం" ఎంచుకోండి.',
    tip3: 'కస్టమర్లు పోస్టర్ నుంచే చెల్లించేలా UPI QR జోడించండి. షేర్ చేసే ముందు మీ ఫోన్‌తో ఒకసారి స్కాన్ చేయండి.',
    tip4: 'ఒకే పోస్టర్‌ను ఒకేసారి 3 భాషల్లో తయారు చేయండి: ఒక గ్రూప్‌కు తెలుగు, మరోదానికి హిందీ, Instagramకు ఇంగ్లీష్.',
    tip5: 'పండుగ శుభాకాంక్షలు 1–2 రోజుల ముందు, ఆఫర్ పోస్టర్ పండుగ రోజు ఉదయం పోస్ట్ చేయండి.',
    tip6: 'మీ ఫోటోలు, లోగో, వివరాలు ఈ ఫోన్ లేదా కంప్యూటర్‌లోనే ఉంటాయి. ఏదీ అప్‌లోడ్ కాదు, అందుకే ఇంటర్నెట్ లేకున్నా పనిచేస్తుంది.'
  },
  kn: {
    app_title: 'ಹಬ್ಬದ ಶುಭಾಶಯ ಮತ್ತು ಆಫರ್ ಪೋಸ್ಟರ್',
    intro: 'ನಿಮ್ಮ ಹೆಸರು, ಲೋಗೋ, ಫೋಟೋ ಮತ್ತು UPI QR ಜೊತೆ ಹಬ್ಬದ ಶುಭಾಶಯ ಮತ್ತು ಅಂಗಡಿ ಆಫರ್ ಪೋಸ್ಟರ್ ಮಾಡಿ, WhatsApp, Instagram ಅಥವಾ ಮುದ್ರಣಕ್ಕೆ ಸಿದ್ಧ.',
    privacy: 'ನಿಮ್ಮ ಫೋಟೋಗಳು, ಲೋಗೋ ಮತ್ತು ವಿವರಗಳು ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತವೆ. ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ.',
    occ_title: 'ಸಂದರ್ಭ ಆಯ್ಕೆಮಾಡಿ', occ_search_ph: 'ಹುಡುಕಿ: ದೀಪಾವಳಿ, ಈದ್, ಸೇಲ್…', occ_fest: 'ಹಬ್ಬಗಳು, ದಿನಾಂಕದ ಪ್ರಕಾರ', occ_biz: 'ಅಂಗಡಿಗೆ, ಯಾವ ದಿನವಾದರೂ',
    when_today: 'ಇಂದು', when_now: 'ಈಗ ನಡೆಯುತ್ತಿದೆ', when_tomorrow: 'ನಾಳೆ', when_in: '{n} ದಿನಗಳಲ್ಲಿ', when_unknown: 'ದಿನಾಂಕ ಇಲ್ಲ', no_match: 'ಏನೂ ಸಿಗಲಿಲ್ಲ. ಬೇರೆ ಪದ ಬರೆದು ನೋಡಿ.',
    dates_btn: 'ಹಬ್ಬದ ದಿನಾಂಕ ಸರಿಪಡಿಸಿ', dates_title: 'ಹಬ್ಬಗಳ ದಿನಾಂಕಗಳು', dates_help: 'ಅನೇಕ ಹಬ್ಬಗಳು ಚಂದ್ರನ ಪ್ರಕಾರ ಬರುತ್ತವೆ, ಹಾಗಾಗಿ ಪ್ರತಿ ವರ್ಷ ದಿನಾಂಕ ಬದಲಾಗುತ್ತದೆ. ನಿಮ್ಮ ಪಂಚಾಂಗ ನೋಡಿ ಯಾವುದೇ ದಿನಾಂಕವನ್ನು ಇಲ್ಲಿ ಸರಿಪಡಿಸಿ.', dates_reset: 'ಮೊದಲೇ ಇರುವ ದಿನಾಂಕಗಳನ್ನು ಬಳಸಿ',
    size_title: 'ಗಾತ್ರ', size_story: 'WhatsApp ಸ್ಟೇಟಸ್', size_insta: 'Instagram ಪೋಸ್ಟ್', size_square: 'ಚೌಕ ಪೋಸ್ಟ್', size_fb: 'Facebook ಪೋಸ್ಟ್', size_a4: 'A4 ಮುದ್ರಣ', size_a5: 'A5 ಕರಪತ್ರ',
    preview_aria: 'ಪೋಸ್ಟರ್ ಮುನ್ನೋಟ. ಬದಲಾಯಿಸಲು ಪೋಸ್ಟರ್‌ನಲ್ಲಿರುವ ಶುಭಾಶಯ, ಹೆಸರು ಅಥವಾ ಆಫರ್ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ.', making: 'ಪೋಸ್ಟರ್ ತಯಾರಾಗುತ್ತಿದೆ…',
    dl_png: 'PNG ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', dl_jpg: 'JPG ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', share_btn: 'WhatsApp ನಲ್ಲಿ ಕಳುಹಿಸಿ',
    share_none: 'ಈ ಬ್ರೌಸರ್ ನೇರವಾಗಿ ಚಿತ್ರ ಕಳುಹಿಸಲಾರದು, ಹಾಗಾಗಿ ಪೋಸ್ಟರ್ ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ. ಗ್ಯಾಲರಿ ಅಥವಾ Downloads ನಿಂದ ಕಳುಹಿಸಿ.',
    saved_file: 'ಉಳಿಸಲಾಗಿದೆ: {name}', shortcut: 'ಶಾರ್ಟ್‌ಕಟ್: Ctrl + S ಒತ್ತಿದರೆ PNG ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತದೆ.',
    multi_title: 'ಒಮ್ಮೆಗೇ 3 ಭಾಷೆಗಳಲ್ಲಿ ಮಾಡಿ', multi_help: '3 ಭಾಷೆಗಳವರೆಗೆ ಆಯ್ಕೆಮಾಡಿ. ಶುಭಾಶಯದ ಭಾಷೆ ಬದಲಾಗುತ್ತದೆ; ನಿಮ್ಮ ಹೆಸರು, ಆಫರ್ ಮತ್ತು ವಿಳಾಸ ನೀವು ಬರೆದಂತೆಯೇ ಇರುತ್ತವೆ.',
    multi_max: 'ನೀವು 3 ಭಾಷೆಗಳವರೆಗೆ ಆಯ್ಕೆಮಾಡಬಹುದು.', multi_make: '{n} ಪೋಸ್ಟರ್ ಮಾಡಿ', multi_dl: 'ಎಲ್ಲವನ್ನೂ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', multi_share: 'ಎಲ್ಲವನ್ನೂ ಹಂಚಿಕೊಳ್ಳಿ',
    text_title: 'ಶುಭಾಶಯ', poster_lang: 'ಪೋಸ್ಟರ್ ಭಾಷೆ', greet_label: 'ದೊಡ್ಡ ಶುಭಾಶಯ', wish_label: 'ಶುಭಾಶಯ ಸಂದೇಶ (ಬೇಕಿದ್ದರೆ)', text_reset: 'ಸೂಚಿಸಿದ ಪಠ್ಯ ಬಳಸಿ',
    biz_title: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ', example_note: 'ಇದು ಒಂದು ಉದಾಹರಣೆ ಅಂಗಡಿ. ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಬರೆಯಿರಿ ಅಥವಾ ಇದನ್ನು ಅಳಿಸಿ.', example_clear: 'ಉದಾಹರಣೆ ಅಳಿಸಿ',
    name_label: 'ಅಂಗಡಿ/ಕಂಪನಿ ಹೆಸರು ಅಥವಾ ನಿಮ್ಮ ಹೆಸರು', offer_label: 'ಆಫರ್ (ಬೇಕಿದ್ದರೆ)', offer_ideas: 'ಸಲಹೆಗಳು:', phone_label: 'ಫೋನ್ / WhatsApp ಸಂಖ್ಯೆ', address_label: 'ವಿಳಾಸ', handle_label: 'Instagram, Facebook ಅಥವಾ ವೆಬ್‌ಸೈಟ್',
    logo_label: 'ಲೋಗೋ', logo_add: 'ಲೋಗೋ ಸೇರಿಸಿ', photo_label: 'ನಿಮ್ಮ, ಅಂಗಡಿಯ ಅಥವಾ ವಸ್ತುವಿನ ಫೋಟೋ', photo_add: 'ಫೋಟೋ ಸೇರಿಸಿ', img_remove: 'ತೆಗೆದುಹಾಕಿ', logo_plate: 'ಲೋಗೋ ಹಿಂದೆ ಬಿಳಿ ವೃತ್ತ',
    photo_shape: 'ಫೋಟೋ ಆಕಾರ', shape_circle: 'ವೃತ್ತ', shape_arch: 'ಕಮಾನು', shape_round: 'ದುಂಡು ಮೂಲೆಗಳು', photo_zoom: 'ಜೂಮ್', photo_hint: 'ಫೋಟೋ ಸರಿಸಲು ಪೋಸ್ಟರ್ ಮೇಲೆ ಅದನ್ನು ಎಳೆಯಿರಿ.',
    img_bad: 'ಈ ಫೈಲ್ ತೆರೆಯಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು JPG ಅಥವಾ PNG ಚಿತ್ರ ಆಯ್ಕೆಮಾಡಿ.', img_unsaved: 'ಚಿತ್ರ ತುಂಬಾ ದೊಡ್ಡದು, ಹಾಗಾಗಿ ಪುಟ ಮುಚ್ಚಿದ ಮೇಲೆ ನೆನಪಿರುವುದಿಲ್ಲ. ಈಗ ಬಳಸಬಹುದು.',
    low_res: 'ಈ ಗಾತ್ರಕ್ಕೆ ಈ ಚಿತ್ರ ಚಿಕ್ಕದು ({w} × {h} ಪಿಕ್ಸೆಲ್), ಹಾಗಾಗಿ ಮಸುಕಾಗಿ ಕಾಣಬಹುದು. ಸಾಧ್ಯವಾದರೆ ದೊಡ್ಡ ಚಿತ್ರ ಬಳಸಿ.',
    qr_title: 'QR ಕೋಡ್', qr_none: 'QR ಬೇಡ', qr_upi: 'UPI ಪಾವತಿ', qr_wa: 'WhatsApp ಚಾಟ್', qr_link: 'ವೆಬ್‌ಸೈಟ್ ಲಿಂಕ್', upi_label: 'UPI ID',
    upi_bad: 'ಇದು UPI ID ಯಂತೆ ಕಾಣುತ್ತಿಲ್ಲ. ಇದು name@bank ರೀತಿ ಇರುತ್ತದೆ, ಉದಾ. sharmasweets@oksbi.', upi_ok: 'ಗ್ರಾಹಕರು ಯಾವುದೇ UPI ಆ್ಯಪ್‌ನಲ್ಲಿ ಇದನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ {name} ಗೆ ಪಾವತಿಸಬಹುದು.',
    wa_need: 'ಮೊದಲು ಮೇಲೆ "ಫೋನ್ / WhatsApp ಸಂಖ್ಯೆ" ಯಲ್ಲಿ ನಿಮ್ಮ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬರೆಯಿರಿ.', wa_ok: 'ಗ್ರಾಹಕರು ಇದನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ {phone} ಜೊತೆ WhatsApp ನಲ್ಲಿ ಮಾತು ಶುರು ಮಾಡಬಹುದು.',
    link_label: 'ಲಿಂಕ್', link_bad: 'https:// ನಿಂದ ಶುರುವಾಗುವ ಪೂರ್ಣ ಲಿಂಕ್ ಬರೆಯಿರಿ.', qr_long: 'QR ಕೋಡ್‌ಗೆ ಇದು ತುಂಬಾ ಉದ್ದ. ಚಿಕ್ಕ ಲಿಂಕ್ ಬಳಸಿ.',
    qr_check: 'ಪೋಸ್ಟರ್ ಹಂಚುವ ಅಥವಾ ಮುದ್ರಿಸುವ ಮೊದಲು QR ಕೋಡ್ ಅನ್ನು ನಿಮ್ಮ ಫೋನ್‌ನಿಂದ ಒಮ್ಮೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ನೋಡಿ.',
    style_title: 'ವಿನ್ಯಾಸ', colours: 'ಬಣ್ಣಗಳು', colour_n: 'ಬಣ್ಣದ ಸೆಟ್ {n}', font_label: 'ಫಾಂಟ್', font_simple: 'ಸರಳ', font_festive: 'ಹಬ್ಬದ',
    font_note: 'ಹಬ್ಬದ ಫಾಂಟ್ ಒಮ್ಮೆ ಇಂಟರ್ನೆಟ್‌ನಿಂದ ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತದೆ. ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದಿದ್ದರೆ ಸರಳ ಫಾಂಟ್ ಬಳಸಲಾಗುತ್ತದೆ.', font_loading: 'ಹಬ್ಬದ ಫಾಂಟ್ ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    font_failed: 'ಹಬ್ಬದ ಫಾಂಟ್ ಡೌನ್‌ಲೋಡ್ ಆಗಲಿಲ್ಲ, ಹಾಗಾಗಿ ಸರಳ ಫಾಂಟ್ ಬಳಸಲಾಗಿದೆ.', shuffle: 'ಬೇರೆ ವಿನ್ಯಾಸ ನೋಡಿ',
    help_title: 'ಹೇಗೆ ಬಳಸುವುದು / ವ್ಯಾಪಾರಕ್ಕೆ ಸಲಹೆಗಳು',
    tip1: 'ಸಂದರ್ಭ ಆಯ್ಕೆಮಾಡಿ, ನಂತರ ನಿಮ್ಮ ಅಂಗಡಿ ಹೆಸರು, ಆಫರ್ ಮತ್ತು ಫೋನ್ ಸಂಖ್ಯೆ ಬರೆಯಿರಿ. ಬರೆಯುತ್ತಿದ್ದಂತೆ ಪೋಸ್ಟರ್ ಬದಲಾಗುತ್ತದೆ.',
    tip2: 'ಸ್ಟೇಟಸ್‌ಗೆ "WhatsApp ಸ್ಟೇಟಸ್", ಫೀಡ್‌ಗೆ "Instagram ಪೋಸ್ಟ್", ಕೌಂಟರ್ ಅಥವಾ ಕರಪತ್ರಗಳಿಗೆ "A4 ಮುದ್ರಣ" ಅಥವಾ "A5 ಕರಪತ್ರ" ಆಯ್ಕೆಮಾಡಿ.',
    tip3: 'ಗ್ರಾಹಕರು ಪೋಸ್ಟರ್‌ನಿಂದಲೇ ಪಾವತಿಸಲು UPI QR ಸೇರಿಸಿ. ಹಂಚುವ ಮೊದಲು ನಿಮ್ಮ ಫೋನ್‌ನಿಂದ ಒಮ್ಮೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ.',
    tip4: 'ಒಂದೇ ಪೋಸ್ಟರ್ ಅನ್ನು ಒಮ್ಮೆಗೇ 3 ಭಾಷೆಗಳಲ್ಲಿ ಮಾಡಿ: ಒಂದು ಗ್ರೂಪ್‌ಗೆ ಕನ್ನಡ, ಇನ್ನೊಂದಕ್ಕೆ ಹಿಂದಿ, Instagram ಗೆ ಇಂಗ್ಲಿಷ್.',
    tip5: 'ಹಬ್ಬದ ಶುಭಾಶಯವನ್ನು 1–2 ದಿನ ಮೊದಲು, ಆಫರ್ ಪೋಸ್ಟರ್ ಅನ್ನು ಹಬ್ಬದ ದಿನ ಬೆಳಿಗ್ಗೆ ಪೋಸ್ಟ್ ಮಾಡಿ.',
    tip6: 'ನಿಮ್ಮ ಫೋಟೋಗಳು, ಲೋಗೋ ಮತ್ತು ವಿವರಗಳು ಈ ಫೋನ್ ಅಥವಾ ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲೇ ಇರುತ್ತವೆ. ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ, ಹಾಗಾಗಿ ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.'
  },
  ml: {
    app_title: 'ഉത്സവ ആശംസ & ഓഫർ പോസ്റ്റർ',
    intro: 'നിങ്ങളുടെ പേര്, ലോഗോ, ഫോട്ടോ, UPI QR എന്നിവ ചേർത്ത് ഉത്സവ ആശംസകളും കടയിലെ ഓഫർ പോസ്റ്ററുകളും ഉണ്ടാക്കൂ, WhatsApp, Instagram അല്ലെങ്കിൽ പ്രിന്റിന് തയ്യാർ.',
    privacy: 'നിങ്ങളുടെ ഫോട്ടോകളും ലോഗോയും വിവരങ്ങളും ഈ ഉപകരണത്തിൽ തന്നെ ഇരിക്കും. ഒന്നും അപ്‌ലോഡ് ചെയ്യില്ല.',
    occ_title: 'അവസരം തിരഞ്ഞെടുക്കൂ', occ_search_ph: 'തിരയൂ: ദീപാവലി, പെരുന്നാൾ, സെയിൽ…', occ_fest: 'ഉത്സവങ്ങൾ, തീയതി അനുസരിച്ച്', occ_biz: 'കടയ്ക്കായി, ഏത് ദിവസവും',
    when_today: 'ഇന്ന്', when_now: 'ഇപ്പോൾ നടക്കുന്നു', when_tomorrow: 'നാളെ', when_in: '{n} ദിവസത്തിനുള്ളിൽ', when_unknown: 'തീയതി നൽകിയിട്ടില്ല', no_match: 'ഒന്നും കണ്ടില്ല. മറ്റൊരു വാക്ക് ടൈപ്പ് ചെയ്ത് നോക്കൂ.',
    dates_btn: 'ഉത്സവ തീയതികൾ തിരുത്തൂ', dates_title: 'ഉത്സവ തീയതികൾ', dates_help: 'പല ഉത്സവങ്ങളും ചന്ദ്രനെ ആശ്രയിച്ചാണ്, അതിനാൽ ഓരോ വർഷവും തീയതി മാറും. നിങ്ങളുടെ കലണ്ടർ നോക്കി ഏത് തീയതിയും ഇവിടെ തിരുത്തൂ.', dates_reset: 'നേരത്തെ നൽകിയ തീയതികൾ ഉപയോഗിക്കൂ',
    size_title: 'വലുപ്പം', size_story: 'WhatsApp സ്റ്റാറ്റസ്', size_insta: 'Instagram പോസ്റ്റ്', size_square: 'ചതുര പോസ്റ്റ്', size_fb: 'Facebook പോസ്റ്റ്', size_a4: 'A4 പ്രിന്റ്', size_a5: 'A5 നോട്ടീസ്',
    preview_aria: 'പോസ്റ്റർ പ്രിവ്യൂ. മാറ്റാൻ പോസ്റ്ററിലെ ആശംസ, പേര് അല്ലെങ്കിൽ ഓഫറിൽ ക്ലിക്ക് ചെയ്യൂ.', making: 'പോസ്റ്റർ തയ്യാറാകുന്നു…',
    dl_png: 'PNG ഡൗൺലോഡ് ചെയ്യൂ', dl_jpg: 'JPG ഡൗൺലോഡ് ചെയ്യൂ', share_btn: 'WhatsApp-ൽ അയയ്ക്കൂ',
    share_none: 'ഈ ബ്രൗസറിന് നേരിട്ട് ചിത്രം അയയ്ക്കാൻ കഴിയില്ല, അതിനാൽ പോസ്റ്റർ ഡൗൺലോഡ് ചെയ്തു. ഗാലറിയിൽ നിന്നോ Downloads-ൽ നിന്നോ അയയ്ക്കൂ.',
    saved_file: 'സേവ് ചെയ്തു: {name}', shortcut: 'ഷോർട്ട്കട്ട്: Ctrl + S അമർത്തിയാൽ PNG ഡൗൺലോഡ് ആകും.',
    multi_title: 'ഒരുമിച്ച് 3 ഭാഷകളിൽ ഉണ്ടാക്കൂ', multi_help: '3 ഭാഷകൾ വരെ തിരഞ്ഞെടുക്കൂ. ആശംസയുടെ ഭാഷ മാറും; നിങ്ങളുടെ പേര്, ഓഫർ, വിലാസം എന്നിവ നിങ്ങൾ എഴുതിയതുപോലെ തന്നെ ഇരിക്കും.',
    multi_max: 'നിങ്ങൾക്ക് 3 ഭാഷകൾ വരെ തിരഞ്ഞെടുക്കാം.', multi_make: '{n} പോസ്റ്ററുകൾ ഉണ്ടാക്കൂ', multi_dl: 'എല്ലാം ഡൗൺലോഡ് ചെയ്യൂ', multi_share: 'എല്ലാം ഷെയർ ചെയ്യൂ',
    text_title: 'ആശംസ', poster_lang: 'പോസ്റ്ററിന്റെ ഭാഷ', greet_label: 'വലിയ ആശംസ', wish_label: 'ആശംസാ സന്ദേശം (വേണമെങ്കിൽ)', text_reset: 'നിർദ്ദേശിച്ച വാചകം ഉപയോഗിക്കൂ',
    biz_title: 'നിങ്ങളുടെ ബിസിനസ്', example_note: 'ഇതൊരു ഉദാഹരണ കടയാണ്. നിങ്ങളുടെ വിവരങ്ങൾ എഴുതൂ, അല്ലെങ്കിൽ ഇത് മായ്ക്കൂ.', example_clear: 'ഉദാഹരണം മായ്ക്കൂ',
    name_label: 'കടയുടെ/സ്ഥാപനത്തിന്റെ പേര് അല്ലെങ്കിൽ നിങ്ങളുടെ പേര്', offer_label: 'ഓഫർ (വേണമെങ്കിൽ)', offer_ideas: 'ആശയങ്ങൾ:', phone_label: 'ഫോൺ / WhatsApp നമ്പർ', address_label: 'വിലാസം', handle_label: 'Instagram, Facebook അല്ലെങ്കിൽ വെബ്സൈറ്റ്',
    logo_label: 'ലോഗോ', logo_add: 'ലോഗോ ചേർക്കൂ', photo_label: 'നിങ്ങളുടെ, കടയുടെ അല്ലെങ്കിൽ ഉൽപ്പന്നത്തിന്റെ ഫോട്ടോ', photo_add: 'ഫോട്ടോ ചേർക്കൂ', img_remove: 'നീക്കം ചെയ്യൂ', logo_plate: 'ലോഗോയ്ക്ക് പിന്നിൽ വെളുത്ത വൃത്തം',
    photo_shape: 'ഫോട്ടോയുടെ ആകൃതി', shape_circle: 'വൃത്തം', shape_arch: 'കമാനം', shape_round: 'ഉരുണ്ട മൂലകൾ', photo_zoom: 'സൂം', photo_hint: 'ഫോട്ടോ നീക്കാൻ പോസ്റ്ററിൽ അത് വലിക്കൂ.',
    img_bad: 'ഈ ഫയൽ തുറക്കാനായില്ല. ദയവായി JPG അല്ലെങ്കിൽ PNG ചിത്രം തിരഞ്ഞെടുക്കൂ.', img_unsaved: 'ചിത്രം വളരെ വലുതാണ്, അതിനാൽ പേജ് അടച്ചാൽ ഓർമ്മയിൽ ഉണ്ടാകില്ല. ഇപ്പോൾ ഉപയോഗിക്കാം.',
    low_res: 'ഈ വലുപ്പത്തിന് ഈ ചിത്രം ചെറുതാണ് ({w} × {h} പിക്സൽ), അതിനാൽ മങ്ങിയതായി തോന്നാം. കഴിയുമെങ്കിൽ വലിയ ചിത്രം ഉപയോഗിക്കൂ.',
    qr_title: 'QR കോഡ്', qr_none: 'QR വേണ്ട', qr_upi: 'UPI പേയ്മെന്റ്', qr_wa: 'WhatsApp ചാറ്റ്', qr_link: 'വെബ്സൈറ്റ് ലിങ്ക്', upi_label: 'UPI ID',
    upi_bad: 'ഇത് UPI ID പോലെ തോന്നുന്നില്ല. ഇത് name@bank പോലെ ആയിരിക്കും, ഉദാ. sharmasweets@oksbi.', upi_ok: 'ഉപഭോക്താക്കൾക്ക് ഏത് UPI ആപ്പിലും ഇത് സ്കാൻ ചെയ്ത് {name}-ന് പണം നൽകാം.',
    wa_need: 'ആദ്യം മുകളിൽ "ഫോൺ / WhatsApp നമ്പർ" എന്നതിൽ നിങ്ങളുടെ 10 അക്ക മൊബൈൽ നമ്പർ എഴുതൂ.', wa_ok: 'ഉപഭോക്താക്കൾക്ക് ഇത് സ്കാൻ ചെയ്ത് {phone}-മായി WhatsApp-ൽ സംസാരിച്ചു തുടങ്ങാം.',
    link_label: 'ലിങ്ക്', link_bad: 'https:// എന്ന് തുടങ്ങുന്ന മുഴുവൻ ലിങ്കും എഴുതൂ.', qr_long: 'QR കോഡിന് ഇത് വളരെ നീളമാണ്. ചെറിയ ലിങ്ക് ഉപയോഗിക്കൂ.',
    qr_check: 'പോസ്റ്റർ ഷെയർ ചെയ്യുന്നതിനോ പ്രിന്റ് ചെയ്യുന്നതിനോ മുമ്പ് QR കോഡ് നിങ്ങളുടെ ഫോണിൽ ഒരിക്കൽ സ്കാൻ ചെയ്ത് നോക്കൂ.',
    style_title: 'ഡിസൈൻ', colours: 'നിറങ്ങൾ', colour_n: 'നിറക്കൂട്ട് {n}', font_label: 'ഫോണ്ട്', font_simple: 'സാധാരണ', font_festive: 'ഉത്സവ',
    font_note: 'ഉത്സവ ഫോണ്ട് ഒരിക്കൽ ഇന്റർനെറ്റിൽ നിന്ന് ഡൗൺലോഡ് ചെയ്യും. ഇന്റർനെറ്റ് ഇല്ലെങ്കിൽ സാധാരണ ഫോണ്ട് ഉപയോഗിക്കും.', font_loading: 'ഉത്സവ ഫോണ്ട് ഡൗൺലോഡ് ചെയ്യുന്നു…',
    font_failed: 'ഉത്സവ ഫോണ്ട് ഡൗൺലോഡ് ചെയ്യാനായില്ല, അതിനാൽ സാധാരണ ഫോണ്ട് ഉപയോഗിക്കുന്നു.', shuffle: 'മറ്റൊരു ഡിസൈൻ കാണൂ',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ബിസിനസിനുള്ള ആശയങ്ങൾ',
    tip1: 'അവസരം തിരഞ്ഞെടുത്ത്, നിങ്ങളുടെ കടയുടെ പേര്, ഓഫർ, ഫോൺ നമ്പർ എന്നിവ എഴുതൂ. എഴുതുമ്പോൾ തന്നെ പോസ്റ്റർ മാറും.',
    tip2: 'സ്റ്റാറ്റസിന് "WhatsApp സ്റ്റാറ്റസ്", ഫീഡിന് "Instagram പോസ്റ്റ്", കൗണ്ടറിനോ നോട്ടീസിനോ "A4 പ്രിന്റ്" അല്ലെങ്കിൽ "A5 നോട്ടീസ്" തിരഞ്ഞെടുക്കൂ.',
    tip3: 'ഉപഭോക്താക്കൾക്ക് പോസ്റ്ററിൽ നിന്ന് തന്നെ പണം നൽകാൻ UPI QR ചേർക്കൂ. ഷെയർ ചെയ്യും മുമ്പ് നിങ്ങളുടെ ഫോണിൽ ഒരിക്കൽ സ്കാൻ ചെയ്യൂ.',
    tip4: 'ഒരേ പോസ്റ്റർ ഒരുമിച്ച് 3 ഭാഷകളിൽ ഉണ്ടാക്കൂ: ഒരു ഗ്രൂപ്പിന് മലയാളം, മറ്റൊന്നിന് തമിഴ്, Instagram-ന് ഇംഗ്ലീഷ്.',
    tip5: 'ഉത്സവ ആശംസ 1–2 ദിവസം മുമ്പും ഓഫർ പോസ്റ്റർ ഉത്സവ ദിവസം രാവിലെയും പോസ്റ്റ് ചെയ്യൂ.',
    tip6: 'നിങ്ങളുടെ ഫോട്ടോകളും ലോഗോയും വിവരങ്ങളും ഈ ഫോണിലോ കമ്പ്യൂട്ടറിലോ തന്നെ ഇരിക്കും. ഒന്നും അപ്‌ലോഡ് ചെയ്യില്ല, അതിനാൽ ഇന്റർനെറ്റ് ഇല്ലാതെയും പ്രവർത്തിക്കും.'
  },
  ur: {
    app_title: 'تہوار مبارکباد اور آفر پوسٹر',
    intro: 'اپنے نام، لوگو، فوٹو اور UPI QR کے ساتھ تہوار کی مبارکباد اور دکان کی آفر والے پوسٹر بنائیں، WhatsApp، Instagram یا پرنٹ کے لیے تیار۔',
    privacy: 'آپ کی تصویریں، لوگو اور معلومات اسی ڈیوائس میں رہتی ہیں۔ کچھ بھی اپ لوڈ نہیں ہوتا۔',
    occ_title: 'موقع چنیں', occ_search_ph: 'تلاش کریں: دیوالی، عید، سیل…', occ_fest: 'تہوار، تاریخ کے حساب سے', occ_biz: 'دکان کے لیے، کسی بھی دن',
    when_today: 'آج', when_now: 'ابھی جاری ہے', when_tomorrow: 'کل', when_in: '{n} دن بعد', when_unknown: 'تاریخ طے نہیں', no_match: 'کچھ نہیں ملا۔ کوئی دوسرا لفظ لکھ کر دیکھیں۔',
    dates_btn: 'تہواروں کی تاریخیں درست کریں', dates_title: 'تہواروں کی تاریخیں', dates_help: 'کئی تہوار چاند کے حساب سے آتے ہیں، اس لیے ہر سال تاریخ بدلتی ہے۔ اپنا کیلنڈر دیکھ کر کوئی بھی تاریخ یہاں درست کریں۔', dates_reset: 'پہلے سے دی گئی تاریخیں لگائیں',
    size_title: 'سائز', size_story: 'WhatsApp اسٹیٹس', size_insta: 'Instagram پوسٹ', size_square: 'چوکور پوسٹ', size_fb: 'Facebook پوسٹ', size_a4: 'A4 پرنٹ', size_a5: 'A5 پرچہ',
    preview_aria: 'پوسٹر کا پیش منظر۔ بدلنے کے لیے پوسٹر پر مبارکباد، نام یا آفر پر کلک کریں۔', making: 'پوسٹر بن رہا ہے…',
    dl_png: 'PNG ڈاؤن لوڈ کریں', dl_jpg: 'JPG ڈاؤن لوڈ کریں', share_btn: 'WhatsApp پر بھیجیں',
    share_none: 'یہ براؤزر سیدھی تصویر نہیں بھیج سکتا، اس لیے پوسٹر ڈاؤن لوڈ ہو گیا ہے۔ اسے گیلری یا Downloads سے بھیجیں۔',
    saved_file: 'محفوظ ہوا: {name}', shortcut: 'شارٹ کٹ: Ctrl + S دبانے سے PNG ڈاؤن لوڈ ہوتا ہے۔',
    multi_title: 'ایک ساتھ 3 زبانوں میں بنائیں', multi_help: '3 زبانوں تک چنیں۔ مبارکباد کی زبان بدلے گی؛ آپ کا نام، آفر اور پتہ ویسے ہی رہیں گے جیسے آپ نے لکھے۔',
    multi_max: 'آپ 3 زبانوں تک چن سکتے ہیں۔', multi_make: '{n} پوسٹر بنائیں', multi_dl: 'سب ڈاؤن لوڈ کریں', multi_share: 'سب شیئر کریں',
    text_title: 'مبارکباد', poster_lang: 'پوسٹر کی زبان', greet_label: 'بڑی مبارکباد', wish_label: 'مبارکباد کا پیغام (چاہیں تو)', text_reset: 'تجویز کردہ متن لگائیں',
    biz_title: 'آپ کا کاروبار', example_note: 'یہ ایک مثالی دکان ہے۔ اپنی معلومات لکھیں یا اسے ہٹا دیں۔', example_clear: 'مثال ہٹائیں',
    name_label: 'دکان/کمپنی کا نام یا آپ کا نام', offer_label: 'آفر (چاہیں تو)', offer_ideas: 'تجاویز:', phone_label: 'فون / WhatsApp نمبر', address_label: 'پتہ', handle_label: 'Instagram، Facebook یا ویب سائٹ',
    logo_label: 'لوگو', logo_add: 'لوگو شامل کریں', photo_label: 'آپ کی، دکان کی یا سامان کی تصویر', photo_add: 'تصویر شامل کریں', img_remove: 'ہٹائیں', logo_plate: 'لوگو کے پیچھے سفید دائرہ',
    photo_shape: 'تصویر کی شکل', shape_circle: 'گول', shape_arch: 'محراب', shape_round: 'گول کونے', photo_zoom: 'زوم', photo_hint: 'تصویر کھسکانے کے لیے اسے پوسٹر پر کھینچیں۔',
    img_bad: 'یہ فائل نہیں کھل سکی۔ براہ کرم JPG یا PNG تصویر چنیں۔', img_unsaved: 'تصویر بہت بڑی ہے، اس لیے صفحہ بند کرنے کے بعد یاد نہیں رہے گی۔ ابھی آپ اسے استعمال کر سکتے ہیں۔',
    low_res: 'اس سائز کے لیے یہ تصویر چھوٹی ہے ({w} × {h} پکسل)، اس لیے دھندلی لگ سکتی ہے۔ ہو سکے تو بڑی تصویر لگائیں۔',
    qr_title: 'QR کوڈ', qr_none: 'QR نہیں', qr_upi: 'UPI ادائیگی', qr_wa: 'WhatsApp چیٹ', qr_link: 'ویب سائٹ لنک', upi_label: 'UPI ID',
    upi_bad: 'یہ UPI ID جیسی نہیں لگتی۔ یہ name@bank جیسی ہوتی ہے، مثلاً sharmasweets@oksbi۔', upi_ok: 'گاہک کسی بھی UPI ایپ سے اسے اسکین کر کے {name} کو ادائیگی کر سکتے ہیں۔',
    wa_need: 'پہلے اوپر "فون / WhatsApp نمبر" میں اپنا 10 ہندسوں کا موبائل نمبر لکھیں۔', wa_ok: 'گاہک اسے اسکین کر کے {phone} سے WhatsApp پر بات شروع کر سکتے ہیں۔',
    link_label: 'لنک', link_bad: 'https:// سے شروع ہونے والا پورا لنک لکھیں۔', qr_long: 'QR کوڈ کے لیے یہ بہت لمبا ہے۔ چھوٹا لنک استعمال کریں۔',
    qr_check: 'پوسٹر شیئر یا پرنٹ کرنے سے پہلے QR کوڈ کو اپنے فون سے ایک بار اسکین کر کے ضرور دیکھیں۔',
    style_title: 'ڈیزائن', colours: 'رنگ', colour_n: 'رنگوں کا سیٹ {n}', font_label: 'فونٹ', font_simple: 'سادہ', font_festive: 'تہواری',
    font_note: 'تہواری فونٹ ایک بار انٹرنیٹ سے ڈاؤن لوڈ ہوتا ہے۔ انٹرنیٹ نہ ہو تو سادہ فونٹ لگتا ہے۔', font_loading: 'تہواری فونٹ ڈاؤن لوڈ ہو رہا ہے…',
    font_failed: 'تہواری فونٹ ڈاؤن لوڈ نہیں ہو سکا، اس لیے سادہ فونٹ لگایا گیا ہے۔', shuffle: 'دوسرا ڈیزائن دیکھیں',
    help_title: 'کیسے استعمال کریں / کاروبار کے لیے تجاویز',
    tip1: 'موقع چنیں، پھر اپنی دکان کا نام، آفر اور فون نمبر لکھیں۔ لکھتے ہی پوسٹر بدل جاتا ہے۔',
    tip2: 'اسٹیٹس کے لیے "WhatsApp اسٹیٹس"، فیڈ کے لیے "Instagram پوسٹ"، اور کاؤنٹر یا پرچوں کے لیے "A4 پرنٹ" یا "A5 پرچہ" چنیں۔',
    tip3: 'UPI QR شامل کریں تاکہ گاہک پوسٹر سے ہی ادائیگی کر سکیں۔ شیئر کرنے سے پہلے اسے اپنے فون سے ایک بار اسکین کریں۔',
    tip4: 'ایک ہی پوسٹر ایک ساتھ 3 زبانوں میں بنائیں: ایک گروپ کے لیے اردو، دوسرے کے لیے ہندی اور Instagram کے لیے انگریزی۔',
    tip5: 'تہوار کی مبارکباد 1–2 دن پہلے اور آفر والا پوسٹر تہوار کی صبح پوسٹ کریں۔',
    tip6: 'آپ کی تصویریں، لوگو اور معلومات اسی فون یا کمپیوٹر میں رہتی ہیں۔ کچھ بھی اپ لوڈ نہیں ہوتا، اس لیے یہ انٹرنیٹ کے بغیر بھی چلتا ہے۔'
  }
};
