/* UI strings for Lens & Mirror Ray Lab. Keys are identical in all 12 languages.
   Optics symbols (F, C, P, O, F₁, 2F₂, u, v, f, m) stay in Latin letters, as in NCERT books of every medium. */
window.APP_STRINGS = {};
window.APP_STRINGS.en = {
  app_title: 'Lens & Mirror Ray Lab',
  intro: 'Move an object in front of a mirror or a lens and watch the rays make its image. Learn the sign convention, the mirror and lens formulas and the NCERT image tables.',
  dev_label: 'Choose a mirror or a lens',
  dev_concave_mirror: 'Concave mirror',
  dev_convex_mirror: 'Convex mirror',
  dev_convex_lens: 'Convex lens',
  dev_concave_lens: 'Concave lens',
  canvas_label: 'Ray diagram. Drag the object, or use the arrow keys to move it.',
  drag_hint: 'Drag the orange object along the axis, or click the picture and use the ← → keys.',
  not_to_scale: 'Heights are drawn larger than distances so the rays are easy to see.',
  rays_label: 'Rays:',
  ray_par: 'Parallel to axis',
  ray_c: 'Through C',
  ray_o: 'Through O',
  ray_f: 'Through F',
  ray_f1: 'Through F₁',
  ray_f2: 'Towards F₂',
  ray_p: 'At pole P',
  ray_n: 'Ray {n}',
  ray_miss: 'Some rays miss the mirror or lens at this position, so they are not drawn (dashed buttons).',
  f_label: 'Focal length |f|',
  u_label: 'Object distance |u|',
  h_label: 'Object height h',
  far_btn: 'Very far (∞)',
  save_png: 'Save picture',
  lbl_object: 'Object',
  lbl_image: 'Image',
  light_dir: 'Light',
  side_front: 'Front: real images',
  side_behind: 'Behind: virtual images',
  side_obj: 'Object side: virtual images',
  side_other: 'Other side: real images',
  note_point: 'The object is very far away: the rays arrive parallel and make a point-sized image at the focus.',
  note_inf_img: 'The rays come out parallel, so the image is formed at infinity.',
  note_off: 'The image is outside the picture, at v = {v}.',
  res_h: 'Results (with signs)',
  r_u: 'Object distance u',
  r_v: 'Image distance v',
  r_f: 'Focal length f',
  r_m: 'Magnification m',
  r_h: 'Object height h',
  r_h2: 'Image height h′',
  r_p: 'Power P',
  r_obj_pos: 'Object:',
  r_img_pos: 'Image:',
  nat_real: 'Real',
  nat_virtual: 'Virtual',
  nat_inverted: 'Inverted',
  nat_erect: 'Erect',
  size_point: 'Highly diminished, point-sized',
  size_dim: 'Diminished',
  size_same: 'Same size',
  size_big: 'Enlarged',
  size_huge: 'Highly enlarged',
  why_obj_inf: 'Rays from a very far object arrive parallel to the axis, so they meet (or seem to meet) at the focus.',
  why_inf: 'The rays come out parallel to each other, so they meet only at infinity.',
  why_mirror_real: 'v is negative: the image is in front of the mirror, where the reflected rays really meet. So it is real.',
  why_mirror_virtual: 'v is positive: the image is behind the mirror. The rays only seem to come from there, so it is virtual.',
  why_lens_real: 'v is positive: the image is on the other side of the lens, where the rays really meet. So it is real.',
  why_lens_virtual: 'v is negative: the image is on the same side as the object. The rays only seem to come from there, so it is virtual.',
  why_m_neg: 'm is negative, so the image is inverted.',
  why_m_pos: 'm is positive, so the image is erect.',
  why_m_big: 'The value of m (without its sign) is more than 1, so the image is enlarged.',
  why_m_small: 'The value of m (without its sign) is less than 1, so the image is diminished.',
  why_m_same: 'The value of m (without its sign) is 1, so the image is the same size as the object.',
  form_h: 'Check with the formula',
  form_mirror: 'Mirror formula',
  form_lens: 'Lens formula',
  form_mag: 'Magnification',
  form_power: 'Power of the lens (f in metres, so 100/f when f is in cm)',
  table_h: 'NCERT table: where is the image?',
  table_tip: 'Tap a row to put the object at that position.',
  th_obj: 'Position of object',
  th_img: 'Position of image',
  th_size: 'Size of image',
  th_nature: 'Nature of image',
  nature_ri: 'Real and inverted',
  nature_ve: 'Virtual and erect',
  pos_inf: 'At infinity',
  pos_beyond_c: 'Beyond C',
  pos_at_c: 'At C',
  pos_c_f: 'Between C and F',
  pos_f_c: 'Between F and C',
  pos_at_f: 'At F',
  pos_p_f: 'Between P and F',
  pos_behind: 'Behind the mirror',
  pos_inf_p: 'Between infinity and the pole P',
  pos_behind_pf: 'Between P and F, behind the mirror',
  pos_behind_f: 'At F, behind the mirror',
  pos_beyond_2f1: 'Beyond 2F₁',
  pos_at_2f1: 'At 2F₁',
  pos_f1_2f1: 'Between F₁ and 2F₁',
  pos_at_f1: 'At F₁',
  pos_f1_o: 'Between F₁ and optical centre O',
  pos_at_f2: 'At F₂',
  pos_f2_2f2: 'Between F₂ and 2F₂',
  pos_at_2f2: 'At 2F₂',
  pos_beyond_2f2: 'Beyond 2F₂',
  pos_same_side: 'On the same side of the lens as the object',
  pos_inf_o: 'Between infinity and optical centre O',
  sign_h: 'New Cartesian sign convention',
  sign_1: 'Measure every distance from the pole P of the mirror or the optical centre O of the lens.',
  sign_2: 'Light falls from the left. Distances to the right (along the light) are positive (+); distances to the left are negative (−).',
  sign_3: 'So the object distance u is always negative here.',
  sign_4: 'Heights above the principal axis are positive; heights below it are negative.',
  sign_5: 'f is negative for a concave mirror and a concave lens, and positive for a convex mirror and a convex lens.',
  quiz_h: 'Quiz: predict the image',
  quiz_q: 'Object distance {u}, focal length {f}. What image is formed?',
  quiz_q_inf: 'The object is very far away (at infinity). Focal length {f}. What image is formed?',
  q_pos: 'Position of image',
  q_nature: 'Real or virtual?',
  q_orient: 'Erect or inverted?',
  q_size: 'Size of image',
  q_choose: 'Choose…',
  q_check: 'Check answer',
  q_next: 'New question',
  q_show: 'See it in the lab',
  q_score: 'Score: {a} / {b}',
  q_need: 'Please answer all four parts first.',
  q_right: 'Well done! All four parts are correct.',
  q_wrong: 'Not quite: {n} of 4 parts are correct. See the right answer below.',
  q_hint: 'Here F is {f} and C (or 2F) is {c} from the mirror or lens.',
  uses_h: 'Where do we use them?',
  use_show: 'Show me',
  use_torch_t: 'Torch and car headlights',
  use_torch_d: 'The bulb sits at the focus of a concave mirror, so the light goes out as a strong parallel beam.',
  use_solar_t: 'Solar cooker and furnace',
  use_solar_d: 'Sunlight comes from very far, so a concave mirror collects it at its focus and makes it very hot.',
  use_shave_t: 'Shaving and make-up mirror',
  use_shave_d: 'Keep your face between P and F of a concave mirror to see an erect, enlarged image.',
  use_rear_t: 'Rear-view mirror',
  use_rear_d: 'A convex mirror always gives an erect, smaller image and shows a wide area behind the vehicle.',
  use_mag_t: 'Magnifying glass',
  use_mag_d: 'Keep the object between F₁ and O of a convex lens to get an erect, enlarged, virtual image.',
  use_proj_t: 'Projector',
  use_proj_d: 'The slide sits between F₁ and 2F₁ of a convex lens, so a large, real, inverted image falls on the screen. That is why slides are put in upside down.',
  use_cam_t: 'Camera and our eye',
  use_cam_d: 'A far object (beyond 2F₁) makes a small, real, inverted image on the sensor or the retina.',
  use_spec_t: 'Spectacles for short sight',
  use_spec_d: 'A concave lens always gives a virtual, erect, smaller image. It helps people with myopia see far.',
  help_h: 'How to use / Ideas for the classroom',
  help_1: 'Pick a mirror or lens, then drag the orange object (or move the slider). The rays, the image and all the numbers change at once.',
  help_2: 'Turn rays on or off with the coloured buttons. Any two rays are enough to find the image; dashed lines show where rays only seem to come from.',
  help_3: 'Read u, v, f and m with their signs. The formula box shows every step, so students can check their own numericals.',
  help_4: 'Tap a row of the NCERT table to jump to that object position. Print the page to get the diagram, the working and the table on paper.',
  help_5: 'Class activity: one student moves the object while the class calls out "real or virtual, erect or inverted, bigger or smaller" before looking. Then play the quiz in teams.',
  help_6: 'Try at home: look into a shiny steel spoon. The inside acts like a concave mirror and the back like a convex mirror.'
};
window.APP_STRINGS.hi = {
  app_title: 'लेंस और दर्पण किरण लैब',
  intro: 'दर्पण या लेंस के सामने वस्तु को खिसकाएँ और देखें कि किरणें प्रतिबिंब कैसे बनाती हैं। चिह्न परिपाटी, दर्पण और लेंस सूत्र तथा NCERT की प्रतिबिंब तालिकाएँ सीखें।',
  dev_label: 'दर्पण या लेंस चुनें',
  dev_concave_mirror: 'अवतल दर्पण',
  dev_convex_mirror: 'उत्तल दर्पण',
  dev_convex_lens: 'उत्तल लेंस',
  dev_concave_lens: 'अवतल लेंस',
  canvas_label: 'किरण आरेख। वस्तु को खींचें या तीर वाली कुंजियों से खिसकाएँ।',
  drag_hint: 'नारंगी वस्तु को अक्ष पर खींचें, या चित्र पर क्लिक करके ← → कुंजियाँ दबाएँ।',
  not_to_scale: 'किरणें साफ़ दिखें, इसलिए ऊँचाइयाँ दूरियों से बड़ी बनाई गई हैं।',
  rays_label: 'किरणें:',
  ray_par: 'अक्ष के समांतर',
  ray_c: 'C से होकर',
  ray_o: 'O से होकर',
  ray_f: 'F से होकर',
  ray_f1: 'F₁ से होकर',
  ray_f2: 'F₂ की ओर',
  ray_p: 'ध्रुव P पर',
  ray_n: 'किरण {n}',
  ray_miss: 'इस स्थिति में कुछ किरणें दर्पण या लेंस तक नहीं पहुँचतीं, इसलिए वे नहीं बनाई गईं (डैश वाले बटन)।',
  f_label: 'फोकस दूरी |f|',
  u_label: 'वस्तु की दूरी |u|',
  h_label: 'वस्तु की ऊँचाई h',
  far_btn: 'बहुत दूर (∞)',
  save_png: 'चित्र सेव करें',
  lbl_object: 'वस्तु',
  lbl_image: 'प्रतिबिंब',
  light_dir: 'प्रकाश',
  side_front: 'सामने: वास्तविक प्रतिबिंब',
  side_behind: 'पीछे: आभासी प्रतिबिंब',
  side_obj: 'वस्तु की ओर: आभासी प्रतिबिंब',
  side_other: 'दूसरी ओर: वास्तविक प्रतिबिंब',
  note_point: 'वस्तु बहुत दूर है: किरणें समांतर आती हैं और फोकस पर बिंदु जैसा प्रतिबिंब बनाती हैं।',
  note_inf_img: 'किरणें समांतर निकलती हैं, इसलिए प्रतिबिंब अनंत पर बनता है।',
  note_off: 'प्रतिबिंब चित्र से बाहर है, v = {v} पर।',
  res_h: 'परिणाम (चिह्न सहित)',
  r_u: 'वस्तु की दूरी u',
  r_v: 'प्रतिबिंब की दूरी v',
  r_f: 'फोकस दूरी f',
  r_m: 'आवर्धन m',
  r_h: 'वस्तु की ऊँचाई h',
  r_h2: 'प्रतिबिंब की ऊँचाई h′',
  r_p: 'क्षमता P',
  r_obj_pos: 'वस्तु:',
  r_img_pos: 'प्रतिबिंब:',
  nat_real: 'वास्तविक',
  nat_virtual: 'आभासी',
  nat_inverted: 'उल्टा',
  nat_erect: 'सीधा',
  size_point: 'अत्यधिक छोटा, बिंदु के आकार का',
  size_dim: 'छोटा',
  size_same: 'समान आकार',
  size_big: 'बड़ा (आवर्धित)',
  size_huge: 'अत्यधिक बड़ा',
  why_obj_inf: 'बहुत दूर की वस्तु से किरणें अक्ष के समांतर आती हैं, इसलिए वे फोकस पर मिलती हैं (या वहाँ से आती लगती हैं)।',
  why_inf: 'निकलने वाली किरणें आपस में समांतर हैं, इसलिए वे केवल अनंत पर मिलती हैं।',
  why_mirror_real: 'v ऋणात्मक है: प्रतिबिंब दर्पण के सामने है, जहाँ परावर्तित किरणें सच में मिलती हैं। इसलिए यह वास्तविक है।',
  why_mirror_virtual: 'v धनात्मक है: प्रतिबिंब दर्पण के पीछे है। किरणें केवल वहाँ से आती लगती हैं, इसलिए यह आभासी है।',
  why_lens_real: 'v धनात्मक है: प्रतिबिंब लेंस की दूसरी ओर है, जहाँ किरणें सच में मिलती हैं। इसलिए यह वास्तविक है।',
  why_lens_virtual: 'v ऋणात्मक है: प्रतिबिंब वस्तु की ओर ही है। किरणें केवल वहाँ से आती लगती हैं, इसलिए यह आभासी है।',
  why_m_neg: 'm ऋणात्मक है, इसलिए प्रतिबिंब उल्टा है।',
  why_m_pos: 'm धनात्मक है, इसलिए प्रतिबिंब सीधा है।',
  why_m_big: 'm का मान (चिह्न छोड़कर) 1 से अधिक है, इसलिए प्रतिबिंब बड़ा है।',
  why_m_small: 'm का मान (चिह्न छोड़कर) 1 से कम है, इसलिए प्रतिबिंब छोटा है।',
  why_m_same: 'm का मान (चिह्न छोड़कर) 1 है, इसलिए प्रतिबिंब वस्तु के बराबर है।',
  form_h: 'सूत्र से जाँचें',
  form_mirror: 'दर्पण सूत्र',
  form_lens: 'लेंस सूत्र',
  form_mag: 'आवर्धन',
  form_power: 'लेंस की क्षमता (f मीटर में, यानी f cm में हो तो 100/f)',
  table_h: 'NCERT तालिका: प्रतिबिंब कहाँ बनेगा?',
  table_tip: 'वस्तु को उस स्थिति पर रखने के लिए किसी पंक्ति पर टैप करें।',
  th_obj: 'वस्तु की स्थिति',
  th_img: 'प्रतिबिंब की स्थिति',
  th_size: 'प्रतिबिंब का आकार',
  th_nature: 'प्रतिबिंब की प्रकृति',
  nature_ri: 'वास्तविक तथा उल्टा',
  nature_ve: 'आभासी तथा सीधा',
  pos_inf: 'अनंत पर',
  pos_beyond_c: 'C से परे',
  pos_at_c: 'C पर',
  pos_c_f: 'C तथा F के बीच',
  pos_f_c: 'F तथा C के बीच',
  pos_at_f: 'F पर',
  pos_p_f: 'P तथा F के बीच',
  pos_behind: 'दर्पण के पीछे',
  pos_inf_p: 'अनंत तथा ध्रुव P के बीच',
  pos_behind_pf: 'दर्पण के पीछे, P तथा F के बीच',
  pos_behind_f: 'दर्पण के पीछे, F पर',
  pos_beyond_2f1: '2F₁ से परे',
  pos_at_2f1: '2F₁ पर',
  pos_f1_2f1: 'F₁ तथा 2F₁ के बीच',
  pos_at_f1: 'F₁ पर',
  pos_f1_o: 'F₁ तथा प्रकाशिक केंद्र O के बीच',
  pos_at_f2: 'F₂ पर',
  pos_f2_2f2: 'F₂ तथा 2F₂ के बीच',
  pos_at_2f2: '2F₂ पर',
  pos_beyond_2f2: '2F₂ से परे',
  pos_same_side: 'लेंस के उसी ओर, जिस ओर वस्तु है',
  pos_inf_o: 'अनंत तथा प्रकाशिक केंद्र O के बीच',
  sign_h: 'नई कार्तीय चिह्न परिपाटी',
  sign_1: 'हर दूरी दर्पण के ध्रुव P या लेंस के प्रकाशिक केंद्र O से मापें।',
  sign_2: 'प्रकाश बाईं ओर से आता है। दाईं ओर (प्रकाश की दिशा में) की दूरियाँ धनात्मक (+) और बाईं ओर की दूरियाँ ऋणात्मक (−) होती हैं।',
  sign_3: 'इसलिए यहाँ वस्तु की दूरी u हमेशा ऋणात्मक है।',
  sign_4: 'मुख्य अक्ष के ऊपर की ऊँचाई धनात्मक और नीचे की ऊँचाई ऋणात्मक होती है।',
  sign_5: 'अवतल दर्पण और अवतल लेंस के लिए f ऋणात्मक, तथा उत्तल दर्पण और उत्तल लेंस के लिए f धनात्मक होती है।',
  quiz_h: 'क्विज़: प्रतिबिंब का अनुमान लगाएँ',
  quiz_q: 'वस्तु की दूरी {u}, फोकस दूरी {f}। कैसा प्रतिबिंब बनेगा?',
  quiz_q_inf: 'वस्तु बहुत दूर (अनंत पर) है। फोकस दूरी {f}। कैसा प्रतिबिंब बनेगा?',
  q_pos: 'प्रतिबिंब की स्थिति',
  q_nature: 'वास्तविक या आभासी?',
  q_orient: 'सीधा या उल्टा?',
  q_size: 'प्रतिबिंब का आकार',
  q_choose: 'चुनें…',
  q_check: 'उत्तर जाँचें',
  q_next: 'नया प्रश्न',
  q_show: 'लैब में देखें',
  q_score: 'स्कोर: {a} / {b}',
  q_need: 'पहले चारों भागों का उत्तर दें।',
  q_right: 'शाबाश! चारों भाग सही हैं।',
  q_wrong: 'पूरा सही नहीं: 4 में से {n} भाग सही हैं। सही उत्तर नीचे देखें।',
  q_hint: 'यहाँ F दर्पण या लेंस से {f} पर और C (या 2F) {c} पर है।',
  uses_h: 'इनका उपयोग कहाँ होता है?',
  use_show: 'दिखाएँ',
  use_torch_t: 'टॉर्च और गाड़ी की हेडलाइट',
  use_torch_d: 'बल्ब अवतल दर्पण के फोकस पर रखा होता है, इसलिए प्रकाश तेज़ समांतर किरण-पुंज बनकर निकलता है।',
  use_solar_t: 'सौर कुकर और सौर भट्टी',
  use_solar_d: 'सूर्य का प्रकाश बहुत दूर से आता है, इसलिए अवतल दर्पण उसे अपने फोकस पर इकट्ठा करके बहुत गर्मी पैदा करता है।',
  use_shave_t: 'शेविंग और मेकअप दर्पण',
  use_shave_d: 'चेहरा अवतल दर्पण के P और F के बीच रखने पर सीधा और बड़ा प्रतिबिंब दिखता है।',
  use_rear_t: 'पीछे देखने वाला दर्पण',
  use_rear_d: 'उत्तल दर्पण हमेशा सीधा और छोटा प्रतिबिंब देता है और गाड़ी के पीछे का बड़ा हिस्सा दिखाता है।',
  use_mag_t: 'आवर्धक लेंस',
  use_mag_d: 'वस्तु को उत्तल लेंस के F₁ और O के बीच रखने पर सीधा, बड़ा और आभासी प्रतिबिंब मिलता है।',
  use_proj_t: 'प्रोजेक्टर',
  use_proj_d: 'स्लाइड उत्तल लेंस के F₁ और 2F₁ के बीच रखी होती है, इसलिए पर्दे पर बड़ा, वास्तविक और उल्टा प्रतिबिंब बनता है। इसी कारण स्लाइड उल्टी लगाई जाती है।',
  use_cam_t: 'कैमरा और हमारी आँख',
  use_cam_d: 'दूर की वस्तु (2F₁ से परे) सेंसर या रेटिना पर छोटा, वास्तविक और उल्टा प्रतिबिंब बनाती है।',
  use_spec_t: 'निकट-दृष्टि का चश्मा',
  use_spec_d: 'अवतल लेंस हमेशा आभासी, सीधा और छोटा प्रतिबिंब देता है। यह निकट-दृष्टि दोष वाले लोगों को दूर देखने में मदद करता है।',
  help_h: 'उपयोग कैसे करें / कक्षा के लिए सुझाव',
  help_1: 'दर्पण या लेंस चुनें, फिर नारंगी वस्तु को खींचें (या स्लाइडर खिसकाएँ)। किरणें, प्रतिबिंब और सारी संख्याएँ तुरंत बदलती हैं।',
  help_2: 'रंगीन बटनों से किरणें चालू या बंद करें। प्रतिबिंब ढूँढने के लिए कोई भी दो किरणें काफ़ी हैं; डैश वाली रेखाएँ बताती हैं कि किरणें कहाँ से आती लगती हैं।',
  help_3: 'u, v, f और m को उनके चिह्न के साथ पढ़ें। सूत्र वाला बॉक्स हर चरण दिखाता है, जिससे विद्यार्थी अपने संख्यात्मक प्रश्न जाँच सकते हैं।',
  help_4: 'NCERT तालिका की किसी पंक्ति पर टैप करके वस्तु को उस स्थिति पर ले जाएँ। पेज प्रिंट करने पर आरेख, हल और तालिका कागज़ पर मिल जाते हैं।',
  help_5: 'कक्षा गतिविधि: एक विद्यार्थी वस्तु खिसकाए और बाकी कक्षा देखने से पहले बोले — "वास्तविक या आभासी, सीधा या उल्टा, बड़ा या छोटा"। फिर टीमों में क्विज़ खेलें।',
  help_6: 'घर पर करके देखें: चमकदार स्टील के चम्मच में झाँकें। अंदर का भाग अवतल दर्पण और पीछे का भाग उत्तल दर्पण जैसा काम करता है।'
};
window.APP_STRINGS.bn = {
  app_title: 'লেন্স ও দর্পণ রশ্মি ল্যাব',
  intro: 'দর্পণ বা লেন্সের সামনে বস্তু সরান আর দেখুন রশ্মিগুলো কীভাবে প্রতিবিম্ব তৈরি করে। চিহ্নের নিয়ম, দর্পণ ও লেন্সের সূত্র এবং NCERT-এর প্রতিবিম্ব সারণি শিখুন।',
  dev_label: 'দর্পণ বা লেন্স বেছে নিন',
  dev_concave_mirror: 'অবতল দর্পণ',
  dev_convex_mirror: 'উত্তল দর্পণ',
  dev_convex_lens: 'উত্তল লেন্স',
  dev_concave_lens: 'অবতল লেন্স',
  canvas_label: 'রশ্মিচিত্র। বস্তুটি টেনে সরান, অথবা তীর-চাবি দিয়ে সরান।',
  drag_hint: 'কমলা রঙের বস্তুটি অক্ষ বরাবর টানুন, অথবা ছবিতে ক্লিক করে ← → চাবি চাপুন।',
  not_to_scale: 'রশ্মি পরিষ্কার দেখাতে উচ্চতাগুলো দূরত্বের চেয়ে বড় করে আঁকা হয়েছে।',
  rays_label: 'রশ্মি:',
  ray_par: 'অক্ষের সমান্তরাল',
  ray_c: 'C দিয়ে',
  ray_o: 'O দিয়ে',
  ray_f: 'F দিয়ে',
  ray_f1: 'F₁ দিয়ে',
  ray_f2: 'F₂-এর দিকে',
  ray_p: 'মেরু P-তে',
  ray_n: 'রশ্মি {n}',
  ray_miss: 'এই অবস্থানে কিছু রশ্মি দর্পণ বা লেন্সে পৌঁছায় না, তাই সেগুলো আঁকা হয়নি (ড্যাশ দেওয়া বোতাম)।',
  f_label: 'ফোকাস দূরত্ব |f|',
  u_label: 'বস্তুর দূরত্ব |u|',
  h_label: 'বস্তুর উচ্চতা h',
  far_btn: 'অনেক দূরে (∞)',
  save_png: 'ছবি সেভ করুন',
  lbl_object: 'বস্তু',
  lbl_image: 'প্রতিবিম্ব',
  light_dir: 'আলো',
  side_front: 'সামনে: সদ্ প্রতিবিম্ব',
  side_behind: 'পিছনে: অসদ্ প্রতিবিম্ব',
  side_obj: 'বস্তুর দিকে: অসদ্ প্রতিবিম্ব',
  side_other: 'অন্য দিকে: সদ্ প্রতিবিম্ব',
  note_point: 'বস্তুটি অনেক দূরে: রশ্মিগুলো সমান্তরালভাবে আসে এবং ফোকাসে বিন্দুর মতো প্রতিবিম্ব তৈরি করে।',
  note_inf_img: 'রশ্মিগুলো সমান্তরালভাবে বেরোয়, তাই প্রতিবিম্ব অসীমে তৈরি হয়।',
  note_off: 'প্রতিবিম্বটি ছবির বাইরে, v = {v}-তে।',
  res_h: 'ফলাফল (চিহ্নসহ)',
  r_u: 'বস্তুর দূরত্ব u',
  r_v: 'প্রতিবিম্বের দূরত্ব v',
  r_f: 'ফোকাস দূরত্ব f',
  r_m: 'বিবর্ধন m',
  r_h: 'বস্তুর উচ্চতা h',
  r_h2: 'প্রতিবিম্বের উচ্চতা h′',
  r_p: 'ক্ষমতা P',
  r_obj_pos: 'বস্তু:',
  r_img_pos: 'প্রতিবিম্ব:',
  nat_real: 'সদ্',
  nat_virtual: 'অসদ্',
  nat_inverted: 'অবশীর্ষ (উল্টো)',
  nat_erect: 'সমশীর্ষ (সোজা)',
  size_point: 'অত্যন্ত খর্বিত, বিন্দুর মতো',
  size_dim: 'খর্বিত (ছোট)',
  size_same: 'একই আকার',
  size_big: 'বিবর্ধিত (বড়)',
  size_huge: 'অত্যন্ত বিবর্ধিত',
  why_obj_inf: 'খুব দূরের বস্তু থেকে রশ্মি অক্ষের সমান্তরালে আসে, তাই সেগুলো ফোকাসে মেলে (বা সেখান থেকে আসছে মনে হয়)।',
  why_inf: 'বেরিয়ে আসা রশ্মিগুলো পরস্পর সমান্তরাল, তাই সেগুলো কেবল অসীমে মেলে।',
  why_mirror_real: 'v ঋণাত্মক: প্রতিবিম্ব দর্পণের সামনে, যেখানে প্রতিফলিত রশ্মি সত্যিই মেলে। তাই এটি সদ্।',
  why_mirror_virtual: 'v ধনাত্মক: প্রতিবিম্ব দর্পণের পিছনে। রশ্মি শুধু সেখান থেকে আসছে বলে মনে হয়, তাই এটি অসদ্।',
  why_lens_real: 'v ধনাত্মক: প্রতিবিম্ব লেন্সের অন্য দিকে, যেখানে রশ্মি সত্যিই মেলে। তাই এটি সদ্।',
  why_lens_virtual: 'v ঋণাত্মক: প্রতিবিম্ব বস্তুর দিকেই। রশ্মি শুধু সেখান থেকে আসছে বলে মনে হয়, তাই এটি অসদ্।',
  why_m_neg: 'm ঋণাত্মক, তাই প্রতিবিম্ব অবশীর্ষ (উল্টো)।',
  why_m_pos: 'm ধনাত্মক, তাই প্রতিবিম্ব সমশীর্ষ (সোজা)।',
  why_m_big: 'চিহ্ন বাদ দিয়ে m-এর মান 1-এর বেশি, তাই প্রতিবিম্ব বিবর্ধিত।',
  why_m_small: 'চিহ্ন বাদ দিয়ে m-এর মান 1-এর কম, তাই প্রতিবিম্ব খর্বিত।',
  why_m_same: 'চিহ্ন বাদ দিয়ে m-এর মান 1, তাই প্রতিবিম্ব বস্তুর সমান আকারের।',
  form_h: 'সূত্র দিয়ে যাচাই করুন',
  form_mirror: 'দর্পণের সূত্র',
  form_lens: 'লেন্সের সূত্র',
  form_mag: 'বিবর্ধন',
  form_power: 'লেন্সের ক্ষমতা (f মিটারে, অর্থাৎ f cm-এ হলে 100/f)',
  table_h: 'NCERT সারণি: প্রতিবিম্ব কোথায় হবে?',
  table_tip: 'বস্তুকে সেই অবস্থানে রাখতে কোনো সারিতে ট্যাপ করুন।',
  th_obj: 'বস্তুর অবস্থান',
  th_img: 'প্রতিবিম্বের অবস্থান',
  th_size: 'প্রতিবিম্বের আকার',
  th_nature: 'প্রতিবিম্বের প্রকৃতি',
  nature_ri: 'সদ্ ও অবশীর্ষ',
  nature_ve: 'অসদ্ ও সমশীর্ষ',
  pos_inf: 'অসীমে',
  pos_beyond_c: 'C-এর বাইরে',
  pos_at_c: 'C-তে',
  pos_c_f: 'C ও F-এর মধ্যে',
  pos_f_c: 'F ও C-এর মধ্যে',
  pos_at_f: 'F-এ',
  pos_p_f: 'P ও F-এর মধ্যে',
  pos_behind: 'দর্পণের পিছনে',
  pos_inf_p: 'অসীম ও মেরু P-এর মধ্যে',
  pos_behind_pf: 'দর্পণের পিছনে, P ও F-এর মধ্যে',
  pos_behind_f: 'দর্পণের পিছনে, F-এ',
  pos_beyond_2f1: '2F₁-এর বাইরে',
  pos_at_2f1: '2F₁-এ',
  pos_f1_2f1: 'F₁ ও 2F₁-এর মধ্যে',
  pos_at_f1: 'F₁-এ',
  pos_f1_o: 'F₁ ও আলোক কেন্দ্র O-এর মধ্যে',
  pos_at_f2: 'F₂-তে',
  pos_f2_2f2: 'F₂ ও 2F₂-এর মধ্যে',
  pos_at_2f2: '2F₂-তে',
  pos_beyond_2f2: '2F₂-এর বাইরে',
  pos_same_side: 'লেন্সের যে দিকে বস্তু, সেই দিকেই',
  pos_inf_o: 'অসীম ও আলোক কেন্দ্র O-এর মধ্যে',
  sign_h: 'নতুন কার্তেসীয় চিহ্নের নিয়ম',
  sign_1: 'সব দূরত্ব দর্পণের মেরু P বা লেন্সের আলোক কেন্দ্র O থেকে মাপুন।',
  sign_2: 'আলো বাঁ দিক থেকে আসে। ডান দিকের (আলোর অভিমুখে) দূরত্ব ধনাত্মক (+), বাঁ দিকের দূরত্ব ঋণাত্মক (−)।',
  sign_3: 'তাই এখানে বস্তুর দূরত্ব u সবসময় ঋণাত্মক।',
  sign_4: 'প্রধান অক্ষের উপরের উচ্চতা ধনাত্মক, নিচের উচ্চতা ঋণাত্মক।',
  sign_5: 'অবতল দর্পণ ও অবতল লেন্সের f ঋণাত্মক; উত্তল দর্পণ ও উত্তল লেন্সের f ধনাত্মক।',
  quiz_h: 'কুইজ: প্রতিবিম্ব অনুমান করুন',
  quiz_q: 'বস্তুর দূরত্ব {u}, ফোকাস দূরত্ব {f}। কেমন প্রতিবিম্ব তৈরি হবে?',
  quiz_q_inf: 'বস্তুটি অনেক দূরে (অসীমে)। ফোকাস দূরত্ব {f}। কেমন প্রতিবিম্ব তৈরি হবে?',
  q_pos: 'প্রতিবিম্বের অবস্থান',
  q_nature: 'সদ্ না অসদ্?',
  q_orient: 'সমশীর্ষ না অবশীর্ষ?',
  q_size: 'প্রতিবিম্বের আকার',
  q_choose: 'বেছে নিন…',
  q_check: 'উত্তর যাচাই করুন',
  q_next: 'নতুন প্রশ্ন',
  q_show: 'ল্যাবে দেখুন',
  q_score: 'স্কোর: {a} / {b}',
  q_need: 'আগে চারটি অংশেরই উত্তর দিন।',
  q_right: 'দারুণ! চারটি অংশই ঠিক।',
  q_wrong: 'পুরোপুরি ঠিক নয়: 4টির মধ্যে {n}টি অংশ ঠিক। নিচে সঠিক উত্তর দেখুন।',
  q_hint: 'এখানে দর্পণ বা লেন্স থেকে F আছে {f} দূরে, আর C (বা 2F) আছে {c} দূরে।',
  uses_h: 'এগুলো কোথায় ব্যবহার হয়?',
  use_show: 'দেখান',
  use_torch_t: 'টর্চ ও গাড়ির হেডলাইট',
  use_torch_d: 'বাল্বটি অবতল দর্পণের ফোকাসে থাকে, তাই আলো জোরালো সমান্তরাল রশ্মিগুচ্ছ হয়ে বেরোয়।',
  use_solar_t: 'সৌর কুকার ও সৌর চুল্লি',
  use_solar_d: 'সূর্যের আলো অনেক দূর থেকে আসে, তাই অবতল দর্পণ তাকে ফোকাসে জড়ো করে খুব গরম করে তোলে।',
  use_shave_t: 'দাড়ি কামানো ও মেকআপের আয়না',
  use_shave_d: 'অবতল দর্পণের P ও F-এর মধ্যে মুখ রাখলে সোজা ও বড় প্রতিবিম্ব দেখা যায়।',
  use_rear_t: 'গাড়ির পিছন দেখার আয়না',
  use_rear_d: 'উত্তল দর্পণ সবসময় সোজা ও ছোট প্রতিবিম্ব দেয় এবং গাড়ির পিছনের অনেকটা জায়গা দেখায়।',
  use_mag_t: 'বিবর্ধক কাচ (আতশ কাচ)',
  use_mag_d: 'উত্তল লেন্সের F₁ ও O-এর মধ্যে বস্তু রাখলে সোজা, বড়, অসদ্ প্রতিবিম্ব পাওয়া যায়।',
  use_proj_t: 'প্রজেক্টর',
  use_proj_d: 'স্লাইডটি উত্তল লেন্সের F₁ ও 2F₁-এর মধ্যে থাকে, তাই পর্দায় বড়, সদ্, উল্টো প্রতিবিম্ব পড়ে। এজন্যই স্লাইড উল্টো করে বসানো হয়।',
  use_cam_t: 'ক্যামেরা ও আমাদের চোখ',
  use_cam_d: 'দূরের বস্তু (2F₁-এর বাইরে) সেন্সর বা রেটিনায় ছোট, সদ্, উল্টো প্রতিবিম্ব তৈরি করে।',
  use_spec_t: 'ক্ষীণদৃষ্টির চশমা',
  use_spec_d: 'অবতল লেন্স সবসময় অসদ্, সোজা, ছোট প্রতিবিম্ব দেয়। এটি মায়োপিয়া থাকা মানুষকে দূরে দেখতে সাহায্য করে।',
  help_h: 'কীভাবে ব্যবহার করবেন / ক্লাসের জন্য ভাবনা',
  help_1: 'দর্পণ বা লেন্স বেছে নিন, তারপর কমলা বস্তুটি টানুন (বা স্লাইডার সরান)। রশ্মি, প্রতিবিম্ব আর সব সংখ্যা সঙ্গে সঙ্গে বদলায়।',
  help_2: 'রঙিন বোতাম দিয়ে রশ্মি চালু বা বন্ধ করুন। প্রতিবিম্ব খুঁজতে যেকোনো দুটি রশ্মিই যথেষ্ট; ড্যাশ রেখা দেখায় রশ্মি কোথা থেকে আসছে বলে মনে হয়।',
  help_3: 'u, v, f ও m চিহ্নসহ পড়ুন। সূত্রের বাক্সে প্রতিটি ধাপ দেখানো আছে, তাই ছাত্রছাত্রীরা নিজেদের অঙ্ক মিলিয়ে নিতে পারে।',
  help_4: 'NCERT সারণির কোনো সারিতে ট্যাপ করলে বস্তু সেই অবস্থানে চলে যায়। পাতা প্রিন্ট করলে রশ্মিচিত্র, সমাধান আর সারণি কাগজে পাবেন।',
  help_5: 'ক্লাসের কাজ: একজন ছাত্র বস্তু সরাবে, বাকিরা দেখার আগে বলবে "সদ্ না অসদ্, সোজা না উল্টো, বড় না ছোট"। তারপর দলে ভাগ হয়ে কুইজ খেলুন।',
  help_6: 'বাড়িতে চেষ্টা করুন: চকচকে স্টিলের চামচে তাকান। ভেতরের দিক অবতল দর্পণের মতো আর পিছনের দিক উত্তল দর্পণের মতো কাজ করে।'
};
window.APP_STRINGS.mr = {
  app_title: 'भिंग व आरसा किरण लॅब',
  intro: 'आरसा किंवा भिंगासमोर वस्तू सरकवा आणि किरण प्रतिमा कशी तयार करतात ते पाहा. चिन्ह संकेत, आरसा व भिंगाची सूत्रे आणि NCERT चे प्रतिमा तक्ते शिका.',
  dev_label: 'आरसा किंवा भिंग निवडा',
  dev_concave_mirror: 'अंतर्गोल आरसा',
  dev_convex_mirror: 'बहिर्गोल आरसा',
  dev_convex_lens: 'बहिर्गोल भिंग',
  dev_concave_lens: 'अंतर्गोल भिंग',
  canvas_label: 'किरण आकृती. वस्तू ओढा किंवा बाण-कळांनी सरकवा.',
  drag_hint: 'नारिंगी वस्तू अक्षावर ओढा, किंवा चित्रावर क्लिक करून ← → कळा दाबा.',
  not_to_scale: 'किरण स्पष्ट दिसावेत म्हणून उंची अंतरांपेक्षा मोठी काढली आहे.',
  rays_label: 'किरण:',
  ray_par: 'अक्षाला समांतर',
  ray_c: 'C मधून',
  ray_o: 'O मधून',
  ray_f: 'F मधून',
  ray_f1: 'F₁ मधून',
  ray_f2: 'F₂ च्या दिशेने',
  ray_p: 'ध्रुव P वर',
  ray_n: 'किरण {n}',
  ray_miss: 'या स्थितीत काही किरण आरशापर्यंत किंवा भिंगापर्यंत पोहोचत नाहीत, म्हणून ते काढलेले नाहीत (डॅश असलेली बटणे).',
  f_label: 'नाभीय अंतर |f|',
  u_label: 'वस्तूचे अंतर |u|',
  h_label: 'वस्तूची उंची h',
  far_btn: 'खूप दूर (∞)',
  save_png: 'चित्र सेव्ह करा',
  lbl_object: 'वस्तू',
  lbl_image: 'प्रतिमा',
  light_dir: 'प्रकाश',
  side_front: 'समोर: वास्तव प्रतिमा',
  side_behind: 'मागे: आभासी प्रतिमा',
  side_obj: 'वस्तूच्या बाजूला: आभासी प्रतिमा',
  side_other: 'दुसऱ्या बाजूला: वास्तव प्रतिमा',
  note_point: 'वस्तू खूप दूर आहे: किरण समांतर येतात आणि नाभीवर बिंदूएवढी प्रतिमा तयार करतात.',
  note_inf_img: 'किरण समांतर बाहेर पडतात, म्हणून प्रतिमा अनंत अंतरावर तयार होते.',
  note_off: 'प्रतिमा चित्राबाहेर आहे, v = {v} वर.',
  res_h: 'निकाल (चिन्हांसह)',
  r_u: 'वस्तूचे अंतर u',
  r_v: 'प्रतिमेचे अंतर v',
  r_f: 'नाभीय अंतर f',
  r_m: 'विशालन m',
  r_h: 'वस्तूची उंची h',
  r_h2: 'प्रतिमेची उंची h′',
  r_p: 'शक्ती P',
  r_obj_pos: 'वस्तू:',
  r_img_pos: 'प्रतिमा:',
  nat_real: 'वास्तव',
  nat_virtual: 'आभासी',
  nat_inverted: 'उलटी',
  nat_erect: 'सुलट',
  size_point: 'अतिशय लहान, बिंदूएवढी',
  size_dim: 'लहान',
  size_same: 'समान आकाराची',
  size_big: 'मोठी (विशालित)',
  size_huge: 'अतिशय मोठी',
  why_obj_inf: 'खूप दूरच्या वस्तूकडून किरण अक्षाला समांतर येतात, म्हणून ते नाभीवर मिळतात (किंवा तिथून आल्यासारखे वाटतात).',
  why_inf: 'बाहेर पडणारे किरण एकमेकांना समांतर आहेत, म्हणून ते फक्त अनंत अंतरावर मिळतात.',
  why_mirror_real: 'v ऋण आहे: प्रतिमा आरशासमोर आहे, जिथे परावर्तित किरण खरोखर मिळतात. म्हणून ती वास्तव आहे.',
  why_mirror_virtual: 'v धन आहे: प्रतिमा आरशामागे आहे. किरण फक्त तिथून आल्यासारखे वाटतात, म्हणून ती आभासी आहे.',
  why_lens_real: 'v धन आहे: प्रतिमा भिंगाच्या दुसऱ्या बाजूला आहे, जिथे किरण खरोखर मिळतात. म्हणून ती वास्तव आहे.',
  why_lens_virtual: 'v ऋण आहे: प्रतिमा वस्तूच्याच बाजूला आहे. किरण फक्त तिथून आल्यासारखे वाटतात, म्हणून ती आभासी आहे.',
  why_m_neg: 'm ऋण आहे, म्हणून प्रतिमा उलटी आहे.',
  why_m_pos: 'm धन आहे, म्हणून प्रतिमा सुलट आहे.',
  why_m_big: 'चिन्ह सोडून m ची किंमत 1 पेक्षा जास्त आहे, म्हणून प्रतिमा मोठी आहे.',
  why_m_small: 'चिन्ह सोडून m ची किंमत 1 पेक्षा कमी आहे, म्हणून प्रतिमा लहान आहे.',
  why_m_same: 'चिन्ह सोडून m ची किंमत 1 आहे, म्हणून प्रतिमा वस्तूएवढीच आहे.',
  form_h: 'सूत्राने तपासा',
  form_mirror: 'आरशाचे सूत्र',
  form_lens: 'भिंगाचे सूत्र',
  form_mag: 'विशालन',
  form_power: 'भिंगाची शक्ती (f मीटरमध्ये, म्हणजे f cm मध्ये असल्यास 100/f)',
  table_h: 'NCERT तक्ता: प्रतिमा कुठे तयार होईल?',
  table_tip: 'वस्तू त्या स्थानी ठेवण्यासाठी एखाद्या ओळीवर टॅप करा.',
  th_obj: 'वस्तूचे स्थान',
  th_img: 'प्रतिमेचे स्थान',
  th_size: 'प्रतिमेचा आकार',
  th_nature: 'प्रतिमेचे स्वरूप',
  nature_ri: 'वास्तव व उलटी',
  nature_ve: 'आभासी व सुलट',
  pos_inf: 'अनंत अंतरावर',
  pos_beyond_c: 'C च्या पलीकडे',
  pos_at_c: 'C वर',
  pos_c_f: 'C आणि F यांच्या दरम्यान',
  pos_f_c: 'F आणि C यांच्या दरम्यान',
  pos_at_f: 'F वर',
  pos_p_f: 'P आणि F यांच्या दरम्यान',
  pos_behind: 'आरशामागे',
  pos_inf_p: 'अनंत अंतर आणि ध्रुव P यांच्या दरम्यान',
  pos_behind_pf: 'आरशामागे, P आणि F यांच्या दरम्यान',
  pos_behind_f: 'आरशामागे, F वर',
  pos_beyond_2f1: '2F₁ च्या पलीकडे',
  pos_at_2f1: '2F₁ वर',
  pos_f1_2f1: 'F₁ आणि 2F₁ यांच्या दरम्यान',
  pos_at_f1: 'F₁ वर',
  pos_f1_o: 'F₁ आणि प्रकाशीय मध्य O यांच्या दरम्यान',
  pos_at_f2: 'F₂ वर',
  pos_f2_2f2: 'F₂ आणि 2F₂ यांच्या दरम्यान',
  pos_at_2f2: '2F₂ वर',
  pos_beyond_2f2: '2F₂ च्या पलीकडे',
  pos_same_side: 'भिंगाच्या ज्या बाजूला वस्तू आहे, त्याच बाजूला',
  pos_inf_o: 'अनंत अंतर आणि प्रकाशीय मध्य O यांच्या दरम्यान',
  sign_h: 'नवीन कार्टेशियन चिन्ह संकेत',
  sign_1: 'प्रत्येक अंतर आरशाच्या ध्रुव P पासून किंवा भिंगाच्या प्रकाशीय मध्य O पासून मोजा.',
  sign_2: 'प्रकाश डावीकडून येतो. उजवीकडील (प्रकाशाच्या दिशेने) अंतरे धन (+) आणि डावीकडील अंतरे ऋण (−) असतात.',
  sign_3: 'म्हणून इथे वस्तूचे अंतर u नेहमी ऋण असते.',
  sign_4: 'मुख्य अक्षाच्या वरची उंची धन आणि खालची उंची ऋण असते.',
  sign_5: 'अंतर्गोल आरसा व अंतर्गोल भिंगासाठी f ऋण, तर बहिर्गोल आरसा व बहिर्गोल भिंगासाठी f धन असते.',
  quiz_h: 'प्रश्नमंजूषा: प्रतिमेचा अंदाज लावा',
  quiz_q: 'वस्तूचे अंतर {u}, नाभीय अंतर {f}. कशी प्रतिमा तयार होईल?',
  quiz_q_inf: 'वस्तू खूप दूर (अनंत अंतरावर) आहे. नाभीय अंतर {f}. कशी प्रतिमा तयार होईल?',
  q_pos: 'प्रतिमेचे स्थान',
  q_nature: 'वास्तव की आभासी?',
  q_orient: 'सुलट की उलटी?',
  q_size: 'प्रतिमेचा आकार',
  q_choose: 'निवडा…',
  q_check: 'उत्तर तपासा',
  q_next: 'नवीन प्रश्न',
  q_show: 'लॅबमध्ये पाहा',
  q_score: 'गुण: {a} / {b}',
  q_need: 'आधी चारही भागांची उत्तरे द्या.',
  q_right: 'छान! चारही भाग बरोबर आहेत.',
  q_wrong: 'पूर्ण बरोबर नाही: 4 पैकी {n} भाग बरोबर. खाली योग्य उत्तर पाहा.',
  q_hint: 'इथे आरसा किंवा भिंगापासून F {f} वर आणि C (किंवा 2F) {c} वर आहे.',
  uses_h: 'यांचा उपयोग कुठे होतो?',
  use_show: 'दाखवा',
  use_torch_t: 'टॉर्च आणि गाडीचे हेडलाइट',
  use_torch_d: 'बल्ब अंतर्गोल आरशाच्या नाभीवर असतो, म्हणून प्रकाश प्रखर समांतर झोत बनून बाहेर पडतो.',
  use_solar_t: 'सौर कुकर आणि सौर भट्टी',
  use_solar_d: 'सूर्यप्रकाश खूप दूरून येतो, म्हणून अंतर्गोल आरसा तो नाभीवर एकत्र करून खूप उष्णता निर्माण करतो.',
  use_shave_t: 'दाढीचा आणि मेकअपचा आरसा',
  use_shave_d: 'चेहरा अंतर्गोल आरशाच्या P आणि F दरम्यान ठेवल्यास सुलट आणि मोठी प्रतिमा दिसते.',
  use_rear_t: 'मागचे पाहण्याचा आरसा',
  use_rear_d: 'बहिर्गोल आरसा नेहमी सुलट आणि लहान प्रतिमा देतो आणि वाहनामागचा मोठा भाग दाखवतो.',
  use_mag_t: 'साधा सूक्ष्मदर्शक (भिंग)',
  use_mag_d: 'वस्तू बहिर्गोल भिंगाच्या F₁ आणि O दरम्यान ठेवल्यास सुलट, मोठी, आभासी प्रतिमा मिळते.',
  use_proj_t: 'प्रोजेक्टर',
  use_proj_d: 'स्लाइड बहिर्गोल भिंगाच्या F₁ आणि 2F₁ दरम्यान असते, म्हणून पडद्यावर मोठी, वास्तव, उलटी प्रतिमा पडते. म्हणूनच स्लाइड उलटी लावतात.',
  use_cam_t: 'कॅमेरा आणि आपला डोळा',
  use_cam_d: 'दूरची वस्तू (2F₁ च्या पलीकडे) सेन्सरवर किंवा दृष्टिपटलावर लहान, वास्तव, उलटी प्रतिमा तयार करते.',
  use_spec_t: 'निकटदृष्टितेचा चष्मा',
  use_spec_d: 'अंतर्गोल भिंग नेहमी आभासी, सुलट, लहान प्रतिमा देते. ते निकटदृष्टिता असलेल्या लोकांना दूरचे पाहण्यास मदत करते.',
  help_h: 'कसे वापरावे / वर्गासाठी कल्पना',
  help_1: 'आरसा किंवा भिंग निवडा, मग नारिंगी वस्तू ओढा (किंवा स्लायडर सरकवा). किरण, प्रतिमा आणि सर्व संख्या लगेच बदलतात.',
  help_2: 'रंगीत बटणांनी किरण चालू किंवा बंद करा. प्रतिमा शोधण्यासाठी कोणतेही दोन किरण पुरेसे असतात; डॅश रेषा दाखवतात की किरण कुठून आल्यासारखे वाटतात.',
  help_3: 'u, v, f आणि m त्यांच्या चिन्हांसह वाचा. सूत्राच्या चौकटीत प्रत्येक पायरी दिसते, त्यामुळे विद्यार्थी आपली उदाहरणे तपासू शकतात.',
  help_4: 'NCERT तक्त्यातील एखाद्या ओळीवर टॅप करून वस्तू त्या स्थानी न्या. पान प्रिंट केल्यास आकृती, उकल आणि तक्ता कागदावर मिळतो.',
  help_5: 'वर्ग उपक्रम: एक विद्यार्थी वस्तू सरकवतो आणि बाकीचा वर्ग पाहण्याआधी सांगतो, "वास्तव की आभासी, सुलट की उलटी, मोठी की लहान". मग गटांमध्ये प्रश्नमंजूषा खेळा.',
  help_6: 'घरी करून पाहा: चमकदार स्टीलच्या चमच्यात पाहा. आतली बाजू अंतर्गोल आरशासारखी आणि मागची बाजू बहिर्गोल आरशासारखी काम करते.'
};
window.APP_STRINGS.gu = {
  app_title: 'લેન્સ અને અરીસા કિરણ લૅબ',
  intro: 'અરીસા કે લેન્સની સામે વસ્તુ ખસેડો અને જુઓ કે કિરણો પ્રતિબિંબ કેવી રીતે બનાવે છે. સંજ્ઞા પ્રણાલી, અરીસા અને લેન્સનાં સૂત્રો તથા NCERTનાં પ્રતિબિંબ કોષ્ટકો શીખો.',
  dev_label: 'અરીસો કે લેન્સ પસંદ કરો',
  dev_concave_mirror: 'અંતર્ગોળ અરીસો',
  dev_convex_mirror: 'બહિર્ગોળ અરીસો',
  dev_convex_lens: 'બહિર્ગોળ લેન્સ',
  dev_concave_lens: 'અંતર્ગોળ લેન્સ',
  canvas_label: 'કિરણાકૃતિ. વસ્તુને ખેંચો અથવા તીર-કી વડે ખસેડો.',
  drag_hint: 'નારંગી વસ્તુને અક્ષ પર ખેંચો, અથવા ચિત્ર પર ક્લિક કરીને ← → કી દબાવો.',
  not_to_scale: 'કિરણો સ્પષ્ટ દેખાય તે માટે ઊંચાઈ અંતર કરતાં મોટી દોરી છે.',
  rays_label: 'કિરણો:',
  ray_par: 'અક્ષને સમાંતર',
  ray_c: 'C માંથી',
  ray_o: 'O માંથી',
  ray_f: 'F માંથી',
  ray_f1: 'F₁ માંથી',
  ray_f2: 'F₂ તરફ',
  ray_p: 'ધ્રુવ P પર',
  ray_n: 'કિરણ {n}',
  ray_miss: 'આ સ્થાને કેટલાંક કિરણો અરીસા કે લેન્સ સુધી પહોંચતાં નથી, તેથી તે દોર્યાં નથી (ડૅશવાળાં બટન).',
  f_label: 'કેન્દ્રલંબાઈ |f|',
  u_label: 'વસ્તુનું અંતર |u|',
  h_label: 'વસ્તુની ઊંચાઈ h',
  far_btn: 'ખૂબ દૂર (∞)',
  save_png: 'ચિત્ર સેવ કરો',
  lbl_object: 'વસ્તુ',
  lbl_image: 'પ્રતિબિંબ',
  light_dir: 'પ્રકાશ',
  side_front: 'આગળ: વાસ્તવિક પ્રતિબિંબ',
  side_behind: 'પાછળ: આભાસી પ્રતિબિંબ',
  side_obj: 'વસ્તુ તરફ: આભાસી પ્રતિબિંબ',
  side_other: 'બીજી બાજુ: વાસ્તવિક પ્રતિબિંબ',
  note_point: 'વસ્તુ ખૂબ દૂર છે: કિરણો સમાંતર આવે છે અને મુખ્ય કેન્દ્ર પર બિંદુ જેવડું પ્રતિબિંબ બનાવે છે.',
  note_inf_img: 'કિરણો સમાંતર બહાર નીકળે છે, તેથી પ્રતિબિંબ અનંત અંતરે બને છે.',
  note_off: 'પ્રતિબિંબ ચિત્રની બહાર છે, v = {v} પર.',
  res_h: 'પરિણામ (સંજ્ઞા સાથે)',
  r_u: 'વસ્તુનું અંતર u',
  r_v: 'પ્રતિબિંબનું અંતર v',
  r_f: 'કેન્દ્રલંબાઈ f',
  r_m: 'મોટવણી m',
  r_h: 'વસ્તુની ઊંચાઈ h',
  r_h2: 'પ્રતિબિંબની ઊંચાઈ h′',
  r_p: 'પાવર P',
  r_obj_pos: 'વસ્તુ:',
  r_img_pos: 'પ્રતિબિંબ:',
  nat_real: 'વાસ્તવિક',
  nat_virtual: 'આભાસી',
  nat_inverted: 'ઊલટું',
  nat_erect: 'ચત્તું',
  size_point: 'ખૂબ જ નાનું, બિંદુવત્',
  size_dim: 'નાનું',
  size_same: 'સમાન કદનું',
  size_big: 'મોટું',
  size_huge: 'ખૂબ જ મોટું',
  why_obj_inf: 'ખૂબ દૂરની વસ્તુમાંથી કિરણો અક્ષને સમાંતર આવે છે, તેથી તે મુખ્ય કેન્દ્ર પર મળે છે (અથવા ત્યાંથી આવતાં લાગે છે).',
  why_inf: 'બહાર નીકળતાં કિરણો એકબીજાને સમાંતર છે, તેથી તે ફક્ત અનંત અંતરે મળે છે.',
  why_mirror_real: 'v ઋણ છે: પ્રતિબિંબ અરીસાની સામે છે, જ્યાં પરાવર્તિત કિરણો ખરેખર મળે છે. તેથી તે વાસ્તવિક છે.',
  why_mirror_virtual: 'v ધન છે: પ્રતિબિંબ અરીસાની પાછળ છે. કિરણો ફક્ત ત્યાંથી આવતાં લાગે છે, તેથી તે આભાસી છે.',
  why_lens_real: 'v ધન છે: પ્રતિબિંબ લેન્સની બીજી બાજુ છે, જ્યાં કિરણો ખરેખર મળે છે. તેથી તે વાસ્તવિક છે.',
  why_lens_virtual: 'v ઋણ છે: પ્રતિબિંબ વસ્તુની બાજુએ જ છે. કિરણો ફક્ત ત્યાંથી આવતાં લાગે છે, તેથી તે આભાસી છે.',
  why_m_neg: 'm ઋણ છે, તેથી પ્રતિબિંબ ઊલટું છે.',
  why_m_pos: 'm ધન છે, તેથી પ્રતિબિંબ ચત્તું છે.',
  why_m_big: 'સંજ્ઞા છોડીને m નું મૂલ્ય 1 કરતાં વધુ છે, તેથી પ્રતિબિંબ મોટું છે.',
  why_m_small: 'સંજ્ઞા છોડીને m નું મૂલ્ય 1 કરતાં ઓછું છે, તેથી પ્રતિબિંબ નાનું છે.',
  why_m_same: 'સંજ્ઞા છોડીને m નું મૂલ્ય 1 છે, તેથી પ્રતિબિંબ વસ્તુ જેટલું જ છે.',
  form_h: 'સૂત્રથી ચકાસો',
  form_mirror: 'અરીસાનું સૂત્ર',
  form_lens: 'લેન્સનું સૂત્ર',
  form_mag: 'મોટવણી',
  form_power: 'લેન્સનો પાવર (f મીટરમાં, એટલે કે f cm માં હોય તો 100/f)',
  table_h: 'NCERT કોષ્ટક: પ્રતિબિંબ ક્યાં બનશે?',
  table_tip: 'વસ્તુને તે સ્થાને મૂકવા માટે કોઈ હરોળ પર ટૅપ કરો.',
  th_obj: 'વસ્તુનું સ્થાન',
  th_img: 'પ્રતિબિંબનું સ્થાન',
  th_size: 'પ્રતિબિંબનું કદ',
  th_nature: 'પ્રતિબિંબનો પ્રકાર',
  nature_ri: 'વાસ્તવિક અને ઊલટું',
  nature_ve: 'આભાસી અને ચત્તું',
  pos_inf: 'અનંત અંતરે',
  pos_beyond_c: 'C થી દૂર',
  pos_at_c: 'C પર',
  pos_c_f: 'C અને F ની વચ્ચે',
  pos_f_c: 'F અને C ની વચ્ચે',
  pos_at_f: 'F પર',
  pos_p_f: 'P અને F ની વચ્ચે',
  pos_behind: 'અરીસાની પાછળ',
  pos_inf_p: 'અનંત અને ધ્રુવ P ની વચ્ચે',
  pos_behind_pf: 'અરીસાની પાછળ, P અને F ની વચ્ચે',
  pos_behind_f: 'અરીસાની પાછળ, F પર',
  pos_beyond_2f1: '2F₁ થી દૂર',
  pos_at_2f1: '2F₁ પર',
  pos_f1_2f1: 'F₁ અને 2F₁ ની વચ્ચે',
  pos_at_f1: 'F₁ પર',
  pos_f1_o: 'F₁ અને પ્રકાશીય કેન્દ્ર O ની વચ્ચે',
  pos_at_f2: 'F₂ પર',
  pos_f2_2f2: 'F₂ અને 2F₂ ની વચ્ચે',
  pos_at_2f2: '2F₂ પર',
  pos_beyond_2f2: '2F₂ થી દૂર',
  pos_same_side: 'લેન્સની જે બાજુ વસ્તુ છે, તે જ બાજુ',
  pos_inf_o: 'અનંત અને પ્રકાશીય કેન્દ્ર O ની વચ્ચે',
  sign_h: 'નવી કાર્તેઝિયન સંજ્ઞા પ્રણાલી',
  sign_1: 'દરેક અંતર અરીસાના ધ્રુવ P અથવા લેન્સના પ્રકાશીય કેન્દ્ર O થી માપો.',
  sign_2: 'પ્રકાશ ડાબી બાજુથી આવે છે. જમણી બાજુનાં (પ્રકાશની દિશામાં) અંતરો ધન (+) અને ડાબી બાજુનાં અંતરો ઋણ (−) છે.',
  sign_3: 'તેથી અહીં વસ્તુનું અંતર u હંમેશાં ઋણ છે.',
  sign_4: 'મુખ્ય અક્ષની ઉપરની ઊંચાઈ ધન અને નીચેની ઊંચાઈ ઋણ છે.',
  sign_5: 'અંતર્ગોળ અરીસા અને અંતર્ગોળ લેન્સ માટે f ઋણ, જ્યારે બહિર્ગોળ અરીસા અને બહિર્ગોળ લેન્સ માટે f ધન છે.',
  quiz_h: 'ક્વિઝ: પ્રતિબિંબનું અનુમાન કરો',
  quiz_q: 'વસ્તુનું અંતર {u}, કેન્દ્રલંબાઈ {f}. કેવું પ્રતિબિંબ બનશે?',
  quiz_q_inf: 'વસ્તુ ખૂબ દૂર (અનંત અંતરે) છે. કેન્દ્રલંબાઈ {f}. કેવું પ્રતિબિંબ બનશે?',
  q_pos: 'પ્રતિબિંબનું સ્થાન',
  q_nature: 'વાસ્તવિક કે આભાસી?',
  q_orient: 'ચત્તું કે ઊલટું?',
  q_size: 'પ્રતિબિંબનું કદ',
  q_choose: 'પસંદ કરો…',
  q_check: 'જવાબ ચકાસો',
  q_next: 'નવો પ્રશ્ન',
  q_show: 'લૅબમાં જુઓ',
  q_score: 'સ્કોર: {a} / {b}',
  q_need: 'પહેલાં ચારેય ભાગના જવાબ આપો.',
  q_right: 'શાબાશ! ચારેય ભાગ સાચા છે.',
  q_wrong: 'પૂરું સાચું નથી: 4 માંથી {n} ભાગ સાચા છે. નીચે સાચો જવાબ જુઓ.',
  q_hint: 'અહીં અરીસા કે લેન્સથી F {f} પર અને C (અથવા 2F) {c} પર છે.',
  uses_h: 'આનો ઉપયોગ ક્યાં થાય છે?',
  use_show: 'બતાવો',
  use_torch_t: 'ટૉર્ચ અને વાહનની હેડલાઇટ',
  use_torch_d: 'બલ્બ અંતર્ગોળ અરીસાના મુખ્ય કેન્દ્ર પર હોય છે, તેથી પ્રકાશ તેજસ્વી સમાંતર પુંજ બનીને બહાર નીકળે છે.',
  use_solar_t: 'સૌર કૂકર અને સૌર ભઠ્ઠી',
  use_solar_d: 'સૂર્યપ્રકાશ ખૂબ દૂરથી આવે છે, તેથી અંતર્ગોળ અરીસો તેને મુખ્ય કેન્દ્ર પર ભેગો કરીને ખૂબ ગરમી પેદા કરે છે.',
  use_shave_t: 'દાઢી કરવાનો અને મેકઅપનો અરીસો',
  use_shave_d: 'ચહેરો અંતર્ગોળ અરીસાના P અને F ની વચ્ચે રાખવાથી ચત્તું અને મોટું પ્રતિબિંબ દેખાય છે.',
  use_rear_t: 'પાછળ જોવાનો અરીસો',
  use_rear_d: 'બહિર્ગોળ અરીસો હંમેશાં ચત્તું અને નાનું પ્રતિબિંબ આપે છે અને વાહનની પાછળનો મોટો વિસ્તાર બતાવે છે.',
  use_mag_t: 'બિલોરી કાચ',
  use_mag_d: 'વસ્તુને બહિર્ગોળ લેન્સના F₁ અને O ની વચ્ચે રાખવાથી ચત્તું, મોટું, આભાસી પ્રતિબિંબ મળે છે.',
  use_proj_t: 'પ્રોજેક્ટર',
  use_proj_d: 'સ્લાઇડ બહિર્ગોળ લેન્સના F₁ અને 2F₁ ની વચ્ચે હોય છે, તેથી પડદા પર મોટું, વાસ્તવિક, ઊલટું પ્રતિબિંબ પડે છે. એટલે જ સ્લાઇડ ઊંધી મૂકવામાં આવે છે.',
  use_cam_t: 'કૅમેરા અને આપણી આંખ',
  use_cam_d: 'દૂરની વસ્તુ (2F₁ થી દૂર) સેન્સર કે નેત્રપટલ પર નાનું, વાસ્તવિક, ઊલટું પ્રતિબિંબ બનાવે છે.',
  use_spec_t: 'લઘુદૃષ્ટિનાં ચશ્માં',
  use_spec_d: 'અંતર્ગોળ લેન્સ હંમેશાં આભાસી, ચત્તું, નાનું પ્રતિબિંબ આપે છે. તે લઘુદૃષ્ટિ ધરાવતા લોકોને દૂરનું જોવામાં મદદ કરે છે.',
  help_h: 'કેવી રીતે વાપરવું / વર્ગખંડ માટે વિચારો',
  help_1: 'અરીસો કે લેન્સ પસંદ કરો, પછી નારંગી વસ્તુને ખેંચો (અથવા સ્લાઇડર ખસેડો). કિરણો, પ્રતિબિંબ અને બધી સંખ્યાઓ તરત બદલાય છે.',
  help_2: 'રંગીન બટનોથી કિરણો ચાલુ કે બંધ કરો. પ્રતિબિંબ શોધવા કોઈ પણ બે કિરણો પૂરતાં છે; ડૅશ રેખાઓ બતાવે છે કે કિરણો ક્યાંથી આવતાં લાગે છે.',
  help_3: 'u, v, f અને m ને તેમની સંજ્ઞા સાથે વાંચો. સૂત્રના ખાનામાં દરેક પગલું દેખાય છે, તેથી વિદ્યાર્થીઓ પોતાના દાખલા ચકાસી શકે છે.',
  help_4: 'NCERT કોષ્ટકની કોઈ હરોળ પર ટૅપ કરીને વસ્તુને તે સ્થાને લઈ જાઓ. પાનું પ્રિન્ટ કરવાથી આકૃતિ, ઉકેલ અને કોષ્ટક કાગળ પર મળે છે.',
  help_5: 'વર્ગ પ્રવૃત્તિ: એક વિદ્યાર્થી વસ્તુ ખસેડે અને બાકીનો વર્ગ જોતાં પહેલાં બોલે, "વાસ્તવિક કે આભાસી, ચત્તું કે ઊલટું, મોટું કે નાનું". પછી ટુકડીઓમાં ક્વિઝ રમો.',
  help_6: 'ઘરે કરી જુઓ: ચળકતી સ્ટીલની ચમચીમાં જુઓ. અંદરની બાજુ અંતર્ગોળ અરીસાની જેમ અને પાછળની બાજુ બહિર્ગોળ અરીસાની જેમ કામ કરે છે.'
};
window.APP_STRINGS.pa = {
  app_title: 'ਲੈਂਜ਼ ਅਤੇ ਦਰਪਣ ਕਿਰਨ ਲੈਬ',
  intro: 'ਦਰਪਣ ਜਾਂ ਲੈਂਜ਼ ਦੇ ਸਾਹਮਣੇ ਵਸਤੂ ਖਿਸਕਾਓ ਅਤੇ ਵੇਖੋ ਕਿ ਕਿਰਨਾਂ ਪ੍ਰਤੀਬਿੰਬ ਕਿਵੇਂ ਬਣਾਉਂਦੀਆਂ ਹਨ। ਚਿੰਨ੍ਹ ਪਰੰਪਰਾ, ਦਰਪਣ ਅਤੇ ਲੈਂਜ਼ ਦੇ ਸੂਤਰ ਅਤੇ NCERT ਦੀਆਂ ਪ੍ਰਤੀਬਿੰਬ ਸਾਰਣੀਆਂ ਸਿੱਖੋ।',
  dev_label: 'ਦਰਪਣ ਜਾਂ ਲੈਂਜ਼ ਚੁਣੋ',
  dev_concave_mirror: 'ਅਵਤਲ ਦਰਪਣ',
  dev_convex_mirror: 'ਉੱਤਲ ਦਰਪਣ',
  dev_convex_lens: 'ਉੱਤਲ ਲੈਂਜ਼',
  dev_concave_lens: 'ਅਵਤਲ ਲੈਂਜ਼',
  canvas_label: 'ਕਿਰਨ ਚਿੱਤਰ। ਵਸਤੂ ਨੂੰ ਖਿੱਚੋ ਜਾਂ ਤੀਰ ਵਾਲੀਆਂ ਕੁੰਜੀਆਂ ਨਾਲ ਖਿਸਕਾਓ।',
  drag_hint: 'ਸੰਤਰੀ ਵਸਤੂ ਨੂੰ ਧੁਰੇ ਉੱਤੇ ਖਿੱਚੋ, ਜਾਂ ਚਿੱਤਰ ਉੱਤੇ ਕਲਿੱਕ ਕਰਕੇ ← → ਕੁੰਜੀਆਂ ਦਬਾਓ।',
  not_to_scale: 'ਕਿਰਨਾਂ ਸਾਫ਼ ਦਿਸਣ, ਇਸ ਲਈ ਉਚਾਈਆਂ ਦੂਰੀਆਂ ਨਾਲੋਂ ਵੱਡੀਆਂ ਬਣਾਈਆਂ ਗਈਆਂ ਹਨ।',
  rays_label: 'ਕਿਰਨਾਂ:',
  ray_par: 'ਧੁਰੇ ਦੇ ਸਮਾਂਤਰ',
  ray_c: 'C ਵਿੱਚੋਂ',
  ray_o: 'O ਵਿੱਚੋਂ',
  ray_f: 'F ਵਿੱਚੋਂ',
  ray_f1: 'F₁ ਵਿੱਚੋਂ',
  ray_f2: 'F₂ ਵੱਲ',
  ray_p: 'ਧਰੁਵ P ਉੱਤੇ',
  ray_n: 'ਕਿਰਨ {n}',
  ray_miss: 'ਇਸ ਸਥਿਤੀ ਵਿੱਚ ਕੁਝ ਕਿਰਨਾਂ ਦਰਪਣ ਜਾਂ ਲੈਂਜ਼ ਤੱਕ ਨਹੀਂ ਪਹੁੰਚਦੀਆਂ, ਇਸ ਲਈ ਉਹ ਨਹੀਂ ਬਣਾਈਆਂ ਗਈਆਂ (ਡੈਸ਼ ਵਾਲੇ ਬਟਨ)।',
  f_label: 'ਫੋਕਸ ਦੂਰੀ |f|',
  u_label: 'ਵਸਤੂ ਦੀ ਦੂਰੀ |u|',
  h_label: 'ਵਸਤੂ ਦੀ ਉਚਾਈ h',
  far_btn: 'ਬਹੁਤ ਦੂਰ (∞)',
  save_png: 'ਚਿੱਤਰ ਸੇਵ ਕਰੋ',
  lbl_object: 'ਵਸਤੂ',
  lbl_image: 'ਪ੍ਰਤੀਬਿੰਬ',
  light_dir: 'ਪ੍ਰਕਾਸ਼',
  side_front: 'ਸਾਹਮਣੇ: ਵਾਸਤਵਿਕ ਪ੍ਰਤੀਬਿੰਬ',
  side_behind: 'ਪਿੱਛੇ: ਆਭਾਸੀ ਪ੍ਰਤੀਬਿੰਬ',
  side_obj: 'ਵਸਤੂ ਵਾਲੇ ਪਾਸੇ: ਆਭਾਸੀ ਪ੍ਰਤੀਬਿੰਬ',
  side_other: 'ਦੂਜੇ ਪਾਸੇ: ਵਾਸਤਵਿਕ ਪ੍ਰਤੀਬਿੰਬ',
  note_point: 'ਵਸਤੂ ਬਹੁਤ ਦੂਰ ਹੈ: ਕਿਰਨਾਂ ਸਮਾਂਤਰ ਆਉਂਦੀਆਂ ਹਨ ਅਤੇ ਫੋਕਸ ਉੱਤੇ ਬਿੰਦੂ ਜਿੰਨਾ ਪ੍ਰਤੀਬਿੰਬ ਬਣਾਉਂਦੀਆਂ ਹਨ।',
  note_inf_img: 'ਕਿਰਨਾਂ ਸਮਾਂਤਰ ਨਿਕਲਦੀਆਂ ਹਨ, ਇਸ ਲਈ ਪ੍ਰਤੀਬਿੰਬ ਅਨੰਤ ਉੱਤੇ ਬਣਦਾ ਹੈ।',
  note_off: 'ਪ੍ਰਤੀਬਿੰਬ ਚਿੱਤਰ ਤੋਂ ਬਾਹਰ ਹੈ, v = {v} ਉੱਤੇ।',
  res_h: 'ਨਤੀਜੇ (ਚਿੰਨ੍ਹਾਂ ਸਮੇਤ)',
  r_u: 'ਵਸਤੂ ਦੀ ਦੂਰੀ u',
  r_v: 'ਪ੍ਰਤੀਬਿੰਬ ਦੀ ਦੂਰੀ v',
  r_f: 'ਫੋਕਸ ਦੂਰੀ f',
  r_m: 'ਵਡਦਰਸ਼ਨ m',
  r_h: 'ਵਸਤੂ ਦੀ ਉਚਾਈ h',
  r_h2: 'ਪ੍ਰਤੀਬਿੰਬ ਦੀ ਉਚਾਈ h′',
  r_p: 'ਸ਼ਕਤੀ P',
  r_obj_pos: 'ਵਸਤੂ:',
  r_img_pos: 'ਪ੍ਰਤੀਬਿੰਬ:',
  nat_real: 'ਵਾਸਤਵਿਕ',
  nat_virtual: 'ਆਭਾਸੀ',
  nat_inverted: 'ਉਲਟਾ',
  nat_erect: 'ਸਿੱਧਾ',
  size_point: 'ਬਹੁਤ ਛੋਟਾ, ਬਿੰਦੂ ਜਿੰਨਾ',
  size_dim: 'ਛੋਟਾ',
  size_same: 'ਬਰਾਬਰ ਆਕਾਰ',
  size_big: 'ਵੱਡਾ',
  size_huge: 'ਬਹੁਤ ਵੱਡਾ',
  why_obj_inf: 'ਬਹੁਤ ਦੂਰ ਦੀ ਵਸਤੂ ਤੋਂ ਕਿਰਨਾਂ ਧੁਰੇ ਦੇ ਸਮਾਂਤਰ ਆਉਂਦੀਆਂ ਹਨ, ਇਸ ਲਈ ਉਹ ਫੋਕਸ ਉੱਤੇ ਮਿਲਦੀਆਂ ਹਨ (ਜਾਂ ਉੱਥੋਂ ਆਉਂਦੀਆਂ ਲੱਗਦੀਆਂ ਹਨ)।',
  why_inf: 'ਨਿਕਲਣ ਵਾਲੀਆਂ ਕਿਰਨਾਂ ਆਪਸ ਵਿੱਚ ਸਮਾਂਤਰ ਹਨ, ਇਸ ਲਈ ਉਹ ਸਿਰਫ਼ ਅਨੰਤ ਉੱਤੇ ਮਿਲਦੀਆਂ ਹਨ।',
  why_mirror_real: 'v ਰਿਣਾਤਮਕ ਹੈ: ਪ੍ਰਤੀਬਿੰਬ ਦਰਪਣ ਦੇ ਸਾਹਮਣੇ ਹੈ, ਜਿੱਥੇ ਪਰਾਵਰਤਿਤ ਕਿਰਨਾਂ ਸੱਚਮੁੱਚ ਮਿਲਦੀਆਂ ਹਨ। ਇਸ ਲਈ ਇਹ ਵਾਸਤਵਿਕ ਹੈ।',
  why_mirror_virtual: 'v ਧਨਾਤਮਕ ਹੈ: ਪ੍ਰਤੀਬਿੰਬ ਦਰਪਣ ਦੇ ਪਿੱਛੇ ਹੈ। ਕਿਰਨਾਂ ਸਿਰਫ਼ ਉੱਥੋਂ ਆਉਂਦੀਆਂ ਲੱਗਦੀਆਂ ਹਨ, ਇਸ ਲਈ ਇਹ ਆਭਾਸੀ ਹੈ।',
  why_lens_real: 'v ਧਨਾਤਮਕ ਹੈ: ਪ੍ਰਤੀਬਿੰਬ ਲੈਂਜ਼ ਦੇ ਦੂਜੇ ਪਾਸੇ ਹੈ, ਜਿੱਥੇ ਕਿਰਨਾਂ ਸੱਚਮੁੱਚ ਮਿਲਦੀਆਂ ਹਨ। ਇਸ ਲਈ ਇਹ ਵਾਸਤਵਿਕ ਹੈ।',
  why_lens_virtual: 'v ਰਿਣਾਤਮਕ ਹੈ: ਪ੍ਰਤੀਬਿੰਬ ਵਸਤੂ ਵਾਲੇ ਪਾਸੇ ਹੀ ਹੈ। ਕਿਰਨਾਂ ਸਿਰਫ਼ ਉੱਥੋਂ ਆਉਂਦੀਆਂ ਲੱਗਦੀਆਂ ਹਨ, ਇਸ ਲਈ ਇਹ ਆਭਾਸੀ ਹੈ।',
  why_m_neg: 'm ਰਿਣਾਤਮਕ ਹੈ, ਇਸ ਲਈ ਪ੍ਰਤੀਬਿੰਬ ਉਲਟਾ ਹੈ।',
  why_m_pos: 'm ਧਨਾਤਮਕ ਹੈ, ਇਸ ਲਈ ਪ੍ਰਤੀਬਿੰਬ ਸਿੱਧਾ ਹੈ।',
  why_m_big: 'ਚਿੰਨ੍ਹ ਛੱਡ ਕੇ m ਦਾ ਮੁੱਲ 1 ਤੋਂ ਵੱਧ ਹੈ, ਇਸ ਲਈ ਪ੍ਰਤੀਬਿੰਬ ਵੱਡਾ ਹੈ।',
  why_m_small: 'ਚਿੰਨ੍ਹ ਛੱਡ ਕੇ m ਦਾ ਮੁੱਲ 1 ਤੋਂ ਘੱਟ ਹੈ, ਇਸ ਲਈ ਪ੍ਰਤੀਬਿੰਬ ਛੋਟਾ ਹੈ।',
  why_m_same: 'ਚਿੰਨ੍ਹ ਛੱਡ ਕੇ m ਦਾ ਮੁੱਲ 1 ਹੈ, ਇਸ ਲਈ ਪ੍ਰਤੀਬਿੰਬ ਵਸਤੂ ਦੇ ਬਰਾਬਰ ਹੈ।',
  form_h: 'ਸੂਤਰ ਨਾਲ ਜਾਂਚੋ',
  form_mirror: 'ਦਰਪਣ ਸੂਤਰ',
  form_lens: 'ਲੈਂਜ਼ ਸੂਤਰ',
  form_mag: 'ਵਡਦਰਸ਼ਨ',
  form_power: 'ਲੈਂਜ਼ ਦੀ ਸ਼ਕਤੀ (f ਮੀਟਰ ਵਿੱਚ, ਭਾਵ f cm ਵਿੱਚ ਹੋਵੇ ਤਾਂ 100/f)',
  table_h: 'NCERT ਸਾਰਣੀ: ਪ੍ਰਤੀਬਿੰਬ ਕਿੱਥੇ ਬਣੇਗਾ?',
  table_tip: 'ਵਸਤੂ ਨੂੰ ਉਸ ਸਥਿਤੀ ਉੱਤੇ ਰੱਖਣ ਲਈ ਕਿਸੇ ਕਤਾਰ ਉੱਤੇ ਟੈਪ ਕਰੋ।',
  th_obj: 'ਵਸਤੂ ਦੀ ਸਥਿਤੀ',
  th_img: 'ਪ੍ਰਤੀਬਿੰਬ ਦੀ ਸਥਿਤੀ',
  th_size: 'ਪ੍ਰਤੀਬਿੰਬ ਦਾ ਆਕਾਰ',
  th_nature: 'ਪ੍ਰਤੀਬਿੰਬ ਦੀ ਪ੍ਰਕਿਰਤੀ',
  nature_ri: 'ਵਾਸਤਵਿਕ ਅਤੇ ਉਲਟਾ',
  nature_ve: 'ਆਭਾਸੀ ਅਤੇ ਸਿੱਧਾ',
  pos_inf: 'ਅਨੰਤ ਉੱਤੇ',
  pos_beyond_c: 'C ਤੋਂ ਪਰੇ',
  pos_at_c: 'C ਉੱਤੇ',
  pos_c_f: 'C ਅਤੇ F ਦੇ ਵਿਚਕਾਰ',
  pos_f_c: 'F ਅਤੇ C ਦੇ ਵਿਚਕਾਰ',
  pos_at_f: 'F ਉੱਤੇ',
  pos_p_f: 'P ਅਤੇ F ਦੇ ਵਿਚਕਾਰ',
  pos_behind: 'ਦਰਪਣ ਦੇ ਪਿੱਛੇ',
  pos_inf_p: 'ਅਨੰਤ ਅਤੇ ਧਰੁਵ P ਦੇ ਵਿਚਕਾਰ',
  pos_behind_pf: 'ਦਰਪਣ ਦੇ ਪਿੱਛੇ, P ਅਤੇ F ਦੇ ਵਿਚਕਾਰ',
  pos_behind_f: 'ਦਰਪਣ ਦੇ ਪਿੱਛੇ, F ਉੱਤੇ',
  pos_beyond_2f1: '2F₁ ਤੋਂ ਪਰੇ',
  pos_at_2f1: '2F₁ ਉੱਤੇ',
  pos_f1_2f1: 'F₁ ਅਤੇ 2F₁ ਦੇ ਵਿਚਕਾਰ',
  pos_at_f1: 'F₁ ਉੱਤੇ',
  pos_f1_o: 'F₁ ਅਤੇ ਪ੍ਰਕਾਸ਼ੀ ਕੇਂਦਰ O ਦੇ ਵਿਚਕਾਰ',
  pos_at_f2: 'F₂ ਉੱਤੇ',
  pos_f2_2f2: 'F₂ ਅਤੇ 2F₂ ਦੇ ਵਿਚਕਾਰ',
  pos_at_2f2: '2F₂ ਉੱਤੇ',
  pos_beyond_2f2: '2F₂ ਤੋਂ ਪਰੇ',
  pos_same_side: 'ਲੈਂਜ਼ ਦੇ ਉਸੇ ਪਾਸੇ ਜਿੱਥੇ ਵਸਤੂ ਹੈ',
  pos_inf_o: 'ਅਨੰਤ ਅਤੇ ਪ੍ਰਕਾਸ਼ੀ ਕੇਂਦਰ O ਦੇ ਵਿਚਕਾਰ',
  sign_h: 'ਨਵੀਂ ਕਾਰਟੀਜ਼ੀਅਨ ਚਿੰਨ੍ਹ ਪਰੰਪਰਾ',
  sign_1: 'ਹਰ ਦੂਰੀ ਦਰਪਣ ਦੇ ਧਰੁਵ P ਜਾਂ ਲੈਂਜ਼ ਦੇ ਪ੍ਰਕਾਸ਼ੀ ਕੇਂਦਰ O ਤੋਂ ਮਾਪੋ।',
  sign_2: 'ਪ੍ਰਕਾਸ਼ ਖੱਬੇ ਪਾਸਿਓਂ ਆਉਂਦਾ ਹੈ। ਸੱਜੇ ਪਾਸੇ (ਪ੍ਰਕਾਸ਼ ਦੀ ਦਿਸ਼ਾ ਵਿੱਚ) ਦੀਆਂ ਦੂਰੀਆਂ ਧਨਾਤਮਕ (+) ਅਤੇ ਖੱਬੇ ਪਾਸੇ ਦੀਆਂ ਦੂਰੀਆਂ ਰਿਣਾਤਮਕ (−) ਹੁੰਦੀਆਂ ਹਨ।',
  sign_3: 'ਇਸ ਲਈ ਇੱਥੇ ਵਸਤੂ ਦੀ ਦੂਰੀ u ਹਮੇਸ਼ਾ ਰਿਣਾਤਮਕ ਹੈ।',
  sign_4: 'ਮੁੱਖ ਧੁਰੇ ਤੋਂ ਉੱਪਰ ਦੀ ਉਚਾਈ ਧਨਾਤਮਕ ਅਤੇ ਹੇਠਾਂ ਦੀ ਉਚਾਈ ਰਿਣਾਤਮਕ ਹੁੰਦੀ ਹੈ।',
  sign_5: 'ਅਵਤਲ ਦਰਪਣ ਅਤੇ ਅਵਤਲ ਲੈਂਜ਼ ਲਈ f ਰਿਣਾਤਮਕ, ਅਤੇ ਉੱਤਲ ਦਰਪਣ ਅਤੇ ਉੱਤਲ ਲੈਂਜ਼ ਲਈ f ਧਨਾਤਮਕ ਹੁੰਦੀ ਹੈ।',
  quiz_h: 'ਕਵਿਜ਼: ਪ੍ਰਤੀਬਿੰਬ ਦਾ ਅੰਦਾਜ਼ਾ ਲਗਾਓ',
  quiz_q: 'ਵਸਤੂ ਦੀ ਦੂਰੀ {u}, ਫੋਕਸ ਦੂਰੀ {f}। ਕਿਹੋ ਜਿਹਾ ਪ੍ਰਤੀਬਿੰਬ ਬਣੇਗਾ?',
  quiz_q_inf: 'ਵਸਤੂ ਬਹੁਤ ਦੂਰ (ਅਨੰਤ ਉੱਤੇ) ਹੈ। ਫੋਕਸ ਦੂਰੀ {f}। ਕਿਹੋ ਜਿਹਾ ਪ੍ਰਤੀਬਿੰਬ ਬਣੇਗਾ?',
  q_pos: 'ਪ੍ਰਤੀਬਿੰਬ ਦੀ ਸਥਿਤੀ',
  q_nature: 'ਵਾਸਤਵਿਕ ਜਾਂ ਆਭਾਸੀ?',
  q_orient: 'ਸਿੱਧਾ ਜਾਂ ਉਲਟਾ?',
  q_size: 'ਪ੍ਰਤੀਬਿੰਬ ਦਾ ਆਕਾਰ',
  q_choose: 'ਚੁਣੋ…',
  q_check: 'ਉੱਤਰ ਜਾਂਚੋ',
  q_next: 'ਨਵਾਂ ਸਵਾਲ',
  q_show: 'ਲੈਬ ਵਿੱਚ ਵੇਖੋ',
  q_score: 'ਸਕੋਰ: {a} / {b}',
  q_need: 'ਪਹਿਲਾਂ ਚਾਰੇ ਭਾਗਾਂ ਦਾ ਉੱਤਰ ਦਿਓ।',
  q_right: 'ਸ਼ਾਬਾਸ਼! ਚਾਰੇ ਭਾਗ ਸਹੀ ਹਨ।',
  q_wrong: 'ਪੂਰਾ ਸਹੀ ਨਹੀਂ: 4 ਵਿੱਚੋਂ {n} ਭਾਗ ਸਹੀ ਹਨ। ਹੇਠਾਂ ਸਹੀ ਉੱਤਰ ਵੇਖੋ।',
  q_hint: 'ਇੱਥੇ ਦਰਪਣ ਜਾਂ ਲੈਂਜ਼ ਤੋਂ F {f} ਉੱਤੇ ਅਤੇ C (ਜਾਂ 2F) {c} ਉੱਤੇ ਹੈ।',
  uses_h: 'ਇਨ੍ਹਾਂ ਦੀ ਵਰਤੋਂ ਕਿੱਥੇ ਹੁੰਦੀ ਹੈ?',
  use_show: 'ਵਿਖਾਓ',
  use_torch_t: 'ਟਾਰਚ ਅਤੇ ਗੱਡੀ ਦੀਆਂ ਹੈੱਡਲਾਈਟਾਂ',
  use_torch_d: 'ਬੱਲਬ ਅਵਤਲ ਦਰਪਣ ਦੇ ਫੋਕਸ ਉੱਤੇ ਹੁੰਦਾ ਹੈ, ਇਸ ਲਈ ਪ੍ਰਕਾਸ਼ ਤੇਜ਼ ਸਮਾਂਤਰ ਕਿਰਨ-ਪੁੰਜ ਬਣ ਕੇ ਨਿਕਲਦਾ ਹੈ।',
  use_solar_t: 'ਸੂਰਜੀ ਕੁੱਕਰ ਅਤੇ ਸੂਰਜੀ ਭੱਠੀ',
  use_solar_d: 'ਸੂਰਜ ਦਾ ਪ੍ਰਕਾਸ਼ ਬਹੁਤ ਦੂਰੋਂ ਆਉਂਦਾ ਹੈ, ਇਸ ਲਈ ਅਵਤਲ ਦਰਪਣ ਉਸਨੂੰ ਫੋਕਸ ਉੱਤੇ ਇਕੱਠਾ ਕਰਕੇ ਬਹੁਤ ਗਰਮੀ ਪੈਦਾ ਕਰਦਾ ਹੈ।',
  use_shave_t: 'ਸ਼ੇਵ ਅਤੇ ਮੇਕਅੱਪ ਵਾਲਾ ਸ਼ੀਸ਼ਾ',
  use_shave_d: 'ਚਿਹਰਾ ਅਵਤਲ ਦਰਪਣ ਦੇ P ਅਤੇ F ਦੇ ਵਿਚਕਾਰ ਰੱਖਣ ਨਾਲ ਸਿੱਧਾ ਅਤੇ ਵੱਡਾ ਪ੍ਰਤੀਬਿੰਬ ਦਿਸਦਾ ਹੈ।',
  use_rear_t: 'ਪਿੱਛੇ ਵੇਖਣ ਵਾਲਾ ਸ਼ੀਸ਼ਾ',
  use_rear_d: 'ਉੱਤਲ ਦਰਪਣ ਹਮੇਸ਼ਾ ਸਿੱਧਾ ਅਤੇ ਛੋਟਾ ਪ੍ਰਤੀਬਿੰਬ ਦਿੰਦਾ ਹੈ ਅਤੇ ਗੱਡੀ ਦੇ ਪਿੱਛੇ ਦਾ ਵੱਡਾ ਹਿੱਸਾ ਵਿਖਾਉਂਦਾ ਹੈ।',
  use_mag_t: 'ਵੱਡਦਰਸ਼ੀ ਸ਼ੀਸ਼ਾ',
  use_mag_d: 'ਵਸਤੂ ਨੂੰ ਉੱਤਲ ਲੈਂਜ਼ ਦੇ F₁ ਅਤੇ O ਦੇ ਵਿਚਕਾਰ ਰੱਖਣ ਨਾਲ ਸਿੱਧਾ, ਵੱਡਾ, ਆਭਾਸੀ ਪ੍ਰਤੀਬਿੰਬ ਮਿਲਦਾ ਹੈ।',
  use_proj_t: 'ਪ੍ਰੋਜੈਕਟਰ',
  use_proj_d: 'ਸਲਾਈਡ ਉੱਤਲ ਲੈਂਜ਼ ਦੇ F₁ ਅਤੇ 2F₁ ਦੇ ਵਿਚਕਾਰ ਹੁੰਦੀ ਹੈ, ਇਸ ਲਈ ਪਰਦੇ ਉੱਤੇ ਵੱਡਾ, ਵਾਸਤਵਿਕ, ਉਲਟਾ ਪ੍ਰਤੀਬਿੰਬ ਪੈਂਦਾ ਹੈ। ਇਸੇ ਲਈ ਸਲਾਈਡ ਉਲਟੀ ਲਾਈ ਜਾਂਦੀ ਹੈ।',
  use_cam_t: 'ਕੈਮਰਾ ਅਤੇ ਸਾਡੀ ਅੱਖ',
  use_cam_d: 'ਦੂਰ ਦੀ ਵਸਤੂ (2F₁ ਤੋਂ ਪਰੇ) ਸੈਂਸਰ ਜਾਂ ਰੈਟਿਨਾ ਉੱਤੇ ਛੋਟਾ, ਵਾਸਤਵਿਕ, ਉਲਟਾ ਪ੍ਰਤੀਬਿੰਬ ਬਣਾਉਂਦੀ ਹੈ।',
  use_spec_t: 'ਨਿਕਟ-ਦ੍ਰਿਸ਼ਟੀ ਦੀ ਐਨਕ',
  use_spec_d: 'ਅਵਤਲ ਲੈਂਜ਼ ਹਮੇਸ਼ਾ ਆਭਾਸੀ, ਸਿੱਧਾ, ਛੋਟਾ ਪ੍ਰਤੀਬਿੰਬ ਦਿੰਦਾ ਹੈ। ਇਹ ਨਿਕਟ-ਦ੍ਰਿਸ਼ਟੀ ਦੋਸ਼ ਵਾਲੇ ਲੋਕਾਂ ਨੂੰ ਦੂਰ ਵੇਖਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',
  help_h: 'ਕਿਵੇਂ ਵਰਤੀਏ / ਕਲਾਸ ਲਈ ਸੁਝਾਅ',
  help_1: 'ਦਰਪਣ ਜਾਂ ਲੈਂਜ਼ ਚੁਣੋ, ਫਿਰ ਸੰਤਰੀ ਵਸਤੂ ਨੂੰ ਖਿੱਚੋ (ਜਾਂ ਸਲਾਈਡਰ ਖਿਸਕਾਓ)। ਕਿਰਨਾਂ, ਪ੍ਰਤੀਬਿੰਬ ਅਤੇ ਸਾਰੇ ਅੰਕ ਤੁਰੰਤ ਬਦਲਦੇ ਹਨ।',
  help_2: 'ਰੰਗੀਨ ਬਟਨਾਂ ਨਾਲ ਕਿਰਨਾਂ ਚਾਲੂ ਜਾਂ ਬੰਦ ਕਰੋ। ਪ੍ਰਤੀਬਿੰਬ ਲੱਭਣ ਲਈ ਕੋਈ ਵੀ ਦੋ ਕਿਰਨਾਂ ਕਾਫ਼ੀ ਹਨ; ਡੈਸ਼ ਵਾਲੀਆਂ ਰੇਖਾਵਾਂ ਦੱਸਦੀਆਂ ਹਨ ਕਿ ਕਿਰਨਾਂ ਕਿੱਥੋਂ ਆਉਂਦੀਆਂ ਲੱਗਦੀਆਂ ਹਨ।',
  help_3: 'u, v, f ਅਤੇ m ਨੂੰ ਉਨ੍ਹਾਂ ਦੇ ਚਿੰਨ੍ਹਾਂ ਸਮੇਤ ਪੜ੍ਹੋ। ਸੂਤਰ ਵਾਲੇ ਡੱਬੇ ਵਿੱਚ ਹਰ ਕਦਮ ਦਿਸਦਾ ਹੈ, ਇਸ ਲਈ ਵਿਦਿਆਰਥੀ ਆਪਣੇ ਸਵਾਲ ਜਾਂਚ ਸਕਦੇ ਹਨ।',
  help_4: 'NCERT ਸਾਰਣੀ ਦੀ ਕਿਸੇ ਕਤਾਰ ਉੱਤੇ ਟੈਪ ਕਰਕੇ ਵਸਤੂ ਨੂੰ ਉਸ ਸਥਿਤੀ ਉੱਤੇ ਲੈ ਜਾਓ। ਸਫ਼ਾ ਪ੍ਰਿੰਟ ਕਰਨ ਨਾਲ ਚਿੱਤਰ, ਹੱਲ ਅਤੇ ਸਾਰਣੀ ਕਾਗਜ਼ ਉੱਤੇ ਮਿਲ ਜਾਂਦੇ ਹਨ।',
  help_5: 'ਕਲਾਸ ਗਤੀਵਿਧੀ: ਇੱਕ ਵਿਦਿਆਰਥੀ ਵਸਤੂ ਖਿਸਕਾਏ ਅਤੇ ਬਾਕੀ ਕਲਾਸ ਵੇਖਣ ਤੋਂ ਪਹਿਲਾਂ ਬੋਲੇ, "ਵਾਸਤਵਿਕ ਜਾਂ ਆਭਾਸੀ, ਸਿੱਧਾ ਜਾਂ ਉਲਟਾ, ਵੱਡਾ ਜਾਂ ਛੋਟਾ"। ਫਿਰ ਟੀਮਾਂ ਵਿੱਚ ਕਵਿਜ਼ ਖੇਡੋ।',
  help_6: 'ਘਰ ਵਿੱਚ ਕਰਕੇ ਵੇਖੋ: ਚਮਕਦੇ ਸਟੀਲ ਦੇ ਚਮਚੇ ਵਿੱਚ ਵੇਖੋ। ਅੰਦਰਲਾ ਪਾਸਾ ਅਵਤਲ ਦਰਪਣ ਵਾਂਗ ਅਤੇ ਪਿਛਲਾ ਪਾਸਾ ਉੱਤਲ ਦਰਪਣ ਵਾਂਗ ਕੰਮ ਕਰਦਾ ਹੈ।'
};
window.APP_STRINGS.or = {
  app_title: 'ଲେନ୍ସ ଓ ଦର୍ପଣ ରଶ୍ମି ଲ୍ୟାବ୍',
  intro: 'ଦର୍ପଣ ବା ଲେନ୍ସ ସାମ୍ନାରେ ବସ୍ତୁକୁ ଘୁଞ୍ଚାନ୍ତୁ ଏବଂ ଦେଖନ୍ତୁ ରଶ୍ମିଗୁଡ଼ିକ କିପରି ପ୍ରତିବିମ୍ବ ତିଆରି କରନ୍ତି। ଚିହ୍ନ ନିୟମ, ଦର୍ପଣ ଓ ଲେନ୍ସ ସୂତ୍ର ଏବଂ NCERTର ପ୍ରତିବିମ୍ବ ସାରଣୀ ଶିଖନ୍ତୁ।',
  dev_label: 'ଦର୍ପଣ ବା ଲେନ୍ସ ବାଛନ୍ତୁ',
  dev_concave_mirror: 'ଅବତଳ ଦର୍ପଣ',
  dev_convex_mirror: 'ଉତ୍ତଳ ଦର୍ପଣ',
  dev_convex_lens: 'ଉତ୍ତଳ ଲେନ୍ସ',
  dev_concave_lens: 'ଅବତଳ ଲେନ୍ସ',
  canvas_label: 'ରଶ୍ମି ଚିତ୍ର। ବସ୍ତୁକୁ ଟାଣନ୍ତୁ କିମ୍ବା ତୀର ଚାବି ଦ୍ୱାରା ଘୁଞ୍ଚାନ୍ତୁ।',
  drag_hint: 'କମଳା ରଙ୍ଗର ବସ୍ତୁକୁ ଅକ୍ଷ ଉପରେ ଟାଣନ୍ତୁ, କିମ୍ବା ଚିତ୍ରରେ କ୍ଲିକ୍ କରି ← → ଚାବି ଦବାନ୍ତୁ।',
  not_to_scale: 'ରଶ୍ମି ସ୍ପଷ୍ଟ ଦେଖାଯିବା ପାଇଁ ଉଚ୍ଚତାକୁ ଦୂରତାଠାରୁ ବଡ଼ କରି ଅଙ୍କାଯାଇଛି।',
  rays_label: 'ରଶ୍ମି:',
  ray_par: 'ଅକ୍ଷ ସହ ସମାନ୍ତର',
  ray_c: 'C ଦେଇ',
  ray_o: 'O ଦେଇ',
  ray_f: 'F ଦେଇ',
  ray_f1: 'F₁ ଦେଇ',
  ray_f2: 'F₂ ଆଡ଼କୁ',
  ray_p: 'ମେରୁ P ଉପରେ',
  ray_n: 'ରଶ୍ମି {n}',
  ray_miss: 'ଏହି ସ୍ଥିତିରେ କିଛି ରଶ୍ମି ଦର୍ପଣ ବା ଲେନ୍ସ ପର୍ଯ୍ୟନ୍ତ ପହଞ୍ଚେ ନାହିଁ, ତେଣୁ ସେଗୁଡ଼ିକ ଅଙ୍କାଯାଇନାହିଁ (ଡ୍ୟାସ୍ ଥିବା ବଟନ୍)।',
  f_label: 'ଫୋକସ ଦୂରତା |f|',
  u_label: 'ବସ୍ତୁର ଦୂରତା |u|',
  h_label: 'ବସ୍ତୁର ଉଚ୍ଚତା h',
  far_btn: 'ବହୁତ ଦୂର (∞)',
  save_png: 'ଚିତ୍ର ସେଭ୍ କରନ୍ତୁ',
  lbl_object: 'ବସ୍ତୁ',
  lbl_image: 'ପ୍ରତିବିମ୍ବ',
  light_dir: 'ଆଲୋକ',
  side_front: 'ସାମ୍ନାରେ: ବାସ୍ତବ ପ୍ରତିବିମ୍ବ',
  side_behind: 'ପଛରେ: ଆଭାସୀ ପ୍ରତିବିମ୍ବ',
  side_obj: 'ବସ୍ତୁ ପାର୍ଶ୍ୱରେ: ଆଭାସୀ ପ୍ରତିବିମ୍ବ',
  side_other: 'ଅନ୍ୟ ପାର୍ଶ୍ୱରେ: ବାସ୍ତବ ପ୍ରତିବିମ୍ବ',
  note_point: 'ବସ୍ତୁ ବହୁତ ଦୂରରେ ଅଛି: ରଶ୍ମିଗୁଡ଼ିକ ସମାନ୍ତର ଭାବେ ଆସନ୍ତି ଏବଂ ଫୋକସରେ ବିନ୍ଦୁ ପରି ପ୍ରତିବିମ୍ବ ତିଆରି କରନ୍ତି।',
  note_inf_img: 'ରଶ୍ମିଗୁଡ଼ିକ ସମାନ୍ତର ଭାବେ ବାହାରନ୍ତି, ତେଣୁ ପ୍ରତିବିମ୍ବ ଅସୀମରେ ଗଠିତ ହୁଏ।',
  note_off: 'ପ୍ରତିବିମ୍ବ ଚିତ୍ର ବାହାରେ ଅଛି, v = {v} ଠାରେ।',
  res_h: 'ଫଳାଫଳ (ଚିହ୍ନ ସହିତ)',
  r_u: 'ବସ୍ତୁର ଦୂରତା u',
  r_v: 'ପ୍ରତିବିମ୍ବର ଦୂରତା v',
  r_f: 'ଫୋକସ ଦୂରତା f',
  r_m: 'ବିବର୍ଦ୍ଧନ m',
  r_h: 'ବସ୍ତୁର ଉଚ୍ଚତା h',
  r_h2: 'ପ୍ରତିବିମ୍ବର ଉଚ୍ଚତା h′',
  r_p: 'ପାୱାର୍ P',
  r_obj_pos: 'ବସ୍ତୁ:',
  r_img_pos: 'ପ୍ରତିବିମ୍ବ:',
  nat_real: 'ବାସ୍ତବ',
  nat_virtual: 'ଆଭାସୀ',
  nat_inverted: 'ଓଲଟା',
  nat_erect: 'ସିଧା',
  size_point: 'ଅତି ଛୋଟ, ବିନ୍ଦୁ ଆକାରର',
  size_dim: 'ଛୋଟ',
  size_same: 'ସମାନ ଆକାର',
  size_big: 'ବଡ଼ (ବିବର୍ଦ୍ଧିତ)',
  size_huge: 'ଅତି ବଡ଼',
  why_obj_inf: 'ବହୁତ ଦୂର ବସ୍ତୁରୁ ରଶ୍ମି ଅକ୍ଷ ସହ ସମାନ୍ତର ଭାବେ ଆସେ, ତେଣୁ ସେଗୁଡ଼ିକ ଫୋକସରେ ମିଳନ୍ତି (କିମ୍ବା ସେଠାରୁ ଆସୁଥିବା ପରି ଲାଗନ୍ତି)।',
  why_inf: 'ବାହାରୁଥିବା ରଶ୍ମିଗୁଡ଼ିକ ପରସ୍ପର ସମାନ୍ତର, ତେଣୁ ସେଗୁଡ଼ିକ କେବଳ ଅସୀମରେ ମିଳନ୍ତି।',
  why_mirror_real: 'v ଋଣାତ୍ମକ: ପ୍ରତିବିମ୍ବ ଦର୍ପଣ ସାମ୍ନାରେ, ଯେଉଁଠି ପ୍ରତିଫଳିତ ରଶ୍ମି ପ୍ରକୃତରେ ମିଳନ୍ତି। ତେଣୁ ଏହା ବାସ୍ତବ।',
  why_mirror_virtual: 'v ଧନାତ୍ମକ: ପ୍ରତିବିମ୍ବ ଦର୍ପଣ ପଛରେ। ରଶ୍ମି କେବଳ ସେଠାରୁ ଆସୁଥିବା ପରି ଲାଗନ୍ତି, ତେଣୁ ଏହା ଆଭାସୀ।',
  why_lens_real: 'v ଧନାତ୍ମକ: ପ୍ରତିବିମ୍ବ ଲେନ୍ସର ଅନ୍ୟ ପାର୍ଶ୍ୱରେ, ଯେଉଁଠି ରଶ୍ମି ପ୍ରକୃତରେ ମିଳନ୍ତି। ତେଣୁ ଏହା ବାସ୍ତବ।',
  why_lens_virtual: 'v ଋଣାତ୍ମକ: ପ୍ରତିବିମ୍ବ ବସ୍ତୁ ପାର୍ଶ୍ୱରେ ହିଁ ଅଛି। ରଶ୍ମି କେବଳ ସେଠାରୁ ଆସୁଥିବା ପରି ଲାଗନ୍ତି, ତେଣୁ ଏହା ଆଭାସୀ।',
  why_m_neg: 'm ଋଣାତ୍ମକ, ତେଣୁ ପ୍ରତିବିମ୍ବ ଓଲଟା।',
  why_m_pos: 'm ଧନାତ୍ମକ, ତେଣୁ ପ୍ରତିବିମ୍ବ ସିଧା।',
  why_m_big: 'ଚିହ୍ନ ଛାଡ଼ି m ର ମାନ 1 ରୁ ଅଧିକ, ତେଣୁ ପ୍ରତିବିମ୍ବ ବଡ଼।',
  why_m_small: 'ଚିହ୍ନ ଛାଡ଼ି m ର ମାନ 1 ରୁ କମ୍, ତେଣୁ ପ୍ରତିବିମ୍ବ ଛୋଟ।',
  why_m_same: 'ଚିହ୍ନ ଛାଡ଼ି m ର ମାନ 1, ତେଣୁ ପ୍ରତିବିମ୍ବ ବସ୍ତୁ ସହ ସମାନ।',
  form_h: 'ସୂତ୍ର ଦ୍ୱାରା ଯାଞ୍ଚ କରନ୍ତୁ',
  form_mirror: 'ଦର୍ପଣ ସୂତ୍ର',
  form_lens: 'ଲେନ୍ସ ସୂତ୍ର',
  form_mag: 'ବିବର୍ଦ୍ଧନ',
  form_power: 'ଲେନ୍ସର ପାୱାର୍ (f ମିଟରରେ, ଅର୍ଥାତ୍ f cm ରେ ଥିଲେ 100/f)',
  table_h: 'NCERT ସାରଣୀ: ପ୍ରତିବିମ୍ବ କେଉଁଠି ହେବ?',
  table_tip: 'ବସ୍ତୁକୁ ସେହି ସ୍ଥିତିରେ ରଖିବାକୁ କୌଣସି ଧାଡ଼ିରେ ଟ୍ୟାପ୍ କରନ୍ତୁ।',
  th_obj: 'ବସ୍ତୁର ସ୍ଥିତି',
  th_img: 'ପ୍ରତିବିମ୍ବର ସ୍ଥିତି',
  th_size: 'ପ୍ରତିବିମ୍ବର ଆକାର',
  th_nature: 'ପ୍ରତିବିମ୍ବର ପ୍ରକୃତି',
  nature_ri: 'ବାସ୍ତବ ଓ ଓଲଟା',
  nature_ve: 'ଆଭାସୀ ଓ ସିଧା',
  pos_inf: 'ଅସୀମରେ',
  pos_beyond_c: 'C ର ବାହାରେ',
  pos_at_c: 'C ଠାରେ',
  pos_c_f: 'C ଓ F ମଧ୍ୟରେ',
  pos_f_c: 'F ଓ C ମଧ୍ୟରେ',
  pos_at_f: 'F ଠାରେ',
  pos_p_f: 'P ଓ F ମଧ୍ୟରେ',
  pos_behind: 'ଦର୍ପଣ ପଛରେ',
  pos_inf_p: 'ଅସୀମ ଓ ମେରୁ P ମଧ୍ୟରେ',
  pos_behind_pf: 'ଦର୍ପଣ ପଛରେ, P ଓ F ମଧ୍ୟରେ',
  pos_behind_f: 'ଦର୍ପଣ ପଛରେ, F ଠାରେ',
  pos_beyond_2f1: '2F₁ ର ବାହାରେ',
  pos_at_2f1: '2F₁ ଠାରେ',
  pos_f1_2f1: 'F₁ ଓ 2F₁ ମଧ୍ୟରେ',
  pos_at_f1: 'F₁ ଠାରେ',
  pos_f1_o: 'F₁ ଓ ଆଲୋକ କେନ୍ଦ୍ର O ମଧ୍ୟରେ',
  pos_at_f2: 'F₂ ଠାରେ',
  pos_f2_2f2: 'F₂ ଓ 2F₂ ମଧ୍ୟରେ',
  pos_at_2f2: '2F₂ ଠାରେ',
  pos_beyond_2f2: '2F₂ ର ବାହାରେ',
  pos_same_side: 'ଲେନ୍ସର ଯେଉଁ ପାର୍ଶ୍ୱରେ ବସ୍ତୁ ଅଛି, ସେହି ପାର୍ଶ୍ୱରେ',
  pos_inf_o: 'ଅସୀମ ଓ ଆଲୋକ କେନ୍ଦ୍ର O ମଧ୍ୟରେ',
  sign_h: 'ନୂଆ କାର୍ଟେସୀୟ ଚିହ୍ନ ନିୟମ',
  sign_1: 'ପ୍ରତ୍ୟେକ ଦୂରତା ଦର୍ପଣର ମେରୁ P କିମ୍ବା ଲେନ୍ସର ଆଲୋକ କେନ୍ଦ୍ର O ଠାରୁ ମାପନ୍ତୁ।',
  sign_2: 'ଆଲୋକ ବାମ ପଟରୁ ଆସେ। ଡାହାଣ ପଟର (ଆଲୋକର ଦିଗରେ) ଦୂରତା ଧନାତ୍ମକ (+) ଏବଂ ବାମ ପଟର ଦୂରତା ଋଣାତ୍ମକ (−)।',
  sign_3: 'ତେଣୁ ଏଠାରେ ବସ୍ତୁର ଦୂରତା u ସବୁବେଳେ ଋଣାତ୍ମକ।',
  sign_4: 'ମୁଖ୍ୟ ଅକ୍ଷର ଉପର ଉଚ୍ଚତା ଧନାତ୍ମକ ଏବଂ ତଳ ଉଚ୍ଚତା ଋଣାତ୍ମକ।',
  sign_5: 'ଅବତଳ ଦର୍ପଣ ଓ ଅବତଳ ଲେନ୍ସ ପାଇଁ f ଋଣାତ୍ମକ, ଉତ୍ତଳ ଦର୍ପଣ ଓ ଉତ୍ତଳ ଲେନ୍ସ ପାଇଁ f ଧନାତ୍ମକ।',
  quiz_h: 'କୁଇଜ୍: ପ୍ରତିବିମ୍ବ ଅନୁମାନ କରନ୍ତୁ',
  quiz_q: 'ବସ୍ତୁର ଦୂରତା {u}, ଫୋକସ ଦୂରତା {f}। କିପରି ପ୍ରତିବିମ୍ବ ଗଠିତ ହେବ?',
  quiz_q_inf: 'ବସ୍ତୁ ବହୁତ ଦୂରରେ (ଅସୀମରେ) ଅଛି। ଫୋକସ ଦୂରତା {f}। କିପରି ପ୍ରତିବିମ୍ବ ଗଠିତ ହେବ?',
  q_pos: 'ପ୍ରତିବିମ୍ବର ସ୍ଥିତି',
  q_nature: 'ବାସ୍ତବ ନା ଆଭାସୀ?',
  q_orient: 'ସିଧା ନା ଓଲଟା?',
  q_size: 'ପ୍ରତିବିମ୍ବର ଆକାର',
  q_choose: 'ବାଛନ୍ତୁ…',
  q_check: 'ଉତ୍ତର ଯାଞ୍ଚ କରନ୍ତୁ',
  q_next: 'ନୂଆ ପ୍ରଶ୍ନ',
  q_show: 'ଲ୍ୟାବ୍‌ରେ ଦେଖନ୍ତୁ',
  q_score: 'ସ୍କୋର୍: {a} / {b}',
  q_need: 'ପ୍ରଥମେ ଚାରିଟି ଭାଗର ଉତ୍ତର ଦିଅନ୍ତୁ।',
  q_right: 'ବହୁତ ଭଲ! ଚାରିଟି ଭାଗ ଠିକ୍।',
  q_wrong: 'ପୂରା ଠିକ୍ ନୁହେଁ: 4 ମଧ୍ୟରୁ {n}ଟି ଭାଗ ଠିକ୍। ତଳେ ଠିକ୍ ଉତ୍ତର ଦେଖନ୍ତୁ।',
  q_hint: 'ଏଠାରେ ଦର୍ପଣ ବା ଲେନ୍ସଠାରୁ F {f} ଦୂରରେ ଏବଂ C (କିମ୍ବା 2F) {c} ଦୂରରେ ଅଛି।',
  uses_h: 'ଏଗୁଡ଼ିକର ବ୍ୟବହାର କେଉଁଠି ହୁଏ?',
  use_show: 'ଦେଖାନ୍ତୁ',
  use_torch_t: 'ଟର୍ଚ୍ଚ ଓ ଗାଡ଼ିର ହେଡଲାଇଟ୍',
  use_torch_d: 'ବଲ୍ବଟି ଅବତଳ ଦର୍ପଣର ଫୋକସରେ ଥାଏ, ତେଣୁ ଆଲୋକ ତୀବ୍ର ସମାନ୍ତର ରଶ୍ମିପୁଞ୍ଜ ହୋଇ ବାହାରେ।',
  use_solar_t: 'ସୌର କୁକର ଓ ସୌର ଚୁଲି',
  use_solar_d: 'ସୂର୍ଯ୍ୟ ଆଲୋକ ବହୁତ ଦୂରରୁ ଆସେ, ତେଣୁ ଅବତଳ ଦର୍ପଣ ତାକୁ ଫୋକସରେ ଏକାଠି କରି ବହୁତ ଗରମ କରେ।',
  use_shave_t: 'ଦାଢ଼ି କାଟିବା ଓ ମେକଅପ୍ ଦର୍ପଣ',
  use_shave_d: 'ମୁହଁକୁ ଅବତଳ ଦର୍ପଣର P ଓ F ମଧ୍ୟରେ ରଖିଲେ ସିଧା ଓ ବଡ଼ ପ୍ରତିବିମ୍ବ ଦେଖାଯାଏ।',
  use_rear_t: 'ପଛ ଦେଖିବା ଦର୍ପଣ',
  use_rear_d: 'ଉତ୍ତଳ ଦର୍ପଣ ସବୁବେଳେ ସିଧା ଓ ଛୋଟ ପ୍ରତିବିମ୍ବ ଦିଏ ଏବଂ ଗାଡ଼ି ପଛର ବଡ଼ ଅଂଶ ଦେଖାଏ।',
  use_mag_t: 'ବିବର୍ଦ୍ଧକ କାଚ',
  use_mag_d: 'ବସ୍ତୁକୁ ଉତ୍ତଳ ଲେନ୍ସର F₁ ଓ O ମଧ୍ୟରେ ରଖିଲେ ସିଧା, ବଡ଼, ଆଭାସୀ ପ୍ରତିବିମ୍ବ ମିଳେ।',
  use_proj_t: 'ପ୍ରୋଜେକ୍ଟର',
  use_proj_d: 'ସ୍ଲାଇଡ୍ ଉତ୍ତଳ ଲେନ୍ସର F₁ ଓ 2F₁ ମଧ୍ୟରେ ଥାଏ, ତେଣୁ ପରଦାରେ ବଡ଼, ବାସ୍ତବ, ଓଲଟା ପ୍ରତିବିମ୍ବ ପଡ଼େ। ସେଥିପାଇଁ ସ୍ଲାଇଡ୍ ଓଲଟା କରି ଲଗାଯାଏ।',
  use_cam_t: 'କ୍ୟାମେରା ଓ ଆମ ଆଖି',
  use_cam_d: 'ଦୂର ବସ୍ତୁ (2F₁ ର ବାହାରେ) ସେନ୍ସର୍ ବା ରେଟିନାରେ ଛୋଟ, ବାସ୍ତବ, ଓଲଟା ପ୍ରତିବିମ୍ବ ତିଆରି କରେ।',
  use_spec_t: 'ନିକଟ ଦୃଷ୍ଟି ଚଷମା',
  use_spec_d: 'ଅବତଳ ଲେନ୍ସ ସବୁବେଳେ ଆଭାସୀ, ସିଧା, ଛୋଟ ପ୍ରତିବିମ୍ବ ଦିଏ। ଏହା ନିକଟ ଦୃଷ୍ଟି ଦୋଷ ଥିବା ଲୋକଙ୍କୁ ଦୂରକୁ ଦେଖିବାରେ ସାହାଯ୍ୟ କରେ।',
  help_h: 'କିପରି ବ୍ୟବହାର କରିବେ / ଶ୍ରେଣୀ ପାଇଁ ଚିନ୍ତାଧାରା',
  help_1: 'ଦର୍ପଣ ବା ଲେନ୍ସ ବାଛନ୍ତୁ, ତା’ପରେ କମଳା ବସ୍ତୁକୁ ଟାଣନ୍ତୁ (କିମ୍ବା ସ୍ଲାଇଡର୍ ଘୁଞ୍ଚାନ୍ତୁ)। ରଶ୍ମି, ପ୍ରତିବିମ୍ବ ଓ ସବୁ ସଂଖ୍ୟା ତୁରନ୍ତ ବଦଳେ।',
  help_2: 'ରଙ୍ଗୀନ ବଟନ୍ ଦ୍ୱାରା ରଶ୍ମି ଚାଲୁ ବା ବନ୍ଦ କରନ୍ତୁ। ପ୍ରତିବିମ୍ବ ଖୋଜିବାକୁ ଯେକୌଣସି ଦୁଇଟି ରଶ୍ମି ଯଥେଷ୍ଟ; ଡ୍ୟାସ୍ ରେଖା ଦେଖାଏ ରଶ୍ମି କେଉଁଠୁ ଆସୁଥିବା ପରି ଲାଗେ।',
  help_3: 'u, v, f ଓ m କୁ ସେମାନଙ୍କ ଚିହ୍ନ ସହ ପଢ଼ନ୍ତୁ। ସୂତ୍ର ବାକ୍ସରେ ପ୍ରତ୍ୟେକ ସୋପାନ ଦେଖାଯାଏ, ତେଣୁ ଛାତ୍ରଛାତ୍ରୀ ନିଜ ପ୍ରଶ୍ନ ଯାଞ୍ଚ କରିପାରିବେ।',
  help_4: 'NCERT ସାରଣୀର କୌଣସି ଧାଡ଼ିରେ ଟ୍ୟାପ୍ କରି ବସ୍ତୁକୁ ସେହି ସ୍ଥିତିକୁ ନିଅନ୍ତୁ। ପୃଷ୍ଠା ପ୍ରିଣ୍ଟ କଲେ ଚିତ୍ର, ସମାଧାନ ଓ ସାରଣୀ କାଗଜରେ ମିଳେ।',
  help_5: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟ: ଜଣେ ଛାତ୍ର ବସ୍ତୁ ଘୁଞ୍ଚାଇବ, ବାକି ଶ୍ରେଣୀ ଦେଖିବା ଆଗରୁ କହିବେ, "ବାସ୍ତବ ନା ଆଭାସୀ, ସିଧା ନା ଓଲଟା, ବଡ଼ ନା ଛୋଟ"। ତା’ପରେ ଦଳରେ କୁଇଜ୍ ଖେଳନ୍ତୁ।',
  help_6: 'ଘରେ କରି ଦେଖନ୍ତୁ: ଚକଚକିଆ ଷ୍ଟିଲ୍ ଚାମଚରେ ଚାହାଁନ୍ତୁ। ଭିତର ପଟ ଅବତଳ ଦର୍ପଣ ପରି ଏବଂ ପଛ ପଟ ଉତ୍ତଳ ଦର୍ପଣ ପରି କାମ କରେ।'
};
window.APP_STRINGS.ta = {
  app_title: 'லென்ஸ் & ஆடி கதிர் ஆய்வகம்',
  intro: 'ஆடி அல்லது லென்ஸின் முன் பொருளை நகர்த்தி, கதிர்கள் எப்படி பிம்பத்தை உருவாக்குகின்றன என்று பாருங்கள். குறியீட்டு மரபு, ஆடி மற்றும் லென்ஸ் சூத்திரங்கள், NCERT பிம்ப அட்டவணைகளைக் கற்றுக்கொள்ளுங்கள்.',
  dev_label: 'ஆடி அல்லது லென்ஸைத் தேர்வுசெய்யுங்கள்',
  dev_concave_mirror: 'குழி ஆடி',
  dev_convex_mirror: 'குவி ஆடி',
  dev_convex_lens: 'குவி லென்ஸ்',
  dev_concave_lens: 'குழி லென்ஸ்',
  canvas_label: 'கதிர் வரைபடம். பொருளை இழுக்கவும் அல்லது அம்புக்குறி விசைகளால் நகர்த்தவும்.',
  drag_hint: 'ஆரஞ்சு நிறப் பொருளை அச்சின் மேல் இழுக்கவும், அல்லது படத்தில் கிளிக் செய்து ← → விசைகளை அழுத்தவும்.',
  not_to_scale: 'கதிர்கள் தெளிவாகத் தெரிய, உயரங்கள் தொலைவுகளை விடப் பெரிதாக வரையப்பட்டுள்ளன.',
  rays_label: 'கதிர்கள்:',
  ray_par: 'அச்சுக்கு இணையாக',
  ray_c: 'C வழியாக',
  ray_o: 'O வழியாக',
  ray_f: 'F வழியாக',
  ray_f1: 'F₁ வழியாக',
  ray_f2: 'F₂ நோக்கி',
  ray_p: 'ஆடி மையம் P-இல்',
  ray_n: 'கதிர் {n}',
  ray_miss: 'இந்த நிலையில் சில கதிர்கள் ஆடியையோ லென்ஸையோ அடைவதில்லை, எனவே அவை வரையப்படவில்லை (கோடிட்ட பொத்தான்கள்).',
  f_label: 'குவியத் தொலைவு |f|',
  u_label: 'பொருளின் தொலைவு |u|',
  h_label: 'பொருளின் உயரம் h',
  far_btn: 'மிகத் தொலைவில் (∞)',
  save_png: 'படத்தைச் சேமி',
  lbl_object: 'பொருள்',
  lbl_image: 'பிம்பம்',
  light_dir: 'ஒளி',
  side_front: 'முன்புறம்: மெய் பிம்பம்',
  side_behind: 'பின்புறம்: மாய பிம்பம்',
  side_obj: 'பொருள் பக்கம்: மாய பிம்பம்',
  side_other: 'மறுபக்கம்: மெய் பிம்பம்',
  note_point: 'பொருள் மிகத் தொலைவில் உள்ளது: கதிர்கள் இணையாக வந்து குவியத்தில் புள்ளி அளவு பிம்பத்தை உருவாக்குகின்றன.',
  note_inf_img: 'கதிர்கள் இணையாக வெளியேறுகின்றன, எனவே பிம்பம் ஈறிலாத் தொலைவில் உருவாகிறது.',
  note_off: 'பிம்பம் படத்திற்கு வெளியே, v = {v}-இல் உள்ளது.',
  res_h: 'முடிவுகள் (குறிகளுடன்)',
  r_u: 'பொருளின் தொலைவு u',
  r_v: 'பிம்பத்தின் தொலைவு v',
  r_f: 'குவியத் தொலைவு f',
  r_m: 'உருப்பெருக்கம் m',
  r_h: 'பொருளின் உயரம் h',
  r_h2: 'பிம்பத்தின் உயரம் h′',
  r_p: 'திறன் P',
  r_obj_pos: 'பொருள்:',
  r_img_pos: 'பிம்பம்:',
  nat_real: 'மெய்',
  nat_virtual: 'மாய',
  nat_inverted: 'தலைகீழானது',
  nat_erect: 'நேரானது',
  size_point: 'மிகச் சிறியது, புள்ளி அளவு',
  size_dim: 'சிறியது',
  size_same: 'அதே அளவு',
  size_big: 'பெரியது',
  size_huge: 'மிகப் பெரியது',
  why_obj_inf: 'மிகத் தொலைவிலுள்ள பொருளிலிருந்து கதிர்கள் அச்சுக்கு இணையாக வருகின்றன, எனவே அவை குவியத்தில் சந்திக்கின்றன (அல்லது அங்கிருந்து வருவது போலத் தோன்றும்).',
  why_inf: 'வெளிவரும் கதிர்கள் ஒன்றுக்கொன்று இணையாக உள்ளன, எனவே அவை ஈறிலாத் தொலைவில் மட்டுமே சந்திக்கின்றன.',
  why_mirror_real: 'v எதிர்க்குறி: பிம்பம் ஆடியின் முன்னால் உள்ளது, அங்கு எதிரொளித்த கதிர்கள் உண்மையில் சந்திக்கின்றன. எனவே இது மெய் பிம்பம்.',
  why_mirror_virtual: 'v நேர்க்குறி: பிம்பம் ஆடிக்குப் பின்னால் உள்ளது. கதிர்கள் அங்கிருந்து வருவது போல மட்டுமே தோன்றும், எனவே இது மாய பிம்பம்.',
  why_lens_real: 'v நேர்க்குறி: பிம்பம் லென்ஸின் மறுபக்கம் உள்ளது, அங்கு கதிர்கள் உண்மையில் சந்திக்கின்றன. எனவே இது மெய் பிம்பம்.',
  why_lens_virtual: 'v எதிர்க்குறி: பிம்பம் பொருள் இருக்கும் பக்கமே உள்ளது. கதிர்கள் அங்கிருந்து வருவது போல மட்டுமே தோன்றும், எனவே இது மாய பிம்பம்.',
  why_m_neg: 'm எதிர்க்குறி, எனவே பிம்பம் தலைகீழானது.',
  why_m_pos: 'm நேர்க்குறி, எனவே பிம்பம் நேரானது.',
  why_m_big: 'குறியை விட்டு m-இன் மதிப்பு 1-ஐ விட அதிகம், எனவே பிம்பம் பெரியது.',
  why_m_small: 'குறியை விட்டு m-இன் மதிப்பு 1-ஐ விடக் குறைவு, எனவே பிம்பம் சிறியது.',
  why_m_same: 'குறியை விட்டு m-இன் மதிப்பு 1, எனவே பிம்பம் பொருளின் அதே அளவு.',
  form_h: 'சூத்திரத்தால் சரிபாருங்கள்',
  form_mirror: 'ஆடிச் சமன்பாடு',
  form_lens: 'லென்ஸ் சமன்பாடு',
  form_mag: 'உருப்பெருக்கம்',
  form_power: 'லென்ஸின் திறன் (f மீட்டரில்; f cm-இல் இருந்தால் 100/f)',
  table_h: 'NCERT அட்டவணை: பிம்பம் எங்கே தோன்றும்?',
  table_tip: 'பொருளை அந்த நிலையில் வைக்க ஒரு வரிசையைத் தட்டவும்.',
  th_obj: 'பொருளின் நிலை',
  th_img: 'பிம்பத்தின் நிலை',
  th_size: 'பிம்பத்தின் அளவு',
  th_nature: 'பிம்பத்தின் தன்மை',
  nature_ri: 'மெய், தலைகீழானது',
  nature_ve: 'மாய, நேரானது',
  pos_inf: 'ஈறிலாத் தொலைவில்',
  pos_beyond_c: 'C-க்கு அப்பால்',
  pos_at_c: 'C-இல்',
  pos_c_f: 'C-க்கும் F-க்கும் இடையில்',
  pos_f_c: 'F-க்கும் C-க்கும் இடையில்',
  pos_at_f: 'F-இல்',
  pos_p_f: 'P-க்கும் F-க்கும் இடையில்',
  pos_behind: 'ஆடிக்குப் பின்னால்',
  pos_inf_p: 'ஈறிலாத் தொலைவுக்கும் ஆடி மையம் P-க்கும் இடையில்',
  pos_behind_pf: 'ஆடிக்குப் பின்னால், P-க்கும் F-க்கும் இடையில்',
  pos_behind_f: 'ஆடிக்குப் பின்னால், F-இல்',
  pos_beyond_2f1: '2F₁-க்கு அப்பால்',
  pos_at_2f1: '2F₁-இல்',
  pos_f1_2f1: 'F₁-க்கும் 2F₁-க்கும் இடையில்',
  pos_at_f1: 'F₁-இல்',
  pos_f1_o: 'F₁-க்கும் ஒளி மையம் O-க்கும் இடையில்',
  pos_at_f2: 'F₂-இல்',
  pos_f2_2f2: 'F₂-க்கும் 2F₂-க்கும் இடையில்',
  pos_at_2f2: '2F₂-இல்',
  pos_beyond_2f2: '2F₂-க்கு அப்பால்',
  pos_same_side: 'பொருள் இருக்கும் அதே பக்கத்தில்',
  pos_inf_o: 'ஈறிலாத் தொலைவுக்கும் ஒளி மையம் O-க்கும் இடையில்',
  sign_h: 'புதிய கார்டீசியன் குறியீட்டு மரபு',
  sign_1: 'எல்லாத் தொலைவுகளையும் ஆடியின் ஆடி மையம் P அல்லது லென்ஸின் ஒளி மையம் O-இலிருந்து அளக்கவும்.',
  sign_2: 'ஒளி இடப்பக்கத்திலிருந்து வருகிறது. வலப்பக்கத் (ஒளி செல்லும் திசை) தொலைவுகள் நேர்க்குறி (+), இடப்பக்கத் தொலைவுகள் எதிர்க்குறி (−).',
  sign_3: 'எனவே இங்கு பொருளின் தொலைவு u எப்போதும் எதிர்க்குறி.',
  sign_4: 'முதன்மை அச்சுக்கு மேலே உள்ள உயரம் நேர்க்குறி, கீழே உள்ள உயரம் எதிர்க்குறி.',
  sign_5: 'குழி ஆடிக்கும் குழி லென்ஸுக்கும் f எதிர்க்குறி; குவி ஆடிக்கும் குவி லென்ஸுக்கும் f நேர்க்குறி.',
  quiz_h: 'வினாடி வினா: பிம்பத்தை ஊகியுங்கள்',
  quiz_q: 'பொருளின் தொலைவு {u}, குவியத் தொலைவு {f}. எத்தகைய பிம்பம் உருவாகும்?',
  quiz_q_inf: 'பொருள் மிகத் தொலைவில் (ஈறிலாத் தொலைவில்) உள்ளது. குவியத் தொலைவு {f}. எத்தகைய பிம்பம் உருவாகும்?',
  q_pos: 'பிம்பத்தின் நிலை',
  q_nature: 'மெய்யா, மாயமா?',
  q_orient: 'நேரானதா, தலைகீழானதா?',
  q_size: 'பிம்பத்தின் அளவு',
  q_choose: 'தேர்வுசெய்க…',
  q_check: 'விடையைச் சரிபார்',
  q_next: 'புதிய கேள்வி',
  q_show: 'ஆய்வகத்தில் பார்',
  q_score: 'மதிப்பெண்: {a} / {b}',
  q_need: 'முதலில் நான்கு பகுதிகளுக்கும் விடை அளியுங்கள்.',
  q_right: 'அருமை! நான்கு பகுதிகளும் சரி.',
  q_wrong: 'முழுமையாகச் சரியில்லை: 4-இல் {n} பகுதிகள் சரி. சரியான விடையைக் கீழே பாருங்கள்.',
  q_hint: 'இங்கு ஆடி அல்லது லென்ஸிலிருந்து F {f} தொலைவிலும், C (அல்லது 2F) {c} தொலைவிலும் உள்ளது.',
  uses_h: 'இவற்றை எங்கே பயன்படுத்துகிறோம்?',
  use_show: 'காட்டு',
  use_torch_t: 'டார்ச் மற்றும் வாகன முகப்பு விளக்கு',
  use_torch_d: 'பல்பு குழி ஆடியின் குவியத்தில் இருப்பதால், ஒளி வலுவான இணைக் கற்றையாக வெளியேறுகிறது.',
  use_solar_t: 'சூரிய அடுப்பு',
  use_solar_d: 'சூரிய ஒளி மிகத் தொலைவிலிருந்து வருவதால், குழி ஆடி அதைக் குவியத்தில் சேர்த்து மிகுந்த வெப்பம் தருகிறது.',
  use_shave_t: 'முகச்சவர மற்றும் ஒப்பனை ஆடி',
  use_shave_d: 'முகத்தைக் குழி ஆடியின் P-க்கும் F-க்கும் இடையில் வைத்தால் நேரான, பெரிய பிம்பம் தெரியும்.',
  use_rear_t: 'பின்னோக்குக் காட்டும் ஆடி',
  use_rear_d: 'குவி ஆடி எப்போதும் நேரான, சிறிய பிம்பத்தைத் தருகிறது; வாகனத்தின் பின்னால் உள்ள பரந்த பகுதியைக் காட்டுகிறது.',
  use_mag_t: 'உருப்பெருக்கும் கண்ணாடி',
  use_mag_d: 'பொருளைக் குவி லென்ஸின் F₁-க்கும் O-க்கும் இடையில் வைத்தால் நேரான, பெரிய, மாய பிம்பம் கிடைக்கும்.',
  use_proj_t: 'புரொஜெக்டர்',
  use_proj_d: 'ஸ்லைடு குவி லென்ஸின் F₁-க்கும் 2F₁-க்கும் இடையில் இருப்பதால், திரையில் பெரிய, மெய், தலைகீழான பிம்பம் விழுகிறது. அதனால்தான் ஸ்லைடைத் தலைகீழாக வைக்கிறார்கள்.',
  use_cam_t: 'கேமராவும் நம் கண்ணும்',
  use_cam_d: 'தொலைவிலுள்ள பொருள் (2F₁-க்கு அப்பால்) சென்சர் அல்லது விழித்திரையில் சிறிய, மெய், தலைகீழான பிம்பத்தை உருவாக்குகிறது.',
  use_spec_t: 'கிட்டப்பார்வைக் கண்ணாடி',
  use_spec_d: 'குழி லென்ஸ் எப்போதும் மாய, நேரான, சிறிய பிம்பத்தைத் தருகிறது. கிட்டப்பார்வை உள்ளவர்கள் தொலைவைப் பார்க்க இது உதவுகிறது.',
  help_h: 'பயன்படுத்தும் முறை / வகுப்பறைக்கான யோசனைகள்',
  help_1: 'ஆடி அல்லது லென்ஸைத் தேர்ந்தெடுத்து, ஆரஞ்சு பொருளை இழுக்கவும் (அல்லது ஸ்லைடரை நகர்த்தவும்). கதிர்கள், பிம்பம், எல்லா எண்களும் உடனே மாறும்.',
  help_2: 'வண்ணப் பொத்தான்களால் கதிர்களை இயக்கவும் அல்லது நிறுத்தவும். பிம்பத்தைக் கண்டுபிடிக்க ஏதேனும் இரண்டு கதிர்கள் போதும்; கோடிட்ட கோடுகள் கதிர்கள் எங்கிருந்து வருவது போலத் தோன்றுகின்றன என்று காட்டும்.',
  help_3: 'u, v, f, m ஆகியவற்றை அவற்றின் குறிகளுடன் படியுங்கள். சூத்திரப் பெட்டி ஒவ்வொரு படியையும் காட்டுவதால், மாணவர்கள் தங்கள் கணக்குகளைச் சரிபார்க்கலாம்.',
  help_4: 'NCERT அட்டவணையின் ஒரு வரிசையைத் தட்டினால் பொருள் அந்த நிலைக்குச் செல்லும். பக்கத்தை அச்சிட்டால் வரைபடம், தீர்வு, அட்டவணை தாளில் கிடைக்கும்.',
  help_5: 'வகுப்புச் செயல்பாடு: ஒரு மாணவர் பொருளை நகர்த்த, மற்றவர்கள் பார்க்கும் முன் "மெய்யா மாயமா, நேரா தலைகீழா, பெரியதா சிறியதா" என்று சொல்லட்டும். பிறகு அணிகளாக வினாடி வினா விளையாடுங்கள்.',
  help_6: 'வீட்டில் செய்து பாருங்கள்: பளபளக்கும் எஃகுக் கரண்டியில் பாருங்கள். உட்புறம் குழி ஆடி போலவும் பின்புறம் குவி ஆடி போலவும் செயல்படும்.'
};
window.APP_STRINGS.te = {
  app_title: 'కటకం & దర్పణం కిరణ ల్యాబ్',
  intro: 'దర్పణం లేదా కటకం ముందు వస్తువును జరిపి, కిరణాలు ప్రతిబింబాన్ని ఎలా ఏర్పరుస్తాయో చూడండి. సంజ్ఞా సంప్రదాయం, దర్పణ, కటక సూత్రాలు, NCERT ప్రతిబింబ పట్టికలు నేర్చుకోండి.',
  dev_label: 'దర్పణం లేదా కటకం ఎంచుకోండి',
  dev_concave_mirror: 'పుటాకార దర్పణం',
  dev_convex_mirror: 'కుంభాకార దర్పణం',
  dev_convex_lens: 'కుంభాకార కటకం',
  dev_concave_lens: 'పుటాకార కటకం',
  canvas_label: 'కిరణ చిత్రం. వస్తువును లాగండి లేదా బాణం కీలతో జరపండి.',
  drag_hint: 'నారింజ రంగు వస్తువును అక్షం మీద లాగండి, లేదా చిత్రంపై క్లిక్ చేసి ← → కీలు నొక్కండి.',
  not_to_scale: 'కిరణాలు స్పష్టంగా కనిపించేందుకు ఎత్తులను దూరాల కంటే పెద్దగా గీశాం.',
  rays_label: 'కిరణాలు:',
  ray_par: 'అక్షానికి సమాంతరం',
  ray_c: 'C గుండా',
  ray_o: 'O గుండా',
  ray_f: 'F గుండా',
  ray_f1: 'F₁ గుండా',
  ray_f2: 'F₂ వైపు',
  ray_p: 'ధ్రువం P వద్ద',
  ray_n: 'కిరణం {n}',
  ray_miss: 'ఈ స్థానంలో కొన్ని కిరణాలు దర్పణాన్ని లేదా కటకాన్ని చేరవు, అందుకే వాటిని గీయలేదు (గీతల అంచు బటన్లు).',
  f_label: 'నాభ్యంతరం |f|',
  u_label: 'వస్తు దూరం |u|',
  h_label: 'వస్తువు ఎత్తు h',
  far_btn: 'చాలా దూరం (∞)',
  save_png: 'చిత్రాన్ని సేవ్ చేయండి',
  lbl_object: 'వస్తువు',
  lbl_image: 'ప్రతిబింబం',
  light_dir: 'కాంతి',
  side_front: 'ముందు: నిజ ప్రతిబింబాలు',
  side_behind: 'వెనుక: మిథ్యా ప్రతిబింబాలు',
  side_obj: 'వస్తువు వైపు: మిథ్యా ప్రతిబింబాలు',
  side_other: 'అవతలి వైపు: నిజ ప్రతిబింబాలు',
  note_point: 'వస్తువు చాలా దూరంలో ఉంది: కిరణాలు సమాంతరంగా వచ్చి నాభి వద్ద బిందువంత ప్రతిబింబాన్ని ఏర్పరుస్తాయి.',
  note_inf_img: 'కిరణాలు సమాంతరంగా బయటకు వస్తాయి, కాబట్టి ప్రతిబింబం అనంత దూరంలో ఏర్పడుతుంది.',
  note_off: 'ప్రతిబింబం చిత్రం బయట, v = {v} వద్ద ఉంది.',
  res_h: 'ఫలితాలు (గుర్తులతో)',
  r_u: 'వస్తు దూరం u',
  r_v: 'ప్రతిబింబ దూరం v',
  r_f: 'నాభ్యంతరం f',
  r_m: 'ఆవర్ధనం m',
  r_h: 'వస్తువు ఎత్తు h',
  r_h2: 'ప్రతిబింబం ఎత్తు h′',
  r_p: 'సామర్థ్యం P',
  r_obj_pos: 'వస్తువు:',
  r_img_pos: 'ప్రతిబింబం:',
  nat_real: 'నిజ',
  nat_virtual: 'మిథ్యా',
  nat_inverted: 'తలకిందులు',
  nat_erect: 'నిటారు',
  size_point: 'చాలా చిన్నది, బిందువంత',
  size_dim: 'చిన్నది',
  size_same: 'అదే పరిమాణం',
  size_big: 'పెద్దది',
  size_huge: 'చాలా పెద్దది',
  why_obj_inf: 'చాలా దూరంలోని వస్తువు నుంచి కిరణాలు అక్షానికి సమాంతరంగా వస్తాయి, కాబట్టి అవి నాభి వద్ద కలుస్తాయి (లేదా అక్కడి నుంచి వస్తున్నట్టు కనిపిస్తాయి).',
  why_inf: 'బయటకు వచ్చే కిరణాలు ఒకదానికొకటి సమాంతరంగా ఉన్నాయి, కాబట్టి అవి అనంత దూరంలో మాత్రమే కలుస్తాయి.',
  why_mirror_real: 'v రుణాత్మకం: ప్రతిబింబం దర్పణం ముందు ఉంది, అక్కడ పరావర్తన కిరణాలు నిజంగా కలుస్తాయి. కాబట్టి ఇది నిజ ప్రతిబింబం.',
  why_mirror_virtual: 'v ధనాత్మకం: ప్రతిబింబం దర్పణం వెనుక ఉంది. కిరణాలు అక్కడి నుంచి వస్తున్నట్టు మాత్రమే కనిపిస్తాయి, కాబట్టి ఇది మిథ్యా ప్రతిబింబం.',
  why_lens_real: 'v ధనాత్మకం: ప్రతిబింబం కటకం అవతలి వైపు ఉంది, అక్కడ కిరణాలు నిజంగా కలుస్తాయి. కాబట్టి ఇది నిజ ప్రతిబింబం.',
  why_lens_virtual: 'v రుణాత్మకం: ప్రతిబింబం వస్తువు ఉన్న వైపే ఉంది. కిరణాలు అక్కడి నుంచి వస్తున్నట్టు మాత్రమే కనిపిస్తాయి, కాబట్టి ఇది మిథ్యా ప్రతిబింబం.',
  why_m_neg: 'm రుణాత్మకం, కాబట్టి ప్రతిబింబం తలకిందులుగా ఉంటుంది.',
  why_m_pos: 'm ధనాత్మకం, కాబట్టి ప్రతిబింబం నిటారుగా ఉంటుంది.',
  why_m_big: 'గుర్తు వదిలితే m విలువ 1 కంటే ఎక్కువ, కాబట్టి ప్రతిబింబం పెద్దది.',
  why_m_small: 'గుర్తు వదిలితే m విలువ 1 కంటే తక్కువ, కాబట్టి ప్రతిబింబం చిన్నది.',
  why_m_same: 'గుర్తు వదిలితే m విలువ 1, కాబట్టి ప్రతిబింబం వస్తువు అంతే ఉంటుంది.',
  form_h: 'సూత్రంతో సరిచూడండి',
  form_mirror: 'దర్పణ సూత్రం',
  form_lens: 'కటక సూత్రం',
  form_mag: 'ఆవర్ధనం',
  form_power: 'కటక సామర్థ్యం (f మీటర్లలో; f cm లో ఉంటే 100/f)',
  table_h: 'NCERT పట్టిక: ప్రతిబింబం ఎక్కడ ఏర్పడుతుంది?',
  table_tip: 'వస్తువును ఆ స్థానంలో ఉంచడానికి ఏదైనా వరుసను నొక్కండి.',
  th_obj: 'వస్తువు స్థానం',
  th_img: 'ప్రతిబింబ స్థానం',
  th_size: 'ప్రతిబింబ పరిమాణం',
  th_nature: 'ప్రతిబింబ స్వభావం',
  nature_ri: 'నిజ, తలకిందులు',
  nature_ve: 'మిథ్యా, నిటారు',
  pos_inf: 'అనంత దూరంలో',
  pos_beyond_c: 'C కి ఆవల',
  pos_at_c: 'C వద్ద',
  pos_c_f: 'C, F ల మధ్య',
  pos_f_c: 'F, C ల మధ్య',
  pos_at_f: 'F వద్ద',
  pos_p_f: 'P, F ల మధ్య',
  pos_behind: 'దర్పణం వెనుక',
  pos_inf_p: 'అనంత దూరం, ధ్రువం P ల మధ్య',
  pos_behind_pf: 'దర్పణం వెనుక, P, F ల మధ్య',
  pos_behind_f: 'దర్పణం వెనుక, F వద్ద',
  pos_beyond_2f1: '2F₁ కి ఆవల',
  pos_at_2f1: '2F₁ వద్ద',
  pos_f1_2f1: 'F₁, 2F₁ ల మధ్య',
  pos_at_f1: 'F₁ వద్ద',
  pos_f1_o: 'F₁, దృక్ కేంద్రం O ల మధ్య',
  pos_at_f2: 'F₂ వద్ద',
  pos_f2_2f2: 'F₂, 2F₂ ల మధ్య',
  pos_at_2f2: '2F₂ వద్ద',
  pos_beyond_2f2: '2F₂ కి ఆవల',
  pos_same_side: 'వస్తువు ఉన్న వైపే',
  pos_inf_o: 'అనంత దూరం, దృక్ కేంద్రం O ల మధ్య',
  sign_h: 'నూతన కార్టీసియన్ సంజ్ఞా సంప్రదాయం',
  sign_1: 'ప్రతి దూరాన్ని దర్పణ ధ్రువం P నుంచి లేదా కటక దృక్ కేంద్రం O నుంచి కొలవండి.',
  sign_2: 'కాంతి ఎడమ వైపు నుంచి వస్తుంది. కుడి వైపు (కాంతి దిశలో) దూరాలు ధనాత్మకం (+), ఎడమ వైపు దూరాలు రుణాత్మకం (−).',
  sign_3: 'కాబట్టి ఇక్కడ వస్తు దూరం u ఎప్పుడూ రుణాత్మకమే.',
  sign_4: 'ప్రధాన అక్షం పైన ఎత్తులు ధనాత్మకం, కింద ఎత్తులు రుణాత్మకం.',
  sign_5: 'పుటాకార దర్పణం, పుటాకార కటకానికి f రుణాత్మకం; కుంభాకార దర్పణం, కుంభాకార కటకానికి f ధనాత్మకం.',
  quiz_h: 'క్విజ్: ప్రతిబింబాన్ని ఊహించండి',
  quiz_q: 'వస్తు దూరం {u}, నాభ్యంతరం {f}. ఎలాంటి ప్రతిబింబం ఏర్పడుతుంది?',
  quiz_q_inf: 'వస్తువు చాలా దూరంలో (అనంత దూరంలో) ఉంది. నాభ్యంతరం {f}. ఎలాంటి ప్రతిబింబం ఏర్పడుతుంది?',
  q_pos: 'ప్రతిబింబ స్థానం',
  q_nature: 'నిజమా, మిథ్యా?',
  q_orient: 'నిటారా, తలకిందులా?',
  q_size: 'ప్రతిబింబ పరిమాణం',
  q_choose: 'ఎంచుకోండి…',
  q_check: 'జవాబు సరిచూడండి',
  q_next: 'కొత్త ప్రశ్న',
  q_show: 'ల్యాబ్‌లో చూడండి',
  q_score: 'స్కోరు: {a} / {b}',
  q_need: 'ముందుగా నాలుగు భాగాలకూ జవాబు ఇవ్వండి.',
  q_right: 'భేష్! నాలుగు భాగాలూ సరైనవే.',
  q_wrong: 'పూర్తిగా సరి కాదు: 4 లో {n} భాగాలు సరైనవి. కింద సరైన జవాబు చూడండి.',
  q_hint: 'ఇక్కడ దర్పణం లేదా కటకం నుంచి F {f} దూరంలో, C (లేదా 2F) {c} దూరంలో ఉన్నాయి.',
  uses_h: 'వీటిని ఎక్కడ వాడతాం?',
  use_show: 'చూపించు',
  use_torch_t: 'టార్చ్, వాహనాల హెడ్‌లైట్లు',
  use_torch_d: 'బల్బు పుటాకార దర్పణ నాభి వద్ద ఉంటుంది, కాబట్టి కాంతి బలమైన సమాంతర పుంజంగా బయటకు వెళ్తుంది.',
  use_solar_t: 'సోలార్ కుక్కర్, సౌర కొలిమి',
  use_solar_d: 'సూర్యకాంతి చాలా దూరం నుంచి వస్తుంది, కాబట్టి పుటాకార దర్పణం దాన్ని నాభి వద్ద కేంద్రీకరించి చాలా వేడి చేస్తుంది.',
  use_shave_t: 'షేవింగ్, మేకప్ అద్దం',
  use_shave_d: 'ముఖాన్ని పుటాకార దర్పణం P, F ల మధ్య ఉంచితే నిటారు, పెద్ద ప్రతిబింబం కనిపిస్తుంది.',
  use_rear_t: 'వెనుక చూపు అద్దం',
  use_rear_d: 'కుంభాకార దర్పణం ఎప్పుడూ నిటారు, చిన్న ప్రతిబింబాన్ని ఇస్తుంది, వాహనం వెనుక విశాల ప్రాంతాన్ని చూపిస్తుంది.',
  use_mag_t: 'భూతద్దం',
  use_mag_d: 'వస్తువును కుంభాకార కటకం F₁, O ల మధ్య ఉంచితే నిటారు, పెద్ద, మిథ్యా ప్రతిబింబం వస్తుంది.',
  use_proj_t: 'ప్రొజెక్టర్',
  use_proj_d: 'స్లైడ్ కుంభాకార కటకం F₁, 2F₁ ల మధ్య ఉంటుంది, కాబట్టి తెరపై పెద్ద, నిజ, తలకిందుల ప్రతిబింబం పడుతుంది. అందుకే స్లైడ్‌ను తలకిందులుగా పెడతారు.',
  use_cam_t: 'కెమెరా, మన కన్ను',
  use_cam_d: 'దూరపు వస్తువు (2F₁ కి ఆవల) సెన్సార్ లేదా రెటీనాపై చిన్న, నిజ, తలకిందుల ప్రతిబింబాన్ని ఏర్పరుస్తుంది.',
  use_spec_t: 'హ్రస్వదృష్టి కళ్లద్దాలు',
  use_spec_d: 'పుటాకార కటకం ఎప్పుడూ మిథ్యా, నిటారు, చిన్న ప్రతిబింబాన్ని ఇస్తుంది. హ్రస్వదృష్టి ఉన్నవారికి దూరం చూడడానికి ఇది సహాయపడుతుంది.',
  help_h: 'ఎలా వాడాలి / తరగతి గది కోసం ఆలోచనలు',
  help_1: 'దర్పణం లేదా కటకం ఎంచుకుని, నారింజ వస్తువును లాగండి (లేదా స్లైడర్ జరపండి). కిరణాలు, ప్రతిబింబం, అన్ని సంఖ్యలు వెంటనే మారతాయి.',
  help_2: 'రంగు బటన్లతో కిరణాలను ఆన్ లేదా ఆఫ్ చేయండి. ప్రతిబింబాన్ని కనుగొనడానికి ఏ రెండు కిరణాలైనా చాలు; చుక్కల గీతలు కిరణాలు ఎక్కడి నుంచి వస్తున్నట్టు కనిపిస్తాయో చూపిస్తాయి.',
  help_3: 'u, v, f, m లను వాటి గుర్తులతో చదవండి. సూత్రం పెట్టెలో ప్రతి సోపానం కనిపిస్తుంది, కాబట్టి విద్యార్థులు తమ లెక్కలు సరిచూసుకోవచ్చు.',
  help_4: 'NCERT పట్టికలో ఏదైనా వరుసను నొక్కితే వస్తువు ఆ స్థానానికి వెళ్తుంది. పేజీని ప్రింట్ చేస్తే చిత్రం, సాధన, పట్టిక కాగితంపై వస్తాయి.',
  help_5: 'తరగతి కృత్యం: ఒక విద్యార్థి వస్తువును జరుపుతుంటే, మిగతావారు చూడకముందే "నిజమా మిథ్యా, నిటారా తలకిందులా, పెద్దదా చిన్నదా" అని చెప్పాలి. తర్వాత జట్లుగా క్విజ్ ఆడండి.',
  help_6: 'ఇంట్లో ప్రయత్నించండి: మెరిసే స్టీల్ చెంచాలో చూడండి. లోపలి వైపు పుటాకార దర్పణంలా, వెనుక వైపు కుంభాకార దర్పణంలా పనిచేస్తుంది.'
};
window.APP_STRINGS.kn = {
  app_title: 'ಮಸೂರ ಮತ್ತು ದರ್ಪಣ ಕಿರಣ ಲ್ಯಾಬ್',
  intro: 'ದರ್ಪಣ ಅಥವಾ ಮಸೂರದ ಮುಂದೆ ವಸ್ತುವನ್ನು ಸರಿಸಿ, ಕಿರಣಗಳು ಪ್ರತಿಬಿಂಬವನ್ನು ಹೇಗೆ ಉಂಟುಮಾಡುತ್ತವೆ ಎಂದು ನೋಡಿ. ಚಿಹ್ನೆ ಸಂಪ್ರದಾಯ, ದರ್ಪಣ ಮತ್ತು ಮಸೂರದ ಸೂತ್ರಗಳು ಹಾಗೂ NCERT ಪ್ರತಿಬಿಂಬ ಕೋಷ್ಟಕಗಳನ್ನು ಕಲಿಯಿರಿ.',
  dev_label: 'ದರ್ಪಣ ಅಥವಾ ಮಸೂರ ಆಯ್ಕೆಮಾಡಿ',
  dev_concave_mirror: 'ನಿಮ್ನ ದರ್ಪಣ',
  dev_convex_mirror: 'ಪೀನ ದರ್ಪಣ',
  dev_convex_lens: 'ಪೀನ ಮಸೂರ',
  dev_concave_lens: 'ನಿಮ್ನ ಮಸೂರ',
  canvas_label: 'ಕಿರಣ ಚಿತ್ರ. ವಸ್ತುವನ್ನು ಎಳೆಯಿರಿ ಅಥವಾ ಬಾಣದ ಕೀಲಿಗಳಿಂದ ಸರಿಸಿ.',
  drag_hint: 'ಕಿತ್ತಳೆ ಬಣ್ಣದ ವಸ್ತುವನ್ನು ಅಕ್ಷದ ಮೇಲೆ ಎಳೆಯಿರಿ, ಅಥವಾ ಚಿತ್ರದ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ ← → ಕೀಲಿಗಳನ್ನು ಒತ್ತಿ.',
  not_to_scale: 'ಕಿರಣಗಳು ಸ್ಪಷ್ಟವಾಗಿ ಕಾಣಲೆಂದು ಎತ್ತರಗಳನ್ನು ದೂರಗಳಿಗಿಂತ ದೊಡ್ಡದಾಗಿ ಬರೆಯಲಾಗಿದೆ.',
  rays_label: 'ಕಿರಣಗಳು:',
  ray_par: 'ಅಕ್ಷಕ್ಕೆ ಸಮಾಂತರ',
  ray_c: 'C ಮೂಲಕ',
  ray_o: 'O ಮೂಲಕ',
  ray_f: 'F ಮೂಲಕ',
  ray_f1: 'F₁ ಮೂಲಕ',
  ray_f2: 'F₂ ಕಡೆಗೆ',
  ray_p: 'ಧ್ರುವ P ಯಲ್ಲಿ',
  ray_n: 'ಕಿರಣ {n}',
  ray_miss: 'ಈ ಸ್ಥಾನದಲ್ಲಿ ಕೆಲವು ಕಿರಣಗಳು ದರ್ಪಣ ಅಥವಾ ಮಸೂರವನ್ನು ತಲುಪುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ ಅವನ್ನು ಬರೆದಿಲ್ಲ (ಗೆರೆ ಅಂಚಿನ ಗುಂಡಿಗಳು).',
  f_label: 'ಸಂಗಮ ದೂರ |f|',
  u_label: 'ವಸ್ತುವಿನ ದೂರ |u|',
  h_label: 'ವಸ್ತುವಿನ ಎತ್ತರ h',
  far_btn: 'ಬಹಳ ದೂರ (∞)',
  save_png: 'ಚಿತ್ರ ಉಳಿಸಿ',
  lbl_object: 'ವಸ್ತು',
  lbl_image: 'ಪ್ರತಿಬಿಂಬ',
  light_dir: 'ಬೆಳಕು',
  side_front: 'ಮುಂದೆ: ಸತ್ಯ ಪ್ರತಿಬಿಂಬ',
  side_behind: 'ಹಿಂದೆ: ಮಿಥ್ಯಾ ಪ್ರತಿಬಿಂಬ',
  side_obj: 'ವಸ್ತುವಿನ ಕಡೆ: ಮಿಥ್ಯಾ ಪ್ರತಿಬಿಂಬ',
  side_other: 'ಇನ್ನೊಂದು ಕಡೆ: ಸತ್ಯ ಪ್ರತಿಬಿಂಬ',
  note_point: 'ವಸ್ತು ಬಹಳ ದೂರದಲ್ಲಿದೆ: ಕಿರಣಗಳು ಸಮಾಂತರವಾಗಿ ಬಂದು ಸಂಗಮದಲ್ಲಿ ಬಿಂದುವಿನಷ್ಟು ಪ್ರತಿಬಿಂಬ ಉಂಟುಮಾಡುತ್ತವೆ.',
  note_inf_img: 'ಕಿರಣಗಳು ಸಮಾಂತರವಾಗಿ ಹೊರಬರುತ್ತವೆ, ಆದ್ದರಿಂದ ಪ್ರತಿಬಿಂಬ ಅನಂತದಲ್ಲಿ ಉಂಟಾಗುತ್ತದೆ.',
  note_off: 'ಪ್ರತಿಬಿಂಬ ಚಿತ್ರದ ಹೊರಗೆ, v = {v} ನಲ್ಲಿದೆ.',
  res_h: 'ಫಲಿತಾಂಶ (ಚಿಹ್ನೆಗಳೊಂದಿಗೆ)',
  r_u: 'ವಸ್ತುವಿನ ದೂರ u',
  r_v: 'ಪ್ರತಿಬಿಂಬದ ದೂರ v',
  r_f: 'ಸಂಗಮ ದೂರ f',
  r_m: 'ವರ್ಧನೆ m',
  r_h: 'ವಸ್ತುವಿನ ಎತ್ತರ h',
  r_h2: 'ಪ್ರತಿಬಿಂಬದ ಎತ್ತರ h′',
  r_p: 'ಸಾಮರ್ಥ್ಯ P',
  r_obj_pos: 'ವಸ್ತು:',
  r_img_pos: 'ಪ್ರತಿಬಿಂಬ:',
  nat_real: 'ಸತ್ಯ',
  nat_virtual: 'ಮಿಥ್ಯಾ',
  nat_inverted: 'ತಲೆಕೆಳಗಾದ',
  nat_erect: 'ನೇರ',
  size_point: 'ಅತಿ ಚಿಕ್ಕದು, ಬಿಂದುವಿನಷ್ಟು',
  size_dim: 'ಚಿಕ್ಕದು',
  size_same: 'ಅದೇ ಗಾತ್ರ',
  size_big: 'ದೊಡ್ಡದು',
  size_huge: 'ಅತಿ ದೊಡ್ಡದು',
  why_obj_inf: 'ಬಹಳ ದೂರದ ವಸ್ತುವಿನಿಂದ ಕಿರಣಗಳು ಅಕ್ಷಕ್ಕೆ ಸಮಾಂತರವಾಗಿ ಬರುತ್ತವೆ, ಆದ್ದರಿಂದ ಅವು ಸಂಗಮದಲ್ಲಿ ಸೇರುತ್ತವೆ (ಅಥವಾ ಅಲ್ಲಿಂದ ಬಂದಂತೆ ಕಾಣುತ್ತವೆ).',
  why_inf: 'ಹೊರಬರುವ ಕಿರಣಗಳು ಒಂದಕ್ಕೊಂದು ಸಮಾಂತರವಾಗಿವೆ, ಆದ್ದರಿಂದ ಅವು ಅನಂತದಲ್ಲಿ ಮಾತ್ರ ಸೇರುತ್ತವೆ.',
  why_mirror_real: 'v ಋಣಾತ್ಮಕ: ಪ್ರತಿಬಿಂಬ ದರ್ಪಣದ ಮುಂದೆ ಇದೆ, ಅಲ್ಲಿ ಪ್ರತಿಫಲಿತ ಕಿರಣಗಳು ನಿಜವಾಗಿಯೂ ಸೇರುತ್ತವೆ. ಆದ್ದರಿಂದ ಇದು ಸತ್ಯ ಪ್ರತಿಬಿಂಬ.',
  why_mirror_virtual: 'v ಧನಾತ್ಮಕ: ಪ್ರತಿಬಿಂಬ ದರ್ಪಣದ ಹಿಂದೆ ಇದೆ. ಕಿರಣಗಳು ಅಲ್ಲಿಂದ ಬಂದಂತೆ ಮಾತ್ರ ಕಾಣುತ್ತವೆ, ಆದ್ದರಿಂದ ಇದು ಮಿಥ್ಯಾ ಪ್ರತಿಬಿಂಬ.',
  why_lens_real: 'v ಧನಾತ್ಮಕ: ಪ್ರತಿಬಿಂಬ ಮಸೂರದ ಇನ್ನೊಂದು ಕಡೆ ಇದೆ, ಅಲ್ಲಿ ಕಿರಣಗಳು ನಿಜವಾಗಿಯೂ ಸೇರುತ್ತವೆ. ಆದ್ದರಿಂದ ಇದು ಸತ್ಯ ಪ್ರತಿಬಿಂಬ.',
  why_lens_virtual: 'v ಋಣಾತ್ಮಕ: ಪ್ರತಿಬಿಂಬ ವಸ್ತುವಿನ ಕಡೆಯೇ ಇದೆ. ಕಿರಣಗಳು ಅಲ್ಲಿಂದ ಬಂದಂತೆ ಮಾತ್ರ ಕಾಣುತ್ತವೆ, ಆದ್ದರಿಂದ ಇದು ಮಿಥ್ಯಾ ಪ್ರತಿಬಿಂಬ.',
  why_m_neg: 'm ಋಣಾತ್ಮಕ, ಆದ್ದರಿಂದ ಪ್ರತಿಬಿಂಬ ತಲೆಕೆಳಗಾಗಿದೆ.',
  why_m_pos: 'm ಧನಾತ್ಮಕ, ಆದ್ದರಿಂದ ಪ್ರತಿಬಿಂಬ ನೇರವಾಗಿದೆ.',
  why_m_big: 'ಚಿಹ್ನೆ ಬಿಟ್ಟು m ನ ಬೆಲೆ 1 ಕ್ಕಿಂತ ಹೆಚ್ಚು, ಆದ್ದರಿಂದ ಪ್ರತಿಬಿಂಬ ದೊಡ್ಡದು.',
  why_m_small: 'ಚಿಹ್ನೆ ಬಿಟ್ಟು m ನ ಬೆಲೆ 1 ಕ್ಕಿಂತ ಕಡಿಮೆ, ಆದ್ದರಿಂದ ಪ್ರತಿಬಿಂಬ ಚಿಕ್ಕದು.',
  why_m_same: 'ಚಿಹ್ನೆ ಬಿಟ್ಟು m ನ ಬೆಲೆ 1, ಆದ್ದರಿಂದ ಪ್ರತಿಬಿಂಬ ವಸ್ತುವಿನಷ್ಟೇ ಇದೆ.',
  form_h: 'ಸೂತ್ರದಿಂದ ಪರಿಶೀಲಿಸಿ',
  form_mirror: 'ದರ್ಪಣ ಸೂತ್ರ',
  form_lens: 'ಮಸೂರ ಸೂತ್ರ',
  form_mag: 'ವರ್ಧನೆ',
  form_power: 'ಮಸೂರದ ಸಾಮರ್ಥ್ಯ (f ಮೀಟರ್‌ಗಳಲ್ಲಿ; f cm ನಲ್ಲಿದ್ದರೆ 100/f)',
  table_h: 'NCERT ಕೋಷ್ಟಕ: ಪ್ರತಿಬಿಂಬ ಎಲ್ಲಿ ಉಂಟಾಗುತ್ತದೆ?',
  table_tip: 'ವಸ್ತುವನ್ನು ಆ ಸ್ಥಾನದಲ್ಲಿ ಇಡಲು ಯಾವುದಾದರೂ ಸಾಲನ್ನು ಒತ್ತಿ.',
  th_obj: 'ವಸ್ತುವಿನ ಸ್ಥಾನ',
  th_img: 'ಪ್ರತಿಬಿಂಬದ ಸ್ಥಾನ',
  th_size: 'ಪ್ರತಿಬಿಂಬದ ಗಾತ್ರ',
  th_nature: 'ಪ್ರತಿಬಿಂಬದ ಸ್ವರೂಪ',
  nature_ri: 'ಸತ್ಯ ಮತ್ತು ತಲೆಕೆಳಗಾದ',
  nature_ve: 'ಮಿಥ್ಯಾ ಮತ್ತು ನೇರ',
  pos_inf: 'ಅನಂತದಲ್ಲಿ',
  pos_beyond_c: 'C ಯ ಆಚೆ',
  pos_at_c: 'C ಯಲ್ಲಿ',
  pos_c_f: 'C ಮತ್ತು F ನಡುವೆ',
  pos_f_c: 'F ಮತ್ತು C ನಡುವೆ',
  pos_at_f: 'F ನಲ್ಲಿ',
  pos_p_f: 'P ಮತ್ತು F ನಡುವೆ',
  pos_behind: 'ದರ್ಪಣದ ಹಿಂದೆ',
  pos_inf_p: 'ಅನಂತ ಮತ್ತು ಧ್ರುವ P ನಡುವೆ',
  pos_behind_pf: 'ದರ್ಪಣದ ಹಿಂದೆ, P ಮತ್ತು F ನಡುವೆ',
  pos_behind_f: 'ದರ್ಪಣದ ಹಿಂದೆ, F ನಲ್ಲಿ',
  pos_beyond_2f1: '2F₁ ರ ಆಚೆ',
  pos_at_2f1: '2F₁ ನಲ್ಲಿ',
  pos_f1_2f1: 'F₁ ಮತ್ತು 2F₁ ನಡುವೆ',
  pos_at_f1: 'F₁ ನಲ್ಲಿ',
  pos_f1_o: 'F₁ ಮತ್ತು ದೃಕ್ ಕೇಂದ್ರ O ನಡುವೆ',
  pos_at_f2: 'F₂ ನಲ್ಲಿ',
  pos_f2_2f2: 'F₂ ಮತ್ತು 2F₂ ನಡುವೆ',
  pos_at_2f2: '2F₂ ನಲ್ಲಿ',
  pos_beyond_2f2: '2F₂ ರ ಆಚೆ',
  pos_same_side: 'ವಸ್ತು ಇರುವ ಕಡೆಯೇ',
  pos_inf_o: 'ಅನಂತ ಮತ್ತು ದೃಕ್ ಕೇಂದ್ರ O ನಡುವೆ',
  sign_h: 'ಹೊಸ ಕಾರ್ಟೀಸಿಯನ್ ಚಿಹ್ನೆ ಸಂಪ್ರದಾಯ',
  sign_1: 'ಪ್ರತಿಯೊಂದು ದೂರವನ್ನು ದರ್ಪಣದ ಧ್ರುವ P ಅಥವಾ ಮಸೂರದ ದೃಕ್ ಕೇಂದ್ರ O ನಿಂದ ಅಳೆಯಿರಿ.',
  sign_2: 'ಬೆಳಕು ಎಡದಿಂದ ಬರುತ್ತದೆ. ಬಲಕ್ಕಿರುವ (ಬೆಳಕಿನ ದಿಕ್ಕಿನ) ದೂರಗಳು ಧನಾತ್ಮಕ (+), ಎಡಕ್ಕಿರುವ ದೂರಗಳು ಋಣಾತ್ಮಕ (−).',
  sign_3: 'ಆದ್ದರಿಂದ ಇಲ್ಲಿ ವಸ್ತುವಿನ ದೂರ u ಯಾವಾಗಲೂ ಋಣಾತ್ಮಕ.',
  sign_4: 'ಪ್ರಧಾನ ಅಕ್ಷದ ಮೇಲಿನ ಎತ್ತರ ಧನಾತ್ಮಕ, ಕೆಳಗಿನ ಎತ್ತರ ಋಣಾತ್ಮಕ.',
  sign_5: 'ನಿಮ್ನ ದರ್ಪಣ ಮತ್ತು ನಿಮ್ನ ಮಸೂರಕ್ಕೆ f ಋಣಾತ್ಮಕ; ಪೀನ ದರ್ಪಣ ಮತ್ತು ಪೀನ ಮಸೂರಕ್ಕೆ f ಧನಾತ್ಮಕ.',
  quiz_h: 'ರಸಪ್ರಶ್ನೆ: ಪ್ರತಿಬಿಂಬವನ್ನು ಊಹಿಸಿ',
  quiz_q: 'ವಸ್ತುವಿನ ದೂರ {u}, ಸಂಗಮ ದೂರ {f}. ಎಂತಹ ಪ್ರತಿಬಿಂಬ ಉಂಟಾಗುತ್ತದೆ?',
  quiz_q_inf: 'ವಸ್ತು ಬಹಳ ದೂರದಲ್ಲಿದೆ (ಅನಂತದಲ್ಲಿ). ಸಂಗಮ ದೂರ {f}. ಎಂತಹ ಪ್ರತಿಬಿಂಬ ಉಂಟಾಗುತ್ತದೆ?',
  q_pos: 'ಪ್ರತಿಬಿಂಬದ ಸ್ಥಾನ',
  q_nature: 'ಸತ್ಯವೇ, ಮಿಥ್ಯಾವೇ?',
  q_orient: 'ನೇರವೇ, ತಲೆಕೆಳಗೇ?',
  q_size: 'ಪ್ರತಿಬಿಂಬದ ಗಾತ್ರ',
  q_choose: 'ಆಯ್ಕೆಮಾಡಿ…',
  q_check: 'ಉತ್ತರ ಪರಿಶೀಲಿಸಿ',
  q_next: 'ಹೊಸ ಪ್ರಶ್ನೆ',
  q_show: 'ಲ್ಯಾಬ್‌ನಲ್ಲಿ ನೋಡಿ',
  q_score: 'ಅಂಕ: {a} / {b}',
  q_need: 'ಮೊದಲು ನಾಲ್ಕೂ ಭಾಗಗಳಿಗೆ ಉತ್ತರಿಸಿ.',
  q_right: 'ಭೇಷ್! ನಾಲ್ಕೂ ಭಾಗಗಳು ಸರಿ.',
  q_wrong: 'ಪೂರ್ತಿ ಸರಿಯಿಲ್ಲ: 4 ರಲ್ಲಿ {n} ಭಾಗಗಳು ಸರಿ. ಕೆಳಗೆ ಸರಿಯಾದ ಉತ್ತರ ನೋಡಿ.',
  q_hint: 'ಇಲ್ಲಿ ದರ್ಪಣ ಅಥವಾ ಮಸೂರದಿಂದ F {f} ದೂರದಲ್ಲಿ ಮತ್ತು C (ಅಥವಾ 2F) {c} ದೂರದಲ್ಲಿದೆ.',
  uses_h: 'ಇವುಗಳನ್ನು ಎಲ್ಲಿ ಬಳಸುತ್ತೇವೆ?',
  use_show: 'ತೋರಿಸಿ',
  use_torch_t: 'ಟಾರ್ಚ್ ಮತ್ತು ವಾಹನದ ಹೆಡ್‌ಲೈಟ್',
  use_torch_d: 'ಬಲ್ಬ್ ನಿಮ್ನ ದರ್ಪಣದ ಸಂಗಮದಲ್ಲಿರುತ್ತದೆ, ಆದ್ದರಿಂದ ಬೆಳಕು ಪ್ರಬಲ ಸಮಾಂತರ ಕಿರಣಪುಂಜವಾಗಿ ಹೊರಹೋಗುತ್ತದೆ.',
  use_solar_t: 'ಸೌರ ಕುಕ್ಕರ್ ಮತ್ತು ಸೌರ ಕುಲುಮೆ',
  use_solar_d: 'ಸೂರ್ಯನ ಬೆಳಕು ಬಹಳ ದೂರದಿಂದ ಬರುತ್ತದೆ, ಆದ್ದರಿಂದ ನಿಮ್ನ ದರ್ಪಣ ಅದನ್ನು ಸಂಗಮದಲ್ಲಿ ಕೇಂದ್ರೀಕರಿಸಿ ಹೆಚ್ಚು ಶಾಖ ಉಂಟುಮಾಡುತ್ತದೆ.',
  use_shave_t: 'ಕ್ಷೌರ ಮತ್ತು ಮೇಕಪ್ ಕನ್ನಡಿ',
  use_shave_d: 'ಮುಖವನ್ನು ನಿಮ್ನ ದರ್ಪಣದ P ಮತ್ತು F ನಡುವೆ ಇಟ್ಟರೆ ನೇರ ಮತ್ತು ದೊಡ್ಡ ಪ್ರತಿಬಿಂಬ ಕಾಣುತ್ತದೆ.',
  use_rear_t: 'ಹಿಂನೋಟದ ಕನ್ನಡಿ',
  use_rear_d: 'ಪೀನ ದರ್ಪಣ ಯಾವಾಗಲೂ ನೇರ ಮತ್ತು ಚಿಕ್ಕ ಪ್ರತಿಬಿಂಬ ಕೊಡುತ್ತದೆ ಮತ್ತು ವಾಹನದ ಹಿಂದಿನ ವಿಶಾಲ ಪ್ರದೇಶವನ್ನು ತೋರಿಸುತ್ತದೆ.',
  use_mag_t: 'ಭೂತಗನ್ನಡಿ',
  use_mag_d: 'ವಸ್ತುವನ್ನು ಪೀನ ಮಸೂರದ F₁ ಮತ್ತು O ನಡುವೆ ಇಟ್ಟರೆ ನೇರ, ದೊಡ್ಡ, ಮಿಥ್ಯಾ ಪ್ರತಿಬಿಂಬ ಸಿಗುತ್ತದೆ.',
  use_proj_t: 'ಪ್ರೊಜೆಕ್ಟರ್',
  use_proj_d: 'ಸ್ಲೈಡ್ ಪೀನ ಮಸೂರದ F₁ ಮತ್ತು 2F₁ ನಡುವೆ ಇರುತ್ತದೆ, ಆದ್ದರಿಂದ ಪರದೆಯ ಮೇಲೆ ದೊಡ್ಡ, ಸತ್ಯ, ತಲೆಕೆಳಗಾದ ಪ್ರತಿಬಿಂಬ ಬೀಳುತ್ತದೆ. ಅದಕ್ಕೇ ಸ್ಲೈಡ್ ಅನ್ನು ತಲೆಕೆಳಗಾಗಿ ಇಡುತ್ತಾರೆ.',
  use_cam_t: 'ಕ್ಯಾಮೆರಾ ಮತ್ತು ನಮ್ಮ ಕಣ್ಣು',
  use_cam_d: 'ದೂರದ ವಸ್ತು (2F₁ ರ ಆಚೆ) ಸೆನ್ಸರ್ ಅಥವಾ ಅಕ್ಷಿಪಟಲದ ಮೇಲೆ ಚಿಕ್ಕ, ಸತ್ಯ, ತಲೆಕೆಳಗಾದ ಪ್ರತಿಬಿಂಬ ಉಂಟುಮಾಡುತ್ತದೆ.',
  use_spec_t: 'ಸಮೀಪದೃಷ್ಟಿಯ ಕನ್ನಡಕ',
  use_spec_d: 'ನಿಮ್ನ ಮಸೂರ ಯಾವಾಗಲೂ ಮಿಥ್ಯಾ, ನೇರ, ಚಿಕ್ಕ ಪ್ರತಿಬಿಂಬ ಕೊಡುತ್ತದೆ. ಸಮೀಪದೃಷ್ಟಿ ಇರುವವರಿಗೆ ದೂರ ನೋಡಲು ಇದು ಸಹಾಯಮಾಡುತ್ತದೆ.',
  help_h: 'ಬಳಸುವುದು ಹೇಗೆ / ತರಗತಿಗೆ ಸಲಹೆಗಳು',
  help_1: 'ದರ್ಪಣ ಅಥವಾ ಮಸೂರ ಆಯ್ಕೆಮಾಡಿ, ನಂತರ ಕಿತ್ತಳೆ ವಸ್ತುವನ್ನು ಎಳೆಯಿರಿ (ಅಥವಾ ಸ್ಲೈಡರ್ ಸರಿಸಿ). ಕಿರಣಗಳು, ಪ್ರತಿಬಿಂಬ ಮತ್ತು ಎಲ್ಲಾ ಸಂಖ್ಯೆಗಳು ತಕ್ಷಣ ಬದಲಾಗುತ್ತವೆ.',
  help_2: 'ಬಣ್ಣದ ಗುಂಡಿಗಳಿಂದ ಕಿರಣಗಳನ್ನು ಆನ್ ಅಥವಾ ಆಫ್ ಮಾಡಿ. ಪ್ರತಿಬಿಂಬ ಕಂಡುಹಿಡಿಯಲು ಯಾವುದೇ ಎರಡು ಕಿರಣಗಳು ಸಾಕು; ಚುಕ್ಕೆ ಗೆರೆಗಳು ಕಿರಣಗಳು ಎಲ್ಲಿಂದ ಬಂದಂತೆ ಕಾಣುತ್ತವೆ ಎಂದು ತೋರಿಸುತ್ತವೆ.',
  help_3: 'u, v, f ಮತ್ತು m ಅನ್ನು ಅವುಗಳ ಚಿಹ್ನೆಗಳೊಂದಿಗೆ ಓದಿ. ಸೂತ್ರದ ಪೆಟ್ಟಿಗೆಯಲ್ಲಿ ಪ್ರತಿ ಹಂತ ಕಾಣುತ್ತದೆ, ಆದ್ದರಿಂದ ವಿದ್ಯಾರ್ಥಿಗಳು ತಮ್ಮ ಲೆಕ್ಕಗಳನ್ನು ಪರಿಶೀಲಿಸಬಹುದು.',
  help_4: 'NCERT ಕೋಷ್ಟಕದ ಯಾವುದಾದರೂ ಸಾಲನ್ನು ಒತ್ತಿದರೆ ವಸ್ತು ಆ ಸ್ಥಾನಕ್ಕೆ ಹೋಗುತ್ತದೆ. ಪುಟವನ್ನು ಮುದ್ರಿಸಿದರೆ ಚಿತ್ರ, ಬಿಡಿಸುವಿಕೆ ಮತ್ತು ಕೋಷ್ಟಕ ಕಾಗದದಲ್ಲಿ ಸಿಗುತ್ತವೆ.',
  help_5: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿ ವಸ್ತುವನ್ನು ಸರಿಸಲಿ, ಉಳಿದವರು ನೋಡುವ ಮೊದಲೇ "ಸತ್ಯವೇ ಮಿಥ್ಯಾವೇ, ನೇರವೇ ತಲೆಕೆಳಗೇ, ದೊಡ್ಡದೇ ಚಿಕ್ಕದೇ" ಎಂದು ಹೇಳಲಿ. ನಂತರ ತಂಡಗಳಲ್ಲಿ ರಸಪ್ರಶ್ನೆ ಆಡಿ.',
  help_6: 'ಮನೆಯಲ್ಲಿ ಮಾಡಿ ನೋಡಿ: ಹೊಳೆಯುವ ಸ್ಟೀಲ್ ಚಮಚದಲ್ಲಿ ನೋಡಿ. ಒಳಭಾಗ ನಿಮ್ನ ದರ್ಪಣದಂತೆ, ಹಿಂಭಾಗ ಪೀನ ದರ್ಪಣದಂತೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ.'
};
window.APP_STRINGS.ml = {
  app_title: 'ലെൻസ് & ദർപ്പണ രശ്മി ലാബ്',
  intro: 'ദർപ്പണത്തിന്റെയോ ലെൻസിന്റെയോ മുന്നിൽ വസ്തു നീക്കി, രശ്മികൾ പ്രതിബിംബം ഉണ്ടാക്കുന്നത് എങ്ങനെയെന്ന് കാണുക. ചിഹ്നരീതി, ദർപ്പണ-ലെൻസ് സൂത്രവാക്യങ്ങൾ, NCERT പ്രതിബിംബ പട്ടികകൾ എന്നിവ പഠിക്കാം.',
  dev_label: 'ദർപ്പണമോ ലെൻസോ തിരഞ്ഞെടുക്കുക',
  dev_concave_mirror: 'കോൺകേവ് ദർപ്പണം',
  dev_convex_mirror: 'കോൺവെക്സ് ദർപ്പണം',
  dev_convex_lens: 'കോൺവെക്സ് ലെൻസ്',
  dev_concave_lens: 'കോൺകേവ് ലെൻസ്',
  canvas_label: 'രശ്മി ചിത്രം. വസ്തുവിനെ വലിച്ചു നീക്കുക, അല്ലെങ്കിൽ ആരോ കീകൾ ഉപയോഗിക്കുക.',
  drag_hint: 'ഓറഞ്ച് നിറത്തിലുള്ള വസ്തുവിനെ അക്ഷത്തിലൂടെ വലിക്കുക, അല്ലെങ്കിൽ ചിത്രത്തിൽ ക്ലിക്ക് ചെയ്ത് ← → കീകൾ അമർത്തുക.',
  not_to_scale: 'രശ്മികൾ വ്യക്തമായി കാണാൻ ഉയരങ്ങൾ ദൂരങ്ങളെക്കാൾ വലുതായി വരച്ചിരിക്കുന്നു.',
  rays_label: 'രശ്മികൾ:',
  ray_par: 'അക്ഷത്തിന് സമാന്തരം',
  ray_c: 'C യിലൂടെ',
  ray_o: 'O യിലൂടെ',
  ray_f: 'F ലൂടെ',
  ray_f1: 'F₁ ലൂടെ',
  ray_f2: 'F₂ ലേക്ക്',
  ray_p: 'പോൾ P യിൽ',
  ray_n: 'രശ്മി {n}',
  ray_miss: 'ഈ സ്ഥാനത്ത് ചില രശ്മികൾ ദർപ്പണത്തിലോ ലെൻസിലോ എത്തുന്നില്ല, അതിനാൽ അവ വരച്ചിട്ടില്ല (ഡാഷ് അരികുള്ള ബട്ടണുകൾ).',
  f_label: 'ഫോക്കസ് ദൂരം |f|',
  u_label: 'വസ്തുവിലേക്കുള്ള ദൂരം |u|',
  h_label: 'വസ്തുവിന്റെ ഉയരം h',
  far_btn: 'വളരെ അകലെ (∞)',
  save_png: 'ചിത്രം സേവ് ചെയ്യുക',
  lbl_object: 'വസ്തു',
  lbl_image: 'പ്രതിബിംബം',
  light_dir: 'പ്രകാശം',
  side_front: 'മുന്നിൽ: യഥാർഥ പ്രതിബിംബം',
  side_behind: 'പിന്നിൽ: മിഥ്യാ പ്രതിബിംബം',
  side_obj: 'വസ്തുവിന്റെ വശം: മിഥ്യാ പ്രതിബിംബം',
  side_other: 'മറുവശം: യഥാർഥ പ്രതിബിംബം',
  note_point: 'വസ്തു വളരെ അകലെയാണ്: രശ്മികൾ സമാന്തരമായി വന്ന് ഫോക്കസിൽ ഒരു ബിന്ദുവോളം ചെറിയ പ്രതിബിംബം ഉണ്ടാക്കുന്നു.',
  note_inf_img: 'രശ്മികൾ സമാന്തരമായി പുറത്തുവരുന്നു, അതിനാൽ പ്രതിബിംബം അനന്തതയിൽ രൂപപ്പെടുന്നു.',
  note_off: 'പ്രതിബിംബം ചിത്രത്തിന് പുറത്താണ്, v = {v} ൽ.',
  res_h: 'ഫലങ്ങൾ (ചിഹ്നങ്ങളോടെ)',
  r_u: 'വസ്തു ദൂരം u',
  r_v: 'പ്രതിബിംബ ദൂരം v',
  r_f: 'ഫോക്കസ് ദൂരം f',
  r_m: 'ആവർധനം m',
  r_h: 'വസ്തുവിന്റെ ഉയരം h',
  r_h2: 'പ്രതിബിംബത്തിന്റെ ഉയരം h′',
  r_p: 'പവർ P',
  r_obj_pos: 'വസ്തു:',
  r_img_pos: 'പ്രതിബിംബം:',
  nat_real: 'യഥാർഥം',
  nat_virtual: 'മിഥ്യ',
  nat_inverted: 'തലകീഴായത്',
  nat_erect: 'നിവർന്നത്',
  size_point: 'വളരെ ചെറുത്, ബിന്ദുവോളം',
  size_dim: 'ചെറുത്',
  size_same: 'അതേ വലുപ്പം',
  size_big: 'വലുത്',
  size_huge: 'വളരെ വലുത്',
  why_obj_inf: 'വളരെ അകലെയുള്ള വസ്തുവിൽ നിന്നുള്ള രശ്മികൾ അക്ഷത്തിന് സമാന്തരമായി വരുന്നു, അതിനാൽ അവ ഫോക്കസിൽ സംഗമിക്കുന്നു (അല്ലെങ്കിൽ അവിടെ നിന്ന് വരുന്നതായി തോന്നുന്നു).',
  why_inf: 'പുറത്തുവരുന്ന രശ്മികൾ പരസ്പരം സമാന്തരമാണ്, അതിനാൽ അവ അനന്തതയിൽ മാത്രമേ സംഗമിക്കൂ.',
  why_mirror_real: 'v നെഗറ്റീവ്: പ്രതിബിംബം ദർപ്പണത്തിന് മുന്നിലാണ്, അവിടെ പ്രതിഫലിച്ച രശ്മികൾ ശരിക്കും സംഗമിക്കുന്നു. അതിനാൽ ഇത് യഥാർഥം.',
  why_mirror_virtual: 'v പോസിറ്റീവ്: പ്രതിബിംബം ദർപ്പണത്തിന് പിന്നിലാണ്. രശ്മികൾ അവിടെ നിന്ന് വരുന്നതായി തോന്നുക മാത്രമാണ്, അതിനാൽ ഇത് മിഥ്യ.',
  why_lens_real: 'v പോസിറ്റീവ്: പ്രതിബിംബം ലെൻസിന്റെ മറുവശത്താണ്, അവിടെ രശ്മികൾ ശരിക്കും സംഗമിക്കുന്നു. അതിനാൽ ഇത് യഥാർഥം.',
  why_lens_virtual: 'v നെഗറ്റീവ്: പ്രതിബിംബം വസ്തുവിന്റെ അതേ വശത്താണ്. രശ്മികൾ അവിടെ നിന്ന് വരുന്നതായി തോന്നുക മാത്രമാണ്, അതിനാൽ ഇത് മിഥ്യ.',
  why_m_neg: 'm നെഗറ്റീവ് ആണ്, അതിനാൽ പ്രതിബിംബം തലകീഴായതാണ്.',
  why_m_pos: 'm പോസിറ്റീവ് ആണ്, അതിനാൽ പ്രതിബിംബം നിവർന്നതാണ്.',
  why_m_big: 'ചിഹ്നം ഒഴിവാക്കിയാൽ m ന്റെ വില 1 നെക്കാൾ കൂടുതലാണ്, അതിനാൽ പ്രതിബിംബം വലുതാണ്.',
  why_m_small: 'ചിഹ്നം ഒഴിവാക്കിയാൽ m ന്റെ വില 1 നെക്കാൾ കുറവാണ്, അതിനാൽ പ്രതിബിംബം ചെറുതാണ്.',
  why_m_same: 'ചിഹ്നം ഒഴിവാക്കിയാൽ m ന്റെ വില 1 ആണ്, അതിനാൽ പ്രതിബിംബം വസ്തുവിന്റെ അതേ വലുപ്പമാണ്.',
  form_h: 'സൂത്രവാക്യം കൊണ്ട് പരിശോധിക്കുക',
  form_mirror: 'ദർപ്പണ സൂത്രവാക്യം',
  form_lens: 'ലെൻസ് സൂത്രവാക്യം',
  form_mag: 'ആവർധനം',
  form_power: 'ലെൻസിന്റെ പവർ (f മീറ്ററിൽ; f cm ൽ ആണെങ്കിൽ 100/f)',
  table_h: 'NCERT പട്ടിക: പ്രതിബിംബം എവിടെ ഉണ്ടാകും?',
  table_tip: 'വസ്തുവിനെ ആ സ്ഥാനത്ത് വയ്ക്കാൻ ഒരു വരിയിൽ ടാപ്പ് ചെയ്യുക.',
  th_obj: 'വസ്തുവിന്റെ സ്ഥാനം',
  th_img: 'പ്രതിബിംബത്തിന്റെ സ്ഥാനം',
  th_size: 'പ്രതിബിംബത്തിന്റെ വലുപ്പം',
  th_nature: 'പ്രതിബിംബത്തിന്റെ സ്വഭാവം',
  nature_ri: 'യഥാർഥം, തലകീഴായത്',
  nature_ve: 'മിഥ്യ, നിവർന്നത്',
  pos_inf: 'അനന്തതയിൽ',
  pos_beyond_c: 'C ക്ക് അപ്പുറം',
  pos_at_c: 'C യിൽ',
  pos_c_f: 'C ക്കും F നും ഇടയിൽ',
  pos_f_c: 'F നും C ക്കും ഇടയിൽ',
  pos_at_f: 'F ൽ',
  pos_p_f: 'P ക്കും F നും ഇടയിൽ',
  pos_behind: 'ദർപ്പണത്തിന് പിന്നിൽ',
  pos_inf_p: 'അനന്തതയ്ക്കും പോൾ P ക്കും ഇടയിൽ',
  pos_behind_pf: 'ദർപ്പണത്തിന് പിന്നിൽ, P ക്കും F നും ഇടയിൽ',
  pos_behind_f: 'ദർപ്പണത്തിന് പിന്നിൽ, F ൽ',
  pos_beyond_2f1: '2F₁ ന് അപ്പുറം',
  pos_at_2f1: '2F₁ ൽ',
  pos_f1_2f1: 'F₁ നും 2F₁ നും ഇടയിൽ',
  pos_at_f1: 'F₁ ൽ',
  pos_f1_o: 'F₁ നും പ്രകാശികകേന്ദ്രം O ക്കും ഇടയിൽ',
  pos_at_f2: 'F₂ ൽ',
  pos_f2_2f2: 'F₂ നും 2F₂ നും ഇടയിൽ',
  pos_at_2f2: '2F₂ ൽ',
  pos_beyond_2f2: '2F₂ ന് അപ്പുറം',
  pos_same_side: 'വസ്തു ഉള്ള അതേ വശത്ത്',
  pos_inf_o: 'അനന്തതയ്ക്കും പ്രകാശികകേന്ദ്രം O ക്കും ഇടയിൽ',
  sign_h: 'പുതിയ കാർട്ടീഷ്യൻ ചിഹ്നരീതി',
  sign_1: 'എല്ലാ ദൂരവും ദർപ്പണത്തിന്റെ പോൾ P യിൽ നിന്നോ ലെൻസിന്റെ പ്രകാശികകേന്ദ്രം O യിൽ നിന്നോ അളക്കുക.',
  sign_2: 'പ്രകാശം ഇടതുവശത്തു നിന്ന് വരുന്നു. വലതുവശത്തേക്കുള്ള (പ്രകാശത്തിന്റെ ദിശയിലുള്ള) ദൂരങ്ങൾ പോസിറ്റീവ് (+), ഇടതുവശത്തേക്കുള്ളവ നെഗറ്റീവ് (−).',
  sign_3: 'അതിനാൽ ഇവിടെ വസ്തു ദൂരം u എപ്പോഴും നെഗറ്റീവ് ആണ്.',
  sign_4: 'മുഖ്യ അക്ഷത്തിന് മുകളിലുള്ള ഉയരം പോസിറ്റീവ്, താഴെയുള്ളത് നെഗറ്റീവ്.',
  sign_5: 'കോൺകേവ് ദർപ്പണത്തിനും കോൺകേവ് ലെൻസിനും f നെഗറ്റീവ്; കോൺവെക്സ് ദർപ്പണത്തിനും കോൺവെക്സ് ലെൻസിനും f പോസിറ്റീവ്.',
  quiz_h: 'ക്വിസ്: പ്രതിബിംബം പ്രവചിക്കുക',
  quiz_q: 'വസ്തു ദൂരം {u}, ഫോക്കസ് ദൂരം {f}. ഏതുതരം പ്രതിബിംബം ഉണ്ടാകും?',
  quiz_q_inf: 'വസ്തു വളരെ അകലെയാണ് (അനന്തതയിൽ). ഫോക്കസ് ദൂരം {f}. ഏതുതരം പ്രതിബിംബം ഉണ്ടാകും?',
  q_pos: 'പ്രതിബിംബത്തിന്റെ സ്ഥാനം',
  q_nature: 'യഥാർഥമോ മിഥ്യയോ?',
  q_orient: 'നിവർന്നതോ തലകീഴായതോ?',
  q_size: 'പ്രതിബിംബത്തിന്റെ വലുപ്പം',
  q_choose: 'തിരഞ്ഞെടുക്കുക…',
  q_check: 'ഉത്തരം പരിശോധിക്കുക',
  q_next: 'പുതിയ ചോദ്യം',
  q_show: 'ലാബിൽ കാണുക',
  q_score: 'സ്കോർ: {a} / {b}',
  q_need: 'ആദ്യം നാലു ഭാഗങ്ങൾക്കും ഉത്തരം നൽകുക.',
  q_right: 'കൊള്ളാം! നാലു ഭാഗങ്ങളും ശരിയാണ്.',
  q_wrong: 'പൂർണമായി ശരിയല്ല: 4 ൽ {n} ഭാഗങ്ങൾ ശരി. ശരിയായ ഉത്തരം താഴെ കാണുക.',
  q_hint: 'ഇവിടെ ദർപ്പണത്തിൽ നിന്നോ ലെൻസിൽ നിന്നോ F {f} അകലെയും C (അല്ലെങ്കിൽ 2F) {c} അകലെയുമാണ്.',
  uses_h: 'ഇവ എവിടെയെല്ലാം ഉപയോഗിക്കുന്നു?',
  use_show: 'കാണിക്കുക',
  use_torch_t: 'ടോർച്ചും വാഹനങ്ങളുടെ ഹെഡ്‌ലൈറ്റും',
  use_torch_d: 'ബൾബ് കോൺകേവ് ദർപ്പണത്തിന്റെ ഫോക്കസിലാണ്, അതിനാൽ പ്രകാശം ശക്തമായ സമാന്തര രശ്മിപുഞ്ജമായി പുറത്തേക്ക് പോകുന്നു.',
  use_solar_t: 'സോളാർ കുക്കറും സൗര ചൂളയും',
  use_solar_d: 'സൂര്യപ്രകാശം വളരെ അകലെ നിന്ന് വരുന്നതിനാൽ കോൺകേവ് ദർപ്പണം അതിനെ ഫോക്കസിൽ കേന്ദ്രീകരിച്ച് വലിയ ചൂട് ഉണ്ടാക്കുന്നു.',
  use_shave_t: 'ഷേവിങ്ങിനും മേക്കപ്പിനുമുള്ള കണ്ണാടി',
  use_shave_d: 'മുഖം കോൺകേവ് ദർപ്പണത്തിന്റെ P ക്കും F നും ഇടയിൽ വച്ചാൽ നിവർന്നതും വലുതുമായ പ്രതിബിംബം കാണാം.',
  use_rear_t: 'റിയർ വ്യൂ മിറർ',
  use_rear_d: 'കോൺവെക്സ് ദർപ്പണം എപ്പോഴും നിവർന്നതും ചെറുതുമായ പ്രതിബിംബം നൽകുന്നു; വാഹനത്തിന് പിന്നിലെ വിശാലമായ ഭാഗം കാണിക്കുന്നു.',
  use_mag_t: 'ഭൂതക്കണ്ണാടി',
  use_mag_d: 'വസ്തുവിനെ കോൺവെക്സ് ലെൻസിന്റെ F₁ നും O ക്കും ഇടയിൽ വച്ചാൽ നിവർന്നതും വലുതുമായ മിഥ്യാ പ്രതിബിംബം കിട്ടും.',
  use_proj_t: 'പ്രൊജക്ടർ',
  use_proj_d: 'സ്ലൈഡ് കോൺവെക്സ് ലെൻസിന്റെ F₁ നും 2F₁ നും ഇടയിലാണ്, അതിനാൽ സ്ക്രീനിൽ വലുതും യഥാർഥവും തലകീഴായതുമായ പ്രതിബിംബം വീഴുന്നു. അതുകൊണ്ടാണ് സ്ലൈഡ് തലകീഴായി വയ്ക്കുന്നത്.',
  use_cam_t: 'ക്യാമറയും നമ്മുടെ കണ്ണും',
  use_cam_d: 'അകലെയുള്ള വസ്തു (2F₁ ന് അപ്പുറം) സെൻസറിലോ റെറ്റിനയിലോ ചെറുതും യഥാർഥവും തലകീഴായതുമായ പ്രതിബിംബം ഉണ്ടാക്കുന്നു.',
  use_spec_t: 'ഹ്രസ്വദൃഷ്ടിക്കുള്ള കണ്ണട',
  use_spec_d: 'കോൺകേവ് ലെൻസ് എപ്പോഴും മിഥ്യയും നിവർന്നതും ചെറുതുമായ പ്രതിബിംബം നൽകുന്നു. ഹ്രസ്വദൃഷ്ടിയുള്ളവർക്ക് ദൂരെ കാണാൻ ഇത് സഹായിക്കുന്നു.',
  help_h: 'ഉപയോഗിക്കുന്ന വിധം / ക്ലാസ്മുറിക്കുള്ള ആശയങ്ങൾ',
  help_1: 'ദർപ്പണമോ ലെൻസോ തിരഞ്ഞെടുത്ത് ഓറഞ്ച് വസ്തുവിനെ വലിക്കുക (അല്ലെങ്കിൽ സ്ലൈഡർ നീക്കുക). രശ്മികളും പ്രതിബിംബവും എല്ലാ സംഖ്യകളും ഉടനെ മാറും.',
  help_2: 'നിറമുള്ള ബട്ടണുകൾ കൊണ്ട് രശ്മികൾ ഓൺ അല്ലെങ്കിൽ ഓഫ് ചെയ്യുക. പ്രതിബിംബം കണ്ടെത്താൻ ഏതെങ്കിലും രണ്ട് രശ്മികൾ മതി; രശ്മികൾ എവിടെ നിന്ന് വരുന്നതായി തോന്നുന്നു എന്ന് ഡാഷ് വരകൾ കാണിക്കുന്നു.',
  help_3: 'u, v, f, m എന്നിവ അവയുടെ ചിഹ്നങ്ങളോടെ വായിക്കുക. സൂത്രവാക്യ പെട്ടിയിൽ ഓരോ ഘട്ടവും കാണാം, അതിനാൽ വിദ്യാർഥികൾക്ക് സ്വന്തം ഗണിതപ്രശ്നങ്ങൾ പരിശോധിക്കാം.',
  help_4: 'NCERT പട്ടികയിലെ ഒരു വരിയിൽ ടാപ്പ് ചെയ്താൽ വസ്തു ആ സ്ഥാനത്തേക്ക് നീങ്ങും. പേജ് പ്രിന്റ് ചെയ്താൽ ചിത്രവും നിർധാരണവും പട്ടികയും കടലാസിൽ കിട്ടും.',
  help_5: 'ക്ലാസ് പ്രവർത്തനം: ഒരു വിദ്യാർഥി വസ്തു നീക്കുമ്പോൾ മറ്റുള്ളവർ നോക്കുന്നതിന് മുമ്പ് "യഥാർഥമോ മിഥ്യയോ, നിവർന്നതോ തലകീഴോ, വലുതോ ചെറുതോ" എന്ന് പറയട്ടെ. പിന്നെ ടീമുകളായി ക്വിസ് കളിക്കുക.',
  help_6: 'വീട്ടിൽ ചെയ്തുനോക്കൂ: തിളങ്ങുന്ന സ്റ്റീൽ സ്പൂണിൽ നോക്കുക. ഉൾവശം കോൺകേവ് ദർപ്പണം പോലെയും പിൻവശം കോൺവെക്സ് ദർപ്പണം പോലെയും പ്രവർത്തിക്കുന്നു.'
};
window.APP_STRINGS.ur = {
  app_title: 'عدسہ اور آئینہ شعاع لیب',
  intro: 'آئینے یا عدسے کے سامنے شے کو کھسکائیں اور دیکھیں کہ شعاعیں عکس کیسے بناتی ہیں۔ علامتوں کا اصول، آئینے اور عدسے کے فارمولے اور NCERT کے عکس والے جدول سیکھیں۔',
  dev_label: 'آئینہ یا عدسہ چنیں',
  dev_concave_mirror: 'مقعر آئینہ',
  dev_convex_mirror: 'محدب آئینہ',
  dev_convex_lens: 'محدب عدسہ',
  dev_concave_lens: 'مقعر عدسہ',
  canvas_label: 'شعاعی خاکہ۔ شے کو کھینچیں یا تیر والی کلیدوں سے کھسکائیں۔',
  drag_hint: 'نارنجی شے کو محور پر کھینچیں، یا تصویر پر کلک کر کے ← → کلیدیں دبائیں۔',
  not_to_scale: 'شعاعیں صاف دکھانے کے لیے اونچائیاں فاصلوں سے بڑی بنائی گئی ہیں۔',
  rays_label: 'شعاعیں:',
  ray_par: 'محور کے متوازی',
  ray_c: 'C سے ہو کر',
  ray_o: 'O سے ہو کر',
  ray_f: 'F سے ہو کر',
  ray_f1: 'F₁ سے ہو کر',
  ray_f2: 'F₂ کی طرف',
  ray_p: 'قطب P پر',
  ray_n: 'شعاع {n}',
  ray_miss: 'اس جگہ کچھ شعاعیں آئینے یا عدسے تک نہیں پہنچتیں، اس لیے وہ نہیں بنائی گئیں (ڈیش والے بٹن)۔',
  f_label: 'فوکسی فاصلہ ‎|f|‎',
  u_label: 'شے کا فاصلہ ‎|u|‎',
  h_label: 'شے کی اونچائی h',
  far_btn: 'بہت دور (∞)',
  save_png: 'تصویر محفوظ کریں',
  lbl_object: 'شے',
  lbl_image: 'عکس',
  light_dir: 'روشنی',
  side_front: 'سامنے: حقیقی عکس',
  side_behind: 'پیچھے: مجازی عکس',
  side_obj: 'شے کی طرف: مجازی عکس',
  side_other: 'دوسری طرف: حقیقی عکس',
  note_point: 'شے بہت دور ہے: شعاعیں متوازی آتی ہیں اور فوکس پر نقطے جتنا عکس بناتی ہیں۔',
  note_inf_img: 'شعاعیں متوازی نکلتی ہیں، اس لیے عکس لامتناہی پر بنتا ہے۔',
  note_off: 'عکس تصویر سے باہر ہے، v = {v} پر۔',
  res_h: 'نتائج (علامتوں کے ساتھ)',
  r_u: 'شے کا فاصلہ u',
  r_v: 'عکس کا فاصلہ v',
  r_f: 'فوکسی فاصلہ f',
  r_m: 'تکبیر m',
  r_h: 'شے کی اونچائی h',
  r_h2: 'عکس کی اونچائی h′',
  r_p: 'طاقت P',
  r_obj_pos: 'شے:',
  r_img_pos: 'عکس:',
  nat_real: 'حقیقی',
  nat_virtual: 'مجازی',
  nat_inverted: 'الٹا',
  nat_erect: 'سیدھا',
  size_point: 'بہت چھوٹا، نقطے جتنا',
  size_dim: 'چھوٹا',
  size_same: 'برابر سائز',
  size_big: 'بڑا',
  size_huge: 'بہت بڑا',
  why_obj_inf: 'بہت دور کی شے سے شعاعیں محور کے متوازی آتی ہیں، اس لیے وہ فوکس پر ملتی ہیں (یا وہاں سے آتی لگتی ہیں)۔',
  why_inf: 'نکلنے والی شعاعیں آپس میں متوازی ہیں، اس لیے وہ صرف لامتناہی پر ملتی ہیں۔',
  why_mirror_real: 'v منفی ہے: عکس آئینے کے سامنے ہے، جہاں منعکس شعاعیں سچ مچ ملتی ہیں۔ اس لیے یہ حقیقی ہے۔',
  why_mirror_virtual: 'v مثبت ہے: عکس آئینے کے پیچھے ہے۔ شعاعیں صرف وہاں سے آتی لگتی ہیں، اس لیے یہ مجازی ہے۔',
  why_lens_real: 'v مثبت ہے: عکس عدسے کی دوسری طرف ہے، جہاں شعاعیں سچ مچ ملتی ہیں۔ اس لیے یہ حقیقی ہے۔',
  why_lens_virtual: 'v منفی ہے: عکس شے کی طرف ہی ہے۔ شعاعیں صرف وہاں سے آتی لگتی ہیں، اس لیے یہ مجازی ہے۔',
  why_m_neg: 'm منفی ہے، اس لیے عکس الٹا ہے۔',
  why_m_pos: 'm مثبت ہے، اس لیے عکس سیدھا ہے۔',
  why_m_big: 'علامت چھوڑ کر m کی قیمت 1 سے زیادہ ہے، اس لیے عکس بڑا ہے۔',
  why_m_small: 'علامت چھوڑ کر m کی قیمت 1 سے کم ہے، اس لیے عکس چھوٹا ہے۔',
  why_m_same: 'علامت چھوڑ کر m کی قیمت 1 ہے، اس لیے عکس شے کے برابر ہے۔',
  form_h: 'فارمولے سے جانچیں',
  form_mirror: 'آئینے کا فارمولا',
  form_lens: 'عدسے کا فارمولا',
  form_mag: 'تکبیر',
  form_power: 'عدسے کی طاقت (f میٹر میں، یعنی f اگر cm میں ہو تو 100/f)',
  table_h: 'NCERT جدول: عکس کہاں بنے گا؟',
  table_tip: 'شے کو اس جگہ رکھنے کے لیے کسی قطار پر ٹیپ کریں۔',
  th_obj: 'شے کا مقام',
  th_img: 'عکس کا مقام',
  th_size: 'عکس کا سائز',
  th_nature: 'عکس کی نوعیت',
  nature_ri: 'حقیقی اور الٹا',
  nature_ve: 'مجازی اور سیدھا',
  pos_inf: 'لامتناہی پر',
  pos_beyond_c: 'C سے آگے',
  pos_at_c: 'C پر',
  pos_c_f: 'C اور F کے درمیان',
  pos_f_c: 'F اور C کے درمیان',
  pos_at_f: 'F پر',
  pos_p_f: 'P اور F کے درمیان',
  pos_behind: 'آئینے کے پیچھے',
  pos_inf_p: 'لامتناہی اور قطب P کے درمیان',
  pos_behind_pf: 'آئینے کے پیچھے، P اور F کے درمیان',
  pos_behind_f: 'آئینے کے پیچھے، F پر',
  pos_beyond_2f1: '2F₁ سے آگے',
  pos_at_2f1: '2F₁ پر',
  pos_f1_2f1: 'F₁ اور 2F₁ کے درمیان',
  pos_at_f1: 'F₁ پر',
  pos_f1_o: 'F₁ اور بصری مرکز O کے درمیان',
  pos_at_f2: 'F₂ پر',
  pos_f2_2f2: 'F₂ اور 2F₂ کے درمیان',
  pos_at_2f2: '2F₂ پر',
  pos_beyond_2f2: '2F₂ سے آگے',
  pos_same_side: 'عدسے کی اسی طرف جہاں شے ہے',
  pos_inf_o: 'لامتناہی اور بصری مرکز O کے درمیان',
  sign_h: 'نیا کارتیسی علامتی اصول',
  sign_1: 'ہر فاصلہ آئینے کے قطب P یا عدسے کے بصری مرکز O سے ناپیں۔',
  sign_2: 'روشنی بائیں طرف سے آتی ہے۔ دائیں طرف (روشنی کی سمت میں) کے فاصلے مثبت (+) اور بائیں طرف کے فاصلے منفی (−) ہوتے ہیں۔',
  sign_3: 'اس لیے یہاں شے کا فاصلہ u ہمیشہ منفی ہے۔',
  sign_4: 'اصل محور کے اوپر کی اونچائی مثبت اور نیچے کی اونچائی منفی ہوتی ہے۔',
  sign_5: 'مقعر آئینے اور مقعر عدسے کے لیے f منفی، جبکہ محدب آئینے اور محدب عدسے کے لیے f مثبت ہوتا ہے۔',
  quiz_h: 'کوئز: عکس کا اندازہ لگائیں',
  quiz_q: 'شے کا فاصلہ {u}، فوکسی فاصلہ {f}۔ کیسا عکس بنے گا؟',
  quiz_q_inf: 'شے بہت دور (لامتناہی پر) ہے۔ فوکسی فاصلہ {f}۔ کیسا عکس بنے گا؟',
  q_pos: 'عکس کا مقام',
  q_nature: 'حقیقی یا مجازی؟',
  q_orient: 'سیدھا یا الٹا؟',
  q_size: 'عکس کا سائز',
  q_choose: 'چنیں…',
  q_check: 'جواب جانچیں',
  q_next: 'نیا سوال',
  q_show: 'لیب میں دیکھیں',
  q_score: 'اسکور: {a} / {b}',
  q_need: 'پہلے چاروں حصوں کا جواب دیں۔',
  q_right: 'شاباش! چاروں حصے درست ہیں۔',
  q_wrong: 'پوری طرح درست نہیں: 4 میں سے {n} حصے درست ہیں۔ نیچے صحیح جواب دیکھیں۔',
  q_hint: 'یہاں آئینے یا عدسے سے F کا فاصلہ {f} اور C (یا 2F) کا فاصلہ {c} ہے۔',
  uses_h: 'ان کا استعمال کہاں ہوتا ہے؟',
  use_show: 'دکھائیں',
  use_torch_t: 'ٹارچ اور گاڑی کی ہیڈلائٹ',
  use_torch_d: 'بلب مقعر آئینے کے فوکس پر ہوتا ہے، اس لیے روشنی طاقتور متوازی شعاعوں کی شکل میں نکلتی ہے۔',
  use_solar_t: 'سولر کُکر اور شمسی بھٹی',
  use_solar_d: 'سورج کی روشنی بہت دور سے آتی ہے، اس لیے مقعر آئینہ اسے فوکس پر جمع کر کے بہت گرمی پیدا کرتا ہے۔',
  use_shave_t: 'شیو اور میک اپ کا آئینہ',
  use_shave_d: 'چہرہ مقعر آئینے کے P اور F کے درمیان رکھنے سے سیدھا اور بڑا عکس دکھائی دیتا ہے۔',
  use_rear_t: 'پیچھے دیکھنے والا آئینہ',
  use_rear_d: 'محدب آئینہ ہمیشہ سیدھا اور چھوٹا عکس دیتا ہے اور گاڑی کے پیچھے کا بڑا حصہ دکھاتا ہے۔',
  use_mag_t: 'محدب شیشہ (آتشی شیشہ)',
  use_mag_d: 'شے کو محدب عدسے کے F₁ اور O کے درمیان رکھنے سے سیدھا، بڑا، مجازی عکس ملتا ہے۔',
  use_proj_t: 'پروجیکٹر',
  use_proj_d: 'سلائیڈ محدب عدسے کے F₁ اور 2F₁ کے درمیان ہوتی ہے، اس لیے پردے پر بڑا، حقیقی، الٹا عکس پڑتا ہے۔ اسی لیے سلائیڈ الٹی لگائی جاتی ہے۔',
  use_cam_t: 'کیمرا اور ہماری آنکھ',
  use_cam_d: 'دور کی شے (2F₁ سے آگے) سینسر یا ریٹینا پر چھوٹا، حقیقی، الٹا عکس بناتی ہے۔',
  use_spec_t: 'قریب نظری کا چشمہ',
  use_spec_d: 'مقعر عدسہ ہمیشہ مجازی، سیدھا، چھوٹا عکس دیتا ہے۔ یہ قریب نظری والے لوگوں کو دور دیکھنے میں مدد دیتا ہے۔',
  help_h: 'استعمال کا طریقہ / کلاس کے لیے خیالات',
  help_1: 'آئینہ یا عدسہ چنیں، پھر نارنجی شے کو کھینچیں (یا سلائیڈر کھسکائیں)۔ شعاعیں، عکس اور سارے اعداد فوراً بدل جاتے ہیں۔',
  help_2: 'رنگین بٹنوں سے شعاعیں چالو یا بند کریں۔ عکس ڈھونڈنے کے لیے کوئی بھی دو شعاعیں کافی ہیں؛ ڈیش والی لکیریں بتاتی ہیں کہ شعاعیں کہاں سے آتی لگتی ہیں۔',
  help_3: 'u، v، f اور m کو ان کی علامتوں کے ساتھ پڑھیں۔ فارمولے کے خانے میں ہر قدم دکھایا گیا ہے، اس لیے طلبہ اپنے سوال خود جانچ سکتے ہیں۔',
  help_4: 'NCERT جدول کی کسی قطار پر ٹیپ کر کے شے کو اس مقام پر لے جائیں۔ صفحہ پرنٹ کرنے پر خاکہ، حل اور جدول کاغذ پر مل جاتے ہیں۔',
  help_5: 'کلاس سرگرمی: ایک طالب علم شے کھسکائے اور باقی کلاس دیکھنے سے پہلے بولے، "حقیقی یا مجازی، سیدھا یا الٹا، بڑا یا چھوٹا"۔ پھر ٹیموں میں کوئز کھیلیں۔',
  help_6: 'گھر پر آزمائیں: چمکتے اسٹیل کے چمچ میں دیکھیں۔ اندر کا حصہ مقعر آئینے کی طرح اور پیچھے کا حصہ محدب آئینے کی طرح کام کرتا ہے۔'
};
