/* UI strings for Social Post Resizer. Keys are identical in all 12 languages.
   Shared words (download, reset, loading, saved_local, confirm_reset, ...) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Social Post Resizer',
    intro: 'Turn one photo or poster into the right size for Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X and Google Business: drag it into place, zoom, then download every size.',
    privacy_head: 'Your photos never leave this device.',
    privacy_body: 'Resizing happens inside your browser. Nothing is uploaded and nothing is saved online.',
    drop_title: 'Pick a photo or poster',
    drop_hint: 'JPG, PNG, WebP or GIF · drag and drop it here, or paste it (Ctrl+V)',
    pick_btn: 'Choose picture',
    sample_btn: 'Try the sample',
    loaded_sample: 'Sample poster loaded. Choose your own picture to begin.',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'Large photo scaled down to {w} × {h} px for faster editing.',
    picture: 'picture',
    err_open: 'This file could not be opened as a picture. Try a JPG or PNG.',
    err_heic: 'HEIC photos (iPhone) do not open here. Share the photo from your phone as JPG, or convert it with our Image Compressor.',
    err_heic_link: 'Open Image Compressor',
    too_big: 'This file is very large. Try a photo under 80 MB.',
    err_export: 'The picture could not be saved. Try a smaller size or PNG.',
    h_adjust: 'Adjust',
    stage_aria: 'Picture preview. Drag to move it, use the mouse wheel or pinch to zoom.',
    drag_hint: 'Drag the picture to move it · scroll or pinch to zoom',
    keys_hint: 'Keyboard: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> move · <kbd>+</kbd> <kbd>−</kbd> zoom · <kbd>0</kbd> reset · <kbd>F</kbd> fit / fill',
    mode_label: 'Fit or fill',
    mode_fit: 'Fit (whole picture)',
    mode_fill: 'Fill (crop to size)',
    zoom: 'Zoom',
    center_btn: 'Reset position and zoom',
    bg_label: 'Background (when the picture does not fill the frame)',
    bg_blur: 'Blurred photo',
    bg_auto: 'Auto colour',
    bg_white: 'White',
    bg_black: 'Black',
    bg_custom: 'Pick colour',
    safe_show: 'Show safe area',
    apply_all: 'Use fit / fill for all sizes',
    applied_all: 'Applied to all sizes.',
    safe_hint_bands: 'Keep names and prices out of the shaded top and bottom: app buttons and captions cover them.',
    safe_hint_rect: 'Only the bright area is visible on every device (TV, computer and phone).',
    safe_hint_circle: 'This picture is shown as a circle: the shaded corners are cut off.',
    safe_hint_avoid: 'The shaded corner is covered by the video length or the profile photo.',
    h_caption: 'Caption band',
    caption_on: 'Add a caption band',
    caption_text: 'Caption text',
    caption_ph: 'e.g. Sharma Sweets · Diwali offer · 20% off',
    caption_pos: 'Position',
    pos_top: 'Top',
    pos_bottom: 'Bottom',
    caption_style: 'Style',
    style_dark: 'Dark',
    style_light: 'Light',
    style_brand: 'Picked colour',
    on_badge: 'On',
    h_logo: 'Logo corner',
    logo_pick: 'Add logo',
    logo_remove: 'Remove logo',
    logo_hint: 'A PNG with a transparent background looks best.',
    logo_corner: 'Corner',
    corner_tl: 'Top left',
    corner_tr: 'Top right',
    corner_bl: 'Bottom left',
    corner_br: 'Bottom right',
    logo_size: 'Logo size',
    h_sizes: 'Sizes',
    sizes_hint: 'Tap a size to adjust it. Tick the sizes you want to download.',
    custom_w: 'Width (px)',
    custom_h: 'Height (px)',
    custom_hint: 'Any size from 16 to 4096 px.',
    sel_count: '{n} sizes ticked for download',
    sel_all: 'Tick all',
    sel_none: 'Untick all',
    tick_aria: 'Download {name}',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'Custom',
    p_ig_square: 'Post (square)',
    p_ig_portrait: 'Post (portrait)',
    p_ig_landscape: 'Post (landscape)',
    p_ig_story: 'Story and Reel cover',
    p_ig_dp: 'Profile picture',
    p_yt_thumb: 'Video thumbnail',
    p_yt_shorts: 'Shorts cover',
    p_yt_banner: 'Channel banner',
    p_yt_dp: 'Channel picture',
    p_wa_dp: 'Profile photo (DP)',
    p_wa_status: 'Status',
    p_fb_post: 'Post (landscape)',
    p_fb_square: 'Post (square)',
    p_fb_cover: 'Page cover',
    p_fb_story: 'Story',
    p_li_post: 'Post',
    p_li_banner: 'Profile banner',
    p_x_post: 'Post',
    p_x_header: 'Header',
    p_gb_photo: 'Business photo',
    p_gb_cover: 'Cover photo',
    p_custom: 'Custom size',
    h_export: 'Download',
    fmt_label: 'Format',
    fmt_hint_jpg: 'JPG: small files, best for photos.',
    fmt_hint_png: 'PNG: sharp text and logos, bigger files.',
    quality: 'JPG quality',
    est_size: 'About {kb} KB at {w} × {h} px',
    dl_this: 'Download this size ({w} × {h})',
    dl_all: 'Download {n} ticked sizes',
    dl_none: 'Tick at least one size first.',
    dl_many_hint: 'Files download one by one. If the browser asks to allow multiple downloads, say yes.',
    dl_done: 'Saved {name} ({kb} KB)',
    dl_progress: '{i} of {n}: {name}',
    dl_all_done: '{n} files downloaded.',
    share_btn: 'Share this size',
    reset_all: 'Reset settings',
    help_title: 'How to use / ideas',
    tip1: 'Choose a picture, tap a size, then drag the picture into place. Scroll or pinch to zoom in on the important part. Every size remembers its own position.',
    tip2: 'Fit keeps the whole poster and fills the empty space with a blurred copy or a colour. Fill crops the picture to the exact shape. "Use fit / fill for all sizes" applies your choice everywhere.',
    tip3: 'Shopkeepers: make the offer poster once, tick Instagram post, WhatsApp status and Facebook cover, and download them together. Add your shop name as a caption band.',
    tip4: 'Creators: for Shorts, Reels and Status keep text out of the shaded top and bottom, where the app buttons sit. For the YouTube banner, keep everything inside the bright centre.',
    tip5: 'Schools and offices: one notice photo becomes a WhatsApp DP, a YouTube thumbnail and a Facebook cover in a minute. Put the logo in a corner so every post looks like yours.',
    tip6: 'Use PNG for posters with text and logos. Use JPG at quality 85–92 for photos: files stay small and upload fast on slow networks.',
    sample_shop: 'Sharma Sweets',
    sample_offer: 'Diwali special · fresh every morning',
    sample_off: '20% off'
  },
  hi: {
    app_title: 'सोशल पोस्ट रीसाइज़र',
    intro: 'एक फ़ोटो या पोस्टर को Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X और Google Business के सही साइज़ में बदलें: खींचकर जगह पर रखें, ज़ूम करें, फिर हर साइज़ डाउनलोड करें।',
    privacy_head: 'आपकी फ़ोटो कभी इस डिवाइस से बाहर नहीं जातीं।',
    privacy_body: 'साइज़ बदलने का काम आपके ब्राउज़र के अंदर ही होता है। कुछ भी अपलोड नहीं होता, कुछ भी ऑनलाइन सेव नहीं होता।',
    drop_title: 'फ़ोटो या पोस्टर चुनें',
    drop_hint: 'JPG, PNG, WebP या GIF · यहाँ खींचकर छोड़ें, या पेस्ट करें (Ctrl+V)',
    pick_btn: 'तस्वीर चुनें',
    sample_btn: 'नमूना देखें',
    loaded_sample: 'नमूना पोस्टर खुला है। शुरू करने के लिए अपनी तस्वीर चुनें।',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'बड़ी फ़ोटो को तेज़ काम के लिए {w} × {h} px तक छोटा किया गया।',
    picture: 'तस्वीर',
    err_open: 'यह फ़ाइल तस्वीर की तरह नहीं खुल सकी। JPG या PNG आज़माएँ।',
    err_heic: 'HEIC फ़ोटो (iPhone) यहाँ नहीं खुलतीं। फ़ोन से फ़ोटो को JPG के रूप में शेयर करें, या हमारे Image Compressor से बदलें।',
    err_heic_link: 'Image Compressor खोलें',
    too_big: 'यह फ़ाइल बहुत बड़ी है। 80 MB से छोटी फ़ोटो आज़माएँ।',
    err_export: 'तस्वीर सेव नहीं हो सकी। छोटा साइज़ या PNG आज़माएँ।',
    h_adjust: 'सेट करें',
    stage_aria: 'तस्वीर का प्रीव्यू। हिलाने के लिए खींचें, ज़ूम के लिए माउस व्हील या दो उँगलियाँ इस्तेमाल करें।',
    drag_hint: 'तस्वीर को हिलाने के लिए खींचें · ज़ूम के लिए स्क्रॉल करें या दो उँगलियों से फैलाएँ',
    keys_hint: 'कीबोर्ड: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> हिलाएँ · <kbd>+</kbd> <kbd>−</kbd> ज़ूम · <kbd>0</kbd> रीसेट · <kbd>F</kbd> फ़िट / फ़िल',
    mode_label: 'फ़िट या फ़िल',
    mode_fit: 'फ़िट (पूरी तस्वीर)',
    mode_fill: 'फ़िल (साइज़ के हिसाब से क्रॉप)',
    zoom: 'ज़ूम',
    center_btn: 'जगह और ज़ूम रीसेट करें',
    bg_label: 'बैकग्राउंड (जब तस्वीर पूरा फ़्रेम न भरे)',
    bg_blur: 'धुँधली फ़ोटो',
    bg_auto: 'अपने आप रंग',
    bg_white: 'सफ़ेद',
    bg_black: 'काला',
    bg_custom: 'रंग चुनें',
    safe_show: 'सुरक्षित हिस्सा दिखाएँ',
    apply_all: 'सभी साइज़ में यही फ़िट / फ़िल',
    applied_all: 'सभी साइज़ पर लागू हो गया।',
    safe_hint_bands: 'नाम और दाम ऊपर-नीचे के छायादार हिस्से से बाहर रखें: वहाँ ऐप के बटन और कैप्शन आ जाते हैं।',
    safe_hint_rect: 'हर डिवाइस (TV, कंप्यूटर और फ़ोन) पर सिर्फ़ चमकीला हिस्सा दिखता है।',
    safe_hint_circle: 'यह तस्वीर गोल दिखती है: छायादार कोने कट जाते हैं।',
    safe_hint_avoid: 'छायादार कोना वीडियो की लंबाई या प्रोफ़ाइल फ़ोटो से ढक जाता है।',
    h_caption: 'कैप्शन पट्टी',
    caption_on: 'कैप्शन पट्टी जोड़ें',
    caption_text: 'कैप्शन का टेक्स्ट',
    caption_ph: 'जैसे: शर्मा स्वीट्स · दिवाली ऑफ़र · 20% छूट',
    caption_pos: 'जगह',
    pos_top: 'ऊपर',
    pos_bottom: 'नीचे',
    caption_style: 'स्टाइल',
    style_dark: 'गहरा',
    style_light: 'हल्का',
    style_brand: 'चुना हुआ रंग',
    on_badge: 'चालू',
    h_logo: 'कोने में लोगो',
    logo_pick: 'लोगो जोड़ें',
    logo_remove: 'लोगो हटाएँ',
    logo_hint: 'पारदर्शी बैकग्राउंड वाला PNG सबसे अच्छा दिखता है।',
    logo_corner: 'कोना',
    corner_tl: 'ऊपर बाएँ',
    corner_tr: 'ऊपर दाएँ',
    corner_bl: 'नीचे बाएँ',
    corner_br: 'नीचे दाएँ',
    logo_size: 'लोगो का साइज़',
    h_sizes: 'साइज़',
    sizes_hint: 'सेट करने के लिए किसी साइज़ पर टैप करें। जो साइज़ डाउनलोड करने हैं, उन पर टिक लगाएँ।',
    custom_w: 'चौड़ाई (px)',
    custom_h: 'ऊँचाई (px)',
    custom_hint: '16 से 4096 px तक कोई भी साइज़।',
    sel_count: 'डाउनलोड के लिए {n} साइज़ पर टिक है',
    sel_all: 'सब पर टिक',
    sel_none: 'सब टिक हटाएँ',
    tick_aria: '{name} डाउनलोड करें',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'अपना साइज़',
    p_ig_square: 'पोस्ट (चौकोर)',
    p_ig_portrait: 'पोस्ट (खड़ी)',
    p_ig_landscape: 'पोस्ट (आड़ी)',
    p_ig_story: 'स्टोरी और रील कवर',
    p_ig_dp: 'प्रोफ़ाइल फ़ोटो',
    p_yt_thumb: 'वीडियो थंबनेल',
    p_yt_shorts: 'Shorts कवर',
    p_yt_banner: 'चैनल बैनर',
    p_yt_dp: 'चैनल की फ़ोटो',
    p_wa_dp: 'प्रोफ़ाइल फ़ोटो (DP)',
    p_wa_status: 'स्टेटस',
    p_fb_post: 'पोस्ट (आड़ी)',
    p_fb_square: 'पोस्ट (चौकोर)',
    p_fb_cover: 'पेज कवर',
    p_fb_story: 'स्टोरी',
    p_li_post: 'पोस्ट',
    p_li_banner: 'प्रोफ़ाइल बैनर',
    p_x_post: 'पोस्ट',
    p_x_header: 'हेडर',
    p_gb_photo: 'बिज़नेस फ़ोटो',
    p_gb_cover: 'कवर फ़ोटो',
    p_custom: 'अपना साइज़',
    h_export: 'डाउनलोड',
    fmt_label: 'फ़ॉर्मैट',
    fmt_hint_jpg: 'JPG: छोटी फ़ाइलें, फ़ोटो के लिए सबसे अच्छा।',
    fmt_hint_png: 'PNG: साफ़ टेक्स्ट और लोगो, फ़ाइलें बड़ी।',
    quality: 'JPG क्वालिटी',
    est_size: '{w} × {h} px पर लगभग {kb} KB',
    dl_this: 'यह साइज़ डाउनलोड करें ({w} × {h})',
    dl_all: '{n} टिक किए साइज़ डाउनलोड करें',
    dl_none: 'पहले कम से कम एक साइज़ पर टिक लगाएँ।',
    dl_many_hint: 'फ़ाइलें एक-एक करके डाउनलोड होती हैं। अगर ब्राउज़र कई डाउनलोड की अनुमति माँगे, तो हाँ कहें।',
    dl_done: '{name} सेव हुई ({kb} KB)',
    dl_progress: '{n} में से {i}: {name}',
    dl_all_done: '{n} फ़ाइलें डाउनलोड हुईं।',
    share_btn: 'यह साइज़ शेयर करें',
    reset_all: 'सेटिंग्स रीसेट करें',
    help_title: 'कैसे इस्तेमाल करें / आइडिया',
    tip1: 'तस्वीर चुनें, किसी साइज़ पर टैप करें, फिर तस्वीर को खींचकर जगह पर रखें। ज़रूरी हिस्से पर ज़ूम करने के लिए स्क्रॉल करें या दो उँगलियों से फैलाएँ। हर साइज़ अपनी जगह याद रखता है।',
    tip2: 'फ़िट पूरा पोस्टर रखता है और खाली जगह को धुँधली कॉपी या रंग से भरता है। फ़िल तस्वीर को सही आकार में क्रॉप करता है। "सभी साइज़ में यही फ़िट / फ़िल" आपकी पसंद हर जगह लागू करता है।',
    tip3: 'दुकानदार: ऑफ़र का पोस्टर एक बार बनाएँ, Instagram पोस्ट, WhatsApp स्टेटस और Facebook कवर पर टिक लगाएँ और सब एक साथ डाउनलोड करें। कैप्शन पट्टी में दुकान का नाम जोड़ें।',
    tip4: 'क्रिएटर: Shorts, Reels और स्टेटस में टेक्स्ट को ऊपर-नीचे के छायादार हिस्से से बाहर रखें, वहाँ ऐप के बटन होते हैं। YouTube बैनर में सब कुछ चमकीले बीच वाले हिस्से में रखें।',
    tip5: 'स्कूल और ऑफ़िस: एक नोटिस की फ़ोटो एक मिनट में WhatsApp DP, YouTube थंबनेल और Facebook कवर बन जाती है। कोने में लोगो लगाएँ ताकि हर पोस्ट आपकी पहचान दिखाए।',
    tip6: 'टेक्स्ट और लोगो वाले पोस्टर के लिए PNG चुनें। फ़ोटो के लिए JPG क्वालिटी 85–92 रखें: फ़ाइलें छोटी रहती हैं और धीमे नेटवर्क पर भी जल्दी अपलोड होती हैं।',
    sample_shop: 'शर्मा स्वीट्स',
    sample_offer: 'दिवाली स्पेशल · हर सुबह ताज़ा',
    sample_off: '20% छूट'
  },
  bn: {
    app_title: 'সোশ্যাল পোস্ট রিসাইজার',
    intro: 'একটি ছবি বা পোস্টারকে Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X ও Google Business-এর সঠিক মাপে বদলান: টেনে জায়গায় বসান, জুম করুন, তারপর সব মাপ ডাউনলোড করুন।',
    privacy_head: 'আপনার ছবি কখনও এই ডিভাইসের বাইরে যায় না।',
    privacy_body: 'মাপ বদলানোর কাজ আপনার ব্রাউজারের ভিতরেই হয়। কিছুই আপলোড হয় না, কিছুই অনলাইনে সেভ হয় না।',
    drop_title: 'ছবি বা পোস্টার বেছে নিন',
    drop_hint: 'JPG, PNG, WebP বা GIF · এখানে টেনে ছাড়ুন, বা পেস্ট করুন (Ctrl+V)',
    pick_btn: 'ছবি বাছুন',
    sample_btn: 'নমুনা দেখুন',
    loaded_sample: 'নমুনা পোস্টার খোলা আছে। শুরু করতে নিজের ছবি বাছুন।',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'বড় ছবিটি দ্রুত কাজের জন্য {w} × {h} px-এ ছোট করা হয়েছে।',
    picture: 'ছবি',
    err_open: 'এই ফাইলটি ছবি হিসেবে খোলা গেল না। JPG বা PNG ব্যবহার করুন।',
    err_heic: 'HEIC ছবি (iPhone) এখানে খোলে না। ফোন থেকে ছবিটি JPG হিসেবে শেয়ার করুন, বা আমাদের Image Compressor দিয়ে বদলান।',
    err_heic_link: 'Image Compressor খুলুন',
    too_big: 'এই ফাইলটি খুব বড়। 80 MB-এর ছোট ছবি ব্যবহার করুন।',
    err_export: 'ছবিটি সেভ করা গেল না। ছোট মাপ বা PNG ব্যবহার করুন।',
    h_adjust: 'ঠিক করুন',
    stage_aria: 'ছবির প্রিভিউ। সরাতে টানুন, জুম করতে মাউস হুইল বা দুই আঙুল ব্যবহার করুন।',
    drag_hint: 'ছবি সরাতে টানুন · জুম করতে স্ক্রল করুন বা দুই আঙুলে ছড়ান',
    keys_hint: 'কীবোর্ড: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> সরান · <kbd>+</kbd> <kbd>−</kbd> জুম · <kbd>0</kbd> রিসেট · <kbd>F</kbd> ফিট / ফিল',
    mode_label: 'ফিট না ফিল',
    mode_fit: 'ফিট (পুরো ছবি)',
    mode_fill: 'ফিল (মাপে কাটা)',
    zoom: 'জুম',
    center_btn: 'জায়গা ও জুম রিসেট করুন',
    bg_label: 'ব্যাকগ্রাউন্ড (ছবি পুরো ফ্রেম না ভরলে)',
    bg_blur: 'ঝাপসা ছবি',
    bg_auto: 'নিজে থেকে রং',
    bg_white: 'সাদা',
    bg_black: 'কালো',
    bg_custom: 'রং বাছুন',
    safe_show: 'নিরাপদ অংশ দেখান',
    apply_all: 'সব মাপে এই ফিট / ফিল',
    applied_all: 'সব মাপে লাগানো হয়েছে।',
    safe_hint_bands: 'নাম ও দাম উপরে-নীচের ছায়া অংশের বাইরে রাখুন: সেখানে অ্যাপের বোতাম ও ক্যাপশন এসে পড়ে।',
    safe_hint_rect: 'সব ডিভাইসে (TV, কম্পিউটার ও ফোন) শুধু উজ্জ্বল অংশটুকুই দেখা যায়।',
    safe_hint_circle: 'এই ছবি গোল করে দেখানো হয়: ছায়া কোণগুলো কেটে যায়।',
    safe_hint_avoid: 'ছায়া কোণটি ভিডিওর দৈর্ঘ্য বা প্রোফাইল ছবিতে ঢাকা পড়ে।',
    h_caption: 'ক্যাপশন পট্টি',
    caption_on: 'ক্যাপশন পট্টি যোগ করুন',
    caption_text: 'ক্যাপশনের লেখা',
    caption_ph: 'যেমন: শর্মা সুইটস · দীপাবলি অফার · 20% ছাড়',
    caption_pos: 'জায়গা',
    pos_top: 'উপরে',
    pos_bottom: 'নীচে',
    caption_style: 'স্টাইল',
    style_dark: 'গাঢ়',
    style_light: 'হালকা',
    style_brand: 'বাছা রং',
    on_badge: 'চালু',
    h_logo: 'কোণে লোগো',
    logo_pick: 'লোগো যোগ করুন',
    logo_remove: 'লোগো সরান',
    logo_hint: 'স্বচ্ছ ব্যাকগ্রাউন্ডের PNG সবচেয়ে ভালো দেখায়।',
    logo_corner: 'কোণ',
    corner_tl: 'উপরে বামে',
    corner_tr: 'উপরে ডানে',
    corner_bl: 'নীচে বামে',
    corner_br: 'নীচে ডানে',
    logo_size: 'লোগোর মাপ',
    h_sizes: 'মাপ',
    sizes_hint: 'ঠিক করতে একটি মাপে ট্যাপ করুন। যে মাপগুলো ডাউনলোড করবেন, সেগুলোতে টিক দিন।',
    custom_w: 'চওড়া (px)',
    custom_h: 'উচ্চতা (px)',
    custom_hint: '16 থেকে 4096 px-এর মধ্যে কোনো মাপ।',
    sel_count: 'ডাউনলোডের জন্য {n}টি মাপে টিক দেওয়া',
    sel_all: 'সবগুলোতে টিক',
    sel_none: 'সব টিক তুলুন',
    tick_aria: '{name} ডাউনলোড করুন',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'নিজের মাপ',
    p_ig_square: 'পোস্ট (চৌকো)',
    p_ig_portrait: 'পোস্ট (লম্বা)',
    p_ig_landscape: 'পোস্ট (আড়াআড়ি)',
    p_ig_story: 'স্টোরি ও রিল কভার',
    p_ig_dp: 'প্রোফাইল ছবি',
    p_yt_thumb: 'ভিডিও থাম্বনেল',
    p_yt_shorts: 'Shorts কভার',
    p_yt_banner: 'চ্যানেল ব্যানার',
    p_yt_dp: 'চ্যানেলের ছবি',
    p_wa_dp: 'প্রোফাইল ছবি (DP)',
    p_wa_status: 'স্ট্যাটাস',
    p_fb_post: 'পোস্ট (আড়াআড়ি)',
    p_fb_square: 'পোস্ট (চৌকো)',
    p_fb_cover: 'পেজ কভার',
    p_fb_story: 'স্টোরি',
    p_li_post: 'পোস্ট',
    p_li_banner: 'প্রোফাইল ব্যানার',
    p_x_post: 'পোস্ট',
    p_x_header: 'হেডার',
    p_gb_photo: 'ব্যবসার ছবি',
    p_gb_cover: 'কভার ছবি',
    p_custom: 'নিজের মাপ',
    h_export: 'ডাউনলোড',
    fmt_label: 'ফরম্যাট',
    fmt_hint_jpg: 'JPG: ছোট ফাইল, ছবির জন্য সবচেয়ে ভালো।',
    fmt_hint_png: 'PNG: স্পষ্ট লেখা ও লোগো, ফাইল বড়।',
    quality: 'JPG কোয়ালিটি',
    est_size: '{w} × {h} px-এ প্রায় {kb} KB',
    dl_this: 'এই মাপ ডাউনলোড করুন ({w} × {h})',
    dl_all: 'টিক দেওয়া {n}টি মাপ ডাউনলোড করুন',
    dl_none: 'আগে অন্তত একটি মাপে টিক দিন।',
    dl_many_hint: 'ফাইলগুলো একটি একটি করে ডাউনলোড হয়। ব্রাউজার একাধিক ডাউনলোডের অনুমতি চাইলে হ্যাঁ বলুন।',
    dl_done: '{name} সেভ হয়েছে ({kb} KB)',
    dl_progress: '{n}-এর মধ্যে {i}: {name}',
    dl_all_done: '{n}টি ফাইল ডাউনলোড হয়েছে।',
    share_btn: 'এই মাপ শেয়ার করুন',
    reset_all: 'সেটিংস রিসেট করুন',
    help_title: 'কীভাবে ব্যবহার করবেন / আইডিয়া',
    tip1: 'ছবি বাছুন, একটি মাপে ট্যাপ করুন, তারপর ছবিটি টেনে জায়গায় বসান। দরকারি অংশে জুম করতে স্ক্রল করুন বা দুই আঙুলে ছড়ান। প্রতিটি মাপ নিজের জায়গা মনে রাখে।',
    tip2: 'ফিট পুরো পোস্টার রাখে এবং ফাঁকা জায়গা ঝাপসা কপি বা রঙে ভরে দেয়। ফিল ছবিটিকে ঠিক আকারে কেটে নেয়। "সব মাপে এই ফিট / ফিল" আপনার পছন্দ সব জায়গায় লাগায়।',
    tip3: 'দোকানদার: অফারের পোস্টার একবার বানান, Instagram পোস্ট, WhatsApp স্ট্যাটাস ও Facebook কভারে টিক দিন এবং সব একসঙ্গে ডাউনলোড করুন। ক্যাপশন পট্টিতে দোকানের নাম দিন।',
    tip4: 'ক্রিয়েটর: Shorts, Reels ও স্ট্যাটাসে লেখা উপরে-নীচের ছায়া অংশের বাইরে রাখুন, সেখানে অ্যাপের বোতাম থাকে। YouTube ব্যানারে সব কিছু উজ্জ্বল মাঝের অংশে রাখুন।',
    tip5: 'স্কুল ও অফিস: একটি নোটিসের ছবি এক মিনিটে WhatsApp DP, YouTube থাম্বনেল ও Facebook কভার হয়ে যায়। কোণে লোগো দিন, যাতে প্রতিটি পোস্ট আপনার পরিচয় দেখায়।',
    tip6: 'লেখা ও লোগোসহ পোস্টারের জন্য PNG বাছুন। ছবির জন্য JPG কোয়ালিটি 85–92 রাখুন: ফাইল ছোট থাকে এবং ধীর নেটওয়ার্কেও দ্রুত আপলোড হয়।',
    sample_shop: 'শর্মা সুইটস',
    sample_offer: 'দীপাবলি স্পেশাল · প্রতিদিন সকালে টাটকা',
    sample_off: '20% ছাড়'
  },
  mr: {
    app_title: 'सोशल पोस्ट रिसाइझर',
    intro: 'एक फोटो किंवा पोस्टर Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X आणि Google Business च्या योग्य साइझमध्ये बदला: ओढून जागेवर ठेवा, झूम करा, मग प्रत्येक साइझ डाउनलोड करा.',
    privacy_head: 'तुमचे फोटो कधीही या डिव्हाइसच्या बाहेर जात नाहीत.',
    privacy_body: 'साइझ बदलण्याचे काम तुमच्या ब्राउझरमध्येच होते. काहीही अपलोड होत नाही, काहीही ऑनलाइन सेव्ह होत नाही.',
    drop_title: 'फोटो किंवा पोस्टर निवडा',
    drop_hint: 'JPG, PNG, WebP किंवा GIF · इथे ओढून सोडा, किंवा पेस्ट करा (Ctrl+V)',
    pick_btn: 'चित्र निवडा',
    sample_btn: 'नमुना पाहा',
    loaded_sample: 'नमुना पोस्टर उघडले आहे. सुरू करण्यासाठी तुमचे चित्र निवडा.',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'मोठा फोटो जलद कामासाठी {w} × {h} px पर्यंत लहान केला.',
    picture: 'चित्र',
    err_open: 'ही फाइल चित्र म्हणून उघडता आली नाही. JPG किंवा PNG वापरून पाहा.',
    err_heic: 'HEIC फोटो (iPhone) इथे उघडत नाहीत. फोनमधून फोटो JPG म्हणून शेअर करा, किंवा आमच्या Image Compressor ने बदला.',
    err_heic_link: 'Image Compressor उघडा',
    too_big: 'ही फाइल खूप मोठी आहे. 80 MB पेक्षा लहान फोटो वापरा.',
    err_export: 'चित्र सेव्ह होऊ शकले नाही. लहान साइझ किंवा PNG वापरून पाहा.',
    h_adjust: 'जुळवा',
    stage_aria: 'चित्राचा प्रीव्ह्यू. हलवण्यासाठी ओढा, झूमसाठी माउस व्हील किंवा दोन बोटे वापरा.',
    drag_hint: 'चित्र हलवण्यासाठी ओढा · झूमसाठी स्क्रोल करा किंवा दोन बोटांनी पसरवा',
    keys_hint: 'कीबोर्ड: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> हलवा · <kbd>+</kbd> <kbd>−</kbd> झूम · <kbd>0</kbd> रीसेट · <kbd>F</kbd> फिट / फिल',
    mode_label: 'फिट किंवा फिल',
    mode_fit: 'फिट (पूर्ण चित्र)',
    mode_fill: 'फिल (साइझनुसार क्रॉप)',
    zoom: 'झूम',
    center_btn: 'जागा आणि झूम रीसेट करा',
    bg_label: 'पार्श्वभूमी (चित्र पूर्ण फ्रेम भरत नसेल तेव्हा)',
    bg_blur: 'अस्पष्ट फोटो',
    bg_auto: 'आपोआप रंग',
    bg_white: 'पांढरा',
    bg_black: 'काळा',
    bg_custom: 'रंग निवडा',
    safe_show: 'सुरक्षित भाग दाखवा',
    apply_all: 'सर्व साइझना हाच फिट / फिल',
    applied_all: 'सर्व साइझना लागू झाले.',
    safe_hint_bands: 'नावे आणि किंमती वर-खालच्या छायांकित भागाबाहेर ठेवा: तिथे ॲपची बटणे आणि कॅप्शन येतात.',
    safe_hint_rect: 'प्रत्येक डिव्हाइसवर (TV, कंप्युटर आणि फोन) फक्त उजळ भागच दिसतो.',
    safe_hint_circle: 'हे चित्र गोल दाखवले जाते: छायांकित कोपरे कापले जातात.',
    safe_hint_avoid: 'छायांकित कोपरा व्हिडिओच्या लांबीने किंवा प्रोफाइल फोटोने झाकला जातो.',
    h_caption: 'कॅप्शन पट्टी',
    caption_on: 'कॅप्शन पट्टी जोडा',
    caption_text: 'कॅप्शनचा मजकूर',
    caption_ph: 'उदा. शर्मा स्वीट्स · दिवाळी ऑफर · 20% सूट',
    caption_pos: 'जागा',
    pos_top: 'वर',
    pos_bottom: 'खाली',
    caption_style: 'शैली',
    style_dark: 'गडद',
    style_light: 'फिकट',
    style_brand: 'निवडलेला रंग',
    on_badge: 'चालू',
    h_logo: 'कोपऱ्यात लोगो',
    logo_pick: 'लोगो जोडा',
    logo_remove: 'लोगो काढा',
    logo_hint: 'पारदर्शक पार्श्वभूमीचा PNG सर्वात चांगला दिसतो.',
    logo_corner: 'कोपरा',
    corner_tl: 'वर डावीकडे',
    corner_tr: 'वर उजवीकडे',
    corner_bl: 'खाली डावीकडे',
    corner_br: 'खाली उजवीकडे',
    logo_size: 'लोगोचा आकार',
    h_sizes: 'साइझ',
    sizes_hint: 'जुळवण्यासाठी एखाद्या साइझवर टॅप करा. डाउनलोड करायच्या साइझना टिक करा.',
    custom_w: 'रुंदी (px)',
    custom_h: 'उंची (px)',
    custom_hint: '16 ते 4096 px मधील कोणताही साइझ.',
    sel_count: 'डाउनलोडसाठी {n} साइझना टिक आहे',
    sel_all: 'सर्वांना टिक',
    sel_none: 'सर्व टिक काढा',
    tick_aria: '{name} डाउनलोड करा',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'स्वतःचा साइझ',
    p_ig_square: 'पोस्ट (चौकोनी)',
    p_ig_portrait: 'पोस्ट (उभी)',
    p_ig_landscape: 'पोस्ट (आडवी)',
    p_ig_story: 'स्टोरी आणि रील कव्हर',
    p_ig_dp: 'प्रोफाइल फोटो',
    p_yt_thumb: 'व्हिडिओ थंबनेल',
    p_yt_shorts: 'Shorts कव्हर',
    p_yt_banner: 'चॅनल बॅनर',
    p_yt_dp: 'चॅनलचा फोटो',
    p_wa_dp: 'प्रोफाइल फोटो (DP)',
    p_wa_status: 'स्टेटस',
    p_fb_post: 'पोस्ट (आडवी)',
    p_fb_square: 'पोस्ट (चौकोनी)',
    p_fb_cover: 'पेज कव्हर',
    p_fb_story: 'स्टोरी',
    p_li_post: 'पोस्ट',
    p_li_banner: 'प्रोफाइल बॅनर',
    p_x_post: 'पोस्ट',
    p_x_header: 'हेडर',
    p_gb_photo: 'व्यवसायाचा फोटो',
    p_gb_cover: 'कव्हर फोटो',
    p_custom: 'स्वतःचा साइझ',
    h_export: 'डाउनलोड',
    fmt_label: 'फॉर्मॅट',
    fmt_hint_jpg: 'JPG: लहान फाइल्स, फोटोंसाठी सर्वोत्तम.',
    fmt_hint_png: 'PNG: स्पष्ट मजकूर आणि लोगो, फाइल्स मोठ्या.',
    quality: 'JPG गुणवत्ता',
    est_size: '{w} × {h} px वर सुमारे {kb} KB',
    dl_this: 'हा साइझ डाउनलोड करा ({w} × {h})',
    dl_all: 'टिक केलेले {n} साइझ डाउनलोड करा',
    dl_none: 'आधी किमान एका साइझला टिक करा.',
    dl_many_hint: 'फाइल्स एकेक करून डाउनलोड होतात. ब्राउझरने अनेक डाउनलोडची परवानगी मागितली तर हो म्हणा.',
    dl_done: '{name} सेव्ह झाली ({kb} KB)',
    dl_progress: '{n} पैकी {i}: {name}',
    dl_all_done: '{n} फाइल्स डाउनलोड झाल्या.',
    share_btn: 'हा साइझ शेअर करा',
    reset_all: 'सेटिंग्ज रीसेट करा',
    help_title: 'कसे वापरायचे / कल्पना',
    tip1: 'चित्र निवडा, एखाद्या साइझवर टॅप करा, मग चित्र ओढून जागेवर ठेवा. महत्त्वाच्या भागावर झूम करण्यासाठी स्क्रोल करा किंवा दोन बोटांनी पसरवा. प्रत्येक साइझ आपली जागा लक्षात ठेवतो.',
    tip2: 'फिट पूर्ण पोस्टर ठेवतो आणि रिकामी जागा अस्पष्ट प्रतीने किंवा रंगाने भरतो. फिल चित्र नेमक्या आकारात क्रॉप करतो. "सर्व साइझना हाच फिट / फिल" तुमची निवड सगळीकडे लागू करतो.',
    tip3: 'दुकानदार: ऑफरचे पोस्टर एकदा बनवा, Instagram पोस्ट, WhatsApp स्टेटस आणि Facebook कव्हरला टिक करा आणि सर्व एकत्र डाउनलोड करा. कॅप्शन पट्टीत दुकानाचे नाव टाका.',
    tip4: 'क्रिएटर: Shorts, Reels आणि स्टेटसमध्ये मजकूर वर-खालच्या छायांकित भागाबाहेर ठेवा, तिथे ॲपची बटणे असतात. YouTube बॅनरमध्ये सर्व काही उजळ मधल्या भागात ठेवा.',
    tip5: 'शाळा आणि ऑफिस: एका नोटिसचा फोटो एका मिनिटात WhatsApp DP, YouTube थंबनेल आणि Facebook कव्हर बनतो. कोपऱ्यात लोगो ठेवा, म्हणजे प्रत्येक पोस्ट तुमची ओळख दाखवेल.',
    tip6: 'मजकूर आणि लोगो असलेल्या पोस्टरसाठी PNG निवडा. फोटोंसाठी JPG गुणवत्ता 85–92 ठेवा: फाइल्स लहान राहतात आणि संथ नेटवर्कवरही लवकर अपलोड होतात.',
    sample_shop: 'शर्मा स्वीट्स',
    sample_offer: 'दिवाळी स्पेशल · रोज सकाळी ताजे',
    sample_off: '20% सूट'
  },
  gu: {
    app_title: 'સોશિયલ પોસ્ટ રીસાઇઝર',
    intro: 'એક ફોટો કે પોસ્ટરને Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X અને Google Business ની સાચી સાઇઝમાં બદલો: ખેંચીને જગ્યા પર મૂકો, ઝૂમ કરો, પછી દરેક સાઇઝ ડાઉનલોડ કરો.',
    privacy_head: 'તમારા ફોટા કદી આ ડિવાઇસની બહાર જતા નથી.',
    privacy_body: 'સાઇઝ બદલવાનું કામ તમારા બ્રાઉઝરની અંદર જ થાય છે. કશું અપલોડ થતું નથી, કશું ઑનલાઇન સેવ થતું નથી.',
    drop_title: 'ફોટો કે પોસ્ટર પસંદ કરો',
    drop_hint: 'JPG, PNG, WebP કે GIF · અહીં ખેંચીને છોડો, કે પેસ્ટ કરો (Ctrl+V)',
    pick_btn: 'ચિત્ર પસંદ કરો',
    sample_btn: 'નમૂનો જુઓ',
    loaded_sample: 'નમૂનાનું પોસ્ટર ખુલ્લું છે. શરૂ કરવા તમારું ચિત્ર પસંદ કરો.',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'મોટો ફોટો ઝડપી કામ માટે {w} × {h} px સુધી નાનો કર્યો.',
    picture: 'ચિત્ર',
    err_open: 'આ ફાઇલ ચિત્ર તરીકે ખોલી શકાઈ નહીં. JPG કે PNG અજમાવો.',
    err_heic: 'HEIC ફોટા (iPhone) અહીં ખૂલતા નથી. ફોનમાંથી ફોટો JPG તરીકે શેર કરો, કે અમારા Image Compressor થી બદલો.',
    err_heic_link: 'Image Compressor ખોલો',
    too_big: 'આ ફાઇલ બહુ મોટી છે. 80 MB થી નાનો ફોટો અજમાવો.',
    err_export: 'ચિત્ર સેવ થઈ શક્યું નહીં. નાની સાઇઝ કે PNG અજમાવો.',
    h_adjust: 'ગોઠવો',
    stage_aria: 'ચિત્રનો પ્રીવ્યૂ. ખસેડવા ખેંચો, ઝૂમ માટે માઉસ વ્હીલ કે બે આંગળી વાપરો.',
    drag_hint: 'ચિત્ર ખસેડવા ખેંચો · ઝૂમ માટે સ્ક્રોલ કરો કે બે આંગળીથી ફેલાવો',
    keys_hint: 'કીબોર્ડ: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> ખસેડો · <kbd>+</kbd> <kbd>−</kbd> ઝૂમ · <kbd>0</kbd> રીસેટ · <kbd>F</kbd> ફિટ / ફિલ',
    mode_label: 'ફિટ કે ફિલ',
    mode_fit: 'ફિટ (પૂરું ચિત્ર)',
    mode_fill: 'ફિલ (સાઇઝ મુજબ ક્રૉપ)',
    zoom: 'ઝૂમ',
    center_btn: 'જગ્યા અને ઝૂમ રીસેટ કરો',
    bg_label: 'બૅકગ્રાઉન્ડ (ચિત્ર પૂરી ફ્રેમ ન ભરે ત્યારે)',
    bg_blur: 'ઝાંખો ફોટો',
    bg_auto: 'આપમેળે રંગ',
    bg_white: 'સફેદ',
    bg_black: 'કાળો',
    bg_custom: 'રંગ પસંદ કરો',
    safe_show: 'સલામત ભાગ બતાવો',
    apply_all: 'બધી સાઇઝમાં આ જ ફિટ / ફિલ',
    applied_all: 'બધી સાઇઝ પર લાગુ થયું.',
    safe_hint_bands: 'નામ અને ભાવ ઉપર-નીચેના છાંયાવાળા ભાગથી બહાર રાખો: ત્યાં ઍપના બટન અને કૅપ્શન આવી જાય છે.',
    safe_hint_rect: 'દરેક ડિવાઇસ (TV, કમ્પ્યૂટર અને ફોન) પર ફક્ત ચમકતો ભાગ જ દેખાય છે.',
    safe_hint_circle: 'આ ચિત્ર ગોળ દેખાય છે: છાંયાવાળા ખૂણા કપાઈ જાય છે.',
    safe_hint_avoid: 'છાંયાવાળો ખૂણો વિડિયોની લંબાઈ કે પ્રોફાઇલ ફોટાથી ઢંકાઈ જાય છે.',
    h_caption: 'કૅપ્શન પટ્ટી',
    caption_on: 'કૅપ્શન પટ્ટી ઉમેરો',
    caption_text: 'કૅપ્શનનું લખાણ',
    caption_ph: 'જેમ કે: શર્મા સ્વીટ્સ · દિવાળી ઑફર · 20% છૂટ',
    caption_pos: 'જગ્યા',
    pos_top: 'ઉપર',
    pos_bottom: 'નીચે',
    caption_style: 'સ્ટાઇલ',
    style_dark: 'ઘેરો',
    style_light: 'આછો',
    style_brand: 'પસંદ કરેલો રંગ',
    on_badge: 'ચાલુ',
    h_logo: 'ખૂણામાં લોગો',
    logo_pick: 'લોગો ઉમેરો',
    logo_remove: 'લોગો કાઢો',
    logo_hint: 'પારદર્શક બૅકગ્રાઉન્ડવાળો PNG સૌથી સારો દેખાય છે.',
    logo_corner: 'ખૂણો',
    corner_tl: 'ઉપર ડાબે',
    corner_tr: 'ઉપર જમણે',
    corner_bl: 'નીચે ડાબે',
    corner_br: 'નીચે જમણે',
    logo_size: 'લોગોની સાઇઝ',
    h_sizes: 'સાઇઝ',
    sizes_hint: 'ગોઠવવા કોઈ સાઇઝ પર ટૅપ કરો. જે સાઇઝ ડાઉનલોડ કરવી હોય તેના પર ટિક કરો.',
    custom_w: 'પહોળાઈ (px)',
    custom_h: 'ઊંચાઈ (px)',
    custom_hint: '16 થી 4096 px વચ્ચેની કોઈ પણ સાઇઝ.',
    sel_count: 'ડાઉનલોડ માટે {n} સાઇઝ પર ટિક છે',
    sel_all: 'બધા પર ટિક',
    sel_none: 'બધી ટિક કાઢો',
    tick_aria: '{name} ડાઉનલોડ કરો',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'પોતાની સાઇઝ',
    p_ig_square: 'પોસ્ટ (ચોરસ)',
    p_ig_portrait: 'પોસ્ટ (ઊભી)',
    p_ig_landscape: 'પોસ્ટ (આડી)',
    p_ig_story: 'સ્ટોરી અને રીલ કવર',
    p_ig_dp: 'પ્રોફાઇલ ફોટો',
    p_yt_thumb: 'વિડિયો થંબનેલ',
    p_yt_shorts: 'Shorts કવર',
    p_yt_banner: 'ચૅનલ બૅનર',
    p_yt_dp: 'ચૅનલનો ફોટો',
    p_wa_dp: 'પ્રોફાઇલ ફોટો (DP)',
    p_wa_status: 'સ્ટેટસ',
    p_fb_post: 'પોસ્ટ (આડી)',
    p_fb_square: 'પોસ્ટ (ચોરસ)',
    p_fb_cover: 'પેજ કવર',
    p_fb_story: 'સ્ટોરી',
    p_li_post: 'પોસ્ટ',
    p_li_banner: 'પ્રોફાઇલ બૅનર',
    p_x_post: 'પોસ્ટ',
    p_x_header: 'હેડર',
    p_gb_photo: 'બિઝનેસ ફોટો',
    p_gb_cover: 'કવર ફોટો',
    p_custom: 'પોતાની સાઇઝ',
    h_export: 'ડાઉનલોડ',
    fmt_label: 'ફૉર્મેટ',
    fmt_hint_jpg: 'JPG: નાની ફાઇલો, ફોટા માટે શ્રેષ્ઠ.',
    fmt_hint_png: 'PNG: સ્પષ્ટ લખાણ અને લોગો, ફાઇલો મોટી.',
    quality: 'JPG ક્વૉલિટી',
    est_size: '{w} × {h} px પર લગભગ {kb} KB',
    dl_this: 'આ સાઇઝ ડાઉનલોડ કરો ({w} × {h})',
    dl_all: 'ટિક કરેલી {n} સાઇઝ ડાઉનલોડ કરો',
    dl_none: 'પહેલાં ઓછામાં ઓછી એક સાઇઝ પર ટિક કરો.',
    dl_many_hint: 'ફાઇલો એક પછી એક ડાઉનલોડ થાય છે. બ્રાઉઝર ઘણા ડાઉનલોડની પરવાનગી માગે તો હા કહો.',
    dl_done: '{name} સેવ થઈ ({kb} KB)',
    dl_progress: '{n} માંથી {i}: {name}',
    dl_all_done: '{n} ફાઇલો ડાઉનલોડ થઈ.',
    share_btn: 'આ સાઇઝ શેર કરો',
    reset_all: 'સેટિંગ્સ રીસેટ કરો',
    help_title: 'કેવી રીતે વાપરવું / વિચારો',
    tip1: 'ચિત્ર પસંદ કરો, કોઈ સાઇઝ પર ટૅપ કરો, પછી ચિત્રને ખેંચીને જગ્યા પર મૂકો. જરૂરી ભાગ પર ઝૂમ કરવા સ્ક્રોલ કરો કે બે આંગળીથી ફેલાવો. દરેક સાઇઝ પોતાની જગ્યા યાદ રાખે છે.',
    tip2: 'ફિટ પૂરું પોસ્ટર રાખે છે અને ખાલી જગ્યા ઝાંખી નકલ કે રંગથી ભરે છે. ફિલ ચિત્રને બરાબર આકારમાં ક્રૉપ કરે છે. "બધી સાઇઝમાં આ જ ફિટ / ફિલ" તમારી પસંદગી બધે લાગુ કરે છે.',
    tip3: 'દુકાનદારો: ઑફરનું પોસ્ટર એક વાર બનાવો, Instagram પોસ્ટ, WhatsApp સ્ટેટસ અને Facebook કવર પર ટિક કરો અને બધું સાથે ડાઉનલોડ કરો. કૅપ્શન પટ્ટીમાં દુકાનનું નામ લખો.',
    tip4: 'ક્રિએટર્સ: Shorts, Reels અને સ્ટેટસમાં લખાણ ઉપર-નીચેના છાંયાવાળા ભાગથી બહાર રાખો, ત્યાં ઍપના બટન હોય છે. YouTube બૅનરમાં બધું ચમકતા વચ્ચેના ભાગમાં રાખો.',
    tip5: 'શાળા અને ઑફિસ: એક નોટિસનો ફોટો એક મિનિટમાં WhatsApp DP, YouTube થંબનેલ અને Facebook કવર બની જાય છે. ખૂણામાં લોગો મૂકો, જેથી દરેક પોસ્ટ તમારી ઓળખ બતાવે.',
    tip6: 'લખાણ અને લોગોવાળા પોસ્ટર માટે PNG પસંદ કરો. ફોટા માટે JPG ક્વૉલિટી 85–92 રાખો: ફાઇલો નાની રહે છે અને ધીમા નેટવર્ક પર પણ ઝડપથી અપલોડ થાય છે.',
    sample_shop: 'શર્મા સ્વીટ્સ',
    sample_offer: 'દિવાળી સ્પેશિયલ · દર સવારે તાજું',
    sample_off: '20% છૂટ'
  },
  pa: {
    app_title: 'ਸੋਸ਼ਲ ਪੋਸਟ ਰੀਸਾਈਜ਼ਰ',
    intro: 'ਇੱਕ ਫੋਟੋ ਜਾਂ ਪੋਸਟਰ ਨੂੰ Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X ਅਤੇ Google Business ਦੇ ਸਹੀ ਸਾਈਜ਼ ਵਿੱਚ ਬਦਲੋ: ਖਿੱਚ ਕੇ ਥਾਂ ਤੇ ਰੱਖੋ, ਜ਼ੂਮ ਕਰੋ, ਫਿਰ ਹਰ ਸਾਈਜ਼ ਡਾਊਨਲੋਡ ਕਰੋ।',
    privacy_head: 'ਤੁਹਾਡੀਆਂ ਫੋਟੋਆਂ ਕਦੇ ਇਸ ਡਿਵਾਈਸ ਤੋਂ ਬਾਹਰ ਨਹੀਂ ਜਾਂਦੀਆਂ।',
    privacy_body: 'ਸਾਈਜ਼ ਬਦਲਣ ਦਾ ਕੰਮ ਤੁਹਾਡੇ ਬ੍ਰਾਊਜ਼ਰ ਦੇ ਅੰਦਰ ਹੀ ਹੁੰਦਾ ਹੈ। ਕੁਝ ਵੀ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ, ਕੁਝ ਵੀ ਆਨਲਾਈਨ ਸੇਵ ਨਹੀਂ ਹੁੰਦਾ।',
    drop_title: 'ਫੋਟੋ ਜਾਂ ਪੋਸਟਰ ਚੁਣੋ',
    drop_hint: 'JPG, PNG, WebP ਜਾਂ GIF · ਇੱਥੇ ਖਿੱਚ ਕੇ ਛੱਡੋ, ਜਾਂ ਪੇਸਟ ਕਰੋ (Ctrl+V)',
    pick_btn: 'ਤਸਵੀਰ ਚੁਣੋ',
    sample_btn: 'ਨਮੂਨਾ ਦੇਖੋ',
    loaded_sample: 'ਨਮੂਨਾ ਪੋਸਟਰ ਖੁੱਲ੍ਹਾ ਹੈ। ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਤਸਵੀਰ ਚੁਣੋ।',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'ਵੱਡੀ ਫੋਟੋ ਤੇਜ਼ ਕੰਮ ਲਈ {w} × {h} px ਤੱਕ ਛੋਟੀ ਕੀਤੀ ਗਈ।',
    picture: 'ਤਸਵੀਰ',
    err_open: 'ਇਹ ਫ਼ਾਈਲ ਤਸਵੀਰ ਵਾਂਗ ਨਹੀਂ ਖੁੱਲ੍ਹ ਸਕੀ। JPG ਜਾਂ PNG ਵਰਤ ਕੇ ਦੇਖੋ।',
    err_heic: 'HEIC ਫੋਟੋਆਂ (iPhone) ਇੱਥੇ ਨਹੀਂ ਖੁੱਲ੍ਹਦੀਆਂ। ਫ਼ੋਨ ਤੋਂ ਫੋਟੋ JPG ਵਜੋਂ ਸਾਂਝੀ ਕਰੋ, ਜਾਂ ਸਾਡੇ Image Compressor ਨਾਲ ਬਦਲੋ।',
    err_heic_link: 'Image Compressor ਖੋਲ੍ਹੋ',
    too_big: 'ਇਹ ਫ਼ਾਈਲ ਬਹੁਤ ਵੱਡੀ ਹੈ। 80 MB ਤੋਂ ਛੋਟੀ ਫੋਟੋ ਵਰਤੋ।',
    err_export: 'ਤਸਵੀਰ ਸੇਵ ਨਹੀਂ ਹੋ ਸਕੀ। ਛੋਟਾ ਸਾਈਜ਼ ਜਾਂ PNG ਵਰਤ ਕੇ ਦੇਖੋ।',
    h_adjust: 'ਸੈੱਟ ਕਰੋ',
    stage_aria: 'ਤਸਵੀਰ ਦਾ ਪ੍ਰੀਵਿਊ। ਹਿਲਾਉਣ ਲਈ ਖਿੱਚੋ, ਜ਼ੂਮ ਲਈ ਮਾਊਸ ਵ੍ਹੀਲ ਜਾਂ ਦੋ ਉਂਗਲਾਂ ਵਰਤੋ।',
    drag_hint: 'ਤਸਵੀਰ ਹਿਲਾਉਣ ਲਈ ਖਿੱਚੋ · ਜ਼ੂਮ ਲਈ ਸਕ੍ਰੋਲ ਕਰੋ ਜਾਂ ਦੋ ਉਂਗਲਾਂ ਨਾਲ ਫੈਲਾਓ',
    keys_hint: 'ਕੀਬੋਰਡ: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> ਹਿਲਾਓ · <kbd>+</kbd> <kbd>−</kbd> ਜ਼ੂਮ · <kbd>0</kbd> ਰੀਸੈੱਟ · <kbd>F</kbd> ਫਿੱਟ / ਫਿੱਲ',
    mode_label: 'ਫਿੱਟ ਜਾਂ ਫਿੱਲ',
    mode_fit: 'ਫਿੱਟ (ਪੂਰੀ ਤਸਵੀਰ)',
    mode_fill: 'ਫਿੱਲ (ਸਾਈਜ਼ ਮੁਤਾਬਕ ਕ੍ਰੌਪ)',
    zoom: 'ਜ਼ੂਮ',
    center_btn: 'ਥਾਂ ਅਤੇ ਜ਼ੂਮ ਰੀਸੈੱਟ ਕਰੋ',
    bg_label: 'ਬੈਕਗ੍ਰਾਊਂਡ (ਜਦੋਂ ਤਸਵੀਰ ਪੂਰਾ ਫ੍ਰੇਮ ਨਾ ਭਰੇ)',
    bg_blur: 'ਧੁੰਦਲੀ ਫੋਟੋ',
    bg_auto: 'ਆਪਣੇ ਆਪ ਰੰਗ',
    bg_white: 'ਸਫ਼ੈਦ',
    bg_black: 'ਕਾਲਾ',
    bg_custom: 'ਰੰਗ ਚੁਣੋ',
    safe_show: 'ਸੁਰੱਖਿਅਤ ਹਿੱਸਾ ਦਿਖਾਓ',
    apply_all: 'ਸਾਰੇ ਸਾਈਜ਼ਾਂ ਲਈ ਇਹੀ ਫਿੱਟ / ਫਿੱਲ',
    applied_all: 'ਸਾਰੇ ਸਾਈਜ਼ਾਂ ਤੇ ਲਾਗੂ ਹੋ ਗਿਆ।',
    safe_hint_bands: 'ਨਾਂ ਅਤੇ ਕੀਮਤਾਂ ਉੱਪਰ-ਹੇਠਾਂ ਦੇ ਛਾਂਦਾਰ ਹਿੱਸੇ ਤੋਂ ਬਾਹਰ ਰੱਖੋ: ਉੱਥੇ ਐਪ ਦੇ ਬਟਨ ਅਤੇ ਕੈਪਸ਼ਨ ਆ ਜਾਂਦੇ ਹਨ।',
    safe_hint_rect: 'ਹਰ ਡਿਵਾਈਸ (TV, ਕੰਪਿਊਟਰ ਅਤੇ ਫ਼ੋਨ) ਤੇ ਸਿਰਫ਼ ਚਮਕਦਾ ਹਿੱਸਾ ਹੀ ਦਿਖਦਾ ਹੈ।',
    safe_hint_circle: 'ਇਹ ਤਸਵੀਰ ਗੋਲ ਦਿਖਦੀ ਹੈ: ਛਾਂਦਾਰ ਕੋਨੇ ਕੱਟ ਜਾਂਦੇ ਹਨ।',
    safe_hint_avoid: 'ਛਾਂਦਾਰ ਕੋਨਾ ਵੀਡੀਓ ਦੀ ਲੰਬਾਈ ਜਾਂ ਪ੍ਰੋਫ਼ਾਈਲ ਫੋਟੋ ਨਾਲ ਢਕ ਜਾਂਦਾ ਹੈ।',
    h_caption: 'ਕੈਪਸ਼ਨ ਪੱਟੀ',
    caption_on: 'ਕੈਪਸ਼ਨ ਪੱਟੀ ਜੋੜੋ',
    caption_text: 'ਕੈਪਸ਼ਨ ਦਾ ਟੈਕਸਟ',
    caption_ph: 'ਜਿਵੇਂ: ਸ਼ਰਮਾ ਸਵੀਟਸ · ਦੀਵਾਲੀ ਆਫ਼ਰ · 20% ਛੋਟ',
    caption_pos: 'ਥਾਂ',
    pos_top: 'ਉੱਪਰ',
    pos_bottom: 'ਹੇਠਾਂ',
    caption_style: 'ਸਟਾਈਲ',
    style_dark: 'ਗੂੜ੍ਹਾ',
    style_light: 'ਹਲਕਾ',
    style_brand: 'ਚੁਣਿਆ ਰੰਗ',
    on_badge: 'ਚਾਲੂ',
    h_logo: 'ਕੋਨੇ ਵਿੱਚ ਲੋਗੋ',
    logo_pick: 'ਲੋਗੋ ਜੋੜੋ',
    logo_remove: 'ਲੋਗੋ ਹਟਾਓ',
    logo_hint: 'ਪਾਰਦਰਸ਼ੀ ਬੈਕਗ੍ਰਾਊਂਡ ਵਾਲਾ PNG ਸਭ ਤੋਂ ਵਧੀਆ ਦਿਖਦਾ ਹੈ।',
    logo_corner: 'ਕੋਨਾ',
    corner_tl: 'ਉੱਪਰ ਖੱਬੇ',
    corner_tr: 'ਉੱਪਰ ਸੱਜੇ',
    corner_bl: 'ਹੇਠਾਂ ਖੱਬੇ',
    corner_br: 'ਹੇਠਾਂ ਸੱਜੇ',
    logo_size: 'ਲੋਗੋ ਦਾ ਸਾਈਜ਼',
    h_sizes: 'ਸਾਈਜ਼',
    sizes_hint: 'ਸੈੱਟ ਕਰਨ ਲਈ ਕਿਸੇ ਸਾਈਜ਼ ਤੇ ਟੈਪ ਕਰੋ। ਜੋ ਸਾਈਜ਼ ਡਾਊਨਲੋਡ ਕਰਨੇ ਹਨ, ਉਨ੍ਹਾਂ ਤੇ ਟਿੱਕ ਲਗਾਓ।',
    custom_w: 'ਚੌੜਾਈ (px)',
    custom_h: 'ਉਚਾਈ (px)',
    custom_hint: '16 ਤੋਂ 4096 px ਤੱਕ ਕੋਈ ਵੀ ਸਾਈਜ਼।',
    sel_count: 'ਡਾਊਨਲੋਡ ਲਈ {n} ਸਾਈਜ਼ਾਂ ਤੇ ਟਿੱਕ ਹੈ',
    sel_all: 'ਸਭ ਤੇ ਟਿੱਕ',
    sel_none: 'ਸਾਰੇ ਟਿੱਕ ਹਟਾਓ',
    tick_aria: '{name} ਡਾਊਨਲੋਡ ਕਰੋ',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'ਆਪਣਾ ਸਾਈਜ਼',
    p_ig_square: 'ਪੋਸਟ (ਚੌਰਸ)',
    p_ig_portrait: 'ਪੋਸਟ (ਖੜ੍ਹੀ)',
    p_ig_landscape: 'ਪੋਸਟ (ਲੇਟਵੀਂ)',
    p_ig_story: 'ਸਟੋਰੀ ਅਤੇ ਰੀਲ ਕਵਰ',
    p_ig_dp: 'ਪ੍ਰੋਫ਼ਾਈਲ ਫੋਟੋ',
    p_yt_thumb: 'ਵੀਡੀਓ ਥੰਬਨੇਲ',
    p_yt_shorts: 'Shorts ਕਵਰ',
    p_yt_banner: 'ਚੈਨਲ ਬੈਨਰ',
    p_yt_dp: 'ਚੈਨਲ ਦੀ ਫੋਟੋ',
    p_wa_dp: 'ਪ੍ਰੋਫ਼ਾਈਲ ਫੋਟੋ (DP)',
    p_wa_status: 'ਸਟੇਟਸ',
    p_fb_post: 'ਪੋਸਟ (ਲੇਟਵੀਂ)',
    p_fb_square: 'ਪੋਸਟ (ਚੌਰਸ)',
    p_fb_cover: 'ਪੇਜ ਕਵਰ',
    p_fb_story: 'ਸਟੋਰੀ',
    p_li_post: 'ਪੋਸਟ',
    p_li_banner: 'ਪ੍ਰੋਫ਼ਾਈਲ ਬੈਨਰ',
    p_x_post: 'ਪੋਸਟ',
    p_x_header: 'ਹੈਡਰ',
    p_gb_photo: 'ਬਿਜ਼ਨਸ ਫੋਟੋ',
    p_gb_cover: 'ਕਵਰ ਫੋਟੋ',
    p_custom: 'ਆਪਣਾ ਸਾਈਜ਼',
    h_export: 'ਡਾਊਨਲੋਡ',
    fmt_label: 'ਫਾਰਮੈਟ',
    fmt_hint_jpg: 'JPG: ਛੋਟੀਆਂ ਫ਼ਾਈਲਾਂ, ਫੋਟੋਆਂ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ।',
    fmt_hint_png: 'PNG: ਸਾਫ਼ ਟੈਕਸਟ ਅਤੇ ਲੋਗੋ, ਫ਼ਾਈਲਾਂ ਵੱਡੀਆਂ।',
    quality: 'JPG ਕੁਆਲਿਟੀ',
    est_size: '{w} × {h} px ਤੇ ਲਗਭਗ {kb} KB',
    dl_this: 'ਇਹ ਸਾਈਜ਼ ਡਾਊਨਲੋਡ ਕਰੋ ({w} × {h})',
    dl_all: 'ਟਿੱਕ ਕੀਤੇ {n} ਸਾਈਜ਼ ਡਾਊਨਲੋਡ ਕਰੋ',
    dl_none: 'ਪਹਿਲਾਂ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਸਾਈਜ਼ ਤੇ ਟਿੱਕ ਲਗਾਓ।',
    dl_many_hint: 'ਫ਼ਾਈਲਾਂ ਇੱਕ-ਇੱਕ ਕਰਕੇ ਡਾਊਨਲੋਡ ਹੁੰਦੀਆਂ ਹਨ। ਜੇ ਬ੍ਰਾਊਜ਼ਰ ਕਈ ਡਾਊਨਲੋਡਾਂ ਦੀ ਇਜਾਜ਼ਤ ਮੰਗੇ, ਤਾਂ ਹਾਂ ਕਹੋ।',
    dl_done: '{name} ਸੇਵ ਹੋਈ ({kb} KB)',
    dl_progress: '{n} ਵਿੱਚੋਂ {i}: {name}',
    dl_all_done: '{n} ਫ਼ਾਈਲਾਂ ਡਾਊਨਲੋਡ ਹੋਈਆਂ।',
    share_btn: 'ਇਹ ਸਾਈਜ਼ ਸਾਂਝਾ ਕਰੋ',
    reset_all: 'ਸੈਟਿੰਗਾਂ ਰੀਸੈੱਟ ਕਰੋ',
    help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ / ਸੁਝਾਅ',
    tip1: 'ਤਸਵੀਰ ਚੁਣੋ, ਕਿਸੇ ਸਾਈਜ਼ ਤੇ ਟੈਪ ਕਰੋ, ਫਿਰ ਤਸਵੀਰ ਨੂੰ ਖਿੱਚ ਕੇ ਥਾਂ ਤੇ ਰੱਖੋ। ਜ਼ਰੂਰੀ ਹਿੱਸੇ ਤੇ ਜ਼ੂਮ ਕਰਨ ਲਈ ਸਕ੍ਰੋਲ ਕਰੋ ਜਾਂ ਦੋ ਉਂਗਲਾਂ ਨਾਲ ਫੈਲਾਓ। ਹਰ ਸਾਈਜ਼ ਆਪਣੀ ਥਾਂ ਯਾਦ ਰੱਖਦਾ ਹੈ।',
    tip2: 'ਫਿੱਟ ਪੂਰਾ ਪੋਸਟਰ ਰੱਖਦਾ ਹੈ ਅਤੇ ਖਾਲੀ ਥਾਂ ਧੁੰਦਲੀ ਕਾਪੀ ਜਾਂ ਰੰਗ ਨਾਲ ਭਰਦਾ ਹੈ। ਫਿੱਲ ਤਸਵੀਰ ਨੂੰ ਸਹੀ ਆਕਾਰ ਵਿੱਚ ਕ੍ਰੌਪ ਕਰਦਾ ਹੈ। "ਸਾਰੇ ਸਾਈਜ਼ਾਂ ਲਈ ਇਹੀ ਫਿੱਟ / ਫਿੱਲ" ਤੁਹਾਡੀ ਪਸੰਦ ਹਰ ਥਾਂ ਲਾਗੂ ਕਰਦਾ ਹੈ।',
    tip3: 'ਦੁਕਾਨਦਾਰ: ਆਫ਼ਰ ਦਾ ਪੋਸਟਰ ਇੱਕ ਵਾਰ ਬਣਾਓ, Instagram ਪੋਸਟ, WhatsApp ਸਟੇਟਸ ਅਤੇ Facebook ਕਵਰ ਤੇ ਟਿੱਕ ਲਗਾਓ ਅਤੇ ਸਭ ਇਕੱਠੇ ਡਾਊਨਲੋਡ ਕਰੋ। ਕੈਪਸ਼ਨ ਪੱਟੀ ਵਿੱਚ ਦੁਕਾਨ ਦਾ ਨਾਂ ਲਿਖੋ।',
    tip4: 'ਕ੍ਰਿਏਟਰ: Shorts, Reels ਅਤੇ ਸਟੇਟਸ ਵਿੱਚ ਟੈਕਸਟ ਉੱਪਰ-ਹੇਠਾਂ ਦੇ ਛਾਂਦਾਰ ਹਿੱਸੇ ਤੋਂ ਬਾਹਰ ਰੱਖੋ, ਉੱਥੇ ਐਪ ਦੇ ਬਟਨ ਹੁੰਦੇ ਹਨ। YouTube ਬੈਨਰ ਵਿੱਚ ਸਭ ਕੁਝ ਚਮਕਦੇ ਵਿਚਕਾਰਲੇ ਹਿੱਸੇ ਵਿੱਚ ਰੱਖੋ।',
    tip5: 'ਸਕੂਲ ਅਤੇ ਦਫ਼ਤਰ: ਇੱਕ ਨੋਟਿਸ ਦੀ ਫੋਟੋ ਇੱਕ ਮਿੰਟ ਵਿੱਚ WhatsApp DP, YouTube ਥੰਬਨੇਲ ਅਤੇ Facebook ਕਵਰ ਬਣ ਜਾਂਦੀ ਹੈ। ਕੋਨੇ ਵਿੱਚ ਲੋਗੋ ਲਗਾਓ ਤਾਂ ਜੋ ਹਰ ਪੋਸਟ ਤੁਹਾਡੀ ਪਛਾਣ ਦਿਖਾਵੇ।',
    tip6: 'ਟੈਕਸਟ ਅਤੇ ਲੋਗੋ ਵਾਲੇ ਪੋਸਟਰਾਂ ਲਈ PNG ਚੁਣੋ। ਫੋਟੋਆਂ ਲਈ JPG ਕੁਆਲਿਟੀ 85–92 ਰੱਖੋ: ਫ਼ਾਈਲਾਂ ਛੋਟੀਆਂ ਰਹਿੰਦੀਆਂ ਹਨ ਅਤੇ ਧੀਮੇ ਨੈੱਟਵਰਕ ਤੇ ਵੀ ਜਲਦੀ ਅੱਪਲੋਡ ਹੁੰਦੀਆਂ ਹਨ।',
    sample_shop: 'ਸ਼ਰਮਾ ਸਵੀਟਸ',
    sample_offer: 'ਦੀਵਾਲੀ ਸਪੈਸ਼ਲ · ਹਰ ਸਵੇਰ ਤਾਜ਼ਾ',
    sample_off: '20% ਛੋਟ'
  },
  or: {
    app_title: 'ସୋସିଆଲ୍ ପୋଷ୍ଟ ରିସାଇଜର',
    intro: 'ଗୋଟିଏ ଫଟୋ କିମ୍ବା ପୋଷ୍ଟରକୁ Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X ଓ Google Business ର ଠିକ୍ ସାଇଜରେ ବଦଳାନ୍ତୁ: ଟାଣି ଜାଗାରେ ରଖନ୍ତୁ, ଜୁମ୍ କରନ୍ତୁ, ତା ପରେ ପ୍ରତ୍ୟେକ ସାଇଜ ଡାଉନଲୋଡ୍ କରନ୍ତୁ।',
    privacy_head: 'ଆପଣଙ୍କ ଫଟୋ କେବେ ବି ଏହି ଡିଭାଇସରୁ ବାହାରକୁ ଯାଏ ନାହିଁ।',
    privacy_body: 'ସାଇଜ ବଦଳାଇବା କାମ ଆପଣଙ୍କ ବ୍ରାଉଜର ଭିତରେ ହିଁ ହୁଏ। କିଛି ବି ଅପଲୋଡ୍ ହୁଏ ନାହିଁ, କିଛି ବି ଅନଲାଇନ୍ ସେଭ୍ ହୁଏ ନାହିଁ।',
    drop_title: 'ଫଟୋ କିମ୍ବା ପୋଷ୍ଟର ବାଛନ୍ତୁ',
    drop_hint: 'JPG, PNG, WebP କିମ୍ବା GIF · ଏଠାରେ ଟାଣି ଛାଡ଼ନ୍ତୁ, କିମ୍ବା ପେଷ୍ଟ କରନ୍ତୁ (Ctrl+V)',
    pick_btn: 'ଛବି ବାଛନ୍ତୁ',
    sample_btn: 'ନମୁନା ଦେଖନ୍ତୁ',
    loaded_sample: 'ନମୁନା ପୋଷ୍ଟର ଖୋଲା ଅଛି। ଆରମ୍ଭ କରିବାକୁ ନିଜ ଛବି ବାଛନ୍ତୁ।',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'ବଡ଼ ଫଟୋକୁ ଶୀଘ୍ର କାମ ପାଇଁ {w} × {h} px କୁ ଛୋଟ କରାଗଲା।',
    picture: 'ଛବି',
    err_open: 'ଏହି ଫାଇଲ୍ ଛବି ଭାବରେ ଖୋଲି ହେଲା ନାହିଁ। JPG କିମ୍ବା PNG ଚେଷ୍ଟା କରନ୍ତୁ।',
    err_heic: 'HEIC ଫଟୋ (iPhone) ଏଠାରେ ଖୋଲେ ନାହିଁ। ଫୋନରୁ ଫଟୋକୁ JPG ଭାବରେ ସେୟାର୍ କରନ୍ତୁ, କିମ୍ବା ଆମ Image Compressor ରେ ବଦଳାନ୍ତୁ।',
    err_heic_link: 'Image Compressor ଖୋଲନ୍ତୁ',
    too_big: 'ଏହି ଫାଇଲ୍ ବହୁତ ବଡ଼। 80 MB ରୁ ଛୋଟ ଫଟୋ ଚେଷ୍ଟା କରନ୍ତୁ।',
    err_export: 'ଛବି ସେଭ୍ ହୋଇପାରିଲା ନାହିଁ। ଛୋଟ ସାଇଜ କିମ୍ବା PNG ଚେଷ୍ଟା କରନ୍ତୁ।',
    h_adjust: 'ସଜାନ୍ତୁ',
    stage_aria: 'ଛବିର ପ୍ରିଭ୍ୟୁ। ଘୁଞ୍ଚାଇବାକୁ ଟାଣନ୍ତୁ, ଜୁମ୍ ପାଇଁ ମାଉସ୍ ହ୍ୱିଲ୍ କିମ୍ବା ଦୁଇ ଆଙ୍ଗୁଳି ବ୍ୟବହାର କରନ୍ତୁ।',
    drag_hint: 'ଛବି ଘୁଞ୍ଚାଇବାକୁ ଟାଣନ୍ତୁ · ଜୁମ୍ ପାଇଁ ସ୍କ୍ରୋଲ୍ କରନ୍ତୁ କିମ୍ବା ଦୁଇ ଆଙ୍ଗୁଳିରେ ମେଲାନ୍ତୁ',
    keys_hint: 'କୀବୋର୍ଡ: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> ଘୁଞ୍ଚାନ୍ତୁ · <kbd>+</kbd> <kbd>−</kbd> ଜୁମ୍ · <kbd>0</kbd> ରିସେଟ୍ · <kbd>F</kbd> ଫିଟ୍ / ଫିଲ୍',
    mode_label: 'ଫିଟ୍ କିମ୍ବା ଫିଲ୍',
    mode_fit: 'ଫିଟ୍ (ପୂରା ଛବି)',
    mode_fill: 'ଫିଲ୍ (ସାଇଜ ଅନୁସାରେ କ୍ରପ୍)',
    zoom: 'ଜୁମ୍',
    center_btn: 'ଜାଗା ଓ ଜୁମ୍ ରିସେଟ୍ କରନ୍ତୁ',
    bg_label: 'ପୃଷ୍ଠଭୂମି (ଛବି ପୂରା ଫ୍ରେମ୍ ନ ଭରିଲେ)',
    bg_blur: 'ଅସ୍ପଷ୍ଟ ଫଟୋ',
    bg_auto: 'ନିଜେ ନିଜେ ରଙ୍ଗ',
    bg_white: 'ଧଳା',
    bg_black: 'କଳା',
    bg_custom: 'ରଙ୍ଗ ବାଛନ୍ତୁ',
    safe_show: 'ସୁରକ୍ଷିତ ଅଂଶ ଦେଖାନ୍ତୁ',
    apply_all: 'ସବୁ ସାଇଜରେ ଏହି ଫିଟ୍ / ଫିଲ୍',
    applied_all: 'ସବୁ ସାଇଜରେ ଲାଗୁ ହେଲା।',
    safe_hint_bands: 'ନାମ ଓ ଦାମ ଉପର-ତଳର ଛାଇ ଅଂଶରୁ ବାହାରେ ରଖନ୍ତୁ: ସେଠାରେ ଆପ୍ ବଟନ୍ ଓ କ୍ୟାପସନ୍ ଆସିଯାଏ।',
    safe_hint_rect: 'ପ୍ରତ୍ୟେକ ଡିଭାଇସରେ (TV, କମ୍ପ୍ୟୁଟର ଓ ଫୋନ୍) କେବଳ ଉଜ୍ଜ୍ୱଳ ଅଂଶ ହିଁ ଦେଖାଯାଏ।',
    safe_hint_circle: 'ଏହି ଛବି ଗୋଲ ଦେଖାଯାଏ: ଛାଇ କୋଣ କଟିଯାଏ।',
    safe_hint_avoid: 'ଛାଇ କୋଣ ଭିଡିଓ ଲମ୍ବ କିମ୍ବା ପ୍ରୋଫାଇଲ୍ ଫଟୋ ଦ୍ୱାରା ଢାଙ୍କି ହୋଇଯାଏ।',
    h_caption: 'କ୍ୟାପସନ୍ ପଟି',
    caption_on: 'କ୍ୟାପସନ୍ ପଟି ଯୋଡ଼ନ୍ତୁ',
    caption_text: 'କ୍ୟାପସନ୍ ଲେଖା',
    caption_ph: 'ଯେପରି: ଶର୍ମା ସ୍ୱିଟ୍ସ · ଦୀପାବଳି ଅଫର · 20% ରିହାତି',
    caption_pos: 'ଜାଗା',
    pos_top: 'ଉପରେ',
    pos_bottom: 'ତଳେ',
    caption_style: 'ଷ୍ଟାଇଲ୍',
    style_dark: 'ଗାଢ଼',
    style_light: 'ହାଲୁକା',
    style_brand: 'ବଛା ରଙ୍ଗ',
    on_badge: 'ଚାଲୁ',
    h_logo: 'କୋଣରେ ଲୋଗୋ',
    logo_pick: 'ଲୋଗୋ ଯୋଡ଼ନ୍ତୁ',
    logo_remove: 'ଲୋଗୋ ହଟାନ୍ତୁ',
    logo_hint: 'ସ୍ୱଚ୍ଛ ପୃଷ୍ଠଭୂମି ଥିବା PNG ସବୁଠୁ ଭଲ ଦେଖାଯାଏ।',
    logo_corner: 'କୋଣ',
    corner_tl: 'ଉପର ବାମ',
    corner_tr: 'ଉପର ଡାହାଣ',
    corner_bl: 'ତଳ ବାମ',
    corner_br: 'ତଳ ଡାହାଣ',
    logo_size: 'ଲୋଗୋ ସାଇଜ',
    h_sizes: 'ସାଇଜ',
    sizes_hint: 'ସଜାଇବାକୁ ଗୋଟିଏ ସାଇଜ ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ। ଯେଉଁ ସାଇଜ ଡାଉନଲୋଡ୍ କରିବେ, ସେଗୁଡ଼ିକରେ ଟିକ୍ ଦିଅନ୍ତୁ।',
    custom_w: 'ଓସାର (px)',
    custom_h: 'ଉଚ୍ଚତା (px)',
    custom_hint: '16 ରୁ 4096 px ମଧ୍ୟରେ କୌଣସି ସାଇଜ।',
    sel_count: 'ଡାଉନଲୋଡ୍ ପାଇଁ {n}ଟି ସାଇଜରେ ଟିକ୍ ଅଛି',
    sel_all: 'ସବୁଥିରେ ଟିକ୍',
    sel_none: 'ସବୁ ଟିକ୍ ହଟାନ୍ତୁ',
    tick_aria: '{name} ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'ନିଜ ସାଇଜ',
    p_ig_square: 'ପୋଷ୍ଟ (ଚତୁର୍ଭୁଜ)',
    p_ig_portrait: 'ପୋଷ୍ଟ (ଠିଆ)',
    p_ig_landscape: 'ପୋଷ୍ଟ (ଆଡ଼)',
    p_ig_story: 'ଷ୍ଟୋରି ଓ ରିଲ୍ କଭର',
    p_ig_dp: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ',
    p_yt_thumb: 'ଭିଡିଓ ଥମ୍ବନେଲ୍',
    p_yt_shorts: 'Shorts କଭର',
    p_yt_banner: 'ଚ୍ୟାନେଲ୍ ବ୍ୟାନର',
    p_yt_dp: 'ଚ୍ୟାନେଲ୍ ଫଟୋ',
    p_wa_dp: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ (DP)',
    p_wa_status: 'ଷ୍ଟାଟସ୍',
    p_fb_post: 'ପୋଷ୍ଟ (ଆଡ଼)',
    p_fb_square: 'ପୋଷ୍ଟ (ଚତୁର୍ଭୁଜ)',
    p_fb_cover: 'ପେଜ୍ କଭର',
    p_fb_story: 'ଷ୍ଟୋରି',
    p_li_post: 'ପୋଷ୍ଟ',
    p_li_banner: 'ପ୍ରୋଫାଇଲ୍ ବ୍ୟାନର',
    p_x_post: 'ପୋଷ୍ଟ',
    p_x_header: 'ହେଡର',
    p_gb_photo: 'ବ୍ୟବସାୟ ଫଟୋ',
    p_gb_cover: 'କଭର ଫଟୋ',
    p_custom: 'ନିଜ ସାଇଜ',
    h_export: 'ଡାଉନଲୋଡ୍',
    fmt_label: 'ଫର୍ମାଟ୍',
    fmt_hint_jpg: 'JPG: ଛୋଟ ଫାଇଲ୍, ଫଟୋ ପାଇଁ ସର୍ବୋତ୍ତମ।',
    fmt_hint_png: 'PNG: ସ୍ପଷ୍ଟ ଲେଖା ଓ ଲୋଗୋ, ଫାଇଲ୍ ବଡ଼।',
    quality: 'JPG ଗୁଣବତ୍ତା',
    est_size: '{w} × {h} px ରେ ପ୍ରାୟ {kb} KB',
    dl_this: 'ଏହି ସାଇଜ ଡାଉନଲୋଡ୍ କରନ୍ତୁ ({w} × {h})',
    dl_all: 'ଟିକ୍ ଥିବା {n}ଟି ସାଇଜ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    dl_none: 'ପ୍ରଥମେ ଅତି କମରେ ଗୋଟିଏ ସାଇଜରେ ଟିକ୍ ଦିଅନ୍ତୁ।',
    dl_many_hint: 'ଫାଇଲ୍ ଗୋଟିଏ ଗୋଟିଏ କରି ଡାଉନଲୋଡ୍ ହୁଏ। ବ୍ରାଉଜର ଅନେକ ଡାଉନଲୋଡ୍ ପାଇଁ ଅନୁମତି ମାଗିଲେ ହଁ କୁହନ୍ତୁ।',
    dl_done: '{name} ସେଭ୍ ହେଲା ({kb} KB)',
    dl_progress: '{n} ମଧ୍ୟରୁ {i}: {name}',
    dl_all_done: '{n}ଟି ଫାଇଲ୍ ଡାଉନଲୋଡ୍ ହେଲା।',
    share_btn: 'ଏହି ସାଇଜ ସେୟାର୍ କରନ୍ତୁ',
    reset_all: 'ସେଟିଂସ୍ ରିସେଟ୍ କରନ୍ତୁ',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ଆଇଡିଆ',
    tip1: 'ଛବି ବାଛନ୍ତୁ, ଗୋଟିଏ ସାଇଜ ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ, ତା ପରେ ଛବିକୁ ଟାଣି ଜାଗାରେ ରଖନ୍ତୁ। ଦରକାରୀ ଅଂଶ ଉପରେ ଜୁମ୍ କରିବାକୁ ସ୍କ୍ରୋଲ୍ କରନ୍ତୁ କିମ୍ବା ଦୁଇ ଆଙ୍ଗୁଳିରେ ମେଲାନ୍ତୁ। ପ୍ରତ୍ୟେକ ସାଇଜ ନିଜ ଜାଗା ମନେ ରଖେ।',
    tip2: 'ଫିଟ୍ ପୂରା ପୋଷ୍ଟର ରଖେ ଓ ଖାଲି ଜାଗାକୁ ଅସ୍ପଷ୍ଟ ନକଲ କିମ୍ବା ରଙ୍ଗରେ ଭରେ। ଫିଲ୍ ଛବିକୁ ଠିକ୍ ଆକାରରେ କ୍ରପ୍ କରେ। "ସବୁ ସାଇଜରେ ଏହି ଫିଟ୍ / ଫିଲ୍" ଆପଣଙ୍କ ପସନ୍ଦ ସବୁଠାରେ ଲାଗୁ କରେ।',
    tip3: 'ଦୋକାନୀ: ଅଫର ପୋଷ୍ଟର ଥରେ ତିଆରି କରନ୍ତୁ, Instagram ପୋଷ୍ଟ, WhatsApp ଷ୍ଟାଟସ୍ ଓ Facebook କଭରରେ ଟିକ୍ ଦିଅନ୍ତୁ ଏବଂ ସବୁ ଏକାଠି ଡାଉନଲୋଡ୍ କରନ୍ତୁ। କ୍ୟାପସନ୍ ପଟିରେ ଦୋକାନ ନାମ ଲେଖନ୍ତୁ।',
    tip4: 'କ୍ରିଏଟର: Shorts, Reels ଓ ଷ୍ଟାଟସ୍‌ରେ ଲେଖାକୁ ଉପର-ତଳର ଛାଇ ଅଂଶରୁ ବାହାରେ ରଖନ୍ତୁ, ସେଠାରେ ଆପ୍ ବଟନ୍ ଥାଏ। YouTube ବ୍ୟାନରରେ ସବୁକିଛି ଉଜ୍ଜ୍ୱଳ ମଝି ଅଂଶରେ ରଖନ୍ତୁ।',
    tip5: 'ବିଦ୍ୟାଳୟ ଓ ଅଫିସ୍: ଗୋଟିଏ ନୋଟିସ୍ ଫଟୋ ଏକ ମିନିଟରେ WhatsApp DP, YouTube ଥମ୍ବନେଲ୍ ଓ Facebook କଭର ହୋଇଯାଏ। କୋଣରେ ଲୋଗୋ ରଖନ୍ତୁ, ଯାହାଦ୍ୱାରା ପ୍ରତ୍ୟେକ ପୋଷ୍ଟ ଆପଣଙ୍କ ପରିଚୟ ଦେଖାଏ।',
    tip6: 'ଲେଖା ଓ ଲୋଗୋ ଥିବା ପୋଷ୍ଟର ପାଇଁ PNG ବାଛନ୍ତୁ। ଫଟୋ ପାଇଁ JPG ଗୁଣବତ୍ତା 85–92 ରଖନ୍ତୁ: ଫାଇଲ୍ ଛୋଟ ରହେ ଓ ଧୀର ନେଟୱର୍କରେ ବି ଶୀଘ୍ର ଅପଲୋଡ୍ ହୁଏ।',
    sample_shop: 'ଶର୍ମା ସ୍ୱିଟ୍ସ',
    sample_offer: 'ଦୀପାବଳି ସ୍ପେଶାଲ୍ · ପ୍ରତି ସକାଳ ତାଜା',
    sample_off: '20% ରିହାତି'
  },
  ta: {
    app_title: 'சோஷியல் போஸ்ட் ரீசைசர்',
    intro: 'ஒரு புகைப்படம் அல்லது போஸ்டரை Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X மற்றும் Google Business-க்கான சரியான அளவுக்கு மாற்றுங்கள்: இழுத்து இடத்தில் வைக்க, ஜூம் செய்ய, பிறகு ஒவ்வொரு அளவையும் பதிவிறக்க.',
    privacy_head: 'உங்கள் புகைப்படங்கள் இந்தச் சாதனத்தை விட்டு வெளியே போகவே இல்லை.',
    privacy_body: 'அளவு மாற்றும் வேலை உங்கள் பிரவுசருக்குள்ளேயே நடக்கிறது. எதுவும் பதிவேற்றப்படாது, எதுவும் ஆன்லைனில் சேமிக்கப்படாது.',
    drop_title: 'புகைப்படம் அல்லது போஸ்டரைத் தேர்வு செய்க',
    drop_hint: 'JPG, PNG, WebP அல்லது GIF · இங்கே இழுத்து விடுங்கள், அல்லது ஒட்டுங்கள் (Ctrl+V)',
    pick_btn: 'படத்தைத் தேர்வு செய்',
    sample_btn: 'மாதிரியைப் பார்க்க',
    loaded_sample: 'மாதிரி போஸ்டர் திறந்துள்ளது. தொடங்க உங்கள் படத்தைத் தேர்வு செய்யுங்கள்.',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'பெரிய புகைப்படம் வேகமான வேலைக்காக {w} × {h} px-க்குச் சிறிதாக்கப்பட்டது.',
    picture: 'படம்',
    err_open: 'இந்தக் கோப்பைப் படமாகத் திறக்க முடியவில்லை. JPG அல்லது PNG முயற்சிக்கவும்.',
    err_heic: 'HEIC புகைப்படங்கள் (iPhone) இங்கே திறக்காது. போனிலிருந்து புகைப்படத்தை JPG ஆகப் பகிரவும், அல்லது எங்கள் Image Compressor மூலம் மாற்றவும்.',
    err_heic_link: 'Image Compressor-ஐத் திறக்க',
    too_big: 'இந்தக் கோப்பு மிகப் பெரியது. 80 MB-க்குக் குறைவான புகைப்படத்தை முயற்சிக்கவும்.',
    err_export: 'படத்தைச் சேமிக்க முடியவில்லை. சிறிய அளவு அல்லது PNG முயற்சிக்கவும்.',
    h_adjust: 'சரிசெய்க',
    stage_aria: 'படத்தின் முன்னோட்டம். நகர்த்த இழுக்கவும், ஜூம் செய்ய மவுஸ் வீல் அல்லது இரு விரல்களைப் பயன்படுத்தவும்.',
    drag_hint: 'படத்தை நகர்த்த இழுக்கவும் · ஜூம் செய்ய ஸ்க்ரோல் செய்யவும் அல்லது இரு விரல்களால் விரிக்கவும்',
    keys_hint: 'கீபோர்டு: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> நகர்த்து · <kbd>+</kbd> <kbd>−</kbd> ஜூம் · <kbd>0</kbd> மீட்டமை · <kbd>F</kbd> ஃபிட் / ஃபில்',
    mode_label: 'ஃபிட் அல்லது ஃபில்',
    mode_fit: 'ஃபிட் (முழுப் படம்)',
    mode_fill: 'ஃபில் (அளவுக்கு வெட்டு)',
    zoom: 'ஜூம்',
    center_btn: 'இடத்தையும் ஜூமையும் மீட்டமை',
    bg_label: 'பின்னணி (படம் முழு சட்டத்தையும் நிரப்பாதபோது)',
    bg_blur: 'மங்கலான புகைப்படம்',
    bg_auto: 'தானியங்கி நிறம்',
    bg_white: 'வெள்ளை',
    bg_black: 'கருப்பு',
    bg_custom: 'நிறத்தைத் தேர்வு செய்',
    safe_show: 'பாதுகாப்பான பகுதியைக் காட்டு',
    apply_all: 'எல்லா அளவுகளுக்கும் இந்த ஃபிட் / ஃபில்',
    applied_all: 'எல்லா அளவுகளுக்கும் பொருத்தப்பட்டது.',
    safe_hint_bands: 'பெயர்களையும் விலைகளையும் மேலும் கீழும் உள்ள நிழல் பகுதிக்கு வெளியே வைக்கவும்: ஆப் பட்டன்களும் கேப்ஷன்களும் அங்கே வரும்.',
    safe_hint_rect: 'எல்லா சாதனங்களிலும் (TV, கணினி, போன்) பிரகாசமான பகுதி மட்டுமே தெரியும்.',
    safe_hint_circle: 'இந்தப் படம் வட்டமாகக் காட்டப்படும்: நிழல் மூலைகள் வெட்டப்படும்.',
    safe_hint_avoid: 'நிழல் மூலையை வீடியோ நீளம் அல்லது சுயவிவரப் படம் மறைக்கும்.',
    h_caption: 'கேப்ஷன் பட்டை',
    caption_on: 'கேப்ஷன் பட்டையைச் சேர்',
    caption_text: 'கேப்ஷன் உரை',
    caption_ph: 'எ.கா. சர்மா ஸ்வீட்ஸ் · தீபாவளி சலுகை · 20% தள்ளுபடி',
    caption_pos: 'இடம்',
    pos_top: 'மேலே',
    pos_bottom: 'கீழே',
    caption_style: 'ஸ்டைல்',
    style_dark: 'அடர்',
    style_light: 'வெளிர்',
    style_brand: 'தேர்ந்த நிறம்',
    on_badge: 'இயக்கத்தில்',
    h_logo: 'மூலையில் லோகோ',
    logo_pick: 'லோகோ சேர்',
    logo_remove: 'லோகோவை நீக்கு',
    logo_hint: 'ஒளிபுகும் பின்னணியுடன் PNG சிறப்பாகத் தெரியும்.',
    logo_corner: 'மூலை',
    corner_tl: 'மேல் இடது',
    corner_tr: 'மேல் வலது',
    corner_bl: 'கீழ் இடது',
    corner_br: 'கீழ் வலது',
    logo_size: 'லோகோ அளவு',
    h_sizes: 'அளவுகள்',
    sizes_hint: 'சரிசெய்ய ஒரு அளவைத் தட்டுங்கள். பதிவிறக்க வேண்டிய அளவுகளுக்குத் டிக் செய்யுங்கள்.',
    custom_w: 'அகலம் (px)',
    custom_h: 'உயரம் (px)',
    custom_hint: '16 முதல் 4096 px வரை எந்த அளவும்.',
    sel_count: 'பதிவிறக்கத்திற்கு {n} அளவுகள் டிக் செய்யப்பட்டுள்ளன',
    sel_all: 'எல்லாவற்றையும் டிக் செய்',
    sel_none: 'எல்லா டிக்கையும் நீக்கு',
    tick_aria: '{name} பதிவிறக்கு',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'சொந்த அளவு',
    p_ig_square: 'போஸ்ட் (சதுரம்)',
    p_ig_portrait: 'போஸ்ட் (நெட்டு)',
    p_ig_landscape: 'போஸ்ட் (படுக்கை)',
    p_ig_story: 'ஸ்டோரி & ரீல் கவர்',
    p_ig_dp: 'சுயவிவரப் படம்',
    p_yt_thumb: 'வீடியோ தம்ப்நெயில்',
    p_yt_shorts: 'Shorts கவர்',
    p_yt_banner: 'சேனல் பேனர்',
    p_yt_dp: 'சேனல் படம்',
    p_wa_dp: 'சுயவிவரப் படம் (DP)',
    p_wa_status: 'ஸ்டேட்டஸ்',
    p_fb_post: 'போஸ்ட் (படுக்கை)',
    p_fb_square: 'போஸ்ட் (சதுரம்)',
    p_fb_cover: 'பேஜ் கவர்',
    p_fb_story: 'ஸ்டோரி',
    p_li_post: 'போஸ்ட்',
    p_li_banner: 'சுயவிவர பேனர்',
    p_x_post: 'போஸ்ட்',
    p_x_header: 'ஹெடர்',
    p_gb_photo: 'வணிகப் படம்',
    p_gb_cover: 'கவர் படம்',
    p_custom: 'சொந்த அளவு',
    h_export: 'பதிவிறக்கம்',
    fmt_label: 'வடிவம்',
    fmt_hint_jpg: 'JPG: சிறிய கோப்புகள், புகைப்படங்களுக்குச் சிறந்தது.',
    fmt_hint_png: 'PNG: தெளிவான உரை, லோகோ; கோப்புகள் பெரியவை.',
    quality: 'JPG தரம்',
    est_size: '{w} × {h} px-இல் சுமார் {kb} KB',
    dl_this: 'இந்த அளவைப் பதிவிறக்கு ({w} × {h})',
    dl_all: 'டிக் செய்த {n} அளவுகளைப் பதிவிறக்கு',
    dl_none: 'முதலில் குறைந்தது ஒரு அளவைத் டிக் செய்யுங்கள்.',
    dl_many_hint: 'கோப்புகள் ஒன்றன் பின் ஒன்றாகப் பதிவிறங்கும். பல பதிவிறக்கங்களுக்கு பிரவுசர் அனுமதி கேட்டால் ஆம் என்று சொல்லுங்கள்.',
    dl_done: '{name} சேமிக்கப்பட்டது ({kb} KB)',
    dl_progress: '{n}-இல் {i}: {name}',
    dl_all_done: '{n} கோப்புகள் பதிவிறக்கப்பட்டன.',
    share_btn: 'இந்த அளவைப் பகிர்',
    reset_all: 'அமைப்புகளை மீட்டமை',
    help_title: 'பயன்படுத்துவது எப்படி / யோசனைகள்',
    tip1: 'படத்தைத் தேர்வு செய்து, ஒரு அளவைத் தட்டி, பிறகு படத்தை இழுத்து இடத்தில் வைக்கவும். முக்கியமான பகுதியை ஜூம் செய்ய ஸ்க்ரோல் செய்யவும் அல்லது இரு விரல்களால் விரிக்கவும். ஒவ்வொரு அளவும் தன் இடத்தை நினைவில் வைக்கும்.',
    tip2: 'ஃபிட் முழு போஸ்டரையும் வைத்து, காலி இடத்தை மங்கலான நகல் அல்லது நிறத்தால் நிரப்பும். ஃபில் படத்தைச் சரியான வடிவத்திற்கு வெட்டும். "எல்லா அளவுகளுக்கும் இந்த ஃபிட் / ஃபில்" உங்கள் தேர்வை எல்லா இடத்திலும் பொருத்தும்.',
    tip3: 'கடைக்காரர்கள்: சலுகை போஸ்டரை ஒரு முறை உருவாக்கி, Instagram போஸ்ட், WhatsApp ஸ்டேட்டஸ், Facebook கவரைத் டிக் செய்து ஒன்றாகப் பதிவிறக்குங்கள். கேப்ஷன் பட்டையில் கடையின் பெயரைச் சேர்க்கவும்.',
    tip4: 'கிரியேட்டர்கள்: Shorts, Reels, ஸ்டேட்டஸில் உரையை மேலும் கீழும் உள்ள நிழல் பகுதிக்கு வெளியே வைக்கவும்; அங்கே ஆப் பட்டன்கள் இருக்கும். YouTube பேனரில் எல்லாவற்றையும் பிரகாசமான நடுப்பகுதிக்குள் வைக்கவும்.',
    tip5: 'பள்ளிகள், அலுவலகங்கள்: ஒரு அறிவிப்புப் படம் ஒரு நிமிடத்தில் WhatsApp DP, YouTube தம்ப்நெயில், Facebook கவர் ஆகும். ஒவ்வொரு போஸ்டும் உங்களுடையதாகத் தெரிய மூலையில் லோகோவை வைக்கவும்.',
    tip6: 'உரையும் லோகோவும் உள்ள போஸ்டர்களுக்கு PNG பயன்படுத்தவும். புகைப்படங்களுக்கு JPG தரம் 85–92: கோப்புகள் சிறியதாக இருக்கும், மெதுவான நெட்வொர்க்கிலும் வேகமாகப் பதிவேறும்.',
    sample_shop: 'சர்மா ஸ்வீட்ஸ்',
    sample_offer: 'தீபாவளி ஸ்பெஷல் · தினமும் காலையில் புதிது',
    sample_off: '20% தள்ளுபடி'
  },
  te: {
    app_title: 'సోషల్ పోస్ట్ రీసైజర్',
    intro: 'ఒక ఫోటో లేదా పోస్టర్‌ను Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X మరియు Google Business కోసం సరైన సైజులోకి మార్చండి: లాగి సరైన చోట పెట్టండి, జూమ్ చేయండి, తర్వాత ప్రతి సైజును డౌన్‌లోడ్ చేయండి.',
    privacy_head: 'మీ ఫోటోలు ఎప్పుడూ ఈ పరికరం దాటి బయటకు వెళ్లవు.',
    privacy_body: 'సైజు మార్చే పని మీ బ్రౌజర్ లోపలే జరుగుతుంది. ఏదీ అప్‌లోడ్ అవదు, ఏదీ ఆన్‌లైన్‌లో సేవ్ అవదు.',
    drop_title: 'ఫోటో లేదా పోస్టర్ ఎంచుకోండి',
    drop_hint: 'JPG, PNG, WebP లేదా GIF · ఇక్కడ లాగి వదలండి, లేదా పేస్ట్ చేయండి (Ctrl+V)',
    pick_btn: 'చిత్రం ఎంచుకోండి',
    sample_btn: 'నమూనా చూడండి',
    loaded_sample: 'నమూనా పోస్టర్ తెరిచి ఉంది. మొదలుపెట్టడానికి మీ చిత్రం ఎంచుకోండి.',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'పెద్ద ఫోటోను వేగంగా పని చేయడానికి {w} × {h} px కి చిన్నది చేశాం.',
    picture: 'చిత్రం',
    err_open: 'ఈ ఫైల్ చిత్రంగా తెరవలేకపోయాం. JPG లేదా PNG ప్రయత్నించండి.',
    err_heic: 'HEIC ఫోటోలు (iPhone) ఇక్కడ తెరుచుకోవు. ఫోన్ నుంచి ఫోటోను JPG గా షేర్ చేయండి, లేదా మా Image Compressor తో మార్చండి.',
    err_heic_link: 'Image Compressor తెరవండి',
    too_big: 'ఈ ఫైల్ చాలా పెద్దది. 80 MB కంటే చిన్న ఫోటో ప్రయత్నించండి.',
    err_export: 'చిత్రం సేవ్ చేయలేకపోయాం. చిన్న సైజు లేదా PNG ప్రయత్నించండి.',
    h_adjust: 'సర్దండి',
    stage_aria: 'చిత్రం ప్రివ్యూ. కదిలించడానికి లాగండి, జూమ్ కోసం మౌస్ వీల్ లేదా రెండు వేళ్లు వాడండి.',
    drag_hint: 'చిత్రం కదిలించడానికి లాగండి · జూమ్ కోసం స్క్రోల్ చేయండి లేదా రెండు వేళ్లతో విస్తరించండి',
    keys_hint: 'కీబోర్డ్: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> కదిలించు · <kbd>+</kbd> <kbd>−</kbd> జూమ్ · <kbd>0</kbd> రీసెట్ · <kbd>F</kbd> ఫిట్ / ఫిల్',
    mode_label: 'ఫిట్ లేదా ఫిల్',
    mode_fit: 'ఫిట్ (పూర్తి చిత్రం)',
    mode_fill: 'ఫిల్ (సైజుకు క్రాప్)',
    zoom: 'జూమ్',
    center_btn: 'స్థానం, జూమ్ రీసెట్ చేయండి',
    bg_label: 'బ్యాక్‌గ్రౌండ్ (చిత్రం ఫ్రేమ్ పూర్తిగా నిండనప్పుడు)',
    bg_blur: 'మసక ఫోటో',
    bg_auto: 'ఆటో రంగు',
    bg_white: 'తెలుపు',
    bg_black: 'నలుపు',
    bg_custom: 'రంగు ఎంచుకోండి',
    safe_show: 'సురక్షిత భాగం చూపించు',
    apply_all: 'అన్ని సైజులకూ ఇదే ఫిట్ / ఫిల్',
    applied_all: 'అన్ని సైజులకూ వర్తించింది.',
    safe_hint_bands: 'పేర్లు, ధరలను పైన-కింద నీడ భాగాల బయట ఉంచండి: అక్కడ యాప్ బటన్లు, క్యాప్షన్లు వస్తాయి.',
    safe_hint_rect: 'ప్రతి పరికరంలో (TV, కంప్యూటర్, ఫోన్) ప్రకాశవంతమైన భాగం మాత్రమే కనిపిస్తుంది.',
    safe_hint_circle: 'ఈ చిత్రం గుండ్రంగా కనిపిస్తుంది: నీడ మూలలు కత్తిరించబడతాయి.',
    safe_hint_avoid: 'నీడ మూలను వీడియో నిడివి లేదా ప్రొఫైల్ ఫోటో కప్పేస్తుంది.',
    h_caption: 'క్యాప్షన్ పట్టీ',
    caption_on: 'క్యాప్షన్ పట్టీ జోడించు',
    caption_text: 'క్యాప్షన్ టెక్స్ట్',
    caption_ph: 'ఉదా. శర్మ స్వీట్స్ · దీపావళి ఆఫర్ · 20% తగ్గింపు',
    caption_pos: 'స్థానం',
    pos_top: 'పైన',
    pos_bottom: 'కింద',
    caption_style: 'స్టైల్',
    style_dark: 'ముదురు',
    style_light: 'లేత',
    style_brand: 'ఎంచుకున్న రంగు',
    on_badge: 'ఆన్',
    h_logo: 'మూలలో లోగో',
    logo_pick: 'లోగో జోడించు',
    logo_remove: 'లోగో తీసివేయి',
    logo_hint: 'పారదర్శక బ్యాక్‌గ్రౌండ్ ఉన్న PNG బాగా కనిపిస్తుంది.',
    logo_corner: 'మూల',
    corner_tl: 'పై ఎడమ',
    corner_tr: 'పై కుడి',
    corner_bl: 'కింద ఎడమ',
    corner_br: 'కింద కుడి',
    logo_size: 'లోగో సైజు',
    h_sizes: 'సైజులు',
    sizes_hint: 'సర్దడానికి ఒక సైజును తాకండి. డౌన్‌లోడ్ చేయాల్సిన సైజులకు టిక్ పెట్టండి.',
    custom_w: 'వెడల్పు (px)',
    custom_h: 'ఎత్తు (px)',
    custom_hint: '16 నుంచి 4096 px వరకు ఏ సైజైనా.',
    sel_count: 'డౌన్‌లోడ్ కోసం {n} సైజులకు టిక్ ఉంది',
    sel_all: 'అన్నింటికీ టిక్',
    sel_none: 'అన్ని టిక్‌లు తీసేయి',
    tick_aria: '{name} డౌన్‌లోడ్ చేయండి',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'సొంత సైజు',
    p_ig_square: 'పోస్ట్ (చతురస్రం)',
    p_ig_portrait: 'పోస్ట్ (నిలువు)',
    p_ig_landscape: 'పోస్ట్ (అడ్డం)',
    p_ig_story: 'స్టోరీ & రీల్ కవర్',
    p_ig_dp: 'ప్రొఫైల్ ఫోటో',
    p_yt_thumb: 'వీడియో థంబ్‌నెయిల్',
    p_yt_shorts: 'Shorts కవర్',
    p_yt_banner: 'ఛానల్ బ్యానర్',
    p_yt_dp: 'ఛానల్ ఫోటో',
    p_wa_dp: 'ప్రొఫైల్ ఫోటో (DP)',
    p_wa_status: 'స్టేటస్',
    p_fb_post: 'పోస్ట్ (అడ్డం)',
    p_fb_square: 'పోస్ట్ (చతురస్రం)',
    p_fb_cover: 'పేజీ కవర్',
    p_fb_story: 'స్టోరీ',
    p_li_post: 'పోస్ట్',
    p_li_banner: 'ప్రొఫైల్ బ్యానర్',
    p_x_post: 'పోస్ట్',
    p_x_header: 'హెడర్',
    p_gb_photo: 'బిజినెస్ ఫోటో',
    p_gb_cover: 'కవర్ ఫోటో',
    p_custom: 'సొంత సైజు',
    h_export: 'డౌన్‌లోడ్',
    fmt_label: 'ఫార్మాట్',
    fmt_hint_jpg: 'JPG: చిన్న ఫైళ్లు, ఫోటోలకు ఉత్తమం.',
    fmt_hint_png: 'PNG: స్పష్టమైన టెక్స్ట్, లోగోలు; ఫైళ్లు పెద్దవి.',
    quality: 'JPG క్వాలిటీ',
    est_size: '{w} × {h} px లో సుమారు {kb} KB',
    dl_this: 'ఈ సైజు డౌన్‌లోడ్ చేయండి ({w} × {h})',
    dl_all: 'టిక్ పెట్టిన {n} సైజులు డౌన్‌లోడ్ చేయండి',
    dl_none: 'ముందుగా కనీసం ఒక సైజుకు టిక్ పెట్టండి.',
    dl_many_hint: 'ఫైళ్లు ఒకదాని తర్వాత ఒకటి డౌన్‌లోడ్ అవుతాయి. బ్రౌజర్ ఎక్కువ డౌన్‌లోడ్‌లకు అనుమతి అడిగితే అవును అనండి.',
    dl_done: '{name} సేవ్ అయింది ({kb} KB)',
    dl_progress: '{n} లో {i}: {name}',
    dl_all_done: '{n} ఫైళ్లు డౌన్‌లోడ్ అయ్యాయి.',
    share_btn: 'ఈ సైజు షేర్ చేయండి',
    reset_all: 'సెట్టింగ్‌లు రీసెట్ చేయండి',
    help_title: 'ఎలా ఉపయోగించాలి / ఆలోచనలు',
    tip1: 'చిత్రం ఎంచుకోండి, ఒక సైజును తాకండి, తర్వాత చిత్రాన్ని లాగి సరైన చోట పెట్టండి. ముఖ్యమైన భాగంపై జూమ్ చేయడానికి స్క్రోల్ చేయండి లేదా రెండు వేళ్లతో విస్తరించండి. ప్రతి సైజు తన స్థానాన్ని గుర్తుంచుకుంటుంది.',
    tip2: 'ఫిట్ పూర్తి పోస్టర్‌ను ఉంచి, ఖాళీ స్థలాన్ని మసక కాపీ లేదా రంగుతో నింపుతుంది. ఫిల్ చిత్రాన్ని సరైన ఆకారానికి క్రాప్ చేస్తుంది. "అన్ని సైజులకూ ఇదే ఫిట్ / ఫిల్" మీ ఎంపికను అన్నింటికీ వర్తింపజేస్తుంది.',
    tip3: 'దుకాణదారులు: ఆఫర్ పోస్టర్ ఒకసారి తయారు చేసి, Instagram పోస్ట్, WhatsApp స్టేటస్, Facebook కవర్‌కు టిక్ పెట్టి, అన్నీ కలిపి డౌన్‌లోడ్ చేయండి. క్యాప్షన్ పట్టీలో దుకాణం పేరు పెట్టండి.',
    tip4: 'క్రియేటర్లు: Shorts, Reels, స్టేటస్‌లో టెక్స్ట్‌ను పైన-కింద నీడ భాగాల బయట ఉంచండి; అక్కడ యాప్ బటన్లు ఉంటాయి. YouTube బ్యానర్‌లో అన్నీ ప్రకాశవంతమైన మధ్య భాగంలోనే ఉంచండి.',
    tip5: 'పాఠశాలలు, కార్యాలయాలు: ఒక నోటీసు ఫోటో ఒక నిమిషంలో WhatsApp DP, YouTube థంబ్‌నెయిల్, Facebook కవర్ అవుతుంది. ప్రతి పోస్ట్ మీదిగా కనిపించేలా మూలలో లోగో పెట్టండి.',
    tip6: 'టెక్స్ట్, లోగో ఉన్న పోస్టర్లకు PNG వాడండి. ఫోటోలకు JPG క్వాలిటీ 85–92 ఉంచండి: ఫైళ్లు చిన్నగా ఉంటాయి, నెమ్మదైన నెట్‌వర్క్‌లోనూ త్వరగా అప్‌లోడ్ అవుతాయి.',
    sample_shop: 'శర్మ స్వీట్స్',
    sample_offer: 'దీపావళి స్పెషల్ · ప్రతి ఉదయం తాజాగా',
    sample_off: '20% తగ్గింపు'
  },
  kn: {
    app_title: 'ಸೋಶಿಯಲ್ ಪೋಸ್ಟ್ ರೀಸೈಜರ್',
    intro: 'ಒಂದು ಫೋಟೋ ಅಥವಾ ಪೋಸ್ಟರ್‌ನ್ನು Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X ಮತ್ತು Google Business ಗೆ ಸರಿಯಾದ ಗಾತ್ರಕ್ಕೆ ಬದಲಿಸಿ: ಎಳೆದು ಸರಿಯಾದ ಜಾಗದಲ್ಲಿ ಇರಿಸಿ, ಜೂಮ್ ಮಾಡಿ, ನಂತರ ಪ್ರತಿ ಗಾತ್ರವನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    privacy_head: 'ನಿಮ್ಮ ಫೋಟೋಗಳು ಈ ಸಾಧನದಿಂದ ಹೊರಗೆ ಹೋಗುವುದೇ ಇಲ್ಲ.',
    privacy_body: 'ಗಾತ್ರ ಬದಲಿಸುವ ಕೆಲಸ ನಿಮ್ಮ ಬ್ರೌಸರ್ ಒಳಗೇ ನಡೆಯುತ್ತದೆ. ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ, ಏನೂ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿಯುವುದಿಲ್ಲ.',
    drop_title: 'ಫೋಟೋ ಅಥವಾ ಪೋಸ್ಟರ್ ಆರಿಸಿ',
    drop_hint: 'JPG, PNG, WebP ಅಥವಾ GIF · ಇಲ್ಲಿ ಎಳೆದು ಬಿಡಿ, ಅಥವಾ ಪೇಸ್ಟ್ ಮಾಡಿ (Ctrl+V)',
    pick_btn: 'ಚಿತ್ರ ಆರಿಸಿ',
    sample_btn: 'ಮಾದರಿ ನೋಡಿ',
    loaded_sample: 'ಮಾದರಿ ಪೋಸ್ಟರ್ ತೆರೆದಿದೆ. ಆರಂಭಿಸಲು ನಿಮ್ಮ ಚಿತ್ರ ಆರಿಸಿ.',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'ದೊಡ್ಡ ಫೋಟೋವನ್ನು ವೇಗದ ಕೆಲಸಕ್ಕಾಗಿ {w} × {h} px ಗೆ ಚಿಕ್ಕದಾಗಿಸಲಾಗಿದೆ.',
    picture: 'ಚಿತ್ರ',
    err_open: 'ಈ ಫೈಲ್ ಚಿತ್ರವಾಗಿ ತೆರೆಯಲಾಗಲಿಲ್ಲ. JPG ಅಥವಾ PNG ಪ್ರಯತ್ನಿಸಿ.',
    err_heic: 'HEIC ಫೋಟೋಗಳು (iPhone) ಇಲ್ಲಿ ತೆರೆಯುವುದಿಲ್ಲ. ಫೋನ್‌ನಿಂದ ಫೋಟೋವನ್ನು JPG ಆಗಿ ಹಂಚಿಕೊಳ್ಳಿ, ಅಥವಾ ನಮ್ಮ Image Compressor ನಿಂದ ಬದಲಿಸಿ.',
    err_heic_link: 'Image Compressor ತೆರೆಯಿರಿ',
    too_big: 'ಈ ಫೈಲ್ ತುಂಬಾ ದೊಡ್ಡದು. 80 MB ಗಿಂತ ಚಿಕ್ಕ ಫೋಟೋ ಪ್ರಯತ್ನಿಸಿ.',
    err_export: 'ಚಿತ್ರ ಉಳಿಸಲಾಗಲಿಲ್ಲ. ಚಿಕ್ಕ ಗಾತ್ರ ಅಥವಾ PNG ಪ್ರಯತ್ನಿಸಿ.',
    h_adjust: 'ಹೊಂದಿಸಿ',
    stage_aria: 'ಚಿತ್ರದ ಮುನ್ನೋಟ. ಸರಿಸಲು ಎಳೆಯಿರಿ, ಜೂಮ್‌ಗೆ ಮೌಸ್ ವೀಲ್ ಅಥವಾ ಎರಡು ಬೆರಳು ಬಳಸಿ.',
    drag_hint: 'ಚಿತ್ರ ಸರಿಸಲು ಎಳೆಯಿರಿ · ಜೂಮ್‌ಗೆ ಸ್ಕ್ರಾಲ್ ಮಾಡಿ ಅಥವಾ ಎರಡು ಬೆರಳಿನಿಂದ ಹಿಗ್ಗಿಸಿ',
    keys_hint: 'ಕೀಬೋರ್ಡ್: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> ಸರಿಸಿ · <kbd>+</kbd> <kbd>−</kbd> ಜೂಮ್ · <kbd>0</kbd> ಮರುಹೊಂದಿಸಿ · <kbd>F</kbd> ಫಿಟ್ / ಫಿಲ್',
    mode_label: 'ಫಿಟ್ ಅಥವಾ ಫಿಲ್',
    mode_fit: 'ಫಿಟ್ (ಪೂರ್ಣ ಚಿತ್ರ)',
    mode_fill: 'ಫಿಲ್ (ಗಾತ್ರಕ್ಕೆ ಕ್ರಾಪ್)',
    zoom: 'ಜೂಮ್',
    center_btn: 'ಸ್ಥಾನ ಮತ್ತು ಜೂಮ್ ಮರುಹೊಂದಿಸಿ',
    bg_label: 'ಹಿನ್ನೆಲೆ (ಚಿತ್ರ ಪೂರ್ಣ ಫ್ರೇಮ್ ತುಂಬದಿದ್ದಾಗ)',
    bg_blur: 'ಮಬ್ಬು ಫೋಟೋ',
    bg_auto: 'ತಾನಾಗಿ ಬಣ್ಣ',
    bg_white: 'ಬಿಳಿ',
    bg_black: 'ಕಪ್ಪು',
    bg_custom: 'ಬಣ್ಣ ಆರಿಸಿ',
    safe_show: 'ಸುರಕ್ಷಿತ ಭಾಗ ತೋರಿಸಿ',
    apply_all: 'ಎಲ್ಲಾ ಗಾತ್ರಗಳಿಗೂ ಇದೇ ಫಿಟ್ / ಫಿಲ್',
    applied_all: 'ಎಲ್ಲಾ ಗಾತ್ರಗಳಿಗೂ ಅನ್ವಯವಾಯಿತು.',
    safe_hint_bands: 'ಹೆಸರು ಮತ್ತು ಬೆಲೆಗಳನ್ನು ಮೇಲೆ-ಕೆಳಗಿನ ನೆರಳು ಭಾಗದಿಂದ ಹೊರಗಿಡಿ: ಅಲ್ಲಿ ಆ್ಯಪ್ ಬಟನ್‌ಗಳು ಮತ್ತು ಕ್ಯಾಪ್ಶನ್ ಬರುತ್ತವೆ.',
    safe_hint_rect: 'ಪ್ರತಿ ಸಾಧನದಲ್ಲಿ (TV, ಕಂಪ್ಯೂಟರ್ ಮತ್ತು ಫೋನ್) ಪ್ರಕಾಶಮಾನ ಭಾಗ ಮಾತ್ರ ಕಾಣುತ್ತದೆ.',
    safe_hint_circle: 'ಈ ಚಿತ್ರ ವೃತ್ತಾಕಾರವಾಗಿ ಕಾಣುತ್ತದೆ: ನೆರಳು ಮೂಲೆಗಳು ಕತ್ತರಿಸಿಹೋಗುತ್ತವೆ.',
    safe_hint_avoid: 'ನೆರಳು ಮೂಲೆಯನ್ನು ವೀಡಿಯೊ ಅವಧಿ ಅಥವಾ ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಮುಚ್ಚುತ್ತದೆ.',
    h_caption: 'ಕ್ಯಾಪ್ಶನ್ ಪಟ್ಟಿ',
    caption_on: 'ಕ್ಯಾಪ್ಶನ್ ಪಟ್ಟಿ ಸೇರಿಸಿ',
    caption_text: 'ಕ್ಯಾಪ್ಶನ್ ಪಠ್ಯ',
    caption_ph: 'ಉದಾ. ಶರ್ಮಾ ಸ್ವೀಟ್ಸ್ · ದೀಪಾವಳಿ ಆಫರ್ · 20% ರಿಯಾಯಿತಿ',
    caption_pos: 'ಸ್ಥಾನ',
    pos_top: 'ಮೇಲೆ',
    pos_bottom: 'ಕೆಳಗೆ',
    caption_style: 'ಶೈಲಿ',
    style_dark: 'ಗಾಢ',
    style_light: 'ತಿಳಿ',
    style_brand: 'ಆರಿಸಿದ ಬಣ್ಣ',
    on_badge: 'ಆನ್',
    h_logo: 'ಮೂಲೆಯಲ್ಲಿ ಲೋಗೋ',
    logo_pick: 'ಲೋಗೋ ಸೇರಿಸಿ',
    logo_remove: 'ಲೋಗೋ ತೆಗೆಯಿರಿ',
    logo_hint: 'ಪಾರದರ್ಶಕ ಹಿನ್ನೆಲೆಯ PNG ಅತ್ಯುತ್ತಮವಾಗಿ ಕಾಣುತ್ತದೆ.',
    logo_corner: 'ಮೂಲೆ',
    corner_tl: 'ಮೇಲೆ ಎಡ',
    corner_tr: 'ಮೇಲೆ ಬಲ',
    corner_bl: 'ಕೆಳಗೆ ಎಡ',
    corner_br: 'ಕೆಳಗೆ ಬಲ',
    logo_size: 'ಲೋಗೋ ಗಾತ್ರ',
    h_sizes: 'ಗಾತ್ರಗಳು',
    sizes_hint: 'ಹೊಂದಿಸಲು ಒಂದು ಗಾತ್ರ ತಟ್ಟಿ. ಡೌನ್‌ಲೋಡ್ ಮಾಡಬೇಕಾದ ಗಾತ್ರಗಳಿಗೆ ಟಿಕ್ ಹಾಕಿ.',
    custom_w: 'ಅಗಲ (px)',
    custom_h: 'ಎತ್ತರ (px)',
    custom_hint: '16 ರಿಂದ 4096 px ವರೆಗೆ ಯಾವುದೇ ಗಾತ್ರ.',
    sel_count: 'ಡೌನ್‌ಲೋಡ್‌ಗೆ {n} ಗಾತ್ರಗಳಿಗೆ ಟಿಕ್ ಇದೆ',
    sel_all: 'ಎಲ್ಲಕ್ಕೂ ಟಿಕ್',
    sel_none: 'ಎಲ್ಲಾ ಟಿಕ್ ತೆಗೆಯಿರಿ',
    tick_aria: '{name} ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'ಸ್ವಂತ ಗಾತ್ರ',
    p_ig_square: 'ಪೋಸ್ಟ್ (ಚೌಕ)',
    p_ig_portrait: 'ಪೋಸ್ಟ್ (ಲಂಬ)',
    p_ig_landscape: 'ಪೋಸ್ಟ್ (ಅಡ್ಡ)',
    p_ig_story: 'ಸ್ಟೋರಿ ಮತ್ತು ರೀಲ್ ಕವರ್',
    p_ig_dp: 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ',
    p_yt_thumb: 'ವೀಡಿಯೊ ಥಂಬ್‌ನೇಲ್',
    p_yt_shorts: 'Shorts ಕವರ್',
    p_yt_banner: 'ಚಾನೆಲ್ ಬ್ಯಾನರ್',
    p_yt_dp: 'ಚಾನೆಲ್ ಫೋಟೋ',
    p_wa_dp: 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ (DP)',
    p_wa_status: 'ಸ್ಟೇಟಸ್',
    p_fb_post: 'ಪೋಸ್ಟ್ (ಅಡ್ಡ)',
    p_fb_square: 'ಪೋಸ್ಟ್ (ಚೌಕ)',
    p_fb_cover: 'ಪೇಜ್ ಕವರ್',
    p_fb_story: 'ಸ್ಟೋರಿ',
    p_li_post: 'ಪೋಸ್ಟ್',
    p_li_banner: 'ಪ್ರೊಫೈಲ್ ಬ್ಯಾನರ್',
    p_x_post: 'ಪೋಸ್ಟ್',
    p_x_header: 'ಹೆಡರ್',
    p_gb_photo: 'ಬಿಸಿನೆಸ್ ಫೋಟೋ',
    p_gb_cover: 'ಕವರ್ ಫೋಟೋ',
    p_custom: 'ಸ್ವಂತ ಗಾತ್ರ',
    h_export: 'ಡೌನ್‌ಲೋಡ್',
    fmt_label: 'ಫಾರ್ಮ್ಯಾಟ್',
    fmt_hint_jpg: 'JPG: ಚಿಕ್ಕ ಫೈಲ್‌ಗಳು, ಫೋಟೋಗಳಿಗೆ ಉತ್ತಮ.',
    fmt_hint_png: 'PNG: ಸ್ಪಷ್ಟ ಪಠ್ಯ ಮತ್ತು ಲೋಗೋ, ಫೈಲ್‌ಗಳು ದೊಡ್ಡವು.',
    quality: 'JPG ಗುಣಮಟ್ಟ',
    est_size: '{w} × {h} px ನಲ್ಲಿ ಸುಮಾರು {kb} KB',
    dl_this: 'ಈ ಗಾತ್ರ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ({w} × {h})',
    dl_all: 'ಟಿಕ್ ಹಾಕಿದ {n} ಗಾತ್ರಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    dl_none: 'ಮೊದಲು ಕನಿಷ್ಠ ಒಂದು ಗಾತ್ರಕ್ಕೆ ಟಿಕ್ ಹಾಕಿ.',
    dl_many_hint: 'ಫೈಲ್‌ಗಳು ಒಂದಾದ ಮೇಲೆ ಒಂದು ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತವೆ. ಬ್ರೌಸರ್ ಹಲವು ಡೌನ್‌ಲೋಡ್‌ಗಳಿಗೆ ಅನುಮತಿ ಕೇಳಿದರೆ ಹೌದು ಎನ್ನಿ.',
    dl_done: '{name} ಉಳಿಸಲಾಗಿದೆ ({kb} KB)',
    dl_progress: '{n} ರಲ್ಲಿ {i}: {name}',
    dl_all_done: '{n} ಫೈಲ್‌ಗಳು ಡೌನ್‌ಲೋಡ್ ಆದವು.',
    share_btn: 'ಈ ಗಾತ್ರ ಹಂಚಿಕೊಳ್ಳಿ',
    reset_all: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ / ಐಡಿಯಾಗಳು',
    tip1: 'ಚಿತ್ರ ಆರಿಸಿ, ಒಂದು ಗಾತ್ರ ತಟ್ಟಿ, ನಂತರ ಚಿತ್ರವನ್ನು ಎಳೆದು ಸರಿಯಾದ ಜಾಗದಲ್ಲಿ ಇರಿಸಿ. ಮುಖ್ಯ ಭಾಗದ ಮೇಲೆ ಜೂಮ್ ಮಾಡಲು ಸ್ಕ್ರಾಲ್ ಮಾಡಿ ಅಥವಾ ಎರಡು ಬೆರಳಿನಿಂದ ಹಿಗ್ಗಿಸಿ. ಪ್ರತಿ ಗಾತ್ರ ತನ್ನ ಸ್ಥಾನವನ್ನು ನೆನಪಿಡುತ್ತದೆ.',
    tip2: 'ಫಿಟ್ ಪೂರ್ಣ ಪೋಸ್ಟರ್ ಉಳಿಸಿ, ಖಾಲಿ ಜಾಗವನ್ನು ಮಬ್ಬು ಪ್ರತಿ ಅಥವಾ ಬಣ್ಣದಿಂದ ತುಂಬುತ್ತದೆ. ಫಿಲ್ ಚಿತ್ರವನ್ನು ಸರಿಯಾದ ಆಕಾರಕ್ಕೆ ಕ್ರಾಪ್ ಮಾಡುತ್ತದೆ. "ಎಲ್ಲಾ ಗಾತ್ರಗಳಿಗೂ ಇದೇ ಫಿಟ್ / ಫಿಲ್" ನಿಮ್ಮ ಆಯ್ಕೆಯನ್ನು ಎಲ್ಲೆಡೆ ಅನ್ವಯಿಸುತ್ತದೆ.',
    tip3: 'ಅಂಗಡಿಯವರು: ಆಫರ್ ಪೋಸ್ಟರ್ ಒಮ್ಮೆ ಮಾಡಿ, Instagram ಪೋಸ್ಟ್, WhatsApp ಸ್ಟೇಟಸ್ ಮತ್ತು Facebook ಕವರ್‌ಗೆ ಟಿಕ್ ಹಾಕಿ, ಎಲ್ಲವನ್ನೂ ಒಟ್ಟಿಗೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ. ಕ್ಯಾಪ್ಶನ್ ಪಟ್ಟಿಯಲ್ಲಿ ಅಂಗಡಿಯ ಹೆಸರು ಸೇರಿಸಿ.',
    tip4: 'ಕ್ರಿಯೇಟರ್‌ಗಳು: Shorts, Reels ಮತ್ತು ಸ್ಟೇಟಸ್‌ನಲ್ಲಿ ಪಠ್ಯವನ್ನು ಮೇಲೆ-ಕೆಳಗಿನ ನೆರಳು ಭಾಗದಿಂದ ಹೊರಗಿಡಿ; ಅಲ್ಲಿ ಆ್ಯಪ್ ಬಟನ್‌ಗಳಿರುತ್ತವೆ. YouTube ಬ್ಯಾನರ್‌ನಲ್ಲಿ ಎಲ್ಲವನ್ನೂ ಪ್ರಕಾಶಮಾನ ಮಧ್ಯಭಾಗದಲ್ಲೇ ಇಡಿ.',
    tip5: 'ಶಾಲೆಗಳು ಮತ್ತು ಕಚೇರಿಗಳು: ಒಂದು ನೋಟಿಸ್ ಫೋಟೋ ಒಂದು ನಿಮಿಷದಲ್ಲಿ WhatsApp DP, YouTube ಥಂಬ್‌ನೇಲ್ ಮತ್ತು Facebook ಕವರ್ ಆಗುತ್ತದೆ. ಪ್ರತಿ ಪೋಸ್ಟ್ ನಿಮ್ಮದೆಂದು ಕಾಣಲು ಮೂಲೆಯಲ್ಲಿ ಲೋಗೋ ಇಡಿ.',
    tip6: 'ಪಠ್ಯ ಮತ್ತು ಲೋಗೋ ಇರುವ ಪೋಸ್ಟರ್‌ಗಳಿಗೆ PNG ಬಳಸಿ. ಫೋಟೋಗಳಿಗೆ JPG ಗುಣಮಟ್ಟ 85–92 ಇಡಿ: ಫೈಲ್‌ಗಳು ಚಿಕ್ಕವಾಗಿರುತ್ತವೆ, ನಿಧಾನ ನೆಟ್‌ವರ್ಕ್‌ನಲ್ಲೂ ಬೇಗ ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತವೆ.',
    sample_shop: 'ಶರ್ಮಾ ಸ್ವೀಟ್ಸ್',
    sample_offer: 'ದೀಪಾವಳಿ ಸ್ಪೆಷಲ್ · ಪ್ರತಿ ಬೆಳಿಗ್ಗೆ ತಾಜಾ',
    sample_off: '20% ರಿಯಾಯಿತಿ'
  },
  ml: {
    app_title: 'സോഷ്യൽ പോസ്റ്റ് റീസൈസർ',
    intro: 'ഒരു ഫോട്ടോ അല്ലെങ്കിൽ പോസ്റ്റർ Instagram, YouTube, WhatsApp, Facebook, LinkedIn, X, Google Business എന്നിവയ്ക്കുള്ള ശരിയായ വലുപ്പത്തിലാക്കുക: വലിച്ച് സ്ഥാനത്ത് വെക്കുക, സൂം ചെയ്യുക, പിന്നെ എല്ലാ വലുപ്പവും ഡൗൺലോഡ് ചെയ്യുക.',
    privacy_head: 'നിങ്ങളുടെ ഫോട്ടോകൾ ഈ ഉപകരണത്തിന് പുറത്തേക്ക് പോകുന്നേയില്ല.',
    privacy_body: 'വലുപ്പം മാറ്റുന്ന ജോലി നിങ്ങളുടെ ബ്രൗസറിനുള്ളിൽ തന്നെ നടക്കുന്നു. ഒന്നും അപ്‌ലോഡ് ആകുന്നില്ല, ഒന്നും ഓൺലൈനിൽ സേവ് ആകുന്നില്ല.',
    drop_title: 'ഫോട്ടോ അല്ലെങ്കിൽ പോസ്റ്റർ തിരഞ്ഞെടുക്കുക',
    drop_hint: 'JPG, PNG, WebP അല്ലെങ്കിൽ GIF · ഇവിടെ വലിച്ചിടുക, അല്ലെങ്കിൽ പേസ്റ്റ് ചെയ്യുക (Ctrl+V)',
    pick_btn: 'ചിത്രം തിരഞ്ഞെടുക്കുക',
    sample_btn: 'മാതൃക കാണുക',
    loaded_sample: 'മാതൃകാ പോസ്റ്റർ തുറന്നിരിക്കുന്നു. തുടങ്ങാൻ നിങ്ങളുടെ ചിത്രം തിരഞ്ഞെടുക്കുക.',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'വലിയ ഫോട്ടോ വേഗത്തിലുള്ള ജോലിക്കായി {w} × {h} px ആയി ചെറുതാക്കി.',
    picture: 'ചിത്രം',
    err_open: 'ഈ ഫയൽ ചിത്രമായി തുറക്കാനായില്ല. JPG അല്ലെങ്കിൽ PNG ശ്രമിക്കുക.',
    err_heic: 'HEIC ഫോട്ടോകൾ (iPhone) ഇവിടെ തുറക്കില്ല. ഫോണിൽ നിന്ന് ഫോട്ടോ JPG ആയി പങ്കിടുക, അല്ലെങ്കിൽ ഞങ്ങളുടെ Image Compressor ഉപയോഗിച്ച് മാറ്റുക.',
    err_heic_link: 'Image Compressor തുറക്കുക',
    too_big: 'ഈ ഫയൽ വളരെ വലുതാണ്. 80 MB-യിൽ താഴെയുള്ള ഫോട്ടോ ശ്രമിക്കുക.',
    err_export: 'ചിത്രം സേവ് ചെയ്യാനായില്ല. ചെറിയ വലുപ്പം അല്ലെങ്കിൽ PNG ശ്രമിക്കുക.',
    h_adjust: 'ക്രമീകരിക്കുക',
    stage_aria: 'ചിത്രത്തിന്റെ പ്രിവ്യൂ. നീക്കാൻ വലിക്കുക, സൂം ചെയ്യാൻ മൗസ് വീൽ അല്ലെങ്കിൽ രണ്ടു വിരലുകൾ ഉപയോഗിക്കുക.',
    drag_hint: 'ചിത്രം നീക്കാൻ വലിക്കുക · സൂം ചെയ്യാൻ സ്ക്രോൾ ചെയ്യുക അല്ലെങ്കിൽ രണ്ടു വിരലുകൊണ്ട് വിടർത്തുക',
    keys_hint: 'കീബോർഡ്: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> നീക്കുക · <kbd>+</kbd> <kbd>−</kbd> സൂം · <kbd>0</kbd> റീസെറ്റ് · <kbd>F</kbd> ഫിറ്റ് / ഫിൽ',
    mode_label: 'ഫിറ്റ് അല്ലെങ്കിൽ ഫിൽ',
    mode_fit: 'ഫിറ്റ് (മുഴുവൻ ചിത്രം)',
    mode_fill: 'ഫിൽ (വലുപ്പത്തിന് ക്രോപ്)',
    zoom: 'സൂം',
    center_btn: 'സ്ഥാനവും സൂമും റീസെറ്റ് ചെയ്യുക',
    bg_label: 'പശ്ചാത്തലം (ചിത്രം ഫ്രെയിം മുഴുവൻ നിറയാത്തപ്പോൾ)',
    bg_blur: 'മങ്ങിയ ഫോട്ടോ',
    bg_auto: 'സ്വയം നിറം',
    bg_white: 'വെള്ള',
    bg_black: 'കറുപ്പ്',
    bg_custom: 'നിറം തിരഞ്ഞെടുക്കുക',
    safe_show: 'സുരക്ഷിത ഭാഗം കാണിക്കുക',
    apply_all: 'എല്ലാ വലുപ്പങ്ങൾക്കും ഇതേ ഫിറ്റ് / ഫിൽ',
    applied_all: 'എല്ലാ വലുപ്പങ്ങൾക്കും ബാധകമാക്കി.',
    safe_hint_bands: 'പേരുകളും വിലകളും മുകളിലും താഴെയുമുള്ള നിഴൽ ഭാഗത്തിന് പുറത്ത് വെക്കുക: അവിടെ ആപ്പ് ബട്ടണുകളും ക്യാപ്ഷനുകളും വരും.',
    safe_hint_rect: 'എല്ലാ ഉപകരണങ്ങളിലും (TV, കമ്പ്യൂട്ടർ, ഫോൺ) തെളിഞ്ഞ ഭാഗം മാത്രമേ കാണൂ.',
    safe_hint_circle: 'ഈ ചിത്രം വൃത്താകൃതിയിൽ കാണിക്കും: നിഴൽ മൂലകൾ മുറിഞ്ഞുപോകും.',
    safe_hint_avoid: 'നിഴൽ മൂല വീഡിയോ ദൈർഘ്യമോ പ്രൊഫൈൽ ഫോട്ടോയോ മറയ്ക്കും.',
    h_caption: 'ക്യാപ്ഷൻ പട്ട',
    caption_on: 'ക്യാപ്ഷൻ പട്ട ചേർക്കുക',
    caption_text: 'ക്യാപ്ഷൻ വാചകം',
    caption_ph: 'ഉദാ. ശർമ്മ സ്വീറ്റ്സ് · ദീപാവലി ഓഫർ · 20% ഇളവ്',
    caption_pos: 'സ്ഥാനം',
    pos_top: 'മുകളിൽ',
    pos_bottom: 'താഴെ',
    caption_style: 'ശൈലി',
    style_dark: 'ഇരുണ്ട',
    style_light: 'ഇളം',
    style_brand: 'തിരഞ്ഞെടുത്ത നിറം',
    on_badge: 'ഓൺ',
    h_logo: 'മൂലയിൽ ലോഗോ',
    logo_pick: 'ലോഗോ ചേർക്കുക',
    logo_remove: 'ലോഗോ നീക്കുക',
    logo_hint: 'സുതാര്യ പശ്ചാത്തലമുള്ള PNG ഏറ്റവും നന്നായി കാണും.',
    logo_corner: 'മൂല',
    corner_tl: 'മുകളിൽ ഇടത്',
    corner_tr: 'മുകളിൽ വലത്',
    corner_bl: 'താഴെ ഇടത്',
    corner_br: 'താഴെ വലത്',
    logo_size: 'ലോഗോ വലുപ്പം',
    h_sizes: 'വലുപ്പങ്ങൾ',
    sizes_hint: 'ക്രമീകരിക്കാൻ ഒരു വലുപ്പത്തിൽ ടാപ്പ് ചെയ്യുക. ഡൗൺലോഡ് ചെയ്യേണ്ട വലുപ്പങ്ങൾ ടിക്ക് ചെയ്യുക.',
    custom_w: 'വീതി (px)',
    custom_h: 'ഉയരം (px)',
    custom_hint: '16 മുതൽ 4096 px വരെ ഏത് വലുപ്പവും.',
    sel_count: 'ഡൗൺലോഡിനായി {n} വലുപ്പങ്ങൾ ടിക്ക് ചെയ്തിരിക്കുന്നു',
    sel_all: 'എല്ലാം ടിക്ക് ചെയ്യുക',
    sel_none: 'എല്ലാ ടിക്കും മാറ്റുക',
    tick_aria: '{name} ഡൗൺലോഡ് ചെയ്യുക',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'സ്വന്തം വലുപ്പം',
    p_ig_square: 'പോസ്റ്റ് (ചതുരം)',
    p_ig_portrait: 'പോസ്റ്റ് (നീളത്തിൽ)',
    p_ig_landscape: 'പോസ്റ്റ് (വീതിയിൽ)',
    p_ig_story: 'സ്റ്റോറി & റീൽ കവർ',
    p_ig_dp: 'പ്രൊഫൈൽ ചിത്രം',
    p_yt_thumb: 'വീഡിയോ തംബ്‌നെയിൽ',
    p_yt_shorts: 'Shorts കവർ',
    p_yt_banner: 'ചാനൽ ബാനർ',
    p_yt_dp: 'ചാനൽ ചിത്രം',
    p_wa_dp: 'പ്രൊഫൈൽ ഫോട്ടോ (DP)',
    p_wa_status: 'സ്റ്റാറ്റസ്',
    p_fb_post: 'പോസ്റ്റ് (വീതിയിൽ)',
    p_fb_square: 'പോസ്റ്റ് (ചതുരം)',
    p_fb_cover: 'പേജ് കവർ',
    p_fb_story: 'സ്റ്റോറി',
    p_li_post: 'പോസ്റ്റ്',
    p_li_banner: 'പ്രൊഫൈൽ ബാനർ',
    p_x_post: 'പോസ്റ്റ്',
    p_x_header: 'ഹെഡർ',
    p_gb_photo: 'ബിസിനസ് ഫോട്ടോ',
    p_gb_cover: 'കവർ ഫോട്ടോ',
    p_custom: 'സ്വന്തം വലുപ്പം',
    h_export: 'ഡൗൺലോഡ്',
    fmt_label: 'ഫോർമാറ്റ്',
    fmt_hint_jpg: 'JPG: ചെറിയ ഫയലുകൾ, ഫോട്ടോകൾക്ക് ഏറ്റവും നല്ലത്.',
    fmt_hint_png: 'PNG: വ്യക്തമായ വാചകവും ലോഗോയും; ഫയലുകൾ വലുത്.',
    quality: 'JPG ഗുണനിലവാരം',
    est_size: '{w} × {h} px-ൽ ഏകദേശം {kb} KB',
    dl_this: 'ഈ വലുപ്പം ഡൗൺലോഡ് ചെയ്യുക ({w} × {h})',
    dl_all: 'ടിക്ക് ചെയ്ത {n} വലുപ്പങ്ങൾ ഡൗൺലോഡ് ചെയ്യുക',
    dl_none: 'ആദ്യം കുറഞ്ഞത് ഒരു വലുപ്പം ടിക്ക് ചെയ്യുക.',
    dl_many_hint: 'ഫയലുകൾ ഒന്നൊന്നായി ഡൗൺലോഡ് ആകും. ഒന്നിലധികം ഡൗൺലോഡിന് ബ്രൗസർ അനുവാദം ചോദിച്ചാൽ അതെ എന്ന് പറയുക.',
    dl_done: '{name} സേവ് ചെയ്തു ({kb} KB)',
    dl_progress: '{n}-ൽ {i}: {name}',
    dl_all_done: '{n} ഫയലുകൾ ഡൗൺലോഡ് ചെയ്തു.',
    share_btn: 'ഈ വലുപ്പം പങ്കിടുക',
    reset_all: 'ക്രമീകരണങ്ങൾ റീസെറ്റ് ചെയ്യുക',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ആശയങ്ങൾ',
    tip1: 'ചിത്രം തിരഞ്ഞെടുക്കുക, ഒരു വലുപ്പത്തിൽ ടാപ്പ് ചെയ്യുക, പിന്നെ ചിത്രം വലിച്ച് സ്ഥാനത്ത് വെക്കുക. പ്രധാന ഭാഗത്തേക്ക് സൂം ചെയ്യാൻ സ്ക്രോൾ ചെയ്യുക അല്ലെങ്കിൽ രണ്ടു വിരലുകൊണ്ട് വിടർത്തുക. ഓരോ വലുപ്പവും അതിന്റെ സ്ഥാനം ഓർമ്മിക്കും.',
    tip2: 'ഫിറ്റ് മുഴുവൻ പോസ്റ്ററും നിലനിർത്തി ഒഴിഞ്ഞ സ്ഥലം മങ്ങിയ പകർപ്പോ നിറമോ കൊണ്ട് നിറയ്ക്കുന്നു. ഫിൽ ചിത്രം കൃത്യമായ ആകൃതിയിൽ ക്രോപ് ചെയ്യുന്നു. "എല്ലാ വലുപ്പങ്ങൾക്കും ഇതേ ഫിറ്റ് / ഫിൽ" നിങ്ങളുടെ തിരഞ്ഞെടുപ്പ് എല്ലായിടത്തും ബാധകമാക്കുന്നു.',
    tip3: 'കടക്കാർ: ഓഫർ പോസ്റ്റർ ഒരിക്കൽ ഉണ്ടാക്കി, Instagram പോസ്റ്റ്, WhatsApp സ്റ്റാറ്റസ്, Facebook കവർ ടിക്ക് ചെയ്ത് എല്ലാം ഒരുമിച്ച് ഡൗൺലോഡ് ചെയ്യുക. ക്യാപ്ഷൻ പട്ടയിൽ കടയുടെ പേര് ചേർക്കുക.',
    tip4: 'ക്രിയേറ്റർമാർ: Shorts, Reels, സ്റ്റാറ്റസ് എന്നിവയിൽ വാചകം മുകളിലും താഴെയുമുള്ള നിഴൽ ഭാഗത്തിന് പുറത്ത് വെക്കുക; അവിടെ ആപ്പ് ബട്ടണുകളാണ്. YouTube ബാനറിൽ എല്ലാം തെളിഞ്ഞ നടുഭാഗത്ത് തന്നെ വെക്കുക.',
    tip5: 'സ്കൂളുകളും ഓഫീസുകളും: ഒരു നോട്ടീസ് ഫോട്ടോ ഒരു മിനിറ്റിൽ WhatsApp DP, YouTube തംബ്‌നെയിൽ, Facebook കവർ ആകും. ഓരോ പോസ്റ്റും നിങ്ങളുടേതെന്ന് കാണാൻ മൂലയിൽ ലോഗോ വെക്കുക.',
    tip6: 'വാചകവും ലോഗോയുമുള്ള പോസ്റ്ററുകൾക്ക് PNG ഉപയോഗിക്കുക. ഫോട്ടോകൾക്ക് JPG ഗുണനിലവാരം 85–92: ഫയലുകൾ ചെറുതായിരിക്കും, മന്ദഗതിയിലുള്ള നെറ്റ്‌വർക്കിലും വേഗം അപ്‌ലോഡ് ആകും.',
    sample_shop: 'ശർമ്മ സ്വീറ്റ്സ്',
    sample_offer: 'ദീപാവലി സ്പെഷ്യൽ · എല്ലാ ദിവസവും രാവിലെ പുതുതായി',
    sample_off: '20% ഇളവ്'
  },
  ur: {
    app_title: 'سوشل پوسٹ ری سائزر',
    intro: 'ایک تصویر یا پوسٹر کو Instagram، YouTube، WhatsApp، Facebook، LinkedIn، X اور Google Business کے صحیح سائز میں بدلیں: کھینچ کر جگہ پر رکھیں، زوم کریں، پھر ہر سائز ڈاؤن لوڈ کریں۔',
    privacy_head: 'آپ کی تصویریں کبھی اس آلے سے باہر نہیں جاتیں۔',
    privacy_body: 'سائز بدلنے کا کام آپ کے براؤزر کے اندر ہی ہوتا ہے۔ کچھ بھی اپ لوڈ نہیں ہوتا، کچھ بھی آن لائن محفوظ نہیں ہوتا۔',
    drop_title: 'تصویر یا پوسٹر چنیں',
    drop_hint: 'JPG، PNG، WebP یا GIF · یہاں کھینچ کر چھوڑیں، یا پیسٹ کریں (Ctrl+V)',
    pick_btn: 'تصویر چنیں',
    sample_btn: 'نمونہ دیکھیں',
    loaded_sample: 'نمونہ پوسٹر کھلا ہے۔ شروع کرنے کے لیے اپنی تصویر چنیں۔',
    loaded_info: '{name} · {w} × {h} px',
    loaded_scaled: 'بڑی تصویر تیز کام کے لیے {w} × {h} px تک چھوٹی کی گئی۔',
    picture: 'تصویر',
    err_open: 'یہ فائل تصویر کے طور پر نہیں کھل سکی۔ JPG یا PNG آزمائیں۔',
    err_heic: 'HEIC تصویریں (iPhone) یہاں نہیں کھلتیں۔ فون سے تصویر JPG کے طور پر شیئر کریں، یا ہمارے Image Compressor سے بدلیں۔',
    err_heic_link: 'Image Compressor کھولیں',
    too_big: 'یہ فائل بہت بڑی ہے۔ 80 MB سے چھوٹی تصویر آزمائیں۔',
    err_export: 'تصویر محفوظ نہیں ہو سکی۔ چھوٹا سائز یا PNG آزمائیں۔',
    h_adjust: 'ترتیب دیں',
    stage_aria: 'تصویر کا پیش منظر۔ ہلانے کے لیے کھینچیں، زوم کے لیے ماؤس وہیل یا دو انگلیاں استعمال کریں۔',
    drag_hint: 'تصویر ہلانے کے لیے کھینچیں · زوم کے لیے اسکرول کریں یا دو انگلیوں سے پھیلائیں',
    keys_hint: 'کی بورڈ: <kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> ہلائیں · <kbd>+</kbd> <kbd>−</kbd> زوم · <kbd>0</kbd> ری سیٹ · <kbd>F</kbd> فِٹ / فِل',
    mode_label: 'فِٹ یا فِل',
    mode_fit: 'فِٹ (پوری تصویر)',
    mode_fill: 'فِل (سائز کے مطابق کراپ)',
    zoom: 'زوم',
    center_btn: 'جگہ اور زوم ری سیٹ کریں',
    bg_label: 'پس منظر (جب تصویر پورا فریم نہ بھرے)',
    bg_blur: 'دھندلی تصویر',
    bg_auto: 'خودکار رنگ',
    bg_white: 'سفید',
    bg_black: 'کالا',
    bg_custom: 'رنگ چنیں',
    safe_show: 'محفوظ حصہ دکھائیں',
    apply_all: 'سب سائزوں کے لیے یہی فِٹ / فِل',
    applied_all: 'سب سائزوں پر لاگو ہو گیا۔',
    safe_hint_bands: 'نام اور قیمتیں اوپر اور نیچے کے سایہ دار حصے سے باہر رکھیں: وہاں ایپ کے بٹن اور کیپشن آ جاتے ہیں۔',
    safe_hint_rect: 'ہر آلے (TV، کمپیوٹر اور فون) پر صرف روشن حصہ ہی نظر آتا ہے۔',
    safe_hint_circle: 'یہ تصویر گول دکھائی جاتی ہے: سایہ دار کونے کٹ جاتے ہیں۔',
    safe_hint_avoid: 'سایہ دار کونا ویڈیو کی لمبائی یا پروفائل تصویر سے ڈھک جاتا ہے۔',
    h_caption: 'کیپشن پٹی',
    caption_on: 'کیپشن پٹی شامل کریں',
    caption_text: 'کیپشن کا متن',
    caption_ph: 'مثلاً: شرما سوئیٹس · دیوالی آفر · 20% رعایت',
    caption_pos: 'جگہ',
    pos_top: 'اوپر',
    pos_bottom: 'نیچے',
    caption_style: 'انداز',
    style_dark: 'گہرا',
    style_light: 'ہلکا',
    style_brand: 'چنا ہوا رنگ',
    on_badge: 'آن',
    h_logo: 'کونے میں لوگو',
    logo_pick: 'لوگو شامل کریں',
    logo_remove: 'لوگو ہٹائیں',
    logo_hint: 'شفاف پس منظر والا PNG سب سے اچھا لگتا ہے۔',
    logo_corner: 'کونا',
    corner_tl: 'اوپر بائیں',
    corner_tr: 'اوپر دائیں',
    corner_bl: 'نیچے بائیں',
    corner_br: 'نیچے دائیں',
    logo_size: 'لوگو کا سائز',
    h_sizes: 'سائز',
    sizes_hint: 'ترتیب دینے کے لیے کسی سائز پر ٹیپ کریں۔ جو سائز ڈاؤن لوڈ کرنے ہیں، ان پر ٹِک لگائیں۔',
    custom_w: 'چوڑائی (px)',
    custom_h: 'اونچائی (px)',
    custom_hint: '16 سے 4096 px تک کوئی بھی سائز۔',
    sel_count: 'ڈاؤن لوڈ کے لیے {n} سائزوں پر ٹِک ہے',
    sel_all: 'سب پر ٹِک',
    sel_none: 'سب ٹِک ہٹائیں',
    tick_aria: '{name} ڈاؤن لوڈ کریں',
    pf_instagram: 'Instagram',
    pf_youtube: 'YouTube',
    pf_whatsapp: 'WhatsApp',
    pf_facebook: 'Facebook',
    pf_linkedin: 'LinkedIn',
    pf_x: 'X (Twitter)',
    pf_google: 'Google Business',
    pf_custom: 'اپنا سائز',
    p_ig_square: 'پوسٹ (چوکور)',
    p_ig_portrait: 'پوسٹ (کھڑی)',
    p_ig_landscape: 'پوسٹ (لیٹی)',
    p_ig_story: 'اسٹوری اور ریل کور',
    p_ig_dp: 'پروفائل تصویر',
    p_yt_thumb: 'ویڈیو تھمب نیل',
    p_yt_shorts: 'Shorts کور',
    p_yt_banner: 'چینل بینر',
    p_yt_dp: 'چینل کی تصویر',
    p_wa_dp: 'پروفائل تصویر (DP)',
    p_wa_status: 'اسٹیٹس',
    p_fb_post: 'پوسٹ (لیٹی)',
    p_fb_square: 'پوسٹ (چوکور)',
    p_fb_cover: 'پیج کور',
    p_fb_story: 'اسٹوری',
    p_li_post: 'پوسٹ',
    p_li_banner: 'پروفائل بینر',
    p_x_post: 'پوسٹ',
    p_x_header: 'ہیڈر',
    p_gb_photo: 'کاروبار کی تصویر',
    p_gb_cover: 'کور تصویر',
    p_custom: 'اپنا سائز',
    h_export: 'ڈاؤن لوڈ',
    fmt_label: 'فارمیٹ',
    fmt_hint_jpg: 'JPG: چھوٹی فائلیں، تصویروں کے لیے بہترین۔',
    fmt_hint_png: 'PNG: صاف متن اور لوگو، فائلیں بڑی۔',
    quality: 'JPG کوالٹی',
    est_size: '{w} × {h} px پر تقریباً {kb} KB',
    dl_this: 'یہ سائز ڈاؤن لوڈ کریں ({w} × {h})',
    dl_all: 'ٹِک کیے گئے {n} سائز ڈاؤن لوڈ کریں',
    dl_none: 'پہلے کم سے کم ایک سائز پر ٹِک لگائیں۔',
    dl_many_hint: 'فائلیں ایک ایک کر کے ڈاؤن لوڈ ہوتی ہیں۔ اگر براؤزر کئی ڈاؤن لوڈ کی اجازت مانگے تو ہاں کہیں۔',
    dl_done: '{name} محفوظ ہو گئی ({kb} KB)',
    dl_progress: '{n} میں سے {i}: {name}',
    dl_all_done: '{n} فائلیں ڈاؤن لوڈ ہو گئیں۔',
    share_btn: 'یہ سائز شیئر کریں',
    reset_all: 'ترتیبات ری سیٹ کریں',
    help_title: 'استعمال کیسے کریں / خیالات',
    tip1: 'تصویر چنیں، کسی سائز پر ٹیپ کریں، پھر تصویر کو کھینچ کر جگہ پر رکھیں۔ اہم حصے پر زوم کرنے کے لیے اسکرول کریں یا دو انگلیوں سے پھیلائیں۔ ہر سائز اپنی جگہ یاد رکھتا ہے۔',
    tip2: 'فِٹ پورا پوسٹر رکھتا ہے اور خالی جگہ دھندلی نقل یا رنگ سے بھرتا ہے۔ فِل تصویر کو صحیح شکل میں کراپ کرتا ہے۔ "سب سائزوں کے لیے یہی فِٹ / فِل" آپ کی پسند ہر جگہ لاگو کرتا ہے۔',
    tip3: 'دکاندار: آفر کا پوسٹر ایک بار بنائیں، Instagram پوسٹ، WhatsApp اسٹیٹس اور Facebook کور پر ٹِک لگائیں اور سب ایک ساتھ ڈاؤن لوڈ کریں۔ کیپشن پٹی میں دکان کا نام لکھیں۔',
    tip4: 'کری ایٹرز: Shorts، Reels اور اسٹیٹس میں متن اوپر اور نیچے کے سایہ دار حصے سے باہر رکھیں، وہاں ایپ کے بٹن ہوتے ہیں۔ YouTube بینر میں سب کچھ روشن درمیانی حصے میں رکھیں۔',
    tip5: 'اسکول اور دفاتر: ایک نوٹس کی تصویر ایک منٹ میں WhatsApp DP، YouTube تھمب نیل اور Facebook کور بن جاتی ہے۔ کونے میں لوگو لگائیں تاکہ ہر پوسٹ آپ کی پہچان دکھائے۔',
    tip6: 'متن اور لوگو والے پوسٹروں کے لیے PNG چنیں۔ تصویروں کے لیے JPG کوالٹی 85–92 رکھیں: فائلیں چھوٹی رہتی ہیں اور سست نیٹ ورک پر بھی جلدی اپ لوڈ ہوتی ہیں۔',
    sample_shop: 'شرما سوئیٹس',
    sample_offer: 'دیوالی اسپیشل · ہر صبح تازہ',
    sample_off: '20% رعایت'
  }
};
