/* Periodic Table Explorer: UI strings. Keys are identical in all 12 languages.
   Shared words (next, reset, print, fullscreen, score, correct, wrong ...) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Periodic Table Explorer',
    intro: 'Explore all 118 elements: tap any element to see its electron configuration, valency and Bohr model, then test yourself with quick quizzes.',
    how_title: 'How to use · Ideas for the classroom',
    tab_table: 'Periodic table', tab_quiz: 'Quiz', tab_cbse: 'Class 9–10 corner',
    search_label: 'Find an element', search_ph: 'Name, symbol or number, e.g. Na, 26, oxygen',
    n_found: '{n} found', no_match: 'No element found. Try a symbol like Fe or a number like 26.',
    colour_by: 'Colour by', by_family: 'Family', by_block: 'Block', by_state: 'State',
    highlight: 'Highlight', hl_all: 'Show all', grp_type: 'Type',
    hl_metal: 'Metals', hl_nonmetal: 'Non-metals', hl_metalloid: 'Metalloids', hl_solid: 'Solids', hl_liquid: 'Liquids', hl_gas: 'Gases', hl_radio: 'Radioactive', hl_first20: 'First 20 elements',
    legend_hint: 'Tap a colour to highlight that set. Tap it again to show all.',
    axis_hint: 'Columns are groups (1–18). Rows are periods (1–7).',
    pt_aria: 'Periodic table of 118 elements', tile_aria: '{name} ({s}), atomic number {n}',
    lanthanoids: 'Lanthanoids', actinoids: 'Actinoids',
    cat_alkali: 'Alkali metal', cat_alkaline: 'Alkaline earth metal', cat_transition: 'Transition metal', cat_post: 'Other metal', cat_metalloid: 'Metalloid', cat_nonmetal: 'Non-metal', cat_halogen: 'Halogen', cat_noble: 'Noble gas', cat_lanthanoid: 'Lanthanoid', cat_actinoid: 'Actinoid',
    block_name: '{b}-block', state_solid: 'Solid', state_liquid: 'Liquid', state_gas: 'Gas', state_unknown: 'Not known',
    type_metal: 'Metal', type_nonmetal: 'Non-metal', type_metalloid: 'Metalloid',
    d_number: 'Atomic number', d_mass: 'Atomic mass (u)', d_group: 'Group', d_period: 'Period', d_family: 'Family', d_type: 'Type', d_state: 'State at room temperature', d_en: 'Electronegativity (Pauling)', d_config: 'Electron configuration', d_full: 'Written in full', d_shells: 'Electrons in shells', d_valence: 'Valence electrons', d_valency: 'Valency', d_particles: 'Inside the atom',
    particles_val: '{p} protons, {n} neutrons, {e} electrons (mass number {a})',
    not_known: 'Not known', mass_note: 'A mass in [ ] is the mass number of the most stable isotope.', latin_note: 'The symbol comes from its Latin name “{name}”.',
    radioactive: 'Radioactive', predicted: 'Only a few atoms have ever been made, so some facts are predictions.',
    uses_title: 'Where we meet it', hear_name: 'Hear the English name', in_english: 'In English: {name}',
    bohr_title: 'Bohr model', bohr_caption: 'Nucleus: {p} protons and {n} neutrons. Shells: {s}.', bohr_only20: 'Bohr diagrams are drawn for the first 20 elements, as in Class 9.',
    featured_hint: 'Tap any element', print_table: 'Print table',
    quiz_mode: 'Question type', q_sym2name: 'Symbol → name', q_name2sym: 'Name → symbol', q_num2sym: 'Number → symbol', q_valency: 'Valency (first 20)',
    quiz_range: 'Elements', range_first: 'First {n}', range_all: 'All 118',
    ask_sym2name: 'Which element has the symbol {s}?', ask_name2sym: 'What is the symbol of {name}?', ask_num2sym: 'Which element has atomic number {n}?', ask_valency: 'What is the valency of {name} ({s})?',
    q_progress: 'Question {i} of {n}', score_val: '{c} / {n}', ans_fact: '{s} is {name}, atomic number {n}.',
    ex_lose: '{name} ({shells}) has {v} electrons in its outer shell. It gives them away, so its valency is {v}.',
    ex_gain: '{name} ({shells}) has {v} electrons in its outer shell. It needs {val} more to make 8, so its valency is {val}.',
    ex_share: '{name} ({shells}) has {v} electrons in its outer shell. It shares them, so its valency is {v}.',
    ex_full: '{name} ({shells}) already has a full outer shell, so its valency is 0.',
    ex_h: 'Hydrogen has 1 electron. It needs 1 more to fill its only shell, so its valency is 1.',
    round_done: 'Round over! You got {c} out of {n}.', best_score: 'Best: {b} / {n}', play_again: 'Play again',
    msg_perfect: 'Full marks! You are a periodic table star.', msg_good: 'Good work! Check your mistakes and play again.', msg_try: 'Keep practising: explore the table, then try again.',
    quiz_keys: 'Keyboard: press 1–5 to answer and Enter for the next question.',
    cbse_first20: 'First 20 elements: shells and valency', first20_hint: 'Tap a name to open that element in the table.',
    col_no: 'No.', col_sym: 'Symbol', col_name: 'Name', col_massno: 'Mass number',
    how_valency_title: 'How to find valency',
    how_valency: 'Count the electrons in the outermost shell. If there are 1, 2, 3 or 4, the valency is the same number. If there are 5, 6 or 7, the valency is 8 minus that number. A full shell (2 for helium, 8 for the others) means valency 0.',
    valency_eg: 'Example: chlorine is 2, 8, 7. It has 7 outer electrons, so its valency is 8 − 7 = 1. Sodium (2, 8, 1) also has valency 1, so common salt is NaCl.',
    triads_title: 'Döbereiner’s triads', triads_desc: 'In each set of three similar elements, the mass of the middle one is close to the average of the other two.',
    col_triad: 'Triad', col_avg: 'Average of 1st and 3rd', col_middle: 'Mass of the middle one',
    mend_title: 'Mendeleev’s table and the modern periodic table', col_point: 'Point', col_mend: 'Mendeleev (1869)', col_modern: 'Modern (Moseley, 1913)',
    trends_title: 'Trends to remember',
    print_ws: 'Print worksheet', ws_title: 'Worksheet: the first 20 elements', ws_line: 'Name: ______________   Class: ______   Date: __________',
    ws_instr: 'Fill in the empty boxes. Use the shells to work out the valency.', ws_key: 'Answer key'
  },
  hi: {
    app_title: 'आवर्त सारणी एक्सप्लोरर',
    intro: 'सभी 118 तत्वों को जानें: किसी भी तत्व पर टैप करके उसका इलेक्ट्रॉनिक विन्यास, संयोजकता और बोर मॉडल देखें, फिर छोटे क्विज़ से खुद को परखें।',
    how_title: 'कैसे इस्तेमाल करें · कक्षा के लिए सुझाव',
    tab_table: 'आवर्त सारणी', tab_quiz: 'क्विज़', tab_cbse: 'कक्षा 9–10 कोना',
    search_label: 'तत्व खोजें', search_ph: 'नाम, प्रतीक या संख्या, जैसे Na, 26, ऑक्सीजन',
    n_found: '{n} मिले', no_match: 'कोई तत्व नहीं मिला। Fe जैसा प्रतीक या 26 जैसी संख्या लिखकर देखें।',
    colour_by: 'रंग किस आधार पर', by_family: 'परिवार', by_block: 'ब्लॉक', by_state: 'अवस्था',
    highlight: 'चमकाएँ', hl_all: 'सभी दिखाएँ', grp_type: 'प्रकार',
    hl_metal: 'धातुएँ', hl_nonmetal: 'अधातुएँ', hl_metalloid: 'उपधातुएँ', hl_solid: 'ठोस', hl_liquid: 'द्रव', hl_gas: 'गैसें', hl_radio: 'रेडियोधर्मी', hl_first20: 'पहले 20 तत्व',
    legend_hint: 'किसी रंग पर टैप करें, वह समूह चमक उठेगा। दोबारा टैप करने पर सब दिखेंगे।',
    axis_hint: 'खड़े कॉलम समूह हैं (1–18)। आड़ी पंक्तियाँ आवर्त हैं (1–7)।',
    pt_aria: '118 तत्वों की आवर्त सारणी', tile_aria: '{name} ({s}), परमाणु संख्या {n}',
    lanthanoids: 'लैंथेनॉयड', actinoids: 'ऐक्टिनॉयड',
    cat_alkali: 'क्षार धातु', cat_alkaline: 'क्षारीय मृदा धातु', cat_transition: 'संक्रमण धातु', cat_post: 'अन्य धातु', cat_metalloid: 'उपधातु', cat_nonmetal: 'अधातु', cat_halogen: 'हैलोजन', cat_noble: 'उत्कृष्ट गैस', cat_lanthanoid: 'लैंथेनॉयड', cat_actinoid: 'ऐक्टिनॉयड',
    block_name: '{b}-ब्लॉक', state_solid: 'ठोस', state_liquid: 'द्रव', state_gas: 'गैस', state_unknown: 'पता नहीं',
    type_metal: 'धातु', type_nonmetal: 'अधातु', type_metalloid: 'उपधातु',
    d_number: 'परमाणु संख्या', d_mass: 'परमाणु द्रव्यमान (u)', d_group: 'समूह', d_period: 'आवर्त', d_family: 'परिवार', d_type: 'प्रकार', d_state: 'कमरे के ताप पर अवस्था', d_en: 'विद्युत ऋणात्मकता (पॉलिंग)', d_config: 'इलेक्ट्रॉनिक विन्यास', d_full: 'पूरा लिखें तो', d_shells: 'कोशों में इलेक्ट्रॉन', d_valence: 'संयोजी इलेक्ट्रॉन', d_valency: 'संयोजकता', d_particles: 'परमाणु के अंदर',
    particles_val: '{p} प्रोटॉन, {n} न्यूट्रॉन, {e} इलेक्ट्रॉन (द्रव्यमान संख्या {a})',
    not_known: 'पता नहीं', mass_note: '[ ] में लिखा द्रव्यमान सबसे स्थायी समस्थानिक की द्रव्यमान संख्या है।', latin_note: 'इसका प्रतीक लैटिन नाम “{name}” से आया है।',
    radioactive: 'रेडियोधर्मी', predicted: 'इसके अब तक बस कुछ ही परमाणु बने हैं, इसलिए कुछ बातें अनुमान हैं।',
    uses_title: 'यह हमें कहाँ मिलता है', hear_name: 'अंग्रेज़ी नाम सुनें', in_english: 'अंग्रेज़ी में: {name}',
    bohr_title: 'बोर मॉडल', bohr_caption: 'नाभिक: {p} प्रोटॉन और {n} न्यूट्रॉन। कोश: {s}।', bohr_only20: 'बोर चित्र पहले 20 तत्वों के लिए बनाए गए हैं, जैसे कक्षा 9 में।',
    featured_hint: 'किसी भी तत्व पर टैप करें', print_table: 'सारणी प्रिंट करें',
    quiz_mode: 'प्रश्न का प्रकार', q_sym2name: 'प्रतीक → नाम', q_name2sym: 'नाम → प्रतीक', q_num2sym: 'संख्या → प्रतीक', q_valency: 'संयोजकता (पहले 20)',
    quiz_range: 'तत्व', range_first: 'पहले {n}', range_all: 'सभी 118',
    ask_sym2name: '{s} किस तत्व का प्रतीक है?', ask_name2sym: '{name} का प्रतीक क्या है?', ask_num2sym: 'परमाणु संख्या {n} किस तत्व की है?', ask_valency: '{name} ({s}) की संयोजकता क्या है?',
    q_progress: 'प्रश्न {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} यानी {name}, परमाणु संख्या {n}।',
    ex_lose: '{name} ({shells}) के बाहरी कोश में {v} इलेक्ट्रॉन हैं। यह इन्हें दे देता है, इसलिए संयोजकता {v} है।',
    ex_gain: '{name} ({shells}) के बाहरी कोश में {v} इलेक्ट्रॉन हैं। 8 पूरे करने के लिए इसे {val} और चाहिए, इसलिए संयोजकता {val} है।',
    ex_share: '{name} ({shells}) के बाहरी कोश में {v} इलेक्ट्रॉन हैं। यह इन्हें साझा करता है, इसलिए संयोजकता {v} है।',
    ex_full: '{name} ({shells}) का बाहरी कोश पहले से भरा है, इसलिए संयोजकता 0 है।',
    ex_h: 'हाइड्रोजन में 1 इलेक्ट्रॉन है। इसके अकेले कोश को भरने के लिए 1 और चाहिए, इसलिए संयोजकता 1 है।',
    round_done: 'राउंड पूरा! आपके {n} में से {c} सही हुए।', best_score: 'सबसे अच्छा: {b} / {n}', play_again: 'फिर से खेलें',
    msg_perfect: 'पूरे अंक! आप आवर्त सारणी के स्टार हैं।', msg_good: 'बहुत अच्छे! गलतियाँ देखें और फिर से खेलें।', msg_try: 'अभ्यास जारी रखें: सारणी में तत्व देखें, फिर दोबारा कोशिश करें।',
    quiz_keys: 'कीबोर्ड: जवाब के लिए 1–5 दबाएँ और अगले प्रश्न के लिए Enter।',
    cbse_first20: 'पहले 20 तत्व: कोश और संयोजकता', first20_hint: 'किसी नाम पर टैप करें, वह तत्व सारणी में खुल जाएगा।',
    col_no: 'क्रम', col_sym: 'प्रतीक', col_name: 'नाम', col_massno: 'द्रव्यमान संख्या',
    how_valency_title: 'संयोजकता कैसे निकालें',
    how_valency: 'सबसे बाहरी कोश के इलेक्ट्रॉन गिनें। अगर 1, 2, 3 या 4 हैं, तो संयोजकता वही संख्या है। अगर 5, 6 या 7 हैं, तो 8 में से वह संख्या घटाने पर संयोजकता मिलती है। कोश भरा हो (हीलियम में 2, बाकी में 8) तो संयोजकता 0 है।',
    valency_eg: 'उदाहरण: क्लोरीन 2, 8, 7 है। इसके बाहरी कोश में 7 इलेक्ट्रॉन हैं, इसलिए संयोजकता 8 − 7 = 1 है। सोडियम (2, 8, 1) की संयोजकता भी 1 है, इसलिए नमक का सूत्र NaCl है।',
    triads_title: 'डॉबेराइनर के त्रिक', triads_desc: 'तीन मिलते-जुलते तत्वों के हर समूह में बीच वाले तत्व का द्रव्यमान बाकी दो के औसत के लगभग बराबर होता है।',
    col_triad: 'त्रिक', col_avg: 'पहले और तीसरे का औसत', col_middle: 'बीच वाले का द्रव्यमान',
    mend_title: 'मेंडलीफ़ की सारणी और आधुनिक आवर्त सारणी', col_point: 'बिंदु', col_mend: 'मेंडलीफ़ (1869)', col_modern: 'आधुनिक (मोज़्ले, 1913)',
    trends_title: 'याद रखने वाले रुझान',
    print_ws: 'वर्कशीट प्रिंट करें', ws_title: 'वर्कशीट: पहले 20 तत्व', ws_line: 'नाम: ______________   कक्षा: ______   तारीख़: __________',
    ws_instr: 'खाली खाने भरें। कोशों से संयोजकता निकालें।', ws_key: 'उत्तर कुंजी'
  },
  bn: {
    app_title: 'পর্যায় সারণি এক্সপ্লোরার',
    intro: 'সব 118টি মৌল জানুন: যেকোনো মৌলে ট্যাপ করে তার ইলেকট্রন বিন্যাস, যোজ্যতা ও বোর মডেল দেখুন, তারপর ছোট কুইজে নিজেকে যাচাই করুন।',
    how_title: 'কীভাবে ব্যবহার করবেন · ক্লাসের জন্য আইডিয়া',
    tab_table: 'পর্যায় সারণি', tab_quiz: 'কুইজ', tab_cbse: 'ক্লাস 9–10 কর্নার',
    search_label: 'মৌল খুঁজুন', search_ph: 'নাম, প্রতীক বা সংখ্যা, যেমন Na, 26, অক্সিজেন',
    n_found: '{n}টি পাওয়া গেছে', no_match: 'কোনো মৌল পাওয়া যায়নি। Fe-র মতো প্রতীক বা 26-এর মতো সংখ্যা লিখে দেখুন।',
    colour_by: 'রং কীসের ভিত্তিতে', by_family: 'পরিবার', by_block: 'ব্লক', by_state: 'অবস্থা',
    highlight: 'আলাদা করে দেখান', hl_all: 'সব দেখান', grp_type: 'ধরন',
    hl_metal: 'ধাতু', hl_nonmetal: 'অধাতু', hl_metalloid: 'অপধাতু', hl_solid: 'কঠিন', hl_liquid: 'তরল', hl_gas: 'গ্যাস', hl_radio: 'তেজস্ক্রিয়', hl_first20: 'প্রথম 20টি মৌল',
    legend_hint: 'কোনো রঙে ট্যাপ করলে সেই দলটি উজ্জ্বল হবে। আবার ট্যাপ করলে সব দেখা যাবে।',
    axis_hint: 'খাড়া কলামগুলি শ্রেণি (1–18)। আড়াআড়ি সারিগুলি পর্যায় (1–7)।',
    pt_aria: '118টি মৌলের পর্যায় সারণি', tile_aria: '{name} ({s}), পারমাণবিক সংখ্যা {n}',
    lanthanoids: 'ল্যান্থানয়েড', actinoids: 'অ্যাক্টিনয়েড',
    cat_alkali: 'ক্ষার ধাতু', cat_alkaline: 'মৃৎক্ষার ধাতু', cat_transition: 'অবস্থান্তর ধাতু', cat_post: 'অন্যান্য ধাতু', cat_metalloid: 'অপধাতু', cat_nonmetal: 'অধাতু', cat_halogen: 'হ্যালোজেন', cat_noble: 'নিষ্ক্রিয় গ্যাস', cat_lanthanoid: 'ল্যান্থানয়েড', cat_actinoid: 'অ্যাক্টিনয়েড',
    block_name: '{b}-ব্লক', state_solid: 'কঠিন', state_liquid: 'তরল', state_gas: 'গ্যাস', state_unknown: 'জানা নেই',
    type_metal: 'ধাতু', type_nonmetal: 'অধাতু', type_metalloid: 'অপধাতু',
    d_number: 'পারমাণবিক সংখ্যা', d_mass: 'পারমাণবিক ভর (u)', d_group: 'শ্রেণি', d_period: 'পর্যায়', d_family: 'পরিবার', d_type: 'ধরন', d_state: 'ঘরের তাপমাত্রায় অবস্থা', d_en: 'তড়িৎ-ঋণাত্মকতা (পলিং)', d_config: 'ইলেকট্রন বিন্যাস', d_full: 'পুরোটা লিখলে', d_shells: 'কক্ষে ইলেকট্রন', d_valence: 'যোজ্যতা ইলেকট্রন', d_valency: 'যোজ্যতা', d_particles: 'পরমাণুর ভেতরে',
    particles_val: '{p}টি প্রোটন, {n}টি নিউট্রন, {e}টি ইলেকট্রন (ভরসংখ্যা {a})',
    not_known: 'জানা নেই', mass_note: '[ ] এর মধ্যে লেখা ভর হলো সবচেয়ে স্থায়ী আইসোটোপের ভরসংখ্যা।', latin_note: 'এর প্রতীক এসেছে লাতিন নাম “{name}” থেকে।',
    radioactive: 'তেজস্ক্রিয়', predicted: 'এর মাত্র কয়েকটি পরমাণু তৈরি হয়েছে, তাই কিছু তথ্য অনুমান।',
    uses_title: 'কোথায় দেখা যায়', hear_name: 'ইংরেজি নাম শুনুন', in_english: 'ইংরেজিতে: {name}',
    bohr_title: 'বোর মডেল', bohr_caption: 'নিউক্লিয়াস: {p}টি প্রোটন ও {n}টি নিউট্রন। কক্ষ: {s}।', bohr_only20: 'ক্লাস 9-এর মতো প্রথম 20টি মৌলের বোর চিত্র আঁকা হয়েছে।',
    featured_hint: 'যেকোনো মৌলে ট্যাপ করুন', print_table: 'সারণি প্রিন্ট করুন',
    quiz_mode: 'প্রশ্নের ধরন', q_sym2name: 'প্রতীক → নাম', q_name2sym: 'নাম → প্রতীক', q_num2sym: 'সংখ্যা → প্রতীক', q_valency: 'যোজ্যতা (প্রথম 20)',
    quiz_range: 'মৌল', range_first: 'প্রথম {n}', range_all: 'সব 118',
    ask_sym2name: '{s} কোন মৌলের প্রতীক?', ask_name2sym: '{name}-এর প্রতীক কী?', ask_num2sym: 'পারমাণবিক সংখ্যা {n} কোন মৌলের?', ask_valency: '{name} ({s})-এর যোজ্যতা কত?',
    q_progress: 'প্রশ্ন {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} মানে {name}, পারমাণবিক সংখ্যা {n}।',
    ex_lose: '{name} ({shells})-এর বাইরের কক্ষে {v}টি ইলেকট্রন আছে। এটি সেগুলি ছেড়ে দেয়, তাই যোজ্যতা {v}।',
    ex_gain: '{name} ({shells})-এর বাইরের কক্ষে {v}টি ইলেকট্রন আছে। 8 পূর্ণ করতে আরও {val}টি লাগে, তাই যোজ্যতা {val}।',
    ex_share: '{name} ({shells})-এর বাইরের কক্ষে {v}টি ইলেকট্রন আছে। এটি সেগুলি ভাগ করে নেয়, তাই যোজ্যতা {v}।',
    ex_full: '{name} ({shells})-এর বাইরের কক্ষ আগে থেকেই পূর্ণ, তাই যোজ্যতা 0।',
    ex_h: 'হাইড্রোজেনে 1টি ইলেকট্রন আছে। এর একমাত্র কক্ষ পূর্ণ করতে আরও 1টি লাগে, তাই যোজ্যতা 1।',
    round_done: 'রাউন্ড শেষ! {n}টির মধ্যে {c}টি ঠিক হয়েছে।', best_score: 'সেরা: {b} / {n}', play_again: 'আবার খেলুন',
    msg_perfect: 'পুরো নম্বর! আপনি পর্যায় সারণির তারকা।', msg_good: 'ভালো হয়েছে! ভুলগুলো দেখে আবার খেলুন।', msg_try: 'অনুশীলন চালিয়ে যান: সারণিতে মৌলগুলি দেখে আবার চেষ্টা করুন।',
    quiz_keys: 'কিবোর্ড: উত্তর দিতে 1–5 টিপুন, পরের প্রশ্নের জন্য Enter।',
    cbse_first20: 'প্রথম 20টি মৌল: কক্ষ ও যোজ্যতা', first20_hint: 'কোনো নামে ট্যাপ করলে মৌলটি সারণিতে খুলবে।',
    col_no: 'ক্রম', col_sym: 'প্রতীক', col_name: 'নাম', col_massno: 'ভরসংখ্যা',
    how_valency_title: 'যোজ্যতা কীভাবে বের করবেন',
    how_valency: 'সবচেয়ে বাইরের কক্ষের ইলেকট্রন গুনুন। 1, 2, 3 বা 4টি হলে যোজ্যতা সেই সংখ্যাই। 5, 6 বা 7টি হলে 8 থেকে সেই সংখ্যা বাদ দিলে যোজ্যতা পাওয়া যায়। কক্ষ পূর্ণ হলে (হিলিয়ামে 2, বাকিদের 8) যোজ্যতা 0।',
    valency_eg: 'উদাহরণ: ক্লোরিন 2, 8, 7। বাইরের কক্ষে 7টি ইলেকট্রন, তাই যোজ্যতা 8 − 7 = 1। সোডিয়ামের (2, 8, 1) যোজ্যতাও 1, তাই খাবার লবণ NaCl।',
    triads_title: 'ডোবেরাইনারের ত্রয়ী', triads_desc: 'একই রকম তিনটি মৌলের প্রতিটি দলে মাঝেরটির ভর বাকি দুটির গড়ের প্রায় সমান।',
    col_triad: 'ত্রয়ী', col_avg: '1ম ও 3য়-এর গড়', col_middle: 'মাঝেরটির ভর',
    mend_title: 'মেন্ডেলিভের সারণি ও আধুনিক পর্যায় সারণি', col_point: 'বিষয়', col_mend: 'মেন্ডেলিভ (1869)', col_modern: 'আধুনিক (মোসলে, 1913)',
    trends_title: 'মনে রাখার মতো প্রবণতা',
    print_ws: 'ওয়ার্কশিট প্রিন্ট করুন', ws_title: 'ওয়ার্কশিট: প্রথম 20টি মৌল', ws_line: 'নাম: ______________   ক্লাস: ______   তারিখ: __________',
    ws_instr: 'খালি ঘরগুলি পূরণ করো। কক্ষ দেখে যোজ্যতা বের করো।', ws_key: 'উত্তরমালা'
  },
  mr: {
    app_title: 'आवर्तसारणी एक्सप्लोरर',
    intro: 'सर्व 118 मूलद्रव्ये जाणून घ्या: कोणत्याही मूलद्रव्यावर टॅप करून त्याचे इलेक्ट्रॉन संरूपण, संयुजा आणि बोर मॉडेल पाहा, मग छोट्या क्विझने स्वतःला तपासा.',
    how_title: 'कसे वापरायचे · वर्गासाठी कल्पना',
    tab_table: 'आवर्तसारणी', tab_quiz: 'क्विझ', tab_cbse: 'इयत्ता 9–10 कोपरा',
    search_label: 'मूलद्रव्य शोधा', search_ph: 'नाव, संज्ञा किंवा क्रमांक, उदा. Na, 26, ऑक्सिजन',
    n_found: '{n} सापडले', no_match: 'कोणतेही मूलद्रव्य सापडले नाही. Fe सारखी संज्ञा किंवा 26 सारखा क्रमांक लिहून पाहा.',
    colour_by: 'रंग कशानुसार', by_family: 'कुटुंब', by_block: 'खंड', by_state: 'अवस्था',
    highlight: 'ठळक करा', hl_all: 'सर्व दाखवा', grp_type: 'प्रकार',
    hl_metal: 'धातू', hl_nonmetal: 'अधातू', hl_metalloid: 'धातुसदृश', hl_solid: 'स्थायू', hl_liquid: 'द्रव', hl_gas: 'वायू', hl_radio: 'किरणोत्सारी', hl_first20: 'पहिली 20 मूलद्रव्ये',
    legend_hint: 'एखाद्या रंगावर टॅप करा, तो गट ठळक होईल. पुन्हा टॅप केल्यावर सर्व दिसतील.',
    axis_hint: 'उभे स्तंभ म्हणजे गण (1–18). आडव्या ओळी म्हणजे आवर्त (1–7).',
    pt_aria: '118 मूलद्रव्यांची आवर्तसारणी', tile_aria: '{name} ({s}), अणुअंक {n}',
    lanthanoids: 'लँथॅनाइड', actinoids: 'ॲक्टिनाइड',
    cat_alkali: 'अल्कली धातू', cat_alkaline: 'अल्कधर्मी मृदा धातू', cat_transition: 'संक्रमण धातू', cat_post: 'इतर धातू', cat_metalloid: 'धातुसदृश', cat_nonmetal: 'अधातू', cat_halogen: 'हॅलोजन', cat_noble: 'राजवायू', cat_lanthanoid: 'लँथॅनाइड', cat_actinoid: 'ॲक्टिनाइड',
    block_name: '{b}-खंड', state_solid: 'स्थायू', state_liquid: 'द्रव', state_gas: 'वायू', state_unknown: 'माहीत नाही',
    type_metal: 'धातू', type_nonmetal: 'अधातू', type_metalloid: 'धातुसदृश',
    d_number: 'अणुअंक', d_mass: 'अणुवस्तुमान (u)', d_group: 'गण', d_period: 'आवर्त', d_family: 'कुटुंब', d_type: 'प्रकार', d_state: 'खोलीच्या तापमानाला अवस्था', d_en: 'विद्युतऋणता (पॉलिंग)', d_config: 'इलेक्ट्रॉन संरूपण', d_full: 'पूर्ण लिहिल्यास', d_shells: 'कवचांमधील इलेक्ट्रॉन', d_valence: 'संयुजा इलेक्ट्रॉन', d_valency: 'संयुजा', d_particles: 'अणूच्या आत',
    particles_val: '{p} प्रोटॉन, {n} न्यूट्रॉन, {e} इलेक्ट्रॉन (अणुवस्तुमानांक {a})',
    not_known: 'माहीत नाही', mass_note: '[ ] मधील वस्तुमान हे सर्वात स्थिर समस्थानिकाचा अणुवस्तुमानांक आहे.', latin_note: 'याची संज्ञा लॅटिन नाव “{name}” वरून आली आहे.',
    radioactive: 'किरणोत्सारी', predicted: 'याचे आजवर फक्त काही अणू तयार झाले आहेत, म्हणून काही माहिती अंदाजावर आधारित आहे.',
    uses_title: 'हे आपल्याला कुठे भेटते', hear_name: 'इंग्रजी नाव ऐका', in_english: 'इंग्रजीत: {name}',
    bohr_title: 'बोर मॉडेल', bohr_caption: 'केंद्रक: {p} प्रोटॉन आणि {n} न्यूट्रॉन. कवचे: {s}.', bohr_only20: 'इयत्ता 9 प्रमाणे पहिल्या 20 मूलद्रव्यांसाठी बोर आकृत्या काढल्या आहेत.',
    featured_hint: 'कोणत्याही मूलद्रव्यावर टॅप करा', print_table: 'सारणी प्रिंट करा',
    quiz_mode: 'प्रश्नाचा प्रकार', q_sym2name: 'संज्ञा → नाव', q_name2sym: 'नाव → संज्ञा', q_num2sym: 'अंक → संज्ञा', q_valency: 'संयुजा (पहिली 20)',
    quiz_range: 'मूलद्रव्ये', range_first: 'पहिली {n}', range_all: 'सर्व 118',
    ask_sym2name: '{s} ही कोणत्या मूलद्रव्याची संज्ञा आहे?', ask_name2sym: '{name} ची संज्ञा काय आहे?', ask_num2sym: 'अणुअंक {n} असलेले मूलद्रव्य कोणते?', ask_valency: '{name} ({s}) ची संयुजा किती?',
    q_progress: 'प्रश्न {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} म्हणजे {name}, अणुअंक {n}.',
    ex_lose: '{name} ({shells}) च्या बाह्य कवचात {v} इलेक्ट्रॉन आहेत. ते हे देऊन टाकते, म्हणून संयुजा {v}.',
    ex_gain: '{name} ({shells}) च्या बाह्य कवचात {v} इलेक्ट्रॉन आहेत. 8 पूर्ण करण्यासाठी आणखी {val} लागतात, म्हणून संयुजा {val}.',
    ex_share: '{name} ({shells}) च्या बाह्य कवचात {v} इलेक्ट्रॉन आहेत. ते हे वाटून घेते, म्हणून संयुजा {v}.',
    ex_full: '{name} ({shells}) चे बाह्य कवच आधीच पूर्ण आहे, म्हणून संयुजा 0.',
    ex_h: 'हायड्रोजनमध्ये 1 इलेक्ट्रॉन आहे. त्याचे एकमेव कवच पूर्ण होण्यासाठी आणखी 1 लागतो, म्हणून संयुजा 1.',
    round_done: 'फेरी संपली! {n} पैकी {c} बरोबर.', best_score: 'सर्वोत्तम: {b} / {n}', play_again: 'पुन्हा खेळा',
    msg_perfect: 'पैकीच्या पैकी! तुम्ही आवर्तसारणीचे स्टार आहात.', msg_good: 'छान! चुका पाहा आणि पुन्हा खेळा.', msg_try: 'सराव करत राहा: सारणीतील मूलद्रव्ये पाहा आणि पुन्हा प्रयत्न करा.',
    quiz_keys: 'कीबोर्ड: उत्तरासाठी 1–5 दाबा आणि पुढच्या प्रश्नासाठी Enter.',
    cbse_first20: 'पहिली 20 मूलद्रव्ये: कवचे आणि संयुजा', first20_hint: 'नावावर टॅप केल्यास ते मूलद्रव्य सारणीत उघडेल.',
    col_no: 'क्र.', col_sym: 'संज्ञा', col_name: 'नाव', col_massno: 'अणुवस्तुमानांक',
    how_valency_title: 'संयुजा कशी काढायची',
    how_valency: 'सर्वात बाहेरच्या कवचातील इलेक्ट्रॉन मोजा. ते 1, 2, 3 किंवा 4 असतील तर संयुजा तीच संख्या. 5, 6 किंवा 7 असतील तर 8 मधून ती संख्या वजा केल्यावर संयुजा मिळते. कवच पूर्ण असेल (हेलियमसाठी 2, इतरांसाठी 8) तर संयुजा 0.',
    valency_eg: 'उदाहरण: क्लोरिन 2, 8, 7 आहे. बाह्य कवचात 7 इलेक्ट्रॉन, म्हणून संयुजा 8 − 7 = 1. सोडियमची (2, 8, 1) संयुजाही 1, म्हणून मीठ म्हणजे NaCl.',
    triads_title: 'डोबरायनरची त्रिके', triads_desc: 'तीन सारख्या मूलद्रव्यांच्या प्रत्येक गटात मधल्याचे वस्तुमान इतर दोघांच्या सरासरीइतके असते.',
    col_triad: 'त्रिक', col_avg: 'पहिल्या व तिसऱ्याची सरासरी', col_middle: 'मधल्याचे वस्तुमान',
    mend_title: 'मेंडेलीव्हची सारणी आणि आधुनिक आवर्तसारणी', col_point: 'मुद्दा', col_mend: 'मेंडेलीव्ह (1869)', col_modern: 'आधुनिक (मोसले, 1913)',
    trends_title: 'लक्षात ठेवण्याचे कल',
    print_ws: 'वर्कशीट प्रिंट करा', ws_title: 'वर्कशीट: पहिली 20 मूलद्रव्ये', ws_line: 'नाव: ______________   इयत्ता: ______   दिनांक: __________',
    ws_instr: 'रिकाम्या जागा भरा. कवचांवरून संयुजा काढा.', ws_key: 'उत्तरसूची'
  },
  gu: {
    app_title: 'આવર્ત કોષ્ટક એક્સપ્લોરર',
    intro: 'બધાં 118 તત્ત્વો જાણો: કોઈ પણ તત્ત્વ પર ટૅપ કરીને તેની ઇલેક્ટ્રૉન રચના, સંયોજકતા અને બોર મૉડલ જુઓ, પછી નાની ક્વિઝથી પોતાને ચકાસો.',
    how_title: 'કેવી રીતે વાપરવું · વર્ગ માટે વિચારો',
    tab_table: 'આવર્ત કોષ્ટક', tab_quiz: 'ક્વિઝ', tab_cbse: 'ધોરણ 9–10 ખૂણો',
    search_label: 'તત્ત્વ શોધો', search_ph: 'નામ, સંજ્ઞા કે ક્રમાંક, જેમ કે Na, 26, ઑક્સિજન',
    n_found: '{n} મળ્યાં', no_match: 'કોઈ તત્ત્વ ન મળ્યું. Fe જેવી સંજ્ઞા કે 26 જેવો ક્રમાંક લખી જુઓ.',
    colour_by: 'રંગ શેના આધારે', by_family: 'કુટુંબ', by_block: 'બ્લૉક', by_state: 'અવસ્થા',
    highlight: 'ઉજાગર કરો', hl_all: 'બધું બતાવો', grp_type: 'પ્રકાર',
    hl_metal: 'ધાતુઓ', hl_nonmetal: 'અધાતુઓ', hl_metalloid: 'અર્ધધાતુઓ', hl_solid: 'ઘન', hl_liquid: 'પ્રવાહી', hl_gas: 'વાયુ', hl_radio: 'રેડિયોઍક્ટિવ', hl_first20: 'પ્રથમ 20 તત્ત્વો',
    legend_hint: 'કોઈ રંગ પર ટૅપ કરો, તે જૂથ ઉજાગર થશે. ફરી ટૅપ કરશો તો બધું દેખાશે.',
    axis_hint: 'ઊભા સ્તંભ સમૂહ છે (1–18). આડી હરોળ આવર્ત છે (1–7).',
    pt_aria: '118 તત્ત્વોનું આવર્ત કોષ્ટક', tile_aria: '{name} ({s}), પરમાણુ ક્રમાંક {n}',
    lanthanoids: 'લેન્થેનોઇડ', actinoids: 'ઍક્ટિનોઇડ',
    cat_alkali: 'આલ્કલી ધાતુ', cat_alkaline: 'આલ્કલાઇન અર્થ ધાતુ', cat_transition: 'સંક્રાંતિ ધાતુ', cat_post: 'અન્ય ધાતુ', cat_metalloid: 'અર્ધધાતુ', cat_nonmetal: 'અધાતુ', cat_halogen: 'હેલોજન', cat_noble: 'નિષ્ક્રિય વાયુ', cat_lanthanoid: 'લેન્થેનોઇડ', cat_actinoid: 'ઍક્ટિનોઇડ',
    block_name: '{b}-બ્લૉક', state_solid: 'ઘન', state_liquid: 'પ્રવાહી', state_gas: 'વાયુ', state_unknown: 'ખબર નથી',
    type_metal: 'ધાતુ', type_nonmetal: 'અધાતુ', type_metalloid: 'અર્ધધાતુ',
    d_number: 'પરમાણુ ક્રમાંક', d_mass: 'પરમાણુ દળ (u)', d_group: 'સમૂહ', d_period: 'આવર્ત', d_family: 'કુટુંબ', d_type: 'પ્રકાર', d_state: 'ઓરડાના તાપમાને અવસ્થા', d_en: 'વિદ્યુતઋણતા (પૉલિંગ)', d_config: 'ઇલેક્ટ્રૉન રચના', d_full: 'પૂરું લખીએ તો', d_shells: 'કક્ષામાં ઇલેક્ટ્રૉન', d_valence: 'સંયોજકતા ઇલેક્ટ્રૉન', d_valency: 'સંયોજકતા', d_particles: 'પરમાણુની અંદર',
    particles_val: '{p} પ્રોટૉન, {n} ન્યૂટ્રૉન, {e} ઇલેક્ટ્રૉન (દળાંક {a})',
    not_known: 'ખબર નથી', mass_note: '[ ] માં લખેલું દળ સૌથી સ્થાયી સમસ્થાનિકનો દળાંક છે.', latin_note: 'તેની સંજ્ઞા લેટિન નામ “{name}” પરથી આવી છે.',
    radioactive: 'રેડિયોઍક્ટિવ', predicted: 'તેના અત્યાર સુધી થોડા જ પરમાણુ બન્યા છે, એટલે કેટલીક માહિતી અનુમાન છે.',
    uses_title: 'તે આપણને ક્યાં મળે છે', hear_name: 'અંગ્રેજી નામ સાંભળો', in_english: 'અંગ્રેજીમાં: {name}',
    bohr_title: 'બોર મૉડલ', bohr_caption: 'કેન્દ્ર: {p} પ્રોટૉન અને {n} ન્યૂટ્રૉન. કક્ષાઓ: {s}.', bohr_only20: 'ધોરણ 9 ની જેમ પ્રથમ 20 તત્ત્વો માટે બોર આકૃતિ દોરેલી છે.',
    featured_hint: 'કોઈ પણ તત્ત્વ પર ટૅપ કરો', print_table: 'કોષ્ટક પ્રિન્ટ કરો',
    quiz_mode: 'પ્રશ્નનો પ્રકાર', q_sym2name: 'સંજ્ઞા → નામ', q_name2sym: 'નામ → સંજ્ઞા', q_num2sym: 'ક્રમાંક → સંજ્ઞા', q_valency: 'સંયોજકતા (પ્રથમ 20)',
    quiz_range: 'તત્ત્વો', range_first: 'પ્રથમ {n}', range_all: 'બધાં 118',
    ask_sym2name: '{s} કયા તત્ત્વની સંજ્ઞા છે?', ask_name2sym: '{name} ની સંજ્ઞા શું છે?', ask_num2sym: 'પરમાણુ ક્રમાંક {n} કયા તત્ત્વનો છે?', ask_valency: '{name} ({s}) ની સંયોજકતા કેટલી છે?',
    q_progress: 'પ્રશ્ન {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} એટલે {name}, પરમાણુ ક્રમાંક {n}.',
    ex_lose: '{name} ({shells}) ની બહારની કક્ષામાં {v} ઇલેક્ટ્રૉન છે. તે આ આપી દે છે, એટલે સંયોજકતા {v} છે.',
    ex_gain: '{name} ({shells}) ની બહારની કક્ષામાં {v} ઇલેક્ટ્રૉન છે. 8 પૂરા કરવા તેને બીજા {val} જોઈએ, એટલે સંયોજકતા {val} છે.',
    ex_share: '{name} ({shells}) ની બહારની કક્ષામાં {v} ઇલેક્ટ્રૉન છે. તે આ વહેંચે છે, એટલે સંયોજકતા {v} છે.',
    ex_full: '{name} ({shells}) ની બહારની કક્ષા પહેલેથી ભરેલી છે, એટલે સંયોજકતા 0 છે.',
    ex_h: 'હાઇડ્રોજનમાં 1 ઇલેક્ટ્રૉન છે. તેની એકમાત્ર કક્ષા ભરવા બીજો 1 જોઈએ, એટલે સંયોજકતા 1 છે.',
    round_done: 'રાઉન્ડ પૂરો! {n} માંથી {c} સાચા.', best_score: 'શ્રેષ્ઠ: {b} / {n}', play_again: 'ફરી રમો',
    msg_perfect: 'પૂરા ગુણ! તમે આવર્ત કોષ્ટકના સ્ટાર છો.', msg_good: 'સરસ! ભૂલો જુઓ અને ફરી રમો.', msg_try: 'પ્રેક્ટિસ ચાલુ રાખો: કોષ્ટકમાં તત્ત્વો જુઓ, પછી ફરી પ્રયાસ કરો.',
    quiz_keys: 'કીબોર્ડ: જવાબ માટે 1–5 દબાવો અને આગલા પ્રશ્ન માટે Enter.',
    cbse_first20: 'પ્રથમ 20 તત્ત્વો: કક્ષાઓ અને સંયોજકતા', first20_hint: 'નામ પર ટૅપ કરશો તો તે તત્ત્વ કોષ્ટકમાં ખૂલશે.',
    col_no: 'ક્રમ', col_sym: 'સંજ્ઞા', col_name: 'નામ', col_massno: 'દળાંક',
    how_valency_title: 'સંયોજકતા કેવી રીતે શોધવી',
    how_valency: 'સૌથી બહારની કક્ષાના ઇલેક્ટ્રૉન ગણો. જો 1, 2, 3 કે 4 હોય તો સંયોજકતા એ જ સંખ્યા. જો 5, 6 કે 7 હોય તો 8 માંથી એ સંખ્યા બાદ કરતાં સંયોજકતા મળે. કક્ષા ભરેલી હોય (હિલિયમમાં 2, બાકીમાં 8) તો સંયોજકતા 0.',
    valency_eg: 'ઉદાહરણ: ક્લોરિન 2, 8, 7 છે. બહારની કક્ષામાં 7 ઇલેક્ટ્રૉન, એટલે સંયોજકતા 8 − 7 = 1. સોડિયમ (2, 8, 1) ની સંયોજકતા પણ 1, એટલે મીઠું NaCl છે.',
    triads_title: 'ડોબરેનરની ત્રિપુટી', triads_desc: 'ત્રણ સરખાં તત્ત્વોના દરેક જૂથમાં વચ્ચેના તત્ત્વનું દળ બાકીનાં બેની સરેરાશ જેટલું હોય છે.',
    col_triad: 'ત્રિપુટી', col_avg: 'પહેલા અને ત્રીજાની સરેરાશ', col_middle: 'વચ્ચેનાનું દળ',
    mend_title: 'મેન્ડેલીફનું કોષ્ટક અને આધુનિક આવર્ત કોષ્ટક', col_point: 'મુદ્દો', col_mend: 'મેન્ડેલીફ (1869)', col_modern: 'આધુનિક (મોસ્લે, 1913)',
    trends_title: 'યાદ રાખવાના વલણો',
    print_ws: 'વર્કશીટ પ્રિન્ટ કરો', ws_title: 'વર્કશીટ: પ્રથમ 20 તત્ત્વો', ws_line: 'નામ: ______________   ધોરણ: ______   તારીખ: __________',
    ws_instr: 'ખાલી ખાનાં ભરો. કક્ષાઓ પરથી સંયોજકતા શોધો.', ws_key: 'જવાબ ચાવી'
  },
  pa: {
    app_title: 'ਆਵਰਤੀ ਸਾਰਣੀ ਐਕਸਪਲੋਰਰ',
    intro: 'ਸਾਰੇ 118 ਤੱਤਾਂ ਨੂੰ ਜਾਣੋ: ਕਿਸੇ ਵੀ ਤੱਤ ’ਤੇ ਟੈਪ ਕਰਕੇ ਉਸਦੀ ਇਲੈਕਟ੍ਰਾਨ ਤਰਤੀਬ, ਸੰਯੋਜਕਤਾ ਅਤੇ ਬੋਰ ਮਾਡਲ ਦੇਖੋ, ਫਿਰ ਛੋਟੇ ਕੁਇਜ਼ ਨਾਲ ਆਪਣੇ ਆਪ ਨੂੰ ਪਰਖੋ।',
    how_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ · ਜਮਾਤ ਲਈ ਸੁਝਾਅ',
    tab_table: 'ਆਵਰਤੀ ਸਾਰਣੀ', tab_quiz: 'ਕੁਇਜ਼', tab_cbse: 'ਜਮਾਤ 9–10 ਕੋਨਾ',
    search_label: 'ਤੱਤ ਲੱਭੋ', search_ph: 'ਨਾਮ, ਨਿਸ਼ਾਨ ਜਾਂ ਸੰਖਿਆ, ਜਿਵੇਂ Na, 26, ਆਕਸੀਜਨ',
    n_found: '{n} ਮਿਲੇ', no_match: 'ਕੋਈ ਤੱਤ ਨਹੀਂ ਮਿਲਿਆ। Fe ਵਰਗਾ ਨਿਸ਼ਾਨ ਜਾਂ 26 ਵਰਗੀ ਸੰਖਿਆ ਲਿਖ ਕੇ ਦੇਖੋ।',
    colour_by: 'ਰੰਗ ਕਿਸ ਆਧਾਰ ’ਤੇ', by_family: 'ਪਰਿਵਾਰ', by_block: 'ਬਲਾਕ', by_state: 'ਅਵਸਥਾ',
    highlight: 'ਉਭਾਰੋ', hl_all: 'ਸਭ ਦਿਖਾਓ', grp_type: 'ਕਿਸਮ',
    hl_metal: 'ਧਾਤਾਂ', hl_nonmetal: 'ਅਧਾਤਾਂ', hl_metalloid: 'ਉਪਧਾਤਾਂ', hl_solid: 'ਠੋਸ', hl_liquid: 'ਤਰਲ', hl_gas: 'ਗੈਸਾਂ', hl_radio: 'ਰੇਡੀਓਐਕਟਿਵ', hl_first20: 'ਪਹਿਲੇ 20 ਤੱਤ',
    legend_hint: 'ਕਿਸੇ ਰੰਗ ’ਤੇ ਟੈਪ ਕਰੋ, ਉਹ ਸਮੂਹ ਉੱਭਰ ਜਾਵੇਗਾ। ਦੁਬਾਰਾ ਟੈਪ ਕਰਨ ’ਤੇ ਸਭ ਦਿਖਣਗੇ।',
    axis_hint: 'ਖੜ੍ਹੇ ਕਾਲਮ ਗਰੁੱਪ ਹਨ (1–18)। ਲੇਟਵੀਆਂ ਕਤਾਰਾਂ ਪੀਰੀਅਡ ਹਨ (1–7)।',
    pt_aria: '118 ਤੱਤਾਂ ਦੀ ਆਵਰਤੀ ਸਾਰਣੀ', tile_aria: '{name} ({s}), ਪਰਮਾਣੂ ਸੰਖਿਆ {n}',
    lanthanoids: 'ਲੈਂਥੇਨਾਇਡ', actinoids: 'ਐਕਟੀਨਾਇਡ',
    cat_alkali: 'ਖਾਰੀ ਧਾਤ', cat_alkaline: 'ਖਾਰੀ ਭੌਂ ਧਾਤ', cat_transition: 'ਸੰਕ੍ਰਮਣ ਧਾਤ', cat_post: 'ਹੋਰ ਧਾਤ', cat_metalloid: 'ਉਪਧਾਤ', cat_nonmetal: 'ਅਧਾਤ', cat_halogen: 'ਹੈਲੋਜਨ', cat_noble: 'ਉੱਤਮ ਗੈਸ', cat_lanthanoid: 'ਲੈਂਥੇਨਾਇਡ', cat_actinoid: 'ਐਕਟੀਨਾਇਡ',
    block_name: '{b}-ਬਲਾਕ', state_solid: 'ਠੋਸ', state_liquid: 'ਤਰਲ', state_gas: 'ਗੈਸ', state_unknown: 'ਪਤਾ ਨਹੀਂ',
    type_metal: 'ਧਾਤ', type_nonmetal: 'ਅਧਾਤ', type_metalloid: 'ਉਪਧਾਤ',
    d_number: 'ਪਰਮਾਣੂ ਸੰਖਿਆ', d_mass: 'ਪਰਮਾਣੂ ਪੁੰਜ (u)', d_group: 'ਗਰੁੱਪ', d_period: 'ਪੀਰੀਅਡ', d_family: 'ਪਰਿਵਾਰ', d_type: 'ਕਿਸਮ', d_state: 'ਕਮਰੇ ਦੇ ਤਾਪਮਾਨ ’ਤੇ ਅਵਸਥਾ', d_en: 'ਬਿਜਲਈ ਰਿਣਾਤਮਕਤਾ (ਪੌਲਿੰਗ)', d_config: 'ਇਲੈਕਟ੍ਰਾਨ ਤਰਤੀਬ', d_full: 'ਪੂਰਾ ਲਿਖੀਏ ਤਾਂ', d_shells: 'ਸ਼ੈੱਲਾਂ ਵਿੱਚ ਇਲੈਕਟ੍ਰਾਨ', d_valence: 'ਸੰਯੋਜਕ ਇਲੈਕਟ੍ਰਾਨ', d_valency: 'ਸੰਯੋਜਕਤਾ', d_particles: 'ਪਰਮਾਣੂ ਦੇ ਅੰਦਰ',
    particles_val: '{p} ਪ੍ਰੋਟਾਨ, {n} ਨਿਊਟ੍ਰਾਨ, {e} ਇਲੈਕਟ੍ਰਾਨ (ਪੁੰਜ ਸੰਖਿਆ {a})',
    not_known: 'ਪਤਾ ਨਹੀਂ', mass_note: '[ ] ਵਿੱਚ ਲਿਖਿਆ ਪੁੰਜ ਸਭ ਤੋਂ ਸਥਿਰ ਆਈਸੋਟੋਪ ਦੀ ਪੁੰਜ ਸੰਖਿਆ ਹੈ।', latin_note: 'ਇਸਦਾ ਨਿਸ਼ਾਨ ਲਾਤੀਨੀ ਨਾਮ “{name}” ਤੋਂ ਆਇਆ ਹੈ।',
    radioactive: 'ਰੇਡੀਓਐਕਟਿਵ', predicted: 'ਇਸਦੇ ਹੁਣ ਤੱਕ ਕੁਝ ਹੀ ਪਰਮਾਣੂ ਬਣੇ ਹਨ, ਇਸ ਲਈ ਕੁਝ ਗੱਲਾਂ ਅੰਦਾਜ਼ੇ ਹਨ।',
    uses_title: 'ਇਹ ਸਾਨੂੰ ਕਿੱਥੇ ਮਿਲਦਾ ਹੈ', hear_name: 'ਅੰਗਰੇਜ਼ੀ ਨਾਮ ਸੁਣੋ', in_english: 'ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ: {name}',
    bohr_title: 'ਬੋਰ ਮਾਡਲ', bohr_caption: 'ਨਿਊਕਲੀਅਸ: {p} ਪ੍ਰੋਟਾਨ ਅਤੇ {n} ਨਿਊਟ੍ਰਾਨ। ਸ਼ੈੱਲ: {s}।', bohr_only20: 'ਜਮਾਤ 9 ਵਾਂਗ ਪਹਿਲੇ 20 ਤੱਤਾਂ ਲਈ ਬੋਰ ਚਿੱਤਰ ਬਣਾਏ ਗਏ ਹਨ।',
    featured_hint: 'ਕਿਸੇ ਵੀ ਤੱਤ ’ਤੇ ਟੈਪ ਕਰੋ', print_table: 'ਸਾਰਣੀ ਪ੍ਰਿੰਟ ਕਰੋ',
    quiz_mode: 'ਪ੍ਰਸ਼ਨ ਦੀ ਕਿਸਮ', q_sym2name: 'ਨਿਸ਼ਾਨ → ਨਾਮ', q_name2sym: 'ਨਾਮ → ਨਿਸ਼ਾਨ', q_num2sym: 'ਸੰਖਿਆ → ਨਿਸ਼ਾਨ', q_valency: 'ਸੰਯੋਜਕਤਾ (ਪਹਿਲੇ 20)',
    quiz_range: 'ਤੱਤ', range_first: 'ਪਹਿਲੇ {n}', range_all: 'ਸਾਰੇ 118',
    ask_sym2name: '{s} ਕਿਸ ਤੱਤ ਦਾ ਨਿਸ਼ਾਨ ਹੈ?', ask_name2sym: '{name} ਦਾ ਨਿਸ਼ਾਨ ਕੀ ਹੈ?', ask_num2sym: 'ਪਰਮਾਣੂ ਸੰਖਿਆ {n} ਕਿਸ ਤੱਤ ਦੀ ਹੈ?', ask_valency: '{name} ({s}) ਦੀ ਸੰਯੋਜਕਤਾ ਕੀ ਹੈ?',
    q_progress: 'ਪ੍ਰਸ਼ਨ {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} ਮਤਲਬ {name}, ਪਰਮਾਣੂ ਸੰਖਿਆ {n}।',
    ex_lose: '{name} ({shells}) ਦੇ ਬਾਹਰੀ ਸ਼ੈੱਲ ਵਿੱਚ {v} ਇਲੈਕਟ੍ਰਾਨ ਹਨ। ਇਹ ਇਨ੍ਹਾਂ ਨੂੰ ਦੇ ਦਿੰਦਾ ਹੈ, ਇਸ ਲਈ ਸੰਯੋਜਕਤਾ {v} ਹੈ।',
    ex_gain: '{name} ({shells}) ਦੇ ਬਾਹਰੀ ਸ਼ੈੱਲ ਵਿੱਚ {v} ਇਲੈਕਟ੍ਰਾਨ ਹਨ। 8 ਪੂਰੇ ਕਰਨ ਲਈ ਇਸਨੂੰ {val} ਹੋਰ ਚਾਹੀਦੇ ਹਨ, ਇਸ ਲਈ ਸੰਯੋਜਕਤਾ {val} ਹੈ।',
    ex_share: '{name} ({shells}) ਦੇ ਬਾਹਰੀ ਸ਼ੈੱਲ ਵਿੱਚ {v} ਇਲੈਕਟ੍ਰਾਨ ਹਨ। ਇਹ ਇਨ੍ਹਾਂ ਨੂੰ ਸਾਂਝਾ ਕਰਦਾ ਹੈ, ਇਸ ਲਈ ਸੰਯੋਜਕਤਾ {v} ਹੈ।',
    ex_full: '{name} ({shells}) ਦਾ ਬਾਹਰੀ ਸ਼ੈੱਲ ਪਹਿਲਾਂ ਹੀ ਭਰਿਆ ਹੈ, ਇਸ ਲਈ ਸੰਯੋਜਕਤਾ 0 ਹੈ।',
    ex_h: 'ਹਾਈਡ੍ਰੋਜਨ ਵਿੱਚ 1 ਇਲੈਕਟ੍ਰਾਨ ਹੈ। ਇਸਦੇ ਇੱਕੋ ਸ਼ੈੱਲ ਨੂੰ ਭਰਨ ਲਈ 1 ਹੋਰ ਚਾਹੀਦਾ ਹੈ, ਇਸ ਲਈ ਸੰਯੋਜਕਤਾ 1 ਹੈ।',
    round_done: 'ਰਾਊਂਡ ਪੂਰਾ! {n} ਵਿੱਚੋਂ {c} ਸਹੀ।', best_score: 'ਸਭ ਤੋਂ ਵਧੀਆ: {b} / {n}', play_again: 'ਫਿਰ ਖੇਡੋ',
    msg_perfect: 'ਪੂਰੇ ਅੰਕ! ਤੁਸੀਂ ਆਵਰਤੀ ਸਾਰਣੀ ਦੇ ਸਟਾਰ ਹੋ।', msg_good: 'ਸ਼ਾਬਾਸ਼! ਗ਼ਲਤੀਆਂ ਦੇਖੋ ਅਤੇ ਫਿਰ ਖੇਡੋ।', msg_try: 'ਅਭਿਆਸ ਜਾਰੀ ਰੱਖੋ: ਸਾਰਣੀ ਵਿੱਚ ਤੱਤ ਦੇਖੋ, ਫਿਰ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    quiz_keys: 'ਕੀਬੋਰਡ: ਜਵਾਬ ਲਈ 1–5 ਦਬਾਓ ਅਤੇ ਅਗਲੇ ਪ੍ਰਸ਼ਨ ਲਈ Enter।',
    cbse_first20: 'ਪਹਿਲੇ 20 ਤੱਤ: ਸ਼ੈੱਲ ਅਤੇ ਸੰਯੋਜਕਤਾ', first20_hint: 'ਕਿਸੇ ਨਾਮ ’ਤੇ ਟੈਪ ਕਰੋ, ਉਹ ਤੱਤ ਸਾਰਣੀ ਵਿੱਚ ਖੁੱਲ੍ਹ ਜਾਵੇਗਾ।',
    col_no: 'ਕ੍ਰਮ', col_sym: 'ਨਿਸ਼ਾਨ', col_name: 'ਨਾਮ', col_massno: 'ਪੁੰਜ ਸੰਖਿਆ',
    how_valency_title: 'ਸੰਯੋਜਕਤਾ ਕਿਵੇਂ ਲੱਭੀਏ',
    how_valency: 'ਸਭ ਤੋਂ ਬਾਹਰਲੇ ਸ਼ੈੱਲ ਦੇ ਇਲੈਕਟ੍ਰਾਨ ਗਿਣੋ। ਜੇ 1, 2, 3 ਜਾਂ 4 ਹਨ ਤਾਂ ਸੰਯੋਜਕਤਾ ਉਹੀ ਸੰਖਿਆ ਹੈ। ਜੇ 5, 6 ਜਾਂ 7 ਹਨ ਤਾਂ 8 ਵਿੱਚੋਂ ਉਹ ਸੰਖਿਆ ਘਟਾ ਕੇ ਸੰਯੋਜਕਤਾ ਮਿਲਦੀ ਹੈ। ਸ਼ੈੱਲ ਭਰਿਆ ਹੋਵੇ (ਹੀਲੀਅਮ ਵਿੱਚ 2, ਬਾਕੀਆਂ ਵਿੱਚ 8) ਤਾਂ ਸੰਯੋਜਕਤਾ 0 ਹੈ।',
    valency_eg: 'ਉਦਾਹਰਨ: ਕਲੋਰੀਨ 2, 8, 7 ਹੈ। ਬਾਹਰੀ ਸ਼ੈੱਲ ਵਿੱਚ 7 ਇਲੈਕਟ੍ਰਾਨ, ਇਸ ਲਈ ਸੰਯੋਜਕਤਾ 8 − 7 = 1। ਸੋਡੀਅਮ (2, 8, 1) ਦੀ ਸੰਯੋਜਕਤਾ ਵੀ 1 ਹੈ, ਇਸ ਲਈ ਲੂਣ NaCl ਹੈ।',
    triads_title: 'ਡੋਬਰਾਈਨਰ ਦੇ ਤ੍ਰਿਕ', triads_desc: 'ਤਿੰਨ ਮਿਲਦੇ-ਜੁਲਦੇ ਤੱਤਾਂ ਦੇ ਹਰ ਸਮੂਹ ਵਿੱਚ ਵਿਚਕਾਰਲੇ ਤੱਤ ਦਾ ਪੁੰਜ ਬਾਕੀ ਦੋਵਾਂ ਦੀ ਔਸਤ ਦੇ ਲਗਭਗ ਬਰਾਬਰ ਹੁੰਦਾ ਹੈ।',
    col_triad: 'ਤ੍ਰਿਕ', col_avg: 'ਪਹਿਲੇ ਅਤੇ ਤੀਜੇ ਦੀ ਔਸਤ', col_middle: 'ਵਿਚਕਾਰਲੇ ਦਾ ਪੁੰਜ',
    mend_title: 'ਮੈਂਡਲੀਫ਼ ਦੀ ਸਾਰਣੀ ਅਤੇ ਆਧੁਨਿਕ ਆਵਰਤੀ ਸਾਰਣੀ', col_point: 'ਨੁਕਤਾ', col_mend: 'ਮੈਂਡਲੀਫ਼ (1869)', col_modern: 'ਆਧੁਨਿਕ (ਮੋਜ਼ਲੇ, 1913)',
    trends_title: 'ਯਾਦ ਰੱਖਣ ਵਾਲੇ ਰੁਝਾਨ',
    print_ws: 'ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ', ws_title: 'ਵਰਕਸ਼ੀਟ: ਪਹਿਲੇ 20 ਤੱਤ', ws_line: 'ਨਾਮ: ______________   ਜਮਾਤ: ______   ਮਿਤੀ: __________',
    ws_instr: 'ਖਾਲੀ ਖਾਨੇ ਭਰੋ। ਸ਼ੈੱਲਾਂ ਤੋਂ ਸੰਯੋਜਕਤਾ ਲੱਭੋ।', ws_key: 'ਉੱਤਰ ਕੁੰਜੀ'
  },
  or: {
    app_title: 'ପର୍ଯ୍ୟାୟ ସାରଣୀ ଏକ୍ସପ୍ଲୋରର',
    intro: 'ସମସ୍ତ 118ଟି ମୌଳିକ ଜାଣନ୍ତୁ: ଯେକୌଣସି ମୌଳିକରେ ଟ୍ୟାପ୍ କରି ତାର ଇଲେକ୍ଟ୍ରନ ବିନ୍ୟାସ, ଯୋଜ୍ୟତା ଓ ବୋର ମଡେଲ ଦେଖନ୍ତୁ, ତାପରେ ଛୋଟ କୁଇଜରେ ନିଜକୁ ପରଖନ୍ତୁ।',
    how_title: 'କିପରି ବ୍ୟବହାର କରିବେ · ଶ୍ରେଣୀ ପାଇଁ ପରାମର୍ଶ',
    tab_table: 'ପର୍ଯ୍ୟାୟ ସାରଣୀ', tab_quiz: 'କୁଇଜ୍', tab_cbse: 'ଶ୍ରେଣୀ 9–10 କୋଣ',
    search_label: 'ମୌଳିକ ଖୋଜନ୍ତୁ', search_ph: 'ନାମ, ସଙ୍କେତ ବା ସଂଖ୍ୟା, ଯେପରି Na, 26, ଅକ୍ସିଜେନ',
    n_found: '{n}ଟି ମିଳିଲା', no_match: 'କୌଣସି ମୌଳିକ ମିଳିଲା ନାହିଁ। Fe ପରି ସଙ୍କେତ ବା 26 ପରି ସଂଖ୍ୟା ଲେଖି ଦେଖନ୍ତୁ।',
    colour_by: 'ରଙ୍ଗ କେଉଁ ଆଧାରରେ', by_family: 'ପରିବାର', by_block: 'ବ୍ଲକ୍', by_state: 'ଅବସ୍ଥା',
    highlight: 'ଉଜ୍ଜ୍ୱଳ କରନ୍ତୁ', hl_all: 'ସବୁ ଦେଖାନ୍ତୁ', grp_type: 'ପ୍ରକାର',
    hl_metal: 'ଧାତୁ', hl_nonmetal: 'ଅଧାତୁ', hl_metalloid: 'ଉପଧାତୁ', hl_solid: 'କଠିନ', hl_liquid: 'ତରଳ', hl_gas: 'ଗ୍ୟାସ୍', hl_radio: 'ତେଜସ୍କ୍ରିୟ', hl_first20: 'ପ୍ରଥମ 20ଟି ମୌଳିକ',
    legend_hint: 'କୌଣସି ରଙ୍ଗରେ ଟ୍ୟାପ୍ କଲେ ସେହି ଦଳ ଉଜ୍ଜ୍ୱଳ ହେବ। ପୁଣି ଟ୍ୟାପ୍ କଲେ ସବୁ ଦେଖାଯିବ।',
    axis_hint: 'ଠିଆ ସ୍ତମ୍ଭଗୁଡ଼ିକ ଗ୍ରୁପ୍ (1–18)। ଶୋଇଥିବା ଧାଡ଼ିଗୁଡ଼ିକ ପର୍ଯ୍ୟାୟ (1–7)।',
    pt_aria: '118ଟି ମୌଳିକର ପର୍ଯ୍ୟାୟ ସାରଣୀ', tile_aria: '{name} ({s}), ପରମାଣୁ ସଂଖ୍ୟା {n}',
    lanthanoids: 'ଲାନ୍ଥାନଏଡ୍', actinoids: 'ଆକ୍ଟିନଏଡ୍',
    cat_alkali: 'କ୍ଷାର ଧାତୁ', cat_alkaline: 'କ୍ଷାରୀୟ ମୃତ୍ତିକା ଧାତୁ', cat_transition: 'ସଂକ୍ରମଣ ଧାତୁ', cat_post: 'ଅନ୍ୟ ଧାତୁ', cat_metalloid: 'ଉପଧାତୁ', cat_nonmetal: 'ଅଧାତୁ', cat_halogen: 'ହାଲୋଜେନ୍', cat_noble: 'ନିଷ୍କ୍ରିୟ ଗ୍ୟାସ୍', cat_lanthanoid: 'ଲାନ୍ଥାନଏଡ୍', cat_actinoid: 'ଆକ୍ଟିନଏଡ୍',
    block_name: '{b}-ବ୍ଲକ୍', state_solid: 'କଠିନ', state_liquid: 'ତରଳ', state_gas: 'ଗ୍ୟାସ୍', state_unknown: 'ଜଣା ନାହିଁ',
    type_metal: 'ଧାତୁ', type_nonmetal: 'ଅଧାତୁ', type_metalloid: 'ଉପଧାତୁ',
    d_number: 'ପରମାଣୁ ସଂଖ୍ୟା', d_mass: 'ପରମାଣୁ ବସ୍ତୁତ୍ୱ (u)', d_group: 'ଗ୍ରୁପ୍', d_period: 'ପର୍ଯ୍ୟାୟ', d_family: 'ପରିବାର', d_type: 'ପ୍ରକାର', d_state: 'କୋଠରୀ ତାପମାତ୍ରାରେ ଅବସ୍ଥା', d_en: 'ବିଦ୍ୟୁତ୍ ଋଣାତ୍ମକତା (ପଲିଂ)', d_config: 'ଇଲେକ୍ଟ୍ରନ ବିନ୍ୟାସ', d_full: 'ପୂରା ଲେଖିଲେ', d_shells: 'କକ୍ଷରେ ଇଲେକ୍ଟ୍ରନ', d_valence: 'ଯୋଜ୍ୟତା ଇଲେକ୍ଟ୍ରନ', d_valency: 'ଯୋଜ୍ୟତା', d_particles: 'ପରମାଣୁ ଭିତରେ',
    particles_val: '{p}ଟି ପ୍ରୋଟନ, {n}ଟି ନ୍ୟୁଟ୍ରନ, {e}ଟି ଇଲେକ୍ଟ୍ରନ (ବସ୍ତୁତ୍ୱ ସଂଖ୍ୟା {a})',
    not_known: 'ଜଣା ନାହିଁ', mass_note: '[ ] ଭିତରେ ଲେଖାଥିବା ବସ୍ତୁତ୍ୱ ହେଉଛି ସବୁଠୁ ସ୍ଥାୟୀ ଆଇସୋଟୋପର ବସ୍ତୁତ୍ୱ ସଂଖ୍ୟା।', latin_note: 'ଏହାର ସଙ୍କେତ ଲାଟିନ୍ ନାମ “{name}”ରୁ ଆସିଛି।',
    radioactive: 'ତେଜସ୍କ୍ରିୟ', predicted: 'ଏହାର ଏପର୍ଯ୍ୟନ୍ତ କେବଳ କିଛି ପରମାଣୁ ତିଆରି ହୋଇଛି, ତେଣୁ କିଛି ତଥ୍ୟ ଅନୁମାନ।',
    uses_title: 'ଏହା ଆମକୁ କେଉଁଠି ମିଳେ', hear_name: 'ଇଂରାଜୀ ନାମ ଶୁଣନ୍ତୁ', in_english: 'ଇଂରାଜୀରେ: {name}',
    bohr_title: 'ବୋର ମଡେଲ', bohr_caption: 'ନ୍ୟୁକ୍ଲିୟସ୍: {p}ଟି ପ୍ରୋଟନ ଓ {n}ଟି ନ୍ୟୁଟ୍ରନ। କକ୍ଷ: {s}।', bohr_only20: 'ଶ୍ରେଣୀ 9 ପରି ପ୍ରଥମ 20ଟି ମୌଳିକ ପାଇଁ ବୋର ଚିତ୍ର ଅଙ୍କାଯାଇଛି।',
    featured_hint: 'ଯେକୌଣସି ମୌଳିକରେ ଟ୍ୟାପ୍ କରନ୍ତୁ', print_table: 'ସାରଣୀ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    quiz_mode: 'ପ୍ରଶ୍ନର ପ୍ରକାର', q_sym2name: 'ସଙ୍କେତ → ନାମ', q_name2sym: 'ନାମ → ସଙ୍କେତ', q_num2sym: 'ସଂଖ୍ୟା → ସଙ୍କେତ', q_valency: 'ଯୋଜ୍ୟତା (ପ୍ରଥମ 20)',
    quiz_range: 'ମୌଳିକ', range_first: 'ପ୍ରଥମ {n}', range_all: 'ସମସ୍ତ 118',
    ask_sym2name: '{s} କେଉଁ ମୌଳିକର ସଙ୍କେତ?', ask_name2sym: '{name}ର ସଙ୍କେତ କ’ଣ?', ask_num2sym: 'ପରମାଣୁ ସଂଖ୍ୟା {n} କେଉଁ ମୌଳିକର?', ask_valency: '{name} ({s})ର ଯୋଜ୍ୟତା କେତେ?',
    q_progress: 'ପ୍ରଶ୍ନ {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} ମାନେ {name}, ପରମାଣୁ ସଂଖ୍ୟା {n}।',
    ex_lose: '{name} ({shells})ର ବାହାର କକ୍ଷରେ {v}ଟି ଇଲେକ୍ଟ୍ରନ ଅଛି। ଏହା ସେଗୁଡ଼ିକୁ ଦେଇଦିଏ, ତେଣୁ ଯୋଜ୍ୟତା {v}।',
    ex_gain: '{name} ({shells})ର ବାହାର କକ୍ଷରେ {v}ଟି ଇଲେକ୍ଟ୍ରନ ଅଛି। 8 ପୂରଣ ପାଇଁ ଆଉ {val}ଟି ଦରକାର, ତେଣୁ ଯୋଜ୍ୟତା {val}।',
    ex_share: '{name} ({shells})ର ବାହାର କକ୍ଷରେ {v}ଟି ଇଲେକ୍ଟ୍ରନ ଅଛି। ଏହା ସେଗୁଡ଼ିକୁ ଅଂଶୀଦାର କରେ, ତେଣୁ ଯୋଜ୍ୟତା {v}।',
    ex_full: '{name} ({shells})ର ବାହାର କକ୍ଷ ଆଗରୁ ପୂର୍ଣ୍ଣ, ତେଣୁ ଯୋଜ୍ୟତା 0।',
    ex_h: 'ହାଇଡ୍ରୋଜେନରେ 1ଟି ଇଲେକ୍ଟ୍ରନ ଅଛି। ଏହାର ଏକମାତ୍ର କକ୍ଷ ପୂରଣ ପାଇଁ ଆଉ 1ଟି ଦରକାର, ତେଣୁ ଯୋଜ୍ୟତା 1।',
    round_done: 'ରାଉଣ୍ଡ ଶେଷ! {n}ରୁ {c}ଟି ଠିକ୍।', best_score: 'ସର୍ବୋତ୍ତମ: {b} / {n}', play_again: 'ପୁଣି ଖେଳନ୍ତୁ',
    msg_perfect: 'ପୂରା ନମ୍ବର! ଆପଣ ପର୍ଯ୍ୟାୟ ସାରଣୀର ତାରକା।', msg_good: 'ବହୁତ ଭଲ! ଭୁଲଗୁଡ଼ିକ ଦେଖି ପୁଣି ଖେଳନ୍ତୁ।', msg_try: 'ଅଭ୍ୟାସ ଜାରି ରଖନ୍ତୁ: ସାରଣୀରେ ମୌଳିକ ଦେଖି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
    quiz_keys: 'କିବୋର୍ଡ: ଉତ୍ତର ପାଇଁ 1–5 ଦବାନ୍ତୁ ଓ ପରବର୍ତ୍ତୀ ପ୍ରଶ୍ନ ପାଇଁ Enter।',
    cbse_first20: 'ପ୍ରଥମ 20ଟି ମୌଳିକ: କକ୍ଷ ଓ ଯୋଜ୍ୟତା', first20_hint: 'କୌଣସି ନାମରେ ଟ୍ୟାପ୍ କଲେ ସେହି ମୌଳିକ ସାରଣୀରେ ଖୋଲିବ।',
    col_no: 'କ୍ରମ', col_sym: 'ସଙ୍କେତ', col_name: 'ନାମ', col_massno: 'ବସ୍ତୁତ୍ୱ ସଂଖ୍ୟା',
    how_valency_title: 'ଯୋଜ୍ୟତା କିପରି ବାହାର କରିବେ',
    how_valency: 'ସବୁଠୁ ବାହାର କକ୍ଷର ଇଲେକ୍ଟ୍ରନ ଗଣନ୍ତୁ। 1, 2, 3 ବା 4ଟି ହେଲେ ଯୋଜ୍ୟତା ସେହି ସଂଖ୍ୟା। 5, 6 ବା 7ଟି ହେଲେ 8ରୁ ସେହି ସଂଖ୍ୟା ବିୟୋଗ କଲେ ଯୋଜ୍ୟତା ମିଳେ। କକ୍ଷ ପୂର୍ଣ୍ଣ ହେଲେ (ହିଲିୟମରେ 2, ବାକିରେ 8) ଯୋଜ୍ୟତା 0।',
    valency_eg: 'ଉଦାହରଣ: କ୍ଲୋରିନ 2, 8, 7। ବାହାର କକ୍ଷରେ 7ଟି ଇଲେକ୍ଟ୍ରନ, ତେଣୁ ଯୋଜ୍ୟତା 8 − 7 = 1। ସୋଡିୟମ (2, 8, 1)ର ଯୋଜ୍ୟତା ମଧ୍ୟ 1, ତେଣୁ ଲୁଣ ହେଉଛି NaCl।',
    triads_title: 'ଡୋବେରାଇନରଙ୍କ ତ୍ରୟୀ', triads_desc: 'ତିନୋଟି ସମାନ ମୌଳିକର ପ୍ରତି ଦଳରେ ମଝି ମୌଳିକର ବସ୍ତୁତ୍ୱ ବାକି ଦୁଇଟିର ହାରାହାରି ପାଖାପାଖି।',
    col_triad: 'ତ୍ରୟୀ', col_avg: 'ପ୍ରଥମ ଓ ତୃତୀୟର ହାରାହାରି', col_middle: 'ମଝିଟିର ବସ୍ତୁତ୍ୱ',
    mend_title: 'ମେଣ୍ଡେଲିଭଙ୍କ ସାରଣୀ ଓ ଆଧୁନିକ ପର୍ଯ୍ୟାୟ ସାରଣୀ', col_point: 'ବିଷୟ', col_mend: 'ମେଣ୍ଡେଲିଭ (1869)', col_modern: 'ଆଧୁନିକ (ମୋସଲେ, 1913)',
    trends_title: 'ମନେ ରଖିବା ପାଇଁ ଧାରା',
    print_ws: 'ୱାର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ', ws_title: 'ୱାର୍କସିଟ୍: ପ୍ରଥମ 20ଟି ମୌଳିକ', ws_line: 'ନାମ: ______________   ଶ୍ରେଣୀ: ______   ତାରିଖ: __________',
    ws_instr: 'ଖାଲି ଘରଗୁଡ଼ିକ ପୂରଣ କର। କକ୍ଷରୁ ଯୋଜ୍ୟତା ବାହାର କର।', ws_key: 'ଉତ୍ତର ସୂଚୀ'
  },
  ta: {
    app_title: 'தனிம வரிசை அட்டவணை ஆய்வு',
    intro: 'அனைத்து 118 தனிமங்களையும் அறிந்துகொள்ளுங்கள்: ஏதேனும் ஒரு தனிமத்தைத் தொட்டு அதன் எலக்ட்ரான் அமைப்பு, இணைதிறன், போர் மாதிரி ஆகியவற்றைப் பாருங்கள்; பிறகு சிறு வினாடி வினாவில் உங்களைச் சோதியுங்கள்.',
    how_title: 'பயன்படுத்துவது எப்படி · வகுப்பறைக்கான யோசனைகள்',
    tab_table: 'தனிம வரிசை அட்டவணை', tab_quiz: 'வினாடி வினா', tab_cbse: '9–10 வகுப்பு பகுதி',
    search_label: 'தனிமத்தைத் தேடு', search_ph: 'பெயர், குறியீடு அல்லது எண், எ.கா. Na, 26, ஆக்சிஜன்',
    n_found: '{n} கிடைத்தன', no_match: 'தனிமம் எதுவும் கிடைக்கவில்லை. Fe போன்ற குறியீடு அல்லது 26 போன்ற எண்ணை முயலுங்கள்.',
    colour_by: 'நிறம் எதன்படி', by_family: 'குடும்பம்', by_block: 'தொகுப்பு', by_state: 'நிலை',
    highlight: 'முன்னிலைப்படுத்து', hl_all: 'அனைத்தையும் காட்டு', grp_type: 'வகை',
    hl_metal: 'உலோகங்கள்', hl_nonmetal: 'அலோகங்கள்', hl_metalloid: 'உலோகப்போலிகள்', hl_solid: 'திண்மங்கள்', hl_liquid: 'நீர்மங்கள்', hl_gas: 'வாயுக்கள்', hl_radio: 'கதிரியக்கத் தனிமங்கள்', hl_first20: 'முதல் 20 தனிமங்கள்',
    legend_hint: 'ஒரு நிறத்தைத் தொட்டால் அந்தக் குழு முன்னிலைப்படும். மீண்டும் தொட்டால் அனைத்தும் தெரியும்.',
    axis_hint: 'நெடுவரிசைகள் தொகுதிகள் (1–18). கிடைவரிசைகள் தொடர்கள் (1–7).',
    pt_aria: '118 தனிமங்களின் தனிம வரிசை அட்டவணை', tile_aria: '{name} ({s}), அணு எண் {n}',
    lanthanoids: 'லாந்தனைடுகள்', actinoids: 'ஆக்டினைடுகள்',
    cat_alkali: 'கார உலோகம்', cat_alkaline: 'காரமண் உலோகம்', cat_transition: 'இடைநிலை உலோகம்', cat_post: 'பிற உலோகம்', cat_metalloid: 'உலோகப்போலி', cat_nonmetal: 'அலோகம்', cat_halogen: 'ஹாலஜன்', cat_noble: 'மந்த வாயு', cat_lanthanoid: 'லாந்தனைடு', cat_actinoid: 'ஆக்டினைடு',
    block_name: '{b}-தொகுப்பு', state_solid: 'திண்மம்', state_liquid: 'நீர்மம்', state_gas: 'வாயு', state_unknown: 'தெரியவில்லை',
    type_metal: 'உலோகம்', type_nonmetal: 'அலோகம்', type_metalloid: 'உலோகப்போலி',
    d_number: 'அணு எண்', d_mass: 'அணு நிறை (u)', d_group: 'தொகுதி', d_period: 'தொடர்', d_family: 'குடும்பம்', d_type: 'வகை', d_state: 'அறை வெப்பநிலையில் நிலை', d_en: 'எலக்ட்ரான் கவர்தன்மை (பாலிங்)', d_config: 'எலக்ட்ரான் அமைப்பு', d_full: 'முழுமையாக எழுதினால்', d_shells: 'கூடுகளில் எலக்ட்ரான்கள்', d_valence: 'இணைதிறன் எலக்ட்ரான்கள்', d_valency: 'இணைதிறன்', d_particles: 'அணுவின் உள்ளே',
    particles_val: '{p} புரோட்டான்கள், {n} நியூட்ரான்கள், {e} எலக்ட்ரான்கள் (நிறை எண் {a})',
    not_known: 'தெரியவில்லை', mass_note: '[ ] க்குள் உள்ள நிறை, மிக நிலைத்த ஐசோடோப்பின் நிறை எண் ஆகும்.', latin_note: 'இதன் குறியீடு “{name}” என்ற லத்தீன் பெயரிலிருந்து வந்தது.',
    radioactive: 'கதிரியக்கம்', predicted: 'இதன் சில அணுக்கள் மட்டுமே இதுவரை உருவாக்கப்பட்டுள்ளன; எனவே சில தகவல்கள் கணிப்புகள்.',
    uses_title: 'இதை எங்கே காண்கிறோம்', hear_name: 'ஆங்கிலப் பெயரைக் கேளுங்கள்', in_english: 'ஆங்கிலத்தில்: {name}',
    bohr_title: 'போர் மாதிரி', bohr_caption: 'உட்கரு: {p} புரோட்டான்கள், {n} நியூட்ரான்கள். கூடுகள்: {s}.', bohr_only20: '9ஆம் வகுப்பில் உள்ளதுபோல் முதல் 20 தனிமங்களுக்கு போர் படங்கள் வரையப்பட்டுள்ளன.',
    featured_hint: 'ஏதேனும் ஒரு தனிமத்தைத் தொடுங்கள்', print_table: 'அட்டவணையை அச்சிடு',
    quiz_mode: 'கேள்வி வகை', q_sym2name: 'குறியீடு → பெயர்', q_name2sym: 'பெயர் → குறியீடு', q_num2sym: 'எண் → குறியீடு', q_valency: 'இணைதிறன் (முதல் 20)',
    quiz_range: 'தனிமங்கள்', range_first: 'முதல் {n}', range_all: 'அனைத்தும் 118',
    ask_sym2name: '{s} எந்தத் தனிமத்தின் குறியீடு?', ask_name2sym: '{name} இன் குறியீடு என்ன?', ask_num2sym: 'அணு எண் {n} உள்ள தனிமம் எது?', ask_valency: '{name} ({s}) இன் இணைதிறன் என்ன?',
    q_progress: 'கேள்வி {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} என்பது {name}, அணு எண் {n}.',
    ex_lose: '{name} ({shells}) இன் வெளிக்கூட்டில் {v} எலக்ட்ரான்கள் உள்ளன. அவற்றை அது இழக்கிறது, எனவே இணைதிறன் {v}.',
    ex_gain: '{name} ({shells}) இன் வெளிக்கூட்டில் {v} எலக்ட்ரான்கள் உள்ளன. 8 ஆக்க இன்னும் {val} தேவை, எனவே இணைதிறன் {val}.',
    ex_share: '{name} ({shells}) இன் வெளிக்கூட்டில் {v} எலக்ட்ரான்கள் உள்ளன. அவற்றை அது பகிர்ந்துகொள்கிறது, எனவே இணைதிறன் {v}.',
    ex_full: '{name} ({shells}) இன் வெளிக்கூடு ஏற்கெனவே நிரம்பியுள்ளது, எனவே இணைதிறன் 0.',
    ex_h: 'ஹைட்ரஜனில் 1 எலக்ட்ரான் உள்ளது. அதன் ஒரே கூட்டை நிரப்ப இன்னும் 1 தேவை, எனவே இணைதிறன் 1.',
    round_done: 'சுற்று முடிந்தது! {n} இல் {c} சரி.', best_score: 'சிறந்தது: {b} / {n}', play_again: 'மீண்டும் விளையாடு',
    msg_perfect: 'முழு மதிப்பெண்! நீங்கள் தனிம அட்டவணை நட்சத்திரம்.', msg_good: 'நன்று! தவறுகளைப் பார்த்து மீண்டும் விளையாடுங்கள்.', msg_try: 'பயிற்சியைத் தொடருங்கள்: அட்டவணையில் தனிமங்களைப் பார்த்து மீண்டும் முயலுங்கள்.',
    quiz_keys: 'விசைப்பலகை: பதிலுக்கு 1–5, அடுத்த கேள்விக்கு Enter அழுத்துங்கள்.',
    cbse_first20: 'முதல் 20 தனிமங்கள்: கூடுகளும் இணைதிறனும்', first20_hint: 'ஒரு பெயரைத் தொட்டால் அந்தத் தனிமம் அட்டவணையில் திறக்கும்.',
    col_no: 'எண்', col_sym: 'குறியீடு', col_name: 'பெயர்', col_massno: 'நிறை எண்',
    how_valency_title: 'இணைதிறனைக் கண்டறிவது எப்படி',
    how_valency: 'வெளிக்கூட்டில் உள்ள எலக்ட்ரான்களை எண்ணுங்கள். 1, 2, 3 அல்லது 4 என்றால் இணைதிறன் அதே எண். 5, 6 அல்லது 7 என்றால் 8 இலிருந்து அந்த எண்ணைக் கழித்தால் இணைதிறன் கிடைக்கும். கூடு நிரம்பியிருந்தால் (ஹீலியத்தில் 2, மற்றவற்றில் 8) இணைதிறன் 0.',
    valency_eg: 'எடுத்துக்காட்டு: குளோரின் 2, 8, 7. வெளிக்கூட்டில் 7 எலக்ட்ரான்கள், எனவே இணைதிறன் 8 − 7 = 1. சோடியத்தின் (2, 8, 1) இணைதிறனும் 1; அதனால்தான் உப்பு NaCl.',
    triads_title: 'டாபரீனரின் மும்மைகள்', triads_desc: 'ஒத்த பண்புள்ள மூன்று தனிமங்களின் ஒவ்வொரு குழுவிலும், நடுவில் உள்ளதன் நிறை மற்ற இரண்டின் சராசரிக்கு அருகில் இருக்கும்.',
    col_triad: 'மும்மை', col_avg: '1ஆவது, 3ஆவதின் சராசரி', col_middle: 'நடுவில் உள்ளதன் நிறை',
    mend_title: 'மெண்டலீஃபின் அட்டவணையும் நவீன தனிம வரிசை அட்டவணையும்', col_point: 'கருத்து', col_mend: 'மெண்டலீஃப் (1869)', col_modern: 'நவீன (மோஸ்லே, 1913)',
    trends_title: 'நினைவில் கொள்ள வேண்டிய போக்குகள்',
    print_ws: 'பயிற்சித்தாளை அச்சிடு', ws_title: 'பயிற்சித்தாள்: முதல் 20 தனிமங்கள்', ws_line: 'பெயர்: ______________   வகுப்பு: ______   தேதி: __________',
    ws_instr: 'காலியான கட்டங்களை நிரப்புங்கள். கூடுகளிலிருந்து இணைதிறனைக் கண்டறியுங்கள்.', ws_key: 'விடைக் குறிப்பு'
  },
  te: {
    app_title: 'ఆవర్తన పట్టిక ఎక్స్‌ప్లోరర్',
    intro: 'మొత్తం 118 మూలకాలను తెలుసుకోండి: ఏదైనా మూలకంపై ట్యాప్ చేసి దాని ఎలక్ట్రాన్ విన్యాసం, సంయోజకత, బోర్ నమూనా చూడండి; తర్వాత చిన్న క్విజ్‌తో మిమ్మల్ని మీరు పరీక్షించుకోండి.',
    how_title: 'ఎలా ఉపయోగించాలి · తరగతి కోసం ఆలోచనలు',
    tab_table: 'ఆవర్తన పట్టిక', tab_quiz: 'క్విజ్', tab_cbse: '9–10 తరగతుల విభాగం',
    search_label: 'మూలకాన్ని వెతకండి', search_ph: 'పేరు, సంకేతం లేదా సంఖ్య, ఉదా. Na, 26, ఆక్సిజన్',
    n_found: '{n} దొరికాయి', no_match: 'ఏ మూలకమూ దొరకలేదు. Fe లాంటి సంకేతం లేదా 26 లాంటి సంఖ్యను ప్రయత్నించండి.',
    colour_by: 'రంగు దేని ప్రకారం', by_family: 'కుటుంబం', by_block: 'బ్లాక్', by_state: 'స్థితి',
    highlight: 'హైలైట్ చేయండి', hl_all: 'అన్నీ చూపించు', grp_type: 'రకం',
    hl_metal: 'లోహాలు', hl_nonmetal: 'అలోహాలు', hl_metalloid: 'అర్ధలోహాలు', hl_solid: 'ఘనాలు', hl_liquid: 'ద్రవాలు', hl_gas: 'వాయువులు', hl_radio: 'రేడియోధార్మిక మూలకాలు', hl_first20: 'మొదటి 20 మూలకాలు',
    legend_hint: 'ఒక రంగుపై ట్యాప్ చేస్తే ఆ సమూహం హైలైట్ అవుతుంది. మళ్ళీ ట్యాప్ చేస్తే అన్నీ కనిపిస్తాయి.',
    axis_hint: 'నిలువు వరుసలు గ్రూపులు (1–18). అడ్డు వరుసలు పీరియడ్‌లు (1–7).',
    pt_aria: '118 మూలకాల ఆవర్తన పట్టిక', tile_aria: '{name} ({s}), పరమాణు సంఖ్య {n}',
    lanthanoids: 'లాంథనైడ్‌లు', actinoids: 'ఆక్టినైడ్‌లు',
    cat_alkali: 'క్షార లోహం', cat_alkaline: 'క్షార మృత్తిక లోహం', cat_transition: 'పరివర్తన లోహం', cat_post: 'ఇతర లోహం', cat_metalloid: 'అర్ధలోహం', cat_nonmetal: 'అలోహం', cat_halogen: 'హాలోజన్', cat_noble: 'ఉత్కృష్ట వాయువు', cat_lanthanoid: 'లాంథనైడ్', cat_actinoid: 'ఆక్టినైడ్',
    block_name: '{b}-బ్లాక్', state_solid: 'ఘనం', state_liquid: 'ద్రవం', state_gas: 'వాయువు', state_unknown: 'తెలియదు',
    type_metal: 'లోహం', type_nonmetal: 'అలోహం', type_metalloid: 'అర్ధలోహం',
    d_number: 'పరమాణు సంఖ్య', d_mass: 'పరమాణు ద్రవ్యరాశి (u)', d_group: 'గ్రూపు', d_period: 'పీరియడ్', d_family: 'కుటుంబం', d_type: 'రకం', d_state: 'గది ఉష్ణోగ్రత వద్ద స్థితి', d_en: 'ఋణవిద్యుదాత్మకత (పౌలింగ్)', d_config: 'ఎలక్ట్రాన్ విన్యాసం', d_full: 'పూర్తిగా రాస్తే', d_shells: 'కర్పరాలలో ఎలక్ట్రాన్‌లు', d_valence: 'వేలన్సీ ఎలక్ట్రాన్‌లు', d_valency: 'సంయోజకత', d_particles: 'పరమాణువు లోపల',
    particles_val: '{p} ప్రోటాన్‌లు, {n} న్యూట్రాన్‌లు, {e} ఎలక్ట్రాన్‌లు (ద్రవ్యరాశి సంఖ్య {a})',
    not_known: 'తెలియదు', mass_note: '[ ] లోని ద్రవ్యరాశి అత్యంత స్థిరమైన ఐసోటోప్ ద్రవ్యరాశి సంఖ్య.', latin_note: 'దీని సంకేతం “{name}” అనే లాటిన్ పేరు నుంచి వచ్చింది.',
    radioactive: 'రేడియోధార్మికం', predicted: 'దీని కొన్ని పరమాణువులు మాత్రమే ఇప్పటివరకు తయారయ్యాయి, కాబట్టి కొన్ని వివరాలు అంచనాలు.',
    uses_title: 'ఇది మనకు ఎక్కడ కనిపిస్తుంది', hear_name: 'ఇంగ్లీష్ పేరు వినండి', in_english: 'ఇంగ్లీష్‌లో: {name}',
    bohr_title: 'బోర్ నమూనా', bohr_caption: 'కేంద్రకం: {p} ప్రోటాన్‌లు, {n} న్యూట్రాన్‌లు. కర్పరాలు: {s}.', bohr_only20: '9వ తరగతిలోలాగే మొదటి 20 మూలకాలకు బోర్ చిత్రాలు గీశాం.',
    featured_hint: 'ఏదైనా మూలకంపై ట్యాప్ చేయండి', print_table: 'పట్టికను ప్రింట్ చేయండి',
    quiz_mode: 'ప్రశ్న రకం', q_sym2name: 'సంకేతం → పేరు', q_name2sym: 'పేరు → సంకేతం', q_num2sym: 'సంఖ్య → సంకేతం', q_valency: 'సంయోజకత (మొదటి 20)',
    quiz_range: 'మూలకాలు', range_first: 'మొదటి {n}', range_all: 'మొత్తం 118',
    ask_sym2name: '{s} ఏ మూలకం సంకేతం?', ask_name2sym: '{name} సంకేతం ఏమిటి?', ask_num2sym: 'పరమాణు సంఖ్య {n} ఉన్న మూలకం ఏది?', ask_valency: '{name} ({s}) సంయోజకత ఎంత?',
    q_progress: 'ప్రశ్న {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} అంటే {name}, పరమాణు సంఖ్య {n}.',
    ex_lose: '{name} ({shells}) బాహ్య కర్పరంలో {v} ఎలక్ట్రాన్‌లు ఉన్నాయి. అది వాటిని కోల్పోతుంది, కాబట్టి సంయోజకత {v}.',
    ex_gain: '{name} ({shells}) బాహ్య కర్పరంలో {v} ఎలక్ట్రాన్‌లు ఉన్నాయి. 8 కావడానికి ఇంకా {val} కావాలి, కాబట్టి సంయోజకత {val}.',
    ex_share: '{name} ({shells}) బాహ్య కర్పరంలో {v} ఎలక్ట్రాన్‌లు ఉన్నాయి. అది వాటిని పంచుకుంటుంది, కాబట్టి సంయోజకత {v}.',
    ex_full: '{name} ({shells}) బాహ్య కర్పరం ఇప్పటికే నిండి ఉంది, కాబట్టి సంయోజకత 0.',
    ex_h: 'హైడ్రోజన్‌లో 1 ఎలక్ట్రాన్ ఉంది. దాని ఒకే కర్పరం నిండడానికి ఇంకా 1 కావాలి, కాబట్టి సంయోజకత 1.',
    round_done: 'రౌండ్ పూర్తయింది! {n} లో {c} సరైనవి.', best_score: 'ఉత్తమం: {b} / {n}', play_again: 'మళ్ళీ ఆడండి',
    msg_perfect: 'పూర్తి మార్కులు! మీరు ఆవర్తన పట్టిక స్టార్.', msg_good: 'బాగుంది! తప్పులు చూసి మళ్ళీ ఆడండి.', msg_try: 'సాధన కొనసాగించండి: పట్టికలో మూలకాలను చూసి మళ్ళీ ప్రయత్నించండి.',
    quiz_keys: 'కీబోర్డ్: సమాధానానికి 1–5, తర్వాతి ప్రశ్నకు Enter నొక్కండి.',
    cbse_first20: 'మొదటి 20 మూలకాలు: కర్పరాలు, సంయోజకత', first20_hint: 'పేరుపై ట్యాప్ చేస్తే ఆ మూలకం పట్టికలో తెరుచుకుంటుంది.',
    col_no: 'సం.', col_sym: 'సంకేతం', col_name: 'పేరు', col_massno: 'ద్రవ్యరాశి సంఖ్య',
    how_valency_title: 'సంయోజకతను ఎలా కనుగొనాలి',
    how_valency: 'బాహ్య కర్పరంలోని ఎలక్ట్రాన్‌లను లెక్కించండి. 1, 2, 3 లేదా 4 అయితే సంయోజకత అదే సంఖ్య. 5, 6 లేదా 7 అయితే 8 నుంచి ఆ సంఖ్య తీసివేస్తే సంయోజకత వస్తుంది. కర్పరం నిండి ఉంటే (హీలియంలో 2, మిగతావాటిలో 8) సంయోజకత 0.',
    valency_eg: 'ఉదాహరణ: క్లోరిన్ 2, 8, 7. బాహ్య కర్పరంలో 7 ఎలక్ట్రాన్‌లు, కాబట్టి సంయోజకత 8 − 7 = 1. సోడియం (2, 8, 1) సంయోజకత కూడా 1, అందుకే ఉప్పు NaCl.',
    triads_title: 'డోబరైనర్ త్రికాలు', triads_desc: 'ఒకేలాంటి మూడు మూలకాల ప్రతి సమూహంలో, మధ్య మూలకం ద్రవ్యరాశి మిగతా రెండింటి సగటుకు దగ్గరగా ఉంటుంది.',
    col_triad: 'త్రికం', col_avg: '1వ, 3వ వాటి సగటు', col_middle: 'మధ్యదాని ద్రవ్యరాశి',
    mend_title: 'మెండలీఫ్ పట్టిక, ఆధునిక ఆవర్తన పట్టిక', col_point: 'అంశం', col_mend: 'మెండలీఫ్ (1869)', col_modern: 'ఆధునిక (మోస్లే, 1913)',
    trends_title: 'గుర్తుంచుకోవాల్సిన ధోరణులు',
    print_ws: 'వర్క్‌షీట్ ప్రింట్ చేయండి', ws_title: 'వర్క్‌షీట్: మొదటి 20 మూలకాలు', ws_line: 'పేరు: ______________   తరగతి: ______   తేదీ: __________',
    ws_instr: 'ఖాళీ గడులను నింపండి. కర్పరాల నుంచి సంయోజకతను కనుగొనండి.', ws_key: 'జవాబులు'
  },
  kn: {
    app_title: 'ಆವರ್ತ ಕೋಷ್ಟಕ ಎಕ್ಸ್‌ಪ್ಲೋರರ್',
    intro: 'ಎಲ್ಲಾ 118 ಧಾತುಗಳನ್ನು ತಿಳಿಯಿರಿ: ಯಾವುದೇ ಧಾತುವಿನ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ ಅದರ ಇಲೆಕ್ಟ್ರಾನ್ ವಿನ್ಯಾಸ, ಸಂಯೋಜಕತೆ ಮತ್ತು ಬೋರ್ ಮಾದರಿ ನೋಡಿ; ನಂತರ ಚಿಕ್ಕ ಕ್ವಿಜ್‌ನಲ್ಲಿ ನಿಮ್ಮನ್ನು ಪರೀಕ್ಷಿಸಿ.',
    how_title: 'ಬಳಸುವುದು ಹೇಗೆ · ತರಗತಿಗೆ ಉಪಾಯಗಳು',
    tab_table: 'ಆವರ್ತ ಕೋಷ್ಟಕ', tab_quiz: 'ಕ್ವಿಜ್', tab_cbse: '9–10ನೇ ತರಗತಿ ವಿಭಾಗ',
    search_label: 'ಧಾತುವನ್ನು ಹುಡುಕಿ', search_ph: 'ಹೆಸರು, ಸಂಕೇತ ಅಥವಾ ಸಂಖ್ಯೆ, ಉದಾ. Na, 26, ಆಕ್ಸಿಜನ್',
    n_found: '{n} ಸಿಕ್ಕಿವೆ', no_match: 'ಯಾವುದೇ ಧಾತು ಸಿಗಲಿಲ್ಲ. Fe ಯಂತಹ ಸಂಕೇತ ಅಥವಾ 26 ರಂತಹ ಸಂಖ್ಯೆ ಪ್ರಯತ್ನಿಸಿ.',
    colour_by: 'ಬಣ್ಣ ಯಾವುದರ ಪ್ರಕಾರ', by_family: 'ಕುಟುಂಬ', by_block: 'ಬ್ಲಾಕ್', by_state: 'ಸ್ಥಿತಿ',
    highlight: 'ಎದ್ದು ಕಾಣಿಸಿ', hl_all: 'ಎಲ್ಲವನ್ನೂ ತೋರಿಸಿ', grp_type: 'ಬಗೆ',
    hl_metal: 'ಲೋಹಗಳು', hl_nonmetal: 'ಅಲೋಹಗಳು', hl_metalloid: 'ಅರೆಲೋಹಗಳು', hl_solid: 'ಘನಗಳು', hl_liquid: 'ದ್ರವಗಳು', hl_gas: 'ಅನಿಲಗಳು', hl_radio: 'ವಿಕಿರಣಶೀಲ ಧಾತುಗಳು', hl_first20: 'ಮೊದಲ 20 ಧಾತುಗಳು',
    legend_hint: 'ಒಂದು ಬಣ್ಣದ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿದರೆ ಆ ಗುಂಪು ಎದ್ದು ಕಾಣುತ್ತದೆ. ಮತ್ತೆ ಟ್ಯಾಪ್ ಮಾಡಿದರೆ ಎಲ್ಲವೂ ಕಾಣುತ್ತವೆ.',
    axis_hint: 'ಲಂಬ ಕಾಲಮ್‌ಗಳು ಗುಂಪುಗಳು (1–18). ಅಡ್ಡ ಸಾಲುಗಳು ಆವರ್ತಗಳು (1–7).',
    pt_aria: '118 ಧಾತುಗಳ ಆವರ್ತ ಕೋಷ್ಟಕ', tile_aria: '{name} ({s}), ಪರಮಾಣು ಸಂಖ್ಯೆ {n}',
    lanthanoids: 'ಲ್ಯಾಂಥನೈಡ್‌ಗಳು', actinoids: 'ಆಕ್ಟಿನೈಡ್‌ಗಳು',
    cat_alkali: 'ಕ್ಷಾರ ಲೋಹ', cat_alkaline: 'ಕ್ಷಾರೀಯ ಭೂ ಲೋಹ', cat_transition: 'ಸಂಕ್ರಮಣ ಲೋಹ', cat_post: 'ಇತರ ಲೋಹ', cat_metalloid: 'ಅರೆಲೋಹ', cat_nonmetal: 'ಅಲೋಹ', cat_halogen: 'ಹ್ಯಾಲೋಜನ್', cat_noble: 'ಜಡ ಅನಿಲ', cat_lanthanoid: 'ಲ್ಯಾಂಥನೈಡ್', cat_actinoid: 'ಆಕ್ಟಿನೈಡ್',
    block_name: '{b}-ಬ್ಲಾಕ್', state_solid: 'ಘನ', state_liquid: 'ದ್ರವ', state_gas: 'ಅನಿಲ', state_unknown: 'ತಿಳಿದಿಲ್ಲ',
    type_metal: 'ಲೋಹ', type_nonmetal: 'ಅಲೋಹ', type_metalloid: 'ಅರೆಲೋಹ',
    d_number: 'ಪರಮಾಣು ಸಂಖ್ಯೆ', d_mass: 'ಪರಮಾಣು ರಾಶಿ (u)', d_group: 'ಗುಂಪು', d_period: 'ಆವರ್ತ', d_family: 'ಕುಟುಂಬ', d_type: 'ಬಗೆ', d_state: 'ಕೋಣೆಯ ತಾಪದಲ್ಲಿ ಸ್ಥಿತಿ', d_en: 'ವಿದ್ಯುತ್ ಋಣತೆ (ಪಾಲಿಂಗ್)', d_config: 'ಇಲೆಕ್ಟ್ರಾನ್ ವಿನ್ಯಾಸ', d_full: 'ಪೂರ್ತಿ ಬರೆದರೆ', d_shells: 'ಕವಚಗಳಲ್ಲಿ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು', d_valence: 'ವೇಲೆನ್ಸ್ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು', d_valency: 'ಸಂಯೋಜಕತೆ', d_particles: 'ಪರಮಾಣುವಿನ ಒಳಗೆ',
    particles_val: '{p} ಪ್ರೋಟಾನ್‌ಗಳು, {n} ನ್ಯೂಟ್ರಾನ್‌ಗಳು, {e} ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು (ರಾಶಿ ಸಂಖ್ಯೆ {a})',
    not_known: 'ತಿಳಿದಿಲ್ಲ', mass_note: '[ ] ಒಳಗಿನ ರಾಶಿಯು ಅತ್ಯಂತ ಸ್ಥಿರ ಐಸೋಟೋಪಿನ ರಾಶಿ ಸಂಖ್ಯೆ.', latin_note: 'ಇದರ ಸಂಕೇತ “{name}” ಎಂಬ ಲ್ಯಾಟಿನ್ ಹೆಸರಿನಿಂದ ಬಂದಿದೆ.',
    radioactive: 'ವಿಕಿರಣಶೀಲ', predicted: 'ಇದರ ಕೆಲವೇ ಪರಮಾಣುಗಳನ್ನು ಇದುವರೆಗೆ ತಯಾರಿಸಲಾಗಿದೆ, ಆದ್ದರಿಂದ ಕೆಲವು ಮಾಹಿತಿ ಅಂದಾಜು.',
    uses_title: 'ಇದು ನಮಗೆ ಎಲ್ಲಿ ಸಿಗುತ್ತದೆ', hear_name: 'ಇಂಗ್ಲಿಷ್ ಹೆಸರು ಕೇಳಿ', in_english: 'ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ: {name}',
    bohr_title: 'ಬೋರ್ ಮಾದರಿ', bohr_caption: 'ನ್ಯೂಕ್ಲಿಯಸ್: {p} ಪ್ರೋಟಾನ್‌ಗಳು ಮತ್ತು {n} ನ್ಯೂಟ್ರಾನ್‌ಗಳು. ಕವಚಗಳು: {s}.', bohr_only20: '9ನೇ ತರಗತಿಯಂತೆ ಮೊದಲ 20 ಧಾತುಗಳಿಗೆ ಬೋರ್ ಚಿತ್ರಗಳನ್ನು ಬರೆಯಲಾಗಿದೆ.',
    featured_hint: 'ಯಾವುದೇ ಧಾತುವಿನ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ', print_table: 'ಕೋಷ್ಟಕ ಮುದ್ರಿಸಿ',
    quiz_mode: 'ಪ್ರಶ್ನೆಯ ಬಗೆ', q_sym2name: 'ಸಂಕೇತ → ಹೆಸರು', q_name2sym: 'ಹೆಸರು → ಸಂಕೇತ', q_num2sym: 'ಸಂಖ್ಯೆ → ಸಂಕೇತ', q_valency: 'ಸಂಯೋಜಕತೆ (ಮೊದಲ 20)',
    quiz_range: 'ಧಾತುಗಳು', range_first: 'ಮೊದಲ {n}', range_all: 'ಎಲ್ಲಾ 118',
    ask_sym2name: '{s} ಯಾವ ಧಾತುವಿನ ಸಂಕೇತ?', ask_name2sym: '{name} ಇದರ ಸಂಕೇತ ಏನು?', ask_num2sym: 'ಪರಮಾಣು ಸಂಖ್ಯೆ {n} ಇರುವ ಧಾತು ಯಾವುದು?', ask_valency: '{name} ({s}) ಇದರ ಸಂಯೋಜಕತೆ ಎಷ್ಟು?',
    q_progress: 'ಪ್ರಶ್ನೆ {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} ಎಂದರೆ {name}, ಪರಮಾಣು ಸಂಖ್ಯೆ {n}.',
    ex_lose: '{name} ({shells}) ಹೊರ ಕವಚದಲ್ಲಿ {v} ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳಿವೆ. ಅದು ಅವನ್ನು ಬಿಟ್ಟುಕೊಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಸಂಯೋಜಕತೆ {v}.',
    ex_gain: '{name} ({shells}) ಹೊರ ಕವಚದಲ್ಲಿ {v} ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳಿವೆ. 8 ಆಗಲು ಇನ್ನೂ {val} ಬೇಕು, ಆದ್ದರಿಂದ ಸಂಯೋಜಕತೆ {val}.',
    ex_share: '{name} ({shells}) ಹೊರ ಕವಚದಲ್ಲಿ {v} ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳಿವೆ. ಅದು ಅವನ್ನು ಹಂಚಿಕೊಳ್ಳುತ್ತದೆ, ಆದ್ದರಿಂದ ಸಂಯೋಜಕತೆ {v}.',
    ex_full: '{name} ({shells}) ಹೊರ ಕವಚ ಈಗಾಗಲೇ ತುಂಬಿದೆ, ಆದ್ದರಿಂದ ಸಂಯೋಜಕತೆ 0.',
    ex_h: 'ಹೈಡ್ರೋಜನ್‌ನಲ್ಲಿ 1 ಇಲೆಕ್ಟ್ರಾನ್ ಇದೆ. ಅದರ ಏಕೈಕ ಕವಚ ತುಂಬಲು ಇನ್ನೂ 1 ಬೇಕು, ಆದ್ದರಿಂದ ಸಂಯೋಜಕತೆ 1.',
    round_done: 'ಸುತ್ತು ಮುಗಿಯಿತು! {n} ರಲ್ಲಿ {c} ಸರಿ.', best_score: 'ಅತ್ಯುತ್ತಮ: {b} / {n}', play_again: 'ಮತ್ತೆ ಆಡಿ',
    msg_perfect: 'ಪೂರ್ಣ ಅಂಕ! ನೀವು ಆವರ್ತ ಕೋಷ್ಟಕದ ತಾರೆ.', msg_good: 'ಚೆನ್ನಾಗಿದೆ! ತಪ್ಪುಗಳನ್ನು ನೋಡಿ ಮತ್ತೆ ಆಡಿ.', msg_try: 'ಅಭ್ಯಾಸ ಮುಂದುವರಿಸಿ: ಕೋಷ್ಟಕದಲ್ಲಿ ಧಾತುಗಳನ್ನು ನೋಡಿ, ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    quiz_keys: 'ಕೀಬೋರ್ಡ್: ಉತ್ತರಕ್ಕೆ 1–5 ಒತ್ತಿ, ಮುಂದಿನ ಪ್ರಶ್ನೆಗೆ Enter ಒತ್ತಿ.',
    cbse_first20: 'ಮೊದಲ 20 ಧಾತುಗಳು: ಕವಚಗಳು ಮತ್ತು ಸಂಯೋಜಕತೆ', first20_hint: 'ಹೆಸರಿನ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿದರೆ ಆ ಧಾತು ಕೋಷ್ಟಕದಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.',
    col_no: 'ಕ್ರ.ಸಂ.', col_sym: 'ಸಂಕೇತ', col_name: 'ಹೆಸರು', col_massno: 'ರಾಶಿ ಸಂಖ್ಯೆ',
    how_valency_title: 'ಸಂಯೋಜಕತೆ ಕಂಡುಹಿಡಿಯುವುದು ಹೇಗೆ',
    how_valency: 'ಹೊರಗಿನ ಕವಚದ ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು ಎಣಿಸಿ. 1, 2, 3 ಅಥವಾ 4 ಇದ್ದರೆ ಸಂಯೋಜಕತೆ ಅದೇ ಸಂಖ್ಯೆ. 5, 6 ಅಥವಾ 7 ಇದ್ದರೆ 8 ರಿಂದ ಆ ಸಂಖ್ಯೆ ಕಳೆದಾಗ ಸಂಯೋಜಕತೆ ಸಿಗುತ್ತದೆ. ಕವಚ ತುಂಬಿದ್ದರೆ (ಹೀಲಿಯಂನಲ್ಲಿ 2, ಉಳಿದವುಗಳಲ್ಲಿ 8) ಸಂಯೋಜಕತೆ 0.',
    valency_eg: 'ಉದಾಹರಣೆ: ಕ್ಲೋರಿನ್ 2, 8, 7. ಹೊರ ಕವಚದಲ್ಲಿ 7 ಇಲೆಕ್ಟ್ರಾನ್‌ಗಳು, ಆದ್ದರಿಂದ ಸಂಯೋಜಕತೆ 8 − 7 = 1. ಸೋಡಿಯಂ (2, 8, 1) ಸಂಯೋಜಕತೆಯೂ 1, ಅದಕ್ಕೇ ಉಪ್ಪು NaCl.',
    triads_title: 'ಡೊಬರೈನರ್‌ನ ತ್ರಿವಳಿಗಳು', triads_desc: 'ಒಂದೇ ರೀತಿಯ ಮೂರು ಧಾತುಗಳ ಪ್ರತಿ ಗುಂಪಿನಲ್ಲಿ ಮಧ್ಯದ ಧಾತುವಿನ ರಾಶಿ ಉಳಿದ ಎರಡರ ಸರಾಸರಿಗೆ ಹತ್ತಿರವಿರುತ್ತದೆ.',
    col_triad: 'ತ್ರಿವಳಿ', col_avg: '1ನೇ ಮತ್ತು 3ನೇಯದರ ಸರಾಸರಿ', col_middle: 'ಮಧ್ಯದ್ದರ ರಾಶಿ',
    mend_title: 'ಮೆಂಡಲೀವ್ ಕೋಷ್ಟಕ ಮತ್ತು ಆಧುನಿಕ ಆವರ್ತ ಕೋಷ್ಟಕ', col_point: 'ಅಂಶ', col_mend: 'ಮೆಂಡಲೀವ್ (1869)', col_modern: 'ಆಧುನಿಕ (ಮೋಸ್ಲೆ, 1913)',
    trends_title: 'ನೆನಪಿಡಬೇಕಾದ ಪ್ರವೃತ್ತಿಗಳು',
    print_ws: 'ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ', ws_title: 'ವರ್ಕ್‌ಶೀಟ್: ಮೊದಲ 20 ಧಾತುಗಳು', ws_line: 'ಹೆಸರು: ______________   ತರಗತಿ: ______   ದಿನಾಂಕ: __________',
    ws_instr: 'ಖಾಲಿ ಚೌಕಗಳನ್ನು ತುಂಬಿ. ಕವಚಗಳಿಂದ ಸಂಯೋಜಕತೆ ಕಂಡುಹಿಡಿಯಿರಿ.', ws_key: 'ಉತ್ತರ ಸೂಚಿ'
  },
  ml: {
    app_title: 'ആവർത്തനപ്പട്ടിക എക്സ്പ്ലോറർ',
    intro: 'എല്ലാ 118 മൂലകങ്ങളെയും അറിയൂ: ഏതെങ്കിലും മൂലകത്തിൽ ടാപ്പ് ചെയ്ത് അതിന്റെ ഇലക്ട്രോൺ വിന്യാസം, സംയോജകത, ബോർ മാതൃക എന്നിവ കാണൂ; പിന്നെ ചെറിയ ക്വിസിലൂടെ സ്വയം പരീക്ഷിക്കൂ.',
    how_title: 'എങ്ങനെ ഉപയോഗിക്കാം · ക്ലാസ് മുറിക്കുള്ള ആശയങ്ങൾ',
    tab_table: 'ആവർത്തനപ്പട്ടിക', tab_quiz: 'ക്വിസ്', tab_cbse: '9–10 ക്ലാസ് കോർണർ',
    search_label: 'മൂലകം തിരയുക', search_ph: 'പേര്, പ്രതീകം അല്ലെങ്കിൽ നമ്പർ, ഉദാ. Na, 26, ഓക്സിജൻ',
    n_found: '{n} എണ്ണം കിട്ടി', no_match: 'ഒരു മൂലകവും കിട്ടിയില്ല. Fe പോലൊരു പ്രതീകമോ 26 പോലൊരു നമ്പറോ നോക്കൂ.',
    colour_by: 'നിറം എന്തിനനുസരിച്ച്', by_family: 'കുടുംബം', by_block: 'ബ്ലോക്ക്', by_state: 'അവസ്ഥ',
    highlight: 'എടുത്തുകാട്ടുക', hl_all: 'എല്ലാം കാണിക്കുക', grp_type: 'തരം',
    hl_metal: 'ലോഹങ്ങൾ', hl_nonmetal: 'അലോഹങ്ങൾ', hl_metalloid: 'ഉപലോഹങ്ങൾ', hl_solid: 'ഖരങ്ങൾ', hl_liquid: 'ദ്രാവകങ്ങൾ', hl_gas: 'വാതകങ്ങൾ', hl_radio: 'റേഡിയോആക്ടീവ് മൂലകങ്ങൾ', hl_first20: 'ആദ്യ 20 മൂലകങ്ങൾ',
    legend_hint: 'ഒരു നിറത്തിൽ ടാപ്പ് ചെയ്താൽ ആ കൂട്ടം എടുത്തുകാട്ടും. വീണ്ടും ടാപ്പ് ചെയ്താൽ എല്ലാം കാണാം.',
    axis_hint: 'നെടുകെയുള്ള കോളങ്ങൾ ഗ്രൂപ്പുകൾ (1–18). കുറുകെയുള്ള വരികൾ പീരിയഡുകൾ (1–7).',
    pt_aria: '118 മൂലകങ്ങളുടെ ആവർത്തനപ്പട്ടിക', tile_aria: '{name} ({s}), അറ്റോമിക നമ്പർ {n}',
    lanthanoids: 'ലാന്തനോയ്ഡുകൾ', actinoids: 'ആക്ടിനോയ്ഡുകൾ',
    cat_alkali: 'ആൽക്കലി ലോഹം', cat_alkaline: 'ആൽക്കലൈൻ എർത്ത് ലോഹം', cat_transition: 'സംക്രമണ ലോഹം', cat_post: 'മറ്റ് ലോഹം', cat_metalloid: 'ഉപലോഹം', cat_nonmetal: 'അലോഹം', cat_halogen: 'ഹാലൊജൻ', cat_noble: 'ഉൽകൃഷ്ട വാതകം', cat_lanthanoid: 'ലാന്തനോയ്ഡ്', cat_actinoid: 'ആക്ടിനോയ്ഡ്',
    block_name: '{b}-ബ്ലോക്ക്', state_solid: 'ഖരം', state_liquid: 'ദ്രാവകം', state_gas: 'വാതകം', state_unknown: 'അറിയില്ല',
    type_metal: 'ലോഹം', type_nonmetal: 'അലോഹം', type_metalloid: 'ഉപലോഹം',
    d_number: 'അറ്റോമിക നമ്പർ', d_mass: 'അറ്റോമിക മാസ് (u)', d_group: 'ഗ്രൂപ്പ്', d_period: 'പീരിയഡ്', d_family: 'കുടുംബം', d_type: 'തരം', d_state: 'മുറിയിലെ താപനിലയിൽ അവസ്ഥ', d_en: 'ഇലക്ട്രോനെഗറ്റിവിറ്റി (പോളിങ്)', d_config: 'ഇലക്ട്രോൺ വിന്യാസം', d_full: 'പൂർണമായി എഴുതിയാൽ', d_shells: 'ഷെല്ലുകളിലെ ഇലക്ട്രോണുകൾ', d_valence: 'സംയോജക ഇലക്ട്രോണുകൾ', d_valency: 'സംയോജകത', d_particles: 'ആറ്റത്തിനുള്ളിൽ',
    particles_val: '{p} പ്രോട്ടോണുകൾ, {n} ന്യൂട്രോണുകൾ, {e} ഇലക്ട്രോണുകൾ (മാസ് നമ്പർ {a})',
    not_known: 'അറിയില്ല', mass_note: '[ ] ൽ ഉള്ള മാസ്, ഏറ്റവും സ്ഥിരതയുള്ള ഐസോടോപ്പിന്റെ മാസ് നമ്പറാണ്.', latin_note: 'ഇതിന്റെ പ്രതീകം “{name}” എന്ന ലാറ്റിൻ പേരിൽ നിന്നാണ്.',
    radioactive: 'റേഡിയോആക്ടീവ്', predicted: 'ഇതിന്റെ ഏതാനും ആറ്റങ്ങൾ മാത്രമേ ഇതുവരെ നിർമിച്ചിട്ടുള്ളൂ, അതിനാൽ ചില വിവരങ്ങൾ അനുമാനങ്ങളാണ്.',
    uses_title: 'ഇത് നമ്മൾ എവിടെ കാണുന്നു', hear_name: 'ഇംഗ്ലീഷ് പേര് കേൾക്കുക', in_english: 'ഇംഗ്ലീഷിൽ: {name}',
    bohr_title: 'ബോർ മാതൃക', bohr_caption: 'ന്യൂക്ലിയസ്: {p} പ്രോട്ടോണുകളും {n} ന്യൂട്രോണുകളും. ഷെല്ലുകൾ: {s}.', bohr_only20: '9-ാം ക്ലാസിലെ പോലെ ആദ്യ 20 മൂലകങ്ങൾക്ക് ബോർ ചിത്രങ്ങൾ വരച്ചിരിക്കുന്നു.',
    featured_hint: 'ഏതെങ്കിലും മൂലകത്തിൽ ടാപ്പ് ചെയ്യുക', print_table: 'പട്ടിക പ്രിന്റ് ചെയ്യുക',
    quiz_mode: 'ചോദ്യത്തിന്റെ തരം', q_sym2name: 'പ്രതീകം → പേര്', q_name2sym: 'പേര് → പ്രതീകം', q_num2sym: 'നമ്പർ → പ്രതീകം', q_valency: 'സംയോജകത (ആദ്യ 20)',
    quiz_range: 'മൂലകങ്ങൾ', range_first: 'ആദ്യ {n}', range_all: 'എല്ലാ 118',
    ask_sym2name: '{s} ഏത് മൂലകത്തിന്റെ പ്രതീകമാണ്?', ask_name2sym: '{name} ന്റെ പ്രതീകം എന്താണ്?', ask_num2sym: 'അറ്റോമിക നമ്പർ {n} ഉള്ള മൂലകം ഏത്?', ask_valency: '{name} ({s}) ന്റെ സംയോജകത എത്ര?',
    q_progress: 'ചോദ്യം {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} എന്നാൽ {name}, അറ്റോമിക നമ്പർ {n}.',
    ex_lose: '{name} ({shells}) ന്റെ ബാഹ്യ ഷെല്ലിൽ {v} ഇലക്ട്രോണുകൾ ഉണ്ട്. അവയെ അത് വിട്ടുകൊടുക്കുന്നു, അതിനാൽ സംയോജകത {v}.',
    ex_gain: '{name} ({shells}) ന്റെ ബാഹ്യ ഷെല്ലിൽ {v} ഇലക്ട്രോണുകൾ ഉണ്ട്. 8 തികയ്ക്കാൻ {val} എണ്ണം കൂടി വേണം, അതിനാൽ സംയോജകത {val}.',
    ex_share: '{name} ({shells}) ന്റെ ബാഹ്യ ഷെല്ലിൽ {v} ഇലക്ട്രോണുകൾ ഉണ്ട്. അവയെ അത് പങ്കുവെക്കുന്നു, അതിനാൽ സംയോജകത {v}.',
    ex_full: '{name} ({shells}) ന്റെ ബാഹ്യ ഷെൽ നേരത്തേ നിറഞ്ഞതാണ്, അതിനാൽ സംയോജകത 0.',
    ex_h: 'ഹൈഡ്രജനിൽ 1 ഇലക്ട്രോൺ ഉണ്ട്. അതിന്റെ ഒരേയൊരു ഷെൽ നിറയാൻ 1 കൂടി വേണം, അതിനാൽ സംയോജകത 1.',
    round_done: 'റൗണ്ട് കഴിഞ്ഞു! {n} ൽ {c} ശരി.', best_score: 'മികച്ചത്: {b} / {n}', play_again: 'വീണ്ടും കളിക്കുക',
    msg_perfect: 'മുഴുവൻ മാർക്ക്! നിങ്ങൾ ആവർത്തനപ്പട്ടികയിലെ താരമാണ്.', msg_good: 'നന്നായി! തെറ്റുകൾ നോക്കി വീണ്ടും കളിക്കൂ.', msg_try: 'പരിശീലനം തുടരൂ: പട്ടികയിലെ മൂലകങ്ങൾ നോക്കി വീണ്ടും ശ്രമിക്കൂ.',
    quiz_keys: 'കീബോർഡ്: ഉത്തരത്തിന് 1–5, അടുത്ത ചോദ്യത്തിന് Enter അമർത്തുക.',
    cbse_first20: 'ആദ്യ 20 മൂലകങ്ങൾ: ഷെല്ലുകളും സംയോജകതയും', first20_hint: 'പേരിൽ ടാപ്പ് ചെയ്താൽ ആ മൂലകം പട്ടികയിൽ തുറക്കും.',
    col_no: 'ക്രമം', col_sym: 'പ്രതീകം', col_name: 'പേര്', col_massno: 'മാസ് നമ്പർ',
    how_valency_title: 'സംയോജകത കണ്ടെത്തുന്ന വിധം',
    how_valency: 'ഏറ്റവും പുറത്തെ ഷെല്ലിലെ ഇലക്ട്രോണുകൾ എണ്ണുക. 1, 2, 3 അല്ലെങ്കിൽ 4 ആണെങ്കിൽ സംയോജകത അതേ സംഖ്യ. 5, 6 അല്ലെങ്കിൽ 7 ആണെങ്കിൽ 8 ൽ നിന്ന് ആ സംഖ്യ കുറച്ചാൽ സംയോജകത കിട്ടും. ഷെൽ നിറഞ്ഞതാണെങ്കിൽ (ഹീലിയത്തിൽ 2, മറ്റുള്ളവയിൽ 8) സംയോജകത 0.',
    valency_eg: 'ഉദാഹരണം: ക്ലോറിൻ 2, 8, 7. ബാഹ്യ ഷെല്ലിൽ 7 ഇലക്ട്രോണുകൾ, അതിനാൽ സംയോജകത 8 − 7 = 1. സോഡിയത്തിന്റെ (2, 8, 1) സംയോജകതയും 1, അതുകൊണ്ടാണ് ഉപ്പ് NaCl ആകുന്നത്.',
    triads_title: 'ഡോബറൈനറുടെ ത്രികങ്ങൾ', triads_desc: 'സമാനമായ മൂന്ന് മൂലകങ്ങളുടെ ഓരോ കൂട്ടത്തിലും നടുവിലുള്ളതിന്റെ മാസ് മറ്റ് രണ്ടിന്റെയും ശരാശരിയോട് അടുത്തായിരിക്കും.',
    col_triad: 'ത്രികം', col_avg: '1-ാമത്തെയും 3-ാമത്തെയും ശരാശരി', col_middle: 'നടുവിലുള്ളതിന്റെ മാസ്',
    mend_title: 'മെൻഡലീഫിന്റെ പട്ടികയും ആധുനിക ആവർത്തനപ്പട്ടികയും', col_point: 'കാര്യം', col_mend: 'മെൻഡലീഫ് (1869)', col_modern: 'ആധുനികം (മോസ്‌ലി, 1913)',
    trends_title: 'ഓർത്തിരിക്കേണ്ട പ്രവണതകൾ',
    print_ws: 'വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യുക', ws_title: 'വർക്ക്ഷീറ്റ്: ആദ്യ 20 മൂലകങ്ങൾ', ws_line: 'പേര്: ______________   ക്ലാസ്: ______   തീയതി: __________',
    ws_instr: 'ഒഴിഞ്ഞ കള്ളികൾ പൂരിപ്പിക്കുക. ഷെല്ലുകളിൽ നിന്ന് സംയോജകത കണ്ടെത്തുക.', ws_key: 'ഉത്തരസൂചിക'
  },
  ur: {
    app_title: 'دوری جدول ایکسپلورر',
    intro: 'تمام 118 عناصر کو جانیں: کسی بھی عنصر پر ٹیپ کر کے اس کی الیکٹرانی ترتیب، گرفت اور بوہر ماڈل دیکھیں، پھر مختصر کوئز سے خود کو پرکھیں۔',
    how_title: 'استعمال کیسے کریں · کلاس کے لیے تجاویز',
    tab_table: 'دوری جدول', tab_quiz: 'کوئز', tab_cbse: 'جماعت 9–10 کا گوشہ',
    search_label: 'عنصر تلاش کریں', search_ph: 'نام، علامت یا نمبر، جیسے Na، 26، آکسیجن',
    n_found: '{n} ملے', no_match: 'کوئی عنصر نہیں ملا۔ Fe جیسی علامت یا 26 جیسا نمبر لکھ کر دیکھیں۔',
    colour_by: 'رنگ کس بنیاد پر', by_family: 'خاندان', by_block: 'بلاک', by_state: 'حالت',
    highlight: 'نمایاں کریں', hl_all: 'سب دکھائیں', grp_type: 'قسم',
    hl_metal: 'دھاتیں', hl_nonmetal: 'غیر دھاتیں', hl_metalloid: 'نیم دھاتیں', hl_solid: 'ٹھوس', hl_liquid: 'مائع', hl_gas: 'گیسیں', hl_radio: 'تابکار', hl_first20: 'پہلے 20 عناصر',
    legend_hint: 'کسی رنگ پر ٹیپ کریں تو وہ گروہ نمایاں ہو جائے گا۔ دوبارہ ٹیپ کرنے پر سب نظر آئیں گے۔',
    axis_hint: 'کھڑے کالم گروپ ہیں (1–18)۔ آڑی قطاریں پیریڈ ہیں (1–7)۔',
    pt_aria: '118 عناصر کا دوری جدول', tile_aria: '{name} ({s})، ایٹمی نمبر {n}',
    lanthanoids: 'لینتھینائیڈ', actinoids: 'ایکٹینائیڈ',
    cat_alkali: 'الکلی دھات', cat_alkaline: 'الکلائن ارتھ دھات', cat_transition: 'عبوری دھات', cat_post: 'دیگر دھات', cat_metalloid: 'نیم دھات', cat_nonmetal: 'غیر دھات', cat_halogen: 'ہیلوجن', cat_noble: 'نوبل گیس', cat_lanthanoid: 'لینتھینائیڈ', cat_actinoid: 'ایکٹینائیڈ',
    block_name: '{b} بلاک', state_solid: 'ٹھوس', state_liquid: 'مائع', state_gas: 'گیس', state_unknown: 'معلوم نہیں',
    type_metal: 'دھات', type_nonmetal: 'غیر دھات', type_metalloid: 'نیم دھات',
    d_number: 'ایٹمی نمبر', d_mass: 'ایٹمی کمیت (u)', d_group: 'گروپ', d_period: 'پیریڈ', d_family: 'خاندان', d_type: 'قسم', d_state: 'کمرے کے درجۂ حرارت پر حالت', d_en: 'برقی منفیت (پالنگ)', d_config: 'الیکٹرانی ترتیب', d_full: 'پوری لکھیں تو', d_shells: 'شیلوں میں الیکٹران', d_valence: 'گرفتی الیکٹران', d_valency: 'گرفت', d_particles: 'ایٹم کے اندر',
    particles_val: '{p} پروٹون، {n} نیوٹران، {e} الیکٹران (کمیتی عدد {a})',
    not_known: 'معلوم نہیں', mass_note: '[ ] میں لکھی کمیت سب سے پائیدار آئسوٹوپ کا کمیتی عدد ہے۔', latin_note: 'اس کی علامت لاطینی نام “{name}” سے آئی ہے۔',
    radioactive: 'تابکار', predicted: 'اس کے اب تک صرف چند ایٹم بنے ہیں، اس لیے کچھ باتیں اندازے ہیں۔',
    uses_title: 'یہ ہمیں کہاں ملتا ہے', hear_name: 'انگریزی نام سنیں', in_english: 'انگریزی میں: {name}',
    bohr_title: 'بوہر ماڈل', bohr_caption: 'مرکزہ: {p} پروٹون اور {n} نیوٹران۔ شیل: {s}۔', bohr_only20: 'جماعت 9 کی طرح پہلے 20 عناصر کے بوہر خاکے بنائے گئے ہیں۔',
    featured_hint: 'کسی بھی عنصر پر ٹیپ کریں', print_table: 'جدول پرنٹ کریں',
    quiz_mode: 'سوال کی قسم', q_sym2name: 'علامت ← نام', q_name2sym: 'نام ← علامت', q_num2sym: 'نمبر ← علامت', q_valency: 'گرفت (پہلے 20)',
    quiz_range: 'عناصر', range_first: 'پہلے {n}', range_all: 'تمام 118',
    ask_sym2name: '{s} کس عنصر کی علامت ہے؟', ask_name2sym: '{name} کی علامت کیا ہے؟', ask_num2sym: 'ایٹمی نمبر {n} کس عنصر کا ہے؟', ask_valency: '{name} ({s}) کی گرفت کیا ہے؟',
    q_progress: 'سوال {i} / {n}', score_val: '{c} / {n}', ans_fact: '{s} یعنی {name}، ایٹمی نمبر {n}۔',
    ex_lose: '{name} ({shells}) کے بیرونی شیل میں {v} الیکٹران ہیں۔ یہ انہیں دے دیتا ہے، اس لیے گرفت {v} ہے۔',
    ex_gain: '{name} ({shells}) کے بیرونی شیل میں {v} الیکٹران ہیں۔ 8 پورے کرنے کے لیے اسے {val} اور چاہئیں، اس لیے گرفت {val} ہے۔',
    ex_share: '{name} ({shells}) کے بیرونی شیل میں {v} الیکٹران ہیں۔ یہ انہیں ساجھا کرتا ہے، اس لیے گرفت {v} ہے۔',
    ex_full: '{name} ({shells}) کا بیرونی شیل پہلے سے بھرا ہے، اس لیے گرفت 0 ہے۔',
    ex_h: 'ہائیڈروجن میں 1 الیکٹران ہے۔ اس کے واحد شیل کو بھرنے کے لیے 1 اور چاہیے، اس لیے گرفت 1 ہے۔',
    round_done: 'راؤنڈ ختم! {n} میں سے {c} درست۔', best_score: 'بہترین: {b} / {n}', play_again: 'دوبارہ کھیلیں',
    msg_perfect: 'پورے نمبر! آپ دوری جدول کے اسٹار ہیں۔', msg_good: 'شاباش! غلطیاں دیکھیں اور دوبارہ کھیلیں۔', msg_try: 'مشق جاری رکھیں: جدول میں عناصر دیکھیں، پھر دوبارہ کوشش کریں۔',
    quiz_keys: 'کی بورڈ: جواب کے لیے 1–5 دبائیں اور اگلے سوال کے لیے Enter۔',
    cbse_first20: 'پہلے 20 عناصر: شیل اور گرفت', first20_hint: 'کسی نام پر ٹیپ کریں، وہ عنصر جدول میں کھل جائے گا۔',
    col_no: 'نمبر', col_sym: 'علامت', col_name: 'نام', col_massno: 'کمیتی عدد',
    how_valency_title: 'گرفت کیسے معلوم کریں',
    how_valency: 'سب سے بیرونی شیل کے الیکٹران گنیں۔ اگر 1، 2، 3 یا 4 ہوں تو گرفت وہی عدد ہے۔ اگر 5، 6 یا 7 ہوں تو 8 میں سے وہ عدد گھٹانے پر گرفت ملتی ہے۔ شیل بھرا ہو (ہیلیم میں 2، باقی میں 8) تو گرفت 0 ہے۔',
    valency_eg: 'مثال: کلورین 2، 8، 7 ہے۔ بیرونی شیل میں 7 الیکٹران، اس لیے گرفت 8 − 7 = 1۔ سوڈیم (2، 8، 1) کی گرفت بھی 1 ہے، اسی لیے نمک NaCl ہے۔',
    triads_title: 'ڈوبرائنر کے ثلاثے', triads_desc: 'تین ملتے جلتے عناصر کے ہر گروہ میں درمیانی عنصر کی کمیت باقی دو کی اوسط کے تقریباً برابر ہوتی ہے۔',
    col_triad: 'ثلاثہ', col_avg: 'پہلے اور تیسرے کی اوسط', col_middle: 'درمیانی کی کمیت',
    mend_title: 'مینڈلیف کا جدول اور جدید دوری جدول', col_point: 'نکتہ', col_mend: 'مینڈلیف (1869)', col_modern: 'جدید (موزلے، 1913)',
    trends_title: 'یاد رکھنے والے رجحانات',
    print_ws: 'ورک شیٹ پرنٹ کریں', ws_title: 'ورک شیٹ: پہلے 20 عناصر', ws_line: 'نام: ______________   جماعت: ______   تاریخ: __________',
    ws_instr: 'خالی خانے بھریں۔ شیلوں سے گرفت معلوم کریں۔', ws_key: 'جوابات'
  }
};
