/* UI strings for Data Explorer. Keys are identical in all 12 languages. */
window.APP_STRINGS = {
  en: {
    app_title: 'Data Explorer',
    intro: 'Open any CSV file and see every column at a glance: types, missing values, mean, median, top values, filters, sorting and correlation.',
    privacy: 'Your data stays on this device. Nothing is uploaded.',
    howto: 'How to use / ideas',
    tip_1: 'Open your own CSV file, drop it on the box, paste rows from Excel or Google Sheets, or try a sample.',
    tip_2: 'Column profiles show each column at a glance: how many values, how many are missing, the smallest, largest, mean and median, and the most common values.',
    tip_3: 'In the data table, tap a column name to sort, search all columns and add filters (contains, between, missing). Download only the filtered rows as a new CSV.',
    tip_4: 'Office idea: open last month\'s sales file, filter one region or payment type, check totals and missing bills, then download those rows for your report.',
    tip_5: 'Class idea: load the class marks sample. Students work out the mean and median of Maths by hand, then check with the app. Who is far from the rest? Which subjects rise together?',
    tip_6: 'Excel or Google Sheets file? Save it as CSV first (File → Save as / Download → CSV). Big files with 50,000 rows work too; the table shows 100 rows a page.',
    words_title: 'Words to know',
    w_dataset: 'Dataset', w_dataset_d: 'A table of data, like one sheet in Excel. This app reads it from a CSV file.',
    w_row: 'Row', w_row_d: 'One record in the table: one student, one bill, one state.',
    w_column: 'Column', w_column_d: 'One kind of information for every row: name, marks, date. Each column has a type: number, text, date or yes/no.',
    w_missing: 'Missing value', w_missing_d: 'An empty cell, or text like NA, N/A or "-". It is counted, then left out of sums and averages.',
    w_mean: 'Mean (average)', w_mean_d: 'Add all the numbers and divide by how many there are.',
    w_median: 'Median', w_median_d: 'The middle number after sorting. One very big value cannot pull it far, so it is often fairer than the mean.',
    w_sd: 'Standard deviation', w_sd_d: 'How spread out the numbers are around the mean. Small: values are close together. Big: values are far apart. (This app uses the sample formula, dividing by n − 1.)',
    w_corr: 'Correlation (r)', w_corr_d: 'A number from −1 to +1 that shows whether two number columns rise and fall together. It does not prove that one causes the other.',
    load_title: 'Open data',
    drop_here: 'Drop a CSV file here, or',
    open_csv: 'Open CSV file',
    paste_data: 'Paste data',
    excel_hint: 'Excel or Sheets file? Choose File → Save as (or Download) → CSV. Your file stays on this device.',
    paste_label: 'Paste rows from Excel, Google Sheets or a CSV file',
    paste_ph: 'Name,Marks\nAarav,78\nAnanya,92',
    paste_use: 'Use this data',
    samples: 'Or try a sample:',
    sample_marks: 'Class marks', sample_shop: 'Shop sales (September)', sample_rain: 'Monsoon rainfall by state',
    tabs_label: 'Views',
    tab_cols: 'Column profiles', tab_table: 'Data table', tab_corr: 'Correlation',
    search_ph: 'Search in all columns…',
    choose_cols: 'Choose columns',
    export_csv: 'Download these rows (CSV)',
    filter_title: 'Filters',
    f_col: 'Column', f_op: 'Rule', f_value: 'Value', f_from: 'From', f_to: 'To',
    add_filter: 'Add filter',
    sort_hint: 'Tap a column name to sort it (▲ low to high, ▼ high to low).',
    corr_title: 'How do the number columns move together?',
    corr_intro: 'Correlation (r) goes from −1 to +1. Near +1: when one goes up, the other usually goes up. Near −1: when one goes up, the other usually goes down. Near 0: no straight-line link.',
    col_n: 'Column {n}',
    too_big_save: 'This file is too big to remember. It works now, but you will need to open it again next time.',
    empty_file: 'This file is empty. Pick another file or try a sample.',
    only_header: 'This file has column names but no rows of data.',
    excel_file: 'This looks like an Excel file. In Excel choose File → Save as → CSV, then open that CSV here.',
    read_error: 'Could not read this file. Is it a CSV text file?',
    pasted_data: 'Pasted data',
    summary: '{rows} rows, {cols} columns, {pct}% missing',
    sep_used: 'Separator found: {sep}',
    sep_comma: 'comma (,)', sep_semicolon: 'semicolon (;)', sep_tab: 'tab', sep_pipe: 'pipe (|)',
    ragged_note: '{n} rows had a different number of cells. Empty cells were added so every row fits.',
    noname_note: '{n} columns had no name, so they got a number.',
    type_number: 'Number', type_text: 'Text', type_date: 'Date', type_bool: 'Yes / No', type_empty: 'Empty',
    st_count: 'Values', st_missing: 'Missing', st_unique: 'Different values', st_min: 'Smallest', st_max: 'Largest', st_mean: 'Mean', st_median: 'Median', st_sd: 'Standard deviation', st_sum: 'Sum', st_earliest: 'Earliest', st_latest: 'Latest', st_top: 'Most common',
    invalid_dates: '{n} values are not dates (left out)',
    invalid_nums: '{n} values are not numbers (left out)',
    shown_rows: 'Showing rows {from}–{to} of {n}',
    filtered_of: '({n} rows in the file)',
    shown_none: 'No rows match. Try removing a filter.',
    page_of: 'Page {p} of {n}',
    op_contains: 'contains', op_equals: 'is exactly', op_between: 'is between', op_missing: 'is missing', op_notmissing: 'is not missing',
    need_value: 'Type a value first.',
    remove_filter: 'Remove filter',
    no_filters: 'No filters. Showing every row.',
    clear_filters: 'Clear all filters',
    show_all: 'Show all', hide_all: 'Hide all',
    exported_n: '{n} rows downloaded',
    r_strong_pos: 'strong positive', r_mod_pos: 'moderate positive', r_weak_pos: 'weak positive', r_none: 'almost no link', r_weak_neg: 'weak negative', r_mod_neg: 'moderate negative', r_strong_neg: 'strong negative',
    corr_read: '{a} and {b}: {kind} (r = {r}).',
    corr_up: 'When {a} is higher, {b} is usually higher too.',
    corr_down: 'When {a} is higher, {b} is usually lower.',
    corr_flat: 'Knowing {a} tells you little about {b}.',
    corr_need: 'You need at least 2 number columns to compare.',
    corr_limit: 'Showing the first {n} number columns.',
    corr_neg_label: '−1 opposite', corr_pos_label: '+1 together',
    corr_pick: 'Tap a square to read it in words.',
    corr_self: 'Every column matches itself perfectly (r = 1).',
    corr_warn: 'A link does not prove that one causes the other.',
    corr_na: 'Not enough filled rows to compare these two columns.',
    corr_strongest: 'Strongest links'
  },
  hi: {
    app_title: 'डेटा एक्सप्लोरर',
    intro: 'कोई भी CSV फ़ाइल खोलें और हर कॉलम एक नज़र में देखें: प्रकार, खाली मान, औसत, माध्यिका, सबसे आम मान, फ़िल्टर, क्रम और सहसंबंध।',
    privacy: 'आपका डेटा इसी डिवाइस पर रहता है। कुछ भी अपलोड नहीं होता।',
    howto: 'कैसे इस्तेमाल करें / सुझाव',
    tip_1: 'अपनी CSV फ़ाइल खोलें, उसे बॉक्स पर छोड़ें, Excel या Google Sheets से पंक्तियाँ पेस्ट करें, या कोई नमूना आज़माएँ।',
    tip_2: 'कॉलम प्रोफ़ाइल में हर कॉलम का सार दिखता है: कितने मान, कितने खाली, सबसे छोटा, सबसे बड़ा, औसत, माध्यिका और सबसे आम मान।',
    tip_3: 'डेटा तालिका में क्रम बदलने के लिए कॉलम के नाम पर टैप करें, सभी कॉलम में खोजें और फ़िल्टर लगाएँ (शामिल है, के बीच, खाली)। सिर्फ़ फ़िल्टर की गई पंक्तियाँ नई CSV में डाउनलोड करें।',
    tip_4: 'दफ़्तर के लिए: पिछले महीने की बिक्री की फ़ाइल खोलें, एक क्षेत्र या भुगतान का तरीका छाँटें, कुल और छूटे बिल जाँचें, फिर रिपोर्ट के लिए वे पंक्तियाँ डाउनलोड करें।',
    tip_5: 'कक्षा के लिए: कक्षा के अंक वाला नमूना खोलें। विद्यार्थी गणित का औसत और माध्यिका हाथ से निकालें, फिर ऐप से मिलाएँ। किसके अंक बाक़ी सबसे बहुत अलग हैं? कौन-से विषय साथ-साथ बढ़ते हैं?',
    tip_6: 'Excel या Google Sheets फ़ाइल है? पहले उसे CSV में सेव करें (File → Save as / Download → CSV)। 50,000 पंक्तियों वाली बड़ी फ़ाइल भी चलती है; तालिका एक पेज में 100 पंक्तियाँ दिखाती है।',
    words_title: 'ज़रूरी शब्द',
    w_dataset: 'डेटासेट', w_dataset_d: 'डेटा की एक तालिका, जैसे Excel की एक शीट। यह ऐप इसे CSV फ़ाइल से पढ़ता है।',
    w_row: 'पंक्ति', w_row_d: 'तालिका का एक रिकॉर्ड: एक विद्यार्थी, एक बिल, एक राज्य।',
    w_column: 'कॉलम', w_column_d: 'हर पंक्ति के लिए एक तरह की जानकारी: नाम, अंक, तारीख। हर कॉलम का एक प्रकार होता है: संख्या, शब्द, तारीख या हाँ/नहीं।',
    w_missing: 'खाली मान', w_missing_d: 'खाली सेल, या NA, N/A, "-" जैसा लिखा हो। इसे गिना जाता है, फिर जोड़ और औसत से बाहर रखा जाता है।',
    w_mean: 'औसत (माध्य)', w_mean_d: 'सभी संख्याएँ जोड़ें और उनकी गिनती से भाग दें।',
    w_median: 'माध्यिका', w_median_d: 'क्रम से लगाने पर बीच वाली संख्या। एक बहुत बड़ा मान इसे ज़्यादा नहीं खींच पाता, इसलिए यह अक्सर औसत से ज़्यादा सही तस्वीर देती है।',
    w_sd: 'मानक विचलन', w_sd_d: 'संख्याएँ औसत के आसपास कितनी फैली हैं। छोटा: मान पास-पास हैं। बड़ा: मान दूर-दूर हैं। (यह ऐप नमूने वाला सूत्र लेता है, n − 1 से भाग।)',
    w_corr: 'सहसंबंध (r)', w_corr_d: '−1 से +1 तक की संख्या, जो बताती है कि दो संख्या वाले कॉलम साथ-साथ बढ़ते-घटते हैं या नहीं। इससे यह साबित नहीं होता कि एक, दूसरे का कारण है।',
    load_title: 'डेटा खोलें',
    drop_here: 'CSV फ़ाइल यहाँ छोड़ें, या',
    open_csv: 'CSV फ़ाइल खोलें',
    paste_data: 'डेटा पेस्ट करें',
    excel_hint: 'Excel या Sheets फ़ाइल है? File → Save as (या Download) → CSV चुनें। आपकी फ़ाइल इसी डिवाइस पर रहती है।',
    paste_label: 'Excel, Google Sheets या CSV फ़ाइल से पंक्तियाँ पेस्ट करें',
    paste_ph: 'नाम,अंक\nआरव,78\nअनन्या,92',
    paste_use: 'यह डेटा इस्तेमाल करें',
    samples: 'या कोई नमूना आज़माएँ:',
    sample_marks: 'कक्षा के अंक', sample_shop: 'दुकान की बिक्री (सितंबर)', sample_rain: 'राज्यों में मानसून की बारिश',
    tabs_label: 'देखने के तरीके',
    tab_cols: 'कॉलम प्रोफ़ाइल', tab_table: 'डेटा तालिका', tab_corr: 'सहसंबंध',
    search_ph: 'सभी कॉलम में खोजें…',
    choose_cols: 'कॉलम चुनें',
    export_csv: 'ये पंक्तियाँ डाउनलोड करें (CSV)',
    filter_title: 'फ़िल्टर',
    f_col: 'कॉलम', f_op: 'नियम', f_value: 'मान', f_from: 'से', f_to: 'तक',
    add_filter: 'फ़िल्टर जोड़ें',
    sort_hint: 'क्रम बदलने के लिए कॉलम के नाम पर टैप करें (▲ छोटे से बड़ा, ▼ बड़े से छोटा)।',
    corr_title: 'संख्या वाले कॉलम साथ-साथ कैसे चलते हैं?',
    corr_intro: 'सहसंबंध (r) −1 से +1 तक होता है। +1 के पास: एक बढ़े तो दूसरा भी अक्सर बढ़ता है। −1 के पास: एक बढ़े तो दूसरा अक्सर घटता है। 0 के पास: कोई सीधा रिश्ता नहीं।',
    col_n: 'कॉलम {n}',
    too_big_save: 'यह फ़ाइल याद रखने के लिए बहुत बड़ी है। अभी काम करेगी, पर अगली बार फिर से खोलनी होगी।',
    empty_file: 'यह फ़ाइल खाली है। दूसरी फ़ाइल चुनें या कोई नमूना आज़माएँ।',
    only_header: 'इस फ़ाइल में कॉलम के नाम हैं, पर डेटा की कोई पंक्ति नहीं है।',
    excel_file: 'यह Excel फ़ाइल लगती है। Excel में File → Save as → CSV चुनें, फिर वह CSV यहाँ खोलें।',
    read_error: 'यह फ़ाइल पढ़ी नहीं जा सकी। क्या यह CSV टेक्स्ट फ़ाइल है?',
    pasted_data: 'पेस्ट किया गया डेटा',
    summary: '{rows} पंक्तियाँ, {cols} कॉलम, {pct}% खाली',
    sep_used: 'अलग करने वाला चिह्न: {sep}',
    sep_comma: 'कॉमा (,)', sep_semicolon: 'सेमीकोलन (;)', sep_tab: 'टैब', sep_pipe: 'पाइप (|)',
    ragged_note: '{n} पंक्तियों में सेल की गिनती अलग थी। हर पंक्ति पूरी करने के लिए खाली सेल जोड़े गए।',
    noname_note: '{n} कॉलम का कोई नाम नहीं था, इसलिए उन्हें नंबर दिया गया।',
    type_number: 'संख्या', type_text: 'शब्द', type_date: 'तारीख', type_bool: 'हाँ / नहीं', type_empty: 'खाली',
    st_count: 'मान', st_missing: 'खाली', st_unique: 'अलग-अलग मान', st_min: 'सबसे छोटा', st_max: 'सबसे बड़ा', st_mean: 'औसत', st_median: 'माध्यिका', st_sd: 'मानक विचलन', st_sum: 'जोड़', st_earliest: 'सबसे पहली', st_latest: 'सबसे बाद की', st_top: 'सबसे आम',
    invalid_dates: '{n} मान तारीख नहीं हैं (छोड़ दिए गए)',
    invalid_nums: '{n} मान संख्या नहीं हैं (छोड़ दिए गए)',
    shown_rows: '{n} में से पंक्तियाँ {from}–{to} दिख रही हैं',
    filtered_of: '(फ़ाइल में {n} पंक्तियाँ)',
    shown_none: 'कोई पंक्ति मेल नहीं खाती। कोई फ़िल्टर हटाकर देखें।',
    page_of: 'पेज {p} / {n}',
    op_contains: 'में शामिल है', op_equals: 'ठीक यही है', op_between: 'के बीच है', op_missing: 'खाली है', op_notmissing: 'खाली नहीं है',
    need_value: 'पहले एक मान लिखें।',
    remove_filter: 'फ़िल्टर हटाएँ',
    no_filters: 'कोई फ़िल्टर नहीं। सभी पंक्तियाँ दिख रही हैं।',
    clear_filters: 'सभी फ़िल्टर हटाएँ',
    show_all: 'सब दिखाएँ', hide_all: 'सब छिपाएँ',
    exported_n: '{n} पंक्तियाँ डाउनलोड हुईं',
    r_strong_pos: 'मज़बूत धनात्मक', r_mod_pos: 'मध्यम धनात्मक', r_weak_pos: 'कमज़ोर धनात्मक', r_none: 'लगभग कोई संबंध नहीं', r_weak_neg: 'कमज़ोर ऋणात्मक', r_mod_neg: 'मध्यम ऋणात्मक', r_strong_neg: 'मज़बूत ऋणात्मक',
    corr_read: '{a} और {b}: {kind} (r = {r})।',
    corr_up: 'जब {a} ज़्यादा होता है, तो {b} भी अक्सर ज़्यादा होता है।',
    corr_down: 'जब {a} ज़्यादा होता है, तो {b} अक्सर कम होता है।',
    corr_flat: '{a} जानकर {b} के बारे में ज़्यादा पता नहीं चलता।',
    corr_need: 'तुलना के लिए कम से कम 2 संख्या वाले कॉलम चाहिए।',
    corr_limit: 'पहले {n} संख्या वाले कॉलम दिख रहे हैं।',
    corr_neg_label: '−1 उलटा', corr_pos_label: '+1 साथ-साथ',
    corr_pick: 'किसी खाने पर टैप करें और उसका मतलब शब्दों में पढ़ें।',
    corr_self: 'हर कॉलम खुद से पूरा मेल खाता है (r = 1)।',
    corr_warn: 'संबंध होने से यह साबित नहीं होता कि एक, दूसरे का कारण है।',
    corr_na: 'इन दो कॉलम की तुलना के लिए काफ़ी भरी हुई पंक्तियाँ नहीं हैं।',
    corr_strongest: 'सबसे मज़बूत संबंध'
  },
  bn: {
    app_title: 'ডেটা এক্সপ্লোরার',
    intro: 'যেকোনো CSV ফাইল খুলুন আর প্রতিটি কলাম এক নজরে দেখুন: ধরন, ফাঁকা ঘর, গড়, মধ্যমা, সবচেয়ে বেশি আসা মান, ফিল্টার, সাজানো আর সহসম্পর্ক।',
    privacy: 'আপনার ডেটা এই ডিভাইসেই থাকে। কিছুই আপলোড হয় না।',
    howto: 'কীভাবে ব্যবহার করবেন / কিছু আইডিয়া',
    tip_1: 'নিজের CSV ফাইল খুলুন, বাক্সে ছেড়ে দিন, Excel বা Google Sheets থেকে সারি পেস্ট করুন, অথবা একটি নমুনা চালিয়ে দেখুন।',
    tip_2: 'কলাম প্রোফাইলে প্রতিটি কলামের সারাংশ দেখা যায়: কতগুলো মান, কতগুলো ফাঁকা, সবচেয়ে ছোট, সবচেয়ে বড়, গড়, মধ্যমা আর সবচেয়ে বেশি আসা মান।',
    tip_3: 'ডেটা টেবিলে সাজাতে কলামের নামে ট্যাপ করুন, সব কলামে খুঁজুন আর ফিল্টার দিন (আছে, মাঝে, ফাঁকা)। শুধু ফিল্টার করা সারিগুলো নতুন CSV হিসেবে ডাউনলোড করুন।',
    tip_4: 'অফিসের জন্য: গত মাসের বিক্রির ফাইল খুলুন, একটি অঞ্চল বা পেমেন্টের ধরন ফিল্টার করুন, মোট আর বাদ পড়া বিল দেখুন, তারপর রিপোর্টের জন্য সেই সারিগুলো ডাউনলোড করুন।',
    tip_5: 'ক্লাসের জন্য: ক্লাসের নম্বরের নমুনা খুলুন। শিক্ষার্থীরা হাতে গণিতের গড় আর মধ্যমা বের করুক, তারপর অ্যাপের সঙ্গে মেলাক। কার নম্বর বাকিদের থেকে অনেক আলাদা? কোন বিষয়গুলো একসঙ্গে বাড়ে?',
    tip_6: 'Excel বা Google Sheets ফাইল? আগে CSV হিসেবে সেভ করুন (File → Save as / Download → CSV)। 50,000 সারির বড় ফাইলও চলে; টেবিল প্রতি পাতায় 100টি সারি দেখায়।',
    words_title: 'জরুরি শব্দ',
    w_dataset: 'ডেটাসেট', w_dataset_d: 'ডেটার একটি টেবিল, যেমন Excel-এর একটি শিট। এই অ্যাপ এটি CSV ফাইল থেকে পড়ে।',
    w_row: 'সারি', w_row_d: 'টেবিলের একটি রেকর্ড: একজন শিক্ষার্থী, একটি বিল, একটি রাজ্য।',
    w_column: 'কলাম', w_column_d: 'প্রতিটি সারির একই ধরনের তথ্য: নাম, নম্বর, তারিখ। প্রতিটি কলামের একটি ধরন থাকে: সংখ্যা, লেখা, তারিখ বা হ্যাঁ/না।',
    w_missing: 'ফাঁকা মান', w_missing_d: 'খালি ঘর, অথবা NA, N/A, "-" লেখা। এগুলো গোনা হয়, তারপর যোগফল আর গড় থেকে বাদ রাখা হয়।',
    w_mean: 'গড়', w_mean_d: 'সব সংখ্যা যোগ করে মোট কয়টি আছে তা দিয়ে ভাগ করুন।',
    w_median: 'মধ্যমা', w_median_d: 'সাজানোর পর মাঝের সংখ্যা। একটি খুব বড় মান একে বেশি টানতে পারে না, তাই এটি প্রায়ই গড়ের চেয়ে ভালো ছবি দেয়।',
    w_sd: 'মানক বিচ্যুতি', w_sd_d: 'সংখ্যাগুলো গড়ের চারপাশে কতটা ছড়ানো। ছোট: মানগুলো কাছাকাছি। বড়: মানগুলো দূরে দূরে। (এই অ্যাপ নমুনার সূত্র ব্যবহার করে, n − 1 দিয়ে ভাগ।)',
    w_corr: 'সহসম্পর্ক (r)', w_corr_d: '−1 থেকে +1 পর্যন্ত একটি সংখ্যা, যা দেখায় দুটি সংখ্যার কলাম একসঙ্গে বাড়ে-কমে কি না। এতে প্রমাণ হয় না যে একটি অন্যটির কারণ।',
    load_title: 'ডেটা খুলুন',
    drop_here: 'CSV ফাইল এখানে ছেড়ে দিন, অথবা',
    open_csv: 'CSV ফাইল খুলুন',
    paste_data: 'ডেটা পেস্ট করুন',
    excel_hint: 'Excel বা Sheets ফাইল? File → Save as (বা Download) → CSV বেছে নিন। আপনার ফাইল এই ডিভাইসেই থাকে।',
    paste_label: 'Excel, Google Sheets বা CSV ফাইল থেকে সারি পেস্ট করুন',
    paste_ph: 'নাম,নম্বর\nআরভ,78\nঅনন্যা,92',
    paste_use: 'এই ডেটা ব্যবহার করুন',
    samples: 'অথবা একটি নমুনা দেখুন:',
    sample_marks: 'ক্লাসের নম্বর', sample_shop: 'দোকানের বিক্রি (সেপ্টেম্বর)', sample_rain: 'রাজ্যভিত্তিক বর্ষার বৃষ্টি',
    tabs_label: 'দেখার ধরন',
    tab_cols: 'কলাম প্রোফাইল', tab_table: 'ডেটা টেবিল', tab_corr: 'সহসম্পর্ক',
    search_ph: 'সব কলামে খুঁজুন…',
    choose_cols: 'কলাম বাছুন',
    export_csv: 'এই সারিগুলো ডাউনলোড করুন (CSV)',
    filter_title: 'ফিল্টার',
    f_col: 'কলাম', f_op: 'নিয়ম', f_value: 'মান', f_from: 'থেকে', f_to: 'পর্যন্ত',
    add_filter: 'ফিল্টার যোগ করুন',
    sort_hint: 'সাজাতে কলামের নামে ট্যাপ করুন (▲ ছোট থেকে বড়, ▼ বড় থেকে ছোট)।',
    corr_title: 'সংখ্যার কলামগুলো একসঙ্গে কীভাবে চলে?',
    corr_intro: 'সহসম্পর্ক (r) −1 থেকে +1 পর্যন্ত। +1-এর কাছে: একটি বাড়লে অন্যটিও সাধারণত বাড়ে। −1-এর কাছে: একটি বাড়লে অন্যটি সাধারণত কমে। 0-এর কাছে: সরল কোনো সম্পর্ক নেই।',
    col_n: 'কলাম {n}',
    too_big_save: 'ফাইলটি মনে রাখার জন্য খুব বড়। এখন কাজ করবে, কিন্তু পরের বার আবার খুলতে হবে।',
    empty_file: 'এই ফাইলটি ফাঁকা। অন্য ফাইল বাছুন বা একটি নমুনা দেখুন।',
    only_header: 'এই ফাইলে কলামের নাম আছে, কিন্তু ডেটার কোনো সারি নেই।',
    excel_file: 'এটি Excel ফাইল মনে হচ্ছে। Excel-এ File → Save as → CSV বেছে নিন, তারপর সেই CSV এখানে খুলুন।',
    read_error: 'ফাইলটি পড়া গেল না। এটি কি CSV টেক্সট ফাইল?',
    pasted_data: 'পেস্ট করা ডেটা',
    summary: '{rows}টি সারি, {cols}টি কলাম, {pct}% ফাঁকা',
    sep_used: 'আলাদা করার চিহ্ন: {sep}',
    sep_comma: 'কমা (,)', sep_semicolon: 'সেমিকোলন (;)', sep_tab: 'ট্যাব', sep_pipe: 'পাইপ (|)',
    ragged_note: '{n}টি সারিতে ঘরের সংখ্যা আলাদা ছিল। প্রতিটি সারি মেলাতে ফাঁকা ঘর যোগ করা হয়েছে।',
    noname_note: '{n}টি কলামের নাম ছিল না, তাই সেগুলোকে নম্বর দেওয়া হয়েছে।',
    type_number: 'সংখ্যা', type_text: 'লেখা', type_date: 'তারিখ', type_bool: 'হ্যাঁ / না', type_empty: 'ফাঁকা',
    st_count: 'মান', st_missing: 'ফাঁকা', st_unique: 'আলাদা মান', st_min: 'সবচেয়ে ছোট', st_max: 'সবচেয়ে বড়', st_mean: 'গড়', st_median: 'মধ্যমা', st_sd: 'মানক বিচ্যুতি', st_sum: 'যোগফল', st_earliest: 'সবচেয়ে আগের', st_latest: 'সবচেয়ে পরের', st_top: 'সবচেয়ে বেশি',
    invalid_dates: '{n}টি মান তারিখ নয় (বাদ দেওয়া হয়েছে)',
    invalid_nums: '{n}টি মান সংখ্যা নয় (বাদ দেওয়া হয়েছে)',
    shown_rows: '{n}টির মধ্যে {from}–{to} নম্বর সারি দেখানো হচ্ছে',
    filtered_of: '(ফাইলে {n}টি সারি)',
    shown_none: 'কোনো সারি মেলেনি। একটি ফিল্টার সরিয়ে দেখুন।',
    page_of: 'পাতা {p} / {n}',
    op_contains: 'এতে আছে', op_equals: 'ঠিক এটাই', op_between: 'এর মাঝে', op_missing: 'ফাঁকা', op_notmissing: 'ফাঁকা নয়',
    need_value: 'আগে একটি মান লিখুন।',
    remove_filter: 'ফিল্টার সরান',
    no_filters: 'কোনো ফিল্টার নেই। সব সারি দেখানো হচ্ছে।',
    clear_filters: 'সব ফিল্টার সরান',
    show_all: 'সব দেখান', hide_all: 'সব লুকান',
    exported_n: '{n}টি সারি ডাউনলোড হয়েছে',
    r_strong_pos: 'জোরালো ধনাত্মক', r_mod_pos: 'মাঝারি ধনাত্মক', r_weak_pos: 'দুর্বল ধনাত্মক', r_none: 'প্রায় কোনো সম্পর্ক নেই', r_weak_neg: 'দুর্বল ঋণাত্মক', r_mod_neg: 'মাঝারি ঋণাত্মক', r_strong_neg: 'জোরালো ঋণাত্মক',
    corr_read: '{a} আর {b}: {kind} (r = {r})।',
    corr_up: '{a} বেশি হলে {b}-ও সাধারণত বেশি হয়।',
    corr_down: '{a} বেশি হলে {b} সাধারণত কম হয়।',
    corr_flat: '{a} জেনে {b} সম্পর্কে প্রায় কিছুই বোঝা যায় না।',
    corr_need: 'তুলনার জন্য অন্তত 2টি সংখ্যার কলাম দরকার।',
    corr_limit: 'প্রথম {n}টি সংখ্যার কলাম দেখানো হচ্ছে।',
    corr_neg_label: '−1 উল্টো', corr_pos_label: '+1 একসঙ্গে',
    corr_pick: 'কোনো ঘরে ট্যাপ করে তার মানে কথায় পড়ুন।',
    corr_self: 'প্রতিটি কলাম নিজের সঙ্গে পুরো মেলে (r = 1)।',
    corr_warn: 'সম্পর্ক থাকলেই প্রমাণ হয় না যে একটি অন্যটির কারণ।',
    corr_na: 'এই দুটি কলাম তুলনার জন্য যথেষ্ট ভরা সারি নেই।',
    corr_strongest: 'সবচেয়ে জোরালো সম্পর্ক'
  },
  mr: {
    app_title: 'डेटा एक्सप्लोरर',
    intro: 'कोणतीही CSV फाइल उघडा आणि प्रत्येक कॉलम एका नजरेत पाहा: प्रकार, रिकाम्या जागा, सरासरी, मध्यक, सर्वाधिक येणारी मूल्ये, फिल्टर, क्रम आणि सहसंबंध.',
    privacy: 'तुमचा डेटा याच डिव्हाइसवर राहतो. काहीही अपलोड होत नाही.',
    howto: 'कसे वापरावे / कल्पना',
    tip_1: 'तुमची CSV फाइल उघडा, ती चौकटीत सोडा, Excel किंवा Google Sheets मधून ओळी पेस्ट करा, किंवा एखादा नमुना वापरून पाहा.',
    tip_2: 'कॉलम प्रोफाइलमध्ये प्रत्येक कॉलमचा सारांश दिसतो: किती मूल्ये, किती रिकामी, सर्वात लहान, सर्वात मोठे, सरासरी, मध्यक आणि सर्वाधिक येणारी मूल्ये.',
    tip_3: 'डेटा तक्त्यात क्रम लावण्यासाठी कॉलमच्या नावावर टॅप करा, सर्व कॉलममध्ये शोधा आणि फिल्टर लावा (यात आहे, दरम्यान, रिकामे). फक्त फिल्टर केलेल्या ओळी नवीन CSV म्हणून डाउनलोड करा.',
    tip_4: 'ऑफिससाठी: मागच्या महिन्याची विक्रीची फाइल उघडा, एक विभाग किंवा पेमेंटचा प्रकार निवडा, एकूण आणि सुटलेली बिले तपासा, मग अहवालासाठी त्या ओळी डाउनलोड करा.',
    tip_5: 'वर्गासाठी: वर्गाच्या गुणांचा नमुना उघडा. विद्यार्थी गणिताची सरासरी आणि मध्यक हाताने काढतील, मग ॲपशी जुळवतील. कोणाचे गुण बाकीच्यांपेक्षा खूप वेगळे आहेत? कोणते विषय सोबत वाढतात?',
    tip_6: 'Excel किंवा Google Sheets फाइल आहे? आधी ती CSV म्हणून सेव्ह करा (File → Save as / Download → CSV). 50,000 ओळींची मोठी फाइलही चालते; तक्ता एका पानावर 100 ओळी दाखवतो.',
    words_title: 'महत्त्वाचे शब्द',
    w_dataset: 'डेटासेट', w_dataset_d: 'डेटाचा एक तक्ता, जसे Excel मधील एक शीट. हे ॲप तो CSV फाइलमधून वाचते.',
    w_row: 'ओळ', w_row_d: 'तक्त्यातील एक नोंद: एक विद्यार्थी, एक बिल, एक राज्य.',
    w_column: 'कॉलम', w_column_d: 'प्रत्येक ओळीसाठी एकाच प्रकारची माहिती: नाव, गुण, तारीख. प्रत्येक कॉलमचा एक प्रकार असतो: संख्या, मजकूर, तारीख किंवा हो/नाही.',
    w_missing: 'रिकामे मूल्य', w_missing_d: 'रिकामा सेल, किंवा NA, N/A, "-" असे लिहिलेले. ते मोजले जाते, मग बेरीज आणि सरासरीतून वगळले जाते.',
    w_mean: 'सरासरी', w_mean_d: 'सर्व संख्यांची बेरीज करा आणि त्या किती आहेत त्याने भागा.',
    w_median: 'मध्यक', w_median_d: 'क्रमाने लावल्यावर मधली संख्या. एखादे खूप मोठे मूल्य तिला फारसे ओढू शकत नाही, म्हणून ती अनेकदा सरासरीपेक्षा योग्य चित्र देते.',
    w_sd: 'प्रमाण विचलन', w_sd_d: 'संख्या सरासरीभोवती किती पसरलेल्या आहेत. लहान: मूल्ये जवळजवळ आहेत. मोठे: मूल्ये दूर दूर आहेत. (हे ॲप नमुन्याचे सूत्र वापरते, n − 1 ने भागते.)',
    w_corr: 'सहसंबंध (r)', w_corr_d: '−1 ते +1 मधील एक संख्या, जी दाखवते की दोन संख्यांचे कॉलम सोबत वाढतात-कमी होतात का. यावरून एक दुसऱ्याचे कारण आहे हे सिद्ध होत नाही.',
    load_title: 'डेटा उघडा',
    drop_here: 'CSV फाइल इथे सोडा, किंवा',
    open_csv: 'CSV फाइल उघडा',
    paste_data: 'डेटा पेस्ट करा',
    excel_hint: 'Excel किंवा Sheets फाइल? File → Save as (किंवा Download) → CSV निवडा. तुमची फाइल याच डिव्हाइसवर राहते.',
    paste_label: 'Excel, Google Sheets किंवा CSV फाइलमधून ओळी पेस्ट करा',
    paste_ph: 'नाव,गुण\nआरव,78\nअनन्या,92',
    paste_use: 'हा डेटा वापरा',
    samples: 'किंवा एखादा नमुना वापरून पाहा:',
    sample_marks: 'वर्गाचे गुण', sample_shop: 'दुकानाची विक्री (सप्टेंबर)', sample_rain: 'राज्यनिहाय पावसाळी पाऊस',
    tabs_label: 'पाहण्याच्या पद्धती',
    tab_cols: 'कॉलम प्रोफाइल', tab_table: 'डेटा तक्ता', tab_corr: 'सहसंबंध',
    search_ph: 'सर्व कॉलममध्ये शोधा…',
    choose_cols: 'कॉलम निवडा',
    export_csv: 'या ओळी डाउनलोड करा (CSV)',
    filter_title: 'फिल्टर',
    f_col: 'कॉलम', f_op: 'नियम', f_value: 'मूल्य', f_from: 'पासून', f_to: 'पर्यंत',
    add_filter: 'फिल्टर जोडा',
    sort_hint: 'क्रम लावण्यासाठी कॉलमच्या नावावर टॅप करा (▲ लहान ते मोठे, ▼ मोठे ते लहान).',
    corr_title: 'संख्यांचे कॉलम सोबत कसे बदलतात?',
    corr_intro: 'सहसंबंध (r) −1 ते +1 असतो. +1 जवळ: एक वाढला की दुसराही बहुधा वाढतो. −1 जवळ: एक वाढला की दुसरा बहुधा कमी होतो. 0 जवळ: सरळ संबंध नाही.',
    col_n: 'कॉलम {n}',
    too_big_save: 'ही फाइल लक्षात ठेवण्यासाठी खूप मोठी आहे. आता चालेल, पण पुढच्या वेळी पुन्हा उघडावी लागेल.',
    empty_file: 'ही फाइल रिकामी आहे. दुसरी फाइल निवडा किंवा एखादा नमुना वापरून पाहा.',
    only_header: 'या फाइलमध्ये कॉलमची नावे आहेत, पण डेटाची एकही ओळ नाही.',
    excel_file: 'ही Excel फाइल दिसते. Excel मध्ये File → Save as → CSV निवडा, मग ती CSV इथे उघडा.',
    read_error: 'ही फाइल वाचता आली नाही. ही CSV टेक्स्ट फाइल आहे का?',
    pasted_data: 'पेस्ट केलेला डेटा',
    summary: '{rows} ओळी, {cols} कॉलम, {pct}% रिकामे',
    sep_used: 'वेगळे करणारे चिन्ह: {sep}',
    sep_comma: 'स्वल्पविराम (,)', sep_semicolon: 'अर्धविराम (;)', sep_tab: 'टॅब', sep_pipe: 'पाइप (|)',
    ragged_note: '{n} ओळींमध्ये सेलची संख्या वेगळी होती. प्रत्येक ओळ पूर्ण करण्यासाठी रिकामे सेल जोडले.',
    noname_note: '{n} कॉलमना नाव नव्हते, म्हणून त्यांना क्रमांक दिला.',
    type_number: 'संख्या', type_text: 'मजकूर', type_date: 'तारीख', type_bool: 'हो / नाही', type_empty: 'रिकामे',
    st_count: 'मूल्ये', st_missing: 'रिकामे', st_unique: 'वेगवेगळी मूल्ये', st_min: 'सर्वात लहान', st_max: 'सर्वात मोठे', st_mean: 'सरासरी', st_median: 'मध्यक', st_sd: 'प्रमाण विचलन', st_sum: 'बेरीज', st_earliest: 'सर्वात आधीची', st_latest: 'सर्वात नंतरची', st_top: 'सर्वाधिक',
    invalid_dates: '{n} मूल्ये तारीख नाहीत (वगळली)',
    invalid_nums: '{n} मूल्ये संख्या नाहीत (वगळली)',
    shown_rows: '{n} पैकी {from}–{to} ओळी दिसत आहेत',
    filtered_of: '(फाइलमध्ये {n} ओळी)',
    shown_none: 'एकही ओळ जुळत नाही. एखादा फिल्टर काढून पाहा.',
    page_of: 'पान {p} / {n}',
    op_contains: 'यात आहे', op_equals: 'नेमके हेच', op_between: 'दरम्यान आहे', op_missing: 'रिकामे आहे', op_notmissing: 'रिकामे नाही',
    need_value: 'आधी एक मूल्य लिहा.',
    remove_filter: 'फिल्टर काढा',
    no_filters: 'फिल्टर नाही. सर्व ओळी दिसत आहेत.',
    clear_filters: 'सर्व फिल्टर काढा',
    show_all: 'सर्व दाखवा', hide_all: 'सर्व लपवा',
    exported_n: '{n} ओळी डाउनलोड झाल्या',
    r_strong_pos: 'मजबूत धन', r_mod_pos: 'मध्यम धन', r_weak_pos: 'कमकुवत धन', r_none: 'जवळजवळ संबंध नाही', r_weak_neg: 'कमकुवत ऋण', r_mod_neg: 'मध्यम ऋण', r_strong_neg: 'मजबूत ऋण',
    corr_read: '{a} आणि {b}: {kind} (r = {r}).',
    corr_up: '{a} जास्त असेल तेव्हा {b} पण बहुधा जास्त असतो.',
    corr_down: '{a} जास्त असेल तेव्हा {b} बहुधा कमी असतो.',
    corr_flat: '{a} माहीत असून {b} बद्दल फारसे कळत नाही.',
    corr_need: 'तुलनेसाठी किमान 2 संख्यांचे कॉलम लागतात.',
    corr_limit: 'पहिले {n} संख्यांचे कॉलम दिसत आहेत.',
    corr_neg_label: '−1 उलट', corr_pos_label: '+1 सोबत',
    corr_pick: 'एखाद्या चौकोनावर टॅप करा आणि त्याचा अर्थ शब्दांत वाचा.',
    corr_self: 'प्रत्येक कॉलम स्वतःशी पूर्ण जुळतो (r = 1).',
    corr_warn: 'संबंध आहे म्हणून एक दुसऱ्याचे कारण आहे हे सिद्ध होत नाही.',
    corr_na: 'या दोन कॉलमची तुलना करण्यासाठी पुरेशा भरलेल्या ओळी नाहीत.',
    corr_strongest: 'सर्वात मजबूत संबंध'
  },
  gu: {
    app_title: 'ડેટા એક્સપ્લોરર',
    intro: 'કોઈ પણ CSV ફાઇલ ખોલો અને દરેક કૉલમ એક નજરે જુઓ: પ્રકાર, ખાલી જગ્યા, સરેરાશ, મધ્યસ્થ, સૌથી વધુ આવતાં મૂલ્યો, ફિલ્ટર, ક્રમ અને સહસંબંધ.',
    privacy: 'તમારો ડેટા આ જ ડિવાઇસ પર રહે છે. કંઈ પણ અપલોડ થતું નથી.',
    howto: 'કેવી રીતે વાપરવું / વિચારો',
    tip_1: 'તમારી CSV ફાઇલ ખોલો, બોક્સ પર મૂકો, Excel કે Google Sheets માંથી હરોળ પેસ્ટ કરો, અથવા કોઈ નમૂનો અજમાવો.',
    tip_2: 'કૉલમ પ્રોફાઇલમાં દરેક કૉલમનો સાર દેખાય છે: કેટલાં મૂલ્યો, કેટલાં ખાલી, સૌથી નાનું, સૌથી મોટું, સરેરાશ, મધ્યસ્થ અને સૌથી વધુ આવતાં મૂલ્યો.',
    tip_3: 'ડેટા કોષ્ટકમાં ક્રમ માટે કૉલમના નામ પર ટૅપ કરો, બધા કૉલમમાં શોધો અને ફિલ્ટર ઉમેરો (સમાવે છે, વચ્ચે, ખાલી). ફક્ત ફિલ્ટર કરેલી હરોળ નવી CSV તરીકે ડાઉનલોડ કરો.',
    tip_4: 'ઑફિસ માટે: ગયા મહિનાની વેચાણની ફાઇલ ખોલો, એક પ્રદેશ કે ચુકવણીનો પ્રકાર ફિલ્ટર કરો, કુલ અને છૂટેલાં બિલ તપાસો, પછી રિપોર્ટ માટે એ હરોળ ડાઉનલોડ કરો.',
    tip_5: 'વર્ગ માટે: વર્ગના ગુણનો નમૂનો ખોલો. વિદ્યાર્થીઓ ગણિતની સરેરાશ અને મધ્યસ્થ હાથથી કાઢે, પછી ઍપ સાથે મેળવે. કોના ગુણ બાકીનાથી ઘણા અલગ છે? કયા વિષયો સાથે વધે છે?',
    tip_6: 'Excel કે Google Sheets ફાઇલ છે? પહેલાં CSV તરીકે સેવ કરો (File → Save as / Download → CSV). 50,000 હરોળવાળી મોટી ફાઇલ પણ ચાલે છે; કોષ્ટક એક પાને 100 હરોળ બતાવે છે.',
    words_title: 'જાણવા જેવા શબ્દો',
    w_dataset: 'ડેટાસેટ', w_dataset_d: 'ડેટાનું એક કોષ્ટક, જેમ Excel ની એક શીટ. આ ઍપ તેને CSV ફાઇલમાંથી વાંચે છે.',
    w_row: 'હરોળ', w_row_d: 'કોષ્ટકની એક નોંધ: એક વિદ્યાર્થી, એક બિલ, એક રાજ્ય.',
    w_column: 'કૉલમ', w_column_d: 'દરેક હરોળ માટે એક જ પ્રકારની માહિતી: નામ, ગુણ, તારીખ. દરેક કૉલમનો એક પ્રકાર હોય છે: સંખ્યા, લખાણ, તારીખ કે હા/ના.',
    w_missing: 'ખાલી મૂલ્ય', w_missing_d: 'ખાલી સેલ, અથવા NA, N/A, "-" લખેલું. તે ગણાય છે, પછી સરવાળા અને સરેરાશમાંથી બહાર રખાય છે.',
    w_mean: 'સરેરાશ', w_mean_d: 'બધી સંખ્યાઓ ઉમેરો અને તે કેટલી છે તેનાથી ભાગો.',
    w_median: 'મધ્યસ્થ', w_median_d: 'ક્રમમાં ગોઠવ્યા પછી વચ્ચેની સંખ્યા. એક બહુ મોટું મૂલ્ય તેને વધુ ખેંચી શકતું નથી, તેથી તે ઘણી વાર સરેરાશ કરતાં સાચું ચિત્ર આપે છે.',
    w_sd: 'પ્રમાણિત વિચલન', w_sd_d: 'સંખ્યાઓ સરેરાશની આસપાસ કેટલી ફેલાયેલી છે. નાનું: મૂલ્યો નજીક નજીક. મોટું: મૂલ્યો દૂર દૂર. (આ ઍપ નમૂનાનું સૂત્ર વાપરે છે, n − 1 થી ભાગ.)',
    w_corr: 'સહસંબંધ (r)', w_corr_d: '−1 થી +1 સુધીની સંખ્યા, જે બતાવે છે કે બે સંખ્યાવાળા કૉલમ સાથે વધે-ઘટે છે કે નહીં. તેનાથી સાબિત નથી થતું કે એક બીજાનું કારણ છે.',
    load_title: 'ડેટા ખોલો',
    drop_here: 'CSV ફાઇલ અહીં મૂકો, અથવા',
    open_csv: 'CSV ફાઇલ ખોલો',
    paste_data: 'ડેટા પેસ્ટ કરો',
    excel_hint: 'Excel કે Sheets ફાઇલ? File → Save as (અથવા Download) → CSV પસંદ કરો. તમારી ફાઇલ આ જ ડિવાઇસ પર રહે છે.',
    paste_label: 'Excel, Google Sheets કે CSV ફાઇલમાંથી હરોળ પેસ્ટ કરો',
    paste_ph: 'નામ,ગુણ\nઆરવ,78\nઅનન્યા,92',
    paste_use: 'આ ડેટા વાપરો',
    samples: 'અથવા કોઈ નમૂનો અજમાવો:',
    sample_marks: 'વર્ગના ગુણ', sample_shop: 'દુકાનનું વેચાણ (સપ્ટેમ્બર)', sample_rain: 'રાજ્ય પ્રમાણે ચોમાસાનો વરસાદ',
    tabs_label: 'જોવાની રીતો',
    tab_cols: 'કૉલમ પ્રોફાઇલ', tab_table: 'ડેટા કોષ્ટક', tab_corr: 'સહસંબંધ',
    search_ph: 'બધા કૉલમમાં શોધો…',
    choose_cols: 'કૉલમ પસંદ કરો',
    export_csv: 'આ હરોળ ડાઉનલોડ કરો (CSV)',
    filter_title: 'ફિલ્ટર',
    f_col: 'કૉલમ', f_op: 'નિયમ', f_value: 'મૂલ્ય', f_from: 'થી', f_to: 'સુધી',
    add_filter: 'ફિલ્ટર ઉમેરો',
    sort_hint: 'ક્રમ બદલવા કૉલમના નામ પર ટૅપ કરો (▲ નાનાથી મોટું, ▼ મોટાથી નાનું).',
    corr_title: 'સંખ્યાવાળા કૉલમ સાથે કેવી રીતે બદલાય છે?',
    corr_intro: 'સહસંબંધ (r) −1 થી +1 સુધી હોય છે. +1 નજીક: એક વધે તો બીજું પણ મોટે ભાગે વધે. −1 નજીક: એક વધે તો બીજું મોટે ભાગે ઘટે. 0 નજીક: સીધો કોઈ સંબંધ નથી.',
    col_n: 'કૉલમ {n}',
    too_big_save: 'આ ફાઇલ યાદ રાખવા માટે બહુ મોટી છે. હમણાં ચાલશે, પણ આવતી વખતે ફરી ખોલવી પડશે.',
    empty_file: 'આ ફાઇલ ખાલી છે. બીજી ફાઇલ પસંદ કરો કે કોઈ નમૂનો અજમાવો.',
    only_header: 'આ ફાઇલમાં કૉલમનાં નામ છે, પણ ડેટાની એક પણ હરોળ નથી.',
    excel_file: 'આ Excel ફાઇલ લાગે છે. Excel માં File → Save as → CSV પસંદ કરો, પછી એ CSV અહીં ખોલો.',
    read_error: 'આ ફાઇલ વાંચી ન શકાઈ. શું આ CSV ટેક્સ્ટ ફાઇલ છે?',
    pasted_data: 'પેસ્ટ કરેલો ડેટા',
    summary: '{rows} હરોળ, {cols} કૉલમ, {pct}% ખાલી',
    sep_used: 'અલગ પાડતું ચિહ્ન: {sep}',
    sep_comma: 'અલ્પવિરામ (,)', sep_semicolon: 'અર્ધવિરામ (;)', sep_tab: 'ટૅબ', sep_pipe: 'પાઇપ (|)',
    ragged_note: '{n} હરોળમાં સેલની સંખ્યા જુદી હતી. દરેક હરોળ પૂરી કરવા ખાલી સેલ ઉમેર્યા.',
    noname_note: '{n} કૉલમને નામ નહોતું, એટલે તેમને નંબર આપ્યો.',
    type_number: 'સંખ્યા', type_text: 'લખાણ', type_date: 'તારીખ', type_bool: 'હા / ના', type_empty: 'ખાલી',
    st_count: 'મૂલ્યો', st_missing: 'ખાલી', st_unique: 'જુદાં મૂલ્યો', st_min: 'સૌથી નાનું', st_max: 'સૌથી મોટું', st_mean: 'સરેરાશ', st_median: 'મધ્યસ્થ', st_sd: 'પ્રમાણિત વિચલન', st_sum: 'સરવાળો', st_earliest: 'સૌથી પહેલી', st_latest: 'સૌથી છેલ્લી', st_top: 'સૌથી વધુ',
    invalid_dates: '{n} મૂલ્યો તારીખ નથી (બાકાત રાખ્યાં)',
    invalid_nums: '{n} મૂલ્યો સંખ્યા નથી (બાકાત રાખ્યાં)',
    shown_rows: '{n} માંથી {from}–{to} હરોળ દેખાય છે',
    filtered_of: '(ફાઇલમાં {n} હરોળ)',
    shown_none: 'કોઈ હરોળ મેળ ખાતી નથી. કોઈ ફિલ્ટર કાઢીને જુઓ.',
    page_of: 'પાનું {p} / {n}',
    op_contains: 'સમાવે છે', op_equals: 'બરાબર આ જ', op_between: 'વચ્ચે છે', op_missing: 'ખાલી છે', op_notmissing: 'ખાલી નથી',
    need_value: 'પહેલાં એક મૂલ્ય લખો.',
    remove_filter: 'ફિલ્ટર કાઢો',
    no_filters: 'કોઈ ફિલ્ટર નથી. બધી હરોળ દેખાય છે.',
    clear_filters: 'બધા ફિલ્ટર કાઢો',
    show_all: 'બધું બતાવો', hide_all: 'બધું છુપાવો',
    exported_n: '{n} હરોળ ડાઉનલોડ થઈ',
    r_strong_pos: 'મજબૂત ધન', r_mod_pos: 'મધ્યમ ધન', r_weak_pos: 'નબળો ધન', r_none: 'લગભગ કોઈ સંબંધ નહીં', r_weak_neg: 'નબળો ઋણ', r_mod_neg: 'મધ્યમ ઋણ', r_strong_neg: 'મજબૂત ઋણ',
    corr_read: '{a} અને {b}: {kind} (r = {r}).',
    corr_up: '{a} વધારે હોય ત્યારે {b} પણ મોટે ભાગે વધારે હોય છે.',
    corr_down: '{a} વધારે હોય ત્યારે {b} મોટે ભાગે ઓછું હોય છે.',
    corr_flat: '{a} જાણવાથી {b} વિશે ખાસ ખબર પડતી નથી.',
    corr_need: 'સરખામણી માટે ઓછામાં ઓછા 2 સંખ્યાવાળા કૉલમ જોઈએ.',
    corr_limit: 'પહેલા {n} સંખ્યાવાળા કૉલમ દેખાય છે.',
    corr_neg_label: '−1 ઊલટું', corr_pos_label: '+1 સાથે',
    corr_pick: 'કોઈ ખાના પર ટૅપ કરો અને તેનો અર્થ શબ્દોમાં વાંચો.',
    corr_self: 'દરેક કૉલમ પોતાની સાથે પૂરો મેળ ખાય છે (r = 1).',
    corr_warn: 'સંબંધ હોવાથી સાબિત નથી થતું કે એક બીજાનું કારણ છે.',
    corr_na: 'આ બે કૉલમની સરખામણી માટે પૂરતી ભરેલી હરોળ નથી.',
    corr_strongest: 'સૌથી મજબૂત સંબંધ'
  },
  pa: {
    app_title: 'ਡੇਟਾ ਐਕਸਪਲੋਰਰ',
    intro: 'ਕੋਈ ਵੀ CSV ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ ਅਤੇ ਹਰ ਕਾਲਮ ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ ਦੇਖੋ: ਕਿਸਮ, ਖਾਲੀ ਖਾਨੇ, ਔਸਤ, ਮੱਧਿਕਾ, ਸਭ ਤੋਂ ਆਮ ਮੁੱਲ, ਫ਼ਿਲਟਰ, ਤਰਤੀਬ ਅਤੇ ਸਹਿ-ਸੰਬੰਧ।',
    privacy: 'ਤੁਹਾਡਾ ਡੇਟਾ ਇਸੇ ਡਿਵਾਈਸ ਉੱਤੇ ਰਹਿੰਦਾ ਹੈ। ਕੁਝ ਵੀ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ।',
    howto: 'ਕਿਵੇਂ ਵਰਤੀਏ / ਸੁਝਾਅ',
    tip_1: 'ਆਪਣੀ CSV ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ, ਡੱਬੇ ਉੱਤੇ ਛੱਡੋ, Excel ਜਾਂ Google Sheets ਤੋਂ ਕਤਾਰਾਂ ਪੇਸਟ ਕਰੋ, ਜਾਂ ਕੋਈ ਨਮੂਨਾ ਅਜ਼ਮਾਓ।',
    tip_2: 'ਕਾਲਮ ਪ੍ਰੋਫ਼ਾਈਲ ਵਿੱਚ ਹਰ ਕਾਲਮ ਦਾ ਸਾਰ ਦਿਸਦਾ ਹੈ: ਕਿੰਨੇ ਮੁੱਲ, ਕਿੰਨੇ ਖਾਲੀ, ਸਭ ਤੋਂ ਛੋਟਾ, ਸਭ ਤੋਂ ਵੱਡਾ, ਔਸਤ, ਮੱਧਿਕਾ ਅਤੇ ਸਭ ਤੋਂ ਆਮ ਮੁੱਲ।',
    tip_3: 'ਡੇਟਾ ਸਾਰਣੀ ਵਿੱਚ ਤਰਤੀਬ ਲਈ ਕਾਲਮ ਦੇ ਨਾਮ ਉੱਤੇ ਟੈਪ ਕਰੋ, ਸਾਰੇ ਕਾਲਮਾਂ ਵਿੱਚ ਲੱਭੋ ਅਤੇ ਫ਼ਿਲਟਰ ਲਗਾਓ (ਸ਼ਾਮਲ ਹੈ, ਵਿਚਕਾਰ, ਖਾਲੀ)। ਸਿਰਫ਼ ਫ਼ਿਲਟਰ ਕੀਤੀਆਂ ਕਤਾਰਾਂ ਨਵੀਂ CSV ਵਜੋਂ ਡਾਊਨਲੋਡ ਕਰੋ।',
    tip_4: 'ਦਫ਼ਤਰ ਲਈ: ਪਿਛਲੇ ਮਹੀਨੇ ਦੀ ਵਿਕਰੀ ਦੀ ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ, ਇੱਕ ਖੇਤਰ ਜਾਂ ਭੁਗਤਾਨ ਦਾ ਤਰੀਕਾ ਫ਼ਿਲਟਰ ਕਰੋ, ਕੁੱਲ ਅਤੇ ਛੁੱਟੇ ਬਿੱਲ ਜਾਂਚੋ, ਫਿਰ ਰਿਪੋਰਟ ਲਈ ਉਹ ਕਤਾਰਾਂ ਡਾਊਨਲੋਡ ਕਰੋ।',
    tip_5: 'ਜਮਾਤ ਲਈ: ਜਮਾਤ ਦੇ ਅੰਕਾਂ ਵਾਲਾ ਨਮੂਨਾ ਖੋਲ੍ਹੋ। ਵਿਦਿਆਰਥੀ ਗਣਿਤ ਦੀ ਔਸਤ ਅਤੇ ਮੱਧਿਕਾ ਹੱਥ ਨਾਲ ਕੱਢਣ, ਫਿਰ ਐਪ ਨਾਲ ਮਿਲਾਉਣ। ਕਿਸ ਦੇ ਅੰਕ ਬਾਕੀਆਂ ਤੋਂ ਬਹੁਤ ਵੱਖਰੇ ਹਨ? ਕਿਹੜੇ ਵਿਸ਼ੇ ਨਾਲ-ਨਾਲ ਵਧਦੇ ਹਨ?',
    tip_6: 'Excel ਜਾਂ Google Sheets ਫ਼ਾਈਲ ਹੈ? ਪਹਿਲਾਂ CSV ਵਜੋਂ ਸੇਵ ਕਰੋ (File → Save as / Download → CSV)। 50,000 ਕਤਾਰਾਂ ਵਾਲੀ ਵੱਡੀ ਫ਼ਾਈਲ ਵੀ ਚੱਲਦੀ ਹੈ; ਸਾਰਣੀ ਇੱਕ ਸਫ਼ੇ ਉੱਤੇ 100 ਕਤਾਰਾਂ ਦਿਖਾਉਂਦੀ ਹੈ।',
    words_title: 'ਜ਼ਰੂਰੀ ਸ਼ਬਦ',
    w_dataset: 'ਡੇਟਾਸੈੱਟ', w_dataset_d: 'ਡੇਟਾ ਦੀ ਇੱਕ ਸਾਰਣੀ, ਜਿਵੇਂ Excel ਦੀ ਇੱਕ ਸ਼ੀਟ। ਇਹ ਐਪ ਇਸ ਨੂੰ CSV ਫ਼ਾਈਲ ਤੋਂ ਪੜ੍ਹਦੀ ਹੈ।',
    w_row: 'ਕਤਾਰ', w_row_d: 'ਸਾਰਣੀ ਦਾ ਇੱਕ ਰਿਕਾਰਡ: ਇੱਕ ਵਿਦਿਆਰਥੀ, ਇੱਕ ਬਿੱਲ, ਇੱਕ ਰਾਜ।',
    w_column: 'ਕਾਲਮ', w_column_d: 'ਹਰ ਕਤਾਰ ਲਈ ਇੱਕੋ ਕਿਸਮ ਦੀ ਜਾਣਕਾਰੀ: ਨਾਮ, ਅੰਕ, ਤਾਰੀਖ। ਹਰ ਕਾਲਮ ਦੀ ਇੱਕ ਕਿਸਮ ਹੁੰਦੀ ਹੈ: ਅੰਕ, ਲਿਖਤ, ਤਾਰੀਖ ਜਾਂ ਹਾਂ/ਨਹੀਂ।',
    w_missing: 'ਖਾਲੀ ਮੁੱਲ', w_missing_d: 'ਖਾਲੀ ਖਾਨਾ, ਜਾਂ NA, N/A, "-" ਲਿਖਿਆ ਹੋਵੇ। ਇਸ ਨੂੰ ਗਿਣਿਆ ਜਾਂਦਾ ਹੈ, ਫਿਰ ਜੋੜ ਅਤੇ ਔਸਤ ਵਿੱਚੋਂ ਬਾਹਰ ਰੱਖਿਆ ਜਾਂਦਾ ਹੈ।',
    w_mean: 'ਔਸਤ', w_mean_d: 'ਸਾਰੇ ਅੰਕ ਜੋੜੋ ਅਤੇ ਉਹ ਜਿੰਨੇ ਹਨ ਉਸ ਨਾਲ ਭਾਗ ਕਰੋ।',
    w_median: 'ਮੱਧਿਕਾ', w_median_d: 'ਤਰਤੀਬ ਵਿੱਚ ਲਾਉਣ ਤੋਂ ਬਾਅਦ ਵਿਚਕਾਰਲਾ ਅੰਕ। ਇੱਕ ਬਹੁਤ ਵੱਡਾ ਮੁੱਲ ਇਸ ਨੂੰ ਜ਼ਿਆਦਾ ਨਹੀਂ ਖਿੱਚ ਸਕਦਾ, ਇਸ ਲਈ ਇਹ ਅਕਸਰ ਔਸਤ ਨਾਲੋਂ ਸਹੀ ਤਸਵੀਰ ਦਿੰਦੀ ਹੈ।',
    w_sd: 'ਮਿਆਰੀ ਵਿਚਲਨ', w_sd_d: 'ਅੰਕ ਔਸਤ ਦੇ ਆਲੇ-ਦੁਆਲੇ ਕਿੰਨੇ ਫੈਲੇ ਹਨ। ਛੋਟਾ: ਮੁੱਲ ਨੇੜੇ-ਨੇੜੇ। ਵੱਡਾ: ਮੁੱਲ ਦੂਰ-ਦੂਰ। (ਇਹ ਐਪ ਨਮੂਨੇ ਵਾਲਾ ਸੂਤਰ ਵਰਤਦੀ ਹੈ, n − 1 ਨਾਲ ਭਾਗ।)',
    w_corr: 'ਸਹਿ-ਸੰਬੰਧ (r)', w_corr_d: '−1 ਤੋਂ +1 ਤੱਕ ਦਾ ਅੰਕ, ਜੋ ਦੱਸਦਾ ਹੈ ਕਿ ਦੋ ਅੰਕਾਂ ਵਾਲੇ ਕਾਲਮ ਨਾਲ-ਨਾਲ ਵਧਦੇ-ਘਟਦੇ ਹਨ ਜਾਂ ਨਹੀਂ। ਇਸ ਨਾਲ ਇਹ ਸਾਬਤ ਨਹੀਂ ਹੁੰਦਾ ਕਿ ਇੱਕ ਦੂਜੇ ਦਾ ਕਾਰਨ ਹੈ।',
    load_title: 'ਡੇਟਾ ਖੋਲ੍ਹੋ',
    drop_here: 'CSV ਫ਼ਾਈਲ ਇੱਥੇ ਛੱਡੋ, ਜਾਂ',
    open_csv: 'CSV ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ',
    paste_data: 'ਡੇਟਾ ਪੇਸਟ ਕਰੋ',
    excel_hint: 'Excel ਜਾਂ Sheets ਫ਼ਾਈਲ? File → Save as (ਜਾਂ Download) → CSV ਚੁਣੋ। ਤੁਹਾਡੀ ਫ਼ਾਈਲ ਇਸੇ ਡਿਵਾਈਸ ਉੱਤੇ ਰਹਿੰਦੀ ਹੈ।',
    paste_label: 'Excel, Google Sheets ਜਾਂ CSV ਫ਼ਾਈਲ ਤੋਂ ਕਤਾਰਾਂ ਪੇਸਟ ਕਰੋ',
    paste_ph: 'ਨਾਮ,ਅੰਕ\nਆਰਵ,78\nਅਨੰਨਿਆ,92',
    paste_use: 'ਇਹ ਡੇਟਾ ਵਰਤੋ',
    samples: 'ਜਾਂ ਕੋਈ ਨਮੂਨਾ ਅਜ਼ਮਾਓ:',
    sample_marks: 'ਜਮਾਤ ਦੇ ਅੰਕ', sample_shop: 'ਦੁਕਾਨ ਦੀ ਵਿਕਰੀ (ਸਤੰਬਰ)', sample_rain: 'ਰਾਜਾਂ ਵਿੱਚ ਮਾਨਸੂਨ ਦਾ ਮੀਂਹ',
    tabs_label: 'ਦੇਖਣ ਦੇ ਤਰੀਕੇ',
    tab_cols: 'ਕਾਲਮ ਪ੍ਰੋਫ਼ਾਈਲ', tab_table: 'ਡੇਟਾ ਸਾਰਣੀ', tab_corr: 'ਸਹਿ-ਸੰਬੰਧ',
    search_ph: 'ਸਾਰੇ ਕਾਲਮਾਂ ਵਿੱਚ ਲੱਭੋ…',
    choose_cols: 'ਕਾਲਮ ਚੁਣੋ',
    export_csv: 'ਇਹ ਕਤਾਰਾਂ ਡਾਊਨਲੋਡ ਕਰੋ (CSV)',
    filter_title: 'ਫ਼ਿਲਟਰ',
    f_col: 'ਕਾਲਮ', f_op: 'ਨਿਯਮ', f_value: 'ਮੁੱਲ', f_from: 'ਤੋਂ', f_to: 'ਤੱਕ',
    add_filter: 'ਫ਼ਿਲਟਰ ਜੋੜੋ',
    sort_hint: 'ਤਰਤੀਬ ਲਈ ਕਾਲਮ ਦੇ ਨਾਮ ਉੱਤੇ ਟੈਪ ਕਰੋ (▲ ਛੋਟੇ ਤੋਂ ਵੱਡਾ, ▼ ਵੱਡੇ ਤੋਂ ਛੋਟਾ)।',
    corr_title: 'ਅੰਕਾਂ ਵਾਲੇ ਕਾਲਮ ਨਾਲ-ਨਾਲ ਕਿਵੇਂ ਚੱਲਦੇ ਹਨ?',
    corr_intro: 'ਸਹਿ-ਸੰਬੰਧ (r) −1 ਤੋਂ +1 ਤੱਕ ਹੁੰਦਾ ਹੈ। +1 ਦੇ ਨੇੜੇ: ਇੱਕ ਵਧੇ ਤਾਂ ਦੂਜਾ ਵੀ ਅਕਸਰ ਵਧਦਾ ਹੈ। −1 ਦੇ ਨੇੜੇ: ਇੱਕ ਵਧੇ ਤਾਂ ਦੂਜਾ ਅਕਸਰ ਘਟਦਾ ਹੈ। 0 ਦੇ ਨੇੜੇ: ਕੋਈ ਸਿੱਧਾ ਸੰਬੰਧ ਨਹੀਂ।',
    col_n: 'ਕਾਲਮ {n}',
    too_big_save: 'ਇਹ ਫ਼ਾਈਲ ਯਾਦ ਰੱਖਣ ਲਈ ਬਹੁਤ ਵੱਡੀ ਹੈ। ਹੁਣ ਚੱਲੇਗੀ, ਪਰ ਅਗਲੀ ਵਾਰ ਫਿਰ ਖੋਲ੍ਹਣੀ ਪਵੇਗੀ।',
    empty_file: 'ਇਹ ਫ਼ਾਈਲ ਖਾਲੀ ਹੈ। ਹੋਰ ਫ਼ਾਈਲ ਚੁਣੋ ਜਾਂ ਕੋਈ ਨਮੂਨਾ ਅਜ਼ਮਾਓ।',
    only_header: 'ਇਸ ਫ਼ਾਈਲ ਵਿੱਚ ਕਾਲਮਾਂ ਦੇ ਨਾਮ ਹਨ, ਪਰ ਡੇਟਾ ਦੀ ਕੋਈ ਕਤਾਰ ਨਹੀਂ।',
    excel_file: 'ਇਹ Excel ਫ਼ਾਈਲ ਲੱਗਦੀ ਹੈ। Excel ਵਿੱਚ File → Save as → CSV ਚੁਣੋ, ਫਿਰ ਉਹ CSV ਇੱਥੇ ਖੋਲ੍ਹੋ।',
    read_error: 'ਇਹ ਫ਼ਾਈਲ ਪੜ੍ਹੀ ਨਹੀਂ ਜਾ ਸਕੀ। ਕੀ ਇਹ CSV ਟੈਕਸਟ ਫ਼ਾਈਲ ਹੈ?',
    pasted_data: 'ਪੇਸਟ ਕੀਤਾ ਡੇਟਾ',
    summary: '{rows} ਕਤਾਰਾਂ, {cols} ਕਾਲਮ, {pct}% ਖਾਲੀ',
    sep_used: 'ਵੱਖ ਕਰਨ ਵਾਲਾ ਚਿੰਨ੍ਹ: {sep}',
    sep_comma: 'ਕੌਮਾ (,)', sep_semicolon: 'ਸੈਮੀਕੋਲਨ (;)', sep_tab: 'ਟੈਬ', sep_pipe: 'ਪਾਈਪ (|)',
    ragged_note: '{n} ਕਤਾਰਾਂ ਵਿੱਚ ਖਾਨਿਆਂ ਦੀ ਗਿਣਤੀ ਵੱਖਰੀ ਸੀ। ਹਰ ਕਤਾਰ ਪੂਰੀ ਕਰਨ ਲਈ ਖਾਲੀ ਖਾਨੇ ਜੋੜੇ ਗਏ।',
    noname_note: '{n} ਕਾਲਮਾਂ ਦਾ ਨਾਮ ਨਹੀਂ ਸੀ, ਇਸ ਲਈ ਉਨ੍ਹਾਂ ਨੂੰ ਨੰਬਰ ਦਿੱਤਾ ਗਿਆ।',
    type_number: 'ਅੰਕ', type_text: 'ਲਿਖਤ', type_date: 'ਤਾਰੀਖ', type_bool: 'ਹਾਂ / ਨਹੀਂ', type_empty: 'ਖਾਲੀ',
    st_count: 'ਮੁੱਲ', st_missing: 'ਖਾਲੀ', st_unique: 'ਵੱਖਰੇ ਮੁੱਲ', st_min: 'ਸਭ ਤੋਂ ਛੋਟਾ', st_max: 'ਸਭ ਤੋਂ ਵੱਡਾ', st_mean: 'ਔਸਤ', st_median: 'ਮੱਧਿਕਾ', st_sd: 'ਮਿਆਰੀ ਵਿਚਲਨ', st_sum: 'ਜੋੜ', st_earliest: 'ਸਭ ਤੋਂ ਪਹਿਲੀ', st_latest: 'ਸਭ ਤੋਂ ਬਾਅਦ ਦੀ', st_top: 'ਸਭ ਤੋਂ ਆਮ',
    invalid_dates: '{n} ਮੁੱਲ ਤਾਰੀਖ ਨਹੀਂ ਹਨ (ਛੱਡ ਦਿੱਤੇ)',
    invalid_nums: '{n} ਮੁੱਲ ਅੰਕ ਨਹੀਂ ਹਨ (ਛੱਡ ਦਿੱਤੇ)',
    shown_rows: '{n} ਵਿੱਚੋਂ {from}–{to} ਕਤਾਰਾਂ ਦਿਸ ਰਹੀਆਂ ਹਨ',
    filtered_of: '(ਫ਼ਾਈਲ ਵਿੱਚ {n} ਕਤਾਰਾਂ)',
    shown_none: 'ਕੋਈ ਕਤਾਰ ਮੇਲ ਨਹੀਂ ਖਾਂਦੀ। ਕੋਈ ਫ਼ਿਲਟਰ ਹਟਾ ਕੇ ਦੇਖੋ।',
    page_of: 'ਸਫ਼ਾ {p} / {n}',
    op_contains: 'ਵਿੱਚ ਸ਼ਾਮਲ ਹੈ', op_equals: 'ਬਿਲਕੁਲ ਇਹੀ', op_between: 'ਵਿਚਕਾਰ ਹੈ', op_missing: 'ਖਾਲੀ ਹੈ', op_notmissing: 'ਖਾਲੀ ਨਹੀਂ',
    need_value: 'ਪਹਿਲਾਂ ਇੱਕ ਮੁੱਲ ਲਿਖੋ।',
    remove_filter: 'ਫ਼ਿਲਟਰ ਹਟਾਓ',
    no_filters: 'ਕੋਈ ਫ਼ਿਲਟਰ ਨਹੀਂ। ਸਾਰੀਆਂ ਕਤਾਰਾਂ ਦਿਸ ਰਹੀਆਂ ਹਨ।',
    clear_filters: 'ਸਾਰੇ ਫ਼ਿਲਟਰ ਹਟਾਓ',
    show_all: 'ਸਭ ਦਿਖਾਓ', hide_all: 'ਸਭ ਲੁਕਾਓ',
    exported_n: '{n} ਕਤਾਰਾਂ ਡਾਊਨਲੋਡ ਹੋਈਆਂ',
    r_strong_pos: 'ਮਜ਼ਬੂਤ ਧਨਾਤਮਕ', r_mod_pos: 'ਦਰਮਿਆਨਾ ਧਨਾਤਮਕ', r_weak_pos: 'ਕਮਜ਼ੋਰ ਧਨਾਤਮਕ', r_none: 'ਲਗਭਗ ਕੋਈ ਸੰਬੰਧ ਨਹੀਂ', r_weak_neg: 'ਕਮਜ਼ੋਰ ਰਿਣਾਤਮਕ', r_mod_neg: 'ਦਰਮਿਆਨਾ ਰਿਣਾਤਮਕ', r_strong_neg: 'ਮਜ਼ਬੂਤ ਰਿਣਾਤਮਕ',
    corr_read: '{a} ਅਤੇ {b}: {kind} (r = {r})।',
    corr_up: 'ਜਦੋਂ {a} ਵੱਧ ਹੁੰਦਾ ਹੈ, ਤਾਂ {b} ਵੀ ਅਕਸਰ ਵੱਧ ਹੁੰਦਾ ਹੈ।',
    corr_down: 'ਜਦੋਂ {a} ਵੱਧ ਹੁੰਦਾ ਹੈ, ਤਾਂ {b} ਅਕਸਰ ਘੱਟ ਹੁੰਦਾ ਹੈ।',
    corr_flat: '{a} ਜਾਣ ਕੇ {b} ਬਾਰੇ ਬਹੁਤਾ ਪਤਾ ਨਹੀਂ ਲੱਗਦਾ।',
    corr_need: 'ਤੁਲਨਾ ਲਈ ਘੱਟੋ-ਘੱਟ 2 ਅੰਕਾਂ ਵਾਲੇ ਕਾਲਮ ਚਾਹੀਦੇ ਹਨ।',
    corr_limit: 'ਪਹਿਲੇ {n} ਅੰਕਾਂ ਵਾਲੇ ਕਾਲਮ ਦਿਸ ਰਹੇ ਹਨ।',
    corr_neg_label: '−1 ਉਲਟ', corr_pos_label: '+1 ਨਾਲ-ਨਾਲ',
    corr_pick: 'ਕਿਸੇ ਖਾਨੇ ਉੱਤੇ ਟੈਪ ਕਰੋ ਅਤੇ ਉਸ ਦਾ ਮਤਲਬ ਸ਼ਬਦਾਂ ਵਿੱਚ ਪੜ੍ਹੋ।',
    corr_self: 'ਹਰ ਕਾਲਮ ਆਪਣੇ ਆਪ ਨਾਲ ਪੂਰਾ ਮੇਲ ਖਾਂਦਾ ਹੈ (r = 1)।',
    corr_warn: 'ਸੰਬੰਧ ਹੋਣ ਨਾਲ ਇਹ ਸਾਬਤ ਨਹੀਂ ਹੁੰਦਾ ਕਿ ਇੱਕ ਦੂਜੇ ਦਾ ਕਾਰਨ ਹੈ।',
    corr_na: 'ਇਨ੍ਹਾਂ ਦੋ ਕਾਲਮਾਂ ਦੀ ਤੁਲਨਾ ਲਈ ਕਾਫ਼ੀ ਭਰੀਆਂ ਕਤਾਰਾਂ ਨਹੀਂ ਹਨ।',
    corr_strongest: 'ਸਭ ਤੋਂ ਮਜ਼ਬੂਤ ਸੰਬੰਧ'
  },
  or: {
    app_title: 'ଡାଟା ଏକ୍ସପ୍ଲୋରର',
    intro: 'ଯେକୌଣସି CSV ଫାଇଲ ଖୋଲନ୍ତୁ ଓ ପ୍ରତ୍ୟେକ ସ୍ତମ୍ଭ ଏକ ନଜରରେ ଦେଖନ୍ତୁ: ପ୍ରକାର, ଖାଲି ଘର, ହାରାହାରି, ମଧ୍ୟମା, ସବୁଠୁ ଅଧିକ ଆସୁଥିବା ମୂଲ୍ୟ, ଫିଲ୍ଟର, କ୍ରମ ଓ ସହସମ୍ପର୍କ।',
    privacy: 'ଆପଣଙ୍କ ଡାଟା ଏହି ଡିଭାଇସରେ ହିଁ ରହେ। କିଛି ବି ଅପଲୋଡ ହୁଏ ନାହିଁ।',
    howto: 'କିପରି ବ୍ୟବହାର କରିବେ / ଧାରଣା',
    tip_1: 'ନିଜ CSV ଫାଇଲ ଖୋଲନ୍ତୁ, ବାକ୍ସ ଉପରେ ଛାଡ଼ନ୍ତୁ, Excel କିମ୍ବା Google Sheets ରୁ ଧାଡ଼ି ପେଷ୍ଟ କରନ୍ତୁ, କିମ୍ବା ଏକ ନମୁନା ଚେଷ୍ଟା କରନ୍ତୁ।',
    tip_2: 'ସ୍ତମ୍ଭ ପ୍ରୋଫାଇଲରେ ପ୍ରତ୍ୟେକ ସ୍ତମ୍ଭର ସାରାଂଶ ଦେଖାଯାଏ: କେତେ ମୂଲ୍ୟ, କେତେ ଖାଲି, ସବୁଠୁ ଛୋଟ, ସବୁଠୁ ବଡ଼, ହାରାହାରି, ମଧ୍ୟମା ଓ ସବୁଠୁ ଅଧିକ ଆସୁଥିବା ମୂଲ୍ୟ।',
    tip_3: 'ଡାଟା ସାରଣୀରେ କ୍ରମ ପାଇଁ ସ୍ତମ୍ଭ ନାମରେ ଟ୍ୟାପ୍ କରନ୍ତୁ, ସବୁ ସ୍ତମ୍ଭରେ ଖୋଜନ୍ତୁ ଓ ଫିଲ୍ଟର ଦିଅନ୍ତୁ (ଅଛି, ମଧ୍ୟରେ, ଖାଲି)। କେବଳ ଫିଲ୍ଟର ହୋଇଥିବା ଧାଡ଼ି ନୂଆ CSV ଭାବେ ଡାଉନଲୋଡ କରନ୍ତୁ।',
    tip_4: 'ଅଫିସ ପାଇଁ: ଗତ ମାସର ବିକ୍ରି ଫାଇଲ ଖୋଲନ୍ତୁ, ଗୋଟିଏ ଅଞ୍ଚଳ କିମ୍ବା ପେମେଣ୍ଟ ପ୍ରକାର ଫିଲ୍ଟର କରନ୍ତୁ, ମୋଟ ଓ ବାଦ ପଡ଼ିଥିବା ବିଲ ଯାଞ୍ଚ କରନ୍ତୁ, ତା’ପରେ ରିପୋର୍ଟ ପାଇଁ ସେହି ଧାଡ଼ି ଡାଉନଲୋଡ କରନ୍ତୁ।',
    tip_5: 'ଶ୍ରେଣୀ ପାଇଁ: ଶ୍ରେଣୀର ନମ୍ବର ନମୁନା ଖୋଲନ୍ତୁ। ଛାତ୍ରଛାତ୍ରୀ ଗଣିତର ହାରାହାରି ଓ ମଧ୍ୟମା ହାତରେ ବାହାର କରନ୍ତୁ, ତା’ପରେ ଆପ୍ ସହ ମିଳାନ୍ତୁ। କାହାର ନମ୍ବର ବାକିଙ୍କଠାରୁ ବହୁତ ଅଲଗା? କେଉଁ ବିଷୟ ଏକାସାଙ୍ଗରେ ବଢ଼େ?',
    tip_6: 'Excel କିମ୍ବା Google Sheets ଫାଇଲ? ପ୍ରଥମେ CSV ଭାବେ ସେଭ କରନ୍ତୁ (File → Save as / Download → CSV)। 50,000 ଧାଡ଼ିର ବଡ଼ ଫାଇଲ ବି ଚାଲେ; ସାରଣୀ ପ୍ରତି ପୃଷ୍ଠାରେ 100 ଧାଡ଼ି ଦେଖାଏ।',
    words_title: 'ଜାଣିବା ଦରକାରୀ ଶବ୍ଦ',
    w_dataset: 'ଡାଟାସେଟ୍', w_dataset_d: 'ଡାଟାର ଏକ ସାରଣୀ, ଯେମିତି Excel ର ଗୋଟିଏ ସିଟ୍। ଏହି ଆପ୍ ଏହାକୁ CSV ଫାଇଲରୁ ପଢ଼େ।',
    w_row: 'ଧାଡ଼ି', w_row_d: 'ସାରଣୀର ଗୋଟିଏ ରେକର୍ଡ: ଜଣେ ଛାତ୍ର, ଗୋଟିଏ ବିଲ, ଗୋଟିଏ ରାଜ୍ୟ।',
    w_column: 'ସ୍ତମ୍ଭ', w_column_d: 'ପ୍ରତ୍ୟେକ ଧାଡ଼ି ପାଇଁ ଏକା ପ୍ରକାର ତଥ୍ୟ: ନାମ, ନମ୍ବର, ତାରିଖ। ପ୍ରତ୍ୟେକ ସ୍ତମ୍ଭର ଏକ ପ୍ରକାର ଥାଏ: ସଂଖ୍ୟା, ଲେଖା, ତାରିଖ କିମ୍ବା ହଁ/ନା।',
    w_missing: 'ଖାଲି ମୂଲ୍ୟ', w_missing_d: 'ଖାଲି ଘର, କିମ୍ବା NA, N/A, "-" ଲେଖାଥିବା। ଏହାକୁ ଗଣାଯାଏ, ତା’ପରେ ଯୋଗଫଳ ଓ ହାରାହାରିରୁ ବାଦ ଦିଆଯାଏ।',
    w_mean: 'ହାରାହାରି', w_mean_d: 'ସବୁ ସଂଖ୍ୟା ଯୋଗ କରି ସେଗୁଡ଼ିକ କେତୋଟି ଅଛି ତାହା ଦ୍ୱାରା ଭାଗ କରନ୍ତୁ।',
    w_median: 'ମଧ୍ୟମା', w_median_d: 'କ୍ରମରେ ସଜାଇବା ପରେ ମଝି ସଂଖ୍ୟା। ଗୋଟିଏ ବହୁତ ବଡ଼ ମୂଲ୍ୟ ଏହାକୁ ବେଶି ଟାଣି ପାରେ ନାହିଁ, ତେଣୁ ଏହା ଅନେକ ସମୟରେ ହାରାହାରିଠାରୁ ଠିକ୍ ଚିତ୍ର ଦିଏ।',
    w_sd: 'ମାନକ ବିଚ୍ୟୁତି', w_sd_d: 'ସଂଖ୍ୟାଗୁଡ଼ିକ ହାରାହାରି ଚାରିପାଖେ କେତେ ବିସ୍ତାରିତ। ଛୋଟ: ମୂଲ୍ୟ ପାଖାପାଖି। ବଡ଼: ମୂଲ୍ୟ ଦୂରଦୂର। (ଏହି ଆପ୍ ନମୁନା ସୂତ୍ର ବ୍ୟବହାର କରେ, n − 1 ଦ୍ୱାରା ଭାଗ।)',
    w_corr: 'ସହସମ୍ପର୍କ (r)', w_corr_d: '−1 ରୁ +1 ପର୍ଯ୍ୟନ୍ତ ଏକ ସଂଖ୍ୟା, ଯାହା ଦେଖାଏ ଦୁଇଟି ସଂଖ୍ୟା ସ୍ତମ୍ଭ ଏକାସାଙ୍ଗରେ ବଢ଼େ-କମେ କି ନାହିଁ। ଏହା ପ୍ରମାଣ କରେ ନାହିଁ ଯେ ଗୋଟିଏ ଅନ୍ୟଟିର କାରଣ।',
    load_title: 'ଡାଟା ଖୋଲନ୍ତୁ',
    drop_here: 'CSV ଫାଇଲ ଏଠାରେ ଛାଡ଼ନ୍ତୁ, କିମ୍ବା',
    open_csv: 'CSV ଫାଇଲ ଖୋଲନ୍ତୁ',
    paste_data: 'ଡାଟା ପେଷ୍ଟ କରନ୍ତୁ',
    excel_hint: 'Excel କିମ୍ବା Sheets ଫାଇଲ? File → Save as (କିମ୍ବା Download) → CSV ବାଛନ୍ତୁ। ଆପଣଙ୍କ ଫାଇଲ ଏହି ଡିଭାଇସରେ ହିଁ ରହେ।',
    paste_label: 'Excel, Google Sheets କିମ୍ବା CSV ଫାଇଲରୁ ଧାଡ଼ି ପେଷ୍ଟ କରନ୍ତୁ',
    paste_ph: 'ନାମ,ନମ୍ବର\nଆରଭ,78\nଅନନ୍ୟା,92',
    paste_use: 'ଏହି ଡାଟା ବ୍ୟବହାର କରନ୍ତୁ',
    samples: 'କିମ୍ବା ଏକ ନମୁନା ଦେଖନ୍ତୁ:',
    sample_marks: 'ଶ୍ରେଣୀର ନମ୍ବର', sample_shop: 'ଦୋକାନ ବିକ୍ରି (ସେପ୍ଟେମ୍ବର)', sample_rain: 'ରାଜ୍ୟ ଅନୁସାରେ ମୌସୁମୀ ବର୍ଷା',
    tabs_label: 'ଦେଖିବା ଢଙ୍ଗ',
    tab_cols: 'ସ୍ତମ୍ଭ ପ୍ରୋଫାଇଲ', tab_table: 'ଡାଟା ସାରଣୀ', tab_corr: 'ସହସମ୍ପର୍କ',
    search_ph: 'ସବୁ ସ୍ତମ୍ଭରେ ଖୋଜନ୍ତୁ…',
    choose_cols: 'ସ୍ତମ୍ଭ ବାଛନ୍ତୁ',
    export_csv: 'ଏହି ଧାଡ଼ି ଡାଉନଲୋଡ କରନ୍ତୁ (CSV)',
    filter_title: 'ଫିଲ୍ଟର',
    f_col: 'ସ୍ତମ୍ଭ', f_op: 'ନିୟମ', f_value: 'ମୂଲ୍ୟ', f_from: 'ରୁ', f_to: 'ପର୍ଯ୍ୟନ୍ତ',
    add_filter: 'ଫିଲ୍ଟର ଯୋଡ଼ନ୍ତୁ',
    sort_hint: 'କ୍ରମ ପାଇଁ ସ୍ତମ୍ଭ ନାମରେ ଟ୍ୟାପ୍ କରନ୍ତୁ (▲ ଛୋଟରୁ ବଡ଼, ▼ ବଡ଼ରୁ ଛୋଟ)।',
    corr_title: 'ସଂଖ୍ୟା ସ୍ତମ୍ଭଗୁଡ଼ିକ ଏକାସାଙ୍ଗରେ କିପରି ବଦଳନ୍ତି?',
    corr_intro: 'ସହସମ୍ପର୍କ (r) −1 ରୁ +1 ପର୍ଯ୍ୟନ୍ତ। +1 ପାଖରେ: ଗୋଟିଏ ବଢ଼ିଲେ ଅନ୍ୟଟି ବି ସାଧାରଣତଃ ବଢ଼େ। −1 ପାଖରେ: ଗୋଟିଏ ବଢ଼ିଲେ ଅନ୍ୟଟି ସାଧାରଣତଃ କମେ। 0 ପାଖରେ: କୌଣସି ସିଧା ସମ୍ପର୍କ ନାହିଁ।',
    col_n: 'ସ୍ତମ୍ଭ {n}',
    too_big_save: 'ଏହି ଫାଇଲ ମନେ ରଖିବା ପାଇଁ ବହୁତ ବଡ଼। ଏବେ କାମ କରିବ, କିନ୍ତୁ ପରଥର ପୁଣି ଖୋଲିବାକୁ ପଡ଼ିବ।',
    empty_file: 'ଏହି ଫାଇଲ ଖାଲି। ଅନ୍ୟ ଫାଇଲ ବାଛନ୍ତୁ କିମ୍ବା ଏକ ନମୁନା ଚେଷ୍ଟା କରନ୍ତୁ।',
    only_header: 'ଏହି ଫାଇଲରେ ସ୍ତମ୍ଭ ନାମ ଅଛି, କିନ୍ତୁ ଡାଟାର କୌଣସି ଧାଡ଼ି ନାହିଁ।',
    excel_file: 'ଏହା Excel ଫାଇଲ ପରି ଲାଗୁଛି। Excel ରେ File → Save as → CSV ବାଛନ୍ତୁ, ତା’ପରେ ସେହି CSV ଏଠାରେ ଖୋଲନ୍ତୁ।',
    read_error: 'ଏହି ଫାଇଲ ପଢ଼ି ହେଲା ନାହିଁ। ଏହା କ’ଣ CSV ଟେକ୍ସଟ ଫାଇଲ?',
    pasted_data: 'ପେଷ୍ଟ କରାଯାଇଥିବା ଡାଟା',
    summary: '{rows}ଟି ଧାଡ଼ି, {cols}ଟି ସ୍ତମ୍ଭ, {pct}% ଖାଲି',
    sep_used: 'ଅଲଗା କରିବା ଚିହ୍ନ: {sep}',
    sep_comma: 'କମା (,)', sep_semicolon: 'ସେମିକୋଲନ (;)', sep_tab: 'ଟ୍ୟାବ୍', sep_pipe: 'ପାଇପ୍ (|)',
    ragged_note: '{n}ଟି ଧାଡ଼ିରେ ଘର ସଂଖ୍ୟା ଅଲଗା ଥିଲା। ପ୍ରତ୍ୟେକ ଧାଡ଼ି ପୂରଣ ପାଇଁ ଖାଲି ଘର ଯୋଡ଼ାଗଲା।',
    noname_note: '{n}ଟି ସ୍ତମ୍ଭର ନାମ ନଥିଲା, ତେଣୁ ସେଗୁଡ଼ିକୁ ନମ୍ବର ଦିଆଗଲା।',
    type_number: 'ସଂଖ୍ୟା', type_text: 'ଲେଖା', type_date: 'ତାରିଖ', type_bool: 'ହଁ / ନା', type_empty: 'ଖାଲି',
    st_count: 'ମୂଲ୍ୟ', st_missing: 'ଖାଲି', st_unique: 'ଅଲଗା ମୂଲ୍ୟ', st_min: 'ସବୁଠୁ ଛୋଟ', st_max: 'ସବୁଠୁ ବଡ଼', st_mean: 'ହାରାହାରି', st_median: 'ମଧ୍ୟମା', st_sd: 'ମାନକ ବିଚ୍ୟୁତି', st_sum: 'ଯୋଗଫଳ', st_earliest: 'ସବୁଠୁ ଆଗ', st_latest: 'ସବୁଠୁ ପରେ', st_top: 'ସବୁଠୁ ଅଧିକ',
    invalid_dates: '{n}ଟି ମୂଲ୍ୟ ତାରିଖ ନୁହେଁ (ବାଦ ଦିଆଗଲା)',
    invalid_nums: '{n}ଟି ମୂଲ୍ୟ ସଂଖ୍ୟା ନୁହେଁ (ବାଦ ଦିଆଗଲା)',
    shown_rows: '{n}ଟିରୁ {from}–{to} ଧାଡ଼ି ଦେଖାଯାଉଛି',
    filtered_of: '(ଫାଇଲରେ {n}ଟି ଧାଡ଼ି)',
    shown_none: 'କୌଣସି ଧାଡ଼ି ମେଳ ଖାଉନାହିଁ। ଗୋଟିଏ ଫିଲ୍ଟର ହଟାଇ ଦେଖନ୍ତୁ।',
    page_of: 'ପୃଷ୍ଠା {p} / {n}',
    op_contains: 'ଏଥିରେ ଅଛି', op_equals: 'ଠିକ୍ ଏହା', op_between: 'ମଧ୍ୟରେ ଅଛି', op_missing: 'ଖାଲି ଅଛି', op_notmissing: 'ଖାଲି ନାହିଁ',
    need_value: 'ପ୍ରଥମେ ଏକ ମୂଲ୍ୟ ଲେଖନ୍ତୁ।',
    remove_filter: 'ଫିଲ୍ଟର ହଟାନ୍ତୁ',
    no_filters: 'କୌଣସି ଫିଲ୍ଟର ନାହିଁ। ସବୁ ଧାଡ଼ି ଦେଖାଯାଉଛି।',
    clear_filters: 'ସବୁ ଫିଲ୍ଟର ହଟାନ୍ତୁ',
    show_all: 'ସବୁ ଦେଖାନ୍ତୁ', hide_all: 'ସବୁ ଲୁଚାନ୍ତୁ',
    exported_n: '{n}ଟି ଧାଡ଼ି ଡାଉନଲୋଡ ହେଲା',
    r_strong_pos: 'ଦୃଢ଼ ଧନାତ୍ମକ', r_mod_pos: 'ମଧ୍ୟମ ଧନାତ୍ମକ', r_weak_pos: 'ଦୁର୍ବଳ ଧନାତ୍ମକ', r_none: 'ପ୍ରାୟ କୌଣସି ସମ୍ପର୍କ ନାହିଁ', r_weak_neg: 'ଦୁର୍ବଳ ଋଣାତ୍ମକ', r_mod_neg: 'ମଧ୍ୟମ ଋଣାତ୍ମକ', r_strong_neg: 'ଦୃଢ଼ ଋଣାତ୍ମକ',
    corr_read: '{a} ଓ {b}: {kind} (r = {r})।',
    corr_up: '{a} ଅଧିକ ହେଲେ {b} ବି ସାଧାରଣତଃ ଅଧିକ ହୁଏ।',
    corr_down: '{a} ଅଧିକ ହେଲେ {b} ସାଧାରଣତଃ କମ୍ ହୁଏ।',
    corr_flat: '{a} ଜାଣି {b} ବିଷୟରେ ବେଶି କିଛି ଜଣାପଡ଼େ ନାହିଁ।',
    corr_need: 'ତୁଳନା ପାଇଁ ଅତି କମରେ 2ଟି ସଂଖ୍ୟା ସ୍ତମ୍ଭ ଦରକାର।',
    corr_limit: 'ପ୍ରଥମ {n}ଟି ସଂଖ୍ୟା ସ୍ତମ୍ଭ ଦେଖାଯାଉଛି।',
    corr_neg_label: '−1 ଓଲଟା', corr_pos_label: '+1 ଏକାସାଙ୍ଗରେ',
    corr_pick: 'ଗୋଟିଏ ଘରେ ଟ୍ୟାପ୍ କରି ତାହାର ଅର୍ଥ ଶବ୍ଦରେ ପଢ଼ନ୍ତୁ।',
    corr_self: 'ପ୍ରତ୍ୟେକ ସ୍ତମ୍ଭ ନିଜ ସହ ପୂରା ମେଳ ଖାଏ (r = 1)।',
    corr_warn: 'ସମ୍ପର୍କ ଥିଲେ ପ୍ରମାଣ ହୁଏ ନାହିଁ ଯେ ଗୋଟିଏ ଅନ୍ୟଟିର କାରଣ।',
    corr_na: 'ଏହି ଦୁଇ ସ୍ତମ୍ଭ ତୁଳନା ପାଇଁ ଯଥେଷ୍ଟ ଭରା ଧାଡ଼ି ନାହିଁ।',
    corr_strongest: 'ସବୁଠୁ ଦୃଢ଼ ସମ୍ପର୍କ'
  },
  ta: {
    app_title: 'டேட்டா எக்ஸ்ப்ளோரர்',
    intro: 'எந்த CSV கோப்பையும் திறந்து ஒவ்வொரு நெடுவரிசையையும் ஒரே பார்வையில் காணுங்கள்: வகை, காலி மதிப்புகள், சராசரி, இடைநிலை, அதிகம் வரும் மதிப்புகள், வடிகட்டி, வரிசைப்படுத்தல், ஒட்டுறவு.',
    privacy: 'உங்கள் டேட்டா இந்தச் சாதனத்திலேயே இருக்கும். எதுவும் பதிவேற்றப்படாது.',
    howto: 'எப்படிப் பயன்படுத்துவது / யோசனைகள்',
    tip_1: 'உங்கள் CSV கோப்பைத் திறக்கவும், பெட்டியில் விடவும், Excel அல்லது Google Sheets இலிருந்து வரிசைகளை ஒட்டவும், அல்லது ஒரு மாதிரியை முயலவும்.',
    tip_2: 'நெடுவரிசை விவரத்தில் ஒவ்வொரு நெடுவரிசையின் சுருக்கம் தெரியும்: எத்தனை மதிப்புகள், எத்தனை காலி, மிகச் சிறியது, மிகப் பெரியது, சராசரி, இடைநிலை, அதிகம் வரும் மதிப்புகள்.',
    tip_3: 'டேட்டா அட்டவணையில் வரிசைப்படுத்த நெடுவரிசைப் பெயரைத் தட்டவும், எல்லா நெடுவரிசைகளிலும் தேடவும், வடிகட்டிகளைச் சேர்க்கவும் (உள்ளது, இடையில், காலி). வடிகட்டிய வரிசைகளை மட்டும் புதிய CSV ஆகப் பதிவிறக்கவும்.',
    tip_4: 'அலுவலகத்துக்கு: கடந்த மாத விற்பனைக் கோப்பைத் திறந்து, ஒரு பகுதி அல்லது கட்டண முறையை வடிகட்டி, மொத்தம் மற்றும் விடுபட்ட பில்களைச் சரிபார்த்து, அறிக்கைக்கு அந்த வரிசைகளைப் பதிவிறக்கவும்.',
    tip_5: 'வகுப்புக்கு: வகுப்பு மதிப்பெண் மாதிரியைத் திறக்கவும். மாணவர்கள் கணித சராசரியையும் இடைநிலையையும் கையால் கண்டுபிடித்து, செயலியுடன் ஒப்பிடட்டும். யாருடைய மதிப்பெண் மற்றவர்களை விட மிகவும் வேறுபட்டது? எந்தப் பாடங்கள் சேர்ந்து உயர்கின்றன?',
    tip_6: 'Excel அல்லது Google Sheets கோப்பா? முதலில் CSV ஆகச் சேமிக்கவும் (File → Save as / Download → CSV). 50,000 வரிசைகள் உள்ள பெரிய கோப்பும் இயங்கும்; அட்டவணை ஒரு பக்கத்தில் 100 வரிசைகளைக் காட்டும்.',
    words_title: 'தெரிந்துகொள்ள வேண்டிய சொற்கள்',
    w_dataset: 'டேட்டாசெட்', w_dataset_d: 'டேட்டாவின் ஓர் அட்டவணை, Excel இல் ஒரு தாள் போல. இந்தச் செயலி அதை CSV கோப்பிலிருந்து படிக்கிறது.',
    w_row: 'வரிசை', w_row_d: 'அட்டவணையில் ஒரு பதிவு: ஒரு மாணவர், ஒரு பில், ஒரு மாநிலம்.',
    w_column: 'நெடுவரிசை', w_column_d: 'ஒவ்வொரு வரிசைக்கும் ஒரே வகைத் தகவல்: பெயர், மதிப்பெண், தேதி. ஒவ்வொரு நெடுவரிசைக்கும் ஒரு வகை உண்டு: எண், உரை, தேதி அல்லது ஆம்/இல்லை.',
    w_missing: 'காலி மதிப்பு', w_missing_d: 'காலியான கட்டம், அல்லது NA, N/A, "-" போன்ற எழுத்து. இது எண்ணப்படும், பிறகு கூட்டுத்தொகை மற்றும் சராசரியிலிருந்து விலக்கப்படும்.',
    w_mean: 'சராசரி', w_mean_d: 'எல்லா எண்களையும் கூட்டி, அவை எத்தனை என்பதால் வகுக்கவும்.',
    w_median: 'இடைநிலை', w_median_d: 'வரிசைப்படுத்திய பின் நடுவில் வரும் எண். ஒரு மிகப் பெரிய மதிப்பு இதை அதிகம் இழுக்க முடியாது, எனவே இது பெரும்பாலும் சராசரியை விட நியாயமான படம் தரும்.',
    w_sd: 'திட்ட விலக்கம்', w_sd_d: 'எண்கள் சராசரியைச் சுற்றி எவ்வளவு பரவியுள்ளன. சிறியது: மதிப்புகள் அருகருகே. பெரியது: மதிப்புகள் தொலைவில். (இந்தச் செயலி மாதிரி சூத்திரத்தைப் பயன்படுத்துகிறது, n − 1 ஆல் வகுத்தல்.)',
    w_corr: 'ஒட்டுறவு (r)', w_corr_d: '−1 முதல் +1 வரையிலான ஓர் எண்; இரண்டு எண் நெடுவரிசைகள் சேர்ந்து ஏறி இறங்குகின்றனவா என்று காட்டுகிறது. ஒன்று மற்றொன்றுக்குக் காரணம் என்று இது நிரூபிக்காது.',
    load_title: 'டேட்டாவைத் திற',
    drop_here: 'CSV கோப்பை இங்கே விடவும், அல்லது',
    open_csv: 'CSV கோப்பைத் திற',
    paste_data: 'டேட்டாவை ஒட்டு',
    excel_hint: 'Excel அல்லது Sheets கோப்பா? File → Save as (அல்லது Download) → CSV தேர்ந்தெடுக்கவும். உங்கள் கோப்பு இந்தச் சாதனத்திலேயே இருக்கும்.',
    paste_label: 'Excel, Google Sheets அல்லது CSV கோப்பிலிருந்து வரிசைகளை ஒட்டவும்',
    paste_ph: 'பெயர்,மதிப்பெண்\nஆரவ்,78\nஅனன்யா,92',
    paste_use: 'இந்த டேட்டாவைப் பயன்படுத்து',
    samples: 'அல்லது ஒரு மாதிரியை முயலவும்:',
    sample_marks: 'வகுப்பு மதிப்பெண்கள்', sample_shop: 'கடை விற்பனை (செப்டம்பர்)', sample_rain: 'மாநில வாரியாகப் பருவமழை',
    tabs_label: 'காட்சிகள்',
    tab_cols: 'நெடுவரிசை விவரம்', tab_table: 'டேட்டா அட்டவணை', tab_corr: 'ஒட்டுறவு',
    search_ph: 'எல்லா நெடுவரிசைகளிலும் தேடு…',
    choose_cols: 'நெடுவரிசைகளைத் தேர்ந்தெடு',
    export_csv: 'இந்த வரிசைகளைப் பதிவிறக்கு (CSV)',
    filter_title: 'வடிகட்டிகள்',
    f_col: 'நெடுவரிசை', f_op: 'விதி', f_value: 'மதிப்பு', f_from: 'இருந்து', f_to: 'வரை',
    add_filter: 'வடிகட்டி சேர்',
    sort_hint: 'வரிசைப்படுத்த நெடுவரிசைப் பெயரைத் தட்டவும் (▲ சிறியதிலிருந்து பெரியது, ▼ பெரியதிலிருந்து சிறியது).',
    corr_title: 'எண் நெடுவரிசைகள் சேர்ந்து எப்படி மாறுகின்றன?',
    corr_intro: 'ஒட்டுறவு (r) −1 முதல் +1 வரை. +1 அருகில்: ஒன்று ஏறினால் மற்றதும் பொதுவாக ஏறும். −1 அருகில்: ஒன்று ஏறினால் மற்றது பொதுவாக இறங்கும். 0 அருகில்: நேரான தொடர்பு இல்லை.',
    col_n: 'நெடுவரிசை {n}',
    too_big_save: 'இந்தக் கோப்பு நினைவில் வைக்க மிகப் பெரியது. இப்போது வேலை செய்யும், ஆனால் அடுத்த முறை மீண்டும் திறக்க வேண்டும்.',
    empty_file: 'இந்தக் கோப்பு காலியாக உள்ளது. வேறு கோப்பைத் தேர்ந்தெடுக்கவும் அல்லது ஒரு மாதிரியை முயலவும்.',
    only_header: 'இந்தக் கோப்பில் நெடுவரிசைப் பெயர்கள் உள்ளன, ஆனால் டேட்டா வரிசை எதுவும் இல்லை.',
    excel_file: 'இது Excel கோப்பு போலத் தெரிகிறது. Excel இல் File → Save as → CSV தேர்ந்தெடுத்து, அந்த CSV ஐ இங்கே திறக்கவும்.',
    read_error: 'இந்தக் கோப்பைப் படிக்க முடியவில்லை. இது CSV உரைக் கோப்பா?',
    pasted_data: 'ஒட்டிய டேட்டா',
    summary: '{rows} வரிசைகள், {cols} நெடுவரிசைகள், {pct}% காலி',
    sep_used: 'பிரிக்கும் குறி: {sep}',
    sep_comma: 'காற்புள்ளி (,)', sep_semicolon: 'அரைப்புள்ளி (;)', sep_tab: 'டேப்', sep_pipe: 'பைப் (|)',
    ragged_note: '{n} வரிசைகளில் கட்டங்களின் எண்ணிக்கை வேறுபட்டது. ஒவ்வொரு வரிசையும் பொருந்த காலிக் கட்டங்கள் சேர்க்கப்பட்டன.',
    noname_note: '{n} நெடுவரிசைகளுக்குப் பெயர் இல்லை, எனவே அவற்றுக்கு எண் கொடுக்கப்பட்டது.',
    type_number: 'எண்', type_text: 'உரை', type_date: 'தேதி', type_bool: 'ஆம் / இல்லை', type_empty: 'காலி',
    st_count: 'மதிப்புகள்', st_missing: 'காலி', st_unique: 'வெவ்வேறு மதிப்புகள்', st_min: 'மிகச் சிறியது', st_max: 'மிகப் பெரியது', st_mean: 'சராசரி', st_median: 'இடைநிலை', st_sd: 'திட்ட விலக்கம்', st_sum: 'கூட்டுத்தொகை', st_earliest: 'மிக முந்தையது', st_latest: 'மிகப் பிந்தையது', st_top: 'அதிகம் வருவது',
    invalid_dates: '{n} மதிப்புகள் தேதிகள் அல்ல (விலக்கப்பட்டன)',
    invalid_nums: '{n} மதிப்புகள் எண்கள் அல்ல (விலக்கப்பட்டன)',
    shown_rows: '{n} இல் {from}–{to} வரிசைகள் காட்டப்படுகின்றன',
    filtered_of: '(கோப்பில் {n} வரிசைகள்)',
    shown_none: 'எந்த வரிசையும் பொருந்தவில்லை. ஒரு வடிகட்டியை நீக்கிப் பாருங்கள்.',
    page_of: 'பக்கம் {p} / {n}',
    op_contains: 'இதில் உள்ளது', op_equals: 'சரியாக இதுவே', op_between: 'இடையில் உள்ளது', op_missing: 'காலியாக உள்ளது', op_notmissing: 'காலியாக இல்லை',
    need_value: 'முதலில் ஒரு மதிப்பைத் தட்டச்சு செய்யவும்.',
    remove_filter: 'வடிகட்டியை நீக்கு',
    no_filters: 'வடிகட்டி இல்லை. எல்லா வரிசைகளும் காட்டப்படுகின்றன.',
    clear_filters: 'எல்லா வடிகட்டிகளையும் நீக்கு',
    show_all: 'அனைத்தையும் காட்டு', hide_all: 'அனைத்தையும் மறை',
    exported_n: '{n} வரிசைகள் பதிவிறக்கப்பட்டன',
    r_strong_pos: 'வலுவான நேர்', r_mod_pos: 'மிதமான நேர்', r_weak_pos: 'பலவீனமான நேர்', r_none: 'கிட்டத்தட்டத் தொடர்பு இல்லை', r_weak_neg: 'பலவீனமான எதிர்', r_mod_neg: 'மிதமான எதிர்', r_strong_neg: 'வலுவான எதிர்',
    corr_read: '{a} மற்றும் {b}: {kind} (r = {r}).',
    corr_up: '{a} அதிகமாக இருக்கும்போது {b} உம் பொதுவாக அதிகமாக இருக்கும்.',
    corr_down: '{a} அதிகமாக இருக்கும்போது {b} பொதுவாகக் குறைவாக இருக்கும்.',
    corr_flat: '{a} தெரிந்தாலும் {b} பற்றி அதிகம் தெரியாது.',
    corr_need: 'ஒப்பிட குறைந்தது 2 எண் நெடுவரிசைகள் தேவை.',
    corr_limit: 'முதல் {n} எண் நெடுவரிசைகள் காட்டப்படுகின்றன.',
    corr_neg_label: '−1 எதிர்', corr_pos_label: '+1 சேர்ந்து',
    corr_pick: 'ஒரு கட்டத்தைத் தட்டி அதன் பொருளைச் சொற்களில் படியுங்கள்.',
    corr_self: 'ஒவ்வொரு நெடுவரிசையும் தன்னுடன் முழுமையாகப் பொருந்தும் (r = 1).',
    corr_warn: 'தொடர்பு இருப்பதால் ஒன்று மற்றொன்றுக்குக் காரணம் என்று நிரூபணமாகாது.',
    corr_na: 'இந்த இரண்டு நெடுவரிசைகளை ஒப்பிட போதுமான நிரம்பிய வரிசைகள் இல்லை.',
    corr_strongest: 'வலுவான தொடர்புகள்'
  },
  te: {
    app_title: 'డేటా ఎక్స్‌ప్లోరర్',
    intro: 'ఏ CSV ఫైల్‌నైనా తెరిచి ప్రతి నిలువు వరుసను ఒక్క చూపులో చూడండి: రకం, ఖాళీ విలువలు, సగటు, మధ్యగతం, ఎక్కువగా వచ్చే విలువలు, ఫిల్టర్లు, క్రమం, సహసంబంధం.',
    privacy: 'మీ డేటా ఈ పరికరంలోనే ఉంటుంది. ఏదీ అప్‌లోడ్ కాదు.',
    howto: 'ఎలా వాడాలి / ఆలోచనలు',
    tip_1: 'మీ CSV ఫైల్ తెరవండి, పెట్టెలో వదలండి, Excel లేదా Google Sheets నుండి వరుసలు పేస్ట్ చేయండి, లేదా ఒక నమూనా ప్రయత్నించండి.',
    tip_2: 'నిలువు వరుస వివరాల్లో ప్రతి నిలువు వరుస సారాంశం కనిపిస్తుంది: ఎన్ని విలువలు, ఎన్ని ఖాళీ, అతి చిన్నది, అతి పెద్దది, సగటు, మధ్యగతం, ఎక్కువగా వచ్చే విలువలు.',
    tip_3: 'డేటా పట్టికలో క్రమం కోసం నిలువు వరుస పేరును తాకండి, అన్ని నిలువు వరుసల్లో వెతకండి, ఫిల్టర్లు జోడించండి (ఉంది, మధ్యలో, ఖాళీ). ఫిల్టర్ చేసిన వరుసలను మాత్రమే కొత్త CSV గా డౌన్‌లోడ్ చేయండి.',
    tip_4: 'ఆఫీసు కోసం: గత నెల అమ్మకాల ఫైల్ తెరిచి, ఒక ప్రాంతం లేదా చెల్లింపు రకాన్ని ఫిల్టర్ చేసి, మొత్తాలు, తప్పిపోయిన బిల్లులు చూసి, రిపోర్ట్ కోసం ఆ వరుసలు డౌన్‌లోడ్ చేయండి.',
    tip_5: 'తరగతి కోసం: తరగతి మార్కుల నమూనా తెరవండి. విద్యార్థులు గణితం సగటు, మధ్యగతం చేతితో కనుక్కుని, యాప్‌తో సరిచూడాలి. ఎవరి మార్కులు మిగతావారి కంటే చాలా వేరుగా ఉన్నాయి? ఏ సబ్జెక్టులు కలిసి పెరుగుతాయి?',
    tip_6: 'Excel లేదా Google Sheets ఫైలా? ముందు CSV గా సేవ్ చేయండి (File → Save as / Download → CSV). 50,000 వరుసల పెద్ద ఫైల్ కూడా పనిచేస్తుంది; పట్టిక ఒక పేజీలో 100 వరుసలు చూపిస్తుంది.',
    words_title: 'తెలుసుకోవాల్సిన పదాలు',
    w_dataset: 'డేటాసెట్', w_dataset_d: 'డేటా పట్టిక, Excel లో ఒక షీట్ లాగా. ఈ యాప్ దాన్ని CSV ఫైల్ నుండి చదువుతుంది.',
    w_row: 'వరుస', w_row_d: 'పట్టికలో ఒక రికార్డు: ఒక విద్యార్థి, ఒక బిల్లు, ఒక రాష్ట్రం.',
    w_column: 'నిలువు వరుస', w_column_d: 'ప్రతి వరుసకు ఒకే రకమైన సమాచారం: పేరు, మార్కులు, తేదీ. ప్రతి నిలువు వరుసకు ఒక రకం ఉంటుంది: సంఖ్య, అక్షరాలు, తేదీ లేదా అవును/కాదు.',
    w_missing: 'ఖాళీ విలువ', w_missing_d: 'ఖాళీ గడి, లేదా NA, N/A, "-" లాంటి రాత. దాన్ని లెక్కిస్తారు, తర్వాత మొత్తం, సగటు నుండి వదిలేస్తారు.',
    w_mean: 'సగటు', w_mean_d: 'అన్ని సంఖ్యలను కూడి, అవి ఎన్ని ఉన్నాయో దానితో భాగించండి.',
    w_median: 'మధ్యగతం', w_median_d: 'క్రమంలో పెట్టాక మధ్యలో వచ్చే సంఖ్య. ఒక చాలా పెద్ద విలువ దీన్ని ఎక్కువగా లాగలేదు, కాబట్టి ఇది తరచుగా సగటు కంటే సరైన చిత్రం ఇస్తుంది.',
    w_sd: 'ప్రామాణిక విచలనం', w_sd_d: 'సంఖ్యలు సగటు చుట్టూ ఎంత విస్తరించి ఉన్నాయో. చిన్నది: విలువలు దగ్గరగా. పెద్దది: విలువలు దూరంగా. (ఈ యాప్ నమూనా సూత్రం వాడుతుంది, n − 1 తో భాగహారం.)',
    w_corr: 'సహసంబంధం (r)', w_corr_d: '−1 నుండి +1 వరకు ఒక సంఖ్య; రెండు సంఖ్యా నిలువు వరుసలు కలిసి పెరుగుతాయా తగ్గుతాయా అని చూపిస్తుంది. ఒకటి మరొకదానికి కారణం అని ఇది నిరూపించదు.',
    load_title: 'డేటా తెరవండి',
    drop_here: 'CSV ఫైల్‌ను ఇక్కడ వదలండి, లేదా',
    open_csv: 'CSV ఫైల్ తెరవండి',
    paste_data: 'డేటా పేస్ట్ చేయండి',
    excel_hint: 'Excel లేదా Sheets ఫైలా? File → Save as (లేదా Download) → CSV ఎంచుకోండి. మీ ఫైల్ ఈ పరికరంలోనే ఉంటుంది.',
    paste_label: 'Excel, Google Sheets లేదా CSV ఫైల్ నుండి వరుసలు పేస్ట్ చేయండి',
    paste_ph: 'పేరు,మార్కులు\nఆరవ్,78\nఅనన్య,92',
    paste_use: 'ఈ డేటా వాడండి',
    samples: 'లేదా ఒక నమూనా ప్రయత్నించండి:',
    sample_marks: 'తరగతి మార్కులు', sample_shop: 'దుకాణం అమ్మకాలు (సెప్టెంబర్)', sample_rain: 'రాష్ట్రాల వారీగా వర్షపాతం',
    tabs_label: 'చూపులు',
    tab_cols: 'నిలువు వరుస వివరాలు', tab_table: 'డేటా పట్టిక', tab_corr: 'సహసంబంధం',
    search_ph: 'అన్ని నిలువు వరుసల్లో వెతకండి…',
    choose_cols: 'నిలువు వరుసలు ఎంచుకోండి',
    export_csv: 'ఈ వరుసలు డౌన్‌లోడ్ చేయండి (CSV)',
    filter_title: 'ఫిల్టర్లు',
    f_col: 'నిలువు వరుస', f_op: 'నియమం', f_value: 'విలువ', f_from: 'నుండి', f_to: 'వరకు',
    add_filter: 'ఫిల్టర్ జోడించండి',
    sort_hint: 'క్రమం కోసం నిలువు వరుస పేరును తాకండి (▲ చిన్న నుండి పెద్ద, ▼ పెద్ద నుండి చిన్న).',
    corr_title: 'సంఖ్యా నిలువు వరుసలు కలిసి ఎలా మారతాయి?',
    corr_intro: 'సహసంబంధం (r) −1 నుండి +1 వరకు. +1 దగ్గర: ఒకటి పెరిగితే మరొకటి కూడా సాధారణంగా పెరుగుతుంది. −1 దగ్గర: ఒకటి పెరిగితే మరొకటి సాధారణంగా తగ్గుతుంది. 0 దగ్గర: సూటి సంబంధం లేదు.',
    col_n: 'నిలువు వరుస {n}',
    too_big_save: 'ఈ ఫైల్ గుర్తుంచుకోవడానికి చాలా పెద్దది. ఇప్పుడు పనిచేస్తుంది, కానీ వచ్చేసారి మళ్లీ తెరవాలి.',
    empty_file: 'ఈ ఫైల్ ఖాళీగా ఉంది. వేరే ఫైల్ ఎంచుకోండి లేదా ఒక నమూనా ప్రయత్నించండి.',
    only_header: 'ఈ ఫైల్‌లో నిలువు వరుస పేర్లు ఉన్నాయి, కానీ డేటా వరుస ఒక్కటీ లేదు.',
    excel_file: 'ఇది Excel ఫైల్ లాగా ఉంది. Excel లో File → Save as → CSV ఎంచుకుని, ఆ CSV ని ఇక్కడ తెరవండి.',
    read_error: 'ఈ ఫైల్ చదవలేకపోయాం. ఇది CSV టెక్స్ట్ ఫైలా?',
    pasted_data: 'పేస్ట్ చేసిన డేటా',
    summary: '{rows} వరుసలు, {cols} నిలువు వరుసలు, {pct}% ఖాళీ',
    sep_used: 'వేరుచేసే గుర్తు: {sep}',
    sep_comma: 'కామా (,)', sep_semicolon: 'సెమికోలన్ (;)', sep_tab: 'ట్యాబ్', sep_pipe: 'పైప్ (|)',
    ragged_note: '{n} వరుసల్లో గడుల సంఖ్య వేరుగా ఉంది. ప్రతి వరుస సరిపోయేలా ఖాళీ గడులు జోడించాం.',
    noname_note: '{n} నిలువు వరుసలకు పేరు లేదు, అందుకే వాటికి సంఖ్య ఇచ్చాం.',
    type_number: 'సంఖ్య', type_text: 'అక్షరాలు', type_date: 'తేదీ', type_bool: 'అవును / కాదు', type_empty: 'ఖాళీ',
    st_count: 'విలువలు', st_missing: 'ఖాళీ', st_unique: 'వేర్వేరు విలువలు', st_min: 'అతి చిన్నది', st_max: 'అతి పెద్దది', st_mean: 'సగటు', st_median: 'మధ్యగతం', st_sd: 'ప్రామాణిక విచలనం', st_sum: 'మొత్తం', st_earliest: 'అన్నిటికంటే ముందు', st_latest: 'అన్నిటికంటే తర్వాత', st_top: 'ఎక్కువగా వచ్చేవి',
    invalid_dates: '{n} విలువలు తేదీలు కావు (వదిలేశాం)',
    invalid_nums: '{n} విలువలు సంఖ్యలు కావు (వదిలేశాం)',
    shown_rows: '{n} లో {from}–{to} వరుసలు చూపిస్తున్నాం',
    filtered_of: '(ఫైల్‌లో {n} వరుసలు)',
    shown_none: 'ఏ వరుసా సరిపోలలేదు. ఒక ఫిల్టర్ తీసేసి చూడండి.',
    page_of: 'పేజీ {p} / {n}',
    op_contains: 'ఇందులో ఉంది', op_equals: 'సరిగ్గా ఇదే', op_between: 'మధ్యలో ఉంది', op_missing: 'ఖాళీగా ఉంది', op_notmissing: 'ఖాళీగా లేదు',
    need_value: 'ముందు ఒక విలువ టైప్ చేయండి.',
    remove_filter: 'ఫిల్టర్ తీసేయండి',
    no_filters: 'ఫిల్టర్లు లేవు. అన్ని వరుసలూ చూపిస్తున్నాం.',
    clear_filters: 'అన్ని ఫిల్టర్లు తీసేయండి',
    show_all: 'అన్నీ చూపించు', hide_all: 'అన్నీ దాచు',
    exported_n: '{n} వరుసలు డౌన్‌లోడ్ అయ్యాయి',
    r_strong_pos: 'బలమైన ధన', r_mod_pos: 'మధ్యస్థ ధన', r_weak_pos: 'బలహీన ధన', r_none: 'దాదాపు సంబంధం లేదు', r_weak_neg: 'బలహీన ఋణ', r_mod_neg: 'మధ్యస్థ ఋణ', r_strong_neg: 'బలమైన ఋణ',
    corr_read: '{a} మరియు {b}: {kind} (r = {r}).',
    corr_up: '{a} ఎక్కువగా ఉన్నప్పుడు {b} కూడా సాధారణంగా ఎక్కువగా ఉంటుంది.',
    corr_down: '{a} ఎక్కువగా ఉన్నప్పుడు {b} సాధారణంగా తక్కువగా ఉంటుంది.',
    corr_flat: '{a} తెలిసినా {b} గురించి పెద్దగా తెలియదు.',
    corr_need: 'పోల్చడానికి కనీసం 2 సంఖ్యా నిలువు వరుసలు కావాలి.',
    corr_limit: 'మొదటి {n} సంఖ్యా నిలువు వరుసలు చూపిస్తున్నాం.',
    corr_neg_label: '−1 వ్యతిరేకం', corr_pos_label: '+1 కలిసి',
    corr_pick: 'ఒక గడిని తాకి దాని అర్థం మాటల్లో చదవండి.',
    corr_self: 'ప్రతి నిలువు వరుస తనతో తాను పూర్తిగా సరిపోతుంది (r = 1).',
    corr_warn: 'సంబంధం ఉన్నంత మాత్రాన ఒకటి మరొకదానికి కారణం అని నిరూపణ కాదు.',
    corr_na: 'ఈ రెండు నిలువు వరుసలను పోల్చడానికి సరిపడా నిండిన వరుసలు లేవు.',
    corr_strongest: 'బలమైన సంబంధాలు'
  },
  kn: {
    app_title: 'ಡೇಟಾ ಎಕ್ಸ್‌ಪ್ಲೋರರ್',
    intro: 'ಯಾವುದೇ CSV ಫೈಲ್ ತೆರೆಯಿರಿ ಮತ್ತು ಪ್ರತಿ ಕಾಲಮ್ ಅನ್ನು ಒಂದೇ ನೋಟದಲ್ಲಿ ನೋಡಿ: ಪ್ರಕಾರ, ಖಾಲಿ ಮೌಲ್ಯಗಳು, ಸರಾಸರಿ, ಮಧ್ಯಾಂಕ, ಹೆಚ್ಚು ಬರುವ ಮೌಲ್ಯಗಳು, ಫಿಲ್ಟರ್, ಕ್ರಮ ಮತ್ತು ಸಹಸಂಬಂಧ.',
    privacy: 'ನಿಮ್ಮ ಡೇಟಾ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ. ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ.',
    howto: 'ಬಳಸುವುದು ಹೇಗೆ / ಆಲೋಚನೆಗಳು',
    tip_1: 'ನಿಮ್ಮ CSV ಫೈಲ್ ತೆರೆಯಿರಿ, ಪೆಟ್ಟಿಗೆಯ ಮೇಲೆ ಬಿಡಿ, Excel ಅಥವಾ Google Sheets ನಿಂದ ಸಾಲುಗಳನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ, ಅಥವಾ ಒಂದು ಮಾದರಿ ಪ್ರಯತ್ನಿಸಿ.',
    tip_2: 'ಕಾಲಮ್ ವಿವರದಲ್ಲಿ ಪ್ರತಿ ಕಾಲಮ್‌ನ ಸಾರಾಂಶ ಕಾಣುತ್ತದೆ: ಎಷ್ಟು ಮೌಲ್ಯಗಳು, ಎಷ್ಟು ಖಾಲಿ, ಅತಿ ಚಿಕ್ಕದು, ಅತಿ ದೊಡ್ಡದು, ಸರಾಸರಿ, ಮಧ್ಯಾಂಕ ಮತ್ತು ಹೆಚ್ಚು ಬರುವ ಮೌಲ್ಯಗಳು.',
    tip_3: 'ಡೇಟಾ ಕೋಷ್ಟಕದಲ್ಲಿ ಕ್ರಮಕ್ಕಾಗಿ ಕಾಲಮ್ ಹೆಸರನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ, ಎಲ್ಲ ಕಾಲಮ್‌ಗಳಲ್ಲಿ ಹುಡುಕಿ ಮತ್ತು ಫಿಲ್ಟರ್ ಸೇರಿಸಿ (ಇದೆ, ನಡುವೆ, ಖಾಲಿ). ಫಿಲ್ಟರ್ ಮಾಡಿದ ಸಾಲುಗಳನ್ನು ಮಾತ್ರ ಹೊಸ CSV ಆಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    tip_4: 'ಕಚೇರಿಗೆ: ಕಳೆದ ತಿಂಗಳ ಮಾರಾಟದ ಫೈಲ್ ತೆರೆಯಿರಿ, ಒಂದು ಪ್ರದೇಶ ಅಥವಾ ಪಾವತಿ ವಿಧಾನವನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಿ, ಒಟ್ಟು ಮತ್ತು ಬಿಟ್ಟುಹೋದ ಬಿಲ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ನಂತರ ವರದಿಗಾಗಿ ಆ ಸಾಲುಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    tip_5: 'ತರಗತಿಗೆ: ತರಗತಿ ಅಂಕಗಳ ಮಾದರಿ ತೆರೆಯಿರಿ. ವಿದ್ಯಾರ್ಥಿಗಳು ಗಣಿತದ ಸರಾಸರಿ ಮತ್ತು ಮಧ್ಯಾಂಕವನ್ನು ಕೈಯಿಂದ ಕಂಡುಹಿಡಿದು, ಆ್ಯಪ್‌ನೊಂದಿಗೆ ಹೋಲಿಸಲಿ. ಯಾರ ಅಂಕಗಳು ಉಳಿದವರಿಗಿಂತ ತುಂಬಾ ಬೇರೆ? ಯಾವ ವಿಷಯಗಳು ಜೊತೆಯಾಗಿ ಏರುತ್ತವೆ?',
    tip_6: 'Excel ಅಥವಾ Google Sheets ಫೈಲ್? ಮೊದಲು CSV ಆಗಿ ಉಳಿಸಿ (File → Save as / Download → CSV). 50,000 ಸಾಲುಗಳ ದೊಡ್ಡ ಫೈಲ್ ಕೂಡ ಕೆಲಸ ಮಾಡುತ್ತದೆ; ಕೋಷ್ಟಕ ಒಂದು ಪುಟದಲ್ಲಿ 100 ಸಾಲು ತೋರಿಸುತ್ತದೆ.',
    words_title: 'ತಿಳಿಯಬೇಕಾದ ಪದಗಳು',
    w_dataset: 'ಡೇಟಾಸೆಟ್', w_dataset_d: 'ಡೇಟಾದ ಒಂದು ಕೋಷ್ಟಕ, Excel ನ ಒಂದು ಶೀಟ್‌ನಂತೆ. ಈ ಆ್ಯಪ್ ಅದನ್ನು CSV ಫೈಲ್‌ನಿಂದ ಓದುತ್ತದೆ.',
    w_row: 'ಸಾಲು', w_row_d: 'ಕೋಷ್ಟಕದ ಒಂದು ದಾಖಲೆ: ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿ, ಒಂದು ಬಿಲ್, ಒಂದು ರಾಜ್ಯ.',
    w_column: 'ಕಾಲಮ್', w_column_d: 'ಪ್ರತಿ ಸಾಲಿಗೆ ಒಂದೇ ರೀತಿಯ ಮಾಹಿತಿ: ಹೆಸರು, ಅಂಕ, ದಿನಾಂಕ. ಪ್ರತಿ ಕಾಲಮ್‌ಗೆ ಒಂದು ಪ್ರಕಾರ ಇರುತ್ತದೆ: ಸಂಖ್ಯೆ, ಪಠ್ಯ, ದಿನಾಂಕ ಅಥವಾ ಹೌದು/ಇಲ್ಲ.',
    w_missing: 'ಖಾಲಿ ಮೌಲ್ಯ', w_missing_d: 'ಖಾಲಿ ಕೋಶ, ಅಥವಾ NA, N/A, "-" ಎಂದು ಬರೆದಿರುವುದು. ಅದನ್ನು ಎಣಿಸಲಾಗುತ್ತದೆ, ನಂತರ ಮೊತ್ತ ಮತ್ತು ಸರಾಸರಿಯಿಂದ ಹೊರಗಿಡಲಾಗುತ್ತದೆ.',
    w_mean: 'ಸರಾಸರಿ', w_mean_d: 'ಎಲ್ಲ ಸಂಖ್ಯೆಗಳನ್ನು ಕೂಡಿಸಿ, ಅವು ಎಷ್ಟಿವೆಯೋ ಅದರಿಂದ ಭಾಗಿಸಿ.',
    w_median: 'ಮಧ್ಯಾಂಕ', w_median_d: 'ಕ್ರಮದಲ್ಲಿ ಜೋಡಿಸಿದ ನಂತರ ನಡುವಿನ ಸಂಖ್ಯೆ. ಒಂದು ತುಂಬಾ ದೊಡ್ಡ ಮೌಲ್ಯ ಇದನ್ನು ಹೆಚ್ಚು ಎಳೆಯಲಾಗದು, ಆದ್ದರಿಂದ ಇದು ಹಲವು ಬಾರಿ ಸರಾಸರಿಗಿಂತ ನ್ಯಾಯವಾದ ಚಿತ್ರ ಕೊಡುತ್ತದೆ.',
    w_sd: 'ಪ್ರಮಾಣಿತ ವಿಚಲನೆ', w_sd_d: 'ಸಂಖ್ಯೆಗಳು ಸರಾಸರಿಯ ಸುತ್ತ ಎಷ್ಟು ಹರಡಿವೆ. ಚಿಕ್ಕದು: ಮೌಲ್ಯಗಳು ಹತ್ತಿರ ಹತ್ತಿರ. ದೊಡ್ಡದು: ಮೌಲ್ಯಗಳು ದೂರ ದೂರ. (ಈ ಆ್ಯಪ್ ಮಾದರಿ ಸೂತ್ರ ಬಳಸುತ್ತದೆ, n − 1 ರಿಂದ ಭಾಗ.)',
    w_corr: 'ಸಹಸಂಬಂಧ (r)', w_corr_d: '−1 ರಿಂದ +1 ರವರೆಗಿನ ಒಂದು ಸಂಖ್ಯೆ; ಎರಡು ಸಂಖ್ಯಾ ಕಾಲಮ್‌ಗಳು ಜೊತೆಯಾಗಿ ಏರಿ ಇಳಿಯುತ್ತವೆಯೇ ಎಂದು ತೋರಿಸುತ್ತದೆ. ಒಂದು ಇನ್ನೊಂದಕ್ಕೆ ಕಾರಣ ಎಂದು ಇದು ಸಾಬೀತುಪಡಿಸುವುದಿಲ್ಲ.',
    load_title: 'ಡೇಟಾ ತೆರೆಯಿರಿ',
    drop_here: 'CSV ಫೈಲ್ ಅನ್ನು ಇಲ್ಲಿ ಬಿಡಿ, ಅಥವಾ',
    open_csv: 'CSV ಫೈಲ್ ತೆರೆಯಿರಿ',
    paste_data: 'ಡೇಟಾ ಪೇಸ್ಟ್ ಮಾಡಿ',
    excel_hint: 'Excel ಅಥವಾ Sheets ಫೈಲ್? File → Save as (ಅಥವಾ Download) → CSV ಆಯ್ಕೆಮಾಡಿ. ನಿಮ್ಮ ಫೈಲ್ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ.',
    paste_label: 'Excel, Google Sheets ಅಥವಾ CSV ಫೈಲ್‌ನಿಂದ ಸಾಲುಗಳನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ',
    paste_ph: 'ಹೆಸರು,ಅಂಕ\nಆರವ್,78\nಅನನ್ಯಾ,92',
    paste_use: 'ಈ ಡೇಟಾ ಬಳಸಿ',
    samples: 'ಅಥವಾ ಒಂದು ಮಾದರಿ ಪ್ರಯತ್ನಿಸಿ:',
    sample_marks: 'ತರಗತಿ ಅಂಕಗಳು', sample_shop: 'ಅಂಗಡಿ ಮಾರಾಟ (ಸೆಪ್ಟೆಂಬರ್)', sample_rain: 'ರಾಜ್ಯವಾರು ಮುಂಗಾರು ಮಳೆ',
    tabs_label: 'ನೋಟಗಳು',
    tab_cols: 'ಕಾಲಮ್ ವಿವರ', tab_table: 'ಡೇಟಾ ಕೋಷ್ಟಕ', tab_corr: 'ಸಹಸಂಬಂಧ',
    search_ph: 'ಎಲ್ಲ ಕಾಲಮ್‌ಗಳಲ್ಲಿ ಹುಡುಕಿ…',
    choose_cols: 'ಕಾಲಮ್ ಆಯ್ಕೆಮಾಡಿ',
    export_csv: 'ಈ ಸಾಲುಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (CSV)',
    filter_title: 'ಫಿಲ್ಟರ್‌ಗಳು',
    f_col: 'ಕಾಲಮ್', f_op: 'ನಿಯಮ', f_value: 'ಮೌಲ್ಯ', f_from: 'ಇಂದ', f_to: 'ವರೆಗೆ',
    add_filter: 'ಫಿಲ್ಟರ್ ಸೇರಿಸಿ',
    sort_hint: 'ಕ್ರಮಕ್ಕಾಗಿ ಕಾಲಮ್ ಹೆಸರನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ (▲ ಚಿಕ್ಕದರಿಂದ ದೊಡ್ಡದು, ▼ ದೊಡ್ಡದರಿಂದ ಚಿಕ್ಕದು).',
    corr_title: 'ಸಂಖ್ಯಾ ಕಾಲಮ್‌ಗಳು ಜೊತೆಯಾಗಿ ಹೇಗೆ ಬದಲಾಗುತ್ತವೆ?',
    corr_intro: 'ಸಹಸಂಬಂಧ (r) −1 ರಿಂದ +1 ರವರೆಗೆ. +1 ಹತ್ತಿರ: ಒಂದು ಏರಿದರೆ ಇನ್ನೊಂದೂ ಸಾಮಾನ್ಯವಾಗಿ ಏರುತ್ತದೆ. −1 ಹತ್ತಿರ: ಒಂದು ಏರಿದರೆ ಇನ್ನೊಂದು ಸಾಮಾನ್ಯವಾಗಿ ಇಳಿಯುತ್ತದೆ. 0 ಹತ್ತಿರ: ನೇರ ಸಂಬಂಧವಿಲ್ಲ.',
    col_n: 'ಕಾಲಮ್ {n}',
    too_big_save: 'ಈ ಫೈಲ್ ನೆನಪಿಡಲು ತುಂಬಾ ದೊಡ್ಡದು. ಈಗ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಆದರೆ ಮುಂದಿನ ಬಾರಿ ಮತ್ತೆ ತೆರೆಯಬೇಕು.',
    empty_file: 'ಈ ಫೈಲ್ ಖಾಲಿಯಾಗಿದೆ. ಬೇರೆ ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ಒಂದು ಮಾದರಿ ಪ್ರಯತ್ನಿಸಿ.',
    only_header: 'ಈ ಫೈಲ್‌ನಲ್ಲಿ ಕಾಲಮ್ ಹೆಸರುಗಳಿವೆ, ಆದರೆ ಡೇಟಾದ ಯಾವುದೇ ಸಾಲು ಇಲ್ಲ.',
    excel_file: 'ಇದು Excel ಫೈಲ್‌ನಂತೆ ಕಾಣುತ್ತದೆ. Excel ನಲ್ಲಿ File → Save as → CSV ಆಯ್ಕೆಮಾಡಿ, ನಂತರ ಆ CSV ಅನ್ನು ಇಲ್ಲಿ ತೆರೆಯಿರಿ.',
    read_error: 'ಈ ಫೈಲ್ ಓದಲು ಆಗಲಿಲ್ಲ. ಇದು CSV ಪಠ್ಯ ಫೈಲೇ?',
    pasted_data: 'ಪೇಸ್ಟ್ ಮಾಡಿದ ಡೇಟಾ',
    summary: '{rows} ಸಾಲುಗಳು, {cols} ಕಾಲಮ್‌ಗಳು, {pct}% ಖಾಲಿ',
    sep_used: 'ಬೇರ್ಪಡಿಸುವ ಚಿಹ್ನೆ: {sep}',
    sep_comma: 'ಅಲ್ಪವಿರಾಮ (,)', sep_semicolon: 'ಅರ್ಧವಿರಾಮ (;)', sep_tab: 'ಟ್ಯಾಬ್', sep_pipe: 'ಪೈಪ್ (|)',
    ragged_note: '{n} ಸಾಲುಗಳಲ್ಲಿ ಕೋಶಗಳ ಸಂಖ್ಯೆ ಬೇರೆಯಾಗಿತ್ತು. ಪ್ರತಿ ಸಾಲು ಹೊಂದುವಂತೆ ಖಾಲಿ ಕೋಶಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ.',
    noname_note: '{n} ಕಾಲಮ್‌ಗಳಿಗೆ ಹೆಸರಿರಲಿಲ್ಲ, ಆದ್ದರಿಂದ ಅವುಗಳಿಗೆ ಸಂಖ್ಯೆ ಕೊಡಲಾಗಿದೆ.',
    type_number: 'ಸಂಖ್ಯೆ', type_text: 'ಪಠ್ಯ', type_date: 'ದಿನಾಂಕ', type_bool: 'ಹೌದು / ಇಲ್ಲ', type_empty: 'ಖಾಲಿ',
    st_count: 'ಮೌಲ್ಯಗಳು', st_missing: 'ಖಾಲಿ', st_unique: 'ಬೇರೆ ಬೇರೆ ಮೌಲ್ಯಗಳು', st_min: 'ಅತಿ ಚಿಕ್ಕದು', st_max: 'ಅತಿ ದೊಡ್ಡದು', st_mean: 'ಸರಾಸರಿ', st_median: 'ಮಧ್ಯಾಂಕ', st_sd: 'ಪ್ರಮಾಣಿತ ವಿಚಲನೆ', st_sum: 'ಮೊತ್ತ', st_earliest: 'ಅತಿ ಮೊದಲು', st_latest: 'ಅತಿ ಕೊನೆ', st_top: 'ಹೆಚ್ಚು ಬರುವವು',
    invalid_dates: '{n} ಮೌಲ್ಯಗಳು ದಿನಾಂಕಗಳಲ್ಲ (ಬಿಡಲಾಗಿದೆ)',
    invalid_nums: '{n} ಮೌಲ್ಯಗಳು ಸಂಖ್ಯೆಗಳಲ್ಲ (ಬಿಡಲಾಗಿದೆ)',
    shown_rows: '{n} ರಲ್ಲಿ {from}–{to} ಸಾಲುಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    filtered_of: '(ಫೈಲ್‌ನಲ್ಲಿ {n} ಸಾಲುಗಳು)',
    shown_none: 'ಯಾವ ಸಾಲೂ ಹೊಂದುವುದಿಲ್ಲ. ಒಂದು ಫಿಲ್ಟರ್ ತೆಗೆದು ನೋಡಿ.',
    page_of: 'ಪುಟ {p} / {n}',
    op_contains: 'ಇದರಲ್ಲಿ ಇದೆ', op_equals: 'ನಿಖರವಾಗಿ ಇದೇ', op_between: 'ನಡುವೆ ಇದೆ', op_missing: 'ಖಾಲಿ ಇದೆ', op_notmissing: 'ಖಾಲಿ ಇಲ್ಲ',
    need_value: 'ಮೊದಲು ಒಂದು ಮೌಲ್ಯ ಟೈಪ್ ಮಾಡಿ.',
    remove_filter: 'ಫಿಲ್ಟರ್ ತೆಗೆಯಿರಿ',
    no_filters: 'ಫಿಲ್ಟರ್ ಇಲ್ಲ. ಎಲ್ಲ ಸಾಲುಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.',
    clear_filters: 'ಎಲ್ಲ ಫಿಲ್ಟರ್ ತೆಗೆಯಿರಿ',
    show_all: 'ಎಲ್ಲ ತೋರಿಸಿ', hide_all: 'ಎಲ್ಲ ಮರೆಮಾಡಿ',
    exported_n: '{n} ಸಾಲುಗಳು ಡೌನ್‌ಲೋಡ್ ಆದವು',
    r_strong_pos: 'ಬಲವಾದ ಧನಾತ್ಮಕ', r_mod_pos: 'ಮಧ್ಯಮ ಧನಾತ್ಮಕ', r_weak_pos: 'ದುರ್ಬಲ ಧನಾತ್ಮಕ', r_none: 'ಬಹುತೇಕ ಸಂಬಂಧವಿಲ್ಲ', r_weak_neg: 'ದುರ್ಬಲ ಋಣಾತ್ಮಕ', r_mod_neg: 'ಮಧ್ಯಮ ಋಣಾತ್ಮಕ', r_strong_neg: 'ಬಲವಾದ ಋಣಾತ್ಮಕ',
    corr_read: '{a} ಮತ್ತು {b}: {kind} (r = {r}).',
    corr_up: '{a} ಹೆಚ್ಚಿದ್ದಾಗ {b} ಕೂಡ ಸಾಮಾನ್ಯವಾಗಿ ಹೆಚ್ಚಿರುತ್ತದೆ.',
    corr_down: '{a} ಹೆಚ್ಚಿದ್ದಾಗ {b} ಸಾಮಾನ್ಯವಾಗಿ ಕಡಿಮೆ ಇರುತ್ತದೆ.',
    corr_flat: '{a} ತಿಳಿದರೂ {b} ಬಗ್ಗೆ ಹೆಚ್ಚು ತಿಳಿಯುವುದಿಲ್ಲ.',
    corr_need: 'ಹೋಲಿಸಲು ಕನಿಷ್ಠ 2 ಸಂಖ್ಯಾ ಕಾಲಮ್‌ಗಳು ಬೇಕು.',
    corr_limit: 'ಮೊದಲ {n} ಸಂಖ್ಯಾ ಕಾಲಮ್‌ಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.',
    corr_neg_label: '−1 ವಿರುದ್ಧ', corr_pos_label: '+1 ಜೊತೆಯಾಗಿ',
    corr_pick: 'ಒಂದು ಚೌಕವನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ ಅದರ ಅರ್ಥವನ್ನು ಪದಗಳಲ್ಲಿ ಓದಿ.',
    corr_self: 'ಪ್ರತಿ ಕಾಲಮ್ ತನ್ನೊಂದಿಗೆ ಪೂರ್ತಿ ಹೊಂದುತ್ತದೆ (r = 1).',
    corr_warn: 'ಸಂಬಂಧ ಇದ್ದ ಮಾತ್ರಕ್ಕೆ ಒಂದು ಇನ್ನೊಂದಕ್ಕೆ ಕಾರಣ ಎಂದು ಸಾಬೀತಾಗುವುದಿಲ್ಲ.',
    corr_na: 'ಈ ಎರಡು ಕಾಲಮ್‌ಗಳನ್ನು ಹೋಲಿಸಲು ಸಾಕಷ್ಟು ತುಂಬಿದ ಸಾಲುಗಳಿಲ್ಲ.',
    corr_strongest: 'ಬಲವಾದ ಸಂಬಂಧಗಳು'
  },
  ml: {
    app_title: 'ഡാറ്റ എക്സ്പ്ലോറർ',
    intro: 'ഏത് CSV ഫയലും തുറന്ന് ഓരോ കോളവും ഒറ്റനോട്ടത്തിൽ കാണൂ: തരം, ഒഴിഞ്ഞ മൂല്യങ്ങൾ, ശരാശരി, മധ്യാങ്കം, കൂടുതൽ വരുന്ന മൂല്യങ്ങൾ, ഫിൽട്ടർ, ക്രമീകരണം, സഹബന്ധം.',
    privacy: 'നിങ്ങളുടെ ഡാറ്റ ഈ ഉപകരണത്തിൽ തന്നെ നിൽക്കും. ഒന്നും അപ്‌ലോഡ് ചെയ്യുന്നില്ല.',
    howto: 'എങ്ങനെ ഉപയോഗിക്കാം / ആശയങ്ങൾ',
    tip_1: 'നിങ്ങളുടെ CSV ഫയൽ തുറക്കൂ, പെട്ടിയിലേക്ക് ഇടൂ, Excel അല്ലെങ്കിൽ Google Sheets ൽ നിന്ന് വരികൾ പേസ്റ്റ് ചെയ്യൂ, അല്ലെങ്കിൽ ഒരു മാതൃക പരീക്ഷിക്കൂ.',
    tip_2: 'കോളം വിവരത്തിൽ ഓരോ കോളത്തിന്റെയും ചുരുക്കം കാണാം: എത്ര മൂല്യങ്ങൾ, എത്ര ഒഴിഞ്ഞവ, ഏറ്റവും ചെറുത്, ഏറ്റവും വലുത്, ശരാശരി, മധ്യാങ്കം, കൂടുതൽ വരുന്ന മൂല്യങ്ങൾ.',
    tip_3: 'ഡാറ്റ പട്ടികയിൽ ക്രമീകരിക്കാൻ കോളത്തിന്റെ പേരിൽ തൊടൂ, എല്ലാ കോളങ്ങളിലും തിരയൂ, ഫിൽട്ടർ ചേർക്കൂ (ഉണ്ട്, ഇടയിൽ, ഒഴിഞ്ഞത്). ഫിൽട്ടർ ചെയ്ത വരികൾ മാത്രം പുതിയ CSV ആയി ഡൗൺലോഡ് ചെയ്യൂ.',
    tip_4: 'ഓഫീസിനായി: കഴിഞ്ഞ മാസത്തെ വിൽപ്പന ഫയൽ തുറന്ന്, ഒരു മേഖലയോ പേയ്മെന്റ് രീതിയോ ഫിൽട്ടർ ചെയ്ത്, ആകെത്തുകയും വിട്ടുപോയ ബില്ലുകളും പരിശോധിച്ച്, റിപ്പോർട്ടിനായി ആ വരികൾ ഡൗൺലോഡ് ചെയ്യൂ.',
    tip_5: 'ക്ലാസിനായി: ക്ലാസ് മാർക്ക് മാതൃക തുറക്കൂ. വിദ്യാർത്ഥികൾ ഗണിതത്തിന്റെ ശരാശരിയും മധ്യാങ്കവും കൈകൊണ്ട് കണ്ടെത്തി ആപ്പുമായി ഒത്തുനോക്കട്ടെ. ആരുടെ മാർക്കാണ് മറ്റുള്ളവരിൽ നിന്ന് വളരെ വ്യത്യസ്തം? ഏതു വിഷയങ്ങളാണ് ഒരുമിച്ച് ഉയരുന്നത്?',
    tip_6: 'Excel അല്ലെങ്കിൽ Google Sheets ഫയലാണോ? ആദ്യം CSV ആയി സേവ് ചെയ്യൂ (File → Save as / Download → CSV). 50,000 വരികളുള്ള വലിയ ഫയലും പ്രവർത്തിക്കും; പട്ടിക ഒരു പേജിൽ 100 വരികൾ കാണിക്കും.',
    words_title: 'അറിയേണ്ട വാക്കുകൾ',
    w_dataset: 'ഡാറ്റാസെറ്റ്', w_dataset_d: 'ഡാറ്റയുടെ ഒരു പട്ടിക, Excel ലെ ഒരു ഷീറ്റ് പോലെ. ഈ ആപ്പ് അത് CSV ഫയലിൽ നിന്ന് വായിക്കുന്നു.',
    w_row: 'വരി', w_row_d: 'പട്ടികയിലെ ഒരു രേഖ: ഒരു വിദ്യാർത്ഥി, ഒരു ബിൽ, ഒരു സംസ്ഥാനം.',
    w_column: 'കോളം', w_column_d: 'ഓരോ വരിക്കും ഒരേ തരം വിവരം: പേര്, മാർക്ക്, തീയതി. ഓരോ കോളത്തിനും ഒരു തരം ഉണ്ട്: സംഖ്യ, എഴുത്ത്, തീയതി അല്ലെങ്കിൽ അതെ/ഇല്ല.',
    w_missing: 'ഒഴിഞ്ഞ മൂല്യം', w_missing_d: 'ഒഴിഞ്ഞ കളം, അല്ലെങ്കിൽ NA, N/A, "-" എന്ന് എഴുതിയത്. അത് എണ്ണും, പിന്നെ തുകയിൽ നിന്നും ശരാശരിയിൽ നിന്നും ഒഴിവാക്കും.',
    w_mean: 'ശരാശരി', w_mean_d: 'എല്ലാ സംഖ്യകളും കൂട്ടി, അവ എത്രയുണ്ടോ അതുകൊണ്ട് ഹരിക്കുക.',
    w_median: 'മധ്യാങ്കം', w_median_d: 'ക്രമത്തിലാക്കിയ ശേഷം നടുവിലെ സംഖ്യ. വളരെ വലിയ ഒരു മൂല്യത്തിന് ഇതിനെ അധികം വലിക്കാനാവില്ല, അതിനാൽ ഇത് പലപ്പോഴും ശരാശരിയെക്കാൾ നീതിയുള്ള ചിത്രം തരും.',
    w_sd: 'മാനക വ്യതിയാനം', w_sd_d: 'സംഖ്യകൾ ശരാശരിക്കു ചുറ്റും എത്ര പരന്നിരിക്കുന്നു. ചെറുത്: മൂല്യങ്ങൾ അടുത്തടുത്ത്. വലുത്: മൂല്യങ്ങൾ അകലെ. (ഈ ആപ്പ് സാമ്പിൾ സൂത്രവാക്യം ഉപയോഗിക്കുന്നു, n − 1 കൊണ്ട് ഹരണം.)',
    w_corr: 'സഹബന്ധം (r)', w_corr_d: '−1 മുതൽ +1 വരെയുള്ള ഒരു സംഖ്യ; രണ്ട് സംഖ്യാ കോളങ്ങൾ ഒരുമിച്ച് കൂടുകയും കുറയുകയും ചെയ്യുന്നുണ്ടോ എന്ന് കാണിക്കുന്നു. ഒന്ന് മറ്റൊന്നിന്റെ കാരണമാണെന്ന് ഇത് തെളിയിക്കുന്നില്ല.',
    load_title: 'ഡാറ്റ തുറക്കുക',
    drop_here: 'CSV ഫയൽ ഇവിടെ ഇടൂ, അല്ലെങ്കിൽ',
    open_csv: 'CSV ഫയൽ തുറക്കുക',
    paste_data: 'ഡാറ്റ പേസ്റ്റ് ചെയ്യുക',
    excel_hint: 'Excel അല്ലെങ്കിൽ Sheets ഫയലാണോ? File → Save as (അല്ലെങ്കിൽ Download) → CSV തിരഞ്ഞെടുക്കൂ. നിങ്ങളുടെ ഫയൽ ഈ ഉപകരണത്തിൽ തന്നെ നിൽക്കും.',
    paste_label: 'Excel, Google Sheets അല്ലെങ്കിൽ CSV ഫയലിൽ നിന്ന് വരികൾ പേസ്റ്റ് ചെയ്യൂ',
    paste_ph: 'പേര്,മാർക്ക്\nആരവ്,78\nഅനന്യ,92',
    paste_use: 'ഈ ഡാറ്റ ഉപയോഗിക്കുക',
    samples: 'അല്ലെങ്കിൽ ഒരു മാതൃക പരീക്ഷിക്കൂ:',
    sample_marks: 'ക്ലാസ് മാർക്ക്', sample_shop: 'കടയിലെ വിൽപ്പന (സെപ്റ്റംബർ)', sample_rain: 'സംസ്ഥാനം തിരിച്ചുള്ള മൺസൂൺ മഴ',
    tabs_label: 'കാഴ്ചകൾ',
    tab_cols: 'കോളം വിവരം', tab_table: 'ഡാറ്റ പട്ടിക', tab_corr: 'സഹബന്ധം',
    search_ph: 'എല്ലാ കോളങ്ങളിലും തിരയൂ…',
    choose_cols: 'കോളങ്ങൾ തിരഞ്ഞെടുക്കുക',
    export_csv: 'ഈ വരികൾ ഡൗൺലോഡ് ചെയ്യുക (CSV)',
    filter_title: 'ഫിൽട്ടറുകൾ',
    f_col: 'കോളം', f_op: 'നിയമം', f_value: 'മൂല്യം', f_from: 'മുതൽ', f_to: 'വരെ',
    add_filter: 'ഫിൽട്ടർ ചേർക്കുക',
    sort_hint: 'ക്രമീകരിക്കാൻ കോളത്തിന്റെ പേരിൽ തൊടൂ (▲ ചെറുതിൽ നിന്ന് വലുതിലേക്ക്, ▼ വലുതിൽ നിന്ന് ചെറുതിലേക്ക്).',
    corr_title: 'സംഖ്യാ കോളങ്ങൾ ഒരുമിച്ച് എങ്ങനെ മാറുന്നു?',
    corr_intro: 'സഹബന്ധം (r) −1 മുതൽ +1 വരെ. +1 ന് അടുത്ത്: ഒന്ന് കൂടിയാൽ മറ്റേതും സാധാരണ കൂടും. −1 ന് അടുത്ത്: ഒന്ന് കൂടിയാൽ മറ്റേത് സാധാരണ കുറയും. 0 ന് അടുത്ത്: നേരിട്ടുള്ള ബന്ധമില്ല.',
    col_n: 'കോളം {n}',
    too_big_save: 'ഈ ഫയൽ ഓർത്തുവെക്കാൻ വളരെ വലുതാണ്. ഇപ്പോൾ പ്രവർത്തിക്കും, പക്ഷേ അടുത്ത തവണ വീണ്ടും തുറക്കണം.',
    empty_file: 'ഈ ഫയൽ ഒഴിഞ്ഞതാണ്. മറ്റൊരു ഫയൽ തിരഞ്ഞെടുക്കൂ അല്ലെങ്കിൽ ഒരു മാതൃക പരീക്ഷിക്കൂ.',
    only_header: 'ഈ ഫയലിൽ കോളം പേരുകളുണ്ട്, പക്ഷേ ഡാറ്റയുടെ ഒരു വരി പോലുമില്ല.',
    excel_file: 'ഇത് ഒരു Excel ഫയൽ പോലെ തോന്നുന്നു. Excel ൽ File → Save as → CSV തിരഞ്ഞെടുത്ത്, ആ CSV ഇവിടെ തുറക്കൂ.',
    read_error: 'ഈ ഫയൽ വായിക്കാനായില്ല. ഇത് CSV ടെക്സ്റ്റ് ഫയലാണോ?',
    pasted_data: 'പേസ്റ്റ് ചെയ്ത ഡാറ്റ',
    summary: '{rows} വരികൾ, {cols} കോളങ്ങൾ, {pct}% ഒഴിഞ്ഞത്',
    sep_used: 'വേർതിരിക്കുന്ന ചിഹ്നം: {sep}',
    sep_comma: 'കോമ (,)', sep_semicolon: 'സെമികോളൻ (;)', sep_tab: 'ടാബ്', sep_pipe: 'പൈപ്പ് (|)',
    ragged_note: '{n} വരികളിൽ കളങ്ങളുടെ എണ്ണം വ്യത്യസ്തമായിരുന്നു. ഓരോ വരിയും ഒത്തുവരാൻ ഒഴിഞ്ഞ കളങ്ങൾ ചേർത്തു.',
    noname_note: '{n} കോളങ്ങൾക്ക് പേരില്ലായിരുന്നു, അതിനാൽ അവയ്ക്ക് നമ്പർ നൽകി.',
    type_number: 'സംഖ്യ', type_text: 'എഴുത്ത്', type_date: 'തീയതി', type_bool: 'അതെ / ഇല്ല', type_empty: 'ഒഴിഞ്ഞത്',
    st_count: 'മൂല്യങ്ങൾ', st_missing: 'ഒഴിഞ്ഞത്', st_unique: 'വ്യത്യസ്ത മൂല്യങ്ങൾ', st_min: 'ഏറ്റവും ചെറുത്', st_max: 'ഏറ്റവും വലുത്', st_mean: 'ശരാശരി', st_median: 'മധ്യാങ്കം', st_sd: 'മാനക വ്യതിയാനം', st_sum: 'തുക', st_earliest: 'ഏറ്റവും ആദ്യം', st_latest: 'ഏറ്റവും അവസാനം', st_top: 'കൂടുതൽ വരുന്നവ',
    invalid_dates: '{n} മൂല്യങ്ങൾ തീയതികളല്ല (ഒഴിവാക്കി)',
    invalid_nums: '{n} മൂല്യങ്ങൾ സംഖ്യകളല്ല (ഒഴിവാക്കി)',
    shown_rows: '{n} ൽ {from}–{to} വരികൾ കാണിക്കുന്നു',
    filtered_of: '(ഫയലിൽ {n} വരികൾ)',
    shown_none: 'ഒരു വരിയും ഒത്തുവരുന്നില്ല. ഒരു ഫിൽട്ടർ മാറ്റി നോക്കൂ.',
    page_of: 'പേജ് {p} / {n}',
    op_contains: 'ഇതിൽ ഉണ്ട്', op_equals: 'കൃത്യമായി ഇത്', op_between: 'ഇടയിലാണ്', op_missing: 'ഒഴിഞ്ഞതാണ്', op_notmissing: 'ഒഴിഞ്ഞതല്ല',
    need_value: 'ആദ്യം ഒരു മൂല്യം ടൈപ്പ് ചെയ്യൂ.',
    remove_filter: 'ഫിൽട്ടർ മാറ്റുക',
    no_filters: 'ഫിൽട്ടറില്ല. എല്ലാ വരികളും കാണിക്കുന്നു.',
    clear_filters: 'എല്ലാ ഫിൽട്ടറും മാറ്റുക',
    show_all: 'എല്ലാം കാണിക്കുക', hide_all: 'എല്ലാം മറയ്ക്കുക',
    exported_n: '{n} വരികൾ ഡൗൺലോഡ് ചെയ്തു',
    r_strong_pos: 'ശക്തമായ ധന', r_mod_pos: 'ഇടത്തരം ധന', r_weak_pos: 'ദുർബല ധന', r_none: 'ഏറെക്കുറെ ബന്ധമില്ല', r_weak_neg: 'ദുർബല ഋണ', r_mod_neg: 'ഇടത്തരം ഋണ', r_strong_neg: 'ശക്തമായ ഋണ',
    corr_read: '{a}, {b}: {kind} (r = {r}).',
    corr_up: '{a} കൂടുതലാകുമ്പോൾ {b} യും സാധാരണ കൂടുതലായിരിക്കും.',
    corr_down: '{a} കൂടുതലാകുമ്പോൾ {b} സാധാരണ കുറവായിരിക്കും.',
    corr_flat: '{a} അറിഞ്ഞാലും {b} യെക്കുറിച്ച് അധികം അറിയില്ല.',
    corr_need: 'താരതമ്യത്തിന് കുറഞ്ഞത് 2 സംഖ്യാ കോളങ്ങൾ വേണം.',
    corr_limit: 'ആദ്യത്തെ {n} സംഖ്യാ കോളങ്ങൾ കാണിക്കുന്നു.',
    corr_neg_label: '−1 വിപരീതം', corr_pos_label: '+1 ഒരുമിച്ച്',
    corr_pick: 'ഒരു കളത്തിൽ തൊട്ട് അതിന്റെ അർത്ഥം വാക്കുകളിൽ വായിക്കൂ.',
    corr_self: 'ഓരോ കോളവും തന്നോട് തന്നെ പൂർണമായി ഒത്തുപോകുന്നു (r = 1).',
    corr_warn: 'ബന്ധമുണ്ടെന്നതുകൊണ്ട് ഒന്ന് മറ്റൊന്നിന്റെ കാരണമാണെന്ന് തെളിയുന്നില്ല.',
    corr_na: 'ഈ രണ്ട് കോളങ്ങൾ താരതമ്യം ചെയ്യാൻ ആവശ്യത്തിന് നിറഞ്ഞ വരികളില്ല.',
    corr_strongest: 'ഏറ്റവും ശക്തമായ ബന്ധങ്ങൾ'
  },
  ur: {
    app_title: 'ڈیٹا ایکسپلورر',
    intro: 'کوئی بھی CSV فائل کھولیں اور ہر کالم ایک نظر میں دیکھیں: قسم، خالی خانے، اوسط، وسطانیہ، سب سے عام قدریں، فلٹر، ترتیب اور باہمی تعلق۔',
    privacy: 'آپ کا ڈیٹا اسی ڈیوائس پر رہتا ہے۔ کچھ بھی اپ لوڈ نہیں ہوتا۔',
    howto: 'استعمال کا طریقہ / تجاویز',
    tip_1: 'اپنی CSV فائل کھولیں، اسے خانے پر چھوڑیں، Excel یا Google Sheets سے قطاریں پیسٹ کریں، یا کوئی نمونہ آزمائیں۔',
    tip_2: 'کالم پروفائل میں ہر کالم کا خلاصہ دکھتا ہے: کتنی قدریں، کتنی خالی، سب سے چھوٹی، سب سے بڑی، اوسط، وسطانیہ اور سب سے عام قدریں۔',
    tip_3: 'ڈیٹا ٹیبل میں ترتیب کے لیے کالم کے نام پر ٹیپ کریں، سب کالموں میں تلاش کریں اور فلٹر لگائیں (شامل ہے، کے درمیان، خالی)۔ صرف فلٹر کی گئی قطاریں نئی CSV میں ڈاؤن لوڈ کریں۔',
    tip_4: 'دفتر کے لیے: پچھلے مہینے کی فروخت کی فائل کھولیں، ایک علاقہ یا ادائیگی کا طریقہ فلٹر کریں، کل رقم اور چھوٹے ہوئے بل دیکھیں، پھر رپورٹ کے لیے وہ قطاریں ڈاؤن لوڈ کریں۔',
    tip_5: 'کلاس کے لیے: کلاس کے نمبروں کا نمونہ کھولیں۔ طلبہ ریاضی کا اوسط اور وسطانیہ ہاتھ سے نکالیں، پھر ایپ سے ملائیں۔ کس کے نمبر باقیوں سے بہت الگ ہیں؟ کون سے مضامین ساتھ ساتھ بڑھتے ہیں؟',
    tip_6: 'Excel یا Google Sheets فائل ہے؟ پہلے اسے CSV میں محفوظ کریں (File → Save as / Download → CSV)۔ 50,000 قطاروں والی بڑی فائل بھی چلتی ہے؛ ٹیبل ایک صفحے پر 100 قطاریں دکھاتا ہے۔',
    words_title: 'ضروری الفاظ',
    w_dataset: 'ڈیٹا سیٹ', w_dataset_d: 'ڈیٹا کا ایک ٹیبل، جیسے Excel کی ایک شیٹ۔ یہ ایپ اسے CSV فائل سے پڑھتی ہے۔',
    w_row: 'قطار', w_row_d: 'ٹیبل کا ایک ریکارڈ: ایک طالب علم، ایک بل، ایک ریاست۔',
    w_column: 'کالم', w_column_d: 'ہر قطار کے لیے ایک ہی طرح کی معلومات: نام، نمبر، تاریخ۔ ہر کالم کی ایک قسم ہوتی ہے: عدد، متن، تاریخ یا ہاں/نہیں۔',
    w_missing: 'خالی قدر', w_missing_d: 'خالی خانہ، یا NA، N/A، "-" جیسا لکھا ہو۔ اسے گنا جاتا ہے، پھر جمع اور اوسط سے باہر رکھا جاتا ہے۔',
    w_mean: 'اوسط', w_mean_d: 'سب اعداد جمع کریں اور ان کی گنتی سے تقسیم کریں۔',
    w_median: 'وسطانیہ', w_median_d: 'ترتیب دینے کے بعد بیچ والا عدد۔ ایک بہت بڑی قدر اسے زیادہ نہیں کھینچ سکتی، اس لیے یہ اکثر اوسط سے بہتر تصویر دیتا ہے۔',
    w_sd: 'معیاری انحراف', w_sd_d: 'اعداد اوسط کے آس پاس کتنے پھیلے ہیں۔ چھوٹا: قدریں قریب قریب۔ بڑا: قدریں دور دور۔ (یہ ایپ نمونے والا فارمولا لیتی ہے، n − 1 سے تقسیم۔)',
    w_corr: 'باہمی تعلق (r)', w_corr_d: '−1 سے +1 تک کا ایک عدد، جو بتاتا ہے کہ دو عددی کالم ساتھ ساتھ بڑھتے گھٹتے ہیں یا نہیں۔ اس سے یہ ثابت نہیں ہوتا کہ ایک دوسرے کی وجہ ہے۔',
    load_title: 'ڈیٹا کھولیں',
    drop_here: 'CSV فائل یہاں چھوڑیں، یا',
    open_csv: 'CSV فائل کھولیں',
    paste_data: 'ڈیٹا پیسٹ کریں',
    excel_hint: 'Excel یا Sheets فائل؟ File → Save as (یا Download) → CSV چنیں۔ آپ کی فائل اسی ڈیوائس پر رہتی ہے۔',
    paste_label: 'Excel، Google Sheets یا CSV فائل سے قطاریں پیسٹ کریں',
    paste_ph: 'نام,نمبر\nآرو,78\nاننیا,92',
    paste_use: 'یہ ڈیٹا استعمال کریں',
    samples: 'یا کوئی نمونہ آزمائیں:',
    sample_marks: 'کلاس کے نمبر', sample_shop: 'دکان کی فروخت (ستمبر)', sample_rain: 'ریاستوں میں مون سون کی بارش',
    tabs_label: 'دیکھنے کے طریقے',
    tab_cols: 'کالم پروفائل', tab_table: 'ڈیٹا ٹیبل', tab_corr: 'باہمی تعلق',
    search_ph: 'سب کالموں میں تلاش کریں…',
    choose_cols: 'کالم چنیں',
    export_csv: 'یہ قطاریں ڈاؤن لوڈ کریں (CSV)',
    filter_title: 'فلٹر',
    f_col: 'کالم', f_op: 'اصول', f_value: 'قدر', f_from: 'سے', f_to: 'تک',
    add_filter: 'فلٹر لگائیں',
    sort_hint: 'ترتیب کے لیے کالم کے نام پر ٹیپ کریں (▲ چھوٹے سے بڑا، ▼ بڑے سے چھوٹا)۔',
    corr_title: 'عددی کالم ساتھ ساتھ کیسے بدلتے ہیں؟',
    corr_intro: 'باہمی تعلق (r) −1 سے +1 تک ہوتا ہے۔ +1 کے قریب: ایک بڑھے تو دوسرا بھی اکثر بڑھتا ہے۔ −1 کے قریب: ایک بڑھے تو دوسرا اکثر گھٹتا ہے۔ 0 کے قریب: کوئی سیدھا تعلق نہیں۔',
    col_n: 'کالم {n}',
    too_big_save: 'یہ فائل یاد رکھنے کے لیے بہت بڑی ہے۔ ابھی کام کرے گی، لیکن اگلی بار پھر کھولنی ہوگی۔',
    empty_file: 'یہ فائل خالی ہے۔ دوسری فائل چنیں یا کوئی نمونہ آزمائیں۔',
    only_header: 'اس فائل میں کالموں کے نام ہیں، لیکن ڈیٹا کی کوئی قطار نہیں۔',
    excel_file: 'یہ Excel فائل لگتی ہے۔ Excel میں File → Save as → CSV چنیں، پھر وہ CSV یہاں کھولیں۔',
    read_error: 'یہ فائل پڑھی نہیں جا سکی۔ کیا یہ CSV ٹیکسٹ فائل ہے؟',
    pasted_data: 'پیسٹ کیا گیا ڈیٹا',
    summary: '{rows} قطاریں، {cols} کالم، {pct}% خالی',
    sep_used: 'الگ کرنے والا نشان: {sep}',
    sep_comma: 'کوما (,)', sep_semicolon: 'سیمی کولن (;)', sep_tab: 'ٹیب', sep_pipe: 'پائپ (|)',
    ragged_note: '{n} قطاروں میں خانوں کی گنتی مختلف تھی۔ ہر قطار پوری کرنے کے لیے خالی خانے جوڑے گئے۔',
    noname_note: '{n} کالموں کا کوئی نام نہیں تھا، اس لیے انہیں نمبر دیا گیا۔',
    type_number: 'عدد', type_text: 'متن', type_date: 'تاریخ', type_bool: 'ہاں / نہیں', type_empty: 'خالی',
    st_count: 'قدریں', st_missing: 'خالی', st_unique: 'الگ الگ قدریں', st_min: 'سب سے چھوٹی', st_max: 'سب سے بڑی', st_mean: 'اوسط', st_median: 'وسطانیہ', st_sd: 'معیاری انحراف', st_sum: 'جمع', st_earliest: 'سب سے پہلی', st_latest: 'سب سے آخری', st_top: 'سب سے عام',
    invalid_dates: '{n} قدریں تاریخ نہیں ہیں (چھوڑ دی گئیں)',
    invalid_nums: '{n} قدریں عدد نہیں ہیں (چھوڑ دی گئیں)',
    shown_rows: '{n} میں سے قطاریں {from}–{to} دکھائی جا رہی ہیں',
    filtered_of: '(فائل میں {n} قطاریں)',
    shown_none: 'کوئی قطار میل نہیں کھاتی۔ کوئی فلٹر ہٹا کر دیکھیں۔',
    page_of: 'صفحہ {p} / {n}',
    op_contains: 'میں شامل ہے', op_equals: 'بالکل یہی', op_between: 'کے درمیان ہے', op_missing: 'خالی ہے', op_notmissing: 'خالی نہیں',
    need_value: 'پہلے ایک قدر لکھیں۔',
    remove_filter: 'فلٹر ہٹائیں',
    no_filters: 'کوئی فلٹر نہیں۔ سب قطاریں دکھائی جا رہی ہیں۔',
    clear_filters: 'سب فلٹر ہٹائیں',
    show_all: 'سب دکھائیں', hide_all: 'سب چھپائیں',
    exported_n: '{n} قطاریں ڈاؤن لوڈ ہوئیں',
    r_strong_pos: 'مضبوط مثبت', r_mod_pos: 'درمیانہ مثبت', r_weak_pos: 'کمزور مثبت', r_none: 'تقریباً کوئی تعلق نہیں', r_weak_neg: 'کمزور منفی', r_mod_neg: 'درمیانہ منفی', r_strong_neg: 'مضبوط منفی',
    corr_read: '{a} اور {b}: {kind} (r = {r})۔',
    corr_up: 'جب {a} زیادہ ہو تو {b} بھی اکثر زیادہ ہوتا ہے۔',
    corr_down: 'جب {a} زیادہ ہو تو {b} اکثر کم ہوتا ہے۔',
    corr_flat: '{a} جان کر {b} کے بارے میں زیادہ پتا نہیں چلتا۔',
    corr_need: 'موازنے کے لیے کم از کم 2 عددی کالم چاہئیں۔',
    corr_limit: 'پہلے {n} عددی کالم دکھائے جا رہے ہیں۔',
    corr_neg_label: '−1 الٹا', corr_pos_label: '+1 ساتھ ساتھ',
    corr_pick: 'کسی خانے پر ٹیپ کریں اور اس کا مطلب لفظوں میں پڑھیں۔',
    corr_self: 'ہر کالم خود سے پوری طرح میل کھاتا ہے (r = 1)۔',
    corr_warn: 'تعلق ہونے سے یہ ثابت نہیں ہوتا کہ ایک دوسرے کی وجہ ہے۔',
    corr_na: 'ان دو کالموں کے موازنے کے لیے کافی بھری قطاریں نہیں ہیں۔',
    corr_strongest: 'سب سے مضبوط تعلق'
  }
};
