/* Live Class Quiz: UI strings. Identical keys in all 12 languages.
   Shared words (start, next, delete, edit, cancel, close, save, download, import, export, loading,
   fullscreen, score, try_again, yes, no) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Live Class Quiz',
    intro: 'Host a live quiz on the projector. Sign in with Google to run it online. Students join on their phones with a code and a nickname (no sign-up), answer each question and see who is on top.',
    demo_banner: 'Demo mode: this works on this one device only. To try it, open the student page in another tab. To play on students\' phones, open apnipathshala.ai/teacher and sign in with Google.',
    shell_wa_msg: "{title}: a free live quiz for your class. Students join on their phones with a code and a nickname, no sign-up; the teacher signs in with Google. No ads, 12 Indian languages. Open it here: {url}",
    demo_teacher: 'Demo Teacher',
    signin_title: 'Sign in with Google — free for teachers',
    signin_text: 'Your quizzes are saved online, so you can use them on any computer. Students never sign in: they join with a code and a nickname.',
    signin_google: 'Sign in with Google',
    signin_demo: 'Try it now in Demo mode',
    inapp_hint: 'Google sign-in does not work inside apps like WhatsApp. Open this page in Chrome.',
    use_demo: 'Use Demo mode instead',
    hello: 'Hello, {name}',
    new_quiz: 'New quiz',
    import_qm: 'Import from Quiz Maker on this device',
    import_file: 'Import JSON / CSV',
    import_hint: 'CSV columns: question, option 1 to option 6, correct (1–6 or A–F), explanation.',
    settings_title: 'Settings for live quizzes',
    time_per_q: 'Time for each question',
    sec: '{n} sec',
    shuffle_q: 'Shuffle the questions',
    shuffle_o: 'Shuffle the answer options',
    my_quizzes: 'My quizzes',
    sample_badge: 'Sample',
    n_questions: '{n} questions',
    host: 'Host live',
    edit_copy: 'Edit a copy',
    no_quizzes: 'No quizzes of your own yet. Make a new quiz, import one, or host the sample quiz.',
    confirm_delete_quiz: 'Delete the quiz "{title}"?',
    deleted: 'Deleted.',
    past_sessions: 'Past sessions',
    no_sessions: 'No sessions yet. Host a quiz and its results will appear here.',
    keep_note: 'Results are deleted after 30 days. Download the CSV to keep them.',
    players_n: '{n} players',
    code_n: 'Code {code}',
    state_lobby: 'Waiting',
    state_live: 'Live',
    state_ended: 'Ended',
    results: 'Results',
    resume: 'Resume',
    confirm_delete_session: 'Delete this session with all its answers?',
    account: 'Your account',
    sign_out: 'Sign out',
    delete_account: 'Delete my account and data',
    delete_account_text: 'This deletes your teacher account, all your quizzes and sessions, and every student nickname and answer in them. It cannot be undone.',
    delete_account_tip: 'Download the CSV of any results you want to keep before you do this.',
    delete_account_check: 'I understand. Delete everything.',
    delete_forever: 'Delete forever',
    account_deleted: 'Your account and all its data were deleted.',
    privacy: 'Privacy policy',
    terms: 'Terms of use',
    data_cloud: 'Your quizzes and results are kept in Google Firebase in Mumbai. Students give only a nickname.',
    data_demo: 'In Demo mode everything stays in this browser.',
    edit_quiz: 'Edit quiz',
    quiz_title: 'Quiz title',
    question_n: 'Question {n}',
    option_n: 'Option {n}',
    tick_correct: 'Tick the correct answer.',
    mark_correct: 'Option {n} is the correct answer',
    add_option: 'Add option',
    remove_option: 'Remove option {n}',
    explain_label: 'Explanation (optional, shown after the answer)',
    time_label: 'Time in seconds (optional)',
    time_ph: 'Default',
    add_question: 'Add question',
    move_up: 'Move question {n} up',
    move_down: 'Move question {n} down',
    delete_question: 'Delete question {n}',
    save_quiz: 'Save quiz',
    saved: 'Saved.',
    err_title: 'Please write a title for the quiz.',
    err_no_questions: 'Add at least one question.',
    err_q_text: 'Question {n}: please write the question.',
    err_q_options: 'Question {n}: write at least 2 options.',
    err_q_correct: 'Question {n}: tick the correct answer.',
    draft_restored: 'Your unsaved changes were brought back.',
    confirm_discard: 'Throw away your changes?',
    untitled: 'Untitled quiz',
    opt_true: 'True',
    opt_false: 'False',
    qm_title: 'Quizzes saved in Quiz Maker',
    qm_none: 'No Quiz Maker quizzes were found on this device.',
    open_qm: 'Open Quiz Maker',
    import_selected: 'Import selected',
    imported_n: 'Imported {n} quizzes.',
    skipped_n: '{n} questions were skipped.',
    import_failed: 'Could not read this file. Use a JSON or CSV file from Quiz Maker.',
    join_line: 'Go to {url} and type this code:',
    scan_qr: 'Or scan this QR code',
    qr_offline: 'The QR code needs internet. Students can type the code instead.',
    waiting_players: 'Waiting for students to join…',
    joined_n: '{n} joined',
    lock: 'Lock',
    unlock: 'Unlock',
    locked_note: 'Locked: nobody new can join.',
    kick: 'Remove {name}',
    confirm_kick: 'Remove {name} from this quiz? They cannot join again.',
    start_quiz: 'Start the quiz',
    need_player: 'At least one student must join first.',
    open_student: 'Open a student tab',
    question_of: 'Question {n} of {total}',
    answered_n: '{n} of {total} answered',
    show_answer: 'Show the answer',
    skip_q: 'Skip question',
    time_up: "Time's up!",
    all_answered: 'Everyone has answered!',
    leaderboard: 'Leaderboard',
    next_question: 'Next question',
    final_results: 'Final results',
    end_quiz: 'End quiz',
    confirm_end: 'End the quiz now and show the final results?',
    correct_answer: 'Correct answer',
    points_n: '{n} points',
    col_rank: 'Rank',
    col_nick: 'Nickname',
    col_correct: 'Correct answers',
    col_q: 'Q{n}',
    col_question: 'Question',
    export_csv: 'Export CSV',
    host_again: 'Host again',
    back_dash: 'Back to my quizzes',
    session_gone: 'This quiz session no longer exists.',
    nobody_joined: 'Nobody joined this quiz.',
    keys_hint: 'Keyboard: Space or → for next',
    offline_banner: 'No internet connection. Answers from students may not arrive.',
    connecting: 'Connecting…',
    err_not_configured: 'The online quiz is not set up yet. Try Demo mode.',
    err_offline: 'No internet. Check the connection and try again.',
    err_quota_exceeded: "Today's free limit is used up. Please try again tomorrow, or use Demo mode.",
    err_not_found: 'Not found. It may have been deleted.',
    err_permission_denied: 'You are not allowed to do this. Please sign in again.',
    err_session_locked: 'This quiz is locked.',
    err_session_ended: 'This quiz has ended.',
    err_name_taken: 'Someone already uses this nickname.',
    err_invalid_input: 'Please check what you typed.',
    err_unknown: 'Something went wrong. Please try again.',
    help_title: 'How to use · Ideas for the classroom',
    help_1: 'Sign in and press "Host live" on the sample quiz to see how it works in 10 seconds.',
    help_2: 'Show the screen on the projector. Students open apnipathshala.ai/join on a phone and type the code and a nickname.',
    help_3: 'Ask students to use a nickname, not their full name. Remove anyone with ✕, and press Lock when everyone is in.',
    help_4: 'A correct answer gets 500 to 1000 points: the faster, the more. A wrong answer gets 0.',
    help_5: 'Classroom idea: at the end of a chapter, let groups of 3 share one phone and discuss before they answer.',
    help_6: 'Make quizzes in Quiz Maker and import them here, or type a new one. Export the results as CSV for your records.'
  },
  hi: {
    app_title: 'लाइव क्लास क्विज़',
    intro: 'प्रोजेक्टर पर लाइव क्विज़ चलाइए। ऑनलाइन चलाने के लिए Google से साइन इन करें। विद्यार्थी अपने फ़ोन पर कोड और निकनेम डालकर जुड़ते हैं (कोई साइन-अप नहीं), हर सवाल का जवाब देते हैं और देखते हैं कि कौन सबसे आगे है।',
    demo_banner: 'डेमो मोड: यह सिर्फ़ इसी एक डिवाइस पर चलता है। आज़माने के लिए विद्यार्थी वाला पेज दूसरे टैब में खोलें। विद्यार्थियों के फ़ोन पर खेलने के लिए apnipathshala.ai/teacher खोलें और Google से साइन इन करें।',
    shell_wa_msg: "{title}: आपकी कक्षा के लिए मुफ़्त लाइव क्विज़। विद्यार्थी फ़ोन पर कोड और निकनेम से जुड़ते हैं, कोई साइन-अप नहीं; शिक्षक Google से साइन इन करते हैं। न विज्ञापन, 12 भारतीय भाषाओं में। यहाँ खोलें: {url}",
    demo_teacher: 'डेमो शिक्षक',
    signin_title: 'Google से साइन इन करें — शिक्षकों के लिए मुफ़्त',
    signin_text: 'आपकी क्विज़ ऑनलाइन सेव होती हैं, इसलिए आप उन्हें किसी भी कंप्यूटर पर इस्तेमाल कर सकते हैं। विद्यार्थी कभी साइन इन नहीं करते: वे कोड और निकनेम से जुड़ते हैं।',
    signin_google: 'Google से साइन इन करें',
    signin_demo: 'अभी डेमो मोड में आज़माएँ',
    inapp_hint: 'WhatsApp जैसे ऐप के अंदर Google साइन-इन नहीं चलता। यह पेज Chrome में खोलें।',
    use_demo: 'इसके बजाय डेमो मोड इस्तेमाल करें',
    hello: 'नमस्ते, {name}',
    new_quiz: 'नई क्विज़',
    import_qm: 'इस डिवाइस के क्विज़ मेकर से लाएँ',
    import_file: 'JSON / CSV इम्पोर्ट करें',
    import_hint: 'CSV के कॉलम: सवाल, विकल्प 1 से विकल्प 6, सही उत्तर (1–6 या A–F), व्याख्या।',
    settings_title: 'लाइव क्विज़ की सेटिंग्स',
    time_per_q: 'हर सवाल का समय',
    sec: '{n} सेकंड',
    shuffle_q: 'सवालों का क्रम बदलें',
    shuffle_o: 'विकल्पों का क्रम बदलें',
    my_quizzes: 'मेरी क्विज़',
    sample_badge: 'नमूना',
    n_questions: '{n} सवाल',
    host: 'लाइव चलाएँ',
    edit_copy: 'कॉपी बनाकर बदलें',
    no_quizzes: 'अभी आपकी अपनी कोई क्विज़ नहीं है। नई क्विज़ बनाएँ, इम्पोर्ट करें या नमूना क्विज़ चलाएँ।',
    confirm_delete_quiz: 'क्विज़ "{title}" हटाएँ?',
    deleted: 'हटा दिया गया।',
    past_sessions: 'पिछले सेशन',
    no_sessions: 'अभी कोई सेशन नहीं है। कोई क्विज़ चलाइए, उसके नतीजे यहाँ दिखेंगे।',
    keep_note: 'नतीजे 30 दिन बाद मिट जाते हैं। रखने के लिए CSV डाउनलोड कर लें।',
    players_n: '{n} खिलाड़ी',
    code_n: 'कोड {code}',
    state_lobby: 'इंतज़ार में',
    state_live: 'चल रहा है',
    state_ended: 'ख़त्म',
    results: 'नतीजे',
    resume: 'फिर से शुरू करें',
    confirm_delete_session: 'यह सेशन उसके सभी जवाबों के साथ हटाएँ?',
    account: 'आपका अकाउंट',
    sign_out: 'साइन आउट',
    delete_account: 'मेरा अकाउंट और डेटा मिटाएँ',
    delete_account_text: 'इससे आपका शिक्षक अकाउंट, आपकी सारी क्विज़ और सेशन, और उनमें विद्यार्थियों के सभी निकनेम और जवाब मिट जाएँगे। इसे वापस नहीं लाया जा सकता।',
    delete_account_tip: 'ऐसा करने से पहले जो नतीजे रखने हैं, उनकी CSV डाउनलोड कर लें।',
    delete_account_check: 'मैं समझता/समझती हूँ। सब कुछ हटा दें।',
    delete_forever: 'हमेशा के लिए हटाएँ',
    account_deleted: 'आपका अकाउंट और उसका सारा डेटा हटा दिया गया।',
    privacy: 'प्राइवेसी नीति',
    terms: 'इस्तेमाल की शर्तें',
    data_cloud: 'आपकी क्विज़ और नतीजे Google Firebase (मुंबई) में रखे जाते हैं। विद्यार्थी सिर्फ़ निकनेम देते हैं।',
    data_demo: 'डेमो मोड में सब कुछ इसी ब्राउज़र में रहता है।',
    edit_quiz: 'क्विज़ बदलें',
    quiz_title: 'क्विज़ का नाम',
    question_n: 'सवाल {n}',
    option_n: 'विकल्प {n}',
    tick_correct: 'सही उत्तर पर टिक करें।',
    mark_correct: 'विकल्प {n} सही उत्तर है',
    add_option: 'विकल्प जोड़ें',
    remove_option: 'विकल्प {n} हटाएँ',
    explain_label: 'व्याख्या (ज़रूरी नहीं, उत्तर के बाद दिखेगी)',
    time_label: 'समय सेकंड में (ज़रूरी नहीं)',
    time_ph: 'डिफ़ॉल्ट',
    add_question: 'सवाल जोड़ें',
    move_up: 'सवाल {n} ऊपर ले जाएँ',
    move_down: 'सवाल {n} नीचे ले जाएँ',
    delete_question: 'सवाल {n} हटाएँ',
    save_quiz: 'क्विज़ सेव करें',
    saved: 'सेव हो गया।',
    err_title: 'कृपया क्विज़ का नाम लिखें।',
    err_no_questions: 'कम से कम एक सवाल जोड़ें।',
    err_q_text: 'सवाल {n}: कृपया सवाल लिखें।',
    err_q_options: 'सवाल {n}: कम से कम 2 विकल्प लिखें।',
    err_q_correct: 'सवाल {n}: सही उत्तर पर टिक करें।',
    draft_restored: 'आपके बिना सेव किए बदलाव वापस आ गए।',
    confirm_discard: 'अपने बदलाव छोड़ दें?',
    untitled: 'बिना नाम की क्विज़',
    opt_true: 'सही',
    opt_false: 'गलत',
    qm_title: 'क्विज़ मेकर में सेव क्विज़',
    qm_none: 'इस डिवाइस पर क्विज़ मेकर की कोई क्विज़ नहीं मिली।',
    open_qm: 'क्विज़ मेकर खोलें',
    import_selected: 'चुनी हुई इम्पोर्ट करें',
    imported_n: '{n} क्विज़ इम्पोर्ट हो गईं।',
    skipped_n: '{n} सवाल छोड़ दिए गए।',
    import_failed: 'यह फ़ाइल नहीं पढ़ी जा सकी। क्विज़ मेकर की JSON या CSV फ़ाइल इस्तेमाल करें।',
    join_line: '{url} पर जाएँ और यह कोड डालें:',
    scan_qr: 'या यह QR कोड स्कैन करें',
    qr_offline: 'QR कोड के लिए इंटरनेट चाहिए। विद्यार्थी कोड टाइप कर सकते हैं।',
    waiting_players: 'विद्यार्थियों के जुड़ने का इंतज़ार…',
    joined_n: '{n} जुड़े',
    lock: 'लॉक करें',
    unlock: 'अनलॉक करें',
    locked_note: 'लॉक है: अब कोई नया नहीं जुड़ सकता।',
    kick: '{name} को हटाएँ',
    confirm_kick: '{name} को इस क्विज़ से हटाएँ? वे फिर से नहीं जुड़ पाएँगे।',
    start_quiz: 'क्विज़ शुरू करें',
    need_player: 'पहले कम से कम एक विद्यार्थी को जुड़ना होगा।',
    open_student: 'विद्यार्थी वाला टैब खोलें',
    question_of: 'सवाल {n} / {total}',
    answered_n: '{total} में से {n} ने जवाब दिया',
    show_answer: 'उत्तर दिखाएँ',
    skip_q: 'सवाल छोड़ें',
    time_up: 'समय ख़त्म!',
    all_answered: 'सबने जवाब दे दिया!',
    leaderboard: 'लीडरबोर्ड',
    next_question: 'अगला सवाल',
    final_results: 'अंतिम नतीजे',
    end_quiz: 'क्विज़ ख़त्म करें',
    confirm_end: 'क्विज़ अभी ख़त्म करके अंतिम नतीजे दिखाएँ?',
    correct_answer: 'सही उत्तर',
    points_n: '{n} अंक',
    col_rank: 'रैंक',
    col_nick: 'निकनेम',
    col_correct: 'सही जवाब',
    col_q: 'प्र{n}',
    col_question: 'सवाल',
    export_csv: 'CSV एक्सपोर्ट करें',
    host_again: 'फिर से चलाएँ',
    back_dash: 'मेरी क्विज़ पर वापस',
    session_gone: 'यह क्विज़ सेशन अब मौजूद नहीं है।',
    nobody_joined: 'इस क्विज़ में कोई नहीं जुड़ा।',
    keys_hint: 'कीबोर्ड: आगे के लिए Space या →',
    offline_banner: 'इंटरनेट कनेक्शन नहीं है। विद्यार्थियों के जवाब शायद न पहुँचें।',
    connecting: 'जुड़ रहा है…',
    err_not_configured: 'ऑनलाइन क्विज़ अभी सेट नहीं हुई है। डेमो मोड आज़माएँ।',
    err_offline: 'इंटरनेट नहीं है। कनेक्शन देखकर फिर कोशिश करें।',
    err_quota_exceeded: 'आज की मुफ़्त सीमा पूरी हो गई। कृपया कल फिर कोशिश करें, या डेमो मोड इस्तेमाल करें।',
    err_not_found: 'नहीं मिला। शायद इसे हटा दिया गया है।',
    err_permission_denied: 'आपको यह करने की अनुमति नहीं है। कृपया फिर से साइन इन करें।',
    err_session_locked: 'यह क्विज़ लॉक है।',
    err_session_ended: 'यह क्विज़ ख़त्म हो चुकी है।',
    err_name_taken: 'यह निकनेम कोई और इस्तेमाल कर रहा है।',
    err_invalid_input: 'कृपया जो लिखा है उसे जाँच लें।',
    err_unknown: 'कुछ गड़बड़ हो गई। कृपया फिर कोशिश करें।',
    help_title: 'कैसे इस्तेमाल करें · कक्षा के लिए आइडिया',
    help_1: 'साइन इन करें और नमूना क्विज़ पर "लाइव चलाएँ" दबाएँ, 10 सेकंड में समझ आ जाएगा कि यह कैसे चलता है।',
    help_2: 'स्क्रीन प्रोजेक्टर पर दिखाएँ। विद्यार्थी फ़ोन पर apnipathshala.ai/join खोलकर कोड और निकनेम डालें।',
    help_3: 'विद्यार्थियों से कहें कि पूरा नाम नहीं, निकनेम लिखें। ✕ से किसी को भी हटा सकते हैं, और सब आ जाएँ तो लॉक दबाएँ।',
    help_4: 'सही जवाब पर 500 से 1000 अंक मिलते हैं: जितना जल्दी, उतने ज़्यादा। गलत जवाब पर 0।',
    help_5: 'कक्षा के लिए आइडिया: अध्याय के अंत में 3-3 के समूह एक फ़ोन पर मिलकर सोचें, फिर जवाब दें।',
    help_6: 'क्विज़ मेकर में क्विज़ बनाकर यहाँ इम्पोर्ट करें, या नई क्विज़ टाइप करें। नतीजे CSV में एक्सपोर्ट करके रिकॉर्ड रखें।'
  },
  bn: {
    app_title: 'লাইভ ক্লাস কুইজ',
    intro: 'প্রজেক্টরে লাইভ কুইজ চালান। অনলাইনে চালাতে Google দিয়ে সাইন ইন করুন। শিক্ষার্থীরা ফোনে কোড আর ডাকনাম দিয়ে যোগ দেয় (সাইন-আপ লাগে না), প্রতিটি প্রশ্নের উত্তর দেয় আর দেখে কে সবার আগে।',
    demo_banner: 'ডেমো মোড: এটি শুধু এই একটি ডিভাইসে চলে। চেষ্টা করতে অন্য ট্যাবে শিক্ষার্থীদের পেজটি খুলুন। শিক্ষার্থীদের ফোনে খেলতে apnipathshala.ai/teacher খুলে Google দিয়ে সাইন ইন করুন।',
    shell_wa_msg: "{title}: আপনার ক্লাসের জন্য বিনামূল্যের লাইভ কুইজ। শিক্ষার্থীরা ফোনে কোড আর ডাকনাম দিয়ে যোগ দেয়, সাইন-আপ লাগে না; শিক্ষক Google দিয়ে সাইন ইন করেন। বিজ্ঞাপন নেই, 12টি ভারতীয় ভাষায়। এখানে খুলুন: {url}",
    demo_teacher: 'ডেমো শিক্ষক',
    signin_title: 'Google দিয়ে সাইন ইন করুন — শিক্ষকদের জন্য বিনামূল্যে',
    signin_text: 'আপনার কুইজ অনলাইনে সেভ থাকে, তাই যেকোনো কম্পিউটারে ব্যবহার করতে পারবেন। শিক্ষার্থীদের কখনো সাইন ইন করতে হয় না: তারা কোড আর ডাকনাম দিয়ে যোগ দেয়।',
    signin_google: 'Google দিয়ে সাইন ইন করুন',
    signin_demo: 'এখনই ডেমো মোডে চেষ্টা করুন',
    inapp_hint: 'WhatsApp-এর মতো অ্যাপের ভেতরে Google সাইন-ইন কাজ করে না। পেজটি Chrome-এ খুলুন।',
    use_demo: 'এর বদলে ডেমো মোড ব্যবহার করুন',
    hello: 'নমস্কার, {name}',
    new_quiz: 'নতুন কুইজ',
    import_qm: 'এই ডিভাইসের কুইজ মেকার থেকে আনুন',
    import_file: 'JSON / CSV ইমপোর্ট করুন',
    import_hint: 'CSV-এর কলাম: প্রশ্ন, বিকল্প 1 থেকে বিকল্প 6, সঠিক উত্তর (1–6 বা A–F), ব্যাখ্যা।',
    settings_title: 'লাইভ কুইজের সেটিংস',
    time_per_q: 'প্রতিটি প্রশ্নের সময়',
    sec: '{n} সেকেন্ড',
    shuffle_q: 'প্রশ্নের ক্রম এলোমেলো করুন',
    shuffle_o: 'বিকল্পের ক্রম এলোমেলো করুন',
    my_quizzes: 'আমার কুইজ',
    sample_badge: 'নমুনা',
    n_questions: '{n}টি প্রশ্ন',
    host: 'লাইভ চালান',
    edit_copy: 'কপি করে সম্পাদনা',
    no_quizzes: 'এখনও আপনার নিজের কোনো কুইজ নেই। নতুন কুইজ বানান, ইমপোর্ট করুন বা নমুনা কুইজ চালান।',
    confirm_delete_quiz: '"{title}" কুইজটি মুছবেন?',
    deleted: 'মুছে ফেলা হয়েছে।',
    past_sessions: 'আগের সেশন',
    no_sessions: 'এখনও কোনো সেশন নেই। একটি কুইজ চালান, তার ফলাফল এখানে দেখা যাবে।',
    keep_note: 'ফলাফল 30 দিন পরে মুছে যায়। রাখতে চাইলে CSV ডাউনলোড করে নিন।',
    players_n: '{n} জন খেলোয়াড়',
    code_n: 'কোড {code}',
    state_lobby: 'অপেক্ষায়',
    state_live: 'চলছে',
    state_ended: 'শেষ',
    results: 'ফলাফল',
    resume: 'আবার চালু করুন',
    confirm_delete_session: 'এই সেশনটি সব উত্তরসহ মুছবেন?',
    account: 'আপনার অ্যাকাউন্ট',
    sign_out: 'সাইন আউট',
    delete_account: 'আমার অ্যাকাউন্ট আর ডেটা মুছুন',
    delete_account_text: 'এতে আপনার শিক্ষক অ্যাকাউন্ট, আপনার সব কুইজ ও সেশন, আর তাতে থাকা শিক্ষার্থীদের সব ডাকনাম ও উত্তর মুছে যাবে। এটি আর ফেরানো যাবে না।',
    delete_account_tip: 'এটি করার আগে যে ফলাফল রাখতে চান, তার CSV ডাউনলোড করে নিন।',
    delete_account_check: 'আমি বুঝেছি। সব মুছে দিন।',
    delete_forever: 'চিরতরে মুছুন',
    account_deleted: 'আপনার অ্যাকাউন্ট ও তার সব ডেটা মুছে ফেলা হয়েছে।',
    privacy: 'গোপনীয়তা নীতি',
    terms: 'ব্যবহারের শর্তাবলি',
    data_cloud: 'আপনার কুইজ ও ফলাফল Google Firebase-এ (মুম্বাই) রাখা হয়। শিক্ষার্থীরা শুধু ডাকনাম দেয়।',
    data_demo: 'ডেমো মোডে সবকিছু এই ব্রাউজারেই থাকে।',
    edit_quiz: 'কুইজ সম্পাদনা',
    quiz_title: 'কুইজের নাম',
    question_n: 'প্রশ্ন {n}',
    option_n: 'বিকল্প {n}',
    tick_correct: 'সঠিক উত্তরে টিক দিন।',
    mark_correct: 'বিকল্প {n} সঠিক উত্তর',
    add_option: 'বিকল্প যোগ করুন',
    remove_option: 'বিকল্প {n} সরান',
    explain_label: 'ব্যাখ্যা (ঐচ্ছিক, উত্তরের পরে দেখানো হবে)',
    time_label: 'সময় সেকেন্ডে (ঐচ্ছিক)',
    time_ph: 'ডিফল্ট',
    add_question: 'প্রশ্ন যোগ করুন',
    move_up: 'প্রশ্ন {n} ওপরে সরান',
    move_down: 'প্রশ্ন {n} নিচে সরান',
    delete_question: 'প্রশ্ন {n} মুছুন',
    save_quiz: 'কুইজ সেভ করুন',
    saved: 'সেভ হয়েছে।',
    err_title: 'কুইজের একটি নাম লিখুন।',
    err_no_questions: 'অন্তত একটি প্রশ্ন যোগ করুন।',
    err_q_text: 'প্রশ্ন {n}: প্রশ্নটি লিখুন।',
    err_q_options: 'প্রশ্ন {n}: অন্তত 2টি বিকল্প লিখুন।',
    err_q_correct: 'প্রশ্ন {n}: সঠিক উত্তরে টিক দিন।',
    draft_restored: 'আপনার সেভ না করা পরিবর্তন ফিরিয়ে আনা হয়েছে।',
    confirm_discard: 'আপনার পরিবর্তনগুলো বাদ দেবেন?',
    untitled: 'নামহীন কুইজ',
    opt_true: 'সত্য',
    opt_false: 'মিথ্যা',
    qm_title: 'কুইজ মেকারে সেভ করা কুইজ',
    qm_none: 'এই ডিভাইসে কুইজ মেকারের কোনো কুইজ পাওয়া যায়নি।',
    open_qm: 'কুইজ মেকার খুলুন',
    import_selected: 'বাছাই করাগুলো ইমপোর্ট করুন',
    imported_n: '{n}টি কুইজ ইমপোর্ট হয়েছে।',
    skipped_n: '{n}টি প্রশ্ন বাদ পড়েছে।',
    import_failed: 'এই ফাইলটি পড়া গেল না। কুইজ মেকারের JSON বা CSV ফাইল ব্যবহার করুন।',
    join_line: '{url}-এ যান আর এই কোডটি লিখুন:',
    scan_qr: 'অথবা এই QR কোড স্ক্যান করুন',
    qr_offline: 'QR কোডের জন্য ইন্টারনেট লাগে। শিক্ষার্থীরা কোডটি টাইপ করতে পারে।',
    waiting_players: 'শিক্ষার্থীদের যোগ দেওয়ার অপেক্ষা…',
    joined_n: '{n} জন যোগ দিয়েছে',
    lock: 'লক করুন',
    unlock: 'আনলক করুন',
    locked_note: 'লক করা: নতুন কেউ যোগ দিতে পারবে না।',
    kick: '{name}-কে সরান',
    confirm_kick: '{name}-কে এই কুইজ থেকে সরাবেন? সে আর যোগ দিতে পারবে না।',
    start_quiz: 'কুইজ শুরু করুন',
    need_player: 'আগে অন্তত একজন শিক্ষার্থীকে যোগ দিতে হবে।',
    open_student: 'শিক্ষার্থীর ট্যাব খুলুন',
    question_of: 'প্রশ্ন {n} / {total}',
    answered_n: '{total} জনের মধ্যে {n} জন উত্তর দিয়েছে',
    show_answer: 'উত্তর দেখান',
    skip_q: 'প্রশ্ন বাদ দিন',
    time_up: 'সময় শেষ!',
    all_answered: 'সবাই উত্তর দিয়েছে!',
    leaderboard: 'লিডারবোর্ড',
    next_question: 'পরের প্রশ্ন',
    final_results: 'চূড়ান্ত ফলাফল',
    end_quiz: 'কুইজ শেষ করুন',
    confirm_end: 'এখনই কুইজ শেষ করে চূড়ান্ত ফলাফল দেখাবেন?',
    correct_answer: 'সঠিক উত্তর',
    points_n: '{n} পয়েন্ট',
    col_rank: 'র‍্যাঙ্ক',
    col_nick: 'ডাকনাম',
    col_correct: 'সঠিক উত্তর',
    col_q: 'প্র{n}',
    col_question: 'প্রশ্ন',
    export_csv: 'CSV এক্সপোর্ট করুন',
    host_again: 'আবার চালান',
    back_dash: 'আমার কুইজে ফিরে যান',
    session_gone: 'এই কুইজ সেশনটি আর নেই।',
    nobody_joined: 'এই কুইজে কেউ যোগ দেয়নি।',
    keys_hint: 'কিবোর্ড: পরের জন্য Space বা →',
    offline_banner: 'ইন্টারনেট সংযোগ নেই। শিক্ষার্থীদের উত্তর হয়তো পৌঁছাবে না।',
    connecting: 'সংযোগ হচ্ছে…',
    err_not_configured: 'অনলাইন কুইজ এখনও চালু হয়নি। ডেমো মোড চেষ্টা করুন।',
    err_offline: 'ইন্টারনেট নেই। সংযোগ দেখে আবার চেষ্টা করুন।',
    err_quota_exceeded: 'আজকের বিনামূল্যের সীমা শেষ। কাল আবার চেষ্টা করুন, অথবা ডেমো মোড ব্যবহার করুন।',
    err_not_found: 'পাওয়া যায়নি। হয়তো মুছে ফেলা হয়েছে।',
    err_permission_denied: 'এটি করার অনুমতি আপনার নেই। আবার সাইন ইন করুন।',
    err_session_locked: 'এই কুইজটি লক করা।',
    err_session_ended: 'এই কুইজ শেষ হয়ে গেছে।',
    err_name_taken: 'এই ডাকনাম অন্য কেউ ব্যবহার করছে।',
    err_invalid_input: 'যা লিখেছেন তা একবার দেখে নিন।',
    err_unknown: 'কিছু একটা ভুল হয়েছে। আবার চেষ্টা করুন।',
    help_title: 'কীভাবে ব্যবহার করবেন · ক্লাসের জন্য আইডিয়া',
    help_1: 'সাইন ইন করে নমুনা কুইজে "লাইভ চালান" টিপুন, 10 সেকেন্ডেই বুঝে যাবেন কীভাবে চলে।',
    help_2: 'স্ক্রিনটি প্রজেক্টরে দেখান। শিক্ষার্থীরা ফোনে apnipathshala.ai/join খুলে কোড আর ডাকনাম লেখে।',
    help_3: 'শিক্ষার্থীদের পুরো নাম নয়, ডাকনাম লিখতে বলুন। ✕ দিয়ে যে কাউকে সরাতে পারেন, আর সবাই এলে লক টিপুন।',
    help_4: 'সঠিক উত্তরে 500 থেকে 1000 পয়েন্ট: যত তাড়াতাড়ি, তত বেশি। ভুল উত্তরে 0।',
    help_5: 'ক্লাসের আইডিয়া: অধ্যায়ের শেষে 3 জনের দল একটি ফোনে আলোচনা করে উত্তর দিক।',
    help_6: 'কুইজ মেকারে কুইজ বানিয়ে এখানে ইমপোর্ট করুন, বা নতুন কুইজ লিখুন। রেকর্ডের জন্য ফলাফল CSV-তে এক্সপোর্ট করুন।'
  },
  mr: {
    app_title: 'लाइव्ह वर्ग क्विझ',
    intro: 'प्रोजेक्टरवर लाइव्ह क्विझ घ्या. ऑनलाइन घेण्यासाठी Google ने साइन इन करा. विद्यार्थी फोनवर कोड आणि टोपणनाव टाकून सामील होतात (साइन-अप नाही), प्रत्येक प्रश्नाचे उत्तर देतात आणि कोण पुढे आहे ते पाहतात.',
    demo_banner: 'डेमो मोड: हे फक्त याच एका डिव्हाइसवर चालते. वापरून पाहण्यासाठी विद्यार्थ्यांचे पेज दुसऱ्या टॅबमध्ये उघडा. विद्यार्थ्यांच्या फोनवर खेळण्यासाठी apnipathshala.ai/teacher उघडा आणि Google ने साइन इन करा.',
    shell_wa_msg: "{title}: तुमच्या वर्गासाठी मोफत लाइव्ह क्विझ. विद्यार्थी फोनवर कोड आणि टोपणनावाने सामील होतात, साइन-अप नाही; शिक्षक Google ने साइन इन करतात. जाहिराती नाहीत, 12 भारतीय भाषांमध्ये. इथे उघडा: {url}",
    demo_teacher: 'डेमो शिक्षक',
    signin_title: 'Google ने साइन इन करा — शिक्षकांसाठी मोफत',
    signin_text: 'तुमच्या क्विझ ऑनलाइन सेव्ह होतात, त्यामुळे त्या कोणत्याही कॉम्प्युटरवर वापरता येतात. विद्यार्थ्यांना कधीच साइन इन करावे लागत नाही: ते कोड आणि टोपणनावाने सामील होतात.',
    signin_google: 'Google ने साइन इन करा',
    signin_demo: 'आत्ता डेमो मोडमध्ये वापरून पाहा',
    inapp_hint: 'WhatsApp सारख्या ॲपमध्ये Google साइन-इन चालत नाही. हे पेज Chrome मध्ये उघडा.',
    use_demo: 'त्याऐवजी डेमो मोड वापरा',
    hello: 'नमस्कार, {name}',
    new_quiz: 'नवीन क्विझ',
    import_qm: 'या डिव्हाइसवरील क्विझ मेकरमधून आणा',
    import_file: 'JSON / CSV इम्पोर्ट करा',
    import_hint: 'CSV चे कॉलम: प्रश्न, पर्याय 1 ते पर्याय 6, बरोबर उत्तर (1–6 किंवा A–F), स्पष्टीकरण.',
    settings_title: 'लाइव्ह क्विझची सेटिंग्ज',
    time_per_q: 'प्रत्येक प्रश्नासाठी वेळ',
    sec: '{n} सेकंद',
    shuffle_q: 'प्रश्नांचा क्रम बदला',
    shuffle_o: 'पर्यायांचा क्रम बदला',
    my_quizzes: 'माझ्या क्विझ',
    sample_badge: 'नमुना',
    n_questions: '{n} प्रश्न',
    host: 'लाइव्ह घ्या',
    edit_copy: 'प्रत बनवून बदला',
    no_quizzes: 'अजून तुमची स्वतःची क्विझ नाही. नवीन क्विझ बनवा, इम्पोर्ट करा किंवा नमुना क्विझ घ्या.',
    confirm_delete_quiz: '"{title}" ही क्विझ काढून टाकायची?',
    deleted: 'काढून टाकले.',
    past_sessions: 'मागील सेशन',
    no_sessions: 'अजून एकही सेशन नाही. एखादी क्विझ घ्या, तिचे निकाल इथे दिसतील.',
    keep_note: 'निकाल 30 दिवसांनी पुसले जातात. ठेवायचे असल्यास CSV डाउनलोड करा.',
    players_n: '{n} खेळाडू',
    code_n: 'कोड {code}',
    state_lobby: 'प्रतीक्षेत',
    state_live: 'चालू',
    state_ended: 'संपले',
    results: 'निकाल',
    resume: 'पुन्हा सुरू करा',
    confirm_delete_session: 'हे सेशन त्याच्या सर्व उत्तरांसह काढून टाकायचे?',
    account: 'तुमचे खाते',
    sign_out: 'साइन आउट',
    delete_account: 'माझे अकाउंट आणि डेटा पुसा',
    delete_account_text: 'यामुळे तुमचे शिक्षक खाते, तुमच्या सर्व क्विझ आणि सेशन, आणि त्यातील विद्यार्थ्यांची सर्व टोपणनावे व उत्तरे पुसली जातील. हे परत आणता येणार नाही.',
    delete_account_tip: 'हे करण्यापूर्वी जे निकाल ठेवायचे आहेत त्यांची CSV डाउनलोड करा.',
    delete_account_check: 'मला समजले. सर्व काही काढून टाका.',
    delete_forever: 'कायमचे काढून टाका',
    account_deleted: 'तुमचे खाते आणि त्याचा सर्व डेटा काढून टाकला.',
    privacy: 'गोपनीयता धोरण',
    terms: 'वापराच्या अटी',
    data_cloud: 'तुमच्या क्विझ आणि निकाल Google Firebase (मुंबई) मध्ये ठेवले जातात. विद्यार्थी फक्त टोपणनाव देतात.',
    data_demo: 'डेमो मोडमध्ये सर्व काही याच ब्राउझरमध्ये राहते.',
    edit_quiz: 'क्विझ बदला',
    quiz_title: 'क्विझचे नाव',
    question_n: 'प्रश्न {n}',
    option_n: 'पर्याय {n}',
    tick_correct: 'बरोबर उत्तरावर टिक करा.',
    mark_correct: 'पर्याय {n} हे बरोबर उत्तर आहे',
    add_option: 'पर्याय जोडा',
    remove_option: 'पर्याय {n} काढा',
    explain_label: 'स्पष्टीकरण (ऐच्छिक, उत्तरानंतर दिसेल)',
    time_label: 'वेळ सेकंदात (ऐच्छिक)',
    time_ph: 'डीफॉल्ट',
    add_question: 'प्रश्न जोडा',
    move_up: 'प्रश्न {n} वर हलवा',
    move_down: 'प्रश्न {n} खाली हलवा',
    delete_question: 'प्रश्न {n} काढून टाका',
    save_quiz: 'क्विझ सेव्ह करा',
    saved: 'सेव्ह झाले.',
    err_title: 'कृपया क्विझचे नाव लिहा.',
    err_no_questions: 'किमान एक प्रश्न जोडा.',
    err_q_text: 'प्रश्न {n}: कृपया प्रश्न लिहा.',
    err_q_options: 'प्रश्न {n}: किमान 2 पर्याय लिहा.',
    err_q_correct: 'प्रश्न {n}: बरोबर उत्तरावर टिक करा.',
    draft_restored: 'तुमचे सेव्ह न केलेले बदल परत आणले.',
    confirm_discard: 'तुमचे बदल सोडून द्यायचे?',
    untitled: 'नाव नसलेली क्विझ',
    opt_true: 'बरोबर',
    opt_false: 'चूक',
    qm_title: 'क्विझ मेकरमध्ये सेव्ह केलेल्या क्विझ',
    qm_none: 'या डिव्हाइसवर क्विझ मेकरची एकही क्विझ सापडली नाही.',
    open_qm: 'क्विझ मेकर उघडा',
    import_selected: 'निवडलेल्या इम्पोर्ट करा',
    imported_n: '{n} क्विझ इम्पोर्ट झाल्या.',
    skipped_n: '{n} प्रश्न सोडून दिले.',
    import_failed: 'ही फाइल वाचता आली नाही. क्विझ मेकरची JSON किंवा CSV फाइल वापरा.',
    join_line: '{url} वर जा आणि हा कोड टाका:',
    scan_qr: 'किंवा हा QR कोड स्कॅन करा',
    qr_offline: 'QR कोडसाठी इंटरनेट लागते. विद्यार्थी कोड टाइप करू शकतात.',
    waiting_players: 'विद्यार्थी सामील होण्याची वाट पाहत आहोत…',
    joined_n: '{n} सामील झाले',
    lock: 'लॉक करा',
    unlock: 'अनलॉक करा',
    locked_note: 'लॉक आहे: आता नवीन कोणी सामील होऊ शकत नाही.',
    kick: '{name} ला काढा',
    confirm_kick: '{name} ला या क्विझमधून काढायचे? ते पुन्हा सामील होऊ शकणार नाहीत.',
    start_quiz: 'क्विझ सुरू करा',
    need_player: 'आधी किमान एका विद्यार्थ्याने सामील व्हायला हवे.',
    open_student: 'विद्यार्थ्याचा टॅब उघडा',
    question_of: 'प्रश्न {n} / {total}',
    answered_n: '{total} पैकी {n} जणांनी उत्तर दिले',
    show_answer: 'उत्तर दाखवा',
    skip_q: 'प्रश्न वगळा',
    time_up: 'वेळ संपली!',
    all_answered: 'सर्वांनी उत्तर दिले!',
    leaderboard: 'लीडरबोर्ड',
    next_question: 'पुढचा प्रश्न',
    final_results: 'अंतिम निकाल',
    end_quiz: 'क्विझ संपवा',
    confirm_end: 'क्विझ आत्ताच संपवून अंतिम निकाल दाखवायचे?',
    correct_answer: 'बरोबर उत्तर',
    points_n: '{n} गुण',
    col_rank: 'क्रमांक',
    col_nick: 'टोपणनाव',
    col_correct: 'बरोबर उत्तरे',
    col_q: 'प्र{n}',
    col_question: 'प्रश्न',
    export_csv: 'CSV एक्सपोर्ट करा',
    host_again: 'पुन्हा घ्या',
    back_dash: 'माझ्या क्विझकडे परत',
    session_gone: 'हे क्विझ सेशन आता अस्तित्वात नाही.',
    nobody_joined: 'या क्विझमध्ये कोणीही सामील झाले नाही.',
    keys_hint: 'कीबोर्ड: पुढे जाण्यासाठी Space किंवा →',
    offline_banner: 'इंटरनेट कनेक्शन नाही. विद्यार्थ्यांची उत्तरे कदाचित पोहोचणार नाहीत.',
    connecting: 'जोडत आहे…',
    err_not_configured: 'ऑनलाइन क्विझ अजून सुरू झालेली नाही. डेमो मोड वापरून पाहा.',
    err_offline: 'इंटरनेट नाही. कनेक्शन तपासून पुन्हा प्रयत्न करा.',
    err_quota_exceeded: 'आजची मोफत मर्यादा संपली. कृपया उद्या पुन्हा प्रयत्न करा, किंवा डेमो मोड वापरा.',
    err_not_found: 'सापडले नाही. कदाचित ते काढून टाकले असेल.',
    err_permission_denied: 'हे करण्याची तुम्हाला परवानगी नाही. कृपया पुन्हा साइन इन करा.',
    err_session_locked: 'ही क्विझ लॉक आहे.',
    err_session_ended: 'ही क्विझ संपली आहे.',
    err_name_taken: 'हे टोपणनाव दुसरे कोणी वापरत आहे.',
    err_invalid_input: 'कृपया तुम्ही लिहिलेले तपासा.',
    err_unknown: 'काहीतरी चुकले. कृपया पुन्हा प्रयत्न करा.',
    help_title: 'कसे वापरायचे · वर्गासाठी कल्पना',
    help_1: 'साइन इन करा आणि नमुना क्विझवर "लाइव्ह घ्या" दाबा, 10 सेकंदात कळेल हे कसे चालते.',
    help_2: 'स्क्रीन प्रोजेक्टरवर दाखवा. विद्यार्थी फोनवर apnipathshala.ai/join उघडून कोड आणि टोपणनाव टाकतात.',
    help_3: 'विद्यार्थ्यांना पूर्ण नाव नाही, टोपणनाव लिहायला सांगा. ✕ ने कोणालाही काढता येते, आणि सगळे आले की लॉक दाबा.',
    help_4: 'बरोबर उत्तराला 500 ते 1000 गुण: जितके लवकर, तितके जास्त. चुकीच्या उत्तराला 0.',
    help_5: 'वर्गासाठी कल्पना: धडा संपल्यावर 3-3 जणांचे गट एका फोनवर चर्चा करून उत्तर देऊ द्या.',
    help_6: 'क्विझ मेकरमध्ये क्विझ बनवून इथे इम्पोर्ट करा, किंवा नवीन क्विझ लिहा. नोंदीसाठी निकाल CSV मध्ये एक्सपोर्ट करा.'
  },
  gu: {
    app_title: 'લાઇવ ક્લાસ ક્વિઝ',
    intro: 'પ્રોજેક્ટર પર લાઇવ ક્વિઝ ચલાવો. ઑનલાઇન ચલાવવા Google થી સાઇન ઇન કરો. વિદ્યાર્થીઓ ફોન પર કોડ અને ઉપનામ નાખીને જોડાય છે (સાઇન-અપ નહીં), દરેક પ્રશ્નનો જવાબ આપે છે અને જુએ છે કે કોણ સૌથી આગળ છે.',
    demo_banner: 'ડેમો મોડ: આ ફક્ત આ એક જ ડિવાઇસ પર ચાલે છે. અજમાવવા માટે વિદ્યાર્થીઓનું પેજ બીજા ટૅબમાં ખોલો. વિદ્યાર્થીઓના ફોન પર રમવા માટે apnipathshala.ai/teacher ખોલો અને Google થી સાઇન ઇન કરો.',
    shell_wa_msg: "{title}: તમારા વર્ગ માટે મફત લાઇવ ક્વિઝ. વિદ્યાર્થીઓ ફોન પર કોડ અને ઉપનામથી જોડાય છે, સાઇન-અપ નહીં; શિક્ષક Google થી સાઇન ઇન કરે છે. જાહેરાત નહીં, 12 ભારતીય ભાષાઓમાં. અહીં ખોલો: {url}",
    demo_teacher: 'ડેમો શિક્ષક',
    signin_title: 'Google થી સાઇન ઇન કરો — શિક્ષકો માટે મફત',
    signin_text: 'તમારી ક્વિઝ ઑનલાઇન સેવ થાય છે, એટલે તમે તેને કોઈ પણ કમ્પ્યુટર પર વાપરી શકો. વિદ્યાર્થીઓએ ક્યારેય સાઇન ઇન કરવું પડતું નથી: તેઓ કોડ અને ઉપનામથી જોડાય છે.',
    signin_google: 'Google થી સાઇન ઇન કરો',
    signin_demo: 'હમણાં ડેમો મોડમાં અજમાવો',
    inapp_hint: 'WhatsApp જેવી ઍપની અંદર Google સાઇન-ઇન ચાલતું નથી. આ પેજ Chrome માં ખોલો.',
    use_demo: 'તેના બદલે ડેમો મોડ વાપરો',
    hello: 'નમસ્તે, {name}',
    new_quiz: 'નવી ક્વિઝ',
    import_qm: 'આ ડિવાઇસના ક્વિઝ મેકરમાંથી લાવો',
    import_file: 'JSON / CSV ઇમ્પોર્ટ કરો',
    import_hint: 'CSV ના કૉલમ: પ્રશ્ન, વિકલ્પ 1 થી વિકલ્પ 6, સાચો જવાબ (1–6 અથવા A–F), સમજૂતી.',
    settings_title: 'લાઇવ ક્વિઝનાં સેટિંગ્સ',
    time_per_q: 'દરેક પ્રશ્ન માટે સમય',
    sec: '{n} સેકન્ડ',
    shuffle_q: 'પ્રશ્નોનો ક્રમ બદલો',
    shuffle_o: 'વિકલ્પોનો ક્રમ બદલો',
    my_quizzes: 'મારી ક્વિઝ',
    sample_badge: 'નમૂનો',
    n_questions: '{n} પ્રશ્ન',
    host: 'લાઇવ ચલાવો',
    edit_copy: 'નકલ બનાવીને બદલો',
    no_quizzes: 'હજી તમારી પોતાની કોઈ ક્વિઝ નથી. નવી ક્વિઝ બનાવો, ઇમ્પોર્ટ કરો અથવા નમૂના ક્વિઝ ચલાવો.',
    confirm_delete_quiz: '"{title}" ક્વિઝ કાઢી નાખવી છે?',
    deleted: 'કાઢી નાખ્યું.',
    past_sessions: 'અગાઉનાં સેશન',
    no_sessions: 'હજી કોઈ સેશન નથી. કોઈ ક્વિઝ ચલાવો, તેનાં પરિણામ અહીં દેખાશે.',
    keep_note: 'પરિણામ 30 દિવસ પછી ભૂંસાઈ જાય છે. રાખવા માટે CSV ડાઉનલોડ કરી લો.',
    players_n: '{n} ખેલાડી',
    code_n: 'કોડ {code}',
    state_lobby: 'રાહ જોઈ રહ્યા છે',
    state_live: 'ચાલુ',
    state_ended: 'પૂરું',
    results: 'પરિણામ',
    resume: 'ફરી ચાલુ કરો',
    confirm_delete_session: 'આ સેશન તેના બધા જવાબો સાથે કાઢી નાખવું છે?',
    account: 'તમારું એકાઉન્ટ',
    sign_out: 'સાઇન આઉટ',
    delete_account: 'મારું એકાઉન્ટ અને ડેટા ભૂંસો',
    delete_account_text: 'આનાથી તમારું શિક્ષક એકાઉન્ટ, તમારી બધી ક્વિઝ અને સેશન, અને તેમાંના વિદ્યાર્થીઓનાં બધાં ઉપનામ અને જવાબ ભૂંસાઈ જશે. તેને પાછું લાવી શકાશે નહીં.',
    delete_account_tip: 'આ કરતાં પહેલાં જે પરિણામ રાખવાં હોય તેની CSV ડાઉનલોડ કરી લો.',
    delete_account_check: 'હું સમજું છું. બધું કાઢી નાખો.',
    delete_forever: 'કાયમ માટે કાઢી નાખો',
    account_deleted: 'તમારું એકાઉન્ટ અને તેનો બધો ડેટા કાઢી નાખવામાં આવ્યો.',
    privacy: 'ગોપનીયતા નીતિ',
    terms: 'ઉપયોગની શરતો',
    data_cloud: 'તમારી ક્વિઝ અને પરિણામ Google Firebase (મુંબઈ) માં રાખવામાં આવે છે. વિદ્યાર્થીઓ ફક્ત ઉપનામ આપે છે.',
    data_demo: 'ડેમો મોડમાં બધું આ જ બ્રાઉઝરમાં રહે છે.',
    edit_quiz: 'ક્વિઝમાં ફેરફાર',
    quiz_title: 'ક્વિઝનું નામ',
    question_n: 'પ્રશ્ન {n}',
    option_n: 'વિકલ્પ {n}',
    tick_correct: 'સાચા જવાબ પર ટિક કરો.',
    mark_correct: 'વિકલ્પ {n} સાચો જવાબ છે',
    add_option: 'વિકલ્પ ઉમેરો',
    remove_option: 'વિકલ્પ {n} કાઢો',
    explain_label: 'સમજૂતી (જરૂરી નથી, જવાબ પછી દેખાશે)',
    time_label: 'સમય સેકન્ડમાં (જરૂરી નથી)',
    time_ph: 'ડિફૉલ્ટ',
    add_question: 'પ્રશ્ન ઉમેરો',
    move_up: 'પ્રશ્ન {n} ઉપર ખસેડો',
    move_down: 'પ્રશ્ન {n} નીચે ખસેડો',
    delete_question: 'પ્રશ્ન {n} કાઢી નાખો',
    save_quiz: 'ક્વિઝ સેવ કરો',
    saved: 'સેવ થયું.',
    err_title: 'કૃપા કરીને ક્વિઝનું નામ લખો.',
    err_no_questions: 'ઓછામાં ઓછો એક પ્રશ્ન ઉમેરો.',
    err_q_text: 'પ્રશ્ન {n}: કૃપા કરીને પ્રશ્ન લખો.',
    err_q_options: 'પ્રશ્ન {n}: ઓછામાં ઓછા 2 વિકલ્પ લખો.',
    err_q_correct: 'પ્રશ્ન {n}: સાચા જવાબ પર ટિક કરો.',
    draft_restored: 'તમારા સેવ ન થયેલા ફેરફારો પાછા લાવ્યા.',
    confirm_discard: 'તમારા ફેરફારો છોડી દેવા છે?',
    untitled: 'નામ વગરની ક્વિઝ',
    opt_true: 'સાચું',
    opt_false: 'ખોટું',
    qm_title: 'ક્વિઝ મેકરમાં સેવ કરેલી ક્વિઝ',
    qm_none: 'આ ડિવાઇસ પર ક્વિઝ મેકરની કોઈ ક્વિઝ મળી નથી.',
    open_qm: 'ક્વિઝ મેકર ખોલો',
    import_selected: 'પસંદ કરેલી ઇમ્પોર્ટ કરો',
    imported_n: '{n} ક્વિઝ ઇમ્પોર્ટ થઈ.',
    skipped_n: '{n} પ્રશ્ન છોડી દેવાયા.',
    import_failed: 'આ ફાઇલ વાંચી શકાઈ નહીં. ક્વિઝ મેકરની JSON અથવા CSV ફાઇલ વાપરો.',
    join_line: '{url} પર જાઓ અને આ કોડ નાખો:',
    scan_qr: 'અથવા આ QR કોડ સ્કૅન કરો',
    qr_offline: 'QR કોડ માટે ઇન્ટરનેટ જોઈએ. વિદ્યાર્થીઓ કોડ ટાઇપ કરી શકે છે.',
    waiting_players: 'વિદ્યાર્થીઓ જોડાય તેની રાહ…',
    joined_n: '{n} જોડાયા',
    lock: 'લૉક કરો',
    unlock: 'અનલૉક કરો',
    locked_note: 'લૉક છે: હવે કોઈ નવું જોડાઈ શકશે નહીં.',
    kick: '{name} ને કાઢો',
    confirm_kick: '{name} ને આ ક્વિઝમાંથી કાઢવા છે? તેઓ ફરી જોડાઈ શકશે નહીં.',
    start_quiz: 'ક્વિઝ શરૂ કરો',
    need_player: 'પહેલાં ઓછામાં ઓછા એક વિદ્યાર્થીએ જોડાવું પડશે.',
    open_student: 'વિદ્યાર્થીનું ટૅબ ખોલો',
    question_of: 'પ્રશ્ન {n} / {total}',
    answered_n: '{total} માંથી {n} એ જવાબ આપ્યો',
    show_answer: 'જવાબ બતાવો',
    skip_q: 'પ્રશ્ન છોડો',
    time_up: 'સમય પૂરો!',
    all_answered: 'બધાએ જવાબ આપી દીધો!',
    leaderboard: 'લીડરબોર્ડ',
    next_question: 'આગળનો પ્રશ્ન',
    final_results: 'અંતિમ પરિણામ',
    end_quiz: 'ક્વિઝ પૂરી કરો',
    confirm_end: 'ક્વિઝ હમણાં પૂરી કરીને અંતિમ પરિણામ બતાવવાં છે?',
    correct_answer: 'સાચો જવાબ',
    points_n: '{n} પૉઇન્ટ',
    col_rank: 'ક્રમ',
    col_nick: 'ઉપનામ',
    col_correct: 'સાચા જવાબ',
    col_q: 'પ્ર{n}',
    col_question: 'પ્રશ્ન',
    export_csv: 'CSV એક્સપોર્ટ કરો',
    host_again: 'ફરી ચલાવો',
    back_dash: 'મારી ક્વિઝ પર પાછા',
    session_gone: 'આ ક્વિઝ સેશન હવે અસ્તિત્વમાં નથી.',
    nobody_joined: 'આ ક્વિઝમાં કોઈ જોડાયું નહીં.',
    keys_hint: 'કીબોર્ડ: આગળ જવા Space અથવા →',
    offline_banner: 'ઇન્ટરનેટ કનેક્શન નથી. વિદ્યાર્થીઓના જવાબ કદાચ નહીં પહોંચે.',
    connecting: 'જોડાઈ રહ્યું છે…',
    err_not_configured: 'ઑનલાઇન ક્વિઝ હજી સેટ થઈ નથી. ડેમો મોડ અજમાવો.',
    err_offline: 'ઇન્ટરનેટ નથી. કનેક્શન તપાસીને ફરી પ્રયાસ કરો.',
    err_quota_exceeded: 'આજની મફત મર્યાદા પૂરી થઈ ગઈ. કૃપા કરીને કાલે ફરી પ્રયાસ કરો, અથવા ડેમો મોડ વાપરો.',
    err_not_found: 'મળ્યું નહીં. કદાચ તે કાઢી નખાયું છે.',
    err_permission_denied: 'તમને આ કરવાની પરવાનગી નથી. કૃપા કરીને ફરી સાઇન ઇન કરો.',
    err_session_locked: 'આ ક્વિઝ લૉક છે.',
    err_session_ended: 'આ ક્વિઝ પૂરી થઈ ગઈ છે.',
    err_name_taken: 'આ ઉપનામ બીજું કોઈ વાપરે છે.',
    err_invalid_input: 'કૃપા કરીને તમે લખેલું તપાસો.',
    err_unknown: 'કંઈક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો.',
    help_title: 'કેવી રીતે વાપરવું · વર્ગ માટે વિચારો',
    help_1: 'સાઇન ઇન કરો અને નમૂના ક્વિઝ પર "લાઇવ ચલાવો" દબાવો, 10 સેકન્ડમાં સમજાઈ જશે કે તે કેવી રીતે ચાલે છે.',
    help_2: 'સ્ક્રીન પ્રોજેક્ટર પર બતાવો. વિદ્યાર્થીઓ ફોન પર apnipathshala.ai/join ખોલીને કોડ અને ઉપનામ નાખે છે.',
    help_3: 'વિદ્યાર્થીઓને પૂરું નામ નહીં, ઉપનામ લખવા કહો. ✕ થી કોઈને પણ કાઢી શકો, અને બધા આવી જાય એટલે લૉક દબાવો.',
    help_4: 'સાચા જવાબ પર 500 થી 1000 પૉઇન્ટ: જેટલું ઝડપી, એટલા વધુ. ખોટા જવાબ પર 0.',
    help_5: 'વર્ગ માટે વિચાર: પ્રકરણના અંતે 3-3 ના જૂથ એક ફોન પર ચર્ચા કરીને જવાબ આપે.',
    help_6: 'ક્વિઝ મેકરમાં ક્વિઝ બનાવીને અહીં ઇમ્પોર્ટ કરો, અથવા નવી ક્વિઝ લખો. રેકૉર્ડ માટે પરિણામ CSV માં એક્સપોર્ટ કરો.'
  },
  pa: {
    app_title: 'ਲਾਈਵ ਕਲਾਸ ਕੁਇਜ਼',
    intro: 'ਪ੍ਰੋਜੈਕਟਰ ਉੱਤੇ ਲਾਈਵ ਕੁਇਜ਼ ਚਲਾਓ। ਔਨਲਾਈਨ ਚਲਾਉਣ ਲਈ Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ। ਵਿਦਿਆਰਥੀ ਫ਼ੋਨ ਉੱਤੇ ਕੋਡ ਅਤੇ ਉਪਨਾਮ ਪਾ ਕੇ ਜੁੜਦੇ ਹਨ (ਕੋਈ ਸਾਈਨ-ਅੱਪ ਨਹੀਂ), ਹਰ ਸਵਾਲ ਦਾ ਜਵਾਬ ਦਿੰਦੇ ਹਨ ਅਤੇ ਦੇਖਦੇ ਹਨ ਕਿ ਕੌਣ ਸਭ ਤੋਂ ਅੱਗੇ ਹੈ।',
    demo_banner: 'ਡੈਮੋ ਮੋਡ: ਇਹ ਸਿਰਫ਼ ਇਸੇ ਇੱਕ ਡਿਵਾਈਸ ਉੱਤੇ ਚੱਲਦਾ ਹੈ। ਅਜ਼ਮਾਉਣ ਲਈ ਵਿਦਿਆਰਥੀਆਂ ਵਾਲਾ ਪੰਨਾ ਦੂਜੇ ਟੈਬ ਵਿੱਚ ਖੋਲ੍ਹੋ। ਵਿਦਿਆਰਥੀਆਂ ਦੇ ਫ਼ੋਨਾਂ ਉੱਤੇ ਖੇਡਣ ਲਈ apnipathshala.ai/teacher ਖੋਲ੍ਹੋ ਅਤੇ Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ।',
    shell_wa_msg: "{title}: ਤੁਹਾਡੀ ਕਲਾਸ ਲਈ ਮੁਫ਼ਤ ਲਾਈਵ ਕੁਇਜ਼। ਵਿਦਿਆਰਥੀ ਫ਼ੋਨ ਉੱਤੇ ਕੋਡ ਅਤੇ ਉਪਨਾਮ ਨਾਲ ਜੁੜਦੇ ਹਨ, ਕੋਈ ਸਾਈਨ-ਅੱਪ ਨਹੀਂ; ਅਧਿਆਪਕ Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰਦੇ ਹਨ। ਨਾ ਇਸ਼ਤਿਹਾਰ, 12 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ। ਇੱਥੇ ਖੋਲ੍ਹੋ: {url}",
    demo_teacher: 'ਡੈਮੋ ਅਧਿਆਪਕ',
    signin_title: 'Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ — ਅਧਿਆਪਕਾਂ ਲਈ ਮੁਫ਼ਤ',
    signin_text: 'ਤੁਹਾਡੇ ਕੁਇਜ਼ ਔਨਲਾਈਨ ਸੇਵ ਹੁੰਦੇ ਹਨ, ਇਸ ਲਈ ਤੁਸੀਂ ਉਨ੍ਹਾਂ ਨੂੰ ਕਿਸੇ ਵੀ ਕੰਪਿਊਟਰ ਉੱਤੇ ਵਰਤ ਸਕਦੇ ਹੋ। ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਕਦੇ ਸਾਈਨ ਇਨ ਨਹੀਂ ਕਰਨਾ ਪੈਂਦਾ: ਉਹ ਕੋਡ ਅਤੇ ਉਪਨਾਮ ਨਾਲ ਜੁੜਦੇ ਹਨ।',
    signin_google: 'Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    signin_demo: 'ਹੁਣੇ ਡੈਮੋ ਮੋਡ ਵਿੱਚ ਅਜ਼ਮਾਓ',
    inapp_hint: 'WhatsApp ਵਰਗੀਆਂ ਐਪਾਂ ਦੇ ਅੰਦਰ Google ਸਾਈਨ-ਇਨ ਨਹੀਂ ਚੱਲਦਾ। ਇਹ ਪੰਨਾ Chrome ਵਿੱਚ ਖੋਲ੍ਹੋ।',
    use_demo: 'ਇਸ ਦੀ ਥਾਂ ਡੈਮੋ ਮੋਡ ਵਰਤੋ',
    hello: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, {name}',
    new_quiz: 'ਨਵਾਂ ਕੁਇਜ਼',
    import_qm: 'ਇਸ ਡਿਵਾਈਸ ਦੇ ਕੁਇਜ਼ ਮੇਕਰ ਤੋਂ ਲਿਆਓ',
    import_file: 'JSON / CSV ਇੰਪੋਰਟ ਕਰੋ',
    import_hint: 'CSV ਦੇ ਕਾਲਮ: ਸਵਾਲ, ਵਿਕਲਪ 1 ਤੋਂ ਵਿਕਲਪ 6, ਸਹੀ ਜਵਾਬ (1–6 ਜਾਂ A–F), ਵਿਆਖਿਆ।',
    settings_title: 'ਲਾਈਵ ਕੁਇਜ਼ ਦੀਆਂ ਸੈਟਿੰਗਾਂ',
    time_per_q: 'ਹਰ ਸਵਾਲ ਲਈ ਸਮਾਂ',
    sec: '{n} ਸਕਿੰਟ',
    shuffle_q: 'ਸਵਾਲਾਂ ਦਾ ਕ੍ਰਮ ਬਦਲੋ',
    shuffle_o: 'ਵਿਕਲਪਾਂ ਦਾ ਕ੍ਰਮ ਬਦਲੋ',
    my_quizzes: 'ਮੇਰੇ ਕੁਇਜ਼',
    sample_badge: 'ਨਮੂਨਾ',
    n_questions: '{n} ਸਵਾਲ',
    host: 'ਲਾਈਵ ਚਲਾਓ',
    edit_copy: 'ਕਾਪੀ ਬਣਾ ਕੇ ਬਦਲੋ',
    no_quizzes: 'ਅਜੇ ਤੁਹਾਡਾ ਆਪਣਾ ਕੋਈ ਕੁਇਜ਼ ਨਹੀਂ ਹੈ। ਨਵਾਂ ਕੁਇਜ਼ ਬਣਾਓ, ਇੰਪੋਰਟ ਕਰੋ ਜਾਂ ਨਮੂਨਾ ਕੁਇਜ਼ ਚਲਾਓ।',
    confirm_delete_quiz: 'ਕੁਇਜ਼ "{title}" ਮਿਟਾਉਣਾ ਹੈ?',
    deleted: 'ਮਿਟਾ ਦਿੱਤਾ।',
    past_sessions: 'ਪਿਛਲੇ ਸੈਸ਼ਨ',
    no_sessions: 'ਅਜੇ ਕੋਈ ਸੈਸ਼ਨ ਨਹੀਂ। ਕੋਈ ਕੁਇਜ਼ ਚਲਾਓ, ਉਸ ਦੇ ਨਤੀਜੇ ਇੱਥੇ ਦਿਸਣਗੇ।',
    keep_note: 'ਨਤੀਜੇ 30 ਦਿਨਾਂ ਬਾਅਦ ਮਿਟ ਜਾਂਦੇ ਹਨ। ਰੱਖਣ ਲਈ CSV ਡਾਊਨਲੋਡ ਕਰ ਲਓ।',
    players_n: '{n} ਖਿਡਾਰੀ',
    code_n: 'ਕੋਡ {code}',
    state_lobby: 'ਉਡੀਕ ਵਿੱਚ',
    state_live: 'ਚੱਲ ਰਿਹਾ ਹੈ',
    state_ended: 'ਖ਼ਤਮ',
    results: 'ਨਤੀਜੇ',
    resume: 'ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ',
    confirm_delete_session: 'ਇਹ ਸੈਸ਼ਨ ਇਸ ਦੇ ਸਾਰੇ ਜਵਾਬਾਂ ਸਮੇਤ ਮਿਟਾਉਣਾ ਹੈ?',
    account: 'ਤੁਹਾਡਾ ਖਾਤਾ',
    sign_out: 'ਸਾਈਨ ਆਊਟ',
    delete_account: 'ਮੇਰਾ ਖਾਤਾ ਅਤੇ ਡੇਟਾ ਮਿਟਾਓ',
    delete_account_text: 'ਇਸ ਨਾਲ ਤੁਹਾਡਾ ਅਧਿਆਪਕ ਖਾਤਾ, ਤੁਹਾਡੇ ਸਾਰੇ ਕੁਇਜ਼ ਅਤੇ ਸੈਸ਼ਨ, ਅਤੇ ਉਨ੍ਹਾਂ ਵਿੱਚ ਵਿਦਿਆਰਥੀਆਂ ਦੇ ਸਾਰੇ ਉਪਨਾਮ ਅਤੇ ਜਵਾਬ ਮਿਟ ਜਾਣਗੇ। ਇਸ ਨੂੰ ਵਾਪਸ ਨਹੀਂ ਲਿਆਂਦਾ ਜਾ ਸਕਦਾ।',
    delete_account_tip: 'ਇਹ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਜੋ ਨਤੀਜੇ ਰੱਖਣੇ ਹਨ, ਉਨ੍ਹਾਂ ਦੀ CSV ਡਾਊਨਲੋਡ ਕਰ ਲਓ।',
    delete_account_check: 'ਮੈਂ ਸਮਝਦਾ/ਸਮਝਦੀ ਹਾਂ। ਸਭ ਕੁਝ ਮਿਟਾ ਦਿਓ।',
    delete_forever: 'ਹਮੇਸ਼ਾ ਲਈ ਮਿਟਾਓ',
    account_deleted: 'ਤੁਹਾਡਾ ਖਾਤਾ ਅਤੇ ਉਸ ਦਾ ਸਾਰਾ ਡਾਟਾ ਮਿਟਾ ਦਿੱਤਾ ਗਿਆ।',
    privacy: 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ',
    terms: 'ਵਰਤੋਂ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    data_cloud: 'ਤੁਹਾਡੇ ਕੁਇਜ਼ ਅਤੇ ਨਤੀਜੇ Google Firebase (ਮੁੰਬਈ) ਵਿੱਚ ਰੱਖੇ ਜਾਂਦੇ ਹਨ। ਵਿਦਿਆਰਥੀ ਸਿਰਫ਼ ਉਪਨਾਮ ਦਿੰਦੇ ਹਨ।',
    data_demo: 'ਡੈਮੋ ਮੋਡ ਵਿੱਚ ਸਭ ਕੁਝ ਇਸੇ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ।',
    edit_quiz: 'ਕੁਇਜ਼ ਬਦਲੋ',
    quiz_title: 'ਕੁਇਜ਼ ਦਾ ਨਾਂ',
    question_n: 'ਸਵਾਲ {n}',
    option_n: 'ਵਿਕਲਪ {n}',
    tick_correct: 'ਸਹੀ ਜਵਾਬ ਉੱਤੇ ਟਿੱਕ ਕਰੋ।',
    mark_correct: 'ਵਿਕਲਪ {n} ਸਹੀ ਜਵਾਬ ਹੈ',
    add_option: 'ਵਿਕਲਪ ਜੋੜੋ',
    remove_option: 'ਵਿਕਲਪ {n} ਹਟਾਓ',
    explain_label: 'ਵਿਆਖਿਆ (ਲਾਜ਼ਮੀ ਨਹੀਂ, ਜਵਾਬ ਤੋਂ ਬਾਅਦ ਦਿਸੇਗੀ)',
    time_label: 'ਸਮਾਂ ਸਕਿੰਟਾਂ ਵਿੱਚ (ਲਾਜ਼ਮੀ ਨਹੀਂ)',
    time_ph: 'ਡਿਫ਼ਾਲਟ',
    add_question: 'ਸਵਾਲ ਜੋੜੋ',
    move_up: 'ਸਵਾਲ {n} ਉੱਪਰ ਕਰੋ',
    move_down: 'ਸਵਾਲ {n} ਹੇਠਾਂ ਕਰੋ',
    delete_question: 'ਸਵਾਲ {n} ਮਿਟਾਓ',
    save_quiz: 'ਕੁਇਜ਼ ਸੇਵ ਕਰੋ',
    saved: 'ਸੇਵ ਹੋ ਗਿਆ।',
    err_title: 'ਕਿਰਪਾ ਕਰਕੇ ਕੁਇਜ਼ ਦਾ ਨਾਂ ਲਿਖੋ।',
    err_no_questions: 'ਘੱਟੋ-ਘੱਟ ਇੱਕ ਸਵਾਲ ਜੋੜੋ।',
    err_q_text: 'ਸਵਾਲ {n}: ਕਿਰਪਾ ਕਰਕੇ ਸਵਾਲ ਲਿਖੋ।',
    err_q_options: 'ਸਵਾਲ {n}: ਘੱਟੋ-ਘੱਟ 2 ਵਿਕਲਪ ਲਿਖੋ।',
    err_q_correct: 'ਸਵਾਲ {n}: ਸਹੀ ਜਵਾਬ ਉੱਤੇ ਟਿੱਕ ਕਰੋ।',
    draft_restored: 'ਤੁਹਾਡੀਆਂ ਬਿਨਾਂ ਸੇਵ ਕੀਤੀਆਂ ਤਬਦੀਲੀਆਂ ਵਾਪਸ ਆ ਗਈਆਂ।',
    confirm_discard: 'ਆਪਣੀਆਂ ਤਬਦੀਲੀਆਂ ਛੱਡ ਦੇਣੀਆਂ ਹਨ?',
    untitled: 'ਬਿਨਾਂ ਨਾਂ ਦਾ ਕੁਇਜ਼',
    opt_true: 'ਸਹੀ',
    opt_false: 'ਗਲਤ',
    qm_title: 'ਕੁਇਜ਼ ਮੇਕਰ ਵਿੱਚ ਸੇਵ ਕੁਇਜ਼',
    qm_none: 'ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਕੁਇਜ਼ ਮੇਕਰ ਦਾ ਕੋਈ ਕੁਇਜ਼ ਨਹੀਂ ਮਿਲਿਆ।',
    open_qm: 'ਕੁਇਜ਼ ਮੇਕਰ ਖੋਲ੍ਹੋ',
    import_selected: 'ਚੁਣੇ ਹੋਏ ਇੰਪੋਰਟ ਕਰੋ',
    imported_n: '{n} ਕੁਇਜ਼ ਇੰਪੋਰਟ ਹੋ ਗਏ।',
    skipped_n: '{n} ਸਵਾਲ ਛੱਡ ਦਿੱਤੇ ਗਏ।',
    import_failed: 'ਇਹ ਫ਼ਾਈਲ ਪੜ੍ਹੀ ਨਹੀਂ ਜਾ ਸਕੀ। ਕੁਇਜ਼ ਮੇਕਰ ਦੀ JSON ਜਾਂ CSV ਫ਼ਾਈਲ ਵਰਤੋ।',
    join_line: '{url} ਉੱਤੇ ਜਾਓ ਅਤੇ ਇਹ ਕੋਡ ਪਾਓ:',
    scan_qr: 'ਜਾਂ ਇਹ QR ਕੋਡ ਸਕੈਨ ਕਰੋ',
    qr_offline: 'QR ਕੋਡ ਲਈ ਇੰਟਰਨੈੱਟ ਚਾਹੀਦਾ ਹੈ। ਵਿਦਿਆਰਥੀ ਕੋਡ ਟਾਈਪ ਕਰ ਸਕਦੇ ਹਨ।',
    waiting_players: 'ਵਿਦਿਆਰਥੀਆਂ ਦੇ ਜੁੜਨ ਦੀ ਉਡੀਕ…',
    joined_n: '{n} ਜੁੜੇ',
    lock: 'ਲੌਕ ਕਰੋ',
    unlock: 'ਅਨਲੌਕ ਕਰੋ',
    locked_note: 'ਲੌਕ ਹੈ: ਹੁਣ ਕੋਈ ਨਵਾਂ ਨਹੀਂ ਜੁੜ ਸਕਦਾ।',
    kick: '{name} ਨੂੰ ਹਟਾਓ',
    confirm_kick: '{name} ਨੂੰ ਇਸ ਕੁਇਜ਼ ਵਿੱਚੋਂ ਹਟਾਉਣਾ ਹੈ? ਉਹ ਦੁਬਾਰਾ ਨਹੀਂ ਜੁੜ ਸਕਣਗੇ।',
    start_quiz: 'ਕੁਇਜ਼ ਸ਼ੁਰੂ ਕਰੋ',
    need_player: 'ਪਹਿਲਾਂ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਵਿਦਿਆਰਥੀ ਦਾ ਜੁੜਨਾ ਜ਼ਰੂਰੀ ਹੈ।',
    open_student: 'ਵਿਦਿਆਰਥੀ ਵਾਲਾ ਟੈਬ ਖੋਲ੍ਹੋ',
    question_of: 'ਸਵਾਲ {n} / {total}',
    answered_n: '{total} ਵਿੱਚੋਂ {n} ਨੇ ਜਵਾਬ ਦਿੱਤਾ',
    show_answer: 'ਜਵਾਬ ਦਿਖਾਓ',
    skip_q: 'ਸਵਾਲ ਛੱਡੋ',
    time_up: 'ਸਮਾਂ ਖ਼ਤਮ!',
    all_answered: 'ਸਭ ਨੇ ਜਵਾਬ ਦੇ ਦਿੱਤਾ!',
    leaderboard: 'ਲੀਡਰਬੋਰਡ',
    next_question: 'ਅਗਲਾ ਸਵਾਲ',
    final_results: 'ਅੰਤਿਮ ਨਤੀਜੇ',
    end_quiz: 'ਕੁਇਜ਼ ਖ਼ਤਮ ਕਰੋ',
    confirm_end: 'ਕੁਇਜ਼ ਹੁਣੇ ਖ਼ਤਮ ਕਰਕੇ ਅੰਤਿਮ ਨਤੀਜੇ ਦਿਖਾਉਣੇ ਹਨ?',
    correct_answer: 'ਸਹੀ ਜਵਾਬ',
    points_n: '{n} ਅੰਕ',
    col_rank: 'ਰੈਂਕ',
    col_nick: 'ਉਪਨਾਮ',
    col_correct: 'ਸਹੀ ਜਵਾਬ',
    col_q: 'ਸ{n}',
    col_question: 'ਸਵਾਲ',
    export_csv: 'CSV ਐਕਸਪੋਰਟ ਕਰੋ',
    host_again: 'ਦੁਬਾਰਾ ਚਲਾਓ',
    back_dash: 'ਮੇਰੇ ਕੁਇਜ਼ਾਂ ਵੱਲ ਵਾਪਸ',
    session_gone: 'ਇਹ ਕੁਇਜ਼ ਸੈਸ਼ਨ ਹੁਣ ਮੌਜੂਦ ਨਹੀਂ ਹੈ।',
    nobody_joined: 'ਇਸ ਕੁਇਜ਼ ਵਿੱਚ ਕੋਈ ਨਹੀਂ ਜੁੜਿਆ।',
    keys_hint: 'ਕੀਬੋਰਡ: ਅੱਗੇ ਲਈ Space ਜਾਂ →',
    offline_banner: 'ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਨਹੀਂ ਹੈ। ਵਿਦਿਆਰਥੀਆਂ ਦੇ ਜਵਾਬ ਸ਼ਾਇਦ ਨਾ ਪਹੁੰਚਣ।',
    connecting: 'ਜੁੜ ਰਿਹਾ ਹੈ…',
    err_not_configured: 'ਔਨਲਾਈਨ ਕੁਇਜ਼ ਅਜੇ ਸੈੱਟ ਨਹੀਂ ਹੋਇਆ। ਡੈਮੋ ਮੋਡ ਅਜ਼ਮਾਓ।',
    err_offline: 'ਇੰਟਰਨੈੱਟ ਨਹੀਂ ਹੈ। ਕਨੈਕਸ਼ਨ ਦੇਖ ਕੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    err_quota_exceeded: 'ਅੱਜ ਦੀ ਮੁਫ਼ਤ ਹੱਦ ਪੂਰੀ ਹੋ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ ਕੱਲ੍ਹ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ, ਜਾਂ ਡੈਮੋ ਮੋਡ ਵਰਤੋ।',
    err_not_found: 'ਨਹੀਂ ਮਿਲਿਆ। ਸ਼ਾਇਦ ਇਸ ਨੂੰ ਮਿਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।',
    err_permission_denied: 'ਤੁਹਾਨੂੰ ਇਹ ਕਰਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਸਾਈਨ ਇਨ ਕਰੋ।',
    err_session_locked: 'ਇਹ ਕੁਇਜ਼ ਲੌਕ ਹੈ।',
    err_session_ended: 'ਇਹ ਕੁਇਜ਼ ਖ਼ਤਮ ਹੋ ਚੁੱਕਾ ਹੈ।',
    err_name_taken: 'ਇਹ ਉਪਨਾਮ ਕੋਈ ਹੋਰ ਵਰਤ ਰਿਹਾ ਹੈ।',
    err_invalid_input: 'ਕਿਰਪਾ ਕਰਕੇ ਜੋ ਲਿਖਿਆ ਹੈ ਉਸ ਨੂੰ ਜਾਂਚ ਲਓ।',
    err_unknown: 'ਕੁਝ ਗੜਬੜ ਹੋ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ · ਕਲਾਸ ਲਈ ਵਿਚਾਰ',
    help_1: 'ਸਾਈਨ ਇਨ ਕਰੋ ਅਤੇ ਨਮੂਨਾ ਕੁਇਜ਼ ਉੱਤੇ "ਲਾਈਵ ਚਲਾਓ" ਦਬਾਓ, 10 ਸਕਿੰਟਾਂ ਵਿੱਚ ਸਮਝ ਆ ਜਾਵੇਗਾ ਕਿ ਇਹ ਕਿਵੇਂ ਚੱਲਦਾ ਹੈ।',
    help_2: 'ਸਕ੍ਰੀਨ ਪ੍ਰੋਜੈਕਟਰ ਉੱਤੇ ਦਿਖਾਓ। ਵਿਦਿਆਰਥੀ ਫ਼ੋਨ ਉੱਤੇ apnipathshala.ai/join ਖੋਲ੍ਹ ਕੇ ਕੋਡ ਅਤੇ ਉਪਨਾਮ ਪਾਉਂਦੇ ਹਨ।',
    help_3: 'ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਪੂਰਾ ਨਾਂ ਨਹੀਂ, ਉਪਨਾਮ ਲਿਖਣ ਲਈ ਕਹੋ। ✕ ਨਾਲ ਕਿਸੇ ਨੂੰ ਵੀ ਹਟਾ ਸਕਦੇ ਹੋ, ਅਤੇ ਸਭ ਆ ਜਾਣ ਤਾਂ ਲੌਕ ਦਬਾਓ।',
    help_4: 'ਸਹੀ ਜਵਾਬ ਉੱਤੇ 500 ਤੋਂ 1000 ਅੰਕ: ਜਿੰਨਾ ਜਲਦੀ, ਓਨੇ ਵੱਧ। ਗਲਤ ਜਵਾਬ ਉੱਤੇ 0।',
    help_5: 'ਕਲਾਸ ਲਈ ਵਿਚਾਰ: ਪਾਠ ਦੇ ਅੰਤ ਵਿੱਚ 3-3 ਦੇ ਸਮੂਹ ਇੱਕ ਫ਼ੋਨ ਉੱਤੇ ਚਰਚਾ ਕਰਕੇ ਜਵਾਬ ਦੇਣ।',
    help_6: 'ਕੁਇਜ਼ ਮੇਕਰ ਵਿੱਚ ਕੁਇਜ਼ ਬਣਾ ਕੇ ਇੱਥੇ ਇੰਪੋਰਟ ਕਰੋ, ਜਾਂ ਨਵਾਂ ਕੁਇਜ਼ ਲਿਖੋ। ਰਿਕਾਰਡ ਲਈ ਨਤੀਜੇ CSV ਵਿੱਚ ਐਕਸਪੋਰਟ ਕਰੋ।'
  },
  or: {
    app_title: 'ଲାଇଭ୍ କ୍ଲାସ୍ କୁଇଜ୍',
    intro: 'ପ୍ରୋଜେକ୍ଟରରେ ଲାଇଭ୍ କୁଇଜ୍ ଚଳାନ୍ତୁ। ଅନଲାଇନରେ ଚଳାଇବାକୁ Google ରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ। ଛାତ୍ରଛାତ୍ରୀ ଫୋନରେ କୋଡ୍ ଓ ଡାକନାମ ଦେଇ ଯୋଗ ଦିଅନ୍ତି (ସାଇନ୍-ଅପ୍ ନାହିଁ), ପ୍ରତ୍ୟେକ ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଅନ୍ତି ଏବଂ ଦେଖନ୍ତି କିଏ ସବୁଠାରୁ ଆଗରେ।',
    demo_banner: 'ଡେମୋ ମୋଡ୍: ଏହା କେବଳ ଏହି ଗୋଟିଏ ଡିଭାଇସରେ ଚାଲେ। ଚେଷ୍ଟା କରିବାକୁ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପେଜ୍ ଅନ୍ୟ ଏକ ଟ୍ୟାବରେ ଖୋଲନ୍ତୁ। ଛାତ୍ରଛାତ୍ରୀଙ୍କ ଫୋନରେ ଖେଳିବାକୁ apnipathshala.ai/teacher ଖୋଲି Google ରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ।',
    shell_wa_msg: "{title}: ଆପଣଙ୍କ କ୍ଲାସ୍ ପାଇଁ ମାଗଣା ଲାଇଭ୍ କୁଇଜ୍। ଛାତ୍ରଛାତ୍ରୀ ଫୋନରେ କୋଡ୍ ଓ ଡାକନାମରେ ଯୋଗ ଦିଅନ୍ତି, ସାଇନ୍-ଅପ୍ ନାହିଁ; ଶିକ୍ଷକ Google ରେ ସାଇନ୍ ଇନ୍ କରନ୍ତି। ବିଜ୍ଞାପନ ନାହିଁ, 12ଟି ଭାରତୀୟ ଭାଷାରେ। ଏଠାରେ ଖୋଲନ୍ତୁ: {url}",
    demo_teacher: 'ଡେମୋ ଶିକ୍ଷକ',
    signin_title: 'Google ସହ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ — ଶିକ୍ଷକଙ୍କ ପାଇଁ ମାଗଣା',
    signin_text: 'ଆପଣଙ୍କ କୁଇଜ୍ ଅନଲାଇନରେ ସେଭ୍ ହୁଏ, ତେଣୁ ଯେକୌଣସି କମ୍ପ୍ୟୁଟରରେ ବ୍ୟବହାର କରିପାରିବେ। ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ କେବେ ସାଇନ୍ ଇନ୍ କରିବାକୁ ପଡ଼େ ନାହିଁ: ସେମାନେ କୋଡ୍ ଓ ଡାକନାମରେ ଯୋଗ ଦିଅନ୍ତି।',
    signin_google: 'Google ସହ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    signin_demo: 'ଏବେ ଡେମୋ ମୋଡରେ ଚେଷ୍ଟା କରନ୍ତୁ',
    inapp_hint: 'WhatsApp ଭଳି ଆପ୍ ଭିତରେ Google ସାଇନ୍-ଇନ୍ କାମ କରେ ନାହିଁ। ଏହି ପେଜ୍ Chrome ରେ ଖୋଲନ୍ତୁ।',
    use_demo: 'ଏହା ବଦଳରେ ଡେମୋ ମୋଡ୍ ବ୍ୟବହାର କରନ୍ତୁ',
    hello: 'ନମସ୍କାର, {name}',
    new_quiz: 'ନୂଆ କୁଇଜ୍',
    import_qm: 'ଏହି ଡିଭାଇସର କୁଇଜ୍ ମେକରରୁ ଆଣନ୍ତୁ',
    import_file: 'JSON / CSV ଇମ୍ପୋର୍ଟ କରନ୍ତୁ',
    import_hint: 'CSV ସ୍ତମ୍ଭ: ପ୍ରଶ୍ନ, ବିକଳ୍ପ 1 ରୁ ବିକଳ୍ପ 6, ଠିକ୍ ଉତ୍ତର (1–6 କିମ୍ବା A–F), ବ୍ୟାଖ୍ୟା।',
    settings_title: 'ଲାଇଭ୍ କୁଇଜର ସେଟିଂସ୍',
    time_per_q: 'ପ୍ରତ୍ୟେକ ପ୍ରଶ୍ନ ପାଇଁ ସମୟ',
    sec: '{n} ସେକେଣ୍ଡ',
    shuffle_q: 'ପ୍ରଶ୍ନର କ୍ରମ ବଦଳାନ୍ତୁ',
    shuffle_o: 'ବିକଳ୍ପର କ୍ରମ ବଦଳାନ୍ତୁ',
    my_quizzes: 'ମୋ କୁଇଜ୍',
    sample_badge: 'ନମୁନା',
    n_questions: '{n}ଟି ପ୍ରଶ୍ନ',
    host: 'ଲାଇଭ୍ ଚଳାନ୍ତୁ',
    edit_copy: 'କପି କରି ବଦଳାନ୍ତୁ',
    no_quizzes: 'ଏପର୍ଯ୍ୟନ୍ତ ଆପଣଙ୍କ ନିଜର କୌଣସି କୁଇଜ୍ ନାହିଁ। ନୂଆ କୁଇଜ୍ ତିଆରି କରନ୍ତୁ, ଇମ୍ପୋର୍ଟ କରନ୍ତୁ କିମ୍ବା ନମୁନା କୁଇଜ୍ ଚଳାନ୍ତୁ।',
    confirm_delete_quiz: '"{title}" କୁଇଜ୍ ବିଲୋପ କରିବେ?',
    deleted: 'ବିଲୋପ ହେଲା।',
    past_sessions: 'ପୂର୍ବ ସେସନ୍',
    no_sessions: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସେସନ୍ ନାହିଁ। ଏକ କୁଇଜ୍ ଚଳାନ୍ତୁ, ତାର ଫଳାଫଳ ଏଠାରେ ଦେଖାଯିବ।',
    keep_note: 'ଫଳାଫଳ 30 ଦିନ ପରେ ଲିଭିଯାଏ। ରଖିବାକୁ CSV ଡାଉନଲୋଡ୍ କରିନିଅନ୍ତୁ।',
    players_n: '{n} ଜଣ ଖେଳାଳି',
    code_n: 'କୋଡ୍ {code}',
    state_lobby: 'ଅପେକ୍ଷାରେ',
    state_live: 'ଚାଲୁଛି',
    state_ended: 'ଶେଷ',
    results: 'ଫଳାଫଳ',
    resume: 'ପୁଣି ଆରମ୍ଭ କରନ୍ତୁ',
    confirm_delete_session: 'ଏହି ସେସନ୍ ତାର ସମସ୍ତ ଉତ୍ତର ସହ ବିଲୋପ କରିବେ?',
    account: 'ଆପଣଙ୍କ ଆକାଉଣ୍ଟ',
    sign_out: 'ସାଇନ୍ ଆଉଟ୍',
    delete_account: 'ମୋ ଆକାଉଣ୍ଟ ଓ ଡାଟା ଲିଭାନ୍ତୁ',
    delete_account_text: 'ଏହା ଆପଣଙ୍କ ଶିକ୍ଷକ ଆକାଉଣ୍ଟ, ଆପଣଙ୍କ ସମସ୍ତ କୁଇଜ୍ ଓ ସେସନ୍, ଏବଂ ସେଥିରେ ଥିବା ଛାତ୍ରଛାତ୍ରୀଙ୍କ ସମସ୍ତ ଡାକନାମ ଓ ଉତ୍ତର ଲିଭାଇଦେବ। ଏହାକୁ ଆଉ ଫେରାଇ ହେବ ନାହିଁ।',
    delete_account_tip: 'ଏହା କରିବା ପୂର୍ବରୁ ଯେଉଁ ଫଳାଫଳ ରଖିବାକୁ ଚାହାଁନ୍ତି, ତାର CSV ଡାଉନଲୋଡ୍ କରିନିଅନ୍ତୁ।',
    delete_account_check: 'ମୁଁ ବୁଝିଛି। ସବୁକିଛି ବିଲୋପ କରନ୍ତୁ।',
    delete_forever: 'ସବୁଦିନ ପାଇଁ ବିଲୋପ କରନ୍ତୁ',
    account_deleted: 'ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ଓ ତାର ସମସ୍ତ ଡାଟା ବିଲୋପ ହେଲା।',
    privacy: 'ଗୋପନୀୟତା ନୀତି',
    terms: 'ବ୍ୟବହାର ସର୍ତ୍ତାବଳୀ',
    data_cloud: 'ଆପଣଙ୍କ କୁଇଜ୍ ଓ ଫଳାଫଳ Google Firebase (ମୁମ୍ବାଇ) ରେ ରଖାଯାଏ। ଛାତ୍ରଛାତ୍ରୀ କେବଳ ଡାକନାମ ଦିଅନ୍ତି।',
    data_demo: 'ଡେମୋ ମୋଡରେ ସବୁକିଛି ଏହି ବ୍ରାଉଜରରେ ହିଁ ରହେ।',
    edit_quiz: 'କୁଇଜ୍ ସମ୍ପାଦନା',
    quiz_title: 'କୁଇଜର ନାମ',
    question_n: 'ପ୍ରଶ୍ନ {n}',
    option_n: 'ବିକଳ୍ପ {n}',
    tick_correct: 'ଠିକ୍ ଉତ୍ତରରେ ଟିକ୍ ଦିଅନ୍ତୁ।',
    mark_correct: 'ବିକଳ୍ପ {n} ଠିକ୍ ଉତ୍ତର',
    add_option: 'ବିକଳ୍ପ ଯୋଡ଼ନ୍ତୁ',
    remove_option: 'ବିକଳ୍ପ {n} ହଟାନ୍ତୁ',
    explain_label: 'ବ୍ୟାଖ୍ୟା (ଇଚ୍ଛାଧୀନ, ଉତ୍ତର ପରେ ଦେଖାଯିବ)',
    time_label: 'ସେକେଣ୍ଡରେ ସମୟ (ଇଚ୍ଛାଧୀନ)',
    time_ph: 'ଡିଫଲ୍ଟ',
    add_question: 'ପ୍ରଶ୍ନ ଯୋଡ଼ନ୍ତୁ',
    move_up: 'ପ୍ରଶ୍ନ {n} ଉପରକୁ ନିଅନ୍ତୁ',
    move_down: 'ପ୍ରଶ୍ନ {n} ତଳକୁ ନିଅନ୍ତୁ',
    delete_question: 'ପ୍ରଶ୍ନ {n} ବିଲୋପ କରନ୍ତୁ',
    save_quiz: 'କୁଇଜ୍ ସେଭ୍ କରନ୍ତୁ',
    saved: 'ସେଭ୍ ହେଲା।',
    err_title: 'ଦୟାକରି କୁଇଜର ନାମ ଲେଖନ୍ତୁ।',
    err_no_questions: 'ଅତି କମରେ ଗୋଟିଏ ପ୍ରଶ୍ନ ଯୋଡ଼ନ୍ତୁ।',
    err_q_text: 'ପ୍ରଶ୍ନ {n}: ଦୟାକରି ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ।',
    err_q_options: 'ପ୍ରଶ୍ନ {n}: ଅତି କମରେ 2ଟି ବିକଳ୍ପ ଲେଖନ୍ତୁ।',
    err_q_correct: 'ପ୍ରଶ୍ନ {n}: ଠିକ୍ ଉତ୍ତରରେ ଟିକ୍ ଦିଅନ୍ତୁ।',
    draft_restored: 'ଆପଣଙ୍କ ସେଭ୍ ହୋଇନଥିବା ପରିବର୍ତ୍ତନ ଫେରିଆସିଲା।',
    confirm_discard: 'ଆପଣଙ୍କ ପରିବର୍ତ୍ତନ ଛାଡ଼ିଦେବେ?',
    untitled: 'ନାମହୀନ କୁଇଜ୍',
    opt_true: 'ଠିକ୍',
    opt_false: 'ଭୁଲ୍',
    qm_title: 'କୁଇଜ୍ ମେକରରେ ସେଭ୍ ହୋଇଥିବା କୁଇଜ୍',
    qm_none: 'ଏହି ଡିଭାଇସରେ କୁଇଜ୍ ମେକରର କୌଣସି କୁଇଜ୍ ମିଳିଲା ନାହିଁ।',
    open_qm: 'କୁଇଜ୍ ମେକର ଖୋଲନ୍ତୁ',
    import_selected: 'ବଛାଯାଇଥିବା ଇମ୍ପୋର୍ଟ କରନ୍ତୁ',
    imported_n: '{n}ଟି କୁଇଜ୍ ଇମ୍ପୋର୍ଟ ହେଲା।',
    skipped_n: '{n}ଟି ପ୍ରଶ୍ନ ଛାଡ଼ି ଦିଆଗଲା।',
    import_failed: 'ଏହି ଫାଇଲ୍ ପଢ଼ି ହେଲା ନାହିଁ। କୁଇଜ୍ ମେକରର JSON କିମ୍ବା CSV ଫାଇଲ୍ ବ୍ୟବହାର କରନ୍ତୁ।',
    join_line: '{url} କୁ ଯାଆନ୍ତୁ ଏବଂ ଏହି କୋଡ୍ ଲେଖନ୍ତୁ:',
    scan_qr: 'କିମ୍ବା ଏହି QR କୋଡ୍ ସ୍କାନ୍ କରନ୍ତୁ',
    qr_offline: 'QR କୋଡ୍ ପାଇଁ ଇଣ୍ଟରନେଟ୍ ଦରକାର। ଛାତ୍ରଛାତ୍ରୀ କୋଡ୍ ଟାଇପ୍ କରିପାରିବେ।',
    waiting_players: 'ଛାତ୍ରଛାତ୍ରୀଙ୍କ ଯୋଗ ଦେବାକୁ ଅପେକ୍ଷା…',
    joined_n: '{n} ଜଣ ଯୋଗ ଦେଲେ',
    lock: 'ଲକ୍ କରନ୍ତୁ',
    unlock: 'ଅନଲକ୍ କରନ୍ତୁ',
    locked_note: 'ଲକ୍ ଅଛି: ଆଉ କେହି ନୂଆ ଯୋଗ ଦେଇପାରିବେ ନାହିଁ।',
    kick: '{name}ଙ୍କୁ ହଟାନ୍ତୁ',
    confirm_kick: '{name}ଙ୍କୁ ଏହି କୁଇଜରୁ ହଟାଇବେ? ସେ ଆଉ ଯୋଗ ଦେଇପାରିବେ ନାହିଁ।',
    start_quiz: 'କୁଇଜ୍ ଆରମ୍ଭ କରନ୍ତୁ',
    need_player: 'ପ୍ରଥମେ ଅତି କମରେ ଜଣେ ଛାତ୍ର ଯୋଗ ଦେବା ଦରକାର।',
    open_student: 'ଛାତ୍ର ଟ୍ୟାବ୍ ଖୋଲନ୍ତୁ',
    question_of: 'ପ୍ରଶ୍ନ {n} / {total}',
    answered_n: '{total} ଜଣଙ୍କ ମଧ୍ୟରୁ {n} ଜଣ ଉତ୍ତର ଦେଲେ',
    show_answer: 'ଉତ୍ତର ଦେଖାନ୍ତୁ',
    skip_q: 'ପ୍ରଶ୍ନ ଛାଡ଼ନ୍ତୁ',
    time_up: 'ସମୟ ଶେଷ!',
    all_answered: 'ସମସ୍ତେ ଉତ୍ତର ଦେଲେ!',
    leaderboard: 'ଲିଡରବୋର୍ଡ',
    next_question: 'ପରବର୍ତ୍ତୀ ପ୍ରଶ୍ନ',
    final_results: 'ଚୂଡ଼ାନ୍ତ ଫଳାଫଳ',
    end_quiz: 'କୁଇଜ୍ ଶେଷ କରନ୍ତୁ',
    confirm_end: 'ଏବେ କୁଇଜ୍ ଶେଷ କରି ଚୂଡ଼ାନ୍ତ ଫଳାଫଳ ଦେଖାଇବେ?',
    correct_answer: 'ଠିକ୍ ଉତ୍ତର',
    points_n: '{n} ପଏଣ୍ଟ',
    col_rank: 'ସ୍ଥାନ',
    col_nick: 'ଡାକନାମ',
    col_correct: 'ଠିକ୍ ଉତ୍ତର',
    col_q: 'ପ୍ର{n}',
    col_question: 'ପ୍ରଶ୍ନ',
    export_csv: 'CSV ଏକ୍ସପୋର୍ଟ କରନ୍ତୁ',
    host_again: 'ପୁଣି ଚଳାନ୍ତୁ',
    back_dash: 'ମୋ କୁଇଜକୁ ଫେରନ୍ତୁ',
    session_gone: 'ଏହି କୁଇଜ୍ ସେସନ୍ ଆଉ ନାହିଁ।',
    nobody_joined: 'ଏହି କୁଇଜରେ କେହି ଯୋଗ ଦେଲେ ନାହିଁ।',
    keys_hint: 'କିବୋର୍ଡ: ଆଗକୁ ଯିବାକୁ Space କିମ୍ବା →',
    offline_banner: 'ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ନାହିଁ। ଛାତ୍ରଛାତ୍ରୀଙ୍କ ଉତ୍ତର ହୁଏତ ପହଞ୍ଚିବ ନାହିଁ।',
    connecting: 'ସଂଯୋଗ ହେଉଛି…',
    err_not_configured: 'ଅନଲାଇନ୍ କୁଇଜ୍ ଏପର୍ଯ୍ୟନ୍ତ ସେଟ୍ ହୋଇନାହିଁ। ଡେମୋ ମୋଡ୍ ଚେଷ୍ଟା କରନ୍ତୁ।',
    err_offline: 'ଇଣ୍ଟରନେଟ୍ ନାହିଁ। ସଂଯୋଗ ଦେଖି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
    err_quota_exceeded: 'ଆଜିର ମାଗଣା ସୀମା ସରିଗଲା। ଦୟାକରି କାଲି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ, କିମ୍ବା ଡେମୋ ମୋଡ୍ ବ୍ୟବହାର କରନ୍ତୁ।',
    err_not_found: 'ମିଳିଲା ନାହିଁ। ହୁଏତ ଏହା ବିଲୋପ ହୋଇଯାଇଛି।',
    err_permission_denied: 'ଆପଣଙ୍କୁ ଏହା କରିବାର ଅନୁମତି ନାହିଁ। ଦୟାକରି ପୁଣି ସାଇନ୍ ଇନ୍ କରନ୍ତୁ।',
    err_session_locked: 'ଏହି କୁଇଜ୍ ଲକ୍ ଅଛି।',
    err_session_ended: 'ଏହି କୁଇଜ୍ ଶେଷ ହୋଇଯାଇଛି।',
    err_name_taken: 'ଏହି ଡାକନାମ ଆଉ କେହି ବ୍ୟବହାର କରୁଛନ୍ତି।',
    err_invalid_input: 'ଦୟାକରି ଯାହା ଲେଖିଛନ୍ତି ତାହା ଯାଞ୍ଚ କରନ୍ତୁ।',
    err_unknown: 'କିଛି ଭୁଲ୍ ହେଲା। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ · ଶ୍ରେଣୀ ପାଇଁ ଧାରଣା',
    help_1: 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ ଏବଂ ନମୁନା କୁଇଜରେ "ଲାଇଭ୍ ଚଳାନ୍ତୁ" ଦବାନ୍ତୁ, 10 ସେକେଣ୍ଡରେ ବୁଝିଯିବେ ଏହା କିପରି ଚାଲେ।',
    help_2: 'ସ୍କ୍ରିନ୍ ପ୍ରୋଜେକ୍ଟରରେ ଦେଖାନ୍ତୁ। ଛାତ୍ରଛାତ୍ରୀ ଫୋନରେ apnipathshala.ai/join ଖୋଲି କୋଡ୍ ଓ ଡାକନାମ ଲେଖନ୍ତି।',
    help_3: 'ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ପୂରା ନାମ ନୁହେଁ, ଡାକନାମ ଲେଖିବାକୁ କୁହନ୍ତୁ। ✕ ଦ୍ୱାରା ଯେକୌଣସି ଜଣଙ୍କୁ ହଟାଇପାରିବେ, ଏବଂ ସମସ୍ତେ ଆସିଗଲେ ଲକ୍ ଦବାନ୍ତୁ।',
    help_4: 'ଠିକ୍ ଉତ୍ତରରେ 500 ରୁ 1000 ପଏଣ୍ଟ: ଯେତେ ଶୀଘ୍ର, ସେତେ ଅଧିକ। ଭୁଲ୍ ଉତ୍ତରରେ 0।',
    help_5: 'ଶ୍ରେଣୀ ପାଇଁ ଧାରଣା: ଅଧ୍ୟାୟ ଶେଷରେ 3 ଜଣିଆ ଦଳ ଗୋଟିଏ ଫୋନରେ ଆଲୋଚନା କରି ଉତ୍ତର ଦିଅନ୍ତୁ।',
    help_6: 'କୁଇଜ୍ ମେକରରେ କୁଇଜ୍ ତିଆରି କରି ଏଠାରେ ଇମ୍ପୋର୍ଟ କରନ୍ତୁ, କିମ୍ବା ନୂଆ କୁଇଜ୍ ଲେଖନ୍ତୁ। ରେକର୍ଡ ପାଇଁ ଫଳାଫଳ CSV ରେ ଏକ୍ସପୋର୍ଟ କରନ୍ତୁ।'
  },
  ta: {
    app_title: 'நேரலை வகுப்பு வினாடி வினா',
    intro: 'புரொஜெக்டரில் நேரலை வினாடி வினா நடத்துங்கள். இணையத்தில் நடத்த Google மூலம் உள்நுழையுங்கள். மாணவர்கள் போனில் குறியீட்டையும் புனைபெயரையும் உள்ளிட்டுச் சேர்ந்து (பதிவு தேவையில்லை), ஒவ்வொரு கேள்விக்கும் பதில் அளித்து, யார் முதலிடத்தில் இருக்கிறார்கள் என்று பார்க்கிறார்கள்.',
    demo_banner: 'டெமோ முறை: இது இந்த ஒரு சாதனத்தில் மட்டுமே இயங்கும். முயற்சிக்க, மாணவர் பக்கத்தை வேறொரு டேபில் திறக்கவும். மாணவர்களின் போன்களில் விளையாட, apnipathshala.ai/teacher திறந்து Google மூலம் உள்நுழையுங்கள்.',
    shell_wa_msg: "{title}: உங்கள் வகுப்புக்கான இலவச நேரலை வினாடி வினா. மாணவர்கள் போனில் குறியீடும் புனைப்பெயரும் கொண்டு சேர்கிறார்கள், பதிவு தேவையில்லை; ஆசிரியர் Google மூலம் உள்நுழைவார். விளம்பரம் இல்லை, 12 இந்திய மொழிகளில். இங்கே திறக்கவும்: {url}",
    demo_teacher: 'டெமோ ஆசிரியர்',
    signin_title: 'Google மூலம் உள்நுழையுங்கள் — ஆசிரியர்களுக்கு இலவசம்',
    signin_text: 'உங்கள் வினாடி வினாக்கள் ஆன்லைனில் சேமிக்கப்படும், அதனால் எந்தக் கணினியிலும் பயன்படுத்தலாம். மாணவர்கள் ஒருபோதும் உள்நுழைவதில்லை: குறியீடும் புனைபெயரும் கொண்டே சேர்கிறார்கள்.',
    signin_google: 'Google மூலம் உள்நுழை',
    signin_demo: 'இப்போதே டெமோ முறையில் முயற்சி செய்',
    inapp_hint: 'WhatsApp போன்ற செயலிகளுக்குள் Google உள்நுழைவு வேலை செய்யாது. இந்தப் பக்கத்தை Chrome-இல் திறக்கவும்.',
    use_demo: 'பதிலாக டெமோ முறையைப் பயன்படுத்து',
    hello: 'வணக்கம், {name}',
    new_quiz: 'புதிய வினாடி வினா',
    import_qm: 'இந்தச் சாதனத்தின் வினாடி வினா உருவாக்கியிலிருந்து கொண்டு வா',
    import_file: 'JSON / CSV இறக்குமதி',
    import_hint: 'CSV நெடுவரிசைகள்: கேள்வி, விருப்பம் 1 முதல் விருப்பம் 6, சரியான பதில் (1–6 அல்லது A–F), விளக்கம்.',
    settings_title: 'நேரலை வினாடி வினா அமைப்புகள்',
    time_per_q: 'ஒவ்வொரு கேள்விக்கும் நேரம்',
    sec: '{n} வினாடி',
    shuffle_q: 'கேள்விகளைக் கலக்கு',
    shuffle_o: 'விடை விருப்பங்களைக் கலக்கு',
    my_quizzes: 'என் வினாடி வினாக்கள்',
    sample_badge: 'மாதிரி',
    n_questions: '{n} கேள்விகள்',
    host: 'நேரலையாக நடத்து',
    edit_copy: 'நகலெடுத்துத் திருத்து',
    no_quizzes: 'உங்களுக்கென்று இன்னும் வினாடி வினா இல்லை. புதியது உருவாக்குங்கள், இறக்குமதி செய்யுங்கள், அல்லது மாதிரி வினாடி வினாவை நடத்துங்கள்.',
    confirm_delete_quiz: '"{title}" வினாடி வினாவை நீக்கவா?',
    deleted: 'நீக்கப்பட்டது.',
    past_sessions: 'முந்தைய அமர்வுகள்',
    no_sessions: 'இன்னும் அமர்வுகள் இல்லை. ஒரு வினாடி வினா நடத்துங்கள், அதன் முடிவுகள் இங்கே தெரியும்.',
    keep_note: 'முடிவுகள் 30 நாட்களுக்குப் பிறகு அழிக்கப்படும். வைத்துக்கொள்ள CSV-ஐப் பதிவிறக்குங்கள்.',
    players_n: '{n} பேர்',
    code_n: 'குறியீடு {code}',
    state_lobby: 'காத்திருக்கிறது',
    state_live: 'நேரலை',
    state_ended: 'முடிந்தது',
    results: 'முடிவுகள்',
    resume: 'தொடர்',
    confirm_delete_session: 'இந்த அமர்வை அதன் எல்லாப் பதில்களுடனும் நீக்கவா?',
    account: 'உங்கள் கணக்கு',
    sign_out: 'வெளியேறு',
    delete_account: 'என் கணக்கையும் தரவையும் நீக்கு',
    delete_account_text: 'இது உங்கள் ஆசிரியர் கணக்கு, உங்கள் எல்லா வினாடி வினாக்கள், அமர்வுகள், அவற்றில் உள்ள மாணவர்களின் எல்லாப் புனைபெயர்கள், பதில்கள் அனைத்தையும் அழிக்கும். இதைத் திரும்பப் பெற முடியாது.',
    delete_account_tip: 'இதைச் செய்வதற்கு முன், வைத்துக்கொள்ள விரும்பும் முடிவுகளின் CSV-ஐப் பதிவிறக்குங்கள்.',
    delete_account_check: 'எனக்குப் புரிகிறது. எல்லாவற்றையும் நீக்கு.',
    delete_forever: 'நிரந்தரமாக நீக்கு',
    account_deleted: 'உங்கள் கணக்கும் அதன் எல்லாத் தரவும் நீக்கப்பட்டன.',
    privacy: 'தனியுரிமைக் கொள்கை',
    terms: 'பயன்பாட்டு விதிமுறைகள்',
    data_cloud: 'உங்கள் வினாடி வினாக்களும் முடிவுகளும் Google Firebase-இல் (மும்பை) வைக்கப்படும். மாணவர்கள் புனைபெயர் மட்டுமே தருகிறார்கள்.',
    data_demo: 'டெமோ முறையில் எல்லாமே இந்த உலாவியில் மட்டுமே இருக்கும்.',
    edit_quiz: 'வினாடி வினாவைத் திருத்து',
    quiz_title: 'வினாடி வினா பெயர்',
    question_n: 'கேள்வி {n}',
    option_n: 'விருப்பம் {n}',
    tick_correct: 'சரியான பதிலைத் தேர்வு செய்யுங்கள்.',
    mark_correct: 'விருப்பம் {n} சரியான பதில்',
    add_option: 'விருப்பம் சேர்',
    remove_option: 'விருப்பம் {n}-ஐ நீக்கு',
    explain_label: 'விளக்கம் (விருப்பப்பட்டால், பதிலுக்குப் பின் காட்டப்படும்)',
    time_label: 'நேரம் வினாடிகளில் (விருப்பப்பட்டால்)',
    time_ph: 'இயல்புநிலை',
    add_question: 'கேள்வி சேர்',
    move_up: 'கேள்வி {n}-ஐ மேலே நகர்த்து',
    move_down: 'கேள்வி {n}-ஐ கீழே நகர்த்து',
    delete_question: 'கேள்வி {n}-ஐ நீக்கு',
    save_quiz: 'வினாடி வினாவைச் சேமி',
    saved: 'சேமிக்கப்பட்டது.',
    err_title: 'வினாடி வினாவுக்கு ஒரு பெயர் எழுதுங்கள்.',
    err_no_questions: 'குறைந்தது ஒரு கேள்வியாவது சேருங்கள்.',
    err_q_text: 'கேள்வி {n}: கேள்வியை எழுதுங்கள்.',
    err_q_options: 'கேள்வி {n}: குறைந்தது 2 விருப்பங்களை எழுதுங்கள்.',
    err_q_correct: 'கேள்வி {n}: சரியான பதிலைத் தேர்வு செய்யுங்கள்.',
    draft_restored: 'சேமிக்காத உங்கள் மாற்றங்கள் மீட்டெடுக்கப்பட்டன.',
    confirm_discard: 'உங்கள் மாற்றங்களைக் கைவிடவா?',
    untitled: 'பெயரில்லா வினாடி வினா',
    opt_true: 'சரி',
    opt_false: 'தவறு',
    qm_title: 'வினாடி வினா உருவாக்கியில் சேமித்தவை',
    qm_none: 'இந்தச் சாதனத்தில் வினாடி வினா உருவாக்கியின் வினாடி வினா எதுவும் இல்லை.',
    open_qm: 'வினாடி வினா உருவாக்கியைத் திற',
    import_selected: 'தேர்ந்தெடுத்தவற்றை இறக்குமதி செய்',
    imported_n: '{n} வினாடி வினாக்கள் இறக்குமதி செய்யப்பட்டன.',
    skipped_n: '{n} கேள்விகள் தவிர்க்கப்பட்டன.',
    import_failed: 'இந்தக் கோப்பைப் படிக்க முடியவில்லை. வினாடி வினா உருவாக்கியின் JSON அல்லது CSV கோப்பைப் பயன்படுத்துங்கள்.',
    join_line: '{url} -க்குச் சென்று இந்தக் குறியீட்டை உள்ளிடுங்கள்:',
    scan_qr: 'அல்லது இந்த QR குறியீட்டை ஸ்கேன் செய்யுங்கள்',
    qr_offline: 'QR குறியீட்டுக்கு இணையம் தேவை. மாணவர்கள் குறியீட்டைத் தட்டச்சு செய்யலாம்.',
    waiting_players: 'மாணவர்கள் சேரக் காத்திருக்கிறோம்…',
    joined_n: '{n} பேர் சேர்ந்தனர்',
    lock: 'பூட்டு',
    unlock: 'திற',
    locked_note: 'பூட்டப்பட்டது: இனி யாரும் புதிதாகச் சேர முடியாது.',
    kick: '{name}-ஐ நீக்கு',
    confirm_kick: '{name}-ஐ இந்த வினாடி வினாவிலிருந்து நீக்கவா? அவர் மீண்டும் சேர முடியாது.',
    start_quiz: 'வினாடி வினாவைத் தொடங்கு',
    need_player: 'முதலில் குறைந்தது ஒரு மாணவராவது சேர வேண்டும்.',
    open_student: 'மாணவர் டேபைத் திற',
    question_of: 'கேள்வி {n} / {total}',
    answered_n: '{total} பேரில் {n} பேர் பதிலளித்தனர்',
    show_answer: 'பதிலைக் காட்டு',
    skip_q: 'கேள்வியைத் தவிர்',
    time_up: 'நேரம் முடிந்தது!',
    all_answered: 'எல்லோரும் பதிலளித்துவிட்டனர்!',
    leaderboard: 'முன்னிலைப் பட்டியல்',
    next_question: 'அடுத்த கேள்வி',
    final_results: 'இறுதி முடிவுகள்',
    end_quiz: 'வினாடி வினாவை முடி',
    confirm_end: 'வினாடி வினாவை இப்போதே முடித்து இறுதி முடிவுகளைக் காட்டவா?',
    correct_answer: 'சரியான பதில்',
    points_n: '{n} புள்ளிகள்',
    col_rank: 'இடம்',
    col_nick: 'புனைபெயர்',
    col_correct: 'சரியான பதில்கள்',
    col_q: 'கே{n}',
    col_question: 'கேள்வி',
    export_csv: 'CSV ஏற்றுமதி',
    host_again: 'மீண்டும் நடத்து',
    back_dash: 'என் வினாடி வினாக்களுக்குத் திரும்பு',
    session_gone: 'இந்த வினாடி வினா அமர்வு இப்போது இல்லை.',
    nobody_joined: 'இந்த வினாடி வினாவில் யாரும் சேரவில்லை.',
    keys_hint: 'விசைப்பலகை: அடுத்ததற்கு Space அல்லது →',
    offline_banner: 'இணைய இணைப்பு இல்லை. மாணவர்களின் பதில்கள் வந்து சேராமல் போகலாம்.',
    connecting: 'இணைக்கிறது…',
    err_not_configured: 'ஆன்லைன் வினாடி வினா இன்னும் அமைக்கப்படவில்லை. டெமோ முறையை முயற்சிக்கவும்.',
    err_offline: 'இணையம் இல்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    err_quota_exceeded: 'இன்றைய இலவச வரம்பு முடிந்தது. நாளை மீண்டும் முயற்சிக்கவும், அல்லது டெமோ முறையைப் பயன்படுத்தவும்.',
    err_not_found: 'கிடைக்கவில்லை. ஒருவேளை நீக்கப்பட்டிருக்கலாம்.',
    err_permission_denied: 'இதைச் செய்ய உங்களுக்கு அனுமதி இல்லை. மீண்டும் உள்நுழையவும்.',
    err_session_locked: 'இந்த வினாடி வினா பூட்டப்பட்டுள்ளது.',
    err_session_ended: 'இந்த வினாடி வினா முடிந்துவிட்டது.',
    err_name_taken: 'இந்தப் புனைபெயரை வேறொருவர் பயன்படுத்துகிறார்.',
    err_invalid_input: 'நீங்கள் எழுதியதைச் சரிபார்க்கவும்.',
    err_unknown: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
    help_title: 'பயன்படுத்துவது எப்படி · வகுப்பறைக்கான யோசனைகள்',
    help_1: 'உள்நுழைந்து மாதிரி வினாடி வினாவில் "நேரலையாக நடத்து" அழுத்துங்கள், 10 வினாடிகளில் இது எப்படி இயங்குகிறது என்று புரியும்.',
    help_2: 'திரையை புரொஜெக்டரில் காட்டுங்கள். மாணவர்கள் போனில் apnipathshala.ai/join திறந்து குறியீட்டையும் புனைபெயரையும் உள்ளிடுவார்கள்.',
    help_3: 'முழுப் பெயர் வேண்டாம், புனைபெயர் போடச் சொல்லுங்கள். ✕ மூலம் யாரையும் நீக்கலாம், எல்லோரும் சேர்ந்ததும் பூட்டு அழுத்துங்கள்.',
    help_4: 'சரியான பதிலுக்கு 500 முதல் 1000 புள்ளிகள்: எவ்வளவு வேகமோ அவ்வளவு அதிகம். தவறான பதிலுக்கு 0.',
    help_5: 'வகுப்பறை யோசனை: பாட முடிவில் 3 பேர் கொண்ட குழுக்கள் ஒரே போனில் கலந்துபேசி பதில் அளிக்கட்டும்.',
    help_6: 'வினாடி வினா உருவாக்கியில் தயாரித்து இங்கே இறக்குமதி செய்யுங்கள், அல்லது புதியதாக எழுதுங்கள். பதிவுக்காக முடிவுகளை CSV-ஆக ஏற்றுமதி செய்யுங்கள்.'
  },
  te: {
    app_title: 'లైవ్ క్లాస్ క్విజ్',
    intro: 'ప్రొజెక్టర్‌పై లైవ్ క్విజ్ నిర్వహించండి. ఆన్‌లైన్‌లో నిర్వహించడానికి Google తో సైన్ ఇన్ చేయండి. విద్యార్థులు ఫోన్‌లో కోడ్, మారుపేరుతో చేరి (సైన్-అప్ అవసరం లేదు), ప్రతి ప్రశ్నకు జవాబిచ్చి, ఎవరు ముందున్నారో చూస్తారు.',
    demo_banner: 'డెమో మోడ్: ఇది ఈ ఒక్క పరికరంలోనే పనిచేస్తుంది. ప్రయత్నించడానికి విద్యార్థి పేజీని మరో ట్యాబ్‌లో తెరవండి. విద్యార్థుల ఫోన్లలో ఆడించడానికి apnipathshala.ai/teacher తెరిచి Google తో సైన్ ఇన్ చేయండి.',
    shell_wa_msg: "{title}: మీ తరగతి కోసం ఉచిత లైవ్ క్విజ్. విద్యార్థులు ఫోన్‌లో కోడ్, మారుపేరుతో చేరతారు, సైన్-అప్ లేదు; ఉపాధ్యాయులు Google తో సైన్ ఇన్ చేస్తారు. ప్రకటనలు లేవు, 12 భారతీయ భాషల్లో. ఇక్కడ తెరవండి: {url}",
    demo_teacher: 'డెమో టీచర్',
    signin_title: 'Google తో సైన్ ఇన్ చేయండి — ఉపాధ్యాయులకు ఉచితం',
    signin_text: 'మీ క్విజ్‌లు ఆన్‌లైన్‌లో సేవ్ అవుతాయి, కాబట్టి ఏ కంప్యూటర్‌లోనైనా వాడుకోవచ్చు. విద్యార్థులు ఎప్పుడూ సైన్ ఇన్ చేయరు: కోడ్, మారుపేరుతో చేరతారు.',
    signin_google: 'Google తో సైన్ ఇన్ చేయండి',
    signin_demo: 'ఇప్పుడే డెమో మోడ్‌లో ప్రయత్నించండి',
    inapp_hint: 'WhatsApp వంటి యాప్‌ల లోపల Google సైన్-ఇన్ పనిచేయదు. ఈ పేజీని Chromeలో తెరవండి.',
    use_demo: 'బదులుగా డెమో మోడ్ వాడండి',
    hello: 'నమస్తే, {name}',
    new_quiz: 'కొత్త క్విజ్',
    import_qm: 'ఈ పరికరంలోని క్విజ్ మేకర్ నుంచి తీసుకురండి',
    import_file: 'JSON / CSV ఇంపోర్ట్ చేయండి',
    import_hint: 'CSV కాలమ్‌లు: ప్రశ్న, ఎంపిక 1 నుంచి ఎంపిక 6, సరైన జవాబు (1–6 లేదా A–F), వివరణ.',
    settings_title: 'లైవ్ క్విజ్ సెట్టింగ్‌లు',
    time_per_q: 'ప్రతి ప్రశ్నకు సమయం',
    sec: '{n} సెకన్లు',
    shuffle_q: 'ప్రశ్నల క్రమం మార్చండి',
    shuffle_o: 'ఎంపికల క్రమం మార్చండి',
    my_quizzes: 'నా క్విజ్‌లు',
    sample_badge: 'నమూనా',
    n_questions: '{n} ప్రశ్నలు',
    host: 'లైవ్‌గా నిర్వహించండి',
    edit_copy: 'కాపీ చేసి మార్చండి',
    no_quizzes: 'ఇంకా మీ సొంత క్విజ్ ఏదీ లేదు. కొత్త క్విజ్ చేయండి, ఇంపోర్ట్ చేయండి, లేదా నమూనా క్విజ్ నిర్వహించండి.',
    confirm_delete_quiz: '"{title}" క్విజ్‌ను తొలగించాలా?',
    deleted: 'తొలగించబడింది.',
    past_sessions: 'గత సెషన్‌లు',
    no_sessions: 'ఇంకా సెషన్‌లు లేవు. ఒక క్విజ్ నిర్వహించండి, దాని ఫలితాలు ఇక్కడ కనిపిస్తాయి.',
    keep_note: 'ఫలితాలు 30 రోజుల తర్వాత తొలగిపోతాయి. ఉంచుకోవాలంటే CSV డౌన్‌లోడ్ చేసుకోండి.',
    players_n: '{n} మంది ఆటగాళ్లు',
    code_n: 'కోడ్ {code}',
    state_lobby: 'వేచి ఉంది',
    state_live: 'లైవ్',
    state_ended: 'ముగిసింది',
    results: 'ఫలితాలు',
    resume: 'కొనసాగించండి',
    confirm_delete_session: 'ఈ సెషన్‌ను దాని అన్ని జవాబులతో సహా తొలగించాలా?',
    account: 'మీ ఖాతా',
    sign_out: 'సైన్ అవుట్',
    delete_account: 'నా ఖాతా, డేటా తొలగించు',
    delete_account_text: 'దీనివల్ల మీ టీచర్ ఖాతా, మీ అన్ని క్విజ్‌లు, సెషన్‌లు, వాటిలోని విద్యార్థుల మారుపేర్లు, జవాబులు అన్నీ తొలగిపోతాయి. దీన్ని మళ్ళీ తెచ్చుకోలేరు.',
    delete_account_tip: 'ఇలా చేసే ముందు, ఉంచుకోవాల్సిన ఫలితాల CSV డౌన్‌లోడ్ చేసుకోండి.',
    delete_account_check: 'నాకు అర్థమైంది. అన్నీ తొలగించండి.',
    delete_forever: 'శాశ్వతంగా తొలగించండి',
    account_deleted: 'మీ ఖాతా, దాని మొత్తం డేటా తొలగించబడ్డాయి.',
    privacy: 'గోప్యతా విధానం',
    terms: 'వినియోగ నిబంధనలు',
    data_cloud: 'మీ క్విజ్‌లు, ఫలితాలు Google Firebase (ముంబై)లో ఉంటాయి. విద్యార్థులు మారుపేరు మాత్రమే ఇస్తారు.',
    data_demo: 'డెమో మోడ్‌లో అంతా ఈ బ్రౌజర్‌లోనే ఉంటుంది.',
    edit_quiz: 'క్విజ్ మార్చండి',
    quiz_title: 'క్విజ్ పేరు',
    question_n: 'ప్రశ్న {n}',
    option_n: 'ఎంపిక {n}',
    tick_correct: 'సరైన జవాబును టిక్ చేయండి.',
    mark_correct: 'ఎంపిక {n} సరైన జవాబు',
    add_option: 'ఎంపిక జోడించండి',
    remove_option: 'ఎంపిక {n} తీసివేయండి',
    explain_label: 'వివరణ (ఐచ్ఛికం, జవాబు తర్వాత చూపిస్తుంది)',
    time_label: 'సమయం సెకన్లలో (ఐచ్ఛికం)',
    time_ph: 'డిఫాల్ట్',
    add_question: 'ప్రశ్న జోడించండి',
    move_up: 'ప్రశ్న {n}ని పైకి జరపండి',
    move_down: 'ప్రశ్న {n}ని కిందికి జరపండి',
    delete_question: 'ప్రశ్న {n}ని తొలగించండి',
    save_quiz: 'క్విజ్ సేవ్ చేయండి',
    saved: 'సేవ్ అయింది.',
    err_title: 'దయచేసి క్విజ్‌కు పేరు రాయండి.',
    err_no_questions: 'కనీసం ఒక ప్రశ్న జోడించండి.',
    err_q_text: 'ప్రశ్న {n}: దయచేసి ప్రశ్న రాయండి.',
    err_q_options: 'ప్రశ్న {n}: కనీసం 2 ఎంపికలు రాయండి.',
    err_q_correct: 'ప్రశ్న {n}: సరైన జవాబును టిక్ చేయండి.',
    draft_restored: 'సేవ్ చేయని మీ మార్పులు తిరిగి తెచ్చాం.',
    confirm_discard: 'మీ మార్పులను వదిలేయాలా?',
    untitled: 'పేరులేని క్విజ్',
    opt_true: 'ఒప్పు',
    opt_false: 'తప్పు',
    qm_title: 'క్విజ్ మేకర్‌లో సేవ్ చేసిన క్విజ్‌లు',
    qm_none: 'ఈ పరికరంలో క్విజ్ మేకర్ క్విజ్‌లు ఏవీ దొరకలేదు.',
    open_qm: 'క్విజ్ మేకర్ తెరవండి',
    import_selected: 'ఎంచుకున్నవి ఇంపోర్ట్ చేయండి',
    imported_n: '{n} క్విజ్‌లు ఇంపోర్ట్ అయ్యాయి.',
    skipped_n: '{n} ప్రశ్నలు వదిలేశాం.',
    import_failed: 'ఈ ఫైల్‌ను చదవలేకపోయాం. క్విజ్ మేకర్ JSON లేదా CSV ఫైల్ వాడండి.',
    join_line: '{url} కి వెళ్ళి ఈ కోడ్ టైప్ చేయండి:',
    scan_qr: 'లేదా ఈ QR కోడ్ స్కాన్ చేయండి',
    qr_offline: 'QR కోడ్‌కు ఇంటర్నెట్ కావాలి. విద్యార్థులు కోడ్ టైప్ చేయవచ్చు.',
    waiting_players: 'విద్యార్థులు చేరడం కోసం ఎదురుచూస్తున్నాం…',
    joined_n: '{n} మంది చేరారు',
    lock: 'లాక్ చేయండి',
    unlock: 'అన్‌లాక్ చేయండి',
    locked_note: 'లాక్ అయింది: ఇక కొత్తవారు ఎవరూ చేరలేరు.',
    kick: '{name}ని తీసివేయండి',
    confirm_kick: '{name}ని ఈ క్విజ్ నుంచి తీసివేయాలా? వారు మళ్ళీ చేరలేరు.',
    start_quiz: 'క్విజ్ ప్రారంభించండి',
    need_player: 'ముందు కనీసం ఒక విద్యార్థి చేరాలి.',
    open_student: 'విద్యార్థి ట్యాబ్ తెరవండి',
    question_of: 'ప్రశ్న {n} / {total}',
    answered_n: '{total} మందిలో {n} మంది జవాబిచ్చారు',
    show_answer: 'జవాబు చూపించండి',
    skip_q: 'ప్రశ్న దాటవేయండి',
    time_up: 'సమయం అయిపోయింది!',
    all_answered: 'అందరూ జవాబిచ్చారు!',
    leaderboard: 'లీడర్‌బోర్డ్',
    next_question: 'తదుపరి ప్రశ్న',
    final_results: 'తుది ఫలితాలు',
    end_quiz: 'క్విజ్ ముగించండి',
    confirm_end: 'క్విజ్‌ను ఇప్పుడే ముగించి తుది ఫలితాలు చూపించాలా?',
    correct_answer: 'సరైన జవాబు',
    points_n: '{n} పాయింట్లు',
    col_rank: 'ర్యాంక్',
    col_nick: 'మారుపేరు',
    col_correct: 'సరైన జవాబులు',
    col_q: 'ప్ర{n}',
    col_question: 'ప్రశ్న',
    export_csv: 'CSV ఎక్స్‌పోర్ట్ చేయండి',
    host_again: 'మళ్ళీ నిర్వహించండి',
    back_dash: 'నా క్విజ్‌లకు తిరిగి వెళ్ళండి',
    session_gone: 'ఈ క్విజ్ సెషన్ ఇప్పుడు లేదు.',
    nobody_joined: 'ఈ క్విజ్‌లో ఎవరూ చేరలేదు.',
    keys_hint: 'కీబోర్డ్: తదుపరికి Space లేదా →',
    offline_banner: 'ఇంటర్నెట్ కనెక్షన్ లేదు. విద్యార్థుల జవాబులు అందకపోవచ్చు.',
    connecting: 'కనెక్ట్ అవుతోంది…',
    err_not_configured: 'ఆన్‌లైన్ క్విజ్ ఇంకా సెటప్ కాలేదు. డెమో మోడ్ ప్రయత్నించండి.',
    err_offline: 'ఇంటర్నెట్ లేదు. కనెక్షన్ చూసి మళ్ళీ ప్రయత్నించండి.',
    err_quota_exceeded: 'ఈ రోజు ఉచిత పరిమితి అయిపోయింది. దయచేసి రేపు మళ్ళీ ప్రయత్నించండి, లేదా డెమో మోడ్ వాడండి.',
    err_not_found: 'దొరకలేదు. బహుశా తొలగించబడి ఉండవచ్చు.',
    err_permission_denied: 'దీనికి మీకు అనుమతి లేదు. దయచేసి మళ్ళీ సైన్ ఇన్ చేయండి.',
    err_session_locked: 'ఈ క్విజ్ లాక్ అయింది.',
    err_session_ended: 'ఈ క్విజ్ ముగిసింది.',
    err_name_taken: 'ఈ మారుపేరును ఇంకెవరో వాడుతున్నారు.',
    err_invalid_input: 'దయచేసి మీరు రాసింది ఒకసారి చూడండి.',
    err_unknown: 'ఏదో పొరపాటు జరిగింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    help_title: 'ఎలా ఉపయోగించాలి · తరగతి కోసం ఆలోచనలు',
    help_1: 'సైన్ ఇన్ చేసి నమూనా క్విజ్‌పై "లైవ్‌గా నిర్వహించండి" నొక్కండి, 10 సెకన్లలో ఇది ఎలా పనిచేస్తుందో అర్థమవుతుంది.',
    help_2: 'స్క్రీన్‌ను ప్రొజెక్టర్‌పై చూపించండి. విద్యార్థులు ఫోన్‌లో apnipathshala.ai/join తెరిచి కోడ్, మారుపేరు టైప్ చేస్తారు.',
    help_3: 'పూర్తి పేరు కాకుండా మారుపేరు వాడమని విద్యార్థులకు చెప్పండి. ✕ తో ఎవరినైనా తీసివేయవచ్చు, అందరూ చేరాక లాక్ నొక్కండి.',
    help_4: 'సరైన జవాబుకు 500 నుంచి 1000 పాయింట్లు: ఎంత వేగంగా ఇస్తే అంత ఎక్కువ. తప్పు జవాబుకు 0.',
    help_5: 'తరగతి ఆలోచన: పాఠం చివర్లో 3 మంది గుంపులు ఒకే ఫోన్‌పై చర్చించి జవాబివ్వనివ్వండి.',
    help_6: 'క్విజ్ మేకర్‌లో క్విజ్ తయారుచేసి ఇక్కడ ఇంపోర్ట్ చేయండి, లేదా కొత్తది రాయండి. రికార్డు కోసం ఫలితాలను CSVగా ఎక్స్‌పోర్ట్ చేయండి.'
  },
  kn: {
    app_title: 'ಲೈವ್ ತರಗತಿ ಕ್ವಿಜ್',
    intro: 'ಪ್ರೊಜೆಕ್ಟರ್‌ನಲ್ಲಿ ಲೈವ್ ಕ್ವಿಜ್ ನಡೆಸಿ. ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ನಡೆಸಲು Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ. ವಿದ್ಯಾರ್ಥಿಗಳು ಫೋನ್‌ನಲ್ಲಿ ಕೋಡ್ ಮತ್ತು ಅಡ್ಡಹೆಸರು ಹಾಕಿ ಸೇರುತ್ತಾರೆ (ಸೈನ್-ಅಪ್ ಬೇಕಿಲ್ಲ), ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸುತ್ತಾರೆ ಮತ್ತು ಯಾರು ಮುಂದಿದ್ದಾರೆ ಎಂದು ನೋಡುತ್ತಾರೆ.',
    demo_banner: 'ಡೆಮೊ ಮೋಡ್: ಇದು ಈ ಒಂದೇ ಸಾಧನದಲ್ಲಿ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ಪ್ರಯತ್ನಿಸಲು ವಿದ್ಯಾರ್ಥಿ ಪುಟವನ್ನು ಇನ್ನೊಂದು ಟ್ಯಾಬ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ. ವಿದ್ಯಾರ್ಥಿಗಳ ಫೋನ್‌ಗಳಲ್ಲಿ ಆಡಿಸಲು apnipathshala.ai/teacher ತೆರೆದು Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    shell_wa_msg: "{title}: ನಿಮ್ಮ ತರಗತಿಗಾಗಿ ಉಚಿತ ಲೈವ್ ಕ್ವಿಜ್. ವಿದ್ಯಾರ್ಥಿಗಳು ಫೋನ್‌ನಲ್ಲಿ ಕೋಡ್ ಮತ್ತು ಅಡ್ಡಹೆಸರಿನಿಂದ ಸೇರುತ್ತಾರೆ, ಸೈನ್-ಅಪ್ ಇಲ್ಲ; ಶಿಕ್ಷಕರು Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡುತ್ತಾರೆ. ಜಾಹೀರಾತು ಇಲ್ಲ, 12 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ. ಇಲ್ಲಿ ತೆರೆಯಿರಿ: {url}",
    demo_teacher: 'ಡೆಮೊ ಶಿಕ್ಷಕ',
    signin_title: 'Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ — ಶಿಕ್ಷಕರಿಗೆ ಉಚಿತ',
    signin_text: 'ನಿಮ್ಮ ಕ್ವಿಜ್‌ಗಳು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿಯುತ್ತವೆ, ಆದ್ದರಿಂದ ಯಾವುದೇ ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ ಬಳಸಬಹುದು. ವಿದ್ಯಾರ್ಥಿಗಳು ಎಂದಿಗೂ ಸೈನ್ ಇನ್ ಮಾಡುವುದಿಲ್ಲ: ಕೋಡ್ ಮತ್ತು ಅಡ್ಡಹೆಸರಿನಿಂದ ಸೇರುತ್ತಾರೆ.',
    signin_google: 'Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signin_demo: 'ಈಗಲೇ ಡೆಮೊ ಮೋಡ್‌ನಲ್ಲಿ ಪ್ರಯತ್ನಿಸಿ',
    inapp_hint: 'WhatsApp ನಂತಹ ಆ್ಯಪ್‌ಗಳ ಒಳಗೆ Google ಸೈನ್-ಇನ್ ಕೆಲಸ ಮಾಡುವುದಿಲ್ಲ. ಈ ಪುಟವನ್ನು Chrome ನಲ್ಲಿ ತೆರೆಯಿರಿ.',
    use_demo: 'ಬದಲಿಗೆ ಡೆಮೊ ಮೋಡ್ ಬಳಸಿ',
    hello: 'ನಮಸ್ಕಾರ, {name}',
    new_quiz: 'ಹೊಸ ಕ್ವಿಜ್',
    import_qm: 'ಈ ಸಾಧನದ ಕ್ವಿಜ್ ಮೇಕರ್‌ನಿಂದ ತನ್ನಿ',
    import_file: 'JSON / CSV ಆಮದು ಮಾಡಿ',
    import_hint: 'CSV ಕಾಲಮ್‌ಗಳು: ಪ್ರಶ್ನೆ, ಆಯ್ಕೆ 1 ರಿಂದ ಆಯ್ಕೆ 6, ಸರಿಯಾದ ಉತ್ತರ (1–6 ಅಥವಾ A–F), ವಿವರಣೆ.',
    settings_title: 'ಲೈವ್ ಕ್ವಿಜ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    time_per_q: 'ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ ಸಮಯ',
    sec: '{n} ಸೆಕೆಂಡ್',
    shuffle_q: 'ಪ್ರಶ್ನೆಗಳ ಕ್ರಮ ಬದಲಿಸಿ',
    shuffle_o: 'ಆಯ್ಕೆಗಳ ಕ್ರಮ ಬದಲಿಸಿ',
    my_quizzes: 'ನನ್ನ ಕ್ವಿಜ್‌ಗಳು',
    sample_badge: 'ಮಾದರಿ',
    n_questions: '{n} ಪ್ರಶ್ನೆಗಳು',
    host: 'ಲೈವ್ ನಡೆಸಿ',
    edit_copy: 'ನಕಲು ಮಾಡಿ ಬದಲಿಸಿ',
    no_quizzes: 'ಇನ್ನೂ ನಿಮ್ಮದೇ ಆದ ಕ್ವಿಜ್ ಇಲ್ಲ. ಹೊಸ ಕ್ವಿಜ್ ಮಾಡಿ, ಆಮದು ಮಾಡಿ ಅಥವಾ ಮಾದರಿ ಕ್ವಿಜ್ ನಡೆಸಿ.',
    confirm_delete_quiz: '"{title}" ಕ್ವಿಜ್ ಅನ್ನು ಅಳಿಸಬೇಕೇ?',
    deleted: 'ಅಳಿಸಲಾಗಿದೆ.',
    past_sessions: 'ಹಿಂದಿನ ಸೆಷನ್‌ಗಳು',
    no_sessions: 'ಇನ್ನೂ ಸೆಷನ್‌ಗಳಿಲ್ಲ. ಒಂದು ಕ್ವಿಜ್ ನಡೆಸಿ, ಅದರ ಫಲಿತಾಂಶ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
    keep_note: 'ಫಲಿತಾಂಶಗಳು 30 ದಿನಗಳ ನಂತರ ಅಳಿಸಿಹೋಗುತ್ತವೆ. ಉಳಿಸಿಕೊಳ್ಳಲು CSV ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    players_n: '{n} ಆಟಗಾರರು',
    code_n: 'ಕೋಡ್ {code}',
    state_lobby: 'ಕಾಯುತ್ತಿದೆ',
    state_live: 'ಲೈವ್',
    state_ended: 'ಮುಗಿದಿದೆ',
    results: 'ಫಲಿತಾಂಶ',
    resume: 'ಮುಂದುವರಿಸಿ',
    confirm_delete_session: 'ಈ ಸೆಷನ್ ಅನ್ನು ಅದರ ಎಲ್ಲ ಉತ್ತರಗಳೊಂದಿಗೆ ಅಳಿಸಬೇಕೇ?',
    account: 'ನಿಮ್ಮ ಖಾತೆ',
    sign_out: 'ಸೈನ್ ಔಟ್',
    delete_account: 'ನನ್ನ ಖಾತೆ ಮತ್ತು ಡೇಟಾ ಅಳಿಸಿ',
    delete_account_text: 'ಇದು ನಿಮ್ಮ ಶಿಕ್ಷಕ ಖಾತೆ, ನಿಮ್ಮ ಎಲ್ಲ ಕ್ವಿಜ್‌ಗಳು ಮತ್ತು ಸೆಷನ್‌ಗಳು, ಹಾಗೂ ಅವುಗಳಲ್ಲಿನ ವಿದ್ಯಾರ್ಥಿಗಳ ಎಲ್ಲ ಅಡ್ಡಹೆಸರು ಮತ್ತು ಉತ್ತರಗಳನ್ನು ಅಳಿಸುತ್ತದೆ. ಇದನ್ನು ಮರಳಿ ಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.',
    delete_account_tip: 'ಇದನ್ನು ಮಾಡುವ ಮೊದಲು, ಉಳಿಸಿಕೊಳ್ಳಬೇಕಾದ ಫಲಿತಾಂಶಗಳ CSV ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    delete_account_check: 'ನನಗೆ ಅರ್ಥವಾಗಿದೆ. ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ.',
    delete_forever: 'ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',
    account_deleted: 'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಅದರ ಎಲ್ಲ ಡೇಟಾ ಅಳಿಸಲಾಗಿದೆ.',
    privacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    terms: 'ಬಳಕೆಯ ನಿಯಮಗಳು',
    data_cloud: 'ನಿಮ್ಮ ಕ್ವಿಜ್‌ಗಳು ಮತ್ತು ಫಲಿತಾಂಶಗಳು Google Firebase (ಮುಂಬೈ) ನಲ್ಲಿ ಇರುತ್ತವೆ. ವಿದ್ಯಾರ್ಥಿಗಳು ಅಡ್ಡಹೆಸರನ್ನು ಮಾತ್ರ ಕೊಡುತ್ತಾರೆ.',
    data_demo: 'ಡೆಮೊ ಮೋಡ್‌ನಲ್ಲಿ ಎಲ್ಲವೂ ಈ ಬ್ರೌಸರ್‌ನಲ್ಲೇ ಇರುತ್ತದೆ.',
    edit_quiz: 'ಕ್ವಿಜ್ ಬದಲಿಸಿ',
    quiz_title: 'ಕ್ವಿಜ್ ಹೆಸರು',
    question_n: 'ಪ್ರಶ್ನೆ {n}',
    option_n: 'ಆಯ್ಕೆ {n}',
    tick_correct: 'ಸರಿಯಾದ ಉತ್ತರಕ್ಕೆ ಟಿಕ್ ಮಾಡಿ.',
    mark_correct: 'ಆಯ್ಕೆ {n} ಸರಿಯಾದ ಉತ್ತರ',
    add_option: 'ಆಯ್ಕೆ ಸೇರಿಸಿ',
    remove_option: 'ಆಯ್ಕೆ {n} ತೆಗೆದುಹಾಕಿ',
    explain_label: 'ವಿವರಣೆ (ಬೇಕಿದ್ದರೆ, ಉತ್ತರದ ನಂತರ ತೋರಿಸುತ್ತದೆ)',
    time_label: 'ಸಮಯ ಸೆಕೆಂಡುಗಳಲ್ಲಿ (ಬೇಕಿದ್ದರೆ)',
    time_ph: 'ಡೀಫಾಲ್ಟ್',
    add_question: 'ಪ್ರಶ್ನೆ ಸೇರಿಸಿ',
    move_up: 'ಪ್ರಶ್ನೆ {n} ಮೇಲಕ್ಕೆ ಸರಿಸಿ',
    move_down: 'ಪ್ರಶ್ನೆ {n} ಕೆಳಕ್ಕೆ ಸರಿಸಿ',
    delete_question: 'ಪ್ರಶ್ನೆ {n} ಅಳಿಸಿ',
    save_quiz: 'ಕ್ವಿಜ್ ಉಳಿಸಿ',
    saved: 'ಉಳಿಸಲಾಗಿದೆ.',
    err_title: 'ದಯವಿಟ್ಟು ಕ್ವಿಜ್‌ಗೆ ಹೆಸರು ಬರೆಯಿರಿ.',
    err_no_questions: 'ಕನಿಷ್ಠ ಒಂದು ಪ್ರಶ್ನೆ ಸೇರಿಸಿ.',
    err_q_text: 'ಪ್ರಶ್ನೆ {n}: ದಯವಿಟ್ಟು ಪ್ರಶ್ನೆ ಬರೆಯಿರಿ.',
    err_q_options: 'ಪ್ರಶ್ನೆ {n}: ಕನಿಷ್ಠ 2 ಆಯ್ಕೆಗಳನ್ನು ಬರೆಯಿರಿ.',
    err_q_correct: 'ಪ್ರಶ್ನೆ {n}: ಸರಿಯಾದ ಉತ್ತರಕ್ಕೆ ಟಿಕ್ ಮಾಡಿ.',
    draft_restored: 'ಉಳಿಸದ ನಿಮ್ಮ ಬದಲಾವಣೆಗಳನ್ನು ಮರಳಿ ತರಲಾಗಿದೆ.',
    confirm_discard: 'ನಿಮ್ಮ ಬದಲಾವಣೆಗಳನ್ನು ಬಿಟ್ಟುಬಿಡಬೇಕೇ?',
    untitled: 'ಹೆಸರಿಲ್ಲದ ಕ್ವಿಜ್',
    opt_true: 'ಸರಿ',
    opt_false: 'ತಪ್ಪು',
    qm_title: 'ಕ್ವಿಜ್ ಮೇಕರ್‌ನಲ್ಲಿ ಉಳಿಸಿದ ಕ್ವಿಜ್‌ಗಳು',
    qm_none: 'ಈ ಸಾಧನದಲ್ಲಿ ಕ್ವಿಜ್ ಮೇಕರ್‌ನ ಯಾವುದೇ ಕ್ವಿಜ್ ಸಿಗಲಿಲ್ಲ.',
    open_qm: 'ಕ್ವಿಜ್ ಮೇಕರ್ ತೆರೆಯಿರಿ',
    import_selected: 'ಆಯ್ಕೆ ಮಾಡಿದವನ್ನು ಆಮದು ಮಾಡಿ',
    imported_n: '{n} ಕ್ವಿಜ್‌ಗಳನ್ನು ಆಮದು ಮಾಡಲಾಗಿದೆ.',
    skipped_n: '{n} ಪ್ರಶ್ನೆಗಳನ್ನು ಬಿಡಲಾಗಿದೆ.',
    import_failed: 'ಈ ಫೈಲ್ ಓದಲು ಆಗಲಿಲ್ಲ. ಕ್ವಿಜ್ ಮೇಕರ್‌ನ JSON ಅಥವಾ CSV ಫೈಲ್ ಬಳಸಿ.',
    join_line: '{url} ಗೆ ಹೋಗಿ ಈ ಕೋಡ್ ಟೈಪ್ ಮಾಡಿ:',
    scan_qr: 'ಅಥವಾ ಈ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    qr_offline: 'QR ಕೋಡ್‌ಗೆ ಇಂಟರ್ನೆಟ್ ಬೇಕು. ವಿದ್ಯಾರ್ಥಿಗಳು ಕೋಡ್ ಟೈಪ್ ಮಾಡಬಹುದು.',
    waiting_players: 'ವಿದ್ಯಾರ್ಥಿಗಳು ಸೇರುವುದಕ್ಕಾಗಿ ಕಾಯುತ್ತಿದ್ದೇವೆ…',
    joined_n: '{n} ಮಂದಿ ಸೇರಿದ್ದಾರೆ',
    lock: 'ಲಾಕ್ ಮಾಡಿ',
    unlock: 'ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    locked_note: 'ಲಾಕ್ ಆಗಿದೆ: ಹೊಸಬರು ಯಾರೂ ಸೇರಲಾಗದು.',
    kick: '{name} ಅವರನ್ನು ತೆಗೆದುಹಾಕಿ',
    confirm_kick: '{name} ಅವರನ್ನು ಈ ಕ್ವಿಜ್‌ನಿಂದ ತೆಗೆದುಹಾಕಬೇಕೇ? ಅವರು ಮತ್ತೆ ಸೇರಲಾಗುವುದಿಲ್ಲ.',
    start_quiz: 'ಕ್ವಿಜ್ ಪ್ರಾರಂಭಿಸಿ',
    need_player: 'ಮೊದಲು ಕನಿಷ್ಠ ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿ ಸೇರಬೇಕು.',
    open_student: 'ವಿದ್ಯಾರ್ಥಿ ಟ್ಯಾಬ್ ತೆರೆಯಿರಿ',
    question_of: 'ಪ್ರಶ್ನೆ {n} / {total}',
    answered_n: '{total} ಮಂದಿಯಲ್ಲಿ {n} ಮಂದಿ ಉತ್ತರಿಸಿದ್ದಾರೆ',
    show_answer: 'ಉತ್ತರ ತೋರಿಸಿ',
    skip_q: 'ಪ್ರಶ್ನೆ ಬಿಟ್ಟುಬಿಡಿ',
    time_up: 'ಸಮಯ ಮುಗಿಯಿತು!',
    all_answered: 'ಎಲ್ಲರೂ ಉತ್ತರಿಸಿದ್ದಾರೆ!',
    leaderboard: 'ಲೀಡರ್‌ಬೋರ್ಡ್',
    next_question: 'ಮುಂದಿನ ಪ್ರಶ್ನೆ',
    final_results: 'ಅಂತಿಮ ಫಲಿತಾಂಶ',
    end_quiz: 'ಕ್ವಿಜ್ ಮುಗಿಸಿ',
    confirm_end: 'ಕ್ವಿಜ್ ಅನ್ನು ಈಗಲೇ ಮುಗಿಸಿ ಅಂತಿಮ ಫಲಿತಾಂಶ ತೋರಿಸಬೇಕೇ?',
    correct_answer: 'ಸರಿಯಾದ ಉತ್ತರ',
    points_n: '{n} ಅಂಕಗಳು',
    col_rank: 'ಸ್ಥಾನ',
    col_nick: 'ಅಡ್ಡಹೆಸರು',
    col_correct: 'ಸರಿಯಾದ ಉತ್ತರಗಳು',
    col_q: 'ಪ್ರ{n}',
    col_question: 'ಪ್ರಶ್ನೆ',
    export_csv: 'CSV ರಫ್ತು ಮಾಡಿ',
    host_again: 'ಮತ್ತೆ ನಡೆಸಿ',
    back_dash: 'ನನ್ನ ಕ್ವಿಜ್‌ಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    session_gone: 'ಈ ಕ್ವಿಜ್ ಸೆಷನ್ ಈಗ ಇಲ್ಲ.',
    nobody_joined: 'ಈ ಕ್ವಿಜ್‌ಗೆ ಯಾರೂ ಸೇರಲಿಲ್ಲ.',
    keys_hint: 'ಕೀಬೋರ್ಡ್: ಮುಂದಕ್ಕೆ Space ಅಥವಾ →',
    offline_banner: 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಇಲ್ಲ. ವಿದ್ಯಾರ್ಥಿಗಳ ಉತ್ತರಗಳು ತಲುಪದೇ ಇರಬಹುದು.',
    connecting: 'ಸಂಪರ್ಕಿಸುತ್ತಿದೆ…',
    err_not_configured: 'ಆನ್‌ಲೈನ್ ಕ್ವಿಜ್ ಇನ್ನೂ ಸಿದ್ಧವಾಗಿಲ್ಲ. ಡೆಮೊ ಮೋಡ್ ಪ್ರಯತ್ನಿಸಿ.',
    err_offline: 'ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ. ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    err_quota_exceeded: 'ಇಂದಿನ ಉಚಿತ ಮಿತಿ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ನಾಳೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ಡೆಮೊ ಮೋಡ್ ಬಳಸಿ.',
    err_not_found: 'ಸಿಗಲಿಲ್ಲ. ಬಹುಶಃ ಅಳಿಸಲಾಗಿದೆ.',
    err_permission_denied: 'ಇದನ್ನು ಮಾಡಲು ನಿಮಗೆ ಅನುಮತಿ ಇಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    err_session_locked: 'ಈ ಕ್ವಿಜ್ ಲಾಕ್ ಆಗಿದೆ.',
    err_session_ended: 'ಈ ಕ್ವಿಜ್ ಮುಗಿದಿದೆ.',
    err_name_taken: 'ಈ ಅಡ್ಡಹೆಸರನ್ನು ಬೇರೆ ಯಾರೋ ಬಳಸುತ್ತಿದ್ದಾರೆ.',
    err_invalid_input: 'ದಯವಿಟ್ಟು ನೀವು ಬರೆದದ್ದನ್ನು ಪರಿಶೀಲಿಸಿ.',
    err_unknown: 'ಏನೋ ತಪ್ಪಾಯಿತು. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ · ತರಗತಿಗೆ ಉಪಾಯಗಳು',
    help_1: 'ಸೈನ್ ಇನ್ ಮಾಡಿ ಮಾದರಿ ಕ್ವಿಜ್‌ನಲ್ಲಿ "ಲೈವ್ ನಡೆಸಿ" ಒತ್ತಿ, 10 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ತಿಳಿಯುತ್ತದೆ.',
    help_2: 'ಪರದೆಯನ್ನು ಪ್ರೊಜೆಕ್ಟರ್‌ನಲ್ಲಿ ತೋರಿಸಿ. ವಿದ್ಯಾರ್ಥಿಗಳು ಫೋನ್‌ನಲ್ಲಿ apnipathshala.ai/join ತೆರೆದು ಕೋಡ್ ಮತ್ತು ಅಡ್ಡಹೆಸರು ಹಾಕುತ್ತಾರೆ.',
    help_3: 'ಪೂರ್ಣ ಹೆಸರಲ್ಲ, ಅಡ್ಡಹೆಸರು ಬಳಸಲು ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಹೇಳಿ. ✕ ಮೂಲಕ ಯಾರನ್ನಾದರೂ ತೆಗೆಯಬಹುದು, ಎಲ್ಲರೂ ಸೇರಿದ ಮೇಲೆ ಲಾಕ್ ಒತ್ತಿ.',
    help_4: 'ಸರಿಯಾದ ಉತ್ತರಕ್ಕೆ 500 ರಿಂದ 1000 ಅಂಕ: ಎಷ್ಟು ಬೇಗವೋ ಅಷ್ಟು ಹೆಚ್ಚು. ತಪ್ಪು ಉತ್ತರಕ್ಕೆ 0.',
    help_5: 'ತರಗತಿ ಉಪಾಯ: ಪಾಠದ ಕೊನೆಯಲ್ಲಿ 3 ಜನರ ಗುಂಪುಗಳು ಒಂದೇ ಫೋನ್‌ನಲ್ಲಿ ಚರ್ಚಿಸಿ ಉತ್ತರಿಸಲಿ.',
    help_6: 'ಕ್ವಿಜ್ ಮೇಕರ್‌ನಲ್ಲಿ ಕ್ವಿಜ್ ಮಾಡಿ ಇಲ್ಲಿ ಆಮದು ಮಾಡಿ, ಅಥವಾ ಹೊಸದನ್ನು ಬರೆಯಿರಿ. ದಾಖಲೆಗಾಗಿ ಫಲಿತಾಂಶಗಳನ್ನು CSV ಆಗಿ ರಫ್ತು ಮಾಡಿ.'
  },
  ml: {
    app_title: 'ലൈവ് ക്ലാസ് ക്വിസ്',
    intro: 'പ്രൊജക്ടറിൽ ലൈവ് ക്വിസ് നടത്തൂ. ഓൺലൈനായി നടത്താൻ Google വഴി സൈൻ ഇൻ ചെയ്യുക. വിദ്യാർത്ഥികൾ ഫോണിൽ കോഡും വിളിപ്പേരും നൽകി ചേരുന്നു (സൈൻ-അപ്പ് വേണ്ട), ഓരോ ചോദ്യത്തിനും ഉത്തരം നൽകുന്നു, ആരാണ് മുന്നിലെന്ന് കാണുന്നു.',
    demo_banner: 'ഡെമോ മോഡ്: ഇത് ഈ ഒരു ഉപകരണത്തിൽ മാത്രമേ പ്രവർത്തിക്കൂ. പരീക്ഷിക്കാൻ വിദ്യാർത്ഥിയുടെ പേജ് മറ്റൊരു ടാബിൽ തുറക്കുക. വിദ്യാർത്ഥികളുടെ ഫോണുകളിൽ കളിക്കാൻ apnipathshala.ai/teacher തുറന്ന് Google വഴി സൈൻ ഇൻ ചെയ്യുക.',
    shell_wa_msg: "{title}: നിങ്ങളുടെ ക്ലാസിനുള്ള സൗജന്യ ലൈവ് ക്വിസ്. വിദ്യാർത്ഥികൾ ഫോണിൽ കോഡും വിളിപ്പേരും നൽകി ചേരുന്നു, സൈൻ-അപ്പ് വേണ്ട; അധ്യാപകർ Google വഴി സൈൻ ഇൻ ചെയ്യുന്നു. പരസ്യമില്ല, 12 ഇന്ത്യൻ ഭാഷകളിൽ. ഇവിടെ തുറക്കൂ: {url}",
    demo_teacher: 'ഡെമോ അധ്യാപകൻ',
    signin_title: 'Google ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യൂ — അധ്യാപകർക്ക് സൗജന്യം',
    signin_text: 'നിങ്ങളുടെ ക്വിസുകൾ ഓൺലൈനായി സേവ് ചെയ്യപ്പെടും, അതിനാൽ ഏത് കമ്പ്യൂട്ടറിലും ഉപയോഗിക്കാം. വിദ്യാർത്ഥികൾ ഒരിക്കലും സൈൻ ഇൻ ചെയ്യേണ്ടതില്ല: കോഡും വിളിപ്പേരും കൊണ്ടാണ് അവർ ചേരുന്നത്.',
    signin_google: 'Google ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക',
    signin_demo: 'ഇപ്പോൾത്തന്നെ ഡെമോ മോഡിൽ പരീക്ഷിക്കുക',
    inapp_hint: 'WhatsApp പോലുള്ള ആപ്പുകൾക്കുള്ളിൽ Google സൈൻ-ഇൻ പ്രവർത്തിക്കില്ല. ഈ പേജ് Chrome-ൽ തുറക്കുക.',
    use_demo: 'പകരം ഡെമോ മോഡ് ഉപയോഗിക്കുക',
    hello: 'നമസ്കാരം, {name}',
    new_quiz: 'പുതിയ ക്വിസ്',
    import_qm: 'ഈ ഉപകരണത്തിലെ ക്വിസ് മേക്കറിൽ നിന്ന് കൊണ്ടുവരിക',
    import_file: 'JSON / CSV ഇമ്പോർട്ട് ചെയ്യുക',
    import_hint: 'CSV കോളങ്ങൾ: ചോദ്യം, ഓപ്ഷൻ 1 മുതൽ ഓപ്ഷൻ 6 വരെ, ശരിയുത്തരം (1–6 അല്ലെങ്കിൽ A–F), വിശദീകരണം.',
    settings_title: 'ലൈവ് ക്വിസ് ക്രമീകരണങ്ങൾ',
    time_per_q: 'ഓരോ ചോദ്യത്തിനുമുള്ള സമയം',
    sec: '{n} സെക്കൻഡ്',
    shuffle_q: 'ചോദ്യങ്ങളുടെ ക്രമം മാറ്റുക',
    shuffle_o: 'ഓപ്ഷനുകളുടെ ക്രമം മാറ്റുക',
    my_quizzes: 'എന്റെ ക്വിസുകൾ',
    sample_badge: 'മാതൃക',
    n_questions: '{n} ചോദ്യങ്ങൾ',
    host: 'ലൈവായി നടത്തുക',
    edit_copy: 'പകർപ്പെടുത്ത് തിരുത്തുക',
    no_quizzes: 'ഇതുവരെ നിങ്ങളുടേതായ ക്വിസ് ഇല്ല. പുതിയ ക്വിസ് ഉണ്ടാക്കുക, ഇമ്പോർട്ട് ചെയ്യുക, അല്ലെങ്കിൽ മാതൃകാ ക്വിസ് നടത്തുക.',
    confirm_delete_quiz: '"{title}" എന്ന ക്വിസ് ഇല്ലാതാക്കണോ?',
    deleted: 'ഇല്ലാതാക്കി.',
    past_sessions: 'മുൻ സെഷനുകൾ',
    no_sessions: 'ഇതുവരെ സെഷനുകളൊന്നുമില്ല. ഒരു ക്വിസ് നടത്തൂ, അതിന്റെ ഫലങ്ങൾ ഇവിടെ കാണാം.',
    keep_note: 'ഫലങ്ങൾ 30 ദിവസത്തിനു ശേഷം മായ്ക്കപ്പെടും. സൂക്ഷിക്കാൻ CSV ഡൗൺലോഡ് ചെയ്യുക.',
    players_n: '{n} കളിക്കാർ',
    code_n: 'കോഡ് {code}',
    state_lobby: 'കാത്തിരിക്കുന്നു',
    state_live: 'ലൈവ്',
    state_ended: 'കഴിഞ്ഞു',
    results: 'ഫലങ്ങൾ',
    resume: 'തുടരുക',
    confirm_delete_session: 'ഈ സെഷൻ അതിലെ എല്ലാ ഉത്തരങ്ങളോടും കൂടി ഇല്ലാതാക്കണോ?',
    account: 'നിങ്ങളുടെ അക്കൗണ്ട്',
    sign_out: 'സൈൻ ഔട്ട്',
    delete_account: 'എന്റെ അക്കൗണ്ടും ഡാറ്റയും ഇല്ലാതാക്കുക',
    delete_account_text: 'ഇത് നിങ്ങളുടെ അധ്യാപക അക്കൗണ്ട്, നിങ്ങളുടെ എല്ലാ ക്വിസുകളും സെഷനുകളും, അവയിലെ വിദ്യാർത്ഥികളുടെ എല്ലാ വിളിപ്പേരുകളും ഉത്തരങ്ങളും ഇല്ലാതാക്കും. ഇത് തിരികെ കൊണ്ടുവരാനാവില്ല.',
    delete_account_tip: 'ഇത് ചെയ്യുന്നതിനു മുമ്പ്, സൂക്ഷിക്കേണ്ട ഫലങ്ങളുടെ CSV ഡൗൺലോഡ് ചെയ്യുക.',
    delete_account_check: 'എനിക്ക് മനസ്സിലായി. എല്ലാം ഇല്ലാതാക്കുക.',
    delete_forever: 'എന്നേക്കുമായി ഇല്ലാതാക്കുക',
    account_deleted: 'നിങ്ങളുടെ അക്കൗണ്ടും അതിലെ എല്ലാ ഡാറ്റയും ഇല്ലാതാക്കി.',
    privacy: 'സ്വകാര്യതാ നയം',
    terms: 'ഉപയോഗ നിബന്ധനകൾ',
    data_cloud: 'നിങ്ങളുടെ ക്വിസുകളും ഫലങ്ങളും Google Firebase-ൽ (മുംബൈ) സൂക്ഷിക്കുന്നു. വിദ്യാർത്ഥികൾ വിളിപ്പേര് മാത്രമേ നൽകുന്നുള്ളൂ.',
    data_demo: 'ഡെമോ മോഡിൽ എല്ലാം ഈ ബ്രൗസറിൽ മാത്രം നിൽക്കും.',
    edit_quiz: 'ക്വിസ് തിരുത്തുക',
    quiz_title: 'ക്വിസിന്റെ പേര്',
    question_n: 'ചോദ്യം {n}',
    option_n: 'ഓപ്ഷൻ {n}',
    tick_correct: 'ശരിയുത്തരം ടിക്ക് ചെയ്യുക.',
    mark_correct: 'ഓപ്ഷൻ {n} ആണ് ശരിയുത്തരം',
    add_option: 'ഓപ്ഷൻ ചേർക്കുക',
    remove_option: 'ഓപ്ഷൻ {n} നീക്കുക',
    explain_label: 'വിശദീകരണം (വേണമെങ്കിൽ, ഉത്തരത്തിനു ശേഷം കാണിക്കും)',
    time_label: 'സമയം സെക്കൻഡിൽ (വേണമെങ്കിൽ)',
    time_ph: 'ഡിഫോൾട്ട്',
    add_question: 'ചോദ്യം ചേർക്കുക',
    move_up: 'ചോദ്യം {n} മുകളിലേക്ക് നീക്കുക',
    move_down: 'ചോദ്യം {n} താഴേക്ക് നീക്കുക',
    delete_question: 'ചോദ്യം {n} ഇല്ലാതാക്കുക',
    save_quiz: 'ക്വിസ് സേവ് ചെയ്യുക',
    saved: 'സേവ് ചെയ്തു.',
    err_title: 'ദയവായി ക്വിസിന് ഒരു പേര് എഴുതുക.',
    err_no_questions: 'കുറഞ്ഞത് ഒരു ചോദ്യമെങ്കിലും ചേർക്കുക.',
    err_q_text: 'ചോദ്യം {n}: ദയവായി ചോദ്യം എഴുതുക.',
    err_q_options: 'ചോദ്യം {n}: കുറഞ്ഞത് 2 ഓപ്ഷനുകൾ എഴുതുക.',
    err_q_correct: 'ചോദ്യം {n}: ശരിയുത്തരം ടിക്ക് ചെയ്യുക.',
    draft_restored: 'സേവ് ചെയ്യാത്ത നിങ്ങളുടെ മാറ്റങ്ങൾ തിരികെ കൊണ്ടുവന്നു.',
    confirm_discard: 'നിങ്ങളുടെ മാറ്റങ്ങൾ ഉപേക്ഷിക്കണോ?',
    untitled: 'പേരില്ലാത്ത ക്വിസ്',
    opt_true: 'ശരി',
    opt_false: 'തെറ്റ്',
    qm_title: 'ക്വിസ് മേക്കറിൽ സേവ് ചെയ്ത ക്വിസുകൾ',
    qm_none: 'ഈ ഉപകരണത്തിൽ ക്വിസ് മേക്കറിന്റെ ക്വിസുകളൊന്നും കണ്ടില്ല.',
    open_qm: 'ക്വിസ് മേക്കർ തുറക്കുക',
    import_selected: 'തിരഞ്ഞെടുത്തവ ഇമ്പോർട്ട് ചെയ്യുക',
    imported_n: '{n} ക്വിസുകൾ ഇമ്പോർട്ട് ചെയ്തു.',
    skipped_n: '{n} ചോദ്യങ്ങൾ ഒഴിവാക്കി.',
    import_failed: 'ഈ ഫയൽ വായിക്കാനായില്ല. ക്വിസ് മേക്കറിന്റെ JSON അല്ലെങ്കിൽ CSV ഫയൽ ഉപയോഗിക്കുക.',
    join_line: '{url} തുറന്ന് ഈ കോഡ് ടൈപ്പ് ചെയ്യുക:',
    scan_qr: 'അല്ലെങ്കിൽ ഈ QR കോഡ് സ്കാൻ ചെയ്യുക',
    qr_offline: 'QR കോഡിന് ഇന്റർനെറ്റ് വേണം. വിദ്യാർത്ഥികൾക്ക് കോഡ് ടൈപ്പ് ചെയ്യാം.',
    waiting_players: 'വിദ്യാർത്ഥികൾ ചേരുന്നതിനായി കാത്തിരിക്കുന്നു…',
    joined_n: '{n} പേർ ചേർന്നു',
    lock: 'ലോക്ക് ചെയ്യുക',
    unlock: 'അൺലോക്ക് ചെയ്യുക',
    locked_note: 'ലോക്ക് ചെയ്തു: ഇനി പുതുതായി ആർക്കും ചേരാനാവില്ല.',
    kick: '{name}-നെ നീക്കുക',
    confirm_kick: '{name}-നെ ഈ ക്വിസിൽ നിന്ന് നീക്കണോ? അവർക്ക് വീണ്ടും ചേരാനാവില്ല.',
    start_quiz: 'ക്വിസ് തുടങ്ങുക',
    need_player: 'ആദ്യം കുറഞ്ഞത് ഒരു വിദ്യാർത്ഥിയെങ്കിലും ചേരണം.',
    open_student: 'വിദ്യാർത്ഥി ടാബ് തുറക്കുക',
    question_of: 'ചോദ്യം {n} / {total}',
    answered_n: '{total} പേരിൽ {n} പേർ ഉത്തരം നൽകി',
    show_answer: 'ഉത്തരം കാണിക്കുക',
    skip_q: 'ചോദ്യം ഒഴിവാക്കുക',
    time_up: 'സമയം കഴിഞ്ഞു!',
    all_answered: 'എല്ലാവരും ഉത്തരം നൽകി!',
    leaderboard: 'ലീഡർബോർഡ്',
    next_question: 'അടുത്ത ചോദ്യം',
    final_results: 'അന്തിമ ഫലങ്ങൾ',
    end_quiz: 'ക്വിസ് അവസാനിപ്പിക്കുക',
    confirm_end: 'ക്വിസ് ഇപ്പോൾത്തന്നെ അവസാനിപ്പിച്ച് അന്തിമ ഫലങ്ങൾ കാണിക്കണോ?',
    correct_answer: 'ശരിയുത്തരം',
    points_n: '{n} പോയിന്റ്',
    col_rank: 'റാങ്ക്',
    col_nick: 'വിളിപ്പേര്',
    col_correct: 'ശരിയുത്തരങ്ങൾ',
    col_q: 'ചോ{n}',
    col_question: 'ചോദ്യം',
    export_csv: 'CSV എക്സ്പോർട്ട് ചെയ്യുക',
    host_again: 'വീണ്ടും നടത്തുക',
    back_dash: 'എന്റെ ക്വിസുകളിലേക്ക് മടങ്ങുക',
    session_gone: 'ഈ ക്വിസ് സെഷൻ ഇപ്പോൾ നിലവിലില്ല.',
    nobody_joined: 'ഈ ക്വിസിൽ ആരും ചേർന്നില്ല.',
    keys_hint: 'കീബോർഡ്: അടുത്തതിന് Space അല്ലെങ്കിൽ →',
    offline_banner: 'ഇന്റർനെറ്റ് കണക്ഷനില്ല. വിദ്യാർത്ഥികളുടെ ഉത്തരങ്ങൾ എത്തിയേക്കില്ല.',
    connecting: 'കണക്റ്റ് ചെയ്യുന്നു…',
    err_not_configured: 'ഓൺലൈൻ ക്വിസ് ഇതുവരെ സജ്ജമായിട്ടില്ല. ഡെമോ മോഡ് പരീക്ഷിക്കുക.',
    err_offline: 'ഇന്റർനെറ്റില്ല. കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    err_quota_exceeded: 'ഇന്നത്തെ സൗജന്യ പരിധി കഴിഞ്ഞു. ദയവായി നാളെ വീണ്ടും ശ്രമിക്കുക, അല്ലെങ്കിൽ ഡെമോ മോഡ് ഉപയോഗിക്കുക.',
    err_not_found: 'കണ്ടെത്തിയില്ല. ഒരുപക്ഷേ ഇല്ലാതാക്കിയിരിക്കാം.',
    err_permission_denied: 'ഇത് ചെയ്യാൻ നിങ്ങൾക്ക് അനുമതിയില്ല. ദയവായി വീണ്ടും സൈൻ ഇൻ ചെയ്യുക.',
    err_session_locked: 'ഈ ക്വിസ് ലോക്ക് ചെയ്തിരിക്കുന്നു.',
    err_session_ended: 'ഈ ക്വിസ് അവസാനിച്ചു.',
    err_name_taken: 'ഈ വിളിപ്പേര് മറ്റാരോ ഉപയോഗിക്കുന്നു.',
    err_invalid_input: 'നിങ്ങൾ എഴുതിയത് ദയവായി പരിശോധിക്കുക.',
    err_unknown: 'എന്തോ കുഴപ്പം സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം · ക്ലാസിനുള്ള ആശയങ്ങൾ',
    help_1: 'സൈൻ ഇൻ ചെയ്ത് മാതൃകാ ക്വിസിൽ "ലൈവായി നടത്തുക" അമർത്തൂ, 10 സെക്കൻഡിൽ ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നുവെന്ന് മനസ്സിലാകും.',
    help_2: 'സ്ക്രീൻ പ്രൊജക്ടറിൽ കാണിക്കുക. വിദ്യാർത്ഥികൾ ഫോണിൽ apnipathshala.ai/join തുറന്ന് കോഡും വിളിപ്പേരും ടൈപ്പ് ചെയ്യും.',
    help_3: 'മുഴുവൻ പേരല്ല, വിളിപ്പേര് ഉപയോഗിക്കാൻ വിദ്യാർത്ഥികളോട് പറയുക. ✕ ഉപയോഗിച്ച് ആരെയും നീക്കാം, എല്ലാവരും എത്തിയാൽ ലോക്ക് അമർത്തുക.',
    help_4: 'ശരിയുത്തരത്തിന് 500 മുതൽ 1000 വരെ പോയിന്റ്: എത്ര വേഗമോ അത്ര കൂടുതൽ. തെറ്റായ ഉത്തരത്തിന് 0.',
    help_5: 'ക്ലാസ് ആശയം: പാഠത്തിന്റെ അവസാനം 3 പേരുള്ള ഗ്രൂപ്പുകൾ ഒരു ഫോണിൽ ചർച്ച ചെയ്ത് ഉത്തരം നൽകട്ടെ.',
    help_6: 'ക്വിസ് മേക്കറിൽ ക്വിസ് ഉണ്ടാക്കി ഇവിടെ ഇമ്പോർട്ട് ചെയ്യുക, അല്ലെങ്കിൽ പുതിയത് എഴുതുക. രേഖകൾക്കായി ഫലങ്ങൾ CSV ആയി എക്സ്പോർട്ട് ചെയ്യുക.'
  },
  ur: {
    app_title: 'لائیو کلاس کوئز',
    intro: 'پروجیکٹر پر لائیو کوئز چلائیں۔ آن لائن چلانے کے لیے Google سے سائن اِن کریں۔ طلبہ اپنے فون پر کوڈ اور عرفی نام ڈال کر شامل ہوتے ہیں (کوئی سائن اپ نہیں)، ہر سوال کا جواب دیتے ہیں اور دیکھتے ہیں کہ کون سب سے آگے ہے۔',
    demo_banner: 'ڈیمو موڈ: یہ صرف اسی ایک آلے پر چلتا ہے۔ آزمانے کے لیے طلبہ والا صفحہ دوسرے ٹیب میں کھولیں۔ طلبہ کے فون پر کھیلنے کے لیے apnipathshala.ai/teacher کھولیں اور Google سے سائن اِن کریں۔',
    shell_wa_msg: "{title}: آپ کی کلاس کے لیے مفت لائیو کوئز۔ طلبہ فون پر کوڈ اور عرفی نام سے شامل ہوتے ہیں، کوئی سائن اپ نہیں؛ استاد Google سے سائن اِن کرتے ہیں۔ نہ اشتہار، 12 ہندوستانی زبانوں میں۔ یہاں کھولیں: {url}",
    demo_teacher: 'ڈیمو استاد',
    signin_title: 'Google سے سائن ان کریں — اساتذہ کے لیے مفت',
    signin_text: 'آپ کے کوئز آن لائن محفوظ ہوتے ہیں، اس لیے آپ انہیں کسی بھی کمپیوٹر پر استعمال کر سکتے ہیں۔ طلبہ کو کبھی سائن ان نہیں کرنا پڑتا: وہ کوڈ اور عرفی نام سے شامل ہوتے ہیں۔',
    signin_google: 'Google سے سائن ان کریں',
    signin_demo: 'ابھی ڈیمو موڈ میں آزمائیں',
    inapp_hint: 'WhatsApp جیسی ایپس کے اندر Google سائن ان کام نہیں کرتا۔ یہ صفحہ Chrome میں کھولیں۔',
    use_demo: 'اس کے بجائے ڈیمو موڈ استعمال کریں',
    hello: 'آداب، {name}',
    new_quiz: 'نیا کوئز',
    import_qm: 'اس آلے کے کوئز میکر سے لائیں',
    import_file: 'JSON / CSV امپورٹ کریں',
    import_hint: 'CSV کے کالم: سوال، آپشن 1 سے آپشن 6، صحیح جواب (1–6 یا A–F)، وضاحت۔',
    settings_title: 'لائیو کوئز کی ترتیبات',
    time_per_q: 'ہر سوال کا وقت',
    sec: '{n} سیکنڈ',
    shuffle_q: 'سوالوں کی ترتیب بدلیں',
    shuffle_o: 'آپشنز کی ترتیب بدلیں',
    my_quizzes: 'میرے کوئز',
    sample_badge: 'نمونہ',
    n_questions: '{n} سوال',
    host: 'لائیو چلائیں',
    edit_copy: 'نقل بنا کر ترمیم کریں',
    no_quizzes: 'ابھی آپ کا اپنا کوئی کوئز نہیں ہے۔ نیا کوئز بنائیں، امپورٹ کریں یا نمونہ کوئز چلائیں۔',
    confirm_delete_quiz: 'کوئز "{title}" حذف کریں؟',
    deleted: 'حذف ہو گیا۔',
    past_sessions: 'پچھلے سیشن',
    no_sessions: 'ابھی کوئی سیشن نہیں۔ کوئی کوئز چلائیں، اس کے نتائج یہاں نظر آئیں گے۔',
    keep_note: 'نتائج 30 دن بعد مٹ جاتے ہیں۔ رکھنے کے لیے CSV ڈاؤن لوڈ کر لیں۔',
    players_n: '{n} کھلاڑی',
    code_n: 'کوڈ {code}',
    state_lobby: 'انتظار میں',
    state_live: 'جاری',
    state_ended: 'ختم',
    results: 'نتائج',
    resume: 'دوبارہ شروع کریں',
    confirm_delete_session: 'یہ سیشن اس کے تمام جوابات سمیت حذف کریں؟',
    account: 'آپ کا اکاؤنٹ',
    sign_out: 'سائن آؤٹ',
    delete_account: 'میرا اکاؤنٹ اور ڈیٹا مٹائیں',
    delete_account_text: 'اس سے آپ کا استاد اکاؤنٹ، آپ کے سارے کوئز اور سیشن، اور ان میں طلبہ کے تمام عرفی نام اور جوابات مٹ جائیں گے۔ اسے واپس نہیں لایا جا سکتا۔',
    delete_account_tip: 'ایسا کرنے سے پہلے جو نتائج رکھنے ہیں، ان کی CSV ڈاؤن لوڈ کر لیں۔',
    delete_account_check: 'میں سمجھتا/سمجھتی ہوں۔ سب کچھ حذف کر دیں۔',
    delete_forever: 'ہمیشہ کے لیے حذف کریں',
    account_deleted: 'آپ کا اکاؤنٹ اور اس کا سارا ڈیٹا حذف کر دیا گیا۔',
    privacy: 'رازداری کی پالیسی',
    terms: 'استعمال کی شرائط',
    data_cloud: 'آپ کے کوئز اور نتائج Google Firebase (ممبئی) میں رکھے جاتے ہیں۔ طلبہ صرف عرفی نام دیتے ہیں۔',
    data_demo: 'ڈیمو موڈ میں سب کچھ اسی براؤزر میں رہتا ہے۔',
    edit_quiz: 'کوئز میں ترمیم',
    quiz_title: 'کوئز کا نام',
    question_n: 'سوال {n}',
    option_n: 'آپشن {n}',
    tick_correct: 'صحیح جواب پر نشان لگائیں۔',
    mark_correct: 'آپشن {n} صحیح جواب ہے',
    add_option: 'آپشن شامل کریں',
    remove_option: 'آپشن {n} ہٹائیں',
    explain_label: 'وضاحت (اختیاری، جواب کے بعد دکھائی جائے گی)',
    time_label: 'وقت سیکنڈ میں (اختیاری)',
    time_ph: 'ڈیفالٹ',
    add_question: 'سوال شامل کریں',
    move_up: 'سوال {n} اوپر کریں',
    move_down: 'سوال {n} نیچے کریں',
    delete_question: 'سوال {n} حذف کریں',
    save_quiz: 'کوئز محفوظ کریں',
    saved: 'محفوظ ہو گیا۔',
    err_title: 'براہِ کرم کوئز کا نام لکھیں۔',
    err_no_questions: 'کم از کم ایک سوال شامل کریں۔',
    err_q_text: 'سوال {n}: براہِ کرم سوال لکھیں۔',
    err_q_options: 'سوال {n}: کم از کم 2 آپشن لکھیں۔',
    err_q_correct: 'سوال {n}: صحیح جواب پر نشان لگائیں۔',
    draft_restored: 'آپ کی غیر محفوظ تبدیلیاں واپس آ گئیں۔',
    confirm_discard: 'اپنی تبدیلیاں چھوڑ دیں؟',
    untitled: 'بے نام کوئز',
    opt_true: 'صحیح',
    opt_false: 'غلط',
    qm_title: 'کوئز میکر میں محفوظ کوئز',
    qm_none: 'اس آلے پر کوئز میکر کا کوئی کوئز نہیں ملا۔',
    open_qm: 'کوئز میکر کھولیں',
    import_selected: 'منتخب کردہ امپورٹ کریں',
    imported_n: '{n} کوئز امپورٹ ہو گئے۔',
    skipped_n: '{n} سوال چھوڑ دیے گئے۔',
    import_failed: 'یہ فائل پڑھی نہیں جا سکی۔ کوئز میکر کی JSON یا CSV فائل استعمال کریں۔',
    join_line: '{url} پر جائیں اور یہ کوڈ ڈالیں:',
    scan_qr: 'یا یہ QR کوڈ اسکین کریں',
    qr_offline: 'QR کوڈ کے لیے انٹرنیٹ چاہیے۔ طلبہ کوڈ ٹائپ کر سکتے ہیں۔',
    waiting_players: 'طلبہ کے شامل ہونے کا انتظار…',
    joined_n: '{n} شامل ہوئے',
    lock: 'لاک کریں',
    unlock: 'ان لاک کریں',
    locked_note: 'لاک ہے: اب کوئی نیا شامل نہیں ہو سکتا۔',
    kick: '{name} کو ہٹائیں',
    confirm_kick: '{name} کو اس کوئز سے ہٹائیں؟ وہ دوبارہ شامل نہیں ہو سکیں گے۔',
    start_quiz: 'کوئز شروع کریں',
    need_player: 'پہلے کم از کم ایک طالب علم کا شامل ہونا ضروری ہے۔',
    open_student: 'طالب علم والا ٹیب کھولیں',
    question_of: 'سوال {n} / {total}',
    answered_n: '{total} میں سے {n} نے جواب دیا',
    show_answer: 'جواب دکھائیں',
    skip_q: 'سوال چھوڑیں',
    time_up: 'وقت ختم!',
    all_answered: 'سب نے جواب دے دیا!',
    leaderboard: 'لیڈر بورڈ',
    next_question: 'اگلا سوال',
    final_results: 'حتمی نتائج',
    end_quiz: 'کوئز ختم کریں',
    confirm_end: 'کوئز ابھی ختم کر کے حتمی نتائج دکھائیں؟',
    correct_answer: 'صحیح جواب',
    points_n: '{n} پوائنٹس',
    col_rank: 'درجہ',
    col_nick: 'عرفی نام',
    col_correct: 'صحیح جوابات',
    col_q: 'س{n}',
    col_question: 'سوال',
    export_csv: 'CSV ایکسپورٹ کریں',
    host_again: 'دوبارہ چلائیں',
    back_dash: 'میرے کوئز پر واپس',
    session_gone: 'یہ کوئز سیشن اب موجود نہیں ہے۔',
    nobody_joined: 'اس کوئز میں کوئی شامل نہیں ہوا۔',
    keys_hint: 'کی بورڈ: آگے کے لیے Space یا →',
    offline_banner: 'انٹرنیٹ کنکشن نہیں ہے۔ طلبہ کے جوابات شاید نہ پہنچیں۔',
    connecting: 'جڑ رہا ہے…',
    err_not_configured: 'آن لائن کوئز ابھی سیٹ نہیں ہوا۔ ڈیمو موڈ آزمائیں۔',
    err_offline: 'انٹرنیٹ نہیں ہے۔ کنکشن دیکھ کر دوبارہ کوشش کریں۔',
    err_quota_exceeded: 'آج کی مفت حد پوری ہو گئی۔ براہِ کرم کل دوبارہ کوشش کریں، یا ڈیمو موڈ استعمال کریں۔',
    err_not_found: 'نہیں ملا۔ شاید اسے حذف کر دیا گیا ہے۔',
    err_permission_denied: 'آپ کو یہ کرنے کی اجازت نہیں ہے۔ براہِ کرم دوبارہ سائن ان کریں۔',
    err_session_locked: 'یہ کوئز لاک ہے۔',
    err_session_ended: 'یہ کوئز ختم ہو چکا ہے۔',
    err_name_taken: 'یہ عرفی نام کوئی اور استعمال کر رہا ہے۔',
    err_invalid_input: 'براہِ کرم جو لکھا ہے اسے جانچ لیں۔',
    err_unknown: 'کچھ گڑبڑ ہو گئی۔ براہِ کرم دوبارہ کوشش کریں۔',
    help_title: 'استعمال کیسے کریں · کلاس کے لیے خیالات',
    help_1: 'سائن ان کریں اور نمونہ کوئز پر "لائیو چلائیں" دبائیں، 10 سیکنڈ میں سمجھ آ جائے گا کہ یہ کیسے چلتا ہے۔',
    help_2: 'اسکرین پروجیکٹر پر دکھائیں۔ طلبہ فون پر apnipathshala.ai/join کھول کر کوڈ اور عرفی نام ڈالتے ہیں۔',
    help_3: 'طلبہ سے کہیں کہ پورا نام نہیں، عرفی نام لکھیں۔ ✕ سے کسی کو بھی ہٹا سکتے ہیں، اور سب آ جائیں تو لاک دبائیں۔',
    help_4: 'صحیح جواب پر 500 سے 1000 پوائنٹس: جتنا جلدی، اتنے زیادہ۔ غلط جواب پر 0۔',
    help_5: 'کلاس کے لیے خیال: باب کے آخر میں 3، 3 طلبہ کے گروپ ایک فون پر مشورہ کر کے جواب دیں۔',
    help_6: 'کوئز میکر میں کوئز بنا کر یہاں امپورٹ کریں، یا نیا کوئز لکھیں۔ ریکارڈ کے لیے نتائج CSV میں ایکسپورٹ کریں۔'
  }
};
