/* UI strings for the Spam Classifier Lab. Keys are identical in all 12 languages.
   Shared words (print, reset, add, clear, fullscreen, confirm_reset, ...) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Spam Classifier Lab',
    intro: 'Teach a computer to separate spam from real messages just by counting words (Naive Bayes). See every step of the maths, then try to fool it.',
    privacy: 'Everything runs in your browser. The messages you type never leave this device.',
    projector: 'Projector mode',

    step1: 'Check a message',
    msg_label: 'Type or paste a message',
    msg_ph: 'For example: You won 10 lakh lottery, click link',
    try_t: 'Or try one of these:',
    try_spam: 'Lottery message',
    try_ham: 'Class cancelled',
    try_tricky: 'Tricky one',
    verdict_spam: 'SPAM',
    verdict_ham: 'NOT SPAM',
    verdict_tie: 'CANNOT TELL',
    sure: 'The filter is {p} sure',
    tie_note: 'Both chances are equal, so the filter cannot decide.',
    chance_spam: 'Chance of spam',
    chance_ham: 'Chance of not spam',
    spam_word: 'spam',
    empty_msg: 'Type a message above to see what the filter thinks.',
    no_words: 'No words found in this message, so only the starting chances count.',
    no_model: 'There are no training messages yet. Add some in “Teach it” or load the sample messages.',
    need_both: 'Add at least one Spam and one Not-spam message, otherwise the filter always gives the same answer.',
    evidence_t: 'Evidence, word by word',
    evidence_hint: 'Red bar = this word pushes towards Spam. Green bar = towards Not spam. Longer = stronger. Grey = a new word the filter has never seen, so it is ignored.',
    new_word: 'new word, ignored',
    times_spam: '{x}× more likely in spam',
    times_ham: '{x}× more likely in real messages',
    even_word: 'equally likely in both',
    maths_t: 'Step by step: the maths',
    step_prior: 'Step 1 · Starting chance (prior). Out of {n} training messages, {s} are spam and {h} are not spam.',
    prior_line: 'P(spam) = {s} ÷ {n} = {ps} · P(not spam) = {h} ÷ {n} = {ph}',
    step_words: 'Step 2 · For each word: how likely is it in a spam message, and in a real one? We add 1 to every count (Laplace smoothing) so that a word never seen in one class does not make the whole product zero.',
    formula_word: 'P(word | class) = (times the word appears in that class + 1) ÷ (all words in that class + V)',
    vocab_line: 'V = different words known = {v} · words in spam messages = {ws} · words in real messages = {wh}',
    col_word: 'Word',
    col_counts: 'Seen in spam / real',
    col_pspam: 'P(word | spam)',
    col_pham: 'P(word | not spam)',
    col_push: 'Pushes towards',
    step_multiply: 'Step 3 · Multiply: the starting chance × the chance of every word, once for Spam and once for Not spam.',
    score_spam: 'Spam score',
    score_ham: 'Not-spam score',
    tiny: 'too small for the computer to show (this is why real filters add logarithms instead of multiplying)',
    step_compare: 'Step 4 · Compare. The spam score’s share of the two scores is the final answer.',
    final_line: 'P(spam | message) = {a} ÷ ({a} + {b}) = {p}',
    final_only: 'P(spam | message) = {p}',
    log_note: 'Real programs add log values instead of multiplying, because multiplying many small numbers gives something too tiny to store. The winner stays the same. Total log-odds for this message: {lo} (positive = spam).',
    unknown_line: 'Skipped because never seen in training: {words}',

    step2: 'Teach it: the training messages',
    step2_hint: 'The filter learns only from these messages. Add your own, remove some, and watch the verdict above change at once.',
    lbl_spam: 'Spam',
    lbl_ham: 'Not spam',
    n_msgs: 'Messages: {n}',
    empty_label: 'No messages yet.',
    test_badge: 'test',
    test_badge_title: 'Held out for the fair test: the filter does not learn from this message',
    remove_msg: 'Remove this message',
    add_as: 'Add a new message as',
    add_ph: 'Type a message, press Enter',
    dup_msg: 'This message is already in the list.',
    max_rows: 'Limit reached: {n} messages.',
    load_samples: 'Sample messages',
    samples_all: 'All 40 sample messages are already in the list.',
    confirm_samples: 'Put back the missing sample messages? Your own messages are kept.',
    clear_all: 'Clear all',
    confirm_clear: 'Remove every training message?',
    export_csv: 'Export CSV',
    import_csv: 'Import CSV',
    csv_hint: 'CSV file with the columns text and label (spam or ham). It opens in Excel or Google Sheets.',
    import_bad: 'Could not read this file. It needs two columns: text and label (spam / ham).',
    import_ok: 'Imported {n} messages.',
    confirm_import: 'Add the {n} messages from this file to the training messages?',
    nothing_export: 'There are no messages to export yet.',
    samples_note: 'Sample messages follow the app language. Messages you add are never translated.',
    exp_t: 'Experiment: is “won” always spam?',
    exp_d: 'The tricky message is a real message from a friend, but it uses words like “congratulations”, “won” and “prize” that the filter has only seen in spam. Add 3 real messages with these words and watch what happens.',
    exp_btn: 'Add 3 real messages',
    exp_before: 'Before',
    exp_after: 'After',
    exp_result: 'Chance of spam for the tricky message: {a} → {b}. The filter learned that these words also appear in real messages.',
    exp_small: 'Chance of spam for the tricky message: {a} → {b}. Not much change. Add a few more real messages with these words.',
    undo_exp: 'Undo the experiment',

    step3: 'How good is it? A fair test',
    holdout_label: 'Hold out 25% of the sample messages as a test set the filter never learns from',
    st_train: 'Training messages',
    st_test: 'Test messages',
    st_vocab: 'Different words known',
    st_acc: 'Correct on the test',
    acc_none: 'There are no test messages. Turn on the fair test above, or load the sample messages.',
    cheat_note: 'Fair test is off, so the filter is marked on the very messages it learned from, like a student marking their own homework. The score looks better than it really is.',
    reshuffle: 'Pick other test messages',
    cm_t: 'Confusion matrix',
    cm_said: 'Filter said',
    cm_real: 'Really',
    cm_tp: 'Spam caught',
    cm_fp: 'Real message blocked',
    cm_fn: 'Spam slipped through',
    cm_tn: 'Real message let through',
    precision_line: 'Precision {p}: of the messages marked spam, this share really was spam.',
    recall_line: 'Recall {p}: of all the real spam, this share was caught.',
    mistakes_t: 'Why did it get these wrong? ({n})',
    no_mistakes: 'No mistakes on the test messages. Press “Pick other test messages” for a harder set.',
    mistake_line: 'Filter said {guess}, really {real} ({p} spam).',
    mistake_why: 'Mostly because of: {words}.',
    mistake_why_none: 'None of its words were seen in training, so only the starting chance decided.',
    see_why: 'See the maths',

    peek_t: 'Peek inside: the word counts are the whole model',
    peek_note: 'Training is only counting. This table is everything the filter knows.',
    peek_filter: 'Find a word',
    sort_by: 'Sort the words',
    sort_common: 'Most common',
    sort_spam: 'Spam clues',
    sort_ham: 'Real-message clues',
    peek_count: 'Showing {a} of {b} words',
    peek_more: 'Show more words',
    peek_none: 'No matching words.',
    col_spam_n: 'In spam',
    col_ham_n: 'In real',
    col_leans: 'Points to',
    lean_even: 'both equally',

    inside_t: 'What is happening inside?',
    in1_t: 'It only counts words',
    in1: 'Training is just counting: how many times does each word appear in spam messages, and how many times in real ones? “lottery” piles up under Spam, “homework” under Not spam.',
    in2_t: 'Bayes’ rule',
    in2: 'For a new message it multiplies the starting chance of each class by the chance of every word in that class. The class with the bigger result wins. This is Naive Bayes, the method behind the first email spam filters.',
    formula: 'P(spam | message) ∝ P(spam) × P(word₁ | spam) × P(word₂ | spam) × …',
    in3_t: 'Laplace smoothing: the +1 trick',
    in3: 'If a word was never seen in one class, its chance would be 0 and the whole product would become 0. Adding 1 to every count (and V to the bottom of the fraction) keeps every chance a little above zero.',
    in4_t: 'Why logarithms?',
    in4: 'Multiplying twenty numbers like 0.003 gives something like 0.000000000000000000000000000001. Computers lose such tiny numbers, so real filters add log values instead. The winner stays the same.',
    in5_t: 'Why “naive”?',
    in5: 'It treats every word as independent and ignores order and meaning. “won the match” and “won the lottery” both just contain “won”. That is why the tricky message fools it, and why more varied examples help.',
    in6_t: 'Real spam filters',
    in6: 'Gmail and WhatsApp use the same idea plus much more: sender history, links, images and large neural networks. But the lesson is the same: a filter is only as good as the examples it learned from.',

    help_t: 'How to use · Ideas for the classroom',
    tip1: 'Type any message in “Check a message”. The verdict, the word bars and the step-by-step maths update as you type.',
    tip2: 'Open “Step by step: the maths” and check one fraction by hand with the counts from “Peek inside”. This matches the CBSE Class 10 AI evaluation unit and the Class 11–12 Naive Bayes topic.',
    tip3: 'Class activity: two teams. Team A writes 5 real messages that the filter marks as spam; Team B writes 5 spam messages that get through. Add them as training messages and see which team’s trick stops working.',
    tip4: 'Turn the fair test off and on. Discuss why testing on the training messages gives a score that is too good.',
    tip5: 'Export the messages as CSV, let students label 20 new ones at home, and import them next class. Nothing is uploaded: everything stays on this device.',
    tip6: 'Discuss: what happens to a real “Congratulations, you won the quiz!” message? What does a false positive cost? What does a false negative cost?'
  },
  //@@MORE_LANGS@@
};
