/* UI strings for Join & Merge Files. Keys must be identical in all 12 languages. */
window.APP_STRINGS = {
  en: {
    app_title: 'Join & Merge Files',
    intro: 'Join two CSV files on a matching column (like VLOOKUP), or stack many monthly files into one. See what matched, what did not, and download the result.',
    mode_join: 'Join two files', mode_stack: 'Stack many files',
    h_files: '1. Your two files', try_sample: 'Try a sample:', sample_students: 'Students + marks', sample_orders: 'Orders + customers',
    file_a: 'File A (left)', file_b: 'File B (right)', open_csv: 'Open CSV', paste_data: 'Paste data',
    paste_ph: 'Paste rows from Excel or Google Sheets, or CSV text', use_paste: 'Use pasted data', pasted_a: 'pasted-A', pasted_b: 'pasted-B',
    drop_hint: 'You can also drop CSV files here. From Excel: File → Save as → CSV. Your files never leave this device.',
    file_info: '{rows} rows, {cols} columns',
    err_empty: 'No rows found. The first row should have the column names.', err_file: 'Could not read this file.',
    err_excel: 'Please save the sheet as CSV first (Excel: File → Save as → CSV).', big_note: 'This file is big, so it is not saved for next time.',
    h_match: '2. How to match rows', key_a: 'Key column in A', key_b: 'Key column in B',
    opt_trim: 'Ignore extra spaces', opt_icase: 'Ignore capital letters', opt_num: 'Treat "007" and "7" as the same', swap: 'Swap A and B',
    join_type: 'Join type', type_inner: 'Inner', type_left: 'Left', type_right: 'Right', type_full: 'Full outer',
    help_inner: 'Inner: only rows whose key is in both files.',
    help_left: 'Left: every row of A, with details from B where the key matches and blanks where it does not.',
    help_right: 'Right: every row of B, with details from A where the key matches.',
    help_full: 'Full outer: every row of both files, matched where possible.',
    venn_label: 'Venn diagram of the join type',
    h_result: '3. Result', st_matched: 'Rows of A with a match', only_in: 'Only in {name}', st_rows: 'Rows in result',
    warn_dup_b: '{n} keys appear more than once in {name}. This is one-to-many: a row of A is repeated once for each match, so the result can have more rows than A.',
    note_dup_a: '{n} keys appear more than once in {name}. That is fine (many-to-one): each of those rows gets the same details.',
    warn_blank: '{n} rows have a blank key. Blank keys never match.',
    warn_none: 'No rows matched. Check that you picked the right key columns.',
    hint_numeric: 'Tip: some keys look like "007" in one file and "7" in the other. Tick "Treat 007 and 7 as the same" to match them.',
    out_cols: 'Columns in the result (tap to hide or show):', no_rows: 'No rows in the result.',
    page_info: 'Rows {from}–{to} of {total}', legend_nm: 'Striped cells: no matching row in the other file.', download_csv: 'Download CSV',
    h_unmatched: '4. Rows that did not match', um_note: 'Check these before you trust the result. A spelling mistake or an extra 0 in a key is the most common reason.',
    only_in_n: '{name}: {n}', um_none: 'Every row found a match.', download_um: 'Download these rows', unmatched_file: 'not-matched',
    h_lookup: 'This is VLOOKUP / XLOOKUP',
    lookup_1: 'A <b>left join</b> does what <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> or <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> does in Excel or Google Sheets, but for every column at once.',
    lookup_2: 'One difference: VLOOKUP and XLOOKUP stop at the <b>first</b> match. A join returns <b>every</b> match, which is why one-to-many keys add rows. VLOOKUP shows #N/A when nothing matches; a left join leaves the cells blank.',
    h_stack: '1. Files to stack (one below the other)',
    stack_note: 'For files with the same kind of columns, like sales for January, February and March. Columns are matched by name, even if they are in a different order.',
    st_empty: 'No files yet. Add CSV files or load the sample.', st_add: 'Add CSV files', st_sample: 'Sample: 3 months of sales', st_clear: 'Remove all',
    st_loose: 'Match column names ignoring capitals and extra spaces', st_source: 'Add a "Source file" column', source_col: 'Source file',
    h_stacked: '2. Stacked result', st_total: '{rows} rows from {files} files, {cols} columns', st_added: '{n} new columns', st_missing: 'missing: {cols}',
    remove_file: 'Remove file', legend_blank: 'Striped cells are empty (often because that file did not have the column).', stacked_file: 'stacked',
    tip1: 'Start with the "Students + marks" sample and switch between Inner, Left, Right and Full outer. Watch the row count and the Venn diagram change.',
    tip2: 'Office: join this month\'s orders with your customer list to add each customer\'s city and phone, then download one file for delivery.',
    tip3: 'Class activity: print both sample files. Students join them by hand on paper, then check with the app. Why does the inner join have 9 rows when only 7 students matched?',
    tip4: 'Keys must be written the same way in both files. Clean them first (spaces, capitals, "007" vs "7") with the options here or the Data Cleaning Lab app.',
    tip5: 'Stack mode: put 12 monthly sales files together into one yearly file, with a "Source file" column that shows where each row came from.',
    words_title: 'Words to know: what is happening inside',
    w_key: '<b>Key</b>: the column used to match rows, like a roll number or a customer ID. A good key is written the same way in both files and is unique in at least one of them.',
    w_inner: '<b>Inner join</b>: keeps only rows that match in both files (the middle of the Venn diagram).',
    w_outer: '<b>Left, right and full outer join</b>: also keep the rows that did not match, from A, from B, or from both. The missing side stays blank.',
    w_many: '<b>One-to-many</b>: one key in A matches many rows in B (one student, many subjects). The result gets one row for each match.',
    w_union: '<b>Stack (append / union)</b>: put files one below the other. Stacking adds rows; a join adds columns.'
  },
  hi: {
    app_title: 'फ़ाइलें जोड़ें और मिलाएँ',
    intro: 'दो CSV फ़ाइलों को एक मिलते-जुलते कॉलम से जोड़ें (VLOOKUP की तरह), या कई महीनों की फ़ाइलों को एक के नीचे एक रखें। देखें क्या मिला, क्या नहीं मिला, और नतीजा डाउनलोड करें।',
    mode_join: 'दो फ़ाइलें जोड़ें', mode_stack: 'कई फ़ाइलें एक के नीचे एक',
    h_files: '1. आपकी दो फ़ाइलें', try_sample: 'नमूना आज़माएँ:', sample_students: 'छात्र + अंक', sample_orders: 'ऑर्डर + ग्राहक',
    file_a: 'फ़ाइल A (बाएँ)', file_b: 'फ़ाइल B (दाएँ)', open_csv: 'CSV खोलें', paste_data: 'डेटा पेस्ट करें',
    paste_ph: 'Excel या Google Sheets से पंक्तियाँ, या CSV टेक्स्ट पेस्ट करें', use_paste: 'पेस्ट किया डेटा इस्तेमाल करें', pasted_a: 'पेस्ट-A', pasted_b: 'पेस्ट-B',
    drop_hint: 'CSV फ़ाइलें यहाँ खींचकर भी छोड़ सकते हैं। Excel में: File → Save as → CSV। आपकी फ़ाइलें इसी डिवाइस पर रहती हैं।',
    file_info: '{rows} पंक्तियाँ, {cols} कॉलम',
    err_empty: 'कोई पंक्ति नहीं मिली। पहली पंक्ति में कॉलम के नाम होने चाहिए।', err_file: 'यह फ़ाइल पढ़ी नहीं जा सकी।',
    err_excel: 'पहले शीट को CSV में सेव करें (Excel: File → Save as → CSV)।', big_note: 'यह फ़ाइल बड़ी है, इसलिए अगली बार के लिए सेव नहीं हुई।',
    h_match: '2. पंक्तियाँ कैसे मिलाएँ', key_a: 'A का की-कॉलम', key_b: 'B का की-कॉलम',
    opt_trim: 'फ़ालतू स्पेस अनदेखा करें', opt_icase: 'बड़े-छोटे अक्षर अनदेखा करें', opt_num: '"007" और "7" को एक जैसा मानें', swap: 'A और B अदला-बदली करें',
    join_type: 'जोड़ने का तरीका', type_inner: 'इनर', type_left: 'लेफ़्ट', type_right: 'राइट', type_full: 'फ़ुल आउटर',
    help_inner: 'इनर: सिर्फ़ वे पंक्तियाँ जिनकी की दोनों फ़ाइलों में है।',
    help_left: 'लेफ़्ट: A की हर पंक्ति; जहाँ की मिले वहाँ B की जानकारी, जहाँ न मिले वहाँ खाली।',
    help_right: 'राइट: B की हर पंक्ति; जहाँ की मिले वहाँ A की जानकारी।',
    help_full: 'फ़ुल आउटर: दोनों फ़ाइलों की हर पंक्ति, जहाँ हो सके वहाँ मिलाकर।',
    venn_label: 'जोड़ने के तरीके का वेन आरेख',
    h_result: '3. नतीजा', st_matched: 'A की मिली हुई पंक्तियाँ', only_in: 'सिर्फ़ {name} में', st_rows: 'नतीजे में पंक्तियाँ',
    warn_dup_b: '{name} में {n} की एक से ज़्यादा बार हैं। यह एक-से-अनेक (one-to-many) है: A की पंक्ति हर मेल के लिए एक बार दोहराई जाती है, इसलिए नतीजे में A से ज़्यादा पंक्तियाँ हो सकती हैं।',
    note_dup_a: '{name} में {n} की एक से ज़्यादा बार हैं। यह ठीक है (अनेक-से-एक): उन सभी पंक्तियों को वही जानकारी मिलती है।',
    warn_blank: '{n} पंक्तियों में की खाली है। खाली की कभी नहीं मिलती।',
    warn_none: 'कोई पंक्ति नहीं मिली। देखें कि सही की-कॉलम चुने हैं।',
    hint_numeric: 'सुझाव: कुछ की एक फ़ाइल में "007" और दूसरी में "7" जैसी हैं। उन्हें मिलाने के लिए "007 और 7 को एक जैसा मानें" पर टिक करें।',
    out_cols: 'नतीजे के कॉलम (छिपाने या दिखाने के लिए दबाएँ):', no_rows: 'नतीजे में कोई पंक्ति नहीं।',
    page_info: 'पंक्तियाँ {from}–{to}, कुल {total}', legend_nm: 'धारीदार सेल: दूसरी फ़ाइल में मेल खाती पंक्ति नहीं।', download_csv: 'CSV डाउनलोड करें',
    h_unmatched: '4. जो पंक्तियाँ नहीं मिलीं', um_note: 'नतीजे पर भरोसा करने से पहले इन्हें देखें। की में वर्तनी की गलती या एक फ़ालतू 0 सबसे आम वजह है।',
    only_in_n: '{name}: {n}', um_none: 'हर पंक्ति का मेल मिल गया।', download_um: 'ये पंक्तियाँ डाउनलोड करें', unmatched_file: 'नहीं-मिलीं',
    h_lookup: 'यही है VLOOKUP / XLOOKUP',
    lookup_1: '<b>लेफ़्ट जॉइन</b> वही करता है जो Excel या Google Sheets में <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> या <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> करता है, पर सारे कॉलम एक साथ।',
    lookup_2: 'एक फ़र्क: VLOOKUP और XLOOKUP <b>पहले</b> मेल पर रुक जाते हैं। जॉइन <b>हर</b> मेल देता है, इसीलिए एक-से-अनेक की से पंक्तियाँ बढ़ती हैं। कुछ न मिले तो VLOOKUP #N/A दिखाता है; लेफ़्ट जॉइन सेल खाली छोड़ता है।',
    h_stack: '1. एक के नीचे एक रखने वाली फ़ाइलें',
    stack_note: 'एक जैसे कॉलम वाली फ़ाइलों के लिए, जैसे जनवरी, फ़रवरी और मार्च की बिक्री। कॉलम नाम से मिलाए जाते हैं, भले ही क्रम अलग हो।',
    st_empty: 'अभी कोई फ़ाइल नहीं। CSV फ़ाइलें जोड़ें या नमूना खोलें।', st_add: 'CSV फ़ाइलें जोड़ें', st_sample: 'नमूना: 3 महीने की बिक्री', st_clear: 'सब हटाएँ',
    st_loose: 'कॉलम के नाम मिलाते समय बड़े-छोटे अक्षर और फ़ालतू स्पेस अनदेखा करें', st_source: '"स्रोत फ़ाइल" कॉलम जोड़ें', source_col: 'स्रोत फ़ाइल',
    h_stacked: '2. एक साथ रखा नतीजा', st_total: '{files} फ़ाइलों से {rows} पंक्तियाँ, {cols} कॉलम', st_added: '{n} नए कॉलम', st_missing: 'नहीं हैं: {cols}',
    remove_file: 'फ़ाइल हटाएँ', legend_blank: 'धारीदार सेल खाली हैं (अक्सर इसलिए कि उस फ़ाइल में वह कॉलम नहीं था)।', stacked_file: 'एक-साथ',
    tip1: '"छात्र + अंक" नमूने से शुरू करें और इनर, लेफ़्ट, राइट और फ़ुल आउटर बदलकर देखें। पंक्तियों की गिनती और वेन आरेख बदलते देखें।',
    tip2: 'दफ़्तर: इस महीने के ऑर्डर को ग्राहक सूची से जोड़ें ताकि हर ग्राहक का शहर और फ़ोन आ जाए, फिर डिलीवरी के लिए एक फ़ाइल डाउनलोड करें।',
    tip3: 'कक्षा गतिविधि: दोनों नमूना फ़ाइलें प्रिंट करें। छात्र कागज़ पर हाथ से जोड़ें, फिर ऐप से जाँचें। सिर्फ़ 7 छात्र मिले, फिर इनर जॉइन में 9 पंक्तियाँ क्यों हैं?',
    tip4: 'की दोनों फ़ाइलों में एक ही तरह लिखी होनी चाहिए। पहले उसे साफ़ करें (स्पेस, बड़े-छोटे अक्षर, "007" और "7") यहाँ के विकल्पों से या डेटा सफ़ाई लैब ऐप से।',
    tip5: 'एक के नीचे एक: 12 महीनों की बिक्री फ़ाइलें मिलाकर एक साल की फ़ाइल बनाएँ, "स्रोत फ़ाइल" कॉलम के साथ जो बताए कि हर पंक्ति कहाँ से आई।',
    words_title: 'ज़रूरी शब्द: अंदर क्या हो रहा है',
    w_key: '<b>की (Key)</b>: पंक्तियाँ मिलाने वाला कॉलम, जैसे रोल नंबर या ग्राहक ID। अच्छी की दोनों फ़ाइलों में एक तरह लिखी होती है और कम से कम एक फ़ाइल में दोहराई नहीं जाती।',
    w_inner: '<b>इनर जॉइन</b>: सिर्फ़ वे पंक्तियाँ जो दोनों फ़ाइलों में मिलती हैं (वेन आरेख का बीच वाला हिस्सा)।',
    w_outer: '<b>लेफ़्ट, राइट और फ़ुल आउटर जॉइन</b>: न मिलने वाली पंक्तियाँ भी रखते हैं, A से, B से, या दोनों से। जो हिस्सा नहीं मिला वह खाली रहता है।',
    w_many: '<b>एक-से-अनेक</b>: A की एक की B की कई पंक्तियों से मिलती है (एक छात्र, कई विषय)। नतीजे में हर मेल की एक पंक्ति बनती है।',
    w_union: '<b>एक के नीचे एक (append / union)</b>: फ़ाइलों को एक के नीचे एक रखना। इससे पंक्तियाँ बढ़ती हैं; जॉइन से कॉलम बढ़ते हैं।'
  },
  bn: {
    app_title: 'ফাইল জোড়া ও মেলানো',
    intro: 'দুটি CSV ফাইলকে একটি মিল-থাকা কলাম দিয়ে জুড়ুন (VLOOKUP-এর মতো), বা অনেক মাসের ফাইল একটার নিচে একটা রাখুন। কী মিলল, কী মিলল না দেখুন, আর ফলাফল ডাউনলোড করুন।',
    mode_join: 'দুটি ফাইল জুড়ুন', mode_stack: 'অনেক ফাইল একটার নিচে একটা',
    h_files: '1. আপনার দুটি ফাইল', try_sample: 'নমুনা দেখুন:', sample_students: 'ছাত্রছাত্রী + নম্বর', sample_orders: 'অর্ডার + গ্রাহক',
    file_a: 'ফাইল A (বাঁ)', file_b: 'ফাইল B (ডান)', open_csv: 'CSV খুলুন', paste_data: 'ডেটা পেস্ট করুন',
    paste_ph: 'Excel বা Google Sheets থেকে সারি, বা CSV লেখা পেস্ট করুন', use_paste: 'পেস্ট করা ডেটা ব্যবহার করুন', pasted_a: 'পেস্ট-A', pasted_b: 'পেস্ট-B',
    drop_hint: 'CSV ফাইল এখানে টেনে এনেও ছাড়তে পারেন। Excel-এ: File → Save as → CSV। আপনার ফাইল এই ডিভাইসেই থাকে।',
    file_info: '{rows}টি সারি, {cols}টি কলাম',
    err_empty: 'কোনো সারি পাওয়া যায়নি। প্রথম সারিতে কলামের নাম থাকা দরকার।', err_file: 'এই ফাইলটি পড়া গেল না।',
    err_excel: 'আগে শিটটি CSV হিসেবে সেভ করুন (Excel: File → Save as → CSV)।', big_note: 'ফাইলটি বড়, তাই পরের বারের জন্য সেভ হয়নি।',
    h_match: '2. সারি কীভাবে মেলাবেন', key_a: 'A-র কী কলাম', key_b: 'B-র কী কলাম',
    opt_trim: 'বাড়তি স্পেস উপেক্ষা করুন', opt_icase: 'বড়-ছোট অক্ষর উপেক্ষা করুন', opt_num: '"007" আর "7" একই ধরুন', swap: 'A আর B অদলবদল',
    join_type: 'জোড়ার ধরন', type_inner: 'ইনার', type_left: 'লেফট', type_right: 'রাইট', type_full: 'ফুল আউটার',
    help_inner: 'ইনার: শুধু সেই সারি যাদের কী দুটি ফাইলেই আছে।',
    help_left: 'লেফট: A-র প্রতিটি সারি; কী মিললে B-র তথ্য, না মিললে ফাঁকা।',
    help_right: 'রাইট: B-র প্রতিটি সারি; কী মিললে A-র তথ্য।',
    help_full: 'ফুল আউটার: দুটি ফাইলের প্রতিটি সারি, যেখানে সম্ভব মিলিয়ে।',
    venn_label: 'জোড়ার ধরনের ভেন চিত্র',
    h_result: '3. ফলাফল', st_matched: 'A-র মেলা সারি', only_in: 'শুধু {name}-এ', st_rows: 'ফলাফলে সারি',
    warn_dup_b: '{name}-এ {n}টি কী একাধিকবার আছে। এটা এক-থেকে-অনেক (one-to-many): A-র একটি সারি প্রতিটি মিলের জন্য একবার করে আসে, তাই ফলাফলে A-র চেয়ে বেশি সারি হতে পারে।',
    note_dup_a: '{name}-এ {n}টি কী একাধিকবার আছে। এতে অসুবিধা নেই (অনেক-থেকে-এক): ওই সব সারি একই তথ্য পায়।',
    warn_blank: '{n}টি সারির কী ফাঁকা। ফাঁকা কী কখনো মেলে না।',
    warn_none: 'কোনো সারি মেলেনি। ঠিক কী কলাম বেছেছেন কি না দেখুন।',
    hint_numeric: 'টিপ: কিছু কী এক ফাইলে "007" আর অন্যটায় "7"। মেলাতে "007 আর 7 একই ধরুন" টিক দিন।',
    out_cols: 'ফলাফলের কলাম (লুকাতে বা দেখাতে টিপুন):', no_rows: 'ফলাফলে কোনো সারি নেই।',
    page_info: 'সারি {from}–{to}, মোট {total}', legend_nm: 'ডোরাকাটা ঘর: অন্য ফাইলে মিল-থাকা সারি নেই।', download_csv: 'CSV ডাউনলোড',
    h_unmatched: '4. যে সারিগুলো মেলেনি', um_note: 'ফলাফলে ভরসা করার আগে এগুলো দেখুন। কী-তে বানান ভুল বা একটা বাড়তি 0 সবচেয়ে সাধারণ কারণ।',
    only_in_n: '{name}: {n}', um_none: 'প্রতিটি সারির মিল পাওয়া গেছে।', download_um: 'এই সারিগুলো ডাউনলোড', unmatched_file: 'মেলেনি',
    h_lookup: 'এটাই VLOOKUP / XLOOKUP',
    lookup_1: '<b>লেফট জয়েন</b> সেটাই করে যা Excel বা Google Sheets-এ <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> বা <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> করে, কিন্তু সব কলাম একসাথে।',
    lookup_2: 'একটা পার্থক্য: VLOOKUP আর XLOOKUP <b>প্রথম</b> মিলেই থেমে যায়। জয়েন <b>প্রতিটি</b> মিল দেয়, তাই এক-থেকে-অনেক কী-তে সারি বাড়ে। কিছু না মিললে VLOOKUP #N/A দেখায়; লেফট জয়েন ঘর ফাঁকা রাখে।',
    h_stack: '1. একটার নিচে একটা রাখার ফাইল',
    stack_note: 'একই ধরনের কলামের ফাইলের জন্য, যেমন জানুয়ারি, ফেব্রুয়ারি আর মার্চের বিক্রি। কলাম নাম দিয়ে মেলানো হয়, ক্রম আলাদা হলেও।',
    st_empty: 'এখনও কোনো ফাইল নেই। CSV ফাইল যোগ করুন বা নমুনা খুলুন।', st_add: 'CSV ফাইল যোগ করুন', st_sample: 'নমুনা: 3 মাসের বিক্রি', st_clear: 'সব মুছুন',
    st_loose: 'কলামের নাম মেলাতে বড়-ছোট অক্ষর আর বাড়তি স্পেস উপেক্ষা করুন', st_source: '"উৎস ফাইল" কলাম যোগ করুন', source_col: 'উৎস ফাইল',
    h_stacked: '2. একসাথে রাখা ফলাফল', st_total: '{files}টি ফাইল থেকে {rows}টি সারি, {cols}টি কলাম', st_added: '{n}টি নতুন কলাম', st_missing: 'নেই: {cols}',
    remove_file: 'ফাইল সরান', legend_blank: 'ডোরাকাটা ঘর ফাঁকা (প্রায়ই কারণ ওই ফাইলে কলামটি ছিল না)।', stacked_file: 'একসাথে',
    tip1: '"ছাত্রছাত্রী + নম্বর" নমুনা দিয়ে শুরু করুন আর ইনার, লেফট, রাইট, ফুল আউটার বদলে দেখুন। সারির সংখ্যা আর ভেন চিত্র বদলাচ্ছে দেখুন।',
    tip2: 'অফিস: এই মাসের অর্ডার গ্রাহক তালিকার সাথে জুড়ুন, যাতে প্রত্যেক গ্রাহকের শহর আর ফোন চলে আসে, তারপর ডেলিভারির জন্য একটি ফাইল নামান।',
    tip3: 'ক্লাসের কাজ: দুটি নমুনা ফাইল প্রিন্ট করুন। ছাত্রছাত্রীরা কাগজে হাতে জুড়বে, তারপর অ্যাপে মিলিয়ে দেখবে। মাত্র 7 জন মিলেছে, তবু ইনার জয়েনে 9টি সারি কেন?',
    tip4: 'দুটি ফাইলে কী একইভাবে লেখা থাকতে হবে। আগে পরিষ্কার করুন (স্পেস, বড়-ছোট অক্ষর, "007" বনাম "7") এখানকার অপশন বা ডেটা পরিষ্কারের ল্যাব অ্যাপ দিয়ে।',
    tip5: 'একটার নিচে একটা: 12 মাসের বিক্রির ফাইল জুড়ে এক বছরের ফাইল বানান, সাথে "উৎস ফাইল" কলাম যা বলে কোন সারি কোথা থেকে এল।',
    words_title: 'জরুরি শব্দ: ভেতরে কী হচ্ছে',
    w_key: '<b>কী (Key)</b>: যে কলাম দিয়ে সারি মেলানো হয়, যেমন রোল নম্বর বা গ্রাহক ID। ভালো কী দুটি ফাইলে একইভাবে লেখা থাকে আর অন্তত একটি ফাইলে একবারই থাকে।',
    w_inner: '<b>ইনার জয়েন</b>: শুধু সেই সারি রাখে যা দুটি ফাইলেই মেলে (ভেন চিত্রের মাঝের অংশ)।',
    w_outer: '<b>লেফট, রাইট আর ফুল আউটার জয়েন</b>: না-মেলা সারিও রাখে, A থেকে, B থেকে, বা দুটি থেকেই। যে দিকটা নেই সেটা ফাঁকা থাকে।',
    w_many: '<b>এক-থেকে-অনেক</b>: A-র একটি কী B-র অনেক সারির সাথে মেলে (একজন ছাত্র, অনেক বিষয়)। ফলাফলে প্রতিটি মিলের জন্য একটি সারি হয়।',
    w_union: '<b>একটার নিচে একটা (append / union)</b>: ফাইলগুলো একটার নিচে একটা রাখা। এতে সারি বাড়ে; জয়েনে কলাম বাড়ে।'
  },
  mr: {
    app_title: 'फाइल्स जोडा आणि एकत्र करा',
    intro: 'दोन CSV फाइल्स एका जुळणाऱ्या कॉलमने जोडा (VLOOKUP सारखे), किंवा अनेक महिन्यांच्या फाइल्स एकाखाली एक ठेवा. काय जुळले, काय नाही ते पाहा आणि निकाल डाउनलोड करा.',
    mode_join: 'दोन फाइल्स जोडा', mode_stack: 'अनेक फाइल्स एकाखाली एक',
    h_files: '1. तुमच्या दोन फाइल्स', try_sample: 'नमुना वापरून पाहा:', sample_students: 'विद्यार्थी + गुण', sample_orders: 'ऑर्डर + ग्राहक',
    file_a: 'फाइल A (डावी)', file_b: 'फाइल B (उजवी)', open_csv: 'CSV उघडा', paste_data: 'डेटा पेस्ट करा',
    paste_ph: 'Excel किंवा Google Sheets मधील ओळी, किंवा CSV मजकूर पेस्ट करा', use_paste: 'पेस्ट केलेला डेटा वापरा', pasted_a: 'पेस्ट-A', pasted_b: 'पेस्ट-B',
    drop_hint: 'CSV फाइल्स इथे ओढून सोडूनही उघडता येतात. Excel मध्ये: File → Save as → CSV. तुमच्या फाइल्स याच डिव्हाइसवर राहतात.',
    file_info: '{rows} ओळी, {cols} कॉलम',
    err_empty: 'एकही ओळ सापडली नाही. पहिल्या ओळीत कॉलमची नावे हवीत.', err_file: 'ही फाइल वाचता आली नाही.',
    err_excel: 'आधी शीट CSV म्हणून सेव्ह करा (Excel: File → Save as → CSV).', big_note: 'ही फाइल मोठी आहे, म्हणून पुढच्या वेळेसाठी सेव्ह झाली नाही.',
    h_match: '2. ओळी कशा जुळवायच्या', key_a: 'A मधील की कॉलम', key_b: 'B मधील की कॉलम',
    opt_trim: 'जास्तीच्या जागा दुर्लक्षित करा', opt_icase: 'मोठी-लहान अक्षरे दुर्लक्षित करा', opt_num: '"007" आणि "7" सारखेच माना', swap: 'A आणि B अदलाबदल',
    join_type: 'जोडण्याचा प्रकार', type_inner: 'इनर', type_left: 'लेफ्ट', type_right: 'राइट', type_full: 'फुल आउटर',
    help_inner: 'इनर: फक्त त्या ओळी ज्यांची की दोन्ही फाइल्समध्ये आहे.',
    help_left: 'लेफ्ट: A ची प्रत्येक ओळ; की जुळली तर B ची माहिती, नाही तर रिकामे.',
    help_right: 'राइट: B ची प्रत्येक ओळ; की जुळली तर A ची माहिती.',
    help_full: 'फुल आउटर: दोन्ही फाइल्सची प्रत्येक ओळ, जिथे शक्य तिथे जुळवून.',
    venn_label: 'जोडण्याच्या प्रकाराची वेन आकृती',
    h_result: '3. निकाल', st_matched: 'A मधील जुळलेल्या ओळी', only_in: 'फक्त {name} मध्ये', st_rows: 'निकालातील ओळी',
    warn_dup_b: '{name} मध्ये {n} की एकापेक्षा जास्त वेळा आहेत. हे एक-ते-अनेक (one-to-many) आहे: A ची ओळ प्रत्येक जुळणीसाठी एकदा येते, म्हणून निकालात A पेक्षा जास्त ओळी असू शकतात.',
    note_dup_a: '{name} मध्ये {n} की एकापेक्षा जास्त वेळा आहेत. हे ठीक आहे (अनेक-ते-एक): त्या सर्व ओळींना तीच माहिती मिळते.',
    warn_blank: '{n} ओळींमध्ये की रिकामी आहे. रिकामी की कधीच जुळत नाही.',
    warn_none: 'एकही ओळ जुळली नाही. योग्य की कॉलम निवडले आहेत का ते पाहा.',
    hint_numeric: 'सूचना: काही की एका फाइलमध्ये "007" आणि दुसऱ्यात "7" अशा आहेत. त्या जुळवण्यासाठी "007 आणि 7 सारखेच माना" वर टिक करा.',
    out_cols: 'निकालातील कॉलम (लपवण्यासाठी किंवा दाखवण्यासाठी दाबा):', no_rows: 'निकालात एकही ओळ नाही.',
    page_info: 'ओळी {from}–{to}, एकूण {total}', legend_nm: 'पट्टेदार सेल: दुसऱ्या फाइलमध्ये जुळणारी ओळ नाही.', download_csv: 'CSV डाउनलोड करा',
    h_unmatched: '4. न जुळलेल्या ओळी', um_note: 'निकालावर विश्वास ठेवण्याआधी या पाहा. की मधील शुद्धलेखनाची चूक किंवा एक जास्तीचा 0 हे सर्वात सामान्य कारण आहे.',
    only_in_n: '{name}: {n}', um_none: 'प्रत्येक ओळ जुळली.', download_um: 'या ओळी डाउनलोड करा', unmatched_file: 'न-जुळलेल्या',
    h_lookup: 'हेच आहे VLOOKUP / XLOOKUP',
    lookup_1: '<b>लेफ्ट जॉइन</b> तेच करते जे Excel किंवा Google Sheets मध्ये <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> किंवा <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> करते, पण सर्व कॉलम एकाच वेळी.',
    lookup_2: 'एक फरक: VLOOKUP आणि XLOOKUP <b>पहिल्या</b> जुळणीवर थांबतात. जॉइन <b>प्रत्येक</b> जुळणी देते, म्हणून एक-ते-अनेक की मुळे ओळी वाढतात. काहीच जुळले नाही तर VLOOKUP #N/A दाखवते; लेफ्ट जॉइन सेल रिकामे ठेवते.',
    h_stack: '1. एकाखाली एक ठेवायच्या फाइल्स',
    stack_note: 'सारखे कॉलम असलेल्या फाइल्ससाठी, उदा. जानेवारी, फेब्रुवारी आणि मार्चची विक्री. कॉलम नावाने जुळवले जातात, क्रम वेगळा असला तरी.',
    st_empty: 'अजून एकही फाइल नाही. CSV फाइल्स जोडा किंवा नमुना उघडा.', st_add: 'CSV फाइल्स जोडा', st_sample: 'नमुना: 3 महिन्यांची विक्री', st_clear: 'सर्व काढा',
    st_loose: 'कॉलमची नावे जुळवताना मोठी-लहान अक्षरे आणि जास्तीच्या जागा दुर्लक्षित करा', st_source: '"मूळ फाइल" कॉलम जोडा', source_col: 'मूळ फाइल',
    h_stacked: '2. एकत्र केलेला निकाल', st_total: '{files} फाइल्समधून {rows} ओळी, {cols} कॉलम', st_added: '{n} नवीन कॉलम', st_missing: 'नाहीत: {cols}',
    remove_file: 'फाइल काढा', legend_blank: 'पट्टेदार सेल रिकामे आहेत (बहुधा त्या फाइलमध्ये तो कॉलम नव्हता म्हणून).', stacked_file: 'एकत्र',
    tip1: '"विद्यार्थी + गुण" नमुन्याने सुरुवात करा आणि इनर, लेफ्ट, राइट, फुल आउटर बदलून पाहा. ओळींची संख्या आणि वेन आकृती बदलताना पाहा.',
    tip2: 'ऑफिस: या महिन्याच्या ऑर्डर ग्राहक यादीशी जोडा, म्हणजे प्रत्येक ग्राहकाचे शहर आणि फोन येईल, मग डिलिव्हरीसाठी एक फाइल डाउनलोड करा.',
    tip3: 'वर्गातील उपक्रम: दोन्ही नमुना फाइल्स प्रिंट करा. विद्यार्थी कागदावर हाताने जोडतील, मग ॲपने तपासतील. फक्त 7 विद्यार्थी जुळले, तरी इनर जॉइनमध्ये 9 ओळी का?',
    tip4: 'की दोन्ही फाइल्समध्ये एकाच पद्धतीने लिहिलेली हवी. आधी ती स्वच्छ करा (जागा, मोठी-लहान अक्षरे, "007" विरुद्ध "7") इथल्या पर्यायांनी किंवा डेटा स्वच्छता लॅब ॲपने.',
    tip5: 'एकाखाली एक: 12 महिन्यांच्या विक्री फाइल्स एकत्र करून वर्षाची एक फाइल बनवा, "मूळ फाइल" कॉलमसह जो प्रत्येक ओळ कुठून आली ते सांगतो.',
    words_title: 'महत्त्वाचे शब्द: आत काय घडते',
    w_key: '<b>की (Key)</b>: ओळी जुळवणारा कॉलम, उदा. रोल नंबर किंवा ग्राहक ID. चांगली की दोन्ही फाइल्समध्ये एकाच पद्धतीने लिहिलेली असते आणि किमान एका फाइलमध्ये एकदाच असते.',
    w_inner: '<b>इनर जॉइन</b>: फक्त दोन्ही फाइल्समध्ये जुळणाऱ्या ओळी ठेवते (वेन आकृतीचा मधला भाग).',
    w_outer: '<b>लेफ्ट, राइट आणि फुल आउटर जॉइन</b>: न जुळलेल्या ओळीही ठेवतात, A मधून, B मधून किंवा दोन्हींतून. नसलेली बाजू रिकामी राहते.',
    w_many: '<b>एक-ते-अनेक</b>: A ची एक की B च्या अनेक ओळींशी जुळते (एक विद्यार्थी, अनेक विषय). निकालात प्रत्येक जुळणीची एक ओळ होते.',
    w_union: '<b>एकाखाली एक (append / union)</b>: फाइल्स एकाखाली एक ठेवणे. यामुळे ओळी वाढतात; जॉइनमुळे कॉलम वाढतात.'
  },
  gu: {
    app_title: 'ફાઇલો જોડો અને ભેગી કરો',
    intro: 'બે CSV ફાઇલોને એક મળતા કૉલમથી જોડો (VLOOKUP ની જેમ), અથવા ઘણા મહિનાની ફાઇલો એકની નીચે એક મૂકો. શું મળ્યું, શું ન મળ્યું તે જુઓ અને પરિણામ ડાઉનલોડ કરો.',
    mode_join: 'બે ફાઇલો જોડો', mode_stack: 'ઘણી ફાઇલો એકની નીચે એક',
    h_files: '1. તમારી બે ફાઇલો', try_sample: 'નમૂનો અજમાવો:', sample_students: 'વિદ્યાર્થીઓ + ગુણ', sample_orders: 'ઓર્ડર + ગ્રાહકો',
    file_a: 'ફાઇલ A (ડાબી)', file_b: 'ફાઇલ B (જમણી)', open_csv: 'CSV ખોલો', paste_data: 'ડેટા પેસ્ટ કરો',
    paste_ph: 'Excel કે Google Sheets માંથી હરોળો, અથવા CSV લખાણ પેસ્ટ કરો', use_paste: 'પેસ્ટ કરેલો ડેટા વાપરો', pasted_a: 'પેસ્ટ-A', pasted_b: 'પેસ્ટ-B',
    drop_hint: 'CSV ફાઇલો અહીં ખેંચીને પણ મૂકી શકો. Excel માં: File → Save as → CSV. તમારી ફાઇલો આ ડિવાઇસ પર જ રહે છે.',
    file_info: '{rows} હરોળ, {cols} કૉલમ',
    err_empty: 'એક પણ હરોળ મળી નહીં. પહેલી હરોળમાં કૉલમનાં નામ હોવાં જોઈએ.', err_file: 'આ ફાઇલ વાંચી શકાઈ નહીં.',
    err_excel: 'પહેલાં શીટને CSV તરીકે સેવ કરો (Excel: File → Save as → CSV).', big_note: 'આ ફાઇલ મોટી છે, એટલે આવતી વખત માટે સેવ નથી થઈ.',
    h_match: '2. હરોળ કેવી રીતે મેળવવી', key_a: 'A નો કી કૉલમ', key_b: 'B નો કી કૉલમ',
    opt_trim: 'વધારાની જગ્યા અવગણો', opt_icase: 'મોટા-નાના અક્ષર અવગણો', opt_num: '"007" અને "7" ને સરખા ગણો', swap: 'A અને B અદલબદલ',
    join_type: 'જોડવાની રીત', type_inner: 'ઇનર', type_left: 'લેફ્ટ', type_right: 'રાઇટ', type_full: 'ફુલ આઉટર',
    help_inner: 'ઇનર: ફક્ત એ હરોળ જેની કી બંને ફાઇલોમાં છે.',
    help_left: 'લેફ્ટ: A ની દરેક હરોળ; કી મળે ત્યાં B ની માહિતી, ન મળે ત્યાં ખાલી.',
    help_right: 'રાઇટ: B ની દરેક હરોળ; કી મળે ત્યાં A ની માહિતી.',
    help_full: 'ફુલ આઉટર: બંને ફાઇલોની દરેક હરોળ, જ્યાં શક્ય હોય ત્યાં મેળવીને.',
    venn_label: 'જોડવાની રીતની વેન આકૃતિ',
    h_result: '3. પરિણામ', st_matched: 'A ની મળેલી હરોળ', only_in: 'ફક્ત {name} માં', st_rows: 'પરિણામમાં હરોળ',
    warn_dup_b: '{name} માં {n} કી એકથી વધુ વાર છે. આ એક-થી-અનેક (one-to-many) છે: A ની હરોળ દરેક મેળ માટે એક વાર આવે છે, એટલે પરિણામમાં A કરતાં વધુ હરોળ હોઈ શકે.',
    note_dup_a: '{name} માં {n} કી એકથી વધુ વાર છે. એ બરાબર છે (અનેક-થી-એક): એ બધી હરોળને એ જ માહિતી મળે છે.',
    warn_blank: '{n} હરોળમાં કી ખાલી છે. ખાલી કી ક્યારેય મળતી નથી.',
    warn_none: 'એક પણ હરોળ મળી નહીં. સાચા કી કૉલમ પસંદ કર્યા છે કે નહીં તે જુઓ.',
    hint_numeric: 'સૂચન: કેટલીક કી એક ફાઇલમાં "007" અને બીજીમાં "7" છે. તેમને મેળવવા "007 અને 7 ને સરખા ગણો" પર ટિક કરો.',
    out_cols: 'પરિણામના કૉલમ (છુપાવવા કે બતાવવા દબાવો):', no_rows: 'પરિણામમાં કોઈ હરોળ નથી.',
    page_info: 'હરોળ {from}–{to}, કુલ {total}', legend_nm: 'પટ્ટાવાળા સેલ: બીજી ફાઇલમાં મળતી હરોળ નથી.', download_csv: 'CSV ડાઉનલોડ કરો',
    h_unmatched: '4. જે હરોળ ન મળી', um_note: 'પરિણામ પર ભરોસો કરતાં પહેલાં આ જુઓ. કી માં જોડણીની ભૂલ કે એક વધારાનો 0 સૌથી સામાન્ય કારણ છે.',
    only_in_n: '{name}: {n}', um_none: 'દરેક હરોળને મેળ મળ્યો.', download_um: 'આ હરોળ ડાઉનલોડ કરો', unmatched_file: 'ન-મળેલી',
    h_lookup: 'આ જ છે VLOOKUP / XLOOKUP',
    lookup_1: '<b>લેફ્ટ જૉઇન</b> એ જ કરે છે જે Excel કે Google Sheets માં <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> કે <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> કરે છે, પણ બધા કૉલમ એકસાથે.',
    lookup_2: 'એક ફરક: VLOOKUP અને XLOOKUP <b>પહેલા</b> મેળ પર અટકે છે. જૉઇન <b>દરેક</b> મેળ આપે છે, એટલે એક-થી-અનેક કી થી હરોળ વધે છે. કંઈ ન મળે તો VLOOKUP #N/A બતાવે છે; લેફ્ટ જૉઇન સેલ ખાલી રાખે છે.',
    h_stack: '1. એકની નીચે એક મૂકવાની ફાઇલો',
    stack_note: 'સરખા કૉલમવાળી ફાઇલો માટે, જેમ કે જાન્યુઆરી, ફેબ્રુઆરી અને માર્ચનું વેચાણ. કૉલમ નામથી મેળવાય છે, ક્રમ જુદો હોય તો પણ.',
    st_empty: 'હજી કોઈ ફાઇલ નથી. CSV ફાઇલો ઉમેરો કે નમૂનો ખોલો.', st_add: 'CSV ફાઇલો ઉમેરો', st_sample: 'નમૂનો: 3 મહિનાનું વેચાણ', st_clear: 'બધું દૂર કરો',
    st_loose: 'કૉલમનાં નામ મેળવતી વખતે મોટા-નાના અક્ષર અને વધારાની જગ્યા અવગણો', st_source: '"મૂળ ફાઇલ" કૉલમ ઉમેરો', source_col: 'મૂળ ફાઇલ',
    h_stacked: '2. ભેગું કરેલું પરિણામ', st_total: '{files} ફાઇલોમાંથી {rows} હરોળ, {cols} કૉલમ', st_added: '{n} નવા કૉલમ', st_missing: 'નથી: {cols}',
    remove_file: 'ફાઇલ દૂર કરો', legend_blank: 'પટ્ટાવાળા સેલ ખાલી છે (ઘણી વાર કારણ કે એ ફાઇલમાં એ કૉલમ નહોતો).', stacked_file: 'ભેગું',
    tip1: '"વિદ્યાર્થીઓ + ગુણ" નમૂનાથી શરૂ કરો અને ઇનર, લેફ્ટ, રાઇટ, ફુલ આઉટર બદલીને જુઓ. હરોળની સંખ્યા અને વેન આકૃતિ બદલાતી જુઓ.',
    tip2: 'ઑફિસ: આ મહિનાના ઓર્ડરને ગ્રાહક યાદી સાથે જોડો જેથી દરેક ગ્રાહકનું શહેર અને ફોન આવી જાય, પછી ડિલિવરી માટે એક ફાઇલ ડાઉનલોડ કરો.',
    tip3: 'વર્ગ પ્રવૃત્તિ: બંને નમૂના ફાઇલો પ્રિન્ટ કરો. વિદ્યાર્થીઓ કાગળ પર હાથથી જોડે, પછી ઍપથી તપાસે. ફક્ત 7 વિદ્યાર્થી મળ્યા, તો ઇનર જૉઇનમાં 9 હરોળ કેમ?',
    tip4: 'કી બંને ફાઇલોમાં એક જ રીતે લખેલી હોવી જોઈએ. પહેલાં તેને સાફ કરો (જગ્યા, મોટા-નાના અક્ષર, "007" સામે "7") અહીંના વિકલ્પોથી કે ડેટા સફાઈ લૅબ ઍપથી.',
    tip5: 'એકની નીચે એક: 12 મહિનાની વેચાણ ફાઇલો ભેગી કરી વર્ષની એક ફાઇલ બનાવો, "મૂળ ફાઇલ" કૉલમ સાથે જે દરેક હરોળ ક્યાંથી આવી તે બતાવે.',
    words_title: 'જાણવા જેવા શબ્દો: અંદર શું થાય છે',
    w_key: '<b>કી (Key)</b>: હરોળ મેળવતો કૉલમ, જેમ કે રોલ નંબર કે ગ્રાહક ID. સારી કી બંને ફાઇલોમાં એક જ રીતે લખેલી હોય અને ઓછામાં ઓછી એક ફાઇલમાં એક જ વાર હોય.',
    w_inner: '<b>ઇનર જૉઇન</b>: ફક્ત બંને ફાઇલોમાં મળતી હરોળ રાખે છે (વેન આકૃતિનો વચ્ચેનો ભાગ).',
    w_outer: '<b>લેફ્ટ, રાઇટ અને ફુલ આઉટર જૉઇન</b>: ન મળેલી હરોળ પણ રાખે છે, A માંથી, B માંથી કે બંનેમાંથી. જે બાજુ નથી તે ખાલી રહે છે.',
    w_many: '<b>એક-થી-અનેક</b>: A ની એક કી B ની ઘણી હરોળ સાથે મળે છે (એક વિદ્યાર્થી, ઘણા વિષય). પરિણામમાં દરેક મેળની એક હરોળ બને છે.',
    w_union: '<b>એકની નીચે એક (append / union)</b>: ફાઇલોને એકની નીચે એક મૂકવી. તેનાથી હરોળ વધે છે; જૉઇનથી કૉલમ વધે છે.'
  },
  pa: {
    app_title: 'ਫ਼ਾਈਲਾਂ ਜੋੜੋ ਅਤੇ ਮਿਲਾਓ',
    intro: 'ਦੋ CSV ਫ਼ਾਈਲਾਂ ਨੂੰ ਇੱਕ ਮਿਲਦੇ ਕਾਲਮ ਨਾਲ ਜੋੜੋ (VLOOKUP ਵਾਂਗ), ਜਾਂ ਕਈ ਮਹੀਨਿਆਂ ਦੀਆਂ ਫ਼ਾਈਲਾਂ ਇੱਕ ਦੇ ਹੇਠਾਂ ਇੱਕ ਰੱਖੋ। ਦੇਖੋ ਕੀ ਮਿਲਿਆ, ਕੀ ਨਹੀਂ, ਅਤੇ ਨਤੀਜਾ ਡਾਊਨਲੋਡ ਕਰੋ।',
    mode_join: 'ਦੋ ਫ਼ਾਈਲਾਂ ਜੋੜੋ', mode_stack: 'ਕਈ ਫ਼ਾਈਲਾਂ ਇੱਕ ਦੇ ਹੇਠਾਂ ਇੱਕ',
    h_files: '1. ਤੁਹਾਡੀਆਂ ਦੋ ਫ਼ਾਈਲਾਂ', try_sample: 'ਨਮੂਨਾ ਅਜ਼ਮਾਓ:', sample_students: 'ਵਿਦਿਆਰਥੀ + ਅੰਕ', sample_orders: 'ਆਰਡਰ + ਗਾਹਕ',
    file_a: 'ਫ਼ਾਈਲ A (ਖੱਬੀ)', file_b: 'ਫ਼ਾਈਲ B (ਸੱਜੀ)', open_csv: 'CSV ਖੋਲ੍ਹੋ', paste_data: 'ਡਾਟਾ ਪੇਸਟ ਕਰੋ',
    paste_ph: 'Excel ਜਾਂ Google Sheets ਤੋਂ ਕਤਾਰਾਂ, ਜਾਂ CSV ਲਿਖਤ ਪੇਸਟ ਕਰੋ', use_paste: 'ਪੇਸਟ ਕੀਤਾ ਡਾਟਾ ਵਰਤੋ', pasted_a: 'ਪੇਸਟ-A', pasted_b: 'ਪੇਸਟ-B',
    drop_hint: 'CSV ਫ਼ਾਈਲਾਂ ਇੱਥੇ ਖਿੱਚ ਕੇ ਵੀ ਛੱਡ ਸਕਦੇ ਹੋ। Excel ਵਿੱਚ: File → Save as → CSV। ਤੁਹਾਡੀਆਂ ਫ਼ਾਈਲਾਂ ਇਸੇ ਡਿਵਾਈਸ ਉੱਤੇ ਰਹਿੰਦੀਆਂ ਹਨ।',
    file_info: '{rows} ਕਤਾਰਾਂ, {cols} ਕਾਲਮ',
    err_empty: 'ਕੋਈ ਕਤਾਰ ਨਹੀਂ ਮਿਲੀ। ਪਹਿਲੀ ਕਤਾਰ ਵਿੱਚ ਕਾਲਮਾਂ ਦੇ ਨਾਮ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ।', err_file: 'ਇਹ ਫ਼ਾਈਲ ਪੜ੍ਹੀ ਨਹੀਂ ਜਾ ਸਕੀ।',
    err_excel: 'ਪਹਿਲਾਂ ਸ਼ੀਟ ਨੂੰ CSV ਵਜੋਂ ਸੇਵ ਕਰੋ (Excel: File → Save as → CSV)।', big_note: 'ਇਹ ਫ਼ਾਈਲ ਵੱਡੀ ਹੈ, ਇਸ ਲਈ ਅਗਲੀ ਵਾਰ ਲਈ ਸੇਵ ਨਹੀਂ ਹੋਈ।',
    h_match: '2. ਕਤਾਰਾਂ ਕਿਵੇਂ ਮਿਲਾਈਏ', key_a: 'A ਦਾ ਕੀ ਕਾਲਮ', key_b: 'B ਦਾ ਕੀ ਕਾਲਮ',
    opt_trim: 'ਵਾਧੂ ਸਪੇਸ ਅਣਡਿੱਠੀ ਕਰੋ', opt_icase: 'ਵੱਡੇ-ਛੋਟੇ ਅੱਖਰ ਅਣਡਿੱਠੇ ਕਰੋ', opt_num: '"007" ਅਤੇ "7" ਨੂੰ ਇੱਕੋ ਮੰਨੋ', swap: 'A ਅਤੇ B ਅਦਲਾ-ਬਦਲੀ',
    join_type: 'ਜੋੜਨ ਦਾ ਤਰੀਕਾ', type_inner: 'ਇਨਰ', type_left: 'ਲੈਫ਼ਟ', type_right: 'ਰਾਈਟ', type_full: 'ਫੁੱਲ ਆਊਟਰ',
    help_inner: 'ਇਨਰ: ਸਿਰਫ਼ ਉਹ ਕਤਾਰਾਂ ਜਿਨ੍ਹਾਂ ਦੀ ਕੀ ਦੋਵਾਂ ਫ਼ਾਈਲਾਂ ਵਿੱਚ ਹੈ।',
    help_left: 'ਲੈਫ਼ਟ: A ਦੀ ਹਰ ਕਤਾਰ; ਕੀ ਮਿਲੇ ਤਾਂ B ਦੀ ਜਾਣਕਾਰੀ, ਨਾ ਮਿਲੇ ਤਾਂ ਖ਼ਾਲੀ।',
    help_right: 'ਰਾਈਟ: B ਦੀ ਹਰ ਕਤਾਰ; ਕੀ ਮਿਲੇ ਤਾਂ A ਦੀ ਜਾਣਕਾਰੀ।',
    help_full: 'ਫੁੱਲ ਆਊਟਰ: ਦੋਵਾਂ ਫ਼ਾਈਲਾਂ ਦੀ ਹਰ ਕਤਾਰ, ਜਿੱਥੇ ਹੋ ਸਕੇ ਮਿਲਾ ਕੇ।',
    venn_label: 'ਜੋੜਨ ਦੇ ਤਰੀਕੇ ਦਾ ਵੈੱਨ ਚਿੱਤਰ',
    h_result: '3. ਨਤੀਜਾ', st_matched: 'A ਦੀਆਂ ਮਿਲੀਆਂ ਕਤਾਰਾਂ', only_in: 'ਸਿਰਫ਼ {name} ਵਿੱਚ', st_rows: 'ਨਤੀਜੇ ਵਿੱਚ ਕਤਾਰਾਂ',
    warn_dup_b: '{name} ਵਿੱਚ {n} ਕੀ ਇੱਕ ਤੋਂ ਵੱਧ ਵਾਰ ਹਨ। ਇਹ ਇੱਕ-ਤੋਂ-ਅਨੇਕ (one-to-many) ਹੈ: A ਦੀ ਕਤਾਰ ਹਰ ਮੇਲ ਲਈ ਇੱਕ ਵਾਰ ਆਉਂਦੀ ਹੈ, ਇਸ ਲਈ ਨਤੀਜੇ ਵਿੱਚ A ਤੋਂ ਵੱਧ ਕਤਾਰਾਂ ਹੋ ਸਕਦੀਆਂ ਹਨ।',
    note_dup_a: '{name} ਵਿੱਚ {n} ਕੀ ਇੱਕ ਤੋਂ ਵੱਧ ਵਾਰ ਹਨ। ਇਹ ਠੀਕ ਹੈ (ਅਨੇਕ-ਤੋਂ-ਇੱਕ): ਉਨ੍ਹਾਂ ਸਾਰੀਆਂ ਕਤਾਰਾਂ ਨੂੰ ਉਹੀ ਜਾਣਕਾਰੀ ਮਿਲਦੀ ਹੈ।',
    warn_blank: '{n} ਕਤਾਰਾਂ ਵਿੱਚ ਕੀ ਖ਼ਾਲੀ ਹੈ। ਖ਼ਾਲੀ ਕੀ ਕਦੇ ਨਹੀਂ ਮਿਲਦੀ।',
    warn_none: 'ਕੋਈ ਕਤਾਰ ਨਹੀਂ ਮਿਲੀ। ਦੇਖੋ ਕਿ ਸਹੀ ਕੀ ਕਾਲਮ ਚੁਣੇ ਹਨ।',
    hint_numeric: 'ਸੁਝਾਅ: ਕੁਝ ਕੀ ਇੱਕ ਫ਼ਾਈਲ ਵਿੱਚ "007" ਅਤੇ ਦੂਜੀ ਵਿੱਚ "7" ਹਨ। ਮਿਲਾਉਣ ਲਈ "007 ਅਤੇ 7 ਨੂੰ ਇੱਕੋ ਮੰਨੋ" ਉੱਤੇ ਟਿੱਕ ਕਰੋ।',
    out_cols: 'ਨਤੀਜੇ ਦੇ ਕਾਲਮ (ਲੁਕਾਉਣ ਜਾਂ ਦਿਖਾਉਣ ਲਈ ਦਬਾਓ):', no_rows: 'ਨਤੀਜੇ ਵਿੱਚ ਕੋਈ ਕਤਾਰ ਨਹੀਂ।',
    page_info: 'ਕਤਾਰਾਂ {from}–{to}, ਕੁੱਲ {total}', legend_nm: 'ਧਾਰੀਦਾਰ ਸੈੱਲ: ਦੂਜੀ ਫ਼ਾਈਲ ਵਿੱਚ ਮਿਲਦੀ ਕਤਾਰ ਨਹੀਂ।', download_csv: 'CSV ਡਾਊਨਲੋਡ ਕਰੋ',
    h_unmatched: '4. ਜੋ ਕਤਾਰਾਂ ਨਹੀਂ ਮਿਲੀਆਂ', um_note: 'ਨਤੀਜੇ ਉੱਤੇ ਭਰੋਸਾ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਇਹ ਦੇਖੋ। ਕੀ ਵਿੱਚ ਸ਼ਬਦ-ਜੋੜ ਦੀ ਗ਼ਲਤੀ ਜਾਂ ਇੱਕ ਵਾਧੂ 0 ਸਭ ਤੋਂ ਆਮ ਕਾਰਨ ਹੈ।',
    only_in_n: '{name}: {n}', um_none: 'ਹਰ ਕਤਾਰ ਦਾ ਮੇਲ ਮਿਲ ਗਿਆ।', download_um: 'ਇਹ ਕਤਾਰਾਂ ਡਾਊਨਲੋਡ ਕਰੋ', unmatched_file: 'ਨਹੀਂ-ਮਿਲੀਆਂ',
    h_lookup: 'ਇਹੀ ਹੈ VLOOKUP / XLOOKUP',
    lookup_1: '<b>ਲੈਫ਼ਟ ਜੌਇਨ</b> ਉਹੀ ਕਰਦਾ ਹੈ ਜੋ Excel ਜਾਂ Google Sheets ਵਿੱਚ <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> ਜਾਂ <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> ਕਰਦਾ ਹੈ, ਪਰ ਸਾਰੇ ਕਾਲਮ ਇਕੱਠੇ।',
    lookup_2: 'ਇੱਕ ਫ਼ਰਕ: VLOOKUP ਅਤੇ XLOOKUP <b>ਪਹਿਲੇ</b> ਮੇਲ ਉੱਤੇ ਰੁਕ ਜਾਂਦੇ ਹਨ। ਜੌਇਨ <b>ਹਰ</b> ਮੇਲ ਦਿੰਦਾ ਹੈ, ਇਸੇ ਲਈ ਇੱਕ-ਤੋਂ-ਅਨੇਕ ਕੀ ਨਾਲ ਕਤਾਰਾਂ ਵਧਦੀਆਂ ਹਨ। ਕੁਝ ਨਾ ਮਿਲੇ ਤਾਂ VLOOKUP #N/A ਦਿਖਾਉਂਦਾ ਹੈ; ਲੈਫ਼ਟ ਜੌਇਨ ਸੈੱਲ ਖ਼ਾਲੀ ਛੱਡਦਾ ਹੈ।',
    h_stack: '1. ਇੱਕ ਦੇ ਹੇਠਾਂ ਇੱਕ ਰੱਖਣ ਵਾਲੀਆਂ ਫ਼ਾਈਲਾਂ',
    stack_note: 'ਇੱਕੋ ਜਿਹੇ ਕਾਲਮਾਂ ਵਾਲੀਆਂ ਫ਼ਾਈਲਾਂ ਲਈ, ਜਿਵੇਂ ਜਨਵਰੀ, ਫ਼ਰਵਰੀ ਅਤੇ ਮਾਰਚ ਦੀ ਵਿਕਰੀ। ਕਾਲਮ ਨਾਮ ਨਾਲ ਮਿਲਾਏ ਜਾਂਦੇ ਹਨ, ਭਾਵੇਂ ਕ੍ਰਮ ਵੱਖਰਾ ਹੋਵੇ।',
    st_empty: 'ਅਜੇ ਕੋਈ ਫ਼ਾਈਲ ਨਹੀਂ। CSV ਫ਼ਾਈਲਾਂ ਜੋੜੋ ਜਾਂ ਨਮੂਨਾ ਖੋਲ੍ਹੋ।', st_add: 'CSV ਫ਼ਾਈਲਾਂ ਜੋੜੋ', st_sample: 'ਨਮੂਨਾ: 3 ਮਹੀਨਿਆਂ ਦੀ ਵਿਕਰੀ', st_clear: 'ਸਭ ਹਟਾਓ',
    st_loose: 'ਕਾਲਮਾਂ ਦੇ ਨਾਮ ਮਿਲਾਉਂਦੇ ਸਮੇਂ ਵੱਡੇ-ਛੋਟੇ ਅੱਖਰ ਅਤੇ ਵਾਧੂ ਸਪੇਸ ਅਣਡਿੱਠੇ ਕਰੋ', st_source: '"ਸਰੋਤ ਫ਼ਾਈਲ" ਕਾਲਮ ਜੋੜੋ', source_col: 'ਸਰੋਤ ਫ਼ਾਈਲ',
    h_stacked: '2. ਇਕੱਠਾ ਕੀਤਾ ਨਤੀਜਾ', st_total: '{files} ਫ਼ਾਈਲਾਂ ਤੋਂ {rows} ਕਤਾਰਾਂ, {cols} ਕਾਲਮ', st_added: '{n} ਨਵੇਂ ਕਾਲਮ', st_missing: 'ਨਹੀਂ ਹਨ: {cols}',
    remove_file: 'ਫ਼ਾਈਲ ਹਟਾਓ', legend_blank: 'ਧਾਰੀਦਾਰ ਸੈੱਲ ਖ਼ਾਲੀ ਹਨ (ਅਕਸਰ ਇਸ ਲਈ ਕਿ ਉਸ ਫ਼ਾਈਲ ਵਿੱਚ ਉਹ ਕਾਲਮ ਨਹੀਂ ਸੀ)।', stacked_file: 'ਇਕੱਠਾ',
    tip1: '"ਵਿਦਿਆਰਥੀ + ਅੰਕ" ਨਮੂਨੇ ਨਾਲ ਸ਼ੁਰੂ ਕਰੋ ਅਤੇ ਇਨਰ, ਲੈਫ਼ਟ, ਰਾਈਟ, ਫੁੱਲ ਆਊਟਰ ਬਦਲ ਕੇ ਦੇਖੋ। ਕਤਾਰਾਂ ਦੀ ਗਿਣਤੀ ਅਤੇ ਵੈੱਨ ਚਿੱਤਰ ਬਦਲਦੇ ਦੇਖੋ।',
    tip2: 'ਦਫ਼ਤਰ: ਇਸ ਮਹੀਨੇ ਦੇ ਆਰਡਰ ਗਾਹਕ ਸੂਚੀ ਨਾਲ ਜੋੜੋ ਤਾਂ ਜੋ ਹਰ ਗਾਹਕ ਦਾ ਸ਼ਹਿਰ ਅਤੇ ਫ਼ੋਨ ਆ ਜਾਵੇ, ਫਿਰ ਡਿਲੀਵਰੀ ਲਈ ਇੱਕ ਫ਼ਾਈਲ ਡਾਊਨਲੋਡ ਕਰੋ।',
    tip3: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: ਦੋਵੇਂ ਨਮੂਨਾ ਫ਼ਾਈਲਾਂ ਪ੍ਰਿੰਟ ਕਰੋ। ਵਿਦਿਆਰਥੀ ਕਾਗ਼ਜ਼ ਉੱਤੇ ਹੱਥ ਨਾਲ ਜੋੜਨ, ਫਿਰ ਐਪ ਨਾਲ ਜਾਂਚਣ। ਸਿਰਫ਼ 7 ਵਿਦਿਆਰਥੀ ਮਿਲੇ, ਫਿਰ ਇਨਰ ਜੌਇਨ ਵਿੱਚ 9 ਕਤਾਰਾਂ ਕਿਉਂ?',
    tip4: 'ਕੀ ਦੋਵਾਂ ਫ਼ਾਈਲਾਂ ਵਿੱਚ ਇੱਕੋ ਤਰ੍ਹਾਂ ਲਿਖੀ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ। ਪਹਿਲਾਂ ਉਸ ਨੂੰ ਸਾਫ਼ ਕਰੋ (ਸਪੇਸ, ਵੱਡੇ-ਛੋਟੇ ਅੱਖਰ, "007" ਬਨਾਮ "7") ਇੱਥੋਂ ਦੇ ਵਿਕਲਪਾਂ ਨਾਲ ਜਾਂ ਡਾਟਾ ਸਫ਼ਾਈ ਲੈਬ ਐਪ ਨਾਲ।',
    tip5: 'ਇੱਕ ਦੇ ਹੇਠਾਂ ਇੱਕ: 12 ਮਹੀਨਿਆਂ ਦੀਆਂ ਵਿਕਰੀ ਫ਼ਾਈਲਾਂ ਮਿਲਾ ਕੇ ਸਾਲ ਦੀ ਇੱਕ ਫ਼ਾਈਲ ਬਣਾਓ, "ਸਰੋਤ ਫ਼ਾਈਲ" ਕਾਲਮ ਨਾਲ ਜੋ ਦੱਸੇ ਕਿ ਹਰ ਕਤਾਰ ਕਿੱਥੋਂ ਆਈ।',
    words_title: 'ਜ਼ਰੂਰੀ ਸ਼ਬਦ: ਅੰਦਰ ਕੀ ਹੋ ਰਿਹਾ ਹੈ',
    w_key: '<b>ਕੀ (Key)</b>: ਕਤਾਰਾਂ ਮਿਲਾਉਣ ਵਾਲਾ ਕਾਲਮ, ਜਿਵੇਂ ਰੋਲ ਨੰਬਰ ਜਾਂ ਗਾਹਕ ID। ਚੰਗੀ ਕੀ ਦੋਵਾਂ ਫ਼ਾਈਲਾਂ ਵਿੱਚ ਇੱਕੋ ਤਰ੍ਹਾਂ ਲਿਖੀ ਹੁੰਦੀ ਹੈ ਅਤੇ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਫ਼ਾਈਲ ਵਿੱਚ ਇੱਕ ਵਾਰ ਹੀ ਹੁੰਦੀ ਹੈ।',
    w_inner: '<b>ਇਨਰ ਜੌਇਨ</b>: ਸਿਰਫ਼ ਦੋਵਾਂ ਫ਼ਾਈਲਾਂ ਵਿੱਚ ਮਿਲਦੀਆਂ ਕਤਾਰਾਂ ਰੱਖਦਾ ਹੈ (ਵੈੱਨ ਚਿੱਤਰ ਦਾ ਵਿਚਕਾਰਲਾ ਹਿੱਸਾ)।',
    w_outer: '<b>ਲੈਫ਼ਟ, ਰਾਈਟ ਅਤੇ ਫੁੱਲ ਆਊਟਰ ਜੌਇਨ</b>: ਨਾ ਮਿਲੀਆਂ ਕਤਾਰਾਂ ਵੀ ਰੱਖਦੇ ਹਨ, A ਤੋਂ, B ਤੋਂ, ਜਾਂ ਦੋਵਾਂ ਤੋਂ। ਜੋ ਪਾਸਾ ਨਹੀਂ ਮਿਲਿਆ ਉਹ ਖ਼ਾਲੀ ਰਹਿੰਦਾ ਹੈ।',
    w_many: '<b>ਇੱਕ-ਤੋਂ-ਅਨੇਕ</b>: A ਦੀ ਇੱਕ ਕੀ B ਦੀਆਂ ਕਈ ਕਤਾਰਾਂ ਨਾਲ ਮਿਲਦੀ ਹੈ (ਇੱਕ ਵਿਦਿਆਰਥੀ, ਕਈ ਵਿਸ਼ੇ)। ਨਤੀਜੇ ਵਿੱਚ ਹਰ ਮੇਲ ਦੀ ਇੱਕ ਕਤਾਰ ਬਣਦੀ ਹੈ।',
    w_union: '<b>ਇੱਕ ਦੇ ਹੇਠਾਂ ਇੱਕ (append / union)</b>: ਫ਼ਾਈਲਾਂ ਨੂੰ ਇੱਕ ਦੇ ਹੇਠਾਂ ਇੱਕ ਰੱਖਣਾ। ਇਸ ਨਾਲ ਕਤਾਰਾਂ ਵਧਦੀਆਂ ਹਨ; ਜੌਇਨ ਨਾਲ ਕਾਲਮ ਵਧਦੇ ਹਨ।'
  },
  or: {
    app_title: 'ଫାଇଲ ଯୋଡ଼ନ୍ତୁ ଓ ମିଶାନ୍ତୁ',
    intro: 'ଦୁଇଟି CSV ଫାଇଲକୁ ଏକ ମେଳ ଖାଉଥିବା ସ୍ତମ୍ଭ ଦ୍ୱାରା ଯୋଡ଼ନ୍ତୁ (VLOOKUP ଭଳି), କିମ୍ବା ଅନେକ ମାସର ଫାଇଲ ଗୋଟିଏ ତଳେ ଗୋଟିଏ ରଖନ୍ତୁ। କ\'ଣ ମିଳିଲା, କ\'ଣ ମିଳିଲା ନାହିଁ ଦେଖନ୍ତୁ ଓ ଫଳାଫଳ ଡାଉନଲୋଡ କରନ୍ତୁ।',
    mode_join: 'ଦୁଇଟି ଫାଇଲ ଯୋଡ଼ନ୍ତୁ', mode_stack: 'ଅନେକ ଫାଇଲ ଗୋଟିଏ ତଳେ ଗୋଟିଏ',
    h_files: '1. ଆପଣଙ୍କ ଦୁଇଟି ଫାଇଲ', try_sample: 'ନମୁନା ଦେଖନ୍ତୁ:', sample_students: 'ଛାତ୍ରଛାତ୍ରୀ + ନମ୍ବର', sample_orders: 'ଅର୍ଡର + ଗ୍ରାହକ',
    file_a: 'ଫାଇଲ A (ବାମ)', file_b: 'ଫାଇଲ B (ଡାହାଣ)', open_csv: 'CSV ଖୋଲନ୍ତୁ', paste_data: 'ଡାଟା ପେଷ୍ଟ କରନ୍ତୁ',
    paste_ph: 'Excel କିମ୍ବା Google Sheets ରୁ ଧାଡ଼ି, କିମ୍ବା CSV ଲେଖା ପେଷ୍ଟ କରନ୍ତୁ', use_paste: 'ପେଷ୍ଟ କରିଥିବା ଡାଟା ବ୍ୟବହାର କରନ୍ତୁ', pasted_a: 'ପେଷ୍ଟ-A', pasted_b: 'ପେଷ୍ଟ-B',
    drop_hint: 'CSV ଫାଇଲ ଏଠାକୁ ଟାଣି ଆଣି ମଧ୍ୟ ଛାଡ଼ିପାରିବେ। Excel ରେ: File → Save as → CSV। ଆପଣଙ୍କ ଫାଇଲ ଏହି ଡିଭାଇସରେ ହିଁ ରହେ।',
    file_info: '{rows}ଟି ଧାଡ଼ି, {cols}ଟି ସ୍ତମ୍ଭ',
    err_empty: 'କୌଣସି ଧାଡ଼ି ମିଳିଲା ନାହିଁ। ପ୍ରଥମ ଧାଡ଼ିରେ ସ୍ତମ୍ଭର ନାମ ରହିବା ଦରକାର।', err_file: 'ଏହି ଫାଇଲ ପଢ଼ିହେଲା ନାହିଁ।',
    err_excel: 'ପ୍ରଥମେ ଶିଟ୍‌କୁ CSV ଭାବେ ସେଭ କରନ୍ତୁ (Excel: File → Save as → CSV)।', big_note: 'ଏହି ଫାଇଲ ବଡ଼, ତେଣୁ ପରବର୍ତ୍ତୀ ଥର ପାଇଁ ସେଭ ହୋଇନାହିଁ।',
    h_match: '2. ଧାଡ଼ି କିପରି ମିଳାଇବେ', key_a: 'A ର କି ସ୍ତମ୍ଭ', key_b: 'B ର କି ସ୍ତମ୍ଭ',
    opt_trim: 'ଅତିରିକ୍ତ ସ୍ପେସ ଉପେକ୍ଷା କରନ୍ତୁ', opt_icase: 'ବଡ଼-ଛୋଟ ଅକ୍ଷର ଉପେକ୍ଷା କରନ୍ତୁ', opt_num: '"007" ଓ "7" କୁ ସମାନ ଧରନ୍ତୁ', swap: 'A ଓ B ଅଦଳବଦଳ',
    join_type: 'ଯୋଡ଼ିବାର ପ୍ରକାର', type_inner: 'ଇନର', type_left: 'ଲେଫ୍ଟ', type_right: 'ରାଇଟ', type_full: 'ଫୁଲ ଆଉଟର',
    help_inner: 'ଇନର: କେବଳ ସେହି ଧାଡ଼ି ଯାହାର କି ଦୁଇଟି ଫାଇଲରେ ଅଛି।',
    help_left: 'ଲେଫ୍ଟ: A ର ପ୍ରତି ଧାଡ଼ି; କି ମିଳିଲେ B ର ତଥ୍ୟ, ନ ମିଳିଲେ ଖାଲି।',
    help_right: 'ରାଇଟ: B ର ପ୍ରତି ଧାଡ଼ି; କି ମିଳିଲେ A ର ତଥ୍ୟ।',
    help_full: 'ଫୁଲ ଆଉଟର: ଦୁଇଟି ଫାଇଲର ପ୍ରତି ଧାଡ଼ି, ଯେଉଁଠି ସମ୍ଭବ ମିଳାଇ।',
    venn_label: 'ଯୋଡ଼ିବା ପ୍ରକାରର ଭେନ ଚିତ୍ର',
    h_result: '3. ଫଳାଫଳ', st_matched: 'A ର ମିଳିଥିବା ଧାଡ଼ି', only_in: 'କେବଳ {name} ରେ', st_rows: 'ଫଳାଫଳରେ ଧାଡ଼ି',
    warn_dup_b: '{name} ରେ {n}ଟି କି ଏକାଧିକ ଥର ଅଛି। ଏହା ଏକ-ରୁ-ଅନେକ (one-to-many): A ର ଧାଡ଼ି ପ୍ରତି ମେଳ ପାଇଁ ଥରେ ଆସେ, ତେଣୁ ଫଳାଫଳରେ A ଠାରୁ ଅଧିକ ଧାଡ଼ି ହୋଇପାରେ।',
    note_dup_a: '{name} ରେ {n}ଟି କି ଏକାଧିକ ଥର ଅଛି। ଏହା ଠିକ୍ (ଅନେକ-ରୁ-ଏକ): ସେହି ସବୁ ଧାଡ଼ି ସମାନ ତଥ୍ୟ ପାଏ।',
    warn_blank: '{n}ଟି ଧାଡ଼ିରେ କି ଖାଲି। ଖାଲି କି କେବେ ମିଳେ ନାହିଁ।',
    warn_none: 'କୌଣସି ଧାଡ଼ି ମିଳିଲା ନାହିଁ। ଠିକ୍ କି ସ୍ତମ୍ଭ ବାଛିଛନ୍ତି କି ନାହିଁ ଦେଖନ୍ତୁ।',
    hint_numeric: 'ପରାମର୍ଶ: କିଛି କି ଗୋଟିଏ ଫାଇଲରେ "007" ଓ ଅନ୍ୟଟିରେ "7"। ମିଳାଇବା ପାଇଁ "007 ଓ 7 କୁ ସମାନ ଧରନ୍ତୁ" ରେ ଟିକ୍ ଦିଅନ୍ତୁ।',
    out_cols: 'ଫଳାଫଳର ସ୍ତମ୍ଭ (ଲୁଚାଇବା ବା ଦେଖାଇବା ପାଇଁ ଦବାନ୍ତୁ):', no_rows: 'ଫଳାଫଳରେ କୌଣସି ଧାଡ଼ି ନାହିଁ।',
    page_info: 'ଧାଡ଼ି {from}–{to}, ମୋଟ {total}', legend_nm: 'ଡୋରିଆ ସେଲ: ଅନ୍ୟ ଫାଇଲରେ ମେଳ ଖାଉଥିବା ଧାଡ଼ି ନାହିଁ।', download_csv: 'CSV ଡାଉନଲୋଡ',
    h_unmatched: '4. ଯେଉଁ ଧାଡ଼ି ମିଳିଲା ନାହିଁ', um_note: 'ଫଳାଫଳକୁ ବିଶ୍ୱାସ କରିବା ପୂର୍ବରୁ ଏଗୁଡ଼ିକ ଦେଖନ୍ତୁ। କି ରେ ବନାନ ଭୁଲ କିମ୍ବା ଏକ ଅତିରିକ୍ତ 0 ସବୁଠୁ ସାଧାରଣ କାରଣ।',
    only_in_n: '{name}: {n}', um_none: 'ପ୍ରତି ଧାଡ଼ିର ମେଳ ମିଳିଲା।', download_um: 'ଏହି ଧାଡ଼ି ଡାଉନଲୋଡ', unmatched_file: 'ମିଳିନଥିବା',
    h_lookup: 'ଏହା ହିଁ VLOOKUP / XLOOKUP',
    lookup_1: '<b>ଲେଫ୍ଟ ଜଏନ</b> ସେହି କାମ କରେ ଯାହା Excel କିମ୍ବା Google Sheets ରେ <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> କିମ୍ବା <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> କରେ, କିନ୍ତୁ ସବୁ ସ୍ତମ୍ଭ ଏକାଥରେ।',
    lookup_2: 'ଗୋଟିଏ ପାର୍ଥକ୍ୟ: VLOOKUP ଓ XLOOKUP <b>ପ୍ରଥମ</b> ମେଳରେ ଅଟକେ। ଜଏନ <b>ପ୍ରତ୍ୟେକ</b> ମେଳ ଦିଏ, ସେଥିପାଇଁ ଏକ-ରୁ-ଅନେକ କି ରେ ଧାଡ଼ି ବଢ଼େ। କିଛି ନ ମିଳିଲେ VLOOKUP #N/A ଦେଖାଏ; ଲେଫ୍ଟ ଜଏନ ସେଲ ଖାଲି ରଖେ।',
    h_stack: '1. ଗୋଟିଏ ତଳେ ଗୋଟିଏ ରଖିବା ଫାଇଲ',
    stack_note: 'ସମାନ ପ୍ରକାର ସ୍ତମ୍ଭ ଥିବା ଫାଇଲ ପାଇଁ, ଯେପରି ଜାନୁଆରୀ, ଫେବୃଆରୀ ଓ ମାର୍ଚ୍ଚର ବିକ୍ରି। ସ୍ତମ୍ଭ ନାମ ଦ୍ୱାରା ମିଳାଯାଏ, କ୍ରମ ଭିନ୍ନ ହେଲେ ମଧ୍ୟ।',
    st_empty: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫାଇଲ ନାହିଁ। CSV ଫାଇଲ ଯୋଡ଼ନ୍ତୁ କିମ୍ବା ନମୁନା ଖୋଲନ୍ତୁ।', st_add: 'CSV ଫାଇଲ ଯୋଡ଼ନ୍ତୁ', st_sample: 'ନମୁନା: 3 ମାସର ବିକ୍ରି', st_clear: 'ସବୁ ହଟାନ୍ତୁ',
    st_loose: 'ସ୍ତମ୍ଭ ନାମ ମିଳାଇବା ସମୟରେ ବଡ଼-ଛୋଟ ଅକ୍ଷର ଓ ଅତିରିକ୍ତ ସ୍ପେସ ଉପେକ୍ଷା କରନ୍ତୁ', st_source: '"ଉତ୍ସ ଫାଇଲ" ସ୍ତମ୍ଭ ଯୋଡ଼ନ୍ତୁ', source_col: 'ଉତ୍ସ ଫାଇଲ',
    h_stacked: '2. ଏକାଠି ରଖାଯାଇଥିବା ଫଳାଫଳ', st_total: '{files}ଟି ଫାଇଲରୁ {rows}ଟି ଧାଡ଼ି, {cols}ଟି ସ୍ତମ୍ଭ', st_added: '{n}ଟି ନୂଆ ସ୍ତମ୍ଭ', st_missing: 'ନାହିଁ: {cols}',
    remove_file: 'ଫାଇଲ ହଟାନ୍ତୁ', legend_blank: 'ଡୋରିଆ ସେଲ ଖାଲି (ଅଧିକାଂଶ ସମୟରେ କାରଣ ସେହି ଫାଇଲରେ ସେହି ସ୍ତମ୍ଭ ନଥିଲା)।', stacked_file: 'ଏକାଠି',
    tip1: '"ଛାତ୍ରଛାତ୍ରୀ + ନମ୍ବର" ନମୁନାରୁ ଆରମ୍ଭ କରନ୍ତୁ ଓ ଇନର, ଲେଫ୍ଟ, ରାଇଟ, ଫୁଲ ଆଉଟର ବଦଳାଇ ଦେଖନ୍ତୁ। ଧାଡ଼ି ସଂଖ୍ୟା ଓ ଭେନ ଚିତ୍ର ବଦଳିବା ଦେଖନ୍ତୁ।',
    tip2: 'ଅଫିସ: ଏହି ମାସର ଅର୍ଡରକୁ ଗ୍ରାହକ ତାଲିକା ସହ ଯୋଡ଼ନ୍ତୁ ଯାହାଫଳରେ ପ୍ରତି ଗ୍ରାହକର ସହର ଓ ଫୋନ ଆସିଯିବ, ତା\'ପରେ ଡେଲିଭରି ପାଇଁ ଗୋଟିଏ ଫାଇଲ ଡାଉନଲୋଡ କରନ୍ତୁ।',
    tip3: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟ: ଦୁଇଟି ନମୁନା ଫାଇଲ ପ୍ରିଣ୍ଟ କରନ୍ତୁ। ଛାତ୍ରଛାତ୍ରୀ କାଗଜରେ ହାତରେ ଯୋଡ଼ିବେ, ତା\'ପରେ ଆପରେ ଯାଞ୍ଚ କରିବେ। କେବଳ 7 ଜଣ ମିଳିଲେ, ତେବେ ଇନର ଜଏନରେ 9ଟି ଧାଡ଼ି କାହିଁକି?',
    tip4: 'କି ଦୁଇଟି ଫାଇଲରେ ସମାନ ଭାବେ ଲେଖାଯାଇଥିବା ଦରକାର। ପ୍ରଥମେ ତାହାକୁ ସଫା କରନ୍ତୁ (ସ୍ପେସ, ବଡ଼-ଛୋଟ ଅକ୍ଷର, "007" ବନାମ "7") ଏଠାର ବିକଳ୍ପ କିମ୍ବା ଡାଟା ସଫା ଲ୍ୟାବ ଆପ ଦ୍ୱାରା।',
    tip5: 'ଗୋଟିଏ ତଳେ ଗୋଟିଏ: 12 ମାସର ବିକ୍ରି ଫାଇଲ ମିଶାଇ ବର୍ଷର ଗୋଟିଏ ଫାଇଲ ତିଆରି କରନ୍ତୁ, "ଉତ୍ସ ଫାଇଲ" ସ୍ତମ୍ଭ ସହ ଯାହା କହେ ପ୍ରତି ଧାଡ଼ି କେଉଁଠୁ ଆସିଲା।',
    words_title: 'ଜାଣିବା ଦରକାରୀ ଶବ୍ଦ: ଭିତରେ କ\'ଣ ହେଉଛି',
    w_key: '<b>କି (Key)</b>: ଧାଡ଼ି ମିଳାଉଥିବା ସ୍ତମ୍ଭ, ଯେପରି ରୋଲ ନମ୍ବର କିମ୍ବା ଗ୍ରାହକ ID। ଭଲ କି ଦୁଇଟି ଫାଇଲରେ ସମାନ ଭାବେ ଲେଖାଯାଏ ଓ ଅତି କମରେ ଗୋଟିଏ ଫାଇଲରେ ଥରେ ହିଁ ଥାଏ।',
    w_inner: '<b>ଇନର ଜଏନ</b>: କେବଳ ଦୁଇଟି ଫାଇଲରେ ମିଳୁଥିବା ଧାଡ଼ି ରଖେ (ଭେନ ଚିତ୍ରର ମଝି ଅଂଶ)।',
    w_outer: '<b>ଲେଫ୍ଟ, ରାଇଟ ଓ ଫୁଲ ଆଉଟର ଜଏନ</b>: ମିଳିନଥିବା ଧାଡ଼ି ମଧ୍ୟ ରଖେ, A ରୁ, B ରୁ, କିମ୍ବା ଦୁଇଟିରୁ। ଯେଉଁ ପାର୍ଶ୍ୱ ନାହିଁ ତାହା ଖାଲି ରହେ।',
    w_many: '<b>ଏକ-ରୁ-ଅନେକ</b>: A ର ଗୋଟିଏ କି B ର ଅନେକ ଧାଡ଼ି ସହ ମିଳେ (ଜଣେ ଛାତ୍ର, ଅନେକ ବିଷୟ)। ଫଳାଫଳରେ ପ୍ରତି ମେଳ ପାଇଁ ଗୋଟିଏ ଧାଡ଼ି ହୁଏ।',
    w_union: '<b>ଗୋଟିଏ ତଳେ ଗୋଟିଏ (append / union)</b>: ଫାଇଲଗୁଡ଼ିକୁ ଗୋଟିଏ ତଳେ ଗୋଟିଏ ରଖିବା। ଏଥିରେ ଧାଡ଼ି ବଢ଼େ; ଜଏନରେ ସ୍ତମ୍ଭ ବଢ଼େ।'
  },
  ta: {
    app_title: 'கோப்புகளை இணை & சேர்',
    intro: 'இரண்டு CSV கோப்புகளை ஒத்துப்போகும் ஒரு நெடுவரிசை மூலம் இணையுங்கள் (VLOOKUP போல), அல்லது பல மாதக் கோப்புகளை ஒன்றின் கீழ் ஒன்றாக அடுக்குங்கள். எது பொருந்தியது, எது பொருந்தவில்லை என்று பார்த்து, முடிவைப் பதிவிறக்குங்கள்.',
    mode_join: 'இரண்டு கோப்புகளை இணை', mode_stack: 'பல கோப்புகளை அடுக்கு',
    h_files: '1. உங்கள் இரண்டு கோப்புகள்', try_sample: 'மாதிரி முயலுங்கள்:', sample_students: 'மாணவர்கள் + மதிப்பெண்கள்', sample_orders: 'ஆர்டர்கள் + வாடிக்கையாளர்கள்',
    file_a: 'கோப்பு A (இடது)', file_b: 'கோப்பு B (வலது)', open_csv: 'CSV திற', paste_data: 'தரவை ஒட்டு',
    paste_ph: 'Excel அல்லது Google Sheets வரிசைகள், அல்லது CSV உரையை ஒட்டவும்', use_paste: 'ஒட்டிய தரவைப் பயன்படுத்து', pasted_a: 'ஒட்டியது-A', pasted_b: 'ஒட்டியது-B',
    drop_hint: 'CSV கோப்புகளை இங்கே இழுத்து விடலாம். Excel-இல்: File → Save as → CSV. உங்கள் கோப்புகள் இந்தச் சாதனத்திலேயே இருக்கும்.',
    file_info: '{rows} வரிசைகள், {cols} நெடுவரிசைகள்',
    err_empty: 'வரிசைகள் இல்லை. முதல் வரிசையில் நெடுவரிசைப் பெயர்கள் இருக்க வேண்டும்.', err_file: 'இந்தக் கோப்பைப் படிக்க முடியவில்லை.',
    err_excel: 'முதலில் தாளை CSV ஆகச் சேமியுங்கள் (Excel: File → Save as → CSV).', big_note: 'இந்தக் கோப்பு பெரியது, அதனால் அடுத்த முறைக்குச் சேமிக்கப்படவில்லை.',
    h_match: '2. வரிசைகளை எப்படிப் பொருத்துவது', key_a: 'A-இன் சாவி நெடுவரிசை', key_b: 'B-இன் சாவி நெடுவரிசை',
    opt_trim: 'கூடுதல் இடைவெளியைக் கணக்கில் கொள்ளாதே', opt_icase: 'பெரிய-சிறிய எழுத்தைக் கணக்கில் கொள்ளாதே', opt_num: '"007", "7" இரண்டையும் ஒன்றாகக் கொள்', swap: 'A, B இடம் மாற்று',
    join_type: 'இணைப்பு வகை', type_inner: 'இன்னர்', type_left: 'லெஃப்ட்', type_right: 'ரைட்', type_full: 'ஃபுல் அவுட்டர்',
    help_inner: 'இன்னர்: சாவி இரண்டு கோப்புகளிலும் உள்ள வரிசைகள் மட்டும்.',
    help_left: 'லெஃப்ட்: A-இன் ஒவ்வொரு வரிசையும்; சாவி பொருந்தினால் B-இன் விவரம், இல்லாவிட்டால் காலி.',
    help_right: 'ரைட்: B-இன் ஒவ்வொரு வரிசையும்; சாவி பொருந்தினால் A-இன் விவரம்.',
    help_full: 'ஃபுல் அவுட்டர்: இரண்டு கோப்புகளின் ஒவ்வொரு வரிசையும், முடிந்த இடங்களில் பொருத்தி.',
    venn_label: 'இணைப்பு வகையின் வென் படம்',
    h_result: '3. முடிவு', st_matched: 'பொருந்திய A வரிசைகள்', only_in: '{name}-இல் மட்டும்', st_rows: 'முடிவில் வரிசைகள்',
    warn_dup_b: '{name}-இல் {n} சாவிகள் ஒருமுறைக்கு மேல் வருகின்றன. இது ஒன்று-பல (one-to-many): A-இன் ஒரு வரிசை ஒவ்வொரு பொருத்தத்துக்கும் ஒருமுறை வரும், அதனால் முடிவில் A-ஐ விட அதிக வரிசைகள் இருக்கலாம்.',
    note_dup_a: '{name}-இல் {n} சாவிகள் ஒருமுறைக்கு மேல் வருகின்றன. இது சரிதான் (பல-ஒன்று): அந்த வரிசைகள் எல்லாம் அதே விவரத்தைப் பெறும்.',
    warn_blank: '{n} வரிசைகளில் சாவி காலியாக உள்ளது. காலிச் சாவி ஒருபோதும் பொருந்தாது.',
    warn_none: 'எந்த வரிசையும் பொருந்தவில்லை. சரியான சாவி நெடுவரிசைகளைத் தேர்ந்தீர்களா என்று பாருங்கள்.',
    hint_numeric: 'குறிப்பு: சில சாவிகள் ஒரு கோப்பில் "007", மற்றதில் "7" என உள்ளன. பொருத்த "007, 7 இரண்டையும் ஒன்றாகக் கொள்" என்பதைத் தேர்வு செய்யுங்கள்.',
    out_cols: 'முடிவின் நெடுவரிசைகள் (மறைக்க அல்லது காட்ட அழுத்துங்கள்):', no_rows: 'முடிவில் வரிசைகள் இல்லை.',
    page_info: 'வரிசைகள் {from}–{to}, மொத்தம் {total}', legend_nm: 'கோடிட்ட கலங்கள்: மற்ற கோப்பில் பொருந்தும் வரிசை இல்லை.', download_csv: 'CSV பதிவிறக்கு',
    h_unmatched: '4. பொருந்தாத வரிசைகள்', um_note: 'முடிவை நம்பும் முன் இவற்றைப் பாருங்கள். சாவியில் எழுத்துப் பிழை அல்லது ஒரு கூடுதல் 0 தான் பொதுவான காரணம்.',
    only_in_n: '{name}: {n}', um_none: 'ஒவ்வொரு வரிசைக்கும் பொருத்தம் கிடைத்தது.', download_um: 'இந்த வரிசைகளைப் பதிவிறக்கு', unmatched_file: 'பொருந்தாதவை',
    h_lookup: 'இதுதான் VLOOKUP / XLOOKUP',
    lookup_1: '<b>லெஃப்ட் ஜாயின்</b> Excel அல்லது Google Sheets-இல் <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> அல்லது <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> செய்வதையே செய்கிறது, ஆனால் எல்லா நெடுவரிசைகளுக்கும் ஒரே நேரத்தில்.',
    lookup_2: 'ஒரு வேறுபாடு: VLOOKUP, XLOOKUP <b>முதல்</b> பொருத்தத்தில் நின்றுவிடும். ஜாயின் <b>ஒவ்வொரு</b> பொருத்தத்தையும் தரும்; அதனால்தான் ஒன்று-பல சாவிகள் வரிசைகளைக் கூட்டுகின்றன. எதுவும் பொருந்தாவிட்டால் VLOOKUP #N/A காட்டும்; லெஃப்ட் ஜாயின் கலங்களைக் காலியாக விடும்.',
    h_stack: '1. அடுக்க வேண்டிய கோப்புகள் (ஒன்றின் கீழ் ஒன்று)',
    stack_note: 'ஒரே வகை நெடுவரிசைகள் உள்ள கோப்புகளுக்கு, உதாரணமாக ஜனவரி, பிப்ரவரி, மார்ச் விற்பனை. வரிசை மாறியிருந்தாலும் நெடுவரிசைகள் பெயரால் பொருத்தப்படும்.',
    st_empty: 'இன்னும் கோப்புகள் இல்லை. CSV கோப்புகளைச் சேருங்கள் அல்லது மாதிரியைத் திறங்கள்.', st_add: 'CSV கோப்புகளைச் சேர்', st_sample: 'மாதிரி: 3 மாத விற்பனை', st_clear: 'எல்லாம் நீக்கு',
    st_loose: 'நெடுவரிசைப் பெயர்களைப் பொருத்தும்போது பெரிய-சிறிய எழுத்தும் கூடுதல் இடைவெளியும் கணக்கில் வேண்டாம்', st_source: '"மூலக் கோப்பு" நெடுவரிசையைச் சேர்', source_col: 'மூலக் கோப்பு',
    h_stacked: '2. அடுக்கிய முடிவு', st_total: '{files} கோப்புகளிலிருந்து {rows} வரிசைகள், {cols} நெடுவரிசைகள்', st_added: '{n} புதிய நெடுவரிசைகள்', st_missing: 'இல்லாதவை: {cols}',
    remove_file: 'கோப்பை நீக்கு', legend_blank: 'கோடிட்ட கலங்கள் காலியானவை (பெரும்பாலும் அந்தக் கோப்பில் அந்த நெடுவரிசை இல்லாததால்).', stacked_file: 'அடுக்கியது',
    tip1: '"மாணவர்கள் + மதிப்பெண்கள்" மாதிரியுடன் தொடங்கி இன்னர், லெஃப்ட், ரைட், ஃபுல் அவுட்டர் என மாற்றிப் பாருங்கள். வரிசை எண்ணிக்கையும் வென் படமும் மாறுவதைப் பாருங்கள்.',
    tip2: 'அலுவலகம்: இந்த மாத ஆர்டர்களை வாடிக்கையாளர் பட்டியலுடன் இணைத்து ஒவ்வொருவரின் நகரம், தொலைபேசியைச் சேர்த்து, டெலிவரிக்கு ஒரு கோப்பைப் பதிவிறக்குங்கள்.',
    tip3: 'வகுப்புச் செயல்பாடு: இரண்டு மாதிரிக் கோப்புகளையும் அச்சிடுங்கள். மாணவர்கள் தாளில் கையால் இணைத்து, பிறகு செயலியில் சரிபார்க்கட்டும். 7 மாணவர்கள் மட்டுமே பொருந்தினர்; இன்னர் ஜாயினில் ஏன் 9 வரிசைகள்?',
    tip4: 'இரண்டு கோப்புகளிலும் சாவி ஒரே மாதிரி எழுதப்பட வேண்டும். முதலில் அதைச் சுத்தம் செய்யுங்கள் (இடைவெளி, பெரிய-சிறிய எழுத்து, "007"-ஆ "7"-ஆ) இங்குள்ள தேர்வுகள் அல்லது தரவு சுத்தம் ஆய்வகம் செயலி மூலம்.',
    tip5: 'அடுக்கு முறை: 12 மாத விற்பனைக் கோப்புகளைச் சேர்த்து ஓர் ஆண்டுக் கோப்பாக்குங்கள்; ஒவ்வொரு வரிசையும் எங்கிருந்து வந்தது என்று காட்டும் "மூலக் கோப்பு" நெடுவரிசையுடன்.',
    words_title: 'தெரிந்துகொள்ள வேண்டிய சொற்கள்: உள்ளே என்ன நடக்கிறது',
    w_key: '<b>சாவி (Key)</b>: வரிசைகளைப் பொருத்தும் நெடுவரிசை, பதிவு எண் அல்லது வாடிக்கையாளர் ID போல. நல்ல சாவி இரண்டு கோப்புகளிலும் ஒரே மாதிரி எழுதப்பட்டு, குறைந்தது ஒரு கோப்பில் ஒருமுறை மட்டுமே வரும்.',
    w_inner: '<b>இன்னர் ஜாயின்</b>: இரண்டு கோப்புகளிலும் பொருந்தும் வரிசைகளை மட்டும் வைக்கும் (வென் படத்தின் நடுப்பகுதி).',
    w_outer: '<b>லெஃப்ட், ரைட், ஃபுல் அவுட்டர் ஜாயின்</b>: பொருந்தாத வரிசைகளையும் வைக்கும், A-இலிருந்து, B-இலிருந்து, அல்லது இரண்டிலிருந்தும். இல்லாத பக்கம் காலியாக இருக்கும்.',
    w_many: '<b>ஒன்று-பல</b>: A-இன் ஒரு சாவி B-இன் பல வரிசைகளுடன் பொருந்தும் (ஒரு மாணவர், பல பாடங்கள்). முடிவில் ஒவ்வொரு பொருத்தத்துக்கும் ஒரு வரிசை.',
    w_union: '<b>அடுக்குதல் (append / union)</b>: கோப்புகளை ஒன்றின் கீழ் ஒன்றாக வைப்பது. இது வரிசைகளைக் கூட்டும்; ஜாயின் நெடுவரிசைகளைக் கூட்டும்.'
  },
  te: {
    app_title: 'ఫైళ్లను జోడించు & కలుపు',
    intro: 'రెండు CSV ఫైళ్లను సరిపోలే ఒక నిలువు వరుసతో జోడించండి (VLOOKUP లాగా), లేదా చాలా నెలల ఫైళ్లను ఒకదాని కింద ఒకటి పేర్చండి. ఏది సరిపోయిందో, ఏది సరిపోలేదో చూసి ఫలితాన్ని డౌన్‌లోడ్ చేయండి.',
    mode_join: 'రెండు ఫైళ్లను జోడించు', mode_stack: 'చాలా ఫైళ్లను పేర్చు',
    h_files: '1. మీ రెండు ఫైళ్లు', try_sample: 'నమూనా ప్రయత్నించండి:', sample_students: 'విద్యార్థులు + మార్కులు', sample_orders: 'ఆర్డర్లు + కస్టమర్లు',
    file_a: 'ఫైల్ A (ఎడమ)', file_b: 'ఫైల్ B (కుడి)', open_csv: 'CSV తెరవండి', paste_data: 'డేటా పేస్ట్ చేయండి',
    paste_ph: 'Excel లేదా Google Sheets వరుసలు, లేదా CSV పాఠ్యం పేస్ట్ చేయండి', use_paste: 'పేస్ట్ చేసిన డేటా వాడండి', pasted_a: 'పేస్ట్-A', pasted_b: 'పేస్ట్-B',
    drop_hint: 'CSV ఫైళ్లను ఇక్కడికి లాగి వదలవచ్చు. Excel లో: File → Save as → CSV. మీ ఫైళ్లు ఈ పరికరంలోనే ఉంటాయి.',
    file_info: '{rows} వరుసలు, {cols} నిలువు వరుసలు',
    err_empty: 'వరుసలు దొరకలేదు. మొదటి వరుసలో నిలువు వరుసల పేర్లు ఉండాలి.', err_file: 'ఈ ఫైల్‌ను చదవలేకపోయాం.',
    err_excel: 'ముందుగా షీట్‌ను CSV గా సేవ్ చేయండి (Excel: File → Save as → CSV).', big_note: 'ఈ ఫైల్ పెద్దది, అందుకే తర్వాతి సారి కోసం సేవ్ కాలేదు.',
    h_match: '2. వరుసలను ఎలా సరిపోల్చాలి', key_a: 'A లో కీ నిలువు వరుస', key_b: 'B లో కీ నిలువు వరుస',
    opt_trim: 'అదనపు ఖాళీలను పట్టించుకోవద్దు', opt_icase: 'పెద్ద-చిన్న అక్షరాలను పట్టించుకోవద్దు', opt_num: '"007", "7" ఒకటే అనుకో', swap: 'A, B మార్చు',
    join_type: 'జోడింపు రకం', type_inner: 'ఇన్నర్', type_left: 'లెఫ్ట్', type_right: 'రైట్', type_full: 'ఫుల్ ఔటర్',
    help_inner: 'ఇన్నర్: కీ రెండు ఫైళ్లలోనూ ఉన్న వరుసలు మాత్రమే.',
    help_left: 'లెఫ్ట్: A లోని ప్రతి వరుస; కీ సరిపోతే B వివరాలు, లేకపోతే ఖాళీ.',
    help_right: 'రైట్: B లోని ప్రతి వరుస; కీ సరిపోతే A వివరాలు.',
    help_full: 'ఫుల్ ఔటర్: రెండు ఫైళ్లలోని ప్రతి వరుస, వీలైనచోట సరిపోల్చి.',
    venn_label: 'జోడింపు రకం వెన్ చిత్రం',
    h_result: '3. ఫలితం', st_matched: 'సరిపోయిన A వరుసలు', only_in: '{name} లో మాత్రమే', st_rows: 'ఫలితంలో వరుసలు',
    warn_dup_b: '{name} లో {n} కీలు ఒకటి కంటే ఎక్కువసార్లు ఉన్నాయి. ఇది ఒకటి-నుండి-అనేకం (one-to-many): A లోని వరుస ప్రతి జోడీకి ఒకసారి వస్తుంది, అందుకే ఫలితంలో A కంటే ఎక్కువ వరుసలు ఉండవచ్చు.',
    note_dup_a: '{name} లో {n} కీలు ఒకటి కంటే ఎక్కువసార్లు ఉన్నాయి. ఇది సరే (అనేకం-నుండి-ఒకటి): ఆ వరుసలన్నీ అవే వివరాలు పొందుతాయి.',
    warn_blank: '{n} వరుసల్లో కీ ఖాళీగా ఉంది. ఖాళీ కీ ఎప్పుడూ సరిపోదు.',
    warn_none: 'ఏ వరుసా సరిపోలేదు. సరైన కీ నిలువు వరుసలు ఎంచుకున్నారో చూడండి.',
    hint_numeric: 'సూచన: కొన్ని కీలు ఒక ఫైల్‌లో "007", మరోదానిలో "7" లా ఉన్నాయి. సరిపోల్చడానికి "007, 7 ఒకటే అనుకో" టిక్ చేయండి.',
    out_cols: 'ఫలితంలోని నిలువు వరుసలు (దాచడానికి లేదా చూపడానికి నొక్కండి):', no_rows: 'ఫలితంలో వరుసలు లేవు.',
    page_info: 'వరుసలు {from}–{to}, మొత్తం {total}', legend_nm: 'చారల గడులు: మరో ఫైల్‌లో సరిపోలే వరుస లేదు.', download_csv: 'CSV డౌన్‌లోడ్',
    h_unmatched: '4. సరిపోని వరుసలు', um_note: 'ఫలితాన్ని నమ్మే ముందు వీటిని చూడండి. కీలో అక్షర దోషం లేదా ఒక అదనపు 0 సాధారణ కారణం.',
    only_in_n: '{name}: {n}', um_none: 'ప్రతి వరుసకూ జోడీ దొరికింది.', download_um: 'ఈ వరుసలు డౌన్‌లోడ్', unmatched_file: 'సరిపోనివి',
    h_lookup: 'ఇదే VLOOKUP / XLOOKUP',
    lookup_1: '<b>లెఫ్ట్ జాయిన్</b> Excel లేదా Google Sheets లో <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> లేదా <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> చేసే పనినే చేస్తుంది, కానీ అన్ని నిలువు వరుసలకూ ఒకేసారి.',
    lookup_2: 'ఒక తేడా: VLOOKUP, XLOOKUP <b>మొదటి</b> జోడీ దగ్గర ఆగిపోతాయి. జాయిన్ <b>ప్రతి</b> జోడీని ఇస్తుంది, అందుకే ఒకటి-నుండి-అనేకం కీలతో వరుసలు పెరుగుతాయి. ఏమీ సరిపోకపోతే VLOOKUP #N/A చూపుతుంది; లెఫ్ట్ జాయిన్ గడులను ఖాళీగా వదులుతుంది.',
    h_stack: '1. పేర్చాల్సిన ఫైళ్లు (ఒకదాని కింద ఒకటి)',
    stack_note: 'ఒకే రకం నిలువు వరుసలు ఉన్న ఫైళ్ల కోసం, ఉదాహరణకు జనవరి, ఫిబ్రవరి, మార్చి అమ్మకాలు. క్రమం వేరైనా నిలువు వరుసలను పేరుతో సరిపోలుస్తాం.',
    st_empty: 'ఇంకా ఫైళ్లు లేవు. CSV ఫైళ్లు జోడించండి లేదా నమూనా తెరవండి.', st_add: 'CSV ఫైళ్లు జోడించు', st_sample: 'నమూనా: 3 నెలల అమ్మకాలు', st_clear: 'అన్నీ తొలగించు',
    st_loose: 'నిలువు వరుస పేర్లు సరిపోల్చేటప్పుడు పెద్ద-చిన్న అక్షరాలు, అదనపు ఖాళీలు పట్టించుకోవద్దు', st_source: '"మూల ఫైల్" నిలువు వరుస జోడించు', source_col: 'మూల ఫైల్',
    h_stacked: '2. పేర్చిన ఫలితం', st_total: '{files} ఫైళ్ల నుండి {rows} వరుసలు, {cols} నిలువు వరుసలు', st_added: '{n} కొత్త నిలువు వరుసలు', st_missing: 'లేనివి: {cols}',
    remove_file: 'ఫైల్ తొలగించు', legend_blank: 'చారల గడులు ఖాళీ (తరచూ ఆ ఫైల్‌లో ఆ నిలువు వరుస లేకపోవడం వల్ల).', stacked_file: 'పేర్చినది',
    tip1: '"విద్యార్థులు + మార్కులు" నమూనాతో మొదలుపెట్టి ఇన్నర్, లెఫ్ట్, రైట్, ఫుల్ ఔటర్ మార్చి చూడండి. వరుసల సంఖ్య, వెన్ చిత్రం మారడం గమనించండి.',
    tip2: 'ఆఫీసు: ఈ నెల ఆర్డర్లను కస్టమర్ జాబితాతో జోడించి ప్రతి కస్టమర్ నగరం, ఫోన్ చేర్చండి, తర్వాత డెలివరీ కోసం ఒక ఫైల్ డౌన్‌లోడ్ చేయండి.',
    tip3: 'తరగతి కార్యకలాపం: రెండు నమూనా ఫైళ్లనూ ప్రింట్ చేయండి. విద్యార్థులు కాగితంపై చేత్తో జోడించి, తర్వాత యాప్‌తో సరిచూడాలి. 7 మంది విద్యార్థులే సరిపోయారు; ఇన్నర్ జాయిన్‌లో 9 వరుసలు ఎందుకు?',
    tip4: 'రెండు ఫైళ్లలోనూ కీ ఒకేలా రాసి ఉండాలి. ముందుగా దాన్ని శుభ్రం చేయండి (ఖాళీలు, పెద్ద-చిన్న అక్షరాలు, "007" vs "7") ఇక్కడి ఎంపికలతో లేదా డేటా శుభ్రత ల్యాబ్ యాప్‌తో.',
    tip5: 'పేర్చే విధానం: 12 నెలల అమ్మకాల ఫైళ్లను కలిపి ఒక ఏడాది ఫైల్ చేయండి; ప్రతి వరుస ఎక్కడి నుండి వచ్చిందో చూపే "మూల ఫైల్" నిలువు వరుసతో.',
    words_title: 'తెలుసుకోవాల్సిన పదాలు: లోపల ఏం జరుగుతోంది',
    w_key: '<b>కీ (Key)</b>: వరుసలను సరిపోల్చే నిలువు వరుస, రోల్ నంబర్ లేదా కస్టమర్ ID లాంటిది. మంచి కీ రెండు ఫైళ్లలోనూ ఒకేలా రాసి ఉంటుంది, కనీసం ఒక ఫైల్‌లో ఒక్కసారే ఉంటుంది.',
    w_inner: '<b>ఇన్నర్ జాయిన్</b>: రెండు ఫైళ్లలోనూ సరిపోయే వరుసలను మాత్రమే ఉంచుతుంది (వెన్ చిత్రం మధ్యభాగం).',
    w_outer: '<b>లెఫ్ట్, రైట్, ఫుల్ ఔటర్ జాయిన్</b>: సరిపోని వరుసలనూ ఉంచుతాయి, A నుండి, B నుండి, లేదా రెండింటి నుండి. లేని వైపు ఖాళీగా ఉంటుంది.',
    w_many: '<b>ఒకటి-నుండి-అనేకం</b>: A లోని ఒక కీ B లోని చాలా వరుసలతో సరిపోతుంది (ఒక విద్యార్థి, చాలా విషయాలు). ఫలితంలో ప్రతి జోడీకి ఒక వరుస.',
    w_union: '<b>పేర్చడం (append / union)</b>: ఫైళ్లను ఒకదాని కింద ఒకటి ఉంచడం. ఇది వరుసలను పెంచుతుంది; జాయిన్ నిలువు వరుసలను పెంచుతుంది.'
  },
  kn: {
    app_title: 'ಫೈಲ್‌ಗಳನ್ನು ಜೋಡಿಸಿ & ಸೇರಿಸಿ',
    intro: 'ಎರಡು CSV ಫೈಲ್‌ಗಳನ್ನು ಹೊಂದುವ ಒಂದು ಕಾಲಂ ಮೂಲಕ ಜೋಡಿಸಿ (VLOOKUP ನಂತೆ), ಅಥವಾ ಹಲವು ತಿಂಗಳ ಫೈಲ್‌ಗಳನ್ನು ಒಂದರ ಕೆಳಗೆ ಒಂದು ಇಡಿ. ಯಾವುದು ಹೊಂದಿತು, ಯಾವುದು ಹೊಂದಲಿಲ್ಲ ಎಂದು ನೋಡಿ, ಫಲಿತಾಂಶ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    mode_join: 'ಎರಡು ಫೈಲ್ ಜೋಡಿಸಿ', mode_stack: 'ಹಲವು ಫೈಲ್ ಒಂದರ ಕೆಳಗೊಂದು',
    h_files: '1. ನಿಮ್ಮ ಎರಡು ಫೈಲ್‌ಗಳು', try_sample: 'ಮಾದರಿ ಪ್ರಯತ್ನಿಸಿ:', sample_students: 'ವಿದ್ಯಾರ್ಥಿಗಳು + ಅಂಕಗಳು', sample_orders: 'ಆರ್ಡರ್‌ಗಳು + ಗ್ರಾಹಕರು',
    file_a: 'ಫೈಲ್ A (ಎಡ)', file_b: 'ಫೈಲ್ B (ಬಲ)', open_csv: 'CSV ತೆರೆಯಿರಿ', paste_data: 'ಡೇಟಾ ಪೇಸ್ಟ್ ಮಾಡಿ',
    paste_ph: 'Excel ಅಥವಾ Google Sheets ಸಾಲುಗಳು, ಅಥವಾ CSV ಪಠ್ಯ ಪೇಸ್ಟ್ ಮಾಡಿ', use_paste: 'ಪೇಸ್ಟ್ ಮಾಡಿದ ಡೇಟಾ ಬಳಸಿ', pasted_a: 'ಪೇಸ್ಟ್-A', pasted_b: 'ಪೇಸ್ಟ್-B',
    drop_hint: 'CSV ಫೈಲ್‌ಗಳನ್ನು ಇಲ್ಲಿ ಎಳೆದು ಬಿಡಬಹುದು. Excel ನಲ್ಲಿ: File → Save as → CSV. ನಿಮ್ಮ ಫೈಲ್‌ಗಳು ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತವೆ.',
    file_info: '{rows} ಸಾಲುಗಳು, {cols} ಕಾಲಂಗಳು',
    err_empty: 'ಯಾವ ಸಾಲೂ ಸಿಗಲಿಲ್ಲ. ಮೊದಲ ಸಾಲಿನಲ್ಲಿ ಕಾಲಂ ಹೆಸರುಗಳು ಇರಬೇಕು.', err_file: 'ಈ ಫೈಲ್ ಓದಲಾಗಲಿಲ್ಲ.',
    err_excel: 'ಮೊದಲು ಶೀಟ್ ಅನ್ನು CSV ಆಗಿ ಉಳಿಸಿ (Excel: File → Save as → CSV).', big_note: 'ಈ ಫೈಲ್ ದೊಡ್ಡದು, ಆದ್ದರಿಂದ ಮುಂದಿನ ಬಾರಿಗೆ ಉಳಿಸಿಲ್ಲ.',
    h_match: '2. ಸಾಲುಗಳನ್ನು ಹೇಗೆ ಹೊಂದಿಸುವುದು', key_a: 'A ಯ ಕೀ ಕಾಲಂ', key_b: 'B ಯ ಕೀ ಕಾಲಂ',
    opt_trim: 'ಹೆಚ್ಚುವರಿ ಸ್ಪೇಸ್ ಲೆಕ್ಕಿಸಬೇಡಿ', opt_icase: 'ದೊಡ್ಡ-ಸಣ್ಣ ಅಕ್ಷರ ಲೆಕ್ಕಿಸಬೇಡಿ', opt_num: '"007" ಮತ್ತು "7" ಒಂದೇ ಎಂದು ಪರಿಗಣಿಸಿ', swap: 'A ಮತ್ತು B ಅದಲುಬದಲು',
    join_type: 'ಜೋಡಣೆಯ ಬಗೆ', type_inner: 'ಇನ್ನರ್', type_left: 'ಲೆಫ್ಟ್', type_right: 'ರೈಟ್', type_full: 'ಫುಲ್ ಔಟರ್',
    help_inner: 'ಇನ್ನರ್: ಕೀ ಎರಡೂ ಫೈಲ್‌ಗಳಲ್ಲಿ ಇರುವ ಸಾಲುಗಳು ಮಾತ್ರ.',
    help_left: 'ಲೆಫ್ಟ್: A ಯ ಪ್ರತಿ ಸಾಲು; ಕೀ ಹೊಂದಿದರೆ B ಯ ವಿವರ, ಇಲ್ಲದಿದ್ದರೆ ಖಾಲಿ.',
    help_right: 'ರೈಟ್: B ಯ ಪ್ರತಿ ಸಾಲು; ಕೀ ಹೊಂದಿದರೆ A ಯ ವಿವರ.',
    help_full: 'ಫುಲ್ ಔಟರ್: ಎರಡೂ ಫೈಲ್‌ಗಳ ಪ್ರತಿ ಸಾಲು, ಸಾಧ್ಯವಿರುವಲ್ಲಿ ಹೊಂದಿಸಿ.',
    venn_label: 'ಜೋಡಣೆಯ ಬಗೆಯ ವೆನ್ ಚಿತ್ರ',
    h_result: '3. ಫಲಿತಾಂಶ', st_matched: 'ಹೊಂದಿದ A ಸಾಲುಗಳು', only_in: '{name} ನಲ್ಲಿ ಮಾತ್ರ', st_rows: 'ಫಲಿತಾಂಶದ ಸಾಲುಗಳು',
    warn_dup_b: '{name} ನಲ್ಲಿ {n} ಕೀಗಳು ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ಬಾರಿ ಇವೆ. ಇದು ಒಂದು-ಹಲವು (one-to-many): A ಯ ಸಾಲು ಪ್ರತಿ ಹೊಂದಾಣಿಕೆಗೆ ಒಮ್ಮೆ ಬರುತ್ತದೆ, ಆದ್ದರಿಂದ ಫಲಿತಾಂಶದಲ್ಲಿ A ಗಿಂತ ಹೆಚ್ಚು ಸಾಲುಗಳು ಇರಬಹುದು.',
    note_dup_a: '{name} ನಲ್ಲಿ {n} ಕೀಗಳು ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ಬಾರಿ ಇವೆ. ಇದು ಸರಿ (ಹಲವು-ಒಂದು): ಆ ಎಲ್ಲ ಸಾಲುಗಳಿಗೆ ಅದೇ ವಿವರ ಸಿಗುತ್ತದೆ.',
    warn_blank: '{n} ಸಾಲುಗಳಲ್ಲಿ ಕೀ ಖಾಲಿ ಇದೆ. ಖಾಲಿ ಕೀ ಎಂದೂ ಹೊಂದುವುದಿಲ್ಲ.',
    warn_none: 'ಯಾವ ಸಾಲೂ ಹೊಂದಲಿಲ್ಲ. ಸರಿಯಾದ ಕೀ ಕಾಲಂಗಳನ್ನು ಆರಿಸಿದ್ದೀರಾ ನೋಡಿ.',
    hint_numeric: 'ಸಲಹೆ: ಕೆಲವು ಕೀಗಳು ಒಂದು ಫೈಲ್‌ನಲ್ಲಿ "007", ಇನ್ನೊಂದರಲ್ಲಿ "7" ಇವೆ. ಹೊಂದಿಸಲು "007 ಮತ್ತು 7 ಒಂದೇ ಎಂದು ಪರಿಗಣಿಸಿ" ಟಿಕ್ ಮಾಡಿ.',
    out_cols: 'ಫಲಿತಾಂಶದ ಕಾಲಂಗಳು (ಮರೆಮಾಡಲು ಅಥವಾ ತೋರಿಸಲು ಒತ್ತಿ):', no_rows: 'ಫಲಿತಾಂಶದಲ್ಲಿ ಸಾಲುಗಳಿಲ್ಲ.',
    page_info: 'ಸಾಲುಗಳು {from}–{to}, ಒಟ್ಟು {total}', legend_nm: 'ಪಟ್ಟೆ ಕೋಶಗಳು: ಇನ್ನೊಂದು ಫೈಲ್‌ನಲ್ಲಿ ಹೊಂದುವ ಸಾಲು ಇಲ್ಲ.', download_csv: 'CSV ಡೌನ್‌ಲೋಡ್',
    h_unmatched: '4. ಹೊಂದದ ಸಾಲುಗಳು', um_note: 'ಫಲಿತಾಂಶ ನಂಬುವ ಮೊದಲು ಇವನ್ನು ನೋಡಿ. ಕೀಯಲ್ಲಿ ಕಾಗುಣಿತ ತಪ್ಪು ಅಥವಾ ಒಂದು ಹೆಚ್ಚುವರಿ 0 ಸಾಮಾನ್ಯ ಕಾರಣ.',
    only_in_n: '{name}: {n}', um_none: 'ಪ್ರತಿ ಸಾಲಿಗೂ ಹೊಂದಾಣಿಕೆ ಸಿಕ್ಕಿತು.', download_um: 'ಈ ಸಾಲುಗಳನ್ನು ಡೌನ್‌ಲೋಡ್', unmatched_file: 'ಹೊಂದದವು',
    h_lookup: 'ಇದೇ VLOOKUP / XLOOKUP',
    lookup_1: '<b>ಲೆಫ್ಟ್ ಜಾಯಿನ್</b> Excel ಅಥವಾ Google Sheets ನಲ್ಲಿ <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> ಅಥವಾ <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> ಮಾಡುವುದನ್ನೇ ಮಾಡುತ್ತದೆ, ಆದರೆ ಎಲ್ಲ ಕಾಲಂಗಳಿಗೂ ಒಮ್ಮೆಲೇ.',
    lookup_2: 'ಒಂದು ವ್ಯತ್ಯಾಸ: VLOOKUP ಮತ್ತು XLOOKUP <b>ಮೊದಲ</b> ಹೊಂದಾಣಿಕೆಯಲ್ಲಿ ನಿಲ್ಲುತ್ತವೆ. ಜಾಯಿನ್ <b>ಪ್ರತಿ</b> ಹೊಂದಾಣಿಕೆಯನ್ನೂ ಕೊಡುತ್ತದೆ, ಅದಕ್ಕೇ ಒಂದು-ಹಲವು ಕೀಗಳಿಂದ ಸಾಲುಗಳು ಹೆಚ್ಚುತ್ತವೆ. ಏನೂ ಹೊಂದದಿದ್ದರೆ VLOOKUP #N/A ತೋರಿಸುತ್ತದೆ; ಲೆಫ್ಟ್ ಜಾಯಿನ್ ಕೋಶಗಳನ್ನು ಖಾಲಿ ಬಿಡುತ್ತದೆ.',
    h_stack: '1. ಒಂದರ ಕೆಳಗೊಂದು ಇಡುವ ಫೈಲ್‌ಗಳು',
    stack_note: 'ಒಂದೇ ಬಗೆಯ ಕಾಲಂಗಳಿರುವ ಫೈಲ್‌ಗಳಿಗೆ, ಉದಾ. ಜನವರಿ, ಫೆಬ್ರವರಿ, ಮಾರ್ಚ್ ಮಾರಾಟ. ಕ್ರಮ ಬೇರೆ ಇದ್ದರೂ ಕಾಲಂಗಳನ್ನು ಹೆಸರಿನಿಂದ ಹೊಂದಿಸಲಾಗುತ್ತದೆ.',
    st_empty: 'ಇನ್ನೂ ಫೈಲ್‌ಗಳಿಲ್ಲ. CSV ಫೈಲ್‌ಗಳನ್ನು ಸೇರಿಸಿ ಅಥವಾ ಮಾದರಿ ತೆರೆಯಿರಿ.', st_add: 'CSV ಫೈಲ್‌ಗಳನ್ನು ಸೇರಿಸಿ', st_sample: 'ಮಾದರಿ: 3 ತಿಂಗಳ ಮಾರಾಟ', st_clear: 'ಎಲ್ಲ ತೆಗೆಯಿರಿ',
    st_loose: 'ಕಾಲಂ ಹೆಸರು ಹೊಂದಿಸುವಾಗ ದೊಡ್ಡ-ಸಣ್ಣ ಅಕ್ಷರ ಮತ್ತು ಹೆಚ್ಚುವರಿ ಸ್ಪೇಸ್ ಲೆಕ್ಕಿಸಬೇಡಿ', st_source: '"ಮೂಲ ಫೈಲ್" ಕಾಲಂ ಸೇರಿಸಿ', source_col: 'ಮೂಲ ಫೈಲ್',
    h_stacked: '2. ಜೋಡಿಸಿದ ಫಲಿತಾಂಶ', st_total: '{files} ಫೈಲ್‌ಗಳಿಂದ {rows} ಸಾಲುಗಳು, {cols} ಕಾಲಂಗಳು', st_added: '{n} ಹೊಸ ಕಾಲಂಗಳು', st_missing: 'ಇಲ್ಲದವು: {cols}',
    remove_file: 'ಫೈಲ್ ತೆಗೆಯಿರಿ', legend_blank: 'ಪಟ್ಟೆ ಕೋಶಗಳು ಖಾಲಿ (ಹೆಚ್ಚಾಗಿ ಆ ಫೈಲ್‌ನಲ್ಲಿ ಆ ಕಾಲಂ ಇಲ್ಲದ ಕಾರಣ).', stacked_file: 'ಜೋಡಿಸಿದ',
    tip1: '"ವಿದ್ಯಾರ್ಥಿಗಳು + ಅಂಕಗಳು" ಮಾದರಿಯಿಂದ ಶುರು ಮಾಡಿ, ಇನ್ನರ್, ಲೆಫ್ಟ್, ರೈಟ್, ಫುಲ್ ಔಟರ್ ಬದಲಿಸಿ ನೋಡಿ. ಸಾಲುಗಳ ಸಂಖ್ಯೆ ಮತ್ತು ವೆನ್ ಚಿತ್ರ ಬದಲಾಗುವುದನ್ನು ಗಮನಿಸಿ.',
    tip2: 'ಕಚೇರಿ: ಈ ತಿಂಗಳ ಆರ್ಡರ್‌ಗಳನ್ನು ಗ್ರಾಹಕರ ಪಟ್ಟಿಯೊಂದಿಗೆ ಜೋಡಿಸಿ ಪ್ರತಿ ಗ್ರಾಹಕರ ನಗರ, ಫೋನ್ ಸೇರಿಸಿ, ನಂತರ ಡೆಲಿವರಿಗಾಗಿ ಒಂದು ಫೈಲ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    tip3: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಎರಡೂ ಮಾದರಿ ಫೈಲ್‌ಗಳನ್ನು ಮುದ್ರಿಸಿ. ವಿದ್ಯಾರ್ಥಿಗಳು ಕಾಗದದಲ್ಲಿ ಕೈಯಿಂದ ಜೋಡಿಸಿ, ನಂತರ ಆ್ಯಪ್‌ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಿ. 7 ವಿದ್ಯಾರ್ಥಿಗಳು ಮಾತ್ರ ಹೊಂದಿದರು; ಇನ್ನರ್ ಜಾಯಿನ್‌ನಲ್ಲಿ 9 ಸಾಲು ಏಕೆ?',
    tip4: 'ಕೀ ಎರಡೂ ಫೈಲ್‌ಗಳಲ್ಲಿ ಒಂದೇ ರೀತಿ ಬರೆದಿರಬೇಕು. ಮೊದಲು ಅದನ್ನು ಸ್ವಚ್ಛಗೊಳಿಸಿ (ಸ್ಪೇಸ್, ದೊಡ್ಡ-ಸಣ್ಣ ಅಕ್ಷರ, "007" vs "7") ಇಲ್ಲಿಯ ಆಯ್ಕೆಗಳಿಂದ ಅಥವಾ ಡೇಟಾ ಸ್ವಚ್ಛತೆ ಲ್ಯಾಬ್ ಆ್ಯಪ್‌ನಿಂದ.',
    tip5: 'ಒಂದರ ಕೆಳಗೊಂದು: 12 ತಿಂಗಳ ಮಾರಾಟ ಫೈಲ್‌ಗಳನ್ನು ಸೇರಿಸಿ ಒಂದು ವರ್ಷದ ಫೈಲ್ ಮಾಡಿ; ಪ್ರತಿ ಸಾಲು ಎಲ್ಲಿಂದ ಬಂತು ಎಂದು ತೋರಿಸುವ "ಮೂಲ ಫೈಲ್" ಕಾಲಂ ಜೊತೆ.',
    words_title: 'ತಿಳಿಯಬೇಕಾದ ಪದಗಳು: ಒಳಗೆ ಏನಾಗುತ್ತಿದೆ',
    w_key: '<b>ಕೀ (Key)</b>: ಸಾಲುಗಳನ್ನು ಹೊಂದಿಸುವ ಕಾಲಂ, ರೋಲ್ ನಂಬರ್ ಅಥವಾ ಗ್ರಾಹಕ ID ಯಂತೆ. ಒಳ್ಳೆಯ ಕೀ ಎರಡೂ ಫೈಲ್‌ಗಳಲ್ಲಿ ಒಂದೇ ರೀತಿ ಬರೆದಿರುತ್ತದೆ ಮತ್ತು ಕನಿಷ್ಠ ಒಂದು ಫೈಲ್‌ನಲ್ಲಿ ಒಮ್ಮೆ ಮಾತ್ರ ಇರುತ್ತದೆ.',
    w_inner: '<b>ಇನ್ನರ್ ಜಾಯಿನ್</b>: ಎರಡೂ ಫೈಲ್‌ಗಳಲ್ಲಿ ಹೊಂದುವ ಸಾಲುಗಳನ್ನು ಮಾತ್ರ ಇಡುತ್ತದೆ (ವೆನ್ ಚಿತ್ರದ ನಡುಭಾಗ).',
    w_outer: '<b>ಲೆಫ್ಟ್, ರೈಟ್ ಮತ್ತು ಫುಲ್ ಔಟರ್ ಜಾಯಿನ್</b>: ಹೊಂದದ ಸಾಲುಗಳನ್ನೂ ಇಡುತ್ತವೆ, A ಯಿಂದ, B ಯಿಂದ, ಅಥವಾ ಎರಡರಿಂದಲೂ. ಇಲ್ಲದ ಬದಿ ಖಾಲಿ ಇರುತ್ತದೆ.',
    w_many: '<b>ಒಂದು-ಹಲವು</b>: A ಯ ಒಂದು ಕೀ B ಯ ಹಲವು ಸಾಲುಗಳೊಂದಿಗೆ ಹೊಂದುತ್ತದೆ (ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿ, ಹಲವು ವಿಷಯ). ಫಲಿತಾಂಶದಲ್ಲಿ ಪ್ರತಿ ಹೊಂದಾಣಿಕೆಗೆ ಒಂದು ಸಾಲು.',
    w_union: '<b>ಒಂದರ ಕೆಳಗೊಂದು (append / union)</b>: ಫೈಲ್‌ಗಳನ್ನು ಒಂದರ ಕೆಳಗೊಂದು ಇಡುವುದು. ಇದು ಸಾಲುಗಳನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ; ಜಾಯಿನ್ ಕಾಲಂಗಳನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ.'
  },
  ml: {
    app_title: 'ഫയലുകൾ ചേർക്കൂ & ലയിപ്പിക്കൂ',
    intro: 'രണ്ട് CSV ഫയലുകൾ ഒത്തുവരുന്ന ഒരു കോളം വഴി ചേർക്കൂ (VLOOKUP പോലെ), അല്ലെങ്കിൽ പല മാസത്തെ ഫയലുകൾ ഒന്നിനു താഴെ ഒന്നായി അടുക്കൂ. എന്ത് ഒത്തുവന്നു, എന്ത് വന്നില്ല എന്ന് കണ്ട് ഫലം ഡൗൺലോഡ് ചെയ്യൂ.',
    mode_join: 'രണ്ട് ഫയലുകൾ ചേർക്കൂ', mode_stack: 'പല ഫയലുകൾ അടുക്കൂ',
    h_files: '1. നിങ്ങളുടെ രണ്ട് ഫയലുകൾ', try_sample: 'മാതൃക പരീക്ഷിക്കൂ:', sample_students: 'വിദ്യാർഥികൾ + മാർക്ക്', sample_orders: 'ഓർഡറുകൾ + ഉപഭോക്താക്കൾ',
    file_a: 'ഫയൽ A (ഇടത്)', file_b: 'ഫയൽ B (വലത്)', open_csv: 'CSV തുറക്കൂ', paste_data: 'ഡാറ്റ പേസ്റ്റ് ചെയ്യൂ',
    paste_ph: 'Excel അല്ലെങ്കിൽ Google Sheets വരികൾ, അല്ലെങ്കിൽ CSV ടെക്സ്റ്റ് പേസ്റ്റ് ചെയ്യൂ', use_paste: 'പേസ്റ്റ് ചെയ്ത ഡാറ്റ ഉപയോഗിക്കൂ', pasted_a: 'പേസ്റ്റ്-A', pasted_b: 'പേസ്റ്റ്-B',
    drop_hint: 'CSV ഫയലുകൾ ഇവിടേക്ക് വലിച്ചിടാം. Excel-ൽ: File → Save as → CSV. നിങ്ങളുടെ ഫയലുകൾ ഈ ഉപകരണത്തിൽ തന്നെ.',
    file_info: '{rows} വരികൾ, {cols} കോളങ്ങൾ',
    err_empty: 'വരികളൊന്നും കിട്ടിയില്ല. ആദ്യ വരിയിൽ കോളം പേരുകൾ വേണം.', err_file: 'ഈ ഫയൽ വായിക്കാൻ കഴിഞ്ഞില്ല.',
    err_excel: 'ആദ്യം ഷീറ്റ് CSV ആയി സേവ് ചെയ്യൂ (Excel: File → Save as → CSV).', big_note: 'ഈ ഫയൽ വലുതാണ്, അതിനാൽ അടുത്ത തവണത്തേക്ക് സേവ് ചെയ്തിട്ടില്ല.',
    h_match: '2. വരികൾ എങ്ങനെ ഒത്തുനോക്കാം', key_a: 'A-യിലെ കീ കോളം', key_b: 'B-യിലെ കീ കോളം',
    opt_trim: 'അധിക സ്പേസ് കണക്കാക്കേണ്ട', opt_icase: 'വലിയ-ചെറിയ അക്ഷരം കണക്കാക്കേണ്ട', opt_num: '"007", "7" ഒന്നായി കണക്കാക്കൂ', swap: 'A, B പരസ്പരം മാറ്റൂ',
    join_type: 'ചേർക്കൽ തരം', type_inner: 'ഇന്നർ', type_left: 'ലെഫ്റ്റ്', type_right: 'റൈറ്റ്', type_full: 'ഫുൾ ഔട്ടർ',
    help_inner: 'ഇന്നർ: കീ രണ്ട് ഫയലിലും ഉള്ള വരികൾ മാത്രം.',
    help_left: 'ലെഫ്റ്റ്: A-യിലെ എല്ലാ വരിയും; കീ ഒത്താൽ B-യിലെ വിവരം, ഇല്ലെങ്കിൽ ശൂന്യം.',
    help_right: 'റൈറ്റ്: B-യിലെ എല്ലാ വരിയും; കീ ഒത്താൽ A-യിലെ വിവരം.',
    help_full: 'ഫുൾ ഔട്ടർ: രണ്ട് ഫയലിലെയും എല്ലാ വരിയും, കഴിയുന്നിടത്ത് ഒത്തുനോക്കി.',
    venn_label: 'ചേർക്കൽ തരത്തിന്റെ വെൻ ചിത്രം',
    h_result: '3. ഫലം', st_matched: 'ഒത്തുവന്ന A വരികൾ', only_in: '{name}-ൽ മാത്രം', st_rows: 'ഫലത്തിലെ വരികൾ',
    warn_dup_b: '{name}-ൽ {n} കീകൾ ഒന്നിലധികം തവണ ഉണ്ട്. ഇത് ഒന്ന്-പല (one-to-many) ആണ്: A-യിലെ ഒരു വരി ഓരോ ഒത്തുചേരലിനും ഒരിക്കൽ വരും, അതിനാൽ ഫലത്തിൽ A-യേക്കാൾ കൂടുതൽ വരികൾ ഉണ്ടാകാം.',
    note_dup_a: '{name}-ൽ {n} കീകൾ ഒന്നിലധികം തവണ ഉണ്ട്. അത് കുഴപ്പമില്ല (പല-ഒന്ന്): ആ വരികൾക്കെല്ലാം ഒരേ വിവരം കിട്ടും.',
    warn_blank: '{n} വരികളിൽ കീ ശൂന്യമാണ്. ശൂന്യ കീ ഒരിക്കലും ഒത്തുവരില്ല.',
    warn_none: 'ഒരു വരിയും ഒത്തുവന്നില്ല. ശരിയായ കീ കോളങ്ങൾ തിരഞ്ഞെടുത്തോ എന്ന് നോക്കൂ.',
    hint_numeric: 'സൂചന: ചില കീകൾ ഒരു ഫയലിൽ "007", മറ്റേതിൽ "7" എന്നാണ്. ഒത്തുനോക്കാൻ "007, 7 ഒന്നായി കണക്കാക്കൂ" ടിക്ക് ചെയ്യൂ.',
    out_cols: 'ഫലത്തിലെ കോളങ്ങൾ (മറയ്ക്കാനോ കാണിക്കാനോ അമർത്തൂ):', no_rows: 'ഫലത്തിൽ വരികളില്ല.',
    page_info: 'വരികൾ {from}–{to}, ആകെ {total}', legend_nm: 'വരയുള്ള സെല്ലുകൾ: മറ്റേ ഫയലിൽ ഒത്തുവരുന്ന വരിയില്ല.', download_csv: 'CSV ഡൗൺലോഡ്',
    h_unmatched: '4. ഒത്തുവരാത്ത വരികൾ', um_note: 'ഫലം വിശ്വസിക്കും മുമ്പ് ഇവ നോക്കൂ. കീയിലെ അക്ഷരത്തെറ്റോ ഒരു അധിക 0-ഓ ആണ് സാധാരണ കാരണം.',
    only_in_n: '{name}: {n}', um_none: 'എല്ലാ വരിക്കും ഒത്തുചേരൽ കിട്ടി.', download_um: 'ഈ വരികൾ ഡൗൺലോഡ്', unmatched_file: 'ഒത്തുവരാത്തവ',
    h_lookup: 'ഇതാണ് VLOOKUP / XLOOKUP',
    lookup_1: '<b>ലെഫ്റ്റ് ജോയിൻ</b> Excel-ലോ Google Sheets-ലോ <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> അല്ലെങ്കിൽ <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> ചെയ്യുന്നതു തന്നെ ചെയ്യുന്നു, പക്ഷേ എല്ലാ കോളത്തിനും ഒരുമിച്ച്.',
    lookup_2: 'ഒരു വ്യത്യാസം: VLOOKUP, XLOOKUP <b>ആദ്യ</b> ഒത്തുചേരലിൽ നിൽക്കും. ജോയിൻ <b>എല്ലാ</b> ഒത്തുചേരലും തരും; അതുകൊണ്ടാണ് ഒന്ന്-പല കീകൾ വരികൾ കൂട്ടുന്നത്. ഒന്നും ഒത്തില്ലെങ്കിൽ VLOOKUP #N/A കാണിക്കും; ലെഫ്റ്റ് ജോയിൻ സെല്ലുകൾ ശൂന്യമാക്കും.',
    h_stack: '1. അടുക്കേണ്ട ഫയലുകൾ (ഒന്നിനു താഴെ ഒന്ന്)',
    stack_note: 'ഒരേ തരം കോളങ്ങളുള്ള ഫയലുകൾക്ക്, ഉദാ. ജനുവരി, ഫെബ്രുവരി, മാർച്ച് വിൽപ്പന. ക്രമം വേറെയാണെങ്കിലും കോളങ്ങൾ പേര് വഴി ഒത്തുനോക്കും.',
    st_empty: 'ഇതുവരെ ഫയലുകളില്ല. CSV ഫയലുകൾ ചേർക്കൂ അല്ലെങ്കിൽ മാതൃക തുറക്കൂ.', st_add: 'CSV ഫയലുകൾ ചേർക്കൂ', st_sample: 'മാതൃക: 3 മാസത്തെ വിൽപ്പന', st_clear: 'എല്ലാം മാറ്റൂ',
    st_loose: 'കോളം പേരുകൾ ഒത്തുനോക്കുമ്പോൾ വലിയ-ചെറിയ അക്ഷരവും അധിക സ്പേസും കണക്കാക്കേണ്ട', st_source: '"ഉറവിട ഫയൽ" കോളം ചേർക്കൂ', source_col: 'ഉറവിട ഫയൽ',
    h_stacked: '2. അടുക്കിയ ഫലം', st_total: '{files} ഫയലുകളിൽ നിന്ന് {rows} വരികൾ, {cols} കോളങ്ങൾ', st_added: '{n} പുതിയ കോളങ്ങൾ', st_missing: 'ഇല്ലാത്തവ: {cols}',
    remove_file: 'ഫയൽ മാറ്റൂ', legend_blank: 'വരയുള്ള സെല്ലുകൾ ശൂന്യമാണ് (മിക്കവാറും ആ ഫയലിൽ ആ കോളം ഇല്ലാത്തതിനാൽ).', stacked_file: 'അടുക്കിയത്',
    tip1: '"വിദ്യാർഥികൾ + മാർക്ക്" മാതൃകയിൽ തുടങ്ങി ഇന്നർ, ലെഫ്റ്റ്, റൈറ്റ്, ഫുൾ ഔട്ടർ മാറ്റി നോക്കൂ. വരികളുടെ എണ്ണവും വെൻ ചിത്രവും മാറുന്നത് കാണൂ.',
    tip2: 'ഓഫീസ്: ഈ മാസത്തെ ഓർഡറുകൾ ഉപഭോക്തൃ ലിസ്റ്റുമായി ചേർത്ത് ഓരോരുത്തരുടെയും നഗരവും ഫോണും ചേർക്കൂ, പിന്നെ ഡെലിവറിക്കായി ഒരു ഫയൽ ഡൗൺലോഡ് ചെയ്യൂ.',
    tip3: 'ക്ലാസ് പ്രവർത്തനം: രണ്ട് മാതൃകാ ഫയലുകളും പ്രിന്റ് ചെയ്യൂ. വിദ്യാർഥികൾ കടലാസിൽ കൈകൊണ്ട് ചേർത്ത്, പിന്നെ ആപ്പിൽ പരിശോധിക്കട്ടെ. 7 വിദ്യാർഥികൾ മാത്രം ഒത്തു; ഇന്നർ ജോയിനിൽ 9 വരി എന്തുകൊണ്ട്?',
    tip4: 'കീ രണ്ട് ഫയലിലും ഒരുപോലെ എഴുതിയിരിക്കണം. ആദ്യം അത് വൃത്തിയാക്കൂ (സ്പേസ്, വലിയ-ചെറിയ അക്ഷരം, "007" vs "7") ഇവിടത്തെ ഓപ്ഷനുകളോ ഡാറ്റ ശുചീകരണ ലാബ് ആപ്പോ ഉപയോഗിച്ച്.',
    tip5: 'അടുക്കൽ: 12 മാസത്തെ വിൽപ്പന ഫയലുകൾ ചേർത്ത് ഒരു വർഷത്തെ ഫയൽ ഉണ്ടാക്കൂ; ഓരോ വരിയും എവിടെ നിന്ന് വന്നു എന്ന് കാണിക്കുന്ന "ഉറവിട ഫയൽ" കോളവുമായി.',
    words_title: 'അറിയേണ്ട വാക്കുകൾ: ഉള്ളിൽ എന്താണ് നടക്കുന്നത്',
    w_key: '<b>കീ (Key)</b>: വരികൾ ഒത്തുനോക്കുന്ന കോളം, റോൾ നമ്പറോ ഉപഭോക്തൃ ID-യോ പോലെ. നല്ല കീ രണ്ട് ഫയലിലും ഒരുപോലെ എഴുതിയതും കുറഞ്ഞത് ഒരു ഫയലിൽ ഒരിക്കൽ മാത്രം വരുന്നതുമാണ്.',
    w_inner: '<b>ഇന്നർ ജോയിൻ</b>: രണ്ട് ഫയലിലും ഒത്തുവരുന്ന വരികൾ മാത്രം നിലനിർത്തും (വെൻ ചിത്രത്തിന്റെ നടുഭാഗം).',
    w_outer: '<b>ലെഫ്റ്റ്, റൈറ്റ്, ഫുൾ ഔട്ടർ ജോയിൻ</b>: ഒത്തുവരാത്ത വരികളും നിലനിർത്തും, A-യിൽ നിന്നോ B-യിൽ നിന്നോ രണ്ടിൽ നിന്നുമോ. ഇല്ലാത്ത ഭാഗം ശൂന്യമായിരിക്കും.',
    w_many: '<b>ഒന്ന്-പല</b>: A-യിലെ ഒരു കീ B-യിലെ പല വരികളുമായി ഒത്തുവരും (ഒരു വിദ്യാർഥി, പല വിഷയങ്ങൾ). ഫലത്തിൽ ഓരോ ഒത്തുചേരലിനും ഒരു വരി.',
    w_union: '<b>അടുക്കൽ (append / union)</b>: ഫയലുകൾ ഒന്നിനു താഴെ ഒന്നായി വയ്ക്കൽ. ഇത് വരികൾ കൂട്ടും; ജോയിൻ കോളങ്ങൾ കൂട്ടും.'
  },
  ur: {
    app_title: 'فائلیں جوڑیں اور ملائیں',
    intro: 'دو CSV فائلوں کو ایک ملتے جلتے کالم سے جوڑیں (VLOOKUP کی طرح)، یا کئی مہینوں کی فائلیں ایک کے نیچے ایک رکھیں۔ دیکھیں کیا ملا، کیا نہیں ملا، اور نتیجہ ڈاؤن لوڈ کریں۔',
    mode_join: 'دو فائلیں جوڑیں', mode_stack: 'کئی فائلیں ایک کے نیچے ایک',
    h_files: '1. آپ کی دو فائلیں', try_sample: 'نمونہ آزمائیں:', sample_students: 'طلبہ + نمبر', sample_orders: 'آرڈر + گاہک',
    file_a: 'فائل A (بائیں)', file_b: 'فائل B (دائیں)', open_csv: 'CSV کھولیں', paste_data: 'ڈیٹا پیسٹ کریں',
    paste_ph: 'Excel یا Google Sheets سے قطاریں، یا CSV متن پیسٹ کریں', use_paste: 'پیسٹ کیا ڈیٹا استعمال کریں', pasted_a: 'پیسٹ-A', pasted_b: 'پیسٹ-B',
    drop_hint: 'CSV فائلیں یہاں کھینچ کر بھی چھوڑ سکتے ہیں۔ Excel میں: File → Save as → CSV۔ آپ کی فائلیں اسی ڈیوائس پر رہتی ہیں۔',
    file_info: '{rows} قطاریں، {cols} کالم',
    err_empty: 'کوئی قطار نہیں ملی۔ پہلی قطار میں کالموں کے نام ہونے چاہئیں۔', err_file: 'یہ فائل پڑھی نہیں جا سکی۔',
    err_excel: 'پہلے شیٹ کو CSV میں محفوظ کریں (Excel: File → Save as → CSV)۔', big_note: 'یہ فائل بڑی ہے، اس لیے اگلی بار کے لیے محفوظ نہیں ہوئی۔',
    h_match: '2. قطاریں کیسے ملائیں', key_a: 'A کا کی کالم', key_b: 'B کا کی کالم',
    opt_trim: 'فالتو اسپیس نظرانداز کریں', opt_icase: 'بڑے چھوٹے حروف نظرانداز کریں', opt_num: '"007" اور "7" کو ایک جیسا مانیں', swap: 'A اور B کی جگہ بدلیں',
    join_type: 'جوڑنے کا طریقہ', type_inner: 'اِنر', type_left: 'لیفٹ', type_right: 'رائٹ', type_full: 'فُل آؤٹر',
    help_inner: 'اِنر: صرف وہ قطاریں جن کی کی دونوں فائلوں میں ہے۔',
    help_left: 'لیفٹ: A کی ہر قطار؛ کی ملے تو B کی معلومات، نہ ملے تو خالی۔',
    help_right: 'رائٹ: B کی ہر قطار؛ کی ملے تو A کی معلومات۔',
    help_full: 'فُل آؤٹر: دونوں فائلوں کی ہر قطار، جہاں ممکن ہو ملا کر۔',
    venn_label: 'جوڑنے کے طریقے کا وین خاکہ',
    h_result: '3. نتیجہ', st_matched: 'A کی ملی ہوئی قطاریں', only_in: 'صرف {name} میں', st_rows: 'نتیجے میں قطاریں',
    warn_dup_b: '{name} میں {n} کی ایک سے زیادہ بار ہیں۔ یہ ایک سے کئی (one-to-many) ہے: A کی قطار ہر میل کے لیے ایک بار آتی ہے، اس لیے نتیجے میں A سے زیادہ قطاریں ہو سکتی ہیں۔',
    note_dup_a: '{name} میں {n} کی ایک سے زیادہ بار ہیں۔ یہ ٹھیک ہے (کئی سے ایک): ان سب قطاروں کو وہی معلومات ملتی ہیں۔',
    warn_blank: '{n} قطاروں میں کی خالی ہے۔ خالی کی کبھی نہیں ملتی۔',
    warn_none: 'کوئی قطار نہیں ملی۔ دیکھیں کہ درست کی کالم چنے ہیں۔',
    hint_numeric: 'مشورہ: کچھ کی ایک فائل میں "007" اور دوسری میں "7" ہیں۔ ملانے کے لیے "007 اور 7 کو ایک جیسا مانیں" پر ٹک کریں۔',
    out_cols: 'نتیجے کے کالم (چھپانے یا دکھانے کے لیے دبائیں):', no_rows: 'نتیجے میں کوئی قطار نہیں۔',
    page_info: 'قطاریں {from}–{to}، کل {total}', legend_nm: 'دھاری دار سیل: دوسری فائل میں ملتی قطار نہیں۔', download_csv: 'CSV ڈاؤن لوڈ کریں',
    h_unmatched: '4. جو قطاریں نہیں ملیں', um_note: 'نتیجے پر بھروسا کرنے سے پہلے انہیں دیکھیں۔ کی میں ہجے کی غلطی یا ایک فالتو 0 سب سے عام وجہ ہے۔',
    only_in_n: '{name}: {n}', um_none: 'ہر قطار کا میل مل گیا۔', download_um: 'یہ قطاریں ڈاؤن لوڈ کریں', unmatched_file: 'نہیں-ملیں',
    h_lookup: 'یہی ہے VLOOKUP / XLOOKUP',
    lookup_1: '<b>لیفٹ جوائن</b> وہی کرتا ہے جو Excel یا Google Sheets میں <code>=XLOOKUP(A2, B!A:A, B!C:C)</code> یا <code>=VLOOKUP(A2, B!A:C, 3, FALSE)</code> کرتا ہے، مگر سارے کالم ایک ساتھ۔',
    lookup_2: 'ایک فرق: VLOOKUP اور XLOOKUP <b>پہلے</b> میل پر رک جاتے ہیں۔ جوائن <b>ہر</b> میل دیتا ہے، اسی لیے ایک سے کئی کی سے قطاریں بڑھتی ہیں۔ کچھ نہ ملے تو VLOOKUP #N/A دکھاتا ہے؛ لیفٹ جوائن سیل خالی چھوڑتا ہے۔',
    h_stack: '1. ایک کے نیچے ایک رکھنے والی فائلیں',
    stack_note: 'ایک جیسے کالموں والی فائلوں کے لیے، جیسے جنوری، فروری اور مارچ کی فروخت۔ کالم نام سے ملائے جاتے ہیں، چاہے ترتیب الگ ہو۔',
    st_empty: 'ابھی کوئی فائل نہیں۔ CSV فائلیں شامل کریں یا نمونہ کھولیں۔', st_add: 'CSV فائلیں شامل کریں', st_sample: 'نمونہ: 3 مہینوں کی فروخت', st_clear: 'سب ہٹائیں',
    st_loose: 'کالموں کے نام ملاتے وقت بڑے چھوٹے حروف اور فالتو اسپیس نظرانداز کریں', st_source: '"ماخذ فائل" کالم شامل کریں', source_col: 'ماخذ فائل',
    h_stacked: '2. اکٹھا کیا نتیجہ', st_total: '{files} فائلوں سے {rows} قطاریں، {cols} کالم', st_added: '{n} نئے کالم', st_missing: 'نہیں ہیں: {cols}',
    remove_file: 'فائل ہٹائیں', legend_blank: 'دھاری دار سیل خالی ہیں (اکثر اس لیے کہ اس فائل میں وہ کالم نہیں تھا)۔', stacked_file: 'اکٹھا',
    tip1: '"طلبہ + نمبر" نمونے سے شروع کریں اور اِنر، لیفٹ، رائٹ، فُل آؤٹر بدل کر دیکھیں۔ قطاروں کی گنتی اور وین خاکہ بدلتے دیکھیں۔',
    tip2: 'دفتر: اس مہینے کے آرڈر گاہک فہرست سے جوڑیں تاکہ ہر گاہک کا شہر اور فون آ جائے، پھر ڈیلیوری کے لیے ایک فائل ڈاؤن لوڈ کریں۔',
    tip3: 'کلاس سرگرمی: دونوں نمونہ فائلیں پرنٹ کریں۔ طلبہ کاغذ پر ہاتھ سے جوڑیں، پھر ایپ سے جانچیں۔ صرف 7 طلبہ ملے، پھر اِنر جوائن میں 9 قطاریں کیوں؟',
    tip4: 'کی دونوں فائلوں میں ایک ہی طرح لکھی ہونی چاہیے۔ پہلے اسے صاف کریں (اسپیس، بڑے چھوٹے حروف، "007" بمقابلہ "7") یہاں کے اختیارات سے یا ڈیٹا صفائی لیب ایپ سے۔',
    tip5: 'ایک کے نیچے ایک: 12 مہینوں کی فروخت کی فائلیں ملا کر ایک سال کی فائل بنائیں، "ماخذ فائل" کالم کے ساتھ جو بتائے کہ ہر قطار کہاں سے آئی۔',
    words_title: 'ضروری الفاظ: اندر کیا ہو رہا ہے',
    w_key: '<b>کی (Key)</b>: قطاریں ملانے والا کالم، جیسے رول نمبر یا گاہک ID۔ اچھی کی دونوں فائلوں میں ایک طرح لکھی ہوتی ہے اور کم از کم ایک فائل میں ایک ہی بار ہوتی ہے۔',
    w_inner: '<b>اِنر جوائن</b>: صرف وہ قطاریں رکھتا ہے جو دونوں فائلوں میں ملتی ہیں (وین خاکے کا بیچ والا حصہ)۔',
    w_outer: '<b>لیفٹ، رائٹ اور فُل آؤٹر جوائن</b>: نہ ملنے والی قطاریں بھی رکھتے ہیں، A سے، B سے، یا دونوں سے۔ جو حصہ نہیں ملا وہ خالی رہتا ہے۔',
    w_many: '<b>ایک سے کئی</b>: A کی ایک کی B کی کئی قطاروں سے ملتی ہے (ایک طالب علم، کئی مضامین)۔ نتیجے میں ہر میل کی ایک قطار بنتی ہے۔',
    w_union: '<b>ایک کے نیچے ایک (append / union)</b>: فائلوں کو ایک کے نیچے ایک رکھنا۔ اس سے قطاریں بڑھتی ہیں؛ جوائن سے کالم بڑھتے ہیں۔'
  }
};
