/* Localized trick content for Vedic Maths. Same shape in all 12 languages.
   Step templates use {vars}; numbers are wrapped in LTR isolates by app.js. */
window.APP_CONTENT = {};
window.APP_CONTENT.en = { tricks: {
  mul11: { icon: '✖️', name: 'Multiply by 11', sample: '52 × 11 = 572', tagline: 'Add neighbouring digits and slip them in between.',
    how: ['Write the last digit as it is.', 'Add each pair of neighbouring digits, moving right to left; carry if the sum is 10 or more.', 'Write the first digit (plus any carry) at the front.'],
    why: '11 = 10 + 1, so n × 11 = n × 10 + n. Adding the number to itself shifted one place is the same as adding neighbouring digits.',
    q: 'What is {a} × {b}?',
    steps: { last: 'Last digit of {n} is {d}. Write {d}.', pair: 'Add neighbours {x} + {y} = {s}. Write {w}.', pair_in: 'Add neighbours {x} + {y} + carry {c} = {s}. Write {w}.', pair_out: 'Add neighbours {x} + {y} = {s}. Write {w}, carry {carry}.', pair_in_out: 'Add neighbours {x} + {y} + carry {c} = {s}. Write {w}, carry {carry}.', first: 'First digit {f} goes in front.', first_c: 'First digit {f} + carry {c} = {s} goes in front.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: 'Multiply by 9, 99, 999', sample: '47 × 99 = 4653', tagline: 'One less, then the complement.',
    how: ['If the number has as many digits as the nines: left part = number − 1.', 'Right part = what the number needs to reach 10, 100 or 1000.', 'Otherwise: multiply by 10, 100 or 1000 and subtract the number.'],
    why: '99 = 100 − 1, so n × 99 = n × 100 − n. Splitting this gives (n − 1) followed by (100 − n).',
    q: 'What is {a} × {b}?',
    steps: { c_left: '{n} × {nines}: left part = {n} − 1 = {left}.', c_right: 'Right part = {base} − {n} = {right}.', c_join: 'Join {left} and {right} → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: 'Multiply by 5, 25, 50', sample: '48 × 5 = 240', tagline: 'Multiply by 10 or 100, then halve or quarter.',
    how: ['× 5: multiply by 10, then divide by 2.', '× 50: multiply by 100, then divide by 2.', '× 25: multiply by 100, then divide by 4.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 and 25 = 100 ÷ 4. Adding zeros and halving is easier than long multiplication.',
    q: 'What is {a} × {b}?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: 'Squares ending in 5', sample: '65² = 4225', tagline: 'One more than the one before, then 25.',
    how: ['Remove the last 5; call what is left a.', 'Multiply a by the next number, a + 1.', 'Write 25 after it.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. So the answer is always a × (a + 1) followed by 25.',
    q: 'What is {n}²?',
    steps: { split: '{n}: remove the 5, left part = {a}.', mul: '{a} × {a1} = {prod}.', join: 'Write 25 after {prod} → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'Near a base (Nikhilam)', sample: '97 × 96 = 9312', tagline: 'All from 9, the last from 10: use how far each number is from 100.',
    how: ['Choose the base (10, 100, 1000) close to both numbers.', 'Find each number’s difference from the base.', 'Left part: one number plus the other’s difference.', 'Right part: multiply the two differences (as many digits as zeros in the base).'],
    why: '(base + x)(base + y) = base × (base + x + y) + x × y. Small differences make the multiplication tiny.',
    q: 'What is {a} × {b}?',
    steps: { base: 'Base for {a} and {b} is {base}.', dev: 'Differences: {a} is {da}, {b} is {db} from {base}.', cross: 'Left part: {a} {db} = {left}.', prod: 'Right part: ({da}) × ({db}) = {prod}, written with {k} digits.', borrow: 'Right part {prod} is negative: borrow {c} from the left. Left {left} → {l2}, right {prod} + {cb} = {p2}.', carry: '{prod} is too big for the base {base}: carry {c}, left {left} → {l3}, right {p3}.', join: 'Join {left} and {right} → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'Vertically and crosswise', sample: '23 × 14 = 322', tagline: 'Any multiplication, one column at a time.',
    how: ['Work column by column from the right.', 'In each column, add the products of digits that meet (vertical and cross).', 'Write the units digit and carry the rest to the next column.'],
    why: 'Each column collects all digit pairs whose place values give the same power of 10, exactly like long multiplication, but done in one line.',
    q: 'What is {a} × {b}?',
    steps: { setup: 'Write {a} above {b}.', col: 'Column {i}: {terms} = {sum}. Write {w}.', col_in: 'Column {i}: {terms} = {sum}, + carry {c} = {total}. Write {w}.', col_out: 'Column {i}: {terms} = {sum}. Write {w}, carry {carry}.', col_in_out: 'Column {i}: {terms} = {sum}, + carry {c} = {total}. Write {w}, carry {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: 'Divide by 9', sample: '2301 ÷ 9 = 255 r 6', tagline: 'Running digit sums give the quotient.',
    how: ['Copy the first digit.', 'Keep adding the next digit to the last sum (leave out the final digit).', 'These sums form the quotient; the sum of all digits is the remainder.', 'If the remainder is 9 or more, take away 9 and add 1 to the quotient.'],
    why: '10 = 9 + 1, so every place value leaves remainder 1 when divided by 9. That is why the digit sums work.',
    q: 'What is {n} ÷ 9? (quotient and remainder)',
    steps: { first: 'First digit of {n}: {d}.', add: '{prev} + {d} = {s}.', quot: 'Sums {list} → quotient {q}.', rem: 'Remainder = {list} = {r}.', adjust: 'Remainder {r} ≥ 9: quotient {q} → {q2}, remainder {r2}.', ans: '{n} ÷ 9 = {q} remainder {r}' } },
  cuberoot: { icon: '🧊', name: 'Cube roots', sample: '∛17576 = 26', tagline: 'Last digit gives the units, the front gives the tens.',
    how: ['Split off the last three digits.', 'The last digit of the cube tells the units digit of the root (2↔8, 3↔7, others same).', 'For the front part, find the biggest cube that fits: that is the tens digit.'],
    why: 'Cubes of 0–9 all end in different digits, and a two-digit root has a cube between (10t)³ and (10t + 10)³.',
    q: 'What is the cube root of {n}?',
    steps: { split: '{n} → front {left}, back {right}.', units: 'Last digit {last}: {u}³ = {u3} ends in {last}, so units = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, so tens = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'Percentage tricks', sample: '15% of 240 = 36', tagline: 'Build any percent from 10%, 5% and halves.',
    how: ['10%: divide by 10.', '5%: half of 10%.', '50% is half, 25% is half of half, 75% = 50% + 25%.', 'Add the pieces: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'Percent means “out of 100”. Splitting a percent into easy pieces avoids big multiplication.',
    q: 'What is {p}% of {n}?',
    steps: { half: '50% of {n} = {half}.', quarter: '25% = half of {half} = {quarter}.', sum: 'Add: {parts} = {ans}.', ten: '10% of {n} = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = half of {ten} = {five}.', ans: '{p}% of {n} = {ans}' } },
  digitsum: { icon: '✅', name: 'Digit-sum check', sample: '47 × 23 = 1081 ✓', tagline: 'Check any multiplication in seconds.',
    how: ['Add the digits of a number again and again until one digit is left (9 counts as 0 for checking).', 'Find the digit sums of both numbers and multiply them; reduce again.', 'Compare with the digit sum of the answer. Different means the answer is wrong.'],
    why: 'A number and its digit sum leave the same remainder when divided by 9, and remainders multiply.',
    q: 'What is the digit sum of {n}?', q_check: 'Is {a} × {b} = {c} correct?',
    steps: { start: 'Find the digit sum of {n}.', sum: '{label}: {list} = {s}.', single: '{n} is already one digit.', root: 'Digit sum of {n} = {r}.', check: 'Check {a} × {b} = {c}.', roots: 'Digit sums: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: 'Digit sum of {c} → {rc}.', match: '{rm} = {rc}: the answer is probably right ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} is wrong ✗' } }
} };
window.APP_CONTENT.hi = { tricks: {
  mul11: { icon: '✖️', name: '11 से गुणा', sample: '52 × 11 = 572', tagline: 'पास-पास के अंक जोड़ें और बीच में रख दें।',
    how: ['आख़िरी अंक जैसा है वैसा लिखें।', 'दाएँ से बाएँ चलते हुए पास-पास के दो-दो अंक जोड़ें; योग 10 या ज़्यादा हो तो हासिल ले जाएँ।', 'सबसे आगे पहला अंक (और हासिल) लिखें।'],
    why: '11 = 10 + 1, इसलिए n × 11 = n × 10 + n। संख्या को एक जगह खिसकाकर खुद में जोड़ना, पास-पास के अंक जोड़ने जैसा ही है।',
    q: '{a} × {b} कितना है?',
    steps: { last: '{n} का आख़िरी अंक {d} है। {d} लिखें।', pair: 'पास के अंक {x} + {y} = {s}। {w} लिखें।', pair_in: 'पास के अंक {x} + {y} + हासिल {c} = {s}। {w} लिखें।', pair_out: 'पास के अंक {x} + {y} = {s}। {w} लिखें, हासिल {carry}।', pair_in_out: 'पास के अंक {x} + {y} + हासिल {c} = {s}। {w} लिखें, हासिल {carry}।', first: 'पहला अंक {f} सबसे आगे लिखें।', first_c: 'पहला अंक {f} + हासिल {c} = {s} सबसे आगे लिखें।', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 से गुणा', sample: '47 × 99 = 4653', tagline: 'एक कम, फिर पूरक।',
    how: ['अगर संख्या में उतने ही अंक हों जितने 9 हैं: बायाँ भाग = संख्या − 1।', 'दायाँ भाग = संख्या को 10, 100 या 1000 तक पहुँचने के लिए जितना चाहिए।', 'वरना: 10, 100 या 1000 से गुणा करें और संख्या घटा दें।'],
    why: '99 = 100 − 1, इसलिए n × 99 = n × 100 − n। इसे बाँटने पर (n − 1) के बाद (100 − n) आता है।',
    q: '{a} × {b} कितना है?',
    steps: { c_left: '{n} × {nines}: बायाँ भाग = {n} − 1 = {left}।', c_right: 'दायाँ भाग = {base} − {n} = {right}।', c_join: '{left} और {right} जोड़कर लिखें → {ans}।', n_is: '{nines} = {base} − 1।', n_times: '{n} × {base} = {m}।', n_minus: '{m} − {n} = {ans}।', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 से गुणा', sample: '48 × 5 = 240', tagline: '10 या 100 से गुणा करें, फिर आधा या चौथाई।',
    how: ['× 5: 10 से गुणा करें, फिर 2 से भाग दें।', '× 50: 100 से गुणा करें, फिर 2 से भाग दें।', '× 25: 100 से गुणा करें, फिर 4 से भाग दें।'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 और 25 = 100 ÷ 4। शून्य लगाकर आधा करना लंबे गुणा से आसान है।',
    q: '{a} × {b} कितना है?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}।', f_times: '{n} × {pw} = {t}।', f_div: '{t} ÷ {dv} = {ans}।', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 पर ख़त्म होने वाले वर्ग', sample: '65² = 4225', tagline: 'पहले वाले को उससे एक अधिक से गुणा, फिर 25।',
    how: ['आख़िरी 5 हटा दें; जो बचा उसे a कहें।', 'a को अगली संख्या a + 1 से गुणा करें।', 'उसके बाद 25 लिख दें।'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25। इसलिए उत्तर हमेशा a × (a + 1) और उसके बाद 25 होता है।',
    q: '{n}² कितना है?',
    steps: { split: '{n}: 5 हटाएँ, बचा भाग = {a}।', mul: '{a} × {a1} = {prod}।', join: '{prod} के बाद 25 लिखें → {ans}।', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'आधार के पास (निखिलम्)', sample: '97 × 96 = 9312', tagline: 'निखिलं नवतश्चरमं दशतः: देखें हर संख्या 100 से कितनी दूर है।',
    how: ['दोनों संख्याओं के पास का आधार (10, 100, 1000) चुनें।', 'हर संख्या का आधार से अंतर निकालें।', 'बायाँ भाग: एक संख्या + दूसरी का अंतर।', 'दायाँ भाग: दोनों अंतरों का गुणा (आधार में जितने शून्य, उतने अंक)।'],
    why: '(आधार + x)(आधार + y) = आधार × (आधार + x + y) + x × y। अंतर छोटे हों तो गुणा बहुत छोटा हो जाता है।',
    q: '{a} × {b} कितना है?',
    steps: { base: '{a} और {b} का आधार {base} है।', dev: 'अंतर: {base} से {a} का {da}, {b} का {db}।', cross: 'बायाँ भाग: {a} {db} = {left}।', prod: 'दायाँ भाग: ({da}) × ({db}) = {prod}, {k} अंकों में लिखें।', borrow: 'दायाँ भाग {prod} ऋणात्मक है: बाएँ से {c} उधार लें। बायाँ {left} → {l2}, दायाँ {prod} + {cb} = {p2}।', carry: '{prod} आधार {base} के लिए बड़ा है: हासिल {c}, बायाँ {left} → {l3}, दायाँ {p3}।', join: '{left} और {right} जोड़कर लिखें → {ans}।', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ऊर्ध्व-तिर्यक (सीधा और तिरछा)', sample: '23 × 14 = 322', tagline: 'कोई भी गुणा, एक-एक कॉलम करके।',
    how: ['दाएँ से एक-एक कॉलम करके चलें।', 'हर कॉलम में मिलने वाले अंकों के गुणनफल (सीधे और तिरछे) जोड़ें।', 'इकाई का अंक लिखें और बाक़ी अगले कॉलम में ले जाएँ।'],
    why: 'हर कॉलम में वे सारे अंक-जोड़े आते हैं जिनका स्थानीय मान 10 की एक ही घात देता है, बिल्कुल लंबे गुणा जैसा, बस एक लाइन में।',
    q: '{a} × {b} कितना है?',
    steps: { setup: '{a} के नीचे {b} लिखें।', col: 'कॉलम {i}: {terms} = {sum}। {w} लिखें।', col_in: 'कॉलम {i}: {terms} = {sum}, + हासिल {c} = {total}। {w} लिखें।', col_out: 'कॉलम {i}: {terms} = {sum}। {w} लिखें, हासिल {carry}।', col_in_out: 'कॉलम {i}: {terms} = {sum}, + हासिल {c} = {total}। {w} लिखें, हासिल {carry}।', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 से भाग', sample: '2301 ÷ 9 = 255 (6)', tagline: 'अंकों के चलते योग से भागफल मिलता है।',
    how: ['पहला अंक वैसा ही लिखें।', 'पिछले योग में अगला अंक जोड़ते जाएँ (आख़िरी अंक छोड़ दें)।', 'ये योग भागफल बनाते हैं; सभी अंकों का योग शेषफल है।', 'शेषफल 9 या ज़्यादा हो तो 9 घटाएँ और भागफल में 1 जोड़ें।'],
    why: '10 = 9 + 1, इसलिए 9 से भाग देने पर हर स्थानीय मान 1 शेष छोड़ता है। इसीलिए अंकों का योग काम करता है।',
    q: '{n} ÷ 9 कितना है? (भागफल और शेषफल)',
    steps: { first: '{n} का पहला अंक: {d}।', add: '{prev} + {d} = {s}।', quot: 'योग {list} → भागफल {q}।', rem: 'शेषफल = {list} = {r}।', adjust: 'शेषफल {r} ≥ 9: भागफल {q} → {q2}, शेषफल {r2}।', ans: '{n} ÷ 9 = {q}, शेषफल {r}' } },
  cuberoot: { icon: '🧊', name: 'घनमूल', sample: '∛17576 = 26', tagline: 'आख़िरी अंक से इकाई, आगे के भाग से दहाई।',
    how: ['आख़िरी तीन अंक अलग करें।', 'घन का आख़िरी अंक मूल का इकाई अंक बताता है (2↔8, 3↔7, बाक़ी वही)।', 'आगे वाले भाग में समाने वाला सबसे बड़ा घन ढूँढें: वही दहाई का अंक है।'],
    why: '0–9 के घन सब अलग-अलग अंकों पर ख़त्म होते हैं, और दो अंकों के मूल का घन (10t)³ और (10t + 10)³ के बीच होता है।',
    q: '{n} का घनमूल कितना है?',
    steps: { split: '{n} → आगे {left}, पीछे {right}।', units: 'आख़िरी अंक {last}: {u}³ = {u3} का आख़िरी अंक {last} है, इसलिए इकाई = {u}।', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, इसलिए दहाई = {t}।', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'प्रतिशत की तरकीबें', sample: '240 का 15% = 36', tagline: 'हर प्रतिशत 10%, 5% और आधे से बनाएँ।',
    how: ['10%: 10 से भाग दें।', '5%: 10% का आधा।', '50% आधा है, 25% आधे का आधा, 75% = 50% + 25%।', 'टुकड़े जोड़ें: 15% = 10% + 5%, 30% = 3 × 10%।'],
    why: 'प्रतिशत यानी “100 में से”। प्रतिशत को आसान टुकड़ों में बाँटने से बड़ा गुणा नहीं करना पड़ता।',
    q: '{n} का {p}% कितना है?',
    steps: { half: '{n} का 50% = {half}।', quarter: '25% = {half} का आधा = {quarter}।', sum: 'जोड़ें: {parts} = {ans}।', ten: '{n} का 10% = {ten}।', minus: '90% = {n} − {ten} = {ans}।', tens: '{p}% = {tens} × {ten} = {val}।', five: '5% = {ten} का आधा = {five}।', ans: '{n} का {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'अंक-योग से जाँच', sample: '47 × 23 = 1081 ✓', tagline: 'कोई भी गुणा कुछ ही सेकंड में जाँचें।',
    how: ['किसी संख्या के अंक बार-बार जोड़ें जब तक एक अंक न बचे (जाँच में 9 को 0 जैसा मानें)।', 'दोनों संख्याओं के अंक-योग का गुणा करें; फिर से एक अंक तक घटाएँ।', 'उत्तर के अंक-योग से मिलाएँ। अलग हो तो उत्तर ग़लत है।'],
    why: 'कोई संख्या और उसका अंक-योग 9 से भाग देने पर एक जैसा शेष छोड़ते हैं, और शेषफल आपस में गुणा होते हैं।',
    q: '{n} का अंक-योग कितना है?', q_check: 'क्या {a} × {b} = {c} सही है?',
    steps: { start: '{n} का अंक-योग निकालें।', sum: '{label}: {list} = {s}।', single: '{n} पहले से एक अंक है।', root: '{n} का अंक-योग = {r}।', check: '{a} × {b} = {c} जाँचें।', roots: 'अंक-योग: {a} → {ra}, {b} → {rb}।', mulroot: '{ra} × {rb} = {prod} → {rm}।', croot: '{c} का अंक-योग → {rc}।', match: '{rm} = {rc}: उत्तर शायद सही है ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ग़लत है ✗' } }
} };
window.APP_CONTENT.mr = { tricks: {
  mul11: { icon: '✖️', name: '11 ने गुणाकार', sample: '52 × 11 = 572', tagline: 'शेजारचे अंक मिळवा आणि मधे ठेवा.',
    how: ['शेवटचा अंक जसाच्या तसा लिहा.', 'उजवीकडून डावीकडे जाताना शेजारच्या अंकांची बेरीज करा; बेरीज 10 किंवा जास्त असेल तर हातचा न्या.', 'सर्वात पुढे पहिला अंक (आणि हातचा) लिहा.'],
    why: '11 = 10 + 1, म्हणून n × 11 = n × 10 + n. संख्या एका जागी सरकवून तिच्यातच मिळवणे म्हणजे शेजारचे अंक मिळवणेच.',
    q: '{a} × {b} किती?',
    steps: { last: '{n} चा शेवटचा अंक {d}. {d} लिहा.', pair: 'शेजारचे अंक {x} + {y} = {s}. {w} लिहा.', pair_in: 'शेजारचे अंक {x} + {y} + हातचा {c} = {s}. {w} लिहा.', pair_out: 'शेजारचे अंक {x} + {y} = {s}. {w} लिहा, हातचा {carry}.', pair_in_out: 'शेजारचे अंक {x} + {y} + हातचा {c} = {s}. {w} लिहा, हातचा {carry}.', first: 'पहिला अंक {f} सर्वात पुढे लिहा.', first_c: 'पहिला अंक {f} + हातचा {c} = {s} सर्वात पुढे लिहा.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 ने गुणाकार', sample: '47 × 99 = 4653', tagline: 'एक कमी, मग पूरक.',
    how: ['संख्येत जितके 9 तितकेच अंक असतील तर: डावा भाग = संख्या − 1.', 'उजवा भाग = संख्येला 10, 100 किंवा 1000 होण्यासाठी लागणारे.', 'नाहीतर: 10, 100 किंवा 1000 ने गुणा आणि संख्या वजा करा.'],
    why: '99 = 100 − 1, म्हणून n × 99 = n × 100 − n. हे विभागले की (n − 1) नंतर (100 − n) येते.',
    q: '{a} × {b} किती?',
    steps: { c_left: '{n} × {nines}: डावा भाग = {n} − 1 = {left}.', c_right: 'उजवा भाग = {base} − {n} = {right}.', c_join: '{left} आणि {right} जोडून लिहा → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 ने गुणाकार', sample: '48 × 5 = 240', tagline: '10 किंवा 100 ने गुणा, मग अर्धा किंवा पाव.',
    how: ['× 5: 10 ने गुणा, मग 2 ने भागा.', '× 50: 100 ने गुणा, मग 2 ने भागा.', '× 25: 100 ने गुणा, मग 4 ने भागा.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 आणि 25 = 100 ÷ 4. शून्य जोडून अर्धे करणे लांब गुणाकारापेक्षा सोपे.',
    q: '{a} × {b} किती?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 ने संपणाऱ्या संख्यांचे वर्ग', sample: '65² = 4225', tagline: 'आधीच्याला पुढच्याने गुणा, मग 25.',
    how: ['शेवटचा 5 काढा; उरलेल्याला a म्हणा.', 'a ला पुढच्या संख्येने, a + 1 ने गुणा.', 'त्यानंतर 25 लिहा.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. म्हणून उत्तर नेहमी a × (a + 1) आणि नंतर 25.',
    q: '{n}² किती?',
    steps: { split: '{n}: 5 काढा, उरलेला भाग = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} नंतर 25 लिहा → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'पायाजवळच्या संख्या (निखिलम्)', sample: '97 × 96 = 9312', tagline: 'सगळे 9 मधून, शेवटचा 10 मधून: प्रत्येक संख्या 100 पासून किती दूर ते पाहा.',
    how: ['दोन्ही संख्यांच्या जवळचा पाया (10, 100, 1000) निवडा.', 'प्रत्येक संख्येचा पायापासूनचा फरक काढा.', 'डावा भाग: एक संख्या + दुसरीचा फरक.', 'उजवा भाग: दोन्ही फरकांचा गुणाकार (पायात जितके शून्य तितके अंक).'],
    why: '(पाया + x)(पाया + y) = पाया × (पाया + x + y) + x × y. फरक लहान असले की गुणाकार खूप छोटा होतो.',
    q: '{a} × {b} किती?',
    steps: { base: '{a} आणि {b} साठी पाया {base}.', dev: 'फरक: {base} पासून {a} चा {da}, {b} चा {db}.', cross: 'डावा भाग: {a} {db} = {left}.', prod: 'उजवा भाग: ({da}) × ({db}) = {prod}, {k} अंकांत लिहा.', borrow: 'उजवा भाग {prod} ऋण आहे: डावीकडून {c} उसने घ्या. डावा {left} → {l2}, उजवा {prod} + {cb} = {p2}.', carry: '{prod} हा पाया {base} साठी मोठा आहे: हातचा {c}, डावा {left} → {l3}, उजवा {p3}.', join: '{left} आणि {right} जोडून लिहा → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ऊर्ध्व-तिर्यक (उभे आणि तिरके)', sample: '23 × 14 = 322', tagline: 'कोणताही गुणाकार, एकेक स्तंभ करून.',
    how: ['उजवीकडून एकेक स्तंभ करा.', 'प्रत्येक स्तंभात भेटणाऱ्या अंकांचे गुणाकार (उभे आणि तिरके) मिळवा.', 'एकक अंक लिहा आणि बाकीचा हातचा पुढच्या स्तंभात न्या.'],
    why: 'प्रत्येक स्तंभात 10 च्या एकाच घाताचे सर्व अंक-जोडे येतात, अगदी लांब गुणाकारासारखे, पण एका ओळीत.',
    q: '{a} × {b} किती?',
    steps: { setup: '{a} च्या खाली {b} लिहा.', col: 'स्तंभ {i}: {terms} = {sum}. {w} लिहा.', col_in: 'स्तंभ {i}: {terms} = {sum}, + हातचा {c} = {total}. {w} लिहा.', col_out: 'स्तंभ {i}: {terms} = {sum}. {w} लिहा, हातचा {carry}.', col_in_out: 'स्तंभ {i}: {terms} = {sum}, + हातचा {c} = {total}. {w} लिहा, हातचा {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 ने भागाकार', sample: '2301 ÷ 9 = 255 (6)', tagline: 'अंकांच्या चालू बेरजेतून भागाकार मिळतो.',
    how: ['पहिला अंक तसाच लिहा.', 'मागच्या बेरजेत पुढचा अंक मिळवत जा (शेवटचा अंक सोडा).', 'या बेरजा भागाकार बनवतात; सर्व अंकांची बेरीज बाकी असते.', 'बाकी 9 किंवा जास्त असेल तर 9 वजा करा आणि भागाकारात 1 मिळवा.'],
    why: '10 = 9 + 1, म्हणून 9 ने भागल्यावर प्रत्येक स्थानिक किंमत 1 बाकी ठेवते. म्हणून अंकांची बेरीज चालते.',
    q: '{n} ÷ 9 किती? (भागाकार आणि बाकी)',
    steps: { first: '{n} चा पहिला अंक: {d}.', add: '{prev} + {d} = {s}.', quot: 'बेरजा {list} → भागाकार {q}.', rem: 'बाकी = {list} = {r}.', adjust: 'बाकी {r} ≥ 9: भागाकार {q} → {q2}, बाकी {r2}.', ans: '{n} ÷ 9 = {q}, बाकी {r}' } },
  cuberoot: { icon: '🧊', name: 'घनमूळ', sample: '∛17576 = 26', tagline: 'शेवटच्या अंकातून एकक, पुढच्या भागातून दशक.',
    how: ['शेवटचे तीन अंक वेगळे करा.', 'घनाचा शेवटचा अंक मुळाचा एकक अंक सांगतो (2↔8, 3↔7, बाकी तेच).', 'पुढच्या भागात बसणारा सर्वात मोठा घन शोधा: तोच दशक अंक.'],
    why: '0–9 चे घन सगळे वेगवेगळ्या अंकांनी संपतात, आणि दोन अंकी मुळाचा घन (10t)³ आणि (10t + 10)³ यांच्यामध्ये असतो.',
    q: '{n} चे घनमूळ किती?',
    steps: { split: '{n} → पुढे {left}, मागे {right}.', units: 'शेवटचा अंक {last}: {u}³ = {u3} चा शेवट {last}, म्हणून एकक = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, म्हणून दशक = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'टक्केवारीच्या युक्त्या', sample: '240 चे 15% = 36', tagline: 'कोणतीही टक्केवारी 10%, 5% आणि अर्ध्यातून बनवा.',
    how: ['10%: 10 ने भागा.', '5%: 10% चा अर्धा.', '50% म्हणजे अर्धा, 25% अर्ध्याचा अर्धा, 75% = 50% + 25%.', 'तुकडे मिळवा: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'टक्का म्हणजे “100 पैकी”. टक्केवारी सोप्या तुकड्यांत तोडली की मोठा गुणाकार टळतो.',
    q: '{n} चे {p}% किती?',
    steps: { half: '{n} चे 50% = {half}.', quarter: '25% = {half} चा अर्धा = {quarter}.', sum: 'मिळवा: {parts} = {ans}.', ten: '{n} चे 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten} चा अर्धा = {five}.', ans: '{n} चे {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'अंक-बेरजेने तपासणी', sample: '47 × 23 = 1081 ✓', tagline: 'कोणताही गुणाकार काही सेकंदांत तपासा.',
    how: ['एक अंक उरेपर्यंत संख्येचे अंक पुन्हा पुन्हा मिळवा (तपासताना 9 म्हणजे 0).', 'दोन्ही संख्यांच्या अंक-बेरजांचा गुणाकार करा; पुन्हा एक अंक करा.', 'उत्तराच्या अंक-बेरजेशी जुळवा. वेगळे आले तर उत्तर चुकीचे.'],
    why: 'संख्या आणि तिची अंक-बेरीज 9 ने भागल्यावर सारखीच बाकी ठेवतात, आणि बाक्यांचा गुणाकार होतो.',
    q: '{n} ची अंक-बेरीज किती?', q_check: '{a} × {b} = {c} बरोबर आहे का?',
    steps: { start: '{n} ची अंक-बेरीज काढा.', sum: '{label}: {list} = {s}.', single: '{n} आधीच एक अंकी आहे.', root: '{n} ची अंक-बेरीज = {r}.', check: '{a} × {b} = {c} तपासा.', roots: 'अंक-बेरजा: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} ची अंक-बेरीज → {rc}.', match: '{rm} = {rc}: उत्तर बहुधा बरोबर ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} चुकीचे ✗' } }
} };
window.APP_CONTENT.bn = { tricks: {
  mul11: { icon: '✖️', name: '11 দিয়ে গুণ', sample: '52 × 11 = 572', tagline: 'পাশাপাশি অঙ্ক যোগ করে মাঝখানে বসান।',
    how: ['শেষ অঙ্কটি যেমন আছে তেমন লিখুন।', 'ডান থেকে বাঁয়ে যেতে যেতে পাশাপাশি দুটি অঙ্ক যোগ করুন; যোগফল 10 বা বেশি হলে হাতে রাখুন।', 'একদম সামনে প্রথম অঙ্ক (আর হাতের সংখ্যা) লিখুন।'],
    why: '11 = 10 + 1, তাই n × 11 = n × 10 + n। সংখ্যাকে এক ঘর সরিয়ে নিজের সঙ্গে যোগ করা মানেই পাশাপাশি অঙ্ক যোগ করা।',
    q: '{a} × {b} কত?',
    steps: { last: '{n}-এর শেষ অঙ্ক {d}। {d} লিখুন।', pair: 'পাশের অঙ্ক {x} + {y} = {s}। {w} লিখুন।', pair_in: 'পাশের অঙ্ক {x} + {y} + হাতে {c} = {s}। {w} লিখুন।', pair_out: 'পাশের অঙ্ক {x} + {y} = {s}। {w} লিখুন, হাতে {carry}।', pair_in_out: 'পাশের অঙ্ক {x} + {y} + হাতে {c} = {s}। {w} লিখুন, হাতে {carry}।', first: 'প্রথম অঙ্ক {f} সামনে বসান।', first_c: 'প্রথম অঙ্ক {f} + হাতে {c} = {s} সামনে বসান।', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 দিয়ে গুণ', sample: '47 × 99 = 4653', tagline: 'এক কম, তারপর পূরক।',
    how: ['সংখ্যায় যতগুলো 9 ততগুলো অঙ্ক থাকলে: বাঁ অংশ = সংখ্যা − 1।', 'ডান অংশ = সংখ্যাটির 10, 100 বা 1000 হতে যত লাগে।', 'নইলে: 10, 100 বা 1000 দিয়ে গুণ করে সংখ্যাটি বিয়োগ করুন।'],
    why: '99 = 100 − 1, তাই n × 99 = n × 100 − n। এটি ভাঙলে (n − 1)-এর পরে (100 − n) আসে।',
    q: '{a} × {b} কত?',
    steps: { c_left: '{n} × {nines}: বাঁ অংশ = {n} − 1 = {left}।', c_right: 'ডান অংশ = {base} − {n} = {right}।', c_join: '{left} আর {right} পাশাপাশি লিখুন → {ans}।', n_is: '{nines} = {base} − 1।', n_times: '{n} × {base} = {m}।', n_minus: '{m} − {n} = {ans}।', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 দিয়ে গুণ', sample: '48 × 5 = 240', tagline: '10 বা 100 দিয়ে গুণ, তারপর অর্ধেক বা এক-চতুর্থাংশ।',
    how: ['× 5: 10 দিয়ে গুণ করে 2 দিয়ে ভাগ করুন।', '× 50: 100 দিয়ে গুণ করে 2 দিয়ে ভাগ করুন।', '× 25: 100 দিয়ে গুণ করে 4 দিয়ে ভাগ করুন।'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 আর 25 = 100 ÷ 4। শূন্য বসিয়ে অর্ধেক করা লম্বা গুণের চেয়ে সহজ।',
    q: '{a} × {b} কত?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}।', f_times: '{n} × {pw} = {t}।', f_div: '{t} ÷ {dv} = {ans}।', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 দিয়ে শেষ হওয়া সংখ্যার বর্গ', sample: '65² = 4225', tagline: 'আগেরটিকে তার পরেরটি দিয়ে গুণ, তারপর 25।',
    how: ['শেষের 5 সরিয়ে দিন; যা থাকল তাকে a বলুন।', 'a-কে পরের সংখ্যা a + 1 দিয়ে গুণ করুন।', 'তার পরে 25 লিখুন।'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25। তাই উত্তর সবসময় a × (a + 1), তারপর 25।',
    q: '{n}² কত?',
    steps: { split: '{n}: 5 সরান, বাকি অংশ = {a}।', mul: '{a} × {a1} = {prod}।', join: '{prod}-এর পরে 25 লিখুন → {ans}।', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'ভিত্তির কাছে (নিখিলম)', sample: '97 × 96 = 9312', tagline: 'সব 9 থেকে, শেষটি 10 থেকে: দেখুন প্রতিটি সংখ্যা 100 থেকে কত দূরে।',
    how: ['দুটি সংখ্যার কাছের ভিত্তি (10, 100, 1000) বেছে নিন।', 'প্রতিটি সংখ্যার ভিত্তি থেকে পার্থক্য বের করুন।', 'বাঁ অংশ: একটি সংখ্যা + অন্যটির পার্থক্য।', 'ডান অংশ: দুই পার্থক্যের গুণফল (ভিত্তিতে যত শূন্য, তত অঙ্ক)।'],
    why: '(ভিত্তি + x)(ভিত্তি + y) = ভিত্তি × (ভিত্তি + x + y) + x × y। পার্থক্য ছোট হলে গুণ খুব ছোট হয়ে যায়।',
    q: '{a} × {b} কত?',
    steps: { base: '{a} আর {b}-এর ভিত্তি {base}।', dev: 'পার্থক্য: {base} থেকে {a}-এর {da}, {b}-এর {db}।', cross: 'বাঁ অংশ: {a} {db} = {left}।', prod: 'ডান অংশ: ({da}) × ({db}) = {prod}, {k} অঙ্কে লিখুন।', borrow: 'ডান অংশ {prod} ঋণাত্মক: বাঁ দিক থেকে {c} ধার নিন। বাঁ {left} → {l2}, ডান {prod} + {cb} = {p2}।', carry: '{prod} ভিত্তি {base}-এর জন্য বড়: হাতে {c}, বাঁ {left} → {l3}, ডান {p3}।', join: '{left} আর {right} পাশাপাশি লিখুন → {ans}।', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ঊর্ধ্ব-তির্যক (খাড়া ও আড়াআড়ি)', sample: '23 × 14 = 322', tagline: 'যেকোনো গুণ, এক এক কলাম করে।',
    how: ['ডান দিক থেকে এক এক কলাম করে এগোন।', 'প্রতিটি কলামে যে অঙ্কগুলো মেলে তাদের গুণফল (খাড়া ও আড়াআড়ি) যোগ করুন।', 'একক অঙ্কটি লিখুন, বাকিটা পরের কলামে নিয়ে যান।'],
    why: 'প্রতিটি কলামে সেই সব অঙ্ক-জোড়া আসে যাদের স্থানীয় মান 10-এর একই ঘাত দেয়, ঠিক লম্বা গুণের মতো, শুধু এক লাইনে।',
    q: '{a} × {b} কত?',
    steps: { setup: '{a}-এর নিচে {b} লিখুন।', col: 'কলাম {i}: {terms} = {sum}। {w} লিখুন।', col_in: 'কলাম {i}: {terms} = {sum}, + হাতে {c} = {total}। {w} লিখুন।', col_out: 'কলাম {i}: {terms} = {sum}। {w} লিখুন, হাতে {carry}।', col_in_out: 'কলাম {i}: {terms} = {sum}, + হাতে {c} = {total}। {w} লিখুন, হাতে {carry}।', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 দিয়ে ভাগ', sample: '2301 ÷ 9 = 255 (6)', tagline: 'অঙ্কের চলতি যোগফল থেকেই ভাগফল।',
    how: ['প্রথম অঙ্কটি যেমন আছে লিখুন।', 'আগের যোগফলে পরের অঙ্ক যোগ করতে থাকুন (শেষ অঙ্কটি বাদ)।', 'এই যোগফলগুলোই ভাগফল; সব অঙ্কের যোগফল হল ভাগশেষ।', 'ভাগশেষ 9 বা বেশি হলে 9 বাদ দিন আর ভাগফলে 1 যোগ করুন।'],
    why: '10 = 9 + 1, তাই 9 দিয়ে ভাগ করলে প্রতিটি স্থানীয় মান 1 ভাগশেষ রাখে। সেজন্যই অঙ্কের যোগফল কাজ করে।',
    q: '{n} ÷ 9 কত? (ভাগফল ও ভাগশেষ)',
    steps: { first: '{n}-এর প্রথম অঙ্ক: {d}।', add: '{prev} + {d} = {s}।', quot: 'যোগফল {list} → ভাগফল {q}।', rem: 'ভাগশেষ = {list} = {r}।', adjust: 'ভাগশেষ {r} ≥ 9: ভাগফল {q} → {q2}, ভাগশেষ {r2}।', ans: '{n} ÷ 9 = {q}, ভাগশেষ {r}' } },
  cuberoot: { icon: '🧊', name: 'ঘনমূল', sample: '∛17576 = 26', tagline: 'শেষ অঙ্ক থেকে একক, সামনের অংশ থেকে দশক।',
    how: ['শেষের তিনটি অঙ্ক আলাদা করুন।', 'ঘনের শেষ অঙ্ক মূলের একক অঙ্ক বলে দেয় (2↔8, 3↔7, বাকিগুলো একই)।', 'সামনের অংশে ধরে এমন সবচেয়ে বড় ঘন খুঁজুন: সেটিই দশকের অঙ্ক।'],
    why: '0–9-এর ঘনগুলো সব আলাদা অঙ্কে শেষ হয়, আর দুই অঙ্কের মূলের ঘন (10t)³ আর (10t + 10)³-এর মাঝে থাকে।',
    q: '{n}-এর ঘনমূল কত?',
    steps: { split: '{n} → সামনে {left}, পেছনে {right}।', units: 'শেষ অঙ্ক {last}: {u}³ = {u3}-এর শেষে {last}, তাই একক = {u}।', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, তাই দশক = {t}।', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'শতাংশের কৌশল', sample: '240-এর 15% = 36', tagline: 'যেকোনো শতাংশ 10%, 5% আর অর্ধেক দিয়ে বানান।',
    how: ['10%: 10 দিয়ে ভাগ করুন।', '5%: 10%-এর অর্ধেক।', '50% হল অর্ধেক, 25% অর্ধেকের অর্ধেক, 75% = 50% + 25%।', 'টুকরোগুলো যোগ করুন: 15% = 10% + 5%, 30% = 3 × 10%।'],
    why: 'শতাংশ মানে “100-এর মধ্যে”। শতাংশকে সহজ টুকরোয় ভাঙলে বড় গুণ করতে হয় না।',
    q: '{n}-এর {p}% কত?',
    steps: { half: '{n}-এর 50% = {half}।', quarter: '25% = {half}-এর অর্ধেক = {quarter}।', sum: 'যোগ করুন: {parts} = {ans}।', ten: '{n}-এর 10% = {ten}।', minus: '90% = {n} − {ten} = {ans}।', tens: '{p}% = {tens} × {ten} = {val}।', five: '5% = {ten}-এর অর্ধেক = {five}।', ans: '{n}-এর {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'অঙ্ক-যোগ দিয়ে যাচাই', sample: '47 × 23 = 1081 ✓', tagline: 'যেকোনো গুণ কয়েক সেকেন্ডে যাচাই করুন।',
    how: ['একটি অঙ্ক না থাকা পর্যন্ত সংখ্যার অঙ্কগুলো বারবার যোগ করুন (যাচাইয়ে 9 মানে 0)।', 'দুটি সংখ্যার অঙ্ক-যোগ গুণ করুন; আবার এক অঙ্কে নামান।', 'উত্তরের অঙ্ক-যোগের সঙ্গে মেলান। না মিললে উত্তর ভুল।'],
    why: 'একটি সংখ্যা আর তার অঙ্ক-যোগ 9 দিয়ে ভাগ করলে একই ভাগশেষ থাকে, আর ভাগশেষ গুণ করা যায়।',
    q: '{n}-এর অঙ্ক-যোগ কত?', q_check: '{a} × {b} = {c} কি ঠিক?',
    steps: { start: '{n}-এর অঙ্ক-যোগ বের করুন।', sum: '{label}: {list} = {s}।', single: '{n} আগে থেকেই এক অঙ্কের।', root: '{n}-এর অঙ্ক-যোগ = {r}।', check: '{a} × {b} = {c} যাচাই করুন।', roots: 'অঙ্ক-যোগ: {a} → {ra}, {b} → {rb}।', mulroot: '{ra} × {rb} = {prod} → {rm}।', croot: '{c}-এর অঙ্ক-যোগ → {rc}।', match: '{rm} = {rc}: উত্তর সম্ভবত ঠিক ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ভুল ✗' } }
} };
window.APP_CONTENT.gu = { tricks: {
  mul11: { icon: '✖️', name: '11 વડે ગુણાકાર', sample: '52 × 11 = 572', tagline: 'બાજુ-બાજુના અંક ઉમેરો અને વચ્ચે મૂકો.',
    how: ['છેલ્લો અંક જેમ છે તેમ લખો.', 'જમણેથી ડાબે જતાં બાજુ-બાજુના અંકોનો સરવાળો કરો; સરવાળો 10 કે વધુ હોય તો વદ્દી લઈ જાઓ.', 'સૌથી આગળ પહેલો અંક (અને વદ્દી) લખો.'],
    why: '11 = 10 + 1, એટલે n × 11 = n × 10 + n. સંખ્યાને એક સ્થાન ખસેડીને પોતામાં ઉમેરવી એટલે બાજુના અંક ઉમેરવા.',
    q: '{a} × {b} કેટલા?',
    steps: { last: '{n} નો છેલ્લો અંક {d}. {d} લખો.', pair: 'બાજુના અંક {x} + {y} = {s}. {w} લખો.', pair_in: 'બાજુના અંક {x} + {y} + વદ્દી {c} = {s}. {w} લખો.', pair_out: 'બાજુના અંક {x} + {y} = {s}. {w} લખો, વદ્દી {carry}.', pair_in_out: 'બાજુના અંક {x} + {y} + વદ્દી {c} = {s}. {w} લખો, વદ્દી {carry}.', first: 'પહેલો અંક {f} સૌથી આગળ લખો.', first_c: 'પહેલો અંક {f} + વદ્દી {c} = {s} સૌથી આગળ લખો.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 વડે ગુણાકાર', sample: '47 × 99 = 4653', tagline: 'એક ઓછો, પછી પૂરક.',
    how: ['સંખ્યામાં જેટલા 9 એટલા જ અંક હોય તો: ડાબો ભાગ = સંખ્યા − 1.', 'જમણો ભાગ = સંખ્યાને 10, 100 કે 1000 થવા માટે જોઈએ તેટલા.', 'નહીં તો: 10, 100 કે 1000 વડે ગુણો અને સંખ્યા બાદ કરો.'],
    why: '99 = 100 − 1, એટલે n × 99 = n × 100 − n. તેને વહેંચતાં (n − 1) પછી (100 − n) આવે.',
    q: '{a} × {b} કેટલા?',
    steps: { c_left: '{n} × {nines}: ડાબો ભાગ = {n} − 1 = {left}.', c_right: 'જમણો ભાગ = {base} − {n} = {right}.', c_join: '{left} અને {right} જોડીને લખો → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 વડે ગુણાકાર', sample: '48 × 5 = 240', tagline: '10 કે 100 વડે ગુણો, પછી અડધું કે ચોથા ભાગનું.',
    how: ['× 5: 10 વડે ગુણો, પછી 2 વડે ભાગો.', '× 50: 100 વડે ગુણો, પછી 2 વડે ભાગો.', '× 25: 100 વડે ગુણો, પછી 4 વડે ભાગો.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 અને 25 = 100 ÷ 4. શૂન્ય ઉમેરી અડધું કરવું લાંબા ગુણાકાર કરતાં સહેલું.',
    q: '{a} × {b} કેટલા?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 થી પૂરી થતી સંખ્યાના વર્ગ', sample: '65² = 4225', tagline: 'આગળના ભાગને તેના પછીના વડે ગુણો, પછી 25.',
    how: ['છેલ્લો 5 કાઢી નાખો; બાકી રહે તેને a કહો.', 'a ને પછીની સંખ્યા a + 1 વડે ગુણો.', 'તેના પછી 25 લખો.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. એટલે જવાબ હંમેશાં a × (a + 1) અને પછી 25.',
    q: '{n}² કેટલા?',
    steps: { split: '{n}: 5 કાઢો, બાકી ભાગ = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} પછી 25 લખો → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'આધારની નજીક (નિખિલમ્)', sample: '97 × 96 = 9312', tagline: 'બધા 9 માંથી, છેલ્લો 10 માંથી: દરેક સંખ્યા 100 થી કેટલી દૂર છે તે જુઓ.',
    how: ['બંને સંખ્યાની નજીકનો આધાર (10, 100, 1000) પસંદ કરો.', 'દરેક સંખ્યાનો આધારથી તફાવત કાઢો.', 'ડાબો ભાગ: એક સંખ્યા + બીજીનો તફાવત.', 'જમણો ભાગ: બંને તફાવતનો ગુણાકાર (આધારમાં જેટલા શૂન્ય એટલા અંક).'],
    why: '(આધાર + x)(આધાર + y) = આધાર × (આધાર + x + y) + x × y. તફાવત નાના હોય તો ગુણાકાર બહુ નાનો થઈ જાય.',
    q: '{a} × {b} કેટલા?',
    steps: { base: '{a} અને {b} માટે આધાર {base}.', dev: 'તફાવત: {base} થી {a} નો {da}, {b} નો {db}.', cross: 'ડાબો ભાગ: {a} {db} = {left}.', prod: 'જમણો ભાગ: ({da}) × ({db}) = {prod}, {k} અંકમાં લખો.', borrow: 'જમણો ભાગ {prod} ઋણ છે: ડાબેથી {c} ઉછીના લો. ડાબો {left} → {l2}, જમણો {prod} + {cb} = {p2}.', carry: '{prod} આધાર {base} માટે મોટો છે: વદ્દી {c}, ડાબો {left} → {l3}, જમણો {p3}.', join: '{left} અને {right} જોડીને લખો → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ઊર્ધ્વ-તિર્યક (ઊભું અને ત્રાંસું)', sample: '23 × 14 = 322', tagline: 'કોઈ પણ ગુણાકાર, એક-એક કૉલમ કરીને.',
    how: ['જમણેથી એક-એક કૉલમ કરો.', 'દરેક કૉલમમાં મળતા અંકોના ગુણાકાર (ઊભા અને ત્રાંસા) ઉમેરો.', 'એકમનો અંક લખો અને બાકીની વદ્દી આગળના કૉલમમાં લઈ જાઓ.'],
    why: 'દરેક કૉલમમાં એવી બધી અંક-જોડી આવે જેની સ્થાનકિંમત 10 ની એક જ ઘાત આપે, બરાબર લાંબા ગુણાકાર જેવું, પણ એક લીટીમાં.',
    q: '{a} × {b} કેટલા?',
    steps: { setup: '{a} ની નીચે {b} લખો.', col: 'કૉલમ {i}: {terms} = {sum}. {w} લખો.', col_in: 'કૉલમ {i}: {terms} = {sum}, + વદ્દી {c} = {total}. {w} લખો.', col_out: 'કૉલમ {i}: {terms} = {sum}. {w} લખો, વદ્દી {carry}.', col_in_out: 'કૉલમ {i}: {terms} = {sum}, + વદ્દી {c} = {total}. {w} લખો, વદ્દી {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 વડે ભાગાકાર', sample: '2301 ÷ 9 = 255 (6)', tagline: 'અંકોના ચાલુ સરવાળાથી ભાગફળ મળે.',
    how: ['પહેલો અંક એમ જ લખો.', 'આગળના સરવાળામાં પછીનો અંક ઉમેરતા જાઓ (છેલ્લો અંક છોડી દો).', 'આ સરવાળા ભાગફળ બનાવે; બધા અંકોનો સરવાળો શેષ છે.', 'શેષ 9 કે વધુ હોય તો 9 બાદ કરો અને ભાગફળમાં 1 ઉમેરો.'],
    why: '10 = 9 + 1, એટલે 9 વડે ભાગતાં દરેક સ્થાનકિંમત 1 શેષ રાખે. તેથી અંકોનો સરવાળો કામ કરે છે.',
    q: '{n} ÷ 9 કેટલા? (ભાગફળ અને શેષ)',
    steps: { first: '{n} નો પહેલો અંક: {d}.', add: '{prev} + {d} = {s}.', quot: 'સરવાળા {list} → ભાગફળ {q}.', rem: 'શેષ = {list} = {r}.', adjust: 'શેષ {r} ≥ 9: ભાગફળ {q} → {q2}, શેષ {r2}.', ans: '{n} ÷ 9 = {q}, શેષ {r}' } },
  cuberoot: { icon: '🧊', name: 'ઘનમૂળ', sample: '∛17576 = 26', tagline: 'છેલ્લા અંકથી એકમ, આગળના ભાગથી દશક.',
    how: ['છેલ્લા ત્રણ અંક અલગ કરો.', 'ઘનનો છેલ્લો અંક મૂળનો એકમ અંક કહે છે (2↔8, 3↔7, બાકી એ જ).', 'આગળના ભાગમાં સમાય તેવો સૌથી મોટો ઘન શોધો: એ જ દશકનો અંક.'],
    why: '0–9 ના ઘન બધા જુદા અંકથી પૂરા થાય છે, અને બે અંકના મૂળનો ઘન (10t)³ અને (10t + 10)³ ની વચ્ચે હોય છે.',
    q: '{n} નું ઘનમૂળ કેટલું?',
    steps: { split: '{n} → આગળ {left}, પાછળ {right}.', units: 'છેલ્લો અંક {last}: {u}³ = {u3} નો છેલ્લો અંક {last}, એટલે એકમ = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, એટલે દશક = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'ટકાવારીની યુક્તિઓ', sample: '240 ના 15% = 36', tagline: 'કોઈ પણ ટકા 10%, 5% અને અડધામાંથી બનાવો.',
    how: ['10%: 10 વડે ભાગો.', '5%: 10% નું અડધું.', '50% એટલે અડધું, 25% અડધાનું અડધું, 75% = 50% + 25%.', 'ટુકડા ઉમેરો: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'ટકા એટલે “100 માંથી”. ટકાને સહેલા ટુકડામાં વહેંચવાથી મોટો ગુણાકાર ટળે.',
    q: '{n} ના {p}% કેટલા?',
    steps: { half: '{n} ના 50% = {half}.', quarter: '25% = {half} નું અડધું = {quarter}.', sum: 'ઉમેરો: {parts} = {ans}.', ten: '{n} ના 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten} નું અડધું = {five}.', ans: '{n} ના {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'અંક-સરવાળાથી ચકાસણી', sample: '47 × 23 = 1081 ✓', tagline: 'કોઈ પણ ગુણાકાર થોડી સેકંડમાં ચકાસો.',
    how: ['એક અંક બાકી રહે ત્યાં સુધી સંખ્યાના અંક વારંવાર ઉમેરો (ચકાસણીમાં 9 એટલે 0).', 'બંને સંખ્યાના અંક-સરવાળાનો ગુણાકાર કરો; ફરી એક અંક સુધી લાવો.', 'જવાબના અંક-સરવાળા સાથે સરખાવો. જુદું આવે તો જવાબ ખોટો.'],
    why: 'સંખ્યા અને તેનો અંક-સરવાળો 9 વડે ભાગતાં સરખી શેષ રાખે છે, અને શેષનો ગુણાકાર થાય છે.',
    q: '{n} નો અંક-સરવાળો કેટલો?', q_check: 'શું {a} × {b} = {c} સાચું છે?',
    steps: { start: '{n} નો અંક-સરવાળો કાઢો.', sum: '{label}: {list} = {s}.', single: '{n} પહેલેથી એક અંકનો છે.', root: '{n} નો અંક-સરવાળો = {r}.', check: '{a} × {b} = {c} ચકાસો.', roots: 'અંક-સરવાળા: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} નો અંક-સરવાળો → {rc}.', match: '{rm} = {rc}: જવાબ કદાચ સાચો ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ખોટું ✗' } }
} };
