/* Localized trick content for Vedic Maths. Same shape in all 12 languages.
   Step templates use {vars}; numbers are wrapped in LTR isolates by app.js. */
window.APP_CONTENT = {};
window.APP_CONTENT.en = { tricks: {
  mul11: { icon: '✖️', name: 'Multiply by 11', sample: '52 × 11 = 572', tagline: 'Add neighbouring digits and slip them in between.',
    how: ['Write the last digit as it is.', 'Add each pair of neighbouring digits, moving right to left; carry if the sum is 10 or more.', 'Write the first digit (plus any carry) at the front.'],
    why: '11 = 10 + 1, so n × 11 = n × 10 + n. Adding the number to itself shifted one place is the same as adding neighbouring digits.',
    q: 'What is {a} × {b}?',
    steps: { last: 'Last digit of {n} is {d}. Write {d}.', pair: 'Add neighbours {x} + {y} = {s}. Write {w}.', pair_in: 'Add neighbours {x} + {y} + carry {c} = {s}. Write {w}.', pair_out: 'Add neighbours {x} + {y} = {s}. Write {w}, carry {carry}.', pair_in_out: 'Add neighbours {x} + {y} + carry {c} = {s}. Write {w}, carry {carry}.', first: 'First digit {f} goes in front.', first_c: 'First digit {f} + carry {c} = {s} goes in front.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: 'Multiply by 9, 99, 999', sample: '47 × 99 = 4653', tagline: 'One less, then the complement.',
    how: ['If the number has as many digits as the nines: left part = number − 1.', 'Right part = what the number needs to reach 10, 100 or 1000.', 'Otherwise: multiply by 10, 100 or 1000 and subtract the number.'],
    why: '99 = 100 − 1, so n × 99 = n × 100 − n. Splitting this gives (n − 1) followed by (100 − n).',
    q: 'What is {a} × {b}?',
    steps: { c_left: '{n} × {nines}: left part = {n} − 1 = {left}.', c_right: 'Right part = {base} − {n} = {right}.', c_join: 'Join {left} and {right} → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: 'Multiply by 5, 25, 50', sample: '48 × 5 = 240', tagline: 'Multiply by 10 or 100, then halve or quarter.',
    how: ['× 5: multiply by 10, then divide by 2.', '× 50: multiply by 100, then divide by 2.', '× 25: multiply by 100, then divide by 4.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 and 25 = 100 ÷ 4. Adding zeros and halving is easier than long multiplication.',
    q: 'What is {a} × {b}?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: 'Squares ending in 5', sample: '65² = 4225', tagline: 'One more than the one before, then 25.',
    how: ['Remove the last 5; call what is left a.', 'Multiply a by the next number, a + 1.', 'Write 25 after it.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. So the answer is always a × (a + 1) followed by 25.',
    q: 'What is {n}²?',
    steps: { split: '{n}: remove the 5, left part = {a}.', mul: '{a} × {a1} = {prod}.', join: 'Write 25 after {prod} → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'Near a base (Nikhilam)', sample: '97 × 96 = 9312', tagline: 'All from 9, the last from 10: use how far each number is from 100.',
    how: ['Choose the base (10, 100, 1000) close to both numbers.', 'Find each number’s difference from the base.', 'Left part: one number plus the other’s difference.', 'Right part: multiply the two differences (as many digits as zeros in the base).'],
    why: '(base + x)(base + y) = base × (base + x + y) + x × y. Small differences make the multiplication tiny.',
    q: 'What is {a} × {b}?',
    steps: { base: 'Base for {a} and {b} is {base}.', dev: 'Differences: {a} is {da}, {b} is {db} from {base}.', cross: 'Left part: {a} {db} = {left}.', prod: 'Right part: ({da}) × ({db}) = {prod}, written with {k} digits.', borrow: 'Right part {prod} is negative: borrow {c} from the left. Left {left} → {l2}, right {prod} + {cb} = {p2}.', carry: '{prod} is too big for the base {base}: carry {c}, left {left} → {l3}, right {p3}.', join: 'Join {left} and {right} → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'Vertically and crosswise', sample: '23 × 14 = 322', tagline: 'Any multiplication, one column at a time.',
    how: ['Work column by column from the right.', 'In each column, add the products of digits that meet (vertical and cross).', 'Write the units digit and carry the rest to the next column.'],
    why: 'Each column collects all digit pairs whose place values give the same power of 10, exactly like long multiplication, but done in one line.',
    q: 'What is {a} × {b}?',
    steps: { setup: 'Write {a} above {b}.', col: 'Column {i}: {terms} = {sum}. Write {w}.', col_in: 'Column {i}: {terms} = {sum}, + carry {c} = {total}. Write {w}.', col_out: 'Column {i}: {terms} = {sum}. Write {w}, carry {carry}.', col_in_out: 'Column {i}: {terms} = {sum}, + carry {c} = {total}. Write {w}, carry {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: 'Divide by 9', sample: '2301 ÷ 9 = 255 r 6', tagline: 'Running digit sums give the quotient.',
    how: ['Copy the first digit.', 'Keep adding the next digit to the last sum (leave out the final digit).', 'These sums form the quotient; the sum of all digits is the remainder.', 'If the remainder is 9 or more, take away 9 and add 1 to the quotient.'],
    why: '10 = 9 + 1, so every place value leaves remainder 1 when divided by 9. That is why the digit sums work.',
    q: 'What is {n} ÷ 9? (quotient and remainder)',
    steps: { first: 'First digit of {n}: {d}.', add: '{prev} + {d} = {s}.', quot: 'Sums {list} → quotient {q}.', rem: 'Remainder = {list} = {r}.', adjust: 'Remainder {r} ≥ 9: quotient {q} → {q2}, remainder {r2}.', ans: '{n} ÷ 9 = {q} remainder {r}' } },
  cuberoot: { icon: '🧊', name: 'Cube roots', sample: '∛17576 = 26', tagline: 'Last digit gives the units, the front gives the tens.',
    how: ['Split off the last three digits.', 'The last digit of the cube tells the units digit of the root (2↔8, 3↔7, others same).', 'For the front part, find the biggest cube that fits: that is the tens digit.'],
    why: 'Cubes of 0–9 all end in different digits, and a two-digit root has a cube between (10t)³ and (10t + 10)³.',
    q: 'What is the cube root of {n}?',
    steps: { split: '{n} → front {left}, back {right}.', units: 'Last digit {last}: {u}³ = {u3} ends in {last}, so units = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, so tens = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'Percentage tricks', sample: '15% of 240 = 36', tagline: 'Build any percent from 10%, 5% and halves.',
    how: ['10%: divide by 10.', '5%: half of 10%.', '50% is half, 25% is half of half, 75% = 50% + 25%.', 'Add the pieces: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'Percent means “out of 100”. Splitting a percent into easy pieces avoids big multiplication.',
    q: 'What is {p}% of {n}?',
    steps: { half: '50% of {n} = {half}.', quarter: '25% = half of {half} = {quarter}.', sum: 'Add: {parts} = {ans}.', ten: '10% of {n} = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = half of {ten} = {five}.', ans: '{p}% of {n} = {ans}' } },
  digitsum: { icon: '✅', name: 'Digit-sum check', sample: '47 × 23 = 1081 ✓', tagline: 'Check any multiplication in seconds.',
    how: ['Add the digits of a number again and again until one digit is left (9 counts as 0 for checking).', 'Find the digit sums of both numbers and multiply them; reduce again.', 'Compare with the digit sum of the answer. Different means the answer is wrong.'],
    why: 'A number and its digit sum leave the same remainder when divided by 9, and remainders multiply.',
    q: 'What is the digit sum of {n}?', q_check: 'Is {a} × {b} = {c} correct?',
    steps: { start: 'Find the digit sum of {n}.', sum: '{label}: {list} = {s}.', single: '{n} is already one digit.', root: 'Digit sum of {n} = {r}.', check: 'Check {a} × {b} = {c}.', roots: 'Digit sums: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: 'Digit sum of {c} → {rc}.', match: '{rm} = {rc}: the answer is probably right ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} is wrong ✗' } }
} };
window.APP_CONTENT.hi = { tricks: {
  mul11: { icon: '✖️', name: '11 से गुणा', sample: '52 × 11 = 572', tagline: 'पास-पास के अंक जोड़ें और बीच में रख दें।',
    how: ['आख़िरी अंक जैसा है वैसा लिखें।', 'दाएँ से बाएँ चलते हुए पास-पास के दो-दो अंक जोड़ें; योग 10 या ज़्यादा हो तो हासिल ले जाएँ।', 'सबसे आगे पहला अंक (और हासिल) लिखें।'],
    why: '11 = 10 + 1, इसलिए n × 11 = n × 10 + n। संख्या को एक जगह खिसकाकर खुद में जोड़ना, पास-पास के अंक जोड़ने जैसा ही है।',
    q: '{a} × {b} कितना है?',
    steps: { last: '{n} का आख़िरी अंक {d} है। {d} लिखें।', pair: 'पास के अंक {x} + {y} = {s}। {w} लिखें।', pair_in: 'पास के अंक {x} + {y} + हासिल {c} = {s}। {w} लिखें।', pair_out: 'पास के अंक {x} + {y} = {s}। {w} लिखें, हासिल {carry}।', pair_in_out: 'पास के अंक {x} + {y} + हासिल {c} = {s}। {w} लिखें, हासिल {carry}।', first: 'पहला अंक {f} सबसे आगे लिखें।', first_c: 'पहला अंक {f} + हासिल {c} = {s} सबसे आगे लिखें।', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 से गुणा', sample: '47 × 99 = 4653', tagline: 'एक कम, फिर पूरक।',
    how: ['अगर संख्या में उतने ही अंक हों जितने 9 हैं: बायाँ भाग = संख्या − 1।', 'दायाँ भाग = संख्या को 10, 100 या 1000 तक पहुँचने के लिए जितना चाहिए।', 'वरना: 10, 100 या 1000 से गुणा करें और संख्या घटा दें।'],
    why: '99 = 100 − 1, इसलिए n × 99 = n × 100 − n। इसे बाँटने पर (n − 1) के बाद (100 − n) आता है।',
    q: '{a} × {b} कितना है?',
    steps: { c_left: '{n} × {nines}: बायाँ भाग = {n} − 1 = {left}।', c_right: 'दायाँ भाग = {base} − {n} = {right}।', c_join: '{left} और {right} जोड़कर लिखें → {ans}।', n_is: '{nines} = {base} − 1।', n_times: '{n} × {base} = {m}।', n_minus: '{m} − {n} = {ans}।', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 से गुणा', sample: '48 × 5 = 240', tagline: '10 या 100 से गुणा करें, फिर आधा या चौथाई।',
    how: ['× 5: 10 से गुणा करें, फिर 2 से भाग दें।', '× 50: 100 से गुणा करें, फिर 2 से भाग दें।', '× 25: 100 से गुणा करें, फिर 4 से भाग दें।'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 और 25 = 100 ÷ 4। शून्य लगाकर आधा करना लंबे गुणा से आसान है।',
    q: '{a} × {b} कितना है?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}।', f_times: '{n} × {pw} = {t}।', f_div: '{t} ÷ {dv} = {ans}।', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 पर ख़त्म होने वाले वर्ग', sample: '65² = 4225', tagline: 'पहले वाले को उससे एक अधिक से गुणा, फिर 25।',
    how: ['आख़िरी 5 हटा दें; जो बचा उसे a कहें।', 'a को अगली संख्या a + 1 से गुणा करें।', 'उसके बाद 25 लिख दें।'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25। इसलिए उत्तर हमेशा a × (a + 1) और उसके बाद 25 होता है।',
    q: '{n}² कितना है?',
    steps: { split: '{n}: 5 हटाएँ, बचा भाग = {a}।', mul: '{a} × {a1} = {prod}।', join: '{prod} के बाद 25 लिखें → {ans}।', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'आधार के पास (निखिलम्)', sample: '97 × 96 = 9312', tagline: 'निखिलं नवतश्चरमं दशतः: देखें हर संख्या 100 से कितनी दूर है।',
    how: ['दोनों संख्याओं के पास का आधार (10, 100, 1000) चुनें।', 'हर संख्या का आधार से अंतर निकालें।', 'बायाँ भाग: एक संख्या + दूसरी का अंतर।', 'दायाँ भाग: दोनों अंतरों का गुणा (आधार में जितने शून्य, उतने अंक)।'],
    why: '(आधार + x)(आधार + y) = आधार × (आधार + x + y) + x × y। अंतर छोटे हों तो गुणा बहुत छोटा हो जाता है।',
    q: '{a} × {b} कितना है?',
    steps: { base: '{a} और {b} का आधार {base} है।', dev: 'अंतर: {base} से {a} का {da}, {b} का {db}।', cross: 'बायाँ भाग: {a} {db} = {left}।', prod: 'दायाँ भाग: ({da}) × ({db}) = {prod}, {k} अंकों में लिखें।', borrow: 'दायाँ भाग {prod} ऋणात्मक है: बाएँ से {c} उधार लें। बायाँ {left} → {l2}, दायाँ {prod} + {cb} = {p2}।', carry: '{prod} आधार {base} के लिए बड़ा है: हासिल {c}, बायाँ {left} → {l3}, दायाँ {p3}।', join: '{left} और {right} जोड़कर लिखें → {ans}।', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ऊर्ध्व-तिर्यक (सीधा और तिरछा)', sample: '23 × 14 = 322', tagline: 'कोई भी गुणा, एक-एक कॉलम करके।',
    how: ['दाएँ से एक-एक कॉलम करके चलें।', 'हर कॉलम में मिलने वाले अंकों के गुणनफल (सीधे और तिरछे) जोड़ें।', 'इकाई का अंक लिखें और बाक़ी अगले कॉलम में ले जाएँ।'],
    why: 'हर कॉलम में वे सारे अंक-जोड़े आते हैं जिनका स्थानीय मान 10 की एक ही घात देता है, बिल्कुल लंबे गुणा जैसा, बस एक लाइन में।',
    q: '{a} × {b} कितना है?',
    steps: { setup: '{a} के नीचे {b} लिखें।', col: 'कॉलम {i}: {terms} = {sum}। {w} लिखें।', col_in: 'कॉलम {i}: {terms} = {sum}, + हासिल {c} = {total}। {w} लिखें।', col_out: 'कॉलम {i}: {terms} = {sum}। {w} लिखें, हासिल {carry}।', col_in_out: 'कॉलम {i}: {terms} = {sum}, + हासिल {c} = {total}। {w} लिखें, हासिल {carry}।', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 से भाग', sample: '2301 ÷ 9 = 255 (6)', tagline: 'अंकों के चलते योग से भागफल मिलता है।',
    how: ['पहला अंक वैसा ही लिखें।', 'पिछले योग में अगला अंक जोड़ते जाएँ (आख़िरी अंक छोड़ दें)।', 'ये योग भागफल बनाते हैं; सभी अंकों का योग शेषफल है।', 'शेषफल 9 या ज़्यादा हो तो 9 घटाएँ और भागफल में 1 जोड़ें।'],
    why: '10 = 9 + 1, इसलिए 9 से भाग देने पर हर स्थानीय मान 1 शेष छोड़ता है। इसीलिए अंकों का योग काम करता है।',
    q: '{n} ÷ 9 कितना है? (भागफल और शेषफल)',
    steps: { first: '{n} का पहला अंक: {d}।', add: '{prev} + {d} = {s}।', quot: 'योग {list} → भागफल {q}।', rem: 'शेषफल = {list} = {r}।', adjust: 'शेषफल {r} ≥ 9: भागफल {q} → {q2}, शेषफल {r2}।', ans: '{n} ÷ 9 = {q}, शेषफल {r}' } },
  cuberoot: { icon: '🧊', name: 'घनमूल', sample: '∛17576 = 26', tagline: 'आख़िरी अंक से इकाई, आगे के भाग से दहाई।',
    how: ['आख़िरी तीन अंक अलग करें।', 'घन का आख़िरी अंक मूल का इकाई अंक बताता है (2↔8, 3↔7, बाक़ी वही)।', 'आगे वाले भाग में समाने वाला सबसे बड़ा घन ढूँढें: वही दहाई का अंक है।'],
    why: '0–9 के घन सब अलग-अलग अंकों पर ख़त्म होते हैं, और दो अंकों के मूल का घन (10t)³ और (10t + 10)³ के बीच होता है।',
    q: '{n} का घनमूल कितना है?',
    steps: { split: '{n} → आगे {left}, पीछे {right}।', units: 'आख़िरी अंक {last}: {u}³ = {u3} का आख़िरी अंक {last} है, इसलिए इकाई = {u}।', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, इसलिए दहाई = {t}।', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'प्रतिशत की तरकीबें', sample: '240 का 15% = 36', tagline: 'हर प्रतिशत 10%, 5% और आधे से बनाएँ।',
    how: ['10%: 10 से भाग दें।', '5%: 10% का आधा।', '50% आधा है, 25% आधे का आधा, 75% = 50% + 25%।', 'टुकड़े जोड़ें: 15% = 10% + 5%, 30% = 3 × 10%।'],
    why: 'प्रतिशत यानी “100 में से”। प्रतिशत को आसान टुकड़ों में बाँटने से बड़ा गुणा नहीं करना पड़ता।',
    q: '{n} का {p}% कितना है?',
    steps: { half: '{n} का 50% = {half}।', quarter: '25% = {half} का आधा = {quarter}।', sum: 'जोड़ें: {parts} = {ans}।', ten: '{n} का 10% = {ten}।', minus: '90% = {n} − {ten} = {ans}।', tens: '{p}% = {tens} × {ten} = {val}।', five: '5% = {ten} का आधा = {five}।', ans: '{n} का {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'अंक-योग से जाँच', sample: '47 × 23 = 1081 ✓', tagline: 'कोई भी गुणा कुछ ही सेकंड में जाँचें।',
    how: ['किसी संख्या के अंक बार-बार जोड़ें जब तक एक अंक न बचे (जाँच में 9 को 0 जैसा मानें)।', 'दोनों संख्याओं के अंक-योग का गुणा करें; फिर से एक अंक तक घटाएँ।', 'उत्तर के अंक-योग से मिलाएँ। अलग हो तो उत्तर ग़लत है।'],
    why: 'कोई संख्या और उसका अंक-योग 9 से भाग देने पर एक जैसा शेष छोड़ते हैं, और शेषफल आपस में गुणा होते हैं।',
    q: '{n} का अंक-योग कितना है?', q_check: 'क्या {a} × {b} = {c} सही है?',
    steps: { start: '{n} का अंक-योग निकालें।', sum: '{label}: {list} = {s}।', single: '{n} पहले से एक अंक है।', root: '{n} का अंक-योग = {r}।', check: '{a} × {b} = {c} जाँचें।', roots: 'अंक-योग: {a} → {ra}, {b} → {rb}।', mulroot: '{ra} × {rb} = {prod} → {rm}।', croot: '{c} का अंक-योग → {rc}।', match: '{rm} = {rc}: उत्तर शायद सही है ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ग़लत है ✗' } }
} };
window.APP_CONTENT.mr = { tricks: {
  mul11: { icon: '✖️', name: '11 ने गुणाकार', sample: '52 × 11 = 572', tagline: 'शेजारचे अंक मिळवा आणि मधे ठेवा.',
    how: ['शेवटचा अंक जसाच्या तसा लिहा.', 'उजवीकडून डावीकडे जाताना शेजारच्या अंकांची बेरीज करा; बेरीज 10 किंवा जास्त असेल तर हातचा न्या.', 'सर्वात पुढे पहिला अंक (आणि हातचा) लिहा.'],
    why: '11 = 10 + 1, म्हणून n × 11 = n × 10 + n. संख्या एका जागी सरकवून तिच्यातच मिळवणे म्हणजे शेजारचे अंक मिळवणेच.',
    q: '{a} × {b} किती?',
    steps: { last: '{n} चा शेवटचा अंक {d}. {d} लिहा.', pair: 'शेजारचे अंक {x} + {y} = {s}. {w} लिहा.', pair_in: 'शेजारचे अंक {x} + {y} + हातचा {c} = {s}. {w} लिहा.', pair_out: 'शेजारचे अंक {x} + {y} = {s}. {w} लिहा, हातचा {carry}.', pair_in_out: 'शेजारचे अंक {x} + {y} + हातचा {c} = {s}. {w} लिहा, हातचा {carry}.', first: 'पहिला अंक {f} सर्वात पुढे लिहा.', first_c: 'पहिला अंक {f} + हातचा {c} = {s} सर्वात पुढे लिहा.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 ने गुणाकार', sample: '47 × 99 = 4653', tagline: 'एक कमी, मग पूरक.',
    how: ['संख्येत जितके 9 तितकेच अंक असतील तर: डावा भाग = संख्या − 1.', 'उजवा भाग = संख्येला 10, 100 किंवा 1000 होण्यासाठी लागणारे.', 'नाहीतर: 10, 100 किंवा 1000 ने गुणा आणि संख्या वजा करा.'],
    why: '99 = 100 − 1, म्हणून n × 99 = n × 100 − n. हे विभागले की (n − 1) नंतर (100 − n) येते.',
    q: '{a} × {b} किती?',
    steps: { c_left: '{n} × {nines}: डावा भाग = {n} − 1 = {left}.', c_right: 'उजवा भाग = {base} − {n} = {right}.', c_join: '{left} आणि {right} जोडून लिहा → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 ने गुणाकार', sample: '48 × 5 = 240', tagline: '10 किंवा 100 ने गुणा, मग अर्धा किंवा पाव.',
    how: ['× 5: 10 ने गुणा, मग 2 ने भागा.', '× 50: 100 ने गुणा, मग 2 ने भागा.', '× 25: 100 ने गुणा, मग 4 ने भागा.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 आणि 25 = 100 ÷ 4. शून्य जोडून अर्धे करणे लांब गुणाकारापेक्षा सोपे.',
    q: '{a} × {b} किती?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 ने संपणाऱ्या संख्यांचे वर्ग', sample: '65² = 4225', tagline: 'आधीच्याला पुढच्याने गुणा, मग 25.',
    how: ['शेवटचा 5 काढा; उरलेल्याला a म्हणा.', 'a ला पुढच्या संख्येने, a + 1 ने गुणा.', 'त्यानंतर 25 लिहा.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. म्हणून उत्तर नेहमी a × (a + 1) आणि नंतर 25.',
    q: '{n}² किती?',
    steps: { split: '{n}: 5 काढा, उरलेला भाग = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} नंतर 25 लिहा → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'पायाजवळच्या संख्या (निखिलम्)', sample: '97 × 96 = 9312', tagline: 'सगळे 9 मधून, शेवटचा 10 मधून: प्रत्येक संख्या 100 पासून किती दूर ते पाहा.',
    how: ['दोन्ही संख्यांच्या जवळचा पाया (10, 100, 1000) निवडा.', 'प्रत्येक संख्येचा पायापासूनचा फरक काढा.', 'डावा भाग: एक संख्या + दुसरीचा फरक.', 'उजवा भाग: दोन्ही फरकांचा गुणाकार (पायात जितके शून्य तितके अंक).'],
    why: '(पाया + x)(पाया + y) = पाया × (पाया + x + y) + x × y. फरक लहान असले की गुणाकार खूप छोटा होतो.',
    q: '{a} × {b} किती?',
    steps: { base: '{a} आणि {b} साठी पाया {base}.', dev: 'फरक: {base} पासून {a} चा {da}, {b} चा {db}.', cross: 'डावा भाग: {a} {db} = {left}.', prod: 'उजवा भाग: ({da}) × ({db}) = {prod}, {k} अंकांत लिहा.', borrow: 'उजवा भाग {prod} ऋण आहे: डावीकडून {c} उसने घ्या. डावा {left} → {l2}, उजवा {prod} + {cb} = {p2}.', carry: '{prod} हा पाया {base} साठी मोठा आहे: हातचा {c}, डावा {left} → {l3}, उजवा {p3}.', join: '{left} आणि {right} जोडून लिहा → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ऊर्ध्व-तिर्यक (उभे आणि तिरके)', sample: '23 × 14 = 322', tagline: 'कोणताही गुणाकार, एकेक स्तंभ करून.',
    how: ['उजवीकडून एकेक स्तंभ करा.', 'प्रत्येक स्तंभात भेटणाऱ्या अंकांचे गुणाकार (उभे आणि तिरके) मिळवा.', 'एकक अंक लिहा आणि बाकीचा हातचा पुढच्या स्तंभात न्या.'],
    why: 'प्रत्येक स्तंभात 10 च्या एकाच घाताचे सर्व अंक-जोडे येतात, अगदी लांब गुणाकारासारखे, पण एका ओळीत.',
    q: '{a} × {b} किती?',
    steps: { setup: '{a} च्या खाली {b} लिहा.', col: 'स्तंभ {i}: {terms} = {sum}. {w} लिहा.', col_in: 'स्तंभ {i}: {terms} = {sum}, + हातचा {c} = {total}. {w} लिहा.', col_out: 'स्तंभ {i}: {terms} = {sum}. {w} लिहा, हातचा {carry}.', col_in_out: 'स्तंभ {i}: {terms} = {sum}, + हातचा {c} = {total}. {w} लिहा, हातचा {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 ने भागाकार', sample: '2301 ÷ 9 = 255 (6)', tagline: 'अंकांच्या चालू बेरजेतून भागाकार मिळतो.',
    how: ['पहिला अंक तसाच लिहा.', 'मागच्या बेरजेत पुढचा अंक मिळवत जा (शेवटचा अंक सोडा).', 'या बेरजा भागाकार बनवतात; सर्व अंकांची बेरीज बाकी असते.', 'बाकी 9 किंवा जास्त असेल तर 9 वजा करा आणि भागाकारात 1 मिळवा.'],
    why: '10 = 9 + 1, म्हणून 9 ने भागल्यावर प्रत्येक स्थानिक किंमत 1 बाकी ठेवते. म्हणून अंकांची बेरीज चालते.',
    q: '{n} ÷ 9 किती? (भागाकार आणि बाकी)',
    steps: { first: '{n} चा पहिला अंक: {d}.', add: '{prev} + {d} = {s}.', quot: 'बेरजा {list} → भागाकार {q}.', rem: 'बाकी = {list} = {r}.', adjust: 'बाकी {r} ≥ 9: भागाकार {q} → {q2}, बाकी {r2}.', ans: '{n} ÷ 9 = {q}, बाकी {r}' } },
  cuberoot: { icon: '🧊', name: 'घनमूळ', sample: '∛17576 = 26', tagline: 'शेवटच्या अंकातून एकक, पुढच्या भागातून दशक.',
    how: ['शेवटचे तीन अंक वेगळे करा.', 'घनाचा शेवटचा अंक मुळाचा एकक अंक सांगतो (2↔8, 3↔7, बाकी तेच).', 'पुढच्या भागात बसणारा सर्वात मोठा घन शोधा: तोच दशक अंक.'],
    why: '0–9 चे घन सगळे वेगवेगळ्या अंकांनी संपतात, आणि दोन अंकी मुळाचा घन (10t)³ आणि (10t + 10)³ यांच्यामध्ये असतो.',
    q: '{n} चे घनमूळ किती?',
    steps: { split: '{n} → पुढे {left}, मागे {right}.', units: 'शेवटचा अंक {last}: {u}³ = {u3} चा शेवट {last}, म्हणून एकक = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, म्हणून दशक = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'टक्केवारीच्या युक्त्या', sample: '240 चे 15% = 36', tagline: 'कोणतीही टक्केवारी 10%, 5% आणि अर्ध्यातून बनवा.',
    how: ['10%: 10 ने भागा.', '5%: 10% चा अर्धा.', '50% म्हणजे अर्धा, 25% अर्ध्याचा अर्धा, 75% = 50% + 25%.', 'तुकडे मिळवा: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'टक्का म्हणजे “100 पैकी”. टक्केवारी सोप्या तुकड्यांत तोडली की मोठा गुणाकार टळतो.',
    q: '{n} चे {p}% किती?',
    steps: { half: '{n} चे 50% = {half}.', quarter: '25% = {half} चा अर्धा = {quarter}.', sum: 'मिळवा: {parts} = {ans}.', ten: '{n} चे 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten} चा अर्धा = {five}.', ans: '{n} चे {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'अंक-बेरजेने तपासणी', sample: '47 × 23 = 1081 ✓', tagline: 'कोणताही गुणाकार काही सेकंदांत तपासा.',
    how: ['एक अंक उरेपर्यंत संख्येचे अंक पुन्हा पुन्हा मिळवा (तपासताना 9 म्हणजे 0).', 'दोन्ही संख्यांच्या अंक-बेरजांचा गुणाकार करा; पुन्हा एक अंक करा.', 'उत्तराच्या अंक-बेरजेशी जुळवा. वेगळे आले तर उत्तर चुकीचे.'],
    why: 'संख्या आणि तिची अंक-बेरीज 9 ने भागल्यावर सारखीच बाकी ठेवतात, आणि बाक्यांचा गुणाकार होतो.',
    q: '{n} ची अंक-बेरीज किती?', q_check: '{a} × {b} = {c} बरोबर आहे का?',
    steps: { start: '{n} ची अंक-बेरीज काढा.', sum: '{label}: {list} = {s}.', single: '{n} आधीच एक अंकी आहे.', root: '{n} ची अंक-बेरीज = {r}.', check: '{a} × {b} = {c} तपासा.', roots: 'अंक-बेरजा: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} ची अंक-बेरीज → {rc}.', match: '{rm} = {rc}: उत्तर बहुधा बरोबर ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} चुकीचे ✗' } }
} };
window.APP_CONTENT.bn = { tricks: {
  mul11: { icon: '✖️', name: '11 দিয়ে গুণ', sample: '52 × 11 = 572', tagline: 'পাশাপাশি অঙ্ক যোগ করে মাঝখানে বসান।',
    how: ['শেষ অঙ্কটি যেমন আছে তেমন লিখুন।', 'ডান থেকে বাঁয়ে যেতে যেতে পাশাপাশি দুটি অঙ্ক যোগ করুন; যোগফল 10 বা বেশি হলে হাতে রাখুন।', 'একদম সামনে প্রথম অঙ্ক (আর হাতের সংখ্যা) লিখুন।'],
    why: '11 = 10 + 1, তাই n × 11 = n × 10 + n। সংখ্যাকে এক ঘর সরিয়ে নিজের সঙ্গে যোগ করা মানেই পাশাপাশি অঙ্ক যোগ করা।',
    q: '{a} × {b} কত?',
    steps: { last: '{n}-এর শেষ অঙ্ক {d}। {d} লিখুন।', pair: 'পাশের অঙ্ক {x} + {y} = {s}। {w} লিখুন।', pair_in: 'পাশের অঙ্ক {x} + {y} + হাতে {c} = {s}। {w} লিখুন।', pair_out: 'পাশের অঙ্ক {x} + {y} = {s}। {w} লিখুন, হাতে {carry}।', pair_in_out: 'পাশের অঙ্ক {x} + {y} + হাতে {c} = {s}। {w} লিখুন, হাতে {carry}।', first: 'প্রথম অঙ্ক {f} সামনে বসান।', first_c: 'প্রথম অঙ্ক {f} + হাতে {c} = {s} সামনে বসান।', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 দিয়ে গুণ', sample: '47 × 99 = 4653', tagline: 'এক কম, তারপর পূরক।',
    how: ['সংখ্যায় যতগুলো 9 ততগুলো অঙ্ক থাকলে: বাঁ অংশ = সংখ্যা − 1।', 'ডান অংশ = সংখ্যাটির 10, 100 বা 1000 হতে যত লাগে।', 'নইলে: 10, 100 বা 1000 দিয়ে গুণ করে সংখ্যাটি বিয়োগ করুন।'],
    why: '99 = 100 − 1, তাই n × 99 = n × 100 − n। এটি ভাঙলে (n − 1)-এর পরে (100 − n) আসে।',
    q: '{a} × {b} কত?',
    steps: { c_left: '{n} × {nines}: বাঁ অংশ = {n} − 1 = {left}।', c_right: 'ডান অংশ = {base} − {n} = {right}।', c_join: '{left} আর {right} পাশাপাশি লিখুন → {ans}।', n_is: '{nines} = {base} − 1।', n_times: '{n} × {base} = {m}।', n_minus: '{m} − {n} = {ans}।', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 দিয়ে গুণ', sample: '48 × 5 = 240', tagline: '10 বা 100 দিয়ে গুণ, তারপর অর্ধেক বা এক-চতুর্থাংশ।',
    how: ['× 5: 10 দিয়ে গুণ করে 2 দিয়ে ভাগ করুন।', '× 50: 100 দিয়ে গুণ করে 2 দিয়ে ভাগ করুন।', '× 25: 100 দিয়ে গুণ করে 4 দিয়ে ভাগ করুন।'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 আর 25 = 100 ÷ 4। শূন্য বসিয়ে অর্ধেক করা লম্বা গুণের চেয়ে সহজ।',
    q: '{a} × {b} কত?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}।', f_times: '{n} × {pw} = {t}।', f_div: '{t} ÷ {dv} = {ans}।', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 দিয়ে শেষ হওয়া সংখ্যার বর্গ', sample: '65² = 4225', tagline: 'আগেরটিকে তার পরেরটি দিয়ে গুণ, তারপর 25।',
    how: ['শেষের 5 সরিয়ে দিন; যা থাকল তাকে a বলুন।', 'a-কে পরের সংখ্যা a + 1 দিয়ে গুণ করুন।', 'তার পরে 25 লিখুন।'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25। তাই উত্তর সবসময় a × (a + 1), তারপর 25।',
    q: '{n}² কত?',
    steps: { split: '{n}: 5 সরান, বাকি অংশ = {a}।', mul: '{a} × {a1} = {prod}।', join: '{prod}-এর পরে 25 লিখুন → {ans}।', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'ভিত্তির কাছে (নিখিলম)', sample: '97 × 96 = 9312', tagline: 'সব 9 থেকে, শেষটি 10 থেকে: দেখুন প্রতিটি সংখ্যা 100 থেকে কত দূরে।',
    how: ['দুটি সংখ্যার কাছের ভিত্তি (10, 100, 1000) বেছে নিন।', 'প্রতিটি সংখ্যার ভিত্তি থেকে পার্থক্য বের করুন।', 'বাঁ অংশ: একটি সংখ্যা + অন্যটির পার্থক্য।', 'ডান অংশ: দুই পার্থক্যের গুণফল (ভিত্তিতে যত শূন্য, তত অঙ্ক)।'],
    why: '(ভিত্তি + x)(ভিত্তি + y) = ভিত্তি × (ভিত্তি + x + y) + x × y। পার্থক্য ছোট হলে গুণ খুব ছোট হয়ে যায়।',
    q: '{a} × {b} কত?',
    steps: { base: '{a} আর {b}-এর ভিত্তি {base}।', dev: 'পার্থক্য: {base} থেকে {a}-এর {da}, {b}-এর {db}।', cross: 'বাঁ অংশ: {a} {db} = {left}।', prod: 'ডান অংশ: ({da}) × ({db}) = {prod}, {k} অঙ্কে লিখুন।', borrow: 'ডান অংশ {prod} ঋণাত্মক: বাঁ দিক থেকে {c} ধার নিন। বাঁ {left} → {l2}, ডান {prod} + {cb} = {p2}।', carry: '{prod} ভিত্তি {base}-এর জন্য বড়: হাতে {c}, বাঁ {left} → {l3}, ডান {p3}।', join: '{left} আর {right} পাশাপাশি লিখুন → {ans}।', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ঊর্ধ্ব-তির্যক (খাড়া ও আড়াআড়ি)', sample: '23 × 14 = 322', tagline: 'যেকোনো গুণ, এক এক কলাম করে।',
    how: ['ডান দিক থেকে এক এক কলাম করে এগোন।', 'প্রতিটি কলামে যে অঙ্কগুলো মেলে তাদের গুণফল (খাড়া ও আড়াআড়ি) যোগ করুন।', 'একক অঙ্কটি লিখুন, বাকিটা পরের কলামে নিয়ে যান।'],
    why: 'প্রতিটি কলামে সেই সব অঙ্ক-জোড়া আসে যাদের স্থানীয় মান 10-এর একই ঘাত দেয়, ঠিক লম্বা গুণের মতো, শুধু এক লাইনে।',
    q: '{a} × {b} কত?',
    steps: { setup: '{a}-এর নিচে {b} লিখুন।', col: 'কলাম {i}: {terms} = {sum}। {w} লিখুন।', col_in: 'কলাম {i}: {terms} = {sum}, + হাতে {c} = {total}। {w} লিখুন।', col_out: 'কলাম {i}: {terms} = {sum}। {w} লিখুন, হাতে {carry}।', col_in_out: 'কলাম {i}: {terms} = {sum}, + হাতে {c} = {total}। {w} লিখুন, হাতে {carry}।', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 দিয়ে ভাগ', sample: '2301 ÷ 9 = 255 (6)', tagline: 'অঙ্কের চলতি যোগফল থেকেই ভাগফল।',
    how: ['প্রথম অঙ্কটি যেমন আছে লিখুন।', 'আগের যোগফলে পরের অঙ্ক যোগ করতে থাকুন (শেষ অঙ্কটি বাদ)।', 'এই যোগফলগুলোই ভাগফল; সব অঙ্কের যোগফল হল ভাগশেষ।', 'ভাগশেষ 9 বা বেশি হলে 9 বাদ দিন আর ভাগফলে 1 যোগ করুন।'],
    why: '10 = 9 + 1, তাই 9 দিয়ে ভাগ করলে প্রতিটি স্থানীয় মান 1 ভাগশেষ রাখে। সেজন্যই অঙ্কের যোগফল কাজ করে।',
    q: '{n} ÷ 9 কত? (ভাগফল ও ভাগশেষ)',
    steps: { first: '{n}-এর প্রথম অঙ্ক: {d}।', add: '{prev} + {d} = {s}।', quot: 'যোগফল {list} → ভাগফল {q}।', rem: 'ভাগশেষ = {list} = {r}।', adjust: 'ভাগশেষ {r} ≥ 9: ভাগফল {q} → {q2}, ভাগশেষ {r2}।', ans: '{n} ÷ 9 = {q}, ভাগশেষ {r}' } },
  cuberoot: { icon: '🧊', name: 'ঘনমূল', sample: '∛17576 = 26', tagline: 'শেষ অঙ্ক থেকে একক, সামনের অংশ থেকে দশক।',
    how: ['শেষের তিনটি অঙ্ক আলাদা করুন।', 'ঘনের শেষ অঙ্ক মূলের একক অঙ্ক বলে দেয় (2↔8, 3↔7, বাকিগুলো একই)।', 'সামনের অংশে ধরে এমন সবচেয়ে বড় ঘন খুঁজুন: সেটিই দশকের অঙ্ক।'],
    why: '0–9-এর ঘনগুলো সব আলাদা অঙ্কে শেষ হয়, আর দুই অঙ্কের মূলের ঘন (10t)³ আর (10t + 10)³-এর মাঝে থাকে।',
    q: '{n}-এর ঘনমূল কত?',
    steps: { split: '{n} → সামনে {left}, পেছনে {right}।', units: 'শেষ অঙ্ক {last}: {u}³ = {u3}-এর শেষে {last}, তাই একক = {u}।', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, তাই দশক = {t}।', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'শতাংশের কৌশল', sample: '240-এর 15% = 36', tagline: 'যেকোনো শতাংশ 10%, 5% আর অর্ধেক দিয়ে বানান।',
    how: ['10%: 10 দিয়ে ভাগ করুন।', '5%: 10%-এর অর্ধেক।', '50% হল অর্ধেক, 25% অর্ধেকের অর্ধেক, 75% = 50% + 25%।', 'টুকরোগুলো যোগ করুন: 15% = 10% + 5%, 30% = 3 × 10%।'],
    why: 'শতাংশ মানে “100-এর মধ্যে”। শতাংশকে সহজ টুকরোয় ভাঙলে বড় গুণ করতে হয় না।',
    q: '{n}-এর {p}% কত?',
    steps: { half: '{n}-এর 50% = {half}।', quarter: '25% = {half}-এর অর্ধেক = {quarter}।', sum: 'যোগ করুন: {parts} = {ans}।', ten: '{n}-এর 10% = {ten}।', minus: '90% = {n} − {ten} = {ans}।', tens: '{p}% = {tens} × {ten} = {val}।', five: '5% = {ten}-এর অর্ধেক = {five}।', ans: '{n}-এর {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'অঙ্ক-যোগ দিয়ে যাচাই', sample: '47 × 23 = 1081 ✓', tagline: 'যেকোনো গুণ কয়েক সেকেন্ডে যাচাই করুন।',
    how: ['একটি অঙ্ক না থাকা পর্যন্ত সংখ্যার অঙ্কগুলো বারবার যোগ করুন (যাচাইয়ে 9 মানে 0)।', 'দুটি সংখ্যার অঙ্ক-যোগ গুণ করুন; আবার এক অঙ্কে নামান।', 'উত্তরের অঙ্ক-যোগের সঙ্গে মেলান। না মিললে উত্তর ভুল।'],
    why: 'একটি সংখ্যা আর তার অঙ্ক-যোগ 9 দিয়ে ভাগ করলে একই ভাগশেষ থাকে, আর ভাগশেষ গুণ করা যায়।',
    q: '{n}-এর অঙ্ক-যোগ কত?', q_check: '{a} × {b} = {c} কি ঠিক?',
    steps: { start: '{n}-এর অঙ্ক-যোগ বের করুন।', sum: '{label}: {list} = {s}।', single: '{n} আগে থেকেই এক অঙ্কের।', root: '{n}-এর অঙ্ক-যোগ = {r}।', check: '{a} × {b} = {c} যাচাই করুন।', roots: 'অঙ্ক-যোগ: {a} → {ra}, {b} → {rb}।', mulroot: '{ra} × {rb} = {prod} → {rm}।', croot: '{c}-এর অঙ্ক-যোগ → {rc}।', match: '{rm} = {rc}: উত্তর সম্ভবত ঠিক ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ভুল ✗' } }
} };
window.APP_CONTENT.gu = { tricks: {
  mul11: { icon: '✖️', name: '11 વડે ગુણાકાર', sample: '52 × 11 = 572', tagline: 'બાજુ-બાજુના અંક ઉમેરો અને વચ્ચે મૂકો.',
    how: ['છેલ્લો અંક જેમ છે તેમ લખો.', 'જમણેથી ડાબે જતાં બાજુ-બાજુના અંકોનો સરવાળો કરો; સરવાળો 10 કે વધુ હોય તો વદ્દી લઈ જાઓ.', 'સૌથી આગળ પહેલો અંક (અને વદ્દી) લખો.'],
    why: '11 = 10 + 1, એટલે n × 11 = n × 10 + n. સંખ્યાને એક સ્થાન ખસેડીને પોતામાં ઉમેરવી એટલે બાજુના અંક ઉમેરવા.',
    q: '{a} × {b} કેટલા?',
    steps: { last: '{n} નો છેલ્લો અંક {d}. {d} લખો.', pair: 'બાજુના અંક {x} + {y} = {s}. {w} લખો.', pair_in: 'બાજુના અંક {x} + {y} + વદ્દી {c} = {s}. {w} લખો.', pair_out: 'બાજુના અંક {x} + {y} = {s}. {w} લખો, વદ્દી {carry}.', pair_in_out: 'બાજુના અંક {x} + {y} + વદ્દી {c} = {s}. {w} લખો, વદ્દી {carry}.', first: 'પહેલો અંક {f} સૌથી આગળ લખો.', first_c: 'પહેલો અંક {f} + વદ્દી {c} = {s} સૌથી આગળ લખો.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 વડે ગુણાકાર', sample: '47 × 99 = 4653', tagline: 'એક ઓછો, પછી પૂરક.',
    how: ['સંખ્યામાં જેટલા 9 એટલા જ અંક હોય તો: ડાબો ભાગ = સંખ્યા − 1.', 'જમણો ભાગ = સંખ્યાને 10, 100 કે 1000 થવા માટે જોઈએ તેટલા.', 'નહીં તો: 10, 100 કે 1000 વડે ગુણો અને સંખ્યા બાદ કરો.'],
    why: '99 = 100 − 1, એટલે n × 99 = n × 100 − n. તેને વહેંચતાં (n − 1) પછી (100 − n) આવે.',
    q: '{a} × {b} કેટલા?',
    steps: { c_left: '{n} × {nines}: ડાબો ભાગ = {n} − 1 = {left}.', c_right: 'જમણો ભાગ = {base} − {n} = {right}.', c_join: '{left} અને {right} જોડીને લખો → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 વડે ગુણાકાર', sample: '48 × 5 = 240', tagline: '10 કે 100 વડે ગુણો, પછી અડધું કે ચોથા ભાગનું.',
    how: ['× 5: 10 વડે ગુણો, પછી 2 વડે ભાગો.', '× 50: 100 વડે ગુણો, પછી 2 વડે ભાગો.', '× 25: 100 વડે ગુણો, પછી 4 વડે ભાગો.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 અને 25 = 100 ÷ 4. શૂન્ય ઉમેરી અડધું કરવું લાંબા ગુણાકાર કરતાં સહેલું.',
    q: '{a} × {b} કેટલા?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 થી પૂરી થતી સંખ્યાના વર્ગ', sample: '65² = 4225', tagline: 'આગળના ભાગને તેના પછીના વડે ગુણો, પછી 25.',
    how: ['છેલ્લો 5 કાઢી નાખો; બાકી રહે તેને a કહો.', 'a ને પછીની સંખ્યા a + 1 વડે ગુણો.', 'તેના પછી 25 લખો.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. એટલે જવાબ હંમેશાં a × (a + 1) અને પછી 25.',
    q: '{n}² કેટલા?',
    steps: { split: '{n}: 5 કાઢો, બાકી ભાગ = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} પછી 25 લખો → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'આધારની નજીક (નિખિલમ્)', sample: '97 × 96 = 9312', tagline: 'બધા 9 માંથી, છેલ્લો 10 માંથી: દરેક સંખ્યા 100 થી કેટલી દૂર છે તે જુઓ.',
    how: ['બંને સંખ્યાની નજીકનો આધાર (10, 100, 1000) પસંદ કરો.', 'દરેક સંખ્યાનો આધારથી તફાવત કાઢો.', 'ડાબો ભાગ: એક સંખ્યા + બીજીનો તફાવત.', 'જમણો ભાગ: બંને તફાવતનો ગુણાકાર (આધારમાં જેટલા શૂન્ય એટલા અંક).'],
    why: '(આધાર + x)(આધાર + y) = આધાર × (આધાર + x + y) + x × y. તફાવત નાના હોય તો ગુણાકાર બહુ નાનો થઈ જાય.',
    q: '{a} × {b} કેટલા?',
    steps: { base: '{a} અને {b} માટે આધાર {base}.', dev: 'તફાવત: {base} થી {a} નો {da}, {b} નો {db}.', cross: 'ડાબો ભાગ: {a} {db} = {left}.', prod: 'જમણો ભાગ: ({da}) × ({db}) = {prod}, {k} અંકમાં લખો.', borrow: 'જમણો ભાગ {prod} ઋણ છે: ડાબેથી {c} ઉછીના લો. ડાબો {left} → {l2}, જમણો {prod} + {cb} = {p2}.', carry: '{prod} આધાર {base} માટે મોટો છે: વદ્દી {c}, ડાબો {left} → {l3}, જમણો {p3}.', join: '{left} અને {right} જોડીને લખો → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ઊર્ધ્વ-તિર્યક (ઊભું અને ત્રાંસું)', sample: '23 × 14 = 322', tagline: 'કોઈ પણ ગુણાકાર, એક-એક કૉલમ કરીને.',
    how: ['જમણેથી એક-એક કૉલમ કરો.', 'દરેક કૉલમમાં મળતા અંકોના ગુણાકાર (ઊભા અને ત્રાંસા) ઉમેરો.', 'એકમનો અંક લખો અને બાકીની વદ્દી આગળના કૉલમમાં લઈ જાઓ.'],
    why: 'દરેક કૉલમમાં એવી બધી અંક-જોડી આવે જેની સ્થાનકિંમત 10 ની એક જ ઘાત આપે, બરાબર લાંબા ગુણાકાર જેવું, પણ એક લીટીમાં.',
    q: '{a} × {b} કેટલા?',
    steps: { setup: '{a} ની નીચે {b} લખો.', col: 'કૉલમ {i}: {terms} = {sum}. {w} લખો.', col_in: 'કૉલમ {i}: {terms} = {sum}, + વદ્દી {c} = {total}. {w} લખો.', col_out: 'કૉલમ {i}: {terms} = {sum}. {w} લખો, વદ્દી {carry}.', col_in_out: 'કૉલમ {i}: {terms} = {sum}, + વદ્દી {c} = {total}. {w} લખો, વદ્દી {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 વડે ભાગાકાર', sample: '2301 ÷ 9 = 255 (6)', tagline: 'અંકોના ચાલુ સરવાળાથી ભાગફળ મળે.',
    how: ['પહેલો અંક એમ જ લખો.', 'આગળના સરવાળામાં પછીનો અંક ઉમેરતા જાઓ (છેલ્લો અંક છોડી દો).', 'આ સરવાળા ભાગફળ બનાવે; બધા અંકોનો સરવાળો શેષ છે.', 'શેષ 9 કે વધુ હોય તો 9 બાદ કરો અને ભાગફળમાં 1 ઉમેરો.'],
    why: '10 = 9 + 1, એટલે 9 વડે ભાગતાં દરેક સ્થાનકિંમત 1 શેષ રાખે. તેથી અંકોનો સરવાળો કામ કરે છે.',
    q: '{n} ÷ 9 કેટલા? (ભાગફળ અને શેષ)',
    steps: { first: '{n} નો પહેલો અંક: {d}.', add: '{prev} + {d} = {s}.', quot: 'સરવાળા {list} → ભાગફળ {q}.', rem: 'શેષ = {list} = {r}.', adjust: 'શેષ {r} ≥ 9: ભાગફળ {q} → {q2}, શેષ {r2}.', ans: '{n} ÷ 9 = {q}, શેષ {r}' } },
  cuberoot: { icon: '🧊', name: 'ઘનમૂળ', sample: '∛17576 = 26', tagline: 'છેલ્લા અંકથી એકમ, આગળના ભાગથી દશક.',
    how: ['છેલ્લા ત્રણ અંક અલગ કરો.', 'ઘનનો છેલ્લો અંક મૂળનો એકમ અંક કહે છે (2↔8, 3↔7, બાકી એ જ).', 'આગળના ભાગમાં સમાય તેવો સૌથી મોટો ઘન શોધો: એ જ દશકનો અંક.'],
    why: '0–9 ના ઘન બધા જુદા અંકથી પૂરા થાય છે, અને બે અંકના મૂળનો ઘન (10t)³ અને (10t + 10)³ ની વચ્ચે હોય છે.',
    q: '{n} નું ઘનમૂળ કેટલું?',
    steps: { split: '{n} → આગળ {left}, પાછળ {right}.', units: 'છેલ્લો અંક {last}: {u}³ = {u3} નો છેલ્લો અંક {last}, એટલે એકમ = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, એટલે દશક = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'ટકાવારીની યુક્તિઓ', sample: '240 ના 15% = 36', tagline: 'કોઈ પણ ટકા 10%, 5% અને અડધામાંથી બનાવો.',
    how: ['10%: 10 વડે ભાગો.', '5%: 10% નું અડધું.', '50% એટલે અડધું, 25% અડધાનું અડધું, 75% = 50% + 25%.', 'ટુકડા ઉમેરો: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'ટકા એટલે “100 માંથી”. ટકાને સહેલા ટુકડામાં વહેંચવાથી મોટો ગુણાકાર ટળે.',
    q: '{n} ના {p}% કેટલા?',
    steps: { half: '{n} ના 50% = {half}.', quarter: '25% = {half} નું અડધું = {quarter}.', sum: 'ઉમેરો: {parts} = {ans}.', ten: '{n} ના 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten} નું અડધું = {five}.', ans: '{n} ના {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'અંક-સરવાળાથી ચકાસણી', sample: '47 × 23 = 1081 ✓', tagline: 'કોઈ પણ ગુણાકાર થોડી સેકંડમાં ચકાસો.',
    how: ['એક અંક બાકી રહે ત્યાં સુધી સંખ્યાના અંક વારંવાર ઉમેરો (ચકાસણીમાં 9 એટલે 0).', 'બંને સંખ્યાના અંક-સરવાળાનો ગુણાકાર કરો; ફરી એક અંક સુધી લાવો.', 'જવાબના અંક-સરવાળા સાથે સરખાવો. જુદું આવે તો જવાબ ખોટો.'],
    why: 'સંખ્યા અને તેનો અંક-સરવાળો 9 વડે ભાગતાં સરખી શેષ રાખે છે, અને શેષનો ગુણાકાર થાય છે.',
    q: '{n} નો અંક-સરવાળો કેટલો?', q_check: 'શું {a} × {b} = {c} સાચું છે?',
    steps: { start: '{n} નો અંક-સરવાળો કાઢો.', sum: '{label}: {list} = {s}.', single: '{n} પહેલેથી એક અંકનો છે.', root: '{n} નો અંક-સરવાળો = {r}.', check: '{a} × {b} = {c} ચકાસો.', roots: 'અંક-સરવાળા: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} નો અંક-સરવાળો → {rc}.', match: '{rm} = {rc}: જવાબ કદાચ સાચો ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ખોટું ✗' } }
} };
window.APP_CONTENT.pa = { tricks: {
  mul11: { icon: '✖️', name: '11 ਨਾਲ ਗੁਣਾ', sample: '52 × 11 = 572', tagline: 'ਨਾਲ-ਨਾਲ ਦੇ ਅੰਕ ਜੋੜੋ ਅਤੇ ਵਿਚਕਾਰ ਰੱਖੋ।',
    how: ['ਆਖਰੀ ਅੰਕ ਜਿਵੇਂ ਹੈ ਤਿਵੇਂ ਲਿਖੋ।', 'ਸੱਜੇ ਤੋਂ ਖੱਬੇ ਜਾਂਦੇ ਹੋਏ ਨਾਲ-ਨਾਲ ਦੇ ਅੰਕ ਜੋੜੋ; ਜੋੜ 10 ਜਾਂ ਵੱਧ ਹੋਵੇ ਤਾਂ ਹਾਸਲ ਲੈ ਜਾਓ।', 'ਸਭ ਤੋਂ ਅੱਗੇ ਪਹਿਲਾ ਅੰਕ (ਅਤੇ ਹਾਸਲ) ਲਿਖੋ।'],
    why: '11 = 10 + 1, ਇਸ ਲਈ n × 11 = n × 10 + n। ਸੰਖਿਆ ਨੂੰ ਇੱਕ ਥਾਂ ਖਿਸਕਾ ਕੇ ਆਪਣੇ ਨਾਲ ਜੋੜਨਾ ਨਾਲ ਦੇ ਅੰਕ ਜੋੜਨ ਵਰਗਾ ਹੀ ਹੈ।',
    q: '{a} × {b} ਕਿੰਨਾ ਹੈ?',
    steps: { last: '{n} ਦਾ ਆਖਰੀ ਅੰਕ {d} ਹੈ। {d} ਲਿਖੋ।', pair: 'ਨਾਲ ਦੇ ਅੰਕ {x} + {y} = {s}। {w} ਲਿਖੋ।', pair_in: 'ਨਾਲ ਦੇ ਅੰਕ {x} + {y} + ਹਾਸਲ {c} = {s}। {w} ਲਿਖੋ।', pair_out: 'ਨਾਲ ਦੇ ਅੰਕ {x} + {y} = {s}। {w} ਲਿਖੋ, ਹਾਸਲ {carry}।', pair_in_out: 'ਨਾਲ ਦੇ ਅੰਕ {x} + {y} + ਹਾਸਲ {c} = {s}। {w} ਲਿਖੋ, ਹਾਸਲ {carry}।', first: 'ਪਹਿਲਾ ਅੰਕ {f} ਸਭ ਤੋਂ ਅੱਗੇ ਲਿਖੋ।', first_c: 'ਪਹਿਲਾ ਅੰਕ {f} + ਹਾਸਲ {c} = {s} ਸਭ ਤੋਂ ਅੱਗੇ ਲਿਖੋ।', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 ਨਾਲ ਗੁਣਾ', sample: '47 × 99 = 4653', tagline: 'ਇੱਕ ਘੱਟ, ਫਿਰ ਪੂਰਕ।',
    how: ['ਜੇ ਸੰਖਿਆ ਵਿੱਚ ਓਨੇ ਹੀ ਅੰਕ ਹੋਣ ਜਿੰਨੇ 9 ਹਨ: ਖੱਬਾ ਹਿੱਸਾ = ਸੰਖਿਆ − 1।', 'ਸੱਜਾ ਹਿੱਸਾ = ਸੰਖਿਆ ਨੂੰ 10, 100 ਜਾਂ 1000 ਤੱਕ ਪਹੁੰਚਣ ਲਈ ਜਿੰਨਾ ਚਾਹੀਦਾ।', 'ਨਹੀਂ ਤਾਂ: 10, 100 ਜਾਂ 1000 ਨਾਲ ਗੁਣਾ ਕਰੋ ਅਤੇ ਸੰਖਿਆ ਘਟਾਓ।'],
    why: '99 = 100 − 1, ਇਸ ਲਈ n × 99 = n × 100 − n। ਇਸ ਨੂੰ ਵੰਡਣ ਨਾਲ (n − 1) ਤੋਂ ਬਾਅਦ (100 − n) ਆਉਂਦਾ ਹੈ।',
    q: '{a} × {b} ਕਿੰਨਾ ਹੈ?',
    steps: { c_left: '{n} × {nines}: ਖੱਬਾ ਹਿੱਸਾ = {n} − 1 = {left}।', c_right: 'ਸੱਜਾ ਹਿੱਸਾ = {base} − {n} = {right}।', c_join: '{left} ਅਤੇ {right} ਜੋੜ ਕੇ ਲਿਖੋ → {ans}।', n_is: '{nines} = {base} − 1।', n_times: '{n} × {base} = {m}।', n_minus: '{m} − {n} = {ans}।', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 ਨਾਲ ਗੁਣਾ', sample: '48 × 5 = 240', tagline: '10 ਜਾਂ 100 ਨਾਲ ਗੁਣਾ, ਫਿਰ ਅੱਧਾ ਜਾਂ ਚੌਥਾਈ।',
    how: ['× 5: 10 ਨਾਲ ਗੁਣਾ ਕਰੋ, ਫਿਰ 2 ਨਾਲ ਵੰਡੋ।', '× 50: 100 ਨਾਲ ਗੁਣਾ ਕਰੋ, ਫਿਰ 2 ਨਾਲ ਵੰਡੋ।', '× 25: 100 ਨਾਲ ਗੁਣਾ ਕਰੋ, ਫਿਰ 4 ਨਾਲ ਵੰਡੋ।'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 ਅਤੇ 25 = 100 ÷ 4। ਸਿਫ਼ਰ ਲਾ ਕੇ ਅੱਧਾ ਕਰਨਾ ਲੰਬੀ ਗੁਣਾ ਨਾਲੋਂ ਸੌਖਾ ਹੈ।',
    q: '{a} × {b} ਕਿੰਨਾ ਹੈ?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}।', f_times: '{n} × {pw} = {t}।', f_div: '{t} ÷ {dv} = {ans}।', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 ਨਾਲ ਖਤਮ ਹੋਣ ਵਾਲੇ ਵਰਗ', sample: '65² = 4225', tagline: 'ਪਹਿਲੇ ਹਿੱਸੇ ਨੂੰ ਅਗਲੇ ਨਾਲ ਗੁਣਾ, ਫਿਰ 25।',
    how: ['ਆਖਰੀ 5 ਹਟਾਓ; ਜੋ ਬਚਿਆ ਉਸ ਨੂੰ a ਕਹੋ।', 'a ਨੂੰ ਅਗਲੀ ਸੰਖਿਆ a + 1 ਨਾਲ ਗੁਣਾ ਕਰੋ।', 'ਉਸ ਤੋਂ ਬਾਅਦ 25 ਲਿਖੋ।'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25। ਇਸ ਲਈ ਜਵਾਬ ਹਮੇਸ਼ਾ a × (a + 1) ਅਤੇ ਫਿਰ 25 ਹੁੰਦਾ ਹੈ।',
    q: '{n}² ਕਿੰਨਾ ਹੈ?',
    steps: { split: '{n}: 5 ਹਟਾਓ, ਬਾਕੀ ਹਿੱਸਾ = {a}।', mul: '{a} × {a1} = {prod}।', join: '{prod} ਤੋਂ ਬਾਅਦ 25 ਲਿਖੋ → {ans}।', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'ਆਧਾਰ ਦੇ ਨੇੜੇ (ਨਿਖਿਲਮ)', sample: '97 × 96 = 9312', tagline: 'ਸਾਰੇ 9 ਵਿੱਚੋਂ, ਆਖਰੀ 10 ਵਿੱਚੋਂ: ਦੇਖੋ ਹਰ ਸੰਖਿਆ 100 ਤੋਂ ਕਿੰਨੀ ਦੂਰ ਹੈ।',
    how: ['ਦੋਵਾਂ ਸੰਖਿਆਵਾਂ ਦੇ ਨੇੜੇ ਦਾ ਆਧਾਰ (10, 100, 1000) ਚੁਣੋ।', 'ਹਰ ਸੰਖਿਆ ਦਾ ਆਧਾਰ ਤੋਂ ਫ਼ਰਕ ਕੱਢੋ।', 'ਖੱਬਾ ਹਿੱਸਾ: ਇੱਕ ਸੰਖਿਆ + ਦੂਜੀ ਦਾ ਫ਼ਰਕ।', 'ਸੱਜਾ ਹਿੱਸਾ: ਦੋਵਾਂ ਫ਼ਰਕਾਂ ਦੀ ਗੁਣਾ (ਆਧਾਰ ਵਿੱਚ ਜਿੰਨੀਆਂ ਸਿਫ਼ਰਾਂ, ਓਨੇ ਅੰਕ)।'],
    why: '(ਆਧਾਰ + x)(ਆਧਾਰ + y) = ਆਧਾਰ × (ਆਧਾਰ + x + y) + x × y। ਫ਼ਰਕ ਛੋਟੇ ਹੋਣ ਤਾਂ ਗੁਣਾ ਬਹੁਤ ਛੋਟੀ ਹੋ ਜਾਂਦੀ ਹੈ।',
    q: '{a} × {b} ਕਿੰਨਾ ਹੈ?',
    steps: { base: '{a} ਅਤੇ {b} ਦਾ ਆਧਾਰ {base} ਹੈ।', dev: 'ਫ਼ਰਕ: {base} ਤੋਂ {a} ਦਾ {da}, {b} ਦਾ {db}।', cross: 'ਖੱਬਾ ਹਿੱਸਾ: {a} {db} = {left}।', prod: 'ਸੱਜਾ ਹਿੱਸਾ: ({da}) × ({db}) = {prod}, {k} ਅੰਕਾਂ ਵਿੱਚ ਲਿਖੋ।', borrow: 'ਸੱਜਾ ਹਿੱਸਾ {prod} ਰਿਣਾਤਮਕ ਹੈ: ਖੱਬੇ ਤੋਂ {c} ਉਧਾਰ ਲਓ। ਖੱਬਾ {left} → {l2}, ਸੱਜਾ {prod} + {cb} = {p2}।', carry: '{prod} ਆਧਾਰ {base} ਲਈ ਵੱਡਾ ਹੈ: ਹਾਸਲ {c}, ਖੱਬਾ {left} → {l3}, ਸੱਜਾ {p3}।', join: '{left} ਅਤੇ {right} ਜੋੜ ਕੇ ਲਿਖੋ → {ans}।', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ਉਰਧਵ-ਤਿਰਯਕ (ਸਿੱਧਾ ਅਤੇ ਤਿਰਛਾ)', sample: '23 × 14 = 322', tagline: 'ਕੋਈ ਵੀ ਗੁਣਾ, ਇੱਕ-ਇੱਕ ਕਾਲਮ ਕਰਕੇ।',
    how: ['ਸੱਜੇ ਤੋਂ ਇੱਕ-ਇੱਕ ਕਾਲਮ ਕਰੋ।', 'ਹਰ ਕਾਲਮ ਵਿੱਚ ਮਿਲਣ ਵਾਲੇ ਅੰਕਾਂ ਦੀਆਂ ਗੁਣਾਵਾਂ (ਸਿੱਧੀਆਂ ਅਤੇ ਤਿਰਛੀਆਂ) ਜੋੜੋ।', 'ਇਕਾਈ ਦਾ ਅੰਕ ਲਿਖੋ ਅਤੇ ਬਾਕੀ ਅਗਲੇ ਕਾਲਮ ਵਿੱਚ ਲੈ ਜਾਓ।'],
    why: 'ਹਰ ਕਾਲਮ ਵਿੱਚ ਉਹ ਸਾਰੇ ਅੰਕ-ਜੋੜੇ ਆਉਂਦੇ ਹਨ ਜਿਨ੍ਹਾਂ ਦਾ ਸਥਾਨਕ ਮੁੱਲ 10 ਦੀ ਇੱਕੋ ਘਾਤ ਦਿੰਦਾ ਹੈ, ਬਿਲਕੁਲ ਲੰਬੀ ਗੁਣਾ ਵਾਂਗ, ਪਰ ਇੱਕ ਲਾਈਨ ਵਿੱਚ।',
    q: '{a} × {b} ਕਿੰਨਾ ਹੈ?',
    steps: { setup: '{a} ਦੇ ਹੇਠਾਂ {b} ਲਿਖੋ।', col: 'ਕਾਲਮ {i}: {terms} = {sum}। {w} ਲਿਖੋ।', col_in: 'ਕਾਲਮ {i}: {terms} = {sum}, + ਹਾਸਲ {c} = {total}। {w} ਲਿਖੋ।', col_out: 'ਕਾਲਮ {i}: {terms} = {sum}। {w} ਲਿਖੋ, ਹਾਸਲ {carry}।', col_in_out: 'ਕਾਲਮ {i}: {terms} = {sum}, + ਹਾਸਲ {c} = {total}। {w} ਲਿਖੋ, ਹਾਸਲ {carry}।', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 ਨਾਲ ਭਾਗ', sample: '2301 ÷ 9 = 255 (6)', tagline: 'ਅੰਕਾਂ ਦੇ ਚੱਲਦੇ ਜੋੜ ਤੋਂ ਭਾਗਫਲ ਮਿਲਦਾ ਹੈ।',
    how: ['ਪਹਿਲਾ ਅੰਕ ਉਵੇਂ ਹੀ ਲਿਖੋ।', 'ਪਿਛਲੇ ਜੋੜ ਵਿੱਚ ਅਗਲਾ ਅੰਕ ਜੋੜਦੇ ਜਾਓ (ਆਖਰੀ ਅੰਕ ਛੱਡ ਦਿਓ)।', 'ਇਹ ਜੋੜ ਭਾਗਫਲ ਬਣਾਉਂਦੇ ਹਨ; ਸਾਰੇ ਅੰਕਾਂ ਦਾ ਜੋੜ ਬਾਕੀ ਹੈ।', 'ਬਾਕੀ 9 ਜਾਂ ਵੱਧ ਹੋਵੇ ਤਾਂ 9 ਘਟਾਓ ਅਤੇ ਭਾਗਫਲ ਵਿੱਚ 1 ਜੋੜੋ।'],
    why: '10 = 9 + 1, ਇਸ ਲਈ 9 ਨਾਲ ਵੰਡਣ ਤੇ ਹਰ ਸਥਾਨਕ ਮੁੱਲ 1 ਬਾਕੀ ਛੱਡਦਾ ਹੈ। ਇਸੇ ਕਰਕੇ ਅੰਕਾਂ ਦਾ ਜੋੜ ਕੰਮ ਕਰਦਾ ਹੈ।',
    q: '{n} ÷ 9 ਕਿੰਨਾ ਹੈ? (ਭਾਗਫਲ ਅਤੇ ਬਾਕੀ)',
    steps: { first: '{n} ਦਾ ਪਹਿਲਾ ਅੰਕ: {d}।', add: '{prev} + {d} = {s}।', quot: 'ਜੋੜ {list} → ਭਾਗਫਲ {q}।', rem: 'ਬਾਕੀ = {list} = {r}।', adjust: 'ਬਾਕੀ {r} ≥ 9: ਭਾਗਫਲ {q} → {q2}, ਬਾਕੀ {r2}।', ans: '{n} ÷ 9 = {q}, ਬਾਕੀ {r}' } },
  cuberoot: { icon: '🧊', name: 'ਘਣਮੂਲ', sample: '∛17576 = 26', tagline: 'ਆਖਰੀ ਅੰਕ ਤੋਂ ਇਕਾਈ, ਅਗਲੇ ਹਿੱਸੇ ਤੋਂ ਦਹਾਈ।',
    how: ['ਆਖਰੀ ਤਿੰਨ ਅੰਕ ਵੱਖ ਕਰੋ।', 'ਘਣ ਦਾ ਆਖਰੀ ਅੰਕ ਮੂਲ ਦਾ ਇਕਾਈ ਅੰਕ ਦੱਸਦਾ ਹੈ (2↔8, 3↔7, ਬਾਕੀ ਉਹੀ)।', 'ਅਗਲੇ ਹਿੱਸੇ ਵਿੱਚ ਸਮਾਉਣ ਵਾਲਾ ਸਭ ਤੋਂ ਵੱਡਾ ਘਣ ਲੱਭੋ: ਉਹੀ ਦਹਾਈ ਦਾ ਅੰਕ ਹੈ।'],
    why: '0–9 ਦੇ ਘਣ ਸਾਰੇ ਵੱਖ-ਵੱਖ ਅੰਕਾਂ ਤੇ ਖਤਮ ਹੁੰਦੇ ਹਨ, ਅਤੇ ਦੋ ਅੰਕਾਂ ਵਾਲੇ ਮੂਲ ਦਾ ਘਣ (10t)³ ਅਤੇ (10t + 10)³ ਦੇ ਵਿਚਕਾਰ ਹੁੰਦਾ ਹੈ।',
    q: '{n} ਦਾ ਘਣਮੂਲ ਕਿੰਨਾ ਹੈ?',
    steps: { split: '{n} → ਅੱਗੇ {left}, ਪਿੱਛੇ {right}।', units: 'ਆਖਰੀ ਅੰਕ {last}: {u}³ = {u3} ਦਾ ਆਖਰੀ ਅੰਕ {last}, ਇਸ ਲਈ ਇਕਾਈ = {u}।', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, ਇਸ ਲਈ ਦਹਾਈ = {t}।', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'ਪ੍ਰਤੀਸ਼ਤ ਦੀਆਂ ਤਰਕੀਬਾਂ', sample: '240 ਦਾ 15% = 36', tagline: 'ਹਰ ਪ੍ਰਤੀਸ਼ਤ 10%, 5% ਅਤੇ ਅੱਧੇ ਤੋਂ ਬਣਾਓ।',
    how: ['10%: 10 ਨਾਲ ਵੰਡੋ।', '5%: 10% ਦਾ ਅੱਧਾ।', '50% ਅੱਧਾ ਹੈ, 25% ਅੱਧੇ ਦਾ ਅੱਧਾ, 75% = 50% + 25%।', 'ਟੁਕੜੇ ਜੋੜੋ: 15% = 10% + 5%, 30% = 3 × 10%।'],
    why: 'ਪ੍ਰਤੀਸ਼ਤ ਦਾ ਮਤਲਬ “100 ਵਿੱਚੋਂ”। ਪ੍ਰਤੀਸ਼ਤ ਨੂੰ ਸੌਖੇ ਟੁਕੜਿਆਂ ਵਿੱਚ ਵੰਡਣ ਨਾਲ ਵੱਡੀ ਗੁਣਾ ਨਹੀਂ ਕਰਨੀ ਪੈਂਦੀ।',
    q: '{n} ਦਾ {p}% ਕਿੰਨਾ ਹੈ?',
    steps: { half: '{n} ਦਾ 50% = {half}।', quarter: '25% = {half} ਦਾ ਅੱਧਾ = {quarter}।', sum: 'ਜੋੜੋ: {parts} = {ans}।', ten: '{n} ਦਾ 10% = {ten}।', minus: '90% = {n} − {ten} = {ans}।', tens: '{p}% = {tens} × {ten} = {val}।', five: '5% = {ten} ਦਾ ਅੱਧਾ = {five}।', ans: '{n} ਦਾ {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'ਅੰਕ-ਜੋੜ ਨਾਲ ਜਾਂਚ', sample: '47 × 23 = 1081 ✓', tagline: 'ਕੋਈ ਵੀ ਗੁਣਾ ਕੁਝ ਸਕਿੰਟਾਂ ਵਿੱਚ ਜਾਂਚੋ।',
    how: ['ਇੱਕ ਅੰਕ ਬਚਣ ਤੱਕ ਸੰਖਿਆ ਦੇ ਅੰਕ ਵਾਰ-ਵਾਰ ਜੋੜੋ (ਜਾਂਚ ਵਿੱਚ 9 ਨੂੰ 0 ਮੰਨੋ)।', 'ਦੋਵਾਂ ਸੰਖਿਆਵਾਂ ਦੇ ਅੰਕ-ਜੋੜ ਦੀ ਗੁਣਾ ਕਰੋ; ਫਿਰ ਇੱਕ ਅੰਕ ਤੱਕ ਘਟਾਓ।', 'ਜਵਾਬ ਦੇ ਅੰਕ-ਜੋੜ ਨਾਲ ਮਿਲਾਓ। ਵੱਖਰਾ ਹੋਵੇ ਤਾਂ ਜਵਾਬ ਗਲਤ ਹੈ।'],
    why: 'ਇੱਕ ਸੰਖਿਆ ਅਤੇ ਉਸ ਦਾ ਅੰਕ-ਜੋੜ 9 ਨਾਲ ਵੰਡਣ ਤੇ ਇੱਕੋ ਬਾਕੀ ਛੱਡਦੇ ਹਨ, ਅਤੇ ਬਾਕੀਆਂ ਦੀ ਗੁਣਾ ਹੁੰਦੀ ਹੈ।',
    q: '{n} ਦਾ ਅੰਕ-ਜੋੜ ਕਿੰਨਾ ਹੈ?', q_check: 'ਕੀ {a} × {b} = {c} ਸਹੀ ਹੈ?',
    steps: { start: '{n} ਦਾ ਅੰਕ-ਜੋੜ ਕੱਢੋ।', sum: '{label}: {list} = {s}।', single: '{n} ਪਹਿਲਾਂ ਹੀ ਇੱਕ ਅੰਕ ਹੈ।', root: '{n} ਦਾ ਅੰਕ-ਜੋੜ = {r}।', check: '{a} × {b} = {c} ਜਾਂਚੋ।', roots: 'ਅੰਕ-ਜੋੜ: {a} → {ra}, {b} → {rb}।', mulroot: '{ra} × {rb} = {prod} → {rm}।', croot: '{c} ਦਾ ਅੰਕ-ਜੋੜ → {rc}।', match: '{rm} = {rc}: ਜਵਾਬ ਸ਼ਾਇਦ ਸਹੀ ਹੈ ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ਗਲਤ ਹੈ ✗' } }
} };
window.APP_CONTENT.or = { tricks: {
  mul11: { icon: '✖️', name: '11 ଦ୍ୱାରା ଗୁଣନ', sample: '52 × 11 = 572', tagline: 'ପାଖାପାଖି ଅଙ୍କ ଯୋଗ କରି ମଝିରେ ରଖନ୍ତୁ।',
    how: ['ଶେଷ ଅଙ୍କଟି ଯେମିତି ଅଛି ସେମିତି ଲେଖନ୍ତୁ।', 'ଡାହାଣରୁ ବାମକୁ ଯାଉଯାଉ ପାଖାପାଖି ଦୁଇଟି ଅଙ୍କ ଯୋଗ କରନ୍ତୁ; ଯୋଗଫଳ 10 ବା ଅଧିକ ହେଲେ ହାତକୁ ନିଅନ୍ତୁ।', 'ସବୁଠୁ ଆଗରେ ପ୍ରଥମ ଅଙ୍କ (ଓ ହାତ) ଲେଖନ୍ତୁ।'],
    why: '11 = 10 + 1, ତେଣୁ n × 11 = n × 10 + n। ସଂଖ୍ୟାକୁ ଏକ ଘର ଘୁଞ୍ଚାଇ ନିଜ ସହ ଯୋଗ କରିବା ମାନେ ପାଖାପାଖି ଅଙ୍କ ଯୋଗ କରିବା।',
    q: '{a} × {b} କେତେ?',
    steps: { last: '{n} ର ଶେଷ ଅଙ୍କ {d}। {d} ଲେଖନ୍ତୁ।', pair: 'ପାଖ ଅଙ୍କ {x} + {y} = {s}। {w} ଲେଖନ୍ତୁ।', pair_in: 'ପାଖ ଅଙ୍କ {x} + {y} + ହାତ {c} = {s}। {w} ଲେଖନ୍ତୁ।', pair_out: 'ପାଖ ଅଙ୍କ {x} + {y} = {s}। {w} ଲେଖନ୍ତୁ, ହାତ {carry}।', pair_in_out: 'ପାଖ ଅଙ୍କ {x} + {y} + ହାତ {c} = {s}। {w} ଲେଖନ୍ତୁ, ହାତ {carry}।', first: 'ପ୍ରଥମ ଅଙ୍କ {f} ସବୁଠୁ ଆଗରେ ଲେଖନ୍ତୁ।', first_c: 'ପ୍ରଥମ ଅଙ୍କ {f} + ହାତ {c} = {s} ସବୁଠୁ ଆଗରେ ଲେଖନ୍ତୁ।', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 ଦ୍ୱାରା ଗୁଣନ', sample: '47 × 99 = 4653', tagline: 'ଗୋଟିଏ କମ୍, ତା’ପରେ ପୂରକ।',
    how: ['ସଂଖ୍ୟାରେ ଯେତେ 9 ସେତେ ଅଙ୍କ ଥିଲେ: ବାମ ଭାଗ = ସଂଖ୍ୟା − 1।', 'ଡାହାଣ ଭାଗ = ସଂଖ୍ୟାକୁ 10, 100 ବା 1000 ହେବାକୁ ଯେତେ ଦରକାର।', 'ନହେଲେ: 10, 100 ବା 1000 ଦ୍ୱାରା ଗୁଣି ସଂଖ୍ୟାଟି ବିୟୋଗ କରନ୍ତୁ।'],
    why: '99 = 100 − 1, ତେଣୁ n × 99 = n × 100 − n। ଏହାକୁ ଭାଗ କଲେ (n − 1) ପରେ (100 − n) ଆସେ।',
    q: '{a} × {b} କେତେ?',
    steps: { c_left: '{n} × {nines}: ବାମ ଭାଗ = {n} − 1 = {left}।', c_right: 'ଡାହାଣ ଭାଗ = {base} − {n} = {right}।', c_join: '{left} ଓ {right} ପାଖାପାଖି ଲେଖନ୍ତୁ → {ans}।', n_is: '{nines} = {base} − 1।', n_times: '{n} × {base} = {m}।', n_minus: '{m} − {n} = {ans}।', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 ଦ୍ୱାରା ଗୁଣନ', sample: '48 × 5 = 240', tagline: '10 ବା 100 ଦ୍ୱାରା ଗୁଣନ, ତା’ପରେ ଅଧା ବା ଚଉଠ।',
    how: ['× 5: 10 ଦ୍ୱାରା ଗୁଣି 2 ଦ୍ୱାରା ଭାଗ କରନ୍ତୁ।', '× 50: 100 ଦ୍ୱାରା ଗୁଣି 2 ଦ୍ୱାରା ଭାଗ କରନ୍ତୁ।', '× 25: 100 ଦ୍ୱାରା ଗୁଣି 4 ଦ୍ୱାରା ଭାଗ କରନ୍ତୁ।'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 ଓ 25 = 100 ÷ 4। ଶୂନ ଲଗାଇ ଅଧା କରିବା ଲମ୍ବା ଗୁଣନଠାରୁ ସହଜ।',
    q: '{a} × {b} କେତେ?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}।', f_times: '{n} × {pw} = {t}।', f_div: '{t} ÷ {dv} = {ans}।', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 ରେ ଶେଷ ହେଉଥିବା ସଂଖ୍ୟାର ବର୍ଗ', sample: '65² = 4225', tagline: 'ଆଗ ଭାଗକୁ ତା’ ପରବର୍ତ୍ତୀ ଦ୍ୱାରା ଗୁଣନ, ତା’ପରେ 25।',
    how: ['ଶେଷ 5 ହଟାନ୍ତୁ; ଯାହା ରହିଲା ତାକୁ a କୁହନ୍ତୁ।', 'a କୁ ପରବର୍ତ୍ତୀ ସଂଖ୍ୟା a + 1 ଦ୍ୱାରା ଗୁଣନ୍ତୁ।', 'ତା’ ପରେ 25 ଲେଖନ୍ତୁ।'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25। ତେଣୁ ଉତ୍ତର ସବୁବେଳେ a × (a + 1), ତା’ପରେ 25।',
    q: '{n}² କେତେ?',
    steps: { split: '{n}: 5 ହଟାନ୍ତୁ, ବାକି ଭାଗ = {a}।', mul: '{a} × {a1} = {prod}।', join: '{prod} ପରେ 25 ଲେଖନ୍ତୁ → {ans}।', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'ଆଧାର ପାଖରେ (ନିଖିଳମ୍)', sample: '97 × 96 = 9312', tagline: 'ସବୁ 9 ରୁ, ଶେଷଟି 10 ରୁ: ଦେଖନ୍ତୁ ପ୍ରତି ସଂଖ୍ୟା 100 ରୁ କେତେ ଦୂର।',
    how: ['ଦୁଇ ସଂଖ୍ୟା ପାଖର ଆଧାର (10, 100, 1000) ବାଛନ୍ତୁ।', 'ପ୍ରତି ସଂଖ୍ୟାର ଆଧାରଠାରୁ ତଫାତ ବାହାର କରନ୍ତୁ।', 'ବାମ ଭାଗ: ଗୋଟିଏ ସଂଖ୍ୟା + ଅନ୍ୟଟିର ତଫାତ।', 'ଡାହାଣ ଭାଗ: ଦୁଇ ତଫାତର ଗୁଣଫଳ (ଆଧାରରେ ଯେତେ ଶୂନ, ସେତେ ଅଙ୍କ)।'],
    why: '(ଆଧାର + x)(ଆଧାର + y) = ଆଧାର × (ଆଧାର + x + y) + x × y। ତଫାତ ଛୋଟ ହେଲେ ଗୁଣନ ବହୁତ ଛୋଟ ହୋଇଯାଏ।',
    q: '{a} × {b} କେତେ?',
    steps: { base: '{a} ଓ {b} ର ଆଧାର {base}।', dev: 'ତଫାତ: {base} ରୁ {a} ର {da}, {b} ର {db}।', cross: 'ବାମ ଭାଗ: {a} {db} = {left}।', prod: 'ଡାହାଣ ଭାଗ: ({da}) × ({db}) = {prod}, {k} ଅଙ୍କରେ ଲେଖନ୍ତୁ।', borrow: 'ଡାହାଣ ଭାଗ {prod} ଋଣାତ୍ମକ: ବାମରୁ {c} ଧାର ନିଅନ୍ତୁ। ବାମ {left} → {l2}, ଡାହାଣ {prod} + {cb} = {p2}।', carry: '{prod} ଆଧାର {base} ପାଇଁ ବଡ଼: ହାତ {c}, ବାମ {left} → {l3}, ଡାହାଣ {p3}।', join: '{left} ଓ {right} ପାଖାପାଖି ଲେଖନ୍ତୁ → {ans}।', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ଊର୍ଦ୍ଧ୍ୱ-ତିର୍ଯ୍ୟକ (ଠିଆ ଓ ତେରେଛା)', sample: '23 × 14 = 322', tagline: 'ଯେକୌଣସି ଗୁଣନ, ଗୋଟିଏ ଗୋଟିଏ ସ୍ତମ୍ଭ କରି।',
    how: ['ଡାହାଣରୁ ଗୋଟିଏ ଗୋଟିଏ ସ୍ତମ୍ଭ କରନ୍ତୁ।', 'ପ୍ରତି ସ୍ତମ୍ଭରେ ମିଳୁଥିବା ଅଙ୍କଗୁଡ଼ିକର ଗୁଣଫଳ (ଠିଆ ଓ ତେରେଛା) ଯୋଗ କରନ୍ତୁ।', 'ଏକକ ଅଙ୍କ ଲେଖନ୍ତୁ, ବାକି ହାତ ପରବର୍ତ୍ତୀ ସ୍ତମ୍ଭକୁ ନିଅନ୍ତୁ।'],
    why: 'ପ୍ରତି ସ୍ତମ୍ଭରେ ସେହି ସବୁ ଅଙ୍କ-ଯୋଡ଼ି ଆସନ୍ତି ଯାହାର ସ୍ଥାନୀୟ ମାନ 10 ର ଏକା ଘାତ ଦିଏ, ଠିକ୍ ଲମ୍ବା ଗୁଣନ ପରି, କେବଳ ଗୋଟିଏ ଧାଡ଼ିରେ।',
    q: '{a} × {b} କେତେ?',
    steps: { setup: '{a} ତଳେ {b} ଲେଖନ୍ତୁ।', col: 'ସ୍ତମ୍ଭ {i}: {terms} = {sum}। {w} ଲେଖନ୍ତୁ।', col_in: 'ସ୍ତମ୍ଭ {i}: {terms} = {sum}, + ହାତ {c} = {total}। {w} ଲେଖନ୍ତୁ।', col_out: 'ସ୍ତମ୍ଭ {i}: {terms} = {sum}। {w} ଲେଖନ୍ତୁ, ହାତ {carry}।', col_in_out: 'ସ୍ତମ୍ଭ {i}: {terms} = {sum}, + ହାତ {c} = {total}। {w} ଲେଖନ୍ତୁ, ହାତ {carry}।', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 ଦ୍ୱାରା ଭାଗ', sample: '2301 ÷ 9 = 255 (6)', tagline: 'ଅଙ୍କର ଚାଲୁ ଯୋଗଫଳରୁ ଭାଗଫଳ ମିଳେ।',
    how: ['ପ୍ରଥମ ଅଙ୍କଟି ସେମିତି ଲେଖନ୍ତୁ।', 'ଆଗ ଯୋଗଫଳରେ ପରବର୍ତ୍ତୀ ଅଙ୍କ ଯୋଗ କରି ଚାଲନ୍ତୁ (ଶେଷ ଅଙ୍କଟି ଛାଡ଼ନ୍ତୁ)।', 'ଏହି ଯୋଗଫଳଗୁଡ଼ିକ ଭାଗଫଳ ତିଆରି କରନ୍ତି; ସବୁ ଅଙ୍କର ଯୋଗଫଳ ହେଉଛି ଭାଗଶେଷ।', 'ଭାଗଶେଷ 9 ବା ଅଧିକ ହେଲେ 9 ବାଦ୍ ଦିଅନ୍ତୁ ଓ ଭାଗଫଳରେ 1 ଯୋଗ କରନ୍ତୁ।'],
    why: '10 = 9 + 1, ତେଣୁ 9 ଦ୍ୱାରା ଭାଗ କଲେ ପ୍ରତି ସ୍ଥାନୀୟ ମାନ 1 ଭାଗଶେଷ ରଖେ। ସେଥିପାଇଁ ଅଙ୍କ ଯୋଗଫଳ କାମ କରେ।',
    q: '{n} ÷ 9 କେତେ? (ଭାଗଫଳ ଓ ଭାଗଶେଷ)',
    steps: { first: '{n} ର ପ୍ରଥମ ଅଙ୍କ: {d}।', add: '{prev} + {d} = {s}।', quot: 'ଯୋଗଫଳ {list} → ଭାଗଫଳ {q}।', rem: 'ଭାଗଶେଷ = {list} = {r}।', adjust: 'ଭାଗଶେଷ {r} ≥ 9: ଭାଗଫଳ {q} → {q2}, ଭାଗଶେଷ {r2}।', ans: '{n} ÷ 9 = {q}, ଭାଗଶେଷ {r}' } },
  cuberoot: { icon: '🧊', name: 'ଘନମୂଳ', sample: '∛17576 = 26', tagline: 'ଶେଷ ଅଙ୍କରୁ ଏକକ, ଆଗ ଭାଗରୁ ଦଶକ।',
    how: ['ଶେଷ ତିନୋଟି ଅଙ୍କ ଅଲଗା କରନ୍ତୁ।', 'ଘନର ଶେଷ ଅଙ୍କ ମୂଳର ଏକକ ଅଙ୍କ କହେ (2↔8, 3↔7, ବାକି ସେହି)।', 'ଆଗ ଭାଗରେ ଧରୁଥିବା ସବୁଠୁ ବଡ଼ ଘନ ଖୋଜନ୍ତୁ: ତାହା ହିଁ ଦଶକ ଅଙ୍କ।'],
    why: '0–9 ର ଘନ ସବୁ ଅଲଗା ଅଙ୍କରେ ଶେଷ ହୁଏ, ଓ ଦୁଇ ଅଙ୍କର ମୂଳର ଘନ (10t)³ ଓ (10t + 10)³ ମଝିରେ ରହେ।',
    q: '{n} ର ଘନମୂଳ କେତେ?',
    steps: { split: '{n} → ଆଗ {left}, ପଛ {right}।', units: 'ଶେଷ ଅଙ୍କ {last}: {u}³ = {u3} ର ଶେଷ ଅଙ୍କ {last}, ତେଣୁ ଏକକ = {u}।', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, ତେଣୁ ଦଶକ = {t}।', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'ଶତକଡ଼ାର କୌଶଳ', sample: '240 ର 15% = 36', tagline: 'ଯେକୌଣସି ଶତକଡ଼ା 10%, 5% ଓ ଅଧାରୁ ତିଆରି କରନ୍ତୁ।',
    how: ['10%: 10 ଦ୍ୱାରା ଭାଗ କରନ୍ତୁ।', '5%: 10% ର ଅଧା।', '50% ଅଧା, 25% ଅଧାର ଅଧା, 75% = 50% + 25%।', 'ଖଣ୍ଡଗୁଡ଼ିକ ଯୋଗ କରନ୍ତୁ: 15% = 10% + 5%, 30% = 3 × 10%।'],
    why: 'ଶତକଡ଼ା ମାନେ “100 ମଧ୍ୟରୁ”। ଶତକଡ଼ାକୁ ସହଜ ଖଣ୍ଡରେ ଭାଙ୍ଗିଲେ ବଡ଼ ଗୁଣନ କରିବାକୁ ପଡ଼େ ନାହିଁ।',
    q: '{n} ର {p}% କେତେ?',
    steps: { half: '{n} ର 50% = {half}।', quarter: '25% = {half} ର ଅଧା = {quarter}।', sum: 'ଯୋଗ କରନ୍ତୁ: {parts} = {ans}।', ten: '{n} ର 10% = {ten}।', minus: '90% = {n} − {ten} = {ans}।', tens: '{p}% = {tens} × {ten} = {val}।', five: '5% = {ten} ର ଅଧା = {five}।', ans: '{n} ର {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'ଅଙ୍କ-ଯୋଗରେ ଯାଞ୍ଚ', sample: '47 × 23 = 1081 ✓', tagline: 'ଯେକୌଣସି ଗୁଣନ କିଛି ସେକେଣ୍ଡରେ ଯାଞ୍ଚ କରନ୍ତୁ।',
    how: ['ଗୋଟିଏ ଅଙ୍କ ରହିବା ଯାଏଁ ସଂଖ୍ୟାର ଅଙ୍କ ବାରମ୍ବାର ଯୋଗ କରନ୍ତୁ (ଯାଞ୍ଚରେ 9 ମାନେ 0)।', 'ଦୁଇ ସଂଖ୍ୟାର ଅଙ୍କ-ଯୋଗକୁ ଗୁଣନ୍ତୁ; ପୁଣି ଗୋଟିଏ ଅଙ୍କକୁ ଆଣନ୍ତୁ।', 'ଉତ୍ତରର ଅଙ୍କ-ଯୋଗ ସହ ମିଳାନ୍ତୁ। ଅଲଗା ହେଲେ ଉତ୍ତର ଭୁଲ।'],
    why: 'ଗୋଟିଏ ସଂଖ୍ୟା ଓ ତା’ର ଅଙ୍କ-ଯୋଗ 9 ଦ୍ୱାରା ଭାଗ କଲେ ସମାନ ଭାଗଶେଷ ରଖନ୍ତି, ଓ ଭାଗଶେଷଗୁଡ଼ିକ ଗୁଣନ ହୁଅନ୍ତି।',
    q: '{n} ର ଅଙ୍କ-ଯୋଗ କେତେ?', q_check: '{a} × {b} = {c} କ’ଣ ଠିକ୍?',
    steps: { start: '{n} ର ଅଙ୍କ-ଯୋଗ ବାହାର କରନ୍ତୁ।', sum: '{label}: {list} = {s}।', single: '{n} ଆଗରୁ ଗୋଟିଏ ଅଙ୍କ।', root: '{n} ର ଅଙ୍କ-ଯୋଗ = {r}।', check: '{a} × {b} = {c} ଯାଞ୍ଚ କରନ୍ତୁ।', roots: 'ଅଙ୍କ-ଯୋଗ: {a} → {ra}, {b} → {rb}।', mulroot: '{ra} × {rb} = {prod} → {rm}।', croot: '{c} ର ଅଙ୍କ-ଯୋଗ → {rc}।', match: '{rm} = {rc}: ଉତ୍ତର ବୋଧହୁଏ ଠିକ୍ ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ଭୁଲ ✗' } }
} };
window.APP_CONTENT.ta = { tricks: {
  mul11: { icon: '✖️', name: '11 ஆல் பெருக்கல்', sample: '52 × 11 = 572', tagline: 'அடுத்தடுத்த இலக்கங்களைக் கூட்டி நடுவில் வையுங்கள்.',
    how: ['கடைசி இலக்கத்தை அப்படியே எழுதுங்கள்.', 'வலமிருந்து இடமாக அடுத்தடுத்த இரண்டு இலக்கங்களைக் கூட்டுங்கள்; கூட்டல் 10 அல்லது அதிகம் என்றால் மீதியை எடுத்துச் செல்லுங்கள்.', 'முன்னால் முதல் இலக்கத்தை (மீதியுடன்) எழுதுங்கள்.'],
    why: '11 = 10 + 1, எனவே n × 11 = n × 10 + n. எண்ணை ஒரு இடம் நகர்த்தி தன்னுடன் கூட்டுவது, அடுத்தடுத்த இலக்கங்களைக் கூட்டுவதே.',
    q: '{a} × {b} எவ்வளவு?',
    steps: { last: '{n} இன் கடைசி இலக்கம் {d}. {d} எழுதுங்கள்.', pair: 'அடுத்த இலக்கங்கள் {x} + {y} = {s}. {w} எழுதுங்கள்.', pair_in: 'அடுத்த இலக்கங்கள் {x} + {y} + மீதி {c} = {s}. {w} எழுதுங்கள்.', pair_out: 'அடுத்த இலக்கங்கள் {x} + {y} = {s}. {w} எழுதுங்கள், மீதி {carry}.', pair_in_out: 'அடுத்த இலக்கங்கள் {x} + {y} + மீதி {c} = {s}. {w} எழுதுங்கள், மீதி {carry}.', first: 'முதல் இலக்கம் {f} முன்னால் வரும்.', first_c: 'முதல் இலக்கம் {f} + மீதி {c} = {s} முன்னால் வரும்.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 ஆல் பெருக்கல்', sample: '47 × 99 = 4653', tagline: 'ஒன்று குறைவு, பிறகு நிரப்பி.',
    how: ['எத்தனை 9 உள்ளதோ அத்தனை இலக்கங்கள் எண்ணில் இருந்தால்: இடப் பகுதி = எண் − 1.', 'வலப் பகுதி = எண் 10, 100 அல்லது 1000 ஆக எவ்வளவு தேவையோ அது.', 'இல்லையெனில்: 10, 100 அல்லது 1000 ஆல் பெருக்கி எண்ணைக் கழியுங்கள்.'],
    why: '99 = 100 − 1, எனவே n × 99 = n × 100 − n. இதைப் பிரித்தால் (n − 1) பிறகு (100 − n) வரும்.',
    q: '{a} × {b} எவ்வளவு?',
    steps: { c_left: '{n} × {nines}: இடப் பகுதி = {n} − 1 = {left}.', c_right: 'வலப் பகுதி = {base} − {n} = {right}.', c_join: '{left}, {right} இரண்டையும் சேர்த்து எழுதுங்கள் → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 ஆல் பெருக்கல்', sample: '48 × 5 = 240', tagline: '10 அல்லது 100 ஆல் பெருக்கி, பாதி அல்லது கால் எடுங்கள்.',
    how: ['× 5: 10 ஆல் பெருக்கி, 2 ஆல் வகுங்கள்.', '× 50: 100 ஆல் பெருக்கி, 2 ஆல் வகுங்கள்.', '× 25: 100 ஆல் பெருக்கி, 4 ஆல் வகுங்கள்.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2, 25 = 100 ÷ 4. பூஜ்ஜியம் சேர்த்துப் பாதியாக்குவது நீண்ட பெருக்கலை விட எளிது.',
    q: '{a} × {b} எவ்வளவு?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 இல் முடியும் எண்களின் வர்க்கம்', sample: '65² = 4225', tagline: 'முன் பகுதியை அடுத்த எண்ணால் பெருக்கி, பிறகு 25.',
    how: ['கடைசி 5 ஐ நீக்குங்கள்; மீதியை a என்று அழையுங்கள்.', 'a ஐ அடுத்த எண் a + 1 ஆல் பெருக்குங்கள்.', 'அதன் பின் 25 எழுதுங்கள்.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. எனவே விடை எப்போதும் a × (a + 1), அதன் பின் 25.',
    q: '{n}² எவ்வளவு?',
    steps: { split: '{n}: 5 ஐ நீக்கினால் மீதி = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} க்குப் பின் 25 எழுதுங்கள் → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'அடிப்படைக்கு அருகில் (நிகிலம்)', sample: '97 × 96 = 9312', tagline: 'எல்லாம் 9 இலிருந்து, கடைசி 10 இலிருந்து: ஒவ்வொரு எண்ணும் 100 இலிருந்து எவ்வளவு தூரம் எனப் பாருங்கள்.',
    how: ['இரண்டு எண்களுக்கும் அருகிலுள்ள அடிப்படையை (10, 100, 1000) தேர்ந்தெடுங்கள்.', 'ஒவ்வொரு எண்ணுக்கும் அடிப்படையிலிருந்து வேறுபாடு காணுங்கள்.', 'இடப் பகுதி: ஒரு எண் + மற்றதன் வேறுபாடு.', 'வலப் பகுதி: இரண்டு வேறுபாடுகளின் பெருக்கல் (அடிப்படையில் எத்தனை பூஜ்ஜியமோ அத்தனை இலக்கம்).'],
    why: '(அடிப்படை + x)(அடிப்படை + y) = அடிப்படை × (அடிப்படை + x + y) + x × y. வேறுபாடுகள் சிறியவை என்றால் பெருக்கல் மிகச் சிறியதாகிறது.',
    q: '{a} × {b} எவ்வளவு?',
    steps: { base: '{a}, {b} க்கு அடிப்படை {base}.', dev: 'வேறுபாடுகள்: {base} இலிருந்து {a} க்கு {da}, {b} க்கு {db}.', cross: 'இடப் பகுதி: {a} {db} = {left}.', prod: 'வலப் பகுதி: ({da}) × ({db}) = {prod}, {k} இலக்கங்களில் எழுதுங்கள்.', borrow: 'வலப் பகுதி {prod} குறை எண்: இடப் பக்கத்திலிருந்து {c} கடன் வாங்குங்கள். இடம் {left} → {l2}, வலம் {prod} + {cb} = {p2}.', carry: 'அடிப்படை {base} க்கு {prod} பெரியது: மீதி {c}, இடம் {left} → {l3}, வலம் {p3}.', join: '{left}, {right} இரண்டையும் சேர்த்து எழுதுங்கள் → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'செங்குத்தும் குறுக்கும் (ஊர்த்வ திர்யக்)', sample: '23 × 14 = 322', tagline: 'எந்தப் பெருக்கலும், ஒவ்வொரு நிரலாக.',
    how: ['வலமிருந்து ஒவ்வொரு நிரலாகச் செய்யுங்கள்.', 'ஒவ்வொரு நிரலிலும் சந்திக்கும் இலக்கங்களின் பெருக்கல்களை (நேராகவும் குறுக்காகவும்) கூட்டுங்கள்.', 'ஒன்றுகள் இலக்கத்தை எழுதி, மீதியை அடுத்த நிரலுக்கு எடுத்துச் செல்லுங்கள்.'],
    why: 'ஒவ்வொரு நிரலும் 10 இன் ஒரே அடுக்கைத் தரும் எல்லா இலக்க ஜோடிகளையும் சேகரிக்கிறது, நீண்ட பெருக்கல் போலவே, ஆனால் ஒரே வரியில்.',
    q: '{a} × {b} எவ்வளவு?',
    steps: { setup: '{a} க்குக் கீழே {b} எழுதுங்கள்.', col: 'நிரல் {i}: {terms} = {sum}. {w} எழுதுங்கள்.', col_in: 'நிரல் {i}: {terms} = {sum}, + மீதி {c} = {total}. {w} எழுதுங்கள்.', col_out: 'நிரல் {i}: {terms} = {sum}. {w} எழுதுங்கள், மீதி {carry}.', col_in_out: 'நிரல் {i}: {terms} = {sum}, + மீதி {c} = {total}. {w} எழுதுங்கள், மீதி {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 ஆல் வகுத்தல்', sample: '2301 ÷ 9 = 255 (6)', tagline: 'இலக்கங்களின் தொடர் கூட்டலே ஈவு.',
    how: ['முதல் இலக்கத்தை அப்படியே எழுதுங்கள்.', 'முந்தைய கூட்டலுடன் அடுத்த இலக்கத்தைக் கூட்டிக்கொண்டே செல்லுங்கள் (கடைசி இலக்கம் வேண்டாம்).', 'இந்தக் கூட்டல்களே ஈவு; எல்லா இலக்கங்களின் கூட்டல் மீதி.', 'மீதி 9 அல்லது அதிகம் என்றால் 9 ஐக் கழித்து ஈவில் 1 கூட்டுங்கள்.'],
    why: '10 = 9 + 1, எனவே 9 ஆல் வகுக்கும்போது ஒவ்வொரு இட மதிப்பும் மீதி 1 தருகிறது. அதனால்தான் இலக்கக் கூட்டல் வேலை செய்கிறது.',
    q: '{n} ÷ 9 எவ்வளவு? (ஈவும் மீதியும்)',
    steps: { first: '{n} இன் முதல் இலக்கம்: {d}.', add: '{prev} + {d} = {s}.', quot: 'கூட்டல்கள் {list} → ஈவு {q}.', rem: 'மீதி = {list} = {r}.', adjust: 'மீதி {r} ≥ 9: ஈவு {q} → {q2}, மீதி {r2}.', ans: '{n} ÷ 9 = {q}, மீதி {r}' } },
  cuberoot: { icon: '🧊', name: 'கனமூலம்', sample: '∛17576 = 26', tagline: 'கடைசி இலக்கம் ஒன்றுகளைத் தரும், முன் பகுதி பத்துகளைத் தரும்.',
    how: ['கடைசி மூன்று இலக்கங்களைப் பிரியுங்கள்.', 'கனத்தின் கடைசி இலக்கம் மூலத்தின் ஒன்றுகள் இலக்கத்தைச் சொல்லும் (2↔8, 3↔7, மற்றவை அதே).', 'முன் பகுதிக்குள் அடங்கும் மிகப் பெரிய கனத்தைக் காணுங்கள்: அதுவே பத்துகள் இலக்கம்.'],
    why: '0–9 இன் கனங்கள் எல்லாம் வெவ்வேறு இலக்கங்களில் முடிகின்றன, இரண்டு இலக்க மூலத்தின் கனம் (10t)³ க்கும் (10t + 10)³ க்கும் இடையில் இருக்கும்.',
    q: '{n} இன் கனமூலம் எவ்வளவு?',
    steps: { split: '{n} → முன் {left}, பின் {right}.', units: 'கடைசி இலக்கம் {last}: {u}³ = {u3} இன் முடிவு {last}, எனவே ஒன்றுகள் = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, எனவே பத்துகள் = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'சதவீத உத்திகள்', sample: '240 இன் 15% = 36', tagline: 'எந்தச் சதவீதத்தையும் 10%, 5%, பாதியிலிருந்து உருவாக்குங்கள்.',
    how: ['10%: 10 ஆல் வகுங்கள்.', '5%: 10% இன் பாதி.', '50% என்பது பாதி, 25% பாதியின் பாதி, 75% = 50% + 25%.', 'துண்டுகளைக் கூட்டுங்கள்: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'சதவீதம் என்றால் “100 இல்”. சதவீதத்தை எளிய துண்டுகளாகப் பிரித்தால் பெரிய பெருக்கல் தேவையில்லை.',
    q: '{n} இன் {p}% எவ்வளவு?',
    steps: { half: '{n} இன் 50% = {half}.', quarter: '25% = {half} இன் பாதி = {quarter}.', sum: 'கூட்டுங்கள்: {parts} = {ans}.', ten: '{n} இன் 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten} இன் பாதி = {five}.', ans: '{n} இன் {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'இலக்கக் கூட்டல் சரிபார்ப்பு', sample: '47 × 23 = 1081 ✓', tagline: 'எந்தப் பெருக்கலையும் சில நொடிகளில் சரிபாருங்கள்.',
    how: ['ஒரே இலக்கம் வரும் வரை எண்ணின் இலக்கங்களை மீண்டும் மீண்டும் கூட்டுங்கள் (சரிபார்ப்பில் 9 என்பது 0).', 'இரண்டு எண்களின் இலக்கக் கூட்டல்களைப் பெருக்கி, மீண்டும் ஒரே இலக்கமாக்குங்கள்.', 'விடையின் இலக்கக் கூட்டலுடன் ஒப்பிடுங்கள். வேறு என்றால் விடை தவறு.'],
    why: 'ஒரு எண்ணும் அதன் இலக்கக் கூட்டலும் 9 ஆல் வகுக்கும்போது ஒரே மீதி தருகின்றன, மீதிகள் பெருக்கலுக்கும் பொருந்தும்.',
    q: '{n} இன் இலக்கக் கூட்டல் எவ்வளவு?', q_check: '{a} × {b} = {c} சரியா?',
    steps: { start: '{n} இன் இலக்கக் கூட்டலைக் காணுங்கள்.', sum: '{label}: {list} = {s}.', single: '{n} ஏற்கனவே ஒரே இலக்கம்.', root: '{n} இன் இலக்கக் கூட்டல் = {r}.', check: '{a} × {b} = {c} ஐச் சரிபாருங்கள்.', roots: 'இலக்கக் கூட்டல்கள்: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} இன் இலக்கக் கூட்டல் → {rc}.', match: '{rm} = {rc}: விடை பெரும்பாலும் சரி ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} தவறு ✗' } }
} };
window.APP_CONTENT.te = { tricks: {
  mul11: { icon: '✖️', name: '11తో గుణకారం', sample: '52 × 11 = 572', tagline: 'పక్కపక్క అంకెలు కూడి మధ్యలో పెట్టండి.',
    how: ['చివరి అంకెను అలాగే రాయండి.', 'కుడి నుంచి ఎడమకు వెళ్తూ పక్కపక్క అంకెలను కూడండి; మొత్తం 10 లేదా ఎక్కువైతే వచ్చేదాన్ని ముందుకు తీసుకెళ్లండి.', 'అన్నిటికంటే ముందు మొదటి అంకె (వచ్చేదానితో) రాయండి.'],
    why: '11 = 10 + 1, కాబట్టి n × 11 = n × 10 + n. సంఖ్యను ఒక స్థానం జరిపి దానికే కలపడం అంటే పక్కపక్క అంకెలు కూడటమే.',
    q: '{a} × {b} ఎంత?',
    steps: { last: '{n} చివరి అంకె {d}. {d} రాయండి.', pair: 'పక్క అంకెలు {x} + {y} = {s}. {w} రాయండి.', pair_in: 'పక్క అంకెలు {x} + {y} + వచ్చేది {c} = {s}. {w} రాయండి.', pair_out: 'పక్క అంకెలు {x} + {y} = {s}. {w} రాయండి, వచ్చేది {carry}.', pair_in_out: 'పక్క అంకెలు {x} + {y} + వచ్చేది {c} = {s}. {w} రాయండి, వచ్చేది {carry}.', first: 'మొదటి అంకె {f} ముందు వస్తుంది.', first_c: 'మొదటి అంకె {f} + వచ్చేది {c} = {s} ముందు వస్తుంది.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999తో గుణకారం', sample: '47 × 99 = 4653', tagline: 'ఒకటి తక్కువ, తర్వాత పూరకం.',
    how: ['ఎన్ని 9లు ఉన్నాయో సంఖ్యలో అన్ని అంకెలు ఉంటే: ఎడమ భాగం = సంఖ్య − 1.', 'కుడి భాగం = సంఖ్య 10, 100 లేదా 1000 కావడానికి ఎంత కావాలో అది.', 'లేకపోతే: 10, 100 లేదా 1000తో గుణించి సంఖ్యను తీసివేయండి.'],
    why: '99 = 100 − 1, కాబట్టి n × 99 = n × 100 − n. దీన్ని విడదీస్తే (n − 1) తర్వాత (100 − n) వస్తుంది.',
    q: '{a} × {b} ఎంత?',
    steps: { c_left: '{n} × {nines}: ఎడమ భాగం = {n} − 1 = {left}.', c_right: 'కుడి భాగం = {base} − {n} = {right}.', c_join: '{left}, {right} కలిపి రాయండి → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50తో గుణకారం', sample: '48 × 5 = 240', tagline: '10 లేదా 100తో గుణించి, సగం లేదా పావు చేయండి.',
    how: ['× 5: 10తో గుణించి, 2తో భాగించండి.', '× 50: 100తో గుణించి, 2తో భాగించండి.', '× 25: 100తో గుణించి, 4తో భాగించండి.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2, 25 = 100 ÷ 4. సున్నాలు చేర్చి సగం చేయడం పొడవైన గుణకారం కంటే సులభం.',
    q: '{a} × {b} ఎంత?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5తో ముగిసే సంఖ్యల వర్గాలు', sample: '65² = 4225', tagline: 'ముందు భాగాన్ని తర్వాతి సంఖ్యతో గుణించి, తర్వాత 25.',
    how: ['చివరి 5ను తీసేయండి; మిగిలినదాన్ని a అనండి.', 'aను తర్వాతి సంఖ్య a + 1తో గుణించండి.', 'దాని తర్వాత 25 రాయండి.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. కాబట్టి జవాబు ఎప్పుడూ a × (a + 1), తర్వాత 25.',
    q: '{n}² ఎంత?',
    steps: { split: '{n}: 5 తీసేస్తే మిగిలింది = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} తర్వాత 25 రాయండి → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'ఆధారానికి దగ్గర (నిఖిలం)', sample: '97 × 96 = 9312', tagline: 'అన్నీ 9 నుంచి, చివరిది 10 నుంచి: ప్రతి సంఖ్య 100 నుంచి ఎంత దూరమో చూడండి.',
    how: ['రెండు సంఖ్యలకూ దగ్గరి ఆధారం (10, 100, 1000) ఎంచుకోండి.', 'ప్రతి సంఖ్యకు ఆధారం నుంచి తేడా కనుగొనండి.', 'ఎడమ భాగం: ఒక సంఖ్య + మరో దాని తేడా.', 'కుడి భాగం: రెండు తేడాల గుణకారం (ఆధారంలో ఎన్ని సున్నాలో అన్ని అంకెలు).'],
    why: '(ఆధారం + x)(ఆధారం + y) = ఆధారం × (ఆధారం + x + y) + x × y. తేడాలు చిన్నవైతే గుణకారం చాలా చిన్నదవుతుంది.',
    q: '{a} × {b} ఎంత?',
    steps: { base: '{a}, {b}లకు ఆధారం {base}.', dev: 'తేడాలు: {base} నుంచి {a}కి {da}, {b}కి {db}.', cross: 'ఎడమ భాగం: {a} {db} = {left}.', prod: 'కుడి భాగం: ({da}) × ({db}) = {prod}, {k} అంకెల్లో రాయండి.', borrow: 'కుడి భాగం {prod} రుణాత్మకం: ఎడమ నుంచి {c} అప్పు తీసుకోండి. ఎడమ {left} → {l2}, కుడి {prod} + {cb} = {p2}.', carry: 'ఆధారం {base}కి {prod} పెద్దది: వచ్చేది {c}, ఎడమ {left} → {l3}, కుడి {p3}.', join: '{left}, {right} కలిపి రాయండి → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'నిలువుగా అడ్డంగా (ఊర్ధ్వ తిర్యక్)', sample: '23 × 14 = 322', tagline: 'ఏ గుణకారమైనా, ఒక్కో నిలువు వరుసగా.',
    how: ['కుడి నుంచి ఒక్కో నిలువు వరుసగా చేయండి.', 'ప్రతి వరుసలో కలిసే అంకెల గుణకారాలను (నిలువుగా, అడ్డంగా) కూడండి.', 'ఒకట్ల అంకెను రాసి, మిగిలినదాన్ని తర్వాతి వరుసకు తీసుకెళ్లండి.'],
    why: 'ప్రతి వరుస 10 యొక్క ఒకే ఘాతాన్ని ఇచ్చే అన్ని అంకెల జతలను సేకరిస్తుంది, పొడవైన గుణకారంలాగే, కానీ ఒకే వరుసలో.',
    q: '{a} × {b} ఎంత?',
    steps: { setup: '{a} కింద {b} రాయండి.', col: 'వరుస {i}: {terms} = {sum}. {w} రాయండి.', col_in: 'వరుస {i}: {terms} = {sum}, + వచ్చేది {c} = {total}. {w} రాయండి.', col_out: 'వరుస {i}: {terms} = {sum}. {w} రాయండి, వచ్చేది {carry}.', col_in_out: 'వరుస {i}: {terms} = {sum}, + వచ్చేది {c} = {total}. {w} రాయండి, వచ్చేది {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9తో భాగహారం', sample: '2301 ÷ 9 = 255 (6)', tagline: 'అంకెల వరుస మొత్తాలే భాగఫలం.',
    how: ['మొదటి అంకెను అలాగే రాయండి.', 'ముందరి మొత్తానికి తర్వాతి అంకెను కలుపుతూ వెళ్లండి (చివరి అంకె వదిలేయండి).', 'ఈ మొత్తాలే భాగఫలం; అన్ని అంకెల మొత్తం శేషం.', 'శేషం 9 లేదా ఎక్కువైతే 9 తీసివేసి భాగఫలానికి 1 కలపండి.'],
    why: '10 = 9 + 1, కాబట్టి 9తో భాగిస్తే ప్రతి స్థాన విలువ శేషం 1 ఇస్తుంది. అందుకే అంకెల మొత్తం పని చేస్తుంది.',
    q: '{n} ÷ 9 ఎంత? (భాగఫలం, శేషం)',
    steps: { first: '{n} మొదటి అంకె: {d}.', add: '{prev} + {d} = {s}.', quot: 'మొత్తాలు {list} → భాగఫలం {q}.', rem: 'శేషం = {list} = {r}.', adjust: 'శేషం {r} ≥ 9: భాగఫలం {q} → {q2}, శేషం {r2}.', ans: '{n} ÷ 9 = {q}, శేషం {r}' } },
  cuberoot: { icon: '🧊', name: 'ఘనమూలాలు', sample: '∛17576 = 26', tagline: 'చివరి అంకె ఒకట్లను, ముందు భాగం పదులను ఇస్తుంది.',
    how: ['చివరి మూడు అంకెలను వేరు చేయండి.', 'ఘనం చివరి అంకె మూలం ఒకట్ల అంకెను చెబుతుంది (2↔8, 3↔7, మిగతావి అవే).', 'ముందు భాగంలో పట్టే అతి పెద్ద ఘనాన్ని కనుగొనండి: అదే పదుల అంకె.'],
    why: '0–9 ఘనాలు అన్నీ వేర్వేరు అంకెలతో ముగుస్తాయి, రెండంకెల మూలం ఘనం (10t)³, (10t + 10)³ మధ్య ఉంటుంది.',
    q: '{n} ఘనమూలం ఎంత?',
    steps: { split: '{n} → ముందు {left}, వెనుక {right}.', units: 'చివరి అంకె {last}: {u}³ = {u3} చివర {last}, కాబట్టి ఒకట్లు = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, కాబట్టి పదులు = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'శాతం చిట్కాలు', sample: '240లో 15% = 36', tagline: 'ఏ శాతాన్నైనా 10%, 5%, సగం నుంచి తయారుచేయండి.',
    how: ['10%: 10తో భాగించండి.', '5%: 10%లో సగం.', '50% అంటే సగం, 25% సగంలో సగం, 75% = 50% + 25%.', 'ముక్కలను కూడండి: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'శాతం అంటే “100లో”. శాతాన్ని సులభమైన ముక్కలుగా విడదీస్తే పెద్ద గుణకారం అవసరం లేదు.',
    q: '{n}లో {p}% ఎంత?',
    steps: { half: '{n}లో 50% = {half}.', quarter: '25% = {half}లో సగం = {quarter}.', sum: 'కూడండి: {parts} = {ans}.', ten: '{n}లో 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten}లో సగం = {five}.', ans: '{n}లో {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'అంకెల మొత్తంతో తనిఖీ', sample: '47 × 23 = 1081 ✓', tagline: 'ఏ గుణకారాన్నైనా కొన్ని సెకన్లలో తనిఖీ చేయండి.',
    how: ['ఒకే అంకె మిగిలే వరకు సంఖ్య అంకెలను మళ్లీ మళ్లీ కూడండి (తనిఖీలో 9 అంటే 0).', 'రెండు సంఖ్యల అంకెల మొత్తాలను గుణించి, మళ్లీ ఒకే అంకెకు తగ్గించండి.', 'జవాబు అంకెల మొత్తంతో పోల్చండి. వేరుగా ఉంటే జవాబు తప్పు.'],
    why: 'ఒక సంఖ్య, దాని అంకెల మొత్తం 9తో భాగిస్తే ఒకే శేషం ఇస్తాయి, శేషాలు గుణకారానికీ వర్తిస్తాయి.',
    q: '{n} అంకెల మొత్తం ఎంత?', q_check: '{a} × {b} = {c} సరైనదేనా?',
    steps: { start: '{n} అంకెల మొత్తం కనుగొనండి.', sum: '{label}: {list} = {s}.', single: '{n} ఇప్పటికే ఒకే అంకె.', root: '{n} అంకెల మొత్తం = {r}.', check: '{a} × {b} = {c} తనిఖీ చేయండి.', roots: 'అంకెల మొత్తాలు: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} అంకెల మొత్తం → {rc}.', match: '{rm} = {rc}: జవాబు బహుశా సరైనది ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} తప్పు ✗' } }
} };
window.APP_CONTENT.kn = { tricks: {
  mul11: { icon: '✖️', name: '11 ರಿಂದ ಗುಣಾಕಾರ', sample: '52 × 11 = 572', tagline: 'ಪಕ್ಕಪಕ್ಕದ ಅಂಕೆಗಳನ್ನು ಕೂಡಿಸಿ ಮಧ್ಯದಲ್ಲಿ ಇಡಿ.',
    how: ['ಕೊನೆಯ ಅಂಕೆಯನ್ನು ಹಾಗೆಯೇ ಬರೆಯಿರಿ.', 'ಬಲದಿಂದ ಎಡಕ್ಕೆ ಹೋಗುತ್ತಾ ಪಕ್ಕಪಕ್ಕದ ಅಂಕೆಗಳನ್ನು ಕೂಡಿಸಿ; ಮೊತ್ತ 10 ಅಥವಾ ಹೆಚ್ಚಾದರೆ ಶೇಷವನ್ನು ಮುಂದಕ್ಕೆ ಒಯ್ಯಿರಿ.', 'ಎಲ್ಲಕ್ಕಿಂತ ಮುಂದೆ ಮೊದಲ ಅಂಕೆ (ಮತ್ತು ಶೇಷ) ಬರೆಯಿರಿ.'],
    why: '11 = 10 + 1, ಆದ್ದರಿಂದ n × 11 = n × 10 + n. ಸಂಖ್ಯೆಯನ್ನು ಒಂದು ಸ್ಥಾನ ಸರಿಸಿ ಅದಕ್ಕೇ ಕೂಡಿಸುವುದು ಪಕ್ಕದ ಅಂಕೆಗಳನ್ನು ಕೂಡಿಸಿದಂತೆಯೇ.',
    q: '{a} × {b} ಎಷ್ಟು?',
    steps: { last: '{n} ರ ಕೊನೆಯ ಅಂಕೆ {d}. {d} ಬರೆಯಿರಿ.', pair: 'ಪಕ್ಕದ ಅಂಕೆಗಳು {x} + {y} = {s}. {w} ಬರೆಯಿರಿ.', pair_in: 'ಪಕ್ಕದ ಅಂಕೆಗಳು {x} + {y} + ಶೇಷ {c} = {s}. {w} ಬರೆಯಿರಿ.', pair_out: 'ಪಕ್ಕದ ಅಂಕೆಗಳು {x} + {y} = {s}. {w} ಬರೆಯಿರಿ, ಶೇಷ {carry}.', pair_in_out: 'ಪಕ್ಕದ ಅಂಕೆಗಳು {x} + {y} + ಶೇಷ {c} = {s}. {w} ಬರೆಯಿರಿ, ಶೇಷ {carry}.', first: 'ಮೊದಲ ಅಂಕೆ {f} ಮುಂದೆ ಬರುತ್ತದೆ.', first_c: 'ಮೊದಲ ಅಂಕೆ {f} + ಶೇಷ {c} = {s} ಮುಂದೆ ಬರುತ್ತದೆ.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 ರಿಂದ ಗುಣಾಕಾರ', sample: '47 × 99 = 4653', tagline: 'ಒಂದು ಕಡಿಮೆ, ನಂತರ ಪೂರಕ.',
    how: ['ಎಷ್ಟು 9 ಇವೆಯೋ ಅಷ್ಟೇ ಅಂಕೆಗಳು ಸಂಖ್ಯೆಯಲ್ಲಿದ್ದರೆ: ಎಡ ಭಾಗ = ಸಂಖ್ಯೆ − 1.', 'ಬಲ ಭಾಗ = ಸಂಖ್ಯೆ 10, 100 ಅಥವಾ 1000 ಆಗಲು ಬೇಕಾದಷ್ಟು.', 'ಇಲ್ಲದಿದ್ದರೆ: 10, 100 ಅಥವಾ 1000 ರಿಂದ ಗುಣಿಸಿ ಸಂಖ್ಯೆಯನ್ನು ಕಳೆಯಿರಿ.'],
    why: '99 = 100 − 1, ಆದ್ದರಿಂದ n × 99 = n × 100 − n. ಇದನ್ನು ಒಡೆದರೆ (n − 1) ನಂತರ (100 − n) ಬರುತ್ತದೆ.',
    q: '{a} × {b} ಎಷ್ಟು?',
    steps: { c_left: '{n} × {nines}: ಎಡ ಭಾಗ = {n} − 1 = {left}.', c_right: 'ಬಲ ಭಾಗ = {base} − {n} = {right}.', c_join: '{left} ಮತ್ತು {right} ಜೊತೆಗೆ ಬರೆಯಿರಿ → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 ರಿಂದ ಗುಣಾಕಾರ', sample: '48 × 5 = 240', tagline: '10 ಅಥವಾ 100 ರಿಂದ ಗುಣಿಸಿ, ಅರ್ಧ ಅಥವಾ ಕಾಲು ಮಾಡಿ.',
    how: ['× 5: 10 ರಿಂದ ಗುಣಿಸಿ, 2 ರಿಂದ ಭಾಗಿಸಿ.', '× 50: 100 ರಿಂದ ಗುಣಿಸಿ, 2 ರಿಂದ ಭಾಗಿಸಿ.', '× 25: 100 ರಿಂದ ಗುಣಿಸಿ, 4 ರಿಂದ ಭಾಗಿಸಿ.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2, 25 = 100 ÷ 4. ಸೊನ್ನೆ ಸೇರಿಸಿ ಅರ್ಧ ಮಾಡುವುದು ಉದ್ದ ಗುಣಾಕಾರಕ್ಕಿಂತ ಸುಲಭ.',
    q: '{a} × {b} ಎಷ್ಟು?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 ರಲ್ಲಿ ಕೊನೆಯಾಗುವ ಸಂಖ್ಯೆಗಳ ವರ್ಗ', sample: '65² = 4225', tagline: 'ಮುಂದಿನ ಭಾಗವನ್ನು ಅದರ ಮುಂದಿನ ಸಂಖ್ಯೆಯಿಂದ ಗುಣಿಸಿ, ನಂತರ 25.',
    how: ['ಕೊನೆಯ 5 ತೆಗೆಯಿರಿ; ಉಳಿದದ್ದನ್ನು a ಎನ್ನಿ.', 'a ಅನ್ನು ಮುಂದಿನ ಸಂಖ್ಯೆ a + 1 ರಿಂದ ಗುಣಿಸಿ.', 'ಅದರ ನಂತರ 25 ಬರೆಯಿರಿ.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. ಆದ್ದರಿಂದ ಉತ್ತರ ಯಾವಾಗಲೂ a × (a + 1), ನಂತರ 25.',
    q: '{n}² ಎಷ್ಟು?',
    steps: { split: '{n}: 5 ತೆಗೆದರೆ ಉಳಿದದ್ದು = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} ನಂತರ 25 ಬರೆಯಿರಿ → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'ಆಧಾರದ ಹತ್ತಿರ (ನಿಖಿಲಂ)', sample: '97 × 96 = 9312', tagline: 'ಎಲ್ಲವೂ 9 ರಿಂದ, ಕೊನೆಯದು 10 ರಿಂದ: ಪ್ರತಿ ಸಂಖ್ಯೆ 100 ರಿಂದ ಎಷ್ಟು ದೂರ ಎಂದು ನೋಡಿ.',
    how: ['ಎರಡೂ ಸಂಖ್ಯೆಗಳ ಹತ್ತಿರದ ಆಧಾರ (10, 100, 1000) ಆರಿಸಿ.', 'ಪ್ರತಿ ಸಂಖ್ಯೆಗೆ ಆಧಾರದಿಂದ ವ್ಯತ್ಯಾಸ ಕಂಡುಹಿಡಿಯಿರಿ.', 'ಎಡ ಭಾಗ: ಒಂದು ಸಂಖ್ಯೆ + ಇನ್ನೊಂದರ ವ್ಯತ್ಯಾಸ.', 'ಬಲ ಭಾಗ: ಎರಡು ವ್ಯತ್ಯಾಸಗಳ ಗುಣಲಬ್ಧ (ಆಧಾರದಲ್ಲಿ ಎಷ್ಟು ಸೊನ್ನೆಗಳೋ ಅಷ್ಟು ಅಂಕೆ).'],
    why: '(ಆಧಾರ + x)(ಆಧಾರ + y) = ಆಧಾರ × (ಆಧಾರ + x + y) + x × y. ವ್ಯತ್ಯಾಸ ಚಿಕ್ಕದಾದರೆ ಗುಣಾಕಾರ ತುಂಬಾ ಚಿಕ್ಕದಾಗುತ್ತದೆ.',
    q: '{a} × {b} ಎಷ್ಟು?',
    steps: { base: '{a}, {b} ಗೆ ಆಧಾರ {base}.', dev: 'ವ್ಯತ್ಯಾಸ: {base} ರಿಂದ {a} ಗೆ {da}, {b} ಗೆ {db}.', cross: 'ಎಡ ಭಾಗ: {a} {db} = {left}.', prod: 'ಬಲ ಭಾಗ: ({da}) × ({db}) = {prod}, {k} ಅಂಕೆಗಳಲ್ಲಿ ಬರೆಯಿರಿ.', borrow: 'ಬಲ ಭಾಗ {prod} ಋಣ: ಎಡದಿಂದ {c} ಸಾಲ ತೆಗೆದುಕೊಳ್ಳಿ. ಎಡ {left} → {l2}, ಬಲ {prod} + {cb} = {p2}.', carry: 'ಆಧಾರ {base} ಗೆ {prod} ದೊಡ್ಡದು: ಶೇಷ {c}, ಎಡ {left} → {l3}, ಬಲ {p3}.', join: '{left} ಮತ್ತು {right} ಜೊತೆಗೆ ಬರೆಯಿರಿ → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ಲಂಬ ಮತ್ತು ಅಡ್ಡ (ಊರ್ಧ್ವ ತಿರ್ಯಕ್)', sample: '23 × 14 = 322', tagline: 'ಯಾವುದೇ ಗುಣಾಕಾರ, ಒಂದೊಂದು ಕಾಲಂ ಆಗಿ.',
    how: ['ಬಲದಿಂದ ಒಂದೊಂದು ಕಾಲಂ ಮಾಡಿ.', 'ಪ್ರತಿ ಕಾಲಂನಲ್ಲಿ ಸಂಧಿಸುವ ಅಂಕೆಗಳ ಗುಣಲಬ್ಧಗಳನ್ನು (ಲಂಬ ಮತ್ತು ಅಡ್ಡ) ಕೂಡಿಸಿ.', 'ಬಿಡಿ ಅಂಕೆ ಬರೆದು, ಉಳಿದದ್ದನ್ನು ಮುಂದಿನ ಕಾಲಂಗೆ ಒಯ್ಯಿರಿ.'],
    why: 'ಪ್ರತಿ ಕಾಲಂ 10 ರ ಒಂದೇ ಘಾತ ಕೊಡುವ ಎಲ್ಲಾ ಅಂಕೆ ಜೋಡಿಗಳನ್ನು ಸೇರಿಸುತ್ತದೆ, ಉದ್ದ ಗುಣಾಕಾರದಂತೆಯೇ, ಆದರೆ ಒಂದೇ ಸಾಲಿನಲ್ಲಿ.',
    q: '{a} × {b} ಎಷ್ಟು?',
    steps: { setup: '{a} ಕೆಳಗೆ {b} ಬರೆಯಿರಿ.', col: 'ಕಾಲಂ {i}: {terms} = {sum}. {w} ಬರೆಯಿರಿ.', col_in: 'ಕಾಲಂ {i}: {terms} = {sum}, + ಶೇಷ {c} = {total}. {w} ಬರೆಯಿರಿ.', col_out: 'ಕಾಲಂ {i}: {terms} = {sum}. {w} ಬರೆಯಿರಿ, ಶೇಷ {carry}.', col_in_out: 'ಕಾಲಂ {i}: {terms} = {sum}, + ಶೇಷ {c} = {total}. {w} ಬರೆಯಿರಿ, ಶೇಷ {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 ರಿಂದ ಭಾಗಾಕಾರ', sample: '2301 ÷ 9 = 255 (6)', tagline: 'ಅಂಕೆಗಳ ಸಾಗುವ ಮೊತ್ತಗಳೇ ಭಾಗಲಬ್ಧ.',
    how: ['ಮೊದಲ ಅಂಕೆಯನ್ನು ಹಾಗೆಯೇ ಬರೆಯಿರಿ.', 'ಹಿಂದಿನ ಮೊತ್ತಕ್ಕೆ ಮುಂದಿನ ಅಂಕೆಯನ್ನು ಕೂಡಿಸುತ್ತಾ ಹೋಗಿ (ಕೊನೆಯ ಅಂಕೆ ಬಿಡಿ).', 'ಈ ಮೊತ್ತಗಳೇ ಭಾಗಲಬ್ಧ; ಎಲ್ಲಾ ಅಂಕೆಗಳ ಮೊತ್ತ ಶೇಷ.', 'ಶೇಷ 9 ಅಥವಾ ಹೆಚ್ಚಾದರೆ 9 ಕಳೆದು ಭಾಗಲಬ್ಧಕ್ಕೆ 1 ಸೇರಿಸಿ.'],
    why: '10 = 9 + 1, ಆದ್ದರಿಂದ 9 ರಿಂದ ಭಾಗಿಸಿದಾಗ ಪ್ರತಿ ಸ್ಥಾನಬೆಲೆ ಶೇಷ 1 ಕೊಡುತ್ತದೆ. ಅದಕ್ಕೇ ಅಂಕೆಗಳ ಮೊತ್ತ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
    q: '{n} ÷ 9 ಎಷ್ಟು? (ಭಾಗಲಬ್ಧ ಮತ್ತು ಶೇಷ)',
    steps: { first: '{n} ರ ಮೊದಲ ಅಂಕೆ: {d}.', add: '{prev} + {d} = {s}.', quot: 'ಮೊತ್ತಗಳು {list} → ಭಾಗಲಬ್ಧ {q}.', rem: 'ಶೇಷ = {list} = {r}.', adjust: 'ಶೇಷ {r} ≥ 9: ಭಾಗಲಬ್ಧ {q} → {q2}, ಶೇಷ {r2}.', ans: '{n} ÷ 9 = {q}, ಶೇಷ {r}' } },
  cuberoot: { icon: '🧊', name: 'ಘನಮೂಲ', sample: '∛17576 = 26', tagline: 'ಕೊನೆಯ ಅಂಕೆಯಿಂದ ಬಿಡಿ, ಮುಂದಿನ ಭಾಗದಿಂದ ಹತ್ತು.',
    how: ['ಕೊನೆಯ ಮೂರು ಅಂಕೆಗಳನ್ನು ಬೇರ್ಪಡಿಸಿ.', 'ಘನದ ಕೊನೆಯ ಅಂಕೆ ಮೂಲದ ಬಿಡಿ ಅಂಕೆಯನ್ನು ಹೇಳುತ್ತದೆ (2↔8, 3↔7, ಉಳಿದವು ಅದೇ).', 'ಮುಂದಿನ ಭಾಗದೊಳಗೆ ಹಿಡಿಯುವ ಅತಿ ದೊಡ್ಡ ಘನ ಹುಡುಕಿ: ಅದೇ ಹತ್ತರ ಅಂಕೆ.'],
    why: '0–9 ರ ಘನಗಳು ಎಲ್ಲವೂ ಬೇರೆ ಬೇರೆ ಅಂಕೆಗಳಲ್ಲಿ ಕೊನೆಯಾಗುತ್ತವೆ, ಎರಡಂಕಿಯ ಮೂಲದ ಘನ (10t)³ ಮತ್ತು (10t + 10)³ ನಡುವೆ ಇರುತ್ತದೆ.',
    q: '{n} ರ ಘನಮೂಲ ಎಷ್ಟು?',
    steps: { split: '{n} → ಮುಂದೆ {left}, ಹಿಂದೆ {right}.', units: 'ಕೊನೆಯ ಅಂಕೆ {last}: {u}³ = {u3} ಕೊನೆ {last}, ಆದ್ದರಿಂದ ಬಿಡಿ = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, ಆದ್ದರಿಂದ ಹತ್ತು = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'ಶೇಕಡಾ ತಂತ್ರಗಳು', sample: '240 ರ 15% = 36', tagline: 'ಯಾವುದೇ ಶೇಕಡಾವನ್ನು 10%, 5% ಮತ್ತು ಅರ್ಧದಿಂದ ಕಟ್ಟಿ.',
    how: ['10%: 10 ರಿಂದ ಭಾಗಿಸಿ.', '5%: 10% ರ ಅರ್ಧ.', '50% ಅರ್ಧ, 25% ಅರ್ಧದ ಅರ್ಧ, 75% = 50% + 25%.', 'ತುಂಡುಗಳನ್ನು ಕೂಡಿಸಿ: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'ಶೇಕಡಾ ಎಂದರೆ “100 ರಲ್ಲಿ”. ಶೇಕಡಾವನ್ನು ಸುಲಭ ತುಂಡುಗಳಾಗಿ ಒಡೆದರೆ ದೊಡ್ಡ ಗುಣಾಕಾರ ಬೇಕಿಲ್ಲ.',
    q: '{n} ರ {p}% ಎಷ್ಟು?',
    steps: { half: '{n} ರ 50% = {half}.', quarter: '25% = {half} ರ ಅರ್ಧ = {quarter}.', sum: 'ಕೂಡಿಸಿ: {parts} = {ans}.', ten: '{n} ರ 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten} ರ ಅರ್ಧ = {five}.', ans: '{n} ರ {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'ಅಂಕೆ ಮೊತ್ತದ ಪರಿಶೀಲನೆ', sample: '47 × 23 = 1081 ✓', tagline: 'ಯಾವುದೇ ಗುಣಾಕಾರವನ್ನು ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.',
    how: ['ಒಂದೇ ಅಂಕೆ ಉಳಿಯುವವರೆಗೆ ಸಂಖ್ಯೆಯ ಅಂಕೆಗಳನ್ನು ಮತ್ತೆ ಮತ್ತೆ ಕೂಡಿಸಿ (ಪರಿಶೀಲನೆಯಲ್ಲಿ 9 ಎಂದರೆ 0).', 'ಎರಡೂ ಸಂಖ್ಯೆಗಳ ಅಂಕೆ ಮೊತ್ತಗಳನ್ನು ಗುಣಿಸಿ; ಮತ್ತೆ ಒಂದೇ ಅಂಕೆಗೆ ಇಳಿಸಿ.', 'ಉತ್ತರದ ಅಂಕೆ ಮೊತ್ತದೊಂದಿಗೆ ಹೋಲಿಸಿ. ಬೇರೆಯಾದರೆ ಉತ್ತರ ತಪ್ಪು.'],
    why: 'ಒಂದು ಸಂಖ್ಯೆ ಮತ್ತು ಅದರ ಅಂಕೆ ಮೊತ್ತ 9 ರಿಂದ ಭಾಗಿಸಿದಾಗ ಒಂದೇ ಶೇಷ ಕೊಡುತ್ತವೆ, ಮತ್ತು ಶೇಷಗಳು ಗುಣಾಕಾರಕ್ಕೂ ಹೊಂದುತ್ತವೆ.',
    q: '{n} ರ ಅಂಕೆ ಮೊತ್ತ ಎಷ್ಟು?', q_check: '{a} × {b} = {c} ಸರಿಯೇ?',
    steps: { start: '{n} ರ ಅಂಕೆ ಮೊತ್ತ ಕಂಡುಹಿಡಿಯಿರಿ.', sum: '{label}: {list} = {s}.', single: '{n} ಈಗಾಗಲೇ ಒಂದೇ ಅಂಕೆ.', root: '{n} ರ ಅಂಕೆ ಮೊತ್ತ = {r}.', check: '{a} × {b} = {c} ಪರಿಶೀಲಿಸಿ.', roots: 'ಅಂಕೆ ಮೊತ್ತಗಳು: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} ರ ಅಂಕೆ ಮೊತ್ತ → {rc}.', match: '{rm} = {rc}: ಉತ್ತರ ಬಹುಶಃ ಸರಿ ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} ತಪ್ಪು ✗' } }
} };
window.APP_CONTENT.ml = { tricks: {
  mul11: { icon: '✖️', name: '11 കൊണ്ട് ഗുണനം', sample: '52 × 11 = 572', tagline: 'അടുത്തടുത്ത അക്കങ്ങൾ കൂട്ടി നടുവിൽ വയ്ക്കുക.',
    how: ['അവസാന അക്കം അതുപോലെ എഴുതുക.', 'വലത്തുനിന്ന് ഇടത്തേക്ക് നീങ്ങി അടുത്തടുത്ത അക്കങ്ങൾ കൂട്ടുക; തുക 10 അല്ലെങ്കിൽ കൂടുതലാണെങ്കിൽ ശിഷ്ടം കൊണ്ടുപോകുക.', 'ഏറ്റവും മുന്നിൽ ആദ്യ അക്കം (ശിഷ്ടവും) എഴുതുക.'],
    why: '11 = 10 + 1, അതിനാൽ n × 11 = n × 10 + n. സംഖ്യയെ ഒരു സ്ഥാനം നീക്കി അതിനോടുതന്നെ കൂട്ടുന്നത് അടുത്ത അക്കങ്ങൾ കൂട്ടുന്നതുതന്നെ.',
    q: '{a} × {b} എത്ര?',
    steps: { last: '{n} ന്റെ അവസാന അക്കം {d}. {d} എഴുതുക.', pair: 'അടുത്ത അക്കങ്ങൾ {x} + {y} = {s}. {w} എഴുതുക.', pair_in: 'അടുത്ത അക്കങ്ങൾ {x} + {y} + ശിഷ്ടം {c} = {s}. {w} എഴുതുക.', pair_out: 'അടുത്ത അക്കങ്ങൾ {x} + {y} = {s}. {w} എഴുതുക, ശിഷ്ടം {carry}.', pair_in_out: 'അടുത്ത അക്കങ്ങൾ {x} + {y} + ശിഷ്ടം {c} = {s}. {w} എഴുതുക, ശിഷ്ടം {carry}.', first: 'ആദ്യ അക്കം {f} മുന്നിൽ വരും.', first_c: 'ആദ്യ അക്കം {f} + ശിഷ്ടം {c} = {s} മുന്നിൽ വരും.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9, 99, 999 കൊണ്ട് ഗുണനം', sample: '47 × 99 = 4653', tagline: 'ഒന്ന് കുറവ്, പിന്നെ പൂരകം.',
    how: ['എത്ര 9 ഉണ്ടോ അത്രയും അക്കങ്ങൾ സംഖ്യയിലുണ്ടെങ്കിൽ: ഇടത് ഭാഗം = സംഖ്യ − 1.', 'വലത് ഭാഗം = സംഖ്യ 10, 100 അല്ലെങ്കിൽ 1000 ആകാൻ വേണ്ടത്.', 'അല്ലെങ്കിൽ: 10, 100 അല്ലെങ്കിൽ 1000 കൊണ്ട് ഗുണിച്ച് സംഖ്യ കുറയ്ക്കുക.'],
    why: '99 = 100 − 1, അതിനാൽ n × 99 = n × 100 − n. ഇത് പിരിച്ചാൽ (n − 1) കഴിഞ്ഞ് (100 − n) വരും.',
    q: '{a} × {b} എത്ര?',
    steps: { c_left: '{n} × {nines}: ഇടത് ഭാഗം = {n} − 1 = {left}.', c_right: 'വലത് ഭാഗം = {base} − {n} = {right}.', c_join: '{left}, {right} ചേർത്ത് എഴുതുക → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5, 25, 50 കൊണ്ട് ഗുണനം', sample: '48 × 5 = 240', tagline: '10 അല്ലെങ്കിൽ 100 കൊണ്ട് ഗുണിച്ച്, പകുതിയോ കാലോ ആക്കുക.',
    how: ['× 5: 10 കൊണ്ട് ഗുണിച്ച്, 2 കൊണ്ട് ഹരിക്കുക.', '× 50: 100 കൊണ്ട് ഗുണിച്ച്, 2 കൊണ്ട് ഹരിക്കുക.', '× 25: 100 കൊണ്ട് ഗുണിച്ച്, 4 കൊണ്ട് ഹരിക്കുക.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2, 25 = 100 ÷ 4. പൂജ്യം ചേർത്ത് പകുതിയാക്കുന്നത് നീണ്ട ഗുണനത്തേക്കാൾ എളുപ്പം.',
    q: '{a} × {b} എത്ര?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 ൽ അവസാനിക്കുന്നവയുടെ വർഗം', sample: '65² = 4225', tagline: 'മുൻഭാഗത്തെ അടുത്ത സംഖ്യകൊണ്ട് ഗുണിച്ച്, പിന്നെ 25.',
    how: ['അവസാനത്തെ 5 മാറ്റുക; ബാക്കിയുള്ളതിനെ a എന്ന് വിളിക്കുക.', 'a യെ അടുത്ത സംഖ്യ a + 1 കൊണ്ട് ഗുണിക്കുക.', 'അതിനുശേഷം 25 എഴുതുക.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. അതിനാൽ ഉത്തരം എപ്പോഴും a × (a + 1), പിന്നെ 25.',
    q: '{n}² എത്ര?',
    steps: { split: '{n}: 5 മാറ്റിയാൽ ബാക്കി = {a}.', mul: '{a} × {a1} = {prod}.', join: '{prod} കഴിഞ്ഞ് 25 എഴുതുക → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'അടിസ്ഥാനത്തിനടുത്ത് (നിഖിലം)', sample: '97 × 96 = 9312', tagline: 'എല്ലാം 9 ൽ നിന്ന്, അവസാനത്തേത് 10 ൽ നിന്ന്: ഓരോ സംഖ്യയും 100 ൽ നിന്ന് എത്ര ദൂരെയെന്ന് നോക്കുക.',
    how: ['രണ്ട് സംഖ്യകൾക്കും അടുത്തുള്ള അടിസ്ഥാനം (10, 100, 1000) തിരഞ്ഞെടുക്കുക.', 'ഓരോ സംഖ്യയ്ക്കും അടിസ്ഥാനത്തിൽ നിന്നുള്ള വ്യത്യാസം കാണുക.', 'ഇടത് ഭാഗം: ഒരു സംഖ്യ + മറ്റേതിന്റെ വ്യത്യാസം.', 'വലത് ഭാഗം: രണ്ട് വ്യത്യാസങ്ങളുടെ ഗുണനഫലം (അടിസ്ഥാനത്തിൽ എത്ര പൂജ്യമോ അത്ര അക്കം).'],
    why: '(അടിസ്ഥാനം + x)(അടിസ്ഥാനം + y) = അടിസ്ഥാനം × (അടിസ്ഥാനം + x + y) + x × y. വ്യത്യാസങ്ങൾ ചെറുതാണെങ്കിൽ ഗുണനം വളരെ ചെറുതാകും.',
    q: '{a} × {b} എത്ര?',
    steps: { base: '{a}, {b} ന് അടിസ്ഥാനം {base}.', dev: 'വ്യത്യാസങ്ങൾ: {base} ൽ നിന്ന് {a} ന് {da}, {b} ന് {db}.', cross: 'ഇടത് ഭാഗം: {a} {db} = {left}.', prod: 'വലത് ഭാഗം: ({da}) × ({db}) = {prod}, {k} അക്കങ്ങളിൽ എഴുതുക.', borrow: 'വലത് ഭാഗം {prod} ന്യൂനസംഖ്യ: ഇടത്തുനിന്ന് {c} കടം എടുക്കുക. ഇടത് {left} → {l2}, വലത് {prod} + {cb} = {p2}.', carry: 'അടിസ്ഥാനം {base} ന് {prod} വലുതാണ്: ശിഷ്ടം {c}, ഇടത് {left} → {l3}, വലത് {p3}.', join: '{left}, {right} ചേർത്ത് എഴുതുക → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'ലംബമായും കുറുകെയും (ഊർധ്വ തിര്യക്)', sample: '23 × 14 = 322', tagline: 'ഏത് ഗുണനവും, ഓരോ നിരയായി.',
    how: ['വലത്തുനിന്ന് ഓരോ നിരയായി ചെയ്യുക.', 'ഓരോ നിരയിലും കൂടിച്ചേരുന്ന അക്കങ്ങളുടെ ഗുണനഫലങ്ങൾ (ലംബവും കുറുകെയും) കൂട്ടുക.', 'ഒറ്റയുടെ അക്കം എഴുതി, ബാക്കി അടുത്ത നിരയിലേക്ക് കൊണ്ടുപോകുക.'],
    why: 'ഓരോ നിരയും 10 ന്റെ ഒരേ ഘാതം തരുന്ന എല്ലാ അക്ക ജോഡികളെയും ശേഖരിക്കുന്നു, നീണ്ട ഗുണനം പോലെതന്നെ, പക്ഷേ ഒറ്റ വരിയിൽ.',
    q: '{a} × {b} എത്ര?',
    steps: { setup: '{a} ന് താഴെ {b} എഴുതുക.', col: 'നിര {i}: {terms} = {sum}. {w} എഴുതുക.', col_in: 'നിര {i}: {terms} = {sum}, + ശിഷ്ടം {c} = {total}. {w} എഴുതുക.', col_out: 'നിര {i}: {terms} = {sum}. {w} എഴുതുക, ശിഷ്ടം {carry}.', col_in_out: 'നിര {i}: {terms} = {sum}, + ശിഷ്ടം {c} = {total}. {w} എഴുതുക, ശിഷ്ടം {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 കൊണ്ട് ഹരണം', sample: '2301 ÷ 9 = 255 (6)', tagline: 'അക്കങ്ങളുടെ തുടർതുകകളാണ് ഹരണഫലം.',
    how: ['ആദ്യ അക്കം അതുപോലെ എഴുതുക.', 'മുൻ തുകയോട് അടുത്ത അക്കം കൂട്ടിക്കൊണ്ടേ പോകുക (അവസാന അക്കം ഒഴിവാക്കുക).', 'ഈ തുകകളാണ് ഹരണഫലം; എല്ലാ അക്കങ്ങളുടെയും തുക ശിഷ്ടം.', 'ശിഷ്ടം 9 അല്ലെങ്കിൽ കൂടുതലാണെങ്കിൽ 9 കുറച്ച് ഹരണഫലത്തിൽ 1 കൂട്ടുക.'],
    why: '10 = 9 + 1, അതിനാൽ 9 കൊണ്ട് ഹരിക്കുമ്പോൾ ഓരോ സ്ഥാനവിലയും ശിഷ്ടം 1 നൽകുന്നു. അതുകൊണ്ടാണ് അക്കത്തുക പ്രവർത്തിക്കുന്നത്.',
    q: '{n} ÷ 9 എത്ര? (ഹരണഫലവും ശിഷ്ടവും)',
    steps: { first: '{n} ന്റെ ആദ്യ അക്കം: {d}.', add: '{prev} + {d} = {s}.', quot: 'തുകകൾ {list} → ഹരണഫലം {q}.', rem: 'ശിഷ്ടം = {list} = {r}.', adjust: 'ശിഷ്ടം {r} ≥ 9: ഹരണഫലം {q} → {q2}, ശിഷ്ടം {r2}.', ans: '{n} ÷ 9 = {q}, ശിഷ്ടം {r}' } },
  cuberoot: { icon: '🧊', name: 'ഘനമൂലം', sample: '∛17576 = 26', tagline: 'അവസാന അക്കം ഒറ്റയും മുൻഭാഗം പത്തും തരും.',
    how: ['അവസാനത്തെ മൂന്ന് അക്കങ്ങൾ വേർതിരിക്കുക.', 'ഘനത്തിന്റെ അവസാന അക്കം മൂലത്തിന്റെ ഒറ്റയുടെ അക്കം പറയും (2↔8, 3↔7, ബാക്കി അതുതന്നെ).', 'മുൻഭാഗത്തിനുള്ളിൽ ഒതുങ്ങുന്ന ഏറ്റവും വലിയ ഘനം കണ്ടെത്തുക: അതാണ് പത്തിന്റെ അക്കം.'],
    why: '0–9 ന്റെ ഘനങ്ങളെല്ലാം വ്യത്യസ്ത അക്കങ്ങളിൽ അവസാനിക്കുന്നു, രണ്ടക്ക മൂലത്തിന്റെ ഘനം (10t)³ നും (10t + 10)³ നും ഇടയിലാണ്.',
    q: '{n} ന്റെ ഘനമൂലം എത്ര?',
    steps: { split: '{n} → മുന്നിൽ {left}, പിന്നിൽ {right}.', units: 'അവസാന അക്കം {last}: {u}³ = {u3} അവസാനിക്കുന്നത് {last} ൽ, അതിനാൽ ഒറ്റ = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, അതിനാൽ പത്ത് = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'ശതമാന വിദ്യകൾ', sample: '240 ന്റെ 15% = 36', tagline: 'ഏത് ശതമാനവും 10%, 5%, പകുതി എന്നിവയിൽ നിന്ന് ഉണ്ടാക്കുക.',
    how: ['10%: 10 കൊണ്ട് ഹരിക്കുക.', '5%: 10% ന്റെ പകുതി.', '50% പകുതി, 25% പകുതിയുടെ പകുതി, 75% = 50% + 25%.', 'കഷണങ്ങൾ കൂട്ടുക: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'ശതമാനം എന്നാൽ “100 ൽ”. ശതമാനത്തെ എളുപ്പമുള്ള കഷണങ്ങളാക്കിയാൽ വലിയ ഗുണനം വേണ്ട.',
    q: '{n} ന്റെ {p}% എത്ര?',
    steps: { half: '{n} ന്റെ 50% = {half}.', quarter: '25% = {half} ന്റെ പകുതി = {quarter}.', sum: 'കൂട്ടുക: {parts} = {ans}.', ten: '{n} ന്റെ 10% = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = {ten} ന്റെ പകുതി = {five}.', ans: '{n} ന്റെ {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'അക്കത്തുക പരിശോധന', sample: '47 × 23 = 1081 ✓', tagline: 'ഏത് ഗുണനവും നിമിഷങ്ങൾക്കുള്ളിൽ പരിശോധിക്കുക.',
    how: ['ഒറ്റ അക്കം ബാക്കിയാകും വരെ സംഖ്യയുടെ അക്കങ്ങൾ വീണ്ടും വീണ്ടും കൂട്ടുക (പരിശോധനയിൽ 9 എന്നാൽ 0).', 'രണ്ട് സംഖ്യകളുടെയും അക്കത്തുകകൾ ഗുണിച്ച്, വീണ്ടും ഒറ്റ അക്കമാക്കുക.', 'ഉത്തരത്തിന്റെ അക്കത്തുകയുമായി താരതമ്യം ചെയ്യുക. വ്യത്യസ്തമെങ്കിൽ ഉത്തരം തെറ്റ്.'],
    why: 'ഒരു സംഖ്യയും അതിന്റെ അക്കത്തുകയും 9 കൊണ്ട് ഹരിച്ചാൽ ഒരേ ശിഷ്ടം തരും, ശിഷ്ടങ്ങൾ ഗുണനത്തിലും ചേരും.',
    q: '{n} ന്റെ അക്കത്തുക എത്ര?', q_check: '{a} × {b} = {c} ശരിയാണോ?',
    steps: { start: '{n} ന്റെ അക്കത്തുക കാണുക.', sum: '{label}: {list} = {s}.', single: '{n} ഇതിനകം ഒറ്റ അക്കമാണ്.', root: '{n} ന്റെ അക്കത്തുക = {r}.', check: '{a} × {b} = {c} പരിശോധിക്കുക.', roots: 'അക്കത്തുകകൾ: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: '{c} ന്റെ അക്കത്തുക → {rc}.', match: '{rm} = {rc}: ഉത്തരം മിക്കവാറും ശരി ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} തെറ്റ് ✗' } }
} };
window.APP_CONTENT.ur = { tricks: {
  mul11: { icon: '✖️', name: '11 سے ضرب', sample: '52 × 11 = 572', tagline: 'ساتھ والے ہندسے جمع کریں اور بیچ میں رکھ دیں۔',
    how: ['آخری ہندسہ جیسا ہے ویسا لکھیں۔', 'دائیں سے بائیں چلتے ہوئے ساتھ والے دو دو ہندسے جمع کریں؛ جمع 10 یا زیادہ ہو تو حاصل آگے لے جائیں۔', 'سب سے آگے پہلا ہندسہ (اور حاصل) لکھیں۔'],
    why: '11 = 10 + 1، اس لیے n × 11 = n × 10 + n۔ عدد کو ایک جگہ کھسکا کر خود میں جمع کرنا ساتھ والے ہندسے جمع کرنے جیسا ہی ہے۔',
    q: '{a} × {b} کتنا ہے؟',
    steps: { last: '{n} کا آخری ہندسہ {d} ہے۔ {d} لکھیں۔', pair: 'ساتھ والے ہندسے {x} + {y} = {s}۔ {w} لکھیں۔', pair_in: 'ساتھ والے ہندسے {x} + {y} + حاصل {c} = {s}۔ {w} لکھیں۔', pair_out: 'ساتھ والے ہندسے {x} + {y} = {s}۔ {w} لکھیں، حاصل {carry}۔', pair_in_out: 'ساتھ والے ہندسے {x} + {y} + حاصل {c} = {s}۔ {w} لکھیں، حاصل {carry}۔', first: 'پہلا ہندسہ {f} سب سے آگے لکھیں۔', first_c: 'پہلا ہندسہ {f} + حاصل {c} = {s} سب سے آگے لکھیں۔', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: '9، 99، 999 سے ضرب', sample: '47 × 99 = 4653', tagline: 'ایک کم، پھر تکملہ۔',
    how: ['اگر عدد میں اتنے ہی ہندسے ہوں جتنے 9 ہیں: بایاں حصہ = عدد − 1۔', 'دایاں حصہ = عدد کو 10، 100 یا 1000 تک پہنچنے کے لیے جتنا چاہیے۔', 'ورنہ: 10، 100 یا 1000 سے ضرب دیں اور عدد گھٹا دیں۔'],
    why: '99 = 100 − 1، اس لیے n × 99 = n × 100 − n۔ اسے بانٹنے پر (n − 1) کے بعد (100 − n) آتا ہے۔',
    q: '{a} × {b} کتنا ہے؟',
    steps: { c_left: '{n} × {nines}: بایاں حصہ = {n} − 1 = {left}۔', c_right: 'دایاں حصہ = {base} − {n} = {right}۔', c_join: '{left} اور {right} ساتھ لکھیں ← {ans}۔', n_is: '{nines} = {base} − 1۔', n_times: '{n} × {base} = {m}۔', n_minus: '{m} − {n} = {ans}۔', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: '5، 25، 50 سے ضرب', sample: '48 × 5 = 240', tagline: '10 یا 100 سے ضرب دیں، پھر آدھا یا چوتھائی۔',
    how: ['× 5: 10 سے ضرب دیں، پھر 2 سے تقسیم کریں۔', '× 50: 100 سے ضرب دیں، پھر 2 سے تقسیم کریں۔', '× 25: 100 سے ضرب دیں، پھر 4 سے تقسیم کریں۔'],
    why: '5 = 10 ÷ 2، 50 = 100 ÷ 2 اور 25 = 100 ÷ 4۔ صفر لگا کر آدھا کرنا لمبی ضرب سے آسان ہے۔',
    q: '{a} × {b} کتنا ہے؟',
    steps: { f_idea: '{m} = {pw} ÷ {dv}۔', f_times: '{n} × {pw} = {t}۔', f_div: '{t} ÷ {dv} = {ans}۔', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: '5 پر ختم ہونے والے مربع', sample: '65² = 4225', tagline: 'پہلے حصے کو اگلے عدد سے ضرب، پھر 25۔',
    how: ['آخری 5 ہٹا دیں؛ جو بچا اسے a کہیں۔', 'a کو اگلے عدد a + 1 سے ضرب دیں۔', 'اس کے بعد 25 لکھ دیں۔'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25۔ اس لیے جواب ہمیشہ a × (a + 1) اور اس کے بعد 25 ہوتا ہے۔',
    q: '{n}² کتنا ہے؟',
    steps: { split: '{n}: 5 ہٹائیں، باقی حصہ = {a}۔', mul: '{a} × {a1} = {prod}۔', join: '{prod} کے بعد 25 لکھیں ← {ans}۔', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'بنیاد کے قریب (نکھلم)', sample: '97 × 96 = 9312', tagline: 'سب 9 سے، آخری 10 سے: دیکھیں ہر عدد 100 سے کتنا دور ہے۔',
    how: ['دونوں عددوں کے قریب کی بنیاد (10، 100، 1000) چنیں۔', 'ہر عدد کا بنیاد سے فرق نکالیں۔', 'بایاں حصہ: ایک عدد + دوسرے کا فرق۔', 'دایاں حصہ: دونوں فرقوں کی ضرب (بنیاد میں جتنے صفر، اتنے ہندسے)۔'],
    why: '(بنیاد + x)(بنیاد + y) = بنیاد × (بنیاد + x + y) + x × y۔ فرق چھوٹے ہوں تو ضرب بہت چھوٹی ہو جاتی ہے۔',
    q: '{a} × {b} کتنا ہے؟',
    steps: { base: '{a} اور {b} کی بنیاد {base} ہے۔', dev: 'فرق: {base} سے {a} کا {da}، {b} کا {db}۔', cross: 'بایاں حصہ: {a} {db} = {left}۔', prod: 'دایاں حصہ: ({da}) × ({db}) = {prod}، {k} ہندسوں میں لکھیں۔', borrow: 'دایاں حصہ {prod} منفی ہے: بائیں سے {c} ادھار لیں۔ بایاں {left} ← {l2}، دایاں {prod} + {cb} = {p2}۔', carry: '{prod} بنیاد {base} کے لیے بڑا ہے: حاصل {c}، بایاں {left} ← {l3}، دایاں {p3}۔', join: '{left} اور {right} ساتھ لکھیں ← {ans}۔', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'عمودی اور ترچھا (اوردھو تریک)', sample: '23 × 14 = 322', tagline: 'کوئی بھی ضرب، ایک ایک کالم کر کے۔',
    how: ['دائیں سے ایک ایک کالم کریں۔', 'ہر کالم میں ملنے والے ہندسوں کی ضربیں (سیدھی اور ترچھی) جمع کریں۔', 'اکائی کا ہندسہ لکھیں اور باقی اگلے کالم میں لے جائیں۔'],
    why: 'ہر کالم میں وہ سب ہندسوں کے جوڑے آتے ہیں جن کی مقامی قیمت 10 کی ایک ہی طاقت دیتی ہے، بالکل لمبی ضرب کی طرح، بس ایک لائن میں۔',
    q: '{a} × {b} کتنا ہے؟',
    steps: { setup: '{a} کے نیچے {b} لکھیں۔', col: 'کالم {i}: {terms} = {sum}۔ {w} لکھیں۔', col_in: 'کالم {i}: {terms} = {sum}، + حاصل {c} = {total}۔ {w} لکھیں۔', col_out: 'کالم {i}: {terms} = {sum}۔ {w} لکھیں، حاصل {carry}۔', col_in_out: 'کالم {i}: {terms} = {sum}، + حاصل {c} = {total}۔ {w} لکھیں، حاصل {carry}۔', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: '9 سے تقسیم', sample: '2301 ÷ 9 = 255 (6)', tagline: 'ہندسوں کے چلتے جمع سے حاصلِ تقسیم ملتا ہے۔',
    how: ['پہلا ہندسہ ویسا ہی لکھیں۔', 'پچھلے جمع میں اگلا ہندسہ جوڑتے جائیں (آخری ہندسہ چھوڑ دیں)۔', 'یہ جمع حاصلِ تقسیم بناتے ہیں؛ سب ہندسوں کا جمع باقی ہے۔', 'باقی 9 یا زیادہ ہو تو 9 گھٹائیں اور حاصلِ تقسیم میں 1 جوڑیں۔'],
    why: '10 = 9 + 1، اس لیے 9 سے تقسیم کرنے پر ہر مقامی قیمت 1 باقی چھوڑتی ہے۔ اسی لیے ہندسوں کا جمع کام کرتا ہے۔',
    q: '{n} ÷ 9 کتنا ہے؟ (حاصلِ تقسیم اور باقی)',
    steps: { first: '{n} کا پہلا ہندسہ: {d}۔', add: '{prev} + {d} = {s}۔', quot: 'جمع {list} ← حاصلِ تقسیم {q}۔', rem: 'باقی = {list} = {r}۔', adjust: 'باقی {r} ≥ 9: حاصلِ تقسیم {q} ← {q2}، باقی {r2}۔', ans: '{n} ÷ 9 = {q}، باقی {r}' } },
  cuberoot: { icon: '🧊', name: 'مکعب جذر', sample: '∛17576 = 26', tagline: 'آخری ہندسے سے اکائی، آگے کے حصے سے دہائی۔',
    how: ['آخری تین ہندسے الگ کریں۔', 'مکعب کا آخری ہندسہ جذر کی اکائی بتاتا ہے (2↔8، 3↔7، باقی وہی)۔', 'آگے والے حصے میں سمانے والا سب سے بڑا مکعب ڈھونڈیں: وہی دہائی کا ہندسہ ہے۔'],
    why: '0–9 کے مکعب سب الگ الگ ہندسوں پر ختم ہوتے ہیں، اور دو ہندسوں والے جذر کا مکعب (10t)³ اور (10t + 10)³ کے بیچ ہوتا ہے۔',
    q: '{n} کا مکعب جذر کتنا ہے؟',
    steps: { split: '{n} ← آگے {left}، پیچھے {right}۔', units: 'آخری ہندسہ {last}: {u}³ = {u3} کا آخری ہندسہ {last} ہے، اس لیے اکائی = {u}۔', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³، اس لیے دہائی = {t}۔', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'فیصد کی ترکیبیں', sample: '240 کا 15% = 36', tagline: 'ہر فیصد 10%، 5% اور آدھے سے بنائیں۔',
    how: ['10%: 10 سے تقسیم کریں۔', '5%: 10% کا آدھا۔', '50% آدھا ہے، 25% آدھے کا آدھا، 75% = 50% + 25%۔', 'ٹکڑے جمع کریں: 15% = 10% + 5%، 30% = 3 × 10%۔'],
    why: 'فیصد کا مطلب ہے “100 میں سے”۔ فیصد کو آسان ٹکڑوں میں بانٹنے سے بڑی ضرب نہیں کرنی پڑتی۔',
    q: '{n} کا {p}% کتنا ہے؟',
    steps: { half: '{n} کا 50% = {half}۔', quarter: '25% = {half} کا آدھا = {quarter}۔', sum: 'جمع کریں: {parts} = {ans}۔', ten: '{n} کا 10% = {ten}۔', minus: '90% = {n} − {ten} = {ans}۔', tens: '{p}% = {tens} × {ten} = {val}۔', five: '5% = {ten} کا آدھا = {five}۔', ans: '{n} کا {p}% = {ans}' } },
  digitsum: { icon: '✅', name: 'ہندسوں کے جمع سے جانچ', sample: '47 × 23 = 1081 ✓', tagline: 'کوئی بھی ضرب چند سیکنڈ میں جانچیں۔',
    how: ['ایک ہندسہ بچنے تک عدد کے ہندسے بار بار جمع کریں (جانچ میں 9 کو 0 سمجھیں)۔', 'دونوں عددوں کے ہندسوں کے جمع کو ضرب دیں؛ پھر ایک ہندسے تک لائیں۔', 'جواب کے ہندسوں کے جمع سے ملائیں۔ الگ ہو تو جواب غلط ہے۔'],
    why: 'کوئی عدد اور اس کے ہندسوں کا جمع 9 سے تقسیم کرنے پر ایک ہی باقی چھوڑتے ہیں، اور باقیاں آپس میں ضرب ہوتی ہیں۔',
    q: '{n} کے ہندسوں کا جمع کتنا ہے؟', q_check: 'کیا {a} × {b} = {c} درست ہے؟',
    steps: { start: '{n} کے ہندسوں کا جمع نکالیں۔', sum: '{label}: {list} = {s}۔', single: '{n} پہلے ہی ایک ہندسہ ہے۔', root: '{n} کے ہندسوں کا جمع = {r}۔', check: '{a} × {b} = {c} جانچیں۔', roots: 'ہندسوں کے جمع: {a} ← {ra}، {b} ← {rb}۔', mulroot: '{ra} × {rb} = {prod} ← {rm}۔', croot: '{c} کے ہندسوں کا جمع ← {rc}۔', match: '{rm} = {rc}: جواب شاید درست ہے ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} غلط ہے ✗' } }
} };
