/* Localized trick content for Vedic Maths. Same shape in all 12 languages.
   Step templates use {vars}; numbers are wrapped in LTR isolates by app.js. */
window.APP_CONTENT = {};
window.APP_CONTENT.en = { tricks: {
  mul11: { icon: '✖️', name: 'Multiply by 11', sample: '52 × 11 = 572', tagline: 'Add neighbouring digits and slip them in between.',
    how: ['Write the last digit as it is.', 'Add each pair of neighbouring digits, moving right to left; carry if the sum is 10 or more.', 'Write the first digit (plus any carry) at the front.'],
    why: '11 = 10 + 1, so n × 11 = n × 10 + n. Adding the number to itself shifted one place is the same as adding neighbouring digits.',
    q: 'What is {a} × {b}?',
    steps: { last: 'Last digit of {n} is {d}. Write {d}.', pair: 'Add neighbours {x} + {y} = {s}. Write {w}.', pair_in: 'Add neighbours {x} + {y} + carry {c} = {s}. Write {w}.', pair_out: 'Add neighbours {x} + {y} = {s}. Write {w}, carry {carry}.', pair_in_out: 'Add neighbours {x} + {y} + carry {c} = {s}. Write {w}, carry {carry}.', first: 'First digit {f} goes in front.', first_c: 'First digit {f} + carry {c} = {s} goes in front.', ans: '{n} × 11 = {ans}' } },
  mul9s: { icon: '9️⃣', name: 'Multiply by 9, 99, 999', sample: '47 × 99 = 4653', tagline: 'One less, then the complement.',
    how: ['If the number has as many digits as the nines: left part = number − 1.', 'Right part = what the number needs to reach 10, 100 or 1000.', 'Otherwise: multiply by 10, 100 or 1000 and subtract the number.'],
    why: '99 = 100 − 1, so n × 99 = n × 100 − n. Splitting this gives (n − 1) followed by (100 − n).',
    q: 'What is {a} × {b}?',
    steps: { c_left: '{n} × {nines}: left part = {n} − 1 = {left}.', c_right: 'Right part = {base} − {n} = {right}.', c_join: 'Join {left} and {right} → {ans}.', n_is: '{nines} = {base} − 1.', n_times: '{n} × {base} = {m}.', n_minus: '{m} − {n} = {ans}.', ans: '{n} × {nines} = {ans}' } },
  mul5: { icon: '🖐️', name: 'Multiply by 5, 25, 50', sample: '48 × 5 = 240', tagline: 'Multiply by 10 or 100, then halve or quarter.',
    how: ['× 5: multiply by 10, then divide by 2.', '× 50: multiply by 100, then divide by 2.', '× 25: multiply by 100, then divide by 4.'],
    why: '5 = 10 ÷ 2, 50 = 100 ÷ 2 and 25 = 100 ÷ 4. Adding zeros and halving is easier than long multiplication.',
    q: 'What is {a} × {b}?',
    steps: { f_idea: '{m} = {pw} ÷ {dv}.', f_times: '{n} × {pw} = {t}.', f_div: '{t} ÷ {dv} = {ans}.', ans: '{n} × {m} = {ans}' } },
  sq5: { icon: '🔢', name: 'Squares ending in 5', sample: '65² = 4225', tagline: 'One more than the one before, then 25.',
    how: ['Remove the last 5; call what is left a.', 'Multiply a by the next number, a + 1.', 'Write 25 after it.'],
    why: '(10a + 5)² = 100 × a(a + 1) + 25. So the answer is always a × (a + 1) followed by 25.',
    q: 'What is {n}²?',
    steps: { split: '{n}: remove the 5, left part = {a}.', mul: '{a} × {a1} = {prod}.', join: 'Write 25 after {prod} → {ans}.', ans: '{n}² = {ans}' } },
  nikhilam: { icon: '🎯', name: 'Near a base (Nikhilam)', sample: '97 × 96 = 9312', tagline: 'All from 9, the last from 10: use how far each number is from 100.',
    how: ['Choose the base (10, 100, 1000) close to both numbers.', 'Find each number’s difference from the base.', 'Left part: one number plus the other’s difference.', 'Right part: multiply the two differences (as many digits as zeros in the base).'],
    why: '(base + x)(base + y) = base × (base + x + y) + x × y. Small differences make the multiplication tiny.',
    q: 'What is {a} × {b}?',
    steps: { base: 'Base for {a} and {b} is {base}.', dev: 'Differences: {a} is {da}, {b} is {db} from {base}.', cross: 'Left part: {a} {db} = {left}.', prod: 'Right part: ({da}) × ({db}) = {prod}, written with {k} digits.', borrow: 'Right part {prod} is negative: left {left} → {l2}, right {prod} + {base} = {p2}.', carry: '{prod} is too big for the base {base}: carry {c}, left {left} → {l3}, right {p3}.', join: 'Join {left} and {right} → {ans}.', ans: '{a} × {b} = {ans}' } },
  cross: { icon: '✳️', name: 'Vertically and crosswise', sample: '23 × 14 = 322', tagline: 'Any multiplication, one column at a time.',
    how: ['Work column by column from the right.', 'In each column, add the products of digits that meet (vertical and cross).', 'Write the units digit and carry the rest to the next column.'],
    why: 'Each column collects all digit pairs whose place values give the same power of 10, exactly like long multiplication, but done in one line.',
    q: 'What is {a} × {b}?',
    steps: { setup: 'Write {a} above {b}.', col: 'Column {i}: {terms} = {sum}. Write {w}.', col_in: 'Column {i}: {terms} = {sum}, + carry {c} = {total}. Write {w}.', col_out: 'Column {i}: {terms} = {sum}. Write {w}, carry {carry}.', col_in_out: 'Column {i}: {terms} = {sum}, + carry {c} = {total}. Write {w}, carry {carry}.', ans: '{a} × {b} = {ans}' } },
  div9: { icon: '➗', name: 'Divide by 9', sample: '2301 ÷ 9 = 255 r 6', tagline: 'Running digit sums give the quotient.',
    how: ['Copy the first digit.', 'Keep adding the next digit to the last sum (leave out the final digit).', 'These sums form the quotient; the sum of all digits is the remainder.', 'If the remainder is 9 or more, take away 9 and add 1 to the quotient.'],
    why: '10 = 9 + 1, so every place value leaves remainder 1 when divided by 9. That is why the digit sums work.',
    q: 'What is {n} ÷ 9? (quotient and remainder)',
    steps: { first: 'First digit of {n}: {d}.', add: '{prev} + {d} = {s}.', quot: 'Sums {list} → quotient {q}.', rem: 'Remainder = {list} = {r}.', adjust: 'Remainder {r} ≥ 9: quotient {q} → {q2}, remainder {r2}.', ans: '{n} ÷ 9 = {q} remainder {r}' } },
  cuberoot: { icon: '🧊', name: 'Cube roots', sample: '∛17576 = 26', tagline: 'Last digit gives the units, the front gives the tens.',
    how: ['Split off the last three digits.', 'The last digit of the cube tells the units digit of the root (2↔8, 3↔7, others same).', 'For the front part, find the biggest cube that fits: that is the tens digit.'],
    why: 'Cubes of 0–9 all end in different digits, and a two-digit root has a cube between (10t)³ and (10t + 10)³.',
    q: 'What is the cube root of {n}?',
    steps: { split: '{n} → front {left}, back {right}.', units: 'Last digit {last}: {u}³ = {u3} ends in {last}, so units = {u}.', tens: '{t}³ = {t3} ≤ {left} < {t13} = {t1}³, so tens = {t}.', ans: '∛{n} = {ans}' } },
  percent: { icon: '💯', name: 'Percentage tricks', sample: '15% of 240 = 36', tagline: 'Build any percent from 10%, 5% and halves.',
    how: ['10%: divide by 10.', '5%: half of 10%.', '50% is half, 25% is half of half, 75% = 50% + 25%.', 'Add the pieces: 15% = 10% + 5%, 30% = 3 × 10%.'],
    why: 'Percent means “out of 100”. Splitting a percent into easy pieces avoids big multiplication.',
    q: 'What is {p}% of {n}?',
    steps: { half: '50% of {n} = {half}.', quarter: '25% = half of {half} = {quarter}.', sum: 'Add: {parts} = {ans}.', ten: '10% of {n} = {ten}.', minus: '90% = {n} − {ten} = {ans}.', tens: '{p}% = {tens} × {ten} = {val}.', five: '5% = half of {ten} = {five}.', ans: '{p}% of {n} = {ans}' } },
  digitsum: { icon: '✅', name: 'Digit-sum check', sample: '47 × 23 = 1081 ✓', tagline: 'Check any multiplication in seconds.',
    how: ['Add the digits of a number again and again until one digit is left (9 counts as 0 for checking).', 'Find the digit sums of both numbers and multiply them; reduce again.', 'Compare with the digit sum of the answer. Different means the answer is wrong.'],
    why: 'A number and its digit sum leave the same remainder when divided by 9, and remainders multiply.',
    q: 'What is the digit sum of {n}?', q_check: 'Is {a} × {b} = {c} correct?',
    steps: { start: 'Find the digit sum of {n}.', sum: '{label}: {list} = {s}.', single: '{n} is already one digit.', root: 'Digit sum of {n} = {r}.', check: 'Check {a} × {b} = {c}.', roots: 'Digit sums: {a} → {ra}, {b} → {rb}.', mulroot: '{ra} × {rb} = {prod} → {rm}.', croot: 'Digit sum of {c} → {rc}.', match: '{rm} = {rc}: the answer is probably right ✓', mismatch: '{rm} ≠ {rc}: {a} × {b} = {c} is wrong ✗' } }
} };
