/* Web Page Maker: UI strings. Keys must be identical in all 12 languages. */
window.APP_STRINGS = {
  en: {
    app_title: 'Web Page Maker',
    intro: 'Learn HTML, CSS and JavaScript by building real web pages. Type code on one side and watch your page change on the other.',
    tpl_label: 'Start from a template',
    tpl_choose: 'Choose a template…',
    project_name: 'Project name',
    save_project: 'Save project',
    save_title: 'Keep a copy in My projects (Ctrl + S)',
    my_projects: 'My projects',
    open_html: 'Open .html file',
    download_html: 'Download .html',
    share_link: 'Copy share link',
    print_code: 'Print code',
    reset_work: 'Start over',
    confirm_reset_work: 'Go back to the starter page? Your saved projects will stay safe.',
    try_this: 'Try this:',
    files_label: 'Files',
    tab_preview: 'Preview',
    files_hint: 'Your page = index.html + style.css + script.js. The CSS and JS tabs are joined to the page automatically.',
    editor_label: '{file} code editor',
    keys_label: 'Keys for typing code',
    key_tab: 'Indent (2 spaces)',
    undo: 'Undo',
    redo: 'Redo',
    font_smaller: 'Smaller code text',
    font_bigger: 'Bigger code text',
    wrap_lines: 'Wrap long lines',
    auto_close: 'Auto-close tags',
    esc_hint: 'Tab adds 2 spaces. To leave the editor with the keyboard, press Esc and then Tab.',
    pos: 'line {line}, column {col}',
    autosaved: 'Saved automatically on this device',
    run: 'Run',
    run_title: 'Run the page again (Ctrl + Enter)',
    auto_update: 'Update while I type',
    width_full: 'Full width',
    width_phone: 'Phone size',
    preview_title: 'Live preview of your web page',
    preview_h: 'Preview',
    console: 'Console',
    console_empty: 'Messages from console.log() and errors will appear here.',
    console_ph: 'Type JavaScript, e.g. 2 + 3, and press Enter',
    console_input_label: 'Run one line of JavaScript',
    count_err: 'Errors: {n}',
    count_warn: 'Warnings: {n}',
    console_cleared: 'The console was cleared.',
    err_at: '{file}, line {line}',
    jump_title: 'Go to this line in the editor',
    err_hint_undefined: 'Tip: check the spelling. JavaScript treats capital and small letters as different.',
    err_hint_null: 'Tip: the element was not found. Check that the id in your JavaScript matches the id in your HTML.',
    err_hint_syntax: 'Tip: look for a missing bracket ( ) { }, quote mark or comma.',
    err_hint_notfn: 'Tip: check the name of the function and the brackets after it.',
    err_hint_declared: 'Tip: this name is already used by another variable. Choose a new name, or remove let / const to change its value.',
    err_hint_const: 'Tip: a const cannot be changed. Use let for a value that changes.',
    loop_stopped: 'A loop ran for too long, so it was stopped ({where}). Make sure the loop can end.',
    modal_skipped: '{fn}() was skipped while you were typing. Press Run to see it:',
    link_clicked: 'Links do not open inside the preview. You clicked:',
    form_sent: 'Form sent! On a real website this data would go to a server:',
    form_empty: '(no input has a name)',
    res_fail: 'Could not load this file. Check the name, or use a full web address:',
    lint_unclosed: '<{tag}> is opened but never closed.',
    lint_stray: '</{tag}> closes a tag that was not opened.',
    lint_void: '<{tag}> does not need a closing tag.',
    lint_unknown: '<{tag}> is not an HTML tag. Check the spelling.',
    lint_comment: 'A comment <!-- is never closed with -->.',
    saved_ok: 'Saved in My projects.',
    save_failed: 'Could not save. The browser storage may be full.',
    projects_empty: 'No saved projects yet. Press "Save project" to keep a copy.',
    open_btn: 'Open',
    confirm_replace: 'Replace the code in the editor? Changes that are not saved in My projects will be lost.',
    confirm_delete: 'Delete the project "{name}"?',
    deleted: 'Deleted.',
    opened_file: 'Opened {name}.',
    file_too_big: 'This file is too big (more than 1 MB).',
    file_bad: 'Could not read this file.',
    link_too_big: 'This project is too big for a link. Use Download .html instead.',
    shared_loaded: 'Opened a shared project. Your earlier work is safe in My projects.',
    backup_suffix: 'earlier work',
    untitled: 'My web page',
    saved_at: 'Saved {date}',
    cheat_title: 'Cheat sheet: tags, styles and commands',
    cheat_intro: 'The most useful HTML tags, CSS styles and JavaScript commands. Press Insert to add one to your code.',
    cheat_search: 'Filter, e.g. table or color',
    insert: 'Insert',
    inserted: 'Added to {file}.',
    print_cheat: 'Print cheat sheet',
    no_match: 'Nothing matches.',
    help_title: 'How to use · Ideas for the classroom',
    help_1: 'Pick a template, then change the words, colours and sizes. The preview changes as you type.',
    help_2: 'HTML builds the page, CSS makes it look good and JavaScript makes it do things. Each one has its own tab.',
    help_3: 'Use console.log() in JavaScript to see values in the Console. Errors and tag mistakes show the line number: click it to jump there.',
    help_4: 'Save project keeps copies on this device. Download .html gives one file that opens in any browser, even without internet.',
    help_5: 'Classroom activity: each student makes a page about their town with a heading, a list of 3 places to visit and a table of festivals. Then pairs swap pages and suggest one improvement each.',
    help_6: 'On a smartboard, use A+ and the full-screen preview. On a phone, switch between HTML, CSS, JS and Preview with the tabs.',
    print_title: 'Code of "{name}"'
  },
  hi: {
    app_title: 'वेब पेज मेकर',
    intro: 'असली वेब पेज बनाकर HTML, CSS और JavaScript सीखें। एक तरफ़ कोड लिखें और दूसरी तरफ़ अपना पेज बदलता देखें।',
    tpl_label: 'किसी टेम्पलेट से शुरू करें',
    tpl_choose: 'टेम्पलेट चुनें…',
    project_name: 'प्रोजेक्ट का नाम',
    save_project: 'प्रोजेक्ट सेव करें',
    save_title: '"मेरे प्रोजेक्ट" में एक कॉपी रखें (Ctrl + S)',
    my_projects: 'मेरे प्रोजेक्ट',
    open_html: '.html फ़ाइल खोलें',
    download_html: '.html डाउनलोड करें',
    share_link: 'शेयर लिंक कॉपी करें',
    print_code: 'कोड प्रिंट करें',
    reset_work: 'फिर से शुरू करें',
    confirm_reset_work: 'शुरुआती पेज पर वापस जाएँ? आपके सेव किए प्रोजेक्ट सुरक्षित रहेंगे।',
    try_this: 'यह करके देखें:',
    files_label: 'फ़ाइलें',
    tab_preview: 'प्रीव्यू',
    files_hint: 'आपका पेज = index.html + style.css + script.js. CSS और JS टैब अपने-आप पेज से जुड़ जाते हैं।',
    editor_label: '{file} कोड एडिटर',
    keys_label: 'कोड लिखने की कुंजियाँ',
    key_tab: 'इंडेंट (2 स्पेस)',
    undo: 'अनडू',
    redo: 'रीडू',
    font_smaller: 'कोड के अक्षर छोटे करें',
    font_bigger: 'कोड के अक्षर बड़े करें',
    wrap_lines: 'लंबी लाइनें मोड़ें',
    auto_close: 'टैग अपने-आप बंद करें',
    esc_hint: 'Tab दबाने से 2 स्पेस जुड़ते हैं। कीबोर्ड से एडिटर से बाहर जाने के लिए पहले Esc और फिर Tab दबाएँ।',
    pos: 'लाइन {line}, कॉलम {col}',
    autosaved: 'इसी डिवाइस पर अपने-आप सेव हो रहा है',
    run: 'चलाएँ',
    run_title: 'पेज फिर से चलाएँ (Ctrl + Enter)',
    auto_update: 'लिखते समय अपडेट करें',
    width_full: 'पूरी चौड़ाई',
    width_phone: 'फ़ोन का साइज़',
    preview_title: 'आपके वेब पेज का लाइव प्रीव्यू',
    preview_h: 'प्रीव्यू',
    console: 'कंसोल',
    console_empty: 'console.log() के संदेश और गलतियाँ यहाँ दिखेंगी।',
    console_ph: 'JavaScript लिखें, जैसे 2 + 3, और Enter दबाएँ',
    console_input_label: 'JavaScript की एक लाइन चलाएँ',
    count_err: 'गलतियाँ: {n}',
    count_warn: 'चेतावनियाँ: {n}',
    console_cleared: 'कंसोल साफ़ कर दिया गया।',
    err_at: '{file}, लाइन {line}',
    jump_title: 'एडिटर में इस लाइन पर जाएँ',
    err_hint_undefined: 'सुझाव: स्पेलिंग जाँचें। JavaScript में बड़े और छोटे अक्षर अलग माने जाते हैं।',
    err_hint_null: 'सुझाव: एलिमेंट नहीं मिला। देखें कि JavaScript वाली id और HTML वाली id एक जैसी हैं।',
    err_hint_syntax: 'सुझाव: कोई छूटा हुआ ब्रैकेट ( ) { }, कोटेशन चिह्न या कॉमा ढूँढें।',
    err_hint_notfn: 'सुझाव: फ़ंक्शन का नाम और उसके बाद के ब्रैकेट जाँचें।',
    err_hint_declared: 'सुझाव: यह नाम पहले से किसी वेरिएबल का है। नया नाम चुनें, या उसकी वैल्यू बदलनी हो तो let / const हटा दें।',
    err_hint_const: 'सुझाव: const को बदला नहीं जा सकता। बदलने वाली वैल्यू के लिए let लिखें।',
    loop_stopped: 'एक लूप बहुत देर तक चलता रहा, इसलिए उसे रोक दिया गया ({where})। पक्का करें कि लूप कभी ख़त्म हो सके।',
    modal_skipped: 'आपके लिखते समय {fn}() नहीं चलाया गया। देखने के लिए "चलाएँ" दबाएँ:',
    link_clicked: 'प्रीव्यू के अंदर लिंक नहीं खुलते। आपने क्लिक किया:',
    form_sent: 'फ़ॉर्म भेज दिया! असली वेबसाइट पर यह डेटा सर्वर पर जाता:',
    form_empty: '(किसी इनपुट का name नहीं है)',
    res_fail: 'यह फ़ाइल लोड नहीं हुई। नाम जाँचें या पूरा वेब पता लिखें:',
    lint_unclosed: '<{tag}> खोला गया है, पर बंद नहीं किया गया।',
    lint_stray: '</{tag}> ऐसा टैग बंद कर रहा है जो खुला ही नहीं था।',
    lint_void: '<{tag}> को बंद करने वाले टैग की ज़रूरत नहीं होती।',
    lint_unknown: '<{tag}> कोई HTML टैग नहीं है। स्पेलिंग जाँचें।',
    lint_comment: 'एक कमेंट <!-- को --> से बंद नहीं किया गया।',
    saved_ok: '"मेरे प्रोजेक्ट" में सेव हो गया।',
    save_failed: 'सेव नहीं हो सका। शायद ब्राउज़र की स्टोरेज भर गई है।',
    projects_empty: 'अभी कोई प्रोजेक्ट सेव नहीं है। कॉपी रखने के लिए "प्रोजेक्ट सेव करें" दबाएँ।',
    open_btn: 'खोलें',
    confirm_replace: 'एडिटर का कोड बदल दें? जो बदलाव "मेरे प्रोजेक्ट" में सेव नहीं हैं, वे मिट जाएँगे।',
    confirm_delete: 'प्रोजेक्ट "{name}" हटा दें?',
    deleted: 'हटा दिया।',
    opened_file: '{name} खुल गई।',
    file_too_big: 'यह फ़ाइल बहुत बड़ी है (1 MB से ज़्यादा)।',
    file_bad: 'यह फ़ाइल पढ़ी नहीं जा सकी।',
    link_too_big: 'यह प्रोजेक्ट लिंक के लिए बहुत बड़ा है। इसकी जगह .html डाउनलोड करें।',
    shared_loaded: 'शेयर किया गया प्रोजेक्ट खुल गया। आपका पिछला काम "मेरे प्रोजेक्ट" में सुरक्षित है।',
    backup_suffix: 'पिछला काम',
    untitled: 'मेरा वेब पेज',
    saved_at: 'सेव किया: {date}',
    cheat_title: 'चीट-शीट: टैग, स्टाइल और कमांड',
    cheat_intro: 'सबसे काम के HTML टैग, CSS स्टाइल और JavaScript कमांड। अपने कोड में जोड़ने के लिए "जोड़ें" दबाएँ।',
    cheat_search: 'खोजें, जैसे table या color',
    insert: 'जोड़ें',
    inserted: '{file} में जोड़ दिया।',
    print_cheat: 'चीट-शीट प्रिंट करें',
    no_match: 'कुछ नहीं मिला।',
    help_title: 'कैसे इस्तेमाल करें · कक्षा के लिए आइडिया',
    help_1: 'कोई टेम्पलेट चुनें, फिर उसके शब्द, रंग और साइज़ बदलें। आप जैसे-जैसे लिखते हैं, प्रीव्यू बदलता जाता है।',
    help_2: 'HTML पेज बनाता है, CSS उसे सुंदर बनाता है और JavaScript उससे काम करवाता है। तीनों का अपना-अपना टैब है।',
    help_3: 'JavaScript में console.log() लिखकर कंसोल में वैल्यू देखें। गलती या टैग की भूल पर लाइन नंबर दिखता है: उस पर क्लिक करके सीधे वहीं पहुँचें।',
    help_4: '"प्रोजेक्ट सेव करें" इसी डिवाइस पर कॉपी रखता है। ".html डाउनलोड करें" से एक फ़ाइल मिलती है जो किसी भी ब्राउज़र में, बिना इंटरनेट के भी, खुलती है।',
    help_5: 'कक्षा गतिविधि: हर विद्यार्थी अपने गाँव या शहर पर एक पेज बनाए, जिसमें एक हेडिंग, घूमने की 3 जगहों की लिस्ट और त्योहारों की एक टेबल हो। फिर जोड़ियाँ आपस में पेज बदलें और हर कोई एक सुधार सुझाए।',
    help_6: 'स्मार्टबोर्ड पर A+ और फ़ुल-स्क्रीन प्रीव्यू इस्तेमाल करें। फ़ोन पर ऊपर के टैब से HTML, CSS, JS और प्रीव्यू के बीच जाएँ।',
    print_title: '"{name}" का कोड'
  },
  bn: {
    app_title: 'ওয়েব পেজ মেকার',
    intro: 'সত্যিকারের ওয়েব পেজ বানিয়ে HTML, CSS আর JavaScript শিখুন। একদিকে কোড লিখুন, অন্যদিকে দেখুন আপনার পেজ কেমন বদলে যাচ্ছে।',
    tpl_label: 'একটি টেমপ্লেট দিয়ে শুরু করুন',
    tpl_choose: 'টেমপ্লেট বেছে নিন…',
    project_name: 'প্রজেক্টের নাম',
    save_project: 'প্রজেক্ট সেভ করুন',
    save_title: '"আমার প্রজেক্ট"-এ একটি কপি রাখুন (Ctrl + S)',
    my_projects: 'আমার প্রজেক্ট',
    open_html: '.html ফাইল খুলুন',
    download_html: '.html ডাউনলোড করুন',
    share_link: 'শেয়ার লিংক কপি করুন',
    print_code: 'কোড প্রিন্ট করুন',
    reset_work: 'আবার শুরু করুন',
    confirm_reset_work: 'শুরুর পেজে ফিরে যাবেন? আপনার সেভ করা প্রজেক্টগুলো নিরাপদ থাকবে।',
    try_this: 'এটা করে দেখুন:',
    files_label: 'ফাইল',
    tab_preview: 'প্রিভিউ',
    files_hint: 'আপনার পেজ = index.html + style.css + script.js। CSS আর JS ট্যাব নিজে থেকেই পেজের সঙ্গে জুড়ে যায়।',
    editor_label: '{file} কোড এডিটর',
    keys_label: 'কোড লেখার বোতাম',
    key_tab: 'ইনডেন্ট (2টি স্পেস)',
    undo: 'আনডু',
    redo: 'রিডু',
    font_smaller: 'কোডের লেখা ছোট করুন',
    font_bigger: 'কোডের লেখা বড় করুন',
    wrap_lines: 'লম্বা লাইন ভাঁজ করুন',
    auto_close: 'ট্যাগ নিজে থেকে বন্ধ হোক',
    esc_hint: 'Tab চাপলে 2টি স্পেস বসে। কিবোর্ড দিয়ে এডিটর থেকে বেরোতে আগে Esc, তারপর Tab চাপুন।',
    pos: 'লাইন {line}, কলাম {col}',
    autosaved: 'এই ডিভাইসে নিজে থেকেই সেভ হচ্ছে',
    run: 'চালান',
    run_title: 'পেজটি আবার চালান (Ctrl + Enter)',
    auto_update: 'লেখার সময়েই আপডেট হোক',
    width_full: 'পুরো চওড়া',
    width_phone: 'ফোনের মাপ',
    preview_title: 'আপনার ওয়েব পেজের লাইভ প্রিভিউ',
    preview_h: 'প্রিভিউ',
    console: 'কনসোল',
    console_empty: 'console.log()-এর বার্তা আর ভুলগুলো এখানে দেখা যাবে।',
    console_ph: 'JavaScript লিখুন, যেমন 2 + 3, তারপর Enter চাপুন',
    console_input_label: 'JavaScript-এর একটি লাইন চালান',
    count_err: 'ভুল: {n}',
    count_warn: 'সতর্কতা: {n}',
    console_cleared: 'কনসোল পরিষ্কার করা হয়েছে।',
    err_at: '{file}, লাইন {line}',
    jump_title: 'এডিটরে এই লাইনে যান',
    err_hint_undefined: 'পরামর্শ: বানান দেখুন। JavaScript বড় হাতের আর ছোট হাতের অক্ষরকে আলাদা ধরে।',
    err_hint_null: 'পরামর্শ: এলিমেন্টটি পাওয়া যায়নি। JavaScript-এর id আর HTML-এর id এক কিনা দেখুন।',
    err_hint_syntax: 'পরামর্শ: কোনো বন্ধনী ( ) { }, উদ্ধৃতিচিহ্ন বা কমা বাদ পড়েছে কিনা খুঁজুন।',
    err_hint_notfn: 'পরামর্শ: ফাংশনের নাম আর তার পরের বন্ধনী দেখুন।',
    err_hint_declared: 'পরামর্শ: এই নামটি আগে থেকেই একটি ভেরিয়েবলের। নতুন নাম দিন, অথবা মান বদলাতে চাইলে let / const বাদ দিন।',
    err_hint_const: 'পরামর্শ: const বদলানো যায় না। যে মান বদলাবে তার জন্য let লিখুন।',
    loop_stopped: 'একটি লুপ অনেকক্ষণ ধরে চলছিল, তাই থামিয়ে দেওয়া হয়েছে ({where})। লুপটি যেন শেষ হতে পারে, তা দেখুন।',
    modal_skipped: 'আপনি লেখার সময় {fn}() চালানো হয়নি। দেখতে "চালান" চাপুন:',
    link_clicked: 'প্রিভিউয়ের ভেতরে লিংক খোলে না। আপনি ক্লিক করেছেন:',
    form_sent: 'ফর্ম পাঠানো হয়েছে! আসল ওয়েবসাইটে এই ডেটা সার্ভারে যেত:',
    form_empty: '(কোনো ইনপুটের name নেই)',
    res_fail: 'এই ফাইলটি লোড হলো না। নাম দেখুন, বা পুরো ওয়েব ঠিকানা দিন:',
    lint_unclosed: '<{tag}> খোলা হয়েছে, কিন্তু বন্ধ করা হয়নি।',
    lint_stray: '</{tag}> এমন একটি ট্যাগ বন্ধ করছে যা খোলাই হয়নি।',
    lint_void: '<{tag}>-এর জন্য বন্ধ করার ট্যাগ লাগে না।',
    lint_unknown: '<{tag}> কোনো HTML ট্যাগ নয়। বানান দেখুন।',
    lint_comment: 'একটি কমেন্ট <!-- কে --> দিয়ে বন্ধ করা হয়নি।',
    saved_ok: '"আমার প্রজেক্ট"-এ সেভ হয়েছে।',
    save_failed: 'সেভ করা গেল না। ব্রাউজারের স্টোরেজ হয়তো ভরে গেছে।',
    projects_empty: 'এখনও কোনো প্রজেক্ট সেভ করা নেই। কপি রাখতে "প্রজেক্ট সেভ করুন" চাপুন।',
    open_btn: 'খুলুন',
    confirm_replace: 'এডিটরের কোড বদলে দেবেন? যে পরিবর্তন "আমার প্রজেক্ট"-এ সেভ নেই, তা মুছে যাবে।',
    confirm_delete: '"{name}" প্রজেক্টটি মুছে ফেলবেন?',
    deleted: 'মুছে ফেলা হয়েছে।',
    opened_file: '{name} খোলা হয়েছে।',
    file_too_big: 'ফাইলটি খুব বড় (1 MB-এর বেশি)।',
    file_bad: 'এই ফাইলটি পড়া গেল না।',
    link_too_big: 'লিংকের জন্য প্রজেক্টটি খুব বড়। তার বদলে .html ডাউনলোড করুন।',
    shared_loaded: 'শেয়ার করা প্রজেক্ট খোলা হয়েছে। আপনার আগের কাজ "আমার প্রজেক্ট"-এ নিরাপদে আছে।',
    backup_suffix: 'আগের কাজ',
    untitled: 'আমার ওয়েব পেজ',
    saved_at: 'সেভ করা হয়েছে: {date}',
    cheat_title: 'চিট-শিট: ট্যাগ, স্টাইল আর কমান্ড',
    cheat_intro: 'সবচেয়ে কাজের HTML ট্যাগ, CSS স্টাইল আর JavaScript কমান্ড। কোডে যোগ করতে "যোগ করুন" চাপুন।',
    cheat_search: 'খুঁজুন, যেমন table বা color',
    insert: 'যোগ করুন',
    inserted: '{file}-এ যোগ করা হয়েছে।',
    print_cheat: 'চিট-শিট প্রিন্ট করুন',
    no_match: 'কিছু মেলেনি।',
    help_title: 'কীভাবে ব্যবহার করবেন · ক্লাসের জন্য আইডিয়া',
    help_1: 'একটি টেমপ্লেট বেছে নিন, তারপর তার লেখা, রং আর মাপ বদলান। আপনি লিখতে লিখতেই প্রিভিউ বদলে যায়।',
    help_2: 'HTML পেজ তৈরি করে, CSS তাকে সুন্দর করে আর JavaScript তাকে দিয়ে কাজ করায়। প্রত্যেকটির আলাদা ট্যাব আছে।',
    help_3: 'JavaScript-এ console.log() লিখে কনসোলে মান দেখুন। ভুল বা ট্যাগের গোলমাল হলে লাইন নম্বর দেখায়: সেখানে ক্লিক করলেই ওই লাইনে পৌঁছে যাবেন।',
    help_4: '"প্রজেক্ট সেভ করুন" এই ডিভাইসেই কপি রাখে। ".html ডাউনলোড করুন" দিলে একটি ফাইল পাবেন যা যেকোনো ব্রাউজারে, ইন্টারনেট ছাড়াও, খোলে।',
    help_5: 'ক্লাসের কাজ: প্রত্যেক ছাত্রছাত্রী নিজের গ্রাম বা শহর নিয়ে একটি পেজ বানাবে, তাতে থাকবে একটি হেডিং, ঘোরার মতো 3টি জায়গার তালিকা আর উৎসবের একটি টেবিল। তারপর জোড়ায় জোড়ায় পেজ বদল করে প্রত্যেকে একটি করে উন্নতির পরামর্শ দেবে।',
    help_6: 'স্মার্টবোর্ডে A+ আর ফুল-স্ক্রিন প্রিভিউ ব্যবহার করুন। ফোনে ওপরের ট্যাব দিয়ে HTML, CSS, JS আর প্রিভিউয়ের মধ্যে যান।',
    print_title: '"{name}"-এর কোড'
  },
  mr: {
    app_title: 'वेब पेज मेकर',
    intro: 'खरी वेब पेजेस बनवत HTML, CSS आणि JavaScript शिका. एका बाजूला कोड लिहा आणि दुसऱ्या बाजूला तुमचे पेज बदलताना पाहा.',
    tpl_label: 'टेम्पलेटपासून सुरुवात करा',
    tpl_choose: 'टेम्पलेट निवडा…',
    project_name: 'प्रोजेक्टचे नाव',
    save_project: 'प्रोजेक्ट सेव्ह करा',
    save_title: '"माझे प्रोजेक्ट" मध्ये एक प्रत ठेवा (Ctrl + S)',
    my_projects: 'माझे प्रोजेक्ट',
    open_html: '.html फाइल उघडा',
    download_html: '.html डाउनलोड करा',
    share_link: 'शेअर लिंक कॉपी करा',
    print_code: 'कोड प्रिंट करा',
    reset_work: 'पुन्हा सुरुवात करा',
    confirm_reset_work: 'सुरुवातीच्या पेजवर परत जायचे? तुमचे सेव्ह केलेले प्रोजेक्ट सुरक्षित राहतील.',
    try_this: 'हे करून पाहा:',
    files_label: 'फाइल्स',
    tab_preview: 'प्रिव्ह्यू',
    files_hint: 'तुमचे पेज = index.html + style.css + script.js. CSS आणि JS टॅब आपोआप पेजला जोडले जातात.',
    editor_label: '{file} कोड एडिटर',
    keys_label: 'कोड लिहिण्यासाठी कळा',
    key_tab: 'इंडेंट (2 स्पेस)',
    undo: 'अनडू',
    redo: 'रीडू',
    font_smaller: 'कोडची अक्षरे लहान करा',
    font_bigger: 'कोडची अक्षरे मोठी करा',
    wrap_lines: 'लांब ओळी दुमडा',
    auto_close: 'टॅग आपोआप बंद करा',
    esc_hint: 'Tab दाबल्यावर 2 स्पेस येतात. कीबोर्डने एडिटरमधून बाहेर पडण्यासाठी आधी Esc आणि मग Tab दाबा.',
    pos: 'ओळ {line}, स्तंभ {col}',
    autosaved: 'या डिव्हाइसवर आपोआप सेव्ह होत आहे',
    run: 'चालवा',
    run_title: 'पेज पुन्हा चालवा (Ctrl + Enter)',
    auto_update: 'लिहिताना अपडेट करा',
    width_full: 'पूर्ण रुंदी',
    width_phone: 'फोनचा आकार',
    preview_title: 'तुमच्या वेब पेजचा लाइव्ह प्रिव्ह्यू',
    preview_h: 'प्रिव्ह्यू',
    console: 'कन्सोल',
    console_empty: 'console.log() चे संदेश आणि चुका इथे दिसतील.',
    console_ph: 'JavaScript लिहा, उदा. 2 + 3, आणि Enter दाबा',
    console_input_label: 'JavaScript ची एक ओळ चालवा',
    count_err: 'चुका: {n}',
    count_warn: 'इशारे: {n}',
    console_cleared: 'कन्सोल साफ केले.',
    err_at: '{file}, ओळ {line}',
    jump_title: 'एडिटरमध्ये या ओळीवर जा',
    err_hint_undefined: 'सूचना: स्पेलिंग तपासा. JavaScript मोठी आणि लहान अक्षरे वेगवेगळी मानते.',
    err_hint_null: 'सूचना: एलिमेंट सापडला नाही. JavaScript मधील id आणि HTML मधील id सारखे आहेत का ते पाहा.',
    err_hint_syntax: 'सूचना: एखादा कंस ( ) { }, अवतरण चिन्ह किंवा स्वल्पविराम राहिला आहे का ते शोधा.',
    err_hint_notfn: 'सूचना: फंक्शनचे नाव आणि त्यानंतरचे कंस तपासा.',
    err_hint_declared: 'सूचना: हे नाव आधीच एका व्हेरिएबलचे आहे. नवीन नाव द्या, किंवा किंमत बदलायची असेल तर let / const काढून टाका.',
    err_hint_const: 'सूचना: const बदलता येत नाही. बदलणाऱ्या किमतीसाठी let वापरा.',
    loop_stopped: 'एक लूप खूप वेळ चालत राहिला, म्हणून तो थांबवला ({where}). लूप कधीतरी संपेल याची खात्री करा.',
    modal_skipped: 'तुम्ही लिहीत असताना {fn}() चालवले नाही. पाहण्यासाठी "चालवा" दाबा:',
    link_clicked: 'प्रिव्ह्यूमध्ये लिंक उघडत नाहीत. तुम्ही क्लिक केले:',
    form_sent: 'फॉर्म पाठवला! खऱ्या वेबसाइटवर हा डेटा सर्व्हरकडे गेला असता:',
    form_empty: '(कोणत्याही इनपुटला name नाही)',
    res_fail: 'ही फाइल लोड झाली नाही. नाव तपासा किंवा पूर्ण वेब पत्ता वापरा:',
    lint_unclosed: '<{tag}> उघडला आहे, पण बंद केलेला नाही.',
    lint_stray: '</{tag}> असा टॅग बंद करत आहे जो उघडलाच नव्हता.',
    lint_void: '<{tag}> साठी बंद करणाऱ्या टॅगची गरज नसते.',
    lint_unknown: '<{tag}> हा HTML टॅग नाही. स्पेलिंग तपासा.',
    lint_comment: 'एक कमेंट <!-- हा --> ने बंद केलेला नाही.',
    saved_ok: '"माझे प्रोजेक्ट" मध्ये सेव्ह झाले.',
    save_failed: 'सेव्ह करता आले नाही. ब्राउझरची स्टोरेज कदाचित भरली आहे.',
    projects_empty: 'अजून एकही प्रोजेक्ट सेव्ह केलेला नाही. प्रत ठेवण्यासाठी "प्रोजेक्ट सेव्ह करा" दाबा.',
    open_btn: 'उघडा',
    confirm_replace: 'एडिटरमधील कोड बदलायचा? "माझे प्रोजेक्ट" मध्ये सेव्ह न केलेले बदल नाहीसे होतील.',
    confirm_delete: '"{name}" हा प्रोजेक्ट हटवायचा?',
    deleted: 'हटवले.',
    opened_file: '{name} उघडली.',
    file_too_big: 'ही फाइल खूप मोठी आहे (1 MB पेक्षा जास्त).',
    file_bad: 'ही फाइल वाचता आली नाही.',
    link_too_big: 'हा प्रोजेक्ट लिंकसाठी खूप मोठा आहे. त्याऐवजी .html डाउनलोड करा.',
    shared_loaded: 'शेअर केलेला प्रोजेक्ट उघडला. तुमचे आधीचे काम "माझे प्रोजेक्ट" मध्ये सुरक्षित आहे.',
    backup_suffix: 'आधीचे काम',
    untitled: 'माझे वेब पेज',
    saved_at: 'सेव्ह केले: {date}',
    cheat_title: 'चीट-शीट: टॅग, स्टाइल आणि कमांड',
    cheat_intro: 'सर्वात उपयोगी HTML टॅग, CSS स्टाइल आणि JavaScript कमांड. कोडमध्ये जोडण्यासाठी "जोडा" दाबा.',
    cheat_search: 'शोधा, उदा. table किंवा color',
    insert: 'जोडा',
    inserted: '{file} मध्ये जोडले.',
    print_cheat: 'चीट-शीट प्रिंट करा',
    no_match: 'काहीही जुळले नाही.',
    help_title: 'कसे वापरावे · वर्गासाठी कल्पना',
    help_1: 'एखादे टेम्पलेट निवडा, मग त्यातले शब्द, रंग आणि आकार बदला. तुम्ही लिहिता तसतसा प्रिव्ह्यू बदलतो.',
    help_2: 'HTML पेज बनवते, CSS ते सुंदर करते आणि JavaScript त्याच्याकडून काम करून घेते. प्रत्येकाचा वेगळा टॅब आहे.',
    help_3: 'JavaScript मध्ये console.log() वापरून कन्सोलमध्ये किंमती पाहा. चूक किंवा टॅगमधील गडबड असल्यास ओळ क्रमांक दिसतो: त्यावर क्लिक करून थेट तिथे जा.',
    help_4: '"प्रोजेक्ट सेव्ह करा" याच डिव्हाइसवर प्रती ठेवते. ".html डाउनलोड करा" ने एक फाइल मिळते जी कोणत्याही ब्राउझरमध्ये, इंटरनेटशिवायही, उघडते.',
    help_5: 'वर्गातील उपक्रम: प्रत्येक विद्यार्थ्याने आपल्या गावाबद्दल किंवा शहराबद्दल एक पेज बनवावे, ज्यात एक हेडिंग, भेट देण्याच्या 3 ठिकाणांची यादी आणि सणांचे एक टेबल असेल. मग जोड्यांनी पेजेसची अदलाबदल करून प्रत्येकी एक सुधारणा सुचवावी.',
    help_6: 'स्मार्टबोर्डवर A+ आणि फुल-स्क्रीन प्रिव्ह्यू वापरा. फोनवर वरच्या टॅबने HTML, CSS, JS आणि प्रिव्ह्यू यांच्यात जा.',
    print_title: '"{name}" चा कोड'
  },
  gu: {
    app_title: 'વેબ પેજ મેકર',
    intro: 'સાચાં વેબ પેજ બનાવીને HTML, CSS અને JavaScript શીખો. એક બાજુ કોડ લખો અને બીજી બાજુ તમારું પેજ બદલાતું જુઓ.',
    tpl_label: 'ટેમ્પ્લેટથી શરૂઆત કરો',
    tpl_choose: 'ટેમ્પ્લેટ પસંદ કરો…',
    project_name: 'પ્રોજેક્ટનું નામ',
    save_project: 'પ્રોજેક્ટ સેવ કરો',
    save_title: '"મારા પ્રોજેક્ટ"માં એક નકલ રાખો (Ctrl + S)',
    my_projects: 'મારા પ્રોજેક્ટ',
    open_html: '.html ફાઇલ ખોલો',
    download_html: '.html ડાઉનલોડ કરો',
    share_link: 'શેર લિંક કૉપિ કરો',
    print_code: 'કોડ પ્રિન્ટ કરો',
    reset_work: 'ફરીથી શરૂ કરો',
    confirm_reset_work: 'શરૂઆતના પેજ પર પાછા જવું છે? તમારા સેવ કરેલા પ્રોજેક્ટ સુરક્ષિત રહેશે.',
    try_this: 'આ કરી જુઓ:',
    files_label: 'ફાઇલો',
    tab_preview: 'પ્રિવ્યૂ',
    files_hint: 'તમારું પેજ = index.html + style.css + script.js. CSS અને JS ટૅબ આપમેળે પેજ સાથે જોડાઈ જાય છે.',
    editor_label: '{file} કોડ એડિટર',
    keys_label: 'કોડ લખવા માટેની કી',
    key_tab: 'ઇન્ડેન્ટ (2 સ્પેસ)',
    undo: 'અનડૂ',
    redo: 'રીડૂ',
    font_smaller: 'કોડના અક્ષર નાના કરો',
    font_bigger: 'કોડના અક્ષર મોટા કરો',
    wrap_lines: 'લાંબી લીટીઓ વાળો',
    auto_close: 'ટૅગ આપમેળે બંધ કરો',
    esc_hint: 'Tab દબાવવાથી 2 સ્પેસ ઉમેરાય છે. કીબોર્ડથી એડિટરની બહાર જવા પહેલાં Esc અને પછી Tab દબાવો.',
    pos: 'લીટી {line}, કૉલમ {col}',
    autosaved: 'આ ડિવાઇસ પર આપમેળે સેવ થાય છે',
    run: 'ચલાવો',
    run_title: 'પેજ ફરીથી ચલાવો (Ctrl + Enter)',
    auto_update: 'લખતી વખતે અપડેટ કરો',
    width_full: 'પૂરી પહોળાઈ',
    width_phone: 'ફોનનું માપ',
    preview_title: 'તમારા વેબ પેજનો લાઇવ પ્રિવ્યૂ',
    preview_h: 'પ્રિવ્યૂ',
    console: 'કન્સોલ',
    console_empty: 'console.log() ના સંદેશ અને ભૂલો અહીં દેખાશે.',
    console_ph: 'JavaScript લખો, જેમ કે 2 + 3, અને Enter દબાવો',
    console_input_label: 'JavaScript ની એક લીટી ચલાવો',
    count_err: 'ભૂલો: {n}',
    count_warn: 'ચેતવણીઓ: {n}',
    console_cleared: 'કન્સોલ સાફ કર્યું.',
    err_at: '{file}, લીટી {line}',
    jump_title: 'એડિટરમાં આ લીટી પર જાઓ',
    err_hint_undefined: 'સૂચન: સ્પેલિંગ તપાસો. JavaScript મોટા અને નાના અક્ષરને અલગ ગણે છે.',
    err_hint_null: 'સૂચન: એલિમેન્ટ મળ્યું નહીં. JavaScript ની id અને HTML ની id સરખી છે કે નહીં તે જુઓ.',
    err_hint_syntax: 'સૂચન: કોઈ કૌંસ ( ) { }, અવતરણ ચિહ્ન કે અલ્પવિરામ છૂટી ગયું છે કે નહીં તે શોધો.',
    err_hint_notfn: 'સૂચન: ફંક્શનનું નામ અને તેના પછીના કૌંસ તપાસો.',
    err_hint_declared: 'સૂચન: આ નામ પહેલેથી જ કોઈ વેરિએબલનું છે. નવું નામ આપો, અથવા કિંમત બદલવી હોય તો let / const કાઢી નાખો.',
    err_hint_const: 'સૂચન: const બદલી શકાતો નથી. બદલાતી કિંમત માટે let વાપરો.',
    loop_stopped: 'એક લૂપ બહુ લાંબો સમય ચાલ્યો, તેથી તેને અટકાવી દીધો ({where}). લૂપ પૂરો થઈ શકે તેની ખાતરી કરો.',
    modal_skipped: 'તમે લખતા હતા ત્યારે {fn}() ચલાવ્યું નહીં. જોવા માટે "ચલાવો" દબાવો:',
    link_clicked: 'પ્રિવ્યૂની અંદર લિંક ખૂલતી નથી. તમે ક્લિક કર્યું:',
    form_sent: 'ફોર્મ મોકલાયું! સાચી વેબસાઇટ પર આ ડેટા સર્વર પર જાત:',
    form_empty: '(કોઈ ઇનપુટને name નથી)',
    res_fail: 'આ ફાઇલ લોડ ન થઈ. નામ તપાસો અથવા પૂરું વેબ સરનામું વાપરો:',
    lint_unclosed: '<{tag}> ખોલ્યો છે, પણ બંધ કર્યો નથી.',
    lint_stray: '</{tag}> એવો ટૅગ બંધ કરે છે જે ખોલ્યો જ નહોતો.',
    lint_void: '<{tag}> ને બંધ કરવાના ટૅગની જરૂર નથી.',
    lint_unknown: '<{tag}> કોઈ HTML ટૅગ નથી. સ્પેલિંગ તપાસો.',
    lint_comment: 'એક કમેન્ટ <!-- ને --> થી બંધ કરી નથી.',
    saved_ok: '"મારા પ્રોજેક્ટ"માં સેવ થયું.',
    save_failed: 'સેવ ન થઈ શક્યું. બ્રાઉઝરની સ્ટોરેજ કદાચ ભરાઈ ગઈ છે.',
    projects_empty: 'હજી કોઈ પ્રોજેક્ટ સેવ નથી. નકલ રાખવા "પ્રોજેક્ટ સેવ કરો" દબાવો.',
    open_btn: 'ખોલો',
    confirm_replace: 'એડિટરનો કોડ બદલી નાખવો છે? "મારા પ્રોજેક્ટ"માં સેવ ન થયેલા ફેરફાર જતા રહેશે.',
    confirm_delete: '"{name}" પ્રોજેક્ટ કાઢી નાખવો છે?',
    deleted: 'કાઢી નાખ્યું.',
    opened_file: '{name} ખૂલી.',
    file_too_big: 'આ ફાઇલ બહુ મોટી છે (1 MB થી વધુ).',
    file_bad: 'આ ફાઇલ વાંચી ન શકાઈ.',
    link_too_big: 'આ પ્રોજેક્ટ લિંક માટે બહુ મોટો છે. તેના બદલે .html ડાઉનલોડ કરો.',
    shared_loaded: 'શેર કરેલો પ્રોજેક્ટ ખૂલ્યો. તમારું પહેલાંનું કામ "મારા પ્રોજેક્ટ"માં સુરક્ષિત છે.',
    backup_suffix: 'પહેલાંનું કામ',
    untitled: 'મારું વેબ પેજ',
    saved_at: 'સેવ કર્યું: {date}',
    cheat_title: 'ચીટ-શીટ: ટૅગ, સ્ટાઇલ અને કમાન્ડ',
    cheat_intro: 'સૌથી ઉપયોગી HTML ટૅગ, CSS સ્ટાઇલ અને JavaScript કમાન્ડ. કોડમાં ઉમેરવા "ઉમેરો" દબાવો.',
    cheat_search: 'શોધો, જેમ કે table કે color',
    insert: 'ઉમેરો',
    inserted: '{file} માં ઉમેર્યું.',
    print_cheat: 'ચીટ-શીટ પ્રિન્ટ કરો',
    no_match: 'કંઈ મળ્યું નહીં.',
    help_title: 'કેવી રીતે વાપરવું · વર્ગ માટેના વિચારો',
    help_1: 'કોઈ ટેમ્પ્લેટ પસંદ કરો, પછી તેના શબ્દો, રંગ અને માપ બદલો. તમે લખો તેમ પ્રિવ્યૂ બદલાતો જાય છે.',
    help_2: 'HTML પેજ બનાવે છે, CSS તેને સુંદર બનાવે છે અને JavaScript તેની પાસે કામ કરાવે છે. દરેકનો પોતાનો ટૅબ છે.',
    help_3: 'JavaScript માં console.log() લખીને કન્સોલમાં કિંમતો જુઓ. ભૂલ કે ટૅગની ગડબડ હોય તો લીટી નંબર દેખાય છે: તેના પર ક્લિક કરીને સીધા ત્યાં પહોંચો.',
    help_4: '"પ્રોજેક્ટ સેવ કરો" આ જ ડિવાઇસ પર નકલ રાખે છે. ".html ડાઉનલોડ કરો" થી એક ફાઇલ મળે છે જે કોઈ પણ બ્રાઉઝરમાં, ઇન્ટરનેટ વિના પણ, ખૂલે છે.',
    help_5: 'વર્ગ પ્રવૃત્તિ: દરેક વિદ્યાર્થી પોતાના ગામ કે શહેર વિશે એક પેજ બનાવે, જેમાં એક હેડિંગ, ફરવા જેવી 3 જગ્યાની યાદી અને તહેવારોનું એક ટેબલ હોય. પછી જોડીઓ પેજની અદલાબદલી કરે અને દરેક એક-એક સુધારો સૂચવે.',
    help_6: 'સ્માર્ટબોર્ડ પર A+ અને ફુલ-સ્ક્રીન પ્રિવ્યૂ વાપરો. ફોન પર ઉપરના ટૅબથી HTML, CSS, JS અને પ્રિવ્યૂ વચ્ચે જાઓ.',
    print_title: '"{name}" નો કોડ'
  },
  pa: {
    app_title: 'ਵੈੱਬ ਪੇਜ ਮੇਕਰ',
    intro: 'ਅਸਲੀ ਵੈੱਬ ਪੇਜ ਬਣਾ ਕੇ HTML, CSS ਅਤੇ JavaScript ਸਿੱਖੋ। ਇੱਕ ਪਾਸੇ ਕੋਡ ਲਿਖੋ ਅਤੇ ਦੂਜੇ ਪਾਸੇ ਆਪਣਾ ਪੇਜ ਬਦਲਦਾ ਦੇਖੋ।',
    tpl_label: 'ਕਿਸੇ ਟੈਂਪਲੇਟ ਤੋਂ ਸ਼ੁਰੂ ਕਰੋ',
    tpl_choose: 'ਟੈਂਪਲੇਟ ਚੁਣੋ…',
    project_name: 'ਪ੍ਰੋਜੈਕਟ ਦਾ ਨਾਂ',
    save_project: 'ਪ੍ਰੋਜੈਕਟ ਸੇਵ ਕਰੋ',
    save_title: '"ਮੇਰੇ ਪ੍ਰੋਜੈਕਟ" ਵਿੱਚ ਇੱਕ ਕਾਪੀ ਰੱਖੋ (Ctrl + S)',
    my_projects: 'ਮੇਰੇ ਪ੍ਰੋਜੈਕਟ',
    open_html: '.html ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ',
    download_html: '.html ਡਾਊਨਲੋਡ ਕਰੋ',
    share_link: 'ਸ਼ੇਅਰ ਲਿੰਕ ਕਾਪੀ ਕਰੋ',
    print_code: 'ਕੋਡ ਪ੍ਰਿੰਟ ਕਰੋ',
    reset_work: 'ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ',
    confirm_reset_work: 'ਸ਼ੁਰੂਆਤੀ ਪੇਜ ’ਤੇ ਵਾਪਸ ਜਾਣਾ ਹੈ? ਤੁਹਾਡੇ ਸੇਵ ਕੀਤੇ ਪ੍ਰੋਜੈਕਟ ਸੁਰੱਖਿਅਤ ਰਹਿਣਗੇ।',
    try_this: 'ਇਹ ਕਰਕੇ ਦੇਖੋ:',
    files_label: 'ਫ਼ਾਈਲਾਂ',
    tab_preview: 'ਪ੍ਰੀਵਿਊ',
    files_hint: 'ਤੁਹਾਡਾ ਪੇਜ = index.html + style.css + script.js। CSS ਅਤੇ JS ਟੈਬ ਆਪਣੇ-ਆਪ ਪੇਜ ਨਾਲ ਜੁੜ ਜਾਂਦੇ ਹਨ।',
    editor_label: '{file} ਕੋਡ ਐਡੀਟਰ',
    keys_label: 'ਕੋਡ ਲਿਖਣ ਵਾਲੀਆਂ ਕੁੰਜੀਆਂ',
    key_tab: 'ਇੰਡੈਂਟ (2 ਸਪੇਸ)',
    undo: 'ਅਨਡੂ',
    redo: 'ਰੀਡੂ',
    font_smaller: 'ਕੋਡ ਦੇ ਅੱਖਰ ਛੋਟੇ ਕਰੋ',
    font_bigger: 'ਕੋਡ ਦੇ ਅੱਖਰ ਵੱਡੇ ਕਰੋ',
    wrap_lines: 'ਲੰਮੀਆਂ ਲਾਈਨਾਂ ਮੋੜੋ',
    auto_close: 'ਟੈਗ ਆਪਣੇ-ਆਪ ਬੰਦ ਕਰੋ',
    esc_hint: 'Tab ਦਬਾਉਣ ਨਾਲ 2 ਸਪੇਸ ਲੱਗਦੀਆਂ ਹਨ। ਕੀਬੋਰਡ ਨਾਲ ਐਡੀਟਰ ਤੋਂ ਬਾਹਰ ਜਾਣ ਲਈ ਪਹਿਲਾਂ Esc ਅਤੇ ਫਿਰ Tab ਦਬਾਓ।',
    pos: 'ਲਾਈਨ {line}, ਕਾਲਮ {col}',
    autosaved: 'ਇਸ ਡਿਵਾਈਸ ’ਤੇ ਆਪਣੇ-ਆਪ ਸੇਵ ਹੋ ਰਿਹਾ ਹੈ',
    run: 'ਚਲਾਓ',
    run_title: 'ਪੇਜ ਮੁੜ ਚਲਾਓ (Ctrl + Enter)',
    auto_update: 'ਲਿਖਦੇ ਸਮੇਂ ਅੱਪਡੇਟ ਕਰੋ',
    width_full: 'ਪੂਰੀ ਚੌੜਾਈ',
    width_phone: 'ਫ਼ੋਨ ਦਾ ਆਕਾਰ',
    preview_title: 'ਤੁਹਾਡੇ ਵੈੱਬ ਪੇਜ ਦਾ ਲਾਈਵ ਪ੍ਰੀਵਿਊ',
    preview_h: 'ਪ੍ਰੀਵਿਊ',
    console: 'ਕੰਸੋਲ',
    console_empty: 'console.log() ਦੇ ਸੁਨੇਹੇ ਅਤੇ ਗ਼ਲਤੀਆਂ ਇੱਥੇ ਦਿਸਣਗੀਆਂ।',
    console_ph: 'JavaScript ਲਿਖੋ, ਜਿਵੇਂ 2 + 3, ਅਤੇ Enter ਦਬਾਓ',
    console_input_label: 'JavaScript ਦੀ ਇੱਕ ਲਾਈਨ ਚਲਾਓ',
    count_err: 'ਗ਼ਲਤੀਆਂ: {n}',
    count_warn: 'ਚੇਤਾਵਨੀਆਂ: {n}',
    console_cleared: 'ਕੰਸੋਲ ਸਾਫ਼ ਕਰ ਦਿੱਤਾ ਗਿਆ।',
    err_at: '{file}, ਲਾਈਨ {line}',
    jump_title: 'ਐਡੀਟਰ ਵਿੱਚ ਇਸ ਲਾਈਨ ’ਤੇ ਜਾਓ',
    err_hint_undefined: 'ਸੁਝਾਅ: ਸਪੈਲਿੰਗ ਜਾਂਚੋ। JavaScript ਵੱਡੇ ਅਤੇ ਛੋਟੇ ਅੱਖਰਾਂ ਨੂੰ ਵੱਖਰਾ ਮੰਨਦੀ ਹੈ।',
    err_hint_null: 'ਸੁਝਾਅ: ਐਲੀਮੈਂਟ ਨਹੀਂ ਮਿਲਿਆ। ਦੇਖੋ ਕਿ JavaScript ਵਾਲੀ id ਅਤੇ HTML ਵਾਲੀ id ਇੱਕੋ ਜਿਹੀ ਹੈ।',
    err_hint_syntax: 'ਸੁਝਾਅ: ਕੋਈ ਛੁੱਟੀ ਹੋਈ ਬਰੈਕਟ ( ) { }, ਕੋਟੇਸ਼ਨ ਚਿੰਨ੍ਹ ਜਾਂ ਕੌਮਾ ਲੱਭੋ।',
    err_hint_notfn: 'ਸੁਝਾਅ: ਫ਼ੰਕਸ਼ਨ ਦਾ ਨਾਂ ਅਤੇ ਉਸ ਤੋਂ ਬਾਅਦ ਦੀਆਂ ਬਰੈਕਟਾਂ ਜਾਂਚੋ।',
    err_hint_declared: 'ਸੁਝਾਅ: ਇਹ ਨਾਂ ਪਹਿਲਾਂ ਹੀ ਕਿਸੇ ਵੇਰੀਏਬਲ ਦਾ ਹੈ। ਨਵਾਂ ਨਾਂ ਚੁਣੋ, ਜਾਂ ਮੁੱਲ ਬਦਲਣਾ ਹੋਵੇ ਤਾਂ let / const ਹਟਾ ਦਿਓ।',
    err_hint_const: 'ਸੁਝਾਅ: const ਨੂੰ ਬਦਲਿਆ ਨਹੀਂ ਜਾ ਸਕਦਾ। ਬਦਲਣ ਵਾਲੇ ਮੁੱਲ ਲਈ let ਵਰਤੋ।',
    loop_stopped: 'ਇੱਕ ਲੂਪ ਬਹੁਤ ਦੇਰ ਤੱਕ ਚੱਲਦਾ ਰਿਹਾ, ਇਸ ਲਈ ਉਸ ਨੂੰ ਰੋਕ ਦਿੱਤਾ ਗਿਆ ({where})। ਪੱਕਾ ਕਰੋ ਕਿ ਲੂਪ ਖ਼ਤਮ ਹੋ ਸਕੇ।',
    modal_skipped: 'ਤੁਹਾਡੇ ਲਿਖਦੇ ਸਮੇਂ {fn}() ਨਹੀਂ ਚਲਾਇਆ ਗਿਆ। ਦੇਖਣ ਲਈ "ਚਲਾਓ" ਦਬਾਓ:',
    link_clicked: 'ਪ੍ਰੀਵਿਊ ਦੇ ਅੰਦਰ ਲਿੰਕ ਨਹੀਂ ਖੁੱਲ੍ਹਦੇ। ਤੁਸੀਂ ਕਲਿੱਕ ਕੀਤਾ:',
    form_sent: 'ਫ਼ਾਰਮ ਭੇਜ ਦਿੱਤਾ! ਅਸਲੀ ਵੈੱਬਸਾਈਟ ’ਤੇ ਇਹ ਡਾਟਾ ਸਰਵਰ ਕੋਲ ਜਾਂਦਾ:',
    form_empty: '(ਕਿਸੇ ਇਨਪੁੱਟ ਦਾ name ਨਹੀਂ ਹੈ)',
    res_fail: 'ਇਹ ਫ਼ਾਈਲ ਲੋਡ ਨਹੀਂ ਹੋਈ। ਨਾਂ ਜਾਂਚੋ ਜਾਂ ਪੂਰਾ ਵੈੱਬ ਪਤਾ ਵਰਤੋ:',
    lint_unclosed: '<{tag}> ਖੋਲ੍ਹਿਆ ਗਿਆ ਹੈ, ਪਰ ਬੰਦ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।',
    lint_stray: '</{tag}> ਅਜਿਹਾ ਟੈਗ ਬੰਦ ਕਰ ਰਿਹਾ ਹੈ ਜੋ ਖੁੱਲ੍ਹਿਆ ਹੀ ਨਹੀਂ ਸੀ।',
    lint_void: '<{tag}> ਨੂੰ ਬੰਦ ਕਰਨ ਵਾਲੇ ਟੈਗ ਦੀ ਲੋੜ ਨਹੀਂ ਹੁੰਦੀ।',
    lint_unknown: '<{tag}> ਕੋਈ HTML ਟੈਗ ਨਹੀਂ ਹੈ। ਸਪੈਲਿੰਗ ਜਾਂਚੋ।',
    lint_comment: 'ਇੱਕ ਕਮੈਂਟ <!-- ਨੂੰ --> ਨਾਲ ਬੰਦ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।',
    saved_ok: '"ਮੇਰੇ ਪ੍ਰੋਜੈਕਟ" ਵਿੱਚ ਸੇਵ ਹੋ ਗਿਆ।',
    save_failed: 'ਸੇਵ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਸ਼ਾਇਦ ਬ੍ਰਾਊਜ਼ਰ ਦੀ ਸਟੋਰੇਜ ਭਰ ਗਈ ਹੈ।',
    projects_empty: 'ਅਜੇ ਕੋਈ ਪ੍ਰੋਜੈਕਟ ਸੇਵ ਨਹੀਂ ਹੈ। ਕਾਪੀ ਰੱਖਣ ਲਈ "ਪ੍ਰੋਜੈਕਟ ਸੇਵ ਕਰੋ" ਦਬਾਓ।',
    open_btn: 'ਖੋਲ੍ਹੋ',
    confirm_replace: 'ਐਡੀਟਰ ਦਾ ਕੋਡ ਬਦਲ ਦੇਈਏ? ਜੋ ਬਦਲਾਅ "ਮੇਰੇ ਪ੍ਰੋਜੈਕਟ" ਵਿੱਚ ਸੇਵ ਨਹੀਂ ਹਨ, ਉਹ ਮਿਟ ਜਾਣਗੇ।',
    confirm_delete: 'ਪ੍ਰੋਜੈਕਟ "{name}" ਮਿਟਾਉਣਾ ਹੈ?',
    deleted: 'ਮਿਟਾ ਦਿੱਤਾ।',
    opened_file: '{name} ਖੁੱਲ੍ਹ ਗਈ।',
    file_too_big: 'ਇਹ ਫ਼ਾਈਲ ਬਹੁਤ ਵੱਡੀ ਹੈ (1 MB ਤੋਂ ਵੱਧ)।',
    file_bad: 'ਇਹ ਫ਼ਾਈਲ ਪੜ੍ਹੀ ਨਹੀਂ ਜਾ ਸਕੀ।',
    link_too_big: 'ਇਹ ਪ੍ਰੋਜੈਕਟ ਲਿੰਕ ਲਈ ਬਹੁਤ ਵੱਡਾ ਹੈ। ਇਸ ਦੀ ਥਾਂ .html ਡਾਊਨਲੋਡ ਕਰੋ।',
    shared_loaded: 'ਸ਼ੇਅਰ ਕੀਤਾ ਪ੍ਰੋਜੈਕਟ ਖੁੱਲ੍ਹ ਗਿਆ। ਤੁਹਾਡਾ ਪਿਛਲਾ ਕੰਮ "ਮੇਰੇ ਪ੍ਰੋਜੈਕਟ" ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਹੈ।',
    backup_suffix: 'ਪਿਛਲਾ ਕੰਮ',
    untitled: 'ਮੇਰਾ ਵੈੱਬ ਪੇਜ',
    saved_at: 'ਸੇਵ ਕੀਤਾ: {date}',
    cheat_title: 'ਚੀਟ-ਸ਼ੀਟ: ਟੈਗ, ਸਟਾਈਲ ਅਤੇ ਕਮਾਂਡ',
    cheat_intro: 'ਸਭ ਤੋਂ ਕੰਮ ਦੇ HTML ਟੈਗ, CSS ਸਟਾਈਲ ਅਤੇ JavaScript ਕਮਾਂਡ। ਕੋਡ ਵਿੱਚ ਜੋੜਨ ਲਈ "ਜੋੜੋ" ਦਬਾਓ।',
    cheat_search: 'ਲੱਭੋ, ਜਿਵੇਂ table ਜਾਂ color',
    insert: 'ਜੋੜੋ',
    inserted: '{file} ਵਿੱਚ ਜੋੜ ਦਿੱਤਾ।',
    print_cheat: 'ਚੀਟ-ਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ',
    no_match: 'ਕੁਝ ਨਹੀਂ ਮਿਲਿਆ।',
    help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ · ਜਮਾਤ ਲਈ ਵਿਚਾਰ',
    help_1: 'ਕੋਈ ਟੈਂਪਲੇਟ ਚੁਣੋ, ਫਿਰ ਉਸ ਦੇ ਸ਼ਬਦ, ਰੰਗ ਅਤੇ ਆਕਾਰ ਬਦਲੋ। ਜਿਵੇਂ-ਜਿਵੇਂ ਤੁਸੀਂ ਲਿਖਦੇ ਹੋ, ਪ੍ਰੀਵਿਊ ਬਦਲਦਾ ਜਾਂਦਾ ਹੈ।',
    help_2: 'HTML ਪੇਜ ਬਣਾਉਂਦਾ ਹੈ, CSS ਉਸ ਨੂੰ ਸੋਹਣਾ ਬਣਾਉਂਦਾ ਹੈ ਅਤੇ JavaScript ਉਸ ਤੋਂ ਕੰਮ ਕਰਵਾਉਂਦੀ ਹੈ। ਹਰ ਇੱਕ ਦਾ ਆਪਣਾ ਟੈਬ ਹੈ।',
    help_3: 'JavaScript ਵਿੱਚ console.log() ਲਿਖ ਕੇ ਕੰਸੋਲ ਵਿੱਚ ਮੁੱਲ ਦੇਖੋ। ਗ਼ਲਤੀ ਜਾਂ ਟੈਗ ਦੀ ਭੁੱਲ ’ਤੇ ਲਾਈਨ ਨੰਬਰ ਦਿਸਦਾ ਹੈ: ਉਸ ’ਤੇ ਕਲਿੱਕ ਕਰਕੇ ਸਿੱਧਾ ਉੱਥੇ ਪਹੁੰਚੋ।',
    help_4: '"ਪ੍ਰੋਜੈਕਟ ਸੇਵ ਕਰੋ" ਇਸੇ ਡਿਵਾਈਸ ’ਤੇ ਕਾਪੀਆਂ ਰੱਖਦਾ ਹੈ। ".html ਡਾਊਨਲੋਡ ਕਰੋ" ਨਾਲ ਇੱਕ ਫ਼ਾਈਲ ਮਿਲਦੀ ਹੈ ਜੋ ਕਿਸੇ ਵੀ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ, ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਵੀ, ਖੁੱਲ੍ਹਦੀ ਹੈ।',
    help_5: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: ਹਰ ਵਿਦਿਆਰਥੀ ਆਪਣੇ ਪਿੰਡ ਜਾਂ ਸ਼ਹਿਰ ਬਾਰੇ ਇੱਕ ਪੇਜ ਬਣਾਏ, ਜਿਸ ਵਿੱਚ ਇੱਕ ਹੈਡਿੰਗ, ਘੁੰਮਣ ਵਾਲੀਆਂ 3 ਥਾਵਾਂ ਦੀ ਸੂਚੀ ਅਤੇ ਤਿਉਹਾਰਾਂ ਦਾ ਇੱਕ ਟੇਬਲ ਹੋਵੇ। ਫਿਰ ਜੋੜੀਆਂ ਪੇਜ ਬਦਲ ਕੇ ਹਰ ਕੋਈ ਇੱਕ ਸੁਧਾਰ ਸੁਝਾਏ।',
    help_6: 'ਸਮਾਰਟਬੋਰਡ ’ਤੇ A+ ਅਤੇ ਫੁੱਲ-ਸਕਰੀਨ ਪ੍ਰੀਵਿਊ ਵਰਤੋ। ਫ਼ੋਨ ’ਤੇ ਉੱਪਰਲੇ ਟੈਬਾਂ ਨਾਲ HTML, CSS, JS ਅਤੇ ਪ੍ਰੀਵਿਊ ਵਿਚਕਾਰ ਜਾਓ।',
    print_title: '"{name}" ਦਾ ਕੋਡ'
  },
  or: {
    app_title: 'ୱେବ୍ ପେଜ୍ ମେକର୍',
    intro: 'ପ୍ରକୃତ ୱେବ୍ ପେଜ୍ ତିଆରି କରି HTML, CSS ଓ JavaScript ଶିଖନ୍ତୁ। ଗୋଟିଏ ପାଖରେ କୋଡ୍ ଲେଖନ୍ତୁ ଓ ଅନ୍ୟ ପାଖରେ ଆପଣଙ୍କ ପେଜ୍ ବଦଳୁଥିବା ଦେଖନ୍ତୁ।',
    tpl_label: 'ଏକ ଟେମ୍ପଲେଟ୍‌ରୁ ଆରମ୍ଭ କରନ୍ତୁ',
    tpl_choose: 'ଟେମ୍ପଲେଟ୍ ବାଛନ୍ତୁ…',
    project_name: 'ପ୍ରୋଜେକ୍ଟର ନାମ',
    save_project: 'ପ୍ରୋଜେକ୍ଟ ସେଭ୍ କରନ୍ତୁ',
    save_title: '"ମୋ ପ୍ରୋଜେକ୍ଟ"ରେ ଗୋଟିଏ କପି ରଖନ୍ତୁ (Ctrl + S)',
    my_projects: 'ମୋ ପ୍ରୋଜେକ୍ଟ',
    open_html: '.html ଫାଇଲ୍ ଖୋଲନ୍ତୁ',
    download_html: '.html ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    share_link: 'ସେୟାର୍ ଲିଙ୍କ କପି କରନ୍ତୁ',
    print_code: 'କୋଡ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    reset_work: 'ପୁଣି ଆରମ୍ଭ କରନ୍ତୁ',
    confirm_reset_work: 'ଆରମ୍ଭ ପେଜ୍‌କୁ ଫେରିବେ? ଆପଣଙ୍କ ସେଭ୍ କରାଯାଇଥିବା ପ୍ରୋଜେକ୍ଟ ସୁରକ୍ଷିତ ରହିବ।',
    try_this: 'ଏହା କରି ଦେଖନ୍ତୁ:',
    files_label: 'ଫାଇଲ୍',
    tab_preview: 'ପ୍ରିଭ୍ୟୁ',
    files_hint: 'ଆପଣଙ୍କ ପେଜ୍ = index.html + style.css + script.js। CSS ଓ JS ଟ୍ୟାବ୍ ନିଜେ ନିଜେ ପେଜ୍ ସହ ଯୋଡ଼ି ହୋଇଯାଏ।',
    editor_label: '{file} କୋଡ୍ ଏଡିଟର୍',
    keys_label: 'କୋଡ୍ ଲେଖିବା ପାଇଁ ଚାବି',
    key_tab: 'ଇଣ୍ଡେଣ୍ଟ (2 ସ୍ପେସ୍)',
    undo: 'ଅନଡୁ',
    redo: 'ରିଡୁ',
    font_smaller: 'କୋଡ୍‌ର ଅକ୍ଷର ଛୋଟ କରନ୍ତୁ',
    font_bigger: 'କୋଡ୍‌ର ଅକ୍ଷର ବଡ଼ କରନ୍ତୁ',
    wrap_lines: 'ଲମ୍ବା ଧାଡ଼ି ମୋଡ଼ନ୍ତୁ',
    auto_close: 'ଟ୍ୟାଗ୍ ନିଜେ ବନ୍ଦ ହେଉ',
    esc_hint: 'Tab ଦବାଇଲେ 2ଟି ସ୍ପେସ୍ ଆସେ। କିବୋର୍ଡରେ ଏଡିଟରରୁ ବାହାରିବାକୁ ପ୍ରଥମେ Esc ଓ ତା’ପରେ Tab ଦବାନ୍ତୁ।',
    pos: 'ଧାଡ଼ି {line}, ସ୍ତମ୍ଭ {col}',
    autosaved: 'ଏହି ଡିଭାଇସରେ ନିଜେ ନିଜେ ସେଭ୍ ହେଉଛି',
    run: 'ଚଲାନ୍ତୁ',
    run_title: 'ପେଜ୍ ପୁଣି ଚଲାନ୍ତୁ (Ctrl + Enter)',
    auto_update: 'ଲେଖିବା ସମୟରେ ଅପଡେଟ୍ କରନ୍ତୁ',
    width_full: 'ପୂରା ଓସାର',
    width_phone: 'ଫୋନ୍ ଆକାର',
    preview_title: 'ଆପଣଙ୍କ ୱେବ୍ ପେଜ୍‌ର ଲାଇଭ୍ ପ୍ରିଭ୍ୟୁ',
    preview_h: 'ପ୍ରିଭ୍ୟୁ',
    console: 'କନସୋଲ୍',
    console_empty: 'console.log()ର ବାର୍ତ୍ତା ଓ ଭୁଲ ଏଠାରେ ଦେଖାଯିବ।',
    console_ph: 'JavaScript ଲେଖନ୍ତୁ, ଯେପରି 2 + 3, ଓ Enter ଦବାନ୍ତୁ',
    console_input_label: 'JavaScriptର ଗୋଟିଏ ଧାଡ଼ି ଚଲାନ୍ତୁ',
    count_err: 'ଭୁଲ: {n}',
    count_warn: 'ଚେତାବନୀ: {n}',
    console_cleared: 'କନସୋଲ୍ ସଫା କରାଗଲା।',
    err_at: '{file}, ଧାଡ଼ି {line}',
    jump_title: 'ଏଡିଟରରେ ଏହି ଧାଡ଼ିକୁ ଯାଆନ୍ତୁ',
    err_hint_undefined: 'ପରାମର୍ଶ: ବନାନ ଯାଞ୍ଚ କରନ୍ତୁ। JavaScript ବଡ଼ ଓ ଛୋଟ ଅକ୍ଷରକୁ ଅଲଗା ବୋଲି ଧରେ।',
    err_hint_null: 'ପରାମର୍ଶ: ଏଲିମେଣ୍ଟ ମିଳିଲା ନାହିଁ। JavaScriptର id ଓ HTMLର id ସମାନ କି ନାହିଁ ଦେଖନ୍ତୁ।',
    err_hint_syntax: 'ପରାମର୍ଶ: କୌଣସି ବନ୍ଧନୀ ( ) { }, ଉଦ୍ଧୃତି ଚିହ୍ନ ବା କମା ଛାଡ଼ି ଯାଇଛି କି ଖୋଜନ୍ତୁ।',
    err_hint_notfn: 'ପରାମର୍ଶ: ଫଙ୍କସନ୍‌ର ନାମ ଓ ତା’ ପରର ବନ୍ଧନୀ ଯାଞ୍ଚ କରନ୍ତୁ।',
    err_hint_declared: 'ପରାମର୍ଶ: ଏହି ନାମ ଆଗରୁ ଗୋଟିଏ ଭେରିଏବଲ୍‌ର ଅଛି। ନୂଆ ନାମ ଦିଅନ୍ତୁ, କିମ୍ବା ମୂଲ୍ୟ ବଦଳାଇବାକୁ ହେଲେ let / const ହଟାନ୍ତୁ।',
    err_hint_const: 'ପରାମର୍ଶ: const କୁ ବଦଳାଯାଇପାରିବ ନାହିଁ। ବଦଳୁଥିବା ମୂଲ୍ୟ ପାଇଁ let ବ୍ୟବହାର କରନ୍ତୁ।',
    loop_stopped: 'ଗୋଟିଏ ଲୁପ୍ ବହୁତ ସମୟ ଧରି ଚାଲୁଥିଲା, ତେଣୁ ତାହାକୁ ବନ୍ଦ କରାଗଲା ({where})। ଲୁପ୍ ଶେଷ ହୋଇପାରିବ ବୋଲି ନିଶ୍ଚିତ କରନ୍ତୁ।',
    modal_skipped: 'ଆପଣ ଲେଖୁଥିବା ବେଳେ {fn}() ଚଳାଯାଇ ନଥିଲା। ଦେଖିବାକୁ "ଚଲାନ୍ତୁ" ଦବାନ୍ତୁ:',
    link_clicked: 'ପ୍ରିଭ୍ୟୁ ଭିତରେ ଲିଙ୍କ ଖୋଲେ ନାହିଁ। ଆପଣ କ୍ଲିକ୍ କଲେ:',
    form_sent: 'ଫର୍ମ ପଠାଗଲା! ପ୍ରକୃତ ୱେବସାଇଟରେ ଏହି ଡାଟା ସର୍ଭରକୁ ଯାଆନ୍ତା:',
    form_empty: '(କୌଣସି ଇନପୁଟ୍‌ର name ନାହିଁ)',
    res_fail: 'ଏହି ଫାଇଲ୍ ଲୋଡ୍ ହେଲା ନାହିଁ। ନାମ ଯାଞ୍ଚ କରନ୍ତୁ, କିମ୍ବା ପୂରା ୱେବ୍ ଠିକଣା ଦିଅନ୍ତୁ:',
    lint_unclosed: '<{tag}> ଖୋଲାଯାଇଛି, କିନ୍ତୁ ବନ୍ଦ କରାଯାଇନାହିଁ।',
    lint_stray: '</{tag}> ଏପରି ଏକ ଟ୍ୟାଗ୍ ବନ୍ଦ କରୁଛି ଯାହା ଖୋଲାଯାଇ ନଥିଲା।',
    lint_void: '<{tag}> ପାଇଁ ବନ୍ଦ କରିବା ଟ୍ୟାଗ୍ ଦରକାର ନାହିଁ।',
    lint_unknown: '<{tag}> କୌଣସି HTML ଟ୍ୟାଗ୍ ନୁହେଁ। ବନାନ ଯାଞ୍ଚ କରନ୍ତୁ।',
    lint_comment: 'ଗୋଟିଏ କମେଣ୍ଟ <!-- କୁ --> ଦେଇ ବନ୍ଦ କରାଯାଇନାହିଁ।',
    saved_ok: '"ମୋ ପ୍ରୋଜେକ୍ଟ"ରେ ସେଭ୍ ହେଲା।',
    save_failed: 'ସେଭ୍ ହୋଇପାରିଲା ନାହିଁ। ବୋଧହୁଏ ବ୍ରାଉଜରର ଷ୍ଟୋରେଜ୍ ଭରିଯାଇଛି।',
    projects_empty: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପ୍ରୋଜେକ୍ଟ ସେଭ୍ ହୋଇନାହିଁ। କପି ରଖିବାକୁ "ପ୍ରୋଜେକ୍ଟ ସେଭ୍ କରନ୍ତୁ" ଦବାନ୍ତୁ।',
    open_btn: 'ଖୋଲନ୍ତୁ',
    confirm_replace: 'ଏଡିଟରର କୋଡ୍ ବଦଳାଇବେ? "ମୋ ପ୍ରୋଜେକ୍ଟ"ରେ ସେଭ୍ ହୋଇନଥିବା ପରିବର୍ତ୍ତନ ହଜିଯିବ।',
    confirm_delete: '"{name}" ପ୍ରୋଜେକ୍ଟ ଡିଲିଟ୍ କରିବେ?',
    deleted: 'ଡିଲିଟ୍ ହେଲା।',
    opened_file: '{name} ଖୋଲିଲା।',
    file_too_big: 'ଏହି ଫାଇଲ୍ ବହୁତ ବଡ଼ (1 MBରୁ ଅଧିକ)।',
    file_bad: 'ଏହି ଫାଇଲ୍ ପଢ଼ି ହେଲା ନାହିଁ।',
    link_too_big: 'ଏହି ପ୍ରୋଜେକ୍ଟ ଲିଙ୍କ ପାଇଁ ବହୁତ ବଡ଼। ତା’ ବଦଳରେ .html ଡାଉନଲୋଡ୍ କରନ୍ତୁ।',
    shared_loaded: 'ସେୟାର୍ ହୋଇଥିବା ପ୍ରୋଜେକ୍ଟ ଖୋଲିଲା। ଆପଣଙ୍କ ପୂର୍ବ କାମ "ମୋ ପ୍ରୋଜେକ୍ଟ"ରେ ସୁରକ୍ଷିତ ଅଛି।',
    backup_suffix: 'ପୂର୍ବ କାମ',
    untitled: 'ମୋ ୱେବ୍ ପେଜ୍',
    saved_at: 'ସେଭ୍ ହୋଇଛି: {date}',
    cheat_title: 'ଚିଟ୍-ସିଟ୍: ଟ୍ୟାଗ୍, ଷ୍ଟାଇଲ୍ ଓ କମାଣ୍ଡ',
    cheat_intro: 'ସବୁଠାରୁ ଉପଯୋଗୀ HTML ଟ୍ୟାଗ୍, CSS ଷ୍ଟାଇଲ୍ ଓ JavaScript କମାଣ୍ଡ। କୋଡ୍‌ରେ ଯୋଡ଼ିବାକୁ "ଯୋଡ଼ନ୍ତୁ" ଦବାନ୍ତୁ।',
    cheat_search: 'ଖୋଜନ୍ତୁ, ଯେପରି table ବା color',
    insert: 'ଯୋଡ଼ନ୍ତୁ',
    inserted: '{file}ରେ ଯୋଡ଼ାଗଲା।',
    print_cheat: 'ଚିଟ୍-ସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    no_match: 'କିଛି ମିଳିଲା ନାହିଁ।',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ · ଶ୍ରେଣୀ ପାଇଁ ଚିନ୍ତାଧାରା',
    help_1: 'ଗୋଟିଏ ଟେମ୍ପଲେଟ୍ ବାଛନ୍ତୁ, ତା’ପରେ ତାର ଶବ୍ଦ, ରଙ୍ଗ ଓ ଆକାର ବଦଳାନ୍ତୁ। ଆପଣ ଲେଖିବା ସାଙ୍ଗେ ସାଙ୍ଗେ ପ୍ରିଭ୍ୟୁ ବଦଳେ।',
    help_2: 'HTML ପେଜ୍ ତିଆରି କରେ, CSS ତାକୁ ସୁନ୍ଦର କରେ ଓ JavaScript ତାକୁ କାମ କରାଏ। ପ୍ରତ୍ୟେକର ନିଜସ୍ୱ ଟ୍ୟାବ୍ ଅଛି।',
    help_3: 'JavaScriptରେ console.log() ଲେଖି କନସୋଲରେ ମୂଲ୍ୟ ଦେଖନ୍ତୁ। ଭୁଲ ବା ଟ୍ୟାଗ୍ ଗଣ୍ଡଗୋଳ ହେଲେ ଧାଡ଼ି ନମ୍ବର ଦେଖାଏ: ସେଥିରେ କ୍ଲିକ୍ କରି ସିଧା ସେଠାକୁ ଯାଆନ୍ତୁ।',
    help_4: '"ପ୍ରୋଜେକ୍ଟ ସେଭ୍ କରନ୍ତୁ" ଏହି ଡିଭାଇସରେ କପି ରଖେ। ".html ଡାଉନଲୋଡ୍ କରନ୍ତୁ"ରେ ଗୋଟିଏ ଫାଇଲ୍ ମିଳେ ଯାହା ଯେକୌଣସି ବ୍ରାଉଜରରେ, ଇଣ୍ଟରନେଟ୍ ବିନା ମଧ୍ୟ, ଖୋଲେ।',
    help_5: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟ: ପ୍ରତ୍ୟେକ ଛାତ୍ରଛାତ୍ରୀ ନିଜ ଗାଁ ବା ସହର ବିଷୟରେ ଗୋଟିଏ ପେଜ୍ ତିଆରି କରନ୍ତୁ, ଯେଉଁଥିରେ ଗୋଟିଏ ହେଡିଂ, ବୁଲିବା ପାଇଁ 3ଟି ସ୍ଥାନର ତାଲିକା ଓ ପର୍ବପର୍ବାଣିର ଗୋଟିଏ ଟେବୁଲ୍ ଥିବ। ତା’ପରେ ଯୋଡ଼ି ଯୋଡ଼ି ହୋଇ ପେଜ୍ ଅଦଳବଦଳ କରି ପ୍ରତ୍ୟେକେ ଗୋଟିଏ ଲେଖାଏଁ ଉନ୍ନତି ପରାମର୍ଶ ଦିଅନ୍ତୁ।',
    help_6: 'ସ୍ମାର୍ଟବୋର୍ଡରେ A+ ଓ ଫୁଲ୍-ସ୍କ୍ରିନ୍ ପ୍ରିଭ୍ୟୁ ବ୍ୟବହାର କରନ୍ତୁ। ଫୋନରେ ଉପର ଟ୍ୟାବ୍ ଦେଇ HTML, CSS, JS ଓ ପ୍ରିଭ୍ୟୁ ମଧ୍ୟରେ ଯାଆନ୍ତୁ।',
    print_title: '"{name}"ର କୋଡ୍'
  },
  ta: {
    app_title: 'வலைப்பக்கம் உருவாக்கி',
    intro: 'உண்மையான வலைப்பக்கங்களை உருவாக்கி HTML, CSS, JavaScript கற்றுக்கொள்ளுங்கள். ஒரு பக்கம் குறியீடு எழுதுங்கள், மறுபக்கம் உங்கள் பக்கம் மாறுவதைப் பாருங்கள்.',
    tpl_label: 'ஒரு வார்ப்புருவிலிருந்து தொடங்குங்கள்',
    tpl_choose: 'வார்ப்புருவைத் தேர்ந்தெடுங்கள்…',
    project_name: 'திட்டத்தின் பெயர்',
    save_project: 'திட்டத்தைச் சேமி',
    save_title: '"என் திட்டங்கள்" பகுதியில் ஒரு நகலை வை (Ctrl + S)',
    my_projects: 'என் திட்டங்கள்',
    open_html: '.html கோப்பைத் திற',
    download_html: '.html பதிவிறக்கு',
    share_link: 'பகிர்வு இணைப்பை நகலெடு',
    print_code: 'குறியீட்டை அச்சிடு',
    reset_work: 'மீண்டும் தொடங்கு',
    confirm_reset_work: 'தொடக்கப் பக்கத்துக்குத் திரும்பவா? நீங்கள் சேமித்த திட்டங்கள் பாதுகாப்பாக இருக்கும்.',
    try_this: 'இதைச் செய்து பாருங்கள்:',
    files_label: 'கோப்புகள்',
    tab_preview: 'முன்னோட்டம்',
    files_hint: 'உங்கள் பக்கம் = index.html + style.css + script.js. CSS, JS தாவல்கள் தானாகவே பக்கத்துடன் இணைக்கப்படும்.',
    editor_label: '{file} குறியீட்டுத் திருத்தி',
    keys_label: 'குறியீடு எழுதுவதற்கான விசைகள்',
    key_tab: 'உள்தள்ளு (2 இடைவெளி)',
    undo: 'செயல்தவிர்',
    redo: 'மீண்டும் செய்',
    font_smaller: 'குறியீட்டு எழுத்தைச் சிறிதாக்கு',
    font_bigger: 'குறியீட்டு எழுத்தைப் பெரிதாக்கு',
    wrap_lines: 'நீண்ட வரிகளை மடி',
    auto_close: 'டேகுகளைத் தானாக மூடு',
    esc_hint: 'Tab அழுத்தினால் 2 இடைவெளி சேரும். விசைப்பலகை மூலம் திருத்தியை விட்டு வெளியேற முதலில் Esc, பிறகு Tab அழுத்துங்கள்.',
    pos: 'வரி {line}, நெடுவரிசை {col}',
    autosaved: 'இந்தச் சாதனத்தில் தானாகச் சேமிக்கப்படுகிறது',
    run: 'இயக்கு',
    run_title: 'பக்கத்தை மீண்டும் இயக்கு (Ctrl + Enter)',
    auto_update: 'தட்டச்சு செய்யும்போதே புதுப்பி',
    width_full: 'முழு அகலம்',
    width_phone: 'கைப்பேசி அளவு',
    preview_title: 'உங்கள் வலைப்பக்கத்தின் நேரடி முன்னோட்டம்',
    preview_h: 'முன்னோட்டம்',
    console: 'கன்சோல்',
    console_empty: 'console.log() செய்திகளும் பிழைகளும் இங்கே தோன்றும்.',
    console_ph: 'JavaScript எழுதுங்கள், எ.கா. 2 + 3, பிறகு Enter அழுத்துங்கள்',
    console_input_label: 'JavaScript-இன் ஒரு வரியை இயக்கு',
    count_err: 'பிழைகள்: {n}',
    count_warn: 'எச்சரிக்கைகள்: {n}',
    console_cleared: 'கன்சோல் துடைக்கப்பட்டது.',
    err_at: '{file}, வரி {line}',
    jump_title: 'திருத்தியில் இந்த வரிக்குச் செல்',
    err_hint_undefined: 'குறிப்பு: எழுத்துக்கூட்டலைச் சரிபாருங்கள். JavaScript பெரிய, சிறிய எழுத்துகளை வேறுவேறாகக் கருதும்.',
    err_hint_null: 'குறிப்பு: அந்த உறுப்பு கிடைக்கவில்லை. JavaScript-இல் உள்ள id-யும் HTML-இல் உள்ள id-யும் ஒன்றா எனப் பாருங்கள்.',
    err_hint_syntax: 'குறிப்பு: விடுபட்ட அடைப்புக்குறி ( ) { }, மேற்கோள் குறி அல்லது காற்புள்ளி உள்ளதா எனத் தேடுங்கள்.',
    err_hint_notfn: 'குறிப்பு: செயல்கூறின் (function) பெயரையும் அதன் பின் உள்ள அடைப்புக்குறிகளையும் சரிபாருங்கள்.',
    err_hint_declared: 'குறிப்பு: இந்தப் பெயர் ஏற்கெனவே ஒரு மாறிக்கு (variable) உள்ளது. புதிய பெயர் வையுங்கள், அல்லது மதிப்பை மாற்ற வேண்டுமெனில் let / const-ஐ நீக்குங்கள்.',
    err_hint_const: 'குறிப்பு: const-ஐ மாற்ற முடியாது. மாறும் மதிப்புக்கு let பயன்படுத்துங்கள்.',
    loop_stopped: 'ஒரு மடக்கு (loop) மிக நீண்ட நேரம் ஓடியதால் நிறுத்தப்பட்டது ({where}). அந்த மடக்கு முடியும்படி இருக்கிறதா எனச் சரிபாருங்கள்.',
    modal_skipped: 'நீங்கள் தட்டச்சு செய்யும்போது {fn}() இயக்கப்படவில்லை. பார்க்க "இயக்கு" அழுத்துங்கள்:',
    link_clicked: 'முன்னோட்டத்துக்குள் இணைப்புகள் திறக்காது. நீங்கள் கிளிக் செய்தது:',
    form_sent: 'படிவம் அனுப்பப்பட்டது! உண்மையான இணையதளத்தில் இந்தத் தரவு சர்வருக்குச் செல்லும்:',
    form_empty: '(எந்த உள்ளீட்டுக்கும் name இல்லை)',
    res_fail: 'இந்தக் கோப்பை ஏற்ற முடியவில்லை. பெயரைச் சரிபாருங்கள், அல்லது முழு இணைய முகவரியைப் பயன்படுத்துங்கள்:',
    lint_unclosed: '<{tag}> திறக்கப்பட்டது, ஆனால் மூடப்படவில்லை.',
    lint_stray: '</{tag}> திறக்கப்படாத ஒரு டேகை மூடுகிறது.',
    lint_void: '<{tag}>-க்கு மூடும் டேக் தேவையில்லை.',
    lint_unknown: '<{tag}> என்பது HTML டேக் அல்ல. எழுத்துக்கூட்டலைச் சரிபாருங்கள்.',
    lint_comment: 'ஒரு குறிப்புரை <!-- என்பது --> கொண்டு மூடப்படவில்லை.',
    saved_ok: '"என் திட்டங்கள்" பகுதியில் சேமிக்கப்பட்டது.',
    save_failed: 'சேமிக்க முடியவில்லை. உலாவியின் சேமிப்பிடம் நிரம்பியிருக்கலாம்.',
    projects_empty: 'இன்னும் எந்தத் திட்டமும் சேமிக்கப்படவில்லை. நகல் வைக்க "திட்டத்தைச் சேமி" அழுத்துங்கள்.',
    open_btn: 'திற',
    confirm_replace: 'திருத்தியில் உள்ள குறியீட்டை மாற்றவா? "என் திட்டங்கள்" பகுதியில் சேமிக்காத மாற்றங்கள் அழிந்துவிடும்.',
    confirm_delete: '"{name}" திட்டத்தை நீக்கவா?',
    deleted: 'நீக்கப்பட்டது.',
    opened_file: '{name} திறக்கப்பட்டது.',
    file_too_big: 'இந்தக் கோப்பு மிகப் பெரியது (1 MB-க்கு மேல்).',
    file_bad: 'இந்தக் கோப்பைப் படிக்க முடியவில்லை.',
    link_too_big: 'இந்தத் திட்டம் இணைப்புக்கு மிகப் பெரியது. அதற்குப் பதில் .html பதிவிறக்குங்கள்.',
    shared_loaded: 'பகிரப்பட்ட திட்டம் திறக்கப்பட்டது. உங்கள் முந்தைய வேலை "என் திட்டங்கள்" பகுதியில் பாதுகாப்பாக உள்ளது.',
    backup_suffix: 'முந்தைய வேலை',
    untitled: 'என் வலைப்பக்கம்',
    saved_at: 'சேமித்தது: {date}',
    cheat_title: 'குறிப்புத்தாள்: டேகுகள், ஸ்டைல்கள், கட்டளைகள்',
    cheat_intro: 'அதிகம் பயன்படும் HTML டேகுகள், CSS ஸ்டைல்கள், JavaScript கட்டளைகள். உங்கள் குறியீட்டில் சேர்க்க "சேர்" அழுத்துங்கள்.',
    cheat_search: 'தேடுங்கள், எ.கா. table அல்லது color',
    insert: 'சேர்',
    inserted: '{file}-இல் சேர்க்கப்பட்டது.',
    print_cheat: 'குறிப்புத்தாளை அச்சிடு',
    no_match: 'எதுவும் பொருந்தவில்லை.',
    help_title: 'பயன்படுத்தும் முறை · வகுப்பறைக்கான யோசனைகள்',
    help_1: 'ஒரு வார்ப்புருவைத் தேர்ந்தெடுத்து, அதன் சொற்கள், நிறங்கள், அளவுகளை மாற்றுங்கள். நீங்கள் தட்டச்சு செய்யச் செய்ய முன்னோட்டம் மாறும்.',
    help_2: 'HTML பக்கத்தை உருவாக்குகிறது, CSS அதை அழகாக்குகிறது, JavaScript அதைச் செயல்பட வைக்கிறது. ஒவ்வொன்றுக்கும் தனித் தாவல் உண்டு.',
    help_3: 'JavaScript-இல் console.log() பயன்படுத்தி கன்சோலில் மதிப்புகளைப் பாருங்கள். பிழை அல்லது டேக் தவறு இருந்தால் வரி எண் தெரியும்: அதைக் கிளிக் செய்தால் அந்த வரிக்கே செல்லலாம்.',
    help_4: '"திட்டத்தைச் சேமி" இந்தச் சாதனத்திலேயே நகல்களை வைக்கும். ".html பதிவிறக்கு" மூலம் ஒரே கோப்பு கிடைக்கும்; அது எந்த உலாவியிலும், இணையம் இல்லாமலும் திறக்கும்.',
    help_5: 'வகுப்புச் செயல்பாடு: ஒவ்வொரு மாணவரும் தங்கள் ஊரைப் பற்றி ஒரு பக்கம் உருவாக்கட்டும்: ஒரு தலைப்பு, பார்க்க வேண்டிய 3 இடங்களின் பட்டியல், திருவிழாக்களின் ஓர் அட்டவணை. பிறகு இருவர் இருவராகப் பக்கங்களை மாற்றிக்கொண்டு ஆளுக்கு ஒரு மேம்பாட்டைப் பரிந்துரைக்கட்டும்.',
    help_6: 'ஸ்மார்ட்போர்டில் A+, முழுத்திரை முன்னோட்டம் பயன்படுத்துங்கள். கைப்பேசியில் மேலே உள்ள தாவல்களால் HTML, CSS, JS, முன்னோட்டம் இடையே மாறுங்கள்.',
    print_title: '"{name}" குறியீடு'
  },
  te: {
    app_title: 'వెబ్ పేజీ మేకర్',
    intro: 'నిజమైన వెబ్ పేజీలు తయారు చేస్తూ HTML, CSS, JavaScript నేర్చుకోండి. ఒక వైపు కోడ్ రాయండి, మరో వైపు మీ పేజీ మారడం చూడండి.',
    tpl_label: 'ఒక టెంప్లేట్‌తో మొదలుపెట్టండి',
    tpl_choose: 'టెంప్లేట్ ఎంచుకోండి…',
    project_name: 'ప్రాజెక్ట్ పేరు',
    save_project: 'ప్రాజెక్ట్ సేవ్ చేయండి',
    save_title: '"నా ప్రాజెక్ట్‌లు"లో ఒక కాపీ ఉంచండి (Ctrl + S)',
    my_projects: 'నా ప్రాజెక్ట్‌లు',
    open_html: '.html ఫైల్ తెరవండి',
    download_html: '.html డౌన్‌లోడ్ చేయండి',
    share_link: 'షేర్ లింక్ కాపీ చేయండి',
    print_code: 'కోడ్ ప్రింట్ చేయండి',
    reset_work: 'మళ్లీ మొదలుపెట్టండి',
    confirm_reset_work: 'మొదటి పేజీకి తిరిగి వెళ్లాలా? మీరు సేవ్ చేసిన ప్రాజెక్ట్‌లు సురక్షితంగా ఉంటాయి.',
    try_this: 'ఇది చేసి చూడండి:',
    files_label: 'ఫైళ్లు',
    tab_preview: 'ప్రివ్యూ',
    files_hint: 'మీ పేజీ = index.html + style.css + script.js. CSS, JS ట్యాబ్‌లు ఆటోమేటిక్‌గా పేజీకి జతవుతాయి.',
    editor_label: '{file} కోడ్ ఎడిటర్',
    keys_label: 'కోడ్ రాయడానికి కీలు',
    key_tab: 'ఇండెంట్ (2 స్పేస్‌లు)',
    undo: 'అన్‌డూ',
    redo: 'రీడూ',
    font_smaller: 'కోడ్ అక్షరాలు చిన్నవి చేయండి',
    font_bigger: 'కోడ్ అక్షరాలు పెద్దవి చేయండి',
    wrap_lines: 'పొడవైన లైన్లను మడవండి',
    auto_close: 'ట్యాగ్‌లను ఆటోమేటిక్‌గా మూసివేయి',
    esc_hint: 'Tab నొక్కితే 2 స్పేస్‌లు వస్తాయి. కీబోర్డ్‌తో ఎడిటర్ నుంచి బయటకు రావడానికి ముందు Esc, తర్వాత Tab నొక్కండి.',
    pos: 'లైన్ {line}, కాలమ్ {col}',
    autosaved: 'ఈ పరికరంలో ఆటోమేటిక్‌గా సేవ్ అవుతోంది',
    run: 'రన్ చేయండి',
    run_title: 'పేజీని మళ్లీ రన్ చేయండి (Ctrl + Enter)',
    auto_update: 'టైప్ చేస్తుండగానే అప్‌డేట్ చేయి',
    width_full: 'పూర్తి వెడల్పు',
    width_phone: 'ఫోన్ సైజు',
    preview_title: 'మీ వెబ్ పేజీ లైవ్ ప్రివ్యూ',
    preview_h: 'ప్రివ్యూ',
    console: 'కన్సోల్',
    console_empty: 'console.log() సందేశాలు, తప్పులు ఇక్కడ కనిపిస్తాయి.',
    console_ph: 'JavaScript రాయండి, ఉదా. 2 + 3, తర్వాత Enter నొక్కండి',
    console_input_label: 'JavaScript లో ఒక లైన్ రన్ చేయండి',
    count_err: 'తప్పులు: {n}',
    count_warn: 'హెచ్చరికలు: {n}',
    console_cleared: 'కన్సోల్ ఖాళీ చేయబడింది.',
    err_at: '{file}, లైన్ {line}',
    jump_title: 'ఎడిటర్‌లో ఈ లైన్‌కు వెళ్లండి',
    err_hint_undefined: 'సూచన: స్పెల్లింగ్ చూడండి. JavaScript పెద్ద, చిన్న అక్షరాలను వేర్వేరుగా చూస్తుంది.',
    err_hint_null: 'సూచన: ఎలిమెంట్ దొరకలేదు. JavaScript లోని id, HTML లోని id ఒకటేనా చూడండి.',
    err_hint_syntax: 'సూచన: ఏదైనా బ్రాకెట్ ( ) { }, కొటేషన్ గుర్తు లేదా కామా వదిలేశారేమో వెతకండి.',
    err_hint_notfn: 'సూచన: ఫంక్షన్ పేరు, దాని తర్వాతి బ్రాకెట్లు సరిచూడండి.',
    err_hint_declared: 'సూచన: ఈ పేరు ఇప్పటికే ఒక వేరియబుల్‌కు ఉంది. కొత్త పేరు పెట్టండి, లేదా విలువ మార్చాలంటే let / const తీసేయండి.',
    err_hint_const: 'సూచన: const ను మార్చలేం. మారే విలువకు let వాడండి.',
    loop_stopped: 'ఒక లూప్ చాలా సేపు నడిచింది, అందుకే దాన్ని ఆపేశాం ({where}). లూప్ ఎప్పటికైనా ముగిసేలా చూడండి.',
    modal_skipped: 'మీరు టైప్ చేస్తున్నప్పుడు {fn}() రన్ కాలేదు. చూడటానికి "రన్ చేయండి" నొక్కండి:',
    link_clicked: 'ప్రివ్యూలో లింక్‌లు తెరుచుకోవు. మీరు క్లిక్ చేసింది:',
    form_sent: 'ఫారం పంపబడింది! నిజమైన వెబ్‌సైట్‌లో ఈ డేటా సర్వర్‌కు వెళ్తుంది:',
    form_empty: '(ఏ ఇన్‌పుట్‌కూ name లేదు)',
    res_fail: 'ఈ ఫైల్ లోడ్ కాలేదు. పేరు చూడండి, లేదా పూర్తి వెబ్ చిరునామా వాడండి:',
    lint_unclosed: '<{tag}> తెరిచారు, కానీ మూసివేయలేదు.',
    lint_stray: '</{tag}> తెరవని ఒక ట్యాగ్‌ను మూసివేస్తోంది.',
    lint_void: '<{tag}> కి మూసే ట్యాగ్ అవసరం లేదు.',
    lint_unknown: '<{tag}> HTML ట్యాగ్ కాదు. స్పెల్లింగ్ చూడండి.',
    lint_comment: 'ఒక కామెంట్ <!-- ను --> తో మూసివేయలేదు.',
    saved_ok: '"నా ప్రాజెక్ట్‌లు"లో సేవ్ అయింది.',
    save_failed: 'సేవ్ చేయలేకపోయాం. బ్రౌజర్ స్టోరేజ్ నిండిపోయి ఉండవచ్చు.',
    projects_empty: 'ఇంకా ఏ ప్రాజెక్ట్‌నూ సేవ్ చేయలేదు. కాపీ ఉంచడానికి "ప్రాజెక్ట్ సేవ్ చేయండి" నొక్కండి.',
    open_btn: 'తెరవండి',
    confirm_replace: 'ఎడిటర్‌లోని కోడ్‌ను మార్చాలా? "నా ప్రాజెక్ట్‌లు"లో సేవ్ చేయని మార్పులు పోతాయి.',
    confirm_delete: '"{name}" ప్రాజెక్ట్‌ను తొలగించాలా?',
    deleted: 'తొలగించబడింది.',
    opened_file: '{name} తెరవబడింది.',
    file_too_big: 'ఈ ఫైల్ చాలా పెద్దది (1 MB కంటే ఎక్కువ).',
    file_bad: 'ఈ ఫైల్‌ను చదవలేకపోయాం.',
    link_too_big: 'ఈ ప్రాజెక్ట్ లింక్‌కు చాలా పెద్దది. బదులుగా .html డౌన్‌లోడ్ చేయండి.',
    shared_loaded: 'షేర్ చేసిన ప్రాజెక్ట్ తెరవబడింది. మీ మునుపటి పని "నా ప్రాజెక్ట్‌లు"లో సురక్షితంగా ఉంది.',
    backup_suffix: 'మునుపటి పని',
    untitled: 'నా వెబ్ పేజీ',
    saved_at: 'సేవ్ చేసింది: {date}',
    cheat_title: 'చీట్-షీట్: ట్యాగ్‌లు, స్టైల్స్, కమాండ్‌లు',
    cheat_intro: 'ఎక్కువగా ఉపయోగపడే HTML ట్యాగ్‌లు, CSS స్టైల్స్, JavaScript కమాండ్‌లు. మీ కోడ్‌లో చేర్చడానికి "చేర్చు" నొక్కండి.',
    cheat_search: 'వెతకండి, ఉదా. table లేదా color',
    insert: 'చేర్చు',
    inserted: '{file} లో చేర్చబడింది.',
    print_cheat: 'చీట్-షీట్ ప్రింట్ చేయండి',
    no_match: 'ఏదీ సరిపోలలేదు.',
    help_title: 'ఎలా వాడాలి · తరగతి కోసం ఆలోచనలు',
    help_1: 'ఒక టెంప్లేట్ ఎంచుకుని, దానిలోని పదాలు, రంగులు, సైజులు మార్చండి. మీరు టైప్ చేస్తుంటే ప్రివ్యూ మారుతూ ఉంటుంది.',
    help_2: 'HTML పేజీని నిర్మిస్తుంది, CSS దాన్ని అందంగా చేస్తుంది, JavaScript దానితో పనులు చేయిస్తుంది. ప్రతిదానికీ దాని సొంత ట్యాబ్ ఉంది.',
    help_3: 'JavaScript లో console.log() వాడి కన్సోల్‌లో విలువలు చూడండి. తప్పులు, ట్యాగ్ పొరపాట్లకు లైన్ నంబర్ కనిపిస్తుంది: దాన్ని క్లిక్ చేస్తే నేరుగా అక్కడికే వెళ్తారు.',
    help_4: '"ప్రాజెక్ట్ సేవ్ చేయండి" ఈ పరికరంలోనే కాపీలు ఉంచుతుంది. ".html డౌన్‌లోడ్ చేయండి" తో ఒకే ఫైల్ వస్తుంది; అది ఏ బ్రౌజర్‌లోనైనా, ఇంటర్నెట్ లేకున్నా తెరుచుకుంటుంది.',
    help_5: 'తరగతి కార్యకలాపం: ప్రతి విద్యార్థి తమ ఊరి గురించి ఒక పేజీ చేయాలి: ఒక హెడింగ్, చూడదగిన 3 ప్రదేశాల జాబితా, పండుగల ఒక టేబుల్. తర్వాత జంటలుగా పేజీలు మార్చుకుని, ఒక్కొక్కరు ఒక మెరుగుదల సూచించాలి.',
    help_6: 'స్మార్ట్‌బోర్డ్‌పై A+, ఫుల్-స్క్రీన్ ప్రివ్యూ వాడండి. ఫోన్‌లో పైన ఉన్న ట్యాబ్‌లతో HTML, CSS, JS, ప్రివ్యూ మధ్య మారండి.',
    print_title: '"{name}" కోడ్'
  },
  kn: {
    app_title: 'ವೆಬ್ ಪುಟ ತಯಾರಕ',
    intro: 'ನಿಜವಾದ ವೆಬ್ ಪುಟಗಳನ್ನು ಮಾಡುತ್ತಾ HTML, CSS ಮತ್ತು JavaScript ಕಲಿಯಿರಿ. ಒಂದು ಕಡೆ ಕೋಡ್ ಬರೆಯಿರಿ, ಇನ್ನೊಂದು ಕಡೆ ನಿಮ್ಮ ಪುಟ ಬದಲಾಗುವುದನ್ನು ನೋಡಿ.',
    tpl_label: 'ಟೆಂಪ್ಲೇಟ್‌ನಿಂದ ಶುರು ಮಾಡಿ',
    tpl_choose: 'ಟೆಂಪ್ಲೇಟ್ ಆಯ್ಕೆಮಾಡಿ…',
    project_name: 'ಪ್ರಾಜೆಕ್ಟ್ ಹೆಸರು',
    save_project: 'ಪ್ರಾಜೆಕ್ಟ್ ಸೇವ್ ಮಾಡಿ',
    save_title: '"ನನ್ನ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು" ಇಲ್ಲಿ ಒಂದು ಪ್ರತಿ ಇಡಿ (Ctrl + S)',
    my_projects: 'ನನ್ನ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು',
    open_html: '.html ಫೈಲ್ ತೆರೆಯಿರಿ',
    download_html: '.html ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    share_link: 'ಶೇರ್ ಲಿಂಕ್ ಕಾಪಿ ಮಾಡಿ',
    print_code: 'ಕೋಡ್ ಪ್ರಿಂಟ್ ಮಾಡಿ',
    reset_work: 'ಮತ್ತೆ ಶುರು ಮಾಡಿ',
    confirm_reset_work: 'ಆರಂಭದ ಪುಟಕ್ಕೆ ಮರಳಬೇಕೇ? ನೀವು ಸೇವ್ ಮಾಡಿದ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು ಸುರಕ್ಷಿತವಾಗಿರುತ್ತವೆ.',
    try_this: 'ಇದನ್ನು ಮಾಡಿ ನೋಡಿ:',
    files_label: 'ಫೈಲ್‌ಗಳು',
    tab_preview: 'ಪ್ರಿವ್ಯೂ',
    files_hint: 'ನಿಮ್ಮ ಪುಟ = index.html + style.css + script.js. CSS ಮತ್ತು JS ಟ್ಯಾಬ್‌ಗಳು ತಾವಾಗಿಯೇ ಪುಟಕ್ಕೆ ಸೇರಿಕೊಳ್ಳುತ್ತವೆ.',
    editor_label: '{file} ಕೋಡ್ ಎಡಿಟರ್',
    keys_label: 'ಕೋಡ್ ಬರೆಯಲು ಕೀಗಳು',
    key_tab: 'ಇಂಡೆಂಟ್ (2 ಸ್ಪೇಸ್)',
    undo: 'ಅನ್‌ಡೂ',
    redo: 'ರೀಡೂ',
    font_smaller: 'ಕೋಡ್ ಅಕ್ಷರ ಚಿಕ್ಕದಾಗಿಸಿ',
    font_bigger: 'ಕೋಡ್ ಅಕ್ಷರ ದೊಡ್ಡದಾಗಿಸಿ',
    wrap_lines: 'ಉದ್ದದ ಸಾಲುಗಳನ್ನು ಮಡಿಸಿ',
    auto_close: 'ಟ್ಯಾಗ್‌ಗಳನ್ನು ತಾನಾಗಿ ಮುಚ್ಚು',
    esc_hint: 'Tab ಒತ್ತಿದರೆ 2 ಸ್ಪೇಸ್ ಸೇರುತ್ತದೆ. ಕೀಬೋರ್ಡ್‌ನಿಂದ ಎಡಿಟರ್‌ನಿಂದ ಹೊರಬರಲು ಮೊದಲು Esc, ನಂತರ Tab ಒತ್ತಿ.',
    pos: 'ಸಾಲು {line}, ಕಾಲಮ್ {col}',
    autosaved: 'ಈ ಸಾಧನದಲ್ಲಿ ತಾನಾಗಿಯೇ ಸೇವ್ ಆಗುತ್ತಿದೆ',
    run: 'ರನ್ ಮಾಡಿ',
    run_title: 'ಪುಟವನ್ನು ಮತ್ತೆ ರನ್ ಮಾಡಿ (Ctrl + Enter)',
    auto_update: 'ಟೈಪ್ ಮಾಡುತ್ತಿರುವಾಗಲೇ ಅಪ್‌ಡೇಟ್ ಮಾಡು',
    width_full: 'ಪೂರ್ಣ ಅಗಲ',
    width_phone: 'ಫೋನ್ ಗಾತ್ರ',
    preview_title: 'ನಿಮ್ಮ ವೆಬ್ ಪುಟದ ಲೈವ್ ಪ್ರಿವ್ಯೂ',
    preview_h: 'ಪ್ರಿವ್ಯೂ',
    console: 'ಕನ್ಸೋಲ್',
    console_empty: 'console.log() ಸಂದೇಶಗಳು ಮತ್ತು ತಪ್ಪುಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',
    console_ph: 'JavaScript ಬರೆಯಿರಿ, ಉದಾ. 2 + 3, ನಂತರ Enter ಒತ್ತಿ',
    console_input_label: 'JavaScript ನ ಒಂದು ಸಾಲನ್ನು ರನ್ ಮಾಡಿ',
    count_err: 'ತಪ್ಪುಗಳು: {n}',
    count_warn: 'ಎಚ್ಚರಿಕೆಗಳು: {n}',
    console_cleared: 'ಕನ್ಸೋಲ್ ಖಾಲಿ ಮಾಡಲಾಯಿತು.',
    err_at: '{file}, ಸಾಲು {line}',
    jump_title: 'ಎಡಿಟರ್‌ನಲ್ಲಿ ಈ ಸಾಲಿಗೆ ಹೋಗಿ',
    err_hint_undefined: 'ಸಲಹೆ: ಕಾಗುಣಿತ ಪರಿಶೀಲಿಸಿ. JavaScript ದೊಡ್ಡ ಮತ್ತು ಸಣ್ಣ ಅಕ್ಷರಗಳನ್ನು ಬೇರೆ ಬೇರೆ ಎಂದು ಪರಿಗಣಿಸುತ್ತದೆ.',
    err_hint_null: 'ಸಲಹೆ: ಎಲಿಮೆಂಟ್ ಸಿಗಲಿಲ್ಲ. JavaScript ನಲ್ಲಿರುವ id ಮತ್ತು HTML ನಲ್ಲಿರುವ id ಒಂದೇ ಆಗಿವೆಯೇ ನೋಡಿ.',
    err_hint_syntax: 'ಸಲಹೆ: ಬಿಟ್ಟುಹೋದ ಆವರಣ ( ) { }, ಉದ್ಧರಣ ಚಿಹ್ನೆ ಅಥವಾ ಅಲ್ಪವಿರಾಮ ಇದೆಯೇ ಹುಡುಕಿ.',
    err_hint_notfn: 'ಸಲಹೆ: ಫಂಕ್ಷನ್ ಹೆಸರು ಮತ್ತು ಅದರ ನಂತರದ ಆವರಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    err_hint_declared: 'ಸಲಹೆ: ಈ ಹೆಸರು ಈಗಾಗಲೇ ಒಂದು ವೇರಿಯಬಲ್‌ಗೆ ಇದೆ. ಹೊಸ ಹೆಸರು ಕೊಡಿ, ಅಥವಾ ಮೌಲ್ಯ ಬದಲಿಸಬೇಕಿದ್ದರೆ let / const ತೆಗೆದುಹಾಕಿ.',
    err_hint_const: 'ಸಲಹೆ: const ಅನ್ನು ಬದಲಿಸಲು ಆಗುವುದಿಲ್ಲ. ಬದಲಾಗುವ ಮೌಲ್ಯಕ್ಕೆ let ಬಳಸಿ.',
    loop_stopped: 'ಒಂದು ಲೂಪ್ ತುಂಬಾ ಹೊತ್ತು ಓಡುತ್ತಿತ್ತು, ಆದ್ದರಿಂದ ಅದನ್ನು ನಿಲ್ಲಿಸಲಾಯಿತು ({where}). ಲೂಪ್ ಕೊನೆಗೊಳ್ಳುವಂತೆ ನೋಡಿಕೊಳ್ಳಿ.',
    modal_skipped: 'ನೀವು ಟೈಪ್ ಮಾಡುತ್ತಿದ್ದಾಗ {fn}() ರನ್ ಆಗಲಿಲ್ಲ. ನೋಡಲು "ರನ್ ಮಾಡಿ" ಒತ್ತಿ:',
    link_clicked: 'ಪ್ರಿವ್ಯೂ ಒಳಗೆ ಲಿಂಕ್‌ಗಳು ತೆರೆಯುವುದಿಲ್ಲ. ನೀವು ಕ್ಲಿಕ್ ಮಾಡಿದ್ದು:',
    form_sent: 'ಫಾರ್ಮ್ ಕಳುಹಿಸಲಾಯಿತು! ನಿಜವಾದ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಈ ಡೇಟಾ ಸರ್ವರ್‌ಗೆ ಹೋಗುತ್ತಿತ್ತು:',
    form_empty: '(ಯಾವ ಇನ್‌ಪುಟ್‌ಗೂ name ಇಲ್ಲ)',
    res_fail: 'ಈ ಫೈಲ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ. ಹೆಸರು ಪರಿಶೀಲಿಸಿ, ಅಥವಾ ಪೂರ್ಣ ವೆಬ್ ವಿಳಾಸ ಬಳಸಿ:',
    lint_unclosed: '<{tag}> ತೆರೆಯಲಾಗಿದೆ, ಆದರೆ ಮುಚ್ಚಿಲ್ಲ.',
    lint_stray: '</{tag}> ತೆರೆಯದೇ ಇರುವ ಟ್ಯಾಗ್ ಅನ್ನು ಮುಚ್ಚುತ್ತಿದೆ.',
    lint_void: '<{tag}> ಗೆ ಮುಚ್ಚುವ ಟ್ಯಾಗ್ ಬೇಕಿಲ್ಲ.',
    lint_unknown: '<{tag}> HTML ಟ್ಯಾಗ್ ಅಲ್ಲ. ಕಾಗುಣಿತ ಪರಿಶೀಲಿಸಿ.',
    lint_comment: 'ಒಂದು ಕಾಮೆಂಟ್ <!-- ಅನ್ನು --> ನಿಂದ ಮುಚ್ಚಿಲ್ಲ.',
    saved_ok: '"ನನ್ನ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು" ಇಲ್ಲಿ ಸೇವ್ ಆಯಿತು.',
    save_failed: 'ಸೇವ್ ಮಾಡಲಾಗಲಿಲ್ಲ. ಬ್ರೌಸರ್ ಸಂಗ್ರಹ ತುಂಬಿರಬಹುದು.',
    projects_empty: 'ಇನ್ನೂ ಯಾವ ಪ್ರಾಜೆಕ್ಟ್ ಕೂಡ ಸೇವ್ ಆಗಿಲ್ಲ. ಪ್ರತಿ ಇಡಲು "ಪ್ರಾಜೆಕ್ಟ್ ಸೇವ್ ಮಾಡಿ" ಒತ್ತಿ.',
    open_btn: 'ತೆರೆಯಿರಿ',
    confirm_replace: 'ಎಡಿಟರ್‌ನ ಕೋಡ್ ಬದಲಿಸಬೇಕೇ? "ನನ್ನ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು" ಇಲ್ಲಿ ಸೇವ್ ಆಗದ ಬದಲಾವಣೆಗಳು ಹೋಗುತ್ತವೆ.',
    confirm_delete: '"{name}" ಪ್ರಾಜೆಕ್ಟ್ ಅಳಿಸಬೇಕೇ?',
    deleted: 'ಅಳಿಸಲಾಗಿದೆ.',
    opened_file: '{name} ತೆರೆಯಲಾಗಿದೆ.',
    file_too_big: 'ಈ ಫೈಲ್ ತುಂಬಾ ದೊಡ್ಡದು (1 MB ಗಿಂತ ಹೆಚ್ಚು).',
    file_bad: 'ಈ ಫೈಲ್ ಓದಲಾಗಲಿಲ್ಲ.',
    link_too_big: 'ಈ ಪ್ರಾಜೆಕ್ಟ್ ಲಿಂಕ್‌ಗೆ ತುಂಬಾ ದೊಡ್ಡದು. ಬದಲಿಗೆ .html ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
    shared_loaded: 'ಶೇರ್ ಮಾಡಿದ ಪ್ರಾಜೆಕ್ಟ್ ತೆರೆಯಲಾಗಿದೆ. ನಿಮ್ಮ ಹಿಂದಿನ ಕೆಲಸ "ನನ್ನ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು" ಇಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿದೆ.',
    backup_suffix: 'ಹಿಂದಿನ ಕೆಲಸ',
    untitled: 'ನನ್ನ ವೆಬ್ ಪುಟ',
    saved_at: 'ಸೇವ್ ಮಾಡಿದ್ದು: {date}',
    cheat_title: 'ಚೀಟ್-ಶೀಟ್: ಟ್ಯಾಗ್‌ಗಳು, ಸ್ಟೈಲ್‌ಗಳು, ಕಮಾಂಡ್‌ಗಳು',
    cheat_intro: 'ಹೆಚ್ಚು ಉಪಯುಕ್ತ HTML ಟ್ಯಾಗ್‌ಗಳು, CSS ಸ್ಟೈಲ್‌ಗಳು ಮತ್ತು JavaScript ಕಮಾಂಡ್‌ಗಳು. ನಿಮ್ಮ ಕೋಡ್‌ಗೆ ಸೇರಿಸಲು "ಸೇರಿಸಿ" ಒತ್ತಿ.',
    cheat_search: 'ಹುಡುಕಿ, ಉದಾ. table ಅಥವಾ color',
    insert: 'ಸೇರಿಸಿ',
    inserted: '{file} ಗೆ ಸೇರಿಸಲಾಗಿದೆ.',
    print_cheat: 'ಚೀಟ್-ಶೀಟ್ ಪ್ರಿಂಟ್ ಮಾಡಿ',
    no_match: 'ಯಾವುದೂ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ.',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ · ತರಗತಿಗಾಗಿ ಐಡಿಯಾಗಳು',
    help_1: 'ಒಂದು ಟೆಂಪ್ಲೇಟ್ ಆಯ್ಕೆಮಾಡಿ, ನಂತರ ಅದರ ಪದಗಳು, ಬಣ್ಣಗಳು ಮತ್ತು ಗಾತ್ರಗಳನ್ನು ಬದಲಿಸಿ. ನೀವು ಟೈಪ್ ಮಾಡಿದಂತೆ ಪ್ರಿವ್ಯೂ ಬದಲಾಗುತ್ತದೆ.',
    help_2: 'HTML ಪುಟವನ್ನು ಕಟ್ಟುತ್ತದೆ, CSS ಅದನ್ನು ಸುಂದರಗೊಳಿಸುತ್ತದೆ ಮತ್ತು JavaScript ಅದರಿಂದ ಕೆಲಸ ಮಾಡಿಸುತ್ತದೆ. ಪ್ರತಿಯೊಂದಕ್ಕೂ ಬೇರೆ ಟ್ಯಾಬ್ ಇದೆ.',
    help_3: 'JavaScript ನಲ್ಲಿ console.log() ಬಳಸಿ ಕನ್ಸೋಲ್‌ನಲ್ಲಿ ಮೌಲ್ಯಗಳನ್ನು ನೋಡಿ. ತಪ್ಪು ಅಥವಾ ಟ್ಯಾಗ್ ಗೊಂದಲ ಇದ್ದರೆ ಸಾಲಿನ ಸಂಖ್ಯೆ ಕಾಣುತ್ತದೆ: ಅದನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿದರೆ ನೇರವಾಗಿ ಅಲ್ಲಿಗೆ ಹೋಗುತ್ತೀರಿ.',
    help_4: '"ಪ್ರಾಜೆಕ್ಟ್ ಸೇವ್ ಮಾಡಿ" ಈ ಸಾಧನದಲ್ಲೇ ಪ್ರತಿಗಳನ್ನು ಇಡುತ್ತದೆ. ".html ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" ಯಿಂದ ಒಂದೇ ಫೈಲ್ ಸಿಗುತ್ತದೆ; ಅದು ಯಾವುದೇ ಬ್ರೌಸರ್‌ನಲ್ಲಿ, ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ತೆರೆಯುತ್ತದೆ.',
    help_5: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿ ತಮ್ಮ ಊರಿನ ಬಗ್ಗೆ ಒಂದು ಪುಟ ಮಾಡಲಿ: ಒಂದು ಶೀರ್ಷಿಕೆ, ನೋಡಬೇಕಾದ 3 ಸ್ಥಳಗಳ ಪಟ್ಟಿ ಮತ್ತು ಹಬ್ಬಗಳ ಒಂದು ಟೇಬಲ್. ನಂತರ ಜೋಡಿಗಳಾಗಿ ಪುಟಗಳನ್ನು ಬದಲಾಯಿಸಿಕೊಂಡು ತಲಾ ಒಂದು ಸುಧಾರಣೆ ಸೂಚಿಸಲಿ.',
    help_6: 'ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ A+ ಮತ್ತು ಫುಲ್-ಸ್ಕ್ರೀನ್ ಪ್ರಿವ್ಯೂ ಬಳಸಿ. ಫೋನ್‌ನಲ್ಲಿ ಮೇಲಿನ ಟ್ಯಾಬ್‌ಗಳ ಮೂಲಕ HTML, CSS, JS ಮತ್ತು ಪ್ರಿವ್ಯೂ ನಡುವೆ ಬದಲಿಸಿ.',
    print_title: '"{name}" ಕೋಡ್'
  },
  ml: {
    app_title: 'വെബ് പേജ് മേക്കർ',
    intro: 'യഥാർത്ഥ വെബ് പേജുകൾ ഉണ്ടാക്കിക്കൊണ്ട് HTML, CSS, JavaScript എന്നിവ പഠിക്കാം. ഒരു വശത്ത് കോഡ് എഴുതൂ, മറുവശത്ത് നിങ്ങളുടെ പേജ് മാറുന്നത് കാണൂ.',
    tpl_label: 'ഒരു ടെംപ്ലേറ്റിൽ നിന്ന് തുടങ്ങാം',
    tpl_choose: 'ടെംപ്ലേറ്റ് തിരഞ്ഞെടുക്കൂ…',
    project_name: 'പ്രോജക്ടിന്റെ പേര്',
    save_project: 'പ്രോജക്ട് സേവ് ചെയ്യൂ',
    save_title: '"എന്റെ പ്രോജക്ടുകൾ" എന്നതിൽ ഒരു കോപ്പി സൂക്ഷിക്കൂ (Ctrl + S)',
    my_projects: 'എന്റെ പ്രോജക്ടുകൾ',
    open_html: '.html ഫയൽ തുറക്കൂ',
    download_html: '.html ഡൗൺലോഡ് ചെയ്യൂ',
    share_link: 'ഷെയർ ലിങ്ക് കോപ്പി ചെയ്യൂ',
    print_code: 'കോഡ് പ്രിന്റ് ചെയ്യൂ',
    reset_work: 'വീണ്ടും തുടങ്ങൂ',
    confirm_reset_work: 'തുടക്ക പേജിലേക്ക് മടങ്ങണോ? നിങ്ങൾ സേവ് ചെയ്ത പ്രോജക്ടുകൾ സുരക്ഷിതമായിരിക്കും.',
    try_this: 'ഇത് ചെയ്തുനോക്കൂ:',
    files_label: 'ഫയലുകൾ',
    tab_preview: 'പ്രിവ്യൂ',
    files_hint: 'നിങ്ങളുടെ പേജ് = index.html + style.css + script.js. CSS, JS ടാബുകൾ സ്വയം പേജിനോട് ചേരും.',
    editor_label: '{file} കോഡ് എഡിറ്റർ',
    keys_label: 'കോഡ് എഴുതാനുള്ള കീകൾ',
    key_tab: 'ഇൻഡന്റ് (2 സ്പേസ്)',
    undo: 'അൺഡൂ',
    redo: 'റീഡൂ',
    font_smaller: 'കോഡിന്റെ അക്ഷരം ചെറുതാക്കൂ',
    font_bigger: 'കോഡിന്റെ അക്ഷരം വലുതാക്കൂ',
    wrap_lines: 'നീണ്ട വരികൾ മടക്കൂ',
    auto_close: 'ടാഗുകൾ സ്വയം അടയ്ക്കുക',
    esc_hint: 'Tab അമർത്തിയാൽ 2 സ്പേസ് ചേരും. കീബോർഡ് ഉപയോഗിച്ച് എഡിറ്ററിൽ നിന്ന് പുറത്തുകടക്കാൻ ആദ്യം Esc, പിന്നെ Tab അമർത്തൂ.',
    pos: 'വരി {line}, കോളം {col}',
    autosaved: 'ഈ ഉപകരണത്തിൽ സ്വയം സേവ് ആകുന്നു',
    run: 'റൺ ചെയ്യൂ',
    run_title: 'പേജ് വീണ്ടും റൺ ചെയ്യൂ (Ctrl + Enter)',
    auto_update: 'ടൈപ്പ് ചെയ്യുമ്പോൾത്തന്നെ പുതുക്കൂ',
    width_full: 'മുഴുവൻ വീതി',
    width_phone: 'ഫോൺ വലുപ്പം',
    preview_title: 'നിങ്ങളുടെ വെബ് പേജിന്റെ ലൈവ് പ്രിവ്യൂ',
    preview_h: 'പ്രിവ്യൂ',
    console: 'കൺസോൾ',
    console_empty: 'console.log() സന്ദേശങ്ങളും പിശകുകളും ഇവിടെ കാണാം.',
    console_ph: 'JavaScript എഴുതൂ, ഉദാ. 2 + 3, എന്നിട്ട് Enter അമർത്തൂ',
    console_input_label: 'JavaScript-ന്റെ ഒരു വരി റൺ ചെയ്യൂ',
    count_err: 'പിശകുകൾ: {n}',
    count_warn: 'മുന്നറിയിപ്പുകൾ: {n}',
    console_cleared: 'കൺസോൾ മായ്ച്ചു.',
    err_at: '{file}, വരി {line}',
    jump_title: 'എഡിറ്ററിൽ ഈ വരിയിലേക്ക് പോകൂ',
    err_hint_undefined: 'സൂചന: സ്പെല്ലിങ് പരിശോധിക്കൂ. JavaScript വലിയക്ഷരവും ചെറിയക്ഷരവും വ്യത്യസ്തമായാണ് കാണുന്നത്.',
    err_hint_null: 'സൂചന: എലമെന്റ് കണ്ടെത്തിയില്ല. JavaScript-ലെ id-യും HTML-ലെ id-യും ഒന്നാണോ എന്ന് നോക്കൂ.',
    err_hint_syntax: 'സൂചന: വിട്ടുപോയ ബ്രാക്കറ്റ് ( ) { }, ഉദ്ധരണിചിഹ്നം അല്ലെങ്കിൽ കോമ ഉണ്ടോ എന്ന് തിരയൂ.',
    err_hint_notfn: 'സൂചന: ഫംഗ്ഷന്റെ പേരും അതിനുശേഷമുള്ള ബ്രാക്കറ്റുകളും പരിശോധിക്കൂ.',
    err_hint_declared: 'സൂചന: ഈ പേര് നേരത്തേ ഒരു വേരിയബിളിന് ഉണ്ട്. പുതിയ പേര് നൽകൂ, അല്ലെങ്കിൽ മൂല്യം മാറ്റാനാണെങ്കിൽ let / const ഒഴിവാക്കൂ.',
    err_hint_const: 'സൂചന: const മാറ്റാനാവില്ല. മാറുന്ന മൂല്യത്തിന് let ഉപയോഗിക്കൂ.',
    loop_stopped: 'ഒരു ലൂപ്പ് വളരെ നേരം ഓടിക്കൊണ്ടിരുന്നു, അതിനാൽ അത് നിർത്തി ({where}). ലൂപ്പ് അവസാനിക്കാൻ കഴിയുമെന്ന് ഉറപ്പാക്കൂ.',
    modal_skipped: 'നിങ്ങൾ ടൈപ്പ് ചെയ്യുമ്പോൾ {fn}() റൺ ചെയ്തില്ല. കാണാൻ "റൺ ചെയ്യൂ" അമർത്തൂ:',
    link_clicked: 'പ്രിവ്യൂവിനുള്ളിൽ ലിങ്കുകൾ തുറക്കില്ല. നിങ്ങൾ ക്ലിക്ക് ചെയ്തത്:',
    form_sent: 'ഫോം അയച്ചു! യഥാർത്ഥ വെബ്സൈറ്റിൽ ഈ ഡേറ്റ സെർവറിലേക്ക് പോകുമായിരുന്നു:',
    form_empty: '(ഒരു ഇൻപുട്ടിനും name ഇല്ല)',
    res_fail: 'ഈ ഫയൽ ലോഡ് ആയില്ല. പേര് പരിശോധിക്കൂ, അല്ലെങ്കിൽ മുഴുവൻ വെബ് വിലാസം ഉപയോഗിക്കൂ:',
    lint_unclosed: '<{tag}> തുറന്നിട്ടുണ്ട്, പക്ഷേ അടച്ചിട്ടില്ല.',
    lint_stray: '</{tag}> തുറക്കാത്ത ഒരു ടാഗ് അടയ്ക്കുന്നു.',
    lint_void: '<{tag}>-ന് അടയ്ക്കുന്ന ടാഗ് ആവശ്യമില്ല.',
    lint_unknown: '<{tag}> ഒരു HTML ടാഗ് അല്ല. സ്പെല്ലിങ് പരിശോധിക്കൂ.',
    lint_comment: 'ഒരു കമന്റ് <!-- എന്നത് --> കൊണ്ട് അടച്ചിട്ടില്ല.',
    saved_ok: '"എന്റെ പ്രോജക്ടുകൾ" എന്നതിൽ സേവ് ചെയ്തു.',
    save_failed: 'സേവ് ചെയ്യാനായില്ല. ബ്രൗസറിന്റെ സ്റ്റോറേജ് നിറഞ്ഞിരിക്കാം.',
    projects_empty: 'ഇതുവരെ ഒരു പ്രോജക്ടും സേവ് ചെയ്തിട്ടില്ല. കോപ്പി സൂക്ഷിക്കാൻ "പ്രോജക്ട് സേവ് ചെയ്യൂ" അമർത്തൂ.',
    open_btn: 'തുറക്കൂ',
    confirm_replace: 'എഡിറ്ററിലെ കോഡ് മാറ്റണോ? "എന്റെ പ്രോജക്ടുകൾ" എന്നതിൽ സേവ് ചെയ്യാത്ത മാറ്റങ്ങൾ നഷ്ടമാകും.',
    confirm_delete: '"{name}" എന്ന പ്രോജക്ട് ഡിലീറ്റ് ചെയ്യണോ?',
    deleted: 'ഡിലീറ്റ് ചെയ്തു.',
    opened_file: '{name} തുറന്നു.',
    file_too_big: 'ഈ ഫയൽ വളരെ വലുതാണ് (1 MB-യിൽ കൂടുതൽ).',
    file_bad: 'ഈ ഫയൽ വായിക്കാനായില്ല.',
    link_too_big: 'ഈ പ്രോജക്ട് ലിങ്കിന് വളരെ വലുതാണ്. പകരം .html ഡൗൺലോഡ് ചെയ്യൂ.',
    shared_loaded: 'ഷെയർ ചെയ്ത പ്രോജക്ട് തുറന്നു. നിങ്ങളുടെ മുമ്പത്തെ ജോലി "എന്റെ പ്രോജക്ടുകൾ" എന്നതിൽ സുരക്ഷിതമാണ്.',
    backup_suffix: 'മുമ്പത്തെ ജോലി',
    untitled: 'എന്റെ വെബ് പേജ്',
    saved_at: 'സേവ് ചെയ്തത്: {date}',
    cheat_title: 'ചീറ്റ്-ഷീറ്റ്: ടാഗുകൾ, സ്റ്റൈലുകൾ, കമാൻഡുകൾ',
    cheat_intro: 'ഏറ്റവും ഉപകാരമുള്ള HTML ടാഗുകൾ, CSS സ്റ്റൈലുകൾ, JavaScript കമാൻഡുകൾ. കോഡിൽ ചേർക്കാൻ "ചേർക്കൂ" അമർത്തൂ.',
    cheat_search: 'തിരയൂ, ഉദാ. table അല്ലെങ്കിൽ color',
    insert: 'ചേർക്കൂ',
    inserted: '{file}-ൽ ചേർത്തു.',
    print_cheat: 'ചീറ്റ്-ഷീറ്റ് പ്രിന്റ് ചെയ്യൂ',
    no_match: 'ഒന്നും പൊരുത്തപ്പെട്ടില്ല.',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം · ക്ലാസ് മുറിക്കുള്ള ആശയങ്ങൾ',
    help_1: 'ഒരു ടെംപ്ലേറ്റ് തിരഞ്ഞെടുക്കൂ, എന്നിട്ട് അതിലെ വാക്കുകളും നിറങ്ങളും വലുപ്പങ്ങളും മാറ്റൂ. ടൈപ്പ് ചെയ്യുന്നതിനനുസരിച്ച് പ്രിവ്യൂ മാറും.',
    help_2: 'HTML പേജ് നിർമ്മിക്കുന്നു, CSS അതിനെ ഭംഗിയാക്കുന്നു, JavaScript അതിനെക്കൊണ്ട് കാര്യങ്ങൾ ചെയ്യിക്കുന്നു. ഓരോന്നിനും സ്വന്തം ടാബുണ്ട്.',
    help_3: 'JavaScript-ൽ console.log() ഉപയോഗിച്ച് കൺസോളിൽ മൂല്യങ്ങൾ കാണൂ. പിശകുകൾക്കും ടാഗ് തെറ്റുകൾക്കും വരി നമ്പർ കാണിക്കും: അതിൽ ക്ലിക്ക് ചെയ്താൽ നേരെ ആ വരിയിലെത്താം.',
    help_4: '"പ്രോജക്ട് സേവ് ചെയ്യൂ" ഈ ഉപകരണത്തിൽത്തന്നെ കോപ്പികൾ സൂക്ഷിക്കും. ".html ഡൗൺലോഡ് ചെയ്യൂ" വഴി ഒറ്റ ഫയൽ കിട്ടും; അത് ഏത് ബ്രൗസറിലും, ഇന്റർനെറ്റ് ഇല്ലാതെയും തുറക്കും.',
    help_5: 'ക്ലാസ് പ്രവർത്തനം: ഓരോ കുട്ടിയും സ്വന്തം നാടിനെക്കുറിച്ച് ഒരു പേജ് ഉണ്ടാക്കട്ടെ: ഒരു തലക്കെട്ട്, കാണേണ്ട 3 സ്ഥലങ്ങളുടെ ലിസ്റ്റ്, ഉത്സവങ്ങളുടെ ഒരു ടേബിൾ. പിന്നെ ജോഡികളായി പേജുകൾ കൈമാറി ഓരോരുത്തരും ഓരോ മെച്ചപ്പെടുത്തൽ നിർദ്ദേശിക്കട്ടെ.',
    help_6: 'സ്മാർട്ട്ബോർഡിൽ A+, ഫുൾ-സ്ക്രീൻ പ്രിവ്യൂ എന്നിവ ഉപയോഗിക്കൂ. ഫോണിൽ മുകളിലെ ടാബുകൾ വഴി HTML, CSS, JS, പ്രിവ്യൂ എന്നിവയ്ക്കിടയിൽ മാറൂ.',
    print_title: '"{name}" കോഡ്'
  },
  ur: {
    app_title: 'ویب پیج میکر',
    intro: 'اصلی ویب پیج بنا کر HTML، CSS اور JavaScript سیکھیں۔ ایک طرف کوڈ لکھیں اور دوسری طرف اپنا پیج بدلتا دیکھیں۔',
    tpl_label: 'کسی ٹیمپلیٹ سے شروع کریں',
    tpl_choose: 'ٹیمپلیٹ چنیں…',
    project_name: 'پروجیکٹ کا نام',
    save_project: 'پروجیکٹ محفوظ کریں',
    save_title: '"میرے پروجیکٹ" میں ایک کاپی رکھیں (Ctrl + S)',
    my_projects: 'میرے پروجیکٹ',
    open_html: '.html فائل کھولیں',
    download_html: '.html ڈاؤن لوڈ کریں',
    share_link: 'شیئر لنک کاپی کریں',
    print_code: 'کوڈ پرنٹ کریں',
    reset_work: 'دوبارہ شروع کریں',
    confirm_reset_work: 'شروع والے پیج پر واپس جائیں؟ آپ کے محفوظ کیے ہوئے پروجیکٹ محفوظ رہیں گے۔',
    try_this: 'یہ کر کے دیکھیں:',
    files_label: 'فائلیں',
    tab_preview: 'پری ویو',
    files_hint: 'آپ کا پیج = index.html + style.css + script.js۔ CSS اور JS ٹیب خود بخود پیج سے جڑ جاتے ہیں۔',
    editor_label: '{file} کوڈ ایڈیٹر',
    keys_label: 'کوڈ لکھنے کی کنجیاں',
    key_tab: 'انڈینٹ (2 اسپیس)',
    undo: 'واپس لیں',
    redo: 'دوبارہ کریں',
    font_smaller: 'کوڈ کے حروف چھوٹے کریں',
    font_bigger: 'کوڈ کے حروف بڑے کریں',
    wrap_lines: 'لمبی لائنیں موڑیں',
    auto_close: 'ٹیگ خود بند کریں',
    esc_hint: 'Tab دبانے سے 2 اسپیس لگتی ہیں۔ کی بورڈ سے ایڈیٹر سے باہر نکلنے کے لیے پہلے Esc اور پھر Tab دبائیں۔',
    pos: 'لائن {line}، کالم {col}',
    autosaved: 'اسی ڈیوائس پر خود بخود محفوظ ہو رہا ہے',
    run: 'چلائیں',
    run_title: 'پیج دوبارہ چلائیں (Ctrl + Enter)',
    auto_update: 'لکھتے وقت اپ ڈیٹ کریں',
    width_full: 'پوری چوڑائی',
    width_phone: 'فون کا سائز',
    preview_title: 'آپ کے ویب پیج کا لائیو پری ویو',
    preview_h: 'پری ویو',
    console: 'کنسول',
    console_empty: 'console.log() کے پیغامات اور غلطیاں یہاں نظر آئیں گی۔',
    console_ph: 'JavaScript لکھیں، جیسے 2 + 3، اور Enter دبائیں',
    console_input_label: 'JavaScript کی ایک لائن چلائیں',
    count_err: 'غلطیاں: {n}',
    count_warn: 'انتباہ: {n}',
    console_cleared: 'کنسول صاف کر دیا گیا۔',
    err_at: '{file}، لائن {line}',
    jump_title: 'ایڈیٹر میں اس لائن پر جائیں',
    err_hint_undefined: 'مشورہ: اسپیلنگ چیک کریں۔ JavaScript بڑے اور چھوٹے حروف کو الگ مانتی ہے۔',
    err_hint_null: 'مشورہ: ایلیمنٹ نہیں ملا۔ دیکھیں کہ JavaScript والی id اور HTML والی id ایک جیسی ہیں۔',
    err_hint_syntax: 'مشورہ: کوئی چھوٹا ہوا بریکٹ ( ) { }، کوٹیشن نشان یا کوما تلاش کریں۔',
    err_hint_notfn: 'مشورہ: فنکشن کا نام اور اس کے بعد والے بریکٹ چیک کریں۔',
    err_hint_declared: 'مشورہ: یہ نام پہلے سے کسی ویری ایبل کا ہے۔ نیا نام رکھیں، یا قدر بدلنی ہو تو let / const ہٹا دیں۔',
    err_hint_const: 'مشورہ: const کو بدلا نہیں جا سکتا۔ بدلنے والی قدر کے لیے let استعمال کریں۔',
    loop_stopped: 'ایک لوپ بہت دیر تک چلتا رہا، اس لیے اسے روک دیا گیا ({where})۔ یقینی بنائیں کہ لوپ ختم ہو سکے۔',
    modal_skipped: 'آپ کے لکھتے وقت {fn}() نہیں چلایا گیا۔ دیکھنے کے لیے "چلائیں" دبائیں:',
    link_clicked: 'پری ویو کے اندر لنک نہیں کھلتے۔ آپ نے کلک کیا:',
    form_sent: 'فارم بھیج دیا گیا! اصلی ویب سائٹ پر یہ ڈیٹا سرور پر جاتا:',
    form_empty: '(کسی ان پٹ کا name نہیں ہے)',
    res_fail: 'یہ فائل لوڈ نہیں ہوئی۔ نام چیک کریں یا پورا ویب پتہ استعمال کریں:',
    lint_unclosed: '<{tag}> کھولا گیا ہے مگر بند نہیں کیا گیا۔',
    lint_stray: '</{tag}> ایسا ٹیگ بند کر رہا ہے جو کھولا ہی نہیں گیا تھا۔',
    lint_void: '<{tag}> کو بند کرنے والے ٹیگ کی ضرورت نہیں ہوتی۔',
    lint_unknown: '<{tag}> کوئی HTML ٹیگ نہیں ہے۔ اسپیلنگ چیک کریں۔',
    lint_comment: 'ایک کمنٹ <!-- کو --> سے بند نہیں کیا گیا۔',
    saved_ok: '"میرے پروجیکٹ" میں محفوظ ہو گیا۔',
    save_failed: 'محفوظ نہیں ہو سکا۔ شاید براؤزر کی اسٹوریج بھر گئی ہے۔',
    projects_empty: 'ابھی کوئی پروجیکٹ محفوظ نہیں ہے۔ کاپی رکھنے کے لیے "پروجیکٹ محفوظ کریں" دبائیں۔',
    open_btn: 'کھولیں',
    confirm_replace: 'ایڈیٹر کا کوڈ بدل دیں؟ جو تبدیلیاں "میرے پروجیکٹ" میں محفوظ نہیں ہیں، وہ مٹ جائیں گی۔',
    confirm_delete: 'پروجیکٹ "{name}" حذف کر دیں؟',
    deleted: 'حذف کر دیا۔',
    opened_file: '{name} کھل گئی۔',
    file_too_big: 'یہ فائل بہت بڑی ہے (1 MB سے زیادہ)۔',
    file_bad: 'یہ فائل پڑھی نہیں جا سکی۔',
    link_too_big: 'یہ پروجیکٹ لنک کے لیے بہت بڑا ہے۔ اس کی جگہ .html ڈاؤن لوڈ کریں۔',
    shared_loaded: 'شیئر کیا گیا پروجیکٹ کھل گیا۔ آپ کا پچھلا کام "میرے پروجیکٹ" میں محفوظ ہے۔',
    backup_suffix: 'پچھلا کام',
    untitled: 'میرا ویب پیج',
    saved_at: 'محفوظ کیا: {date}',
    cheat_title: 'چیٹ شیٹ: ٹیگ، اسٹائل اور کمانڈ',
    cheat_intro: 'سب سے کام کے HTML ٹیگ، CSS اسٹائل اور JavaScript کمانڈ۔ کوڈ میں شامل کرنے کے لیے "شامل کریں" دبائیں۔',
    cheat_search: 'تلاش کریں، جیسے table یا color',
    insert: 'شامل کریں',
    inserted: '{file} میں شامل کر دیا۔',
    print_cheat: 'چیٹ شیٹ پرنٹ کریں',
    no_match: 'کچھ نہیں ملا۔',
    help_title: 'استعمال کا طریقہ · کلاس کے لیے آئیڈیاز',
    help_1: 'کوئی ٹیمپلیٹ چنیں، پھر اس کے الفاظ، رنگ اور سائز بدلیں۔ جیسے جیسے آپ لکھتے ہیں، پری ویو بدلتا جاتا ہے۔',
    help_2: 'HTML پیج بناتا ہے، CSS اسے خوبصورت بناتا ہے اور JavaScript اس سے کام کرواتی ہے۔ ہر ایک کا اپنا ٹیب ہے۔',
    help_3: 'JavaScript میں console.log() لکھ کر کنسول میں قدریں دیکھیں۔ غلطی یا ٹیگ کی چوک پر لائن نمبر دکھتا ہے: اس پر کلک کر کے سیدھے وہیں پہنچیں۔',
    help_4: '"پروجیکٹ محفوظ کریں" اسی ڈیوائس پر کاپیاں رکھتا ہے۔ ".html ڈاؤن لوڈ کریں" سے ایک فائل ملتی ہے جو کسی بھی براؤزر میں، انٹرنیٹ کے بغیر بھی، کھلتی ہے۔',
    help_5: 'کلاس سرگرمی: ہر طالب علم اپنے شہر یا گاؤں پر ایک پیج بنائے جس میں ایک ہیڈنگ، گھومنے کی 3 جگہوں کی فہرست اور تہواروں کا ایک ٹیبل ہو۔ پھر جوڑیاں آپس میں پیج بدلیں اور ہر کوئی ایک بہتری تجویز کرے۔',
    help_6: 'اسمارٹ بورڈ پر A+ اور فل اسکرین پری ویو استعمال کریں۔ فون پر اوپر کے ٹیب سے HTML، CSS، JS اور پری ویو کے بیچ جائیں۔',
    print_title: '"{name}" کا کوڈ'
  }
};
