/* UI strings for the Chemical Equation Balancer. Keys must be identical in all 12 languages.
   Shared words (copy, print, clear, next, previous, yes, no, confirm_reset, fullscreen) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Chemical Equation Balancer',
    intro: 'Balance any chemical equation step by step, count the atoms on both sides, and practise 15 reactions from NCERT Class 10.',
    tab_balance: 'Balancer',
    tab_practice: 'Practice: NCERT Class 10',
    eq_label: 'Type a chemical equation',
    eq_hint: 'Put → (or -> or =) between the two sides and + between substances. Brackets, hydrates like CuSO4·5H2O, states like (aq) and charges like Fe^3+ or SO4^2- also work.',
    balance_btn: 'Balance',
    keys_aria: 'Insert a symbol',
    try_these: 'Try these examples',
    result_title: 'Balanced equation',
    status_ok: 'Balanced ✓',
    status_many: 'More than one answer',
    atoms_title: 'Atom count on both sides',
    col_element: 'Element',
    col_left: 'Left side (reactants)',
    col_right: 'Right side (products)',
    col_ok: 'Equal?',
    charge: 'Charge',
    law: 'Law of conservation of mass: in a chemical reaction atoms are only rearranged. None are created or destroyed, so each element must have the same count on both sides.',
    steps_title: 'How it is solved (algebra method)',
    s1_title: 'List the elements',
    s1_text: 'These elements appear in the equation:',
    s2_title: 'Put an unknown number before each formula',
    s2_text: 'Each letter is a coefficient that we have to find.',
    s3_title: 'Write one equation for each element',
    s3_text: 'Atoms of each element on the left = atoms of that element on the right.',
    s3_charge: 'The total charge must also be the same on both sides.',
    s4_title: 'Solve the equations',
    s4_let: 'Let {eq} (the number in front of {f}). Then:',
    s4_together: 'Solving the remaining equations together gives:',
    s4_mult: 'Multiply every number by {m} to get the smallest whole numbers:',
    s4_whole: 'These are already the smallest whole numbers:',
    s5_title: 'Check',
    s5_text: 'Count every atom again with these numbers (see the table). Both sides match, so the equation is balanced.',
    many_text: 'This equation can be balanced in more than one way, because it mixes two or more separate reactions. One possible answer is shown. Check the formulas with your teacher.',
    many_none: 'This equation can be balanced in many ways, so there is no single answer. Check the formulas.',
    err_empty: 'Type an equation first, for example: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'Put exactly one arrow (→, -> or =) between the reactants and the products.',
    err_side_empty: 'One side of the arrow is empty. Write substances on both sides.',
    err_plus: 'Something is missing next to a + sign.',
    err_bad_char: 'The sign "{c}" cannot be used in a formula. Use element symbols, numbers and brackets.',
    err_element: '"{e}" is not an element symbol. Check capital and small letters: Co is cobalt but CO is carbon monoxide.',
    err_lower: 'Element symbols start with a capital letter (H, Fe, Cl). Check "{f}".',
    err_bracket: 'The brackets in "{f}" do not match.',
    err_formula: 'Could not read the formula "{f}".',
    err_coef: 'A number in front of a formula must be a whole number, 1 or more.',
    err_too_many: 'Too many substances. Use at most {n}.',
    err_only_side: '{e} appears on only one side of the arrow, so it can never be balanced. Check the formulas.',
    err_impossible: 'This equation cannot be balanced. A formula may be wrong, or a reactant or product may be missing.',
    err_charge: 'The charges cannot be made equal. Check the charges, or add electrons (e-) for a half reaction.',
    err_zero: 'Cannot balance: {f} would get the number 0, which means it takes no part. Remove it or check the formulas.',
    err_side: 'Cannot balance with positive numbers: {f} would have to be on the other side of the arrow.',
    yours_label: 'You typed:',
    yours_ok: 'Your numbers are correct. The equation is balanced.',
    yours_multiple: 'Your numbers balance the equation, but they are not the smallest. Divide all of them by {k}.',
    yours_bad: 'Your numbers do not balance the equation yet. Not equal: {list}. The correct answer is shown above.',
    pr_pick: 'Choose a reaction',
    pr_num: 'Reaction {n} of {total}',
    pr_solved: 'Solved: {n} of {total}',
    pr_enter: 'Write the smallest whole numbers in the boxes. An empty box means 1.',
    pr_done: 'Solved',
    pr_shown: 'Answer seen',
    coef_aria: 'Number in front of {f}',
    check: 'Check',
    hint: 'Hint',
    show_answer: 'Show answer',
    fb_ok: 'Correct! The equation is balanced with the smallest whole numbers.',
    fb_ok_seen: 'Correct! But you saw the answer to this one, so it is not counted as solved.',
    fb_multiple: 'It is balanced, but these are not the smallest numbers. Divide all of them by {k}.',
    fb_bad: 'Not balanced yet. Look at: {list}.',
    fb_invalid: 'Use whole numbers from 1 to 99 in the boxes.',
    fb_shown: 'Here is the answer. Check each atom in the table, then try the next reaction.',
    hint_atoms: 'Count {e}: {l} on the left and {r} on the right. Change the number in front of {list}.',
    hint_reveal: 'The number in front of {f} is {n}.',
    hint_done: 'All the numbers are right. Press Check.',
    type_q: 'What type of reaction is this?',
    type_ok: 'Correct!',
    type_bad: 'Not quite. Look at the answer below.',
    type_label: 'Type',
    also: 'also',
    t_combination: 'Combination',
    t_decomposition: 'Decomposition',
    t_displacement: 'Displacement',
    t_double: 'Double displacement',
    t_combustion: 'Combustion',
    t_redox: 'Redox',
    x_combination: 'Combination: two or more substances join to form a single new substance (A + B → AB).',
    x_decomposition: 'Decomposition: one substance breaks down into simpler substances using heat, light or electricity (AB → A + B).',
    x_displacement: 'Displacement: a more reactive element pushes a less reactive element out of its compound (A + BC → AC + B).',
    x_double: 'Double displacement: two compounds swap their ions, and often a solid precipitate forms (AB + CD → AD + CB).',
    x_combustion: 'Combustion: a substance burns in oxygen and gives heat and light. Fuels like methane and LPG give carbon dioxide and water.',
    x_redox: 'Redox: one substance is oxidised (gains oxygen or loses hydrogen) while another is reduced (loses oxygen or gains hydrogen).',
    cond_heat: 'Heat',
    cond_sun: 'Sunlight',
    cond_elec: 'Electricity',
    states_note: '(s) solid · (l) liquid · (g) gas · (aq) dissolved in water',
    print_ws: 'Print worksheet',
    ws_title: 'Balance these chemical equations',
    ws_name: 'Name',
    ws_class: 'Class',
    ws_date: 'Date',
    ws_instr: 'Write the smallest whole number in each blank, then write the type of reaction.',
    ws_key: 'Answer key',
    reset_progress: 'Reset progress',
    help_title: 'How to use / Ideas for the classroom',
    help_1: 'Type an equation with correct capital letters (Co is cobalt, CO is carbon monoxide) and press Balance. You can use →, -> or = for the arrow.',
    help_2: 'Brackets ( ) and [ ], hydrates (CuSO4·5H2O or CuSO4.5H2O), states (s), (l), (g), (aq) and ions (Fe^3+, SO4^2-, e-) are understood.',
    help_3: 'Read "How it is solved": the app writes one equation for each element and solves them. Compare it with the hit-and-trial method in your NCERT book.',
    help_4: 'Type your own numbers in front of the formulas (for example 2H2 + O2 -> 2H2O) to check whether your answer is right.',
    help_5: 'Practice has 15 reactions from NCERT Class 10. Fill the boxes, press Check, use Hint when stuck, and name the type of reaction.',
    help_6: 'Classroom activity: show a Practice reaction on the smartboard in full screen. Teams balance it on paper in 2 minutes, then one team explains its steps. Print the worksheet for homework.'
  },
  hi: {
    app_title: 'रासायनिक समीकरण संतुलन',
    intro: 'किसी भी रासायनिक समीकरण को चरण-दर-चरण संतुलित करें, दोनों ओर के परमाणु गिनें और NCERT कक्षा 10 की 15 अभिक्रियाओं का अभ्यास करें।',
    tab_balance: 'संतुलन करें',
    tab_practice: 'अभ्यास: NCERT कक्षा 10',
    eq_label: 'रासायनिक समीकरण लिखें',
    eq_hint: 'दोनों पक्षों के बीच → (या -> या =) और पदार्थों के बीच + लगाएँ। कोष्ठक, CuSO4·5H2O जैसे जलयोजित लवण, (aq) जैसी अवस्थाएँ और Fe^3+ या SO4^2- जैसे आवेश भी चलते हैं।',
    balance_btn: 'संतुलित करें',
    keys_aria: 'चिह्न जोड़ें',
    try_these: 'ये उदाहरण आज़माएँ',
    result_title: 'संतुलित समीकरण',
    status_ok: 'संतुलित ✓',
    status_many: 'एक से अधिक उत्तर',
    atoms_title: 'दोनों ओर परमाणुओं की गिनती',
    col_element: 'तत्व',
    col_left: 'बायाँ पक्ष (अभिकारक)',
    col_right: 'दायाँ पक्ष (उत्पाद)',
    col_ok: 'बराबर?',
    charge: 'आवेश',
    law: 'द्रव्यमान संरक्षण का नियम: रासायनिक अभिक्रिया में परमाणु केवल नए ढंग से जुड़ते हैं। न कोई बनता है, न नष्ट होता है, इसलिए हर तत्व की गिनती दोनों ओर बराबर होनी चाहिए।',
    steps_title: 'हल कैसे हुआ (बीजगणित विधि)',
    s1_title: 'तत्वों की सूची बनाएँ',
    s1_text: 'समीकरण में ये तत्व हैं:',
    s2_title: 'हर सूत्र के आगे एक अज्ञात संख्या रखें',
    s2_text: 'हर अक्षर एक गुणांक है जिसे हमें ढूँढना है।',
    s3_title: 'हर तत्व के लिए एक समीकरण लिखें',
    s3_text: 'बाईं ओर किसी तत्व के परमाणु = दाईं ओर उसी तत्व के परमाणु।',
    s3_charge: 'कुल आवेश भी दोनों ओर बराबर होना चाहिए।',
    s4_title: 'समीकरण हल करें',
    s4_let: 'मान लें {eq} ({f} के आगे की संख्या)। तब:',
    s4_together: 'बचे हुए समीकरणों को एक साथ हल करने पर:',
    s4_mult: 'सबसे छोटी पूर्ण संख्याएँ पाने के लिए हर संख्या को {m} से गुणा करें:',
    s4_whole: 'ये पहले से ही सबसे छोटी पूर्ण संख्याएँ हैं:',
    s5_title: 'जाँच करें',
    s5_text: 'इन संख्याओं के साथ हर परमाणु फिर से गिनें (तालिका देखें)। दोनों ओर बराबर है, इसलिए समीकरण संतुलित है।',
    many_text: 'यह समीकरण एक से अधिक तरीकों से संतुलित हो सकता है, क्योंकि इसमें दो या अधिक अलग-अलग अभिक्रियाएँ मिली हुई हैं। एक संभावित उत्तर दिखाया गया है। सूत्रों को अपने शिक्षक से जाँच लें।',
    many_none: 'यह समीकरण कई तरीकों से संतुलित हो सकता है, इसलिए कोई एक उत्तर नहीं है। सूत्र जाँचें।',
    err_empty: 'पहले कोई समीकरण लिखें, जैसे: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'अभिकारकों और उत्पादों के बीच ठीक एक तीर (→, -> या =) लगाएँ।',
    err_side_empty: 'तीर का एक पक्ष खाली है। दोनों ओर पदार्थ लिखें।',
    err_plus: '+ चिह्न के पास कुछ छूट गया है।',
    err_bad_char: 'सूत्र में "{c}" चिह्न नहीं चल सकता। तत्वों के प्रतीक, अंक और कोष्ठक ही लिखें।',
    err_element: '"{e}" किसी तत्व का प्रतीक नहीं है। बड़े-छोटे अक्षर जाँचें: Co कोबाल्ट है, पर CO कार्बन मोनोऑक्साइड है।',
    err_lower: 'तत्वों के प्रतीक बड़े अक्षर से शुरू होते हैं (H, Fe, Cl)। "{f}" जाँचें।',
    err_bracket: '"{f}" में कोष्ठक ठीक से बंद नहीं हैं।',
    err_formula: 'सूत्र "{f}" पढ़ा नहीं जा सका।',
    err_coef: 'सूत्र के आगे की संख्या 1 या उससे बड़ी पूर्ण संख्या होनी चाहिए।',
    err_too_many: 'बहुत अधिक पदार्थ हैं। अधिकतम {n} लिखें।',
    err_only_side: '{e} तीर के केवल एक ओर है, इसलिए यह कभी संतुलित नहीं हो सकता। सूत्र जाँचें।',
    err_impossible: 'यह समीकरण संतुलित नहीं हो सकता। कोई सूत्र गलत हो सकता है, या कोई अभिकारक या उत्पाद छूट गया है।',
    err_charge: 'आवेश बराबर नहीं हो सकते। आवेश जाँचें, या अर्ध-अभिक्रिया के लिए इलेक्ट्रॉन (e-) जोड़ें।',
    err_zero: 'संतुलन संभव नहीं: {f} को संख्या 0 मिलेगी, यानी वह अभिक्रिया में भाग नहीं लेता। उसे हटाएँ या सूत्र जाँचें।',
    err_side: 'धनात्मक संख्याओं से संतुलन संभव नहीं: {f} को तीर के दूसरी ओर होना चाहिए।',
    yours_label: 'आपने लिखा:',
    yours_ok: 'आपकी संख्याएँ सही हैं। समीकरण संतुलित है।',
    yours_multiple: 'आपकी संख्याओं से समीकरण संतुलित है, पर ये सबसे छोटी नहीं हैं। सबको {k} से भाग दें।',
    yours_bad: 'आपकी संख्याओं से समीकरण अभी संतुलित नहीं है। बराबर नहीं: {list}। सही उत्तर ऊपर दिखाया गया है।',
    pr_pick: 'अभिक्रिया चुनें',
    pr_num: 'अभिक्रिया {n} / {total}',
    pr_solved: 'हल किए: {total} में से {n}',
    pr_enter: 'खानों में सबसे छोटी पूर्ण संख्याएँ लिखें। खाली खाने का मतलब 1 है।',
    pr_done: 'हल हो गया',
    pr_shown: 'उत्तर देखा',
    coef_aria: '{f} के आगे की संख्या',
    check: 'जाँचें',
    hint: 'संकेत',
    show_answer: 'उत्तर दिखाएँ',
    fb_ok: 'सही! समीकरण सबसे छोटी पूर्ण संख्याओं से संतुलित है।',
    fb_ok_seen: 'सही! पर आपने इसका उत्तर देख लिया था, इसलिए इसे हल किया हुआ नहीं गिना गया।',
    fb_multiple: 'संतुलित तो है, पर ये सबसे छोटी संख्याएँ नहीं हैं। सबको {k} से भाग दें।',
    fb_bad: 'अभी संतुलित नहीं है। इन्हें देखें: {list}।',
    fb_invalid: 'खानों में 1 से 99 तक की पूर्ण संख्याएँ ही लिखें।',
    fb_shown: 'यह रहा उत्तर। तालिका में हर परमाणु जाँचें, फिर अगली अभिक्रिया करें।',
    hint_atoms: '{e} गिनें: बाईं ओर {l} और दाईं ओर {r}। {list} के आगे की संख्या बदलें।',
    hint_reveal: '{f} के आगे की संख्या {n} है।',
    hint_done: 'सभी संख्याएँ सही हैं। जाँचें दबाएँ।',
    type_q: 'यह किस प्रकार की अभिक्रिया है?',
    type_ok: 'सही!',
    type_bad: 'ठीक नहीं। नीचे उत्तर देखें।',
    type_label: 'प्रकार',
    also: 'साथ ही',
    t_combination: 'संयोजन',
    t_decomposition: 'वियोजन',
    t_displacement: 'विस्थापन',
    t_double: 'द्विविस्थापन',
    t_combustion: 'दहन',
    t_redox: 'रेडॉक्स',
    x_combination: 'संयोजन: दो या अधिक पदार्थ मिलकर एक नया पदार्थ बनाते हैं (A + B → AB)।',
    x_decomposition: 'वियोजन: एक पदार्थ ऊष्मा, प्रकाश या विद्युत से टूटकर सरल पदार्थ बनाता है (AB → A + B)।',
    x_displacement: 'विस्थापन: अधिक क्रियाशील तत्व कम क्रियाशील तत्व को उसके यौगिक से हटा देता है (A + BC → AC + B)।',
    x_double: 'द्विविस्थापन: दो यौगिक अपने आयनों की अदला-बदली करते हैं, और अक्सर अवक्षेप बनता है (AB + CD → AD + CB)।',
    x_combustion: 'दहन: पदार्थ ऑक्सीजन में जलकर ऊष्मा और प्रकाश देता है। मीथेन और LPG जैसे ईंधन कार्बन डाइऑक्साइड और जल देते हैं।',
    x_redox: 'रेडॉक्स: एक पदार्थ का उपचयन होता है (ऑक्सीजन जुड़ती है या हाइड्रोजन हटती है) और दूसरे का अपचयन (ऑक्सीजन हटती है या हाइड्रोजन जुड़ती है)।',
    cond_heat: 'ऊष्मा',
    cond_sun: 'सूर्य का प्रकाश',
    cond_elec: 'विद्युत',
    states_note: '(s) ठोस · (l) द्रव · (g) गैस · (aq) जल में घुला हुआ',
    print_ws: 'वर्कशीट प्रिंट करें',
    ws_title: 'इन रासायनिक समीकरणों को संतुलित करें',
    ws_name: 'नाम',
    ws_class: 'कक्षा',
    ws_date: 'तारीख',
    ws_instr: 'हर खाली जगह में सबसे छोटी पूर्ण संख्या लिखें, फिर अभिक्रिया का प्रकार लिखें।',
    ws_key: 'उत्तर कुंजी',
    reset_progress: 'प्रगति रीसेट करें',
    help_title: 'कैसे इस्तेमाल करें / कक्षा के लिए सुझाव',
    help_1: 'सही बड़े-छोटे अक्षरों के साथ समीकरण लिखें (Co कोबाल्ट है, CO कार्बन मोनोऑक्साइड) और संतुलित करें दबाएँ। तीर के लिए →, -> या = लिख सकते हैं।',
    help_2: 'कोष्ठक ( ) और [ ], जलयोजित लवण (CuSO4·5H2O या CuSO4.5H2O), अवस्थाएँ (s), (l), (g), (aq) और आयन (Fe^3+, SO4^2-, e-) भी समझे जाते हैं।',
    help_3: '"हल कैसे हुआ" पढ़ें: ऐप हर तत्व के लिए एक समीकरण लिखकर उन्हें हल करता है। इसकी तुलना अपनी NCERT पुस्तक की हिट-एंड-ट्रायल (प्रयास और त्रुटि) विधि से करें।',
    help_4: 'सूत्रों के आगे अपनी संख्याएँ लिखें (जैसे 2H2 + O2 -> 2H2O), ऐप बताएगा कि आपका उत्तर सही है या नहीं।',
    help_5: 'अभ्यास में NCERT कक्षा 10 की 15 अभिक्रियाएँ हैं। खाने भरें, जाँचें दबाएँ, अटकने पर संकेत लें और अभिक्रिया का प्रकार बताएँ।',
    help_6: 'कक्षा गतिविधि: स्मार्टबोर्ड पर फुल स्क्रीन में अभ्यास की कोई अभिक्रिया दिखाएँ। टीमें 2 मिनट में कागज़ पर उसे संतुलित करें, फिर एक टीम अपने चरण समझाए। गृहकार्य के लिए वर्कशीट प्रिंट करें।'
  },
  bn: {
    app_title: 'রাসায়নিক সমীকরণের সমতা',
    intro: 'যেকোনো রাসায়নিক সমীকরণ ধাপে ধাপে সমতা করুন, দুই দিকের পরমাণু গুনুন, আর NCERT দশম শ্রেণির 15টি বিক্রিয়া অনুশীলন করুন।',
    tab_balance: 'সমতা করুন',
    tab_practice: 'অনুশীলন: NCERT 10',
    eq_label: 'একটি রাসায়নিক সমীকরণ লিখুন',
    eq_hint: 'দুই দিকের মাঝে → (বা -> বা =) আর পদার্থগুলোর মাঝে + দিন। বন্ধনী, CuSO4·5H2O-এর মতো কেলাস জলযুক্ত লবণ, (aq)-এর মতো অবস্থা আর Fe^3+ বা SO4^2- এর মতো আধানও চলবে।',
    balance_btn: 'সমতা করুন',
    keys_aria: 'চিহ্ন বসান',
    try_these: 'এই উদাহরণগুলো চেষ্টা করুন',
    result_title: 'সমতাযুক্ত সমীকরণ',
    status_ok: 'সমতা হয়েছে ✓',
    status_many: 'একাধিক উত্তর',
    atoms_title: 'দুই দিকে পরমাণুর সংখ্যা',
    col_element: 'মৌল',
    col_left: 'বাম দিক (বিক্রিয়ক)',
    col_right: 'ডান দিক (বিক্রিয়াজাত পদার্থ)',
    col_ok: 'সমান?',
    charge: 'আধান',
    law: 'ভরের সংরক্ষণ সূত্র: রাসায়নিক বিক্রিয়ায় পরমাণুগুলো শুধু নতুনভাবে সাজে। কোনো পরমাণু তৈরি বা ধ্বংস হয় না, তাই প্রতিটি মৌলের সংখ্যা দুই দিকে সমান হতে হবে।',
    steps_title: 'কীভাবে সমাধান হলো (বীজগণিত পদ্ধতি)',
    s1_title: 'মৌলগুলোর তালিকা করুন',
    s1_text: 'সমীকরণে এই মৌলগুলো আছে:',
    s2_title: 'প্রতিটি সংকেতের আগে একটি অজানা সংখ্যা বসান',
    s2_text: 'প্রতিটি অক্ষর একটি সহগ, যা আমাদের খুঁজে বের করতে হবে।',
    s3_title: 'প্রতিটি মৌলের জন্য একটি সমীকরণ লিখুন',
    s3_text: 'বাম দিকে কোনো মৌলের পরমাণু = ডান দিকে সেই মৌলের পরমাণু।',
    s3_charge: 'মোট আধানও দুই দিকে সমান হতে হবে।',
    s4_title: 'সমীকরণগুলো সমাধান করুন',
    s4_let: 'ধরা যাক {eq} ({f}-এর আগের সংখ্যা)। তাহলে:',
    s4_together: 'বাকি সমীকরণগুলো একসঙ্গে সমাধান করে পাই:',
    s4_mult: 'সবচেয়ে ছোট পূর্ণসংখ্যা পেতে প্রতিটি সংখ্যাকে {m} দিয়ে গুণ করুন:',
    s4_whole: 'এগুলোই সবচেয়ে ছোট পূর্ণসংখ্যা:',
    s5_title: 'যাচাই করুন',
    s5_text: 'এই সংখ্যাগুলো দিয়ে আবার প্রতিটি পরমাণু গুনুন (সারণি দেখুন)। দুই দিক মিলে গেছে, তাই সমীকরণটি সমতাযুক্ত।',
    many_text: 'এই সমীকরণটি একাধিক উপায়ে সমতা করা যায়, কারণ এতে দুই বা তার বেশি আলাদা বিক্রিয়া মিশে আছে। একটি সম্ভাব্য উত্তর দেখানো হলো। সংকেতগুলো শিক্ষকের সঙ্গে মিলিয়ে নিন।',
    many_none: 'এই সমীকরণটি অনেকভাবে সমতা করা যায়, তাই কোনো একটি উত্তর নেই। সংকেতগুলো যাচাই করুন।',
    err_empty: 'আগে একটি সমীকরণ লিখুন, যেমন: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'বিক্রিয়ক আর বিক্রিয়াজাত পদার্থের মাঝে ঠিক একটি তীর (→, -> বা =) দিন।',
    err_side_empty: 'তীরের একটি দিক ফাঁকা। দুই দিকেই পদার্থ লিখুন।',
    err_plus: '+ চিহ্নের পাশে কিছু বাদ পড়েছে।',
    err_bad_char: 'সংকেতে "{c}" চিহ্ন ব্যবহার করা যায় না। মৌলের প্রতীক, সংখ্যা আর বন্ধনী ব্যবহার করুন।',
    err_element: '"{e}" কোনো মৌলের প্রতীক নয়। বড় ও ছোট হাতের অক্ষর দেখুন: Co হলো কোবাল্ট, কিন্তু CO হলো কার্বন মনোক্সাইড।',
    err_lower: 'মৌলের প্রতীক বড় হাতের অক্ষরে শুরু হয় (H, Fe, Cl)। "{f}" দেখুন।',
    err_bracket: '"{f}"-এর বন্ধনীগুলো মিলছে না।',
    err_formula: '"{f}" সংকেতটি পড়া গেল না।',
    err_coef: 'সংকেতের আগের সংখ্যা 1 বা তার বেশি পূর্ণসংখ্যা হতে হবে।',
    err_too_many: 'অনেক বেশি পদার্থ। সর্বোচ্চ {n}টি লিখুন।',
    err_only_side: '{e} তীরের শুধু এক দিকে আছে, তাই এটি কখনো সমতা হবে না। সংকেতগুলো দেখুন।',
    err_impossible: 'এই সমীকরণের সমতা করা যায় না। কোনো সংকেত ভুল থাকতে পারে, বা কোনো বিক্রিয়ক বা বিক্রিয়াজাত পদার্থ বাদ পড়েছে।',
    err_charge: 'আধান সমান করা যাচ্ছে না। আধানগুলো দেখুন, বা অর্ধ-বিক্রিয়ার জন্য ইলেকট্রন (e-) যোগ করুন।',
    err_zero: 'সমতা সম্ভব নয়: {f}-এর সংখ্যা 0 হবে, অর্থাৎ এটি বিক্রিয়ায় অংশ নেয় না। এটি বাদ দিন বা সংকেতগুলো দেখুন।',
    err_side: 'ধনাত্মক সংখ্যা দিয়ে সমতা সম্ভব নয়: {f}-কে তীরের অন্য দিকে থাকতে হবে।',
    yours_label: 'আপনি লিখেছেন:',
    yours_ok: 'আপনার সংখ্যাগুলো ঠিক। সমীকরণটি সমতাযুক্ত।',
    yours_multiple: 'আপনার সংখ্যাগুলোয় সমতা হয়েছে, কিন্তু এগুলো সবচেয়ে ছোট নয়। সবগুলোকে {k} দিয়ে ভাগ করুন।',
    yours_bad: 'আপনার সংখ্যাগুলোয় এখনও সমতা হয়নি। সমান নয়: {list}। সঠিক উত্তর ওপরে দেখানো হয়েছে।',
    pr_pick: 'একটি বিক্রিয়া বাছুন',
    pr_num: 'বিক্রিয়া {n} / {total}',
    pr_solved: 'সমাধান হয়েছে: {total}টির মধ্যে {n}টি',
    pr_enter: 'ঘরগুলোতে সবচেয়ে ছোট পূর্ণসংখ্যা লিখুন। ফাঁকা ঘর মানে 1।',
    pr_done: 'সমাধান হয়েছে',
    pr_shown: 'উত্তর দেখা হয়েছে',
    coef_aria: '{f}-এর আগের সংখ্যা',
    check: 'যাচাই করুন',
    hint: 'ইঙ্গিত',
    show_answer: 'উত্তর দেখুন',
    fb_ok: 'ঠিক! সমীকরণটি সবচেয়ে ছোট পূর্ণসংখ্যা দিয়ে সমতাযুক্ত।',
    fb_ok_seen: 'ঠিক! কিন্তু আপনি এটির উত্তর দেখে নিয়েছিলেন, তাই এটি সমাধান হিসেবে গোনা হয়নি।',
    fb_multiple: 'সমতা হয়েছে, কিন্তু এগুলো সবচেয়ে ছোট সংখ্যা নয়। সবগুলোকে {k} দিয়ে ভাগ করুন।',
    fb_bad: 'এখনও সমতা হয়নি। এগুলো দেখুন: {list}।',
    fb_invalid: 'ঘরগুলোতে 1 থেকে 99-এর মধ্যে পূর্ণসংখ্যা লিখুন।',
    fb_shown: 'এই হলো উত্তর। সারণিতে প্রতিটি পরমাণু মিলিয়ে দেখুন, তারপর পরের বিক্রিয়াটি করুন।',
    hint_atoms: '{e} গুনুন: বাম দিকে {l}টি আর ডান দিকে {r}টি। {list}-এর আগের সংখ্যা বদলান।',
    hint_reveal: '{f}-এর আগের সংখ্যা হলো {n}।',
    hint_done: 'সব সংখ্যা ঠিক আছে। যাচাই করুন টিপুন।',
    type_q: 'এটি কোন ধরনের বিক্রিয়া?',
    type_ok: 'ঠিক!',
    type_bad: 'ঠিক হলো না। নিচে উত্তর দেখুন।',
    type_label: 'ধরন',
    also: 'এছাড়াও',
    t_combination: 'সংযোজন',
    t_decomposition: 'বিয়োজন',
    t_displacement: 'প্রতিস্থাপন',
    t_double: 'দ্বি-প্রতিস্থাপন',
    t_combustion: 'দহন',
    t_redox: 'জারণ-বিজারণ',
    x_combination: 'সংযোজন: দুই বা তার বেশি পদার্থ মিলে একটি নতুন পদার্থ তৈরি করে (A + B → AB)।',
    x_decomposition: 'বিয়োজন: একটি পদার্থ তাপ, আলো বা বিদ্যুতের সাহায্যে ভেঙে সরল পদার্থে পরিণত হয় (AB → A + B)।',
    x_displacement: 'প্রতিস্থাপন: বেশি সক্রিয় মৌল কম সক্রিয় মৌলকে তার যৌগ থেকে সরিয়ে দেয় (A + BC → AC + B)।',
    x_double: 'দ্বি-প্রতিস্থাপন: দুটি যৌগ নিজেদের আয়ন বদলাবদলি করে, আর প্রায়ই অধঃক্ষেপ তৈরি হয় (AB + CD → AD + CB)।',
    x_combustion: 'দহন: পদার্থ অক্সিজেনে পুড়ে তাপ ও আলো দেয়। মিথেন ও LPG-এর মতো জ্বালানি থেকে কার্বন ডাইঅক্সাইড ও জল তৈরি হয়।',
    x_redox: 'জারণ-বিজারণ: একটি পদার্থের জারণ হয় (অক্সিজেন যুক্ত হয় বা হাইড্রোজেন সরে যায়), আর অন্যটির বিজারণ হয় (অক্সিজেন সরে যায় বা হাইড্রোজেন যুক্ত হয়)।',
    cond_heat: 'তাপ',
    cond_sun: 'সূর্যালোক',
    cond_elec: 'বিদ্যুৎ',
    states_note: '(s) কঠিন · (l) তরল · (g) গ্যাস · (aq) জলে দ্রবীভূত',
    print_ws: 'ওয়ার্কশিট প্রিন্ট করুন',
    ws_title: 'এই রাসায়নিক সমীকরণগুলোর সমতা করুন',
    ws_name: 'নাম',
    ws_class: 'শ্রেণি',
    ws_date: 'তারিখ',
    ws_instr: 'প্রতিটি ফাঁকা জায়গায় সবচেয়ে ছোট পূর্ণসংখ্যা লিখুন, তারপর বিক্রিয়ার ধরন লিখুন।',
    ws_key: 'উত্তরমালা',
    reset_progress: 'অগ্রগতি রিসেট করুন',
    help_title: 'কীভাবে ব্যবহার করবেন / শ্রেণিকক্ষের জন্য পরামর্শ',
    help_1: 'ঠিক বড় ও ছোট হাতের অক্ষরে সমীকরণ লিখুন (Co হলো কোবাল্ট, CO হলো কার্বন মনোক্সাইড) আর সমতা করুন টিপুন। তীরের জায়গায় →, -> বা = লিখতে পারেন।',
    help_2: 'বন্ধনী ( ) ও [ ], কেলাস জলযুক্ত লবণ (CuSO4·5H2O বা CuSO4.5H2O), অবস্থা (s), (l), (g), (aq) আর আয়ন (Fe^3+, SO4^2-, e-) সবই বোঝে।',
    help_3: '"কীভাবে সমাধান হলো" পড়ুন: অ্যাপটি প্রতিটি মৌলের জন্য একটি সমীকরণ লিখে সেগুলো সমাধান করে। NCERT বইয়ের হিট-অ্যান্ড-ট্রায়াল (চেষ্টা ও ভুল) পদ্ধতির সঙ্গে তুলনা করুন।',
    help_4: 'সংকেতের আগে নিজের সংখ্যা লিখুন (যেমন 2H2 + O2 -> 2H2O), অ্যাপ জানিয়ে দেবে আপনার উত্তর ঠিক কি না।',
    help_5: 'অনুশীলনে NCERT দশম শ্রেণির 15টি বিক্রিয়া আছে। ঘর পূরণ করুন, যাচাই করুন টিপুন, আটকে গেলে ইঙ্গিত নিন, আর বিক্রিয়ার ধরন বলুন।',
    help_6: 'শ্রেণিকক্ষের কাজ: স্মার্টবোর্ডে ফুল স্ক্রিনে অনুশীলনের একটি বিক্রিয়া দেখান। দলগুলো 2 মিনিটে খাতায় সমতা করবে, তারপর একটি দল ধাপগুলো বুঝিয়ে বলবে। বাড়ির কাজের জন্য ওয়ার্কশিট প্রিন্ট করুন।'
  },
  mr: {
    app_title: 'रासायनिक समीकरण संतुलन',
    intro: 'कोणतेही रासायनिक समीकरण टप्प्याटप्प्याने संतुलित करा, दोन्ही बाजूंचे अणू मोजा आणि NCERT इयत्ता 10 च्या 15 अभिक्रियांचा सराव करा.',
    tab_balance: 'संतुलित करा',
    tab_practice: 'सराव: NCERT 10',
    eq_label: 'रासायनिक समीकरण लिहा',
    eq_hint: 'दोन बाजूंच्या मध्ये → (किंवा -> किंवा =) आणि पदार्थांच्या मध्ये + लिहा. कंस, CuSO4·5H2O सारखे जलयुक्त क्षार, (aq) सारख्या अवस्था आणि Fe^3+ किंवा SO4^2- सारखे प्रभारसुद्धा चालतात.',
    balance_btn: 'संतुलित करा',
    keys_aria: 'चिन्ह घाला',
    try_these: 'ही उदाहरणे करून पाहा',
    result_title: 'संतुलित समीकरण',
    status_ok: 'संतुलित ✓',
    status_many: 'एकापेक्षा जास्त उत्तरे',
    atoms_title: 'दोन्ही बाजूंच्या अणूंची संख्या',
    col_element: 'मूलद्रव्य',
    col_left: 'डावी बाजू (अभिक्रियाकारके)',
    col_right: 'उजवी बाजू (उत्पादिते)',
    col_ok: 'समान?',
    charge: 'प्रभार',
    law: 'वस्तुमान अक्षय्यतेचा नियम: रासायनिक अभिक्रियेत अणू फक्त नव्याने जुळतात. कोणताही अणू तयार होत नाही की नष्ट होत नाही, म्हणून प्रत्येक मूलद्रव्याची संख्या दोन्ही बाजूंना समान असली पाहिजे.',
    steps_title: 'उत्तर कसे मिळाले (बीजगणित पद्धत)',
    s1_title: 'मूलद्रव्यांची यादी करा',
    s1_text: 'समीकरणात ही मूलद्रव्ये आहेत:',
    s2_title: 'प्रत्येक सूत्रापुढे एक अज्ञात संख्या ठेवा',
    s2_text: 'प्रत्येक अक्षर हा एक गुणांक आहे, जो आपल्याला शोधायचा आहे.',
    s3_title: 'प्रत्येक मूलद्रव्यासाठी एक समीकरण लिहा',
    s3_text: 'डावीकडील एखाद्या मूलद्रव्याचे अणू = उजवीकडील त्याच मूलद्रव्याचे अणू.',
    s3_charge: 'एकूण प्रभारसुद्धा दोन्ही बाजूंना समान असला पाहिजे.',
    s4_title: 'समीकरणे सोडवा',
    s4_let: 'समजा {eq} ({f} पुढील संख्या). मग:',
    s4_together: 'उरलेली समीकरणे एकत्र सोडवल्यावर:',
    s4_mult: 'सर्वात लहान पूर्ण संख्या मिळवण्यासाठी प्रत्येक संख्येला {m} ने गुणा:',
    s4_whole: 'या आधीच सर्वात लहान पूर्ण संख्या आहेत:',
    s5_title: 'तपासा',
    s5_text: 'या संख्यांसह प्रत्येक अणू पुन्हा मोजा (तक्ता पाहा). दोन्ही बाजू जुळतात, म्हणून समीकरण संतुलित आहे.',
    many_text: 'हे समीकरण एकापेक्षा जास्त प्रकारे संतुलित करता येते, कारण त्यात दोन किंवा अधिक वेगळ्या अभिक्रिया मिसळल्या आहेत. एक शक्य उत्तर दाखवले आहे. सूत्रे शिक्षकांकडून तपासून घ्या.',
    many_none: 'हे समीकरण अनेक प्रकारे संतुलित करता येते, त्यामुळे एकच उत्तर नाही. सूत्रे तपासा.',
    err_empty: 'आधी एक समीकरण लिहा, उदाहरणार्थ: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'अभिक्रियाकारके आणि उत्पादिते यांच्यामध्ये नेमका एक बाण (→, -> किंवा =) लिहा.',
    err_side_empty: 'बाणाची एक बाजू रिकामी आहे. दोन्ही बाजूंना पदार्थ लिहा.',
    err_plus: '+ चिन्हाजवळ काहीतरी राहिले आहे.',
    err_bad_char: 'सूत्रात "{c}" हे चिन्ह वापरता येत नाही. मूलद्रव्यांच्या संज्ञा, अंक आणि कंस वापरा.',
    err_element: '"{e}" ही कोणत्याही मूलद्रव्याची संज्ञा नाही. मोठी व लहान अक्षरे तपासा: Co म्हणजे कोबाल्ट, पण CO म्हणजे कार्बन मोनॉक्साइड.',
    err_lower: 'मूलद्रव्यांच्या संज्ञा मोठ्या अक्षराने सुरू होतात (H, Fe, Cl). "{f}" तपासा.',
    err_bracket: '"{f}" मधील कंस जुळत नाहीत.',
    err_formula: '"{f}" हे सूत्र वाचता आले नाही.',
    err_coef: 'सूत्रापुढील संख्या 1 किंवा त्याहून मोठी पूर्ण संख्या असली पाहिजे.',
    err_too_many: 'खूप जास्त पदार्थ आहेत. जास्तीत जास्त {n} लिहा.',
    err_only_side: '{e} बाणाच्या फक्त एकाच बाजूला आहे, म्हणून ते कधीच संतुलित होणार नाही. सूत्रे तपासा.',
    err_impossible: 'हे समीकरण संतुलित करता येत नाही. एखादे सूत्र चुकीचे असू शकते, किंवा एखादे अभिक्रियाकारक किंवा उत्पादित राहिले असेल.',
    err_charge: 'प्रभार समान करता येत नाहीत. प्रभार तपासा, किंवा अर्ध-अभिक्रियेसाठी इलेक्ट्रॉन (e-) जोडा.',
    err_zero: 'संतुलन शक्य नाही: {f} ला संख्या 0 मिळेल, म्हणजे ते अभिक्रियेत भाग घेत नाही. ते काढा किंवा सूत्रे तपासा.',
    err_side: 'धन संख्यांनी संतुलन शक्य नाही: {f} बाणाच्या दुसऱ्या बाजूला असायला हवे.',
    yours_label: 'तुम्ही लिहिले:',
    yours_ok: 'तुमच्या संख्या बरोबर आहेत. समीकरण संतुलित आहे.',
    yours_multiple: 'तुमच्या संख्यांनी समीकरण संतुलित होते, पण त्या सर्वात लहान नाहीत. सर्वांना {k} ने भागा.',
    yours_bad: 'तुमच्या संख्यांनी समीकरण अजून संतुलित नाही. समान नाही: {list}. बरोबर उत्तर वर दाखवले आहे.',
    pr_pick: 'अभिक्रिया निवडा',
    pr_num: 'अभिक्रिया {n} / {total}',
    pr_solved: 'सोडवल्या: {total} पैकी {n}',
    pr_enter: 'चौकटींमध्ये सर्वात लहान पूर्ण संख्या लिहा. रिकामी चौकट म्हणजे 1.',
    pr_done: 'सोडवले',
    pr_shown: 'उत्तर पाहिले',
    coef_aria: '{f} पुढील संख्या',
    check: 'तपासा',
    hint: 'संकेत',
    show_answer: 'उत्तर दाखवा',
    fb_ok: 'बरोबर! समीकरण सर्वात लहान पूर्ण संख्यांनी संतुलित आहे.',
    fb_ok_seen: 'बरोबर! पण तुम्ही याचे उत्तर पाहिले होते, म्हणून हे सोडवलेले म्हणून मोजले नाही.',
    fb_multiple: 'संतुलित तर आहे, पण या सर्वात लहान संख्या नाहीत. सर्वांना {k} ने भागा.',
    fb_bad: 'अजून संतुलित नाही. हे पाहा: {list}.',
    fb_invalid: 'चौकटींमध्ये 1 ते 99 पर्यंतच्या पूर्ण संख्याच लिहा.',
    fb_shown: 'हे घ्या उत्तर. तक्त्यात प्रत्येक अणू तपासा, मग पुढची अभिक्रिया करा.',
    hint_atoms: '{e} मोजा: डावीकडे {l} आणि उजवीकडे {r}. {list} पुढील संख्या बदला.',
    hint_reveal: '{f} पुढील संख्या {n} आहे.',
    hint_done: 'सर्व संख्या बरोबर आहेत. तपासा दाबा.',
    type_q: 'ही कोणत्या प्रकारची अभिक्रिया आहे?',
    type_ok: 'बरोबर!',
    type_bad: 'नाही. खाली उत्तर पाहा.',
    type_label: 'प्रकार',
    also: 'तसेच',
    t_combination: 'संयोग',
    t_decomposition: 'अपघटन',
    t_displacement: 'विस्थापन',
    t_double: 'दुहेरी विस्थापन',
    t_combustion: 'ज्वलन',
    t_redox: 'रेडॉक्स',
    x_combination: 'संयोग: दोन किंवा अधिक पदार्थ एकत्र येऊन एक नवा पदार्थ तयार होतो (A + B → AB).',
    x_decomposition: 'अपघटन: एका पदार्थाचे उष्णता, प्रकाश किंवा विद्युत यांच्या मदतीने साध्या पदार्थांत विघटन होते (AB → A + B).',
    x_displacement: 'विस्थापन: जास्त अभिक्रियाशील मूलद्रव्य कमी अभिक्रियाशील मूलद्रव्याला त्याच्या संयुगातून बाहेर काढते (A + BC → AC + B).',
    x_double: 'दुहेरी विस्थापन: दोन संयुगे आपल्या आयनांची अदलाबदल करतात, आणि अनेकदा अवक्षेप तयार होतो (AB + CD → AD + CB).',
    x_combustion: 'ज्वलन: पदार्थ ऑक्सिजनमध्ये जळून उष्णता आणि प्रकाश देतो. मिथेन आणि LPG सारख्या इंधनांपासून कार्बन डायऑक्साइड आणि पाणी मिळते.',
    x_redox: 'रेडॉक्स: एका पदार्थाचे ऑक्सिडीकरण होते (ऑक्सिजन जोडला जातो किंवा हायड्रोजन निघतो) आणि दुसऱ्याचे क्षपण होते (ऑक्सिजन निघतो किंवा हायड्रोजन जोडला जातो).',
    cond_heat: 'उष्णता',
    cond_sun: 'सूर्यप्रकाश',
    cond_elec: 'विद्युत',
    states_note: '(s) स्थायू · (l) द्रव · (g) वायू · (aq) पाण्यात विरघळलेले',
    print_ws: 'वर्कशीट प्रिंट करा',
    ws_title: 'ही रासायनिक समीकरणे संतुलित करा',
    ws_name: 'नाव',
    ws_class: 'इयत्ता',
    ws_date: 'दिनांक',
    ws_instr: 'प्रत्येक रिकाम्या जागी सर्वात लहान पूर्ण संख्या लिहा, मग अभिक्रियेचा प्रकार लिहा.',
    ws_key: 'उत्तरसूची',
    reset_progress: 'प्रगती रीसेट करा',
    help_title: 'कसे वापरावे / वर्गासाठी कल्पना',
    help_1: 'योग्य मोठ्या-लहान अक्षरांत समीकरण लिहा (Co म्हणजे कोबाल्ट, CO म्हणजे कार्बन मोनॉक्साइड) आणि संतुलित करा दाबा. बाणासाठी →, -> किंवा = लिहू शकता.',
    help_2: 'कंस ( ) आणि [ ], जलयुक्त क्षार (CuSO4·5H2O किंवा CuSO4.5H2O), अवस्था (s), (l), (g), (aq) आणि आयन (Fe^3+, SO4^2-, e-) सगळे समजतात.',
    help_3: '"उत्तर कसे मिळाले" वाचा: ॲप प्रत्येक मूलद्रव्यासाठी एक समीकरण लिहून ती सोडवते. NCERT पुस्तकातील प्रयत्न-प्रमाद (हिट अँड ट्रायल) पद्धतीशी तुलना करा.',
    help_4: 'सूत्रांपुढे स्वतःच्या संख्या लिहा (उदा. 2H2 + O2 -> 2H2O), ॲप सांगेल की तुमचे उत्तर बरोबर आहे की नाही.',
    help_5: 'सरावात NCERT इयत्ता 10 च्या 15 अभिक्रिया आहेत. चौकटी भरा, तपासा दाबा, अडल्यास संकेत घ्या आणि अभिक्रियेचा प्रकार सांगा.',
    help_6: 'वर्गातील उपक्रम: स्मार्टबोर्डवर फुल स्क्रीनमध्ये सरावातील एक अभिक्रिया दाखवा. गटांनी 2 मिनिटांत कागदावर ती संतुलित करावी, मग एका गटाने आपल्या पायऱ्या समजावून सांगाव्या. गृहपाठासाठी वर्कशीट प्रिंट करा.'
  },
  gu: {
    app_title: 'રાસાયણિક સમીકરણ સંતુલન',
    intro: 'કોઈ પણ રાસાયણિક સમીકરણને પગલે પગલે સંતુલિત કરો, બંને બાજુના પરમાણુ ગણો અને NCERT ધોરણ 10 ની 15 પ્રક્રિયાઓનો મહાવરો કરો.',
    tab_balance: 'સંતુલિત કરો',
    tab_practice: 'મહાવરો: NCERT 10',
    eq_label: 'રાસાયણિક સમીકરણ લખો',
    eq_hint: 'બે બાજુ વચ્ચે → (અથવા -> અથવા =) અને પદાર્થો વચ્ચે + મૂકો. કૌંસ, CuSO4·5H2O જેવા સ્ફટિકજળવાળા ક્ષાર, (aq) જેવી અવસ્થાઓ અને Fe^3+ કે SO4^2- જેવા વીજભાર પણ ચાલે છે.',
    balance_btn: 'સંતુલિત કરો',
    keys_aria: 'ચિહ્ન ઉમેરો',
    try_these: 'આ ઉદાહરણો અજમાવો',
    result_title: 'સંતુલિત સમીકરણ',
    status_ok: 'સંતુલિત ✓',
    status_many: 'એકથી વધુ જવાબ',
    atoms_title: 'બંને બાજુ પરમાણુઓની ગણતરી',
    col_element: 'તત્ત્વ',
    col_left: 'ડાબી બાજુ (પ્રક્રિયકો)',
    col_right: 'જમણી બાજુ (નીપજો)',
    col_ok: 'સરખા?',
    charge: 'વીજભાર',
    law: 'દળ સંરક્ષણનો નિયમ: રાસાયણિક પ્રક્રિયામાં પરમાણુઓ ફક્ત નવી રીતે ગોઠવાય છે. કોઈ પરમાણુ બનતો કે નાશ પામતો નથી, તેથી દરેક તત્ત્વની સંખ્યા બંને બાજુ સરખી હોવી જોઈએ.',
    steps_title: 'કેવી રીતે ઉકેલ્યું (બીજગણિત પદ્ધતિ)',
    s1_title: 'તત્ત્વોની યાદી બનાવો',
    s1_text: 'સમીકરણમાં આ તત્ત્વો છે:',
    s2_title: 'દરેક સૂત્રની આગળ એક અજ્ઞાત સંખ્યા મૂકો',
    s2_text: 'દરેક અક્ષર એક ગુણાંક છે, જે આપણે શોધવાનો છે.',
    s3_title: 'દરેક તત્ત્વ માટે એક સમીકરણ લખો',
    s3_text: 'ડાબી બાજુ કોઈ તત્ત્વના પરમાણુ = જમણી બાજુ એ જ તત્ત્વના પરમાણુ.',
    s3_charge: 'કુલ વીજભાર પણ બંને બાજુ સરખો હોવો જોઈએ.',
    s4_title: 'સમીકરણો ઉકેલો',
    s4_let: 'ધારો કે {eq} ({f} ની આગળની સંખ્યા). તો:',
    s4_together: 'બાકીનાં સમીકરણો સાથે ઉકેલતાં:',
    s4_mult: 'સૌથી નાની પૂર્ણ સંખ્યાઓ મેળવવા દરેક સંખ્યાને {m} વડે ગુણો:',
    s4_whole: 'આ પહેલેથી જ સૌથી નાની પૂર્ણ સંખ્યાઓ છે:',
    s5_title: 'ચકાસો',
    s5_text: 'આ સંખ્યાઓ સાથે દરેક પરમાણુ ફરી ગણો (કોષ્ટક જુઓ). બંને બાજુ સરખી છે, તેથી સમીકરણ સંતુલિત છે.',
    many_text: 'આ સમીકરણ એકથી વધુ રીતે સંતુલિત થઈ શકે છે, કારણ કે તેમાં બે કે વધુ અલગ પ્રક્રિયાઓ ભળેલી છે. એક શક્ય જવાબ બતાવ્યો છે. સૂત્રો શિક્ષક સાથે ચકાસી લો.',
    many_none: 'આ સમીકરણ ઘણી રીતે સંતુલિત થઈ શકે છે, તેથી કોઈ એક જવાબ નથી. સૂત્રો ચકાસો.',
    err_empty: 'પહેલાં એક સમીકરણ લખો, જેમ કે: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'પ્રક્રિયકો અને નીપજો વચ્ચે બરાબર એક તીર (→, -> અથવા =) મૂકો.',
    err_side_empty: 'તીરની એક બાજુ ખાલી છે. બંને બાજુ પદાર્થો લખો.',
    err_plus: '+ ચિહ્નની પાસે કંઈક ખૂટે છે.',
    err_bad_char: 'સૂત્રમાં "{c}" ચિહ્ન વાપરી શકાય નહીં. તત્ત્વોની સંજ્ઞા, અંકો અને કૌંસ વાપરો.',
    err_element: '"{e}" કોઈ તત્ત્વની સંજ્ઞા નથી. મોટા અને નાના અક્ષરો ચકાસો: Co એ કોબાલ્ટ છે, પણ CO એ કાર્બન મોનોક્સાઇડ છે.',
    err_lower: 'તત્ત્વોની સંજ્ઞા મોટા અક્ષરથી શરૂ થાય છે (H, Fe, Cl). "{f}" ચકાસો.',
    err_bracket: '"{f}" માં કૌંસ મેળ ખાતા નથી.',
    err_formula: '"{f}" સૂત્ર વાંચી શકાયું નહીં.',
    err_coef: 'સૂત્રની આગળની સંખ્યા 1 કે તેથી મોટી પૂર્ણ સંખ્યા હોવી જોઈએ.',
    err_too_many: 'ઘણા બધા પદાર્થો છે. વધુમાં વધુ {n} લખો.',
    err_only_side: '{e} તીરની ફક્ત એક જ બાજુ છે, તેથી તે ક્યારેય સંતુલિત નહીં થાય. સૂત્રો ચકાસો.',
    err_impossible: 'આ સમીકરણ સંતુલિત થઈ શકતું નથી. કોઈ સૂત્ર ખોટું હોઈ શકે, અથવા કોઈ પ્રક્રિયક કે નીપજ ખૂટતી હોઈ શકે.',
    err_charge: 'વીજભાર સરખા થઈ શકતા નથી. વીજભાર ચકાસો, અથવા અર્ધ-પ્રક્રિયા માટે ઇલેક્ટ્રૉન (e-) ઉમેરો.',
    err_zero: 'સંતુલન શક્ય નથી: {f} ને સંખ્યા 0 મળશે, એટલે કે તે પ્રક્રિયામાં ભાગ લેતો નથી. તેને કાઢો અથવા સૂત્રો ચકાસો.',
    err_side: 'ધન સંખ્યાઓથી સંતુલન શક્ય નથી: {f} ને તીરની બીજી બાજુ હોવું જોઈએ.',
    yours_label: 'તમે લખ્યું:',
    yours_ok: 'તમારી સંખ્યાઓ સાચી છે. સમીકરણ સંતુલિત છે.',
    yours_multiple: 'તમારી સંખ્યાઓથી સમીકરણ સંતુલિત છે, પણ તે સૌથી નાની નથી. બધીને {k} વડે ભાગો.',
    yours_bad: 'તમારી સંખ્યાઓથી સમીકરણ હજુ સંતુલિત નથી. સરખા નથી: {list}. સાચો જવાબ ઉપર બતાવ્યો છે.',
    pr_pick: 'પ્રક્રિયા પસંદ કરો',
    pr_num: 'પ્રક્રિયા {n} / {total}',
    pr_solved: 'ઉકેલી: {total} માંથી {n}',
    pr_enter: 'ખાનાંમાં સૌથી નાની પૂર્ણ સંખ્યાઓ લખો. ખાલી ખાનું એટલે 1.',
    pr_done: 'ઉકેલાઈ ગયું',
    pr_shown: 'જવાબ જોયો',
    coef_aria: '{f} ની આગળની સંખ્યા',
    check: 'ચકાસો',
    hint: 'સંકેત',
    show_answer: 'જવાબ બતાવો',
    fb_ok: 'સાચું! સમીકરણ સૌથી નાની પૂર્ણ સંખ્યાઓથી સંતુલિત છે.',
    fb_ok_seen: 'સાચું! પણ તમે આનો જવાબ જોઈ લીધો હતો, તેથી તેને ઉકેલેલું ગણ્યું નથી.',
    fb_multiple: 'સંતુલિત તો છે, પણ આ સૌથી નાની સંખ્યાઓ નથી. બધીને {k} વડે ભાગો.',
    fb_bad: 'હજુ સંતુલિત નથી. આ જુઓ: {list}.',
    fb_invalid: 'ખાનાંમાં 1 થી 99 સુધીની પૂર્ણ સંખ્યાઓ જ લખો.',
    fb_shown: 'આ રહ્યો જવાબ. કોષ્ટકમાં દરેક પરમાણુ ચકાસો, પછી આગળની પ્રક્રિયા કરો.',
    hint_atoms: '{e} ગણો: ડાબી બાજુ {l} અને જમણી બાજુ {r}. {list} ની આગળની સંખ્યા બદલો.',
    hint_reveal: '{f} ની આગળની સંખ્યા {n} છે.',
    hint_done: 'બધી સંખ્યાઓ સાચી છે. ચકાસો દબાવો.',
    type_q: 'આ કયા પ્રકારની પ્રક્રિયા છે?',
    type_ok: 'સાચું!',
    type_bad: 'બરાબર નથી. નીચે જવાબ જુઓ.',
    type_label: 'પ્રકાર',
    also: 'સાથે',
    t_combination: 'સંયોગીકરણ',
    t_decomposition: 'વિઘટન',
    t_displacement: 'વિસ્થાપન',
    t_double: 'દ્વિવિસ્થાપન',
    t_combustion: 'દહન',
    t_redox: 'રેડૉક્સ',
    x_combination: 'સંયોગીકરણ: બે કે વધુ પદાર્થો જોડાઈને એક નવો પદાર્થ બનાવે છે (A + B → AB).',
    x_decomposition: 'વિઘટન: એક પદાર્થ ઉષ્મા, પ્રકાશ કે વિદ્યુતની મદદથી તૂટીને સાદા પદાર્થો બનાવે છે (AB → A + B).',
    x_displacement: 'વિસ્થાપન: વધુ સક્રિય તત્ત્વ ઓછા સક્રિય તત્ત્વને તેના સંયોજનમાંથી ખસેડી દે છે (A + BC → AC + B).',
    x_double: 'દ્વિવિસ્થાપન: બે સંયોજનો પોતાના આયનોની અદલાબદલી કરે છે, અને ઘણી વાર અવક્ષેપ બને છે (AB + CD → AD + CB).',
    x_combustion: 'દહન: પદાર્થ ઑક્સિજનમાં બળીને ઉષ્મા અને પ્રકાશ આપે છે. મિથેન અને LPG જેવાં બળતણ કાર્બન ડાયૉક્સાઇડ અને પાણી આપે છે.',
    x_redox: 'રેડૉક્સ: એક પદાર્થનું ઑક્સિડેશન થાય છે (ઑક્સિજન ઉમેરાય કે હાઇડ્રોજન દૂર થાય) અને બીજાનું રિડક્શન થાય છે (ઑક્સિજન દૂર થાય કે હાઇડ્રોજન ઉમેરાય).',
    cond_heat: 'ઉષ્મા',
    cond_sun: 'સૂર્યપ્રકાશ',
    cond_elec: 'વિદ્યુત',
    states_note: '(s) ઘન · (l) પ્રવાહી · (g) વાયુ · (aq) પાણીમાં ઓગળેલું',
    print_ws: 'વર્કશીટ પ્રિન્ટ કરો',
    ws_title: 'આ રાસાયણિક સમીકરણો સંતુલિત કરો',
    ws_name: 'નામ',
    ws_class: 'ધોરણ',
    ws_date: 'તારીખ',
    ws_instr: 'દરેક ખાલી જગ્યામાં સૌથી નાની પૂર્ણ સંખ્યા લખો, પછી પ્રક્રિયાનો પ્રકાર લખો.',
    ws_key: 'ઉત્તરસૂચિ',
    reset_progress: 'પ્રગતિ રીસેટ કરો',
    help_title: 'કેવી રીતે વાપરવું / વર્ગખંડ માટે વિચારો',
    help_1: 'સાચા મોટા-નાના અક્ષરો સાથે સમીકરણ લખો (Co એ કોબાલ્ટ, CO એ કાર્બન મોનોક્સાઇડ) અને સંતુલિત કરો દબાવો. તીર માટે →, -> કે = લખી શકો.',
    help_2: 'કૌંસ ( ) અને [ ], સ્ફટિકજળવાળા ક્ષાર (CuSO4·5H2O કે CuSO4.5H2O), અવસ્થાઓ (s), (l), (g), (aq) અને આયન (Fe^3+, SO4^2-, e-) પણ સમજાય છે.',
    help_3: '"કેવી રીતે ઉકેલ્યું" વાંચો: ઍપ દરેક તત્ત્વ માટે એક સમીકરણ લખીને તેને ઉકેલે છે. NCERT પુસ્તકની પ્રયત્ન-ભૂલ (હિટ ઍન્ડ ટ્રાયલ) પદ્ધતિ સાથે સરખાવો.',
    help_4: 'સૂત્રોની આગળ તમારી પોતાની સંખ્યાઓ લખો (જેમ કે 2H2 + O2 -> 2H2O), ઍપ કહેશે કે તમારો જવાબ સાચો છે કે નહીં.',
    help_5: 'મહાવરામાં NCERT ધોરણ 10 ની 15 પ્રક્રિયાઓ છે. ખાનાં ભરો, ચકાસો દબાવો, અટકો તો સંકેત લો અને પ્રક્રિયાનો પ્રકાર જણાવો.',
    help_6: 'વર્ગખંડ પ્રવૃત્તિ: સ્માર્ટબોર્ડ પર ફુલ સ્ક્રીનમાં મહાવરાની એક પ્રક્રિયા બતાવો. ટીમો 2 મિનિટમાં કાગળ પર તેને સંતુલિત કરે, પછી એક ટીમ પોતાનાં પગલાં સમજાવે. ગૃહકાર્ય માટે વર્કશીટ પ્રિન્ટ કરો.'
  },
  pa: {
    app_title: 'ਰਸਾਇਣਕ ਸਮੀਕਰਨ ਸੰਤੁਲਨ',
    intro: 'ਕਿਸੇ ਵੀ ਰਸਾਇਣਕ ਸਮੀਕਰਨ ਨੂੰ ਕਦਮ-ਦਰ-ਕਦਮ ਸੰਤੁਲਿਤ ਕਰੋ, ਦੋਵਾਂ ਪਾਸਿਆਂ ਦੇ ਪਰਮਾਣੂ ਗਿਣੋ ਅਤੇ NCERT ਜਮਾਤ 10 ਦੀਆਂ 15 ਪ੍ਰਤੀਕਿਰਿਆਵਾਂ ਦਾ ਅਭਿਆਸ ਕਰੋ।',
    tab_balance: 'ਸੰਤੁਲਿਤ ਕਰੋ',
    tab_practice: 'ਅਭਿਆਸ: NCERT 10',
    eq_label: 'ਰਸਾਇਣਕ ਸਮੀਕਰਨ ਲਿਖੋ',
    eq_hint: 'ਦੋਵਾਂ ਪਾਸਿਆਂ ਵਿਚਕਾਰ → (ਜਾਂ -> ਜਾਂ =) ਅਤੇ ਪਦਾਰਥਾਂ ਵਿਚਕਾਰ + ਲਗਾਓ। ਬਰੈਕਟਾਂ, CuSO4·5H2O ਵਰਗੇ ਕ੍ਰਿਸਟਲੀ ਪਾਣੀ ਵਾਲੇ ਲੂਣ, (aq) ਵਰਗੀਆਂ ਅਵਸਥਾਵਾਂ ਅਤੇ Fe^3+ ਜਾਂ SO4^2- ਵਰਗੇ ਚਾਰਜ ਵੀ ਚੱਲਦੇ ਹਨ।',
    balance_btn: 'ਸੰਤੁਲਿਤ ਕਰੋ',
    keys_aria: 'ਚਿੰਨ੍ਹ ਪਾਓ',
    try_these: 'ਇਹ ਉਦਾਹਰਨਾਂ ਅਜ਼ਮਾਓ',
    result_title: 'ਸੰਤੁਲਿਤ ਸਮੀਕਰਨ',
    status_ok: 'ਸੰਤੁਲਿਤ ✓',
    status_many: 'ਇੱਕ ਤੋਂ ਵੱਧ ਉੱਤਰ',
    atoms_title: 'ਦੋਵਾਂ ਪਾਸਿਆਂ ਪਰਮਾਣੂਆਂ ਦੀ ਗਿਣਤੀ',
    col_element: 'ਤੱਤ',
    col_left: 'ਖੱਬਾ ਪਾਸਾ (ਪ੍ਰਤੀਕਾਰਕ)',
    col_right: 'ਸੱਜਾ ਪਾਸਾ (ਉਤਪਾਦ)',
    col_ok: 'ਬਰਾਬਰ?',
    charge: 'ਚਾਰਜ',
    law: 'ਪੁੰਜ ਦੀ ਸੰਭਾਲ ਦਾ ਨਿਯਮ: ਰਸਾਇਣਕ ਪ੍ਰਤੀਕਿਰਿਆ ਵਿੱਚ ਪਰਮਾਣੂ ਸਿਰਫ਼ ਨਵੇਂ ਢੰਗ ਨਾਲ ਜੁੜਦੇ ਹਨ। ਕੋਈ ਪਰਮਾਣੂ ਨਾ ਬਣਦਾ ਹੈ, ਨਾ ਨਸ਼ਟ ਹੁੰਦਾ ਹੈ, ਇਸ ਲਈ ਹਰ ਤੱਤ ਦੀ ਗਿਣਤੀ ਦੋਵੇਂ ਪਾਸੇ ਬਰਾਬਰ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।',
    steps_title: 'ਹੱਲ ਕਿਵੇਂ ਹੋਇਆ (ਬੀਜਗਣਿਤ ਵਿਧੀ)',
    s1_title: 'ਤੱਤਾਂ ਦੀ ਸੂਚੀ ਬਣਾਓ',
    s1_text: 'ਸਮੀਕਰਨ ਵਿੱਚ ਇਹ ਤੱਤ ਹਨ:',
    s2_title: 'ਹਰ ਫ਼ਾਰਮੂਲੇ ਅੱਗੇ ਇੱਕ ਅਣਜਾਣ ਸੰਖਿਆ ਰੱਖੋ',
    s2_text: 'ਹਰ ਅੱਖਰ ਇੱਕ ਗੁਣਾਂਕ ਹੈ, ਜੋ ਅਸੀਂ ਲੱਭਣਾ ਹੈ।',
    s3_title: 'ਹਰ ਤੱਤ ਲਈ ਇੱਕ ਸਮੀਕਰਨ ਲਿਖੋ',
    s3_text: 'ਖੱਬੇ ਪਾਸੇ ਕਿਸੇ ਤੱਤ ਦੇ ਪਰਮਾਣੂ = ਸੱਜੇ ਪਾਸੇ ਉਸੇ ਤੱਤ ਦੇ ਪਰਮਾਣੂ।',
    s3_charge: 'ਕੁੱਲ ਚਾਰਜ ਵੀ ਦੋਵੇਂ ਪਾਸੇ ਬਰਾਬਰ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
    s4_title: 'ਸਮੀਕਰਨਾਂ ਹੱਲ ਕਰੋ',
    s4_let: 'ਮੰਨ ਲਓ {eq} ({f} ਅੱਗੇ ਵਾਲੀ ਸੰਖਿਆ)। ਫਿਰ:',
    s4_together: 'ਬਾਕੀ ਸਮੀਕਰਨਾਂ ਨੂੰ ਇਕੱਠੇ ਹੱਲ ਕਰਨ ਨਾਲ:',
    s4_mult: 'ਸਭ ਤੋਂ ਛੋਟੀਆਂ ਪੂਰਨ ਸੰਖਿਆਵਾਂ ਲਈ ਹਰ ਸੰਖਿਆ ਨੂੰ {m} ਨਾਲ ਗੁਣਾ ਕਰੋ:',
    s4_whole: 'ਇਹ ਪਹਿਲਾਂ ਹੀ ਸਭ ਤੋਂ ਛੋਟੀਆਂ ਪੂਰਨ ਸੰਖਿਆਵਾਂ ਹਨ:',
    s5_title: 'ਜਾਂਚ ਕਰੋ',
    s5_text: 'ਇਨ੍ਹਾਂ ਸੰਖਿਆਵਾਂ ਨਾਲ ਹਰ ਪਰਮਾਣੂ ਦੁਬਾਰਾ ਗਿਣੋ (ਸਾਰਣੀ ਵੇਖੋ)। ਦੋਵੇਂ ਪਾਸੇ ਬਰਾਬਰ ਹਨ, ਇਸ ਲਈ ਸਮੀਕਰਨ ਸੰਤੁਲਿਤ ਹੈ।',
    many_text: 'ਇਹ ਸਮੀਕਰਨ ਇੱਕ ਤੋਂ ਵੱਧ ਤਰੀਕਿਆਂ ਨਾਲ ਸੰਤੁਲਿਤ ਹੋ ਸਕਦੀ ਹੈ, ਕਿਉਂਕਿ ਇਸ ਵਿੱਚ ਦੋ ਜਾਂ ਵੱਧ ਵੱਖਰੀਆਂ ਪ੍ਰਤੀਕਿਰਿਆਵਾਂ ਮਿਲੀਆਂ ਹਨ। ਇੱਕ ਸੰਭਵ ਉੱਤਰ ਦਿਖਾਇਆ ਗਿਆ ਹੈ। ਫ਼ਾਰਮੂਲੇ ਆਪਣੇ ਅਧਿਆਪਕ ਤੋਂ ਜਾਂਚ ਕਰਵਾਓ।',
    many_none: 'ਇਹ ਸਮੀਕਰਨ ਕਈ ਤਰੀਕਿਆਂ ਨਾਲ ਸੰਤੁਲਿਤ ਹੋ ਸਕਦੀ ਹੈ, ਇਸ ਲਈ ਕੋਈ ਇੱਕ ਉੱਤਰ ਨਹੀਂ ਹੈ। ਫ਼ਾਰਮੂਲੇ ਜਾਂਚੋ।',
    err_empty: 'ਪਹਿਲਾਂ ਕੋਈ ਸਮੀਕਰਨ ਲਿਖੋ, ਜਿਵੇਂ: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'ਪ੍ਰਤੀਕਾਰਕਾਂ ਅਤੇ ਉਤਪਾਦਾਂ ਵਿਚਕਾਰ ਠੀਕ ਇੱਕ ਤੀਰ (→, -> ਜਾਂ =) ਲਗਾਓ।',
    err_side_empty: 'ਤੀਰ ਦਾ ਇੱਕ ਪਾਸਾ ਖਾਲੀ ਹੈ। ਦੋਵੇਂ ਪਾਸੇ ਪਦਾਰਥ ਲਿਖੋ।',
    err_plus: '+ ਚਿੰਨ੍ਹ ਦੇ ਕੋਲ ਕੁਝ ਛੁੱਟ ਗਿਆ ਹੈ।',
    err_bad_char: 'ਫ਼ਾਰਮੂਲੇ ਵਿੱਚ "{c}" ਚਿੰਨ੍ਹ ਨਹੀਂ ਵਰਤਿਆ ਜਾ ਸਕਦਾ। ਤੱਤਾਂ ਦੇ ਸੰਕੇਤ, ਅੰਕ ਅਤੇ ਬਰੈਕਟਾਂ ਵਰਤੋ।',
    err_element: '"{e}" ਕਿਸੇ ਤੱਤ ਦਾ ਸੰਕੇਤ ਨਹੀਂ ਹੈ। ਵੱਡੇ ਅਤੇ ਛੋਟੇ ਅੱਖਰ ਜਾਂਚੋ: Co ਕੋਬਾਲਟ ਹੈ, ਪਰ CO ਕਾਰਬਨ ਮੋਨੋਆਕਸਾਈਡ ਹੈ।',
    err_lower: 'ਤੱਤਾਂ ਦੇ ਸੰਕੇਤ ਵੱਡੇ ਅੱਖਰ ਨਾਲ ਸ਼ੁਰੂ ਹੁੰਦੇ ਹਨ (H, Fe, Cl)। "{f}" ਜਾਂਚੋ।',
    err_bracket: '"{f}" ਵਿੱਚ ਬਰੈਕਟਾਂ ਮੇਲ ਨਹੀਂ ਖਾਂਦੀਆਂ।',
    err_formula: 'ਫ਼ਾਰਮੂਲਾ "{f}" ਪੜ੍ਹਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ।',
    err_coef: 'ਫ਼ਾਰਮੂਲੇ ਅੱਗੇ ਵਾਲੀ ਸੰਖਿਆ 1 ਜਾਂ ਉਸ ਤੋਂ ਵੱਡੀ ਪੂਰਨ ਸੰਖਿਆ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।',
    err_too_many: 'ਬਹੁਤ ਜ਼ਿਆਦਾ ਪਦਾਰਥ ਹਨ। ਵੱਧ ਤੋਂ ਵੱਧ {n} ਲਿਖੋ।',
    err_only_side: '{e} ਤੀਰ ਦੇ ਸਿਰਫ਼ ਇੱਕ ਪਾਸੇ ਹੈ, ਇਸ ਲਈ ਇਹ ਕਦੇ ਸੰਤੁਲਿਤ ਨਹੀਂ ਹੋ ਸਕਦੀ। ਫ਼ਾਰਮੂਲੇ ਜਾਂਚੋ।',
    err_impossible: 'ਇਹ ਸਮੀਕਰਨ ਸੰਤੁਲਿਤ ਨਹੀਂ ਹੋ ਸਕਦੀ। ਕੋਈ ਫ਼ਾਰਮੂਲਾ ਗਲਤ ਹੋ ਸਕਦਾ ਹੈ, ਜਾਂ ਕੋਈ ਪ੍ਰਤੀਕਾਰਕ ਜਾਂ ਉਤਪਾਦ ਛੁੱਟ ਗਿਆ ਹੈ।',
    err_charge: 'ਚਾਰਜ ਬਰਾਬਰ ਨਹੀਂ ਹੋ ਸਕਦੇ। ਚਾਰਜ ਜਾਂਚੋ, ਜਾਂ ਅੱਧੀ ਪ੍ਰਤੀਕਿਰਿਆ ਲਈ ਇਲੈਕਟ੍ਰਾਨ (e-) ਜੋੜੋ।',
    err_zero: 'ਸੰਤੁਲਨ ਸੰਭਵ ਨਹੀਂ: {f} ਨੂੰ ਸੰਖਿਆ 0 ਮਿਲੇਗੀ, ਭਾਵ ਇਹ ਪ੍ਰਤੀਕਿਰਿਆ ਵਿੱਚ ਹਿੱਸਾ ਨਹੀਂ ਲੈਂਦਾ। ਇਸ ਨੂੰ ਹਟਾਓ ਜਾਂ ਫ਼ਾਰਮੂਲੇ ਜਾਂਚੋ।',
    err_side: 'ਧਨਾਤਮਕ ਸੰਖਿਆਵਾਂ ਨਾਲ ਸੰਤੁਲਨ ਸੰਭਵ ਨਹੀਂ: {f} ਨੂੰ ਤੀਰ ਦੇ ਦੂਜੇ ਪਾਸੇ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
    yours_label: 'ਤੁਸੀਂ ਲਿਖਿਆ:',
    yours_ok: 'ਤੁਹਾਡੀਆਂ ਸੰਖਿਆਵਾਂ ਸਹੀ ਹਨ। ਸਮੀਕਰਨ ਸੰਤੁਲਿਤ ਹੈ।',
    yours_multiple: 'ਤੁਹਾਡੀਆਂ ਸੰਖਿਆਵਾਂ ਨਾਲ ਸਮੀਕਰਨ ਸੰਤੁਲਿਤ ਹੈ, ਪਰ ਇਹ ਸਭ ਤੋਂ ਛੋਟੀਆਂ ਨਹੀਂ ਹਨ। ਸਾਰੀਆਂ ਨੂੰ {k} ਨਾਲ ਭਾਗ ਕਰੋ।',
    yours_bad: 'ਤੁਹਾਡੀਆਂ ਸੰਖਿਆਵਾਂ ਨਾਲ ਸਮੀਕਰਨ ਅਜੇ ਸੰਤੁਲਿਤ ਨਹੀਂ ਹੈ। ਬਰਾਬਰ ਨਹੀਂ: {list}। ਸਹੀ ਉੱਤਰ ਉੱਪਰ ਦਿਖਾਇਆ ਗਿਆ ਹੈ।',
    pr_pick: 'ਪ੍ਰਤੀਕਿਰਿਆ ਚੁਣੋ',
    pr_num: 'ਪ੍ਰਤੀਕਿਰਿਆ {n} / {total}',
    pr_solved: 'ਹੱਲ ਕੀਤੀਆਂ: {total} ਵਿੱਚੋਂ {n}',
    pr_enter: 'ਖਾਨਿਆਂ ਵਿੱਚ ਸਭ ਤੋਂ ਛੋਟੀਆਂ ਪੂਰਨ ਸੰਖਿਆਵਾਂ ਲਿਖੋ। ਖਾਲੀ ਖਾਨੇ ਦਾ ਮਤਲਬ 1 ਹੈ।',
    pr_done: 'ਹੱਲ ਹੋ ਗਿਆ',
    pr_shown: 'ਉੱਤਰ ਵੇਖਿਆ',
    coef_aria: '{f} ਅੱਗੇ ਵਾਲੀ ਸੰਖਿਆ',
    check: 'ਜਾਂਚੋ',
    hint: 'ਇਸ਼ਾਰਾ',
    show_answer: 'ਉੱਤਰ ਵਿਖਾਓ',
    fb_ok: 'ਸਹੀ! ਸਮੀਕਰਨ ਸਭ ਤੋਂ ਛੋਟੀਆਂ ਪੂਰਨ ਸੰਖਿਆਵਾਂ ਨਾਲ ਸੰਤੁਲਿਤ ਹੈ।',
    fb_ok_seen: 'ਸਹੀ! ਪਰ ਤੁਸੀਂ ਇਸਦਾ ਉੱਤਰ ਵੇਖ ਲਿਆ ਸੀ, ਇਸ ਲਈ ਇਸਨੂੰ ਹੱਲ ਕੀਤਾ ਨਹੀਂ ਗਿਣਿਆ ਗਿਆ।',
    fb_multiple: 'ਸੰਤੁਲਿਤ ਤਾਂ ਹੈ, ਪਰ ਇਹ ਸਭ ਤੋਂ ਛੋਟੀਆਂ ਸੰਖਿਆਵਾਂ ਨਹੀਂ ਹਨ। ਸਾਰੀਆਂ ਨੂੰ {k} ਨਾਲ ਭਾਗ ਕਰੋ।',
    fb_bad: 'ਅਜੇ ਸੰਤੁਲਿਤ ਨਹੀਂ। ਇਹ ਵੇਖੋ: {list}।',
    fb_invalid: 'ਖਾਨਿਆਂ ਵਿੱਚ 1 ਤੋਂ 99 ਤੱਕ ਦੀਆਂ ਪੂਰਨ ਸੰਖਿਆਵਾਂ ਹੀ ਲਿਖੋ।',
    fb_shown: 'ਇਹ ਰਿਹਾ ਉੱਤਰ। ਸਾਰਣੀ ਵਿੱਚ ਹਰ ਪਰਮਾਣੂ ਜਾਂਚੋ, ਫਿਰ ਅਗਲੀ ਪ੍ਰਤੀਕਿਰਿਆ ਕਰੋ।',
    hint_atoms: '{e} ਗਿਣੋ: ਖੱਬੇ ਪਾਸੇ {l} ਅਤੇ ਸੱਜੇ ਪਾਸੇ {r}। {list} ਅੱਗੇ ਵਾਲੀ ਸੰਖਿਆ ਬਦਲੋ।',
    hint_reveal: '{f} ਅੱਗੇ ਵਾਲੀ ਸੰਖਿਆ {n} ਹੈ।',
    hint_done: 'ਸਾਰੀਆਂ ਸੰਖਿਆਵਾਂ ਸਹੀ ਹਨ। ਜਾਂਚੋ ਦਬਾਓ।',
    type_q: 'ਇਹ ਕਿਸ ਕਿਸਮ ਦੀ ਪ੍ਰਤੀਕਿਰਿਆ ਹੈ?',
    type_ok: 'ਸਹੀ!',
    type_bad: 'ਠੀਕ ਨਹੀਂ। ਹੇਠਾਂ ਉੱਤਰ ਵੇਖੋ।',
    type_label: 'ਕਿਸਮ',
    also: 'ਨਾਲ ਹੀ',
    t_combination: 'ਸੰਯੋਜਨ',
    t_decomposition: 'ਵਿਘਟਨ',
    t_displacement: 'ਵਿਸਥਾਪਨ',
    t_double: 'ਦੋਹਰਾ ਵਿਸਥਾਪਨ',
    t_combustion: 'ਜਲਣ',
    t_redox: 'ਰੈਡੌਕਸ',
    x_combination: 'ਸੰਯੋਜਨ: ਦੋ ਜਾਂ ਵੱਧ ਪਦਾਰਥ ਮਿਲ ਕੇ ਇੱਕ ਨਵਾਂ ਪਦਾਰਥ ਬਣਾਉਂਦੇ ਹਨ (A + B → AB)।',
    x_decomposition: 'ਵਿਘਟਨ: ਇੱਕ ਪਦਾਰਥ ਗਰਮੀ, ਰੋਸ਼ਨੀ ਜਾਂ ਬਿਜਲੀ ਨਾਲ ਟੁੱਟ ਕੇ ਸਰਲ ਪਦਾਰਥ ਬਣਾਉਂਦਾ ਹੈ (AB → A + B)।',
    x_displacement: 'ਵਿਸਥਾਪਨ: ਵੱਧ ਕਿਰਿਆਸ਼ੀਲ ਤੱਤ ਘੱਟ ਕਿਰਿਆਸ਼ੀਲ ਤੱਤ ਨੂੰ ਉਸ ਦੇ ਯੌਗਿਕ ਵਿੱਚੋਂ ਹਟਾ ਦਿੰਦਾ ਹੈ (A + BC → AC + B)।',
    x_double: 'ਦੋਹਰਾ ਵਿਸਥਾਪਨ: ਦੋ ਯੌਗਿਕ ਆਪਣੇ ਆਇਨਾਂ ਦੀ ਅਦਲਾ-ਬਦਲੀ ਕਰਦੇ ਹਨ, ਅਤੇ ਅਕਸਰ ਤਲਛਟ ਬਣਦੀ ਹੈ (AB + CD → AD + CB)।',
    x_combustion: 'ਜਲਣ: ਪਦਾਰਥ ਆਕਸੀਜਨ ਵਿੱਚ ਸੜ ਕੇ ਗਰਮੀ ਅਤੇ ਰੋਸ਼ਨੀ ਦਿੰਦਾ ਹੈ। ਮੀਥੇਨ ਅਤੇ LPG ਵਰਗੇ ਬਾਲਣ ਕਾਰਬਨ ਡਾਈਆਕਸਾਈਡ ਅਤੇ ਪਾਣੀ ਦਿੰਦੇ ਹਨ।',
    x_redox: 'ਰੈਡੌਕਸ: ਇੱਕ ਪਦਾਰਥ ਦਾ ਆਕਸੀਕਰਨ ਹੁੰਦਾ ਹੈ (ਆਕਸੀਜਨ ਜੁੜਦੀ ਹੈ ਜਾਂ ਹਾਈਡ੍ਰੋਜਨ ਹਟਦੀ ਹੈ) ਅਤੇ ਦੂਜੇ ਦਾ ਲਘੂਕਰਨ ਹੁੰਦਾ ਹੈ (ਆਕਸੀਜਨ ਹਟਦੀ ਹੈ ਜਾਂ ਹਾਈਡ੍ਰੋਜਨ ਜੁੜਦੀ ਹੈ)।',
    cond_heat: 'ਗਰਮੀ',
    cond_sun: 'ਧੁੱਪ',
    cond_elec: 'ਬਿਜਲੀ',
    states_note: '(s) ਠੋਸ · (l) ਤਰਲ · (g) ਗੈਸ · (aq) ਪਾਣੀ ਵਿੱਚ ਘੁਲਿਆ',
    print_ws: 'ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ',
    ws_title: 'ਇਨ੍ਹਾਂ ਰਸਾਇਣਕ ਸਮੀਕਰਨਾਂ ਨੂੰ ਸੰਤੁਲਿਤ ਕਰੋ',
    ws_name: 'ਨਾਮ',
    ws_class: 'ਜਮਾਤ',
    ws_date: 'ਤਾਰੀਖ਼',
    ws_instr: 'ਹਰ ਖਾਲੀ ਥਾਂ ਵਿੱਚ ਸਭ ਤੋਂ ਛੋਟੀ ਪੂਰਨ ਸੰਖਿਆ ਲਿਖੋ, ਫਿਰ ਪ੍ਰਤੀਕਿਰਿਆ ਦੀ ਕਿਸਮ ਲਿਖੋ।',
    ws_key: 'ਉੱਤਰ ਕੁੰਜੀ',
    reset_progress: 'ਪ੍ਰਗਤੀ ਰੀਸੈੱਟ ਕਰੋ',
    help_title: 'ਕਿਵੇਂ ਵਰਤੀਏ / ਜਮਾਤ ਲਈ ਸੁਝਾਅ',
    help_1: 'ਸਹੀ ਵੱਡੇ-ਛੋਟੇ ਅੱਖਰਾਂ ਨਾਲ ਸਮੀਕਰਨ ਲਿਖੋ (Co ਕੋਬਾਲਟ ਹੈ, CO ਕਾਰਬਨ ਮੋਨੋਆਕਸਾਈਡ) ਅਤੇ ਸੰਤੁਲਿਤ ਕਰੋ ਦਬਾਓ। ਤੀਰ ਲਈ →, -> ਜਾਂ = ਲਿਖ ਸਕਦੇ ਹੋ।',
    help_2: 'ਬਰੈਕਟਾਂ ( ) ਅਤੇ [ ], ਕ੍ਰਿਸਟਲੀ ਪਾਣੀ ਵਾਲੇ ਲੂਣ (CuSO4·5H2O ਜਾਂ CuSO4.5H2O), ਅਵਸਥਾਵਾਂ (s), (l), (g), (aq) ਅਤੇ ਆਇਨ (Fe^3+, SO4^2-, e-) ਵੀ ਸਮਝੇ ਜਾਂਦੇ ਹਨ।',
    help_3: '"ਹੱਲ ਕਿਵੇਂ ਹੋਇਆ" ਪੜ੍ਹੋ: ਐਪ ਹਰ ਤੱਤ ਲਈ ਇੱਕ ਸਮੀਕਰਨ ਲਿਖ ਕੇ ਉਨ੍ਹਾਂ ਨੂੰ ਹੱਲ ਕਰਦੀ ਹੈ। ਇਸ ਦੀ ਤੁਲਨਾ NCERT ਕਿਤਾਬ ਦੀ ਹਿੱਟ ਐਂਡ ਟ੍ਰਾਇਲ (ਕੋਸ਼ਿਸ਼ ਅਤੇ ਗਲਤੀ) ਵਿਧੀ ਨਾਲ ਕਰੋ।',
    help_4: 'ਫ਼ਾਰਮੂਲਿਆਂ ਅੱਗੇ ਆਪਣੀਆਂ ਸੰਖਿਆਵਾਂ ਲਿਖੋ (ਜਿਵੇਂ 2H2 + O2 -> 2H2O), ਐਪ ਦੱਸੇਗੀ ਕਿ ਤੁਹਾਡਾ ਉੱਤਰ ਸਹੀ ਹੈ ਜਾਂ ਨਹੀਂ।',
    help_5: 'ਅਭਿਆਸ ਵਿੱਚ NCERT ਜਮਾਤ 10 ਦੀਆਂ 15 ਪ੍ਰਤੀਕਿਰਿਆਵਾਂ ਹਨ। ਖਾਨੇ ਭਰੋ, ਜਾਂਚੋ ਦਬਾਓ, ਅਟਕਣ ਉੱਤੇ ਇਸ਼ਾਰਾ ਲਓ ਅਤੇ ਪ੍ਰਤੀਕਿਰਿਆ ਦੀ ਕਿਸਮ ਦੱਸੋ।',
    help_6: 'ਜਮਾਤ ਗਤੀਵਿਧੀ: ਸਮਾਰਟਬੋਰਡ ਉੱਤੇ ਫੁੱਲ ਸਕ੍ਰੀਨ ਵਿੱਚ ਅਭਿਆਸ ਦੀ ਇੱਕ ਪ੍ਰਤੀਕਿਰਿਆ ਵਿਖਾਓ। ਟੀਮਾਂ 2 ਮਿੰਟ ਵਿੱਚ ਕਾਗਜ਼ ਉੱਤੇ ਇਸ ਨੂੰ ਸੰਤੁਲਿਤ ਕਰਨ, ਫਿਰ ਇੱਕ ਟੀਮ ਆਪਣੇ ਕਦਮ ਸਮਝਾਏ। ਘਰ ਦੇ ਕੰਮ ਲਈ ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ।'
  },
  or: {
    app_title: 'ରାସାୟନିକ ସମୀକରଣ ସନ୍ତୁଳନ',
    intro: 'ଯେକୌଣସି ରାସାୟନିକ ସମୀକରଣକୁ ପାହାଚ ପରେ ପାହାଚ ସନ୍ତୁଳିତ କରନ୍ତୁ, ଦୁଇ ପାର୍ଶ୍ୱର ପରମାଣୁ ଗଣନ୍ତୁ ଏବଂ NCERT ଦଶମ ଶ୍ରେଣୀର 15ଟି ପ୍ରତିକ୍ରିୟା ଅଭ୍ୟାସ କରନ୍ତୁ।',
    tab_balance: 'ସନ୍ତୁଳିତ କରନ୍ତୁ',
    tab_practice: 'ଅଭ୍ୟାସ: NCERT 10',
    eq_label: 'ଏକ ରାସାୟନିକ ସମୀକରଣ ଲେଖନ୍ତୁ',
    eq_hint: 'ଦୁଇ ପାର୍ଶ୍ୱ ମଧ୍ୟରେ → (କିମ୍ବା -> କିମ୍ବା =) ଏବଂ ପଦାର୍ଥଗୁଡ଼ିକ ମଧ୍ୟରେ + ଦିଅନ୍ତୁ। ବନ୍ଧନୀ, CuSO4·5H2O ପରି ସ୍ଫଟିକ ଜଳଯୁକ୍ତ ଲବଣ, (aq) ପରି ଅବସ୍ଥା ଏବଂ Fe^3+ କିମ୍ବା SO4^2- ପରି ଚାର୍ଜ ମଧ୍ୟ ଚାଲେ।',
    balance_btn: 'ସନ୍ତୁଳିତ କରନ୍ତୁ',
    keys_aria: 'ଚିହ୍ନ ଯୋଡ଼ନ୍ତୁ',
    try_these: 'ଏହି ଉଦାହରଣଗୁଡ଼ିକ ଚେଷ୍ଟା କରନ୍ତୁ',
    result_title: 'ସନ୍ତୁଳିତ ସମୀକରଣ',
    status_ok: 'ସନ୍ତୁଳିତ ✓',
    status_many: 'ଏକାଧିକ ଉତ୍ତର',
    atoms_title: 'ଦୁଇ ପାର୍ଶ୍ୱରେ ପରମାଣୁ ସଂଖ୍ୟା',
    col_element: 'ମୌଳିକ',
    col_left: 'ବାମ ପାର୍ଶ୍ୱ (ପ୍ରତିକାରକ)',
    col_right: 'ଡାହାଣ ପାର୍ଶ୍ୱ (ଉତ୍ପାଦ)',
    col_ok: 'ସମାନ?',
    charge: 'ଚାର୍ଜ',
    law: 'ବସ୍ତୁତ୍ୱ ସଂରକ୍ଷଣ ନିୟମ: ରାସାୟନିକ ପ୍ରତିକ୍ରିୟାରେ ପରମାଣୁଗୁଡ଼ିକ କେବଳ ନୂଆ ଭାବେ ସଜେଇ ହୁଅନ୍ତି। କୌଣସି ପରମାଣୁ ସୃଷ୍ଟି କିମ୍ବା ନଷ୍ଟ ହୁଏ ନାହିଁ, ତେଣୁ ପ୍ରତ୍ୟେକ ମୌଳିକର ସଂଖ୍ୟା ଦୁଇ ପାର୍ଶ୍ୱରେ ସମାନ ହେବା ଦରକାର।',
    steps_title: 'କିପରି ସମାଧାନ ହେଲା (ବୀଜଗଣିତ ପଦ୍ଧତି)',
    s1_title: 'ମୌଳିକଗୁଡ଼ିକର ତାଲିକା କରନ୍ତୁ',
    s1_text: 'ସମୀକରଣରେ ଏହି ମୌଳିକଗୁଡ଼ିକ ଅଛନ୍ତି:',
    s2_title: 'ପ୍ରତ୍ୟେକ ସଙ୍କେତ ଆଗରେ ଏକ ଅଜଣା ସଂଖ୍ୟା ରଖନ୍ତୁ',
    s2_text: 'ପ୍ରତ୍ୟେକ ଅକ୍ଷର ଗୋଟିଏ ଗୁଣାଙ୍କ, ଯାହାକୁ ଆମକୁ ଖୋଜିବାକୁ ହେବ।',
    s3_title: 'ପ୍ରତ୍ୟେକ ମୌଳିକ ପାଇଁ ଗୋଟିଏ ସମୀକରଣ ଲେଖନ୍ତୁ',
    s3_text: 'ବାମ ପାର୍ଶ୍ୱରେ କୌଣସି ମୌଳିକର ପରମାଣୁ = ଡାହାଣ ପାର୍ଶ୍ୱରେ ସେହି ମୌଳିକର ପରମାଣୁ।',
    s3_charge: 'ମୋଟ ଚାର୍ଜ ମଧ୍ୟ ଦୁଇ ପାର୍ଶ୍ୱରେ ସମାନ ହେବା ଦରକାର।',
    s4_title: 'ସମୀକରଣଗୁଡ଼ିକ ସମାଧାନ କରନ୍ତୁ',
    s4_let: 'ଧରନ୍ତୁ {eq} ({f} ଆଗର ସଂଖ୍ୟା)। ତାପରେ:',
    s4_together: 'ବାକି ସମୀକରଣଗୁଡ଼ିକୁ ଏକାଠି ସମାଧାନ କଲେ:',
    s4_mult: 'ସବୁଠାରୁ ଛୋଟ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା ପାଇବା ପାଇଁ ପ୍ରତ୍ୟେକ ସଂଖ୍ୟାକୁ {m} ରେ ଗୁଣନ୍ତୁ:',
    s4_whole: 'ଏଗୁଡ଼ିକ ପୂର୍ବରୁ ସବୁଠାରୁ ଛୋଟ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା:',
    s5_title: 'ଯାଞ୍ଚ କରନ୍ତୁ',
    s5_text: 'ଏହି ସଂଖ୍ୟାଗୁଡ଼ିକ ସହ ପ୍ରତ୍ୟେକ ପରମାଣୁ ପୁଣି ଗଣନ୍ତୁ (ସାରଣୀ ଦେଖନ୍ତୁ)। ଦୁଇ ପାର୍ଶ୍ୱ ମେଳ ଖାଉଛି, ତେଣୁ ସମୀକରଣଟି ସନ୍ତୁଳିତ।',
    many_text: 'ଏହି ସମୀକରଣକୁ ଏକାଧିକ ଉପାୟରେ ସନ୍ତୁଳିତ କରାଯାଇପାରେ, କାରଣ ଏଥିରେ ଦୁଇ ବା ଅଧିକ ଅଲଗା ପ୍ରତିକ୍ରିୟା ମିଶିଛି। ଗୋଟିଏ ସମ୍ଭାବ୍ୟ ଉତ୍ତର ଦେଖାଯାଇଛି। ସଙ୍କେତଗୁଡ଼ିକୁ ଶିକ୍ଷକଙ୍କ ସହ ଯାଞ୍ଚ କରନ୍ତୁ।',
    many_none: 'ଏହି ସମୀକରଣକୁ ଅନେକ ଉପାୟରେ ସନ୍ତୁଳିତ କରାଯାଇପାରେ, ତେଣୁ କୌଣସି ଗୋଟିଏ ଉତ୍ତର ନାହିଁ। ସଙ୍କେତଗୁଡ଼ିକ ଯାଞ୍ଚ କରନ୍ତୁ।',
    err_empty: 'ପ୍ରଥମେ ଏକ ସମୀକରଣ ଲେଖନ୍ତୁ, ଯେପରି: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'ପ୍ରତିକାରକ ଓ ଉତ୍ପାଦ ମଧ୍ୟରେ ଠିକ୍ ଗୋଟିଏ ତୀର (→, -> କିମ୍ବା =) ଦିଅନ୍ତୁ।',
    err_side_empty: 'ତୀରର ଗୋଟିଏ ପାର୍ଶ୍ୱ ଖାଲି ଅଛି। ଦୁଇ ପାର୍ଶ୍ୱରେ ପଦାର୍ଥ ଲେଖନ୍ତୁ।',
    err_plus: '+ ଚିହ୍ନ ପାଖରେ କିଛି ଛାଡ଼ି ଯାଇଛି।',
    err_bad_char: 'ସଙ୍କେତରେ "{c}" ଚିହ୍ନ ବ୍ୟବହାର କରାଯାଇପାରିବ ନାହିଁ। ମୌଳିକର ପ୍ରତୀକ, ଅଙ୍କ ଓ ବନ୍ଧନୀ ବ୍ୟବହାର କରନ୍ତୁ।',
    err_element: '"{e}" କୌଣସି ମୌଳିକର ପ୍ରତୀକ ନୁହେଁ। ବଡ଼ ଓ ଛୋଟ ଅକ୍ଷର ଯାଞ୍ଚ କରନ୍ତୁ: Co ହେଉଛି କୋବାଲ୍ଟ, କିନ୍ତୁ CO ହେଉଛି କାର୍ବନ ମନୋକ୍ସାଇଡ୍।',
    err_lower: 'ମୌଳିକର ପ୍ରତୀକ ବଡ଼ ଅକ୍ଷରରେ ଆରମ୍ଭ ହୁଏ (H, Fe, Cl)। "{f}" ଯାଞ୍ଚ କରନ୍ତୁ।',
    err_bracket: '"{f}" ରେ ବନ୍ଧନୀଗୁଡ଼ିକ ମେଳ ଖାଉନାହିଁ।',
    err_formula: '"{f}" ସଙ୍କେତଟି ପଢ଼ି ହେଲା ନାହିଁ।',
    err_coef: 'ସଙ୍କେତ ଆଗର ସଂଖ୍ୟା 1 କିମ୍ବା ତାଠାରୁ ବଡ଼ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା ହେବା ଦରକାର।',
    err_too_many: 'ବହୁତ ଅଧିକ ପଦାର୍ଥ। ସର୍ବାଧିକ {n}ଟି ଲେଖନ୍ତୁ।',
    err_only_side: '{e} ତୀରର କେବଳ ଗୋଟିଏ ପାର୍ଶ୍ୱରେ ଅଛି, ତେଣୁ ଏହା କେବେ ସନ୍ତୁଳିତ ହେବ ନାହିଁ। ସଙ୍କେତଗୁଡ଼ିକ ଯାଞ୍ଚ କରନ୍ତୁ।',
    err_impossible: 'ଏହି ସମୀକରଣକୁ ସନ୍ତୁଳିତ କରାଯାଇପାରିବ ନାହିଁ। କୌଣସି ସଙ୍କେତ ଭୁଲ ଥାଇପାରେ, କିମ୍ବା କୌଣସି ପ୍ରତିକାରକ ବା ଉତ୍ପାଦ ଛାଡ଼ି ଯାଇଥାଇପାରେ।',
    err_charge: 'ଚାର୍ଜ ସମାନ କରାଯାଇପାରୁନାହିଁ। ଚାର୍ଜ ଯାଞ୍ଚ କରନ୍ତୁ, କିମ୍ବା ଅର୍ଦ୍ଧ-ପ୍ରତିକ୍ରିୟା ପାଇଁ ଇଲେକ୍ଟ୍ରନ (e-) ଯୋଡ଼ନ୍ତୁ।',
    err_zero: 'ସନ୍ତୁଳନ ସମ୍ଭବ ନୁହେଁ: {f} ସଂଖ୍ୟା 0 ପାଇବ, ଅର୍ଥାତ୍ ଏହା ପ୍ରତିକ୍ରିୟାରେ ଭାଗ ନିଏ ନାହିଁ। ଏହାକୁ ହଟାନ୍ତୁ କିମ୍ବା ସଙ୍କେତ ଯାଞ୍ଚ କରନ୍ତୁ।',
    err_side: 'ଧନାତ୍ମକ ସଂଖ୍ୟାରେ ସନ୍ତୁଳନ ସମ୍ଭବ ନୁହେଁ: {f} ତୀରର ଅନ୍ୟ ପାର୍ଶ୍ୱରେ ରହିବା ଦରକାର।',
    yours_label: 'ଆପଣ ଲେଖିଲେ:',
    yours_ok: 'ଆପଣଙ୍କ ସଂଖ୍ୟା ଠିକ୍। ସମୀକରଣଟି ସନ୍ତୁଳିତ।',
    yours_multiple: 'ଆପଣଙ୍କ ସଂଖ୍ୟାରେ ସମୀକରଣ ସନ୍ତୁଳିତ, କିନ୍ତୁ ଏଗୁଡ଼ିକ ସବୁଠାରୁ ଛୋଟ ନୁହେଁ। ସବୁକୁ {k} ରେ ଭାଗ କରନ୍ତୁ।',
    yours_bad: 'ଆପଣଙ୍କ ସଂଖ୍ୟାରେ ସମୀକରଣ ଏପର୍ଯ୍ୟନ୍ତ ସନ୍ତୁଳିତ ନୁହେଁ। ସମାନ ନୁହେଁ: {list}। ଠିକ୍ ଉତ୍ତର ଉପରେ ଦେଖାଯାଇଛି।',
    pr_pick: 'ଏକ ପ୍ରତିକ୍ରିୟା ବାଛନ୍ତୁ',
    pr_num: 'ପ୍ରତିକ୍ରିୟା {n} / {total}',
    pr_solved: 'ସମାଧାନ: {total}ରୁ {n}',
    pr_enter: 'ଘରଗୁଡ଼ିକରେ ସବୁଠାରୁ ଛୋଟ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା ଲେଖନ୍ତୁ। ଖାଲି ଘର ଅର୍ଥ 1।',
    pr_done: 'ସମାଧାନ ହେଲା',
    pr_shown: 'ଉତ୍ତର ଦେଖାଗଲା',
    coef_aria: '{f} ଆଗର ସଂଖ୍ୟା',
    check: 'ଯାଞ୍ଚ କରନ୍ତୁ',
    hint: 'ସୂଚନା',
    show_answer: 'ଉତ୍ତର ଦେଖାନ୍ତୁ',
    fb_ok: 'ଠିକ୍! ସମୀକରଣଟି ସବୁଠାରୁ ଛୋଟ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟାରେ ସନ୍ତୁଳିତ।',
    fb_ok_seen: 'ଠିକ୍! କିନ୍ତୁ ଆପଣ ଏହାର ଉତ୍ତର ଦେଖିସାରିଥିଲେ, ତେଣୁ ଏହାକୁ ସମାଧାନ ହୋଇଥିବା ବୋଲି ଗଣାଯାଇନାହିଁ।',
    fb_multiple: 'ସନ୍ତୁଳିତ ତ ହେଲା, କିନ୍ତୁ ଏଗୁଡ଼ିକ ସବୁଠାରୁ ଛୋଟ ସଂଖ୍ୟା ନୁହେଁ। ସବୁକୁ {k} ରେ ଭାଗ କରନ୍ତୁ।',
    fb_bad: 'ଏପର୍ଯ୍ୟନ୍ତ ସନ୍ତୁଳିତ ନୁହେଁ। ଏଗୁଡ଼ିକ ଦେଖନ୍ତୁ: {list}।',
    fb_invalid: 'ଘରଗୁଡ଼ିକରେ 1 ରୁ 99 ପର୍ଯ୍ୟନ୍ତ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା ହିଁ ଲେଖନ୍ତୁ।',
    fb_shown: 'ଏହା ହେଉଛି ଉତ୍ତର। ସାରଣୀରେ ପ୍ରତ୍ୟେକ ପରମାଣୁ ଯାଞ୍ଚ କରନ୍ତୁ, ତାପରେ ପରବର୍ତ୍ତୀ ପ୍ରତିକ୍ରିୟା କରନ୍ତୁ।',
    hint_atoms: '{e} ଗଣନ୍ତୁ: ବାମ ପାର୍ଶ୍ୱରେ {l} ଏବଂ ଡାହାଣ ପାର୍ଶ୍ୱରେ {r}। {list} ଆଗର ସଂଖ୍ୟା ବଦଳାନ୍ତୁ।',
    hint_reveal: '{f} ଆଗର ସଂଖ୍ୟା ହେଉଛି {n}।',
    hint_done: 'ସବୁ ସଂଖ୍ୟା ଠିକ୍ ଅଛି। ଯାଞ୍ଚ କରନ୍ତୁ ଦବାନ୍ତୁ।',
    type_q: 'ଏହା କେଉଁ ପ୍ରକାରର ପ୍ରତିକ୍ରିୟା?',
    type_ok: 'ଠିକ୍!',
    type_bad: 'ଠିକ୍ ନୁହେଁ। ତଳେ ଉତ୍ତର ଦେଖନ୍ତୁ।',
    type_label: 'ପ୍ରକାର',
    also: 'ଏହା ସହ',
    t_combination: 'ସଂଯୋଜନ',
    t_decomposition: 'ବିଘଟନ',
    t_displacement: 'ବିସ୍ଥାପନ',
    t_double: 'ଦ୍ୱି-ବିସ୍ଥାପନ',
    t_combustion: 'ଦହନ',
    t_redox: 'ଜାରଣ-ବିଜାରଣ',
    x_combination: 'ସଂଯୋଜନ: ଦୁଇ ବା ଅଧିକ ପଦାର୍ଥ ମିଶି ଗୋଟିଏ ନୂଆ ପଦାର୍ଥ ତିଆରି କରନ୍ତି (A + B → AB)।',
    x_decomposition: 'ବିଘଟନ: ଗୋଟିଏ ପଦାର୍ଥ ଉତ୍ତାପ, ଆଲୋକ କିମ୍ବା ବିଦ୍ୟୁତ୍ ଦ୍ୱାରା ଭାଙ୍ଗି ସରଳ ପଦାର୍ଥ ତିଆରି କରେ (AB → A + B)।',
    x_displacement: 'ବିସ୍ଥାପନ: ଅଧିକ ସକ୍ରିୟ ମୌଳିକ କମ୍ ସକ୍ରିୟ ମୌଳିକକୁ ତାହାର ଯୌଗିକରୁ ହଟାଇ ଦିଏ (A + BC → AC + B)।',
    x_double: 'ଦ୍ୱି-ବିସ୍ଥାପନ: ଦୁଇଟି ଯୌଗିକ ନିଜ ଆୟନ ଅଦଳବଦଳ କରନ୍ତି, ଏବଂ ପ୍ରାୟତଃ ଅଧଃକ୍ଷେପ ସୃଷ୍ଟି ହୁଏ (AB + CD → AD + CB)।',
    x_combustion: 'ଦହନ: ପଦାର୍ଥ ଅକ୍ସିଜେନରେ ଜଳି ଉତ୍ତାପ ଓ ଆଲୋକ ଦିଏ। ମିଥେନ ଓ LPG ପରି ଇନ୍ଧନ କାର୍ବନ ଡାଇଅକ୍ସାଇଡ୍ ଓ ଜଳ ଦିଏ।',
    x_redox: 'ଜାରଣ-ବିଜାରଣ: ଗୋଟିଏ ପଦାର୍ଥର ଜାରଣ ହୁଏ (ଅକ୍ସିଜେନ ଯୋଗ ହୁଏ ବା ହାଇଡ୍ରୋଜେନ ହଟିଯାଏ) ଏବଂ ଅନ୍ୟଟିର ବିଜାରଣ ହୁଏ (ଅକ୍ସିଜେନ ହଟିଯାଏ ବା ହାଇଡ୍ରୋଜେନ ଯୋଗ ହୁଏ)।',
    cond_heat: 'ଉତ୍ତାପ',
    cond_sun: 'ସୂର୍ଯ୍ୟାଲୋକ',
    cond_elec: 'ବିଦ୍ୟୁତ୍',
    states_note: '(s) କଠିନ · (l) ତରଳ · (g) ଗ୍ୟାସ · (aq) ଜଳରେ ଦ୍ରବୀଭୂତ',
    print_ws: 'ୱାର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    ws_title: 'ଏହି ରାସାୟନିକ ସମୀକରଣଗୁଡ଼ିକୁ ସନ୍ତୁଳିତ କରନ୍ତୁ',
    ws_name: 'ନାମ',
    ws_class: 'ଶ୍ରେଣୀ',
    ws_date: 'ତାରିଖ',
    ws_instr: 'ପ୍ରତ୍ୟେକ ଖାଲି ସ୍ଥାନରେ ସବୁଠାରୁ ଛୋଟ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା ଲେଖନ୍ତୁ, ତାପରେ ପ୍ରତିକ୍ରିୟାର ପ୍ରକାର ଲେଖନ୍ତୁ।',
    ws_key: 'ଉତ୍ତର ତାଲିକା',
    reset_progress: 'ପ୍ରଗତି ରିସେଟ୍ କରନ୍ତୁ',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ଶ୍ରେଣୀ ପାଇଁ ପରାମର୍ଶ',
    help_1: 'ଠିକ୍ ବଡ଼-ଛୋଟ ଅକ୍ଷରରେ ସମୀକରଣ ଲେଖନ୍ତୁ (Co ହେଉଛି କୋବାଲ୍ଟ, CO ହେଉଛି କାର୍ବନ ମନୋକ୍ସାଇଡ୍) ଏବଂ ସନ୍ତୁଳିତ କରନ୍ତୁ ଦବାନ୍ତୁ। ତୀର ପାଇଁ →, -> କିମ୍ବା = ଲେଖିପାରିବେ।',
    help_2: 'ବନ୍ଧନୀ ( ) ଓ [ ], ସ୍ଫଟିକ ଜଳଯୁକ୍ତ ଲବଣ (CuSO4·5H2O କିମ୍ବା CuSO4.5H2O), ଅବସ୍ଥା (s), (l), (g), (aq) ଏବଂ ଆୟନ (Fe^3+, SO4^2-, e-) ମଧ୍ୟ ବୁଝାଯାଏ।',
    help_3: '"କିପରି ସମାଧାନ ହେଲା" ପଢ଼ନ୍ତୁ: ଆପ୍ ପ୍ରତ୍ୟେକ ମୌଳିକ ପାଇଁ ଗୋଟିଏ ସମୀକରଣ ଲେଖି ସେଗୁଡ଼ିକୁ ସମାଧାନ କରେ। NCERT ବହିର ହିଟ୍ ଆଣ୍ଡ୍ ଟ୍ରାଏଲ୍ (ଚେଷ୍ଟା ଓ ଭୁଲ) ପଦ୍ଧତି ସହ ତୁଳନା କରନ୍ତୁ।',
    help_4: 'ସଙ୍କେତ ଆଗରେ ନିଜର ସଂଖ୍ୟା ଲେଖନ୍ତୁ (ଯେପରି 2H2 + O2 -> 2H2O), ଆପ୍ କହିବ ଆପଣଙ୍କ ଉତ୍ତର ଠିକ୍ କି ନାହିଁ।',
    help_5: 'ଅଭ୍ୟାସରେ NCERT ଦଶମ ଶ୍ରେଣୀର 15ଟି ପ୍ରତିକ୍ରିୟା ଅଛି। ଘର ପୂରଣ କରନ୍ତୁ, ଯାଞ୍ଚ କରନ୍ତୁ ଦବାନ୍ତୁ, ଅଟକିଗଲେ ସୂଚନା ନିଅନ୍ତୁ ଏବଂ ପ୍ରତିକ୍ରିୟାର ପ୍ରକାର କୁହନ୍ତୁ।',
    help_6: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ: ସ୍ମାର୍ଟବୋର୍ଡରେ ଫୁଲ୍ ସ୍କ୍ରିନରେ ଅଭ୍ୟାସର ଏକ ପ୍ରତିକ୍ରିୟା ଦେଖାନ୍ତୁ। ଦଳଗୁଡ଼ିକ 2 ମିନିଟରେ କାଗଜରେ ସନ୍ତୁଳିତ କରନ୍ତୁ, ତାପରେ ଗୋଟିଏ ଦଳ ନିଜ ପାହାଚଗୁଡ଼ିକ ବୁଝାନ୍ତୁ। ଘରକାମ ପାଇଁ ୱାର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ।'
  },
  ta: {
    app_title: 'வேதிச் சமன்பாடு சமன்செய்தல்',
    intro: 'எந்த வேதிச் சமன்பாட்டையும் படிப்படியாகச் சமன் செய்யுங்கள், இரு பக்க அணுக்களையும் எண்ணுங்கள், NCERT 10ஆம் வகுப்பின் 15 வினைகளைப் பயிற்சி செய்யுங்கள்.',
    tab_balance: 'சமன் செய்',
    tab_practice: 'பயிற்சி: NCERT 10',
    eq_label: 'ஒரு வேதிச் சமன்பாட்டைத் தட்டச்சு செய்யுங்கள்',
    eq_hint: 'இரு பக்கங்களுக்கு இடையே → (அல்லது -> அல்லது =), பொருள்களுக்கு இடையே + இடுங்கள். அடைப்புக்குறிகள், CuSO4·5H2O போன்ற நீரேறிய உப்புகள், (aq) போன்ற நிலைகள், Fe^3+ அல்லது SO4^2- போன்ற மின்சுமைகளும் வேலை செய்யும்.',
    balance_btn: 'சமன் செய்',
    keys_aria: 'குறியைச் சேர்',
    try_these: 'இந்த எடுத்துக்காட்டுகளை முயலுங்கள்',
    result_title: 'சமன்செய்யப்பட்ட சமன்பாடு',
    status_ok: 'சமன் ஆனது ✓',
    status_many: 'ஒன்றுக்கு மேற்பட்ட விடைகள்',
    atoms_title: 'இரு பக்கங்களிலும் அணுக்களின் எண்ணிக்கை',
    col_element: 'தனிமம்',
    col_left: 'இடப்பக்கம் (வினைபடு பொருள்கள்)',
    col_right: 'வலப்பக்கம் (வினைவிளை பொருள்கள்)',
    col_ok: 'சமமா?',
    charge: 'மின்சுமை',
    law: 'நிறை அழியா விதி: வேதிவினையில் அணுக்கள் புதிய முறையில் இணைகின்றன, அவ்வளவுதான். எந்த அணுவும் உருவாவதும் இல்லை, அழிவதும் இல்லை. எனவே ஒவ்வொரு தனிமத்தின் எண்ணிக்கையும் இரு பக்கமும் சமமாக இருக்க வேண்டும்.',
    steps_title: 'எப்படித் தீர்க்கப்பட்டது (இயற்கணித முறை)',
    s1_title: 'தனிமங்களைப் பட்டியலிடுங்கள்',
    s1_text: 'சமன்பாட்டில் இந்தத் தனிமங்கள் உள்ளன:',
    s2_title: 'ஒவ்வொரு வாய்ப்பாட்டின் முன்பும் ஒரு தெரியாத எண்ணை வையுங்கள்',
    s2_text: 'ஒவ்வொரு எழுத்தும் நாம் கண்டுபிடிக்க வேண்டிய ஒரு குணகம்.',
    s3_title: 'ஒவ்வொரு தனிமத்துக்கும் ஒரு சமன்பாடு எழுதுங்கள்',
    s3_text: 'இடப்பக்கம் ஒரு தனிமத்தின் அணுக்கள் = வலப்பக்கம் அதே தனிமத்தின் அணுக்கள்.',
    s3_charge: 'மொத்த மின்சுமையும் இரு பக்கமும் சமமாக இருக்க வேண்டும்.',
    s4_title: 'சமன்பாடுகளைத் தீர்க்கவும்',
    s4_let: '{eq} என்று கொள்வோம் ({f} முன் உள்ள எண்). அப்படியானால்:',
    s4_together: 'மீதமுள்ள சமன்பாடுகளை ஒன்றாகத் தீர்த்தால்:',
    s4_mult: 'மிகச் சிறிய முழு எண்களைப் பெற ஒவ்வொரு எண்ணையும் {m} ஆல் பெருக்குங்கள்:',
    s4_whole: 'இவை ஏற்கெனவே மிகச் சிறிய முழு எண்கள்:',
    s5_title: 'சரிபாருங்கள்',
    s5_text: 'இந்த எண்களுடன் ஒவ்வொரு அணுவையும் மீண்டும் எண்ணுங்கள் (அட்டவணையைப் பாருங்கள்). இரு பக்கமும் பொருந்துகிறது, எனவே சமன்பாடு சமன் ஆனது.',
    many_text: 'இந்தச் சமன்பாட்டை ஒன்றுக்கு மேற்பட்ட வழிகளில் சமன் செய்யலாம், ஏனெனில் இதில் இரண்டு அல்லது அதற்கு மேற்பட்ட தனித்தனி வினைகள் கலந்துள்ளன. ஒரு சாத்தியமான விடை காட்டப்பட்டுள்ளது. வாய்ப்பாடுகளை ஆசிரியரிடம் சரிபார்த்துக் கொள்ளுங்கள்.',
    many_none: 'இந்தச் சமன்பாட்டைப் பல வழிகளில் சமன் செய்யலாம், எனவே ஒரே விடை இல்லை. வாய்ப்பாடுகளைச் சரிபாருங்கள்.',
    err_empty: 'முதலில் ஒரு சமன்பாட்டை எழுதுங்கள், எ.கா.: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'வினைபடு பொருள்களுக்கும் வினைவிளை பொருள்களுக்கும் இடையே சரியாக ஒரு அம்புக்குறி (→, -> அல்லது =) இடுங்கள்.',
    err_side_empty: 'அம்புக்குறியின் ஒரு பக்கம் காலியாக உள்ளது. இரு பக்கமும் பொருள்களை எழுதுங்கள்.',
    err_plus: '+ குறியின் அருகில் ஏதோ விடுபட்டுள்ளது.',
    err_bad_char: 'வாய்ப்பாட்டில் "{c}" குறியைப் பயன்படுத்த முடியாது. தனிமக் குறியீடுகள், எண்கள், அடைப்புக்குறிகளை மட்டும் பயன்படுத்துங்கள்.',
    err_element: '"{e}" எந்தத் தனிமத்தின் குறியீடும் அல்ல. பெரிய, சிறிய எழுத்துகளைச் சரிபாருங்கள்: Co என்பது கோபால்ட், ஆனால் CO என்பது கார்பன் மோனாக்சைடு.',
    err_lower: 'தனிமக் குறியீடுகள் பெரிய எழுத்தில் தொடங்கும் (H, Fe, Cl). "{f}" ஐச் சரிபாருங்கள்.',
    err_bracket: '"{f}" இல் அடைப்புக்குறிகள் பொருந்தவில்லை.',
    err_formula: '"{f}" என்ற வாய்ப்பாட்டைப் படிக்க முடியவில்லை.',
    err_coef: 'வாய்ப்பாட்டின் முன் உள்ள எண் 1 அல்லது அதற்கு மேற்பட்ட முழு எண்ணாக இருக்க வேண்டும்.',
    err_too_many: 'பொருள்கள் அதிகம். அதிகபட்சம் {n} எழுதுங்கள்.',
    err_only_side: '{e} அம்புக்குறியின் ஒரு பக்கத்தில் மட்டுமே உள்ளது, எனவே இதைச் சமன் செய்யவே முடியாது. வாய்ப்பாடுகளைச் சரிபாருங்கள்.',
    err_impossible: 'இந்தச் சமன்பாட்டைச் சமன் செய்ய முடியாது. ஏதேனும் வாய்ப்பாடு தவறாக இருக்கலாம், அல்லது ஒரு வினைபடு பொருள் அல்லது வினைவிளை பொருள் விடுபட்டிருக்கலாம்.',
    err_charge: 'மின்சுமைகளைச் சமமாக்க முடியவில்லை. மின்சுமைகளைச் சரிபாருங்கள், அல்லது அரை வினைக்கு எலக்ட்ரான்களை (e-) சேருங்கள்.',
    err_zero: 'சமன் செய்ய முடியாது: {f} க்கு எண் 0 கிடைக்கும், அதாவது அது வினையில் பங்கேற்கவில்லை. அதை நீக்குங்கள் அல்லது வாய்ப்பாடுகளைச் சரிபாருங்கள்.',
    err_side: 'நேர்ம எண்களால் சமன் செய்ய முடியாது: {f} அம்புக்குறியின் மறுபக்கத்தில் இருக்க வேண்டும்.',
    yours_label: 'நீங்கள் எழுதியது:',
    yours_ok: 'உங்கள் எண்கள் சரி. சமன்பாடு சமன் ஆனது.',
    yours_multiple: 'உங்கள் எண்களால் சமன்பாடு சமன் ஆகிறது, ஆனால் அவை மிகச் சிறியவை அல்ல. எல்லாவற்றையும் {k} ஆல் வகுங்கள்.',
    yours_bad: 'உங்கள் எண்களால் சமன்பாடு இன்னும் சமன் ஆகவில்லை. சமமில்லாதவை: {list}. சரியான விடை மேலே காட்டப்பட்டுள்ளது.',
    pr_pick: 'ஒரு வினையைத் தேர்ந்தெடுங்கள்',
    pr_num: 'வினை {n} / {total}',
    pr_solved: 'தீர்த்தவை: {total} இல் {n}',
    pr_enter: 'கட்டங்களில் மிகச் சிறிய முழு எண்களை எழுதுங்கள். காலிக் கட்டம் என்றால் 1.',
    pr_done: 'தீர்க்கப்பட்டது',
    pr_shown: 'விடை பார்க்கப்பட்டது',
    coef_aria: '{f} முன் உள்ள எண்',
    check: 'சரிபார்',
    hint: 'குறிப்பு',
    show_answer: 'விடையைக் காட்டு',
    fb_ok: 'சரி! சமன்பாடு மிகச் சிறிய முழு எண்களால் சமன் ஆனது.',
    fb_ok_seen: 'சரி! ஆனால் இதன் விடையை நீங்கள் பார்த்துவிட்டீர்கள், எனவே இது தீர்த்ததாகக் கணக்கிடப்படவில்லை.',
    fb_multiple: 'சமன் ஆனது, ஆனால் இவை மிகச் சிறிய எண்கள் அல்ல. எல்லாவற்றையும் {k} ஆல் வகுங்கள்.',
    fb_bad: 'இன்னும் சமன் ஆகவில்லை. இவற்றைப் பாருங்கள்: {list}.',
    fb_invalid: 'கட்டங்களில் 1 முதல் 99 வரையிலான முழு எண்களை மட்டும் எழுதுங்கள்.',
    fb_shown: 'இதோ விடை. அட்டவணையில் ஒவ்வொரு அணுவையும் சரிபாருங்கள், பிறகு அடுத்த வினையை முயலுங்கள்.',
    hint_atoms: '{e} ஐ எண்ணுங்கள்: இடப்பக்கம் {l}, வலப்பக்கம் {r}. {list} முன் உள்ள எண்ணை மாற்றுங்கள்.',
    hint_reveal: '{f} முன் உள்ள எண் {n}.',
    hint_done: 'எல்லா எண்களும் சரி. சரிபார் அழுத்துங்கள்.',
    type_q: 'இது எந்த வகை வினை?',
    type_ok: 'சரி!',
    type_bad: 'சரியில்லை. கீழே விடையைப் பாருங்கள்.',
    type_label: 'வகை',
    also: 'மேலும்',
    t_combination: 'சேர்க்கை',
    t_decomposition: 'சிதைவு',
    t_displacement: 'இடப்பெயர்ச்சி',
    t_double: 'இரட்டை இடப்பெயர்ச்சி',
    t_combustion: 'எரிதல்',
    t_redox: 'ஆக்சிஜனேற்ற-ஒடுக்கம்',
    x_combination: 'சேர்க்கை: இரண்டு அல்லது அதற்கு மேற்பட்ட பொருள்கள் இணைந்து ஒரே புதிய பொருளாகின்றன (A + B → AB).',
    x_decomposition: 'சிதைவு: ஒரு பொருள் வெப்பம், ஒளி அல்லது மின்சாரத்தால் உடைந்து எளிய பொருள்களாகிறது (AB → A + B).',
    x_displacement: 'இடப்பெயர்ச்சி: அதிக வினைத்திறன் உள்ள தனிமம் குறைந்த வினைத்திறன் உள்ள தனிமத்தை அதன் சேர்மத்திலிருந்து வெளியேற்றுகிறது (A + BC → AC + B).',
    x_double: 'இரட்டை இடப்பெயர்ச்சி: இரண்டு சேர்மங்கள் தங்கள் அயனிகளை மாற்றிக்கொள்கின்றன, பெரும்பாலும் வீழ்படிவு உருவாகிறது (AB + CD → AD + CB).',
    x_combustion: 'எரிதல்: ஒரு பொருள் ஆக்சிஜனில் எரிந்து வெப்பமும் ஒளியும் தருகிறது. மீத்தேன், LPG போன்ற எரிபொருள்கள் கார்பன் டை ஆக்சைடும் நீரும் தருகின்றன.',
    x_redox: 'ஆக்சிஜனேற்ற-ஒடுக்கம்: ஒரு பொருள் ஆக்சிஜனேற்றம் அடைகிறது (ஆக்சிஜன் சேர்கிறது அல்லது ஹைட்ரஜன் நீங்குகிறது), மற்றொன்று ஒடுக்கம் அடைகிறது (ஆக்சிஜன் நீங்குகிறது அல்லது ஹைட்ரஜன் சேர்கிறது).',
    cond_heat: 'வெப்பம்',
    cond_sun: 'சூரிய ஒளி',
    cond_elec: 'மின்சாரம்',
    states_note: '(s) திண்மம் · (l) நீர்மம் · (g) வாயு · (aq) நீரில் கரைந்தது',
    print_ws: 'பயிற்சித்தாளை அச்சிடு',
    ws_title: 'இந்த வேதிச் சமன்பாடுகளைச் சமன் செய்யுங்கள்',
    ws_name: 'பெயர்',
    ws_class: 'வகுப்பு',
    ws_date: 'தேதி',
    ws_instr: 'ஒவ்வொரு கோட்டிலும் மிகச் சிறிய முழு எண்ணை எழுதுங்கள், பிறகு வினையின் வகையை எழுதுங்கள்.',
    ws_key: 'விடைக்குறிப்பு',
    reset_progress: 'முன்னேற்றத்தை மீட்டமை',
    help_title: 'எப்படிப் பயன்படுத்துவது / வகுப்பறைக்கான யோசனைகள்',
    help_1: 'சரியான பெரிய, சிறிய எழுத்துகளுடன் சமன்பாட்டை எழுதுங்கள் (Co என்பது கோபால்ட், CO என்பது கார்பன் மோனாக்சைடு), பிறகு சமன் செய் அழுத்துங்கள். அம்புக்குறிக்கு →, -> அல்லது = பயன்படுத்தலாம்.',
    help_2: 'அடைப்புக்குறிகள் ( ) மற்றும் [ ], நீரேறிய உப்புகள் (CuSO4·5H2O அல்லது CuSO4.5H2O), நிலைகள் (s), (l), (g), (aq), அயனிகள் (Fe^3+, SO4^2-, e-) ஆகியவையும் புரிந்துகொள்ளப்படும்.',
    help_3: '"எப்படித் தீர்க்கப்பட்டது" பகுதியைப் படியுங்கள்: செயலி ஒவ்வொரு தனிமத்துக்கும் ஒரு சமன்பாடு எழுதித் தீர்க்கிறது. உங்கள் NCERT புத்தகத்தின் முயன்று பார்த்தல் (ஹிட் அண்ட் ட்ரையல்) முறையுடன் ஒப்பிடுங்கள்.',
    help_4: 'வாய்ப்பாடுகளின் முன் உங்கள் சொந்த எண்களை எழுதுங்கள் (எ.கா. 2H2 + O2 -> 2H2O), உங்கள் விடை சரியா என்று செயலி சொல்லும்.',
    help_5: 'பயிற்சியில் NCERT 10ஆம் வகுப்பின் 15 வினைகள் உள்ளன. கட்டங்களை நிரப்புங்கள், சரிபார் அழுத்துங்கள், சிக்கினால் குறிப்பைப் பெறுங்கள், வினையின் வகையைச் சொல்லுங்கள்.',
    help_6: 'வகுப்பறைச் செயல்பாடு: ஸ்மார்ட்போர்டில் முழுத் திரையில் பயிற்சியிலிருந்து ஒரு வினையைக் காட்டுங்கள். குழுக்கள் 2 நிமிடங்களில் தாளில் அதைச் சமன் செய்யட்டும், பிறகு ஒரு குழு தன் படிகளை விளக்கட்டும். வீட்டுப்பாடத்துக்குப் பயிற்சித்தாளை அச்சிடுங்கள்.'
  },
  te: {
    app_title: 'రసాయన సమీకరణాల తుల్యం',
    intro: 'ఏ రసాయన సమీకరణాన్నైనా దశలవారీగా తుల్యం చేయండి, రెండు వైపులా పరమాణువులను లెక్కించండి, NCERT 10వ తరగతిలోని 15 చర్యలను సాధన చేయండి.',
    tab_balance: 'తుల్యం చేయండి',
    tab_practice: 'సాధన: NCERT 10',
    eq_label: 'రసాయన సమీకరణాన్ని టైప్ చేయండి',
    eq_hint: 'రెండు వైపుల మధ్య → (లేదా -> లేదా =), పదార్థాల మధ్య + పెట్టండి. బ్రాకెట్లు, CuSO4·5H2O లాంటి స్ఫటిక జలం ఉన్న లవణాలు, (aq) లాంటి స్థితులు, Fe^3+ లేదా SO4^2- లాంటి ఆవేశాలు కూడా పనిచేస్తాయి.',
    balance_btn: 'తుల్యం చేయండి',
    keys_aria: 'గుర్తును చేర్చండి',
    try_these: 'ఈ ఉదాహరణలు ప్రయత్నించండి',
    result_title: 'తుల్య సమీకరణం',
    status_ok: 'తుల్యమైంది ✓',
    status_many: 'ఒకటి కంటే ఎక్కువ సమాధానాలు',
    atoms_title: 'రెండు వైపులా పరమాణువుల సంఖ్య',
    col_element: 'మూలకం',
    col_left: 'ఎడమ వైపు (క్రియాజనకాలు)',
    col_right: 'కుడి వైపు (క్రియాజన్యాలు)',
    col_ok: 'సమానమా?',
    charge: 'ఆవేశం',
    law: 'ద్రవ్యరాశి నిత్యత్వ నియమం: రసాయన చర్యలో పరమాణువులు కొత్తగా అమరుతాయి, అంతే. ఏ పరమాణువూ కొత్తగా పుట్టదు, నశించదు. కాబట్టి ప్రతి మూలకం సంఖ్య రెండు వైపులా సమానంగా ఉండాలి.',
    steps_title: 'ఎలా సాధించాం (బీజగణిత పద్ధతి)',
    s1_title: 'మూలకాల జాబితా రాయండి',
    s1_text: 'సమీకరణంలో ఈ మూలకాలు ఉన్నాయి:',
    s2_title: 'ప్రతి ఫార్ములా ముందు ఒక తెలియని సంఖ్య పెట్టండి',
    s2_text: 'ప్రతి అక్షరం మనం కనుక్కోవలసిన ఒక గుణకం.',
    s3_title: 'ప్రతి మూలకానికి ఒక సమీకరణం రాయండి',
    s3_text: 'ఎడమ వైపు ఒక మూలకం పరమాణువులు = కుడి వైపు అదే మూలకం పరమాణువులు.',
    s3_charge: 'మొత్తం ఆవేశం కూడా రెండు వైపులా సమానంగా ఉండాలి.',
    s4_title: 'సమీకరణాలను సాధించండి',
    s4_let: '{eq} అనుకుందాం ({f} ముందున్న సంఖ్య). అప్పుడు:',
    s4_together: 'మిగిలిన సమీకరణాలను కలిపి సాధిస్తే:',
    s4_mult: 'అతి చిన్న పూర్ణ సంఖ్యల కోసం ప్రతి సంఖ్యను {m} తో గుణించండి:',
    s4_whole: 'ఇవి ఇప్పటికే అతి చిన్న పూర్ణ సంఖ్యలు:',
    s5_title: 'సరిచూడండి',
    s5_text: 'ఈ సంఖ్యలతో ప్రతి పరమాణువును మళ్లీ లెక్కించండి (పట్టిక చూడండి). రెండు వైపులా సరిపోయింది, కాబట్టి సమీకరణం తుల్యమైంది.',
    many_text: 'ఈ సమీకరణాన్ని ఒకటి కంటే ఎక్కువ విధాలుగా తుల్యం చేయవచ్చు, ఎందుకంటే ఇందులో రెండు లేదా అంతకంటే ఎక్కువ వేర్వేరు చర్యలు కలిసి ఉన్నాయి. ఒక సాధ్యమైన సమాధానం చూపించాం. ఫార్ములాలను మీ ఉపాధ్యాయులతో సరిచూసుకోండి.',
    many_none: 'ఈ సమీకరణాన్ని చాలా విధాలుగా తుల్యం చేయవచ్చు, కాబట్టి ఒకే సమాధానం లేదు. ఫార్ములాలను సరిచూడండి.',
    err_empty: 'ముందుగా ఒక సమీకరణం రాయండి, ఉదాహరణకు: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'క్రియాజనకాలు, క్రియాజన్యాల మధ్య సరిగ్గా ఒక బాణం (→, -> లేదా =) పెట్టండి.',
    err_side_empty: 'బాణానికి ఒక వైపు ఖాళీగా ఉంది. రెండు వైపులా పదార్థాలు రాయండి.',
    err_plus: '+ గుర్తు దగ్గర ఏదో వదిలేశారు.',
    err_bad_char: 'ఫార్ములాలో "{c}" గుర్తును వాడలేం. మూలక సంకేతాలు, అంకెలు, బ్రాకెట్లు మాత్రమే వాడండి.',
    err_element: '"{e}" ఏ మూలకానికీ సంకేతం కాదు. పెద్ద, చిన్న అక్షరాలు సరిచూడండి: Co అంటే కోబాల్ట్, కానీ CO అంటే కార్బన్ మోనాక్సైడ్.',
    err_lower: 'మూలక సంకేతాలు పెద్ద అక్షరంతో మొదలవుతాయి (H, Fe, Cl). "{f}" సరిచూడండి.',
    err_bracket: '"{f}" లో బ్రాకెట్లు సరిపోలడం లేదు.',
    err_formula: '"{f}" ఫార్ములాను చదవలేకపోయాం.',
    err_coef: 'ఫార్ములా ముందున్న సంఖ్య 1 లేదా అంతకంటే పెద్ద పూర్ణ సంఖ్య కావాలి.',
    err_too_many: 'పదార్థాలు చాలా ఎక్కువ. గరిష్ఠంగా {n} రాయండి.',
    err_only_side: '{e} బాణానికి ఒక వైపు మాత్రమే ఉంది, కాబట్టి దీన్ని ఎప్పటికీ తుల్యం చేయలేం. ఫార్ములాలను సరిచూడండి.',
    err_impossible: 'ఈ సమీకరణాన్ని తుల్యం చేయలేం. ఏదైనా ఫార్ములా తప్పు కావచ్చు, లేదా ఒక క్రియాజనకం లేదా క్రియాజన్యం వదిలేసి ఉండవచ్చు.',
    err_charge: 'ఆవేశాలను సమానం చేయలేం. ఆవేశాలను సరిచూడండి, లేదా అర్ధ చర్య కోసం ఎలక్ట్రాన్లు (e-) చేర్చండి.',
    err_zero: 'తుల్యం చేయలేం: {f} కి సంఖ్య 0 వస్తుంది, అంటే అది చర్యలో పాల్గొనదు. దాన్ని తీసివేయండి లేదా ఫార్ములాలను సరిచూడండి.',
    err_side: 'ధన సంఖ్యలతో తుల్యం చేయలేం: {f} బాణానికి అవతలి వైపు ఉండాలి.',
    yours_label: 'మీరు రాసింది:',
    yours_ok: 'మీ సంఖ్యలు సరైనవి. సమీకరణం తుల్యమైంది.',
    yours_multiple: 'మీ సంఖ్యలతో సమీకరణం తుల్యమవుతుంది, కానీ అవి అతి చిన్నవి కావు. అన్నింటినీ {k} తో భాగించండి.',
    yours_bad: 'మీ సంఖ్యలతో సమీకరణం ఇంకా తుల్యం కాలేదు. సమానం కానివి: {list}. సరైన సమాధానం పైన చూపించాం.',
    pr_pick: 'ఒక చర్యను ఎంచుకోండి',
    pr_num: 'చర్య {n} / {total}',
    pr_solved: 'సాధించినవి: {total} లో {n}',
    pr_enter: 'పెట్టెల్లో అతి చిన్న పూర్ణ సంఖ్యలు రాయండి. ఖాళీ పెట్టె అంటే 1.',
    pr_done: 'సాధించారు',
    pr_shown: 'సమాధానం చూశారు',
    coef_aria: '{f} ముందున్న సంఖ్య',
    check: 'సరిచూడు',
    hint: 'సూచన',
    show_answer: 'సమాధానం చూపు',
    fb_ok: 'సరైనది! సమీకరణం అతి చిన్న పూర్ణ సంఖ్యలతో తుల్యమైంది.',
    fb_ok_seen: 'సరైనది! కానీ మీరు దీని సమాధానం చూశారు, కాబట్టి దీన్ని సాధించినట్లుగా లెక్కించలేదు.',
    fb_multiple: 'తుల్యమైంది, కానీ ఇవి అతి చిన్న సంఖ్యలు కావు. అన్నింటినీ {k} తో భాగించండి.',
    fb_bad: 'ఇంకా తుల్యం కాలేదు. వీటిని చూడండి: {list}.',
    fb_invalid: 'పెట్టెల్లో 1 నుంచి 99 వరకు పూర్ణ సంఖ్యలు మాత్రమే రాయండి.',
    fb_shown: 'ఇదిగో సమాధానం. పట్టికలో ప్రతి పరమాణువును సరిచూడండి, తర్వాత తదుపరి చర్యను ప్రయత్నించండి.',
    hint_atoms: '{e} లెక్కించండి: ఎడమ వైపు {l}, కుడి వైపు {r}. {list} ముందున్న సంఖ్యను మార్చండి.',
    hint_reveal: '{f} ముందున్న సంఖ్య {n}.',
    hint_done: 'అన్ని సంఖ్యలూ సరైనవే. సరిచూడు నొక్కండి.',
    type_q: 'ఇది ఏ రకమైన చర్య?',
    type_ok: 'సరైనది!',
    type_bad: 'సరి కాదు. కింద సమాధానం చూడండి.',
    type_label: 'రకం',
    also: 'ఇంకా',
    t_combination: 'సంయోగం',
    t_decomposition: 'వియోగం',
    t_displacement: 'స్థానభ్రంశం',
    t_double: 'ద్వంద్వ స్థానభ్రంశం',
    t_combustion: 'దహనం',
    t_redox: 'రెడాక్స్',
    x_combination: 'సంయోగం: రెండు లేదా అంతకంటే ఎక్కువ పదార్థాలు కలిసి ఒకే కొత్త పదార్థంగా ఏర్పడతాయి (A + B → AB).',
    x_decomposition: 'వియోగం: ఒక పదార్థం వేడి, కాంతి లేదా విద్యుత్ వల్ల విడిపోయి సరళ పదార్థాలుగా మారుతుంది (AB → A + B).',
    x_displacement: 'స్థానభ్రంశం: ఎక్కువ చర్యాశీలత ఉన్న మూలకం తక్కువ చర్యాశీలత ఉన్న మూలకాన్ని దాని సమ్మేళనం నుంచి బయటకు నెడుతుంది (A + BC → AC + B).',
    x_double: 'ద్వంద్వ స్థానభ్రంశం: రెండు సమ్మేళనాలు తమ అయాన్లను మార్చుకుంటాయి, తరచుగా అవక్షేపం ఏర్పడుతుంది (AB + CD → AD + CB).',
    x_combustion: 'దహనం: పదార్థం ఆక్సిజన్‌లో మండి వేడి, కాంతి ఇస్తుంది. మీథేన్, LPG లాంటి ఇంధనాలు కార్బన్ డయాక్సైడ్, నీరు ఇస్తాయి.',
    x_redox: 'రెడాక్స్: ఒక పదార్థం ఆక్సీకరణం చెందుతుంది (ఆక్సిజన్ కలుస్తుంది లేదా హైడ్రోజన్ పోతుంది), మరొకటి క్షయకరణం చెందుతుంది (ఆక్సిజన్ పోతుంది లేదా హైడ్రోజన్ కలుస్తుంది).',
    cond_heat: 'వేడి',
    cond_sun: 'సూర్యకాంతి',
    cond_elec: 'విద్యుత్',
    states_note: '(s) ఘనం · (l) ద్రవం · (g) వాయువు · (aq) నీటిలో కరిగినది',
    print_ws: 'వర్క్‌షీట్ ప్రింట్ చేయండి',
    ws_title: 'ఈ రసాయన సమీకరణాలను తుల్యం చేయండి',
    ws_name: 'పేరు',
    ws_class: 'తరగతి',
    ws_date: 'తేదీ',
    ws_instr: 'ప్రతి ఖాళీలో అతి చిన్న పూర్ణ సంఖ్య రాయండి, తర్వాత చర్య రకాన్ని రాయండి.',
    ws_key: 'సమాధానాల కీ',
    reset_progress: 'పురోగతిని రీసెట్ చేయండి',
    help_title: 'ఎలా వాడాలి / తరగతి గదికి ఆలోచనలు',
    help_1: 'సరైన పెద్ద, చిన్న అక్షరాలతో సమీకరణం రాయండి (Co అంటే కోబాల్ట్, CO అంటే కార్బన్ మోనాక్సైడ్), తర్వాత తుల్యం చేయండి నొక్కండి. బాణం కోసం →, -> లేదా = వాడవచ్చు.',
    help_2: 'బ్రాకెట్లు ( ), [ ], స్ఫటిక జలం ఉన్న లవణాలు (CuSO4·5H2O లేదా CuSO4.5H2O), స్థితులు (s), (l), (g), (aq), అయాన్లు (Fe^3+, SO4^2-, e-) కూడా అర్థమవుతాయి.',
    help_3: '"ఎలా సాధించాం" చదవండి: యాప్ ప్రతి మూలకానికి ఒక సమీకరణం రాసి వాటిని సాధిస్తుంది. మీ NCERT పుస్తకంలోని ప్రయత్న-దోష (హిట్ అండ్ ట్రయల్) పద్ధతితో పోల్చండి.',
    help_4: 'ఫార్ములాల ముందు మీ సొంత సంఖ్యలు రాయండి (ఉదా. 2H2 + O2 -> 2H2O), మీ సమాధానం సరైనదో కాదో యాప్ చెబుతుంది.',
    help_5: 'సాధనలో NCERT 10వ తరగతిలోని 15 చర్యలు ఉన్నాయి. పెట్టెలు నింపండి, సరిచూడు నొక్కండి, ఇరుక్కుపోతే సూచన తీసుకోండి, చర్య రకాన్ని చెప్పండి.',
    help_6: 'తరగతి కార్యకలాపం: స్మార్ట్‌బోర్డ్‌పై ఫుల్ స్క్రీన్‌లో సాధనలోని ఒక చర్యను చూపించండి. జట్లు 2 నిమిషాల్లో కాగితంపై తుల్యం చేయాలి, తర్వాత ఒక జట్టు తన దశలను వివరించాలి. ఇంటిపని కోసం వర్క్‌షీట్ ప్రింట్ చేయండి.'
  },
  kn: {
    app_title: 'ರಾಸಾಯನಿಕ ಸಮೀಕರಣ ಸರಿದೂಗಿಸುವಿಕೆ',
    intro: 'ಯಾವುದೇ ರಾಸಾಯನಿಕ ಸಮೀಕರಣವನ್ನು ಹಂತ ಹಂತವಾಗಿ ಸರಿದೂಗಿಸಿ, ಎರಡೂ ಬದಿಯ ಪರಮಾಣುಗಳನ್ನು ಎಣಿಸಿ, NCERT 10ನೇ ತರಗತಿಯ 15 ಕ್ರಿಯೆಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ.',
    tab_balance: 'ಸರಿದೂಗಿಸಿ',
    tab_practice: 'ಅಭ್ಯಾಸ: NCERT 10',
    eq_label: 'ರಾಸಾಯನಿಕ ಸಮೀಕರಣವನ್ನು ಟೈಪ್ ಮಾಡಿ',
    eq_hint: 'ಎರಡು ಬದಿಗಳ ನಡುವೆ → (ಅಥವಾ -> ಅಥವಾ =) ಮತ್ತು ವಸ್ತುಗಳ ನಡುವೆ + ಹಾಕಿ. ಆವರಣಗಳು, CuSO4·5H2O ನಂತಹ ಸ್ಫಟಿಕ ಜಲವಿರುವ ಲವಣಗಳು, (aq) ನಂತಹ ಸ್ಥಿತಿಗಳು ಮತ್ತು Fe^3+ ಅಥವಾ SO4^2- ನಂತಹ ಆವೇಶಗಳೂ ಕೆಲಸ ಮಾಡುತ್ತವೆ.',
    balance_btn: 'ಸರಿದೂಗಿಸಿ',
    keys_aria: 'ಚಿಹ್ನೆ ಸೇರಿಸಿ',
    try_these: 'ಈ ಉದಾಹರಣೆಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ',
    result_title: 'ಸರಿದೂಗಿಸಿದ ಸಮೀಕರಣ',
    status_ok: 'ಸರಿದೂಗಿದೆ ✓',
    status_many: 'ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ಉತ್ತರಗಳು',
    atoms_title: 'ಎರಡೂ ಬದಿಗಳಲ್ಲಿ ಪರಮಾಣುಗಳ ಎಣಿಕೆ',
    col_element: 'ಧಾತು',
    col_left: 'ಎಡಬದಿ (ಪ್ರತಿವರ್ತಕಗಳು)',
    col_right: 'ಬಲಬದಿ (ಉತ್ಪನ್ನಗಳು)',
    col_ok: 'ಸಮವೇ?',
    charge: 'ಆವೇಶ',
    law: 'ದ್ರವ್ಯರಾಶಿ ಸಂರಕ್ಷಣಾ ನಿಯಮ: ರಾಸಾಯನಿಕ ಕ್ರಿಯೆಯಲ್ಲಿ ಪರಮಾಣುಗಳು ಹೊಸ ರೀತಿಯಲ್ಲಿ ಜೋಡಣೆಯಾಗುತ್ತವೆ ಅಷ್ಟೇ. ಯಾವ ಪರಮಾಣುವೂ ಹುಟ್ಟುವುದಿಲ್ಲ, ನಾಶವಾಗುವುದಿಲ್ಲ. ಆದ್ದರಿಂದ ಪ್ರತಿ ಧಾತುವಿನ ಸಂಖ್ಯೆ ಎರಡೂ ಬದಿಗಳಲ್ಲಿ ಸಮವಾಗಿರಬೇಕು.',
    steps_title: 'ಹೇಗೆ ಬಿಡಿಸಲಾಯಿತು (ಬೀಜಗಣಿತ ವಿಧಾನ)',
    s1_title: 'ಧಾತುಗಳ ಪಟ್ಟಿ ಮಾಡಿ',
    s1_text: 'ಸಮೀಕರಣದಲ್ಲಿ ಈ ಧಾತುಗಳಿವೆ:',
    s2_title: 'ಪ್ರತಿ ಸೂತ್ರದ ಮುಂದೆ ಒಂದು ಅಜ್ಞಾತ ಸಂಖ್ಯೆ ಇಡಿ',
    s2_text: 'ಪ್ರತಿ ಅಕ್ಷರವೂ ನಾವು ಕಂಡುಹಿಡಿಯಬೇಕಾದ ಒಂದು ಗುಣಾಂಕ.',
    s3_title: 'ಪ್ರತಿ ಧಾತುವಿಗೆ ಒಂದು ಸಮೀಕರಣ ಬರೆಯಿರಿ',
    s3_text: 'ಎಡಬದಿಯಲ್ಲಿ ಒಂದು ಧಾತುವಿನ ಪರಮಾಣುಗಳು = ಬಲಬದಿಯಲ್ಲಿ ಅದೇ ಧಾತುವಿನ ಪರಮಾಣುಗಳು.',
    s3_charge: 'ಒಟ್ಟು ಆವೇಶವೂ ಎರಡೂ ಬದಿಗಳಲ್ಲಿ ಸಮವಾಗಿರಬೇಕು.',
    s4_title: 'ಸಮೀಕರಣಗಳನ್ನು ಬಿಡಿಸಿ',
    s4_let: '{eq} ಎಂದುಕೊಳ್ಳೋಣ ({f} ಮುಂದಿನ ಸಂಖ್ಯೆ). ಆಗ:',
    s4_together: 'ಉಳಿದ ಸಮೀಕರಣಗಳನ್ನು ಒಟ್ಟಿಗೆ ಬಿಡಿಸಿದರೆ:',
    s4_mult: 'ಅತಿ ಚಿಕ್ಕ ಪೂರ್ಣ ಸಂಖ್ಯೆಗಳನ್ನು ಪಡೆಯಲು ಪ್ರತಿ ಸಂಖ್ಯೆಯನ್ನು {m} ರಿಂದ ಗುಣಿಸಿ:',
    s4_whole: 'ಇವು ಈಗಾಗಲೇ ಅತಿ ಚಿಕ್ಕ ಪೂರ್ಣ ಸಂಖ್ಯೆಗಳು:',
    s5_title: 'ಪರಿಶೀಲಿಸಿ',
    s5_text: 'ಈ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ಪ್ರತಿ ಪರಮಾಣುವನ್ನು ಮತ್ತೆ ಎಣಿಸಿ (ಕೋಷ್ಟಕ ನೋಡಿ). ಎರಡೂ ಬದಿ ಹೊಂದುತ್ತವೆ, ಆದ್ದರಿಂದ ಸಮೀಕರಣ ಸರಿದೂಗಿದೆ.',
    many_text: 'ಈ ಸಮೀಕರಣವನ್ನು ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ರೀತಿಯಲ್ಲಿ ಸರಿದೂಗಿಸಬಹುದು, ಏಕೆಂದರೆ ಇದರಲ್ಲಿ ಎರಡು ಅಥವಾ ಹೆಚ್ಚು ಬೇರೆ ಬೇರೆ ಕ್ರಿಯೆಗಳು ಬೆರೆತಿವೆ. ಒಂದು ಸಾಧ್ಯ ಉತ್ತರವನ್ನು ತೋರಿಸಲಾಗಿದೆ. ಸೂತ್ರಗಳನ್ನು ನಿಮ್ಮ ಶಿಕ್ಷಕರೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ.',
    many_none: 'ಈ ಸಮೀಕರಣವನ್ನು ಹಲವು ರೀತಿಯಲ್ಲಿ ಸರಿದೂಗಿಸಬಹುದು, ಆದ್ದರಿಂದ ಒಂದೇ ಉತ್ತರ ಇಲ್ಲ. ಸೂತ್ರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    err_empty: 'ಮೊದಲು ಒಂದು ಸಮೀಕರಣ ಬರೆಯಿರಿ, ಉದಾಹರಣೆಗೆ: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'ಪ್ರತಿವರ್ತಕಗಳು ಮತ್ತು ಉತ್ಪನ್ನಗಳ ನಡುವೆ ಸರಿಯಾಗಿ ಒಂದು ಬಾಣ (→, -> ಅಥವಾ =) ಹಾಕಿ.',
    err_side_empty: 'ಬಾಣದ ಒಂದು ಬದಿ ಖಾಲಿಯಾಗಿದೆ. ಎರಡೂ ಬದಿಗಳಲ್ಲಿ ವಸ್ತುಗಳನ್ನು ಬರೆಯಿರಿ.',
    err_plus: '+ ಚಿಹ್ನೆಯ ಬಳಿ ಏನೋ ಬಿಟ್ಟುಹೋಗಿದೆ.',
    err_bad_char: 'ಸೂತ್ರದಲ್ಲಿ "{c}" ಚಿಹ್ನೆ ಬಳಸಲಾಗದು. ಧಾತು ಸಂಕೇತಗಳು, ಅಂಕಿಗಳು ಮತ್ತು ಆವರಣಗಳನ್ನು ಬಳಸಿ.',
    err_element: '"{e}" ಯಾವುದೇ ಧಾತುವಿನ ಸಂಕೇತವಲ್ಲ. ದೊಡ್ಡ ಮತ್ತು ಸಣ್ಣ ಅಕ್ಷರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ: Co ಎಂದರೆ ಕೋಬಾಲ್ಟ್, ಆದರೆ CO ಎಂದರೆ ಕಾರ್ಬನ್ ಮೊನಾಕ್ಸೈಡ್.',
    err_lower: 'ಧಾತು ಸಂಕೇತಗಳು ದೊಡ್ಡ ಅಕ್ಷರದಿಂದ ಆರಂಭವಾಗುತ್ತವೆ (H, Fe, Cl). "{f}" ಪರಿಶೀಲಿಸಿ.',
    err_bracket: '"{f}" ನಲ್ಲಿ ಆವರಣಗಳು ಹೊಂದುತ್ತಿಲ್ಲ.',
    err_formula: '"{f}" ಸೂತ್ರವನ್ನು ಓದಲಾಗಲಿಲ್ಲ.',
    err_coef: 'ಸೂತ್ರದ ಮುಂದಿನ ಸಂಖ್ಯೆ 1 ಅಥವಾ ಅದಕ್ಕಿಂತ ದೊಡ್ಡ ಪೂರ್ಣ ಸಂಖ್ಯೆಯಾಗಿರಬೇಕು.',
    err_too_many: 'ತುಂಬಾ ಹೆಚ್ಚು ವಸ್ತುಗಳಿವೆ. ಗರಿಷ್ಠ {n} ಬರೆಯಿರಿ.',
    err_only_side: '{e} ಬಾಣದ ಒಂದೇ ಬದಿಯಲ್ಲಿದೆ, ಆದ್ದರಿಂದ ಇದನ್ನು ಎಂದಿಗೂ ಸರಿದೂಗಿಸಲಾಗದು. ಸೂತ್ರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    err_impossible: 'ಈ ಸಮೀಕರಣವನ್ನು ಸರಿದೂಗಿಸಲಾಗದು. ಯಾವುದಾದರೂ ಸೂತ್ರ ತಪ್ಪಾಗಿರಬಹುದು, ಅಥವಾ ಒಂದು ಪ್ರತಿವರ್ತಕ ಅಥವಾ ಉತ್ಪನ್ನ ಬಿಟ್ಟುಹೋಗಿರಬಹುದು.',
    err_charge: 'ಆವೇಶಗಳನ್ನು ಸಮಗೊಳಿಸಲಾಗದು. ಆವೇಶಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ಅಥವಾ ಅರ್ಧ ಕ್ರಿಯೆಗೆ ಎಲೆಕ್ಟ್ರಾನ್‌ಗಳನ್ನು (e-) ಸೇರಿಸಿ.',
    err_zero: 'ಸರಿದೂಗಿಸಲಾಗದು: {f} ಗೆ ಸಂಖ್ಯೆ 0 ಬರುತ್ತದೆ, ಅಂದರೆ ಅದು ಕ್ರಿಯೆಯಲ್ಲಿ ಭಾಗವಹಿಸುವುದಿಲ್ಲ. ಅದನ್ನು ತೆಗೆದುಹಾಕಿ ಅಥವಾ ಸೂತ್ರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    err_side: 'ಧನ ಸಂಖ್ಯೆಗಳಿಂದ ಸರಿದೂಗಿಸಲಾಗದು: {f} ಬಾಣದ ಇನ್ನೊಂದು ಬದಿಯಲ್ಲಿರಬೇಕು.',
    yours_label: 'ನೀವು ಬರೆದದ್ದು:',
    yours_ok: 'ನಿಮ್ಮ ಸಂಖ್ಯೆಗಳು ಸರಿಯಾಗಿವೆ. ಸಮೀಕರಣ ಸರಿದೂಗಿದೆ.',
    yours_multiple: 'ನಿಮ್ಮ ಸಂಖ್ಯೆಗಳಿಂದ ಸಮೀಕರಣ ಸರಿದೂಗುತ್ತದೆ, ಆದರೆ ಅವು ಅತಿ ಚಿಕ್ಕವಲ್ಲ. ಎಲ್ಲವನ್ನೂ {k} ರಿಂದ ಭಾಗಿಸಿ.',
    yours_bad: 'ನಿಮ್ಮ ಸಂಖ್ಯೆಗಳಿಂದ ಸಮೀಕರಣ ಇನ್ನೂ ಸರಿದೂಗಿಲ್ಲ. ಸಮವಿಲ್ಲದವು: {list}. ಸರಿಯಾದ ಉತ್ತರವನ್ನು ಮೇಲೆ ತೋರಿಸಲಾಗಿದೆ.',
    pr_pick: 'ಒಂದು ಕ್ರಿಯೆಯನ್ನು ಆರಿಸಿ',
    pr_num: 'ಕ್ರಿಯೆ {n} / {total}',
    pr_solved: 'ಬಿಡಿಸಿದವು: {total} ರಲ್ಲಿ {n}',
    pr_enter: 'ಚೌಕಗಳಲ್ಲಿ ಅತಿ ಚಿಕ್ಕ ಪೂರ್ಣ ಸಂಖ್ಯೆಗಳನ್ನು ಬರೆಯಿರಿ. ಖಾಲಿ ಚೌಕ ಎಂದರೆ 1.',
    pr_done: 'ಬಿಡಿಸಲಾಗಿದೆ',
    pr_shown: 'ಉತ್ತರ ನೋಡಲಾಗಿದೆ',
    coef_aria: '{f} ಮುಂದಿನ ಸಂಖ್ಯೆ',
    check: 'ಪರಿಶೀಲಿಸಿ',
    hint: 'ಸುಳಿವು',
    show_answer: 'ಉತ್ತರ ತೋರಿಸಿ',
    fb_ok: 'ಸರಿ! ಸಮೀಕರಣ ಅತಿ ಚಿಕ್ಕ ಪೂರ್ಣ ಸಂಖ್ಯೆಗಳಿಂದ ಸರಿದೂಗಿದೆ.',
    fb_ok_seen: 'ಸರಿ! ಆದರೆ ನೀವು ಇದರ ಉತ್ತರವನ್ನು ನೋಡಿದ್ದೀರಿ, ಆದ್ದರಿಂದ ಇದನ್ನು ಬಿಡಿಸಿದ್ದು ಎಂದು ಎಣಿಸಿಲ್ಲ.',
    fb_multiple: 'ಸರಿದೂಗಿದೆ, ಆದರೆ ಇವು ಅತಿ ಚಿಕ್ಕ ಸಂಖ್ಯೆಗಳಲ್ಲ. ಎಲ್ಲವನ್ನೂ {k} ರಿಂದ ಭಾಗಿಸಿ.',
    fb_bad: 'ಇನ್ನೂ ಸರಿದೂಗಿಲ್ಲ. ಇವುಗಳನ್ನು ನೋಡಿ: {list}.',
    fb_invalid: 'ಚೌಕಗಳಲ್ಲಿ 1 ರಿಂದ 99 ರವರೆಗಿನ ಪೂರ್ಣ ಸಂಖ್ಯೆಗಳನ್ನು ಮಾತ್ರ ಬರೆಯಿರಿ.',
    fb_shown: 'ಇಲ್ಲಿದೆ ಉತ್ತರ. ಕೋಷ್ಟಕದಲ್ಲಿ ಪ್ರತಿ ಪರಮಾಣುವನ್ನು ಪರಿಶೀಲಿಸಿ, ನಂತರ ಮುಂದಿನ ಕ್ರಿಯೆಯನ್ನು ಮಾಡಿ.',
    hint_atoms: '{e} ಎಣಿಸಿ: ಎಡಬದಿಯಲ್ಲಿ {l}, ಬಲಬದಿಯಲ್ಲಿ {r}. {list} ಮುಂದಿನ ಸಂಖ್ಯೆಯನ್ನು ಬದಲಿಸಿ.',
    hint_reveal: '{f} ಮುಂದಿನ ಸಂಖ್ಯೆ {n}.',
    hint_done: 'ಎಲ್ಲ ಸಂಖ್ಯೆಗಳೂ ಸರಿಯಾಗಿವೆ. ಪರಿಶೀಲಿಸಿ ಒತ್ತಿ.',
    type_q: 'ಇದು ಯಾವ ಬಗೆಯ ಕ್ರಿಯೆ?',
    type_ok: 'ಸರಿ!',
    type_bad: 'ಸರಿಯಲ್ಲ. ಕೆಳಗೆ ಉತ್ತರ ನೋಡಿ.',
    type_label: 'ಬಗೆ',
    also: 'ಜೊತೆಗೆ',
    t_combination: 'ಸಂಯೋಗ',
    t_decomposition: 'ವಿಭಜನೆ',
    t_displacement: 'ಸ್ಥಾನಪಲ್ಲಟ',
    t_double: 'ದ್ವಿಸ್ಥಾನಪಲ್ಲಟ',
    t_combustion: 'ದಹನ',
    t_redox: 'ರೆಡಾಕ್ಸ್',
    x_combination: 'ಸಂಯೋಗ: ಎರಡು ಅಥವಾ ಹೆಚ್ಚು ವಸ್ತುಗಳು ಸೇರಿ ಒಂದೇ ಹೊಸ ವಸ್ತು ಉಂಟಾಗುತ್ತದೆ (A + B → AB).',
    x_decomposition: 'ವಿಭಜನೆ: ಒಂದು ವಸ್ತು ಶಾಖ, ಬೆಳಕು ಅಥವಾ ವಿದ್ಯುತ್‌ನಿಂದ ಒಡೆದು ಸರಳ ವಸ್ತುಗಳಾಗುತ್ತದೆ (AB → A + B).',
    x_displacement: 'ಸ್ಥಾನಪಲ್ಲಟ: ಹೆಚ್ಚು ಕ್ರಿಯಾಶೀಲ ಧಾತು ಕಡಿಮೆ ಕ್ರಿಯಾಶೀಲ ಧಾತುವನ್ನು ಅದರ ಸಂಯುಕ್ತದಿಂದ ಹೊರಹಾಕುತ್ತದೆ (A + BC → AC + B).',
    x_double: 'ದ್ವಿಸ್ಥಾನಪಲ್ಲಟ: ಎರಡು ಸಂಯುಕ್ತಗಳು ತಮ್ಮ ಅಯಾನುಗಳನ್ನು ಅದಲುಬದಲು ಮಾಡಿಕೊಳ್ಳುತ್ತವೆ, ಹಲವು ಬಾರಿ ಅವಕ್ಷೇಪ ಉಂಟಾಗುತ್ತದೆ (AB + CD → AD + CB).',
    x_combustion: 'ದಹನ: ವಸ್ತು ಆಮ್ಲಜನಕದಲ್ಲಿ ಉರಿದು ಶಾಖ ಮತ್ತು ಬೆಳಕು ನೀಡುತ್ತದೆ. ಮೀಥೇನ್, LPG ಯಂತಹ ಇಂಧನಗಳು ಕಾರ್ಬನ್ ಡೈಆಕ್ಸೈಡ್ ಮತ್ತು ನೀರನ್ನು ನೀಡುತ್ತವೆ.',
    x_redox: 'ರೆಡಾಕ್ಸ್: ಒಂದು ವಸ್ತು ಉತ್ಕರ್ಷಣಗೊಳ್ಳುತ್ತದೆ (ಆಮ್ಲಜನಕ ಸೇರುತ್ತದೆ ಅಥವಾ ಹೈಡ್ರೋಜನ್ ಹೋಗುತ್ತದೆ), ಇನ್ನೊಂದು ಅಪಕರ್ಷಣಗೊಳ್ಳುತ್ತದೆ (ಆಮ್ಲಜನಕ ಹೋಗುತ್ತದೆ ಅಥವಾ ಹೈಡ್ರೋಜನ್ ಸೇರುತ್ತದೆ).',
    cond_heat: 'ಶಾಖ',
    cond_sun: 'ಸೂರ್ಯನ ಬೆಳಕು',
    cond_elec: 'ವಿದ್ಯುತ್',
    states_note: '(s) ಘನ · (l) ದ್ರವ · (g) ಅನಿಲ · (aq) ನೀರಿನಲ್ಲಿ ಕರಗಿದ',
    print_ws: 'ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ',
    ws_title: 'ಈ ರಾಸಾಯನಿಕ ಸಮೀಕರಣಗಳನ್ನು ಸರಿದೂಗಿಸಿ',
    ws_name: 'ಹೆಸರು',
    ws_class: 'ತರಗತಿ',
    ws_date: 'ದಿನಾಂಕ',
    ws_instr: 'ಪ್ರತಿ ಖಾಲಿ ಜಾಗದಲ್ಲಿ ಅತಿ ಚಿಕ್ಕ ಪೂರ್ಣ ಸಂಖ್ಯೆ ಬರೆಯಿರಿ, ನಂತರ ಕ್ರಿಯೆಯ ಬಗೆಯನ್ನು ಬರೆಯಿರಿ.',
    ws_key: 'ಉತ್ತರ ಸೂಚಿ',
    reset_progress: 'ಪ್ರಗತಿಯನ್ನು ಮರುಹೊಂದಿಸಿ',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ / ತರಗತಿಗೆ ಉಪಾಯಗಳು',
    help_1: 'ಸರಿಯಾದ ದೊಡ್ಡ, ಸಣ್ಣ ಅಕ್ಷರಗಳೊಂದಿಗೆ ಸಮೀಕರಣ ಬರೆಯಿರಿ (Co ಎಂದರೆ ಕೋಬಾಲ್ಟ್, CO ಎಂದರೆ ಕಾರ್ಬನ್ ಮೊನಾಕ್ಸೈಡ್), ನಂತರ ಸರಿದೂಗಿಸಿ ಒತ್ತಿ. ಬಾಣಕ್ಕಾಗಿ →, -> ಅಥವಾ = ಬಳಸಬಹುದು.',
    help_2: 'ಆವರಣಗಳು ( ) ಮತ್ತು [ ], ಸ್ಫಟಿಕ ಜಲವಿರುವ ಲವಣಗಳು (CuSO4·5H2O ಅಥವಾ CuSO4.5H2O), ಸ್ಥಿತಿಗಳು (s), (l), (g), (aq) ಮತ್ತು ಅಯಾನುಗಳು (Fe^3+, SO4^2-, e-) ಕೂಡ ಅರ್ಥವಾಗುತ್ತವೆ.',
    help_3: '"ಹೇಗೆ ಬಿಡಿಸಲಾಯಿತು" ಓದಿ: ಆ್ಯಪ್ ಪ್ರತಿ ಧಾತುವಿಗೆ ಒಂದು ಸಮೀಕರಣ ಬರೆದು ಅವುಗಳನ್ನು ಬಿಡಿಸುತ್ತದೆ. ನಿಮ್ಮ NCERT ಪುಸ್ತಕದ ಪ್ರಯತ್ನ-ದೋಷ (ಹಿಟ್ ಅಂಡ್ ಟ್ರಯಲ್) ವಿಧಾನದೊಂದಿಗೆ ಹೋಲಿಸಿ.',
    help_4: 'ಸೂತ್ರಗಳ ಮುಂದೆ ನಿಮ್ಮದೇ ಸಂಖ್ಯೆಗಳನ್ನು ಬರೆಯಿರಿ (ಉದಾ. 2H2 + O2 -> 2H2O), ನಿಮ್ಮ ಉತ್ತರ ಸರಿಯೇ ಎಂದು ಆ್ಯಪ್ ಹೇಳುತ್ತದೆ.',
    help_5: 'ಅಭ್ಯಾಸದಲ್ಲಿ NCERT 10ನೇ ತರಗತಿಯ 15 ಕ್ರಿಯೆಗಳಿವೆ. ಚೌಕಗಳನ್ನು ತುಂಬಿ, ಪರಿಶೀಲಿಸಿ ಒತ್ತಿ, ಸಿಕ್ಕಿಹಾಕಿಕೊಂಡರೆ ಸುಳಿವು ಪಡೆಯಿರಿ, ಕ್ರಿಯೆಯ ಬಗೆಯನ್ನು ಹೇಳಿ.',
    help_6: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಪೂರ್ಣ ಪರದೆಯಲ್ಲಿ ಅಭ್ಯಾಸದ ಒಂದು ಕ್ರಿಯೆಯನ್ನು ತೋರಿಸಿ. ತಂಡಗಳು 2 ನಿಮಿಷಗಳಲ್ಲಿ ಕಾಗದದ ಮೇಲೆ ಸರಿದೂಗಿಸಲಿ, ನಂತರ ಒಂದು ತಂಡ ತನ್ನ ಹಂತಗಳನ್ನು ವಿವರಿಸಲಿ. ಮನೆಗೆಲಸಕ್ಕಾಗಿ ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ.'
  },
  ml: {
    app_title: 'രാസസമവാക്യ സമീകരണം',
    intro: 'ഏത് രാസസമവാക്യവും പടിപടിയായി സമീകരിക്കൂ, ഇരുവശത്തെയും ആറ്റങ്ങൾ എണ്ണൂ, NCERT പത്താം ക്ലാസിലെ 15 രാസപ്രവർത്തനങ്ങൾ പരിശീലിക്കൂ.',
    tab_balance: 'സമീകരിക്കുക',
    tab_practice: 'പരിശീലനം: NCERT 10',
    eq_label: 'ഒരു രാസസമവാക്യം ടൈപ്പ് ചെയ്യുക',
    eq_hint: 'ഇരുവശങ്ങൾക്കുമിടയിൽ → (അല്ലെങ്കിൽ -> അല്ലെങ്കിൽ =), പദാർഥങ്ങൾക്കിടയിൽ + ഇടുക. ബ്രാക്കറ്റുകൾ, CuSO4·5H2O പോലുള്ള ക്രിസ്റ്റൽ ജലമുള്ള ലവണങ്ങൾ, (aq) പോലുള്ള അവസ്ഥകൾ, Fe^3+ അല്ലെങ്കിൽ SO4^2- പോലുള്ള ചാർജുകൾ എന്നിവയും പ്രവർത്തിക്കും.',
    balance_btn: 'സമീകരിക്കുക',
    keys_aria: 'ചിഹ്നം ചേർക്കുക',
    try_these: 'ഈ ഉദാഹരണങ്ങൾ പരീക്ഷിക്കൂ',
    result_title: 'സമീകരിച്ച സമവാക്യം',
    status_ok: 'സമീകരിച്ചു ✓',
    status_many: 'ഒന്നിലധികം ഉത്തരങ്ങൾ',
    atoms_title: 'ഇരുവശത്തെയും ആറ്റങ്ങളുടെ എണ്ണം',
    col_element: 'മൂലകം',
    col_left: 'ഇടതുവശം (അഭികാരകങ്ങൾ)',
    col_right: 'വലതുവശം (ഉൽപ്പന്നങ്ങൾ)',
    col_ok: 'തുല്യമോ?',
    charge: 'ചാർജ്',
    law: 'മാസ് സംരക്ഷണ നിയമം: രാസപ്രവർത്തനത്തിൽ ആറ്റങ്ങൾ പുതിയ രീതിയിൽ ക്രമീകരിക്കപ്പെടുന്നു എന്നു മാത്രം. ഒരു ആറ്റവും ഉണ്ടാകുന്നില്ല, നശിക്കുന്നുമില്ല. അതിനാൽ ഓരോ മൂലകത്തിന്റെയും എണ്ണം ഇരുവശത്തും തുല്യമായിരിക്കണം.',
    steps_title: 'എങ്ങനെ നിർധാരണം ചെയ്തു (ബീജഗണിത രീതി)',
    s1_title: 'മൂലകങ്ങളുടെ പട്ടിക തയ്യാറാക്കുക',
    s1_text: 'സമവാക്യത്തിൽ ഈ മൂലകങ്ങളുണ്ട്:',
    s2_title: 'ഓരോ രാസസൂത്രത്തിനും മുന്നിൽ ഒരു അജ്ഞാത സംഖ്യ വയ്ക്കുക',
    s2_text: 'ഓരോ അക്ഷരവും നാം കണ്ടെത്തേണ്ട ഒരു ഗുണാങ്കമാണ്.',
    s3_title: 'ഓരോ മൂലകത്തിനും ഒരു സമവാക്യം എഴുതുക',
    s3_text: 'ഇടതുവശത്ത് ഒരു മൂലകത്തിന്റെ ആറ്റങ്ങൾ = വലതുവശത്ത് അതേ മൂലകത്തിന്റെ ആറ്റങ്ങൾ.',
    s3_charge: 'ആകെ ചാർജും ഇരുവശത്തും തുല്യമായിരിക്കണം.',
    s4_title: 'സമവാക്യങ്ങൾ നിർധാരണം ചെയ്യുക',
    s4_let: '{eq} എന്ന് എടുക്കാം ({f} ന്റെ മുന്നിലെ സംഖ്യ). അപ്പോൾ:',
    s4_together: 'ബാക്കിയുള്ള സമവാക്യങ്ങൾ ഒരുമിച്ച് നിർധാരണം ചെയ്താൽ:',
    s4_mult: 'ഏറ്റവും ചെറിയ പൂർണസംഖ്യകൾ കിട്ടാൻ ഓരോ സംഖ്യയെയും {m} കൊണ്ട് ഗുണിക്കുക:',
    s4_whole: 'ഇവ ഇതിനകം ഏറ്റവും ചെറിയ പൂർണസംഖ്യകളാണ്:',
    s5_title: 'പരിശോധിക്കുക',
    s5_text: 'ഈ സംഖ്യകൾ വച്ച് ഓരോ ആറ്റവും വീണ്ടും എണ്ണുക (പട്ടിക കാണുക). ഇരുവശവും ഒത്തുവരുന്നു, അതിനാൽ സമവാക്യം സമീകരിച്ചതാണ്.',
    many_text: 'ഈ സമവാക്യം ഒന്നിലധികം രീതിയിൽ സമീകരിക്കാം, കാരണം ഇതിൽ രണ്ടോ അതിലധികമോ വേറിട്ട രാസപ്രവർത്തനങ്ങൾ കലർന്നിരിക്കുന്നു. സാധ്യമായ ഒരു ഉത്തരം കാണിച്ചിരിക്കുന്നു. സൂത്രങ്ങൾ അധ്യാപകരോടൊപ്പം പരിശോധിക്കുക.',
    many_none: 'ഈ സമവാക്യം പല രീതിയിൽ സമീകരിക്കാം, അതിനാൽ ഒറ്റ ഉത്തരമില്ല. സൂത്രങ്ങൾ പരിശോധിക്കുക.',
    err_empty: 'ആദ്യം ഒരു സമവാക്യം എഴുതുക, ഉദാഹരണത്തിന്: Fe + H2O -> Fe3O4 + H2',
    err_arrow: 'അഭികാരകങ്ങൾക്കും ഉൽപ്പന്നങ്ങൾക്കുമിടയിൽ കൃത്യം ഒരു അമ്പടയാളം (→, -> അല്ലെങ്കിൽ =) ഇടുക.',
    err_side_empty: 'അമ്പടയാളത്തിന്റെ ഒരു വശം ശൂന്യമാണ്. ഇരുവശത്തും പദാർഥങ്ങൾ എഴുതുക.',
    err_plus: '+ ചിഹ്നത്തിനടുത്ത് എന്തോ വിട്ടുപോയിരിക്കുന്നു.',
    err_bad_char: 'സൂത്രത്തിൽ "{c}" എന്ന ചിഹ്നം ഉപയോഗിക്കാനാവില്ല. മൂലക പ്രതീകങ്ങൾ, അക്കങ്ങൾ, ബ്രാക്കറ്റുകൾ എന്നിവ ഉപയോഗിക്കുക.',
    err_element: '"{e}" ഒരു മൂലകത്തിന്റെയും പ്രതീകമല്ല. വലിയക്ഷരവും ചെറിയക്ഷരവും പരിശോധിക്കുക: Co കൊബാൾട്ട് ആണ്, എന്നാൽ CO കാർബൺ മോണോക്സൈഡ് ആണ്.',
    err_lower: 'മൂലക പ്രതീകങ്ങൾ വലിയക്ഷരത്തിൽ തുടങ്ങുന്നു (H, Fe, Cl). "{f}" പരിശോധിക്കുക.',
    err_bracket: '"{f}" ലെ ബ്രാക്കറ്റുകൾ ഒത്തുവരുന്നില്ല.',
    err_formula: '"{f}" എന്ന സൂത്രം വായിക്കാനായില്ല.',
    err_coef: 'സൂത്രത്തിനു മുന്നിലെ സംഖ്യ 1 അല്ലെങ്കിൽ അതിൽ കൂടുതലുള്ള പൂർണസംഖ്യ ആയിരിക്കണം.',
    err_too_many: 'പദാർഥങ്ങൾ വളരെ കൂടുതലാണ്. പരമാവധി {n} എഴുതുക.',
    err_only_side: '{e} അമ്പടയാളത്തിന്റെ ഒരു വശത്ത് മാത്രമേയുള്ളൂ, അതിനാൽ ഇത് ഒരിക്കലും സമീകരിക്കാനാവില്ല. സൂത്രങ്ങൾ പരിശോധിക്കുക.',
    err_impossible: 'ഈ സമവാക്യം സമീകരിക്കാനാവില്ല. ഏതെങ്കിലും സൂത്രം തെറ്റായിരിക്കാം, അല്ലെങ്കിൽ ഒരു അഭികാരകമോ ഉൽപ്പന്നമോ വിട്ടുപോയിരിക്കാം.',
    err_charge: 'ചാർജുകൾ തുല്യമാക്കാനാവില്ല. ചാർജുകൾ പരിശോധിക്കുക, അല്ലെങ്കിൽ അർധപ്രവർത്തനത്തിന് ഇലക്ട്രോണുകൾ (e-) ചേർക്കുക.',
    err_zero: 'സമീകരിക്കാനാവില്ല: {f} ന് സംഖ്യ 0 കിട്ടും, അതായത് അത് പ്രവർത്തനത്തിൽ പങ്കെടുക്കുന്നില്ല. അത് നീക്കുക അല്ലെങ്കിൽ സൂത്രങ്ങൾ പരിശോധിക്കുക.',
    err_side: 'പോസിറ്റീവ് സംഖ്യകൾ കൊണ്ട് സമീകരിക്കാനാവില്ല: {f} അമ്പടയാളത്തിന്റെ മറുവശത്ത് ആയിരിക്കണം.',
    yours_label: 'നിങ്ങൾ എഴുതിയത്:',
    yours_ok: 'നിങ്ങളുടെ സംഖ്യകൾ ശരിയാണ്. സമവാക്യം സമീകരിച്ചതാണ്.',
    yours_multiple: 'നിങ്ങളുടെ സംഖ്യകൾ കൊണ്ട് സമവാക്യം സമീകരിക്കുന്നു, പക്ഷേ അവ ഏറ്റവും ചെറുതല്ല. എല്ലാറ്റിനെയും {k} കൊണ്ട് ഹരിക്കുക.',
    yours_bad: 'നിങ്ങളുടെ സംഖ്യകൾ കൊണ്ട് സമവാക്യം ഇതുവരെ സമീകരിച്ചിട്ടില്ല. തുല്യമല്ലാത്തവ: {list}. ശരിയായ ഉത്തരം മുകളിൽ കാണിച്ചിരിക്കുന്നു.',
    pr_pick: 'ഒരു രാസപ്രവർത്തനം തിരഞ്ഞെടുക്കുക',
    pr_num: 'പ്രവർത്തനം {n} / {total}',
    pr_solved: 'ചെയ്തവ: {total} ൽ {n}',
    pr_enter: 'കള്ളികളിൽ ഏറ്റവും ചെറിയ പൂർണസംഖ്യകൾ എഴുതുക. ഒഴിഞ്ഞ കള്ളി എന്നാൽ 1.',
    pr_done: 'ചെയ്തു',
    pr_shown: 'ഉത്തരം കണ്ടു',
    coef_aria: '{f} ന്റെ മുന്നിലെ സംഖ്യ',
    check: 'പരിശോധിക്കുക',
    hint: 'സൂചന',
    show_answer: 'ഉത്തരം കാണിക്കുക',
    fb_ok: 'ശരി! സമവാക്യം ഏറ്റവും ചെറിയ പൂർണസംഖ്യകൾ കൊണ്ട് സമീകരിച്ചു.',
    fb_ok_seen: 'ശരി! പക്ഷേ നിങ്ങൾ ഇതിന്റെ ഉത്തരം കണ്ടിരുന്നു, അതിനാൽ ഇത് ചെയ്തതായി കണക്കാക്കിയിട്ടില്ല.',
    fb_multiple: 'സമീകരിച്ചു, പക്ഷേ ഇവ ഏറ്റവും ചെറിയ സംഖ്യകളല്ല. എല്ലാറ്റിനെയും {k} കൊണ്ട് ഹരിക്കുക.',
    fb_bad: 'ഇതുവരെ സമീകരിച്ചിട്ടില്ല. ഇവ നോക്കുക: {list}.',
    fb_invalid: 'കള്ളികളിൽ 1 മുതൽ 99 വരെയുള്ള പൂർണസംഖ്യകൾ മാത്രം എഴുതുക.',
    fb_shown: 'ഇതാ ഉത്തരം. പട്ടികയിൽ ഓരോ ആറ്റവും പരിശോധിക്കുക, എന്നിട്ട് അടുത്ത പ്രവർത്തനം ചെയ്യുക.',
    hint_atoms: '{e} എണ്ണുക: ഇടതുവശത്ത് {l}, വലതുവശത്ത് {r}. {list} ന്റെ മുന്നിലെ സംഖ്യ മാറ്റുക.',
    hint_reveal: '{f} ന്റെ മുന്നിലെ സംഖ്യ {n} ആണ്.',
    hint_done: 'എല്ലാ സംഖ്യകളും ശരിയാണ്. പരിശോധിക്കുക അമർത്തുക.',
    type_q: 'ഇത് ഏതുതരം രാസപ്രവർത്തനമാണ്?',
    type_ok: 'ശരി!',
    type_bad: 'ശരിയല്ല. താഴെ ഉത്തരം കാണുക.',
    type_label: 'തരം',
    also: 'കൂടാതെ',
    t_combination: 'സംയോജനം',
    t_decomposition: 'വിഘടനം',
    t_displacement: 'ആദേശം',
    t_double: 'ദ്വിആദേശം',
    t_combustion: 'ജ്വലനം',
    t_redox: 'റെഡോക്സ്',
    x_combination: 'സംയോജനം: രണ്ടോ അതിലധികമോ പദാർഥങ്ങൾ ചേർന്ന് ഒരു പുതിയ പദാർഥം ഉണ്ടാകുന്നു (A + B → AB).',
    x_decomposition: 'വിഘടനം: ഒരു പദാർഥം താപം, പ്രകാശം അല്ലെങ്കിൽ വൈദ്യുതി കൊണ്ട് വിഘടിച്ച് ലളിതമായ പദാർഥങ്ങളാകുന്നു (AB → A + B).',
    x_displacement: 'ആദേശം: കൂടുതൽ ക്രിയാശീലമുള്ള മൂലകം കുറഞ്ഞ ക്രിയാശീലമുള്ള മൂലകത്തെ അതിന്റെ സംയുക്തത്തിൽ നിന്ന് പുറത്താക്കുന്നു (A + BC → AC + B).',
    x_double: 'ദ്വിആദേശം: രണ്ട് സംയുക്തങ്ങൾ അവയുടെ അയോണുകൾ പരസ്പരം കൈമാറുന്നു, പലപ്പോഴും അവക്ഷിപ്തം ഉണ്ടാകുന്നു (AB + CD → AD + CB).',
    x_combustion: 'ജ്വലനം: ഒരു പദാർഥം ഓക്സിജനിൽ കത്തി താപവും പ്രകാശവും നൽകുന്നു. മീഥെയ്ൻ, LPG പോലുള്ള ഇന്ധനങ്ങൾ കാർബൺ ഡൈ ഓക്സൈഡും ജലവും നൽകുന്നു.',
    x_redox: 'റെഡോക്സ്: ഒരു പദാർഥം ഓക്സീകരിക്കപ്പെടുന്നു (ഓക്സിജൻ ചേരുന്നു അല്ലെങ്കിൽ ഹൈഡ്രജൻ നഷ്ടപ്പെടുന്നു), മറ്റൊന്ന് നിരോക്സീകരിക്കപ്പെടുന്നു (ഓക്സിജൻ നഷ്ടപ്പെടുന്നു അല്ലെങ്കിൽ ഹൈഡ്രജൻ ചേരുന്നു).',
    cond_heat: 'താപം',
    cond_sun: 'സൂര്യപ്രകാശം',
    cond_elec: 'വൈദ്യുതി',
    states_note: '(s) ഖരം · (l) ദ്രാവകം · (g) വാതകം · (aq) ജലത്തിൽ ലയിച്ചത്',
    print_ws: 'വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യുക',
    ws_title: 'ഈ രാസസമവാക്യങ്ങൾ സമീകരിക്കുക',
    ws_name: 'പേര്',
    ws_class: 'ക്ലാസ്',
    ws_date: 'തീയതി',
    ws_instr: 'ഓരോ ഒഴിഞ്ഞ സ്ഥലത്തും ഏറ്റവും ചെറിയ പൂർണസംഖ്യ എഴുതുക, എന്നിട്ട് പ്രവർത്തനത്തിന്റെ തരം എഴുതുക.',
    ws_key: 'ഉത്തരസൂചിക',
    reset_progress: 'പുരോഗതി റീസെറ്റ് ചെയ്യുക',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ക്ലാസ് മുറിക്കുള്ള ആശയങ്ങൾ',
    help_1: 'ശരിയായ വലിയക്ഷരവും ചെറിയക്ഷരവും ഉപയോഗിച്ച് സമവാക്യം എഴുതുക (Co കൊബാൾട്ട്, CO കാർബൺ മോണോക്സൈഡ്), എന്നിട്ട് സമീകരിക്കുക അമർത്തുക. അമ്പടയാളത്തിന് →, -> അല്ലെങ്കിൽ = ഉപയോഗിക്കാം.',
    help_2: 'ബ്രാക്കറ്റുകൾ ( ), [ ], ക്രിസ്റ്റൽ ജലമുള്ള ലവണങ്ങൾ (CuSO4·5H2O അല്ലെങ്കിൽ CuSO4.5H2O), അവസ്ഥകൾ (s), (l), (g), (aq), അയോണുകൾ (Fe^3+, SO4^2-, e-) എന്നിവയും മനസ്സിലാക്കും.',
    help_3: '"എങ്ങനെ നിർധാരണം ചെയ്തു" വായിക്കുക: ആപ്പ് ഓരോ മൂലകത്തിനും ഒരു സമവാക്യം എഴുതി അവ നിർധാരണം ചെയ്യുന്നു. നിങ്ങളുടെ NCERT പുസ്തകത്തിലെ ശ്രമ-പിഴവ് (ഹിറ്റ് ആൻഡ് ട്രയൽ) രീതിയുമായി താരതമ്യം ചെയ്യുക.',
    help_4: 'സൂത്രങ്ങൾക്കു മുന്നിൽ നിങ്ങളുടെ സ്വന്തം സംഖ്യകൾ എഴുതുക (ഉദാ. 2H2 + O2 -> 2H2O), നിങ്ങളുടെ ഉത്തരം ശരിയാണോ എന്ന് ആപ്പ് പറയും.',
    help_5: 'പരിശീലനത്തിൽ NCERT പത്താം ക്ലാസിലെ 15 രാസപ്രവർത്തനങ്ങളുണ്ട്. കള്ളികൾ പൂരിപ്പിക്കുക, പരിശോധിക്കുക അമർത്തുക, കുടുങ്ങിയാൽ സൂചന എടുക്കുക, പ്രവർത്തനത്തിന്റെ തരം പറയുക.',
    help_6: 'ക്ലാസ് പ്രവർത്തനം: സ്മാർട്ട്ബോർഡിൽ ഫുൾ സ്ക്രീനിൽ പരിശീലനത്തിലെ ഒരു പ്രവർത്തനം കാണിക്കുക. ടീമുകൾ 2 മിനിറ്റിനുള്ളിൽ കടലാസിൽ അത് സമീകരിക്കട്ടെ, എന്നിട്ട് ഒരു ടീം അവരുടെ ഘട്ടങ്ങൾ വിശദീകരിക്കട്ടെ. ഗൃഹപാഠത്തിനായി വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യുക.'
  },
  ur: {
    app_title: 'کیمیائی مساوات کا توازن',
    intro: 'کسی بھی کیمیائی مساوات کو قدم بہ قدم متوازن کریں، دونوں طرف کے ایٹم گنیں اور NCERT جماعت 10 کے 15 تعاملات کی مشق کریں۔',
    tab_balance: 'متوازن کریں',
    tab_practice: 'مشق: NCERT جماعت 10',
    eq_label: 'کیمیائی مساوات لکھیں',
    eq_hint: 'دونوں طرف کے بیچ → (یا ⁦->⁩ یا =) اور مادّوں کے بیچ + لگائیں۔ قوسین، ⁦CuSO4·5H2O⁩ جیسے آبیدہ نمک، (aq) جیسی حالتیں اور ⁦Fe^3+⁩ یا ⁦SO4^2-⁩ جیسے چارج بھی چلتے ہیں۔',
    balance_btn: 'متوازن کریں',
    keys_aria: 'علامت ڈالیں',
    try_these: 'یہ مثالیں آزمائیں',
    result_title: 'متوازن مساوات',
    status_ok: 'متوازن ✓',
    status_many: 'ایک سے زیادہ جواب',
    atoms_title: 'دونوں طرف ایٹموں کی گنتی',
    col_element: 'عنصر',
    col_left: 'بایاں رخ (متعاملات)',
    col_right: 'دایاں رخ (حاصلات)',
    col_ok: 'برابر؟',
    charge: 'چارج',
    law: 'بقائے کمیت کا قانون: کیمیائی تعامل میں ایٹم صرف نئے ڈھنگ سے جڑتے ہیں۔ نہ کوئی ایٹم بنتا ہے نہ فنا ہوتا ہے، اس لیے ہر عنصر کی گنتی دونوں طرف برابر ہونی چاہیے۔',
    steps_title: 'حل کیسے ہوا (الجبرا کا طریقہ)',
    s1_title: 'عناصر کی فہرست بنائیں',
    s1_text: 'مساوات میں یہ عناصر ہیں:',
    s2_title: 'ہر فارمولے کے آگے ایک نامعلوم عدد رکھیں',
    s2_text: 'ہر حرف ایک ضریب ہے جو ہمیں معلوم کرنا ہے۔',
    s3_title: 'ہر عنصر کے لیے ایک مساوات لکھیں',
    s3_text: 'بائیں طرف کسی عنصر کے ایٹم = دائیں طرف اسی عنصر کے ایٹم۔',
    s3_charge: 'کل چارج بھی دونوں طرف برابر ہونا چاہیے۔',
    s4_title: 'مساواتیں حل کریں',
    s4_let: 'فرض کریں {eq} ({f} کے آگے کا عدد)۔ تب:',
    s4_together: 'باقی مساواتوں کو ایک ساتھ حل کرنے پر:',
    s4_mult: 'سب سے چھوٹے مکمل اعداد پانے کے لیے ہر عدد کو {m} سے ضرب دیں:',
    s4_whole: 'یہ پہلے سے سب سے چھوٹے مکمل اعداد ہیں:',
    s5_title: 'جانچ کریں',
    s5_text: 'ان اعداد کے ساتھ ہر ایٹم پھر سے گنیں (جدول دیکھیں)۔ دونوں طرف برابر ہیں، اس لیے مساوات متوازن ہے۔',
    many_text: 'یہ مساوات ایک سے زیادہ طریقوں سے متوازن ہو سکتی ہے، کیونکہ اس میں دو یا زیادہ الگ الگ تعاملات ملے ہوئے ہیں۔ ایک ممکنہ جواب دکھایا گیا ہے۔ فارمولے اپنے استاد سے جانچ لیں۔',
    many_none: 'یہ مساوات کئی طریقوں سے متوازن ہو سکتی ہے، اس لیے کوئی ایک جواب نہیں ہے۔ فارمولے جانچیں۔',
    err_empty: 'پہلے کوئی مساوات لکھیں، مثلاً: ⁦Fe + H2O -> Fe3O4 + H2⁩',
    err_arrow: 'متعاملات اور حاصلات کے بیچ ٹھیک ایک تیر (→، ⁦->⁩ یا =) لگائیں۔',
    err_side_empty: 'تیر کی ایک طرف خالی ہے۔ دونوں طرف مادّے لکھیں۔',
    err_plus: '+ علامت کے پاس کچھ چھوٹ گیا ہے۔',
    err_bad_char: 'فارمولے میں "{c}" علامت استعمال نہیں ہو سکتی۔ عناصر کی علامتیں، ہندسے اور قوسین استعمال کریں۔',
    err_element: '"{e}" کسی عنصر کی علامت نہیں ہے۔ بڑے اور چھوٹے حروف جانچیں: Co کوبالٹ ہے، لیکن CO کاربن مونو آکسائیڈ ہے۔',
    err_lower: 'عناصر کی علامتیں بڑے حرف سے شروع ہوتی ہیں (H، Fe، Cl)۔ "{f}" جانچیں۔',
    err_bracket: '"{f}" میں قوسین ٹھیک سے بند نہیں ہیں۔',
    err_formula: 'فارمولا "{f}" پڑھا نہیں جا سکا۔',
    err_coef: 'فارمولے کے آگے کا عدد 1 یا اس سے بڑا مکمل عدد ہونا چاہیے۔',
    err_too_many: 'بہت زیادہ مادّے ہیں۔ زیادہ سے زیادہ {n} لکھیں۔',
    err_only_side: '{e} تیر کی صرف ایک طرف ہے، اس لیے یہ کبھی متوازن نہیں ہو سکتی۔ فارمولے جانچیں۔',
    err_impossible: 'یہ مساوات متوازن نہیں ہو سکتی۔ کوئی فارمولا غلط ہو سکتا ہے، یا کوئی متعامل یا حاصل چھوٹ گیا ہے۔',
    err_charge: 'چارج برابر نہیں ہو سکتے۔ چارج جانچیں، یا نصف تعامل کے لیے الیکٹران ⁦(e-)⁩ جوڑیں۔',
    err_zero: 'توازن ممکن نہیں: {f} کو عدد 0 ملے گا، یعنی وہ تعامل میں حصہ نہیں لیتا۔ اسے ہٹائیں یا فارمولے جانچیں۔',
    err_side: 'مثبت اعداد سے توازن ممکن نہیں: {f} کو تیر کی دوسری طرف ہونا چاہیے۔',
    yours_label: 'آپ نے لکھا:',
    yours_ok: 'آپ کے اعداد درست ہیں۔ مساوات متوازن ہے۔',
    yours_multiple: 'آپ کے اعداد سے مساوات متوازن ہے، لیکن یہ سب سے چھوٹے نہیں ہیں۔ سب کو {k} سے تقسیم کریں۔',
    yours_bad: 'آپ کے اعداد سے مساوات ابھی متوازن نہیں۔ برابر نہیں: {list}۔ درست جواب اوپر دکھایا گیا ہے۔',
    pr_pick: 'تعامل چنیں',
    pr_num: 'تعامل {n} / {total}',
    pr_solved: 'حل کیے: {total} میں سے {n}',
    pr_enter: 'خانوں میں سب سے چھوٹے مکمل اعداد لکھیں۔ خالی خانے کا مطلب 1 ہے۔',
    pr_done: 'حل ہو گیا',
    pr_shown: 'جواب دیکھا',
    coef_aria: '{f} کے آگے کا عدد',
    check: 'جانچیں',
    hint: 'اشارہ',
    show_answer: 'جواب دکھائیں',
    fb_ok: 'درست! مساوات سب سے چھوٹے مکمل اعداد سے متوازن ہے۔',
    fb_ok_seen: 'درست! لیکن آپ نے اس کا جواب دیکھ لیا تھا، اس لیے اسے حل شدہ نہیں گنا گیا۔',
    fb_multiple: 'متوازن تو ہے، لیکن یہ سب سے چھوٹے اعداد نہیں ہیں۔ سب کو {k} سے تقسیم کریں۔',
    fb_bad: 'ابھی متوازن نہیں۔ انہیں دیکھیں: {list}۔',
    fb_invalid: 'خانوں میں 1 سے 99 تک کے مکمل اعداد ہی لکھیں۔',
    fb_shown: 'یہ رہا جواب۔ جدول میں ہر ایٹم جانچیں، پھر اگلا تعامل کریں۔',
    hint_atoms: '{e} گنیں: بائیں طرف {l} اور دائیں طرف {r}۔ {list} کے آگے کا عدد بدلیں۔',
    hint_reveal: '{f} کے آگے کا عدد {n} ہے۔',
    hint_done: 'سب اعداد درست ہیں۔ جانچیں دبائیں۔',
    type_q: 'یہ کس قسم کا تعامل ہے؟',
    type_ok: 'درست!',
    type_bad: 'ٹھیک نہیں۔ نیچے جواب دیکھیں۔',
    type_label: 'قسم',
    also: 'نیز',
    t_combination: 'امتزاج',
    t_decomposition: 'تجزیہ',
    t_displacement: 'ہٹاؤ',
    t_double: 'دوہرا ہٹاؤ',
    t_combustion: 'احتراق',
    t_redox: 'ریڈاکس',
    x_combination: 'امتزاج: دو یا زیادہ مادّے مل کر ایک نیا مادّہ بناتے ہیں (A + B → AB)۔',
    x_decomposition: 'تجزیہ: ایک مادّہ حرارت، روشنی یا بجلی سے ٹوٹ کر سادہ مادّے بناتا ہے (AB → A + B)۔',
    x_displacement: 'ہٹاؤ: زیادہ فعال عنصر کم فعال عنصر کو اس کے مرکب سے باہر نکال دیتا ہے (A + BC → AC + B)۔',
    x_double: 'دوہرا ہٹاؤ: دو مرکبات اپنے آئنوں کا تبادلہ کرتے ہیں، اور اکثر رسوب بنتا ہے (AB + CD → AD + CB)۔',
    x_combustion: 'احتراق: مادّہ آکسیجن میں جل کر حرارت اور روشنی دیتا ہے۔ میتھین اور LPG جیسے ایندھن کاربن ڈائی آکسائیڈ اور پانی دیتے ہیں۔',
    x_redox: 'ریڈاکس: ایک مادّے کی تکسید ہوتی ہے (آکسیجن جڑتی ہے یا ہائیڈروجن ہٹتی ہے) اور دوسرے کی تخفیف ہوتی ہے (آکسیجن ہٹتی ہے یا ہائیڈروجن جڑتی ہے)۔',
    cond_heat: 'حرارت',
    cond_sun: 'دھوپ',
    cond_elec: 'بجلی',
    states_note: '(s) ٹھوس · (l) مائع · (g) گیس · (aq) پانی میں حل شدہ',
    print_ws: 'ورک شیٹ پرنٹ کریں',
    ws_title: 'ان کیمیائی مساواتوں کو متوازن کریں',
    ws_name: 'نام',
    ws_class: 'جماعت',
    ws_date: 'تاریخ',
    ws_instr: 'ہر خالی جگہ میں سب سے چھوٹا مکمل عدد لکھیں، پھر تعامل کی قسم لکھیں۔',
    ws_key: 'جوابات',
    reset_progress: 'پیش رفت ری سیٹ کریں',
    help_title: 'استعمال کا طریقہ / کلاس کے لیے مشورے',
    help_1: 'صحیح بڑے اور چھوٹے حروف کے ساتھ مساوات لکھیں (Co کوبالٹ ہے، CO کاربن مونو آکسائیڈ) اور متوازن کریں دبائیں۔ تیر کے لیے →، ⁦->⁩ یا = لکھ سکتے ہیں۔',
    help_2: 'قوسین ( ) اور [ ]، آبیدہ نمک (⁦CuSO4·5H2O⁩ یا ⁦CuSO4.5H2O⁩)، حالتیں (s)، (l)، (g)، (aq) اور آئن (⁦Fe^3+⁩، ⁦SO4^2-⁩، ⁦e-⁩) بھی سمجھے جاتے ہیں۔',
    help_3: '"حل کیسے ہوا" پڑھیں: ایپ ہر عنصر کے لیے ایک مساوات لکھ کر انہیں حل کرتی ہے۔ اس کا موازنہ اپنی NCERT کتاب کے ہٹ اینڈ ٹرائل (آزمائش اور غلطی) طریقے سے کریں۔',
    help_4: 'فارمولوں کے آگے اپنے اعداد لکھیں (مثلاً ⁦2H2 + O2 -> 2H2O⁩)، ایپ بتائے گی کہ آپ کا جواب درست ہے یا نہیں۔',
    help_5: 'مشق میں NCERT جماعت 10 کے 15 تعاملات ہیں۔ خانے بھریں، جانچیں دبائیں، اٹکنے پر اشارہ لیں اور تعامل کی قسم بتائیں۔',
    help_6: 'کلاس کی سرگرمی: اسمارٹ بورڈ پر فل اسکرین میں مشق کا ایک تعامل دکھائیں۔ ٹیمیں 2 منٹ میں کاغذ پر اسے متوازن کریں، پھر ایک ٹیم اپنے مراحل سمجھائے۔ ہوم ورک کے لیے ورک شیٹ پرنٹ کریں۔'
  }
};
