/* UI strings for Excel to Contacts (VCF). Keys must be identical in all 12 languages.
   Shared words (clear, copy, copied, download, reset ...) come from EDU.COMMON. Tech words (Excel, VCF, CSV, WhatsApp) stay in Latin script. */
window.APP_STRINGS = window.APP_STRINGS || {};
window.APP_STRINGS.en = {
  app_title: 'Excel to Contacts (VCF)',
  intro: 'Paste a customer list from Excel or Google Sheets, clean up the mobile numbers and download a VCF file that imports straight into any phone, or a Google Contacts CSV. It also turns a VCF back into a CSV for Excel.',
  privacy: 'Your customer list never leaves this device: nothing is uploaded. Under India’s DPDP Act 2023 you are responsible for protecting your customers’ personal data, so share these files only with people who need them and delete them when the work is done.',
  h_input: '1. Paste or open your list',
  paste_label: 'Paste here from Excel, Google Sheets or any CSV (one person per line)',
  paste_ph: 'Name    Mobile    Email    Company    Group\nRamesh Kumar    98765 43210    ramesh@example.com    Kumar Kirana    Customers',
  open_csv: 'Open CSV / TXT file', open_vcf: 'Open VCF file', load_example: 'Load example',
  example_note: 'This is example data with made-up numbers. Paste your own list to replace it.',
  excel_tip: 'Tip: in Excel or Google Sheets, select the columns with their heading row, copy, and paste here. If a number shows as 9.87654E+09, format that column as Text first and copy again.',
  lines_read: '{n} lines read', vcf_read: '{n} contacts read from the VCF file and placed in the list.', dl_vcf_csv: 'Download them as CSV',
  bad_file: 'Could not read this file. Use a .csv, .txt or .vcf file.', empty_list: 'Paste your list above to begin.',
  h_map: '2. Which column is what?', map_hint: 'Guessed from your data. Change a box if the guess is wrong.', has_header: 'The first line is a heading row',
  col_name: 'Name', col_last: 'Last name (optional)', col_phone: 'Mobile / phone', col_phone2: 'Second phone (optional)', col_email: 'Email', col_company: 'Company / shop', col_label: 'Group / label', col_note: 'Note',
  none_opt: '— none —', col_n: 'Column {n}',
  h_clean: '3. Clean-up options', cc_label: 'Country code for numbers that have none', cc_hint: 'India 91 · UAE 971 · Nepal 977 · Bangladesh 880 · Sri Lanka 94',
  opt_title: 'Fix capital letters in names (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'Merge duplicate numbers into one contact',
  opt_landline: 'Keep landline numbers (marked ⚠)', opt_intl: 'Keep foreign numbers (marked 🌐)',
  prefix_label: 'Add before every name', prefix_ph: 'e.g. Cust -', suffix_label: 'Add after every name', suffix_ph: 'e.g. (Diwali 2026)',
  prefix_hint: 'A prefix like “Cust -” keeps these contacts together in your phone and makes picking them for a WhatsApp broadcast list easy.',
  h_result: '4. Check the result',
  stat_rows: 'Lines', stat_contacts: 'Contacts ready', stat_invalid: 'Invalid numbers', stat_dups: 'Duplicates merged', stat_landline: 'Landlines', stat_noname: 'Without a name',
  filter_label: 'Show', filter_all: 'All', filter_ok: 'Ready', filter_warn: 'Flagged', filter_bad: 'Invalid',
  th_line: 'Line', th_name: 'Name', th_phone: 'Number(s)', th_email: 'Email', th_company: 'Company', th_label: 'Group', th_status: 'Status', th_note: 'Note', th_title: 'Designation', th_address: 'Address', th_bday: 'Birthday', csv_phone: 'Phone {n}',
  st_ok: 'Ready', st_landline: 'Landline', st_intl: 'Foreign number', st_merged: '{n} lines merged', st_noname: 'No name, so the number is used as the name', st_dropped: '{n} invalid number(s) left out',
  st_landline_off: 'Landline (left out by your settings)', st_intl_off: 'Foreign number (left out by your settings)',
  bad_sci: 'Excel shortened this number (9.87654E+09). Format the column as Text and copy again.', bad_len: 'Wrong length: {n} digits instead of 10', bad_text: 'This is not a phone number', bad_empty: 'No number',
  show_more: 'Show {n} more', showing: 'Showing {a} of {b}', no_rows_filter: 'Nothing to show in this filter.', processing: 'Cleaning {n} lines…',
  h_export: '5. Download', file_label: 'File name',
  dl_vcf: 'Download VCF (all contacts)', dl_csv: 'Cleaned CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'Copy all numbers',
  split_label: 'Split into files of', split_hint: 'A WhatsApp broadcast list can have at most 256 people (checked Oct 2026), so files of 256 give one list per file.',
  dl_parts_zip: 'Download all parts (ZIP)', part_n: 'Part {n}: contacts {a}–{b}', parts_summary: '{n} files of up to {m} contacts',
  preview_title: 'Preview of the VCF file (first 3 contacts)', nothing_to_export: 'No contacts to download yet.', done_dl: 'Downloaded {name}', note_also: 'Also written as: {names}',
  import_tip: 'On a phone: send the .vcf file to yourself on WhatsApp or email, open it and choose “Import contacts”. On a computer: contacts.google.com → Import → choose the CSV.',
  help_title: 'How to use & ideas',
  help_1: 'Excel or Google Sheets: select the Name and Mobile columns together with their heading row, copy, and paste in box 1. The columns line up by themselves.',
  help_2: 'Numbers written as 098765-43210, +91 98765 43210 or 9876543210 all become +919876543210. Two numbers in one cell (98765 43210 / 91234 56789) become two numbers of the same contact.',
  help_3: 'WhatsApp broadcast: add a prefix like “Diwali -”, download the VCF in parts of 256, import on the phone, then make a broadcast list and pick everyone starting with “Diwali -”.',
  help_4: 'Google Contacts: download the Google Contacts CSV and import it at contacts.google.com. The group name becomes a label there.',
  help_5: 'VCF to Excel: open a .vcf exported from a phone, then download the cleaned CSV and open it in Excel. Numbers stay as text with +91, so Excel will not shorten them.',
  help_6: 'Ask first: under the DPDP Act 2023 and TRAI rules, send promotions only to customers who agreed, and remove anyone who asks you to stop.',
  aria_table: 'Cleaned contact list',
  sample_tsv: 'Name\tMobile\tEmail\tCompany\tGroup\nRamesh Kumar\t098765-43210\tramesh@example.com\tKumar Kirana Store\tCustomers\npriya sharma\t+91 91234 56789\tpriya@example.com\tSharma Tuition Classes\tCustomers\nRamesh Kumar\t9876543210\t\t\tCustomers\nAnil Mehta\t9.87654E+09\t\tMehta Traders\tSuppliers\nFatima Khan\t98989 89898 / 97979 79797\tfatima@example.com\tKhan Boutique\tCustomers\nRajesh Office\t011-23456789\t\tRajesh and Sons\tSuppliers\nSunita Devi\t12345\t\tDevi Dairy\tCustomers'
};
window.APP_STRINGS.hi = {
  app_title: 'Excel से कॉन्टैक्ट (VCF)',
  intro: 'Excel या Google Sheets से ग्राहक सूची पेस्ट करें, मोबाइल नंबर साफ़ करें और ऐसी VCF फ़ाइल डाउनलोड करें जो किसी भी फ़ोन में सीधे इम्पोर्ट हो जाए, या Google Contacts CSV बनाएँ। VCF को वापस Excel के लिए CSV भी बना सकते हैं।',
  privacy: 'आपकी ग्राहक सूची इस डिवाइस से बाहर नहीं जाती: कुछ भी अपलोड नहीं होता। भारत के DPDP Act 2023 के तहत ग्राहकों का निजी डेटा सुरक्षित रखना आपकी ज़िम्मेदारी है, इसलिए ये फ़ाइलें सिर्फ़ ज़रूरी लोगों से साझा करें और काम पूरा होने पर हटा दें।',
  h_input: '1. अपनी सूची पेस्ट करें या खोलें',
  paste_label: 'यहाँ Excel, Google Sheets या किसी CSV से पेस्ट करें (एक लाइन में एक व्यक्ति)',
  paste_ph: 'नाम    मोबाइल    ईमेल    कंपनी    ग्रुप\nरमेश कुमार    98765 43210    ramesh@example.com    कुमार किराना    ग्राहक',
  open_csv: 'CSV / TXT फ़ाइल खोलें', open_vcf: 'VCF फ़ाइल खोलें', load_example: 'उदाहरण भरें',
  example_note: 'यह काल्पनिक नंबरों वाला उदाहरण है। इसकी जगह अपनी सूची पेस्ट करें।',
  excel_tip: 'सुझाव: Excel या Google Sheets में हेडिंग वाली लाइन समेत कॉलम चुनें, कॉपी करें और यहाँ पेस्ट करें। अगर नंबर 9.87654E+09 जैसा दिखे, तो पहले उस कॉलम को Text फ़ॉर्मेट करें और फिर कॉपी करें।',
  lines_read: '{n} लाइनें पढ़ी गईं', vcf_read: 'VCF फ़ाइल से {n} कॉन्टैक्ट पढ़कर सूची में रख दिए गए।', dl_vcf_csv: 'इन्हें CSV में डाउनलोड करें',
  bad_file: 'यह फ़ाइल पढ़ी नहीं जा सकी। .csv, .txt या .vcf फ़ाइल चुनें।', empty_list: 'शुरू करने के लिए ऊपर अपनी सूची पेस्ट करें।',
  h_map: '2. कौन-सा कॉलम क्या है?', map_hint: 'आपके डेटा से अनुमान लगाया है। गलत हो तो बॉक्स बदल दें।', has_header: 'पहली लाइन हेडिंग है',
  col_name: 'नाम', col_last: 'उपनाम (वैकल्पिक)', col_phone: 'मोबाइल / फ़ोन', col_phone2: 'दूसरा फ़ोन (वैकल्पिक)', col_email: 'ईमेल', col_company: 'कंपनी / दुकान', col_label: 'ग्रुप / लेबल', col_note: 'नोट',
  none_opt: '— कोई नहीं —', col_n: 'कॉलम {n}',
  h_clean: '3. सफ़ाई के विकल्प', cc_label: 'जिन नंबरों में देश कोड नहीं है, उनके लिए कोड', cc_hint: 'भारत 91 · UAE 971 · नेपाल 977 · बांग्लादेश 880 · श्रीलंका 94',
  opt_title: 'नामों के बड़े-छोटे अक्षर ठीक करें (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'एक ही नंबर की डुप्लीकेट लाइनें एक कॉन्टैक्ट में मिलाएँ',
  opt_landline: 'लैंडलाइन नंबर रखें (⚠ चिह्न के साथ)', opt_intl: 'विदेशी नंबर रखें (🌐 चिह्न के साथ)',
  prefix_label: 'हर नाम के आगे जोड़ें', prefix_ph: 'जैसे Cust -', suffix_label: 'हर नाम के बाद जोड़ें', suffix_ph: 'जैसे (दीवाली 2026)',
  prefix_hint: '“Cust -” जैसा उपसर्ग इन सब कॉन्टैक्ट को फ़ोन में एक साथ रखता है और WhatsApp ब्रॉडकास्ट लिस्ट बनाते समय चुनना आसान बनाता है।',
  h_result: '4. नतीजा जाँचें',
  stat_rows: 'लाइनें', stat_contacts: 'तैयार कॉन्टैक्ट', stat_invalid: 'गलत नंबर', stat_dups: 'डुप्लीकेट मिलाए', stat_landline: 'लैंडलाइन', stat_noname: 'बिना नाम',
  filter_label: 'दिखाएँ', filter_all: 'सभी', filter_ok: 'तैयार', filter_warn: 'ध्यान दें', filter_bad: 'गलत',
  th_line: 'लाइन', th_name: 'नाम', th_phone: 'नंबर', th_email: 'ईमेल', th_company: 'कंपनी', th_label: 'ग्रुप', th_status: 'स्थिति', th_note: 'नोट', th_title: 'पद', th_address: 'पता', th_bday: 'जन्मदिन', csv_phone: 'फ़ोन {n}',
  st_ok: 'तैयार', st_landline: 'लैंडलाइन', st_intl: 'विदेशी नंबर', st_merged: '{n} लाइनें मिलाई गईं', st_noname: 'नाम नहीं है, इसलिए नंबर ही नाम बना', st_dropped: '{n} गलत नंबर छोड़े गए',
  st_landline_off: 'लैंडलाइन (आपकी सेटिंग से हटाया)', st_intl_off: 'विदेशी नंबर (आपकी सेटिंग से हटाया)',
  bad_sci: 'Excel ने यह नंबर छोटा कर दिया (9.87654E+09)। कॉलम को Text फ़ॉर्मेट करके फिर कॉपी करें।', bad_len: 'गलत लंबाई: 10 की जगह {n} अंक', bad_text: 'यह फ़ोन नंबर नहीं है', bad_empty: 'नंबर नहीं है',
  show_more: '{n} और दिखाएँ', showing: '{b} में से {a} दिख रहे हैं', no_rows_filter: 'इस फ़िल्टर में कुछ नहीं है।', processing: '{n} लाइनें साफ़ हो रही हैं…',
  h_export: '5. डाउनलोड', file_label: 'फ़ाइल का नाम',
  dl_vcf: 'VCF डाउनलोड करें (सभी कॉन्टैक्ट)', dl_csv: 'साफ़ CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'सभी नंबर कॉपी करें',
  split_label: 'इतने-इतने की फ़ाइलों में बाँटें', split_hint: 'WhatsApp ब्रॉडकास्ट लिस्ट में अधिकतम 256 लोग हो सकते हैं (अक्टूबर 2026 में जाँचा), इसलिए 256 की फ़ाइलें = हर फ़ाइल की एक लिस्ट।',
  dl_parts_zip: 'सभी हिस्से डाउनलोड करें (ZIP)', part_n: 'हिस्सा {n}: कॉन्टैक्ट {a}–{b}', parts_summary: '{n} फ़ाइलें, हर एक में अधिकतम {m} कॉन्टैक्ट',
  preview_title: 'VCF फ़ाइल की झलक (पहले 3 कॉन्टैक्ट)', nothing_to_export: 'अभी डाउनलोड के लिए कोई कॉन्टैक्ट नहीं।', done_dl: '{name} डाउनलोड हुई', note_also: 'यह नाम भी लिखा था: {names}',
  import_tip: 'फ़ोन में: .vcf फ़ाइल WhatsApp या ईमेल से खुद को भेजें, खोलें और “Import contacts” चुनें। कंप्यूटर पर: contacts.google.com → Import → CSV चुनें।',
  help_title: 'कैसे इस्तेमाल करें और आइडिया',
  help_1: 'Excel या Google Sheets: नाम और मोबाइल के कॉलम हेडिंग वाली लाइन समेत चुनें, कॉपी करें और बॉक्स 1 में पेस्ट करें। कॉलम अपने-आप सही बैठ जाते हैं।',
  help_2: '098765-43210, +91 98765 43210 या 9876543210, सब +919876543210 बन जाते हैं। एक सेल में दो नंबर (98765 43210 / 91234 56789) उसी कॉन्टैक्ट के दो नंबर बनते हैं।',
  help_3: 'WhatsApp ब्रॉडकास्ट: “Diwali -” जैसा उपसर्ग जोड़ें, VCF को 256-256 के हिस्सों में डाउनलोड करें, फ़ोन में इम्पोर्ट करें, फिर ब्रॉडकास्ट लिस्ट बनाकर “Diwali -” से शुरू होने वाले सब चुन लें।',
  help_4: 'Google Contacts: Google Contacts CSV डाउनलोड करें और contacts.google.com पर इम्पोर्ट करें। ग्रुप का नाम वहाँ लेबल बन जाता है।',
  help_5: 'VCF से Excel: फ़ोन से निकली .vcf फ़ाइल खोलें, फिर साफ़ CSV डाउनलोड करके Excel में खोलें। नंबर +91 के साथ टेक्स्ट रहते हैं, इसलिए Excel उन्हें छोटा नहीं करेगा।',
  help_6: 'पहले अनुमति लें: DPDP Act 2023 और TRAI नियमों के तहत प्रमोशन सिर्फ़ उन ग्राहकों को भेजें जो सहमत हों, और जो रोकने को कहे उसे सूची से हटा दें।',
  aria_table: 'साफ़ की गई कॉन्टैक्ट सूची',
  sample_tsv: 'नाम\tमोबाइल\tईमेल\tकंपनी\tग्रुप\nरमेश कुमार\t098765-43210\tramesh@example.com\tकुमार किराना स्टोर\tग्राहक\nप्रिया शर्मा\t+91 91234 56789\tpriya@example.com\tशर्मा ट्यूशन क्लासेस\tग्राहक\nरमेश कुमार\t9876543210\t\t\tग्राहक\nअनिल मेहता\t9.87654E+09\t\tमेहता ट्रेडर्स\tसप्लायर\nफ़ातिमा ख़ान\t98989 89898 / 97979 79797\tfatima@example.com\tख़ान बुटीक\tग्राहक\nराजेश ऑफ़िस\t011-23456789\t\tराजेश एंड संस\tसप्लायर\nसुनीता देवी\t12345\t\tदेवी डेयरी\tग्राहक'
};
window.APP_STRINGS.bn = {
  app_title: 'Excel থেকে কন্টাক্ট (VCF)',
  intro: 'Excel বা Google Sheets থেকে গ্রাহক তালিকা পেস্ট করুন, মোবাইল নম্বর ঠিক করুন আর এমন VCF ফাইল ডাউনলোড করুন যা যেকোনো ফোনে সরাসরি ইমপোর্ট হয়, বা Google Contacts CSV বানান। VCF থেকে আবার Excel-এর জন্য CSV-ও বানানো যায়।',
  privacy: 'আপনার গ্রাহক তালিকা এই ডিভাইসের বাইরে যায় না: কিছুই আপলোড হয় না। ভারতের DPDP Act 2023 অনুযায়ী গ্রাহকদের ব্যক্তিগত তথ্য সুরক্ষিত রাখা আপনার দায়িত্ব, তাই এই ফাইল শুধু দরকারি লোকের সঙ্গে শেয়ার করুন আর কাজ শেষে মুছে দিন।',
  h_input: '1. তালিকা পেস্ট করুন বা খুলুন',
  paste_label: 'Excel, Google Sheets বা যেকোনো CSV থেকে এখানে পেস্ট করুন (এক লাইনে একজন)',
  paste_ph: 'নাম    মোবাইল    ইমেল    কোম্পানি    গ্রুপ\nরমেশ কুমার    98765 43210    ramesh@example.com    কুমার কিরানা    গ্রাহক',
  open_csv: 'CSV / TXT ফাইল খুলুন', open_vcf: 'VCF ফাইল খুলুন', load_example: 'উদাহরণ ভরুন',
  example_note: 'এটি কাল্পনিক নম্বরের উদাহরণ। এর জায়গায় নিজের তালিকা পেস্ট করুন।',
  excel_tip: 'টিপ: Excel বা Google Sheets-এ শিরোনামের লাইন সহ কলামগুলো বেছে কপি করে এখানে পেস্ট করুন। নম্বর 9.87654E+09 এর মতো দেখালে আগে কলামটি Text ফরম্যাট করে আবার কপি করুন।',
  lines_read: '{n}টি লাইন পড়া হয়েছে', vcf_read: 'VCF ফাইল থেকে {n}টি কন্টাক্ট পড়ে তালিকায় রাখা হয়েছে।', dl_vcf_csv: 'এগুলো CSV হিসেবে ডাউনলোড করুন',
  bad_file: 'এই ফাইলটি পড়া গেল না। .csv, .txt বা .vcf ফাইল দিন।', empty_list: 'শুরু করতে ওপরে আপনার তালিকা পেস্ট করুন।',
  h_map: '2. কোন কলাম কী?', map_hint: 'আপনার ডেটা দেখে অনুমান করা হয়েছে। ভুল হলে বাক্স বদলে দিন।', has_header: 'প্রথম লাইনটি শিরোনাম',
  col_name: 'নাম', col_last: 'পদবি (ঐচ্ছিক)', col_phone: 'মোবাইল / ফোন', col_phone2: 'দ্বিতীয় ফোন (ঐচ্ছিক)', col_email: 'ইমেল', col_company: 'কোম্পানি / দোকান', col_label: 'গ্রুপ / লেবেল', col_note: 'নোট',
  none_opt: '— কিছু না —', col_n: 'কলাম {n}',
  h_clean: '3. পরিষ্কারের বিকল্প', cc_label: 'যে নম্বরে দেশের কোড নেই, তার কোড', cc_hint: 'ভারত 91 · UAE 971 · নেপাল 977 · বাংলাদেশ 880 · শ্রীলঙ্কা 94',
  opt_title: 'নামের বড়-ছোট অক্ষর ঠিক করুন (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'একই নম্বরের ডুপ্লিকেট লাইন এক কন্টাক্টে মেলান',
  opt_landline: 'ল্যান্ডলাইন নম্বর রাখুন (⚠ চিহ্ন সহ)', opt_intl: 'বিদেশি নম্বর রাখুন (🌐 চিহ্ন সহ)',
  prefix_label: 'প্রতিটি নামের আগে যোগ করুন', prefix_ph: 'যেমন Cust -', suffix_label: 'প্রতিটি নামের পরে যোগ করুন', suffix_ph: 'যেমন (দীপাবলি 2026)',
  prefix_hint: '“Cust -” এর মতো উপসর্গ এই কন্টাক্টগুলো ফোনে একসঙ্গে রাখে, ফলে WhatsApp ব্রডকাস্ট লিস্টে বেছে নেওয়া সহজ হয়।',
  h_result: '4. ফলাফল দেখুন',
  stat_rows: 'লাইন', stat_contacts: 'তৈরি কন্টাক্ট', stat_invalid: 'ভুল নম্বর', stat_dups: 'ডুপ্লিকেট মেলানো', stat_landline: 'ল্যান্ডলাইন', stat_noname: 'নাম ছাড়া',
  filter_label: 'দেখান', filter_all: 'সব', filter_ok: 'তৈরি', filter_warn: 'খেয়াল করুন', filter_bad: 'ভুল',
  th_line: 'লাইন', th_name: 'নাম', th_phone: 'নম্বর', th_email: 'ইমেল', th_company: 'কোম্পানি', th_label: 'গ্রুপ', th_status: 'অবস্থা', th_note: 'নোট', th_title: 'পদ', th_address: 'ঠিকানা', th_bday: 'জন্মদিন', csv_phone: 'ফোন {n}',
  st_ok: 'তৈরি', st_landline: 'ল্যান্ডলাইন', st_intl: 'বিদেশি নম্বর', st_merged: '{n}টি লাইন মেলানো হয়েছে', st_noname: 'নাম নেই, তাই নম্বরই নাম', st_dropped: '{n}টি ভুল নম্বর বাদ দেওয়া হয়েছে',
  st_landline_off: 'ল্যান্ডলাইন (আপনার সেটিং অনুযায়ী বাদ)', st_intl_off: 'বিদেশি নম্বর (আপনার সেটিং অনুযায়ী বাদ)',
  bad_sci: 'Excel নম্বরটি ছোট করে দিয়েছে (9.87654E+09)। কলামটি Text ফরম্যাট করে আবার কপি করুন।', bad_len: 'ভুল দৈর্ঘ্য: 10-এর বদলে {n} অঙ্ক', bad_text: 'এটি ফোন নম্বর নয়', bad_empty: 'নম্বর নেই',
  show_more: 'আরও {n}টি দেখান', showing: '{b}টির মধ্যে {a}টি দেখানো হচ্ছে', no_rows_filter: 'এই ফিল্টারে কিছু নেই।', processing: '{n}টি লাইন পরিষ্কার হচ্ছে…',
  h_export: '5. ডাউনলোড', file_label: 'ফাইলের নাম',
  dl_vcf: 'VCF ডাউনলোড (সব কন্টাক্ট)', dl_csv: 'পরিষ্কার CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'সব নম্বর কপি করুন',
  split_label: 'এত জন করে ফাইলে ভাগ করুন', split_hint: 'WhatsApp ব্রডকাস্ট লিস্টে সর্বোচ্চ 256 জন থাকতে পারে (অক্টোবর 2026-এ দেখা), তাই 256-এর ফাইল মানে প্রতি ফাইলে একটি লিস্ট।',
  dl_parts_zip: 'সব অংশ ডাউনলোড (ZIP)', part_n: 'অংশ {n}: কন্টাক্ট {a}–{b}', parts_summary: '{n}টি ফাইল, প্রতিটিতে সর্বোচ্চ {m}টি কন্টাক্ট',
  preview_title: 'VCF ফাইলের ঝলক (প্রথম 3টি কন্টাক্ট)', nothing_to_export: 'এখনও ডাউনলোডের মতো কোনো কন্টাক্ট নেই।', done_dl: '{name} ডাউনলোড হয়েছে', note_also: 'এই নামেও লেখা ছিল: {names}',
  import_tip: 'ফোনে: .vcf ফাইলটি WhatsApp বা ইমেলে নিজেকে পাঠান, খুলে “Import contacts” বেছে নিন। কম্পিউটারে: contacts.google.com → Import → CSV বেছে নিন।',
  help_title: 'কীভাবে ব্যবহার করবেন ও আইডিয়া',
  help_1: 'Excel বা Google Sheets: নাম আর মোবাইলের কলাম শিরোনাম সহ বেছে কপি করে 1 নম্বর বাক্সে পেস্ট করুন। কলাম নিজে থেকেই মিলে যায়।',
  help_2: '098765-43210, +91 98765 43210 বা 9876543210, সবই +919876543210 হয়ে যায়। এক ঘরে দুটি নম্বর (98765 43210 / 91234 56789) একই কন্টাক্টের দুটি নম্বর হয়।',
  help_3: 'WhatsApp ব্রডকাস্ট: “Diwali -” এর মতো উপসর্গ দিন, VCF 256-এর অংশে ডাউনলোড করে ফোনে ইমপোর্ট করুন, তারপর ব্রডকাস্ট লিস্টে “Diwali -” দিয়ে শুরু সবাইকে বেছে নিন।',
  help_4: 'Google Contacts: Google Contacts CSV ডাউনলোড করে contacts.google.com-এ ইমপোর্ট করুন। গ্রুপের নাম সেখানে লেবেল হয়ে যায়।',
  help_5: 'VCF থেকে Excel: ফোন থেকে নেওয়া .vcf খুলুন, তারপর পরিষ্কার CSV ডাউনলোড করে Excel-এ খুলুন। নম্বর +91 সহ টেক্সট থাকে, তাই Excel ছোট করবে না।',
  help_6: 'আগে অনুমতি নিন: DPDP Act 2023 আর TRAI নিয়ম অনুযায়ী শুধু সম্মত গ্রাহকদের প্রচার পাঠান, আর কেউ থামাতে বললে তালিকা থেকে সরিয়ে দিন।',
  aria_table: 'পরিষ্কার কন্টাক্ট তালিকা',
  sample_tsv: 'নাম\tমোবাইল\tইমেল\tকোম্পানি\tগ্রুপ\nরমেশ কুমার\t098765-43210\tramesh@example.com\tকুমার কিরানা স্টোর\tগ্রাহক\nপ্রিয়া শর্মা\t+91 91234 56789\tpriya@example.com\tশর্মা টিউশন\tগ্রাহক\nরমেশ কুমার\t9876543210\t\t\tগ্রাহক\nঅনিল মেহতা\t9.87654E+09\t\tমেহতা ট্রেডার্স\tসাপ্লায়ার\nফাতিমা খান\t98989 89898 / 97979 79797\tfatima@example.com\tখান বুটিক\tগ্রাহক\nরাজেশ অফিস\t011-23456789\t\tরাজেশ অ্যান্ড সন্স\tসাপ্লায়ার\nসুনীতা দেবী\t12345\t\tদেবী ডেয়ারি\tগ্রাহক'
};
window.APP_STRINGS.mr = {
  app_title: 'Excel मधून कॉन्टॅक्ट (VCF)',
  intro: 'Excel किंवा Google Sheets मधून ग्राहक यादी पेस्ट करा, मोबाइल नंबर दुरुस्त करा आणि कोणत्याही फोनमध्ये थेट इम्पोर्ट होणारी VCF फाइल डाउनलोड करा, किंवा Google Contacts CSV बनवा. VCF पुन्हा Excel साठी CSV मध्येही बदलता येते.',
  privacy: 'तुमची ग्राहक यादी या डिव्हाइसबाहेर जात नाही: काहीही अपलोड होत नाही. भारताच्या DPDP Act 2023 नुसार ग्राहकांचा वैयक्तिक डेटा सुरक्षित ठेवणे ही तुमची जबाबदारी आहे, म्हणून या फाइल फक्त गरजेच्या लोकांना द्या आणि काम झाल्यावर हटवा.',
  h_input: '1. यादी पेस्ट करा किंवा उघडा',
  paste_label: 'Excel, Google Sheets किंवा कोणत्याही CSV मधून इथे पेस्ट करा (एका ओळीत एक व्यक्ती)',
  paste_ph: 'नाव    मोबाइल    ईमेल    कंपनी    गट\nरमेश कुमार    98765 43210    ramesh@example.com    कुमार किराणा    ग्राहक',
  open_csv: 'CSV / TXT फाइल उघडा', open_vcf: 'VCF फाइल उघडा', load_example: 'उदाहरण भरा',
  example_note: 'हे काल्पनिक नंबरांचे उदाहरण आहे. त्याऐवजी तुमची यादी पेस्ट करा.',
  excel_tip: 'टीप: Excel किंवा Google Sheets मध्ये शीर्षक ओळीसह कॉलम निवडा, कॉपी करा आणि इथे पेस्ट करा. नंबर 9.87654E+09 असा दिसला तर आधी तो कॉलम Text फॉरमॅट करा आणि पुन्हा कॉपी करा.',
  lines_read: '{n} ओळी वाचल्या', vcf_read: 'VCF फाइलमधून {n} कॉन्टॅक्ट वाचून यादीत ठेवले.', dl_vcf_csv: 'हे CSV म्हणून डाउनलोड करा',
  bad_file: 'ही फाइल वाचता आली नाही. .csv, .txt किंवा .vcf फाइल निवडा.', empty_list: 'सुरू करण्यासाठी वर तुमची यादी पेस्ट करा.',
  h_map: '2. कोणता कॉलम काय आहे?', map_hint: 'तुमच्या डेटावरून अंदाज लावला आहे. चुकला असेल तर बॉक्स बदला.', has_header: 'पहिली ओळ शीर्षक आहे',
  col_name: 'नाव', col_last: 'आडनाव (ऐच्छिक)', col_phone: 'मोबाइल / फोन', col_phone2: 'दुसरा फोन (ऐच्छिक)', col_email: 'ईमेल', col_company: 'कंपनी / दुकान', col_label: 'गट / लेबल', col_note: 'टीप',
  none_opt: '— काहीही नाही —', col_n: 'कॉलम {n}',
  h_clean: '3. स्वच्छतेचे पर्याय', cc_label: 'देश कोड नसलेल्या नंबरसाठी कोड', cc_hint: 'भारत 91 · UAE 971 · नेपाळ 977 · बांगलादेश 880 · श्रीलंका 94',
  opt_title: 'नावांतील कॅपिटल अक्षरे दुरुस्त करा (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'एकाच नंबरच्या डुप्लिकेट ओळी एका कॉन्टॅक्टमध्ये जोडा',
  opt_landline: 'लँडलाइन नंबर ठेवा (⚠ खुणेसह)', opt_intl: 'परदेशी नंबर ठेवा (🌐 खुणेसह)',
  prefix_label: 'प्रत्येक नावाच्या आधी जोडा', prefix_ph: 'उदा. Cust -', suffix_label: 'प्रत्येक नावानंतर जोडा', suffix_ph: 'उदा. (दिवाळी 2026)',
  prefix_hint: '“Cust -” सारखा उपसर्ग हे कॉन्टॅक्ट फोनमध्ये एकत्र ठेवतो, त्यामुळे WhatsApp ब्रॉडकास्ट लिस्टसाठी निवडणे सोपे होते.',
  h_result: '4. निकाल तपासा',
  stat_rows: 'ओळी', stat_contacts: 'तयार कॉन्टॅक्ट', stat_invalid: 'चुकीचे नंबर', stat_dups: 'डुप्लिकेट जोडले', stat_landline: 'लँडलाइन', stat_noname: 'नावाशिवाय',
  filter_label: 'दाखवा', filter_all: 'सर्व', filter_ok: 'तयार', filter_warn: 'लक्ष द्या', filter_bad: 'चुकीचे',
  th_line: 'ओळ', th_name: 'नाव', th_phone: 'नंबर', th_email: 'ईमेल', th_company: 'कंपनी', th_label: 'गट', th_status: 'स्थिती', th_note: 'टीप', th_title: 'पद', th_address: 'पत्ता', th_bday: 'वाढदिवस', csv_phone: 'फोन {n}',
  st_ok: 'तयार', st_landline: 'लँडलाइन', st_intl: 'परदेशी नंबर', st_merged: '{n} ओळी जोडल्या', st_noname: 'नाव नाही, म्हणून नंबरच नाव', st_dropped: '{n} चुकीचे नंबर वगळले',
  st_landline_off: 'लँडलाइन (तुमच्या सेटिंगनुसार वगळला)', st_intl_off: 'परदेशी नंबर (तुमच्या सेटिंगनुसार वगळला)',
  bad_sci: 'Excel ने हा नंबर लहान केला (9.87654E+09). कॉलम Text फॉरमॅट करून पुन्हा कॉपी करा.', bad_len: 'चुकीची लांबी: 10 ऐवजी {n} अंक', bad_text: 'हा फोन नंबर नाही', bad_empty: 'नंबर नाही',
  show_more: 'आणखी {n} दाखवा', showing: '{b} पैकी {a} दिसत आहेत', no_rows_filter: 'या फिल्टरमध्ये काही नाही.', processing: '{n} ओळी स्वच्छ होत आहेत…',
  h_export: '5. डाउनलोड', file_label: 'फाइलचे नाव',
  dl_vcf: 'VCF डाउनलोड (सर्व कॉन्टॅक्ट)', dl_csv: 'स्वच्छ CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'सर्व नंबर कॉपी करा',
  split_label: 'इतक्या-इतक्यांच्या फाइलमध्ये विभागा', split_hint: 'WhatsApp ब्रॉडकास्ट लिस्टमध्ये जास्तीत जास्त 256 लोक असू शकतात (ऑक्टोबर 2026 मध्ये तपासले), म्हणून 256 च्या फाइल = प्रत्येक फाइलची एक लिस्ट.',
  dl_parts_zip: 'सर्व भाग डाउनलोड करा (ZIP)', part_n: 'भाग {n}: कॉन्टॅक्ट {a}–{b}', parts_summary: '{n} फाइल, प्रत्येकीत जास्तीत जास्त {m} कॉन्टॅक्ट',
  preview_title: 'VCF फाइलची झलक (पहिले 3 कॉन्टॅक्ट)', nothing_to_export: 'अजून डाउनलोडसाठी कॉन्टॅक्ट नाहीत.', done_dl: '{name} डाउनलोड झाली', note_also: 'हे नावही लिहिले होते: {names}',
  import_tip: 'फोनवर: .vcf फाइल WhatsApp किंवा ईमेलने स्वतःला पाठवा, उघडा आणि “Import contacts” निवडा. कॉम्प्युटरवर: contacts.google.com → Import → CSV निवडा.',
  help_title: 'कसे वापरावे आणि कल्पना',
  help_1: 'Excel किंवा Google Sheets: नाव आणि मोबाइलचे कॉलम शीर्षक ओळीसह निवडा, कॉपी करा आणि बॉक्स 1 मध्ये पेस्ट करा. कॉलम आपोआप जुळतात.',
  help_2: '098765-43210, +91 98765 43210 किंवा 9876543210, सगळे +919876543210 होतात. एका सेलमधील दोन नंबर (98765 43210 / 91234 56789) एकाच कॉन्टॅक्टचे दोन नंबर होतात.',
  help_3: 'WhatsApp ब्रॉडकास्ट: “Diwali -” सारखा उपसर्ग जोडा, VCF 256 च्या भागांत डाउनलोड करा, फोनमध्ये इम्पोर्ट करा, मग ब्रॉडकास्ट लिस्टमध्ये “Diwali -” ने सुरू होणारे सगळे निवडा.',
  help_4: 'Google Contacts: Google Contacts CSV डाउनलोड करून contacts.google.com वर इम्पोर्ट करा. गटाचे नाव तिथे लेबल बनते.',
  help_5: 'VCF ते Excel: फोनमधून काढलेली .vcf उघडा, मग स्वच्छ CSV डाउनलोड करून Excel मध्ये उघडा. नंबर +91 सह टेक्स्ट राहतात, म्हणून Excel ते लहान करत नाही.',
  help_6: 'आधी परवानगी घ्या: DPDP Act 2023 आणि TRAI नियमांनुसार प्रचार फक्त संमती दिलेल्या ग्राहकांना पाठवा, आणि थांबवायला सांगणाऱ्यांना यादीतून काढा.',
  aria_table: 'स्वच्छ कॉन्टॅक्ट यादी',
  sample_tsv: 'नाव\tमोबाइल\tईमेल\tकंपनी\tगट\nरमेश कुमार\t098765-43210\tramesh@example.com\tकुमार किराणा स्टोअर\tग्राहक\nप्रिया शर्मा\t+91 91234 56789\tpriya@example.com\tशर्मा ट्यूशन\tग्राहक\nरमेश कुमार\t9876543210\t\t\tग्राहक\nअनिल मेहता\t9.87654E+09\t\tमेहता ट्रेडर्स\tपुरवठादार\nफातिमा खान\t98989 89898 / 97979 79797\tfatima@example.com\tखान बुटीक\tग्राहक\nराजेश ऑफिस\t011-23456789\t\tराजेश अँड सन्स\tपुरवठादार\nसुनीता देवी\t12345\t\tदेवी डेअरी\tग्राहक'
};
window.APP_STRINGS.gu = {
  app_title: 'Excel થી કોન્ટેક્ટ (VCF)',
  intro: 'Excel કે Google Sheets માંથી ગ્રાહક યાદી પેસ્ટ કરો, મોબાઇલ નંબર સાફ કરો અને કોઈ પણ ફોનમાં સીધી ઇમ્પોર્ટ થતી VCF ફાઇલ ડાઉનલોડ કરો, અથવા Google Contacts CSV બનાવો. VCF ને પાછી Excel માટે CSV પણ બનાવી શકાય.',
  privacy: 'તમારી ગ્રાહક યાદી આ ડિવાઇસની બહાર જતી નથી: કંઈ અપલોડ થતું નથી. ભારતના DPDP Act 2023 મુજબ ગ્રાહકોનો અંગત ડેટા સુરક્ષિત રાખવો તમારી જવાબદારી છે, તેથી આ ફાઇલો ફક્ત જરૂરી લોકોને જ આપો અને કામ પૂરું થાય પછી કાઢી નાખો.',
  h_input: '1. યાદી પેસ્ટ કરો અથવા ખોલો',
  paste_label: 'Excel, Google Sheets કે કોઈ CSV માંથી અહીં પેસ્ટ કરો (એક લાઇનમાં એક વ્યક્તિ)',
  paste_ph: 'નામ    મોબાઇલ    ઈમેલ    કંપની    ગ્રુપ\nરમેશ કુમાર    98765 43210    ramesh@example.com    કુમાર કરિયાણા    ગ્રાહક',
  open_csv: 'CSV / TXT ફાઇલ ખોલો', open_vcf: 'VCF ફાઇલ ખોલો', load_example: 'ઉદાહરણ ભરો',
  example_note: 'આ કાલ્પનિક નંબરોવાળું ઉદાહરણ છે. તેની જગ્યાએ તમારી યાદી પેસ્ટ કરો.',
  excel_tip: 'ટિપ: Excel કે Google Sheets માં મથાળાની લાઇન સાથે કૉલમ પસંદ કરો, કૉપિ કરો અને અહીં પેસ્ટ કરો. નંબર 9.87654E+09 જેવો દેખાય તો પહેલાં તે કૉલમ Text ફૉર્મેટ કરો અને ફરી કૉપિ કરો.',
  lines_read: '{n} લાઇન વાંચી', vcf_read: 'VCF ફાઇલમાંથી {n} કોન્ટેક્ટ વાંચીને યાદીમાં મૂક્યા.', dl_vcf_csv: 'આને CSV તરીકે ડાઉનલોડ કરો',
  bad_file: 'આ ફાઇલ વાંચી શકાઈ નહીં. .csv, .txt કે .vcf ફાઇલ પસંદ કરો.', empty_list: 'શરૂ કરવા ઉપર તમારી યાદી પેસ્ટ કરો.',
  h_map: '2. કયો કૉલમ શું છે?', map_hint: 'તમારા ડેટા પરથી અંદાજ લગાવ્યો છે. ખોટો હોય તો બૉક્સ બદલો.', has_header: 'પહેલી લાઇન મથાળું છે',
  col_name: 'નામ', col_last: 'અટક (વૈકલ્પિક)', col_phone: 'મોબાઇલ / ફોન', col_phone2: 'બીજો ફોન (વૈકલ્પિક)', col_email: 'ઈમેલ', col_company: 'કંપની / દુકાન', col_label: 'ગ્રુપ / લેબલ', col_note: 'નોંધ',
  none_opt: '— કંઈ નહીં —', col_n: 'કૉલમ {n}',
  h_clean: '3. સફાઈના વિકલ્પો', cc_label: 'દેશ કોડ વગરના નંબર માટે કોડ', cc_hint: 'ભારત 91 · UAE 971 · નેપાળ 977 · બાંગ્લાદેશ 880 · શ્રીલંકા 94',
  opt_title: 'નામના કૅપિટલ અક્ષરો સુધારો (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'એક જ નંબરની ડુપ્લિકેટ લાઇનો એક કોન્ટેક્ટમાં જોડો',
  opt_landline: 'લેન્ડલાઇન નંબર રાખો (⚠ નિશાની સાથે)', opt_intl: 'વિદેશી નંબર રાખો (🌐 નિશાની સાથે)',
  prefix_label: 'દરેક નામની આગળ ઉમેરો', prefix_ph: 'જેમ કે Cust -', suffix_label: 'દરેક નામ પછી ઉમેરો', suffix_ph: 'જેમ કે (દિવાળી 2026)',
  prefix_hint: '“Cust -” જેવો ઉપસર્ગ આ કોન્ટેક્ટને ફોનમાં સાથે રાખે છે, તેથી WhatsApp બ્રૉડકાસ્ટ લિસ્ટ માટે પસંદ કરવા સહેલા બને છે.',
  h_result: '4. પરિણામ તપાસો',
  stat_rows: 'લાઇન', stat_contacts: 'તૈયાર કોન્ટેક્ટ', stat_invalid: 'ખોટા નંબર', stat_dups: 'ડુપ્લિકેટ જોડ્યા', stat_landline: 'લેન્ડલાઇન', stat_noname: 'નામ વગર',
  filter_label: 'બતાવો', filter_all: 'બધા', filter_ok: 'તૈયાર', filter_warn: 'ધ્યાન આપો', filter_bad: 'ખોટા',
  th_line: 'લાઇન', th_name: 'નામ', th_phone: 'નંબર', th_email: 'ઈમેલ', th_company: 'કંપની', th_label: 'ગ્રુપ', th_status: 'સ્થિતિ', th_note: 'નોંધ', th_title: 'હોદ્દો', th_address: 'સરનામું', th_bday: 'જન્મદિવસ', csv_phone: 'ફોન {n}',
  st_ok: 'તૈયાર', st_landline: 'લેન્ડલાઇન', st_intl: 'વિદેશી નંબર', st_merged: '{n} લાઇન જોડી', st_noname: 'નામ નથી, તેથી નંબર જ નામ', st_dropped: '{n} ખોટા નંબર છોડ્યા',
  st_landline_off: 'લેન્ડલાઇન (તમારા સેટિંગથી છોડ્યો)', st_intl_off: 'વિદેશી નંબર (તમારા સેટિંગથી છોડ્યો)',
  bad_sci: 'Excel એ આ નંબર ટૂંકો કરી દીધો (9.87654E+09). કૉલમ Text ફૉર્મેટ કરીને ફરી કૉપિ કરો.', bad_len: 'ખોટી લંબાઈ: 10 ને બદલે {n} અંક', bad_text: 'આ ફોન નંબર નથી', bad_empty: 'નંબર નથી',
  show_more: 'વધુ {n} બતાવો', showing: '{b} માંથી {a} દેખાય છે', no_rows_filter: 'આ ફિલ્ટરમાં કંઈ નથી.', processing: '{n} લાઇન સાફ થઈ રહી છે…',
  h_export: '5. ડાઉનલોડ', file_label: 'ફાઇલનું નામ',
  dl_vcf: 'VCF ડાઉનલોડ (બધા કોન્ટેક્ટ)', dl_csv: 'સાફ CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'બધા નંબર કૉપિ કરો',
  split_label: 'આટલા-આટલાની ફાઇલોમાં વહેંચો', split_hint: 'WhatsApp બ્રૉડકાસ્ટ લિસ્ટમાં વધુમાં વધુ 256 લોકો હોઈ શકે (ઑક્ટોબર 2026 માં તપાસ્યું), તેથી 256 ની ફાઇલ = દરેક ફાઇલની એક લિસ્ટ.',
  dl_parts_zip: 'બધા ભાગ ડાઉનલોડ કરો (ZIP)', part_n: 'ભાગ {n}: કોન્ટેક્ટ {a}–{b}', parts_summary: '{n} ફાઇલ, દરેકમાં વધુમાં વધુ {m} કોન્ટેક્ટ',
  preview_title: 'VCF ફાઇલની ઝલક (પહેલા 3 કોન્ટેક્ટ)', nothing_to_export: 'હજી ડાઉનલોડ માટે કોઈ કોન્ટેક્ટ નથી.', done_dl: '{name} ડાઉનલોડ થઈ', note_also: 'આ નામ પણ લખ્યું હતું: {names}',
  import_tip: 'ફોનમાં: .vcf ફાઇલ WhatsApp કે ઈમેલથી પોતાને મોકલો, ખોલો અને “Import contacts” પસંદ કરો. કમ્પ્યુટર પર: contacts.google.com → Import → CSV પસંદ કરો.',
  help_title: 'કેવી રીતે વાપરવું અને આઇડિયા',
  help_1: 'Excel કે Google Sheets: નામ અને મોબાઇલના કૉલમ મથાળા સાથે પસંદ કરો, કૉપિ કરો અને બૉક્સ 1 માં પેસ્ટ કરો. કૉલમ આપમેળે ગોઠવાઈ જાય છે.',
  help_2: '098765-43210, +91 98765 43210 કે 9876543210, બધા +919876543210 બને છે. એક સેલમાં બે નંબર (98765 43210 / 91234 56789) એક જ કોન્ટેક્ટના બે નંબર બને છે.',
  help_3: 'WhatsApp બ્રૉડકાસ્ટ: “Diwali -” જેવો ઉપસર્ગ ઉમેરો, VCF 256 ના ભાગમાં ડાઉનલોડ કરો, ફોનમાં ઇમ્પોર્ટ કરો, પછી બ્રૉડકાસ્ટ લિસ્ટમાં “Diwali -” થી શરૂ થતા બધા પસંદ કરો.',
  help_4: 'Google Contacts: Google Contacts CSV ડાઉનલોડ કરી contacts.google.com પર ઇમ્પોર્ટ કરો. ગ્રુપનું નામ ત્યાં લેબલ બને છે.',
  help_5: 'VCF થી Excel: ફોનમાંથી કાઢેલી .vcf ખોલો, પછી સાફ CSV ડાઉનલોડ કરી Excel માં ખોલો. નંબર +91 સાથે ટેક્સ્ટ રહે છે, તેથી Excel તેને ટૂંકા નહીં કરે.',
  help_6: 'પહેલાં પરવાનગી લો: DPDP Act 2023 અને TRAI નિયમો મુજબ પ્રચાર ફક્ત સંમતિ આપનાર ગ્રાહકોને જ મોકલો, અને બંધ કરવાનું કહે તેને યાદીમાંથી કાઢો.',
  aria_table: 'સાફ કરેલી કોન્ટેક્ટ યાદી',
  sample_tsv: 'નામ\tમોબાઇલ\tઈમેલ\tકંપની\tગ્રુપ\nરમેશ કુમાર\t098765-43210\tramesh@example.com\tકુમાર કરિયાણા સ્ટોર\tગ્રાહક\nપ્રિયા શર્મા\t+91 91234 56789\tpriya@example.com\tશર્મા ટ્યુશન\tગ્રાહક\nરમેશ કુમાર\t9876543210\t\t\tગ્રાહક\nઅનિલ મહેતા\t9.87654E+09\t\tમહેતા ટ્રેડર્સ\tસપ્લાયર\nફાતિમા ખાન\t98989 89898 / 97979 79797\tfatima@example.com\tખાન બુટિક\tગ્રાહક\nરાજેશ ઑફિસ\t011-23456789\t\tરાજેશ એન્ડ સન્સ\tસપ્લાયર\nસુનીતા દેવી\t12345\t\tદેવી ડેરી\tગ્રાહક'
};
window.APP_STRINGS.pa = {
  app_title: 'Excel ਤੋਂ ਕਾਂਟੈਕਟ (VCF)',
  intro: 'Excel ਜਾਂ Google Sheets ਤੋਂ ਗਾਹਕ ਸੂਚੀ ਪੇਸਟ ਕਰੋ, ਮੋਬਾਈਲ ਨੰਬਰ ਠੀਕ ਕਰੋ ਅਤੇ ਅਜਿਹੀ VCF ਫ਼ਾਈਲ ਡਾਊਨਲੋਡ ਕਰੋ ਜੋ ਕਿਸੇ ਵੀ ਫ਼ੋਨ ਵਿੱਚ ਸਿੱਧੀ ਇੰਪੋਰਟ ਹੋ ਜਾਵੇ, ਜਾਂ Google Contacts CSV ਬਣਾਓ। VCF ਨੂੰ ਵਾਪਸ Excel ਲਈ CSV ਵੀ ਬਣਾ ਸਕਦੇ ਹੋ।',
  privacy: 'ਤੁਹਾਡੀ ਗਾਹਕ ਸੂਚੀ ਇਸ ਡਿਵਾਈਸ ਤੋਂ ਬਾਹਰ ਨਹੀਂ ਜਾਂਦੀ: ਕੁਝ ਵੀ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ। ਭਾਰਤ ਦੇ DPDP Act 2023 ਅਨੁਸਾਰ ਗਾਹਕਾਂ ਦਾ ਨਿੱਜੀ ਡਾਟਾ ਸੁਰੱਖਿਅਤ ਰੱਖਣਾ ਤੁਹਾਡੀ ਜ਼ਿੰਮੇਵਾਰੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਫ਼ਾਈਲਾਂ ਸਿਰਫ਼ ਲੋੜੀਂਦੇ ਲੋਕਾਂ ਨਾਲ ਸਾਂਝੀਆਂ ਕਰੋ ਅਤੇ ਕੰਮ ਮੁੱਕਣ ਤੇ ਮਿਟਾ ਦਿਓ।',
  h_input: '1. ਸੂਚੀ ਪੇਸਟ ਕਰੋ ਜਾਂ ਖੋਲ੍ਹੋ',
  paste_label: 'Excel, Google Sheets ਜਾਂ ਕਿਸੇ CSV ਤੋਂ ਇੱਥੇ ਪੇਸਟ ਕਰੋ (ਇੱਕ ਲਾਈਨ ਵਿੱਚ ਇੱਕ ਵਿਅਕਤੀ)',
  paste_ph: 'ਨਾਂ    ਮੋਬਾਈਲ    ਈਮੇਲ    ਕੰਪਨੀ    ਗਰੁੱਪ\nਰਮੇਸ਼ ਕੁਮਾਰ    98765 43210    ramesh@example.com    ਕੁਮਾਰ ਕਰਿਆਨਾ    ਗਾਹਕ',
  open_csv: 'CSV / TXT ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ', open_vcf: 'VCF ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ', load_example: 'ਉਦਾਹਰਨ ਭਰੋ',
  example_note: 'ਇਹ ਕਾਲਪਨਿਕ ਨੰਬਰਾਂ ਵਾਲੀ ਉਦਾਹਰਨ ਹੈ। ਇਸ ਦੀ ਥਾਂ ਆਪਣੀ ਸੂਚੀ ਪੇਸਟ ਕਰੋ।',
  excel_tip: 'ਸੁਝਾਅ: Excel ਜਾਂ Google Sheets ਵਿੱਚ ਸਿਰਲੇਖ ਵਾਲੀ ਲਾਈਨ ਸਮੇਤ ਕਾਲਮ ਚੁਣੋ, ਕਾਪੀ ਕਰੋ ਅਤੇ ਇੱਥੇ ਪੇਸਟ ਕਰੋ। ਜੇ ਨੰਬਰ 9.87654E+09 ਵਰਗਾ ਦਿਸੇ ਤਾਂ ਪਹਿਲਾਂ ਉਸ ਕਾਲਮ ਨੂੰ Text ਫ਼ਾਰਮੈਟ ਕਰੋ ਅਤੇ ਫਿਰ ਕਾਪੀ ਕਰੋ।',
  lines_read: '{n} ਲਾਈਨਾਂ ਪੜ੍ਹੀਆਂ', vcf_read: 'VCF ਫ਼ਾਈਲ ਵਿੱਚੋਂ {n} ਕਾਂਟੈਕਟ ਪੜ੍ਹ ਕੇ ਸੂਚੀ ਵਿੱਚ ਰੱਖੇ।', dl_vcf_csv: 'ਇਹਨਾਂ ਨੂੰ CSV ਵਜੋਂ ਡਾਊਨਲੋਡ ਕਰੋ',
  bad_file: 'ਇਹ ਫ਼ਾਈਲ ਪੜ੍ਹੀ ਨਹੀਂ ਜਾ ਸਕੀ। .csv, .txt ਜਾਂ .vcf ਫ਼ਾਈਲ ਚੁਣੋ।', empty_list: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਉੱਪਰ ਆਪਣੀ ਸੂਚੀ ਪੇਸਟ ਕਰੋ।',
  h_map: '2. ਕਿਹੜਾ ਕਾਲਮ ਕੀ ਹੈ?', map_hint: 'ਤੁਹਾਡੇ ਡਾਟੇ ਤੋਂ ਅੰਦਾਜ਼ਾ ਲਾਇਆ ਹੈ। ਗਲਤ ਹੋਵੇ ਤਾਂ ਬਕਸਾ ਬਦਲੋ।', has_header: 'ਪਹਿਲੀ ਲਾਈਨ ਸਿਰਲੇਖ ਹੈ',
  col_name: 'ਨਾਂ', col_last: 'ਗੋਤ (ਚੋਣਵਾਂ)', col_phone: 'ਮੋਬਾਈਲ / ਫ਼ੋਨ', col_phone2: 'ਦੂਜਾ ਫ਼ੋਨ (ਚੋਣਵਾਂ)', col_email: 'ਈਮੇਲ', col_company: 'ਕੰਪਨੀ / ਦੁਕਾਨ', col_label: 'ਗਰੁੱਪ / ਲੇਬਲ', col_note: 'ਨੋਟ',
  none_opt: '— ਕੋਈ ਨਹੀਂ —', col_n: 'ਕਾਲਮ {n}',
  h_clean: '3. ਸਫ਼ਾਈ ਦੇ ਵਿਕਲਪ', cc_label: 'ਜਿਨ੍ਹਾਂ ਨੰਬਰਾਂ ਵਿੱਚ ਦੇਸ਼ ਕੋਡ ਨਹੀਂ, ਉਹਨਾਂ ਲਈ ਕੋਡ', cc_hint: 'ਭਾਰਤ 91 · UAE 971 · ਨੇਪਾਲ 977 · ਬੰਗਲਾਦੇਸ਼ 880 · ਸ੍ਰੀਲੰਕਾ 94',
  opt_title: 'ਨਾਂਵਾਂ ਦੇ ਵੱਡੇ-ਛੋਟੇ ਅੱਖਰ ਠੀਕ ਕਰੋ (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'ਇੱਕੋ ਨੰਬਰ ਦੀਆਂ ਡੁਪਲੀਕੇਟ ਲਾਈਨਾਂ ਇੱਕ ਕਾਂਟੈਕਟ ਵਿੱਚ ਜੋੜੋ',
  opt_landline: 'ਲੈਂਡਲਾਈਨ ਨੰਬਰ ਰੱਖੋ (⚠ ਨਿਸ਼ਾਨ ਨਾਲ)', opt_intl: 'ਵਿਦੇਸ਼ੀ ਨੰਬਰ ਰੱਖੋ (🌐 ਨਿਸ਼ਾਨ ਨਾਲ)',
  prefix_label: 'ਹਰ ਨਾਂ ਤੋਂ ਪਹਿਲਾਂ ਜੋੜੋ', prefix_ph: 'ਜਿਵੇਂ Cust -', suffix_label: 'ਹਰ ਨਾਂ ਤੋਂ ਬਾਅਦ ਜੋੜੋ', suffix_ph: 'ਜਿਵੇਂ (ਦੀਵਾਲੀ 2026)',
  prefix_hint: '“Cust -” ਵਰਗਾ ਅਗੇਤਰ ਇਹਨਾਂ ਕਾਂਟੈਕਟਾਂ ਨੂੰ ਫ਼ੋਨ ਵਿੱਚ ਇਕੱਠੇ ਰੱਖਦਾ ਹੈ, ਇਸ ਲਈ WhatsApp ਬ੍ਰੌਡਕਾਸਟ ਲਿਸਟ ਲਈ ਚੁਣਨਾ ਸੌਖਾ ਹੁੰਦਾ ਹੈ।',
  h_result: '4. ਨਤੀਜਾ ਜਾਂਚੋ',
  stat_rows: 'ਲਾਈਨਾਂ', stat_contacts: 'ਤਿਆਰ ਕਾਂਟੈਕਟ', stat_invalid: 'ਗਲਤ ਨੰਬਰ', stat_dups: 'ਡੁਪਲੀਕੇਟ ਜੋੜੇ', stat_landline: 'ਲੈਂਡਲਾਈਨ', stat_noname: 'ਬਿਨਾਂ ਨਾਂ',
  filter_label: 'ਦਿਖਾਓ', filter_all: 'ਸਾਰੇ', filter_ok: 'ਤਿਆਰ', filter_warn: 'ਧਿਆਨ ਦਿਓ', filter_bad: 'ਗਲਤ',
  th_line: 'ਲਾਈਨ', th_name: 'ਨਾਂ', th_phone: 'ਨੰਬਰ', th_email: 'ਈਮੇਲ', th_company: 'ਕੰਪਨੀ', th_label: 'ਗਰੁੱਪ', th_status: 'ਸਥਿਤੀ', th_note: 'ਨੋਟ', th_title: 'ਅਹੁਦਾ', th_address: 'ਪਤਾ', th_bday: 'ਜਨਮਦਿਨ', csv_phone: 'ਫ਼ੋਨ {n}',
  st_ok: 'ਤਿਆਰ', st_landline: 'ਲੈਂਡਲਾਈਨ', st_intl: 'ਵਿਦੇਸ਼ੀ ਨੰਬਰ', st_merged: '{n} ਲਾਈਨਾਂ ਜੋੜੀਆਂ', st_noname: 'ਨਾਂ ਨਹੀਂ, ਇਸ ਲਈ ਨੰਬਰ ਹੀ ਨਾਂ', st_dropped: '{n} ਗਲਤ ਨੰਬਰ ਛੱਡੇ',
  st_landline_off: 'ਲੈਂਡਲਾਈਨ (ਤੁਹਾਡੀ ਸੈਟਿੰਗ ਅਨੁਸਾਰ ਛੱਡਿਆ)', st_intl_off: 'ਵਿਦੇਸ਼ੀ ਨੰਬਰ (ਤੁਹਾਡੀ ਸੈਟਿੰਗ ਅਨੁਸਾਰ ਛੱਡਿਆ)',
  bad_sci: 'Excel ਨੇ ਇਹ ਨੰਬਰ ਛੋਟਾ ਕਰ ਦਿੱਤਾ (9.87654E+09)। ਕਾਲਮ ਨੂੰ Text ਫ਼ਾਰਮੈਟ ਕਰਕੇ ਫਿਰ ਕਾਪੀ ਕਰੋ।', bad_len: 'ਗਲਤ ਲੰਬਾਈ: 10 ਦੀ ਥਾਂ {n} ਅੰਕ', bad_text: 'ਇਹ ਫ਼ੋਨ ਨੰਬਰ ਨਹੀਂ ਹੈ', bad_empty: 'ਨੰਬਰ ਨਹੀਂ',
  show_more: '{n} ਹੋਰ ਦਿਖਾਓ', showing: '{b} ਵਿੱਚੋਂ {a} ਦਿਸ ਰਹੇ ਹਨ', no_rows_filter: 'ਇਸ ਫ਼ਿਲਟਰ ਵਿੱਚ ਕੁਝ ਨਹੀਂ।', processing: '{n} ਲਾਈਨਾਂ ਸਾਫ਼ ਹੋ ਰਹੀਆਂ ਹਨ…',
  h_export: '5. ਡਾਊਨਲੋਡ', file_label: 'ਫ਼ਾਈਲ ਦਾ ਨਾਂ',
  dl_vcf: 'VCF ਡਾਊਨਲੋਡ (ਸਾਰੇ ਕਾਂਟੈਕਟ)', dl_csv: 'ਸਾਫ਼ CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'ਸਾਰੇ ਨੰਬਰ ਕਾਪੀ ਕਰੋ',
  split_label: 'ਇੰਨੇ-ਇੰਨੇ ਦੀਆਂ ਫ਼ਾਈਲਾਂ ਵਿੱਚ ਵੰਡੋ', split_hint: 'WhatsApp ਬ੍ਰੌਡਕਾਸਟ ਲਿਸਟ ਵਿੱਚ ਵੱਧ ਤੋਂ ਵੱਧ 256 ਲੋਕ ਹੋ ਸਕਦੇ ਹਨ (ਅਕਤੂਬਰ 2026 ਵਿੱਚ ਜਾਂਚਿਆ), ਇਸ ਲਈ 256 ਦੀਆਂ ਫ਼ਾਈਲਾਂ = ਹਰ ਫ਼ਾਈਲ ਦੀ ਇੱਕ ਲਿਸਟ।',
  dl_parts_zip: 'ਸਾਰੇ ਹਿੱਸੇ ਡਾਊਨਲੋਡ ਕਰੋ (ZIP)', part_n: 'ਹਿੱਸਾ {n}: ਕਾਂਟੈਕਟ {a}–{b}', parts_summary: '{n} ਫ਼ਾਈਲਾਂ, ਹਰ ਇੱਕ ਵਿੱਚ ਵੱਧ ਤੋਂ ਵੱਧ {m} ਕਾਂਟੈਕਟ',
  preview_title: 'VCF ਫ਼ਾਈਲ ਦੀ ਝਲਕ (ਪਹਿਲੇ 3 ਕਾਂਟੈਕਟ)', nothing_to_export: 'ਅਜੇ ਡਾਊਨਲੋਡ ਲਈ ਕੋਈ ਕਾਂਟੈਕਟ ਨਹੀਂ।', done_dl: '{name} ਡਾਊਨਲੋਡ ਹੋਈ', note_also: 'ਇਹ ਨਾਂ ਵੀ ਲਿਖਿਆ ਸੀ: {names}',
  import_tip: 'ਫ਼ੋਨ ਵਿੱਚ: .vcf ਫ਼ਾਈਲ WhatsApp ਜਾਂ ਈਮੇਲ ਰਾਹੀਂ ਆਪਣੇ ਆਪ ਨੂੰ ਭੇਜੋ, ਖੋਲ੍ਹੋ ਅਤੇ “Import contacts” ਚੁਣੋ। ਕੰਪਿਊਟਰ ਤੇ: contacts.google.com → Import → CSV ਚੁਣੋ।',
  help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ ਅਤੇ ਵਿਚਾਰ',
  help_1: 'Excel ਜਾਂ Google Sheets: ਨਾਂ ਅਤੇ ਮੋਬਾਈਲ ਦੇ ਕਾਲਮ ਸਿਰਲੇਖ ਸਮੇਤ ਚੁਣੋ, ਕਾਪੀ ਕਰੋ ਅਤੇ ਬਕਸੇ 1 ਵਿੱਚ ਪੇਸਟ ਕਰੋ। ਕਾਲਮ ਆਪਣੇ ਆਪ ਮਿਲ ਜਾਂਦੇ ਹਨ।',
  help_2: '098765-43210, +91 98765 43210 ਜਾਂ 9876543210, ਸਾਰੇ +919876543210 ਬਣ ਜਾਂਦੇ ਹਨ। ਇੱਕ ਸੈੱਲ ਵਿੱਚ ਦੋ ਨੰਬਰ (98765 43210 / 91234 56789) ਇੱਕੋ ਕਾਂਟੈਕਟ ਦੇ ਦੋ ਨੰਬਰ ਬਣਦੇ ਹਨ।',
  help_3: 'WhatsApp ਬ੍ਰੌਡਕਾਸਟ: “Diwali -” ਵਰਗਾ ਅਗੇਤਰ ਜੋੜੋ, VCF ਨੂੰ 256 ਦੇ ਹਿੱਸਿਆਂ ਵਿੱਚ ਡਾਊਨਲੋਡ ਕਰੋ, ਫ਼ੋਨ ਵਿੱਚ ਇੰਪੋਰਟ ਕਰੋ, ਫਿਰ ਬ੍ਰੌਡਕਾਸਟ ਲਿਸਟ ਵਿੱਚ “Diwali -” ਨਾਲ ਸ਼ੁਰੂ ਹੋਣ ਵਾਲੇ ਸਾਰੇ ਚੁਣੋ।',
  help_4: 'Google Contacts: Google Contacts CSV ਡਾਊਨਲੋਡ ਕਰਕੇ contacts.google.com ਤੇ ਇੰਪੋਰਟ ਕਰੋ। ਗਰੁੱਪ ਦਾ ਨਾਂ ਉੱਥੇ ਲੇਬਲ ਬਣ ਜਾਂਦਾ ਹੈ।',
  help_5: 'VCF ਤੋਂ Excel: ਫ਼ੋਨ ਤੋਂ ਕੱਢੀ .vcf ਖੋਲ੍ਹੋ, ਫਿਰ ਸਾਫ਼ CSV ਡਾਊਨਲੋਡ ਕਰਕੇ Excel ਵਿੱਚ ਖੋਲ੍ਹੋ। ਨੰਬਰ +91 ਨਾਲ ਟੈਕਸਟ ਰਹਿੰਦੇ ਹਨ, ਇਸ ਲਈ Excel ਉਹਨਾਂ ਨੂੰ ਛੋਟਾ ਨਹੀਂ ਕਰੇਗਾ।',
  help_6: 'ਪਹਿਲਾਂ ਇਜਾਜ਼ਤ ਲਓ: DPDP Act 2023 ਅਤੇ TRAI ਨਿਯਮਾਂ ਅਨੁਸਾਰ ਪ੍ਰਚਾਰ ਸਿਰਫ਼ ਸਹਿਮਤ ਗਾਹਕਾਂ ਨੂੰ ਭੇਜੋ, ਅਤੇ ਜੋ ਰੋਕਣ ਲਈ ਕਹੇ ਉਸਨੂੰ ਸੂਚੀ ਵਿੱਚੋਂ ਹਟਾ ਦਿਓ।',
  aria_table: 'ਸਾਫ਼ ਕੀਤੀ ਕਾਂਟੈਕਟ ਸੂਚੀ',
  sample_tsv: 'ਨਾਂ\tਮੋਬਾਈਲ\tਈਮੇਲ\tਕੰਪਨੀ\tਗਰੁੱਪ\nਰਮੇਸ਼ ਕੁਮਾਰ\t098765-43210\tramesh@example.com\tਕੁਮਾਰ ਕਰਿਆਨਾ ਸਟੋਰ\tਗਾਹਕ\nਪ੍ਰਿਆ ਸ਼ਰਮਾ\t+91 91234 56789\tpriya@example.com\tਸ਼ਰਮਾ ਟਿਊਸ਼ਨ\tਗਾਹਕ\nਰਮੇਸ਼ ਕੁਮਾਰ\t9876543210\t\t\tਗਾਹਕ\nਅਨਿਲ ਮਹਿਤਾ\t9.87654E+09\t\tਮਹਿਤਾ ਟ੍ਰੇਡਰਜ਼\tਸਪਲਾਇਰ\nਫ਼ਾਤਿਮਾ ਖ਼ਾਨ\t98989 89898 / 97979 79797\tfatima@example.com\tਖ਼ਾਨ ਬੁਟੀਕ\tਗਾਹਕ\nਰਾਜੇਸ਼ ਦਫ਼ਤਰ\t011-23456789\t\tਰਾਜੇਸ਼ ਐਂਡ ਸੰਨਜ਼\tਸਪਲਾਇਰ\nਸੁਨੀਤਾ ਦੇਵੀ\t12345\t\tਦੇਵੀ ਡੇਅਰੀ\tਗਾਹਕ'
};
window.APP_STRINGS.or = {
  app_title: 'Excel ରୁ କଣ୍ଟାକ୍ଟ (VCF)',
  intro: 'Excel ବା Google Sheets ରୁ ଗ୍ରାହକ ତାଲିକା ପେଷ୍ଟ କରନ୍ତୁ, ମୋବାଇଲ ନମ୍ବର ସଫା କରନ୍ତୁ ଏବଂ ଯେକୌଣସି ଫୋନରେ ସିଧା ଇମ୍ପୋର୍ଟ ହେଉଥିବା VCF ଫାଇଲ ଡାଉନଲୋଡ କରନ୍ତୁ, କିମ୍ବା Google Contacts CSV ତିଆରି କରନ୍ତୁ। VCF କୁ ପୁଣି Excel ପାଇଁ CSV ମଧ୍ୟ କରିହେବ।',
  privacy: 'ଆପଣଙ୍କ ଗ୍ରାହକ ତାଲିକା ଏହି ଡିଭାଇସ ବାହାରକୁ ଯାଏ ନାହିଁ: କିଛି ଅପଲୋଡ ହୁଏ ନାହିଁ। ଭାରତର DPDP Act 2023 ଅନୁସାରେ ଗ୍ରାହକଙ୍କ ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ ସୁରକ୍ଷିତ ରଖିବା ଆପଣଙ୍କ ଦାୟିତ୍ୱ, ତେଣୁ ଏହି ଫାଇଲ କେବଳ ଦରକାରୀ ଲୋକଙ୍କ ସହ ସେୟାର କରନ୍ତୁ ଏବଂ କାମ ସରିଲେ ଡିଲିଟ କରନ୍ତୁ।',
  h_input: '1. ତାଲିକା ପେଷ୍ଟ କରନ୍ତୁ ବା ଖୋଲନ୍ତୁ',
  paste_label: 'Excel, Google Sheets ବା କୌଣସି CSV ରୁ ଏଠାରେ ପେଷ୍ଟ କରନ୍ତୁ (ଗୋଟିଏ ଲାଇନରେ ଜଣେ)',
  paste_ph: 'ନାମ    ମୋବାଇଲ    ଇମେଲ    କମ୍ପାନୀ    ଗ୍ରୁପ\nରମେଶ କୁମାର    98765 43210    ramesh@example.com    କୁମାର କିରାଣା    ଗ୍ରାହକ',
  open_csv: 'CSV / TXT ଫାଇଲ ଖୋଲନ୍ତୁ', open_vcf: 'VCF ଫାଇଲ ଖୋଲନ୍ତୁ', load_example: 'ଉଦାହରଣ ଭରନ୍ତୁ',
  example_note: 'ଏହା କାଳ୍ପନିକ ନମ୍ବର ଥିବା ଉଦାହରଣ। ଏହା ବଦଳରେ ନିଜ ତାଲିକା ପେଷ୍ଟ କରନ୍ତୁ।',
  excel_tip: 'ଟିପ୍ସ: Excel ବା Google Sheets ରେ ଶୀର୍ଷକ ଲାଇନ ସହ କଲମ ବାଛନ୍ତୁ, କପି କରି ଏଠାରେ ପେଷ୍ଟ କରନ୍ତୁ। ନମ୍ବର 9.87654E+09 ପରି ଦେଖାଗଲେ ପ୍ରଥମେ ସେହି କଲମକୁ Text ଫର୍ମାଟ କରି ପୁଣି କପି କରନ୍ତୁ।',
  lines_read: '{n}ଟି ଲାଇନ ପଢ଼ାଗଲା', vcf_read: 'VCF ଫାଇଲରୁ {n}ଟି କଣ୍ଟାକ୍ଟ ପଢ଼ି ତାଲିକାରେ ରଖାଗଲା।', dl_vcf_csv: 'ଏଗୁଡ଼ିକୁ CSV ଭାବେ ଡାଉନଲୋଡ କରନ୍ତୁ',
  bad_file: 'ଏହି ଫାଇଲ ପଢ଼ିହେଲା ନାହିଁ। .csv, .txt ବା .vcf ଫାଇଲ ବାଛନ୍ତୁ।', empty_list: 'ଆରମ୍ଭ କରିବାକୁ ଉପରେ ଆପଣଙ୍କ ତାଲିକା ପେଷ୍ଟ କରନ୍ତୁ।',
  h_map: '2. କେଉଁ କଲମ କଣ?', map_hint: 'ଆପଣଙ୍କ ତଥ୍ୟରୁ ଅନୁମାନ କରାଯାଇଛି। ଭୁଲ ହେଲେ ବାକ୍ସ ବଦଳାନ୍ତୁ।', has_header: 'ପ୍ରଥମ ଲାଇନଟି ଶୀର୍ଷକ',
  col_name: 'ନାମ', col_last: 'ସାଙ୍ଗିଆ (ଇଚ୍ଛାଧୀନ)', col_phone: 'ମୋବାଇଲ / ଫୋନ', col_phone2: 'ଦ୍ୱିତୀୟ ଫୋନ (ଇଚ୍ଛାଧୀନ)', col_email: 'ଇମେଲ', col_company: 'କମ୍ପାନୀ / ଦୋକାନ', col_label: 'ଗ୍ରୁପ / ଲେବଲ', col_note: 'ନୋଟ',
  none_opt: '— କିଛି ନାହିଁ —', col_n: 'କଲମ {n}',
  h_clean: '3. ସଫା କରିବା ବିକଳ୍ପ', cc_label: 'ଦେଶ କୋଡ ନଥିବା ନମ୍ବର ପାଇଁ କୋଡ', cc_hint: 'ଭାରତ 91 · UAE 971 · ନେପାଳ 977 · ବାଂଲାଦେଶ 880 · ଶ୍ରୀଲଙ୍କା 94',
  opt_title: 'ନାମର ବଡ଼-ଛୋଟ ଅକ୍ଷର ଠିକ କରନ୍ତୁ (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'ସମାନ ନମ୍ବରର ଡୁପ୍ଲିକେଟ ଲାଇନ ଗୋଟିଏ କଣ୍ଟାକ୍ଟରେ ମିଶାନ୍ତୁ',
  opt_landline: 'ଲ୍ୟାଣ୍ଡଲାଇନ ନମ୍ବର ରଖନ୍ତୁ (⚠ ଚିହ୍ନ ସହ)', opt_intl: 'ବିଦେଶୀ ନମ୍ବର ରଖନ୍ତୁ (🌐 ଚିହ୍ନ ସହ)',
  prefix_label: 'ପ୍ରତି ନାମ ଆଗରେ ଯୋଡ଼ନ୍ତୁ', prefix_ph: 'ଯେପରି Cust -', suffix_label: 'ପ୍ରତି ନାମ ପରେ ଯୋଡ଼ନ୍ତୁ', suffix_ph: 'ଯେପରି (ଦୀପାବଳି 2026)',
  prefix_hint: '“Cust -” ପରି ଉପସର୍ଗ ଏହି କଣ୍ଟାକ୍ଟଗୁଡ଼ିକୁ ଫୋନରେ ଏକାଠି ରଖେ, ତେଣୁ WhatsApp ବ୍ରଡକାଷ୍ଟ ଲିଷ୍ଟ ପାଇଁ ବାଛିବା ସହଜ ହୁଏ।',
  h_result: '4. ଫଳାଫଳ ଦେଖନ୍ତୁ',
  stat_rows: 'ଲାଇନ', stat_contacts: 'ପ୍ରସ୍ତୁତ କଣ୍ଟାକ୍ଟ', stat_invalid: 'ଭୁଲ ନମ୍ବର', stat_dups: 'ଡୁପ୍ଲିକେଟ ମିଶାଗଲା', stat_landline: 'ଲ୍ୟାଣ୍ଡଲାଇନ', stat_noname: 'ନାମ ବିନା',
  filter_label: 'ଦେଖାନ୍ତୁ', filter_all: 'ସବୁ', filter_ok: 'ପ୍ରସ୍ତୁତ', filter_warn: 'ଧ୍ୟାନ ଦିଅନ୍ତୁ', filter_bad: 'ଭୁଲ',
  th_line: 'ଲାଇନ', th_name: 'ନାମ', th_phone: 'ନମ୍ବର', th_email: 'ଇମେଲ', th_company: 'କମ୍ପାନୀ', th_label: 'ଗ୍ରୁପ', th_status: 'ସ୍ଥିତି', th_note: 'ନୋଟ', th_title: 'ପଦବୀ', th_address: 'ଠିକଣା', th_bday: 'ଜନ୍ମଦିନ', csv_phone: 'ଫୋନ {n}',
  st_ok: 'ପ୍ରସ୍ତୁତ', st_landline: 'ଲ୍ୟାଣ୍ଡଲାଇନ', st_intl: 'ବିଦେଶୀ ନମ୍ବର', st_merged: '{n}ଟି ଲାଇନ ମିଶାଗଲା', st_noname: 'ନାମ ନାହିଁ, ତେଣୁ ନମ୍ବର ହିଁ ନାମ', st_dropped: '{n}ଟି ଭୁଲ ନମ୍ବର ବାଦ ଦିଆଗଲା',
  st_landline_off: 'ଲ୍ୟାଣ୍ଡଲାଇନ (ଆପଣଙ୍କ ସେଟିଂ ଅନୁସାରେ ବାଦ)', st_intl_off: 'ବିଦେଶୀ ନମ୍ବର (ଆପଣଙ୍କ ସେଟିଂ ଅନୁସାରେ ବାଦ)',
  bad_sci: 'Excel ଏହି ନମ୍ବରକୁ ଛୋଟ କରିଦେଲା (9.87654E+09)। କଲମକୁ Text ଫର୍ମାଟ କରି ପୁଣି କପି କରନ୍ତୁ।', bad_len: 'ଭୁଲ ଲମ୍ବ: 10 ବଦଳରେ {n} ଅଙ୍କ', bad_text: 'ଏହା ଫୋନ ନମ୍ବର ନୁହେଁ', bad_empty: 'ନମ୍ବର ନାହିଁ',
  show_more: 'ଆଉ {n}ଟି ଦେଖାନ୍ତୁ', showing: '{b} ମଧ୍ୟରୁ {a} ଦେଖାଯାଉଛି', no_rows_filter: 'ଏହି ଫିଲ୍ଟରରେ କିଛି ନାହିଁ।', processing: '{n}ଟି ଲାଇନ ସଫା ହେଉଛି…',
  h_export: '5. ଡାଉନଲୋଡ', file_label: 'ଫାଇଲ ନାମ',
  dl_vcf: 'VCF ଡାଉନଲୋଡ (ସବୁ କଣ୍ଟାକ୍ଟ)', dl_csv: 'ସଫା CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'ସବୁ ନମ୍ବର କପି କରନ୍ତୁ',
  split_label: 'ଏତେ ଜଣିଆ ଫାଇଲରେ ଭାଗ କରନ୍ତୁ', split_hint: 'WhatsApp ବ୍ରଡକାଷ୍ଟ ଲିଷ୍ଟରେ ସର୍ବାଧିକ 256 ଜଣ ରହିପାରିବେ (ଅକ୍ଟୋବର 2026 ରେ ଯାଞ୍ଚ), ତେଣୁ 256 ର ଫାଇଲ = ପ୍ରତି ଫାଇଲରେ ଗୋଟିଏ ଲିଷ୍ଟ।',
  dl_parts_zip: 'ସବୁ ଭାଗ ଡାଉନଲୋଡ କରନ୍ତୁ (ZIP)', part_n: 'ଭାଗ {n}: କଣ୍ଟାକ୍ଟ {a}–{b}', parts_summary: '{n}ଟି ଫାଇଲ, ପ୍ରତ୍ୟେକରେ ସର୍ବାଧିକ {m}ଟି କଣ୍ଟାକ୍ଟ',
  preview_title: 'VCF ଫାଇଲର ଝଲକ (ପ୍ରଥମ 3ଟି କଣ୍ଟାକ୍ଟ)', nothing_to_export: 'ଏବେ ଡାଉନଲୋଡ ପାଇଁ କୌଣସି କଣ୍ଟାକ୍ଟ ନାହିଁ।', done_dl: '{name} ଡାଉନଲୋଡ ହେଲା', note_also: 'ଏହି ନାମ ମଧ୍ୟ ଲେଖାଥିଲା: {names}',
  import_tip: 'ଫୋନରେ: .vcf ଫାଇଲ WhatsApp ବା ଇମେଲରେ ନିଜକୁ ପଠାନ୍ତୁ, ଖୋଲି “Import contacts” ବାଛନ୍ତୁ। କମ୍ପ୍ୟୁଟରରେ: contacts.google.com → Import → CSV ବାଛନ୍ତୁ।',
  help_title: 'କିପରି ବ୍ୟବହାର କରିବେ ଓ ଆଇଡିଆ',
  help_1: 'Excel ବା Google Sheets: ନାମ ଓ ମୋବାଇଲ କଲମ ଶୀର୍ଷକ ସହ ବାଛି କପି କରନ୍ତୁ ଏବଂ ବାକ୍ସ 1 ରେ ପେଷ୍ଟ କରନ୍ତୁ। କଲମ ନିଜେ ମେଳ ହୋଇଯାଏ।',
  help_2: '098765-43210, +91 98765 43210 ବା 9876543210, ସବୁ +919876543210 ହୋଇଯାଏ। ଗୋଟିଏ ସେଲରେ ଦୁଇଟି ନମ୍ବର (98765 43210 / 91234 56789) ସମାନ କଣ୍ଟାକ୍ଟର ଦୁଇଟି ନମ୍ବର ହୁଏ।',
  help_3: 'WhatsApp ବ୍ରଡକାଷ୍ଟ: “Diwali -” ପରି ଉପସର୍ଗ ଯୋଡ଼ନ୍ତୁ, VCF କୁ 256 ର ଭାଗରେ ଡାଉନଲୋଡ କରି ଫୋନରେ ଇମ୍ପୋର୍ଟ କରନ୍ତୁ, ତାପରେ ବ୍ରଡକାଷ୍ଟ ଲିଷ୍ଟରେ “Diwali -” ରୁ ଆରମ୍ଭ ହେଉଥିବା ସମସ୍ତଙ୍କୁ ବାଛନ୍ତୁ।',
  help_4: 'Google Contacts: Google Contacts CSV ଡାଉନଲୋଡ କରି contacts.google.com ରେ ଇମ୍ପୋର୍ଟ କରନ୍ତୁ। ଗ୍ରୁପ ନାମ ସେଠାରେ ଲେବଲ ହୋଇଯାଏ।',
  help_5: 'VCF ରୁ Excel: ଫୋନରୁ ବାହାର କରିଥିବା .vcf ଖୋଲନ୍ତୁ, ତାପରେ ସଫା CSV ଡାଉନଲୋଡ କରି Excel ରେ ଖୋଲନ୍ତୁ। ନମ୍ବର +91 ସହ ଟେକ୍ସଟ ରହେ, ତେଣୁ Excel ଛୋଟ କରିବ ନାହିଁ।',
  help_6: 'ପ୍ରଥମେ ଅନୁମତି ନିଅନ୍ତୁ: DPDP Act 2023 ଓ TRAI ନିୟମ ଅନୁସାରେ କେବଳ ରାଜି ହୋଇଥିବା ଗ୍ରାହକଙ୍କୁ ପ୍ରଚାର ପଠାନ୍ତୁ, ଏବଂ ବନ୍ଦ କରିବାକୁ କହୁଥିବାଙ୍କୁ ତାଲିକାରୁ ହଟାନ୍ତୁ।',
  aria_table: 'ସଫା କଣ୍ଟାକ୍ଟ ତାଲିକା',
  sample_tsv: 'ନାମ\tମୋବାଇଲ\tଇମେଲ\tକମ୍ପାନୀ\tଗ୍ରୁପ\nରମେଶ କୁମାର\t098765-43210\tramesh@example.com\tକୁମାର କିରାଣା ଷ୍ଟୋର\tଗ୍ରାହକ\nପ୍ରିୟା ଶର୍ମା\t+91 91234 56789\tpriya@example.com\tଶର୍ମା ଟ୍ୟୁସନ\tଗ୍ରାହକ\nରମେଶ କୁମାର\t9876543210\t\t\tଗ୍ରାହକ\nଅନିଲ ମେହେଟା\t9.87654E+09\t\tମେହେଟା ଟ୍ରେଡର୍ସ\tଯୋଗାଣକାରୀ\nଫାତିମା ଖାନ\t98989 89898 / 97979 79797\tfatima@example.com\tଖାନ ବୁଟିକ\tଗ୍ରାହକ\nରାଜେଶ ଅଫିସ\t011-23456789\t\tରାଜେଶ ଆଣ୍ଡ ସନ୍ସ\tଯୋଗାଣକାରୀ\nସୁନୀତା ଦେବୀ\t12345\t\tଦେବୀ ଡେରି\tଗ୍ରାହକ'
};
window.APP_STRINGS.ta = {
  app_title: 'Excel இலிருந்து தொடர்புகள் (VCF)',
  intro: 'Excel அல்லது Google Sheets இலிருந்து வாடிக்கையாளர் பட்டியலை ஒட்டுங்கள், மொபைல் எண்களைச் சரிசெய்து எந்த போனிலும் நேரடியாக இறக்குமதி ஆகும் VCF கோப்பைப் பதிவிறக்குங்கள், அல்லது Google Contacts CSV உருவாக்குங்கள். VCF ஐ மீண்டும் Excel க்கான CSV ஆகவும் மாற்றலாம்.',
  privacy: 'உங்கள் வாடிக்கையாளர் பட்டியல் இந்தச் சாதனத்தை விட்டு வெளியே போகாது: எதுவும் பதிவேற்றப்படாது. இந்தியாவின் DPDP Act 2023 படி வாடிக்கையாளர்களின் தனிப்பட்ட தரவைப் பாதுகாப்பது உங்கள் பொறுப்பு, எனவே இந்தக் கோப்புகளைத் தேவையானவர்களுடன் மட்டும் பகிர்ந்து, வேலை முடிந்ததும் நீக்குங்கள்.',
  h_input: '1. பட்டியலை ஒட்டவும் அல்லது திறக்கவும்',
  paste_label: 'Excel, Google Sheets அல்லது எந்த CSV இலிருந்தும் இங்கே ஒட்டுங்கள் (ஒரு வரியில் ஒருவர்)',
  paste_ph: 'பெயர்    மொபைல்    மின்னஞ்சல்    நிறுவனம்    குழு\nரமேஷ் குமார்    98765 43210    ramesh@example.com    குமார் மளிகை    வாடிக்கையாளர்',
  open_csv: 'CSV / TXT கோப்பைத் திற', open_vcf: 'VCF கோப்பைத் திற', load_example: 'உதாரணம் நிரப்பு',
  example_note: 'இது கற்பனை எண்கள் கொண்ட உதாரணம். இதற்குப் பதில் உங்கள் பட்டியலை ஒட்டுங்கள்.',
  excel_tip: 'குறிப்பு: Excel அல்லது Google Sheets இல் தலைப்பு வரியுடன் நெடுவரிசைகளைத் தேர்ந்தெடுத்து, நகலெடுத்து இங்கே ஒட்டுங்கள். எண் 9.87654E+09 போலத் தெரிந்தால், முதலில் அந்த நெடுவரிசையை Text ஆக வடிவமைத்து மீண்டும் நகலெடுங்கள்.',
  lines_read: '{n} வரிகள் படிக்கப்பட்டன', vcf_read: 'VCF கோப்பிலிருந்து {n} தொடர்புகள் படிக்கப்பட்டுப் பட்டியலில் வைக்கப்பட்டன.', dl_vcf_csv: 'இவற்றை CSV ஆகப் பதிவிறக்கு',
  bad_file: 'இந்தக் கோப்பைப் படிக்க முடியவில்லை. .csv, .txt அல்லது .vcf கோப்பைத் தேர்ந்தெடுங்கள்.', empty_list: 'தொடங்க மேலே உங்கள் பட்டியலை ஒட்டுங்கள்.',
  h_map: '2. எந்த நெடுவரிசை எது?', map_hint: 'உங்கள் தரவைப் பார்த்து ஊகிக்கப்பட்டது. தவறு என்றால் பெட்டியை மாற்றுங்கள்.', has_header: 'முதல் வரி தலைப்பு',
  col_name: 'பெயர்', col_last: 'குடும்பப் பெயர் (விருப்பம்)', col_phone: 'மொபைல் / போன்', col_phone2: 'இரண்டாவது போன் (விருப்பம்)', col_email: 'மின்னஞ்சல்', col_company: 'நிறுவனம் / கடை', col_label: 'குழு / லேபிள்', col_note: 'குறிப்பு',
  none_opt: '— எதுவும் இல்லை —', col_n: 'நெடுவரிசை {n}',
  h_clean: '3. சுத்தம் செய்யும் விருப்பங்கள்', cc_label: 'நாட்டுக் குறியீடு இல்லாத எண்களுக்கான குறியீடு', cc_hint: 'இந்தியா 91 · UAE 971 · நேபாளம் 977 · வங்கதேசம் 880 · இலங்கை 94',
  opt_title: 'பெயர்களின் பெரிய-சிறிய எழுத்துகளைச் சரிசெய் (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'ஒரே எண்ணின் நகல் வரிகளை ஒரு தொடர்பாக இணை',
  opt_landline: 'லேண்ட்லைன் எண்களை வைத்திரு (⚠ குறியுடன்)', opt_intl: 'வெளிநாட்டு எண்களை வைத்திரு (🌐 குறியுடன்)',
  prefix_label: 'ஒவ்வொரு பெயருக்கும் முன் சேர்', prefix_ph: 'எ.கா. Cust -', suffix_label: 'ஒவ்வொரு பெயருக்கும் பின் சேர்', suffix_ph: 'எ.கா. (தீபாவளி 2026)',
  prefix_hint: '“Cust -” போன்ற முன்னொட்டு இந்தத் தொடர்புகளை போனில் ஒன்றாக வைக்கும், அதனால் WhatsApp ஒளிபரப்புப் பட்டியலுக்குத் தேர்வு செய்வது எளிது.',
  h_result: '4. முடிவைச் சரிபாருங்கள்',
  stat_rows: 'வரிகள்', stat_contacts: 'தயார் தொடர்புகள்', stat_invalid: 'தவறான எண்கள்', stat_dups: 'இணைத்த நகல்கள்', stat_landline: 'லேண்ட்லைன்', stat_noname: 'பெயர் இல்லாதவை',
  filter_label: 'காட்டு', filter_all: 'அனைத்தும்', filter_ok: 'தயார்', filter_warn: 'கவனிக்க', filter_bad: 'தவறு',
  th_line: 'வரி', th_name: 'பெயர்', th_phone: 'எண்(கள்)', th_email: 'மின்னஞ்சல்', th_company: 'நிறுவனம்', th_label: 'குழு', th_status: 'நிலை', th_note: 'குறிப்பு', th_title: 'பதவி', th_address: 'முகவரி', th_bday: 'பிறந்தநாள்', csv_phone: 'போன் {n}',
  st_ok: 'தயார்', st_landline: 'லேண்ட்லைன்', st_intl: 'வெளிநாட்டு எண்', st_merged: '{n} வரிகள் இணைக்கப்பட்டன', st_noname: 'பெயர் இல்லை, அதனால் எண்ணே பெயர்', st_dropped: '{n} தவறான எண்கள் விடப்பட்டன',
  st_landline_off: 'லேண்ட்லைன் (உங்கள் அமைப்பின்படி விடப்பட்டது)', st_intl_off: 'வெளிநாட்டு எண் (உங்கள் அமைப்பின்படி விடப்பட்டது)',
  bad_sci: 'Excel இந்த எண்ணைச் சுருக்கிவிட்டது (9.87654E+09). நெடுவரிசையை Text ஆக வடிவமைத்து மீண்டும் நகலெடுங்கள்.', bad_len: 'தவறான நீளம்: 10 க்குப் பதில் {n} இலக்கங்கள்', bad_text: 'இது போன் எண் அல்ல', bad_empty: 'எண் இல்லை',
  show_more: 'மேலும் {n} காட்டு', showing: '{b} இல் {a} காட்டப்படுகிறது', no_rows_filter: 'இந்த வடிகட்டியில் எதுவும் இல்லை.', processing: '{n} வரிகள் சுத்தம் செய்யப்படுகின்றன…',
  h_export: '5. பதிவிறக்கம்', file_label: 'கோப்பின் பெயர்',
  dl_vcf: 'VCF பதிவிறக்கு (அனைத்துத் தொடர்புகளும்)', dl_csv: 'சுத்தமான CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'அனைத்து எண்களையும் நகலெடு',
  split_label: 'இத்தனை பேர் கொண்ட கோப்புகளாகப் பிரி', split_hint: 'WhatsApp ஒளிபரப்புப் பட்டியலில் அதிகபட்சம் 256 பேர் இருக்கலாம் (அக்டோபர் 2026 இல் சரிபார்த்தது), அதனால் 256 கோப்பு = ஒரு கோப்புக்கு ஒரு பட்டியல்.',
  dl_parts_zip: 'அனைத்துப் பகுதிகளையும் பதிவிறக்கு (ZIP)', part_n: 'பகுதி {n}: தொடர்புகள் {a}–{b}', parts_summary: '{n} கோப்புகள், ஒவ்வொன்றிலும் அதிகபட்சம் {m} தொடர்புகள்',
  preview_title: 'VCF கோப்பின் முன்னோட்டம் (முதல் 3 தொடர்புகள்)', nothing_to_export: 'பதிவிறக்க இன்னும் தொடர்புகள் இல்லை.', done_dl: '{name} பதிவிறக்கப்பட்டது', note_also: 'இந்தப் பெயரும் எழுதப்பட்டிருந்தது: {names}',
  import_tip: 'போனில்: .vcf கோப்பை WhatsApp அல்லது மின்னஞ்சலில் உங்களுக்கே அனுப்பி, திறந்து “Import contacts” தேர்ந்தெடுங்கள். கணினியில்: contacts.google.com → Import → CSV தேர்ந்தெடுங்கள்.',
  help_title: 'பயன்படுத்துவது எப்படி & யோசனைகள்',
  help_1: 'Excel அல்லது Google Sheets: பெயர், மொபைல் நெடுவரிசைகளைத் தலைப்பு வரியுடன் தேர்ந்தெடுத்து, நகலெடுத்து, பெட்டி 1 இல் ஒட்டுங்கள். நெடுவரிசைகள் தானாகப் பொருந்தும்.',
  help_2: '098765-43210, +91 98765 43210 அல்லது 9876543210 எல்லாம் +919876543210 ஆகும். ஒரு செல்லில் இரண்டு எண்கள் (98765 43210 / 91234 56789) ஒரே தொடர்பின் இரண்டு எண்களாகும்.',
  help_3: 'WhatsApp ஒளிபரப்பு: “Diwali -” போன்ற முன்னொட்டைச் சேர்த்து, VCF ஐ 256 பகுதிகளாகப் பதிவிறக்கி போனில் இறக்குமதி செய்யுங்கள், பிறகு ஒளிபரப்புப் பட்டியலில் “Diwali -” என்று தொடங்கும் அனைவரையும் தேர்ந்தெடுங்கள்.',
  help_4: 'Google Contacts: Google Contacts CSV ஐப் பதிவிறக்கி contacts.google.com இல் இறக்குமதி செய்யுங்கள். குழுப் பெயர் அங்கே லேபிள் ஆகும்.',
  help_5: 'VCF இலிருந்து Excel: போனிலிருந்து எடுத்த .vcf ஐத் திறந்து, சுத்தமான CSV ஐப் பதிவிறக்கி Excel இல் திறங்கள். எண்கள் +91 உடன் உரையாக இருப்பதால் Excel சுருக்காது.',
  help_6: 'முதலில் அனுமதி பெறுங்கள்: DPDP Act 2023 மற்றும் TRAI விதிகளின்படி சம்மதித்த வாடிக்கையாளர்களுக்கு மட்டும் விளம்பரம் அனுப்புங்கள், நிறுத்தச் சொல்பவர்களைப் பட்டியலிலிருந்து நீக்குங்கள்.',
  aria_table: 'சுத்தம் செய்த தொடர்புப் பட்டியல்',
  sample_tsv: 'பெயர்\tமொபைல்\tமின்னஞ்சல்\tநிறுவனம்\tகுழு\nரமேஷ் குமார்\t098765-43210\tramesh@example.com\tகுமார் மளிகைக் கடை\tவாடிக்கையாளர்\nபிரியா சர்மா\t+91 91234 56789\tpriya@example.com\tசர்மா டியூஷன்\tவாடிக்கையாளர்\nரமேஷ் குமார்\t9876543210\t\t\tவாடிக்கையாளர்\nஅனில் மேத்தா\t9.87654E+09\t\tமேத்தா டிரேடர்ஸ்\tசப்ளையர்\nபாத்திமா கான்\t98989 89898 / 97979 79797\tfatima@example.com\tகான் பூட்டிக்\tவாடிக்கையாளர்\nராஜேஷ் அலுவலகம்\t011-23456789\t\tராஜேஷ் அண்ட் சன்ஸ்\tசப்ளையர்\nசுனிதா தேவி\t12345\t\tதேவி பால் பண்ணை\tவாடிக்கையாளர்'
};
window.APP_STRINGS.te = {
  app_title: 'Excel నుంచి కాంటాక్ట్‌లు (VCF)',
  intro: 'Excel లేదా Google Sheets నుంచి కస్టమర్ జాబితాను పేస్ట్ చేయండి, మొబైల్ నంబర్లు సరిచేసి ఏ ఫోన్‌లోనైనా నేరుగా ఇంపోర్ట్ అయ్యే VCF ఫైల్ డౌన్‌లోడ్ చేయండి, లేదా Google Contacts CSV తయారు చేయండి. VCF ను తిరిగి Excel కోసం CSV గా కూడా మార్చవచ్చు.',
  privacy: 'మీ కస్టమర్ జాబితా ఈ పరికరం దాటి వెళ్లదు: ఏదీ అప్‌లోడ్ కాదు. భారతదేశ DPDP Act 2023 ప్రకారం కస్టమర్ల వ్యక్తిగత డేటాను కాపాడటం మీ బాధ్యత, కాబట్టి ఈ ఫైల్‌లను అవసరమైన వారితో మాత్రమే పంచుకోండి, పని అయ్యాక తొలగించండి.',
  h_input: '1. జాబితాను పేస్ట్ చేయండి లేదా తెరవండి',
  paste_label: 'Excel, Google Sheets లేదా ఏ CSV నుంచైనా ఇక్కడ పేస్ట్ చేయండి (ఒక లైన్‌లో ఒకరు)',
  paste_ph: 'పేరు    మొబైల్    ఈమెయిల్    కంపెనీ    గ్రూప్\nరమేష్ కుమార్    98765 43210    ramesh@example.com    కుమార్ కిరాణా    కస్టమర్',
  open_csv: 'CSV / TXT ఫైల్ తెరవండి', open_vcf: 'VCF ఫైల్ తెరవండి', load_example: 'ఉదాహరణ నింపండి',
  example_note: 'ఇది కల్పిత నంబర్లతో ఉదాహరణ. దీని బదులు మీ జాబితాను పేస్ట్ చేయండి.',
  excel_tip: 'చిట్కా: Excel లేదా Google Sheets లో శీర్షిక లైన్‌తో కలిపి కాలమ్‌లను ఎంచుకుని, కాపీ చేసి ఇక్కడ పేస్ట్ చేయండి. నంబర్ 9.87654E+09 లా కనిపిస్తే, ముందు ఆ కాలమ్‌ను Text గా ఫార్మాట్ చేసి మళ్లీ కాపీ చేయండి.',
  lines_read: '{n} లైన్‌లు చదివాం', vcf_read: 'VCF ఫైల్ నుంచి {n} కాంటాక్ట్‌లు చదివి జాబితాలో పెట్టాం.', dl_vcf_csv: 'వీటిని CSV గా డౌన్‌లోడ్ చేయండి',
  bad_file: 'ఈ ఫైల్ చదవలేకపోయాం. .csv, .txt లేదా .vcf ఫైల్ ఎంచుకోండి.', empty_list: 'మొదలుపెట్టడానికి పైన మీ జాబితాను పేస్ట్ చేయండి.',
  h_map: '2. ఏ కాలమ్ ఏమిటి?', map_hint: 'మీ డేటా చూసి ఊహించాం. తప్పైతే బాక్స్ మార్చండి.', has_header: 'మొదటి లైన్ శీర్షిక',
  col_name: 'పేరు', col_last: 'ఇంటి పేరు (ఐచ్ఛికం)', col_phone: 'మొబైల్ / ఫోన్', col_phone2: 'రెండో ఫోన్ (ఐచ్ఛికం)', col_email: 'ఈమెయిల్', col_company: 'కంపెనీ / దుకాణం', col_label: 'గ్రూప్ / లేబుల్', col_note: 'నోట్',
  none_opt: '— ఏదీ లేదు —', col_n: 'కాలమ్ {n}',
  h_clean: '3. శుభ్రం చేసే ఎంపికలు', cc_label: 'దేశ కోడ్ లేని నంబర్లకు కోడ్', cc_hint: 'భారత్ 91 · UAE 971 · నేపాల్ 977 · బంగ్లాదేశ్ 880 · శ్రీలంక 94',
  opt_title: 'పేర్లలో పెద్ద-చిన్న అక్షరాలు సరిచేయండి (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'ఒకే నంబర్ ఉన్న నకలు లైన్‌లను ఒక కాంటాక్ట్‌గా కలపండి',
  opt_landline: 'ల్యాండ్‌లైన్ నంబర్లు ఉంచండి (⚠ గుర్తుతో)', opt_intl: 'విదేశీ నంబర్లు ఉంచండి (🌐 గుర్తుతో)',
  prefix_label: 'ప్రతి పేరు ముందు చేర్చండి', prefix_ph: 'ఉదా. Cust -', suffix_label: 'ప్రతి పేరు తర్వాత చేర్చండి', suffix_ph: 'ఉదా. (దీపావళి 2026)',
  prefix_hint: '“Cust -” లాంటి ఉపసర్గ ఈ కాంటాక్ట్‌లను ఫోన్‌లో కలిపి ఉంచుతుంది, దాంతో WhatsApp బ్రాడ్‌కాస్ట్ లిస్ట్ కోసం ఎంచుకోవడం సులువు.',
  h_result: '4. ఫలితం చూడండి',
  stat_rows: 'లైన్‌లు', stat_contacts: 'సిద్ధమైన కాంటాక్ట్‌లు', stat_invalid: 'తప్పు నంబర్లు', stat_dups: 'కలిపిన నకళ్లు', stat_landline: 'ల్యాండ్‌లైన్', stat_noname: 'పేరు లేనివి',
  filter_label: 'చూపించు', filter_all: 'అన్నీ', filter_ok: 'సిద్ధం', filter_warn: 'గమనించండి', filter_bad: 'తప్పు',
  th_line: 'లైన్', th_name: 'పేరు', th_phone: 'నంబర్(లు)', th_email: 'ఈమెయిల్', th_company: 'కంపెనీ', th_label: 'గ్రూప్', th_status: 'స్థితి', th_note: 'నోట్', th_title: 'హోదా', th_address: 'చిరునామా', th_bday: 'పుట్టినరోజు', csv_phone: 'ఫోన్ {n}',
  st_ok: 'సిద్ధం', st_landline: 'ల్యాండ్‌లైన్', st_intl: 'విదేశీ నంబర్', st_merged: '{n} లైన్‌లు కలిపాం', st_noname: 'పేరు లేదు, కాబట్టి నంబరే పేరు', st_dropped: '{n} తప్పు నంబర్లు వదిలేశాం',
  st_landline_off: 'ల్యాండ్‌లైన్ (మీ సెట్టింగ్ ప్రకారం వదిలేశాం)', st_intl_off: 'విదేశీ నంబర్ (మీ సెట్టింగ్ ప్రకారం వదిలేశాం)',
  bad_sci: 'Excel ఈ నంబర్‌ను కుదించింది (9.87654E+09). కాలమ్‌ను Text గా ఫార్మాట్ చేసి మళ్లీ కాపీ చేయండి.', bad_len: 'తప్పు పొడవు: 10 బదులు {n} అంకెలు', bad_text: 'ఇది ఫోన్ నంబర్ కాదు', bad_empty: 'నంబర్ లేదు',
  show_more: 'ఇంకా {n} చూపించు', showing: '{b} లో {a} చూపిస్తున్నాం', no_rows_filter: 'ఈ ఫిల్టర్‌లో ఏమీ లేదు.', processing: '{n} లైన్‌లు శుభ్రం అవుతున్నాయి…',
  h_export: '5. డౌన్‌లోడ్', file_label: 'ఫైల్ పేరు',
  dl_vcf: 'VCF డౌన్‌లోడ్ (అన్ని కాంటాక్ట్‌లు)', dl_csv: 'శుభ్రమైన CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'అన్ని నంబర్లు కాపీ చేయండి',
  split_label: 'ఇంతమంది చొప్పున ఫైల్‌లుగా విభజించండి', split_hint: 'WhatsApp బ్రాడ్‌కాస్ట్ లిస్ట్‌లో గరిష్ఠంగా 256 మంది ఉండవచ్చు (అక్టోబర్ 2026 లో చూశాం), కాబట్టి 256 ఫైల్ = ఒక్కో ఫైల్‌కు ఒక లిస్ట్.',
  dl_parts_zip: 'అన్ని భాగాలు డౌన్‌లోడ్ (ZIP)', part_n: 'భాగం {n}: కాంటాక్ట్‌లు {a}–{b}', parts_summary: '{n} ఫైల్‌లు, ఒక్కోదానిలో గరిష్ఠంగా {m} కాంటాక్ట్‌లు',
  preview_title: 'VCF ఫైల్ ప్రివ్యూ (మొదటి 3 కాంటాక్ట్‌లు)', nothing_to_export: 'డౌన్‌లోడ్ చేయడానికి ఇంకా కాంటాక్ట్‌లు లేవు.', done_dl: '{name} డౌన్‌లోడ్ అయింది', note_also: 'ఈ పేరుతో కూడా ఉంది: {names}',
  import_tip: 'ఫోన్‌లో: .vcf ఫైల్‌ను WhatsApp లేదా ఈమెయిల్‌లో మీకే పంపి, తెరిచి “Import contacts” ఎంచుకోండి. కంప్యూటర్‌లో: contacts.google.com → Import → CSV ఎంచుకోండి.',
  help_title: 'ఎలా వాడాలి & ఆలోచనలు',
  help_1: 'Excel లేదా Google Sheets: పేరు, మొబైల్ కాలమ్‌లను శీర్షికతో కలిపి ఎంచుకుని, కాపీ చేసి బాక్స్ 1 లో పేస్ట్ చేయండి. కాలమ్‌లు వాటంతట అవే సరిపోతాయి.',
  help_2: '098765-43210, +91 98765 43210 లేదా 9876543210 అన్నీ +919876543210 అవుతాయి. ఒకే సెల్‌లో రెండు నంబర్లు (98765 43210 / 91234 56789) ఒకే కాంటాక్ట్‌కు రెండు నంబర్లు అవుతాయి.',
  help_3: 'WhatsApp బ్రాడ్‌కాస్ట్: “Diwali -” లాంటి ఉపసర్గ చేర్చి, VCF ను 256 భాగాలుగా డౌన్‌లోడ్ చేసి ఫోన్‌లో ఇంపోర్ట్ చేయండి, తర్వాత బ్రాడ్‌కాస్ట్ లిస్ట్‌లో “Diwali -” తో మొదలయ్యే అందరినీ ఎంచుకోండి.',
  help_4: 'Google Contacts: Google Contacts CSV డౌన్‌లోడ్ చేసి contacts.google.com లో ఇంపోర్ట్ చేయండి. గ్రూప్ పేరు అక్కడ లేబుల్ అవుతుంది.',
  help_5: 'VCF నుంచి Excel: ఫోన్ నుంచి తీసిన .vcf తెరిచి, శుభ్రమైన CSV డౌన్‌లోడ్ చేసి Excel లో తెరవండి. నంబర్లు +91 తో టెక్స్ట్‌గా ఉంటాయి, కాబట్టి Excel కుదించదు.',
  help_6: 'ముందు అనుమతి తీసుకోండి: DPDP Act 2023, TRAI నియమాల ప్రకారం ఒప్పుకున్న కస్టమర్లకే ప్రచార సందేశాలు పంపండి, ఆపమని అడిగినవారిని జాబితా నుంచి తీసేయండి.',
  aria_table: 'శుభ్రం చేసిన కాంటాక్ట్ జాబితా',
  sample_tsv: 'పేరు\tమొబైల్\tఈమెయిల్\tకంపెనీ\tగ్రూప్\nరమేష్ కుమార్\t098765-43210\tramesh@example.com\tకుమార్ కిరాణా స్టోర్\tకస్టమర్\nప్రియ శర్మ\t+91 91234 56789\tpriya@example.com\tశర్మ ట్యూషన్\tకస్టమర్\nరమేష్ కుమార్\t9876543210\t\t\tకస్టమర్\nఅనిల్ మెహతా\t9.87654E+09\t\tమెహతా ట్రేడర్స్\tసప్లయర్\nఫాతిమా ఖాన్\t98989 89898 / 97979 79797\tfatima@example.com\tఖాన్ బొటిక్\tకస్టమర్\nరాజేష్ ఆఫీస్\t011-23456789\t\tరాజేష్ అండ్ సన్స్\tసప్లయర్\nసునీత దేవి\t12345\t\tదేవి డెయిరీ\tకస్టమర్'
};
window.APP_STRINGS.kn = {
  app_title: 'Excel ನಿಂದ ಸಂಪರ್ಕಗಳು (VCF)',
  intro: 'Excel ಅಥವಾ Google Sheets ನಿಂದ ಗ್ರಾಹಕರ ಪಟ್ಟಿಯನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ, ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗಳನ್ನು ಸರಿಪಡಿಸಿ ಯಾವುದೇ ಫೋನ್‌ಗೆ ನೇರವಾಗಿ ಇಂಪೋರ್ಟ್ ಆಗುವ VCF ಫೈಲ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ, ಅಥವಾ Google Contacts CSV ಮಾಡಿ. VCF ಅನ್ನು ಮತ್ತೆ Excel ಗಾಗಿ CSV ಆಗಿಯೂ ಮಾಡಬಹುದು.',
  privacy: 'ನಿಮ್ಮ ಗ್ರಾಹಕರ ಪಟ್ಟಿ ಈ ಸಾಧನದಿಂದ ಹೊರಗೆ ಹೋಗುವುದಿಲ್ಲ: ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ. ಭಾರತದ DPDP Act 2023 ಪ್ರಕಾರ ಗ್ರಾಹಕರ ವೈಯಕ್ತಿಕ ಡೇಟಾ ರಕ್ಷಿಸುವುದು ನಿಮ್ಮ ಜವಾಬ್ದಾರಿ, ಆದ್ದರಿಂದ ಈ ಫೈಲ್‌ಗಳನ್ನು ಅಗತ್ಯವಿರುವವರ ಜೊತೆ ಮಾತ್ರ ಹಂಚಿ, ಕೆಲಸ ಮುಗಿದ ಮೇಲೆ ಅಳಿಸಿ.',
  h_input: '1. ಪಟ್ಟಿಯನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ ಅಥವಾ ತೆರೆಯಿರಿ',
  paste_label: 'Excel, Google Sheets ಅಥವಾ ಯಾವುದೇ CSV ನಿಂದ ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ (ಒಂದು ಸಾಲಿಗೆ ಒಬ್ಬರು)',
  paste_ph: 'ಹೆಸರು    ಮೊಬೈಲ್    ಇಮೇಲ್    ಕಂಪನಿ    ಗುಂಪು\nರಮೇಶ್ ಕುಮಾರ್    98765 43210    ramesh@example.com    ಕುಮಾರ್ ಕಿರಾಣಿ    ಗ್ರಾಹಕರು',
  open_csv: 'CSV / TXT ಫೈಲ್ ತೆರೆಯಿರಿ', open_vcf: 'VCF ಫೈಲ್ ತೆರೆಯಿರಿ', load_example: 'ಉದಾಹರಣೆ ತುಂಬಿ',
  example_note: 'ಇದು ಕಾಲ್ಪನಿಕ ಸಂಖ್ಯೆಗಳ ಉದಾಹರಣೆ. ಇದರ ಬದಲು ನಿಮ್ಮ ಪಟ್ಟಿ ಪೇಸ್ಟ್ ಮಾಡಿ.',
  excel_tip: 'ಸಲಹೆ: Excel ಅಥವಾ Google Sheets ನಲ್ಲಿ ಶೀರ್ಷಿಕೆ ಸಾಲಿನೊಂದಿಗೆ ಕಾಲಮ್‌ಗಳನ್ನು ಆರಿಸಿ, ಕಾಪಿ ಮಾಡಿ ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ. ಸಂಖ್ಯೆ 9.87654E+09 ಎಂದು ಕಂಡರೆ, ಮೊದಲು ಆ ಕಾಲಮ್ ಅನ್ನು Text ಆಗಿ ಫಾರ್ಮ್ಯಾಟ್ ಮಾಡಿ ಮತ್ತೆ ಕಾಪಿ ಮಾಡಿ.',
  lines_read: '{n} ಸಾಲುಗಳನ್ನು ಓದಲಾಗಿದೆ', vcf_read: 'VCF ಫೈಲ್‌ನಿಂದ {n} ಸಂಪರ್ಕಗಳನ್ನು ಓದಿ ಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಗಿದೆ.', dl_vcf_csv: 'ಇವನ್ನು CSV ಆಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
  bad_file: 'ಈ ಫೈಲ್ ಓದಲಾಗಲಿಲ್ಲ. .csv, .txt ಅಥವಾ .vcf ಫೈಲ್ ಆರಿಸಿ.', empty_list: 'ಶುರು ಮಾಡಲು ಮೇಲೆ ನಿಮ್ಮ ಪಟ್ಟಿ ಪೇಸ್ಟ್ ಮಾಡಿ.',
  h_map: '2. ಯಾವ ಕಾಲಮ್ ಏನು?', map_hint: 'ನಿಮ್ಮ ಡೇಟಾ ನೋಡಿ ಊಹಿಸಲಾಗಿದೆ. ತಪ್ಪಾದರೆ ಬಾಕ್ಸ್ ಬದಲಿಸಿ.', has_header: 'ಮೊದಲ ಸಾಲು ಶೀರ್ಷಿಕೆ',
  col_name: 'ಹೆಸರು', col_last: 'ಮನೆತನದ ಹೆಸರು (ಐಚ್ಛಿಕ)', col_phone: 'ಮೊಬೈಲ್ / ಫೋನ್', col_phone2: 'ಎರಡನೇ ಫೋನ್ (ಐಚ್ಛಿಕ)', col_email: 'ಇಮೇಲ್', col_company: 'ಕಂಪನಿ / ಅಂಗಡಿ', col_label: 'ಗುಂಪು / ಲೇಬಲ್', col_note: 'ಟಿಪ್ಪಣಿ',
  none_opt: '— ಯಾವುದೂ ಇಲ್ಲ —', col_n: 'ಕಾಲಮ್ {n}',
  h_clean: '3. ಸ್ವಚ್ಛಗೊಳಿಸುವ ಆಯ್ಕೆಗಳು', cc_label: 'ದೇಶದ ಕೋಡ್ ಇಲ್ಲದ ಸಂಖ್ಯೆಗಳಿಗೆ ಕೋಡ್', cc_hint: 'ಭಾರತ 91 · UAE 971 · ನೇಪಾಳ 977 · ಬಾಂಗ್ಲಾದೇಶ 880 · ಶ್ರೀಲಂಕಾ 94',
  opt_title: 'ಹೆಸರುಗಳ ದೊಡ್ಡ-ಸಣ್ಣ ಅಕ್ಷರ ಸರಿಪಡಿಸಿ (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'ಒಂದೇ ಸಂಖ್ಯೆಯ ನಕಲು ಸಾಲುಗಳನ್ನು ಒಂದು ಸಂಪರ್ಕವಾಗಿ ಸೇರಿಸಿ',
  opt_landline: 'ಲ್ಯಾಂಡ್‌ಲೈನ್ ಸಂಖ್ಯೆಗಳನ್ನು ಇಡಿ (⚠ ಗುರುತಿನೊಂದಿಗೆ)', opt_intl: 'ವಿದೇಶಿ ಸಂಖ್ಯೆಗಳನ್ನು ಇಡಿ (🌐 ಗುರುತಿನೊಂದಿಗೆ)',
  prefix_label: 'ಪ್ರತಿ ಹೆಸರಿನ ಮುಂದೆ ಸೇರಿಸಿ', prefix_ph: 'ಉದಾ. Cust -', suffix_label: 'ಪ್ರತಿ ಹೆಸರಿನ ನಂತರ ಸೇರಿಸಿ', suffix_ph: 'ಉದಾ. (ದೀಪಾವಳಿ 2026)',
  prefix_hint: '“Cust -” ನಂತಹ ಪೂರ್ವಪ್ರತ್ಯಯ ಈ ಸಂಪರ್ಕಗಳನ್ನು ಫೋನ್‌ನಲ್ಲಿ ಒಟ್ಟಿಗೆ ಇಡುತ್ತದೆ, ಹಾಗಾಗಿ WhatsApp ಬ್ರಾಡ್‌ಕಾಸ್ಟ್ ಪಟ್ಟಿಗೆ ಆರಿಸುವುದು ಸುಲಭ.',
  h_result: '4. ಫಲಿತಾಂಶ ಪರಿಶೀಲಿಸಿ',
  stat_rows: 'ಸಾಲುಗಳು', stat_contacts: 'ಸಿದ್ಧ ಸಂಪರ್ಕಗಳು', stat_invalid: 'ತಪ್ಪು ಸಂಖ್ಯೆಗಳು', stat_dups: 'ಸೇರಿಸಿದ ನಕಲುಗಳು', stat_landline: 'ಲ್ಯಾಂಡ್‌ಲೈನ್', stat_noname: 'ಹೆಸರಿಲ್ಲದವು',
  filter_label: 'ತೋರಿಸು', filter_all: 'ಎಲ್ಲಾ', filter_ok: 'ಸಿದ್ಧ', filter_warn: 'ಗಮನಿಸಿ', filter_bad: 'ತಪ್ಪು',
  th_line: 'ಸಾಲು', th_name: 'ಹೆಸರು', th_phone: 'ಸಂಖ್ಯೆ(ಗಳು)', th_email: 'ಇಮೇಲ್', th_company: 'ಕಂಪನಿ', th_label: 'ಗುಂಪು', th_status: 'ಸ್ಥಿತಿ', th_note: 'ಟಿಪ್ಪಣಿ', th_title: 'ಹುದ್ದೆ', th_address: 'ವಿಳಾಸ', th_bday: 'ಹುಟ್ಟುಹಬ್ಬ', csv_phone: 'ಫೋನ್ {n}',
  st_ok: 'ಸಿದ್ಧ', st_landline: 'ಲ್ಯಾಂಡ್‌ಲೈನ್', st_intl: 'ವಿದೇಶಿ ಸಂಖ್ಯೆ', st_merged: '{n} ಸಾಲುಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ', st_noname: 'ಹೆಸರಿಲ್ಲ, ಆದ್ದರಿಂದ ಸಂಖ್ಯೆಯೇ ಹೆಸರು', st_dropped: '{n} ತಪ್ಪು ಸಂಖ್ಯೆಗಳನ್ನು ಬಿಡಲಾಗಿದೆ',
  st_landline_off: 'ಲ್ಯಾಂಡ್‌ಲೈನ್ (ನಿಮ್ಮ ಸೆಟ್ಟಿಂಗ್ ಪ್ರಕಾರ ಬಿಡಲಾಗಿದೆ)', st_intl_off: 'ವಿದೇಶಿ ಸಂಖ್ಯೆ (ನಿಮ್ಮ ಸೆಟ್ಟಿಂಗ್ ಪ್ರಕಾರ ಬಿಡಲಾಗಿದೆ)',
  bad_sci: 'Excel ಈ ಸಂಖ್ಯೆಯನ್ನು ಚಿಕ್ಕದು ಮಾಡಿದೆ (9.87654E+09). ಕಾಲಮ್ ಅನ್ನು Text ಆಗಿ ಫಾರ್ಮ್ಯಾಟ್ ಮಾಡಿ ಮತ್ತೆ ಕಾಪಿ ಮಾಡಿ.', bad_len: 'ತಪ್ಪು ಉದ್ದ: 10 ರ ಬದಲು {n} ಅಂಕೆಗಳು', bad_text: 'ಇದು ಫೋನ್ ಸಂಖ್ಯೆ ಅಲ್ಲ', bad_empty: 'ಸಂಖ್ಯೆ ಇಲ್ಲ',
  show_more: 'ಇನ್ನೂ {n} ತೋರಿಸು', showing: '{b} ರಲ್ಲಿ {a} ತೋರಿಸಲಾಗುತ್ತಿದೆ', no_rows_filter: 'ಈ ಫಿಲ್ಟರ್‌ನಲ್ಲಿ ಏನೂ ಇಲ್ಲ.', processing: '{n} ಸಾಲುಗಳು ಸ್ವಚ್ಛವಾಗುತ್ತಿವೆ…',
  h_export: '5. ಡೌನ್‌ಲೋಡ್', file_label: 'ಫೈಲ್ ಹೆಸರು',
  dl_vcf: 'VCF ಡೌನ್‌ಲೋಡ್ (ಎಲ್ಲಾ ಸಂಪರ್ಕಗಳು)', dl_csv: 'ಸ್ವಚ್ಛ CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'ಎಲ್ಲಾ ಸಂಖ್ಯೆಗಳನ್ನು ಕಾಪಿ ಮಾಡಿ',
  split_label: 'ಇಷ್ಟು ಜನರ ಫೈಲ್‌ಗಳಾಗಿ ವಿಂಗಡಿಸಿ', split_hint: 'WhatsApp ಬ್ರಾಡ್‌ಕಾಸ್ಟ್ ಪಟ್ಟಿಯಲ್ಲಿ ಗರಿಷ್ಠ 256 ಜನ ಇರಬಹುದು (ಅಕ್ಟೋಬರ್ 2026 ರಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ), ಆದ್ದರಿಂದ 256 ರ ಫೈಲ್ = ಪ್ರತಿ ಫೈಲ್‌ಗೆ ಒಂದು ಪಟ್ಟಿ.',
  dl_parts_zip: 'ಎಲ್ಲಾ ಭಾಗಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (ZIP)', part_n: 'ಭಾಗ {n}: ಸಂಪರ್ಕಗಳು {a}–{b}', parts_summary: '{n} ಫೈಲ್‌ಗಳು, ಪ್ರತಿಯೊಂದರಲ್ಲಿ ಗರಿಷ್ಠ {m} ಸಂಪರ್ಕಗಳು',
  preview_title: 'VCF ಫೈಲ್ ಮುನ್ನೋಟ (ಮೊದಲ 3 ಸಂಪರ್ಕಗಳು)', nothing_to_export: 'ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಇನ್ನೂ ಸಂಪರ್ಕಗಳಿಲ್ಲ.', done_dl: '{name} ಡೌನ್‌ಲೋಡ್ ಆಯಿತು', note_also: 'ಈ ಹೆಸರಿನಲ್ಲೂ ಇತ್ತು: {names}',
  import_tip: 'ಫೋನ್‌ನಲ್ಲಿ: .vcf ಫೈಲ್ ಅನ್ನು WhatsApp ಅಥವಾ ಇಮೇಲ್‌ನಲ್ಲಿ ನಿಮಗೇ ಕಳುಹಿಸಿ, ತೆರೆದು “Import contacts” ಆರಿಸಿ. ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ: contacts.google.com → Import → CSV ಆರಿಸಿ.',
  help_title: 'ಬಳಸುವುದು ಹೇಗೆ & ಆಲೋಚನೆಗಳು',
  help_1: 'Excel ಅಥವಾ Google Sheets: ಹೆಸರು ಮತ್ತು ಮೊಬೈಲ್ ಕಾಲಮ್‌ಗಳನ್ನು ಶೀರ್ಷಿಕೆಯೊಂದಿಗೆ ಆರಿಸಿ, ಕಾಪಿ ಮಾಡಿ ಬಾಕ್ಸ್ 1 ರಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ. ಕಾಲಮ್‌ಗಳು ತಾವಾಗಿಯೇ ಹೊಂದಿಕೊಳ್ಳುತ್ತವೆ.',
  help_2: '098765-43210, +91 98765 43210 ಅಥವಾ 9876543210 ಎಲ್ಲವೂ +919876543210 ಆಗುತ್ತವೆ. ಒಂದು ಸೆಲ್‌ನಲ್ಲಿ ಎರಡು ಸಂಖ್ಯೆಗಳು (98765 43210 / 91234 56789) ಒಂದೇ ಸಂಪರ್ಕದ ಎರಡು ಸಂಖ್ಯೆಗಳಾಗುತ್ತವೆ.',
  help_3: 'WhatsApp ಬ್ರಾಡ್‌ಕಾಸ್ಟ್: “Diwali -” ನಂತಹ ಪೂರ್ವಪ್ರತ್ಯಯ ಸೇರಿಸಿ, VCF ಅನ್ನು 256 ರ ಭಾಗಗಳಲ್ಲಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಫೋನ್‌ಗೆ ಇಂಪೋರ್ಟ್ ಮಾಡಿ, ನಂತರ ಬ್ರಾಡ್‌ಕಾಸ್ಟ್ ಪಟ್ಟಿಯಲ್ಲಿ “Diwali -” ನಿಂದ ಶುರುವಾಗುವ ಎಲ್ಲರನ್ನೂ ಆರಿಸಿ.',
  help_4: 'Google Contacts: Google Contacts CSV ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ contacts.google.com ನಲ್ಲಿ ಇಂಪೋರ್ಟ್ ಮಾಡಿ. ಗುಂಪಿನ ಹೆಸರು ಅಲ್ಲಿ ಲೇಬಲ್ ಆಗುತ್ತದೆ.',
  help_5: 'VCF ನಿಂದ Excel: ಫೋನ್‌ನಿಂದ ತೆಗೆದ .vcf ತೆರೆಯಿರಿ, ನಂತರ ಸ್ವಚ್ಛ CSV ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ Excel ನಲ್ಲಿ ತೆರೆಯಿರಿ. ಸಂಖ್ಯೆಗಳು +91 ಜೊತೆ ಪಠ್ಯವಾಗಿ ಇರುತ್ತವೆ, ಹಾಗಾಗಿ Excel ಚಿಕ್ಕದು ಮಾಡುವುದಿಲ್ಲ.',
  help_6: 'ಮೊದಲು ಅನುಮತಿ ಪಡೆಯಿರಿ: DPDP Act 2023 ಮತ್ತು TRAI ನಿಯಮಗಳ ಪ್ರಕಾರ ಒಪ್ಪಿದ ಗ್ರಾಹಕರಿಗೆ ಮಾತ್ರ ಪ್ರಚಾರ ಕಳುಹಿಸಿ, ನಿಲ್ಲಿಸಲು ಹೇಳಿದವರನ್ನು ಪಟ್ಟಿಯಿಂದ ತೆಗೆಯಿರಿ.',
  aria_table: 'ಸ್ವಚ್ಛಗೊಳಿಸಿದ ಸಂಪರ್ಕ ಪಟ್ಟಿ',
  sample_tsv: 'ಹೆಸರು\tಮೊಬೈಲ್\tಇಮೇಲ್\tಕಂಪನಿ\tಗುಂಪು\nರಮೇಶ್ ಕುಮಾರ್\t098765-43210\tramesh@example.com\tಕುಮಾರ್ ಕಿರಾಣಿ ಅಂಗಡಿ\tಗ್ರಾಹಕರು\nಪ್ರಿಯಾ ಶರ್ಮಾ\t+91 91234 56789\tpriya@example.com\tಶರ್ಮಾ ಟ್ಯೂಷನ್\tಗ್ರಾಹಕರು\nರಮೇಶ್ ಕುಮಾರ್\t9876543210\t\t\tಗ್ರಾಹಕರು\nಅನಿಲ್ ಮೆಹ್ತಾ\t9.87654E+09\t\tಮೆಹ್ತಾ ಟ್ರೇಡರ್ಸ್\tಪೂರೈಕೆದಾರರು\nಫಾತಿಮಾ ಖಾನ್\t98989 89898 / 97979 79797\tfatima@example.com\tಖಾನ್ ಬುಟೀಕ್\tಗ್ರಾಹಕರು\nರಾಜೇಶ್ ಆಫೀಸ್\t011-23456789\t\tರಾಜೇಶ್ ಅಂಡ್ ಸನ್ಸ್\tಪೂರೈಕೆದಾರರು\nಸುನೀತಾ ದೇವಿ\t12345\t\tದೇವಿ ಡೈರಿ\tಗ್ರಾಹಕರು'
};
window.APP_STRINGS.ml = {
  app_title: 'Excel ൽ നിന്ന് കോൺടാക്റ്റ് (VCF)',
  intro: 'Excel അല്ലെങ്കിൽ Google Sheets ൽ നിന്ന് ഉപഭോക്തൃ പട്ടിക പേസ്റ്റ് ചെയ്യുക, മൊബൈൽ നമ്പറുകൾ ശരിയാക്കി ഏത് ഫോണിലും നേരിട്ട് ഇംപോർട്ട് ആകുന്ന VCF ഫയൽ ഡൗൺലോഡ് ചെയ്യുക, അല്ലെങ്കിൽ Google Contacts CSV ഉണ്ടാക്കുക. VCF നെ തിരികെ Excel നുള്ള CSV ആക്കാനും കഴിയും.',
  privacy: 'നിങ്ങളുടെ ഉപഭോക്തൃ പട്ടിക ഈ ഉപകരണം വിട്ടു പോകില്ല: ഒന്നും അപ്‌ലോഡ് ചെയ്യില്ല. ഇന്ത്യയുടെ DPDP Act 2023 പ്രകാരം ഉപഭോക്താക്കളുടെ വ്യക്തിഗത ഡാറ്റ സംരക്ഷിക്കേണ്ടത് നിങ്ങളുടെ ഉത്തരവാദിത്തമാണ്, അതിനാൽ ഈ ഫയലുകൾ ആവശ്യമുള്ളവരുമായി മാത്രം പങ്കിടുക, ജോലി കഴിഞ്ഞാൽ മായ്ക്കുക.',
  h_input: '1. പട്ടിക പേസ്റ്റ് ചെയ്യുക അല്ലെങ്കിൽ തുറക്കുക',
  paste_label: 'Excel, Google Sheets അല്ലെങ്കിൽ ഏതെങ്കിലും CSV ൽ നിന്ന് ഇവിടെ പേസ്റ്റ് ചെയ്യുക (ഒരു വരിയിൽ ഒരാൾ)',
  paste_ph: 'പേര്    മൊബൈൽ    ഇമെയിൽ    കമ്പനി    ഗ്രൂപ്പ്\nരമേഷ് കുമാർ    98765 43210    ramesh@example.com    കുമാർ പലചരക്ക്    ഉപഭോക്താവ്',
  open_csv: 'CSV / TXT ഫയൽ തുറക്കുക', open_vcf: 'VCF ഫയൽ തുറക്കുക', load_example: 'ഉദാഹരണം നിറയ്ക്കുക',
  example_note: 'ഇത് സാങ്കൽപ്പിക നമ്പറുകളുള്ള ഉദാഹരണമാണ്. പകരം നിങ്ങളുടെ പട്ടിക പേസ്റ്റ് ചെയ്യുക.',
  excel_tip: 'നുറുങ്ങ്: Excel അല്ലെങ്കിൽ Google Sheets ൽ തലക്കെട്ട് വരിയോടൊപ്പം കോളങ്ങൾ തിരഞ്ഞെടുത്ത്, കോപ്പി ചെയ്ത് ഇവിടെ പേസ്റ്റ് ചെയ്യുക. നമ്പർ 9.87654E+09 എന്ന് കാണിച്ചാൽ, ആദ്യം ആ കോളം Text ആയി ഫോർമാറ്റ് ചെയ്ത് വീണ്ടും കോപ്പി ചെയ്യുക.',
  lines_read: '{n} വരികൾ വായിച്ചു', vcf_read: 'VCF ഫയലിൽ നിന്ന് {n} കോൺടാക്റ്റുകൾ വായിച്ച് പട്ടികയിൽ ചേർത്തു.', dl_vcf_csv: 'ഇവ CSV ആയി ഡൗൺലോഡ് ചെയ്യുക',
  bad_file: 'ഈ ഫയൽ വായിക്കാനായില്ല. .csv, .txt അല്ലെങ്കിൽ .vcf ഫയൽ തിരഞ്ഞെടുക്കുക.', empty_list: 'തുടങ്ങാൻ മുകളിൽ നിങ്ങളുടെ പട്ടിക പേസ്റ്റ് ചെയ്യുക.',
  h_map: '2. ഏത് കോളം എന്താണ്?', map_hint: 'നിങ്ങളുടെ ഡാറ്റ നോക്കി ഊഹിച്ചതാണ്. തെറ്റാണെങ്കിൽ ബോക്സ് മാറ്റുക.', has_header: 'ആദ്യ വരി തലക്കെട്ടാണ്',
  col_name: 'പേര്', col_last: 'കുടുംബപ്പേര് (ഐച്ഛികം)', col_phone: 'മൊബൈൽ / ഫോൺ', col_phone2: 'രണ്ടാം ഫോൺ (ഐച്ഛികം)', col_email: 'ഇമെയിൽ', col_company: 'കമ്പനി / കട', col_label: 'ഗ്രൂപ്പ് / ലേബൽ', col_note: 'കുറിപ്പ്',
  none_opt: '— ഒന്നുമില്ല —', col_n: 'കോളം {n}',
  h_clean: '3. വൃത്തിയാക്കൽ ഓപ്ഷനുകൾ', cc_label: 'രാജ്യ കോഡ് ഇല്ലാത്ത നമ്പറുകൾക്കുള്ള കോഡ്', cc_hint: 'ഇന്ത്യ 91 · UAE 971 · നേപ്പാൾ 977 · ബംഗ്ലാദേശ് 880 · ശ്രീലങ്ക 94',
  opt_title: 'പേരുകളിലെ വലിയ-ചെറിയ അക്ഷരങ്ങൾ ശരിയാക്കുക (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'ഒരേ നമ്പറുള്ള ഡ്യൂപ്ലിക്കേറ്റ് വരികൾ ഒരു കോൺടാക്റ്റായി ചേർക്കുക',
  opt_landline: 'ലാൻഡ്‌ലൈൻ നമ്പറുകൾ നിലനിർത്തുക (⚠ അടയാളത്തോടെ)', opt_intl: 'വിദേശ നമ്പറുകൾ നിലനിർത്തുക (🌐 അടയാളത്തോടെ)',
  prefix_label: 'ഓരോ പേരിനും മുൻപ് ചേർക്കുക', prefix_ph: 'ഉദാ. Cust -', suffix_label: 'ഓരോ പേരിനും ശേഷം ചേർക്കുക', suffix_ph: 'ഉദാ. (ദീപാവലി 2026)',
  prefix_hint: '“Cust -” പോലുള്ള മുൻപദം ഈ കോൺടാക്റ്റുകളെ ഫോണിൽ ഒരുമിച്ച് നിർത്തും, അതിനാൽ WhatsApp ബ്രോഡ്‌കാസ്റ്റ് ലിസ്റ്റിനായി തിരഞ്ഞെടുക്കാൻ എളുപ്പം.',
  h_result: '4. ഫലം പരിശോധിക്കുക',
  stat_rows: 'വരികൾ', stat_contacts: 'തയ്യാറായ കോൺടാക്റ്റുകൾ', stat_invalid: 'തെറ്റായ നമ്പറുകൾ', stat_dups: 'ചേർത്ത ഡ്യൂപ്ലിക്കേറ്റുകൾ', stat_landline: 'ലാൻഡ്‌ലൈൻ', stat_noname: 'പേരില്ലാത്തവ',
  filter_label: 'കാണിക്കുക', filter_all: 'എല്ലാം', filter_ok: 'തയ്യാർ', filter_warn: 'ശ്രദ്ധിക്കുക', filter_bad: 'തെറ്റ്',
  th_line: 'വരി', th_name: 'പേര്', th_phone: 'നമ്പർ(കൾ)', th_email: 'ഇമെയിൽ', th_company: 'കമ്പനി', th_label: 'ഗ്രൂപ്പ്', th_status: 'നില', th_note: 'കുറിപ്പ്', th_title: 'പദവി', th_address: 'വിലാസം', th_bday: 'ജന്മദിനം', csv_phone: 'ഫോൺ {n}',
  st_ok: 'തയ്യാർ', st_landline: 'ലാൻഡ്‌ലൈൻ', st_intl: 'വിദേശ നമ്പർ', st_merged: '{n} വരികൾ ചേർത്തു', st_noname: 'പേരില്ല, അതിനാൽ നമ്പർ തന്നെ പേര്', st_dropped: '{n} തെറ്റായ നമ്പറുകൾ ഒഴിവാക്കി',
  st_landline_off: 'ലാൻഡ്‌ലൈൻ (നിങ്ങളുടെ ക്രമീകരണം പ്രകാരം ഒഴിവാക്കി)', st_intl_off: 'വിദേശ നമ്പർ (നിങ്ങളുടെ ക്രമീകരണം പ്രകാരം ഒഴിവാക്കി)',
  bad_sci: 'Excel ഈ നമ്പർ ചുരുക്കി (9.87654E+09). കോളം Text ആയി ഫോർമാറ്റ് ചെയ്ത് വീണ്ടും കോപ്പി ചെയ്യുക.', bad_len: 'തെറ്റായ നീളം: 10 നു പകരം {n} അക്കങ്ങൾ', bad_text: 'ഇത് ഫോൺ നമ്പറല്ല', bad_empty: 'നമ്പറില്ല',
  show_more: '{n} കൂടി കാണിക്കുക', showing: '{b} ൽ {a} കാണിക്കുന്നു', no_rows_filter: 'ഈ ഫിൽട്ടറിൽ ഒന്നുമില്ല.', processing: '{n} വരികൾ വൃത്തിയാക്കുന്നു…',
  h_export: '5. ഡൗൺലോഡ്', file_label: 'ഫയലിന്റെ പേര്',
  dl_vcf: 'VCF ഡൗൺലോഡ് (എല്ലാ കോൺടാക്റ്റുകളും)', dl_csv: 'വൃത്തിയാക്കിയ CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'എല്ലാ നമ്പറുകളും കോപ്പി ചെയ്യുക',
  split_label: 'ഇത്രപേർ വീതമുള്ള ഫയലുകളായി വിഭജിക്കുക', split_hint: 'WhatsApp ബ്രോഡ്‌കാസ്റ്റ് ലിസ്റ്റിൽ പരമാവധി 256 പേർ ആകാം (ഒക്ടോബർ 2026 ൽ പരിശോധിച്ചത്), അതിനാൽ 256 ന്റെ ഫയൽ = ഓരോ ഫയലിനും ഒരു ലിസ്റ്റ്.',
  dl_parts_zip: 'എല്ലാ ഭാഗങ്ങളും ഡൗൺലോഡ് ചെയ്യുക (ZIP)', part_n: 'ഭാഗം {n}: കോൺടാക്റ്റുകൾ {a}–{b}', parts_summary: '{n} ഫയലുകൾ, ഓരോന്നിലും പരമാവധി {m} കോൺടാക്റ്റുകൾ',
  preview_title: 'VCF ഫയലിന്റെ പ്രിവ്യൂ (ആദ്യ 3 കോൺടാക്റ്റുകൾ)', nothing_to_export: 'ഡൗൺലോഡ് ചെയ്യാൻ ഇതുവരെ കോൺടാക്റ്റുകളില്ല.', done_dl: '{name} ഡൗൺലോഡ് ചെയ്തു', note_also: 'ഈ പേരിലും ഉണ്ടായിരുന്നു: {names}',
  import_tip: 'ഫോണിൽ: .vcf ഫയൽ WhatsApp അല്ലെങ്കിൽ ഇമെയിൽ വഴി നിങ്ങൾക്കുതന്നെ അയച്ച്, തുറന്ന് “Import contacts” തിരഞ്ഞെടുക്കുക. കമ്പ്യൂട്ടറിൽ: contacts.google.com → Import → CSV തിരഞ്ഞെടുക്കുക.',
  help_title: 'ഉപയോഗിക്കുന്ന വിധം & ആശയങ്ങൾ',
  help_1: 'Excel അല്ലെങ്കിൽ Google Sheets: പേര്, മൊബൈൽ കോളങ്ങൾ തലക്കെട്ടോടെ തിരഞ്ഞെടുത്ത്, കോപ്പി ചെയ്ത് ബോക്സ് 1 ൽ പേസ്റ്റ് ചെയ്യുക. കോളങ്ങൾ സ്വയം ശരിയാകും.',
  help_2: '098765-43210, +91 98765 43210 അല്ലെങ്കിൽ 9876543210 എല്ലാം +919876543210 ആകും. ഒരു സെല്ലിലെ രണ്ട് നമ്പറുകൾ (98765 43210 / 91234 56789) ഒരേ കോൺടാക്റ്റിന്റെ രണ്ട് നമ്പറുകളാകും.',
  help_3: 'WhatsApp ബ്രോഡ്‌കാസ്റ്റ്: “Diwali -” പോലുള്ള മുൻപദം ചേർത്ത്, VCF 256 ന്റെ ഭാഗങ്ങളായി ഡൗൺലോഡ് ചെയ്ത് ഫോണിൽ ഇംപോർട്ട് ചെയ്യുക, തുടർന്ന് ബ്രോഡ്‌കാസ്റ്റ് ലിസ്റ്റിൽ “Diwali -” ൽ തുടങ്ങുന്ന എല്ലാവരെയും തിരഞ്ഞെടുക്കുക.',
  help_4: 'Google Contacts: Google Contacts CSV ഡൗൺലോഡ് ചെയ്ത് contacts.google.com ൽ ഇംപോർട്ട് ചെയ്യുക. ഗ്രൂപ്പ് പേര് അവിടെ ലേബൽ ആകും.',
  help_5: 'VCF ൽ നിന്ന് Excel: ഫോണിൽ നിന്നെടുത്ത .vcf തുറന്ന്, വൃത്തിയാക്കിയ CSV ഡൗൺലോഡ് ചെയ്ത് Excel ൽ തുറക്കുക. നമ്പറുകൾ +91 ഓടെ ടെക്സ്റ്റായി നിൽക്കും, അതിനാൽ Excel ചുരുക്കില്ല.',
  help_6: 'ആദ്യം അനുമതി വാങ്ങുക: DPDP Act 2023, TRAI നിയമങ്ങൾ പ്രകാരം സമ്മതിച്ച ഉപഭോക്താക്കൾക്ക് മാത്രം പ്രചാരണം അയയ്ക്കുക, നിർത്താൻ പറയുന്നവരെ പട്ടികയിൽ നിന്ന് നീക്കുക.',
  aria_table: 'വൃത്തിയാക്കിയ കോൺടാക്റ്റ് പട്ടിക',
  sample_tsv: 'പേര്\tമൊബൈൽ\tഇമെയിൽ\tകമ്പനി\tഗ്രൂപ്പ്\nരമേഷ് കുമാർ\t098765-43210\tramesh@example.com\tകുമാർ പലചരക്ക് കട\tഉപഭോക്താവ്\nപ്രിയ ശർമ്മ\t+91 91234 56789\tpriya@example.com\tശർമ്മ ട്യൂഷൻ\tഉപഭോക്താവ്\nരമേഷ് കുമാർ\t9876543210\t\t\tഉപഭോക്താവ്\nഅനിൽ മേത്ത\t9.87654E+09\t\tമേത്ത ട്രേഡേഴ്സ്\tവിതരണക്കാരൻ\nഫാത്തിമ ഖാൻ\t98989 89898 / 97979 79797\tfatima@example.com\tഖാൻ ബുട്ടീക്ക്\tഉപഭോക്താവ്\nരാജേഷ് ഓഫീസ്\t011-23456789\t\tരാജേഷ് ആൻഡ് സൺസ്\tവിതരണക്കാരൻ\nസുനിത ദേവി\t12345\t\tദേവി ഡെയറി\tഉപഭോക്താവ്'
};
window.APP_STRINGS.ur = {
  app_title: 'Excel سے کانٹیکٹ (VCF)',
  intro: 'Excel یا Google Sheets سے گاہکوں کی فہرست پیسٹ کریں، موبائل نمبر صاف کریں اور ایسی VCF فائل ڈاؤن لوڈ کریں جو کسی بھی فون میں سیدھی امپورٹ ہو جائے، یا Google Contacts CSV بنائیں۔ VCF کو واپس Excel کے لیے CSV بھی بنا سکتے ہیں۔',
  privacy: 'آپ کی گاہک فہرست اس ڈیوائس سے باہر نہیں جاتی: کچھ بھی اپ لوڈ نہیں ہوتا۔ بھارت کے DPDP Act 2023 کے تحت گاہکوں کا ذاتی ڈیٹا محفوظ رکھنا آپ کی ذمہ داری ہے، اس لیے یہ فائلیں صرف ضروری لوگوں سے شیئر کریں اور کام پورا ہونے پر حذف کر دیں۔',
  h_input: '1. فہرست پیسٹ کریں یا کھولیں',
  paste_label: 'یہاں Excel، Google Sheets یا کسی CSV سے پیسٹ کریں (ایک لائن میں ایک شخص)',
  paste_ph: 'نام    موبائل    ای میل    کمپنی    گروپ\nرمیش کمار    98765 43210    ramesh@example.com    کمار کریانہ    گاہک',
  open_csv: 'CSV / TXT فائل کھولیں', open_vcf: 'VCF فائل کھولیں', load_example: 'مثال بھریں',
  example_note: 'یہ فرضی نمبروں والی مثال ہے۔ اس کی جگہ اپنی فہرست پیسٹ کریں۔',
  excel_tip: 'مشورہ: Excel یا Google Sheets میں سرخی والی لائن سمیت کالم چنیں، کاپی کریں اور یہاں پیسٹ کریں۔ اگر نمبر 9.87654E+09 جیسا دکھے تو پہلے اس کالم کو Text فارمیٹ کریں اور پھر کاپی کریں۔',
  lines_read: '{n} لائنیں پڑھی گئیں', vcf_read: 'VCF فائل سے {n} کانٹیکٹ پڑھ کر فہرست میں رکھ دیے گئے۔', dl_vcf_csv: 'انہیں CSV میں ڈاؤن لوڈ کریں',
  bad_file: 'یہ فائل پڑھی نہیں جا سکی۔ .csv، .txt یا .vcf فائل چنیں۔', empty_list: 'شروع کرنے کے لیے اوپر اپنی فہرست پیسٹ کریں۔',
  h_map: '2. کون سا کالم کیا ہے؟', map_hint: 'آپ کے ڈیٹا سے اندازہ لگایا ہے۔ غلط ہو تو خانہ بدل دیں۔', has_header: 'پہلی لائن سرخی ہے',
  col_name: 'نام', col_last: 'خاندانی نام (اختیاری)', col_phone: 'موبائل / فون', col_phone2: 'دوسرا فون (اختیاری)', col_email: 'ای میل', col_company: 'کمپنی / دکان', col_label: 'گروپ / لیبل', col_note: 'نوٹ',
  none_opt: '— کوئی نہیں —', col_n: 'کالم {n}',
  h_clean: '3. صفائی کے اختیارات', cc_label: 'جن نمبروں میں ملک کا کوڈ نہیں، ان کے لیے کوڈ', cc_hint: 'بھارت 91 · UAE 971 · نیپال 977 · بنگلہ دیش 880 · سری لنکا 94',
  opt_title: 'ناموں کے بڑے چھوٹے حروف ٹھیک کریں (ramesh KUMAR → Ramesh Kumar)', opt_dedupe: 'ایک ہی نمبر کی دہری لائنیں ایک کانٹیکٹ میں ملائیں',
  opt_landline: 'لینڈ لائن نمبر رکھیں (⚠ نشان کے ساتھ)', opt_intl: 'غیر ملکی نمبر رکھیں (🌐 نشان کے ساتھ)',
  prefix_label: 'ہر نام سے پہلے جوڑیں', prefix_ph: 'جیسے Cust -', suffix_label: 'ہر نام کے بعد جوڑیں', suffix_ph: 'جیسے (دیوالی 2026)',
  prefix_hint: '“Cust -” جیسا سابقہ ان کانٹیکٹس کو فون میں ایک ساتھ رکھتا ہے، اس لیے WhatsApp براڈکاسٹ لسٹ کے لیے چننا آسان ہو جاتا ہے۔',
  h_result: '4. نتیجہ جانچیں',
  stat_rows: 'لائنیں', stat_contacts: 'تیار کانٹیکٹ', stat_invalid: 'غلط نمبر', stat_dups: 'ملائے گئے دہرے', stat_landline: 'لینڈ لائن', stat_noname: 'بغیر نام',
  filter_label: 'دکھائیں', filter_all: 'سب', filter_ok: 'تیار', filter_warn: 'توجہ دیں', filter_bad: 'غلط',
  th_line: 'لائن', th_name: 'نام', th_phone: 'نمبر', th_email: 'ای میل', th_company: 'کمپنی', th_label: 'گروپ', th_status: 'حالت', th_note: 'نوٹ', th_title: 'عہدہ', th_address: 'پتہ', th_bday: 'سالگرہ', csv_phone: 'فون {n}',
  st_ok: 'تیار', st_landline: 'لینڈ لائن', st_intl: 'غیر ملکی نمبر', st_merged: '{n} لائنیں ملائی گئیں', st_noname: 'نام نہیں، اس لیے نمبر ہی نام بنا', st_dropped: '{n} غلط نمبر چھوڑ دیے گئے',
  st_landline_off: 'لینڈ لائن (آپ کی سیٹنگ سے ہٹایا)', st_intl_off: 'غیر ملکی نمبر (آپ کی سیٹنگ سے ہٹایا)',
  bad_sci: 'Excel نے یہ نمبر چھوٹا کر دیا (9.87654E+09)۔ کالم کو Text فارمیٹ کر کے پھر کاپی کریں۔', bad_len: 'غلط لمبائی: 10 کی جگہ {n} ہندسے', bad_text: 'یہ فون نمبر نہیں ہے', bad_empty: 'نمبر نہیں',
  show_more: 'مزید {n} دکھائیں', showing: '{b} میں سے {a} دکھ رہے ہیں', no_rows_filter: 'اس فلٹر میں کچھ نہیں۔', processing: '{n} لائنیں صاف ہو رہی ہیں…',
  h_export: '5. ڈاؤن لوڈ', file_label: 'فائل کا نام',
  dl_vcf: 'VCF ڈاؤن لوڈ کریں (سب کانٹیکٹ)', dl_csv: 'صاف CSV', dl_google: 'Google Contacts CSV', copy_numbers: 'سب نمبر کاپی کریں',
  split_label: 'اتنے اتنے کی فائلوں میں بانٹیں', split_hint: 'WhatsApp براڈکاسٹ لسٹ میں زیادہ سے زیادہ 256 لوگ ہو سکتے ہیں (اکتوبر 2026 میں جانچا)، اس لیے 256 کی فائلیں = ہر فائل کی ایک لسٹ۔',
  dl_parts_zip: 'سب حصے ڈاؤن لوڈ کریں (ZIP)', part_n: 'حصہ {n}: کانٹیکٹ {a}–{b}', parts_summary: '{n} فائلیں، ہر ایک میں زیادہ سے زیادہ {m} کانٹیکٹ',
  preview_title: 'VCF فائل کی جھلک (پہلے 3 کانٹیکٹ)', nothing_to_export: 'ابھی ڈاؤن لوڈ کے لیے کوئی کانٹیکٹ نہیں۔', done_dl: '{name} ڈاؤن لوڈ ہو گئی', note_also: 'یہ نام بھی لکھا تھا: {names}',
  import_tip: 'فون میں: .vcf فائل WhatsApp یا ای میل سے خود کو بھیجیں، کھولیں اور “Import contacts” چنیں۔ کمپیوٹر پر: contacts.google.com → Import → CSV چنیں۔',
  help_title: 'استعمال کا طریقہ اور خیالات',
  help_1: 'Excel یا Google Sheets: نام اور موبائل کے کالم سرخی والی لائن سمیت چنیں، کاپی کریں اور خانہ 1 میں پیسٹ کریں۔ کالم خود بخود ٹھیک بیٹھ جاتے ہیں۔',
  help_2: '098765-43210، +91 98765 43210 یا 9876543210، سب +919876543210 بن جاتے ہیں۔ ایک سیل میں دو نمبر (98765 43210 / 91234 56789) اسی کانٹیکٹ کے دو نمبر بنتے ہیں۔',
  help_3: 'WhatsApp براڈکاسٹ: “Diwali -” جیسا سابقہ جوڑیں، VCF کو 256 کے حصوں میں ڈاؤن لوڈ کریں، فون میں امپورٹ کریں، پھر براڈکاسٹ لسٹ بنا کر “Diwali -” سے شروع ہونے والے سب چن لیں۔',
  help_4: 'Google Contacts: Google Contacts CSV ڈاؤن لوڈ کریں اور contacts.google.com پر امپورٹ کریں۔ گروپ کا نام وہاں لیبل بن جاتا ہے۔',
  help_5: 'VCF سے Excel: فون سے نکالی گئی .vcf فائل کھولیں، پھر صاف CSV ڈاؤن لوڈ کر کے Excel میں کھولیں۔ نمبر +91 کے ساتھ ٹیکسٹ رہتے ہیں، اس لیے Excel انہیں چھوٹا نہیں کرے گا۔',
  help_6: 'پہلے اجازت لیں: DPDP Act 2023 اور TRAI قواعد کے تحت تشہیر صرف رضامند گاہکوں کو بھیجیں، اور جو روکنے کو کہے اسے فہرست سے ہٹا دیں۔',
  aria_table: 'صاف کی گئی کانٹیکٹ فہرست',
  sample_tsv: 'نام\tموبائل\tای میل\tکمپنی\tگروپ\nرمیش کمار\t098765-43210\tramesh@example.com\tکمار کریانہ اسٹور\tگاہک\nپریا شرما\t+91 91234 56789\tpriya@example.com\tشرما ٹیوشن\tگاہک\nرمیش کمار\t9876543210\t\t\tگاہک\nانل مہتا\t9.87654E+09\t\tمہتا ٹریڈرز\tسپلائر\nفاطمہ خان\t98989 89898 / 97979 79797\tfatima@example.com\tخان بوتیک\tگاہک\nراجیش دفتر\t011-23456789\t\tراجیش اینڈ سنز\tسپلائر\nسنیتا دیوی\t12345\t\tدیوی ڈیری\tگاہک'
};
