/* Sign & Fill PDF: UI strings in 12 languages (identical keys). */
window.APP_STRINGS = {
en: {
  app_title: 'Sign & Fill PDF',
  intro: 'Sign, fill and stamp a PDF right here: draw or type your signature, add text, a date, a tick, a “Self attested” note or a stamp, and fill form fields. The file never leaves your device.',
  privacy_title: 'Your PDF never leaves this device.',
  privacy_body: 'Offer letters, contracts, KYC copies and forms are signed inside your browser. Nothing is uploaded, and the file is gone when you close this page.',
  eng_loading: 'Loading the PDF engine… (needs internet the first time)',
  eng_ready: 'PDF engine ready',
  eng_failed: 'Could not load the PDF engine. Connect to the internet and press Retry. After one successful load it works offline.',
  retry: 'Retry', waiting_engine: 'Waiting for the PDF engine…', working: 'Working…',
  drop_title: 'Drop a PDF here',
  drop_hint: 'or open one from your phone or computer. Offer letter, agreement, application form, Aadhaar or PAN copy.',
  open_pdf: 'Open PDF', try_sample: 'Try the sample letter',
  opening: 'Opening {name}…', opened: 'Opened {name}, {n} pages.',
  one_page: '1 page', n_pages: '{n} pages',
  err_type: '{name} is not a PDF. Save it as PDF first.',
  err_corrupt: '{name} could not be opened. The file may be damaged.',
  err_locked: '{name} is password-protected. Remove the password first with the PDF Compress & Convert app, then come back.',
  unlock_btn: 'Open the unlock tool',
  err_big: '{name} is large ({size}). It may be slow on a phone.',
  err_img: 'That image could not be read. Use a JPG or PNG.',
  err_blank: 'No dark signature found in the photo. Use a dark pen on white paper.',
  err_save: 'Could not write the PDF. Try again or use another file.',
  prev_page: 'Previous page', next_page: 'Next page', goto_page: 'Go to page',
  undo: 'Undo', redo: 'Redo', it_delete: 'Remove', clear_page: 'Clear this page',
  confirm_clear_page: 'Remove everything you added on this page?',
  items_on_page: '{n} added on this page', page_canvas: 'PDF page', items_label: 'Items added to the page',
  stage_hint: 'Tap an item to select it, drag to move it, drag the blue corner to resize. Arrow keys also move it.',
  added: 'Added to the page. Drag it into place.', added_all: 'Added to all {n} pages.', removed: 'Removed.',
  item_sig: 'Signature', item_init: 'Initials', item_stamp: 'Stamp', item_text: 'Text', item_date: 'Date', item_tick: 'Tick', item_cross: 'Cross', item_white: 'White box',
  tools_label: 'Tools',
  tool_sign: 'Signature', tool_text: 'Text', tool_date: 'Date', tool_mark: 'Tick / cross', tool_self: 'Self attested', tool_stamp: 'Stamp', tool_hide: 'White-out', tool_form: 'Form fields',
  sig_draw: 'Draw', sig_type: 'Type', sig_photo: 'Photo',
  sig_pad_hint: 'Sign here with your finger, stylus or mouse.',
  sig_type_label: 'Your name', sig_type_ph: 'e.g. Priya Sharma', sig_type_prev_empty: 'Your name appears here in a handwriting style',
  sig_photo_pick: 'Choose a photo of your signature',
  sig_photo_hint: 'Sign with a dark pen on white paper and take a clear photo. The paper is made transparent automatically.',
  ink: 'Ink colour', col_blue: 'Blue', col_black: 'Black', col_red: 'Red', col_green: 'Green',
  sig_use: 'Add as signature', sig_use_init: 'Add as initials',
  sig_empty: 'Draw, type or choose a photo first.',
  sig_saved_title: 'Saved on this device', sig_saved_sig: 'Signature', sig_saved_init: 'Initials',
  sig_add: 'Add to page', sig_add_all: 'Every page', sig_forget: 'Forget',
  sig_saved_note: 'Saved only in this browser so you can reuse it. On a shared computer press Forget when you are done.',
  sig_too_big: 'This image is too big to remember for next time, but it is added to the page.',
  forgotten: 'Forgotten.',
  text_label: 'Text', text_ph: 'e.g. Approved, Paid, Priya Sharma', text_size: 'Size', text_style: 'Style', font_normal: 'Normal', font_hand: 'Handwriting',
  text_ink_note: 'Uses the ink colour chosen under Signature.', text_add: 'Add text',
  date_label: 'Date', date_fmt: 'Format', date_add: 'Add date',
  mark_help: 'Tick a box or cross out an option. Drag the corner to make it bigger.', mark_tick: 'Tick', mark_cross: 'Cross',
  self_help: 'Offices ask for “Self attested” copies of Aadhaar, PAN, marksheets and certificates: write it, sign and date each copy. This adds all three together.',
  self_text_label: 'Text', self_default: 'Self attested',
  self_need_sig: 'Make a signature first (draw, type or photo). It is placed together with the text and today’s date.',
  self_add: 'Add to this page', self_add_all: 'Every page',
  stamp_help: 'Company seal, “PAID”, “RECEIVED”, school stamp. A PNG with a transparent background looks best.',
  stamp_pick: 'Choose stamp image', stamp_last: 'Stamp',
  hide_help: 'Covers part of the page with a white box, e.g. an old date or a wrong entry. The text under it still exists in the file, so do not use it to hide secrets.',
  hide_add: 'Add white box',
  form_none: 'This PDF has no fillable form fields. Use the Text tool to write on it.',
  form_xfa: 'This is an XFA form; its fields cannot be filled here.',
  form_help: '{n} fields found. Fill them here; they are written into the PDF when you save. Tap a highlighted box on the page to jump to it.',
  form_flatten: 'Lock the fields after saving (flatten)',
  field_aria: 'Form field {name}',
  out_name: 'File name', save_btn: 'Save signed PDF', saving: 'Writing the PDF…',
  result_msg: 'Saved {name} ({size}). Open it once and check before you send it.', download_again: 'Download again',
  nothing_added: 'Nothing added yet. Add a signature, text or date first.',
  legal_title: 'Please note',
  legal_body: 'This puts a picture of your signature on the PDF. It is not a Digital Signature Certificate (DSC) or Aadhaar eSign under the IT Act. Many offices accept it for everyday papers, but some filings (GST, MCA, income tax, tenders) need a DSC or eSign. Check what the receiver needs.',
  help_title: 'How to use · Ideas for work',
  tip1: 'Open the PDF, draw your signature once and press “Add as signature”. It is saved on this device, so next time you just press “Add to page”.',
  tip2: 'Offer letter or agreement: add your signature, then “Date”, then type your name with the Text tool. Save and send the new file back.',
  tip3: 'Document copies for a bank, school or job: use “Self attested” on every page. Add the KYC watermark with the PDF Merge app if the bank asks.',
  tip4: 'Shop or office: make a PNG of your rubber stamp (photo on white paper, Photo tool) and use “Stamp” on invoices and receipts.',
  tip5: 'Forms with boxes: the Form fields tool lists them; fill and tick directly. For scanned forms, use Text, Tick and Cross.',
  tip6: 'Made a mistake on paper? Scan it, cover the error with a White-out box and write the correction with Text.',
  keys_title: 'Keyboard',
  key1: 'Tab to an item, then arrow keys move it; Shift + arrow moves faster.',
  key2: '+ and − make the selected item bigger or smaller.',
  key3: 'Delete removes it; Esc unselects.',
  key4: 'Ctrl+Z undo, Ctrl+Y redo.',
  reset_help: 'Forget the saved signature and settings on this device.', reset_done: 'Reset done.',
  sample_title: 'Sample offer letter', sample_file: 'sample-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'Hinjewadi, Pune 411057 · hr@example.com',
  sample_heading: 'Offer Letter',
  sample_p1: 'Dear Priya Sharma,',
  sample_p2: 'We are happy to offer you the post of Junior Accountant from 1 November 2026 at a salary of ₹ 25,000 per month. Office hours are 9:30 am to 6:00 pm, Monday to Saturday.',
  sample_p3: 'Please fill in your name, tick the box, sign and date below, and send this letter back to accept the offer.',
  sample_name_lbl: 'Full name:', sample_agree: 'I accept this offer.', sample_sign_lbl: 'Signature:', sample_date_lbl: 'Date:',
  sample_footer: 'Sample document made by AI Pathshala for practice. Not a real offer.'
},
hi: {
  app_title: 'PDF साइन करें और भरें',
  intro: 'PDF पर यहीं साइन करें, भरें और मोहर लगाएँ: अपना हस्ताक्षर बनाएँ या टाइप करें, टेक्स्ट, तारीख, टिक, “Self attested” या स्टाम्प जोड़ें और फ़ॉर्म के खाने भरें। फ़ाइल आपके डिवाइस से बाहर नहीं जाती।',
  privacy_title: 'आपकी PDF इस डिवाइस से बाहर कभी नहीं जाती।',
  privacy_body: 'ऑफ़र लेटर, अनुबंध, KYC कॉपी और फ़ॉर्म आपके ब्राउज़र के अंदर ही साइन होते हैं। कुछ भी अपलोड नहीं होता, और यह पेज बंद करने पर फ़ाइल हट जाती है।',
  eng_loading: 'PDF इंजन लोड हो रहा है… (पहली बार इंटरनेट चाहिए)',
  eng_ready: 'PDF इंजन तैयार है',
  eng_failed: 'PDF इंजन लोड नहीं हो सका। इंटरनेट से जुड़ें और “फिर कोशिश करें” दबाएँ। एक बार लोड होने के बाद यह ऑफ़लाइन भी चलता है।',
  retry: 'फिर कोशिश करें', waiting_engine: 'PDF इंजन का इंतज़ार…', working: 'काम चल रहा है…',
  drop_title: 'PDF यहाँ छोड़ें',
  drop_hint: 'या फ़ोन/कंप्यूटर से खोलें। ऑफ़र लेटर, एग्रीमेंट, आवेदन फ़ॉर्म, आधार या PAN की कॉपी।',
  open_pdf: 'PDF खोलें', try_sample: 'नमूना पत्र आज़माएँ',
  opening: '{name} खुल रही है…', opened: '{name} खुली, {n} पेज।',
  one_page: '1 पेज', n_pages: '{n} पेज',
  err_type: '{name} PDF नहीं है। पहले इसे PDF के रूप में सेव करें।',
  err_corrupt: '{name} खुल नहीं सकी। फ़ाइल खराब हो सकती है।',
  err_locked: '{name} पर पासवर्ड लगा है। पहले PDF Compress & Convert ऐप से पासवर्ड हटाएँ, फिर यहाँ आएँ।',
  unlock_btn: 'अनलॉक टूल खोलें',
  err_big: '{name} बड़ी है ({size})। फ़ोन पर धीमी चल सकती है।',
  err_img: 'यह इमेज पढ़ी नहीं जा सकी। JPG या PNG इस्तेमाल करें।',
  err_blank: 'फ़ोटो में गहरा हस्ताक्षर नहीं मिला। सफ़ेद कागज़ पर गहरे पेन से साइन करें।',
  err_save: 'PDF लिखी नहीं जा सकी। फिर कोशिश करें या दूसरी फ़ाइल लें।',
  prev_page: 'पिछला पेज', next_page: 'अगला पेज', goto_page: 'पेज पर जाएँ',
  undo: 'पूर्ववत', redo: 'फिर से करें', it_delete: 'हटाएँ', clear_page: 'यह पेज साफ़ करें',
  confirm_clear_page: 'इस पेज पर जोड़ा हुआ सब कुछ हटाएँ?',
  items_on_page: 'इस पेज पर {n} जोड़े गए', page_canvas: 'PDF पेज', items_label: 'पेज पर जोड़ी गई चीज़ें',
  stage_hint: 'किसी चीज़ को चुनने के लिए टैप करें, खींचकर हिलाएँ, नीले कोने को खींचकर आकार बदलें। ऐरो कुंजियाँ भी हिलाती हैं।',
  added: 'पेज पर जोड़ा गया। खींचकर सही जगह रखें।', added_all: 'सभी {n} पेजों पर जोड़ा गया।', removed: 'हटा दिया गया।',
  item_sig: 'हस्ताक्षर', item_init: 'छोटे हस्ताक्षर', item_stamp: 'स्टाम्प', item_text: 'टेक्स्ट', item_date: 'तारीख', item_tick: 'टिक', item_cross: 'क्रॉस', item_white: 'सफ़ेद बॉक्स',
  tools_label: 'टूल',
  tool_sign: 'हस्ताक्षर', tool_text: 'टेक्स्ट', tool_date: 'तारीख', tool_mark: 'टिक / क्रॉस', tool_self: 'Self attested', tool_stamp: 'स्टाम्प', tool_hide: 'सफ़ेद बॉक्स', tool_form: 'फ़ॉर्म खाने',
  sig_draw: 'बनाएँ', sig_type: 'टाइप करें', sig_photo: 'फ़ोटो',
  sig_pad_hint: 'यहाँ उँगली, स्टाइलस या माउस से साइन करें।',
  sig_type_label: 'आपका नाम', sig_type_ph: 'जैसे Priya Sharma', sig_type_prev_empty: 'आपका नाम यहाँ हस्तलेख शैली में दिखेगा',
  sig_photo_pick: 'हस्ताक्षर की फ़ोटो चुनें',
  sig_photo_hint: 'सफ़ेद कागज़ पर गहरे पेन से साइन करें और साफ़ फ़ोटो लें। कागज़ अपने आप पारदर्शी हो जाता है।',
  ink: 'स्याही का रंग', col_blue: 'नीला', col_black: 'काला', col_red: 'लाल', col_green: 'हरा',
  sig_use: 'हस्ताक्षर के रूप में जोड़ें', sig_use_init: 'छोटे हस्ताक्षर के रूप में',
  sig_empty: 'पहले बनाएँ, टाइप करें या फ़ोटो चुनें।',
  sig_saved_title: 'इस डिवाइस पर सेव', sig_saved_sig: 'हस्ताक्षर', sig_saved_init: 'छोटे हस्ताक्षर',
  sig_add: 'पेज पर जोड़ें', sig_add_all: 'हर पेज पर', sig_forget: 'भूल जाएँ',
  sig_saved_note: 'सिर्फ़ इस ब्राउज़र में सेव है ताकि दोबारा काम आए। साझा कंप्यूटर पर काम के बाद “भूल जाएँ” दबाएँ।',
  sig_too_big: 'यह इमेज अगली बार के लिए याद रखने को बहुत बड़ी है, पर पेज पर जोड़ दी गई है।',
  forgotten: 'भुला दिया गया।',
  text_label: 'टेक्स्ट', text_ph: 'जैसे Approved, Paid, Priya Sharma', text_size: 'आकार', text_style: 'शैली', font_normal: 'सामान्य', font_hand: 'हस्तलेख',
  text_ink_note: 'हस्ताक्षर में चुना गया स्याही का रंग इस्तेमाल होता है।', text_add: 'टेक्स्ट जोड़ें',
  date_label: 'तारीख', date_fmt: 'फ़ॉर्मैट', date_add: 'तारीख जोड़ें',
  mark_help: 'किसी खाने पर टिक लगाएँ या विकल्प को क्रॉस करें। बड़ा करने के लिए कोना खींचें।', mark_tick: 'टिक', mark_cross: 'क्रॉस',
  self_help: 'दफ़्तर आधार, PAN, मार्कशीट और प्रमाणपत्र की “Self attested” कॉपी माँगते हैं: हर कॉपी पर यह लिखें, साइन करें और तारीख डालें। यह तीनों एक साथ जोड़ता है।',
  self_text_label: 'टेक्स्ट', self_default: 'Self attested',
  self_need_sig: 'पहले हस्ताक्षर बनाएँ (बनाएँ, टाइप करें या फ़ोटो)। यह टेक्स्ट और आज की तारीख के साथ रखा जाता है।',
  self_add: 'इस पेज पर जोड़ें', self_add_all: 'हर पेज पर',
  stamp_help: 'कंपनी की मोहर, “PAID”, “RECEIVED”, स्कूल की मोहर। पारदर्शी पृष्ठभूमि वाली PNG सबसे अच्छी दिखती है।',
  stamp_pick: 'स्टाम्प की इमेज चुनें', stamp_last: 'स्टाम्प',
  hide_help: 'पेज के किसी हिस्से को सफ़ेद बॉक्स से ढकता है, जैसे पुरानी तारीख या गलत प्रविष्टि। नीचे का टेक्स्ट फ़ाइल में रहता है, इसलिए गुप्त बातें छिपाने के लिए इसे न इस्तेमाल करें।',
  hide_add: 'सफ़ेद बॉक्स जोड़ें',
  form_none: 'इस PDF में भरने योग्य फ़ॉर्म खाने नहीं हैं। उस पर लिखने के लिए टेक्स्ट टूल इस्तेमाल करें।',
  form_xfa: 'यह XFA फ़ॉर्म है; इसके खाने यहाँ नहीं भरे जा सकते।',
  form_help: '{n} खाने मिले। यहाँ भरें; सेव करते समय वे PDF में लिख दिए जाते हैं। पेज पर हाइलाइट बॉक्स टैप करके वहाँ जाएँ।',
  form_flatten: 'सेव के बाद खाने लॉक करें (flatten)',
  field_aria: 'फ़ॉर्म खाना {name}',
  out_name: 'फ़ाइल का नाम', save_btn: 'साइन की हुई PDF सेव करें', saving: 'PDF लिखी जा रही है…',
  result_msg: '{name} ({size}) सेव हुई। भेजने से पहले एक बार खोलकर जाँच लें।', download_again: 'फिर डाउनलोड करें',
  nothing_added: 'अभी कुछ नहीं जोड़ा। पहले हस्ताक्षर, टेक्स्ट या तारीख जोड़ें।',
  legal_title: 'कृपया ध्यान दें',
  legal_body: 'यह PDF पर आपके हस्ताक्षर की तस्वीर लगाता है। यह IT Act के तहत Digital Signature Certificate (DSC) या आधार eSign नहीं है। रोज़ के कागज़ों के लिए कई दफ़्तर इसे मानते हैं, पर कुछ फ़ाइलिंग (GST, MCA, इनकम टैक्स, टेंडर) में DSC या eSign चाहिए। पाने वाले से पूछ लें।',
  help_title: 'कैसे इस्तेमाल करें · काम के लिए आइडिया',
  tip1: 'PDF खोलें, एक बार हस्ताक्षर बनाएँ और “हस्ताक्षर के रूप में जोड़ें” दबाएँ। यह इस डिवाइस पर सेव रहता है, अगली बार बस “पेज पर जोड़ें” दबाएँ।',
  tip2: 'ऑफ़र लेटर या एग्रीमेंट: हस्ताक्षर जोड़ें, फिर “तारीख”, फिर टेक्स्ट टूल से अपना नाम टाइप करें। सेव करके नई फ़ाइल वापस भेजें।',
  tip3: 'बैंक, स्कूल या नौकरी के लिए दस्तावेज़ की कॉपी: हर पेज पर “Self attested” लगाएँ। बैंक माँगे तो PDF Merge ऐप से KYC वॉटरमार्क जोड़ें।',
  tip4: 'दुकान या दफ़्तर: अपनी रबर मोहर की PNG बनाएँ (सफ़ेद कागज़ पर फ़ोटो, फ़ोटो टूल) और बिल व रसीदों पर “स्टाम्प” लगाएँ।',
  tip5: 'खानों वाले फ़ॉर्म: फ़ॉर्म खाने टूल उन्हें सूची में दिखाता है; सीधे भरें और टिक करें। स्कैन किए फ़ॉर्म के लिए टेक्स्ट, टिक और क्रॉस इस्तेमाल करें।',
  tip6: 'कागज़ पर गलती हो गई? स्कैन करें, गलती को सफ़ेद बॉक्स से ढकें और टेक्स्ट से सुधार लिखें।',
  keys_title: 'कीबोर्ड',
  key1: 'Tab से किसी चीज़ पर जाएँ, फिर ऐरो कुंजियाँ उसे हिलाती हैं; Shift + ऐरो तेज़ी से।',
  key2: '+ और − चुनी हुई चीज़ को बड़ा या छोटा करते हैं।',
  key3: 'Delete उसे हटाता है; Esc चुनाव हटाता है।',
  key4: 'Ctrl+Z पूर्ववत, Ctrl+Y फिर से।',
  reset_help: 'इस डिवाइस पर सेव हस्ताक्षर और सेटिंग भूल जाएँ।', reset_done: 'रीसेट हो गया।',
  sample_title: 'नमूना ऑफ़र लेटर', sample_file: 'namuna-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'हिंजेवाड़ी, पुणे 411057 · hr@example.com',
  sample_heading: 'ऑफ़र लेटर',
  sample_p1: 'प्रिय प्रिया शर्मा,',
  sample_p2: 'हमें खुशी है कि हम आपको 1 नवंबर 2026 से जूनियर अकाउंटेंट के पद पर ₹ 25,000 प्रति माह वेतन पर नियुक्त कर रहे हैं। कार्यालय समय सोमवार से शनिवार, सुबह 9:30 से शाम 6:00 तक है।',
  sample_p3: 'ऑफ़र स्वीकार करने के लिए नीचे अपना नाम भरें, खाने पर टिक करें, साइन करें, तारीख डालें और यह पत्र वापस भेजें।',
  sample_name_lbl: 'पूरा नाम:', sample_agree: 'मैं यह ऑफ़र स्वीकार करती/करता हूँ।', sample_sign_lbl: 'हस्ताक्षर:', sample_date_lbl: 'तारीख:',
  sample_footer: 'अभ्यास के लिए AI Pathshala द्वारा बनाया नमूना दस्तावेज़। असली ऑफ़र नहीं।'
},
bn: {
  app_title: 'PDF সাইন ও ফিল',
  intro: 'PDF-এ এখানেই সাইন করুন, ভরুন ও সিল দিন: সই আঁকুন বা টাইপ করুন, লেখা, তারিখ, টিক, “Self attested” নোট বা স্ট্যাম্প যোগ করুন, ফর্মের ঘর ভরুন। ফাইল আপনার ডিভাইসের বাইরে যায় না।',
  privacy_title: 'আপনার PDF কখনও এই ডিভাইসের বাইরে যায় না।',
  privacy_body: 'অফার লেটার, চুক্তি, KYC কপি ও ফর্ম আপনার ব্রাউজারের ভিতরেই সাইন হয়। কিছুই আপলোড হয় না, পাতা বন্ধ করলে ফাইলও মুছে যায়।',
  eng_loading: 'PDF ইঞ্জিন লোড হচ্ছে… (প্রথমবার ইন্টারনেট লাগবে)',
  eng_ready: 'PDF ইঞ্জিন তৈরি',
  eng_failed: 'PDF ইঞ্জিন লোড করা গেল না। ইন্টারনেটে যুক্ত হয়ে “আবার চেষ্টা করুন” টিপুন। একবার লোড হলে এটি অফলাইনেও চলে।',
  retry: 'আবার চেষ্টা করুন', waiting_engine: 'PDF ইঞ্জিনের জন্য অপেক্ষা…', working: 'কাজ চলছে…',
  drop_title: 'PDF এখানে ছাড়ুন',
  drop_hint: 'বা ফোন/কম্পিউটার থেকে খুলুন। অফার লেটার, চুক্তি, আবেদন ফর্ম, আধার বা PAN কপি।',
  open_pdf: 'PDF খুলুন', try_sample: 'নমুনা চিঠি দেখুন',
  opening: '{name} খুলছে…', opened: '{name} খোলা হল, {n} পাতা।',
  one_page: '1 পাতা', n_pages: '{n} পাতা',
  err_type: '{name} PDF নয়। আগে PDF হিসেবে সেভ করুন।',
  err_corrupt: '{name} খোলা গেল না। ফাইলটি নষ্ট হতে পারে।',
  err_locked: '{name}-এ পাসওয়ার্ড আছে। আগে PDF Compress & Convert অ্যাপে পাসওয়ার্ড সরান, তারপর এখানে আসুন।',
  unlock_btn: 'আনলক টুল খুলুন',
  err_big: '{name} বড় ({size})। ফোনে ধীর হতে পারে।',
  err_img: 'ছবিটি পড়া গেল না। JPG বা PNG দিন।',
  err_blank: 'ছবিতে গাঢ় সই পাওয়া যায়নি। সাদা কাগজে গাঢ় কলমে সই করুন।',
  err_save: 'PDF লেখা গেল না। আবার চেষ্টা করুন বা অন্য ফাইল নিন।',
  prev_page: 'আগের পাতা', next_page: 'পরের পাতা', goto_page: 'পাতায় যান',
  undo: 'পূর্বাবস্থা', redo: 'আবার করুন', it_delete: 'সরান', clear_page: 'এই পাতা খালি করুন',
  confirm_clear_page: 'এই পাতায় যোগ করা সব কিছু সরাবেন?',
  items_on_page: 'এই পাতায় {n}টি যোগ হয়েছে', page_canvas: 'PDF পাতা', items_label: 'পাতায় যোগ করা জিনিস',
  stage_hint: 'কোনো জিনিস বেছে নিতে টিপুন, টেনে সরান, নীল কোণ টেনে মাপ বদলান। অ্যারো কি-ও সরায়।',
  added: 'পাতায় যোগ হল। টেনে ঠিক জায়গায় রাখুন।', added_all: 'সব {n} পাতায় যোগ হল।', removed: 'সরানো হল।',
  item_sig: 'সই', item_init: 'ছোট সই', item_stamp: 'স্ট্যাম্প', item_text: 'লেখা', item_date: 'তারিখ', item_tick: 'টিক', item_cross: 'ক্রস', item_white: 'সাদা বাক্স',
  tools_label: 'টুল',
  tool_sign: 'সই', tool_text: 'লেখা', tool_date: 'তারিখ', tool_mark: 'টিক / ক্রস', tool_self: 'Self attested', tool_stamp: 'স্ট্যাম্প', tool_hide: 'সাদা বাক্স', tool_form: 'ফর্মের ঘর',
  sig_draw: 'আঁকুন', sig_type: 'টাইপ', sig_photo: 'ছবি',
  sig_pad_hint: 'এখানে আঙুল, স্টাইলাস বা মাউস দিয়ে সই করুন।',
  sig_type_label: 'আপনার নাম', sig_type_ph: 'যেমন Priya Sharma', sig_type_prev_empty: 'আপনার নাম এখানে হাতের লেখার মতো দেখাবে',
  sig_photo_pick: 'সইয়ের ছবি বেছে নিন',
  sig_photo_hint: 'সাদা কাগজে গাঢ় কলমে সই করে স্পষ্ট ছবি তুলুন। কাগজ নিজে থেকেই স্বচ্ছ হয়ে যায়।',
  ink: 'কালির রং', col_blue: 'নীল', col_black: 'কালো', col_red: 'লাল', col_green: 'সবুজ',
  sig_use: 'সই হিসেবে যোগ করুন', sig_use_init: 'ছোট সই হিসেবে',
  sig_empty: 'আগে আঁকুন, টাইপ করুন বা ছবি বেছে নিন।',
  sig_saved_title: 'এই ডিভাইসে সেভ', sig_saved_sig: 'সই', sig_saved_init: 'ছোট সই',
  sig_add: 'পাতায় যোগ', sig_add_all: 'সব পাতায়', sig_forget: 'ভুলে যান',
  sig_saved_note: 'শুধু এই ব্রাউজারে সেভ থাকে, যাতে আবার ব্যবহার করা যায়। শেয়ার করা কম্পিউটারে কাজ শেষে “ভুলে যান” টিপুন।',
  sig_too_big: 'ছবিটি পরের বারের জন্য মনে রাখার মতো ছোট নয়, তবে পাতায় যোগ হয়েছে।',
  forgotten: 'ভুলে যাওয়া হল।',
  text_label: 'লেখা', text_ph: 'যেমন Approved, Paid, Priya Sharma', text_size: 'মাপ', text_style: 'ধরন', font_normal: 'সাধারণ', font_hand: 'হাতের লেখা',
  text_ink_note: 'সইয়ের নিচে বেছে নেওয়া কালির রং ব্যবহার হয়।', text_add: 'লেখা যোগ করুন',
  date_label: 'তারিখ', date_fmt: 'ফরম্যাট', date_add: 'তারিখ যোগ করুন',
  mark_help: 'ঘরে টিক দিন বা কোনো বিকল্প কেটে দিন। বড় করতে কোণ টানুন।', mark_tick: 'টিক', mark_cross: 'ক্রস',
  self_help: 'অফিস আধার, PAN, মার্কশিট ও সার্টিফিকেটের “Self attested” কপি চায়: প্রতিটি কপিতে এটি লিখুন, সই করুন, তারিখ দিন। এটি তিনটিই একসাথে যোগ করে।',
  self_text_label: 'লেখা', self_default: 'Self attested',
  self_need_sig: 'আগে একটি সই বানান (আঁকুন, টাইপ করুন বা ছবি)। এটি লেখা ও আজকের তারিখের সাথে বসানো হয়।',
  self_add: 'এই পাতায় যোগ', self_add_all: 'সব পাতায়',
  stamp_help: 'কোম্পানির সিল, “PAID”, “RECEIVED”, স্কুলের স্ট্যাম্প। স্বচ্ছ পটভূমির PNG সবচেয়ে ভালো দেখায়।',
  stamp_pick: 'স্ট্যাম্পের ছবি বেছে নিন', stamp_last: 'স্ট্যাম্প',
  hide_help: 'পাতার একটি অংশ সাদা বাক্সে ঢেকে দেয়, যেমন পুরনো তারিখ বা ভুল এন্ট্রি। নিচের লেখা ফাইলে থেকেই যায়, তাই গোপন কিছু লুকাতে এটি ব্যবহার করবেন না।',
  hide_add: 'সাদা বাক্স যোগ করুন',
  form_none: 'এই PDF-এ ভরার মতো ফর্মের ঘর নেই। লিখতে লেখা টুল ব্যবহার করুন।',
  form_xfa: 'এটি XFA ফর্ম; এর ঘর এখানে ভরা যায় না।',
  form_help: '{n}টি ঘর পাওয়া গেছে। এখানে ভরুন; সেভ করার সময় PDF-এ লেখা হয়। পাতায় হাইলাইট বাক্স টিপে সেখানে যান।',
  form_flatten: 'সেভের পরে ঘর লক করুন (flatten)',
  field_aria: 'ফর্মের ঘর {name}',
  out_name: 'ফাইলের নাম', save_btn: 'সাইন করা PDF সেভ করুন', saving: 'PDF লেখা হচ্ছে…',
  result_msg: '{name} ({size}) সেভ হল। পাঠানোর আগে একবার খুলে দেখে নিন।', download_again: 'আবার ডাউনলোড',
  nothing_added: 'এখনও কিছু যোগ হয়নি। আগে সই, লেখা বা তারিখ যোগ করুন।',
  legal_title: 'দয়া করে খেয়াল করুন',
  legal_body: 'এটি PDF-এ আপনার সইয়ের ছবি বসায়। এটি IT Act-এর Digital Signature Certificate (DSC) বা আধার eSign নয়। রোজকার কাগজে অনেক অফিস এটি মানে, কিন্তু কিছু ফাইলিং (GST, MCA, আয়কর, টেন্ডার) DSC বা eSign চায়। গ্রহীতার কী লাগবে জেনে নিন।',
  help_title: 'কীভাবে ব্যবহার করবেন · কাজের জন্য আইডিয়া',
  tip1: 'PDF খুলুন, একবার সই আঁকুন এবং “সই হিসেবে যোগ করুন” টিপুন। এটি এই ডিভাইসে সেভ থাকে, পরের বার শুধু “পাতায় যোগ” টিপুন।',
  tip2: 'অফার লেটার বা চুক্তি: সই যোগ করুন, তারপর “তারিখ”, তারপর লেখা টুলে নাম টাইপ করুন। সেভ করে নতুন ফাইল ফেরত পাঠান।',
  tip3: 'ব্যাংক, স্কুল বা চাকরির জন্য নথির কপি: প্রতি পাতায় “Self attested” দিন। ব্যাংক চাইলে PDF Merge অ্যাপে KYC জলছাপ দিন।',
  tip4: 'দোকান বা অফিস: রাবার স্ট্যাম্পের PNG বানান (সাদা কাগজে ছবি, ছবি টুল) এবং বিল ও রসিদে “স্ট্যাম্প” দিন।',
  tip5: 'ঘরওয়ালা ফর্ম: ফর্মের ঘর টুল তালিকা দেখায়; সরাসরি ভরুন ও টিক দিন। স্ক্যান করা ফর্মে লেখা, টিক ও ক্রস ব্যবহার করুন।',
  tip6: 'কাগজে ভুল হয়েছে? স্ক্যান করুন, ভুলটি সাদা বাক্সে ঢাকুন আর লেখা দিয়ে সংশোধন লিখুন।',
  keys_title: 'কিবোর্ড',
  key1: 'Tab দিয়ে জিনিসে যান, তারপর অ্যারো কি সরায়; Shift + অ্যারো দ্রুত সরায়।',
  key2: '+ ও − বেছে নেওয়া জিনিস বড় বা ছোট করে।',
  key3: 'Delete সরায়; Esc বাছাই তোলে।',
  key4: 'Ctrl+Z পূর্বাবস্থা, Ctrl+Y আবার।',
  reset_help: 'এই ডিভাইসে সেভ করা সই ও সেটিংস ভুলে যান।', reset_done: 'রিসেট হয়েছে।',
  sample_title: 'নমুনা অফার লেটার', sample_file: 'namuna-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'হিঞ্জেওয়াড়ি, পুনে 411057 · hr@example.com',
  sample_heading: 'অফার লেটার',
  sample_p1: 'প্রিয় প্রিয়া শর্মা,',
  sample_p2: 'আমরা আনন্দের সাথে আপনাকে 1 নভেম্বর 2026 থেকে জুনিয়র অ্যাকাউন্ট্যান্ট পদে মাসিক ₹ 25,000 বেতনে নিয়োগ দিচ্ছি। অফিসের সময় সোম থেকে শনি, সকাল 9:30 থেকে সন্ধ্যা 6:00।',
  sample_p3: 'অফার গ্রহণ করতে নিচে নাম লিখুন, ঘরে টিক দিন, সই ও তারিখ দিন এবং চিঠিটি ফেরত পাঠান।',
  sample_name_lbl: 'পূর্ণ নাম:', sample_agree: 'আমি এই অফার গ্রহণ করছি।', sample_sign_lbl: 'সই:', sample_date_lbl: 'তারিখ:',
  sample_footer: 'অনুশীলনের জন্য AI Pathshala-র তৈরি নমুনা নথি। আসল অফার নয়।'
},
mr: {
  app_title: 'PDF सही करा आणि भरा',
  intro: 'PDF वर इथेच सही करा, भरा आणि शिक्का मारा: सही काढा किंवा टाइप करा, मजकूर, तारीख, टिक, “Self attested” नोंद किंवा स्टॅम्प जोडा आणि फॉर्मचे रकाने भरा. फाइल तुमच्या डिव्हाइसबाहेर जात नाही.',
  privacy_title: 'तुमची PDF या डिव्हाइसच्या बाहेर कधीच जात नाही.',
  privacy_body: 'ऑफर लेटर, करार, KYC प्रती आणि फॉर्म तुमच्या ब्राउझरमध्येच सही होतात. काहीही अपलोड होत नाही, आणि हे पान बंद केल्यावर फाइल जाते.',
  eng_loading: 'PDF इंजिन लोड होत आहे… (पहिल्यांदा इंटरनेट लागेल)',
  eng_ready: 'PDF इंजिन तयार',
  eng_failed: 'PDF इंजिन लोड होऊ शकले नाही. इंटरनेटशी जोडा आणि “पुन्हा प्रयत्न करा” दाबा. एकदा लोड झाल्यावर ते ऑफलाइनही चालते.',
  retry: 'पुन्हा प्रयत्न करा', waiting_engine: 'PDF इंजिनची वाट पाहत आहे…', working: 'काम चालू…',
  drop_title: 'PDF इथे सोडा',
  drop_hint: 'किंवा फोन/कॉम्प्युटरमधून उघडा. ऑफर लेटर, करार, अर्ज, आधार किंवा PAN ची प्रत.',
  open_pdf: 'PDF उघडा', try_sample: 'नमुना पत्र पाहा',
  opening: '{name} उघडत आहे…', opened: '{name} उघडली, {n} पाने.',
  one_page: '1 पान', n_pages: '{n} पाने',
  err_type: '{name} PDF नाही. आधी ती PDF म्हणून सेव्ह करा.',
  err_corrupt: '{name} उघडू शकली नाही. फाइल खराब असू शकते.',
  err_locked: '{name} ला पासवर्ड आहे. आधी PDF Compress & Convert ॲपने पासवर्ड काढा, मग इथे या.',
  unlock_btn: 'अनलॉक टूल उघडा',
  err_big: '{name} मोठी आहे ({size}). फोनवर हळू चालू शकते.',
  err_img: 'ही इमेज वाचता आली नाही. JPG किंवा PNG वापरा.',
  err_blank: 'फोटोत गडद सही सापडली नाही. पांढऱ्या कागदावर गडद पेनने सही करा.',
  err_save: 'PDF लिहिता आली नाही. पुन्हा प्रयत्न करा किंवा दुसरी फाइल घ्या.',
  prev_page: 'मागील पान', next_page: 'पुढील पान', goto_page: 'पानावर जा',
  undo: 'पूर्ववत', redo: 'पुन्हा करा', it_delete: 'काढा', clear_page: 'हे पान रिकामे करा',
  confirm_clear_page: 'या पानावर जोडलेले सर्व काढायचे?',
  items_on_page: 'या पानावर {n} जोडले', page_canvas: 'PDF पान', items_label: 'पानावर जोडलेल्या गोष्टी',
  stage_hint: 'गोष्ट निवडायला टॅप करा, ओढून हलवा, निळा कोपरा ओढून आकार बदला. ॅरो कीनेही हलवता येते.',
  added: 'पानावर जोडले. ओढून योग्य जागी ठेवा.', added_all: 'सर्व {n} पानांवर जोडले.', removed: 'काढले.',
  item_sig: 'सही', item_init: 'छोटी सही', item_stamp: 'स्टॅम्प', item_text: 'मजकूर', item_date: 'तारीख', item_tick: 'टिक', item_cross: 'क्रॉस', item_white: 'पांढरा चौकोन',
  tools_label: 'टूल्स',
  tool_sign: 'सही', tool_text: 'मजकूर', tool_date: 'तारीख', tool_mark: 'टिक / क्रॉस', tool_self: 'Self attested', tool_stamp: 'स्टॅम्प', tool_hide: 'पांढरा चौकोन', tool_form: 'फॉर्म रकाने',
  sig_draw: 'काढा', sig_type: 'टाइप करा', sig_photo: 'फोटो',
  sig_pad_hint: 'इथे बोट, स्टायलस किंवा माऊसने सही करा.',
  sig_type_label: 'तुमचे नाव', sig_type_ph: 'उदा. Priya Sharma', sig_type_prev_empty: 'तुमचे नाव इथे हस्ताक्षर शैलीत दिसेल',
  sig_photo_pick: 'सहीचा फोटो निवडा',
  sig_photo_hint: 'पांढऱ्या कागदावर गडद पेनने सही करा आणि स्पष्ट फोटो काढा. कागद आपोआप पारदर्शक होतो.',
  ink: 'शाईचा रंग', col_blue: 'निळा', col_black: 'काळा', col_red: 'लाल', col_green: 'हिरवा',
  sig_use: 'सही म्हणून जोडा', sig_use_init: 'छोटी सही म्हणून',
  sig_empty: 'आधी काढा, टाइप करा किंवा फोटो निवडा.',
  sig_saved_title: 'या डिव्हाइसवर सेव्ह', sig_saved_sig: 'सही', sig_saved_init: 'छोटी सही',
  sig_add: 'पानावर जोडा', sig_add_all: 'प्रत्येक पानावर', sig_forget: 'विसरा',
  sig_saved_note: 'फक्त या ब्राउझरमध्ये सेव्ह, पुन्हा वापरण्यासाठी. सामायिक कॉम्प्युटरवर काम झाल्यावर “विसरा” दाबा.',
  sig_too_big: 'ही इमेज पुढच्या वेळेसाठी लक्षात ठेवायला फार मोठी आहे, पण पानावर जोडली आहे.',
  forgotten: 'विसरले.',
  text_label: 'मजकूर', text_ph: 'उदा. Approved, Paid, Priya Sharma', text_size: 'आकार', text_style: 'शैली', font_normal: 'साधी', font_hand: 'हस्ताक्षर',
  text_ink_note: 'सहीखाली निवडलेला शाईचा रंग वापरला जातो.', text_add: 'मजकूर जोडा',
  date_label: 'तारीख', date_fmt: 'स्वरूप', date_add: 'तारीख जोडा',
  mark_help: 'रकान्यावर टिक करा किंवा पर्याय खोडा. मोठे करायला कोपरा ओढा.', mark_tick: 'टिक', mark_cross: 'क्रॉस',
  self_help: 'कार्यालये आधार, PAN, मार्कशीट आणि प्रमाणपत्रांच्या “Self attested” प्रती मागतात: प्रत्येक प्रतीवर हे लिहा, सही करा, तारीख टाका. हे तिन्ही एकत्र जोडते.',
  self_text_label: 'मजकूर', self_default: 'Self attested',
  self_need_sig: 'आधी सही बनवा (काढा, टाइप करा किंवा फोटो). ती मजकूर आणि आजच्या तारखेसह ठेवली जाते.',
  self_add: 'या पानावर जोडा', self_add_all: 'प्रत्येक पानावर',
  stamp_help: 'कंपनीचा शिक्का, “PAID”, “RECEIVED”, शाळेचा शिक्का. पारदर्शक पार्श्वभूमीची PNG सर्वात चांगली दिसते.',
  stamp_pick: 'स्टॅम्पची इमेज निवडा', stamp_last: 'स्टॅम्प',
  hide_help: 'पानाचा भाग पांढऱ्या चौकोनाने झाकतो, उदा. जुनी तारीख किंवा चुकीची नोंद. खालचा मजकूर फाइलमध्ये राहतो, म्हणून गुपिते लपवायला हे वापरू नका.',
  hide_add: 'पांढरा चौकोन जोडा',
  form_none: 'या PDF मध्ये भरण्याजोगे फॉर्म रकाने नाहीत. लिहिण्यासाठी मजकूर टूल वापरा.',
  form_xfa: 'हा XFA फॉर्म आहे; त्याचे रकाने इथे भरता येत नाहीत.',
  form_help: '{n} रकाने सापडले. इथे भरा; सेव्ह करताना ते PDF मध्ये लिहिले जातात. पानावरील हायलाइट चौकोन टॅप करून तिथे जा.',
  form_flatten: 'सेव्ह केल्यावर रकाने लॉक करा (flatten)',
  field_aria: 'फॉर्म रकाना {name}',
  out_name: 'फाइलचे नाव', save_btn: 'सही केलेली PDF सेव्ह करा', saving: 'PDF लिहिली जात आहे…',
  result_msg: '{name} ({size}) सेव्ह झाली. पाठवण्याआधी एकदा उघडून तपासा.', download_again: 'पुन्हा डाउनलोड',
  nothing_added: 'अजून काही जोडले नाही. आधी सही, मजकूर किंवा तारीख जोडा.',
  legal_title: 'कृपया लक्षात घ्या',
  legal_body: 'हे PDF वर तुमच्या सहीचे चित्र लावते. हे IT Act खालील Digital Signature Certificate (DSC) किंवा आधार eSign नाही. रोजच्या कागदपत्रांसाठी अनेक कार्यालये हे मानतात, पण काही फायलिंग (GST, MCA, आयकर, टेंडर) साठी DSC किंवा eSign लागते. घेणाऱ्याला काय हवे ते तपासा.',
  help_title: 'कसे वापरावे · कामासाठी कल्पना',
  tip1: 'PDF उघडा, एकदा सही काढा आणि “सही म्हणून जोडा” दाबा. ती या डिव्हाइसवर सेव्ह राहते, पुढच्या वेळी फक्त “पानावर जोडा” दाबा.',
  tip2: 'ऑफर लेटर किंवा करार: सही जोडा, मग “तारीख”, मग मजकूर टूलने नाव टाइप करा. सेव्ह करून नवी फाइल परत पाठवा.',
  tip3: 'बँक, शाळा किंवा नोकरीसाठी कागदपत्रांच्या प्रती: प्रत्येक पानावर “Self attested” लावा. बँकेने मागितले तर PDF Merge ॲपने KYC वॉटरमार्क लावा.',
  tip4: 'दुकान किंवा कार्यालय: तुमच्या रबर शिक्क्याची PNG बनवा (पांढऱ्या कागदावर फोटो, फोटो टूल) आणि बिल व पावत्यांवर “स्टॅम्प” लावा.',
  tip5: 'रकान्यांचे फॉर्म: फॉर्म रकाने टूल त्यांची यादी दाखवते; थेट भरा आणि टिक करा. स्कॅन केलेल्या फॉर्मसाठी मजकूर, टिक आणि क्रॉस वापरा.',
  tip6: 'कागदावर चूक झाली? स्कॅन करा, चूक पांढऱ्या चौकोनाने झाका आणि मजकूराने दुरुस्ती लिहा.',
  keys_title: 'कीबोर्ड',
  key1: 'Tab ने गोष्टीवर जा, मग ॅरो की ती हलवतात; Shift + ॅरो वेगाने.',
  key2: '+ आणि − निवडलेली गोष्ट मोठी किंवा छोटी करतात.',
  key3: 'Delete ती काढते; Esc निवड रद्द करते.',
  key4: 'Ctrl+Z पूर्ववत, Ctrl+Y पुन्हा.',
  reset_help: 'या डिव्हाइसवरील सेव्ह केलेली सही आणि सेटिंग्ज विसरा.', reset_done: 'रीसेट झाले.',
  sample_title: 'नमुना ऑफर लेटर', sample_file: 'namuna-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'हिंजवडी, पुणे 411057 · hr@example.com',
  sample_heading: 'ऑफर लेटर',
  sample_p1: 'प्रिय प्रिया शर्मा,',
  sample_p2: 'आम्हाला आनंद आहे की आम्ही तुम्हाला 1 नोव्हेंबर 2026 पासून ज्युनिअर अकाउंटंट पदावर दरमहा ₹ 25,000 वेतनावर नेमत आहोत. कार्यालयीन वेळ सोमवार ते शनिवार, सकाळी 9:30 ते संध्याकाळी 6:00.',
  sample_p3: 'ऑफर स्वीकारण्यासाठी खाली नाव भरा, रकान्यावर टिक करा, सही करा, तारीख टाका आणि हे पत्र परत पाठवा.',
  sample_name_lbl: 'पूर्ण नाव:', sample_agree: 'मी ही ऑफर स्वीकारतो/स्वीकारते.', sample_sign_lbl: 'सही:', sample_date_lbl: 'तारीख:',
  sample_footer: 'सरावासाठी AI Pathshala ने बनवलेला नमुना दस्तऐवज. खरी ऑफर नाही.'
},

gu: {
  app_title: 'PDF સહી કરો અને ભરો',
  intro: 'PDF પર અહીં જ સહી કરો, ભરો અને સિક્કો લગાવો: સહી દોરો કે ટાઇપ કરો, લખાણ, તારીખ, ટિક, “Self attested” નોંધ કે સ્ટેમ્પ ઉમેરો અને ફોર્મના ખાના ભરો. ફાઇલ તમારા ડિવાઇસની બહાર જતી નથી.',
  privacy_title: 'તમારી PDF ક્યારેય આ ડિવાઇસની બહાર જતી નથી.',
  privacy_body: 'ઑફર લેટર, કરાર, KYC નકલો અને ફોર્મ તમારા બ્રાઉઝરની અંદર જ સહી થાય છે. કંઈ અપલોડ થતું નથી, અને આ પાનું બંધ કરતાં ફાઇલ જતી રહે છે.',
  eng_loading: 'PDF એન્જિન લોડ થઈ રહ્યું છે… (પહેલી વાર ઇન્ટરનેટ જોઈએ)',
  eng_ready: 'PDF એન્જિન તૈયાર',
  eng_failed: 'PDF એન્જિન લોડ થઈ શક્યું નહીં. ઇન્ટરનેટ સાથે જોડાઓ અને “ફરી પ્રયાસ કરો” દબાવો. એક વાર લોડ થયા પછી તે ઑફલાઇન પણ ચાલે છે.',
  retry: 'ફરી પ્રયાસ કરો', waiting_engine: 'PDF એન્જિનની રાહ જોવાય છે…', working: 'કામ ચાલુ…',
  drop_title: 'PDF અહીં મૂકો',
  drop_hint: 'કે ફોન/કમ્પ્યુટરમાંથી ખોલો. ઑફર લેટર, કરાર, અરજી ફોર્મ, આધાર કે PAN ની નકલ.',
  open_pdf: 'PDF ખોલો', try_sample: 'નમૂના પત્ર અજમાવો',
  opening: '{name} ખૂલે છે…', opened: '{name} ખૂલી, {n} પાનાં.',
  one_page: '1 પાનું', n_pages: '{n} પાનાં',
  err_type: '{name} PDF નથી. પહેલાં તેને PDF તરીકે સેવ કરો.',
  err_corrupt: '{name} ખૂલી શકી નહીં. ફાઇલ ખરાબ હોઈ શકે.',
  err_locked: '{name} પર પાસવર્ડ છે. પહેલાં PDF Compress & Convert ઍપથી પાસવર્ડ દૂર કરો, પછી અહીં આવો.',
  unlock_btn: 'અનલૉક ટૂલ ખોલો',
  err_big: '{name} મોટી છે ({size}). ફોન પર ધીમી ચાલી શકે.',
  err_img: 'આ ઇમેજ વાંચી શકાઈ નહીં. JPG કે PNG વાપરો.',
  err_blank: 'ફોટામાં ઘાટી સહી મળી નહીં. સફેદ કાગળ પર ઘાટી પેનથી સહી કરો.',
  err_save: 'PDF લખી શકાઈ નહીં. ફરી પ્રયાસ કરો કે બીજી ફાઇલ લો.',
  prev_page: 'પાછલું પાનું', next_page: 'આગલું પાનું', goto_page: 'પાના પર જાઓ',
  undo: 'પાછું વાળો', redo: 'ફરી કરો', it_delete: 'દૂર કરો', clear_page: 'આ પાનું ખાલી કરો',
  confirm_clear_page: 'આ પાના પર ઉમેરેલું બધું દૂર કરવું?',
  items_on_page: 'આ પાના પર {n} ઉમેર્યાં', page_canvas: 'PDF પાનું', items_label: 'પાના પર ઉમેરેલી વસ્તુઓ',
  stage_hint: 'વસ્તુ પસંદ કરવા ટૅપ કરો, ખેંચીને ખસેડો, ભૂરો ખૂણો ખેંચીને માપ બદલો. ઍરો કી પણ ખસેડે છે.',
  added: 'પાના પર ઉમેર્યું. ખેંચીને યોગ્ય જગ્યાએ મૂકો.', added_all: 'બધાં {n} પાનાં પર ઉમેર્યું.', removed: 'દૂર કર્યું.',
  item_sig: 'સહી', item_init: 'ટૂંકી સહી', item_stamp: 'સ્ટેમ્પ', item_text: 'લખાણ', item_date: 'તારીખ', item_tick: 'ટિક', item_cross: 'ક્રોસ', item_white: 'સફેદ બૉક્સ',
  tools_label: 'ટૂલ્સ',
  tool_sign: 'સહી', tool_text: 'લખાણ', tool_date: 'તારીખ', tool_mark: 'ટિક / ક્રોસ', tool_self: 'Self attested', tool_stamp: 'સ્ટેમ્પ', tool_hide: 'સફેદ બૉક્સ', tool_form: 'ફોર્મ ખાના',
  sig_draw: 'દોરો', sig_type: 'ટાઇપ કરો', sig_photo: 'ફોટો',
  sig_pad_hint: 'અહીં આંગળી, સ્ટાઇલસ કે માઉસથી સહી કરો.',
  sig_type_label: 'તમારું નામ', sig_type_ph: 'દા.ત. Priya Sharma', sig_type_prev_empty: 'તમારું નામ અહીં હસ્તાક્ષર શૈલીમાં દેખાશે',
  sig_photo_pick: 'સહીનો ફોટો પસંદ કરો',
  sig_photo_hint: 'સફેદ કાગળ પર ઘાટી પેનથી સહી કરી સ્પષ્ટ ફોટો લો. કાગળ આપમેળે પારદર્શક થઈ જાય છે.',
  ink: 'શાહીનો રંગ', col_blue: 'ભૂરો', col_black: 'કાળો', col_red: 'લાલ', col_green: 'લીલો',
  sig_use: 'સહી તરીકે ઉમેરો', sig_use_init: 'ટૂંકી સહી તરીકે',
  sig_empty: 'પહેલાં દોરો, ટાઇપ કરો કે ફોટો પસંદ કરો.',
  sig_saved_title: 'આ ડિવાઇસ પર સેવ', sig_saved_sig: 'સહી', sig_saved_init: 'ટૂંકી સહી',
  sig_add: 'પાના પર ઉમેરો', sig_add_all: 'દરેક પાના પર', sig_forget: 'ભૂલી જાઓ',
  sig_saved_note: 'ફરી વાપરવા માટે ફક્ત આ બ્રાઉઝરમાં સેવ છે. શેર કરેલા કમ્પ્યુટર પર કામ પછી “ભૂલી જાઓ” દબાવો.',
  sig_too_big: 'આ ઇમેજ આગલી વાર માટે યાદ રાખવા બહુ મોટી છે, પણ પાના પર ઉમેરાઈ છે.',
  forgotten: 'ભૂલી ગયા.',
  text_label: 'લખાણ', text_ph: 'દા.ત. Approved, Paid, Priya Sharma', text_size: 'માપ', text_style: 'શૈલી', font_normal: 'સામાન્ય', font_hand: 'હસ્તાક્ષર',
  text_ink_note: 'સહી હેઠળ પસંદ કરેલો શાહીનો રંગ વપરાય છે.', text_add: 'લખાણ ઉમેરો',
  date_label: 'તારીખ', date_fmt: 'ફોર્મેટ', date_add: 'તારીખ ઉમેરો',
  mark_help: 'ખાનામાં ટિક કરો કે વિકલ્પ પર ક્રોસ કરો. મોટું કરવા ખૂણો ખેંચો.', mark_tick: 'ટિક', mark_cross: 'ક્રોસ',
  self_help: 'કચેરીઓ આધાર, PAN, માર્કશીટ અને પ્રમાણપત્રોની “Self attested” નકલ માગે છે: દરેક નકલ પર આ લખો, સહી કરો અને તારીખ લખો. આ ત્રણેય સાથે ઉમેરે છે.',
  self_text_label: 'લખાણ', self_default: 'Self attested',
  self_need_sig: 'પહેલાં સહી બનાવો (દોરો, ટાઇપ કરો કે ફોટો). તે લખાણ અને આજની તારીખ સાથે મૂકાય છે.',
  self_add: 'આ પાના પર ઉમેરો', self_add_all: 'દરેક પાના પર',
  stamp_help: 'કંપનીનો સિક્કો, “PAID”, “RECEIVED”, શાળાનો સિક્કો. પારદર્શક પૃષ્ઠભૂમિવાળી PNG સૌથી સારી દેખાય છે.',
  stamp_pick: 'સ્ટેમ્પની ઇમેજ પસંદ કરો', stamp_last: 'સ્ટેમ્પ',
  hide_help: 'પાનાનો ભાગ સફેદ બૉક્સથી ઢાંકે છે, દા.ત. જૂની તારીખ કે ખોટી નોંધ. નીચેનું લખાણ ફાઇલમાં રહે છે, એટલે ગુપ્ત વાતો છુપાવવા આ ન વાપરો.',
  hide_add: 'સફેદ બૉક્સ ઉમેરો',
  form_none: 'આ PDF માં ભરવા જેવા ફોર્મ ખાના નથી. લખવા માટે લખાણ ટૂલ વાપરો.',
  form_xfa: 'આ XFA ફોર્મ છે; તેના ખાના અહીં ભરી શકાતા નથી.',
  form_help: '{n} ખાના મળ્યા. અહીં ભરો; સેવ કરતી વખતે તે PDF માં લખાય છે. પાના પર હાઇલાઇટ બૉક્સ ટૅપ કરીને ત્યાં જાઓ.',
  form_flatten: 'સેવ પછી ખાના લૉક કરો (flatten)',
  field_aria: 'ફોર્મ ખાનું {name}',
  out_name: 'ફાઇલનું નામ', save_btn: 'સહી કરેલી PDF સેવ કરો', saving: 'PDF લખાય છે…',
  result_msg: '{name} ({size}) સેવ થઈ. મોકલતાં પહેલાં એક વાર ખોલીને તપાસો.', download_again: 'ફરી ડાઉનલોડ',
  nothing_added: 'હજી કંઈ ઉમેર્યું નથી. પહેલાં સહી, લખાણ કે તારીખ ઉમેરો.',
  legal_title: 'કૃપા કરીને નોંધો',
  legal_body: 'આ PDF પર તમારી સહીનું ચિત્ર મૂકે છે. તે IT Act હેઠળનું Digital Signature Certificate (DSC) કે આધાર eSign નથી. રોજના કાગળો માટે ઘણી કચેરીઓ તે સ્વીકારે છે, પણ કેટલીક ફાઇલિંગ (GST, MCA, આવકવેરો, ટેન્ડર) માટે DSC કે eSign જોઈએ. લેનારને શું જોઈએ તે તપાસો.',
  help_title: 'કેવી રીતે વાપરવું · કામ માટે વિચારો',
  tip1: 'PDF ખોલો, એક વાર સહી દોરો અને “સહી તરીકે ઉમેરો” દબાવો. તે આ ડિવાઇસ પર સેવ રહે છે, આગલી વાર ફક્ત “પાના પર ઉમેરો” દબાવો.',
  tip2: 'ઑફર લેટર કે કરાર: સહી ઉમેરો, પછી “તારીખ”, પછી લખાણ ટૂલથી નામ ટાઇપ કરો. સેવ કરીને નવી ફાઇલ પાછી મોકલો.',
  tip3: 'બેંક, શાળા કે નોકરી માટે દસ્તાવેજની નકલો: દરેક પાના પર “Self attested” મૂકો. બેંક માગે તો PDF Merge ઍપથી KYC વૉટરમાર્ક મૂકો.',
  tip4: 'દુકાન કે કચેરી: તમારા રબર સ્ટેમ્પની PNG બનાવો (સફેદ કાગળ પર ફોટો, ફોટો ટૂલ) અને બિલ તથા રસીદો પર “સ્ટેમ્પ” મૂકો.',
  tip5: 'ખાનાવાળા ફોર્મ: ફોર્મ ખાના ટૂલ તેની યાદી બતાવે છે; સીધું ભરો અને ટિક કરો. સ્કેન કરેલા ફોર્મ માટે લખાણ, ટિક અને ક્રોસ વાપરો.',
  tip6: 'કાગળ પર ભૂલ થઈ? સ્કેન કરો, ભૂલને સફેદ બૉક્સથી ઢાંકો અને લખાણથી સુધારો લખો.',
  keys_title: 'કીબોર્ડ',
  key1: 'Tab થી વસ્તુ પર જાઓ, પછી ઍરો કી તેને ખસેડે છે; Shift + ઍરો ઝડપથી.',
  key2: '+ અને − પસંદ કરેલી વસ્તુને મોટી કે નાની કરે છે.',
  key3: 'Delete તેને દૂર કરે છે; Esc પસંદગી હટાવે છે.',
  key4: 'Ctrl+Z પાછું વાળો, Ctrl+Y ફરી કરો.',
  reset_help: 'આ ડિવાઇસ પર સેવ કરેલી સહી અને સેટિંગ્સ ભૂલી જાઓ.', reset_done: 'રીસેટ થયું.',
  sample_title: 'નમૂના ઑફર લેટર', sample_file: 'namuna-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'હિંજેવાડી, પુણે 411057 · hr@example.com',
  sample_heading: 'ઑફર લેટર',
  sample_p1: 'પ્રિય પ્રિયા શર્મા,',
  sample_p2: 'અમને આનંદ છે કે અમે તમને 1 નવેમ્બર 2026 થી જુનિયર અકાઉન્ટન્ટ પદે માસિક ₹ 25,000 પગાર પર નિમણૂક આપીએ છીએ. કચેરીનો સમય સોમવારથી શનિવાર, સવારે 9:30 થી સાંજે 6:00.',
  sample_p3: 'ઑફર સ્વીકારવા નીચે નામ લખો, ખાનામાં ટિક કરો, સહી કરો, તારીખ લખો અને આ પત્ર પાછો મોકલો.',
  sample_name_lbl: 'પૂરું નામ:', sample_agree: 'હું આ ઑફર સ્વીકારું છું.', sample_sign_lbl: 'સહી:', sample_date_lbl: 'તારીખ:',
  sample_footer: 'અભ્યાસ માટે AI Pathshala એ બનાવેલો નમૂના દસ્તાવેજ. ખરી ઑફર નથી.'
},
pa: {
  app_title: 'PDF ਸਾਈਨ ਕਰੋ ਅਤੇ ਭਰੋ',
  intro: 'PDF ਉੱਤੇ ਇੱਥੇ ਹੀ ਸਾਈਨ ਕਰੋ, ਭਰੋ ਅਤੇ ਮੋਹਰ ਲਾਓ: ਆਪਣੇ ਦਸਤਖ਼ਤ ਵਾਹੋ ਜਾਂ ਟਾਈਪ ਕਰੋ, ਲਿਖਤ, ਤਾਰੀਖ਼, ਟਿੱਕ, “Self attested” ਨੋਟ ਜਾਂ ਸਟੈਂਪ ਜੋੜੋ ਅਤੇ ਫ਼ਾਰਮ ਦੇ ਖਾਨੇ ਭਰੋ। ਫ਼ਾਈਲ ਤੁਹਾਡੇ ਡਿਵਾਈਸ ਤੋਂ ਬਾਹਰ ਨਹੀਂ ਜਾਂਦੀ।',
  privacy_title: 'ਤੁਹਾਡੀ PDF ਕਦੇ ਵੀ ਇਸ ਡਿਵਾਈਸ ਤੋਂ ਬਾਹਰ ਨਹੀਂ ਜਾਂਦੀ।',
  privacy_body: 'ਆਫ਼ਰ ਲੈਟਰ, ਇਕਰਾਰਨਾਮੇ, KYC ਕਾਪੀਆਂ ਅਤੇ ਫ਼ਾਰਮ ਤੁਹਾਡੇ ਬ੍ਰਾਊਜ਼ਰ ਦੇ ਅੰਦਰ ਹੀ ਸਾਈਨ ਹੁੰਦੇ ਹਨ। ਕੁਝ ਵੀ ਅਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ, ਅਤੇ ਇਹ ਸਫ਼ਾ ਬੰਦ ਕਰਨ ਤੇ ਫ਼ਾਈਲ ਹਟ ਜਾਂਦੀ ਹੈ।',
  eng_loading: 'PDF ਇੰਜਣ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ… (ਪਹਿਲੀ ਵਾਰ ਇੰਟਰਨੈੱਟ ਚਾਹੀਦਾ ਹੈ)',
  eng_ready: 'PDF ਇੰਜਣ ਤਿਆਰ',
  eng_failed: 'PDF ਇੰਜਣ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਇੰਟਰਨੈੱਟ ਨਾਲ ਜੁੜੋ ਅਤੇ “ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ” ਦਬਾਓ। ਇੱਕ ਵਾਰ ਲੋਡ ਹੋਣ ਤੋਂ ਬਾਅਦ ਇਹ ਆਫ਼ਲਾਈਨ ਵੀ ਚੱਲਦਾ ਹੈ।',
  retry: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ', waiting_engine: 'PDF ਇੰਜਣ ਦੀ ਉਡੀਕ…', working: 'ਕੰਮ ਚੱਲ ਰਿਹਾ ਹੈ…',
  drop_title: 'PDF ਇੱਥੇ ਛੱਡੋ',
  drop_hint: 'ਜਾਂ ਫ਼ੋਨ/ਕੰਪਿਊਟਰ ਤੋਂ ਖੋਲ੍ਹੋ। ਆਫ਼ਰ ਲੈਟਰ, ਇਕਰਾਰਨਾਮਾ, ਅਰਜ਼ੀ ਫ਼ਾਰਮ, ਆਧਾਰ ਜਾਂ PAN ਦੀ ਕਾਪੀ।',
  open_pdf: 'PDF ਖੋਲ੍ਹੋ', try_sample: 'ਨਮੂਨਾ ਚਿੱਠੀ ਅਜ਼ਮਾਓ',
  opening: '{name} ਖੁੱਲ੍ਹ ਰਹੀ ਹੈ…', opened: '{name} ਖੁੱਲ੍ਹੀ, {n} ਸਫ਼ੇ।',
  one_page: '1 ਸਫ਼ਾ', n_pages: '{n} ਸਫ਼ੇ',
  err_type: '{name} PDF ਨਹੀਂ ਹੈ। ਪਹਿਲਾਂ ਇਸਨੂੰ PDF ਵਜੋਂ ਸੇਵ ਕਰੋ।',
  err_corrupt: '{name} ਖੁੱਲ੍ਹ ਨਹੀਂ ਸਕੀ। ਫ਼ਾਈਲ ਖ਼ਰਾਬ ਹੋ ਸਕਦੀ ਹੈ।',
  err_locked: '{name} ਉੱਤੇ ਪਾਸਵਰਡ ਹੈ। ਪਹਿਲਾਂ PDF Compress & Convert ਐਪ ਨਾਲ ਪਾਸਵਰਡ ਹਟਾਓ, ਫਿਰ ਇੱਥੇ ਆਓ।',
  unlock_btn: 'ਅਨਲੌਕ ਟੂਲ ਖੋਲ੍ਹੋ',
  err_big: '{name} ਵੱਡੀ ਹੈ ({size})। ਫ਼ੋਨ ਤੇ ਧੀਮੀ ਚੱਲ ਸਕਦੀ ਹੈ।',
  err_img: 'ਇਹ ਤਸਵੀਰ ਪੜ੍ਹੀ ਨਹੀਂ ਜਾ ਸਕੀ। JPG ਜਾਂ PNG ਵਰਤੋ।',
  err_blank: 'ਫ਼ੋਟੋ ਵਿੱਚ ਗੂੜ੍ਹੇ ਦਸਤਖ਼ਤ ਨਹੀਂ ਮਿਲੇ। ਸਫ਼ੈਦ ਕਾਗਜ਼ ਤੇ ਗੂੜ੍ਹੇ ਪੈੱਨ ਨਾਲ ਸਾਈਨ ਕਰੋ।',
  err_save: 'PDF ਲਿਖੀ ਨਹੀਂ ਜਾ ਸਕੀ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਹੋਰ ਫ਼ਾਈਲ ਲਓ।',
  prev_page: 'ਪਿਛਲਾ ਸਫ਼ਾ', next_page: 'ਅਗਲਾ ਸਫ਼ਾ', goto_page: 'ਸਫ਼ੇ ਤੇ ਜਾਓ',
  undo: 'ਵਾਪਸ ਲਓ', redo: 'ਮੁੜ ਕਰੋ', it_delete: 'ਹਟਾਓ', clear_page: 'ਇਹ ਸਫ਼ਾ ਖ਼ਾਲੀ ਕਰੋ',
  confirm_clear_page: 'ਇਸ ਸਫ਼ੇ ਤੇ ਜੋੜਿਆ ਸਭ ਕੁਝ ਹਟਾਉਣਾ ਹੈ?',
  items_on_page: 'ਇਸ ਸਫ਼ੇ ਤੇ {n} ਜੋੜੇ', page_canvas: 'PDF ਸਫ਼ਾ', items_label: 'ਸਫ਼ੇ ਤੇ ਜੋੜੀਆਂ ਚੀਜ਼ਾਂ',
  stage_hint: 'ਚੀਜ਼ ਚੁਣਨ ਲਈ ਟੈਪ ਕਰੋ, ਖਿੱਚ ਕੇ ਹਿਲਾਓ, ਨੀਲਾ ਕੋਨਾ ਖਿੱਚ ਕੇ ਆਕਾਰ ਬਦਲੋ। ਐਰੋ ਕੀਆਂ ਵੀ ਹਿਲਾਉਂਦੀਆਂ ਹਨ।',
  added: 'ਸਫ਼ੇ ਤੇ ਜੋੜਿਆ। ਖਿੱਚ ਕੇ ਸਹੀ ਜਗ੍ਹਾ ਰੱਖੋ।', added_all: 'ਸਾਰੇ {n} ਸਫ਼ਿਆਂ ਤੇ ਜੋੜਿਆ।', removed: 'ਹਟਾ ਦਿੱਤਾ।',
  item_sig: 'ਦਸਤਖ਼ਤ', item_init: 'ਛੋਟੇ ਦਸਤਖ਼ਤ', item_stamp: 'ਸਟੈਂਪ', item_text: 'ਲਿਖਤ', item_date: 'ਤਾਰੀਖ਼', item_tick: 'ਟਿੱਕ', item_cross: 'ਕਰਾਸ', item_white: 'ਸਫ਼ੈਦ ਡੱਬਾ',
  tools_label: 'ਟੂਲ',
  tool_sign: 'ਦਸਤਖ਼ਤ', tool_text: 'ਲਿਖਤ', tool_date: 'ਤਾਰੀਖ਼', tool_mark: 'ਟਿੱਕ / ਕਰਾਸ', tool_self: 'Self attested', tool_stamp: 'ਸਟੈਂਪ', tool_hide: 'ਸਫ਼ੈਦ ਡੱਬਾ', tool_form: 'ਫ਼ਾਰਮ ਖਾਨੇ',
  sig_draw: 'ਵਾਹੋ', sig_type: 'ਟਾਈਪ ਕਰੋ', sig_photo: 'ਫ਼ੋਟੋ',
  sig_pad_hint: 'ਇੱਥੇ ਉਂਗਲ, ਸਟਾਈਲਸ ਜਾਂ ਮਾਊਸ ਨਾਲ ਸਾਈਨ ਕਰੋ।',
  sig_type_label: 'ਤੁਹਾਡਾ ਨਾਂ', sig_type_ph: 'ਜਿਵੇਂ Priya Sharma', sig_type_prev_empty: 'ਤੁਹਾਡਾ ਨਾਂ ਇੱਥੇ ਹੱਥ-ਲਿਖਤ ਸ਼ੈਲੀ ਵਿੱਚ ਦਿਖੇਗਾ',
  sig_photo_pick: 'ਦਸਤਖ਼ਤ ਦੀ ਫ਼ੋਟੋ ਚੁਣੋ',
  sig_photo_hint: 'ਸਫ਼ੈਦ ਕਾਗਜ਼ ਤੇ ਗੂੜ੍ਹੇ ਪੈੱਨ ਨਾਲ ਸਾਈਨ ਕਰੋ ਅਤੇ ਸਾਫ਼ ਫ਼ੋਟੋ ਲਓ। ਕਾਗਜ਼ ਆਪਣੇ ਆਪ ਪਾਰਦਰਸ਼ੀ ਹੋ ਜਾਂਦਾ ਹੈ।',
  ink: 'ਸਿਆਹੀ ਦਾ ਰੰਗ', col_blue: 'ਨੀਲਾ', col_black: 'ਕਾਲਾ', col_red: 'ਲਾਲ', col_green: 'ਹਰਾ',
  sig_use: 'ਦਸਤਖ਼ਤ ਵਜੋਂ ਜੋੜੋ', sig_use_init: 'ਛੋਟੇ ਦਸਤਖ਼ਤ ਵਜੋਂ',
  sig_empty: 'ਪਹਿਲਾਂ ਵਾਹੋ, ਟਾਈਪ ਕਰੋ ਜਾਂ ਫ਼ੋਟੋ ਚੁਣੋ।',
  sig_saved_title: 'ਇਸ ਡਿਵਾਈਸ ਤੇ ਸੇਵ', sig_saved_sig: 'ਦਸਤਖ਼ਤ', sig_saved_init: 'ਛੋਟੇ ਦਸਤਖ਼ਤ',
  sig_add: 'ਸਫ਼ੇ ਤੇ ਜੋੜੋ', sig_add_all: 'ਹਰ ਸਫ਼ੇ ਤੇ', sig_forget: 'ਭੁੱਲ ਜਾਓ',
  sig_saved_note: 'ਮੁੜ ਵਰਤਣ ਲਈ ਸਿਰਫ਼ ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਸੇਵ ਹੈ। ਸਾਂਝੇ ਕੰਪਿਊਟਰ ਤੇ ਕੰਮ ਮਗਰੋਂ “ਭੁੱਲ ਜਾਓ” ਦਬਾਓ।',
  sig_too_big: 'ਇਹ ਤਸਵੀਰ ਅਗਲੀ ਵਾਰ ਲਈ ਯਾਦ ਰੱਖਣ ਲਈ ਬਹੁਤ ਵੱਡੀ ਹੈ, ਪਰ ਸਫ਼ੇ ਤੇ ਜੋੜ ਦਿੱਤੀ ਗਈ ਹੈ।',
  forgotten: 'ਭੁਲਾ ਦਿੱਤਾ।',
  text_label: 'ਲਿਖਤ', text_ph: 'ਜਿਵੇਂ Approved, Paid, Priya Sharma', text_size: 'ਆਕਾਰ', text_style: 'ਸ਼ੈਲੀ', font_normal: 'ਸਾਧਾਰਨ', font_hand: 'ਹੱਥ-ਲਿਖਤ',
  text_ink_note: 'ਦਸਤਖ਼ਤ ਹੇਠ ਚੁਣਿਆ ਸਿਆਹੀ ਦਾ ਰੰਗ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।', text_add: 'ਲਿਖਤ ਜੋੜੋ',
  date_label: 'ਤਾਰੀਖ਼', date_fmt: 'ਫ਼ਾਰਮੈਟ', date_add: 'ਤਾਰੀਖ਼ ਜੋੜੋ',
  mark_help: 'ਖਾਨੇ ਤੇ ਟਿੱਕ ਲਾਓ ਜਾਂ ਵਿਕਲਪ ਤੇ ਕਰਾਸ ਕਰੋ। ਵੱਡਾ ਕਰਨ ਲਈ ਕੋਨਾ ਖਿੱਚੋ।', mark_tick: 'ਟਿੱਕ', mark_cross: 'ਕਰਾਸ',
  self_help: 'ਦਫ਼ਤਰ ਆਧਾਰ, PAN, ਮਾਰਕਸ਼ੀਟ ਅਤੇ ਸਰਟੀਫ਼ਿਕੇਟ ਦੀਆਂ “Self attested” ਕਾਪੀਆਂ ਮੰਗਦੇ ਹਨ: ਹਰ ਕਾਪੀ ਤੇ ਇਹ ਲਿਖੋ, ਸਾਈਨ ਕਰੋ ਅਤੇ ਤਾਰੀਖ਼ ਪਾਓ। ਇਹ ਤਿੰਨੇ ਇਕੱਠੇ ਜੋੜਦਾ ਹੈ।',
  self_text_label: 'ਲਿਖਤ', self_default: 'Self attested',
  self_need_sig: 'ਪਹਿਲਾਂ ਦਸਤਖ਼ਤ ਬਣਾਓ (ਵਾਹੋ, ਟਾਈਪ ਕਰੋ ਜਾਂ ਫ਼ੋਟੋ)। ਇਹ ਲਿਖਤ ਅਤੇ ਅੱਜ ਦੀ ਤਾਰੀਖ਼ ਨਾਲ ਰੱਖੇ ਜਾਂਦੇ ਹਨ।',
  self_add: 'ਇਸ ਸਫ਼ੇ ਤੇ ਜੋੜੋ', self_add_all: 'ਹਰ ਸਫ਼ੇ ਤੇ',
  stamp_help: 'ਕੰਪਨੀ ਦੀ ਮੋਹਰ, “PAID”, “RECEIVED”, ਸਕੂਲ ਦੀ ਮੋਹਰ। ਪਾਰਦਰਸ਼ੀ ਪਿਛੋਕੜ ਵਾਲੀ PNG ਸਭ ਤੋਂ ਵਧੀਆ ਦਿਖਦੀ ਹੈ।',
  stamp_pick: 'ਸਟੈਂਪ ਦੀ ਤਸਵੀਰ ਚੁਣੋ', stamp_last: 'ਸਟੈਂਪ',
  hide_help: 'ਸਫ਼ੇ ਦਾ ਹਿੱਸਾ ਸਫ਼ੈਦ ਡੱਬੇ ਨਾਲ ਢਕਦਾ ਹੈ, ਜਿਵੇਂ ਪੁਰਾਣੀ ਤਾਰੀਖ਼ ਜਾਂ ਗ਼ਲਤ ਐਂਟਰੀ। ਹੇਠਲੀ ਲਿਖਤ ਫ਼ਾਈਲ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ, ਇਸ ਲਈ ਗੁਪਤ ਗੱਲਾਂ ਲੁਕਾਉਣ ਲਈ ਇਹ ਨਾ ਵਰਤੋ।',
  hide_add: 'ਸਫ਼ੈਦ ਡੱਬਾ ਜੋੜੋ',
  form_none: 'ਇਸ PDF ਵਿੱਚ ਭਰਨ ਵਾਲੇ ਫ਼ਾਰਮ ਖਾਨੇ ਨਹੀਂ ਹਨ। ਲਿਖਣ ਲਈ ਲਿਖਤ ਟੂਲ ਵਰਤੋ।',
  form_xfa: 'ਇਹ XFA ਫ਼ਾਰਮ ਹੈ; ਇਸਦੇ ਖਾਨੇ ਇੱਥੇ ਨਹੀਂ ਭਰੇ ਜਾ ਸਕਦੇ।',
  form_help: '{n} ਖਾਨੇ ਮਿਲੇ। ਇੱਥੇ ਭਰੋ; ਸੇਵ ਕਰਨ ਵੇਲੇ ਇਹ PDF ਵਿੱਚ ਲਿਖੇ ਜਾਂਦੇ ਹਨ। ਸਫ਼ੇ ਤੇ ਹਾਈਲਾਈਟ ਡੱਬਾ ਟੈਪ ਕਰ ਕੇ ਉੱਥੇ ਜਾਓ।',
  form_flatten: 'ਸੇਵ ਤੋਂ ਬਾਅਦ ਖਾਨੇ ਲੌਕ ਕਰੋ (flatten)',
  field_aria: 'ਫ਼ਾਰਮ ਖਾਨਾ {name}',
  out_name: 'ਫ਼ਾਈਲ ਦਾ ਨਾਂ', save_btn: 'ਸਾਈਨ ਕੀਤੀ PDF ਸੇਵ ਕਰੋ', saving: 'PDF ਲਿਖੀ ਜਾ ਰਹੀ ਹੈ…',
  result_msg: '{name} ({size}) ਸੇਵ ਹੋਈ। ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਇੱਕ ਵਾਰ ਖੋਲ੍ਹ ਕੇ ਜਾਂਚੋ।', download_again: 'ਮੁੜ ਡਾਊਨਲੋਡ',
  nothing_added: 'ਹਾਲੇ ਕੁਝ ਨਹੀਂ ਜੋੜਿਆ। ਪਹਿਲਾਂ ਦਸਤਖ਼ਤ, ਲਿਖਤ ਜਾਂ ਤਾਰੀਖ਼ ਜੋੜੋ।',
  legal_title: 'ਕਿਰਪਾ ਕਰਕੇ ਧਿਆਨ ਦਿਓ',
  legal_body: 'ਇਹ PDF ਉੱਤੇ ਤੁਹਾਡੇ ਦਸਤਖ਼ਤ ਦੀ ਤਸਵੀਰ ਲਾਉਂਦਾ ਹੈ। ਇਹ IT Act ਹੇਠ Digital Signature Certificate (DSC) ਜਾਂ ਆਧਾਰ eSign ਨਹੀਂ ਹੈ। ਰੋਜ਼ ਦੇ ਕਾਗਜ਼ਾਂ ਲਈ ਕਈ ਦਫ਼ਤਰ ਇਸਨੂੰ ਮੰਨਦੇ ਹਨ, ਪਰ ਕੁਝ ਫ਼ਾਈਲਿੰਗ (GST, MCA, ਇਨਕਮ ਟੈਕਸ, ਟੈਂਡਰ) ਲਈ DSC ਜਾਂ eSign ਚਾਹੀਦਾ ਹੈ। ਲੈਣ ਵਾਲੇ ਤੋਂ ਪੁੱਛ ਲਓ।',
  help_title: 'ਕਿਵੇਂ ਵਰਤੀਏ · ਕੰਮ ਲਈ ਸੁਝਾਅ',
  tip1: 'PDF ਖੋਲ੍ਹੋ, ਇੱਕ ਵਾਰ ਦਸਤਖ਼ਤ ਵਾਹੋ ਅਤੇ “ਦਸਤਖ਼ਤ ਵਜੋਂ ਜੋੜੋ” ਦਬਾਓ। ਇਹ ਇਸ ਡਿਵਾਈਸ ਤੇ ਸੇਵ ਰਹਿੰਦੇ ਹਨ, ਅਗਲੀ ਵਾਰ ਬਸ “ਸਫ਼ੇ ਤੇ ਜੋੜੋ” ਦਬਾਓ।',
  tip2: 'ਆਫ਼ਰ ਲੈਟਰ ਜਾਂ ਇਕਰਾਰਨਾਮਾ: ਦਸਤਖ਼ਤ ਜੋੜੋ, ਫਿਰ “ਤਾਰੀਖ਼”, ਫਿਰ ਲਿਖਤ ਟੂਲ ਨਾਲ ਆਪਣਾ ਨਾਂ ਟਾਈਪ ਕਰੋ। ਸੇਵ ਕਰ ਕੇ ਨਵੀਂ ਫ਼ਾਈਲ ਵਾਪਸ ਭੇਜੋ।',
  tip3: 'ਬੈਂਕ, ਸਕੂਲ ਜਾਂ ਨੌਕਰੀ ਲਈ ਦਸਤਾਵੇਜ਼ ਦੀਆਂ ਕਾਪੀਆਂ: ਹਰ ਸਫ਼ੇ ਤੇ “Self attested” ਲਾਓ। ਬੈਂਕ ਮੰਗੇ ਤਾਂ PDF Merge ਐਪ ਨਾਲ KYC ਵਾਟਰਮਾਰਕ ਲਾਓ।',
  tip4: 'ਦੁਕਾਨ ਜਾਂ ਦਫ਼ਤਰ: ਆਪਣੀ ਰਬੜ ਮੋਹਰ ਦੀ PNG ਬਣਾਓ (ਸਫ਼ੈਦ ਕਾਗਜ਼ ਤੇ ਫ਼ੋਟੋ, ਫ਼ੋਟੋ ਟੂਲ) ਅਤੇ ਬਿੱਲਾਂ ਤੇ ਰਸੀਦਾਂ ਉੱਤੇ “ਸਟੈਂਪ” ਲਾਓ।',
  tip5: 'ਖਾਨਿਆਂ ਵਾਲੇ ਫ਼ਾਰਮ: ਫ਼ਾਰਮ ਖਾਨੇ ਟੂਲ ਉਨ੍ਹਾਂ ਦੀ ਸੂਚੀ ਦਿਖਾਉਂਦਾ ਹੈ; ਸਿੱਧਾ ਭਰੋ ਅਤੇ ਟਿੱਕ ਕਰੋ। ਸਕੈਨ ਕੀਤੇ ਫ਼ਾਰਮ ਲਈ ਲਿਖਤ, ਟਿੱਕ ਅਤੇ ਕਰਾਸ ਵਰਤੋ।',
  tip6: 'ਕਾਗਜ਼ ਤੇ ਗ਼ਲਤੀ ਹੋ ਗਈ? ਸਕੈਨ ਕਰੋ, ਗ਼ਲਤੀ ਨੂੰ ਸਫ਼ੈਦ ਡੱਬੇ ਨਾਲ ਢਕੋ ਅਤੇ ਲਿਖਤ ਨਾਲ ਸੁਧਾਰ ਲਿਖੋ।',
  keys_title: 'ਕੀਬੋਰਡ',
  key1: 'Tab ਨਾਲ ਚੀਜ਼ ਤੇ ਜਾਓ, ਫਿਰ ਐਰੋ ਕੀਆਂ ਉਸਨੂੰ ਹਿਲਾਉਂਦੀਆਂ ਹਨ; Shift + ਐਰੋ ਤੇਜ਼ੀ ਨਾਲ।',
  key2: '+ ਅਤੇ − ਚੁਣੀ ਚੀਜ਼ ਨੂੰ ਵੱਡੀ ਜਾਂ ਛੋਟੀ ਕਰਦੇ ਹਨ।',
  key3: 'Delete ਉਸਨੂੰ ਹਟਾਉਂਦਾ ਹੈ; Esc ਚੁਣਾਵ ਹਟਾਉਂਦਾ ਹੈ।',
  key4: 'Ctrl+Z ਵਾਪਸ ਲਓ, Ctrl+Y ਮੁੜ ਕਰੋ।',
  reset_help: 'ਇਸ ਡਿਵਾਈਸ ਤੇ ਸੇਵ ਦਸਤਖ਼ਤ ਅਤੇ ਸੈਟਿੰਗਾਂ ਭੁੱਲ ਜਾਓ।', reset_done: 'ਰੀਸੈੱਟ ਹੋ ਗਿਆ।',
  sample_title: 'ਨਮੂਨਾ ਆਫ਼ਰ ਲੈਟਰ', sample_file: 'namuna-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'ਹਿੰਜੇਵਾੜੀ, ਪੁਣੇ 411057 · hr@example.com',
  sample_heading: 'ਆਫ਼ਰ ਲੈਟਰ',
  sample_p1: 'ਪਿਆਰੀ ਪ੍ਰਿਆ ਸ਼ਰਮਾ,',
  sample_p2: 'ਸਾਨੂੰ ਖ਼ੁਸ਼ੀ ਹੈ ਕਿ ਅਸੀਂ ਤੁਹਾਨੂੰ 1 ਨਵੰਬਰ 2026 ਤੋਂ ਜੂਨੀਅਰ ਅਕਾਊਂਟੈਂਟ ਦੇ ਪਦ ਤੇ ₹ 25,000 ਮਹੀਨਾ ਤਨਖ਼ਾਹ ਉੱਤੇ ਨਿਯੁਕਤ ਕਰ ਰਹੇ ਹਾਂ। ਦਫ਼ਤਰ ਦਾ ਸਮਾਂ ਸੋਮਵਾਰ ਤੋਂ ਸ਼ਨੀਵਾਰ, ਸਵੇਰੇ 9:30 ਤੋਂ ਸ਼ਾਮ 6:00 ਤੱਕ ਹੈ।',
  sample_p3: 'ਆਫ਼ਰ ਮੰਨਣ ਲਈ ਹੇਠਾਂ ਆਪਣਾ ਨਾਂ ਭਰੋ, ਖਾਨੇ ਤੇ ਟਿੱਕ ਕਰੋ, ਸਾਈਨ ਕਰੋ, ਤਾਰੀਖ਼ ਪਾਓ ਅਤੇ ਇਹ ਚਿੱਠੀ ਵਾਪਸ ਭੇਜੋ।',
  sample_name_lbl: 'ਪੂਰਾ ਨਾਂ:', sample_agree: 'ਮੈਂ ਇਹ ਆਫ਼ਰ ਮੰਨਦੀ/ਮੰਨਦਾ ਹਾਂ।', sample_sign_lbl: 'ਦਸਤਖ਼ਤ:', sample_date_lbl: 'ਤਾਰੀਖ਼:',
  sample_footer: 'ਅਭਿਆਸ ਲਈ AI Pathshala ਦੁਆਰਾ ਬਣਾਇਆ ਨਮੂਨਾ ਦਸਤਾਵੇਜ਼। ਅਸਲ ਆਫ਼ਰ ਨਹੀਂ।'
},
or: {
  app_title: 'PDF ସାଇନ କରନ୍ତୁ ଓ ଭରନ୍ତୁ',
  intro: 'PDF ଉପରେ ଏଠାରେ ହିଁ ସାଇନ କରନ୍ତୁ, ଭରନ୍ତୁ ଓ ମୋହର ଲଗାନ୍ତୁ: ଦସ୍ତଖତ ଆଙ୍କନ୍ତୁ ବା ଟାଇପ କରନ୍ତୁ, ଲେଖା, ତାରିଖ, ଟିକ, “Self attested” ନୋଟ ବା ଷ୍ଟାମ୍ପ ଯୋଡ଼ନ୍ତୁ ଏବଂ ଫର୍ମ ଘର ଭରନ୍ତୁ। ଫାଇଲ ଆପଣଙ୍କ ଡିଭାଇସ ବାହାରକୁ ଯାଏ ନାହିଁ।',
  privacy_title: 'ଆପଣଙ୍କ PDF କେବେ ବି ଏହି ଡିଭାଇସ ବାହାରକୁ ଯାଏ ନାହିଁ।',
  privacy_body: 'ଅଫର ଲେଟର, ଚୁକ୍ତିନାମା, KYC କପି ଓ ଫର୍ମ ଆପଣଙ୍କ ବ୍ରାଉଜର ଭିତରେ ହିଁ ସାଇନ ହୁଏ। କିଛି ବି ଅପଲୋଡ ହୁଏ ନାହିଁ, ଏହି ପୃଷ୍ଠା ବନ୍ଦ କଲେ ଫାଇଲ ଚାଲିଯାଏ।',
  eng_loading: 'PDF ଇଞ୍ଜିନ ଲୋଡ ହେଉଛି… (ପ୍ରଥମ ଥର ଇଣ୍ଟରନେଟ ଦରକାର)',
  eng_ready: 'PDF ଇଞ୍ଜିନ ପ୍ରସ୍ତୁତ',
  eng_failed: 'PDF ଇଞ୍ଜିନ ଲୋଡ ହୋଇପାରିଲା ନାହିଁ। ଇଣ୍ଟରନେଟ ସହ ଯୋଡ଼ି “ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ” ଦବାନ୍ତୁ। ଥରେ ଲୋଡ ହେଲେ ଏହା ଅଫଲାଇନରେ ମଧ୍ୟ ଚାଲେ।',
  retry: 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ', waiting_engine: 'PDF ଇଞ୍ଜିନ ପାଇଁ ଅପେକ୍ଷା…', working: 'କାମ ଚାଲିଛି…',
  drop_title: 'PDF ଏଠାରେ ଛାଡ଼ନ୍ତୁ',
  drop_hint: 'କିମ୍ବା ଫୋନ/କମ୍ପ୍ୟୁଟରରୁ ଖୋଲନ୍ତୁ। ଅଫର ଲେଟର, ଚୁକ୍ତି, ଆବେଦନ ଫର୍ମ, ଆଧାର ବା PAN କପି।',
  open_pdf: 'PDF ଖୋଲନ୍ତୁ', try_sample: 'ନମୁନା ଚିଠି ଦେଖନ୍ତୁ',
  opening: '{name} ଖୋଲୁଛି…', opened: '{name} ଖୋଲିଲା, {n} ପୃଷ୍ଠା।',
  one_page: '1 ପୃଷ୍ଠା', n_pages: '{n} ପୃଷ୍ଠା',
  err_type: '{name} PDF ନୁହେଁ। ପ୍ରଥମେ ଏହାକୁ PDF ଭାବରେ ସେଭ କରନ୍ତୁ।',
  err_corrupt: '{name} ଖୋଲି ପାରିଲା ନାହିଁ। ଫାଇଲ ଖରାପ ହୋଇପାରେ।',
  err_locked: '{name} ରେ ପାସୱାର୍ଡ ଅଛି। ପ୍ରଥମେ PDF Compress & Convert ଆପରେ ପାସୱାର୍ଡ ହଟାନ୍ତୁ, ତାପରେ ଏଠାକୁ ଆସନ୍ତୁ।',
  unlock_btn: 'ଅନଲକ ଟୁଲ ଖୋଲନ୍ତୁ',
  err_big: '{name} ବଡ଼ ({size})। ଫୋନରେ ଧୀର ହୋଇପାରେ।',
  err_img: 'ଏହି ଛବି ପଢ଼ି ହେଲା ନାହିଁ। JPG ବା PNG ବ୍ୟବହାର କରନ୍ତୁ।',
  err_blank: 'ଫଟୋରେ ଗାଢ଼ ଦସ୍ତଖତ ମିଳିଲା ନାହିଁ। ଧଳା କାଗଜରେ ଗାଢ଼ କଲମରେ ସାଇନ କରନ୍ତୁ।',
  err_save: 'PDF ଲେଖି ହେଲା ନାହିଁ। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ ବା ଅନ୍ୟ ଫାଇଲ ନିଅନ୍ତୁ।',
  prev_page: 'ପୂର୍ବ ପୃଷ୍ଠା', next_page: 'ପର ପୃଷ୍ଠା', goto_page: 'ପୃଷ୍ଠାକୁ ଯାଆନ୍ତୁ',
  undo: 'ପୂର୍ବାବସ୍ଥା', redo: 'ପୁଣି କରନ୍ତୁ', it_delete: 'ହଟାନ୍ତୁ', clear_page: 'ଏହି ପୃଷ୍ଠା ଖାଲି କରନ୍ତୁ',
  confirm_clear_page: 'ଏହି ପୃଷ୍ଠାରେ ଯୋଡ଼ା ସବୁ ହଟାଇବେ?',
  items_on_page: 'ଏହି ପୃଷ୍ଠାରେ {n} ଯୋଡ଼ା ହୋଇଛି', page_canvas: 'PDF ପୃଷ୍ଠା', items_label: 'ପୃଷ୍ଠାରେ ଯୋଡ଼ା ଜିନିଷ',
  stage_hint: 'ଜିନିଷ ବାଛିବାକୁ ଟ୍ୟାପ କରନ୍ତୁ, ଟାଣି ଘୁଞ୍ଚାନ୍ତୁ, ନୀଳ କୋଣ ଟାଣି ଆକାର ବଦଳାନ୍ତୁ। ଆରୋ କି ମଧ୍ୟ ଘୁଞ୍ଚାଏ।',
  added: 'ପୃଷ୍ଠାରେ ଯୋଡ଼ା ହେଲା। ଟାଣି ଠିକ୍ ସ୍ଥାନରେ ରଖନ୍ତୁ।', added_all: 'ସବୁ {n} ପୃଷ୍ଠାରେ ଯୋଡ଼ା ହେଲା।', removed: 'ହଟାଇ ଦିଆଗଲା।',
  item_sig: 'ଦସ୍ତଖତ', item_init: 'ଛୋଟ ଦସ୍ତଖତ', item_stamp: 'ଷ୍ଟାମ୍ପ', item_text: 'ଲେଖା', item_date: 'ତାରିଖ', item_tick: 'ଟିକ', item_cross: 'କ୍ରସ', item_white: 'ଧଳା ବାକ୍ସ',
  tools_label: 'ଟୁଲ',
  tool_sign: 'ଦସ୍ତଖତ', tool_text: 'ଲେଖା', tool_date: 'ତାରିଖ', tool_mark: 'ଟିକ / କ୍ରସ', tool_self: 'Self attested', tool_stamp: 'ଷ୍ଟାମ୍ପ', tool_hide: 'ଧଳା ବାକ୍ସ', tool_form: 'ଫର୍ମ ଘର',
  sig_draw: 'ଆଙ୍କନ୍ତୁ', sig_type: 'ଟାଇପ', sig_photo: 'ଫଟୋ',
  sig_pad_hint: 'ଏଠାରେ ଆଙ୍ଗୁଠି, ଷ୍ଟାଇଲସ ବା ମାଉସରେ ସାଇନ କରନ୍ତୁ।',
  sig_type_label: 'ଆପଣଙ୍କ ନାମ', sig_type_ph: 'ଯେପରି Priya Sharma', sig_type_prev_empty: 'ଆପଣଙ୍କ ନାମ ଏଠାରେ ହସ୍ତଲିଖନ ଶୈଳୀରେ ଦେଖାଯିବ',
  sig_photo_pick: 'ଦସ୍ତଖତର ଫଟୋ ବାଛନ୍ତୁ',
  sig_photo_hint: 'ଧଳା କାଗଜରେ ଗାଢ଼ କଲମରେ ସାଇନ କରି ସ୍ପଷ୍ଟ ଫଟୋ ନିଅନ୍ତୁ। କାଗଜ ନିଜେ ନିଜେ ସ୍ୱଚ୍ଛ ହୋଇଯାଏ।',
  ink: 'କାଳିର ରଙ୍ଗ', col_blue: 'ନୀଳ', col_black: 'କଳା', col_red: 'ଲାଲ', col_green: 'ସବୁଜ',
  sig_use: 'ଦସ୍ତଖତ ଭାବରେ ଯୋଡ଼ନ୍ତୁ', sig_use_init: 'ଛୋଟ ଦସ୍ତଖତ ଭାବରେ',
  sig_empty: 'ପ୍ରଥମେ ଆଙ୍କନ୍ତୁ, ଟାଇପ କରନ୍ତୁ ବା ଫଟୋ ବାଛନ୍ତୁ।',
  sig_saved_title: 'ଏହି ଡିଭାଇସରେ ସେଭ', sig_saved_sig: 'ଦସ୍ତଖତ', sig_saved_init: 'ଛୋଟ ଦସ୍ତଖତ',
  sig_add: 'ପୃଷ୍ଠାରେ ଯୋଡ଼ନ୍ତୁ', sig_add_all: 'ପ୍ରତି ପୃଷ୍ଠାରେ', sig_forget: 'ଭୁଲିଯାଆନ୍ତୁ',
  sig_saved_note: 'ପୁଣି ବ୍ୟବହାର ପାଇଁ କେବଳ ଏହି ବ୍ରାଉଜରରେ ସେଭ ଅଛି। ସାଝା କମ୍ପ୍ୟୁଟରରେ କାମ ପରେ “ଭୁଲିଯାଆନ୍ତୁ” ଦବାନ୍ତୁ।',
  sig_too_big: 'ଏହି ଛବି ପରବର୍ତ୍ତୀ ଥର ପାଇଁ ମନେ ରଖିବାକୁ ବହୁତ ବଡ଼, କିନ୍ତୁ ପୃଷ୍ଠାରେ ଯୋଡ଼ା ହୋଇଛି।',
  forgotten: 'ଭୁଲିଗଲା।',
  text_label: 'ଲେଖା', text_ph: 'ଯେପରି Approved, Paid, Priya Sharma', text_size: 'ଆକାର', text_style: 'ଶୈଳୀ', font_normal: 'ସାଧାରଣ', font_hand: 'ହସ୍ତଲିଖନ',
  text_ink_note: 'ଦସ୍ତଖତ ତଳେ ବଛା କାଳିର ରଙ୍ଗ ବ୍ୟବହାର ହୁଏ।', text_add: 'ଲେଖା ଯୋଡ଼ନ୍ତୁ',
  date_label: 'ତାରିଖ', date_fmt: 'ଫର୍ମାଟ', date_add: 'ତାରିଖ ଯୋଡ଼ନ୍ତୁ',
  mark_help: 'ଘରରେ ଟିକ ଦିଅନ୍ତୁ ବା ବିକଳ୍ପ କାଟନ୍ତୁ। ବଡ଼ କରିବାକୁ କୋଣ ଟାଣନ୍ତୁ।', mark_tick: 'ଟିକ', mark_cross: 'କ୍ରସ',
  self_help: 'ଅଫିସ ଆଧାର, PAN, ମାର୍କଶିଟ ଓ ସାର୍ଟିଫିକେଟର “Self attested” କପି ମାଗନ୍ତି: ପ୍ରତି କପିରେ ଏହା ଲେଖନ୍ତୁ, ସାଇନ କରନ୍ତୁ ଓ ତାରିଖ ଦିଅନ୍ତୁ। ଏହା ତିନୋଟି ଏକାଠି ଯୋଡ଼େ।',
  self_text_label: 'ଲେଖା', self_default: 'Self attested',
  self_need_sig: 'ପ୍ରଥମେ ଦସ୍ତଖତ ତିଆରି କରନ୍ତୁ (ଆଙ୍କନ୍ତୁ, ଟାଇପ କରନ୍ତୁ ବା ଫଟୋ)। ଏହା ଲେଖା ଓ ଆଜିର ତାରିଖ ସହ ରଖାଯାଏ।',
  self_add: 'ଏହି ପୃଷ୍ଠାରେ ଯୋଡ଼ନ୍ତୁ', self_add_all: 'ପ୍ରତି ପୃଷ୍ଠାରେ',
  stamp_help: 'କମ୍ପାନୀ ମୋହର, “PAID”, “RECEIVED”, ସ୍କୁଲ ମୋହର। ସ୍ୱଚ୍ଛ ପୃଷ୍ଠଭୂମିର PNG ସବୁଠୁ ଭଲ ଦେଖାଯାଏ।',
  stamp_pick: 'ଷ୍ଟାମ୍ପ ଛବି ବାଛନ୍ତୁ', stamp_last: 'ଷ୍ଟାମ୍ପ',
  hide_help: 'ପୃଷ୍ଠାର ଅଂଶକୁ ଧଳା ବାକ୍ସରେ ଢାଙ୍କେ, ଯେପରି ପୁରୁଣା ତାରିଖ ବା ଭୁଲ ଏଣ୍ଟ୍ରି। ତଳ ଲେଖା ଫାଇଲରେ ରହିଯାଏ, ତେଣୁ ଗୁପ୍ତ କଥା ଲୁଚାଇବାକୁ ଏହା ବ୍ୟବହାର କରନ୍ତୁ ନାହିଁ।',
  hide_add: 'ଧଳା ବାକ୍ସ ଯୋଡ଼ନ୍ତୁ',
  form_none: 'ଏହି PDF ରେ ଭରିବା ଫର୍ମ ଘର ନାହିଁ। ଲେଖିବାକୁ ଲେଖା ଟୁଲ ବ୍ୟବହାର କରନ୍ତୁ।',
  form_xfa: 'ଏହା XFA ଫର୍ମ; ଏହାର ଘର ଏଠାରେ ଭରି ହେବ ନାହିଁ।',
  form_help: '{n} ଘର ମିଳିଲା। ଏଠାରେ ଭରନ୍ତୁ; ସେଭ କଲାବେଳେ PDF ରେ ଲେଖାଯାଏ। ପୃଷ୍ଠାରେ ହାଇଲାଇଟ ବାକ୍ସ ଟ୍ୟାପ କରି ସେଠାକୁ ଯାଆନ୍ତୁ।',
  form_flatten: 'ସେଭ ପରେ ଘର ଲକ କରନ୍ତୁ (flatten)',
  field_aria: 'ଫର୍ମ ଘର {name}',
  out_name: 'ଫାଇଲ ନାମ', save_btn: 'ସାଇନ ହୋଇଥିବା PDF ସେଭ କରନ୍ତୁ', saving: 'PDF ଲେଖାଯାଉଛି…',
  result_msg: '{name} ({size}) ସେଭ ହେଲା। ପଠାଇବା ପୂର୍ବରୁ ଥରେ ଖୋଲି ଯାଞ୍ଚ କରନ୍ତୁ।', download_again: 'ପୁଣି ଡାଉନଲୋଡ',
  nothing_added: 'ଏପର୍ୟ୍ୟନ୍ତ କିଛି ଯୋଡ଼ା ହୋଇନାହିଁ। ପ୍ରଥମେ ଦସ୍ତଖତ, ଲେଖା ବା ତାରିଖ ଯୋଡ଼ନ୍ତୁ।',
  legal_title: 'ଦୟାକରି ଧ୍ୟାନ ଦିଅନ୍ତୁ',
  legal_body: 'ଏହା PDF ରେ ଆପଣଙ୍କ ଦସ୍ତଖତର ଛବି ରଖେ। ଏହା IT Act ଅଧୀନ Digital Signature Certificate (DSC) ବା ଆଧାର eSign ନୁହେଁ। ଦୈନନ୍ଦିନ କାଗଜ ପାଇଁ ଅନେକ ଅଫିସ ଏହା ମାନନ୍ତି, କିନ୍ତୁ କିଛି ଫାଇଲିଂ (GST, MCA, ଆୟକର, ଟେଣ୍ଡର) ପାଇଁ DSC ବା eSign ଦରକାର। ଗ୍ରହୀତା କଣ ଚାହେଁ ଯାଞ୍ଚ କରନ୍ତୁ।',
  help_title: 'କିପରି ବ୍ୟବହାର କରିବେ · କାମ ପାଇଁ ଧାରଣା',
  tip1: 'PDF ଖୋଲନ୍ତୁ, ଥରେ ଦସ୍ତଖତ ଆଙ୍କନ୍ତୁ ଓ “ଦସ୍ତଖତ ଭାବରେ ଯୋଡ଼ନ୍ତୁ” ଦବାନ୍ତୁ। ଏହା ଏହି ଡିଭାଇସରେ ସେଭ ରହେ, ପରବର୍ତ୍ତୀ ଥର କେବଳ “ପୃଷ୍ଠାରେ ଯୋଡ଼ନ୍ତୁ” ଦବାନ୍ତୁ।',
  tip2: 'ଅଫର ଲେଟର ବା ଚୁକ୍ତି: ଦସ୍ତଖତ ଯୋଡ଼ନ୍ତୁ, ତାପରେ “ତାରିଖ”, ତାପରେ ଲେଖା ଟୁଲରେ ନାମ ଟାଇପ କରନ୍ତୁ। ସେଭ କରି ନୂଆ ଫାଇଲ ଫେରାନ୍ତୁ।',
  tip3: 'ବ୍ୟାଙ୍କ, ସ୍କୁଲ ବା ଚାକିରି ପାଇଁ ଦଲିଲ କପି: ପ୍ରତି ପୃଷ୍ଠାରେ “Self attested” ଦିଅନ୍ତୁ। ବ୍ୟାଙ୍କ ମାଗିଲେ PDF Merge ଆପରେ KYC ୱାଟରମାର୍କ ଦିଅନ୍ତୁ।',
  tip4: 'ଦୋକାନ ବା ଅଫିସ: ରବର ମୋହରର PNG ତିଆରି କରନ୍ତୁ (ଧଳା କାଗଜରେ ଫଟୋ, ଫଟୋ ଟୁଲ) ଓ ବିଲ୍ ଓ ରସିଦରେ “ଷ୍ଟାମ୍ପ” ଦିଅନ୍ତୁ।',
  tip5: 'ଘର ଥିବା ଫର୍ମ: ଫର୍ମ ଘର ଟୁଲ ତାଲିକା ଦେଖାଏ; ସିଧା ଭରନ୍ତୁ ଓ ଟିକ କରନ୍ତୁ। ସ୍କାନ ଫର୍ମ ପାଇଁ ଲେଖା, ଟିକ ଓ କ୍ରସ ବ୍ୟବହାର କରନ୍ତୁ।',
  tip6: 'କାଗଜରେ ଭୁଲ ହେଲା? ସ୍କାନ କରନ୍ତୁ, ଭୁଲକୁ ଧଳା ବାକ୍ସରେ ଢାଙ୍କନ୍ତୁ ଓ ଲେଖାରେ ସଂଶୋଧନ ଲେଖନ୍ତୁ।',
  keys_title: 'କୀବୋର୍ଡ',
  key1: 'Tab ରେ ଜିନିଷକୁ ଯାଆନ୍ତୁ, ତାପରେ ଆରୋ କି ଘୁଞ୍ଚାଏ; Shift + ଆରୋ ଶୀଘ୍ର।',
  key2: '+ ଓ − ବଛା ଜିନିଷକୁ ବଡ଼ ବା ଛୋଟ କରେ।',
  key3: 'Delete ହଟାଏ; Esc ବଛା ହଟାଏ।',
  key4: 'Ctrl+Z ପୂର୍ବାବସ୍ଥା, Ctrl+Y ପୁଣି।',
  reset_help: 'ଏହି ଡିଭାଇସରେ ସେଭ ଦସ୍ତଖତ ଓ ସେଟିଂ ଭୁଲିଯାଆନ୍ତୁ।', reset_done: 'ରିସେଟ ହେଲା।',
  sample_title: 'ନମୁନା ଅଫର ଲେଟର', sample_file: 'namuna-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'ହିଞ୍ଜେୱାଡ଼ି, ପୁଣେ 411057 · hr@example.com',
  sample_heading: 'ଅଫର ଲେଟର',
  sample_p1: 'ପ୍ରିୟ ପ୍ରିୟା ଶର୍ମା,',
  sample_p2: 'ଆମେ ଆନନ୍ଦର ସହ ଆପଣଙ୍କୁ 1 ନଭେମ୍ବର 2026 ରୁ ଜୁନିଅର ଆକାଉଣ୍ଟାଣ୍ଟ ପଦରେ ମାସିକ ₹ 25,000 ଦରମାରେ ନିଯୁକ୍ତି ଦେଉଛୁ। ଅଫିସ ସମୟ ସୋମବାରରୁ ଶନିବାର, ସକାଳ 9:30 ରୁ ସନ୍ଧ୍ୟା 6:00।',
  sample_p3: 'ଅଫର ଗ୍ରହଣ କରିବାକୁ ତଳେ ନାମ ଲେଖନ୍ତୁ, ଘରରେ ଟିକ କରନ୍ତୁ, ସାଇନ ଓ ତାରିଖ ଦିଅନ୍ତୁ ଏବଂ ଏହି ଚିଠି ଫେରାନ୍ତୁ।',
  sample_name_lbl: 'ପୂରା ନାମ:', sample_agree: 'ମୁଁ ଏହି ଅଫର ଗ୍ରହଣ କରୁଛି।', sample_sign_lbl: 'ଦସ୍ତଖତ:', sample_date_lbl: 'ତାରିଖ:',
  sample_footer: 'ଅଭ୍ୟାସ ପାଇଁ AI Pathshala ଦ୍ୱାରା ତିଆରି ନମୁନା ଦଲିଲ। ପ୍ରକୃତ ଅଫର ନୁହେଁ।'
},

ta: {
  app_title: 'PDF கையொப்பமிட்டு நிரப்பு',
  intro: 'PDF-இல் இங்கேயே கையொப்பமிடுங்கள், நிரப்புங்கள், முத்திரை வையுங்கள்: உங்கள் கையொப்பத்தை வரையுங்கள் அல்லது தட்டச்சு செய்யுங்கள், எழுத்து, தேதி, டிக், “Self attested” குறிப்பு அல்லது முத்திரை சேர்த்து, படிவக் கட்டங்களை நிரப்புங்கள். கோப்பு உங்கள் சாதனத்தை விட்டு வெளியே போகாது.',
  privacy_title: 'உங்கள் PDF இந்தச் சாதனத்தை விட்டு வெளியே போகாது.',
  privacy_body: 'வேலை வாய்ப்புக் கடிதம், ஒப்பந்தம், KYC நகல்கள், படிவங்கள் எல்லாம் உங்கள் உலாவிக்குள்ளேயே கையொப்பமிடப்படுகின்றன. எதுவும் பதிவேற்றப்படாது; இந்தப் பக்கத்தை மூடியதும் கோப்பு போய்விடும்.',
  eng_loading: 'PDF இயந்திரம் ஏறுகிறது… (முதல் முறை இணையம் தேவை)',
  eng_ready: 'PDF இயந்திரம் தயார்',
  eng_failed: 'PDF இயந்திரத்தை ஏற்ற முடியவில்லை. இணையத்துடன் இணைந்து “மீண்டும் முயல்” அழுத்துங்கள். ஒருமுறை ஏறிய பிறகு இணையம் இல்லாமலும் வேலை செய்யும்.',
  retry: 'மீண்டும் முயல்', waiting_engine: 'PDF இயந்திரத்துக்காகக் காத்திருக்கிறது…', working: 'வேலை நடக்கிறது…',
  drop_title: 'PDF-ஐ இங்கே போடுங்கள்',
  drop_hint: 'அல்லது உங்கள் போன் அல்லது கணினியிலிருந்து திறங்கள். வேலை வாய்ப்புக் கடிதம், ஒப்பந்தம், விண்ணப்பப் படிவம், ஆதார் அல்லது PAN நகல்.',
  open_pdf: 'PDF திற', try_sample: 'மாதிரிக் கடிதத்தை முயலுங்கள்',
  opening: '{name} திறக்கிறது…', opened: '{name} திறந்தது, {n} பக்கங்கள்.',
  one_page: '1 பக்கம்', n_pages: '{n} பக்கங்கள்',
  err_type: '{name} ஒரு PDF அல்ல. முதலில் அதை PDF ஆகச் சேமியுங்கள்.',
  err_corrupt: '{name} திறக்க முடியவில்லை. கோப்பு சேதமடைந்திருக்கலாம்.',
  err_locked: '{name} கடவுச்சொல்லால் பூட்டப்பட்டுள்ளது. முதலில் PDF Compress & Convert செயலியில் கடவுச்சொல்லை நீக்கிவிட்டுத் திரும்பி வாருங்கள்.',
  unlock_btn: 'பூட்டு நீக்கும் கருவியைத் திற',
  err_big: '{name} பெரியது ({size}). போனில் மெதுவாக இருக்கலாம்.',
  err_img: 'அந்தப் படத்தைப் படிக்க முடியவில்லை. JPG அல்லது PNG பயன்படுத்துங்கள்.',
  err_blank: 'புகைப்படத்தில் அடர் நிறக் கையொப்பம் கிடைக்கவில்லை. வெள்ளைத் தாளில் அடர் நிறப் பேனாவால் கையொப்பமிடுங்கள்.',
  err_save: 'PDF-ஐ எழுத முடியவில்லை. மீண்டும் முயலுங்கள் அல்லது வேறு கோப்பைப் பயன்படுத்துங்கள்.',
  prev_page: 'முந்தைய பக்கம்', next_page: 'அடுத்த பக்கம்', goto_page: 'பக்கத்துக்குச் செல்',
  undo: 'செயல்தவிர்', redo: 'மீண்டும் செய்', it_delete: 'நீக்கு', clear_page: 'இந்தப் பக்கத்தைச் சுத்தம் செய்',
  confirm_clear_page: 'இந்தப் பக்கத்தில் நீங்கள் சேர்த்த எல்லாவற்றையும் நீக்கவா?',
  items_on_page: 'இந்தப் பக்கத்தில் {n} சேர்க்கப்பட்டன', page_canvas: 'PDF பக்கம்', items_label: 'பக்கத்தில் சேர்த்தவை',
  stage_hint: 'ஒன்றைத் தேர்ந்தெடுக்கத் தட்டுங்கள், நகர்த்த இழுங்கள், அளவை மாற்ற நீல மூலையை இழுங்கள். அம்புக்குறி விசைகளாலும் நகர்த்தலாம்.',
  added: 'பக்கத்தில் சேர்க்கப்பட்டது. இழுத்துச் சரியான இடத்தில் வையுங்கள்.', added_all: 'எல்லா {n} பக்கங்களிலும் சேர்க்கப்பட்டது.', removed: 'நீக்கப்பட்டது.',
  item_sig: 'கையொப்பம்', item_init: 'சுருக்கக் கையொப்பம்', item_stamp: 'முத்திரை', item_text: 'எழுத்து', item_date: 'தேதி', item_tick: 'டிக்', item_cross: 'பெருக்கல் குறி', item_white: 'வெள்ளைப் பெட்டி',
  tools_label: 'கருவிகள்',
  tool_sign: 'கையொப்பம்', tool_text: 'எழுத்து', tool_date: 'தேதி', tool_mark: 'டிக் / பெருக்கல்', tool_self: 'Self attested', tool_stamp: 'முத்திரை', tool_hide: 'வெள்ளை மறைப்பு', tool_form: 'படிவக் கட்டங்கள்',
  sig_draw: 'வரை', sig_type: 'தட்டச்சு', sig_photo: 'புகைப்படம்',
  sig_pad_hint: 'உங்கள் விரல், ஸ்டைலஸ் அல்லது மவுஸால் இங்கே கையொப்பமிடுங்கள்.',
  sig_type_label: 'உங்கள் பெயர்', sig_type_ph: 'எ.கா. Priya Sharma', sig_type_prev_empty: 'உங்கள் பெயர் கையெழுத்து வடிவில் இங்கே தெரியும்',
  sig_photo_pick: 'உங்கள் கையொப்பப் புகைப்படத்தைத் தேர்ந்தெடுங்கள்',
  sig_photo_hint: 'வெள்ளைத் தாளில் அடர் நிறப் பேனாவால் கையொப்பமிட்டுத் தெளிவான புகைப்படம் எடுங்கள். தாள் தானாகவே ஒளிபுகும்படி ஆகிவிடும்.',
  ink: 'மை நிறம்', col_blue: 'நீலம்', col_black: 'கருப்பு', col_red: 'சிவப்பு', col_green: 'பச்சை',
  sig_use: 'கையொப்பமாகச் சேர்', sig_use_init: 'சுருக்கக் கையொப்பமாகச் சேர்',
  sig_empty: 'முதலில் வரையுங்கள், தட்டச்சு செய்யுங்கள் அல்லது புகைப்படம் தேர்ந்தெடுங்கள்.',
  sig_saved_title: 'இந்தச் சாதனத்தில் சேமித்தவை', sig_saved_sig: 'கையொப்பம்', sig_saved_init: 'சுருக்கக் கையொப்பம்',
  sig_add: 'பக்கத்தில் சேர்', sig_add_all: 'எல்லாப் பக்கங்களிலும்', sig_forget: 'மற',
  sig_saved_note: 'மீண்டும் பயன்படுத்த இந்த உலாவியில் மட்டுமே சேமிக்கப்பட்டுள்ளது. பகிரப்பட்ட கணினியில் வேலை முடிந்ததும் “மற” அழுத்துங்கள்.',
  sig_too_big: 'அடுத்த முறைக்கு நினைவில் வைக்க இந்தப் படம் மிகப் பெரியது, ஆனால் பக்கத்தில் சேர்க்கப்பட்டுவிட்டது.',
  forgotten: 'மறக்கப்பட்டது.',
  text_label: 'எழுத்து', text_ph: 'எ.கா. Approved, Paid, Priya Sharma', text_size: 'அளவு', text_style: 'பாணி', font_normal: 'சாதாரணம்', font_hand: 'கையெழுத்து',
  text_ink_note: 'கையொப்பத்தில் தேர்ந்த மை நிறமே பயன்படும்.', text_add: 'எழுத்தைச் சேர்',
  date_label: 'தேதி', date_fmt: 'வடிவம்', date_add: 'தேதியைச் சேர்',
  mark_help: 'ஒரு கட்டத்தில் டிக் போடுங்கள் அல்லது ஒரு விருப்பத்தை அடித்துவிடுங்கள். பெரிதாக்க மூலையை இழுங்கள்.', mark_tick: 'டிக்', mark_cross: 'பெருக்கல் குறி',
  self_help: 'அலுவலகங்கள் ஆதார், PAN, மதிப்பெண் சான்றிதழ், சான்றிதழ்களின் “Self attested” நகல்களைக் கேட்கும்: ஒவ்வொரு நகலிலும் அதை எழுதி, கையொப்பமிட்டு, தேதி போடுங்கள். இது மூன்றையும் ஒன்றாகச் சேர்க்கும்.',
  self_text_label: 'எழுத்து', self_default: 'Self attested',
  self_need_sig: 'முதலில் ஒரு கையொப்பம் உருவாக்குங்கள் (வரை, தட்டச்சு அல்லது புகைப்படம்). அது எழுத்துடனும் இன்றைய தேதியுடனும் சேர்த்து வைக்கப்படும்.',
  self_add: 'இந்தப் பக்கத்தில் சேர்', self_add_all: 'எல்லாப் பக்கங்களிலும்',
  stamp_help: 'நிறுவன முத்திரை, “PAID”, “RECEIVED”, பள்ளி முத்திரை. ஒளிபுகும் பின்னணி கொண்ட PNG மிக அழகாகத் தெரியும்.',
  stamp_pick: 'முத்திரைப் படத்தைத் தேர்ந்தெடு', stamp_last: 'முத்திரை',
  hide_help: 'பக்கத்தின் ஒரு பகுதியை வெள்ளைப் பெட்டியால் மூடும், எ.கா. பழைய தேதி அல்லது தவறான பதிவு. அதன் கீழுள்ள எழுத்து கோப்பில் இன்னும் இருக்கும், எனவே ரகசியங்களை மறைக்க இதைப் பயன்படுத்தாதீர்கள்.',
  hide_add: 'வெள்ளைப் பெட்டியைச் சேர்',
  form_none: 'இந்த PDF-இல் நிரப்பக்கூடிய படிவக் கட்டங்கள் இல்லை. அதில் எழுத “எழுத்து” கருவியைப் பயன்படுத்துங்கள்.',
  form_xfa: 'இது ஒரு XFA படிவம்; இதன் கட்டங்களை இங்கே நிரப்ப முடியாது.',
  form_help: '{n} கட்டங்கள் கிடைத்தன. இங்கே நிரப்புங்கள்; சேமிக்கும்போது அவை PDF-இல் எழுதப்படும். அங்கே செல்லப் பக்கத்திலுள்ள ஒளிரும் பெட்டியைத் தட்டுங்கள்.',
  form_flatten: 'சேமித்த பிறகு கட்டங்களைப் பூட்டு (flatten)',
  field_aria: 'படிவக் கட்டம் {name}',
  out_name: 'கோப்பின் பெயர்', save_btn: 'கையொப்பமிட்ட PDF-ஐச் சேமி', saving: 'PDF எழுதப்படுகிறது…',
  result_msg: '{name} ({size}) சேமிக்கப்பட்டது. அனுப்பும் முன் ஒருமுறை திறந்து சரிபாருங்கள்.', download_again: 'மீண்டும் பதிவிறக்கு',
  nothing_added: 'இன்னும் எதுவும் சேர்க்கவில்லை. முதலில் கையொப்பம், எழுத்து அல்லது தேதியைச் சேருங்கள்.',
  legal_title: 'கவனிக்கவும்',
  legal_body: 'இது உங்கள் கையொப்பத்தின் படத்தை PDF-இல் வைக்கிறது. இது IT Act-இன் கீழ் வரும் Digital Signature Certificate (DSC) அல்லது ஆதார் eSign அல்ல. அன்றாடக் காகிதங்களுக்குப் பல அலுவலகங்கள் இதை ஏற்கும், ஆனால் சில தாக்கல்களுக்கு (GST, MCA, வருமான வரி, டெண்டர்) DSC அல்லது eSign தேவை. பெறுபவருக்கு என்ன தேவை என்று கேட்டுக்கொள்ளுங்கள்.',
  help_title: 'எப்படிப் பயன்படுத்துவது · வேலைக்கான யோசனைகள்',
  tip1: 'PDF-ஐத் திறந்து, ஒருமுறை கையொப்பம் வரைந்து “கையொப்பமாகச் சேர்” அழுத்துங்கள். அது இந்தச் சாதனத்தில் சேமிக்கப்படும், அடுத்த முறை “பக்கத்தில் சேர்” அழுத்தினால் போதும்.',
  tip2: 'வேலை வாய்ப்புக் கடிதம் அல்லது ஒப்பந்தம்: கையொப்பம் சேருங்கள், பிறகு “தேதி”, பிறகு “எழுத்து” கருவியால் உங்கள் பெயரைத் தட்டச்சு செய்யுங்கள். சேமித்துப் புதிய கோப்பைத் திருப்பி அனுப்புங்கள்.',
  tip3: 'வங்கி, பள்ளி அல்லது வேலைக்கான ஆவண நகல்கள்: ஒவ்வொரு பக்கத்திலும் “Self attested” பயன்படுத்துங்கள். வங்கி கேட்டால் PDF Merge செயலியில் KYC நீர்க்குறியைச் சேருங்கள்.',
  tip4: 'கடை அல்லது அலுவலகம்: உங்கள் ரப்பர் முத்திரையின் PNG உருவாக்குங்கள் (வெள்ளைத் தாளில் புகைப்படம், புகைப்படக் கருவி), பில்கள், ரசீதுகளில் “முத்திரை” பயன்படுத்துங்கள்.',
  tip5: 'கட்டங்கள் உள்ள படிவங்கள்: “படிவக் கட்டங்கள்” கருவி அவற்றைப் பட்டியலிடும்; நேரடியாக நிரப்பி டிக் போடுங்கள். ஸ்கேன் செய்த படிவங்களுக்கு எழுத்து, டிக், பெருக்கல் குறி பயன்படுத்துங்கள்.',
  tip6: 'காகிதத்தில் தவறு செய்துவிட்டீர்களா? ஸ்கேன் செய்து, தவற்றை வெள்ளைப் பெட்டியால் மூடி, திருத்தத்தை “எழுத்து” மூலம் எழுதுங்கள்.',
  keys_title: 'விசைப்பலகை',
  key1: 'Tab மூலம் ஒன்றுக்குச் சென்று, அம்புக்குறி விசைகளால் நகர்த்துங்கள்; Shift + அம்புக்குறி வேகமாக நகர்த்தும்.',
  key2: '+ மற்றும் − தேர்ந்தெடுத்ததைப் பெரிதாக்கும் அல்லது சிறிதாக்கும்.',
  key3: 'Delete அதை நீக்கும்; Esc தேர்வை நீக்கும்.',
  key4: 'Ctrl+Z செயல்தவிர், Ctrl+Y மீண்டும் செய்.',
  reset_help: 'இந்தச் சாதனத்தில் சேமித்த கையொப்பத்தையும் அமைப்புகளையும் மறந்துவிடு.', reset_done: 'மீட்டமைக்கப்பட்டது.',
  sample_title: 'மாதிரி வேலை வாய்ப்புக் கடிதம்', sample_file: 'maadhiri-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'ஹிஞ்ஜேவாடி, புனே 411057 · hr@example.com',
  sample_heading: 'வேலை வாய்ப்புக் கடிதம்',
  sample_p1: 'அன்புள்ள பிரியா சர்மா,',
  sample_p2: '1 நவம்பர் 2026 முதல் மாதம் ₹ 25,000 சம்பளத்தில் ஜூனியர் அக்கவுண்டன்ட் பணியை உங்களுக்கு வழங்குவதில் மகிழ்ச்சி அடைகிறோம். அலுவலக நேரம் திங்கள் முதல் சனி வரை, காலை 9:30 முதல் மாலை 6:00 வரை.',
  sample_p3: 'இந்த வாய்ப்பை ஏற்க, கீழே உங்கள் பெயரை நிரப்பி, கட்டத்தில் டிக் போட்டு, கையொப்பமிட்டு, தேதி போட்டு, இந்தக் கடிதத்தைத் திருப்பி அனுப்புங்கள்.',
  sample_name_lbl: 'முழுப் பெயர்:', sample_agree: 'இந்த வாய்ப்பை ஏற்கிறேன்.', sample_sign_lbl: 'கையொப்பம்:', sample_date_lbl: 'தேதி:',
  sample_footer: 'பயிற்சிக்காக AI Pathshala உருவாக்கிய மாதிரி ஆவணம். உண்மையான வேலை வாய்ப்பு அல்ல.'
},

te: {
  app_title: 'PDF సంతకం చేసి నింపండి',
  intro: 'PDF మీద ఇక్కడే సంతకం చేయండి, నింపండి, ముద్ర వేయండి: మీ సంతకం గీయండి లేదా టైప్ చేయండి, అక్షరాలు, తేదీ, టిక్, “Self attested” గమనిక లేదా ముద్ర జోడించండి, ఫారం గడులు నింపండి. ఫైల్ మీ పరికరం దాటి బయటకు వెళ్లదు.',
  privacy_title: 'మీ PDF ఈ పరికరం దాటి ఎప్పుడూ బయటకు వెళ్లదు.',
  privacy_body: 'ఆఫర్ లెటర్లు, ఒప్పందాలు, KYC కాపీలు, ఫారాలు అన్నీ మీ బ్రౌజర్ లోపలే సంతకం అవుతాయి. ఏదీ అప్‌లోడ్ కాదు; ఈ పేజీ మూసేయగానే ఫైల్ పోతుంది.',
  eng_loading: 'PDF ఇంజిన్ లోడ్ అవుతోంది… (మొదటిసారి ఇంటర్నెట్ కావాలి)',
  eng_ready: 'PDF ఇంజిన్ సిద్ధం',
  eng_failed: 'PDF ఇంజిన్ లోడ్ కాలేదు. ఇంటర్నెట్‌కు కనెక్ట్ అయి “మళ్లీ ప్రయత్నించు” నొక్కండి. ఒకసారి లోడ్ అయ్యాక ఇంటర్నెట్ లేకుండానూ పనిచేస్తుంది.',
  retry: 'మళ్లీ ప్రయత్నించు', waiting_engine: 'PDF ఇంజిన్ కోసం ఎదురుచూస్తోంది…', working: 'పని జరుగుతోంది…',
  drop_title: 'PDF ని ఇక్కడ వదలండి',
  drop_hint: 'లేదా మీ ఫోన్ లేదా కంప్యూటర్ నుంచి తెరవండి. ఆఫర్ లెటర్, ఒప్పందం, దరఖాస్తు ఫారం, ఆధార్ లేదా PAN కాపీ.',
  open_pdf: 'PDF తెరువు', try_sample: 'నమూనా లేఖను ప్రయత్నించండి',
  opening: '{name} తెరుచుకుంటోంది…', opened: '{name} తెరుచుకుంది, {n} పేజీలు.',
  one_page: '1 పేజీ', n_pages: '{n} పేజీలు',
  err_type: '{name} PDF కాదు. ముందు దాన్ని PDF గా సేవ్ చేయండి.',
  err_corrupt: '{name} తెరవలేకపోయాం. ఫైల్ పాడై ఉండవచ్చు.',
  err_locked: '{name} కి పాస్‌వర్డ్ ఉంది. ముందు PDF Compress & Convert యాప్‌తో పాస్‌వర్డ్ తీసేసి, మళ్లీ ఇక్కడికి రండి.',
  unlock_btn: 'అన్‌లాక్ టూల్ తెరువు',
  err_big: '{name} పెద్దది ({size}). ఫోన్‌లో నెమ్మదిగా ఉండవచ్చు.',
  err_img: 'ఆ చిత్రాన్ని చదవలేకపోయాం. JPG లేదా PNG వాడండి.',
  err_blank: 'ఫోటోలో ముదురు రంగు సంతకం కనిపించలేదు. తెల్ల కాగితంపై ముదురు పెన్నుతో సంతకం చేయండి.',
  err_save: 'PDF రాయలేకపోయాం. మళ్లీ ప్రయత్నించండి లేదా వేరే ఫైల్ వాడండి.',
  prev_page: 'ముందు పేజీ', next_page: 'తర్వాతి పేజీ', goto_page: 'పేజీకి వెళ్లు',
  undo: 'రద్దు చేయి', redo: 'మళ్లీ చేయి', it_delete: 'తీసేయి', clear_page: 'ఈ పేజీ శుభ్రం చేయి',
  confirm_clear_page: 'ఈ పేజీలో మీరు జోడించినవన్నీ తీసేయాలా?',
  items_on_page: 'ఈ పేజీలో {n} జోడించారు', page_canvas: 'PDF పేజీ', items_label: 'పేజీకి జోడించినవి',
  stage_hint: 'దేన్నైనా ఎంచుకోవడానికి తాకండి, కదపడానికి లాగండి, పరిమాణం మార్చడానికి నీలం మూలను లాగండి. బాణం కీలతోనూ కదపవచ్చు.',
  added: 'పేజీకి జోడించాం. లాగి సరైన చోట పెట్టండి.', added_all: 'మొత్తం {n} పేజీలకు జోడించాం.', removed: 'తీసేశాం.',
  item_sig: 'సంతకం', item_init: 'పొట్టి సంతకం', item_stamp: 'ముద్ర', item_text: 'అక్షరాలు', item_date: 'తేదీ', item_tick: 'టిక్', item_cross: 'అడ్డగీత', item_white: 'తెల్ల పెట్టె',
  tools_label: 'టూల్స్',
  tool_sign: 'సంతకం', tool_text: 'అక్షరాలు', tool_date: 'తేదీ', tool_mark: 'టిక్ / అడ్డగీత', tool_self: 'Self attested', tool_stamp: 'ముద్ర', tool_hide: 'తెల్ల కవర్', tool_form: 'ఫారం గడులు',
  sig_draw: 'గీయి', sig_type: 'టైప్', sig_photo: 'ఫోటో',
  sig_pad_hint: 'మీ వేలు, స్టైలస్ లేదా మౌస్‌తో ఇక్కడ సంతకం చేయండి.',
  sig_type_label: 'మీ పేరు', sig_type_ph: 'ఉదా. Priya Sharma', sig_type_prev_empty: 'మీ పేరు చేతిరాత శైలిలో ఇక్కడ కనిపిస్తుంది',
  sig_photo_pick: 'మీ సంతకం ఫోటోను ఎంచుకోండి',
  sig_photo_hint: 'తెల్ల కాగితంపై ముదురు పెన్నుతో సంతకం చేసి స్పష్టమైన ఫోటో తీయండి. కాగితం దానంతట అదే పారదర్శకంగా మారుతుంది.',
  ink: 'ఇంకు రంగు', col_blue: 'నీలం', col_black: 'నలుపు', col_red: 'ఎరుపు', col_green: 'ఆకుపచ్చ',
  sig_use: 'సంతకంగా జోడించు', sig_use_init: 'పొట్టి సంతకంగా జోడించు',
  sig_empty: 'ముందు గీయండి, టైప్ చేయండి లేదా ఫోటో ఎంచుకోండి.',
  sig_saved_title: 'ఈ పరికరంలో సేవ్ అయినవి', sig_saved_sig: 'సంతకం', sig_saved_init: 'పొట్టి సంతకం',
  sig_add: 'పేజీకి జోడించు', sig_add_all: 'ప్రతి పేజీకి', sig_forget: 'మర్చిపో',
  sig_saved_note: 'మళ్లీ వాడుకోవడానికి ఈ బ్రౌజర్‌లో మాత్రమే సేవ్ అయింది. అందరూ వాడే కంప్యూటర్‌లో పని అయ్యాక “మర్చిపో” నొక్కండి.',
  sig_too_big: 'తర్వాతిసారి కోసం గుర్తుంచుకోవడానికి ఈ చిత్రం చాలా పెద్దది, కానీ పేజీకి జోడించాం.',
  forgotten: 'మర్చిపోయాం.',
  text_label: 'అక్షరాలు', text_ph: 'ఉదా. Approved, Paid, Priya Sharma', text_size: 'పరిమాణం', text_style: 'శైలి', font_normal: 'మామూలు', font_hand: 'చేతిరాత',
  text_ink_note: 'సంతకంలో ఎంచుకున్న ఇంకు రంగే వాడబడుతుంది.', text_add: 'అక్షరాలు జోడించు',
  date_label: 'తేదీ', date_fmt: 'రూపం', date_add: 'తేదీ జోడించు',
  mark_help: 'ఒక గడిలో టిక్ పెట్టండి లేదా ఒక ఎంపికను కొట్టేయండి. పెద్దది చేయడానికి మూలను లాగండి.', mark_tick: 'టిక్', mark_cross: 'అడ్డగీత',
  self_help: 'ఆఫీసులు ఆధార్, PAN, మార్కుల మెమో, సర్టిఫికెట్ల “Self attested” కాపీలు అడుగుతాయి: ప్రతి కాపీపై అది రాసి, సంతకం చేసి, తేదీ వేయండి. ఇది మూడింటినీ కలిపి జోడిస్తుంది.',
  self_text_label: 'అక్షరాలు', self_default: 'Self attested',
  self_need_sig: 'ముందు ఒక సంతకం తయారు చేయండి (గీయి, టైప్ లేదా ఫోటో). అది అక్షరాలు, ఈరోజు తేదీతో కలిపి పెట్టబడుతుంది.',
  self_add: 'ఈ పేజీకి జోడించు', self_add_all: 'ప్రతి పేజీకి',
  stamp_help: 'కంపెనీ ముద్ర, “PAID”, “RECEIVED”, స్కూల్ ముద్ర. పారదర్శక నేపథ్యం ఉన్న PNG బాగా కనిపిస్తుంది.',
  stamp_pick: 'ముద్ర చిత్రం ఎంచుకో', stamp_last: 'ముద్ర',
  hide_help: 'పేజీలోని కొంత భాగాన్ని తెల్ల పెట్టెతో కప్పుతుంది, ఉదా. పాత తేదీ లేదా తప్పు రాత. దాని కింద ఉన్న అక్షరాలు ఫైల్‌లో ఇంకా ఉంటాయి, కాబట్టి రహస్యాలు దాచడానికి దీన్ని వాడకండి.',
  hide_add: 'తెల్ల పెట్టె జోడించు',
  form_none: 'ఈ PDF లో నింపగల ఫారం గడులు లేవు. దానిపై రాయడానికి “అక్షరాలు” టూల్ వాడండి.',
  form_xfa: 'ఇది XFA ఫారం; దీని గడులను ఇక్కడ నింపలేం.',
  form_help: '{n} గడులు దొరికాయి. ఇక్కడ నింపండి; సేవ్ చేసినప్పుడు అవి PDF లో రాయబడతాయి. అక్కడికి వెళ్లడానికి పేజీలో వెలిగే పెట్టెను తాకండి.',
  form_flatten: 'సేవ్ చేశాక గడులను లాక్ చేయి (flatten)',
  field_aria: 'ఫారం గడి {name}',
  out_name: 'ఫైల్ పేరు', save_btn: 'సంతకం చేసిన PDF సేవ్ చేయి', saving: 'PDF రాస్తోంది…',
  result_msg: '{name} ({size}) సేవ్ అయింది. పంపే ముందు ఒకసారి తెరిచి చూసుకోండి.', download_again: 'మళ్లీ డౌన్‌లోడ్ చేయి',
  nothing_added: 'ఇంకా ఏమీ జోడించలేదు. ముందు సంతకం, అక్షరాలు లేదా తేదీ జోడించండి.',
  legal_title: 'దయచేసి గమనించండి',
  legal_body: 'ఇది మీ సంతకం చిత్రాన్ని PDF పై పెడుతుంది. ఇది IT Act కింద Digital Signature Certificate (DSC) లేదా ఆధార్ eSign కాదు. రోజువారీ కాగితాలకు చాలా ఆఫీసులు దీన్ని ఒప్పుకుంటాయి, కానీ కొన్ని ఫైలింగ్‌లకు (GST, MCA, ఆదాయపు పన్ను, టెండర్లు) DSC లేదా eSign కావాలి. తీసుకునేవారికి ఏం కావాలో అడిగి తెలుసుకోండి.',
  help_title: 'ఎలా వాడాలి · పనికి ఆలోచనలు',
  tip1: 'PDF తెరిచి, ఒకసారి సంతకం గీసి “సంతకంగా జోడించు” నొక్కండి. అది ఈ పరికరంలో సేవ్ అవుతుంది, తర్వాతిసారి “పేజీకి జోడించు” నొక్కితే చాలు.',
  tip2: 'ఆఫర్ లెటర్ లేదా ఒప్పందం: సంతకం జోడించండి, తర్వాత “తేదీ”, తర్వాత “అక్షరాలు” టూల్‌తో మీ పేరు టైప్ చేయండి. సేవ్ చేసి కొత్త ఫైల్‌ను తిరిగి పంపండి.',
  tip3: 'బ్యాంక్, స్కూల్ లేదా ఉద్యోగం కోసం పత్రాల కాపీలు: ప్రతి పేజీపై “Self attested” వాడండి. బ్యాంక్ అడిగితే PDF Merge యాప్‌తో KYC వాటర్‌మార్క్ జోడించండి.',
  tip4: 'దుకాణం లేదా ఆఫీసు: మీ రబ్బరు ముద్ర PNG తయారు చేయండి (తెల్ల కాగితంపై ఫోటో, ఫోటో టూల్), బిల్లులు, రసీదులపై “ముద్ర” వాడండి.',
  tip5: 'గడులు ఉన్న ఫారాలు: “ఫారం గడులు” టూల్ వాటిని జాబితాగా చూపిస్తుంది; నేరుగా నింపి టిక్ చేయండి. స్కాన్ చేసిన ఫారాలకు అక్షరాలు, టిక్, అడ్డగీత వాడండి.',
  tip6: 'కాగితంపై తప్పు చేశారా? స్కాన్ చేసి, తప్పును తెల్ల పెట్టెతో కప్పి, సరిచేసినది “అక్షరాలు” తో రాయండి.',
  keys_title: 'కీబోర్డ్',
  key1: 'Tab తో ఒకదానికి వెళ్లి, బాణం కీలతో కదపండి; Shift + బాణం వేగంగా కదుపుతుంది.',
  key2: '+ మరియు − ఎంచుకున్నదాన్ని పెద్దది లేదా చిన్నది చేస్తాయి.',
  key3: 'Delete దాన్ని తీసేస్తుంది; Esc ఎంపిక తీసేస్తుంది.',
  key4: 'Ctrl+Z రద్దు, Ctrl+Y మళ్లీ చేయి.',
  reset_help: 'ఈ పరికరంలో సేవ్ అయిన సంతకం, సెట్టింగ్‌లను మర్చిపో.', reset_done: 'రీసెట్ అయింది.',
  sample_title: 'నమూనా ఆఫర్ లెటర్', sample_file: 'namuna-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'హింజేవాడి, పుణె 411057 · hr@example.com',
  sample_heading: 'ఆఫర్ లెటర్',
  sample_p1: 'ప్రియమైన ప్రియా శర్మ గారికి,',
  sample_p2: '1 నవంబర్ 2026 నుంచి నెలకు ₹ 25,000 జీతంతో జూనియర్ అకౌంటెంట్ ఉద్యోగాన్ని మీకు ఇవ్వడానికి సంతోషిస్తున్నాం. ఆఫీసు సమయం సోమవారం నుంచి శనివారం వరకు, ఉదయం 9:30 నుంచి సాయంత్రం 6:00 వరకు.',
  sample_p3: 'ఈ ఆఫర్‌ను ఒప్పుకోవడానికి కింద మీ పేరు నింపి, గడిలో టిక్ పెట్టి, సంతకం చేసి, తేదీ వేసి, ఈ లేఖను తిరిగి పంపండి.',
  sample_name_lbl: 'పూర్తి పేరు:', sample_agree: 'నేను ఈ ఆఫర్‌ను ఒప్పుకుంటున్నాను.', sample_sign_lbl: 'సంతకం:', sample_date_lbl: 'తేదీ:',
  sample_footer: 'సాధన కోసం AI Pathshala తయారు చేసిన నమూనా పత్రం. ఇది నిజమైన ఆఫర్ కాదు.'
},

kn: {
  app_title: 'PDF ಸಹಿ ಮಾಡಿ ಮತ್ತು ತುಂಬಿ',
  intro: 'PDF ಮೇಲೆ ಇಲ್ಲೇ ಸಹಿ ಮಾಡಿ, ತುಂಬಿ ಮತ್ತು ಮುದ್ರೆ ಹಾಕಿ: ನಿಮ್ಮ ಸಹಿಯನ್ನು ಬರೆಯಿರಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ, ಅಕ್ಷರ, ದಿನಾಂಕ, ಟಿಕ್, “Self attested” ಅಥವಾ ಮುದ್ರೆ ಸೇರಿಸಿ, ಫಾರ್ಮ್ ಖಾನೆಗಳನ್ನು ತುಂಬಿ. ಫೈಲ್ ನಿಮ್ಮ ಸಾಧನದಿಂದ ಹೊರಗೆ ಹೋಗುವುದಿಲ್ಲ.',
  privacy_title: 'ನಿಮ್ಮ PDF ಈ ಸಾಧನದಿಂದ ಎಂದಿಗೂ ಹೊರಗೆ ಹೋಗುವುದಿಲ್ಲ.',
  privacy_body: 'ಆಫರ್ ಲೆಟರ್, ಒಪ್ಪಂದ, KYC ಪ್ರತಿಗಳು ಮತ್ತು ಫಾರ್ಮ್‌ಗಳಿಗೆ ನಿಮ್ಮ ಬ್ರೌಸರ್ ಒಳಗೇ ಸಹಿ ಆಗುತ್ತದೆ. ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ, ಈ ಪುಟ ಮುಚ್ಚಿದಾಗ ಫೈಲ್ ಹೋಗುತ್ತದೆ.',
  eng_loading: 'PDF ಎಂಜಿನ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ… (ಮೊದಲ ಸಲ ಇಂಟರ್ನೆಟ್ ಬೇಕು)',
  eng_ready: 'PDF ಎಂಜಿನ್ ಸಿದ್ಧವಾಗಿದೆ',
  eng_failed: 'PDF ಎಂಜಿನ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ. ಇಂಟರ್ನೆಟ್‌ಗೆ ಸಂಪರ್ಕಿಸಿ “ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ” ಒತ್ತಿ. ಒಮ್ಮೆ ಲೋಡ್ ಆದ ನಂತರ ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
  retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ', waiting_engine: 'PDF ಎಂಜಿನ್‌ಗಾಗಿ ಕಾಯುತ್ತಿದೆ…', working: 'ಕೆಲಸ ನಡೆಯುತ್ತಿದೆ…',
  drop_title: 'PDF ಅನ್ನು ಇಲ್ಲಿ ಬಿಡಿ',
  drop_hint: 'ಅಥವಾ ಫೋನ್ / ಕಂಪ್ಯೂಟರ್‌ನಿಂದ ತೆರೆಯಿರಿ. ಆಫರ್ ಲೆಟರ್, ಒಪ್ಪಂದ, ಅರ್ಜಿ ಫಾರ್ಮ್, ಆಧಾರ್ ಅಥವಾ PAN ಪ್ರತಿ.',
  open_pdf: 'PDF ತೆರೆಯಿರಿ', try_sample: 'ಮಾದರಿ ಪತ್ರ ಪ್ರಯತ್ನಿಸಿ',
  opening: '{name} ತೆರೆಯುತ್ತಿದೆ…', opened: '{name} ತೆರೆಯಿತು, {n} ಪುಟಗಳು.',
  one_page: '1 ಪುಟ', n_pages: '{n} ಪುಟಗಳು',
  err_type: '{name} PDF ಅಲ್ಲ. ಮೊದಲು ಅದನ್ನು PDF ಆಗಿ ಉಳಿಸಿ.',
  err_corrupt: '{name} ತೆರೆಯಲಾಗಲಿಲ್ಲ. ಫೈಲ್ ಹಾಳಾಗಿರಬಹುದು.',
  err_locked: '{name} ಗೆ ಪಾಸ್‌ವರ್ಡ್ ಇದೆ. ಮೊದಲು PDF Compress & Convert ಆ್ಯಪ್‌ನಲ್ಲಿ ಪಾಸ್‌ವರ್ಡ್ ತೆಗೆದು, ನಂತರ ಇಲ್ಲಿಗೆ ಬನ್ನಿ.',
  unlock_btn: 'ಅನ್‌ಲಾಕ್ ಟೂಲ್ ತೆರೆಯಿರಿ',
  err_big: '{name} ದೊಡ್ಡದಾಗಿದೆ ({size}). ಫೋನ್‌ನಲ್ಲಿ ನಿಧಾನವಾಗಬಹುದು.',
  err_img: 'ಈ ಚಿತ್ರವನ್ನು ಓದಲಾಗಲಿಲ್ಲ. JPG ಅಥವಾ PNG ಬಳಸಿ.',
  err_blank: 'ಫೋಟೋದಲ್ಲಿ ಕಪ್ಪು ಸಹಿ ಸಿಗಲಿಲ್ಲ. ಬಿಳಿ ಕಾಗದದ ಮೇಲೆ ಕಪ್ಪು ಪೆನ್ನಿನಿಂದ ಸಹಿ ಮಾಡಿ.',
  err_save: 'PDF ಬರೆಯಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಬೇರೆ ಫೈಲ್ ಬಳಸಿ.',
  prev_page: 'ಹಿಂದಿನ ಪುಟ', next_page: 'ಮುಂದಿನ ಪುಟ', goto_page: 'ಪುಟಕ್ಕೆ ಹೋಗಿ',
  undo: 'ರದ್ದು ಮಾಡಿ', redo: 'ಮತ್ತೆ ಮಾಡಿ', it_delete: 'ತೆಗೆದುಹಾಕಿ', clear_page: 'ಈ ಪುಟ ಖಾಲಿ ಮಾಡಿ',
  confirm_clear_page: 'ಈ ಪುಟದಲ್ಲಿ ನೀವು ಸೇರಿಸಿದ ಎಲ್ಲವನ್ನೂ ತೆಗೆಯಬೇಕೇ?',
  items_on_page: 'ಈ ಪುಟದಲ್ಲಿ {n} ಸೇರಿಸಲಾಗಿದೆ', page_canvas: 'PDF ಪುಟ', items_label: 'ಪುಟಕ್ಕೆ ಸೇರಿಸಿದ ವಸ್ತುಗಳು',
  stage_hint: 'ಒಂದು ವಸ್ತುವನ್ನು ಆರಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ, ಸರಿಸಲು ಎಳೆಯಿರಿ, ಗಾತ್ರ ಬದಲಿಸಲು ನೀಲಿ ಮೂಲೆಯನ್ನು ಎಳೆಯಿರಿ. ಬಾಣದ ಕೀಲಿಗಳೂ ಸರಿಸುತ್ತವೆ.',
  added: 'ಪುಟಕ್ಕೆ ಸೇರಿಸಲಾಗಿದೆ. ಸರಿಯಾದ ಜಾಗಕ್ಕೆ ಎಳೆಯಿರಿ.', added_all: 'ಎಲ್ಲಾ {n} ಪುಟಗಳಿಗೆ ಸೇರಿಸಲಾಗಿದೆ.', removed: 'ತೆಗೆದುಹಾಕಲಾಗಿದೆ.',
  item_sig: 'ಸಹಿ', item_init: 'ಕಿರು ಸಹಿ', item_stamp: 'ಮುದ್ರೆ', item_text: 'ಅಕ್ಷರ', item_date: 'ದಿನಾಂಕ', item_tick: 'ಟಿಕ್', item_cross: 'ಕ್ರಾಸ್', item_white: 'ಬಿಳಿ ಡಬ್ಬಿ',
  tools_label: 'ಸಾಧನಗಳು',
  tool_sign: 'ಸಹಿ', tool_text: 'ಅಕ್ಷರ', tool_date: 'ದಿನಾಂಕ', tool_mark: 'ಟಿಕ್ / ಕ್ರಾಸ್', tool_self: 'Self attested', tool_stamp: 'ಮುದ್ರೆ', tool_hide: 'ಬಿಳಿ ಡಬ್ಬಿ', tool_form: 'ಫಾರ್ಮ್ ಖಾನೆಗಳು',
  sig_draw: 'ಬರೆಯಿರಿ', sig_type: 'ಟೈಪ್ ಮಾಡಿ', sig_photo: 'ಫೋಟೋ',
  sig_pad_hint: 'ಇಲ್ಲಿ ಬೆರಳು, ಸ್ಟೈಲಸ್ ಅಥವಾ ಮೌಸ್‌ನಿಂದ ಸಹಿ ಮಾಡಿ.',
  sig_type_label: 'ನಿಮ್ಮ ಹೆಸರು', sig_type_ph: 'ಉದಾ: Priya Sharma', sig_type_prev_empty: 'ನಿಮ್ಮ ಹೆಸರು ಇಲ್ಲಿ ಕೈಬರಹದ ಶೈಲಿಯಲ್ಲಿ ಕಾಣುತ್ತದೆ',
  sig_photo_pick: 'ನಿಮ್ಮ ಸಹಿಯ ಫೋಟೋ ಆರಿಸಿ',
  sig_photo_hint: 'ಬಿಳಿ ಕಾಗದದ ಮೇಲೆ ಕಪ್ಪು ಪೆನ್ನಿನಿಂದ ಸಹಿ ಮಾಡಿ ಸ್ಪಷ್ಟ ಫೋಟೋ ತೆಗೆಯಿರಿ. ಕಾಗದ ತಾನಾಗಿಯೇ ಪಾರದರ್ಶಕವಾಗುತ್ತದೆ.',
  ink: 'ಶಾಯಿಯ ಬಣ್ಣ', col_blue: 'ನೀಲಿ', col_black: 'ಕಪ್ಪು', col_red: 'ಕೆಂಪು', col_green: 'ಹಸಿರು',
  sig_use: 'ಸಹಿಯಾಗಿ ಸೇರಿಸಿ', sig_use_init: 'ಕಿರು ಸಹಿಯಾಗಿ ಸೇರಿಸಿ',
  sig_empty: 'ಮೊದಲು ಬರೆಯಿರಿ, ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಫೋಟೋ ಆರಿಸಿ.',
  sig_saved_title: 'ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ', sig_saved_sig: 'ಸಹಿ', sig_saved_init: 'ಕಿರು ಸಹಿ',
  sig_add: 'ಪುಟಕ್ಕೆ ಸೇರಿಸಿ', sig_add_all: 'ಪ್ರತಿ ಪುಟಕ್ಕೆ', sig_forget: 'ಮರೆತುಬಿಡಿ',
  sig_saved_note: 'ಮತ್ತೆ ಬಳಸಲು ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಮಾತ್ರ ಉಳಿಸಲಾಗಿದೆ. ಹಂಚಿಕೊಂಡ ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ ಕೆಲಸ ಮುಗಿದ ಮೇಲೆ “ಮರೆತುಬಿಡಿ” ಒತ್ತಿ.',
  sig_too_big: 'ಈ ಚಿತ್ರ ಮುಂದಿನ ಸಲಕ್ಕೆ ನೆನಪಿಡಲು ತುಂಬಾ ದೊಡ್ಡದು, ಆದರೆ ಪುಟಕ್ಕೆ ಸೇರಿಸಲಾಗಿದೆ.',
  forgotten: 'ಮರೆತುಬಿಡಲಾಗಿದೆ.',
  text_label: 'ಅಕ್ಷರ', text_ph: 'ಉದಾ: Approved, Paid, Priya Sharma', text_size: 'ಗಾತ್ರ', text_style: 'ಶೈಲಿ', font_normal: 'ಸಾಮಾನ್ಯ', font_hand: 'ಕೈಬರಹ',
  text_ink_note: 'ಸಹಿ ವಿಭಾಗದಲ್ಲಿ ಆರಿಸಿದ ಶಾಯಿಯ ಬಣ್ಣ ಬಳಸುತ್ತದೆ.', text_add: 'ಅಕ್ಷರ ಸೇರಿಸಿ',
  date_label: 'ದಿನಾಂಕ', date_fmt: 'ರೂಪ', date_add: 'ದಿನಾಂಕ ಸೇರಿಸಿ',
  mark_help: 'ಡಬ್ಬಿಗೆ ಟಿಕ್ ಹಾಕಿ ಅಥವಾ ಆಯ್ಕೆಯನ್ನು ಕ್ರಾಸ್ ಮಾಡಿ. ದೊಡ್ಡದು ಮಾಡಲು ಮೂಲೆಯನ್ನು ಎಳೆಯಿರಿ.', mark_tick: 'ಟಿಕ್', mark_cross: 'ಕ್ರಾಸ್',
  self_help: 'ಕಚೇರಿಗಳು ಆಧಾರ್, PAN, ಅಂಕಪಟ್ಟಿ ಮತ್ತು ಪ್ರಮಾಣಪತ್ರಗಳ “Self attested” ಪ್ರತಿ ಕೇಳುತ್ತವೆ: ಪ್ರತಿ ಪ್ರತಿಯ ಮೇಲೆ ಅದನ್ನು ಬರೆದು, ಸಹಿ ಮಾಡಿ, ದಿನಾಂಕ ಹಾಕಿ. ಇದು ಮೂರನ್ನೂ ಒಟ್ಟಿಗೆ ಸೇರಿಸುತ್ತದೆ.',
  self_text_label: 'ಅಕ್ಷರ', self_default: 'Self attested',
  self_need_sig: 'ಮೊದಲು ಸಹಿ ಮಾಡಿ (ಬರೆಯಿರಿ, ಟೈಪ್ ಅಥವಾ ಫೋಟೋ). ಅದನ್ನು ಅಕ್ಷರ ಮತ್ತು ಇಂದಿನ ದಿನಾಂಕದ ಜೊತೆ ಇಡಲಾಗುತ್ತದೆ.',
  self_add: 'ಈ ಪುಟಕ್ಕೆ ಸೇರಿಸಿ', self_add_all: 'ಪ್ರತಿ ಪುಟಕ್ಕೆ',
  stamp_help: 'ಕಂಪನಿ ಮುದ್ರೆ, “PAID”, “RECEIVED”, ಶಾಲೆಯ ಮುದ್ರೆ. ಪಾರದರ್ಶಕ ಹಿನ್ನೆಲೆಯ PNG ಅತ್ಯುತ್ತಮವಾಗಿ ಕಾಣುತ್ತದೆ.',
  stamp_pick: 'ಮುದ್ರೆಯ ಚಿತ್ರ ಆರಿಸಿ', stamp_last: 'ಮುದ್ರೆ',
  hide_help: 'ಪುಟದ ಒಂದು ಭಾಗವನ್ನು ಬಿಳಿ ಡಬ್ಬಿಯಿಂದ ಮುಚ್ಚುತ್ತದೆ, ಉದಾ: ಹಳೆಯ ದಿನಾಂಕ ಅಥವಾ ತಪ್ಪು ನಮೂದು. ಅದರ ಕೆಳಗಿನ ಅಕ್ಷರ ಫೈಲ್‌ನಲ್ಲಿ ಇನ್ನೂ ಇರುತ್ತದೆ, ಆದ್ದರಿಂದ ರಹಸ್ಯಗಳನ್ನು ಮುಚ್ಚಲು ಇದನ್ನು ಬಳಸಬೇಡಿ.',
  hide_add: 'ಬಿಳಿ ಡಬ್ಬಿ ಸೇರಿಸಿ',
  form_none: 'ಈ PDF ನಲ್ಲಿ ತುಂಬಬಹುದಾದ ಫಾರ್ಮ್ ಖಾನೆಗಳಿಲ್ಲ. ಅದರ ಮೇಲೆ ಬರೆಯಲು ಅಕ್ಷರ ಸಾಧನ ಬಳಸಿ.',
  form_xfa: 'ಇದು XFA ಫಾರ್ಮ್; ಇದರ ಖಾನೆಗಳನ್ನು ಇಲ್ಲಿ ತುಂಬಲಾಗುವುದಿಲ್ಲ.',
  form_help: '{n} ಖಾನೆಗಳು ಸಿಕ್ಕಿವೆ. ಇಲ್ಲಿ ತುಂಬಿ; ಉಳಿಸುವಾಗ ಅವು PDF ಗೆ ಬರೆಯಲ್ಪಡುತ್ತವೆ. ಪುಟದಲ್ಲಿ ಹೈಲೈಟ್ ಆದ ಡಬ್ಬಿ ಟ್ಯಾಪ್ ಮಾಡಿದರೆ ಅಲ್ಲಿಗೆ ಹೋಗುತ್ತದೆ.',
  form_flatten: 'ಉಳಿಸಿದ ನಂತರ ಖಾನೆಗಳನ್ನು ಲಾಕ್ ಮಾಡಿ (flatten)',
  field_aria: 'ಫಾರ್ಮ್ ಖಾನೆ {name}',
  out_name: 'ಫೈಲ್ ಹೆಸರು', save_btn: 'ಸಹಿ ಮಾಡಿದ PDF ಉಳಿಸಿ', saving: 'PDF ಬರೆಯುತ್ತಿದೆ…',
  result_msg: '{name} ({size}) ಉಳಿಸಲಾಗಿದೆ. ಕಳುಹಿಸುವ ಮೊದಲು ಒಮ್ಮೆ ತೆರೆದು ನೋಡಿ.', download_again: 'ಮತ್ತೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
  nothing_added: 'ಇನ್ನೂ ಏನೂ ಸೇರಿಸಿಲ್ಲ. ಮೊದಲು ಸಹಿ, ಅಕ್ಷರ ಅಥವಾ ದಿನಾಂಕ ಸೇರಿಸಿ.',
  legal_title: 'ದಯವಿಟ್ಟು ಗಮನಿಸಿ',
  legal_body: 'ಇದು PDF ಮೇಲೆ ನಿಮ್ಮ ಸಹಿಯ ಚಿತ್ರವನ್ನು ಹಾಕುತ್ತದೆ. ಇದು IT Act ಅಡಿಯಲ್ಲಿ Digital Signature Certificate (DSC) ಅಥವಾ ಆಧಾರ್ eSign ಅಲ್ಲ. ದಿನನಿತ್ಯದ ಕಾಗದಗಳಿಗೆ ಅನೇಕ ಕಚೇರಿಗಳು ಇದನ್ನು ಒಪ್ಪುತ್ತವೆ, ಆದರೆ ಕೆಲವು ಸಲ್ಲಿಕೆಗಳಿಗೆ (GST, MCA, ಆದಾಯ ತೆರಿಗೆ, ಟೆಂಡರ್) DSC ಅಥವಾ eSign ಬೇಕು. ಪಡೆಯುವವರಿಗೆ ಏನು ಬೇಕು ಎಂದು ಕೇಳಿ.',
  help_title: 'ಬಳಸುವುದು ಹೇಗೆ · ಕೆಲಸಕ್ಕೆ ಐಡಿಯಾಗಳು',
  tip1: 'PDF ತೆರೆಯಿರಿ, ಒಮ್ಮೆ ಸಹಿ ಬರೆದು “ಸಹಿಯಾಗಿ ಸೇರಿಸಿ” ಒತ್ತಿ. ಅದು ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಯುತ್ತದೆ, ಮುಂದಿನ ಸಲ “ಪುಟಕ್ಕೆ ಸೇರಿಸಿ” ಒತ್ತಿದರೆ ಸಾಕು.',
  tip2: 'ಆಫರ್ ಲೆಟರ್ ಅಥವಾ ಒಪ್ಪಂದ: ಸಹಿ ಸೇರಿಸಿ, ನಂತರ “ದಿನಾಂಕ”, ನಂತರ ಅಕ್ಷರ ಸಾಧನದಿಂದ ನಿಮ್ಮ ಹೆಸರು ಟೈಪ್ ಮಾಡಿ. ಉಳಿಸಿ ಹೊಸ ಫೈಲ್ ಅನ್ನು ವಾಪಸ್ ಕಳುಹಿಸಿ.',
  tip3: 'ಬ್ಯಾಂಕ್, ಶಾಲೆ ಅಥವಾ ಉದ್ಯೋಗಕ್ಕೆ ದಾಖಲೆ ಪ್ರತಿಗಳು: ಪ್ರತಿ ಪುಟದಲ್ಲಿ “Self attested” ಬಳಸಿ. ಬ್ಯಾಂಕ್ ಕೇಳಿದರೆ PDF Merge ಆ್ಯಪ್‌ನಿಂದ KYC ವಾಟರ್‌ಮಾರ್ಕ್ ಸೇರಿಸಿ.',
  tip4: 'ಅಂಗಡಿ ಅಥವಾ ಕಚೇರಿ: ನಿಮ್ಮ ರಬ್ಬರ್ ಮುದ್ರೆಯ PNG ಮಾಡಿ (ಬಿಳಿ ಕಾಗದದ ಮೇಲೆ ಫೋಟೋ, ಫೋಟೋ ಸಾಧನ) ಮತ್ತು ಬಿಲ್, ರಸೀದಿಗಳ ಮೇಲೆ “ಮುದ್ರೆ” ಬಳಸಿ.',
  tip5: 'ಡಬ್ಬಿಗಳಿರುವ ಫಾರ್ಮ್‌ಗಳು: ಫಾರ್ಮ್ ಖಾನೆಗಳ ಸಾಧನ ಅವುಗಳ ಪಟ್ಟಿ ತೋರಿಸುತ್ತದೆ; ನೇರವಾಗಿ ತುಂಬಿ ಟಿಕ್ ಮಾಡಿ. ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ಫಾರ್ಮ್‌ಗಳಿಗೆ ಅಕ್ಷರ, ಟಿಕ್ ಮತ್ತು ಕ್ರಾಸ್ ಬಳಸಿ.',
  tip6: 'ಕಾಗದದಲ್ಲಿ ತಪ್ಪಾಯಿತೇ? ಸ್ಕ್ಯಾನ್ ಮಾಡಿ, ತಪ್ಪನ್ನು ಬಿಳಿ ಡಬ್ಬಿಯಿಂದ ಮುಚ್ಚಿ, ಅಕ್ಷರ ಸಾಧನದಿಂದ ಸರಿಯಾದುದನ್ನು ಬರೆಯಿರಿ.',
  keys_title: 'ಕೀಬೋರ್ಡ್',
  key1: 'Tab ನಿಂದ ಒಂದು ವಸ್ತುವಿಗೆ ಹೋಗಿ, ನಂತರ ಬಾಣದ ಕೀಲಿಗಳು ಅದನ್ನು ಸರಿಸುತ್ತವೆ; Shift + ಬಾಣ ವೇಗವಾಗಿ ಸರಿಸುತ್ತದೆ.',
  key2: '+ ಮತ್ತು − ಆರಿಸಿದ ವಸ್ತುವನ್ನು ದೊಡ್ಡದು ಅಥವಾ ಚಿಕ್ಕದು ಮಾಡುತ್ತವೆ.',
  key3: 'Delete ಅದನ್ನು ತೆಗೆಯುತ್ತದೆ; Esc ಆಯ್ಕೆ ಬಿಡುತ್ತದೆ.',
  key4: 'Ctrl+Z ರದ್ದು, Ctrl+Y ಮತ್ತೆ ಮಾಡಿ.',
  reset_help: 'ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಿದ ಸಹಿ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಮರೆತುಬಿಡಿ.', reset_done: 'ರೀಸೆಟ್ ಆಯಿತು.',
  sample_title: 'ಮಾದರಿ ಆಫರ್ ಲೆಟರ್', sample_file: 'madari-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'ಹಿಂಜೆವಾಡಿ, ಪುಣೆ 411057 · hr@example.com',
  sample_heading: 'ಆಫರ್ ಲೆಟರ್',
  sample_p1: 'ಪ್ರಿಯ ಪ್ರಿಯಾ ಶರ್ಮಾ,',
  sample_p2: '1 ನವೆಂಬರ್ 2026 ರಿಂದ ತಿಂಗಳಿಗೆ ₹ 25,000 ಸಂಬಳದಲ್ಲಿ ಜೂನಿಯರ್ ಅಕೌಂಟೆಂಟ್ ಹುದ್ದೆಯನ್ನು ನಿಮಗೆ ನೀಡಲು ನಮಗೆ ಸಂತೋಷವಾಗಿದೆ. ಕಚೇರಿ ಸಮಯ ಸೋಮವಾರದಿಂದ ಶನಿವಾರ, ಬೆಳಿಗ್ಗೆ 9:30 ರಿಂದ ಸಂಜೆ 6:00 ರವರೆಗೆ.',
  sample_p3: 'ಆಫರ್ ಒಪ್ಪಿಕೊಳ್ಳಲು ಕೆಳಗೆ ನಿಮ್ಮ ಹೆಸರು ತುಂಬಿ, ಡಬ್ಬಿಗೆ ಟಿಕ್ ಹಾಕಿ, ಸಹಿ ಮಾಡಿ, ದಿನಾಂಕ ಹಾಕಿ ಮತ್ತು ಈ ಪತ್ರವನ್ನು ವಾಪಸ್ ಕಳುಹಿಸಿ.',
  sample_name_lbl: 'ಪೂರ್ಣ ಹೆಸರು:', sample_agree: 'ನಾನು ಈ ಆಫರ್ ಒಪ್ಪಿಕೊಳ್ಳುತ್ತೇನೆ.', sample_sign_lbl: 'ಸಹಿ:', sample_date_lbl: 'ದಿನಾಂಕ:',
  sample_footer: 'ಅಭ್ಯಾಸಕ್ಕಾಗಿ AI Pathshala ಮಾಡಿದ ಮಾದರಿ ದಾಖಲೆ. ಇದು ನಿಜವಾದ ಆಫರ್ ಅಲ್ಲ.'
},

ml: {
  app_title: 'PDF-ൽ ഒപ്പിടുക, പൂരിപ്പിക്കുക',
  intro: 'PDF-ൽ ഇവിടെത്തന്നെ ഒപ്പിടുക, പൂരിപ്പിക്കുക, സീൽ വയ്ക്കുക: ഒപ്പ് വരയ്ക്കുകയോ ടൈപ്പ് ചെയ്യുകയോ ചെയ്യുക, ടെക്സ്റ്റ്, തീയതി, ടിക്ക്, “Self attested” കുറിപ്പ്, സ്റ്റാമ്പ് എന്നിവ ചേർക്കുക, ഫോമിലെ കള്ളികൾ പൂരിപ്പിക്കുക. ഫയൽ നിങ്ങളുടെ ഉപകരണത്തിൽ നിന്ന് പുറത്തുപോകില്ല.',
  privacy_title: 'നിങ്ങളുടെ PDF ഈ ഉപകരണത്തിൽ നിന്ന് ഒരിക്കലും പുറത്തുപോകില്ല.',
  privacy_body: 'ഓഫർ ലെറ്റർ, കരാറുകൾ, KYC പകർപ്പുകൾ, ഫോമുകൾ എന്നിവ നിങ്ങളുടെ ബ്രൗസറിനുള്ളിൽത്തന്നെ ഒപ്പിടുന്നു. ഒന്നും അപ്‌ലോഡ് ചെയ്യുന്നില്ല; ഈ പേജ് അടച്ചാൽ ഫയൽ പോകും.',
  eng_loading: 'PDF എഞ്ചിൻ ലോഡ് ചെയ്യുന്നു… (ആദ്യത്തെ തവണ ഇന്റർനെറ്റ് വേണം)',
  eng_ready: 'PDF എഞ്ചിൻ തയ്യാർ',
  eng_failed: 'PDF എഞ്ചിൻ ലോഡ് ചെയ്യാനായില്ല. ഇന്റർനെറ്റുമായി ബന്ധിപ്പിച്ച് വീണ്ടും ശ്രമിക്കുക അമർത്തുക. ഒരിക്കൽ ലോഡ് ആയാൽ ഇന്റർനെറ്റില്ലാതെയും പ്രവർത്തിക്കും.',
  retry: 'വീണ്ടും ശ്രമിക്കുക', waiting_engine: 'PDF എഞ്ചിനായി കാത്തിരിക്കുന്നു…', working: 'ചെയ്യുന്നു…',
  drop_title: 'PDF ഇവിടെ ഇടുക',
  drop_hint: 'അല്ലെങ്കിൽ ഫോണിൽ നിന്നോ കമ്പ്യൂട്ടറിൽ നിന്നോ തുറക്കുക. ഓഫർ ലെറ്റർ, കരാർ, അപേക്ഷാ ഫോം, ആധാർ അല്ലെങ്കിൽ PAN പകർപ്പ്.',
  open_pdf: 'PDF തുറക്കുക', try_sample: 'മാതൃകാ കത്ത് പരീക്ഷിക്കുക',
  opening: '{name} തുറക്കുന്നു…', opened: '{name} തുറന്നു, {n} പേജുകൾ.',
  one_page: '1 പേജ്', n_pages: '{n} പേജുകൾ',
  err_type: '{name} ഒരു PDF അല്ല. ആദ്യം PDF ആയി സേവ് ചെയ്യുക.',
  err_corrupt: '{name} തുറക്കാനായില്ല. ഫയൽ കേടായിരിക്കാം.',
  err_locked: '{name}-ന് പാസ്‌വേഡ് ഉണ്ട്. ആദ്യം PDF Compress & Convert ആപ്പിൽ പാസ്‌വേഡ് മാറ്റി തിരികെ വരിക.',
  unlock_btn: 'അൺലോക്ക് ടൂൾ തുറക്കുക',
  err_big: '{name} വലുതാണ് ({size}). ഫോണിൽ പതുക്കെയാകാം.',
  err_img: 'ഈ ചിത്രം വായിക്കാനായില്ല. JPG അല്ലെങ്കിൽ PNG ഉപയോഗിക്കുക.',
  err_blank: 'ഫോട്ടോയിൽ കടും നിറത്തിലുള്ള ഒപ്പ് കണ്ടില്ല. വെള്ളക്കടലാസിൽ കടും നിറ പേന കൊണ്ട് ഒപ്പിടുക.',
  err_save: 'PDF ഉണ്ടാക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ മറ്റൊരു ഫയൽ എടുക്കുക.',
  prev_page: 'മുൻ പേജ്', next_page: 'അടുത്ത പേജ്', goto_page: 'പേജിലേക്ക് പോകുക',
  undo: 'പഴയപടി', redo: 'വീണ്ടും ചെയ്യുക', it_delete: 'നീക്കുക', clear_page: 'ഈ പേജ് മായ്ക്കുക',
  confirm_clear_page: 'ഈ പേജിൽ നിങ്ങൾ ചേർത്തതെല്ലാം നീക്കണോ?',
  items_on_page: 'ഈ പേജിൽ {n} എണ്ണം ചേർത്തു', page_canvas: 'PDF പേജ്', items_label: 'പേജിൽ ചേർത്തവ',
  stage_hint: 'തിരഞ്ഞെടുക്കാൻ ടാപ്പ് ചെയ്യുക, നീക്കാൻ വലിക്കുക, വലുപ്പം മാറ്റാൻ നീല മൂല വലിക്കുക. ആരോ കീകളും നീക്കും.',
  added: 'പേജിൽ ചേർത്തു. ശരിയായ സ്ഥലത്തേക്ക് വലിച്ചിടുക.', added_all: 'എല്ലാ {n} പേജുകളിലും ചേർത്തു.', removed: 'നീക്കി.',
  item_sig: 'ഒപ്പ്', item_init: 'ചുരുക്കൊപ്പ്', item_stamp: 'സ്റ്റാമ്പ്', item_text: 'ടെക്സ്റ്റ്', item_date: 'തീയതി', item_tick: 'ടിക്ക്', item_cross: 'ക്രോസ്', item_white: 'വെള്ളപ്പെട്ടി',
  tools_label: 'ടൂളുകൾ',
  tool_sign: 'ഒപ്പ്', tool_text: 'ടെക്സ്റ്റ്', tool_date: 'തീയതി', tool_mark: 'ടിക്ക് / ക്രോസ്', tool_self: 'സ്വയം സാക്ഷ്യം', tool_stamp: 'സ്റ്റാമ്പ്', tool_hide: 'മായ്ക്കൽ', tool_form: 'ഫോം കള്ളികൾ',
  sig_draw: 'വരയ്ക്കുക', sig_type: 'ടൈപ്പ്', sig_photo: 'ഫോട്ടോ',
  sig_pad_hint: 'വിരൽ, സ്റ്റൈലസ് അല്ലെങ്കിൽ മൗസ് കൊണ്ട് ഇവിടെ ഒപ്പിടുക.',
  sig_type_label: 'നിങ്ങളുടെ പേര്', sig_type_ph: 'ഉദാ. പ്രിയ ശർമ്മ', sig_type_prev_empty: 'നിങ്ങളുടെ പേര് കൈയക്ഷര ശൈലിയിൽ ഇവിടെ കാണാം',
  sig_photo_pick: 'ഒപ്പിന്റെ ഫോട്ടോ തിരഞ്ഞെടുക്കുക',
  sig_photo_hint: 'വെള്ളക്കടലാസിൽ കടും നിറ പേന കൊണ്ട് ഒപ്പിട്ട് വ്യക്തമായ ഫോട്ടോ എടുക്കുക. കടലാസ് തനിയെ സുതാര്യമാകും.',
  ink: 'മഷിയുടെ നിറം', col_blue: 'നീല', col_black: 'കറുപ്പ്', col_red: 'ചുവപ്പ്', col_green: 'പച്ച',
  sig_use: 'ഒപ്പായി ചേർക്കുക', sig_use_init: 'ചുരുക്കൊപ്പായി ചേർക്കുക',
  sig_empty: 'ആദ്യം ഒപ്പ് വരയ്ക്കുക, ടൈപ്പ് ചെയ്യുക അല്ലെങ്കിൽ ഫോട്ടോ തിരഞ്ഞെടുക്കുക.',
  sig_saved_title: 'ഈ ഉപകരണത്തിൽ സൂക്ഷിച്ചത്', sig_saved_sig: 'ഒപ്പ്', sig_saved_init: 'ചുരുക്കൊപ്പ്',
  sig_add: 'പേജിൽ ചേർക്കുക', sig_add_all: 'എല്ലാ പേജിലും', sig_forget: 'മറക്കുക',
  sig_saved_note: 'വീണ്ടും ഉപയോഗിക്കാൻ ഈ ബ്രൗസറിൽ മാത്രം സൂക്ഷിക്കുന്നു. പൊതു കമ്പ്യൂട്ടറിൽ ജോലി കഴിഞ്ഞാൽ “മറക്കുക” അമർത്തുക.',
  sig_too_big: 'അടുത്ത തവണത്തേക്ക് ഓർക്കാൻ ഈ ചിത്രം വളരെ വലുതാണ്, എങ്കിലും പേജിൽ ചേർത്തു.',
  forgotten: 'മറന്നു.',
  text_label: 'ടെക്സ്റ്റ്', text_ph: 'ഉദാ. Approved, Paid, പ്രിയ ശർമ്മ', text_size: 'വലുപ്പം', text_style: 'ശൈലി', font_normal: 'സാധാരണ', font_hand: 'കൈയക്ഷരം',
  text_ink_note: 'ഒപ്പ് ഭാഗത്ത് തിരഞ്ഞെടുത്ത മഷിനിറം ഉപയോഗിക്കും.', text_add: 'ടെക്സ്റ്റ് ചേർക്കുക',
  date_label: 'തീയതി', date_fmt: 'രീതി', date_add: 'തീയതി ചേർക്കുക',
  mark_help: 'കള്ളിയിൽ ടിക്ക് ചെയ്യുക അല്ലെങ്കിൽ ഒരു ഓപ്ഷൻ വെട്ടുക. വലുതാക്കാൻ മൂല വലിക്കുക.', mark_tick: 'ടിക്ക്', mark_cross: 'ക്രോസ്',
  self_help: 'ആധാർ, PAN, മാർക്ക് ഷീറ്റ്, സർട്ടിഫിക്കറ്റ് എന്നിവയുടെ “Self attested” പകർപ്പുകൾ ഓഫീസുകൾ ചോദിക്കും: ഓരോ പകർപ്പിലും അത് എഴുതി, ഒപ്പിട്ട്, തീയതി ഇടുക. ഇത് മൂന്നും ഒരുമിച്ച് ചേർക്കുന്നു.',
  self_text_label: 'ടെക്സ്റ്റ്', self_default: 'Self attested',
  self_need_sig: 'ആദ്യം ഒരു ഒപ്പ് ഉണ്ടാക്കുക (വരച്ചോ ടൈപ്പ് ചെയ്തോ ഫോട്ടോയിൽ നിന്നോ). അത് ടെക്സ്റ്റിനും ഇന്നത്തെ തീയതിക്കും ഒപ്പം വയ്ക്കും.',
  self_add: 'ഈ പേജിൽ ചേർക്കുക', self_add_all: 'എല്ലാ പേജിലും',
  stamp_help: 'കമ്പനി സീൽ, “PAID”, “RECEIVED”, സ്കൂൾ സ്റ്റാമ്പ്. സുതാര്യ പശ്ചാത്തലമുള്ള PNG ആണ് നല്ലത്.',
  stamp_pick: 'സ്റ്റാമ്പ് ചിത്രം തിരഞ്ഞെടുക്കുക', stamp_last: 'സ്റ്റാമ്പ്',
  hide_help: 'പേജിന്റെ ഒരു ഭാഗം വെള്ളപ്പെട്ടി കൊണ്ട് മൂടുന്നു, ഉദാ. പഴയ തീയതി അല്ലെങ്കിൽ തെറ്റായ എഴുത്ത്. അടിയിലെ എഴുത്ത് ഫയലിൽ അപ്പോഴും ഉണ്ടാകും, അതിനാൽ രഹസ്യം മറയ്ക്കാൻ ഉപയോഗിക്കരുത്.',
  hide_add: 'വെള്ളപ്പെട്ടി ചേർക്കുക',
  form_none: 'ഈ PDF-ൽ പൂരിപ്പിക്കാവുന്ന കള്ളികളില്ല. എഴുതാൻ ടെക്സ്റ്റ് ടൂൾ ഉപയോഗിക്കുക.',
  form_xfa: 'ഇതൊരു XFA ഫോം ആണ്; ഇതിന്റെ കള്ളികൾ ഇവിടെ പൂരിപ്പിക്കാനാവില്ല.',
  form_help: '{n} കള്ളികൾ കണ്ടു. ഇവിടെ പൂരിപ്പിക്കുക; സേവ് ചെയ്യുമ്പോൾ PDF-ൽ എഴുതും. പേജിലെ അടയാളപ്പെടുത്തിയ കള്ളിയിൽ ടാപ്പ് ചെയ്താൽ അതിലേക്ക് പോകാം.',
  form_flatten: 'സേവ് ചെയ്ത ശേഷം കള്ളികൾ ലോക്ക് ചെയ്യുക (flatten)',
  field_aria: 'ഫോം കള്ളി {name}',
  out_name: 'ഫയലിന്റെ പേര്', save_btn: 'ഒപ്പിട്ട PDF സേവ് ചെയ്യുക', saving: 'PDF ഉണ്ടാക്കുന്നു…',
  result_msg: '{name} സേവ് ചെയ്തു ({size}). അയയ്ക്കുന്നതിന് മുമ്പ് ഒരിക്കൽ തുറന്ന് പരിശോധിക്കുക.', download_again: 'വീണ്ടും ഡൗൺലോഡ്',
  nothing_added: 'ഇതുവരെ ഒന്നും ചേർത്തില്ല. ആദ്യം ഒപ്പ്, ടെക്സ്റ്റ് അല്ലെങ്കിൽ തീയതി ചേർക്കുക.',
  legal_title: 'ശ്രദ്ധിക്കുക',
  legal_body: 'ഇത് PDF-ൽ നിങ്ങളുടെ ഒപ്പിന്റെ ചിത്രം ചേർക്കുന്നു. ഇത് IT Act പ്രകാരമുള്ള ഡിജിറ്റൽ സിഗ്നേച്ചർ സർട്ടിഫിക്കറ്റ് (DSC) അല്ലെങ്കിൽ ആധാർ eSign അല്ല. സാധാരണ രേഖകൾക്ക് പല ഓഫീസുകളും ഇത് സ്വീകരിക്കും, പക്ഷേ ചില ഫയലിംഗുകൾക്ക് (GST, MCA, ആദായനികുതി, ടെൻഡർ) DSC അല്ലെങ്കിൽ eSign വേണം. സ്വീകരിക്കുന്നവർക്ക് എന്താണ് വേണ്ടതെന്ന് ചോദിക്കുക.',
  help_title: 'ഉപയോഗിക്കേണ്ട വിധം · ജോലിക്കുള്ള ആശയങ്ങൾ',
  tip1: 'PDF തുറന്ന് ഒരിക്കൽ ഒപ്പ് വരച്ച് “ഒപ്പായി ചേർക്കുക” അമർത്തുക. ഇത് ഈ ഉപകരണത്തിൽ സൂക്ഷിക്കും, അടുത്ത തവണ “പേജിൽ ചേർക്കുക” മാത്രം അമർത്തിയാൽ മതി.',
  tip2: 'ഓഫർ ലെറ്റർ അല്ലെങ്കിൽ കരാർ: ഒപ്പ് ചേർക്കുക, പിന്നെ “തീയതി”, പിന്നെ ടെക്സ്റ്റ് ടൂളിൽ പേര് എഴുതുക. സേവ് ചെയ്ത് പുതിയ ഫയൽ തിരികെ അയയ്ക്കുക.',
  tip3: 'ബാങ്ക്, സ്കൂൾ, ജോലി എന്നിവയ്ക്കുള്ള രേഖാപകർപ്പുകൾ: എല്ലാ പേജിലും “സ്വയം സാക്ഷ്യം” ഉപയോഗിക്കുക. ബാങ്ക് ചോദിച്ചാൽ PDF Merge ആപ്പിൽ KYC വാട്ടർമാർക്ക് ചേർക്കുക.',
  tip4: 'കട അല്ലെങ്കിൽ ഓഫീസ്: റബ്ബർ സ്റ്റാമ്പിന്റെ PNG ഉണ്ടാക്കുക (വെള്ളക്കടലാസിൽ ഫോട്ടോ, ഫോട്ടോ ടൂൾ), ബില്ലുകളിലും രസീതുകളിലും “സ്റ്റാമ്പ്” ഉപയോഗിക്കുക.',
  tip5: 'കള്ളികളുള്ള ഫോമുകൾ: “ഫോം കള്ളികൾ” ടൂൾ അവ കാണിക്കും; നേരിട്ട് പൂരിപ്പിച്ച് ടിക്ക് ചെയ്യുക. സ്കാൻ ചെയ്ത ഫോമുകൾക്ക് ടെക്സ്റ്റ്, ടിക്ക്, ക്രോസ് ഉപയോഗിക്കുക.',
  tip6: 'കടലാസിൽ തെറ്റ് പറ്റിയോ? സ്കാൻ ചെയ്ത്, തെറ്റ് വെള്ളപ്പെട്ടി കൊണ്ട് മൂടി, ടെക്സ്റ്റ് കൊണ്ട് തിരുത്ത് എഴുതുക.',
  keys_title: 'കീബോർഡ്',
  key1: 'Tab കൊണ്ട് ഒരു ഇനത്തിലെത്തുക, പിന്നെ ആരോ കീകൾ അത് നീക്കും; Shift + ആരോ വേഗത്തിൽ നീക്കും.',
  key2: '+, − എന്നിവ തിരഞ്ഞെടുത്തത് വലുതാക്കുകയോ ചെറുതാക്കുകയോ ചെയ്യും.',
  key3: 'Delete അത് നീക്കും; Esc തിരഞ്ഞെടുപ്പ് മാറ്റും.',
  key4: 'Ctrl+Z പഴയപടി, Ctrl+Y വീണ്ടും.',
  reset_help: 'ഈ ഉപകരണത്തിൽ സൂക്ഷിച്ച ഒപ്പും ക്രമീകരണങ്ങളും മറക്കുക.', reset_done: 'റീസെറ്റ് ചെയ്തു.',
  sample_title: 'മാതൃകാ ഓഫർ ലെറ്റർ', sample_file: 'mathruka-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'ഹിൻജെവാഡി, പൂനെ 411057 · hr@example.com',
  sample_heading: 'ഓഫർ ലെറ്റർ',
  sample_p1: 'പ്രിയ പ്രിയ ശർമ്മ,',
  sample_p2: '2026 നവംബർ 1 മുതൽ പ്രതിമാസം ₹ 25,000 ശമ്പളത്തിൽ ജൂനിയർ അക്കൗണ്ടന്റ് തസ്തികയിലേക്ക് നിങ്ങളെ നിയമിക്കുന്നതിൽ ഞങ്ങൾക്ക് സന്തോഷമുണ്ട്. ഓഫീസ് സമയം തിങ്കൾ മുതൽ ശനി വരെ, രാവിലെ 9:30 മുതൽ വൈകിട്ട് 6:00 വരെ.',
  sample_p3: 'ഓഫർ സ്വീകരിക്കാൻ താഴെ നിങ്ങളുടെ പേര് എഴുതി, കള്ളിയിൽ ടിക്ക് ചെയ്ത്, ഒപ്പിട്ട്, തീയതി ഇട്ട് ഈ കത്ത് തിരികെ അയയ്ക്കുക.',
  sample_name_lbl: 'മുഴുവൻ പേര്:', sample_agree: 'ഞാൻ ഈ ഓഫർ സ്വീകരിക്കുന്നു.', sample_sign_lbl: 'ഒപ്പ്:', sample_date_lbl: 'തീയതി:',
  sample_footer: 'പരിശീലനത്തിനായി AI Pathshala ഉണ്ടാക്കിയ മാതൃകാ രേഖ. യഥാർത്ഥ ഓഫർ അല്ല.'
},

ur: {
  app_title: 'PDF پر دستخط کریں اور بھریں',
  intro: 'PDF پر یہیں دستخط کریں، بھریں اور مہر لگائیں: دستخط بنائیں یا ٹائپ کریں، متن، تاریخ، ٹِک، “خود تصدیق شدہ” نوٹ یا مہر لگائیں اور فارم کے خانے بھریں۔ فائل آپ کے ڈیوائس سے باہر نہیں جاتی۔',
  privacy_title: 'آپ کی PDF اس ڈیوائس سے کبھی باہر نہیں جاتی۔',
  privacy_body: 'آفر لیٹر، معاہدے، KYC کاپیاں اور فارم آپ کے براؤزر کے اندر ہی سائن ہوتے ہیں۔ کچھ بھی اپ لوڈ نہیں ہوتا، اور یہ صفحہ بند کرتے ہی فائل ہٹ جاتی ہے۔',
  eng_loading: 'PDF انجن لوڈ ہو رہا ہے… (پہلی بار انٹرنیٹ چاہیے)',
  eng_ready: 'PDF انجن تیار ہے',
  eng_failed: 'PDF انجن لوڈ نہیں ہو سکا۔ انٹرنیٹ سے جڑیں اور دوبارہ کوشش دبائیں۔ ایک بار لوڈ ہونے کے بعد یہ بغیر انٹرنیٹ بھی چلتا ہے۔',
  retry: 'دوبارہ کوشش', waiting_engine: 'PDF انجن کا انتظار ہے…', working: 'کام ہو رہا ہے…',
  drop_title: 'PDF یہاں چھوڑیں',
  drop_hint: 'یا اپنے فون یا کمپیوٹر سے کھولیں۔ آفر لیٹر، معاہدہ، درخواست فارم، آدھار یا PAN کی کاپی۔',
  open_pdf: 'PDF کھولیں', try_sample: 'نمونہ خط آزمائیں',
  opening: '{name} کھل رہی ہے…', opened: '{name} کھل گئی، {n} صفحے۔',
  one_page: '1 صفحہ', n_pages: '{n} صفحے',
  err_type: '{name} PDF نہیں ہے۔ پہلے اسے PDF کے طور پر محفوظ کریں۔',
  err_corrupt: '{name} کھل نہیں سکی۔ فائل خراب ہو سکتی ہے۔',
  err_locked: '{name} پر پاس ورڈ لگا ہے۔ پہلے PDF Compress & Convert ایپ سے پاس ورڈ ہٹائیں، پھر واپس آئیں۔',
  unlock_btn: 'ان لاک ٹول کھولیں',
  err_big: '{name} بڑی ہے ({size})۔ فون پر دھیمی چل سکتی ہے۔',
  err_img: 'یہ تصویر پڑھی نہیں جا سکی۔ JPG یا PNG استعمال کریں۔',
  err_blank: 'تصویر میں گہرے رنگ کے دستخط نہیں ملے۔ سفید کاغذ پر گہرے قلم سے سائن کریں۔',
  err_save: 'PDF نہیں بن سکی۔ دوبارہ کوشش کریں یا دوسری فائل لیں۔',
  prev_page: 'پچھلا صفحہ', next_page: 'اگلا صفحہ', goto_page: 'صفحے پر جائیں',
  undo: 'واپس', redo: 'دوبارہ', it_delete: 'ہٹائیں', clear_page: 'یہ صفحہ صاف کریں',
  confirm_clear_page: 'اس صفحے پر آپ نے جو کچھ لگایا وہ سب ہٹا دیں؟',
  items_on_page: 'اس صفحے پر {n} چیزیں', page_canvas: 'PDF صفحہ', items_label: 'صفحے پر لگائی گئی چیزیں',
  stage_hint: 'کسی چیز کو چننے کے لیے ٹیپ کریں، کھسکانے کے لیے گھسیٹیں، سائز بدلنے کے لیے نیلا کونا گھسیٹیں۔ تیر والی کلیدیں بھی اسے کھسکاتی ہیں۔',
  added: 'صفحے پر لگ گیا۔ اسے صحیح جگہ پر گھسیٹیں۔', added_all: 'سبھی {n} صفحوں پر لگ گیا۔', removed: 'ہٹا دیا۔',
  item_sig: 'دستخط', item_init: 'مخفف دستخط', item_stamp: 'مہر', item_text: 'متن', item_date: 'تاریخ', item_tick: 'ٹِک', item_cross: 'کراس', item_white: 'سفید خانہ',
  tools_label: 'ٹول',
  tool_sign: 'دستخط', tool_text: 'متن', tool_date: 'تاریخ', tool_mark: 'ٹِک / کراس', tool_self: 'خود تصدیق', tool_stamp: 'مہر', tool_hide: 'سفیدی', tool_form: 'فارم کے خانے',
  sig_draw: 'بنائیں', sig_type: 'ٹائپ', sig_photo: 'تصویر',
  sig_pad_hint: 'یہاں انگلی، اسٹائلس یا ماؤس سے سائن کریں۔',
  sig_type_label: 'آپ کا نام', sig_type_ph: 'جیسے پریا شرما', sig_type_prev_empty: 'آپ کا نام یہاں ہاتھ کی لکھائی کے انداز میں دکھے گا',
  sig_photo_pick: 'اپنے دستخط کی تصویر چنیں',
  sig_photo_hint: 'سفید کاغذ پر گہرے قلم سے سائن کریں اور صاف تصویر لیں۔ کاغذ خود بخود شفاف ہو جاتا ہے۔',
  ink: 'سیاہی کا رنگ', col_blue: 'نیلا', col_black: 'کالا', col_red: 'لال', col_green: 'ہرا',
  sig_use: 'دستخط کے طور پر لگائیں', sig_use_init: 'مخفف کے طور پر لگائیں',
  sig_empty: 'پہلے دستخط بنائیں، ٹائپ کریں یا تصویر چنیں۔',
  sig_saved_title: 'اس ڈیوائس پر محفوظ', sig_saved_sig: 'دستخط', sig_saved_init: 'مخفف دستخط',
  sig_add: 'صفحے پر لگائیں', sig_add_all: 'ہر صفحے پر', sig_forget: 'بھول جائیں',
  sig_saved_note: 'صرف اسی براؤزر میں محفوظ ہے تاکہ دوبارہ کام آئے۔ مشترکہ کمپیوٹر پر کام ختم ہونے پر “بھول جائیں” دبائیں۔',
  sig_too_big: 'یہ تصویر اگلی بار کے لیے یاد رکھنے کو بہت بڑی ہے، مگر صفحے پر لگ گئی ہے۔',
  forgotten: 'بھلا دیا گیا۔',
  text_label: 'متن', text_ph: 'جیسے Approved، Paid، پریا شرما', text_size: 'سائز', text_style: 'انداز', font_normal: 'عام', font_hand: 'ہاتھ کی لکھائی',
  text_ink_note: 'دستخط والے حصے میں چنا گیا سیاہی کا رنگ استعمال ہوتا ہے۔', text_add: 'متن لگائیں',
  date_label: 'تاریخ', date_fmt: 'انداز', date_add: 'تاریخ لگائیں',
  mark_help: 'خانے میں ٹِک لگائیں یا کسی آپشن کو کاٹیں۔ بڑا کرنے کے لیے کونا گھسیٹیں۔', mark_tick: 'ٹِک', mark_cross: 'کراس',
  self_help: 'دفتر آدھار، PAN، مارک شیٹ اور سرٹیفکیٹ کی “خود تصدیق شدہ” کاپیاں مانگتے ہیں: ہر کاپی پر یہ لکھیں، سائن کریں اور تاریخ ڈالیں۔ یہ تینوں ایک ساتھ لگاتا ہے۔',
  self_text_label: 'متن', self_default: 'خود تصدیق شدہ',
  self_need_sig: 'پہلے دستخط بنائیں (بنا کر، ٹائپ کر کے یا تصویر سے)۔ یہ متن اور آج کی تاریخ کے ساتھ لگتا ہے۔',
  self_add: 'اس صفحے پر لگائیں', self_add_all: 'ہر صفحے پر',
  stamp_help: 'کمپنی کی مہر، “PAID”، “RECEIVED”، اسکول کی مہر۔ شفاف پس منظر والی PNG سب سے اچھی لگتی ہے۔',
  stamp_pick: 'مہر کی تصویر چنیں', stamp_last: 'مہر',
  hide_help: 'صفحے کا کچھ حصہ سفید خانے سے ڈھک دیتا ہے، جیسے پرانی تاریخ یا غلط اندراج۔ نیچے کا متن فائل میں پھر بھی رہتا ہے، اس لیے راز چھپانے کے لیے استعمال نہ کریں۔',
  hide_add: 'سفید خانہ لگائیں',
  form_none: 'اس PDF میں بھرنے والے خانے نہیں ہیں۔ اس پر لکھنے کے لیے متن ٹول استعمال کریں۔',
  form_xfa: 'یہ XFA فارم ہے؛ اس کے خانے یہاں نہیں بھرے جا سکتے۔',
  form_help: '{n} خانے ملے۔ انہیں یہاں بھریں؛ محفوظ کرنے پر یہ PDF میں لکھ دیے جاتے ہیں۔ صفحے پر نمایاں خانے کو ٹیپ کر کے اس تک جائیں۔',
  form_flatten: 'محفوظ کرنے کے بعد خانوں کو لاک کریں (flatten)',
  field_aria: 'فارم کا خانہ {name}',
  out_name: 'فائل کا نام', save_btn: 'سائن شدہ PDF محفوظ کریں', saving: 'PDF بن رہی ہے…',
  result_msg: '{name} محفوظ ہو گئی ({size})۔ بھیجنے سے پہلے ایک بار کھول کر جانچ لیں۔', download_again: 'دوبارہ ڈاؤن لوڈ',
  nothing_added: 'ابھی کچھ نہیں لگایا۔ پہلے دستخط، متن یا تاریخ لگائیں۔',
  legal_title: 'براہ کرم دھیان دیں',
  legal_body: 'یہ PDF پر آپ کے دستخط کی تصویر لگاتا ہے۔ یہ IT Act کے تحت ڈیجیٹل سگنیچر سرٹیفکیٹ (DSC) یا آدھار eSign نہیں ہے۔ بہت سے دفتر روزمرہ کاغذات کے لیے اسے مان لیتے ہیں، مگر کچھ فائلنگ (GST، MCA، انکم ٹیکس، ٹینڈر) کے لیے DSC یا eSign چاہیے۔ لینے والے سے پوچھ لیں۔',
  help_title: 'استعمال کا طریقہ · کام کے آئیڈیا',
  tip1: 'PDF کھولیں، ایک بار دستخط بنائیں اور “دستخط کے طور پر لگائیں” دبائیں۔ یہ اس ڈیوائس پر محفوظ رہتا ہے، اگلی بار بس “صفحے پر لگائیں” دبائیں۔',
  tip2: 'آفر لیٹر یا معاہدہ: دستخط لگائیں، پھر “تاریخ”، پھر متن ٹول سے اپنا نام لکھیں۔ محفوظ کریں اور نئی فائل واپس بھیجیں۔',
  tip3: 'بینک، اسکول یا نوکری کے لیے کاغذات کی کاپیاں: ہر صفحے پر “خود تصدیق” لگائیں۔ بینک کہے تو PDF Merge ایپ سے KYC واٹر مارک لگائیں۔',
  tip4: 'دکان یا دفتر: اپنی ربر اسٹیمپ کی PNG بنائیں (سفید کاغذ پر تصویر، تصویر ٹول) اور بل اور رسید پر “مہر” لگائیں۔',
  tip5: 'خانوں والے فارم: “فارم کے خانے” ٹول انہیں دکھاتا ہے؛ سیدھے بھریں اور ٹِک کریں۔ اسکین کیے فارم کے لیے متن، ٹِک اور کراس استعمال کریں۔',
  tip6: 'کاغذ پر غلطی ہو گئی؟ اسکین کریں، غلطی کو سفید خانے سے ڈھکیں اور متن سے درستی لکھیں۔',
  keys_title: 'کی بورڈ',
  key1: 'Tab سے کسی چیز پر جائیں، پھر تیر والی کلیدیں اسے کھسکاتی ہیں؛ Shift + تیر تیزی سے کھسکاتا ہے۔',
  key2: '+ اور − چنی ہوئی چیز کو بڑا یا چھوٹا کرتے ہیں۔',
  key3: 'Delete اسے ہٹاتا ہے؛ Esc چناؤ ختم کرتا ہے۔',
  key4: 'Ctrl+Z واپس، Ctrl+Y دوبارہ۔',
  reset_help: 'اس ڈیوائس پر محفوظ دستخط اور سیٹنگز بھلا دیں۔', reset_done: 'ری سیٹ ہو گیا۔',
  sample_title: 'نمونہ آفر لیٹر', sample_file: 'namoona-offer-letter.pdf',
  sample_org: 'Sunrise Technologies Pvt. Ltd.', sample_addr: 'ہنجے واڑی، پونے 411057 · hr@example.com',
  sample_heading: 'آفر لیٹر',
  sample_p1: 'محترمہ پریا شرما،',
  sample_p2: 'ہمیں خوشی ہے کہ ہم آپ کو 1 نومبر 2026 سے جونیئر اکاؤنٹنٹ کے عہدے پر ₹ 25,000 ماہانہ تنخواہ پر رکھ رہے ہیں۔ دفتر کا وقت پیر سے سنیچر، صبح 9:30 سے شام 6:00 تک ہے۔',
  sample_p3: 'آفر قبول کرنے کے لیے نیچے اپنا نام بھریں، خانے میں ٹِک کریں، سائن کریں، تاریخ ڈالیں اور یہ خط واپس بھیجیں۔',
  sample_name_lbl: 'پورا نام:', sample_agree: 'میں یہ آفر قبول کرتی/کرتا ہوں۔', sample_sign_lbl: 'دستخط:', sample_date_lbl: 'تاریخ:',
  sample_footer: 'مشق کے لیے AI Pathshala کا بنایا نمونہ کاغذ۔ اصلی آفر نہیں۔'
},

};
