/* UI strings for Certificate Maker. Keys are identical in all 12 languages.
   Shared words (print, reset, next, previous, fullscreen, ...) come from EDU.COMMON.
   {name} {event} {position} {school} {date} inside help/hint texts are literal tokens the teacher types. */
window.APP_STRINGS = {};

window.APP_STRINGS.en = {
  app_title: 'Certificate Maker',
  intro: 'Make beautiful certificates for the whole class in one go: type the names, pick a design, then print them all or save as PNG.',
  help_title: 'How to use · Ideas for the classroom',
  help_1: 'Type or paste the names, one per line. Add a position after a dash, like "Aarav Sharma - 1st". 1st, 2nd and 3rd also get a gold, silver or bronze seal.',
  help_2: 'Choose the certificate type and a design. The title and message change by themselves, and you can still edit them.',
  help_3: 'In the message you can use {name}, {event}, {position}, {school} and {date}. They are filled in for every person.',
  help_4: '"Print all" puts each certificate on its own A4 landscape page. In the print window turn on "Background graphics" for full colour, or choose "Save as PDF".',
  help_5: 'Classroom idea: after a quiz or sports day, let students type the winners list and pick the design, then show each certificate full screen on the smartboard during the prize ceremony.',
  help_6: 'Want the certificate in English while the app is in your language? Choose English under "Certificate language".',
  sec_design: 'Design',
  sec_names: 'Names',
  sec_text: 'Certificate text',
  sec_school: 'School, signatures and date',
  sec_preview: 'Preview',
  designs_aria: 'Choose a design',
  d_classic: 'Classic Gold',
  d_royal: 'Royal Blue',
  d_tiranga: 'Tricolour',
  d_rangoli: 'Rangoli',
  d_modern: 'Modern',
  f_names: 'Names, one per line',
  f_names_hint: 'Add a position after a dash: "Aarav Sharma - 1st". You can also paste a column from Excel.',
  count_n: '{n} certificates',
  count_1: '1 certificate',
  too_many: 'Only the first {n} names are used.',
  no_names: 'Type at least one name to make certificates.',
  f_type: 'Certificate type',
  type_merit: 'Merit',
  type_participation: 'Participation',
  type_appreciation: 'Appreciation',
  type_excellence: 'Excellence',
  type_completion: 'Completion',
  title_merit: 'Certificate of Merit',
  title_participation: 'Certificate of Participation',
  title_appreciation: 'Certificate of Appreciation',
  title_excellence: 'Certificate of Excellence',
  title_completion: 'Certificate of Completion',
  f_title: 'Title on the certificate',
  f_event: 'Event or reason',
  f_message: 'Message',
  f_message_hint: 'Use {name}, {event}, {position}, {school} or {date} to fill in details for each person.',
  msg_default: 'Use default text',
  msg_merit: 'for outstanding performance in {event}. We are proud of your hard work.',
  msg_merit_gen: 'for outstanding performance and hard work. We are proud of you!',
  msg_participation: 'for taking part with enthusiasm in {event}. Keep learning and keep shining!',
  msg_participation_gen: 'for taking part with enthusiasm. Keep learning and keep shining!',
  msg_appreciation: 'in appreciation of the valuable contribution to {event}. Thank you for your dedication.',
  msg_appreciation_gen: 'in appreciation of the valuable contribution and dedication. Thank you!',
  msg_excellence: 'for excellence in {event}. Your effort and talent inspire everyone.',
  msg_excellence_gen: 'for excellence in studies and good conduct. Your effort inspires everyone.',
  msg_completion: 'for successfully completing {event}.',
  msg_completion_gen: 'for successfully completing the course with sincerity and commitment.',
  f_certlang: 'Certificate language',
  certlang_ui: 'Same as the app',
  certlang_en: 'English',
  f_school: 'School name',
  f_logo: 'School logo (optional)',
  logo_add: 'Add logo',
  logo_remove: 'Remove logo',
  logo_bad: 'Could not open that image. Try a PNG or JPG file.',
  logo_alt: 'School logo',
  f_date: 'Date on the certificate',
  f_date_hint: 'Leave it empty to hide the date.',
  f_sig1: 'Signature 1',
  f_sig2: 'Signature 2',
  f_sig_name: 'Name',
  f_sig_role: 'Designation',
  f_seal: 'Show the seal',
  cert_presented: 'This certificate is proudly presented to',
  cert_date: 'Date',
  name_placeholder: 'Student name',
  pos_1: 'First Place',
  pos_2: 'Second Place',
  pos_3: 'Third Place',
  pos_word_1: 'First',
  pos_word_2: 'Second',
  pos_word_3: 'Third',
  btn_print_all: 'Print all',
  btn_print_one: 'Print this one',
  btn_png: 'Save as PNG',
  prev_of: '{i} of {n}',
  keys_tip: 'Tip: use the arrow keys to move between certificates, even in full screen.',
  print_tip: 'In the print window choose A4, Landscape and margins "None", and turn on "Background graphics".',
  png_wait: 'Making the image…',
  png_fail: 'This browser could not make the image. Use "Print" and choose "Save as PDF" instead.',
  png_done: 'Image saved',
  sample_names: 'Aarav Sharma - 1st\nPriya Nair - 2nd\nMohammed Irfan - 3rd\nAnanya Das\nGurpreet Kaur\nKavya Reddy',
  sample_event: 'Annual Science Exhibition 2026',
  sample_school: 'Government Senior Secondary School, Jaipur',
  sample_sig1_name: 'Sunita Verma',
  sample_sig1_role: 'Class Teacher',
  sample_sig2_name: 'Dr. Rajesh Mehta',
  sample_sig2_role: 'Principal'
};

window.APP_STRINGS.hi = {
  app_title: 'प्रमाण पत्र मेकर',
  intro: 'पूरी कक्षा के सुंदर प्रमाण पत्र एक बार में बनाइए: नाम लिखिए, डिज़ाइन चुनिए, फिर सब प्रिंट कीजिए या PNG में सेव कीजिए।',
  help_title: 'कैसे इस्तेमाल करें · कक्षा के लिए आइडिया',
  help_1: 'नाम लिखें या पेस्ट करें, हर लाइन में एक नाम। स्थान जोड़ने के लिए डैश के बाद लिखें, जैसे "आरव शर्मा - प्रथम"। प्रथम, द्वितीय और तृतीय (या 1, 2, 3) को सुनहरी, चाँदी या काँसे जैसी मुहर भी मिलती है।',
  help_2: 'प्रमाण पत्र का प्रकार और डिज़ाइन चुनें। शीर्षक और संदेश अपने-आप बदल जाते हैं, फिर भी आप उन्हें बदल सकते हैं।',
  help_3: 'संदेश में {name}, {event}, {position}, {school} और {date} लिख सकते हैं। हर व्यक्ति के लिए ये अपने-आप भर जाते हैं।',
  help_4: '"सब प्रिंट करें" से हर प्रमाण पत्र अलग A4 लैंडस्केप पेज पर छपता है। प्रिंट विंडो में पूरे रंगों के लिए "Background graphics" चालू करें, या "Save as PDF" चुनें।',
  help_5: 'कक्षा के लिए आइडिया: क्विज़ या खेल दिवस के बाद बच्चों से विजेताओं की सूची लिखवाएँ और डिज़ाइन चुनवाएँ, फिर पुरस्कार समारोह में हर प्रमाण पत्र स्मार्टबोर्ड पर पूरी स्क्रीन में दिखाएँ।',
  help_6: 'ऐप आपकी भाषा में है, पर प्रमाण पत्र अंग्रेज़ी में चाहिए? "प्रमाण पत्र की भाषा" में अंग्रेज़ी चुनें।',
  sec_design: 'डिज़ाइन',
  sec_names: 'नाम',
  sec_text: 'प्रमाण पत्र का लेख',
  sec_school: 'स्कूल, हस्ताक्षर और तारीख',
  sec_preview: 'झलक',
  designs_aria: 'डिज़ाइन चुनें',
  d_classic: 'सुनहरा क्लासिक',
  d_royal: 'शाही नीला',
  d_tiranga: 'तिरंगा',
  d_rangoli: 'रंगोली',
  d_modern: 'आधुनिक',
  f_names: 'नाम, हर लाइन में एक',
  f_names_hint: 'डैश के बाद स्थान लिखें: "आरव शर्मा - प्रथम"। Excel से पूरा कॉलम भी पेस्ट कर सकते हैं।',
  count_n: '{n} प्रमाण पत्र',
  count_1: '1 प्रमाण पत्र',
  too_many: 'सिर्फ़ पहले {n} नाम लिए जाएँगे।',
  no_names: 'प्रमाण पत्र बनाने के लिए कम से कम एक नाम लिखें।',
  f_type: 'प्रमाण पत्र का प्रकार',
  type_merit: 'योग्यता (मेरिट)',
  type_participation: 'सहभागिता',
  type_appreciation: 'प्रशंसा',
  type_excellence: 'उत्कृष्टता',
  type_completion: 'कोर्स पूरा करना',
  title_merit: 'योग्यता प्रमाण पत्र',
  title_participation: 'सहभागिता प्रमाण पत्र',
  title_appreciation: 'प्रशंसा प्रमाण पत्र',
  title_excellence: 'उत्कृष्टता प्रमाण पत्र',
  title_completion: 'पूर्णता प्रमाण पत्र',
  f_title: 'प्रमाण पत्र का शीर्षक',
  f_event: 'कार्यक्रम या कारण',
  f_message: 'संदेश',
  f_message_hint: 'हर व्यक्ति की जानकारी भरने के लिए {name}, {event}, {position}, {school} या {date} लिखें।',
  msg_default: 'पहले वाला लेख लगाएँ',
  msg_merit: 'ने {event} में उत्कृष्ट प्रदर्शन किया है। हमें इस मेहनत पर गर्व है।',
  msg_merit_gen: 'ने उत्कृष्ट प्रदर्शन और कड़ी मेहनत की है। हमें आप पर गर्व है!',
  msg_participation: 'ने {event} में उत्साह के साथ भाग लिया। सीखते रहें, आगे बढ़ते रहें!',
  msg_participation_gen: 'ने उत्साह के साथ भाग लिया। सीखते रहें, आगे बढ़ते रहें!',
  msg_appreciation: 'ने {event} में बहुमूल्य योगदान दिया है। आपके समर्पण के लिए हार्दिक धन्यवाद।',
  msg_appreciation_gen: 'ने बहुमूल्य योगदान और समर्पण दिखाया है। हार्दिक धन्यवाद!',
  msg_excellence: 'ने {event} में उत्कृष्टता दिखाई है। आपकी मेहनत और प्रतिभा सबको प्रेरित करती है।',
  msg_excellence_gen: 'ने पढ़ाई और अच्छे आचरण में उत्कृष्टता दिखाई है। आपकी मेहनत सबको प्रेरित करती है।',
  msg_completion: 'ने {event} सफलतापूर्वक पूरा किया है।',
  msg_completion_gen: 'ने पूरी लगन और ईमानदारी से यह कोर्स सफलतापूर्वक पूरा किया है।',
  f_certlang: 'प्रमाण पत्र की भाषा',
  certlang_ui: 'ऐप वाली भाषा',
  certlang_en: 'अंग्रेज़ी',
  f_school: 'स्कूल का नाम',
  f_logo: 'स्कूल का लोगो (चाहें तो)',
  logo_add: 'लोगो जोड़ें',
  logo_remove: 'लोगो हटाएँ',
  logo_bad: 'यह चित्र नहीं खुल सका। PNG या JPG फ़ाइल आज़माएँ।',
  logo_alt: 'स्कूल का लोगो',
  f_date: 'प्रमाण पत्र पर तारीख',
  f_date_hint: 'तारीख छिपानी हो तो इसे खाली छोड़ दें।',
  f_sig1: 'हस्ताक्षर 1',
  f_sig2: 'हस्ताक्षर 2',
  f_sig_name: 'नाम',
  f_sig_role: 'पद',
  f_seal: 'मुहर दिखाएँ',
  cert_presented: 'प्रमाणित किया जाता है कि',
  cert_date: 'दिनांक',
  name_placeholder: 'विद्यार्थी का नाम',
  pos_1: 'प्रथम स्थान',
  pos_2: 'द्वितीय स्थान',
  pos_3: 'तृतीय स्थान',
  pos_word_1: 'प्रथम',
  pos_word_2: 'द्वितीय',
  pos_word_3: 'तृतीय',
  btn_print_all: 'सब प्रिंट करें',
  btn_print_one: 'यह वाला प्रिंट करें',
  btn_png: 'PNG में सेव करें',
  prev_of: '{n} में से {i}',
  keys_tip: 'सुझाव: एक से दूसरे प्रमाण पत्र पर जाने के लिए तीर वाली कुंजियाँ दबाएँ, पूरी स्क्रीन में भी।',
  print_tip: 'प्रिंट विंडो में A4, Landscape और margins "None" चुनें, और "Background graphics" चालू करें।',
  png_wait: 'चित्र बन रहा है…',
  png_fail: 'यह ब्राउज़र चित्र नहीं बना सका। इसके बजाय "प्रिंट करें" दबाकर "Save as PDF" चुनें।',
  png_done: 'चित्र सेव हो गया',
  sample_names: 'आरव शर्मा - प्रथम\nप्रिया नायर - द्वितीय\nमोहम्मद इरफ़ान - तृतीय\nअनन्या दास\nगुरप्रीत कौर\nकाव्या रेड्डी',
  sample_event: 'वार्षिक विज्ञान प्रदर्शनी 2026',
  sample_school: 'राजकीय उच्च माध्यमिक विद्यालय, जयपुर',
  sample_sig1_name: 'सुनीता वर्मा',
  sample_sig1_role: 'कक्षा अध्यापिका',
  sample_sig2_name: 'डॉ. राजेश मेहता',
  sample_sig2_role: 'प्रधानाचार्य'
};

window.APP_STRINGS.bn = {
  app_title: 'সার্টিফিকেট মেকার',
  intro: 'পুরো ক্লাসের সুন্দর সার্টিফিকেট একবারেই বানান: নাম লিখুন, ডিজাইন বাছুন, তারপর সব প্রিন্ট করুন বা PNG হিসেবে সেভ করুন।',
  help_title: 'কীভাবে ব্যবহার করবেন · ক্লাসের জন্য আইডিয়া',
  help_1: 'নাম লিখুন বা পেস্ট করুন, প্রতি লাইনে একটি নাম। স্থান যোগ করতে ড্যাশের পরে লিখুন, যেমন "অর্ক বসু - প্রথম"। প্রথম, দ্বিতীয় ও তৃতীয় (বা 1, 2, 3) সোনালি, রুপোলি বা ব্রোঞ্জ রঙের সিলও পায়।',
  help_2: 'সার্টিফিকেটের ধরন আর ডিজাইন বাছুন। শিরোনাম আর বার্তা নিজে থেকেই বদলে যায়, তবু আপনি সেগুলো বদলাতে পারেন।',
  help_3: 'বার্তায় {name}, {event}, {position}, {school} আর {date} লিখতে পারেন। প্রত্যেকের জন্য এগুলো নিজে থেকেই ভরে যায়।',
  help_4: '"সব প্রিন্ট করুন" দিলে প্রতিটি সার্টিফিকেট আলাদা A4 ল্যান্ডস্কেপ পাতায় ছাপা হয়। প্রিন্ট উইন্ডোতে পুরো রঙের জন্য "Background graphics" চালু করুন, বা "Save as PDF" বাছুন।',
  help_5: 'ক্লাসের আইডিয়া: কুইজ বা ক্রীড়া দিবসের পরে ছাত্রছাত্রীদের দিয়ে বিজয়ীদের তালিকা লেখান আর ডিজাইন বাছাই করান, তারপর পুরস্কার বিতরণের সময় প্রতিটি সার্টিফিকেট স্মার্টবোর্ডে পূর্ণ পর্দায় দেখান।',
  help_6: 'অ্যাপ আপনার ভাষায়, কিন্তু সার্টিফিকেট ইংরেজিতে চান? "সার্টিফিকেটের ভাষা"-তে ইংরেজি বাছুন।',
  sec_design: 'ডিজাইন',
  sec_names: 'নাম',
  sec_text: 'সার্টিফিকেটের লেখা',
  sec_school: 'স্কুল, স্বাক্ষর ও তারিখ',
  sec_preview: 'প্রিভিউ',
  designs_aria: 'ডিজাইন বাছুন',
  d_classic: 'সোনালি ক্লাসিক',
  d_royal: 'রাজকীয় নীল',
  d_tiranga: 'তেরঙা',
  d_rangoli: 'আলপনা',
  d_modern: 'আধুনিক',
  f_names: 'নাম, প্রতি লাইনে একটি',
  f_names_hint: 'ড্যাশের পরে স্থান লিখুন: "অর্ক বসু - প্রথম"। Excel থেকে পুরো কলামও পেস্ট করতে পারেন।',
  count_n: '{n}টি সার্টিফিকেট',
  count_1: '1টি সার্টিফিকেট',
  too_many: 'শুধু প্রথম {n}টি নাম নেওয়া হবে।',
  no_names: 'সার্টিফিকেট বানাতে অন্তত একটি নাম লিখুন।',
  f_type: 'সার্টিফিকেটের ধরন',
  type_merit: 'মেধা',
  type_participation: 'অংশগ্রহণ',
  type_appreciation: 'প্রশংসা',
  type_excellence: 'উৎকর্ষ',
  type_completion: 'কোর্স সমাপ্তি',
  title_merit: 'মেধা শংসাপত্র',
  title_participation: 'অংশগ্রহণ শংসাপত্র',
  title_appreciation: 'প্রশংসাপত্র',
  title_excellence: 'উৎকর্ষ শংসাপত্র',
  title_completion: 'সমাপ্তি শংসাপত্র',
  f_title: 'সার্টিফিকেটের শিরোনাম',
  f_event: 'অনুষ্ঠান বা কারণ',
  f_message: 'বার্তা',
  f_message_hint: 'প্রত্যেকের তথ্য ভরতে {name}, {event}, {position}, {school} বা {date} লিখুন।',
  msg_default: 'আগের লেখা ফিরিয়ে আনুন',
  msg_merit: '{event}-এ অসাধারণ কৃতিত্ব দেখিয়েছে। এই পরিশ্রমে আমরা গর্বিত।',
  msg_merit_gen: 'অসাধারণ কৃতিত্ব ও পরিশ্রম দেখিয়েছে। আমরা গর্বিত!',
  msg_participation: '{event}-এ উৎসাহের সঙ্গে অংশগ্রহণ করেছে। শিখতে থাকো, এগিয়ে চলো!',
  msg_participation_gen: 'উৎসাহের সঙ্গে অংশগ্রহণ করেছে। শিখতে থাকো, এগিয়ে চলো!',
  msg_appreciation: '{event}-এ মূল্যবান অবদান রেখেছে। এই নিষ্ঠার জন্য আন্তরিক ধন্যবাদ।',
  msg_appreciation_gen: 'মূল্যবান অবদান ও নিষ্ঠা দেখিয়েছে। আন্তরিক ধন্যবাদ!',
  msg_excellence: '{event}-এ উৎকর্ষ দেখিয়েছে। এই পরিশ্রম ও প্রতিভা সবাইকে অনুপ্রাণিত করে।',
  msg_excellence_gen: 'পড়াশোনা ও সুন্দর আচরণে উৎকর্ষ দেখিয়েছে। এই পরিশ্রম সবাইকে অনুপ্রাণিত করে।',
  msg_completion: 'সাফল্যের সঙ্গে {event} সম্পূর্ণ করেছে।',
  msg_completion_gen: 'নিষ্ঠা ও আন্তরিকতার সঙ্গে কোর্সটি সাফল্যের সঙ্গে সম্পূর্ণ করেছে।',
  f_certlang: 'সার্টিফিকেটের ভাষা',
  certlang_ui: 'অ্যাপের ভাষাই',
  certlang_en: 'ইংরেজি',
  f_school: 'স্কুলের নাম',
  f_logo: 'স্কুলের লোগো (ইচ্ছে হলে)',
  logo_add: 'লোগো যোগ করুন',
  logo_remove: 'লোগো সরান',
  logo_bad: 'ছবিটি খোলা গেল না। PNG বা JPG ফাইল দিয়ে দেখুন।',
  logo_alt: 'স্কুলের লোগো',
  f_date: 'সার্টিফিকেটের তারিখ',
  f_date_hint: 'তারিখ লুকোতে চাইলে এটি খালি রাখুন।',
  f_sig1: 'স্বাক্ষর 1',
  f_sig2: 'স্বাক্ষর 2',
  f_sig_name: 'নাম',
  f_sig_role: 'পদ',
  f_seal: 'সিল দেখান',
  cert_presented: 'এই মর্মে প্রত্যয়িত করা হচ্ছে যে',
  cert_date: 'তারিখ',
  name_placeholder: 'ছাত্র/ছাত্রীর নাম',
  pos_1: 'প্রথম স্থান',
  pos_2: 'দ্বিতীয় স্থান',
  pos_3: 'তৃতীয় স্থান',
  pos_word_1: 'প্রথম',
  pos_word_2: 'দ্বিতীয়',
  pos_word_3: 'তৃতীয়',
  btn_print_all: 'সব প্রিন্ট করুন',
  btn_print_one: 'এটি প্রিন্ট করুন',
  btn_png: 'PNG হিসেবে সেভ করুন',
  prev_of: '{n}টির মধ্যে {i}',
  keys_tip: 'টিপস: এক সার্টিফিকেট থেকে আরেকটিতে যেতে তীর-চিহ্নের কী ব্যবহার করুন, পূর্ণ পর্দাতেও।',
  print_tip: 'প্রিন্ট উইন্ডোতে A4, Landscape আর margins "None" বাছুন এবং "Background graphics" চালু করুন।',
  png_wait: 'ছবি তৈরি হচ্ছে…',
  png_fail: 'এই ব্রাউজার ছবি বানাতে পারল না। তার বদলে "প্রিন্ট" দিয়ে "Save as PDF" বাছুন।',
  png_done: 'ছবি সেভ হয়েছে',
  sample_names: 'অর্ক বসু - প্রথম\nঋতিকা দাস - দ্বিতীয়\nসায়ন মুখার্জি - তৃতীয়\nতানিয়া সেন\nরাহুল ঘোষ\nপূজা রায়',
  sample_event: 'বার্ষিক বিজ্ঞান প্রদর্শনী 2026',
  sample_school: 'সরকারি উচ্চ মাধ্যমিক বিদ্যালয়, কলকাতা',
  sample_sig1_name: 'সুমিতা চক্রবর্তী',
  sample_sig1_role: 'শ্রেণি শিক্ষিকা',
  sample_sig2_name: 'ড. অমিতাভ সেনগুপ্ত',
  sample_sig2_role: 'প্রধান শিক্ষক'
};

window.APP_STRINGS.mr = {
  app_title: 'प्रमाणपत्र मेकर',
  intro: 'संपूर्ण वर्गाची सुंदर प्रमाणपत्रे एकाच वेळी बनवा: नावे लिहा, डिझाइन निवडा, मग सगळी प्रिंट करा किंवा PNG म्हणून सेव्ह करा.',
  help_title: 'कसे वापरायचे · वर्गासाठी कल्पना',
  help_1: 'नावे लिहा किंवा पेस्ट करा, प्रत्येक ओळीत एक नाव. क्रमांक जोडण्यासाठी डॅशनंतर लिहा, उदा. "आदित्य पाटील - प्रथम". प्रथम, द्वितीय आणि तृतीय (किंवा 1, 2, 3) यांना सोनेरी, चंदेरी किंवा कांस्य रंगाचा शिक्काही मिळतो.',
  help_2: 'प्रमाणपत्राचा प्रकार आणि डिझाइन निवडा. शीर्षक आणि संदेश आपोआप बदलतात, तरीही तुम्ही ते बदलू शकता.',
  help_3: 'संदेशात {name}, {event}, {position}, {school} आणि {date} वापरू शकता. प्रत्येकासाठी ते आपोआप भरले जातात.',
  help_4: '"सर्व प्रिंट करा" मुळे प्रत्येक प्रमाणपत्र वेगळ्या A4 लँडस्केप पानावर छापले जाते. प्रिंट विंडोमध्ये पूर्ण रंगांसाठी "Background graphics" चालू करा, किंवा "Save as PDF" निवडा.',
  help_5: 'वर्गासाठी कल्पना: प्रश्नमंजूषा किंवा क्रीडा दिनानंतर विद्यार्थ्यांकडून विजेत्यांची यादी लिहून घ्या आणि डिझाइन निवडू द्या, मग बक्षीस समारंभात प्रत्येक प्रमाणपत्र स्मार्टबोर्डवर पूर्ण स्क्रीनमध्ये दाखवा.',
  help_6: 'ॲप तुमच्या भाषेत आहे, पण प्रमाणपत्र इंग्रजीत हवे आहे? "प्रमाणपत्राची भाषा" मध्ये इंग्रजी निवडा.',
  sec_design: 'डिझाइन',
  sec_names: 'नावे',
  sec_text: 'प्रमाणपत्रातील मजकूर',
  sec_school: 'शाळा, स्वाक्षऱ्या आणि दिनांक',
  sec_preview: 'पूर्वावलोकन',
  designs_aria: 'डिझाइन निवडा',
  d_classic: 'सोनेरी क्लासिक',
  d_royal: 'राजेशाही निळा',
  d_tiranga: 'तिरंगा',
  d_rangoli: 'रांगोळी',
  d_modern: 'आधुनिक',
  f_names: 'नावे, प्रत्येक ओळीत एक',
  f_names_hint: 'डॅशनंतर क्रमांक लिहा: "आदित्य पाटील - प्रथम". Excel मधून पूर्ण कॉलमही पेस्ट करू शकता.',
  count_n: '{n} प्रमाणपत्रे',
  count_1: '1 प्रमाणपत्र',
  too_many: 'फक्त पहिली {n} नावे घेतली जातील.',
  no_names: 'प्रमाणपत्र बनवण्यासाठी किमान एक नाव लिहा.',
  f_type: 'प्रमाणपत्राचा प्रकार',
  type_merit: 'गुणवत्ता',
  type_participation: 'सहभाग',
  type_appreciation: 'प्रशंसा',
  type_excellence: 'उत्कृष्टता',
  type_completion: 'अभ्यासक्रम पूर्तता',
  title_merit: 'गुणवत्ता प्रमाणपत्र',
  title_participation: 'सहभाग प्रमाणपत्र',
  title_appreciation: 'प्रशंसा प्रमाणपत्र',
  title_excellence: 'उत्कृष्टता प्रमाणपत्र',
  title_completion: 'पूर्तता प्रमाणपत्र',
  f_title: 'प्रमाणपत्रावरील शीर्षक',
  f_event: 'कार्यक्रम किंवा कारण',
  f_message: 'संदेश',
  f_message_hint: 'प्रत्येकाची माहिती भरण्यासाठी {name}, {event}, {position}, {school} किंवा {date} लिहा.',
  msg_default: 'मूळ मजकूर वापरा',
  msg_merit: 'यांनी {event} मध्ये उत्कृष्ट कामगिरी केली आहे. त्यांच्या मेहनतीचा आम्हाला अभिमान आहे.',
  msg_merit_gen: 'यांनी उत्कृष्ट कामगिरी आणि कठोर परिश्रम केले आहेत. आम्हाला अभिमान आहे!',
  msg_participation: 'यांनी {event} मध्ये उत्साहाने सहभाग घेतला. शिकत राहा, पुढे जात राहा!',
  msg_participation_gen: 'यांनी उत्साहाने सहभाग घेतला. शिकत राहा, पुढे जात राहा!',
  msg_appreciation: 'यांनी {event} मध्ये मोलाचे योगदान दिले आहे. त्यांच्या समर्पणाबद्दल मनःपूर्वक आभार.',
  msg_appreciation_gen: 'यांनी मोलाचे योगदान आणि समर्पण दाखवले आहे. मनःपूर्वक आभार!',
  msg_excellence: 'यांनी {event} मध्ये उत्कृष्टता दाखवली आहे. त्यांची मेहनत आणि प्रतिभा सर्वांना प्रेरणा देते.',
  msg_excellence_gen: 'यांनी अभ्यास आणि चांगल्या वर्तनात उत्कृष्टता दाखवली आहे. त्यांची मेहनत सर्वांना प्रेरणा देते.',
  msg_completion: 'यांनी {event} यशस्वीरीत्या पूर्ण केले आहे.',
  msg_completion_gen: 'यांनी हा अभ्यासक्रम मन लावून आणि प्रामाणिकपणे यशस्वीरीत्या पूर्ण केला आहे.',
  f_certlang: 'प्रमाणपत्राची भाषा',
  certlang_ui: 'ॲपचीच भाषा',
  certlang_en: 'इंग्रजी',
  f_school: 'शाळेचे नाव',
  f_logo: 'शाळेचा लोगो (हवा असल्यास)',
  logo_add: 'लोगो जोडा',
  logo_remove: 'लोगो काढा',
  logo_bad: 'हे चित्र उघडता आले नाही. PNG किंवा JPG फाइल वापरून पाहा.',
  logo_alt: 'शाळेचा लोगो',
  f_date: 'प्रमाणपत्रावरील दिनांक',
  f_date_hint: 'दिनांक लपवायचा असल्यास हे रिकामे ठेवा.',
  f_sig1: 'स्वाक्षरी 1',
  f_sig2: 'स्वाक्षरी 2',
  f_sig_name: 'नाव',
  f_sig_role: 'पद',
  f_seal: 'शिक्का दाखवा',
  cert_presented: 'प्रमाणित करण्यात येते की',
  cert_date: 'दिनांक',
  name_placeholder: 'विद्यार्थ्याचे नाव',
  pos_1: 'प्रथम क्रमांक',
  pos_2: 'द्वितीय क्रमांक',
  pos_3: 'तृतीय क्रमांक',
  pos_word_1: 'प्रथम',
  pos_word_2: 'द्वितीय',
  pos_word_3: 'तृतीय',
  btn_print_all: 'सर्व प्रिंट करा',
  btn_print_one: 'हे प्रिंट करा',
  btn_png: 'PNG म्हणून सेव्ह करा',
  prev_of: '{n} पैकी {i}',
  keys_tip: 'टीप: एका प्रमाणपत्रावरून दुसऱ्यावर जाण्यासाठी बाणांच्या कळा वापरा, पूर्ण स्क्रीनमध्येही.',
  print_tip: 'प्रिंट विंडोमध्ये A4, Landscape आणि margins "None" निवडा, आणि "Background graphics" चालू करा.',
  png_wait: 'चित्र तयार होत आहे…',
  png_fail: 'या ब्राउझरला चित्र बनवता आले नाही. त्याऐवजी "प्रिंट करा" दाबून "Save as PDF" निवडा.',
  png_done: 'चित्र सेव्ह झाले',
  sample_names: 'आदित्य पाटील - प्रथम\nसायली जोशी - द्वितीय\nओंकार देशमुख - तृतीय\nप्राची कुलकर्णी\nरोहन शिंदे\nतन्वी पवार',
  sample_event: 'वार्षिक विज्ञान प्रदर्शन 2026',
  sample_school: 'जिल्हा परिषद माध्यमिक शाळा, पुणे',
  sample_sig1_name: 'सुनीता गायकवाड',
  sample_sig1_role: 'वर्गशिक्षिका',
  sample_sig2_name: 'डॉ. राजेश कुलकर्णी',
  sample_sig2_role: 'मुख्याध्यापक'
};

window.APP_STRINGS.gu = {
  app_title: 'પ્રમાણપત્ર મેકર',
  intro: 'આખા વર્ગ માટે સુંદર પ્રમાણપત્રો એક જ વારમાં બનાવો: નામ લખો, ડિઝાઇન પસંદ કરો, પછી બધાં પ્રિન્ટ કરો અથવા PNG તરીકે સેવ કરો.',
  help_title: 'કેવી રીતે વાપરવું · વર્ગ માટે વિચારો',
  help_1: 'નામ લખો અથવા પેસ્ટ કરો, દરેક લીટીમાં એક નામ. સ્થાન ઉમેરવા ડૅશ પછી લખો, જેમ કે "હેત પટેલ - પ્રથમ". પ્રથમ, દ્વિતીય અને તૃતીય (અથવા 1, 2, 3) સ્થાનને સોનેરી, ચાંદી કે કાંસ્ય રંગની મહોર પણ મળે છે.',
  help_2: 'પ્રમાણપત્રનો પ્રકાર અને ડિઝાઇન પસંદ કરો. શીર્ષક અને સંદેશ જાતે બદલાઈ જાય છે, છતાં તમે તેમાં ફેરફાર કરી શકો છો.',
  help_3: 'સંદેશમાં {name}, {event}, {position}, {school} અને {date} લખી શકો છો. દરેક વ્યક્તિ માટે તે જાતે ભરાઈ જાય છે.',
  help_4: '"બધાં પ્રિન્ટ કરો"થી દરેક પ્રમાણપત્ર અલગ A4 લૅન્ડસ્કેપ પાના પર છપાય છે. પ્રિન્ટ વિન્ડોમાં પૂરા રંગ માટે "Background graphics" ચાલુ કરો, અથવા "Save as PDF" પસંદ કરો.',
  help_5: 'વર્ગ માટે વિચાર: ક્વિઝ કે રમતોત્સવ પછી વિદ્યાર્થીઓ પાસે વિજેતાઓની યાદી લખાવો અને ડિઝાઇન પસંદ કરાવો, પછી ઇનામ વિતરણ વખતે દરેક પ્રમાણપત્ર સ્માર્ટબોર્ડ પર પૂર્ણ સ્ક્રીનમાં બતાવો.',
  help_6: 'ઍપ તમારી ભાષામાં છે, પણ પ્રમાણપત્ર અંગ્રેજીમાં જોઈએ છે? "પ્રમાણપત્રની ભાષા"માં અંગ્રેજી પસંદ કરો.',
  sec_design: 'ડિઝાઇન',
  sec_names: 'નામ',
  sec_text: 'પ્રમાણપત્રનું લખાણ',
  sec_school: 'શાળા, સહી અને તારીખ',
  sec_preview: 'પૂર્વાવલોકન',
  designs_aria: 'ડિઝાઇન પસંદ કરો',
  d_classic: 'સોનેરી ક્લાસિક',
  d_royal: 'શાહી વાદળી',
  d_tiranga: 'ત્રિરંગો',
  d_rangoli: 'રંગોળી',
  d_modern: 'આધુનિક',
  f_names: 'નામ, દરેક લીટીમાં એક',
  f_names_hint: 'ડૅશ પછી સ્થાન લખો: "હેત પટેલ - પ્રથમ". Excelમાંથી આખી કૉલમ પણ પેસ્ટ કરી શકો છો.',
  count_n: '{n} પ્રમાણપત્રો',
  count_1: '1 પ્રમાણપત્ર',
  too_many: 'ફક્ત પહેલાં {n} નામ લેવાશે.',
  no_names: 'પ્રમાણપત્ર બનાવવા ઓછામાં ઓછું એક નામ લખો.',
  f_type: 'પ્રમાણપત્રનો પ્રકાર',
  type_merit: 'ગુણવત્તા',
  type_participation: 'ભાગીદારી',
  type_appreciation: 'પ્રશંસા',
  type_excellence: 'શ્રેષ્ઠતા',
  type_completion: 'કોર્સ પૂર્ણ',
  title_merit: 'ગુણવત્તા પ્રમાણપત્ર',
  title_participation: 'ભાગીદારી પ્રમાણપત્ર',
  title_appreciation: 'પ્રશંસા પ્રમાણપત્ર',
  title_excellence: 'શ્રેષ્ઠતા પ્રમાણપત્ર',
  title_completion: 'પૂર્ણતા પ્રમાણપત્ર',
  f_title: 'પ્રમાણપત્ર પરનું શીર્ષક',
  f_event: 'કાર્યક્રમ અથવા કારણ',
  f_message: 'સંદેશ',
  f_message_hint: 'દરેક વ્યક્તિની વિગતો ભરવા {name}, {event}, {position}, {school} અથવા {date} લખો.',
  msg_default: 'મૂળ લખાણ વાપરો',
  msg_merit: '{event}માં ઉત્કૃષ્ટ દેખાવ બદલ. અમને આ મહેનત પર ગર્વ છે.',
  msg_merit_gen: 'ઉત્કૃષ્ટ દેખાવ અને સખત મહેનત બદલ. અમને ગર્વ છે!',
  msg_participation: '{event}માં ઉત્સાહથી ભાગ લેવા બદલ. શીખતા રહો, આગળ વધતા રહો!',
  msg_participation_gen: 'ઉત્સાહથી ભાગ લેવા બદલ. શીખતા રહો, આગળ વધતા રહો!',
  msg_appreciation: '{event}માં કીમતી યોગદાનની કદરરૂપે. તમારા સમર્પણ માટે હૃદયપૂર્વક આભાર.',
  msg_appreciation_gen: 'કીમતી યોગદાન અને સમર્પણની કદરરૂપે. હૃદયપૂર્વક આભાર!',
  msg_excellence: '{event}માં શ્રેષ્ઠતા બદલ. તમારી મહેનત અને પ્રતિભા સૌને પ્રેરણા આપે છે.',
  msg_excellence_gen: 'અભ્યાસ અને સારા વર્તનમાં શ્રેષ્ઠતા બદલ. તમારી મહેનત સૌને પ્રેરણા આપે છે.',
  msg_completion: '{event} સફળતાપૂર્વક પૂર્ણ કરવા બદલ.',
  msg_completion_gen: 'લગન અને નિષ્ઠાથી કોર્સ સફળતાપૂર્વક પૂર્ણ કરવા બદલ.',
  f_certlang: 'પ્રમાણપત્રની ભાષા',
  certlang_ui: 'ઍપની ભાષા જ',
  certlang_en: 'અંગ્રેજી',
  f_school: 'શાળાનું નામ',
  f_logo: 'શાળાનો લોગો (ઇચ્છો તો)',
  logo_add: 'લોગો ઉમેરો',
  logo_remove: 'લોગો દૂર કરો',
  logo_bad: 'આ ચિત્ર ખૂલી શક્યું નહીં. PNG અથવા JPG ફાઇલ અજમાવો.',
  logo_alt: 'શાળાનો લોગો',
  f_date: 'પ્રમાણપત્ર પરની તારીખ',
  f_date_hint: 'તારીખ છુપાવવી હોય તો આ ખાલી રાખો.',
  f_sig1: 'સહી 1',
  f_sig2: 'સહી 2',
  f_sig_name: 'નામ',
  f_sig_role: 'હોદ્દો',
  f_seal: 'મહોર બતાવો',
  cert_presented: 'આ પ્રમાણપત્ર ગૌરવપૂર્વક અર્પણ કરવામાં આવે છે',
  cert_date: 'તારીખ',
  name_placeholder: 'વિદ્યાર્થીનું નામ',
  pos_1: 'પ્રથમ સ્થાન',
  pos_2: 'દ્વિતીય સ્થાન',
  pos_3: 'તૃતીય સ્થાન',
  pos_word_1: 'પ્રથમ',
  pos_word_2: 'દ્વિતીય',
  pos_word_3: 'તૃતીય',
  btn_print_all: 'બધાં પ્રિન્ટ કરો',
  btn_print_one: 'આ પ્રિન્ટ કરો',
  btn_png: 'PNG તરીકે સેવ કરો',
  prev_of: '{n}માંથી {i}',
  keys_tip: 'ટીપ: એક પ્રમાણપત્રથી બીજા પર જવા તીરવાળી કી વાપરો, પૂર્ણ સ્ક્રીનમાં પણ.',
  print_tip: 'પ્રિન્ટ વિન્ડોમાં A4, Landscape અને margins "None" પસંદ કરો, અને "Background graphics" ચાલુ કરો.',
  png_wait: 'ચિત્ર બની રહ્યું છે…',
  png_fail: 'આ બ્રાઉઝર ચિત્ર બનાવી શક્યું નહીં. તેના બદલે "પ્રિન્ટ કરો" દબાવી "Save as PDF" પસંદ કરો.',
  png_done: 'ચિત્ર સેવ થયું',
  sample_names: 'હેત પટેલ - પ્રથમ\nજાનવી શાહ - દ્વિતીય\nદેવ દેસાઈ - તૃતીય\nકૃપા મહેતા\nઆર્યન જોશી\nનિધિ પંડ્યા',
  sample_event: 'વાર્ષિક વિજ્ઞાન પ્રદર્શન 2026',
  sample_school: 'સરકારી માધ્યમિક શાળા, અમદાવાદ',
  sample_sig1_name: 'સુનિતા પરમાર',
  sample_sig1_role: 'વર્ગ શિક્ષિકા',
  sample_sig2_name: 'ડૉ. રાજેશ મહેતા',
  sample_sig2_role: 'આચાર્ય'
};

window.APP_STRINGS.pa = {
  app_title: 'ਸਰਟੀਫਿਕੇਟ ਮੇਕਰ',
  intro: 'ਪੂਰੀ ਜਮਾਤ ਦੇ ਸੋਹਣੇ ਸਰਟੀਫਿਕੇਟ ਇੱਕੋ ਵਾਰ ਵਿੱਚ ਬਣਾਓ: ਨਾਂ ਲਿਖੋ, ਡਿਜ਼ਾਈਨ ਚੁਣੋ, ਫਿਰ ਸਾਰੇ ਪ੍ਰਿੰਟ ਕਰੋ ਜਾਂ PNG ਵਜੋਂ ਸੇਵ ਕਰੋ।',
  help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ · ਜਮਾਤ ਲਈ ਵਿਚਾਰ',
  help_1: 'ਨਾਂ ਲਿਖੋ ਜਾਂ ਪੇਸਟ ਕਰੋ, ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ ਨਾਂ। ਸਥਾਨ ਜੋੜਨ ਲਈ ਡੈਸ਼ ਤੋਂ ਬਾਅਦ ਲਿਖੋ, ਜਿਵੇਂ "ਹਰਜੋਤ ਸਿੰਘ - ਪਹਿਲਾ"। ਪਹਿਲੇ, ਦੂਜੇ ਅਤੇ ਤੀਜੇ ਸਥਾਨ (ਜਾਂ 1, 2, 3) ਨੂੰ ਸੁਨਹਿਰੀ, ਚਾਂਦੀ ਜਾਂ ਕਾਂਸੀ ਰੰਗ ਦੀ ਮੋਹਰ ਵੀ ਮਿਲਦੀ ਹੈ।',
  help_2: 'ਸਰਟੀਫਿਕੇਟ ਦੀ ਕਿਸਮ ਅਤੇ ਡਿਜ਼ਾਈਨ ਚੁਣੋ। ਸਿਰਲੇਖ ਅਤੇ ਸੁਨੇਹਾ ਆਪਣੇ-ਆਪ ਬਦਲ ਜਾਂਦੇ ਹਨ, ਫਿਰ ਵੀ ਤੁਸੀਂ ਇਹਨਾਂ ਨੂੰ ਬਦਲ ਸਕਦੇ ਹੋ।',
  help_3: 'ਸੁਨੇਹੇ ਵਿੱਚ {name}, {event}, {position}, {school} ਅਤੇ {date} ਲਿਖ ਸਕਦੇ ਹੋ। ਹਰ ਵਿਅਕਤੀ ਲਈ ਇਹ ਆਪਣੇ-ਆਪ ਭਰ ਜਾਂਦੇ ਹਨ।',
  help_4: '"ਸਾਰੇ ਪ੍ਰਿੰਟ ਕਰੋ" ਨਾਲ ਹਰ ਸਰਟੀਫਿਕੇਟ ਵੱਖਰੇ A4 ਲੈਂਡਸਕੇਪ ਪੰਨੇ ਉੱਤੇ ਛਪਦਾ ਹੈ। ਪ੍ਰਿੰਟ ਵਿੰਡੋ ਵਿੱਚ ਪੂਰੇ ਰੰਗਾਂ ਲਈ "Background graphics" ਚਾਲੂ ਕਰੋ, ਜਾਂ "Save as PDF" ਚੁਣੋ।',
  help_5: 'ਜਮਾਤ ਲਈ ਵਿਚਾਰ: ਕੁਇਜ਼ ਜਾਂ ਖੇਡ ਦਿਵਸ ਤੋਂ ਬਾਅਦ ਵਿਦਿਆਰਥੀਆਂ ਤੋਂ ਜੇਤੂਆਂ ਦੀ ਸੂਚੀ ਲਿਖਵਾਓ ਅਤੇ ਡਿਜ਼ਾਈਨ ਚੁਣਵਾਓ, ਫਿਰ ਇਨਾਮ ਵੰਡ ਸਮਾਰੋਹ ਵਿੱਚ ਹਰ ਸਰਟੀਫਿਕੇਟ ਸਮਾਰਟਬੋਰਡ ਉੱਤੇ ਪੂਰੀ ਸਕ੍ਰੀਨ ਵਿੱਚ ਦਿਖਾਓ।',
  help_6: 'ਐਪ ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਹੈ, ਪਰ ਸਰਟੀਫਿਕੇਟ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਚਾਹੀਦਾ ਹੈ? "ਸਰਟੀਫਿਕੇਟ ਦੀ ਭਾਸ਼ਾ" ਵਿੱਚ ਅੰਗਰੇਜ਼ੀ ਚੁਣੋ।',
  sec_design: 'ਡਿਜ਼ਾਈਨ',
  sec_names: 'ਨਾਂ',
  sec_text: 'ਸਰਟੀਫਿਕੇਟ ਦੀ ਲਿਖਤ',
  sec_school: 'ਸਕੂਲ, ਦਸਤਖ਼ਤ ਅਤੇ ਤਾਰੀਖ਼',
  sec_preview: 'ਝਲਕ',
  designs_aria: 'ਡਿਜ਼ਾਈਨ ਚੁਣੋ',
  d_classic: 'ਸੁਨਹਿਰੀ ਕਲਾਸਿਕ',
  d_royal: 'ਸ਼ਾਹੀ ਨੀਲਾ',
  d_tiranga: 'ਤਿਰੰਗਾ',
  d_rangoli: 'ਰੰਗੋਲੀ',
  d_modern: 'ਆਧੁਨਿਕ',
  f_names: 'ਨਾਂ, ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ',
  f_names_hint: 'ਡੈਸ਼ ਤੋਂ ਬਾਅਦ ਸਥਾਨ ਲਿਖੋ: "ਹਰਜੋਤ ਸਿੰਘ - ਪਹਿਲਾ"। Excel ਤੋਂ ਪੂਰਾ ਕਾਲਮ ਵੀ ਪੇਸਟ ਕਰ ਸਕਦੇ ਹੋ।',
  count_n: '{n} ਸਰਟੀਫਿਕੇਟ',
  count_1: '1 ਸਰਟੀਫਿਕੇਟ',
  too_many: 'ਸਿਰਫ਼ ਪਹਿਲੇ {n} ਨਾਂ ਲਏ ਜਾਣਗੇ।',
  no_names: 'ਸਰਟੀਫਿਕੇਟ ਬਣਾਉਣ ਲਈ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਨਾਂ ਲਿਖੋ।',
  f_type: 'ਸਰਟੀਫਿਕੇਟ ਦੀ ਕਿਸਮ',
  type_merit: 'ਯੋਗਤਾ',
  type_participation: 'ਭਾਗੀਦਾਰੀ',
  type_appreciation: 'ਪ੍ਰਸ਼ੰਸਾ',
  type_excellence: 'ਉੱਤਮਤਾ',
  type_completion: 'ਕੋਰਸ ਪੂਰਾ',
  title_merit: 'ਯੋਗਤਾ ਪ੍ਰਮਾਣ ਪੱਤਰ',
  title_participation: 'ਭਾਗੀਦਾਰੀ ਪ੍ਰਮਾਣ ਪੱਤਰ',
  title_appreciation: 'ਪ੍ਰਸ਼ੰਸਾ ਪ੍ਰਮਾਣ ਪੱਤਰ',
  title_excellence: 'ਉੱਤਮਤਾ ਪ੍ਰਮਾਣ ਪੱਤਰ',
  title_completion: 'ਸੰਪੂਰਨਤਾ ਪ੍ਰਮਾਣ ਪੱਤਰ',
  f_title: 'ਸਰਟੀਫਿਕੇਟ ਦਾ ਸਿਰਲੇਖ',
  f_event: 'ਸਮਾਗਮ ਜਾਂ ਕਾਰਨ',
  f_message: 'ਸੁਨੇਹਾ',
  f_message_hint: 'ਹਰ ਵਿਅਕਤੀ ਦੀ ਜਾਣਕਾਰੀ ਭਰਨ ਲਈ {name}, {event}, {position}, {school} ਜਾਂ {date} ਲਿਖੋ।',
  msg_default: 'ਮੂਲ ਲਿਖਤ ਵਰਤੋ',
  msg_merit: 'ਨੇ {event} ਵਿੱਚ ਸ਼ਾਨਦਾਰ ਪ੍ਰਦਰਸ਼ਨ ਕੀਤਾ ਹੈ। ਸਾਨੂੰ ਇਸ ਮਿਹਨਤ ਉੱਤੇ ਮਾਣ ਹੈ।',
  msg_merit_gen: 'ਨੇ ਸ਼ਾਨਦਾਰ ਪ੍ਰਦਰਸ਼ਨ ਅਤੇ ਸਖ਼ਤ ਮਿਹਨਤ ਕੀਤੀ ਹੈ। ਸਾਨੂੰ ਮਾਣ ਹੈ!',
  msg_participation: 'ਨੇ {event} ਵਿੱਚ ਉਤਸ਼ਾਹ ਨਾਲ ਹਿੱਸਾ ਲਿਆ। ਸਿੱਖਦੇ ਰਹੋ, ਅੱਗੇ ਵਧਦੇ ਰਹੋ!',
  msg_participation_gen: 'ਨੇ ਉਤਸ਼ਾਹ ਨਾਲ ਹਿੱਸਾ ਲਿਆ। ਸਿੱਖਦੇ ਰਹੋ, ਅੱਗੇ ਵਧਦੇ ਰਹੋ!',
  msg_appreciation: 'ਨੇ {event} ਵਿੱਚ ਕੀਮਤੀ ਯੋਗਦਾਨ ਪਾਇਆ ਹੈ। ਤੁਹਾਡੀ ਲਗਨ ਲਈ ਦਿਲੋਂ ਧੰਨਵਾਦ।',
  msg_appreciation_gen: 'ਨੇ ਕੀਮਤੀ ਯੋਗਦਾਨ ਪਾਇਆ ਅਤੇ ਲਗਨ ਦਿਖਾਈ ਹੈ। ਦਿਲੋਂ ਧੰਨਵਾਦ!',
  msg_excellence: 'ਨੇ {event} ਵਿੱਚ ਉੱਤਮਤਾ ਦਿਖਾਈ ਹੈ। ਤੁਹਾਡੀ ਮਿਹਨਤ ਅਤੇ ਪ੍ਰਤਿਭਾ ਸਭ ਨੂੰ ਪ੍ਰੇਰਿਤ ਕਰਦੀ ਹੈ।',
  msg_excellence_gen: 'ਨੇ ਪੜ੍ਹਾਈ ਅਤੇ ਚੰਗੇ ਵਿਹਾਰ ਵਿੱਚ ਉੱਤਮਤਾ ਦਿਖਾਈ ਹੈ। ਤੁਹਾਡੀ ਮਿਹਨਤ ਸਭ ਨੂੰ ਪ੍ਰੇਰਿਤ ਕਰਦੀ ਹੈ।',
  msg_completion: 'ਨੇ {event} ਸਫਲਤਾਪੂਰਵਕ ਪੂਰਾ ਕੀਤਾ ਹੈ।',
  msg_completion_gen: 'ਨੇ ਪੂਰੀ ਲਗਨ ਅਤੇ ਇਮਾਨਦਾਰੀ ਨਾਲ ਇਹ ਕੋਰਸ ਸਫਲਤਾਪੂਰਵਕ ਪੂਰਾ ਕੀਤਾ ਹੈ।',
  f_certlang: 'ਸਰਟੀਫਿਕੇਟ ਦੀ ਭਾਸ਼ਾ',
  certlang_ui: 'ਐਪ ਵਾਲੀ ਭਾਸ਼ਾ',
  certlang_en: 'ਅੰਗਰੇਜ਼ੀ',
  f_school: 'ਸਕੂਲ ਦਾ ਨਾਂ',
  f_logo: 'ਸਕੂਲ ਦਾ ਲੋਗੋ (ਜੇ ਚਾਹੋ)',
  logo_add: 'ਲੋਗੋ ਜੋੜੋ',
  logo_remove: 'ਲੋਗੋ ਹਟਾਓ',
  logo_bad: 'ਇਹ ਤਸਵੀਰ ਖੁੱਲ੍ਹ ਨਹੀਂ ਸਕੀ। PNG ਜਾਂ JPG ਫ਼ਾਈਲ ਵਰਤ ਕੇ ਦੇਖੋ।',
  logo_alt: 'ਸਕੂਲ ਦਾ ਲੋਗੋ',
  f_date: 'ਸਰਟੀਫਿਕੇਟ ਉੱਤੇ ਤਾਰੀਖ਼',
  f_date_hint: 'ਤਾਰੀਖ਼ ਲੁਕਾਉਣੀ ਹੋਵੇ ਤਾਂ ਇਸ ਨੂੰ ਖਾਲੀ ਛੱਡ ਦਿਓ।',
  f_sig1: 'ਦਸਤਖ਼ਤ 1',
  f_sig2: 'ਦਸਤਖ਼ਤ 2',
  f_sig_name: 'ਨਾਂ',
  f_sig_role: 'ਅਹੁਦਾ',
  f_seal: 'ਮੋਹਰ ਦਿਖਾਓ',
  cert_presented: 'ਪ੍ਰਮਾਣਿਤ ਕੀਤਾ ਜਾਂਦਾ ਹੈ ਕਿ',
  cert_date: 'ਮਿਤੀ',
  name_placeholder: 'ਵਿਦਿਆਰਥੀ ਦਾ ਨਾਂ',
  pos_1: 'ਪਹਿਲਾ ਸਥਾਨ',
  pos_2: 'ਦੂਜਾ ਸਥਾਨ',
  pos_3: 'ਤੀਜਾ ਸਥਾਨ',
  pos_word_1: 'ਪਹਿਲਾ',
  pos_word_2: 'ਦੂਜਾ',
  pos_word_3: 'ਤੀਜਾ',
  btn_print_all: 'ਸਾਰੇ ਪ੍ਰਿੰਟ ਕਰੋ',
  btn_print_one: 'ਇਹ ਪ੍ਰਿੰਟ ਕਰੋ',
  btn_png: 'PNG ਵਜੋਂ ਸੇਵ ਕਰੋ',
  prev_of: '{n} ਵਿੱਚੋਂ {i}',
  keys_tip: 'ਸੁਝਾਅ: ਇੱਕ ਸਰਟੀਫਿਕੇਟ ਤੋਂ ਦੂਜੇ ਉੱਤੇ ਜਾਣ ਲਈ ਤੀਰ ਵਾਲੀਆਂ ਕੁੰਜੀਆਂ ਵਰਤੋ, ਪੂਰੀ ਸਕ੍ਰੀਨ ਵਿੱਚ ਵੀ।',
  print_tip: 'ਪ੍ਰਿੰਟ ਵਿੰਡੋ ਵਿੱਚ A4, Landscape ਅਤੇ margins "None" ਚੁਣੋ, ਅਤੇ "Background graphics" ਚਾਲੂ ਕਰੋ।',
  png_wait: 'ਤਸਵੀਰ ਬਣ ਰਹੀ ਹੈ…',
  png_fail: 'ਇਹ ਬ੍ਰਾਊਜ਼ਰ ਤਸਵੀਰ ਨਹੀਂ ਬਣਾ ਸਕਿਆ। ਇਸ ਦੀ ਥਾਂ "ਪ੍ਰਿੰਟ ਕਰੋ" ਦਬਾ ਕੇ "Save as PDF" ਚੁਣੋ।',
  png_done: 'ਤਸਵੀਰ ਸੇਵ ਹੋ ਗਈ',
  sample_names: 'ਹਰਜੋਤ ਸਿੰਘ - ਪਹਿਲਾ\nਸਿਮਰਨ ਕੌਰ - ਦੂਜਾ\nਅਰਜਨ ਗਿੱਲ - ਤੀਜਾ\nਨਵਨੀਤ ਕੌਰ\nਗੁਰਵਿੰਦਰ ਸੰਧੂ\nਜਸਲੀਨ ਬਰਾੜ',
  sample_event: 'ਸਾਲਾਨਾ ਵਿਗਿਆਨ ਪ੍ਰਦਰਸ਼ਨੀ 2026',
  sample_school: 'ਸਰਕਾਰੀ ਸੀਨੀਅਰ ਸੈਕੰਡਰੀ ਸਕੂਲ, ਲੁਧਿਆਣਾ',
  sample_sig1_name: 'ਸੁਨੀਤਾ ਸ਼ਰਮਾ',
  sample_sig1_role: 'ਜਮਾਤ ਅਧਿਆਪਕਾ',
  sample_sig2_name: 'ਡਾ. ਰਾਜੇਸ਼ ਮਹਿਤਾ',
  sample_sig2_role: 'ਪ੍ਰਿੰਸੀਪਲ'
};

window.APP_STRINGS.or = {
  app_title: 'ପ୍ରମାଣପତ୍ର ମେକର',
  intro: 'ପୂରା ଶ୍ରେଣୀର ସୁନ୍ଦର ପ୍ରମାଣପତ୍ର ଥରକରେ ତିଆରି କରନ୍ତୁ: ନାମ ଲେଖନ୍ତୁ, ଡିଜାଇନ୍ ବାଛନ୍ତୁ, ତାପରେ ସବୁ ପ୍ରିଣ୍ଟ କରନ୍ତୁ ବା PNG ଭାବେ ସେଭ୍ କରନ୍ତୁ।',
  help_title: 'କିପରି ବ୍ୟବହାର କରିବେ · ଶ୍ରେଣୀ ପାଇଁ ଚିନ୍ତାଧାରା',
  help_1: 'ନାମ ଲେଖନ୍ତୁ ବା ପେଷ୍ଟ କରନ୍ତୁ, ପ୍ରତି ଧାଡ଼ିରେ ଗୋଟିଏ ନାମ। ସ୍ଥାନ ଯୋଡ଼ିବାକୁ ଡ୍ୟାସ୍ ପରେ ଲେଖନ୍ତୁ, ଯେପରି "ଅଭିଷେକ ମହାନ୍ତି - ପ୍ରଥମ"। ପ୍ରଥମ, ଦ୍ୱିତୀୟ ଓ ତୃତୀୟ (ବା 1, 2, 3) ସ୍ଥାନକୁ ସୁନେଲି, ରୁପେଲି ବା କାଂସ୍ୟ ରଙ୍ଗର ମୋହର ମଧ୍ୟ ମିଳେ।',
  help_2: 'ପ୍ରମାଣପତ୍ରର ପ୍ରକାର ଓ ଡିଜାଇନ୍ ବାଛନ୍ତୁ। ଶିରୋନାମା ଓ ବାର୍ତ୍ତା ନିଜେ ବଦଳିଯାଏ, ତଥାପି ଆପଣ ସେଗୁଡ଼ିକୁ ବଦଳାଇ ପାରିବେ।',
  help_3: 'ବାର୍ତ୍ତାରେ {name}, {event}, {position}, {school} ଓ {date} ଲେଖିପାରିବେ। ପ୍ରତ୍ୟେକ ବ୍ୟକ୍ତିଙ୍କ ପାଇଁ ଏଗୁଡ଼ିକ ନିଜେ ଭରିହୋଇଯାଏ।',
  help_4: '"ସବୁ ପ୍ରିଣ୍ଟ କରନ୍ତୁ" ଦ୍ୱାରା ପ୍ରତ୍ୟେକ ପ୍ରମାଣପତ୍ର ଅଲଗା A4 ଲ୍ୟାଣ୍ଡସ୍କେପ୍ ପୃଷ୍ଠାରେ ଛପାହୁଏ। ପ୍ରିଣ୍ଟ ୱିଣ୍ଡୋରେ ପୂରା ରଙ୍ଗ ପାଇଁ "Background graphics" ଚାଲୁ କରନ୍ତୁ, କିମ୍ବା "Save as PDF" ବାଛନ୍ତୁ।',
  help_5: 'ଶ୍ରେଣୀ ପାଇଁ ଚିନ୍ତାଧାରା: କୁଇଜ୍ ବା କ୍ରୀଡ଼ା ଦିବସ ପରେ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ଦ୍ୱାରା ବିଜେତାଙ୍କ ତାଲିକା ଲେଖାନ୍ତୁ ଓ ଡିଜାଇନ୍ ବଛାନ୍ତୁ, ତାପରେ ପୁରସ୍କାର ବିତରଣ ସମୟରେ ପ୍ରତ୍ୟେକ ପ୍ରମାଣପତ୍ର ସ୍ମାର୍ଟବୋର୍ଡରେ ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍‌ରେ ଦେଖାନ୍ତୁ।',
  help_6: 'ଆପ୍ ଆପଣଙ୍କ ଭାଷାରେ ଅଛି, କିନ୍ତୁ ପ୍ରମାଣପତ୍ର ଇଂରାଜୀରେ ଦରକାର? "ପ୍ରମାଣପତ୍ରର ଭାଷା"ରେ ଇଂରାଜୀ ବାଛନ୍ତୁ।',
  sec_design: 'ଡିଜାଇନ୍',
  sec_names: 'ନାମ',
  sec_text: 'ପ୍ରମାଣପତ୍ରର ଲେଖା',
  sec_school: 'ବିଦ୍ୟାଳୟ, ଦସ୍ତଖତ ଓ ତାରିଖ',
  sec_preview: 'ପୂର୍ବାବଲୋକନ',
  designs_aria: 'ଡିଜାଇନ୍ ବାଛନ୍ତୁ',
  d_classic: 'ସୁନେଲି କ୍ଲାସିକ୍',
  d_royal: 'ରାଜକୀୟ ନୀଳ',
  d_tiranga: 'ତ୍ରିରଙ୍ଗା',
  d_rangoli: 'ମୁରୁଜ',
  d_modern: 'ଆଧୁନିକ',
  f_names: 'ନାମ, ପ୍ରତି ଧାଡ଼ିରେ ଗୋଟିଏ',
  f_names_hint: 'ଡ୍ୟାସ୍ ପରେ ସ୍ଥାନ ଲେଖନ୍ତୁ: "ଅଭିଷେକ ମହାନ୍ତି - ପ୍ରଥମ"। Excel ରୁ ପୂରା ସ୍ତମ୍ଭ ମଧ୍ୟ ପେଷ୍ଟ କରିପାରିବେ।',
  count_n: '{n}ଟି ପ୍ରମାଣପତ୍ର',
  count_1: '1ଟି ପ୍ରମାଣପତ୍ର',
  too_many: 'କେବଳ ପ୍ରଥମ {n}ଟି ନାମ ନିଆଯିବ।',
  no_names: 'ପ୍ରମାଣପତ୍ର ତିଆରି ପାଇଁ ଅତି କମରେ ଗୋଟିଏ ନାମ ଲେଖନ୍ତୁ।',
  f_type: 'ପ୍ରମାଣପତ୍ରର ପ୍ରକାର',
  type_merit: 'ମେଧା',
  type_participation: 'ଅଂଶଗ୍ରହଣ',
  type_appreciation: 'ପ୍ରଶଂସା',
  type_excellence: 'ଉତ୍କର୍ଷ',
  type_completion: 'ପାଠ୍ୟକ୍ରମ ସମାପ୍ତି',
  title_merit: 'ମେଧା ପ୍ରମାଣପତ୍ର',
  title_participation: 'ଅଂଶଗ୍ରହଣ ପ୍ରମାଣପତ୍ର',
  title_appreciation: 'ପ୍ରଶଂସା ପତ୍ର',
  title_excellence: 'ଉତ୍କର୍ଷ ପ୍ରମାଣପତ୍ର',
  title_completion: 'ସମାପ୍ତି ପ୍ରମାଣପତ୍ର',
  f_title: 'ପ୍ରମାଣପତ୍ରର ଶିରୋନାମା',
  f_event: 'କାର୍ଯ୍ୟକ୍ରମ ବା କାରଣ',
  f_message: 'ବାର୍ତ୍ତା',
  f_message_hint: 'ପ୍ରତ୍ୟେକଙ୍କ ବିବରଣୀ ଭରିବାକୁ {name}, {event}, {position}, {school} ବା {date} ଲେଖନ୍ତୁ।',
  msg_default: 'ମୂଳ ଲେଖା ବ୍ୟବହାର କରନ୍ତୁ',
  msg_merit: '{event}ରେ ଉତ୍କୃଷ୍ଟ ପ୍ରଦର୍ଶନ କରିଛନ୍ତି। ଏହି ପରିଶ୍ରମ ପାଇଁ ଆମେ ଗର୍ବିତ।',
  msg_merit_gen: 'ଉତ୍କୃଷ୍ଟ ପ୍ରଦର୍ଶନ ଓ କଠିନ ପରିଶ୍ରମ କରିଛନ୍ତି। ଆମେ ଗର୍ବିତ!',
  msg_participation: '{event}ରେ ଉତ୍ସାହର ସହ ଭାଗ ନେଇଛନ୍ତି। ଶିଖୁଥାଆନ୍ତୁ, ଆଗକୁ ବଢ଼ୁଥାଆନ୍ତୁ!',
  msg_participation_gen: 'ଉତ୍ସାହର ସହ ଭାଗ ନେଇଛନ୍ତି। ଶିଖୁଥାଆନ୍ତୁ, ଆଗକୁ ବଢ଼ୁଥାଆନ୍ତୁ!',
  msg_appreciation: '{event}ରେ ମୂଲ୍ୟବାନ ଯୋଗଦାନ ଦେଇଛନ୍ତି। ଏହି ନିଷ୍ଠା ପାଇଁ ହୃଦୟରୁ ଧନ୍ୟବାଦ।',
  msg_appreciation_gen: 'ମୂଲ୍ୟବାନ ଯୋଗଦାନ ଓ ନିଷ୍ଠା ଦେଖାଇଛନ୍ତି। ହୃଦୟରୁ ଧନ୍ୟବାଦ!',
  msg_excellence: '{event}ରେ ଉତ୍କର୍ଷ ଦେଖାଇଛନ୍ତି। ଏହି ପରିଶ୍ରମ ଓ ପ୍ରତିଭା ସମସ୍ତଙ୍କୁ ପ୍ରେରଣା ଦିଏ।',
  msg_excellence_gen: 'ପାଠପଢ଼ା ଓ ଭଲ ଆଚରଣରେ ଉତ୍କର୍ଷ ଦେଖାଇଛନ୍ତି। ଏହି ପରିଶ୍ରମ ସମସ୍ତଙ୍କୁ ପ୍ରେରଣା ଦିଏ।',
  msg_completion: 'ସଫଳତାର ସହ {event} ସମ୍ପୂର୍ଣ୍ଣ କରିଛନ୍ତି।',
  msg_completion_gen: 'ନିଷ୍ଠା ଓ ଆନ୍ତରିକତାର ସହ ପାଠ୍ୟକ୍ରମଟି ସଫଳତାର ସହ ସମ୍ପୂର୍ଣ୍ଣ କରିଛନ୍ତି।',
  f_certlang: 'ପ୍ରମାଣପତ୍ରର ଭାଷା',
  certlang_ui: 'ଆପ୍‌ର ଭାଷା',
  certlang_en: 'ଇଂରାଜୀ',
  f_school: 'ବିଦ୍ୟାଳୟର ନାମ',
  f_logo: 'ବିଦ୍ୟାଳୟର ଲୋଗୋ (ଇଚ୍ଛା ହେଲେ)',
  logo_add: 'ଲୋଗୋ ଯୋଡ଼ନ୍ତୁ',
  logo_remove: 'ଲୋଗୋ ହଟାନ୍ତୁ',
  logo_bad: 'ଏହି ଛବି ଖୋଲିହେଲା ନାହିଁ। PNG ବା JPG ଫାଇଲ୍ ଚେଷ୍ଟା କରନ୍ତୁ।',
  logo_alt: 'ବିଦ୍ୟାଳୟର ଲୋଗୋ',
  f_date: 'ପ୍ରମାଣପତ୍ରରେ ତାରିଖ',
  f_date_hint: 'ତାରିଖ ଲୁଚାଇବାକୁ ଚାହିଁଲେ ଏହାକୁ ଖାଲି ରଖନ୍ତୁ।',
  f_sig1: 'ଦସ୍ତଖତ 1',
  f_sig2: 'ଦସ୍ତଖତ 2',
  f_sig_name: 'ନାମ',
  f_sig_role: 'ପଦବୀ',
  f_seal: 'ମୋହର ଦେଖାନ୍ତୁ',
  cert_presented: 'ଏତଦ୍ୱାରା ପ୍ରମାଣିତ କରାଯାଉଛି ଯେ',
  cert_date: 'ତାରିଖ',
  name_placeholder: 'ଛାତ୍ର/ଛାତ୍ରୀଙ୍କ ନାମ',
  pos_1: 'ପ୍ରଥମ ସ୍ଥାନ',
  pos_2: 'ଦ୍ୱିତୀୟ ସ୍ଥାନ',
  pos_3: 'ତୃତୀୟ ସ୍ଥାନ',
  pos_word_1: 'ପ୍ରଥମ',
  pos_word_2: 'ଦ୍ୱିତୀୟ',
  pos_word_3: 'ତୃତୀୟ',
  btn_print_all: 'ସବୁ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
  btn_print_one: 'ଏହାକୁ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
  btn_png: 'PNG ଭାବେ ସେଭ୍ କରନ୍ତୁ',
  prev_of: '{n}ରୁ {i}',
  keys_tip: 'ପରାମର୍ଶ: ଗୋଟିଏ ପ୍ରମାଣପତ୍ରରୁ ଅନ୍ୟକୁ ଯିବାକୁ ତୀର ଚାବି ବ୍ୟବହାର କରନ୍ତୁ, ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍‌ରେ ମଧ୍ୟ।',
  print_tip: 'ପ୍ରିଣ୍ଟ ୱିଣ୍ଡୋରେ A4, Landscape ଓ margins "None" ବାଛନ୍ତୁ, ଏବଂ "Background graphics" ଚାଲୁ କରନ୍ତୁ।',
  png_wait: 'ଛବି ତିଆରି ହେଉଛି…',
  png_fail: 'ଏହି ବ୍ରାଉଜର୍ ଛବି ତିଆରି କରିପାରିଲା ନାହିଁ। ଏହା ବଦଳରେ "ପ୍ରିଣ୍ଟ କରନ୍ତୁ" ଦବାଇ "Save as PDF" ବାଛନ୍ତୁ।',
  png_done: 'ଛବି ସେଭ୍ ହେଲା',
  sample_names: 'ଅଭିଷେକ ମହାନ୍ତି - ପ୍ରଥମ\nସୁସ୍ମିତା ପଣ୍ଡା - ଦ୍ୱିତୀୟ\nଶୁଭମ ଦାଶ - ତୃତୀୟ\nପ୍ରିୟଙ୍କା ସାହୁ\nଆଦିତ୍ୟ ମିଶ୍ର\nଲିପ୍ସା ବେହେରା',
  sample_event: 'ବାର୍ଷିକ ବିଜ୍ଞାନ ପ୍ରଦର୍ଶନୀ 2026',
  sample_school: 'ସରକାରୀ ଉଚ୍ଚ ବିଦ୍ୟାଳୟ, କଟକ',
  sample_sig1_name: 'ସୁନୀତା ମହାପାତ୍ର',
  sample_sig1_role: 'ଶ୍ରେଣୀ ଶିକ୍ଷୟିତ୍ରୀ',
  sample_sig2_name: 'ଡ. ରାଜେଶ ମିଶ୍ର',
  sample_sig2_role: 'ପ୍ରଧାନ ଶିକ୍ଷକ'
};

window.APP_STRINGS.ta = {
  app_title: 'சான்றிதழ் தயாரிப்பான்',
  intro: 'முழு வகுப்புக்குமான அழகான சான்றிதழ்களை ஒரே நேரத்தில் உருவாக்குங்கள்: பெயர்களை எழுதுங்கள், வடிவமைப்பைத் தேர்ந்தெடுங்கள், பிறகு அனைத்தையும் அச்சிடுங்கள் அல்லது PNG ஆகச் சேமியுங்கள்.',
  help_title: 'பயன்படுத்துவது எப்படி · வகுப்பறைக்கான யோசனைகள்',
  help_1: 'பெயர்களை எழுதுங்கள் அல்லது ஒட்டுங்கள், ஒரு வரிக்கு ஒரு பெயர். இடத்தைச் சேர்க்க கோட்டுக்குப் (-) பிறகு எழுதுங்கள், எ.கா. "அருண் குமார் - முதல்". முதல், இரண்டாம், மூன்றாம் (அல்லது 1, 2, 3) இடங்களுக்குத் தங்கம், வெள்ளி, வெண்கல நிற முத்திரையும் கிடைக்கும்.',
  help_2: 'சான்றிதழ் வகையையும் வடிவமைப்பையும் தேர்ந்தெடுங்கள். தலைப்பும் செய்தியும் தானாக மாறும்; அவற்றை நீங்கள் திருத்தவும் செய்யலாம்.',
  help_3: 'செய்தியில் {name}, {event}, {position}, {school}, {date} ஆகியவற்றைப் பயன்படுத்தலாம். ஒவ்வொருவருக்கும் இவை தானாக நிரப்பப்படும்.',
  help_4: '"அனைத்தையும் அச்சிடு" அழுத்தினால் ஒவ்வொரு சான்றிதழும் தனி A4 கிடைமட்டப் பக்கத்தில் அச்சாகும். அச்சு சாளரத்தில் முழு வண்ணத்திற்கு "Background graphics" ஐ இயக்குங்கள், அல்லது "Save as PDF" ஐத் தேர்ந்தெடுங்கள்.',
  help_5: 'வகுப்பறை யோசனை: வினாடி வினா அல்லது விளையாட்டு நாளுக்குப் பிறகு வெற்றியாளர் பட்டியலை மாணவர்களே எழுதி வடிவமைப்பைத் தேர்ந்தெடுக்கட்டும்; பரிசளிப்பு விழாவில் ஒவ்வொரு சான்றிதழையும் ஸ்மார்ட்போர்டில் முழுத் திரையில் காட்டுங்கள்.',
  help_6: 'செயலி உங்கள் மொழியில் உள்ளது, ஆனால் சான்றிதழ் ஆங்கிலத்தில் வேண்டுமா? "சான்றிதழ் மொழி" என்பதில் ஆங்கிலத்தைத் தேர்ந்தெடுங்கள்.',
  sec_design: 'வடிவமைப்பு',
  sec_names: 'பெயர்கள்',
  sec_text: 'சான்றிதழ் வாசகம்',
  sec_school: 'பள்ளி, கையொப்பங்கள், தேதி',
  sec_preview: 'முன்னோட்டம்',
  designs_aria: 'வடிவமைப்பைத் தேர்ந்தெடுங்கள்',
  d_classic: 'தங்க கிளாசிக்',
  d_royal: 'அரச நீலம்',
  d_tiranga: 'மூவர்ணம்',
  d_rangoli: 'கோலம்',
  d_modern: 'நவீனம்',
  f_names: 'பெயர்கள், ஒரு வரிக்கு ஒன்று',
  f_names_hint: 'கோட்டுக்குப் பிறகு இடத்தை எழுதுங்கள்: "அருண் குமார் - முதல்". Excel-இலிருந்து முழு நெடுவரிசையையும் ஒட்டலாம்.',
  count_n: '{n} சான்றிதழ்கள்',
  count_1: '1 சான்றிதழ்',
  too_many: 'முதல் {n} பெயர்கள் மட்டுமே எடுத்துக்கொள்ளப்படும்.',
  no_names: 'சான்றிதழ் உருவாக்கக் குறைந்தது ஒரு பெயரையாவது எழுதுங்கள்.',
  f_type: 'சான்றிதழ் வகை',
  type_merit: 'தகுதி',
  type_participation: 'பங்கேற்பு',
  type_appreciation: 'பாராட்டு',
  type_excellence: 'சிறப்பு',
  type_completion: 'பாடநெறி நிறைவு',
  title_merit: 'தகுதிச் சான்றிதழ்',
  title_participation: 'பங்கேற்புச் சான்றிதழ்',
  title_appreciation: 'பாராட்டுச் சான்றிதழ்',
  title_excellence: 'சிறப்புச் சான்றிதழ்',
  title_completion: 'நிறைவுச் சான்றிதழ்',
  f_title: 'சான்றிதழின் தலைப்பு',
  f_event: 'நிகழ்ச்சி அல்லது காரணம்',
  f_message: 'செய்தி',
  f_message_hint: 'ஒவ்வொருவரின் விவரங்களையும் நிரப்ப {name}, {event}, {position}, {school} அல்லது {date} எழுதுங்கள்.',
  msg_default: 'இயல்பு வாசகத்தைப் பயன்படுத்து',
  msg_merit: 'அவர்கள் {event}-இல் சிறப்பாகச் செயல்பட்டுள்ளார். அவரது உழைப்பைக் கண்டு பெருமை கொள்கிறோம்.',
  msg_merit_gen: 'அவர்கள் சிறப்பான செயல்பாட்டையும் கடின உழைப்பையும் வெளிப்படுத்தியுள்ளார். பெருமை கொள்கிறோம்!',
  msg_participation: 'அவர்கள் {event}-இல் ஆர்வத்துடன் பங்கேற்றார். தொடர்ந்து கற்று, தொடர்ந்து ஒளிருங்கள்!',
  msg_participation_gen: 'அவர்கள் ஆர்வத்துடன் பங்கேற்றார். தொடர்ந்து கற்று, தொடர்ந்து ஒளிருங்கள்!',
  msg_appreciation: 'அவர்கள் {event}-இல் மதிப்புமிக்க பங்களிப்பு செய்துள்ளார். அவரது அர்ப்பணிப்புக்கு மனமார்ந்த நன்றி.',
  msg_appreciation_gen: 'அவர்கள் மதிப்புமிக்க பங்களிப்பும் அர்ப்பணிப்பும் காட்டியுள்ளார். மனமார்ந்த நன்றி!',
  msg_excellence: 'அவர்கள் {event}-இல் சிறந்து விளங்கியுள்ளார். அவரது உழைப்பும் திறமையும் அனைவருக்கும் ஊக்கம் தருகின்றன.',
  msg_excellence_gen: 'அவர்கள் படிப்பிலும் நல்லொழுக்கத்திலும் சிறந்து விளங்கியுள்ளார். அவரது உழைப்பு அனைவருக்கும் ஊக்கம் தருகிறது.',
  msg_completion: 'அவர்கள் {event}-ஐ வெற்றிகரமாக நிறைவு செய்துள்ளார்.',
  msg_completion_gen: 'அவர்கள் இப்பாடநெறியை ஈடுபாட்டுடனும் நேர்மையுடனும் வெற்றிகரமாக நிறைவு செய்துள்ளார்.',
  f_certlang: 'சான்றிதழ் மொழி',
  certlang_ui: 'செயலியின் மொழியே',
  certlang_en: 'ஆங்கிலம்',
  f_school: 'பள்ளியின் பெயர்',
  f_logo: 'பள்ளி லோகோ (விரும்பினால்)',
  logo_add: 'லோகோ சேர்',
  logo_remove: 'லோகோவை நீக்கு',
  logo_bad: 'இந்தப் படத்தைத் திறக்க முடியவில்லை. PNG அல்லது JPG கோப்பை முயற்சிக்கவும்.',
  logo_alt: 'பள்ளி லோகோ',
  f_date: 'சான்றிதழில் தேதி',
  f_date_hint: 'தேதியை மறைக்க இதைக் காலியாக விடுங்கள்.',
  f_sig1: 'கையொப்பம் 1',
  f_sig2: 'கையொப்பம் 2',
  f_sig_name: 'பெயர்',
  f_sig_role: 'பதவி',
  f_seal: 'முத்திரையைக் காட்டு',
  cert_presented: 'இதன் மூலம் சான்றளிக்கப்படுவது யாதெனில்',
  cert_date: 'தேதி',
  name_placeholder: 'மாணவர் பெயர்',
  pos_1: 'முதல் இடம்',
  pos_2: 'இரண்டாம் இடம்',
  pos_3: 'மூன்றாம் இடம்',
  pos_word_1: 'முதல்',
  pos_word_2: 'இரண்டாம்',
  pos_word_3: 'மூன்றாம்',
  btn_print_all: 'அனைத்தையும் அச்சிடு',
  btn_print_one: 'இதை அச்சிடு',
  btn_png: 'PNG ஆகச் சேமி',
  prev_of: '{n}-இல் {i}',
  keys_tip: 'குறிப்பு: ஒரு சான்றிதழிலிருந்து அடுத்ததற்குச் செல்ல அம்புக்குறி விசைகளைப் பயன்படுத்துங்கள், முழுத் திரையிலும்.',
  print_tip: 'அச்சு சாளரத்தில் A4, Landscape, margins "None" ஆகியவற்றைத் தேர்ந்தெடுத்து, "Background graphics" ஐ இயக்குங்கள்.',
  png_wait: 'படம் உருவாகிறது…',
  png_fail: 'இந்த உலாவியால் படத்தை உருவாக்க முடியவில்லை. அதற்குப் பதிலாக "அச்சிடு" அழுத்தி "Save as PDF" ஐத் தேர்ந்தெடுங்கள்.',
  png_done: 'படம் சேமிக்கப்பட்டது',
  sample_names: 'அருண் குமார் - முதல்\nகாவ்யா சுப்பிரமணியன் - இரண்டாம்\nகார்த்திக் ராஜா - மூன்றாம்\nதிவ்யா முருகன்\nசூர்யா பாலு\nமீனா சேகர்',
  sample_event: 'ஆண்டு அறிவியல் கண்காட்சி 2026',
  sample_school: 'அரசு மேல்நிலைப் பள்ளி, மதுரை',
  sample_sig1_name: 'சுனிதா ராமன்',
  sample_sig1_role: 'வகுப்பு ஆசிரியர்',
  sample_sig2_name: 'முனைவர் ராஜேஷ் கிருஷ்ணன்',
  sample_sig2_role: 'தலைமை ஆசிரியர்'
};

window.APP_STRINGS.te = {
  app_title: 'సర్టిఫికెట్ మేకర్',
  intro: 'తరగతి మొత్తానికి అందమైన సర్టిఫికెట్లు ఒకేసారి తయారు చేయండి: పేర్లు రాయండి, డిజైన్ ఎంచుకోండి, తర్వాత అన్నీ ప్రింట్ చేయండి లేదా PNGగా సేవ్ చేయండి.',
  help_title: 'ఎలా ఉపయోగించాలి · తరగతి కోసం ఆలోచనలు',
  help_1: 'పేర్లు రాయండి లేదా పేస్ట్ చేయండి, ఒక్కో లైన్‌లో ఒక పేరు. స్థానం జోడించాలంటే డ్యాష్ తర్వాత రాయండి, ఉదా. "సాయి కృష్ణ - ప్రథమ". ప్రథమ, ద్వితీయ, తృతీయ (లేదా 1, 2, 3) స్థానాలకు బంగారు, వెండి, కంచు రంగు ముద్ర కూడా వస్తుంది.',
  help_2: 'సర్టిఫికెట్ రకం, డిజైన్ ఎంచుకోండి. శీర్షిక, సందేశం వాటంతట అవే మారతాయి; అయినా మీరు వాటిని మార్చుకోవచ్చు.',
  help_3: 'సందేశంలో {name}, {event}, {position}, {school}, {date} వాడవచ్చు. ప్రతి ఒక్కరికీ ఇవి వాటంతట అవే నిండుతాయి.',
  help_4: '"అన్నీ ప్రింట్ చేయండి" నొక్కితే ప్రతి సర్టిఫికెట్ వేరే A4 ల్యాండ్‌స్కేప్ పేజీపై ప్రింట్ అవుతుంది. ప్రింట్ విండోలో పూర్తి రంగుల కోసం "Background graphics" ఆన్ చేయండి, లేదా "Save as PDF" ఎంచుకోండి.',
  help_5: 'తరగతి ఆలోచన: క్విజ్ లేదా క్రీడా దినోత్సవం తర్వాత విజేతల జాబితాను విద్యార్థులే రాసి డిజైన్ ఎంచుకోనివ్వండి, తర్వాత బహుమతి ప్రదానోత్సవంలో ప్రతి సర్టిఫికెట్‌ను స్మార్ట్‌బోర్డుపై పూర్తి స్క్రీన్‌లో చూపించండి.',
  help_6: 'యాప్ మీ భాషలో ఉంది, కానీ సర్టిఫికెట్ ఇంగ్లీషులో కావాలా? "సర్టిఫికెట్ భాష"లో ఇంగ్లీష్ ఎంచుకోండి.',
  sec_design: 'డిజైన్',
  sec_names: 'పేర్లు',
  sec_text: 'సర్టిఫికెట్ వాక్యాలు',
  sec_school: 'పాఠశాల, సంతకాలు, తేదీ',
  sec_preview: 'ప్రివ్యూ',
  designs_aria: 'డిజైన్ ఎంచుకోండి',
  d_classic: 'బంగారు క్లాసిక్',
  d_royal: 'రాజ నీలం',
  d_tiranga: 'త్రివర్ణం',
  d_rangoli: 'ముగ్గు',
  d_modern: 'ఆధునికం',
  f_names: 'పేర్లు, ఒక్కో లైన్‌లో ఒకటి',
  f_names_hint: 'డ్యాష్ తర్వాత స్థానం రాయండి: "సాయి కృష్ణ - ప్రథమ". Excel నుండి పూర్తి కాలమ్‌ను కూడా పేస్ట్ చేయవచ్చు.',
  count_n: '{n} సర్టిఫికెట్లు',
  count_1: '1 సర్టిఫికెట్',
  too_many: 'మొదటి {n} పేర్లు మాత్రమే తీసుకుంటాం.',
  no_names: 'సర్టిఫికెట్లు తయారు చేయడానికి కనీసం ఒక పేరు రాయండి.',
  f_type: 'సర్టిఫికెట్ రకం',
  type_merit: 'ప్రతిభ',
  type_participation: 'భాగస్వామ్యం',
  type_appreciation: 'ప్రశంస',
  type_excellence: 'శ్రేష్ఠత',
  type_completion: 'కోర్సు పూర్తి',
  title_merit: 'ప్రతిభా ధ్రువపత్రం',
  title_participation: 'భాగస్వామ్య ధ్రువపత్రం',
  title_appreciation: 'ప్రశంసా పత్రం',
  title_excellence: 'శ్రేష్ఠతా ధ్రువపత్రం',
  title_completion: 'కోర్సు పూర్తి ధ్రువపత్రం',
  f_title: 'సర్టిఫికెట్ శీర్షిక',
  f_event: 'కార్యక్రమం లేదా కారణం',
  f_message: 'సందేశం',
  f_message_hint: 'ప్రతి ఒక్కరి వివరాలు నింపడానికి {name}, {event}, {position}, {school} లేదా {date} రాయండి.',
  msg_default: 'అసలు వాక్యం వాడండి',
  msg_merit: '{event}లో అద్భుతమైన ప్రతిభ కనబరిచారు. వారి కృషికి మేము గర్విస్తున్నాము.',
  msg_merit_gen: 'అద్భుతమైన ప్రతిభ, కఠోర శ్రమ కనబరిచారు. మేము గర్విస్తున్నాము!',
  msg_participation: '{event}లో ఉత్సాహంగా పాల్గొన్నారు. నేర్చుకుంటూ ఉండండి, ముందుకు సాగండి!',
  msg_participation_gen: 'ఉత్సాహంగా పాల్గొన్నారు. నేర్చుకుంటూ ఉండండి, ముందుకు సాగండి!',
  msg_appreciation: '{event}లో విలువైన సేవలు అందించారు. వారి అంకితభావానికి హృదయపూర్వక ధన్యవాదాలు.',
  msg_appreciation_gen: 'విలువైన సేవలు, అంకితభావం చూపారు. హృదయపూర్వక ధన్యవాదాలు!',
  msg_excellence: '{event}లో శ్రేష్ఠత కనబరిచారు. వారి కృషి, ప్రతిభ అందరికీ స్ఫూర్తినిస్తాయి.',
  msg_excellence_gen: 'చదువులోనూ మంచి నడవడికలోనూ శ్రేష్ఠత కనబరిచారు. వారి కృషి అందరికీ స్ఫూర్తినిస్తుంది.',
  msg_completion: '{event}ను విజయవంతంగా పూర్తి చేశారు.',
  msg_completion_gen: 'ఈ కోర్సును శ్రద్ధగా, నిజాయితీగా విజయవంతంగా పూర్తి చేశారు.',
  f_certlang: 'సర్టిఫికెట్ భాష',
  certlang_ui: 'యాప్ భాషే',
  certlang_en: 'ఇంగ్లీష్',
  f_school: 'పాఠశాల పేరు',
  f_logo: 'పాఠశాల లోగో (కావాలంటే)',
  logo_add: 'లోగో జోడించండి',
  logo_remove: 'లోగో తీసివేయండి',
  logo_bad: 'ఈ చిత్రం తెరవలేకపోయాం. PNG లేదా JPG ఫైల్ ప్రయత్నించండి.',
  logo_alt: 'పాఠశాల లోగో',
  f_date: 'సర్టిఫికెట్‌పై తేదీ',
  f_date_hint: 'తేదీ దాచాలంటే దీన్ని ఖాళీగా ఉంచండి.',
  f_sig1: 'సంతకం 1',
  f_sig2: 'సంతకం 2',
  f_sig_name: 'పేరు',
  f_sig_role: 'హోదా',
  f_seal: 'ముద్ర చూపించు',
  cert_presented: 'ఇందుమూలంగా ధ్రువీకరించడమేమనగా',
  cert_date: 'తేదీ',
  name_placeholder: 'విద్యార్థి పేరు',
  pos_1: 'ప్రథమ స్థానం',
  pos_2: 'ద్వితీయ స్థానం',
  pos_3: 'తృతీయ స్థానం',
  pos_word_1: 'ప్రథమ',
  pos_word_2: 'ద్వితీయ',
  pos_word_3: 'తృతీయ',
  btn_print_all: 'అన్నీ ప్రింట్ చేయండి',
  btn_print_one: 'ఇది ప్రింట్ చేయండి',
  btn_png: 'PNGగా సేవ్ చేయండి',
  prev_of: '{n}లో {i}',
  keys_tip: 'సూచన: ఒక సర్టిఫికెట్ నుండి మరొకదానికి వెళ్లడానికి బాణం కీలను వాడండి, పూర్తి స్క్రీన్‌లో కూడా.',
  print_tip: 'ప్రింట్ విండోలో A4, Landscape, margins "None" ఎంచుకుని, "Background graphics" ఆన్ చేయండి.',
  png_wait: 'చిత్రం తయారవుతోంది…',
  png_fail: 'ఈ బ్రౌజర్ చిత్రాన్ని తయారు చేయలేకపోయింది. బదులుగా "ప్రింట్ చేయండి" నొక్కి "Save as PDF" ఎంచుకోండి.',
  png_done: 'చిత్రం సేవ్ అయింది',
  sample_names: 'సాయి కృష్ణ - ప్రథమ\nలక్ష్మీ ప్రసన్న - ద్వితీయ\nవంశీ రెడ్డి - తృతీయ\nశ్రావ్య నాయుడు\nకిరణ్ వర్మ\nదీపిక రావు',
  sample_event: 'వార్షిక విజ్ఞాన ప్రదర్శన 2026',
  sample_school: 'ప్రభుత్వ ఉన్నత పాఠశాల, విజయవాడ',
  sample_sig1_name: 'సునీత రెడ్డి',
  sample_sig1_role: 'తరగతి ఉపాధ్యాయురాలు',
  sample_sig2_name: 'డా. రాజేష్ కుమార్',
  sample_sig2_role: 'ప్రధానోపాధ్యాయులు'
};

window.APP_STRINGS.kn = {
  app_title: 'ಪ್ರಮಾಣಪತ್ರ ಮೇಕರ್',
  intro: 'ಇಡೀ ತರಗತಿಯ ಸುಂದರ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಒಮ್ಮೆಲೇ ತಯಾರಿಸಿ: ಹೆಸರುಗಳನ್ನು ಬರೆಯಿರಿ, ವಿನ್ಯಾಸ ಆರಿಸಿ, ನಂತರ ಎಲ್ಲವನ್ನೂ ಮುದ್ರಿಸಿ ಅಥವಾ PNG ಆಗಿ ಉಳಿಸಿ.',
  help_title: 'ಬಳಸುವುದು ಹೇಗೆ · ತರಗತಿಗಾಗಿ ಆಲೋಚನೆಗಳು',
  help_1: 'ಹೆಸರುಗಳನ್ನು ಬರೆಯಿರಿ ಅಥವಾ ಅಂಟಿಸಿ, ಪ್ರತಿ ಸಾಲಿಗೆ ಒಂದು ಹೆಸರು. ಸ್ಥಾನ ಸೇರಿಸಲು ಡ್ಯಾಶ್ ನಂತರ ಬರೆಯಿರಿ, ಉದಾ. "ಪ್ರಜ್ವಲ್ ಗೌಡ - ಪ್ರಥಮ". ಪ್ರಥಮ, ದ್ವಿತೀಯ, ತೃತೀಯ (ಅಥವಾ 1, 2, 3) ಸ್ಥಾನಗಳಿಗೆ ಚಿನ್ನ, ಬೆಳ್ಳಿ, ಕಂಚಿನ ಬಣ್ಣದ ಮುದ್ರೆಯೂ ಸಿಗುತ್ತದೆ.',
  help_2: 'ಪ್ರಮಾಣಪತ್ರದ ಪ್ರಕಾರ ಮತ್ತು ವಿನ್ಯಾಸ ಆರಿಸಿ. ಶೀರ್ಷಿಕೆ ಮತ್ತು ಸಂದೇಶ ತಾವಾಗಿಯೇ ಬದಲಾಗುತ್ತವೆ; ಆದರೂ ನೀವು ಅವನ್ನು ಬದಲಿಸಬಹುದು.',
  help_3: 'ಸಂದೇಶದಲ್ಲಿ {name}, {event}, {position}, {school} ಮತ್ತು {date} ಬಳಸಬಹುದು. ಪ್ರತಿಯೊಬ್ಬರಿಗೂ ಇವು ತಾವಾಗಿಯೇ ತುಂಬುತ್ತವೆ.',
  help_4: '"ಎಲ್ಲವನ್ನೂ ಮುದ್ರಿಸಿ" ಒತ್ತಿದರೆ ಪ್ರತಿ ಪ್ರಮಾಣಪತ್ರ ಬೇರೆ A4 ಲ್ಯಾಂಡ್‌ಸ್ಕೇಪ್ ಪುಟದಲ್ಲಿ ಮುದ್ರಣವಾಗುತ್ತದೆ. ಪ್ರಿಂಟ್ ವಿಂಡೋದಲ್ಲಿ ಪೂರ್ಣ ಬಣ್ಣಕ್ಕಾಗಿ "Background graphics" ಆನ್ ಮಾಡಿ, ಅಥವಾ "Save as PDF" ಆರಿಸಿ.',
  help_5: 'ತರಗತಿ ಆಲೋಚನೆ: ರಸಪ್ರಶ್ನೆ ಅಥವಾ ಕ್ರೀಡಾ ದಿನದ ನಂತರ ವಿಜೇತರ ಪಟ್ಟಿಯನ್ನು ವಿದ್ಯಾರ್ಥಿಗಳೇ ಬರೆದು ವಿನ್ಯಾಸ ಆರಿಸಲಿ; ಬಹುಮಾನ ವಿತರಣೆಯಲ್ಲಿ ಪ್ರತಿ ಪ್ರಮಾಣಪತ್ರವನ್ನು ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಪೂರ್ಣ ಪರದೆಯಲ್ಲಿ ತೋರಿಸಿ.',
  help_6: 'ಆ್ಯಪ್ ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿದೆ, ಆದರೆ ಪ್ರಮಾಣಪತ್ರ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಬೇಕೇ? "ಪ್ರಮಾಣಪತ್ರದ ಭಾಷೆ"ಯಲ್ಲಿ ಇಂಗ್ಲಿಷ್ ಆರಿಸಿ.',
  sec_design: 'ವಿನ್ಯಾಸ',
  sec_names: 'ಹೆಸರುಗಳು',
  sec_text: 'ಪ್ರಮಾಣಪತ್ರದ ಬರಹ',
  sec_school: 'ಶಾಲೆ, ಸಹಿಗಳು ಮತ್ತು ದಿನಾಂಕ',
  sec_preview: 'ಮುನ್ನೋಟ',
  designs_aria: 'ವಿನ್ಯಾಸ ಆರಿಸಿ',
  d_classic: 'ಚಿನ್ನದ ಕ್ಲಾಸಿಕ್',
  d_royal: 'ರಾಜ ನೀಲಿ',
  d_tiranga: 'ತ್ರಿವರ್ಣ',
  d_rangoli: 'ರಂಗೋಲಿ',
  d_modern: 'ಆಧುನಿಕ',
  f_names: 'ಹೆಸರುಗಳು, ಪ್ರತಿ ಸಾಲಿಗೆ ಒಂದು',
  f_names_hint: 'ಡ್ಯಾಶ್ ನಂತರ ಸ್ಥಾನ ಬರೆಯಿರಿ: "ಪ್ರಜ್ವಲ್ ಗೌಡ - ಪ್ರಥಮ". Excel ನಿಂದ ಪೂರ್ಣ ಕಾಲಂ ಅನ್ನು ಸಹ ಅಂಟಿಸಬಹುದು.',
  count_n: '{n} ಪ್ರಮಾಣಪತ್ರಗಳು',
  count_1: '1 ಪ್ರಮಾಣಪತ್ರ',
  too_many: 'ಮೊದಲ {n} ಹೆಸರುಗಳನ್ನು ಮಾತ್ರ ತೆಗೆದುಕೊಳ್ಳಲಾಗುತ್ತದೆ.',
  no_names: 'ಪ್ರಮಾಣಪತ್ರ ತಯಾರಿಸಲು ಕನಿಷ್ಠ ಒಂದು ಹೆಸರು ಬರೆಯಿರಿ.',
  f_type: 'ಪ್ರಮಾಣಪತ್ರದ ಪ್ರಕಾರ',
  type_merit: 'ಪ್ರತಿಭೆ',
  type_participation: 'ಭಾಗವಹಿಸುವಿಕೆ',
  type_appreciation: 'ಪ್ರಶಂಸೆ',
  type_excellence: 'ಶ್ರೇಷ್ಠತೆ',
  type_completion: 'ಕೋರ್ಸ್ ಪೂರ್ಣ',
  title_merit: 'ಪ್ರತಿಭಾ ಪ್ರಮಾಣಪತ್ರ',
  title_participation: 'ಭಾಗವಹಿಸುವಿಕೆ ಪ್ರಮಾಣಪತ್ರ',
  title_appreciation: 'ಪ್ರಶಂಸಾ ಪತ್ರ',
  title_excellence: 'ಶ್ರೇಷ್ಠತಾ ಪ್ರಮಾಣಪತ್ರ',
  title_completion: 'ಕೋರ್ಸ್ ಪೂರ್ಣಗೊಳಿಸಿದ ಪ್ರಮಾಣಪತ್ರ',
  f_title: 'ಪ್ರಮಾಣಪತ್ರದ ಶೀರ್ಷಿಕೆ',
  f_event: 'ಕಾರ್ಯಕ್ರಮ ಅಥವಾ ಕಾರಣ',
  f_message: 'ಸಂದೇಶ',
  f_message_hint: 'ಪ್ರತಿಯೊಬ್ಬರ ವಿವರ ತುಂಬಲು {name}, {event}, {position}, {school} ಅಥವಾ {date} ಬರೆಯಿರಿ.',
  msg_default: 'ಮೂಲ ಬರಹ ಬಳಸಿ',
  msg_merit: 'ಅವರು {event}ನಲ್ಲಿ ಅತ್ಯುತ್ತಮ ಸಾಧನೆ ಮಾಡಿದ್ದಾರೆ. ಅವರ ಪರಿಶ್ರಮದ ಬಗ್ಗೆ ನಮಗೆ ಹೆಮ್ಮೆ ಇದೆ.',
  msg_merit_gen: 'ಅವರು ಅತ್ಯುತ್ತಮ ಸಾಧನೆ ಮತ್ತು ಕಠಿಣ ಪರಿಶ್ರಮ ತೋರಿದ್ದಾರೆ. ನಮಗೆ ಹೆಮ್ಮೆ ಇದೆ!',
  msg_participation: 'ಅವರು {event}ನಲ್ಲಿ ಉತ್ಸಾಹದಿಂದ ಭಾಗವಹಿಸಿದ್ದಾರೆ. ಕಲಿಯುತ್ತಾ ಇರಿ, ಮುನ್ನಡೆಯುತ್ತಾ ಇರಿ!',
  msg_participation_gen: 'ಅವರು ಉತ್ಸಾಹದಿಂದ ಭಾಗವಹಿಸಿದ್ದಾರೆ. ಕಲಿಯುತ್ತಾ ಇರಿ, ಮುನ್ನಡೆಯುತ್ತಾ ಇರಿ!',
  msg_appreciation: 'ಅವರು {event}ನಲ್ಲಿ ಅಮೂಲ್ಯ ಕೊಡುಗೆ ನೀಡಿದ್ದಾರೆ. ಅವರ ಸಮರ್ಪಣೆಗೆ ಹೃತ್ಪೂರ್ವಕ ಧನ್ಯವಾದಗಳು.',
  msg_appreciation_gen: 'ಅವರು ಅಮೂಲ್ಯ ಕೊಡುಗೆ ಮತ್ತು ಸಮರ್ಪಣೆ ತೋರಿದ್ದಾರೆ. ಹೃತ್ಪೂರ್ವಕ ಧನ್ಯವಾದಗಳು!',
  msg_excellence: 'ಅವರು {event}ನಲ್ಲಿ ಶ್ರೇಷ್ಠತೆ ತೋರಿದ್ದಾರೆ. ಅವರ ಪರಿಶ್ರಮ ಮತ್ತು ಪ್ರತಿಭೆ ಎಲ್ಲರಿಗೂ ಸ್ಫೂರ್ತಿ.',
  msg_excellence_gen: 'ಅವರು ಓದು ಮತ್ತು ಉತ್ತಮ ನಡತೆಯಲ್ಲಿ ಶ್ರೇಷ್ಠತೆ ತೋರಿದ್ದಾರೆ. ಅವರ ಪರಿಶ್ರಮ ಎಲ್ಲರಿಗೂ ಸ್ಫೂರ್ತಿ.',
  msg_completion: 'ಅವರು {event} ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಳಿಸಿದ್ದಾರೆ.',
  msg_completion_gen: 'ಅವರು ಈ ಕೋರ್ಸ್ ಅನ್ನು ಶ್ರದ್ಧೆ ಮತ್ತು ಪ್ರಾಮಾಣಿಕತೆಯಿಂದ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಳಿಸಿದ್ದಾರೆ.',
  f_certlang: 'ಪ್ರಮಾಣಪತ್ರದ ಭಾಷೆ',
  certlang_ui: 'ಆ್ಯಪ್‌ನ ಭಾಷೆಯೇ',
  certlang_en: 'ಇಂಗ್ಲಿಷ್',
  f_school: 'ಶಾಲೆಯ ಹೆಸರು',
  f_logo: 'ಶಾಲೆಯ ಲೋಗೋ (ಬೇಕಿದ್ದರೆ)',
  logo_add: 'ಲೋಗೋ ಸೇರಿಸಿ',
  logo_remove: 'ಲೋಗೋ ತೆಗೆಯಿರಿ',
  logo_bad: 'ಈ ಚಿತ್ರ ತೆರೆಯಲಾಗಲಿಲ್ಲ. PNG ಅಥವಾ JPG ಫೈಲ್ ಪ್ರಯತ್ನಿಸಿ.',
  logo_alt: 'ಶಾಲೆಯ ಲೋಗೋ',
  f_date: 'ಪ್ರಮಾಣಪತ್ರದ ದಿನಾಂಕ',
  f_date_hint: 'ದಿನಾಂಕ ಮರೆಮಾಡಲು ಇದನ್ನು ಖಾಲಿ ಬಿಡಿ.',
  f_sig1: 'ಸಹಿ 1',
  f_sig2: 'ಸಹಿ 2',
  f_sig_name: 'ಹೆಸರು',
  f_sig_role: 'ಹುದ್ದೆ',
  f_seal: 'ಮುದ್ರೆ ತೋರಿಸಿ',
  cert_presented: 'ಈ ಮೂಲಕ ಪ್ರಮಾಣೀಕರಿಸುವುದೇನೆಂದರೆ',
  cert_date: 'ದಿನಾಂಕ',
  name_placeholder: 'ವಿದ್ಯಾರ್ಥಿಯ ಹೆಸರು',
  pos_1: 'ಪ್ರಥಮ ಸ್ಥಾನ',
  pos_2: 'ದ್ವಿತೀಯ ಸ್ಥಾನ',
  pos_3: 'ತೃತೀಯ ಸ್ಥಾನ',
  pos_word_1: 'ಪ್ರಥಮ',
  pos_word_2: 'ದ್ವಿತೀಯ',
  pos_word_3: 'ತೃತೀಯ',
  btn_print_all: 'ಎಲ್ಲವನ್ನೂ ಮುದ್ರಿಸಿ',
  btn_print_one: 'ಇದನ್ನು ಮುದ್ರಿಸಿ',
  btn_png: 'PNG ಆಗಿ ಉಳಿಸಿ',
  prev_of: '{n}ರಲ್ಲಿ {i}',
  keys_tip: 'ಸಲಹೆ: ಒಂದು ಪ್ರಮಾಣಪತ್ರದಿಂದ ಇನ್ನೊಂದಕ್ಕೆ ಹೋಗಲು ಬಾಣದ ಕೀಲಿಗಳನ್ನು ಬಳಸಿ, ಪೂರ್ಣ ಪರದೆಯಲ್ಲೂ.',
  print_tip: 'ಪ್ರಿಂಟ್ ವಿಂಡೋದಲ್ಲಿ A4, Landscape ಮತ್ತು margins "None" ಆರಿಸಿ, "Background graphics" ಆನ್ ಮಾಡಿ.',
  png_wait: 'ಚಿತ್ರ ತಯಾರಾಗುತ್ತಿದೆ…',
  png_fail: 'ಈ ಬ್ರೌಸರ್‌ಗೆ ಚಿತ್ರ ತಯಾರಿಸಲಾಗಲಿಲ್ಲ. ಬದಲಿಗೆ "ಮುದ್ರಿಸಿ" ಒತ್ತಿ "Save as PDF" ಆರಿಸಿ.',
  png_done: 'ಚಿತ್ರ ಉಳಿಸಲಾಗಿದೆ',
  sample_names: 'ಪ್ರಜ್ವಲ್ ಗೌಡ - ಪ್ರಥಮ\nಅನನ್ಯಾ ಹೆಗ್ಡೆ - ದ್ವಿತೀಯ\nಕಿರಣ್ ಶೆಟ್ಟಿ - ತೃತೀಯ\nಸ್ನೇಹಾ ರಾವ್\nಮನೋಜ್ ನಾಯಕ್\nಭಾವನಾ ಭಟ್',
  sample_event: 'ವಾರ್ಷಿಕ ವಿಜ್ಞಾನ ಪ್ರದರ್ಶನ 2026',
  sample_school: 'ಸರ್ಕಾರಿ ಪ್ರೌಢಶಾಲೆ, ಮೈಸೂರು',
  sample_sig1_name: 'ಸುನೀತಾ ಹೆಗ್ಡೆ',
  sample_sig1_role: 'ತರಗತಿ ಶಿಕ್ಷಕಿ',
  sample_sig2_name: 'ಡಾ. ರಾಜೇಶ್ ಮೂರ್ತಿ',
  sample_sig2_role: 'ಮುಖ್ಯ ಶಿಕ್ಷಕರು'
};

window.APP_STRINGS.ml = {
  app_title: 'സർട്ടിഫിക്കറ്റ് മേക്കർ',
  intro: 'ക്ലാസിലെ എല്ലാവർക്കുമുള്ള മനോഹരമായ സർട്ടിഫിക്കറ്റുകൾ ഒറ്റയടിക്ക് തയ്യാറാക്കൂ: പേരുകൾ എഴുതുക, ഡിസൈൻ തിരഞ്ഞെടുക്കുക, പിന്നെ എല്ലാം പ്രിന്റ് ചെയ്യുക അല്ലെങ്കിൽ PNG ആയി സേവ് ചെയ്യുക.',
  help_title: 'എങ്ങനെ ഉപയോഗിക്കാം · ക്ലാസ് മുറിക്കുള്ള ആശയങ്ങൾ',
  help_1: 'പേരുകൾ എഴുതുക അല്ലെങ്കിൽ പേസ്റ്റ് ചെയ്യുക, ഓരോ വരിയിലും ഒരു പേര്. സ്ഥാനം ചേർക്കാൻ ഡാഷിനു ശേഷം എഴുതുക, ഉദാ. "അർജുൻ മേനോൻ - ഒന്നാം". ഒന്നാം, രണ്ടാം, മൂന്നാം (അല്ലെങ്കിൽ 1, 2, 3) സ്ഥാനങ്ങൾക്ക് സ്വർണ്ണം, വെള്ളി, വെങ്കല നിറത്തിലുള്ള മുദ്രയും ലഭിക്കും.',
  help_2: 'സർട്ടിഫിക്കറ്റിന്റെ തരവും ഡിസൈനും തിരഞ്ഞെടുക്കുക. തലക്കെട്ടും സന്ദേശവും തനിയെ മാറും; എന്നാലും നിങ്ങൾക്ക് അവ തിരുത്താം.',
  help_3: 'സന്ദേശത്തിൽ {name}, {event}, {position}, {school}, {date} എന്നിവ ഉപയോഗിക്കാം. ഓരോരുത്തർക്കും ഇവ തനിയെ നിറയും.',
  help_4: '"എല്ലാം പ്രിന്റ് ചെയ്യുക" അമർത്തിയാൽ ഓരോ സർട്ടിഫിക്കറ്റും വെവ്വേറെ A4 ലാൻഡ്‌സ്‌കേപ്പ് പേജിൽ പ്രിന്റ് ആകും. പ്രിന്റ് വിൻഡോയിൽ പൂർണ്ണ നിറത്തിനായി "Background graphics" ഓണാക്കുക, അല്ലെങ്കിൽ "Save as PDF" തിരഞ്ഞെടുക്കുക.',
  help_5: 'ക്ലാസ് ആശയം: ക്വിസോ കായികദിനമോ കഴിഞ്ഞ് വിജയികളുടെ പട്ടിക കുട്ടികൾ തന്നെ എഴുതി ഡിസൈൻ തിരഞ്ഞെടുക്കട്ടെ; സമ്മാനദാന ചടങ്ങിൽ ഓരോ സർട്ടിഫിക്കറ്റും സ്മാർട്ട്ബോർഡിൽ പൂർണ്ണ സ്ക്രീനിൽ കാണിക്കുക.',
  help_6: 'ആപ്പ് നിങ്ങളുടെ ഭാഷയിലാണ്, പക്ഷേ സർട്ടിഫിക്കറ്റ് ഇംഗ്ലീഷിൽ വേണോ? "സർട്ടിഫിക്കറ്റിന്റെ ഭാഷ"യിൽ ഇംഗ്ലീഷ് തിരഞ്ഞെടുക്കുക.',
  sec_design: 'ഡിസൈൻ',
  sec_names: 'പേരുകൾ',
  sec_text: 'സർട്ടിഫിക്കറ്റിലെ വാചകം',
  sec_school: 'സ്കൂൾ, ഒപ്പുകൾ, തീയതി',
  sec_preview: 'പ്രിവ്യൂ',
  designs_aria: 'ഡിസൈൻ തിരഞ്ഞെടുക്കുക',
  d_classic: 'സ്വർണ്ണ ക്ലാസിക്',
  d_royal: 'രാജകീയ നീല',
  d_tiranga: 'ത്രിവർണ്ണം',
  d_rangoli: 'പൂക്കളം',
  d_modern: 'ആധുനികം',
  f_names: 'പേരുകൾ, ഓരോ വരിയിലും ഒന്ന്',
  f_names_hint: 'ഡാഷിനു ശേഷം സ്ഥാനം എഴുതുക: "അർജുൻ മേനോൻ - ഒന്നാം". Excel-ൽ നിന്ന് മുഴുവൻ കോളവും പേസ്റ്റ് ചെയ്യാം.',
  count_n: '{n} സർട്ടിഫിക്കറ്റുകൾ',
  count_1: '1 സർട്ടിഫിക്കറ്റ്',
  too_many: 'ആദ്യത്തെ {n} പേരുകൾ മാത്രമേ എടുക്കൂ.',
  no_names: 'സർട്ടിഫിക്കറ്റ് തയ്യാറാക്കാൻ കുറഞ്ഞത് ഒരു പേരെങ്കിലും എഴുതുക.',
  f_type: 'സർട്ടിഫിക്കറ്റിന്റെ തരം',
  type_merit: 'മെറിറ്റ്',
  type_participation: 'പങ്കാളിത്തം',
  type_appreciation: 'അഭിനന്ദനം',
  type_excellence: 'മികവ്',
  type_completion: 'കോഴ്സ് പൂർത്തീകരണം',
  title_merit: 'മെറിറ്റ് സർട്ടിഫിക്കറ്റ്',
  title_participation: 'പങ്കാളിത്ത സർട്ടിഫിക്കറ്റ്',
  title_appreciation: 'അഭിനന്ദന സർട്ടിഫിക്കറ്റ്',
  title_excellence: 'മികവിനുള്ള സർട്ടിഫിക്കറ്റ്',
  title_completion: 'പൂർത്തീകരണ സർട്ടിഫിക്കറ്റ്',
  f_title: 'സർട്ടിഫിക്കറ്റിലെ തലക്കെട്ട്',
  f_event: 'പരിപാടി അല്ലെങ്കിൽ കാരണം',
  f_message: 'സന്ദേശം',
  f_message_hint: 'ഓരോരുത്തരുടെയും വിവരങ്ങൾ നിറയ്ക്കാൻ {name}, {event}, {position}, {school} അല്ലെങ്കിൽ {date} എഴുതുക.',
  msg_default: 'ആദ്യത്തെ വാചകം ഉപയോഗിക്കുക',
  msg_merit: '{event}-ൽ മികച്ച പ്രകടനം കാഴ്ചവച്ചതിന്. ഈ കഠിനാധ്വാനത്തിൽ ഞങ്ങൾ അഭിമാനിക്കുന്നു.',
  msg_merit_gen: 'മികച്ച പ്രകടനത്തിനും കഠിനാധ്വാനത്തിനും. ഞങ്ങൾ അഭിമാനിക്കുന്നു!',
  msg_participation: '{event}-ൽ ആവേശത്തോടെ പങ്കെടുത്തതിന്. പഠനം തുടരൂ, തിളങ്ങൂ!',
  msg_participation_gen: 'ആവേശത്തോടെ പങ്കെടുത്തതിന്. പഠനം തുടരൂ, തിളങ്ങൂ!',
  msg_appreciation: '{event}-ൽ നൽകിയ വിലപ്പെട്ട സംഭാവനയ്ക്കുള്ള അഭിനന്ദനമായി. ഈ അർപ്പണബോധത്തിന് ഹൃദയം നിറഞ്ഞ നന്ദി.',
  msg_appreciation_gen: 'വിലപ്പെട്ട സംഭാവനയ്ക്കും അർപ്പണബോധത്തിനുമുള്ള അഭിനന്ദനമായി. ഹൃദയം നിറഞ്ഞ നന്ദി!',
  msg_excellence: '{event}-ലെ മികവിന്. ഈ പരിശ്രമവും കഴിവും എല്ലാവർക്കും പ്രചോദനമാണ്.',
  msg_excellence_gen: 'പഠനത്തിലും നല്ല പെരുമാറ്റത്തിലുമുള്ള മികവിന്. ഈ പരിശ്രമം എല്ലാവർക്കും പ്രചോദനമാണ്.',
  msg_completion: '{event} വിജയകരമായി പൂർത്തിയാക്കിയതിന്.',
  msg_completion_gen: 'ആത്മാർഥതയോടെയും അർപ്പണത്തോടെയും കോഴ്സ് വിജയകരമായി പൂർത്തിയാക്കിയതിന്.',
  f_certlang: 'സർട്ടിഫിക്കറ്റിന്റെ ഭാഷ',
  certlang_ui: 'ആപ്പിന്റെ ഭാഷ തന്നെ',
  certlang_en: 'ഇംഗ്ലീഷ്',
  f_school: 'സ്കൂളിന്റെ പേര്',
  f_logo: 'സ്കൂൾ ലോഗോ (വേണമെങ്കിൽ)',
  logo_add: 'ലോഗോ ചേർക്കുക',
  logo_remove: 'ലോഗോ നീക്കുക',
  logo_bad: 'ഈ ചിത്രം തുറക്കാനായില്ല. PNG അല്ലെങ്കിൽ JPG ഫയൽ ശ്രമിക്കുക.',
  logo_alt: 'സ്കൂൾ ലോഗോ',
  f_date: 'സർട്ടിഫിക്കറ്റിലെ തീയതി',
  f_date_hint: 'തീയതി മറയ്ക്കാൻ ഇത് ശൂന്യമായി വിടുക.',
  f_sig1: 'ഒപ്പ് 1',
  f_sig2: 'ഒപ്പ് 2',
  f_sig_name: 'പേര്',
  f_sig_role: 'പദവി',
  f_seal: 'മുദ്ര കാണിക്കുക',
  cert_presented: 'ഈ സർട്ടിഫിക്കറ്റ് അഭിമാനപൂർവം സമ്മാനിക്കുന്നു',
  cert_date: 'തീയതി',
  name_placeholder: 'വിദ്യാർഥിയുടെ പേര്',
  pos_1: 'ഒന്നാം സ്ഥാനം',
  pos_2: 'രണ്ടാം സ്ഥാനം',
  pos_3: 'മൂന്നാം സ്ഥാനം',
  pos_word_1: 'ഒന്നാം',
  pos_word_2: 'രണ്ടാം',
  pos_word_3: 'മൂന്നാം',
  btn_print_all: 'എല്ലാം പ്രിന്റ് ചെയ്യുക',
  btn_print_one: 'ഇത് പ്രിന്റ് ചെയ്യുക',
  btn_png: 'PNG ആയി സേവ് ചെയ്യുക',
  prev_of: '{n}-ൽ {i}',
  keys_tip: 'സൂചന: ഒരു സർട്ടിഫിക്കറ്റിൽ നിന്ന് അടുത്തതിലേക്ക് പോകാൻ ആരോ കീകൾ ഉപയോഗിക്കുക, പൂർണ്ണ സ്ക്രീനിലും.',
  print_tip: 'പ്രിന്റ് വിൻഡോയിൽ A4, Landscape, margins "None" എന്നിവ തിരഞ്ഞെടുത്ത് "Background graphics" ഓണാക്കുക.',
  png_wait: 'ചിത്രം തയ്യാറാക്കുന്നു…',
  png_fail: 'ഈ ബ്രൗസറിന് ചിത്രം തയ്യാറാക്കാനായില്ല. പകരം "പ്രിന്റ്" അമർത്തി "Save as PDF" തിരഞ്ഞെടുക്കുക.',
  png_done: 'ചിത്രം സേവ് ചെയ്തു',
  sample_names: 'അർജുൻ മേനോൻ - ഒന്നാം\nഅനഘ നായർ - രണ്ടാം\nമുഹമ്മദ് ഷാഫി - മൂന്നാം\nഗോപിക പിള്ള\nആദിത്യ കൃഷ്ണൻ\nനിവേദ്യ ജോസഫ്',
  sample_event: 'വാർഷിക ശാസ്ത്രമേള 2026',
  sample_school: 'ഗവൺമെന്റ് ഹയർ സെക്കൻഡറി സ്കൂൾ, തൃശ്ശൂർ',
  sample_sig1_name: 'സുനിത മേനോൻ',
  sample_sig1_role: 'ക്ലാസ് ടീച്ചർ',
  sample_sig2_name: 'ഡോ. രാജേഷ് നായർ',
  sample_sig2_role: 'പ്രിൻസിപ്പൽ'
};

window.APP_STRINGS.ur = {
  app_title: 'سرٹیفکیٹ میکر',
  intro: 'پوری جماعت کے خوبصورت سرٹیفکیٹ ایک ساتھ بنائیں: نام لکھیں، ڈیزائن چنیں، پھر سب پرنٹ کریں یا PNG کے طور پر محفوظ کریں۔',
  help_title: 'استعمال کیسے کریں · کلاس کے لیے خیالات',
  help_1: 'نام لکھیں یا پیسٹ کریں، ہر لائن میں ایک نام۔ پوزیشن جوڑنے کے لیے ڈیش کے بعد لکھیں، جیسے "محمد فیضان - اول"۔ اول، دوم اور سوم (یا 1، 2، 3) پوزیشن کو سنہری، چاندی یا کانسی رنگ کی مہر بھی ملتی ہے۔',
  help_2: 'سرٹیفکیٹ کی قسم اور ڈیزائن چنیں۔ عنوان اور پیغام خود بخود بدل جاتے ہیں، پھر بھی آپ انہیں بدل سکتے ہیں۔',
  help_3: 'پیغام میں {name}، {event}، {position}، {school} اور {date} لکھ سکتے ہیں۔ ہر شخص کے لیے یہ خود بخود بھر جاتے ہیں۔',
  help_4: '"سب پرنٹ کریں" سے ہر سرٹیفکیٹ الگ A4 لینڈ اسکیپ صفحے پر چھپتا ہے۔ پرنٹ ونڈو میں پورے رنگوں کے لیے "Background graphics" آن کریں، یا "Save as PDF" چنیں۔',
  help_5: 'کلاس کے لیے خیال: کوئز یا کھیلوں کے دن کے بعد طلبہ سے جیتنے والوں کی فہرست لکھوائیں اور ڈیزائن چنوائیں، پھر انعامی تقریب میں ہر سرٹیفکیٹ اسمارٹ بورڈ پر پوری اسکرین میں دکھائیں۔',
  help_6: 'ایپ آپ کی زبان میں ہے، لیکن سرٹیفکیٹ انگریزی میں چاہیے؟ "سرٹیفکیٹ کی زبان" میں انگریزی چنیں۔',
  sec_design: 'ڈیزائن',
  sec_names: 'نام',
  sec_text: 'سرٹیفکیٹ کی عبارت',
  sec_school: 'اسکول، دستخط اور تاریخ',
  sec_preview: 'پیش نظارہ',
  designs_aria: 'ڈیزائن چنیں',
  d_classic: 'سنہرا کلاسک',
  d_royal: 'شاہی نیلا',
  d_tiranga: 'ترنگا',
  d_rangoli: 'رنگولی',
  d_modern: 'جدید',
  f_names: 'نام، ہر لائن میں ایک',
  f_names_hint: 'ڈیش کے بعد پوزیشن لکھیں: "محمد فیضان - اول"۔ Excel سے پورا کالم بھی پیسٹ کر سکتے ہیں۔',
  count_n: '{n} سرٹیفکیٹ',
  count_1: '1 سرٹیفکیٹ',
  too_many: 'صرف پہلے {n} نام لیے جائیں گے۔',
  no_names: 'سرٹیفکیٹ بنانے کے لیے کم از کم ایک نام لکھیں۔',
  f_type: 'سرٹیفکیٹ کی قسم',
  type_merit: 'امتیاز (میرٹ)',
  type_participation: 'شرکت',
  type_appreciation: 'تعریف',
  type_excellence: 'فضیلت',
  type_completion: 'کورس کی تکمیل',
  title_merit: 'سندِ امتیاز',
  title_participation: 'سندِ شرکت',
  title_appreciation: 'تعریفی سند',
  title_excellence: 'سندِ فضیلت',
  title_completion: 'سندِ تکمیل',
  f_title: 'سرٹیفکیٹ کا عنوان',
  f_event: 'تقریب یا وجہ',
  f_message: 'پیغام',
  f_message_hint: 'ہر شخص کی تفصیل بھرنے کے لیے {name}، {event}، {position}، {school} یا {date} لکھیں۔',
  msg_default: 'اصل عبارت لگائیں',
  msg_merit: 'نے {event} میں شاندار کارکردگی کا مظاہرہ کیا ہے۔ ہمیں اس محنت پر فخر ہے۔',
  msg_merit_gen: 'نے شاندار کارکردگی اور سخت محنت کا مظاہرہ کیا ہے۔ ہمیں فخر ہے!',
  msg_participation: 'نے {event} میں جوش و خروش سے حصہ لیا۔ سیکھتے رہیں، آگے بڑھتے رہیں!',
  msg_participation_gen: 'نے جوش و خروش سے حصہ لیا۔ سیکھتے رہیں، آگے بڑھتے رہیں!',
  msg_appreciation: 'نے {event} میں قیمتی تعاون پیش کیا ہے۔ آپ کی لگن کا دل سے شکریہ۔',
  msg_appreciation_gen: 'نے قیمتی تعاون اور لگن کا مظاہرہ کیا ہے۔ دل سے شکریہ!',
  msg_excellence: 'نے {event} میں امتیازی کارکردگی دکھائی ہے۔ آپ کی محنت اور صلاحیت سب کے لیے باعثِ ترغیب ہے۔',
  msg_excellence_gen: 'نے تعلیم اور اچھے اخلاق میں امتیاز حاصل کیا ہے۔ آپ کی محنت سب کے لیے باعثِ ترغیب ہے۔',
  msg_completion: 'نے {event} کامیابی سے مکمل کیا ہے۔',
  msg_completion_gen: 'نے پوری لگن اور دیانت داری سے یہ کورس کامیابی سے مکمل کیا ہے۔',
  f_certlang: 'سرٹیفکیٹ کی زبان',
  certlang_ui: 'ایپ والی زبان',
  certlang_en: 'انگریزی',
  f_school: 'اسکول کا نام',
  f_logo: 'اسکول کا لوگو (اگر چاہیں)',
  logo_add: 'لوگو شامل کریں',
  logo_remove: 'لوگو ہٹائیں',
  logo_bad: 'یہ تصویر نہیں کھل سکی۔ PNG یا JPG فائل آزمائیں۔',
  logo_alt: 'اسکول کا لوگو',
  f_date: 'سرٹیفکیٹ پر تاریخ',
  f_date_hint: 'تاریخ چھپانی ہو تو اسے خالی چھوڑ دیں۔',
  f_sig1: 'دستخط 1',
  f_sig2: 'دستخط 2',
  f_sig_name: 'نام',
  f_sig_role: 'عہدہ',
  f_seal: 'مہر دکھائیں',
  cert_presented: 'تصدیق کی جاتی ہے کہ',
  cert_date: 'تاریخ',
  name_placeholder: 'طالب علم کا نام',
  pos_1: 'پہلی پوزیشن',
  pos_2: 'دوسری پوزیشن',
  pos_3: 'تیسری پوزیشن',
  pos_word_1: 'اول',
  pos_word_2: 'دوم',
  pos_word_3: 'سوم',
  btn_print_all: 'سب پرنٹ کریں',
  btn_print_one: 'یہ پرنٹ کریں',
  btn_png: 'PNG میں محفوظ کریں',
  prev_of: '{n} میں سے {i}',
  keys_tip: 'مشورہ: ایک سرٹیفکیٹ سے دوسرے پر جانے کے لیے تیر والی کلیدیں استعمال کریں، پوری اسکرین میں بھی۔',
  print_tip: 'پرنٹ ونڈو میں A4، Landscape اور margins "None" چنیں، اور "Background graphics" آن کریں۔',
  png_wait: 'تصویر بن رہی ہے…',
  png_fail: 'یہ براؤزر تصویر نہیں بنا سکا۔ اس کے بجائے "پرنٹ کریں" دبا کر "Save as PDF" چنیں۔',
  png_done: 'تصویر محفوظ ہو گئی',
  sample_names: 'محمد فیضان - اول\nعائشہ خان - دوم\nزید احمد - سوم\nمریم فاطمہ\nعمران قریشی\nثنا پروین',
  sample_event: 'سالانہ سائنس نمائش 2026',
  sample_school: 'گورنمنٹ ہائر سیکنڈری اسکول، لکھنؤ',
  sample_sig1_name: 'نسرین بانو',
  sample_sig1_role: 'کلاس ٹیچر',
  sample_sig2_name: 'ڈاکٹر راجیش مہتا',
  sample_sig2_role: 'پرنسپل'
};
