/* UI strings for Line of Best Fit. Keys are identical in all 12 languages.
   Dataset names, axis names and the "Understand it" cards live in content.js. */
window.APP_STRINGS = {
  en: {
    app_title: 'Line of Best Fit',
    intro: 'See how AI learns a straight line from data: errors, loss, gradient descent and predictions.',
    data_label: 'Data',
    restore: 'Restore data',
    clear_dots: 'Clear dots',
    restored: 'The original data is back.',
    confirm_clear: 'Remove all your dots?',
    paste_btn: 'Paste data',
    show_label: 'Show:',
    show_res: 'Errors',
    show_sq: 'Squared errors',
    show_best: 'Best line',
    eq_label: 'The model (line)',
    loss_label: 'Loss (MSE)',
    miss: 'Typical miss ≈ {v}',
    closeness: 'Close to best',
    tab_manual: 'Fit by hand',
    tab_auto: 'Let AI learn',
    tab_predict: 'Predict',
    manual_hint: 'Move the line so that the red error lines become as short as possible. Watch the loss fall.',
    slope: 'Slope m (tilt)',
    slope_hint: 'How much y changes when x goes up by 1.',
    intercept: 'Intercept c',
    intercept_hint: 'The value of y where the line meets x = 0.',
    reset_line: 'Flat line again',
    coach_m0: 'The line is far from the dots. Tilt it with the round handles or the slope slider.',
    coach_m1: 'Getting closer! Make the red lines shorter on both sides of the line.',
    coach_m2: 'Very close. Small changes to m and c will squeeze out the last bit of loss.',
    coach_m3: 'Excellent! Your line is almost the best possible line. Now compare it with "Let AI learn".',
    need_points: 'Add at least 2 dots with different x values.',
    same_x: 'All dots have the same x, so no sloping line can be found. Move one dot sideways.',
    exact_title: 'Exact answer (least squares)',
    exact_hint: 'For a straight line, a formula finds the best m and c in one go.',
    exact_btn: 'Find the best line',
    follow: 'Keep the best line while I move dots',
    show_math: 'Show the calculation',
    gd_title: 'Gradient descent: how AI learns',
    gd_hint: 'The AI starts with a flat line. In every epoch it looks at all the dots and nudges m and c a little downhill on the loss.',
    lr_label: 'Learning rate (step size)',
    lr_tiny: 'Very small: safe, but very slow.',
    lr_small: 'Small: steady, but slow.',
    lr_good: 'Good: fast and stable.',
    lr_big: 'Too big: steps overshoot and the loss can explode!',
    epochs_label: 'Epochs per run',
    speed_label: 'Speed',
    speed_slow: 'Slow',
    speed_normal: 'Normal',
    speed_fast: 'Fast',
    gd_step: 'One step',
    gd_run: 'Run',
    gd_restart: 'Restart',
    epoch_label: 'Epoch',
    best_possible: 'Best possible',
    loss_chart: 'Loss curve: loss after every epoch',
    chart_empty: 'Press "One step" or "Run" to see the loss fall.',
    coach_gd_need: 'First add at least 2 dots with different x values.',
    coach_gd_explode: 'The loss exploded! The learning rate is too big. Choose a smaller one and press Restart.',
    coach_gd_up: 'The loss is going up: every step jumps over the valley. Lower the learning rate.',
    coach_gd_done: 'Learning done! The loss is now almost equal to the best possible loss.',
    coach_gd_running: 'Learning… watch the line move and the loss curve fall.',
    coach_gd_idle: 'Press "One step" to see one update, or "Run" to watch many epochs.',
    coach_gd_slow: 'The loss is falling, but slowly, because the learning rate is small. Run more epochs or raise it.',
    coach_gd_progress: 'The loss is falling. Press Run again to keep learning.',
    pred_title: 'Predict a new value',
    pred_hint: 'Choose x, or tap the graph. The line gives the prediction ŷ = m × x + c.',
    pred_answer: 'Prediction ŷ',
    pred_outside: 'Careful: this x is outside the data ({a} to {b}). Predictions far from the data can be badly wrong.',
    pred_negative: 'The line predicts a value below zero, which is impossible here. A straight line cannot describe everything.',
    pred_tip_best: 'Tip: this line is not the best one yet. Open "Let AI learn" and press "Find the best line" for a better prediction.',
    explain_title: 'Understand it',
    exp_title: 'Try an experiment',
    exp_outlier: '📍 Add an outlier',
    exp_small: '🐢 Learning rate too small',
    exp_right: '👍 Learning rate just right',
    exp_big: '💥 Learning rate too big',
    exp_outlier_msg: 'One unusual dot was added far from the others. The grey dashed line was the best line before; the new best line is pulled towards the outlier. Drag that dot around to see how much one point can change the model.',
    exp_small_msg: 'Learning rate 0.01: every step is tiny, so even after 200 epochs the line has not reached the best place. See how slowly the loss curve falls.',
    exp_right_msg: 'Learning rate 0.6: the loss falls quickly and the line settles on the best fit.',
    exp_big_msg: 'Learning rate 1.5: every step jumps over the valley and lands higher on the other side. The loss explodes instead of falling.',
    table_title: 'Data table and errors',
    add_row: 'Add row',
    dl_csv: 'Download CSV',
    col_pred: 'Predicted ŷ',
    col_err: 'Error y − ŷ',
    col_sq: 'Squared error',
    del_row: 'Delete row {n}',
    mse_line: 'Sum of squared errors = {s}. Divide by {n} dots: MSE = {v}.',
    own_empty: 'Tap the graph to add dots.',
    max_points: 'At most {n} dots.',
    kept_inside: 'The value was kept inside the graph.',
    paste_title: 'Paste your own data',
    paste_hint: 'Paste two columns of numbers (x and y), one pair on each line. Copy them from Excel or Google Sheets, or type them like: 150, 152',
    paste_xname: 'Name for x (optional)',
    paste_yname: 'Name for y (optional)',
    paste_go: 'Use this data',
    paste_bad: 'No number pairs found. Put two numbers on each line.',
    paste_ok: '{n} dots added.',
    before_label: 'before',
    best_label: 'best',
    err_word: 'error',
    graph_aria: 'Graph of {n} dots: {x} across and {y} upwards, with the model line.',
    points_n: '{n} dots',
    canvas_hint_manual: 'Drag a round handle to tilt the line, or drag the line up or down. Tap an empty spot to add a dot, drag a dot to move it, double-tap a dot to remove it.',
    canvas_hint_auto: 'Tap to add a dot, drag a dot to move it, double-tap a dot to remove it. Then let the AI learn again.',
    canvas_hint_predict: 'Tap anywhere on the graph to choose x for a prediction.',
    ws_title: 'Worksheet: Line of best fit',
    ws_name: 'Name: ______________   Class: ______   Date: __________',
    ws_q1: 'Write the equation of the line in the graph above. What do m and c mean for this data?',
    ws_q2: 'Choose any two dots. Find the error (y − ŷ) and the squared error for each.',
    ws_q3: 'Use the line to predict y when x = {x}. Show your working.',
    ws_q4: 'Why do we square the errors instead of just adding them?',
    ws_q5: 'In gradient descent, what happens if the learning rate is too big? What if it is too small?',
    howto: 'How to use / Ideas for the classroom',
    tip1: 'Start with "Fit by hand": drag the line until the loss is as small as you can make it. Then switch on "Best line" to compare.',
    tip2: 'Switch on "Squared errors": the boxes show why one big miss counts much more than many small ones.',
    tip3: 'Open "Let AI learn" and press Run. The falling loss curve is what "training" means. Then try the learning-rate experiments.',
    tip4: 'Class activity: measure the height and arm span of 10–15 classmates, add them with "Paste data", and predict the arm span of a new student.',
    tip5: 'Use Predict for a discussion: can the line predict the marks of a student who studies 40 hours a week? Why not?',
    tip6: 'Print gives the graph, the data table and a worksheet with 5 questions. Fullscreen works well on a smartboard.'
  },

  hi: {
    app_title: 'सबसे अच्छी रेखा',
    intro: 'देखिए AI डेटा से एक सीधी रेखा कैसे सीखता है: त्रुटि, लॉस, ग्रेडिएंट डिसेंट और अनुमान।',
    data_label: 'डेटा',
    restore: 'डेटा वापस लाएँ',
    clear_dots: 'बिंदु मिटाएँ',
    restored: 'असली डेटा वापस आ गया।',
    confirm_clear: 'अपने सारे बिंदु हटा दें?',
    paste_btn: 'डेटा पेस्ट करें',
    show_label: 'दिखाएँ:',
    show_res: 'त्रुटियाँ',
    show_sq: 'त्रुटियों के वर्ग',
    show_best: 'सबसे अच्छी रेखा',
    eq_label: 'मॉडल (रेखा)',
    loss_label: 'लॉस (MSE)',
    miss: 'आम तौर पर चूक ≈ {v}',
    closeness: 'सबसे अच्छी से कितनी पास',
    tab_manual: 'हाथ से बैठाएँ',
    tab_auto: 'AI को सीखने दें',
    tab_predict: 'अनुमान',
    manual_hint: 'रेखा को ऐसे खिसकाएँ कि लाल त्रुटि-लाइनें जितनी हो सके उतनी छोटी हो जाएँ। लॉस को घटते देखें।',
    slope: 'ढलान m (झुकाव)',
    slope_hint: 'x के 1 बढ़ने पर y कितना बदलता है।',
    intercept: 'अंतःखंड c',
    intercept_hint: 'जहाँ रेखा x = 0 पर मिलती है, वहाँ y का मान।',
    reset_line: 'फिर से सपाट रेखा',
    coach_m0: 'रेखा बिंदुओं से बहुत दूर है। गोल हैंडल या ढलान स्लाइडर से इसे झुकाइए।',
    coach_m1: 'पास आ रहे हैं! रेखा के दोनों तरफ़ लाल लाइनों को छोटा कीजिए।',
    coach_m2: 'बहुत पास! m और c में छोटे बदलाव से बचा हुआ लॉस भी घट जाएगा।',
    coach_m3: 'शाबाश! आपकी रेखा लगभग सबसे अच्छी रेखा है। अब "AI को सीखने दें" से तुलना कीजिए।',
    need_points: 'अलग-अलग x वाले कम से कम 2 बिंदु जोड़ें।',
    same_x: 'सभी बिंदुओं का x एक जैसा है, इसलिए कोई तिरछी रेखा नहीं मिल सकती। किसी एक बिंदु को बगल में खिसकाएँ।',
    exact_title: 'सटीक उत्तर (न्यूनतम वर्ग विधि)',
    exact_hint: 'सीधी रेखा के लिए एक सूत्र एक बार में सबसे अच्छे m और c निकाल देता है।',
    exact_btn: 'सबसे अच्छी रेखा खोजें',
    follow: 'बिंदु खिसकाते समय सबसे अच्छी रेखा बनाए रखें',
    show_math: 'हिसाब दिखाएँ',
    gd_title: 'ग्रेडिएंट डिसेंट: AI कैसे सीखता है',
    gd_hint: 'AI एक सपाट रेखा से शुरू करता है। हर एपॉक में वह सारे बिंदु देखता है और m और c को लॉस की ढलान पर थोड़ा नीचे की ओर खिसकाता है।',
    lr_label: 'लर्निंग रेट (कदम का आकार)',
    lr_tiny: 'बहुत छोटा: सुरक्षित, पर बहुत धीमा।',
    lr_small: 'छोटा: स्थिर, पर धीमा।',
    lr_good: 'अच्छा: तेज़ और स्थिर।',
    lr_big: 'बहुत बड़ा: कदम आगे निकल जाते हैं और लॉस फट सकता है!',
    epochs_label: 'एक बार में एपॉक',
    speed_label: 'गति',
    speed_slow: 'धीमी',
    speed_normal: 'सामान्य',
    speed_fast: 'तेज़',
    gd_step: 'एक कदम',
    gd_run: 'चलाएँ',
    gd_restart: 'फिर से शुरू',
    epoch_label: 'एपॉक',
    best_possible: 'सबसे कम संभव',
    loss_chart: 'लॉस वक्र: हर एपॉक के बाद का लॉस',
    chart_empty: 'लॉस को घटते देखने के लिए "एक कदम" या "चलाएँ" दबाएँ।',
    coach_gd_need: 'पहले अलग-अलग x वाले कम से कम 2 बिंदु जोड़ें।',
    coach_gd_explode: 'लॉस फट गया! लर्निंग रेट बहुत बड़ा है। छोटा चुनें और "फिर से शुरू" दबाएँ।',
    coach_gd_up: 'लॉस बढ़ रहा है: हर कदम घाटी के पार कूद रहा है। लर्निंग रेट कम कीजिए।',
    coach_gd_done: 'सीखना पूरा! अब लॉस लगभग सबसे कम संभव लॉस के बराबर है।',
    coach_gd_running: 'सीख रहा है… रेखा को खिसकते और लॉस वक्र को गिरते देखिए।',
    coach_gd_idle: 'एक बदलाव देखने के लिए "एक कदम" दबाएँ, या कई एपॉक देखने के लिए "चलाएँ"।',
    coach_gd_slow: 'लॉस घट रहा है, पर धीरे, क्योंकि लर्निंग रेट छोटा है। और एपॉक चलाएँ या रेट बढ़ाएँ।',
    coach_gd_progress: 'लॉस घट रहा है। सीखते रहने के लिए फिर "चलाएँ" दबाएँ।',
    pred_title: 'नए मान का अनुमान',
    pred_hint: 'x चुनें या ग्राफ़ पर टैप करें। रेखा अनुमान देती है: ŷ = m × x + c',
    pred_answer: 'अनुमान ŷ',
    pred_outside: 'सावधान: यह x डेटा की सीमा ({a} से {b}) से बाहर है। डेटा से दूर के अनुमान बहुत गलत हो सकते हैं।',
    pred_negative: 'रेखा शून्य से कम मान बता रही है, जो यहाँ असंभव है। सीधी रेखा हर चीज़ नहीं समझा सकती।',
    pred_tip_best: 'सुझाव: यह रेखा अभी सबसे अच्छी नहीं है। बेहतर अनुमान के लिए "AI को सीखने दें" खोलकर "सबसे अच्छी रेखा खोजें" दबाएँ।',
    explain_title: 'इसे समझें',
    exp_title: 'एक प्रयोग करके देखें',
    exp_outlier: '📍 एक आउटलायर जोड़ें',
    exp_small: '🐢 लर्निंग रेट बहुत छोटा',
    exp_right: '👍 लर्निंग रेट बिल्कुल सही',
    exp_big: '💥 लर्निंग रेट बहुत बड़ा',
    exp_outlier_msg: 'बाकी सबसे दूर एक अनोखा बिंदु जोड़ा गया है। स्लेटी डैश वाली रेखा पहले की सबसे अच्छी रेखा थी; नई सबसे अच्छी रेखा आउटलायर की ओर खिंच गई है। उस बिंदु को खींचकर देखिए कि एक बिंदु मॉडल को कितना बदल सकता है।',
    exp_small_msg: 'लर्निंग रेट 0.01: हर कदम बहुत छोटा है, इसलिए 200 एपॉक के बाद भी रेखा सबसे अच्छी जगह तक नहीं पहुँची। देखिए लॉस वक्र कितना धीरे गिरता है।',
    exp_right_msg: 'लर्निंग रेट 0.6: लॉस तेज़ी से घटता है और रेखा सबसे अच्छी जगह पर टिक जाती है।',
    exp_big_msg: 'लर्निंग रेट 1.5: हर कदम घाटी के पार कूदकर दूसरी तरफ़ और ऊपर पहुँचता है। लॉस घटने के बजाय फट जाता है।',
    table_title: 'डेटा तालिका और त्रुटियाँ',
    add_row: 'पंक्ति जोड़ें',
    dl_csv: 'CSV डाउनलोड करें',
    col_pred: 'अनुमानित ŷ',
    col_err: 'त्रुटि y − ŷ',
    col_sq: 'त्रुटि का वर्ग',
    del_row: 'पंक्ति {n} हटाएँ',
    mse_line: 'त्रुटियों के वर्गों का योग = {s}। इसे {n} बिंदुओं से भाग दें: MSE = {v}।',
    own_empty: 'बिंदु जोड़ने के लिए ग्राफ़ पर टैप करें।',
    max_points: 'ज़्यादा से ज़्यादा {n} बिंदु।',
    kept_inside: 'मान को ग्राफ़ के अंदर ही रखा गया।',
    paste_title: 'अपना डेटा पेस्ट करें',
    paste_hint: 'संख्याओं के दो कॉलम (x और y) पेस्ट करें, हर लाइन में एक जोड़ी। Excel या Google Sheets से कॉपी करें, या ऐसे लिखें: 150, 152',
    paste_xname: 'x का नाम (ज़रूरी नहीं)',
    paste_yname: 'y का नाम (ज़रूरी नहीं)',
    paste_go: 'यह डेटा इस्तेमाल करें',
    paste_bad: 'संख्याओं की कोई जोड़ी नहीं मिली। हर लाइन में दो संख्याएँ लिखें।',
    paste_ok: '{n} बिंदु जोड़े गए।',
    before_label: 'पहले',
    best_label: 'सबसे अच्छी',
    err_word: 'त्रुटि',
    graph_aria: '{n} बिंदुओं का ग्राफ़: आड़ी तरफ़ {x} और ऊपर की ओर {y}, साथ में मॉडल रेखा।',
    points_n: '{n} बिंदु',
    canvas_hint_manual: 'रेखा झुकाने के लिए गोल हैंडल खींचें, या रेखा को ऊपर-नीचे खींचें। खाली जगह टैप करके बिंदु जोड़ें, बिंदु खींचकर खिसकाएँ, दो बार टैप करके हटाएँ।',
    canvas_hint_auto: 'टैप करके बिंदु जोड़ें, खींचकर खिसकाएँ, दो बार टैप करके हटाएँ। फिर AI को दोबारा सीखने दें।',
    canvas_hint_predict: 'अनुमान के लिए x चुनने को ग्राफ़ पर कहीं भी टैप करें।',
    ws_title: 'वर्कशीट: सबसे अच्छी रेखा',
    ws_name: 'नाम: ______________   कक्षा: ______   तारीख: __________',
    ws_q1: 'ऊपर के ग्राफ़ वाली रेखा का समीकरण लिखिए। इस डेटा के लिए m और c का क्या मतलब है?',
    ws_q2: 'कोई दो बिंदु चुनिए। हर एक की त्रुटि (y − ŷ) और त्रुटि का वर्ग निकालिए।',
    ws_q3: 'रेखा से x = {x} होने पर y का अनुमान लगाइए। अपना हिसाब दिखाइए।',
    ws_q4: 'हम त्रुटियों को सीधे जोड़ने के बजाय उनका वर्ग क्यों करते हैं?',
    ws_q5: 'ग्रेडिएंट डिसेंट में लर्निंग रेट बहुत बड़ा हो तो क्या होता है? बहुत छोटा हो तो?',
    howto: 'कैसे इस्तेमाल करें / कक्षा के लिए सुझाव',
    tip1: '"हाथ से बैठाएँ" से शुरू करें: रेखा को तब तक खींचें जब तक लॉस जितना हो सके कम न हो जाए। फिर तुलना के लिए "सबसे अच्छी रेखा" चालू करें।',
    tip2: '"त्रुटियों के वर्ग" चालू करें: डिब्बे दिखाते हैं कि एक बड़ी चूक कई छोटी चूकों से कहीं ज़्यादा क्यों गिनी जाती है।',
    tip3: '"AI को सीखने दें" खोलकर "चलाएँ" दबाएँ। गिरता हुआ लॉस वक्र ही "ट्रेनिंग" है। फिर लर्निंग रेट वाले प्रयोग आज़माएँ।',
    tip4: 'कक्षा गतिविधि: 10–15 सहपाठियों की लंबाई और बाँहों का फैलाव नापें, "डेटा पेस्ट करें" से जोड़ें, और नए विद्यार्थी के फैलाव का अनुमान लगाएँ।',
    tip5: '"अनुमान" से चर्चा करें: क्या रेखा हफ़्ते में 40 घंटे पढ़ने वाले के अंक बता सकती है? क्यों नहीं?',
    tip6: 'प्रिंट करने पर ग्राफ़, डेटा तालिका और 5 सवालों वाली वर्कशीट मिलती है। स्मार्टबोर्ड पर फ़ुलस्क्रीन अच्छा चलता है।'
  },

  bn: {
    app_title: 'সবচেয়ে মানানসই রেখা',
    intro: 'দেখুন AI কীভাবে ডেটা থেকে একটি সরলরেখা শেখে: ত্রুটি, লস, গ্রেডিয়েন্ট ডিসেন্ট আর অনুমান।',
    data_label: 'ডেটা',
    restore: 'ডেটা ফিরিয়ে আনুন',
    clear_dots: 'বিন্দু মুছুন',
    restored: 'আসল ডেটা ফিরে এসেছে।',
    confirm_clear: 'আপনার সব বিন্দু মুছে ফেলবেন?',
    paste_btn: 'ডেটা পেস্ট করুন',
    show_label: 'দেখান:',
    show_res: 'ত্রুটি',
    show_sq: 'ত্রুটির বর্গ',
    show_best: 'সেরা রেখা',
    eq_label: 'মডেল (রেখা)',
    loss_label: 'লস (MSE)',
    miss: 'সাধারণত ভুল ≈ {v}',
    closeness: 'সেরার কত কাছে',
    tab_manual: 'হাতে মেলান',
    tab_auto: 'AI-কে শিখতে দিন',
    tab_predict: 'অনুমান',
    manual_hint: 'রেখাটা এমনভাবে সরান যাতে লাল ত্রুটি-রেখাগুলো যত সম্ভব ছোট হয়। লস কমতে দেখুন।',
    slope: 'ঢাল m (হেলানো)',
    slope_hint: 'x 1 বাড়লে y কতটা বদলায়।',
    intercept: 'ছেদক c',
    intercept_hint: 'যেখানে রেখা x = 0-তে মেলে, সেখানে y-এর মান।',
    reset_line: 'আবার সমতল রেখা',
    coach_m0: 'রেখাটা বিন্দুগুলো থেকে অনেক দূরে। গোল হ্যান্ডেল বা ঢালের স্লাইডার দিয়ে হেলিয়ে দিন।',
    coach_m1: 'কাছে আসছেন! রেখার দুই দিকেই লাল রেখাগুলো ছোট করুন।',
    coach_m2: 'খুব কাছে। m আর c-তে ছোট বদল করলে বাকি লসটুকুও কমবে।',
    coach_m3: 'দারুণ! আপনার রেখা প্রায় সেরা রেখা। এবার "AI-কে শিখতে দিন"-এর সঙ্গে মিলিয়ে দেখুন।',
    need_points: 'আলাদা আলাদা x-সহ অন্তত 2টি বিন্দু যোগ করুন।',
    same_x: 'সব বিন্দুর x একই, তাই কোনো হেলানো রেখা পাওয়া যাবে না। একটি বিন্দু পাশে সরান।',
    exact_title: 'সঠিক উত্তর (ন্যূনতম বর্গ পদ্ধতি)',
    exact_hint: 'সরলরেখার জন্য একটি সূত্র এক বারেই সেরা m আর c বের করে দেয়।',
    exact_btn: 'সেরা রেখা খুঁজুন',
    follow: 'বিন্দু সরানোর সময় সেরা রেখা বজায় রাখুন',
    show_math: 'হিসাব দেখান',
    gd_title: 'গ্রেডিয়েন্ট ডিসেন্ট: AI কীভাবে শেখে',
    gd_hint: 'AI একটি সমতল রেখা দিয়ে শুরু করে। প্রতিটি এপকে সে সব বিন্দু দেখে এবং m আর c-কে লসের ঢাল বেয়ে একটু নিচের দিকে সরায়।',
    lr_label: 'লার্নিং রেট (পদক্ষেপের মাপ)',
    lr_tiny: 'খুব ছোট: নিরাপদ, কিন্তু খুব ধীর।',
    lr_small: 'ছোট: স্থির, কিন্তু ধীর।',
    lr_good: 'ভালো: দ্রুত আর স্থির।',
    lr_big: 'খুব বড়: পদক্ষেপ ছাড়িয়ে যায়, লস বিস্ফোরিত হতে পারে!',
    epochs_label: 'এক বারে কত এপক',
    speed_label: 'গতি',
    speed_slow: 'ধীর',
    speed_normal: 'সাধারণ',
    speed_fast: 'দ্রুত',
    gd_step: 'এক পদক্ষেপ',
    gd_run: 'চালান',
    gd_restart: 'আবার শুরু',
    epoch_label: 'এপক',
    best_possible: 'সবচেয়ে কম সম্ভব',
    loss_chart: 'লস রেখাচিত্র: প্রতি এপকের পরের লস',
    chart_empty: 'লস কমতে দেখতে "এক পদক্ষেপ" বা "চালান" টিপুন।',
    coach_gd_need: 'আগে আলাদা আলাদা x-সহ অন্তত 2টি বিন্দু যোগ করুন।',
    coach_gd_explode: 'লস বিস্ফোরিত হয়েছে! লার্নিং রেট খুব বড়। ছোট একটি বেছে "আবার শুরু" টিপুন।',
    coach_gd_up: 'লস বাড়ছে: প্রতিটি পদক্ষেপ উপত্যকা পেরিয়ে লাফিয়ে যাচ্ছে। লার্নিং রেট কমান।',
    coach_gd_done: 'শেখা শেষ! লস এখন প্রায় সবচেয়ে কম সম্ভব লসের সমান।',
    coach_gd_running: 'শিখছে… রেখার নড়াচড়া আর লস রেখাচিত্রের নামা দেখুন।',
    coach_gd_idle: 'একটি বদল দেখতে "এক পদক্ষেপ" টিপুন, অনেক এপক দেখতে "চালান"।',
    coach_gd_slow: 'লস কমছে, কিন্তু ধীরে, কারণ লার্নিং রেট ছোট। আরও এপক চালান বা রেট বাড়ান।',
    coach_gd_progress: 'লস কমছে। শেখা চালিয়ে যেতে আবার "চালান" টিপুন।',
    pred_title: 'নতুন মান অনুমান করুন',
    pred_hint: 'x বেছে নিন বা গ্রাফে টিপুন। রেখা অনুমান দেয়: ŷ = m × x + c',
    pred_answer: 'অনুমান ŷ',
    pred_outside: 'সাবধান: এই x ডেটার সীমার ({a} থেকে {b}) বাইরে। ডেটা থেকে দূরের অনুমান খুব ভুল হতে পারে।',
    pred_negative: 'রেখা শূন্যের চেয়ে কম মান দেখাচ্ছে, যা এখানে অসম্ভব। একটা সরলরেখা সব কিছু বোঝাতে পারে না।',
    pred_tip_best: 'পরামর্শ: এই রেখা এখনও সেরা নয়। ভালো অনুমানের জন্য "AI-কে শিখতে দিন" খুলে "সেরা রেখা খুঁজুন" টিপুন।',
    explain_title: 'বুঝে নিন',
    exp_title: 'একটা পরীক্ষা করে দেখুন',
    exp_outlier: '📍 একটি আউটলায়ার যোগ করুন',
    exp_small: '🐢 লার্নিং রেট খুব ছোট',
    exp_right: '👍 লার্নিং রেট একদম ঠিক',
    exp_big: '💥 লার্নিং রেট খুব বড়',
    exp_outlier_msg: 'বাকিদের থেকে অনেক দূরে একটি অদ্ভুত বিন্দু যোগ করা হয়েছে। ধূসর ড্যাশ রেখাটি আগের সেরা রেখা; নতুন সেরা রেখা আউটলায়ারের দিকে টেনে নেওয়া হয়েছে। বিন্দুটি টেনে দেখুন একটি বিন্দু মডেলকে কতটা বদলাতে পারে।',
    exp_small_msg: 'লার্নিং রেট 0.01: প্রতিটি পদক্ষেপ খুব ছোট, তাই 200 এপকের পরেও রেখা সেরা জায়গায় পৌঁছায়নি। দেখুন লস রেখাচিত্র কত ধীরে নামে।',
    exp_right_msg: 'লার্নিং রেট 0.6: লস দ্রুত কমে আর রেখা সেরা জায়গায় থিতু হয়।',
    exp_big_msg: 'লার্নিং রেট 1.5: প্রতিটি পদক্ষেপ উপত্যকা পেরিয়ে অন্য পাশে আরও উঁচুতে গিয়ে পড়ে। লস কমার বদলে বিস্ফোরিত হয়।',
    table_title: 'ডেটা সারণি ও ত্রুটি',
    add_row: 'সারি যোগ করুন',
    dl_csv: 'CSV ডাউনলোড',
    col_pred: 'অনুমিত ŷ',
    col_err: 'ত্রুটি y − ŷ',
    col_sq: 'ত্রুটির বর্গ',
    del_row: 'সারি {n} মুছুন',
    mse_line: 'ত্রুটির বর্গগুলোর যোগফল = {s}। {n}টি বিন্দু দিয়ে ভাগ করুন: MSE = {v}।',
    own_empty: 'বিন্দু যোগ করতে গ্রাফে টিপুন।',
    max_points: 'সর্বোচ্চ {n}টি বিন্দু।',
    kept_inside: 'মানটি গ্রাফের ভেতরেই রাখা হয়েছে।',
    paste_title: 'নিজের ডেটা পেস্ট করুন',
    paste_hint: 'সংখ্যার দুটি কলাম (x আর y) পেস্ট করুন, প্রতি লাইনে একটি জোড়া। Excel বা Google Sheets থেকে কপি করুন, বা এভাবে লিখুন: 150, 152',
    paste_xname: 'x-এর নাম (ঐচ্ছিক)',
    paste_yname: 'y-এর নাম (ঐচ্ছিক)',
    paste_go: 'এই ডেটা ব্যবহার করুন',
    paste_bad: 'কোনো সংখ্যার জোড়া পাওয়া যায়নি। প্রতি লাইনে দুটি সংখ্যা লিখুন।',
    paste_ok: '{n}টি বিন্দু যোগ হয়েছে।',
    before_label: 'আগে',
    best_label: 'সেরা',
    err_word: 'ত্রুটি',
    graph_aria: '{n}টি বিন্দুর গ্রাফ: আড়াআড়ি {x}, উপরের দিকে {y}, সঙ্গে মডেল রেখা।',
    points_n: '{n}টি বিন্দু',
    canvas_hint_manual: 'রেখা হেলাতে গোল হ্যান্ডেল টানুন, বা রেখাটি উপরে-নিচে টানুন। ফাঁকা জায়গায় টিপে বিন্দু যোগ করুন, টেনে সরান, দুবার টিপে মুছুন।',
    canvas_hint_auto: 'টিপে বিন্দু যোগ করুন, টেনে সরান, দুবার টিপে মুছুন। তারপর AI-কে আবার শিখতে দিন।',
    canvas_hint_predict: 'অনুমানের জন্য x বাছতে গ্রাফের যে কোনো জায়গায় টিপুন।',
    ws_title: 'ওয়ার্কশিট: সবচেয়ে মানানসই রেখা',
    ws_name: 'নাম: ______________   শ্রেণি: ______   তারিখ: __________',
    ws_q1: 'উপরের গ্রাফের রেখার সমীকরণ লেখো। এই ডেটার ক্ষেত্রে m আর c-এর মানে কী?',
    ws_q2: 'যে কোনো দুটি বিন্দু বেছে নাও। প্রতিটির ত্রুটি (y − ŷ) আর ত্রুটির বর্গ বের করো।',
    ws_q3: 'রেখা ব্যবহার করে x = {x} হলে y অনুমান করো। হিসাব দেখাও।',
    ws_q4: 'ত্রুটিগুলো সরাসরি যোগ না করে আমরা তাদের বর্গ করি কেন?',
    ws_q5: 'গ্রেডিয়েন্ট ডিসেন্টে লার্নিং রেট খুব বড় হলে কী হয়? খুব ছোট হলে?',
    howto: 'কীভাবে ব্যবহার করবেন / ক্লাসের জন্য ভাবনা',
    tip1: '"হাতে মেলান" দিয়ে শুরু করুন: লস যত কম সম্ভব না হওয়া পর্যন্ত রেখা টানুন। তারপর মেলাতে "সেরা রেখা" চালু করুন।',
    tip2: '"ত্রুটির বর্গ" চালু করুন: বাক্সগুলো দেখায় কেন একটা বড় ভুল অনেক ছোট ভুলের চেয়ে বেশি গোনা হয়।',
    tip3: '"AI-কে শিখতে দিন" খুলে "চালান" টিপুন। নামতে থাকা লস রেখাচিত্রই হলো "ট্রেনিং"। তারপর লার্নিং রেটের পরীক্ষাগুলো করুন।',
    tip4: 'ক্লাসের কাজ: 10–15 জন সহপাঠীর উচ্চতা আর হাতের বিস্তার মাপুন, "ডেটা পেস্ট করুন" দিয়ে যোগ করুন, আর নতুন ছাত্রের বিস্তার অনুমান করুন।',
    tip5: '"অনুমান" দিয়ে আলোচনা করুন: সপ্তাহে 40 ঘণ্টা পড়া ছাত্রের নম্বর কি রেখা বলতে পারবে? কেন নয়?',
    tip6: 'প্রিন্ট করলে গ্রাফ, ডেটা সারণি আর 5টি প্রশ্নের ওয়ার্কশিট পাওয়া যায়। স্মার্টবোর্ডে ফুলস্ক্রিন ভালো চলে।'
  },

  mr: {
    app_title: 'सर्वोत्तम रेषा',
    intro: 'AI डेटामधून सरळ रेषा कशी शिकते ते पाहा: त्रुटी, लॉस, ग्रेडियंट डिसेंट आणि अंदाज.',
    data_label: 'डेटा',
    restore: 'डेटा परत आणा',
    clear_dots: 'बिंदू पुसा',
    restored: 'मूळ डेटा परत आला.',
    confirm_clear: 'तुमचे सगळे बिंदू काढून टाकायचे?',
    paste_btn: 'डेटा पेस्ट करा',
    show_label: 'दाखवा:',
    show_res: 'त्रुटी',
    show_sq: 'त्रुटींचे वर्ग',
    show_best: 'सर्वोत्तम रेषा',
    eq_label: 'मॉडेल (रेषा)',
    loss_label: 'लॉस (MSE)',
    miss: 'साधारण चूक ≈ {v}',
    closeness: 'सर्वोत्तमच्या किती जवळ',
    tab_manual: 'हाताने बसवा',
    tab_auto: 'AI ला शिकू द्या',
    tab_predict: 'अंदाज',
    manual_hint: 'रेषा अशी हलवा की लाल त्रुटी-रेषा शक्य तितक्या लहान होतील. लॉस कमी होताना पाहा.',
    slope: 'उतार m (कल)',
    slope_hint: 'x 1 ने वाढला की y किती बदलतो.',
    intercept: 'अंतःखंड c',
    intercept_hint: 'रेषा x = 0 ला जिथे भेटते तिथली y ची किंमत.',
    reset_line: 'पुन्हा सपाट रेषा',
    coach_m0: 'रेषा बिंदूंपासून खूप दूर आहे. गोल हँडल किंवा उतार स्लायडरने ती तिरकी करा.',
    coach_m1: 'जवळ येताय! रेषेच्या दोन्ही बाजूंच्या लाल रेषा लहान करा.',
    coach_m2: 'खूप जवळ. m आणि c मध्ये छोटे बदल केले की उरलेला लॉसही कमी होईल.',
    coach_m3: 'छान! तुमची रेषा जवळजवळ सर्वोत्तम आहे. आता "AI ला शिकू द्या" शी तुलना करा.',
    need_points: 'वेगवेगळ्या x चे किमान 2 बिंदू जोडा.',
    same_x: 'सगळ्या बिंदूंचा x सारखाच आहे, म्हणून तिरकी रेषा मिळू शकत नाही. एक बिंदू बाजूला सरकवा.',
    exact_title: 'अचूक उत्तर (किमान वर्ग पद्धत)',
    exact_hint: 'सरळ रेषेसाठी एक सूत्र एका झटक्यात सर्वोत्तम m आणि c काढते.',
    exact_btn: 'सर्वोत्तम रेषा शोधा',
    follow: 'बिंदू हलवताना सर्वोत्तम रेषा कायम ठेवा',
    show_math: 'गणित दाखवा',
    gd_title: 'ग्रेडियंट डिसेंट: AI कसे शिकते',
    gd_hint: 'AI सपाट रेषेने सुरुवात करते. प्रत्येक एपॉकमध्ये ती सगळे बिंदू पाहते आणि m व c ला लॉसच्या उतारावरून थोडे खाली सरकवते.',
    lr_label: 'लर्निंग रेट (पावलाचा आकार)',
    lr_tiny: 'खूप लहान: सुरक्षित, पण खूप हळू.',
    lr_small: 'लहान: स्थिर, पण हळू.',
    lr_good: 'चांगला: वेगवान आणि स्थिर.',
    lr_big: 'खूप मोठा: पावले पुढे निघून जातात आणि लॉस फुगू शकतो!',
    epochs_label: 'एका वेळी एपॉक',
    speed_label: 'वेग',
    speed_slow: 'हळू',
    speed_normal: 'साधारण',
    speed_fast: 'जलद',
    gd_step: 'एक पाऊल',
    gd_run: 'चालवा',
    gd_restart: 'पुन्हा सुरू',
    epoch_label: 'एपॉक',
    best_possible: 'शक्य तितका कमी',
    loss_chart: 'लॉस वक्र: प्रत्येक एपॉकनंतरचा लॉस',
    chart_empty: 'लॉस कमी होताना पाहण्यासाठी "एक पाऊल" किंवा "चालवा" दाबा.',
    coach_gd_need: 'आधी वेगवेगळ्या x चे किमान 2 बिंदू जोडा.',
    coach_gd_explode: 'लॉस फुगला! लर्निंग रेट खूप मोठा आहे. लहान निवडा आणि "पुन्हा सुरू" दाबा.',
    coach_gd_up: 'लॉस वाढतोय: प्रत्येक पाऊल दरी ओलांडून उडी मारतंय. लर्निंग रेट कमी करा.',
    coach_gd_done: 'शिकणे पूर्ण! लॉस आता जवळजवळ शक्य तितक्या कमी लॉसएवढा आहे.',
    coach_gd_running: 'शिकत आहे… रेषा हलताना आणि लॉस वक्र खाली येताना पाहा.',
    coach_gd_idle: 'एक बदल पाहण्यासाठी "एक पाऊल" दाबा, अनेक एपॉक पाहण्यासाठी "चालवा".',
    coach_gd_slow: 'लॉस कमी होतोय, पण हळू, कारण लर्निंग रेट लहान आहे. आणखी एपॉक चालवा किंवा रेट वाढवा.',
    coach_gd_progress: 'लॉस कमी होतोय. शिकणे चालू ठेवण्यासाठी पुन्हा "चालवा" दाबा.',
    pred_title: 'नव्या किमतीचा अंदाज',
    pred_hint: 'x निवडा किंवा ग्राफवर टॅप करा. रेषा अंदाज देते: ŷ = m × x + c',
    pred_answer: 'अंदाज ŷ',
    pred_outside: 'सावधान: हा x डेटाच्या मर्यादेबाहेर ({a} ते {b}) आहे. डेटापासून दूरचे अंदाज खूप चुकू शकतात.',
    pred_negative: 'रेषा शून्यापेक्षा कमी किंमत सांगते, जी इथे अशक्य आहे. सरळ रेषा प्रत्येक गोष्ट समजावू शकत नाही.',
    pred_tip_best: 'टीप: ही रेषा अजून सर्वोत्तम नाही. चांगल्या अंदाजासाठी "AI ला शिकू द्या" उघडून "सर्वोत्तम रेषा शोधा" दाबा.',
    explain_title: 'समजून घ्या',
    exp_title: 'एक प्रयोग करून पाहा',
    exp_outlier: '📍 एक आउटलायर जोडा',
    exp_small: '🐢 लर्निंग रेट खूप लहान',
    exp_right: '👍 लर्निंग रेट अगदी योग्य',
    exp_big: '💥 लर्निंग रेट खूप मोठा',
    exp_outlier_msg: 'बाकीच्यांपासून खूप दूर एक वेगळा बिंदू जोडला आहे. राखाडी तुटक रेषा आधीची सर्वोत्तम रेषा होती; नवी सर्वोत्तम रेषा आउटलायरकडे ओढली गेली आहे. तो बिंदू ओढून पाहा, एक बिंदू मॉडेल किती बदलू शकतो.',
    exp_small_msg: 'लर्निंग रेट 0.01: प्रत्येक पाऊल अगदी लहान आहे, म्हणून 200 एपॉकनंतरही रेषा सर्वोत्तम जागी पोहोचली नाही. लॉस वक्र किती हळू खाली येतो ते पाहा.',
    exp_right_msg: 'लर्निंग रेट 0.6: लॉस वेगाने कमी होतो आणि रेषा सर्वोत्तम जागी स्थिरावते.',
    exp_big_msg: 'लर्निंग रेट 1.5: प्रत्येक पाऊल दरी ओलांडून दुसऱ्या बाजूला अजून वर पोहोचते. लॉस कमी होण्याऐवजी फुगत जातो.',
    table_title: 'डेटा तक्ता आणि त्रुटी',
    add_row: 'ओळ जोडा',
    dl_csv: 'CSV डाउनलोड करा',
    col_pred: 'अंदाजित ŷ',
    col_err: 'त्रुटी y − ŷ',
    col_sq: 'त्रुटीचा वर्ग',
    del_row: 'ओळ {n} काढा',
    mse_line: 'त्रुटींच्या वर्गांची बेरीज = {s}. तिला {n} बिंदूंनी भागा: MSE = {v}.',
    own_empty: 'बिंदू जोडण्यासाठी ग्राफवर टॅप करा.',
    max_points: 'जास्तीत जास्त {n} बिंदू.',
    kept_inside: 'किंमत ग्राफच्या आतच ठेवली.',
    paste_title: 'तुमचा डेटा पेस्ट करा',
    paste_hint: 'संख्यांचे दोन स्तंभ (x आणि y) पेस्ट करा, प्रत्येक ओळीत एक जोडी. Excel किंवा Google Sheets मधून कॉपी करा, किंवा असे लिहा: 150, 152',
    paste_xname: 'x चे नाव (ऐच्छिक)',
    paste_yname: 'y चे नाव (ऐच्छिक)',
    paste_go: 'हा डेटा वापरा',
    paste_bad: 'संख्यांची एकही जोडी मिळाली नाही. प्रत्येक ओळीत दोन संख्या लिहा.',
    paste_ok: '{n} बिंदू जोडले.',
    before_label: 'आधी',
    best_label: 'सर्वोत्तम',
    err_word: 'त्रुटी',
    graph_aria: '{n} बिंदूंचा ग्राफ: आडवा {x} आणि उभा {y}, सोबत मॉडेल रेषा.',
    points_n: '{n} बिंदू',
    canvas_hint_manual: 'रेषा तिरकी करण्यासाठी गोल हँडल ओढा, किंवा रेषा वर-खाली ओढा. रिकाम्या जागी टॅप करून बिंदू जोडा, ओढून हलवा, दोनदा टॅप करून काढा.',
    canvas_hint_auto: 'टॅप करून बिंदू जोडा, ओढून हलवा, दोनदा टॅप करून काढा. मग AI ला पुन्हा शिकू द्या.',
    canvas_hint_predict: 'अंदाजासाठी x निवडायला ग्राफवर कुठेही टॅप करा.',
    ws_title: 'वर्कशीट: सर्वोत्तम रेषा',
    ws_name: 'नाव: ______________   इयत्ता: ______   दिनांक: __________',
    ws_q1: 'वरील ग्राफमधील रेषेचे समीकरण लिहा. या डेटासाठी m आणि c चा अर्थ काय?',
    ws_q2: 'कोणतेही दोन बिंदू निवडा. प्रत्येकाची त्रुटी (y − ŷ) आणि त्रुटीचा वर्ग काढा.',
    ws_q3: 'रेषेच्या मदतीने x = {x} असताना y चा अंदाज करा. तुमचे गणित दाखवा.',
    ws_q4: 'त्रुटी थेट न बेरता आपण त्यांचा वर्ग का करतो?',
    ws_q5: 'ग्रेडियंट डिसेंटमध्ये लर्निंग रेट खूप मोठा असेल तर काय होते? खूप लहान असेल तर?',
    howto: 'कसे वापरावे / वर्गासाठी कल्पना',
    tip1: '"हाताने बसवा" पासून सुरुवात करा: लॉस शक्य तितका कमी होईपर्यंत रेषा ओढा. मग तुलनेसाठी "सर्वोत्तम रेषा" चालू करा.',
    tip2: '"त्रुटींचे वर्ग" चालू करा: चौकोन दाखवतात की एक मोठी चूक अनेक छोट्या चुकांपेक्षा खूप जास्त का मोजली जाते.',
    tip3: '"AI ला शिकू द्या" उघडून "चालवा" दाबा. खाली येणारा लॉस वक्र म्हणजेच "ट्रेनिंग". मग लर्निंग रेटचे प्रयोग करून पाहा.',
    tip4: 'वर्ग उपक्रम: 10–15 वर्गमित्रांची उंची आणि हातांचा पसारा मोजा, "डेटा पेस्ट करा" ने जोडा, आणि नव्या विद्यार्थ्याच्या पसाऱ्याचा अंदाज करा.',
    tip5: '"अंदाज" वापरून चर्चा करा: आठवड्याला 40 तास अभ्यास करणाऱ्याचे गुण रेषा सांगू शकेल का? का नाही?',
    tip6: 'प्रिंट केल्यावर ग्राफ, डेटा तक्ता आणि 5 प्रश्नांची वर्कशीट मिळते. स्मार्टबोर्डवर फुलस्क्रीन छान चालते.'
  },

  gu: {
    app_title: 'શ્રેષ્ઠ બંધબેસતી રેખા',
    intro: 'જુઓ AI ડેટામાંથી સીધી રેખા કેવી રીતે શીખે છે: ભૂલ, લૉસ, ગ્રેડિયન્ટ ડિસેન્ટ અને અનુમાન.',
    data_label: 'ડેટા',
    restore: 'ડેટા પાછો લાવો',
    clear_dots: 'બિંદુ ભૂંસો',
    restored: 'મૂળ ડેટા પાછો આવી ગયો.',
    confirm_clear: 'તમારા બધા બિંદુ કાઢી નાખવા છે?',
    paste_btn: 'ડેટા પેસ્ટ કરો',
    show_label: 'બતાવો:',
    show_res: 'ભૂલો',
    show_sq: 'ભૂલોના વર્ગ',
    show_best: 'શ્રેષ્ઠ રેખા',
    eq_label: 'મૉડલ (રેખા)',
    loss_label: 'લૉસ (MSE)',
    miss: 'સામાન્ય ચૂક ≈ {v}',
    closeness: 'શ્રેષ્ઠની કેટલી નજીક',
    tab_manual: 'હાથથી બેસાડો',
    tab_auto: 'AIને શીખવા દો',
    tab_predict: 'અનુમાન',
    manual_hint: 'રેખાને એવી રીતે ખસેડો કે લાલ ભૂલ-રેખાઓ બને એટલી નાની થાય. લૉસ ઘટતો જુઓ.',
    slope: 'ઢાળ m (નમણ)',
    slope_hint: 'x 1 વધે ત્યારે y કેટલો બદલાય છે.',
    intercept: 'અંતઃખંડ c',
    intercept_hint: 'રેખા x = 0 ને જ્યાં મળે ત્યાં y ની કિંમત.',
    reset_line: 'ફરી સપાટ રેખા',
    coach_m0: 'રેખા બિંદુઓથી ઘણી દૂર છે. ગોળ હૅન્ડલ કે ઢાળ સ્લાઇડરથી તેને નમાવો.',
    coach_m1: 'નજીક આવી રહ્યા છો! રેખાની બંને બાજુની લાલ રેખાઓ નાની કરો.',
    coach_m2: 'ખૂબ નજીક. m અને c માં નાના ફેરફારથી બાકીનો લૉસ પણ ઘટશે.',
    coach_m3: 'શાબાશ! તમારી રેખા લગભગ શ્રેષ્ઠ રેખા છે. હવે "AIને શીખવા દો" સાથે સરખાવો.',
    need_points: 'જુદા જુદા x વાળા ઓછામાં ઓછા 2 બિંદુ ઉમેરો.',
    same_x: 'બધા બિંદુઓનો x સરખો છે, તેથી કોઈ ત્રાંસી રેખા મળી શકે નહીં. એક બિંદુને બાજુમાં ખસેડો.',
    exact_title: 'ચોક્કસ જવાબ (લઘુતમ વર્ગ પદ્ધતિ)',
    exact_hint: 'સીધી રેખા માટે એક સૂત્ર એક જ વારમાં શ્રેષ્ઠ m અને c શોધી આપે છે.',
    exact_btn: 'શ્રેષ્ઠ રેખા શોધો',
    follow: 'બિંદુ ખસેડું ત્યારે શ્રેષ્ઠ રેખા જાળવી રાખો',
    show_math: 'ગણતરી બતાવો',
    gd_title: 'ગ્રેડિયન્ટ ડિસેન્ટ: AI કેવી રીતે શીખે છે',
    gd_hint: 'AI સપાટ રેખાથી શરૂ કરે છે. દરેક એપૉકમાં તે બધા બિંદુ જુએ છે અને m તથા c ને લૉસના ઢાળ પર થોડા નીચે તરફ ખસેડે છે.',
    lr_label: 'લર્નિંગ રેટ (પગલાનું કદ)',
    lr_tiny: 'બહુ નાનું: સલામત, પણ બહુ ધીમું.',
    lr_small: 'નાનું: સ્થિર, પણ ધીમું.',
    lr_good: 'સારું: ઝડપી અને સ્થિર.',
    lr_big: 'બહુ મોટું: પગલાં આગળ નીકળી જાય છે અને લૉસ ફાટી શકે છે!',
    epochs_label: 'એક વારમાં એપૉક',
    speed_label: 'ઝડપ',
    speed_slow: 'ધીમી',
    speed_normal: 'સામાન્ય',
    speed_fast: 'ઝડપી',
    gd_step: 'એક પગલું',
    gd_run: 'ચલાવો',
    gd_restart: 'ફરી શરૂ',
    epoch_label: 'એપૉક',
    best_possible: 'શક્ય સૌથી ઓછો',
    loss_chart: 'લૉસ વક્ર: દરેક એપૉક પછીનો લૉસ',
    chart_empty: 'લૉસ ઘટતો જોવા "એક પગલું" કે "ચલાવો" દબાવો.',
    coach_gd_need: 'પહેલાં જુદા જુદા x વાળા ઓછામાં ઓછા 2 બિંદુ ઉમેરો.',
    coach_gd_explode: 'લૉસ ફાટી ગયો! લર્નિંગ રેટ બહુ મોટું છે. નાનું પસંદ કરી "ફરી શરૂ" દબાવો.',
    coach_gd_up: 'લૉસ વધી રહ્યો છે: દરેક પગલું ખીણ કૂદી જાય છે. લર્નિંગ રેટ ઘટાડો.',
    coach_gd_done: 'શીખવાનું પૂરું! હવે લૉસ લગભગ શક્ય સૌથી ઓછા લૉસ જેટલો છે.',
    coach_gd_running: 'શીખી રહ્યું છે… રેખા ખસતી અને લૉસ વક્ર નીચે જતો જુઓ.',
    coach_gd_idle: 'એક ફેરફાર જોવા "એક પગલું" દબાવો, ઘણા એપૉક જોવા "ચલાવો".',
    coach_gd_slow: 'લૉસ ઘટે છે, પણ ધીમે, કારણ કે લર્નિંગ રેટ નાનું છે. વધુ એપૉક ચલાવો કે રેટ વધારો.',
    coach_gd_progress: 'લૉસ ઘટી રહ્યો છે. શીખવાનું ચાલુ રાખવા ફરી "ચલાવો" દબાવો.',
    pred_title: 'નવી કિંમતનું અનુમાન',
    pred_hint: 'x પસંદ કરો કે ગ્રાફ પર ટૅપ કરો. રેખા અનુમાન આપે છે: ŷ = m × x + c',
    pred_answer: 'અનુમાન ŷ',
    pred_outside: 'સાવધાન: આ x ડેટાની મર્યાદા ({a} થી {b}) ની બહાર છે. ડેટાથી દૂરના અનુમાન બહુ ખોટા પડી શકે.',
    pred_negative: 'રેખા શૂન્યથી ઓછી કિંમત બતાવે છે, જે અહીં અશક્ય છે. સીધી રેખા બધું સમજાવી શકતી નથી.',
    pred_tip_best: 'સૂચન: આ રેખા હજુ શ્રેષ્ઠ નથી. સારા અનુમાન માટે "AIને શીખવા દો" ખોલીને "શ્રેષ્ઠ રેખા શોધો" દબાવો.',
    explain_title: 'સમજો',
    exp_title: 'એક પ્રયોગ કરી જુઓ',
    exp_outlier: '📍 એક આઉટલાયર ઉમેરો',
    exp_small: '🐢 લર્નિંગ રેટ બહુ નાનું',
    exp_right: '👍 લર્નિંગ રેટ બરાબર',
    exp_big: '💥 લર્નિંગ રેટ બહુ મોટું',
    exp_outlier_msg: 'બાકીનાથી ઘણો દૂર એક અનોખો બિંદુ ઉમેર્યો છે. રાખોડી તૂટક રેખા પહેલાંની શ્રેષ્ઠ રેખા હતી; નવી શ્રેષ્ઠ રેખા આઉટલાયર તરફ ખેંચાઈ ગઈ છે. એ બિંદુને ખેંચીને જુઓ કે એક બિંદુ મૉડલને કેટલું બદલી શકે.',
    exp_small_msg: 'લર્નિંગ રેટ 0.01: દરેક પગલું બહુ નાનું છે, એટલે 200 એપૉક પછી પણ રેખા શ્રેષ્ઠ જગ્યાએ પહોંચી નથી. લૉસ વક્ર કેટલો ધીમે ઊતરે છે તે જુઓ.',
    exp_right_msg: 'લર્નિંગ રેટ 0.6: લૉસ ઝડપથી ઘટે છે અને રેખા શ્રેષ્ઠ જગ્યાએ સ્થિર થાય છે.',
    exp_big_msg: 'લર્નિંગ રેટ 1.5: દરેક પગલું ખીણ કૂદીને બીજી બાજુ વધુ ઊંચે પહોંચે છે. લૉસ ઘટવાને બદલે ફાટી જાય છે.',
    table_title: 'ડેટા કોઠો અને ભૂલો',
    add_row: 'હાર ઉમેરો',
    dl_csv: 'CSV ડાઉનલોડ કરો',
    col_pred: 'અનુમાનિત ŷ',
    col_err: 'ભૂલ y − ŷ',
    col_sq: 'ભૂલનો વર્ગ',
    del_row: 'હાર {n} કાઢો',
    mse_line: 'ભૂલોના વર્ગનો સરવાળો = {s}. તેને {n} બિંદુથી ભાગો: MSE = {v}.',
    own_empty: 'બિંદુ ઉમેરવા ગ્રાફ પર ટૅપ કરો.',
    max_points: 'વધુમાં વધુ {n} બિંદુ.',
    kept_inside: 'કિંમત ગ્રાફની અંદર જ રાખી.',
    paste_title: 'તમારો ડેટા પેસ્ટ કરો',
    paste_hint: 'સંખ્યાના બે કૉલમ (x અને y) પેસ્ટ કરો, દરેક લાઇનમાં એક જોડી. Excel કે Google Sheets માંથી કૉપી કરો, અથવા આમ લખો: 150, 152',
    paste_xname: 'x નું નામ (મરજિયાત)',
    paste_yname: 'y નું નામ (મરજિયાત)',
    paste_go: 'આ ડેટા વાપરો',
    paste_bad: 'સંખ્યાની કોઈ જોડી મળી નહીં. દરેક લાઇનમાં બે સંખ્યા લખો.',
    paste_ok: '{n} બિંદુ ઉમેર્યા.',
    before_label: 'પહેલાં',
    best_label: 'શ્રેષ્ઠ',
    err_word: 'ભૂલ',
    graph_aria: '{n} બિંદુનો ગ્રાફ: આડો {x} અને ઊભો {y}, સાથે મૉડલ રેખા.',
    points_n: '{n} બિંદુ',
    canvas_hint_manual: 'રેખા નમાવવા ગોળ હૅન્ડલ ખેંચો, અથવા રેખાને ઉપર-નીચે ખેંચો. ખાલી જગ્યાએ ટૅપ કરી બિંદુ ઉમેરો, ખેંચીને ખસેડો, બે વાર ટૅપ કરી કાઢો.',
    canvas_hint_auto: 'ટૅપ કરી બિંદુ ઉમેરો, ખેંચીને ખસેડો, બે વાર ટૅપ કરી કાઢો. પછી AIને ફરી શીખવા દો.',
    canvas_hint_predict: 'અનુમાન માટે x પસંદ કરવા ગ્રાફ પર ક્યાંય પણ ટૅપ કરો.',
    ws_title: 'વર્કશીટ: શ્રેષ્ઠ બંધબેસતી રેખા',
    ws_name: 'નામ: ______________   ધોરણ: ______   તારીખ: __________',
    ws_q1: 'ઉપરના ગ્રાફની રેખાનું સમીકરણ લખો. આ ડેટા માટે m અને c નો અર્થ શું છે?',
    ws_q2: 'કોઈ પણ બે બિંદુ પસંદ કરો. દરેકની ભૂલ (y − ŷ) અને ભૂલનો વર્ગ શોધો.',
    ws_q3: 'રેખાની મદદથી x = {x} હોય ત્યારે y નું અનુમાન કરો. ગણતરી બતાવો.',
    ws_q4: 'આપણે ભૂલોને સીધી ઉમેરવાને બદલે તેમનો વર્ગ કેમ કરીએ છીએ?',
    ws_q5: 'ગ્રેડિયન્ટ ડિસેન્ટમાં લર્નિંગ રેટ બહુ મોટું હોય તો શું થાય? બહુ નાનું હોય તો?',
    howto: 'કેવી રીતે વાપરવું / વર્ગખંડ માટે વિચારો',
    tip1: '"હાથથી બેસાડો" થી શરૂ કરો: લૉસ બને એટલો ઓછો થાય ત્યાં સુધી રેખા ખેંચો. પછી સરખામણી માટે "શ્રેષ્ઠ રેખા" ચાલુ કરો.',
    tip2: '"ભૂલોના વર્ગ" ચાલુ કરો: ચોરસ બતાવે છે કે એક મોટી ચૂક ઘણી નાની ચૂકો કરતાં કેમ ઘણી વધારે ગણાય છે.',
    tip3: '"AIને શીખવા દો" ખોલી "ચલાવો" દબાવો. નીચે ઊતરતો લૉસ વક્ર એ જ "ટ્રેનિંગ" છે. પછી લર્નિંગ રેટના પ્રયોગો કરી જુઓ.',
    tip4: 'વર્ગ પ્રવૃત્તિ: 10–15 સહપાઠીઓની ઊંચાઈ અને હાથનો ફેલાવો માપો, "ડેટા પેસ્ટ કરો" થી ઉમેરો, અને નવા વિદ્યાર્થીના ફેલાવાનું અનુમાન કરો.',
    tip5: '"અનુમાન" વડે ચર્ચા કરો: અઠવાડિયે 40 કલાક વાંચનારના ગુણ રેખા કહી શકે? કેમ નહીં?',
    tip6: 'પ્રિન્ટ કરવાથી ગ્રાફ, ડેટા કોઠો અને 5 પ્રશ્નોવાળી વર્કશીટ મળે છે. સ્માર્ટબોર્ડ પર ફુલસ્ક્રીન સરસ ચાલે છે.'
  },

  pa: {
    app_title: 'ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ',
    intro: 'ਦੇਖੋ AI ਡਾਟਾ ਤੋਂ ਇੱਕ ਸਿੱਧੀ ਰੇਖਾ ਕਿਵੇਂ ਸਿੱਖਦਾ ਹੈ: ਗਲਤੀ, ਲੌਸ, ਗ੍ਰੇਡੀਅੰਟ ਡਿਸੈਂਟ ਅਤੇ ਅਨੁਮਾਨ।',
    data_label: 'ਡਾਟਾ',
    restore: 'ਡਾਟਾ ਵਾਪਸ ਲਿਆਓ',
    clear_dots: 'ਬਿੰਦੂ ਮਿਟਾਓ',
    restored: 'ਅਸਲ ਡਾਟਾ ਵਾਪਸ ਆ ਗਿਆ।',
    confirm_clear: 'ਆਪਣੇ ਸਾਰੇ ਬਿੰਦੂ ਹਟਾ ਦੇਈਏ?',
    paste_btn: 'ਡਾਟਾ ਪੇਸਟ ਕਰੋ',
    show_label: 'ਦਿਖਾਓ:',
    show_res: 'ਗਲਤੀਆਂ',
    show_sq: 'ਗਲਤੀਆਂ ਦੇ ਵਰਗ',
    show_best: 'ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ',
    eq_label: 'ਮਾਡਲ (ਰੇਖਾ)',
    loss_label: 'ਲੌਸ (MSE)',
    miss: 'ਆਮ ਤੌਰ ’ਤੇ ਖੁੰਝ ≈ {v}',
    closeness: 'ਸਭ ਤੋਂ ਵਧੀਆ ਦੇ ਕਿੰਨਾ ਨੇੜੇ',
    tab_manual: 'ਹੱਥ ਨਾਲ ਬਿਠਾਓ',
    tab_auto: 'AI ਨੂੰ ਸਿੱਖਣ ਦਿਓ',
    tab_predict: 'ਅਨੁਮਾਨ',
    manual_hint: 'ਰੇਖਾ ਨੂੰ ਇਸ ਤਰ੍ਹਾਂ ਖਿਸਕਾਓ ਕਿ ਲਾਲ ਗਲਤੀ-ਲਾਈਨਾਂ ਜਿੰਨੀਆਂ ਹੋ ਸਕਣ ਛੋਟੀਆਂ ਹੋ ਜਾਣ। ਲੌਸ ਨੂੰ ਘਟਦਾ ਦੇਖੋ।',
    slope: 'ਢਲਾਣ m (ਝੁਕਾਅ)',
    slope_hint: 'x ਦੇ 1 ਵਧਣ ’ਤੇ y ਕਿੰਨਾ ਬਦਲਦਾ ਹੈ।',
    intercept: 'ਅੰਤਰ-ਖੰਡ c',
    intercept_hint: 'ਜਿੱਥੇ ਰੇਖਾ x = 0 ’ਤੇ ਮਿਲਦੀ ਹੈ, ਉੱਥੇ y ਦਾ ਮੁੱਲ।',
    reset_line: 'ਫਿਰ ਸਪਾਟ ਰੇਖਾ',
    coach_m0: 'ਰੇਖਾ ਬਿੰਦੂਆਂ ਤੋਂ ਬਹੁਤ ਦੂਰ ਹੈ। ਗੋਲ ਹੈਂਡਲ ਜਾਂ ਢਲਾਣ ਸਲਾਈਡਰ ਨਾਲ ਇਸਨੂੰ ਝੁਕਾਓ।',
    coach_m1: 'ਨੇੜੇ ਆ ਰਹੇ ਹੋ! ਰੇਖਾ ਦੇ ਦੋਵੇਂ ਪਾਸੇ ਲਾਲ ਲਾਈਨਾਂ ਛੋਟੀਆਂ ਕਰੋ।',
    coach_m2: 'ਬਹੁਤ ਨੇੜੇ। m ਅਤੇ c ਵਿੱਚ ਛੋਟੇ ਬਦਲਾਅ ਨਾਲ ਬਚਿਆ ਲੌਸ ਵੀ ਘਟ ਜਾਵੇਗਾ।',
    coach_m3: 'ਸ਼ਾਬਾਸ਼! ਤੁਹਾਡੀ ਰੇਖਾ ਲਗਭਗ ਸਭ ਤੋਂ ਵਧੀਆ ਹੈ। ਹੁਣ "AI ਨੂੰ ਸਿੱਖਣ ਦਿਓ" ਨਾਲ ਮਿਲਾਓ।',
    need_points: 'ਵੱਖ-ਵੱਖ x ਵਾਲੇ ਘੱਟੋ-ਘੱਟ 2 ਬਿੰਦੂ ਜੋੜੋ।',
    same_x: 'ਸਾਰੇ ਬਿੰਦੂਆਂ ਦਾ x ਇੱਕੋ ਹੈ, ਇਸ ਲਈ ਕੋਈ ਤਿਰਛੀ ਰੇਖਾ ਨਹੀਂ ਮਿਲ ਸਕਦੀ। ਇੱਕ ਬਿੰਦੂ ਨੂੰ ਪਾਸੇ ਖਿਸਕਾਓ।',
    exact_title: 'ਸਹੀ ਜਵਾਬ (ਘੱਟੋ-ਘੱਟ ਵਰਗ ਵਿਧੀ)',
    exact_hint: 'ਸਿੱਧੀ ਰੇਖਾ ਲਈ ਇੱਕ ਫ਼ਾਰਮੂਲਾ ਇੱਕੋ ਵਾਰ ਵਿੱਚ ਸਭ ਤੋਂ ਵਧੀਆ m ਅਤੇ c ਲੱਭ ਦਿੰਦਾ ਹੈ।',
    exact_btn: 'ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ ਲੱਭੋ',
    follow: 'ਬਿੰਦੂ ਖਿਸਕਾਉਂਦੇ ਸਮੇਂ ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ ਬਣਾਈ ਰੱਖੋ',
    show_math: 'ਹਿਸਾਬ ਦਿਖਾਓ',
    gd_title: 'ਗ੍ਰੇਡੀਅੰਟ ਡਿਸੈਂਟ: AI ਕਿਵੇਂ ਸਿੱਖਦਾ ਹੈ',
    gd_hint: 'AI ਇੱਕ ਸਪਾਟ ਰੇਖਾ ਨਾਲ ਸ਼ੁਰੂ ਕਰਦਾ ਹੈ। ਹਰ ਐਪੌਕ ਵਿੱਚ ਉਹ ਸਾਰੇ ਬਿੰਦੂ ਦੇਖਦਾ ਹੈ ਅਤੇ m ਤੇ c ਨੂੰ ਲੌਸ ਦੀ ਢਲਾਣ ’ਤੇ ਥੋੜ੍ਹਾ ਹੇਠਾਂ ਵੱਲ ਖਿਸਕਾਉਂਦਾ ਹੈ।',
    lr_label: 'ਲਰਨਿੰਗ ਰੇਟ (ਕਦਮ ਦਾ ਆਕਾਰ)',
    lr_tiny: 'ਬਹੁਤ ਛੋਟਾ: ਸੁਰੱਖਿਅਤ, ਪਰ ਬਹੁਤ ਹੌਲੀ।',
    lr_small: 'ਛੋਟਾ: ਟਿਕਿਆ ਹੋਇਆ, ਪਰ ਹੌਲੀ।',
    lr_good: 'ਵਧੀਆ: ਤੇਜ਼ ਅਤੇ ਟਿਕਿਆ ਹੋਇਆ।',
    lr_big: 'ਬਹੁਤ ਵੱਡਾ: ਕਦਮ ਅੱਗੇ ਲੰਘ ਜਾਂਦੇ ਹਨ ਅਤੇ ਲੌਸ ਫਟ ਸਕਦਾ ਹੈ!',
    epochs_label: 'ਇੱਕ ਵਾਰ ਵਿੱਚ ਐਪੌਕ',
    speed_label: 'ਰਫ਼ਤਾਰ',
    speed_slow: 'ਹੌਲੀ',
    speed_normal: 'ਆਮ',
    speed_fast: 'ਤੇਜ਼',
    gd_step: 'ਇੱਕ ਕਦਮ',
    gd_run: 'ਚਲਾਓ',
    gd_restart: 'ਮੁੜ ਸ਼ੁਰੂ',
    epoch_label: 'ਐਪੌਕ',
    best_possible: 'ਸਭ ਤੋਂ ਘੱਟ ਸੰਭਵ',
    loss_chart: 'ਲੌਸ ਵਕਰ: ਹਰ ਐਪੌਕ ਤੋਂ ਬਾਅਦ ਦਾ ਲੌਸ',
    chart_empty: 'ਲੌਸ ਨੂੰ ਘਟਦਾ ਦੇਖਣ ਲਈ "ਇੱਕ ਕਦਮ" ਜਾਂ "ਚਲਾਓ" ਦਬਾਓ।',
    coach_gd_need: 'ਪਹਿਲਾਂ ਵੱਖ-ਵੱਖ x ਵਾਲੇ ਘੱਟੋ-ਘੱਟ 2 ਬਿੰਦੂ ਜੋੜੋ।',
    coach_gd_explode: 'ਲੌਸ ਫਟ ਗਿਆ! ਲਰਨਿੰਗ ਰੇਟ ਬਹੁਤ ਵੱਡਾ ਹੈ। ਛੋਟਾ ਚੁਣੋ ਅਤੇ "ਮੁੜ ਸ਼ੁਰੂ" ਦਬਾਓ।',
    coach_gd_up: 'ਲੌਸ ਵਧ ਰਿਹਾ ਹੈ: ਹਰ ਕਦਮ ਵਾਦੀ ਦੇ ਪਾਰ ਛਾਲ ਮਾਰ ਰਿਹਾ ਹੈ। ਲਰਨਿੰਗ ਰੇਟ ਘਟਾਓ।',
    coach_gd_done: 'ਸਿੱਖਣਾ ਪੂਰਾ! ਹੁਣ ਲੌਸ ਲਗਭਗ ਸਭ ਤੋਂ ਘੱਟ ਸੰਭਵ ਲੌਸ ਦੇ ਬਰਾਬਰ ਹੈ।',
    coach_gd_running: 'ਸਿੱਖ ਰਿਹਾ ਹੈ… ਰੇਖਾ ਨੂੰ ਖਿਸਕਦਾ ਅਤੇ ਲੌਸ ਵਕਰ ਨੂੰ ਡਿੱਗਦਾ ਦੇਖੋ।',
    coach_gd_idle: 'ਇੱਕ ਬਦਲਾਅ ਦੇਖਣ ਲਈ "ਇੱਕ ਕਦਮ" ਦਬਾਓ, ਜਾਂ ਕਈ ਐਪੌਕ ਦੇਖਣ ਲਈ "ਚਲਾਓ"।',
    coach_gd_slow: 'ਲੌਸ ਘਟ ਰਿਹਾ ਹੈ, ਪਰ ਹੌਲੀ, ਕਿਉਂਕਿ ਲਰਨਿੰਗ ਰੇਟ ਛੋਟਾ ਹੈ। ਹੋਰ ਐਪੌਕ ਚਲਾਓ ਜਾਂ ਰੇਟ ਵਧਾਓ।',
    coach_gd_progress: 'ਲੌਸ ਘਟ ਰਿਹਾ ਹੈ। ਸਿੱਖਦੇ ਰਹਿਣ ਲਈ ਫਿਰ "ਚਲਾਓ" ਦਬਾਓ।',
    pred_title: 'ਨਵੇਂ ਮੁੱਲ ਦਾ ਅਨੁਮਾਨ',
    pred_hint: 'x ਚੁਣੋ ਜਾਂ ਗ੍ਰਾਫ਼ ’ਤੇ ਟੈਪ ਕਰੋ। ਰੇਖਾ ਅਨੁਮਾਨ ਦਿੰਦੀ ਹੈ: ŷ = m × x + c',
    pred_answer: 'ਅਨੁਮਾਨ ŷ',
    pred_outside: 'ਸਾਵਧਾਨ: ਇਹ x ਡਾਟਾ ਦੀ ਹੱਦ ({a} ਤੋਂ {b}) ਤੋਂ ਬਾਹਰ ਹੈ। ਡਾਟਾ ਤੋਂ ਦੂਰ ਦੇ ਅਨੁਮਾਨ ਬਹੁਤ ਗਲਤ ਹੋ ਸਕਦੇ ਹਨ।',
    pred_negative: 'ਰੇਖਾ ਸਿਫ਼ਰ ਤੋਂ ਘੱਟ ਮੁੱਲ ਦੱਸ ਰਹੀ ਹੈ, ਜੋ ਇੱਥੇ ਅਸੰਭਵ ਹੈ। ਸਿੱਧੀ ਰੇਖਾ ਹਰ ਚੀਜ਼ ਨਹੀਂ ਸਮਝਾ ਸਕਦੀ।',
    pred_tip_best: 'ਸੁਝਾਅ: ਇਹ ਰੇਖਾ ਅਜੇ ਸਭ ਤੋਂ ਵਧੀਆ ਨਹੀਂ। ਬਿਹਤਰ ਅਨੁਮਾਨ ਲਈ "AI ਨੂੰ ਸਿੱਖਣ ਦਿਓ" ਖੋਲ੍ਹ ਕੇ "ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ ਲੱਭੋ" ਦਬਾਓ।',
    explain_title: 'ਇਸਨੂੰ ਸਮਝੋ',
    exp_title: 'ਇੱਕ ਪ੍ਰਯੋਗ ਕਰਕੇ ਦੇਖੋ',
    exp_outlier: '📍 ਇੱਕ ਆਊਟਲਾਇਰ ਜੋੜੋ',
    exp_small: '🐢 ਲਰਨਿੰਗ ਰੇਟ ਬਹੁਤ ਛੋਟਾ',
    exp_right: '👍 ਲਰਨਿੰਗ ਰੇਟ ਬਿਲਕੁਲ ਸਹੀ',
    exp_big: '💥 ਲਰਨਿੰਗ ਰੇਟ ਬਹੁਤ ਵੱਡਾ',
    exp_outlier_msg: 'ਬਾਕੀਆਂ ਤੋਂ ਬਹੁਤ ਦੂਰ ਇੱਕ ਅਨੋਖਾ ਬਿੰਦੂ ਜੋੜਿਆ ਗਿਆ ਹੈ। ਸਲੇਟੀ ਡੈਸ਼ ਵਾਲੀ ਰੇਖਾ ਪਹਿਲਾਂ ਦੀ ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ ਸੀ; ਨਵੀਂ ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ ਆਊਟਲਾਇਰ ਵੱਲ ਖਿੱਚੀ ਗਈ ਹੈ। ਉਸ ਬਿੰਦੂ ਨੂੰ ਖਿੱਚ ਕੇ ਦੇਖੋ ਕਿ ਇੱਕ ਬਿੰਦੂ ਮਾਡਲ ਨੂੰ ਕਿੰਨਾ ਬਦਲ ਸਕਦਾ ਹੈ।',
    exp_small_msg: 'ਲਰਨਿੰਗ ਰੇਟ 0.01: ਹਰ ਕਦਮ ਬਹੁਤ ਛੋਟਾ ਹੈ, ਇਸ ਲਈ 200 ਐਪੌਕ ਬਾਅਦ ਵੀ ਰੇਖਾ ਸਭ ਤੋਂ ਵਧੀਆ ਥਾਂ ਨਹੀਂ ਪਹੁੰਚੀ। ਦੇਖੋ ਲੌਸ ਵਕਰ ਕਿੰਨਾ ਹੌਲੀ ਡਿੱਗਦਾ ਹੈ।',
    exp_right_msg: 'ਲਰਨਿੰਗ ਰੇਟ 0.6: ਲੌਸ ਤੇਜ਼ੀ ਨਾਲ ਘਟਦਾ ਹੈ ਅਤੇ ਰੇਖਾ ਸਭ ਤੋਂ ਵਧੀਆ ਥਾਂ ’ਤੇ ਟਿਕ ਜਾਂਦੀ ਹੈ।',
    exp_big_msg: 'ਲਰਨਿੰਗ ਰੇਟ 1.5: ਹਰ ਕਦਮ ਵਾਦੀ ਦੇ ਪਾਰ ਛਾਲ ਮਾਰ ਕੇ ਦੂਜੇ ਪਾਸੇ ਹੋਰ ਉੱਚਾ ਪਹੁੰਚਦਾ ਹੈ। ਲੌਸ ਘਟਣ ਦੀ ਥਾਂ ਫਟ ਜਾਂਦਾ ਹੈ।',
    table_title: 'ਡਾਟਾ ਸਾਰਣੀ ਅਤੇ ਗਲਤੀਆਂ',
    add_row: 'ਕਤਾਰ ਜੋੜੋ',
    dl_csv: 'CSV ਡਾਊਨਲੋਡ ਕਰੋ',
    col_pred: 'ਅਨੁਮਾਨਿਤ ŷ',
    col_err: 'ਗਲਤੀ y − ŷ',
    col_sq: 'ਗਲਤੀ ਦਾ ਵਰਗ',
    del_row: 'ਕਤਾਰ {n} ਹਟਾਓ',
    mse_line: 'ਗਲਤੀਆਂ ਦੇ ਵਰਗਾਂ ਦਾ ਜੋੜ = {s}। ਇਸਨੂੰ {n} ਬਿੰਦੂਆਂ ਨਾਲ ਭਾਗ ਦਿਓ: MSE = {v}।',
    own_empty: 'ਬਿੰਦੂ ਜੋੜਨ ਲਈ ਗ੍ਰਾਫ਼ ’ਤੇ ਟੈਪ ਕਰੋ।',
    max_points: 'ਵੱਧ ਤੋਂ ਵੱਧ {n} ਬਿੰਦੂ।',
    kept_inside: 'ਮੁੱਲ ਗ੍ਰਾਫ਼ ਦੇ ਅੰਦਰ ਹੀ ਰੱਖਿਆ ਗਿਆ।',
    paste_title: 'ਆਪਣਾ ਡਾਟਾ ਪੇਸਟ ਕਰੋ',
    paste_hint: 'ਸੰਖਿਆਵਾਂ ਦੇ ਦੋ ਕਾਲਮ (x ਅਤੇ y) ਪੇਸਟ ਕਰੋ, ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ ਜੋੜੀ। Excel ਜਾਂ Google Sheets ਤੋਂ ਕਾਪੀ ਕਰੋ, ਜਾਂ ਇਉਂ ਲਿਖੋ: 150, 152',
    paste_xname: 'x ਦਾ ਨਾਮ (ਜ਼ਰੂਰੀ ਨਹੀਂ)',
    paste_yname: 'y ਦਾ ਨਾਮ (ਜ਼ਰੂਰੀ ਨਹੀਂ)',
    paste_go: 'ਇਹ ਡਾਟਾ ਵਰਤੋ',
    paste_bad: 'ਸੰਖਿਆਵਾਂ ਦੀ ਕੋਈ ਜੋੜੀ ਨਹੀਂ ਮਿਲੀ। ਹਰ ਲਾਈਨ ਵਿੱਚ ਦੋ ਸੰਖਿਆਵਾਂ ਲਿਖੋ।',
    paste_ok: '{n} ਬਿੰਦੂ ਜੋੜੇ ਗਏ।',
    before_label: 'ਪਹਿਲਾਂ',
    best_label: 'ਸਭ ਤੋਂ ਵਧੀਆ',
    err_word: 'ਗਲਤੀ',
    graph_aria: '{n} ਬਿੰਦੂਆਂ ਦਾ ਗ੍ਰਾਫ਼: ਲੇਟਵਾਂ {x} ਅਤੇ ਖੜ੍ਹਵਾਂ {y}, ਨਾਲ ਮਾਡਲ ਰੇਖਾ।',
    points_n: '{n} ਬਿੰਦੂ',
    canvas_hint_manual: 'ਰੇਖਾ ਝੁਕਾਉਣ ਲਈ ਗੋਲ ਹੈਂਡਲ ਖਿੱਚੋ, ਜਾਂ ਰੇਖਾ ਨੂੰ ਉੱਪਰ-ਹੇਠਾਂ ਖਿੱਚੋ। ਖਾਲੀ ਥਾਂ ਟੈਪ ਕਰਕੇ ਬਿੰਦੂ ਜੋੜੋ, ਖਿੱਚ ਕੇ ਖਿਸਕਾਓ, ਦੋ ਵਾਰ ਟੈਪ ਕਰਕੇ ਹਟਾਓ।',
    canvas_hint_auto: 'ਟੈਪ ਕਰਕੇ ਬਿੰਦੂ ਜੋੜੋ, ਖਿੱਚ ਕੇ ਖਿਸਕਾਓ, ਦੋ ਵਾਰ ਟੈਪ ਕਰਕੇ ਹਟਾਓ। ਫਿਰ AI ਨੂੰ ਦੁਬਾਰਾ ਸਿੱਖਣ ਦਿਓ।',
    canvas_hint_predict: 'ਅਨੁਮਾਨ ਲਈ x ਚੁਣਨ ਵਾਸਤੇ ਗ੍ਰਾਫ਼ ’ਤੇ ਕਿਤੇ ਵੀ ਟੈਪ ਕਰੋ।',
    ws_title: 'ਵਰਕਸ਼ੀਟ: ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ',
    ws_name: 'ਨਾਮ: ______________   ਜਮਾਤ: ______   ਤਾਰੀਖ਼: __________',
    ws_q1: 'ਉੱਪਰਲੇ ਗ੍ਰਾਫ਼ ਵਾਲੀ ਰੇਖਾ ਦਾ ਸਮੀਕਰਨ ਲਿਖੋ। ਇਸ ਡਾਟਾ ਲਈ m ਅਤੇ c ਦਾ ਕੀ ਮਤਲਬ ਹੈ?',
    ws_q2: 'ਕੋਈ ਦੋ ਬਿੰਦੂ ਚੁਣੋ। ਹਰੇਕ ਦੀ ਗਲਤੀ (y − ŷ) ਅਤੇ ਗਲਤੀ ਦਾ ਵਰਗ ਕੱਢੋ।',
    ws_q3: 'ਰੇਖਾ ਨਾਲ x = {x} ਹੋਣ ’ਤੇ y ਦਾ ਅਨੁਮਾਨ ਲਗਾਓ। ਆਪਣਾ ਹਿਸਾਬ ਦਿਖਾਓ।',
    ws_q4: 'ਅਸੀਂ ਗਲਤੀਆਂ ਨੂੰ ਸਿੱਧਾ ਜੋੜਨ ਦੀ ਥਾਂ ਉਹਨਾਂ ਦਾ ਵਰਗ ਕਿਉਂ ਕਰਦੇ ਹਾਂ?',
    ws_q5: 'ਗ੍ਰੇਡੀਅੰਟ ਡਿਸੈਂਟ ਵਿੱਚ ਲਰਨਿੰਗ ਰੇਟ ਬਹੁਤ ਵੱਡਾ ਹੋਵੇ ਤਾਂ ਕੀ ਹੁੰਦਾ ਹੈ? ਬਹੁਤ ਛੋਟਾ ਹੋਵੇ ਤਾਂ?',
    howto: 'ਕਿਵੇਂ ਵਰਤੀਏ / ਜਮਾਤ ਲਈ ਸੁਝਾਅ',
    tip1: '"ਹੱਥ ਨਾਲ ਬਿਠਾਓ" ਤੋਂ ਸ਼ੁਰੂ ਕਰੋ: ਰੇਖਾ ਨੂੰ ਉਦੋਂ ਤੱਕ ਖਿੱਚੋ ਜਦੋਂ ਤੱਕ ਲੌਸ ਜਿੰਨਾ ਹੋ ਸਕੇ ਘੱਟ ਨਾ ਹੋ ਜਾਵੇ। ਫਿਰ ਮਿਲਾਉਣ ਲਈ "ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਖਾ" ਚਾਲੂ ਕਰੋ।',
    tip2: '"ਗਲਤੀਆਂ ਦੇ ਵਰਗ" ਚਾਲੂ ਕਰੋ: ਡੱਬੇ ਦਿਖਾਉਂਦੇ ਹਨ ਕਿ ਇੱਕ ਵੱਡੀ ਖੁੰਝ ਕਈ ਛੋਟੀਆਂ ਖੁੰਝਾਂ ਨਾਲੋਂ ਕਿਤੇ ਵੱਧ ਕਿਉਂ ਗਿਣੀ ਜਾਂਦੀ ਹੈ।',
    tip3: '"AI ਨੂੰ ਸਿੱਖਣ ਦਿਓ" ਖੋਲ੍ਹ ਕੇ "ਚਲਾਓ" ਦਬਾਓ। ਡਿੱਗਦਾ ਲੌਸ ਵਕਰ ਹੀ "ਟ੍ਰੇਨਿੰਗ" ਹੈ। ਫਿਰ ਲਰਨਿੰਗ ਰੇਟ ਵਾਲੇ ਪ੍ਰਯੋਗ ਕਰਕੇ ਦੇਖੋ।',
    tip4: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: 10–15 ਸਹਿਪਾਠੀਆਂ ਦਾ ਕੱਦ ਅਤੇ ਬਾਹਾਂ ਦਾ ਫੈਲਾਅ ਮਾਪੋ, "ਡਾਟਾ ਪੇਸਟ ਕਰੋ" ਨਾਲ ਜੋੜੋ, ਅਤੇ ਨਵੇਂ ਵਿਦਿਆਰਥੀ ਦੇ ਫੈਲਾਅ ਦਾ ਅਨੁਮਾਨ ਲਗਾਓ।',
    tip5: '"ਅਨੁਮਾਨ" ਨਾਲ ਚਰਚਾ ਕਰੋ: ਕੀ ਰੇਖਾ ਹਫ਼ਤੇ ਵਿੱਚ 40 ਘੰਟੇ ਪੜ੍ਹਨ ਵਾਲੇ ਦੇ ਅੰਕ ਦੱਸ ਸਕਦੀ ਹੈ? ਕਿਉਂ ਨਹੀਂ?',
    tip6: 'ਪ੍ਰਿੰਟ ਕਰਨ ’ਤੇ ਗ੍ਰਾਫ਼, ਡਾਟਾ ਸਾਰਣੀ ਅਤੇ 5 ਸਵਾਲਾਂ ਵਾਲੀ ਵਰਕਸ਼ੀਟ ਮਿਲਦੀ ਹੈ। ਸਮਾਰਟਬੋਰਡ ’ਤੇ ਫੁੱਲਸਕ੍ਰੀਨ ਵਧੀਆ ਚੱਲਦੀ ਹੈ।'
  },

  or: {
    app_title: 'ସବୁଠୁ ଭଲ ରେଖା',
    intro: 'ଦେଖନ୍ତୁ AI କିପରି ଡାଟାରୁ ଏକ ସିଧା ରେଖା ଶିଖେ: ତ୍ରୁଟି, ଲସ୍, ଗ୍ରାଡିଏଣ୍ଟ ଡିସେଣ୍ଟ ଓ ଅନୁମାନ।',
    data_label: 'ଡାଟା',
    restore: 'ଡାଟା ଫେରାଇ ଆଣନ୍ତୁ',
    clear_dots: 'ବିନ୍ଦୁ ଲିଭାନ୍ତୁ',
    restored: 'ମୂଳ ଡାଟା ଫେରି ଆସିଲା।',
    confirm_clear: 'ଆପଣଙ୍କ ସବୁ ବିନ୍ଦୁ ହଟାଇବେ?',
    paste_btn: 'ଡାଟା ପେଷ୍ଟ କରନ୍ତୁ',
    show_label: 'ଦେଖାନ୍ତୁ:',
    show_res: 'ତ୍ରୁଟି',
    show_sq: 'ତ୍ରୁଟିର ବର୍ଗ',
    show_best: 'ସବୁଠୁ ଭଲ ରେଖା',
    eq_label: 'ମଡେଲ୍ (ରେଖା)',
    loss_label: 'ଲସ୍ (MSE)',
    miss: 'ସାଧାରଣ ଭୁଲ ≈ {v}',
    closeness: 'ସବୁଠୁ ଭଲର କେତେ ପାଖ',
    tab_manual: 'ହାତରେ ବସାନ୍ତୁ',
    tab_auto: 'AIକୁ ଶିଖିବାକୁ ଦିଅନ୍ତୁ',
    tab_predict: 'ଅନୁମାନ',
    manual_hint: 'ରେଖାକୁ ଏପରି ଘୁଞ୍ଚାନ୍ତୁ ଯେପରି ଲାଲ ତ୍ରୁଟି-ରେଖାଗୁଡ଼ିକ ଯେତେ ସମ୍ଭବ ଛୋଟ ହେବ। ଲସ୍ କମିବା ଦେଖନ୍ତୁ।',
    slope: 'ଢାଲ m (ଝୁଙ୍କ)',
    slope_hint: 'x 1 ବଢ଼ିଲେ y କେତେ ବଦଳେ।',
    intercept: 'ଅନ୍ତଃଖଣ୍ଡ c',
    intercept_hint: 'ରେଖା x = 0 ରେ ଯେଉଁଠି ମିଶେ, ସେଠାରେ y ର ମାନ।',
    reset_line: 'ପୁଣି ସମତଳ ରେଖା',
    coach_m0: 'ରେଖା ବିନ୍ଦୁଗୁଡ଼ିକଠାରୁ ବହୁତ ଦୂରରେ। ଗୋଲ ହ୍ୟାଣ୍ଡେଲ୍ ବା ଢାଲ ସ୍ଲାଇଡର୍‌ରେ ଏହାକୁ ଝୁଙ୍କାନ୍ତୁ।',
    coach_m1: 'ପାଖକୁ ଆସୁଛନ୍ତି! ରେଖାର ଦୁଇ ପଟର ଲାଲ ରେଖା ଛୋଟ କରନ୍ତୁ।',
    coach_m2: 'ବହୁତ ପାଖ। m ଓ c ରେ ଛୋଟ ବଦଳରେ ବାକି ଲସ୍ ବି କମିଯିବ।',
    coach_m3: 'ବାଃ! ଆପଣଙ୍କ ରେଖା ପ୍ରାୟ ସବୁଠୁ ଭଲ ରେଖା। ଏବେ "AIକୁ ଶିଖିବାକୁ ଦିଅନ୍ତୁ" ସହ ତୁଳନା କରନ୍ତୁ।',
    need_points: 'ଅଲଗା ଅଲଗା x ଥିବା ଅତି କମରେ 2ଟି ବିନ୍ଦୁ ଯୋଡ଼ନ୍ତୁ।',
    same_x: 'ସବୁ ବିନ୍ଦୁର x ସମାନ, ତେଣୁ କୌଣସି ତେରଛା ରେଖା ମିଳିପାରିବ ନାହିଁ। ଗୋଟିଏ ବିନ୍ଦୁକୁ କଡ଼କୁ ଘୁଞ୍ଚାନ୍ତୁ।',
    exact_title: 'ସଠିକ୍ ଉତ୍ତର (ସର୍ବନିମ୍ନ ବର୍ଗ ପଦ୍ଧତି)',
    exact_hint: 'ସିଧା ରେଖା ପାଇଁ ଗୋଟିଏ ସୂତ୍ର ଥରକେ ସବୁଠୁ ଭଲ m ଓ c ବାହାର କରେ।',
    exact_btn: 'ସବୁଠୁ ଭଲ ରେଖା ଖୋଜନ୍ତୁ',
    follow: 'ବିନ୍ଦୁ ଘୁଞ୍ଚାଇଲା ବେଳେ ସବୁଠୁ ଭଲ ରେଖା ରଖନ୍ତୁ',
    show_math: 'ହିସାବ ଦେଖାନ୍ତୁ',
    gd_title: 'ଗ୍ରାଡିଏଣ୍ଟ ଡିସେଣ୍ଟ: AI କିପରି ଶିଖେ',
    gd_hint: 'AI ଏକ ସମତଳ ରେଖାରୁ ଆରମ୍ଭ କରେ। ପ୍ରତି ଏପକ୍‌ରେ ଏହା ସବୁ ବିନ୍ଦୁ ଦେଖେ ଓ m ଏବଂ c କୁ ଲସ୍‌ର ଢାଲରେ ଟିକେ ତଳକୁ ଘୁଞ୍ଚାଏ।',
    lr_label: 'ଲର୍ଣ୍ଣିଂ ରେଟ୍ (ପାଦର ଆକାର)',
    lr_tiny: 'ବହୁତ ଛୋଟ: ସୁରକ୍ଷିତ, କିନ୍ତୁ ବହୁତ ଧୀର।',
    lr_small: 'ଛୋଟ: ସ୍ଥିର, କିନ୍ତୁ ଧୀର।',
    lr_good: 'ଭଲ: ଦ୍ରୁତ ଓ ସ୍ଥିର।',
    lr_big: 'ବହୁତ ବଡ଼: ପାଦ ଆଗକୁ ଚାଲିଯାଏ ଓ ଲସ୍ ଫାଟିପାରେ!',
    epochs_label: 'ଥରକେ କେତେ ଏପକ୍',
    speed_label: 'ବେଗ',
    speed_slow: 'ଧୀର',
    speed_normal: 'ସାଧାରଣ',
    speed_fast: 'ଦ୍ରୁତ',
    gd_step: 'ଗୋଟିଏ ପାଦ',
    gd_run: 'ଚଲାନ୍ତୁ',
    gd_restart: 'ପୁଣି ଆରମ୍ଭ',
    epoch_label: 'ଏପକ୍',
    best_possible: 'ସର୍ବନିମ୍ନ ସମ୍ଭବ',
    loss_chart: 'ଲସ୍ ବକ୍ର: ପ୍ରତି ଏପକ୍ ପରର ଲସ୍',
    chart_empty: 'ଲସ୍ କମିବା ଦେଖିବାକୁ "ଗୋଟିଏ ପାଦ" ବା "ଚଲାନ୍ତୁ" ଦବାନ୍ତୁ।',
    coach_gd_need: 'ପ୍ରଥମେ ଅଲଗା ଅଲଗା x ଥିବା ଅତି କମରେ 2ଟି ବିନ୍ଦୁ ଯୋଡ଼ନ୍ତୁ।',
    coach_gd_explode: 'ଲସ୍ ଫାଟିଗଲା! ଲର୍ଣ୍ଣିଂ ରେଟ୍ ବହୁତ ବଡ଼। ଛୋଟ ବାଛି "ପୁଣି ଆରମ୍ଭ" ଦବାନ୍ତୁ।',
    coach_gd_up: 'ଲସ୍ ବଢ଼ୁଛି: ପ୍ରତି ପାଦ ଉପତ୍ୟକା ଡେଇଁଯାଉଛି। ଲର୍ଣ୍ଣିଂ ରେଟ୍ କମାନ୍ତୁ।',
    coach_gd_done: 'ଶିଖିବା ସରିଲା! ଏବେ ଲସ୍ ପ୍ରାୟ ସର୍ବନିମ୍ନ ସମ୍ଭବ ଲସ୍ ସହ ସମାନ।',
    coach_gd_running: 'ଶିଖୁଛି… ରେଖାର ଘୁଞ୍ଚିବା ଓ ଲସ୍ ବକ୍ରର ଖସିବା ଦେଖନ୍ତୁ।',
    coach_gd_idle: 'ଗୋଟିଏ ବଦଳ ଦେଖିବାକୁ "ଗୋଟିଏ ପାଦ" ଦବାନ୍ତୁ, ଅନେକ ଏପକ୍ ଦେଖିବାକୁ "ଚଲାନ୍ତୁ"।',
    coach_gd_slow: 'ଲସ୍ କମୁଛି, କିନ୍ତୁ ଧୀରେ, କାରଣ ଲର୍ଣ୍ଣିଂ ରେଟ୍ ଛୋଟ। ଆହୁରି ଏପକ୍ ଚଲାନ୍ତୁ ବା ରେଟ୍ ବଢ଼ାନ୍ତୁ।',
    coach_gd_progress: 'ଲସ୍ କମୁଛି। ଶିଖିବା ଜାରି ରଖିବାକୁ ପୁଣି "ଚଲାନ୍ତୁ" ଦବାନ୍ତୁ।',
    pred_title: 'ନୂଆ ମାନର ଅନୁମାନ',
    pred_hint: 'x ବାଛନ୍ତୁ ବା ଗ୍ରାଫରେ ଟ୍ୟାପ୍ କରନ୍ତୁ। ରେଖା ଅନୁମାନ ଦିଏ: ŷ = m × x + c',
    pred_answer: 'ଅନୁମାନ ŷ',
    pred_outside: 'ସାବଧାନ: ଏହି x ଡାଟାର ସୀମା ({a} ରୁ {b}) ବାହାରେ। ଡାଟାଠାରୁ ଦୂରର ଅନୁମାନ ବହୁତ ଭୁଲ ହୋଇପାରେ।',
    pred_negative: 'ରେଖା ଶୂନ୍ୟରୁ କମ୍ ମାନ କହୁଛି, ଯାହା ଏଠାରେ ଅସମ୍ଭବ। ସିଧା ରେଖା ସବୁକିଛି ବୁଝାଇପାରେ ନାହିଁ।',
    pred_tip_best: 'ପରାମର୍ଶ: ଏହି ରେଖା ଏବେ ସବୁଠୁ ଭଲ ନୁହେଁ। ଭଲ ଅନୁମାନ ପାଇଁ "AIକୁ ଶିଖିବାକୁ ଦିଅନ୍ତୁ" ଖୋଲି "ସବୁଠୁ ଭଲ ରେଖା ଖୋଜନ୍ତୁ" ଦବାନ୍ତୁ।',
    explain_title: 'ବୁଝନ୍ତୁ',
    exp_title: 'ଗୋଟିଏ ପରୀକ୍ଷା କରି ଦେଖନ୍ତୁ',
    exp_outlier: '📍 ଗୋଟିଏ ଆଉଟଲାୟର ଯୋଡ଼ନ୍ତୁ',
    exp_small: '🐢 ଲର୍ଣ୍ଣିଂ ରେଟ୍ ବହୁତ ଛୋଟ',
    exp_right: '👍 ଲର୍ଣ୍ଣିଂ ରେଟ୍ ଠିକ୍',
    exp_big: '💥 ଲର୍ଣ୍ଣିଂ ରେଟ୍ ବହୁତ ବଡ଼',
    exp_outlier_msg: 'ବାକିମାନଙ୍କଠାରୁ ବହୁତ ଦୂରରେ ଏକ ଅଲଗା ବିନ୍ଦୁ ଯୋଡ଼ାଗଲା। ଧୂସର ଡ୍ୟାସ୍ ରେଖା ଆଗର ସବୁଠୁ ଭଲ ରେଖା ଥିଲା; ନୂଆ ସବୁଠୁ ଭଲ ରେଖା ଆଉଟଲାୟର ଆଡ଼କୁ ଟାଣି ହୋଇଗଲା। ସେହି ବିନ୍ଦୁକୁ ଟାଣି ଦେଖନ୍ତୁ, ଗୋଟିଏ ବିନ୍ଦୁ ମଡେଲକୁ କେତେ ବଦଳାଇପାରେ।',
    exp_small_msg: 'ଲର୍ଣ୍ଣିଂ ରେଟ୍ 0.01: ପ୍ରତି ପାଦ ବହୁତ ଛୋଟ, ତେଣୁ 200 ଏପକ୍ ପରେ ବି ରେଖା ସବୁଠୁ ଭଲ ସ୍ଥାନରେ ପହଞ୍ଚିନାହିଁ। ଲସ୍ ବକ୍ର କେତେ ଧୀରେ ଖସେ ଦେଖନ୍ତୁ।',
    exp_right_msg: 'ଲର୍ଣ୍ଣିଂ ରେଟ୍ 0.6: ଲସ୍ ଶୀଘ୍ର କମେ ଓ ରେଖା ସବୁଠୁ ଭଲ ସ୍ଥାନରେ ସ୍ଥିର ହୁଏ।',
    exp_big_msg: 'ଲର୍ଣ୍ଣିଂ ରେଟ୍ 1.5: ପ୍ରତି ପାଦ ଉପତ୍ୟକା ଡେଇଁ ଅନ୍ୟ ପଟେ ଆହୁରି ଉପରେ ପଡ଼େ। ଲସ୍ କମିବା ବଦଳରେ ଫାଟିଯାଏ।',
    table_title: 'ଡାଟା ସାରଣୀ ଓ ତ୍ରୁଟି',
    add_row: 'ଧାଡ଼ି ଯୋଡ଼ନ୍ତୁ',
    dl_csv: 'CSV ଡାଉନଲୋଡ୍',
    col_pred: 'ଅନୁମାନିତ ŷ',
    col_err: 'ତ୍ରୁଟି y − ŷ',
    col_sq: 'ତ୍ରୁଟିର ବର୍ଗ',
    del_row: 'ଧାଡ଼ି {n} ହଟାନ୍ତୁ',
    mse_line: 'ତ୍ରୁଟି ବର୍ଗଗୁଡ଼ିକର ଯୋଗଫଳ = {s}। ଏହାକୁ {n}ଟି ବିନ୍ଦୁରେ ଭାଗ କରନ୍ତୁ: MSE = {v}।',
    own_empty: 'ବିନ୍ଦୁ ଯୋଡ଼ିବାକୁ ଗ୍ରାଫରେ ଟ୍ୟାପ୍ କରନ୍ତୁ।',
    max_points: 'ସର୍ବାଧିକ {n}ଟି ବିନ୍ଦୁ।',
    kept_inside: 'ମାନଟି ଗ୍ରାଫ ଭିତରେ ହିଁ ରଖାଗଲା।',
    paste_title: 'ନିଜ ଡାଟା ପେଷ୍ଟ କରନ୍ତୁ',
    paste_hint: 'ସଂଖ୍ୟାର ଦୁଇଟି ସ୍ତମ୍ଭ (x ଓ y) ପେଷ୍ଟ କରନ୍ତୁ, ପ୍ରତି ଧାଡ଼ିରେ ଗୋଟିଏ ଯୋଡ଼ି। Excel ବା Google Sheets ରୁ କପି କରନ୍ତୁ, ବା ଏପରି ଲେଖନ୍ତୁ: 150, 152',
    paste_xname: 'x ର ନାମ (ଇଚ୍ଛାଧୀନ)',
    paste_yname: 'y ର ନାମ (ଇଚ୍ଛାଧୀନ)',
    paste_go: 'ଏହି ଡାଟା ବ୍ୟବହାର କରନ୍ତୁ',
    paste_bad: 'ସଂଖ୍ୟାର କୌଣସି ଯୋଡ଼ି ମିଳିଲା ନାହିଁ। ପ୍ରତି ଧାଡ଼ିରେ ଦୁଇଟି ସଂଖ୍ୟା ଲେଖନ୍ତୁ।',
    paste_ok: '{n}ଟି ବିନ୍ଦୁ ଯୋଡ଼ାଗଲା।',
    before_label: 'ଆଗରୁ',
    best_label: 'ସବୁଠୁ ଭଲ',
    err_word: 'ତ୍ରୁଟି',
    graph_aria: '{n}ଟି ବିନ୍ଦୁର ଗ୍ରାଫ: ଭୂସମାନ୍ତର {x} ଓ ଉପରକୁ {y}, ସହିତ ମଡେଲ୍ ରେଖା।',
    points_n: '{n}ଟି ବିନ୍ଦୁ',
    canvas_hint_manual: 'ରେଖା ଝୁଙ୍କାଇବାକୁ ଗୋଲ ହ୍ୟାଣ୍ଡେଲ୍ ଟାଣନ୍ତୁ, ବା ରେଖାକୁ ଉପର-ତଳ ଟାଣନ୍ତୁ। ଖାଲି ଜାଗାରେ ଟ୍ୟାପ୍ କରି ବିନ୍ଦୁ ଯୋଡ଼ନ୍ତୁ, ଟାଣି ଘୁଞ୍ଚାନ୍ତୁ, ଦୁଇଥର ଟ୍ୟାପ୍ କରି ହଟାନ୍ତୁ।',
    canvas_hint_auto: 'ଟ୍ୟାପ୍ କରି ବିନ୍ଦୁ ଯୋଡ଼ନ୍ତୁ, ଟାଣି ଘୁଞ୍ଚାନ୍ତୁ, ଦୁଇଥର ଟ୍ୟାପ୍ କରି ହଟାନ୍ତୁ। ତାପରେ AIକୁ ପୁଣି ଶିଖିବାକୁ ଦିଅନ୍ତୁ।',
    canvas_hint_predict: 'ଅନୁମାନ ପାଇଁ x ବାଛିବାକୁ ଗ୍ରାଫର ଯେକୌଣସି ଜାଗାରେ ଟ୍ୟାପ୍ କରନ୍ତୁ।',
    ws_title: 'ୱର୍କସିଟ୍: ସବୁଠୁ ଭଲ ରେଖା',
    ws_name: 'ନାମ: ______________   ଶ୍ରେଣୀ: ______   ତାରିଖ: __________',
    ws_q1: 'ଉପର ଗ୍ରାଫର ରେଖାର ସମୀକରଣ ଲେଖ। ଏହି ଡାଟା ପାଇଁ m ଓ c ର ଅର୍ଥ କ’ଣ?',
    ws_q2: 'ଯେକୌଣସି ଦୁଇଟି ବିନ୍ଦୁ ବାଛ। ପ୍ରତ୍ୟେକର ତ୍ରୁଟି (y − ŷ) ଓ ତ୍ରୁଟିର ବର୍ଗ ବାହାର କର।',
    ws_q3: 'ରେଖା ବ୍ୟବହାର କରି x = {x} ହେଲେ y ର ଅନୁମାନ କର। ହିସାବ ଦେଖାଅ।',
    ws_q4: 'ଆମେ ତ୍ରୁଟିଗୁଡ଼ିକୁ ସିଧା ଯୋଗ ନକରି ସେଗୁଡ଼ିକର ବର୍ଗ କାହିଁକି କରୁ?',
    ws_q5: 'ଗ୍ରାଡିଏଣ୍ଟ ଡିସେଣ୍ଟରେ ଲର୍ଣ୍ଣିଂ ରେଟ୍ ବହୁତ ବଡ଼ ହେଲେ କ’ଣ ହୁଏ? ବହୁତ ଛୋଟ ହେଲେ?',
    howto: 'କିପରି ବ୍ୟବହାର କରିବେ / ଶ୍ରେଣୀ ପାଇଁ ଚିନ୍ତାଧାରା',
    tip1: '"ହାତରେ ବସାନ୍ତୁ" ରୁ ଆରମ୍ଭ କରନ୍ତୁ: ଲସ୍ ଯେତେ ସମ୍ଭବ କମ୍ ନହେବା ଯାଏଁ ରେଖା ଟାଣନ୍ତୁ। ତାପରେ ତୁଳନା ପାଇଁ "ସବୁଠୁ ଭଲ ରେଖା" ଚାଲୁ କରନ୍ତୁ।',
    tip2: '"ତ୍ରୁଟିର ବର୍ଗ" ଚାଲୁ କରନ୍ତୁ: ବାକ୍ସଗୁଡ଼ିକ ଦେଖାଏ ଗୋଟିଏ ବଡ଼ ଭୁଲ ଅନେକ ଛୋଟ ଭୁଲଠାରୁ କାହିଁକି ବହୁତ ବେଶି ଗଣାଯାଏ।',
    tip3: '"AIକୁ ଶିଖିବାକୁ ଦିଅନ୍ତୁ" ଖୋଲି "ଚଲାନ୍ତୁ" ଦବାନ୍ତୁ। ଖସୁଥିବା ଲସ୍ ବକ୍ର ହିଁ "ଟ୍ରେନିଂ"। ତାପରେ ଲର୍ଣ୍ଣିଂ ରେଟ୍ ପରୀକ୍ଷାଗୁଡ଼ିକ କରନ୍ତୁ।',
    tip4: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟ: 10–15 ସହପାଠୀଙ୍କ ଉଚ୍ଚତା ଓ ହାତର ବିସ୍ତାର ମାପନ୍ତୁ, "ଡାଟା ପେଷ୍ଟ କରନ୍ତୁ" ରେ ଯୋଡ଼ନ୍ତୁ, ଓ ନୂଆ ଛାତ୍ରଙ୍କ ବିସ୍ତାର ଅନୁମାନ କରନ୍ତୁ।',
    tip5: '"ଅନୁମାନ" ଦ୍ୱାରା ଆଲୋଚନା କରନ୍ତୁ: ସପ୍ତାହରେ 40 ଘଣ୍ଟା ପଢ଼ୁଥିବା ଜଣଙ୍କ ନମ୍ବର ରେଖା କହିପାରିବ କି? କାହିଁକି ନୁହେଁ?',
    tip6: 'ପ୍ରିଣ୍ଟ କଲେ ଗ୍ରାଫ, ଡାଟା ସାରଣୀ ଓ 5ଟି ପ୍ରଶ୍ନର ୱର୍କସିଟ୍ ମିଳେ। ସ୍ମାର୍ଟବୋର୍ଡରେ ଫୁଲସ୍କ୍ରିନ୍ ଭଲ ଚାଲେ।'
  },

  ta: {
    app_title: 'சிறந்த பொருத்தக் கோடு',
    intro: 'தரவிலிருந்து AI ஒரு நேர்கோட்டை எப்படிக் கற்கிறது என்று பாருங்கள்: பிழை, இழப்பு, கிரேடியன்ட் டிசென்ட், கணிப்பு.',
    data_label: 'தரவு',
    restore: 'தரவை மீட்டெடு',
    clear_dots: 'புள்ளிகளை அழி',
    restored: 'அசல் தரவு திரும்ப வந்தது.',
    confirm_clear: 'உங்கள் புள்ளிகள் அனைத்தையும் நீக்கவா?',
    paste_btn: 'தரவை ஒட்டு',
    show_label: 'காட்டு:',
    show_res: 'பிழைகள்',
    show_sq: 'பிழைகளின் வர்க்கம்',
    show_best: 'சிறந்த கோடு',
    eq_label: 'மாதிரி (கோடு)',
    loss_label: 'இழப்பு (MSE)',
    miss: 'வழக்கமான தவறு ≈ {v}',
    closeness: 'சிறந்ததற்கு எவ்வளவு அருகில்',
    tab_manual: 'கையால் பொருத்து',
    tab_auto: 'AI கற்கட்டும்',
    tab_predict: 'கணி',
    manual_hint: 'சிவப்புப் பிழைக் கோடுகள் முடிந்தவரை குட்டையாகும்படி கோட்டை நகர்த்துங்கள். இழப்பு குறைவதைப் பாருங்கள்.',
    slope: 'சாய்வு m',
    slope_hint: 'x ஒன்று கூடும்போது y எவ்வளவு மாறுகிறது.',
    intercept: 'வெட்டுத்துண்டு c',
    intercept_hint: 'கோடு x = 0-ஐச் சந்திக்கும் இடத்தில் y-இன் மதிப்பு.',
    reset_line: 'மீண்டும் தட்டைக் கோடு',
    coach_m0: 'கோடு புள்ளிகளிலிருந்து வெகு தொலைவில் உள்ளது. வட்டக் கைப்பிடிகள் அல்லது சாய்வு ஸ்லைடரால் அதைச் சாய்க்கவும்.',
    coach_m1: 'நெருங்குகிறீர்கள்! கோட்டின் இரு பக்கமும் சிவப்புக் கோடுகளைக் குட்டையாக்குங்கள்.',
    coach_m2: 'மிக அருகில். m, c-இல் சிறு மாற்றங்கள் மீதமுள்ள இழப்பையும் குறைக்கும்.',
    coach_m3: 'அருமை! உங்கள் கோடு கிட்டத்தட்ட சிறந்த கோடுதான். இப்போது "AI கற்கட்டும்" உடன் ஒப்பிடுங்கள்.',
    need_points: 'வெவ்வேறு x மதிப்புள்ள குறைந்தது 2 புள்ளிகளைச் சேருங்கள்.',
    same_x: 'எல்லாப் புள்ளிகளுக்கும் ஒரே x, எனவே சாய்ந்த கோடு கிடைக்காது. ஒரு புள்ளியைப் பக்கவாட்டில் நகர்த்துங்கள்.',
    exact_title: 'துல்லியமான விடை (மீச்சிறு வர்க்க முறை)',
    exact_hint: 'நேர்கோட்டுக்கு, ஒரு சூத்திரம் ஒரே முறையில் சிறந்த m, c-ஐக் கண்டுபிடிக்கும்.',
    exact_btn: 'சிறந்த கோட்டைக் கண்டுபிடி',
    follow: 'புள்ளிகளை நகர்த்தும்போது சிறந்த கோட்டை வைத்திரு',
    show_math: 'கணக்கைக் காட்டு',
    gd_title: 'கிரேடியன்ட் டிசென்ட்: AI எப்படிக் கற்கிறது',
    gd_hint: 'AI ஒரு தட்டைக் கோட்டிலிருந்து தொடங்குகிறது. ஒவ்வொரு எபாக்கிலும் எல்லாப் புள்ளிகளையும் பார்த்து, m, c-ஐ இழப்பின் சரிவில் சற்றுக் கீழே நகர்த்துகிறது.',
    lr_label: 'கற்றல் வீதம் (அடியின் அளவு)',
    lr_tiny: 'மிகச் சிறியது: பாதுகாப்பானது, ஆனால் மிக மெதுவானது.',
    lr_small: 'சிறியது: நிலையானது, ஆனால் மெதுவானது.',
    lr_good: 'நல்லது: வேகமும் நிலைத்தன்மையும்.',
    lr_big: 'மிகப் பெரியது: அடிகள் தாண்டிச் செல்லும், இழப்பு வெடிக்கலாம்!',
    epochs_label: 'ஒரு ஓட்டத்தில் எபாக்குகள்',
    speed_label: 'வேகம்',
    speed_slow: 'மெதுவாக',
    speed_normal: 'சாதாரணம்',
    speed_fast: 'வேகமாக',
    gd_step: 'ஒரு அடி',
    gd_run: 'ஓட்டு',
    gd_restart: 'மீண்டும் தொடங்கு',
    epoch_label: 'எபாக்',
    best_possible: 'சாத்தியமான குறைந்தபட்சம்',
    loss_chart: 'இழப்பு வளைவு: ஒவ்வொரு எபாக்குக்குப் பின் இழப்பு',
    chart_empty: 'இழப்பு குறைவதைப் பார்க்க "ஒரு அடி" அல்லது "ஓட்டு" அழுத்துங்கள்.',
    coach_gd_need: 'முதலில் வெவ்வேறு x மதிப்புள்ள குறைந்தது 2 புள்ளிகளைச் சேருங்கள்.',
    coach_gd_explode: 'இழப்பு வெடித்துவிட்டது! கற்றல் வீதம் மிகப் பெரியது. சிறியதைத் தேர்ந்தெடுத்து "மீண்டும் தொடங்கு" அழுத்துங்கள்.',
    coach_gd_up: 'இழப்பு கூடுகிறது: ஒவ்வொரு அடியும் பள்ளத்தாக்கைத் தாண்டுகிறது. கற்றல் வீதத்தைக் குறையுங்கள்.',
    coach_gd_done: 'கற்றல் முடிந்தது! இழப்பு இப்போது சாத்தியமான குறைந்தபட்ச இழப்புக்குக் கிட்டத்தட்டச் சமம்.',
    coach_gd_running: 'கற்கிறது… கோடு நகர்வதையும் இழப்பு வளைவு இறங்குவதையும் பாருங்கள்.',
    coach_gd_idle: 'ஒரு மாற்றத்தைப் பார்க்க "ஒரு அடி", பல எபாக்குகளைப் பார்க்க "ஓட்டு" அழுத்துங்கள்.',
    coach_gd_slow: 'இழப்பு குறைகிறது, ஆனால் மெதுவாக; கற்றல் வீதம் சிறியது. மேலும் எபாக்குகள் ஓட்டுங்கள் அல்லது வீதத்தைக் கூட்டுங்கள்.',
    coach_gd_progress: 'இழப்பு குறைகிறது. தொடர்ந்து கற்க மீண்டும் "ஓட்டு" அழுத்துங்கள்.',
    pred_title: 'புதிய மதிப்பைக் கணி',
    pred_hint: 'x-ஐத் தேர்ந்தெடுங்கள் அல்லது வரைபடத்தில் தட்டுங்கள். கோடு தரும் கணிப்பு: ŷ = m × x + c',
    pred_answer: 'கணிப்பு ŷ',
    pred_outside: 'கவனம்: இந்த x தரவின் வரம்புக்கு ({a} முதல் {b}) வெளியே உள்ளது. தரவிலிருந்து தொலைவான கணிப்புகள் மிகத் தவறாகலாம்.',
    pred_negative: 'கோடு பூஜ்ஜியத்தை விடக் குறைவான மதிப்பைக் கணிக்கிறது; இங்கே அது சாத்தியமில்லை. ஒரு நேர்கோடு எல்லாவற்றையும் விளக்காது.',
    pred_tip_best: 'குறிப்பு: இந்தக் கோடு இன்னும் சிறந்தது அல்ல. சிறந்த கணிப்புக்கு "AI கற்கட்டும்" திறந்து "சிறந்த கோட்டைக் கண்டுபிடி" அழுத்துங்கள்.',
    explain_title: 'புரிந்துகொள்ளுங்கள்',
    exp_title: 'ஒரு சோதனை செய்து பாருங்கள்',
    exp_outlier: '📍 ஒரு விலகல் புள்ளி சேர்',
    exp_small: '🐢 கற்றல் வீதம் மிகச் சிறியது',
    exp_right: '👍 கற்றல் வீதம் சரியானது',
    exp_big: '💥 கற்றல் வீதம் மிகப் பெரியது',
    exp_outlier_msg: 'மற்றவற்றிலிருந்து வெகு தொலைவில் ஒரு வித்தியாசமான புள்ளி சேர்க்கப்பட்டது. சாம்பல் நிறக் கோடிட்ட கோடு முன்பிருந்த சிறந்த கோடு; புதிய சிறந்த கோடு விலகல் புள்ளியை நோக்கி இழுக்கப்பட்டுள்ளது. அந்தப் புள்ளியை இழுத்து, ஒரு புள்ளி மாதிரியை எவ்வளவு மாற்றும் என்று பாருங்கள்.',
    exp_small_msg: 'கற்றல் வீதம் 0.01: ஒவ்வொரு அடியும் மிகச் சிறியது, எனவே 200 எபாக்குகளுக்குப் பிறகும் கோடு சிறந்த இடத்தை அடையவில்லை. இழப்பு வளைவு எவ்வளவு மெதுவாக இறங்குகிறது என்று பாருங்கள்.',
    exp_right_msg: 'கற்றல் வீதம் 0.6: இழப்பு வேகமாகக் குறைகிறது, கோடு சிறந்த இடத்தில் நிலைக்கிறது.',
    exp_big_msg: 'கற்றல் வீதம் 1.5: ஒவ்வொரு அடியும் பள்ளத்தாக்கைத் தாண்டி மறுபக்கம் இன்னும் உயரத்தில் விழுகிறது. இழப்பு குறைவதற்குப் பதில் வெடிக்கிறது.',
    table_title: 'தரவு அட்டவணையும் பிழைகளும்',
    add_row: 'வரிசை சேர்',
    dl_csv: 'CSV பதிவிறக்கு',
    col_pred: 'கணித்த ŷ',
    col_err: 'பிழை y − ŷ',
    col_sq: 'பிழையின் வர்க்கம்',
    del_row: 'வரிசை {n}-ஐ நீக்கு',
    mse_line: 'பிழை வர்க்கங்களின் கூட்டுத்தொகை = {s}. அதை {n} புள்ளிகளால் வகுக்க: MSE = {v}.',
    own_empty: 'புள்ளிகளைச் சேர்க்க வரைபடத்தில் தட்டுங்கள்.',
    max_points: 'அதிகபட்சம் {n} புள்ளிகள்.',
    kept_inside: 'மதிப்பு வரைபடத்துக்குள்ளேயே வைக்கப்பட்டது.',
    paste_title: 'உங்கள் தரவை ஒட்டுங்கள்',
    paste_hint: 'எண்களின் இரண்டு நெடுவரிசைகளை (x, y) ஒட்டுங்கள், ஒவ்வொரு வரியிலும் ஒரு ஜோடி. Excel அல்லது Google Sheets-இலிருந்து நகலெடுக்கலாம், அல்லது இப்படித் தட்டச்சு செய்யலாம்: 150, 152',
    paste_xname: 'x-இன் பெயர் (விருப்பம்)',
    paste_yname: 'y-இன் பெயர் (விருப்பம்)',
    paste_go: 'இந்தத் தரவைப் பயன்படுத்து',
    paste_bad: 'எண் ஜோடிகள் எதுவும் கிடைக்கவில்லை. ஒவ்வொரு வரியிலும் இரண்டு எண்கள் இடுங்கள்.',
    paste_ok: '{n} புள்ளிகள் சேர்க்கப்பட்டன.',
    before_label: 'முன்பு',
    best_label: 'சிறந்தது',
    err_word: 'பிழை',
    graph_aria: '{n} புள்ளிகளின் வரைபடம்: குறுக்கே {x}, மேலே {y}, மாதிரிக் கோட்டுடன்.',
    points_n: '{n} புள்ளிகள்',
    canvas_hint_manual: 'கோட்டைச் சாய்க்க வட்டக் கைப்பிடியை இழுங்கள், அல்லது கோட்டை மேலே/கீழே இழுங்கள். காலி இடத்தில் தட்டிப் புள்ளி சேர்க்கவும், இழுத்து நகர்த்தவும், இருமுறை தட்டி நீக்கவும்.',
    canvas_hint_auto: 'தட்டிப் புள்ளி சேர்க்கவும், இழுத்து நகர்த்தவும், இருமுறை தட்டி நீக்கவும். பிறகு AI மீண்டும் கற்கட்டும்.',
    canvas_hint_predict: 'கணிப்புக்கு x-ஐத் தேர்ந்தெடுக்க வரைபடத்தில் எங்காவது தட்டுங்கள்.',
    ws_title: 'பயிற்சித்தாள்: சிறந்த பொருத்தக் கோடு',
    ws_name: 'பெயர்: ______________   வகுப்பு: ______   தேதி: __________',
    ws_q1: 'மேலே உள்ள வரைபடத்தின் கோட்டுச் சமன்பாட்டை எழுதுக. இந்தத் தரவுக்கு m, c என்பவை எதைக் குறிக்கின்றன?',
    ws_q2: 'ஏதேனும் இரண்டு புள்ளிகளைத் தேர்ந்தெடு. ஒவ்வொன்றின் பிழை (y − ŷ), பிழையின் வர்க்கம் கண்டுபிடி.',
    ws_q3: 'கோட்டைப் பயன்படுத்தி x = {x} எனில் y-ஐக் கணி. உன் கணக்கைக் காட்டு.',
    ws_q4: 'பிழைகளை நேரடியாகக் கூட்டாமல் ஏன் வர்க்கப்படுத்துகிறோம்?',
    ws_q5: 'கிரேடியன்ட் டிசென்டில் கற்றல் வீதம் மிகப் பெரியதானால் என்ன நடக்கும்? மிகச் சிறியதானால்?',
    howto: 'பயன்படுத்தும் முறை / வகுப்பறைக்கான யோசனைகள்',
    tip1: '"கையால் பொருத்து" உடன் தொடங்குங்கள்: இழப்பு முடிந்தவரை குறையும் வரை கோட்டை இழுங்கள். பிறகு ஒப்பிட "சிறந்த கோடு" இயக்குங்கள்.',
    tip2: '"பிழைகளின் வர்க்கம்" இயக்குங்கள்: ஒரு பெரிய தவறு பல சிறிய தவறுகளை விட ஏன் அதிகமாகக் கணக்கிடப்படுகிறது என்று சதுரங்கள் காட்டும்.',
    tip3: '"AI கற்கட்டும்" திறந்து "ஓட்டு" அழுத்துங்கள். இறங்கும் இழப்பு வளைவுதான் "பயிற்சி" (training). பிறகு கற்றல் வீதச் சோதனைகளைச் செய்யுங்கள்.',
    tip4: 'வகுப்புச் செயல்பாடு: 10–15 வகுப்புத் தோழர்களின் உயரத்தையும் கை விரிப்பு நீளத்தையும் அளந்து, "தரவை ஒட்டு" மூலம் சேர்த்து, புதிய மாணவரின் கை விரிப்பைக் கணியுங்கள்.',
    tip5: '"கணி" மூலம் விவாதியுங்கள்: வாரம் 40 மணி நேரம் படிக்கும் மாணவரின் மதிப்பெண்ணைக் கோடு சொல்ல முடியுமா? ஏன் முடியாது?',
    tip6: 'அச்சிட்டால் வரைபடம், தரவு அட்டவணை, 5 கேள்விகள் கொண்ட பயிற்சித்தாள் கிடைக்கும். ஸ்மார்ட்போர்டில் முழுத்திரை நன்றாக வேலை செய்யும்.'
  },

  te: {
    app_title: 'ఉత్తమ సరిపోలిక రేఖ',
    intro: 'డేటా నుంచి AI ఒక సరళ రేఖను ఎలా నేర్చుకుంటుందో చూడండి: దోషం, లాస్, గ్రేడియంట్ డిసెంట్, అంచనాలు.',
    data_label: 'డేటా',
    restore: 'డేటాను తిరిగి తెండి',
    clear_dots: 'బిందువులు తుడిచేయండి',
    restored: 'అసలు డేటా తిరిగి వచ్చింది.',
    confirm_clear: 'మీ బిందువులన్నీ తీసేయాలా?',
    paste_btn: 'డేటా పేస్ట్ చేయండి',
    show_label: 'చూపించు:',
    show_res: 'దోషాలు',
    show_sq: 'దోషాల వర్గాలు',
    show_best: 'ఉత్తమ రేఖ',
    eq_label: 'మోడల్ (రేఖ)',
    loss_label: 'లాస్ (MSE)',
    miss: 'సాధారణ తప్పు ≈ {v}',
    closeness: 'ఉత్తమానికి ఎంత దగ్గర',
    tab_manual: 'చేత్తో సరిపెట్టండి',
    tab_auto: 'AI నేర్చుకోనివ్వండి',
    tab_predict: 'అంచనా',
    manual_hint: 'ఎరుపు దోష-గీతలు వీలైనంత చిన్నవి అయ్యేలా రేఖను జరపండి. లాస్ తగ్గడం చూడండి.',
    slope: 'వాలు m',
    slope_hint: 'x ఒకటి పెరిగితే y ఎంత మారుతుంది.',
    intercept: 'అంతఃఖండం c',
    intercept_hint: 'రేఖ x = 0 ను కలిసే చోట y విలువ.',
    reset_line: 'మళ్ళీ చదునైన రేఖ',
    coach_m0: 'రేఖ బిందువులకు చాలా దూరంగా ఉంది. గుండ్రని హ్యాండిల్స్ లేదా వాలు స్లయిడర్‌తో దాన్ని వంచండి.',
    coach_m1: 'దగ్గరవుతున్నారు! రేఖకు రెండు వైపులా ఎరుపు గీతలను చిన్నవి చేయండి.',
    coach_m2: 'చాలా దగ్గర. m, c లో చిన్న మార్పులతో మిగిలిన లాస్ కూడా తగ్గుతుంది.',
    coach_m3: 'అద్భుతం! మీ రేఖ దాదాపు ఉత్తమ రేఖే. ఇప్పుడు "AI నేర్చుకోనివ్వండి" తో పోల్చండి.',
    need_points: 'వేర్వేరు x విలువలతో కనీసం 2 బిందువులు చేర్చండి.',
    same_x: 'అన్ని బిందువులకూ ఒకే x ఉంది, కాబట్టి వాలు రేఖ దొరకదు. ఒక బిందువును పక్కకు జరపండి.',
    exact_title: 'ఖచ్చితమైన జవాబు (కనిష్ఠ వర్గాల పద్ధతి)',
    exact_hint: 'సరళ రేఖకు ఒక సూత్రం ఒకేసారి ఉత్తమ m, c కనుగొంటుంది.',
    exact_btn: 'ఉత్తమ రేఖను కనుగొనండి',
    follow: 'బిందువులు జరిపేటప్పుడు ఉత్తమ రేఖను ఉంచండి',
    show_math: 'లెక్క చూపించు',
    gd_title: 'గ్రేడియంట్ డిసెంట్: AI ఎలా నేర్చుకుంటుంది',
    gd_hint: 'AI చదునైన రేఖతో మొదలవుతుంది. ప్రతి ఎపాక్‌లో అన్ని బిందువులనూ చూసి, m, c లను లాస్ వాలుపై కొంచెం కిందికి జరుపుతుంది.',
    lr_label: 'లెర్నింగ్ రేట్ (అడుగు పరిమాణం)',
    lr_tiny: 'చాలా చిన్నది: సురక్షితం, కానీ చాలా నెమ్మది.',
    lr_small: 'చిన్నది: స్థిరం, కానీ నెమ్మది.',
    lr_good: 'బాగుంది: వేగం, స్థిరం.',
    lr_big: 'చాలా పెద్దది: అడుగులు దాటిపోతాయి, లాస్ పేలిపోవచ్చు!',
    epochs_label: 'ఒక్కసారికి ఎపాక్‌లు',
    speed_label: 'వేగం',
    speed_slow: 'నెమ్మది',
    speed_normal: 'సాధారణం',
    speed_fast: 'వేగంగా',
    gd_step: 'ఒక అడుగు',
    gd_run: 'నడుపు',
    gd_restart: 'మళ్ళీ మొదలు',
    epoch_label: 'ఎపాక్',
    best_possible: 'సాధ్యమైన కనిష్ఠం',
    loss_chart: 'లాస్ వక్రం: ప్రతి ఎపాక్ తర్వాత లాస్',
    chart_empty: 'లాస్ తగ్గడం చూడటానికి "ఒక అడుగు" లేదా "నడుపు" నొక్కండి.',
    coach_gd_need: 'ముందుగా వేర్వేరు x విలువలతో కనీసం 2 బిందువులు చేర్చండి.',
    coach_gd_explode: 'లాస్ పేలిపోయింది! లెర్నింగ్ రేట్ చాలా పెద్దది. చిన్నది ఎంచుకుని "మళ్ళీ మొదలు" నొక్కండి.',
    coach_gd_up: 'లాస్ పెరుగుతోంది: ప్రతి అడుగూ లోయను దాటి దూకుతోంది. లెర్నింగ్ రేట్ తగ్గించండి.',
    coach_gd_done: 'నేర్చుకోవడం పూర్తి! లాస్ ఇప్పుడు సాధ్యమైన కనిష్ఠ లాస్‌కు దాదాపు సమానం.',
    coach_gd_running: 'నేర్చుకుంటోంది… రేఖ కదలడం, లాస్ వక్రం దిగడం చూడండి.',
    coach_gd_idle: 'ఒక మార్పు చూడటానికి "ఒక అడుగు", చాలా ఎపాక్‌లు చూడటానికి "నడుపు" నొక్కండి.',
    coach_gd_slow: 'లాస్ తగ్గుతోంది, కానీ నెమ్మదిగా; లెర్నింగ్ రేట్ చిన్నది. మరిన్ని ఎపాక్‌లు నడపండి లేదా రేట్ పెంచండి.',
    coach_gd_progress: 'లాస్ తగ్గుతోంది. నేర్చుకోవడం కొనసాగించడానికి మళ్ళీ "నడుపు" నొక్కండి.',
    pred_title: 'కొత్త విలువను అంచనా వేయండి',
    pred_hint: 'x ఎంచుకోండి లేదా గ్రాఫ్‌పై తాకండి. రేఖ ఇచ్చే అంచనా: ŷ = m × x + c',
    pred_answer: 'అంచనా ŷ',
    pred_outside: 'జాగ్రత్త: ఈ x డేటా పరిధికి ({a} నుంచి {b}) బయట ఉంది. డేటాకు దూరంగా ఉన్న అంచనాలు చాలా తప్పు కావచ్చు.',
    pred_negative: 'రేఖ సున్నా కంటే తక్కువ విలువ చెబుతోంది, ఇక్కడ అది అసాధ్యం. ఒక సరళ రేఖ అన్నింటినీ వివరించలేదు.',
    pred_tip_best: 'సూచన: ఈ రేఖ ఇంకా ఉత్తమమైనది కాదు. మంచి అంచనా కోసం "AI నేర్చుకోనివ్వండి" తెరిచి "ఉత్తమ రేఖను కనుగొనండి" నొక్కండి.',
    explain_title: 'అర్థం చేసుకోండి',
    exp_title: 'ఒక ప్రయోగం చేసి చూడండి',
    exp_outlier: '📍 ఒక అవుట్‌లయర్ చేర్చండి',
    exp_small: '🐢 లెర్నింగ్ రేట్ చాలా చిన్నది',
    exp_right: '👍 లెర్నింగ్ రేట్ సరిగ్గా',
    exp_big: '💥 లెర్నింగ్ రేట్ చాలా పెద్దది',
    exp_outlier_msg: 'మిగతా వాటికి చాలా దూరంగా ఒక వింత బిందువు చేర్చబడింది. బూడిద రంగు గీతల రేఖ ఇంతకు ముందు ఉత్తమ రేఖ; కొత్త ఉత్తమ రేఖ అవుట్‌లయర్ వైపు లాగబడింది. ఆ బిందువును లాగి, ఒక్క బిందువు మోడల్‌ను ఎంత మార్చగలదో చూడండి.',
    exp_small_msg: 'లెర్నింగ్ రేట్ 0.01: ప్రతి అడుగూ చాలా చిన్నది, కాబట్టి 200 ఎపాక్‌ల తర్వాత కూడా రేఖ ఉత్తమ స్థానానికి చేరలేదు. లాస్ వక్రం ఎంత నెమ్మదిగా దిగుతుందో చూడండి.',
    exp_right_msg: 'లెర్నింగ్ రేట్ 0.6: లాస్ వేగంగా తగ్గుతుంది, రేఖ ఉత్తమ స్థానంలో స్థిరపడుతుంది.',
    exp_big_msg: 'లెర్నింగ్ రేట్ 1.5: ప్రతి అడుగూ లోయను దాటి అవతలి వైపు ఇంకా పైకి చేరుతుంది. లాస్ తగ్గడానికి బదులు పేలిపోతుంది.',
    table_title: 'డేటా పట్టిక, దోషాలు',
    add_row: 'వరుస చేర్చు',
    dl_csv: 'CSV డౌన్‌లోడ్',
    col_pred: 'అంచనా ŷ',
    col_err: 'దోషం y − ŷ',
    col_sq: 'దోషం వర్గం',
    del_row: 'వరుస {n} తొలగించు',
    mse_line: 'దోషాల వర్గాల మొత్తం = {s}. దాన్ని {n} బిందువులతో భాగించండి: MSE = {v}.',
    own_empty: 'బిందువులు చేర్చడానికి గ్రాఫ్‌పై తాకండి.',
    max_points: 'గరిష్ఠంగా {n} బిందువులు.',
    kept_inside: 'విలువను గ్రాఫ్ లోపలే ఉంచాం.',
    paste_title: 'మీ డేటా పేస్ట్ చేయండి',
    paste_hint: 'సంఖ్యల రెండు నిలువు వరుసలు (x, y) పేస్ట్ చేయండి, ప్రతి లైన్‌లో ఒక జత. Excel లేదా Google Sheets నుంచి కాపీ చేయవచ్చు, లేదా ఇలా టైప్ చేయవచ్చు: 150, 152',
    paste_xname: 'x పేరు (ఐచ్ఛికం)',
    paste_yname: 'y పేరు (ఐచ్ఛికం)',
    paste_go: 'ఈ డేటా వాడండి',
    paste_bad: 'సంఖ్యల జతలు దొరకలేదు. ప్రతి లైన్‌లో రెండు సంఖ్యలు రాయండి.',
    paste_ok: '{n} బిందువులు చేర్చబడ్డాయి.',
    before_label: 'ముందు',
    best_label: 'ఉత్తమం',
    err_word: 'దోషం',
    graph_aria: '{n} బిందువుల గ్రాఫ్: అడ్డంగా {x}, నిలువుగా {y}, మోడల్ రేఖతో.',
    points_n: '{n} బిందువులు',
    canvas_hint_manual: 'రేఖను వంచడానికి గుండ్రని హ్యాండిల్‌ను లాగండి, లేదా రేఖను పైకి-కిందికి లాగండి. ఖాళీ చోట తాకి బిందువు చేర్చండి, లాగి జరపండి, రెండుసార్లు తాకి తొలగించండి.',
    canvas_hint_auto: 'తాకి బిందువు చేర్చండి, లాగి జరపండి, రెండుసార్లు తాకి తొలగించండి. తర్వాత AI ని మళ్ళీ నేర్చుకోనివ్వండి.',
    canvas_hint_predict: 'అంచనా కోసం x ఎంచుకోవడానికి గ్రాఫ్‌పై ఎక్కడైనా తాకండి.',
    ws_title: 'వర్క్‌షీట్: ఉత్తమ సరిపోలిక రేఖ',
    ws_name: 'పేరు: ______________   తరగతి: ______   తేదీ: __________',
    ws_q1: 'పై గ్రాఫ్‌లోని రేఖ సమీకరణం రాయండి. ఈ డేటాకు m, c అంటే ఏమిటి?',
    ws_q2: 'ఏవైనా రెండు బిందువులు ఎంచుకోండి. ప్రతిదాని దోషం (y − ŷ), దోషం వర్గం కనుగొనండి.',
    ws_q3: 'రేఖను ఉపయోగించి x = {x} అయినప్పుడు y ని అంచనా వేయండి. మీ లెక్క చూపించండి.',
    ws_q4: 'దోషాలను నేరుగా కూడకుండా వాటి వర్గం ఎందుకు తీసుకుంటాం?',
    ws_q5: 'గ్రేడియంట్ డిసెంట్‌లో లెర్నింగ్ రేట్ చాలా పెద్దదైతే ఏమవుతుంది? చాలా చిన్నదైతే?',
    howto: 'ఎలా వాడాలి / తరగతి గది ఆలోచనలు',
    tip1: '"చేత్తో సరిపెట్టండి" తో మొదలుపెట్టండి: లాస్ వీలైనంత తగ్గే వరకు రేఖను లాగండి. తర్వాత పోల్చడానికి "ఉత్తమ రేఖ" ఆన్ చేయండి.',
    tip2: '"దోషాల వర్గాలు" ఆన్ చేయండి: ఒక పెద్ద తప్పు చాలా చిన్న తప్పుల కంటే ఎందుకు ఎక్కువగా లెక్కకు వస్తుందో చతురస్రాలు చూపిస్తాయి.',
    tip3: '"AI నేర్చుకోనివ్వండి" తెరిచి "నడుపు" నొక్కండి. దిగుతున్న లాస్ వక్రమే "ట్రైనింగ్". తర్వాత లెర్నింగ్ రేట్ ప్రయోగాలు చేయండి.',
    tip4: 'తరగతి కార్యకలాపం: 10–15 మంది సహవిద్యార్థుల ఎత్తు, చేతుల వెడల్పు కొలిచి, "డేటా పేస్ట్ చేయండి" తో చేర్చి, కొత్త విద్యార్థి చేతుల వెడల్పును అంచనా వేయండి.',
    tip5: '"అంచనా" తో చర్చించండి: వారానికి 40 గంటలు చదివే విద్యార్థి మార్కులను రేఖ చెప్పగలదా? ఎందుకు కాదు?',
    tip6: 'ప్రింట్ చేస్తే గ్రాఫ్, డేటా పట్టిక, 5 ప్రశ్నల వర్క్‌షీట్ వస్తాయి. స్మార్ట్‌బోర్డ్‌పై ఫుల్‌స్క్రీన్ బాగా పనిచేస్తుంది.'
  },

  kn: {
    app_title: 'ಅತ್ಯುತ್ತಮ ಹೊಂದಾಣಿಕೆ ರೇಖೆ',
    intro: 'ಡೇಟಾದಿಂದ AI ಒಂದು ಸರಳ ರೇಖೆಯನ್ನು ಹೇಗೆ ಕಲಿಯುತ್ತದೆ ನೋಡಿ: ದೋಷ, ಲಾಸ್, ಗ್ರೇಡಿಯಂಟ್ ಡಿಸೆಂಟ್ ಮತ್ತು ಅಂದಾಜು.',
    data_label: 'ಡೇಟಾ',
    restore: 'ಡೇಟಾ ಮರಳಿ ತನ್ನಿ',
    clear_dots: 'ಬಿಂದುಗಳನ್ನು ಅಳಿಸಿ',
    restored: 'ಮೂಲ ಡೇಟಾ ಮರಳಿ ಬಂದಿದೆ.',
    confirm_clear: 'ನಿಮ್ಮ ಎಲ್ಲಾ ಬಿಂದುಗಳನ್ನು ತೆಗೆಯಬೇಕೇ?',
    paste_btn: 'ಡೇಟಾ ಅಂಟಿಸಿ',
    show_label: 'ತೋರಿಸು:',
    show_res: 'ದೋಷಗಳು',
    show_sq: 'ದೋಷಗಳ ವರ್ಗ',
    show_best: 'ಅತ್ಯುತ್ತಮ ರೇಖೆ',
    eq_label: 'ಮಾದರಿ (ರೇಖೆ)',
    loss_label: 'ಲಾಸ್ (MSE)',
    miss: 'ಸಾಮಾನ್ಯ ತಪ್ಪು ≈ {v}',
    closeness: 'ಅತ್ಯುತ್ತಮಕ್ಕೆ ಎಷ್ಟು ಹತ್ತಿರ',
    tab_manual: 'ಕೈಯಿಂದ ಹೊಂದಿಸಿ',
    tab_auto: 'AI ಕಲಿಯಲಿ',
    tab_predict: 'ಅಂದಾಜು',
    manual_hint: 'ಕೆಂಪು ದೋಷ-ಗೆರೆಗಳು ಸಾಧ್ಯವಾದಷ್ಟು ಚಿಕ್ಕದಾಗುವಂತೆ ರೇಖೆಯನ್ನು ಸರಿಸಿ. ಲಾಸ್ ಇಳಿಯುವುದನ್ನು ನೋಡಿ.',
    slope: 'ಇಳಿಜಾರು m',
    slope_hint: 'x 1 ಹೆಚ್ಚಾದಾಗ y ಎಷ್ಟು ಬದಲಾಗುತ್ತದೆ.',
    intercept: 'ಅಂತಃಖಂಡ c',
    intercept_hint: 'ರೇಖೆ x = 0 ಅನ್ನು ಸಂಧಿಸುವಲ್ಲಿ y ಯ ಮೌಲ್ಯ.',
    reset_line: 'ಮತ್ತೆ ಸಮತಟ್ಟು ರೇಖೆ',
    coach_m0: 'ರೇಖೆ ಬಿಂದುಗಳಿಂದ ತುಂಬಾ ದೂರದಲ್ಲಿದೆ. ದುಂಡು ಹ್ಯಾಂಡಲ್‌ಗಳು ಅಥವಾ ಇಳಿಜಾರು ಸ್ಲೈಡರ್‌ನಿಂದ ಅದನ್ನು ಓರೆ ಮಾಡಿ.',
    coach_m1: 'ಹತ್ತಿರ ಬರುತ್ತಿದ್ದೀರಿ! ರೇಖೆಯ ಎರಡೂ ಬದಿಯ ಕೆಂಪು ಗೆರೆಗಳನ್ನು ಚಿಕ್ಕದು ಮಾಡಿ.',
    coach_m2: 'ತುಂಬಾ ಹತ್ತಿರ. m ಮತ್ತು c ಯಲ್ಲಿ ಸಣ್ಣ ಬದಲಾವಣೆಯಿಂದ ಉಳಿದ ಲಾಸ್ ಕೂಡ ಇಳಿಯುತ್ತದೆ.',
    coach_m3: 'ಅದ್ಭುತ! ನಿಮ್ಮ ರೇಖೆ ಬಹುತೇಕ ಅತ್ಯುತ್ತಮ ರೇಖೆಯೇ. ಈಗ "AI ಕಲಿಯಲಿ" ಜೊತೆ ಹೋಲಿಸಿ.',
    need_points: 'ಬೇರೆ ಬೇರೆ x ಇರುವ ಕನಿಷ್ಠ 2 ಬಿಂದುಗಳನ್ನು ಸೇರಿಸಿ.',
    same_x: 'ಎಲ್ಲಾ ಬಿಂದುಗಳ x ಒಂದೇ, ಆದ್ದರಿಂದ ಓರೆ ರೇಖೆ ಸಿಗುವುದಿಲ್ಲ. ಒಂದು ಬಿಂದುವನ್ನು ಪಕ್ಕಕ್ಕೆ ಸರಿಸಿ.',
    exact_title: 'ನಿಖರ ಉತ್ತರ (ಕನಿಷ್ಠ ವರ್ಗ ವಿಧಾನ)',
    exact_hint: 'ಸರಳ ರೇಖೆಗೆ ಒಂದು ಸೂತ್ರ ಒಮ್ಮೆಲೇ ಅತ್ಯುತ್ತಮ m ಮತ್ತು c ಕಂಡುಹಿಡಿಯುತ್ತದೆ.',
    exact_btn: 'ಅತ್ಯುತ್ತಮ ರೇಖೆ ಹುಡುಕಿ',
    follow: 'ಬಿಂದುಗಳನ್ನು ಸರಿಸುವಾಗ ಅತ್ಯುತ್ತಮ ರೇಖೆ ಉಳಿಸಿ',
    show_math: 'ಲೆಕ್ಕ ತೋರಿಸು',
    gd_title: 'ಗ್ರೇಡಿಯಂಟ್ ಡಿಸೆಂಟ್: AI ಹೇಗೆ ಕಲಿಯುತ್ತದೆ',
    gd_hint: 'AI ಸಮತಟ್ಟು ರೇಖೆಯಿಂದ ಶುರು ಮಾಡುತ್ತದೆ. ಪ್ರತಿ ಎಪಾಕ್‌ನಲ್ಲಿ ಎಲ್ಲಾ ಬಿಂದುಗಳನ್ನು ನೋಡಿ m ಮತ್ತು c ಯನ್ನು ಲಾಸ್‌ನ ಇಳಿಜಾರಿನಲ್ಲಿ ಸ್ವಲ್ಪ ಕೆಳಗೆ ಸರಿಸುತ್ತದೆ.',
    lr_label: 'ಲರ್ನಿಂಗ್ ರೇಟ್ (ಹೆಜ್ಜೆಯ ಗಾತ್ರ)',
    lr_tiny: 'ತುಂಬಾ ಚಿಕ್ಕದು: ಸುರಕ್ಷಿತ, ಆದರೆ ತುಂಬಾ ನಿಧಾನ.',
    lr_small: 'ಚಿಕ್ಕದು: ಸ್ಥಿರ, ಆದರೆ ನಿಧಾನ.',
    lr_good: 'ಒಳ್ಳೆಯದು: ವೇಗ ಮತ್ತು ಸ್ಥಿರ.',
    lr_big: 'ತುಂಬಾ ದೊಡ್ಡದು: ಹೆಜ್ಜೆಗಳು ದಾಟಿ ಹೋಗುತ್ತವೆ, ಲಾಸ್ ಸ್ಫೋಟಗೊಳ್ಳಬಹುದು!',
    epochs_label: 'ಒಮ್ಮೆಗೆ ಎಪಾಕ್‌ಗಳು',
    speed_label: 'ವೇಗ',
    speed_slow: 'ನಿಧಾನ',
    speed_normal: 'ಸಾಮಾನ್ಯ',
    speed_fast: 'ವೇಗವಾಗಿ',
    gd_step: 'ಒಂದು ಹೆಜ್ಜೆ',
    gd_run: 'ಚಲಾಯಿಸಿ',
    gd_restart: 'ಮತ್ತೆ ಶುರು',
    epoch_label: 'ಎಪಾಕ್',
    best_possible: 'ಸಾಧ್ಯವಾದ ಕನಿಷ್ಠ',
    loss_chart: 'ಲಾಸ್ ವಕ್ರ: ಪ್ರತಿ ಎಪಾಕ್ ನಂತರದ ಲಾಸ್',
    chart_empty: 'ಲಾಸ್ ಇಳಿಯುವುದನ್ನು ನೋಡಲು "ಒಂದು ಹೆಜ್ಜೆ" ಅಥವಾ "ಚಲಾಯಿಸಿ" ಒತ್ತಿ.',
    coach_gd_need: 'ಮೊದಲು ಬೇರೆ ಬೇರೆ x ಇರುವ ಕನಿಷ್ಠ 2 ಬಿಂದುಗಳನ್ನು ಸೇರಿಸಿ.',
    coach_gd_explode: 'ಲಾಸ್ ಸ್ಫೋಟಗೊಂಡಿತು! ಲರ್ನಿಂಗ್ ರೇಟ್ ತುಂಬಾ ದೊಡ್ಡದು. ಚಿಕ್ಕದನ್ನು ಆರಿಸಿ "ಮತ್ತೆ ಶುರು" ಒತ್ತಿ.',
    coach_gd_up: 'ಲಾಸ್ ಏರುತ್ತಿದೆ: ಪ್ರತಿ ಹೆಜ್ಜೆ ಕಣಿವೆಯನ್ನು ಹಾರಿ ದಾಟುತ್ತಿದೆ. ಲರ್ನಿಂಗ್ ರೇಟ್ ಕಡಿಮೆ ಮಾಡಿ.',
    coach_gd_done: 'ಕಲಿಕೆ ಮುಗಿಯಿತು! ಲಾಸ್ ಈಗ ಸಾಧ್ಯವಾದ ಕನಿಷ್ಠ ಲಾಸ್‌ಗೆ ಬಹುತೇಕ ಸಮ.',
    coach_gd_running: 'ಕಲಿಯುತ್ತಿದೆ… ರೇಖೆ ಸರಿಯುವುದನ್ನೂ ಲಾಸ್ ವಕ್ರ ಇಳಿಯುವುದನ್ನೂ ನೋಡಿ.',
    coach_gd_idle: 'ಒಂದು ಬದಲಾವಣೆ ನೋಡಲು "ಒಂದು ಹೆಜ್ಜೆ", ಹಲವು ಎಪಾಕ್ ನೋಡಲು "ಚಲಾಯಿಸಿ" ಒತ್ತಿ.',
    coach_gd_slow: 'ಲಾಸ್ ಇಳಿಯುತ್ತಿದೆ, ಆದರೆ ನಿಧಾನವಾಗಿ; ಲರ್ನಿಂಗ್ ರೇಟ್ ಚಿಕ್ಕದು. ಇನ್ನಷ್ಟು ಎಪಾಕ್ ಚಲಾಯಿಸಿ ಅಥವಾ ರೇಟ್ ಹೆಚ್ಚಿಸಿ.',
    coach_gd_progress: 'ಲಾಸ್ ಇಳಿಯುತ್ತಿದೆ. ಕಲಿಕೆ ಮುಂದುವರಿಸಲು ಮತ್ತೆ "ಚಲಾಯಿಸಿ" ಒತ್ತಿ.',
    pred_title: 'ಹೊಸ ಮೌಲ್ಯದ ಅಂದಾಜು',
    pred_hint: 'x ಆರಿಸಿ ಅಥವಾ ಗ್ರಾಫ್ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ. ರೇಖೆ ಕೊಡುವ ಅಂದಾಜು: ŷ = m × x + c',
    pred_answer: 'ಅಂದಾಜು ŷ',
    pred_outside: 'ಎಚ್ಚರ: ಈ x ಡೇಟಾದ ವ್ಯಾಪ್ತಿಯ ({a} ರಿಂದ {b}) ಹೊರಗಿದೆ. ಡೇಟಾದಿಂದ ದೂರದ ಅಂದಾಜುಗಳು ತುಂಬಾ ತಪ್ಪಾಗಬಹುದು.',
    pred_negative: 'ರೇಖೆ ಸೊನ್ನೆಗಿಂತ ಕಡಿಮೆ ಮೌಲ್ಯ ಹೇಳುತ್ತಿದೆ, ಇಲ್ಲಿ ಅದು ಅಸಾಧ್ಯ. ಸರಳ ರೇಖೆ ಎಲ್ಲವನ್ನೂ ವಿವರಿಸಲಾರದು.',
    pred_tip_best: 'ಸಲಹೆ: ಈ ರೇಖೆ ಇನ್ನೂ ಅತ್ಯುತ್ತಮವಲ್ಲ. ಉತ್ತಮ ಅಂದಾಜಿಗೆ "AI ಕಲಿಯಲಿ" ತೆರೆದು "ಅತ್ಯುತ್ತಮ ರೇಖೆ ಹುಡುಕಿ" ಒತ್ತಿ.',
    explain_title: 'ಅರ್ಥ ಮಾಡಿಕೊಳ್ಳಿ',
    exp_title: 'ಒಂದು ಪ್ರಯೋಗ ಮಾಡಿ ನೋಡಿ',
    exp_outlier: '📍 ಒಂದು ಔಟ್‌ಲೈಯರ್ ಸೇರಿಸಿ',
    exp_small: '🐢 ಲರ್ನಿಂಗ್ ರೇಟ್ ತುಂಬಾ ಚಿಕ್ಕದು',
    exp_right: '👍 ಲರ್ನಿಂಗ್ ರೇಟ್ ಸರಿಯಾಗಿದೆ',
    exp_big: '💥 ಲರ್ನಿಂಗ್ ರೇಟ್ ತುಂಬಾ ದೊಡ್ಡದು',
    exp_outlier_msg: 'ಉಳಿದವುಗಳಿಂದ ತುಂಬಾ ದೂರದಲ್ಲಿ ಒಂದು ವಿಚಿತ್ರ ಬಿಂದು ಸೇರಿಸಲಾಗಿದೆ. ಬೂದು ಚುಕ್ಕೆ ರೇಖೆ ಹಿಂದಿನ ಅತ್ಯುತ್ತಮ ರೇಖೆ; ಹೊಸ ಅತ್ಯುತ್ತಮ ರೇಖೆ ಔಟ್‌ಲೈಯರ್ ಕಡೆಗೆ ಎಳೆಯಲ್ಪಟ್ಟಿದೆ. ಆ ಬಿಂದುವನ್ನು ಎಳೆದು, ಒಂದೇ ಬಿಂದು ಮಾದರಿಯನ್ನು ಎಷ್ಟು ಬದಲಿಸಬಲ್ಲದು ನೋಡಿ.',
    exp_small_msg: 'ಲರ್ನಿಂಗ್ ರೇಟ್ 0.01: ಪ್ರತಿ ಹೆಜ್ಜೆ ತುಂಬಾ ಚಿಕ್ಕದು, ಹಾಗಾಗಿ 200 ಎಪಾಕ್ ನಂತರವೂ ರೇಖೆ ಅತ್ಯುತ್ತಮ ಸ್ಥಳ ತಲುಪಿಲ್ಲ. ಲಾಸ್ ವಕ್ರ ಎಷ್ಟು ನಿಧಾನವಾಗಿ ಇಳಿಯುತ್ತದೆ ನೋಡಿ.',
    exp_right_msg: 'ಲರ್ನಿಂಗ್ ರೇಟ್ 0.6: ಲಾಸ್ ವೇಗವಾಗಿ ಇಳಿಯುತ್ತದೆ, ರೇಖೆ ಅತ್ಯುತ್ತಮ ಸ್ಥಳದಲ್ಲಿ ನೆಲೆಸುತ್ತದೆ.',
    exp_big_msg: 'ಲರ್ನಿಂಗ್ ರೇಟ್ 1.5: ಪ್ರತಿ ಹೆಜ್ಜೆ ಕಣಿವೆಯನ್ನು ದಾಟಿ ಆಚೆ ಬದಿಯಲ್ಲಿ ಇನ್ನೂ ಮೇಲೆ ಬೀಳುತ್ತದೆ. ಲಾಸ್ ಇಳಿಯುವ ಬದಲು ಸ್ಫೋಟಗೊಳ್ಳುತ್ತದೆ.',
    table_title: 'ಡೇಟಾ ಕೋಷ್ಟಕ ಮತ್ತು ದೋಷಗಳು',
    add_row: 'ಸಾಲು ಸೇರಿಸಿ',
    dl_csv: 'CSV ಡೌನ್‌ಲೋಡ್',
    col_pred: 'ಅಂದಾಜಿತ ŷ',
    col_err: 'ದೋಷ y − ŷ',
    col_sq: 'ದೋಷದ ವರ್ಗ',
    del_row: 'ಸಾಲು {n} ಅಳಿಸಿ',
    mse_line: 'ದೋಷಗಳ ವರ್ಗಗಳ ಮೊತ್ತ = {s}. ಅದನ್ನು {n} ಬಿಂದುಗಳಿಂದ ಭಾಗಿಸಿ: MSE = {v}.',
    own_empty: 'ಬಿಂದುಗಳನ್ನು ಸೇರಿಸಲು ಗ್ರಾಫ್ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ.',
    max_points: 'ಗರಿಷ್ಠ {n} ಬಿಂದುಗಳು.',
    kept_inside: 'ಮೌಲ್ಯವನ್ನು ಗ್ರಾಫ್ ಒಳಗೇ ಇರಿಸಲಾಗಿದೆ.',
    paste_title: 'ನಿಮ್ಮ ಡೇಟಾ ಅಂಟಿಸಿ',
    paste_hint: 'ಸಂಖ್ಯೆಗಳ ಎರಡು ಕಾಲಮ್ (x ಮತ್ತು y) ಅಂಟಿಸಿ, ಪ್ರತಿ ಸಾಲಿನಲ್ಲಿ ಒಂದು ಜೋಡಿ. Excel ಅಥವಾ Google Sheets ನಿಂದ ಕಾಪಿ ಮಾಡಿ, ಅಥವಾ ಹೀಗೆ ಬರೆಯಿರಿ: 150, 152',
    paste_xname: 'x ನ ಹೆಸರು (ಐಚ್ಛಿಕ)',
    paste_yname: 'y ನ ಹೆಸರು (ಐಚ್ಛಿಕ)',
    paste_go: 'ಈ ಡೇಟಾ ಬಳಸಿ',
    paste_bad: 'ಸಂಖ್ಯೆಗಳ ಜೋಡಿ ಸಿಗಲಿಲ್ಲ. ಪ್ರತಿ ಸಾಲಿನಲ್ಲಿ ಎರಡು ಸಂಖ್ಯೆ ಬರೆಯಿರಿ.',
    paste_ok: '{n} ಬಿಂದುಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ.',
    before_label: 'ಹಿಂದೆ',
    best_label: 'ಅತ್ಯುತ್ತಮ',
    err_word: 'ದೋಷ',
    graph_aria: '{n} ಬಿಂದುಗಳ ಗ್ರಾಫ್: ಅಡ್ಡಲಾಗಿ {x}, ಮೇಲ್ಮುಖವಾಗಿ {y}, ಮಾದರಿ ರೇಖೆಯೊಂದಿಗೆ.',
    points_n: '{n} ಬಿಂದುಗಳು',
    canvas_hint_manual: 'ರೇಖೆಯನ್ನು ಓರೆ ಮಾಡಲು ದುಂಡು ಹ್ಯಾಂಡಲ್ ಎಳೆಯಿರಿ, ಅಥವಾ ರೇಖೆಯನ್ನು ಮೇಲೆ-ಕೆಳಗೆ ಎಳೆಯಿರಿ. ಖಾಲಿ ಜಾಗದಲ್ಲಿ ಟ್ಯಾಪ್ ಮಾಡಿ ಬಿಂದು ಸೇರಿಸಿ, ಎಳೆದು ಸರಿಸಿ, ಎರಡು ಬಾರಿ ಟ್ಯಾಪ್ ಮಾಡಿ ಅಳಿಸಿ.',
    canvas_hint_auto: 'ಟ್ಯಾಪ್ ಮಾಡಿ ಬಿಂದು ಸೇರಿಸಿ, ಎಳೆದು ಸರಿಸಿ, ಎರಡು ಬಾರಿ ಟ್ಯಾಪ್ ಮಾಡಿ ಅಳಿಸಿ. ನಂತರ AI ಮತ್ತೆ ಕಲಿಯಲಿ.',
    canvas_hint_predict: 'ಅಂದಾಜಿಗಾಗಿ x ಆರಿಸಲು ಗ್ರಾಫ್‌ನಲ್ಲಿ ಎಲ್ಲಾದರೂ ಟ್ಯಾಪ್ ಮಾಡಿ.',
    ws_title: 'ವರ್ಕ್‌ಶೀಟ್: ಅತ್ಯುತ್ತಮ ಹೊಂದಾಣಿಕೆ ರೇಖೆ',
    ws_name: 'ಹೆಸರು: ______________   ತರಗತಿ: ______   ದಿನಾಂಕ: __________',
    ws_q1: 'ಮೇಲಿನ ಗ್ರಾಫ್‌ನ ರೇಖೆಯ ಸಮೀಕರಣ ಬರೆಯಿರಿ. ಈ ಡೇಟಾಗೆ m ಮತ್ತು c ಅರ್ಥವೇನು?',
    ws_q2: 'ಯಾವುದಾದರೂ ಎರಡು ಬಿಂದುಗಳನ್ನು ಆರಿಸಿ. ಪ್ರತಿಯೊಂದರ ದೋಷ (y − ŷ) ಮತ್ತು ದೋಷದ ವರ್ಗ ಕಂಡುಹಿಡಿಯಿರಿ.',
    ws_q3: 'ರೇಖೆ ಬಳಸಿ x = {x} ಆದಾಗ y ಅಂದಾಜಿಸಿ. ನಿಮ್ಮ ಲೆಕ್ಕ ತೋರಿಸಿ.',
    ws_q4: 'ದೋಷಗಳನ್ನು ನೇರವಾಗಿ ಕೂಡಿಸುವ ಬದಲು ಅವುಗಳ ವರ್ಗ ಏಕೆ ಮಾಡುತ್ತೇವೆ?',
    ws_q5: 'ಗ್ರೇಡಿಯಂಟ್ ಡಿಸೆಂಟ್‌ನಲ್ಲಿ ಲರ್ನಿಂಗ್ ರೇಟ್ ತುಂಬಾ ದೊಡ್ಡದಾದರೆ ಏನಾಗುತ್ತದೆ? ತುಂಬಾ ಚಿಕ್ಕದಾದರೆ?',
    howto: 'ಹೇಗೆ ಬಳಸುವುದು / ತರಗತಿಗೆ ಐಡಿಯಾಗಳು',
    tip1: '"ಕೈಯಿಂದ ಹೊಂದಿಸಿ" ಯಿಂದ ಶುರು ಮಾಡಿ: ಲಾಸ್ ಸಾಧ್ಯವಾದಷ್ಟು ಕಡಿಮೆಯಾಗುವವರೆಗೆ ರೇಖೆ ಎಳೆಯಿರಿ. ನಂತರ ಹೋಲಿಸಲು "ಅತ್ಯುತ್ತಮ ರೇಖೆ" ಆನ್ ಮಾಡಿ.',
    tip2: '"ದೋಷಗಳ ವರ್ಗ" ಆನ್ ಮಾಡಿ: ಒಂದು ದೊಡ್ಡ ತಪ್ಪು ಹಲವು ಸಣ್ಣ ತಪ್ಪುಗಳಿಗಿಂತ ಏಕೆ ಹೆಚ್ಚು ಲೆಕ್ಕಕ್ಕೆ ಬರುತ್ತದೆ ಎಂದು ಚೌಕಗಳು ತೋರಿಸುತ್ತವೆ.',
    tip3: '"AI ಕಲಿಯಲಿ" ತೆರೆದು "ಚಲಾಯಿಸಿ" ಒತ್ತಿ. ಇಳಿಯುವ ಲಾಸ್ ವಕ್ರವೇ "ಟ್ರೈನಿಂಗ್". ನಂತರ ಲರ್ನಿಂಗ್ ರೇಟ್ ಪ್ರಯೋಗಗಳನ್ನು ಮಾಡಿ.',
    tip4: 'ತರಗತಿ ಚಟುವಟಿಕೆ: 10–15 ಸಹಪಾಠಿಗಳ ಎತ್ತರ ಮತ್ತು ತೋಳುಗಳ ಅಗಲ ಅಳೆಯಿರಿ, "ಡೇಟಾ ಅಂಟಿಸಿ" ಮೂಲಕ ಸೇರಿಸಿ, ಹೊಸ ವಿದ್ಯಾರ್ಥಿಯ ತೋಳುಗಳ ಅಗಲ ಅಂದಾಜಿಸಿ.',
    tip5: '"ಅಂದಾಜು" ಬಳಸಿ ಚರ್ಚಿಸಿ: ವಾರಕ್ಕೆ 40 ಗಂಟೆ ಓದುವ ವಿದ್ಯಾರ್ಥಿಯ ಅಂಕವನ್ನು ರೇಖೆ ಹೇಳಬಲ್ಲದೇ? ಏಕೆ ಇಲ್ಲ?',
    tip6: 'ಮುದ್ರಿಸಿದರೆ ಗ್ರಾಫ್, ಡೇಟಾ ಕೋಷ್ಟಕ ಮತ್ತು 5 ಪ್ರಶ್ನೆಗಳ ವರ್ಕ್‌ಶೀಟ್ ಸಿಗುತ್ತದೆ. ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಪೂರ್ಣ ಪರದೆ ಚೆನ್ನಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.'
  },

  ml: {
    app_title: 'ഏറ്റവും ചേരുന്ന രേഖ',
    intro: 'ഡാറ്റയിൽ നിന്ന് AI ഒരു നേർരേഖ എങ്ങനെ പഠിക്കുന്നു എന്ന് കാണൂ: പിശക്, ലോസ്, ഗ്രേഡിയന്റ് ഡിസെന്റ്, പ്രവചനം.',
    data_label: 'ഡാറ്റ',
    restore: 'ഡാറ്റ തിരികെ കൊണ്ടുവരിക',
    clear_dots: 'ബിന്ദുക്കൾ മായ്ക്കുക',
    restored: 'യഥാർത്ഥ ഡാറ്റ തിരികെ വന്നു.',
    confirm_clear: 'നിങ്ങളുടെ എല്ലാ ബിന്ദുക്കളും നീക്കണോ?',
    paste_btn: 'ഡാറ്റ പേസ്റ്റ് ചെയ്യുക',
    show_label: 'കാണിക്കുക:',
    show_res: 'പിശകുകൾ',
    show_sq: 'പിശകുകളുടെ വർഗം',
    show_best: 'മികച്ച രേഖ',
    eq_label: 'മോഡൽ (രേഖ)',
    loss_label: 'ലോസ് (MSE)',
    miss: 'സാധാരണ പിഴവ് ≈ {v}',
    closeness: 'മികച്ചതിനോട് എത്ര അടുത്ത്',
    tab_manual: 'കൈകൊണ്ട് ചേർക്കുക',
    tab_auto: 'AI പഠിക്കട്ടെ',
    tab_predict: 'പ്രവചിക്കുക',
    manual_hint: 'ചുവന്ന പിശക്-വരകൾ കഴിയുന്നത്ര ചെറുതാകുന്ന വിധം രേഖ നീക്കുക. ലോസ് കുറയുന്നത് നോക്കൂ.',
    slope: 'ചരിവ് m',
    slope_hint: 'x ഒന്ന് കൂടുമ്പോൾ y എത്ര മാറുന്നു.',
    intercept: 'അന്തഃഖണ്ഡം c',
    intercept_hint: 'രേഖ x = 0-നെ സന്ധിക്കുന്നിടത്തെ y-യുടെ വില.',
    reset_line: 'വീണ്ടും പരന്ന രേഖ',
    coach_m0: 'രേഖ ബിന്ദുക്കളിൽ നിന്ന് വളരെ അകലെയാണ്. വട്ടത്തിലുള്ള ഹാൻഡിലുകളോ ചരിവ് സ്ലൈഡറോ ഉപയോഗിച്ച് ചരിക്കുക.',
    coach_m1: 'അടുത്തെത്തുന്നു! രേഖയുടെ ഇരുവശത്തെയും ചുവന്ന വരകൾ ചെറുതാക്കുക.',
    coach_m2: 'വളരെ അടുത്ത്. m, c എന്നിവയിലെ ചെറിയ മാറ്റങ്ങൾ ബാക്കിയുള്ള ലോസും കുറയ്ക്കും.',
    coach_m3: 'ഗംഭീരം! നിങ്ങളുടെ രേഖ ഏതാണ്ട് മികച്ച രേഖ തന്നെ. ഇനി "AI പഠിക്കട്ടെ" യുമായി താരതമ്യം ചെയ്യൂ.',
    need_points: 'വ്യത്യസ്ത x വിലകളുള്ള കുറഞ്ഞത് 2 ബിന്ദുക്കൾ ചേർക്കുക.',
    same_x: 'എല്ലാ ബിന്ദുക്കൾക്കും ഒരേ x ആണ്, അതിനാൽ ചരിഞ്ഞ രേഖ കിട്ടില്ല. ഒരു ബിന്ദു വശത്തേക്ക് നീക്കുക.',
    exact_title: 'കൃത്യമായ ഉത്തരം (ലഘുതമ വർഗ രീതി)',
    exact_hint: 'നേർരേഖയ്ക്ക് ഒരു സൂത്രവാക്യം ഒറ്റയടിക്ക് മികച്ച m, c കണ്ടെത്തുന്നു.',
    exact_btn: 'മികച്ച രേഖ കണ്ടെത്തുക',
    follow: 'ബിന്ദുക്കൾ നീക്കുമ്പോൾ മികച്ച രേഖ നിലനിർത്തുക',
    show_math: 'കണക്കുകൂട്ടൽ കാണിക്കുക',
    gd_title: 'ഗ്രേഡിയന്റ് ഡിസെന്റ്: AI എങ്ങനെ പഠിക്കുന്നു',
    gd_hint: 'AI ഒരു പരന്ന രേഖയിൽ നിന്ന് തുടങ്ങുന്നു. ഓരോ എപ്പോക്കിലും എല്ലാ ബിന്ദുക്കളും നോക്കി m, c എന്നിവയെ ലോസിന്റെ ചരിവിലൂടെ അൽപം താഴേക്ക് നീക്കുന്നു.',
    lr_label: 'ലേണിംഗ് റേറ്റ് (ചുവടിന്റെ വലുപ്പം)',
    lr_tiny: 'വളരെ ചെറുത്: സുരക്ഷിതം, പക്ഷേ വളരെ പതുക്കെ.',
    lr_small: 'ചെറുത്: സ്ഥിരം, പക്ഷേ പതുക്കെ.',
    lr_good: 'നല്ലത്: വേഗവും സ്ഥിരതയും.',
    lr_big: 'വളരെ വലുത്: ചുവടുകൾ കടന്നുപോകും, ലോസ് പൊട്ടിത്തെറിക്കാം!',
    epochs_label: 'ഒരു തവണ എപ്പോക്കുകൾ',
    speed_label: 'വേഗം',
    speed_slow: 'പതുക്കെ',
    speed_normal: 'സാധാരണ',
    speed_fast: 'വേഗത്തിൽ',
    gd_step: 'ഒരു ചുവട്',
    gd_run: 'ഓടിക്കുക',
    gd_restart: 'വീണ്ടും തുടങ്ങുക',
    epoch_label: 'എപ്പോക്ക്',
    best_possible: 'സാധ്യമായ ഏറ്റവും കുറവ്',
    loss_chart: 'ലോസ് വക്രം: ഓരോ എപ്പോക്കിനും ശേഷമുള്ള ലോസ്',
    chart_empty: 'ലോസ് കുറയുന്നത് കാണാൻ "ഒരു ചുവട്" അല്ലെങ്കിൽ "ഓടിക്കുക" അമർത്തുക.',
    coach_gd_need: 'ആദ്യം വ്യത്യസ്ത x വിലകളുള്ള കുറഞ്ഞത് 2 ബിന്ദുക്കൾ ചേർക്കുക.',
    coach_gd_explode: 'ലോസ് പൊട്ടിത്തെറിച്ചു! ലേണിംഗ് റേറ്റ് വളരെ വലുതാണ്. ചെറുത് തിരഞ്ഞെടുത്ത് "വീണ്ടും തുടങ്ങുക" അമർത്തുക.',
    coach_gd_up: 'ലോസ് കൂടുന്നു: ഓരോ ചുവടും താഴ്‌വര ചാടിക്കടക്കുന്നു. ലേണിംഗ് റേറ്റ് കുറയ്ക്കുക.',
    coach_gd_done: 'പഠനം കഴിഞ്ഞു! ലോസ് ഇപ്പോൾ സാധ്യമായ ഏറ്റവും കുറഞ്ഞ ലോസിന് ഏതാണ്ട് തുല്യമാണ്.',
    coach_gd_running: 'പഠിക്കുന്നു… രേഖ നീങ്ങുന്നതും ലോസ് വക്രം താഴുന്നതും നോക്കൂ.',
    coach_gd_idle: 'ഒരു മാറ്റം കാണാൻ "ഒരു ചുവട്", ഒരുപാട് എപ്പോക്കുകൾ കാണാൻ "ഓടിക്കുക" അമർത്തുക.',
    coach_gd_slow: 'ലോസ് കുറയുന്നുണ്ട്, പക്ഷേ പതുക്കെ; ലേണിംഗ് റേറ്റ് ചെറുതാണ്. കൂടുതൽ എപ്പോക്കുകൾ ഓടിക്കുക, അല്ലെങ്കിൽ റേറ്റ് കൂട്ടുക.',
    coach_gd_progress: 'ലോസ് കുറയുന്നു. പഠനം തുടരാൻ വീണ്ടും "ഓടിക്കുക" അമർത്തുക.',
    pred_title: 'പുതിയ വില പ്രവചിക്കുക',
    pred_hint: 'x തിരഞ്ഞെടുക്കുക, അല്ലെങ്കിൽ ഗ്രാഫിൽ ടാപ്പ് ചെയ്യുക. രേഖ നൽകുന്ന പ്രവചനം: ŷ = m × x + c',
    pred_answer: 'പ്രവചനം ŷ',
    pred_outside: 'ശ്രദ്ധിക്കുക: ഈ x ഡാറ്റയുടെ പരിധിക്ക് ({a} മുതൽ {b} വരെ) പുറത്താണ്. ഡാറ്റയിൽ നിന്ന് അകലെയുള്ള പ്രവചനങ്ങൾ വളരെ തെറ്റാകാം.',
    pred_negative: 'രേഖ പൂജ്യത്തിൽ താഴെയുള്ള വില പ്രവചിക്കുന്നു, ഇവിടെ അത് അസാധ്യമാണ്. ഒരു നേർരേഖയ്ക്ക് എല്ലാം വിശദീകരിക്കാനാവില്ല.',
    pred_tip_best: 'നുറുങ്ങ്: ഈ രേഖ ഇനിയും മികച്ചതല്ല. നല്ല പ്രവചനത്തിന് "AI പഠിക്കട്ടെ" തുറന്ന് "മികച്ച രേഖ കണ്ടെത്തുക" അമർത്തുക.',
    explain_title: 'മനസ്സിലാക്കുക',
    exp_title: 'ഒരു പരീക്ഷണം ചെയ്തുനോക്കൂ',
    exp_outlier: '📍 ഒരു ഔട്ട്‌ലയർ ചേർക്കുക',
    exp_small: '🐢 ലേണിംഗ് റേറ്റ് വളരെ ചെറുത്',
    exp_right: '👍 ലേണിംഗ് റേറ്റ് കൃത്യം',
    exp_big: '💥 ലേണിംഗ് റേറ്റ് വളരെ വലുത്',
    exp_outlier_msg: 'മറ്റുള്ളവയിൽ നിന്ന് വളരെ അകലെ ഒരു വിചിത്ര ബിന്ദു ചേർത്തു. ചാരനിറത്തിലുള്ള ഇടവിട്ട രേഖ മുമ്പത്തെ മികച്ച രേഖയാണ്; പുതിയ മികച്ച രേഖ ഔട്ട്‌ലയറിലേക്ക് വലിക്കപ്പെട്ടു. ആ ബിന്ദു വലിച്ചുനോക്കൂ, ഒരൊറ്റ ബിന്ദുവിന് മോഡലിനെ എത്ര മാറ്റാനാകുമെന്ന്.',
    exp_small_msg: 'ലേണിംഗ് റേറ്റ് 0.01: ഓരോ ചുവടും വളരെ ചെറുതാണ്, അതിനാൽ 200 എപ്പോക്കുകൾക്ക് ശേഷവും രേഖ മികച്ച സ്ഥാനത്ത് എത്തിയില്ല. ലോസ് വക്രം എത്ര പതുക്കെ താഴുന്നു എന്ന് നോക്കൂ.',
    exp_right_msg: 'ലേണിംഗ് റേറ്റ് 0.6: ലോസ് വേഗം കുറയുന്നു, രേഖ മികച്ച സ്ഥാനത്ത് ഉറയ്ക്കുന്നു.',
    exp_big_msg: 'ലേണിംഗ് റേറ്റ് 1.5: ഓരോ ചുവടും താഴ്‌വര കടന്ന് മറുവശത്ത് കൂടുതൽ ഉയരത്തിൽ വീഴുന്നു. ലോസ് കുറയുന്നതിനു പകരം പൊട്ടിത്തെറിക്കുന്നു.',
    table_title: 'ഡാറ്റ പട്ടികയും പിശകുകളും',
    add_row: 'വരി ചേർക്കുക',
    dl_csv: 'CSV ഡൗൺലോഡ്',
    col_pred: 'പ്രവചിച്ച ŷ',
    col_err: 'പിശക് y − ŷ',
    col_sq: 'പിശകിന്റെ വർഗം',
    del_row: 'വരി {n} നീക്കുക',
    mse_line: 'പിശകുകളുടെ വർഗങ്ങളുടെ തുക = {s}. അതിനെ {n} ബിന്ദുക്കൾ കൊണ്ട് ഹരിക്കുക: MSE = {v}.',
    own_empty: 'ബിന്ദുക്കൾ ചേർക്കാൻ ഗ്രാഫിൽ ടാപ്പ് ചെയ്യുക.',
    max_points: 'പരമാവധി {n} ബിന്ദുക്കൾ.',
    kept_inside: 'വില ഗ്രാഫിനുള്ളിൽ തന്നെ നിർത്തി.',
    paste_title: 'നിങ്ങളുടെ ഡാറ്റ പേസ്റ്റ് ചെയ്യുക',
    paste_hint: 'സംഖ്യകളുടെ രണ്ട് കോളം (x, y) പേസ്റ്റ് ചെയ്യുക, ഓരോ വരിയിലും ഒരു ജോടി. Excel അല്ലെങ്കിൽ Google Sheets-ൽ നിന്ന് കോപ്പി ചെയ്യാം, അല്ലെങ്കിൽ ഇങ്ങനെ ടൈപ്പ് ചെയ്യാം: 150, 152',
    paste_xname: 'x-ന്റെ പേര് (ഐച്ഛികം)',
    paste_yname: 'y-യുടെ പേര് (ഐച്ഛികം)',
    paste_go: 'ഈ ഡാറ്റ ഉപയോഗിക്കുക',
    paste_bad: 'സംഖ്യാ ജോടികൾ ഒന്നും കിട്ടിയില്ല. ഓരോ വരിയിലും രണ്ട് സംഖ്യകൾ എഴുതുക.',
    paste_ok: '{n} ബിന്ദുക്കൾ ചേർത്തു.',
    before_label: 'മുമ്പ്',
    best_label: 'മികച്ചത്',
    err_word: 'പിശക്',
    graph_aria: '{n} ബിന്ദുക്കളുടെ ഗ്രാഫ്: കുറുകെ {x}, മുകളിലേക്ക് {y}, മോഡൽ രേഖയോടൊപ്പം.',
    points_n: '{n} ബിന്ദുക്കൾ',
    canvas_hint_manual: 'രേഖ ചരിക്കാൻ വട്ട ഹാൻഡിൽ വലിക്കുക, അല്ലെങ്കിൽ രേഖ മുകളിലേക്കോ താഴേക്കോ വലിക്കുക. ഒഴിഞ്ഞ ഇടത്ത് ടാപ്പ് ചെയ്ത് ബിന്ദു ചേർക്കുക, വലിച്ച് നീക്കുക, രണ്ടുതവണ ടാപ്പ് ചെയ്ത് നീക്കം ചെയ്യുക.',
    canvas_hint_auto: 'ടാപ്പ് ചെയ്ത് ബിന്ദു ചേർക്കുക, വലിച്ച് നീക്കുക, രണ്ടുതവണ ടാപ്പ് ചെയ്ത് നീക്കം ചെയ്യുക. പിന്നെ AI വീണ്ടും പഠിക്കട്ടെ.',
    canvas_hint_predict: 'പ്രവചനത്തിനുള്ള x തിരഞ്ഞെടുക്കാൻ ഗ്രാഫിൽ എവിടെയെങ്കിലും ടാപ്പ് ചെയ്യുക.',
    ws_title: 'വർക്ക്ഷീറ്റ്: ഏറ്റവും ചേരുന്ന രേഖ',
    ws_name: 'പേര്: ______________   ക്ലാസ്: ______   തീയതി: __________',
    ws_q1: 'മുകളിലെ ഗ്രാഫിലെ രേഖയുടെ സമവാക്യം എഴുതുക. ഈ ഡാറ്റയിൽ m, c എന്നിവയുടെ അർത്ഥം എന്ത്?',
    ws_q2: 'ഏതെങ്കിലും രണ്ട് ബിന്ദുക്കൾ തിരഞ്ഞെടുക്കുക. ഓരോന്നിന്റെയും പിശകും (y − ŷ) പിശകിന്റെ വർഗവും കണ്ടെത്തുക.',
    ws_q3: 'രേഖ ഉപയോഗിച്ച് x = {x} ആകുമ്പോൾ y പ്രവചിക്കുക. കണക്കുകൂട്ടൽ കാണിക്കുക.',
    ws_q4: 'പിശകുകൾ നേരിട്ട് കൂട്ടുന്നതിനു പകരം നാം അവയുടെ വർഗം എടുക്കുന്നത് എന്തുകൊണ്ട്?',
    ws_q5: 'ഗ്രേഡിയന്റ് ഡിസെന്റിൽ ലേണിംഗ് റേറ്റ് വളരെ വലുതായാൽ എന്തു സംഭവിക്കും? വളരെ ചെറുതായാൽ?',
    howto: 'എങ്ങനെ ഉപയോഗിക്കാം / ക്ലാസ് മുറിക്കുള്ള ആശയങ്ങൾ',
    tip1: '"കൈകൊണ്ട് ചേർക്കുക" യിൽ തുടങ്ങൂ: ലോസ് കഴിയുന്നത്ര കുറയുന്നതുവരെ രേഖ വലിക്കുക. പിന്നെ താരതമ്യത്തിന് "മികച്ച രേഖ" ഓൺ ചെയ്യുക.',
    tip2: '"പിശകുകളുടെ വർഗം" ഓൺ ചെയ്യുക: ഒരു വലിയ പിഴവ് ഒരുപാട് ചെറിയ പിഴവുകളേക്കാൾ എന്തുകൊണ്ട് കൂടുതൽ എണ്ണപ്പെടുന്നു എന്ന് ചതുരങ്ങൾ കാണിക്കും.',
    tip3: '"AI പഠിക്കട്ടെ" തുറന്ന് "ഓടിക്കുക" അമർത്തുക. താഴുന്ന ലോസ് വക്രമാണ് "ട്രെയിനിംഗ്". പിന്നെ ലേണിംഗ് റേറ്റ് പരീക്ഷണങ്ങൾ ചെയ്തുനോക്കൂ.',
    tip4: 'ക്ലാസ് പ്രവർത്തനം: 10–15 സഹപാഠികളുടെ ഉയരവും കൈവിരിവും അളന്ന്, "ഡാറ്റ പേസ്റ്റ് ചെയ്യുക" വഴി ചേർത്ത്, പുതിയ ഒരു വിദ്യാർത്ഥിയുടെ കൈവിരിവ് പ്രവചിക്കുക.',
    tip5: '"പ്രവചിക്കുക" ഉപയോഗിച്ച് ചർച്ച ചെയ്യൂ: ആഴ്ചയിൽ 40 മണിക്കൂർ പഠിക്കുന്ന കുട്ടിയുടെ മാർക്ക് രേഖയ്ക്ക് പറയാനാകുമോ? എന്തുകൊണ്ട് ഇല്ല?',
    tip6: 'പ്രിന്റ് ചെയ്താൽ ഗ്രാഫും ഡാറ്റ പട്ടികയും 5 ചോദ്യങ്ങളുള്ള വർക്ക്ഷീറ്റും കിട്ടും. സ്മാർട്ട്ബോർഡിൽ ഫുൾസ്ക്രീൻ നന്നായി പ്രവർത്തിക്കും.'
  },

  ur: {
    app_title: 'بہترین فٹ لکیر',
    intro: 'دیکھیے AI ڈیٹا سے ایک سیدھی لکیر کیسے سیکھتا ہے: غلطی، لاس، گریڈینٹ ڈیسنٹ اور اندازے۔',
    data_label: 'ڈیٹا',
    restore: 'ڈیٹا واپس لائیں',
    clear_dots: 'نقطے مٹائیں',
    restored: 'اصل ڈیٹا واپس آ گیا۔',
    confirm_clear: 'اپنے سارے نقطے ہٹا دیں؟',
    paste_btn: 'ڈیٹا پیسٹ کریں',
    show_label: 'دکھائیں:',
    show_res: 'غلطیاں',
    show_sq: 'غلطیوں کے مربع',
    show_best: 'بہترین لکیر',
    eq_label: 'ماڈل (لکیر)',
    loss_label: 'لاس (MSE)',
    miss: 'عام چُوک ≈ {v}',
    closeness: 'بہترین سے کتنی قریب',
    tab_manual: 'ہاتھ سے بٹھائیں',
    tab_auto: 'AI کو سیکھنے دیں',
    tab_predict: 'اندازہ',
    manual_hint: 'لکیر کو ایسے کھسکائیں کہ سرخ غلطی کی لکیریں جتنی ہو سکیں چھوٹی ہو جائیں۔ لاس کو گھٹتے دیکھیں۔',
    slope: 'ڈھلان m (جھکاؤ)',
    slope_hint: 'x کے 1 بڑھنے پر y کتنا بدلتا ہے۔',
    intercept: 'قطع c',
    intercept_hint: 'جہاں لکیر x = 0 سے ملتی ہے، وہاں y کی قیمت۔',
    reset_line: 'پھر سے سپاٹ لکیر',
    coach_m0: 'لکیر نقطوں سے بہت دور ہے۔ گول ہینڈل یا ڈھلان سلائیڈر سے اسے جھکائیے۔',
    coach_m1: 'قریب آ رہے ہیں! لکیر کے دونوں طرف سرخ لکیروں کو چھوٹا کیجیے۔',
    coach_m2: 'بہت قریب۔ m اور c میں چھوٹی تبدیلی سے باقی لاس بھی گھٹ جائے گا۔',
    coach_m3: 'شاباش! آپ کی لکیر تقریباً بہترین لکیر ہے۔ اب "AI کو سیکھنے دیں" سے موازنہ کیجیے۔',
    need_points: 'الگ الگ x والے کم از کم 2 نقطے جوڑیں۔',
    same_x: 'سب نقطوں کا x ایک جیسا ہے، اس لیے کوئی ترچھی لکیر نہیں مل سکتی۔ کسی ایک نقطے کو ایک طرف کھسکائیں۔',
    exact_title: 'درست جواب (کم سے کم مربعوں کا طریقہ)',
    exact_hint: 'سیدھی لکیر کے لیے ایک فارمولا ایک ہی بار میں بہترین m اور c نکال دیتا ہے۔',
    exact_btn: 'بہترین لکیر تلاش کریں',
    follow: 'نقطے کھسکاتے وقت بہترین لکیر برقرار رکھیں',
    show_math: 'حساب دکھائیں',
    gd_title: 'گریڈینٹ ڈیسنٹ: AI کیسے سیکھتا ہے',
    gd_hint: 'AI ایک سپاٹ لکیر سے شروع کرتا ہے۔ ہر ایپوک میں وہ سارے نقطے دیکھتا ہے اور m اور c کو لاس کی ڈھلان پر تھوڑا نیچے کی طرف کھسکاتا ہے۔',
    lr_label: 'لرننگ ریٹ (قدم کا سائز)',
    lr_tiny: 'بہت چھوٹا: محفوظ، مگر بہت سست۔',
    lr_small: 'چھوٹا: مستحکم، مگر سست۔',
    lr_good: 'اچھا: تیز اور مستحکم۔',
    lr_big: 'بہت بڑا: قدم آگے نکل جاتے ہیں اور لاس پھٹ سکتا ہے!',
    epochs_label: 'ایک بار میں ایپوک',
    speed_label: 'رفتار',
    speed_slow: 'آہستہ',
    speed_normal: 'عام',
    speed_fast: 'تیز',
    gd_step: 'ایک قدم',
    gd_run: 'چلائیں',
    gd_restart: 'دوبارہ شروع',
    epoch_label: 'ایپوک',
    best_possible: 'کم سے کم ممکن',
    loss_chart: 'لاس کا خم: ہر ایپوک کے بعد کا لاس',
    chart_empty: 'لاس کو گھٹتے دیکھنے کے لیے "ایک قدم" یا "چلائیں" دبائیں۔',
    coach_gd_need: 'پہلے الگ الگ x والے کم از کم 2 نقطے جوڑیں۔',
    coach_gd_explode: 'لاس پھٹ گیا! لرننگ ریٹ بہت بڑا ہے۔ چھوٹا چنیں اور "دوبارہ شروع" دبائیں۔',
    coach_gd_up: 'لاس بڑھ رہا ہے: ہر قدم وادی کے پار کود رہا ہے۔ لرننگ ریٹ کم کیجیے۔',
    coach_gd_done: 'سیکھنا مکمل! اب لاس تقریباً کم سے کم ممکن لاس کے برابر ہے۔',
    coach_gd_running: 'سیکھ رہا ہے… لکیر کو کھسکتے اور لاس کے خم کو گرتے دیکھیے۔',
    coach_gd_idle: 'ایک تبدیلی دیکھنے کے لیے "ایک قدم" دبائیں، یا کئی ایپوک دیکھنے کے لیے "چلائیں"۔',
    coach_gd_slow: 'لاس گھٹ رہا ہے، مگر آہستہ، کیونکہ لرننگ ریٹ چھوٹا ہے۔ مزید ایپوک چلائیں یا ریٹ بڑھائیں۔',
    coach_gd_progress: 'لاس گھٹ رہا ہے۔ سیکھتے رہنے کے لیے پھر "چلائیں" دبائیں۔',
    pred_title: 'نئی قیمت کا اندازہ',
    pred_hint: 'x چنیں یا گراف پر ٹیپ کریں۔ لکیر اندازہ دیتی ہے: ŷ = m × x + c',
    pred_answer: 'اندازہ ŷ',
    pred_outside: 'احتیاط: یہ x ڈیٹا کی حد ({a} سے {b}) سے باہر ہے۔ ڈیٹا سے دور کے اندازے بہت غلط ہو سکتے ہیں۔',
    pred_negative: 'لکیر صفر سے کم قیمت بتا رہی ہے، جو یہاں ناممکن ہے۔ سیدھی لکیر ہر چیز نہیں سمجھا سکتی۔',
    pred_tip_best: 'مشورہ: یہ لکیر ابھی بہترین نہیں۔ بہتر اندازے کے لیے "AI کو سیکھنے دیں" کھول کر "بہترین لکیر تلاش کریں" دبائیں۔',
    explain_title: 'اسے سمجھیں',
    exp_title: 'ایک تجربہ کر کے دیکھیں',
    exp_outlier: '📍 ایک آؤٹ لائر جوڑیں',
    exp_small: '🐢 لرننگ ریٹ بہت چھوٹا',
    exp_right: '👍 لرننگ ریٹ بالکل ٹھیک',
    exp_big: '💥 لرننگ ریٹ بہت بڑا',
    exp_outlier_msg: 'باقی سب سے بہت دور ایک انوکھا نقطہ جوڑا گیا ہے۔ سرمئی ڈیش والی لکیر پہلے کی بہترین لکیر تھی؛ نئی بہترین لکیر آؤٹ لائر کی طرف کھنچ گئی ہے۔ اس نقطے کو کھینچ کر دیکھیے کہ ایک نقطہ ماڈل کو کتنا بدل سکتا ہے۔',
    exp_small_msg: 'لرننگ ریٹ 0.01: ہر قدم بہت چھوٹا ہے، اس لیے 200 ایپوک کے بعد بھی لکیر بہترین جگہ تک نہیں پہنچی۔ دیکھیے لاس کا خم کتنا آہستہ گرتا ہے۔',
    exp_right_msg: 'لرننگ ریٹ 0.6: لاس تیزی سے گھٹتا ہے اور لکیر بہترین جگہ پر ٹک جاتی ہے۔',
    exp_big_msg: 'لرننگ ریٹ 1.5: ہر قدم وادی کے پار کود کر دوسری طرف اور اوپر جا پہنچتا ہے۔ لاس گھٹنے کے بجائے پھٹ جاتا ہے۔',
    table_title: 'ڈیٹا جدول اور غلطیاں',
    add_row: 'قطار جوڑیں',
    dl_csv: 'CSV ڈاؤن لوڈ کریں',
    col_pred: 'اندازہ ŷ',
    col_err: 'غلطی y − ŷ',
    col_sq: 'غلطی کا مربع',
    del_row: 'قطار {n} ہٹائیں',
    mse_line: 'غلطیوں کے مربعوں کا مجموعہ = {s}۔ اسے {n} نقطوں سے تقسیم کریں: MSE = {v}۔',
    own_empty: 'نقطے جوڑنے کے لیے گراف پر ٹیپ کریں۔',
    max_points: 'زیادہ سے زیادہ {n} نقطے۔',
    kept_inside: 'قیمت کو گراف کے اندر ہی رکھا گیا۔',
    paste_title: 'اپنا ڈیٹا پیسٹ کریں',
    paste_hint: 'عددوں کے دو کالم (x اور y) پیسٹ کریں، ہر لائن میں ایک جوڑی۔ Excel یا Google Sheets سے کاپی کریں، یا ایسے لکھیں: 150, 152',
    paste_xname: 'x کا نام (اختیاری)',
    paste_yname: 'y کا نام (اختیاری)',
    paste_go: 'یہ ڈیٹا استعمال کریں',
    paste_bad: 'عددوں کی کوئی جوڑی نہیں ملی۔ ہر لائن میں دو عدد لکھیں۔',
    paste_ok: '{n} نقطے جوڑے گئے۔',
    before_label: 'پہلے',
    best_label: 'بہترین',
    err_word: 'غلطی',
    graph_aria: '{n} نقطوں کا گراف: افقی {x} اور عمودی {y}، ساتھ میں ماڈل لکیر۔',
    points_n: '{n} نقطے',
    canvas_hint_manual: 'لکیر جھکانے کے لیے گول ہینڈل کھینچیں، یا لکیر کو اوپر نیچے کھینچیں۔ خالی جگہ ٹیپ کر کے نقطہ جوڑیں، کھینچ کر کھسکائیں، دو بار ٹیپ کر کے ہٹائیں۔',
    canvas_hint_auto: 'ٹیپ کر کے نقطہ جوڑیں، کھینچ کر کھسکائیں، دو بار ٹیپ کر کے ہٹائیں۔ پھر AI کو دوبارہ سیکھنے دیں۔',
    canvas_hint_predict: 'اندازے کے لیے x چننے کو گراف پر کہیں بھی ٹیپ کریں۔',
    ws_title: 'ورک شیٹ: بہترین فٹ لکیر',
    ws_name: 'نام: ______________   جماعت: ______   تاریخ: __________',
    ws_q1: 'اوپر کے گراف والی لکیر کی مساوات لکھیے۔ اس ڈیٹا کے لیے m اور c کا کیا مطلب ہے؟',
    ws_q2: 'کوئی دو نقطے چنیے۔ ہر ایک کی غلطی (y − ŷ) اور غلطی کا مربع نکالیے۔',
    ws_q3: 'لکیر سے x = {x} ہونے پر y کا اندازہ لگائیے۔ اپنا حساب دکھائیے۔',
    ws_q4: 'ہم غلطیوں کو سیدھا جوڑنے کے بجائے ان کا مربع کیوں لیتے ہیں؟',
    ws_q5: 'گریڈینٹ ڈیسنٹ میں لرننگ ریٹ بہت بڑا ہو تو کیا ہوتا ہے؟ بہت چھوٹا ہو تو؟',
    howto: 'استعمال کا طریقہ / کلاس کے لیے خیالات',
    tip1: '"ہاتھ سے بٹھائیں" سے شروع کریں: لکیر کو تب تک کھینچیں جب تک لاس جتنا ہو سکے کم نہ ہو جائے۔ پھر موازنے کے لیے "بہترین لکیر" آن کریں۔',
    tip2: '"غلطیوں کے مربع" آن کریں: ڈبے دکھاتے ہیں کہ ایک بڑی چُوک کئی چھوٹی چُوکوں سے کہیں زیادہ کیوں گنی جاتی ہے۔',
    tip3: '"AI کو سیکھنے دیں" کھول کر "چلائیں" دبائیں۔ گرتا ہوا لاس کا خم ہی "ٹریننگ" ہے۔ پھر لرننگ ریٹ والے تجربے آزمائیں۔',
    tip4: 'کلاس کی سرگرمی: 10–15 ہم جماعتوں کا قد اور بازوؤں کا پھیلاؤ ناپیں، "ڈیٹا پیسٹ کریں" سے جوڑیں، اور نئے طالب علم کے پھیلاؤ کا اندازہ لگائیں۔',
    tip5: '"اندازہ" سے بحث کریں: کیا لکیر ہفتے میں 40 گھنٹے پڑھنے والے کے نمبر بتا سکتی ہے؟ کیوں نہیں؟',
    tip6: 'پرنٹ کرنے پر گراف، ڈیٹا جدول اور 5 سوالوں والی ورک شیٹ ملتی ہے۔ اسمارٹ بورڈ پر فل اسکرین اچھا چلتا ہے۔'
  }
};
