/* UI strings for every language. Keys are identical in all 12 languages.
   Shared words (start, next, copy, print, ...) come from EDU.COMMON. */
window.APP_STRINGS = {};

window.APP_STRINGS.en = {
  app_title: 'Flashcards',
  intro: 'Make your own flashcards and remember them for longer with spaced repetition, a typing quiz and a matching game.',
  deck: 'Deck', new_deck: 'New deck', new_deck_name: 'My deck {n}', untitled: 'Untitled deck',
  stat_cards: 'Cards', stat_due: 'Due today', stat_streak: 'Day streak',
  boxes_caption: 'Leitner boxes: every time you remember a card, it moves up one box and comes back later.',
  box_n: 'Box {n}', every_1: 'daily', every_2: 'every 2 days', every_4: 'every 4 days', every_7: 'weekly', every_14: 'every 2 weeks',
  modes: 'Ways to practise', tab_study: 'Study', tab_quiz: 'Quiz', tab_match: 'Match', tab_edit: 'Edit cards',
  no_cards: 'This deck has no cards yet.', go_edit: 'Add cards',
  due_label: 'cards to review today', all_done: 'All done for today! 🎉',
  next_due: 'Next review: {when}.', more_due: 'Still due today: {n} more cards.',
  when_today: 'today', when_tomorrow: 'tomorrow', when_days: 'in {n} days',
  session_size: 'Cards in one session', all: 'All', reverse: 'Show the back first',
  start_study: 'Start studying', cram: 'Practise all cards', cram_badge: 'Practice round: boxes do not change',
  front: 'Front', back: 'Back',
  flip_hint: 'Think of the answer first, then tap the card to turn it over.',
  show_answer: 'Show answer', knew: 'I knew it', again: 'Still learning', read_aloud: 'Read aloud',
  end_session: 'End session', progress_label: 'Cards learnt in this session',
  sum_title: 'Session complete!', sum_knew: 'Knew on the first try', sum_again: 'Still learning', sum_score: 'Score',
  sum_moved: 'Moved up a box: {up} · Back to Box 1: {down}',
  study_again: 'Practise the hard ones again',
  need_cards: 'First add cards in “Edit cards” (at least {n}).',
  quiz_title: 'Type-the-answer quiz', quiz_help: 'Read the clue and type the answer. Small spelling mistakes are okay.',
  answer_side: 'What will you type?', side_back: 'The back', side_front: 'The front',
  questions: 'Questions', start_quiz: 'Start quiz', q_of: 'Question {n} of {total}',
  type_back: 'Type the back of this card', type_front: 'Type the front of this card',
  your_answer: 'Your answer', check: 'Check', dont_know: 'I don\'t know',
  answer_label: 'Answer:', almost: 'Correct! Check the spelling:', override: 'I was right',
  quiz_end: 'End quiz', quiz_done: 'Quiz finished',
  msg_great: 'Excellent! You know these well. 🌟', msg_good: 'Good work! Practise the mistakes once more.',
  msg_try: 'Keep going! Study the cards, then try again.',
  mistakes: 'Mistakes to review', you_wrote: 'You wrote:', skipped: 'Skipped',
  retry_mistakes: 'Retry the wrong ones', new_quiz: 'New quiz',
  pairs: 'Pairs', new_game: 'New game',
  match_help: 'Tap a card, then tap its partner. Match all the pairs as fast as you can.',
  time_s: '{n} s', tries_n: 'Tries: {n}', best_s: 'Best: {n} s',
  match_done: 'All matched! Time: {s} s · Tries: {n} 🎉', new_best: 'New best time!',
  deck_name: 'Deck name', add_card_title: 'Add a card', edit_card_title: 'Edit card {n}',
  front_ph: 'e.g. Assam', back_ph: 'e.g. Dispur',
  add_picture: 'Add picture', remove_picture: 'Remove picture',
  img_note: 'Pictures are made small and saved only on this device.',
  img_bad: 'Could not use this picture. Try a JPG or PNG file.',
  img_full: 'Not enough space for more pictures. Remove some pictures first.',
  add_card: 'Add card', save_card: 'Save card', card_added: 'Card added', card_saved: 'Card saved',
  need_both: 'Fill in both the front and the back.',
  deck_full: 'A deck can have at most {n} cards.', too_many_decks: 'You can keep at most {n} decks. Delete one first.',
  bulk_title: 'Add many cards at once',
  bulk_help: 'One card per line, like “front - back”. You can also paste two columns from Excel or Google Sheets.',
  bulk_ph: 'Kerala - Thiruvananthapuram\nKarnataka - Bengaluru\nOdisha - Bhubaneswar',
  bulk_found: 'Ready to add: {n}', bulk_skipped: 'Lines skipped (no “ - ”): {n}',
  bulk_add: 'Add all', bulk_added: 'Cards added: {n}',
  cards_title: 'Cards in this deck', search_cards: 'Search cards',
  list_empty: 'No cards yet. Add your first card above.', no_results: 'No cards match your search.',
  card_new: 'New', card_box: 'Box {n} · {when}', card_deleted: 'Card deleted.', undo: 'Undo',
  share_title: 'Share, import and print', make_link: 'Make share link',
  link_ready: 'Send this link to your students. It opens this deck on their phone, ready to save.',
  link_long: 'This link is very long. If it does not open, share the CSV file instead.',
  link_file: 'You opened this app from a file, so this link works only on this computer. Use the online app or share the CSV file.',
  no_img_note: 'Pictures are not included in links and CSV files.',
  whatsapp: 'WhatsApp', export_csv: 'Export CSV', import_file: 'Import CSV', print_sheet: 'Print fold-over sheet',
  csv_note: 'CSV files have two columns: front and back. They open in Excel and Google Sheets.',
  more_title: 'More options', backup: 'Backup all decks',
  restore_q: 'Add {n} decks from this backup file?', restored: 'Decks added: {n}',
  reset_progress: 'Reset progress', confirm_progress: 'Put every card of this deck back in Box 1?',
  progress_reset: 'All cards are back in Box 1.',
  add_samples: 'Add sample decks', samples_added: 'Sample decks added: {n}', samples_present: 'All sample decks are already here.',
  delete_deck: 'Delete deck', confirm_delete: 'Delete the deck “{name}” and all its cards?', deck_deleted: 'Deck deleted',
  import_title: 'Import a deck', import_count: 'Cards: {n}', import_dup: 'You already have this deck.',
  open_copy: 'Open my copy', import_save: 'Save as a new deck', import_merge: 'Add to the open deck',
  import_saved: 'Deck saved. Start studying!', import_more: '…and {n} more',
  bad_link: 'This link is broken or incomplete. Ask your teacher to send it again.',
  bad_file: 'No cards found in this file. Use two columns: front and back.',
  storage_full: 'Could not save. This device is out of space.',
  print_name: 'Name', print_class: 'Class', print_date: 'Date',
  print_tip: 'Fold the page along the dotted line. Read the front, say the answer, then open the fold to check.',
  help_title: 'How to use · Ideas for the classroom',
  help_1: 'Pick a deck and press “Start studying”. Think of the answer, then turn the card over.',
  help_2: 'Be honest: press “I knew it” only if you really remembered it. Easy cards come back later, hard cards come back tomorrow. Study a little every day!',
  help_3: 'Make your own deck in “Edit cards”, or paste a list like “Assam - Dispur”. Then send it to the class as a WhatsApp link.',
  help_4: 'Class activity: open Match on the smartboard, pick 8 pairs and let two teams take turns. The team with fewer tries wins!',
  help_5: 'For homework, print the fold-over sheet: students fold the page and test themselves. Use Quiz for quick revision before a test.',
  help_6: 'Keyboard: Space turns the card, 1 = I knew it, 2 = Still learning.',
  inside_title: 'What’s happening inside? (spaced repetition)',
  inside_text: 'Every card lives in one of 5 boxes. New and forgotten cards sit in Box 1 and come back every day. Each time you remember a card, it moves up one box and waits longer: 2 days, 4 days, a week, then 2 weeks. So you spend your time on what you don’t know yet, and remembering something just before you forget it makes the memory much stronger.'
};

window.APP_STRINGS.hi = {
  app_title: 'फ़्लैशकार्ड',
  intro: 'अपने फ़्लैशकार्ड बनाएँ और स्पेस्ड रिपिटिशन, टाइपिंग क्विज़ और जोड़ी मिलाओ खेल से उन्हें लंबे समय तक याद रखें।',
  deck: 'डेक', new_deck: 'नया डेक', new_deck_name: 'मेरा डेक {n}', untitled: 'बिना नाम का डेक',
  stat_cards: 'कार्ड', stat_due: 'आज दोहराने हैं', stat_streak: 'लगातार दिन',
  boxes_caption: 'लाइटनर बॉक्स: जब भी कोई कार्ड याद रहता है, वह एक बॉक्स ऊपर जाता है और देर से वापस आता है।',
  box_n: 'बॉक्स {n}', every_1: 'रोज़', every_2: 'हर 2 दिन', every_4: 'हर 4 दिन', every_7: 'हर हफ़्ते', every_14: 'हर 2 हफ़्ते',
  modes: 'अभ्यास के तरीके', tab_study: 'पढ़ें', tab_quiz: 'क्विज़', tab_match: 'जोड़ी मिलाओ', tab_edit: 'कार्ड बदलें',
  no_cards: 'इस डेक में अभी कोई कार्ड नहीं है।', go_edit: 'कार्ड जोड़ें',
  due_label: 'कार्ड आज दोहराने हैं', all_done: 'आज का काम पूरा! 🎉',
  next_due: 'अगली दोहराई: {when}।', more_due: 'आज {n} और कार्ड दोहराने बाकी हैं।',
  when_today: 'आज', when_tomorrow: 'कल', when_days: '{n} दिन बाद',
  session_size: 'एक बार में कितने कार्ड', all: 'सभी', reverse: 'पहले पीछे वाला हिस्सा दिखाएँ',
  start_study: 'पढ़ना शुरू करें', cram: 'सभी कार्ड का अभ्यास करें', cram_badge: 'अभ्यास राउंड: बॉक्स नहीं बदलेंगे',
  front: 'आगे का हिस्सा', back: 'पीछे का हिस्सा',
  flip_hint: 'पहले उत्तर सोचें, फिर कार्ड पर टैप करके उसे पलटें।',
  show_answer: 'उत्तर दिखाएँ', knew: 'मुझे याद था', again: 'अभी सीख रहे हैं', read_aloud: 'बोलकर सुनाएँ',
  end_session: 'सत्र खत्म करें', progress_label: 'इस सत्र में सीखे गए कार्ड',
  sum_title: 'सत्र पूरा हुआ!', sum_knew: 'पहली बार में याद था', sum_again: 'अभी सीख रहे हैं', sum_score: 'स्कोर',
  sum_moved: '{up} कार्ड एक बॉक्स ऊपर गए। {down} कार्ड वापस बॉक्स 1 में गए।',
  study_again: 'कठिन कार्ड फिर से दोहराएँ',
  need_cards: 'पहले “कार्ड बदलें” में कम से कम {n} कार्ड जोड़ें।',
  quiz_title: 'उत्तर टाइप करो क्विज़', quiz_help: 'संकेत पढ़ें और उत्तर टाइप करें। छोटी-मोटी स्पेलिंग की गलती चलेगी।',
  answer_side: 'आप क्या टाइप करेंगे?', side_back: 'पीछे वाला हिस्सा', side_front: 'आगे वाला हिस्सा',
  questions: 'सवाल', start_quiz: 'क्विज़ शुरू करें', q_of: 'सवाल {n} / {total}',
  type_back: 'इस कार्ड का पीछे वाला हिस्सा टाइप करें', type_front: 'इस कार्ड का आगे वाला हिस्सा टाइप करें',
  your_answer: 'आपका उत्तर', check: 'जाँचें', dont_know: 'मुझे नहीं पता',
  answer_label: 'उत्तर:', almost: 'सही! स्पेलिंग देख लें:', override: 'मेरा उत्तर सही था',
  quiz_end: 'क्विज़ खत्म करें', quiz_done: 'क्विज़ पूरा हुआ',
  msg_great: 'बहुत बढ़िया! आपको ये अच्छी तरह याद हैं। 🌟', msg_good: 'अच्छा काम! गलतियों का एक बार और अभ्यास करें।',
  msg_try: 'हिम्मत रखें! कार्ड पढ़ें, फिर दोबारा कोशिश करें।',
  mistakes: 'जिन्हें दोहराना है', you_wrote: 'आपने लिखा:', skipped: 'छोड़ दिया',
  retry_mistakes: 'गलत सवाल फिर से करें', new_quiz: 'नया क्विज़',
  pairs: 'जोड़ियाँ', new_game: 'नया खेल',
  match_help: 'एक कार्ड पर टैप करें, फिर उसकी जोड़ी पर। सारी जोड़ियाँ जितनी जल्दी हो सके मिलाएँ।',
  time_s: '{n} सेकंड', tries_n: 'कोशिशें: {n}', best_s: 'सबसे तेज़: {n} सेकंड',
  match_done: '{s} सेकंड और {n} कोशिशों में सारी जोड़ियाँ मिल गईं! 🎉', new_best: 'नया रिकॉर्ड!',
  deck_name: 'डेक का नाम', add_card_title: 'कार्ड जोड़ें', edit_card_title: 'कार्ड {n} बदलें',
  front_ph: 'जैसे: असम', back_ph: 'जैसे: दिसपुर',
  add_picture: 'तस्वीर जोड़ें', remove_picture: 'तस्वीर हटाएँ',
  img_note: 'तस्वीरें छोटी करके सिर्फ़ इसी डिवाइस पर सेव होती हैं।',
  img_bad: 'यह तस्वीर इस्तेमाल नहीं हो सकी। JPG या PNG फ़ाइल आज़माएँ।',
  img_full: 'और तस्वीरों के लिए जगह नहीं है। पहले कुछ तस्वीरें हटाएँ।',
  add_card: 'कार्ड जोड़ें', save_card: 'कार्ड सेव करें', card_added: 'कार्ड जुड़ गया', card_saved: 'कार्ड सेव हो गया',
  need_both: 'आगे और पीछे, दोनों भरें।',
  deck_full: 'एक डेक में ज़्यादा से ज़्यादा {n} कार्ड हो सकते हैं।', too_many_decks: 'आप ज़्यादा से ज़्यादा {n} डेक रख सकते हैं। पहले कोई डेक हटाएँ।',
  bulk_title: 'एक साथ कई कार्ड जोड़ें',
  bulk_help: 'हर लाइन में एक कार्ड, जैसे “आगे - पीछे”। Excel या Google Sheets से दो कॉलम भी पेस्ट कर सकते हैं।',
  bulk_ph: 'केरल - तिरुवनंतपुरम\nकर्नाटक - बेंगलुरु\nओडिशा - भुवनेश्वर',
  bulk_found: '{n} कार्ड जोड़ने के लिए तैयार', bulk_skipped: '{n} लाइनें छोड़ीं (“ - ” नहीं मिला)',
  bulk_add: 'सब जोड़ें', bulk_added: '{n} कार्ड जुड़ गए',
  cards_title: 'इस डेक के कार्ड', search_cards: 'कार्ड खोजें',
  list_empty: 'अभी कोई कार्ड नहीं है। ऊपर अपना पहला कार्ड जोड़ें।', no_results: 'आपकी खोज से कोई कार्ड नहीं मिला।',
  card_new: 'नया', card_box: 'बॉक्स {n} · {when}', card_deleted: 'कार्ड हटा दिया गया।', undo: 'वापस लाएँ',
  share_title: 'शेयर, इम्पोर्ट और प्रिंट', make_link: 'शेयर लिंक बनाएँ',
  link_ready: 'यह लिंक अपने विद्यार्थियों को भेजें। यह उनके फ़ोन पर यही डेक खोलेगा, सेव करने के लिए तैयार।',
  link_long: 'यह लिंक बहुत लंबा है। अगर न खुले, तो CSV फ़ाइल शेयर करें।',
  link_file: 'आपने यह ऐप फ़ाइल से खोला है, इसलिए यह लिंक सिर्फ़ इसी कंप्यूटर पर चलेगा। ऑनलाइन ऐप इस्तेमाल करें या CSV फ़ाइल शेयर करें।',
  no_img_note: 'तस्वीरें लिंक और CSV फ़ाइल में नहीं जातीं।',
  whatsapp: 'WhatsApp', export_csv: 'CSV एक्सपोर्ट करें', import_file: 'CSV इम्पोर्ट करें', print_sheet: 'मोड़ने वाली शीट प्रिंट करें',
  csv_note: 'CSV फ़ाइल में दो कॉलम होते हैं: आगे और पीछे। यह Excel और Google Sheets में खुलती है।',
  more_title: 'और विकल्प', backup: 'सभी डेक का बैकअप',
  restore_q: 'इस बैकअप फ़ाइल से {n} डेक जोड़ें?', restored: '{n} डेक जुड़ गए',
  reset_progress: 'प्रगति रीसेट करें', confirm_progress: 'इस डेक के सभी कार्ड वापस बॉक्स 1 में डालें?',
  progress_reset: 'सभी कार्ड वापस बॉक्स 1 में हैं।',
  add_samples: 'नमूना डेक जोड़ें', samples_added: '{n} नमूना डेक जुड़ गए', samples_present: 'सभी नमूना डेक पहले से मौजूद हैं।',
  delete_deck: 'डेक हटाएँ', confirm_delete: 'डेक “{name}” और उसके सभी कार्ड हटाएँ?', deck_deleted: 'डेक हटा दिया गया',
  import_title: 'डेक इम्पोर्ट करें', import_count: '{n} कार्ड', import_dup: 'यह डेक आपके पास पहले से है।',
  open_copy: 'मेरी कॉपी खोलें', import_save: 'नए डेक के रूप में सेव करें', import_merge: 'खुले हुए डेक में जोड़ें',
  import_saved: 'डेक सेव हो गया। पढ़ना शुरू करें!', import_more: '…और {n} कार्ड',
  bad_link: 'यह लिंक टूटा हुआ या अधूरा है। अपने शिक्षक से इसे फिर से भेजने को कहें।',
  bad_file: 'इस फ़ाइल में कोई कार्ड नहीं मिला। दो कॉलम रखें: आगे और पीछे।',
  storage_full: 'सेव नहीं हो सका। इस डिवाइस में जगह नहीं बची।',
  print_name: 'नाम', print_class: 'कक्षा', print_date: 'तारीख',
  print_tip: 'पेज को बिंदु वाली लाइन पर मोड़ें। आगे वाला हिस्सा पढ़ें, उत्तर बोलें, फिर मोड़ खोलकर जाँचें।',
  help_title: 'कैसे इस्तेमाल करें · कक्षा के लिए आइडिया',
  help_1: 'एक डेक चुनें और “पढ़ना शुरू करें” दबाएँ। उत्तर सोचें, फिर कार्ड पलटें।',
  help_2: 'ईमानदार रहें: “मुझे याद था” तभी दबाएँ जब सच में याद हो। आसान कार्ड देर से लौटते हैं, कठिन कार्ड कल फिर आते हैं। रोज़ थोड़ा-थोड़ा पढ़ें!',
  help_3: '“कार्ड बदलें” में अपना डेक बनाएँ, या “असम - दिसपुर” जैसी सूची पेस्ट करें। फिर इसे कक्षा को WhatsApp लिंक से भेजें।',
  help_4: 'कक्षा गतिविधि: स्मार्टबोर्ड पर “जोड़ी मिलाओ” खोलें, 8 जोड़ियाँ चुनें और दो टीमों को बारी-बारी खेलने दें। कम कोशिशों वाली टीम जीतेगी!',
  help_5: 'होमवर्क के लिए मोड़ने वाली शीट प्रिंट करें: विद्यार्थी पेज मोड़कर खुद को जाँचें। टेस्ट से पहले जल्दी दोहराने के लिए क्विज़ चलाएँ।',
  help_6: 'कीबोर्ड: Space से कार्ड पलटें, 1 = मुझे याद था, 2 = अभी सीख रहे हैं।',
  inside_title: 'अंदर क्या हो रहा है? (स्पेस्ड रिपिटिशन)',
  inside_text: 'हर कार्ड 5 में से किसी एक बॉक्स में रहता है। नए और भूले हुए कार्ड बॉक्स 1 में रहते हैं और रोज़ आते हैं। हर बार याद रहने पर कार्ड एक बॉक्स ऊपर जाता है और ज़्यादा दिन बाद लौटता है: 2 दिन, 4 दिन, एक हफ़्ता, फिर 2 हफ़्ते। इससे आपका समय उन चीज़ों पर लगता है जो अभी याद नहीं हैं, और भूलने से ठीक पहले याद करने पर याददाश्त बहुत पक्की हो जाती है।'
};

window.APP_STRINGS.bn = {
  app_title: 'ফ্ল্যাশকার্ড',
  intro: 'নিজের ফ্ল্যাশকার্ড বানান, তারপর স্পেসড রিপিটিশন, টাইপিং কুইজ আর জোড়া মেলানোর খেলায় অনেক দিন মনে রাখুন।',
  deck: 'ডেক', new_deck: 'নতুন ডেক', new_deck_name: 'আমার ডেক {n}', untitled: 'নামহীন ডেক',
  stat_cards: 'কার্ড', stat_due: 'আজ ঝালাতে হবে', stat_streak: 'টানা দিন',
  boxes_caption: 'লাইটনার বাক্স: কোনো কার্ড মনে থাকলে সেটি এক বাক্স উপরে যায় আর দেরিতে ফিরে আসে।',
  box_n: 'বাক্স {n}', every_1: 'রোজ', every_2: 'প্রতি 2 দিনে', every_4: 'প্রতি 4 দিনে', every_7: 'প্রতি সপ্তাহে', every_14: 'প্রতি 2 সপ্তাহে',
  modes: 'অনুশীলনের উপায়', tab_study: 'পড়ুন', tab_quiz: 'কুইজ', tab_match: 'জোড়া মেলাও', tab_edit: 'কার্ড সম্পাদনা',
  no_cards: 'এই ডেকে এখনও কোনো কার্ড নেই।', go_edit: 'কার্ড যোগ করুন',
  due_label: 'কার্ড আজ ঝালাতে হবে', all_done: 'আজকের কাজ শেষ! 🎉',
  next_due: 'পরের বার ঝালাই: {when}।', more_due: 'আজ আরও {n}টি কার্ড ঝালানো বাকি।',
  when_today: 'আজ', when_tomorrow: 'আগামীকাল', when_days: '{n} দিন পরে',
  session_size: 'একবারে কটি কার্ড', all: 'সব', reverse: 'আগে পেছনের দিক দেখাও',
  start_study: 'পড়া শুরু করুন', cram: 'সব কার্ড অনুশীলন করুন', cram_badge: 'অনুশীলন রাউন্ড: বাক্স বদলাবে না',
  front: 'সামনের দিক', back: 'পেছনের দিক',
  flip_hint: 'আগে উত্তরটা ভাবুন, তারপর কার্ডে ট্যাপ করে উল্টে দিন।',
  show_answer: 'উত্তর দেখুন', knew: 'আমার মনে ছিল', again: 'এখনও শিখছি', read_aloud: 'জোরে পড়ে শোনাও',
  end_session: 'সেশন শেষ করুন', progress_label: 'এই সেশনে শেখা কার্ড',
  sum_title: 'সেশন শেষ!', sum_knew: 'প্রথম বারেই মনে ছিল', sum_again: 'এখনও শিখছি', sum_score: 'স্কোর',
  sum_moved: '{up}টি কার্ড এক বাক্স উপরে গেল। {down}টি কার্ড আবার বাক্স 1-এ ফিরল।',
  study_again: 'কঠিনগুলো আবার অনুশীলন করুন',
  need_cards: 'আগে “কার্ড সম্পাদনা”-য় অন্তত {n}টি কার্ড যোগ করুন।',
  quiz_title: 'উত্তর টাইপ করার কুইজ', quiz_help: 'সূত্র পড়ে উত্তর টাইপ করুন। ছোটখাটো বানান ভুল চলবে।',
  answer_side: 'আপনি কী টাইপ করবেন?', side_back: 'পেছনের দিক', side_front: 'সামনের দিক',
  questions: 'প্রশ্ন', start_quiz: 'কুইজ শুরু করুন', q_of: 'প্রশ্ন {n} / {total}',
  type_back: 'এই কার্ডের পেছনের দিক টাইপ করুন', type_front: 'এই কার্ডের সামনের দিক টাইপ করুন',
  your_answer: 'আপনার উত্তর', check: 'যাচাই করুন', dont_know: 'আমি জানি না',
  answer_label: 'উত্তর:', almost: 'সঠিক! বানানটা দেখে নিন:', override: 'আমার উত্তর ঠিক ছিল',
  quiz_end: 'কুইজ শেষ করুন', quiz_done: 'কুইজ শেষ',
  msg_great: 'দারুণ! এগুলো আপনার ভালো মনে আছে। 🌟', msg_good: 'ভালো হয়েছে! ভুলগুলো আর একবার অনুশীলন করুন।',
  msg_try: 'চালিয়ে যান! কার্ডগুলো পড়ে আবার চেষ্টা করুন।',
  mistakes: 'যেগুলো আবার দেখতে হবে', you_wrote: 'আপনি লিখেছেন:', skipped: 'বাদ দেওয়া হয়েছে',
  retry_mistakes: 'ভুল প্রশ্নগুলো আবার করুন', new_quiz: 'নতুন কুইজ',
  pairs: 'জোড়া', new_game: 'নতুন খেলা',
  match_help: 'একটি কার্ডে ট্যাপ করুন, তারপর তার জোড়ায়। যত তাড়াতাড়ি পারেন সব জোড়া মেলান।',
  time_s: '{n} সেকেন্ড', tries_n: 'চেষ্টা: {n}', best_s: 'সেরা: {n} সেকেন্ড',
  match_done: '{s} সেকেন্ডে {n}টি চেষ্টায় সব জোড়া মিলেছে! 🎉', new_best: 'নতুন রেকর্ড!',
  deck_name: 'ডেকের নাম', add_card_title: 'কার্ড যোগ করুন', edit_card_title: 'কার্ড {n} সম্পাদনা',
  front_ph: 'যেমন: অসম', back_ph: 'যেমন: দিসপুর',
  add_picture: 'ছবি যোগ করুন', remove_picture: 'ছবি সরান',
  img_note: 'ছবি ছোট করে শুধু এই ডিভাইসে সেভ হয়।',
  img_bad: 'এই ছবিটি ব্যবহার করা গেল না। JPG বা PNG ফাইল দিয়ে চেষ্টা করুন।',
  img_full: 'আর ছবির জায়গা নেই। আগে কিছু ছবি সরান।',
  add_card: 'কার্ড যোগ করুন', save_card: 'কার্ড সেভ করুন', card_added: 'কার্ড যোগ হয়েছে', card_saved: 'কার্ড সেভ হয়েছে',
  need_both: 'সামনে আর পেছনে, দুটোই লিখুন।',
  deck_full: 'একটি ডেকে বড়জোর {n}টি কার্ড রাখা যায়।', too_many_decks: 'বড়জোর {n}টি ডেক রাখা যায়। আগে একটি মুছে ফেলুন।',
  bulk_title: 'একসঙ্গে অনেক কার্ড যোগ করুন',
  bulk_help: 'প্রতি লাইনে একটি কার্ড, যেমন “সামনে - পেছনে”। Excel বা Google Sheets থেকে দুটি কলামও পেস্ট করতে পারেন।',
  bulk_ph: 'কেরল - তিরুবনন্তপুরম\nকর্ণাটক - বেঙ্গালুরু\nওড়িশা - ভুবনেশ্বর',
  bulk_found: '{n}টি কার্ড যোগ করার জন্য তৈরি', bulk_skipped: '{n}টি লাইন বাদ গেছে (“ - ” পাওয়া যায়নি)',
  bulk_add: 'সব যোগ করুন', bulk_added: '{n}টি কার্ড যোগ হয়েছে',
  cards_title: 'এই ডেকের কার্ড', search_cards: 'কার্ড খুঁজুন',
  list_empty: 'এখনও কোনো কার্ড নেই। উপরে প্রথম কার্ডটি যোগ করুন।', no_results: 'খোঁজার সঙ্গে কোনো কার্ড মেলেনি।',
  card_new: 'নতুন', card_box: 'বাক্স {n} · {when}', card_deleted: 'কার্ড মুছে ফেলা হয়েছে।', undo: 'ফিরিয়ে আনুন',
  share_title: 'শেয়ার, ইমপোর্ট আর প্রিন্ট', make_link: 'শেয়ার লিংক বানান',
  link_ready: 'এই লিংকটি ছাত্রছাত্রীদের পাঠান। এটি তাদের ফোনে এই ডেকটি খুলবে, সেভ করার জন্য তৈরি।',
  link_long: 'লিংকটি খুব লম্বা। না খুললে CSV ফাইল শেয়ার করুন।',
  link_file: 'আপনি অ্যাপটি ফাইল থেকে খুলেছেন, তাই এই লিংক শুধু এই কম্পিউটারেই চলবে। অনলাইন অ্যাপ ব্যবহার করুন বা CSV ফাইল শেয়ার করুন।',
  no_img_note: 'লিংক আর CSV ফাইলে ছবি যায় না।',
  whatsapp: 'WhatsApp', export_csv: 'CSV এক্সপোর্ট', import_file: 'CSV ইমপোর্ট', print_sheet: 'ভাঁজ করার শিট প্রিন্ট করুন',
  csv_note: 'CSV ফাইলে দুটি কলাম থাকে: সামনে আর পেছনে। এটি Excel ও Google Sheets-এ খোলে।',
  more_title: 'আরও বিকল্প', backup: 'সব ডেকের ব্যাকআপ',
  restore_q: 'এই ব্যাকআপ ফাইল থেকে {n}টি ডেক যোগ করবেন?', restored: '{n}টি ডেক যোগ হয়েছে',
  reset_progress: 'অগ্রগতি রিসেট', confirm_progress: 'এই ডেকের সব কার্ড আবার বাক্স 1-এ রাখবেন?',
  progress_reset: 'সব কার্ড আবার বাক্স 1-এ।',
  add_samples: 'নমুনা ডেক যোগ করুন', samples_added: '{n}টি নমুনা ডেক যোগ হয়েছে', samples_present: 'সব নমুনা ডেক আগে থেকেই আছে।',
  delete_deck: 'ডেক মুছুন', confirm_delete: '“{name}” ডেক আর তার সব কার্ড মুছে ফেলবেন?', deck_deleted: 'ডেক মুছে ফেলা হয়েছে',
  import_title: 'ডেক ইমপোর্ট করুন', import_count: '{n}টি কার্ড', import_dup: 'এই ডেকটি আপনার কাছে আগে থেকেই আছে।',
  open_copy: 'আমার কপি খুলুন', import_save: 'নতুন ডেক হিসেবে সেভ করুন', import_merge: 'খোলা ডেকে যোগ করুন',
  import_saved: 'ডেক সেভ হয়েছে। পড়া শুরু করুন!', import_more: '…আর {n}টি',
  bad_link: 'এই লিংকটি ভাঙা বা অসম্পূর্ণ। শিক্ষককে আবার পাঠাতে বলুন।',
  bad_file: 'এই ফাইলে কোনো কার্ড পাওয়া যায়নি। দুটি কলাম রাখুন: সামনে আর পেছনে।',
  storage_full: 'সেভ করা গেল না। এই ডিভাইসে জায়গা নেই।',
  print_name: 'নাম', print_class: 'শ্রেণি', print_date: 'তারিখ',
  print_tip: 'বিন্দু দেওয়া লাইন বরাবর পাতাটি ভাঁজ করুন। সামনের দিক পড়ুন, উত্তর বলুন, তারপর ভাঁজ খুলে মিলিয়ে নিন।',
  help_title: 'কীভাবে ব্যবহার করবেন · ক্লাসের জন্য আইডিয়া',
  help_1: 'একটি ডেক বেছে “পড়া শুরু করুন” টিপুন। উত্তর ভাবুন, তারপর কার্ড উল্টান।',
  help_2: 'সৎ থাকুন: সত্যিই মনে থাকলে তবেই “আমার মনে ছিল” টিপুন। সহজ কার্ড দেরিতে ফেরে, কঠিন কার্ড কালই ফেরে। রোজ একটু করে পড়ুন!',
  help_3: '“কার্ড সম্পাদনা”-য় নিজের ডেক বানান, বা “অসম - দিসপুর”-এর মতো তালিকা পেস্ট করুন। তারপর WhatsApp লিংকে ক্লাসে পাঠান।',
  help_4: 'ক্লাস অ্যাক্টিভিটি: স্মার্টবোর্ডে “জোড়া মেলাও” খুলুন, 8 জোড়া বাছুন আর দুই দলকে পালা করে খেলতে দিন। কম চেষ্টায় যে দল মেলাবে, সে জিতবে!',
  help_5: 'হোমওয়ার্কের জন্য ভাঁজ করার শিট প্রিন্ট করুন: ছাত্রছাত্রীরা পাতা ভাঁজ করে নিজেরাই যাচাই করবে। পরীক্ষার আগে দ্রুত ঝালাতে কুইজ চালান।',
  help_6: 'কিবোর্ড: Space দিয়ে কার্ড উল্টান, 1 = আমার মনে ছিল, 2 = এখনও শিখছি।',
  inside_title: 'ভেতরে কী হচ্ছে? (স্পেসড রিপিটিশন)',
  inside_text: 'প্রতিটি কার্ড 5টি বাক্সের কোনো একটিতে থাকে। নতুন আর ভুলে যাওয়া কার্ড থাকে বাক্স 1-এ, রোজ ফিরে আসে। প্রতিবার মনে থাকলে কার্ড এক বাক্স উপরে যায় আর বেশি দিন পরে ফেরে: 2 দিন, 4 দিন, এক সপ্তাহ, তারপর 2 সপ্তাহ। ফলে আপনার সময় যায় যা এখনও জানেন না তার পেছনে, আর ভুলে যাওয়ার ঠিক আগে মনে করলে স্মৃতি অনেক পাকা হয়।'
};

window.APP_STRINGS.mr = {
  app_title: 'फ्लॅशकार्ड',
  intro: 'स्वतःचे फ्लॅशकार्ड बनवा आणि स्पेस्ड रिपिटिशन, टायपिंग क्विझ व जोड्या जुळवा खेळाने ते जास्त काळ लक्षात ठेवा.',
  deck: 'डेक', new_deck: 'नवीन डेक', new_deck_name: 'माझा डेक {n}', untitled: 'नाव नसलेला डेक',
  stat_cards: 'कार्ड', stat_due: 'आज उजळणी', stat_streak: 'सलग दिवस',
  boxes_caption: 'लाइटनर बॉक्स: कार्ड लक्षात राहिले की ते एक बॉक्स वर जाते आणि उशिरा परत येते.',
  box_n: 'बॉक्स {n}', every_1: 'रोज', every_2: 'दर 2 दिवसांनी', every_4: 'दर 4 दिवसांनी', every_7: 'दर आठवड्याला', every_14: 'दर 2 आठवड्यांनी',
  modes: 'सरावाच्या पद्धती', tab_study: 'अभ्यास', tab_quiz: 'क्विझ', tab_match: 'जोड्या जुळवा', tab_edit: 'कार्ड बदला',
  no_cards: 'या डेकमध्ये अजून एकही कार्ड नाही.', go_edit: 'कार्ड जोडा',
  due_label: 'कार्डांची आज उजळणी करायची आहे', all_done: 'आजचे काम पूर्ण! 🎉',
  next_due: 'पुढची उजळणी: {when}.', more_due: 'आज अजून {n} कार्डांची उजळणी बाकी आहे.',
  when_today: 'आज', when_tomorrow: 'उद्या', when_days: '{n} दिवसांनी',
  session_size: 'एका वेळी किती कार्ड', all: 'सर्व', reverse: 'आधी मागची बाजू दाखवा',
  start_study: 'अभ्यास सुरू करा', cram: 'सर्व कार्डांचा सराव करा', cram_badge: 'सराव फेरी: बॉक्स बदलणार नाहीत',
  front: 'पुढची बाजू', back: 'मागची बाजू',
  flip_hint: 'आधी उत्तर आठवा, मग कार्डवर टॅप करून ते उलटा.',
  show_answer: 'उत्तर दाखवा', knew: 'मला आठवले', again: 'अजून शिकायचे आहे', read_aloud: 'मोठ्याने वाचून दाखवा',
  end_session: 'सत्र संपवा', progress_label: 'या सत्रात शिकलेली कार्ड',
  sum_title: 'सत्र पूर्ण!', sum_knew: 'पहिल्याच वेळी आठवले', sum_again: 'अजून शिकायचे आहे', sum_score: 'गुण',
  sum_moved: '{up} कार्ड एक बॉक्स वर गेली. {down} कार्ड परत बॉक्स 1 मध्ये गेली.',
  study_again: 'अवघड कार्डांचा पुन्हा सराव करा',
  need_cards: 'आधी “कार्ड बदला” मध्ये किमान {n} कार्ड जोडा.',
  quiz_title: 'उत्तर टाइप करा क्विझ', quiz_help: 'संकेत वाचा आणि उत्तर टाइप करा. छोट्या स्पेलिंग चुका चालतील.',
  answer_side: 'तुम्ही काय टाइप कराल?', side_back: 'मागची बाजू', side_front: 'पुढची बाजू',
  questions: 'प्रश्न', start_quiz: 'क्विझ सुरू करा', q_of: 'प्रश्न {n} / {total}',
  type_back: 'या कार्डची मागची बाजू टाइप करा', type_front: 'या कार्डची पुढची बाजू टाइप करा',
  your_answer: 'तुमचे उत्तर', check: 'तपासा', dont_know: 'मला माहीत नाही',
  answer_label: 'उत्तर:', almost: 'बरोबर! स्पेलिंग पाहून घ्या:', override: 'माझे उत्तर बरोबर होते',
  quiz_end: 'क्विझ संपवा', quiz_done: 'क्विझ पूर्ण',
  msg_great: 'उत्तम! तुम्हाला हे चांगले आठवते. 🌟', msg_good: 'छान! चुकांचा अजून एकदा सराव करा.',
  msg_try: 'प्रयत्न चालू ठेवा! कार्ड वाचा आणि पुन्हा प्रयत्न करा.',
  mistakes: 'पुन्हा पाहायचे प्रश्न', you_wrote: 'तुम्ही लिहिले:', skipped: 'सोडून दिले',
  retry_mistakes: 'चुकलेले प्रश्न पुन्हा सोडवा', new_quiz: 'नवीन क्विझ',
  pairs: 'जोड्या', new_game: 'नवीन खेळ',
  match_help: 'एका कार्डवर टॅप करा, मग त्याच्या जोडीवर. सर्व जोड्या शक्य तितक्या लवकर जुळवा.',
  time_s: '{n} सेकंद', tries_n: 'प्रयत्न: {n}', best_s: 'सर्वोत्तम: {n} सेकंद',
  match_done: '{s} सेकंदांत {n} प्रयत्नांत सर्व जोड्या जुळल्या! 🎉', new_best: 'नवीन विक्रम!',
  deck_name: 'डेकचे नाव', add_card_title: 'कार्ड जोडा', edit_card_title: 'कार्ड {n} बदला',
  front_ph: 'उदा. आसाम', back_ph: 'उदा. दिसपूर',
  add_picture: 'चित्र जोडा', remove_picture: 'चित्र काढा',
  img_note: 'चित्रे लहान करून फक्त याच डिव्हाइसवर सेव्ह होतात.',
  img_bad: 'हे चित्र वापरता आले नाही. JPG किंवा PNG फाइल वापरून पाहा.',
  img_full: 'अजून चित्रांसाठी जागा नाही. आधी काही चित्रे काढा.',
  add_card: 'कार्ड जोडा', save_card: 'कार्ड सेव्ह करा', card_added: 'कार्ड जोडले', card_saved: 'कार्ड सेव्ह झाले',
  need_both: 'पुढची आणि मागची, दोन्ही बाजू भरा.',
  deck_full: 'एका डेकमध्ये जास्तीत जास्त {n} कार्ड ठेवता येतात.', too_many_decks: 'जास्तीत जास्त {n} डेक ठेवता येतात. आधी एक काढून टाका.',
  bulk_title: 'एकदम अनेक कार्ड जोडा',
  bulk_help: 'प्रत्येक ओळीत एक कार्ड, जसे “पुढची - मागची”. Excel किंवा Google Sheets मधून दोन कॉलमही पेस्ट करू शकता.',
  bulk_ph: 'केरळ - तिरुवनंतपुरम\nकर्नाटक - बंगळुरू\nओडिशा - भुवनेश्वर',
  bulk_found: '{n} कार्ड जोडण्यासाठी तयार', bulk_skipped: '{n} ओळी सोडल्या (“ - ” सापडले नाही)',
  bulk_add: 'सर्व जोडा', bulk_added: '{n} कार्ड जोडली',
  cards_title: 'या डेकमधील कार्ड', search_cards: 'कार्ड शोधा',
  list_empty: 'अजून एकही कार्ड नाही. वर तुमचे पहिले कार्ड जोडा.', no_results: 'शोधाशी जुळणारे कार्ड नाही.',
  card_new: 'नवीन', card_box: 'बॉक्स {n} · {when}', card_deleted: 'कार्ड काढून टाकले.', undo: 'परत आणा',
  share_title: 'शेअर, इम्पोर्ट आणि प्रिंट', make_link: 'शेअर लिंक बनवा',
  link_ready: 'ही लिंक विद्यार्थ्यांना पाठवा. ती त्यांच्या फोनवर हाच डेक उघडेल, सेव्ह करण्यासाठी तयार.',
  link_long: 'ही लिंक खूप मोठी आहे. उघडली नाही तर CSV फाइल शेअर करा.',
  link_file: 'तुम्ही हे ॲप फाइलमधून उघडले आहे, त्यामुळे ही लिंक फक्त याच संगणकावर चालेल. ऑनलाइन ॲप वापरा किंवा CSV फाइल शेअर करा.',
  no_img_note: 'लिंक आणि CSV फाइलमध्ये चित्रे जात नाहीत.',
  whatsapp: 'WhatsApp', export_csv: 'CSV एक्सपोर्ट करा', import_file: 'CSV इम्पोर्ट करा', print_sheet: 'घडी घालायची शीट प्रिंट करा',
  csv_note: 'CSV फाइलमध्ये दोन कॉलम असतात: पुढची आणि मागची बाजू. ती Excel आणि Google Sheets मध्ये उघडते.',
  more_title: 'अधिक पर्याय', backup: 'सर्व डेकचा बॅकअप',
  restore_q: 'या बॅकअप फाइलमधून {n} डेक जोडायचे?', restored: '{n} डेक जोडले',
  reset_progress: 'प्रगती रीसेट करा', confirm_progress: 'या डेकमधील सर्व कार्ड परत बॉक्स 1 मध्ये ठेवायची?',
  progress_reset: 'सर्व कार्ड परत बॉक्स 1 मध्ये आहेत.',
  add_samples: 'नमुना डेक जोडा', samples_added: '{n} नमुना डेक जोडले', samples_present: 'सर्व नमुना डेक आधीच आहेत.',
  delete_deck: 'डेक काढून टाका', confirm_delete: '“{name}” डेक आणि त्यातील सर्व कार्ड काढून टाकायची?', deck_deleted: 'डेक काढून टाकला',
  import_title: 'डेक इम्पोर्ट करा', import_count: '{n} कार्ड', import_dup: 'हा डेक तुमच्याकडे आधीच आहे.',
  open_copy: 'माझी प्रत उघडा', import_save: 'नवीन डेक म्हणून सेव्ह करा', import_merge: 'उघड्या डेकमध्ये जोडा',
  import_saved: 'डेक सेव्ह झाला. अभ्यास सुरू करा!', import_more: '…आणि अजून {n}',
  bad_link: 'ही लिंक तुटलेली किंवा अपूर्ण आहे. शिक्षकांना ती पुन्हा पाठवायला सांगा.',
  bad_file: 'या फाइलमध्ये कार्ड सापडली नाहीत. दोन कॉलम ठेवा: पुढची आणि मागची बाजू.',
  storage_full: 'सेव्ह करता आले नाही. या डिव्हाइसवर जागा नाही.',
  print_name: 'नाव', print_class: 'इयत्ता', print_date: 'दिनांक',
  print_tip: 'ठिपक्यांच्या रेषेवर पान दुमडा. पुढची बाजू वाचा, उत्तर सांगा, मग घडी उघडून तपासा.',
  help_title: 'कसे वापरायचे · वर्गासाठी कल्पना',
  help_1: 'एक डेक निवडा आणि “अभ्यास सुरू करा” दाबा. उत्तर आठवा, मग कार्ड उलटा.',
  help_2: 'प्रामाणिक राहा: खरंच आठवले असेल तरच “मला आठवले” दाबा. सोपी कार्ड उशिरा परत येतात, अवघड कार्ड उद्याच परत येतात. रोज थोडा अभ्यास करा!',
  help_3: '“कार्ड बदला” मध्ये स्वतःचा डेक बनवा, किंवा “आसाम - दिसपूर” सारखी यादी पेस्ट करा. मग ती वर्गाला WhatsApp लिंकने पाठवा.',
  help_4: 'वर्ग उपक्रम: स्मार्टबोर्डवर “जोड्या जुळवा” उघडा, 8 जोड्या निवडा आणि दोन संघांना आळीपाळीने खेळू द्या. कमी प्रयत्नांत जुळवणारा संघ जिंकेल!',
  help_5: 'गृहपाठासाठी घडी घालायची शीट प्रिंट करा: विद्यार्थी पान दुमडून स्वतःची परीक्षा घेतील. परीक्षेआधी झटपट उजळणीसाठी क्विझ घ्या.',
  help_6: 'कीबोर्ड: Space ने कार्ड उलटा, 1 = मला आठवले, 2 = अजून शिकायचे आहे.',
  inside_title: 'आत काय चालले आहे? (स्पेस्ड रिपिटिशन)',
  inside_text: 'प्रत्येक कार्ड 5 पैकी एका बॉक्समध्ये असते. नवीन आणि विसरलेली कार्ड बॉक्स 1 मध्ये असतात आणि रोज येतात. प्रत्येक वेळी आठवले की कार्ड एक बॉक्स वर जाते आणि जास्त दिवसांनी परत येते: 2 दिवस, 4 दिवस, एक आठवडा, मग 2 आठवडे. त्यामुळे तुमचा वेळ जे अजून येत नाही त्यावर जातो, आणि विसरण्याच्या अगदी आधी आठवल्याने स्मरण खूप पक्के होते.'
};

window.APP_STRINGS.gu = {
  app_title: 'ફ્લેશકાર્ડ',
  intro: 'પોતાનાં ફ્લેશકાર્ડ બનાવો અને સ્પેસ્ડ રિપિટિશન, ટાઇપિંગ ક્વિઝ અને જોડી મેળવો રમતથી તેમને લાંબો સમય યાદ રાખો.',
  deck: 'ડેક', new_deck: 'નવો ડેક', new_deck_name: 'મારો ડેક {n}', untitled: 'નામ વગરનો ડેક',
  stat_cards: 'કાર્ડ', stat_due: 'આજે દોહરાવવાનાં', stat_streak: 'સળંગ દિવસ',
  boxes_caption: 'લાઇટનર બૉક્સ: કાર્ડ યાદ રહે ત્યારે તે એક બૉક્સ ઉપર જાય છે અને મોડું પાછું આવે છે.',
  box_n: 'બૉક્સ {n}', every_1: 'રોજ', every_2: 'દર 2 દિવસે', every_4: 'દર 4 દિવસે', every_7: 'દર અઠવાડિયે', every_14: 'દર 2 અઠવાડિયે',
  modes: 'અભ્યાસની રીતો', tab_study: 'અભ્યાસ', tab_quiz: 'ક્વિઝ', tab_match: 'જોડી મેળવો', tab_edit: 'કાર્ડ બદલો',
  no_cards: 'આ ડેકમાં હજી કોઈ કાર્ડ નથી.', go_edit: 'કાર્ડ ઉમેરો',
  due_label: 'કાર્ડ આજે દોહરાવવાનાં છે', all_done: 'આજનું કામ પૂરું! 🎉',
  next_due: 'આગળનું પુનરાવર્તન: {when}.', more_due: 'આજે હજી {n} કાર્ડ દોહરાવવાનાં બાકી છે.',
  when_today: 'આજે', when_tomorrow: 'આવતીકાલે', when_days: '{n} દિવસ પછી',
  session_size: 'એક વારમાં કેટલાં કાર્ડ', all: 'બધાં', reverse: 'પહેલાં પાછળની બાજુ બતાવો',
  start_study: 'અભ્યાસ શરૂ કરો', cram: 'બધાં કાર્ડનો અભ્યાસ કરો', cram_badge: 'અભ્યાસ રાઉન્ડ: બૉક્સ નહીં બદલાય',
  front: 'આગળની બાજુ', back: 'પાછળની બાજુ',
  flip_hint: 'પહેલાં જવાબ વિચારો, પછી કાર્ડ પર ટૅપ કરીને તેને ફેરવો.',
  show_answer: 'જવાબ બતાવો', knew: 'મને યાદ હતું', again: 'હજી શીખવાનું છે', read_aloud: 'મોટેથી વાંચી સંભળાવો',
  end_session: 'સત્ર પૂરું કરો', progress_label: 'આ સત્રમાં શીખેલાં કાર્ડ',
  sum_title: 'સત્ર પૂરું!', sum_knew: 'પહેલી વારમાં યાદ હતું', sum_again: 'હજી શીખવાનું છે', sum_score: 'સ્કોર',
  sum_moved: '{up} કાર્ડ એક બૉક્સ ઉપર ગયાં. {down} કાર્ડ પાછાં બૉક્સ 1 માં ગયાં.',
  study_again: 'અઘરાં કાર્ડનો ફરી અભ્યાસ કરો',
  need_cards: 'પહેલાં “કાર્ડ બદલો” માં ઓછામાં ઓછાં {n} કાર્ડ ઉમેરો.',
  quiz_title: 'જવાબ ટાઇપ કરો ક્વિઝ', quiz_help: 'સંકેત વાંચો અને જવાબ ટાઇપ કરો. નાની જોડણી ભૂલ ચાલશે.',
  answer_side: 'તમે શું ટાઇપ કરશો?', side_back: 'પાછળની બાજુ', side_front: 'આગળની બાજુ',
  questions: 'પ્રશ્નો', start_quiz: 'ક્વિઝ શરૂ કરો', q_of: 'પ્રશ્ન {n} / {total}',
  type_back: 'આ કાર્ડની પાછળની બાજુ ટાઇપ કરો', type_front: 'આ કાર્ડની આગળની બાજુ ટાઇપ કરો',
  your_answer: 'તમારો જવાબ', check: 'તપાસો', dont_know: 'મને ખબર નથી',
  answer_label: 'જવાબ:', almost: 'સાચું! જોડણી જોઈ લો:', override: 'મારો જવાબ સાચો હતો',
  quiz_end: 'ક્વિઝ પૂરી કરો', quiz_done: 'ક્વિઝ પૂરી',
  msg_great: 'ખૂબ સરસ! તમને આ સારી રીતે યાદ છે. 🌟', msg_good: 'સરસ! ભૂલોનો એક વાર ફરી અભ્યાસ કરો.',
  msg_try: 'હિંમત રાખો! કાર્ડ વાંચો અને ફરી પ્રયાસ કરો.',
  mistakes: 'ફરી જોવાના પ્રશ્નો', you_wrote: 'તમે લખ્યું:', skipped: 'છોડી દીધું',
  retry_mistakes: 'ખોટા પ્રશ્નો ફરી કરો', new_quiz: 'નવી ક્વિઝ',
  pairs: 'જોડી', new_game: 'નવી રમત',
  match_help: 'એક કાર્ડ પર ટૅપ કરો, પછી તેની જોડી પર. બધી જોડી બને એટલી ઝડપથી મેળવો.',
  time_s: '{n} સેકન્ડ', tries_n: 'પ્રયાસ: {n}', best_s: 'શ્રેષ્ઠ: {n} સેકન્ડ',
  match_done: '{s} સેકન્ડમાં {n} પ્રયાસમાં બધી જોડી મળી ગઈ! 🎉', new_best: 'નવો રેકૉર્ડ!',
  deck_name: 'ડેકનું નામ', add_card_title: 'કાર્ડ ઉમેરો', edit_card_title: 'કાર્ડ {n} બદલો',
  front_ph: 'જેમ કે: આસામ', back_ph: 'જેમ કે: દિસપુર',
  add_picture: 'ચિત્ર ઉમેરો', remove_picture: 'ચિત્ર કાઢો',
  img_note: 'ચિત્રો નાનાં કરીને ફક્ત આ ડિવાઇસ પર સેવ થાય છે.',
  img_bad: 'આ ચિત્ર વાપરી ન શકાયું. JPG કે PNG ફાઇલ અજમાવો.',
  img_full: 'વધુ ચિત્રો માટે જગ્યા નથી. પહેલાં થોડાં ચિત્રો કાઢો.',
  add_card: 'કાર્ડ ઉમેરો', save_card: 'કાર્ડ સેવ કરો', card_added: 'કાર્ડ ઉમેરાયું', card_saved: 'કાર્ડ સેવ થયું',
  need_both: 'આગળ અને પાછળ, બંને ભરો.',
  deck_full: 'એક ડેકમાં વધુમાં વધુ {n} કાર્ડ રાખી શકાય.', too_many_decks: 'વધુમાં વધુ {n} ડેક રાખી શકાય. પહેલાં એક કાઢી નાખો.',
  bulk_title: 'એકસાથે ઘણાં કાર્ડ ઉમેરો',
  bulk_help: 'દરેક લીટીમાં એક કાર્ડ, જેમ કે “આગળ - પાછળ”. Excel કે Google Sheets માંથી બે કૉલમ પણ પેસ્ટ કરી શકો.',
  bulk_ph: 'કેરળ - તિરુવનંતપુરમ\nકર્ણાટક - બેંગલુરુ\nઓડિશા - ભુવનેશ્વર',
  bulk_found: '{n} કાર્ડ ઉમેરવા તૈયાર', bulk_skipped: '{n} લીટી છોડી (“ - ” ન મળ્યું)',
  bulk_add: 'બધાં ઉમેરો', bulk_added: '{n} કાર્ડ ઉમેરાયાં',
  cards_title: 'આ ડેકનાં કાર્ડ', search_cards: 'કાર્ડ શોધો',
  list_empty: 'હજી કોઈ કાર્ડ નથી. ઉપર તમારું પહેલું કાર્ડ ઉમેરો.', no_results: 'તમારી શોધ સાથે કોઈ કાર્ડ મેળ ખાતું નથી.',
  card_new: 'નવું', card_box: 'બૉક્સ {n} · {when}', card_deleted: 'કાર્ડ કાઢી નાખ્યું.', undo: 'પાછું લાવો',
  share_title: 'શેર, ઇમ્પોર્ટ અને પ્રિન્ટ', make_link: 'શેર લિંક બનાવો',
  link_ready: 'આ લિંક તમારા વિદ્યાર્થીઓને મોકલો. તે તેમના ફોન પર આ જ ડેક ખોલશે, સેવ કરવા તૈયાર.',
  link_long: 'આ લિંક ખૂબ લાંબી છે. ન ખૂલે તો CSV ફાઇલ શેર કરો.',
  link_file: 'તમે આ ઍપ ફાઇલમાંથી ખોલી છે, એટલે આ લિંક ફક્ત આ જ કમ્પ્યુટર પર ચાલશે. ઑનલાઇન ઍપ વાપરો અથવા CSV ફાઇલ શેર કરો.',
  no_img_note: 'લિંક અને CSV ફાઇલમાં ચિત્રો જતાં નથી.',
  whatsapp: 'WhatsApp', export_csv: 'CSV એક્સપોર્ટ કરો', import_file: 'CSV ઇમ્પોર્ટ કરો', print_sheet: 'વાળવાની શીટ પ્રિન્ટ કરો',
  csv_note: 'CSV ફાઇલમાં બે કૉલમ હોય છે: આગળ અને પાછળ. તે Excel અને Google Sheets માં ખૂલે છે.',
  more_title: 'વધુ વિકલ્પો', backup: 'બધા ડેકનો બૅકઅપ',
  restore_q: 'આ બૅકઅપ ફાઇલમાંથી {n} ડેક ઉમેરવા છે?', restored: '{n} ડેક ઉમેરાયા',
  reset_progress: 'પ્રગતિ રીસેટ કરો', confirm_progress: 'આ ડેકનાં બધાં કાર્ડ પાછાં બૉક્સ 1 માં મૂકવાં છે?',
  progress_reset: 'બધાં કાર્ડ પાછાં બૉક્સ 1 માં છે.',
  add_samples: 'નમૂના ડેક ઉમેરો', samples_added: '{n} નમૂના ડેક ઉમેરાયા', samples_present: 'બધા નમૂના ડેક પહેલેથી છે.',
  delete_deck: 'ડેક કાઢી નાખો', confirm_delete: '“{name}” ડેક અને તેનાં બધાં કાર્ડ કાઢી નાખવાં છે?', deck_deleted: 'ડેક કાઢી નાખ્યો',
  import_title: 'ડેક ઇમ્પોર્ટ કરો', import_count: '{n} કાર્ડ', import_dup: 'આ ડેક તમારી પાસે પહેલેથી છે.',
  open_copy: 'મારી નકલ ખોલો', import_save: 'નવા ડેક તરીકે સેવ કરો', import_merge: 'ખુલ્લા ડેકમાં ઉમેરો',
  import_saved: 'ડેક સેવ થયો. અભ્યાસ શરૂ કરો!', import_more: '…અને બીજાં {n}',
  bad_link: 'આ લિંક તૂટેલી કે અધૂરી છે. શિક્ષકને ફરી મોકલવા કહો.',
  bad_file: 'આ ફાઇલમાં કોઈ કાર્ડ ન મળ્યું. બે કૉલમ રાખો: આગળ અને પાછળ.',
  storage_full: 'સેવ ન થયું. આ ડિવાઇસમાં જગ્યા નથી.',
  print_name: 'નામ', print_class: 'ધોરણ', print_date: 'તારીખ',
  print_tip: 'ટપકાંવાળી લીટી પર પાનું વાળો. આગળની બાજુ વાંચો, જવાબ બોલો, પછી ગડી ખોલીને તપાસો.',
  help_title: 'કેવી રીતે વાપરવું · વર્ગ માટે આઇડિયા',
  help_1: 'એક ડેક પસંદ કરો અને “અભ્યાસ શરૂ કરો” દબાવો. જવાબ વિચારો, પછી કાર્ડ ફેરવો.',
  help_2: 'પ્રામાણિક રહો: ખરેખર યાદ હોય ત્યારે જ “મને યાદ હતું” દબાવો. સહેલાં કાર્ડ મોડાં પાછાં આવે, અઘરાં કાર્ડ કાલે જ આવે. રોજ થોડું થોડું વાંચો!',
  help_3: '“કાર્ડ બદલો” માં પોતાનો ડેક બનાવો, અથવા “આસામ - દિસપુર” જેવી યાદી પેસ્ટ કરો. પછી તેને વર્ગને WhatsApp લિંકથી મોકલો.',
  help_4: 'વર્ગ પ્રવૃત્તિ: સ્માર્ટબોર્ડ પર “જોડી મેળવો” ખોલો, 8 જોડી પસંદ કરો અને બે ટીમને વારાફરતી રમવા દો. ઓછા પ્રયાસવાળી ટીમ જીતશે!',
  help_5: 'ગૃહકાર્ય માટે વાળવાની શીટ પ્રિન્ટ કરો: વિદ્યાર્થીઓ પાનું વાળીને જાતે ચકાસશે. પરીક્ષા પહેલાં ઝડપી પુનરાવર્તન માટે ક્વિઝ ચલાવો.',
  help_6: 'કીબોર્ડ: Space થી કાર્ડ ફેરવો, 1 = મને યાદ હતું, 2 = હજી શીખવાનું છે.',
  inside_title: 'અંદર શું થાય છે? (સ્પેસ્ડ રિપિટિશન)',
  inside_text: 'દરેક કાર્ડ 5 માંથી કોઈ એક બૉક્સમાં રહે છે. નવાં અને ભૂલાયેલાં કાર્ડ બૉક્સ 1 માં રહે છે અને રોજ આવે છે. દર વખતે યાદ રહે ત્યારે કાર્ડ એક બૉક્સ ઉપર જાય છે અને વધુ દિવસે પાછું આવે છે: 2 દિવસ, 4 દિવસ, એક અઠવાડિયું, પછી 2 અઠવાડિયાં. એટલે તમારો સમય જે હજી નથી આવડતું તેના પર જાય છે, અને ભૂલી જવાની બરાબર પહેલાં યાદ કરવાથી યાદશક્તિ ખૂબ પાકી થાય છે.'
};

window.APP_STRINGS.pa = {
  app_title: 'ਫ਼ਲੈਸ਼ਕਾਰਡ',
  intro: 'ਆਪਣੇ ਫ਼ਲੈਸ਼ਕਾਰਡ ਬਣਾਓ ਅਤੇ ਸਪੇਸਡ ਰਿਪੀਟੀਸ਼ਨ, ਟਾਈਪਿੰਗ ਕੁਇਜ਼ ਅਤੇ ਜੋੜੀ ਮਿਲਾਓ ਖੇਡ ਨਾਲ ਲੰਮੇ ਸਮੇਂ ਤੱਕ ਯਾਦ ਰੱਖੋ।',
  deck: 'ਡੈੱਕ', new_deck: 'ਨਵਾਂ ਡੈੱਕ', new_deck_name: 'ਮੇਰਾ ਡੈੱਕ {n}', untitled: 'ਬਿਨਾਂ ਨਾਂ ਦਾ ਡੈੱਕ',
  stat_cards: 'ਕਾਰਡ', stat_due: 'ਅੱਜ ਦੁਹਰਾਉਣੇ ਹਨ', stat_streak: 'ਲਗਾਤਾਰ ਦਿਨ',
  boxes_caption: 'ਲਾਈਟਨਰ ਬਕਸੇ: ਜਦੋਂ ਵੀ ਕੋਈ ਕਾਰਡ ਯਾਦ ਰਹਿੰਦਾ ਹੈ, ਉਹ ਇੱਕ ਬਕਸਾ ਉੱਪਰ ਜਾਂਦਾ ਹੈ ਅਤੇ ਦੇਰ ਨਾਲ ਵਾਪਸ ਆਉਂਦਾ ਹੈ।',
  box_n: 'ਬਕਸਾ {n}', every_1: 'ਰੋਜ਼', every_2: 'ਹਰ 2 ਦਿਨ', every_4: 'ਹਰ 4 ਦਿਨ', every_7: 'ਹਰ ਹਫ਼ਤੇ', every_14: 'ਹਰ 2 ਹਫ਼ਤੇ',
  modes: 'ਅਭਿਆਸ ਦੇ ਤਰੀਕੇ', tab_study: 'ਪੜ੍ਹੋ', tab_quiz: 'ਕੁਇਜ਼', tab_match: 'ਜੋੜੀ ਮਿਲਾਓ', tab_edit: 'ਕਾਰਡ ਬਦਲੋ',
  no_cards: 'ਇਸ ਡੈੱਕ ਵਿੱਚ ਅਜੇ ਕੋਈ ਕਾਰਡ ਨਹੀਂ।', go_edit: 'ਕਾਰਡ ਜੋੜੋ',
  due_label: 'ਕਾਰਡ ਅੱਜ ਦੁਹਰਾਉਣੇ ਹਨ', all_done: 'ਅੱਜ ਦਾ ਕੰਮ ਪੂਰਾ! 🎉',
  next_due: 'ਅਗਲੀ ਦੁਹਰਾਈ: {when}।', more_due: 'ਅੱਜ {n} ਹੋਰ ਕਾਰਡ ਦੁਹਰਾਉਣੇ ਬਾਕੀ ਹਨ।',
  when_today: 'ਅੱਜ', when_tomorrow: 'ਕੱਲ੍ਹ', when_days: '{n} ਦਿਨਾਂ ਬਾਅਦ',
  session_size: 'ਇੱਕ ਵਾਰ ਵਿੱਚ ਕਿੰਨੇ ਕਾਰਡ', all: 'ਸਾਰੇ', reverse: 'ਪਹਿਲਾਂ ਪਿਛਲਾ ਪਾਸਾ ਦਿਖਾਓ',
  start_study: 'ਪੜ੍ਹਨਾ ਸ਼ੁਰੂ ਕਰੋ', cram: 'ਸਾਰੇ ਕਾਰਡਾਂ ਦਾ ਅਭਿਆਸ ਕਰੋ', cram_badge: 'ਅਭਿਆਸ ਗੇੜ: ਬਕਸੇ ਨਹੀਂ ਬਦਲਣਗੇ',
  front: 'ਅਗਲਾ ਪਾਸਾ', back: 'ਪਿਛਲਾ ਪਾਸਾ',
  flip_hint: "ਪਹਿਲਾਂ ਜਵਾਬ ਸੋਚੋ, ਫਿਰ ਕਾਰਡ 'ਤੇ ਟੈਪ ਕਰਕੇ ਉਸਨੂੰ ਪਲਟੋ।",
  show_answer: 'ਜਵਾਬ ਦਿਖਾਓ', knew: 'ਮੈਨੂੰ ਯਾਦ ਸੀ', again: 'ਅਜੇ ਸਿੱਖਣਾ ਹੈ', read_aloud: 'ਬੋਲ ਕੇ ਸੁਣਾਓ',
  end_session: 'ਸੈਸ਼ਨ ਖ਼ਤਮ ਕਰੋ', progress_label: 'ਇਸ ਸੈਸ਼ਨ ਵਿੱਚ ਸਿੱਖੇ ਕਾਰਡ',
  sum_title: 'ਸੈਸ਼ਨ ਪੂਰਾ!', sum_knew: 'ਪਹਿਲੀ ਵਾਰ ਵਿੱਚ ਯਾਦ ਸੀ', sum_again: 'ਅਜੇ ਸਿੱਖਣਾ ਹੈ', sum_score: 'ਅੰਕ',
  sum_moved: '{up} ਕਾਰਡ ਇੱਕ ਬਕਸਾ ਉੱਪਰ ਗਏ। {down} ਕਾਰਡ ਵਾਪਸ ਬਕਸਾ 1 ਵਿੱਚ ਗਏ।',
  study_again: 'ਔਖੇ ਕਾਰਡ ਫਿਰ ਦੁਹਰਾਓ',
  need_cards: 'ਪਹਿਲਾਂ “ਕਾਰਡ ਬਦਲੋ” ਵਿੱਚ ਘੱਟੋ-ਘੱਟ {n} ਕਾਰਡ ਜੋੜੋ।',
  quiz_title: 'ਜਵਾਬ ਟਾਈਪ ਕਰੋ ਕੁਇਜ਼', quiz_help: 'ਇਸ਼ਾਰਾ ਪੜ੍ਹੋ ਅਤੇ ਜਵਾਬ ਟਾਈਪ ਕਰੋ। ਛੋਟੀਆਂ ਸ਼ਬਦ-ਜੋੜ ਗ਼ਲਤੀਆਂ ਚੱਲ ਜਾਣਗੀਆਂ।',
  answer_side: 'ਤੁਸੀਂ ਕੀ ਟਾਈਪ ਕਰੋਗੇ?', side_back: 'ਪਿਛਲਾ ਪਾਸਾ', side_front: 'ਅਗਲਾ ਪਾਸਾ',
  questions: 'ਸਵਾਲ', start_quiz: 'ਕੁਇਜ਼ ਸ਼ੁਰੂ ਕਰੋ', q_of: 'ਸਵਾਲ {n} / {total}',
  type_back: 'ਇਸ ਕਾਰਡ ਦਾ ਪਿਛਲਾ ਪਾਸਾ ਟਾਈਪ ਕਰੋ', type_front: 'ਇਸ ਕਾਰਡ ਦਾ ਅਗਲਾ ਪਾਸਾ ਟਾਈਪ ਕਰੋ',
  your_answer: 'ਤੁਹਾਡਾ ਜਵਾਬ', check: 'ਜਾਂਚੋ', dont_know: 'ਮੈਨੂੰ ਨਹੀਂ ਪਤਾ',
  answer_label: 'ਜਵਾਬ:', almost: 'ਸਹੀ! ਸ਼ਬਦ-ਜੋੜ ਦੇਖ ਲਓ:', override: 'ਮੇਰਾ ਜਵਾਬ ਸਹੀ ਸੀ',
  quiz_end: 'ਕੁਇਜ਼ ਖ਼ਤਮ ਕਰੋ', quiz_done: 'ਕੁਇਜ਼ ਪੂਰਾ',
  msg_great: 'ਸ਼ਾਬਾਸ਼! ਤੁਹਾਨੂੰ ਇਹ ਚੰਗੀ ਤਰ੍ਹਾਂ ਯਾਦ ਹਨ। 🌟', msg_good: 'ਵਧੀਆ! ਗ਼ਲਤੀਆਂ ਦਾ ਇੱਕ ਵਾਰ ਹੋਰ ਅਭਿਆਸ ਕਰੋ।',
  msg_try: 'ਹਿੰਮਤ ਰੱਖੋ! ਕਾਰਡ ਪੜ੍ਹੋ ਅਤੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  mistakes: 'ਦੁਬਾਰਾ ਦੇਖਣ ਵਾਲੇ', you_wrote: 'ਤੁਸੀਂ ਲਿਖਿਆ:', skipped: 'ਛੱਡ ਦਿੱਤਾ',
  retry_mistakes: 'ਗ਼ਲਤ ਸਵਾਲ ਦੁਬਾਰਾ ਕਰੋ', new_quiz: 'ਨਵਾਂ ਕੁਇਜ਼',
  pairs: 'ਜੋੜੀਆਂ', new_game: 'ਨਵੀਂ ਖੇਡ',
  match_help: "ਇੱਕ ਕਾਰਡ 'ਤੇ ਟੈਪ ਕਰੋ, ਫਿਰ ਉਸਦੀ ਜੋੜੀ 'ਤੇ। ਸਾਰੀਆਂ ਜੋੜੀਆਂ ਜਿੰਨੀ ਛੇਤੀ ਹੋ ਸਕੇ ਮਿਲਾਓ।",
  time_s: '{n} ਸਕਿੰਟ', tries_n: 'ਕੋਸ਼ਿਸ਼ਾਂ: {n}', best_s: 'ਸਭ ਤੋਂ ਵਧੀਆ: {n} ਸਕਿੰਟ',
  match_done: '{s} ਸਕਿੰਟਾਂ ਵਿੱਚ {n} ਕੋਸ਼ਿਸ਼ਾਂ ਨਾਲ ਸਾਰੀਆਂ ਜੋੜੀਆਂ ਮਿਲ ਗਈਆਂ! 🎉', new_best: 'ਨਵਾਂ ਰਿਕਾਰਡ!',
  deck_name: 'ਡੈੱਕ ਦਾ ਨਾਂ', add_card_title: 'ਕਾਰਡ ਜੋੜੋ', edit_card_title: 'ਕਾਰਡ {n} ਬਦਲੋ',
  front_ph: 'ਜਿਵੇਂ: ਅਸਾਮ', back_ph: 'ਜਿਵੇਂ: ਦਿਸਪੁਰ',
  add_picture: 'ਤਸਵੀਰ ਜੋੜੋ', remove_picture: 'ਤਸਵੀਰ ਹਟਾਓ',
  img_note: "ਤਸਵੀਰਾਂ ਛੋਟੀਆਂ ਕਰਕੇ ਸਿਰਫ਼ ਇਸੇ ਡਿਵਾਈਸ 'ਤੇ ਸੇਵ ਹੁੰਦੀਆਂ ਹਨ।",
  img_bad: 'ਇਹ ਤਸਵੀਰ ਵਰਤੀ ਨਹੀਂ ਜਾ ਸਕੀ। JPG ਜਾਂ PNG ਫ਼ਾਈਲ ਵਰਤ ਕੇ ਦੇਖੋ।',
  img_full: 'ਹੋਰ ਤਸਵੀਰਾਂ ਲਈ ਥਾਂ ਨਹੀਂ। ਪਹਿਲਾਂ ਕੁਝ ਤਸਵੀਰਾਂ ਹਟਾਓ।',
  add_card: 'ਕਾਰਡ ਜੋੜੋ', save_card: 'ਕਾਰਡ ਸੇਵ ਕਰੋ', card_added: 'ਕਾਰਡ ਜੁੜ ਗਿਆ', card_saved: 'ਕਾਰਡ ਸੇਵ ਹੋ ਗਿਆ',
  need_both: 'ਅਗਲਾ ਅਤੇ ਪਿਛਲਾ, ਦੋਵੇਂ ਪਾਸੇ ਭਰੋ।',
  deck_full: 'ਇੱਕ ਡੈੱਕ ਵਿੱਚ ਵੱਧ ਤੋਂ ਵੱਧ {n} ਕਾਰਡ ਹੋ ਸਕਦੇ ਹਨ।', too_many_decks: 'ਤੁਸੀਂ ਵੱਧ ਤੋਂ ਵੱਧ {n} ਡੈੱਕ ਰੱਖ ਸਕਦੇ ਹੋ। ਪਹਿਲਾਂ ਇੱਕ ਮਿਟਾਓ।',
  bulk_title: 'ਇੱਕੋ ਵਾਰ ਕਈ ਕਾਰਡ ਜੋੜੋ',
  bulk_help: 'ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ ਕਾਰਡ, ਜਿਵੇਂ “ਅਗਲਾ - ਪਿਛਲਾ”। Excel ਜਾਂ Google Sheets ਤੋਂ ਦੋ ਕਾਲਮ ਵੀ ਪੇਸਟ ਕਰ ਸਕਦੇ ਹੋ।',
  bulk_ph: 'ਕੇਰਲ - ਤਿਰੂਵਨੰਤਪੁਰਮ\nਕਰਨਾਟਕ - ਬੰਗਲੁਰੂ\nਓਡੀਸ਼ਾ - ਭੁਵਨੇਸ਼ਵਰ',
  bulk_found: '{n} ਕਾਰਡ ਜੋੜਨ ਲਈ ਤਿਆਰ', bulk_skipped: '{n} ਲਾਈਨਾਂ ਛੱਡੀਆਂ (“ - ” ਨਹੀਂ ਮਿਲਿਆ)',
  bulk_add: 'ਸਾਰੇ ਜੋੜੋ', bulk_added: '{n} ਕਾਰਡ ਜੁੜ ਗਏ',
  cards_title: 'ਇਸ ਡੈੱਕ ਦੇ ਕਾਰਡ', search_cards: 'ਕਾਰਡ ਖੋਜੋ',
  list_empty: 'ਅਜੇ ਕੋਈ ਕਾਰਡ ਨਹੀਂ। ਉੱਪਰ ਆਪਣਾ ਪਹਿਲਾ ਕਾਰਡ ਜੋੜੋ।', no_results: 'ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਕੋਈ ਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।',
  card_new: 'ਨਵਾਂ', card_box: 'ਬਕਸਾ {n} · {when}', card_deleted: 'ਕਾਰਡ ਮਿਟਾ ਦਿੱਤਾ।', undo: 'ਵਾਪਸ ਲਿਆਓ',
  share_title: 'ਸਾਂਝਾ, ਇੰਪੋਰਟ ਅਤੇ ਪ੍ਰਿੰਟ', make_link: 'ਸਾਂਝਾ ਕਰਨ ਵਾਲਾ ਲਿੰਕ ਬਣਾਓ',
  link_ready: "ਇਹ ਲਿੰਕ ਆਪਣੇ ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਭੇਜੋ। ਇਹ ਉਨ੍ਹਾਂ ਦੇ ਫ਼ੋਨ 'ਤੇ ਇਹੀ ਡੈੱਕ ਖੋਲ੍ਹੇਗਾ, ਸੇਵ ਕਰਨ ਲਈ ਤਿਆਰ।",
  link_long: 'ਇਹ ਲਿੰਕ ਬਹੁਤ ਲੰਮਾ ਹੈ। ਜੇ ਨਾ ਖੁੱਲ੍ਹੇ ਤਾਂ CSV ਫ਼ਾਈਲ ਸਾਂਝੀ ਕਰੋ।',
  link_file: "ਤੁਸੀਂ ਇਹ ਐਪ ਫ਼ਾਈਲ ਤੋਂ ਖੋਲ੍ਹੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਲਿੰਕ ਸਿਰਫ਼ ਇਸੇ ਕੰਪਿਊਟਰ 'ਤੇ ਚੱਲੇਗਾ। ਔਨਲਾਈਨ ਐਪ ਵਰਤੋ ਜਾਂ CSV ਫ਼ਾਈਲ ਸਾਂਝੀ ਕਰੋ।",
  no_img_note: 'ਲਿੰਕ ਅਤੇ CSV ਫ਼ਾਈਲ ਵਿੱਚ ਤਸਵੀਰਾਂ ਨਹੀਂ ਜਾਂਦੀਆਂ।',
  whatsapp: 'WhatsApp', export_csv: 'CSV ਐਕਸਪੋਰਟ ਕਰੋ', import_file: 'CSV ਇੰਪੋਰਟ ਕਰੋ', print_sheet: 'ਮੋੜਨ ਵਾਲੀ ਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ',
  csv_note: 'CSV ਫ਼ਾਈਲ ਵਿੱਚ ਦੋ ਕਾਲਮ ਹੁੰਦੇ ਹਨ: ਅਗਲਾ ਅਤੇ ਪਿਛਲਾ ਪਾਸਾ। ਇਹ Excel ਅਤੇ Google Sheets ਵਿੱਚ ਖੁੱਲ੍ਹਦੀ ਹੈ।',
  more_title: 'ਹੋਰ ਵਿਕਲਪ', backup: 'ਸਾਰੇ ਡੈੱਕਾਂ ਦਾ ਬੈਕਅੱਪ',
  restore_q: 'ਇਸ ਬੈਕਅੱਪ ਫ਼ਾਈਲ ਤੋਂ {n} ਡੈੱਕ ਜੋੜੀਏ?', restored: '{n} ਡੈੱਕ ਜੁੜ ਗਏ',
  reset_progress: 'ਤਰੱਕੀ ਰੀਸੈੱਟ ਕਰੋ', confirm_progress: 'ਇਸ ਡੈੱਕ ਦੇ ਸਾਰੇ ਕਾਰਡ ਵਾਪਸ ਬਕਸਾ 1 ਵਿੱਚ ਪਾਈਏ?',
  progress_reset: 'ਸਾਰੇ ਕਾਰਡ ਵਾਪਸ ਬਕਸਾ 1 ਵਿੱਚ ਹਨ।',
  add_samples: 'ਨਮੂਨਾ ਡੈੱਕ ਜੋੜੋ', samples_added: '{n} ਨਮੂਨਾ ਡੈੱਕ ਜੁੜ ਗਏ', samples_present: 'ਸਾਰੇ ਨਮੂਨਾ ਡੈੱਕ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹਨ।',
  delete_deck: 'ਡੈੱਕ ਮਿਟਾਓ', confirm_delete: '“{name}” ਡੈੱਕ ਅਤੇ ਇਸਦੇ ਸਾਰੇ ਕਾਰਡ ਮਿਟਾਈਏ?', deck_deleted: 'ਡੈੱਕ ਮਿਟਾ ਦਿੱਤਾ',
  import_title: 'ਡੈੱਕ ਇੰਪੋਰਟ ਕਰੋ', import_count: '{n} ਕਾਰਡ', import_dup: 'ਇਹ ਡੈੱਕ ਤੁਹਾਡੇ ਕੋਲ ਪਹਿਲਾਂ ਹੀ ਹੈ।',
  open_copy: 'ਮੇਰੀ ਕਾਪੀ ਖੋਲ੍ਹੋ', import_save: 'ਨਵੇਂ ਡੈੱਕ ਵਜੋਂ ਸੇਵ ਕਰੋ', import_merge: 'ਖੁੱਲ੍ਹੇ ਡੈੱਕ ਵਿੱਚ ਜੋੜੋ',
  import_saved: 'ਡੈੱਕ ਸੇਵ ਹੋ ਗਿਆ। ਪੜ੍ਹਨਾ ਸ਼ੁਰੂ ਕਰੋ!', import_more: '…ਅਤੇ {n} ਹੋਰ',
  bad_link: 'ਇਹ ਲਿੰਕ ਟੁੱਟਿਆ ਹੋਇਆ ਜਾਂ ਅਧੂਰਾ ਹੈ। ਆਪਣੇ ਅਧਿਆਪਕ ਨੂੰ ਦੁਬਾਰਾ ਭੇਜਣ ਲਈ ਕਹੋ।',
  bad_file: 'ਇਸ ਫ਼ਾਈਲ ਵਿੱਚ ਕੋਈ ਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ। ਦੋ ਕਾਲਮ ਰੱਖੋ: ਅਗਲਾ ਅਤੇ ਪਿਛਲਾ ਪਾਸਾ।',
  storage_full: 'ਸੇਵ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਇਸ ਡਿਵਾਈਸ ਵਿੱਚ ਥਾਂ ਨਹੀਂ ਬਚੀ।',
  print_name: 'ਨਾਂ', print_class: 'ਜਮਾਤ', print_date: 'ਤਾਰੀਖ਼',
  print_tip: "ਬਿੰਦੀਆਂ ਵਾਲੀ ਲਾਈਨ 'ਤੇ ਸਫ਼ਾ ਮੋੜੋ। ਅਗਲਾ ਪਾਸਾ ਪੜ੍ਹੋ, ਜਵਾਬ ਬੋਲੋ, ਫਿਰ ਮੋੜ ਖੋਲ੍ਹ ਕੇ ਜਾਂਚੋ।",
  help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ · ਜਮਾਤ ਲਈ ਵਿਚਾਰ',
  help_1: 'ਇੱਕ ਡੈੱਕ ਚੁਣੋ ਅਤੇ “ਪੜ੍ਹਨਾ ਸ਼ੁਰੂ ਕਰੋ” ਦਬਾਓ। ਜਵਾਬ ਸੋਚੋ, ਫਿਰ ਕਾਰਡ ਪਲਟੋ।',
  help_2: 'ਇਮਾਨਦਾਰ ਰਹੋ: “ਮੈਨੂੰ ਯਾਦ ਸੀ” ਤਾਂ ਹੀ ਦਬਾਓ ਜੇ ਸੱਚਮੁੱਚ ਯਾਦ ਸੀ। ਸੌਖੇ ਕਾਰਡ ਦੇਰ ਨਾਲ ਮੁੜਦੇ ਹਨ, ਔਖੇ ਕਾਰਡ ਕੱਲ੍ਹ ਹੀ ਮੁੜਦੇ ਹਨ। ਰੋਜ਼ ਥੋੜ੍ਹਾ-ਥੋੜ੍ਹਾ ਪੜ੍ਹੋ!',
  help_3: '“ਕਾਰਡ ਬਦਲੋ” ਵਿੱਚ ਆਪਣਾ ਡੈੱਕ ਬਣਾਓ, ਜਾਂ “ਅਸਾਮ - ਦਿਸਪੁਰ” ਵਰਗੀ ਸੂਚੀ ਪੇਸਟ ਕਰੋ। ਫਿਰ ਇਸਨੂੰ ਜਮਾਤ ਨੂੰ WhatsApp ਲਿੰਕ ਰਾਹੀਂ ਭੇਜੋ।',
  help_4: "ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: ਸਮਾਰਟਬੋਰਡ 'ਤੇ “ਜੋੜੀ ਮਿਲਾਓ” ਖੋਲ੍ਹੋ, 8 ਜੋੜੀਆਂ ਚੁਣੋ ਅਤੇ ਦੋ ਟੀਮਾਂ ਨੂੰ ਵਾਰੀ-ਵਾਰੀ ਖੇਡਣ ਦਿਓ। ਘੱਟ ਕੋਸ਼ਿਸ਼ਾਂ ਵਾਲੀ ਟੀਮ ਜਿੱਤੇਗੀ!",
  help_5: 'ਘਰ ਦੇ ਕੰਮ ਲਈ ਮੋੜਨ ਵਾਲੀ ਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ: ਵਿਦਿਆਰਥੀ ਸਫ਼ਾ ਮੋੜ ਕੇ ਆਪਣੇ ਆਪ ਨੂੰ ਜਾਂਚਣਗੇ। ਟੈਸਟ ਤੋਂ ਪਹਿਲਾਂ ਛੇਤੀ ਦੁਹਰਾਈ ਲਈ ਕੁਇਜ਼ ਚਲਾਓ।',
  help_6: 'ਕੀਬੋਰਡ: Space ਨਾਲ ਕਾਰਡ ਪਲਟੋ, 1 = ਮੈਨੂੰ ਯਾਦ ਸੀ, 2 = ਅਜੇ ਸਿੱਖਣਾ ਹੈ।',
  inside_title: 'ਅੰਦਰ ਕੀ ਹੋ ਰਿਹਾ ਹੈ? (ਸਪੇਸਡ ਰਿਪੀਟੀਸ਼ਨ)',
  inside_text: "ਹਰ ਕਾਰਡ 5 ਵਿੱਚੋਂ ਕਿਸੇ ਇੱਕ ਬਕਸੇ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ। ਨਵੇਂ ਅਤੇ ਭੁੱਲੇ ਹੋਏ ਕਾਰਡ ਬਕਸਾ 1 ਵਿੱਚ ਰਹਿੰਦੇ ਹਨ ਅਤੇ ਰੋਜ਼ ਆਉਂਦੇ ਹਨ। ਹਰ ਵਾਰ ਯਾਦ ਰਹਿਣ 'ਤੇ ਕਾਰਡ ਇੱਕ ਬਕਸਾ ਉੱਪਰ ਜਾਂਦਾ ਹੈ ਅਤੇ ਵੱਧ ਦਿਨਾਂ ਬਾਅਦ ਮੁੜਦਾ ਹੈ: 2 ਦਿਨ, 4 ਦਿਨ, ਇੱਕ ਹਫ਼ਤਾ, ਫਿਰ 2 ਹਫ਼ਤੇ। ਇਸ ਨਾਲ ਤੁਹਾਡਾ ਸਮਾਂ ਉਨ੍ਹਾਂ ਚੀਜ਼ਾਂ 'ਤੇ ਲੱਗਦਾ ਹੈ ਜੋ ਅਜੇ ਯਾਦ ਨਹੀਂ, ਅਤੇ ਭੁੱਲਣ ਤੋਂ ਠੀਕ ਪਹਿਲਾਂ ਯਾਦ ਕਰਨ ਨਾਲ ਯਾਦਦਾਸ਼ਤ ਬਹੁਤ ਪੱਕੀ ਹੁੰਦੀ ਹੈ।"
};

window.APP_STRINGS.or = {
  app_title: 'ଫ୍ଲାସକାର୍ଡ',
  intro: 'ନିଜର ଫ୍ଲାସକାର୍ଡ ତିଆରି କରନ୍ତୁ ଏବଂ ସ୍ପେସଡ୍ ରିପିଟିସନ୍, ଟାଇପିଂ କୁଇଜ୍ ଓ ଯୋଡ଼ି ମିଳାଅ ଖେଳରେ ସେଗୁଡ଼ିକୁ ଅଧିକ ଦିନ ମନେ ରଖନ୍ତୁ।',
  deck: 'ଡେକ୍', new_deck: 'ନୂଆ ଡେକ୍', new_deck_name: 'ମୋ ଡେକ୍ {n}', untitled: 'ନାମହୀନ ଡେକ୍',
  stat_cards: 'କାର୍ଡ', stat_due: 'ଆଜି ଦୋହରାଇବାକୁ', stat_streak: 'ଲଗାତାର ଦିନ',
  boxes_caption: 'ଲାଇଟନର୍ ବାକ୍ସ: କାର୍ଡଟିଏ ମନେ ରହିଲେ ତାହା ଗୋଟିଏ ବାକ୍ସ ଉପରକୁ ଯାଏ ଏବଂ ଡେରିରେ ଫେରେ।',
  box_n: 'ବାକ୍ସ {n}', every_1: 'ପ୍ରତିଦିନ', every_2: 'ପ୍ରତି 2 ଦିନରେ', every_4: 'ପ୍ରତି 4 ଦିନରେ', every_7: 'ପ୍ରତି ସପ୍ତାହରେ', every_14: 'ପ୍ରତି 2 ସପ୍ତାହରେ',
  modes: 'ଅଭ୍ୟାସର ଉପାୟ', tab_study: 'ପଢ଼ନ୍ତୁ', tab_quiz: 'କୁଇଜ୍', tab_match: 'ଯୋଡ଼ି ମିଳାଅ', tab_edit: 'କାର୍ଡ ବଦଳାନ୍ତୁ',
  no_cards: 'ଏହି ଡେକରେ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାର୍ଡ ନାହିଁ।', go_edit: 'କାର୍ଡ ଯୋଡ଼ନ୍ତୁ',
  due_label: 'କାର୍ଡ ଆଜି ଦୋହରାଇବାକୁ ଅଛି', all_done: 'ଆଜିର କାମ ସରିଲା! 🎉',
  next_due: 'ପରବର୍ତ୍ତୀ ଦୋହରା: {when}।', more_due: 'ଆଜି ଆଉ {n}ଟି କାର୍ଡ ଦୋହରାଇବା ବାକି ଅଛି।',
  when_today: 'ଆଜି', when_tomorrow: 'କାଲି', when_days: '{n} ଦିନ ପରେ',
  session_size: 'ଥରକରେ କେତେ କାର୍ଡ', all: 'ସବୁ', reverse: 'ପ୍ରଥମେ ପଛ ପାର୍ଶ୍ୱ ଦେଖାନ୍ତୁ',
  start_study: 'ପଢ଼ିବା ଆରମ୍ଭ କରନ୍ତୁ', cram: 'ସବୁ କାର୍ଡ ଅଭ୍ୟାସ କରନ୍ତୁ', cram_badge: 'ଅଭ୍ୟାସ ରାଉଣ୍ଡ: ବାକ୍ସ ବଦଳିବ ନାହିଁ',
  front: 'ଆଗ ପାର୍ଶ୍ୱ', back: 'ପଛ ପାର୍ଶ୍ୱ',
  flip_hint: 'ପ୍ରଥମେ ଉତ୍ତର ଭାବନ୍ତୁ, ତା’ପରେ କାର୍ଡରେ ଟ୍ୟାପ୍ କରି ଓଲଟାନ୍ତୁ।',
  show_answer: 'ଉତ୍ତର ଦେଖାନ୍ତୁ', knew: 'ମୋର ମନେ ଥିଲା', again: 'ଏବେ ବି ଶିଖୁଛି', read_aloud: 'ଜୋରରେ ପଢ଼ି ଶୁଣାନ୍ତୁ',
  end_session: 'ସେସନ୍ ଶେଷ କରନ୍ତୁ', progress_label: 'ଏହି ସେସନରେ ଶିଖିଥିବା କାର୍ଡ',
  sum_title: 'ସେସନ୍ ସରିଲା!', sum_knew: 'ପ୍ରଥମ ଥରରେ ମନେ ଥିଲା', sum_again: 'ଏବେ ବି ଶିଖୁଛି', sum_score: 'ସ୍କୋର୍',
  sum_moved: '{up}ଟି କାର୍ଡ ଗୋଟିଏ ବାକ୍ସ ଉପରକୁ ଗଲା। {down}ଟି କାର୍ଡ ପୁଣି ବାକ୍ସ 1କୁ ଫେରିଲା।',
  study_again: 'କଠିନ କାର୍ଡ ପୁଣି ଅଭ୍ୟାସ କରନ୍ତୁ',
  need_cards: 'ପ୍ରଥମେ “କାର୍ଡ ବଦଳାନ୍ତୁ”ରେ ଅତି କମରେ {n}ଟି କାର୍ଡ ଯୋଡ଼ନ୍ତୁ।',
  quiz_title: 'ଉତ୍ତର ଟାଇପ୍ କରିବା କୁଇଜ୍', quiz_help: 'ସୂଚନା ପଢ଼ି ଉତ୍ତର ଟାଇପ୍ କରନ୍ତୁ। ଛୋଟ ବନାନ ଭୁଲ୍ ଚଳିବ।',
  answer_side: 'ଆପଣ କ’ଣ ଟାଇପ୍ କରିବେ?', side_back: 'ପଛ ପାର୍ଶ୍ୱ', side_front: 'ଆଗ ପାର୍ଶ୍ୱ',
  questions: 'ପ୍ରଶ୍ନ', start_quiz: 'କୁଇଜ୍ ଆରମ୍ଭ କରନ୍ତୁ', q_of: 'ପ୍ରଶ୍ନ {n} / {total}',
  type_back: 'ଏହି କାର୍ଡର ପଛ ପାର୍ଶ୍ୱ ଟାଇପ୍ କରନ୍ତୁ', type_front: 'ଏହି କାର୍ଡର ଆଗ ପାର୍ଶ୍ୱ ଟାଇପ୍ କରନ୍ତୁ',
  your_answer: 'ଆପଣଙ୍କ ଉତ୍ତର', check: 'ଯାଞ୍ଚ କରନ୍ତୁ', dont_know: 'ମୁଁ ଜାଣିନି',
  answer_label: 'ଉତ୍ତର:', almost: 'ଠିକ୍! ବନାନଟି ଦେଖିନିଅନ୍ତୁ:', override: 'ମୋ ଉତ୍ତର ଠିକ୍ ଥିଲା',
  quiz_end: 'କୁଇଜ୍ ଶେଷ କରନ୍ତୁ', quiz_done: 'କୁଇଜ୍ ସରିଲା',
  msg_great: 'ବହୁତ ସୁନ୍ଦର! ଆପଣଙ୍କୁ ଏସବୁ ଭଲ ଭାବେ ମନେ ଅଛି। 🌟', msg_good: 'ଭଲ କାମ! ଭୁଲଗୁଡ଼ିକ ଆଉ ଥରେ ଅଭ୍ୟାସ କରନ୍ତୁ।',
  msg_try: 'ଚାଲୁ ରଖନ୍ତୁ! କାର୍ଡ ପଢ଼ି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
  mistakes: 'ପୁଣି ଦେଖିବାକୁ ଥିବା ପ୍ରଶ୍ନ', you_wrote: 'ଆପଣ ଲେଖିଲେ:', skipped: 'ଛାଡ଼ି ଦିଆଗଲା',
  retry_mistakes: 'ଭୁଲ ପ୍ରଶ୍ନଗୁଡ଼ିକ ପୁଣି କରନ୍ତୁ', new_quiz: 'ନୂଆ କୁଇଜ୍',
  pairs: 'ଯୋଡ଼ି', new_game: 'ନୂଆ ଖେଳ',
  match_help: 'ଗୋଟିଏ କାର୍ଡରେ ଟ୍ୟାପ୍ କରନ୍ତୁ, ତା’ପରେ ତାର ଯୋଡ଼ିରେ। ଯେତେ ଶୀଘ୍ର ପାରିବେ ସବୁ ଯୋଡ଼ି ମିଳାନ୍ତୁ।',
  time_s: '{n} ସେକେଣ୍ଡ', tries_n: 'ଚେଷ୍ଟା: {n}', best_s: 'ସର୍ବୋତ୍ତମ: {n} ସେକେଣ୍ଡ',
  match_done: '{s} ସେକେଣ୍ଡରେ {n}ଟି ଚେଷ୍ଟାରେ ସବୁ ଯୋଡ଼ି ମିଳିଗଲା! 🎉', new_best: 'ନୂଆ ରେକର୍ଡ!',
  deck_name: 'ଡେକର ନାମ', add_card_title: 'କାର୍ଡ ଯୋଡ଼ନ୍ତୁ', edit_card_title: 'କାର୍ଡ {n} ବଦଳାନ୍ତୁ',
  front_ph: 'ଯେପରି: ଆସାମ', back_ph: 'ଯେପରି: ଦିସପୁର',
  add_picture: 'ଛବି ଯୋଡ଼ନ୍ତୁ', remove_picture: 'ଛବି ହଟାନ୍ତୁ',
  img_note: 'ଛବିଗୁଡ଼ିକ ଛୋଟ କରି କେବଳ ଏହି ଡିଭାଇସରେ ସେଭ୍ ହୁଏ।',
  img_bad: 'ଏହି ଛବି ବ୍ୟବହାର କରିହେଲା ନାହିଁ। JPG ବା PNG ଫାଇଲ୍ ଚେଷ୍ଟା କରନ୍ତୁ।',
  img_full: 'ଆଉ ଛବି ପାଇଁ ଜାଗା ନାହିଁ। ପ୍ରଥମେ କିଛି ଛବି ହଟାନ୍ତୁ।',
  add_card: 'କାର୍ଡ ଯୋଡ଼ନ୍ତୁ', save_card: 'କାର୍ଡ ସେଭ୍ କରନ୍ତୁ', card_added: 'କାର୍ଡ ଯୋଡ଼ାଗଲା', card_saved: 'କାର୍ଡ ସେଭ୍ ହେଲା',
  need_both: 'ଆଗ ଓ ପଛ, ଦୁଇଟି ଯାକ ଭରନ୍ତୁ।',
  deck_full: 'ଗୋଟିଏ ଡେକରେ ସର୍ବାଧିକ {n}ଟି କାର୍ଡ ରହିପାରିବ।', too_many_decks: 'ସର୍ବାଧିକ {n}ଟି ଡେକ୍ ରଖିହେବ। ପ୍ରଥମେ ଗୋଟିଏ ବିଲୋପ କରନ୍ତୁ।',
  bulk_title: 'ଥରକେ ଅନେକ କାର୍ଡ ଯୋଡ଼ନ୍ତୁ',
  bulk_help: 'ପ୍ରତି ଧାଡ଼ିରେ ଗୋଟିଏ କାର୍ଡ, ଯେପରି “ଆଗ - ପଛ”। Excel ବା Google Sheetsରୁ ଦୁଇଟି ସ୍ତମ୍ଭ ମଧ୍ୟ ପେଷ୍ଟ କରିପାରିବେ।',
  bulk_ph: 'କେରଳ - ତିରୁବନନ୍ତପୁରମ୍\nକର୍ଣ୍ଣାଟକ - ବେଙ୍ଗାଲୁରୁ\nଓଡ଼ିଶା - ଭୁବନେଶ୍ୱର',
  bulk_found: '{n}ଟି କାର୍ଡ ଯୋଡ଼ିବାକୁ ପ୍ରସ୍ତୁତ', bulk_skipped: '{n}ଟି ଧାଡ଼ି ଛାଡ଼ିଦିଆଗଲା (“ - ” ମିଳିଲା ନାହିଁ)',
  bulk_add: 'ସବୁ ଯୋଡ଼ନ୍ତୁ', bulk_added: '{n}ଟି କାର୍ଡ ଯୋଡ଼ାଗଲା',
  cards_title: 'ଏହି ଡେକର କାର୍ଡ', search_cards: 'କାର୍ଡ ଖୋଜନ୍ତୁ',
  list_empty: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାର୍ଡ ନାହିଁ। ଉପରେ ଆପଣଙ୍କ ପ୍ରଥମ କାର୍ଡ ଯୋଡ଼ନ୍ତୁ।', no_results: 'ଆପଣଙ୍କ ଖୋଜା ସହ କୌଣସି କାର୍ଡ ମେଳ ଖାଉନାହିଁ।',
  card_new: 'ନୂଆ', card_box: 'ବାକ୍ସ {n} · {when}', card_deleted: 'କାର୍ଡ ବିଲୋପ ହେଲା।', undo: 'ଫେରାଇ ଆଣନ୍ତୁ',
  share_title: 'ସେୟାର୍, ଇମ୍ପୋର୍ଟ ଓ ପ୍ରିଣ୍ଟ', make_link: 'ସେୟାର୍ ଲିଙ୍କ୍ ତିଆରି କରନ୍ତୁ',
  link_ready: 'ଏହି ଲିଙ୍କ୍ ଆପଣଙ୍କ ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ପଠାନ୍ତୁ। ଏହା ସେମାନଙ୍କ ଫୋନରେ ଏହି ଡେକ୍ ଖୋଲିବ, ସେଭ୍ କରିବାକୁ ପ୍ରସ୍ତୁତ।',
  link_long: 'ଏହି ଲିଙ୍କ୍ ବହୁତ ଲମ୍ବା। ନ ଖୋଲିଲେ CSV ଫାଇଲ୍ ସେୟାର୍ କରନ୍ତୁ।',
  link_file: 'ଆପଣ ଏହି ଆପ୍ ଫାଇଲରୁ ଖୋଲିଛନ୍ତି, ତେଣୁ ଏହି ଲିଙ୍କ୍ କେବଳ ଏହି କମ୍ପ୍ୟୁଟରରେ ଚାଲିବ। ଅନଲାଇନ୍ ଆପ୍ ବ୍ୟବହାର କରନ୍ତୁ ବା CSV ଫାଇଲ୍ ସେୟାର୍ କରନ୍ତୁ।',
  no_img_note: 'ଲିଙ୍କ୍ ଓ CSV ଫାଇଲରେ ଛବି ଯାଏ ନାହିଁ।',
  whatsapp: 'WhatsApp', export_csv: 'CSV ଏକ୍ସପୋର୍ଟ', import_file: 'CSV ଇମ୍ପୋର୍ଟ', print_sheet: 'ଭାଙ୍ଗିବା ସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
  csv_note: 'CSV ଫାଇଲରେ ଦୁଇଟି ସ୍ତମ୍ଭ ଥାଏ: ଆଗ ଓ ପଛ। ଏହା Excel ଓ Google Sheetsରେ ଖୋଲେ।',
  more_title: 'ଅଧିକ ବିକଳ୍ପ', backup: 'ସବୁ ଡେକର ବ୍ୟାକଅପ୍',
  restore_q: 'ଏହି ବ୍ୟାକଅପ୍ ଫାଇଲରୁ {n}ଟି ଡେକ୍ ଯୋଡ଼ିବେ?', restored: '{n}ଟି ଡେକ୍ ଯୋଡ଼ାଗଲା',
  reset_progress: 'ପ୍ରଗତି ରିସେଟ୍ କରନ୍ତୁ', confirm_progress: 'ଏହି ଡେକର ସବୁ କାର୍ଡ ପୁଣି ବାକ୍ସ 1ରେ ରଖିବେ?',
  progress_reset: 'ସବୁ କାର୍ଡ ପୁଣି ବାକ୍ସ 1ରେ ଅଛି।',
  add_samples: 'ନମୁନା ଡେକ୍ ଯୋଡ଼ନ୍ତୁ', samples_added: '{n}ଟି ନମୁନା ଡେକ୍ ଯୋଡ଼ାଗଲା', samples_present: 'ସବୁ ନମୁନା ଡେକ୍ ଆଗରୁ ଅଛି।',
  delete_deck: 'ଡେକ୍ ବିଲୋପ କରନ୍ତୁ', confirm_delete: '“{name}” ଡେକ୍ ଓ ଏହାର ସବୁ କାର୍ଡ ବିଲୋପ କରିବେ?', deck_deleted: 'ଡେକ୍ ବିଲୋପ ହେଲା',
  import_title: 'ଡେକ୍ ଇମ୍ପୋର୍ଟ କରନ୍ତୁ', import_count: '{n}ଟି କାର୍ଡ', import_dup: 'ଏହି ଡେକ୍ ଆପଣଙ୍କ ପାଖରେ ଆଗରୁ ଅଛି।',
  open_copy: 'ମୋ କପି ଖୋଲନ୍ତୁ', import_save: 'ନୂଆ ଡେକ୍ ଭାବେ ସେଭ୍ କରନ୍ତୁ', import_merge: 'ଖୋଲା ଡେକରେ ଯୋଡ଼ନ୍ତୁ',
  import_saved: 'ଡେକ୍ ସେଭ୍ ହେଲା। ପଢ଼ିବା ଆରମ୍ଭ କରନ୍ତୁ!', import_more: '…ଆଉ {n}ଟି',
  bad_link: 'ଏହି ଲିଙ୍କ୍ ଭଙ୍ଗା ବା ଅସମ୍ପୂର୍ଣ୍ଣ। ଆପଣଙ୍କ ଶିକ୍ଷକଙ୍କୁ ପୁଣି ପଠାଇବାକୁ କୁହନ୍ତୁ।',
  bad_file: 'ଏହି ଫାଇଲରେ କୌଣସି କାର୍ଡ ମିଳିଲା ନାହିଁ। ଦୁଇଟି ସ୍ତମ୍ଭ ରଖନ୍ତୁ: ଆଗ ଓ ପଛ।',
  storage_full: 'ସେଭ୍ ହେଲା ନାହିଁ। ଏହି ଡିଭାଇସରେ ଜାଗା ନାହିଁ।',
  print_name: 'ନାମ', print_class: 'ଶ୍ରେଣୀ', print_date: 'ତାରିଖ',
  print_tip: 'ବିନ୍ଦୁ ଥିବା ଧାଡ଼ି ଉପରେ ପୃଷ୍ଠାଟି ଭାଙ୍ଗନ୍ତୁ। ଆଗ ପାର୍ଶ୍ୱ ପଢ଼ନ୍ତୁ, ଉତ୍ତର କୁହନ୍ତୁ, ତା’ପରେ ଭାଙ୍ଗ ଖୋଲି ଯାଞ୍ଚ କରନ୍ତୁ।',
  help_title: 'କିପରି ବ୍ୟବହାର କରିବେ · ଶ୍ରେଣୀ ପାଇଁ ଧାରଣା',
  help_1: 'ଗୋଟିଏ ଡେକ୍ ବାଛି “ପଢ଼ିବା ଆରମ୍ଭ କରନ୍ତୁ” ଦବାନ୍ତୁ। ଉତ୍ତର ଭାବନ୍ତୁ, ତା’ପରେ କାର୍ଡ ଓଲଟାନ୍ତୁ।',
  help_2: 'ସଚ୍ଚୋଟ ରୁହନ୍ତୁ: ସତରେ ମନେ ଥିଲେ ହିଁ “ମୋର ମନେ ଥିଲା” ଦବାନ୍ତୁ। ସହଜ କାର୍ଡ ଡେରିରେ ଫେରେ, କଠିନ କାର୍ଡ କାଲି ହିଁ ଫେରେ। ପ୍ରତିଦିନ ଟିକିଏ ଟିକିଏ ପଢ଼ନ୍ତୁ!',
  help_3: '“କାର୍ଡ ବଦଳାନ୍ତୁ”ରେ ନିଜ ଡେକ୍ ତିଆରି କରନ୍ତୁ, ବା “ଆସାମ - ଦିସପୁର” ପରି ତାଲିକା ପେଷ୍ଟ କରନ୍ତୁ। ତା’ପରେ ଶ୍ରେଣୀକୁ WhatsApp ଲିଙ୍କରେ ପଠାନ୍ତୁ।',
  help_4: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ: ସ୍ମାର୍ଟବୋର୍ଡରେ “ଯୋଡ଼ି ମିଳାଅ” ଖୋଲନ୍ତୁ, 8 ଯୋଡ଼ି ବାଛନ୍ତୁ ଓ ଦୁଇ ଦଳକୁ ପାଳି କରି ଖେଳିବାକୁ ଦିଅନ୍ତୁ। କମ୍ ଚେଷ୍ଟାରେ ମିଳାଉଥିବା ଦଳ ଜିତିବ!',
  help_5: 'ଗୃହକାର୍ଯ୍ୟ ପାଇଁ ଭାଙ୍ଗିବା ସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ: ଛାତ୍ରଛାତ୍ରୀ ପୃଷ୍ଠା ଭାଙ୍ଗି ନିଜକୁ ଯାଞ୍ଚ କରିବେ। ପରୀକ୍ଷା ଆଗରୁ ଶୀଘ୍ର ଦୋହରାଇବା ପାଇଁ କୁଇଜ୍ ଚଲାନ୍ତୁ।',
  help_6: 'କିବୋର୍ଡ: Spaceରେ କାର୍ଡ ଓଲଟାନ୍ତୁ, 1 = ମୋର ମନେ ଥିଲା, 2 = ଏବେ ବି ଶିଖୁଛି।',
  inside_title: 'ଭିତରେ କ’ଣ ହେଉଛି? (ସ୍ପେସଡ୍ ରିପିଟିସନ୍)',
  inside_text: 'ପ୍ରତ୍ୟେକ କାର୍ଡ 5ଟି ବାକ୍ସ ମଧ୍ୟରୁ କୌଣସି ଗୋଟିଏରେ ରହେ। ନୂଆ ଓ ଭୁଲିଯାଇଥିବା କାର୍ଡ ବାକ୍ସ 1ରେ ରହେ ଏବଂ ପ୍ରତିଦିନ ଆସେ। ପ୍ରତିଥର ମନେ ରହିଲେ କାର୍ଡ ଗୋଟିଏ ବାକ୍ସ ଉପରକୁ ଯାଏ ଏବଂ ଅଧିକ ଦିନ ପରେ ଫେରେ: 2 ଦିନ, 4 ଦିନ, ଏକ ସପ୍ତାହ, ତା’ପରେ 2 ସପ୍ତାହ। ଫଳରେ ଆପଣଙ୍କ ସମୟ ଯାହା ଏବେ ବି ଜଣା ନାହିଁ ତା ଉପରେ ଲାଗେ, ଏବଂ ଭୁଲିବାର ଠିକ୍ ଆଗରୁ ମନେ ପକାଇଲେ ସ୍ମୃତି ବହୁତ ଦୃଢ଼ ହୁଏ।'
};

window.APP_STRINGS.ta = {
  app_title: 'ஃபிளாஷ் கார்டுகள்',
  intro: 'உங்கள் சொந்த ஃபிளாஷ் கார்டுகளை உருவாக்கி, இடைவெளி மீள்பார்வை, தட்டச்சு வினாடி வினா, ஜோடி சேர்க்கும் விளையாட்டு மூலம் நீண்ட நாள் நினைவில் வையுங்கள்.',
  deck: 'தொகுப்பு', new_deck: 'புதிய தொகுப்பு', new_deck_name: 'என் தொகுப்பு {n}', untitled: 'பெயரில்லாத் தொகுப்பு',
  stat_cards: 'கார்டுகள்', stat_due: 'இன்று மீள்பார்வை', stat_streak: 'தொடர் நாட்கள்',
  boxes_caption: 'லைட்னர் பெட்டிகள்: ஒரு கார்டு நினைவில் இருந்தால் அது ஒரு பெட்டி மேலே சென்று தாமதமாகத் திரும்பும்.',
  box_n: 'பெட்டி {n}', every_1: 'தினமும்', every_2: '2 நாளுக்கு ஒருமுறை', every_4: '4 நாளுக்கு ஒருமுறை', every_7: 'வாரம் ஒருமுறை', every_14: '2 வாரத்துக்கு ஒருமுறை',
  modes: 'பயிற்சி முறைகள்', tab_study: 'படி', tab_quiz: 'வினாடி வினா', tab_match: 'ஜோடி சேர்', tab_edit: 'கார்டுகளைத் திருத்து',
  no_cards: 'இந்தத் தொகுப்பில் இன்னும் கார்டுகள் இல்லை.', go_edit: 'கார்டுகளைச் சேர்',
  due_label: 'கார்டுகள் இன்று மீள்பார்வைக்கு', all_done: 'இன்றைய வேலை முடிந்தது! 🎉',
  next_due: 'அடுத்த மீள்பார்வை: {when}.', more_due: 'இன்னும் {n} கார்டுகள் இன்று மீள்பார்வைக்குக் காத்திருக்கின்றன.',
  when_today: 'இன்று', when_tomorrow: 'நாளை', when_days: '{n} நாட்களில்',
  session_size: 'ஒரு அமர்வில் எத்தனை கார்டுகள்', all: 'அனைத்தும்', reverse: 'பின்பக்கத்தை முதலில் காட்டு',
  start_study: 'படிக்கத் தொடங்கு', cram: 'அனைத்து கார்டுகளையும் பயிற்சி செய்', cram_badge: 'பயிற்சிச் சுற்று: பெட்டிகள் மாறாது',
  front: 'முன்பக்கம்', back: 'பின்பக்கம்',
  flip_hint: 'முதலில் விடையை யோசியுங்கள், பிறகு கார்டைத் தட்டித் திருப்புங்கள்.',
  show_answer: 'விடையைக் காட்டு', knew: 'எனக்குத் தெரியும்', again: 'இன்னும் கற்கிறேன்', read_aloud: 'உரக்கப் படி',
  end_session: 'அமர்வை முடி', progress_label: 'இந்த அமர்வில் கற்ற கார்டுகள்',
  sum_title: 'அமர்வு முடிந்தது!', sum_knew: 'முதல் முறையிலேயே தெரிந்தது', sum_again: 'இன்னும் கற்கிறேன்', sum_score: 'மதிப்பெண்',
  sum_moved: '{up} கார்டுகள் ஒரு பெட்டி மேலே சென்றன. {down} கார்டுகள் பெட்டி 1-க்குத் திரும்பின.',
  study_again: 'கடினமானவற்றை மீண்டும் பயிற்சி செய்',
  need_cards: 'முதலில் “கார்டுகளைத் திருத்து” பகுதியில் குறைந்தது {n} கார்டுகளைச் சேருங்கள்.',
  quiz_title: 'விடையைத் தட்டச்சு செய்யும் வினாடி வினா', quiz_help: 'குறிப்பைப் படித்து விடையைத் தட்டச்சு செய்யுங்கள். சிறிய எழுத்துப் பிழைகள் பரவாயில்லை.',
  answer_side: 'நீங்கள் எதைத் தட்டச்சு செய்வீர்கள்?', side_back: 'பின்பக்கம்', side_front: 'முன்பக்கம்',
  questions: 'கேள்விகள்', start_quiz: 'வினாடி வினாவைத் தொடங்கு', q_of: 'கேள்வி {n} / {total}',
  type_back: 'இந்தக் கார்டின் பின்பக்கத்தைத் தட்டச்சு செய்யுங்கள்', type_front: 'இந்தக் கார்டின் முன்பக்கத்தைத் தட்டச்சு செய்யுங்கள்',
  your_answer: 'உங்கள் விடை', check: 'சரிபார்', dont_know: 'எனக்குத் தெரியாது',
  answer_label: 'விடை:', almost: 'சரி! எழுத்துக்கூட்டலைப் பாருங்கள்:', override: 'என் விடை சரிதான்',
  quiz_end: 'வினாடி வினாவை முடி', quiz_done: 'வினாடி வினா முடிந்தது',
  msg_great: 'அருமை! இவை உங்களுக்கு நன்றாகத் தெரியும். 🌟', msg_good: 'நல்ல முயற்சி! தவறுகளை இன்னொரு முறை பயிற்சி செய்யுங்கள்.',
  msg_try: 'தொடருங்கள்! கார்டுகளைப் படித்துவிட்டு மீண்டும் முயலுங்கள்.',
  mistakes: 'மீண்டும் பார்க்க வேண்டியவை', you_wrote: 'நீங்கள் எழுதியது:', skipped: 'தவிர்க்கப்பட்டது',
  retry_mistakes: 'தவறிய கேள்விகளை மீண்டும் செய்', new_quiz: 'புதிய வினாடி வினா',
  pairs: 'ஜோடிகள்', new_game: 'புதிய விளையாட்டு',
  match_help: 'ஒரு கார்டைத் தட்டுங்கள், பிறகு அதன் ஜோடியைத் தட்டுங்கள். எல்லா ஜோடிகளையும் விரைவாகச் சேருங்கள்.',
  time_s: '{n} வி', tries_n: 'முயற்சிகள்: {n}', best_s: 'சிறந்தது: {n} வி',
  match_done: '{s} விநாடிகளில் {n} முயற்சிகளில் எல்லா ஜோடிகளும் சேர்ந்தன! 🎉', new_best: 'புதிய சாதனை!',
  deck_name: 'தொகுப்பின் பெயர்', add_card_title: 'கார்டு சேர்', edit_card_title: 'கார்டு {n} திருத்து',
  front_ph: 'எ.கா. அசாம்', back_ph: 'எ.கா. திஸ்பூர்',
  add_picture: 'படம் சேர்', remove_picture: 'படத்தை நீக்கு',
  img_note: 'படங்கள் சிறிதாக்கப்பட்டு இந்தச் சாதனத்தில் மட்டும் சேமிக்கப்படும்.',
  img_bad: 'இந்தப் படத்தைப் பயன்படுத்த முடியவில்லை. JPG அல்லது PNG கோப்பை முயலுங்கள்.',
  img_full: 'மேலும் படங்களுக்கு இடமில்லை. முதலில் சில படங்களை நீக்குங்கள்.',
  add_card: 'கார்டு சேர்', save_card: 'கார்டைச் சேமி', card_added: 'கார்டு சேர்க்கப்பட்டது', card_saved: 'கார்டு சேமிக்கப்பட்டது',
  need_both: 'முன்பக்கம், பின்பக்கம் இரண்டையும் நிரப்புங்கள்.',
  deck_full: 'ஒரு தொகுப்பில் அதிகபட்சம் {n} கார்டுகள் இருக்கலாம்.', too_many_decks: 'அதிகபட்சம் {n} தொகுப்புகள் வைக்கலாம். முதலில் ஒன்றை நீக்குங்கள்.',
  bulk_title: 'ஒரே நேரத்தில் பல கார்டுகளைச் சேர்',
  bulk_help: 'ஒரு வரிக்கு ஒரு கார்டு, எ.கா. “முன் - பின்”. Excel அல்லது Google Sheets-இலிருந்து இரண்டு நெடுவரிசைகளையும் ஒட்டலாம்.',
  bulk_ph: 'கேரளா - திருவனந்தபுரம்\nகர்நாடகா - பெங்களூரு\nஒடிசா - புவனேஸ்வர்',
  bulk_found: '{n} கார்டுகள் சேர்க்கத் தயார்', bulk_skipped: '{n} வரிகள் தவிர்க்கப்பட்டன (“ - ” இல்லை)',
  bulk_add: 'அனைத்தையும் சேர்', bulk_added: '{n} கார்டுகள் சேர்க்கப்பட்டன',
  cards_title: 'இந்தத் தொகுப்பின் கார்டுகள்', search_cards: 'கார்டுகளைத் தேடு',
  list_empty: 'இன்னும் கார்டுகள் இல்லை. மேலே உங்கள் முதல் கார்டைச் சேருங்கள்.', no_results: 'உங்கள் தேடலுக்குப் பொருந்தும் கார்டு இல்லை.',
  card_new: 'புதியது', card_box: 'பெட்டி {n} · {when}', card_deleted: 'கார்டு நீக்கப்பட்டது.', undo: 'செயல்தவிர்',
  share_title: 'பகிர்வு, இறக்குமதி, அச்சு', make_link: 'பகிர்வு இணைப்பை உருவாக்கு',
  link_ready: 'இந்த இணைப்பை மாணவர்களுக்கு அனுப்புங்கள். இது அவர்களின் ஃபோனில் இந்தத் தொகுப்பைத் திறக்கும், சேமிக்கத் தயாராக.',
  link_long: 'இந்த இணைப்பு மிக நீளமானது. திறக்கவில்லை என்றால் CSV கோப்பைப் பகிருங்கள்.',
  link_file: 'இந்தச் செயலியைக் கோப்பிலிருந்து திறந்துள்ளீர்கள், எனவே இந்த இணைப்பு இந்தக் கணினியில் மட்டுமே வேலை செய்யும். ஆன்லைன் செயலியைப் பயன்படுத்துங்கள் அல்லது CSV கோப்பைப் பகிருங்கள்.',
  no_img_note: 'இணைப்புகளிலும் CSV கோப்புகளிலும் படங்கள் சேராது.',
  whatsapp: 'WhatsApp', export_csv: 'CSV ஏற்றுமதி', import_file: 'CSV இறக்குமதி', print_sheet: 'மடிக்கும் தாளை அச்சிடு',
  csv_note: 'CSV கோப்பில் இரண்டு நெடுவரிசைகள்: முன்பக்கம், பின்பக்கம். இது Excel, Google Sheets-இல் திறக்கும்.',
  more_title: 'மேலும் விருப்பங்கள்', backup: 'அனைத்துத் தொகுப்புகளின் காப்புப்பிரதி',
  restore_q: 'இந்தக் காப்புப்பிரதிக் கோப்பிலிருந்து {n} தொகுப்புகளைச் சேர்க்கவா?', restored: '{n} தொகுப்புகள் சேர்க்கப்பட்டன',
  reset_progress: 'முன்னேற்றத்தை மீட்டமை', confirm_progress: 'இந்தத் தொகுப்பின் எல்லா கார்டுகளையும் பெட்டி 1-க்குத் திருப்பவா?',
  progress_reset: 'எல்லா கார்டுகளும் பெட்டி 1-இல் உள்ளன.',
  add_samples: 'மாதிரித் தொகுப்புகளைச் சேர்', samples_added: '{n} மாதிரித் தொகுப்புகள் சேர்க்கப்பட்டன', samples_present: 'எல்லா மாதிரித் தொகுப்புகளும் ஏற்கெனவே உள்ளன.',
  delete_deck: 'தொகுப்பை நீக்கு', confirm_delete: '“{name}” தொகுப்பையும் அதன் எல்லா கார்டுகளையும் நீக்கவா?', deck_deleted: 'தொகுப்பு நீக்கப்பட்டது',
  import_title: 'தொகுப்பை இறக்குமதி செய்', import_count: '{n} கார்டுகள்', import_dup: 'இந்தத் தொகுப்பு ஏற்கெனவே உங்களிடம் உள்ளது.',
  open_copy: 'என் நகலைத் திற', import_save: 'புதிய தொகுப்பாகச் சேமி', import_merge: 'திறந்துள்ள தொகுப்பில் சேர்',
  import_saved: 'தொகுப்பு சேமிக்கப்பட்டது. படிக்கத் தொடங்குங்கள்!', import_more: '…மேலும் {n}',
  bad_link: 'இந்த இணைப்பு உடைந்துள்ளது அல்லது முழுமையில்லை. ஆசிரியரிடம் மீண்டும் அனுப்பச் சொல்லுங்கள்.',
  bad_file: 'இந்தக் கோப்பில் கார்டுகள் இல்லை. இரண்டு நெடுவரிசைகள் வையுங்கள்: முன்பக்கம், பின்பக்கம்.',
  storage_full: 'சேமிக்க முடியவில்லை. இந்தச் சாதனத்தில் இடமில்லை.',
  print_name: 'பெயர்', print_class: 'வகுப்பு', print_date: 'தேதி',
  print_tip: 'புள்ளிக்கோட்டில் தாளை மடியுங்கள். முன்பக்கத்தைப் படித்து விடையைச் சொல்லுங்கள், பிறகு மடிப்பைத் திறந்து சரிபாருங்கள்.',
  help_title: 'பயன்படுத்துவது எப்படி · வகுப்பறைக்கான யோசனைகள்',
  help_1: 'ஒரு தொகுப்பைத் தேர்ந்தெடுத்து “படிக்கத் தொடங்கு” அழுத்துங்கள். விடையை யோசித்து, பிறகு கார்டைத் திருப்புங்கள்.',
  help_2: 'நேர்மையாக இருங்கள்: உண்மையில் நினைவிருந்தால் மட்டும் “எனக்குத் தெரியும்” அழுத்துங்கள். எளிய கார்டுகள் தாமதமாகவும், கடினமானவை நாளையும் திரும்பும். தினமும் கொஞ்சம் படியுங்கள்!',
  help_3: '“கார்டுகளைத் திருத்து” பகுதியில் உங்கள் தொகுப்பை உருவாக்குங்கள், அல்லது “அசாம் - திஸ்பூர்” போன்ற பட்டியலை ஒட்டுங்கள். பிறகு வகுப்புக்கு WhatsApp இணைப்பாக அனுப்புங்கள்.',
  help_4: 'வகுப்புச் செயல்பாடு: ஸ்மார்ட்போர்டில் “ஜோடி சேர்” திறந்து, 8 ஜோடிகளைத் தேர்ந்து, இரண்டு அணிகளை மாறி மாறி விளையாட விடுங்கள். குறைந்த முயற்சிகளில் முடிக்கும் அணி வெல்லும்!',
  help_5: 'வீட்டுப்பாடத்துக்கு மடிக்கும் தாளை அச்சிடுங்கள்: மாணவர்கள் தாளை மடித்துத் தங்களைத் தாங்களே சோதிக்கலாம். தேர்வுக்கு முன் விரைவு மீள்பார்வைக்கு வினாடி வினா நடத்துங்கள்.',
  help_6: 'விசைப்பலகை: Space கார்டைத் திருப்பும், 1 = எனக்குத் தெரியும், 2 = இன்னும் கற்கிறேன்.',
  inside_title: 'உள்ளே என்ன நடக்கிறது? (இடைவெளி மீள்பார்வை)',
  inside_text: 'ஒவ்வொரு கார்டும் 5 பெட்டிகளில் ஒன்றில் இருக்கும். புதிய மற்றும் மறந்த கார்டுகள் பெட்டி 1-இல் இருந்து தினமும் வரும். ஒவ்வொரு முறை நினைவிருக்கும்போதும் கார்டு ஒரு பெட்டி மேலே சென்று இன்னும் தாமதமாக வரும்: 2 நாள், 4 நாள், ஒரு வாரம், பிறகு 2 வாரம். இதனால் இன்னும் தெரியாதவற்றில் உங்கள் நேரம் செலவாகும்; மறப்பதற்குச் சற்று முன் நினைவுகூர்வது நினைவை மிக வலுவாக்கும்.'
};

window.APP_STRINGS.te = {
  app_title: 'ఫ్లాష్‌కార్డులు',
  intro: 'మీ సొంత ఫ్లాష్‌కార్డులు తయారుచేసుకోండి, స్పేస్డ్ రిపిటిషన్, టైపింగ్ క్విజ్, జతలు కలిపే ఆటతో వాటిని ఎక్కువ కాలం గుర్తుంచుకోండి.',
  deck: 'డెక్', new_deck: 'కొత్త డెక్', new_deck_name: 'నా డెక్ {n}', untitled: 'పేరు లేని డెక్',
  stat_cards: 'కార్డులు', stat_due: 'ఈరోజు పునశ్చరణ', stat_streak: 'వరుస రోజులు',
  boxes_caption: 'లైట్నర్ పెట్టెలు: ఒక కార్డు గుర్తుంటే అది ఒక పెట్టె పైకి వెళ్ళి ఆలస్యంగా తిరిగి వస్తుంది.',
  box_n: 'పెట్టె {n}', every_1: 'రోజూ', every_2: 'ప్రతి 2 రోజులకు', every_4: 'ప్రతి 4 రోజులకు', every_7: 'వారానికోసారి', every_14: 'ప్రతి 2 వారాలకు',
  modes: 'అభ్యాస పద్ధతులు', tab_study: 'చదువు', tab_quiz: 'క్విజ్', tab_match: 'జతలు కలుపు', tab_edit: 'కార్డులు మార్చు',
  no_cards: 'ఈ డెక్‌లో ఇంకా కార్డులు లేవు.', go_edit: 'కార్డులు జోడించండి',
  due_label: 'కార్డులు ఈరోజు పునశ్చరణకు', all_done: 'ఈరోజు పని పూర్తయింది! 🎉',
  next_due: 'తదుపరి పునశ్చరణ: {when}.', more_due: 'ఈరోజు ఇంకా {n} కార్డులు పునశ్చరణకు ఉన్నాయి.',
  when_today: 'ఈరోజు', when_tomorrow: 'రేపు', when_days: '{n} రోజుల్లో',
  session_size: 'ఒక సెషన్‌లో ఎన్ని కార్డులు', all: 'అన్నీ', reverse: 'ముందుగా వెనుక వైపు చూపించు',
  start_study: 'చదవడం ప్రారంభించండి', cram: 'అన్ని కార్డులను అభ్యాసం చేయండి', cram_badge: 'అభ్యాస రౌండ్: పెట్టెలు మారవు',
  front: 'ముందు వైపు', back: 'వెనుక వైపు',
  flip_hint: 'ముందుగా జవాబు ఆలోచించండి, తర్వాత కార్డును తాకి తిప్పండి.',
  show_answer: 'జవాబు చూపించు', knew: 'నాకు గుర్తుంది', again: 'ఇంకా నేర్చుకుంటున్నాను', read_aloud: 'గట్టిగా చదివి వినిపించు',
  end_session: 'సెషన్ ముగించు', progress_label: 'ఈ సెషన్‌లో నేర్చుకున్న కార్డులు',
  sum_title: 'సెషన్ పూర్తయింది!', sum_knew: 'మొదటిసారే గుర్తుంది', sum_again: 'ఇంకా నేర్చుకుంటున్నాను', sum_score: 'స్కోరు',
  sum_moved: '{up} కార్డులు ఒక పెట్టె పైకి వెళ్ళాయి. {down} కార్డులు తిరిగి పెట్టె 1కి వచ్చాయి.',
  study_again: 'కష్టమైనవి మళ్ళీ అభ్యాసం చేయండి',
  need_cards: 'ముందుగా “కార్డులు మార్చు”లో కనీసం {n} కార్డులు జోడించండి.',
  quiz_title: 'జవాబు టైప్ చేసే క్విజ్', quiz_help: 'సూచన చదివి జవాబు టైప్ చేయండి. చిన్న అక్షర దోషాలు పర్వాలేదు.',
  answer_side: 'మీరు ఏది టైప్ చేస్తారు?', side_back: 'వెనుక వైపు', side_front: 'ముందు వైపు',
  questions: 'ప్రశ్నలు', start_quiz: 'క్విజ్ ప్రారంభించండి', q_of: 'ప్రశ్న {n} / {total}',
  type_back: 'ఈ కార్డు వెనుక వైపు టైప్ చేయండి', type_front: 'ఈ కార్డు ముందు వైపు టైప్ చేయండి',
  your_answer: 'మీ జవాబు', check: 'సరిచూడు', dont_know: 'నాకు తెలియదు',
  answer_label: 'జవాబు:', almost: 'సరైనది! అక్షరక్రమం చూసుకోండి:', override: 'నా జవాబు సరైనదే',
  quiz_end: 'క్విజ్ ముగించు', quiz_done: 'క్విజ్ పూర్తయింది',
  msg_great: 'అద్భుతం! ఇవి మీకు బాగా గుర్తున్నాయి. 🌟', msg_good: 'బాగుంది! తప్పులను ఇంకోసారి అభ్యాసం చేయండి.',
  msg_try: 'కొనసాగించండి! కార్డులు చదివి మళ్ళీ ప్రయత్నించండి.',
  mistakes: 'మళ్ళీ చూడాల్సినవి', you_wrote: 'మీరు రాసింది:', skipped: 'వదిలేశారు',
  retry_mistakes: 'తప్పిన ప్రశ్నలు మళ్ళీ చేయండి', new_quiz: 'కొత్త క్విజ్',
  pairs: 'జతలు', new_game: 'కొత్త ఆట',
  match_help: 'ఒక కార్డును తాకండి, తర్వాత దాని జతను తాకండి. అన్ని జతలను వీలైనంత వేగంగా కలపండి.',
  time_s: '{n} సె', tries_n: 'ప్రయత్నాలు: {n}', best_s: 'ఉత్తమం: {n} సె',
  match_done: '{s} సెకన్లలో {n} ప్రయత్నాలతో అన్ని జతలు కలిశాయి! 🎉', new_best: 'కొత్త రికార్డు!',
  deck_name: 'డెక్ పేరు', add_card_title: 'కార్డు జోడించండి', edit_card_title: 'కార్డు {n} మార్చండి',
  front_ph: 'ఉదా. అస్సాం', back_ph: 'ఉదా. దిస్పూర్',
  add_picture: 'చిత్రం జోడించండి', remove_picture: 'చిత్రం తీసివేయండి',
  img_note: 'చిత్రాలను చిన్నవిగా చేసి ఈ పరికరంలో మాత్రమే సేవ్ చేస్తాం.',
  img_bad: 'ఈ చిత్రాన్ని ఉపయోగించలేకపోయాం. JPG లేదా PNG ఫైల్ ప్రయత్నించండి.',
  img_full: 'మరిన్ని చిత్రాలకు చోటు లేదు. ముందుగా కొన్ని చిత్రాలు తీసివేయండి.',
  add_card: 'కార్డు జోడించు', save_card: 'కార్డు సేవ్ చేయి', card_added: 'కార్డు జోడించబడింది', card_saved: 'కార్డు సేవ్ అయింది',
  need_both: 'ముందు వైపు, వెనుక వైపు రెండూ నింపండి.',
  deck_full: 'ఒక డెక్‌లో గరిష్ఠంగా {n} కార్డులు ఉండవచ్చు.', too_many_decks: 'గరిష్ఠంగా {n} డెక్‌లు ఉంచవచ్చు. ముందుగా ఒకటి తొలగించండి.',
  bulk_title: 'ఒకేసారి చాలా కార్డులు జోడించండి',
  bulk_help: 'ప్రతి లైన్‌కు ఒక కార్డు, ఉదా. “ముందు - వెనుక”. Excel లేదా Google Sheets నుంచి రెండు కాలమ్‌లను కూడా పేస్ట్ చేయవచ్చు.',
  bulk_ph: 'కేరళ - తిరువనంతపురం\nకర్ణాటక - బెంగళూరు\nఒడిశా - భువనేశ్వర్',
  bulk_found: '{n} కార్డులు జోడించడానికి సిద్ధం', bulk_skipped: '{n} లైన్లు వదిలేశాం (“ - ” దొరకలేదు)',
  bulk_add: 'అన్నీ జోడించు', bulk_added: '{n} కార్డులు జోడించబడ్డాయి',
  cards_title: 'ఈ డెక్‌లోని కార్డులు', search_cards: 'కార్డులు వెతకండి',
  list_empty: 'ఇంకా కార్డులు లేవు. పైన మీ మొదటి కార్డు జోడించండి.', no_results: 'మీ వెతుకులాటకు సరిపోయే కార్డు లేదు.',
  card_new: 'కొత్తది', card_box: 'పెట్టె {n} · {when}', card_deleted: 'కార్డు తొలగించబడింది.', undo: 'రద్దు చేయి',
  share_title: 'షేర్, ఇంపోర్ట్, ప్రింట్', make_link: 'షేర్ లింక్ తయారుచేయి',
  link_ready: 'ఈ లింక్‌ను మీ విద్యార్థులకు పంపండి. ఇది వారి ఫోన్‌లో ఈ డెక్‌ను తెరుస్తుంది, సేవ్ చేయడానికి సిద్ధంగా.',
  link_long: 'ఈ లింక్ చాలా పొడవుగా ఉంది. తెరుచుకోకపోతే CSV ఫైల్ షేర్ చేయండి.',
  link_file: 'మీరు ఈ యాప్‌ను ఫైల్ నుంచి తెరిచారు, కాబట్టి ఈ లింక్ ఈ కంప్యూటర్‌లో మాత్రమే పనిచేస్తుంది. ఆన్‌లైన్ యాప్ వాడండి లేదా CSV ఫైల్ షేర్ చేయండి.',
  no_img_note: 'లింక్‌లలో, CSV ఫైళ్లలో చిత్రాలు ఉండవు.',
  whatsapp: 'WhatsApp', export_csv: 'CSV ఎక్స్‌పోర్ట్', import_file: 'CSV ఇంపోర్ట్', print_sheet: 'మడిచే షీట్ ప్రింట్ చేయి',
  csv_note: 'CSV ఫైల్‌లో రెండు కాలమ్‌లు: ముందు వైపు, వెనుక వైపు. ఇది Excel, Google Sheetsలో తెరుచుకుంటుంది.',
  more_title: 'మరిన్ని ఎంపికలు', backup: 'అన్ని డెక్‌ల బ్యాకప్',
  restore_q: 'ఈ బ్యాకప్ ఫైల్ నుంచి {n} డెక్‌లు జోడించాలా?', restored: '{n} డెక్‌లు జోడించబడ్డాయి',
  reset_progress: 'ప్రగతిని రీసెట్ చేయి', confirm_progress: 'ఈ డెక్‌లోని అన్ని కార్డులను తిరిగి పెట్టె 1లో పెట్టాలా?',
  progress_reset: 'అన్ని కార్డులు తిరిగి పెట్టె 1లో ఉన్నాయి.',
  add_samples: 'నమూనా డెక్‌లు జోడించు', samples_added: '{n} నమూనా డెక్‌లు జోడించబడ్డాయి', samples_present: 'అన్ని నమూనా డెక్‌లు ఇప్పటికే ఉన్నాయి.',
  delete_deck: 'డెక్ తొలగించు', confirm_delete: '“{name}” డెక్‌ను, దానిలోని అన్ని కార్డులను తొలగించాలా?', deck_deleted: 'డెక్ తొలగించబడింది',
  import_title: 'డెక్ ఇంపోర్ట్ చేయండి', import_count: '{n} కార్డులు', import_dup: 'ఈ డెక్ ఇప్పటికే మీ దగ్గర ఉంది.',
  open_copy: 'నా కాపీ తెరువు', import_save: 'కొత్త డెక్‌గా సేవ్ చేయి', import_merge: 'తెరిచి ఉన్న డెక్‌కు జోడించు',
  import_saved: 'డెక్ సేవ్ అయింది. చదవడం ప్రారంభించండి!', import_more: '…ఇంకా {n}',
  bad_link: 'ఈ లింక్ పాడైంది లేదా అసంపూర్ణంగా ఉంది. మీ టీచర్‌ను మళ్ళీ పంపమని అడగండి.',
  bad_file: 'ఈ ఫైల్‌లో కార్డులు దొరకలేదు. రెండు కాలమ్‌లు ఉంచండి: ముందు వైపు, వెనుక వైపు.',
  storage_full: 'సేవ్ చేయలేకపోయాం. ఈ పరికరంలో చోటు లేదు.',
  print_name: 'పేరు', print_class: 'తరగతి', print_date: 'తేదీ',
  print_tip: 'చుక్కల గీత వెంట పేజీని మడవండి. ముందు వైపు చదివి, జవాబు చెప్పి, తర్వాత మడత తెరిచి సరిచూసుకోండి.',
  help_title: 'ఎలా ఉపయోగించాలి · తరగతి కోసం ఆలోచనలు',
  help_1: 'ఒక డెక్ ఎంచుకుని “చదవడం ప్రారంభించండి” నొక్కండి. జవాబు ఆలోచించి, తర్వాత కార్డు తిప్పండి.',
  help_2: 'నిజాయితీగా ఉండండి: నిజంగా గుర్తుంటేనే “నాకు గుర్తుంది” నొక్కండి. సులభమైన కార్డులు ఆలస్యంగా, కష్టమైనవి రేపే మళ్ళీ వస్తాయి. రోజూ కొంచెం చదవండి!',
  help_3: '“కార్డులు మార్చు”లో మీ సొంత డెక్ తయారుచేయండి, లేదా “అస్సాం - దిస్పూర్” వంటి జాబితాను పేస్ట్ చేయండి. తర్వాత దాన్ని తరగతికి WhatsApp లింక్‌గా పంపండి.',
  help_4: 'తరగతి కార్యక్రమం: స్మార్ట్‌బోర్డ్‌పై “జతలు కలుపు” తెరిచి, 8 జతలు ఎంచుకుని, రెండు జట్లను వంతులవారీగా ఆడనివ్వండి. తక్కువ ప్రయత్నాలతో పూర్తిచేసిన జట్టు గెలుస్తుంది!',
  help_5: 'హోంవర్క్ కోసం మడిచే షీట్ ప్రింట్ చేయండి: విద్యార్థులు పేజీ మడిచి తమను తాము పరీక్షించుకుంటారు. పరీక్షకు ముందు త్వరిత పునశ్చరణకు క్విజ్ నడపండి.',
  help_6: 'కీబోర్డ్: Space కార్డును తిప్పుతుంది, 1 = నాకు గుర్తుంది, 2 = ఇంకా నేర్చుకుంటున్నాను.',
  inside_title: 'లోపల ఏం జరుగుతోంది? (స్పేస్డ్ రిపిటిషన్)',
  inside_text: 'ప్రతి కార్డు 5 పెట్టెల్లో ఏదో ఒకదానిలో ఉంటుంది. కొత్తవి, మర్చిపోయిన కార్డులు పెట్టె 1లో ఉండి రోజూ వస్తాయి. ప్రతిసారి గుర్తుంటే కార్డు ఒక పెట్టె పైకి వెళ్ళి ఇంకా ఆలస్యంగా వస్తుంది: 2 రోజులు, 4 రోజులు, ఒక వారం, తర్వాత 2 వారాలు. దీంతో మీ సమయం ఇంకా రాని వాటిపై ఖర్చవుతుంది, మర్చిపోయే ముందే గుర్తుచేసుకుంటే జ్ఞాపకం చాలా బలపడుతుంది.'
};

window.APP_STRINGS.kn = {
  app_title: 'ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್‌ಗಳು',
  intro: 'ನಿಮ್ಮದೇ ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್‌ಗಳನ್ನು ಮಾಡಿ, ಸ್ಪೇಸ್ಡ್ ರಿಪಿಟಿಷನ್, ಟೈಪಿಂಗ್ ಕ್ವಿಜ್ ಮತ್ತು ಜೋಡಿ ಹೊಂದಿಸುವ ಆಟದಿಂದ ಅವುಗಳನ್ನು ಹೆಚ್ಚು ಕಾಲ ನೆನಪಿಡಿ.',
  deck: 'ಡೆಕ್', new_deck: 'ಹೊಸ ಡೆಕ್', new_deck_name: 'ನನ್ನ ಡೆಕ್ {n}', untitled: 'ಹೆಸರಿಲ್ಲದ ಡೆಕ್',
  stat_cards: 'ಕಾರ್ಡ್‌ಗಳು', stat_due: 'ಇಂದು ಪುನರಾವರ್ತನೆ', stat_streak: 'ಸತತ ದಿನಗಳು',
  boxes_caption: 'ಲೈಟ್ನರ್ ಪೆಟ್ಟಿಗೆಗಳು: ಕಾರ್ಡ್ ನೆನಪಿದ್ದಾಗ ಅದು ಒಂದು ಪೆಟ್ಟಿಗೆ ಮೇಲೆ ಹೋಗಿ ತಡವಾಗಿ ಮರಳುತ್ತದೆ.',
  box_n: 'ಪೆಟ್ಟಿಗೆ {n}', every_1: 'ಪ್ರತಿದಿನ', every_2: 'ಪ್ರತಿ 2 ದಿನಕ್ಕೆ', every_4: 'ಪ್ರತಿ 4 ದಿನಕ್ಕೆ', every_7: 'ವಾರಕ್ಕೊಮ್ಮೆ', every_14: 'ಪ್ರತಿ 2 ವಾರಕ್ಕೆ',
  modes: 'ಅಭ್ಯಾಸದ ವಿಧಾನಗಳು', tab_study: 'ಓದಿ', tab_quiz: 'ಕ್ವಿಜ್', tab_match: 'ಜೋಡಿ ಹೊಂದಿಸಿ', tab_edit: 'ಕಾರ್ಡ್ ಬದಲಿಸಿ',
  no_cards: 'ಈ ಡೆಕ್‌ನಲ್ಲಿ ಇನ್ನೂ ಕಾರ್ಡ್‌ಗಳಿಲ್ಲ.', go_edit: 'ಕಾರ್ಡ್ ಸೇರಿಸಿ',
  due_label: 'ಕಾರ್ಡ್‌ಗಳು ಇಂದು ಪುನರಾವರ್ತನೆಗೆ', all_done: 'ಇಂದಿನ ಕೆಲಸ ಮುಗಿಯಿತು! 🎉',
  next_due: 'ಮುಂದಿನ ಪುನರಾವರ್ತನೆ: {when}.', more_due: 'ಇಂದು ಇನ್ನೂ {n} ಕಾರ್ಡ್‌ಗಳ ಪುನರಾವರ್ತನೆ ಬಾಕಿ ಇದೆ.',
  when_today: 'ಇಂದು', when_tomorrow: 'ನಾಳೆ', when_days: '{n} ದಿನಗಳಲ್ಲಿ',
  session_size: 'ಒಂದು ಸೆಷನ್‌ನಲ್ಲಿ ಎಷ್ಟು ಕಾರ್ಡ್', all: 'ಎಲ್ಲಾ', reverse: 'ಮೊದಲು ಹಿಂಭಾಗ ತೋರಿಸಿ',
  start_study: 'ಓದಲು ಪ್ರಾರಂಭಿಸಿ', cram: 'ಎಲ್ಲಾ ಕಾರ್ಡ್ ಅಭ್ಯಾಸ ಮಾಡಿ', cram_badge: 'ಅಭ್ಯಾಸ ಸುತ್ತು: ಪೆಟ್ಟಿಗೆಗಳು ಬದಲಾಗುವುದಿಲ್ಲ',
  front: 'ಮುಂಭಾಗ', back: 'ಹಿಂಭಾಗ',
  flip_hint: 'ಮೊದಲು ಉತ್ತರ ಯೋಚಿಸಿ, ನಂತರ ಕಾರ್ಡ್ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ ತಿರುಗಿಸಿ.',
  show_answer: 'ಉತ್ತರ ತೋರಿಸಿ', knew: 'ನನಗೆ ನೆನಪಿತ್ತು', again: 'ಇನ್ನೂ ಕಲಿಯುತ್ತಿದ್ದೇನೆ', read_aloud: 'ಜೋರಾಗಿ ಓದಿ ಹೇಳಿ',
  end_session: 'ಸೆಷನ್ ಮುಗಿಸಿ', progress_label: 'ಈ ಸೆಷನ್‌ನಲ್ಲಿ ಕಲಿತ ಕಾರ್ಡ್‌ಗಳು',
  sum_title: 'ಸೆಷನ್ ಮುಗಿಯಿತು!', sum_knew: 'ಮೊದಲ ಬಾರಿಯೇ ನೆನಪಿತ್ತು', sum_again: 'ಇನ್ನೂ ಕಲಿಯುತ್ತಿದ್ದೇನೆ', sum_score: 'ಅಂಕ',
  sum_moved: '{up} ಕಾರ್ಡ್‌ಗಳು ಒಂದು ಪೆಟ್ಟಿಗೆ ಮೇಲೆ ಹೋದವು. {down} ಕಾರ್ಡ್‌ಗಳು ಪೆಟ್ಟಿಗೆ 1ಕ್ಕೆ ಮರಳಿದವು.',
  study_again: 'ಕಠಿಣವಾದವನ್ನು ಮತ್ತೆ ಅಭ್ಯಾಸ ಮಾಡಿ',
  need_cards: 'ಮೊದಲು “ಕಾರ್ಡ್ ಬದಲಿಸಿ”ಯಲ್ಲಿ ಕನಿಷ್ಠ {n} ಕಾರ್ಡ್‌ಗಳನ್ನು ಸೇರಿಸಿ.',
  quiz_title: 'ಉತ್ತರ ಟೈಪ್ ಮಾಡುವ ಕ್ವಿಜ್', quiz_help: 'ಸುಳಿವು ಓದಿ ಉತ್ತರ ಟೈಪ್ ಮಾಡಿ. ಸಣ್ಣ ಕಾಗುಣಿತ ತಪ್ಪುಗಳು ಪರವಾಗಿಲ್ಲ.',
  answer_side: 'ನೀವು ಏನು ಟೈಪ್ ಮಾಡುತ್ತೀರಿ?', side_back: 'ಹಿಂಭಾಗ', side_front: 'ಮುಂಭಾಗ',
  questions: 'ಪ್ರಶ್ನೆಗಳು', start_quiz: 'ಕ್ವಿಜ್ ಪ್ರಾರಂಭಿಸಿ', q_of: 'ಪ್ರಶ್ನೆ {n} / {total}',
  type_back: 'ಈ ಕಾರ್ಡ್‌ನ ಹಿಂಭಾಗವನ್ನು ಟೈಪ್ ಮಾಡಿ', type_front: 'ಈ ಕಾರ್ಡ್‌ನ ಮುಂಭಾಗವನ್ನು ಟೈಪ್ ಮಾಡಿ',
  your_answer: 'ನಿಮ್ಮ ಉತ್ತರ', check: 'ಪರಿಶೀಲಿಸಿ', dont_know: 'ನನಗೆ ಗೊತ್ತಿಲ್ಲ',
  answer_label: 'ಉತ್ತರ:', almost: 'ಸರಿ! ಕಾಗುಣಿತ ನೋಡಿಕೊಳ್ಳಿ:', override: 'ನನ್ನ ಉತ್ತರ ಸರಿಯಿತ್ತು',
  quiz_end: 'ಕ್ವಿಜ್ ಮುಗಿಸಿ', quiz_done: 'ಕ್ವಿಜ್ ಮುಗಿಯಿತು',
  msg_great: 'ಅದ್ಭುತ! ಇವು ನಿಮಗೆ ಚೆನ್ನಾಗಿ ನೆನಪಿವೆ. 🌟', msg_good: 'ಒಳ್ಳೆಯ ಕೆಲಸ! ತಪ್ಪುಗಳನ್ನು ಇನ್ನೊಮ್ಮೆ ಅಭ್ಯಾಸ ಮಾಡಿ.',
  msg_try: 'ಮುಂದುವರಿಸಿ! ಕಾರ್ಡ್‌ಗಳನ್ನು ಓದಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  mistakes: 'ಮತ್ತೆ ನೋಡಬೇಕಾದವು', you_wrote: 'ನೀವು ಬರೆದದ್ದು:', skipped: 'ಬಿಡಲಾಗಿದೆ',
  retry_mistakes: 'ತಪ್ಪಾದ ಪ್ರಶ್ನೆಗಳನ್ನು ಮತ್ತೆ ಮಾಡಿ', new_quiz: 'ಹೊಸ ಕ್ವಿಜ್',
  pairs: 'ಜೋಡಿಗಳು', new_game: 'ಹೊಸ ಆಟ',
  match_help: 'ಒಂದು ಕಾರ್ಡ್ ಟ್ಯಾಪ್ ಮಾಡಿ, ನಂತರ ಅದರ ಜೋಡಿಯನ್ನು. ಎಲ್ಲಾ ಜೋಡಿಗಳನ್ನು ಸಾಧ್ಯವಾದಷ್ಟು ಬೇಗ ಹೊಂದಿಸಿ.',
  time_s: '{n} ಸೆ', tries_n: 'ಪ್ರಯತ್ನಗಳು: {n}', best_s: 'ಅತ್ಯುತ್ತಮ: {n} ಸೆ',
  match_done: '{s} ಸೆಕೆಂಡುಗಳಲ್ಲಿ {n} ಪ್ರಯತ್ನಗಳಲ್ಲಿ ಎಲ್ಲಾ ಜೋಡಿಗಳು ಹೊಂದಿದವು! 🎉', new_best: 'ಹೊಸ ದಾಖಲೆ!',
  deck_name: 'ಡೆಕ್ ಹೆಸರು', add_card_title: 'ಕಾರ್ಡ್ ಸೇರಿಸಿ', edit_card_title: 'ಕಾರ್ಡ್ {n} ಬದಲಿಸಿ',
  front_ph: 'ಉದಾ: ಅಸ್ಸಾಂ', back_ph: 'ಉದಾ: ದಿಸ್ಪುರ್',
  add_picture: 'ಚಿತ್ರ ಸೇರಿಸಿ', remove_picture: 'ಚಿತ್ರ ತೆಗೆಯಿರಿ',
  img_note: 'ಚಿತ್ರಗಳನ್ನು ಚಿಕ್ಕದಾಗಿಸಿ ಈ ಸಾಧನದಲ್ಲಿ ಮಾತ್ರ ಉಳಿಸಲಾಗುತ್ತದೆ.',
  img_bad: 'ಈ ಚಿತ್ರವನ್ನು ಬಳಸಲಾಗಲಿಲ್ಲ. JPG ಅಥವಾ PNG ಫೈಲ್ ಪ್ರಯತ್ನಿಸಿ.',
  img_full: 'ಇನ್ನಷ್ಟು ಚಿತ್ರಗಳಿಗೆ ಜಾಗವಿಲ್ಲ. ಮೊದಲು ಕೆಲವು ಚಿತ್ರಗಳನ್ನು ತೆಗೆಯಿರಿ.',
  add_card: 'ಕಾರ್ಡ್ ಸೇರಿಸಿ', save_card: 'ಕಾರ್ಡ್ ಉಳಿಸಿ', card_added: 'ಕಾರ್ಡ್ ಸೇರಿಸಲಾಗಿದೆ', card_saved: 'ಕಾರ್ಡ್ ಉಳಿಸಲಾಗಿದೆ',
  need_both: 'ಮುಂಭಾಗ ಮತ್ತು ಹಿಂಭಾಗ ಎರಡನ್ನೂ ತುಂಬಿ.',
  deck_full: 'ಒಂದು ಡೆಕ್‌ನಲ್ಲಿ ಗರಿಷ್ಠ {n} ಕಾರ್ಡ್‌ಗಳು ಇರಬಹುದು.', too_many_decks: 'ಗರಿಷ್ಠ {n} ಡೆಕ್‌ಗಳನ್ನು ಇಡಬಹುದು. ಮೊದಲು ಒಂದನ್ನು ತೆಗೆದುಹಾಕಿ.',
  bulk_title: 'ಒಮ್ಮೆಗೇ ಹಲವು ಕಾರ್ಡ್ ಸೇರಿಸಿ',
  bulk_help: 'ಪ್ರತಿ ಸಾಲಿಗೆ ಒಂದು ಕಾರ್ಡ್, ಉದಾ: “ಮುಂಭಾಗ - ಹಿಂಭಾಗ”. Excel ಅಥವಾ Google Sheets ನಿಂದ ಎರಡು ಕಾಲಮ್‌ಗಳನ್ನೂ ಅಂಟಿಸಬಹುದು.',
  bulk_ph: 'ಕೇರಳ - ತಿರುವನಂತಪುರ\nಕರ್ನಾಟಕ - ಬೆಂಗಳೂರು\nಒಡಿಶಾ - ಭುವನೇಶ್ವರ',
  bulk_found: '{n} ಕಾರ್ಡ್‌ಗಳು ಸೇರಿಸಲು ಸಿದ್ಧ', bulk_skipped: '{n} ಸಾಲುಗಳನ್ನು ಬಿಡಲಾಗಿದೆ (“ - ” ಸಿಗಲಿಲ್ಲ)',
  bulk_add: 'ಎಲ್ಲಾ ಸೇರಿಸಿ', bulk_added: '{n} ಕಾರ್ಡ್‌ಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ',
  cards_title: 'ಈ ಡೆಕ್‌ನ ಕಾರ್ಡ್‌ಗಳು', search_cards: 'ಕಾರ್ಡ್ ಹುಡುಕಿ',
  list_empty: 'ಇನ್ನೂ ಕಾರ್ಡ್‌ಗಳಿಲ್ಲ. ಮೇಲೆ ನಿಮ್ಮ ಮೊದಲ ಕಾರ್ಡ್ ಸೇರಿಸಿ.', no_results: 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಕಾರ್ಡ್ ಇಲ್ಲ.',
  card_new: 'ಹೊಸದು', card_box: 'ಪೆಟ್ಟಿಗೆ {n} · {when}', card_deleted: 'ಕಾರ್ಡ್ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.', undo: 'ರದ್ದುಮಾಡಿ',
  share_title: 'ಹಂಚಿಕೆ, ಆಮದು ಮತ್ತು ಮುದ್ರಣ', make_link: 'ಹಂಚುವ ಲಿಂಕ್ ಮಾಡಿ',
  link_ready: 'ಈ ಲಿಂಕ್ ಅನ್ನು ನಿಮ್ಮ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಕಳುಹಿಸಿ. ಇದು ಅವರ ಫೋನ್‌ನಲ್ಲಿ ಈ ಡೆಕ್ ತೆರೆಯುತ್ತದೆ, ಉಳಿಸಲು ಸಿದ್ಧವಾಗಿ.',
  link_long: 'ಈ ಲಿಂಕ್ ತುಂಬಾ ಉದ್ದವಾಗಿದೆ. ತೆರೆಯದಿದ್ದರೆ CSV ಫೈಲ್ ಹಂಚಿಕೊಳ್ಳಿ.',
  link_file: 'ನೀವು ಈ ಆ್ಯಪ್ ಅನ್ನು ಫೈಲ್‌ನಿಂದ ತೆರೆದಿದ್ದೀರಿ, ಹಾಗಾಗಿ ಈ ಲಿಂಕ್ ಈ ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ಆನ್‌ಲೈನ್ ಆ್ಯಪ್ ಬಳಸಿ ಅಥವಾ CSV ಫೈಲ್ ಹಂಚಿಕೊಳ್ಳಿ.',
  no_img_note: 'ಲಿಂಕ್ ಮತ್ತು CSV ಫೈಲ್‌ಗಳಲ್ಲಿ ಚಿತ್ರಗಳು ಸೇರುವುದಿಲ್ಲ.',
  whatsapp: 'WhatsApp', export_csv: 'CSV ರಫ್ತು', import_file: 'CSV ಆಮದು', print_sheet: 'ಮಡಚುವ ಹಾಳೆ ಮುದ್ರಿಸಿ',
  csv_note: 'CSV ಫೈಲ್‌ನಲ್ಲಿ ಎರಡು ಕಾಲಮ್‌ಗಳು: ಮುಂಭಾಗ ಮತ್ತು ಹಿಂಭಾಗ. ಇದು Excel ಮತ್ತು Google Sheets ನಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.',
  more_title: 'ಇನ್ನಷ್ಟು ಆಯ್ಕೆಗಳು', backup: 'ಎಲ್ಲಾ ಡೆಕ್‌ಗಳ ಬ್ಯಾಕಪ್',
  restore_q: 'ಈ ಬ್ಯಾಕಪ್ ಫೈಲ್‌ನಿಂದ {n} ಡೆಕ್‌ಗಳನ್ನು ಸೇರಿಸಬೇಕೇ?', restored: '{n} ಡೆಕ್‌ಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ',
  reset_progress: 'ಪ್ರಗತಿ ಮರುಹೊಂದಿಸಿ', confirm_progress: 'ಈ ಡೆಕ್‌ನ ಎಲ್ಲಾ ಕಾರ್ಡ್‌ಗಳನ್ನು ಮತ್ತೆ ಪೆಟ್ಟಿಗೆ 1ಕ್ಕೆ ಹಾಕಬೇಕೇ?',
  progress_reset: 'ಎಲ್ಲಾ ಕಾರ್ಡ್‌ಗಳು ಮತ್ತೆ ಪೆಟ್ಟಿಗೆ 1ರಲ್ಲಿವೆ.',
  add_samples: 'ಮಾದರಿ ಡೆಕ್ ಸೇರಿಸಿ', samples_added: '{n} ಮಾದರಿ ಡೆಕ್‌ಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ', samples_present: 'ಎಲ್ಲಾ ಮಾದರಿ ಡೆಕ್‌ಗಳು ಈಗಾಗಲೇ ಇವೆ.',
  delete_deck: 'ಡೆಕ್ ತೆಗೆದುಹಾಕಿ', confirm_delete: '“{name}” ಡೆಕ್ ಮತ್ತು ಅದರ ಎಲ್ಲಾ ಕಾರ್ಡ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಬೇಕೇ?', deck_deleted: 'ಡೆಕ್ ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
  import_title: 'ಡೆಕ್ ಆಮದು ಮಾಡಿ', import_count: '{n} ಕಾರ್ಡ್‌ಗಳು', import_dup: 'ಈ ಡೆಕ್ ಈಗಾಗಲೇ ನಿಮ್ಮಲ್ಲಿದೆ.',
  open_copy: 'ನನ್ನ ಪ್ರತಿ ತೆರೆಯಿರಿ', import_save: 'ಹೊಸ ಡೆಕ್ ಆಗಿ ಉಳಿಸಿ', import_merge: 'ತೆರೆದಿರುವ ಡೆಕ್‌ಗೆ ಸೇರಿಸಿ',
  import_saved: 'ಡೆಕ್ ಉಳಿಸಲಾಗಿದೆ. ಓದಲು ಪ್ರಾರಂಭಿಸಿ!', import_more: '…ಇನ್ನೂ {n}',
  bad_link: 'ಈ ಲಿಂಕ್ ಮುರಿದಿದೆ ಅಥವಾ ಅಪೂರ್ಣವಾಗಿದೆ. ನಿಮ್ಮ ಶಿಕ್ಷಕರಿಗೆ ಮತ್ತೆ ಕಳುಹಿಸಲು ಹೇಳಿ.',
  bad_file: 'ಈ ಫೈಲ್‌ನಲ್ಲಿ ಕಾರ್ಡ್‌ಗಳು ಸಿಗಲಿಲ್ಲ. ಎರಡು ಕಾಲಮ್ ಇಡಿ: ಮುಂಭಾಗ ಮತ್ತು ಹಿಂಭಾಗ.',
  storage_full: 'ಉಳಿಸಲಾಗಲಿಲ್ಲ. ಈ ಸಾಧನದಲ್ಲಿ ಜಾಗವಿಲ್ಲ.',
  print_name: 'ಹೆಸರು', print_class: 'ತರಗತಿ', print_date: 'ದಿನಾಂಕ',
  print_tip: 'ಚುಕ್ಕೆ ಗೆರೆಯ ಮೇಲೆ ಹಾಳೆಯನ್ನು ಮಡಚಿ. ಮುಂಭಾಗ ಓದಿ, ಉತ್ತರ ಹೇಳಿ, ನಂತರ ಮಡಿಕೆ ತೆರೆದು ಪರಿಶೀಲಿಸಿ.',
  help_title: 'ಬಳಸುವುದು ಹೇಗೆ · ತರಗತಿಗಾಗಿ ಆಲೋಚನೆಗಳು',
  help_1: 'ಒಂದು ಡೆಕ್ ಆಯ್ಕೆ ಮಾಡಿ “ಓದಲು ಪ್ರಾರಂಭಿಸಿ” ಒತ್ತಿ. ಉತ್ತರ ಯೋಚಿಸಿ, ನಂತರ ಕಾರ್ಡ್ ತಿರುಗಿಸಿ.',
  help_2: 'ಪ್ರಾಮಾಣಿಕವಾಗಿರಿ: ನಿಜವಾಗಿ ನೆನಪಿದ್ದರೆ ಮಾತ್ರ “ನನಗೆ ನೆನಪಿತ್ತು” ಒತ್ತಿ. ಸುಲಭ ಕಾರ್ಡ್‌ಗಳು ತಡವಾಗಿ, ಕಠಿಣವಾದವು ನಾಳೆಯೇ ಮರಳುತ್ತವೆ. ಪ್ರತಿದಿನ ಸ್ವಲ್ಪ ಓದಿ!',
  help_3: '“ಕಾರ್ಡ್ ಬದಲಿಸಿ”ಯಲ್ಲಿ ನಿಮ್ಮದೇ ಡೆಕ್ ಮಾಡಿ, ಅಥವಾ “ಅಸ್ಸಾಂ - ದಿಸ್ಪುರ್” ನಂತಹ ಪಟ್ಟಿ ಅಂಟಿಸಿ. ನಂತರ ಅದನ್ನು ತರಗತಿಗೆ WhatsApp ಲಿಂಕ್ ಆಗಿ ಕಳುಹಿಸಿ.',
  help_4: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ “ಜೋಡಿ ಹೊಂದಿಸಿ” ತೆರೆಯಿರಿ, 8 ಜೋಡಿ ಆಯ್ಕೆ ಮಾಡಿ, ಎರಡು ತಂಡಗಳಿಗೆ ಸರದಿಯಂತೆ ಆಡಲು ಬಿಡಿ. ಕಡಿಮೆ ಪ್ರಯತ್ನಗಳಲ್ಲಿ ಮುಗಿಸುವ ತಂಡ ಗೆಲ್ಲುತ್ತದೆ!',
  help_5: 'ಮನೆಗೆಲಸಕ್ಕೆ ಮಡಚುವ ಹಾಳೆ ಮುದ್ರಿಸಿ: ವಿದ್ಯಾರ್ಥಿಗಳು ಹಾಳೆ ಮಡಚಿ ತಮ್ಮನ್ನು ತಾವೇ ಪರೀಕ್ಷಿಸಿಕೊಳ್ಳುತ್ತಾರೆ. ಪರೀಕ್ಷೆಗೂ ಮೊದಲು ತ್ವರಿತ ಪುನರಾವರ್ತನೆಗೆ ಕ್ವಿಜ್ ನಡೆಸಿ.',
  help_6: 'ಕೀಬೋರ್ಡ್: Space ಕಾರ್ಡ್ ತಿರುಗಿಸುತ್ತದೆ, 1 = ನನಗೆ ನೆನಪಿತ್ತು, 2 = ಇನ್ನೂ ಕಲಿಯುತ್ತಿದ್ದೇನೆ.',
  inside_title: 'ಒಳಗೆ ಏನಾಗುತ್ತಿದೆ? (ಸ್ಪೇಸ್ಡ್ ರಿಪಿಟಿಷನ್)',
  inside_text: 'ಪ್ರತಿ ಕಾರ್ಡ್ 5 ಪೆಟ್ಟಿಗೆಗಳಲ್ಲಿ ಒಂದರಲ್ಲಿ ಇರುತ್ತದೆ. ಹೊಸ ಮತ್ತು ಮರೆತ ಕಾರ್ಡ್‌ಗಳು ಪೆಟ್ಟಿಗೆ 1ರಲ್ಲಿದ್ದು ಪ್ರತಿದಿನ ಬರುತ್ತವೆ. ಪ್ರತಿ ಬಾರಿ ನೆನಪಿದ್ದಾಗ ಕಾರ್ಡ್ ಒಂದು ಪೆಟ್ಟಿಗೆ ಮೇಲೆ ಹೋಗಿ ಇನ್ನೂ ತಡವಾಗಿ ಬರುತ್ತದೆ: 2 ದಿನ, 4 ದಿನ, ಒಂದು ವಾರ, ನಂತರ 2 ವಾರ. ಹೀಗಾಗಿ ನಿಮ್ಮ ಸಮಯ ಇನ್ನೂ ಬಾರದವುಗಳ ಮೇಲೆ ಹೋಗುತ್ತದೆ, ಮತ್ತು ಮರೆಯುವ ಸ್ವಲ್ಪ ಮೊದಲು ನೆನಪಿಸಿಕೊಂಡರೆ ನೆನಪು ತುಂಬಾ ಗಟ್ಟಿಯಾಗುತ್ತದೆ.'
};

window.APP_STRINGS.ml = {
  app_title: 'ഫ്ലാഷ്‌കാർഡുകൾ',
  intro: 'സ്വന്തം ഫ്ലാഷ്‌കാർഡുകൾ ഉണ്ടാക്കൂ; സ്പേസ്ഡ് റിപ്പറ്റീഷൻ, ടൈപ്പിംഗ് ക്വിസ്, ജോടി ചേർക്കൽ കളി എന്നിവയിലൂടെ അവ ഏറെക്കാലം ഓർമ്മിക്കൂ.',
  deck: 'ഡെക്ക്', new_deck: 'പുതിയ ഡെക്ക്', new_deck_name: 'എന്റെ ഡെക്ക് {n}', untitled: 'പേരില്ലാത്ത ഡെക്ക്',
  stat_cards: 'കാർഡുകൾ', stat_due: 'ഇന്ന് പഠിക്കാൻ', stat_streak: 'തുടർച്ചയായ ദിവസം',
  boxes_caption: 'ലൈറ്റ്നർ പെട്ടികൾ: ഒരു കാർഡ് ഓർമ്മയുണ്ടെങ്കിൽ അത് ഒരു പെട്ടി മുകളിലേക്ക് പോയി വൈകി തിരിച്ചെത്തും.',
  box_n: 'പെട്ടി {n}', every_1: 'ദിവസവും', every_2: 'ഓരോ 2 ദിവസം', every_4: 'ഓരോ 4 ദിവസം', every_7: 'ആഴ്ചതോറും', every_14: 'ഓരോ 2 ആഴ്ച',
  modes: 'പരിശീലന രീതികൾ', tab_study: 'പഠിക്കുക', tab_quiz: 'ക്വിസ്', tab_match: 'ജോടി ചേർക്കുക', tab_edit: 'കാർഡുകൾ തിരുത്തുക',
  no_cards: 'ഈ ഡെക്കിൽ ഇതുവരെ കാർഡുകളില്ല.', go_edit: 'കാർഡുകൾ ചേർക്കുക',
  due_label: 'കാർഡുകൾ ഇന്ന് ആവർത്തിക്കാനുണ്ട്', all_done: 'ഇന്നത്തെ ജോലി കഴിഞ്ഞു! 🎉',
  next_due: 'അടുത്ത ആവർത്തനം: {when}.', more_due: 'ഇന്ന് ഇനിയും {n} കാർഡുകൾ ആവർത്തിക്കാനുണ്ട്.',
  when_today: 'ഇന്ന്', when_tomorrow: 'നാളെ', when_days: '{n} ദിവസത്തിനു ശേഷം',
  session_size: 'ഒരു സെഷനിൽ എത്ര കാർഡുകൾ', all: 'എല്ലാം', reverse: 'ആദ്യം പിൻവശം കാണിക്കുക',
  start_study: 'പഠനം തുടങ്ങുക', cram: 'എല്ലാ കാർഡുകളും പരിശീലിക്കുക', cram_badge: 'പരിശീലന റൗണ്ട്: പെട്ടികൾ മാറില്ല',
  front: 'മുൻവശം', back: 'പിൻവശം',
  flip_hint: 'ആദ്യം ഉത്തരം ആലോചിക്കുക, പിന്നെ കാർഡിൽ തൊട്ട് മറിക്കുക.',
  show_answer: 'ഉത്തരം കാണിക്കുക', knew: 'എനിക്കറിയാം', again: 'ഇനിയും പഠിക്കണം', read_aloud: 'ഉറക്കെ വായിക്കുക',
  end_session: 'സെഷൻ അവസാനിപ്പിക്കുക', progress_label: 'ഈ സെഷനിൽ പഠിച്ച കാർഡുകൾ',
  sum_title: 'സെഷൻ പൂർത്തിയായി!', sum_knew: 'ആദ്യ ശ്രമത്തിൽ തന്നെ അറിഞ്ഞു', sum_again: 'ഇനിയും പഠിക്കണം', sum_score: 'സ്കോർ',
  sum_moved: '{up} കാർഡുകൾ ഒരു പെട്ടി മുകളിലേക്ക് പോയി. {down} കാർഡുകൾ പെട്ടി 1-ലേക്ക് തിരിച്ചെത്തി.',
  study_again: 'പ്രയാസമുള്ളവ വീണ്ടും പരിശീലിക്കുക',
  need_cards: 'ആദ്യം “കാർഡുകൾ തിരുത്തുക” എന്നതിൽ കുറഞ്ഞത് {n} കാർഡുകൾ ചേർക്കുക.',
  quiz_title: 'ഉത്തരം ടൈപ്പ് ചെയ്യുന്ന ക്വിസ്', quiz_help: 'സൂചന വായിച്ച് ഉത്തരം ടൈപ്പ് ചെയ്യുക. ചെറിയ അക്ഷരത്തെറ്റുകൾ സാരമില്ല.',
  answer_side: 'നിങ്ങൾ എന്ത് ടൈപ്പ് ചെയ്യും?', side_back: 'പിൻവശം', side_front: 'മുൻവശം',
  questions: 'ചോദ്യങ്ങൾ', start_quiz: 'ക്വിസ് തുടങ്ങുക', q_of: 'ചോദ്യം {n} / {total}',
  type_back: 'ഈ കാർഡിന്റെ പിൻവശം ടൈപ്പ് ചെയ്യുക', type_front: 'ഈ കാർഡിന്റെ മുൻവശം ടൈപ്പ് ചെയ്യുക',
  your_answer: 'നിങ്ങളുടെ ഉത്തരം', check: 'പരിശോധിക്കുക', dont_know: 'എനിക്കറിയില്ല',
  answer_label: 'ഉത്തരം:', almost: 'ശരി! അക്ഷരം ഒന്നു നോക്കൂ:', override: 'എന്റെ ഉത്തരം ശരിയായിരുന്നു',
  quiz_end: 'ക്വിസ് അവസാനിപ്പിക്കുക', quiz_done: 'ക്വിസ് കഴിഞ്ഞു',
  msg_great: 'ഗംഭീരം! ഇവ നിങ്ങൾക്ക് നന്നായി ഓർമ്മയുണ്ട്. 🌟', msg_good: 'നന്നായി! തെറ്റുകൾ ഒരിക്കൽ കൂടി പരിശീലിക്കുക.',
  msg_try: 'തുടരൂ! കാർഡുകൾ പഠിച്ച് വീണ്ടും ശ്രമിക്കൂ.',
  mistakes: 'വീണ്ടും നോക്കേണ്ടവ', you_wrote: 'നിങ്ങൾ എഴുതിയത്:', skipped: 'ഒഴിവാക്കി',
  retry_mistakes: 'തെറ്റിയ ചോദ്യങ്ങൾ വീണ്ടും ചെയ്യുക', new_quiz: 'പുതിയ ക്വിസ്',
  pairs: 'ജോടികൾ', new_game: 'പുതിയ കളി',
  match_help: 'ഒരു കാർഡിൽ തൊടുക, പിന്നെ അതിന്റെ ജോടിയിൽ. എല്ലാ ജോടികളും കഴിയുന്നത്ര വേഗം ചേർക്കുക.',
  time_s: '{n} സെ', tries_n: 'ശ്രമങ്ങൾ: {n}', best_s: 'മികച്ചത്: {n} സെ',
  match_done: '{s} സെക്കൻഡിൽ {n} ശ്രമങ്ങളിൽ എല്ലാ ജോടികളും ചേർന്നു! 🎉', new_best: 'പുതിയ റെക്കോർഡ്!',
  deck_name: 'ഡെക്കിന്റെ പേര്', add_card_title: 'കാർഡ് ചേർക്കുക', edit_card_title: 'കാർഡ് {n} തിരുത്തുക',
  front_ph: 'ഉദാ: അസം', back_ph: 'ഉദാ: ദിസ്പൂർ',
  add_picture: 'ചിത്രം ചേർക്കുക', remove_picture: 'ചിത്രം നീക്കുക',
  img_note: 'ചിത്രങ്ങൾ ചെറുതാക്കി ഈ ഉപകരണത്തിൽ മാത്രം സേവ് ചെയ്യുന്നു.',
  img_bad: 'ഈ ചിത്രം ഉപയോഗിക്കാനായില്ല. JPG അല്ലെങ്കിൽ PNG ഫയൽ ശ്രമിക്കുക.',
  img_full: 'കൂടുതൽ ചിത്രങ്ങൾക്ക് സ്ഥലമില്ല. ആദ്യം കുറച്ച് ചിത്രങ്ങൾ നീക്കുക.',
  add_card: 'കാർഡ് ചേർക്കുക', save_card: 'കാർഡ് സേവ് ചെയ്യുക', card_added: 'കാർഡ് ചേർത്തു', card_saved: 'കാർഡ് സേവ് ചെയ്തു',
  need_both: 'മുൻവശവും പിൻവശവും രണ്ടും പൂരിപ്പിക്കുക.',
  deck_full: 'ഒരു ഡെക്കിൽ പരമാവധി {n} കാർഡുകൾ ആകാം.', too_many_decks: 'പരമാവധി {n} ഡെക്കുകൾ സൂക്ഷിക്കാം. ആദ്യം ഒന്ന് ഇല്ലാതാക്കുക.',
  bulk_title: 'ഒരുമിച്ച് ഒട്ടേറെ കാർഡുകൾ ചേർക്കുക',
  bulk_help: 'ഓരോ വരിയിലും ഒരു കാർഡ്, ഉദാ: “മുൻവശം - പിൻവശം”. Excel അല്ലെങ്കിൽ Google Sheets-ൽ നിന്ന് രണ്ട് കോളങ്ങളും ഒട്ടിക്കാം.',
  bulk_ph: 'കേരളം - തിരുവനന്തപുരം\nകർണാടക - ബെംഗളൂരു\nഒഡിഷ - ഭുവനേശ്വർ',
  bulk_found: '{n} കാർഡുകൾ ചേർക്കാൻ തയ്യാർ', bulk_skipped: '{n} വരികൾ ഒഴിവാക്കി (“ - ” കണ്ടില്ല)',
  bulk_add: 'എല്ലാം ചേർക്കുക', bulk_added: '{n} കാർഡുകൾ ചേർത്തു',
  cards_title: 'ഈ ഡെക്കിലെ കാർഡുകൾ', search_cards: 'കാർഡുകൾ തിരയുക',
  list_empty: 'ഇതുവരെ കാർഡുകളില്ല. മുകളിൽ നിങ്ങളുടെ ആദ്യ കാർഡ് ചേർക്കുക.', no_results: 'തിരച്ചിലിനു ചേരുന്ന കാർഡില്ല.',
  card_new: 'പുതിയത്', card_box: 'പെട്ടി {n} · {when}', card_deleted: 'കാർഡ് ഇല്ലാതാക്കി.', undo: 'തിരികെ കൊണ്ടുവരിക',
  share_title: 'പങ്കിടൽ, ഇമ്പോർട്ട്, പ്രിന്റ്', make_link: 'പങ്കിടാനുള്ള ലിങ്ക് ഉണ്ടാക്കുക',
  link_ready: 'ഈ ലിങ്ക് വിദ്യാർത്ഥികൾക്ക് അയയ്ക്കുക. ഇത് അവരുടെ ഫോണിൽ ഈ ഡെക്ക് തുറക്കും, സേവ് ചെയ്യാൻ തയ്യാറായി.',
  link_long: 'ഈ ലിങ്ക് വളരെ നീളമുള്ളതാണ്. തുറന്നില്ലെങ്കിൽ CSV ഫയൽ പങ്കിടുക.',
  link_file: 'നിങ്ങൾ ഈ ആപ്പ് ഫയലിൽ നിന്നാണ് തുറന്നത്, അതിനാൽ ഈ ലിങ്ക് ഈ കമ്പ്യൂട്ടറിൽ മാത്രമേ പ്രവർത്തിക്കൂ. ഓൺലൈൻ ആപ്പ് ഉപയോഗിക്കുക അല്ലെങ്കിൽ CSV ഫയൽ പങ്കിടുക.',
  no_img_note: 'ലിങ്കുകളിലും CSV ഫയലുകളിലും ചിത്രങ്ങൾ ഉൾപ്പെടില്ല.',
  whatsapp: 'WhatsApp', export_csv: 'CSV എക്സ്പോർട്ട്', import_file: 'CSV ഇമ്പോർട്ട്', print_sheet: 'മടക്കാവുന്ന ഷീറ്റ് പ്രിന്റ് ചെയ്യുക',
  csv_note: 'CSV ഫയലിൽ രണ്ട് കോളങ്ങൾ: മുൻവശം, പിൻവശം. ഇത് Excel-ലും Google Sheets-ലും തുറക്കും.',
  more_title: 'കൂടുതൽ ഓപ്ഷനുകൾ', backup: 'എല്ലാ ഡെക്കുകളുടെയും ബാക്കപ്പ്',
  restore_q: 'ഈ ബാക്കപ്പ് ഫയലിൽ നിന്ന് {n} ഡെക്കുകൾ ചേർക്കണോ?', restored: '{n} ഡെക്കുകൾ ചേർത്തു',
  reset_progress: 'പുരോഗതി റീസെറ്റ് ചെയ്യുക', confirm_progress: 'ഈ ഡെക്കിലെ എല്ലാ കാർഡുകളും പെട്ടി 1-ലേക്ക് തിരികെ ഇടണോ?',
  progress_reset: 'എല്ലാ കാർഡുകളും പെട്ടി 1-ൽ തിരിച്ചെത്തി.',
  add_samples: 'മാതൃകാ ഡെക്കുകൾ ചേർക്കുക', samples_added: '{n} മാതൃകാ ഡെക്കുകൾ ചേർത്തു', samples_present: 'എല്ലാ മാതൃകാ ഡെക്കുകളും ഇപ്പോൾത്തന്നെയുണ്ട്.',
  delete_deck: 'ഡെക്ക് ഇല്ലാതാക്കുക', confirm_delete: '“{name}” ഡെക്കും അതിലെ എല്ലാ കാർഡുകളും ഇല്ലാതാക്കണോ?', deck_deleted: 'ഡെക്ക് ഇല്ലാതാക്കി',
  import_title: 'ഡെക്ക് ഇമ്പോർട്ട് ചെയ്യുക', import_count: '{n} കാർഡുകൾ', import_dup: 'ഈ ഡെക്ക് ഇപ്പോൾത്തന്നെ നിങ്ങളുടെ പക്കലുണ്ട്.',
  open_copy: 'എന്റെ പകർപ്പ് തുറക്കുക', import_save: 'പുതിയ ഡെക്കായി സേവ് ചെയ്യുക', import_merge: 'തുറന്നിരിക്കുന്ന ഡെക്കിൽ ചേർക്കുക',
  import_saved: 'ഡെക്ക് സേവ് ചെയ്തു. പഠനം തുടങ്ങൂ!', import_more: '…കൂടാതെ {n} എണ്ണം',
  bad_link: 'ഈ ലിങ്ക് തകരാറിലാണ് അല്ലെങ്കിൽ പൂർണ്ണമല്ല. അധ്യാപകനോട് വീണ്ടും അയയ്ക്കാൻ പറയുക.',
  bad_file: 'ഈ ഫയലിൽ കാർഡുകളൊന്നും കണ്ടില്ല. രണ്ട് കോളങ്ങൾ വയ്ക്കുക: മുൻവശം, പിൻവശം.',
  storage_full: 'സേവ് ചെയ്യാനായില്ല. ഈ ഉപകരണത്തിൽ സ്ഥലമില്ല.',
  print_name: 'പേര്', print_class: 'ക്ലാസ്', print_date: 'തീയതി',
  print_tip: 'കുത്തുവരയിലൂടെ പേജ് മടക്കുക. മുൻവശം വായിച്ച് ഉത്തരം പറയുക, പിന്നെ മടക്ക് തുറന്ന് ഒത്തുനോക്കുക.',
  help_title: 'എങ്ങനെ ഉപയോഗിക്കാം · ക്ലാസ് മുറിക്കുള്ള ആശയങ്ങൾ',
  help_1: 'ഒരു ഡെക്ക് തിരഞ്ഞെടുത്ത് “പഠനം തുടങ്ങുക” അമർത്തുക. ഉത്തരം ആലോചിച്ച്, പിന്നെ കാർഡ് മറിക്കുക.',
  help_2: 'സത്യസന്ധരാകുക: ശരിക്കും ഓർമ്മയുണ്ടെങ്കിൽ മാത്രം “എനിക്കറിയാം” അമർത്തുക. എളുപ്പമുള്ളവ വൈകിയും പ്രയാസമുള്ളവ നാളെയും തിരിച്ചെത്തും. ദിവസവും കുറച്ച് പഠിക്കൂ!',
  help_3: '“കാർഡുകൾ തിരുത്തുക” എന്നതിൽ സ്വന്തം ഡെക്ക് ഉണ്ടാക്കുക, അല്ലെങ്കിൽ “അസം - ദിസ്പൂർ” പോലെയുള്ള പട്ടിക ഒട്ടിക്കുക. പിന്നെ അത് ക്ലാസിന് WhatsApp ലിങ്കായി അയയ്ക്കുക.',
  help_4: 'ക്ലാസ് പ്രവർത്തനം: സ്മാർട്ട്ബോർഡിൽ “ജോടി ചേർക്കുക” തുറന്ന്, 8 ജോടികൾ തിരഞ്ഞെടുത്ത്, രണ്ട് ടീമുകളെ മാറിമാറി കളിക്കാൻ അനുവദിക്കുക. കുറച്ച് ശ്രമങ്ങളിൽ തീർക്കുന്ന ടീം ജയിക്കും!',
  help_5: 'ഹോംവർക്കിന് മടക്കാവുന്ന ഷീറ്റ് പ്രിന്റ് ചെയ്യുക: വിദ്യാർത്ഥികൾ പേജ് മടക്കി സ്വയം പരീക്ഷിക്കും. പരീക്ഷയ്ക്കു മുമ്പ് വേഗത്തിലുള്ള ആവർത്തനത്തിന് ക്വിസ് നടത്തുക.',
  help_6: 'കീബോർഡ്: Space കാർഡ് മറിക്കും, 1 = എനിക്കറിയാം, 2 = ഇനിയും പഠിക്കണം.',
  inside_title: 'ഉള്ളിൽ എന്താണ് നടക്കുന്നത്? (സ്പേസ്ഡ് റിപ്പറ്റീഷൻ)',
  inside_text: 'ഓരോ കാർഡും 5 പെട്ടികളിൽ ഒന്നിലാണ്. പുതിയതും മറന്നതുമായ കാർഡുകൾ പെട്ടി 1-ൽ ഇരുന്ന് ദിവസവും വരും. ഓരോ തവണ ഓർമ്മയുണ്ടാകുമ്പോഴും കാർഡ് ഒരു പെട്ടി മുകളിലേക്ക് പോയി കൂടുതൽ വൈകി വരും: 2 ദിവസം, 4 ദിവസം, ഒരാഴ്ച, പിന്നെ 2 ആഴ്ച. അങ്ങനെ ഇനിയും അറിയാത്തവയ്ക്കായി നിങ്ങളുടെ സമയം ചെലവാകും; മറക്കുന്നതിന് തൊട്ടുമുമ്പ് ഓർത്തെടുക്കുന്നത് ഓർമ്മയെ വളരെ ശക്തമാക്കുന്നു.'
};

window.APP_STRINGS.ur = {
  app_title: 'فلیش کارڈ',
  intro: 'اپنے فلیش کارڈ بنائیں اور اسپیسڈ ریپیٹیشن، ٹائپنگ کوئز اور جوڑی ملاؤ کھیل سے انہیں دیر تک یاد رکھیں۔',
  deck: 'ڈیک', new_deck: 'نیا ڈیک', new_deck_name: 'میرا ڈیک {n}', untitled: 'بے نام ڈیک',
  stat_cards: 'کارڈ', stat_due: 'آج دہرانے ہیں', stat_streak: 'مسلسل دن',
  boxes_caption: 'لائٹنر بکس: جب بھی کوئی کارڈ یاد رہتا ہے، وہ ایک بکس اوپر جاتا ہے اور دیر سے واپس آتا ہے۔',
  box_n: 'بکس {n}', every_1: 'روزانہ', every_2: 'ہر 2 دن', every_4: 'ہر 4 دن', every_7: 'ہر ہفتے', every_14: 'ہر 2 ہفتے',
  modes: 'مشق کے طریقے', tab_study: 'پڑھیں', tab_quiz: 'کوئز', tab_match: 'جوڑی ملاؤ', tab_edit: 'کارڈ بدلیں',
  no_cards: 'اس ڈیک میں ابھی کوئی کارڈ نہیں۔', go_edit: 'کارڈ شامل کریں',
  due_label: 'کارڈ آج دہرانے ہیں', all_done: 'آج کا کام مکمل! 🎉',
  next_due: 'اگلی دہرائی: {when}۔', more_due: 'آج {n} اور کارڈ دہرانے باقی ہیں۔',
  when_today: 'آج', when_tomorrow: 'کل', when_days: '{n} دن بعد',
  session_size: 'ایک بار میں کتنے کارڈ', all: 'سب', reverse: 'پہلے پچھلا رخ دکھائیں',
  start_study: 'پڑھنا شروع کریں', cram: 'سب کارڈوں کی مشق کریں', cram_badge: 'مشق کا راؤنڈ: بکس نہیں بدلیں گے',
  front: 'سامنے کا رخ', back: 'پچھلا رخ',
  flip_hint: 'پہلے جواب سوچیں، پھر کارڈ پر ٹیپ کر کے اسے پلٹیں۔',
  show_answer: 'جواب دکھائیں', knew: 'مجھے یاد تھا', again: 'ابھی سیکھ رہے ہیں', read_aloud: 'بول کر سنائیں',
  end_session: 'سیشن ختم کریں', progress_label: 'اس سیشن میں سیکھے گئے کارڈ',
  sum_title: 'سیشن مکمل!', sum_knew: 'پہلی بار میں یاد تھا', sum_again: 'ابھی سیکھ رہے ہیں', sum_score: 'اسکور',
  sum_moved: '{up} کارڈ ایک بکس اوپر گئے۔ {down} کارڈ واپس بکس 1 میں گئے۔',
  study_again: 'مشکل کارڈوں کی پھر مشق کریں',
  need_cards: 'پہلے “کارڈ بدلیں” میں کم از کم {n} کارڈ شامل کریں۔',
  quiz_title: 'جواب ٹائپ کرو کوئز', quiz_help: 'اشارہ پڑھیں اور جواب ٹائپ کریں۔ چھوٹی موٹی ہجے کی غلطی چل جائے گی۔',
  answer_side: 'آپ کیا ٹائپ کریں گے؟', side_back: 'پچھلا رخ', side_front: 'سامنے کا رخ',
  questions: 'سوال', start_quiz: 'کوئز شروع کریں', q_of: 'سوال {n} / {total}',
  type_back: 'اس کارڈ کا پچھلا رخ ٹائپ کریں', type_front: 'اس کارڈ کا سامنے کا رخ ٹائپ کریں',
  your_answer: 'آپ کا جواب', check: 'جانچیں', dont_know: 'مجھے نہیں معلوم',
  answer_label: 'جواب:', almost: 'درست! ہجے دیکھ لیں:', override: 'میرا جواب درست تھا',
  quiz_end: 'کوئز ختم کریں', quiz_done: 'کوئز مکمل',
  msg_great: 'بہت خوب! آپ کو یہ اچھی طرح یاد ہیں۔ 🌟', msg_good: 'اچھا کام! غلطیوں کی ایک بار اور مشق کریں۔',
  msg_try: 'ہمت رکھیں! کارڈ پڑھیں اور پھر کوشش کریں۔',
  mistakes: 'جنہیں دوبارہ دیکھنا ہے', you_wrote: 'آپ نے لکھا:', skipped: 'چھوڑ دیا',
  retry_mistakes: 'غلط سوال دوبارہ کریں', new_quiz: 'نیا کوئز',
  pairs: 'جوڑیاں', new_game: 'نیا کھیل',
  match_help: 'ایک کارڈ پر ٹیپ کریں، پھر اس کی جوڑی پر۔ ساری جوڑیاں جتنی جلدی ہو سکے ملائیں۔',
  time_s: '{n} سیکنڈ', tries_n: 'کوششیں: {n}', best_s: 'بہترین: {n} سیکنڈ',
  match_done: '{s} سیکنڈ اور {n} کوششوں میں ساری جوڑیاں مل گئیں! 🎉', new_best: 'نیا ریکارڈ!',
  deck_name: 'ڈیک کا نام', add_card_title: 'کارڈ شامل کریں', edit_card_title: 'کارڈ {n} بدلیں',
  front_ph: 'جیسے: آسام', back_ph: 'جیسے: دسپور',
  add_picture: 'تصویر شامل کریں', remove_picture: 'تصویر ہٹائیں',
  img_note: 'تصویریں چھوٹی کر کے صرف اسی آلے پر محفوظ ہوتی ہیں۔',
  img_bad: 'یہ تصویر استعمال نہیں ہو سکی۔ JPG یا PNG فائل آزمائیں۔',
  img_full: 'مزید تصویروں کی جگہ نہیں۔ پہلے کچھ تصویریں ہٹائیں۔',
  add_card: 'کارڈ شامل کریں', save_card: 'کارڈ محفوظ کریں', card_added: 'کارڈ شامل ہو گیا', card_saved: 'کارڈ محفوظ ہو گیا',
  need_both: 'سامنے اور پیچھے، دونوں رخ بھریں۔',
  deck_full: 'ایک ڈیک میں زیادہ سے زیادہ {n} کارڈ ہو سکتے ہیں۔', too_many_decks: 'آپ زیادہ سے زیادہ {n} ڈیک رکھ سکتے ہیں۔ پہلے کوئی ایک حذف کریں۔',
  bulk_title: 'ایک ساتھ کئی کارڈ شامل کریں',
  bulk_help: 'ہر سطر میں ایک کارڈ، جیسے “سامنے - پیچھے”۔ Excel یا Google Sheets سے دو کالم بھی پیسٹ کر سکتے ہیں۔',
  bulk_ph: 'کیرالا - ترواننت پورم\nکرناٹک - بنگلورو\nاوڈیشہ - بھونیشور',
  bulk_found: '{n} کارڈ شامل کرنے کے لیے تیار', bulk_skipped: '{n} سطریں چھوڑ دی گئیں (“ - ” نہیں ملا)',
  bulk_add: 'سب شامل کریں', bulk_added: '{n} کارڈ شامل ہو گئے',
  cards_title: 'اس ڈیک کے کارڈ', search_cards: 'کارڈ تلاش کریں',
  list_empty: 'ابھی کوئی کارڈ نہیں۔ اوپر اپنا پہلا کارڈ شامل کریں۔', no_results: 'آپ کی تلاش سے کوئی کارڈ نہیں ملا۔',
  card_new: 'نیا', card_box: 'بکس {n} · {when}', card_deleted: 'کارڈ حذف ہو گیا۔', undo: 'واپس لائیں',
  share_title: 'شیئر، امپورٹ اور پرنٹ', make_link: 'شیئر لنک بنائیں',
  link_ready: 'یہ لنک اپنے طلبہ کو بھیجیں۔ یہ ان کے فون پر یہی ڈیک کھولے گا، محفوظ کرنے کے لیے تیار۔',
  link_long: 'یہ لنک بہت لمبا ہے۔ اگر نہ کھلے تو CSV فائل شیئر کریں۔',
  link_file: 'آپ نے یہ ایپ فائل سے کھولی ہے، اس لیے یہ لنک صرف اسی کمپیوٹر پر چلے گا۔ آن لائن ایپ استعمال کریں یا CSV فائل شیئر کریں۔',
  no_img_note: 'تصویریں لنک اور CSV فائل میں نہیں جاتیں۔',
  whatsapp: 'WhatsApp', export_csv: 'CSV ایکسپورٹ کریں', import_file: 'CSV امپورٹ کریں', print_sheet: 'موڑنے والی شیٹ پرنٹ کریں',
  csv_note: 'CSV فائل میں دو کالم ہوتے ہیں: سامنے اور پیچھے۔ یہ Excel اور Google Sheets میں کھلتی ہے۔',
  more_title: 'مزید اختیارات', backup: 'سب ڈیکوں کا بیک اپ',
  restore_q: 'اس بیک اپ فائل سے {n} ڈیک شامل کریں؟', restored: '{n} ڈیک شامل ہو گئے',
  reset_progress: 'پیش رفت ری سیٹ کریں', confirm_progress: 'اس ڈیک کے سب کارڈ واپس بکس 1 میں ڈالیں؟',
  progress_reset: 'سب کارڈ واپس بکس 1 میں ہیں۔',
  add_samples: 'نمونہ ڈیک شامل کریں', samples_added: '{n} نمونہ ڈیک شامل ہو گئے', samples_present: 'سب نمونہ ڈیک پہلے سے موجود ہیں۔',
  delete_deck: 'ڈیک حذف کریں', confirm_delete: 'ڈیک “{name}” اور اس کے سب کارڈ حذف کریں؟', deck_deleted: 'ڈیک حذف ہو گیا',
  import_title: 'ڈیک امپورٹ کریں', import_count: '{n} کارڈ', import_dup: 'یہ ڈیک آپ کے پاس پہلے سے ہے۔',
  open_copy: 'میری کاپی کھولیں', import_save: 'نئے ڈیک کے طور پر محفوظ کریں', import_merge: 'کھلے ہوئے ڈیک میں شامل کریں',
  import_saved: 'ڈیک محفوظ ہو گیا۔ پڑھنا شروع کریں!', import_more: '…اور {n}',
  bad_link: 'یہ لنک ٹوٹا ہوا یا ادھورا ہے۔ اپنے استاد سے دوبارہ بھیجنے کو کہیں۔',
  bad_file: 'اس فائل میں کوئی کارڈ نہیں ملا۔ دو کالم رکھیں: سامنے اور پیچھے۔',
  storage_full: 'محفوظ نہیں ہو سکا۔ اس آلے میں جگہ نہیں بچی۔',
  print_name: 'نام', print_class: 'جماعت', print_date: 'تاریخ',
  print_tip: 'صفحے کو نقطوں والی لکیر پر موڑیں۔ سامنے کا رخ پڑھیں، جواب بولیں، پھر موڑ کھول کر جانچیں۔',
  help_title: 'استعمال کیسے کریں · کلاس کے لیے خیالات',
  help_1: 'ایک ڈیک چنیں اور “پڑھنا شروع کریں” دبائیں۔ جواب سوچیں، پھر کارڈ پلٹیں۔',
  help_2: 'ایمان داری رکھیں: “مجھے یاد تھا” تبھی دبائیں جب سچ میں یاد ہو۔ آسان کارڈ دیر سے لوٹتے ہیں، مشکل کارڈ کل ہی آ جاتے ہیں۔ روز تھوڑا تھوڑا پڑھیں!',
  help_3: '“کارڈ بدلیں” میں اپنا ڈیک بنائیں، یا “آسام - دسپور” جیسی فہرست پیسٹ کریں۔ پھر اسے کلاس کو WhatsApp لنک سے بھیجیں۔',
  help_4: 'کلاس کی سرگرمی: اسمارٹ بورڈ پر “جوڑی ملاؤ” کھولیں، 8 جوڑیاں چنیں اور دو ٹیموں کو باری باری کھیلنے دیں۔ کم کوششوں والی ٹیم جیتے گی!',
  help_5: 'ہوم ورک کے لیے موڑنے والی شیٹ پرنٹ کریں: طلبہ صفحہ موڑ کر خود کو جانچیں گے۔ ٹیسٹ سے پہلے جلدی دہرائی کے لیے کوئز چلائیں۔',
  help_6: 'کی بورڈ: Space سے کارڈ پلٹیں، 1 = مجھے یاد تھا، 2 = ابھی سیکھ رہے ہیں۔',
  inside_title: 'اندر کیا ہو رہا ہے؟ (اسپیسڈ ریپیٹیشن)',
  inside_text: 'ہر کارڈ 5 میں سے کسی ایک بکس میں رہتا ہے۔ نئے اور بھولے ہوئے کارڈ بکس 1 میں رہتے ہیں اور روز آتے ہیں۔ ہر بار یاد رہنے پر کارڈ ایک بکس اوپر جاتا ہے اور زیادہ دنوں بعد لوٹتا ہے: 2 دن، 4 دن، ایک ہفتہ، پھر 2 ہفتے۔ اس سے آپ کا وقت ان چیزوں پر لگتا ہے جو ابھی یاد نہیں، اور بھولنے سے ذرا پہلے یاد کرنے سے یادداشت بہت پکی ہو جاتی ہے۔'
};
