/* Invitation Card Maker: UI strings. Keys are identical in all 12 languages.
   Card wording, example names and the small labels printed on the card are in content.js. */
window.APP_STRINGS = {
  en: {
    app_title: 'Invitation Card Maker',
    intro: 'Make beautiful invitation cards for weddings, engagements, birthdays, griha pravesh, pooja, school functions and shop openings, in your language, ready for WhatsApp or print.',
    privacy: 'Your names, photo and details never leave this device. Nothing is uploaded.',
    occ_title: 'Occasion',
    size_title: 'Size', size_wa: 'WhatsApp', size_story: 'Status / Story', size_square: 'Square', size_a5: 'A5 print',
    preview_aria: 'Invitation card preview. Click a line on the card to edit it.', making: 'Making the card…',
    share_btn: 'Send on WhatsApp', dl_png: 'Download PNG', copy_text: 'Copy invite text', print_a5: 'Print A5', print_2up: 'Print 2 on A4',
    print_hint: '"Print A5" prints one card per page. "Print 2 on A4" puts two cards side by side on one A4 sheet; cut along the middle.',
    shortcut: 'Shortcut: Ctrl + S downloads the PNG, Ctrl + P prints.',
    share_none: 'This browser cannot send pictures directly, so the card was downloaded. Send it from your gallery or Downloads.',
    saved_file: 'Saved {name}', copied_text: 'Invite text copied. Paste it in WhatsApp along with the card.',
    text_title: 'Wording', card_lang: 'Card language', example_note: 'This is an example invitation. Replace the names and details with yours.', example_clear: 'Clear example',
    heading_label: 'Heading', invite_label: 'Invitation line', n1_label: 'Name 1 (person, couple, family, school or shop)', join_label: 'Word between the names', n2_label: 'Name 2 (optional)',
    sub_label: 'Line under the names (parents, age, occasion)', closing_label: 'Closing line', family_label: 'From (family / hosts)', text_reset: 'Use the suggested wording',
    details_title: 'Date, time & venue', date_label: 'Date', time_label: 'Time', venue_label: 'Venue (name and address)',
    map_label: 'Google Maps link (optional, printed as a QR code)', map_bad: 'Paste a full link that starts with https://', map_ok: 'Guests can scan the QR code on the card to open the map.',
    schedule_label: 'Programme (optional, one function per line)', rsvp_label: 'RSVP phone number',
    design_title: 'Design', colours: 'Colours', colour_n: 'Colour set {n}',
    design_royal: 'Royal paisley', design_toran: 'Marigold toran', design_kalash: 'Kalash', design_lotus: 'Lotus', design_peacock: 'Peacock feather', design_diya: 'Diya lights', design_jaali: 'Jaali arch',
    design_floral: 'Roses', design_mandala: 'Mandala', design_balloons: 'Balloons', design_banana: 'Banana leaf', design_minimal: 'Minimal', design_ribbon: 'Ribbon', design_hearts: 'Rings & hearts',
    font_label: 'Lettering', font_elegant: 'Elegant', font_festive: 'Festive', font_simple: 'Simple',
    font_note: 'Elegant and festive letters download once from the internet. Without internet, the device font is used.',
    sym_title: 'Sacred symbol at the top', sym_none: 'None', sym_ganesh: 'Shree Ganesh', sym_om: 'Om', sym_ikonkar: 'Ik Onkar', sym_bismillah: 'Bismillah', sym_cross: 'Cross', sym_buddha: 'Dharma wheel',
    photo_title: 'Photo (optional)', photo_add: 'Add photo', photo_remove: 'Remove', photo_shape: 'Shape', shape_circle: 'Circle', shape_arch: 'Arch', shape_round: 'Rounded', photo_zoom: 'Zoom',
    photo_hint: 'Drag the photo on the card to move it.', img_bad: 'This file could not be opened. Please choose a JPG or PNG picture.',
    img_unsaved: 'The photo is too big to remember after you close this page, but you can use it now.',
    drafts_title: 'Drafts', drafts_help: 'Save a card to come back to it later, for example one card per function or per language.',
    draft_name_ph: 'Draft name, e.g. Priya wedding', draft_save: 'Save draft', draft_saved: 'Draft saved on this device.', draft_open: 'Open', draft_opened: 'Draft opened.', drafts_none: 'No saved drafts yet.',
    draft_full: 'Not enough space to save this draft. Delete an old draft or remove the photo.', draft_limit: 'Only 12 drafts are kept, so the oldest draft was removed.', draft_delete_q: 'Delete this draft?',
    help_title: 'How to use / Ideas',
    tip1: 'Pick the occasion, then change the names, date, time and venue. The card updates as you type.',
    tip2: 'Choose "WhatsApp" for sending, "Status / Story" for WhatsApp status and Instagram, and "A5 print" for the printing shop. Any card can also be printed 2 on an A4 sheet.',
    tip3: 'Paste your Google Maps link: guests scan the QR code on the card and reach the venue without asking for directions.',
    tip4: 'Make the same card in two languages: save a draft, change the card language, and download again. Hindi for relatives, English for colleagues.',
    tip5: 'For a wedding, add the Mehndi, Sangeet and Baraat timings in "Programme", or save one draft per function.',
    tip6: 'Your names, photo and details stay on this phone or computer. Nothing is uploaded, so the app also works without internet.'
  },
  hi: {
    app_title: 'निमंत्रण कार्ड मेकर',
    intro: 'शादी, सगाई, जन्मदिन, गृह प्रवेश, पूजा, स्कूल के कार्यक्रम और दुकान के उद्घाटन के सुंदर निमंत्रण कार्ड अपनी भाषा में बनाइए, WhatsApp या प्रिंट के लिए तैयार।',
    privacy: 'आपके नाम, फ़ोटो और जानकारी इसी डिवाइस में रहती है। कुछ भी अपलोड नहीं होता।',
    occ_title: 'मौका',
    size_title: 'साइज़', size_wa: 'WhatsApp', size_story: 'स्टेटस / स्टोरी', size_square: 'चौकोर', size_a5: 'A5 प्रिंट',
    preview_aria: 'निमंत्रण कार्ड का प्रीव्यू। कार्ड की किसी लाइन पर क्लिक करके उसे बदलें।', making: 'कार्ड बन रहा है…',
    share_btn: 'WhatsApp पर भेजें', dl_png: 'PNG डाउनलोड करें', copy_text: 'निमंत्रण का टेक्स्ट कॉपी करें', print_a5: 'A5 प्रिंट करें', print_2up: 'A4 पर 2 प्रिंट करें',
    print_hint: '"A5 प्रिंट" में हर पेज पर एक कार्ड छपता है। "A4 पर 2" में एक A4 शीट पर दो कार्ड अगल-बगल छपते हैं; बीच से काट लें।',
    shortcut: 'शॉर्टकट: Ctrl + S से PNG डाउनलोड, Ctrl + P से प्रिंट।',
    share_none: 'यह ब्राउज़र सीधे तस्वीर नहीं भेज सकता, इसलिए कार्ड डाउनलोड हो गया। इसे गैलरी या Downloads से भेजें।',
    saved_file: '{name} सेव हुआ', copied_text: 'निमंत्रण का टेक्स्ट कॉपी हो गया। इसे कार्ड के साथ WhatsApp में पेस्ट करें।',
    text_title: 'शब्द', card_lang: 'कार्ड की भाषा', example_note: 'यह एक उदाहरण निमंत्रण है। नाम और जानकारी अपनी लिखिए।', example_clear: 'उदाहरण हटाएँ',
    heading_label: 'शीर्षक', invite_label: 'निमंत्रण की पंक्ति', n1_label: 'नाम 1 (व्यक्ति, जोड़ा, परिवार, स्कूल या दुकान)', join_label: 'नामों के बीच का शब्द', n2_label: 'नाम 2 (वैकल्पिक)',
    sub_label: 'नामों के नीचे की पंक्ति (माता-पिता, उम्र, अवसर)', closing_label: 'अंतिम पंक्ति', family_label: 'की ओर से (परिवार / मेज़बान)', text_reset: 'सुझाए गए शब्द इस्तेमाल करें',
    details_title: 'तारीख, समय और स्थान', date_label: 'तारीख', time_label: 'समय', venue_label: 'स्थान (नाम और पता)',
    map_label: 'Google Maps लिंक (वैकल्पिक, QR कोड के रूप में छपेगा)', map_bad: 'https:// से शुरू होने वाला पूरा लिंक पेस्ट करें', map_ok: 'मेहमान कार्ड पर QR कोड स्कैन करके नक्शा खोल सकते हैं।',
    schedule_label: 'कार्यक्रम (वैकल्पिक, हर रस्म एक लाइन में)', rsvp_label: 'RSVP फ़ोन नंबर',
    design_title: 'डिज़ाइन', colours: 'रंग', colour_n: 'रंग सेट {n}',
    design_royal: 'शाही पैस्ले', design_toran: 'गेंदे का तोरण', design_kalash: 'कलश', design_lotus: 'कमल', design_peacock: 'मोर पंख', design_diya: 'दीये और झालर', design_jaali: 'जाली मेहराब',
    design_floral: 'गुलाब', design_mandala: 'मंडला', design_balloons: 'गुब्बारे', design_banana: 'केले का पत्ता', design_minimal: 'सादा', design_ribbon: 'रिबन', design_hearts: 'अंगूठियाँ और दिल',
    font_label: 'अक्षरों की शैली', font_elegant: 'सुंदर', font_festive: 'उत्सवी', font_simple: 'सादी',
    font_note: 'सुंदर और उत्सवी अक्षर एक बार इंटरनेट से डाउनलोड होते हैं। इंटरनेट न हो तो डिवाइस का फ़ॉन्ट इस्तेमाल होता है।',
    sym_title: 'ऊपर पवित्र चिह्न', sym_none: 'कोई नहीं', sym_ganesh: 'श्री गणेश', sym_om: 'ॐ (ओम)', sym_ikonkar: 'इक ओंकार', sym_bismillah: 'बिस्मिल्लाह', sym_cross: 'क्रॉस', sym_buddha: 'धर्म चक्र',
    photo_title: 'फ़ोटो (वैकल्पिक)', photo_add: 'फ़ोटो जोड़ें', photo_remove: 'हटाएँ', photo_shape: 'आकार', shape_circle: 'गोल', shape_arch: 'मेहराब', shape_round: 'गोल कोने', photo_zoom: 'ज़ूम',
    photo_hint: 'फ़ोटो को हिलाने के लिए कार्ड पर उसे खींचें।', img_bad: 'यह फ़ाइल नहीं खुल सकी। कृपया JPG या PNG तस्वीर चुनें।',
    img_unsaved: 'फ़ोटो इतनी बड़ी है कि पेज बंद करने के बाद याद नहीं रहेगी, लेकिन अभी इस्तेमाल कर सकते हैं।',
    drafts_title: 'ड्राफ़्ट', drafts_help: 'कार्ड सेव करके बाद में फिर खोलें, जैसे हर रस्म या हर भाषा के लिए एक कार्ड।',
    draft_name_ph: 'ड्राफ़्ट का नाम, जैसे प्रिया की शादी', draft_save: 'ड्राफ़्ट सेव करें', draft_saved: 'ड्राफ़्ट इसी डिवाइस में सेव हुआ।', draft_open: 'खोलें', draft_opened: 'ड्राफ़्ट खुल गया।', drafts_none: 'अभी कोई ड्राफ़्ट सेव नहीं है।',
    draft_full: 'इस ड्राफ़्ट के लिए जगह नहीं है। कोई पुराना ड्राफ़्ट हटाएँ या फ़ोटो हटाएँ।', draft_limit: 'सिर्फ़ 12 ड्राफ़्ट रखे जाते हैं, इसलिए सबसे पुराना ड्राफ़्ट हट गया।', draft_delete_q: 'यह ड्राफ़्ट हटाएँ?',
    help_title: 'कैसे इस्तेमाल करें / आइडिया',
    tip1: 'मौका चुनें, फिर नाम, तारीख, समय और स्थान बदलें। टाइप करते ही कार्ड बदल जाता है।',
    tip2: 'भेजने के लिए "WhatsApp", स्टेटस और Instagram के लिए "स्टेटस / स्टोरी", और प्रिंटिंग की दुकान के लिए "A5 प्रिंट" चुनें। कोई भी कार्ड A4 शीट पर 2 भी छप सकता है।',
    tip3: 'अपना Google Maps लिंक पेस्ट करें: मेहमान कार्ड का QR कोड स्कैन करके बिना रास्ता पूछे स्थान तक पहुँच जाएँगे।',
    tip4: 'एक ही कार्ड दो भाषाओं में बनाएँ: ड्राफ़्ट सेव करें, कार्ड की भाषा बदलें और फिर डाउनलोड करें। रिश्तेदारों के लिए हिंदी, सहकर्मियों के लिए अंग्रेज़ी।',
    tip5: 'शादी के लिए मेहंदी, संगीत और बारात का समय "कार्यक्रम" में लिखें, या हर रस्म के लिए अलग ड्राफ़्ट सेव करें।',
    tip6: 'आपके नाम, फ़ोटो और जानकारी इसी फ़ोन या कंप्यूटर में रहती है। कुछ अपलोड नहीं होता, इसलिए ऐप बिना इंटरनेट भी चलता है।'
  },
  bn: {
    app_title: 'নিমন্ত্রণ কার্ড মেকার',
    intro: 'বিয়ে, আশীর্বাদ, জন্মদিন, গৃহপ্রবেশ, পূজা, স্কুলের অনুষ্ঠান ও দোকান উদ্বোধনের সুন্দর নিমন্ত্রণ কার্ড নিজের ভাষায় বানান, WhatsApp বা প্রিন্টের জন্য তৈরি।',
    privacy: 'আপনার নাম, ছবি ও তথ্য এই ডিভাইসেই থাকে। কিছুই আপলোড হয় না।',
    occ_title: 'উপলক্ষ',
    size_title: 'মাপ', size_wa: 'WhatsApp', size_story: 'স্ট্যাটাস / স্টোরি', size_square: 'চৌকো', size_a5: 'A5 প্রিন্ট',
    preview_aria: 'নিমন্ত্রণ কার্ডের প্রিভিউ। কার্ডের কোনো লাইনে ক্লিক করে সেটি বদলান।', making: 'কার্ড তৈরি হচ্ছে…',
    share_btn: 'WhatsApp-এ পাঠান', dl_png: 'PNG ডাউনলোড', copy_text: 'নিমন্ত্রণের লেখা কপি করুন', print_a5: 'A5 প্রিন্ট', print_2up: 'A4-এ 2টি প্রিন্ট',
    print_hint: '"A5 প্রিন্ট"-এ প্রতি পাতায় একটি কার্ড ছাপা হয়। "A4-এ 2টি"-তে এক A4 পাতায় দুটি কার্ড পাশাপাশি ছাপা হয়; মাঝখান থেকে কেটে নিন।',
    shortcut: 'শর্টকাট: Ctrl + S-এ PNG ডাউনলোড, Ctrl + P-এ প্রিন্ট।',
    share_none: 'এই ব্রাউজার সরাসরি ছবি পাঠাতে পারে না, তাই কার্ডটি ডাউনলোড হয়েছে। গ্যালারি বা Downloads থেকে পাঠান।',
    saved_file: '{name} সেভ হয়েছে', copied_text: 'নিমন্ত্রণের লেখা কপি হয়েছে। কার্ডের সঙ্গে WhatsApp-এ পেস্ট করুন।',
    text_title: 'লেখা', card_lang: 'কার্ডের ভাষা', example_note: 'এটি একটি উদাহরণ নিমন্ত্রণ। নাম ও তথ্য নিজের মতো বদলান।', example_clear: 'উদাহরণ মুছুন',
    heading_label: 'শিরোনাম', invite_label: 'নিমন্ত্রণের লাইন', n1_label: 'নাম 1 (ব্যক্তি, দম্পতি, পরিবার, স্কুল বা দোকান)', join_label: 'নামের মাঝের শব্দ', n2_label: 'নাম 2 (ঐচ্ছিক)',
    sub_label: 'নামের নিচের লাইন (বাবা-মা, বয়স, উপলক্ষ)', closing_label: 'শেষ লাইন', family_label: 'পক্ষ থেকে (পরিবার / আয়োজক)', text_reset: 'প্রস্তাবিত লেখা ব্যবহার করুন',
    details_title: 'তারিখ, সময় ও স্থান', date_label: 'তারিখ', time_label: 'সময়', venue_label: 'স্থান (নাম ও ঠিকানা)',
    map_label: 'Google Maps লিংক (ঐচ্ছিক, QR কোড হিসেবে ছাপা হবে)', map_bad: 'https:// দিয়ে শুরু পুরো লিংক পেস্ট করুন', map_ok: 'অতিথিরা কার্ডের QR কোড স্ক্যান করে ম্যাপ খুলতে পারবেন।',
    schedule_label: 'অনুষ্ঠানসূচি (ঐচ্ছিক, প্রতি লাইনে একটি অনুষ্ঠান)', rsvp_label: 'RSVP ফোন নম্বর',
    design_title: 'ডিজাইন', colours: 'রং', colour_n: 'রঙের সেট {n}',
    design_royal: 'রাজকীয় কলকা', design_toran: 'গাঁদার তোরণ', design_kalash: 'কলস', design_lotus: 'পদ্ম', design_peacock: 'ময়ূরপালক', design_diya: 'প্রদীপ ও আলো', design_jaali: 'জালি খিলান',
    design_floral: 'গোলাপ', design_mandala: 'মণ্ডল', design_balloons: 'বেলুন', design_banana: 'কলাপাতা', design_minimal: 'সাদামাটা', design_ribbon: 'ফিতা', design_hearts: 'আংটি ও হৃদয়',
    font_label: 'অক্ষরের ধরন', font_elegant: 'সুন্দর', font_festive: 'উৎসবের', font_simple: 'সাধারণ',
    font_note: 'সুন্দর ও উৎসবের অক্ষর একবার ইন্টারনেট থেকে ডাউনলোড হয়। ইন্টারনেট না থাকলে ডিভাইসের ফন্ট ব্যবহার হয়।',
    sym_title: 'উপরে পবিত্র চিহ্ন', sym_none: 'কিছু না', sym_ganesh: 'শ্রী গণেশ', sym_om: 'ওঁ', sym_ikonkar: 'ইক ওঙ্কার', sym_bismillah: 'বিসমিল্লাহ', sym_cross: 'ক্রস', sym_buddha: 'ধর্মচক্র',
    photo_title: 'ছবি (ঐচ্ছিক)', photo_add: 'ছবি যোগ করুন', photo_remove: 'সরান', photo_shape: 'আকার', shape_circle: 'গোল', shape_arch: 'খিলান', shape_round: 'গোল কোণ', photo_zoom: 'জুম',
    photo_hint: 'ছবি সরাতে কার্ডের উপর টেনে আনুন।', img_bad: 'এই ফাইলটি খোলা গেল না। JPG বা PNG ছবি বেছে নিন।',
    img_unsaved: 'ছবিটি এত বড় যে পাতা বন্ধ করলে মনে থাকবে না, তবে এখন ব্যবহার করা যাবে।',
    drafts_title: 'খসড়া', drafts_help: 'কার্ড সেভ করে পরে আবার খুলুন, যেমন প্রতিটি অনুষ্ঠান বা ভাষার জন্য একটি কার্ড।',
    draft_name_ph: 'খসড়ার নাম, যেমন প্রিয়ার বিয়ে', draft_save: 'খসড়া সেভ করুন', draft_saved: 'খসড়া এই ডিভাইসে সেভ হয়েছে।', draft_open: 'খুলুন', draft_opened: 'খসড়া খোলা হয়েছে।', drafts_none: 'এখনও কোনো খসড়া সেভ করা নেই।',
    draft_full: 'এই খসড়ার জন্য জায়গা নেই। পুরনো খসড়া মুছুন বা ছবি সরান।', draft_limit: 'শুধু 12টি খসড়া রাখা হয়, তাই সবচেয়ে পুরনো খসড়াটি মুছে গেছে।', draft_delete_q: 'এই খসড়া মুছবেন?',
    help_title: 'কীভাবে ব্যবহার করবেন / আইডিয়া',
    tip1: 'উপলক্ষ বেছে নিন, তারপর নাম, তারিখ, সময় ও স্থান বদলান। লিখতে লিখতেই কার্ড বদলে যায়।',
    tip2: 'পাঠানোর জন্য "WhatsApp", স্ট্যাটাস ও Instagram-এর জন্য "স্ট্যাটাস / স্টোরি", আর প্রিন্টের দোকানের জন্য "A5 প্রিন্ট" বেছে নিন। যেকোনো কার্ড A4 পাতায় 2টিও ছাপা যায়।',
    tip3: 'আপনার Google Maps লিংক পেস্ট করুন: অতিথিরা কার্ডের QR কোড স্ক্যান করে পথ না জিজ্ঞেস করেই পৌঁছে যাবেন।',
    tip4: 'একই কার্ড দুই ভাষায় বানান: খসড়া সেভ করুন, কার্ডের ভাষা বদলান, আবার ডাউনলোড করুন। আত্মীয়দের জন্য বাংলা, সহকর্মীদের জন্য ইংরেজি।',
    tip5: 'বিয়ের জন্য মেহেন্দি, সঙ্গীত ও বরযাত্রীর সময় "অনুষ্ঠানসূচি"-তে লিখুন, বা প্রতিটি অনুষ্ঠানের জন্য আলাদা খসড়া সেভ করুন।',
    tip6: 'আপনার নাম, ছবি ও তথ্য এই ফোন বা কম্পিউটারেই থাকে। কিছুই আপলোড হয় না, তাই অ্যাপটি ইন্টারনেট ছাড়াও চলে।'
  },
  mr: {
    app_title: 'निमंत्रण पत्रिका मेकर',
    intro: 'लग्न, साखरपुडा, वाढदिवस, गृहप्रवेश, पूजा, शाळेचे कार्यक्रम आणि दुकानाच्या उद्घाटनाच्या सुंदर निमंत्रण पत्रिका तुमच्या भाषेत बनवा, WhatsApp किंवा प्रिंटसाठी तयार.',
    privacy: 'तुमची नावे, फोटो आणि माहिती याच डिव्हाइसवर राहते. काहीही अपलोड होत नाही.',
    occ_title: 'प्रसंग',
    size_title: 'आकार', size_wa: 'WhatsApp', size_story: 'स्टेटस / स्टोरी', size_square: 'चौरस', size_a5: 'A5 प्रिंट',
    preview_aria: 'निमंत्रण पत्रिकेचे प्रिव्ह्यू. पत्रिकेवरील ओळीवर क्लिक करून ती बदला.', making: 'पत्रिका तयार होत आहे…',
    share_btn: 'WhatsApp वर पाठवा', dl_png: 'PNG डाउनलोड करा', copy_text: 'निमंत्रणाचा मजकूर कॉपी करा', print_a5: 'A5 प्रिंट करा', print_2up: 'A4 वर 2 प्रिंट करा',
    print_hint: '"A5 प्रिंट" मध्ये प्रत्येक पानावर एक पत्रिका छापली जाते. "A4 वर 2" मध्ये एका A4 शीटवर दोन पत्रिका शेजारी छापल्या जातात; मधून कापा.',
    shortcut: 'शॉर्टकट: Ctrl + S ने PNG डाउनलोड, Ctrl + P ने प्रिंट.',
    share_none: 'हा ब्राउझर थेट चित्र पाठवू शकत नाही, म्हणून पत्रिका डाउनलोड झाली. ती गॅलरी किंवा Downloads मधून पाठवा.',
    saved_file: '{name} सेव्ह झाले', copied_text: 'निमंत्रणाचा मजकूर कॉपी झाला. पत्रिकेसोबत WhatsApp मध्ये पेस्ट करा.',
    text_title: 'मजकूर', card_lang: 'पत्रिकेची भाषा', example_note: 'ही उदाहरणादाखल पत्रिका आहे. नावे आणि माहिती तुमची लिहा.', example_clear: 'उदाहरण काढा',
    heading_label: 'शीर्षक', invite_label: 'निमंत्रणाची ओळ', n1_label: 'नाव 1 (व्यक्ती, जोडपे, परिवार, शाळा किंवा दुकान)', join_label: 'नावांमधील शब्द', n2_label: 'नाव 2 (ऐच्छिक)',
    sub_label: 'नावांखालील ओळ (आई-वडील, वय, प्रसंग)', closing_label: 'शेवटची ओळ', family_label: 'कडून (परिवार / यजमान)', text_reset: 'सुचवलेला मजकूर वापरा',
    details_title: 'दिनांक, वेळ आणि स्थळ', date_label: 'दिनांक', time_label: 'वेळ', venue_label: 'स्थळ (नाव आणि पत्ता)',
    map_label: 'Google Maps लिंक (ऐच्छिक, QR कोड म्हणून छापली जाईल)', map_bad: 'https:// ने सुरू होणारी पूर्ण लिंक पेस्ट करा', map_ok: 'पाहुणे पत्रिकेवरील QR कोड स्कॅन करून नकाशा उघडू शकतात.',
    schedule_label: 'कार्यक्रम (ऐच्छिक, प्रत्येक विधी एका ओळीत)', rsvp_label: 'RSVP फोन नंबर',
    design_title: 'डिझाइन', colours: 'रंग', colour_n: 'रंग संच {n}',
    design_royal: 'राजेशाही पैस्ली', design_toran: 'झेंडूचे तोरण', design_kalash: 'कलश', design_lotus: 'कमळ', design_peacock: 'मोरपीस', design_diya: 'दिवे आणि रोषणाई', design_jaali: 'जाळीची कमान',
    design_floral: 'गुलाब', design_mandala: 'मंडल', design_balloons: 'फुगे', design_banana: 'केळीचे पान', design_minimal: 'साधे', design_ribbon: 'रिबन', design_hearts: 'अंगठ्या आणि हृदय',
    font_label: 'अक्षरशैली', font_elegant: 'नाजूक', font_festive: 'उत्सवी', font_simple: 'साधी',
    font_note: 'नाजूक आणि उत्सवी अक्षरे एकदा इंटरनेटवरून डाउनलोड होतात. इंटरनेट नसल्यास डिव्हाइसचा फॉन्ट वापरला जातो.',
    sym_title: 'वर पवित्र चिन्ह', sym_none: 'काही नाही', sym_ganesh: 'श्री गणेश', sym_om: 'ॐ (ओम)', sym_ikonkar: 'इक ओंकार', sym_bismillah: 'बिस्मिल्लाह', sym_cross: 'क्रॉस', sym_buddha: 'धर्मचक्र',
    photo_title: 'फोटो (ऐच्छिक)', photo_add: 'फोटो जोडा', photo_remove: 'काढा', photo_shape: 'आकार', shape_circle: 'गोल', shape_arch: 'कमान', shape_round: 'गोल कोपरे', photo_zoom: 'झूम',
    photo_hint: 'फोटो हलवण्यासाठी पत्रिकेवर तो ओढा.', img_bad: 'ही फाइल उघडता आली नाही. कृपया JPG किंवा PNG चित्र निवडा.',
    img_unsaved: 'फोटो इतका मोठा आहे की पान बंद केल्यावर लक्षात राहणार नाही, पण आता वापरता येईल.',
    drafts_title: 'मसुदे', drafts_help: 'पत्रिका सेव्ह करून नंतर पुन्हा उघडा, उदा. प्रत्येक विधीसाठी किंवा भाषेसाठी एक पत्रिका.',
    draft_name_ph: 'मसुद्याचे नाव, उदा. प्रियाचे लग्न', draft_save: 'मसुदा सेव्ह करा', draft_saved: 'मसुदा याच डिव्हाइसवर सेव्ह झाला.', draft_open: 'उघडा', draft_opened: 'मसुदा उघडला.', drafts_none: 'अजून कोणताही मसुदा सेव्ह केलेला नाही.',
    draft_full: 'या मसुद्यासाठी जागा नाही. जुना मसुदा हटवा किंवा फोटो काढा.', draft_limit: 'फक्त 12 मसुदे ठेवले जातात, म्हणून सर्वात जुना मसुदा काढला गेला.', draft_delete_q: 'हा मसुदा हटवायचा?',
    help_title: 'कसे वापरावे / कल्पना',
    tip1: 'प्रसंग निवडा, मग नावे, दिनांक, वेळ आणि स्थळ बदला. टाइप करताच पत्रिका बदलते.',
    tip2: 'पाठवण्यासाठी "WhatsApp", स्टेटस आणि Instagram साठी "स्टेटस / स्टोरी", आणि प्रिंटिंगच्या दुकानासाठी "A5 प्रिंट" निवडा. कोणतीही पत्रिका A4 शीटवर 2 अशीही छापता येते.',
    tip3: 'तुमची Google Maps लिंक पेस्ट करा: पाहुणे पत्रिकेवरील QR कोड स्कॅन करून रस्ता न विचारता स्थळी पोहोचतील.',
    tip4: 'तीच पत्रिका दोन भाषांत बनवा: मसुदा सेव्ह करा, पत्रिकेची भाषा बदला आणि पुन्हा डाउनलोड करा. नातेवाइकांसाठी मराठी, सहकाऱ्यांसाठी इंग्रजी.',
    tip5: 'लग्नासाठी मेहंदी, संगीत आणि वरातीच्या वेळा "कार्यक्रम" मध्ये लिहा, किंवा प्रत्येक विधीसाठी वेगळा मसुदा सेव्ह करा.',
    tip6: 'तुमची नावे, फोटो आणि माहिती याच फोन किंवा कॉम्प्युटरवर राहते. काहीही अपलोड होत नाही, त्यामुळे ॲप इंटरनेटशिवायही चालते.'
  },
  gu: {
    app_title: 'આમંત્રણ કાર્ડ મેકર',
    intro: 'લગ્ન, સગાઈ, જન્મદિવસ, ગૃહપ્રવેશ, પૂજા, શાળાના કાર્યક્રમો અને દુકાનના ઉદ્ઘાટનનાં સુંદર આમંત્રણ કાર્ડ તમારી ભાષામાં બનાવો, WhatsApp કે પ્રિન્ટ માટે તૈયાર.',
    privacy: 'તમારાં નામ, ફોટો અને માહિતી આ જ ડિવાઇસમાં રહે છે. કંઈ અપલોડ થતું નથી.',
    occ_title: 'પ્રસંગ',
    size_title: 'સાઇઝ', size_wa: 'WhatsApp', size_story: 'સ્ટેટસ / સ્ટોરી', size_square: 'ચોરસ', size_a5: 'A5 પ્રિન્ટ',
    preview_aria: 'આમંત્રણ કાર્ડનું પ્રિવ્યૂ. કાર્ડની કોઈ લાઇન પર ક્લિક કરીને તે બદલો.', making: 'કાર્ડ બની રહ્યું છે…',
    share_btn: 'WhatsApp પર મોકલો', dl_png: 'PNG ડાઉનલોડ કરો', copy_text: 'આમંત્રણનું લખાણ કૉપિ કરો', print_a5: 'A5 પ્રિન્ટ કરો', print_2up: 'A4 પર 2 પ્રિન્ટ કરો',
    print_hint: '"A5 પ્રિન્ટ"માં દરેક પાન પર એક કાર્ડ છપાય છે. "A4 પર 2"માં એક A4 શીટ પર બે કાર્ડ બાજુ-બાજુમાં છપાય છે; વચ્ચેથી કાપી લો.',
    shortcut: 'શૉર્ટકટ: Ctrl + S થી PNG ડાઉનલોડ, Ctrl + P થી પ્રિન્ટ.',
    share_none: 'આ બ્રાઉઝર સીધું ચિત્ર મોકલી શકતું નથી, એટલે કાર્ડ ડાઉનલોડ થયું. તેને ગૅલરી કે Downloads માંથી મોકલો.',
    saved_file: '{name} સેવ થયું', copied_text: 'આમંત્રણનું લખાણ કૉપિ થયું. કાર્ડ સાથે WhatsApp માં પેસ્ટ કરો.',
    text_title: 'લખાણ', card_lang: 'કાર્ડની ભાષા', example_note: 'આ એક ઉદાહરણ આમંત્રણ છે. નામ અને માહિતી તમારાં લખો.', example_clear: 'ઉદાહરણ કાઢો',
    heading_label: 'મથાળું', invite_label: 'આમંત્રણની લાઇન', n1_label: 'નામ 1 (વ્યક્તિ, યુગલ, પરિવાર, શાળા કે દુકાન)', join_label: 'નામો વચ્ચેનો શબ્દ', n2_label: 'નામ 2 (વૈકલ્પિક)',
    sub_label: 'નામો નીચેની લાઇન (માતા-પિતા, ઉંમર, પ્રસંગ)', closing_label: 'છેલ્લી લાઇન', family_label: 'તરફથી (પરિવાર / યજમાન)', text_reset: 'સૂચવેલું લખાણ વાપરો',
    details_title: 'તારીખ, સમય અને સ્થળ', date_label: 'તારીખ', time_label: 'સમય', venue_label: 'સ્થળ (નામ અને સરનામું)',
    map_label: 'Google Maps લિંક (વૈકલ્પિક, QR કોડ તરીકે છપાશે)', map_bad: 'https:// થી શરૂ થતી પૂરી લિંક પેસ્ટ કરો', map_ok: 'મહેમાનો કાર્ડ પરનો QR કોડ સ્કૅન કરીને નકશો ખોલી શકે છે.',
    schedule_label: 'કાર્યક્રમ (વૈકલ્પિક, દરેક વિધિ એક લાઇનમાં)', rsvp_label: 'RSVP ફોન નંબર',
    design_title: 'ડિઝાઇન', colours: 'રંગ', colour_n: 'રંગ સેટ {n}',
    design_royal: 'શાહી પૈસ્લી', design_toran: 'ગલગોટાનું તોરણ', design_kalash: 'કળશ', design_lotus: 'કમળ', design_peacock: 'મોરપીંછ', design_diya: 'દીવા અને રોશની', design_jaali: 'જાળી કમાન',
    design_floral: 'ગુલાબ', design_mandala: 'મંડલ', design_balloons: 'ફુગ્ગા', design_banana: 'કેળનું પાન', design_minimal: 'સાદું', design_ribbon: 'રિબન', design_hearts: 'વીંટી અને હૃદય',
    font_label: 'અક્ષરોની શૈલી', font_elegant: 'સુંદર', font_festive: 'ઉત્સવી', font_simple: 'સાદી',
    font_note: 'સુંદર અને ઉત્સવી અક્ષરો એક વાર ઇન્ટરનેટથી ડાઉનલોડ થાય છે. ઇન્ટરનેટ ન હોય તો ડિવાઇસનો ફૉન્ટ વપરાય છે.',
    sym_title: 'ઉપર પવિત્ર ચિહ્ન', sym_none: 'કંઈ નહીં', sym_ganesh: 'શ્રી ગણેશ', sym_om: 'ૐ (ઓમ)', sym_ikonkar: 'ઇક ઓંકાર', sym_bismillah: 'બિસ્મિલ્લાહ', sym_cross: 'ક્રોસ', sym_buddha: 'ધર્મચક્ર',
    photo_title: 'ફોટો (વૈકલ્પિક)', photo_add: 'ફોટો ઉમેરો', photo_remove: 'કાઢો', photo_shape: 'આકાર', shape_circle: 'ગોળ', shape_arch: 'કમાન', shape_round: 'ગોળ ખૂણા', photo_zoom: 'ઝૂમ',
    photo_hint: 'ફોટો ખસેડવા કાર્ડ પર તેને ખેંચો.', img_bad: 'આ ફાઇલ ખૂલી શકી નહીં. કૃપા કરીને JPG કે PNG ચિત્ર પસંદ કરો.',
    img_unsaved: 'ફોટો એટલો મોટો છે કે પાનું બંધ કર્યા પછી યાદ નહીં રહે, પણ અત્યારે વાપરી શકો છો.',
    drafts_title: 'ડ્રાફ્ટ', drafts_help: 'કાર્ડ સેવ કરીને પછી ફરી ખોલો, જેમ કે દરેક વિધિ કે ભાષા માટે એક કાર્ડ.',
    draft_name_ph: 'ડ્રાફ્ટનું નામ, જેમ કે પ્રિયાનાં લગ્ન', draft_save: 'ડ્રાફ્ટ સેવ કરો', draft_saved: 'ડ્રાફ્ટ આ જ ડિવાઇસમાં સેવ થયો.', draft_open: 'ખોલો', draft_opened: 'ડ્રાફ્ટ ખૂલ્યો.', drafts_none: 'હજી કોઈ ડ્રાફ્ટ સેવ નથી.',
    draft_full: 'આ ડ્રાફ્ટ માટે જગ્યા નથી. જૂનો ડ્રાફ્ટ કાઢો કે ફોટો કાઢો.', draft_limit: 'માત્ર 12 ડ્રાફ્ટ રાખવામાં આવે છે, તેથી સૌથી જૂનો ડ્રાફ્ટ કાઢી નાખ્યો.', draft_delete_q: 'આ ડ્રાફ્ટ કાઢવો છે?',
    help_title: 'કેવી રીતે વાપરવું / આઇડિયા',
    tip1: 'પ્રસંગ પસંદ કરો, પછી નામ, તારીખ, સમય અને સ્થળ બદલો. ટાઇપ કરતાં જ કાર્ડ બદલાય છે.',
    tip2: 'મોકલવા માટે "WhatsApp", સ્ટેટસ અને Instagram માટે "સ્ટેટસ / સ્ટોરી", અને પ્રિન્ટિંગની દુકાન માટે "A5 પ્રિન્ટ" પસંદ કરો. કોઈપણ કાર્ડ A4 શીટ પર 2 પણ છાપી શકાય.',
    tip3: 'તમારી Google Maps લિંક પેસ્ટ કરો: મહેમાનો કાર્ડનો QR કોડ સ્કૅન કરીને રસ્તો પૂછ્યા વગર સ્થળે પહોંચી જશે.',
    tip4: 'એક જ કાર્ડ બે ભાષામાં બનાવો: ડ્રાફ્ટ સેવ કરો, કાર્ડની ભાષા બદલો અને ફરી ડાઉનલોડ કરો. સગાં માટે ગુજરાતી, સહકર્મીઓ માટે અંગ્રેજી.',
    tip5: 'લગ્ન માટે મહેંદી, સંગીત અને જાનનો સમય "કાર્યક્રમ"માં લખો, અથવા દરેક વિધિ માટે અલગ ડ્રાફ્ટ સેવ કરો.',
    tip6: 'તમારાં નામ, ફોટો અને માહિતી આ જ ફોન કે કમ્પ્યૂટરમાં રહે છે. કંઈ અપલોડ થતું નથી, એટલે ઍપ ઇન્ટરનેટ વગર પણ ચાલે છે.'
  },
  pa: {
    app_title: 'ਸੱਦਾ ਕਾਰਡ ਮੇਕਰ',
    intro: 'ਵਿਆਹ, ਮੰਗਣੀ, ਜਨਮਦਿਨ, ਗ੍ਰਹਿ ਪ੍ਰਵੇਸ਼, ਪਾਠ, ਸਕੂਲ ਦੇ ਸਮਾਗਮ ਅਤੇ ਦੁਕਾਨ ਦੇ ਉਦਘਾਟਨ ਦੇ ਸੋਹਣੇ ਸੱਦਾ ਕਾਰਡ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬਣਾਓ, WhatsApp ਜਾਂ ਪ੍ਰਿੰਟ ਲਈ ਤਿਆਰ।',
    privacy: 'ਤੁਹਾਡੇ ਨਾਮ, ਫ਼ੋਟੋ ਅਤੇ ਜਾਣਕਾਰੀ ਇਸੇ ਡਿਵਾਈਸ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ। ਕੁਝ ਵੀ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ।',
    occ_title: 'ਮੌਕਾ',
    size_title: 'ਸਾਈਜ਼', size_wa: 'WhatsApp', size_story: 'ਸਟੇਟਸ / ਸਟੋਰੀ', size_square: 'ਚੌਰਸ', size_a5: 'A5 ਪ੍ਰਿੰਟ',
    preview_aria: 'ਸੱਦਾ ਕਾਰਡ ਦਾ ਪ੍ਰੀਵਿਊ। ਕਾਰਡ ਦੀ ਕਿਸੇ ਲਾਈਨ ਤੇ ਕਲਿੱਕ ਕਰਕੇ ਉਸ ਨੂੰ ਬਦਲੋ।', making: 'ਕਾਰਡ ਬਣ ਰਿਹਾ ਹੈ…',
    share_btn: 'WhatsApp ਤੇ ਭੇਜੋ', dl_png: 'PNG ਡਾਊਨਲੋਡ ਕਰੋ', copy_text: 'ਸੱਦੇ ਦਾ ਟੈਕਸਟ ਕਾਪੀ ਕਰੋ', print_a5: 'A5 ਪ੍ਰਿੰਟ ਕਰੋ', print_2up: 'A4 ਤੇ 2 ਪ੍ਰਿੰਟ ਕਰੋ',
    print_hint: '"A5 ਪ੍ਰਿੰਟ" ਵਿੱਚ ਹਰ ਪੰਨੇ ਤੇ ਇੱਕ ਕਾਰਡ ਛਪਦਾ ਹੈ। "A4 ਤੇ 2" ਵਿੱਚ ਇੱਕ A4 ਸ਼ੀਟ ਤੇ ਦੋ ਕਾਰਡ ਨਾਲ-ਨਾਲ ਛਪਦੇ ਹਨ; ਵਿਚਕਾਰੋਂ ਕੱਟ ਲਓ।',
    shortcut: 'ਸ਼ਾਰਟਕੱਟ: Ctrl + S ਨਾਲ PNG ਡਾਊਨਲੋਡ, Ctrl + P ਨਾਲ ਪ੍ਰਿੰਟ।',
    share_none: 'ਇਹ ਬ੍ਰਾਊਜ਼ਰ ਸਿੱਧੀ ਤਸਵੀਰ ਨਹੀਂ ਭੇਜ ਸਕਦਾ, ਇਸ ਲਈ ਕਾਰਡ ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ। ਇਸ ਨੂੰ ਗੈਲਰੀ ਜਾਂ Downloads ਤੋਂ ਭੇਜੋ।',
    saved_file: '{name} ਸੇਵ ਹੋਇਆ', copied_text: 'ਸੱਦੇ ਦਾ ਟੈਕਸਟ ਕਾਪੀ ਹੋ ਗਿਆ। ਇਸ ਨੂੰ ਕਾਰਡ ਨਾਲ WhatsApp ਵਿੱਚ ਪੇਸਟ ਕਰੋ।',
    text_title: 'ਸ਼ਬਦ', card_lang: 'ਕਾਰਡ ਦੀ ਭਾਸ਼ਾ', example_note: 'ਇਹ ਇੱਕ ਉਦਾਹਰਨ ਸੱਦਾ ਹੈ। ਨਾਮ ਅਤੇ ਜਾਣਕਾਰੀ ਆਪਣੀ ਲਿਖੋ।', example_clear: 'ਉਦਾਹਰਨ ਹਟਾਓ',
    heading_label: 'ਸਿਰਲੇਖ', invite_label: 'ਸੱਦੇ ਦੀ ਲਾਈਨ', n1_label: 'ਨਾਮ 1 (ਵਿਅਕਤੀ, ਜੋੜਾ, ਪਰਿਵਾਰ, ਸਕੂਲ ਜਾਂ ਦੁਕਾਨ)', join_label: 'ਨਾਵਾਂ ਵਿਚਕਾਰ ਦਾ ਸ਼ਬਦ', n2_label: 'ਨਾਮ 2 (ਵਿਕਲਪਿਕ)',
    sub_label: 'ਨਾਵਾਂ ਹੇਠਲੀ ਲਾਈਨ (ਮਾਪੇ, ਉਮਰ, ਮੌਕਾ)', closing_label: 'ਆਖ਼ਰੀ ਲਾਈਨ', family_label: 'ਵੱਲੋਂ (ਪਰਿਵਾਰ / ਮੇਜ਼ਬਾਨ)', text_reset: 'ਸੁਝਾਏ ਸ਼ਬਦ ਵਰਤੋ',
    details_title: 'ਤਾਰੀਖ਼, ਸਮਾਂ ਅਤੇ ਸਥਾਨ', date_label: 'ਤਾਰੀਖ਼', time_label: 'ਸਮਾਂ', venue_label: 'ਸਥਾਨ (ਨਾਮ ਅਤੇ ਪਤਾ)',
    map_label: 'Google Maps ਲਿੰਕ (ਵਿਕਲਪਿਕ, QR ਕੋਡ ਵਜੋਂ ਛਪੇਗਾ)', map_bad: 'https:// ਨਾਲ ਸ਼ੁਰੂ ਹੋਣ ਵਾਲਾ ਪੂਰਾ ਲਿੰਕ ਪੇਸਟ ਕਰੋ', map_ok: 'ਮਹਿਮਾਨ ਕਾਰਡ ਤੇ QR ਕੋਡ ਸਕੈਨ ਕਰਕੇ ਨਕਸ਼ਾ ਖੋਲ੍ਹ ਸਕਦੇ ਹਨ।',
    schedule_label: 'ਪ੍ਰੋਗਰਾਮ (ਵਿਕਲਪਿਕ, ਹਰ ਰਸਮ ਇੱਕ ਲਾਈਨ ਵਿੱਚ)', rsvp_label: 'RSVP ਫ਼ੋਨ ਨੰਬਰ',
    design_title: 'ਡਿਜ਼ਾਈਨ', colours: 'ਰੰਗ', colour_n: 'ਰੰਗ ਸੈੱਟ {n}',
    design_royal: 'ਸ਼ਾਹੀ ਅੰਬੀ', design_toran: 'ਗੇਂਦੇ ਦਾ ਤੋਰਣ', design_kalash: 'ਕਲਸ਼', design_lotus: 'ਕਮਲ', design_peacock: 'ਮੋਰ ਪੰਖ', design_diya: 'ਦੀਵੇ ਅਤੇ ਲੜੀਆਂ', design_jaali: 'ਜਾਲੀ ਮਹਿਰਾਬ',
    design_floral: 'ਗੁਲਾਬ', design_mandala: 'ਮੰਡਲ', design_balloons: 'ਗੁਬਾਰੇ', design_banana: 'ਕੇਲੇ ਦਾ ਪੱਤਾ', design_minimal: 'ਸਾਦਾ', design_ribbon: 'ਰਿਬਨ', design_hearts: 'ਮੁੰਦਰੀਆਂ ਅਤੇ ਦਿਲ',
    font_label: 'ਅੱਖਰਾਂ ਦੀ ਸ਼ੈਲੀ', font_elegant: 'ਸੋਹਣੀ', font_festive: 'ਤਿਉਹਾਰੀ', font_simple: 'ਸਾਦੀ',
    font_note: 'ਸੋਹਣੇ ਅਤੇ ਤਿਉਹਾਰੀ ਅੱਖਰ ਇੱਕ ਵਾਰ ਇੰਟਰਨੈੱਟ ਤੋਂ ਡਾਊਨਲੋਡ ਹੁੰਦੇ ਹਨ। ਇੰਟਰਨੈੱਟ ਨਾ ਹੋਵੇ ਤਾਂ ਡਿਵਾਈਸ ਦਾ ਫ਼ੌਂਟ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।',
    sym_title: 'ਉੱਪਰ ਪਵਿੱਤਰ ਚਿੰਨ੍ਹ', sym_none: 'ਕੋਈ ਨਹੀਂ', sym_ganesh: 'ਸ਼੍ਰੀ ਗਣੇਸ਼', sym_om: 'ਓਮ', sym_ikonkar: 'ੴ ਇੱਕ ਓਅੰਕਾਰ', sym_bismillah: 'ਬਿਸਮਿੱਲਾਹ', sym_cross: 'ਕ੍ਰਾਸ', sym_buddha: 'ਧਰਮ ਚੱਕਰ',
    photo_title: 'ਫ਼ੋਟੋ (ਵਿਕਲਪਿਕ)', photo_add: 'ਫ਼ੋਟੋ ਜੋੜੋ', photo_remove: 'ਹਟਾਓ', photo_shape: 'ਆਕਾਰ', shape_circle: 'ਗੋਲ', shape_arch: 'ਮਹਿਰਾਬ', shape_round: 'ਗੋਲ ਕੋਨੇ', photo_zoom: 'ਜ਼ੂਮ',
    photo_hint: 'ਫ਼ੋਟੋ ਹਿਲਾਉਣ ਲਈ ਕਾਰਡ ਤੇ ਉਸ ਨੂੰ ਖਿੱਚੋ।', img_bad: 'ਇਹ ਫ਼ਾਈਲ ਨਹੀਂ ਖੁੱਲ੍ਹ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ JPG ਜਾਂ PNG ਤਸਵੀਰ ਚੁਣੋ।',
    img_unsaved: 'ਫ਼ੋਟੋ ਇੰਨੀ ਵੱਡੀ ਹੈ ਕਿ ਪੰਨਾ ਬੰਦ ਕਰਨ ਤੋਂ ਬਾਅਦ ਯਾਦ ਨਹੀਂ ਰਹੇਗੀ, ਪਰ ਹੁਣ ਵਰਤ ਸਕਦੇ ਹੋ।',
    drafts_title: 'ਡਰਾਫ਼ਟ', drafts_help: 'ਕਾਰਡ ਸੇਵ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਫਿਰ ਖੋਲ੍ਹੋ, ਜਿਵੇਂ ਹਰ ਰਸਮ ਜਾਂ ਹਰ ਭਾਸ਼ਾ ਲਈ ਇੱਕ ਕਾਰਡ।',
    draft_name_ph: 'ਡਰਾਫ਼ਟ ਦਾ ਨਾਮ, ਜਿਵੇਂ ਸਿਮਰਨ ਦਾ ਵਿਆਹ', draft_save: 'ਡਰਾਫ਼ਟ ਸੇਵ ਕਰੋ', draft_saved: 'ਡਰਾਫ਼ਟ ਇਸੇ ਡਿਵਾਈਸ ਵਿੱਚ ਸੇਵ ਹੋਇਆ।', draft_open: 'ਖੋਲ੍ਹੋ', draft_opened: 'ਡਰਾਫ਼ਟ ਖੁੱਲ੍ਹ ਗਿਆ।', drafts_none: 'ਹਾਲੇ ਕੋਈ ਡਰਾਫ਼ਟ ਸੇਵ ਨਹੀਂ।',
    draft_full: 'ਇਸ ਡਰਾਫ਼ਟ ਲਈ ਥਾਂ ਨਹੀਂ ਹੈ। ਕੋਈ ਪੁਰਾਣਾ ਡਰਾਫ਼ਟ ਮਿਟਾਓ ਜਾਂ ਫ਼ੋਟੋ ਹਟਾਓ।', draft_limit: 'ਸਿਰਫ਼ 12 ਡਰਾਫ਼ਟ ਰੱਖੇ ਜਾਂਦੇ ਹਨ, ਇਸ ਲਈ ਸਭ ਤੋਂ ਪੁਰਾਣਾ ਡਰਾਫ਼ਟ ਹਟਾ ਦਿੱਤਾ ਗਿਆ।', draft_delete_q: 'ਇਹ ਡਰਾਫ਼ਟ ਮਿਟਾਉਣਾ ਹੈ?',
    help_title: 'ਕਿਵੇਂ ਵਰਤੀਏ / ਆਈਡੀਆ',
    tip1: 'ਮੌਕਾ ਚੁਣੋ, ਫਿਰ ਨਾਮ, ਤਾਰੀਖ਼, ਸਮਾਂ ਅਤੇ ਸਥਾਨ ਬਦਲੋ। ਟਾਈਪ ਕਰਦਿਆਂ ਹੀ ਕਾਰਡ ਬਦਲ ਜਾਂਦਾ ਹੈ।',
    tip2: 'ਭੇਜਣ ਲਈ "WhatsApp", ਸਟੇਟਸ ਅਤੇ Instagram ਲਈ "ਸਟੇਟਸ / ਸਟੋਰੀ", ਅਤੇ ਪ੍ਰਿੰਟਿੰਗ ਦੀ ਦੁਕਾਨ ਲਈ "A5 ਪ੍ਰਿੰਟ" ਚੁਣੋ। ਕੋਈ ਵੀ ਕਾਰਡ A4 ਸ਼ੀਟ ਤੇ 2 ਵੀ ਛਪ ਸਕਦਾ ਹੈ।',
    tip3: 'ਆਪਣਾ Google Maps ਲਿੰਕ ਪੇਸਟ ਕਰੋ: ਮਹਿਮਾਨ ਕਾਰਡ ਦਾ QR ਕੋਡ ਸਕੈਨ ਕਰਕੇ ਬਿਨਾਂ ਰਸਤਾ ਪੁੱਛੇ ਸਥਾਨ ਤੇ ਪਹੁੰਚ ਜਾਣਗੇ।',
    tip4: 'ਇੱਕੋ ਕਾਰਡ ਦੋ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਬਣਾਓ: ਡਰਾਫ਼ਟ ਸੇਵ ਕਰੋ, ਕਾਰਡ ਦੀ ਭਾਸ਼ਾ ਬਦਲੋ ਅਤੇ ਫਿਰ ਡਾਊਨਲੋਡ ਕਰੋ। ਰਿਸ਼ਤੇਦਾਰਾਂ ਲਈ ਪੰਜਾਬੀ, ਸਹਿਕਰਮੀਆਂ ਲਈ ਅੰਗਰੇਜ਼ੀ।',
    tip5: 'ਵਿਆਹ ਲਈ ਮਹਿੰਦੀ, ਸੰਗੀਤ ਅਤੇ ਬਰਾਤ ਦਾ ਸਮਾਂ "ਪ੍ਰੋਗਰਾਮ" ਵਿੱਚ ਲਿਖੋ, ਜਾਂ ਹਰ ਰਸਮ ਲਈ ਵੱਖਰਾ ਡਰਾਫ਼ਟ ਸੇਵ ਕਰੋ।',
    tip6: 'ਤੁਹਾਡੇ ਨਾਮ, ਫ਼ੋਟੋ ਅਤੇ ਜਾਣਕਾਰੀ ਇਸੇ ਫ਼ੋਨ ਜਾਂ ਕੰਪਿਊਟਰ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ। ਕੁਝ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ, ਇਸ ਲਈ ਐਪ ਬਿਨਾਂ ਇੰਟਰਨੈੱਟ ਵੀ ਚੱਲਦੀ ਹੈ।'
  },
  or: {
    app_title: 'ନିମନ୍ତ୍ରଣ କାର୍ଡ ମେକର',
    intro: 'ବିବାହ, ନିର୍ବନ୍ଧ, ଜନ୍ମଦିନ, ଗୃହପ୍ରବେଶ, ପୂଜା, ସ୍କୁଲ ଉତ୍ସବ ଓ ଦୋକାନ ଉଦ୍‌ଘାଟନର ସୁନ୍ଦର ନିମନ୍ତ୍ରଣ କାର୍ଡ ନିଜ ଭାଷାରେ ତିଆରି କରନ୍ତୁ, WhatsApp ବା ପ୍ରିଣ୍ଟ ପାଇଁ ପ୍ରସ୍ତୁତ।',
    privacy: 'ଆପଣଙ୍କ ନାମ, ଫଟୋ ଓ ତଥ୍ୟ ଏହି ଡିଭାଇସରେ ହିଁ ରହେ। କିଛି ଅପଲୋଡ୍ ହୁଏ ନାହିଁ।',
    occ_title: 'ଅବସର',
    size_title: 'ଆକାର', size_wa: 'WhatsApp', size_story: 'ଷ୍ଟାଟସ୍ / ଷ୍ଟୋରି', size_square: 'ବର୍ଗାକାର', size_a5: 'A5 ପ୍ରିଣ୍ଟ',
    preview_aria: 'ନିମନ୍ତ୍ରଣ କାର୍ଡର ପ୍ରିଭ୍ୟୁ। କାର୍ଡର କୌଣସି ଧାଡ଼ିରେ କ୍ଲିକ୍ କରି ତାହା ବଦଳାନ୍ତୁ।', making: 'କାର୍ଡ ତିଆରି ହେଉଛି…',
    share_btn: 'WhatsApp ରେ ପଠାନ୍ତୁ', dl_png: 'PNG ଡାଉନଲୋଡ୍ କରନ୍ତୁ', copy_text: 'ନିମନ୍ତ୍ରଣ ଲେଖା କପି କରନ୍ତୁ', print_a5: 'A5 ପ୍ରିଣ୍ଟ କରନ୍ତୁ', print_2up: 'A4 ରେ 2ଟି ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    print_hint: '"A5 ପ୍ରିଣ୍ଟ" ରେ ପ୍ରତି ପୃଷ୍ଠାରେ ଗୋଟିଏ କାର୍ଡ ଛପେ। "A4 ରେ 2ଟି" ରେ ଗୋଟିଏ A4 ସିଟ୍‌ରେ ଦୁଇଟି କାର୍ଡ ପାଖାପାଖି ଛପେ; ମଝିରୁ କାଟନ୍ତୁ।',
    shortcut: 'ସର୍ଟକଟ୍: Ctrl + S ରେ PNG ଡାଉନଲୋଡ୍, Ctrl + P ରେ ପ୍ରିଣ୍ଟ।',
    share_none: 'ଏହି ବ୍ରାଉଜର ସିଧାସଳଖ ଛବି ପଠାଇ ପାରିବ ନାହିଁ, ତେଣୁ କାର୍ଡ ଡାଉନଲୋଡ୍ ହେଲା। ଏହାକୁ ଗ୍ୟାଲେରି ବା Downloads ରୁ ପଠାନ୍ତୁ।',
    saved_file: '{name} ସେଭ୍ ହେଲା', copied_text: 'ନିମନ୍ତ୍ରଣ ଲେଖା କପି ହେଲା। କାର୍ଡ ସହ WhatsApp ରେ ପେଷ୍ଟ କରନ୍ତୁ।',
    text_title: 'ଲେଖା', card_lang: 'କାର୍ଡର ଭାଷା', example_note: 'ଏହା ଏକ ଉଦାହରଣ ନିମନ୍ତ୍ରଣ। ନାମ ଓ ତଥ୍ୟ ନିଜର ଲେଖନ୍ତୁ।', example_clear: 'ଉଦାହରଣ ହଟାନ୍ତୁ',
    heading_label: 'ଶୀର୍ଷକ', invite_label: 'ନିମନ୍ତ୍ରଣ ଧାଡ଼ି', n1_label: 'ନାମ 1 (ବ୍ୟକ୍ତି, ଯୁଗଳ, ପରିବାର, ସ୍କୁଲ ବା ଦୋକାନ)', join_label: 'ନାମ ମଝିର ଶବ୍ଦ', n2_label: 'ନାମ 2 (ଐଚ୍ଛିକ)',
    sub_label: 'ନାମ ତଳ ଧାଡ଼ି (ପିତାମାତା, ବୟସ, ଅବସର)', closing_label: 'ଶେଷ ଧାଡ଼ି', family_label: 'ତରଫରୁ (ପରିବାର / ଆୟୋଜକ)', text_reset: 'ପ୍ରସ୍ତାବିତ ଲେଖା ବ୍ୟବହାର କରନ୍ତୁ',
    details_title: 'ତାରିଖ, ସମୟ ଓ ସ୍ଥାନ', date_label: 'ତାରିଖ', time_label: 'ସମୟ', venue_label: 'ସ୍ଥାନ (ନାମ ଓ ଠିକଣା)',
    map_label: 'Google Maps ଲିଙ୍କ (ଐଚ୍ଛିକ, QR କୋଡ୍ ଭାବେ ଛପିବ)', map_bad: 'https:// ରୁ ଆରମ୍ଭ ହେଉଥିବା ପୂରା ଲିଙ୍କ ପେଷ୍ଟ କରନ୍ତୁ', map_ok: 'ଅତିଥିମାନେ କାର୍ଡର QR କୋଡ୍ ସ୍କାନ୍ କରି ମ୍ୟାପ୍ ଖୋଲିପାରିବେ।',
    schedule_label: 'କାର୍ଯ୍ୟକ୍ରମ (ଐଚ୍ଛିକ, ପ୍ରତି ଧାଡ଼ିରେ ଗୋଟିଏ ଉତ୍ସବ)', rsvp_label: 'RSVP ଫୋନ୍ ନମ୍ବର',
    design_title: 'ଡିଜାଇନ୍', colours: 'ରଙ୍ଗ', colour_n: 'ରଙ୍ଗ ସେଟ୍ {n}',
    design_royal: 'ରାଜକୀୟ କଲ୍କା', design_toran: 'ଗେଣ୍ଡୁ ତୋରଣ', design_kalash: 'କଳସ', design_lotus: 'ପଦ୍ମ', design_peacock: 'ମୟୂର ପର', design_diya: 'ଦୀପ ଓ ଆଲୋକ', design_jaali: 'ଜାଲି ଖିଲାଣ',
    design_floral: 'ଗୋଲାପ', design_mandala: 'ମଣ୍ଡଳ', design_balloons: 'ବେଲୁନ୍', design_banana: 'କଦଳୀ ପତ୍ର', design_minimal: 'ସରଳ', design_ribbon: 'ରିବନ୍', design_hearts: 'ମୁଦି ଓ ହୃଦୟ',
    font_label: 'ଅକ୍ଷର ଶୈଳୀ', font_elegant: 'ସୁନ୍ଦର', font_festive: 'ଉତ୍ସବୀ', font_simple: 'ସରଳ',
    font_note: 'ସୁନ୍ଦର ଓ ଉତ୍ସବୀ ଅକ୍ଷର ଥରେ ଇଣ୍ଟରନେଟରୁ ଡାଉନଲୋଡ୍ ହୁଏ। ଇଣ୍ଟରନେଟ ନଥିଲେ ଡିଭାଇସର ଫଣ୍ଟ ବ୍ୟବହୃତ ହୁଏ।',
    sym_title: 'ଉପରେ ପବିତ୍ର ଚିହ୍ନ', sym_none: 'କିଛି ନାହିଁ', sym_ganesh: 'ଶ୍ରୀ ଗଣେଶ', sym_om: 'ଓଁ', sym_ikonkar: 'ଇକ ଓଙ୍କାର', sym_bismillah: 'ବିସମିଲ୍ଲାହ', sym_cross: 'କ୍ରସ୍', sym_buddha: 'ଧର୍ମଚକ୍ର',
    photo_title: 'ଫଟୋ (ଐଚ୍ଛିକ)', photo_add: 'ଫଟୋ ଯୋଡ଼ନ୍ତୁ', photo_remove: 'ହଟାନ୍ତୁ', photo_shape: 'ଆକୃତି', shape_circle: 'ଗୋଲ', shape_arch: 'ଖିଲାଣ', shape_round: 'ଗୋଲ କୋଣ', photo_zoom: 'ଜୁମ୍',
    photo_hint: 'ଫଟୋ ଘୁଞ୍ଚାଇବାକୁ କାର୍ଡ ଉପରେ ତାହାକୁ ଟାଣନ୍ତୁ।', img_bad: 'ଏହି ଫାଇଲ୍ ଖୋଲି ହେଲା ନାହିଁ। ଦୟାକରି JPG ବା PNG ଛବି ବାଛନ୍ତୁ।',
    img_unsaved: 'ଫଟୋ ଏତେ ବଡ଼ ଯେ ପୃଷ୍ଠା ବନ୍ଦ କଲେ ମନେ ରହିବ ନାହିଁ, କିନ୍ତୁ ଏବେ ବ୍ୟବହାର କରିପାରିବେ।',
    drafts_title: 'ଡ୍ରାଫ୍ଟ', drafts_help: 'କାର୍ଡ ସେଭ୍ କରି ପରେ ପୁଣି ଖୋଲନ୍ତୁ, ଯେପରି ପ୍ରତି ଉତ୍ସବ ବା ଭାଷା ପାଇଁ ଗୋଟିଏ କାର୍ଡ।',
    draft_name_ph: 'ଡ୍ରାଫ୍ଟ ନାମ, ଯେପରି ପ୍ରିୟାଙ୍କ ବିବାହ', draft_save: 'ଡ୍ରାଫ୍ଟ ସେଭ୍ କରନ୍ତୁ', draft_saved: 'ଡ୍ରାଫ୍ଟ ଏହି ଡିଭାଇସରେ ସେଭ୍ ହେଲା।', draft_open: 'ଖୋଲନ୍ତୁ', draft_opened: 'ଡ୍ରାଫ୍ଟ ଖୋଲିଲା।', drafts_none: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଡ୍ରାଫ୍ଟ ସେଭ୍ ହୋଇନାହିଁ।',
    draft_full: 'ଏହି ଡ୍ରାଫ୍ଟ ପାଇଁ ସ୍ଥାନ ନାହିଁ। ପୁରୁଣା ଡ୍ରାଫ୍ଟ ହଟାନ୍ତୁ ବା ଫଟୋ ହଟାନ୍ତୁ।', draft_limit: 'କେବଳ 12ଟି ଡ୍ରାଫ୍ଟ ରଖାଯାଏ, ତେଣୁ ସବୁଠାରୁ ପୁରୁଣା ଡ୍ରାଫ୍ଟ ହଟାଇ ଦିଆଗଲା।', draft_delete_q: 'ଏହି ଡ୍ରାଫ୍ଟ ହଟାଇବେ?',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ଆଇଡିଆ',
    tip1: 'ଅବସର ବାଛନ୍ତୁ, ତାପରେ ନାମ, ତାରିଖ, ସମୟ ଓ ସ୍ଥାନ ବଦଳାନ୍ତୁ। ଟାଇପ୍ କରୁ କରୁ କାର୍ଡ ବଦଳିଯାଏ।',
    tip2: 'ପଠାଇବା ପାଇଁ "WhatsApp", ଷ୍ଟାଟସ୍ ଓ Instagram ପାଇଁ "ଷ୍ଟାଟସ୍ / ଷ୍ଟୋରି", ଓ ପ୍ରିଣ୍ଟିଂ ଦୋକାନ ପାଇଁ "A5 ପ୍ରିଣ୍ଟ" ବାଛନ୍ତୁ। ଯେକୌଣସି କାର୍ଡ A4 ସିଟ୍‌ରେ 2ଟି ମଧ୍ୟ ଛପାଯାଇପାରିବ।',
    tip3: 'ନିଜ Google Maps ଲିଙ୍କ ପେଷ୍ଟ କରନ୍ତୁ: ଅତିଥିମାନେ କାର୍ଡର QR କୋଡ୍ ସ୍କାନ୍ କରି ରାସ୍ତା ନ ପଚାରି ସ୍ଥାନରେ ପହଞ୍ଚିଯିବେ।',
    tip4: 'ସମାନ କାର୍ଡ ଦୁଇ ଭାଷାରେ ତିଆରି କରନ୍ତୁ: ଡ୍ରାଫ୍ଟ ସେଭ୍ କରନ୍ତୁ, କାର୍ଡର ଭାଷା ବଦଳାନ୍ତୁ ଓ ପୁଣି ଡାଉନଲୋଡ୍ କରନ୍ତୁ। ସମ୍ପର୍କୀୟଙ୍କ ପାଇଁ ଓଡ଼ିଆ, ସହକର୍ମୀଙ୍କ ପାଇଁ ଇଂରାଜୀ।',
    tip5: 'ବିବାହ ପାଇଁ ମେହେନ୍ଦି, ସଂଗୀତ ଓ ବରଯାତ୍ରୀର ସମୟ "କାର୍ଯ୍ୟକ୍ରମ" ରେ ଲେଖନ୍ତୁ, ବା ପ୍ରତି ଉତ୍ସବ ପାଇଁ ଅଲଗା ଡ୍ରାଫ୍ଟ ସେଭ୍ କରନ୍ତୁ।',
    tip6: 'ଆପଣଙ୍କ ନାମ, ଫଟୋ ଓ ତଥ୍ୟ ଏହି ଫୋନ୍ ବା କମ୍ପ୍ୟୁଟରରେ ହିଁ ରହେ। କିଛି ଅପଲୋଡ୍ ହୁଏ ନାହିଁ, ତେଣୁ ଆପ୍ ଇଣ୍ଟରନେଟ ବିନା ମଧ୍ୟ ଚାଲେ।'
  },
  ta: {
    app_title: 'அழைப்பிதழ் மேக்கர்',
    intro: 'திருமணம், நிச்சயதார்த்தம், பிறந்தநாள், கிரகப்பிரவேசம், பூஜை, பள்ளி விழா, கடை திறப்பு ஆகியவற்றுக்கு அழகான அழைப்பிதழ்களை உங்கள் மொழியில் உருவாக்குங்கள்; WhatsApp அல்லது அச்சுக்கு தயார்.',
    privacy: 'உங்கள் பெயர்கள், புகைப்படம், விவரங்கள் இந்த சாதனத்திலேயே இருக்கும். எதுவும் பதிவேற்றப்படாது.',
    occ_title: 'நிகழ்வு',
    size_title: 'அளவு', size_wa: 'WhatsApp', size_story: 'ஸ்டேட்டஸ் / ஸ்டோரி', size_square: 'சதுரம்', size_a5: 'A5 அச்சு',
    preview_aria: 'அழைப்பிதழ் முன்னோட்டம். அட்டையில் ஒரு வரியைக் கிளிக் செய்து மாற்றலாம்.', making: 'அட்டை உருவாகிறது…',
    share_btn: 'WhatsApp-இல் அனுப்பு', dl_png: 'PNG பதிவிறக்கு', copy_text: 'அழைப்பு உரையை நகலெடு', print_a5: 'A5 அச்சிடு', print_2up: 'A4-இல் 2 அச்சிடு',
    print_hint: '"A5 அச்சிடு" ஒரு பக்கத்திற்கு ஒரு அட்டை அச்சிடும். "A4-இல் 2" ஒரு A4 தாளில் இரண்டு அட்டைகளை அருகருகே அச்சிடும்; நடுவில் வெட்டவும்.',
    shortcut: 'குறுக்குவழி: Ctrl + S என்றால் PNG பதிவிறக்கம், Ctrl + P என்றால் அச்சு.',
    share_none: 'இந்த உலாவி படத்தை நேரடியாக அனுப்ப முடியாது, எனவே அட்டை பதிவிறக்கப்பட்டது. கேலரி அல்லது Downloads-இலிருந்து அனுப்புங்கள்.',
    saved_file: '{name} சேமிக்கப்பட்டது', copied_text: 'அழைப்பு உரை நகலெடுக்கப்பட்டது. அட்டையுடன் WhatsApp-இல் ஒட்டுங்கள்.',
    text_title: 'வாசகம்', card_lang: 'அட்டையின் மொழி', example_note: 'இது ஒரு மாதிரி அழைப்பிதழ். பெயர்களையும் விவரங்களையும் உங்களுடையதாக மாற்றுங்கள்.', example_clear: 'மாதிரியை நீக்கு',
    heading_label: 'தலைப்பு', invite_label: 'அழைப்பு வரி', n1_label: 'பெயர் 1 (நபர், தம்பதி, குடும்பம், பள்ளி அல்லது கடை)', join_label: 'பெயர்களுக்கு இடையிலான சொல்', n2_label: 'பெயர் 2 (விருப்பத்திற்கு)',
    sub_label: 'பெயர்களுக்குக் கீழ் வரி (பெற்றோர், வயது, நிகழ்வு)', closing_label: 'முடிவு வரி', family_label: 'அனுப்புநர் (குடும்பம் / விருந்தினர்)', text_reset: 'பரிந்துரைத்த வாசகத்தைப் பயன்படுத்து',
    details_title: 'தேதி, நேரம், இடம்', date_label: 'தேதி', time_label: 'நேரம்', venue_label: 'இடம் (பெயர் மற்றும் முகவரி)',
    map_label: 'Google Maps இணைப்பு (விருப்பத்திற்கு, QR குறியீடாக அச்சிடப்படும்)', map_bad: 'https:// எனத் தொடங்கும் முழு இணைப்பை ஒட்டவும்', map_ok: 'விருந்தினர்கள் அட்டையிலுள்ள QR குறியீட்டை ஸ்கேன் செய்து வரைபடத்தைத் திறக்கலாம்.',
    schedule_label: 'நிகழ்ச்சி நிரல் (விருப்பத்திற்கு, ஒரு வரிக்கு ஒரு நிகழ்ச்சி)', rsvp_label: 'RSVP தொலைபேசி எண்',
    design_title: 'வடிவமைப்பு', colours: 'நிறங்கள்', colour_n: 'நிறத் தொகுப்பு {n}',
    design_royal: 'அரச மாங்காய்', design_toran: 'சாமந்தி தோரணம்', design_kalash: 'கலசம்', design_lotus: 'தாமரை', design_peacock: 'மயில் இறகு', design_diya: 'விளக்கு ஒளி', design_jaali: 'ஜாலி வளைவு',
    design_floral: 'ரோஜா', design_mandala: 'மண்டலம்', design_balloons: 'பலூன்கள்', design_banana: 'வாழை இலை', design_minimal: 'எளிமை', design_ribbon: 'ரிப்பன்', design_hearts: 'மோதிரங்கள் & இதயம்',
    font_label: 'எழுத்து வடிவம்', font_elegant: 'அழகிய', font_festive: 'விழா', font_simple: 'எளிய',
    font_note: 'அழகிய மற்றும் விழா எழுத்துருக்கள் ஒருமுறை இணையத்திலிருந்து பதிவிறக்கமாகும். இணையம் இல்லையெனில் சாதன எழுத்துரு பயன்படும்.',
    sym_title: 'மேலே புனித சின்னம்', sym_none: 'இல்லை', sym_ganesh: 'ஸ்ரீ கணேஷ்', sym_om: 'ஓம்', sym_ikonkar: 'இக் ஓங்கார்', sym_bismillah: 'பிஸ்மில்லாஹ்', sym_cross: 'சிலுவை', sym_buddha: 'தர்ம சக்கரம்',
    photo_title: 'புகைப்படம் (விருப்பத்திற்கு)', photo_add: 'புகைப்படம் சேர்', photo_remove: 'நீக்கு', photo_shape: 'வடிவம்', shape_circle: 'வட்டம்', shape_arch: 'வளைவு', shape_round: 'வட்ட மூலைகள்', photo_zoom: 'ஸூம்',
    photo_hint: 'புகைப்படத்தை நகர்த்த அட்டையில் அதை இழுக்கவும்.', img_bad: 'இந்தக் கோப்பைத் திறக்க முடியவில்லை. JPG அல்லது PNG படத்தைத் தேர்ந்தெடுக்கவும்.',
    img_unsaved: 'புகைப்படம் மிகப் பெரியது, பக்கத்தை மூடிய பின் நினைவில் இருக்காது; ஆனால் இப்போது பயன்படுத்தலாம்.',
    drafts_title: 'வரைவுகள்', drafts_help: 'அட்டையைச் சேமித்து பின்னர் மீண்டும் திறக்கலாம்; எடுத்துக்காட்டாக ஒவ்வொரு நிகழ்ச்சிக்கும் அல்லது மொழிக்கும் ஒரு அட்டை.',
    draft_name_ph: 'வரைவின் பெயர், எ.கா. பிரியா திருமணம்', draft_save: 'வரைவைச் சேமி', draft_saved: 'வரைவு இந்த சாதனத்தில் சேமிக்கப்பட்டது.', draft_open: 'திற', draft_opened: 'வரைவு திறக்கப்பட்டது.', drafts_none: 'இன்னும் வரைவுகள் சேமிக்கப்படவில்லை.',
    draft_full: 'இந்த வரைவைச் சேமிக்க இடம் போதவில்லை. பழைய வரைவை நீக்கவும் அல்லது புகைப்படத்தை நீக்கவும்.', draft_limit: '12 வரைவுகள் மட்டுமே வைக்கப்படும், எனவே மிகப் பழைய வரைவு நீக்கப்பட்டது.', draft_delete_q: 'இந்த வரைவை நீக்கவா?',
    help_title: 'பயன்படுத்துவது எப்படி / யோசனைகள்',
    tip1: 'நிகழ்வைத் தேர்ந்தெடுத்து, பெயர்கள், தேதி, நேரம், இடத்தை மாற்றுங்கள். தட்டச்சு செய்யும்போதே அட்டை மாறும்.',
    tip2: 'அனுப்ப "WhatsApp", ஸ்டேட்டஸ் மற்றும் Instagram-க்கு "ஸ்டேட்டஸ் / ஸ்டோரி", அச்சகத்திற்கு "A5 அச்சு" தேர்ந்தெடுங்கள். எந்த அட்டையையும் A4 தாளில் 2 ஆகவும் அச்சிடலாம்.',
    tip3: 'உங்கள் Google Maps இணைப்பை ஒட்டுங்கள்: விருந்தினர்கள் அட்டையின் QR குறியீட்டை ஸ்கேன் செய்து வழி கேட்காமல் இடத்தை அடைவார்கள்.',
    tip4: 'ஒரே அட்டையை இரு மொழிகளில் உருவாக்குங்கள்: வரைவைச் சேமித்து, அட்டையின் மொழியை மாற்றி, மீண்டும் பதிவிறக்குங்கள். உறவினர்களுக்குத் தமிழ், சக ஊழியர்களுக்கு ஆங்கிலம்.',
    tip5: 'திருமணத்திற்கு மருதாணி, சங்கீத், முகூர்த்த நேரங்களை "நிகழ்ச்சி நிரல்"-இல் சேர்க்கவும், அல்லது ஒவ்வொரு நிகழ்ச்சிக்கும் தனி வரைவு சேமிக்கவும்.',
    tip6: 'உங்கள் பெயர்கள், புகைப்படம், விவரங்கள் இந்தத் தொலைபேசி அல்லது கணினியிலேயே இருக்கும். எதுவும் பதிவேற்றப்படாது, எனவே இணையம் இல்லாமலும் செயலி வேலை செய்யும்.'
  },
  te: {
    app_title: 'ఆహ్వాన పత్రిక మేకర్',
    intro: 'పెళ్లి, నిశ్చితార్థం, పుట్టినరోజు, గృహప్రవేశం, పూజ, స్కూల్ వేడుకలు, షాప్ ప్రారంభోత్సవాలకు అందమైన ఆహ్వాన పత్రికలను మీ భాషలో తయారు చేయండి; WhatsApp లేదా ప్రింట్ కోసం సిద్ధం.',
    privacy: 'మీ పేర్లు, ఫోటో, వివరాలు ఈ పరికరంలోనే ఉంటాయి. ఏదీ అప్‌లోడ్ కాదు.',
    occ_title: 'సందర్భం',
    size_title: 'సైజు', size_wa: 'WhatsApp', size_story: 'స్టేటస్ / స్టోరీ', size_square: 'చతురస్రం', size_a5: 'A5 ప్రింట్',
    preview_aria: 'ఆహ్వాన పత్రిక ప్రివ్యూ. కార్డుపై ఏదైనా లైన్‌ను క్లిక్ చేసి మార్చవచ్చు.', making: 'కార్డు తయారవుతోంది…',
    share_btn: 'WhatsApp లో పంపండి', dl_png: 'PNG డౌన్‌లోడ్', copy_text: 'ఆహ్వాన టెక్స్ట్ కాపీ చేయండి', print_a5: 'A5 ప్రింట్', print_2up: 'A4 పై 2 ప్రింట్',
    print_hint: '"A5 ప్రింట్" ప్రతి పేజీకి ఒక కార్డు ప్రింట్ చేస్తుంది. "A4 పై 2" ఒక A4 షీట్‌పై రెండు కార్డులను పక్కపక్కనే ప్రింట్ చేస్తుంది; మధ్యలో కత్తిరించండి.',
    shortcut: 'షార్ట్‌కట్: Ctrl + S తో PNG డౌన్‌లోడ్, Ctrl + P తో ప్రింట్.',
    share_none: 'ఈ బ్రౌజర్ నేరుగా చిత్రాన్ని పంపలేదు, కాబట్టి కార్డు డౌన్‌లోడ్ అయింది. గ్యాలరీ లేదా Downloads నుండి పంపండి.',
    saved_file: '{name} సేవ్ అయింది', copied_text: 'ఆహ్వాన టెక్స్ట్ కాపీ అయింది. కార్డుతో పాటు WhatsApp లో పేస్ట్ చేయండి.',
    text_title: 'పదాలు', card_lang: 'కార్డు భాష', example_note: 'ఇది ఒక ఉదాహరణ ఆహ్వానం. పేర్లు, వివరాలను మీవిగా మార్చండి.', example_clear: 'ఉదాహరణ తొలగించు',
    heading_label: 'శీర్షిక', invite_label: 'ఆహ్వాన వాక్యం', n1_label: 'పేరు 1 (వ్యక్తి, జంట, కుటుంబం, స్కూల్ లేదా షాప్)', join_label: 'పేర్ల మధ్య పదం', n2_label: 'పేరు 2 (ఐచ్ఛికం)',
    sub_label: 'పేర్ల కింది లైన్ (తల్లిదండ్రులు, వయస్సు, సందర్భం)', closing_label: 'ముగింపు వాక్యం', family_label: 'ఇట్లు (కుటుంబం / ఆతిథ్యం)', text_reset: 'సూచించిన పదాలు వాడండి',
    details_title: 'తేదీ, సమయం, వేదిక', date_label: 'తేదీ', time_label: 'సమయం', venue_label: 'వేదిక (పేరు, చిరునామా)',
    map_label: 'Google Maps లింక్ (ఐచ్ఛికం, QR కోడ్‌గా ప్రింట్ అవుతుంది)', map_bad: 'https:// తో మొదలయ్యే పూర్తి లింక్ పేస్ట్ చేయండి', map_ok: 'అతిథులు కార్డుపై QR కోడ్ స్కాన్ చేసి మ్యాప్ తెరవవచ్చు.',
    schedule_label: 'కార్యక్రమం (ఐచ్ఛికం, ఒక్కో లైన్‌కు ఒక వేడుక)', rsvp_label: 'RSVP ఫోన్ నంబర్',
    design_title: 'డిజైన్', colours: 'రంగులు', colour_n: 'రంగుల సెట్ {n}',
    design_royal: 'రాజసపు మామిడిపిందె', design_toran: 'బంతిపూల తోరణం', design_kalash: 'కలశం', design_lotus: 'కమలం', design_peacock: 'నెమలి పింఛం', design_diya: 'దీపాల వెలుగు', design_jaali: 'జాలీ ఆర్చ్',
    design_floral: 'గులాబీలు', design_mandala: 'మండలం', design_balloons: 'బెలూన్లు', design_banana: 'అరటి ఆకు', design_minimal: 'సరళం', design_ribbon: 'రిబ్బన్', design_hearts: 'ఉంగరాలు & హృదయాలు',
    font_label: 'అక్షర శైలి', font_elegant: 'అందమైన', font_festive: 'పండుగ', font_simple: 'సాధారణ',
    font_note: 'అందమైన, పండుగ అక్షరాలు ఒకసారి ఇంటర్నెట్ నుండి డౌన్‌లోడ్ అవుతాయి. ఇంటర్నెట్ లేకపోతే పరికరం ఫాంట్ వాడబడుతుంది.',
    sym_title: 'పైన పవిత్ర చిహ్నం', sym_none: 'ఏదీ లేదు', sym_ganesh: 'శ్రీ గణేశ్', sym_om: 'ఓం', sym_ikonkar: 'ఇక్ ఓంకార్', sym_bismillah: 'బిస్మిల్లాహ్', sym_cross: 'శిలువ', sym_buddha: 'ధర్మ చక్రం',
    photo_title: 'ఫోటో (ఐచ్ఛికం)', photo_add: 'ఫోటో జోడించు', photo_remove: 'తొలగించు', photo_shape: 'ఆకారం', shape_circle: 'వృత్తం', shape_arch: 'ఆర్చ్', shape_round: 'గుండ్రని మూలలు', photo_zoom: 'జూమ్',
    photo_hint: 'ఫోటోను కదపడానికి కార్డుపై దాన్ని లాగండి.', img_bad: 'ఈ ఫైల్ తెరవలేకపోయాం. దయచేసి JPG లేదా PNG చిత్రాన్ని ఎంచుకోండి.',
    img_unsaved: 'ఫోటో చాలా పెద్దది, పేజీ మూసిన తర్వాత గుర్తుండదు; కానీ ఇప్పుడు వాడుకోవచ్చు.',
    drafts_title: 'డ్రాఫ్ట్‌లు', drafts_help: 'కార్డును సేవ్ చేసి తర్వాత మళ్లీ తెరవండి; ఉదాహరణకు ఒక్కో వేడుకకు లేదా భాషకు ఒక కార్డు.',
    draft_name_ph: 'డ్రాఫ్ట్ పేరు, ఉదా. ప్రియ పెళ్లి', draft_save: 'డ్రాఫ్ట్ సేవ్ చేయండి', draft_saved: 'డ్రాఫ్ట్ ఈ పరికరంలో సేవ్ అయింది.', draft_open: 'తెరువు', draft_opened: 'డ్రాఫ్ట్ తెరవబడింది.', drafts_none: 'ఇంకా డ్రాఫ్ట్‌లు సేవ్ కాలేదు.',
    draft_full: 'ఈ డ్రాఫ్ట్ సేవ్ చేయడానికి స్థలం లేదు. పాత డ్రాఫ్ట్‌ను తొలగించండి లేదా ఫోటో తీసేయండి.', draft_limit: '12 డ్రాఫ్ట్‌లు మాత్రమే ఉంచబడతాయి, కాబట్టి అత్యంత పాత డ్రాఫ్ట్ తొలగించబడింది.', draft_delete_q: 'ఈ డ్రాఫ్ట్‌ను తొలగించాలా?',
    help_title: 'ఎలా వాడాలి / ఆలోచనలు',
    tip1: 'సందర్భం ఎంచుకుని, పేర్లు, తేదీ, సమయం, వేదిక మార్చండి. టైప్ చేస్తుండగానే కార్డు మారుతుంది.',
    tip2: 'పంపడానికి "WhatsApp", స్టేటస్ మరియు Instagram కోసం "స్టేటస్ / స్టోరీ", ప్రింటింగ్ షాప్ కోసం "A5 ప్రింట్" ఎంచుకోండి. ఏ కార్డునైనా A4 షీట్‌పై 2గా కూడా ప్రింట్ చేయవచ్చు.',
    tip3: 'మీ Google Maps లింక్ పేస్ట్ చేయండి: అతిథులు కార్డుపై QR కోడ్ స్కాన్ చేసి దారి అడగకుండానే వేదికకు చేరుకుంటారు.',
    tip4: 'అదే కార్డును రెండు భాషల్లో చేయండి: డ్రాఫ్ట్ సేవ్ చేసి, కార్డు భాష మార్చి, మళ్లీ డౌన్‌లోడ్ చేయండి. బంధువులకు తెలుగు, సహోద్యోగులకు ఇంగ్లీష్.',
    tip5: 'పెళ్లికి మెహందీ, సంగీత్, ముహూర్త సమయాలను "కార్యక్రమం"లో రాయండి, లేదా ఒక్కో వేడుకకు వేరే డ్రాఫ్ట్ సేవ్ చేయండి.',
    tip6: 'మీ పేర్లు, ఫోటో, వివరాలు ఈ ఫోన్ లేదా కంప్యూటర్‌లోనే ఉంటాయి. ఏదీ అప్‌లోడ్ కాదు, కాబట్టి యాప్ ఇంటర్నెట్ లేకుండా కూడా పనిచేస్తుంది.'
  },
  kn: {
    app_title: 'ಆಮಂತ್ರಣ ಪತ್ರ ಮೇಕರ್',
    intro: 'ಮದುವೆ, ನಿಶ್ಚಿತಾರ್ಥ, ಹುಟ್ಟುಹಬ್ಬ, ಗೃಹಪ್ರವೇಶ, ಪೂಜೆ, ಶಾಲಾ ಕಾರ್ಯಕ್ರಮ ಮತ್ತು ಅಂಗಡಿ ಉದ್ಘಾಟನೆಗೆ ಸುಂದರ ಆಮಂತ್ರಣ ಪತ್ರಗಳನ್ನು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾಡಿ; WhatsApp ಅಥವಾ ಮುದ್ರಣಕ್ಕೆ ಸಿದ್ಧ.',
    privacy: 'ನಿಮ್ಮ ಹೆಸರು, ಫೋಟೋ ಮತ್ತು ವಿವರಗಳು ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತವೆ. ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ.',
    occ_title: 'ಸಂದರ್ಭ',
    size_title: 'ಗಾತ್ರ', size_wa: 'WhatsApp', size_story: 'ಸ್ಟೇಟಸ್ / ಸ್ಟೋರಿ', size_square: 'ಚೌಕ', size_a5: 'A5 ಮುದ್ರಣ',
    preview_aria: 'ಆಮಂತ್ರಣ ಪತ್ರದ ಪೂರ್ವವೀಕ್ಷಣೆ. ಕಾರ್ಡ್‌ನ ಯಾವುದೇ ಸಾಲನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ ಬದಲಾಯಿಸಿ.', making: 'ಕಾರ್ಡ್ ತಯಾರಾಗುತ್ತಿದೆ…',
    share_btn: 'WhatsApp ನಲ್ಲಿ ಕಳುಹಿಸಿ', dl_png: 'PNG ಡೌನ್‌ಲೋಡ್', copy_text: 'ಆಮಂತ್ರಣ ಪಠ್ಯ ನಕಲಿಸಿ', print_a5: 'A5 ಮುದ್ರಿಸಿ', print_2up: 'A4 ನಲ್ಲಿ 2 ಮುದ್ರಿಸಿ',
    print_hint: '"A5 ಮುದ್ರಿಸಿ" ಪ್ರತಿ ಪುಟಕ್ಕೆ ಒಂದು ಕಾರ್ಡ್ ಮುದ್ರಿಸುತ್ತದೆ. "A4 ನಲ್ಲಿ 2" ಒಂದು A4 ಹಾಳೆಯಲ್ಲಿ ಎರಡು ಕಾರ್ಡ್‌ಗಳನ್ನು ಅಕ್ಕಪಕ್ಕ ಮುದ್ರಿಸುತ್ತದೆ; ಮಧ್ಯದಲ್ಲಿ ಕತ್ತರಿಸಿ.',
    shortcut: 'ಶಾರ್ಟ್‌ಕಟ್: Ctrl + S ನಿಂದ PNG ಡೌನ್‌ಲೋಡ್, Ctrl + P ನಿಂದ ಮುದ್ರಣ.',
    share_none: 'ಈ ಬ್ರೌಸರ್ ನೇರವಾಗಿ ಚಿತ್ರ ಕಳುಹಿಸಲಾರದು, ಹಾಗಾಗಿ ಕಾರ್ಡ್ ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ. ಗ್ಯಾಲರಿ ಅಥವಾ Downloads ನಿಂದ ಕಳುಹಿಸಿ.',
    saved_file: '{name} ಉಳಿಸಲಾಗಿದೆ', copied_text: 'ಆಮಂತ್ರಣ ಪಠ್ಯ ನಕಲಾಗಿದೆ. ಕಾರ್ಡ್ ಜೊತೆಗೆ WhatsApp ನಲ್ಲಿ ಅಂಟಿಸಿ.',
    text_title: 'ಪದಗಳು', card_lang: 'ಕಾರ್ಡ್ ಭಾಷೆ', example_note: 'ಇದು ಮಾದರಿ ಆಮಂತ್ರಣ. ಹೆಸರು ಮತ್ತು ವಿವರಗಳನ್ನು ನಿಮ್ಮದಾಗಿ ಬದಲಾಯಿಸಿ.', example_clear: 'ಮಾದರಿ ತೆಗೆ',
    heading_label: 'ಶೀರ್ಷಿಕೆ', invite_label: 'ಆಮಂತ್ರಣ ಸಾಲು', n1_label: 'ಹೆಸರು 1 (ವ್ಯಕ್ತಿ, ಜೋಡಿ, ಕುಟುಂಬ, ಶಾಲೆ ಅಥವಾ ಅಂಗಡಿ)', join_label: 'ಹೆಸರುಗಳ ನಡುವಿನ ಪದ', n2_label: 'ಹೆಸರು 2 (ಐಚ್ಛಿಕ)',
    sub_label: 'ಹೆಸರುಗಳ ಕೆಳಗಿನ ಸಾಲು (ಪೋಷಕರು, ವಯಸ್ಸು, ಸಂದರ್ಭ)', closing_label: 'ಕೊನೆಯ ಸಾಲು', family_label: 'ಇಂತಿ (ಕುಟುಂಬ / ಆತಿಥೇಯರು)', text_reset: 'ಸೂಚಿಸಿದ ಪದಗಳನ್ನು ಬಳಸಿ',
    details_title: 'ದಿನಾಂಕ, ಸಮಯ ಮತ್ತು ಸ್ಥಳ', date_label: 'ದಿನಾಂಕ', time_label: 'ಸಮಯ', venue_label: 'ಸ್ಥಳ (ಹೆಸರು ಮತ್ತು ವಿಳಾಸ)',
    map_label: 'Google Maps ಲಿಂಕ್ (ಐಚ್ಛಿಕ, QR ಕೋಡ್ ಆಗಿ ಮುದ್ರಿತವಾಗುತ್ತದೆ)', map_bad: 'https:// ನಿಂದ ಆರಂಭವಾಗುವ ಪೂರ್ಣ ಲಿಂಕ್ ಅಂಟಿಸಿ', map_ok: 'ಅತಿಥಿಗಳು ಕಾರ್ಡ್‌ನ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ನಕ್ಷೆ ತೆರೆಯಬಹುದು.',
    schedule_label: 'ಕಾರ್ಯಕ್ರಮ (ಐಚ್ಛಿಕ, ಒಂದು ಸಾಲಿಗೆ ಒಂದು ಸಮಾರಂಭ)', rsvp_label: 'RSVP ಫೋನ್ ಸಂಖ್ಯೆ',
    design_title: 'ವಿನ್ಯಾಸ', colours: 'ಬಣ್ಣಗಳು', colour_n: 'ಬಣ್ಣದ ಸೆಟ್ {n}',
    design_royal: 'ರಾಜಮನೆತನದ ಮಾವಿನ ಚಿತ್ತಾರ', design_toran: 'ಚೆಂಡು ಹೂವಿನ ತೋರಣ', design_kalash: 'ಕಲಶ', design_lotus: 'ಕಮಲ', design_peacock: 'ನವಿಲು ಗರಿ', design_diya: 'ದೀಪದ ಬೆಳಕು', design_jaali: 'ಜಾಲಿ ಕಮಾನು',
    design_floral: 'ಗುಲಾಬಿ', design_mandala: 'ಮಂಡಲ', design_balloons: 'ಬಲೂನುಗಳು', design_banana: 'ಬಾಳೆ ಎಲೆ', design_minimal: 'ಸರಳ', design_ribbon: 'ರಿಬ್ಬನ್', design_hearts: 'ಉಂಗುರ ಮತ್ತು ಹೃದಯ',
    font_label: 'ಅಕ್ಷರ ಶೈಲಿ', font_elegant: 'ಸುಂದರ', font_festive: 'ಹಬ್ಬದ', font_simple: 'ಸರಳ',
    font_note: 'ಸುಂದರ ಮತ್ತು ಹಬ್ಬದ ಅಕ್ಷರಗಳು ಒಮ್ಮೆ ಇಂಟರ್ನೆಟ್‌ನಿಂದ ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತವೆ. ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದಿದ್ದರೆ ಸಾಧನದ ಫಾಂಟ್ ಬಳಕೆಯಾಗುತ್ತದೆ.',
    sym_title: 'ಮೇಲೆ ಪವಿತ್ರ ಚಿಹ್ನೆ', sym_none: 'ಯಾವುದೂ ಇಲ್ಲ', sym_ganesh: 'ಶ್ರೀ ಗಣೇಶ', sym_om: 'ಓಂ', sym_ikonkar: 'ಇಕ್ ಓಂಕಾರ್', sym_bismillah: 'ಬಿಸ್ಮಿಲ್ಲಾಹ್', sym_cross: 'ಶಿಲುಬೆ', sym_buddha: 'ಧರ್ಮ ಚಕ್ರ',
    photo_title: 'ಫೋಟೋ (ಐಚ್ಛಿಕ)', photo_add: 'ಫೋಟೋ ಸೇರಿಸಿ', photo_remove: 'ತೆಗೆ', photo_shape: 'ಆಕಾರ', shape_circle: 'ವೃತ್ತ', shape_arch: 'ಕಮಾನು', shape_round: 'ದುಂಡು ಮೂಲೆ', photo_zoom: 'ಝೂಮ್',
    photo_hint: 'ಫೋಟೋ ಸರಿಸಲು ಕಾರ್ಡ್ ಮೇಲೆ ಅದನ್ನು ಎಳೆಯಿರಿ.', img_bad: 'ಈ ಫೈಲ್ ತೆರೆಯಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು JPG ಅಥವಾ PNG ಚಿತ್ರ ಆರಿಸಿ.',
    img_unsaved: 'ಫೋಟೋ ತುಂಬಾ ದೊಡ್ಡದು, ಪುಟ ಮುಚ್ಚಿದ ಮೇಲೆ ನೆನಪಿರುವುದಿಲ್ಲ; ಆದರೆ ಈಗ ಬಳಸಬಹುದು.',
    drafts_title: 'ಕರಡುಗಳು', drafts_help: 'ಕಾರ್ಡ್ ಉಳಿಸಿ ನಂತರ ಮತ್ತೆ ತೆರೆಯಿರಿ; ಉದಾಹರಣೆಗೆ ಪ್ರತಿ ಸಮಾರಂಭಕ್ಕೆ ಅಥವಾ ಭಾಷೆಗೆ ಒಂದು ಕಾರ್ಡ್.',
    draft_name_ph: 'ಕರಡಿನ ಹೆಸರು, ಉದಾ. ಪ್ರಿಯಾ ಮದುವೆ', draft_save: 'ಕರಡು ಉಳಿಸಿ', draft_saved: 'ಕರಡು ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ.', draft_open: 'ತೆರೆ', draft_opened: 'ಕರಡು ತೆರೆಯಲಾಗಿದೆ.', drafts_none: 'ಇನ್ನೂ ಯಾವ ಕರಡೂ ಉಳಿಸಿಲ್ಲ.',
    draft_full: 'ಈ ಕರಡು ಉಳಿಸಲು ಜಾಗವಿಲ್ಲ. ಹಳೆಯ ಕರಡು ಅಳಿಸಿ ಅಥವಾ ಫೋಟೋ ತೆಗೆಯಿರಿ.', draft_limit: 'ಕೇವಲ 12 ಡ್ರಾಫ್ಟ್‌ಗಳನ್ನು ಇಡಲಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಅತ್ಯಂತ ಹಳೆಯ ಡ್ರಾಫ್ಟ್ ತೆಗೆದುಹಾಕಲಾಯಿತು.', draft_delete_q: 'ಈ ಕರಡನ್ನು ಅಳಿಸುವುದೇ?',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ / ಐಡಿಯಾಗಳು',
    tip1: 'ಸಂದರ್ಭ ಆರಿಸಿ, ನಂತರ ಹೆಸರು, ದಿನಾಂಕ, ಸಮಯ ಮತ್ತು ಸ್ಥಳ ಬದಲಾಯಿಸಿ. ಟೈಪ್ ಮಾಡುತ್ತಿದ್ದಂತೆ ಕಾರ್ಡ್ ಬದಲಾಗುತ್ತದೆ.',
    tip2: 'ಕಳುಹಿಸಲು "WhatsApp", ಸ್ಟೇಟಸ್ ಮತ್ತು Instagram ಗೆ "ಸ್ಟೇಟಸ್ / ಸ್ಟೋರಿ", ಮುದ್ರಣ ಅಂಗಡಿಗೆ "A5 ಮುದ್ರಣ" ಆರಿಸಿ. ಯಾವುದೇ ಕಾರ್ಡನ್ನು A4 ಹಾಳೆಯಲ್ಲಿ 2 ಆಗಿಯೂ ಮುದ್ರಿಸಬಹುದು.',
    tip3: 'ನಿಮ್ಮ Google Maps ಲಿಂಕ್ ಅಂಟಿಸಿ: ಅತಿಥಿಗಳು ಕಾರ್ಡ್‌ನ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ದಾರಿ ಕೇಳದೆ ಸ್ಥಳ ತಲುಪುತ್ತಾರೆ.',
    tip4: 'ಅದೇ ಕಾರ್ಡನ್ನು ಎರಡು ಭಾಷೆಯಲ್ಲಿ ಮಾಡಿ: ಕರಡು ಉಳಿಸಿ, ಕಾರ್ಡ್ ಭಾಷೆ ಬದಲಾಯಿಸಿ, ಮತ್ತೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ. ಬಂಧುಗಳಿಗೆ ಕನ್ನಡ, ಸಹೋದ್ಯೋಗಿಗಳಿಗೆ ಇಂಗ್ಲಿಷ್.',
    tip5: 'ಮದುವೆಗೆ ಮೆಹೆಂದಿ, ಸಂಗೀತ ಮತ್ತು ಮುಹೂರ್ತದ ಸಮಯವನ್ನು "ಕಾರ್ಯಕ್ರಮ"ದಲ್ಲಿ ಸೇರಿಸಿ, ಅಥವಾ ಪ್ರತಿ ಸಮಾರಂಭಕ್ಕೆ ಬೇರೆ ಕರಡು ಉಳಿಸಿ.',
    tip6: 'ನಿಮ್ಮ ಹೆಸರು, ಫೋಟೋ ಮತ್ತು ವಿವರಗಳು ಈ ಫೋನ್ ಅಥವಾ ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲೇ ಇರುತ್ತವೆ. ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ, ಹಾಗಾಗಿ ಆ್ಯಪ್ ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.'
  },
  ml: {
    app_title: 'ക്ഷണക്കത്ത് മേക്കർ',
    intro: 'വിവാഹം, വിവാഹനിശ്ചയം, പിറന്നാൾ, ഗൃഹപ്രവേശം, പൂജ, സ്കൂൾ പരിപാടികൾ, കട ഉദ്ഘാടനം എന്നിവയ്ക്ക് മനോഹരമായ ക്ഷണക്കത്തുകൾ നിങ്ങളുടെ ഭാഷയിൽ ഉണ്ടാക്കൂ; WhatsApp-നോ പ്രിന്റിനോ തയ്യാർ.',
    privacy: 'നിങ്ങളുടെ പേരുകൾ, ഫോട്ടോ, വിവരങ്ങൾ ഈ ഉപകരണത്തിൽ തന്നെ. ഒന്നും അപ്‌ലോഡ് ചെയ്യുന്നില്ല.',
    occ_title: 'അവസരം',
    size_title: 'വലുപ്പം', size_wa: 'WhatsApp', size_story: 'സ്റ്റാറ്റസ് / സ്റ്റോറി', size_square: 'ചതുരം', size_a5: 'A5 പ്രിന്റ്',
    preview_aria: 'ക്ഷണക്കത്തിന്റെ പ്രിവ്യൂ. കാർഡിലെ ഒരു വരിയിൽ ക്ലിക്ക് ചെയ്ത് മാറ്റാം.', making: 'കാർഡ് തയ്യാറാകുന്നു…',
    share_btn: 'WhatsApp-ൽ അയയ്ക്കുക', dl_png: 'PNG ഡൗൺലോഡ്', copy_text: 'ക്ഷണ വാചകം പകർത്തുക', print_a5: 'A5 പ്രിന്റ്', print_2up: 'A4-ൽ 2 പ്രിന്റ്',
    print_hint: '"A5 പ്രിന്റ്" ഒരു പേജിൽ ഒരു കാർഡ് പ്രിന്റ് ചെയ്യും. "A4-ൽ 2" ഒരു A4 ഷീറ്റിൽ രണ്ട് കാർഡുകൾ അടുത്തടുത്ത് പ്രിന്റ് ചെയ്യും; നടുവിൽ മുറിക്കുക.',
    shortcut: 'ഷോർട്ട്കട്ട്: Ctrl + S PNG ഡൗൺലോഡ് ചെയ്യും, Ctrl + P പ്രിന്റ് ചെയ്യും.',
    share_none: 'ഈ ബ്രൗസറിന് ചിത്രം നേരിട്ട് അയയ്ക്കാനാവില്ല, അതിനാൽ കാർഡ് ഡൗൺലോഡ് ചെയ്തു. ഗാലറിയിൽ നിന്നോ Downloads-ൽ നിന്നോ അയയ്ക്കുക.',
    saved_file: '{name} സേവ് ചെയ്തു', copied_text: 'ക്ഷണ വാചകം പകർത്തി. കാർഡിനൊപ്പം WhatsApp-ൽ പേസ്റ്റ് ചെയ്യുക.',
    text_title: 'വാചകം', card_lang: 'കാർഡിന്റെ ഭാഷ', example_note: 'ഇത് ഒരു മാതൃകാ ക്ഷണക്കത്താണ്. പേരുകളും വിവരങ്ങളും നിങ്ങളുടേതാക്കി മാറ്റുക.', example_clear: 'മാതൃക നീക്കുക',
    heading_label: 'തലക്കെട്ട്', invite_label: 'ക്ഷണ വരി', n1_label: 'പേര് 1 (വ്യക്തി, ദമ്പതികൾ, കുടുംബം, സ്കൂൾ അല്ലെങ്കിൽ കട)', join_label: 'പേരുകൾക്കിടയിലെ വാക്ക്', n2_label: 'പേര് 2 (ഐച്ഛികം)',
    sub_label: 'പേരുകൾക്ക് താഴെയുള്ള വരി (മാതാപിതാക്കൾ, പ്രായം, അവസരം)', closing_label: 'അവസാന വരി', family_label: 'എന്ന് (കുടുംബം / ആതിഥേയർ)', text_reset: 'നിർദ്ദേശിച്ച വാചകം ഉപയോഗിക്കുക',
    details_title: 'തീയതി, സമയം, സ്ഥലം', date_label: 'തീയതി', time_label: 'സമയം', venue_label: 'സ്ഥലം (പേരും വിലാസവും)',
    map_label: 'Google Maps ലിങ്ക് (ഐച്ഛികം, QR കോഡായി പ്രിന്റ് ചെയ്യും)', map_bad: 'https:// എന്ന് തുടങ്ങുന്ന മുഴുവൻ ലിങ്ക് പേസ്റ്റ് ചെയ്യുക', map_ok: 'അതിഥികൾക്ക് കാർഡിലെ QR കോഡ് സ്കാൻ ചെയ്ത് മാപ്പ് തുറക്കാം.',
    schedule_label: 'പരിപാടി (ഐച്ഛികം, ഒരു വരിയിൽ ഒരു ചടങ്ങ്)', rsvp_label: 'RSVP ഫോൺ നമ്പർ',
    design_title: 'ഡിസൈൻ', colours: 'നിറങ്ങൾ', colour_n: 'നിറ സെറ്റ് {n}',
    design_royal: 'രാജകീയ മാങ്ങാചിത്രം', design_toran: 'ചെണ്ടുമല്ലി തോരണം', design_kalash: 'കലശം', design_lotus: 'താമര', design_peacock: 'മയിൽപ്പീലി', design_diya: 'ദീപാലങ്കാരം', design_jaali: 'ജാലി കമാനം',
    design_floral: 'റോസാപ്പൂ', design_mandala: 'മണ്ഡലം', design_balloons: 'ബലൂണുകൾ', design_banana: 'വാഴയില', design_minimal: 'ലളിതം', design_ribbon: 'റിബൺ', design_hearts: 'മോതിരവും ഹൃദയവും',
    font_label: 'അക്ഷര ശൈലി', font_elegant: 'മനോഹരം', font_festive: 'ഉത്സവം', font_simple: 'ലളിതം',
    font_note: 'മനോഹര, ഉത്സവ അക്ഷരങ്ങൾ ഒരിക്കൽ ഇന്റർനെറ്റിൽ നിന്ന് ഡൗൺലോഡ് ചെയ്യും. ഇന്റർനെറ്റ് ഇല്ലെങ്കിൽ ഉപകരണത്തിന്റെ ഫോണ്ട് ഉപയോഗിക്കും.',
    sym_title: 'മുകളിൽ പവിത്ര ചിഹ്നം', sym_none: 'ഒന്നുമില്ല', sym_ganesh: 'ശ്രീ ഗണേശ്', sym_om: 'ഓം', sym_ikonkar: 'ഇക് ഓങ്കാർ', sym_bismillah: 'ബിസ്മില്ലാഹ്', sym_cross: 'കുരിശ്', sym_buddha: 'ധർമ്മചക്രം',
    photo_title: 'ഫോട്ടോ (ഐച്ഛികം)', photo_add: 'ഫോട്ടോ ചേർക്കുക', photo_remove: 'നീക്കുക', photo_shape: 'ആകൃതി', shape_circle: 'വൃത്തം', shape_arch: 'കമാനം', shape_round: 'വൃത്താകൃതിയിലുള്ള കോണുകൾ', photo_zoom: 'സൂം',
    photo_hint: 'ഫോട്ടോ നീക്കാൻ കാർഡിൽ അത് വലിച്ചിടുക.', img_bad: 'ഈ ഫയൽ തുറക്കാനായില്ല. JPG അല്ലെങ്കിൽ PNG ചിത്രം തിരഞ്ഞെടുക്കുക.',
    img_unsaved: 'ഫോട്ടോ വളരെ വലുതാണ്, പേജ് അടച്ചാൽ ഓർമ്മയിലുണ്ടാകില്ല; എന്നാൽ ഇപ്പോൾ ഉപയോഗിക്കാം.',
    drafts_title: 'ഡ്രാഫ്റ്റുകൾ', drafts_help: 'കാർഡ് സേവ് ചെയ്ത് പിന്നീട് വീണ്ടും തുറക്കാം; ഉദാഹരണത്തിന് ഓരോ ചടങ്ങിനോ ഭാഷയ്ക്കോ ഒരു കാർഡ്.',
    draft_name_ph: 'ഡ്രാഫ്റ്റിന്റെ പേര്, ഉദാ. അഞ്ജലി വിവാഹം', draft_save: 'ഡ്രാഫ്റ്റ് സേവ് ചെയ്യുക', draft_saved: 'ഡ്രാഫ്റ്റ് ഈ ഉപകരണത്തിൽ സേവ് ചെയ്തു.', draft_open: 'തുറക്കുക', draft_opened: 'ഡ്രാഫ്റ്റ് തുറന്നു.', drafts_none: 'ഇതുവരെ ഡ്രാഫ്റ്റുകൾ സേവ് ചെയ്തിട്ടില്ല.',
    draft_full: 'ഈ ഡ്രാഫ്റ്റ് സേവ് ചെയ്യാൻ സ്ഥലമില്ല. പഴയ ഡ്രാഫ്റ്റ് ഇല്ലാതാക്കുക അല്ലെങ്കിൽ ഫോട്ടോ നീക്കുക.', draft_limit: '12 ഡ്രാഫ്റ്റുകൾ മാത്രമേ സൂക്ഷിക്കൂ, അതിനാൽ ഏറ്റവും പഴയ ഡ്രാഫ്റ്റ് നീക്കം ചെയ്തു.', draft_delete_q: 'ഈ ഡ്രാഫ്റ്റ് ഇല്ലാതാക്കണോ?',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ആശയങ്ങൾ',
    tip1: 'അവസരം തിരഞ്ഞെടുത്ത്, പേരുകൾ, തീയതി, സമയം, സ്ഥലം മാറ്റുക. ടൈപ്പ് ചെയ്യുമ്പോൾ തന്നെ കാർഡ് മാറും.',
    tip2: 'അയയ്ക്കാൻ "WhatsApp", സ്റ്റാറ്റസിനും Instagram-നും "സ്റ്റാറ്റസ് / സ്റ്റോറി", പ്രിന്റിംഗ് കടയ്ക്ക് "A5 പ്രിന്റ്" തിരഞ്ഞെടുക്കുക. ഏത് കാർഡും A4 ഷീറ്റിൽ 2 ആയും പ്രിന്റ് ചെയ്യാം.',
    tip3: 'നിങ്ങളുടെ Google Maps ലിങ്ക് പേസ്റ്റ് ചെയ്യുക: അതിഥികൾ കാർഡിലെ QR കോഡ് സ്കാൻ ചെയ്ത് വഴി ചോദിക്കാതെ സ്ഥലത്തെത്തും.',
    tip4: 'ഒരേ കാർഡ് രണ്ട് ഭാഷകളിൽ ഉണ്ടാക്കുക: ഡ്രാഫ്റ്റ് സേവ് ചെയ്ത്, കാർഡിന്റെ ഭാഷ മാറ്റി, വീണ്ടും ഡൗൺലോഡ് ചെയ്യുക. ബന്ധുക്കൾക്ക് മലയാളം, സഹപ്രവർത്തകർക്ക് ഇംഗ്ലീഷ്.',
    tip5: 'വിവാഹത്തിന് മൈലാഞ്ചി, സംഗീത്, മുഹൂർത്ത സമയങ്ങൾ "പരിപാടി"യിൽ ചേർക്കുക, അല്ലെങ്കിൽ ഓരോ ചടങ്ങിനും വേറെ ഡ്രാഫ്റ്റ് സേവ് ചെയ്യുക.',
    tip6: 'നിങ്ങളുടെ പേരുകൾ, ഫോട്ടോ, വിവരങ്ങൾ ഈ ഫോണിലോ കമ്പ്യൂട്ടറിലോ തന്നെ. ഒന്നും അപ്‌ലോഡ് ചെയ്യുന്നില്ല, അതിനാൽ ഇന്റർനെറ്റ് ഇല്ലാതെയും ആപ്പ് പ്രവർത്തിക്കും.'
  },
  ur: {
    app_title: 'دعوت نامہ میکر',
    intro: 'شادی، منگنی، سالگرہ، نئے گھر، میلاد، اسکول کی تقریبات اور دکان کے افتتاح کے خوبصورت دعوت نامے اپنی زبان میں بنائیں، WhatsApp یا پرنٹ کے لیے تیار۔',
    privacy: 'آپ کے نام، تصویر اور تفصیلات اسی ڈیوائس میں رہتی ہیں۔ کچھ بھی اپ لوڈ نہیں ہوتا۔',
    occ_title: 'موقع',
    size_title: 'سائز', size_wa: 'WhatsApp', size_story: 'اسٹیٹس / اسٹوری', size_square: 'مربع', size_a5: 'A5 پرنٹ',
    preview_aria: 'دعوت نامے کا پیش منظر۔ کارڈ کی کسی سطر پر کلک کرکے اسے بدلیں۔', making: 'کارڈ بن رہا ہے…',
    share_btn: 'WhatsApp پر بھیجیں', dl_png: 'PNG ڈاؤن لوڈ کریں', copy_text: 'دعوت کا متن کاپی کریں', print_a5: 'A5 پرنٹ کریں', print_2up: 'A4 پر 2 پرنٹ کریں',
    print_hint: '"A5 پرنٹ" میں ہر صفحے پر ایک کارڈ چھپتا ہے۔ "A4 پر 2" میں ایک A4 شیٹ پر دو کارڈ ساتھ ساتھ چھپتے ہیں؛ درمیان سے کاٹ لیں۔',
    shortcut: 'شارٹ کٹ: Ctrl + S سے PNG ڈاؤن لوڈ، Ctrl + P سے پرنٹ۔',
    share_none: 'یہ براؤزر براہِ راست تصویر نہیں بھیج سکتا، اس لیے کارڈ ڈاؤن لوڈ ہو گیا۔ اسے گیلری یا Downloads سے بھیجیں۔',
    saved_file: '{name} محفوظ ہو گیا', copied_text: 'دعوت کا متن کاپی ہو گیا۔ اسے کارڈ کے ساتھ WhatsApp میں پیسٹ کریں۔',
    text_title: 'الفاظ', card_lang: 'کارڈ کی زبان', example_note: 'یہ ایک مثالی دعوت نامہ ہے۔ نام اور تفصیلات اپنی لکھیں۔', example_clear: 'مثال ہٹائیں',
    heading_label: 'عنوان', invite_label: 'دعوت کی سطر', n1_label: 'نام 1 (فرد، جوڑا، خاندان، اسکول یا دکان)', join_label: 'ناموں کے درمیان کا لفظ', n2_label: 'نام 2 (اختیاری)',
    sub_label: 'ناموں کے نیچے کی سطر (والدین، عمر، موقع)', closing_label: 'آخری سطر', family_label: 'منجانب (خاندان / میزبان)', text_reset: 'تجویز کردہ الفاظ استعمال کریں',
    details_title: 'تاریخ، وقت اور مقام', date_label: 'تاریخ', time_label: 'وقت', venue_label: 'مقام (نام اور پتہ)',
    map_label: 'Google Maps لنک (اختیاری، QR کوڈ کے طور پر چھپے گا)', map_bad: 'https:// سے شروع ہونے والا مکمل لنک پیسٹ کریں', map_ok: 'مہمان کارڈ پر QR کوڈ اسکین کرکے نقشہ کھول سکتے ہیں۔',
    schedule_label: 'پروگرام (اختیاری، ہر رسم ایک سطر میں)', rsvp_label: 'RSVP فون نمبر',
    design_title: 'ڈیزائن', colours: 'رنگ', colour_n: 'رنگ سیٹ {n}',
    design_royal: 'شاہی کیری', design_toran: 'گیندے کا تورن', design_kalash: 'کلش', design_lotus: 'کنول', design_peacock: 'مور پنکھ', design_diya: 'دیے اور روشنی', design_jaali: 'جالی محراب',
    design_floral: 'گلاب', design_mandala: 'منڈلا', design_balloons: 'غبارے', design_banana: 'کیلے کا پتا', design_minimal: 'سادہ', design_ribbon: 'ربن', design_hearts: 'انگوٹھیاں اور دل',
    font_label: 'حروف کا انداز', font_elegant: 'نفیس', font_festive: 'تہواری', font_simple: 'سادہ',
    font_note: 'نفیس اور تہواری حروف ایک بار انٹرنیٹ سے ڈاؤن لوڈ ہوتے ہیں۔ انٹرنیٹ نہ ہو تو ڈیوائس کا فونٹ استعمال ہوتا ہے۔',
    sym_title: 'اوپر مقدس نشان', sym_none: 'کوئی نہیں', sym_ganesh: 'شری گنیش', sym_om: 'اوم', sym_ikonkar: 'اک اونکار', sym_bismillah: 'بسم اللہ', sym_cross: 'صلیب', sym_buddha: 'دھرم چکر',
    photo_title: 'تصویر (اختیاری)', photo_add: 'تصویر شامل کریں', photo_remove: 'ہٹائیں', photo_shape: 'شکل', shape_circle: 'گول', shape_arch: 'محراب', shape_round: 'گول کونے', photo_zoom: 'زوم',
    photo_hint: 'تصویر ہلانے کے لیے کارڈ پر اسے کھینچیں۔', img_bad: 'یہ فائل نہیں کھل سکی۔ براہِ کرم JPG یا PNG تصویر منتخب کریں۔',
    img_unsaved: 'تصویر اتنی بڑی ہے کہ صفحہ بند کرنے کے بعد یاد نہیں رہے گی، لیکن ابھی استعمال کر سکتے ہیں۔',
    drafts_title: 'ڈرافٹ', drafts_help: 'کارڈ محفوظ کرکے بعد میں دوبارہ کھولیں، مثلاً ہر رسم یا ہر زبان کے لیے ایک کارڈ۔',
    draft_name_ph: 'ڈرافٹ کا نام، مثلاً عائشہ کی شادی', draft_save: 'ڈرافٹ محفوظ کریں', draft_saved: 'ڈرافٹ اسی ڈیوائس میں محفوظ ہو گیا۔', draft_open: 'کھولیں', draft_opened: 'ڈرافٹ کھل گیا۔', drafts_none: 'ابھی کوئی ڈرافٹ محفوظ نہیں۔',
    draft_full: 'اس ڈرافٹ کے لیے جگہ نہیں ہے۔ کوئی پرانا ڈرافٹ حذف کریں یا تصویر ہٹائیں۔', draft_limit: 'صرف 12 ڈرافٹ رکھے جاتے ہیں، اس لیے سب سے پرانا ڈرافٹ ہٹا دیا گیا۔', draft_delete_q: 'یہ ڈرافٹ حذف کریں؟',
    help_title: 'استعمال کا طریقہ / آئیڈیاز',
    tip1: 'موقع چنیں، پھر نام، تاریخ، وقت اور مقام بدلیں۔ ٹائپ کرتے ہی کارڈ بدل جاتا ہے۔',
    tip2: 'بھیجنے کے لیے "WhatsApp"، اسٹیٹس اور Instagram کے لیے "اسٹیٹس / اسٹوری"، اور پرنٹنگ کی دکان کے لیے "A5 پرنٹ" چنیں۔ کوئی بھی کارڈ A4 شیٹ پر 2 بھی چھپ سکتا ہے۔',
    tip3: 'اپنا Google Maps لنک پیسٹ کریں: مہمان کارڈ کا QR کوڈ اسکین کرکے بغیر راستہ پوچھے مقام تک پہنچ جائیں گے۔',
    tip4: 'ایک ہی کارڈ دو زبانوں میں بنائیں: ڈرافٹ محفوظ کریں، کارڈ کی زبان بدلیں اور دوبارہ ڈاؤن لوڈ کریں۔ رشتہ داروں کے لیے اردو، ساتھیوں کے لیے انگریزی۔',
    tip5: 'شادی کے لیے مہندی، مایوں اور بارات کے اوقات "پروگرام" میں لکھیں، یا ہر رسم کے لیے الگ ڈرافٹ محفوظ کریں۔',
    tip6: 'آپ کے نام، تصویر اور تفصیلات اسی فون یا کمپیوٹر میں رہتی ہیں۔ کچھ اپ لوڈ نہیں ہوتا، اس لیے ایپ انٹرنیٹ کے بغیر بھی چلتی ہے۔'
  }
};
