/* Attendance Register: UI strings. Keys are identical in all 12 languages.
   Lists (wd_full, wd_min, months, sample_names) are comma-separated, split in app.js. */
window.APP_STRINGS = window.APP_STRINGS || {};

window.APP_STRINGS.en = {
  app_title: 'Attendance Register',
  intro: 'Take class attendance in seconds, see monthly totals and attendance %, and print the register. Everything stays on this device.',
  tab_day: 'Daily',
  tab_month: 'Monthly',
  tab_students: 'Students',
  class_label: 'Class',
  date_label: 'Date',
  today: 'Today',
  prev_day: 'Previous day',
  next_day: 'Next day',
  prev_month: 'Previous month',
  next_month: 'Next month',
  st_P: 'Present',
  st_A: 'Absent',
  st_T: 'Late',
  st_V: 'Leave',
  st_none: 'Not marked',
  sh_P: 'P',
  sh_A: 'A',
  sh_T: 'Lt',
  sh_V: 'Lv',
  sh_H: 'H',
  holiday: 'Holiday',
  mark_all: 'Mark all present',
  marked_present: '{n} students marked present.',
  all_marked: 'Everyone is already marked.',
  clear_day: 'Clear this day',
  confirm_clear_day: 'Remove all marks for {date}?',
  copy_absent: 'Copy absent list',
  absent_text: '{cls} · {date} · Absent ({n}): {list}',
  none_absent: 'Nobody is absent on this day.',
  marked_n: '{n} of {total} marked',
  tap_hint: 'Tap a name to change it: Present → Absent → Late → Leave → not marked.',
  search_ph: 'Search name or roll no.',
  no_match: 'No student matches “{q}”.',
  holiday_sunday: 'Sunday is a holiday.',
  holiday_national: 'This is a national holiday.',
  holiday_marked: 'This day is marked as a holiday.',
  take_anyway: 'Take attendance on this day',
  make_holiday: 'Mark as holiday',
  future_note: 'This date is in the future.',
  no_students: 'This class has no students yet.',
  go_students: 'Add students',
  sample_note: 'This is a sample class with made-up attendance, so you can try the app. Add your own class in the Students tab, then delete the sample.',
  sample_class: 'Sample · Class 6 A',
  sample_names: 'Aarav Sharma,Ananya Iyer,Arjun Reddy,Diya Patel,Fatima Khan,Gurpreet Singh,Ishaan Verma,Kavya Nair,Lakshmi Rao,Mohammed Ali,Neha Gupta,Pranav Joshi,Priya Das,Rahul Yadav,Riya Banerjee,Rohan Mehta,Sana Shaikh,Siddharth Kulkarni,Tanvi Desai,Vikram Choudhary',
  my_class: 'My class',
  month_hint: 'Tap a cell to change a mark. Tap a date at the top to make it a holiday, or a working day again.',
  sundays_off: 'Sundays and national holidays (26 Jan, 15 Aug, 2 Oct) are off',
  leave_counts: 'Count leave as present',
  min_pct: 'Minimum attendance %',
  late_note: 'Late counts as present.',
  leave_note: 'Leave also counts as present.',
  col_roll: 'Roll',
  col_name: 'Name',
  col_days: 'Days',
  col_pct: '%',
  stat_days: 'Days attendance was taken',
  stat_avg: 'Class average',
  stat_below: 'Students below {p}%',
  day_present: 'Present each day',
  export_csv: 'Export CSV',
  print_register: 'Print register',
  print_meta: 'Class: {cls} · Month: {month}',
  printed_on: 'Printed on {date}',
  sign_teacher: 'Class teacher',
  sign_principal: 'Principal',
  school_name: 'School name (shown on the printed register)',
  school_ph: 'e.g. Govt. Senior Secondary School, Jaipur',
  class_settings: 'This class',
  class_name: 'Class name',
  class_ph: 'e.g. Class 7 B',
  delete_class: 'Delete this class',
  confirm_delete_class: 'Delete “{name}” and all its attendance? This cannot be undone.',
  new_class: 'Add a new class',
  add_class: 'Add class',
  class_added: 'Class “{name}” added.',
  renamed: 'Class name saved.',
  students_n: '{n} students',
  add_student: 'Add one student',
  roll_ph: 'Roll',
  name_ph: 'Student name',
  paste_title: 'Paste a list of students',
  paste_help: 'One student per line: roll no., then name. A line with only a name gets the next roll no. You can copy two columns straight from Excel or Google Sheets.',
  paste_ph: 'e.g.\n1, Aarav Sharma\n2, Fatima Khan\nRohan Das',
  paste_add: 'Add these students',
  import_csv: 'Import CSV',
  csv_help: 'Or import a CSV file with roll no. and name columns. A header row is skipped.',
  added_n: '{n} students added.',
  nothing_added: 'No names found. Please check the format.',
  dup_rolls: 'Same roll no. used more than once: {list}',
  remove_student: 'Remove {name}',
  confirm_remove: 'Remove {name}? Their attendance in this class will also be deleted.',
  need_name: 'Please type a name.',
  backup_title: 'Backup and restore',
  backup_help: 'Attendance is saved only in this browser. Download a backup every week, and restore it on a new phone or computer.',
  backup_dl: 'Download backup',
  restore: 'Restore backup',
  restore_ok: 'Backup restored: {n} classes.',
  restore_bad: 'This file is not an Attendance Register backup.',
  confirm_restore: 'Replace all classes on this device with the ones in the backup?',
  help_1: 'Make one class for each section you teach. Paste names from your school list, or import a CSV file.',
  help_2: 'Every morning tap “Mark all present”, then tap only the students who are absent. Even 60 students take less than a minute.',
  help_3: 'The Monthly tab shows each student’s attendance %. Rows in red are below the minimum (CBSE expects 75%), so you can talk to parents early.',
  help_4: 'At the end of the month, print the register (A4 landscape) and sign it, or export CSV for Excel or Google Sheets.',
  help_5: 'Classroom activity: let the class monitor take attendance on the smartboard. Then students work out their own attendance %: (days present ÷ working days) × 100.',
  help_6: 'Your data never leaves this device. Download a backup every week so nothing is lost if the phone changes.',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday',
  wd_min: 'Su,Mo,Tu,We,Th,Fr,Sa',
  months: 'January,February,March,April,May,June,July,August,September,October,November,December'
};

window.APP_STRINGS.hi = {
  app_title: 'हाज़िरी रजिस्टर',
  intro: 'सेकंडों में कक्षा की हाज़िरी लें, महीने का कुल और हाज़िरी % देखें, और रजिस्टर प्रिंट करें। सारा डेटा इसी डिवाइस पर रहता है।',
  tab_day: 'रोज़ाना',
  tab_month: 'महीना',
  tab_students: 'विद्यार्थी',
  class_label: 'कक्षा',
  date_label: 'तारीख़',
  today: 'आज',
  prev_day: 'पिछला दिन',
  next_day: 'अगला दिन',
  prev_month: 'पिछला महीना',
  next_month: 'अगला महीना',
  st_P: 'उपस्थित',
  st_A: 'अनुपस्थित',
  st_T: 'देर से',
  st_V: 'छुट्टी',
  st_none: 'बाकी',
  sh_P: 'उ',
  sh_A: 'अ',
  sh_T: 'दे',
  sh_V: 'छु',
  sh_H: 'अव',
  holiday: 'अवकाश',
  mark_all: 'सबको उपस्थित लगाएँ',
  marked_present: '{n} विद्यार्थी उपस्थित लगाए गए।',
  all_marked: 'सबकी हाज़िरी पहले से लगी है।',
  clear_day: 'यह दिन मिटाएँ',
  confirm_clear_day: '{date} की सारी हाज़िरी मिटा दें?',
  copy_absent: 'अनुपस्थित सूची कॉपी करें',
  absent_text: '{cls} · {date} · अनुपस्थित ({n}): {list}',
  none_absent: 'इस दिन कोई अनुपस्थित नहीं है।',
  marked_n: '{total} में से {n} की हाज़िरी लगी',
  tap_hint: 'नाम पर टैप करके बदलें: उपस्थित → अनुपस्थित → देर से → छुट्टी → बाकी।',
  search_ph: 'नाम या रोल नंबर खोजें',
  no_match: '“{q}” से कोई विद्यार्थी नहीं मिला।',
  holiday_sunday: 'रविवार की छुट्टी है।',
  holiday_national: 'यह राष्ट्रीय अवकाश है।',
  holiday_marked: 'इस दिन अवकाश रखा गया है।',
  take_anyway: 'इस दिन भी हाज़िरी लें',
  make_holiday: 'अवकाश घोषित करें',
  future_note: 'यह तारीख़ अभी आगे की है।',
  no_students: 'इस कक्षा में अभी कोई विद्यार्थी नहीं है।',
  go_students: 'विद्यार्थी जोड़ें',
  sample_note: 'यह नमूना कक्षा है, इसकी हाज़िरी काल्पनिक है ताकि आप ऐप आज़मा सकें। “विद्यार्थी” टैब में अपनी कक्षा जोड़ें, फिर नमूना हटा दें।',
  sample_class: 'नमूना · कक्षा 6 अ',
  sample_names: 'आरव शर्मा,अनन्या अय्यर,अर्जुन रेड्डी,दिया पटेल,फ़ातिमा ख़ान,गुरप्रीत सिंह,ईशान वर्मा,काव्या नायर,लक्ष्मी राव,मोहम्मद अली,नेहा गुप्ता,प्रणव जोशी,प्रिया दास,राहुल यादव,रिया बनर्जी,रोहन मेहता,सना शेख़,सिद्धार्थ कुलकर्णी,तन्वी देसाई,विक्रम चौधरी',
  my_class: 'मेरी कक्षा',
  month_hint: 'हाज़िरी बदलने के लिए खाने पर टैप करें। ऊपर किसी तारीख़ पर टैप करके उसे अवकाश बनाएँ, या फिर से पढ़ाई का दिन बनाएँ।',
  sundays_off: 'रविवार और राष्ट्रीय अवकाश (26 जनवरी, 15 अगस्त, 2 अक्टूबर) की छुट्टी',
  leave_counts: 'छुट्टी को उपस्थित गिनें',
  min_pct: 'न्यूनतम हाज़िरी %',
  late_note: 'देर से आने वाले उपस्थित गिने जाते हैं।',
  leave_note: 'छुट्टी को भी उपस्थित गिना जाता है।',
  col_roll: 'रोल',
  col_name: 'नाम',
  col_days: 'दिन',
  col_pct: '%',
  stat_days: 'जितने दिन हाज़िरी ली गई',
  stat_avg: 'कक्षा का औसत',
  stat_below: '{p}% से कम वाले विद्यार्थी',
  day_present: 'हर दिन उपस्थित',
  export_csv: 'CSV निकालें',
  print_register: 'रजिस्टर प्रिंट करें',
  print_meta: 'कक्षा: {cls} · महीना: {month}',
  printed_on: 'प्रिंट की तारीख़: {date}',
  sign_teacher: 'कक्षा अध्यापक',
  sign_principal: 'प्रधानाचार्य',
  school_name: 'स्कूल का नाम (प्रिंट किए रजिस्टर पर दिखेगा)',
  school_ph: 'जैसे: राजकीय उच्च माध्यमिक विद्यालय, जयपुर',
  class_settings: 'यह कक्षा',
  class_name: 'कक्षा का नाम',
  class_ph: 'जैसे: कक्षा 7 ब',
  delete_class: 'यह कक्षा हटाएँ',
  confirm_delete_class: '“{name}” और उसकी सारी हाज़िरी हटा दें? यह वापस नहीं होगा।',
  new_class: 'नई कक्षा जोड़ें',
  add_class: 'कक्षा जोड़ें',
  class_added: 'कक्षा “{name}” जुड़ गई।',
  renamed: 'कक्षा का नाम सेव हो गया।',
  students_n: '{n} विद्यार्थी',
  add_student: 'एक विद्यार्थी जोड़ें',
  roll_ph: 'रोल',
  name_ph: 'विद्यार्थी का नाम',
  paste_title: 'विद्यार्थियों की सूची चिपकाएँ',
  paste_help: 'हर लाइन में एक विद्यार्थी: पहले रोल नंबर, फिर नाम। जिस लाइन में सिर्फ़ नाम है, उसे अगला रोल नंबर मिल जाएगा। Excel या Google Sheets से दो कॉलम सीधे कॉपी कर सकते हैं।',
  paste_ph: 'जैसे:\n1, आरव शर्मा\n2, फ़ातिमा ख़ान\nरोहन दास',
  paste_add: 'ये विद्यार्थी जोड़ें',
  import_csv: 'CSV इम्पोर्ट करें',
  csv_help: 'या रोल नंबर और नाम के कॉलम वाली CSV फ़ाइल इम्पोर्ट करें। हेडर वाली पंक्ति अपने-आप छूट जाती है।',
  added_n: '{n} विद्यार्थी जुड़ गए।',
  nothing_added: 'कोई नाम नहीं मिला। लिखने का तरीका जाँच लें।',
  dup_rolls: 'ये रोल नंबर एक से ज़्यादा बार हैं: {list}',
  remove_student: '{name} को हटाएँ',
  confirm_remove: '{name} को हटाएँ? इस कक्षा में उनकी हाज़िरी भी मिट जाएगी।',
  need_name: 'कृपया नाम लिखें।',
  backup_title: 'बैकअप और रीस्टोर',
  backup_help: 'हाज़िरी सिर्फ़ इसी ब्राउज़र में सेव होती है। हर हफ़्ते बैकअप डाउनलोड करें, और नए फ़ोन या कंप्यूटर पर उसे रीस्टोर करें।',
  backup_dl: 'बैकअप डाउनलोड करें',
  restore: 'बैकअप रीस्टोर करें',
  restore_ok: 'बैकअप रीस्टोर हो गया: {n} कक्षाएँ।',
  restore_bad: 'यह हाज़िरी रजिस्टर की बैकअप फ़ाइल नहीं है।',
  confirm_restore: 'इस डिवाइस की सभी कक्षाओं की जगह बैकअप वाली कक्षाएँ रख दें?',
  help_1: 'आप जितने सेक्शन पढ़ाते हैं, हर एक की अलग कक्षा बनाएँ। स्कूल की सूची से नाम चिपकाएँ या CSV फ़ाइल इम्पोर्ट करें।',
  help_2: 'रोज़ सुबह “सबको उपस्थित लगाएँ” दबाएँ, फिर सिर्फ़ अनुपस्थित बच्चों पर टैप करें। 60 बच्चों की हाज़िरी भी एक मिनट से कम में लग जाती है।',
  help_3: '“महीना” टैब में हर विद्यार्थी का हाज़िरी % दिखता है। लाल पंक्तियाँ न्यूनतम से कम हैं (CBSE में 75% ज़रूरी है), ताकि आप समय रहते अभिभावकों से बात कर सकें।',
  help_4: 'महीने के अंत में रजिस्टर प्रिंट करें (A4 आड़ा पेज) और हस्ताक्षर करें, या Excel / Google Sheets के लिए CSV निकालें।',
  help_5: 'कक्षा गतिविधि: कक्षा मॉनिटर से स्मार्टबोर्ड पर हाज़िरी लगवाएँ। फिर विद्यार्थी अपना हाज़िरी % खुद निकालें: (उपस्थित दिन ÷ कामकाजी दिन) × 100।',
  help_6: 'आपका डेटा इस डिवाइस से बाहर नहीं जाता। हर हफ़्ते बैकअप डाउनलोड करें, ताकि फ़ोन बदलने पर कुछ न खोए।',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'रविवार,सोमवार,मंगलवार,बुधवार,गुरुवार,शुक्रवार,शनिवार',
  wd_min: 'र,सो,मं,बु,गु,शु,श',
  months: 'जनवरी,फ़रवरी,मार्च,अप्रैल,मई,जून,जुलाई,अगस्त,सितंबर,अक्टूबर,नवंबर,दिसंबर'
};

window.APP_STRINGS.bn = {
  app_title: 'হাজিরা খাতা',
  intro: 'কয়েক সেকেন্ডে ক্লাসের হাজিরা নিন, মাসের মোট ও হাজিরার % দেখুন, আর খাতা প্রিন্ট করুন। সব তথ্য এই ডিভাইসেই থাকে।',
  tab_day: 'দৈনিক',
  tab_month: 'মাসিক',
  tab_students: 'ছাত্রছাত্রী',
  class_label: 'ক্লাস',
  date_label: 'তারিখ',
  today: 'আজ',
  prev_day: 'আগের দিন',
  next_day: 'পরের দিন',
  prev_month: 'আগের মাস',
  next_month: 'পরের মাস',
  st_P: 'উপস্থিত',
  st_A: 'অনুপস্থিত',
  st_T: 'দেরিতে',
  st_V: 'ছুটি',
  st_none: 'বাকি',
  sh_P: 'উ',
  sh_A: 'অ',
  sh_T: 'দে',
  sh_V: 'ছু',
  sh_H: 'ব',
  holiday: 'বন্ধ',
  mark_all: 'সবাইকে উপস্থিত দিন',
  marked_present: '{n} জনকে উপস্থিত দেওয়া হল।',
  all_marked: 'সবার হাজিরা আগেই দেওয়া হয়েছে।',
  clear_day: 'এই দিনটি মুছুন',
  confirm_clear_day: '{date}-এর সব হাজিরা মুছে দেবেন?',
  copy_absent: 'অনুপস্থিতদের তালিকা কপি করুন',
  absent_text: '{cls} · {date} · অনুপস্থিত ({n}): {list}',
  none_absent: 'এই দিন কেউ অনুপস্থিত নেই।',
  marked_n: '{total} জনের মধ্যে {n} জনের হাজিরা দেওয়া হয়েছে',
  tap_hint: 'নামে ট্যাপ করে বদলান: উপস্থিত → অনুপস্থিত → দেরিতে → ছুটি → বাকি।',
  search_ph: 'নাম বা রোল নম্বর খুঁজুন',
  no_match: '“{q}” নামে কোনো ছাত্রছাত্রী পাওয়া যায়নি।',
  holiday_sunday: 'রবিবার ছুটির দিন।',
  holiday_national: 'এটি জাতীয় ছুটির দিন।',
  holiday_marked: 'এই দিনটি ছুটি হিসেবে রাখা আছে।',
  take_anyway: 'এই দিনেও হাজিরা নিন',
  make_holiday: 'ছুটি ঘোষণা করুন',
  future_note: 'এই তারিখটি এখনও আসেনি।',
  no_students: 'এই ক্লাসে এখনও কোনো ছাত্রছাত্রী নেই।',
  go_students: 'ছাত্রছাত্রী যোগ করুন',
  sample_note: 'এটি একটি নমুনা ক্লাস, হাজিরাগুলো বানানো, যাতে আপনি অ্যাপটি চালিয়ে দেখতে পারেন। “ছাত্রছাত্রী” ট্যাবে নিজের ক্লাস যোগ করুন, তারপর নমুনাটি মুছে দিন।',
  sample_class: 'নমুনা · ষষ্ঠ শ্রেণি ক',
  sample_names: 'অরিত্র সেন,অনন্যা ঘোষ,অর্জুন দাস,দীপা মণ্ডল,ফাতিমা খাতুন,গৌরব সাহা,ঈশান রায়,কাবেরী পাল,লক্ষ্মী বর্মন,মহম্মদ আলি,নেহা চক্রবর্তী,প্রণব দত্ত,প্রিয়া বসু,রাহুল হালদার,রিয়া ব্যানার্জি,রোহন মুখার্জি,সানা পারভিন,সিদ্ধার্থ গুহ,তানিয়া সরকার,বিক্রম চৌধুরী',
  my_class: 'আমার ক্লাস',
  month_hint: 'হাজিরা বদলাতে ঘরে ট্যাপ করুন। উপরে কোনো তারিখে ট্যাপ করে সেটিকে ছুটি করুন, বা আবার ক্লাসের দিন করুন।',
  sundays_off: 'রবিবার ও জাতীয় ছুটি (26 জানুয়ারি, 15 আগস্ট, 2 অক্টোবর) বন্ধ',
  leave_counts: 'ছুটিকে উপস্থিত ধরুন',
  min_pct: 'ন্যূনতম হাজিরা %',
  late_note: 'দেরিতে এলেও উপস্থিত ধরা হয়।',
  leave_note: 'ছুটিকেও উপস্থিত ধরা হয়।',
  col_roll: 'রোল',
  col_name: 'নাম',
  col_days: 'দিন',
  col_pct: '%',
  stat_days: 'যত দিন হাজিরা নেওয়া হয়েছে',
  stat_avg: 'ক্লাসের গড়',
  stat_below: '{p}%-এর কম ছাত্রছাত্রী',
  day_present: 'প্রতিদিন উপস্থিত',
  export_csv: 'CSV নিন',
  print_register: 'খাতা প্রিন্ট করুন',
  print_meta: 'ক্লাস: {cls} · মাস: {month}',
  printed_on: 'প্রিন্টের তারিখ: {date}',
  sign_teacher: 'শ্রেণি শিক্ষক',
  sign_principal: 'প্রধান শিক্ষক',
  school_name: 'স্কুলের নাম (প্রিন্ট করা খাতায় দেখাবে)',
  school_ph: 'যেমন: সরকারি উচ্চ মাধ্যমিক বিদ্যালয়, বর্ধমান',
  class_settings: 'এই ক্লাস',
  class_name: 'ক্লাসের নাম',
  class_ph: 'যেমন: সপ্তম শ্রেণি খ',
  delete_class: 'এই ক্লাস মুছুন',
  confirm_delete_class: '“{name}” আর তার সব হাজিরা মুছে দেবেন? এটি আর ফেরানো যাবে না।',
  new_class: 'নতুন ক্লাস যোগ করুন',
  add_class: 'ক্লাস যোগ করুন',
  class_added: '“{name}” ক্লাস যোগ হয়েছে।',
  renamed: 'ক্লাসের নাম সেভ হয়েছে।',
  students_n: '{n} জন ছাত্রছাত্রী',
  add_student: 'একজন ছাত্র/ছাত্রী যোগ করুন',
  roll_ph: 'রোল',
  name_ph: 'ছাত্র/ছাত্রীর নাম',
  paste_title: 'ছাত্রছাত্রীদের তালিকা পেস্ট করুন',
  paste_help: 'প্রতি লাইনে একজন: আগে রোল নম্বর, তারপর নাম। যে লাইনে শুধু নাম আছে, সে পরের রোল নম্বর পাবে। Excel বা Google Sheets থেকে দুটি কলাম সরাসরি কপি করতে পারেন।',
  paste_ph: 'যেমন:\n1, অরিত্র সেন\n2, ফাতিমা খাতুন\nরোহন দাস',
  paste_add: 'এদের যোগ করুন',
  import_csv: 'CSV ইমপোর্ট করুন',
  csv_help: 'অথবা রোল নম্বর ও নামের কলাম থাকা CSV ফাইল ইমপোর্ট করুন। শিরোনামের সারি নিজে থেকেই বাদ যায়।',
  added_n: '{n} জন যোগ হয়েছে।',
  nothing_added: 'কোনো নাম পাওয়া যায়নি। লেখার ধরন দেখে নিন।',
  dup_rolls: 'এই রোল নম্বরগুলো একাধিকবার আছে: {list}',
  remove_student: '{name}-কে সরান',
  confirm_remove: '{name}-কে সরাবেন? এই ক্লাসে তার হাজিরাও মুছে যাবে।',
  need_name: 'দয়া করে নাম লিখুন।',
  backup_title: 'ব্যাকআপ ও রিস্টোর',
  backup_help: 'হাজিরা শুধু এই ব্রাউজারেই সেভ থাকে। প্রতি সপ্তাহে ব্যাকআপ ডাউনলোড করুন, আর নতুন ফোন বা কম্পিউটারে রিস্টোর করুন।',
  backup_dl: 'ব্যাকআপ ডাউনলোড করুন',
  restore: 'ব্যাকআপ রিস্টোর করুন',
  restore_ok: 'ব্যাকআপ রিস্টোর হয়েছে: {n}টি ক্লাস।',
  restore_bad: 'এটি হাজিরা খাতার ব্যাকআপ ফাইল নয়।',
  confirm_restore: 'এই ডিভাইসের সব ক্লাসের বদলে ব্যাকআপের ক্লাসগুলো রাখবেন?',
  help_1: 'যতগুলো সেকশনে পড়ান, প্রতিটির জন্য আলাদা ক্লাস বানান। স্কুলের তালিকা থেকে নাম পেস্ট করুন বা CSV ফাইল ইমপোর্ট করুন।',
  help_2: 'প্রতিদিন সকালে “সবাইকে উপস্থিত দিন” টিপুন, তারপর শুধু অনুপস্থিতদের নামে ট্যাপ করুন। 60 জনের হাজিরাও এক মিনিটের কম সময়ে হয়ে যায়।',
  help_3: '“মাসিক” ট্যাবে প্রত্যেকের হাজিরার % দেখা যায়। লাল সারিগুলো ন্যূনতমের কম (CBSE অনুযায়ী 75% লাগে), তাই সময় থাকতেই অভিভাবকদের সঙ্গে কথা বলতে পারবেন।',
  help_4: 'মাসের শেষে খাতা প্রিন্ট করুন (A4 আড়াআড়ি) ও সই করুন, অথবা Excel / Google Sheets-এর জন্য CSV নিন।',
  help_5: 'ক্লাসের কাজ: ক্লাস মনিটরকে স্মার্টবোর্ডে হাজিরা নিতে দিন। তারপর ছাত্রছাত্রীরা নিজেদের হাজিরার % বের করুক: (উপস্থিত দিন ÷ ক্লাসের দিন) × 100।',
  help_6: 'আপনার তথ্য এই ডিভাইসের বাইরে যায় না। প্রতি সপ্তাহে ব্যাকআপ ডাউনলোড করুন, যাতে ফোন বদলালেও কিছু না হারায়।',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'রবিবার,সোমবার,মঙ্গলবার,বুধবার,বৃহস্পতিবার,শুক্রবার,শনিবার',
  wd_min: 'র,সো,ম,বু,বৃ,শু,শ',
  months: 'জানুয়ারি,ফেব্রুয়ারি,মার্চ,এপ্রিল,মে,জুন,জুলাই,আগস্ট,সেপ্টেম্বর,অক্টোবর,নভেম্বর,ডিসেম্বর'
};

window.APP_STRINGS.mr = {
  app_title: 'हजेरी रजिस्टर',
  intro: 'काही सेकंदांत वर्गाची हजेरी घ्या, महिन्याची एकूण आणि हजेरीची % पाहा, आणि रजिस्टर प्रिंट करा. सर्व माहिती याच डिव्हाइसवर राहते.',
  tab_day: 'दैनिक',
  tab_month: 'मासिक',
  tab_students: 'विद्यार्थी',
  class_label: 'वर्ग',
  date_label: 'तारीख',
  today: 'आज',
  prev_day: 'मागचा दिवस',
  next_day: 'पुढचा दिवस',
  prev_month: 'मागचा महिना',
  next_month: 'पुढचा महिना',
  st_P: 'हजर',
  st_A: 'गैरहजर',
  st_T: 'उशिरा',
  st_V: 'रजा',
  st_none: 'बाकी',
  sh_P: 'ह',
  sh_A: 'गै',
  sh_T: 'उ',
  sh_V: 'र',
  sh_H: 'सु',
  holiday: 'सुट्टी',
  mark_all: 'सर्वांना हजर करा',
  marked_present: '{n} विद्यार्थी हजर नोंदवले.',
  all_marked: 'सर्वांची हजेरी आधीच लागली आहे.',
  clear_day: 'हा दिवस पुसा',
  confirm_clear_day: '{date} ची सर्व हजेरी पुसायची?',
  copy_absent: 'गैरहजर यादी कॉपी करा',
  absent_text: '{cls} · {date} · गैरहजर ({n}): {list}',
  none_absent: 'या दिवशी कोणीही गैरहजर नाही.',
  marked_n: '{total} पैकी {n} जणांची हजेरी लागली',
  tap_hint: 'बदलण्यासाठी नावावर टॅप करा: हजर → गैरहजर → उशिरा → रजा → बाकी.',
  search_ph: 'नाव किंवा रोल नंबर शोधा',
  no_match: '“{q}” शी जुळणारा विद्यार्थी सापडला नाही.',
  holiday_sunday: 'रविवारची सुट्टी आहे.',
  holiday_national: 'ही राष्ट्रीय सुट्टी आहे.',
  holiday_marked: 'हा दिवस सुट्टी म्हणून नोंदवला आहे.',
  take_anyway: 'या दिवशीही हजेरी घ्या',
  make_holiday: 'सुट्टी जाहीर करा',
  future_note: 'ही तारीख अजून यायची आहे.',
  no_students: 'या वर्गात अजून एकही विद्यार्थी नाही.',
  go_students: 'विद्यार्थी जोडा',
  sample_note: 'हा नमुना वर्ग आहे आणि त्याची हजेरी काल्पनिक आहे, म्हणजे तुम्ही ॲप वापरून पाहू शकता. “विद्यार्थी” टॅबमध्ये तुमचा वर्ग जोडा आणि मग नमुना काढून टाका.',
  sample_class: 'नमुना · इयत्ता 6 अ',
  sample_names: 'आरव पाटील,अनन्या कुलकर्णी,अर्जुन जाधव,दिया शिंदे,फातिमा शेख,गौरव पवार,ईशान देशमुख,काव्या जोशी,लक्ष्मी गायकवाड,मोहम्मद अन्सारी,नेहा भोसले,प्रणव देशपांडे,प्रिया चव्हाण,राहुल मोरे,रिया कदम,रोहन साळुंखे,सना पठाण,सिद्धार्थ गोखले,तन्वी नाईक,विक्रम सावंत',
  my_class: 'माझा वर्ग',
  month_hint: 'हजेरी बदलण्यासाठी चौकोनावर टॅप करा. वरच्या तारखेवर टॅप करून तो दिवस सुट्टी करा, किंवा पुन्हा शाळेचा दिवस करा.',
  sundays_off: 'रविवार आणि राष्ट्रीय सुट्ट्या (26 जानेवारी, 15 ऑगस्ट, 2 ऑक्टोबर) सुट्टी',
  leave_counts: 'रजा हजर म्हणून मोजा',
  min_pct: 'किमान हजेरी %',
  late_note: 'उशिरा आलेले हजर म्हणून मोजले जातात.',
  leave_note: 'रजा देखील हजर म्हणून मोजली जाते.',
  col_roll: 'रोल',
  col_name: 'नाव',
  col_days: 'दिवस',
  col_pct: '%',
  stat_days: 'हजेरी घेतलेले दिवस',
  stat_avg: 'वर्गाची सरासरी',
  stat_below: '{p}% पेक्षा कमी असलेले विद्यार्थी',
  day_present: 'दररोज हजर',
  export_csv: 'CSV काढा',
  print_register: 'रजिस्टर प्रिंट करा',
  print_meta: 'वर्ग: {cls} · महिना: {month}',
  printed_on: 'प्रिंटची तारीख: {date}',
  sign_teacher: 'वर्गशिक्षक',
  sign_principal: 'मुख्याध्यापक',
  school_name: 'शाळेचे नाव (प्रिंट केलेल्या रजिस्टरवर दिसेल)',
  school_ph: 'उदा. जिल्हा परिषद शाळा, सातारा',
  class_settings: 'हा वर्ग',
  class_name: 'वर्गाचे नाव',
  class_ph: 'उदा. इयत्ता 7 ब',
  delete_class: 'हा वर्ग काढून टाका',
  confirm_delete_class: '“{name}” आणि त्याची सर्व हजेरी काढून टाकायची? हे परत आणता येणार नाही.',
  new_class: 'नवीन वर्ग जोडा',
  add_class: 'वर्ग जोडा',
  class_added: '“{name}” वर्ग जोडला.',
  renamed: 'वर्गाचे नाव सेव्ह झाले.',
  students_n: '{n} विद्यार्थी',
  add_student: 'एक विद्यार्थी जोडा',
  roll_ph: 'रोल',
  name_ph: 'विद्यार्थ्याचे नाव',
  paste_title: 'विद्यार्थ्यांची यादी पेस्ट करा',
  paste_help: 'प्रत्येक ओळीत एक विद्यार्थी: आधी रोल नंबर, मग नाव. फक्त नाव असलेल्या ओळीला पुढचा रोल नंबर मिळेल. Excel किंवा Google Sheets मधून दोन कॉलम थेट कॉपी करू शकता.',
  paste_ph: 'उदा.\n1, आरव पाटील\n2, फातिमा शेख\nरोहन मोरे',
  paste_add: 'हे विद्यार्थी जोडा',
  import_csv: 'CSV इम्पोर्ट करा',
  csv_help: 'किंवा रोल नंबर आणि नाव असलेली CSV फाइल इम्पोर्ट करा. शीर्षकाची ओळ आपोआप वगळली जाते.',
  added_n: '{n} विद्यार्थी जोडले.',
  nothing_added: 'एकही नाव सापडले नाही. लिहिण्याची पद्धत तपासा.',
  dup_rolls: 'हे रोल नंबर एकापेक्षा जास्त वेळा आहेत: {list}',
  remove_student: '{name} यांना काढा',
  confirm_remove: '{name} यांना काढायचे? या वर्गातील त्यांची हजेरीही पुसली जाईल.',
  need_name: 'कृपया नाव लिहा.',
  backup_title: 'बॅकअप आणि रिस्टोअर',
  backup_help: 'हजेरी फक्त याच ब्राउझरमध्ये सेव्ह होते. दर आठवड्याला बॅकअप डाउनलोड करा आणि नवीन फोन किंवा कॉम्प्युटरवर तो रिस्टोअर करा.',
  backup_dl: 'बॅकअप डाउनलोड करा',
  restore: 'बॅकअप रिस्टोअर करा',
  restore_ok: 'बॅकअप रिस्टोअर झाला: {n} वर्ग.',
  restore_bad: 'ही हजेरी रजिस्टरची बॅकअप फाइल नाही.',
  confirm_restore: 'या डिव्हाइसवरील सर्व वर्गांच्या जागी बॅकअपमधील वर्ग ठेवायचे?',
  help_1: 'तुम्ही शिकवता त्या प्रत्येक तुकडीसाठी वेगळा वर्ग बनवा. शाळेच्या यादीतून नावे पेस्ट करा किंवा CSV फाइल इम्पोर्ट करा.',
  help_2: 'रोज सकाळी “सर्वांना हजर करा” दाबा, मग फक्त गैरहजर विद्यार्थ्यांच्या नावावर टॅप करा. 60 विद्यार्थ्यांची हजेरीही एका मिनिटापेक्षा कमी वेळात होते.',
  help_3: '“मासिक” टॅबमध्ये प्रत्येक विद्यार्थ्याची हजेरी % दिसते. लाल ओळी किमानपेक्षा कमी आहेत (CBSE नुसार 75% आवश्यक), म्हणजे तुम्ही वेळेत पालकांशी बोलू शकता.',
  help_4: 'महिन्याच्या शेवटी रजिस्टर प्रिंट करा (A4 आडवे पान) आणि सही करा, किंवा Excel / Google Sheets साठी CSV काढा.',
  help_5: 'वर्गातील उपक्रम: वर्ग मॉनिटरला स्मार्टबोर्डवर हजेरी घेऊ द्या. मग विद्यार्थ्यांनी स्वतःची हजेरी % काढावी: (हजर दिवस ÷ शाळेचे दिवस) × 100.',
  help_6: 'तुमची माहिती या डिव्हाइसबाहेर जात नाही. दर आठवड्याला बॅकअप डाउनलोड करा, म्हणजे फोन बदलला तरी काही हरवणार नाही.',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'रविवार,सोमवार,मंगळवार,बुधवार,गुरुवार,शुक्रवार,शनिवार',
  wd_min: 'र,सो,मं,बु,गु,शु,श',
  months: 'जानेवारी,फेब्रुवारी,मार्च,एप्रिल,मे,जून,जुलै,ऑगस्ट,सप्टेंबर,ऑक्टोबर,नोव्हेंबर,डिसेंबर'
};

window.APP_STRINGS.gu = {
  app_title: 'હાજરી પત્રક',
  intro: 'થોડી સેકન્ડમાં વર્ગની હાજરી લો, મહિનાનો કુલ અને હાજરીની % જુઓ, અને પત્રક પ્રિન્ટ કરો. બધી માહિતી આ જ ડિવાઇસ પર રહે છે.',
  tab_day: 'દૈનિક',
  tab_month: 'માસિક',
  tab_students: 'વિદ્યાર્થીઓ',
  class_label: 'વર્ગ',
  date_label: 'તારીખ',
  today: 'આજે',
  prev_day: 'પાછલો દિવસ',
  next_day: 'આગલો દિવસ',
  prev_month: 'પાછલો મહિનો',
  next_month: 'આગલો મહિનો',
  st_P: 'હાજર',
  st_A: 'ગેરહાજર',
  st_T: 'મોડા',
  st_V: 'રજા',
  st_none: 'બાકી',
  sh_P: 'હા',
  sh_A: 'ગે',
  sh_T: 'મો',
  sh_V: 'ર',
  sh_H: 'છુ',
  holiday: 'છુટ્ટી',
  mark_all: 'બધાને હાજર કરો',
  marked_present: '{n} વિદ્યાર્થીઓને હાજર કર્યા.',
  all_marked: 'બધાની હાજરી પહેલેથી પુરાઈ ગઈ છે.',
  clear_day: 'આ દિવસ ભૂંસો',
  confirm_clear_day: '{date}ની બધી હાજરી ભૂંસી નાખવી છે?',
  copy_absent: 'ગેરહાજર યાદી કૉપિ કરો',
  absent_text: '{cls} · {date} · ગેરહાજર ({n}): {list}',
  none_absent: 'આ દિવસે કોઈ ગેરહાજર નથી.',
  marked_n: '{total}માંથી {n}ની હાજરી પુરાઈ',
  tap_hint: 'બદલવા માટે નામ પર ટૅપ કરો: હાજર → ગેરહાજર → મોડા → રજા → બાકી.',
  search_ph: 'નામ કે રોલ નંબર શોધો',
  no_match: '“{q}” સાથે કોઈ વિદ્યાર્થી મળ્યો નથી.',
  holiday_sunday: 'રવિવારની રજા છે.',
  holiday_national: 'આ રાષ્ટ્રીય રજાનો દિવસ છે.',
  holiday_marked: 'આ દિવસ રજા તરીકે નોંધાયેલો છે.',
  take_anyway: 'આ દિવસે પણ હાજરી લો',
  make_holiday: 'રજા જાહેર કરો',
  future_note: 'આ તારીખ હજી આવવાની બાકી છે.',
  no_students: 'આ વર્ગમાં હજી કોઈ વિદ્યાર્થી નથી.',
  go_students: 'વિદ્યાર્થીઓ ઉમેરો',
  sample_note: 'આ નમૂનાનો વર્ગ છે અને તેની હાજરી કાલ્પનિક છે, જેથી તમે ઍપ અજમાવી શકો. “વિદ્યાર્થીઓ” ટૅબમાં તમારો વર્ગ ઉમેરો, પછી નમૂનો કાઢી નાખો.',
  sample_class: 'નમૂનો · ધોરણ 6 અ',
  sample_names: 'આરવ પટેલ,અનન્યા શાહ,અર્જુન દેસાઈ,દિયા મહેતા,ફાતિમા મન્સૂરી,ગૌરવ ચૌહાણ,ઈશાન જોશી,કાવ્યા ત્રિવેદી,લક્ષ્મી પરમાર,મોહમ્મદ વહોરા,નેહા ભટ્ટ,પ્રણવ વ્યાસ,પ્રિયા સોલંકી,રાહુલ રાઠોડ,રિયા પંડ્યા,રોહન ઠક્કર,સના મેમણ,સિદ્ધાર્થ દવે,તન્વી પરીખ,વિક્રમ જાડેજા',
  my_class: 'મારો વર્ગ',
  month_hint: 'હાજરી બદલવા ખાના પર ટૅપ કરો. ઉપર કોઈ તારીખ પર ટૅપ કરીને તેને રજા બનાવો, અથવા ફરી શાળાનો દિવસ બનાવો.',
  sundays_off: 'રવિવાર અને રાષ્ટ્રીય રજાઓ (26 જાન્યુઆરી, 15 ઑગસ્ટ, 2 ઑક્ટોબર) બંધ',
  leave_counts: 'રજાને હાજર ગણો',
  min_pct: 'ઓછામાં ઓછી હાજરી %',
  late_note: 'મોડા આવનારને હાજર ગણવામાં આવે છે.',
  leave_note: 'રજાને પણ હાજર ગણવામાં આવે છે.',
  col_roll: 'રોલ',
  col_name: 'નામ',
  col_days: 'દિવસ',
  col_pct: '%',
  stat_days: 'જેટલા દિવસ હાજરી લીધી',
  stat_avg: 'વર્ગની સરેરાશ',
  stat_below: '{p}%થી ઓછા વિદ્યાર્થીઓ',
  day_present: 'દરરોજ હાજર',
  export_csv: 'CSV કાઢો',
  print_register: 'પત્રક પ્રિન્ટ કરો',
  print_meta: 'વર્ગ: {cls} · મહિનો: {month}',
  printed_on: 'પ્રિન્ટની તારીખ: {date}',
  sign_teacher: 'વર્ગશિક્ષક',
  sign_principal: 'આચાર્ય',
  school_name: 'શાળાનું નામ (પ્રિન્ટ કરેલા પત્રક પર દેખાશે)',
  school_ph: 'દા.ત. સરકારી માધ્યમિક શાળા, આણંદ',
  class_settings: 'આ વર્ગ',
  class_name: 'વર્ગનું નામ',
  class_ph: 'દા.ત. ધોરણ 7 બ',
  delete_class: 'આ વર્ગ કાઢી નાખો',
  confirm_delete_class: '“{name}” અને તેની બધી હાજરી કાઢી નાખવી છે? આ પાછું નહીં આવે.',
  new_class: 'નવો વર્ગ ઉમેરો',
  add_class: 'વર્ગ ઉમેરો',
  class_added: '“{name}” વર્ગ ઉમેરાયો.',
  renamed: 'વર્ગનું નામ સેવ થયું.',
  students_n: '{n} વિદ્યાર્થીઓ',
  add_student: 'એક વિદ્યાર્થી ઉમેરો',
  roll_ph: 'રોલ',
  name_ph: 'વિદ્યાર્થીનું નામ',
  paste_title: 'વિદ્યાર્થીઓની યાદી પેસ્ટ કરો',
  paste_help: 'દરેક લાઇનમાં એક વિદ્યાર્થી: પહેલા રોલ નંબર, પછી નામ. જે લાઇનમાં ફક્ત નામ હોય તેને આગલો રોલ નંબર મળશે. Excel કે Google Sheetsમાંથી બે કૉલમ સીધા કૉપિ કરી શકો.',
  paste_ph: 'દા.ત.\n1, આરવ પટેલ\n2, ફાતિમા મન્સૂરી\nરોહન દવે',
  paste_add: 'આ વિદ્યાર્થીઓ ઉમેરો',
  import_csv: 'CSV ઇમ્પોર્ટ કરો',
  csv_help: 'અથવા રોલ નંબર અને નામના કૉલમવાળી CSV ફાઇલ ઇમ્પોર્ટ કરો. મથાળાની લાઇન આપમેળે છોડી દેવાય છે.',
  added_n: '{n} વિદ્યાર્થીઓ ઉમેરાયા.',
  nothing_added: 'કોઈ નામ મળ્યું નથી. લખવાની રીત તપાસો.',
  dup_rolls: 'આ રોલ નંબર એકથી વધુ વાર છે: {list}',
  remove_student: '{name}ને કાઢો',
  confirm_remove: '{name}ને કાઢવા છે? આ વર્ગમાં તેમની હાજરી પણ ભૂંસાઈ જશે.',
  need_name: 'કૃપા કરીને નામ લખો.',
  backup_title: 'બૅકઅપ અને રિસ્ટોર',
  backup_help: 'હાજરી ફક્ત આ બ્રાઉઝરમાં જ સેવ થાય છે. દર અઠવાડિયે બૅકઅપ ડાઉનલોડ કરો, અને નવા ફોન કે કમ્પ્યુટર પર તેને રિસ્ટોર કરો.',
  backup_dl: 'બૅકઅપ ડાઉનલોડ કરો',
  restore: 'બૅકઅપ રિસ્ટોર કરો',
  restore_ok: 'બૅકઅપ રિસ્ટોર થયો: {n} વર્ગ.',
  restore_bad: 'આ હાજરી પત્રકની બૅકઅપ ફાઇલ નથી.',
  confirm_restore: 'આ ડિવાઇસના બધા વર્ગોની જગ્યાએ બૅકઅપના વર્ગો મૂકવા છે?',
  help_1: 'તમે ભણાવો છો તે દરેક વર્ગ-વિભાગ માટે અલગ વર્ગ બનાવો. શાળાની યાદીમાંથી નામ પેસ્ટ કરો અથવા CSV ફાઇલ ઇમ્પોર્ટ કરો.',
  help_2: 'રોજ સવારે “બધાને હાજર કરો” દબાવો, પછી ફક્ત ગેરહાજર વિદ્યાર્થીઓનાં નામ પર ટૅપ કરો. 60 વિદ્યાર્થીઓની હાજરી પણ એક મિનિટથી ઓછા સમયમાં થઈ જાય.',
  help_3: '“માસિક” ટૅબમાં દરેક વિદ્યાર્થીની હાજરી % દેખાય છે. લાલ લાઇનો ઓછામાં ઓછી મર્યાદાથી નીચે છે (CBSE મુજબ 75% જરૂરી), જેથી તમે સમયસર વાલીઓ સાથે વાત કરી શકો.',
  help_4: 'મહિનાના અંતે પત્રક પ્રિન્ટ કરો (A4 આડું પાનું) અને સહી કરો, અથવા Excel / Google Sheets માટે CSV કાઢો.',
  help_5: 'વર્ગ પ્રવૃત્તિ: વર્ગ મૉનિટરને સ્માર્ટબોર્ડ પર હાજરી લેવા દો. પછી વિદ્યાર્થીઓ પોતાની હાજરી % ગણે: (હાજર દિવસ ÷ શાળાના દિવસ) × 100.',
  help_6: 'તમારી માહિતી આ ડિવાઇસની બહાર જતી નથી. દર અઠવાડિયે બૅકઅપ ડાઉનલોડ કરો, જેથી ફોન બદલાય તોય કંઈ ન ખોવાય.',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'રવિવાર,સોમવાર,મંગળવાર,બુધવાર,ગુરુવાર,શુક્રવાર,શનિવાર',
  wd_min: 'ર,સો,મં,બુ,ગુ,શુ,શ',
  months: 'જાન્યુઆરી,ફેબ્રુઆરી,માર્ચ,એપ્રિલ,મે,જૂન,જુલાઈ,ઑગસ્ટ,સપ્ટેમ્બર,ઑક્ટોબર,નવેમ્બર,ડિસેમ્બર'
};

window.APP_STRINGS.pa = {
  app_title: 'ਹਾਜ਼ਰੀ ਰਜਿਸਟਰ',
  intro: 'ਕੁਝ ਸਕਿੰਟਾਂ ਵਿੱਚ ਜਮਾਤ ਦੀ ਹਾਜ਼ਰੀ ਲਓ, ਮਹੀਨੇ ਦਾ ਕੁੱਲ ਅਤੇ ਹਾਜ਼ਰੀ % ਦੇਖੋ, ਅਤੇ ਰਜਿਸਟਰ ਪ੍ਰਿੰਟ ਕਰੋ। ਸਾਰਾ ਡਾਟਾ ਇਸੇ ਡਿਵਾਈਸ ’ਤੇ ਰਹਿੰਦਾ ਹੈ।',
  tab_day: 'ਰੋਜ਼ਾਨਾ',
  tab_month: 'ਮਹੀਨਾ',
  tab_students: 'ਵਿਦਿਆਰਥੀ',
  class_label: 'ਜਮਾਤ',
  date_label: 'ਤਾਰੀਖ਼',
  today: 'ਅੱਜ',
  prev_day: 'ਪਿਛਲਾ ਦਿਨ',
  next_day: 'ਅਗਲਾ ਦਿਨ',
  prev_month: 'ਪਿਛਲਾ ਮਹੀਨਾ',
  next_month: 'ਅਗਲਾ ਮਹੀਨਾ',
  st_P: 'ਹਾਜ਼ਰ',
  st_A: 'ਗ਼ੈਰਹਾਜ਼ਰ',
  st_T: 'ਦੇਰੀ ਨਾਲ',
  st_V: 'ਛੁੱਟੀ',
  st_none: 'ਬਾਕੀ',
  sh_P: 'ਹਾ',
  sh_A: 'ਗ਼ੈ',
  sh_T: 'ਦੇ',
  sh_V: 'ਛੁ',
  sh_H: 'ਬੰ',
  holiday: 'ਬੰਦ',
  mark_all: 'ਸਭ ਨੂੰ ਹਾਜ਼ਰ ਲਾਓ',
  marked_present: '{n} ਵਿਦਿਆਰਥੀ ਹਾਜ਼ਰ ਲਾਏ ਗਏ।',
  all_marked: 'ਸਭ ਦੀ ਹਾਜ਼ਰੀ ਪਹਿਲਾਂ ਹੀ ਲੱਗੀ ਹੋਈ ਹੈ।',
  clear_day: 'ਇਹ ਦਿਨ ਮਿਟਾਓ',
  confirm_clear_day: '{date} ਦੀ ਸਾਰੀ ਹਾਜ਼ਰੀ ਮਿਟਾ ਦੇਈਏ?',
  copy_absent: 'ਗ਼ੈਰਹਾਜ਼ਰ ਸੂਚੀ ਕਾਪੀ ਕਰੋ',
  absent_text: '{cls} · {date} · ਗ਼ੈਰਹਾਜ਼ਰ ({n}): {list}',
  none_absent: 'ਇਸ ਦਿਨ ਕੋਈ ਗ਼ੈਰਹਾਜ਼ਰ ਨਹੀਂ।',
  marked_n: '{total} ਵਿੱਚੋਂ {n} ਦੀ ਹਾਜ਼ਰੀ ਲੱਗੀ',
  tap_hint: 'ਬਦਲਣ ਲਈ ਨਾਂ ’ਤੇ ਟੈਪ ਕਰੋ: ਹਾਜ਼ਰ → ਗ਼ੈਰਹਾਜ਼ਰ → ਦੇਰੀ ਨਾਲ → ਛੁੱਟੀ → ਬਾਕੀ।',
  search_ph: 'ਨਾਂ ਜਾਂ ਰੋਲ ਨੰਬਰ ਖੋਜੋ',
  no_match: '“{q}” ਨਾਲ ਕੋਈ ਵਿਦਿਆਰਥੀ ਨਹੀਂ ਮਿਲਿਆ।',
  holiday_sunday: 'ਐਤਵਾਰ ਦੀ ਛੁੱਟੀ ਹੈ।',
  holiday_national: 'ਇਹ ਕੌਮੀ ਛੁੱਟੀ ਦਾ ਦਿਨ ਹੈ।',
  holiday_marked: 'ਇਹ ਦਿਨ ਛੁੱਟੀ ਵਜੋਂ ਲਗਾਇਆ ਹੋਇਆ ਹੈ।',
  take_anyway: 'ਇਸ ਦਿਨ ਵੀ ਹਾਜ਼ਰੀ ਲਓ',
  make_holiday: 'ਛੁੱਟੀ ਐਲਾਨੋ',
  future_note: 'ਇਹ ਤਾਰੀਖ਼ ਅਜੇ ਆਉਣੀ ਹੈ।',
  no_students: 'ਇਸ ਜਮਾਤ ਵਿੱਚ ਅਜੇ ਕੋਈ ਵਿਦਿਆਰਥੀ ਨਹੀਂ ਹੈ।',
  go_students: 'ਵਿਦਿਆਰਥੀ ਜੋੜੋ',
  sample_note: 'ਇਹ ਨਮੂਨੇ ਦੀ ਜਮਾਤ ਹੈ, ਇਸ ਦੀ ਹਾਜ਼ਰੀ ਬਣਾਉਟੀ ਹੈ ਤਾਂ ਜੋ ਤੁਸੀਂ ਐਪ ਵਰਤ ਕੇ ਦੇਖ ਸਕੋ। “ਵਿਦਿਆਰਥੀ” ਟੈਬ ਵਿੱਚ ਆਪਣੀ ਜਮਾਤ ਜੋੜੋ, ਫਿਰ ਨਮੂਨਾ ਮਿਟਾ ਦਿਓ।',
  sample_class: 'ਨਮੂਨਾ · ਛੇਵੀਂ ਜਮਾਤ ਏ',
  sample_names: 'ਅਰਜਨ ਸਿੰਘ,ਅਨੰਨਿਆ ਸ਼ਰਮਾ,ਅਮਨਦੀਪ ਕੌਰ,ਦੀਆ ਅਰੋੜਾ,ਫ਼ਾਤਿਮਾ ਖ਼ਾਨ,ਗੁਰਪ੍ਰੀਤ ਸਿੰਘ,ਇਸ਼ਾਨ ਵਰਮਾ,ਹਰਲੀਨ ਕੌਰ,ਜਸਪ੍ਰੀਤ ਗਿੱਲ,ਮੁਹੰਮਦ ਅਲੀ,ਨੇਹਾ ਗੁਪਤਾ,ਪ੍ਰਭਜੋਤ ਸੰਧੂ,ਪ੍ਰਿਆ ਬਾਜਵਾ,ਰਾਹੁਲ ਕੁਮਾਰ,ਰੀਆ ਮਲਹੋਤਰਾ,ਰੋਹਨ ਸੈਣੀ,ਸਿਮਰਨ ਢਿੱਲੋਂ,ਸੁਖਮਨ ਬਰਾੜ,ਤਨਵੀ ਚੋਪੜਾ,ਵਿਕਰਮ ਗਰੇਵਾਲ',
  my_class: 'ਮੇਰੀ ਜਮਾਤ',
  month_hint: 'ਹਾਜ਼ਰੀ ਬਦਲਣ ਲਈ ਖਾਨੇ ’ਤੇ ਟੈਪ ਕਰੋ। ਉੱਪਰ ਕਿਸੇ ਤਾਰੀਖ਼ ’ਤੇ ਟੈਪ ਕਰਕੇ ਉਸ ਨੂੰ ਛੁੱਟੀ ਬਣਾਓ, ਜਾਂ ਮੁੜ ਸਕੂਲ ਦਾ ਦਿਨ ਬਣਾਓ।',
  sundays_off: 'ਐਤਵਾਰ ਅਤੇ ਕੌਮੀ ਛੁੱਟੀਆਂ (26 ਜਨਵਰੀ, 15 ਅਗਸਤ, 2 ਅਕਤੂਬਰ) ਬੰਦ',
  leave_counts: 'ਛੁੱਟੀ ਨੂੰ ਹਾਜ਼ਰ ਗਿਣੋ',
  min_pct: 'ਘੱਟੋ-ਘੱਟ ਹਾਜ਼ਰੀ %',
  late_note: 'ਦੇਰੀ ਨਾਲ ਆਏ ਵਿਦਿਆਰਥੀ ਹਾਜ਼ਰ ਗਿਣੇ ਜਾਂਦੇ ਹਨ।',
  leave_note: 'ਛੁੱਟੀ ਨੂੰ ਵੀ ਹਾਜ਼ਰ ਗਿਣਿਆ ਜਾਂਦਾ ਹੈ।',
  col_roll: 'ਰੋਲ',
  col_name: 'ਨਾਂ',
  col_days: 'ਦਿਨ',
  col_pct: '%',
  stat_days: 'ਜਿੰਨੇ ਦਿਨ ਹਾਜ਼ਰੀ ਲਈ ਗਈ',
  stat_avg: 'ਜਮਾਤ ਦੀ ਔਸਤ',
  stat_below: '{p}% ਤੋਂ ਘੱਟ ਵਾਲੇ ਵਿਦਿਆਰਥੀ',
  day_present: 'ਹਰ ਦਿਨ ਹਾਜ਼ਰ',
  export_csv: 'CSV ਕੱਢੋ',
  print_register: 'ਰਜਿਸਟਰ ਪ੍ਰਿੰਟ ਕਰੋ',
  print_meta: 'ਜਮਾਤ: {cls} · ਮਹੀਨਾ: {month}',
  printed_on: 'ਪ੍ਰਿੰਟ ਦੀ ਤਾਰੀਖ਼: {date}',
  sign_teacher: 'ਜਮਾਤ ਇੰਚਾਰਜ',
  sign_principal: 'ਪ੍ਰਿੰਸੀਪਲ',
  school_name: 'ਸਕੂਲ ਦਾ ਨਾਂ (ਪ੍ਰਿੰਟ ਕੀਤੇ ਰਜਿਸਟਰ ’ਤੇ ਦਿਖੇਗਾ)',
  school_ph: 'ਜਿਵੇਂ: ਸਰਕਾਰੀ ਸੀਨੀਅਰ ਸੈਕੰਡਰੀ ਸਕੂਲ, ਲੁਧਿਆਣਾ',
  class_settings: 'ਇਹ ਜਮਾਤ',
  class_name: 'ਜਮਾਤ ਦਾ ਨਾਂ',
  class_ph: 'ਜਿਵੇਂ: ਸੱਤਵੀਂ ਬੀ',
  delete_class: 'ਇਹ ਜਮਾਤ ਮਿਟਾਓ',
  confirm_delete_class: '“{name}” ਅਤੇ ਉਸ ਦੀ ਸਾਰੀ ਹਾਜ਼ਰੀ ਮਿਟਾ ਦੇਈਏ? ਇਹ ਵਾਪਸ ਨਹੀਂ ਆਵੇਗੀ।',
  new_class: 'ਨਵੀਂ ਜਮਾਤ ਜੋੜੋ',
  add_class: 'ਜਮਾਤ ਜੋੜੋ',
  class_added: '“{name}” ਜਮਾਤ ਜੁੜ ਗਈ।',
  renamed: 'ਜਮਾਤ ਦਾ ਨਾਂ ਸੇਵ ਹੋ ਗਿਆ।',
  students_n: '{n} ਵਿਦਿਆਰਥੀ',
  add_student: 'ਇੱਕ ਵਿਦਿਆਰਥੀ ਜੋੜੋ',
  roll_ph: 'ਰੋਲ',
  name_ph: 'ਵਿਦਿਆਰਥੀ ਦਾ ਨਾਂ',
  paste_title: 'ਵਿਦਿਆਰਥੀਆਂ ਦੀ ਸੂਚੀ ਪੇਸਟ ਕਰੋ',
  paste_help: 'ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ ਵਿਦਿਆਰਥੀ: ਪਹਿਲਾਂ ਰੋਲ ਨੰਬਰ, ਫਿਰ ਨਾਂ। ਜਿਸ ਲਾਈਨ ਵਿੱਚ ਸਿਰਫ਼ ਨਾਂ ਹੈ, ਉਸ ਨੂੰ ਅਗਲਾ ਰੋਲ ਨੰਬਰ ਮਿਲ ਜਾਵੇਗਾ। Excel ਜਾਂ Google Sheets ਤੋਂ ਦੋ ਕਾਲਮ ਸਿੱਧੇ ਕਾਪੀ ਕਰ ਸਕਦੇ ਹੋ।',
  paste_ph: 'ਜਿਵੇਂ:\n1, ਅਰਜਨ ਸਿੰਘ\n2, ਫ਼ਾਤਿਮਾ ਖ਼ਾਨ\nਰੋਹਨ ਸੈਣੀ',
  paste_add: 'ਇਹ ਵਿਦਿਆਰਥੀ ਜੋੜੋ',
  import_csv: 'CSV ਇੰਪੋਰਟ ਕਰੋ',
  csv_help: 'ਜਾਂ ਰੋਲ ਨੰਬਰ ਅਤੇ ਨਾਂ ਦੇ ਕਾਲਮਾਂ ਵਾਲੀ CSV ਫ਼ਾਈਲ ਇੰਪੋਰਟ ਕਰੋ। ਸਿਰਲੇਖ ਵਾਲੀ ਲਾਈਨ ਆਪਣੇ-ਆਪ ਛੱਡ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ।',
  added_n: '{n} ਵਿਦਿਆਰਥੀ ਜੁੜ ਗਏ।',
  nothing_added: 'ਕੋਈ ਨਾਂ ਨਹੀਂ ਮਿਲਿਆ। ਲਿਖਣ ਦਾ ਤਰੀਕਾ ਜਾਂਚੋ।',
  dup_rolls: 'ਇਹ ਰੋਲ ਨੰਬਰ ਇੱਕ ਤੋਂ ਵੱਧ ਵਾਰ ਹਨ: {list}',
  remove_student: '{name} ਨੂੰ ਹਟਾਓ',
  confirm_remove: '{name} ਨੂੰ ਹਟਾਈਏ? ਇਸ ਜਮਾਤ ਵਿੱਚ ਉਸ ਦੀ ਹਾਜ਼ਰੀ ਵੀ ਮਿਟ ਜਾਵੇਗੀ।',
  need_name: 'ਕਿਰਪਾ ਕਰਕੇ ਨਾਂ ਲਿਖੋ।',
  backup_title: 'ਬੈਕਅੱਪ ਅਤੇ ਰੀਸਟੋਰ',
  backup_help: 'ਹਾਜ਼ਰੀ ਸਿਰਫ਼ ਇਸੇ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਸੇਵ ਹੁੰਦੀ ਹੈ। ਹਰ ਹਫ਼ਤੇ ਬੈਕਅੱਪ ਡਾਊਨਲੋਡ ਕਰੋ, ਅਤੇ ਨਵੇਂ ਫ਼ੋਨ ਜਾਂ ਕੰਪਿਊਟਰ ’ਤੇ ਰੀਸਟੋਰ ਕਰੋ।',
  backup_dl: 'ਬੈਕਅੱਪ ਡਾਊਨਲੋਡ ਕਰੋ',
  restore: 'ਬੈਕਅੱਪ ਰੀਸਟੋਰ ਕਰੋ',
  restore_ok: 'ਬੈਕਅੱਪ ਰੀਸਟੋਰ ਹੋ ਗਿਆ: {n} ਜਮਾਤਾਂ।',
  restore_bad: 'ਇਹ ਹਾਜ਼ਰੀ ਰਜਿਸਟਰ ਦੀ ਬੈਕਅੱਪ ਫ਼ਾਈਲ ਨਹੀਂ ਹੈ।',
  confirm_restore: 'ਇਸ ਡਿਵਾਈਸ ਦੀਆਂ ਸਾਰੀਆਂ ਜਮਾਤਾਂ ਦੀ ਥਾਂ ਬੈਕਅੱਪ ਵਾਲੀਆਂ ਜਮਾਤਾਂ ਰੱਖ ਦੇਈਏ?',
  help_1: 'ਤੁਸੀਂ ਜਿੰਨੇ ਸੈਕਸ਼ਨ ਪੜ੍ਹਾਉਂਦੇ ਹੋ, ਹਰ ਇੱਕ ਦੀ ਵੱਖਰੀ ਜਮਾਤ ਬਣਾਓ। ਸਕੂਲ ਦੀ ਸੂਚੀ ਤੋਂ ਨਾਂ ਪੇਸਟ ਕਰੋ ਜਾਂ CSV ਫ਼ਾਈਲ ਇੰਪੋਰਟ ਕਰੋ।',
  help_2: 'ਰੋਜ਼ ਸਵੇਰੇ “ਸਭ ਨੂੰ ਹਾਜ਼ਰ ਲਾਓ” ਦਬਾਓ, ਫਿਰ ਸਿਰਫ਼ ਗ਼ੈਰਹਾਜ਼ਰ ਵਿਦਿਆਰਥੀਆਂ ’ਤੇ ਟੈਪ ਕਰੋ। 60 ਵਿਦਿਆਰਥੀਆਂ ਦੀ ਹਾਜ਼ਰੀ ਵੀ ਇੱਕ ਮਿੰਟ ਤੋਂ ਘੱਟ ਵਿੱਚ ਲੱਗ ਜਾਂਦੀ ਹੈ।',
  help_3: '“ਮਹੀਨਾ” ਟੈਬ ਵਿੱਚ ਹਰ ਵਿਦਿਆਰਥੀ ਦੀ ਹਾਜ਼ਰੀ % ਦਿਖਦੀ ਹੈ। ਲਾਲ ਲਾਈਨਾਂ ਘੱਟੋ-ਘੱਟ ਤੋਂ ਹੇਠਾਂ ਹਨ (CBSE ਮੁਤਾਬਕ 75% ਲਾਜ਼ਮੀ), ਤਾਂ ਜੋ ਤੁਸੀਂ ਸਮੇਂ ਸਿਰ ਮਾਪਿਆਂ ਨਾਲ ਗੱਲ ਕਰ ਸਕੋ।',
  help_4: 'ਮਹੀਨੇ ਦੇ ਅਖੀਰ ’ਤੇ ਰਜਿਸਟਰ ਪ੍ਰਿੰਟ ਕਰੋ (A4 ਲੇਟਵਾਂ ਪੰਨਾ) ਅਤੇ ਦਸਤਖ਼ਤ ਕਰੋ, ਜਾਂ Excel / Google Sheets ਲਈ CSV ਕੱਢੋ।',
  help_5: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: ਜਮਾਤ ਦੇ ਮਾਨੀਟਰ ਨੂੰ ਸਮਾਰਟਬੋਰਡ ’ਤੇ ਹਾਜ਼ਰੀ ਲਾਉਣ ਦਿਓ। ਫਿਰ ਵਿਦਿਆਰਥੀ ਆਪਣੀ ਹਾਜ਼ਰੀ % ਆਪ ਕੱਢਣ: (ਹਾਜ਼ਰ ਦਿਨ ÷ ਸਕੂਲ ਦੇ ਦਿਨ) × 100।',
  help_6: 'ਤੁਹਾਡਾ ਡਾਟਾ ਇਸ ਡਿਵਾਈਸ ਤੋਂ ਬਾਹਰ ਨਹੀਂ ਜਾਂਦਾ। ਹਰ ਹਫ਼ਤੇ ਬੈਕਅੱਪ ਡਾਊਨਲੋਡ ਕਰੋ, ਤਾਂ ਜੋ ਫ਼ੋਨ ਬਦਲਣ ’ਤੇ ਕੁਝ ਨਾ ਗੁਆਚੇ।',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'ਐਤਵਾਰ,ਸੋਮਵਾਰ,ਮੰਗਲਵਾਰ,ਬੁੱਧਵਾਰ,ਵੀਰਵਾਰ,ਸ਼ੁੱਕਰਵਾਰ,ਸ਼ਨਿੱਚਰਵਾਰ',
  wd_min: 'ਐ,ਸੋ,ਮੰ,ਬੁੱ,ਵੀ,ਸ਼ੁੱ,ਸ਼',
  months: 'ਜਨਵਰੀ,ਫ਼ਰਵਰੀ,ਮਾਰਚ,ਅਪ੍ਰੈਲ,ਮਈ,ਜੂਨ,ਜੁਲਾਈ,ਅਗਸਤ,ਸਤੰਬਰ,ਅਕਤੂਬਰ,ਨਵੰਬਰ,ਦਸੰਬਰ'
};

window.APP_STRINGS.or = {
  app_title: 'ହାଜିରା ଖାତା',
  intro: 'କିଛି ସେକେଣ୍ଡରେ ଶ୍ରେଣୀର ହାଜିରା ନିଅନ୍ତୁ, ମାସର ମୋଟ ଓ ହାଜିରା % ଦେଖନ୍ତୁ, ଏବଂ ଖାତା ପ୍ରିଣ୍ଟ କରନ୍ତୁ। ସବୁ ତଥ୍ୟ ଏହି ଡିଭାଇସରେ ହିଁ ରହେ।',
  tab_day: 'ଦୈନିକ',
  tab_month: 'ମାସିକ',
  tab_students: 'ଛାତ୍ରଛାତ୍ରୀ',
  class_label: 'ଶ୍ରେଣୀ',
  date_label: 'ତାରିଖ',
  today: 'ଆଜି',
  prev_day: 'ପୂର୍ବ ଦିନ',
  next_day: 'ପରଦିନ',
  prev_month: 'ପୂର୍ବ ମାସ',
  next_month: 'ପର ମାସ',
  st_P: 'ଉପସ୍ଥିତ',
  st_A: 'ଅନୁପସ୍ଥିତ',
  st_T: 'ବିଳମ୍ବରେ',
  st_V: 'ଛୁଟି',
  st_none: 'ବାକି',
  sh_P: 'ଉ',
  sh_A: 'ଅ',
  sh_T: 'ବି',
  sh_V: 'ଛୁ',
  sh_H: 'ବ',
  holiday: 'ବନ୍ଦ',
  mark_all: 'ସମସ୍ତଙ୍କୁ ଉପସ୍ଥିତ ଦିଅନ୍ତୁ',
  marked_present: '{n} ଜଣଙ୍କୁ ଉପସ୍ଥିତ ଦିଆଗଲା।',
  all_marked: 'ସମସ୍ତଙ୍କ ହାଜିରା ପୂର୍ବରୁ ଦିଆଯାଇଛି।',
  clear_day: 'ଏହି ଦିନ ଲିଭାନ୍ତୁ',
  confirm_clear_day: '{date} ର ସମସ୍ତ ହାଜିରା ଲିଭାଇବେ?',
  copy_absent: 'ଅନୁପସ୍ଥିତ ତାଲିକା କପି କରନ୍ତୁ',
  absent_text: '{cls} · {date} · ଅନୁପସ୍ଥିତ ({n}): {list}',
  none_absent: 'ଏହି ଦିନ କେହି ଅନୁପସ୍ଥିତ ନାହାନ୍ତି।',
  marked_n: '{total} ଜଣଙ୍କ ମଧ୍ୟରୁ {n} ଜଣଙ୍କ ହାଜିରା ହୋଇଛି',
  tap_hint: 'ବଦଳାଇବାକୁ ନାମ ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ: ଉପସ୍ଥିତ → ଅନୁପସ୍ଥିତ → ବିଳମ୍ବରେ → ଛୁଟି → ବାକି।',
  search_ph: 'ନାମ ବା ରୋଲ୍ ନମ୍ବର ଖୋଜନ୍ତୁ',
  no_match: '“{q}” ସହ କୌଣସି ଛାତ୍ରଛାତ୍ରୀ ମିଳିଲେ ନାହିଁ।',
  holiday_sunday: 'ରବିବାର ଛୁଟି ଦିନ।',
  holiday_national: 'ଏହା ଜାତୀୟ ଛୁଟି ଦିନ।',
  holiday_marked: 'ଏହି ଦିନକୁ ଛୁଟି ଭାବେ ରଖାଯାଇଛି।',
  take_anyway: 'ଏହି ଦିନ ବି ହାଜିରା ନିଅନ୍ତୁ',
  make_holiday: 'ଛୁଟି ଘୋଷଣା କରନ୍ତୁ',
  future_note: 'ଏହି ତାରିଖ ଏଯାଏଁ ଆସିନାହିଁ।',
  no_students: 'ଏହି ଶ୍ରେଣୀରେ ଏଯାଏଁ କୌଣସି ଛାତ୍ରଛାତ୍ରୀ ନାହାନ୍ତି।',
  go_students: 'ଛାତ୍ରଛାତ୍ରୀ ଯୋଡ଼ନ୍ତୁ',
  sample_note: 'ଏହା ଏକ ନମୁନା ଶ୍ରେଣୀ, ଏହାର ହାଜିରା କାଳ୍ପନିକ, ଯାହାଦ୍ୱାରା ଆପଣ ଆପ୍ ଚଳାଇ ଦେଖିପାରିବେ। “ଛାତ୍ରଛାତ୍ରୀ” ଟ୍ୟାବରେ ନିଜ ଶ୍ରେଣୀ ଯୋଡ଼ନ୍ତୁ, ତା’ପରେ ନମୁନାଟି ବିଲୋପ କରନ୍ତୁ।',
  sample_class: 'ନମୁନା · ଷଷ୍ଠ ଶ୍ରେଣୀ କ',
  sample_names: 'ଆଦିତ୍ୟ ମହାପାତ୍ର,ଅନନ୍ୟା ମିଶ୍ର,ଅର୍ଜୁନ ସାହୁ,ଦିବ୍ୟା ପଣ୍ଡା,ଫାତିମା ବେଗମ,ଗୌରବ ନାୟକ,ଈଶାନ ଦାଶ,କାବ୍ୟା ମହାନ୍ତି,ଲକ୍ଷ୍ମୀ ବେହେରା,ମହମ୍ମଦ ଆଲି,ନେହା ପଟ୍ଟନାୟକ,ପ୍ରଣବ ରାଉତ,ପ୍ରିୟା ଜେନା,ରାହୁଲ ପ୍ରଧାନ,ରିଆ ସାମଲ,ରୋହନ ମଲ୍ଲିକ,ସନା ଖାତୁନ,ସିଦ୍ଧାର୍ଥ ଷଡ଼ଙ୍ଗୀ,ତନ୍ୱୀ ସ୍ୱାଇଁ,ବିକ୍ରମ ଭୋଇ',
  my_class: 'ମୋ ଶ୍ରେଣୀ',
  month_hint: 'ହାଜିରା ବଦଳାଇବାକୁ ଘର ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ। ଉପରେ କୌଣସି ତାରିଖ ଉପରେ ଟ୍ୟାପ୍ କରି ତାକୁ ଛୁଟି କରନ୍ତୁ, କିମ୍ବା ପୁଣି ସ୍କୁଲ ଦିନ କରନ୍ତୁ।',
  sundays_off: 'ରବିବାର ଓ ଜାତୀୟ ଛୁଟି (26 ଜାନୁଆରୀ, 15 ଅଗଷ୍ଟ, 2 ଅକ୍ଟୋବର) ବନ୍ଦ',
  leave_counts: 'ଛୁଟିକୁ ଉପସ୍ଥିତ ଗଣନ୍ତୁ',
  min_pct: 'ସର୍ବନିମ୍ନ ହାଜିରା %',
  late_note: 'ବିଳମ୍ବରେ ଆସିଲେ ମଧ୍ୟ ଉପସ୍ଥିତ ଗଣାଯାଏ।',
  leave_note: 'ଛୁଟିକୁ ମଧ୍ୟ ଉପସ୍ଥିତ ଗଣାଯାଏ।',
  col_roll: 'ରୋଲ୍',
  col_name: 'ନାମ',
  col_days: 'ଦିନ',
  col_pct: '%',
  stat_days: 'ଯେତେ ଦିନ ହାଜିରା ନିଆଗଲା',
  stat_avg: 'ଶ୍ରେଣୀର ହାରାହାରି',
  stat_below: '{p}% ରୁ କମ୍ ଥିବା ଛାତ୍ରଛାତ୍ରୀ',
  day_present: 'ପ୍ରତିଦିନ ଉପସ୍ଥିତ',
  export_csv: 'CSV ବାହାର କରନ୍ତୁ',
  print_register: 'ଖାତା ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
  print_meta: 'ଶ୍ରେଣୀ: {cls} · ମାସ: {month}',
  printed_on: 'ପ୍ରିଣ୍ଟ ତାରିଖ: {date}',
  sign_teacher: 'ଶ୍ରେଣୀ ଶିକ୍ଷକ',
  sign_principal: 'ପ୍ରଧାନ ଶିକ୍ଷକ',
  school_name: 'ସ୍କୁଲର ନାମ (ପ୍ରିଣ୍ଟ ଖାତାରେ ଦେଖାଯିବ)',
  school_ph: 'ଯେପରି: ସରକାରୀ ଉଚ୍ଚ ବିଦ୍ୟାଳୟ, କଟକ',
  class_settings: 'ଏହି ଶ୍ରେଣୀ',
  class_name: 'ଶ୍ରେଣୀର ନାମ',
  class_ph: 'ଯେପରି: ସପ୍ତମ ଶ୍ରେଣୀ ଖ',
  delete_class: 'ଏହି ଶ୍ରେଣୀ ବିଲୋପ କରନ୍ତୁ',
  confirm_delete_class: '“{name}” ଓ ଏହାର ସମସ୍ତ ହାଜିରା ବିଲୋପ କରିବେ? ଏହା ଆଉ ଫେରିବ ନାହିଁ।',
  new_class: 'ନୂଆ ଶ୍ରେଣୀ ଯୋଡ଼ନ୍ତୁ',
  add_class: 'ଶ୍ରେଣୀ ଯୋଡ଼ନ୍ତୁ',
  class_added: '“{name}” ଶ୍ରେଣୀ ଯୋଡ଼ାଗଲା।',
  renamed: 'ଶ୍ରେଣୀର ନାମ ସେଭ୍ ହେଲା।',
  students_n: '{n} ଜଣ ଛାତ୍ରଛାତ୍ରୀ',
  add_student: 'ଜଣେ ଛାତ୍ର/ଛାତ୍ରୀ ଯୋଡ଼ନ୍ତୁ',
  roll_ph: 'ରୋଲ୍',
  name_ph: 'ଛାତ୍ର/ଛାତ୍ରୀଙ୍କ ନାମ',
  paste_title: 'ଛାତ୍ରଛାତ୍ରୀଙ୍କ ତାଲିକା ପେଷ୍ଟ କରନ୍ତୁ',
  paste_help: 'ପ୍ରତି ଧାଡ଼ିରେ ଜଣେ: ପ୍ରଥମେ ରୋଲ୍ ନମ୍ବର, ତା’ପରେ ନାମ। ଯେଉଁ ଧାଡ଼ିରେ କେବଳ ନାମ ଅଛି, ତାକୁ ପରବର୍ତ୍ତୀ ରୋଲ୍ ନମ୍ବର ମିଳିବ। Excel ବା Google Sheets ରୁ ଦୁଇଟି ସ୍ତମ୍ଭ ସିଧା କପି କରିପାରିବେ।',
  paste_ph: 'ଯେପରି:\n1, ଆଦିତ୍ୟ ମହାପାତ୍ର\n2, ଫାତିମା ବେଗମ\nରୋହନ ଦାଶ',
  paste_add: 'ଏମାନଙ୍କୁ ଯୋଡ଼ନ୍ତୁ',
  import_csv: 'CSV ଇମ୍ପୋର୍ଟ କରନ୍ତୁ',
  csv_help: 'କିମ୍ବା ରୋଲ୍ ନମ୍ବର ଓ ନାମ ସ୍ତମ୍ଭ ଥିବା CSV ଫାଇଲ୍ ଇମ୍ପୋର୍ଟ କରନ୍ତୁ। ଶୀର୍ଷକ ଧାଡ଼ି ନିଜେ ବାଦ୍ ପଡ଼ିଯାଏ।',
  added_n: '{n} ଜଣ ଯୋଡ଼ାଗଲେ।',
  nothing_added: 'କୌଣସି ନାମ ମିଳିଲା ନାହିଁ। ଲେଖିବା ଢଙ୍ଗ ଦେଖନ୍ତୁ।',
  dup_rolls: 'ଏହି ରୋଲ୍ ନମ୍ବର ଏକାଧିକ ଥର ଅଛି: {list}',
  remove_student: '{name} ଙ୍କୁ ହଟାନ୍ତୁ',
  confirm_remove: '{name} ଙ୍କୁ ହଟାଇବେ? ଏହି ଶ୍ରେଣୀରେ ତାଙ୍କ ହାଜିରା ମଧ୍ୟ ଲିଭିଯିବ।',
  need_name: 'ଦୟାକରି ନାମ ଲେଖନ୍ତୁ।',
  backup_title: 'ବ୍ୟାକଅପ୍ ଓ ରିଷ୍ଟୋର୍',
  backup_help: 'ହାଜିରା କେବଳ ଏହି ବ୍ରାଉଜରରେ ସେଭ୍ ହୁଏ। ପ୍ରତି ସପ୍ତାହରେ ବ୍ୟାକଅପ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ, ଏବଂ ନୂଆ ଫୋନ୍ ବା କମ୍ପ୍ୟୁଟରରେ ରିଷ୍ଟୋର୍ କରନ୍ତୁ।',
  backup_dl: 'ବ୍ୟାକଅପ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
  restore: 'ବ୍ୟାକଅପ୍ ରିଷ୍ଟୋର୍ କରନ୍ତୁ',
  restore_ok: 'ବ୍ୟାକଅପ୍ ରିଷ୍ଟୋର୍ ହେଲା: {n}ଟି ଶ୍ରେଣୀ।',
  restore_bad: 'ଏହା ହାଜିରା ଖାତାର ବ୍ୟାକଅପ୍ ଫାଇଲ୍ ନୁହେଁ।',
  confirm_restore: 'ଏହି ଡିଭାଇସର ସମସ୍ତ ଶ୍ରେଣୀ ବଦଳରେ ବ୍ୟାକଅପ୍‌ର ଶ୍ରେଣୀ ରଖିବେ?',
  help_1: 'ଆପଣ ପଢ଼ାଉଥିବା ପ୍ରତ୍ୟେକ ବିଭାଗ ପାଇଁ ଅଲଗା ଶ୍ରେଣୀ ତିଆରି କରନ୍ତୁ। ସ୍କୁଲ ତାଲିକାରୁ ନାମ ପେଷ୍ଟ କରନ୍ତୁ ବା CSV ଫାଇଲ୍ ଇମ୍ପୋର୍ଟ କରନ୍ତୁ।',
  help_2: 'ପ୍ରତିଦିନ ସକାଳେ “ସମସ୍ତଙ୍କୁ ଉପସ୍ଥିତ ଦିଅନ୍ତୁ” ଦବାନ୍ତୁ, ତା’ପରେ କେବଳ ଅନୁପସ୍ଥିତଙ୍କ ନାମରେ ଟ୍ୟାପ୍ କରନ୍ତୁ। 60 ଜଣଙ୍କ ହାଜିରା ମଧ୍ୟ ଏକ ମିନିଟରୁ କମ୍ ସମୟରେ ହୋଇଯାଏ।',
  help_3: '“ମାସିକ” ଟ୍ୟାବରେ ପ୍ରତ୍ୟେକଙ୍କ ହାଜିରା % ଦେଖାଯାଏ। ନାଲି ଧାଡ଼ି ସର୍ବନିମ୍ନରୁ କମ୍ (CBSE ଅନୁସାରେ 75% ଦରକାର), ତେଣୁ ଆପଣ ସମୟ ଥାଉ ଥାଉ ଅଭିଭାବକଙ୍କ ସହ କଥା ହୋଇପାରିବେ।',
  help_4: 'ମାସ ଶେଷରେ ଖାତା ପ୍ରିଣ୍ଟ କରନ୍ତୁ (A4 ଆଡ଼ ପୃଷ୍ଠା) ଓ ଦସ୍ତଖତ କରନ୍ତୁ, କିମ୍ବା Excel / Google Sheets ପାଇଁ CSV ବାହାର କରନ୍ତୁ।',
  help_5: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ: ଶ୍ରେଣୀ ମନିଟରଙ୍କୁ ସ୍ମାର୍ଟବୋର୍ଡରେ ହାଜିରା ନେବାକୁ ଦିଅନ୍ତୁ। ତା’ପରେ ଛାତ୍ରଛାତ୍ରୀ ନିଜ ହାଜିରା % ବାହାର କରନ୍ତୁ: (ଉପସ୍ଥିତ ଦିନ ÷ ସ୍କୁଲ ଦିନ) × 100।',
  help_6: 'ଆପଣଙ୍କ ତଥ୍ୟ ଏହି ଡିଭାଇସ ବାହାରକୁ ଯାଏ ନାହିଁ। ପ୍ରତି ସପ୍ତାହରେ ବ୍ୟାକଅପ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ, ଯାହାଦ୍ୱାରା ଫୋନ୍ ବଦଳିଲେ ବି କିଛି ହଜିବ ନାହିଁ।',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'ରବିବାର,ସୋମବାର,ମଙ୍ଗଳବାର,ବୁଧବାର,ଗୁରୁବାର,ଶୁକ୍ରବାର,ଶନିବାର',
  wd_min: 'ର,ସୋ,ମ,ବୁ,ଗୁ,ଶୁ,ଶ',
  months: 'ଜାନୁଆରୀ,ଫେବୃଆରୀ,ମାର୍ଚ୍ଚ,ଅପ୍ରେଲ,ମେ,ଜୁନ,ଜୁଲାଇ,ଅଗଷ୍ଟ,ସେପ୍ଟେମ୍ବର,ଅକ୍ଟୋବର,ନଭେମ୍ବର,ଡିସେମ୍ବର'
};

window.APP_STRINGS.ta = {
  app_title: 'வருகைப் பதிவேடு',
  intro: 'சில நொடிகளில் வகுப்பு வருகையைப் பதிவு செய்யுங்கள், மாத மொத்தம் மற்றும் வருகை % பாருங்கள், பதிவேட்டை அச்சிடுங்கள். எல்லாத் தகவலும் இந்தச் சாதனத்திலேயே இருக்கும்.',
  tab_day: 'தினசரி',
  tab_month: 'மாதம்',
  tab_students: 'மாணவர்கள்',
  class_label: 'வகுப்பு',
  date_label: 'தேதி',
  today: 'இன்று',
  prev_day: 'முந்தைய நாள்',
  next_day: 'அடுத்த நாள்',
  prev_month: 'முந்தைய மாதம்',
  next_month: 'அடுத்த மாதம்',
  st_P: 'வருகை',
  st_A: 'வரவில்லை',
  st_T: 'தாமதம்',
  st_V: 'விடுப்பு',
  st_none: 'குறிக்கவில்லை',
  sh_P: 'வ',
  sh_A: 'இ',
  sh_T: 'தா',
  sh_V: 'வி',
  sh_H: 'ஓ',
  holiday: 'விடுமுறை',
  mark_all: 'அனைவருக்கும் வருகை',
  marked_present: '{n} மாணவர்களுக்கு வருகை குறிக்கப்பட்டது.',
  all_marked: 'அனைவருக்கும் ஏற்கனவே குறிக்கப்பட்டுள்ளது.',
  clear_day: 'இந்த நாளை அழி',
  confirm_clear_day: '{date} அன்றைய வருகை அனைத்தையும் அழிக்கவா?',
  copy_absent: 'வராதவர் பட்டியலை நகலெடு',
  absent_text: '{cls} · {date} · வரவில்லை ({n}): {list}',
  none_absent: 'இந்த நாளில் வராதவர் யாரும் இல்லை.',
  marked_n: '{total} பேரில் {n} பேருக்குக் குறிக்கப்பட்டது',
  tap_hint: 'மாற்ற பெயரைத் தொடுங்கள்: வருகை → வரவில்லை → தாமதம் → விடுப்பு → குறிக்கவில்லை.',
  search_ph: 'பெயர் அல்லது வரிசை எண் தேடு',
  no_match: '“{q}” உடன் பொருந்தும் மாணவர் இல்லை.',
  holiday_sunday: 'ஞாயிறு விடுமுறை நாள்.',
  holiday_national: 'இது தேசிய விடுமுறை நாள்.',
  holiday_marked: 'இந்த நாள் விடுமுறையாகக் குறிக்கப்பட்டுள்ளது.',
  take_anyway: 'இந்த நாளிலும் வருகை எடு',
  make_holiday: 'விடுமுறையாக்கு',
  future_note: 'இந்தத் தேதி இன்னும் வரவில்லை.',
  no_students: 'இந்த வகுப்பில் இன்னும் மாணவர்கள் இல்லை.',
  go_students: 'மாணவர்களைச் சேர்',
  sample_note: 'இது மாதிரி வகுப்பு; இதன் வருகை கற்பனையானது, நீங்கள் செயலியை முயன்று பார்க்கலாம். “மாணவர்கள்” தாவலில் உங்கள் வகுப்பைச் சேர்த்து, பிறகு மாதிரியை நீக்குங்கள்.',
  sample_class: 'மாதிரி · 6ஆம் வகுப்பு அ',
  sample_names: 'அருண் குமார்,அனன்யா சுப்பிரமணியன்,அர்ஜுன் ராஜா,திவ்யா முருகன்,பாத்திமா பீவி,கௌதம் சேகர்,ஈஸ்வர் பாலு,காவ்யா ரமேஷ்,லட்சுமி நாராயணன்,முகமது இஸ்மாயில்,நந்தினி செல்வம்,பிரவீன் கண்ணன்,பிரியா வெங்கடேஷ்,ராகுல் பாண்டியன்,ரேவதி சுந்தரம்,சூர்யா மணி,சனா பேகம்,சித்தார்த் கிருஷ்ணன்,தமிழ்செல்வி ராஜன்,விக்னேஷ் சரவணன்',
  my_class: 'என் வகுப்பு',
  month_hint: 'குறியை மாற்றக் கட்டத்தைத் தொடுங்கள். மேலே ஒரு தேதியைத் தொட்டு அதை விடுமுறையாக்கலாம், அல்லது மீண்டும் பள்ளி நாளாக்கலாம்.',
  sundays_off: 'ஞாயிறு மற்றும் தேசிய விடுமுறைகள் (26 ஜனவரி, 15 ஆகஸ்ட், 2 அக்டோபர்) விடுமுறை',
  leave_counts: 'விடுப்பை வருகையாகக் கணக்கிடு',
  min_pct: 'குறைந்தபட்ச வருகை %',
  late_note: 'தாமதமாக வந்தாலும் வருகையாகக் கணக்கிடப்படும்.',
  leave_note: 'விடுப்பும் வருகையாகக் கணக்கிடப்படும்.',
  col_roll: 'எண்',
  col_name: 'பெயர்',
  col_days: 'நாட்கள்',
  col_pct: '%',
  stat_days: 'வருகை எடுத்த நாட்கள்',
  stat_avg: 'வகுப்பு சராசரி',
  stat_below: '{p}%க்குக் கீழ் உள்ள மாணவர்கள்',
  day_present: 'தினசரி வருகை',
  export_csv: 'CSV ஏற்றுமதி',
  print_register: 'பதிவேட்டை அச்சிடு',
  print_meta: 'வகுப்பு: {cls} · மாதம்: {month}',
  printed_on: 'அச்சிட்ட தேதி: {date}',
  sign_teacher: 'வகுப்பு ஆசிரியர்',
  sign_principal: 'தலைமை ஆசிரியர்',
  school_name: 'பள்ளியின் பெயர் (அச்சிடும் பதிவேட்டில் வரும்)',
  school_ph: 'எ.கா. அரசு மேல்நிலைப் பள்ளி, மதுரை',
  class_settings: 'இந்த வகுப்பு',
  class_name: 'வகுப்பின் பெயர்',
  class_ph: 'எ.கா. 7ஆம் வகுப்பு ஆ',
  delete_class: 'இந்த வகுப்பை நீக்கு',
  confirm_delete_class: '“{name}” மற்றும் அதன் வருகை அனைத்தையும் நீக்கவா? இதைத் திரும்பப் பெற முடியாது.',
  new_class: 'புதிய வகுப்பைச் சேர்',
  add_class: 'வகுப்பைச் சேர்',
  class_added: '“{name}” வகுப்பு சேர்க்கப்பட்டது.',
  renamed: 'வகுப்பின் பெயர் சேமிக்கப்பட்டது.',
  students_n: '{n} மாணவர்கள்',
  add_student: 'ஒரு மாணவரைச் சேர்',
  roll_ph: 'எண்',
  name_ph: 'மாணவர் பெயர்',
  paste_title: 'மாணவர் பட்டியலை ஒட்டு',
  paste_help: 'ஒவ்வொரு வரியிலும் ஒரு மாணவர்: முதலில் வரிசை எண், பிறகு பெயர். பெயர் மட்டும் உள்ள வரிக்கு அடுத்த எண் தானாகக் கிடைக்கும். Excel அல்லது Google Sheets-இலிருந்து இரண்டு நெடுவரிசைகளை நேரடியாக நகலெடுக்கலாம்.',
  paste_ph: 'எ.கா.\n1, அருண் குமார்\n2, பாத்திமா பீவி\nசூர்யா மணி',
  paste_add: 'இவர்களைச் சேர்',
  import_csv: 'CSV இறக்குமதி',
  csv_help: 'அல்லது வரிசை எண், பெயர் நெடுவரிசைகள் உள்ள CSV கோப்பை இறக்குமதி செய்யுங்கள். தலைப்பு வரி தானாகத் தவிர்க்கப்படும்.',
  added_n: '{n} மாணவர்கள் சேர்க்கப்பட்டனர்.',
  nothing_added: 'பெயர் எதுவும் கிடைக்கவில்லை. வடிவத்தைச் சரிபாருங்கள்.',
  dup_rolls: 'இந்த எண்கள் ஒன்றுக்கு மேற்பட்ட முறை உள்ளன: {list}',
  remove_student: '{name}-ஐ நீக்கு',
  confirm_remove: '{name}-ஐ நீக்கவா? இந்த வகுப்பில் அவரது வருகையும் அழிக்கப்படும்.',
  need_name: 'தயவுசெய்து பெயரை எழுதுங்கள்.',
  backup_title: 'காப்புப்பிரதி மற்றும் மீட்பு',
  backup_help: 'வருகை இந்த உலாவியில் மட்டுமே சேமிக்கப்படுகிறது. ஒவ்வொரு வாரமும் காப்புப்பிரதியைப் பதிவிறக்கி, புதிய போன் அல்லது கணினியில் மீட்டெடுங்கள்.',
  backup_dl: 'காப்புப்பிரதி பதிவிறக்கு',
  restore: 'காப்புப்பிரதியை மீட்டெடு',
  restore_ok: 'காப்புப்பிரதி மீட்கப்பட்டது: {n} வகுப்புகள்.',
  restore_bad: 'இது வருகைப் பதிவேட்டின் காப்புப்பிரதி கோப்பு அல்ல.',
  confirm_restore: 'இந்தச் சாதனத்தில் உள்ள எல்லா வகுப்புகளுக்கும் பதிலாகக் காப்புப்பிரதியில் உள்ளவற்றை வைக்கவா?',
  help_1: 'நீங்கள் பாடம் எடுக்கும் ஒவ்வொரு பிரிவுக்கும் தனி வகுப்பு உருவாக்குங்கள். பள்ளிப் பட்டியலிலிருந்து பெயர்களை ஒட்டுங்கள் அல்லது CSV கோப்பை இறக்குமதி செய்யுங்கள்.',
  help_2: 'ஒவ்வொரு காலையும் “அனைவருக்கும் வருகை” அழுத்தி, வராதவர்களின் பெயரை மட்டும் தொடுங்கள். 60 மாணவர்களுக்கும் ஒரு நிமிடத்துக்குள் முடிந்துவிடும்.',
  help_3: '“மாதம்” தாவலில் ஒவ்வொரு மாணவரின் வருகை % தெரியும். சிவப்பு வரிகள் குறைந்தபட்சத்துக்குக் கீழ் உள்ளவை (CBSE விதிப்படி 75% தேவை), எனவே முன்கூட்டியே பெற்றோரிடம் பேசலாம்.',
  help_4: 'மாத இறுதியில் பதிவேட்டை அச்சிட்டு (A4 கிடைமட்டம்) கையொப்பமிடுங்கள், அல்லது Excel / Google Sheets-க்கு CSV ஏற்றுமதி செய்யுங்கள்.',
  help_5: 'வகுப்புச் செயல்பாடு: வகுப்புத் தலைவரை ஸ்மார்ட்போர்டில் வருகை எடுக்கச் சொல்லுங்கள். பிறகு மாணவர்கள் தங்கள் வருகை % கணக்கிடட்டும்: (வந்த நாட்கள் ÷ பள்ளி நாட்கள்) × 100.',
  help_6: 'உங்கள் தகவல் இந்தச் சாதனத்தை விட்டு வெளியே போகாது. போன் மாறினாலும் இழக்காமல் இருக்க ஒவ்வொரு வாரமும் காப்புப்பிரதி பதிவிறக்குங்கள்.',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'ஞாயிறு,திங்கள்,செவ்வாய்,புதன்,வியாழன்,வெள்ளி,சனி',
  wd_min: 'ஞா,தி,செ,பு,வி,வெ,ச',
  months: 'ஜனவரி,பிப்ரவரி,மார்ச்,ஏப்ரல்,மே,ஜூன்,ஜூலை,ஆகஸ்ட்,செப்டம்பர்,அக்டோபர்,நவம்பர்,டிசம்பர்'
};

window.APP_STRINGS.te = {
  app_title: 'హాజరు రిజిస్టర్',
  intro: 'కొన్ని సెకన్లలో తరగతి హాజరు తీసుకోండి, నెల మొత్తం మరియు హాజరు % చూడండి, రిజిస్టర్‌ను ప్రింట్ చేయండి. సమాచారం అంతా ఈ పరికరంలోనే ఉంటుంది.',
  tab_day: 'రోజువారీ',
  tab_month: 'నెలవారీ',
  tab_students: 'విద్యార్థులు',
  class_label: 'తరగతి',
  date_label: 'తేదీ',
  today: 'ఈరోజు',
  prev_day: 'ముందు రోజు',
  next_day: 'తర్వాతి రోజు',
  prev_month: 'ముందు నెల',
  next_month: 'తర్వాతి నెల',
  st_P: 'హాజరు',
  st_A: 'గైర్హాజరు',
  st_T: 'ఆలస్యం',
  st_V: 'సెలవు',
  st_none: 'గుర్తించలేదు',
  sh_P: 'హా',
  sh_A: 'గై',
  sh_T: 'ఆ',
  sh_V: 'సె',
  sh_H: 'బం',
  holiday: 'బడి సెలవు',
  mark_all: 'అందరికీ హాజరు వేయండి',
  marked_present: '{n} మంది విద్యార్థులకు హాజరు వేశాం.',
  all_marked: 'అందరికీ ఇప్పటికే గుర్తించారు.',
  clear_day: 'ఈ రోజును తుడిచివేయండి',
  confirm_clear_day: '{date} నాటి హాజరు అంతా తుడిచివేయాలా?',
  copy_absent: 'గైర్హాజరు జాబితా కాపీ చేయండి',
  absent_text: '{cls} · {date} · గైర్హాజరు ({n}): {list}',
  none_absent: 'ఈ రోజు ఎవరూ గైర్హాజరు కాలేదు.',
  marked_n: '{total} మందిలో {n} మందికి గుర్తించారు',
  tap_hint: 'మార్చడానికి పేరుపై నొక్కండి: హాజరు → గైర్హాజరు → ఆలస్యం → సెలవు → గుర్తించలేదు.',
  search_ph: 'పేరు లేదా రోల్ నంబర్ వెతకండి',
  no_match: '“{q}”కు సరిపోయే విద్యార్థి లేరు.',
  holiday_sunday: 'ఆదివారం సెలవు.',
  holiday_national: 'ఇది జాతీయ సెలవు దినం.',
  holiday_marked: 'ఈ రోజును సెలవుగా గుర్తించారు.',
  take_anyway: 'ఈ రోజు కూడా హాజరు తీసుకోండి',
  make_holiday: 'సెలవుగా ప్రకటించండి',
  future_note: 'ఈ తేదీ ఇంకా రాలేదు.',
  no_students: 'ఈ తరగతిలో ఇంకా విద్యార్థులు లేరు.',
  go_students: 'విద్యార్థులను జోడించండి',
  sample_note: 'ఇది నమూనా తరగతి, దీని హాజరు కల్పితం; మీరు యాప్‌ను ప్రయత్నించి చూడవచ్చు. “విద్యార్థులు” ట్యాబ్‌లో మీ తరగతిని జోడించి, తర్వాత నమూనాను తొలగించండి.',
  sample_class: 'నమూనా · 6వ తరగతి ఎ',
  sample_names: 'ఆదిత్య రెడ్డి,అనన్య రావు,అర్జున్ నాయుడు,దీప్తి వర్మ,ఫాతిమా బేగం,గౌతమ్ చౌదరి,ఈశ్వర్ ప్రసాద్,కావ్య శర్మ,లక్ష్మి దేవి,మహమ్మద్ రఫీ,నేహా గౌడ్,ప్రణవ్ కుమార్,ప్రియా యాదవ్,రాహుల్ వర్మ,రమ్య శ్రీ,రోహిత్ బాబు,సనా ఫాతిమా,సిద్ధార్థ్ రాజు,తేజస్వి నాయుడు,విక్రమ్ సింహా',
  my_class: 'నా తరగతి',
  month_hint: 'గుర్తును మార్చడానికి గడిపై నొక్కండి. పైన ఏదైనా తేదీపై నొక్కి దాన్ని సెలవుగా, లేదా మళ్ళీ బడి రోజుగా మార్చండి.',
  sundays_off: 'ఆదివారాలు మరియు జాతీయ సెలవులు (26 జనవరి, 15 ఆగస్టు, 2 అక్టోబర్) సెలవు',
  leave_counts: 'సెలవును హాజరుగా లెక్కించండి',
  min_pct: 'కనీస హాజరు %',
  late_note: 'ఆలస్యంగా వచ్చినా హాజరుగానే లెక్కిస్తాం.',
  leave_note: 'సెలవును కూడా హాజరుగానే లెక్కిస్తాం.',
  col_roll: 'రోల్',
  col_name: 'పేరు',
  col_days: 'రోజులు',
  col_pct: '%',
  stat_days: 'హాజరు తీసుకున్న రోజులు',
  stat_avg: 'తరగతి సగటు',
  stat_below: '{p}% కంటే తక్కువ ఉన్నవారు',
  day_present: 'ప్రతి రోజు హాజరు',
  export_csv: 'CSV ఎక్స్‌పోర్ట్',
  print_register: 'రిజిస్టర్ ప్రింట్ చేయండి',
  print_meta: 'తరగతి: {cls} · నెల: {month}',
  printed_on: 'ప్రింట్ తేదీ: {date}',
  sign_teacher: 'తరగతి ఉపాధ్యాయులు',
  sign_principal: 'ప్రధానోపాధ్యాయులు',
  school_name: 'పాఠశాల పేరు (ప్రింట్ చేసిన రిజిస్టర్‌పై కనిపిస్తుంది)',
  school_ph: 'ఉదా. జిల్లా పరిషత్ ఉన్నత పాఠశాల, గుంటూరు',
  class_settings: 'ఈ తరగతి',
  class_name: 'తరగతి పేరు',
  class_ph: 'ఉదా. 7వ తరగతి బి',
  delete_class: 'ఈ తరగతిని తొలగించండి',
  confirm_delete_class: '“{name}” మరియు దాని హాజరు అంతా తొలగించాలా? దీన్ని మళ్ళీ తిరిగి తేలేం.',
  new_class: 'కొత్త తరగతి జోడించండి',
  add_class: 'తరగతి జోడించండి',
  class_added: '“{name}” తరగతి జోడించబడింది.',
  renamed: 'తరగతి పేరు సేవ్ అయింది.',
  students_n: '{n} మంది విద్యార్థులు',
  add_student: 'ఒక విద్యార్థిని జోడించండి',
  roll_ph: 'రోల్',
  name_ph: 'విద్యార్థి పేరు',
  paste_title: 'విద్యార్థుల జాబితాను పేస్ట్ చేయండి',
  paste_help: 'ప్రతి లైన్‌లో ఒక విద్యార్థి: ముందు రోల్ నంబర్, తర్వాత పేరు. పేరు మాత్రమే ఉన్న లైన్‌కు తర్వాతి రోల్ నంబర్ వస్తుంది. Excel లేదా Google Sheets నుండి రెండు కాలమ్‌లను నేరుగా కాపీ చేయవచ్చు.',
  paste_ph: 'ఉదా.\n1, ఆదిత్య రెడ్డి\n2, ఫాతిమా బేగం\nరోహిత్ బాబు',
  paste_add: 'వీరిని జోడించండి',
  import_csv: 'CSV ఇంపోర్ట్ చేయండి',
  csv_help: 'లేదా రోల్ నంబర్, పేరు కాలమ్‌లు ఉన్న CSV ఫైల్‌ను ఇంపోర్ట్ చేయండి. శీర్షిక వరుసను దానంతట అదే వదిలేస్తుంది.',
  added_n: '{n} మంది విద్యార్థులు జోడించబడ్డారు.',
  nothing_added: 'పేర్లు ఏవీ దొరకలేదు. రాసిన పద్ధతిని చూడండి.',
  dup_rolls: 'ఈ రోల్ నంబర్లు ఒకటి కంటే ఎక్కువసార్లు ఉన్నాయి: {list}',
  remove_student: '{name}ను తొలగించండి',
  confirm_remove: '{name}ను తొలగించాలా? ఈ తరగతిలో వారి హాజరు కూడా తుడిచివేయబడుతుంది.',
  need_name: 'దయచేసి పేరు రాయండి.',
  backup_title: 'బ్యాకప్ మరియు రీస్టోర్',
  backup_help: 'హాజరు ఈ బ్రౌజర్‌లో మాత్రమే సేవ్ అవుతుంది. ప్రతి వారం బ్యాకప్ డౌన్‌లోడ్ చేసి, కొత్త ఫోన్ లేదా కంప్యూటర్‌లో రీస్టోర్ చేయండి.',
  backup_dl: 'బ్యాకప్ డౌన్‌లోడ్ చేయండి',
  restore: 'బ్యాకప్ రీస్టోర్ చేయండి',
  restore_ok: 'బ్యాకప్ రీస్టోర్ అయింది: {n} తరగతులు.',
  restore_bad: 'ఇది హాజరు రిజిస్టర్ బ్యాకప్ ఫైల్ కాదు.',
  confirm_restore: 'ఈ పరికరంలోని అన్ని తరగతుల స్థానంలో బ్యాకప్‌లోని తరగతులను ఉంచాలా?',
  help_1: 'మీరు బోధించే ప్రతి సెక్షన్‌కు వేరే తరగతి సృష్టించండి. పాఠశాల జాబితా నుండి పేర్లు పేస్ట్ చేయండి లేదా CSV ఫైల్ ఇంపోర్ట్ చేయండి.',
  help_2: 'ప్రతి ఉదయం “అందరికీ హాజరు వేయండి” నొక్కి, గైర్హాజరైనవారి పేర్లపై మాత్రమే నొక్కండి. 60 మంది విద్యార్థులకైనా ఒక నిమిషం కంటే తక్కువ పడుతుంది.',
  help_3: '“నెలవారీ” ట్యాబ్‌లో ప్రతి విద్యార్థి హాజరు % కనిపిస్తుంది. ఎరుపు వరుసలు కనీసం కంటే తక్కువ (CBSE ప్రకారం 75% అవసరం), కాబట్టి ముందుగానే తల్లిదండ్రులతో మాట్లాడవచ్చు.',
  help_4: 'నెల చివర రిజిస్టర్‌ను ప్రింట్ చేసి (A4 అడ్డం పేజీ) సంతకం చేయండి, లేదా Excel / Google Sheets కోసం CSV ఎక్స్‌పోర్ట్ చేయండి.',
  help_5: 'తరగతి కార్యాచరణ: క్లాస్ లీడర్‌ను స్మార్ట్‌బోర్డ్‌పై హాజరు తీసుకోనివ్వండి. తర్వాత విద్యార్థులు తమ హాజరు % లెక్కించాలి: (హాజరైన రోజులు ÷ బడి రోజులు) × 100.',
  help_6: 'మీ సమాచారం ఈ పరికరం దాటి బయటకు వెళ్ళదు. ఫోన్ మారినా ఏమీ పోకుండా ప్రతి వారం బ్యాకప్ డౌన్‌లోడ్ చేయండి.',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'ఆదివారం,సోమవారం,మంగళవారం,బుధవారం,గురువారం,శుక్రవారం,శనివారం',
  wd_min: 'ఆ,సో,మం,బు,గు,శు,శ',
  months: 'జనవరి,ఫిబ్రవరి,మార్చి,ఏప్రిల్,మే,జూన్,జూలై,ఆగస్టు,సెప్టెంబర్,అక్టోబర్,నవంబర్,డిసెంబర్'
};

window.APP_STRINGS.kn = {
  app_title: 'ಹಾಜರಾತಿ ರಿಜಿಸ್ಟರ್',
  intro: 'ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ತರಗತಿಯ ಹಾಜರಾತಿ ತೆಗೆದುಕೊಳ್ಳಿ, ತಿಂಗಳ ಒಟ್ಟು ಮತ್ತು ಹಾಜರಾತಿ % ನೋಡಿ, ರಿಜಿಸ್ಟರ್ ಮುದ್ರಿಸಿ. ಎಲ್ಲಾ ಮಾಹಿತಿ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ.',
  tab_day: 'ದಿನನಿತ್ಯ',
  tab_month: 'ತಿಂಗಳು',
  tab_students: 'ವಿದ್ಯಾರ್ಥಿಗಳು',
  class_label: 'ತರಗತಿ',
  date_label: 'ದಿನಾಂಕ',
  today: 'ಇಂದು',
  prev_day: 'ಹಿಂದಿನ ದಿನ',
  next_day: 'ಮುಂದಿನ ದಿನ',
  prev_month: 'ಹಿಂದಿನ ತಿಂಗಳು',
  next_month: 'ಮುಂದಿನ ತಿಂಗಳು',
  st_P: 'ಹಾಜರು',
  st_A: 'ಗೈರು',
  st_T: 'ತಡ',
  st_V: 'ರಜೆ',
  st_none: 'ಗುರುತಿಸಿಲ್ಲ',
  sh_P: 'ಹಾ',
  sh_A: 'ಗೈ',
  sh_T: 'ತ',
  sh_V: 'ರ',
  sh_H: 'ಬಿ',
  holiday: 'ಶಾಲೆಗೆ ಬಿಡುವು',
  mark_all: 'ಎಲ್ಲರಿಗೂ ಹಾಜರು ಹಾಕಿ',
  marked_present: '{n} ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಹಾಜರು ಹಾಕಲಾಗಿದೆ.',
  all_marked: 'ಎಲ್ಲರಿಗೂ ಈಗಾಗಲೇ ಗುರುತಿಸಲಾಗಿದೆ.',
  clear_day: 'ಈ ದಿನವನ್ನು ಅಳಿಸಿ',
  confirm_clear_day: '{date} ರ ಎಲ್ಲಾ ಹಾಜರಾತಿ ಅಳಿಸಬೇಕೆ?',
  copy_absent: 'ಗೈರು ಪಟ್ಟಿ ನಕಲಿಸಿ',
  absent_text: '{cls} · {date} · ಗೈರು ({n}): {list}',
  none_absent: 'ಈ ದಿನ ಯಾರೂ ಗೈರಾಗಿಲ್ಲ.',
  marked_n: '{total} ರಲ್ಲಿ {n} ಜನರಿಗೆ ಗುರುತಿಸಲಾಗಿದೆ',
  tap_hint: 'ಬದಲಿಸಲು ಹೆಸರಿನ ಮೇಲೆ ಒತ್ತಿ: ಹಾಜರು → ಗೈರು → ತಡ → ರಜೆ → ಗುರುತಿಸಿಲ್ಲ.',
  search_ph: 'ಹೆಸರು ಅಥವಾ ರೋಲ್ ನಂಬರ್ ಹುಡುಕಿ',
  no_match: '“{q}” ಗೆ ಹೊಂದುವ ವಿದ್ಯಾರ್ಥಿ ಇಲ್ಲ.',
  holiday_sunday: 'ಭಾನುವಾರ ರಜೆ.',
  holiday_national: 'ಇದು ರಾಷ್ಟ್ರೀಯ ರಜಾದಿನ.',
  holiday_marked: 'ಈ ದಿನವನ್ನು ರಜೆ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ.',
  take_anyway: 'ಈ ದಿನವೂ ಹಾಜರಾತಿ ತೆಗೆದುಕೊಳ್ಳಿ',
  make_holiday: 'ರಜೆ ಎಂದು ಘೋಷಿಸಿ',
  future_note: 'ಈ ದಿನಾಂಕ ಇನ್ನೂ ಬಂದಿಲ್ಲ.',
  no_students: 'ಈ ತರಗತಿಯಲ್ಲಿ ಇನ್ನೂ ವಿದ್ಯಾರ್ಥಿಗಳಿಲ್ಲ.',
  go_students: 'ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಸೇರಿಸಿ',
  sample_note: 'ಇದು ಮಾದರಿ ತರಗತಿ, ಇದರ ಹಾಜರಾತಿ ಕಾಲ್ಪನಿಕ; ನೀವು ಆ್ಯಪ್ ಬಳಸಿ ನೋಡಬಹುದು. “ವಿದ್ಯಾರ್ಥಿಗಳು” ಟ್ಯಾಬ್‌ನಲ್ಲಿ ನಿಮ್ಮ ತರಗತಿ ಸೇರಿಸಿ, ನಂತರ ಮಾದರಿಯನ್ನು ತೆಗೆದುಹಾಕಿ.',
  sample_class: 'ಮಾದರಿ · 6ನೇ ತರಗತಿ ಎ',
  sample_names: 'ಆದಿತ್ಯ ಗೌಡ,ಅನನ್ಯಾ ಭಟ್,ಅರ್ಜುನ್ ಶೆಟ್ಟಿ,ದೀಪಾ ಹೆಗ್ಡೆ,ಫಾತಿಮಾ ಬಾನು,ಗೌತಮ್ ರಾವ್,ಈಶ್ವರ್ ನಾಯಕ್,ಕಾವ್ಯಾ ಕುಲಕರ್ಣಿ,ಲಕ್ಷ್ಮಿ ಪ್ರಸಾದ್,ಮಹಮ್ಮದ್ ರಫೀಕ್,ನೇಹಾ ಜೋಶಿ,ಪ್ರಣವ್ ಕಾಮತ್,ಪ್ರಿಯಾ ಶರ್ಮಾ,ರಾಹುಲ್ ಪಾಟೀಲ್,ರಮ್ಯಾ ಮೂರ್ತಿ,ರೋಹನ್ ಪೈ,ಸನಾ ಖಾನ್,ಸಿದ್ಧಾರ್ಥ ಹೆಗ್ಡೆ,ತೇಜಸ್ವಿನಿ ರಾಜು,ವಿಕ್ರಮ್ ಕುಮಾರ್',
  my_class: 'ನನ್ನ ತರಗತಿ',
  month_hint: 'ಗುರುತು ಬದಲಿಸಲು ಚೌಕದ ಮೇಲೆ ಒತ್ತಿ. ಮೇಲಿನ ದಿನಾಂಕದ ಮೇಲೆ ಒತ್ತಿ ಅದನ್ನು ರಜೆ ಮಾಡಿ, ಅಥವಾ ಮತ್ತೆ ಶಾಲಾ ದಿನ ಮಾಡಿ.',
  sundays_off: 'ಭಾನುವಾರ ಮತ್ತು ರಾಷ್ಟ್ರೀಯ ರಜೆಗಳು (26 ಜನವರಿ, 15 ಆಗಸ್ಟ್, 2 ಅಕ್ಟೋಬರ್) ರಜೆ',
  leave_counts: 'ರಜೆಯನ್ನು ಹಾಜರು ಎಂದು ಎಣಿಸಿ',
  min_pct: 'ಕನಿಷ್ಠ ಹಾಜರಾತಿ %',
  late_note: 'ತಡವಾಗಿ ಬಂದರೂ ಹಾಜರು ಎಂದೇ ಎಣಿಸಲಾಗುತ್ತದೆ.',
  leave_note: 'ರಜೆಯನ್ನೂ ಹಾಜರು ಎಂದೇ ಎಣಿಸಲಾಗುತ್ತದೆ.',
  col_roll: 'ರೋಲ್',
  col_name: 'ಹೆಸರು',
  col_days: 'ದಿನಗಳು',
  col_pct: '%',
  stat_days: 'ಹಾಜರಾತಿ ತೆಗೆದುಕೊಂಡ ದಿನಗಳು',
  stat_avg: 'ತರಗತಿಯ ಸರಾಸರಿ',
  stat_below: '{p}% ಕ್ಕಿಂತ ಕಡಿಮೆ ಇರುವವರು',
  day_present: 'ಪ್ರತಿದಿನ ಹಾಜರು',
  export_csv: 'CSV ರಫ್ತು',
  print_register: 'ರಿಜಿಸ್ಟರ್ ಮುದ್ರಿಸಿ',
  print_meta: 'ತರಗತಿ: {cls} · ತಿಂಗಳು: {month}',
  printed_on: 'ಮುದ್ರಿಸಿದ ದಿನಾಂಕ: {date}',
  sign_teacher: 'ತರಗತಿ ಶಿಕ್ಷಕರು',
  sign_principal: 'ಮುಖ್ಯ ಶಿಕ್ಷಕರು',
  school_name: 'ಶಾಲೆಯ ಹೆಸರು (ಮುದ್ರಿಸಿದ ರಿಜಿಸ್ಟರ್‌ನಲ್ಲಿ ಕಾಣುತ್ತದೆ)',
  school_ph: 'ಉದಾ. ಸರ್ಕಾರಿ ಪ್ರೌಢಶಾಲೆ, ಮೈಸೂರು',
  class_settings: 'ಈ ತರಗತಿ',
  class_name: 'ತರಗತಿಯ ಹೆಸರು',
  class_ph: 'ಉದಾ. 7ನೇ ತರಗತಿ ಬಿ',
  delete_class: 'ಈ ತರಗತಿ ತೆಗೆದುಹಾಕಿ',
  confirm_delete_class: '“{name}” ಮತ್ತು ಅದರ ಎಲ್ಲಾ ಹಾಜರಾತಿ ತೆಗೆದುಹಾಕಬೇಕೆ? ಇದನ್ನು ಮರಳಿ ಪಡೆಯಲು ಆಗುವುದಿಲ್ಲ.',
  new_class: 'ಹೊಸ ತರಗತಿ ಸೇರಿಸಿ',
  add_class: 'ತರಗತಿ ಸೇರಿಸಿ',
  class_added: '“{name}” ತರಗತಿ ಸೇರಿಸಲಾಗಿದೆ.',
  renamed: 'ತರಗತಿಯ ಹೆಸರು ಉಳಿಸಲಾಗಿದೆ.',
  students_n: '{n} ವಿದ್ಯಾರ್ಥಿಗಳು',
  add_student: 'ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಸೇರಿಸಿ',
  roll_ph: 'ರೋಲ್',
  name_ph: 'ವಿದ್ಯಾರ್ಥಿಯ ಹೆಸರು',
  paste_title: 'ವಿದ್ಯಾರ್ಥಿಗಳ ಪಟ್ಟಿ ಅಂಟಿಸಿ',
  paste_help: 'ಪ್ರತಿ ಸಾಲಿನಲ್ಲಿ ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿ: ಮೊದಲು ರೋಲ್ ನಂಬರ್, ನಂತರ ಹೆಸರು. ಹೆಸರು ಮಾತ್ರ ಇರುವ ಸಾಲಿಗೆ ಮುಂದಿನ ರೋಲ್ ನಂಬರ್ ಸಿಗುತ್ತದೆ. Excel ಅಥವಾ Google Sheets ನಿಂದ ಎರಡು ಕಾಲಂಗಳನ್ನು ನೇರವಾಗಿ ನಕಲಿಸಬಹುದು.',
  paste_ph: 'ಉದಾ.\n1, ಆದಿತ್ಯ ಗೌಡ\n2, ಫಾತಿಮಾ ಬಾನು\nರೋಹನ್ ಪೈ',
  paste_add: 'ಇವರನ್ನು ಸೇರಿಸಿ',
  import_csv: 'CSV ಆಮದು ಮಾಡಿ',
  csv_help: 'ಅಥವಾ ರೋಲ್ ನಂಬರ್ ಮತ್ತು ಹೆಸರಿನ ಕಾಲಂಗಳಿರುವ CSV ಫೈಲ್ ಆಮದು ಮಾಡಿ. ಶೀರ್ಷಿಕೆ ಸಾಲನ್ನು ತಾನಾಗಿಯೇ ಬಿಡಲಾಗುತ್ತದೆ.',
  added_n: '{n} ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ.',
  nothing_added: 'ಯಾವ ಹೆಸರೂ ಸಿಗಲಿಲ್ಲ. ಬರೆದ ರೀತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.',
  dup_rolls: 'ಈ ರೋಲ್ ನಂಬರ್‌ಗಳು ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ಬಾರಿ ಇವೆ: {list}',
  remove_student: '{name} ಅವರನ್ನು ತೆಗೆದುಹಾಕಿ',
  confirm_remove: '{name} ಅವರನ್ನು ತೆಗೆದುಹಾಕಬೇಕೆ? ಈ ತರಗತಿಯಲ್ಲಿ ಅವರ ಹಾಜರಾತಿಯೂ ಅಳಿಸಿಹೋಗುತ್ತದೆ.',
  need_name: 'ದಯವಿಟ್ಟು ಹೆಸರು ಬರೆಯಿರಿ.',
  backup_title: 'ಬ್ಯಾಕಪ್ ಮತ್ತು ಮರುಸ್ಥಾಪನೆ',
  backup_help: 'ಹಾಜರಾತಿ ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಮಾತ್ರ ಉಳಿಯುತ್ತದೆ. ಪ್ರತಿ ವಾರ ಬ್ಯಾಕಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ, ಹೊಸ ಫೋನ್ ಅಥವಾ ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ ಮರುಸ್ಥಾಪಿಸಿ.',
  backup_dl: 'ಬ್ಯಾಕಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
  restore: 'ಬ್ಯಾಕಪ್ ಮರುಸ್ಥಾಪಿಸಿ',
  restore_ok: 'ಬ್ಯಾಕಪ್ ಮರುಸ್ಥಾಪಿಸಲಾಗಿದೆ: {n} ತರಗತಿಗಳು.',
  restore_bad: 'ಇದು ಹಾಜರಾತಿ ರಿಜಿಸ್ಟರ್‌ನ ಬ್ಯಾಕಪ್ ಫೈಲ್ ಅಲ್ಲ.',
  confirm_restore: 'ಈ ಸಾಧನದ ಎಲ್ಲಾ ತರಗತಿಗಳ ಬದಲು ಬ್ಯಾಕಪ್‌ನಲ್ಲಿರುವ ತರಗತಿಗಳನ್ನು ಇಡಬೇಕೆ?',
  help_1: 'ನೀವು ಕಲಿಸುವ ಪ್ರತಿ ವಿಭಾಗಕ್ಕೂ ಬೇರೆ ತರಗತಿ ರಚಿಸಿ. ಶಾಲೆಯ ಪಟ್ಟಿಯಿಂದ ಹೆಸರುಗಳನ್ನು ಅಂಟಿಸಿ ಅಥವಾ CSV ಫೈಲ್ ಆಮದು ಮಾಡಿ.',
  help_2: 'ಪ್ರತಿ ಬೆಳಿಗ್ಗೆ “ಎಲ್ಲರಿಗೂ ಹಾಜರು ಹಾಕಿ” ಒತ್ತಿ, ನಂತರ ಗೈರಾದವರ ಹೆಸರಿನ ಮೇಲೆ ಮಾತ್ರ ಒತ್ತಿ. 60 ವಿದ್ಯಾರ್ಥಿಗಳಿಗೂ ಒಂದು ನಿಮಿಷಕ್ಕಿಂತ ಕಡಿಮೆ ಸಾಕು.',
  help_3: '“ತಿಂಗಳು” ಟ್ಯಾಬ್‌ನಲ್ಲಿ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಯ ಹಾಜರಾತಿ % ಕಾಣುತ್ತದೆ. ಕೆಂಪು ಸಾಲುಗಳು ಕನಿಷ್ಠಕ್ಕಿಂತ ಕಡಿಮೆ (CBSE ಪ್ರಕಾರ 75% ಬೇಕು), ಹಾಗಾಗಿ ಮೊದಲೇ ಪೋಷಕರೊಂದಿಗೆ ಮಾತನಾಡಬಹುದು.',
  help_4: 'ತಿಂಗಳ ಕೊನೆಯಲ್ಲಿ ರಿಜಿಸ್ಟರ್ ಮುದ್ರಿಸಿ (A4 ಅಡ್ಡ ಪುಟ) ಸಹಿ ಮಾಡಿ, ಅಥವಾ Excel / Google Sheets ಗಾಗಿ CSV ರಫ್ತು ಮಾಡಿ.',
  help_5: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ತರಗತಿಯ ನಾಯಕನಿಗೆ ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಹಾಜರಾತಿ ತೆಗೆದುಕೊಳ್ಳಲು ಬಿಡಿ. ನಂತರ ವಿದ್ಯಾರ್ಥಿಗಳು ತಮ್ಮ ಹಾಜರಾತಿ % ಲೆಕ್ಕ ಹಾಕಲಿ: (ಹಾಜರಾದ ದಿನ ÷ ಶಾಲಾ ದಿನ) × 100.',
  help_6: 'ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಸಾಧನದಿಂದ ಹೊರಗೆ ಹೋಗುವುದಿಲ್ಲ. ಫೋನ್ ಬದಲಾದರೂ ಏನೂ ಕಳೆದುಹೋಗದಂತೆ ಪ್ರತಿ ವಾರ ಬ್ಯಾಕಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'ಭಾನುವಾರ,ಸೋಮವಾರ,ಮಂಗಳವಾರ,ಬುಧವಾರ,ಗುರುವಾರ,ಶುಕ್ರವಾರ,ಶನಿವಾರ',
  wd_min: 'ಭಾ,ಸೋ,ಮಂ,ಬು,ಗು,ಶು,ಶ',
  months: 'ಜನವರಿ,ಫೆಬ್ರವರಿ,ಮಾರ್ಚ್,ಏಪ್ರಿಲ್,ಮೇ,ಜೂನ್,ಜುಲೈ,ಆಗಸ್ಟ್,ಸೆಪ್ಟೆಂಬರ್,ಅಕ್ಟೋಬರ್,ನವೆಂಬರ್,ಡಿಸೆಂಬರ್'
};

window.APP_STRINGS.ml = {
  app_title: 'ഹാജർ രജിസ്റ്റർ',
  intro: 'നിമിഷങ്ങൾക്കുള്ളിൽ ക്ലാസ്സിലെ ഹാജർ എടുക്കൂ, മാസത്തെ ആകെയും ഹാജർ ശതമാനവും കാണൂ, രജിസ്റ്റർ പ്രിന്റ് ചെയ്യൂ. എല്ലാ വിവരങ്ങളും ഈ ഉപകരണത്തിൽ മാത്രം.',
  tab_day: 'ദിവസേന',
  tab_month: 'മാസം',
  tab_students: 'വിദ്യാർത്ഥികൾ',
  class_label: 'ക്ലാസ്',
  date_label: 'തീയതി',
  today: 'ഇന്ന്',
  prev_day: 'മുൻ ദിവസം',
  next_day: 'അടുത്ത ദിവസം',
  prev_month: 'മുൻ മാസം',
  next_month: 'അടുത്ത മാസം',
  st_P: 'ഹാജർ',
  st_A: 'ഹാജരില്ല',
  st_T: 'വൈകി',
  st_V: 'ലീവ്',
  st_none: 'രേഖപ്പെടുത്തിയില്ല',
  sh_P: 'ഹാ',
  sh_A: 'ഇ',
  sh_T: 'വൈ',
  sh_V: 'ലീ',
  sh_H: 'അ',
  holiday: 'അവധി',
  mark_all: 'എല്ലാവർക്കും ഹാജർ',
  marked_present: '{n} പേർക്ക് ഹാജർ രേഖപ്പെടുത്തി.',
  all_marked: 'എല്ലാവരെയും ഇതിനകം രേഖപ്പെടുത്തി.',
  clear_day: 'ഈ ദിവസം മായ്ക്കുക',
  confirm_clear_day: '{date} ലെ എല്ലാ ഹാജറും മായ്ക്കണോ?',
  copy_absent: 'ഹാജരില്ലാത്തവരുടെ പട്ടിക പകർത്തുക',
  absent_text: '{cls} · {date} · ഹാജരില്ല ({n}): {list}',
  none_absent: 'ഈ ദിവസം ഹാജരാകാത്തവർ ആരുമില്ല.',
  marked_n: '{total} പേരിൽ {n} പേരെ രേഖപ്പെടുത്തി',
  tap_hint: 'മാറ്റാൻ പേരിൽ തൊടുക: ഹാജർ → ഹാജരില്ല → വൈകി → ലീവ് → രേഖപ്പെടുത്തിയില്ല.',
  search_ph: 'പേരോ റോൾ നമ്പറോ തിരയുക',
  no_match: '“{q}” എന്നതുമായി ചേരുന്ന വിദ്യാർത്ഥിയില്ല.',
  holiday_sunday: 'ഞായറാഴ്ച അവധിയാണ്.',
  holiday_national: 'ഇത് ദേശീയ അവധി ദിനമാണ്.',
  holiday_marked: 'ഈ ദിവസം അവധിയായി രേഖപ്പെടുത്തിയിട്ടുണ്ട്.',
  take_anyway: 'ഈ ദിവസവും ഹാജർ എടുക്കുക',
  make_holiday: 'അവധിയാക്കുക',
  future_note: 'ഈ തീയതി ഇനിയും വന്നിട്ടില്ല.',
  no_students: 'ഈ ക്ലാസ്സിൽ ഇതുവരെ വിദ്യാർത്ഥികളില്ല.',
  go_students: 'വിദ്യാർത്ഥികളെ ചേർക്കുക',
  sample_note: 'ഇതൊരു മാതൃകാ ക്ലാസ്സാണ്, ഹാജർ സാങ്കൽപ്പികമാണ്; ആപ്പ് പരീക്ഷിച്ചുനോക്കാം. “വിദ്യാർത്ഥികൾ” ടാബിൽ നിങ്ങളുടെ ക്ലാസ് ചേർത്ത്, പിന്നീട് മാതൃക നീക്കം ചെയ്യുക.',
  sample_class: 'മാതൃക · 6 എ ക്ലാസ്',
  sample_names: 'ആദിത്യ നായർ,അനന്യ മേനോൻ,അർജുൻ പിള്ള,ദിവ്യ കുറുപ്പ്,ഫാത്തിമ ബീവി,ഗൗതം വർമ്മ,ഈശ്വർ നമ്പൂതിരി,കാവ്യ ജോസ്,ലക്ഷ്മി പണിക്കർ,മുഹമ്മദ് ഷാഫി,നേഹ തോമസ്,പ്രണവ് കൃഷ്ണൻ,പ്രിയ വർഗീസ്,രാഹുൽ രാജ്,റിയ മാത്യു,രോഹൻ ശങ്കർ,സന ഫാത്തിമ,സിദ്ധാർത്ഥ് മോഹൻ,തൻവി സുരേഷ്,വിക്രം ചന്ദ്രൻ',
  my_class: 'എന്റെ ക്ലാസ്',
  month_hint: 'അടയാളം മാറ്റാൻ കളത്തിൽ തൊടുക. മുകളിലെ തീയതിയിൽ തൊട്ട് അത് അവധിയാക്കാം, അല്ലെങ്കിൽ വീണ്ടും പ്രവൃത്തിദിനമാക്കാം.',
  sundays_off: 'ഞായറാഴ്ചകളും ദേശീയ അവധികളും (26 ജനുവരി, 15 ആഗസ്റ്റ്, 2 ഒക്ടോബർ) അവധി',
  leave_counts: 'ലീവ് ഹാജരായി കണക്കാക്കുക',
  min_pct: 'കുറഞ്ഞ ഹാജർ %',
  late_note: 'വൈകി വന്നാലും ഹാജരായി കണക്കാക്കും.',
  leave_note: 'ലീവും ഹാജരായി കണക്കാക്കും.',
  col_roll: 'റോൾ',
  col_name: 'പേര്',
  col_days: 'ദിവസം',
  col_pct: '%',
  stat_days: 'ഹാജർ എടുത്ത ദിവസങ്ങൾ',
  stat_avg: 'ക്ലാസ് ശരാശരി',
  stat_below: '{p}%-ൽ കുറവുള്ളവർ',
  day_present: 'ഓരോ ദിവസവും ഹാജർ',
  export_csv: 'CSV എക്സ്പോർട്ട്',
  print_register: 'രജിസ്റ്റർ പ്രിന്റ് ചെയ്യുക',
  print_meta: 'ക്ലാസ്: {cls} · മാസം: {month}',
  printed_on: 'പ്രിന്റ് ചെയ്ത തീയതി: {date}',
  sign_teacher: 'ക്ലാസ് ടീച്ചർ',
  sign_principal: 'പ്രധാനാധ്യാപകൻ',
  school_name: 'സ്കൂളിന്റെ പേര് (പ്രിന്റ് ചെയ്ത രജിസ്റ്ററിൽ കാണാം)',
  school_ph: 'ഉദാ. ഗവ. ഹയർ സെക്കൻഡറി സ്കൂൾ, തൃശ്ശൂർ',
  class_settings: 'ഈ ക്ലാസ്',
  class_name: 'ക്ലാസിന്റെ പേര്',
  class_ph: 'ഉദാ. 7 ബി ക്ലാസ്',
  delete_class: 'ഈ ക്ലാസ് നീക്കം ചെയ്യുക',
  confirm_delete_class: '“{name}” ഉം അതിലെ എല്ലാ ഹാജറും നീക്കം ചെയ്യണോ? ഇത് തിരികെ കിട്ടില്ല.',
  new_class: 'പുതിയ ക്ലാസ് ചേർക്കുക',
  add_class: 'ക്ലാസ് ചേർക്കുക',
  class_added: '“{name}” ക്ലാസ് ചേർത്തു.',
  renamed: 'ക്ലാസിന്റെ പേര് സേവ് ചെയ്തു.',
  students_n: '{n} വിദ്യാർത്ഥികൾ',
  add_student: 'ഒരു വിദ്യാർത്ഥിയെ ചേർക്കുക',
  roll_ph: 'റോൾ',
  name_ph: 'വിദ്യാർത്ഥിയുടെ പേര്',
  paste_title: 'വിദ്യാർത്ഥികളുടെ പട്ടിക പേസ്റ്റ് ചെയ്യുക',
  paste_help: 'ഓരോ വരിയിലും ഒരാൾ: ആദ്യം റോൾ നമ്പർ, പിന്നെ പേര്. പേര് മാത്രമുള്ള വരിക്ക് അടുത്ത റോൾ നമ്പർ കിട്ടും. Excel അല്ലെങ്കിൽ Google Sheets-ൽ നിന്ന് രണ്ട് കോളങ്ങൾ നേരിട്ട് പകർത്താം.',
  paste_ph: 'ഉദാ.\n1, ആദിത്യ നായർ\n2, ഫാത്തിമ ബീവി\nരോഹൻ ശങ്കർ',
  paste_add: 'ഇവരെ ചേർക്കുക',
  import_csv: 'CSV ഇമ്പോർട്ട് ചെയ്യുക',
  csv_help: 'അല്ലെങ്കിൽ റോൾ നമ്പറും പേരും കോളങ്ങളായുള്ള CSV ഫയൽ ഇമ്പോർട്ട് ചെയ്യുക. തലക്കെട്ട് വരി സ്വയം ഒഴിവാക്കും.',
  added_n: '{n} വിദ്യാർത്ഥികളെ ചേർത്തു.',
  nothing_added: 'പേരുകളൊന്നും കിട്ടിയില്ല. എഴുതിയ രീതി പരിശോധിക്കുക.',
  dup_rolls: 'ഈ റോൾ നമ്പറുകൾ ഒന്നിലധികം തവണയുണ്ട്: {list}',
  remove_student: '{name} നെ നീക്കുക',
  confirm_remove: '{name} നെ നീക്കണോ? ഈ ക്ലാസ്സിലെ അവരുടെ ഹാജറും മായും.',
  need_name: 'ദയവായി പേര് എഴുതുക.',
  backup_title: 'ബാക്കപ്പും റീസ്റ്റോറും',
  backup_help: 'ഹാജർ ഈ ബ്രൗസറിൽ മാത്രമാണ് സേവ് ചെയ്യുന്നത്. എല്ലാ ആഴ്ചയും ബാക്കപ്പ് ഡൗൺലോഡ് ചെയ്യുക, പുതിയ ഫോണിലോ കമ്പ്യൂട്ടറിലോ റീസ്റ്റോർ ചെയ്യുക.',
  backup_dl: 'ബാക്കപ്പ് ഡൗൺലോഡ് ചെയ്യുക',
  restore: 'ബാക്കപ്പ് റീസ്റ്റോർ ചെയ്യുക',
  restore_ok: 'ബാക്കപ്പ് റീസ്റ്റോർ ചെയ്തു: {n} ക്ലാസുകൾ.',
  restore_bad: 'ഇത് ഹാജർ രജിസ്റ്ററിന്റെ ബാക്കപ്പ് ഫയലല്ല.',
  confirm_restore: 'ഈ ഉപകരണത്തിലെ എല്ലാ ക്ലാസുകൾക്കും പകരം ബാക്കപ്പിലുള്ളവ വെക്കണോ?',
  help_1: 'നിങ്ങൾ പഠിപ്പിക്കുന്ന ഓരോ ഡിവിഷനും പ്രത്യേകം ക്ലാസ് ഉണ്ടാക്കുക. സ്കൂൾ പട്ടികയിൽ നിന്ന് പേരുകൾ പേസ്റ്റ് ചെയ്യുക, അല്ലെങ്കിൽ CSV ഫയൽ ഇമ്പോർട്ട് ചെയ്യുക.',
  help_2: 'എല്ലാ ദിവസവും രാവിലെ “എല്ലാവർക്കും ഹാജർ” അമർത്തുക, പിന്നെ ഹാജരാകാത്തവരുടെ പേരിൽ മാത്രം തൊടുക. 60 പേർക്കും ഒരു മിനിറ്റിൽ താഴെ മതി.',
  help_3: '“മാസം” ടാബിൽ ഓരോ വിദ്യാർത്ഥിയുടെയും ഹാജർ % കാണാം. ചുവന്ന വരികൾ കുറഞ്ഞ പരിധിക്ക് താഴെയാണ് (CBSE പ്രകാരം 75% വേണം), അതിനാൽ നേരത്തേ രക്ഷിതാക്കളോട് സംസാരിക്കാം.',
  help_4: 'മാസാവസാനം രജിസ്റ്റർ പ്രിന്റ് ചെയ്ത് (A4 കിടപ്പ് പേജ്) ഒപ്പിടുക, അല്ലെങ്കിൽ Excel / Google Sheets-നായി CSV എക്സ്പോർട്ട് ചെയ്യുക.',
  help_5: 'ക്ലാസ് പ്രവർത്തനം: ക്ലാസ് ലീഡറെക്കൊണ്ട് സ്മാർട്ട്ബോർഡിൽ ഹാജർ എടുപ്പിക്കുക. പിന്നെ വിദ്യാർത്ഥികൾ സ്വന്തം ഹാജർ % കണക്കാക്കട്ടെ: (ഹാജരായ ദിവസം ÷ പ്രവൃത്തിദിനം) × 100.',
  help_6: 'നിങ്ങളുടെ വിവരങ്ങൾ ഈ ഉപകരണത്തിന് പുറത്ത് പോകില്ല. ഫോൺ മാറിയാലും ഒന്നും നഷ്ടപ്പെടാതിരിക്കാൻ എല്ലാ ആഴ്ചയും ബാക്കപ്പ് ഡൗൺലോഡ് ചെയ്യുക.',
  date_long: '{wd}, {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'ഞായർ,തിങ്കൾ,ചൊവ്വ,ബുധൻ,വ്യാഴം,വെള്ളി,ശനി',
  wd_min: 'ഞാ,തി,ചൊ,ബു,വ്യാ,വെ,ശ',
  months: 'ജനുവരി,ഫെബ്രുവരി,മാർച്ച്,ഏപ്രിൽ,മേയ്,ജൂൺ,ജൂലൈ,ആഗസ്റ്റ്,സെപ്റ്റംബർ,ഒക്ടോബർ,നവംബർ,ഡിസംബർ'
};

window.APP_STRINGS.ur = {
  app_title: 'حاضری رجسٹر',
  intro: 'چند سیکنڈ میں کلاس کی حاضری لیں، مہینے کا کل اور حاضری کا % دیکھیں، اور رجسٹر پرنٹ کریں۔ سارا ڈیٹا اسی آلے پر رہتا ہے۔',
  tab_day: 'روزانہ',
  tab_month: 'ماہانہ',
  tab_students: 'طلبہ',
  class_label: 'کلاس',
  date_label: 'تاریخ',
  today: 'آج',
  prev_day: 'پچھلا دن',
  next_day: 'اگلا دن',
  prev_month: 'پچھلا مہینہ',
  next_month: 'اگلا مہینہ',
  st_P: 'حاضر',
  st_A: 'غیر حاضر',
  st_T: 'دیر سے',
  st_V: 'رخصت',
  st_none: 'باقی',
  sh_P: 'ح',
  sh_A: 'غ',
  sh_T: 'د',
  sh_V: 'ر',
  sh_H: 'چ',
  holiday: 'چھٹی',
  mark_all: 'سب کو حاضر لگائیں',
  marked_present: '{n} طلبہ کو حاضر لگایا گیا۔',
  all_marked: 'سب کی حاضری پہلے سے لگی ہوئی ہے۔',
  clear_day: 'یہ دن مٹائیں',
  confirm_clear_day: '{date} کی ساری حاضری مٹا دیں؟',
  copy_absent: 'غیر حاضر فہرست کاپی کریں',
  absent_text: '{cls} · {date} · غیر حاضر ({n}): {list}',
  none_absent: 'اس دن کوئی غیر حاضر نہیں۔',
  marked_n: '{total} میں سے {n} کی حاضری لگی',
  tap_hint: 'بدلنے کے لیے نام پر ٹیپ کریں: حاضر ← غیر حاضر ← دیر سے ← رخصت ← باقی۔',
  search_ph: 'نام یا رول نمبر تلاش کریں',
  no_match: '“{q}” سے کوئی طالب علم نہیں ملا۔',
  holiday_sunday: 'اتوار کی چھٹی ہے۔',
  holiday_national: 'یہ قومی تعطیل کا دن ہے۔',
  holiday_marked: 'اس دن کو چھٹی کے طور پر رکھا گیا ہے۔',
  take_anyway: 'اس دن بھی حاضری لیں',
  make_holiday: 'چھٹی کا اعلان کریں',
  future_note: 'یہ تاریخ ابھی آنی ہے۔',
  no_students: 'اس کلاس میں ابھی کوئی طالب علم نہیں ہے۔',
  go_students: 'طلبہ شامل کریں',
  sample_note: 'یہ نمونے کی کلاس ہے، اس کی حاضری فرضی ہے تاکہ آپ ایپ آزما سکیں۔ “طلبہ” ٹیب میں اپنی کلاس شامل کریں، پھر نمونہ حذف کر دیں۔',
  sample_class: 'نمونہ · جماعت ششم الف',
  sample_names: 'عارف شیخ,عائشہ صدیقی,ارجن شرما,دیا پٹیل,فاطمہ خان,گرپریت سنگھ,عمران قریشی,کاویہ نائر,لکشمی راؤ,محمد علی,نیہا گپتا,پرنو جوشی,پریا داس,راہل یادو,ریا بنرجی,روہن مہتا,ثنا شیخ,سدھارتھ کلکرنی,تنوی دیسائی,زید انصاری',
  my_class: 'میری کلاس',
  month_hint: 'نشان بدلنے کے لیے خانے پر ٹیپ کریں۔ اوپر کسی تاریخ پر ٹیپ کر کے اسے چھٹی بنائیں، یا پھر سے اسکول کا دن بنائیں۔',
  sundays_off: 'اتوار اور قومی تعطیلات (26 جنوری، 15 اگست، 2 اکتوبر) بند',
  leave_counts: 'رخصت کو حاضر گنیں',
  min_pct: 'کم از کم حاضری %',
  late_note: 'دیر سے آنے والے حاضر گنے جاتے ہیں۔',
  leave_note: 'رخصت کو بھی حاضر گنا جاتا ہے۔',
  col_roll: 'رول',
  col_name: 'نام',
  col_days: 'دن',
  col_pct: '%',
  stat_days: 'جتنے دن حاضری لی گئی',
  stat_avg: 'کلاس کا اوسط',
  stat_below: '{p}% سے کم والے طلبہ',
  day_present: 'ہر دن حاضر',
  export_csv: 'CSV نکالیں',
  print_register: 'رجسٹر پرنٹ کریں',
  print_meta: 'کلاس: {cls} · مہینہ: {month}',
  printed_on: 'پرنٹ کی تاریخ: {date}',
  sign_teacher: 'کلاس ٹیچر',
  sign_principal: 'پرنسپل',
  school_name: 'اسکول کا نام (پرنٹ شدہ رجسٹر پر دکھے گا)',
  school_ph: 'مثلاً: گورنمنٹ ہائر سیکنڈری اسکول، لکھنؤ',
  class_settings: 'یہ کلاس',
  class_name: 'کلاس کا نام',
  class_ph: 'مثلاً: جماعت ہفتم ب',
  delete_class: 'یہ کلاس حذف کریں',
  confirm_delete_class: '“{name}” اور اس کی ساری حاضری حذف کر دیں؟ یہ واپس نہیں آئے گی۔',
  new_class: 'نئی کلاس شامل کریں',
  add_class: 'کلاس شامل کریں',
  class_added: '“{name}” کلاس شامل ہو گئی۔',
  renamed: 'کلاس کا نام محفوظ ہو گیا۔',
  students_n: '{n} طلبہ',
  add_student: 'ایک طالب علم شامل کریں',
  roll_ph: 'رول',
  name_ph: 'طالب علم کا نام',
  paste_title: 'طلبہ کی فہرست پیسٹ کریں',
  paste_help: 'ہر لائن میں ایک طالب علم: پہلے رول نمبر، پھر نام۔ جس لائن میں صرف نام ہو اسے اگلا رول نمبر مل جائے گا۔ Excel یا Google Sheets سے دو کالم سیدھے کاپی کر سکتے ہیں۔',
  paste_ph: 'مثلاً:\n1, عارف شیخ\n2, فاطمہ خان\nروہن مہتا',
  paste_add: 'یہ طلبہ شامل کریں',
  import_csv: 'CSV امپورٹ کریں',
  csv_help: 'یا رول نمبر اور نام کے کالم والی CSV فائل امپورٹ کریں۔ عنوان والی لائن خود بخود چھوڑ دی جاتی ہے۔',
  added_n: '{n} طلبہ شامل ہو گئے۔',
  nothing_added: 'کوئی نام نہیں ملا۔ لکھنے کا طریقہ جانچ لیں۔',
  dup_rolls: 'یہ رول نمبر ایک سے زیادہ بار ہیں: {list}',
  remove_student: '{name} کو ہٹائیں',
  confirm_remove: '{name} کو ہٹائیں؟ اس کلاس میں ان کی حاضری بھی مٹ جائے گی۔',
  need_name: 'براہِ کرم نام لکھیں۔',
  backup_title: 'بیک اپ اور ریسٹور',
  backup_help: 'حاضری صرف اسی براؤزر میں محفوظ ہوتی ہے۔ ہر ہفتے بیک اپ ڈاؤن لوڈ کریں، اور نئے فون یا کمپیوٹر پر اسے ریسٹور کریں۔',
  backup_dl: 'بیک اپ ڈاؤن لوڈ کریں',
  restore: 'بیک اپ ریسٹور کریں',
  restore_ok: 'بیک اپ ریسٹور ہو گیا: {n} کلاسیں۔',
  restore_bad: 'یہ حاضری رجسٹر کی بیک اپ فائل نہیں ہے۔',
  confirm_restore: 'اس آلے کی تمام کلاسوں کی جگہ بیک اپ والی کلاسیں رکھ دیں؟',
  help_1: 'آپ جتنے سیکشن پڑھاتے ہیں، ہر ایک کی الگ کلاس بنائیں۔ اسکول کی فہرست سے نام پیسٹ کریں یا CSV فائل امپورٹ کریں۔',
  help_2: 'روز صبح “سب کو حاضر لگائیں” دبائیں، پھر صرف غیر حاضر طلبہ پر ٹیپ کریں۔ 60 طلبہ کی حاضری بھی ایک منٹ سے کم میں لگ جاتی ہے۔',
  help_3: '“ماہانہ” ٹیب میں ہر طالب علم کا حاضری % دکھتا ہے۔ سرخ قطاریں کم از کم حد سے نیچے ہیں (CBSE کے مطابق 75% ضروری)، تاکہ آپ وقت پر والدین سے بات کر سکیں۔',
  help_4: 'مہینے کے آخر میں رجسٹر پرنٹ کریں (A4 افقی صفحہ) اور دستخط کریں، یا Excel / Google Sheets کے لیے CSV نکالیں۔',
  help_5: 'کلاس کی سرگرمی: کلاس مانیٹر سے اسمارٹ بورڈ پر حاضری لگوائیں۔ پھر طلبہ اپنا حاضری % خود نکالیں: (حاضر دن ÷ اسکول کے دن) × 100۔',
  help_6: 'آپ کا ڈیٹا اس آلے سے باہر نہیں جاتا۔ ہر ہفتے بیک اپ ڈاؤن لوڈ کریں تاکہ فون بدلنے پر کچھ ضائع نہ ہو۔',
  date_long: '{wd}، {d} {m} {y}',
  month_year: '{m} {y}',
  wd_full: 'اتوار,پیر,منگل,بدھ,جمعرات,جمعہ,ہفتہ',
  wd_min: 'ات,پیر,منگل,بدھ,جمعرات,جمعہ,ہفتہ',
  months: 'جنوری,فروری,مارچ,اپریل,مئی,جون,جولائی,اگست,ستمبر,اکتوبر,نومبر,دسمبر'
};
