/* Area & Volume Lab: UI strings. Keys must be identical in all 12 languages.
   Units (mm, cm, m, km), π and letters like r, h, l are maths symbols and stay in Latin script. */
window.APP_STRINGS = {};
window.APP_STRINGS.en = {
  app_title: 'Area & Volume Lab',
  intro: 'Pick a shape, type its measurements and see its area, perimeter, volume and surface area, with a drawing to scale and step-by-step working.',
  tab_calc: 'Calculator', tab_practice: 'Practice', tab_units: 'Unit converter',
  choose_shape: 'Choose a shape', grp_2d: '2D shapes', grp_3d: '3D solids',
  grp_2d_hint: 'Flat shapes: area and perimeter (Classes 6–9)', grp_3d_hint: 'Solids: volume and surface area (Classes 8–10)',
  measurements: 'Measurements', unit: 'Unit', pi_value: 'Value of π', sample: 'Sample values',
  results: 'Answers', working: 'Step-by-step working', other_units: 'Same answer in other units',
  real_life: 'In real life: {x}', fig_aria: 'Labelled drawing', fig_note: 'The drawing is to scale: change a number and the shape changes too.',
  approx_note: '≈ means the answer is rounded to 2 decimal places.',
  sh_square: 'Square', sh_rectangle: 'Rectangle', sh_tri_bh: 'Triangle (base & height)', sh_tri_heron: 'Triangle (3 sides, Heron)',
  sh_parallelogram: 'Parallelogram', sh_rhombus: 'Rhombus', sh_trapezium: 'Trapezium', sh_circle: 'Circle', sh_semicircle: 'Semicircle',
  sh_ring: 'Ring (circular path)', sh_cube: 'Cube', sh_cuboid: 'Cuboid', sh_cylinder: 'Cylinder', sh_cone: 'Cone', sh_sphere: 'Sphere',
  sh_hemisphere: 'Hemisphere', sh_frustum: 'Frustum of a cone',
  ex_square: 'a floor tile, a chessboard, a carrom board', ex_rectangle: 'a classroom floor, a cricket pitch, a phone screen',
  ex_tri_bh: 'a road sign, the side of a roof, a set square', ex_tri_heron: 'a triangular field whose three sides were measured',
  ex_parallelogram: 'a slanted parking space, a tile pattern', ex_rhombus: 'a kite, the diamond on playing cards',
  ex_trapezium: 'the side of a handbag, a field next to a road', ex_circle: 'a roti, a coin, a round park',
  ex_semicircle: 'a protractor, a half-moon window', ex_ring: 'a path around a round garden, a bangle',
  ex_cube: 'a dice, a Rubik\'s cube, a sugar cube', ex_cuboid: 'a brick, a matchbox, an almirah, a water tank',
  ex_cylinder: 'a gas cylinder, a pipe, a tin, a water tank', ex_cone: 'an ice-cream cone, a birthday cap, a tent',
  ex_sphere: 'a football, a ladoo, a marble', ex_hemisphere: 'a katori (bowl), the dome of a building',
  ex_frustum: 'a bucket, a steel glass, a lampshade',
  d_side: 'Side (a)', d_edge: 'Edge (a)', d_length: 'Length (l)', d_breadth: 'Breadth (b)', d_base: 'Base (b)', d_height: 'Height (h)',
  d_side_a: 'Side a', d_side_b: 'Side b', d_side_c: 'Side c', d_slant_side: 'Slanted side (a)',
  d_diag1: 'Diagonal d₁', d_diag2: 'Diagonal d₂', d_par_a: 'Parallel side a', d_par_b: 'Parallel side b',
  d_radius: 'Radius (r)', d_outer: 'Outer radius (R)', d_inner: 'Inner radius (r)', d_r1: 'Top radius (r₁)', d_r2: 'Bottom radius (r₂)',
  r_area: 'Area', r_perimeter: 'Perimeter', r_circumference: 'Circumference', r_diameter: 'Diameter', r_diagonal: 'Diagonal',
  r_s: 'Semi-perimeter (s)', r_side: 'Side (a)', r_leg: 'Slanted side (c)', r_width: 'Width of the path',
  r_volume: 'Volume', r_lsa: 'Lateral surface area (LSA)', r_csa: 'Curved surface area (CSA)', r_tsa: 'Total surface area (TSA)',
  r_sa: 'Surface area', r_slant: 'Slant height (l)', r_capacity: 'Capacity',
  err_positive: 'Type a number greater than 0 in every box.', err_big: 'Please use numbers up to {max}.',
  err_triangle: 'These sides cannot make a triangle. Any two sides together must be longer than the third side.',
  err_para: 'The height cannot be longer than the slanted side a.', err_ring: 'The outer radius R must be bigger than the inner radius r.',
  note_heron: 'Heron\'s formula needs only the three sides. You do not need the height.',
  note_trap: 'The perimeter here is for an isosceles trapezium (both slanted sides are equal).',
  note_cyl: 'TSA is for a closed cylinder. An open pipe has only the curved surface.',
  note_hemi: 'TSA is for a solid hemisphere (curved part + flat circle). The inside of a bowl is only the CSA.',
  note_frustum: 'Class 10: a frustum is a cone with its top cut off. r₁ and r₂ are the radii of the two circular ends.',
  note_pi: 'Tip: 22/7 gives neat answers when the radius is a multiple of 7.',
  u_ha: 'hectare', u_ml: 'millilitre', u_litre: 'litre',
  pr_title: 'Practice', pr_which: 'Questions on', pr_both: 'Both', pr_given: 'Given', pr_find: 'Find', pr_in_unit: '(answer in {u})',
  pr_answer: 'Your answer', pr_check: 'Check', pr_show: 'Show solution', pr_new: 'New question',
  pr_round: 'Use π = {pi}. Round your answer to 2 decimal places if needed.',
  pr_right: 'Correct! The answer is {ans}.', pr_wrong: 'Not quite. The correct answer is {ans}. Read the working below.',
  pr_enter: 'First type your answer as a number.', pr_score: 'Score: {c} out of {n}', pr_streak: 'Streak: {n} 🔥',
  ws_title: 'Worksheet: area and volume', ws_note: 'Make 10 fresh questions with an answer key, then print them. Answers use π = {pi}.',
  ws_make: 'Make a worksheet', ws_print: 'Print worksheet', ws_head: 'Name: ____________   Class: ______   Date: __________',
  ws_line: 'Answer: ______________', ws_answers: 'Answer key',
  cv_title: 'Convert units', cv_length: 'Length', cv_area: 'Area', cv_volume: 'Volume & capacity', cv_value: 'Value', cv_from: 'From unit',
  cv_unit_col: 'Unit', cv_value_col: 'Value',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km.',
  cv_rule_area: 'For area, square the length rule: 1 m = 100 cm, so 1 m² = 100 × 100 = 10,000 cm². Also 1 hectare = 10,000 m² and 1 km² = 100 hectares.',
  cv_rule_vol: 'For volume, cube the length rule: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³. Also 1 cm³ = 1 mL, 1000 cm³ = 1 litre and 1 m³ = 1000 litres.',
  help_title: 'How to use · Ideas for the classroom',
  tip1: 'Choose 2D or 3D, tap a shape and type its measurements. The answers change as you type.',
  tip2: 'Switch π between 22/7 and 3.14 and compare. Textbooks use 22/7 when the radius is a multiple of 7 because the answer comes out neat.',
  tip3: 'Read the working like a textbook solution: write the formula, put in the numbers, simplify, and give the answer with its unit.',
  tip4: 'Use the unit buttons and the converter to show why 1 m² is 10,000 cm² and not 100 cm².',
  tip5: 'Classroom activity: give each group a real object (a bucket, a tin, a sweets box). They measure it, guess its volume, then check here.',
  tip6: 'Practice gives new questions every time. Make a worksheet with an answer key for homework or a class test.'
};
window.APP_STRINGS.hi = {
  app_title: 'क्षेत्रफल और आयतन लैब',
  intro: 'कोई आकृति चुनें, उसकी माप लिखें और उसका क्षेत्रफल, परिमाप, आयतन और पृष्ठीय क्षेत्रफल देखें — नाप के अनुसार चित्र और चरणबद्ध हल के साथ।',
  tab_calc: 'कैलकुलेटर', tab_practice: 'अभ्यास', tab_units: 'इकाई बदलें',
  choose_shape: 'आकृति चुनें', grp_2d: '2D आकृतियाँ', grp_3d: '3D ठोस',
  grp_2d_hint: 'समतल आकृतियाँ: क्षेत्रफल और परिमाप (कक्षा 6–9)', grp_3d_hint: 'ठोस: आयतन और पृष्ठीय क्षेत्रफल (कक्षा 8–10)',
  measurements: 'माप', unit: 'इकाई', pi_value: 'π का मान', sample: 'नमूना मान',
  results: 'उत्तर', working: 'चरणबद्ध हल', other_units: 'यही उत्तर दूसरी इकाइयों में',
  real_life: 'असल ज़िंदगी में: {x}', fig_aria: 'नामांकित चित्र', fig_note: 'चित्र नाप के अनुसार है: कोई संख्या बदलें तो आकृति भी बदल जाती है।',
  approx_note: '≈ का मतलब है कि उत्तर को 2 दशमलव स्थानों तक पूर्णांकित किया गया है।',
  sh_square: 'वर्ग', sh_rectangle: 'आयत', sh_tri_bh: 'त्रिभुज (आधार और ऊँचाई)', sh_tri_heron: 'त्रिभुज (3 भुजाएँ, हीरोन)',
  sh_parallelogram: 'समांतर चतुर्भुज', sh_rhombus: 'समचतुर्भुज', sh_trapezium: 'समलंब', sh_circle: 'वृत्त', sh_semicircle: 'अर्धवृत्त',
  sh_ring: 'वलय (वृत्ताकार पथ)', sh_cube: 'घन', sh_cuboid: 'घनाभ', sh_cylinder: 'बेलन', sh_cone: 'शंकु', sh_sphere: 'गोला',
  sh_hemisphere: 'अर्धगोला', sh_frustum: 'शंकु का छिन्नक',
  ex_square: 'फ़र्श की टाइल, शतरंज की बिसात, कैरम बोर्ड', ex_rectangle: 'कक्षा का फ़र्श, क्रिकेट पिच, मोबाइल की स्क्रीन',
  ex_tri_bh: 'सड़क का संकेत-बोर्ड, छत का किनारा, सेट-स्क्वेयर', ex_tri_heron: 'एक तिकोना खेत जिसकी तीनों भुजाएँ नापी गई हों',
  ex_parallelogram: 'तिरछी पार्किंग की जगह, टाइलों का डिज़ाइन', ex_rhombus: 'पतंग, ताश के पत्तों पर ईंट का निशान',
  ex_trapezium: 'हैंडबैग का किनारा, सड़क के पास का खेत', ex_circle: 'रोटी, सिक्का, गोल पार्क',
  ex_semicircle: 'चाँदा (प्रोट्रैक्टर), अर्धचंद्र खिड़की', ex_ring: 'गोल बगीचे के चारों ओर का रास्ता, चूड़ी',
  ex_cube: 'पासा, रूबिक क्यूब, चीनी का क्यूब', ex_cuboid: 'ईंट, माचिस की डिब्बी, अलमारी, पानी की टंकी',
  ex_cylinder: 'गैस सिलेंडर, पाइप, डिब्बा, पानी की टंकी', ex_cone: 'आइसक्रीम कोन, जन्मदिन की टोपी, तंबू',
  ex_sphere: 'फ़ुटबॉल, लड्डू, कंचा', ex_hemisphere: 'कटोरी, इमारत का गुंबद',
  ex_frustum: 'बाल्टी, स्टील का गिलास, लैंपशेड',
  d_side: 'भुजा (a)', d_edge: 'किनारा (a)', d_length: 'लंबाई (l)', d_breadth: 'चौड़ाई (b)', d_base: 'आधार (b)', d_height: 'ऊँचाई (h)',
  d_side_a: 'भुजा a', d_side_b: 'भुजा b', d_side_c: 'भुजा c', d_slant_side: 'तिरछी भुजा (a)',
  d_diag1: 'विकर्ण d₁', d_diag2: 'विकर्ण d₂', d_par_a: 'समांतर भुजा a', d_par_b: 'समांतर भुजा b',
  d_radius: 'त्रिज्या (r)', d_outer: 'बाहरी त्रिज्या (R)', d_inner: 'भीतरी त्रिज्या (r)', d_r1: 'ऊपरी त्रिज्या (r₁)', d_r2: 'निचली त्रिज्या (r₂)',
  r_area: 'क्षेत्रफल', r_perimeter: 'परिमाप', r_circumference: 'परिधि', r_diameter: 'व्यास', r_diagonal: 'विकर्ण',
  r_s: 'अर्धपरिमाप (s)', r_side: 'भुजा (a)', r_leg: 'तिरछी भुजा (c)', r_width: 'रास्ते की चौड़ाई',
  r_volume: 'आयतन', r_lsa: 'पार्श्व पृष्ठीय क्षेत्रफल (LSA)', r_csa: 'वक्र पृष्ठीय क्षेत्रफल (CSA)', r_tsa: 'संपूर्ण पृष्ठीय क्षेत्रफल (TSA)',
  r_sa: 'पृष्ठीय क्षेत्रफल', r_slant: 'तिर्यक ऊँचाई (l)', r_capacity: 'धारिता',
  err_positive: 'हर खाने में 0 से बड़ी संख्या लिखें।', err_big: 'कृपया {max} तक की संख्याएँ ही लिखें।',
  err_triangle: 'इन भुजाओं से त्रिभुज नहीं बन सकता। किन्हीं दो भुजाओं का योग तीसरी भुजा से बड़ा होना चाहिए।',
  err_para: 'ऊँचाई तिरछी भुजा a से बड़ी नहीं हो सकती।', err_ring: 'बाहरी त्रिज्या R, भीतरी त्रिज्या r से बड़ी होनी चाहिए।',
  note_heron: 'हीरोन के सूत्र में सिर्फ़ तीनों भुजाएँ चाहिए, ऊँचाई की ज़रूरत नहीं।',
  note_trap: 'यहाँ परिमाप समद्विबाहु समलंब का है (दोनों तिरछी भुजाएँ बराबर)।',
  note_cyl: 'TSA बंद बेलन का है। खुले पाइप में सिर्फ़ वक्र पृष्ठ होता है।',
  note_hemi: 'TSA ठोस अर्धगोले का है (वक्र भाग + सपाट वृत्त)। कटोरी के अंदर का हिस्सा सिर्फ़ CSA है।',
  note_frustum: 'कक्षा 10: छिन्नक वह शंकु है जिसका ऊपरी भाग काट दिया गया हो। r₁ और r₂ दोनों वृत्ताकार सिरों की त्रिज्याएँ हैं।',
  note_pi: 'सुझाव: जब त्रिज्या 7 का गुणज हो, तो 22/7 से उत्तर साफ़-सुथरा आता है।',
  u_ha: 'हेक्टेयर', u_ml: 'मिलीलीटर', u_litre: 'लीटर',
  pr_title: 'अभ्यास', pr_which: 'प्रश्न किस पर', pr_both: 'दोनों', pr_given: 'दिया है', pr_find: 'ज्ञात करें', pr_in_unit: '(उत्तर {u} में)',
  pr_answer: 'आपका उत्तर', pr_check: 'जाँचें', pr_show: 'हल दिखाएँ', pr_new: 'नया प्रश्न',
  pr_round: 'π = {pi} लें। ज़रूरत हो तो उत्तर को 2 दशमलव स्थानों तक पूर्णांकित करें।',
  pr_right: 'सही! उत्तर {ans} है।', pr_wrong: 'थोड़ा चूक गए। सही उत्तर {ans} है। नीचे हल पढ़ें।',
  pr_enter: 'पहले अपना उत्तर संख्या में लिखें।', pr_score: 'अंक: {n} में से {c}', pr_streak: 'लगातार सही: {n} 🔥',
  ws_title: 'वर्कशीट: क्षेत्रफल और आयतन', ws_note: '10 नए प्रश्न उत्तर-कुंजी के साथ बनाएँ और प्रिंट करें। उत्तरों में π = {pi} लिया गया है।',
  ws_make: 'वर्कशीट बनाएँ', ws_print: 'वर्कशीट प्रिंट करें', ws_head: 'नाम: ____________   कक्षा: ______   दिनांक: __________',
  ws_line: 'उत्तर: ______________', ws_answers: 'उत्तर-कुंजी',
  cv_title: 'इकाई बदलें', cv_length: 'लंबाई', cv_area: 'क्षेत्रफल', cv_volume: 'आयतन और धारिता', cv_value: 'मान', cv_from: 'किस इकाई से',
  cv_unit_col: 'इकाई', cv_value_col: 'मान',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km।',
  cv_rule_area: 'क्षेत्रफल के लिए लंबाई वाले नियम का वर्ग करें: 1 m = 100 cm, इसलिए 1 m² = 100 × 100 = 10,000 cm²। साथ ही 1 हेक्टेयर = 10,000 m² और 1 km² = 100 हेक्टेयर।',
  cv_rule_vol: 'आयतन के लिए लंबाई वाले नियम का घन करें: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³। साथ ही 1 cm³ = 1 mL, 1000 cm³ = 1 लीटर और 1 m³ = 1000 लीटर।',
  help_title: 'कैसे इस्तेमाल करें · कक्षा के लिए सुझाव',
  tip1: '2D या 3D चुनें, किसी आकृति पर टैप करें और उसकी माप लिखें। लिखते-लिखते उत्तर बदलते जाते हैं।',
  tip2: 'π को 22/7 और 3.14 के बीच बदलकर तुलना करें। जब त्रिज्या 7 का गुणज हो, तो किताबें 22/7 लेती हैं क्योंकि उत्तर साफ़ आता है।',
  tip3: 'हल को किताब की तरह पढ़ें: सूत्र लिखें, संख्याएँ रखें, सरल करें और उत्तर इकाई के साथ लिखें।',
  tip4: 'इकाई वाले बटन और कन्वर्टर से दिखाएँ कि 1 m² में 10,000 cm² होते हैं, 100 cm² नहीं।',
  tip5: 'कक्षा गतिविधि: हर समूह को एक असली चीज़ दें (बाल्टी, डिब्बा, मिठाई का डिब्बा)। वे उसे नापें, आयतन का अनुमान लगाएँ और फिर यहाँ जाँचें।',
  tip6: 'अभ्यास में हर बार नए प्रश्न आते हैं। गृहकार्य या कक्षा टेस्ट के लिए उत्तर-कुंजी वाली वर्कशीट बनाएँ।'
};
window.APP_STRINGS.bn = {
  app_title: 'ক্ষেত্রফল ও আয়তন ল্যাব',
  intro: 'একটি আকার বেছে নিন, তার মাপ লিখুন আর দেখুন তার ক্ষেত্রফল, পরিসীমা, আয়তন ও তলের ক্ষেত্রফল — মাপমতো ছবি আর ধাপে ধাপে সমাধানসহ।',
  tab_calc: 'ক্যালকুলেটর', tab_practice: 'অনুশীলন', tab_units: 'একক বদল',
  choose_shape: 'আকার বেছে নিন', grp_2d: '2D আকার', grp_3d: '3D ঘনবস্তু',
  grp_2d_hint: 'সমতল আকার: ক্ষেত্রফল ও পরিসীমা (ষষ্ঠ–নবম শ্রেণি)', grp_3d_hint: 'ঘনবস্তু: আয়তন ও তলের ক্ষেত্রফল (অষ্টম–দশম শ্রেণি)',
  measurements: 'মাপ', unit: 'একক', pi_value: 'π-এর মান', sample: 'নমুনা মান',
  results: 'উত্তর', working: 'ধাপে ধাপে সমাধান', other_units: 'একই উত্তর অন্য এককে',
  real_life: 'বাস্তব জীবনে: {x}', fig_aria: 'চিহ্নিত ছবি', fig_note: 'ছবিটি মাপমতো আঁকা: কোনো সংখ্যা বদলালে আকারও বদলে যায়।',
  approx_note: '≈ মানে উত্তরটি দশমিকের পরে 2 ঘর পর্যন্ত আসন্ন মান।',
  sh_square: 'বর্গক্ষেত্র', sh_rectangle: 'আয়তক্ষেত্র', sh_tri_bh: 'ত্রিভুজ (ভূমি ও উচ্চতা)', sh_tri_heron: 'ত্রিভুজ (3 বাহু, হেরন)',
  sh_parallelogram: 'সামান্তরিক', sh_rhombus: 'রম্বস', sh_trapezium: 'ট্রাপিজিয়াম', sh_circle: 'বৃত্ত', sh_semicircle: 'অর্ধবৃত্ত',
  sh_ring: 'বলয় (বৃত্তাকার পথ)', sh_cube: 'ঘনক', sh_cuboid: 'আয়তঘন', sh_cylinder: 'চোঙ', sh_cone: 'শঙ্কু', sh_sphere: 'গোলক',
  sh_hemisphere: 'অর্ধগোলক', sh_frustum: 'শঙ্কুর ছিন্নক',
  ex_square: 'মেঝের টালি, দাবার বোর্ড, ক্যারম বোর্ড', ex_rectangle: 'ক্লাসঘরের মেঝে, ক্রিকেট পিচ, মোবাইলের স্ক্রিন',
  ex_tri_bh: 'রাস্তার সংকেত বোর্ড, চালের পাশ, সেট-স্কোয়ার', ex_tri_heron: 'এমন এক ত্রিভুজাকার জমি যার তিনটি বাহু মাপা হয়েছে',
  ex_parallelogram: 'হেলানো পার্কিংয়ের জায়গা, টালির নকশা', ex_rhombus: 'ঘুড়ি, তাসের রুইতনের চিহ্ন',
  ex_trapezium: 'হাতব্যাগের পাশ, রাস্তার ধারের জমি', ex_circle: 'রুটি, মুদ্রা, গোল পার্ক',
  ex_semicircle: 'চাঁদা (প্রোট্র্যাক্টর), অর্ধচন্দ্র জানালা', ex_ring: 'গোল বাগানের চারপাশের রাস্তা, চুড়ি',
  ex_cube: 'লুডোর ছক্কা, রুবিক কিউব, চিনির কিউব', ex_cuboid: 'ইট, দেশলাই বাক্স, আলমারি, জলের ট্যাঙ্ক',
  ex_cylinder: 'গ্যাস সিলিন্ডার, পাইপ, টিনের কৌটো, জলের ট্যাঙ্ক', ex_cone: 'আইসক্রিম কোন, জন্মদিনের টুপি, তাঁবু',
  ex_sphere: 'ফুটবল, লাড্ডু, মার্বেল', ex_hemisphere: 'বাটি, বাড়ির গম্বুজ',
  ex_frustum: 'বালতি, স্টিলের গ্লাস, ল্যাম্পশেড',
  d_side: 'বাহু (a)', d_edge: 'ধার (a)', d_length: 'দৈর্ঘ্য (l)', d_breadth: 'প্রস্থ (b)', d_base: 'ভূমি (b)', d_height: 'উচ্চতা (h)',
  d_side_a: 'বাহু a', d_side_b: 'বাহু b', d_side_c: 'বাহু c', d_slant_side: 'হেলানো বাহু (a)',
  d_diag1: 'কর্ণ d₁', d_diag2: 'কর্ণ d₂', d_par_a: 'সমান্তরাল বাহু a', d_par_b: 'সমান্তরাল বাহু b',
  d_radius: 'ব্যাসার্ধ (r)', d_outer: 'বাইরের ব্যাসার্ধ (R)', d_inner: 'ভেতরের ব্যাসার্ধ (r)', d_r1: 'ওপরের ব্যাসার্ধ (r₁)', d_r2: 'নিচের ব্যাসার্ধ (r₂)',
  r_area: 'ক্ষেত্রফল', r_perimeter: 'পরিসীমা', r_circumference: 'পরিধি', r_diameter: 'ব্যাস', r_diagonal: 'কর্ণ',
  r_s: 'অর্ধপরিসীমা (s)', r_side: 'বাহু (a)', r_leg: 'হেলানো বাহু (c)', r_width: 'রাস্তার চওড়া',
  r_volume: 'আয়তন', r_lsa: 'পার্শ্বতলের ক্ষেত্রফল (LSA)', r_csa: 'বক্রতলের ক্ষেত্রফল (CSA)', r_tsa: 'সমগ্রতলের ক্ষেত্রফল (TSA)',
  r_sa: 'তলের ক্ষেত্রফল', r_slant: 'হেলানো উচ্চতা (l)', r_capacity: 'ধারণক্ষমতা',
  err_positive: 'প্রতিটি ঘরে 0-এর চেয়ে বড় সংখ্যা লিখুন।', err_big: 'অনুগ্রহ করে {max} পর্যন্ত সংখ্যা ব্যবহার করুন।',
  err_triangle: 'এই বাহুগুলো দিয়ে ত্রিভুজ হয় না। যেকোনো দুটি বাহুর যোগফল তৃতীয় বাহুর চেয়ে বড় হতে হবে।',
  err_para: 'উচ্চতা হেলানো বাহু a-এর চেয়ে বড় হতে পারে না।', err_ring: 'বাইরের ব্যাসার্ধ R ভেতরের ব্যাসার্ধ r-এর চেয়ে বড় হতে হবে।',
  note_heron: 'হেরনের সূত্রে শুধু তিনটি বাহু লাগে, উচ্চতা লাগে না।',
  note_trap: 'এখানে পরিসীমা সমদ্বিবাহু ট্রাপিজিয়ামের (দুটি হেলানো বাহু সমান)।',
  note_cyl: 'TSA হলো বন্ধ চোঙের। খোলা পাইপে শুধু বক্রতল থাকে।',
  note_hemi: 'TSA হলো নিরেট অর্ধগোলকের (বাঁকা অংশ + সমতল বৃত্ত)। বাটির ভেতরের অংশ শুধু CSA।',
  note_frustum: 'দশম শ্রেণি: ছিন্নক হলো ওপরের অংশ কেটে ফেলা শঙ্কু। r₁ আর r₂ দুই বৃত্তাকার প্রান্তের ব্যাসার্ধ।',
  note_pi: 'পরামর্শ: ব্যাসার্ধ 7-এর গুণিতক হলে 22/7 নিলে উত্তর সুন্দর পূর্ণ সংখ্যায় আসে।',
  u_ha: 'হেক্টর', u_ml: 'মিলিলিটার', u_litre: 'লিটার',
  pr_title: 'অনুশীলন', pr_which: 'প্রশ্নের বিষয়', pr_both: 'দুটোই', pr_given: 'দেওয়া আছে', pr_find: 'নির্ণয় করো', pr_in_unit: '(উত্তর {u}-এ)',
  pr_answer: 'তোমার উত্তর', pr_check: 'যাচাই করো', pr_show: 'সমাধান দেখাও', pr_new: 'নতুন প্রশ্ন',
  pr_round: 'π = {pi} ধরো। দরকার হলে উত্তর দশমিকের পরে 2 ঘর পর্যন্ত লেখো।',
  pr_right: 'ঠিক! উত্তর {ans}।', pr_wrong: 'একটু ভুল হলো। সঠিক উত্তর {ans}। নিচের সমাধানটি পড়ো।',
  pr_enter: 'আগে তোমার উত্তর সংখ্যায় লেখো।', pr_score: 'স্কোর: {n}-এর মধ্যে {c}', pr_streak: 'টানা ঠিক: {n} 🔥',
  ws_title: 'ওয়ার্কশিট: ক্ষেত্রফল ও আয়তন', ws_note: 'উত্তরমালাসহ 10টি নতুন প্রশ্ন তৈরি করে প্রিন্ট করুন। উত্তরে π = {pi} ধরা হয়েছে।',
  ws_make: 'ওয়ার্কশিট তৈরি করুন', ws_print: 'ওয়ার্কশিট প্রিন্ট করুন', ws_head: 'নাম: ____________   শ্রেণি: ______   তারিখ: __________',
  ws_line: 'উত্তর: ______________', ws_answers: 'উত্তরমালা',
  cv_title: 'একক বদলান', cv_length: 'দৈর্ঘ্য', cv_area: 'ক্ষেত্রফল', cv_volume: 'আয়তন ও ধারণক্ষমতা', cv_value: 'মান', cv_from: 'কোন একক থেকে',
  cv_unit_col: 'একক', cv_value_col: 'মান',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km।',
  cv_rule_area: 'ক্ষেত্রফলের জন্য দৈর্ঘ্যের নিয়মের বর্গ করুন: 1 m = 100 cm, তাই 1 m² = 100 × 100 = 10,000 cm²। এছাড়া 1 হেক্টর = 10,000 m² আর 1 km² = 100 হেক্টর।',
  cv_rule_vol: 'আয়তনের জন্য দৈর্ঘ্যের নিয়মের ঘন করুন: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³। এছাড়া 1 cm³ = 1 mL, 1000 cm³ = 1 লিটার আর 1 m³ = 1000 লিটার।',
  help_title: 'কীভাবে ব্যবহার করবেন · ক্লাসের জন্য ভাবনা',
  tip1: '2D বা 3D বেছে নিন, একটি আকারে ট্যাপ করুন আর তার মাপ লিখুন। লেখার সঙ্গে সঙ্গেই উত্তর বদলায়।',
  tip2: 'π-কে 22/7 আর 3.14-এর মধ্যে বদলে তুলনা করুন। ব্যাসার্ধ 7-এর গুণিতক হলে বইয়ে 22/7 নেওয়া হয়, কারণ উত্তর পরিষ্কার আসে।',
  tip3: 'সমাধানটি বইয়ের মতো পড়ুন: সূত্র লিখুন, সংখ্যা বসান, সরল করুন আর এককসহ উত্তর লিখুন।',
  tip4: 'একক বোতাম আর কনভার্টার দিয়ে দেখান কেন 1 m² = 10,000 cm², 100 cm² নয়।',
  tip5: 'ক্লাসের কাজ: প্রতিটি দলকে একটি আসল জিনিস দিন (বালতি, কৌটো, মিষ্টির বাক্স)। তারা মেপে আয়তন আন্দাজ করবে, তারপর এখানে মিলিয়ে দেখবে।',
  tip6: 'অনুশীলনে প্রতিবার নতুন প্রশ্ন আসে। বাড়ির কাজ বা ক্লাস টেস্টের জন্য উত্তরমালাসহ ওয়ার্কশিট তৈরি করুন।'
};
window.APP_STRINGS.mr = {
  app_title: 'क्षेत्रफळ व घनफळ लॅब',
  intro: 'एखादा आकार निवडा, त्याची मापे लिहा आणि त्याचे क्षेत्रफळ, परिमिती, घनफळ व पृष्ठफळ पाहा — मापानुसार आकृती आणि टप्प्याटप्प्याने उकलीसह.',
  tab_calc: 'कॅल्क्युलेटर', tab_practice: 'सराव', tab_units: 'एकक रूपांतर',
  choose_shape: 'आकार निवडा', grp_2d: '2D आकार', grp_3d: '3D घनाकृती',
  grp_2d_hint: 'सपाट आकार: क्षेत्रफळ आणि परिमिती (इयत्ता 6–9)', grp_3d_hint: 'घनाकृती: घनफळ आणि पृष्ठफळ (इयत्ता 8–10)',
  measurements: 'मापे', unit: 'एकक', pi_value: 'π ची किंमत', sample: 'नमुना किमती',
  results: 'उत्तरे', working: 'टप्प्याटप्प्याने उकल', other_units: 'हेच उत्तर इतर एककांत',
  real_life: 'रोजच्या जीवनात: {x}', fig_aria: 'नावे दिलेली आकृती', fig_note: 'आकृती मापानुसार आहे: एखादी संख्या बदलली की आकारही बदलतो.',
  approx_note: '≈ म्हणजे उत्तर दशांश चिन्हानंतर 2 अंकांपर्यंत पूर्णांकित केले आहे.',
  sh_square: 'चौरस', sh_rectangle: 'आयत', sh_tri_bh: 'त्रिकोण (पाया आणि उंची)', sh_tri_heron: 'त्रिकोण (3 बाजू, हेरॉन)',
  sh_parallelogram: 'समांतरभुज चौकोन', sh_rhombus: 'समभुज चौकोन', sh_trapezium: 'समलंब चौकोन', sh_circle: 'वर्तुळ', sh_semicircle: 'अर्धवर्तुळ',
  sh_ring: 'कंकण (वर्तुळाकार मार्ग)', sh_cube: 'घन', sh_cuboid: 'इष्टिकाचिती', sh_cylinder: 'वृत्तचिती', sh_cone: 'शंकू', sh_sphere: 'गोल',
  sh_hemisphere: 'अर्धगोल', sh_frustum: 'शंकूचा छेद',
  ex_square: 'फरशीची टाइल, बुद्धिबळाचा पट, कॅरम बोर्ड', ex_rectangle: 'वर्गाची फरशी, क्रिकेटची खेळपट्टी, मोबाइलची स्क्रीन',
  ex_tri_bh: 'रस्त्यावरचा फलक, छपराची बाजू, गुणिया', ex_tri_heron: 'तिन्ही बाजू मोजलेले एक त्रिकोणी शेत',
  ex_parallelogram: 'तिरकी पार्किंगची जागा, टाइल्सची नक्षी', ex_rhombus: 'पतंग, पत्त्यांवरील चौकटची खूण',
  ex_trapezium: 'हँडबॅगची बाजू, रस्त्याशेजारचे शेत', ex_circle: 'पोळी, नाणे, गोल बाग',
  ex_semicircle: 'कोनमापक, अर्धचंद्राकृती खिडकी', ex_ring: 'गोल बागेभोवतीचा रस्ता, बांगडी',
  ex_cube: 'फासा, रुबिक क्यूब, साखरेचा खडा', ex_cuboid: 'वीट, आगपेटी, कपाट, पाण्याची टाकी',
  ex_cylinder: 'गॅस सिलिंडर, पाइप, डबा, पाण्याची टाकी', ex_cone: 'आइसक्रीम कोन, वाढदिवसाची टोपी, तंबू',
  ex_sphere: 'फुटबॉल, लाडू, गोटी', ex_hemisphere: 'वाटी, इमारतीचा घुमट',
  ex_frustum: 'बादली, स्टीलचा ग्लास, लॅम्पशेड',
  d_side: 'बाजू (a)', d_edge: 'कडा (a)', d_length: 'लांबी (l)', d_breadth: 'रुंदी (b)', d_base: 'पाया (b)', d_height: 'उंची (h)',
  d_side_a: 'बाजू a', d_side_b: 'बाजू b', d_side_c: 'बाजू c', d_slant_side: 'तिरकी बाजू (a)',
  d_diag1: 'कर्ण d₁', d_diag2: 'कर्ण d₂', d_par_a: 'समांतर बाजू a', d_par_b: 'समांतर बाजू b',
  d_radius: 'त्रिज्या (r)', d_outer: 'बाहेरची त्रिज्या (R)', d_inner: 'आतली त्रिज्या (r)', d_r1: 'वरची त्रिज्या (r₁)', d_r2: 'खालची त्रिज्या (r₂)',
  r_area: 'क्षेत्रफळ', r_perimeter: 'परिमिती', r_circumference: 'परीघ', r_diameter: 'व्यास', r_diagonal: 'कर्ण',
  r_s: 'अर्धपरिमिती (s)', r_side: 'बाजू (a)', r_leg: 'तिरकी बाजू (c)', r_width: 'रस्त्याची रुंदी',
  r_volume: 'घनफळ', r_lsa: 'पार्श्वपृष्ठफळ (LSA)', r_csa: 'वक्रपृष्ठफळ (CSA)', r_tsa: 'एकूण पृष्ठफळ (TSA)',
  r_sa: 'पृष्ठफळ', r_slant: 'तिरकी उंची (l)', r_capacity: 'धारकता',
  err_positive: 'प्रत्येक चौकटीत 0 पेक्षा मोठी संख्या लिहा.', err_big: 'कृपया {max} पर्यंतच्या संख्या वापरा.',
  err_triangle: 'या बाजूंनी त्रिकोण होऊ शकत नाही. कोणत्याही दोन बाजूंची बेरीज तिसऱ्या बाजूपेक्षा मोठी असली पाहिजे.',
  err_para: 'उंची तिरकी बाजू a पेक्षा मोठी असू शकत नाही.', err_ring: 'बाहेरची त्रिज्या R ही आतल्या त्रिज्या r पेक्षा मोठी असली पाहिजे.',
  note_heron: 'हेरॉनच्या सूत्रासाठी फक्त तीन बाजू लागतात, उंचीची गरज नाही.',
  note_trap: 'येथील परिमिती समद्विभुज समलंब चौकोनाची आहे (दोन्ही तिरक्या बाजू समान).',
  note_cyl: 'TSA बंद वृत्तचितीचे आहे. उघड्या पाइपला फक्त वक्रपृष्ठ असते.',
  note_hemi: 'TSA भरीव अर्धगोलाचे आहे (वक्र भाग + सपाट वर्तुळ). वाटीचा आतला भाग फक्त CSA असतो.',
  note_frustum: 'इयत्ता 10: शंकूचा वरचा भाग कापल्यावर उरतो तो शंकूचा छेद. r₁ आणि r₂ या दोन वर्तुळाकार टोकांच्या त्रिज्या आहेत.',
  note_pi: 'टीप: त्रिज्या 7 च्या पटीत असेल तर 22/7 घेतल्यास उत्तर नेटके येते.',
  u_ha: 'हेक्टर', u_ml: 'मिलिलिटर', u_litre: 'लिटर',
  pr_title: 'सराव', pr_which: 'प्रश्नांचा विषय', pr_both: 'दोन्ही', pr_given: 'दिलेले', pr_find: 'काढा', pr_in_unit: '(उत्तर {u} मध्ये)',
  pr_answer: 'तुमचे उत्तर', pr_check: 'तपासा', pr_show: 'उकल दाखवा', pr_new: 'नवीन प्रश्न',
  pr_round: 'π = {pi} घ्या. गरज असल्यास उत्तर दशांश चिन्हानंतर 2 अंकांपर्यंत पूर्णांकित करा.',
  pr_right: 'बरोबर! उत्तर {ans} आहे.', pr_wrong: 'थोडक्यात चुकले. बरोबर उत्तर {ans} आहे. खालची उकल वाचा.',
  pr_enter: 'आधी तुमचे उत्तर संख्येत लिहा.', pr_score: 'गुण: {n} पैकी {c}', pr_streak: 'सलग बरोबर: {n} 🔥',
  ws_title: 'वर्कशीट: क्षेत्रफळ आणि घनफळ', ws_note: 'उत्तरसूचीसह 10 नवीन प्रश्न तयार करा आणि प्रिंट करा. उत्तरांत π = {pi} घेतले आहे.',
  ws_make: 'वर्कशीट तयार करा', ws_print: 'वर्कशीट प्रिंट करा', ws_head: 'नाव: ____________   इयत्ता: ______   दिनांक: __________',
  ws_line: 'उत्तर: ______________', ws_answers: 'उत्तरसूची',
  cv_title: 'एकक बदला', cv_length: 'लांबी', cv_area: 'क्षेत्रफळ', cv_volume: 'घनफळ व धारकता', cv_value: 'किंमत', cv_from: 'कोणत्या एककातून',
  cv_unit_col: 'एकक', cv_value_col: 'किंमत',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km.',
  cv_rule_area: 'क्षेत्रफळासाठी लांबीच्या नियमाचा वर्ग करा: 1 m = 100 cm, म्हणून 1 m² = 100 × 100 = 10,000 cm². तसेच 1 हेक्टर = 10,000 m² आणि 1 km² = 100 हेक्टर.',
  cv_rule_vol: 'घनफळासाठी लांबीच्या नियमाचा घन करा: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³. तसेच 1 cm³ = 1 mL, 1000 cm³ = 1 लिटर आणि 1 m³ = 1000 लिटर.',
  help_title: 'कसे वापरायचे · वर्गासाठी कल्पना',
  tip1: '2D किंवा 3D निवडा, एखाद्या आकारावर टॅप करा आणि त्याची मापे लिहा. लिहिता लिहिताच उत्तरे बदलतात.',
  tip2: 'π ला 22/7 आणि 3.14 मध्ये बदलून तुलना करा. त्रिज्या 7 च्या पटीत असेल तर पुस्तकात 22/7 घेतात, कारण उत्तर नेटके येते.',
  tip3: 'उकल पुस्तकासारखी वाचा: सूत्र लिहा, संख्या ठेवा, सोपे करा आणि उत्तर एककासह लिहा.',
  tip4: 'एककाची बटणे आणि कन्व्हर्टर वापरून दाखवा की 1 m² म्हणजे 10,000 cm², 100 cm² नाही.',
  tip5: 'वर्गातील उपक्रम: प्रत्येक गटाला एक खरी वस्तू द्या (बादली, डबा, मिठाईचा खोका). ते ती मोजतील, घनफळाचा अंदाज करतील आणि मग इथे तपासतील.',
  tip6: 'सरावात दर वेळी नवीन प्रश्न येतात. गृहपाठ किंवा वर्ग चाचणीसाठी उत्तरसूचीसह वर्कशीट तयार करा.'
};
window.APP_STRINGS.gu = {
  app_title: 'ક્ષેત્રફળ અને ઘનફળ લૅબ',
  intro: 'કોઈ આકાર પસંદ કરો, તેનાં માપ લખો અને તેનું ક્ષેત્રફળ, પરિમિતિ, ઘનફળ અને પૃષ્ઠફળ જુઓ — માપ પ્રમાણેની આકૃતિ અને પગલાવાર ઉકેલ સાથે.',
  tab_calc: 'કૅલ્ક્યુલેટર', tab_practice: 'મહાવરો', tab_units: 'એકમ રૂપાંતર',
  choose_shape: 'આકાર પસંદ કરો', grp_2d: '2D આકારો', grp_3d: '3D ઘન પદાર્થો',
  grp_2d_hint: 'સપાટ આકારો: ક્ષેત્રફળ અને પરિમિતિ (ધોરણ 6–9)', grp_3d_hint: 'ઘન પદાર્થો: ઘનફળ અને પૃષ્ઠફળ (ધોરણ 8–10)',
  measurements: 'માપ', unit: 'એકમ', pi_value: 'π ની કિંમત', sample: 'નમૂનાની કિંમતો',
  results: 'જવાબો', working: 'પગલાવાર ઉકેલ', other_units: 'આ જ જવાબ બીજા એકમોમાં',
  real_life: 'રોજિંદા જીવનમાં: {x}', fig_aria: 'નામ સાથેની આકૃતિ', fig_note: 'આકૃતિ માપ પ્રમાણે છે: કોઈ સંખ્યા બદલો તો આકાર પણ બદલાય છે.',
  approx_note: '≈ એટલે જવાબને દશાંશ પછી 2 અંક સુધી રાઉન્ડ કર્યો છે.',
  sh_square: 'ચોરસ', sh_rectangle: 'લંબચોરસ', sh_tri_bh: 'ત્રિકોણ (પાયો અને ઊંચાઈ)', sh_tri_heron: 'ત્રિકોણ (3 બાજુ, હેરોન)',
  sh_parallelogram: 'સમાંતરબાજુ ચતુષ્કોણ', sh_rhombus: 'સમબાજુ ચતુષ્કોણ', sh_trapezium: 'સમલંબ ચતુષ્કોણ', sh_circle: 'વર્તુળ', sh_semicircle: 'અર્ધવર્તુળ',
  sh_ring: 'વલય (વર્તુળાકાર રસ્તો)', sh_cube: 'સમઘન', sh_cuboid: 'લંબઘન', sh_cylinder: 'નળાકાર', sh_cone: 'શંકુ', sh_sphere: 'ગોલક',
  sh_hemisphere: 'અર્ધગોલક', sh_frustum: 'શંકુનો આડછેદ',
  ex_square: 'ફરસની ટાઇલ, શતરંજનું પાટિયું, કૅરમ બોર્ડ', ex_rectangle: 'વર્ગખંડની ફરસ, ક્રિકેટની પીચ, મોબાઇલની સ્ક્રીન',
  ex_tri_bh: 'રસ્તાનું ચિહ્ન-પાટિયું, છાપરાની બાજુ, કાટખૂણિયું', ex_tri_heron: 'ત્રણેય બાજુ માપેલું એક ત્રિકોણ આકારનું ખેતર',
  ex_parallelogram: 'ત્રાંસી પાર્કિંગની જગ્યા, ટાઇલ્સની ભાત', ex_rhombus: 'પતંગ, પત્તાં પરનું ચોકટનું નિશાન',
  ex_trapezium: 'હૅન્ડબૅગની બાજુ, રસ્તાને અડીને આવેલું ખેતર', ex_circle: 'રોટલી, સિક્કો, ગોળ બગીચો',
  ex_semicircle: 'કોણમાપક, અર્ધચંદ્રાકાર બારી', ex_ring: 'ગોળ બગીચાની ફરતે રસ્તો, બંગડી',
  ex_cube: 'પાસો, રુબિક ક્યુબ, ખાંડનો ટુકડો', ex_cuboid: 'ઈંટ, દીવાસળીની પેટી, કબાટ, પાણીની ટાંકી',
  ex_cylinder: 'ગૅસ સિલિન્ડર, પાઇપ, ડબ્બો, પાણીની ટાંકી', ex_cone: 'આઇસક્રીમ કોન, જન્મદિવસની ટોપી, તંબુ',
  ex_sphere: 'ફૂટબૉલ, લાડુ, લખોટી', ex_hemisphere: 'વાટકી, મકાનનો ઘુમ્મટ',
  ex_frustum: 'ડોલ, સ્ટીલનો ગ્લાસ, લૅમ્પશેડ',
  d_side: 'બાજુ (a)', d_edge: 'ધાર (a)', d_length: 'લંબાઈ (l)', d_breadth: 'પહોળાઈ (b)', d_base: 'પાયો (b)', d_height: 'ઊંચાઈ (h)',
  d_side_a: 'બાજુ a', d_side_b: 'બાજુ b', d_side_c: 'બાજુ c', d_slant_side: 'ત્રાંસી બાજુ (a)',
  d_diag1: 'વિકર્ણ d₁', d_diag2: 'વિકર્ણ d₂', d_par_a: 'સમાંતર બાજુ a', d_par_b: 'સમાંતર બાજુ b',
  d_radius: 'ત્રિજ્યા (r)', d_outer: 'બહારની ત્રિજ્યા (R)', d_inner: 'અંદરની ત્રિજ્યા (r)', d_r1: 'ઉપરની ત્રિજ્યા (r₁)', d_r2: 'નીચેની ત્રિજ્યા (r₂)',
  r_area: 'ક્ષેત્રફળ', r_perimeter: 'પરિમિતિ', r_circumference: 'પરિઘ', r_diameter: 'વ્યાસ', r_diagonal: 'વિકર્ણ',
  r_s: 'અર્ધપરિમિતિ (s)', r_side: 'બાજુ (a)', r_leg: 'ત્રાંસી બાજુ (c)', r_width: 'રસ્તાની પહોળાઈ',
  r_volume: 'ઘનફળ', r_lsa: 'બાજુઓનું પૃષ્ઠફળ (LSA)', r_csa: 'વક્ર સપાટીનું પૃષ્ઠફળ (CSA)', r_tsa: 'કુલ પૃષ્ઠફળ (TSA)',
  r_sa: 'પૃષ્ઠફળ', r_slant: 'ત્રાંસી ઊંચાઈ (l)', r_capacity: 'ક્ષમતા',
  err_positive: 'દરેક ખાનામાં 0 કરતાં મોટી સંખ્યા લખો.', err_big: 'કૃપા કરીને {max} સુધીની સંખ્યાઓ જ વાપરો.',
  err_triangle: 'આ બાજુઓથી ત્રિકોણ ન બને. કોઈ પણ બે બાજુઓનો સરવાળો ત્રીજી બાજુ કરતાં મોટો હોવો જોઈએ.',
  err_para: 'ઊંચાઈ ત્રાંસી બાજુ a કરતાં મોટી ન હોઈ શકે.', err_ring: 'બહારની ત્રિજ્યા R અંદરની ત્રિજ્યા r કરતાં મોટી હોવી જોઈએ.',
  note_heron: 'હેરોનના સૂત્રમાં ફક્ત ત્રણ બાજુ જોઈએ, ઊંચાઈની જરૂર નથી.',
  note_trap: 'અહીં પરિમિતિ સમદ્વિબાજુ સમલંબ ચતુષ્કોણની છે (બંને ત્રાંસી બાજુ સરખી).',
  note_cyl: 'TSA બંધ નળાકારનું છે. ખુલ્લી પાઇપમાં ફક્ત વક્ર સપાટી હોય છે.',
  note_hemi: 'TSA નક્કર અર્ધગોલકનું છે (વક્ર ભાગ + સપાટ વર્તુળ). વાટકીની અંદરનો ભાગ ફક્ત CSA છે.',
  note_frustum: 'ધોરણ 10: શંકુનો ઉપરનો ભાગ કાપી નાખતાં જે બાકી રહે તે આડછેદ. r₁ અને r₂ બંને વર્તુળાકાર છેડાની ત્રિજ્યા છે.',
  note_pi: 'ટિપ: ત્રિજ્યા 7 નો ગુણક હોય ત્યારે 22/7 લેવાથી જવાબ સરસ આવે છે.',
  u_ha: 'હેક્ટર', u_ml: 'મિલિલિટર', u_litre: 'લિટર',
  pr_title: 'મહાવરો', pr_which: 'પ્રશ્નો શેના પર', pr_both: 'બંને', pr_given: 'આપેલું', pr_find: 'શોધો', pr_in_unit: '(જવાબ {u} માં)',
  pr_answer: 'તમારો જવાબ', pr_check: 'તપાસો', pr_show: 'ઉકેલ બતાવો', pr_new: 'નવો પ્રશ્ન',
  pr_round: 'π = {pi} લો. જરૂર હોય તો જવાબને દશાંશ પછી 2 અંક સુધી રાઉન્ડ કરો.',
  pr_right: 'સાચું! જવાબ {ans} છે.', pr_wrong: 'થોડું ચૂકી ગયા. સાચો જવાબ {ans} છે. નીચેનો ઉકેલ વાંચો.',
  pr_enter: 'પહેલાં તમારો જવાબ સંખ્યામાં લખો.', pr_score: 'ગુણ: {n} માંથી {c}', pr_streak: 'સતત સાચા: {n} 🔥',
  ws_title: 'વર્કશીટ: ક્ષેત્રફળ અને ઘનફળ', ws_note: 'જવાબ-ચાવી સાથે 10 નવા પ્રશ્નો બનાવો અને પ્રિન્ટ કરો. જવાબોમાં π = {pi} લીધું છે.',
  ws_make: 'વર્કશીટ બનાવો', ws_print: 'વર્કશીટ પ્રિન્ટ કરો', ws_head: 'નામ: ____________   ધોરણ: ______   તારીખ: __________',
  ws_line: 'જવાબ: ______________', ws_answers: 'જવાબ-ચાવી',
  cv_title: 'એકમ બદલો', cv_length: 'લંબાઈ', cv_area: 'ક્ષેત્રફળ', cv_volume: 'ઘનફળ અને ક્ષમતા', cv_value: 'કિંમત', cv_from: 'કયા એકમમાંથી',
  cv_unit_col: 'એકમ', cv_value_col: 'કિંમત',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km.',
  cv_rule_area: 'ક્ષેત્રફળ માટે લંબાઈના નિયમનો વર્ગ કરો: 1 m = 100 cm, એટલે 1 m² = 100 × 100 = 10,000 cm². વળી 1 હેક્ટર = 10,000 m² અને 1 km² = 100 હેક્ટર.',
  cv_rule_vol: 'ઘનફળ માટે લંબાઈના નિયમનો ઘન કરો: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³. વળી 1 cm³ = 1 mL, 1000 cm³ = 1 લિટર અને 1 m³ = 1000 લિટર.',
  help_title: 'કેવી રીતે વાપરવું · વર્ગખંડ માટે વિચારો',
  tip1: '2D કે 3D પસંદ કરો, કોઈ આકાર પર ટૅપ કરો અને તેનાં માપ લખો. લખતાંની સાથે જ જવાબ બદલાય છે.',
  tip2: 'π ને 22/7 અને 3.14 વચ્ચે બદલીને સરખાવો. ત્રિજ્યા 7 નો ગુણક હોય ત્યારે પાઠ્યપુસ્તક 22/7 લે છે, કારણ કે જવાબ ચોખ્ખો આવે છે.',
  tip3: 'ઉકેલને પાઠ્યપુસ્તકની જેમ વાંચો: સૂત્ર લખો, સંખ્યાઓ મૂકો, સાદું રૂપ આપો અને જવાબ એકમ સાથે લખો.',
  tip4: 'એકમનાં બટન અને કન્વર્ટરથી બતાવો કે 1 m² એટલે 10,000 cm², 100 cm² નહીં.',
  tip5: 'વર્ગખંડ પ્રવૃત્તિ: દરેક જૂથને એક સાચી વસ્તુ આપો (ડોલ, ડબ્બો, મીઠાઈનું બૉક્સ). તેઓ માપ લે, ઘનફળનો અંદાજ કાઢે અને પછી અહીં ચકાસે.',
  tip6: 'મહાવરામાં દર વખતે નવા પ્રશ્નો આવે છે. ગૃહકાર્ય કે વર્ગ કસોટી માટે જવાબ-ચાવી સાથે વર્કશીટ બનાવો.'
};
window.APP_STRINGS.pa = {
  app_title: 'ਖੇਤਰਫਲ ਤੇ ਆਇਤਨ ਲੈਬ',
  intro: 'ਕੋਈ ਆਕਾਰ ਚੁਣੋ, ਉਸ ਦੇ ਮਾਪ ਲਿਖੋ ਅਤੇ ਉਸ ਦਾ ਖੇਤਰਫਲ, ਪਰਿਮਾਪ, ਆਇਤਨ ਅਤੇ ਸਤ੍ਹਾ ਖੇਤਰਫਲ ਵੇਖੋ — ਮਾਪ ਅਨੁਸਾਰ ਚਿੱਤਰ ਅਤੇ ਕਦਮ-ਦਰ-ਕਦਮ ਹੱਲ ਨਾਲ।',
  tab_calc: 'ਕੈਲਕੁਲੇਟਰ', tab_practice: 'ਅਭਿਆਸ', tab_units: 'ਇਕਾਈ ਬਦਲੋ',
  choose_shape: 'ਆਕਾਰ ਚੁਣੋ', grp_2d: '2D ਆਕਾਰ', grp_3d: '3D ਠੋਸ',
  grp_2d_hint: 'ਸਮਤਲ ਆਕਾਰ: ਖੇਤਰਫਲ ਅਤੇ ਪਰਿਮਾਪ (ਜਮਾਤ 6–9)', grp_3d_hint: 'ਠੋਸ: ਆਇਤਨ ਅਤੇ ਸਤ੍ਹਾ ਖੇਤਰਫਲ (ਜਮਾਤ 8–10)',
  measurements: 'ਮਾਪ', unit: 'ਇਕਾਈ', pi_value: 'π ਦਾ ਮੁੱਲ', sample: 'ਨਮੂਨਾ ਮੁੱਲ',
  results: 'ਉੱਤਰ', working: 'ਕਦਮ-ਦਰ-ਕਦਮ ਹੱਲ', other_units: 'ਇਹੀ ਉੱਤਰ ਹੋਰ ਇਕਾਈਆਂ ਵਿੱਚ',
  real_life: 'ਅਸਲ ਜ਼ਿੰਦਗੀ ਵਿੱਚ: {x}', fig_aria: 'ਨਾਂ ਵਾਲਾ ਚਿੱਤਰ', fig_note: 'ਚਿੱਤਰ ਮਾਪ ਅਨੁਸਾਰ ਹੈ: ਕੋਈ ਸੰਖਿਆ ਬਦਲੋ ਤਾਂ ਆਕਾਰ ਵੀ ਬਦਲ ਜਾਂਦਾ ਹੈ।',
  approx_note: '≈ ਦਾ ਮਤਲਬ ਹੈ ਕਿ ਉੱਤਰ ਨੂੰ ਦਸ਼ਮਲਵ ਤੋਂ ਬਾਅਦ 2 ਅੰਕਾਂ ਤੱਕ ਪੂਰਨ ਕੀਤਾ ਗਿਆ ਹੈ।',
  sh_square: 'ਵਰਗ', sh_rectangle: 'ਆਇਤ', sh_tri_bh: 'ਤ੍ਰਿਭੁਜ (ਅਧਾਰ ਅਤੇ ਉਚਾਈ)', sh_tri_heron: 'ਤ੍ਰਿਭੁਜ (3 ਭੁਜਾਵਾਂ, ਹੀਰੋਨ)',
  sh_parallelogram: 'ਸਮਾਂਤਰ ਚਤੁਰਭੁਜ', sh_rhombus: 'ਸਮਚਤੁਰਭੁਜ', sh_trapezium: 'ਸਮਲੰਬ ਚਤੁਰਭੁਜ', sh_circle: 'ਚੱਕਰ', sh_semicircle: 'ਅਰਧ-ਚੱਕਰ',
  sh_ring: 'ਛੱਲਾ (ਗੋਲ ਰਸਤਾ)', sh_cube: 'ਘਣ', sh_cuboid: 'ਘਣਾਵ', sh_cylinder: 'ਵੇਲਣ', sh_cone: 'ਸ਼ੰਕੂ', sh_sphere: 'ਗੋਲਾ',
  sh_hemisphere: 'ਅਰਧ-ਗੋਲਾ', sh_frustum: 'ਸ਼ੰਕੂ ਦਾ ਛਿੰਨਕ',
  ex_square: 'ਫ਼ਰਸ਼ ਦੀ ਟਾਈਲ, ਸ਼ਤਰੰਜ ਦਾ ਬੋਰਡ, ਕੈਰਮ ਬੋਰਡ', ex_rectangle: 'ਜਮਾਤ ਦਾ ਫ਼ਰਸ਼, ਕ੍ਰਿਕਟ ਪਿੱਚ, ਮੋਬਾਈਲ ਦੀ ਸਕ੍ਰੀਨ',
  ex_tri_bh: 'ਸੜਕ ਦਾ ਨਿਸ਼ਾਨ-ਬੋਰਡ, ਛੱਤ ਦਾ ਪਾਸਾ, ਸੈੱਟ-ਸਕੁਏਅਰ', ex_tri_heron: 'ਇੱਕ ਤਿਕੋਣਾ ਖੇਤ ਜਿਸ ਦੀਆਂ ਤਿੰਨੇ ਭੁਜਾਵਾਂ ਮਿਣੀਆਂ ਗਈਆਂ ਹੋਣ',
  ex_parallelogram: 'ਤਿਰਛੀ ਪਾਰਕਿੰਗ ਦੀ ਥਾਂ, ਟਾਈਲਾਂ ਦਾ ਡਿਜ਼ਾਈਨ', ex_rhombus: 'ਪਤੰਗ, ਤਾਸ਼ ਦੇ ਪੱਤਿਆਂ ਉੱਤੇ ਇੱਟ ਦਾ ਨਿਸ਼ਾਨ',
  ex_trapezium: 'ਹੈਂਡਬੈਗ ਦਾ ਪਾਸਾ, ਸੜਕ ਦੇ ਨਾਲ ਲੱਗਦਾ ਖੇਤ', ex_circle: 'ਰੋਟੀ, ਸਿੱਕਾ, ਗੋਲ ਪਾਰਕ',
  ex_semicircle: 'ਕੋਣ-ਮਾਪਕ (ਪ੍ਰੋਟ੍ਰੈਕਟਰ), ਅੱਧੇ ਚੰਨ ਵਰਗੀ ਖਿੜਕੀ', ex_ring: 'ਗੋਲ ਬਗ਼ੀਚੇ ਦੇ ਦੁਆਲੇ ਰਸਤਾ, ਚੂੜੀ',
  ex_cube: 'ਲੂਡੋ ਦਾ ਪਾਸਾ, ਰੂਬਿਕ ਕਿਊਬ, ਖੰਡ ਦਾ ਕਿਊਬ', ex_cuboid: 'ਇੱਟ, ਮਾਚਿਸ ਦੀ ਡੱਬੀ, ਅਲਮਾਰੀ, ਪਾਣੀ ਦੀ ਟੈਂਕੀ',
  ex_cylinder: 'ਗੈਸ ਸਿਲੰਡਰ, ਪਾਈਪ, ਡੱਬਾ, ਪਾਣੀ ਦੀ ਟੈਂਕੀ', ex_cone: 'ਆਈਸਕ੍ਰੀਮ ਕੋਨ, ਜਨਮਦਿਨ ਦੀ ਟੋਪੀ, ਤੰਬੂ',
  ex_sphere: 'ਫੁੱਟਬਾਲ, ਲੱਡੂ, ਬੰਟਾ', ex_hemisphere: 'ਕੌਲੀ, ਇਮਾਰਤ ਦਾ ਗੁੰਬਦ',
  ex_frustum: 'ਬਾਲਟੀ, ਸਟੀਲ ਦਾ ਗਲਾਸ, ਲੈਂਪਸ਼ੇਡ',
  d_side: 'ਭੁਜਾ (a)', d_edge: 'ਕਿਨਾਰਾ (a)', d_length: 'ਲੰਬਾਈ (l)', d_breadth: 'ਚੌੜਾਈ (b)', d_base: 'ਅਧਾਰ (b)', d_height: 'ਉਚਾਈ (h)',
  d_side_a: 'ਭੁਜਾ a', d_side_b: 'ਭੁਜਾ b', d_side_c: 'ਭੁਜਾ c', d_slant_side: 'ਤਿਰਛੀ ਭੁਜਾ (a)',
  d_diag1: 'ਵਿਕਰਨ d₁', d_diag2: 'ਵਿਕਰਨ d₂', d_par_a: 'ਸਮਾਂਤਰ ਭੁਜਾ a', d_par_b: 'ਸਮਾਂਤਰ ਭੁਜਾ b',
  d_radius: 'ਅਰਧ-ਵਿਆਸ (r)', d_outer: 'ਬਾਹਰੀ ਅਰਧ-ਵਿਆਸ (R)', d_inner: 'ਅੰਦਰੂਨੀ ਅਰਧ-ਵਿਆਸ (r)', d_r1: 'ਉੱਪਰਲਾ ਅਰਧ-ਵਿਆਸ (r₁)', d_r2: 'ਹੇਠਲਾ ਅਰਧ-ਵਿਆਸ (r₂)',
  r_area: 'ਖੇਤਰਫਲ', r_perimeter: 'ਪਰਿਮਾਪ', r_circumference: 'ਘੇਰਾ', r_diameter: 'ਵਿਆਸ', r_diagonal: 'ਵਿਕਰਨ',
  r_s: 'ਅਰਧ-ਪਰਿਮਾਪ (s)', r_side: 'ਭੁਜਾ (a)', r_leg: 'ਤਿਰਛੀ ਭੁਜਾ (c)', r_width: 'ਰਸਤੇ ਦੀ ਚੌੜਾਈ',
  r_volume: 'ਆਇਤਨ', r_lsa: 'ਪਾਸਿਆਂ ਦਾ ਸਤ੍ਹਾ ਖੇਤਰਫਲ (LSA)', r_csa: 'ਵਕਰ ਸਤ੍ਹਾ ਖੇਤਰਫਲ (CSA)', r_tsa: 'ਕੁੱਲ ਸਤ੍ਹਾ ਖੇਤਰਫਲ (TSA)',
  r_sa: 'ਸਤ੍ਹਾ ਖੇਤਰਫਲ', r_slant: 'ਤਿਰਛੀ ਉਚਾਈ (l)', r_capacity: 'ਸਮਰੱਥਾ',
  err_positive: 'ਹਰ ਖ਼ਾਨੇ ਵਿੱਚ 0 ਤੋਂ ਵੱਡੀ ਸੰਖਿਆ ਲਿਖੋ।', err_big: 'ਕਿਰਪਾ ਕਰਕੇ {max} ਤੱਕ ਦੀਆਂ ਸੰਖਿਆਵਾਂ ਹੀ ਵਰਤੋ।',
  err_triangle: 'ਇਨ੍ਹਾਂ ਭੁਜਾਵਾਂ ਨਾਲ ਤ੍ਰਿਭੁਜ ਨਹੀਂ ਬਣ ਸਕਦੀ। ਕਿਸੇ ਵੀ ਦੋ ਭੁਜਾਵਾਂ ਦਾ ਜੋੜ ਤੀਜੀ ਭੁਜਾ ਤੋਂ ਵੱਡਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
  err_para: 'ਉਚਾਈ ਤਿਰਛੀ ਭੁਜਾ a ਤੋਂ ਵੱਡੀ ਨਹੀਂ ਹੋ ਸਕਦੀ।', err_ring: 'ਬਾਹਰੀ ਅਰਧ-ਵਿਆਸ R, ਅੰਦਰੂਨੀ ਅਰਧ-ਵਿਆਸ r ਤੋਂ ਵੱਡਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
  note_heron: 'ਹੀਰੋਨ ਦੇ ਸੂਤਰ ਲਈ ਸਿਰਫ਼ ਤਿੰਨ ਭੁਜਾਵਾਂ ਚਾਹੀਦੀਆਂ ਹਨ, ਉਚਾਈ ਦੀ ਲੋੜ ਨਹੀਂ।',
  note_trap: 'ਇੱਥੇ ਪਰਿਮਾਪ ਸਮਦੋਭੁਜੀ ਸਮਲੰਬ ਚਤੁਰਭੁਜ ਦਾ ਹੈ (ਦੋਵੇਂ ਤਿਰਛੀਆਂ ਭੁਜਾਵਾਂ ਬਰਾਬਰ)।',
  note_cyl: 'TSA ਬੰਦ ਵੇਲਣ ਦਾ ਹੈ। ਖੁੱਲ੍ਹੀ ਪਾਈਪ ਵਿੱਚ ਸਿਰਫ਼ ਵਕਰ ਸਤ੍ਹਾ ਹੁੰਦੀ ਹੈ।',
  note_hemi: 'TSA ਠੋਸ ਅਰਧ-ਗੋਲੇ ਦਾ ਹੈ (ਵਕਰ ਹਿੱਸਾ + ਪੱਧਰਾ ਚੱਕਰ)। ਕੌਲੀ ਦਾ ਅੰਦਰਲਾ ਹਿੱਸਾ ਸਿਰਫ਼ CSA ਹੈ।',
  note_frustum: 'ਜਮਾਤ 10: ਛਿੰਨਕ ਉਹ ਸ਼ੰਕੂ ਹੈ ਜਿਸ ਦਾ ਉੱਪਰਲਾ ਹਿੱਸਾ ਕੱਟ ਦਿੱਤਾ ਗਿਆ ਹੋਵੇ। r₁ ਅਤੇ r₂ ਦੋਵੇਂ ਗੋਲ ਸਿਰਿਆਂ ਦੇ ਅਰਧ-ਵਿਆਸ ਹਨ।',
  note_pi: 'ਸੁਝਾਅ: ਜਦੋਂ ਅਰਧ-ਵਿਆਸ 7 ਦਾ ਗੁਣਜ ਹੋਵੇ, ਤਾਂ 22/7 ਲੈਣ ਨਾਲ ਉੱਤਰ ਸਾਫ਼ ਆਉਂਦਾ ਹੈ।',
  u_ha: 'ਹੈਕਟੇਅਰ', u_ml: 'ਮਿਲੀਲੀਟਰ', u_litre: 'ਲੀਟਰ',
  pr_title: 'ਅਭਿਆਸ', pr_which: 'ਪ੍ਰਸ਼ਨ ਕਿਸ ਉੱਤੇ', pr_both: 'ਦੋਵੇਂ', pr_given: 'ਦਿੱਤਾ ਹੈ', pr_find: 'ਪਤਾ ਕਰੋ', pr_in_unit: '(ਉੱਤਰ {u} ਵਿੱਚ)',
  pr_answer: 'ਤੁਹਾਡਾ ਉੱਤਰ', pr_check: 'ਜਾਂਚੋ', pr_show: 'ਹੱਲ ਵਿਖਾਓ', pr_new: 'ਨਵਾਂ ਪ੍ਰਸ਼ਨ',
  pr_round: 'π = {pi} ਲਓ। ਲੋੜ ਹੋਵੇ ਤਾਂ ਉੱਤਰ ਨੂੰ ਦਸ਼ਮਲਵ ਤੋਂ ਬਾਅਦ 2 ਅੰਕਾਂ ਤੱਕ ਪੂਰਨ ਕਰੋ।',
  pr_right: 'ਸਹੀ! ਉੱਤਰ {ans} ਹੈ।', pr_wrong: 'ਥੋੜ੍ਹਾ ਖੁੰਝ ਗਏ। ਸਹੀ ਉੱਤਰ {ans} ਹੈ। ਹੇਠਾਂ ਹੱਲ ਪੜ੍ਹੋ।',
  pr_enter: 'ਪਹਿਲਾਂ ਆਪਣਾ ਉੱਤਰ ਸੰਖਿਆ ਵਿੱਚ ਲਿਖੋ।', pr_score: 'ਅੰਕ: {n} ਵਿੱਚੋਂ {c}', pr_streak: 'ਲਗਾਤਾਰ ਸਹੀ: {n} 🔥',
  ws_title: 'ਵਰਕਸ਼ੀਟ: ਖੇਤਰਫਲ ਅਤੇ ਆਇਤਨ', ws_note: 'ਉੱਤਰ-ਕੁੰਜੀ ਸਮੇਤ 10 ਨਵੇਂ ਪ੍ਰਸ਼ਨ ਬਣਾਓ ਅਤੇ ਪ੍ਰਿੰਟ ਕਰੋ। ਉੱਤਰਾਂ ਵਿੱਚ π = {pi} ਲਿਆ ਗਿਆ ਹੈ।',
  ws_make: 'ਵਰਕਸ਼ੀਟ ਬਣਾਓ', ws_print: 'ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ', ws_head: 'ਨਾਂ: ____________   ਜਮਾਤ: ______   ਮਿਤੀ: __________',
  ws_line: 'ਉੱਤਰ: ______________', ws_answers: 'ਉੱਤਰ-ਕੁੰਜੀ',
  cv_title: 'ਇਕਾਈ ਬਦਲੋ', cv_length: 'ਲੰਬਾਈ', cv_area: 'ਖੇਤਰਫਲ', cv_volume: 'ਆਇਤਨ ਅਤੇ ਸਮਰੱਥਾ', cv_value: 'ਮੁੱਲ', cv_from: 'ਕਿਸ ਇਕਾਈ ਤੋਂ',
  cv_unit_col: 'ਇਕਾਈ', cv_value_col: 'ਮੁੱਲ',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km।',
  cv_rule_area: 'ਖੇਤਰਫਲ ਲਈ ਲੰਬਾਈ ਵਾਲੇ ਨਿਯਮ ਦਾ ਵਰਗ ਕਰੋ: 1 m = 100 cm, ਇਸ ਲਈ 1 m² = 100 × 100 = 10,000 cm²। ਨਾਲ ਹੀ 1 ਹੈਕਟੇਅਰ = 10,000 m² ਅਤੇ 1 km² = 100 ਹੈਕਟੇਅਰ।',
  cv_rule_vol: 'ਆਇਤਨ ਲਈ ਲੰਬਾਈ ਵਾਲੇ ਨਿਯਮ ਦਾ ਘਣ ਕਰੋ: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³। ਨਾਲ ਹੀ 1 cm³ = 1 mL, 1000 cm³ = 1 ਲੀਟਰ ਅਤੇ 1 m³ = 1000 ਲੀਟਰ।',
  help_title: 'ਕਿਵੇਂ ਵਰਤੀਏ · ਜਮਾਤ ਲਈ ਸੁਝਾਅ',
  tip1: '2D ਜਾਂ 3D ਚੁਣੋ, ਕਿਸੇ ਆਕਾਰ ਉੱਤੇ ਟੈਪ ਕਰੋ ਅਤੇ ਉਸ ਦੇ ਮਾਪ ਲਿਖੋ। ਲਿਖਦੇ ਹੀ ਉੱਤਰ ਬਦਲਦੇ ਜਾਂਦੇ ਹਨ।',
  tip2: 'π ਨੂੰ 22/7 ਅਤੇ 3.14 ਵਿਚਕਾਰ ਬਦਲ ਕੇ ਤੁਲਨਾ ਕਰੋ। ਜਦੋਂ ਅਰਧ-ਵਿਆਸ 7 ਦਾ ਗੁਣਜ ਹੋਵੇ, ਕਿਤਾਬਾਂ 22/7 ਲੈਂਦੀਆਂ ਹਨ ਕਿਉਂਕਿ ਉੱਤਰ ਸਾਫ਼ ਆਉਂਦਾ ਹੈ।',
  tip3: 'ਹੱਲ ਨੂੰ ਕਿਤਾਬ ਵਾਂਗ ਪੜ੍ਹੋ: ਸੂਤਰ ਲਿਖੋ, ਸੰਖਿਆਵਾਂ ਰੱਖੋ, ਸਰਲ ਕਰੋ ਅਤੇ ਉੱਤਰ ਇਕਾਈ ਸਮੇਤ ਲਿਖੋ।',
  tip4: 'ਇਕਾਈ ਵਾਲੇ ਬਟਨਾਂ ਅਤੇ ਕਨਵਰਟਰ ਨਾਲ ਵਿਖਾਓ ਕਿ 1 m² ਵਿੱਚ 10,000 cm² ਹੁੰਦੇ ਹਨ, 100 cm² ਨਹੀਂ।',
  tip5: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: ਹਰ ਟੋਲੀ ਨੂੰ ਇੱਕ ਅਸਲੀ ਚੀਜ਼ ਦਿਓ (ਬਾਲਟੀ, ਡੱਬਾ, ਮਿਠਾਈ ਦਾ ਡੱਬਾ)। ਉਹ ਮਿਣਨ, ਆਇਤਨ ਦਾ ਅੰਦਾਜ਼ਾ ਲਾਉਣ ਅਤੇ ਫਿਰ ਇੱਥੇ ਜਾਂਚਣ।',
  tip6: 'ਅਭਿਆਸ ਵਿੱਚ ਹਰ ਵਾਰ ਨਵੇਂ ਪ੍ਰਸ਼ਨ ਆਉਂਦੇ ਹਨ। ਘਰ ਦੇ ਕੰਮ ਜਾਂ ਜਮਾਤ ਟੈਸਟ ਲਈ ਉੱਤਰ-ਕੁੰਜੀ ਵਾਲੀ ਵਰਕਸ਼ੀਟ ਬਣਾਓ।'
};
window.APP_STRINGS.or = {
  app_title: 'କ୍ଷେତ୍ରଫଳ ଓ ଆୟତନ ଲ୍ୟାବ୍',
  intro: 'ଏକ ଆକୃତି ବାଛନ୍ତୁ, ତାର ମାପ ଲେଖନ୍ତୁ ଏବଂ ତାର କ୍ଷେତ୍ରଫଳ, ପରିସୀମା, ଆୟତନ ଓ ପୃଷ୍ଠତଳର କ୍ଷେତ୍ରଫଳ ଦେଖନ୍ତୁ — ମାପ ଅନୁଯାୟୀ ଚିତ୍ର ଓ ସୋପାନ ଅନୁସାରେ ସମାଧାନ ସହିତ।',
  tab_calc: 'କାଲକୁଲେଟର୍', tab_practice: 'ଅଭ୍ୟାସ', tab_units: 'ଏକକ ବଦଳ',
  choose_shape: 'ଆକୃତି ବାଛନ୍ତୁ', grp_2d: '2D ଆକୃତି', grp_3d: '3D ଘନ ବସ୍ତୁ',
  grp_2d_hint: 'ସମତଳ ଆକୃତି: କ୍ଷେତ୍ରଫଳ ଓ ପରିସୀମା (ଷଷ୍ଠ–ନବମ ଶ୍ରେଣୀ)', grp_3d_hint: 'ଘନ ବସ୍ତୁ: ଆୟତନ ଓ ପୃଷ୍ଠତଳର କ୍ଷେତ୍ରଫଳ (ଅଷ୍ଟମ–ଦଶମ ଶ୍ରେଣୀ)',
  measurements: 'ମାପ', unit: 'ଏକକ', pi_value: 'π ର ମାନ', sample: 'ନମୁନା ମାନ',
  results: 'ଉତ୍ତର', working: 'ସୋପାନ ଅନୁସାରେ ସମାଧାନ', other_units: 'ସେହି ଉତ୍ତର ଅନ୍ୟ ଏକକରେ',
  real_life: 'ବାସ୍ତବ ଜୀବନରେ: {x}', fig_aria: 'ନାମାଙ୍କିତ ଚିତ୍ର', fig_note: 'ଚିତ୍ରଟି ମାପ ଅନୁଯାୟୀ: କୌଣସି ସଂଖ୍ୟା ବଦଳାନ୍ତୁ, ଆକୃତି ମଧ୍ୟ ବଦଳିଯିବ।',
  approx_note: '≈ ର ଅର୍ଥ ଉତ୍ତରକୁ ଦଶମିକ ପରେ 2 ଅଙ୍କ ପର୍ଯ୍ୟନ୍ତ ଆସନ୍ନ କରାଯାଇଛି।',
  sh_square: 'ବର୍ଗକ୍ଷେତ୍ର', sh_rectangle: 'ଆୟତକ୍ଷେତ୍ର', sh_tri_bh: 'ତ୍ରିଭୁଜ (ଭୂମି ଓ ଉଚ୍ଚତା)', sh_tri_heron: 'ତ୍ରିଭୁଜ (3 ବାହୁ, ହେରନ୍)',
  sh_parallelogram: 'ସାମାନ୍ତରିକ ଚିତ୍ର', sh_rhombus: 'ରମ୍ବସ୍', sh_trapezium: 'ଟ୍ରାପିଜିୟମ୍', sh_circle: 'ବୃତ୍ତ', sh_semicircle: 'ଅର୍ଦ୍ଧବୃତ୍ତ',
  sh_ring: 'ବଳୟ (ବୃତ୍ତାକାର ପଥ)', sh_cube: 'ଘନ', sh_cuboid: 'ଆୟତଘନ', sh_cylinder: 'ସିଲିଣ୍ଡର୍', sh_cone: 'ଶଙ୍କୁ', sh_sphere: 'ଗୋଲକ',
  sh_hemisphere: 'ଅର୍ଦ୍ଧଗୋଲକ', sh_frustum: 'ଶଙ୍କୁର ଛିନ୍ନକ',
  ex_square: 'ଚଟାଣର ଟାଇଲ୍, ଚେସ୍ ବୋର୍ଡ, କ୍ୟାରମ୍ ବୋର୍ଡ', ex_rectangle: 'ଶ୍ରେଣୀଗୃହର ଚଟାଣ, କ୍ରିକେଟ୍ ପିଚ୍, ମୋବାଇଲ୍ ସ୍କ୍ରିନ୍',
  ex_tri_bh: 'ରାସ୍ତାର ସଙ୍କେତ ବୋର୍ଡ, ଛାତର ପାର୍ଶ୍ୱ, ସେଟ୍-ସ୍କୋୟାର୍', ex_tri_heron: 'ତିନି ବାହୁ ମପାଯାଇଥିବା ଏକ ତ୍ରିଭୁଜାକାର ଜମି',
  ex_parallelogram: 'ତେରେଛା ପାର୍କିଂ ସ୍ଥାନ, ଟାଇଲ୍‌ର ନକ୍ସା', ex_rhombus: 'ଗୁଡ଼ି, ତାସ ପତ୍ରର ଇଟା ଚିହ୍ନ',
  ex_trapezium: 'ହ୍ୟାଣ୍ଡବ୍ୟାଗର ପାର୍ଶ୍ୱ, ରାସ୍ତା କଡ଼ର ଜମି', ex_circle: 'ରୁଟି, ମୁଦ୍ରା, ଗୋଲ ପାର୍କ',
  ex_semicircle: 'ପ୍ରୋଟ୍ରାକ୍ଟର୍, ଅର୍ଦ୍ଧଚନ୍ଦ୍ର ଝରକା', ex_ring: 'ଗୋଲ ବଗିଚା ଚାରିପାଖ ରାସ୍ତା, ଚୁଡ଼ି',
  ex_cube: 'ପଶାଗୁଟି, ରୁବିକ୍ କ୍ୟୁବ୍, ଚିନି କ୍ୟୁବ୍', ex_cuboid: 'ଇଟା, ଦିଆସିଲି ବାକ୍ସ, ଆଲମାରି, ପାଣି ଟାଙ୍କି',
  ex_cylinder: 'ଗ୍ୟାସ୍ ସିଲିଣ୍ଡର୍, ପାଇପ୍, ଟିଣ ଡବା, ପାଣି ଟାଙ୍କି', ex_cone: 'ଆଇସକ୍ରିମ୍ କୋନ୍, ଜନ୍ମଦିନ ଟୋପି, ତମ୍ବୁ',
  ex_sphere: 'ଫୁଟବଲ୍, ଲଡ୍ଡୁ, ଗୋଲି', ex_hemisphere: 'ବାଟି, ଘରର ଗମ୍ବୁଜ',
  ex_frustum: 'ବାଲଟି, ଷ୍ଟିଲ୍ ଗିଲାସ, ଲ୍ୟାମ୍ପସେଡ୍',
  d_side: 'ବାହୁ (a)', d_edge: 'ଧାର (a)', d_length: 'ଦୈର୍ଘ୍ୟ (l)', d_breadth: 'ପ୍ରସ୍ଥ (b)', d_base: 'ଭୂମି (b)', d_height: 'ଉଚ୍ଚତା (h)',
  d_side_a: 'ବାହୁ a', d_side_b: 'ବାହୁ b', d_side_c: 'ବାହୁ c', d_slant_side: 'ତେରେଛା ବାହୁ (a)',
  d_diag1: 'କର୍ଣ୍ଣ d₁', d_diag2: 'କର୍ଣ୍ଣ d₂', d_par_a: 'ସମାନ୍ତର ବାହୁ a', d_par_b: 'ସମାନ୍ତର ବାହୁ b',
  d_radius: 'ବ୍ୟାସାର୍ଦ୍ଧ (r)', d_outer: 'ବାହାର ବ୍ୟାସାର୍ଦ୍ଧ (R)', d_inner: 'ଭିତର ବ୍ୟାସାର୍ଦ୍ଧ (r)', d_r1: 'ଉପର ବ୍ୟାସାର୍ଦ୍ଧ (r₁)', d_r2: 'ତଳ ବ୍ୟାସାର୍ଦ୍ଧ (r₂)',
  r_area: 'କ୍ଷେତ୍ରଫଳ', r_perimeter: 'ପରିସୀମା', r_circumference: 'ପରିଧି', r_diameter: 'ବ୍ୟାସ', r_diagonal: 'କର୍ଣ୍ଣ',
  r_s: 'ଅର୍ଦ୍ଧପରିସୀମା (s)', r_side: 'ବାହୁ (a)', r_leg: 'ତେରେଛା ବାହୁ (c)', r_width: 'ରାସ୍ତାର ଓସାର',
  r_volume: 'ଆୟତନ', r_lsa: 'ପାର୍ଶ୍ୱପୃଷ୍ଠର କ୍ଷେତ୍ରଫଳ (LSA)', r_csa: 'ବକ୍ରପୃଷ୍ଠର କ୍ଷେତ୍ରଫଳ (CSA)', r_tsa: 'ସମଗ୍ର ପୃଷ୍ଠତଳର କ୍ଷେତ୍ରଫଳ (TSA)',
  r_sa: 'ପୃଷ୍ଠତଳର କ୍ଷେତ୍ରଫଳ', r_slant: 'ତିର୍ଯ୍ୟକ ଉଚ୍ଚତା (l)', r_capacity: 'ଧାରଣ କ୍ଷମତା',
  err_positive: 'ପ୍ରତ୍ୟେକ ଘରେ 0 ଠାରୁ ବଡ଼ ସଂଖ୍ୟା ଲେଖନ୍ତୁ।', err_big: 'ଦୟାକରି {max} ପର୍ଯ୍ୟନ୍ତ ସଂଖ୍ୟା ବ୍ୟବହାର କରନ୍ତୁ।',
  err_triangle: 'ଏହି ବାହୁଗୁଡ଼ିକରେ ତ୍ରିଭୁଜ ହୋଇପାରିବ ନାହିଁ। ଯେକୌଣସି ଦୁଇ ବାହୁର ଯୋଗଫଳ ତୃତୀୟ ବାହୁଠାରୁ ବଡ଼ ହେବା ଦରକାର।',
  err_para: 'ଉଚ୍ଚତା ତେରେଛା ବାହୁ a ଠାରୁ ବଡ଼ ହୋଇପାରିବ ନାହିଁ।', err_ring: 'ବାହାର ବ୍ୟାସାର୍ଦ୍ଧ R, ଭିତର ବ୍ୟାସାର୍ଦ୍ଧ r ଠାରୁ ବଡ଼ ହେବା ଦରକାର।',
  note_heron: 'ହେରନ୍‌ଙ୍କ ସୂତ୍ରରେ କେବଳ ତିନି ବାହୁ ଦରକାର, ଉଚ୍ଚତା ଦରକାର ନାହିଁ।',
  note_trap: 'ଏଠାରେ ପରିସୀମା ସମଦ୍ୱିବାହୁ ଟ୍ରାପିଜିୟମ୍‌ର (ଦୁଇଟି ତେରେଛା ବାହୁ ସମାନ)।',
  note_cyl: 'TSA ବନ୍ଦ ସିଲିଣ୍ଡର୍‌ର। ଖୋଲା ପାଇପ୍‌ରେ କେବଳ ବକ୍ରପୃଷ୍ଠ ଥାଏ।',
  note_hemi: 'TSA ନିରେଟ ଅର୍ଦ୍ଧଗୋଲକର (ବକ୍ର ଅଂଶ + ସମତଳ ବୃତ୍ତ)। ବାଟିର ଭିତର ଅଂଶ କେବଳ CSA।',
  note_frustum: 'ଦଶମ ଶ୍ରେଣୀ: ଶଙ୍କୁର ଉପର ଅଂଶ କାଟିଦେଲେ ଯାହା ରହେ ତାହା ଛିନ୍ନକ। r₁ ଓ r₂ ଦୁଇ ବୃତ୍ତାକାର ମୁଣ୍ଡର ବ୍ୟାସାର୍ଦ୍ଧ।',
  note_pi: 'ପରାମର୍ଶ: ବ୍ୟାସାର୍ଦ୍ଧ 7 ର ଗୁଣିତକ ହେଲେ 22/7 ନେଲେ ଉତ୍ତର ସୁନ୍ଦର ଆସେ।',
  u_ha: 'ହେକ୍ଟର୍', u_ml: 'ମିଲିଲିଟର୍', u_litre: 'ଲିଟର୍',
  pr_title: 'ଅଭ୍ୟାସ', pr_which: 'ପ୍ରଶ୍ନର ବିଷୟ', pr_both: 'ଉଭୟ', pr_given: 'ଦିଆଯାଇଛି', pr_find: 'ନିର୍ଣ୍ଣୟ କର', pr_in_unit: '(ଉତ୍ତର {u} ରେ)',
  pr_answer: 'ତୁମ ଉତ୍ତର', pr_check: 'ଯାଞ୍ଚ କର', pr_show: 'ସମାଧାନ ଦେଖାଅ', pr_new: 'ନୂଆ ପ୍ରଶ୍ନ',
  pr_round: 'π = {pi} ନିଅ। ଦରକାର ହେଲେ ଉତ୍ତରକୁ ଦଶମିକ ପରେ 2 ଅଙ୍କ ପର୍ଯ୍ୟନ୍ତ ଆସନ୍ନ କର।',
  pr_right: 'ଠିକ୍! ଉତ୍ତର {ans}।', pr_wrong: 'ଟିକିଏ ଭୁଲ। ଠିକ୍ ଉତ୍ତର {ans}। ତଳେ ସମାଧାନ ପଢ଼।',
  pr_enter: 'ପ୍ରଥମେ ତୁମ ଉତ୍ତର ସଂଖ୍ୟାରେ ଲେଖ।', pr_score: 'ସ୍କୋର୍: {n} ମଧ୍ୟରୁ {c}', pr_streak: 'କ୍ରମାଗତ ଠିକ୍: {n} 🔥',
  ws_title: 'ୱାର୍କସିଟ୍: କ୍ଷେତ୍ରଫଳ ଓ ଆୟତନ', ws_note: 'ଉତ୍ତରମାଳା ସହିତ 10ଟି ନୂଆ ପ୍ରଶ୍ନ ତିଆରି କରି ପ୍ରିଣ୍ଟ କରନ୍ତୁ। ଉତ୍ତରରେ π = {pi} ନିଆଯାଇଛି।',
  ws_make: 'ୱାର୍କସିଟ୍ ତିଆରି କରନ୍ତୁ', ws_print: 'ୱାର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ', ws_head: 'ନାମ: ____________   ଶ୍ରେଣୀ: ______   ତାରିଖ: __________',
  ws_line: 'ଉତ୍ତର: ______________', ws_answers: 'ଉତ୍ତରମାଳା',
  cv_title: 'ଏକକ ବଦଳାନ୍ତୁ', cv_length: 'ଦୈର୍ଘ୍ୟ', cv_area: 'କ୍ଷେତ୍ରଫଳ', cv_volume: 'ଆୟତନ ଓ ଧାରଣ କ୍ଷମତା', cv_value: 'ମାନ', cv_from: 'କେଉଁ ଏକକରୁ',
  cv_unit_col: 'ଏକକ', cv_value_col: 'ମାନ',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km।',
  cv_rule_area: 'କ୍ଷେତ୍ରଫଳ ପାଇଁ ଦୈର୍ଘ୍ୟ ନିୟମର ବର୍ଗ କରନ୍ତୁ: 1 m = 100 cm, ତେଣୁ 1 m² = 100 × 100 = 10,000 cm²। ଏହା ସହିତ 1 ହେକ୍ଟର୍ = 10,000 m² ଓ 1 km² = 100 ହେକ୍ଟର୍।',
  cv_rule_vol: 'ଆୟତନ ପାଇଁ ଦୈର୍ଘ୍ୟ ନିୟମର ଘନ କରନ୍ତୁ: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³। ଏହା ସହିତ 1 cm³ = 1 mL, 1000 cm³ = 1 ଲିଟର୍ ଓ 1 m³ = 1000 ଲିଟର୍।',
  help_title: 'କିପରି ବ୍ୟବହାର କରିବେ · ଶ୍ରେଣୀ ପାଇଁ ଭାବନା',
  tip1: '2D ବା 3D ବାଛନ୍ତୁ, ଏକ ଆକୃତିରେ ଟାପ୍ କରନ୍ତୁ ଓ ତାର ମାପ ଲେଖନ୍ତୁ। ଲେଖିବା ସାଙ୍ଗେ ସାଙ୍ଗେ ଉତ୍ତର ବଦଳେ।',
  tip2: 'π କୁ 22/7 ଓ 3.14 ମଧ୍ୟରେ ବଦଳାଇ ତୁଳନା କରନ୍ତୁ। ବ୍ୟାସାର୍ଦ୍ଧ 7 ର ଗୁଣିତକ ହେଲେ ବହିରେ 22/7 ନିଆଯାଏ, କାରଣ ଉତ୍ତର ସଫା ଆସେ।',
  tip3: 'ସମାଧାନକୁ ବହି ପରି ପଢ଼ନ୍ତୁ: ସୂତ୍ର ଲେଖନ୍ତୁ, ସଂଖ୍ୟା ବସାନ୍ତୁ, ସରଳ କରନ୍ତୁ ଓ ଏକକ ସହିତ ଉତ୍ତର ଲେଖନ୍ତୁ।',
  tip4: 'ଏକକ ବଟନ୍ ଓ କନଭର୍ଟର୍ ଦ୍ୱାରା ଦେଖାନ୍ତୁ କାହିଁକି 1 m² = 10,000 cm², 100 cm² ନୁହେଁ।',
  tip5: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ: ପ୍ରତି ଦଳକୁ ଗୋଟିଏ ପ୍ରକୃତ ଜିନିଷ ଦିଅନ୍ତୁ (ବାଲଟି, ଡବା, ମିଠା ବାକ୍ସ)। ସେମାନେ ମାପିବେ, ଆୟତନ ଅନୁମାନ କରିବେ, ତା’ପରେ ଏଠାରେ ଯାଞ୍ଚ କରିବେ।',
  tip6: 'ଅଭ୍ୟାସରେ ପ୍ରତିଥର ନୂଆ ପ୍ରଶ୍ନ ଆସେ। ଗୃହକାର୍ଯ୍ୟ ବା ଶ୍ରେଣୀ ପରୀକ୍ଷା ପାଇଁ ଉତ୍ତରମାଳା ସହିତ ୱାର୍କସିଟ୍ ତିଆରି କରନ୍ତୁ।'
};
window.APP_STRINGS.ta = {
  app_title: 'பரப்பு & கன அளவு ஆய்வகம்',
  intro: 'ஒரு வடிவத்தைத் தேர்ந்தெடுத்து, அதன் அளவுகளை எழுதுங்கள்; அதன் பரப்பளவு, சுற்றளவு, கன அளவு, புறப்பரப்பு ஆகியவற்றை அளவுக்கேற்ற படமும் படிப்படியான தீர்வும் சேர்த்துப் பாருங்கள்.',
  tab_calc: 'கணிப்பான்', tab_practice: 'பயிற்சி', tab_units: 'அலகு மாற்றி',
  choose_shape: 'வடிவத்தைத் தேர்ந்தெடுங்கள்', grp_2d: '2D வடிவங்கள்', grp_3d: '3D திண்மங்கள்',
  grp_2d_hint: 'தட்டை வடிவங்கள்: பரப்பளவு, சுற்றளவு (வகுப்பு 6–9)', grp_3d_hint: 'திண்மங்கள்: கன அளவு, புறப்பரப்பு (வகுப்பு 8–10)',
  measurements: 'அளவுகள்', unit: 'அலகு', pi_value: 'π இன் மதிப்பு', sample: 'மாதிரி மதிப்புகள்',
  results: 'விடைகள்', working: 'படிப்படியான தீர்வு', other_units: 'அதே விடை மற்ற அலகுகளில்',
  real_life: 'அன்றாட வாழ்வில்: {x}', fig_aria: 'பெயரிடப்பட்ட படம்', fig_note: 'படம் அளவுக்கேற்ப வரையப்பட்டது: ஓர் எண்ணை மாற்றினால் வடிவமும் மாறும்.',
  approx_note: '≈ என்றால் விடை 2 தசம இடங்களுக்கு முழுமையாக்கப்பட்டது.',
  sh_square: 'சதுரம்', sh_rectangle: 'செவ்வகம்', sh_tri_bh: 'முக்கோணம் (அடிப்பக்கம், உயரம்)', sh_tri_heron: 'முக்கோணம் (3 பக்கங்கள், ஹீரான்)',
  sh_parallelogram: 'இணைகரம்', sh_rhombus: 'சாய்சதுரம்', sh_trapezium: 'சரிவகம்', sh_circle: 'வட்டம்', sh_semicircle: 'அரைவட்டம்',
  sh_ring: 'வளையம் (வட்டப் பாதை)', sh_cube: 'கனசதுரம்', sh_cuboid: 'கனச்செவ்வகம்', sh_cylinder: 'உருளை', sh_cone: 'கூம்பு', sh_sphere: 'கோளம்',
  sh_hemisphere: 'அரைக்கோளம்', sh_frustum: 'கூம்பின் இடைக்கண்டம்',
  ex_square: 'தரை ஓடு, சதுரங்கப் பலகை, கேரம் பலகை', ex_rectangle: 'வகுப்பறைத் தரை, கிரிக்கெட் ஆடுகளம், கைப்பேசித் திரை',
  ex_tri_bh: 'சாலைக் குறிப் பலகை, கூரையின் பக்கம், மூலைமட்டம்', ex_tri_heron: 'மூன்று பக்கங்களும் அளக்கப்பட்ட ஒரு முக்கோண வயல்',
  ex_parallelogram: 'சாய்வான வாகன நிறுத்த இடம், ஓடுகளின் வடிவமைப்பு', ex_rhombus: 'பட்டம், சீட்டுக்கட்டில் உள்ள டைமண்ட் குறி',
  ex_trapezium: 'கைப்பையின் பக்கம், சாலையோர வயல்', ex_circle: 'சப்பாத்தி, நாணயம், வட்டப் பூங்கா',
  ex_semicircle: 'கோணமானி, அரைநிலா வடிவ ஜன்னல்', ex_ring: 'வட்டத் தோட்டத்தைச் சுற்றிய பாதை, வளையல்',
  ex_cube: 'தாயக்கட்டை, ரூபிக் கியூப், சர்க்கரைக் கட்டி', ex_cuboid: 'செங்கல், தீப்பெட்டி, அலமாரி, தண்ணீர்த் தொட்டி',
  ex_cylinder: 'எரிவாயு சிலிண்டர், குழாய், டப்பா, தண்ணீர்த் தொட்டி', ex_cone: 'ஐஸ்கிரீம் கோன், பிறந்தநாள் தொப்பி, கூடாரம்',
  ex_sphere: 'கால்பந்து, லட்டு, கோலிக்குண்டு', ex_hemisphere: 'கிண்ணம், கட்டடத்தின் குவிமாடம்',
  ex_frustum: 'வாளி, எவர்சில்வர் டம்ளர், விளக்கு மூடி',
  d_side: 'பக்கம் (a)', d_edge: 'விளிம்பு (a)', d_length: 'நீளம் (l)', d_breadth: 'அகலம் (b)', d_base: 'அடிப்பக்கம் (b)', d_height: 'உயரம் (h)',
  d_side_a: 'பக்கம் a', d_side_b: 'பக்கம் b', d_side_c: 'பக்கம் c', d_slant_side: 'சாய்ந்த பக்கம் (a)',
  d_diag1: 'மூலைவிட்டம் d₁', d_diag2: 'மூலைவிட்டம் d₂', d_par_a: 'இணைப் பக்கம் a', d_par_b: 'இணைப் பக்கம் b',
  d_radius: 'ஆரம் (r)', d_outer: 'வெளி ஆரம் (R)', d_inner: 'உள் ஆரம் (r)', d_r1: 'மேல் ஆரம் (r₁)', d_r2: 'கீழ் ஆரம் (r₂)',
  r_area: 'பரப்பளவு', r_perimeter: 'சுற்றளவு', r_circumference: 'பரிதி', r_diameter: 'விட்டம்', r_diagonal: 'மூலைவிட்டம்',
  r_s: 'அரைச் சுற்றளவு (s)', r_side: 'பக்கம் (a)', r_leg: 'சாய்ந்த பக்கம் (c)', r_width: 'பாதையின் அகலம்',
  r_volume: 'கன அளவு', r_lsa: 'பக்கப் பரப்பு (LSA)', r_csa: 'வளைபரப்பு (CSA)', r_tsa: 'மொத்தப் புறப்பரப்பு (TSA)',
  r_sa: 'புறப்பரப்பு', r_slant: 'சாய்வு உயரம் (l)', r_capacity: 'கொள்ளளவு',
  err_positive: 'ஒவ்வொரு கட்டத்திலும் 0-ஐ விடப் பெரிய எண்ணை எழுதுங்கள்.', err_big: 'தயவுசெய்து {max} வரையிலான எண்களைப் பயன்படுத்துங்கள்.',
  err_triangle: 'இந்தப் பக்கங்களால் முக்கோணம் அமையாது. எந்த இரண்டு பக்கங்களின் கூட்டுத்தொகையும் மூன்றாவது பக்கத்தை விடப் பெரிதாக இருக்க வேண்டும்.',
  err_para: 'உயரம் சாய்ந்த பக்கம் a-ஐ விட அதிகமாக இருக்க முடியாது.', err_ring: 'வெளி ஆரம் R, உள் ஆரம் r-ஐ விடப் பெரிதாக இருக்க வேண்டும்.',
  note_heron: 'ஹீரான் சூத்திரத்திற்கு மூன்று பக்கங்கள் மட்டும் போதும்; உயரம் தேவையில்லை.',
  note_trap: 'இங்குள்ள சுற்றளவு இருசமபக்கச் சரிவகத்திற்கானது (இரு சாய்ந்த பக்கங்களும் சமம்).',
  note_cyl: 'TSA மூடிய உருளைக்கானது. திறந்த குழாய்க்கு வளைபரப்பு மட்டுமே உண்டு.',
  note_hemi: 'TSA திண்ம அரைக்கோளத்திற்கானது (வளைந்த பகுதி + தட்டையான வட்டம்). கிண்ணத்தின் உட்பகுதி CSA மட்டுமே.',
  note_frustum: 'வகுப்பு 10: மேல் பகுதி வெட்டப்பட்ட கூம்பே இடைக்கண்டம். r₁, r₂ என்பவை இரண்டு வட்ட முனைகளின் ஆரங்கள்.',
  note_pi: 'குறிப்பு: ஆரம் 7-இன் மடங்காக இருந்தால் 22/7 எடுத்தால் விடை நேர்த்தியாக வரும்.',
  u_ha: 'ஹெக்டேர்', u_ml: 'மில்லிலிட்டர்', u_litre: 'லிட்டர்',
  pr_title: 'பயிற்சி', pr_which: 'கேள்விகள் எதில்', pr_both: 'இரண்டும்', pr_given: 'கொடுக்கப்பட்டது', pr_find: 'காண்க', pr_in_unit: '(விடை {u} இல்)',
  pr_answer: 'உங்கள் விடை', pr_check: 'சரிபார்', pr_show: 'தீர்வைக் காட்டு', pr_new: 'புதிய கேள்வி',
  pr_round: 'π = {pi} எனக் கொள்க. தேவைப்பட்டால் விடையை 2 தசம இடங்களுக்கு முழுமையாக்குக.',
  pr_right: 'சரி! விடை {ans}.', pr_wrong: 'சற்றுத் தவறு. சரியான விடை {ans}. கீழே உள்ள தீர்வைப் படியுங்கள்.',
  pr_enter: 'முதலில் உங்கள் விடையை எண்ணாக எழுதுங்கள்.', pr_score: 'மதிப்பெண்: {n} இல் {c}', pr_streak: 'தொடர்ந்து சரி: {n} 🔥',
  ws_title: 'பணித்தாள்: பரப்பளவு, கன அளவு', ws_note: 'விடைக் குறிப்புடன் 10 புதிய கேள்விகளை உருவாக்கி அச்சிடுங்கள். விடைகளில் π = {pi}.',
  ws_make: 'பணித்தாள் உருவாக்கு', ws_print: 'பணித்தாளை அச்சிடு', ws_head: 'பெயர்: ____________   வகுப்பு: ______   தேதி: __________',
  ws_line: 'விடை: ______________', ws_answers: 'விடைக் குறிப்பு',
  cv_title: 'அலகுகளை மாற்று', cv_length: 'நீளம்', cv_area: 'பரப்பளவு', cv_volume: 'கன அளவு & கொள்ளளவு', cv_value: 'மதிப்பு', cv_from: 'எந்த அலகிலிருந்து',
  cv_unit_col: 'அலகு', cv_value_col: 'மதிப்பு',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km.',
  cv_rule_area: 'பரப்பளவுக்கு நீள விதியை வர்க்கம் செய்யுங்கள்: 1 m = 100 cm, எனவே 1 m² = 100 × 100 = 10,000 cm². மேலும் 1 ஹெக்டேர் = 10,000 m², 1 km² = 100 ஹெக்டேர்.',
  cv_rule_vol: 'கன அளவுக்கு நீள விதியைக் கனம் செய்யுங்கள்: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³. மேலும் 1 cm³ = 1 mL, 1000 cm³ = 1 லிட்டர், 1 m³ = 1000 லிட்டர்.',
  help_title: 'எப்படிப் பயன்படுத்துவது · வகுப்பறை யோசனைகள்',
  tip1: '2D அல்லது 3D-ஐத் தேர்ந்தெடுத்து, ஒரு வடிவத்தைத் தொட்டு அதன் அளவுகளை எழுதுங்கள். எழுதும்போதே விடைகள் மாறும்.',
  tip2: 'π-ஐ 22/7, 3.14 என மாற்றி ஒப்பிடுங்கள். ஆரம் 7-இன் மடங்காக இருந்தால் பாடநூல்கள் 22/7 எடுக்கின்றன, ஏனெனில் விடை நேர்த்தியாக வரும்.',
  tip3: 'தீர்வைப் பாடநூல் போலப் படியுங்கள்: சூத்திரம் எழுது, எண்களைப் பிரதியிடு, சுருக்கு, அலகுடன் விடை எழுது.',
  tip4: 'அலகுப் பொத்தான்களும் மாற்றியும் கொண்டு 1 m² என்பது 10,000 cm², 100 cm² அல்ல என்று காட்டுங்கள்.',
  tip5: 'வகுப்புச் செயல்பாடு: ஒவ்வொரு குழுவுக்கும் ஓர் உண்மையான பொருளைக் கொடுங்கள் (வாளி, டப்பா, இனிப்புப் பெட்டி). அவர்கள் அளந்து, கன அளவை ஊகித்து, பிறகு இங்கே சரிபார்க்கட்டும்.',
  tip6: 'பயிற்சியில் ஒவ்வொரு முறையும் புதிய கேள்விகள் வரும். வீட்டுப்பாடம் அல்லது வகுப்புத் தேர்வுக்கு விடைக் குறிப்புடன் பணித்தாள் உருவாக்குங்கள்.'
};
window.APP_STRINGS.te = {
  app_title: 'వైశాల్యం & ఘనపరిమాణం ల్యాబ్',
  intro: 'ఒక ఆకారాన్ని ఎంచుకుని, దాని కొలతలు రాయండి; దాని వైశాల్యం, చుట్టుకొలత, ఘనపరిమాణం, ఉపరితల వైశాల్యాలను కొలత ప్రకారం గీసిన బొమ్మ, దశలవారీ సాధనతో చూడండి.',
  tab_calc: 'క్యాలిక్యులేటర్', tab_practice: 'అభ్యాసం', tab_units: 'ప్రమాణాల మార్పిడి',
  choose_shape: 'ఆకారాన్ని ఎంచుకోండి', grp_2d: '2D ఆకారాలు', grp_3d: '3D ఘనాలు',
  grp_2d_hint: 'సమతల ఆకారాలు: వైశాల్యం, చుట్టుకొలత (6–9 తరగతులు)', grp_3d_hint: 'ఘనాలు: ఘనపరిమాణం, ఉపరితల వైశాల్యం (8–10 తరగతులు)',
  measurements: 'కొలతలు', unit: 'ప్రమాణం', pi_value: 'π విలువ', sample: 'నమూనా విలువలు',
  results: 'జవాబులు', working: 'దశలవారీ సాధన', other_units: 'అదే జవాబు ఇతర ప్రమాణాలలో',
  real_life: 'నిజ జీవితంలో: {x}', fig_aria: 'పేర్లు రాసిన బొమ్మ', fig_note: 'బొమ్మ కొలత ప్రకారం ఉంది: ఏదైనా సంఖ్య మార్చితే ఆకారం కూడా మారుతుంది.',
  approx_note: '≈ అంటే జవాబును 2 దశాంశ స్థానాల వరకు సవరించారు.',
  sh_square: 'చతురస్రం', sh_rectangle: 'దీర్ఘచతురస్రం', sh_tri_bh: 'త్రిభుజం (భూమి, ఎత్తు)', sh_tri_heron: 'త్రిభుజం (3 భుజాలు, హెరాన్)',
  sh_parallelogram: 'సమాంతర చతుర్భుజం', sh_rhombus: 'సమచతుర్భుజం (రాంబస్)', sh_trapezium: 'ట్రెపీజియం', sh_circle: 'వృత్తం', sh_semicircle: 'అర్ధవృత్తం',
  sh_ring: 'వలయం (వృత్తాకార బాట)', sh_cube: 'ఘనం', sh_cuboid: 'దీర్ఘఘనం', sh_cylinder: 'స్థూపం', sh_cone: 'శంకువు', sh_sphere: 'గోళం',
  sh_hemisphere: 'అర్ధగోళం', sh_frustum: 'శంకు భిన్నకం',
  ex_square: 'నేల టైల్, చదరంగం బోర్డు, క్యారమ్ బోర్డు', ex_rectangle: 'తరగతి గది నేల, క్రికెట్ పిచ్, మొబైల్ స్క్రీన్',
  ex_tri_bh: 'రోడ్డు సూచిక బోర్డు, పైకప్పు పక్క భాగం, సెట్ స్క్వేర్', ex_tri_heron: 'మూడు భుజాలూ కొలిచిన ఒక త్రిభుజాకార పొలం',
  ex_parallelogram: 'వాలుగా ఉన్న పార్కింగ్ స్థలం, టైల్స్ డిజైన్', ex_rhombus: 'గాలిపటం, పేకముక్కల మీద డైమండ్ గుర్తు',
  ex_trapezium: 'హ్యాండ్‌బ్యాగ్ పక్క భాగం, రోడ్డు పక్కన పొలం', ex_circle: 'రొట్టె, నాణెం, గుండ్రటి పార్కు',
  ex_semicircle: 'కోణమానిని, అర్ధచంద్రాకార కిటికీ', ex_ring: 'గుండ్రటి తోట చుట్టూ బాట, గాజు',
  ex_cube: 'పాచిక, రూబిక్ క్యూబ్, చక్కెర ముక్క', ex_cuboid: 'ఇటుక, అగ్గిపెట్టె, బీరువా, నీటి ట్యాంకు',
  ex_cylinder: 'గ్యాస్ సిలిండర్, పైపు, డబ్బా, నీటి ట్యాంకు', ex_cone: 'ఐస్‌క్రీమ్ కోన్, పుట్టినరోజు టోపీ, గుడారం',
  ex_sphere: 'ఫుట్‌బాల్, లడ్డు, గోలీ', ex_hemisphere: 'గిన్నె, భవనం గుమ్మటం',
  ex_frustum: 'బకెట్, స్టీలు గ్లాసు, లాంప్‌షేడ్',
  d_side: 'భుజం (a)', d_edge: 'అంచు (a)', d_length: 'పొడవు (l)', d_breadth: 'వెడల్పు (b)', d_base: 'భూమి (b)', d_height: 'ఎత్తు (h)',
  d_side_a: 'భుజం a', d_side_b: 'భుజం b', d_side_c: 'భుజం c', d_slant_side: 'వాలు భుజం (a)',
  d_diag1: 'కర్ణం d₁', d_diag2: 'కర్ణం d₂', d_par_a: 'సమాంతర భుజం a', d_par_b: 'సమాంతర భుజం b',
  d_radius: 'వ్యాసార్ధం (r)', d_outer: 'బయటి వ్యాసార్ధం (R)', d_inner: 'లోపలి వ్యాసార్ధం (r)', d_r1: 'పై వ్యాసార్ధం (r₁)', d_r2: 'కింది వ్యాసార్ధం (r₂)',
  r_area: 'వైశాల్యం', r_perimeter: 'చుట్టుకొలత', r_circumference: 'పరిధి', r_diameter: 'వ్యాసం', r_diagonal: 'కర్ణం',
  r_s: 'అర్ధ చుట్టుకొలత (s)', r_side: 'భుజం (a)', r_leg: 'వాలు భుజం (c)', r_width: 'బాట వెడల్పు',
  r_volume: 'ఘనపరిమాణం', r_lsa: 'పార్శ్వ ఉపరితల వైశాల్యం (LSA)', r_csa: 'వక్రతల వైశాల్యం (CSA)', r_tsa: 'సంపూర్ణతల వైశాల్యం (TSA)',
  r_sa: 'ఉపరితల వైశాల్యం', r_slant: 'ఏటవాలు ఎత్తు (l)', r_capacity: 'ధారణ సామర్థ్యం',
  err_positive: 'ప్రతి గడిలో 0 కంటే పెద్ద సంఖ్య రాయండి.', err_big: 'దయచేసి {max} వరకు ఉన్న సంఖ్యలనే వాడండి.',
  err_triangle: 'ఈ భుజాలతో త్రిభుజం ఏర్పడదు. ఏ రెండు భుజాల మొత్తమైనా మూడో భుజం కంటే ఎక్కువగా ఉండాలి.',
  err_para: 'ఎత్తు వాలు భుజం a కంటే ఎక్కువ ఉండకూడదు.', err_ring: 'బయటి వ్యాసార్ధం R, లోపలి వ్యాసార్ధం r కంటే పెద్దదిగా ఉండాలి.',
  note_heron: 'హెరాన్ సూత్రానికి మూడు భుజాలు చాలు; ఎత్తు అవసరం లేదు.',
  note_trap: 'ఇక్కడ చుట్టుకొలత సమద్విబాహు ట్రెపీజియానిది (రెండు వాలు భుజాలు సమానం).',
  note_cyl: 'TSA మూసి ఉన్న స్థూపానిది. తెరిచి ఉన్న పైపుకు వక్రతలం మాత్రమే ఉంటుంది.',
  note_hemi: 'TSA ఘన అర్ధగోళానిది (వంపు భాగం + చదునైన వృత్తం). గిన్నె లోపలి భాగం CSA మాత్రమే.',
  note_frustum: '10వ తరగతి: పై భాగం కోసివేసిన శంకువే భిన్నకం. r₁, r₂ రెండు వృత్తాకార చివరల వ్యాసార్ధాలు.',
  note_pi: 'సూచన: వ్యాసార్ధం 7 గుణిజం అయితే 22/7 తీసుకుంటే జవాబు చక్కగా వస్తుంది.',
  u_ha: 'హెక్టారు', u_ml: 'మిల్లీలీటరు', u_litre: 'లీటరు',
  pr_title: 'అభ్యాసం', pr_which: 'ప్రశ్నలు దేనిపై', pr_both: 'రెండూ', pr_given: 'ఇచ్చినవి', pr_find: 'కనుక్కోండి', pr_in_unit: '(జవాబు {u}లో)',
  pr_answer: 'మీ జవాబు', pr_check: 'సరిచూడు', pr_show: 'సాధన చూపు', pr_new: 'కొత్త ప్రశ్న',
  pr_round: 'π = {pi} తీసుకోండి. అవసరమైతే జవాబును 2 దశాంశ స్థానాల వరకు సవరించండి.',
  pr_right: 'సరైనది! జవాబు {ans}.', pr_wrong: 'కొంచెం తప్పింది. సరైన జవాబు {ans}. కింద ఉన్న సాధన చదవండి.',
  pr_enter: 'ముందుగా మీ జవాబును సంఖ్యగా రాయండి.', pr_score: 'స్కోరు: {n}కి {c}', pr_streak: 'వరుసగా సరైనవి: {n} 🔥',
  ws_title: 'వర్క్‌షీట్: వైశాల్యం, ఘనపరిమాణం', ws_note: 'జవాబుల కీతో 10 కొత్త ప్రశ్నలు తయారుచేసి ప్రింట్ చేయండి. జవాబుల్లో π = {pi}.',
  ws_make: 'వర్క్‌షీట్ తయారుచేయండి', ws_print: 'వర్క్‌షీట్ ప్రింట్ చేయండి', ws_head: 'పేరు: ____________   తరగతి: ______   తేదీ: __________',
  ws_line: 'జవాబు: ______________', ws_answers: 'జవాబుల కీ',
  cv_title: 'ప్రమాణాలను మార్చండి', cv_length: 'పొడవు', cv_area: 'వైశాల్యం', cv_volume: 'ఘనపరిమాణం & ధారణ సామర్థ్యం', cv_value: 'విలువ', cv_from: 'ఏ ప్రమాణం నుంచి',
  cv_unit_col: 'ప్రమాణం', cv_value_col: 'విలువ',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km.',
  cv_rule_area: 'వైశాల్యానికి పొడవు నియమాన్ని వర్గం చేయండి: 1 m = 100 cm, కాబట్టి 1 m² = 100 × 100 = 10,000 cm². అలాగే 1 హెక్టారు = 10,000 m², 1 km² = 100 హెక్టార్లు.',
  cv_rule_vol: 'ఘనపరిమాణానికి పొడవు నియమాన్ని ఘనం చేయండి: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³. అలాగే 1 cm³ = 1 mL, 1000 cm³ = 1 లీటరు, 1 m³ = 1000 లీటర్లు.',
  help_title: 'ఎలా వాడాలి · తరగతి గది ఆలోచనలు',
  tip1: '2D లేదా 3D ఎంచుకుని, ఒక ఆకారాన్ని తాకి, దాని కొలతలు రాయండి. రాస్తూ ఉండగానే జవాబులు మారుతాయి.',
  tip2: 'π ను 22/7, 3.14 మధ్య మార్చి పోల్చండి. వ్యాసార్ధం 7 గుణిజం అయితే పాఠ్యపుస్తకాలు 22/7 తీసుకుంటాయి, ఎందుకంటే జవాబు చక్కగా వస్తుంది.',
  tip3: 'సాధనను పాఠ్యపుస్తకంలా చదవండి: సూత్రం రాయి, సంఖ్యలు ప్రతిక్షేపించు, సూక్ష్మీకరించు, ప్రమాణంతో జవాబు రాయి.',
  tip4: 'ప్రమాణ బటన్లు, మార్పిడి సాధనంతో 1 m² అంటే 10,000 cm², 100 cm² కాదు అని చూపించండి.',
  tip5: 'తరగతి కృత్యం: ప్రతి బృందానికి ఒక నిజమైన వస్తువు ఇవ్వండి (బకెట్, డబ్బా, స్వీట్ల పెట్టె). వాళ్లు కొలిచి, ఘనపరిమాణాన్ని అంచనా వేసి, తర్వాత ఇక్కడ సరిచూసుకుంటారు.',
  tip6: 'అభ్యాసంలో ప్రతిసారీ కొత్త ప్రశ్నలు వస్తాయి. హోంవర్క్ లేదా తరగతి పరీక్ష కోసం జవాబుల కీతో వర్క్‌షీట్ తయారుచేయండి.'
};
window.APP_STRINGS.kn = {
  app_title: 'ವಿಸ್ತೀರ್ಣ ಮತ್ತು ಘನಫಲ ಲ್ಯಾಬ್',
  intro: 'ಒಂದು ಆಕೃತಿಯನ್ನು ಆರಿಸಿ, ಅದರ ಅಳತೆಗಳನ್ನು ಬರೆಯಿರಿ; ಅದರ ವಿಸ್ತೀರ್ಣ, ಸುತ್ತಳತೆ, ಘನಫಲ ಮತ್ತು ಮೇಲ್ಮೈ ವಿಸ್ತೀರ್ಣವನ್ನು ಅಳತೆಗೆ ತಕ್ಕ ಚಿತ್ರ ಮತ್ತು ಹಂತ ಹಂತದ ಬಿಡಿಸುವಿಕೆಯೊಂದಿಗೆ ನೋಡಿ.',
  tab_calc: 'ಕ್ಯಾಲ್ಕುಲೇಟರ್', tab_practice: 'ಅಭ್ಯಾಸ', tab_units: 'ಏಕಮಾನ ಬದಲಾವಣೆ',
  choose_shape: 'ಆಕೃತಿಯನ್ನು ಆರಿಸಿ', grp_2d: '2D ಆಕೃತಿಗಳು', grp_3d: '3D ಘನಾಕೃತಿಗಳು',
  grp_2d_hint: 'ಸಮತಲ ಆಕೃತಿಗಳು: ವಿಸ್ತೀರ್ಣ ಮತ್ತು ಸುತ್ತಳತೆ (6–9ನೇ ತರಗತಿ)', grp_3d_hint: 'ಘನಾಕೃತಿಗಳು: ಘನಫಲ ಮತ್ತು ಮೇಲ್ಮೈ ವಿಸ್ತೀರ್ಣ (8–10ನೇ ತರಗತಿ)',
  measurements: 'ಅಳತೆಗಳು', unit: 'ಏಕಮಾನ', pi_value: 'π ದ ಬೆಲೆ', sample: 'ಮಾದರಿ ಬೆಲೆಗಳು',
  results: 'ಉತ್ತರಗಳು', working: 'ಹಂತ ಹಂತದ ಬಿಡಿಸುವಿಕೆ', other_units: 'ಇದೇ ಉತ್ತರ ಬೇರೆ ಏಕಮಾನಗಳಲ್ಲಿ',
  real_life: 'ನಿಜ ಜೀವನದಲ್ಲಿ: {x}', fig_aria: 'ಹೆಸರಿಸಿದ ಚಿತ್ರ', fig_note: 'ಚಿತ್ರ ಅಳತೆಗೆ ತಕ್ಕಂತಿದೆ: ಯಾವುದೇ ಸಂಖ್ಯೆ ಬದಲಿಸಿದರೆ ಆಕೃತಿಯೂ ಬದಲಾಗುತ್ತದೆ.',
  approx_note: '≈ ಅಂದರೆ ಉತ್ತರವನ್ನು 2 ದಶಮಾಂಶ ಸ್ಥಾನಗಳವರೆಗೆ ಸರಿಹೊಂದಿಸಲಾಗಿದೆ.',
  sh_square: 'ಚೌಕ', sh_rectangle: 'ಆಯತ', sh_tri_bh: 'ತ್ರಿಭುಜ (ಪಾದ ಮತ್ತು ಎತ್ತರ)', sh_tri_heron: 'ತ್ರಿಭುಜ (3 ಬಾಹುಗಳು, ಹೆರಾನ್)',
  sh_parallelogram: 'ಸಮಾಂತರ ಚತುರ್ಭುಜ', sh_rhombus: 'ವಜ್ರಾಕೃತಿ', sh_trapezium: 'ತ್ರಾಪಿಜ್ಯ', sh_circle: 'ವೃತ್ತ', sh_semicircle: 'ಅರ್ಧವೃತ್ತ',
  sh_ring: 'ಉಂಗುರ (ವೃತ್ತಾಕಾರದ ದಾರಿ)', sh_cube: 'ಘನ', sh_cuboid: 'ಆಯತಘನ', sh_cylinder: 'ಸಿಲಿಂಡರ್', sh_cone: 'ಶಂಕು', sh_sphere: 'ಗೋಳ',
  sh_hemisphere: 'ಅರ್ಧಗೋಳ', sh_frustum: 'ಶಂಕುವಿನ ಛಿನ್ನಕ',
  ex_square: 'ನೆಲದ ಟೈಲ್, ಚದುರಂಗದ ಮಣೆ, ಕೇರಂ ಬೋರ್ಡ್', ex_rectangle: 'ತರಗತಿಯ ನೆಲ, ಕ್ರಿಕೆಟ್ ಪಿಚ್, ಮೊಬೈಲ್ ಪರದೆ',
  ex_tri_bh: 'ರಸ್ತೆಯ ಸೂಚನಾ ಫಲಕ, ಚಾವಣಿಯ ಪಕ್ಕ, ಸೆಟ್ ಸ್ಕ್ವೇರ್', ex_tri_heron: 'ಮೂರೂ ಬಾಹುಗಳನ್ನು ಅಳೆದಿರುವ ಒಂದು ತ್ರಿಕೋನಾಕಾರದ ಹೊಲ',
  ex_parallelogram: 'ಓರೆಯಾದ ಪಾರ್ಕಿಂಗ್ ಜಾಗ, ಟೈಲ್ ವಿನ್ಯಾಸ', ex_rhombus: 'ಗಾಳಿಪಟ, ಇಸ್ಪೀಟ್ ಎಲೆಯ ಡೈಮಂಡ್ ಗುರುತು',
  ex_trapezium: 'ಕೈಚೀಲದ ಪಕ್ಕ, ರಸ್ತೆಬದಿಯ ಹೊಲ', ex_circle: 'ರೊಟ್ಟಿ, ನಾಣ್ಯ, ವೃತ್ತಾಕಾರದ ಉದ್ಯಾನ',
  ex_semicircle: 'ಕೋನಮಾಪಕ, ಅರ್ಧಚಂದ್ರಾಕಾರದ ಕಿಟಕಿ', ex_ring: 'ವೃತ್ತಾಕಾರದ ತೋಟದ ಸುತ್ತಲಿನ ದಾರಿ, ಬಳೆ',
  ex_cube: 'ದಾಳ, ರೂಬಿಕ್ ಕ್ಯೂಬ್, ಸಕ್ಕರೆ ತುಂಡು', ex_cuboid: 'ಇಟ್ಟಿಗೆ, ಬೆಂಕಿಪೊಟ್ಟಣ, ಕಪಾಟು, ನೀರಿನ ತೊಟ್ಟಿ',
  ex_cylinder: 'ಗ್ಯಾಸ್ ಸಿಲಿಂಡರ್, ಪೈಪ್, ಡಬ್ಬಿ, ನೀರಿನ ತೊಟ್ಟಿ', ex_cone: 'ಐಸ್‌ಕ್ರೀಮ್ ಕೋನ್, ಹುಟ್ಟುಹಬ್ಬದ ಟೋಪಿ, ಡೇರೆ',
  ex_sphere: 'ಫುಟ್‌ಬಾಲ್, ಲಾಡು, ಗೋಲಿ', ex_hemisphere: 'ಬಟ್ಟಲು, ಕಟ್ಟಡದ ಗುಮ್ಮಟ',
  ex_frustum: 'ಬಕೆಟ್, ಸ್ಟೀಲ್ ಲೋಟ, ದೀಪದ ಶೇಡ್',
  d_side: 'ಬಾಹು (a)', d_edge: 'ಅಂಚು (a)', d_length: 'ಉದ್ದ (l)', d_breadth: 'ಅಗಲ (b)', d_base: 'ಪಾದ (b)', d_height: 'ಎತ್ತರ (h)',
  d_side_a: 'ಬಾಹು a', d_side_b: 'ಬಾಹು b', d_side_c: 'ಬಾಹು c', d_slant_side: 'ಓರೆ ಬಾಹು (a)',
  d_diag1: 'ಕರ್ಣ d₁', d_diag2: 'ಕರ್ಣ d₂', d_par_a: 'ಸಮಾಂತರ ಬಾಹು a', d_par_b: 'ಸಮಾಂತರ ಬಾಹು b',
  d_radius: 'ತ್ರಿಜ್ಯ (r)', d_outer: 'ಹೊರ ತ್ರಿಜ್ಯ (R)', d_inner: 'ಒಳ ತ್ರಿಜ್ಯ (r)', d_r1: 'ಮೇಲಿನ ತ್ರಿಜ್ಯ (r₁)', d_r2: 'ಕೆಳಗಿನ ತ್ರಿಜ್ಯ (r₂)',
  r_area: 'ವಿಸ್ತೀರ್ಣ', r_perimeter: 'ಸುತ್ತಳತೆ', r_circumference: 'ಪರಿಧಿ', r_diameter: 'ವ್ಯಾಸ', r_diagonal: 'ಕರ್ಣ',
  r_s: 'ಅರ್ಧ ಸುತ್ತಳತೆ (s)', r_side: 'ಬಾಹು (a)', r_leg: 'ಓರೆ ಬಾಹು (c)', r_width: 'ದಾರಿಯ ಅಗಲ',
  r_volume: 'ಘನಫಲ', r_lsa: 'ಪಾರ್ಶ್ವ ಮೇಲ್ಮೈ ವಿಸ್ತೀರ್ಣ (LSA)', r_csa: 'ವಕ್ರ ಮೇಲ್ಮೈ ವಿಸ್ತೀರ್ಣ (CSA)', r_tsa: 'ಒಟ್ಟು ಮೇಲ್ಮೈ ವಿಸ್ತೀರ್ಣ (TSA)',
  r_sa: 'ಮೇಲ್ಮೈ ವಿಸ್ತೀರ್ಣ', r_slant: 'ಓರೆ ಎತ್ತರ (l)', r_capacity: 'ಧಾರಣ ಸಾಮರ್ಥ್ಯ',
  err_positive: 'ಪ್ರತಿ ಚೌಕದಲ್ಲೂ 0 ಗಿಂತ ದೊಡ್ಡ ಸಂಖ್ಯೆ ಬರೆಯಿರಿ.', err_big: 'ದಯವಿಟ್ಟು {max} ವರೆಗಿನ ಸಂಖ್ಯೆಗಳನ್ನು ಮಾತ್ರ ಬಳಸಿ.',
  err_triangle: 'ಈ ಬಾಹುಗಳಿಂದ ತ್ರಿಭುಜ ಆಗುವುದಿಲ್ಲ. ಯಾವುದೇ ಎರಡು ಬಾಹುಗಳ ಮೊತ್ತ ಮೂರನೇ ಬಾಹುವಿಗಿಂತ ಹೆಚ್ಚಿರಬೇಕು.',
  err_para: 'ಎತ್ತರವು ಓರೆ ಬಾಹು a ಗಿಂತ ಹೆಚ್ಚಿರಲು ಸಾಧ್ಯವಿಲ್ಲ.', err_ring: 'ಹೊರ ತ್ರಿಜ್ಯ R, ಒಳ ತ್ರಿಜ್ಯ r ಗಿಂತ ದೊಡ್ಡದಿರಬೇಕು.',
  note_heron: 'ಹೆರಾನ್ ಸೂತ್ರಕ್ಕೆ ಮೂರು ಬಾಹುಗಳು ಸಾಕು; ಎತ್ತರ ಬೇಕಿಲ್ಲ.',
  note_trap: 'ಇಲ್ಲಿನ ಸುತ್ತಳತೆ ಸಮದ್ವಿಬಾಹು ತ್ರಾಪಿಜ್ಯದ್ದು (ಎರಡೂ ಓರೆ ಬಾಹುಗಳು ಸಮ).',
  note_cyl: 'TSA ಮುಚ್ಚಿದ ಸಿಲಿಂಡರ್‌ನದ್ದು. ತೆರೆದ ಪೈಪ್‌ಗೆ ವಕ್ರ ಮೇಲ್ಮೈ ಮಾತ್ರ ಇರುತ್ತದೆ.',
  note_hemi: 'TSA ಘನ ಅರ್ಧಗೋಳದ್ದು (ವಕ್ರ ಭಾಗ + ಸಮತಟ್ಟಾದ ವೃತ್ತ). ಬಟ್ಟಲಿನ ಒಳಭಾಗ CSA ಮಾತ್ರ.',
  note_frustum: '10ನೇ ತರಗತಿ: ಮೇಲ್ಭಾಗ ಕತ್ತರಿಸಿದ ಶಂಕುವೇ ಛಿನ್ನಕ. r₁ ಮತ್ತು r₂ ಎರಡು ವೃತ್ತಾಕಾರದ ತುದಿಗಳ ತ್ರಿಜ್ಯಗಳು.',
  note_pi: 'ಸಲಹೆ: ತ್ರಿಜ್ಯ 7 ರ ಅಪವರ್ತ್ಯವಾಗಿದ್ದರೆ 22/7 ತೆಗೆದುಕೊಂಡರೆ ಉತ್ತರ ಅಚ್ಚುಕಟ್ಟಾಗಿ ಬರುತ್ತದೆ.',
  u_ha: 'ಹೆಕ್ಟೇರ್', u_ml: 'ಮಿಲಿಲೀಟರ್', u_litre: 'ಲೀಟರ್',
  pr_title: 'ಅಭ್ಯಾಸ', pr_which: 'ಪ್ರಶ್ನೆಗಳು ಯಾವುದರ ಮೇಲೆ', pr_both: 'ಎರಡೂ', pr_given: 'ಕೊಟ್ಟಿರುವುದು', pr_find: 'ಕಂಡುಹಿಡಿಯಿರಿ', pr_in_unit: '(ಉತ್ತರ {u} ನಲ್ಲಿ)',
  pr_answer: 'ನಿಮ್ಮ ಉತ್ತರ', pr_check: 'ಪರಿಶೀಲಿಸಿ', pr_show: 'ಬಿಡಿಸುವಿಕೆ ತೋರಿಸಿ', pr_new: 'ಹೊಸ ಪ್ರಶ್ನೆ',
  pr_round: 'π = {pi} ತೆಗೆದುಕೊಳ್ಳಿ. ಬೇಕಾದರೆ ಉತ್ತರವನ್ನು 2 ದಶಮಾಂಶ ಸ್ಥಾನಗಳವರೆಗೆ ಸರಿಹೊಂದಿಸಿ.',
  pr_right: 'ಸರಿ! ಉತ್ತರ {ans}.', pr_wrong: 'ಸ್ವಲ್ಪ ತಪ್ಪಾಯಿತು. ಸರಿಯಾದ ಉತ್ತರ {ans}. ಕೆಳಗಿನ ಬಿಡಿಸುವಿಕೆಯನ್ನು ಓದಿ.',
  pr_enter: 'ಮೊದಲು ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಸಂಖ್ಯೆಯಲ್ಲಿ ಬರೆಯಿರಿ.', pr_score: 'ಅಂಕ: {n} ರಲ್ಲಿ {c}', pr_streak: 'ಸತತ ಸರಿ: {n} 🔥',
  ws_title: 'ವರ್ಕ್‌ಶೀಟ್: ವಿಸ್ತೀರ್ಣ ಮತ್ತು ಘನಫಲ', ws_note: 'ಉತ್ತರ ಸೂಚಿಯೊಂದಿಗೆ 10 ಹೊಸ ಪ್ರಶ್ನೆಗಳನ್ನು ಮಾಡಿ ಮುದ್ರಿಸಿ. ಉತ್ತರಗಳಲ್ಲಿ π = {pi}.',
  ws_make: 'ವರ್ಕ್‌ಶೀಟ್ ಮಾಡಿ', ws_print: 'ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ', ws_head: 'ಹೆಸರು: ____________   ತರಗತಿ: ______   ದಿನಾಂಕ: __________',
  ws_line: 'ಉತ್ತರ: ______________', ws_answers: 'ಉತ್ತರ ಸೂಚಿ',
  cv_title: 'ಏಕಮಾನಗಳನ್ನು ಬದಲಿಸಿ', cv_length: 'ಉದ್ದ', cv_area: 'ವಿಸ್ತೀರ್ಣ', cv_volume: 'ಘನಫಲ ಮತ್ತು ಧಾರಣ ಸಾಮರ್ಥ್ಯ', cv_value: 'ಬೆಲೆ', cv_from: 'ಯಾವ ಏಕಮಾನದಿಂದ',
  cv_unit_col: 'ಏಕಮಾನ', cv_value_col: 'ಬೆಲೆ',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km.',
  cv_rule_area: 'ವಿಸ್ತೀರ್ಣಕ್ಕೆ ಉದ್ದದ ನಿಯಮದ ವರ್ಗ ಮಾಡಿ: 1 m = 100 cm, ಆದ್ದರಿಂದ 1 m² = 100 × 100 = 10,000 cm². ಹಾಗೆಯೇ 1 ಹೆಕ್ಟೇರ್ = 10,000 m² ಮತ್ತು 1 km² = 100 ಹೆಕ್ಟೇರ್.',
  cv_rule_vol: 'ಘನಫಲಕ್ಕೆ ಉದ್ದದ ನಿಯಮದ ಘನ ಮಾಡಿ: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³. ಹಾಗೆಯೇ 1 cm³ = 1 mL, 1000 cm³ = 1 ಲೀಟರ್ ಮತ್ತು 1 m³ = 1000 ಲೀಟರ್.',
  help_title: 'ಬಳಸುವುದು ಹೇಗೆ · ತರಗತಿಗೆ ಉಪಾಯಗಳು',
  tip1: '2D ಅಥವಾ 3D ಆರಿಸಿ, ಒಂದು ಆಕೃತಿಯನ್ನು ಒತ್ತಿ ಮತ್ತು ಅದರ ಅಳತೆಗಳನ್ನು ಬರೆಯಿರಿ. ಬರೆಯುತ್ತಿದ್ದಂತೆಯೇ ಉತ್ತರಗಳು ಬದಲಾಗುತ್ತವೆ.',
  tip2: 'π ಅನ್ನು 22/7 ಮತ್ತು 3.14 ನಡುವೆ ಬದಲಿಸಿ ಹೋಲಿಸಿ. ತ್ರಿಜ್ಯ 7 ರ ಅಪವರ್ತ್ಯವಾದಾಗ ಪಠ್ಯಪುಸ್ತಕಗಳು 22/7 ತೆಗೆದುಕೊಳ್ಳುತ್ತವೆ, ಏಕೆಂದರೆ ಉತ್ತರ ಅಚ್ಚುಕಟ್ಟಾಗಿ ಬರುತ್ತದೆ.',
  tip3: 'ಬಿಡಿಸುವಿಕೆಯನ್ನು ಪಠ್ಯಪುಸ್ತಕದಂತೆ ಓದಿ: ಸೂತ್ರ ಬರೆಯಿರಿ, ಸಂಖ್ಯೆಗಳನ್ನು ಆದೇಶಿಸಿ, ಸರಳಗೊಳಿಸಿ ಮತ್ತು ಏಕಮಾನದೊಂದಿಗೆ ಉತ್ತರ ಬರೆಯಿರಿ.',
  tip4: 'ಏಕಮಾನ ಗುಂಡಿಗಳು ಮತ್ತು ಪರಿವರ್ತಕದಿಂದ 1 m² ಅಂದರೆ 10,000 cm², 100 cm² ಅಲ್ಲ ಎಂದು ತೋರಿಸಿ.',
  tip5: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಪ್ರತಿ ಗುಂಪಿಗೆ ಒಂದು ನಿಜವಾದ ವಸ್ತು ಕೊಡಿ (ಬಕೆಟ್, ಡಬ್ಬಿ, ಸಿಹಿ ಪೆಟ್ಟಿಗೆ). ಅವರು ಅಳೆದು, ಘನಫಲವನ್ನು ಊಹಿಸಿ, ನಂತರ ಇಲ್ಲಿ ಪರಿಶೀಲಿಸಲಿ.',
  tip6: 'ಅಭ್ಯಾಸದಲ್ಲಿ ಪ್ರತಿ ಬಾರಿ ಹೊಸ ಪ್ರಶ್ನೆಗಳು ಬರುತ್ತವೆ. ಮನೆಗೆಲಸ ಅಥವಾ ತರಗತಿ ಪರೀಕ್ಷೆಗೆ ಉತ್ತರ ಸೂಚಿಯೊಂದಿಗೆ ವರ್ಕ್‌ಶೀಟ್ ಮಾಡಿ.'
};
window.APP_STRINGS.ml = {
  app_title: 'പരപ്പളവ് & വ്യാപ്തം ലാബ്',
  intro: 'ഒരു രൂപം തിരഞ്ഞെടുത്ത് അതിന്റെ അളവുകൾ എഴുതൂ; അതിന്റെ പരപ്പളവ്, ചുറ്റളവ്, വ്യാപ്തം, ഉപരിതല പരപ്പളവ് എന്നിവ അളവിനൊത്ത ചിത്രവും പടിപടിയായ നിർദ്ധാരണവും സഹിതം കാണൂ.',
  tab_calc: 'കാൽക്കുലേറ്റർ', tab_practice: 'പരിശീലനം', tab_units: 'ഏകക മാറ്റം',
  choose_shape: 'രൂപം തിരഞ്ഞെടുക്കൂ', grp_2d: '2D രൂപങ്ങൾ', grp_3d: '3D ഘനരൂപങ്ങൾ',
  grp_2d_hint: 'പരന്ന രൂപങ്ങൾ: പരപ്പളവും ചുറ്റളവും (ക്ലാസ് 6–9)', grp_3d_hint: 'ഘനരൂപങ്ങൾ: വ്യാപ്തവും ഉപരിതല പരപ്പളവും (ക്ലാസ് 8–10)',
  measurements: 'അളവുകൾ', unit: 'ഏകകം', pi_value: 'π യുടെ വില', sample: 'മാതൃകാ വിലകൾ',
  results: 'ഉത്തരങ്ങൾ', working: 'പടിപടിയായ നിർദ്ധാരണം', other_units: 'ഇതേ ഉത്തരം മറ്റ് ഏകകങ്ങളിൽ',
  real_life: 'നിത്യജീവിതത്തിൽ: {x}', fig_aria: 'പേരെഴുതിയ ചിത്രം', fig_note: 'ചിത്രം അളവിനൊത്താണ്: ഒരു സംഖ്യ മാറ്റിയാൽ രൂപവും മാറും.',
  approx_note: '≈ എന്നാൽ ഉത്തരം 2 ദശാംശ സ്ഥാനങ്ങൾ വരെ ഏകദേശമാക്കിയതാണ്.',
  sh_square: 'സമചതുരം', sh_rectangle: 'ചതുരം', sh_tri_bh: 'ത്രികോണം (പാദവും ഉയരവും)', sh_tri_heron: 'ത്രികോണം (3 വശങ്ങൾ, ഹെറോൺ)',
  sh_parallelogram: 'സാമാന്തരികം', sh_rhombus: 'സമഭുജ സാമാന്തരികം', sh_trapezium: 'ലംബകം', sh_circle: 'വൃത്തം', sh_semicircle: 'അർധവൃത്തം',
  sh_ring: 'വലയം (വൃത്താകൃതിയിലുള്ള പാത)', sh_cube: 'സമചതുരക്കട്ട', sh_cuboid: 'ചതുരക്കട്ട', sh_cylinder: 'വൃത്തസ്തംഭം', sh_cone: 'വൃത്തസ്തൂപിക', sh_sphere: 'ഗോളം',
  sh_hemisphere: 'അർധഗോളം', sh_frustum: 'സ്തൂപികാഛിന്നം',
  ex_square: 'തറയിലെ ടൈൽ, ചെസ് ബോർഡ്, കാരംസ് ബോർഡ്', ex_rectangle: 'ക്ലാസ് മുറിയുടെ തറ, ക്രിക്കറ്റ് പിച്ച്, മൊബൈൽ സ്ക്രീൻ',
  ex_tri_bh: 'റോഡിലെ സൂചനാ ബോർഡ്, മേൽക്കൂരയുടെ വശം, സെറ്റ് സ്ക്വയർ', ex_tri_heron: 'മൂന്നു വശങ്ങളും അളന്ന ഒരു ത്രികോണാകൃതിയിലുള്ള പറമ്പ്',
  ex_parallelogram: 'ചരിഞ്ഞ പാർക്കിങ് സ്ഥലം, ടൈൽ ഡിസൈൻ', ex_rhombus: 'പട്ടം, ചീട്ടിലെ ഡയമണ്ട് അടയാളം',
  ex_trapezium: 'ഹാൻഡ്ബാഗിന്റെ വശം, റോഡരികിലെ പറമ്പ്', ex_circle: 'ചപ്പാത്തി, നാണയം, വൃത്താകൃതിയിലുള്ള പാർക്ക്',
  ex_semicircle: 'കോണമാപിനി, അർധചന്ദ്രാകൃതിയിലുള്ള ജനൽ', ex_ring: 'വട്ടത്തിലുള്ള പൂന്തോട്ടത്തിനു ചുറ്റുമുള്ള വഴി, വള',
  ex_cube: 'പകിട, റൂബിക് ക്യൂബ്, പഞ്ചസാരക്കട്ട', ex_cuboid: 'ഇഷ്ടിക, തീപ്പെട്ടി, അലമാര, വെള്ളടാങ്ക്',
  ex_cylinder: 'ഗ്യാസ് സിലിണ്ടർ, പൈപ്പ്, ടിൻ, വെള്ളടാങ്ക്', ex_cone: 'ഐസ്ക്രീം കോൺ, പിറന്നാൾ തൊപ്പി, കൂടാരം',
  ex_sphere: 'ഫുട്ബോൾ, ലഡ്ഡു, ഗോലി', ex_hemisphere: 'കിണ്ണം, കെട്ടിടത്തിന്റെ താഴികക്കുടം',
  ex_frustum: 'ബക്കറ്റ്, സ്റ്റീൽ ഗ്ലാസ്, ലാമ്പ്ഷേഡ്',
  d_side: 'വശം (a)', d_edge: 'വക്ക് (a)', d_length: 'നീളം (l)', d_breadth: 'വീതി (b)', d_base: 'പാദം (b)', d_height: 'ഉയരം (h)',
  d_side_a: 'വശം a', d_side_b: 'വശം b', d_side_c: 'വശം c', d_slant_side: 'ചരിഞ്ഞ വശം (a)',
  d_diag1: 'വികർണം d₁', d_diag2: 'വികർണം d₂', d_par_a: 'സമാന്തര വശം a', d_par_b: 'സമാന്തര വശം b',
  d_radius: 'ആരം (r)', d_outer: 'പുറത്തെ ആരം (R)', d_inner: 'അകത്തെ ആരം (r)', d_r1: 'മുകളിലെ ആരം (r₁)', d_r2: 'താഴത്തെ ആരം (r₂)',
  r_area: 'പരപ്പളവ്', r_perimeter: 'ചുറ്റളവ്', r_circumference: 'വൃത്തത്തിന്റെ ചുറ്റളവ്', r_diameter: 'വ്യാസം', r_diagonal: 'വികർണം',
  r_s: 'അർധചുറ്റളവ് (s)', r_side: 'വശം (a)', r_leg: 'ചരിഞ്ഞ വശം (c)', r_width: 'പാതയുടെ വീതി',
  r_volume: 'വ്യാപ്തം', r_lsa: 'പാർശ്വതല പരപ്പളവ് (LSA)', r_csa: 'വക്രതല പരപ്പളവ് (CSA)', r_tsa: 'ആകെ ഉപരിതല പരപ്പളവ് (TSA)',
  r_sa: 'ഉപരിതല പരപ്പളവ്', r_slant: 'ചരിവുയരം (l)', r_capacity: 'ഉൾക്കൊള്ളൽ ശേഷി',
  err_positive: 'ഓരോ കള്ളിയിലും 0-നെക്കാൾ വലിയ സംഖ്യ എഴുതൂ.', err_big: 'ദയവായി {max} വരെയുള്ള സംഖ്യകൾ മാത്രം ഉപയോഗിക്കൂ.',
  err_triangle: 'ഈ വശങ്ങൾ കൊണ്ട് ത്രികോണം ഉണ്ടാക്കാനാവില്ല. ഏതു രണ്ടു വശങ്ങളുടെയും തുക മൂന്നാമത്തെ വശത്തെക്കാൾ കൂടുതലായിരിക്കണം.',
  err_para: 'ഉയരം ചരിഞ്ഞ വശം a-യെക്കാൾ കൂടാൻ പാടില്ല.', err_ring: 'പുറത്തെ ആരം R, അകത്തെ ആരം r-നെക്കാൾ വലുതായിരിക്കണം.',
  note_heron: 'ഹെറോണിന്റെ സൂത്രവാക്യത്തിന് മൂന്നു വശങ്ങൾ മതി; ഉയരം വേണ്ട.',
  note_trap: 'ഇവിടത്തെ ചുറ്റളവ് സമപാർശ്വ ലംബകത്തിന്റേതാണ് (രണ്ടു ചരിഞ്ഞ വശങ്ങളും തുല്യം).',
  note_cyl: 'TSA അടഞ്ഞ വൃത്തസ്തംഭത്തിന്റേതാണ്. തുറന്ന പൈപ്പിന് വക്രതലം മാത്രമേയുള്ളൂ.',
  note_hemi: 'TSA ഖര അർധഗോളത്തിന്റേതാണ് (വളഞ്ഞ ഭാഗം + പരന്ന വൃത്തം). കിണ്ണത്തിന്റെ ഉൾഭാഗം CSA മാത്രം.',
  note_frustum: 'ക്ലാസ് 10: മുകൾഭാഗം മുറിച്ചുമാറ്റിയ സ്തൂപികയാണ് ഛിന്നം. r₁, r₂ എന്നിവ രണ്ട് വൃത്താകൃതിയിലുള്ള അറ്റങ്ങളുടെ ആരങ്ങളാണ്.',
  note_pi: 'സൂചന: ആരം 7-ന്റെ ഗുണിതമാണെങ്കിൽ 22/7 എടുത്താൽ ഉത്തരം വൃത്തിയായി കിട്ടും.',
  u_ha: 'ഹെക്ടർ', u_ml: 'മില്ലിലിറ്റർ', u_litre: 'ലിറ്റർ',
  pr_title: 'പരിശീലനം', pr_which: 'ചോദ്യങ്ങൾ ഏതിൽ', pr_both: 'രണ്ടും', pr_given: 'തന്നിരിക്കുന്നത്', pr_find: 'കണ്ടെത്തുക', pr_in_unit: '(ഉത്തരം {u}-ൽ)',
  pr_answer: 'നിങ്ങളുടെ ഉത്തരം', pr_check: 'പരിശോധിക്കൂ', pr_show: 'നിർദ്ധാരണം കാണിക്കൂ', pr_new: 'പുതിയ ചോദ്യം',
  pr_round: 'π = {pi} എടുക്കുക. ആവശ്യമെങ്കിൽ ഉത്തരം 2 ദശാംശ സ്ഥാനങ്ങൾ വരെ ഏകദേശമാക്കുക.',
  pr_right: 'ശരി! ഉത്തരം {ans}.', pr_wrong: 'ചെറിയ പിഴവ്. ശരിയായ ഉത്തരം {ans}. താഴെയുള്ള നിർദ്ധാരണം വായിക്കൂ.',
  pr_enter: 'ആദ്യം നിങ്ങളുടെ ഉത്തരം സംഖ്യയായി എഴുതൂ.', pr_score: 'സ്കോർ: {n}-ൽ {c}', pr_streak: 'തുടർച്ചയായി ശരി: {n} 🔥',
  ws_title: 'വർക്ക്ഷീറ്റ്: പരപ്പളവും വ്യാപ്തവും', ws_note: 'ഉത്തരസൂചികയോടെ 10 പുതിയ ചോദ്യങ്ങൾ ഉണ്ടാക്കി പ്രിന്റ് ചെയ്യൂ. ഉത്തരങ്ങളിൽ π = {pi}.',
  ws_make: 'വർക്ക്ഷീറ്റ് ഉണ്ടാക്കൂ', ws_print: 'വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യൂ', ws_head: 'പേര്: ____________   ക്ലാസ്: ______   തീയതി: __________',
  ws_line: 'ഉത്തരം: ______________', ws_answers: 'ഉത്തരസൂചിക',
  cv_title: 'ഏകകങ്ങൾ മാറ്റൂ', cv_length: 'നീളം', cv_area: 'പരപ്പളവ്', cv_volume: 'വ്യാപ്തവും ഉൾക്കൊള്ളൽ ശേഷിയും', cv_value: 'വില', cv_from: 'ഏത് ഏകകത്തിൽ നിന്ന്',
  cv_unit_col: 'ഏകകം', cv_value_col: 'വില',
  cv_rule_len: '10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km.',
  cv_rule_area: 'പരപ്പളവിന് നീളത്തിന്റെ നിയമം വർഗമാക്കുക: 1 m = 100 cm, അതിനാൽ 1 m² = 100 × 100 = 10,000 cm². കൂടാതെ 1 ഹെക്ടർ = 10,000 m², 1 km² = 100 ഹെക്ടർ.',
  cv_rule_vol: 'വ്യാപ്തത്തിന് നീളത്തിന്റെ നിയമം ഘനമാക്കുക: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³. കൂടാതെ 1 cm³ = 1 mL, 1000 cm³ = 1 ലിറ്റർ, 1 m³ = 1000 ലിറ്റർ.',
  help_title: 'എങ്ങനെ ഉപയോഗിക്കാം · ക്ലാസ്സിനുള്ള ആശയങ്ങൾ',
  tip1: '2D അല്ലെങ്കിൽ 3D തിരഞ്ഞെടുത്ത്, ഒരു രൂപത്തിൽ തൊട്ട്, അതിന്റെ അളവുകൾ എഴുതൂ. എഴുതുമ്പോൾത്തന്നെ ഉത്തരങ്ങൾ മാറും.',
  tip2: 'π-യെ 22/7, 3.14 എന്നിവയ്ക്കിടയിൽ മാറ്റി താരതമ്യം ചെയ്യൂ. ആരം 7-ന്റെ ഗുണിതമാകുമ്പോൾ പാഠപുസ്തകങ്ങൾ 22/7 എടുക്കുന്നു, കാരണം ഉത്തരം വൃത്തിയായി വരും.',
  tip3: 'നിർദ്ധാരണം പാഠപുസ്തകം പോലെ വായിക്കൂ: സൂത്രവാക്യം എഴുതുക, സംഖ്യകൾ ആദേശം ചെയ്യുക, ലഘൂകരിക്കുക, ഏകകത്തോടെ ഉത്തരം എഴുതുക.',
  tip4: 'ഏകക ബട്ടണുകളും കൺവെർട്ടറും ഉപയോഗിച്ച് 1 m² എന്നാൽ 10,000 cm² ആണ്, 100 cm² അല്ല എന്ന് കാണിക്കൂ.',
  tip5: 'ക്ലാസ് പ്രവർത്തനം: ഓരോ ഗ്രൂപ്പിനും ഒരു യഥാർഥ വസ്തു നൽകൂ (ബക്കറ്റ്, ടിൻ, മധുരപ്പെട്ടി). അവർ അളന്ന്, വ്യാപ്തം ഊഹിച്ച്, പിന്നെ ഇവിടെ പരിശോധിക്കട്ടെ.',
  tip6: 'പരിശീലനത്തിൽ ഓരോ തവണയും പുതിയ ചോദ്യങ്ങൾ വരും. ഗൃഹപാഠത്തിനോ ക്ലാസ് പരീക്ഷയ്ക്കോ ഉത്തരസൂചികയോടെ വർക്ക്ഷീറ്റ് ഉണ്ടാക്കൂ.'
};
window.APP_STRINGS.ur = {
  app_title: 'رقبہ اور حجم لیب',
  intro: 'کوئی شکل چنیں، اس کی پیمائش لکھیں اور اس کا رقبہ، احاطہ، حجم اور سطحی رقبہ دیکھیں — ناپ کے مطابق تصویر اور مرحلہ وار حل کے ساتھ۔',
  tab_calc: 'کیلکولیٹر', tab_practice: 'مشق', tab_units: 'اکائی بدلیں',
  choose_shape: 'شکل چنیں', grp_2d: '2D شکلیں', grp_3d: '3D ٹھوس',
  grp_2d_hint: 'ہموار شکلیں: رقبہ اور احاطہ (جماعت 6–9)', grp_3d_hint: 'ٹھوس اجسام: حجم اور سطحی رقبہ (جماعت 8–10)',
  measurements: 'پیمائش', unit: 'اکائی', pi_value: 'π کی قیمت', sample: 'نمونے کی قیمتیں',
  results: 'جوابات', working: 'مرحلہ وار حل', other_units: 'یہی جواب دوسری اکائیوں میں',
  real_life: 'روزمرہ زندگی میں: {x}', fig_aria: 'نام لکھی تصویر', fig_note: 'تصویر ناپ کے مطابق ہے: کوئی عدد بدلیں تو شکل بھی بدل جاتی ہے۔',
  approx_note: '≈ کا مطلب ہے کہ جواب کو اعشاریہ کے بعد 2 ہندسوں تک گول کیا گیا ہے۔',
  sh_square: 'مربع', sh_rectangle: 'مستطیل', sh_tri_bh: 'مثلث (قاعدہ اور اونچائی)', sh_tri_heron: 'مثلث (3 اضلاع، ہیرون)',
  sh_parallelogram: 'متوازی الاضلاع', sh_rhombus: 'معین', sh_trapezium: 'ذوزنقہ', sh_circle: 'دائرہ', sh_semicircle: 'نیم دائرہ',
  sh_ring: 'چھلا (دائرہ نما راستہ)', sh_cube: 'مکعب', sh_cuboid: 'مستطیلی مکعب', sh_cylinder: 'اسطوانہ', sh_cone: 'مخروط', sh_sphere: 'کرہ',
  sh_hemisphere: 'نصف کرہ', sh_frustum: 'مخروط کا قطعہ',
  ex_square: 'فرش کی ٹائل، شطرنج کی بساط، کیرم بورڈ', ex_rectangle: 'کلاس روم کا فرش، کرکٹ کی پچ، موبائل کی اسکرین',
  ex_tri_bh: 'سڑک کا نشان بورڈ، چھت کا کنارہ، سیٹ اسکوائر', ex_tri_heron: 'ایک تکونا کھیت جس کے تینوں اضلاع ناپے گئے ہوں',
  ex_parallelogram: 'ترچھی پارکنگ کی جگہ، ٹائلوں کا ڈیزائن', ex_rhombus: 'پتنگ، تاش کے پتوں پر اینٹ کا نشان',
  ex_trapezium: 'ہینڈ بیگ کا پہلو، سڑک کے ساتھ والا کھیت', ex_circle: 'روٹی، سکہ، گول پارک',
  ex_semicircle: 'زاویہ پیما، نیم چاند جیسی کھڑکی', ex_ring: 'گول باغ کے گرد راستہ، چوڑی',
  ex_cube: 'پانسہ، روبک کیوب، چینی کا کیوب', ex_cuboid: 'اینٹ، ماچس کی ڈبیا، الماری، پانی کی ٹنکی',
  ex_cylinder: 'گیس سلنڈر، پائپ، ڈبا، پانی کی ٹنکی', ex_cone: 'آئس کریم کون، سالگرہ کی ٹوپی، خیمہ',
  ex_sphere: 'فٹ بال، لڈو، کنچا', ex_hemisphere: 'کٹوری، عمارت کا گنبد',
  ex_frustum: 'بالٹی، اسٹیل کا گلاس، لیمپ شیڈ',
  d_side: 'ضلع (a)', d_edge: 'کنارہ (a)', d_length: 'لمبائی (l)', d_breadth: 'چوڑائی (b)', d_base: 'قاعدہ (b)', d_height: 'اونچائی (h)',
  d_side_a: 'ضلع a', d_side_b: 'ضلع b', d_side_c: 'ضلع c', d_slant_side: 'ترچھا ضلع (a)',
  d_diag1: 'وتر d₁', d_diag2: 'وتر d₂', d_par_a: 'متوازی ضلع a', d_par_b: 'متوازی ضلع b',
  d_radius: 'نصف قطر (r)', d_outer: 'بیرونی نصف قطر (R)', d_inner: 'اندرونی نصف قطر (r)', d_r1: 'اوپر کا نصف قطر (r₁)', d_r2: 'نیچے کا نصف قطر (r₂)',
  r_area: 'رقبہ', r_perimeter: 'احاطہ', r_circumference: 'محیط', r_diameter: 'قطر', r_diagonal: 'وتر',
  r_s: 'نصف احاطہ (s)', r_side: 'ضلع (a)', r_leg: 'ترچھا ضلع (c)', r_width: 'راستے کی چوڑائی',
  r_volume: 'حجم', r_lsa: 'پہلوؤں کا سطحی رقبہ (LSA)', r_csa: 'خمدار سطح کا رقبہ (CSA)', r_tsa: 'کل سطحی رقبہ (TSA)',
  r_sa: 'سطحی رقبہ', r_slant: 'ترچھی اونچائی (l)', r_capacity: 'گنجائش',
  err_positive: 'ہر خانے میں 0 سے بڑا عدد لکھیں۔', err_big: 'براہ کرم {max} تک کے اعداد ہی استعمال کریں۔',
  err_triangle: 'ان اضلاع سے مثلث نہیں بن سکتی۔ کسی بھی دو اضلاع کا مجموعہ تیسرے ضلع سے بڑا ہونا چاہیے۔',
  err_para: 'اونچائی ترچھے ضلع a سے زیادہ نہیں ہو سکتی۔', err_ring: 'بیرونی نصف قطر R، اندرونی نصف قطر r سے بڑا ہونا چاہیے۔',
  note_heron: 'ہیرون کے فارمولے میں صرف تین اضلاع چاہئیں، اونچائی کی ضرورت نہیں۔',
  note_trap: 'یہاں احاطہ مساوی الساقین ذوزنقہ کا ہے (دونوں ترچھے اضلاع برابر)۔',
  note_cyl: 'TSA بند اسطوانے کا ہے۔ کھلے پائپ میں صرف خمدار سطح ہوتی ہے۔',
  note_hemi: 'TSA ٹھوس نصف کرہ کا ہے (خمدار حصہ + ہموار دائرہ)۔ کٹوری کا اندرونی حصہ صرف CSA ہے۔',
  note_frustum: 'جماعت 10: مخروط کا اوپری حصہ کاٹ دیں تو جو بچے وہ قطعہ ہے۔ r₁ اور r₂ دونوں گول سروں کے نصف قطر ہیں۔',
  note_pi: 'مشورہ: جب نصف قطر 7 کا ضعف ہو تو 22/7 لینے سے جواب صاف آتا ہے۔',
  u_ha: 'ہیکٹر', u_ml: 'ملی لیٹر', u_litre: 'لیٹر',
  pr_title: 'مشق', pr_which: 'سوالات کس پر', pr_both: 'دونوں', pr_given: 'دیا گیا', pr_find: 'معلوم کریں', pr_in_unit: '(جواب {u} میں)',
  pr_answer: 'آپ کا جواب', pr_check: 'جانچیں', pr_show: 'حل دکھائیں', pr_new: 'نیا سوال',
  pr_round: 'π = {pi} لیں۔ ضرورت ہو تو جواب کو اعشاریہ کے بعد 2 ہندسوں تک گول کریں۔',
  pr_right: 'درست! جواب {ans} ہے۔', pr_wrong: 'تھوڑی سی چوک ہوئی۔ صحیح جواب {ans} ہے۔ نیچے حل پڑھیں۔',
  pr_enter: 'پہلے اپنا جواب عدد میں لکھیں۔', pr_score: 'اسکور: {n} میں سے {c}', pr_streak: 'لگاتار درست: {n} 🔥',
  ws_title: 'ورک شیٹ: رقبہ اور حجم', ws_note: 'جوابی کلید کے ساتھ 10 نئے سوال بنائیں اور پرنٹ کریں۔ جوابات میں π = {pi} لیا گیا ہے۔',
  ws_make: 'ورک شیٹ بنائیں', ws_print: 'ورک شیٹ پرنٹ کریں', ws_head: 'نام: ____________   جماعت: ______   تاریخ: __________',
  ws_line: 'جواب: ______________', ws_answers: 'جوابی کلید',
  cv_title: 'اکائیاں بدلیں', cv_length: 'لمبائی', cv_area: 'رقبہ', cv_volume: 'حجم اور گنجائش', cv_value: 'قیمت', cv_from: 'کس اکائی سے',
  cv_unit_col: 'اکائی', cv_value_col: 'قیمت',
  cv_rule_len: '10 mm = 1 cm، 100 cm = 1 m، 1000 m = 1 km۔',
  cv_rule_area: 'رقبے کے لیے لمبائی کے اصول کا مربع کریں: 1 m = 100 cm، اس لیے 1 m² = 100 × 100 = 10,000 cm²۔ نیز 1 ہیکٹر = 10,000 m² اور 1 km² = 100 ہیکٹر۔',
  cv_rule_vol: 'حجم کے لیے لمبائی کے اصول کا مکعب کریں: 1 m³ = 100 × 100 × 100 = 10,00,000 cm³۔ نیز 1 cm³ = 1 mL، 1000 cm³ = 1 لیٹر اور 1 m³ = 1000 لیٹر۔',
  help_title: 'استعمال کا طریقہ · کلاس کے لیے خیالات',
  tip1: '2D یا 3D چنیں، کسی شکل پر ٹیپ کریں اور اس کی پیمائش لکھیں۔ لکھتے ہی جوابات بدلتے جاتے ہیں۔',
  tip2: 'π کو 22/7 اور 3.14 کے درمیان بدل کر موازنہ کریں۔ جب نصف قطر 7 کا ضعف ہو تو کتابیں 22/7 لیتی ہیں کیونکہ جواب صاف آتا ہے۔',
  tip3: 'حل کو کتاب کی طرح پڑھیں: فارمولا لکھیں، اعداد رکھیں، مختصر کریں اور جواب اکائی کے ساتھ لکھیں۔',
  tip4: 'اکائی کے بٹنوں اور کنورٹر سے دکھائیں کہ 1 m² میں 10,000 cm² ہوتے ہیں، 100 cm² نہیں۔',
  tip5: 'کلاس کی سرگرمی: ہر گروپ کو ایک اصلی چیز دیں (بالٹی، ڈبا، مٹھائی کا ڈبا)۔ وہ اسے ناپیں، حجم کا اندازہ لگائیں اور پھر یہاں جانچیں۔',
  tip6: 'مشق میں ہر بار نئے سوال آتے ہیں۔ ہوم ورک یا کلاس ٹیسٹ کے لیے جوابی کلید والی ورک شیٹ بنائیں۔'
};
