/* Spelling Bee: one-line meaning of every word, in each UI language.
   APP_CONTENT[lang].m[word] — same 125 keys in all 12 languages. English gives a simple definition
   (never containing the word itself); other languages give the everyday word(s) a child knows. */
window.APP_CONTENT = {
  en: { m: {
    cat: 'a small furry pet that says “meow”', dog: 'a pet animal that barks', sun: 'the bright star that gives us daylight',
    bus: 'a big vehicle that carries many passengers', cup: 'a small container for drinking tea', hen: 'a female bird that lays eggs',
    pen: 'a tool for writing with ink', red: 'the colour of blood and ripe tomatoes', fish: 'an animal that lives and swims in water',
    milk: 'the white drink we get from cows', book: 'pages of words and pictures joined together', tree: 'a tall plant with a trunk and branches',
    ball: 'a round thing used in games', frog: 'a small green animal that hops and croaks', duck: 'a water bird that says “quack”',
    star: 'a tiny bright light in the night sky', rain: 'drops of water falling from clouds', cake: 'a soft sweet food baked for parties',
    kite: 'a paper toy that flies high on a string', boat: 'a small vehicle that floats on water', hand: 'the part of the arm with five fingers',
    nest: 'the home a bird builds', ship: 'a very large vessel that sails on the sea', bell: 'a metal thing that rings',
    jump: 'to push yourself up into the air with your legs',
    apple: 'a round red or green fruit', water: 'the clear liquid we drink', school: 'the place where children learn',
    happy: 'feeling glad and cheerful', mango: 'a sweet, juicy summer fruit', green: 'the colour of leaves and grass',
    house: 'a building where a family lives', chair: 'a seat with a back, for one person', mother: 'your mummy, maa',
    flower: 'the colourful part of a plant', garden: 'a place where plants and flowers grow', orange: 'a round juicy fruit with a thick peel',
    monkey: 'a playful animal that climbs trees', pencil: 'a writing tool whose marks can be rubbed out', window: 'an opening in a wall that lets in light and air',
    yellow: 'the colour of a ripe banana', rabbit: 'a small animal with long ears', little: 'small in size',
    friend: 'someone you like and play with', bread: 'a baked food made from flour, like pav', clock: 'a machine that shows the time',
    sweet: 'tasting like sugar', river: 'a long stream of water flowing to the sea', colour: 'red, blue and green are examples of this',
    plant: 'a living thing that grows in soil',
    beautiful: 'very pretty, lovely to look at', because: 'for the reason that', elephant: 'the biggest land animal, with a trunk',
    holiday: 'a day with no school or work', tomorrow: 'the day after today', village: 'a small place in the countryside',
    picture: 'a drawing, painting or photo', kitchen: 'the room where food is cooked', festival: 'a special day of celebration',
    umbrella: 'it keeps you dry in the rain', birthday: 'the day you were born, every year', morning: 'the early part of the day',
    family: 'parents, children and relatives', weather: 'how hot, cold, rainy or windy it is', doctor: 'a person who treats sick people',
    people: 'men, women and children', answer: 'a reply to a question', question: 'something you ask to find out',
    hospital: 'a place where sick people are treated', island: 'land with water all around it', breakfast: 'the first meal of the day',
    library: 'a room full of books to read or borrow', country: 'a nation, like India', children: 'young boys and girls',
    butterfly: 'an insect with colourful wings',
    knowledge: 'what you know and have learned', science: 'the study of nature and how things work', neighbour: 'a person who lives next door',
    believe: 'to feel sure that something is true', receive: 'to get something that is given or sent', journey: 'travelling from one place to another',
    language: 'the words we use to speak and write', vegetable: 'a plant part we cook and eat, like potato', calendar: 'a chart of the days, weeks and months',
    dangerous: 'likely to cause harm', delicious: 'very tasty', exercise: 'moving the body to stay fit',
    honest: 'always telling the truth', invitation: 'a request to come to an event', temperature: 'how hot or cold something is',
    surprise: 'something you did not expect', thought: 'an idea in your mind', through: 'in at one side and out at the other',
    tongue: 'the part of the mouth we taste with', scissors: 'a cutting tool with two blades', guard: 'a person who keeps a place safe',
    address: 'house number, street and city where you live', sentence: 'a group of words that makes complete sense', government: 'the people who run a country or state',
    adventure: 'an exciting and slightly risky experience',
    accommodate: 'to have enough room for', necessary: 'needed; it must be done', occasion: 'a special event or time',
    embarrass: 'to make someone feel shy and awkward', conscience: 'the inner voice that tells right from wrong', conscious: 'awake and aware',
    definitely: 'surely, without any doubt', environment: 'the air, water, land and living things around us', independence: 'freedom from the rule of others',
    maintenance: 'keeping something in good working order', mischievous: 'naughty in a playful way', pronunciation: 'the way a word is spoken',
    recommend: 'to suggest something as good', rhythm: 'a regular beat in music or dance', privilege: 'a special right or honour',
    restaurant: 'a place where you pay to eat meals', guarantee: 'a firm promise, often to repair or replace', committee: 'a group chosen to plan or decide something',
    parliament: 'the body that makes a country’s laws', achievement: 'something good done with effort', separate: 'apart; not together',
    beginning: 'the start of something', exaggerate: 'to make something sound bigger than it is', hygiene: 'keeping yourself and your surroundings clean',
    occurrence: 'something that happens; an event'
  } },
  hi: { m: {
    cat: 'बिल्ली', dog: 'कुत्ता', sun: 'सूरज', bus: 'बस (सवारी गाड़ी)', cup: 'कप, प्याला', hen: 'मुर्गी', pen: 'पेन, कलम', red: 'लाल रंग',
    fish: 'मछली', milk: 'दूध', book: 'किताब', tree: 'पेड़', ball: 'गेंद', frog: 'मेंढक', duck: 'बत्तख', star: 'तारा', rain: 'बारिश',
    cake: 'केक', kite: 'पतंग', boat: 'नाव', hand: 'हाथ', nest: 'घोंसला', ship: 'पानी का जहाज़', bell: 'घंटी', jump: 'कूदना',
    apple: 'सेब', water: 'पानी', school: 'स्कूल, विद्यालय', happy: 'खुश', mango: 'आम', green: 'हरा रंग', house: 'घर', chair: 'कुर्सी',
    mother: 'माँ', flower: 'फूल', garden: 'बगीचा', orange: 'संतरा', monkey: 'बंदर', pencil: 'पेंसिल', window: 'खिड़की', yellow: 'पीला रंग',
    rabbit: 'खरगोश', little: 'छोटा', friend: 'दोस्त, मित्र', bread: 'डबल रोटी, ब्रेड', clock: 'घड़ी', sweet: 'मीठा', river: 'नदी', colour: 'रंग',
    plant: 'पौधा',
    beautiful: 'सुंदर', because: 'क्योंकि', elephant: 'हाथी', holiday: 'छुट्टी', tomorrow: 'आने वाला कल', village: 'गाँव', picture: 'चित्र, तस्वीर',
    kitchen: 'रसोई', festival: 'त्योहार', umbrella: 'छाता', birthday: 'जन्मदिन', morning: 'सुबह', family: 'परिवार', weather: 'मौसम',
    doctor: 'डॉक्टर, चिकित्सक', people: 'लोग', answer: 'उत्तर, जवाब', question: 'प्रश्न, सवाल', hospital: 'अस्पताल', island: 'द्वीप, टापू',
    breakfast: 'सुबह का नाश्ता', library: 'पुस्तकालय', country: 'देश', children: 'बच्चे', butterfly: 'तितली',
    knowledge: 'ज्ञान', science: 'विज्ञान', neighbour: 'पड़ोसी', believe: 'विश्वास करना, मानना', receive: 'प्राप्त करना, पाना', journey: 'यात्रा, सफ़र',
    language: 'भाषा', vegetable: 'सब्ज़ी', calendar: 'कैलेंडर (तारीख़ों की सूची)', dangerous: 'ख़तरनाक', delicious: 'स्वादिष्ट', exercise: 'व्यायाम, कसरत',
    honest: 'ईमानदार', invitation: 'निमंत्रण, न्योता', temperature: 'तापमान', surprise: 'अचानक मिली ख़ुशी, आश्चर्य', thought: 'विचार, सोच',
    through: 'के बीच से होकर, आर-पार', tongue: 'जीभ', scissors: 'कैंची', guard: 'पहरेदार, चौकीदार', address: 'पता (घर का)', sentence: 'वाक्य',
    government: 'सरकार', adventure: 'रोमांचक अनुभव, साहसिक काम',
    accommodate: 'जगह देना, समा लेना', necessary: 'ज़रूरी, आवश्यक', occasion: 'मौक़ा, अवसर', embarrass: 'शर्मिंदा करना',
    conscience: 'अंतरात्मा, सही-ग़लत बताने वाली भीतरी आवाज़', conscious: 'होश में, सचेत', definitely: 'ज़रूर, निश्चित रूप से',
    environment: 'पर्यावरण', independence: 'स्वतंत्रता, आज़ादी', maintenance: 'रखरखाव, देखभाल', mischievous: 'शरारती', pronunciation: 'उच्चारण',
    recommend: 'सिफ़ारिश करना, सुझाव देना', rhythm: 'लय, ताल', privilege: 'विशेष अधिकार, सम्मान की बात', restaurant: 'रेस्टोरेंट, भोजनालय',
    guarantee: 'गारंटी, पक्का वादा', committee: 'समिति', parliament: 'संसद', achievement: 'उपलब्धि', separate: 'अलग', beginning: 'शुरुआत',
    exaggerate: 'बढ़ा-चढ़ाकर बताना', hygiene: 'साफ़-सफ़ाई, स्वच्छता', occurrence: 'घटना'
  } },
  bn: { m: {
    cat: 'বিড়াল', dog: 'কুকুর', sun: 'সূর্য', bus: 'বাস (যাত্রী গাড়ি)', cup: 'কাপ, পেয়ালা', hen: 'মুরগি', pen: 'কলম', red: 'লাল রং',
    fish: 'মাছ', milk: 'দুধ', book: 'বই', tree: 'গাছ', ball: 'বল', frog: 'ব্যাঙ', duck: 'হাঁস', star: 'তারা', rain: 'বৃষ্টি',
    cake: 'কেক', kite: 'ঘুড়ি', boat: 'নৌকা', hand: 'হাত', nest: 'পাখির বাসা', ship: 'জাহাজ', bell: 'ঘণ্টা', jump: 'লাফানো',
    apple: 'আপেল', water: 'জল', school: 'স্কুল, বিদ্যালয়', happy: 'খুশি', mango: 'আম', green: 'সবুজ রং', house: 'বাড়ি', chair: 'চেয়ার',
    mother: 'মা', flower: 'ফুল', garden: 'বাগান', orange: 'কমলালেবু', monkey: 'বাঁদর', pencil: 'পেনসিল', window: 'জানালা', yellow: 'হলুদ রং',
    rabbit: 'খরগোশ', little: 'ছোট', friend: 'বন্ধু', bread: 'পাউরুটি', clock: 'ঘড়ি', sweet: 'মিষ্টি', river: 'নদী', colour: 'রং',
    plant: 'চারাগাছ',
    beautiful: 'সুন্দর', because: 'কারণ, যেহেতু', elephant: 'হাতি', holiday: 'ছুটির দিন', tomorrow: 'আগামীকাল', village: 'গ্রাম', picture: 'ছবি',
    kitchen: 'রান্নাঘর', festival: 'উৎসব', umbrella: 'ছাতা', birthday: 'জন্মদিন', morning: 'সকাল', family: 'পরিবার', weather: 'আবহাওয়া',
    doctor: 'ডাক্তার', people: 'লোকজন, মানুষ', answer: 'উত্তর', question: 'প্রশ্ন', hospital: 'হাসপাতাল', island: 'দ্বীপ',
    breakfast: 'সকালের জলখাবার', library: 'গ্রন্থাগার, লাইব্রেরি', country: 'দেশ', children: 'ছোটরা, শিশুরা', butterfly: 'প্রজাপতি',
    knowledge: 'জ্ঞান', science: 'বিজ্ঞান', neighbour: 'প্রতিবেশী', believe: 'বিশ্বাস করা', receive: 'পাওয়া, গ্রহণ করা', journey: 'যাত্রা, ভ্রমণ',
    language: 'ভাষা', vegetable: 'সবজি', calendar: 'ক্যালেন্ডার (দিন-তারিখের তালিকা)', dangerous: 'বিপজ্জনক', delicious: 'সুস্বাদু', exercise: 'ব্যায়াম',
    honest: 'সৎ', invitation: 'নিমন্ত্রণ', temperature: 'তাপমাত্রা', surprise: 'অবাক করা ব্যাপার, চমক', thought: 'চিন্তা, ভাবনা',
    through: 'এক পাশ দিয়ে ঢুকে অন্য পাশ দিয়ে', tongue: 'জিভ', scissors: 'কাঁচি', guard: 'পাহারাদার', address: 'ঠিকানা', sentence: 'বাক্য',
    government: 'সরকার', adventure: 'রোমাঞ্চকর অভিযান',
    accommodate: 'জায়গা দেওয়া, ধরানো', necessary: 'দরকারি, প্রয়োজনীয়', occasion: 'উপলক্ষ, অনুষ্ঠান', embarrass: 'লজ্জায় ফেলা',
    conscience: 'বিবেক', conscious: 'জ্ঞান আছে এমন, সচেতন', definitely: 'নিশ্চয়ই',
    environment: 'পরিবেশ', independence: 'স্বাধীনতা', maintenance: 'রক্ষণাবেক্ষণ', mischievous: 'দুষ্টু', pronunciation: 'উচ্চারণ',
    recommend: 'সুপারিশ করা', rhythm: 'ছন্দ, তাল', privilege: 'বিশেষ সুবিধা, সৌভাগ্য', restaurant: 'রেস্তোরাঁ',
    guarantee: 'গ্যারান্টি, পাকা কথা', committee: 'কমিটি, সমিতি', parliament: 'সংসদ', achievement: 'সাফল্য, কৃতিত্ব', separate: 'আলাদা', beginning: 'শুরু',
    exaggerate: 'বাড়িয়ে বলা', hygiene: 'পরিচ্ছন্নতা', occurrence: 'ঘটনা'
  } },
  mr: { m: {
    cat: 'मांजर', dog: 'कुत्रा', sun: 'सूर्य', bus: 'बस (प्रवासी गाडी)', cup: 'कप, पेला', hen: 'कोंबडी', pen: 'पेन, लेखणी', red: 'लाल रंग',
    fish: 'मासा', milk: 'दूध', book: 'पुस्तक', tree: 'झाड', ball: 'चेंडू', frog: 'बेडूक', duck: 'बदक', star: 'तारा', rain: 'पाऊस',
    cake: 'केक', kite: 'पतंग', boat: 'होडी', hand: 'हात', nest: 'घरटे', ship: 'जहाज', bell: 'घंटा', jump: 'उडी मारणे',
    apple: 'सफरचंद', water: 'पाणी', school: 'शाळा', happy: 'आनंदी', mango: 'आंबा', green: 'हिरवा रंग', house: 'घर', chair: 'खुर्ची',
    mother: 'आई', flower: 'फूल', garden: 'बाग', orange: 'संत्रे', monkey: 'माकड', pencil: 'पेन्सिल', window: 'खिडकी', yellow: 'पिवळा रंग',
    rabbit: 'ससा', little: 'लहान', friend: 'मित्र, मैत्रीण', bread: 'पाव, ब्रेड', clock: 'घड्याळ', sweet: 'गोड', river: 'नदी', colour: 'रंग',
    plant: 'रोप',
    beautiful: 'सुंदर', because: 'कारण', elephant: 'हत्ती', holiday: 'सुट्टी', tomorrow: 'उद्या', village: 'गाव', picture: 'चित्र',
    kitchen: 'स्वयंपाकघर', festival: 'सण', umbrella: 'छत्री', birthday: 'वाढदिवस', morning: 'सकाळ', family: 'कुटुंब', weather: 'हवामान',
    doctor: 'डॉक्टर', people: 'लोक', answer: 'उत्तर', question: 'प्रश्न', hospital: 'रुग्णालय, दवाखाना', island: 'बेट',
    breakfast: 'सकाळची न्याहारी', library: 'ग्रंथालय', country: 'देश', children: 'मुले', butterfly: 'फुलपाखरू',
    knowledge: 'ज्ञान', science: 'विज्ञान', neighbour: 'शेजारी', believe: 'विश्वास ठेवणे', receive: 'मिळणे, स्वीकारणे', journey: 'प्रवास',
    language: 'भाषा', vegetable: 'भाजी', calendar: 'दिनदर्शिका', dangerous: 'धोकादायक', delicious: 'चविष्ट', exercise: 'व्यायाम',
    honest: 'प्रामाणिक', invitation: 'आमंत्रण', temperature: 'तापमान', surprise: 'आश्चर्याचा धक्का, सरप्राइज', thought: 'विचार',
    through: 'आरपार, मधून', tongue: 'जीभ', scissors: 'कात्री', guard: 'पहारेकरी', address: 'पत्ता', sentence: 'वाक्य',
    government: 'सरकार', adventure: 'साहस, रोमांचक अनुभव',
    accommodate: 'सामावून घेणे', necessary: 'आवश्यक, गरजेचे', occasion: 'प्रसंग', embarrass: 'लाजवणे, ओशाळवाणे करणे',
    conscience: 'सद्सद्विवेकबुद्धी, मनाचा आवाज', conscious: 'शुद्धीवर, जागरूक', definitely: 'नक्की',
    environment: 'पर्यावरण', independence: 'स्वातंत्र्य', maintenance: 'देखभाल', mischievous: 'खोडकर', pronunciation: 'उच्चार',
    recommend: 'शिफारस करणे', rhythm: 'लय, ताल', privilege: 'विशेष हक्क, भाग्याची गोष्ट', restaurant: 'उपाहारगृह, हॉटेल',
    guarantee: 'हमी', committee: 'समिती', parliament: 'संसद', achievement: 'यश, कामगिरी', separate: 'वेगळे', beginning: 'सुरुवात',
    exaggerate: 'अतिशयोक्ती करणे', hygiene: 'स्वच्छता', occurrence: 'घटना'
  } },
  gu: { m: {
    cat: 'બિલાડી', dog: 'કૂતરો', sun: 'સૂરજ', bus: 'બસ (મુસાફરોની ગાડી)', cup: 'કપ, પ્યાલો', hen: 'મરઘી', pen: 'પેન, કલમ', red: 'લાલ રંગ',
    fish: 'માછલી', milk: 'દૂધ', book: 'ચોપડી, પુસ્તક', tree: 'ઝાડ', ball: 'દડો', frog: 'દેડકો', duck: 'બતક', star: 'તારો', rain: 'વરસાદ',
    cake: 'કેક', kite: 'પતંગ', boat: 'હોડી', hand: 'હાથ', nest: 'માળો', ship: 'વહાણ', bell: 'ઘંટ', jump: 'કૂદવું',
    apple: 'સફરજન', water: 'પાણી', school: 'શાળા', happy: 'ખુશ', mango: 'કેરી', green: 'લીલો રંગ', house: 'ઘર', chair: 'ખુરશી',
    mother: 'મા', flower: 'ફૂલ', garden: 'બગીચો', orange: 'સંતરું, નારંગી', monkey: 'વાંદરો', pencil: 'પેન્સિલ', window: 'બારી', yellow: 'પીળો રંગ',
    rabbit: 'સસલું', little: 'નાનું', friend: 'મિત્ર, ભાઈબંધ', bread: 'બ્રેડ, પાંઉ', clock: 'ઘડિયાળ', sweet: 'મીઠું', river: 'નદી', colour: 'રંગ',
    plant: 'છોડ',
    beautiful: 'સુંદર', because: 'કારણ કે', elephant: 'હાથી', holiday: 'રજા', tomorrow: 'આવતીકાલ', village: 'ગામ', picture: 'ચિત્ર',
    kitchen: 'રસોડું', festival: 'તહેવાર', umbrella: 'છત્રી', birthday: 'જન્મદિવસ', morning: 'સવાર', family: 'કુટુંબ, પરિવાર', weather: 'હવામાન',
    doctor: 'ડૉક્ટર', people: 'લોકો', answer: 'જવાબ', question: 'પ્રશ્ન', hospital: 'હૉસ્પિટલ, દવાખાનું', island: 'ટાપુ',
    breakfast: 'સવારનો નાસ્તો', library: 'પુસ્તકાલય', country: 'દેશ', children: 'બાળકો', butterfly: 'પતંગિયું',
    knowledge: 'જ્ઞાન', science: 'વિજ્ઞાન', neighbour: 'પાડોશી', believe: 'વિશ્વાસ કરવો, માનવું', receive: 'મેળવવું', journey: 'મુસાફરી, યાત્રા',
    language: 'ભાષા', vegetable: 'શાકભાજી', calendar: 'કૅલેન્ડર (તારીખિયું)', dangerous: 'ખતરનાક, જોખમી', delicious: 'સ્વાદિષ્ટ', exercise: 'કસરત',
    honest: 'પ્રામાણિક', invitation: 'આમંત્રણ', temperature: 'તાપમાન', surprise: 'અચાનક મળતો આનંદ, આશ્ચર્ય', thought: 'વિચાર',
    through: 'આરપાર, વચ્ચેથી', tongue: 'જીભ', scissors: 'કાતર', guard: 'ચોકીદાર', address: 'સરનામું', sentence: 'વાક્ય',
    government: 'સરકાર', adventure: 'સાહસ, રોમાંચક અનુભવ',
    accommodate: 'સમાવવું, જગ્યા આપવી', necessary: 'જરૂરી', occasion: 'પ્રસંગ, અવસર', embarrass: 'શરમમાં મૂકવું',
    conscience: 'અંતરાત્મા, સાચું-ખોટું કહેતો અંદરનો અવાજ', conscious: 'ભાનમાં, સભાન', definitely: 'ચોક્કસ',
    environment: 'પર્યાવરણ', independence: 'સ્વતંત્રતા, આઝાદી', maintenance: 'જાળવણી', mischievous: 'તોફાની', pronunciation: 'ઉચ્ચાર',
    recommend: 'ભલામણ કરવી', rhythm: 'લય, તાલ', privilege: 'ખાસ હક, ગૌરવની વાત', restaurant: 'રેસ્ટોરન્ટ, ભોજનાલય',
    guarantee: 'ગૅરંટી, ખાતરી', committee: 'સમિતિ', parliament: 'સંસદ', achievement: 'સિદ્ધિ', separate: 'અલગ', beginning: 'શરૂઆત',
    exaggerate: 'વધારીને કહેવું, અતિશયોક્તિ કરવી', hygiene: 'સ્વચ્છતા', occurrence: 'ઘટના'
  } },
  pa: { m: {
    cat: 'ਬਿੱਲੀ', dog: 'ਕੁੱਤਾ', sun: 'ਸੂਰਜ', bus: 'ਬੱਸ (ਸਵਾਰੀ ਗੱਡੀ)', cup: 'ਕੱਪ, ਪਿਆਲਾ', hen: 'ਮੁਰਗੀ', pen: 'ਪੈੱਨ, ਕਲਮ', red: 'ਲਾਲ ਰੰਗ',
    fish: 'ਮੱਛੀ', milk: 'ਦੁੱਧ', book: 'ਕਿਤਾਬ', tree: 'ਰੁੱਖ', ball: 'ਗੇਂਦ', frog: 'ਡੱਡੂ', duck: 'ਬੱਤਖ', star: 'ਤਾਰਾ', rain: 'ਮੀਂਹ',
    cake: 'ਕੇਕ', kite: 'ਪਤੰਗ', boat: 'ਕਿਸ਼ਤੀ', hand: 'ਹੱਥ', nest: 'ਆਲ੍ਹਣਾ', ship: 'ਸਮੁੰਦਰੀ ਜਹਾਜ਼', bell: 'ਘੰਟੀ', jump: 'ਛਾਲ ਮਾਰਨਾ',
    apple: 'ਸੇਬ', water: 'ਪਾਣੀ', school: 'ਸਕੂਲ', happy: 'ਖ਼ੁਸ਼', mango: 'ਅੰਬ', green: 'ਹਰਾ ਰੰਗ', house: 'ਘਰ', chair: 'ਕੁਰਸੀ',
    mother: 'ਮਾਂ', flower: 'ਫੁੱਲ', garden: 'ਬਗੀਚਾ', orange: 'ਸੰਤਰਾ', monkey: 'ਬਾਂਦਰ', pencil: 'ਪੈਨਸਿਲ', window: 'ਖਿੜਕੀ', yellow: 'ਪੀਲਾ ਰੰਗ',
    rabbit: 'ਖ਼ਰਗੋਸ਼', little: 'ਛੋਟਾ', friend: 'ਦੋਸਤ, ਮਿੱਤਰ', bread: 'ਡਬਲ ਰੋਟੀ', clock: 'ਘੜੀ', sweet: 'ਮਿੱਠਾ', river: 'ਨਦੀ, ਦਰਿਆ', colour: 'ਰੰਗ',
    plant: 'ਪੌਦਾ',
    beautiful: 'ਸੋਹਣਾ, ਸੁੰਦਰ', because: 'ਕਿਉਂਕਿ', elephant: 'ਹਾਥੀ', holiday: 'ਛੁੱਟੀ', tomorrow: 'ਆਉਣ ਵਾਲਾ ਕੱਲ੍ਹ', village: 'ਪਿੰਡ', picture: 'ਤਸਵੀਰ',
    kitchen: 'ਰਸੋਈ', festival: 'ਤਿਉਹਾਰ', umbrella: 'ਛਤਰੀ', birthday: 'ਜਨਮਦਿਨ', morning: 'ਸਵੇਰ', family: 'ਪਰਿਵਾਰ', weather: 'ਮੌਸਮ',
    doctor: 'ਡਾਕਟਰ', people: 'ਲੋਕ', answer: 'ਜਵਾਬ, ਉੱਤਰ', question: 'ਸਵਾਲ, ਪ੍ਰਸ਼ਨ', hospital: 'ਹਸਪਤਾਲ', island: 'ਟਾਪੂ',
    breakfast: 'ਸਵੇਰ ਦਾ ਨਾਸ਼ਤਾ', library: 'ਲਾਇਬ੍ਰੇਰੀ, ਪੁਸਤਕਾਲਾ', country: 'ਦੇਸ਼', children: 'ਬੱਚੇ', butterfly: 'ਤਿਤਲੀ',
    knowledge: 'ਗਿਆਨ', science: 'ਵਿਗਿਆਨ', neighbour: 'ਗੁਆਂਢੀ', believe: 'ਵਿਸ਼ਵਾਸ ਕਰਨਾ, ਮੰਨਣਾ', receive: 'ਪ੍ਰਾਪਤ ਕਰਨਾ, ਮਿਲਣਾ', journey: 'ਸਫ਼ਰ, ਯਾਤਰਾ',
    language: 'ਭਾਸ਼ਾ, ਬੋਲੀ', vegetable: 'ਸਬਜ਼ੀ', calendar: 'ਕੈਲੰਡਰ (ਤਰੀਕਾਂ ਵਾਲਾ)', dangerous: 'ਖ਼ਤਰਨਾਕ', delicious: 'ਸੁਆਦੀ', exercise: 'ਕਸਰਤ',
    honest: 'ਇਮਾਨਦਾਰ', invitation: 'ਸੱਦਾ', temperature: 'ਤਾਪਮਾਨ', surprise: 'ਅਚਾਨਕ ਖ਼ੁਸ਼ੀ, ਹੈਰਾਨੀ', thought: 'ਵਿਚਾਰ, ਖ਼ਿਆਲ',
    through: 'ਆਰ-ਪਾਰ, ਵਿੱਚੋਂ ਦੀ', tongue: 'ਜੀਭ', scissors: 'ਕੈਂਚੀ', guard: 'ਪਹਿਰੇਦਾਰ', address: 'ਪਤਾ (ਘਰ ਦਾ)', sentence: 'ਵਾਕ',
    government: 'ਸਰਕਾਰ', adventure: 'ਰੋਮਾਂਚਕ ਤਜਰਬਾ, ਸਾਹਸ',
    accommodate: 'ਥਾਂ ਦੇਣਾ, ਸਮਾ ਲੈਣਾ', necessary: 'ਜ਼ਰੂਰੀ', occasion: 'ਮੌਕਾ', embarrass: 'ਸ਼ਰਮਿੰਦਾ ਕਰਨਾ',
    conscience: 'ਜ਼ਮੀਰ, ਅੰਦਰ ਦੀ ਆਵਾਜ਼', conscious: 'ਹੋਸ਼ ਵਿੱਚ, ਸੁਚੇਤ', definitely: 'ਜ਼ਰੂਰ, ਪੱਕਾ',
    environment: 'ਵਾਤਾਵਰਨ', independence: 'ਆਜ਼ਾਦੀ', maintenance: 'ਸਾਂਭ-ਸੰਭਾਲ', mischievous: 'ਸ਼ਰਾਰਤੀ', pronunciation: 'ਉਚਾਰਨ',
    recommend: 'ਸਿਫ਼ਾਰਸ਼ ਕਰਨਾ', rhythm: 'ਤਾਲ, ਲੈਅ', privilege: 'ਖ਼ਾਸ ਹੱਕ, ਮਾਣ ਦੀ ਗੱਲ', restaurant: 'ਰੈਸਟੋਰੈਂਟ, ਢਾਬਾ',
    guarantee: 'ਗਰੰਟੀ, ਪੱਕਾ ਵਾਅਦਾ', committee: 'ਕਮੇਟੀ', parliament: 'ਸੰਸਦ', achievement: 'ਪ੍ਰਾਪਤੀ', separate: 'ਵੱਖਰਾ', beginning: 'ਸ਼ੁਰੂਆਤ',
    exaggerate: 'ਵਧਾ-ਚੜ੍ਹਾ ਕੇ ਦੱਸਣਾ', hygiene: 'ਸਾਫ਼-ਸਫ਼ਾਈ', occurrence: 'ਘਟਨਾ'
  } },
  or: { m: {
    cat: 'ବିରାଡ଼ି', dog: 'କୁକୁର', sun: 'ସୂର୍ଯ୍ୟ', bus: 'ବସ୍ (ଯାତ୍ରୀ ଗାଡ଼ି)', cup: 'କପ୍, ପିଆଲା', hen: 'ମାଈ କୁକୁଡ଼ା', pen: 'କଲମ', red: 'ନାଲି ରଙ୍ଗ',
    fish: 'ମାଛ', milk: 'କ୍ଷୀର', book: 'ବହି', tree: 'ଗଛ', ball: 'ବଲ୍', frog: 'ବେଙ୍ଗ', duck: 'ବତକ', star: 'ତାରା', rain: 'ବର୍ଷା',
    cake: 'କେକ୍', kite: 'ଗୁଡ଼ି', boat: 'ଡଙ୍ଗା', hand: 'ହାତ', nest: 'ଚଢ଼େଇ ବସା', ship: 'ଜାହାଜ', bell: 'ଘଣ୍ଟି', jump: 'ଡେଇଁବା',
    apple: 'ସେଓ', water: 'ପାଣି', school: 'ବିଦ୍ୟାଳୟ, ସ୍କୁଲ୍', happy: 'ଖୁସି', mango: 'ଆମ୍ବ', green: 'ସବୁଜ ରଙ୍ଗ', house: 'ଘର', chair: 'ଚୌକି',
    mother: 'ମା', flower: 'ଫୁଲ', garden: 'ବଗିଚା', orange: 'କମଳା', monkey: 'ମାଙ୍କଡ଼', pencil: 'ପେନସିଲ୍', window: 'ଝରକା', yellow: 'ହଳଦିଆ ରଙ୍ଗ',
    rabbit: 'ଠେକୁଆ', little: 'ଛୋଟ', friend: 'ସାଙ୍ଗ, ବନ୍ଧୁ', bread: 'ପାଉଁରୁଟି', clock: 'ଘଣ୍ଟା, ଘଡ଼ି', sweet: 'ମିଠା', river: 'ନଦୀ', colour: 'ରଙ୍ଗ',
    plant: 'ଚାରା ଗଛ',
    beautiful: 'ସୁନ୍ଦର', because: 'କାରଣ, ଯେହେତୁ', elephant: 'ହାତୀ', holiday: 'ଛୁଟି ଦିନ', tomorrow: 'ଆସନ୍ତାକାଲି', village: 'ଗାଁ', picture: 'ଛବି',
    kitchen: 'ରୋଷେଇ ଘର', festival: 'ପର୍ବ', umbrella: 'ଛତା', birthday: 'ଜନ୍ମଦିନ', morning: 'ସକାଳ', family: 'ପରିବାର', weather: 'ପାଣିପାଗ',
    doctor: 'ଡାକ୍ତର', people: 'ଲୋକମାନେ', answer: 'ଉତ୍ତର', question: 'ପ୍ରଶ୍ନ', hospital: 'ଡାକ୍ତରଖାନା', island: 'ଦ୍ୱୀପ',
    breakfast: 'ସକାଳର ଜଳଖିଆ', library: 'ପାଠାଗାର', country: 'ଦେଶ', children: 'ପିଲାମାନେ', butterfly: 'ପ୍ରଜାପତି',
    knowledge: 'ଜ୍ଞାନ', science: 'ବିଜ୍ଞାନ', neighbour: 'ପଡ଼ୋଶୀ', believe: 'ବିଶ୍ୱାସ କରିବା', receive: 'ପାଇବା, ଗ୍ରହଣ କରିବା', journey: 'ଯାତ୍ରା',
    language: 'ଭାଷା', vegetable: 'ପରିବା', calendar: 'କ୍ୟାଲେଣ୍ଡର (ତାରିଖ ତାଲିକା)', dangerous: 'ବିପଜ୍ଜନକ', delicious: 'ସୁସ୍ୱାଦୁ', exercise: 'ବ୍ୟାୟାମ',
    honest: 'ସଚ୍ଚୋଟ', invitation: 'ନିମନ୍ତ୍ରଣ', temperature: 'ତାପମାତ୍ରା', surprise: 'ହଠାତ୍ ଖୁସି, ଆଶ୍ଚର୍ଯ୍ୟ', thought: 'ଚିନ୍ତା, ଭାବନା',
    through: 'ଭିତର ଦେଇ, ଆରପାର', tongue: 'ଜିଭ', scissors: 'କଇଁଚି', guard: 'ପ୍ରହରୀ, ଜଗୁଆଳି', address: 'ଠିକଣା', sentence: 'ବାକ୍ୟ',
    government: 'ସରକାର', adventure: 'ରୋମାଞ୍ଚକର ଅଭିଯାନ',
    accommodate: 'ସ୍ଥାନ ଦେବା', necessary: 'ଆବଶ୍ୟକ, ଦରକାରୀ', occasion: 'ଅବସର, ଉତ୍ସବ', embarrass: 'ଲଜ୍ଜିତ କରିବା',
    conscience: 'ବିବେକ', conscious: 'ଚେତନା ଥିବା, ସଚେତନ', definitely: 'ନିଶ୍ଚିତ ଭାବେ',
    environment: 'ପରିବେଶ', independence: 'ସ୍ୱାଧୀନତା', maintenance: 'ରକ୍ଷଣାବେକ୍ଷଣ', mischievous: 'ଦୁଷ୍ଟ, ଚଗଲା', pronunciation: 'ଉଚ୍ଚାରଣ',
    recommend: 'ସୁପାରିଶ କରିବା', rhythm: 'ତାଳ, ଲୟ', privilege: 'ବିଶେଷ ଅଧିକାର, ସୌଭାଗ୍ୟ', restaurant: 'ରେଷ୍ଟୁରାଣ୍ଟ, ହୋଟେଲ୍',
    guarantee: 'ଗ୍ୟାରେଣ୍ଟି, ପକ୍କା ପ୍ରତିଶ୍ରୁତି', committee: 'କମିଟି', parliament: 'ସଂସଦ', achievement: 'ସଫଳତା, କୃତିତ୍ୱ', separate: 'ଅଲଗା', beginning: 'ଆରମ୍ଭ',
    exaggerate: 'ବଢ଼ାଇ ଚଢ଼ାଇ କହିବା', hygiene: 'ପରିଷ୍କାର ପରିଚ୍ଛନ୍ନତା', occurrence: 'ଘଟଣା'
  } },
  ta: { m: {
    cat: 'பூனை', dog: 'நாய்', sun: 'சூரியன்', bus: 'பேருந்து', cup: 'கோப்பை', hen: 'கோழி', pen: 'பேனா', red: 'சிவப்பு நிறம்',
    fish: 'மீன்', milk: 'பால்', book: 'புத்தகம்', tree: 'மரம்', ball: 'பந்து', frog: 'தவளை', duck: 'வாத்து', star: 'நட்சத்திரம்', rain: 'மழை',
    cake: 'கேக்', kite: 'பட்டம்', boat: 'படகு', hand: 'கை', nest: 'பறவைக் கூடு', ship: 'கப்பல்', bell: 'மணி', jump: 'குதித்தல்',
    apple: 'ஆப்பிள் பழம்', water: 'தண்ணீர்', school: 'பள்ளி', happy: 'மகிழ்ச்சியான', mango: 'மாம்பழம்', green: 'பச்சை நிறம்', house: 'வீடு', chair: 'நாற்காலி',
    mother: 'அம்மா', flower: 'பூ', garden: 'தோட்டம்', orange: 'ஆரஞ்சுப் பழம்', monkey: 'குரங்கு', pencil: 'பென்சில்', window: 'ஜன்னல்', yellow: 'மஞ்சள் நிறம்',
    rabbit: 'முயல்', little: 'சிறிய', friend: 'நண்பன், தோழி', bread: 'ரொட்டி', clock: 'கடிகாரம்', sweet: 'இனிப்பு', river: 'ஆறு, நதி', colour: 'நிறம்',
    plant: 'செடி',
    beautiful: 'அழகான', because: 'ஏனென்றால்', elephant: 'யானை', holiday: 'விடுமுறை', tomorrow: 'நாளை', village: 'கிராமம்', picture: 'படம்',
    kitchen: 'சமையலறை', festival: 'திருவிழா, பண்டிகை', umbrella: 'குடை', birthday: 'பிறந்தநாள்', morning: 'காலை', family: 'குடும்பம்', weather: 'வானிலை',
    doctor: 'மருத்துவர்', people: 'மக்கள்', answer: 'விடை, பதில்', question: 'கேள்வி', hospital: 'மருத்துவமனை', island: 'தீவு',
    breakfast: 'காலை உணவு', library: 'நூலகம்', country: 'நாடு', children: 'குழந்தைகள்', butterfly: 'பட்டாம்பூச்சி',
    knowledge: 'அறிவு', science: 'அறிவியல்', neighbour: 'அண்டை வீட்டுக்காரர்', believe: 'நம்புதல்', receive: 'பெறுதல்', journey: 'பயணம்',
    language: 'மொழி', vegetable: 'காய்கறி', calendar: 'நாள்காட்டி', dangerous: 'ஆபத்தான', delicious: 'சுவையான', exercise: 'உடற்பயிற்சி',
    honest: 'நேர்மையான', invitation: 'அழைப்பு, அழைப்பிதழ்', temperature: 'வெப்பநிலை', surprise: 'எதிர்பாராத மகிழ்ச்சி, வியப்பு', thought: 'எண்ணம், சிந்தனை',
    through: 'ஒரு பக்கம் நுழைந்து மறு பக்கம் வழியாக', tongue: 'நாக்கு', scissors: 'கத்தரிக்கோல்', guard: 'காவலர்', address: 'முகவரி', sentence: 'வாக்கியம்',
    government: 'அரசு', adventure: 'சாகசம்',
    accommodate: 'இடம் கொடுத்தல்', necessary: 'அவசியமான, தேவையான', occasion: 'நிகழ்ச்சி, சந்தர்ப்பம்', embarrass: 'சங்கடப்படுத்துதல்',
    conscience: 'மனசாட்சி', conscious: 'சுயநினைவுடன், விழிப்புடன்', definitely: 'நிச்சயமாக',
    environment: 'சுற்றுச்சூழல்', independence: 'சுதந்திரம்', maintenance: 'பராமரிப்பு', mischievous: 'குறும்புக்கார', pronunciation: 'உச்சரிப்பு',
    recommend: 'பரிந்துரைத்தல்', rhythm: 'தாளம்', privilege: 'தனிச்சலுகை, பெருமை', restaurant: 'உணவகம்',
    guarantee: 'உத்தரவாதம்', committee: 'குழு', parliament: 'நாடாளுமன்றம்', achievement: 'சாதனை', separate: 'தனியான, பிரித்து', beginning: 'தொடக்கம்',
    exaggerate: 'மிகைப்படுத்திச் சொல்லுதல்', hygiene: 'சுகாதாரம், தூய்மை', occurrence: 'நிகழ்வு'
  } },
  te: { m: {
    cat: 'పిల్లి', dog: 'కుక్క', sun: 'సూర్యుడు', bus: 'బస్సు', cup: 'కప్పు', hen: 'పెట్ట కోడి', pen: 'పెన్ను, కలం', red: 'ఎరుపు రంగు',
    fish: 'చేప', milk: 'పాలు', book: 'పుస్తకం', tree: 'చెట్టు', ball: 'బంతి', frog: 'కప్ప', duck: 'బాతు', star: 'నక్షత్రం', rain: 'వర్షం',
    cake: 'కేక్', kite: 'గాలిపటం', boat: 'పడవ', hand: 'చేయి', nest: 'పక్షి గూడు', ship: 'ఓడ', bell: 'గంట', jump: 'దూకడం',
    apple: 'ఆపిల్ పండు', water: 'నీళ్లు', school: 'బడి, పాఠశాల', happy: 'సంతోషంగా', mango: 'మామిడి పండు', green: 'ఆకుపచ్చ రంగు', house: 'ఇల్లు', chair: 'కుర్చీ',
    mother: 'అమ్మ', flower: 'పువ్వు', garden: 'తోట', orange: 'నారింజ పండు', monkey: 'కోతి', pencil: 'పెన్సిల్', window: 'కిటికీ', yellow: 'పసుపు రంగు',
    rabbit: 'కుందేలు', little: 'చిన్న', friend: 'స్నేహితుడు, స్నేహితురాలు', bread: 'బ్రెడ్, రొట్టె', clock: 'గడియారం', sweet: 'తీపి', river: 'నది', colour: 'రంగు',
    plant: 'మొక్క',
    beautiful: 'అందమైన', because: 'ఎందుకంటే', elephant: 'ఏనుగు', holiday: 'సెలవు రోజు', tomorrow: 'రేపు', village: 'పల్లె, గ్రామం', picture: 'బొమ్మ, చిత్రం',
    kitchen: 'వంటగది', festival: 'పండుగ', umbrella: 'గొడుగు', birthday: 'పుట్టినరోజు', morning: 'ఉదయం', family: 'కుటుంబం', weather: 'వాతావరణం',
    doctor: 'వైద్యుడు, డాక్టర్', people: 'ప్రజలు', answer: 'జవాబు', question: 'ప్రశ్న', hospital: 'ఆసుపత్రి', island: 'ద్వీపం',
    breakfast: 'ఉదయం టిఫిన్, అల్పాహారం', library: 'గ్రంథాలయం', country: 'దేశం', children: 'పిల్లలు', butterfly: 'సీతాకోకచిలుక',
    knowledge: 'జ్ఞానం', science: 'విజ్ఞాన శాస్త్రం', neighbour: 'పొరుగువారు', believe: 'నమ్మడం', receive: 'అందుకోవడం', journey: 'ప్రయాణం',
    language: 'భాష', vegetable: 'కూరగాయ', calendar: 'క్యాలెండర్ (తేదీల పట్టిక)', dangerous: 'ప్రమాదకరమైన', delicious: 'రుచికరమైన', exercise: 'వ్యాయామం',
    honest: 'నిజాయితీగల', invitation: 'ఆహ్వానం', temperature: 'ఉష్ణోగ్రత', surprise: 'అనుకోని ఆనందం, ఆశ్చర్యం', thought: 'ఆలోచన',
    through: 'ఒక వైపు నుంచి మరో వైపు గుండా', tongue: 'నాలుక', scissors: 'కత్తెర', guard: 'కాపలాదారు', address: 'చిరునామా', sentence: 'వాక్యం',
    government: 'ప్రభుత్వం', adventure: 'సాహసం',
    accommodate: 'చోటు కల్పించడం', necessary: 'అవసరమైన', occasion: 'సందర్భం', embarrass: 'ఇబ్బంది పెట్టడం',
    conscience: 'మనస్సాక్షి', conscious: 'స్పృహలో ఉన్న, అప్రమత్తమైన', definitely: 'తప్పకుండా',
    environment: 'పర్యావరణం', independence: 'స్వాతంత్ర్యం', maintenance: 'నిర్వహణ, మరమ్మత్తు', mischievous: 'అల్లరి చేసే', pronunciation: 'ఉచ్చారణ',
    recommend: 'సిఫార్సు చేయడం', rhythm: 'లయ, తాళం', privilege: 'ప్రత్యేక హక్కు, గౌరవం', restaurant: 'రెస్టారెంట్, హోటల్',
    guarantee: 'హామీ', committee: 'కమిటీ, సంఘం', parliament: 'పార్లమెంటు', achievement: 'సాధన, విజయం', separate: 'వేరుగా', beginning: 'మొదలు, ప్రారంభం',
    exaggerate: 'అతిశయోక్తిగా చెప్పడం', hygiene: 'పరిశుభ్రత', occurrence: 'సంఘటన'
  } },
  kn: { m: {
    cat: 'ಬೆಕ್ಕು', dog: 'ನಾಯಿ', sun: 'ಸೂರ್ಯ', bus: 'ಬಸ್ಸು', cup: 'ಲೋಟ, ಕಪ್', hen: 'ಹೇಂಟೆ (ಹೆಣ್ಣು ಕೋಳಿ)', pen: 'ಪೆನ್ನು', red: 'ಕೆಂಪು ಬಣ್ಣ',
    fish: 'ಮೀನು', milk: 'ಹಾಲು', book: 'ಪುಸ್ತಕ', tree: 'ಮರ', ball: 'ಚೆಂಡು', frog: 'ಕಪ್ಪೆ', duck: 'ಬಾತುಕೋಳಿ', star: 'ನಕ್ಷತ್ರ', rain: 'ಮಳೆ',
    cake: 'ಕೇಕ್', kite: 'ಗಾಳಿಪಟ', boat: 'ದೋಣಿ', hand: 'ಕೈ', nest: 'ಹಕ್ಕಿ ಗೂಡು', ship: 'ಹಡಗು', bell: 'ಗಂಟೆ', jump: 'ಜಿಗಿಯುವುದು',
    apple: 'ಸೇಬು', water: 'ನೀರು', school: 'ಶಾಲೆ', happy: 'ಸಂತೋಷ', mango: 'ಮಾವಿನ ಹಣ್ಣು', green: 'ಹಸಿರು ಬಣ್ಣ', house: 'ಮನೆ', chair: 'ಕುರ್ಚಿ',
    mother: 'ಅಮ್ಮ, ತಾಯಿ', flower: 'ಹೂವು', garden: 'ತೋಟ', orange: 'ಕಿತ್ತಳೆ ಹಣ್ಣು', monkey: 'ಕೋತಿ, ಮಂಗ', pencil: 'ಪೆನ್ಸಿಲ್', window: 'ಕಿಟಕಿ', yellow: 'ಹಳದಿ ಬಣ್ಣ',
    rabbit: 'ಮೊಲ', little: 'ಚಿಕ್ಕ', friend: 'ಸ್ನೇಹಿತ, ಗೆಳೆಯ', bread: 'ಬ್ರೆಡ್, ರೊಟ್ಟಿ', clock: 'ಗಡಿಯಾರ', sweet: 'ಸಿಹಿ', river: 'ನದಿ', colour: 'ಬಣ್ಣ',
    plant: 'ಗಿಡ',
    beautiful: 'ಸುಂದರ', because: 'ಏಕೆಂದರೆ', elephant: 'ಆನೆ', holiday: 'ರಜೆ', tomorrow: 'ನಾಳೆ', village: 'ಹಳ್ಳಿ', picture: 'ಚಿತ್ರ',
    kitchen: 'ಅಡುಗೆಮನೆ', festival: 'ಹಬ್ಬ', umbrella: 'ಕೊಡೆ', birthday: 'ಹುಟ್ಟುಹಬ್ಬ', morning: 'ಬೆಳಿಗ್ಗೆ', family: 'ಕುಟುಂಬ', weather: 'ಹವಾಮಾನ',
    doctor: 'ವೈದ್ಯ, ಡಾಕ್ಟರ್', people: 'ಜನರು', answer: 'ಉತ್ತರ', question: 'ಪ್ರಶ್ನೆ', hospital: 'ಆಸ್ಪತ್ರೆ', island: 'ದ್ವೀಪ',
    breakfast: 'ಬೆಳಗಿನ ತಿಂಡಿ', library: 'ಗ್ರಂಥಾಲಯ', country: 'ದೇಶ', children: 'ಮಕ್ಕಳು', butterfly: 'ಚಿಟ್ಟೆ',
    knowledge: 'ಜ್ಞಾನ', science: 'ವಿಜ್ಞಾನ', neighbour: 'ನೆರೆಹೊರೆಯವರು', believe: 'ನಂಬುವುದು', receive: 'ಪಡೆಯುವುದು, ಸ್ವೀಕರಿಸುವುದು', journey: 'ಪ್ರಯಾಣ',
    language: 'ಭಾಷೆ', vegetable: 'ತರಕಾರಿ', calendar: 'ಕ್ಯಾಲೆಂಡರ್ (ದಿನಾಂಕಗಳ ಪಟ್ಟಿ)', dangerous: 'ಅಪಾಯಕಾರಿ', delicious: 'ರುಚಿಕರ', exercise: 'ವ್ಯಾಯಾಮ',
    honest: 'ಪ್ರಾಮಾಣಿಕ', invitation: 'ಆಮಂತ್ರಣ', temperature: 'ತಾಪಮಾನ', surprise: 'ಅನಿರೀಕ್ಷಿತ ಖುಷಿ, ಅಚ್ಚರಿ', thought: 'ಯೋಚನೆ, ಆಲೋಚನೆ',
    through: 'ಒಂದು ಕಡೆಯಿಂದ ಇನ್ನೊಂದು ಕಡೆಗೆ ಒಳಗಿನಿಂದ', tongue: 'ನಾಲಿಗೆ', scissors: 'ಕತ್ತರಿ', guard: 'ಕಾವಲುಗಾರ', address: 'ವಿಳಾಸ', sentence: 'ವಾಕ್ಯ',
    government: 'ಸರ್ಕಾರ', adventure: 'ಸಾಹಸ',
    accommodate: 'ಸ್ಥಳಾವಕಾಶ ನೀಡುವುದು', necessary: 'ಅಗತ್ಯ', occasion: 'ಸಂದರ್ಭ', embarrass: 'ಮುಜುಗರ ಉಂಟುಮಾಡುವುದು',
    conscience: 'ಆತ್ಮಸಾಕ್ಷಿ', conscious: 'ಪ್ರಜ್ಞೆಯಲ್ಲಿರುವ, ಜಾಗೃತ', definitely: 'ಖಂಡಿತವಾಗಿ',
    environment: 'ಪರಿಸರ', independence: 'ಸ್ವಾತಂತ್ರ್ಯ', maintenance: 'ನಿರ್ವಹಣೆ', mischievous: 'ತುಂಟ', pronunciation: 'ಉಚ್ಚಾರಣೆ',
    recommend: 'ಶಿಫಾರಸು ಮಾಡುವುದು', rhythm: 'ಲಯ, ತಾಳ', privilege: 'ವಿಶೇಷ ಹಕ್ಕು, ಗೌರವ', restaurant: 'ಹೋಟೆಲ್, ಉಪಾಹಾರ ಗೃಹ',
    guarantee: 'ಖಾತರಿ', committee: 'ಸಮಿತಿ', parliament: 'ಸಂಸತ್ತು', achievement: 'ಸಾಧನೆ', separate: 'ಬೇರೆ, ಪ್ರತ್ಯೇಕ', beginning: 'ಆರಂಭ',
    exaggerate: 'ಉತ್ಪ್ರೇಕ್ಷೆ ಮಾಡುವುದು', hygiene: 'ಶುಚಿತ್ವ', occurrence: 'ಘಟನೆ'
  } },
  ml: { m: {
    cat: 'പൂച്ച', dog: 'നായ', sun: 'സൂര്യൻ', bus: 'ബസ്', cup: 'കപ്പ്', hen: 'പിടക്കോഴി', pen: 'പേന', red: 'ചുവപ്പ് നിറം',
    fish: 'മീൻ', milk: 'പാൽ', book: 'പുസ്തകം', tree: 'മരം', ball: 'പന്ത്', frog: 'തവള', duck: 'താറാവ്', star: 'നക്ഷത്രം', rain: 'മഴ',
    cake: 'കേക്ക്', kite: 'പട്ടം', boat: 'വള്ളം, തോണി', hand: 'കൈ', nest: 'കിളിക്കൂട്', ship: 'കപ്പൽ', bell: 'മണി', jump: 'ചാടുക',
    apple: 'ആപ്പിൾ', water: 'വെള്ളം', school: 'സ്കൂൾ, വിദ്യാലയം', happy: 'സന്തോഷമുള്ള', mango: 'മാമ്പഴം', green: 'പച്ച നിറം', house: 'വീട്', chair: 'കസേര',
    mother: 'അമ്മ', flower: 'പൂവ്', garden: 'പൂന്തോട്ടം', orange: 'ഓറഞ്ച് പഴം', monkey: 'കുരങ്ങൻ', pencil: 'പെൻസിൽ', window: 'ജനൽ', yellow: 'മഞ്ഞ നിറം',
    rabbit: 'മുയൽ', little: 'ചെറിയ', friend: 'കൂട്ടുകാരൻ, കൂട്ടുകാരി', bread: 'റൊട്ടി, ബ്രെഡ്', clock: 'ക്ലോക്ക്, ഘടികാരം', sweet: 'മധുരം', river: 'പുഴ, നദി', colour: 'നിറം',
    plant: 'ചെടി',
    beautiful: 'മനോഹരമായ', because: 'കാരണം, എന്തെന്നാൽ', elephant: 'ആന', holiday: 'അവധി ദിവസം', tomorrow: 'നാളെ', village: 'ഗ്രാമം', picture: 'ചിത്രം',
    kitchen: 'അടുക്കള', festival: 'ഉത്സവം, ആഘോഷം', umbrella: 'കുട', birthday: 'പിറന്നാൾ', morning: 'രാവിലെ', family: 'കുടുംബം', weather: 'കാലാവസ്ഥ',
    doctor: 'ഡോക്ടർ', people: 'ആളുകൾ, ജനങ്ങൾ', answer: 'ഉത്തരം', question: 'ചോദ്യം', hospital: 'ആശുപത്രി', island: 'ദ്വീപ്',
    breakfast: 'പ്രഭാതഭക്ഷണം', library: 'ഗ്രന്ഥശാല, വായനശാല', country: 'രാജ്യം', children: 'കുട്ടികൾ', butterfly: 'പൂമ്പാറ്റ',
    knowledge: 'അറിവ്', science: 'ശാസ്ത്രം', neighbour: 'അയൽക്കാരൻ', believe: 'വിശ്വസിക്കുക', receive: 'സ്വീകരിക്കുക, കിട്ടുക', journey: 'യാത്ര',
    language: 'ഭാഷ', vegetable: 'പച്ചക്കറി', calendar: 'കലണ്ടർ (തീയതികളുടെ പട്ടിക)', dangerous: 'അപകടകരമായ', delicious: 'രുചികരമായ', exercise: 'വ്യായാമം',
    honest: 'സത്യസന്ധമായ', invitation: 'ക്ഷണം', temperature: 'താപനില', surprise: 'അപ്രതീക്ഷിത സന്തോഷം, അത്ഭുതം', thought: 'ചിന്ത',
    through: 'ഒരു വശത്തുകൂടി കയറി മറുവശത്തുകൂടി', tongue: 'നാക്ക്', scissors: 'കത്രിക', guard: 'കാവൽക്കാരൻ', address: 'വിലാസം', sentence: 'വാക്യം',
    government: 'സർക്കാർ', adventure: 'സാഹസികത',
    accommodate: 'ഉൾക്കൊള്ളുക, ഇടം നൽകുക', necessary: 'ആവശ്യമായ', occasion: 'അവസരം, സന്ദർഭം', embarrass: 'നാണം കെടുത്തുക',
    conscience: 'മനസ്സാക്ഷി', conscious: 'ബോധമുള്ള', definitely: 'തീർച്ചയായും',
    environment: 'പരിസ്ഥിതി', independence: 'സ്വാതന്ത്ര്യം', maintenance: 'അറ്റകുറ്റപ്പണി, പരിപാലനം', mischievous: 'കുസൃതിയായ', pronunciation: 'ഉച്ചാരണം',
    recommend: 'ശുപാർശ ചെയ്യുക', rhythm: 'താളം', privilege: 'പ്രത്യേക അവകാശം, ബഹുമതി', restaurant: 'ഭക്ഷണശാല, ഹോട്ടൽ',
    guarantee: 'ഉറപ്പ്, ഗ്യാരന്റി', committee: 'സമിതി', parliament: 'പാർലമെന്റ്', achievement: 'നേട്ടം', separate: 'വേറിട്ട, വെവ്വേറെ', beginning: 'തുടക്കം',
    exaggerate: 'പെരുപ്പിച്ചു പറയുക', hygiene: 'ശുചിത്വം', occurrence: 'സംഭവം'
  } },
  ur: { m: {
    cat: 'بلی', dog: 'کتا', sun: 'سورج', bus: 'بس (سواری گاڑی)', cup: 'کپ، پیالی', hen: 'مرغی', pen: 'قلم، پین', red: 'لال رنگ',
    fish: 'مچھلی', milk: 'دودھ', book: 'کتاب', tree: 'پیڑ، درخت', ball: 'گیند', frog: 'مینڈک', duck: 'بطخ', star: 'تارا', rain: 'بارش',
    cake: 'کیک', kite: 'پتنگ', boat: 'کشتی', hand: 'ہاتھ', nest: 'گھونسلا', ship: 'پانی کا جہاز', bell: 'گھنٹی', jump: 'کودنا',
    apple: 'سیب', water: 'پانی', school: 'اسکول', happy: 'خوش', mango: 'آم', green: 'ہرا رنگ', house: 'گھر', chair: 'کرسی',
    mother: 'ماں', flower: 'پھول', garden: 'باغ', orange: 'سنترا، نارنگی', monkey: 'بندر', pencil: 'پنسل', window: 'کھڑکی', yellow: 'پیلا رنگ',
    rabbit: 'خرگوش', little: 'چھوٹا', friend: 'دوست', bread: 'ڈبل روٹی', clock: 'گھڑی', sweet: 'میٹھا', river: 'ندی، دریا', colour: 'رنگ',
    plant: 'پودا',
    beautiful: 'خوب صورت', because: 'کیونکہ', elephant: 'ہاتھی', holiday: 'چھٹی', tomorrow: 'آنے والا کل', village: 'گاؤں', picture: 'تصویر',
    kitchen: 'باورچی خانہ', festival: 'تہوار', umbrella: 'چھتری', birthday: 'سالگرہ', morning: 'صبح', family: 'خاندان، گھر والے', weather: 'موسم',
    doctor: 'ڈاکٹر', people: 'لوگ', answer: 'جواب', question: 'سوال', hospital: 'اسپتال', island: 'جزیرہ',
    breakfast: 'صبح کا ناشتہ', library: 'کتب خانہ، لائبریری', country: 'ملک', children: 'بچے', butterfly: 'تتلی',
    knowledge: 'علم', science: 'سائنس', neighbour: 'پڑوسی', believe: 'یقین کرنا', receive: 'وصول کرنا، پانا', journey: 'سفر',
    language: 'زبان (بولی)', vegetable: 'سبزی', calendar: 'کیلنڈر (تاریخوں کی فہرست)', dangerous: 'خطرناک', delicious: 'مزیدار، لذیذ', exercise: 'ورزش',
    honest: 'ایمان دار', invitation: 'دعوت، دعوت نامہ', temperature: 'درجۂ حرارت', surprise: 'اچانک ملی خوشی، حیرت', thought: 'خیال، سوچ',
    through: 'آر پار، بیچ سے ہو کر', tongue: 'زبان (منہ کا حصہ)', scissors: 'قینچی', guard: 'چوکیدار، محافظ', address: 'پتا (گھر کا)', sentence: 'جملہ',
    government: 'حکومت، سرکار', adventure: 'مہم، سنسنی خیز تجربہ',
    accommodate: 'جگہ دینا، سما لینا', necessary: 'ضروری', occasion: 'موقع', embarrass: 'شرمندہ کرنا',
    conscience: 'ضمیر', conscious: 'ہوش میں، باخبر', definitely: 'ضرور، یقیناً',
    environment: 'ماحول', independence: 'آزادی', maintenance: 'دیکھ بھال، مرمت', mischievous: 'شرارتی', pronunciation: 'تلفظ',
    recommend: 'سفارش کرنا', rhythm: 'لے، تال', privilege: 'خاص حق، اعزاز', restaurant: 'ریستوراں',
    guarantee: 'گارنٹی، پکا وعدہ', committee: 'کمیٹی', parliament: 'پارلیمنٹ', achievement: 'کامیابی', separate: 'الگ', beginning: 'شروعات، آغاز',
    exaggerate: 'بڑھا چڑھا کر بتانا', hygiene: 'صفائی ستھرائی', occurrence: 'واقعہ'
  } }
};
