/* Spelling Bee: UI strings. Keys are identical in all 12 languages.
   Shared words (clear, cancel, score, fullscreen, loading, ...) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Spelling Bee',
    intro: 'Hear an English word, then spell it. Learn meanings in your own language, use hints, play a class spelling bee and print spelling tests.',
    tab_practise: 'Practise', tab_bee: 'Class bee', tab_lists: 'Word lists',
    choose_level: 'Choose a level', level_n: 'Level {n}', class_n: 'Class {n}', n_words: '{n} words', best_n: 'best {s}/{n}',
    my_list: 'My list', review_lvl: 'My mistakes', review_none: 'No mistakes yet', custom_none: 'Add words in “Word lists”',
    opt_second: 'Give a second try', opt_auto: 'Say each new word automatically', start_round: 'Start', round_info: '{n} words in this round',
    help_h: 'How to use · Ideas for the classroom',
    tip1: 'Choose a level and press <b>Start</b>. Listen to the word 🔊, hear it in a sentence 💬 or slowly 🐢. Type the spelling and press <b>Check</b> (or Enter).',
    tip2: 'Stuck? Take a hint: the first letter, the number of letters, or the jumbled letters. On a phone or smartboard, tap the jumbled letters instead of typing.',
    tip3: 'Green letters are right, red letters need fixing and a dashed box means a letter is missing. Words you miss go to <b>My mistakes</b> so you can practise them again.',
    tip4: 'Teachers: paste this week’s words in <b>Word lists</b>, one per line. Print the list or a spelling test with an answer key, or send the list to students as a WhatsApp link.',
    tip5: 'Class activity: open <b>Class bee</b> on the projector, make 2–4 teams and let them spell in turn. Children can spell aloud while you tap ✓ or ✗.',
    tip6: 'No English voice? The app shows the meaning, the sentence with a blank and the jumbled letters, so children can still play. On Windows, add the “English (India)” voice in Settings → Time &amp; language → Speech.',
    voice_h: 'Voice', voice_lbl: 'English voice', voice_auto: 'Automatic (Indian English first)', voice_using: 'Using:', voice_test: 'Test the voice', speed: 'Speed',
    nv_title: 'No English voice on this device',
    nv_short: 'Use the meaning, the sentence and the jumbled letters to find the word.',
    nv_help: 'You can still play: the meaning, the sentence and the jumbled letters are shown. Chrome on Android usually has an English voice; on a computer add “English (India)” in the speech settings.',
    stats_h: 'My progress', st_words: 'words tried', st_acc: 'correct', st_streak: 'best streak', st_review: 'to practise again',
    reset_progress: 'Reset progress', confirm_progress: 'Clear your scores and your mistakes list? Your own word list is kept.', reset_done: 'Progress cleared.',
    word_x_of_y: 'Word {i} of {n}', streak: 'Streak (right answers in a row)', end_round: 'End round',
    hear_word: 'Hear the word', hear_sent: 'In a sentence', hear_slow: 'Slowly',
    meaning: 'Meaning', sentence_lbl: 'Sentence', starts_with: 'Starts with',
    hints: 'Hints', hint_first: 'First letter', hint_len: 'How many letters', hint_jumble: 'Jumbled letters',
    hints_used_n: 'Hints used: {n}', hint_free: 'Jumbled letters are free when there is no voice.', letters_n: '{n} letters',
    jumble_aria: 'Jumbled letters, tap to type', tap_letter: 'Type {l}', space_key: 'Space',
    your_spelling: 'Your spelling', answer_ph: 'Type the spelling', backspace: 'Delete last letter', check: 'Check', show_answer: 'Show answer',
    fb_empty: 'Type the spelling first.', fb_retry: 'Almost! Fix the red letters and try once more.', fb_missing: 'Missing letters: {n}',
    lg_ok: 'right', lg_bad: 'wrong', lg_miss: 'missing',
    fb_ok: 'Correct! Well done.', fb_ok2: 'Correct on the second try!',
    fb_alt: '“{alt}” is the American spelling. In India we usually write “{w}”.',
    fb_bad: 'Not this time. The right spelling is:', fb_shown: 'Here is the right spelling:',
    you_wrote: 'You wrote', right_spelling: 'Right spelling',
    fb_learn: 'Look at the yellow letters, they are the tricky part. Say the word and spell it aloud once.',
    next_word: 'Next word', see_result: 'See my score',
    sum_title: 'Round complete!', sum_score: '{c} out of {n} correct',
    praise_1: 'Good effort! Practise the words below and try again.', praise_2: 'Well done! A little more practice and you will get them all.', praise_3: 'Superb spelling!',
    sum_streak: 'Best streak: {n}', sum_hints: 'Hints used: {n}', new_best: 'New best score!',
    sum_mistakes: 'Words to practise', sum_perfect: 'Perfect round, no mistakes! 🎉',
    practise_these: 'Practise these words', new_round: 'New round', change_level: 'Change level', listen_to: 'Listen to {w}',
    bee_setup_h: 'Set up a class spelling bee',
    bee_help: 'Show this on the projector or smartboard. Players or teams take turns: each hears a word and spells it, by typing or aloud while the teacher judges.',
    players: 'Players or teams', player_n: 'Player {n}', add_player: 'Add player', remove_player: 'Remove player {n}',
    level_lbl: 'Word level', per_player: 'Words for each player', game_type: 'Game', type_points: 'Points', type_ko: 'Knock-out',
    type_points_help: 'Everyone gets the same number of words. Most correct words wins.',
    type_ko_help: 'Each player has 3 lives. A wrong spelling costs a life; the last player left wins.',
    start_bee: 'Start the bee', bee_how_h: 'How to run it',
    bee_step1: 'Write the names of players or teams and pick a level.',
    bee_step2: 'Press Start and go full screen. The app reads the word aloud.',
    bee_step3: 'The player types the word, or spells it aloud and you tap ✓ or ✗.',
    bee_step4: 'Everyone sees the right spelling, then press Next player.',
    turn_of: '{name}, your turn!', bee_round: 'Word {i} of {n}', judge_help: 'Spelt aloud? Teacher, judge:', judge_ok: 'Correct', judge_bad: 'Wrong',
    next_player: 'Next player', see_winner: 'See the winner', end_game: 'End game', confirm_end: 'End the game now and show the scores?',
    lives_n: '{n} lives left', out: 'Out', winner_is: '{name} wins! 🎉', winners_tie: 'It’s a tie: {names}',
    final_note: 'Clap for every speller, they all practised today!', col_player: 'Player', col_lives: 'Lives',
    play_again: 'Play again', change_players: 'Change players',
    my_list_h: 'My word list',
    my_list_help: 'For teachers: type or paste English words, one per line. You can add a sentence and a meaning after a | sign.',
    format_lbl: 'Format:', my_list_format: 'word | sentence | meaning', words_box: 'Words',
    save_list: 'Save list', example_list: 'Example', share_list: 'Share link',
    list_saved: 'Saved {n} words. Choose “My list” in Practise or Class bee.', list_skipped: '{n} lines skipped: use English letters only.',
    list_empty: 'The list is empty. Type some words first.', list_cleared: 'List cleared.', confirm_clear_list: 'Delete your word list?', confirm_replace_list: 'This replaces your current word list ({n} words). Continue?',
    share_done: 'Link copied! Send it to students: the list opens in their browser.',
    wa_list: 'Spelling practice: {n} words for this week. Open: {url}',
    shared_found: 'Someone shared a list of {n} words with you.', use_shared: 'Use this list', wa_share: 'Send on WhatsApp',
    print_h: 'See and print word lists', print_list: 'Print word list', print_test: 'Print spelling test',
    col_word: 'Word', col_sentence: 'Example sentence', col_listen: 'Listen',
    print_title: 'Spelling list: {level}', test_title: 'Spelling test: {level}',
    print_name: 'Name', print_class: 'Class', print_date: 'Date',
    test_instr: 'Listen to your teacher and write each word. The meaning is given as a clue.', answer_key: 'Answer key (for the teacher)'
  },
  hi: {
    app_title: 'स्पेलिंग बी',
    intro: 'अंग्रेज़ी शब्द सुनें और उसकी स्पेलिंग लिखें। अपनी भाषा में अर्थ जानें, संकेत लें, कक्षा में स्पेलिंग बी खेलें और स्पेलिंग टेस्ट प्रिंट करें।',
    tab_practise: 'अभ्यास', tab_bee: 'कक्षा प्रतियोगिता', tab_lists: 'शब्द सूचियाँ',
    choose_level: 'स्तर चुनें', level_n: 'स्तर {n}', class_n: 'कक्षा {n}', n_words: '{n} शब्द', best_n: 'सबसे अच्छा {s}/{n}',
    my_list: 'मेरी सूची', review_lvl: 'मेरी गलतियाँ', review_none: 'अभी कोई गलती नहीं', custom_none: '“शब्द सूचियाँ” में शब्द जोड़ें',
    opt_second: 'दूसरा मौका दें', opt_auto: 'हर शब्द अपने आप बोले', start_round: 'शुरू करें', round_info: 'इस राउंड में {n} शब्द',
    help_h: 'कैसे इस्तेमाल करें · कक्षा के लिए सुझाव',
    tip1: 'स्तर चुनें और <b>शुरू करें</b> दबाएँ। शब्द सुनें 🔊, वाक्य में सुनें 💬 या धीरे सुनें 🐢। फिर स्पेलिंग टाइप करें और <b>जाँचें</b> दबाएँ (या Enter)।',
    tip2: 'अटक गए? संकेत लें: पहला अक्षर, कितने अक्षर, या उलझे हुए अक्षर। फ़ोन या स्मार्टबोर्ड पर टाइप करने की जगह उलझे अक्षरों पर टैप करें।',
    tip3: 'हरे अक्षर सही हैं, लाल अक्षर ठीक करने हैं और बिंदुओं वाला डिब्बा मतलब कोई अक्षर छूट गया। जो शब्द गलत हों वे <b>मेरी गलतियाँ</b> में चले जाते हैं, ताकि आप बाद में फिर अभ्यास कर सकें।',
    tip4: 'शिक्षक: इस हफ़्ते के शब्द <b>शब्द सूचियाँ</b> में डालें, हर लाइन में एक। सूची या उत्तर-कुंजी वाला स्पेलिंग टेस्ट प्रिंट करें, या सूची को WhatsApp लिंक बनाकर बच्चों को भेजें।',
    tip5: 'कक्षा गतिविधि: प्रोजेक्टर पर <b>कक्षा प्रतियोगिता</b> खोलें, 2–4 टीमें बनाएँ और बारी-बारी से स्पेलिंग पूछें। बच्चे बोलकर स्पेलिंग बता सकते हैं और आप ✓ या ✗ दबाएँ।',
    tip6: 'अंग्रेज़ी आवाज़ नहीं है? ऐप अर्थ, खाली जगह वाला वाक्य और उलझे अक्षर दिखाता है, इसलिए बच्चे फिर भी खेल सकते हैं। Windows में Settings → Time &amp; language → Speech में जाकर “English (India)” आवाज़ जोड़ें।',
    voice_h: 'आवाज़', voice_lbl: 'अंग्रेज़ी आवाज़', voice_auto: 'अपने आप (पहले भारतीय अंग्रेज़ी)', voice_using: 'आवाज़:', voice_test: 'आवाज़ जाँचें', speed: 'गति',
    nv_title: 'इस डिवाइस पर अंग्रेज़ी आवाज़ नहीं है',
    nv_short: 'शब्द पहचानने के लिए अर्थ, वाक्य और उलझे अक्षरों की मदद लें।',
    nv_help: 'आप फिर भी खेल सकते हैं: अर्थ, वाक्य और उलझे अक्षर दिखाए जाएँगे। Android पर Chrome में अक्सर अंग्रेज़ी आवाज़ होती है; कंप्यूटर पर स्पीच सेटिंग में “English (India)” जोड़ें।',
    stats_h: 'मेरी प्रगति', st_words: 'शब्द आज़माए', st_acc: 'सही', st_streak: 'लगातार सही का रिकॉर्ड', st_review: 'फिर से अभ्यास करने हैं',
    reset_progress: 'प्रगति रीसेट करें', confirm_progress: 'आपके अंक और गलतियों की सूची मिटा दें? आपकी अपनी शब्द सूची बनी रहेगी।', reset_done: 'प्रगति मिटा दी गई।',
    word_x_of_y: 'शब्द {i} / {n}', streak: 'लगातार सही जवाब', end_round: 'राउंड खत्म करें',
    hear_word: 'शब्द सुनें', hear_sent: 'वाक्य में सुनें', hear_slow: 'धीरे सुनें',
    meaning: 'अर्थ', sentence_lbl: 'वाक्य', starts_with: 'पहला अक्षर',
    hints: 'संकेत', hint_first: 'पहला अक्षर', hint_len: 'कितने अक्षर', hint_jumble: 'उलझे अक्षर',
    hints_used_n: 'संकेत लिए: {n}', hint_free: 'आवाज़ न होने पर उलझे अक्षर मुफ़्त हैं।', letters_n: '{n} अक्षर',
    jumble_aria: 'उलझे अक्षर, टाइप करने के लिए टैप करें', tap_letter: '{l} लिखें', space_key: 'स्पेस',
    your_spelling: 'आपकी स्पेलिंग', answer_ph: 'स्पेलिंग टाइप करें', backspace: 'आख़िरी अक्षर मिटाएँ', check: 'जाँचें', show_answer: 'उत्तर दिखाएँ',
    fb_empty: 'पहले स्पेलिंग टाइप करें।', fb_retry: 'लगभग सही! लाल अक्षर ठीक करें और एक बार फिर कोशिश करें।', fb_missing: 'छूटे अक्षर: {n}',
    lg_ok: 'सही', lg_bad: 'गलत', lg_miss: 'छूटा हुआ',
    fb_ok: 'सही! बहुत बढ़िया।', fb_ok2: 'दूसरी कोशिश में सही!',
    fb_alt: '“{alt}” अमेरिकी स्पेलिंग है। भारत में हम आमतौर पर “{w}” लिखते हैं।',
    fb_bad: 'इस बार नहीं। सही स्पेलिंग है:', fb_shown: 'यह रही सही स्पेलिंग:',
    you_wrote: 'आपने लिखा', right_spelling: 'सही स्पेलिंग',
    fb_learn: 'पीले अक्षर देखें, यही मुश्किल हिस्सा है। शब्द बोलें और एक बार ज़ोर से स्पेलिंग बोलें।',
    next_word: 'अगला शब्द', see_result: 'मेरा स्कोर देखें',
    sum_title: 'राउंड पूरा हुआ!', sum_score: '{n} में से {c} सही',
    praise_1: 'अच्छी कोशिश! नीचे के शब्दों का अभ्यास करें और फिर से खेलें।', praise_2: 'शाबाश! थोड़ा और अभ्यास, और सब सही होंगे।', praise_3: 'कमाल की स्पेलिंग!',
    sum_streak: 'लगातार सही: {n}', sum_hints: 'संकेत लिए: {n}', new_best: 'नया सबसे अच्छा स्कोर!',
    sum_mistakes: 'अभ्यास के लिए शब्द', sum_perfect: 'बिना किसी गलती के पूरा राउंड! 🎉',
    practise_these: 'इन शब्दों का अभ्यास करें', new_round: 'नया राउंड', change_level: 'स्तर बदलें', listen_to: '{w} सुनें',
    bee_setup_h: 'कक्षा में स्पेलिंग प्रतियोगिता',
    bee_help: 'इसे प्रोजेक्टर या स्मार्टबोर्ड पर दिखाएँ। खिलाड़ी या टीमें बारी-बारी से खेलती हैं: हर कोई एक शब्द सुनकर उसकी स्पेलिंग टाइप करता है या बोलकर बताता है और शिक्षक फ़ैसला करते हैं।',
    players: 'खिलाड़ी या टीमें', player_n: 'खिलाड़ी {n}', add_player: 'खिलाड़ी जोड़ें', remove_player: 'खिलाड़ी {n} हटाएँ',
    level_lbl: 'शब्दों का स्तर', per_player: 'हर खिलाड़ी को कितने शब्द', game_type: 'खेल', type_points: 'अंक', type_ko: 'नॉक-आउट',
    type_points_help: 'सबको बराबर शब्द मिलते हैं। सबसे ज़्यादा सही शब्द वाला जीतता है।',
    type_ko_help: 'हर खिलाड़ी के पास 3 जान हैं। गलत स्पेलिंग पर एक जान जाती है; आख़िर में बचा खिलाड़ी जीतता है।',
    start_bee: 'प्रतियोगिता शुरू करें', bee_how_h: 'कैसे चलाएँ',
    bee_step1: 'खिलाड़ियों या टीमों के नाम लिखें और स्तर चुनें।',
    bee_step2: 'शुरू करें दबाएँ और पूरी स्क्रीन करें। ऐप शब्द बोलकर सुनाता है।',
    bee_step3: 'खिलाड़ी शब्द टाइप करे, या बोलकर स्पेलिंग बताए और आप ✓ या ✗ दबाएँ।',
    bee_step4: 'सब सही स्पेलिंग देखें, फिर अगला खिलाड़ी दबाएँ।',
    turn_of: '{name}, आपकी बारी!', bee_round: 'शब्द {i} / {n}', judge_help: 'बोलकर स्पेलिंग बताई? शिक्षक, फ़ैसला करें:', judge_ok: 'सही', judge_bad: 'गलत',
    next_player: 'अगला खिलाड़ी', see_winner: 'विजेता देखें', end_game: 'खेल खत्म करें', confirm_end: 'खेल अभी खत्म करके अंक दिखाएँ?',
    lives_n: '{n} जान बाकी', out: 'बाहर', winner_is: '{name} जीत गए! 🎉', winners_tie: 'बराबरी: {names}',
    final_note: 'हर खिलाड़ी के लिए ताली, आज सबने अभ्यास किया!', col_player: 'खिलाड़ी', col_lives: 'जान',
    play_again: 'फिर से खेलें', change_players: 'खिलाड़ी बदलें',
    my_list_h: 'मेरी शब्द सूची',
    my_list_help: 'शिक्षकों के लिए: अंग्रेज़ी शब्द टाइप या पेस्ट करें, हर लाइन में एक। चाहें तो | निशान के बाद वाक्य और अर्थ भी लिखें।',
    format_lbl: 'तरीका:', my_list_format: 'शब्द | वाक्य | अर्थ', words_box: 'शब्द',
    save_list: 'सूची सेव करें', example_list: 'उदाहरण', share_list: 'लिंक शेयर करें',
    list_saved: '{n} शब्द सेव हुए। अभ्यास या कक्षा प्रतियोगिता में “मेरी सूची” चुनें।', list_skipped: '{n} लाइनें छोड़ दी गईं: सिर्फ़ अंग्रेज़ी अक्षर लिखें।',
    list_empty: 'सूची खाली है। पहले कुछ शब्द लिखें।', list_cleared: 'सूची मिटा दी गई।', confirm_clear_list: 'अपनी शब्द सूची मिटा दें?', confirm_replace_list: 'इससे आपकी अभी की शब्द सूची ({n} शब्द) बदल जाएगी। आगे बढ़ें?',
    share_done: 'लिंक कॉपी हो गया! इसे बच्चों को भेजें: सूची उनके ब्राउज़र में खुल जाएगी।',
    wa_list: 'स्पेलिंग अभ्यास: इस हफ़्ते के {n} शब्द। यहाँ खोलें: {url}',
    shared_found: 'किसी ने आपके साथ {n} शब्दों की सूची शेयर की है।', use_shared: 'यह सूची इस्तेमाल करें', wa_share: 'WhatsApp पर भेजें',
    print_h: 'शब्द सूचियाँ देखें और प्रिंट करें', print_list: 'शब्द सूची प्रिंट करें', print_test: 'स्पेलिंग टेस्ट प्रिंट करें',
    col_word: 'शब्द', col_sentence: 'उदाहरण वाक्य', col_listen: 'सुनें',
    print_title: 'स्पेलिंग सूची: {level}', test_title: 'स्पेलिंग टेस्ट: {level}',
    print_name: 'नाम', print_class: 'कक्षा', print_date: 'तारीख़',
    test_instr: 'शिक्षक को ध्यान से सुनें और हर शब्द लिखें। संकेत के लिए अर्थ दिया गया है।', answer_key: 'उत्तर कुंजी (शिक्षक के लिए)'
  }
  ,
  bn: {
    app_title: 'স্পেলিং বি',
    intro: 'ইংরেজি শব্দ শুনুন, তারপর তার বানান লিখুন। নিজের ভাষায় অর্থ জানুন, সংকেত নিন, ক্লাসে স্পেলিং বি খেলুন আর বানান পরীক্ষা প্রিন্ট করুন।',
    tab_practise: 'অনুশীলন', tab_bee: 'ক্লাসের প্রতিযোগিতা', tab_lists: 'শব্দ তালিকা',
    choose_level: 'স্তর বেছে নিন', level_n: 'স্তর {n}', class_n: 'শ্রেণি {n}', n_words: '{n}টি শব্দ', best_n: 'সেরা {s}/{n}',
    my_list: 'আমার তালিকা', review_lvl: 'আমার ভুলগুলো', review_none: 'এখনও কোনো ভুল নেই', custom_none: '“শব্দ তালিকা”-য় শব্দ যোগ করুন',
    opt_second: 'দ্বিতীয় সুযোগ দিন', opt_auto: 'প্রতিটি শব্দ নিজে থেকে বলবে', start_round: 'শুরু করুন', round_info: 'এই রাউন্ডে {n}টি শব্দ',
    help_h: 'কীভাবে ব্যবহার করবেন · ক্লাসের জন্য পরামর্শ',
    tip1: 'স্তর বেছে <b>শুরু করুন</b> চাপুন। শব্দ শুনুন 🔊, বাক্যে শুনুন 💬 বা ধীরে শুনুন 🐢। তারপর বানান টাইপ করে <b>যাচাই করুন</b> চাপুন (বা Enter)।',
    tip2: 'আটকে গেছেন? সংকেত নিন: প্রথম অক্ষর, কটি অক্ষর, বা এলোমেলো অক্ষর। ফোন বা স্মার্টবোর্ডে টাইপ না করে এলোমেলো অক্ষরে ট্যাপ করুন।',
    tip3: 'সবুজ অক্ষর ঠিক, লাল অক্ষর ঠিক করতে হবে, আর ডট-দাগের বাক্স মানে একটি অক্ষর বাদ পড়েছে। ভুল শব্দগুলো <b>আমার ভুলগুলো</b>-তে জমা হয়, পরে আবার অনুশীলন করতে পারবেন।',
    tip4: 'শিক্ষকদের জন্য: এই সপ্তাহের শব্দ <b>শব্দ তালিকা</b>-য় লিখুন, প্রতি লাইনে একটি। তালিকা বা উত্তরসহ বানান পরীক্ষা প্রিন্ট করুন, অথবা WhatsApp লিংকে ছাত্রছাত্রীদের পাঠান।',
    tip5: 'ক্লাসের খেলা: প্রোজেক্টরে <b>ক্লাসের প্রতিযোগিতা</b> খুলুন, 2–4টি দল বানান আর পালা করে বানান জিজ্ঞেস করুন। শিশুরা মুখে বানান বলতে পারে, আপনি ✓ বা ✗ চাপবেন।',
    tip6: 'ইংরেজি কণ্ঠস্বর নেই? অ্যাপ অর্থ, ফাঁকা জায়গাসহ বাক্য আর এলোমেলো অক্ষর দেখায়, তাই শিশুরা তবুও খেলতে পারে। Windows-এ Settings → Time &amp; language → Speech-এ গিয়ে “English (India)” ভয়েস যোগ করুন।',
    voice_h: 'কণ্ঠস্বর', voice_lbl: 'ইংরেজি কণ্ঠস্বর', voice_auto: 'স্বয়ংক্রিয় (আগে ভারতীয় ইংরেজি)', voice_using: 'কণ্ঠস্বর:', voice_test: 'কণ্ঠস্বর পরীক্ষা করুন', speed: 'গতি',
    nv_title: 'এই ডিভাইসে ইংরেজি কণ্ঠস্বর নেই',
    nv_short: 'শব্দটি খুঁজতে অর্থ, বাক্য আর এলোমেলো অক্ষরের সাহায্য নিন।',
    nv_help: 'তবুও খেলা যাবে: অর্থ, বাক্য আর এলোমেলো অক্ষর দেখানো হবে। Android-এ Chrome-এ সাধারণত ইংরেজি কণ্ঠস্বর থাকে; কম্পিউটারে স্পিচ সেটিংসে “English (India)” যোগ করুন।',
    stats_h: 'আমার অগ্রগতি', st_words: 'চেষ্টা করা শব্দ', st_acc: 'সঠিক', st_streak: 'টানা সঠিকের রেকর্ড', st_review: 'আবার অনুশীলন বাকি',
    reset_progress: 'অগ্রগতি রিসেট করুন', confirm_progress: 'আপনার স্কোর আর ভুলের তালিকা মুছে ফেলবেন? আপনার নিজের শব্দ তালিকা থেকে যাবে।', reset_done: 'অগ্রগতি মুছে ফেলা হয়েছে।',
    word_x_of_y: 'শব্দ {i} / {n}', streak: 'টানা সঠিক উত্তর', end_round: 'রাউন্ড শেষ করুন',
    hear_word: 'শব্দ শুনুন', hear_sent: 'বাক্যে শুনুন', hear_slow: 'ধীরে শুনুন',
    meaning: 'অর্থ', sentence_lbl: 'বাক্য', starts_with: 'প্রথম অক্ষর',
    hints: 'সংকেত', hint_first: 'প্রথম অক্ষর', hint_len: 'কটি অক্ষর', hint_jumble: 'এলোমেলো অক্ষর',
    hints_used_n: 'সংকেত নেওয়া হয়েছে: {n}', hint_free: 'কণ্ঠস্বর না থাকলে এলোমেলো অক্ষর বিনামূল্যে।', letters_n: '{n}টি অক্ষর',
    jumble_aria: 'এলোমেলো অক্ষর, টাইপ করতে ট্যাপ করুন', tap_letter: '{l} লিখুন', space_key: 'স্পেস',
    your_spelling: 'আপনার বানান', answer_ph: 'বানান টাইপ করুন', backspace: 'শেষ অক্ষর মুছুন', check: 'যাচাই করুন', show_answer: 'উত্তর দেখান',
    fb_empty: 'আগে বানান টাইপ করুন।', fb_retry: 'প্রায় হয়ে গেছে! লাল অক্ষরগুলো ঠিক করে আর একবার চেষ্টা করুন।', fb_missing: 'বাদ পড়া অক্ষর: {n}',
    lg_ok: 'ঠিক', lg_bad: 'ভুল', lg_miss: 'বাদ পড়েছে',
    fb_ok: 'সঠিক! দারুণ।', fb_ok2: 'দ্বিতীয় চেষ্টায় সঠিক!',
    fb_alt: '“{alt}” আমেরিকান বানান। ভারতে আমরা সাধারণত “{w}” লিখি।',
    fb_bad: 'এবার হলো না। সঠিক বানান হলো:', fb_shown: 'এই হলো সঠিক বানান:',
    you_wrote: 'আপনি লিখেছেন', right_spelling: 'সঠিক বানান',
    fb_learn: 'হলুদ অক্ষরগুলো দেখুন, এগুলোই কঠিন অংশ। শব্দটি বলুন আর একবার জোরে বানান করুন।',
    next_word: 'পরের শব্দ', see_result: 'আমার স্কোর দেখুন',
    sum_title: 'রাউন্ড শেষ!', sum_score: '{n}টির মধ্যে {c}টি সঠিক',
    praise_1: 'ভালো চেষ্টা! নিচের শব্দগুলো অনুশীলন করে আবার খেলুন।', praise_2: 'শাবাশ! আর একটু অনুশীলন করলেই সব ঠিক হবে।', praise_3: 'দুর্দান্ত বানান!',
    sum_streak: 'টানা সঠিক: {n}', sum_hints: 'সংকেত নেওয়া: {n}', new_best: 'নতুন সেরা স্কোর!',
    sum_mistakes: 'অনুশীলনের শব্দ', sum_perfect: 'একটাও ভুল নেই, নিখুঁত রাউন্ড! 🎉',
    practise_these: 'এই শব্দগুলো অনুশীলন করুন', new_round: 'নতুন রাউন্ড', change_level: 'স্তর বদলান', listen_to: '{w} শুনুন',
    bee_setup_h: 'ক্লাসে বানান প্রতিযোগিতা',
    bee_help: 'এটি প্রোজেক্টর বা স্মার্টবোর্ডে দেখান। খেলোয়াড় বা দলগুলো পালা করে খেলে: প্রত্যেকে একটি শব্দ শুনে বানান টাইপ করে বা মুখে বলে, আর শিক্ষক বিচার করেন।',
    players: 'খেলোয়াড় বা দল', player_n: 'খেলোয়াড় {n}', add_player: 'খেলোয়াড় যোগ করুন', remove_player: 'খেলোয়াড় {n} সরান',
    level_lbl: 'শব্দের স্তর', per_player: 'প্রতি খেলোয়াড়ের শব্দ', game_type: 'খেলার ধরন', type_points: 'পয়েন্ট', type_ko: 'নক-আউট',
    type_points_help: 'সবাই সমান সংখ্যক শব্দ পায়। যার সবচেয়ে বেশি সঠিক, সে জেতে।',
    type_ko_help: 'প্রত্যেকের 3টি প্রাণ। ভুল বানানে একটি প্রাণ যায়; শেষে যে টিকে থাকে সে জেতে।',
    start_bee: 'প্রতিযোগিতা শুরু করুন', bee_how_h: 'কীভাবে চালাবেন',
    bee_step1: 'খেলোয়াড় বা দলের নাম লিখুন আর স্তর বেছে নিন।',
    bee_step2: 'শুরু চাপুন আর পূর্ণ পর্দা করুন। অ্যাপ শব্দটি পড়ে শোনাবে।',
    bee_step3: 'খেলোয়াড় শব্দটি টাইপ করবে, অথবা মুখে বানান বলবে আর আপনি ✓ বা ✗ চাপবেন।',
    bee_step4: 'সবাই সঠিক বানান দেখবে, তারপর পরের খেলোয়াড় চাপুন।',
    turn_of: '{name}, এবার তোমার পালা!', bee_round: 'শব্দ {i} / {n}', judge_help: 'মুখে বানান বলেছে? শিক্ষক, বিচার করুন:', judge_ok: 'সঠিক', judge_bad: 'ভুল',
    next_player: 'পরের খেলোয়াড়', see_winner: 'বিজয়ী দেখুন', end_game: 'খেলা শেষ করুন', confirm_end: 'খেলা এখনই শেষ করে স্কোর দেখাবেন?',
    lives_n: '{n}টি প্রাণ বাকি', out: 'আউট', winner_is: '{name} জিতেছে! 🎉', winners_tie: 'সমান সমান: {names}',
    final_note: 'সব খেলোয়াড়ের জন্য হাততালি, আজ সবাই অনুশীলন করেছে!', col_player: 'খেলোয়াড়', col_lives: 'প্রাণ',
    play_again: 'আবার খেলুন', change_players: 'খেলোয়াড় বদলান',
    my_list_h: 'আমার শব্দ তালিকা',
    my_list_help: 'শিক্ষকদের জন্য: ইংরেজি শব্দ টাইপ বা পেস্ট করুন, প্রতি লাইনে একটি। চাইলে | চিহ্নের পরে বাক্য আর অর্থও লিখুন।',
    format_lbl: 'নিয়ম:', my_list_format: 'শব্দ | বাক্য | অর্থ', words_box: 'শব্দগুলো',
    save_list: 'তালিকা সেভ করুন', example_list: 'উদাহরণ', share_list: 'লিংক শেয়ার করুন',
    list_saved: '{n}টি শব্দ সেভ হয়েছে। অনুশীলন বা ক্লাসের প্রতিযোগিতায় “আমার তালিকা” বেছে নিন।', list_skipped: '{n}টি লাইন বাদ দেওয়া হয়েছে: শুধু ইংরেজি অক্ষর লিখুন।',
    list_empty: 'তালিকা খালি। আগে কয়েকটি শব্দ লিখুন।', list_cleared: 'তালিকা মুছে ফেলা হয়েছে।', confirm_clear_list: 'আপনার শব্দ তালিকা মুছে ফেলবেন?', confirm_replace_list: 'এতে আপনার এখনকার শব্দ তালিকা ({n}টি শব্দ) বদলে যাবে। এগোবেন?',
    share_done: 'লিংক কপি হয়েছে! ছাত্রছাত্রীদের পাঠান: তালিকাটি তাদের ব্রাউজারে খুলবে।',
    wa_list: 'বানান অনুশীলন: এই সপ্তাহের {n}টি শব্দ। এখানে খুলুন: {url}',
    shared_found: 'কেউ আপনাকে {n}টি শব্দের একটি তালিকা পাঠিয়েছে।', use_shared: 'এই তালিকা ব্যবহার করুন', wa_share: 'WhatsApp-এ পাঠান',
    print_h: 'শব্দ তালিকা দেখুন ও প্রিন্ট করুন', print_list: 'শব্দ তালিকা প্রিন্ট করুন', print_test: 'বানান পরীক্ষা প্রিন্ট করুন',
    col_word: 'শব্দ', col_sentence: 'উদাহরণ বাক্য', col_listen: 'শুনুন',
    print_title: 'বানান তালিকা: {level}', test_title: 'বানান পরীক্ষা: {level}',
    print_name: 'নাম', print_class: 'শ্রেণি', print_date: 'তারিখ',
    test_instr: 'শিক্ষকের কথা মন দিয়ে শুনে প্রতিটি শব্দ লেখো। সংকেত হিসেবে অর্থ দেওয়া আছে।', answer_key: 'উত্তর (শিক্ষকের জন্য)'
  },
  mr: {
    app_title: 'स्पेलिंग बी',
    intro: 'इंग्रजी शब्द ऐका आणि त्याचे स्पेलिंग लिहा. आपल्या भाषेत अर्थ जाणून घ्या, संकेत घ्या, वर्गात स्पेलिंग बी खेळा आणि स्पेलिंग चाचणी प्रिंट करा.',
    tab_practise: 'सराव', tab_bee: 'वर्ग स्पर्धा', tab_lists: 'शब्दयाद्या',
    choose_level: 'स्तर निवडा', level_n: 'स्तर {n}', class_n: 'इयत्ता {n}', n_words: '{n} शब्द', best_n: 'सर्वोत्तम {s}/{n}',
    my_list: 'माझी यादी', review_lvl: 'माझ्या चुका', review_none: 'अजून एकही चूक नाही', custom_none: '“शब्दयाद्या” मध्ये शब्द जोडा',
    opt_second: 'दुसरी संधी द्या', opt_auto: 'प्रत्येक शब्द आपोआप बोलला जावा', start_round: 'सुरू करा', round_info: 'या फेरीत {n} शब्द',
    help_h: 'कसे वापरायचे · वर्गासाठी कल्पना',
    tip1: 'स्तर निवडा आणि <b>सुरू करा</b> दाबा. शब्द ऐका 🔊, वाक्यात ऐका 💬 किंवा हळू ऐका 🐢. मग स्पेलिंग टाइप करा आणि <b>तपासा</b> दाबा (किंवा Enter).',
    tip2: 'अडकलात? संकेत घ्या: पहिले अक्षर, किती अक्षरे, किंवा उलटसुलट अक्षरे. फोन किंवा स्मार्टबोर्डवर टाइप करण्याऐवजी उलटसुलट अक्षरांवर टॅप करा.',
    tip3: 'हिरवी अक्षरे बरोबर, लाल अक्षरे दुरुस्त करायची आहेत आणि ठिपक्यांचा चौकोन म्हणजे एखादे अक्षर राहिले. चुकलेले शब्द <b>माझ्या चुका</b> मध्ये जातात, म्हणजे नंतर पुन्हा सराव करता येतो.',
    tip4: 'शिक्षकांसाठी: या आठवड्याचे शब्द <b>शब्दयाद्या</b> मध्ये लिहा, प्रत्येक ओळीत एक. यादी किंवा उत्तरसूचीसह स्पेलिंग चाचणी प्रिंट करा, किंवा WhatsApp लिंकने विद्यार्थ्यांना पाठवा.',
    tip5: 'वर्गातील उपक्रम: प्रोजेक्टरवर <b>वर्ग स्पर्धा</b> उघडा, 2–4 गट करा आणि आळीपाळीने स्पेलिंग विचारा. मुले तोंडी स्पेलिंग सांगू शकतात आणि तुम्ही ✓ किंवा ✗ दाबा.',
    tip6: 'इंग्रजी आवाज नाही? ॲप अर्थ, रिकाम्या जागेचे वाक्य आणि उलटसुलट अक्षरे दाखवते, त्यामुळे मुले तरीही खेळू शकतात. Windows मध्ये Settings → Time &amp; language → Speech मध्ये जाऊन “English (India)” आवाज जोडा.',
    voice_h: 'आवाज', voice_lbl: 'इंग्रजी आवाज', voice_auto: 'आपोआप (आधी भारतीय इंग्रजी)', voice_using: 'आवाज:', voice_test: 'आवाज तपासा', speed: 'वेग',
    nv_title: 'या डिव्हाइसवर इंग्रजी आवाज नाही',
    nv_short: 'शब्द ओळखण्यासाठी अर्थ, वाक्य आणि उलटसुलट अक्षरांची मदत घ्या.',
    nv_help: 'तरीही खेळता येईल: अर्थ, वाक्य आणि उलटसुलट अक्षरे दाखवली जातात. Android वर Chrome मध्ये सहसा इंग्रजी आवाज असतो; संगणकावर स्पीच सेटिंग्जमध्ये “English (India)” जोडा.',
    stats_h: 'माझी प्रगती', st_words: 'प्रयत्न केलेले शब्द', st_acc: 'बरोबर', st_streak: 'सलग बरोबरचा विक्रम', st_review: 'पुन्हा सराव बाकी',
    reset_progress: 'प्रगती रीसेट करा', confirm_progress: 'तुमचे गुण आणि चुकांची यादी पुसायची? तुमची स्वतःची शब्दयादी राहील.', reset_done: 'प्रगती पुसली.',
    word_x_of_y: 'शब्द {i} / {n}', streak: 'सलग बरोबर उत्तरे', end_round: 'फेरी संपवा',
    hear_word: 'शब्द ऐका', hear_sent: 'वाक्यात ऐका', hear_slow: 'हळू ऐका',
    meaning: 'अर्थ', sentence_lbl: 'वाक्य', starts_with: 'पहिले अक्षर',
    hints: 'संकेत', hint_first: 'पहिले अक्षर', hint_len: 'किती अक्षरे', hint_jumble: 'उलटसुलट अक्षरे',
    hints_used_n: 'घेतलेले संकेत: {n}', hint_free: 'आवाज नसल्यास उलटसुलट अक्षरे मोफत.', letters_n: '{n} अक्षरे',
    jumble_aria: 'उलटसुलट अक्षरे, टाइप करण्यासाठी टॅप करा', tap_letter: '{l} लिहा', space_key: 'स्पेस',
    your_spelling: 'तुमचे स्पेलिंग', answer_ph: 'स्पेलिंग टाइप करा', backspace: 'शेवटचे अक्षर पुसा', check: 'तपासा', show_answer: 'उत्तर दाखवा',
    fb_empty: 'आधी स्पेलिंग टाइप करा.', fb_retry: 'जवळजवळ बरोबर! लाल अक्षरे दुरुस्त करा आणि पुन्हा एकदा प्रयत्न करा.', fb_missing: 'राहिलेली अक्षरे: {n}',
    lg_ok: 'बरोबर', lg_bad: 'चूक', lg_miss: 'राहिलेले',
    fb_ok: 'बरोबर! छान.', fb_ok2: 'दुसऱ्या प्रयत्नात बरोबर!',
    fb_alt: '“{alt}” हे अमेरिकन स्पेलिंग आहे. भारतात आपण सहसा “{w}” लिहितो.',
    fb_bad: 'या वेळी नाही. बरोबर स्पेलिंग:', fb_shown: 'हे आहे बरोबर स्पेलिंग:',
    you_wrote: 'तुम्ही लिहिले', right_spelling: 'बरोबर स्पेलिंग',
    fb_learn: 'पिवळी अक्षरे पाहा, तोच अवघड भाग आहे. शब्द उच्चारा आणि एकदा मोठ्याने स्पेलिंग सांगा.',
    next_word: 'पुढचा शब्द', see_result: 'माझे गुण पाहा',
    sum_title: 'फेरी पूर्ण!', sum_score: '{n} पैकी {c} बरोबर',
    praise_1: 'छान प्रयत्न! खालील शब्दांचा सराव करा आणि पुन्हा खेळा.', praise_2: 'शाब्बास! थोडा अजून सराव केला की सगळे बरोबर येतील.', praise_3: 'अप्रतिम स्पेलिंग!',
    sum_streak: 'सलग बरोबर: {n}', sum_hints: 'घेतलेले संकेत: {n}', new_best: 'नवा सर्वोत्तम स्कोअर!',
    sum_mistakes: 'सरावासाठी शब्द', sum_perfect: 'एकही चूक नाही, परिपूर्ण फेरी! 🎉',
    practise_these: 'या शब्दांचा सराव करा', new_round: 'नवी फेरी', change_level: 'स्तर बदला', listen_to: '{w} ऐका',
    bee_setup_h: 'वर्गात स्पेलिंग स्पर्धा',
    bee_help: 'हे प्रोजेक्टर किंवा स्मार्टबोर्डवर दाखवा. खेळाडू किंवा गट आळीपाळीने खेळतात: प्रत्येकजण एक शब्द ऐकून त्याचे स्पेलिंग टाइप करतो किंवा तोंडी सांगतो आणि शिक्षक निर्णय देतात.',
    players: 'खेळाडू किंवा गट', player_n: 'खेळाडू {n}', add_player: 'खेळाडू जोडा', remove_player: 'खेळाडू {n} काढा',
    level_lbl: 'शब्दांचा स्तर', per_player: 'प्रत्येक खेळाडूला किती शब्द', game_type: 'खेळ', type_points: 'गुण', type_ko: 'नॉक-आउट',
    type_points_help: 'सर्वांना सारखेच शब्द मिळतात. सर्वात जास्त बरोबर शब्द असलेला जिंकतो.',
    type_ko_help: 'प्रत्येक खेळाडूकडे 3 जीव असतात. चुकीच्या स्पेलिंगला एक जीव जातो; शेवटी उरलेला खेळाडू जिंकतो.',
    start_bee: 'स्पर्धा सुरू करा', bee_how_h: 'कशी घ्यायची',
    bee_step1: 'खेळाडूंची किंवा गटांची नावे लिहा आणि स्तर निवडा.',
    bee_step2: 'सुरू करा दाबा आणि पूर्ण स्क्रीन करा. ॲप शब्द मोठ्याने वाचते.',
    bee_step3: 'खेळाडू शब्द टाइप करतो, किंवा तोंडी स्पेलिंग सांगतो आणि तुम्ही ✓ किंवा ✗ दाबा.',
    bee_step4: 'सर्वांना बरोबर स्पेलिंग दिसते, मग पुढचा खेळाडू दाबा.',
    turn_of: '{name}, तुमची पाळी!', bee_round: 'शब्द {i} / {n}', judge_help: 'तोंडी स्पेलिंग सांगितले? शिक्षक, निर्णय द्या:', judge_ok: 'बरोबर', judge_bad: 'चूक',
    next_player: 'पुढचा खेळाडू', see_winner: 'विजेता पाहा', end_game: 'खेळ संपवा', confirm_end: 'खेळ आत्ताच संपवून गुण दाखवायचे?',
    lives_n: '{n} जीव बाकी', out: 'बाद', winner_is: '{name} जिंकले! 🎉', winners_tie: 'बरोबरी: {names}',
    final_note: 'प्रत्येक खेळाडूसाठी टाळ्या, आज सर्वांनी सराव केला!', col_player: 'खेळाडू', col_lives: 'जीव',
    play_again: 'पुन्हा खेळा', change_players: 'खेळाडू बदला',
    my_list_h: 'माझी शब्दयादी',
    my_list_help: 'शिक्षकांसाठी: इंग्रजी शब्द टाइप किंवा पेस्ट करा, प्रत्येक ओळीत एक. हवे असल्यास | चिन्हानंतर वाक्य आणि अर्थही लिहा.',
    format_lbl: 'पद्धत:', my_list_format: 'शब्द | वाक्य | अर्थ', words_box: 'शब्द',
    save_list: 'यादी सेव्ह करा', example_list: 'उदाहरण', share_list: 'लिंक शेअर करा',
    list_saved: '{n} शब्द सेव्ह झाले. सराव किंवा वर्ग स्पर्धेत “माझी यादी” निवडा.', list_skipped: '{n} ओळी वगळल्या: फक्त इंग्रजी अक्षरे वापरा.',
    list_empty: 'यादी रिकामी आहे. आधी काही शब्द लिहा.', list_cleared: 'यादी पुसली.', confirm_clear_list: 'तुमची शब्दयादी काढून टाकायची?', confirm_replace_list: 'यामुळे तुमची सध्याची शब्दयादी ({n} शब्द) बदलेल. पुढे जायचे?',
    share_done: 'लिंक कॉपी झाली! विद्यार्थ्यांना पाठवा: यादी त्यांच्या ब्राउझरमध्ये उघडेल.',
    wa_list: 'स्पेलिंग सराव: या आठवड्याचे {n} शब्द. इथे उघडा: {url}',
    shared_found: 'कोणीतरी तुमच्यासोबत {n} शब्दांची यादी शेअर केली आहे.', use_shared: 'ही यादी वापरा', wa_share: 'WhatsApp वर पाठवा',
    print_h: 'शब्दयाद्या पाहा आणि प्रिंट करा', print_list: 'शब्दयादी प्रिंट करा', print_test: 'स्पेलिंग चाचणी प्रिंट करा',
    col_word: 'शब्द', col_sentence: 'उदाहरण वाक्य', col_listen: 'ऐका',
    print_title: 'स्पेलिंग यादी: {level}', test_title: 'स्पेलिंग चाचणी: {level}',
    print_name: 'नाव', print_class: 'इयत्ता', print_date: 'दिनांक',
    test_instr: 'शिक्षकांचे लक्षपूर्वक ऐका आणि प्रत्येक शब्द लिहा. संकेत म्हणून अर्थ दिला आहे.', answer_key: 'उत्तरसूची (शिक्षकांसाठी)'
  }
  ,
  gu: {
    app_title: 'સ્પેલિંગ બી',
    intro: 'અંગ્રેજી શબ્દ સાંભળો અને તેનો સ્પેલિંગ લખો. તમારી ભાષામાં અર્થ જાણો, સંકેત લો, વર્ગમાં સ્પેલિંગ બી રમો અને સ્પેલિંગ ટેસ્ટ પ્રિન્ટ કરો.',
    tab_practise: 'મહાવરો', tab_bee: 'વર્ગ સ્પર્ધા', tab_lists: 'શબ્દ યાદીઓ',
    choose_level: 'સ્તર પસંદ કરો', level_n: 'સ્તર {n}', class_n: 'ધોરણ {n}', n_words: '{n} શબ્દ', best_n: 'શ્રેષ્ઠ {s}/{n}',
    my_list: 'મારી યાદી', review_lvl: 'મારી ભૂલો', review_none: 'હજી કોઈ ભૂલ નથી', custom_none: '“શબ્દ યાદીઓ”માં શબ્દ ઉમેરો',
    opt_second: 'બીજી તક આપો', opt_auto: 'દરેક શબ્દ આપમેળે બોલે', start_round: 'શરૂ કરો', round_info: 'આ રાઉન્ડમાં {n} શબ્દ',
    help_h: 'કેવી રીતે વાપરવું · વર્ગ માટે વિચારો',
    tip1: 'સ્તર પસંદ કરી <b>શરૂ કરો</b> દબાવો. શબ્દ સાંભળો 🔊, વાક્યમાં સાંભળો 💬 કે ધીમે સાંભળો 🐢. પછી સ્પેલિંગ ટાઇપ કરી <b>તપાસો</b> દબાવો (અથવા Enter).',
    tip2: 'અટકી ગયા? સંકેત લો: પહેલો અક્ષર, કેટલા અક્ષર, કે ગૂંચવાયેલા અક્ષર. ફોન કે સ્માર્ટબોર્ડ પર ટાઇપ કરવાને બદલે ગૂંચવાયેલા અક્ષરો પર ટૅપ કરો.',
    tip3: 'લીલા અક્ષર સાચા છે, લાલ અક્ષર સુધારવાના છે અને ટપકાંવાળું ખાનું એટલે કોઈ અક્ષર રહી ગયો. ખોટા પડેલા શબ્દો <b>મારી ભૂલો</b>માં જાય છે, જેથી પછી ફરી મહાવરો કરી શકો.',
    tip4: 'શિક્ષકો માટે: આ અઠવાડિયાના શબ્દો <b>શબ્દ યાદીઓ</b>માં લખો, દરેક લીટીમાં એક. યાદી કે જવાબ સાથેનો સ્પેલિંગ ટેસ્ટ પ્રિન્ટ કરો, અથવા WhatsApp લિંકથી વિદ્યાર્થીઓને મોકલો.',
    tip5: 'વર્ગ પ્રવૃત્તિ: પ્રોજેક્ટર પર <b>વર્ગ સ્પર્ધા</b> ખોલો, 2–4 ટીમ બનાવો અને વારાફરતી સ્પેલિંગ પૂછો. બાળકો બોલીને સ્પેલિંગ કહી શકે અને તમે ✓ કે ✗ દબાવો.',
    tip6: 'અંગ્રેજી અવાજ નથી? ઍપ અર્થ, ખાલી જગ્યાવાળું વાક્ય અને ગૂંચવાયેલા અક્ષરો બતાવે છે, એટલે બાળકો છતાં રમી શકે. Windows માં Settings → Time &amp; language → Speech માં જઈ “English (India)” અવાજ ઉમેરો.',
    voice_h: 'અવાજ', voice_lbl: 'અંગ્રેજી અવાજ', voice_auto: 'આપમેળે (પહેલાં ભારતીય અંગ્રેજી)', voice_using: 'અવાજ:', voice_test: 'અવાજ તપાસો', speed: 'ઝડપ',
    nv_title: 'આ ડિવાઇસ પર અંગ્રેજી અવાજ નથી',
    nv_short: 'શબ્દ શોધવા અર્થ, વાક્ય અને ગૂંચવાયેલા અક્ષરોની મદદ લો.',
    nv_help: 'છતાં રમી શકાય: અર્થ, વાક્ય અને ગૂંચવાયેલા અક્ષરો બતાવાશે. Android પર Chrome માં સામાન્ય રીતે અંગ્રેજી અવાજ હોય છે; કમ્પ્યુટર પર સ્પીચ સેટિંગ્સમાં “English (India)” ઉમેરો.',
    stats_h: 'મારી પ્રગતિ', st_words: 'પ્રયત્ન કરેલા શબ્દ', st_acc: 'સાચા', st_streak: 'સળંગ સાચાનો રેકોર્ડ', st_review: 'ફરી મહાવરો બાકી',
    reset_progress: 'પ્રગતિ રીસેટ કરો', confirm_progress: 'તમારો સ્કોર અને ભૂલોની યાદી ભૂંસી નાખવી છે? તમારી પોતાની શબ્દ યાદી રહેશે.', reset_done: 'પ્રગતિ ભૂંસાઈ ગઈ.',
    word_x_of_y: 'શબ્દ {i} / {n}', streak: 'સળંગ સાચા જવાબ', end_round: 'રાઉન્ડ પૂરો કરો',
    hear_word: 'શબ્દ સાંભળો', hear_sent: 'વાક્યમાં સાંભળો', hear_slow: 'ધીમે સાંભળો',
    meaning: 'અર્થ', sentence_lbl: 'વાક્ય', starts_with: 'પહેલો અક્ષર',
    hints: 'સંકેત', hint_first: 'પહેલો અક્ષર', hint_len: 'કેટલા અક્ષર', hint_jumble: 'ગૂંચવાયેલા અક્ષર',
    hints_used_n: 'લીધેલા સંકેત: {n}', hint_free: 'અવાજ ન હોય ત્યારે ગૂંચવાયેલા અક્ષર મફત છે.', letters_n: '{n} અક્ષર',
    jumble_aria: 'ગૂંચવાયેલા અક્ષર, ટાઇપ કરવા ટૅપ કરો', tap_letter: '{l} લખો', space_key: 'સ્પેસ',
    your_spelling: 'તમારો સ્પેલિંગ', answer_ph: 'સ્પેલિંગ ટાઇપ કરો', backspace: 'છેલ્લો અક્ષર ભૂંસો', check: 'તપાસો', show_answer: 'જવાબ બતાવો',
    fb_empty: 'પહેલાં સ્પેલિંગ ટાઇપ કરો.', fb_retry: 'લગભગ સાચું! લાલ અક્ષર સુધારો અને ફરી એક વાર પ્રયાસ કરો.', fb_missing: 'રહી ગયેલા અક્ષર: {n}',
    lg_ok: 'સાચો', lg_bad: 'ખોટો', lg_miss: 'રહી ગયેલો',
    fb_ok: 'સાચું! શાબાશ.', fb_ok2: 'બીજા પ્રયાસમાં સાચું!',
    fb_alt: '“{alt}” અમેરિકન સ્પેલિંગ છે. ભારતમાં આપણે સામાન્ય રીતે “{w}” લખીએ છીએ.',
    fb_bad: 'આ વખતે નહીં. સાચો સ્પેલિંગ છે:', fb_shown: 'આ રહ્યો સાચો સ્પેલિંગ:',
    you_wrote: 'તમે લખ્યું', right_spelling: 'સાચો સ્પેલિંગ',
    fb_learn: 'પીળા અક્ષર જુઓ, એ જ અઘરો ભાગ છે. શબ્દ બોલો અને એક વાર મોટેથી સ્પેલિંગ બોલો.',
    next_word: 'આગળનો શબ્દ', see_result: 'મારો સ્કોર જુઓ',
    sum_title: 'રાઉન્ડ પૂરો!', sum_score: '{n} માંથી {c} સાચા',
    praise_1: 'સારો પ્રયાસ! નીચેના શબ્દોનો મહાવરો કરી ફરી રમો.', praise_2: 'શાબાશ! થોડો વધુ મહાવરો કરશો તો બધા સાચા થશે.', praise_3: 'અદ્ભુત સ્પેલિંગ!',
    sum_streak: 'સળંગ સાચા: {n}', sum_hints: 'લીધેલા સંકેત: {n}', new_best: 'નવો શ્રેષ્ઠ સ્કોર!',
    sum_mistakes: 'મહાવરા માટેના શબ્દો', sum_perfect: 'એક પણ ભૂલ નહીં, સંપૂર્ણ રાઉન્ડ! 🎉',
    practise_these: 'આ શબ્દોનો મહાવરો કરો', new_round: 'નવો રાઉન્ડ', change_level: 'સ્તર બદલો', listen_to: '{w} સાંભળો',
    bee_setup_h: 'વર્ગમાં સ્પેલિંગ સ્પર્ધા',
    bee_help: 'આ પ્રોજેક્ટર કે સ્માર્ટબોર્ડ પર બતાવો. ખેલાડીઓ કે ટીમો વારાફરતી રમે છે: દરેક જણ એક શબ્દ સાંભળી સ્પેલિંગ ટાઇપ કરે અથવા બોલીને કહે, અને શિક્ષક નિર્ણય આપે.',
    players: 'ખેલાડીઓ કે ટીમો', player_n: 'ખેલાડી {n}', add_player: 'ખેલાડી ઉમેરો', remove_player: 'ખેલાડી {n} કાઢો',
    level_lbl: 'શબ્દોનું સ્તર', per_player: 'દરેક ખેલાડીને કેટલા શબ્દ', game_type: 'રમત', type_points: 'પોઇન્ટ', type_ko: 'નૉક-આઉટ',
    type_points_help: 'દરેકને સરખા શબ્દ મળે છે. સૌથી વધુ સાચા શબ્દવાળો જીતે છે.',
    type_ko_help: 'દરેક ખેલાડી પાસે 3 જીવ છે. ખોટા સ્પેલિંગ પર એક જીવ જાય; છેલ્લે બચેલો ખેલાડી જીતે.',
    start_bee: 'સ્પર્ધા શરૂ કરો', bee_how_h: 'કેવી રીતે ચલાવવી',
    bee_step1: 'ખેલાડીઓ કે ટીમોનાં નામ લખો અને સ્તર પસંદ કરો.',
    bee_step2: 'શરૂ કરો દબાવો અને પૂર્ણ સ્ક્રીન કરો. ઍપ શબ્દ બોલીને સંભળાવે છે.',
    bee_step3: 'ખેલાડી શબ્દ ટાઇપ કરે, અથવા બોલીને સ્પેલિંગ કહે અને તમે ✓ કે ✗ દબાવો.',
    bee_step4: 'બધા સાચો સ્પેલિંગ જુએ, પછી આગળનો ખેલાડી દબાવો.',
    turn_of: '{name}, તમારો વારો!', bee_round: 'શબ્દ {i} / {n}', judge_help: 'બોલીને સ્પેલિંગ કહ્યો? શિક્ષક, નિર્ણય આપો:', judge_ok: 'સાચો', judge_bad: 'ખોટો',
    next_player: 'આગળનો ખેલાડી', see_winner: 'વિજેતા જુઓ', end_game: 'રમત પૂરી કરો', confirm_end: 'રમત અત્યારે પૂરી કરીને સ્કોર બતાવવો છે?',
    lives_n: '{n} જીવ બાકી', out: 'આઉટ', winner_is: '{name} જીત્યા! 🎉', winners_tie: 'બરાબરી: {names}',
    final_note: 'દરેક ખેલાડી માટે તાળીઓ, આજે બધાએ મહાવરો કર્યો!', col_player: 'ખેલાડી', col_lives: 'જીવ',
    play_again: 'ફરી રમો', change_players: 'ખેલાડીઓ બદલો',
    my_list_h: 'મારી શબ્દ યાદી',
    my_list_help: 'શિક્ષકો માટે: અંગ્રેજી શબ્દો ટાઇપ કે પેસ્ટ કરો, દરેક લીટીમાં એક. ઇચ્છો તો | ચિહ્ન પછી વાક્ય અને અર્થ પણ લખો.',
    format_lbl: 'રીત:', my_list_format: 'શબ્દ | વાક્ય | અર્થ', words_box: 'શબ્દો',
    save_list: 'યાદી સેવ કરો', example_list: 'ઉદાહરણ', share_list: 'લિંક શેર કરો',
    list_saved: '{n} શબ્દ સેવ થયા. મહાવરો કે વર્ગ સ્પર્ધામાં “મારી યાદી” પસંદ કરો.', list_skipped: '{n} લીટીઓ છોડી દીધી: ફક્ત અંગ્રેજી અક્ષરો વાપરો.',
    list_empty: 'યાદી ખાલી છે. પહેલાં થોડા શબ્દો લખો.', list_cleared: 'યાદી ભૂંસાઈ ગઈ.', confirm_clear_list: 'તમારી શબ્દ યાદી કાઢી નાખવી છે?', confirm_replace_list: 'આથી તમારી હાલની શબ્દ યાદી ({n} શબ્દ) બદલાઈ જશે. આગળ વધવું છે?',
    share_done: 'લિંક કૉપિ થઈ ગઈ! વિદ્યાર્થીઓને મોકલો: યાદી તેમના બ્રાઉઝરમાં ખુલશે.',
    wa_list: 'સ્પેલિંગ મહાવરો: આ અઠવાડિયાના {n} શબ્દ. અહીં ખોલો: {url}',
    shared_found: 'કોઈએ તમારી સાથે {n} શબ્દોની યાદી શેર કરી છે.', use_shared: 'આ યાદી વાપરો', wa_share: 'WhatsApp પર મોકલો',
    print_h: 'શબ્દ યાદીઓ જુઓ અને પ્રિન્ટ કરો', print_list: 'શબ્દ યાદી પ્રિન્ટ કરો', print_test: 'સ્પેલિંગ ટેસ્ટ પ્રિન્ટ કરો',
    col_word: 'શબ્દ', col_sentence: 'ઉદાહરણ વાક્ય', col_listen: 'સાંભળો',
    print_title: 'સ્પેલિંગ યાદી: {level}', test_title: 'સ્પેલિંગ ટેસ્ટ: {level}',
    print_name: 'નામ', print_class: 'ધોરણ', print_date: 'તારીખ',
    test_instr: 'શિક્ષકને ધ્યાનથી સાંભળો અને દરેક શબ્દ લખો. સંકેત તરીકે અર્થ આપેલો છે.', answer_key: 'જવાબો (શિક્ષક માટે)'
  },
  pa: {
    app_title: 'ਸਪੈਲਿੰਗ ਬੀ',
    intro: 'ਅੰਗਰੇਜ਼ੀ ਸ਼ਬਦ ਸੁਣੋ ਅਤੇ ਉਸ ਦੇ ਸਪੈਲਿੰਗ ਲਿਖੋ। ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਅਰਥ ਜਾਣੋ, ਸੰਕੇਤ ਲਓ, ਜਮਾਤ ਵਿੱਚ ਸਪੈਲਿੰਗ ਬੀ ਖੇਡੋ ਅਤੇ ਸਪੈਲਿੰਗ ਟੈਸਟ ਪ੍ਰਿੰਟ ਕਰੋ।',
    tab_practise: 'ਅਭਿਆਸ', tab_bee: 'ਜਮਾਤ ਮੁਕਾਬਲਾ', tab_lists: 'ਸ਼ਬਦ ਸੂਚੀਆਂ',
    choose_level: 'ਪੱਧਰ ਚੁਣੋ', level_n: 'ਪੱਧਰ {n}', class_n: 'ਜਮਾਤ {n}', n_words: '{n} ਸ਼ਬਦ', best_n: 'ਸਭ ਤੋਂ ਵਧੀਆ {s}/{n}',
    my_list: 'ਮੇਰੀ ਸੂਚੀ', review_lvl: 'ਮੇਰੀਆਂ ਗ਼ਲਤੀਆਂ', review_none: 'ਹਾਲੇ ਕੋਈ ਗ਼ਲਤੀ ਨਹੀਂ', custom_none: '“ਸ਼ਬਦ ਸੂਚੀਆਂ” ਵਿੱਚ ਸ਼ਬਦ ਜੋੜੋ',
    opt_second: 'ਦੂਜਾ ਮੌਕਾ ਦਿਓ', opt_auto: 'ਹਰ ਸ਼ਬਦ ਆਪਣੇ ਆਪ ਬੋਲੇ', start_round: 'ਸ਼ੁਰੂ ਕਰੋ', round_info: 'ਇਸ ਗੇੜ ਵਿੱਚ {n} ਸ਼ਬਦ',
    help_h: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ · ਜਮਾਤ ਲਈ ਸੁਝਾਅ',
    tip1: 'ਪੱਧਰ ਚੁਣੋ ਅਤੇ <b>ਸ਼ੁਰੂ ਕਰੋ</b> ਦਬਾਓ। ਸ਼ਬਦ ਸੁਣੋ 🔊, ਵਾਕ ਵਿੱਚ ਸੁਣੋ 💬 ਜਾਂ ਹੌਲੀ ਸੁਣੋ 🐢। ਫਿਰ ਸਪੈਲਿੰਗ ਟਾਈਪ ਕਰੋ ਅਤੇ <b>ਜਾਂਚੋ</b> ਦਬਾਓ (ਜਾਂ Enter)।',
    tip2: 'ਅਟਕ ਗਏ? ਸੰਕੇਤ ਲਓ: ਪਹਿਲਾ ਅੱਖਰ, ਕਿੰਨੇ ਅੱਖਰ, ਜਾਂ ਉਲਝੇ ਅੱਖਰ। ਫ਼ੋਨ ਜਾਂ ਸਮਾਰਟਬੋਰਡ \'ਤੇ ਟਾਈਪ ਕਰਨ ਦੀ ਥਾਂ ਉਲਝੇ ਅੱਖਰਾਂ \'ਤੇ ਟੈਪ ਕਰੋ।',
    tip3: 'ਹਰੇ ਅੱਖਰ ਸਹੀ ਹਨ, ਲਾਲ ਅੱਖਰ ਠੀਕ ਕਰਨੇ ਹਨ ਅਤੇ ਬਿੰਦੀਆਂ ਵਾਲਾ ਡੱਬਾ ਮਤਲਬ ਕੋਈ ਅੱਖਰ ਰਹਿ ਗਿਆ। ਗ਼ਲਤ ਸ਼ਬਦ <b>ਮੇਰੀਆਂ ਗ਼ਲਤੀਆਂ</b> ਵਿੱਚ ਚਲੇ ਜਾਂਦੇ ਹਨ, ਤਾਂ ਜੋ ਬਾਅਦ ਵਿੱਚ ਫਿਰ ਅਭਿਆਸ ਕਰ ਸਕੋ।',
    tip4: 'ਅਧਿਆਪਕਾਂ ਲਈ: ਇਸ ਹਫ਼ਤੇ ਦੇ ਸ਼ਬਦ <b>ਸ਼ਬਦ ਸੂਚੀਆਂ</b> ਵਿੱਚ ਲਿਖੋ, ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ। ਸੂਚੀ ਜਾਂ ਉੱਤਰਾਂ ਵਾਲਾ ਸਪੈਲਿੰਗ ਟੈਸਟ ਪ੍ਰਿੰਟ ਕਰੋ, ਜਾਂ WhatsApp ਲਿੰਕ ਰਾਹੀਂ ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਭੇਜੋ।',
    tip5: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: ਪ੍ਰੋਜੈਕਟਰ \'ਤੇ <b>ਜਮਾਤ ਮੁਕਾਬਲਾ</b> ਖੋਲ੍ਹੋ, 2–4 ਟੀਮਾਂ ਬਣਾਓ ਅਤੇ ਵਾਰੀ-ਵਾਰੀ ਸਪੈਲਿੰਗ ਪੁੱਛੋ। ਬੱਚੇ ਬੋਲ ਕੇ ਸਪੈਲਿੰਗ ਦੱਸ ਸਕਦੇ ਹਨ ਅਤੇ ਤੁਸੀਂ ✓ ਜਾਂ ✗ ਦਬਾਓ।',
    tip6: 'ਅੰਗਰੇਜ਼ੀ ਆਵਾਜ਼ ਨਹੀਂ? ਐਪ ਅਰਥ, ਖ਼ਾਲੀ ਥਾਂ ਵਾਲਾ ਵਾਕ ਅਤੇ ਉਲਝੇ ਅੱਖਰ ਦਿਖਾਉਂਦੀ ਹੈ, ਇਸ ਲਈ ਬੱਚੇ ਫਿਰ ਵੀ ਖੇਡ ਸਕਦੇ ਹਨ। Windows ਵਿੱਚ Settings → Time &amp; language → Speech ਵਿੱਚ ਜਾ ਕੇ “English (India)” ਆਵਾਜ਼ ਜੋੜੋ।',
    voice_h: 'ਆਵਾਜ਼', voice_lbl: 'ਅੰਗਰੇਜ਼ੀ ਆਵਾਜ਼', voice_auto: 'ਆਪਣੇ ਆਪ (ਪਹਿਲਾਂ ਭਾਰਤੀ ਅੰਗਰੇਜ਼ੀ)', voice_using: 'ਆਵਾਜ਼:', voice_test: 'ਆਵਾਜ਼ ਜਾਂਚੋ', speed: 'ਰਫ਼ਤਾਰ',
    nv_title: 'ਇਸ ਡਿਵਾਈਸ \'ਤੇ ਅੰਗਰੇਜ਼ੀ ਆਵਾਜ਼ ਨਹੀਂ ਹੈ',
    nv_short: 'ਸ਼ਬਦ ਲੱਭਣ ਲਈ ਅਰਥ, ਵਾਕ ਅਤੇ ਉਲਝੇ ਅੱਖਰਾਂ ਦੀ ਮਦਦ ਲਓ।',
    nv_help: 'ਫਿਰ ਵੀ ਖੇਡ ਸਕਦੇ ਹੋ: ਅਰਥ, ਵਾਕ ਅਤੇ ਉਲਝੇ ਅੱਖਰ ਦਿਖਾਏ ਜਾਂਦੇ ਹਨ। Android \'ਤੇ Chrome ਵਿੱਚ ਆਮ ਤੌਰ \'ਤੇ ਅੰਗਰੇਜ਼ੀ ਆਵਾਜ਼ ਹੁੰਦੀ ਹੈ; ਕੰਪਿਊਟਰ \'ਤੇ ਸਪੀਚ ਸੈਟਿੰਗਾਂ ਵਿੱਚ “English (India)” ਜੋੜੋ।',
    stats_h: 'ਮੇਰੀ ਤਰੱਕੀ', st_words: 'ਕੋਸ਼ਿਸ਼ ਕੀਤੇ ਸ਼ਬਦ', st_acc: 'ਸਹੀ', st_streak: 'ਲਗਾਤਾਰ ਸਹੀ ਦਾ ਰਿਕਾਰਡ', st_review: 'ਮੁੜ ਅਭਿਆਸ ਬਾਕੀ',
    reset_progress: 'ਤਰੱਕੀ ਰੀਸੈੱਟ ਕਰੋ', confirm_progress: 'ਤੁਹਾਡੇ ਅੰਕ ਅਤੇ ਗ਼ਲਤੀਆਂ ਦੀ ਸੂਚੀ ਮਿਟਾ ਦੇਈਏ? ਤੁਹਾਡੀ ਆਪਣੀ ਸ਼ਬਦ ਸੂਚੀ ਬਣੀ ਰਹੇਗੀ।', reset_done: 'ਤਰੱਕੀ ਮਿਟਾ ਦਿੱਤੀ ਗਈ।',
    word_x_of_y: 'ਸ਼ਬਦ {i} / {n}', streak: 'ਲਗਾਤਾਰ ਸਹੀ ਜਵਾਬ', end_round: 'ਗੇੜ ਖ਼ਤਮ ਕਰੋ',
    hear_word: 'ਸ਼ਬਦ ਸੁਣੋ', hear_sent: 'ਵਾਕ ਵਿੱਚ ਸੁਣੋ', hear_slow: 'ਹੌਲੀ ਸੁਣੋ',
    meaning: 'ਅਰਥ', sentence_lbl: 'ਵਾਕ', starts_with: 'ਪਹਿਲਾ ਅੱਖਰ',
    hints: 'ਸੰਕੇਤ', hint_first: 'ਪਹਿਲਾ ਅੱਖਰ', hint_len: 'ਕਿੰਨੇ ਅੱਖਰ', hint_jumble: 'ਉਲਝੇ ਅੱਖਰ',
    hints_used_n: 'ਲਏ ਸੰਕੇਤ: {n}', hint_free: 'ਆਵਾਜ਼ ਨਾ ਹੋਣ \'ਤੇ ਉਲਝੇ ਅੱਖਰ ਮੁਫ਼ਤ ਹਨ।', letters_n: '{n} ਅੱਖਰ',
    jumble_aria: 'ਉਲਝੇ ਅੱਖਰ, ਟਾਈਪ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ', tap_letter: '{l} ਲਿਖੋ', space_key: 'ਸਪੇਸ',
    your_spelling: 'ਤੁਹਾਡੇ ਸਪੈਲਿੰਗ', answer_ph: 'ਸਪੈਲਿੰਗ ਟਾਈਪ ਕਰੋ', backspace: 'ਆਖ਼ਰੀ ਅੱਖਰ ਮਿਟਾਓ', check: 'ਜਾਂਚੋ', show_answer: 'ਉੱਤਰ ਦਿਖਾਓ',
    fb_empty: 'ਪਹਿਲਾਂ ਸਪੈਲਿੰਗ ਟਾਈਪ ਕਰੋ।', fb_retry: 'ਲਗਭਗ ਸਹੀ! ਲਾਲ ਅੱਖਰ ਠੀਕ ਕਰੋ ਅਤੇ ਇੱਕ ਵਾਰ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।', fb_missing: 'ਰਹਿ ਗਏ ਅੱਖਰ: {n}',
    lg_ok: 'ਸਹੀ', lg_bad: 'ਗ਼ਲਤ', lg_miss: 'ਰਹਿ ਗਿਆ',
    fb_ok: 'ਸਹੀ! ਬਹੁਤ ਵਧੀਆ।', fb_ok2: 'ਦੂਜੀ ਕੋਸ਼ਿਸ਼ ਵਿੱਚ ਸਹੀ!',
    fb_alt: '“{alt}” ਅਮਰੀਕੀ ਸਪੈਲਿੰਗ ਹੈ। ਭਾਰਤ ਵਿੱਚ ਅਸੀਂ ਆਮ ਤੌਰ \'ਤੇ “{w}” ਲਿਖਦੇ ਹਾਂ।',
    fb_bad: 'ਇਸ ਵਾਰ ਨਹੀਂ। ਸਹੀ ਸਪੈਲਿੰਗ ਹੈ:', fb_shown: 'ਇਹ ਰਹੇ ਸਹੀ ਸਪੈਲਿੰਗ:',
    you_wrote: 'ਤੁਸੀਂ ਲਿਖਿਆ', right_spelling: 'ਸਹੀ ਸਪੈਲਿੰਗ',
    fb_learn: 'ਪੀਲੇ ਅੱਖਰ ਵੇਖੋ, ਇਹੀ ਔਖਾ ਹਿੱਸਾ ਹੈ। ਸ਼ਬਦ ਬੋਲੋ ਅਤੇ ਇੱਕ ਵਾਰ ਉੱਚੀ ਸਪੈਲਿੰਗ ਬੋਲੋ।',
    next_word: 'ਅਗਲਾ ਸ਼ਬਦ', see_result: 'ਮੇਰੇ ਅੰਕ ਵੇਖੋ',
    sum_title: 'ਗੇੜ ਪੂਰਾ!', sum_score: '{n} ਵਿੱਚੋਂ {c} ਸਹੀ',
    praise_1: 'ਚੰਗੀ ਕੋਸ਼ਿਸ਼! ਹੇਠਲੇ ਸ਼ਬਦਾਂ ਦਾ ਅਭਿਆਸ ਕਰੋ ਅਤੇ ਫਿਰ ਖੇਡੋ।', praise_2: 'ਸ਼ਾਬਾਸ਼! ਥੋੜ੍ਹਾ ਹੋਰ ਅਭਿਆਸ ਅਤੇ ਸਭ ਸਹੀ ਹੋਣਗੇ।', praise_3: 'ਕਮਾਲ ਦੇ ਸਪੈਲਿੰਗ!',
    sum_streak: 'ਲਗਾਤਾਰ ਸਹੀ: {n}', sum_hints: 'ਲਏ ਸੰਕੇਤ: {n}', new_best: 'ਨਵਾਂ ਸਭ ਤੋਂ ਵਧੀਆ ਸਕੋਰ!',
    sum_mistakes: 'ਅਭਿਆਸ ਲਈ ਸ਼ਬਦ', sum_perfect: 'ਇੱਕ ਵੀ ਗ਼ਲਤੀ ਨਹੀਂ, ਪੂਰਾ ਗੇੜ ਸਹੀ! 🎉',
    practise_these: 'ਇਹਨਾਂ ਸ਼ਬਦਾਂ ਦਾ ਅਭਿਆਸ ਕਰੋ', new_round: 'ਨਵਾਂ ਗੇੜ', change_level: 'ਪੱਧਰ ਬਦਲੋ', listen_to: '{w} ਸੁਣੋ',
    bee_setup_h: 'ਜਮਾਤ ਵਿੱਚ ਸਪੈਲਿੰਗ ਮੁਕਾਬਲਾ',
    bee_help: 'ਇਸ ਨੂੰ ਪ੍ਰੋਜੈਕਟਰ ਜਾਂ ਸਮਾਰਟਬੋਰਡ \'ਤੇ ਦਿਖਾਓ। ਖਿਡਾਰੀ ਜਾਂ ਟੀਮਾਂ ਵਾਰੀ-ਵਾਰੀ ਖੇਡਦੀਆਂ ਹਨ: ਹਰ ਕੋਈ ਇੱਕ ਸ਼ਬਦ ਸੁਣ ਕੇ ਸਪੈਲਿੰਗ ਟਾਈਪ ਕਰਦਾ ਹੈ ਜਾਂ ਬੋਲ ਕੇ ਦੱਸਦਾ ਹੈ, ਅਤੇ ਅਧਿਆਪਕ ਫ਼ੈਸਲਾ ਕਰਦੇ ਹਨ।',
    players: 'ਖਿਡਾਰੀ ਜਾਂ ਟੀਮਾਂ', player_n: 'ਖਿਡਾਰੀ {n}', add_player: 'ਖਿਡਾਰੀ ਜੋੜੋ', remove_player: 'ਖਿਡਾਰੀ {n} ਹਟਾਓ',
    level_lbl: 'ਸ਼ਬਦਾਂ ਦਾ ਪੱਧਰ', per_player: 'ਹਰ ਖਿਡਾਰੀ ਲਈ ਸ਼ਬਦ', game_type: 'ਖੇਡ', type_points: 'ਅੰਕ', type_ko: 'ਨਾਕ-ਆਊਟ',
    type_points_help: 'ਹਰ ਕਿਸੇ ਨੂੰ ਬਰਾਬਰ ਸ਼ਬਦ ਮਿਲਦੇ ਹਨ। ਸਭ ਤੋਂ ਵੱਧ ਸਹੀ ਸ਼ਬਦਾਂ ਵਾਲਾ ਜਿੱਤਦਾ ਹੈ।',
    type_ko_help: 'ਹਰ ਖਿਡਾਰੀ ਕੋਲ 3 ਜਾਨਾਂ ਹਨ। ਗ਼ਲਤ ਸਪੈਲਿੰਗ \'ਤੇ ਇੱਕ ਜਾਨ ਜਾਂਦੀ ਹੈ; ਆਖ਼ਰ ਵਿੱਚ ਬਚਿਆ ਖਿਡਾਰੀ ਜਿੱਤਦਾ ਹੈ।',
    start_bee: 'ਮੁਕਾਬਲਾ ਸ਼ੁਰੂ ਕਰੋ', bee_how_h: 'ਕਿਵੇਂ ਚਲਾਉਣਾ ਹੈ',
    bee_step1: 'ਖਿਡਾਰੀਆਂ ਜਾਂ ਟੀਮਾਂ ਦੇ ਨਾਂ ਲਿਖੋ ਅਤੇ ਪੱਧਰ ਚੁਣੋ।',
    bee_step2: 'ਸ਼ੁਰੂ ਕਰੋ ਦਬਾਓ ਅਤੇ ਪੂਰੀ ਸਕ੍ਰੀਨ ਕਰੋ। ਐਪ ਸ਼ਬਦ ਬੋਲ ਕੇ ਸੁਣਾਉਂਦੀ ਹੈ।',
    bee_step3: 'ਖਿਡਾਰੀ ਸ਼ਬਦ ਟਾਈਪ ਕਰੇ, ਜਾਂ ਬੋਲ ਕੇ ਸਪੈਲਿੰਗ ਦੱਸੇ ਅਤੇ ਤੁਸੀਂ ✓ ਜਾਂ ✗ ਦਬਾਓ।',
    bee_step4: 'ਸਭ ਸਹੀ ਸਪੈਲਿੰਗ ਵੇਖਦੇ ਹਨ, ਫਿਰ ਅਗਲਾ ਖਿਡਾਰੀ ਦਬਾਓ।',
    turn_of: '{name}, ਤੁਹਾਡੀ ਵਾਰੀ!', bee_round: 'ਸ਼ਬਦ {i} / {n}', judge_help: 'ਬੋਲ ਕੇ ਸਪੈਲਿੰਗ ਦੱਸੇ? ਅਧਿਆਪਕ, ਫ਼ੈਸਲਾ ਕਰੋ:', judge_ok: 'ਸਹੀ', judge_bad: 'ਗ਼ਲਤ',
    next_player: 'ਅਗਲਾ ਖਿਡਾਰੀ', see_winner: 'ਜੇਤੂ ਵੇਖੋ', end_game: 'ਖੇਡ ਖ਼ਤਮ ਕਰੋ', confirm_end: 'ਖੇਡ ਹੁਣੇ ਖ਼ਤਮ ਕਰਕੇ ਅੰਕ ਦਿਖਾਈਏ?',
    lives_n: '{n} ਜਾਨਾਂ ਬਾਕੀ', out: 'ਆਊਟ', winner_is: '{name} ਜਿੱਤ ਗਏ! 🎉', winners_tie: 'ਬਰਾਬਰੀ: {names}',
    final_note: 'ਹਰ ਖਿਡਾਰੀ ਲਈ ਤਾੜੀਆਂ, ਅੱਜ ਸਭ ਨੇ ਅਭਿਆਸ ਕੀਤਾ!', col_player: 'ਖਿਡਾਰੀ', col_lives: 'ਜਾਨਾਂ',
    play_again: 'ਫਿਰ ਖੇਡੋ', change_players: 'ਖਿਡਾਰੀ ਬਦਲੋ',
    my_list_h: 'ਮੇਰੀ ਸ਼ਬਦ ਸੂਚੀ',
    my_list_help: 'ਅਧਿਆਪਕਾਂ ਲਈ: ਅੰਗਰੇਜ਼ੀ ਸ਼ਬਦ ਟਾਈਪ ਜਾਂ ਪੇਸਟ ਕਰੋ, ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ। ਚਾਹੋ ਤਾਂ | ਨਿਸ਼ਾਨ ਤੋਂ ਬਾਅਦ ਵਾਕ ਅਤੇ ਅਰਥ ਵੀ ਲਿਖੋ।',
    format_lbl: 'ਤਰੀਕਾ:', my_list_format: 'ਸ਼ਬਦ | ਵਾਕ | ਅਰਥ', words_box: 'ਸ਼ਬਦ',
    save_list: 'ਸੂਚੀ ਸੇਵ ਕਰੋ', example_list: 'ਉਦਾਹਰਨ', share_list: 'ਲਿੰਕ ਸਾਂਝਾ ਕਰੋ',
    list_saved: '{n} ਸ਼ਬਦ ਸੇਵ ਹੋਏ। ਅਭਿਆਸ ਜਾਂ ਜਮਾਤ ਮੁਕਾਬਲੇ ਵਿੱਚ “ਮੇਰੀ ਸੂਚੀ” ਚੁਣੋ।', list_skipped: '{n} ਲਾਈਨਾਂ ਛੱਡ ਦਿੱਤੀਆਂ: ਸਿਰਫ਼ ਅੰਗਰੇਜ਼ੀ ਅੱਖਰ ਵਰਤੋ।',
    list_empty: 'ਸੂਚੀ ਖ਼ਾਲੀ ਹੈ। ਪਹਿਲਾਂ ਕੁਝ ਸ਼ਬਦ ਲਿਖੋ।', list_cleared: 'ਸੂਚੀ ਮਿਟਾ ਦਿੱਤੀ ਗਈ।', confirm_clear_list: 'ਆਪਣੀ ਸ਼ਬਦ ਸੂਚੀ ਮਿਟਾ ਦੇਈਏ?', confirm_replace_list: 'ਇਸ ਨਾਲ ਤੁਹਾਡੀ ਹੁਣ ਵਾਲੀ ਸ਼ਬਦ ਸੂਚੀ ({n} ਸ਼ਬਦ) ਬਦਲ ਜਾਵੇਗੀ। ਅੱਗੇ ਵਧੀਏ?',
    share_done: 'ਲਿੰਕ ਕਾਪੀ ਹੋ ਗਿਆ! ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਭੇਜੋ: ਸੂਚੀ ਉਹਨਾਂ ਦੇ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਖੁੱਲ੍ਹ ਜਾਵੇਗੀ।',
    wa_list: 'ਸਪੈਲਿੰਗ ਅਭਿਆਸ: ਇਸ ਹਫ਼ਤੇ ਦੇ {n} ਸ਼ਬਦ। ਇੱਥੇ ਖੋਲ੍ਹੋ: {url}',
    shared_found: 'ਕਿਸੇ ਨੇ ਤੁਹਾਡੇ ਨਾਲ {n} ਸ਼ਬਦਾਂ ਦੀ ਸੂਚੀ ਸਾਂਝੀ ਕੀਤੀ ਹੈ।', use_shared: 'ਇਹ ਸੂਚੀ ਵਰਤੋ', wa_share: 'WhatsApp \'ਤੇ ਭੇਜੋ',
    print_h: 'ਸ਼ਬਦ ਸੂਚੀਆਂ ਵੇਖੋ ਅਤੇ ਪ੍ਰਿੰਟ ਕਰੋ', print_list: 'ਸ਼ਬਦ ਸੂਚੀ ਪ੍ਰਿੰਟ ਕਰੋ', print_test: 'ਸਪੈਲਿੰਗ ਟੈਸਟ ਪ੍ਰਿੰਟ ਕਰੋ',
    col_word: 'ਸ਼ਬਦ', col_sentence: 'ਉਦਾਹਰਨ ਵਾਕ', col_listen: 'ਸੁਣੋ',
    print_title: 'ਸਪੈਲਿੰਗ ਸੂਚੀ: {level}', test_title: 'ਸਪੈਲਿੰਗ ਟੈਸਟ: {level}',
    print_name: 'ਨਾਂ', print_class: 'ਜਮਾਤ', print_date: 'ਤਾਰੀਖ਼',
    test_instr: 'ਅਧਿਆਪਕ ਨੂੰ ਧਿਆਨ ਨਾਲ ਸੁਣੋ ਅਤੇ ਹਰ ਸ਼ਬਦ ਲਿਖੋ। ਸੰਕੇਤ ਲਈ ਅਰਥ ਦਿੱਤਾ ਗਿਆ ਹੈ।', answer_key: 'ਉੱਤਰ ਕੁੰਜੀ (ਅਧਿਆਪਕ ਲਈ)'
  }
  ,
  or: {
    app_title: 'ସ୍ପେଲିଂ ବି',
    intro: 'ଇଂରାଜୀ ଶବ୍ଦ ଶୁଣନ୍ତୁ ଏବଂ ତାହାର ବନାନ ଲେଖନ୍ତୁ। ନିଜ ଭାଷାରେ ଅର୍ଥ ଜାଣନ୍ତୁ, ସଙ୍କେତ ନିଅନ୍ତୁ, ଶ୍ରେଣୀରେ ସ୍ପେଲିଂ ବି ଖେଳନ୍ତୁ ଏବଂ ବନାନ ପରୀକ୍ଷା ପ୍ରିଣ୍ଟ କରନ୍ତୁ।',
    tab_practise: 'ଅଭ୍ୟାସ', tab_bee: 'ଶ୍ରେଣୀ ପ୍ରତିଯୋଗିତା', tab_lists: 'ଶବ୍ଦ ତାଲିକା',
    choose_level: 'ସ୍ତର ବାଛନ୍ତୁ', level_n: 'ସ୍ତର {n}', class_n: 'ଶ୍ରେଣୀ {n}', n_words: '{n}ଟି ଶବ୍ଦ', best_n: 'ସର୍ବୋତ୍ତମ {s}/{n}',
    my_list: 'ମୋ ତାଲିକା', review_lvl: 'ମୋ ଭୁଲଗୁଡ଼ିକ', review_none: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଭୁଲ୍ ନାହିଁ', custom_none: '“ଶବ୍ଦ ତାଲିକା”ରେ ଶବ୍ଦ ଯୋଡ଼ନ୍ତୁ',
    opt_second: 'ଦ୍ୱିତୀୟ ସୁଯୋଗ ଦିଅନ୍ତୁ', opt_auto: 'ପ୍ରତ୍ୟେକ ଶବ୍ଦ ନିଜେ ନିଜେ କହିବ', start_round: 'ଆରମ୍ଭ କରନ୍ତୁ', round_info: 'ଏହି ରାଉଣ୍ଡରେ {n}ଟି ଶବ୍ଦ',
    help_h: 'କିପରି ବ୍ୟବହାର କରିବେ · ଶ୍ରେଣୀ ପାଇଁ ପରାମର୍ଶ',
    tip1: 'ସ୍ତର ବାଛି <b>ଆରମ୍ଭ କରନ୍ତୁ</b> ଦବାନ୍ତୁ। ଶବ୍ଦ ଶୁଣନ୍ତୁ 🔊, ବାକ୍ୟରେ ଶୁଣନ୍ତୁ 💬 କିମ୍ବା ଧୀରେ ଶୁଣନ୍ତୁ 🐢। ତା’ପରେ ବନାନ ଟାଇପ୍ କରି <b>ଯାଞ୍ଚ କରନ୍ତୁ</b> ଦବାନ୍ତୁ (କିମ୍ବା Enter)।',
    tip2: 'ଅଟକି ଗଲେ? ସଙ୍କେତ ନିଅନ୍ତୁ: ପ୍ରଥମ ଅକ୍ଷର, କେତୋଟି ଅକ୍ଷର, କିମ୍ବା ଏଲୋମେଲୋ ଅକ୍ଷର। ଫୋନ୍ କିମ୍ବା ସ୍ମାର୍ଟବୋର୍ଡରେ ଟାଇପ୍ ବଦଳରେ ଏଲୋମେଲୋ ଅକ୍ଷରରେ ଟାପ୍ କରନ୍ତୁ।',
    tip3: 'ସବୁଜ ଅକ୍ଷର ଠିକ୍, ନାଲି ଅକ୍ଷର ସୁଧାରିବାକୁ ହେବ ଏବଂ ବିନ୍ଦୁ-ଧାଡ଼ି ବାକ୍ସର ଅର୍ଥ ଗୋଟିଏ ଅକ୍ଷର ଛାଡ଼ି ଯାଇଛି। ଭୁଲ୍ ହୋଇଥିବା ଶବ୍ଦ <b>ମୋ ଭୁଲଗୁଡ଼ିକ</b>ରେ ଯାଏ, ଯେପରି ପରେ ପୁଣି ଅଭ୍ୟାସ କରିପାରିବେ।',
    tip4: 'ଶିକ୍ଷକଙ୍କ ପାଇଁ: ଏହି ସପ୍ତାହର ଶବ୍ଦ <b>ଶବ୍ଦ ତାଲିକା</b>ରେ ଲେଖନ୍ତୁ, ପ୍ରତି ଧାଡ଼ିରେ ଗୋଟିଏ। ତାଲିକା କିମ୍ବା ଉତ୍ତର ସହ ବନାନ ପରୀକ୍ଷା ପ୍ରିଣ୍ଟ କରନ୍ତୁ, କିମ୍ବା WhatsApp ଲିଙ୍କରେ ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ପଠାନ୍ତୁ।',
    tip5: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ: ପ୍ରୋଜେକ୍ଟରରେ <b>ଶ୍ରେଣୀ ପ୍ରତିଯୋଗିତା</b> ଖୋଲନ୍ତୁ, 2–4ଟି ଦଳ କରନ୍ତୁ ଏବଂ ପାଳି କରି ବନାନ ପଚାରନ୍ତୁ। ପିଲାମାନେ ମୁହଁରେ ବନାନ କହିପାରିବେ ଏବଂ ଆପଣ ✓ କିମ୍ବା ✗ ଦବାନ୍ତୁ।',
    tip6: 'ଇଂରାଜୀ ସ୍ୱର ନାହିଁ? ଆପ୍ ଅର୍ଥ, ଖାଲି ସ୍ଥାନ ଥିବା ବାକ୍ୟ ଓ ଏଲୋମେଲୋ ଅକ୍ଷର ଦେଖାଏ, ତେଣୁ ପିଲାମାନେ ତଥାପି ଖେଳିପାରିବେ। Windows ରେ Settings → Time &amp; language → Speech ରେ ଯାଇ “English (India)” ସ୍ୱର ଯୋଡ଼ନ୍ତୁ।',
    voice_h: 'ସ୍ୱର', voice_lbl: 'ଇଂରାଜୀ ସ୍ୱର', voice_auto: 'ସ୍ୱୟଂଚାଳିତ (ପ୍ରଥମେ ଭାରତୀୟ ଇଂରାଜୀ)', voice_using: 'ସ୍ୱର:', voice_test: 'ସ୍ୱର ଯାଞ୍ଚ କରନ୍ତୁ', speed: 'ଗତି',
    nv_title: 'ଏହି ଡିଭାଇସରେ ଇଂରାଜୀ ସ୍ୱର ନାହିଁ',
    nv_short: 'ଶବ୍ଦଟି ଖୋଜିବା ପାଇଁ ଅର୍ଥ, ବାକ୍ୟ ଓ ଏଲୋମେଲୋ ଅକ୍ଷରର ସାହାଯ୍ୟ ନିଅନ୍ତୁ।',
    nv_help: 'ତଥାପି ଖେଳିହେବ: ଅର୍ଥ, ବାକ୍ୟ ଓ ଏଲୋମେଲୋ ଅକ୍ଷର ଦେଖାଯିବ। Android ରେ Chrome ରେ ସାଧାରଣତଃ ଇଂରାଜୀ ସ୍ୱର ଥାଏ; କମ୍ପ୍ୟୁଟରରେ ସ୍ପିଚ୍ ସେଟିଂସରେ “English (India)” ଯୋଡ଼ନ୍ତୁ।',
    stats_h: 'ମୋ ପ୍ରଗତି', st_words: 'ଚେଷ୍ଟା କରିଥିବା ଶବ୍ଦ', st_acc: 'ଠିକ୍', st_streak: 'ଲଗାତାର ଠିକ୍‌ର ରେକର୍ଡ', st_review: 'ପୁଣି ଅଭ୍ୟାସ ବାକି',
    reset_progress: 'ପ୍ରଗତି ରିସେଟ୍ କରନ୍ତୁ', confirm_progress: 'ଆପଣଙ୍କ ସ୍କୋର ଓ ଭୁଲ ତାଲିକା ଲିଭାଇବେ? ଆପଣଙ୍କ ନିଜ ଶବ୍ଦ ତାଲିକା ରହିବ।', reset_done: 'ପ୍ରଗତି ଲିଭାଗଲା।',
    word_x_of_y: 'ଶବ୍ଦ {i} / {n}', streak: 'ଲଗାତାର ଠିକ୍ ଉତ୍ତର', end_round: 'ରାଉଣ୍ଡ ଶେଷ କରନ୍ତୁ',
    hear_word: 'ଶବ୍ଦ ଶୁଣନ୍ତୁ', hear_sent: 'ବାକ୍ୟରେ ଶୁଣନ୍ତୁ', hear_slow: 'ଧୀରେ ଶୁଣନ୍ତୁ',
    meaning: 'ଅର୍ଥ', sentence_lbl: 'ବାକ୍ୟ', starts_with: 'ପ୍ରଥମ ଅକ୍ଷର',
    hints: 'ସଙ୍କେତ', hint_first: 'ପ୍ରଥମ ଅକ୍ଷର', hint_len: 'କେତୋଟି ଅକ୍ଷର', hint_jumble: 'ଏଲୋମେଲୋ ଅକ୍ଷର',
    hints_used_n: 'ନିଆଯାଇଥିବା ସଙ୍କେତ: {n}', hint_free: 'ସ୍ୱର ନ ଥିଲେ ଏଲୋମେଲୋ ଅକ୍ଷର ମାଗଣା।', letters_n: '{n}ଟି ଅକ୍ଷର',
    jumble_aria: 'ଏଲୋମେଲୋ ଅକ୍ଷର, ଟାଇପ୍ ପାଇଁ ଟାପ୍ କରନ୍ତୁ', tap_letter: '{l} ଲେଖନ୍ତୁ', space_key: 'ସ୍ପେସ୍',
    your_spelling: 'ଆପଣଙ୍କ ବନାନ', answer_ph: 'ବନାନ ଟାଇପ୍ କରନ୍ତୁ', backspace: 'ଶେଷ ଅକ୍ଷର ଲିଭାନ୍ତୁ', check: 'ଯାଞ୍ଚ କରନ୍ତୁ', show_answer: 'ଉତ୍ତର ଦେଖାନ୍ତୁ',
    fb_empty: 'ପ୍ରଥମେ ବନାନ ଟାଇପ୍ କରନ୍ତୁ।', fb_retry: 'ପ୍ରାୟ ଠିକ୍! ନାଲି ଅକ୍ଷର ସୁଧାରି ଆଉ ଥରେ ଚେଷ୍ଟା କରନ୍ତୁ।', fb_missing: 'ଛାଡ଼ି ଯାଇଥିବା ଅକ୍ଷର: {n}',
    lg_ok: 'ଠିକ୍', lg_bad: 'ଭୁଲ୍', lg_miss: 'ଛାଡ଼ିଯାଇଛି',
    fb_ok: 'ଠିକ୍! ବହୁତ ଭଲ।', fb_ok2: 'ଦ୍ୱିତୀୟ ଚେଷ୍ଟାରେ ଠିକ୍!',
    fb_alt: '“{alt}” ଆମେରିକୀୟ ବନାନ। ଭାରତରେ ଆମେ ସାଧାରଣତଃ “{w}” ଲେଖୁ।',
    fb_bad: 'ଏଥର ନୁହେଁ। ଠିକ୍ ବନାନ ହେଲା:', fb_shown: 'ଏହା ହେଉଛି ଠିକ୍ ବନାନ:',
    you_wrote: 'ଆପଣ ଲେଖିଲେ', right_spelling: 'ଠିକ୍ ବନାନ',
    fb_learn: 'ହଳଦିଆ ଅକ୍ଷରଗୁଡ଼ିକ ଦେଖନ୍ତୁ, ଏହା ହିଁ କଠିନ ଅଂଶ। ଶବ୍ଦଟି କୁହନ୍ତୁ ଏବଂ ଥରେ ଜୋରରେ ବନାନ କୁହନ୍ତୁ।',
    next_word: 'ପରବର୍ତ୍ତୀ ଶବ୍ଦ', see_result: 'ମୋ ସ୍କୋର ଦେଖନ୍ତୁ',
    sum_title: 'ରାଉଣ୍ଡ ଶେଷ!', sum_score: '{n}ରୁ {c}ଟି ଠିକ୍',
    praise_1: 'ଭଲ ଚେଷ୍ଟା! ତଳ ଶବ୍ଦଗୁଡ଼ିକ ଅଭ୍ୟାସ କରି ପୁଣି ଖେଳନ୍ତୁ।', praise_2: 'ସାବାସ୍! ଆଉ ଟିକେ ଅଭ୍ୟାସ କଲେ ସବୁ ଠିକ୍ ହେବ।', praise_3: 'ଚମତ୍କାର ବନାନ!',
    sum_streak: 'ଲଗାତାର ଠିକ୍: {n}', sum_hints: 'ନିଆଯାଇଥିବା ସଙ୍କେତ: {n}', new_best: 'ନୂଆ ସର୍ବୋତ୍ତମ ସ୍କୋର!',
    sum_mistakes: 'ଅଭ୍ୟାସ ପାଇଁ ଶବ୍ଦ', sum_perfect: 'ଗୋଟିଏ ବି ଭୁଲ୍ ନାହିଁ, ସମ୍ପୂର୍ଣ୍ଣ ରାଉଣ୍ଡ! 🎉',
    practise_these: 'ଏହି ଶବ୍ଦଗୁଡ଼ିକ ଅଭ୍ୟାସ କରନ୍ତୁ', new_round: 'ନୂଆ ରାଉଣ୍ଡ', change_level: 'ସ୍ତର ବଦଳାନ୍ତୁ', listen_to: '{w} ଶୁଣନ୍ତୁ',
    bee_setup_h: 'ଶ୍ରେଣୀରେ ବନାନ ପ୍ରତିଯୋଗିତା',
    bee_help: 'ଏହାକୁ ପ୍ରୋଜେକ୍ଟର କିମ୍ବା ସ୍ମାର୍ଟବୋର୍ଡରେ ଦେଖାନ୍ତୁ। ଖେଳାଳି କିମ୍ବା ଦଳ ପାଳି କରି ଖେଳନ୍ତି: ପ୍ରତ୍ୟେକ ଗୋଟିଏ ଶବ୍ଦ ଶୁଣି ବନାନ ଟାଇପ୍ କରନ୍ତି କିମ୍ବା ମୁହଁରେ କହନ୍ତି, ଏବଂ ଶିକ୍ଷକ ବିଚାର କରନ୍ତି।',
    players: 'ଖେଳାଳି କିମ୍ବା ଦଳ', player_n: 'ଖେଳାଳି {n}', add_player: 'ଖେଳାଳି ଯୋଡ଼ନ୍ତୁ', remove_player: 'ଖେଳାଳି {n}ଙ୍କୁ ହଟାନ୍ତୁ',
    level_lbl: 'ଶବ୍ଦର ସ୍ତର', per_player: 'ପ୍ରତ୍ୟେକ ଖେଳାଳିଙ୍କ ପାଇଁ ଶବ୍ଦ', game_type: 'ଖେଳ', type_points: 'ପଏଣ୍ଟ', type_ko: 'ନକ୍-ଆଉଟ୍',
    type_points_help: 'ସମସ୍ତେ ସମାନ ସଂଖ୍ୟକ ଶବ୍ଦ ପାଆନ୍ତି। ସବୁଠୁ ଅଧିକ ଠିକ୍ ଶବ୍ଦ ଥିବା ଜିତେ।',
    type_ko_help: 'ପ୍ରତ୍ୟେକ ଖେଳାଳିଙ୍କର 3ଟି ଜୀବନ। ଭୁଲ୍ ବନାନରେ ଗୋଟିଏ ଜୀବନ ଯାଏ; ଶେଷରେ ରହିଥିବା ଖେଳାଳି ଜିତେ।',
    start_bee: 'ପ୍ରତିଯୋଗିତା ଆରମ୍ଭ କରନ୍ତୁ', bee_how_h: 'କିପରି ଚଳାଇବେ',
    bee_step1: 'ଖେଳାଳି କିମ୍ବା ଦଳର ନାମ ଲେଖନ୍ତୁ ଏବଂ ସ୍ତର ବାଛନ୍ତୁ।',
    bee_step2: 'ଆରମ୍ଭ ଦବାନ୍ତୁ ଏବଂ ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍ କରନ୍ତୁ। ଆପ୍ ଶବ୍ଦଟି ପଢ଼ି ଶୁଣାଏ।',
    bee_step3: 'ଖେଳାଳି ଶବ୍ଦ ଟାଇପ୍ କରନ୍ତି, କିମ୍ବା ମୁହଁରେ ବନାନ କହନ୍ତି ଏବଂ ଆପଣ ✓ କିମ୍ବା ✗ ଦବାନ୍ତୁ।',
    bee_step4: 'ସମସ୍ତେ ଠିକ୍ ବନାନ ଦେଖନ୍ତି, ତା’ପରେ ପରବର୍ତ୍ତୀ ଖେଳାଳି ଦବାନ୍ତୁ।',
    turn_of: '{name}, ଆପଣଙ୍କ ପାଳି!', bee_round: 'ଶବ୍ଦ {i} / {n}', judge_help: 'ମୁହଁରେ ବନାନ କହିଲେ? ଶିକ୍ଷକ, ବିଚାର କରନ୍ତୁ:', judge_ok: 'ଠିକ୍', judge_bad: 'ଭୁଲ୍',
    next_player: 'ପରବର୍ତ୍ତୀ ଖେଳାଳି', see_winner: 'ବିଜେତା ଦେଖନ୍ତୁ', end_game: 'ଖେଳ ଶେଷ କରନ୍ତୁ', confirm_end: 'ଖେଳ ଏବେ ଶେଷ କରି ସ୍କୋର ଦେଖାଇବେ?',
    lives_n: '{n}ଟି ଜୀବନ ବାକି', out: 'ଆଉଟ୍', winner_is: '{name} ଜିତିଲେ! 🎉', winners_tie: 'ସମାନ ସମାନ: {names}',
    final_note: 'ପ୍ରତ୍ୟେକ ଖେଳାଳିଙ୍କ ପାଇଁ ତାଳି, ଆଜି ସମସ୍ତେ ଅଭ୍ୟାସ କଲେ!', col_player: 'ଖେଳାଳି', col_lives: 'ଜୀବନ',
    play_again: 'ପୁଣି ଖେଳନ୍ତୁ', change_players: 'ଖେଳାଳି ବଦଳାନ୍ତୁ',
    my_list_h: 'ମୋ ଶବ୍ଦ ତାଲିକା',
    my_list_help: 'ଶିକ୍ଷକଙ୍କ ପାଇଁ: ଇଂରାଜୀ ଶବ୍ଦ ଟାଇପ୍ କିମ୍ବା ପେଷ୍ଟ କରନ୍ତୁ, ପ୍ରତି ଧାଡ଼ିରେ ଗୋଟିଏ। ଚାହିଁଲେ | ଚିହ୍ନ ପରେ ବାକ୍ୟ ଓ ଅର୍ଥ ମଧ୍ୟ ଲେଖନ୍ତୁ।',
    format_lbl: 'ନିୟମ:', my_list_format: 'ଶବ୍ଦ | ବାକ୍ୟ | ଅର୍ଥ', words_box: 'ଶବ୍ଦଗୁଡ଼ିକ',
    save_list: 'ତାଲିକା ସେଭ୍ କରନ୍ତୁ', example_list: 'ଉଦାହରଣ', share_list: 'ଲିଙ୍କ ସେୟାର୍ କରନ୍ତୁ',
    list_saved: '{n}ଟି ଶବ୍ଦ ସେଭ୍ ହେଲା। ଅଭ୍ୟାସ କିମ୍ବା ଶ୍ରେଣୀ ପ୍ରତିଯୋଗିତାରେ “ମୋ ତାଲିକା” ବାଛନ୍ତୁ।', list_skipped: '{n}ଟି ଧାଡ଼ି ଛାଡ଼ି ଦିଆଗଲା: କେବଳ ଇଂରାଜୀ ଅକ୍ଷର ବ୍ୟବହାର କରନ୍ତୁ।',
    list_empty: 'ତାଲିକା ଖାଲି ଅଛି। ପ୍ରଥମେ କିଛି ଶବ୍ଦ ଲେଖନ୍ତୁ।', list_cleared: 'ତାଲିକା ଲିଭାଗଲା।', confirm_clear_list: 'ଆପଣଙ୍କ ଶବ୍ଦ ତାଲିକା ବିଲୋପ କରିବେ?', confirm_replace_list: 'ଏହା ଆପଣଙ୍କ ବର୍ତ୍ତମାନର {n}ଟି ଶବ୍ଦର ତାଲିକାକୁ ବଦଳାଇଦେବ। ଆଗକୁ ବଢ଼ିବେ?',
    share_done: 'ଲିଙ୍କ କପି ହେଲା! ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ପଠାନ୍ତୁ: ତାଲିକା ସେମାନଙ୍କ ବ୍ରାଉଜରରେ ଖୋଲିବ।',
    wa_list: 'ବନାନ ଅଭ୍ୟାସ: ଏହି ସପ୍ତାହର {n}ଟି ଶବ୍ଦ। ଏଠାରେ ଖୋଲନ୍ତୁ: {url}',
    shared_found: 'କେହି ଆପଣଙ୍କ ସହ {n}ଟି ଶବ୍ଦର ତାଲିକା ସେୟାର୍ କରିଛନ୍ତି।', use_shared: 'ଏହି ତାଲିକା ବ୍ୟବହାର କରନ୍ତୁ', wa_share: 'WhatsApp ରେ ପଠାନ୍ତୁ',
    print_h: 'ଶବ୍ଦ ତାଲିକା ଦେଖନ୍ତୁ ଓ ପ୍ରିଣ୍ଟ କରନ୍ତୁ', print_list: 'ଶବ୍ଦ ତାଲିକା ପ୍ରିଣ୍ଟ କରନ୍ତୁ', print_test: 'ବନାନ ପରୀକ୍ଷା ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    col_word: 'ଶବ୍ଦ', col_sentence: 'ଉଦାହରଣ ବାକ୍ୟ', col_listen: 'ଶୁଣନ୍ତୁ',
    print_title: 'ବନାନ ତାଲିକା: {level}', test_title: 'ବନାନ ପରୀକ୍ଷା: {level}',
    print_name: 'ନାମ', print_class: 'ଶ୍ରେଣୀ', print_date: 'ତାରିଖ',
    test_instr: 'ଶିକ୍ଷକଙ୍କୁ ଧ୍ୟାନରେ ଶୁଣି ପ୍ରତ୍ୟେକ ଶବ୍ଦ ଲେଖନ୍ତୁ। ସଙ୍କେତ ଭାବେ ଅର୍ଥ ଦିଆଯାଇଛି।', answer_key: 'ଉତ୍ତର (ଶିକ୍ଷକଙ୍କ ପାଇଁ)'
  },
  ta: {
    app_title: 'ஸ்பெல்லிங் பீ',
    intro: 'ஆங்கிலச் சொல்லைக் கேட்டு, அதன் எழுத்துக்கூட்டலை எழுதுங்கள். உங்கள் மொழியில் பொருள் அறியுங்கள், குறிப்புகள் பெறுங்கள், வகுப்பில் ஸ்பெல்லிங் பீ விளையாடுங்கள், எழுத்துக்கூட்டல் தேர்வை அச்சிடுங்கள்.',
    tab_practise: 'பயிற்சி', tab_bee: 'வகுப்புப் போட்டி', tab_lists: 'சொல் பட்டியல்கள்',
    choose_level: 'நிலையைத் தேர்ந்தெடுங்கள்', level_n: 'நிலை {n}', class_n: 'வகுப்பு {n}', n_words: '{n} சொற்கள்', best_n: 'சிறந்தது {s}/{n}',
    my_list: 'என் பட்டியல்', review_lvl: 'என் தவறுகள்', review_none: 'இன்னும் தவறு இல்லை', custom_none: '“சொல் பட்டியல்கள்” பகுதியில் சொற்களைச் சேருங்கள்',
    opt_second: 'இரண்டாவது வாய்ப்பு தரவும்', opt_auto: 'ஒவ்வொரு சொல்லையும் தானாகச் சொல்லும்', start_round: 'தொடங்கு', round_info: 'இந்தச் சுற்றில் {n} சொற்கள்',
    help_h: 'பயன்படுத்துவது எப்படி · வகுப்பறைக்கான யோசனைகள்',
    tip1: 'நிலையைத் தேர்ந்தெடுத்து <b>தொடங்கு</b> அழுத்துங்கள். சொல்லைக் கேளுங்கள் 🔊, வாக்கியத்தில் கேளுங்கள் 💬 அல்லது மெதுவாகக் கேளுங்கள் 🐢. பிறகு எழுத்துக்கூட்டலைத் தட்டச்சு செய்து <b>சரிபார்</b> அழுத்துங்கள் (அல்லது Enter).',
    tip2: 'சிக்கிக்கொண்டீர்களா? குறிப்பு எடுங்கள்: முதல் எழுத்து, எத்தனை எழுத்துகள், அல்லது கலைந்த எழுத்துகள். கைபேசி அல்லது ஸ்மார்ட்போர்டில் தட்டச்சுக்குப் பதில் கலைந்த எழுத்துகளைத் தொடுங்கள்.',
    tip3: 'பச்சை எழுத்துகள் சரி, சிவப்பு எழுத்துகளைத் திருத்த வேண்டும், புள்ளிக்கோட்டுப் பெட்டி என்றால் ஒரு எழுத்து விடுபட்டுள்ளது. தவறிய சொற்கள் <b>என் தவறுகள்</b> பகுதிக்குச் செல்லும், பிறகு மீண்டும் பயிற்சி செய்யலாம்.',
    tip4: 'ஆசிரியர்களுக்கு: இந்த வாரச் சொற்களை <b>சொல் பட்டியல்கள்</b> பகுதியில் வரிக்கு ஒன்றாக எழுதுங்கள். பட்டியலையோ விடைகளுடன் கூடிய தேர்வையோ அச்சிடுங்கள், அல்லது WhatsApp இணைப்பாக மாணவர்களுக்கு அனுப்புங்கள்.',
    tip5: 'வகுப்புச் செயல்பாடு: புரொஜெக்டரில் <b>வகுப்புப் போட்டி</b> திறந்து, 2–4 அணிகள் அமைத்து, முறை வைத்து எழுத்துக்கூட்டல் கேளுங்கள். குழந்தைகள் வாய்விட்டுச் சொல்லலாம், நீங்கள் ✓ அல்லது ✗ அழுத்துங்கள்.',
    tip6: 'ஆங்கிலக் குரல் இல்லையா? செயலி பொருள், இடைவெளியுடன் கூடிய வாக்கியம், கலைந்த எழுத்துகளைக் காட்டும், எனவே குழந்தைகள் அப்போதும் விளையாடலாம். Windows-இல் Settings → Time &amp; language → Speech சென்று “English (India)” குரலைச் சேருங்கள்.',
    voice_h: 'குரல்', voice_lbl: 'ஆங்கிலக் குரல்', voice_auto: 'தானியங்கி (முதலில் இந்திய ஆங்கிலம்)', voice_using: 'குரல்:', voice_test: 'குரலைச் சோதி', speed: 'வேகம்',
    nv_title: 'இந்தச் சாதனத்தில் ஆங்கிலக் குரல் இல்லை',
    nv_short: 'சொல்லைக் கண்டுபிடிக்கப் பொருள், வாக்கியம், கலைந்த எழுத்துகளின் உதவியைப் பெறுங்கள்.',
    nv_help: 'அப்போதும் விளையாடலாம்: பொருள், வாக்கியம், கலைந்த எழுத்துகள் காட்டப்படும். Android-இல் Chrome-இல் பொதுவாக ஆங்கிலக் குரல் இருக்கும்; கணினியில் பேச்சு அமைப்புகளில் “English (India)” சேருங்கள்.',
    stats_h: 'என் முன்னேற்றம்', st_words: 'முயன்ற சொற்கள்', st_acc: 'சரி', st_streak: 'தொடர் சரி சாதனை', st_review: 'மீண்டும் பயிற்சிக்கு',
    reset_progress: 'முன்னேற்றத்தை மீட்டமை', confirm_progress: 'உங்கள் மதிப்பெண்களையும் தவறுகள் பட்டியலையும் அழிக்கவா? உங்கள் சொந்தச் சொல் பட்டியல் அப்படியே இருக்கும்.', reset_done: 'முன்னேற்றம் அழிக்கப்பட்டது.',
    word_x_of_y: 'சொல் {i} / {n}', streak: 'தொடர்ந்து சரியான விடைகள்', end_round: 'சுற்றை முடி',
    hear_word: 'சொல்லைக் கேள்', hear_sent: 'வாக்கியத்தில் கேள்', hear_slow: 'மெதுவாகக் கேள்',
    meaning: 'பொருள்', sentence_lbl: 'வாக்கியம்', starts_with: 'முதல் எழுத்து',
    hints: 'குறிப்புகள்', hint_first: 'முதல் எழுத்து', hint_len: 'எத்தனை எழுத்துகள்', hint_jumble: 'கலைந்த எழுத்துகள்',
    hints_used_n: 'பெற்ற குறிப்புகள்: {n}', hint_free: 'குரல் இல்லாதபோது கலைந்த எழுத்துகள் இலவசம்.', letters_n: '{n} எழுத்துகள்',
    jumble_aria: 'கலைந்த எழுத்துகள், தட்டச்சு செய்யத் தொடுங்கள்', tap_letter: '{l} எழுது', space_key: 'இடைவெளி',
    your_spelling: 'உங்கள் எழுத்துக்கூட்டல்', answer_ph: 'எழுத்துக்கூட்டலைத் தட்டச்சு செய்க', backspace: 'கடைசி எழுத்தை நீக்கு', check: 'சரிபார்', show_answer: 'விடையைக் காட்டு',
    fb_empty: 'முதலில் எழுத்துக்கூட்டலைத் தட்டச்சு செய்யுங்கள்.', fb_retry: 'கிட்டத்தட்ட சரி! சிவப்பு எழுத்துகளைத் திருத்தி இன்னொரு முறை முயலுங்கள்.', fb_missing: 'விடுபட்ட எழுத்துகள்: {n}',
    lg_ok: 'சரி', lg_bad: 'தவறு', lg_miss: 'விடுபட்டது',
    fb_ok: 'சரி! அருமை.', fb_ok2: 'இரண்டாவது முயற்சியில் சரி!',
    fb_alt: '“{alt}” என்பது அமெரிக்க எழுத்துக்கூட்டல். இந்தியாவில் பொதுவாக “{w}” என்று எழுதுகிறோம்.',
    fb_bad: 'இந்த முறை இல்லை. சரியான எழுத்துக்கூட்டல்:', fb_shown: 'இதோ சரியான எழுத்துக்கூட்டல்:',
    you_wrote: 'நீங்கள் எழுதியது', right_spelling: 'சரியான எழுத்துக்கூட்டல்',
    fb_learn: 'மஞ்சள் எழுத்துகளைப் பாருங்கள், அதுதான் கடினமான பகுதி. சொல்லைச் சொல்லி, ஒருமுறை சத்தமாக எழுத்துக்கூட்டிச் சொல்லுங்கள்.',
    next_word: 'அடுத்த சொல்', see_result: 'என் மதிப்பெண்ணைப் பார்',
    sum_title: 'சுற்று முடிந்தது!', sum_score: '{n}-இல் {c} சரி',
    praise_1: 'நல்ல முயற்சி! கீழே உள்ள சொற்களைப் பயிற்சி செய்து மீண்டும் விளையாடுங்கள்.', praise_2: 'சபாஷ்! இன்னும் கொஞ்சம் பயிற்சி செய்தால் எல்லாம் சரியாகும்.', praise_3: 'அற்புதமான எழுத்துக்கூட்டல்!',
    sum_streak: 'தொடர் சரி: {n}', sum_hints: 'பெற்ற குறிப்புகள்: {n}', new_best: 'புதிய சிறந்த மதிப்பெண்!',
    sum_mistakes: 'பயிற்சிக்கான சொற்கள்', sum_perfect: 'ஒரு தவறும் இல்லை, முழுமையான சுற்று! 🎉',
    practise_these: 'இந்தச் சொற்களைப் பயிற்சி செய்', new_round: 'புதிய சுற்று', change_level: 'நிலையை மாற்று', listen_to: '{w} கேள்',
    bee_setup_h: 'வகுப்பில் எழுத்துக்கூட்டல் போட்டி',
    bee_help: 'இதைப் புரொஜெக்டர் அல்லது ஸ்மார்ட்போர்டில் காட்டுங்கள். வீரர்கள் அல்லது அணிகள் முறைப்படி விளையாடுவார்கள்: ஒவ்வொருவரும் ஒரு சொல்லைக் கேட்டு, தட்டச்சு செய்வார்கள் அல்லது வாய்விட்டுச் சொல்வார்கள், ஆசிரியர் தீர்ப்பு சொல்வார்.',
    players: 'வீரர்கள் அல்லது அணிகள்', player_n: 'வீரர் {n}', add_player: 'வீரரைச் சேர்', remove_player: 'வீரர் {n}-ஐ நீக்கு',
    level_lbl: 'சொற்களின் நிலை', per_player: 'ஒவ்வொரு வீரருக்கும் சொற்கள்', game_type: 'விளையாட்டு', type_points: 'புள்ளிகள்', type_ko: 'நாக்-அவுட்',
    type_points_help: 'அனைவருக்கும் சம எண்ணிக்கையில் சொற்கள். அதிக சரியான சொற்கள் பெற்றவர் வெல்வார்.',
    type_ko_help: 'ஒவ்வொரு வீரருக்கும் 3 உயிர்கள். தவறான எழுத்துக்கூட்டலுக்கு ஒரு உயிர் போகும்; கடைசியில் மிஞ்சுபவர் வெல்வார்.',
    start_bee: 'போட்டியைத் தொடங்கு', bee_how_h: 'நடத்துவது எப்படி',
    bee_step1: 'வீரர்கள் அல்லது அணிகளின் பெயர்களை எழுதி, நிலையைத் தேர்ந்தெடுங்கள்.',
    bee_step2: 'தொடங்கு அழுத்தி முழுத் திரைக்கு மாற்றுங்கள். செயலி சொல்லை உரக்கப் படிக்கும்.',
    bee_step3: 'வீரர் சொல்லைத் தட்டச்சு செய்வார், அல்லது வாய்விட்டுச் சொல்வார்; நீங்கள் ✓ அல்லது ✗ அழுத்துங்கள்.',
    bee_step4: 'அனைவரும் சரியான எழுத்துக்கூட்டலைப் பார்த்த பிறகு அடுத்த வீரர் அழுத்துங்கள்.',
    turn_of: '{name}, உங்கள் முறை!', bee_round: 'சொல் {i} / {n}', judge_help: 'வாய்விட்டுச் சொன்னாரா? ஆசிரியரே, தீர்ப்பு சொல்லுங்கள்:', judge_ok: 'சரி', judge_bad: 'தவறு',
    next_player: 'அடுத்த வீரர்', see_winner: 'வெற்றியாளரைப் பார்', end_game: 'விளையாட்டை முடி', confirm_end: 'விளையாட்டை இப்போதே முடித்து மதிப்பெண்களைக் காட்டவா?',
    lives_n: '{n} உயிர்கள் மீதம்', out: 'வெளியே', winner_is: '{name} வென்றார்! 🎉', winners_tie: 'சமநிலை: {names}',
    final_note: 'ஒவ்வொரு வீரருக்கும் கைதட்டுங்கள், இன்று எல்லோரும் பயிற்சி செய்தார்கள்!', col_player: 'வீரர்', col_lives: 'உயிர்கள்',
    play_again: 'மீண்டும் விளையாடு', change_players: 'வீரர்களை மாற்று',
    my_list_h: 'என் சொல் பட்டியல்',
    my_list_help: 'ஆசிரியர்களுக்கு: ஆங்கிலச் சொற்களை வரிக்கு ஒன்றாகத் தட்டச்சு செய்யுங்கள் அல்லது ஒட்டுங்கள். விரும்பினால் | குறிக்குப் பிறகு வாக்கியமும் பொருளும் எழுதலாம்.',
    format_lbl: 'வடிவம்:', my_list_format: 'சொல் | வாக்கியம் | பொருள்', words_box: 'சொற்கள்',
    save_list: 'பட்டியலைச் சேமி', example_list: 'எடுத்துக்காட்டு', share_list: 'இணைப்பைப் பகிர்',
    list_saved: '{n} சொற்கள் சேமிக்கப்பட்டன. பயிற்சி அல்லது வகுப்புப் போட்டியில் “என் பட்டியல்” தேர்ந்தெடுங்கள்.', list_skipped: '{n} வரிகள் தவிர்க்கப்பட்டன: ஆங்கில எழுத்துகளை மட்டும் பயன்படுத்துங்கள்.',
    list_empty: 'பட்டியல் காலியாக உள்ளது. முதலில் சில சொற்களை எழுதுங்கள்.', list_cleared: 'பட்டியல் அழிக்கப்பட்டது.', confirm_clear_list: 'உங்கள் சொல் பட்டியலை நீக்கவா?', confirm_replace_list: 'இது உங்கள் தற்போதைய சொல் பட்டியலை ({n} சொற்கள்) மாற்றிவிடும். தொடரவா?',
    share_done: 'இணைப்பு நகலெடுக்கப்பட்டது! மாணவர்களுக்கு அனுப்புங்கள்: பட்டியல் அவர்களின் உலாவியில் திறக்கும்.',
    wa_list: 'எழுத்துக்கூட்டல் பயிற்சி: இந்த வாரத்தின் {n} சொற்கள். இங்கே திறக்கவும்: {url}',
    shared_found: 'யாரோ {n} சொற்கள் கொண்ட பட்டியலை உங்களுடன் பகிர்ந்துள்ளார்.', use_shared: 'இந்தப் பட்டியலைப் பயன்படுத்து', wa_share: 'WhatsApp-இல் அனுப்பு',
    print_h: 'சொல் பட்டியல்களைப் பார்த்து அச்சிடுங்கள்', print_list: 'சொல் பட்டியலை அச்சிடு', print_test: 'எழுத்துக்கூட்டல் தேர்வை அச்சிடு',
    col_word: 'சொல்', col_sentence: 'எடுத்துக்காட்டு வாக்கியம்', col_listen: 'கேள்',
    print_title: 'எழுத்துக்கூட்டல் பட்டியல்: {level}', test_title: 'எழுத்துக்கூட்டல் தேர்வு: {level}',
    print_name: 'பெயர்', print_class: 'வகுப்பு', print_date: 'தேதி',
    test_instr: 'ஆசிரியர் சொல்வதைக் கவனமாகக் கேட்டு ஒவ்வொரு சொல்லையும் எழுதுங்கள். குறிப்பாகப் பொருள் கொடுக்கப்பட்டுள்ளது.', answer_key: 'விடைகள் (ஆசிரியருக்கு)'
  }
  ,
  te: {
    app_title: 'స్పెల్లింగ్ బీ',
    intro: 'ఇంగ్లీష్ పదాన్ని విని, దాని స్పెల్లింగ్ రాయండి. మీ భాషలో అర్థం తెలుసుకోండి, సూచనలు తీసుకోండి, తరగతిలో స్పెల్లింగ్ బీ ఆడండి, స్పెల్లింగ్ పరీక్షను ప్రింట్ చేయండి.',
    tab_practise: 'సాధన', tab_bee: 'తరగతి పోటీ', tab_lists: 'పదాల జాబితాలు',
    choose_level: 'స్థాయిని ఎంచుకోండి', level_n: 'స్థాయి {n}', class_n: 'తరగతి {n}', n_words: '{n} పదాలు', best_n: 'ఉత్తమం {s}/{n}',
    my_list: 'నా జాబితా', review_lvl: 'నా తప్పులు', review_none: 'ఇంకా తప్పులు లేవు', custom_none: '“పదాల జాబితాలు”లో పదాలు జోడించండి',
    opt_second: 'రెండో అవకాశం ఇవ్వండి', opt_auto: 'ప్రతి పదాన్ని దానంతట అదే చెప్పు', start_round: 'ప్రారంభించండి', round_info: 'ఈ రౌండ్‌లో {n} పదాలు',
    help_h: 'ఎలా ఉపయోగించాలి · తరగతి కోసం ఆలోచనలు',
    tip1: 'స్థాయిని ఎంచుకుని <b>ప్రారంభించండి</b> నొక్కండి. పదం వినండి 🔊, వాక్యంలో వినండి 💬 లేదా నెమ్మదిగా వినండి 🐢. తర్వాత స్పెల్లింగ్ టైప్ చేసి <b>తనిఖీ చేయండి</b> నొక్కండి (లేదా Enter).',
    tip2: 'ఇరుక్కుపోయారా? సూచన తీసుకోండి: మొదటి అక్షరం, ఎన్ని అక్షరాలు, లేదా కలగలిసిన అక్షరాలు. ఫోన్ లేదా స్మార్ట్‌బోర్డ్‌పై టైప్ చేయకుండా కలగలిసిన అక్షరాలను తాకండి.',
    tip3: 'ఆకుపచ్చ అక్షరాలు సరైనవి, ఎరుపు అక్షరాలను సరిచేయాలి, చుక్కల పెట్టె అంటే ఒక అక్షరం తప్పిపోయింది. తప్పిన పదాలు <b>నా తప్పులు</b>లోకి వెళ్తాయి, తర్వాత మళ్ళీ సాధన చేయవచ్చు.',
    tip4: 'ఉపాధ్యాయులకు: ఈ వారం పదాలను <b>పదాల జాబితాలు</b>లో లైన్‌కు ఒకటి చొప్పున రాయండి. జాబితాను లేదా జవాబులతో కూడిన స్పెల్లింగ్ పరీక్షను ప్రింట్ చేయండి, లేదా WhatsApp లింక్‌గా విద్యార్థులకు పంపండి.',
    tip5: 'తరగతి కార్యకలాపం: ప్రొజెక్టర్‌పై <b>తరగతి పోటీ</b> తెరిచి, 2–4 జట్లు చేసి, వంతుల వారీగా స్పెల్లింగ్ అడగండి. పిల్లలు నోటితో స్పెల్లింగ్ చెప్పవచ్చు, మీరు ✓ లేదా ✗ నొక్కండి.',
    tip6: 'ఇంగ్లీష్ వాయిస్ లేదా? యాప్ అర్థం, ఖాళీ ఉన్న వాక్యం, కలగలిసిన అక్షరాలు చూపిస్తుంది, కాబట్టి పిల్లలు అయినా ఆడవచ్చు. Windowsలో Settings → Time &amp; language → Speechకి వెళ్లి “English (India)” వాయిస్ జోడించండి.',
    voice_h: 'వాయిస్', voice_lbl: 'ఇంగ్లీష్ వాయిస్', voice_auto: 'ఆటోమేటిక్ (ముందు భారతీయ ఇంగ్లీష్)', voice_using: 'వాయిస్:', voice_test: 'వాయిస్ పరీక్షించండి', speed: 'వేగం',
    nv_title: 'ఈ పరికరంలో ఇంగ్లీష్ వాయిస్ లేదు',
    nv_short: 'పదాన్ని కనుక్కోవడానికి అర్థం, వాక్యం, కలగలిసిన అక్షరాల సహాయం తీసుకోండి.',
    nv_help: 'అయినా ఆడవచ్చు: అర్థం, వాక్యం, కలగలిసిన అక్షరాలు చూపిస్తాం. Androidలో Chromeలో సాధారణంగా ఇంగ్లీష్ వాయిస్ ఉంటుంది; కంప్యూటర్‌లో స్పీచ్ సెట్టింగ్‌లలో “English (India)” జోడించండి.',
    stats_h: 'నా ప్రగతి', st_words: 'ప్రయత్నించిన పదాలు', st_acc: 'సరైనవి', st_streak: 'వరుస సరైన వాటి రికార్డు', st_review: 'మళ్ళీ సాధన చేయాల్సినవి',
    reset_progress: 'ప్రగతిని రీసెట్ చేయండి', confirm_progress: 'మీ స్కోర్లు, తప్పుల జాబితాను తుడిచివేయాలా? మీ సొంత పదాల జాబితా అలాగే ఉంటుంది.', reset_done: 'ప్రగతి తుడిచివేయబడింది.',
    word_x_of_y: 'పదం {i} / {n}', streak: 'వరుసగా సరైన జవాబులు', end_round: 'రౌండ్ ముగించండి',
    hear_word: 'పదం వినండి', hear_sent: 'వాక్యంలో వినండి', hear_slow: 'నెమ్మదిగా వినండి',
    meaning: 'అర్థం', sentence_lbl: 'వాక్యం', starts_with: 'మొదటి అక్షరం',
    hints: 'సూచనలు', hint_first: 'మొదటి అక్షరం', hint_len: 'ఎన్ని అక్షరాలు', hint_jumble: 'కలగలిసిన అక్షరాలు',
    hints_used_n: 'తీసుకున్న సూచనలు: {n}', hint_free: 'వాయిస్ లేనప్పుడు కలగలిసిన అక్షరాలు ఉచితం.', letters_n: '{n} అక్షరాలు',
    jumble_aria: 'కలగలిసిన అక్షరాలు, టైప్ చేయడానికి తాకండి', tap_letter: '{l} రాయండి', space_key: 'స్పేస్',
    your_spelling: 'మీ స్పెల్లింగ్', answer_ph: 'స్పెల్లింగ్ టైప్ చేయండి', backspace: 'చివరి అక్షరం తొలగించండి', check: 'తనిఖీ చేయండి', show_answer: 'జవాబు చూపించు',
    fb_empty: 'ముందు స్పెల్లింగ్ టైప్ చేయండి.', fb_retry: 'దాదాపు సరైంది! ఎరుపు అక్షరాలను సరిచేసి మరోసారి ప్రయత్నించండి.', fb_missing: 'తప్పిపోయిన అక్షరాలు: {n}',
    lg_ok: 'సరైనది', lg_bad: 'తప్పు', lg_miss: 'తప్పిపోయింది',
    fb_ok: 'సరైనది! చాలా బాగుంది.', fb_ok2: 'రెండో ప్రయత్నంలో సరైనది!',
    fb_alt: '“{alt}” అమెరికన్ స్పెల్లింగ్. భారతదేశంలో మనం సాధారణంగా “{w}” అని రాస్తాం.',
    fb_bad: 'ఈసారి కాదు. సరైన స్పెల్లింగ్:', fb_shown: 'ఇదిగో సరైన స్పెల్లింగ్:',
    you_wrote: 'మీరు రాసింది', right_spelling: 'సరైన స్పెల్లింగ్',
    fb_learn: 'పసుపు అక్షరాలను చూడండి, అదే కష్టమైన భాగం. పదాన్ని పలికి, ఒకసారి గట్టిగా స్పెల్లింగ్ చెప్పండి.',
    next_word: 'తదుపరి పదం', see_result: 'నా స్కోరు చూడు',
    sum_title: 'రౌండ్ పూర్తయింది!', sum_score: '{n}లో {c} సరైనవి',
    praise_1: 'మంచి ప్రయత్నం! కింది పదాలను సాధన చేసి మళ్ళీ ఆడండి.', praise_2: 'శభాష్! ఇంకొంచెం సాధన చేస్తే అన్నీ సరైపోతాయి.', praise_3: 'అద్భుతమైన స్పెల్లింగ్!',
    sum_streak: 'వరుసగా సరైనవి: {n}', sum_hints: 'తీసుకున్న సూచనలు: {n}', new_best: 'కొత్త ఉత్తమ స్కోరు!',
    sum_mistakes: 'సాధన చేయాల్సిన పదాలు', sum_perfect: 'ఒక్క తప్పు కూడా లేదు, పరిపూర్ణ రౌండ్! 🎉',
    practise_these: 'ఈ పదాలను సాధన చేయండి', new_round: 'కొత్త రౌండ్', change_level: 'స్థాయి మార్చండి', listen_to: '{w} వినండి',
    bee_setup_h: 'తరగతిలో స్పెల్లింగ్ పోటీ',
    bee_help: 'దీన్ని ప్రొజెక్టర్ లేదా స్మార్ట్‌బోర్డ్‌పై చూపించండి. ఆటగాళ్లు లేదా జట్లు వంతుల వారీగా ఆడతారు: ప్రతి ఒక్కరూ ఒక పదం విని స్పెల్లింగ్ టైప్ చేస్తారు లేదా నోటితో చెబుతారు, ఉపాధ్యాయులు తీర్పు ఇస్తారు.',
    players: 'ఆటగాళ్లు లేదా జట్లు', player_n: 'ఆటగాడు {n}', add_player: 'ఆటగాడిని జోడించండి', remove_player: 'ఆటగాడు {n}ని తీసివేయండి',
    level_lbl: 'పదాల స్థాయి', per_player: 'ప్రతి ఆటగాడికి పదాలు', game_type: 'ఆట', type_points: 'పాయింట్లు', type_ko: 'నాకౌట్',
    type_points_help: 'అందరికీ సమాన సంఖ్యలో పదాలు. ఎక్కువ సరైన పదాలు చెప్పినవారు గెలుస్తారు.',
    type_ko_help: 'ప్రతి ఆటగాడికి 3 ప్రాణాలు. తప్పు స్పెల్లింగ్‌కు ఒక ప్రాణం పోతుంది; చివరికి మిగిలినవారు గెలుస్తారు.',
    start_bee: 'పోటీ ప్రారంభించండి', bee_how_h: 'ఎలా నడపాలి',
    bee_step1: 'ఆటగాళ్లు లేదా జట్ల పేర్లు రాసి, స్థాయిని ఎంచుకోండి.',
    bee_step2: 'ప్రారంభించండి నొక్కి పూర్తి స్క్రీన్ చేయండి. యాప్ పదాన్ని గట్టిగా చదువుతుంది.',
    bee_step3: 'ఆటగాడు పదాన్ని టైప్ చేస్తాడు, లేదా నోటితో స్పెల్లింగ్ చెబుతాడు; మీరు ✓ లేదా ✗ నొక్కండి.',
    bee_step4: 'అందరూ సరైన స్పెల్లింగ్ చూశాక, తదుపరి ఆటగాడు నొక్కండి.',
    turn_of: '{name}, మీ వంతు!', bee_round: 'పదం {i} / {n}', judge_help: 'నోటితో స్పెల్లింగ్ చెప్పారా? ఉపాధ్యాయులారా, తీర్పు ఇవ్వండి:', judge_ok: 'సరైనది', judge_bad: 'తప్పు',
    next_player: 'తదుపరి ఆటగాడు', see_winner: 'విజేతను చూడండి', end_game: 'ఆట ముగించండి', confirm_end: 'ఆటను ఇప్పుడే ముగించి స్కోర్లు చూపించాలా?',
    lives_n: '{n} ప్రాణాలు మిగిలాయి', out: 'ఔట్', winner_is: '{name} గెలిచారు! 🎉', winners_tie: 'సమానం: {names}',
    final_note: 'ప్రతి ఆటగాడికీ చప్పట్లు, ఈ రోజు అందరూ సాధన చేశారు!', col_player: 'ఆటగాడు', col_lives: 'ప్రాణాలు',
    play_again: 'మళ్ళీ ఆడండి', change_players: 'ఆటగాళ్లను మార్చండి',
    my_list_h: 'నా పదాల జాబితా',
    my_list_help: 'ఉపాధ్యాయులకు: ఇంగ్లీష్ పదాలను లైన్‌కు ఒకటి చొప్పున టైప్ లేదా పేస్ట్ చేయండి. కావాలంటే | గుర్తు తర్వాత వాక్యం, అర్థం కూడా రాయండి.',
    format_lbl: 'పద్ధతి:', my_list_format: 'పదం | వాక్యం | అర్థం', words_box: 'పదాలు',
    save_list: 'జాబితా సేవ్ చేయండి', example_list: 'ఉదాహరణ', share_list: 'లింక్ షేర్ చేయండి',
    list_saved: '{n} పదాలు సేవ్ అయ్యాయి. సాధన లేదా తరగతి పోటీలో “నా జాబితా” ఎంచుకోండి.', list_skipped: '{n} లైన్లు వదిలేశాం: ఇంగ్లీష్ అక్షరాలు మాత్రమే వాడండి.',
    list_empty: 'జాబితా ఖాళీగా ఉంది. ముందు కొన్ని పదాలు రాయండి.', list_cleared: 'జాబితా తుడిచివేయబడింది.', confirm_clear_list: 'మీ పదాల జాబితాను తొలగించాలా?', confirm_replace_list: 'దీనితో మీ ప్రస్తుత పదాల జాబితా ({n} పదాలు) మారిపోతుంది. కొనసాగించాలా?',
    share_done: 'లింక్ కాపీ అయింది! విద్యార్థులకు పంపండి: జాబితా వారి బ్రౌజర్‌లో తెరుచుకుంటుంది.',
    wa_list: 'స్పెల్లింగ్ సాధన: ఈ వారం {n} పదాలు. ఇక్కడ తెరవండి: {url}',
    shared_found: 'ఎవరో {n} పదాల జాబితాను మీతో పంచుకున్నారు.', use_shared: 'ఈ జాబితాను వాడండి', wa_share: 'WhatsAppలో పంపండి',
    print_h: 'పదాల జాబితాలు చూసి ప్రింట్ చేయండి', print_list: 'పదాల జాబితా ప్రింట్ చేయండి', print_test: 'స్పెల్లింగ్ పరీక్ష ప్రింట్ చేయండి',
    col_word: 'పదం', col_sentence: 'ఉదాహరణ వాక్యం', col_listen: 'వినండి',
    print_title: 'స్పెల్లింగ్ జాబితా: {level}', test_title: 'స్పెల్లింగ్ పరీక్ష: {level}',
    print_name: 'పేరు', print_class: 'తరగతి', print_date: 'తేదీ',
    test_instr: 'ఉపాధ్యాయులు చెప్పేది శ్రద్ధగా విని ప్రతి పదాన్ని రాయండి. సూచనగా అర్థం ఇవ్వబడింది.', answer_key: 'జవాబులు (ఉపాధ్యాయుల కోసం)'
  },
  kn: {
    app_title: 'ಸ್ಪೆಲ್ಲಿಂಗ್ ಬೀ',
    intro: 'ಇಂಗ್ಲಿಷ್ ಪದವನ್ನು ಕೇಳಿ, ಅದರ ಸ್ಪೆಲ್ಲಿಂಗ್ ಬರೆಯಿರಿ. ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಅರ್ಥ ತಿಳಿಯಿರಿ, ಸುಳಿವು ಪಡೆಯಿರಿ, ತರಗತಿಯಲ್ಲಿ ಸ್ಪೆಲ್ಲಿಂಗ್ ಬೀ ಆಡಿ ಮತ್ತು ಸ್ಪೆಲ್ಲಿಂಗ್ ಪರೀಕ್ಷೆ ಮುದ್ರಿಸಿ.',
    tab_practise: 'ಅಭ್ಯಾಸ', tab_bee: 'ತರಗತಿ ಸ್ಪರ್ಧೆ', tab_lists: 'ಪದಪಟ್ಟಿಗಳು',
    choose_level: 'ಹಂತ ಆಯ್ಕೆಮಾಡಿ', level_n: 'ಹಂತ {n}', class_n: 'ತರಗತಿ {n}', n_words: '{n} ಪದಗಳು', best_n: 'ಅತ್ಯುತ್ತಮ {s}/{n}',
    my_list: 'ನನ್ನ ಪಟ್ಟಿ', review_lvl: 'ನನ್ನ ತಪ್ಪುಗಳು', review_none: 'ಇನ್ನೂ ತಪ್ಪುಗಳಿಲ್ಲ', custom_none: '“ಪದಪಟ್ಟಿಗಳು” ವಿಭಾಗದಲ್ಲಿ ಪದಗಳನ್ನು ಸೇರಿಸಿ',
    opt_second: 'ಎರಡನೇ ಅವಕಾಶ ಕೊಡಿ', opt_auto: 'ಪ್ರತಿ ಪದವನ್ನು ತಾನಾಗಿ ಹೇಳಲಿ', start_round: 'ಪ್ರಾರಂಭಿಸಿ', round_info: 'ಈ ಸುತ್ತಿನಲ್ಲಿ {n} ಪದಗಳು',
    help_h: 'ಬಳಸುವುದು ಹೇಗೆ · ತರಗತಿಗೆ ಉಪಾಯಗಳು',
    tip1: 'ಹಂತ ಆಯ್ಕೆಮಾಡಿ <b>ಪ್ರಾರಂಭಿಸಿ</b> ಒತ್ತಿ. ಪದ ಕೇಳಿ 🔊, ವಾಕ್ಯದಲ್ಲಿ ಕೇಳಿ 💬 ಅಥವಾ ನಿಧಾನವಾಗಿ ಕೇಳಿ 🐢. ನಂತರ ಸ್ಪೆಲ್ಲಿಂಗ್ ಟೈಪ್ ಮಾಡಿ <b>ಪರಿಶೀಲಿಸಿ</b> ಒತ್ತಿ (ಅಥವಾ Enter).',
    tip2: 'ಸಿಕ್ಕಿಹಾಕಿಕೊಂಡಿರಾ? ಸುಳಿವು ಪಡೆಯಿರಿ: ಮೊದಲ ಅಕ್ಷರ, ಎಷ್ಟು ಅಕ್ಷರಗಳು, ಅಥವಾ ಕಲಸಿದ ಅಕ್ಷರಗಳು. ಫೋನ್ ಅಥವಾ ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಟೈಪ್ ಮಾಡುವ ಬದಲು ಕಲಸಿದ ಅಕ್ಷರಗಳನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ.',
    tip3: 'ಹಸಿರು ಅಕ್ಷರಗಳು ಸರಿ, ಕೆಂಪು ಅಕ್ಷರಗಳನ್ನು ಸರಿಪಡಿಸಬೇಕು, ಚುಕ್ಕೆ ಗೆರೆಯ ಡಬ್ಬಿ ಎಂದರೆ ಒಂದು ಅಕ್ಷರ ಬಿಟ್ಟುಹೋಗಿದೆ. ತಪ್ಪಾದ ಪದಗಳು <b>ನನ್ನ ತಪ್ಪುಗಳು</b> ವಿಭಾಗಕ್ಕೆ ಹೋಗುತ್ತವೆ, ನಂತರ ಮತ್ತೆ ಅಭ್ಯಾಸ ಮಾಡಬಹುದು.',
    tip4: 'ಶಿಕ್ಷಕರಿಗೆ: ಈ ವಾರದ ಪದಗಳನ್ನು <b>ಪದಪಟ್ಟಿಗಳು</b> ವಿಭಾಗದಲ್ಲಿ ಸಾಲಿಗೆ ಒಂದರಂತೆ ಬರೆಯಿರಿ. ಪಟ್ಟಿಯನ್ನು ಅಥವಾ ಉತ್ತರಗಳಿರುವ ಸ್ಪೆಲ್ಲಿಂಗ್ ಪರೀಕ್ಷೆಯನ್ನು ಮುದ್ರಿಸಿ, ಅಥವಾ WhatsApp ಲಿಂಕ್ ಆಗಿ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಕಳುಹಿಸಿ.',
    tip5: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಪ್ರೊಜೆಕ್ಟರ್‌ನಲ್ಲಿ <b>ತರಗತಿ ಸ್ಪರ್ಧೆ</b> ತೆರೆಯಿರಿ, 2–4 ತಂಡಗಳನ್ನು ಮಾಡಿ, ಸರದಿಯಂತೆ ಸ್ಪೆಲ್ಲಿಂಗ್ ಕೇಳಿ. ಮಕ್ಕಳು ಬಾಯಿಂದ ಸ್ಪೆಲ್ಲಿಂಗ್ ಹೇಳಬಹುದು, ನೀವು ✓ ಅಥವಾ ✗ ಒತ್ತಿ.',
    tip6: 'ಇಂಗ್ಲಿಷ್ ಧ್ವನಿ ಇಲ್ಲವೇ? ಆ್ಯಪ್ ಅರ್ಥ, ಖಾಲಿ ಜಾಗವಿರುವ ವಾಕ್ಯ ಮತ್ತು ಕಲಸಿದ ಅಕ್ಷರಗಳನ್ನು ತೋರಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಮಕ್ಕಳು ಆಗಲೂ ಆಡಬಹುದು. Windows ನಲ್ಲಿ Settings → Time &amp; language → Speech ಗೆ ಹೋಗಿ “English (India)” ಧ್ವನಿ ಸೇರಿಸಿ.',
    voice_h: 'ಧ್ವನಿ', voice_lbl: 'ಇಂಗ್ಲಿಷ್ ಧ್ವನಿ', voice_auto: 'ಸ್ವಯಂಚಾಲಿತ (ಮೊದಲು ಭಾರತೀಯ ಇಂಗ್ಲಿಷ್)', voice_using: 'ಧ್ವನಿ:', voice_test: 'ಧ್ವನಿ ಪರೀಕ್ಷಿಸಿ', speed: 'ವೇಗ',
    nv_title: 'ಈ ಸಾಧನದಲ್ಲಿ ಇಂಗ್ಲಿಷ್ ಧ್ವನಿ ಇಲ್ಲ',
    nv_short: 'ಪದ ಹುಡುಕಲು ಅರ್ಥ, ವಾಕ್ಯ ಮತ್ತು ಕಲಸಿದ ಅಕ್ಷರಗಳ ಸಹಾಯ ಪಡೆಯಿರಿ.',
    nv_help: 'ಆಗಲೂ ಆಡಬಹುದು: ಅರ್ಥ, ವಾಕ್ಯ ಮತ್ತು ಕಲಸಿದ ಅಕ್ಷರಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತದೆ. Android ನಲ್ಲಿ Chrome ನಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಇಂಗ್ಲಿಷ್ ಧ್ವನಿ ಇರುತ್ತದೆ; ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ ಸ್ಪೀಚ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ “English (India)” ಸೇರಿಸಿ.',
    stats_h: 'ನನ್ನ ಪ್ರಗತಿ', st_words: 'ಪ್ರಯತ್ನಿಸಿದ ಪದಗಳು', st_acc: 'ಸರಿ', st_streak: 'ಸತತ ಸರಿ ದಾಖಲೆ', st_review: 'ಮತ್ತೆ ಅಭ್ಯಾಸ ಬಾಕಿ',
    reset_progress: 'ಪ್ರಗತಿ ಮರುಹೊಂದಿಸಿ', confirm_progress: 'ನಿಮ್ಮ ಅಂಕಗಳು ಮತ್ತು ತಪ್ಪುಗಳ ಪಟ್ಟಿಯನ್ನು ಅಳಿಸಬೇಕೇ? ನಿಮ್ಮ ಸ್ವಂತ ಪದಪಟ್ಟಿ ಉಳಿಯುತ್ತದೆ.', reset_done: 'ಪ್ರಗತಿ ಅಳಿಸಲಾಗಿದೆ.',
    word_x_of_y: 'ಪದ {i} / {n}', streak: 'ಸತತ ಸರಿ ಉತ್ತರಗಳು', end_round: 'ಸುತ್ತು ಮುಗಿಸಿ',
    hear_word: 'ಪದ ಕೇಳಿ', hear_sent: 'ವಾಕ್ಯದಲ್ಲಿ ಕೇಳಿ', hear_slow: 'ನಿಧಾನವಾಗಿ ಕೇಳಿ',
    meaning: 'ಅರ್ಥ', sentence_lbl: 'ವಾಕ್ಯ', starts_with: 'ಮೊದಲ ಅಕ್ಷರ',
    hints: 'ಸುಳಿವುಗಳು', hint_first: 'ಮೊದಲ ಅಕ್ಷರ', hint_len: 'ಎಷ್ಟು ಅಕ್ಷರಗಳು', hint_jumble: 'ಕಲಸಿದ ಅಕ್ಷರಗಳು',
    hints_used_n: 'ಪಡೆದ ಸುಳಿವುಗಳು: {n}', hint_free: 'ಧ್ವನಿ ಇಲ್ಲದಾಗ ಕಲಸಿದ ಅಕ್ಷರಗಳು ಉಚಿತ.', letters_n: '{n} ಅಕ್ಷರಗಳು',
    jumble_aria: 'ಕಲಸಿದ ಅಕ್ಷರಗಳು, ಟೈಪ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ', tap_letter: '{l} ಬರೆಯಿರಿ', space_key: 'ಸ್ಪೇಸ್',
    your_spelling: 'ನಿಮ್ಮ ಸ್ಪೆಲ್ಲಿಂಗ್', answer_ph: 'ಸ್ಪೆಲ್ಲಿಂಗ್ ಟೈಪ್ ಮಾಡಿ', backspace: 'ಕೊನೆಯ ಅಕ್ಷರ ಅಳಿಸಿ', check: 'ಪರಿಶೀಲಿಸಿ', show_answer: 'ಉತ್ತರ ತೋರಿಸಿ',
    fb_empty: 'ಮೊದಲು ಸ್ಪೆಲ್ಲಿಂಗ್ ಟೈಪ್ ಮಾಡಿ.', fb_retry: 'ಬಹುತೇಕ ಸರಿ! ಕೆಂಪು ಅಕ್ಷರಗಳನ್ನು ಸರಿಪಡಿಸಿ ಇನ್ನೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ.', fb_missing: 'ಬಿಟ್ಟುಹೋದ ಅಕ್ಷರಗಳು: {n}',
    lg_ok: 'ಸರಿ', lg_bad: 'ತಪ್ಪು', lg_miss: 'ಬಿಟ್ಟುಹೋಗಿದೆ',
    fb_ok: 'ಸರಿ! ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ.', fb_ok2: 'ಎರಡನೇ ಪ್ರಯತ್ನದಲ್ಲಿ ಸರಿ!',
    fb_alt: '“{alt}” ಅಮೆರಿಕನ್ ಸ್ಪೆಲ್ಲಿಂಗ್. ಭಾರತದಲ್ಲಿ ನಾವು ಸಾಮಾನ್ಯವಾಗಿ “{w}” ಎಂದು ಬರೆಯುತ್ತೇವೆ.',
    fb_bad: 'ಈ ಬಾರಿ ಅಲ್ಲ. ಸರಿಯಾದ ಸ್ಪೆಲ್ಲಿಂಗ್:', fb_shown: 'ಇಗೋ ಸರಿಯಾದ ಸ್ಪೆಲ್ಲಿಂಗ್:',
    you_wrote: 'ನೀವು ಬರೆದದ್ದು', right_spelling: 'ಸರಿಯಾದ ಸ್ಪೆಲ್ಲಿಂಗ್',
    fb_learn: 'ಹಳದಿ ಅಕ್ಷರಗಳನ್ನು ನೋಡಿ, ಅದೇ ಕಠಿಣ ಭಾಗ. ಪದವನ್ನು ಹೇಳಿ, ಒಮ್ಮೆ ಜೋರಾಗಿ ಸ್ಪೆಲ್ಲಿಂಗ್ ಹೇಳಿ.',
    next_word: 'ಮುಂದಿನ ಪದ', see_result: 'ನನ್ನ ಅಂಕ ನೋಡಿ',
    sum_title: 'ಸುತ್ತು ಮುಗಿಯಿತು!', sum_score: '{n} ರಲ್ಲಿ {c} ಸರಿ',
    praise_1: 'ಒಳ್ಳೆಯ ಪ್ರಯತ್ನ! ಕೆಳಗಿನ ಪದಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ ಮತ್ತೆ ಆಡಿ.', praise_2: 'ಶಹಬ್ಬಾಸ್! ಇನ್ನೂ ಸ್ವಲ್ಪ ಅಭ್ಯಾಸ ಮಾಡಿದರೆ ಎಲ್ಲವೂ ಸರಿಯಾಗುತ್ತದೆ.', praise_3: 'ಅದ್ಭುತ ಸ್ಪೆಲ್ಲಿಂಗ್!',
    sum_streak: 'ಸತತ ಸರಿ: {n}', sum_hints: 'ಪಡೆದ ಸುಳಿವುಗಳು: {n}', new_best: 'ಹೊಸ ಅತ್ಯುತ್ತಮ ಅಂಕ!',
    sum_mistakes: 'ಅಭ್ಯಾಸಕ್ಕೆ ಪದಗಳು', sum_perfect: 'ಒಂದೂ ತಪ್ಪಿಲ್ಲ, ಪರಿಪೂರ್ಣ ಸುತ್ತು! 🎉',
    practise_these: 'ಈ ಪದಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ', new_round: 'ಹೊಸ ಸುತ್ತು', change_level: 'ಹಂತ ಬದಲಿಸಿ', listen_to: '{w} ಕೇಳಿ',
    bee_setup_h: 'ತರಗತಿಯಲ್ಲಿ ಸ್ಪೆಲ್ಲಿಂಗ್ ಸ್ಪರ್ಧೆ',
    bee_help: 'ಇದನ್ನು ಪ್ರೊಜೆಕ್ಟರ್ ಅಥವಾ ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ತೋರಿಸಿ. ಆಟಗಾರರು ಅಥವಾ ತಂಡಗಳು ಸರದಿಯಂತೆ ಆಡುತ್ತಾರೆ: ಪ್ರತಿಯೊಬ್ಬರೂ ಒಂದು ಪದ ಕೇಳಿ ಸ್ಪೆಲ್ಲಿಂಗ್ ಟೈಪ್ ಮಾಡುತ್ತಾರೆ ಅಥವಾ ಬಾಯಿಂದ ಹೇಳುತ್ತಾರೆ, ಶಿಕ್ಷಕರು ತೀರ್ಪು ಕೊಡುತ್ತಾರೆ.',
    players: 'ಆಟಗಾರರು ಅಥವಾ ತಂಡಗಳು', player_n: 'ಆಟಗಾರ {n}', add_player: 'ಆಟಗಾರರನ್ನು ಸೇರಿಸಿ', remove_player: 'ಆಟಗಾರ {n} ತೆಗೆದುಹಾಕಿ',
    level_lbl: 'ಪದಗಳ ಹಂತ', per_player: 'ಪ್ರತಿ ಆಟಗಾರನಿಗೆ ಪದಗಳು', game_type: 'ಆಟ', type_points: 'ಅಂಕಗಳು', type_ko: 'ನಾಕ್‌ಔಟ್',
    type_points_help: 'ಎಲ್ಲರಿಗೂ ಸಮಾನ ಸಂಖ್ಯೆಯ ಪದಗಳು. ಹೆಚ್ಚು ಸರಿ ಪದಗಳನ್ನು ಹೇಳಿದವರು ಗೆಲ್ಲುತ್ತಾರೆ.',
    type_ko_help: 'ಪ್ರತಿ ಆಟಗಾರನಿಗೆ 3 ಜೀವಗಳು. ತಪ್ಪು ಸ್ಪೆಲ್ಲಿಂಗ್‌ಗೆ ಒಂದು ಜೀವ ಹೋಗುತ್ತದೆ; ಕೊನೆಯಲ್ಲಿ ಉಳಿದವರು ಗೆಲ್ಲುತ್ತಾರೆ.',
    start_bee: 'ಸ್ಪರ್ಧೆ ಪ್ರಾರಂಭಿಸಿ', bee_how_h: 'ನಡೆಸುವುದು ಹೇಗೆ',
    bee_step1: 'ಆಟಗಾರರ ಅಥವಾ ತಂಡಗಳ ಹೆಸರು ಬರೆದು, ಹಂತ ಆಯ್ಕೆಮಾಡಿ.',
    bee_step2: 'ಪ್ರಾರಂಭಿಸಿ ಒತ್ತಿ ಪೂರ್ಣ ಪರದೆ ಮಾಡಿ. ಆ್ಯಪ್ ಪದವನ್ನು ಜೋರಾಗಿ ಓದುತ್ತದೆ.',
    bee_step3: 'ಆಟಗಾರ ಪದವನ್ನು ಟೈಪ್ ಮಾಡುತ್ತಾನೆ, ಅಥವಾ ಬಾಯಿಂದ ಸ್ಪೆಲ್ಲಿಂಗ್ ಹೇಳುತ್ತಾನೆ; ನೀವು ✓ ಅಥವಾ ✗ ಒತ್ತಿ.',
    bee_step4: 'ಎಲ್ಲರೂ ಸರಿಯಾದ ಸ್ಪೆಲ್ಲಿಂಗ್ ನೋಡಿದ ನಂತರ ಮುಂದಿನ ಆಟಗಾರ ಒತ್ತಿ.',
    turn_of: '{name}, ನಿಮ್ಮ ಸರದಿ!', bee_round: 'ಪದ {i} / {n}', judge_help: 'ಬಾಯಿಂದ ಸ್ಪೆಲ್ಲಿಂಗ್ ಹೇಳಿದರೇ? ಶಿಕ್ಷಕರೇ, ತೀರ್ಪು ಕೊಡಿ:', judge_ok: 'ಸರಿ', judge_bad: 'ತಪ್ಪು',
    next_player: 'ಮುಂದಿನ ಆಟಗಾರ', see_winner: 'ವಿಜೇತರನ್ನು ನೋಡಿ', end_game: 'ಆಟ ಮುಗಿಸಿ', confirm_end: 'ಆಟವನ್ನು ಈಗಲೇ ಮುಗಿಸಿ ಅಂಕಗಳನ್ನು ತೋರಿಸಬೇಕೇ?',
    lives_n: '{n} ಜೀವಗಳು ಉಳಿದಿವೆ', out: 'ಔಟ್', winner_is: '{name} ಗೆದ್ದರು! 🎉', winners_tie: 'ಸಮಬಲ: {names}',
    final_note: 'ಪ್ರತಿ ಆಟಗಾರನಿಗೂ ಚಪ್ಪಾಳೆ, ಇಂದು ಎಲ್ಲರೂ ಅಭ್ಯಾಸ ಮಾಡಿದರು!', col_player: 'ಆಟಗಾರ', col_lives: 'ಜೀವಗಳು',
    play_again: 'ಮತ್ತೆ ಆಡಿ', change_players: 'ಆಟಗಾರರನ್ನು ಬದಲಿಸಿ',
    my_list_h: 'ನನ್ನ ಪದಪಟ್ಟಿ',
    my_list_help: 'ಶಿಕ್ಷಕರಿಗೆ: ಇಂಗ್ಲಿಷ್ ಪದಗಳನ್ನು ಸಾಲಿಗೆ ಒಂದರಂತೆ ಟೈಪ್ ಅಥವಾ ಪೇಸ್ಟ್ ಮಾಡಿ. ಬೇಕಿದ್ದರೆ | ಚಿಹ್ನೆಯ ನಂತರ ವಾಕ್ಯ ಮತ್ತು ಅರ್ಥವನ್ನೂ ಬರೆಯಿರಿ.',
    format_lbl: 'ರೂಪ:', my_list_format: 'ಪದ | ವಾಕ್ಯ | ಅರ್ಥ', words_box: 'ಪದಗಳು',
    save_list: 'ಪಟ್ಟಿ ಉಳಿಸಿ', example_list: 'ಉದಾಹರಣೆ', share_list: 'ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ',
    list_saved: '{n} ಪದಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ. ಅಭ್ಯಾಸ ಅಥವಾ ತರಗತಿ ಸ್ಪರ್ಧೆಯಲ್ಲಿ “ನನ್ನ ಪಟ್ಟಿ” ಆಯ್ಕೆಮಾಡಿ.', list_skipped: '{n} ಸಾಲುಗಳನ್ನು ಬಿಡಲಾಗಿದೆ: ಇಂಗ್ಲಿಷ್ ಅಕ್ಷರಗಳನ್ನು ಮಾತ್ರ ಬಳಸಿ.',
    list_empty: 'ಪಟ್ಟಿ ಖಾಲಿಯಾಗಿದೆ. ಮೊದಲು ಕೆಲವು ಪದಗಳನ್ನು ಬರೆಯಿರಿ.', list_cleared: 'ಪಟ್ಟಿ ಅಳಿಸಲಾಗಿದೆ.', confirm_clear_list: 'ನಿಮ್ಮ ಪದಪಟ್ಟಿಯನ್ನು ಅಳಿಸಬೇಕೇ?', confirm_replace_list: 'ಇದರಿಂದ ನಿಮ್ಮ ಈಗಿನ ಪದಪಟ್ಟಿ ({n} ಪದಗಳು) ಬದಲಾಗುತ್ತದೆ. ಮುಂದುವರಿಯಬೇಕೇ?',
    share_done: 'ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ! ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಕಳುಹಿಸಿ: ಪಟ್ಟಿ ಅವರ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.',
    wa_list: 'ಸ್ಪೆಲ್ಲಿಂಗ್ ಅಭ್ಯಾಸ: ಈ ವಾರದ {n} ಪದಗಳು. ಇಲ್ಲಿ ತೆರೆಯಿರಿ: {url}',
    shared_found: 'ಯಾರೋ {n} ಪದಗಳ ಪಟ್ಟಿಯನ್ನು ನಿಮ್ಮೊಂದಿಗೆ ಹಂಚಿಕೊಂಡಿದ್ದಾರೆ.', use_shared: 'ಈ ಪಟ್ಟಿ ಬಳಸಿ', wa_share: 'WhatsApp ನಲ್ಲಿ ಕಳುಹಿಸಿ',
    print_h: 'ಪದಪಟ್ಟಿಗಳನ್ನು ನೋಡಿ ಮತ್ತು ಮುದ್ರಿಸಿ', print_list: 'ಪದಪಟ್ಟಿ ಮುದ್ರಿಸಿ', print_test: 'ಸ್ಪೆಲ್ಲಿಂಗ್ ಪರೀಕ್ಷೆ ಮುದ್ರಿಸಿ',
    col_word: 'ಪದ', col_sentence: 'ಉದಾಹರಣೆ ವಾಕ್ಯ', col_listen: 'ಕೇಳಿ',
    print_title: 'ಸ್ಪೆಲ್ಲಿಂಗ್ ಪಟ್ಟಿ: {level}', test_title: 'ಸ್ಪೆಲ್ಲಿಂಗ್ ಪರೀಕ್ಷೆ: {level}',
    print_name: 'ಹೆಸರು', print_class: 'ತರಗತಿ', print_date: 'ದಿನಾಂಕ',
    test_instr: 'ಶಿಕ್ಷಕರು ಹೇಳುವುದನ್ನು ಗಮನವಿಟ್ಟು ಕೇಳಿ ಪ್ರತಿ ಪದವನ್ನು ಬರೆಯಿರಿ. ಸುಳಿವಾಗಿ ಅರ್ಥ ನೀಡಲಾಗಿದೆ.', answer_key: 'ಉತ್ತರಗಳು (ಶಿಕ್ಷಕರಿಗೆ)'
  }
  ,
  ml: {
    app_title: 'സ്പെല്ലിംഗ് ബീ',
    intro: 'ഇംഗ്ലീഷ് വാക്ക് കേട്ട് അതിന്റെ സ്പെല്ലിംഗ് എഴുതൂ. നിങ്ങളുടെ ഭാഷയിൽ അർത്ഥം അറിയൂ, സൂചനകൾ നേടൂ, ക്ലാസിൽ സ്പെല്ലിംഗ് ബീ കളിക്കൂ, സ്പെല്ലിംഗ് ടെസ്റ്റ് പ്രിന്റ് ചെയ്യൂ.',
    tab_practise: 'പരിശീലനം', tab_bee: 'ക്ലാസ് മത്സരം', tab_lists: 'വാക്കുകളുടെ പട്ടിക',
    choose_level: 'നില തിരഞ്ഞെടുക്കുക', level_n: 'നില {n}', class_n: 'ക്ലാസ് {n}', n_words: '{n} വാക്കുകൾ', best_n: 'മികച്ചത് {s}/{n}',
    my_list: 'എന്റെ പട്ടിക', review_lvl: 'എന്റെ തെറ്റുകൾ', review_none: 'ഇതുവരെ തെറ്റുകളില്ല', custom_none: '“വാക്കുകളുടെ പട്ടിക”യിൽ വാക്കുകൾ ചേർക്കുക',
    opt_second: 'രണ്ടാമതൊരു അവസരം നൽകുക', opt_auto: 'ഓരോ വാക്കും തനിയെ പറയട്ടെ', start_round: 'ആരംഭിക്കുക', round_info: 'ഈ റൗണ്ടിൽ {n} വാക്കുകൾ',
    help_h: 'എങ്ങനെ ഉപയോഗിക്കാം · ക്ലാസിനുള്ള ആശയങ്ങൾ',
    tip1: 'നില തിരഞ്ഞെടുത്ത് <b>ആരംഭിക്കുക</b> അമർത്തുക. വാക്ക് കേൾക്കൂ 🔊, വാക്യത്തിൽ കേൾക്കൂ 💬 അല്ലെങ്കിൽ പതുക്കെ കേൾക്കൂ 🐢. എന്നിട്ട് സ്പെല്ലിംഗ് ടൈപ്പ് ചെയ്ത് <b>പരിശോധിക്കുക</b> അമർത്തുക (അല്ലെങ്കിൽ Enter).',
    tip2: 'കുടുങ്ങിയോ? സൂചന എടുക്കൂ: ആദ്യ അക്ഷരം, എത്ര അക്ഷരങ്ങൾ, അല്ലെങ്കിൽ കുഴഞ്ഞ അക്ഷരങ്ങൾ. ഫോണിലോ സ്മാർട്ട്ബോർഡിലോ ടൈപ്പ് ചെയ്യുന്നതിനു പകരം കുഴഞ്ഞ അക്ഷരങ്ങളിൽ തൊടാം.',
    tip3: 'പച്ച അക്ഷരങ്ങൾ ശരി, ചുവപ്പ് അക്ഷരങ്ങൾ തിരുത്തണം, കുത്തുവരയുള്ള കള്ളി എന്നാൽ ഒരു അക്ഷരം വിട്ടുപോയി. തെറ്റിയ വാക്കുകൾ <b>എന്റെ തെറ്റുകൾ</b> എന്നതിലേക്ക് പോകും, പിന്നീട് വീണ്ടും പരിശീലിക്കാം.',
    tip4: 'അധ്യാപകർക്ക്: ഈ ആഴ്ചയിലെ വാക്കുകൾ <b>വാക്കുകളുടെ പട്ടിക</b>യിൽ വരിക്ക് ഒന്ന് എന്ന കണക്കിൽ എഴുതുക. പട്ടികയോ ഉത്തരങ്ങളോടു കൂടിയ സ്പെല്ലിംഗ് ടെസ്റ്റോ പ്രിന്റ് ചെയ്യാം, അല്ലെങ്കിൽ WhatsApp ലിങ്കായി കുട്ടികൾക്ക് അയയ്ക്കാം.',
    tip5: 'ക്ലാസ് പ്രവർത്തനം: പ്രൊജക്ടറിൽ <b>ക്ലാസ് മത്സരം</b> തുറക്കുക, 2–4 ടീമുകൾ ഉണ്ടാക്കി ഊഴമനുസരിച്ച് സ്പെല്ലിംഗ് ചോദിക്കുക. കുട്ടികൾക്ക് ഉറക്കെ സ്പെല്ലിംഗ് പറയാം, നിങ്ങൾ ✓ അല്ലെങ്കിൽ ✗ അമർത്തുക.',
    tip6: 'ഇംഗ്ലീഷ് ശബ്ദമില്ലേ? ആപ്പ് അർത്ഥവും വിട്ട ഭാഗമുള്ള വാക്യവും കുഴഞ്ഞ അക്ഷരങ്ങളും കാണിക്കും, അതിനാൽ കുട്ടികൾക്ക് എന്നിട്ടും കളിക്കാം. Windows-ൽ Settings → Time &amp; language → Speech-ൽ പോയി “English (India)” ശബ്ദം ചേർക്കുക.',
    voice_h: 'ശബ്ദം', voice_lbl: 'ഇംഗ്ലീഷ് ശബ്ദം', voice_auto: 'സ്വയം (ആദ്യം ഇന്ത്യൻ ഇംഗ്ലീഷ്)', voice_using: 'ശബ്ദം:', voice_test: 'ശബ്ദം പരിശോധിക്കുക', speed: 'വേഗത',
    nv_title: 'ഈ ഉപകരണത്തിൽ ഇംഗ്ലീഷ് ശബ്ദമില്ല',
    nv_short: 'വാക്ക് കണ്ടെത്താൻ അർത്ഥം, വാക്യം, കുഴഞ്ഞ അക്ഷരങ്ങൾ എന്നിവയുടെ സഹായം തേടൂ.',
    nv_help: 'എന്നിട്ടും കളിക്കാം: അർത്ഥവും വാക്യവും കുഴഞ്ഞ അക്ഷരങ്ങളും കാണിക്കും. Android-ലെ Chrome-ൽ സാധാരണ ഇംഗ്ലീഷ് ശബ്ദം ഉണ്ടാകും; കമ്പ്യൂട്ടറിൽ സ്പീച്ച് ക്രമീകരണങ്ങളിൽ “English (India)” ചേർക്കുക.',
    stats_h: 'എന്റെ പുരോഗതി', st_words: 'ശ്രമിച്ച വാക്കുകൾ', st_acc: 'ശരി', st_streak: 'തുടർച്ചയായ ശരിയുടെ റെക്കോർഡ്', st_review: 'വീണ്ടും പരിശീലിക്കാൻ',
    reset_progress: 'പുരോഗതി റീസെറ്റ് ചെയ്യുക', confirm_progress: 'നിങ്ങളുടെ സ്കോറുകളും തെറ്റുകളുടെ പട്ടികയും മായ്ക്കണോ? നിങ്ങളുടെ സ്വന്തം വാക്കുപട്ടിക നിലനിൽക്കും.', reset_done: 'പുരോഗതി മായ്ച്ചു.',
    word_x_of_y: 'വാക്ക് {i} / {n}', streak: 'തുടർച്ചയായ ശരിയുത്തരങ്ങൾ', end_round: 'റൗണ്ട് അവസാനിപ്പിക്കുക',
    hear_word: 'വാക്ക് കേൾക്കൂ', hear_sent: 'വാക്യത്തിൽ കേൾക്കൂ', hear_slow: 'പതുക്കെ കേൾക്കൂ',
    meaning: 'അർത്ഥം', sentence_lbl: 'വാക്യം', starts_with: 'ആദ്യ അക്ഷരം',
    hints: 'സൂചനകൾ', hint_first: 'ആദ്യ അക്ഷരം', hint_len: 'എത്ര അക്ഷരങ്ങൾ', hint_jumble: 'കുഴഞ്ഞ അക്ഷരങ്ങൾ',
    hints_used_n: 'എടുത്ത സൂചനകൾ: {n}', hint_free: 'ശബ്ദമില്ലാത്തപ്പോൾ കുഴഞ്ഞ അക്ഷരങ്ങൾ സൗജന്യം.', letters_n: '{n} അക്ഷരങ്ങൾ',
    jumble_aria: 'കുഴഞ്ഞ അക്ഷരങ്ങൾ, ടൈപ്പ് ചെയ്യാൻ തൊടുക', tap_letter: '{l} എഴുതുക', space_key: 'സ്പേസ്',
    your_spelling: 'നിങ്ങളുടെ സ്പെല്ലിംഗ്', answer_ph: 'സ്പെല്ലിംഗ് ടൈപ്പ് ചെയ്യുക', backspace: 'അവസാന അക്ഷരം മായ്ക്കുക', check: 'പരിശോധിക്കുക', show_answer: 'ഉത്തരം കാണിക്കുക',
    fb_empty: 'ആദ്യം സ്പെല്ലിംഗ് ടൈപ്പ് ചെയ്യുക.', fb_retry: 'ഏതാണ്ട് ശരി! ചുവപ്പ് അക്ഷരങ്ങൾ തിരുത്തി ഒരിക്കൽ കൂടി ശ്രമിക്കൂ.', fb_missing: 'വിട്ടുപോയ അക്ഷരങ്ങൾ: {n}',
    lg_ok: 'ശരി', lg_bad: 'തെറ്റ്', lg_miss: 'വിട്ടുപോയത്',
    fb_ok: 'ശരി! വളരെ നന്നായി.', fb_ok2: 'രണ്ടാം ശ്രമത്തിൽ ശരി!',
    fb_alt: '“{alt}” അമേരിക്കൻ സ്പെല്ലിംഗ് ആണ്. ഇന്ത്യയിൽ നമ്മൾ സാധാരണ “{w}” എന്നാണ് എഴുതുന്നത്.',
    fb_bad: 'ഇത്തവണ ശരിയായില്ല. ശരിയായ സ്പെല്ലിംഗ്:', fb_shown: 'ഇതാ ശരിയായ സ്പെല്ലിംഗ്:',
    you_wrote: 'നിങ്ങൾ എഴുതിയത്', right_spelling: 'ശരിയായ സ്പെല്ലിംഗ്',
    fb_learn: 'മഞ്ഞ അക്ഷരങ്ങൾ നോക്കൂ, അതാണ് പ്രയാസമുള്ള ഭാഗം. വാക്ക് പറഞ്ഞ് ഒരിക്കൽ ഉറക്കെ സ്പെല്ലിംഗ് പറയൂ.',
    next_word: 'അടുത്ത വാക്ക്', see_result: 'എന്റെ സ്കോർ കാണുക',
    sum_title: 'റൗണ്ട് പൂർത്തിയായി!', sum_score: '{n}-ൽ {c} ശരി',
    praise_1: 'നല്ല ശ്രമം! താഴെയുള്ള വാക്കുകൾ പരിശീലിച്ച് വീണ്ടും കളിക്കൂ.', praise_2: 'മിടുക്ക്! കുറച്ചുകൂടി പരിശീലിച്ചാൽ എല്ലാം ശരിയാകും.', praise_3: 'ഗംഭീര സ്പെല്ലിംഗ്!',
    sum_streak: 'തുടർച്ചയായ ശരി: {n}', sum_hints: 'എടുത്ത സൂചനകൾ: {n}', new_best: 'പുതിയ മികച്ച സ്കോർ!',
    sum_mistakes: 'പരിശീലിക്കാനുള്ള വാക്കുകൾ', sum_perfect: 'ഒരു തെറ്റുമില്ല, പൂർണ്ണമായ റൗണ്ട്! 🎉',
    practise_these: 'ഈ വാക്കുകൾ പരിശീലിക്കുക', new_round: 'പുതിയ റൗണ്ട്', change_level: 'നില മാറ്റുക', listen_to: '{w} കേൾക്കുക',
    bee_setup_h: 'ക്ലാസിൽ സ്പെല്ലിംഗ് മത്സരം',
    bee_help: 'ഇത് പ്രൊജക്ടറിലോ സ്മാർട്ട്ബോർഡിലോ കാണിക്കുക. കളിക്കാരോ ടീമുകളോ ഊഴമനുസരിച്ച് കളിക്കും: ഓരോരുത്തരും ഒരു വാക്ക് കേട്ട് സ്പെല്ലിംഗ് ടൈപ്പ് ചെയ്യും അല്ലെങ്കിൽ ഉറക്കെ പറയും, അധ്യാപകർ വിധി പറയും.',
    players: 'കളിക്കാർ അല്ലെങ്കിൽ ടീമുകൾ', player_n: 'കളിക്കാരൻ {n}', add_player: 'കളിക്കാരനെ ചേർക്കുക', remove_player: 'കളിക്കാരൻ {n}-നെ നീക്കുക',
    level_lbl: 'വാക്കുകളുടെ നില', per_player: 'ഓരോ കളിക്കാരനും വാക്കുകൾ', game_type: 'കളി', type_points: 'പോയിന്റ്', type_ko: 'നോക്കൗട്ട്',
    type_points_help: 'എല്ലാവർക്കും ഒരേ എണ്ണം വാക്കുകൾ. കൂടുതൽ ശരിയാക്കുന്നയാൾ ജയിക്കും.',
    type_ko_help: 'ഓരോ കളിക്കാരനും 3 ജീവൻ. തെറ്റായ സ്പെല്ലിംഗിന് ഒരു ജീവൻ പോകും; അവസാനം ബാക്കിയാകുന്നയാൾ ജയിക്കും.',
    start_bee: 'മത്സരം ആരംഭിക്കുക', bee_how_h: 'എങ്ങനെ നടത്താം',
    bee_step1: 'കളിക്കാരുടെയോ ടീമുകളുടെയോ പേരുകൾ എഴുതി നില തിരഞ്ഞെടുക്കുക.',
    bee_step2: 'ആരംഭിക്കുക അമർത്തി പൂർണ്ണ സ്ക്രീനാക്കുക. ആപ്പ് വാക്ക് ഉറക്കെ വായിക്കും.',
    bee_step3: 'കളിക്കാരൻ വാക്ക് ടൈപ്പ് ചെയ്യും, അല്ലെങ്കിൽ ഉറക്കെ സ്പെല്ലിംഗ് പറയും; നിങ്ങൾ ✓ അല്ലെങ്കിൽ ✗ അമർത്തുക.',
    bee_step4: 'എല്ലാവരും ശരിയായ സ്പെല്ലിംഗ് കണ്ടശേഷം അടുത്ത കളിക്കാരൻ അമർത്തുക.',
    turn_of: '{name}, നിങ്ങളുടെ ഊഴം!', bee_round: 'വാക്ക് {i} / {n}', judge_help: 'ഉറക്കെ സ്പെല്ലിംഗ് പറഞ്ഞോ? അധ്യാപകരേ, വിധി പറയൂ:', judge_ok: 'ശരി', judge_bad: 'തെറ്റ്',
    next_player: 'അടുത്ത കളിക്കാരൻ', see_winner: 'വിജയിയെ കാണുക', end_game: 'കളി അവസാനിപ്പിക്കുക', confirm_end: 'കളി ഇപ്പോൾ അവസാനിപ്പിച്ച് സ്കോറുകൾ കാണിക്കണോ?',
    lives_n: '{n} ജീവൻ ബാക്കി', out: 'പുറത്ത്', winner_is: '{name} ജയിച്ചു! 🎉', winners_tie: 'സമനില: {names}',
    final_note: 'ഓരോ കളിക്കാരനും കൈയടി, ഇന്ന് എല്ലാവരും പരിശീലിച്ചു!', col_player: 'കളിക്കാരൻ', col_lives: 'ജീവൻ',
    play_again: 'വീണ്ടും കളിക്കുക', change_players: 'കളിക്കാരെ മാറ്റുക',
    my_list_h: 'എന്റെ വാക്കുപട്ടിക',
    my_list_help: 'അധ്യാപകർക്ക്: ഇംഗ്ലീഷ് വാക്കുകൾ വരിക്ക് ഒന്ന് എന്ന കണക്കിൽ ടൈപ്പ് ചെയ്യുക അല്ലെങ്കിൽ പേസ്റ്റ് ചെയ്യുക. വേണമെങ്കിൽ | ചിഹ്നത്തിനു ശേഷം വാക്യവും അർത്ഥവും എഴുതാം.',
    format_lbl: 'രീതി:', my_list_format: 'വാക്ക് | വാക്യം | അർത്ഥം', words_box: 'വാക്കുകൾ',
    save_list: 'പട്ടിക സേവ് ചെയ്യുക', example_list: 'ഉദാഹരണം', share_list: 'ലിങ്ക് പങ്കിടുക',
    list_saved: '{n} വാക്കുകൾ സേവ് ചെയ്തു. പരിശീലനത്തിലോ ക്ലാസ് മത്സരത്തിലോ “എന്റെ പട്ടിക” തിരഞ്ഞെടുക്കുക.', list_skipped: '{n} വരികൾ ഒഴിവാക്കി: ഇംഗ്ലീഷ് അക്ഷരങ്ങൾ മാത്രം ഉപയോഗിക്കുക.',
    list_empty: 'പട്ടിക ശൂന്യമാണ്. ആദ്യം കുറച്ച് വാക്കുകൾ എഴുതുക.', list_cleared: 'പട്ടിക മായ്ച്ചു.', confirm_clear_list: 'നിങ്ങളുടെ വാക്കുപട്ടിക ഇല്ലാതാക്കണോ?', confirm_replace_list: 'ഇത് നിങ്ങളുടെ ഇപ്പോഴത്തെ വാക്കുപട്ടിക ({n} വാക്കുകൾ) മാറ്റും. തുടരണോ?',
    share_done: 'ലിങ്ക് പകർത്തി! കുട്ടികൾക്ക് അയയ്ക്കൂ: പട്ടിക അവരുടെ ബ്രൗസറിൽ തുറക്കും.',
    wa_list: 'സ്പെല്ലിംഗ് പരിശീലനം: ഈ ആഴ്ചയിലെ {n} വാക്കുകൾ. ഇവിടെ തുറക്കൂ: {url}',
    shared_found: 'ആരോ {n} വാക്കുകളുള്ള ഒരു പട്ടിക നിങ്ങളുമായി പങ്കിട്ടു.', use_shared: 'ഈ പട്ടിക ഉപയോഗിക്കുക', wa_share: 'WhatsApp-ൽ അയയ്ക്കുക',
    print_h: 'വാക്കുപട്ടികകൾ കാണുക, പ്രിന്റ് ചെയ്യുക', print_list: 'വാക്കുപട്ടിക പ്രിന്റ് ചെയ്യുക', print_test: 'സ്പെല്ലിംഗ് ടെസ്റ്റ് പ്രിന്റ് ചെയ്യുക',
    col_word: 'വാക്ക്', col_sentence: 'ഉദാഹരണ വാക്യം', col_listen: 'കേൾക്കുക',
    print_title: 'സ്പെല്ലിംഗ് പട്ടിക: {level}', test_title: 'സ്പെല്ലിംഗ് ടെസ്റ്റ്: {level}',
    print_name: 'പേര്', print_class: 'ക്ലാസ്', print_date: 'തീയതി',
    test_instr: 'അധ്യാപകർ പറയുന്നത് ശ്രദ്ധിച്ചു കേട്ട് ഓരോ വാക്കും എഴുതുക. സൂചനയായി അർത്ഥം നൽകിയിട്ടുണ്ട്.', answer_key: 'ഉത്തരങ്ങൾ (അധ്യാപകർക്ക്)'
  },
  ur: {
    app_title: 'اسپیلنگ بی',
    intro: 'انگریزی لفظ سنیں اور اس کی اسپیلنگ لکھیں۔ اپنی زبان میں معنی جانیں، اشارے لیں، کلاس میں اسپیلنگ بی کھیلیں اور اسپیلنگ ٹیسٹ پرنٹ کریں۔',
    tab_practise: 'مشق', tab_bee: 'کلاس مقابلہ', tab_lists: 'الفاظ کی فہرستیں',
    choose_level: 'سطح چنیں', level_n: 'سطح {n}', class_n: 'جماعت {n}', n_words: '{n} الفاظ', best_n: 'بہترین {s}/{n}',
    my_list: 'میری فہرست', review_lvl: 'میری غلطیاں', review_none: 'ابھی کوئی غلطی نہیں', custom_none: '“الفاظ کی فہرستیں” میں الفاظ شامل کریں',
    opt_second: 'دوسرا موقع دیں', opt_auto: 'ہر لفظ خود بولے', start_round: 'شروع کریں', round_info: 'اس راؤنڈ میں {n} الفاظ',
    help_h: 'استعمال کیسے کریں · کلاس کے لیے خیالات',
    tip1: 'سطح چنیں اور <b>شروع کریں</b> دبائیں۔ لفظ سنیں 🔊، جملے میں سنیں 💬 یا آہستہ سنیں 🐢۔ پھر اسپیلنگ ٹائپ کریں اور <b>جانچیں</b> دبائیں (یا Enter)۔',
    tip2: 'اٹک گئے؟ اشارہ لیں: پہلا حرف، کتنے حروف، یا الجھے ہوئے حروف۔ فون یا اسمارٹ بورڈ پر ٹائپ کرنے کے بجائے الجھے حروف پر ٹیپ کریں۔',
    tip3: 'ہرے حروف صحیح ہیں، لال حروف ٹھیک کرنے ہیں اور نقطوں والا خانہ مطلب کوئی حرف چھوٹ گیا۔ غلط الفاظ <b>میری غلطیاں</b> میں چلے جاتے ہیں تاکہ آپ بعد میں پھر مشق کر سکیں۔',
    tip4: 'اساتذہ کے لیے: اس ہفتے کے الفاظ <b>الفاظ کی فہرستیں</b> میں لکھیں، ہر لائن میں ایک۔ فہرست یا جوابات والا اسپیلنگ ٹیسٹ پرنٹ کریں، یا WhatsApp لنک بنا کر طلبہ کو بھیجیں۔',
    tip5: 'کلاس کی سرگرمی: پروجیکٹر پر <b>کلاس مقابلہ</b> کھولیں، 2–4 ٹیمیں بنائیں اور باری باری اسپیلنگ پوچھیں۔ بچے بول کر اسپیلنگ بتا سکتے ہیں اور آپ ✓ یا ✗ دبائیں۔',
    tip6: 'انگریزی آواز نہیں ہے؟ ایپ معنی، خالی جگہ والا جملہ اور الجھے حروف دکھاتی ہے، اس لیے بچے پھر بھی کھیل سکتے ہیں۔ Windows میں Settings → Time &amp; language → Speech میں جا کر “English (India)” آواز شامل کریں۔',
    voice_h: 'آواز', voice_lbl: 'انگریزی آواز', voice_auto: 'خودکار (پہلے ہندوستانی انگریزی)', voice_using: 'آواز:', voice_test: 'آواز جانچیں', speed: 'رفتار',
    nv_title: 'اس آلے پر انگریزی آواز نہیں ہے',
    nv_short: 'لفظ پہچاننے کے لیے معنی، جملے اور الجھے حروف کی مدد لیں۔',
    nv_help: 'آپ پھر بھی کھیل سکتے ہیں: معنی، جملہ اور الجھے حروف دکھائے جاتے ہیں۔ Android پر Chrome میں عام طور پر انگریزی آواز ہوتی ہے؛ کمپیوٹر پر اسپیچ کی ترتیبات میں “English (India)” شامل کریں۔',
    stats_h: 'میری پیش رفت', st_words: 'آزمائے گئے الفاظ', st_acc: 'صحیح', st_streak: 'لگاتار صحیح کا ریکارڈ', st_review: 'دوبارہ مشق باقی',
    reset_progress: 'پیش رفت ری سیٹ کریں', confirm_progress: 'آپ کے نمبر اور غلطیوں کی فہرست مٹا دیں؟ آپ کی اپنی الفاظ کی فہرست باقی رہے گی۔', reset_done: 'پیش رفت مٹا دی گئی۔',
    word_x_of_y: 'لفظ {i} / {n}', streak: 'لگاتار صحیح جواب', end_round: 'راؤنڈ ختم کریں',
    hear_word: 'لفظ سنیں', hear_sent: 'جملے میں سنیں', hear_slow: 'آہستہ سنیں',
    meaning: 'معنی', sentence_lbl: 'جملہ', starts_with: 'پہلا حرف',
    hints: 'اشارے', hint_first: 'پہلا حرف', hint_len: 'کتنے حروف', hint_jumble: 'الجھے حروف',
    hints_used_n: 'لیے گئے اشارے: {n}', hint_free: 'آواز نہ ہو تو الجھے حروف مفت ہیں۔', letters_n: '{n} حروف',
    jumble_aria: 'الجھے حروف، ٹائپ کرنے کے لیے ٹیپ کریں', tap_letter: '{l} لکھیں', space_key: 'اسپیس',
    your_spelling: 'آپ کی اسپیلنگ', answer_ph: 'اسپیلنگ ٹائپ کریں', backspace: 'آخری حرف مٹائیں', check: 'جانچیں', show_answer: 'جواب دکھائیں',
    fb_empty: 'پہلے اسپیلنگ ٹائپ کریں۔', fb_retry: 'تقریباً صحیح! لال حروف ٹھیک کریں اور ایک بار پھر کوشش کریں۔', fb_missing: 'چھوٹے ہوئے حروف: {n}',
    lg_ok: 'صحیح', lg_bad: 'غلط', lg_miss: 'چھوٹا ہوا',
    fb_ok: 'صحیح! بہت خوب۔', fb_ok2: 'دوسری کوشش میں صحیح!',
    fb_alt: '“{alt}” امریکی اسپیلنگ ہے۔ ہندوستان میں ہم عام طور پر “{w}” لکھتے ہیں۔',
    fb_bad: 'اس بار نہیں۔ صحیح اسپیلنگ یہ ہے:', fb_shown: 'یہ رہی صحیح اسپیلنگ:',
    you_wrote: 'آپ نے لکھا', right_spelling: 'صحیح اسپیلنگ',
    fb_learn: 'پیلے حروف دیکھیں، یہی مشکل حصہ ہے۔ لفظ بولیں اور ایک بار زور سے اسپیلنگ بولیں۔',
    next_word: 'اگلا لفظ', see_result: 'میرا اسکور دیکھیں',
    sum_title: 'راؤنڈ مکمل!', sum_score: '{n} میں سے {c} صحیح',
    praise_1: 'اچھی کوشش! نیچے دیے الفاظ کی مشق کریں اور پھر کھیلیں۔', praise_2: 'شاباش! تھوڑی اور مشق، اور سب صحیح ہوں گے۔', praise_3: 'کمال کی اسپیلنگ!',
    sum_streak: 'لگاتار صحیح: {n}', sum_hints: 'لیے گئے اشارے: {n}', new_best: 'نیا بہترین اسکور!',
    sum_mistakes: 'مشق کے لیے الفاظ', sum_perfect: 'ایک بھی غلطی نہیں، مکمل راؤنڈ! 🎉',
    practise_these: 'ان الفاظ کی مشق کریں', new_round: 'نیا راؤنڈ', change_level: 'سطح بدلیں', listen_to: '{w} سنیں',
    bee_setup_h: 'کلاس میں اسپیلنگ مقابلہ',
    bee_help: 'اسے پروجیکٹر یا اسمارٹ بورڈ پر دکھائیں۔ کھلاڑی یا ٹیمیں باری باری کھیلتی ہیں: ہر کوئی ایک لفظ سن کر اسپیلنگ ٹائپ کرتا ہے یا بول کر بتاتا ہے، اور استاد فیصلہ کرتے ہیں۔',
    players: 'کھلاڑی یا ٹیمیں', player_n: 'کھلاڑی {n}', add_player: 'کھلاڑی شامل کریں', remove_player: 'کھلاڑی {n} ہٹائیں',
    level_lbl: 'الفاظ کی سطح', per_player: 'ہر کھلاڑی کے لیے الفاظ', game_type: 'کھیل', type_points: 'پوائنٹس', type_ko: 'ناک آؤٹ',
    type_points_help: 'سب کو برابر الفاظ ملتے ہیں۔ سب سے زیادہ صحیح الفاظ والا جیتتا ہے۔',
    type_ko_help: 'ہر کھلاڑی کے پاس 3 جانیں ہیں۔ غلط اسپیلنگ پر ایک جان جاتی ہے؛ آخر میں بچا کھلاڑی جیتتا ہے۔',
    start_bee: 'مقابلہ شروع کریں', bee_how_h: 'کیسے چلائیں',
    bee_step1: 'کھلاڑیوں یا ٹیموں کے نام لکھیں اور سطح چنیں۔',
    bee_step2: 'شروع کریں دبائیں اور پوری اسکرین کریں۔ ایپ لفظ بول کر سناتی ہے۔',
    bee_step3: 'کھلاڑی لفظ ٹائپ کرے، یا بول کر اسپیلنگ بتائے اور آپ ✓ یا ✗ دبائیں۔',
    bee_step4: 'سب صحیح اسپیلنگ دیکھیں، پھر اگلا کھلاڑی دبائیں۔',
    turn_of: '{name}، آپ کی باری!', bee_round: 'لفظ {i} / {n}', judge_help: 'بول کر اسپیلنگ بتائی؟ استاد، فیصلہ کریں:', judge_ok: 'صحیح', judge_bad: 'غلط',
    next_player: 'اگلا کھلاڑی', see_winner: 'فاتح دیکھیں', end_game: 'کھیل ختم کریں', confirm_end: 'کھیل ابھی ختم کر کے اسکور دکھائیں؟',
    lives_n: '{n} جانیں باقی', out: 'آؤٹ', winner_is: '{name} جیت گئے! 🎉', winners_tie: 'برابری: {names}',
    final_note: 'ہر کھلاڑی کے لیے تالیاں، آج سب نے مشق کی!', col_player: 'کھلاڑی', col_lives: 'جانیں',
    play_again: 'پھر کھیلیں', change_players: 'کھلاڑی بدلیں',
    my_list_h: 'میری الفاظ کی فہرست',
    my_list_help: 'اساتذہ کے لیے: انگریزی الفاظ ٹائپ یا پیسٹ کریں، ہر لائن میں ایک۔ چاہیں تو | نشان کے بعد جملہ اور معنی بھی لکھیں۔',
    format_lbl: 'طریقہ:', my_list_format: 'لفظ | جملہ | معنی', words_box: 'الفاظ',
    save_list: 'فہرست محفوظ کریں', example_list: 'مثال', share_list: 'لنک شیئر کریں',
    list_saved: '{n} الفاظ محفوظ ہو گئے۔ مشق یا کلاس مقابلے میں “میری فہرست” چنیں۔', list_skipped: '{n} لائنیں چھوڑ دی گئیں: صرف انگریزی حروف استعمال کریں۔',
    list_empty: 'فہرست خالی ہے۔ پہلے کچھ الفاظ لکھیں۔', list_cleared: 'فہرست مٹا دی گئی۔', confirm_clear_list: 'اپنی الفاظ کی فہرست حذف کریں؟', confirm_replace_list: 'اس سے آپ کی موجودہ الفاظ کی فہرست ({n} الفاظ) بدل جائے گی۔ آگے بڑھیں؟',
    share_done: 'لنک کاپی ہو گیا! طلبہ کو بھیجیں: فہرست ان کے براؤزر میں کھل جائے گی۔',
    wa_list: 'اسپیلنگ کی مشق: اس ہفتے کے {n} الفاظ۔ یہاں کھولیں: {url}',
    shared_found: 'کسی نے آپ کے ساتھ {n} الفاظ کی فہرست شیئر کی ہے۔', use_shared: 'یہ فہرست استعمال کریں', wa_share: 'WhatsApp پر بھیجیں',
    print_h: 'الفاظ کی فہرستیں دیکھیں اور پرنٹ کریں', print_list: 'الفاظ کی فہرست پرنٹ کریں', print_test: 'اسپیلنگ ٹیسٹ پرنٹ کریں',
    col_word: 'لفظ', col_sentence: 'مثالی جملہ', col_listen: 'سنیں',
    print_title: 'اسپیلنگ فہرست: {level}', test_title: 'اسپیلنگ ٹیسٹ: {level}',
    print_name: 'نام', print_class: 'جماعت', print_date: 'تاریخ',
    test_instr: 'استاد کو غور سے سنیں اور ہر لفظ لکھیں۔ اشارے کے لیے معنی دیے گئے ہیں۔', answer_key: 'جوابات (استاد کے لیے)'
  }
};
