/* UI strings for JSON ↔ CSV Converter. Keys must be identical in all 12 languages. */
window.APP_STRINGS = {
  en: {
    app_title: 'JSON ↔ CSV Converter',
    intro: 'Turn JSON from apps and APIs into a CSV table for Excel, turn a CSV into JSON, and find mistakes in JSON with the exact line and column.',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'Check & format JSON',
    help_j2c: 'Paste JSON (or JSON Lines) from an app, API or export. Nested fields become columns like customer.address.city.',
    help_c2j: 'Paste a CSV. Each row becomes an object; numbers and true/false get real types, and empty cells become null.',
    help_fmt: 'Check if JSON is valid, find the exact place of a mistake, and make it easy to read or small.',
    in_json: 'Your JSON', in_csv: 'Your CSV', in_label: 'Input', in_ph: 'Paste here, open a file, or drop it on this box',
    sample_json: 'Sample: API response', sample_csv: 'Sample: contacts CSV', open_file: 'Open file', convert: 'Convert',
    drop_hint: 'Files stay on this device.', size_b: '{n} bytes', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'Very big file: only the start is shown here, but all of it is converted.', big_press: 'This is a big input. Press Convert when you are ready.',
    rec_path: 'Rows come from', path_whole: '(the whole object as one row)', path_list: '{path} ({n} items)', path_top: 'the top-level list ({n} items)', path_lines: 'each line (JSON Lines)',
    arr_mode: 'Lists inside a record', arr_join: 'Join into one cell ("a; b")', arr_explode: 'One row per item (explode)', arr_json: 'Keep as JSON text',
    opt_text: 'Keep every value as text', opt_nest: 'Turn columns like address.city into nested objects',
    out_fmt: 'Output', fmt_pretty: 'JSON, easy to read', fmt_compact: 'JSON, one line (smaller)', fmt_jsonl: 'JSON Lines (one object per line)',
    indent: 'Indent', indent_2: '2 spaces', indent_4: '4 spaces', indent_tab: 'Tab', btn_pretty: 'Pretty print', btn_min: 'Minify', btn_use: 'Use the result as input',
    goto_err: 'Show me in the input', err_where: 'Line {line}, column {col}',
    e_empty: 'The input is empty.',
    e_unexpected_char: 'This character should not be here.',
    e_unexpected_end: 'The text ends too early: a closing }, ] or " is missing.',
    e_trailing_comma: 'Remove the comma before } or ]. JSON does not allow a comma after the last item.',
    e_extra_comma: 'There are two commas in a row, or a comma where a value should be.',
    e_missing_comma: 'A comma is missing between two items.',
    e_missing_colon: 'A colon ( : ) is missing after the name.',
    e_single_quotes: 'JSON needs double quotes " " and not single quotes \' \'.',
    e_key_quotes: 'Names (keys) must be inside double quotes, like "name".',
    e_no_quotes: 'Text values must be inside double quotes, like "Pune".',
    e_unclosed_string: 'This text starts with " but never ends.',
    e_newline_in_string: 'A line break inside quotes is not allowed. Write \\n instead.',
    e_bad_char_in_string: 'There is a hidden control character inside the quotes.',
    e_bad_escape: 'Wrong backslash code. Use \\" \\\\ \\n \\t or \\u0041.',
    e_bad_number: 'This number is written in a way JSON does not allow (for example 01, 1. or .5).',
    e_bad_literal: 'Write true, false or null in small letters (not True, None or undefined).',
    e_extra_text: 'There is extra text after the end of the JSON.',
    e_comment: 'JSON does not allow comments (// or /* */).',
    e_too_deep: 'The JSON is nested too deeply to check.',
    err_generic: 'Something went wrong while converting.', err_csv: 'No rows found in this CSV.', err_file: 'Could not read this file.',
    err_excel: 'Please save the sheet as CSV first (Excel: File → Save as → CSV).', empty_input: 'Paste or type something above, or load a sample.',
    valid_json: 'Valid JSON.', valid_jsonl: 'Valid JSON Lines: {n} lines.', top_array: 'It is a list of {n} items.', top_object: 'It is an object with {n} keys.', top_value: 'It is a single value.',
    j2c_done: '{recs} records → {rows} rows × {cols} columns.', read_jsonl: 'Read as JSON Lines.',
    note_capped: 'Too many rows: only the first {n} are kept. Try "Join into one cell" for lists.',
    note_dotkeys: 'Some names already contain a dot, so their column can look like a nested field.',
    c2j_done: '{rows} objects with {cols} fields each.',
    out_title: 'Result', tab_table: 'Table', tab_csv: 'CSV text', tab_json: 'JSON text', tab_schema: 'Schema', out_empty: 'Nothing to show yet.',
    text_cut: 'Only the first part is shown here. Download or Copy gives you everything.', timing: 'Done in {ms} ms',
    page_info: 'Rows {from}–{to} of {total}',
    sc_field: 'Field', sc_type: 'Type', sc_present: 'Filled', sc_example: 'Example', schema_info: '{n} fields in {recs} records',
    ty_string: 'text', ty_number: 'number', ty_boolean: 'true/false', ty_null: 'empty (null)', ty_object: 'object', ty_array: 'list', mixed: 'mixed',
    tip1: 'Start with the sample API response: look at the Table, then change "Lists inside a record" to "One row per item" and watch 3 orders become 6 rows.',
    tip2: 'Office: many apps and websites export JSON. Convert it to CSV here and open it in Excel or Google Sheets. Or save a sheet as CSV and turn it into JSON for a website or app.',
    tip3: 'Phone numbers like 09876543210 and codes like 007 stay as text, because as a number they would lose the 0 at the start.',
    tip4: 'Class activity: write a small JSON about your class (name, age, a list of hobbies) on the board with one mistake. Students find it, then check with "Check & format JSON".',
    tip5: 'Big files (10 MB and more) work too. Your file is read on this device; nothing is uploaded.',
    words_title: 'Words to know: what is happening inside',
    w_json: '<b>JSON</b>: a text format apps use to send data. <code>{ }</code> is an object (names and values), <code>[ ]</code> is a list. Names and text always use double quotes.',
    w_csv: '<b>CSV</b>: a simple table written as text: one row per line, values separated by commas. Excel and Google Sheets can open it.',
    w_flat: '<b>Flatten</b>: turning nested data into columns. <code>{"address": {"city": "Pune"}}</code> becomes a column called <code>address.city</code>.',
    w_jsonl: '<b>JSON Lines</b>: one JSON object on each line. It is common for logs and big exports, because a program can read it line by line.',
    w_schema: '<b>Schema</b>: the list of fields, their type (text, number, true/false, list) and how often they are filled.',
    w_errors: '<b>Common mistakes</b>: a comma after the last item, single quotes, a missing comma, or True instead of true.'
  },
  hi: {
    app_title: 'JSON ↔ CSV कन्वर्टर',
    intro: 'ऐप और API से आए JSON को Excel के लिए CSV टेबल में बदलें, CSV को JSON में बदलें, और JSON की गलती ठीक लाइन और कॉलम के साथ ढूँढें।',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON जाँचें और सजाएँ',
    help_j2c: 'किसी ऐप, API या एक्सपोर्ट का JSON (या JSON Lines) पेस्ट करें। अंदर के फ़ील्ड customer.address.city जैसे कॉलम बन जाते हैं।',
    help_c2j: 'CSV पेस्ट करें। हर पंक्ति एक ऑब्जेक्ट बनती है; संख्याएँ और true/false सही प्रकार में आते हैं, और खाली सेल null बनते हैं।',
    help_fmt: 'देखें कि JSON सही है या नहीं, गलती की ठीक जगह ढूँढें, और उसे पढ़ने में आसान या छोटा बनाएँ।',
    in_json: 'आपका JSON', in_csv: 'आपकी CSV', in_label: 'इनपुट', in_ph: 'यहाँ पेस्ट करें, फ़ाइल खोलें, या इस बॉक्स पर छोड़ें',
    sample_json: 'नमूना: API जवाब', sample_csv: 'नमूना: संपर्क CSV', open_file: 'फ़ाइल खोलें', convert: 'बदलें',
    drop_hint: 'फ़ाइलें इसी डिवाइस पर रहती हैं।', size_b: '{n} बाइट', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'बहुत बड़ी फ़ाइल: यहाँ सिर्फ़ शुरू का हिस्सा दिखता है, पर पूरी फ़ाइल बदली जाती है।', big_press: 'यह बड़ा इनपुट है। तैयार हों तो "बदलें" दबाएँ।',
    rec_path: 'पंक्तियाँ कहाँ से आएँ', path_whole: '(पूरा ऑब्जेक्ट एक पंक्ति)', path_list: '{path} ({n} आइटम)', path_top: 'सबसे ऊपर की सूची ({n} आइटम)', path_lines: 'हर लाइन (JSON Lines)',
    arr_mode: 'रिकॉर्ड के अंदर की सूचियाँ', arr_join: 'एक सेल में जोड़ें ("a; b")', arr_explode: 'हर आइटम की अलग पंक्ति', arr_json: 'JSON टेक्स्ट ही रखें',
    opt_text: 'हर मान को टेक्स्ट ही रखें', opt_nest: 'address.city जैसे कॉलम को अंदर वाले ऑब्जेक्ट में बदलें',
    out_fmt: 'आउटपुट', fmt_pretty: 'JSON, पढ़ने में आसान', fmt_compact: 'JSON, एक लाइन (छोटा)', fmt_jsonl: 'JSON Lines (हर लाइन में एक ऑब्जेक्ट)',
    indent: 'इंडेंट', indent_2: '2 स्पेस', indent_4: '4 स्पेस', indent_tab: 'टैब', btn_pretty: 'सजाकर दिखाएँ', btn_min: 'छोटा करें', btn_use: 'नतीजे को इनपुट बनाएँ',
    goto_err: 'इनपुट में दिखाएँ', err_where: 'लाइन {line}, कॉलम {col}',
    e_empty: 'इनपुट खाली है।',
    e_unexpected_char: 'यह चिह्न यहाँ नहीं होना चाहिए।',
    e_unexpected_end: 'टेक्स्ट जल्दी खत्म हो गया: बंद करने वाला }, ] या " नहीं है।',
    e_trailing_comma: '} या ] से पहले का कॉमा हटाएँ। JSON में आखिरी आइटम के बाद कॉमा नहीं चलता।',
    e_extra_comma: 'लगातार दो कॉमा हैं, या जहाँ मान होना चाहिए वहाँ कॉमा है।',
    e_missing_comma: 'दो आइटम के बीच कॉमा नहीं है।',
    e_missing_colon: 'नाम के बाद कोलन ( : ) नहीं है।',
    e_single_quotes: 'JSON में डबल कोट " " चाहिए, सिंगल कोट \' \' नहीं।',
    e_key_quotes: 'नाम (की) डबल कोट में होने चाहिए, जैसे "name"।',
    e_no_quotes: 'टेक्स्ट वाले मान डबल कोट में होने चाहिए, जैसे "Pune"।',
    e_unclosed_string: 'यह टेक्स्ट " से शुरू होता है पर खत्म नहीं होता।',
    e_newline_in_string: 'कोट के अंदर नई लाइन नहीं चलती। उसकी जगह \\n लिखें।',
    e_bad_char_in_string: 'कोट के अंदर एक छिपा हुआ कंट्रोल चिह्न है।',
    e_bad_escape: 'बैकस्लैश कोड गलत है। \\" \\\\ \\n \\t या \\u0041 इस्तेमाल करें।',
    e_bad_number: 'यह संख्या उस तरह लिखी है जो JSON में नहीं चलती (जैसे 01, 1. या .5)।',
    e_bad_literal: 'true, false या null छोटे अक्षरों में लिखें (True, None या undefined नहीं)।',
    e_extra_text: 'JSON खत्म होने के बाद फ़ालतू टेक्स्ट है।',
    e_comment: 'JSON में टिप्पणी (// या /* */) नहीं चलती।',
    e_too_deep: 'JSON बहुत गहराई तक अंदर-अंदर है, जाँचा नहीं जा सकता।',
    err_generic: 'बदलते समय कुछ गड़बड़ हो गई।', err_csv: 'इस CSV में कोई पंक्ति नहीं मिली।', err_file: 'यह फ़ाइल पढ़ी नहीं जा सकी।',
    err_excel: 'पहले शीट को CSV में सेव करें (Excel: File → Save as → CSV)।', empty_input: 'ऊपर कुछ पेस्ट करें या लिखें, या नमूना खोलें।',
    valid_json: 'JSON सही है।', valid_jsonl: 'JSON Lines सही है: {n} लाइनें।', top_array: 'यह {n} आइटम की सूची है।', top_object: 'यह {n} की वाला ऑब्जेक्ट है।', top_value: 'यह एक अकेला मान है।',
    j2c_done: '{recs} रिकॉर्ड → {rows} पंक्तियाँ × {cols} कॉलम।', read_jsonl: 'JSON Lines की तरह पढ़ा।',
    note_capped: 'बहुत ज़्यादा पंक्तियाँ: सिर्फ़ पहली {n} रखी गईं। सूचियों के लिए "एक सेल में जोड़ें" आज़माएँ।',
    note_dotkeys: 'कुछ नामों में पहले से बिंदु है, इसलिए उनका कॉलम अंदर वाले फ़ील्ड जैसा दिख सकता है।',
    c2j_done: '{rows} ऑब्जेक्ट, हर एक में {cols} फ़ील्ड।',
    out_title: 'नतीजा', tab_table: 'टेबल', tab_csv: 'CSV टेक्स्ट', tab_json: 'JSON टेक्स्ट', tab_schema: 'स्कीमा', out_empty: 'अभी दिखाने को कुछ नहीं।',
    text_cut: 'यहाँ सिर्फ़ पहला हिस्सा दिख रहा है। डाउनलोड या कॉपी से पूरा मिलेगा।', timing: '{ms} ms में पूरा',
    page_info: 'पंक्तियाँ {from}–{to}, कुल {total}',
    sc_field: 'फ़ील्ड', sc_type: 'प्रकार', sc_present: 'भरा हुआ', sc_example: 'उदाहरण', schema_info: '{recs} रिकॉर्ड में {n} फ़ील्ड',
    ty_string: 'टेक्स्ट', ty_number: 'संख्या', ty_boolean: 'true/false', ty_null: 'खाली (null)', ty_object: 'ऑब्जेक्ट', ty_array: 'सूची', mixed: 'मिला-जुला',
    tip1: 'नमूना API जवाब से शुरू करें: टेबल देखें, फिर "रिकॉर्ड के अंदर की सूचियाँ" को "हर आइटम की अलग पंक्ति" करें और देखें कि 3 ऑर्डर 6 पंक्तियाँ बन जाते हैं।',
    tip2: 'दफ़्तर: कई ऐप और वेबसाइट JSON एक्सपोर्ट करती हैं। उसे यहाँ CSV बनाकर Excel या Google Sheets में खोलें। या शीट को CSV में सेव करके वेबसाइट या ऐप के लिए JSON बनाएँ।',
    tip3: '09876543210 जैसे फ़ोन नंबर और 007 जैसे कोड टेक्स्ट ही रहते हैं, क्योंकि संख्या बनने पर शुरू का 0 गायब हो जाता।',
    tip4: 'कक्षा गतिविधि: बोर्ड पर अपनी कक्षा के बारे में एक छोटा JSON लिखें (नाम, उम्र, शौक की सूची) जिसमें एक गलती हो। छात्र उसे ढूँढें, फिर "JSON जाँचें और सजाएँ" से जाँचें।',
    tip5: 'बड़ी फ़ाइलें (10 MB या ज़्यादा) भी चलती हैं। आपकी फ़ाइल इसी डिवाइस पर पढ़ी जाती है; कुछ भी अपलोड नहीं होता।',
    words_title: 'ज़रूरी शब्द: अंदर क्या हो रहा है',
    w_json: '<b>JSON</b>: टेक्स्ट का एक तरीका जिससे ऐप डेटा भेजते हैं। <code>{ }</code> ऑब्जेक्ट है (नाम और मान), <code>[ ]</code> सूची है। नाम और टेक्स्ट हमेशा डबल कोट में।',
    w_csv: '<b>CSV</b>: टेक्स्ट में लिखी सादी टेबल: हर लाइन एक पंक्ति, मान कॉमा से अलग। Excel और Google Sheets इसे खोल लेते हैं।',
    w_flat: '<b>फ़्लैट करना</b>: अंदर-अंदर वाले डेटा को कॉलम बनाना। <code>{"address": {"city": "Pune"}}</code> से <code>address.city</code> नाम का कॉलम बनता है।',
    w_jsonl: '<b>JSON Lines</b>: हर लाइन में एक JSON ऑब्जेक्ट। लॉग और बड़े एक्सपोर्ट में आम है, क्योंकि प्रोग्राम इसे लाइन-दर-लाइन पढ़ सकता है।',
    w_schema: '<b>स्कीमा</b>: फ़ील्ड की सूची, उनका प्रकार (टेक्स्ट, संख्या, true/false, सूची) और वे कितनी बार भरे हैं।',
    w_errors: '<b>आम गलतियाँ</b>: आखिरी आइटम के बाद कॉमा, सिंगल कोट, छूटा हुआ कॉमा, या true की जगह True।'
  },
  bn: {
    app_title: 'JSON ↔ CSV কনভার্টার',
    intro: 'অ্যাপ আর API থেকে আসা JSON-কে Excel-এর জন্য CSV টেবিলে বদলান, CSV-কে JSON-এ বদলান, আর JSON-এর ভুল ঠিক লাইন ও কলাম সহ খুঁজুন।',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON যাচাই ও সাজানো',
    help_j2c: 'কোনো অ্যাপ, API বা এক্সপোর্টের JSON (বা JSON Lines) পেস্ট করুন। ভেতরের ফিল্ড customer.address.city-র মতো কলাম হয়ে যায়।',
    help_c2j: 'CSV পেস্ট করুন। প্রতিটি সারি একটি অবজেক্ট হয়; সংখ্যা আর true/false ঠিক ধরনে আসে, ফাঁকা ঘর null হয়।',
    help_fmt: 'JSON ঠিক আছে কি না দেখুন, ভুলের ঠিক জায়গা খুঁজুন, আর পড়তে সহজ বা ছোট করুন।',
    in_json: 'আপনার JSON', in_csv: 'আপনার CSV', in_label: 'ইনপুট', in_ph: 'এখানে পেস্ট করুন, ফাইল খুলুন, বা এই বাক্সে ছাড়ুন',
    sample_json: 'নমুনা: API উত্তর', sample_csv: 'নমুনা: যোগাযোগ CSV', open_file: 'ফাইল খুলুন', convert: 'বদলান',
    drop_hint: 'ফাইল এই ডিভাইসেই থাকে।', size_b: '{n} বাইট', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'খুব বড় ফাইল: এখানে শুধু শুরুর অংশ দেখা যায়, কিন্তু পুরো ফাইলটাই বদলানো হয়।', big_press: 'এটা বড় ইনপুট। তৈরি হলে "বদলান" টিপুন।',
    rec_path: 'সারি কোথা থেকে আসবে', path_whole: '(পুরো অবজেক্ট একটি সারি)', path_list: '{path} ({n}টি আইটেম)', path_top: 'সবার ওপরের তালিকা ({n}টি আইটেম)', path_lines: 'প্রতিটি লাইন (JSON Lines)',
    arr_mode: 'রেকর্ডের ভেতরের তালিকা', arr_join: 'এক ঘরে জুড়ুন ("a; b")', arr_explode: 'প্রতিটি আইটেমের আলাদা সারি', arr_json: 'JSON লেখা হিসেবেই রাখুন',
    opt_text: 'সব মান লেখা হিসেবেই রাখুন', opt_nest: 'address.city-র মতো কলামকে ভেতরের অবজেক্টে বদলান',
    out_fmt: 'আউটপুট', fmt_pretty: 'JSON, পড়তে সহজ', fmt_compact: 'JSON, এক লাইনে (ছোট)', fmt_jsonl: 'JSON Lines (প্রতি লাইনে একটি অবজেক্ট)',
    indent: 'ইন্ডেন্ট', indent_2: '2 স্পেস', indent_4: '4 স্পেস', indent_tab: 'ট্যাব', btn_pretty: 'সাজিয়ে দেখান', btn_min: 'ছোট করুন', btn_use: 'ফলাফলকে ইনপুট করুন',
    goto_err: 'ইনপুটে দেখান', err_where: 'লাইন {line}, কলাম {col}',
    e_empty: 'ইনপুট ফাঁকা।',
    e_unexpected_char: 'এই চিহ্নটি এখানে থাকার কথা নয়।',
    e_unexpected_end: 'লেখা আগেই শেষ হয়ে গেছে: বন্ধ করার }, ] বা " নেই।',
    e_trailing_comma: '} বা ]-এর আগের কমাটি মুছুন। JSON-এ শেষ আইটেমের পরে কমা চলে না।',
    e_extra_comma: 'পরপর দুটি কমা, বা যেখানে মান থাকার কথা সেখানে কমা।',
    e_missing_comma: 'দুটি আইটেমের মাঝে কমা নেই।',
    e_missing_colon: 'নামের পরে কোলন ( : ) নেই।',
    e_single_quotes: 'JSON-এ ডাবল কোট " " লাগে, সিঙ্গল কোট \' \' নয়।',
    e_key_quotes: 'নাম (কী) ডাবল কোটের ভেতরে থাকতে হবে, যেমন "name"।',
    e_no_quotes: 'লেখার মান ডাবল কোটের ভেতরে থাকতে হবে, যেমন "Pune"।',
    e_unclosed_string: 'এই লেখা " দিয়ে শুরু হয়েছে কিন্তু শেষ হয়নি।',
    e_newline_in_string: 'কোটের ভেতরে নতুন লাইন চলে না। তার বদলে \\n লিখুন।',
    e_bad_char_in_string: 'কোটের ভেতরে একটি লুকানো কন্ট্রোল চিহ্ন আছে।',
    e_bad_escape: 'ব্যাকস্ল্যাশ কোড ভুল। \\" \\\\ \\n \\t বা \\u0041 ব্যবহার করুন।',
    e_bad_number: 'সংখ্যাটি এমনভাবে লেখা যা JSON-এ চলে না (যেমন 01, 1. বা .5)।',
    e_bad_literal: 'true, false বা null ছোট হাতের অক্ষরে লিখুন (True, None বা undefined নয়)।',
    e_extra_text: 'JSON শেষ হওয়ার পরে বাড়তি লেখা আছে।',
    e_comment: 'JSON-এ মন্তব্য (// বা /* */) চলে না।',
    e_too_deep: 'JSON খুব গভীরে ভেতরে-ভেতরে, যাচাই করা যাচ্ছে না।',
    err_generic: 'বদলানোর সময় কিছু গোলমাল হয়েছে।', err_csv: 'এই CSV-তে কোনো সারি পাওয়া যায়নি।', err_file: 'এই ফাইলটি পড়া গেল না।',
    err_excel: 'আগে শিটটি CSV হিসেবে সেভ করুন (Excel: File → Save as → CSV)।', empty_input: 'ওপরে কিছু পেস্ট করুন বা লিখুন, বা নমুনা খুলুন।',
    valid_json: 'JSON ঠিক আছে।', valid_jsonl: 'JSON Lines ঠিক আছে: {n}টি লাইন।', top_array: 'এটি {n}টি আইটেমের তালিকা।', top_object: 'এটি {n}টি কী-র অবজেক্ট।', top_value: 'এটি একটি মাত্র মান।',
    j2c_done: '{recs}টি রেকর্ড → {rows}টি সারি × {cols}টি কলাম।', read_jsonl: 'JSON Lines হিসেবে পড়া হয়েছে।',
    note_capped: 'অনেক বেশি সারি: শুধু প্রথম {n}টি রাখা হয়েছে। তালিকার জন্য "এক ঘরে জুড়ুন" চেষ্টা করুন।',
    note_dotkeys: 'কিছু নামে আগে থেকেই বিন্দু আছে, তাই তাদের কলাম ভেতরের ফিল্ডের মতো দেখাতে পারে।',
    c2j_done: '{rows}টি অবজেক্ট, প্রতিটিতে {cols}টি ফিল্ড।',
    out_title: 'ফলাফল', tab_table: 'টেবিল', tab_csv: 'CSV লেখা', tab_json: 'JSON লেখা', tab_schema: 'স্কিমা', out_empty: 'এখনও দেখানোর কিছু নেই।',
    text_cut: 'এখানে শুধু প্রথম অংশ দেখানো হচ্ছে। ডাউনলোড বা কপি করলে পুরোটা পাবেন।', timing: '{ms} ms-এ শেষ',
    page_info: 'সারি {from}–{to}, মোট {total}',
    sc_field: 'ফিল্ড', sc_type: 'ধরন', sc_present: 'ভরা', sc_example: 'উদাহরণ', schema_info: '{recs}টি রেকর্ডে {n}টি ফিল্ড',
    ty_string: 'লেখা', ty_number: 'সংখ্যা', ty_boolean: 'true/false', ty_null: 'ফাঁকা (null)', ty_object: 'অবজেক্ট', ty_array: 'তালিকা', mixed: 'মেশানো',
    tip1: 'নমুনা API উত্তর দিয়ে শুরু করুন: টেবিল দেখুন, তারপর "রেকর্ডের ভেতরের তালিকা" বদলে "প্রতিটি আইটেমের আলাদা সারি" করুন আর দেখুন 3টি অর্ডার 6টি সারি হয়ে যায়।',
    tip2: 'অফিস: অনেক অ্যাপ আর ওয়েবসাইট JSON এক্সপোর্ট করে। এখানে CSV করে Excel বা Google Sheets-এ খুলুন। বা শিট CSV হিসেবে সেভ করে ওয়েবসাইট বা অ্যাপের জন্য JSON বানান।',
    tip3: '09876543210-এর মতো ফোন নম্বর আর 007-এর মতো কোড লেখা হিসেবেই থাকে, কারণ সংখ্যা হলে শুরুর 0 হারিয়ে যেত।',
    tip4: 'ক্লাসের কাজ: বোর্ডে আপনার ক্লাস নিয়ে একটি ছোট JSON লিখুন (নাম, বয়স, শখের তালিকা) যাতে একটি ভুল আছে। ছাত্রছাত্রীরা সেটা খুঁজবে, তারপর "JSON যাচাই ও সাজানো" দিয়ে মিলিয়ে দেখবে।',
    tip5: 'বড় ফাইলও (10 MB বা বেশি) চলে। আপনার ফাইল এই ডিভাইসেই পড়া হয়; কিছুই আপলোড হয় না।',
    words_title: 'জরুরি শব্দ: ভেতরে কী হচ্ছে',
    w_json: '<b>JSON</b>: লেখার একটি ধরন যা দিয়ে অ্যাপ ডেটা পাঠায়। <code>{ }</code> হলো অবজেক্ট (নাম আর মান), <code>[ ]</code> হলো তালিকা। নাম আর লেখা সবসময় ডাবল কোটে।',
    w_csv: '<b>CSV</b>: লেখায় তৈরি সাধারণ টেবিল: প্রতি লাইনে একটি সারি, মান কমা দিয়ে আলাদা। Excel আর Google Sheets এটা খুলতে পারে।',
    w_flat: '<b>ফ্ল্যাট করা</b>: ভেতরে-ভেতরে থাকা ডেটাকে কলাম বানানো। <code>{"address": {"city": "Pune"}}</code> থেকে <code>address.city</code> নামের কলাম হয়।',
    w_jsonl: '<b>JSON Lines</b>: প্রতি লাইনে একটি JSON অবজেক্ট। লগ আর বড় এক্সপোর্টে এটা প্রচলিত, কারণ প্রোগ্রাম এটা লাইন ধরে ধরে পড়তে পারে।',
    w_schema: '<b>স্কিমা</b>: ফিল্ডের তালিকা, তাদের ধরন (লেখা, সংখ্যা, true/false, তালিকা) আর কতবার ভরা আছে।',
    w_errors: '<b>সাধারণ ভুল</b>: শেষ আইটেমের পরে কমা, সিঙ্গল কোট, বাদ পড়া কমা, বা true-র জায়গায় True।'
  },
  mr: {
    app_title: 'JSON ↔ CSV कन्व्हर्टर',
    intro: 'ॲप आणि API मधून आलेला JSON Excel साठी CSV टेबलमध्ये बदला, CSV ला JSON मध्ये बदला, आणि JSON मधील चूक नेमक्या ओळ व कॉलमसह शोधा.',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON तपासा व मांडा',
    help_j2c: 'एखाद्या ॲप, API किंवा एक्सपोर्टमधील JSON (किंवा JSON Lines) पेस्ट करा. आतील फील्ड customer.address.city सारखे कॉलम बनतात.',
    help_c2j: 'CSV पेस्ट करा. प्रत्येक ओळ एक ऑब्जेक्ट बनते; संख्या आणि true/false योग्य प्रकारात येतात, आणि रिकामे सेल null बनतात.',
    help_fmt: 'JSON बरोबर आहे का ते तपासा, चुकीची नेमकी जागा शोधा, आणि तो वाचायला सोपा किंवा लहान करा.',
    in_json: 'तुमचा JSON', in_csv: 'तुमची CSV', in_label: 'इनपुट', in_ph: 'इथे पेस्ट करा, फाइल उघडा, किंवा या बॉक्सवर सोडा',
    sample_json: 'नमुना: API उत्तर', sample_csv: 'नमुना: संपर्क CSV', open_file: 'फाइल उघडा', convert: 'बदला',
    drop_hint: 'फाइल्स याच डिव्हाइसवर राहतात.', size_b: '{n} बाइट', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'खूप मोठी फाइल: इथे फक्त सुरुवातीचा भाग दिसतो, पण संपूर्ण फाइल बदलली जाते.', big_press: 'हा मोठा इनपुट आहे. तयार असाल तेव्हा "बदला" दाबा.',
    rec_path: 'ओळी कुठून येतात', path_whole: '(संपूर्ण ऑब्जेक्ट एक ओळ)', path_list: '{path} ({n} आयटम)', path_top: 'सर्वात वरची यादी ({n} आयटम)', path_lines: 'प्रत्येक ओळ (JSON Lines)',
    arr_mode: 'रेकॉर्डमधील याद्या', arr_join: 'एका सेलमध्ये जोडा ("a; b")', arr_explode: 'प्रत्येक आयटमची वेगळी ओळ', arr_json: 'JSON मजकूर म्हणूनच ठेवा',
    opt_text: 'प्रत्येक मूल्य मजकूर म्हणूनच ठेवा', opt_nest: 'address.city सारखे कॉलम आतील ऑब्जेक्टमध्ये बदला',
    out_fmt: 'आउटपुट', fmt_pretty: 'JSON, वाचायला सोपा', fmt_compact: 'JSON, एका ओळीत (लहान)', fmt_jsonl: 'JSON Lines (प्रत्येक ओळीत एक ऑब्जेक्ट)',
    indent: 'इंडेंट', indent_2: '2 स्पेस', indent_4: '4 स्पेस', indent_tab: 'टॅब', btn_pretty: 'नीट मांडा', btn_min: 'लहान करा', btn_use: 'निकाल इनपुट म्हणून वापरा',
    goto_err: 'इनपुटमध्ये दाखवा', err_where: 'ओळ {line}, कॉलम {col}',
    e_empty: 'इनपुट रिकामा आहे.',
    e_unexpected_char: 'हे चिन्ह इथे असायला नको.',
    e_unexpected_end: 'मजकूर लवकर संपला: बंद करणारा }, ] किंवा " नाही.',
    e_trailing_comma: '} किंवा ] आधीचा स्वल्पविराम काढा. JSON मध्ये शेवटच्या आयटमनंतर स्वल्पविराम चालत नाही.',
    e_extra_comma: 'लागोपाठ दोन स्वल्पविराम आहेत, किंवा जिथे मूल्य हवे तिथे स्वल्पविराम आहे.',
    e_missing_comma: 'दोन आयटमच्या मध्ये स्वल्पविराम नाही.',
    e_missing_colon: 'नावानंतर कोलन ( : ) नाही.',
    e_single_quotes: 'JSON मध्ये डबल कोट " " हवेत, सिंगल कोट \' \' नाही.',
    e_key_quotes: 'नावे (की) डबल कोटमध्ये हवीत, उदा. "name".',
    e_no_quotes: 'मजकूर मूल्ये डबल कोटमध्ये हवीत, उदा. "Pune".',
    e_unclosed_string: 'हा मजकूर " ने सुरू होतो पण संपत नाही.',
    e_newline_in_string: 'कोटच्या आत नवी ओळ चालत नाही. त्याऐवजी \\n लिहा.',
    e_bad_char_in_string: 'कोटच्या आत एक लपलेले नियंत्रण चिन्ह आहे.',
    e_bad_escape: 'बॅकस्लॅश कोड चुकीचा आहे. \\" \\\\ \\n \\t किंवा \\u0041 वापरा.',
    e_bad_number: 'ही संख्या JSON मध्ये न चालणाऱ्या पद्धतीने लिहिली आहे (उदा. 01, 1. किंवा .5).',
    e_bad_literal: 'true, false किंवा null लहान अक्षरांत लिहा (True, None किंवा undefined नाही).',
    e_extra_text: 'JSON संपल्यानंतर जास्तीचा मजकूर आहे.',
    e_comment: 'JSON मध्ये टिप्पणी (// किंवा /* */) चालत नाही.',
    e_too_deep: 'JSON खूप खोलवर आत-आत आहे, तपासता येत नाही.',
    err_generic: 'बदलताना काहीतरी चुकले.', err_csv: 'या CSV मध्ये एकही ओळ सापडली नाही.', err_file: 'ही फाइल वाचता आली नाही.',
    err_excel: 'आधी शीट CSV म्हणून सेव्ह करा (Excel: File → Save as → CSV).', empty_input: 'वर काहीतरी पेस्ट करा किंवा लिहा, किंवा नमुना उघडा.',
    valid_json: 'JSON बरोबर आहे.', valid_jsonl: 'JSON Lines बरोबर आहे: {n} ओळी.', top_array: 'ही {n} आयटमची यादी आहे.', top_object: 'हा {n} की असलेला ऑब्जेक्ट आहे.', top_value: 'हे एकच मूल्य आहे.',
    j2c_done: '{recs} रेकॉर्ड → {rows} ओळी × {cols} कॉलम.', read_jsonl: 'JSON Lines म्हणून वाचले.',
    note_capped: 'खूप जास्त ओळी: फक्त पहिल्या {n} ठेवल्या. याद्यांसाठी "एका सेलमध्ये जोडा" वापरून पाहा.',
    note_dotkeys: 'काही नावांमध्ये आधीच बिंदू आहे, म्हणून त्यांचा कॉलम आतील फील्डसारखा दिसू शकतो.',
    c2j_done: '{rows} ऑब्जेक्ट, प्रत्येकात {cols} फील्ड.',
    out_title: 'निकाल', tab_table: 'टेबल', tab_csv: 'CSV मजकूर', tab_json: 'JSON मजकूर', tab_schema: 'स्कीमा', out_empty: 'अजून दाखवण्यासारखे काही नाही.',
    text_cut: 'इथे फक्त पहिला भाग दिसतो. डाउनलोड किंवा कॉपीने सगळे मिळेल.', timing: '{ms} ms मध्ये पूर्ण',
    page_info: 'ओळी {from}–{to}, एकूण {total}',
    sc_field: 'फील्ड', sc_type: 'प्रकार', sc_present: 'भरलेले', sc_example: 'उदाहरण', schema_info: '{recs} रेकॉर्डमध्ये {n} फील्ड',
    ty_string: 'मजकूर', ty_number: 'संख्या', ty_boolean: 'true/false', ty_null: 'रिकामे (null)', ty_object: 'ऑब्जेक्ट', ty_array: 'यादी', mixed: 'मिश्र',
    tip1: 'नमुना API उत्तराने सुरुवात करा: टेबल पाहा, मग "रेकॉर्डमधील याद्या" बदलून "प्रत्येक आयटमची वेगळी ओळ" करा आणि 3 ऑर्डरच्या 6 ओळी होताना पाहा.',
    tip2: 'ऑफिस: अनेक ॲप्स आणि वेबसाइट्स JSON एक्सपोर्ट करतात. तो इथे CSV करून Excel किंवा Google Sheets मध्ये उघडा. किंवा शीट CSV म्हणून सेव्ह करून वेबसाइट किंवा ॲपसाठी JSON बनवा.',
    tip3: '09876543210 सारखे फोन नंबर आणि 007 सारखे कोड मजकूरच राहतात, कारण संख्या झाल्यास सुरुवातीचा 0 हरवला असता.',
    tip4: 'वर्गातील उपक्रम: फळ्यावर तुमच्या वर्गाबद्दल एक छोटा JSON लिहा (नाव, वय, छंदांची यादी) ज्यात एक चूक असेल. विद्यार्थी ती शोधतील, मग "JSON तपासा व मांडा" ने तपासतील.',
    tip5: 'मोठ्या फाइल्स (10 MB किंवा जास्त) सुद्धा चालतात. तुमची फाइल याच डिव्हाइसवर वाचली जाते; काहीही अपलोड होत नाही.',
    words_title: 'महत्त्वाचे शब्द: आत काय घडते',
    w_json: '<b>JSON</b>: ॲप्स डेटा पाठवण्यासाठी वापरतात ती मजकुराची पद्धत. <code>{ }</code> म्हणजे ऑब्जेक्ट (नावे आणि मूल्ये), <code>[ ]</code> म्हणजे यादी. नावे आणि मजकूर नेहमी डबल कोटमध्ये.',
    w_csv: '<b>CSV</b>: मजकुरात लिहिलेले साधे टेबल: प्रत्येक ओळ एक रांग, मूल्ये स्वल्पविरामाने वेगळी. Excel आणि Google Sheets ते उघडू शकतात.',
    w_flat: '<b>सपाट करणे</b>: आत-आत असलेला डेटा कॉलममध्ये आणणे. <code>{"address": {"city": "Pune"}}</code> पासून <code>address.city</code> नावाचा कॉलम बनतो.',
    w_jsonl: '<b>JSON Lines</b>: प्रत्येक ओळीत एक JSON ऑब्जेक्ट. लॉग आणि मोठ्या एक्सपोर्टमध्ये सामान्य, कारण प्रोग्राम तो ओळ-ओळ वाचू शकतो.',
    w_schema: '<b>स्कीमा</b>: फील्डची यादी, त्यांचा प्रकार (मजकूर, संख्या, true/false, यादी) आणि ते किती वेळा भरलेले आहेत.',
    w_errors: '<b>नेहमीच्या चुका</b>: शेवटच्या आयटमनंतर स्वल्पविराम, सिंगल कोट, राहिलेला स्वल्पविराम, किंवा true ऐवजी True.'
  },
  gu: {
    app_title: 'JSON ↔ CSV કન્વર્ટર',
    intro: 'ઍપ અને API માંથી આવેલા JSON ને Excel માટે CSV ટેબલમાં ફેરવો, CSV ને JSON માં ફેરવો, અને JSON ની ભૂલ ચોક્કસ લાઇન અને કૉલમ સાથે શોધો.',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON તપાસો અને ગોઠવો',
    help_j2c: 'કોઈ ઍપ, API કે એક્સપોર્ટનો JSON (કે JSON Lines) પેસ્ટ કરો. અંદરના ફીલ્ડ customer.address.city જેવા કૉલમ બની જાય છે.',
    help_c2j: 'CSV પેસ્ટ કરો. દરેક હરોળ એક ઑબ્જેક્ટ બને છે; સંખ્યા અને true/false સાચા પ્રકારમાં આવે છે, અને ખાલી સેલ null બને છે.',
    help_fmt: 'JSON સાચો છે કે નહીં તપાસો, ભૂલની ચોક્કસ જગ્યા શોધો, અને તેને વાંચવામાં સરળ કે નાનો બનાવો.',
    in_json: 'તમારો JSON', in_csv: 'તમારી CSV', in_label: 'ઇનપુટ', in_ph: 'અહીં પેસ્ટ કરો, ફાઇલ ખોલો, કે આ બૉક્સ પર મૂકો',
    sample_json: 'નમૂનો: API જવાબ', sample_csv: 'નમૂનો: સંપર્ક CSV', open_file: 'ફાઇલ ખોલો', convert: 'ફેરવો',
    drop_hint: 'ફાઇલો આ ડિવાઇસ પર જ રહે છે.', size_b: '{n} બાઇટ', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'બહુ મોટી ફાઇલ: અહીં ફક્ત શરૂઆતનો ભાગ દેખાય છે, પણ આખી ફાઇલ ફેરવાય છે.', big_press: 'આ મોટો ઇનપુટ છે. તૈયાર હો ત્યારે "ફેરવો" દબાવો.',
    rec_path: 'હરોળ ક્યાંથી આવે', path_whole: '(આખો ઑબ્જેક્ટ એક હરોળ)', path_list: '{path} ({n} આઇટમ)', path_top: 'સૌથી ઉપરની યાદી ({n} આઇટમ)', path_lines: 'દરેક લાઇન (JSON Lines)',
    arr_mode: 'રેકૉર્ડની અંદરની યાદીઓ', arr_join: 'એક સેલમાં જોડો ("a; b")', arr_explode: 'દરેક આઇટમની જુદી હરોળ', arr_json: 'JSON લખાણ તરીકે જ રાખો',
    opt_text: 'દરેક મૂલ્ય લખાણ તરીકે જ રાખો', opt_nest: 'address.city જેવા કૉલમને અંદરના ઑબ્જેક્ટમાં ફેરવો',
    out_fmt: 'આઉટપુટ', fmt_pretty: 'JSON, વાંચવામાં સરળ', fmt_compact: 'JSON, એક લાઇનમાં (નાનો)', fmt_jsonl: 'JSON Lines (દરેક લાઇનમાં એક ઑબ્જેક્ટ)',
    indent: 'ઇન્ડેન્ટ', indent_2: '2 સ્પેસ', indent_4: '4 સ્પેસ', indent_tab: 'ટૅબ', btn_pretty: 'ગોઠવીને બતાવો', btn_min: 'નાનો કરો', btn_use: 'પરિણામને ઇનપુટ બનાવો',
    goto_err: 'ઇનપુટમાં બતાવો', err_where: 'લાઇન {line}, કૉલમ {col}',
    e_empty: 'ઇનપુટ ખાલી છે.',
    e_unexpected_char: 'આ ચિહ્ન અહીં ન હોવું જોઈએ.',
    e_unexpected_end: 'લખાણ વહેલું પૂરું થઈ ગયું: બંધ કરનાર }, ] કે " નથી.',
    e_trailing_comma: '} કે ] પહેલાંનો અલ્પવિરામ કાઢો. JSON માં છેલ્લી આઇટમ પછી અલ્પવિરામ ચાલતો નથી.',
    e_extra_comma: 'સળંગ બે અલ્પવિરામ છે, અથવા જ્યાં મૂલ્ય હોવું જોઈએ ત્યાં અલ્પવિરામ છે.',
    e_missing_comma: 'બે આઇટમ વચ્ચે અલ્પવિરામ નથી.',
    e_missing_colon: 'નામ પછી કોલન ( : ) નથી.',
    e_single_quotes: 'JSON માં ડબલ ક્વોટ " " જોઈએ, સિંગલ ક્વોટ \' \' નહીં.',
    e_key_quotes: 'નામ (કી) ડબલ ક્વોટમાં હોવાં જોઈએ, જેમ કે "name".',
    e_no_quotes: 'લખાણવાળાં મૂલ્ય ડબલ ક્વોટમાં હોવાં જોઈએ, જેમ કે "Pune".',
    e_unclosed_string: 'આ લખાણ " થી શરૂ થાય છે પણ પૂરું થતું નથી.',
    e_newline_in_string: 'ક્વોટની અંદર નવી લાઇન ચાલતી નથી. તેને બદલે \\n લખો.',
    e_bad_char_in_string: 'ક્વોટની અંદર એક છુપાયેલું કંટ્રોલ ચિહ્ન છે.',
    e_bad_escape: 'બૅકસ્લૅશ કોડ ખોટો છે. \\" \\\\ \\n \\t કે \\u0041 વાપરો.',
    e_bad_number: 'આ સંખ્યા JSON માં ન ચાલે એ રીતે લખી છે (જેમ કે 01, 1. કે .5).',
    e_bad_literal: 'true, false કે null નાના અક્ષરોમાં લખો (True, None કે undefined નહીં).',
    e_extra_text: 'JSON પૂરો થયા પછી વધારાનું લખાણ છે.',
    e_comment: 'JSON માં ટિપ્પણી (// કે /* */) ચાલતી નથી.',
    e_too_deep: 'JSON બહુ ઊંડે સુધી અંદર-અંદર છે, તપાસી શકાતો નથી.',
    err_generic: 'ફેરવતી વખતે કંઈક ગરબડ થઈ.', err_csv: 'આ CSV માં કોઈ હરોળ મળી નહીં.', err_file: 'આ ફાઇલ વાંચી શકાઈ નહીં.',
    err_excel: 'પહેલાં શીટને CSV તરીકે સેવ કરો (Excel: File → Save as → CSV).', empty_input: 'ઉપર કંઈક પેસ્ટ કરો કે લખો, અથવા નમૂનો ખોલો.',
    valid_json: 'JSON સાચો છે.', valid_jsonl: 'JSON Lines સાચી છે: {n} લાઇન.', top_array: 'આ {n} આઇટમની યાદી છે.', top_object: 'આ {n} કી વાળો ઑબ્જેક્ટ છે.', top_value: 'આ એક જ મૂલ્ય છે.',
    j2c_done: '{recs} રેકૉર્ડ → {rows} હરોળ × {cols} કૉલમ.', read_jsonl: 'JSON Lines તરીકે વાંચ્યું.',
    note_capped: 'બહુ વધારે હરોળ: ફક્ત પહેલી {n} રાખી. યાદીઓ માટે "એક સેલમાં જોડો" અજમાવો.',
    note_dotkeys: 'કેટલાંક નામમાં પહેલેથી બિંદુ છે, એટલે તેમનો કૉલમ અંદરના ફીલ્ડ જેવો લાગી શકે.',
    c2j_done: '{rows} ઑબ્જેક્ટ, દરેકમાં {cols} ફીલ્ડ.',
    out_title: 'પરિણામ', tab_table: 'ટેબલ', tab_csv: 'CSV લખાણ', tab_json: 'JSON લખાણ', tab_schema: 'સ્કીમા', out_empty: 'હજી બતાવવા માટે કંઈ નથી.',
    text_cut: 'અહીં ફક્ત પહેલો ભાગ દેખાય છે. ડાઉનલોડ કે કૉપિથી બધું મળશે.', timing: '{ms} ms માં પૂરું',
    page_info: 'હરોળ {from}–{to}, કુલ {total}',
    sc_field: 'ફીલ્ડ', sc_type: 'પ્રકાર', sc_present: 'ભરેલું', sc_example: 'ઉદાહરણ', schema_info: '{recs} રેકૉર્ડમાં {n} ફીલ્ડ',
    ty_string: 'લખાણ', ty_number: 'સંખ્યા', ty_boolean: 'true/false', ty_null: 'ખાલી (null)', ty_object: 'ઑબ્જેક્ટ', ty_array: 'યાદી', mixed: 'મિશ્ર',
    tip1: 'નમૂનાના API જવાબથી શરૂ કરો: ટેબલ જુઓ, પછી "રેકૉર્ડની અંદરની યાદીઓ" ને "દરેક આઇટમની જુદી હરોળ" કરો અને 3 ઓર્ડરની 6 હરોળ બનતી જુઓ.',
    tip2: 'ઑફિસ: ઘણી ઍપ અને વેબસાઇટ JSON એક્સપોર્ટ કરે છે. તેને અહીં CSV બનાવી Excel કે Google Sheets માં ખોલો. અથવા શીટને CSV તરીકે સેવ કરી વેબસાઇટ કે ઍપ માટે JSON બનાવો.',
    tip3: '09876543210 જેવા ફોન નંબર અને 007 જેવા કોડ લખાણ જ રહે છે, કારણ કે સંખ્યા બને તો શરૂઆતનો 0 જતો રહે.',
    tip4: 'વર્ગ પ્રવૃત્તિ: બોર્ડ પર તમારા વર્ગ વિશે નાનો JSON લખો (નામ, ઉંમર, શોખની યાદી) જેમાં એક ભૂલ હોય. વિદ્યાર્થીઓ તે શોધે, પછી "JSON તપાસો અને ગોઠવો" થી તપાસે.',
    tip5: 'મોટી ફાઇલો (10 MB કે વધુ) પણ ચાલે છે. તમારી ફાઇલ આ ડિવાઇસ પર જ વંચાય છે; કંઈ અપલોડ થતું નથી.',
    words_title: 'જાણવા જેવા શબ્દો: અંદર શું થાય છે',
    w_json: '<b>JSON</b>: ઍપ ડેટા મોકલવા વાપરે તે લખાણની રીત. <code>{ }</code> એટલે ઑબ્જેક્ટ (નામ અને મૂલ્ય), <code>[ ]</code> એટલે યાદી. નામ અને લખાણ હંમેશાં ડબલ ક્વોટમાં.',
    w_csv: '<b>CSV</b>: લખાણમાં લખેલું સાદું ટેબલ: દરેક લાઇન એક હરોળ, મૂલ્ય અલ્પવિરામથી જુદાં. Excel અને Google Sheets તેને ખોલી શકે છે.',
    w_flat: '<b>ફ્લૅટ કરવું</b>: અંદર-અંદરના ડેટાને કૉલમ બનાવવા. <code>{"address": {"city": "Pune"}}</code> માંથી <code>address.city</code> નામનો કૉલમ બને છે.',
    w_jsonl: '<b>JSON Lines</b>: દરેક લાઇનમાં એક JSON ઑબ્જેક્ટ. લૉગ અને મોટા એક્સપોર્ટમાં સામાન્ય, કારણ કે પ્રોગ્રામ તેને લાઇન-લાઇન વાંચી શકે છે.',
    w_schema: '<b>સ્કીમા</b>: ફીલ્ડની યાદી, તેમનો પ્રકાર (લખાણ, સંખ્યા, true/false, યાદી) અને તે કેટલી વાર ભરેલાં છે.',
    w_errors: '<b>સામાન્ય ભૂલો</b>: છેલ્લી આઇટમ પછી અલ્પવિરામ, સિંગલ ક્વોટ, છૂટી ગયેલો અલ્પવિરામ, કે true ને બદલે True.'
  },
  pa: {
    app_title: 'JSON ↔ CSV ਕਨਵਰਟਰ',
    intro: 'ਐਪ ਅਤੇ API ਤੋਂ ਆਏ JSON ਨੂੰ Excel ਲਈ CSV ਟੇਬਲ ਵਿੱਚ ਬਦਲੋ, CSV ਨੂੰ JSON ਵਿੱਚ ਬਦਲੋ, ਅਤੇ JSON ਦੀ ਗ਼ਲਤੀ ਸਹੀ ਲਾਈਨ ਅਤੇ ਕਾਲਮ ਸਮੇਤ ਲੱਭੋ।',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON ਜਾਂਚੋ ਅਤੇ ਸਜਾਓ',
    help_j2c: 'ਕਿਸੇ ਐਪ, API ਜਾਂ ਐਕਸਪੋਰਟ ਦਾ JSON (ਜਾਂ JSON Lines) ਪੇਸਟ ਕਰੋ। ਅੰਦਰਲੇ ਫ਼ੀਲਡ customer.address.city ਵਰਗੇ ਕਾਲਮ ਬਣ ਜਾਂਦੇ ਹਨ।',
    help_c2j: 'CSV ਪੇਸਟ ਕਰੋ। ਹਰ ਕਤਾਰ ਇੱਕ ਆਬਜੈਕਟ ਬਣਦੀ ਹੈ; ਸੰਖਿਆਵਾਂ ਅਤੇ true/false ਸਹੀ ਕਿਸਮ ਵਿੱਚ ਆਉਂਦੇ ਹਨ, ਅਤੇ ਖ਼ਾਲੀ ਸੈੱਲ null ਬਣਦੇ ਹਨ।',
    help_fmt: 'ਦੇਖੋ ਕਿ JSON ਸਹੀ ਹੈ ਜਾਂ ਨਹੀਂ, ਗ਼ਲਤੀ ਦੀ ਸਹੀ ਥਾਂ ਲੱਭੋ, ਅਤੇ ਇਸ ਨੂੰ ਪੜ੍ਹਨ ਵਿੱਚ ਸੌਖਾ ਜਾਂ ਛੋਟਾ ਬਣਾਓ।',
    in_json: 'ਤੁਹਾਡਾ JSON', in_csv: 'ਤੁਹਾਡੀ CSV', in_label: 'ਇਨਪੁਟ', in_ph: 'ਇੱਥੇ ਪੇਸਟ ਕਰੋ, ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ, ਜਾਂ ਇਸ ਡੱਬੇ ਉੱਤੇ ਛੱਡੋ',
    sample_json: 'ਨਮੂਨਾ: API ਜਵਾਬ', sample_csv: 'ਨਮੂਨਾ: ਸੰਪਰਕ CSV', open_file: 'ਫ਼ਾਈਲ ਖੋਲ੍ਹੋ', convert: 'ਬਦਲੋ',
    drop_hint: 'ਫ਼ਾਈਲਾਂ ਇਸੇ ਡਿਵਾਈਸ ਉੱਤੇ ਰਹਿੰਦੀਆਂ ਹਨ।', size_b: '{n} ਬਾਈਟ', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'ਬਹੁਤ ਵੱਡੀ ਫ਼ਾਈਲ: ਇੱਥੇ ਸਿਰਫ਼ ਸ਼ੁਰੂ ਦਾ ਹਿੱਸਾ ਦਿਖਦਾ ਹੈ, ਪਰ ਪੂਰੀ ਫ਼ਾਈਲ ਬਦਲੀ ਜਾਂਦੀ ਹੈ।', big_press: 'ਇਹ ਵੱਡਾ ਇਨਪੁਟ ਹੈ। ਤਿਆਰ ਹੋਵੋ ਤਾਂ "ਬਦਲੋ" ਦਬਾਓ।',
    rec_path: 'ਕਤਾਰਾਂ ਕਿੱਥੋਂ ਆਉਣ', path_whole: '(ਪੂਰਾ ਆਬਜੈਕਟ ਇੱਕ ਕਤਾਰ)', path_list: '{path} ({n} ਆਈਟਮ)', path_top: 'ਸਭ ਤੋਂ ਉੱਪਰਲੀ ਸੂਚੀ ({n} ਆਈਟਮ)', path_lines: 'ਹਰ ਲਾਈਨ (JSON Lines)',
    arr_mode: 'ਰਿਕਾਰਡ ਅੰਦਰਲੀਆਂ ਸੂਚੀਆਂ', arr_join: 'ਇੱਕ ਸੈੱਲ ਵਿੱਚ ਜੋੜੋ ("a; b")', arr_explode: 'ਹਰ ਆਈਟਮ ਦੀ ਵੱਖਰੀ ਕਤਾਰ', arr_json: 'JSON ਲਿਖਤ ਹੀ ਰੱਖੋ',
    opt_text: 'ਹਰ ਮੁੱਲ ਲਿਖਤ ਹੀ ਰੱਖੋ', opt_nest: 'address.city ਵਰਗੇ ਕਾਲਮ ਨੂੰ ਅੰਦਰਲੇ ਆਬਜੈਕਟ ਵਿੱਚ ਬਦਲੋ',
    out_fmt: 'ਆਉਟਪੁਟ', fmt_pretty: 'JSON, ਪੜ੍ਹਨ ਵਿੱਚ ਸੌਖਾ', fmt_compact: 'JSON, ਇੱਕ ਲਾਈਨ (ਛੋਟਾ)', fmt_jsonl: 'JSON Lines (ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ ਆਬਜੈਕਟ)',
    indent: 'ਇੰਡੈਂਟ', indent_2: '2 ਸਪੇਸ', indent_4: '4 ਸਪੇਸ', indent_tab: 'ਟੈਬ', btn_pretty: 'ਸਜਾ ਕੇ ਦਿਖਾਓ', btn_min: 'ਛੋਟਾ ਕਰੋ', btn_use: 'ਨਤੀਜੇ ਨੂੰ ਇਨਪੁਟ ਬਣਾਓ',
    goto_err: 'ਇਨਪੁਟ ਵਿੱਚ ਦਿਖਾਓ', err_where: 'ਲਾਈਨ {line}, ਕਾਲਮ {col}',
    e_empty: 'ਇਨਪੁਟ ਖ਼ਾਲੀ ਹੈ।',
    e_unexpected_char: 'ਇਹ ਚਿੰਨ੍ਹ ਇੱਥੇ ਨਹੀਂ ਹੋਣਾ ਚਾਹੀਦਾ।',
    e_unexpected_end: 'ਲਿਖਤ ਜਲਦੀ ਮੁੱਕ ਗਈ: ਬੰਦ ਕਰਨ ਵਾਲਾ }, ] ਜਾਂ " ਨਹੀਂ ਹੈ।',
    e_trailing_comma: '} ਜਾਂ ] ਤੋਂ ਪਹਿਲਾਂ ਵਾਲਾ ਕਾਮਾ ਹਟਾਓ। JSON ਵਿੱਚ ਆਖ਼ਰੀ ਆਈਟਮ ਤੋਂ ਬਾਅਦ ਕਾਮਾ ਨਹੀਂ ਚੱਲਦਾ।',
    e_extra_comma: 'ਲਗਾਤਾਰ ਦੋ ਕਾਮੇ ਹਨ, ਜਾਂ ਜਿੱਥੇ ਮੁੱਲ ਹੋਣਾ ਚਾਹੀਦਾ ਉੱਥੇ ਕਾਮਾ ਹੈ।',
    e_missing_comma: 'ਦੋ ਆਈਟਮਾਂ ਵਿਚਕਾਰ ਕਾਮਾ ਨਹੀਂ ਹੈ।',
    e_missing_colon: 'ਨਾਮ ਤੋਂ ਬਾਅਦ ਕੋਲਨ ( : ) ਨਹੀਂ ਹੈ।',
    e_single_quotes: 'JSON ਵਿੱਚ ਡਬਲ ਕੋਟ " " ਚਾਹੀਦੇ ਹਨ, ਸਿੰਗਲ ਕੋਟ \' \' ਨਹੀਂ।',
    e_key_quotes: 'ਨਾਮ (ਕੀ) ਡਬਲ ਕੋਟ ਵਿੱਚ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ, ਜਿਵੇਂ "name"।',
    e_no_quotes: 'ਲਿਖਤ ਵਾਲੇ ਮੁੱਲ ਡਬਲ ਕੋਟ ਵਿੱਚ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ, ਜਿਵੇਂ "Pune"।',
    e_unclosed_string: 'ਇਹ ਲਿਖਤ " ਨਾਲ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ ਪਰ ਮੁੱਕਦੀ ਨਹੀਂ।',
    e_newline_in_string: 'ਕੋਟ ਦੇ ਅੰਦਰ ਨਵੀਂ ਲਾਈਨ ਨਹੀਂ ਚੱਲਦੀ। ਉਸ ਦੀ ਥਾਂ \\n ਲਿਖੋ।',
    e_bad_char_in_string: 'ਕੋਟ ਦੇ ਅੰਦਰ ਇੱਕ ਲੁਕਿਆ ਕੰਟਰੋਲ ਚਿੰਨ੍ਹ ਹੈ।',
    e_bad_escape: 'ਬੈਕਸਲੈਸ਼ ਕੋਡ ਗ਼ਲਤ ਹੈ। \\" \\\\ \\n \\t ਜਾਂ \\u0041 ਵਰਤੋ।',
    e_bad_number: 'ਇਹ ਸੰਖਿਆ ਉਸ ਤਰ੍ਹਾਂ ਲਿਖੀ ਹੈ ਜੋ JSON ਵਿੱਚ ਨਹੀਂ ਚੱਲਦੀ (ਜਿਵੇਂ 01, 1. ਜਾਂ .5)।',
    e_bad_literal: 'true, false ਜਾਂ null ਛੋਟੇ ਅੱਖਰਾਂ ਵਿੱਚ ਲਿਖੋ (True, None ਜਾਂ undefined ਨਹੀਂ)।',
    e_extra_text: 'JSON ਮੁੱਕਣ ਤੋਂ ਬਾਅਦ ਵਾਧੂ ਲਿਖਤ ਹੈ।',
    e_comment: 'JSON ਵਿੱਚ ਟਿੱਪਣੀ (// ਜਾਂ /* */) ਨਹੀਂ ਚੱਲਦੀ।',
    e_too_deep: 'JSON ਬਹੁਤ ਡੂੰਘਾਈ ਤੱਕ ਅੰਦਰ-ਅੰਦਰ ਹੈ, ਜਾਂਚਿਆ ਨਹੀਂ ਜਾ ਸਕਦਾ।',
    err_generic: 'ਬਦਲਦੇ ਸਮੇਂ ਕੁਝ ਗੜਬੜ ਹੋ ਗਈ।', err_csv: 'ਇਸ CSV ਵਿੱਚ ਕੋਈ ਕਤਾਰ ਨਹੀਂ ਮਿਲੀ।', err_file: 'ਇਹ ਫ਼ਾਈਲ ਪੜ੍ਹੀ ਨਹੀਂ ਜਾ ਸਕੀ।',
    err_excel: 'ਪਹਿਲਾਂ ਸ਼ੀਟ ਨੂੰ CSV ਵਜੋਂ ਸੇਵ ਕਰੋ (Excel: File → Save as → CSV)।', empty_input: 'ਉੱਪਰ ਕੁਝ ਪੇਸਟ ਕਰੋ ਜਾਂ ਲਿਖੋ, ਜਾਂ ਨਮੂਨਾ ਖੋਲ੍ਹੋ।',
    valid_json: 'JSON ਸਹੀ ਹੈ।', valid_jsonl: 'JSON Lines ਸਹੀ ਹੈ: {n} ਲਾਈਨਾਂ।', top_array: 'ਇਹ {n} ਆਈਟਮਾਂ ਦੀ ਸੂਚੀ ਹੈ।', top_object: 'ਇਹ {n} ਕੀ ਵਾਲਾ ਆਬਜੈਕਟ ਹੈ।', top_value: 'ਇਹ ਇੱਕ ਇਕੱਲਾ ਮੁੱਲ ਹੈ।',
    j2c_done: '{recs} ਰਿਕਾਰਡ → {rows} ਕਤਾਰਾਂ × {cols} ਕਾਲਮ।', read_jsonl: 'JSON Lines ਵਜੋਂ ਪੜ੍ਹਿਆ।',
    note_capped: 'ਬਹੁਤ ਜ਼ਿਆਦਾ ਕਤਾਰਾਂ: ਸਿਰਫ਼ ਪਹਿਲੀਆਂ {n} ਰੱਖੀਆਂ। ਸੂਚੀਆਂ ਲਈ "ਇੱਕ ਸੈੱਲ ਵਿੱਚ ਜੋੜੋ" ਅਜ਼ਮਾਓ।',
    note_dotkeys: 'ਕੁਝ ਨਾਮਾਂ ਵਿੱਚ ਪਹਿਲਾਂ ਤੋਂ ਬਿੰਦੀ ਹੈ, ਇਸ ਲਈ ਉਨ੍ਹਾਂ ਦਾ ਕਾਲਮ ਅੰਦਰਲੇ ਫ਼ੀਲਡ ਵਰਗਾ ਲੱਗ ਸਕਦਾ ਹੈ।',
    c2j_done: '{rows} ਆਬਜੈਕਟ, ਹਰ ਇੱਕ ਵਿੱਚ {cols} ਫ਼ੀਲਡ।',
    out_title: 'ਨਤੀਜਾ', tab_table: 'ਟੇਬਲ', tab_csv: 'CSV ਲਿਖਤ', tab_json: 'JSON ਲਿਖਤ', tab_schema: 'ਸਕੀਮਾ', out_empty: 'ਅਜੇ ਦਿਖਾਉਣ ਲਈ ਕੁਝ ਨਹੀਂ।',
    text_cut: 'ਇੱਥੇ ਸਿਰਫ਼ ਪਹਿਲਾ ਹਿੱਸਾ ਦਿਖ ਰਿਹਾ ਹੈ। ਡਾਊਨਲੋਡ ਜਾਂ ਕਾਪੀ ਨਾਲ ਪੂਰਾ ਮਿਲੇਗਾ।', timing: '{ms} ms ਵਿੱਚ ਪੂਰਾ',
    page_info: 'ਕਤਾਰਾਂ {from}–{to}, ਕੁੱਲ {total}',
    sc_field: 'ਫ਼ੀਲਡ', sc_type: 'ਕਿਸਮ', sc_present: 'ਭਰਿਆ', sc_example: 'ਉਦਾਹਰਨ', schema_info: '{recs} ਰਿਕਾਰਡਾਂ ਵਿੱਚ {n} ਫ਼ੀਲਡ',
    ty_string: 'ਲਿਖਤ', ty_number: 'ਸੰਖਿਆ', ty_boolean: 'true/false', ty_null: 'ਖ਼ਾਲੀ (null)', ty_object: 'ਆਬਜੈਕਟ', ty_array: 'ਸੂਚੀ', mixed: 'ਰਲਿਆ-ਮਿਲਿਆ',
    tip1: 'ਨਮੂਨਾ API ਜਵਾਬ ਨਾਲ ਸ਼ੁਰੂ ਕਰੋ: ਟੇਬਲ ਦੇਖੋ, ਫਿਰ "ਰਿਕਾਰਡ ਅੰਦਰਲੀਆਂ ਸੂਚੀਆਂ" ਨੂੰ "ਹਰ ਆਈਟਮ ਦੀ ਵੱਖਰੀ ਕਤਾਰ" ਕਰੋ ਅਤੇ 3 ਆਰਡਰਾਂ ਨੂੰ 6 ਕਤਾਰਾਂ ਬਣਦੇ ਦੇਖੋ।',
    tip2: 'ਦਫ਼ਤਰ: ਕਈ ਐਪਾਂ ਅਤੇ ਵੈੱਬਸਾਈਟਾਂ JSON ਐਕਸਪੋਰਟ ਕਰਦੀਆਂ ਹਨ। ਇਸ ਨੂੰ ਇੱਥੇ CSV ਬਣਾ ਕੇ Excel ਜਾਂ Google Sheets ਵਿੱਚ ਖੋਲ੍ਹੋ। ਜਾਂ ਸ਼ੀਟ ਨੂੰ CSV ਵਜੋਂ ਸੇਵ ਕਰਕੇ ਵੈੱਬਸਾਈਟ ਜਾਂ ਐਪ ਲਈ JSON ਬਣਾਓ।',
    tip3: '09876543210 ਵਰਗੇ ਫ਼ੋਨ ਨੰਬਰ ਅਤੇ 007 ਵਰਗੇ ਕੋਡ ਲਿਖਤ ਹੀ ਰਹਿੰਦੇ ਹਨ, ਕਿਉਂਕਿ ਸੰਖਿਆ ਬਣਨ ਨਾਲ ਸ਼ੁਰੂ ਦਾ 0 ਗੁਆਚ ਜਾਂਦਾ।',
    tip4: 'ਜਮਾਤ ਦੀ ਗਤੀਵਿਧੀ: ਬੋਰਡ ਉੱਤੇ ਆਪਣੀ ਜਮਾਤ ਬਾਰੇ ਇੱਕ ਛੋਟਾ JSON ਲਿਖੋ (ਨਾਮ, ਉਮਰ, ਸ਼ੌਕਾਂ ਦੀ ਸੂਚੀ) ਜਿਸ ਵਿੱਚ ਇੱਕ ਗ਼ਲਤੀ ਹੋਵੇ। ਵਿਦਿਆਰਥੀ ਉਹ ਲੱਭਣ, ਫਿਰ "JSON ਜਾਂਚੋ ਅਤੇ ਸਜਾਓ" ਨਾਲ ਜਾਂਚਣ।',
    tip5: 'ਵੱਡੀਆਂ ਫ਼ਾਈਲਾਂ (10 MB ਜਾਂ ਵੱਧ) ਵੀ ਚੱਲਦੀਆਂ ਹਨ। ਤੁਹਾਡੀ ਫ਼ਾਈਲ ਇਸੇ ਡਿਵਾਈਸ ਉੱਤੇ ਪੜ੍ਹੀ ਜਾਂਦੀ ਹੈ; ਕੁਝ ਵੀ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ।',
    words_title: 'ਜ਼ਰੂਰੀ ਸ਼ਬਦ: ਅੰਦਰ ਕੀ ਹੋ ਰਿਹਾ ਹੈ',
    w_json: '<b>JSON</b>: ਲਿਖਤ ਦਾ ਇੱਕ ਤਰੀਕਾ ਜਿਸ ਨਾਲ ਐਪਾਂ ਡਾਟਾ ਭੇਜਦੀਆਂ ਹਨ। <code>{ }</code> ਆਬਜੈਕਟ ਹੈ (ਨਾਮ ਅਤੇ ਮੁੱਲ), <code>[ ]</code> ਸੂਚੀ ਹੈ। ਨਾਮ ਅਤੇ ਲਿਖਤ ਹਮੇਸ਼ਾ ਡਬਲ ਕੋਟ ਵਿੱਚ।',
    w_csv: '<b>CSV</b>: ਲਿਖਤ ਵਿੱਚ ਲਿਖਿਆ ਸਾਦਾ ਟੇਬਲ: ਹਰ ਲਾਈਨ ਇੱਕ ਕਤਾਰ, ਮੁੱਲ ਕਾਮੇ ਨਾਲ ਵੱਖ। Excel ਅਤੇ Google Sheets ਇਸ ਨੂੰ ਖੋਲ੍ਹ ਸਕਦੇ ਹਨ।',
    w_flat: '<b>ਫ਼ਲੈਟ ਕਰਨਾ</b>: ਅੰਦਰ-ਅੰਦਰ ਵਾਲੇ ਡਾਟੇ ਨੂੰ ਕਾਲਮ ਬਣਾਉਣਾ। <code>{"address": {"city": "Pune"}}</code> ਤੋਂ <code>address.city</code> ਨਾਮ ਦਾ ਕਾਲਮ ਬਣਦਾ ਹੈ।',
    w_jsonl: '<b>JSON Lines</b>: ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ JSON ਆਬਜੈਕਟ। ਲੌਗ ਅਤੇ ਵੱਡੇ ਐਕਸਪੋਰਟ ਵਿੱਚ ਆਮ ਹੈ, ਕਿਉਂਕਿ ਪ੍ਰੋਗਰਾਮ ਇਸ ਨੂੰ ਲਾਈਨ-ਦਰ-ਲਾਈਨ ਪੜ੍ਹ ਸਕਦਾ ਹੈ।',
    w_schema: '<b>ਸਕੀਮਾ</b>: ਫ਼ੀਲਡਾਂ ਦੀ ਸੂਚੀ, ਉਨ੍ਹਾਂ ਦੀ ਕਿਸਮ (ਲਿਖਤ, ਸੰਖਿਆ, true/false, ਸੂਚੀ) ਅਤੇ ਉਹ ਕਿੰਨੀ ਵਾਰ ਭਰੇ ਹਨ।',
    w_errors: '<b>ਆਮ ਗ਼ਲਤੀਆਂ</b>: ਆਖ਼ਰੀ ਆਈਟਮ ਤੋਂ ਬਾਅਦ ਕਾਮਾ, ਸਿੰਗਲ ਕੋਟ, ਛੁੱਟਿਆ ਕਾਮਾ, ਜਾਂ true ਦੀ ਥਾਂ True।'
  },
  or: {
    app_title: 'JSON ↔ CSV କନଭର୍ଟର',
    intro: 'ଆପ ଓ API ରୁ ଆସିଥିବା JSON କୁ Excel ପାଇଁ CSV ଟେବୁଲରେ ବଦଳାନ୍ତୁ, CSV କୁ JSON ରେ ବଦଳାନ୍ତୁ, ଓ JSON ର ଭୁଲ ଠିକ୍ ଲାଇନ ଓ ସ୍ତମ୍ଭ ସହ ଖୋଜନ୍ତୁ।',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON ଯାଞ୍ଚ ଓ ସଜାଡ଼ନ୍ତୁ',
    help_j2c: 'କୌଣସି ଆପ, API କିମ୍ବା ଏକ୍ସପୋର୍ଟର JSON (କିମ୍ବା JSON Lines) ପେଷ୍ଟ କରନ୍ତୁ। ଭିତରର ଫିଲ୍ଡ customer.address.city ଭଳି ସ୍ତମ୍ଭ ହୋଇଯାଏ।',
    help_c2j: 'CSV ପେଷ୍ଟ କରନ୍ତୁ। ପ୍ରତି ଧାଡ଼ି ଏକ ଅବଜେକ୍ଟ ହୁଏ; ସଂଖ୍ୟା ଓ true/false ଠିକ୍ ପ୍ରକାରରେ ଆସେ, ଓ ଖାଲି ସେଲ null ହୁଏ।',
    help_fmt: 'JSON ଠିକ୍ ଅଛି କି ନାହିଁ ଦେଖନ୍ତୁ, ଭୁଲର ଠିକ୍ ସ୍ଥାନ ଖୋଜନ୍ତୁ, ଓ ଏହାକୁ ପଢ଼ିବାକୁ ସହଜ କିମ୍ବା ଛୋଟ କରନ୍ତୁ।',
    in_json: 'ଆପଣଙ୍କ JSON', in_csv: 'ଆପଣଙ୍କ CSV', in_label: 'ଇନପୁଟ', in_ph: 'ଏଠାରେ ପେଷ୍ଟ କରନ୍ତୁ, ଫାଇଲ ଖୋଲନ୍ତୁ, କିମ୍ବା ଏହି ବାକ୍ସରେ ଛାଡ଼ନ୍ତୁ',
    sample_json: 'ନମୁନା: API ଉତ୍ତର', sample_csv: 'ନମୁନା: ଯୋଗାଯୋଗ CSV', open_file: 'ଫାଇଲ ଖୋଲନ୍ତୁ', convert: 'ବଦଳାନ୍ତୁ',
    drop_hint: 'ଫାଇଲ ଏହି ଡିଭାଇସରେ ହିଁ ରହେ।', size_b: '{n} ବାଇଟ', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'ବହୁତ ବଡ଼ ଫାଇଲ: ଏଠାରେ କେବଳ ଆରମ୍ଭ ଅଂଶ ଦେଖାଯାଏ, କିନ୍ତୁ ପୂରା ଫାଇଲ ବଦଳାଯାଏ।', big_press: 'ଏହା ବଡ଼ ଇନପୁଟ। ପ୍ରସ୍ତୁତ ହେଲେ "ବଦଳାନ୍ତୁ" ଦବାନ୍ତୁ।',
    rec_path: 'ଧାଡ଼ି କେଉଁଠୁ ଆସିବ', path_whole: '(ପୂରା ଅବଜେକ୍ଟ ଗୋଟିଏ ଧାଡ଼ି)', path_list: '{path} ({n}ଟି ଆଇଟମ)', path_top: 'ସବୁଠୁ ଉପର ତାଲିକା ({n}ଟି ଆଇଟମ)', path_lines: 'ପ୍ରତି ଲାଇନ (JSON Lines)',
    arr_mode: 'ରେକର୍ଡ ଭିତରର ତାଲିକା', arr_join: 'ଗୋଟିଏ ସେଲରେ ଯୋଡ଼ନ୍ତୁ ("a; b")', arr_explode: 'ପ୍ରତି ଆଇଟମର ଅଲଗା ଧାଡ଼ି', arr_json: 'JSON ଲେଖା ଭାବେ ହିଁ ରଖନ୍ତୁ',
    opt_text: 'ପ୍ରତି ମୂଲ୍ୟ ଲେଖା ଭାବେ ହିଁ ରଖନ୍ତୁ', opt_nest: 'address.city ଭଳି ସ୍ତମ୍ଭକୁ ଭିତର ଅବଜେକ୍ଟରେ ବଦଳାନ୍ତୁ',
    out_fmt: 'ଆଉଟପୁଟ', fmt_pretty: 'JSON, ପଢ଼ିବାକୁ ସହଜ', fmt_compact: 'JSON, ଗୋଟିଏ ଲାଇନ (ଛୋଟ)', fmt_jsonl: 'JSON Lines (ପ୍ରତି ଲାଇନରେ ଗୋଟିଏ ଅବଜେକ୍ଟ)',
    indent: 'ଇଣ୍ଡେଣ୍ଟ', indent_2: '2 ସ୍ପେସ', indent_4: '4 ସ୍ପେସ', indent_tab: 'ଟ୍ୟାବ', btn_pretty: 'ସଜାଡ଼ି ଦେଖାନ୍ତୁ', btn_min: 'ଛୋଟ କରନ୍ତୁ', btn_use: 'ଫଳାଫଳକୁ ଇନପୁଟ କରନ୍ତୁ',
    goto_err: 'ଇନପୁଟରେ ଦେଖାନ୍ତୁ', err_where: 'ଲାଇନ {line}, ସ୍ତମ୍ଭ {col}',
    e_empty: 'ଇନପୁଟ ଖାଲି ଅଛି।',
    e_unexpected_char: 'ଏହି ଚିହ୍ନ ଏଠାରେ ରହିବା କଥା ନୁହେଁ।',
    e_unexpected_end: 'ଲେଖା ଶୀଘ୍ର ଶେଷ ହୋଇଗଲା: ବନ୍ଦ କରିବା }, ] କିମ୍ବା " ନାହିଁ।',
    e_trailing_comma: '} କିମ୍ବା ] ପୂର୍ବର କମା କାଢ଼ନ୍ତୁ। JSON ରେ ଶେଷ ଆଇଟମ ପରେ କମା ଚଳେ ନାହିଁ।',
    e_extra_comma: 'ଲଗାତାର ଦୁଇଟି କମା ଅଛି, କିମ୍ବା ଯେଉଁଠି ମୂଲ୍ୟ ରହିବା କଥା ସେଠାରେ କମା ଅଛି।',
    e_missing_comma: 'ଦୁଇଟି ଆଇଟମ ମଝିରେ କମା ନାହିଁ।',
    e_missing_colon: 'ନାମ ପରେ କୋଲନ ( : ) ନାହିଁ।',
    e_single_quotes: 'JSON ରେ ଡବଲ କୋଟ " " ଦରକାର, ସିଙ୍ଗଲ କୋଟ \' \' ନୁହେଁ।',
    e_key_quotes: 'ନାମ (କି) ଡବଲ କୋଟ ଭିତରେ ରହିବା ଦରକାର, ଯେପରି "name"।',
    e_no_quotes: 'ଲେଖା ମୂଲ୍ୟ ଡବଲ କୋଟ ଭିତରେ ରହିବା ଦରକାର, ଯେପରି "Pune"।',
    e_unclosed_string: 'ଏହି ଲେଖା " ରେ ଆରମ୍ଭ ହୁଏ କିନ୍ତୁ ଶେଷ ହୁଏ ନାହିଁ।',
    e_newline_in_string: 'କୋଟ ଭିତରେ ନୂଆ ଲାଇନ ଚଳେ ନାହିଁ। ତା\' ବଦଳରେ \\n ଲେଖନ୍ତୁ।',
    e_bad_char_in_string: 'କୋଟ ଭିତରେ ଏକ ଲୁଚିଥିବା କଣ୍ଟ୍ରୋଲ ଚିହ୍ନ ଅଛି।',
    e_bad_escape: 'ବ୍ୟାକସ୍ଲାସ କୋଡ ଭୁଲ। \\" \\\\ \\n \\t କିମ୍ବା \\u0041 ବ୍ୟବହାର କରନ୍ତୁ।',
    e_bad_number: 'ଏହି ସଂଖ୍ୟା ଏପରି ଲେଖାଯାଇଛି ଯାହା JSON ରେ ଚଳେ ନାହିଁ (ଯେପରି 01, 1. କିମ୍ବା .5)।',
    e_bad_literal: 'true, false କିମ୍ବା null ଛୋଟ ଅକ୍ଷରରେ ଲେଖନ୍ତୁ (True, None କିମ୍ବା undefined ନୁହେଁ)।',
    e_extra_text: 'JSON ଶେଷ ହେବା ପରେ ଅତିରିକ୍ତ ଲେଖା ଅଛି।',
    e_comment: 'JSON ରେ ଟିପ୍ପଣୀ (// କିମ୍ବା /* */) ଚଳେ ନାହିଁ।',
    e_too_deep: 'JSON ବହୁତ ଗଭୀରକୁ ଭିତରେ-ଭିତରେ ଅଛି, ଯାଞ୍ଚ କରିହେବ ନାହିଁ।',
    err_generic: 'ବଦଳାଇବା ସମୟରେ କିଛି ଗଣ୍ଡଗୋଳ ହେଲା।', err_csv: 'ଏହି CSV ରେ କୌଣସି ଧାଡ଼ି ମିଳିଲା ନାହିଁ।', err_file: 'ଏହି ଫାଇଲ ପଢ଼ିହେଲା ନାହିଁ।',
    err_excel: 'ପ୍ରଥମେ ଶିଟ୍‌କୁ CSV ଭାବେ ସେଭ କରନ୍ତୁ (Excel: File → Save as → CSV)।', empty_input: 'ଉପରେ କିଛି ପେଷ୍ଟ କରନ୍ତୁ ବା ଲେଖନ୍ତୁ, କିମ୍ବା ନମୁନା ଖୋଲନ୍ତୁ।',
    valid_json: 'JSON ଠିକ୍ ଅଛି।', valid_jsonl: 'JSON Lines ଠିକ୍ ଅଛି: {n}ଟି ଲାଇନ।', top_array: 'ଏହା {n}ଟି ଆଇଟମର ତାଲିକା।', top_object: 'ଏହା {n}ଟି କି ଥିବା ଅବଜେକ୍ଟ।', top_value: 'ଏହା ଗୋଟିଏ ମାତ୍ର ମୂଲ୍ୟ।',
    j2c_done: '{recs}ଟି ରେକର୍ଡ → {rows}ଟି ଧାଡ଼ି × {cols}ଟି ସ୍ତମ୍ଭ।', read_jsonl: 'JSON Lines ଭାବେ ପଢ଼ାଗଲା।',
    note_capped: 'ବହୁତ ଅଧିକ ଧାଡ଼ି: କେବଳ ପ୍ରଥମ {n}ଟି ରଖାଗଲା। ତାଲିକା ପାଇଁ "ଗୋଟିଏ ସେଲରେ ଯୋଡ଼ନ୍ତୁ" ଚେଷ୍ଟା କରନ୍ତୁ।',
    note_dotkeys: 'କିଛି ନାମରେ ଆଗରୁ ବିନ୍ଦୁ ଅଛି, ତେଣୁ ସେମାନଙ୍କ ସ୍ତମ୍ଭ ଭିତର ଫିଲ୍ଡ ଭଳି ଦେଖାଯାଇପାରେ।',
    c2j_done: '{rows}ଟି ଅବଜେକ୍ଟ, ପ୍ରତ୍ୟେକରେ {cols}ଟି ଫିଲ୍ଡ।',
    out_title: 'ଫଳାଫଳ', tab_table: 'ଟେବୁଲ', tab_csv: 'CSV ଲେଖା', tab_json: 'JSON ଲେଖା', tab_schema: 'ସ୍କିମା', out_empty: 'ଏପର୍ଯ୍ୟନ୍ତ ଦେଖାଇବାକୁ କିଛି ନାହିଁ।',
    text_cut: 'ଏଠାରେ କେବଳ ପ୍ରଥମ ଅଂଶ ଦେଖାଯାଉଛି। ଡାଉନଲୋଡ କିମ୍ବା କପି କଲେ ପୂରା ମିଳିବ।', timing: '{ms} ms ରେ ସମ୍ପୂର୍ଣ୍ଣ',
    page_info: 'ଧାଡ଼ି {from}–{to}, ମୋଟ {total}',
    sc_field: 'ଫିଲ୍ଡ', sc_type: 'ପ୍ରକାର', sc_present: 'ଭରା', sc_example: 'ଉଦାହରଣ', schema_info: '{recs}ଟି ରେକର୍ଡରେ {n}ଟି ଫିଲ୍ଡ',
    ty_string: 'ଲେଖା', ty_number: 'ସଂଖ୍ୟା', ty_boolean: 'true/false', ty_null: 'ଖାଲି (null)', ty_object: 'ଅବଜେକ୍ଟ', ty_array: 'ତାଲିକା', mixed: 'ମିଶ୍ରିତ',
    tip1: 'ନମୁନା API ଉତ୍ତରରୁ ଆରମ୍ଭ କରନ୍ତୁ: ଟେବୁଲ ଦେଖନ୍ତୁ, ତା\'ପରେ "ରେକର୍ଡ ଭିତରର ତାଲିକା"କୁ "ପ୍ରତି ଆଇଟମର ଅଲଗା ଧାଡ଼ି" କରନ୍ତୁ ଓ 3ଟି ଅର୍ଡର 6ଟି ଧାଡ଼ି ହେବା ଦେଖନ୍ତୁ।',
    tip2: 'ଅଫିସ: ଅନେକ ଆପ ଓ ୱେବସାଇଟ JSON ଏକ୍ସପୋର୍ଟ କରନ୍ତି। ଏହାକୁ ଏଠାରେ CSV କରି Excel କିମ୍ବା Google Sheets ରେ ଖୋଲନ୍ତୁ। କିମ୍ବା ଶିଟ୍‌କୁ CSV ଭାବେ ସେଭ କରି ୱେବସାଇଟ ବା ଆପ ପାଇଁ JSON କରନ୍ତୁ।',
    tip3: '09876543210 ଭଳି ଫୋନ ନମ୍ବର ଓ 007 ଭଳି କୋଡ ଲେଖା ଭାବେ ହିଁ ରହେ, କାରଣ ସଂଖ୍ୟା ହେଲେ ଆରମ୍ଭର 0 ହଜିଯାଆନ୍ତା।',
    tip4: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟ: ବୋର୍ଡରେ ଆପଣଙ୍କ ଶ୍ରେଣୀ ବିଷୟରେ ଏକ ଛୋଟ JSON ଲେଖନ୍ତୁ (ନାମ, ବୟସ, ସଉକର ତାଲିକା) ଯେଉଁଥିରେ ଗୋଟିଏ ଭୁଲ ଅଛି। ଛାତ୍ରଛାତ୍ରୀ ତାହା ଖୋଜିବେ, ତା\'ପରେ "JSON ଯାଞ୍ଚ ଓ ସଜାଡ଼ନ୍ତୁ" ରେ ଯାଞ୍ଚ କରିବେ।',
    tip5: 'ବଡ଼ ଫାଇଲ (10 MB କିମ୍ବା ଅଧିକ) ମଧ୍ୟ ଚାଲେ। ଆପଣଙ୍କ ଫାଇଲ ଏହି ଡିଭାଇସରେ ହିଁ ପଢ଼ାଯାଏ; କିଛି ଅପଲୋଡ ହୁଏ ନାହିଁ।',
    words_title: 'ଜାଣିବା ଦରକାରୀ ଶବ୍ଦ: ଭିତରେ କ\'ଣ ହେଉଛି',
    w_json: '<b>JSON</b>: ଆପ ଡାଟା ପଠାଇବା ପାଇଁ ବ୍ୟବହାର କରୁଥିବା ଲେଖାର ଏକ ଉପାୟ। <code>{ }</code> ହେଉଛି ଅବଜେକ୍ଟ (ନାମ ଓ ମୂଲ୍ୟ), <code>[ ]</code> ହେଉଛି ତାଲିକା। ନାମ ଓ ଲେଖା ସବୁବେଳେ ଡବଲ କୋଟରେ।',
    w_csv: '<b>CSV</b>: ଲେଖାରେ ଲେଖାଯାଇଥିବା ସାଧା ଟେବୁଲ: ପ୍ରତି ଲାଇନ ଗୋଟିଏ ଧାଡ଼ି, ମୂଲ୍ୟ କମାରେ ଅଲଗା। Excel ଓ Google Sheets ଏହାକୁ ଖୋଲିପାରନ୍ତି।',
    w_flat: '<b>ଫ୍ଲାଟ କରିବା</b>: ଭିତରେ-ଭିତରେ ଥିବା ଡାଟାକୁ ସ୍ତମ୍ଭ କରିବା। <code>{"address": {"city": "Pune"}}</code> ରୁ <code>address.city</code> ନାମର ସ୍ତମ୍ଭ ହୁଏ।',
    w_jsonl: '<b>JSON Lines</b>: ପ୍ରତି ଲାଇନରେ ଗୋଟିଏ JSON ଅବଜେକ୍ଟ। ଲଗ ଓ ବଡ଼ ଏକ୍ସପୋର୍ଟରେ ସାଧାରଣ, କାରଣ ପ୍ରୋଗ୍ରାମ ଏହାକୁ ଲାଇନ-ଲାଇନ ପଢ଼ିପାରେ।',
    w_schema: '<b>ସ୍କିମା</b>: ଫିଲ୍ଡର ତାଲିକା, ସେମାନଙ୍କ ପ୍ରକାର (ଲେଖା, ସଂଖ୍ୟା, true/false, ତାଲିକା) ଓ ସେଗୁଡ଼ିକ କେତେଥର ଭରା।',
    w_errors: '<b>ସାଧାରଣ ଭୁଲ</b>: ଶେଷ ଆଇଟମ ପରେ କମା, ସିଙ୍ଗଲ କୋଟ, ଛାଡ଼ିଯାଇଥିବା କମା, କିମ୍ବା true ବଦଳରେ True।'
  },
  ta: {
    app_title: 'JSON ↔ CSV மாற்றி',
    intro: 'செயலிகள், API-களிலிருந்து வரும் JSON-ஐ Excel-க்கான CSV அட்டவணையாக மாற்றுங்கள், CSV-ஐ JSON ஆக மாற்றுங்கள், JSON பிழையைச் சரியான வரி, நெடுவரிசையுடன் கண்டுபிடியுங்கள்.',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON சரிபார் & ஒழுங்குபடுத்து',
    help_j2c: 'ஒரு செயலி, API அல்லது ஏற்றுமதியின் JSON (அல்லது JSON Lines) ஒட்டுங்கள். உள்ளே இருக்கும் புலங்கள் customer.address.city போன்ற நெடுவரிசைகளாகும்.',
    help_c2j: 'CSV ஒட்டுங்கள். ஒவ்வொரு வரிசையும் ஒரு பொருளாகும் (object); எண்களும் true/false-உம் சரியான வகையில் வரும், காலிக் கலங்கள் null ஆகும்.',
    help_fmt: 'JSON சரியா என்று பாருங்கள், பிழையின் சரியான இடத்தைக் கண்டுபிடியுங்கள், அதைப் படிக்க எளிதாக அல்லது சிறியதாக்குங்கள்.',
    in_json: 'உங்கள் JSON', in_csv: 'உங்கள் CSV', in_label: 'உள்ளீடு', in_ph: 'இங்கே ஒட்டுங்கள், கோப்பைத் திறங்கள், அல்லது இந்தப் பெட்டியில் விடுங்கள்',
    sample_json: 'மாதிரி: API பதில்', sample_csv: 'மாதிரி: தொடர்புகள் CSV', open_file: 'கோப்பைத் திற', convert: 'மாற்று',
    drop_hint: 'கோப்புகள் இந்தச் சாதனத்திலேயே இருக்கும்.', size_b: '{n} பைட்', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'மிகப் பெரிய கோப்பு: இங்கே தொடக்கம் மட்டுமே தெரியும், ஆனால் முழுக் கோப்பும் மாற்றப்படும்.', big_press: 'இது பெரிய உள்ளீடு. தயாரானதும் "மாற்று" அழுத்துங்கள்.',
    rec_path: 'வரிசைகள் எங்கிருந்து', path_whole: '(முழுப் பொருளும் ஒரு வரிசை)', path_list: '{path} ({n} உருப்படிகள்)', path_top: 'மேல்நிலைப் பட்டியல் ({n} உருப்படிகள்)', path_lines: 'ஒவ்வொரு வரியும் (JSON Lines)',
    arr_mode: 'பதிவுக்குள் உள்ள பட்டியல்கள்', arr_join: 'ஒரு கலத்தில் சேர் ("a; b")', arr_explode: 'ஒவ்வொரு உருப்படிக்கும் ஒரு வரிசை', arr_json: 'JSON உரையாகவே வை',
    opt_text: 'ஒவ்வொரு மதிப்பையும் உரையாகவே வை', opt_nest: 'address.city போன்ற நெடுவரிசைகளை உள்ளடங்கிய பொருளாக மாற்று',
    out_fmt: 'வெளியீடு', fmt_pretty: 'JSON, படிக்க எளிது', fmt_compact: 'JSON, ஒரே வரி (சிறியது)', fmt_jsonl: 'JSON Lines (ஒரு வரிக்கு ஒரு பொருள்)',
    indent: 'உள்தள்ளல்', indent_2: '2 இடைவெளி', indent_4: '4 இடைவெளி', indent_tab: 'டேப்', btn_pretty: 'அழகாகக் காட்டு', btn_min: 'சிறிதாக்கு', btn_use: 'முடிவை உள்ளீடாக்கு',
    goto_err: 'உள்ளீட்டில் காட்டு', err_where: 'வரி {line}, நெடுவரிசை {col}',
    e_empty: 'உள்ளீடு காலியாக உள்ளது.',
    e_unexpected_char: 'இந்தக் குறி இங்கே இருக்கக் கூடாது.',
    e_unexpected_end: 'உரை சீக்கிரம் முடிந்துவிட்டது: மூடும் }, ] அல்லது " இல்லை.',
    e_trailing_comma: '} அல்லது ] முன் உள்ள காற்புள்ளியை நீக்குங்கள். JSON-இல் கடைசி உருப்படிக்குப் பின் காற்புள்ளி கூடாது.',
    e_extra_comma: 'தொடர்ந்து இரண்டு காற்புள்ளிகள், அல்லது மதிப்பு இருக்க வேண்டிய இடத்தில் காற்புள்ளி.',
    e_missing_comma: 'இரண்டு உருப்படிகளுக்கு இடையே காற்புள்ளி இல்லை.',
    e_missing_colon: 'பெயருக்குப் பின் முக்காற்புள்ளி ( : ) இல்லை.',
    e_single_quotes: 'JSON-க்கு இரட்டை மேற்கோள் " " தேவை, ஒற்றை மேற்கோள் \' \' அல்ல.',
    e_key_quotes: 'பெயர்கள் (சாவிகள்) இரட்டை மேற்கோளுக்குள் இருக்க வேண்டும், "name" போல.',
    e_no_quotes: 'உரை மதிப்புகள் இரட்டை மேற்கோளுக்குள் இருக்க வேண்டும், "Pune" போல.',
    e_unclosed_string: 'இந்த உரை " உடன் தொடங்குகிறது, ஆனால் முடியவில்லை.',
    e_newline_in_string: 'மேற்கோளுக்குள் புதிய வரி கூடாது. அதற்குப் பதில் \\n எழுதுங்கள்.',
    e_bad_char_in_string: 'மேற்கோளுக்குள் ஒரு மறைந்த கட்டுப்பாட்டுக் குறி உள்ளது.',
    e_bad_escape: 'பின்சாய்வுக் குறியீடு தவறு. \\" \\\\ \\n \\t அல்லது \\u0041 பயன்படுத்துங்கள்.',
    e_bad_number: 'இந்த எண் JSON அனுமதிக்காத வகையில் எழுதப்பட்டுள்ளது (உதா. 01, 1. அல்லது .5).',
    e_bad_literal: 'true, false அல்லது null-ஐச் சிறிய எழுத்தில் எழுதுங்கள் (True, None அல்லது undefined அல்ல).',
    e_extra_text: 'JSON முடிந்த பின் கூடுதல் உரை உள்ளது.',
    e_comment: 'JSON-இல் குறிப்புரை (// அல்லது /* */) கூடாது.',
    e_too_deep: 'JSON மிக ஆழமாக உள்ளடங்கியுள்ளது, சரிபார்க்க முடியவில்லை.',
    err_generic: 'மாற்றும்போது ஏதோ தவறு நடந்தது.', err_csv: 'இந்த CSV-இல் வரிசைகள் இல்லை.', err_file: 'இந்தக் கோப்பைப் படிக்க முடியவில்லை.',
    err_excel: 'முதலில் தாளை CSV ஆகச் சேமியுங்கள் (Excel: File → Save as → CSV).', empty_input: 'மேலே ஏதாவது ஒட்டுங்கள் அல்லது எழுதுங்கள், அல்லது மாதிரியைத் திறங்கள்.',
    valid_json: 'JSON சரியானது.', valid_jsonl: 'JSON Lines சரியானது: {n} வரிகள்.', top_array: 'இது {n} உருப்படிகளின் பட்டியல்.', top_object: 'இது {n} சாவிகள் கொண்ட பொருள்.', top_value: 'இது ஒரே ஒரு மதிப்பு.',
    j2c_done: '{recs} பதிவுகள் → {rows} வரிசைகள் × {cols} நெடுவரிசைகள்.', read_jsonl: 'JSON Lines ஆகப் படிக்கப்பட்டது.',
    note_capped: 'மிக அதிக வரிசைகள்: முதல் {n} மட்டும் வைக்கப்பட்டன. பட்டியல்களுக்கு "ஒரு கலத்தில் சேர்" முயலுங்கள்.',
    note_dotkeys: 'சில பெயர்களில் ஏற்கெனவே புள்ளி உள்ளது, அதனால் அவற்றின் நெடுவரிசை உள்ளடங்கிய புலம் போலத் தோன்றலாம்.',
    c2j_done: '{rows} பொருள்கள், ஒவ்வொன்றிலும் {cols} புலங்கள்.',
    out_title: 'முடிவு', tab_table: 'அட்டவணை', tab_csv: 'CSV உரை', tab_json: 'JSON உரை', tab_schema: 'ஸ்கீமா', out_empty: 'இன்னும் காட்ட எதுவும் இல்லை.',
    text_cut: 'இங்கே முதல் பகுதி மட்டுமே தெரிகிறது. பதிவிறக்கம் அல்லது நகல் முழுவதையும் தரும்.', timing: '{ms} ms-இல் முடிந்தது',
    page_info: 'வரிசைகள் {from}–{to}, மொத்தம் {total}',
    sc_field: 'புலம்', sc_type: 'வகை', sc_present: 'நிரம்பியது', sc_example: 'எடுத்துக்காட்டு', schema_info: '{recs} பதிவுகளில் {n} புலங்கள்',
    ty_string: 'உரை', ty_number: 'எண்', ty_boolean: 'true/false', ty_null: 'காலி (null)', ty_object: 'பொருள்', ty_array: 'பட்டியல்', mixed: 'கலப்பு',
    tip1: 'மாதிரி API பதிலுடன் தொடங்குங்கள்: அட்டவணையைப் பாருங்கள், பிறகு "பதிவுக்குள் உள்ள பட்டியல்கள்" என்பதை "ஒவ்வொரு உருப்படிக்கும் ஒரு வரிசை" என மாற்றி 3 ஆர்டர்கள் 6 வரிசைகளாவதைப் பாருங்கள்.',
    tip2: 'அலுவலகம்: பல செயலிகளும் இணையதளங்களும் JSON ஏற்றுமதி செய்கின்றன. அதை இங்கே CSV ஆக்கி Excel அல்லது Google Sheets-இல் திறங்கள். அல்லது தாளை CSV ஆகச் சேமித்து இணையதளம் அல்லது செயலிக்கான JSON ஆக்குங்கள்.',
    tip3: '09876543210 போன்ற தொலைபேசி எண்களும் 007 போன்ற குறியீடுகளும் உரையாகவே இருக்கும்; எண்ணாக்கினால் தொடக்க 0 போய்விடும்.',
    tip4: 'வகுப்புச் செயல்பாடு: பலகையில் உங்கள் வகுப்பைப் பற்றி ஒரு சிறிய JSON எழுதுங்கள் (பெயர், வயது, பொழுதுபோக்குப் பட்டியல்), அதில் ஒரு பிழை இருக்கட்டும். மாணவர்கள் அதைக் கண்டுபிடித்து, "JSON சரிபார் & ஒழுங்குபடுத்து" மூலம் சரிபார்க்கட்டும்.',
    tip5: 'பெரிய கோப்புகளும் (10 MB அல்லது அதிகம்) வேலை செய்யும். உங்கள் கோப்பு இந்தச் சாதனத்திலேயே படிக்கப்படுகிறது; எதுவும் பதிவேற்றப்படாது.',
    words_title: 'தெரிந்துகொள்ள வேண்டிய சொற்கள்: உள்ளே என்ன நடக்கிறது',
    w_json: '<b>JSON</b>: செயலிகள் தரவை அனுப்பப் பயன்படுத்தும் உரை வடிவம். <code>{ }</code> என்பது பொருள் (பெயர்களும் மதிப்புகளும்), <code>[ ]</code> என்பது பட்டியல். பெயர்களும் உரையும் எப்போதும் இரட்டை மேற்கோளில்.',
    w_csv: '<b>CSV</b>: உரையாக எழுதப்பட்ட எளிய அட்டவணை: ஒரு வரிக்கு ஒரு வரிசை, மதிப்புகள் காற்புள்ளியால் பிரிக்கப்படும். Excel, Google Sheets இதைத் திறக்கும்.',
    w_flat: '<b>தட்டையாக்குதல்</b>: உள்ளடங்கிய தரவை நெடுவரிசைகளாக்குதல். <code>{"address": {"city": "Pune"}}</code> என்பது <code>address.city</code> என்ற நெடுவரிசையாகும்.',
    w_jsonl: '<b>JSON Lines</b>: ஒவ்வொரு வரியிலும் ஒரு JSON பொருள். பதிவுகள், பெரிய ஏற்றுமதிகளில் பொதுவானது, ஏனெனில் நிரல் அதை வரிவரியாகப் படிக்கலாம்.',
    w_schema: '<b>ஸ்கீமா</b>: புலங்களின் பட்டியல், அவற்றின் வகை (உரை, எண், true/false, பட்டியல்), அவை எத்தனை முறை நிரம்பியுள்ளன.',
    w_errors: '<b>பொதுவான பிழைகள்</b>: கடைசி உருப்படிக்குப் பின் காற்புள்ளி, ஒற்றை மேற்கோள், விடுபட்ட காற்புள்ளி, அல்லது true-க்குப் பதில் True.'
  },
  te: {
    app_title: 'JSON ↔ CSV మార్పిడి',
    intro: 'యాప్‌లు, API ల నుండి వచ్చే JSON ని Excel కోసం CSV పట్టికగా మార్చండి, CSV ని JSON గా మార్చండి, JSON తప్పును సరైన లైన్, నిలువు వరుసతో కనుగొనండి.',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON తనిఖీ & అమర్చు',
    help_j2c: 'యాప్, API లేదా ఎగుమతి నుండి వచ్చిన JSON (లేదా JSON Lines) పేస్ట్ చేయండి. లోపలి ఫీల్డ్‌లు customer.address.city లాంటి నిలువు వరుసలవుతాయి.',
    help_c2j: 'CSV పేస్ట్ చేయండి. ప్రతి వరుస ఒక ఆబ్జెక్ట్ అవుతుంది; సంఖ్యలు, true/false సరైన రకంలో వస్తాయి, ఖాళీ గడులు null అవుతాయి.',
    help_fmt: 'JSON సరైనదో కాదో చూడండి, తప్పు ఉన్న సరైన చోటు కనుగొనండి, దాన్ని చదవడానికి సులువుగా లేదా చిన్నదిగా చేయండి.',
    in_json: 'మీ JSON', in_csv: 'మీ CSV', in_label: 'ఇన్‌పుట్', in_ph: 'ఇక్కడ పేస్ట్ చేయండి, ఫైల్ తెరవండి, లేదా ఈ పెట్టెపై వదలండి',
    sample_json: 'నమూనా: API జవాబు', sample_csv: 'నమూనా: పరిచయాల CSV', open_file: 'ఫైల్ తెరవండి', convert: 'మార్చు',
    drop_hint: 'ఫైళ్లు ఈ పరికరంలోనే ఉంటాయి.', size_b: '{n} బైట్లు', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'చాలా పెద్ద ఫైల్: ఇక్కడ మొదటి భాగం మాత్రమే కనిపిస్తుంది, కానీ మొత్తం ఫైల్ మారుతుంది.', big_press: 'ఇది పెద్ద ఇన్‌పుట్. సిద్ధంగా ఉన్నప్పుడు "మార్చు" నొక్కండి.',
    rec_path: 'వరుసలు ఎక్కడి నుండి', path_whole: '(మొత్తం ఆబ్జెక్ట్ ఒక వరుస)', path_list: '{path} ({n} అంశాలు)', path_top: 'పై స్థాయి జాబితా ({n} అంశాలు)', path_lines: 'ప్రతి లైన్ (JSON Lines)',
    arr_mode: 'రికార్డులోని జాబితాలు', arr_join: 'ఒకే గడిలో కలుపు ("a; b")', arr_explode: 'ప్రతి అంశానికి ఒక వరుస', arr_json: 'JSON పాఠ్యంగానే ఉంచు',
    opt_text: 'ప్రతి విలువను పాఠ్యంగానే ఉంచు', opt_nest: 'address.city లాంటి నిలువు వరుసలను లోపలి ఆబ్జెక్ట్‌లుగా మార్చు',
    out_fmt: 'అవుట్‌పుట్', fmt_pretty: 'JSON, చదవడానికి సులువు', fmt_compact: 'JSON, ఒకే లైన్ (చిన్నది)', fmt_jsonl: 'JSON Lines (లైన్‌కు ఒక ఆబ్జెక్ట్)',
    indent: 'ఇండెంట్', indent_2: '2 ఖాళీలు', indent_4: '4 ఖాళీలు', indent_tab: 'ట్యాబ్', btn_pretty: 'అందంగా చూపు', btn_min: 'చిన్నది చేయి', btn_use: 'ఫలితాన్ని ఇన్‌పుట్‌గా వాడు',
    goto_err: 'ఇన్‌పుట్‌లో చూపు', err_where: 'లైన్ {line}, నిలువు వరుస {col}',
    e_empty: 'ఇన్‌పుట్ ఖాళీగా ఉంది.',
    e_unexpected_char: 'ఈ గుర్తు ఇక్కడ ఉండకూడదు.',
    e_unexpected_end: 'పాఠ్యం త్వరగా ముగిసింది: మూసే }, ] లేదా " లేదు.',
    e_trailing_comma: '} లేదా ] ముందు ఉన్న కామా తీసేయండి. JSON లో చివరి అంశం తర్వాత కామా కుదరదు.',
    e_extra_comma: 'వరుసగా రెండు కామాలు ఉన్నాయి, లేదా విలువ ఉండాల్సిన చోట కామా ఉంది.',
    e_missing_comma: 'రెండు అంశాల మధ్య కామా లేదు.',
    e_missing_colon: 'పేరు తర్వాత కోలన్ ( : ) లేదు.',
    e_single_quotes: 'JSON కి డబుల్ కోట్స్ " " కావాలి, సింగిల్ కోట్స్ \' \' కాదు.',
    e_key_quotes: 'పేర్లు (కీలు) డబుల్ కోట్స్ లోపల ఉండాలి, "name" లాగా.',
    e_no_quotes: 'పాఠ్య విలువలు డబుల్ కోట్స్ లోపల ఉండాలి, "Pune" లాగా.',
    e_unclosed_string: 'ఈ పాఠ్యం " తో మొదలై ఎప్పటికీ ముగియలేదు.',
    e_newline_in_string: 'కోట్స్ లోపల కొత్త లైన్ కుదరదు. దానికి బదులు \\n రాయండి.',
    e_bad_char_in_string: 'కోట్స్ లోపల దాగి ఉన్న ఒక కంట్రోల్ గుర్తు ఉంది.',
    e_bad_escape: 'బ్యాక్‌స్లాష్ కోడ్ తప్పు. \\" \\\\ \\n \\t లేదా \\u0041 వాడండి.',
    e_bad_number: 'ఈ సంఖ్య JSON అనుమతించని విధంగా రాసి ఉంది (ఉదా. 01, 1. లేదా .5).',
    e_bad_literal: 'true, false లేదా null ని చిన్న అక్షరాల్లో రాయండి (True, None లేదా undefined కాదు).',
    e_extra_text: 'JSON ముగిసిన తర్వాత అదనపు పాఠ్యం ఉంది.',
    e_comment: 'JSON లో వ్యాఖ్యలు (// లేదా /* */) కుదరవు.',
    e_too_deep: 'JSON చాలా లోతుగా లోపల-లోపల ఉంది, తనిఖీ చేయలేం.',
    err_generic: 'మార్చేటప్పుడు ఏదో తప్పు జరిగింది.', err_csv: 'ఈ CSV లో వరుసలు దొరకలేదు.', err_file: 'ఈ ఫైల్‌ను చదవలేకపోయాం.',
    err_excel: 'ముందుగా షీట్‌ను CSV గా సేవ్ చేయండి (Excel: File → Save as → CSV).', empty_input: 'పైన ఏదైనా పేస్ట్ చేయండి లేదా రాయండి, లేదా నమూనా తెరవండి.',
    valid_json: 'JSON సరైనది.', valid_jsonl: 'JSON Lines సరైనది: {n} లైన్లు.', top_array: 'ఇది {n} అంశాల జాబితా.', top_object: 'ఇది {n} కీలు ఉన్న ఆబ్జెక్ట్.', top_value: 'ఇది ఒకే ఒక విలువ.',
    j2c_done: '{recs} రికార్డులు → {rows} వరుసలు × {cols} నిలువు వరుసలు.', read_jsonl: 'JSON Lines గా చదివాం.',
    note_capped: 'చాలా ఎక్కువ వరుసలు: మొదటి {n} మాత్రమే ఉంచాం. జాబితాలకు "ఒకే గడిలో కలుపు" ప్రయత్నించండి.',
    note_dotkeys: 'కొన్ని పేర్లలో ముందే చుక్క ఉంది, అందుకే వాటి నిలువు వరుస లోపలి ఫీల్డ్‌లా కనిపించవచ్చు.',
    c2j_done: '{rows} ఆబ్జెక్ట్‌లు, ఒక్కోదానిలో {cols} ఫీల్డ్‌లు.',
    out_title: 'ఫలితం', tab_table: 'పట్టిక', tab_csv: 'CSV పాఠ్యం', tab_json: 'JSON పాఠ్యం', tab_schema: 'స్కీమా', out_empty: 'ఇంకా చూపడానికి ఏమీ లేదు.',
    text_cut: 'ఇక్కడ మొదటి భాగం మాత్రమే కనిపిస్తోంది. డౌన్‌లోడ్ లేదా కాపీతో మొత్తం వస్తుంది.', timing: '{ms} ms లో పూర్తి',
    page_info: 'వరుసలు {from}–{to}, మొత్తం {total}',
    sc_field: 'ఫీల్డ్', sc_type: 'రకం', sc_present: 'నిండినవి', sc_example: 'ఉదాహరణ', schema_info: '{recs} రికార్డుల్లో {n} ఫీల్డ్‌లు',
    ty_string: 'పాఠ్యం', ty_number: 'సంఖ్య', ty_boolean: 'true/false', ty_null: 'ఖాళీ (null)', ty_object: 'ఆబ్జెక్ట్', ty_array: 'జాబితా', mixed: 'మిశ్రమం',
    tip1: 'నమూనా API జవాబుతో మొదలుపెట్టండి: పట్టిక చూడండి, తర్వాత "రికార్డులోని జాబితాలు" ను "ప్రతి అంశానికి ఒక వరుస" గా మార్చి 3 ఆర్డర్లు 6 వరుసలు కావడం చూడండి.',
    tip2: 'ఆఫీసు: చాలా యాప్‌లు, వెబ్‌సైట్లు JSON ఎగుమతి చేస్తాయి. దాన్ని ఇక్కడ CSV గా మార్చి Excel లేదా Google Sheets లో తెరవండి. లేదా షీట్‌ను CSV గా సేవ్ చేసి వెబ్‌సైట్ లేదా యాప్ కోసం JSON చేయండి.',
    tip3: '09876543210 లాంటి ఫోన్ నంబర్లు, 007 లాంటి కోడ్‌లు పాఠ్యంగానే ఉంటాయి; సంఖ్యగా మారితే మొదటి 0 పోతుంది.',
    tip4: 'తరగతి కార్యకలాపం: బోర్డుపై మీ తరగతి గురించి ఒక చిన్న JSON రాయండి (పేరు, వయస్సు, అభిరుచుల జాబితా), అందులో ఒక తప్పు ఉంచండి. విద్యార్థులు దాన్ని కనుగొని, "JSON తనిఖీ & అమర్చు" తో సరిచూడాలి.',
    tip5: 'పెద్ద ఫైళ్లు (10 MB లేదా ఎక్కువ) కూడా పని చేస్తాయి. మీ ఫైల్ ఈ పరికరంలోనే చదవబడుతుంది; ఏదీ అప్‌లోడ్ కాదు.',
    words_title: 'తెలుసుకోవాల్సిన పదాలు: లోపల ఏం జరుగుతోంది',
    w_json: '<b>JSON</b>: యాప్‌లు డేటా పంపడానికి వాడే పాఠ్య రూపం. <code>{ }</code> అంటే ఆబ్జెక్ట్ (పేర్లు, విలువలు), <code>[ ]</code> అంటే జాబితా. పేర్లు, పాఠ్యం ఎప్పుడూ డబుల్ కోట్స్‌లో.',
    w_csv: '<b>CSV</b>: పాఠ్యంగా రాసిన సాధారణ పట్టిక: లైన్‌కు ఒక వరుస, విలువలు కామాతో వేరు. Excel, Google Sheets దీన్ని తెరవగలవు.',
    w_flat: '<b>చదును చేయడం</b>: లోపల-లోపల ఉన్న డేటాను నిలువు వరుసలుగా మార్చడం. <code>{"address": {"city": "Pune"}}</code> నుండి <code>address.city</code> అనే నిలువు వరుస వస్తుంది.',
    w_jsonl: '<b>JSON Lines</b>: ప్రతి లైన్‌లో ఒక JSON ఆబ్జెక్ట్. లాగ్‌లు, పెద్ద ఎగుమతుల్లో సాధారణం, ఎందుకంటే ప్రోగ్రామ్ దాన్ని లైన్‌వారీగా చదవగలదు.',
    w_schema: '<b>స్కీమా</b>: ఫీల్డ్‌ల జాబితా, వాటి రకం (పాఠ్యం, సంఖ్య, true/false, జాబితా), అవి ఎన్నిసార్లు నిండి ఉన్నాయి.',
    w_errors: '<b>సాధారణ తప్పులు</b>: చివరి అంశం తర్వాత కామా, సింగిల్ కోట్స్, మిస్సైన కామా, లేదా true కి బదులు True.'
  },
  kn: {
    app_title: 'JSON ↔ CSV ಪರಿವರ್ತಕ',
    intro: 'ಆ್ಯಪ್ ಮತ್ತು API ಗಳಿಂದ ಬರುವ JSON ಅನ್ನು Excel ಗಾಗಿ CSV ಕೋಷ್ಟಕವಾಗಿ ಬದಲಿಸಿ, CSV ಅನ್ನು JSON ಆಗಿ ಬದಲಿಸಿ, ಮತ್ತು JSON ತಪ್ಪನ್ನು ನಿಖರ ಸಾಲು ಮತ್ತು ಕಾಲಂ ಜೊತೆ ಹುಡುಕಿ.',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON ಪರಿಶೀಲಿಸಿ & ಜೋಡಿಸಿ',
    help_j2c: 'ಆ್ಯಪ್, API ಅಥವಾ ರಫ್ತಿನಿಂದ ಬಂದ JSON (ಅಥವಾ JSON Lines) ಪೇಸ್ಟ್ ಮಾಡಿ. ಒಳಗಿನ ಕ್ಷೇತ್ರಗಳು customer.address.city ರಂತಹ ಕಾಲಂಗಳಾಗುತ್ತವೆ.',
    help_c2j: 'CSV ಪೇಸ್ಟ್ ಮಾಡಿ. ಪ್ರತಿ ಸಾಲು ಒಂದು ಆಬ್ಜೆಕ್ಟ್ ಆಗುತ್ತದೆ; ಸಂಖ್ಯೆಗಳು ಮತ್ತು true/false ಸರಿಯಾದ ಬಗೆಯಲ್ಲಿ ಬರುತ್ತವೆ, ಖಾಲಿ ಕೋಶಗಳು null ಆಗುತ್ತವೆ.',
    help_fmt: 'JSON ಸರಿಯೇ ಎಂದು ನೋಡಿ, ತಪ್ಪಿನ ನಿಖರ ಸ್ಥಳ ಹುಡುಕಿ, ಮತ್ತು ಅದನ್ನು ಓದಲು ಸುಲಭ ಅಥವಾ ಚಿಕ್ಕದು ಮಾಡಿ.',
    in_json: 'ನಿಮ್ಮ JSON', in_csv: 'ನಿಮ್ಮ CSV', in_label: 'ಇನ್‌ಪುಟ್', in_ph: 'ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ, ಫೈಲ್ ತೆರೆಯಿರಿ, ಅಥವಾ ಈ ಪೆಟ್ಟಿಗೆಯಲ್ಲಿ ಬಿಡಿ',
    sample_json: 'ಮಾದರಿ: API ಉತ್ತರ', sample_csv: 'ಮಾದರಿ: ಸಂಪರ್ಕ CSV', open_file: 'ಫೈಲ್ ತೆರೆಯಿರಿ', convert: 'ಬದಲಿಸಿ',
    drop_hint: 'ಫೈಲ್‌ಗಳು ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತವೆ.', size_b: '{n} ಬೈಟ್', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'ತುಂಬಾ ದೊಡ್ಡ ಫೈಲ್: ಇಲ್ಲಿ ಮೊದಲ ಭಾಗ ಮಾತ್ರ ಕಾಣುತ್ತದೆ, ಆದರೆ ಇಡೀ ಫೈಲ್ ಬದಲಾಗುತ್ತದೆ.', big_press: 'ಇದು ದೊಡ್ಡ ಇನ್‌ಪುಟ್. ಸಿದ್ಧವಾದಾಗ "ಬದಲಿಸಿ" ಒತ್ತಿ.',
    rec_path: 'ಸಾಲುಗಳು ಎಲ್ಲಿಂದ', path_whole: '(ಇಡೀ ಆಬ್ಜೆಕ್ಟ್ ಒಂದು ಸಾಲು)', path_list: '{path} ({n} ಐಟಂಗಳು)', path_top: 'ಮೇಲ್ಮಟ್ಟದ ಪಟ್ಟಿ ({n} ಐಟಂಗಳು)', path_lines: 'ಪ್ರತಿ ಸಾಲು (JSON Lines)',
    arr_mode: 'ದಾಖಲೆಯೊಳಗಿನ ಪಟ್ಟಿಗಳು', arr_join: 'ಒಂದೇ ಕೋಶದಲ್ಲಿ ಜೋಡಿಸಿ ("a; b")', arr_explode: 'ಪ್ರತಿ ಐಟಂಗೆ ಒಂದು ಸಾಲು', arr_json: 'JSON ಪಠ್ಯವಾಗಿಯೇ ಇಡಿ',
    opt_text: 'ಪ್ರತಿ ಮೌಲ್ಯವನ್ನು ಪಠ್ಯವಾಗಿಯೇ ಇಡಿ', opt_nest: 'address.city ರಂತಹ ಕಾಲಂಗಳನ್ನು ಒಳಗಿನ ಆಬ್ಜೆಕ್ಟ್ ಆಗಿ ಬದಲಿಸಿ',
    out_fmt: 'ಔಟ್‌ಪುಟ್', fmt_pretty: 'JSON, ಓದಲು ಸುಲಭ', fmt_compact: 'JSON, ಒಂದೇ ಸಾಲು (ಚಿಕ್ಕದು)', fmt_jsonl: 'JSON Lines (ಸಾಲಿಗೆ ಒಂದು ಆಬ್ಜೆಕ್ಟ್)',
    indent: 'ಇಂಡೆಂಟ್', indent_2: '2 ಸ್ಪೇಸ್', indent_4: '4 ಸ್ಪೇಸ್', indent_tab: 'ಟ್ಯಾಬ್', btn_pretty: 'ಅಂದವಾಗಿ ತೋರಿಸಿ', btn_min: 'ಚಿಕ್ಕದು ಮಾಡಿ', btn_use: 'ಫಲಿತಾಂಶವನ್ನು ಇನ್‌ಪುಟ್ ಮಾಡಿ',
    goto_err: 'ಇನ್‌ಪುಟ್‌ನಲ್ಲಿ ತೋರಿಸಿ', err_where: 'ಸಾಲು {line}, ಕಾಲಂ {col}',
    e_empty: 'ಇನ್‌ಪುಟ್ ಖಾಲಿ ಇದೆ.',
    e_unexpected_char: 'ಈ ಚಿಹ್ನೆ ಇಲ್ಲಿ ಇರಬಾರದು.',
    e_unexpected_end: 'ಪಠ್ಯ ಬೇಗ ಮುಗಿದಿದೆ: ಮುಚ್ಚುವ }, ] ಅಥವಾ " ಇಲ್ಲ.',
    e_trailing_comma: '} ಅಥವಾ ] ಮೊದಲಿನ ಅಲ್ಪವಿರಾಮ ತೆಗೆಯಿರಿ. JSON ನಲ್ಲಿ ಕೊನೆಯ ಐಟಂ ನಂತರ ಅಲ್ಪವಿರಾಮ ಸಲ್ಲದು.',
    e_extra_comma: 'ಸತತ ಎರಡು ಅಲ್ಪವಿರಾಮಗಳಿವೆ, ಅಥವಾ ಮೌಲ್ಯ ಇರಬೇಕಾದಲ್ಲಿ ಅಲ್ಪವಿರಾಮ ಇದೆ.',
    e_missing_comma: 'ಎರಡು ಐಟಂಗಳ ನಡುವೆ ಅಲ್ಪವಿರಾಮ ಇಲ್ಲ.',
    e_missing_colon: 'ಹೆಸರಿನ ನಂತರ ಕೋಲನ್ ( : ) ಇಲ್ಲ.',
    e_single_quotes: 'JSON ಗೆ ಡಬಲ್ ಕೋಟ್ " " ಬೇಕು, ಸಿಂಗಲ್ ಕೋಟ್ \' \' ಅಲ್ಲ.',
    e_key_quotes: 'ಹೆಸರುಗಳು (ಕೀಗಳು) ಡಬಲ್ ಕೋಟ್ ಒಳಗೆ ಇರಬೇಕು, "name" ರಂತೆ.',
    e_no_quotes: 'ಪಠ್ಯ ಮೌಲ್ಯಗಳು ಡಬಲ್ ಕೋಟ್ ಒಳಗೆ ಇರಬೇಕು, "Pune" ರಂತೆ.',
    e_unclosed_string: 'ಈ ಪಠ್ಯ " ನಿಂದ ಶುರುವಾಗಿ ಮುಗಿಯಲೇ ಇಲ್ಲ.',
    e_newline_in_string: 'ಕೋಟ್ ಒಳಗೆ ಹೊಸ ಸಾಲು ಸಲ್ಲದು. ಅದರ ಬದಲು \\n ಬರೆಯಿರಿ.',
    e_bad_char_in_string: 'ಕೋಟ್ ಒಳಗೆ ಅಡಗಿದ ಒಂದು ನಿಯಂತ್ರಣ ಚಿಹ್ನೆ ಇದೆ.',
    e_bad_escape: 'ಬ್ಯಾಕ್‌ಸ್ಲ್ಯಾಶ್ ಕೋಡ್ ತಪ್ಪು. \\" \\\\ \\n \\t ಅಥವಾ \\u0041 ಬಳಸಿ.',
    e_bad_number: 'ಈ ಸಂಖ್ಯೆ JSON ಒಪ್ಪದ ರೀತಿಯಲ್ಲಿ ಬರೆದಿದೆ (ಉದಾ. 01, 1. ಅಥವಾ .5).',
    e_bad_literal: 'true, false ಅಥವಾ null ಅನ್ನು ಸಣ್ಣ ಅಕ್ಷರಗಳಲ್ಲಿ ಬರೆಯಿರಿ (True, None ಅಥವಾ undefined ಅಲ್ಲ).',
    e_extra_text: 'JSON ಮುಗಿದ ನಂತರ ಹೆಚ್ಚುವರಿ ಪಠ್ಯ ಇದೆ.',
    e_comment: 'JSON ನಲ್ಲಿ ಟಿಪ್ಪಣಿಗಳು (// ಅಥವಾ /* */) ಸಲ್ಲವು.',
    e_too_deep: 'JSON ತುಂಬಾ ಆಳವಾಗಿ ಒಳಗೊಳಗೆ ಇದೆ, ಪರಿಶೀಲಿಸಲಾಗದು.',
    err_generic: 'ಬದಲಿಸುವಾಗ ಏನೋ ತಪ್ಪಾಯಿತು.', err_csv: 'ಈ CSV ನಲ್ಲಿ ಸಾಲುಗಳು ಸಿಗಲಿಲ್ಲ.', err_file: 'ಈ ಫೈಲ್ ಓದಲಾಗಲಿಲ್ಲ.',
    err_excel: 'ಮೊದಲು ಶೀಟ್ ಅನ್ನು CSV ಆಗಿ ಉಳಿಸಿ (Excel: File → Save as → CSV).', empty_input: 'ಮೇಲೆ ಏನಾದರೂ ಪೇಸ್ಟ್ ಮಾಡಿ ಅಥವಾ ಬರೆಯಿರಿ, ಅಥವಾ ಮಾದರಿ ತೆರೆಯಿರಿ.',
    valid_json: 'JSON ಸರಿಯಾಗಿದೆ.', valid_jsonl: 'JSON Lines ಸರಿಯಾಗಿದೆ: {n} ಸಾಲುಗಳು.', top_array: 'ಇದು {n} ಐಟಂಗಳ ಪಟ್ಟಿ.', top_object: 'ಇದು {n} ಕೀಗಳಿರುವ ಆಬ್ಜೆಕ್ಟ್.', top_value: 'ಇದು ಒಂದೇ ಮೌಲ್ಯ.',
    j2c_done: '{recs} ದಾಖಲೆಗಳು → {rows} ಸಾಲುಗಳು × {cols} ಕಾಲಂಗಳು.', read_jsonl: 'JSON Lines ಆಗಿ ಓದಲಾಗಿದೆ.',
    note_capped: 'ತುಂಬಾ ಹೆಚ್ಚು ಸಾಲುಗಳು: ಮೊದಲ {n} ಮಾತ್ರ ಇಡಲಾಗಿದೆ. ಪಟ್ಟಿಗಳಿಗೆ "ಒಂದೇ ಕೋಶದಲ್ಲಿ ಜೋಡಿಸಿ" ಪ್ರಯತ್ನಿಸಿ.',
    note_dotkeys: 'ಕೆಲವು ಹೆಸರುಗಳಲ್ಲಿ ಈಗಾಗಲೇ ಬಿಂದು ಇದೆ, ಆದ್ದರಿಂದ ಅವುಗಳ ಕಾಲಂ ಒಳಗಿನ ಕ್ಷೇತ್ರದಂತೆ ಕಾಣಬಹುದು.',
    c2j_done: '{rows} ಆಬ್ಜೆಕ್ಟ್‌ಗಳು, ಪ್ರತಿಯೊಂದರಲ್ಲಿ {cols} ಕ್ಷೇತ್ರಗಳು.',
    out_title: 'ಫಲಿತಾಂಶ', tab_table: 'ಕೋಷ್ಟಕ', tab_csv: 'CSV ಪಠ್ಯ', tab_json: 'JSON ಪಠ್ಯ', tab_schema: 'ಸ್ಕೀಮಾ', out_empty: 'ಇನ್ನೂ ತೋರಿಸಲು ಏನೂ ಇಲ್ಲ.',
    text_cut: 'ಇಲ್ಲಿ ಮೊದಲ ಭಾಗ ಮಾತ್ರ ಕಾಣುತ್ತಿದೆ. ಡೌನ್‌ಲೋಡ್ ಅಥವಾ ಕಾಪಿ ಎಲ್ಲವನ್ನೂ ಕೊಡುತ್ತದೆ.', timing: '{ms} ms ನಲ್ಲಿ ಮುಗಿದಿದೆ',
    page_info: 'ಸಾಲುಗಳು {from}–{to}, ಒಟ್ಟು {total}',
    sc_field: 'ಕ್ಷೇತ್ರ', sc_type: 'ಬಗೆ', sc_present: 'ತುಂಬಿದ್ದು', sc_example: 'ಉದಾಹರಣೆ', schema_info: '{recs} ದಾಖಲೆಗಳಲ್ಲಿ {n} ಕ್ಷೇತ್ರಗಳು',
    ty_string: 'ಪಠ್ಯ', ty_number: 'ಸಂಖ್ಯೆ', ty_boolean: 'true/false', ty_null: 'ಖಾಲಿ (null)', ty_object: 'ಆಬ್ಜೆಕ್ಟ್', ty_array: 'ಪಟ್ಟಿ', mixed: 'ಮಿಶ್ರ',
    tip1: 'ಮಾದರಿ API ಉತ್ತರದಿಂದ ಶುರು ಮಾಡಿ: ಕೋಷ್ಟಕ ನೋಡಿ, ನಂತರ "ದಾಖಲೆಯೊಳಗಿನ ಪಟ್ಟಿಗಳು" ಅನ್ನು "ಪ್ರತಿ ಐಟಂಗೆ ಒಂದು ಸಾಲು" ಮಾಡಿ, 3 ಆರ್ಡರ್‌ಗಳು 6 ಸಾಲುಗಳಾಗುವುದನ್ನು ನೋಡಿ.',
    tip2: 'ಕಚೇರಿ: ಅನೇಕ ಆ್ಯಪ್‌ಗಳು ಮತ್ತು ವೆಬ್‌ಸೈಟ್‌ಗಳು JSON ರಫ್ತು ಮಾಡುತ್ತವೆ. ಅದನ್ನು ಇಲ್ಲಿ CSV ಮಾಡಿ Excel ಅಥವಾ Google Sheets ನಲ್ಲಿ ತೆರೆಯಿರಿ. ಅಥವಾ ಶೀಟ್ ಅನ್ನು CSV ಆಗಿ ಉಳಿಸಿ ವೆಬ್‌ಸೈಟ್ ಅಥವಾ ಆ್ಯಪ್‌ಗಾಗಿ JSON ಮಾಡಿ.',
    tip3: '09876543210 ರಂತಹ ಫೋನ್ ಸಂಖ್ಯೆಗಳು ಮತ್ತು 007 ರಂತಹ ಕೋಡ್‌ಗಳು ಪಠ್ಯವಾಗಿಯೇ ಉಳಿಯುತ್ತವೆ; ಸಂಖ್ಯೆಯಾದರೆ ಮೊದಲ 0 ಕಳೆದುಹೋಗುತ್ತಿತ್ತು.',
    tip4: 'ತರಗತಿ ಚಟುವಟಿಕೆ: ಬೋರ್ಡ್ ಮೇಲೆ ನಿಮ್ಮ ತರಗತಿಯ ಬಗ್ಗೆ ಒಂದು ಚಿಕ್ಕ JSON ಬರೆಯಿರಿ (ಹೆಸರು, ವಯಸ್ಸು, ಹವ್ಯಾಸಗಳ ಪಟ್ಟಿ), ಅದರಲ್ಲಿ ಒಂದು ತಪ್ಪು ಇರಲಿ. ವಿದ್ಯಾರ್ಥಿಗಳು ಅದನ್ನು ಹುಡುಕಿ, "JSON ಪರಿಶೀಲಿಸಿ & ಜೋಡಿಸಿ" ಮೂಲಕ ಪರಿಶೀಲಿಸಲಿ.',
    tip5: 'ದೊಡ್ಡ ಫೈಲ್‌ಗಳು (10 MB ಅಥವಾ ಹೆಚ್ಚು) ಕೂಡ ಕೆಲಸ ಮಾಡುತ್ತವೆ. ನಿಮ್ಮ ಫೈಲ್ ಈ ಸಾಧನದಲ್ಲೇ ಓದಲ್ಪಡುತ್ತದೆ; ಏನೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ.',
    words_title: 'ತಿಳಿಯಬೇಕಾದ ಪದಗಳು: ಒಳಗೆ ಏನಾಗುತ್ತಿದೆ',
    w_json: '<b>JSON</b>: ಆ್ಯಪ್‌ಗಳು ಡೇಟಾ ಕಳುಹಿಸಲು ಬಳಸುವ ಪಠ್ಯ ರೂಪ. <code>{ }</code> ಎಂದರೆ ಆಬ್ಜೆಕ್ಟ್ (ಹೆಸರುಗಳು ಮತ್ತು ಮೌಲ್ಯಗಳು), <code>[ ]</code> ಎಂದರೆ ಪಟ್ಟಿ. ಹೆಸರುಗಳು ಮತ್ತು ಪಠ್ಯ ಯಾವಾಗಲೂ ಡಬಲ್ ಕೋಟ್‌ನಲ್ಲಿ.',
    w_csv: '<b>CSV</b>: ಪಠ್ಯವಾಗಿ ಬರೆದ ಸರಳ ಕೋಷ್ಟಕ: ಸಾಲಿಗೆ ಒಂದು ಸಾಲು, ಮೌಲ್ಯಗಳು ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರೆ. Excel ಮತ್ತು Google Sheets ಇದನ್ನು ತೆರೆಯಬಲ್ಲವು.',
    w_flat: '<b>ಸಮತಟ್ಟು ಮಾಡುವುದು</b>: ಒಳಗೊಳಗಿನ ಡೇಟಾವನ್ನು ಕಾಲಂಗಳಾಗಿ ಮಾಡುವುದು. <code>{"address": {"city": "Pune"}}</code> ನಿಂದ <code>address.city</code> ಎಂಬ ಕಾಲಂ ಬರುತ್ತದೆ.',
    w_jsonl: '<b>JSON Lines</b>: ಪ್ರತಿ ಸಾಲಿನಲ್ಲಿ ಒಂದು JSON ಆಬ್ಜೆಕ್ಟ್. ಲಾಗ್‌ಗಳು ಮತ್ತು ದೊಡ್ಡ ರಫ್ತುಗಳಲ್ಲಿ ಸಾಮಾನ್ಯ, ಏಕೆಂದರೆ ಪ್ರೋಗ್ರಾಂ ಇದನ್ನು ಸಾಲು-ಸಾಲಾಗಿ ಓದಬಲ್ಲದು.',
    w_schema: '<b>ಸ್ಕೀಮಾ</b>: ಕ್ಷೇತ್ರಗಳ ಪಟ್ಟಿ, ಅವುಗಳ ಬಗೆ (ಪಠ್ಯ, ಸಂಖ್ಯೆ, true/false, ಪಟ್ಟಿ) ಮತ್ತು ಅವು ಎಷ್ಟು ಬಾರಿ ತುಂಬಿವೆ.',
    w_errors: '<b>ಸಾಮಾನ್ಯ ತಪ್ಪುಗಳು</b>: ಕೊನೆಯ ಐಟಂ ನಂತರ ಅಲ್ಪವಿರಾಮ, ಸಿಂಗಲ್ ಕೋಟ್, ಬಿಟ್ಟುಹೋದ ಅಲ್ಪವಿರಾಮ, ಅಥವಾ true ಬದಲು True.'
  },
  ml: {
    app_title: 'JSON ↔ CSV കൺവെർട്ടർ',
    intro: 'ആപ്പുകളിൽ നിന്നും API-കളിൽ നിന്നും വരുന്ന JSON-നെ Excel-നുള്ള CSV പട്ടികയാക്കൂ, CSV-യെ JSON ആക്കൂ, JSON-ലെ തെറ്റ് കൃത്യമായ വരിയും കോളവും സഹിതം കണ്ടെത്തൂ.',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON പരിശോധിക്കൂ & ക്രമീകരിക്കൂ',
    help_j2c: 'ഒരു ആപ്പ്, API അല്ലെങ്കിൽ എക്സ്പോർട്ടിൽ നിന്നുള്ള JSON (അല്ലെങ്കിൽ JSON Lines) പേസ്റ്റ് ചെയ്യൂ. ഉള്ളിലെ ഫീൽഡുകൾ customer.address.city പോലുള്ള കോളങ്ങളാകും.',
    help_c2j: 'CSV പേസ്റ്റ് ചെയ്യൂ. ഓരോ വരിയും ഒരു ഒബ്ജക്റ്റ് ആകും; സംഖ്യകളും true/false-ഉം ശരിയായ തരത്തിൽ വരും, ശൂന്യ സെല്ലുകൾ null ആകും.',
    help_fmt: 'JSON ശരിയാണോ എന്ന് നോക്കൂ, തെറ്റിന്റെ കൃത്യമായ സ്ഥലം കണ്ടെത്തൂ, അത് വായിക്കാൻ എളുപ്പമോ ചെറുതോ ആക്കൂ.',
    in_json: 'നിങ്ങളുടെ JSON', in_csv: 'നിങ്ങളുടെ CSV', in_label: 'ഇൻപുട്ട്', in_ph: 'ഇവിടെ പേസ്റ്റ് ചെയ്യൂ, ഫയൽ തുറക്കൂ, അല്ലെങ്കിൽ ഈ ബോക്സിൽ ഇടൂ',
    sample_json: 'മാതൃക: API മറുപടി', sample_csv: 'മാതൃക: കോൺടാക്റ്റ് CSV', open_file: 'ഫയൽ തുറക്കൂ', convert: 'മാറ്റൂ',
    drop_hint: 'ഫയലുകൾ ഈ ഉപകരണത്തിൽ തന്നെ നിൽക്കും.', size_b: '{n} ബൈറ്റ്', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'വളരെ വലിയ ഫയൽ: ഇവിടെ തുടക്കം മാത്രം കാണിക്കുന്നു, പക്ഷേ മുഴുവൻ ഫയലും മാറ്റുന്നു.', big_press: 'ഇത് വലിയ ഇൻപുട്ടാണ്. തയ്യാറാകുമ്പോൾ "മാറ്റൂ" അമർത്തൂ.',
    rec_path: 'വരികൾ എവിടെ നിന്ന്', path_whole: '(മുഴുവൻ ഒബ്ജക്റ്റ് ഒരു വരി)', path_list: '{path} ({n} ഇനങ്ങൾ)', path_top: 'മുകളിലെ ലിസ്റ്റ് ({n} ഇനങ്ങൾ)', path_lines: 'ഓരോ ലൈനും (JSON Lines)',
    arr_mode: 'റെക്കോർഡിനുള്ളിലെ ലിസ്റ്റുകൾ', arr_join: 'ഒരു സെല്ലിൽ ചേർക്കൂ ("a; b")', arr_explode: 'ഓരോ ഇനത്തിനും ഓരോ വരി', arr_json: 'JSON ടെക്സ്റ്റായി തന്നെ വയ്ക്കൂ',
    opt_text: 'എല്ലാ മൂല്യവും ടെക്സ്റ്റായി തന്നെ വയ്ക്കൂ', opt_nest: 'address.city പോലുള്ള കോളങ്ങൾ ഉള്ളിലെ ഒബ്ജക്റ്റാക്കൂ',
    out_fmt: 'ഔട്ട്പുട്ട്', fmt_pretty: 'JSON, വായിക്കാൻ എളുപ്പം', fmt_compact: 'JSON, ഒരു വരി (ചെറുത്)', fmt_jsonl: 'JSON Lines (ഓരോ ലൈനിലും ഒരു ഒബ്ജക്റ്റ്)',
    indent: 'ഇൻഡന്റ്', indent_2: '2 സ്പേസ്', indent_4: '4 സ്പേസ്', indent_tab: 'ടാബ്', btn_pretty: 'ഭംഗിയായി കാണിക്കൂ', btn_min: 'ചെറുതാക്കൂ', btn_use: 'ഫലം ഇൻപുട്ടാക്കൂ',
    goto_err: 'ഇൻപുട്ടിൽ കാണിക്കൂ', err_where: 'വരി {line}, കോളം {col}',
    e_empty: 'ഇൻപുട്ട് ശൂന്യമാണ്.',
    e_unexpected_char: 'ഈ ചിഹ്നം ഇവിടെ വരാൻ പാടില്ല.',
    e_unexpected_end: 'ടെക്സ്റ്റ് നേരത്തേ തീർന്നു: അടയ്ക്കുന്ന }, ] അല്ലെങ്കിൽ " ഇല്ല.',
    e_trailing_comma: '} അല്ലെങ്കിൽ ] മുമ്പുള്ള കോമ മാറ്റൂ. JSON-ൽ അവസാന ഇനത്തിന് ശേഷം കോമ പാടില്ല.',
    e_extra_comma: 'തുടർച്ചയായി രണ്ട് കോമകൾ, അല്ലെങ്കിൽ മൂല്യം വേണ്ട സ്ഥലത്ത് കോമ.',
    e_missing_comma: 'രണ്ട് ഇനങ്ങൾക്കിടയിൽ കോമ ഇല്ല.',
    e_missing_colon: 'പേരിന് ശേഷം കോളൻ ( : ) ഇല്ല.',
    e_single_quotes: 'JSON-ന് ഡബിൾ ക്വോട്ട് " " വേണം, സിംഗിൾ ക്വോട്ട് \' \' അല്ല.',
    e_key_quotes: 'പേരുകൾ (കീകൾ) ഡബിൾ ക്വോട്ടിനുള്ളിൽ വേണം, "name" പോലെ.',
    e_no_quotes: 'ടെക്സ്റ്റ് മൂല്യങ്ങൾ ഡബിൾ ക്വോട്ടിനുള്ളിൽ വേണം, "Pune" പോലെ.',
    e_unclosed_string: 'ഈ ടെക്സ്റ്റ് " കൊണ്ട് തുടങ്ങുന്നു, പക്ഷേ അവസാനിക്കുന്നില്ല.',
    e_newline_in_string: 'ക്വോട്ടിനുള്ളിൽ പുതിയ വരി പാടില്ല. പകരം \\n എഴുതൂ.',
    e_bad_char_in_string: 'ക്വോട്ടിനുള്ളിൽ മറഞ്ഞിരിക്കുന്ന ഒരു കൺട്രോൾ ചിഹ്നമുണ്ട്.',
    e_bad_escape: 'ബാക്ക്സ്ലാഷ് കോഡ് തെറ്റാണ്. \\" \\\\ \\n \\t അല്ലെങ്കിൽ \\u0041 ഉപയോഗിക്കൂ.',
    e_bad_number: 'ഈ സംഖ്യ JSON അനുവദിക്കാത്ത രീതിയിലാണ് എഴുതിയത് (ഉദാ. 01, 1. അല്ലെങ്കിൽ .5).',
    e_bad_literal: 'true, false അല്ലെങ്കിൽ null ചെറിയ അക്ഷരത്തിൽ എഴുതൂ (True, None, undefined അല്ല).',
    e_extra_text: 'JSON അവസാനിച്ചതിന് ശേഷം അധിക ടെക്സ്റ്റ് ഉണ്ട്.',
    e_comment: 'JSON-ൽ കമന്റുകൾ (// അല്ലെങ്കിൽ /* */) പാടില്ല.',
    e_too_deep: 'JSON വളരെ ആഴത്തിൽ ഉള്ളിൽ-ഉള്ളിലാണ്, പരിശോധിക്കാനാവില്ല.',
    err_generic: 'മാറ്റുമ്പോൾ എന്തോ പിശക് സംഭവിച്ചു.', err_csv: 'ഈ CSV-യിൽ വരികളൊന്നുമില്ല.', err_file: 'ഈ ഫയൽ വായിക്കാൻ കഴിഞ്ഞില്ല.',
    err_excel: 'ആദ്യം ഷീറ്റ് CSV ആയി സേവ് ചെയ്യൂ (Excel: File → Save as → CSV).', empty_input: 'മുകളിൽ എന്തെങ്കിലും പേസ്റ്റ് ചെയ്യൂ അല്ലെങ്കിൽ എഴുതൂ, അല്ലെങ്കിൽ മാതൃക തുറക്കൂ.',
    valid_json: 'JSON ശരിയാണ്.', valid_jsonl: 'JSON Lines ശരിയാണ്: {n} വരികൾ.', top_array: 'ഇത് {n} ഇനങ്ങളുള്ള ലിസ്റ്റാണ്.', top_object: 'ഇത് {n} കീകളുള്ള ഒബ്ജക്റ്റാണ്.', top_value: 'ഇത് ഒരു ഒറ്റ മൂല്യമാണ്.',
    j2c_done: '{recs} റെക്കോർഡുകൾ → {rows} വരികൾ × {cols} കോളങ്ങൾ.', read_jsonl: 'JSON Lines ആയി വായിച്ചു.',
    note_capped: 'വളരെയധികം വരികൾ: ആദ്യ {n} മാത്രം നിലനിർത്തി. ലിസ്റ്റുകൾക്ക് "ഒരു സെല്ലിൽ ചേർക്കൂ" പരീക്ഷിക്കൂ.',
    note_dotkeys: 'ചില പേരുകളിൽ ഇതിനകം ഡോട്ട് ഉണ്ട്, അതിനാൽ അവയുടെ കോളം ഉള്ളിലെ ഫീൽഡ് പോലെ തോന്നാം.',
    c2j_done: '{rows} ഒബ്ജക്റ്റുകൾ, ഓരോന്നിലും {cols} ഫീൽഡുകൾ.',
    out_title: 'ഫലം', tab_table: 'പട്ടിക', tab_csv: 'CSV ടെക്സ്റ്റ്', tab_json: 'JSON ടെക്സ്റ്റ്', tab_schema: 'സ്കീമ', out_empty: 'ഇതുവരെ കാണിക്കാൻ ഒന്നുമില്ല.',
    text_cut: 'ഇവിടെ ആദ്യ ഭാഗം മാത്രമേ കാണിക്കുന്നുള്ളൂ. ഡൗൺലോഡോ കോപ്പിയോ മുഴുവനും തരും.', timing: '{ms} ms-ൽ പൂർത്തിയായി',
    page_info: 'വരികൾ {from}–{to}, ആകെ {total}',
    sc_field: 'ഫീൽഡ്', sc_type: 'തരം', sc_present: 'നിറഞ്ഞത്', sc_example: 'ഉദാഹരണം', schema_info: '{recs} റെക്കോർഡുകളിൽ {n} ഫീൽഡുകൾ',
    ty_string: 'ടെക്സ്റ്റ്', ty_number: 'സംഖ്യ', ty_boolean: 'true/false', ty_null: 'ശൂന്യം (null)', ty_object: 'ഒബ്ജക്റ്റ്', ty_array: 'ലിസ്റ്റ്', mixed: 'കലർന്നത്',
    tip1: 'മാതൃക API മറുപടിയിൽ നിന്ന് തുടങ്ങൂ: പട്ടിക നോക്കൂ, പിന്നെ "റെക്കോർഡിനുള്ളിലെ ലിസ്റ്റുകൾ" എന്നത് "ഓരോ ഇനത്തിനും ഓരോ വരി" ആക്കി 3 ഓർഡറുകൾ 6 വരികളാകുന്നത് കാണൂ.',
    tip2: 'ഓഫീസ്: പല ആപ്പുകളും വെബ്സൈറ്റുകളും JSON എക്സ്പോർട്ട് ചെയ്യുന്നു. അത് ഇവിടെ CSV ആക്കി Excel-ലോ Google Sheets-ലോ തുറക്കൂ. അല്ലെങ്കിൽ ഷീറ്റ് CSV ആയി സേവ് ചെയ്ത് വെബ്സൈറ്റിനോ ആപ്പിനോ വേണ്ട JSON ആക്കൂ.',
    tip3: '09876543210 പോലുള്ള ഫോൺ നമ്പറുകളും 007 പോലുള്ള കോഡുകളും ടെക്സ്റ്റായി തന്നെ നിൽക്കും; സംഖ്യയാക്കിയാൽ തുടക്കത്തിലെ 0 പോകും.',
    tip4: 'ക്ലാസ് പ്രവർത്തനം: ബോർഡിൽ നിങ്ങളുടെ ക്ലാസിനെക്കുറിച്ച് ഒരു ചെറിയ JSON എഴുതൂ (പേര്, പ്രായം, ഹോബികളുടെ ലിസ്റ്റ്), അതിൽ ഒരു തെറ്റ് വയ്ക്കൂ. വിദ്യാർഥികൾ അത് കണ്ടെത്തി, "JSON പരിശോധിക്കൂ & ക്രമീകരിക്കൂ" വഴി പരിശോധിക്കട്ടെ.',
    tip5: 'വലിയ ഫയലുകളും (10 MB അല്ലെങ്കിൽ അതിൽ കൂടുതൽ) പ്രവർത്തിക്കും. നിങ്ങളുടെ ഫയൽ ഈ ഉപകരണത്തിൽ തന്നെ വായിക്കുന്നു; ഒന്നും അപ്‌ലോഡ് ചെയ്യുന്നില്ല.',
    words_title: 'അറിയേണ്ട വാക്കുകൾ: ഉള്ളിൽ എന്താണ് നടക്കുന്നത്',
    w_json: '<b>JSON</b>: ആപ്പുകൾ ഡാറ്റ അയയ്ക്കാൻ ഉപയോഗിക്കുന്ന ടെക്സ്റ്റ് രൂപം. <code>{ }</code> ഒരു ഒബ്ജക്റ്റ് (പേരുകളും മൂല്യങ്ങളും), <code>[ ]</code> ഒരു ലിസ്റ്റ്. പേരുകളും ടെക്സ്റ്റും എപ്പോഴും ഡബിൾ ക്വോട്ടിൽ.',
    w_csv: '<b>CSV</b>: ടെക്സ്റ്റായി എഴുതിയ ലളിതമായ പട്ടിക: ഓരോ ലൈനും ഒരു വരി, മൂല്യങ്ങൾ കോമ കൊണ്ട് വേർതിരിച്ച്. Excel-നും Google Sheets-നും ഇത് തുറക്കാം.',
    w_flat: '<b>പരത്തൽ</b>: ഉള്ളിൽ-ഉള്ളിലുള്ള ഡാറ്റ കോളങ്ങളാക്കൽ. <code>{"address": {"city": "Pune"}}</code> എന്നത് <code>address.city</code> എന്ന കോളമാകും.',
    w_jsonl: '<b>JSON Lines</b>: ഓരോ ലൈനിലും ഒരു JSON ഒബ്ജക്റ്റ്. ലോഗുകളിലും വലിയ എക്സ്പോർട്ടുകളിലും സാധാരണം, കാരണം പ്രോഗ്രാമിന് ഇത് ലൈൻ-ലൈനായി വായിക്കാം.',
    w_schema: '<b>സ്കീമ</b>: ഫീൽഡുകളുടെ ലിസ്റ്റ്, അവയുടെ തരം (ടെക്സ്റ്റ്, സംഖ്യ, true/false, ലിസ്റ്റ്), അവ എത്ര തവണ നിറഞ്ഞിരിക്കുന്നു.',
    w_errors: '<b>സാധാരണ തെറ്റുകൾ</b>: അവസാന ഇനത്തിന് ശേഷം കോമ, സിംഗിൾ ക്വോട്ട്, വിട്ടുപോയ കോമ, അല്ലെങ്കിൽ true-ന് പകരം True.'
  },
  ur: {
    app_title: 'JSON ↔ CSV کنورٹر',
    intro: 'ایپ اور API سے آئے JSON کو Excel کے لیے CSV ٹیبل میں بدلیں، CSV کو JSON میں بدلیں، اور JSON کی غلطی ٹھیک لائن اور کالم کے ساتھ ڈھونڈیں۔',
    mode_j2c: 'JSON → CSV', mode_c2j: 'CSV → JSON', mode_fmt: 'JSON جانچیں اور سجائیں',
    help_j2c: 'کسی ایپ، API یا ایکسپورٹ کا JSON (یا JSON Lines) پیسٹ کریں۔ اندر کے فیلڈ customer.address.city جیسے کالم بن جاتے ہیں۔',
    help_c2j: 'CSV پیسٹ کریں۔ ہر قطار ایک آبجیکٹ بنتی ہے؛ اعداد اور true/false درست قسم میں آتے ہیں، اور خالی سیل null بنتے ہیں۔',
    help_fmt: 'دیکھیں کہ JSON درست ہے یا نہیں، غلطی کی ٹھیک جگہ ڈھونڈیں، اور اسے پڑھنے میں آسان یا چھوٹا بنائیں۔',
    in_json: 'آپ کا JSON', in_csv: 'آپ کی CSV', in_label: 'ان پٹ', in_ph: 'یہاں پیسٹ کریں، فائل کھولیں، یا اس باکس پر چھوڑیں',
    sample_json: 'نمونہ: API جواب', sample_csv: 'نمونہ: رابطے CSV', open_file: 'فائل کھولیں', convert: 'بدلیں',
    drop_hint: 'فائلیں اسی ڈیوائس پر رہتی ہیں۔', size_b: '{n} بائٹ', size_kb: '{n} KB', size_mb: '{n} MB',
    big_view: 'بہت بڑی فائل: یہاں صرف شروع کا حصہ دکھتا ہے، مگر پوری فائل بدلی جاتی ہے۔', big_press: 'یہ بڑا ان پٹ ہے۔ تیار ہوں تو "بدلیں" دبائیں۔',
    rec_path: 'قطاریں کہاں سے آئیں', path_whole: '(پورا آبجیکٹ ایک قطار)', path_list: '{path} ({n} آئٹم)', path_top: 'سب سے اوپر کی فہرست ({n} آئٹم)', path_lines: 'ہر لائن (JSON Lines)',
    arr_mode: 'ریکارڈ کے اندر کی فہرستیں', arr_join: 'ایک سیل میں جوڑیں ("a; b")', arr_explode: 'ہر آئٹم کی الگ قطار', arr_json: 'JSON متن ہی رکھیں',
    opt_text: 'ہر قدر کو متن ہی رکھیں', opt_nest: 'address.city جیسے کالم کو اندر والے آبجیکٹ میں بدلیں',
    out_fmt: 'آؤٹ پٹ', fmt_pretty: 'JSON، پڑھنے میں آسان', fmt_compact: 'JSON، ایک لائن (چھوٹا)', fmt_jsonl: 'JSON Lines (ہر لائن میں ایک آبجیکٹ)',
    indent: 'انڈینٹ', indent_2: '2 اسپیس', indent_4: '4 اسپیس', indent_tab: 'ٹیب', btn_pretty: 'سجا کر دکھائیں', btn_min: 'چھوٹا کریں', btn_use: 'نتیجے کو ان پٹ بنائیں',
    goto_err: 'ان پٹ میں دکھائیں', err_where: 'لائن {line}، کالم {col}',
    e_empty: 'ان پٹ خالی ہے۔',
    e_unexpected_char: 'یہ نشان یہاں نہیں ہونا چاہیے۔',
    e_unexpected_end: 'متن جلدی ختم ہو گیا: بند کرنے والا }، ] یا " نہیں ہے۔',
    e_trailing_comma: '} یا ] سے پہلے والا کوما ہٹائیں۔ JSON میں آخری آئٹم کے بعد کوما نہیں چلتا۔',
    e_extra_comma: 'لگاتار دو کوما ہیں، یا جہاں قدر ہونی چاہیے وہاں کوما ہے۔',
    e_missing_comma: 'دو آئٹم کے بیچ کوما نہیں ہے۔',
    e_missing_colon: 'نام کے بعد کولن ( : ) نہیں ہے۔',
    e_single_quotes: 'JSON میں ڈبل کوٹ " " چاہیے، سنگل کوٹ \' \' نہیں۔',
    e_key_quotes: 'نام (کی) ڈبل کوٹ میں ہونے چاہئیں، جیسے "name"۔',
    e_no_quotes: 'متن والی قدریں ڈبل کوٹ میں ہونی چاہئیں، جیسے "Pune"۔',
    e_unclosed_string: 'یہ متن " سے شروع ہوتا ہے مگر ختم نہیں ہوتا۔',
    e_newline_in_string: 'کوٹ کے اندر نئی لائن نہیں چلتی۔ اس کی جگہ \\n لکھیں۔',
    e_bad_char_in_string: 'کوٹ کے اندر ایک چھپا ہوا کنٹرول نشان ہے۔',
    e_bad_escape: 'بیک سلیش کوڈ غلط ہے۔ \\" \\\\ \\n \\t یا \\u0041 استعمال کریں۔',
    e_bad_number: 'یہ عدد اس طرح لکھا ہے جو JSON میں نہیں چلتا (جیسے 01، 1. یا .5)۔',
    e_bad_literal: 'true، false یا null چھوٹے حروف میں لکھیں (True، None یا undefined نہیں)۔',
    e_extra_text: 'JSON ختم ہونے کے بعد فالتو متن ہے۔',
    e_comment: 'JSON میں تبصرے (// یا /* */) نہیں چلتے۔',
    e_too_deep: 'JSON بہت گہرائی تک اندر اندر ہے، جانچا نہیں جا سکتا۔',
    err_generic: 'بدلتے وقت کچھ گڑبڑ ہو گئی۔', err_csv: 'اس CSV میں کوئی قطار نہیں ملی۔', err_file: 'یہ فائل پڑھی نہیں جا سکی۔',
    err_excel: 'پہلے شیٹ کو CSV میں محفوظ کریں (Excel: File → Save as → CSV)۔', empty_input: 'اوپر کچھ پیسٹ کریں یا لکھیں، یا نمونہ کھولیں۔',
    valid_json: 'JSON درست ہے۔', valid_jsonl: 'JSON Lines درست ہے: {n} لائنیں۔', top_array: 'یہ {n} آئٹم کی فہرست ہے۔', top_object: 'یہ {n} کی والا آبجیکٹ ہے۔', top_value: 'یہ ایک اکیلی قدر ہے۔',
    j2c_done: '{recs} ریکارڈ ← {rows} قطاریں × {cols} کالم۔', read_jsonl: 'JSON Lines کی طرح پڑھا۔',
    note_capped: 'بہت زیادہ قطاریں: صرف پہلی {n} رکھی گئیں۔ فہرستوں کے لیے "ایک سیل میں جوڑیں" آزمائیں۔',
    note_dotkeys: 'کچھ ناموں میں پہلے سے نقطہ ہے، اس لیے ان کا کالم اندر والے فیلڈ جیسا لگ سکتا ہے۔',
    c2j_done: '{rows} آبجیکٹ، ہر ایک میں {cols} فیلڈ۔',
    out_title: 'نتیجہ', tab_table: 'ٹیبل', tab_csv: 'CSV متن', tab_json: 'JSON متن', tab_schema: 'اسکیما', out_empty: 'ابھی دکھانے کو کچھ نہیں۔',
    text_cut: 'یہاں صرف پہلا حصہ دکھ رہا ہے۔ ڈاؤن لوڈ یا کاپی سے پورا ملے گا۔', timing: '{ms} ms میں مکمل',
    page_info: 'قطاریں {from}–{to}، کل {total}',
    sc_field: 'فیلڈ', sc_type: 'قسم', sc_present: 'بھرا ہوا', sc_example: 'مثال', schema_info: '{recs} ریکارڈ میں {n} فیلڈ',
    ty_string: 'متن', ty_number: 'عدد', ty_boolean: 'true/false', ty_null: 'خالی (null)', ty_object: 'آبجیکٹ', ty_array: 'فہرست', mixed: 'ملا جلا',
    tip1: 'نمونہ API جواب سے شروع کریں: ٹیبل دیکھیں، پھر "ریکارڈ کے اندر کی فہرستیں" کو "ہر آئٹم کی الگ قطار" کریں اور 3 آرڈر کو 6 قطاریں بنتے دیکھیں۔',
    tip2: 'دفتر: بہت سی ایپس اور ویب سائٹس JSON ایکسپورٹ کرتی ہیں۔ اسے یہاں CSV بنا کر Excel یا Google Sheets میں کھولیں۔ یا شیٹ کو CSV میں محفوظ کر کے ویب سائٹ یا ایپ کے لیے JSON بنائیں۔',
    tip3: '09876543210 جیسے فون نمبر اور 007 جیسے کوڈ متن ہی رہتے ہیں، کیونکہ عدد بننے پر شروع کا 0 غائب ہو جاتا۔',
    tip4: 'کلاس سرگرمی: بورڈ پر اپنی جماعت کے بارے میں ایک چھوٹا JSON لکھیں (نام، عمر، مشغلوں کی فہرست) جس میں ایک غلطی ہو۔ طلبہ اسے ڈھونڈیں، پھر "JSON جانچیں اور سجائیں" سے جانچیں۔',
    tip5: 'بڑی فائلیں (10 MB یا زیادہ) بھی چلتی ہیں۔ آپ کی فائل اسی ڈیوائس پر پڑھی جاتی ہے؛ کچھ بھی اپ لوڈ نہیں ہوتا۔',
    words_title: 'ضروری الفاظ: اندر کیا ہو رہا ہے',
    w_json: '<b>JSON</b>: متن کا ایک طریقہ جس سے ایپس ڈیٹا بھیجتی ہیں۔ <code>{ }</code> آبجیکٹ ہے (نام اور قدریں)، <code>[ ]</code> فہرست ہے۔ نام اور متن ہمیشہ ڈبل کوٹ میں۔',
    w_csv: '<b>CSV</b>: متن میں لکھا سادہ ٹیبل: ہر لائن ایک قطار، قدریں کوما سے الگ۔ Excel اور Google Sheets اسے کھول سکتے ہیں۔',
    w_flat: '<b>فلیٹ کرنا</b>: اندر اندر والے ڈیٹا کو کالم بنانا۔ <code>{"address": {"city": "Pune"}}</code> سے <code>address.city</code> نام کا کالم بنتا ہے۔',
    w_jsonl: '<b>JSON Lines</b>: ہر لائن میں ایک JSON آبجیکٹ۔ لاگ اور بڑے ایکسپورٹ میں عام ہے، کیونکہ پروگرام اسے لائن بہ لائن پڑھ سکتا ہے۔',
    w_schema: '<b>اسکیما</b>: فیلڈز کی فہرست، ان کی قسم (متن، عدد، true/false، فہرست) اور وہ کتنی بار بھرے ہیں۔',
    w_errors: '<b>عام غلطیاں</b>: آخری آئٹم کے بعد کوما، سنگل کوٹ، چھوٹا ہوا کوما، یا true کی جگہ True۔'
  }
};
