/* UI strings for the A/B Test Calculator. Keys are identical in all 12 languages. */
window.APP_STRINGS = {
  en: {
    app_title: "A/B Test Calculator",
    intro: "You tried two versions of a message, banner or notice. Did B really do better than A, or was it just luck? See the p-value, a confidence range, the chance B beats A, and plan how many people you need.",
    ex_label: "Try an example:",
    ex_whatsapp: "Two WhatsApp messages",
    ex_banner: "Shop banner",
    ex_notice: "School notice reminder",
    ex_whatsapp_note: "A sweet shop sent offer message A to 1,000 customers and message B to another 1,000. Conversion = the customer replied to place an order.",
    ex_banner_note: "An online saree shop showed banner A or banner B to visitors at random. Conversion = the visitor bought something.",
    ex_notice_note: "Parents got fee reminder A (plain), B (last date in bold) or C (sent twice). Conversion = the fee was paid on time.",
    data_h: "Your test results",
    col_version: "Version",
    col_visitors: "Visitors (people who saw it)",
    col_conv: "Conversions (people who did the action)",
    col_rate: "Conversion rate",
    ver_a: "Current version",
    ver_b: "New version",
    ver_c: "Another new version",
    add_c: "+ Add version C",
    remove_c: "Remove version C",
    sig_label: "Significance level",
    sig_5: "5% (usual)",
    sig_1: "1% (strict)",
    err_blank: "Fill in visitors and conversions for every version.",
    err_bad: "Use whole numbers like 1000 (no decimals, no minus sign).",
    err_zero: "Version {v}: visitors must be at least 1.",
    err_more: "Version {v}: conversions ({c}) cannot be more than visitors ({n}).",
    copy_result: "Copy result",
    res_h: "Result",
    res_wait: "Enter the numbers to see the result.",
    three_note: "With 3 versions, B and C are each compared with A. To keep false wins rare, each comparison must pass a stricter level: {a}.",
    cmp_h: "{v} compared with A",
    verdict_better: "{v} is better, and this is unlikely to be luck.",
    verdict_worse: "{v} is worse than A, and this is unlikely to be luck.",
    verdict_unsure: "Not enough evidence yet. The difference could just be luck.",
    verdict_sig_sub: "The p-value {p} is below {a}.",
    verdict_unsure_sub: "The p-value {p} is not below {a}. Keep the test running until you reach the planned number of people.",
    st_diff: "Difference ({v} − A)",
    pts_unit: "percentage points",
    st_uplift: "Relative uplift",
    st_p: "p-value",
    p_need: "significant if below {a}",
    st_ci: "{c}% confidence range of the difference",
    st_ci_val: "{lo} to {hi}",
    st_beat: "Chance {v} beats A",
    st_beat_sub: "Bayesian estimate",
    ci_note_pos: "The whole range is above 0, so {v} is very likely better.",
    ci_note_neg: "The whole range is below 0, so {v} is very likely worse.",
    ci_note_zero: "The range includes 0, so \"no real difference\" is still possible.",
    work_h: "Show the working (z-test)",
    work_pool: "Combined rate of A and {v}: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "Standard error (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = difference ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = chance of a z this far from 0 (on either side) if there were no real difference = {p}",
    work_ci: "Confidence range = difference ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "Chance of being the best",
    warn_small: "Very small sample: version {v} has fewer than 10 conversions or fewer than 10 non-conversions. Results can swing a lot. Collect more data.",
    warn_split: "Unequal split: {s}. If you meant to split people equally, a gap this big is very unlikely by chance. Check how people were given each version.",
    warn_peek: "You have only {x}% of the people the planner says you need ({n} per version). Stopping the moment the result looks good is called \"peeking\", and it gives many false wins. Wait for the planned number.",
    warn_peek_gen: "Do not peek: decide how many people you need (planner below) before you start, and judge the result only when you reach that number.",
    chart_h: "Where the true rate probably lies",
    chart_note: "Each curve shows the believable values of a version's true conversion rate. If the curves overlap a lot, the test cannot tell the versions apart yet.",
    chart_aria: "Curves of the likely true conversion rate of each version",
    axis_rate: "Conversion rate",
    plan_h: "Sample-size planner",
    plan_intro: "Before you start a test: how many people should see each version?",
    plan_base: "Current conversion rate (%)",
    plan_use_a: "Use rate of A",
    plan_change: "Smallest change worth finding",
    plan_abs: "percentage points",
    plan_rel: "% of current rate",
    plan_power: "Power (chance to catch a real change)",
    plan_sig: "Significance level",
    plan_versions: "Versions in the test",
    plan_daily: "People per day (all versions together)",
    plan_per: "People per version",
    plan_total: "Total people",
    plan_days: "Days needed",
    plan_days_val: "{n} days",
    plan_bad: "Enter a current rate between 0 and 100, and a change that keeps the new rate between 0 and 100.",
    plan_target: "You want to find a change from {a}% to {b}%.",
    plan_3note: "With 3 versions each comparison uses the stricter level {a}.",
    plan_formula: "Formula (two-sided test): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², where p̄ = (p1 + p2) ÷ 2. Here the z values are {za} and {zb}, so n = {raw}, rounded up to {n}.",
    plan_note: "Small changes need many more people: to find half the change, you need about 4 times as many people.",
    words_h: "Words to know",
    w_conv: "Conversion",
    d_conv: "The action you want: a reply, a purchase, a form filled, a fee paid, a click.",
    w_rate: "Conversion rate",
    d_rate: "Conversions ÷ people who saw it. 250 buyers out of 1,000 visitors = 25%.",
    w_uplift: "Uplift",
    d_uplift: "From 20% to 25% is a rise of 5 percentage points, which is a relative uplift of 25% (5 is a quarter of 20).",
    w_p: "p-value",
    d_p: "If A and B were really the same, how often would luck alone give a difference this big? A small p-value (like 0.01) means luck is an unlikely explanation.",
    w_sig: "Significance level",
    d_sig: "The p-value cut-off you choose before the test, usually 5%. Below it we call the result \"significant\".",
    w_ci: "Confidence range",
    d_ci: "The range of differences that fit the data. If it does not include 0, the result is significant.",
    w_power: "Power",
    d_power: "The chance that your test catches a real change of the size you planned for. 80% is common.",
    w_bayes: "Chance B beats A",
    d_bayes: "Another way to read the same data (Bayesian): how likely is it that the true rate of B is higher than that of A?",
    w_peek: "Peeking",
    d_peek: "Checking again and again and stopping as soon as the result looks significant. It makes false wins much more common.",
    help_title: "How to use / ideas",
    tip1: "Pick an example, or type the people and conversions for each version. The result updates as you type.",
    tip2: "At work: send two versions of a WhatsApp offer to two random halves of your customer list and count replies. Use the planner first to see how big the list must be.",
    tip3: "Shops and websites: show banner A or B at random during the same days (not A this week and B next week), and change only one thing at a time.",
    tip4: "In class: half the class gets homework reminder A, half gets B. Count who submits on time and test if the difference is real. Then toss coins to see how often pure luck makes a difference.",
    tip5: "Decide the number of people and the significance level before you start, and do not stop early just because the result looks good.",
    sum_row: "{v}: {r} ({c} of {n})"
  },
  hi: {
    app_title: "A/B टेस्ट कैलकुलेटर",
    intro: "आपने किसी मैसेज, बैनर या सूचना के दो रूप आज़माए। क्या B सच में A से बेहतर रहा, या यह बस किस्मत थी? p-value, भरोसे की सीमा, B के जीतने की संभावना देखें, और जानें कि कितने लोग चाहिए।",
    ex_label: "उदाहरण आज़माएँ:",
    ex_whatsapp: "दो WhatsApp मैसेज",
    ex_banner: "दुकान का बैनर",
    ex_notice: "स्कूल सूचना रिमाइंडर",
    ex_whatsapp_note: "एक मिठाई की दुकान ने 1,000 ग्राहकों को ऑफ़र मैसेज A और दूसरे 1,000 को मैसेज B भेजा। कन्वर्ज़न = ग्राहक ने ऑर्डर के लिए जवाब दिया।",
    ex_banner_note: "एक ऑनलाइन साड़ी दुकान ने आने वालों को बिना चुने (रैंडम) बैनर A या B दिखाया। कन्वर्ज़न = आने वाले ने कुछ खरीदा।",
    ex_notice_note: "अभिभावकों को फ़ीस रिमाइंडर A (सादा), B (आख़िरी तारीख़ मोटे अक्षरों में) या C (दो बार भेजा) मिला। कन्वर्ज़न = फ़ीस समय पर जमा हुई।",
    data_h: "आपके टेस्ट के नतीजे",
    col_version: "रूप",
    col_visitors: "विज़िटर (जिन्होंने देखा)",
    col_conv: "कन्वर्ज़न (जिन्होंने काम किया)",
    col_rate: "कन्वर्ज़न दर",
    ver_a: "मौजूदा रूप",
    ver_b: "नया रूप",
    ver_c: "एक और नया रूप",
    add_c: "+ रूप C जोड़ें",
    remove_c: "रूप C हटाएँ",
    sig_label: "सार्थकता स्तर",
    sig_5: "5% (आम)",
    sig_1: "1% (सख़्त)",
    err_blank: "हर रूप के लिए विज़िटर और कन्वर्ज़न भरें।",
    err_bad: "1000 जैसी पूरी संख्या लिखें (दशमलव या माइनस नहीं)।",
    err_zero: "रूप {v}: विज़िटर कम से कम 1 होने चाहिए।",
    err_more: "रूप {v}: कन्वर्ज़न ({c}) विज़िटर ({n}) से ज़्यादा नहीं हो सकते।",
    copy_result: "नतीजा कॉपी करें",
    res_h: "नतीजा",
    res_wait: "नतीजा देखने के लिए संख्याएँ भरें।",
    three_note: "3 रूपों में B और C दोनों की तुलना A से होती है। झूठी जीत कम रहे, इसलिए हर तुलना को ज़्यादा सख़्त स्तर पार करना होगा: {a}।",
    cmp_h: "{v} की तुलना A से",
    verdict_better: "{v} बेहतर है, और यह किस्मत होने की संभावना कम है।",
    verdict_worse: "{v} A से ख़राब है, और यह किस्मत होने की संभावना कम है।",
    verdict_unsure: "अभी पक्का सबूत नहीं है। यह अंतर बस किस्मत भी हो सकता है।",
    verdict_sig_sub: "p-value {p} है, जो {a} से कम है।",
    verdict_unsure_sub: "p-value {p} है, जो {a} से कम नहीं है। तय की गई गिनती के लोग पूरे होने तक टेस्ट चलाते रहें।",
    st_diff: "अंतर ({v} − A)",
    pts_unit: "प्रतिशत अंक",
    st_uplift: "तुलनात्मक बढ़त",
    st_p: "p-value",
    p_need: "{a} से कम हो तो सार्थक",
    st_ci: "अंतर की {c}% भरोसे की सीमा",
    st_ci_val: "{lo} से {hi}",
    st_beat: "{v} के A से आगे होने की संभावना",
    st_beat_sub: "बेज़ियन अनुमान",
    ci_note_pos: "पूरी सीमा 0 से ऊपर है, इसलिए {v} लगभग पक्का बेहतर है।",
    ci_note_neg: "पूरी सीमा 0 से नीचे है, इसलिए {v} लगभग पक्का ख़राब है।",
    ci_note_zero: "सीमा में 0 शामिल है, इसलिए \"कोई असली अंतर नहीं\" भी हो सकता है।",
    work_h: "हल देखें (z-टेस्ट)",
    work_pool: "A और {v} की मिली-जुली दर: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "मानक त्रुटि (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = अंतर ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = अगर कोई असली अंतर न हो, तो z के 0 से इतना दूर (किसी भी तरफ़) आने की संभावना = {p}",
    work_ci: "भरोसे की सीमा = अंतर ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "सबसे अच्छा होने की संभावना",
    warn_small: "बहुत छोटा सैंपल: रूप {v} में 10 से कम कन्वर्ज़न या 10 से कम बिना-कन्वर्ज़न हैं। नतीजे बहुत ऊपर-नीचे हो सकते हैं। और डेटा जुटाएँ।",
    warn_split: "बँटवारा बराबर नहीं: {s}। अगर आप लोगों को बराबर बाँटना चाहते थे, तो इतना बड़ा अंतर संयोग से होना बहुत मुश्किल है। जाँचें कि लोगों को कौन-सा रूप कैसे मिला।",
    warn_peek: "आपके पास प्लानर के बताए लोगों ({n} हर रूप में) में से सिर्फ़ {x}% हैं। नतीजा अच्छा दिखते ही टेस्ट रोक देना \"झाँकना\" (peeking) कहलाता है, और इससे कई झूठी जीतें मिलती हैं। तय गिनती का इंतज़ार करें।",
    warn_peek_gen: "झाँकें नहीं: शुरू करने से पहले तय करें कि कितने लोग चाहिए (नीचे प्लानर), और उतने लोग पूरे होने पर ही नतीजा देखें।",
    chart_h: "असली दर शायद कहाँ है",
    chart_note: "हर वक्र किसी रूप की असली कन्वर्ज़न दर के भरोसेमंद मान दिखाता है। अगर वक्र बहुत ज़्यादा एक-दूसरे पर चढ़े हैं, तो टेस्ट अभी रूपों में फ़र्क़ नहीं बता सकता।",
    chart_aria: "हर रूप की संभावित असली कन्वर्ज़न दर के वक्र",
    axis_rate: "कन्वर्ज़न दर",
    plan_h: "सैंपल साइज़ प्लानर",
    plan_intro: "टेस्ट शुरू करने से पहले: हर रूप कितने लोगों को दिखाना चाहिए?",
    plan_base: "अभी की कन्वर्ज़न दर (%)",
    plan_use_a: "A की दर लें",
    plan_change: "सबसे छोटा बदलाव जो पकड़ना है",
    plan_abs: "प्रतिशत अंक",
    plan_rel: "अभी की दर का %",
    plan_power: "पावर (असली बदलाव पकड़ने की संभावना)",
    plan_sig: "सार्थकता स्तर",
    plan_versions: "टेस्ट में रूप",
    plan_daily: "रोज़ के लोग (सभी रूप मिलाकर)",
    plan_per: "हर रूप के लिए लोग",
    plan_total: "कुल लोग",
    plan_days: "कितने दिन लगेंगे",
    plan_days_val: "{n} दिन",
    plan_bad: "अभी की दर 0 और 100 के बीच भरें, और ऐसा बदलाव जिससे नई दर भी 0 और 100 के बीच रहे।",
    plan_target: "आप {a}% से {b}% का बदलाव पकड़ना चाहते हैं।",
    plan_3note: "3 रूपों में हर तुलना ज़्यादा सख़्त स्तर {a} इस्तेमाल करती है।",
    plan_formula: "सूत्र (दोनों तरफ़ का टेस्ट): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², जहाँ p̄ = (p1 + p2) ÷ 2। यहाँ z के मान {za} और {zb} हैं, तो n = {raw}, ऊपर की ओर पूरा करके {n}।",
    plan_note: "छोटे बदलाव के लिए बहुत ज़्यादा लोग चाहिए: आधा बदलाव पकड़ने के लिए लगभग 4 गुना लोग।",
    words_h: "ज़रूरी शब्द",
    w_conv: "कन्वर्ज़न",
    d_conv: "जो काम आप चाहते हैं: जवाब, ख़रीदारी, फ़ॉर्म भरना, फ़ीस जमा करना, क्लिक।",
    w_rate: "कन्वर्ज़न दर",
    d_rate: "कन्वर्ज़न ÷ देखने वाले लोग। 1,000 विज़िटर में 250 ख़रीदार = 25%।",
    w_uplift: "बढ़त",
    d_uplift: "20% से 25% होना 5 प्रतिशत अंक की बढ़त है, यानी 25% की तुलनात्मक बढ़त (5, 20 का एक-चौथाई है)।",
    w_p: "p-value",
    d_p: "अगर A और B सच में एक जैसे हों, तो सिर्फ़ किस्मत से इतना बड़ा अंतर कितनी बार आएगा? छोटा p-value (जैसे 0.01) मतलब किस्मत वाली बात मुश्किल है।",
    w_sig: "सार्थकता स्तर",
    d_sig: "p-value की सीमा जो आप टेस्ट से पहले चुनते हैं, आमतौर पर 5%। इससे कम हो तो नतीजा \"सार्थक\" कहलाता है।",
    w_ci: "भरोसे की सीमा",
    d_ci: "अंतर के वे मान जो डेटा से मेल खाते हैं। अगर इसमें 0 नहीं है, तो नतीजा सार्थक है।",
    w_power: "पावर",
    d_power: "यह संभावना कि आपका टेस्ट उतना असली बदलाव पकड़ ले जितना आपने सोचा था। आमतौर पर 80%।",
    w_bayes: "B के A से आगे होने की संभावना",
    d_bayes: "उसी डेटा को पढ़ने का दूसरा तरीका (बेज़ियन): कितनी संभावना है कि B की असली दर A से ज़्यादा है?",
    w_peek: "झाँकना (peeking)",
    d_peek: "बार-बार नतीजा देखना और सार्थक दिखते ही रोक देना। इससे झूठी जीतें बहुत बढ़ जाती हैं।",
    help_title: "कैसे इस्तेमाल करें / सुझाव",
    tip1: "कोई उदाहरण चुनें, या हर रूप के लोग और कन्वर्ज़न लिखें। लिखते ही नतीजा बदलता है।",
    tip2: "काम पर: WhatsApp ऑफ़र के दो रूप ग्राहक सूची के दो रैंडम आधे हिस्सों को भेजें और जवाब गिनें। पहले प्लानर से देखें कि सूची कितनी बड़ी होनी चाहिए।",
    tip3: "दुकान और वेबसाइट: बैनर A या B एक ही दिनों में रैंडम दिखाएँ (इस हफ़्ते A और अगले हफ़्ते B नहीं), और एक बार में एक ही चीज़ बदलें।",
    tip4: "कक्षा में: आधी कक्षा को होमवर्क रिमाइंडर A मिले, आधी को B। गिनें किसने समय पर जमा किया और जाँचें कि अंतर असली है या नहीं। फिर सिक्के उछालकर देखें कि सिर्फ़ किस्मत कितनी बार अंतर बना देती है।",
    tip5: "शुरू करने से पहले लोगों की गिनती और सार्थकता स्तर तय करें, और नतीजा अच्छा दिखने पर जल्दी न रोकें।",
    sum_row: "{v}: {r} ({n} में से {c})"
  },
  bn: {
    app_title: "A/B টেস্ট ক্যালকুলেটর",
    intro: "আপনি কোনো মেসেজ, ব্যানার বা নোটিশের দুটি রূপ চেষ্টা করেছেন। B কি সত্যিই A-র চেয়ে ভালো, নাকি এটা শুধু ভাগ্য? p-value, ভরসার সীমা, B জেতার সম্ভাবনা দেখুন, আর কতজন লোক লাগবে তা ঠিক করুন।",
    ex_label: "একটি উদাহরণ দেখুন:",
    ex_whatsapp: "দুটি WhatsApp মেসেজ",
    ex_banner: "দোকানের ব্যানার",
    ex_notice: "স্কুলের নোটিশ রিমাইন্ডার",
    ex_whatsapp_note: "একটি মিষ্টির দোকান 1,000 জন ক্রেতাকে অফার মেসেজ A আর অন্য 1,000 জনকে মেসেজ B পাঠিয়েছে। কনভার্শন = ক্রেতা অর্ডার দিতে উত্তর দিয়েছেন।",
    ex_banner_note: "একটি অনলাইন শাড়ির দোকান দর্শকদের এলোমেলোভাবে ব্যানার A বা B দেখিয়েছে। কনভার্শন = দর্শক কিছু কিনেছেন।",
    ex_notice_note: "অভিভাবকরা ফি রিমাইন্ডার A (সাধারণ), B (শেষ তারিখ মোটা অক্ষরে) বা C (দুবার পাঠানো) পেয়েছেন। কনভার্শন = সময়মতো ফি জমা হয়েছে।",
    data_h: "আপনার টেস্টের ফলাফল",
    col_version: "রূপ",
    col_visitors: "দর্শক (যাঁরা দেখেছেন)",
    col_conv: "কনভার্শন (যাঁরা কাজটি করেছেন)",
    col_rate: "কনভার্শন হার",
    ver_a: "বর্তমান রূপ",
    ver_b: "নতুন রূপ",
    ver_c: "আরেকটি নতুন রূপ",
    add_c: "+ রূপ C যোগ করুন",
    remove_c: "রূপ C সরান",
    sig_label: "তাৎপর্যের মাত্রা",
    sig_5: "5% (সাধারণ)",
    sig_1: "1% (কড়া)",
    err_blank: "প্রতিটি রূপের দর্শক আর কনভার্শন লিখুন।",
    err_bad: "1000-এর মতো পূর্ণ সংখ্যা লিখুন (দশমিক বা মাইনাস নয়)।",
    err_zero: "রূপ {v}: দর্শক অন্তত 1 হতে হবে।",
    err_more: "রূপ {v}: কনভার্শন ({c}) দর্শকের ({n}) চেয়ে বেশি হতে পারে না।",
    copy_result: "ফলাফল কপি করুন",
    res_h: "ফলাফল",
    res_wait: "ফলাফল দেখতে সংখ্যাগুলি লিখুন।",
    three_note: "3টি রূপে B আর C দুটিকেই A-র সঙ্গে তুলনা করা হয়। ভুল জয় কম রাখতে প্রতিটি তুলনাকে আরও কড়া মাত্রা পার হতে হবে: {a}।",
    cmp_h: "A-র সঙ্গে {v}-এর তুলনা",
    verdict_better: "{v} ভালো, আর এটা ভাগ্যের ফল হওয়ার সম্ভাবনা কম।",
    verdict_worse: "{v} A-র চেয়ে খারাপ, আর এটা ভাগ্যের ফল হওয়ার সম্ভাবনা কম।",
    verdict_unsure: "এখনও যথেষ্ট প্রমাণ নেই। পার্থক্যটা শুধু ভাগ্যও হতে পারে।",
    verdict_sig_sub: "p-value {p}, যা {a}-এর কম।",
    verdict_unsure_sub: "p-value {p}, যা {a}-এর কম নয়। পরিকল্পিত সংখ্যক লোক না হওয়া পর্যন্ত টেস্ট চালিয়ে যান।",
    st_diff: "পার্থক্য ({v} − A)",
    pts_unit: "শতাংশ বিন্দু",
    st_uplift: "আপেক্ষিক বৃদ্ধি",
    st_p: "p-value",
    p_need: "{a}-এর কম হলে তাৎপর্যপূর্ণ",
    st_ci: "পার্থক্যের {c}% ভরসার সীমা",
    st_ci_val: "{lo} থেকে {hi}",
    st_beat: "{v}-এর A-কে হারানোর সম্ভাবনা",
    st_beat_sub: "বেইজিয়ান অনুমান",
    ci_note_pos: "পুরো সীমাটাই 0-র ওপরে, তাই {v} প্রায় নিশ্চিতভাবে ভালো।",
    ci_note_neg: "পুরো সীমাটাই 0-র নিচে, তাই {v} প্রায় নিশ্চিতভাবে খারাপ।",
    ci_note_zero: "সীমার মধ্যে 0 আছে, তাই \"আসল কোনো পার্থক্য নেই\" এখনও সম্ভব।",
    work_h: "হিসাব দেখুন (z-টেস্ট)",
    work_pool: "A আর {v}-এর মিলিত হার: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "স্ট্যান্ডার্ড এরর (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = পার্থক্য ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = আসল পার্থক্য না থাকলে z-এর 0 থেকে এতটা দূরে (যেকোনো দিকে) আসার সম্ভাবনা = {p}",
    work_ci: "ভরসার সীমা = পার্থক্য ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "সেরা হওয়ার সম্ভাবনা",
    warn_small: "খুব ছোট নমুনা: রূপ {v}-এ 10-এর কম কনভার্শন বা 10-এর কম না-কনভার্শন। ফলাফল অনেক ওঠানামা করতে পারে। আরও ডেটা সংগ্রহ করুন।",
    warn_split: "ভাগ সমান নয়: {s}। আপনি যদি সমানভাবে ভাগ করতে চেয়ে থাকেন, তাহলে এত বড় ফারাক কাকতালীয় হওয়া খুবই কঠিন। দেখুন কে কোন রূপ কীভাবে পেয়েছেন।",
    warn_peek: "প্ল্যানার যত লোক বলছে ({n} প্রতি রূপে), আপনার কাছে তার মাত্র {x}% আছে। ফল ভালো দেখালেই টেস্ট থামানোকে \"উঁকি দেওয়া\" (peeking) বলে, এতে অনেক ভুল জয় আসে। পরিকল্পিত সংখ্যার জন্য অপেক্ষা করুন।",
    warn_peek_gen: "উঁকি দেবেন না: শুরুর আগে ঠিক করুন কতজন লাগবে (নিচের প্ল্যানার), আর সেই সংখ্যা পূর্ণ হলে তবেই ফলাফল বিচার করুন।",
    chart_h: "আসল হার সম্ভবত কোথায়",
    chart_note: "প্রতিটি বক্ররেখা একটি রূপের আসল কনভার্শন হারের বিশ্বাসযোগ্য মান দেখায়। রেখাগুলি অনেকটা একে অন্যের ওপর পড়লে টেস্ট এখনও রূপগুলির পার্থক্য বলতে পারে না।",
    chart_aria: "প্রতিটি রূপের সম্ভাব্য আসল কনভার্শন হারের বক্ররেখা",
    axis_rate: "কনভার্শন হার",
    plan_h: "নমুনার আকার পরিকল্পনা",
    plan_intro: "টেস্ট শুরুর আগে: প্রতিটি রূপ কতজনকে দেখাতে হবে?",
    plan_base: "এখনকার কনভার্শন হার (%)",
    plan_use_a: "A-র হার নিন",
    plan_change: "ধরতে চাওয়া সবচেয়ে ছোট পরিবর্তন",
    plan_abs: "শতাংশ বিন্দু",
    plan_rel: "এখনকার হারের %",
    plan_power: "পাওয়ার (আসল পরিবর্তন ধরার সম্ভাবনা)",
    plan_sig: "তাৎপর্যের মাত্রা",
    plan_versions: "টেস্টে কটি রূপ",
    plan_daily: "দিনে কতজন (সব রূপ মিলিয়ে)",
    plan_per: "প্রতি রূপে লোক",
    plan_total: "মোট লোক",
    plan_days: "কত দিন লাগবে",
    plan_days_val: "{n} দিন",
    plan_bad: "এখনকার হার 0 থেকে 100-এর মধ্যে লিখুন, আর এমন পরিবর্তন দিন যাতে নতুন হারও 0 থেকে 100-এর মধ্যে থাকে।",
    plan_target: "আপনি {a}% থেকে {b}%-এর পরিবর্তন ধরতে চান।",
    plan_3note: "3টি রূপে প্রতিটি তুলনা আরও কড়া মাত্রা {a} ব্যবহার করে।",
    plan_formula: "সূত্র (দুই-দিকের টেস্ট): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², যেখানে p̄ = (p1 + p2) ÷ 2। এখানে z-এর মান {za} আর {zb}, তাই n = {raw}, ওপরের দিকে পূর্ণ করে {n}।",
    plan_note: "ছোট পরিবর্তন ধরতে অনেক বেশি লোক লাগে: অর্ধেক পরিবর্তন ধরতে প্রায় 4 গুণ লোক।",
    words_h: "জানার মতো শব্দ",
    w_conv: "কনভার্শন",
    d_conv: "যে কাজটি আপনি চান: উত্তর, কেনাকাটা, ফর্ম পূরণ, ফি জমা, ক্লিক।",
    w_rate: "কনভার্শন হার",
    d_rate: "কনভার্শন ÷ যাঁরা দেখেছেন। 1,000 দর্শকের মধ্যে 250 জন ক্রেতা = 25%।",
    w_uplift: "বৃদ্ধি",
    d_uplift: "20% থেকে 25% মানে 5 শতাংশ বিন্দু বৃদ্ধি, অর্থাৎ 25% আপেক্ষিক বৃদ্ধি (5 হল 20-এর এক-চতুর্থাংশ)।",
    w_p: "p-value",
    d_p: "A আর B সত্যিই একই হলে শুধু ভাগ্যের জোরে এত বড় পার্থক্য কতবার আসবে? ছোট p-value (যেমন 0.01) মানে ভাগ্যের ব্যাখ্যা অসম্ভাব্য।",
    w_sig: "তাৎপর্যের মাত্রা",
    d_sig: "টেস্টের আগে বেছে নেওয়া p-value-এর সীমা, সাধারণত 5%। এর নিচে হলে ফলাফলকে \"তাৎপর্যপূর্ণ\" বলি।",
    w_ci: "ভরসার সীমা",
    d_ci: "পার্থক্যের যে মানগুলি ডেটার সঙ্গে মেলে। এতে 0 না থাকলে ফলাফল তাৎপর্যপূর্ণ।",
    w_power: "পাওয়ার",
    d_power: "আপনার পরিকল্পিত মাপের আসল পরিবর্তন টেস্ট ধরতে পারার সম্ভাবনা। সাধারণত 80%।",
    w_bayes: "B-র A-কে হারানোর সম্ভাবনা",
    d_bayes: "একই ডেটা পড়ার আরেকটি উপায় (বেইজিয়ান): B-র আসল হার A-র চেয়ে বেশি হওয়ার সম্ভাবনা কত?",
    w_peek: "উঁকি দেওয়া (peeking)",
    d_peek: "বারবার ফল দেখা আর তাৎপর্যপূর্ণ দেখালেই থামিয়ে দেওয়া। এতে ভুল জয় অনেক বেড়ে যায়।",
    help_title: "কীভাবে ব্যবহার করবেন / কিছু ভাবনা",
    tip1: "একটি উদাহরণ বাছুন, বা প্রতিটি রূপের লোক আর কনভার্শন লিখুন। লেখার সঙ্গে সঙ্গে ফলাফল বদলায়।",
    tip2: "কাজে: WhatsApp অফারের দুটি রূপ ক্রেতা তালিকার এলোমেলো দুই অর্ধেককে পাঠান আর উত্তর গুনুন। আগে প্ল্যানারে দেখে নিন তালিকা কত বড় হওয়া দরকার।",
    tip3: "দোকান আর ওয়েবসাইট: একই দিনগুলিতে এলোমেলোভাবে ব্যানার A বা B দেখান (এই সপ্তাহে A, পরের সপ্তাহে B নয়), আর একবারে একটাই জিনিস বদলান।",
    tip4: "ক্লাসে: অর্ধেক ক্লাস হোমওয়ার্ক রিমাইন্ডার A পাবে, অর্ধেক B। কে সময়মতো জমা দিল গুনুন আর পার্থক্যটা আসল কিনা পরীক্ষা করুন। তারপর কয়েন ছুড়ে দেখুন শুধু ভাগ্য কতবার পার্থক্য তৈরি করে।",
    tip5: "শুরুর আগেই লোকের সংখ্যা আর তাৎপর্যের মাত্রা ঠিক করুন, আর ফল ভালো দেখালেই তাড়াতাড়ি থামাবেন না।",
    sum_row: "{v}: {r} ({n} জনের মধ্যে {c})"
  },
  mr: {
    app_title: "A/B टेस्ट कॅल्क्युलेटर",
    intro: "तुम्ही एखाद्या मेसेज, बॅनर किंवा सूचनेची दोन रूपे वापरून पाहिली. B खरंच A पेक्षा चांगले ठरले, की हे फक्त नशीब होते? p-value, खात्रीची मर्यादा, B जिंकण्याची शक्यता पाहा आणि किती लोक लागतील ते ठरवा.",
    ex_label: "एखादे उदाहरण पाहा:",
    ex_whatsapp: "दोन WhatsApp मेसेज",
    ex_banner: "दुकानाचे बॅनर",
    ex_notice: "शाळेच्या सूचनेची आठवण",
    ex_whatsapp_note: "एका मिठाईच्या दुकानाने 1,000 ग्राहकांना ऑफर मेसेज A आणि दुसऱ्या 1,000 जणांना मेसेज B पाठवला. कन्व्हर्जन = ग्राहकाने ऑर्डरसाठी उत्तर दिले.",
    ex_banner_note: "एका ऑनलाइन साडी दुकानाने येणाऱ्यांना कोणताही क्रम न ठेवता (रँडम) बॅनर A किंवा B दाखवले. कन्व्हर्जन = येणाऱ्याने काहीतरी खरेदी केले.",
    ex_notice_note: "पालकांना फी आठवण A (साधी), B (शेवटची तारीख ठळक) किंवा C (दोनदा पाठवलेली) मिळाली. कन्व्हर्जन = फी वेळेवर भरली.",
    data_h: "तुमच्या टेस्टचे निकाल",
    col_version: "रूप",
    col_visitors: "व्हिजिटर (ज्यांनी पाहिले)",
    col_conv: "कन्व्हर्जन (ज्यांनी कृती केली)",
    col_rate: "कन्व्हर्जन दर",
    ver_a: "सध्याचे रूप",
    ver_b: "नवे रूप",
    ver_c: "आणखी एक नवे रूप",
    add_c: "+ रूप C जोडा",
    remove_c: "रूप C काढा",
    sig_label: "सार्थकता पातळी",
    sig_5: "5% (नेहमीची)",
    sig_1: "1% (कडक)",
    err_blank: "प्रत्येक रूपासाठी व्हिजिटर आणि कन्व्हर्जन भरा.",
    err_bad: "1000 सारखी पूर्ण संख्या लिहा (दशांश किंवा उणे चिन्ह नको).",
    err_zero: "रूप {v}: व्हिजिटर किमान 1 असायला हवेत.",
    err_more: "रूप {v}: कन्व्हर्जन ({c}) व्हिजिटरपेक्षा ({n}) जास्त असू शकत नाहीत.",
    copy_result: "निकाल कॉपी करा",
    res_h: "निकाल",
    res_wait: "निकाल पाहण्यासाठी संख्या भरा.",
    three_note: "3 रूपांमध्ये B आणि C दोघांची तुलना A शी होते. खोटे विजय कमी राहावेत म्हणून प्रत्येक तुलनेला जास्त कडक पातळी पार करावी लागते: {a}.",
    cmp_h: "{v} ची A शी तुलना",
    verdict_better: "{v} चांगले आहे, आणि हे नशिबामुळे असण्याची शक्यता कमी आहे.",
    verdict_worse: "{v} हे A पेक्षा वाईट आहे, आणि हे नशिबामुळे असण्याची शक्यता कमी आहे.",
    verdict_unsure: "अजून पुरेसा पुरावा नाही. हा फरक फक्त नशिबाचाही असू शकतो.",
    verdict_sig_sub: "p-value {p} आहे, जे {a} पेक्षा कमी आहे.",
    verdict_unsure_sub: "p-value {p} आहे, जे {a} पेक्षा कमी नाही. ठरवलेले लोक पूर्ण होईपर्यंत टेस्ट चालू ठेवा.",
    st_diff: "फरक ({v} − A)",
    pts_unit: "टक्के गुण",
    st_uplift: "सापेक्ष वाढ",
    st_p: "p-value",
    p_need: "{a} पेक्षा कमी असेल तर सार्थक",
    st_ci: "फरकाची {c}% खात्रीची मर्यादा",
    st_ci_val: "{lo} ते {hi}",
    st_beat: "{v} ने A ला मागे टाकण्याची शक्यता",
    st_beat_sub: "बेझियन अंदाज",
    ci_note_pos: "संपूर्ण मर्यादा 0 च्या वर आहे, म्हणून {v} जवळजवळ नक्की चांगले आहे.",
    ci_note_neg: "संपूर्ण मर्यादा 0 च्या खाली आहे, म्हणून {v} जवळजवळ नक्की वाईट आहे.",
    ci_note_zero: "मर्यादेत 0 येतो, म्हणून \"खरा फरक नाही\" हेही शक्य आहे.",
    work_h: "गणित पाहा (z-टेस्ट)",
    work_pool: "A आणि {v} चा एकत्रित दर: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "प्रमाण त्रुटी (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = फरक ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = खरा फरक नसताना z हे 0 पासून इतके दूर (कोणत्याही बाजूला) येण्याची शक्यता = {p}",
    work_ci: "खात्रीची मर्यादा = फरक ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "सर्वोत्तम असण्याची शक्यता",
    warn_small: "खूप लहान नमुना: रूप {v} मध्ये 10 पेक्षा कमी कन्व्हर्जन किंवा 10 पेक्षा कमी बिन-कन्व्हर्जन आहेत. निकाल खूप बदलू शकतात. आणखी डेटा गोळा करा.",
    warn_split: "वाटणी समान नाही: {s}. तुम्हाला लोक समान वाटायचे होते, तर इतका मोठा फरक योगायोगाने होणे फारच कठीण आहे. कोणाला कोणते रूप कसे मिळाले ते तपासा.",
    warn_peek: "प्लॅनरने सांगितलेल्या लोकांपैकी ({n} प्रत्येक रूपात) तुमच्याकडे फक्त {x}% आहेत. निकाल चांगला दिसताच टेस्ट थांबवणे याला \"डोकावणे\" (peeking) म्हणतात, आणि त्यामुळे अनेक खोटे विजय मिळतात. ठरवलेल्या संख्येची वाट पाहा.",
    warn_peek_gen: "डोकावू नका: सुरू करण्यापूर्वी किती लोक लागतील ते ठरवा (खालील प्लॅनर), आणि तेवढे लोक पूर्ण झाल्यावरच निकाल ठरवा.",
    chart_h: "खरा दर बहुधा कुठे आहे",
    chart_note: "प्रत्येक वक्र एखाद्या रूपाच्या खऱ्या कन्व्हर्जन दराच्या विश्वासार्ह किमती दाखवतो. वक्र एकमेकांवर खूप येत असतील तर टेस्ट अजून रूपांमधला फरक सांगू शकत नाही.",
    chart_aria: "प्रत्येक रूपाच्या संभाव्य खऱ्या कन्व्हर्जन दराचे वक्र",
    axis_rate: "कन्व्हर्जन दर",
    plan_h: "नमुना आकार प्लॅनर",
    plan_intro: "टेस्ट सुरू करण्यापूर्वी: प्रत्येक रूप किती लोकांना दाखवायला हवे?",
    plan_base: "सध्याचा कन्व्हर्जन दर (%)",
    plan_use_a: "A चा दर घ्या",
    plan_change: "शोधायचा सर्वात लहान बदल",
    plan_abs: "टक्के गुण",
    plan_rel: "सध्याच्या दराचे %",
    plan_power: "पॉवर (खरा बदल पकडण्याची शक्यता)",
    plan_sig: "सार्थकता पातळी",
    plan_versions: "टेस्टमधील रूपे",
    plan_daily: "दररोजचे लोक (सर्व रूपे मिळून)",
    plan_per: "प्रत्येक रूपासाठी लोक",
    plan_total: "एकूण लोक",
    plan_days: "किती दिवस लागतील",
    plan_days_val: "{n} दिवस",
    plan_bad: "सध्याचा दर 0 ते 100 दरम्यान भरा, आणि असा बदल द्या की नवा दरही 0 ते 100 दरम्यान राहील.",
    plan_target: "तुम्हाला {a}% पासून {b}% पर्यंतचा बदल शोधायचा आहे.",
    plan_3note: "3 रूपांमध्ये प्रत्येक तुलना जास्त कडक पातळी {a} वापरते.",
    plan_formula: "सूत्र (दोन्ही बाजूंची टेस्ट): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², जिथे p̄ = (p1 + p2) ÷ 2. इथे z च्या किमती {za} आणि {zb} आहेत, म्हणून n = {raw}, वरच्या पूर्ण संख्येत {n}.",
    plan_note: "लहान बदलासाठी खूप जास्त लोक लागतात: अर्धा बदल शोधायला सुमारे 4 पट लोक.",
    words_h: "महत्त्वाचे शब्द",
    w_conv: "कन्व्हर्जन",
    d_conv: "तुम्हाला हवी असलेली कृती: उत्तर, खरेदी, फॉर्म भरणे, फी भरणे, क्लिक.",
    w_rate: "कन्व्हर्जन दर",
    d_rate: "कन्व्हर्जन ÷ पाहणारे लोक. 1,000 व्हिजिटरपैकी 250 खरेदीदार = 25%.",
    w_uplift: "वाढ",
    d_uplift: "20% वरून 25% म्हणजे 5 टक्के गुणांची वाढ, म्हणजेच 25% सापेक्ष वाढ (5 हा 20 चा एक-चतुर्थांश आहे).",
    w_p: "p-value",
    d_p: "A आणि B खरंच सारखे असते, तर फक्त नशिबाने इतका मोठा फरक किती वेळा येईल? लहान p-value (उदा. 0.01) म्हणजे नशिबाचे कारण संभवत नाही.",
    w_sig: "सार्थकता पातळी",
    d_sig: "टेस्टच्या आधी ठरवलेली p-value ची मर्यादा, सहसा 5%. त्याखाली असेल तर निकाल \"सार्थक\" म्हणतात.",
    w_ci: "खात्रीची मर्यादा",
    d_ci: "डेटाशी जुळणाऱ्या फरकांची मर्यादा. त्यात 0 नसेल तर निकाल सार्थक आहे.",
    w_power: "पॉवर",
    d_power: "तुम्ही ठरवलेल्या आकाराचा खरा बदल टेस्ट पकडेल याची शक्यता. सहसा 80%.",
    w_bayes: "B ने A ला मागे टाकण्याची शक्यता",
    d_bayes: "तोच डेटा वाचण्याची दुसरी पद्धत (बेझियन): B चा खरा दर A पेक्षा जास्त असण्याची शक्यता किती?",
    w_peek: "डोकावणे (peeking)",
    d_peek: "पुन्हा पुन्हा निकाल पाहणे आणि सार्थक दिसताच थांबवणे. त्यामुळे खोटे विजय खूप वाढतात.",
    help_title: "कसे वापरावे / कल्पना",
    tip1: "एखादे उदाहरण निवडा, किंवा प्रत्येक रूपाचे लोक आणि कन्व्हर्जन लिहा. लिहिताच निकाल बदलतो.",
    tip2: "कामावर: WhatsApp ऑफरची दोन रूपे ग्राहक यादीच्या रँडम दोन अर्ध्या भागांना पाठवा आणि उत्तरे मोजा. आधी प्लॅनरमध्ये यादी किती मोठी हवी ते पाहा.",
    tip3: "दुकान आणि वेबसाइट: त्याच दिवसांत बॅनर A किंवा B रँडम दाखवा (या आठवड्यात A आणि पुढच्या आठवड्यात B नाही), आणि एका वेळी एकच गोष्ट बदला.",
    tip4: "वर्गात: अर्ध्या वर्गाला गृहपाठाची आठवण A, अर्ध्याला B. वेळेवर कोणी जमा केले ते मोजा आणि फरक खरा आहे का ते तपासा. मग नाणी उडवून पाहा की फक्त नशीब किती वेळा फरक घडवते.",
    tip5: "सुरू करण्यापूर्वी लोकांची संख्या आणि सार्थकता पातळी ठरवा, आणि निकाल चांगला दिसला म्हणून लवकर थांबू नका.",
    sum_row: "{v}: {r} ({n} पैकी {c})"
  },
  gu: {
    app_title: "A/B ટેસ્ટ કેલ્ક્યુલેટર",
    intro: "તમે કોઈ મેસેજ, બેનર કે સૂચનાનાં બે રૂપ અજમાવ્યાં. શું B ખરેખર A કરતાં સારું રહ્યું, કે આ ફક્ત નસીબ હતું? p-value, ભરોસાની મર્યાદા, B જીતવાની શક્યતા જુઓ અને કેટલા લોકો જોઈએ તે નક્કી કરો.",
    ex_label: "ઉદાહરણ અજમાવો:",
    ex_whatsapp: "બે WhatsApp મેસેજ",
    ex_banner: "દુકાનનું બેનર",
    ex_notice: "શાળા સૂચના રિમાઇન્ડર",
    ex_whatsapp_note: "એક મીઠાઈની દુકાને 1,000 ગ્રાહકોને ઑફર મેસેજ A અને બીજા 1,000ને મેસેજ B મોકલ્યો. કન્વર્ઝન = ગ્રાહકે ઑર્ડર માટે જવાબ આપ્યો.",
    ex_banner_note: "એક ઑનલાઇન સાડીની દુકાને મુલાકાતીઓને રેન્ડમ રીતે બેનર A કે B બતાવ્યું. કન્વર્ઝન = મુલાકાતીએ કંઈક ખરીદ્યું.",
    ex_notice_note: "વાલીઓને ફી રિમાઇન્ડર A (સાદું), B (છેલ્લી તારીખ ઘાટા અક્ષરે) કે C (બે વાર મોકલેલું) મળ્યું. કન્વર્ઝન = ફી સમયસર ભરાઈ.",
    data_h: "તમારા ટેસ્ટનાં પરિણામ",
    col_version: "રૂપ",
    col_visitors: "મુલાકાતી (જેમણે જોયું)",
    col_conv: "કન્વર્ઝન (જેમણે કામ કર્યું)",
    col_rate: "કન્વર્ઝન દર",
    ver_a: "હાલનું રૂપ",
    ver_b: "નવું રૂપ",
    ver_c: "બીજું એક નવું રૂપ",
    add_c: "+ રૂપ C ઉમેરો",
    remove_c: "રૂપ C કાઢો",
    sig_label: "સાર્થકતા સ્તર",
    sig_5: "5% (સામાન્ય)",
    sig_1: "1% (કડક)",
    err_blank: "દરેક રૂપ માટે મુલાકાતી અને કન્વર્ઝન ભરો.",
    err_bad: "1000 જેવી પૂર્ણ સંખ્યા લખો (દશાંશ કે માઇનસ નહીં).",
    err_zero: "રૂપ {v}: મુલાકાતી ઓછામાં ઓછા 1 હોવા જોઈએ.",
    err_more: "રૂપ {v}: કન્વર્ઝન ({c}) મુલાકાતી ({n}) કરતાં વધુ ન હોઈ શકે.",
    copy_result: "પરિણામ કૉપી કરો",
    res_h: "પરિણામ",
    res_wait: "પરિણામ જોવા સંખ્યાઓ ભરો.",
    three_note: "3 રૂપમાં B અને C બંનેની સરખામણી A સાથે થાય છે. ખોટી જીત ઓછી રહે તે માટે દરેક સરખામણીએ વધુ કડક સ્તર પાર કરવું પડે: {a}.",
    cmp_h: "{v}ની A સાથે સરખામણી",
    verdict_better: "{v} વધુ સારું છે, અને આ નસીબ હોવાની શક્યતા ઓછી છે.",
    verdict_worse: "{v} A કરતાં ખરાબ છે, અને આ નસીબ હોવાની શક્યતા ઓછી છે.",
    verdict_unsure: "હજી પૂરતો પુરાવો નથી. આ તફાવત ફક્ત નસીબ પણ હોઈ શકે.",
    verdict_sig_sub: "p-value {p} છે, જે {a}થી ઓછું છે.",
    verdict_unsure_sub: "p-value {p} છે, જે {a}થી ઓછું નથી. નક્કી કરેલા લોકો પૂરા થાય ત્યાં સુધી ટેસ્ટ ચાલુ રાખો.",
    st_diff: "તફાવત ({v} − A)",
    pts_unit: "ટકા પોઇન્ટ",
    st_uplift: "સાપેક્ષ વધારો",
    st_p: "p-value",
    p_need: "{a}થી ઓછું હોય તો સાર્થક",
    st_ci: "તફાવતની {c}% ભરોસાની મર્યાદા",
    st_ci_val: "{lo}થી {hi}",
    st_beat: "{v} A કરતાં આગળ હોવાની શક્યતા",
    st_beat_sub: "બેયેસિયન અંદાજ",
    ci_note_pos: "આખી મર્યાદા 0થી ઉપર છે, એટલે {v} લગભગ ચોક્કસ સારું છે.",
    ci_note_neg: "આખી મર્યાદા 0થી નીચે છે, એટલે {v} લગભગ ચોક્કસ ખરાબ છે.",
    ci_note_zero: "મર્યાદામાં 0 આવે છે, એટલે \"કોઈ સાચો તફાવત નથી\" એ પણ શક્ય છે.",
    work_h: "ગણતરી જુઓ (z-ટેસ્ટ)",
    work_pool: "A અને {v}નો સંયુક્ત દર: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "પ્રમાણભૂત ભૂલ (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = તફાવત ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = સાચો તફાવત ન હોય તો z ના 0થી આટલું દૂર (કોઈ પણ બાજુ) આવવાની શક્યતા = {p}",
    work_ci: "ભરોસાની મર્યાદા = તફાવત ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "શ્રેષ્ઠ હોવાની શક્યતા",
    warn_small: "ખૂબ નાનો નમૂનો: રૂપ {v}માં 10થી ઓછાં કન્વર્ઝન કે 10થી ઓછાં બિન-કન્વર્ઝન છે. પરિણામ ઘણું બદલાઈ શકે. વધુ ડેટા ભેગો કરો.",
    warn_split: "વહેંચણી સરખી નથી: {s}. જો તમે લોકોને સરખા વહેંચવા માગતા હતા, તો આટલો મોટો ફરક સંયોગથી થવો બહુ મુશ્કેલ છે. કોને કયું રૂપ કેવી રીતે મળ્યું તે તપાસો.",
    warn_peek: "પ્લાનરે કહેલા લોકો ({n} દરેક રૂપમાં)માંથી તમારી પાસે ફક્ત {x}% છે. પરિણામ સારું દેખાય કે તરત ટેસ્ટ બંધ કરવું એને \"ડોકિયું\" (peeking) કહે છે, અને તેનાથી ઘણી ખોટી જીત મળે છે. નક્કી કરેલી સંખ્યાની રાહ જુઓ.",
    warn_peek_gen: "ડોકિયું ન કરો: શરૂ કરતાં પહેલાં નક્કી કરો કે કેટલા લોકો જોઈએ (નીચે પ્લાનર), અને એટલા લોકો પૂરા થાય પછી જ પરિણામ જુઓ.",
    chart_h: "સાચો દર કદાચ ક્યાં છે",
    chart_note: "દરેક વક્ર કોઈ રૂપના સાચા કન્વર્ઝન દરની ભરોસાપાત્ર કિંમતો બતાવે છે. વક્રો એકબીજા પર બહુ ચડે તો ટેસ્ટ હજી રૂપો વચ્ચેનો ફરક કહી શકતો નથી.",
    chart_aria: "દરેક રૂપના સંભવિત સાચા કન્વર્ઝન દરના વક્ર",
    axis_rate: "કન્વર્ઝન દર",
    plan_h: "નમૂના કદ પ્લાનર",
    plan_intro: "ટેસ્ટ શરૂ કરતાં પહેલાં: દરેક રૂપ કેટલા લોકોને બતાવવું જોઈએ?",
    plan_base: "હાલનો કન્વર્ઝન દર (%)",
    plan_use_a: "A નો દર લો",
    plan_change: "શોધવા જેવો સૌથી નાનો ફેરફાર",
    plan_abs: "ટકા પોઇન્ટ",
    plan_rel: "હાલના દરના %",
    plan_power: "પાવર (સાચો ફેરફાર પકડવાની શક્યતા)",
    plan_sig: "સાર્થકતા સ્તર",
    plan_versions: "ટેસ્ટમાં રૂપ",
    plan_daily: "રોજના લોકો (બધાં રૂપ મળીને)",
    plan_per: "દરેક રૂપ માટે લોકો",
    plan_total: "કુલ લોકો",
    plan_days: "કેટલા દિવસ લાગશે",
    plan_days_val: "{n} દિવસ",
    plan_bad: "હાલનો દર 0 અને 100 વચ્ચે ભરો, અને એવો ફેરફાર આપો કે નવો દર પણ 0 અને 100 વચ્ચે રહે.",
    plan_target: "તમે {a}%થી {b}% સુધીનો ફેરફાર શોધવા માગો છો.",
    plan_3note: "3 રૂપમાં દરેક સરખામણી વધુ કડક સ્તર {a} વાપરે છે.",
    plan_formula: "સૂત્ર (બંને બાજુનો ટેસ્ટ): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², જ્યાં p̄ = (p1 + p2) ÷ 2. અહીં z ની કિંમતો {za} અને {zb} છે, એટલે n = {raw}, ઉપરની પૂર્ણ સંખ્યામાં {n}.",
    plan_note: "નાના ફેરફાર માટે ઘણા વધુ લોકો જોઈએ: અડધો ફેરફાર શોધવા લગભગ 4 ગણા લોકો.",
    words_h: "જાણવા જેવા શબ્દો",
    w_conv: "કન્વર્ઝન",
    d_conv: "તમે ઇચ્છો તે કામ: જવાબ, ખરીદી, ફોર્મ ભરવું, ફી ભરવી, ક્લિક.",
    w_rate: "કન્વર્ઝન દર",
    d_rate: "કન્વર્ઝન ÷ જોનારા લોકો. 1,000 મુલાકાતીમાંથી 250 ખરીદનાર = 25%.",
    w_uplift: "વધારો",
    d_uplift: "20%થી 25% એટલે 5 ટકા પોઇન્ટનો વધારો, એટલે કે 25% સાપેક્ષ વધારો (5 એ 20નો ચોથો ભાગ છે).",
    w_p: "p-value",
    d_p: "જો A અને B ખરેખર સરખાં હોય, તો ફક્ત નસીબથી આટલો મોટો તફાવત કેટલી વાર આવે? નાનું p-value (જેમ કે 0.01) એટલે નસીબવાળી વાત મુશ્કેલ છે.",
    w_sig: "સાર્થકતા સ્તર",
    d_sig: "ટેસ્ટ પહેલાં પસંદ કરેલી p-value ની મર્યાદા, સામાન્ય રીતે 5%. એનાથી નીચે હોય તો પરિણામ \"સાર્થક\" કહેવાય.",
    w_ci: "ભરોસાની મર્યાદા",
    d_ci: "ડેટા સાથે મેળ ખાતા તફાવતોની મર્યાદા. એમાં 0 ન હોય તો પરિણામ સાર્થક છે.",
    w_power: "પાવર",
    d_power: "તમે ધાર્યા જેટલો સાચો ફેરફાર ટેસ્ટ પકડી લે તેની શક્યતા. સામાન્ય રીતે 80%.",
    w_bayes: "B ના A કરતાં આગળ હોવાની શક્યતા",
    d_bayes: "એ જ ડેટા વાંચવાની બીજી રીત (બેયેસિયન): B નો સાચો દર A કરતાં વધુ હોવાની શક્યતા કેટલી?",
    w_peek: "ડોકિયું (peeking)",
    d_peek: "વારંવાર પરિણામ જોવું અને સાર્થક દેખાય કે તરત બંધ કરવું. એનાથી ખોટી જીત ઘણી વધી જાય છે.",
    help_title: "કેવી રીતે વાપરવું / સૂચનો",
    tip1: "કોઈ ઉદાહરણ પસંદ કરો, અથવા દરેક રૂપના લોકો અને કન્વર્ઝન લખો. લખતાં જ પરિણામ બદલાય છે.",
    tip2: "કામ પર: WhatsApp ઑફરનાં બે રૂપ ગ્રાહક યાદીના રેન્ડમ બે અડધા ભાગને મોકલો અને જવાબ ગણો. પહેલાં પ્લાનરમાં જુઓ કે યાદી કેટલી મોટી હોવી જોઈએ.",
    tip3: "દુકાન અને વેબસાઇટ: એ જ દિવસોમાં બેનર A કે B રેન્ડમ બતાવો (આ અઠવાડિયે A અને આવતા અઠવાડિયે B નહીં), અને એક વખતે એક જ વસ્તુ બદલો.",
    tip4: "વર્ગમાં: અડધા વર્ગને ગૃહકાર્યનું રિમાઇન્ડર A, અડધાને B. કોણે સમયસર જમા કર્યું તે ગણો અને તફાવત સાચો છે કે નહીં તે તપાસો. પછી સિક્કા ઉછાળીને જુઓ કે ફક્ત નસીબ કેટલી વાર તફાવત ઊભો કરે છે.",
    tip5: "શરૂ કરતાં પહેલાં લોકોની સંખ્યા અને સાર્થકતા સ્તર નક્કી કરો, અને પરિણામ સારું દેખાય એટલે વહેલું બંધ ન કરો.",
    sum_row: "{v}: {r} ({n}માંથી {c})"
  },
  pa: {
    app_title: "A/B ਟੈਸਟ ਕੈਲਕੁਲੇਟਰ",
    intro: "ਤੁਸੀਂ ਕਿਸੇ ਮੈਸੇਜ, ਬੈਨਰ ਜਾਂ ਸੂਚਨਾ ਦੇ ਦੋ ਰੂਪ ਅਜ਼ਮਾਏ। ਕੀ B ਸੱਚਮੁੱਚ A ਤੋਂ ਵਧੀਆ ਰਿਹਾ, ਜਾਂ ਇਹ ਸਿਰਫ਼ ਕਿਸਮਤ ਸੀ? p-value, ਭਰੋਸੇ ਦੀ ਸੀਮਾ, B ਦੇ ਜਿੱਤਣ ਦੀ ਸੰਭਾਵਨਾ ਵੇਖੋ, ਅਤੇ ਜਾਣੋ ਕਿ ਕਿੰਨੇ ਲੋਕ ਚਾਹੀਦੇ ਹਨ।",
    ex_label: "ਕੋਈ ਉਦਾਹਰਨ ਅਜ਼ਮਾਓ:",
    ex_whatsapp: "ਦੋ WhatsApp ਮੈਸੇਜ",
    ex_banner: "ਦੁਕਾਨ ਦਾ ਬੈਨਰ",
    ex_notice: "ਸਕੂਲ ਸੂਚਨਾ ਰਿਮਾਈਂਡਰ",
    ex_whatsapp_note: "ਇੱਕ ਮਠਿਆਈ ਦੀ ਦੁਕਾਨ ਨੇ 1,000 ਗਾਹਕਾਂ ਨੂੰ ਆਫ਼ਰ ਮੈਸੇਜ A ਅਤੇ ਹੋਰ 1,000 ਨੂੰ ਮੈਸੇਜ B ਭੇਜਿਆ। ਕਨਵਰਜ਼ਨ = ਗਾਹਕ ਨੇ ਆਰਡਰ ਲਈ ਜਵਾਬ ਦਿੱਤਾ।",
    ex_banner_note: "ਇੱਕ ਔਨਲਾਈਨ ਸਾੜੀ ਦੁਕਾਨ ਨੇ ਆਉਣ ਵਾਲਿਆਂ ਨੂੰ ਰੈਂਡਮ ਤਰੀਕੇ ਨਾਲ ਬੈਨਰ A ਜਾਂ B ਵਿਖਾਇਆ। ਕਨਵਰਜ਼ਨ = ਆਉਣ ਵਾਲੇ ਨੇ ਕੁਝ ਖ਼ਰੀਦਿਆ।",
    ex_notice_note: "ਮਾਪਿਆਂ ਨੂੰ ਫ਼ੀਸ ਰਿਮਾਈਂਡਰ A (ਸਾਦਾ), B (ਆਖ਼ਰੀ ਤਾਰੀਖ਼ ਮੋਟੇ ਅੱਖਰਾਂ ਵਿੱਚ) ਜਾਂ C (ਦੋ ਵਾਰ ਭੇਜਿਆ) ਮਿਲਿਆ। ਕਨਵਰਜ਼ਨ = ਫ਼ੀਸ ਸਮੇਂ ਸਿਰ ਜਮ੍ਹਾਂ ਹੋਈ।",
    data_h: "ਤੁਹਾਡੇ ਟੈਸਟ ਦੇ ਨਤੀਜੇ",
    col_version: "ਰੂਪ",
    col_visitors: "ਵਿਜ਼ਿਟਰ (ਜਿਨ੍ਹਾਂ ਨੇ ਵੇਖਿਆ)",
    col_conv: "ਕਨਵਰਜ਼ਨ (ਜਿਨ੍ਹਾਂ ਨੇ ਕੰਮ ਕੀਤਾ)",
    col_rate: "ਕਨਵਰਜ਼ਨ ਦਰ",
    ver_a: "ਮੌਜੂਦਾ ਰੂਪ",
    ver_b: "ਨਵਾਂ ਰੂਪ",
    ver_c: "ਇੱਕ ਹੋਰ ਨਵਾਂ ਰੂਪ",
    add_c: "+ ਰੂਪ C ਜੋੜੋ",
    remove_c: "ਰੂਪ C ਹਟਾਓ",
    sig_label: "ਸਾਰਥਕਤਾ ਪੱਧਰ",
    sig_5: "5% (ਆਮ)",
    sig_1: "1% (ਸਖ਼ਤ)",
    err_blank: "ਹਰ ਰੂਪ ਲਈ ਵਿਜ਼ਿਟਰ ਅਤੇ ਕਨਵਰਜ਼ਨ ਭਰੋ।",
    err_bad: "1000 ਵਰਗੀ ਪੂਰੀ ਸੰਖਿਆ ਲਿਖੋ (ਦਸ਼ਮਲਵ ਜਾਂ ਮਾਈਨਸ ਨਹੀਂ)।",
    err_zero: "ਰੂਪ {v}: ਵਿਜ਼ਿਟਰ ਘੱਟੋ-ਘੱਟ 1 ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ।",
    err_more: "ਰੂਪ {v}: ਕਨਵਰਜ਼ਨ ({c}) ਵਿਜ਼ਿਟਰਾਂ ({n}) ਤੋਂ ਵੱਧ ਨਹੀਂ ਹੋ ਸਕਦੇ।",
    copy_result: "ਨਤੀਜਾ ਕਾਪੀ ਕਰੋ",
    res_h: "ਨਤੀਜਾ",
    res_wait: "ਨਤੀਜਾ ਵੇਖਣ ਲਈ ਸੰਖਿਆਵਾਂ ਭਰੋ।",
    three_note: "3 ਰੂਪਾਂ ਵਿੱਚ B ਅਤੇ C ਦੋਵਾਂ ਦੀ ਤੁਲਨਾ A ਨਾਲ ਹੁੰਦੀ ਹੈ। ਝੂਠੀਆਂ ਜਿੱਤਾਂ ਘੱਟ ਰਹਿਣ, ਇਸ ਲਈ ਹਰ ਤੁਲਨਾ ਨੂੰ ਵੱਧ ਸਖ਼ਤ ਪੱਧਰ ਪਾਰ ਕਰਨਾ ਪਵੇਗਾ: {a}।",
    cmp_h: "{v} ਦੀ A ਨਾਲ ਤੁਲਨਾ",
    verdict_better: "{v} ਵਧੀਆ ਹੈ, ਅਤੇ ਇਸ ਦੇ ਕਿਸਮਤ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ ਘੱਟ ਹੈ।",
    verdict_worse: "{v} A ਤੋਂ ਮਾੜਾ ਹੈ, ਅਤੇ ਇਸ ਦੇ ਕਿਸਮਤ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ ਘੱਟ ਹੈ।",
    verdict_unsure: "ਅਜੇ ਕਾਫ਼ੀ ਸਬੂਤ ਨਹੀਂ ਹੈ। ਇਹ ਫ਼ਰਕ ਸਿਰਫ਼ ਕਿਸਮਤ ਵੀ ਹੋ ਸਕਦਾ ਹੈ।",
    verdict_sig_sub: "p-value {p} ਹੈ, ਜੋ {a} ਤੋਂ ਘੱਟ ਹੈ।",
    verdict_unsure_sub: "p-value {p} ਹੈ, ਜੋ {a} ਤੋਂ ਘੱਟ ਨਹੀਂ। ਤੈਅ ਕੀਤੇ ਲੋਕ ਪੂਰੇ ਹੋਣ ਤੱਕ ਟੈਸਟ ਚਲਾਉਂਦੇ ਰਹੋ।",
    st_diff: "ਫ਼ਰਕ ({v} − A)",
    pts_unit: "ਪ੍ਰਤੀਸ਼ਤ ਅੰਕ",
    st_uplift: "ਤੁਲਨਾਤਮਕ ਵਾਧਾ",
    st_p: "p-value",
    p_need: "{a} ਤੋਂ ਘੱਟ ਹੋਵੇ ਤਾਂ ਸਾਰਥਕ",
    st_ci: "ਫ਼ਰਕ ਦੀ {c}% ਭਰੋਸੇ ਦੀ ਸੀਮਾ",
    st_ci_val: "{lo} ਤੋਂ {hi}",
    st_beat: "{v} ਦੇ A ਤੋਂ ਅੱਗੇ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ",
    st_beat_sub: "ਬੇਜ਼ੀਅਨ ਅੰਦਾਜ਼ਾ",
    ci_note_pos: "ਪੂਰੀ ਸੀਮਾ 0 ਤੋਂ ਉੱਪਰ ਹੈ, ਇਸ ਲਈ {v} ਲਗਭਗ ਪੱਕਾ ਵਧੀਆ ਹੈ।",
    ci_note_neg: "ਪੂਰੀ ਸੀਮਾ 0 ਤੋਂ ਹੇਠਾਂ ਹੈ, ਇਸ ਲਈ {v} ਲਗਭਗ ਪੱਕਾ ਮਾੜਾ ਹੈ।",
    ci_note_zero: "ਸੀਮਾ ਵਿੱਚ 0 ਸ਼ਾਮਲ ਹੈ, ਇਸ ਲਈ \"ਕੋਈ ਅਸਲੀ ਫ਼ਰਕ ਨਹੀਂ\" ਵੀ ਹੋ ਸਕਦਾ ਹੈ।",
    work_h: "ਹੱਲ ਵੇਖੋ (z-ਟੈਸਟ)",
    work_pool: "A ਅਤੇ {v} ਦੀ ਮਿਲੀ-ਜੁਲੀ ਦਰ: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "ਮਿਆਰੀ ਗ਼ਲਤੀ (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = ਫ਼ਰਕ ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = ਜੇ ਕੋਈ ਅਸਲੀ ਫ਼ਰਕ ਨਾ ਹੋਵੇ, ਤਾਂ z ਦੇ 0 ਤੋਂ ਇੰਨਾ ਦੂਰ (ਕਿਸੇ ਵੀ ਪਾਸੇ) ਆਉਣ ਦੀ ਸੰਭਾਵਨਾ = {p}",
    work_ci: "ਭਰੋਸੇ ਦੀ ਸੀਮਾ = ਫ਼ਰਕ ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "ਸਭ ਤੋਂ ਵਧੀਆ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ",
    warn_small: "ਬਹੁਤ ਛੋਟਾ ਨਮੂਨਾ: ਰੂਪ {v} ਵਿੱਚ 10 ਤੋਂ ਘੱਟ ਕਨਵਰਜ਼ਨ ਜਾਂ 10 ਤੋਂ ਘੱਟ ਬਿਨਾਂ-ਕਨਵਰਜ਼ਨ ਹਨ। ਨਤੀਜੇ ਬਹੁਤ ਉੱਪਰ-ਹੇਠਾਂ ਹੋ ਸਕਦੇ ਹਨ। ਹੋਰ ਡਾਟਾ ਇਕੱਠਾ ਕਰੋ।",
    warn_split: "ਵੰਡ ਬਰਾਬਰ ਨਹੀਂ: {s}। ਜੇ ਤੁਸੀਂ ਲੋਕਾਂ ਨੂੰ ਬਰਾਬਰ ਵੰਡਣਾ ਚਾਹੁੰਦੇ ਸੀ, ਤਾਂ ਇੰਨਾ ਵੱਡਾ ਫ਼ਰਕ ਇਤਫ਼ਾਕ ਨਾਲ ਹੋਣਾ ਬਹੁਤ ਔਖਾ ਹੈ। ਜਾਂਚੋ ਕਿ ਕਿਸ ਨੂੰ ਕਿਹੜਾ ਰੂਪ ਕਿਵੇਂ ਮਿਲਿਆ।",
    warn_peek: "ਪਲਾਨਰ ਵੱਲੋਂ ਦੱਸੇ ਲੋਕਾਂ ({n} ਹਰ ਰੂਪ ਵਿੱਚ) ਵਿੱਚੋਂ ਤੁਹਾਡੇ ਕੋਲ ਸਿਰਫ਼ {x}% ਹਨ। ਨਤੀਜਾ ਚੰਗਾ ਲੱਗਦੇ ਹੀ ਟੈਸਟ ਰੋਕ ਦੇਣ ਨੂੰ \"ਝਾਤੀ ਮਾਰਨਾ\" (peeking) ਕਹਿੰਦੇ ਹਨ, ਅਤੇ ਇਸ ਨਾਲ ਕਈ ਝੂਠੀਆਂ ਜਿੱਤਾਂ ਮਿਲਦੀਆਂ ਹਨ। ਤੈਅ ਗਿਣਤੀ ਦੀ ਉਡੀਕ ਕਰੋ।",
    warn_peek_gen: "ਝਾਤੀ ਨਾ ਮਾਰੋ: ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਤੈਅ ਕਰੋ ਕਿ ਕਿੰਨੇ ਲੋਕ ਚਾਹੀਦੇ ਹਨ (ਹੇਠਾਂ ਪਲਾਨਰ), ਅਤੇ ਉਨ੍ਹੇ ਲੋਕ ਪੂਰੇ ਹੋਣ ਤੇ ਹੀ ਨਤੀਜਾ ਵੇਖੋ।",
    chart_h: "ਅਸਲੀ ਦਰ ਸ਼ਾਇਦ ਕਿੱਥੇ ਹੈ",
    chart_note: "ਹਰ ਵਕਰ ਕਿਸੇ ਰੂਪ ਦੀ ਅਸਲੀ ਕਨਵਰਜ਼ਨ ਦਰ ਦੇ ਭਰੋਸੇਯੋਗ ਮੁੱਲ ਵਿਖਾਉਂਦਾ ਹੈ। ਜੇ ਵਕਰ ਇੱਕ-ਦੂਜੇ ਉੱਤੇ ਬਹੁਤ ਚੜ੍ਹੇ ਹੋਣ, ਤਾਂ ਟੈਸਟ ਅਜੇ ਰੂਪਾਂ ਵਿੱਚ ਫ਼ਰਕ ਨਹੀਂ ਦੱਸ ਸਕਦਾ।",
    chart_aria: "ਹਰ ਰੂਪ ਦੀ ਸੰਭਾਵੀ ਅਸਲੀ ਕਨਵਰਜ਼ਨ ਦਰ ਦੇ ਵਕਰ",
    axis_rate: "ਕਨਵਰਜ਼ਨ ਦਰ",
    plan_h: "ਨਮੂਨਾ ਆਕਾਰ ਪਲਾਨਰ",
    plan_intro: "ਟੈਸਟ ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ: ਹਰ ਰੂਪ ਕਿੰਨੇ ਲੋਕਾਂ ਨੂੰ ਵਿਖਾਉਣਾ ਚਾਹੀਦਾ ਹੈ?",
    plan_base: "ਹੁਣ ਦੀ ਕਨਵਰਜ਼ਨ ਦਰ (%)",
    plan_use_a: "A ਦੀ ਦਰ ਲਓ",
    plan_change: "ਲੱਭਣ ਯੋਗ ਸਭ ਤੋਂ ਛੋਟੀ ਤਬਦੀਲੀ",
    plan_abs: "ਪ੍ਰਤੀਸ਼ਤ ਅੰਕ",
    plan_rel: "ਹੁਣ ਦੀ ਦਰ ਦਾ %",
    plan_power: "ਪਾਵਰ (ਅਸਲੀ ਤਬਦੀਲੀ ਫੜਨ ਦੀ ਸੰਭਾਵਨਾ)",
    plan_sig: "ਸਾਰਥਕਤਾ ਪੱਧਰ",
    plan_versions: "ਟੈਸਟ ਵਿੱਚ ਰੂਪ",
    plan_daily: "ਰੋਜ਼ ਦੇ ਲੋਕ (ਸਾਰੇ ਰੂਪ ਮਿਲਾ ਕੇ)",
    plan_per: "ਹਰ ਰੂਪ ਲਈ ਲੋਕ",
    plan_total: "ਕੁੱਲ ਲੋਕ",
    plan_days: "ਕਿੰਨੇ ਦਿਨ ਲੱਗਣਗੇ",
    plan_days_val: "{n} ਦਿਨ",
    plan_bad: "ਹੁਣ ਦੀ ਦਰ 0 ਅਤੇ 100 ਦੇ ਵਿਚਕਾਰ ਭਰੋ, ਅਤੇ ਅਜਿਹੀ ਤਬਦੀਲੀ ਦਿਓ ਕਿ ਨਵੀਂ ਦਰ ਵੀ 0 ਅਤੇ 100 ਦੇ ਵਿਚਕਾਰ ਰਹੇ।",
    plan_target: "ਤੁਸੀਂ {a}% ਤੋਂ {b}% ਦੀ ਤਬਦੀਲੀ ਲੱਭਣਾ ਚਾਹੁੰਦੇ ਹੋ।",
    plan_3note: "3 ਰੂਪਾਂ ਵਿੱਚ ਹਰ ਤੁਲਨਾ ਵੱਧ ਸਖ਼ਤ ਪੱਧਰ {a} ਵਰਤਦੀ ਹੈ।",
    plan_formula: "ਫ਼ਾਰਮੂਲਾ (ਦੋਵੇਂ ਪਾਸਿਆਂ ਦਾ ਟੈਸਟ): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², ਜਿੱਥੇ p̄ = (p1 + p2) ÷ 2। ਇੱਥੇ z ਦੇ ਮੁੱਲ {za} ਅਤੇ {zb} ਹਨ, ਤਾਂ n = {raw}, ਉੱਪਰ ਵੱਲ ਪੂਰਾ ਕਰਕੇ {n}।",
    plan_note: "ਛੋਟੀ ਤਬਦੀਲੀ ਲਈ ਬਹੁਤ ਵੱਧ ਲੋਕ ਚਾਹੀਦੇ ਹਨ: ਅੱਧੀ ਤਬਦੀਲੀ ਲੱਭਣ ਲਈ ਲਗਭਗ 4 ਗੁਣਾ ਲੋਕ।",
    words_h: "ਜਾਣਨ ਯੋਗ ਸ਼ਬਦ",
    w_conv: "ਕਨਵਰਜ਼ਨ",
    d_conv: "ਜੋ ਕੰਮ ਤੁਸੀਂ ਚਾਹੁੰਦੇ ਹੋ: ਜਵਾਬ, ਖ਼ਰੀਦ, ਫ਼ਾਰਮ ਭਰਨਾ, ਫ਼ੀਸ ਜਮ੍ਹਾਂ ਕਰਨਾ, ਕਲਿੱਕ।",
    w_rate: "ਕਨਵਰਜ਼ਨ ਦਰ",
    d_rate: "ਕਨਵਰਜ਼ਨ ÷ ਵੇਖਣ ਵਾਲੇ ਲੋਕ। 1,000 ਵਿਜ਼ਿਟਰਾਂ ਵਿੱਚੋਂ 250 ਖ਼ਰੀਦਦਾਰ = 25%।",
    w_uplift: "ਵਾਧਾ",
    d_uplift: "20% ਤੋਂ 25% ਹੋਣਾ 5 ਪ੍ਰਤੀਸ਼ਤ ਅੰਕ ਦਾ ਵਾਧਾ ਹੈ, ਯਾਨੀ 25% ਤੁਲਨਾਤਮਕ ਵਾਧਾ (5, 20 ਦਾ ਚੌਥਾ ਹਿੱਸਾ ਹੈ)।",
    w_p: "p-value",
    d_p: "ਜੇ A ਅਤੇ B ਸੱਚਮੁੱਚ ਇੱਕੋ ਜਿਹੇ ਹੋਣ, ਤਾਂ ਸਿਰਫ਼ ਕਿਸਮਤ ਨਾਲ ਇੰਨਾ ਵੱਡਾ ਫ਼ਰਕ ਕਿੰਨੀ ਵਾਰ ਆਵੇਗਾ? ਛੋਟਾ p-value (ਜਿਵੇਂ 0.01) ਦਾ ਮਤਲਬ ਕਿਸਮਤ ਵਾਲੀ ਗੱਲ ਮੁਸ਼ਕਲ ਹੈ।",
    w_sig: "ਸਾਰਥਕਤਾ ਪੱਧਰ",
    d_sig: "ਟੈਸਟ ਤੋਂ ਪਹਿਲਾਂ ਚੁਣੀ p-value ਦੀ ਹੱਦ, ਆਮ ਤੌਰ ਤੇ 5%। ਇਸ ਤੋਂ ਘੱਟ ਹੋਵੇ ਤਾਂ ਨਤੀਜਾ \"ਸਾਰਥਕ\" ਕਹਾਉਂਦਾ ਹੈ।",
    w_ci: "ਭਰੋਸੇ ਦੀ ਸੀਮਾ",
    d_ci: "ਫ਼ਰਕ ਦੇ ਉਹ ਮੁੱਲ ਜੋ ਡਾਟਾ ਨਾਲ ਮੇਲ ਖਾਂਦੇ ਹਨ। ਜੇ ਇਸ ਵਿੱਚ 0 ਨਹੀਂ, ਤਾਂ ਨਤੀਜਾ ਸਾਰਥਕ ਹੈ।",
    w_power: "ਪਾਵਰ",
    d_power: "ਇਹ ਸੰਭਾਵਨਾ ਕਿ ਤੁਹਾਡਾ ਟੈਸਟ ਤੁਹਾਡੀ ਸੋਚੀ ਹੋਈ ਜਿੰਨੀ ਅਸਲੀ ਤਬਦੀਲੀ ਫੜ ਲਵੇ। ਆਮ ਤੌਰ ਤੇ 80%।",
    w_bayes: "B ਦੇ A ਤੋਂ ਅੱਗੇ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ",
    d_bayes: "ਉਸੇ ਡਾਟਾ ਨੂੰ ਪੜ੍ਹਨ ਦਾ ਦੂਜਾ ਤਰੀਕਾ (ਬੇਜ਼ੀਅਨ): ਕਿੰਨੀ ਸੰਭਾਵਨਾ ਹੈ ਕਿ B ਦੀ ਅਸਲੀ ਦਰ A ਤੋਂ ਵੱਧ ਹੈ?",
    w_peek: "ਝਾਤੀ ਮਾਰਨਾ (peeking)",
    d_peek: "ਵਾਰ-ਵਾਰ ਨਤੀਜਾ ਵੇਖਣਾ ਅਤੇ ਸਾਰਥਕ ਲੱਗਦੇ ਹੀ ਰੋਕ ਦੇਣਾ। ਇਸ ਨਾਲ ਝੂਠੀਆਂ ਜਿੱਤਾਂ ਬਹੁਤ ਵਧ ਜਾਂਦੀਆਂ ਹਨ।",
    help_title: "ਕਿਵੇਂ ਵਰਤੀਏ / ਸੁਝਾਅ",
    tip1: "ਕੋਈ ਉਦਾਹਰਨ ਚੁਣੋ, ਜਾਂ ਹਰ ਰੂਪ ਦੇ ਲੋਕ ਅਤੇ ਕਨਵਰਜ਼ਨ ਲਿਖੋ। ਲਿਖਦੇ ਹੀ ਨਤੀਜਾ ਬਦਲਦਾ ਹੈ।",
    tip2: "ਕੰਮ ਤੇ: WhatsApp ਆਫ਼ਰ ਦੇ ਦੋ ਰੂਪ ਗਾਹਕ ਸੂਚੀ ਦੇ ਰੈਂਡਮ ਦੋ ਅੱਧੇ ਹਿੱਸਿਆਂ ਨੂੰ ਭੇਜੋ ਅਤੇ ਜਵਾਬ ਗਿਣੋ। ਪਹਿਲਾਂ ਪਲਾਨਰ ਵਿੱਚ ਵੇਖੋ ਕਿ ਸੂਚੀ ਕਿੰਨੀ ਵੱਡੀ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।",
    tip3: "ਦੁਕਾਨ ਅਤੇ ਵੈੱਬਸਾਈਟ: ਉਨ੍ਹਾਂ ਹੀ ਦਿਨਾਂ ਵਿੱਚ ਬੈਨਰ A ਜਾਂ B ਰੈਂਡਮ ਵਿਖਾਓ (ਇਸ ਹਫ਼ਤੇ A ਅਤੇ ਅਗਲੇ ਹਫ਼ਤੇ B ਨਹੀਂ), ਅਤੇ ਇੱਕ ਵਾਰ ਵਿੱਚ ਇੱਕੋ ਚੀਜ਼ ਬਦਲੋ।",
    tip4: "ਜਮਾਤ ਵਿੱਚ: ਅੱਧੀ ਜਮਾਤ ਨੂੰ ਹੋਮਵਰਕ ਰਿਮਾਈਂਡਰ A ਮਿਲੇ, ਅੱਧੀ ਨੂੰ B। ਗਿਣੋ ਕਿਸ ਨੇ ਸਮੇਂ ਸਿਰ ਜਮ੍ਹਾਂ ਕੀਤਾ ਅਤੇ ਜਾਂਚੋ ਕਿ ਫ਼ਰਕ ਅਸਲੀ ਹੈ ਜਾਂ ਨਹੀਂ। ਫਿਰ ਸਿੱਕੇ ਉਛਾਲ ਕੇ ਵੇਖੋ ਕਿ ਸਿਰਫ਼ ਕਿਸਮਤ ਕਿੰਨੀ ਵਾਰ ਫ਼ਰਕ ਬਣਾ ਦਿੰਦੀ ਹੈ।",
    tip5: "ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਲੋਕਾਂ ਦੀ ਗਿਣਤੀ ਅਤੇ ਸਾਰਥਕਤਾ ਪੱਧਰ ਤੈਅ ਕਰੋ, ਅਤੇ ਨਤੀਜਾ ਚੰਗਾ ਲੱਗਣ ਤੇ ਜਲਦੀ ਨਾ ਰੋਕੋ।",
    sum_row: "{v}: {r} ({n} ਵਿੱਚੋਂ {c})"
  },
  or: {
    app_title: "A/B ଟେଷ୍ଟ କାଲକୁଲେଟର",
    intro: "ଆପଣ କୌଣସି ମେସେଜ, ବ୍ୟାନର ବା ସୂଚନାର ଦୁଇଟି ରୂପ ଚେଷ୍ଟା କଲେ। B କ'ଣ ସତରେ A ଠାରୁ ଭଲ ହେଲା, ନା ଏହା କେବଳ ଭାଗ୍ୟ? p-value, ଭରସାର ସୀମା, B ଜିତିବାର ସମ୍ଭାବନା ଦେଖନ୍ତୁ, ଏବଂ କେତେ ଲୋକ ଦରକାର ତାହା ସ୍ଥିର କରନ୍ତୁ।",
    ex_label: "ଏକ ଉଦାହରଣ ଦେଖନ୍ତୁ:",
    ex_whatsapp: "ଦୁଇଟି WhatsApp ମେସେଜ",
    ex_banner: "ଦୋକାନର ବ୍ୟାନର",
    ex_notice: "ସ୍କୁଲ ସୂଚନା ରିମାଇଣ୍ଡର",
    ex_whatsapp_note: "ଗୋଟିଏ ମିଠା ଦୋକାନ 1,000 ଗ୍ରାହକଙ୍କୁ ଅଫର ମେସେଜ A ଏବଂ ଆଉ 1,000 ଜଣଙ୍କୁ ମେସେଜ B ପଠାଇଲା। କନଭର୍ସନ = ଗ୍ରାହକ ଅର୍ଡର ପାଇଁ ଉତ୍ତର ଦେଲେ।",
    ex_banner_note: "ଗୋଟିଏ ଅନଲାଇନ ଶାଢ଼ି ଦୋକାନ ଆସୁଥିବା ଲୋକଙ୍କୁ ଅନିୟମିତ ଭାବେ (ରାଣ୍ଡମ) ବ୍ୟାନର A ବା B ଦେଖାଇଲା। କନଭର୍ସନ = ସେ କିଛି କିଣିଲେ।",
    ex_notice_note: "ଅଭିଭାବକମାନେ ଫି ରିମାଇଣ୍ଡର A (ସାଧା), B (ଶେଷ ତାରିଖ ମୋଟା ଅକ୍ଷରରେ) ବା C (ଦୁଇଥର ପଠାଯାଇଥିବା) ପାଇଲେ। କନଭର୍ସନ = ଫି ସମୟରେ ଜମା ହେଲା।",
    data_h: "ଆପଣଙ୍କ ଟେଷ୍ଟର ଫଳାଫଳ",
    col_version: "ରୂପ",
    col_visitors: "ଭିଜିଟର (ଯେଉଁମାନେ ଦେଖିଲେ)",
    col_conv: "କନଭର୍ସନ (ଯେଉଁମାନେ କାମଟି କଲେ)",
    col_rate: "କନଭର୍ସନ ହାର",
    ver_a: "ବର୍ତ୍ତମାନର ରୂପ",
    ver_b: "ନୂଆ ରୂପ",
    ver_c: "ଆଉ ଏକ ନୂଆ ରୂପ",
    add_c: "+ ରୂପ C ଯୋଡ଼ନ୍ତୁ",
    remove_c: "ରୂପ C ହଟାନ୍ତୁ",
    sig_label: "ସାର୍ଥକତା ସ୍ତର",
    sig_5: "5% (ସାଧାରଣ)",
    sig_1: "1% (କଡ଼ା)",
    err_blank: "ପ୍ରତ୍ୟେକ ରୂପ ପାଇଁ ଭିଜିଟର ଓ କନଭର୍ସନ ଭରନ୍ତୁ।",
    err_bad: "1000 ପରି ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା ଲେଖନ୍ତୁ (ଦଶମିକ ବା ମାଇନସ ନୁହେଁ)।",
    err_zero: "ରୂପ {v}: ଭିଜିଟର ଅତି କମରେ 1 ହେବା ଦରକାର।",
    err_more: "ରୂପ {v}: କନଭର୍ସନ ({c}) ଭିଜିଟର ({n}) ଠାରୁ ଅଧିକ ହୋଇପାରିବ ନାହିଁ।",
    copy_result: "ଫଳାଫଳ କପି କରନ୍ତୁ",
    res_h: "ଫଳାଫଳ",
    res_wait: "ଫଳାଫଳ ଦେଖିବାକୁ ସଂଖ୍ୟାଗୁଡ଼ିକ ଭରନ୍ତୁ।",
    three_note: "3ଟି ରୂପରେ B ଓ C ଦୁହିଁଙ୍କୁ A ସହ ତୁଳନା କରାଯାଏ। ଭୁଲ ଜିତ କମ ରଖିବା ପାଇଁ ପ୍ରତ୍ୟେକ ତୁଳନାକୁ ଅଧିକ କଡ଼ା ସ୍ତର ପାର କରିବାକୁ ହେବ: {a}।",
    cmp_h: "A ସହ {v}ର ତୁଳନା",
    verdict_better: "{v} ଭଲ, ଏବଂ ଏହା ଭାଗ୍ୟ ହେବାର ସମ୍ଭାବନା କମ।",
    verdict_worse: "{v} A ଠାରୁ ଖରାପ, ଏବଂ ଏହା ଭାଗ୍ୟ ହେବାର ସମ୍ଭାବନା କମ।",
    verdict_unsure: "ଏବେ ଯଥେଷ୍ଟ ପ୍ରମାଣ ନାହିଁ। ଏହି ପାର୍ଥକ୍ୟ କେବଳ ଭାଗ୍ୟ ମଧ୍ୟ ହୋଇପାରେ।",
    verdict_sig_sub: "p-value {p}, ଯାହା {a} ଠାରୁ କମ।",
    verdict_unsure_sub: "p-value {p}, ଯାହା {a} ଠାରୁ କମ ନୁହେଁ। ସ୍ଥିର କରିଥିବା ଲୋକ ସଂଖ୍ୟା ପୂରଣ ହେବା ପର୍ଯ୍ୟନ୍ତ ଟେଷ୍ଟ ଚଲାନ୍ତୁ।",
    st_diff: "ପାର୍ଥକ୍ୟ ({v} − A)",
    pts_unit: "ପ୍ରତିଶତ ଅଙ୍କ",
    st_uplift: "ଆପେକ୍ଷିକ ବୃଦ୍ଧି",
    st_p: "p-value",
    p_need: "{a} ଠାରୁ କମ ହେଲେ ସାର୍ଥକ",
    st_ci: "ପାର୍ଥକ୍ୟର {c}% ଭରସାର ସୀମା",
    st_ci_val: "{lo} ରୁ {hi}",
    st_beat: "{v} A କୁ ହରାଇବାର ସମ୍ଭାବନା",
    st_beat_sub: "ବେଜିଆନ ଅନୁମାନ",
    ci_note_pos: "ପୂରା ସୀମା 0 ଉପରେ, ତେଣୁ {v} ପ୍ରାୟ ନିଶ୍ଚିତ ଭାବେ ଭଲ।",
    ci_note_neg: "ପୂରା ସୀମା 0 ତଳେ, ତେଣୁ {v} ପ୍ରାୟ ନିଶ୍ଚିତ ଭାବେ ଖରାପ।",
    ci_note_zero: "ସୀମା ଭିତରେ 0 ଅଛି, ତେଣୁ \"କୌଣସି ପ୍ରକୃତ ପାର୍ଥକ୍ୟ ନାହିଁ\" ମଧ୍ୟ ସମ୍ଭବ।",
    work_h: "ହିସାବ ଦେଖନ୍ତୁ (z-ଟେଷ୍ଟ)",
    work_pool: "A ଓ {v}ର ମିଳିତ ହାର: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "ମାନକ ତ୍ରୁଟି (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = ପାର୍ଥକ୍ୟ ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = ପ୍ରକୃତ ପାର୍ଥକ୍ୟ ନ ଥିଲେ z 0 ଠାରୁ ଏତେ ଦୂର (ଯେକୌଣସି ପଟେ) ଆସିବାର ସମ୍ଭାବନା = {p}",
    work_ci: "ଭରସାର ସୀମା = ପାର୍ଥକ୍ୟ ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "ସର୍ବୋତ୍ତମ ହେବାର ସମ୍ଭାବନା",
    warn_small: "ବହୁତ ଛୋଟ ନମୁନା: ରୂପ {v}ରେ 10ରୁ କମ କନଭର୍ସନ ବା 10ରୁ କମ ବିନା-କନଭର୍ସନ ଅଛି। ଫଳାଫଳ ବହୁତ ଉପର-ତଳ ହୋଇପାରେ। ଅଧିକ ଡାଟା ସଂଗ୍ରହ କରନ୍ତୁ।",
    warn_split: "ବଣ୍ଟନ ସମାନ ନୁହେଁ: {s}। ଯଦି ଆପଣ ଲୋକଙ୍କୁ ସମାନ ଭାବେ ବାଣ୍ଟିବାକୁ ଚାହୁଁଥିଲେ, ଏତେ ବଡ଼ ଫରକ ସଂଯୋଗରେ ହେବା ବହୁତ କଷ୍ଟ। କିଏ କେଉଁ ରୂପ କିପରି ପାଇଲେ ଯାଞ୍ଚ କରନ୍ତୁ।",
    warn_peek: "ପ୍ଲାନର କହୁଥିବା ଲୋକଙ୍କ ({n} ପ୍ରତି ରୂପରେ) ମଧ୍ୟରୁ ଆପଣଙ୍କ ପାଖରେ କେବଳ {x}% ଅଛି। ଫଳାଫଳ ଭଲ ଦେଖାଯିବା ମାତ୍ରେ ଟେଷ୍ଟ ବନ୍ଦ କରିବାକୁ \"ଝାଙ୍କିବା\" (peeking) କୁହାଯାଏ, ଏଥିରେ ଅନେକ ଭୁଲ ଜିତ ମିଳେ। ସ୍ଥିର ସଂଖ୍ୟା ପାଇଁ ଅପେକ୍ଷା କରନ୍ତୁ।",
    warn_peek_gen: "ଝାଙ୍କନ୍ତୁ ନାହିଁ: ଆରମ୍ଭ ପୂର୍ବରୁ କେତେ ଲୋକ ଦରକାର ସ୍ଥିର କରନ୍ତୁ (ତଳେ ପ୍ଲାନର), ଏବଂ ସେତିକି ଲୋକ ପୂରଣ ହେଲେ ହିଁ ଫଳାଫଳ ବିଚାର କରନ୍ତୁ।",
    chart_h: "ପ୍ରକୃତ ହାର ବୋଧହୁଏ କେଉଁଠି",
    chart_note: "ପ୍ରତ୍ୟେକ ବକ୍ରରେଖା ଗୋଟିଏ ରୂପର ପ୍ରକୃତ କନଭର୍ସନ ହାରର ବିଶ୍ୱାସଯୋଗ୍ୟ ମୂଲ୍ୟ ଦେଖାଏ। ରେଖାଗୁଡ଼ିକ ପରସ୍ପର ଉପରେ ବହୁତ ପଡ଼ିଲେ, ଟେଷ୍ଟ ଏବେ ରୂପଗୁଡ଼ିକର ପାର୍ଥକ୍ୟ କହିପାରିବ ନାହିଁ।",
    chart_aria: "ପ୍ରତ୍ୟେକ ରୂପର ସମ୍ଭାବ୍ୟ ପ୍ରକୃତ କନଭର୍ସନ ହାରର ବକ୍ରରେଖା",
    axis_rate: "କନଭର୍ସନ ହାର",
    plan_h: "ନମୁନା ଆକାର ପ୍ଲାନର",
    plan_intro: "ଟେଷ୍ଟ ଆରମ୍ଭ ପୂର୍ବରୁ: ପ୍ରତ୍ୟେକ ରୂପ କେତେ ଲୋକଙ୍କୁ ଦେଖାଇବା ଦରକାର?",
    plan_base: "ବର୍ତ୍ତମାନର କନଭର୍ସନ ହାର (%)",
    plan_use_a: "A ର ହାର ନିଅନ୍ତୁ",
    plan_change: "ଖୋଜିବା ଯୋଗ୍ୟ ସବୁଠୁ ଛୋଟ ପରିବର୍ତ୍ତନ",
    plan_abs: "ପ୍ରତିଶତ ଅଙ୍କ",
    plan_rel: "ବର୍ତ୍ତମାନ ହାରର %",
    plan_power: "ପାୱାର (ପ୍ରକୃତ ପରିବର୍ତ୍ତନ ଧରିବାର ସମ୍ଭାବନା)",
    plan_sig: "ସାର୍ଥକତା ସ୍ତର",
    plan_versions: "ଟେଷ୍ଟରେ ରୂପ",
    plan_daily: "ଦିନକୁ ଲୋକ (ସବୁ ରୂପ ମିଶି)",
    plan_per: "ପ୍ରତି ରୂପ ପାଇଁ ଲୋକ",
    plan_total: "ମୋଟ ଲୋକ",
    plan_days: "କେତେ ଦିନ ଲାଗିବ",
    plan_days_val: "{n} ଦିନ",
    plan_bad: "ବର୍ତ୍ତମାନର ହାର 0 ରୁ 100 ମଧ୍ୟରେ ଭରନ୍ତୁ, ଏବଂ ଏପରି ପରିବର୍ତ୍ତନ ଦିଅନ୍ତୁ ଯେପରି ନୂଆ ହାର ମଧ୍ୟ 0 ରୁ 100 ମଧ୍ୟରେ ରହେ।",
    plan_target: "ଆପଣ {a}% ରୁ {b}% ର ପରିବର୍ତ୍ତନ ଖୋଜିବାକୁ ଚାହାନ୍ତି।",
    plan_3note: "3ଟି ରୂପରେ ପ୍ରତ୍ୟେକ ତୁଳନା ଅଧିକ କଡ଼ା ସ୍ତର {a} ବ୍ୟବହାର କରେ।",
    plan_formula: "ସୂତ୍ର (ଦୁଇପଟ ଟେଷ୍ଟ): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², ଯେଉଁଠି p̄ = (p1 + p2) ÷ 2। ଏଠାରେ z ର ମୂଲ୍ୟ {za} ଓ {zb}, ତେଣୁ n = {raw}, ଉପରକୁ ପୂର୍ଣ୍ଣ କରି {n}।",
    plan_note: "ଛୋଟ ପରିବର୍ତ୍ତନ ପାଇଁ ବହୁତ ଅଧିକ ଲୋକ ଦରକାର: ଅଧା ପରିବର୍ତ୍ତନ ଖୋଜିବାକୁ ପ୍ରାୟ 4 ଗୁଣ ଲୋକ।",
    words_h: "ଜାଣିବା ଦରକାରୀ ଶବ୍ଦ",
    w_conv: "କନଭର୍ସନ",
    d_conv: "ଆପଣ ଚାହୁଁଥିବା କାମ: ଉତ୍ତର, କିଣାକିଣି, ଫର୍ମ ଭରିବା, ଫି ଜମା, କ୍ଲିକ।",
    w_rate: "କନଭର୍ସନ ହାର",
    d_rate: "କନଭର୍ସନ ÷ ଦେଖିଥିବା ଲୋକ। 1,000 ଭିଜିଟରରୁ 250 କିଣାଳି = 25%।",
    w_uplift: "ବୃଦ୍ଧି",
    d_uplift: "20% ରୁ 25% ହେବା 5 ପ୍ରତିଶତ ଅଙ୍କ ବୃଦ୍ଧି, ଅର୍ଥାତ 25% ଆପେକ୍ଷିକ ବୃଦ୍ଧି (5 ହେଉଛି 20 ର ଏକ-ଚତୁର୍ଥାଂଶ)।",
    w_p: "p-value",
    d_p: "ଯଦି A ଓ B ସତରେ ସମାନ, ତେବେ କେବଳ ଭାଗ୍ୟରୁ ଏତେ ବଡ଼ ପାର୍ଥକ୍ୟ କେତେଥର ଆସିବ? ଛୋଟ p-value (ଯେପରି 0.01) ଅର୍ଥ ଭାଗ୍ୟ କାରଣ ହେବା କଷ୍ଟ।",
    w_sig: "ସାର୍ଥକତା ସ୍ତର",
    d_sig: "ଟେଷ୍ଟ ପୂର୍ବରୁ ବାଛିଥିବା p-value ର ସୀମା, ସାଧାରଣତଃ 5%। ଏହାଠାରୁ କମ ହେଲେ ଫଳାଫଳକୁ \"ସାର୍ଥକ\" କୁହାଯାଏ।",
    w_ci: "ଭରସାର ସୀମା",
    d_ci: "ଡାଟା ସହ ମେଳ ଖାଉଥିବା ପାର୍ଥକ୍ୟର ସୀମା। ଏଥିରେ 0 ନ ଥିଲେ ଫଳାଫଳ ସାର୍ଥକ।",
    w_power: "ପାୱାର",
    d_power: "ଆପଣ ଯୋଜନା କରିଥିବା ଆକାରର ପ୍ରକୃତ ପରିବର୍ତ୍ତନ ଟେଷ୍ଟ ଧରିପାରିବାର ସମ୍ଭାବନା। ସାଧାରଣତଃ 80%।",
    w_bayes: "B A କୁ ହରାଇବାର ସମ୍ଭାବନା",
    d_bayes: "ସେହି ଡାଟା ପଢ଼ିବାର ଆଉ ଏକ ଉପାୟ (ବେଜିଆନ): B ର ପ୍ରକୃତ ହାର A ଠାରୁ ଅଧିକ ହେବାର ସମ୍ଭାବନା କେତେ?",
    w_peek: "ଝାଙ୍କିବା (peeking)",
    d_peek: "ବାରମ୍ବାର ଫଳାଫଳ ଦେଖିବା ଏବଂ ସାର୍ଥକ ଦେଖାଯିବା ମାତ୍ରେ ବନ୍ଦ କରିଦେବା। ଏଥିରେ ଭୁଲ ଜିତ ବହୁତ ବଢ଼ିଯାଏ।",
    help_title: "କିପରି ବ୍ୟବହାର କରିବେ / ପରାମର୍ଶ",
    tip1: "ଏକ ଉଦାହରଣ ବାଛନ୍ତୁ, ବା ପ୍ରତ୍ୟେକ ରୂପର ଲୋକ ଓ କନଭର୍ସନ ଲେଖନ୍ତୁ। ଲେଖିବା ସାଙ୍ଗେ ସାଙ୍ଗେ ଫଳାଫଳ ବଦଳେ।",
    tip2: "କାମରେ: WhatsApp ଅଫରର ଦୁଇଟି ରୂପ ଗ୍ରାହକ ତାଲିକାର ରାଣ୍ଡମ ଦୁଇ ଅଧା ଭାଗକୁ ପଠାନ୍ତୁ ଏବଂ ଉତ୍ତର ଗଣନ୍ତୁ। ପ୍ରଥମେ ପ୍ଲାନରରେ ଦେଖନ୍ତୁ ତାଲିକା କେତେ ବଡ଼ ହେବା ଦରକାର।",
    tip3: "ଦୋକାନ ଓ ୱେବସାଇଟ: ସେହି ଦିନଗୁଡ଼ିକରେ ବ୍ୟାନର A ବା B ରାଣ୍ଡମ ଦେଖାନ୍ତୁ (ଏହି ସପ୍ତାହ A ଓ ଆସନ୍ତା ସପ୍ତାହ B ନୁହେଁ), ଏବଂ ଥରକେ ଗୋଟିଏ ଜିନିଷ ବଦଳାନ୍ତୁ।",
    tip4: "ଶ୍ରେଣୀରେ: ଅଧା ଶ୍ରେଣୀ ଗୃହକାର୍ଯ୍ୟ ରିମାଇଣ୍ଡର A ପାଇବେ, ଅଧା B। କିଏ ସମୟରେ ଜମା କଲେ ଗଣନ୍ତୁ ଏବଂ ପାର୍ଥକ୍ୟ ପ୍ରକୃତ କି ନାହିଁ ଯାଞ୍ଚ କରନ୍ତୁ। ତା'ପରେ ମୁଦ୍ରା ଟସ କରି ଦେଖନ୍ତୁ କେବଳ ଭାଗ୍ୟ କେତେଥର ପାର୍ଥକ୍ୟ ସୃଷ୍ଟି କରେ।",
    tip5: "ଆରମ୍ଭ ପୂର୍ବରୁ ଲୋକ ସଂଖ୍ୟା ଓ ସାର୍ଥକତା ସ୍ତର ସ୍ଥିର କରନ୍ତୁ, ଏବଂ ଫଳାଫଳ ଭଲ ଦେଖାଗଲେ ଶୀଘ୍ର ବନ୍ଦ କରନ୍ତୁ ନାହିଁ।",
    sum_row: "{v}: {r} ({n} ରୁ {c})"
  },
  ta: {
    app_title: "A/B சோதனை கணிப்பான்",
    intro: "ஒரு செய்தி, பேனர் அல்லது அறிவிப்பின் இரண்டு வடிவங்களை முயன்றீர்கள். B உண்மையில் A-ஐ விட நன்றாக இருந்ததா, அல்லது வெறும் அதிர்ஷ்டமா? p-value, நம்பக வரம்பு, B வெல்லும் வாய்ப்பு ஆகியவற்றைப் பாருங்கள்; எத்தனை பேர் தேவை என்றும் திட்டமிடுங்கள்.",
    ex_label: "ஒரு எடுத்துக்காட்டு:",
    ex_whatsapp: "இரண்டு WhatsApp செய்திகள்",
    ex_banner: "கடை பேனர்",
    ex_notice: "பள்ளி அறிவிப்பு நினைவூட்டல்",
    ex_whatsapp_note: "ஒரு இனிப்புக் கடை 1,000 வாடிக்கையாளர்களுக்கு சலுகைச் செய்தி A-வும் வேறு 1,000 பேருக்கு செய்தி B-யும் அனுப்பியது. மாற்றம் = வாடிக்கையாளர் ஆர்டர் செய்ய பதில் அனுப்பினார்.",
    ex_banner_note: "ஒரு ஆன்லைன் சேலைக் கடை வருபவர்களுக்கு சீரற்ற முறையில் (ரேண்டம்) பேனர் A அல்லது B காட்டியது. மாற்றம் = வந்தவர் ஏதாவது வாங்கினார்.",
    ex_notice_note: "பெற்றோருக்கு கட்டண நினைவூட்டல் A (சாதாரணம்), B (கடைசி தேதி தடித்த எழுத்தில்) அல்லது C (இருமுறை அனுப்பியது) கிடைத்தது. மாற்றம் = கட்டணம் நேரத்தில் செலுத்தப்பட்டது.",
    data_h: "உங்கள் சோதனை முடிவுகள்",
    col_version: "வடிவம்",
    col_visitors: "பார்வையாளர்கள் (பார்த்தவர்கள்)",
    col_conv: "மாற்றங்கள் (செயலைச் செய்தவர்கள்)",
    col_rate: "மாற்ற விகிதம்",
    ver_a: "தற்போதைய வடிவம்",
    ver_b: "புதிய வடிவம்",
    ver_c: "இன்னொரு புதிய வடிவம்",
    add_c: "+ வடிவம் C சேர்",
    remove_c: "வடிவம் C நீக்கு",
    sig_label: "முக்கியத்துவ நிலை",
    sig_5: "5% (வழக்கம்)",
    sig_1: "1% (கண்டிப்பு)",
    err_blank: "ஒவ்வொரு வடிவத்திற்கும் பார்வையாளர்களையும் மாற்றங்களையும் நிரப்புங்கள்.",
    err_bad: "1000 போன்ற முழு எண்களை எழுதுங்கள் (தசமம் அல்லது கழித்தல் குறி வேண்டாம்).",
    err_zero: "வடிவம் {v}: பார்வையாளர்கள் குறைந்தது 1 ஆக இருக்க வேண்டும்.",
    err_more: "வடிவம் {v}: மாற்றங்கள் ({c}) பார்வையாளர்களை ({n}) விட அதிகமாக இருக்க முடியாது.",
    copy_result: "முடிவை நகலெடு",
    res_h: "முடிவு",
    res_wait: "முடிவைப் பார்க்க எண்களை நிரப்புங்கள்.",
    three_note: "3 வடிவங்களில் B, C இரண்டும் A-உடன் ஒப்பிடப்படுகின்றன. தவறான வெற்றிகள் குறைவாக இருக்க, ஒவ்வொரு ஒப்பீடும் கடுமையான நிலையைத் தாண்ட வேண்டும்: {a}.",
    cmp_h: "{v} மற்றும் A ஒப்பீடு",
    verdict_better: "{v} சிறந்தது, இது அதிர்ஷ்டமாக இருக்க வாய்ப்பு குறைவு.",
    verdict_worse: "{v} A-ஐ விட மோசம், இது அதிர்ஷ்டமாக இருக்க வாய்ப்பு குறைவு.",
    verdict_unsure: "இன்னும் போதுமான சான்று இல்லை. இந்த வேறுபாடு வெறும் அதிர்ஷ்டமாகவும் இருக்கலாம்.",
    verdict_sig_sub: "p-value {p}, இது {a}-ஐ விடக் குறைவு.",
    verdict_unsure_sub: "p-value {p}, இது {a}-ஐ விடக் குறைவு அல்ல. திட்டமிட்ட எண்ணிக்கையில் மக்கள் வரும் வரை சோதனையைத் தொடருங்கள்.",
    st_diff: "வேறுபாடு ({v} − A)",
    pts_unit: "சதவீதப் புள்ளிகள்",
    st_uplift: "ஒப்பீட்டு உயர்வு",
    st_p: "p-value",
    p_need: "{a}-க்குக் கீழ் என்றால் முக்கியமானது",
    st_ci: "வேறுபாட்டின் {c}% நம்பக வரம்பு",
    st_ci_val: "{lo} முதல் {hi}",
    st_beat: "{v} A-ஐ வெல்லும் வாய்ப்பு",
    st_beat_sub: "பேயிசியன் மதிப்பீடு",
    ci_note_pos: "முழு வரம்பும் 0-க்கு மேல் உள்ளது, எனவே {v} பெரும்பாலும் சிறந்தது.",
    ci_note_neg: "முழு வரம்பும் 0-க்குக் கீழ் உள்ளது, எனவே {v} பெரும்பாலும் மோசமானது.",
    ci_note_zero: "வரம்பில் 0 உள்ளது, எனவே \"உண்மையான வேறுபாடு இல்லை\" என்பதும் சாத்தியம்.",
    work_h: "கணக்கைக் காட்டு (z-சோதனை)",
    work_pool: "A மற்றும் {v} இன் சேர்ந்த விகிதம்: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "திட்டப் பிழை (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = வேறுபாடு ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = உண்மையான வேறுபாடு இல்லையெனில் z இவ்வளவு தூரம் 0-இலிருந்து (எந்தப் பக்கமும்) வரும் வாய்ப்பு = {p}",
    work_ci: "நம்பக வரம்பு = வேறுபாடு ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "சிறந்ததாக இருக்கும் வாய்ப்பு",
    warn_small: "மிகச் சிறிய மாதிரி: வடிவம் {v} இல் 10-க்கும் குறைவான மாற்றங்கள் அல்லது 10-க்கும் குறைவான மாறாதவர்கள். முடிவுகள் அதிகம் மாறலாம். மேலும் தரவைச் சேகரியுங்கள்.",
    warn_split: "சமமற்ற பிரிவு: {s}. மக்களைச் சமமாகப் பிரிக்க நினைத்திருந்தால், இவ்வளவு பெரிய இடைவெளி தற்செயலாக வருவது மிகக் கடினம். யாருக்கு எந்த வடிவம் எப்படிக் கிடைத்தது என்று சரிபாருங்கள்.",
    warn_peek: "திட்டமிடுபவர் சொல்லும் மக்களில் ({n} ஒவ்வொரு வடிவத்திற்கும்) உங்களிடம் {x}% மட்டுமே உள்ளது. முடிவு நன்றாகத் தெரிந்தவுடன் நிறுத்துவது \"எட்டிப் பார்த்தல்\" (peeking) எனப்படும்; இது பல தவறான வெற்றிகளைத் தரும். திட்டமிட்ட எண்ணிக்கைக்குக் காத்திருங்கள்.",
    warn_peek_gen: "எட்டிப் பார்க்காதீர்கள்: தொடங்கும் முன் எத்தனை பேர் தேவை என்று முடிவு செய்யுங்கள் (கீழே திட்டமிடுபவர்), அந்த எண்ணிக்கை வந்த பிறகே முடிவைத் தீர்மானியுங்கள்.",
    chart_h: "உண்மையான விகிதம் எங்கே இருக்கலாம்",
    chart_note: "ஒவ்வொரு வளைவும் ஒரு வடிவத்தின் உண்மையான மாற்ற விகிதத்தின் நம்பத்தகுந்த மதிப்புகளைக் காட்டுகிறது. வளைவுகள் அதிகம் ஒன்றின் மேல் ஒன்று விழுந்தால், சோதனையால் இன்னும் வடிவங்களைப் பிரித்துச் சொல்ல முடியாது.",
    chart_aria: "ஒவ்வொரு வடிவத்தின் சாத்தியமான உண்மை மாற்ற விகித வளைவுகள்",
    axis_rate: "மாற்ற விகிதம்",
    plan_h: "மாதிரி அளவு திட்டமிடுபவர்",
    plan_intro: "சோதனையைத் தொடங்கும் முன்: ஒவ்வொரு வடிவத்தையும் எத்தனை பேர் பார்க்க வேண்டும்?",
    plan_base: "தற்போதைய மாற்ற விகிதம் (%)",
    plan_use_a: "A-இன் விகிதம்",
    plan_change: "கண்டறிய வேண்டிய மிகச் சிறிய மாற்றம்",
    plan_abs: "சதவீதப் புள்ளிகள்",
    plan_rel: "தற்போதைய விகிதத்தின் %",
    plan_power: "திறன் (உண்மை மாற்றத்தைப் பிடிக்கும் வாய்ப்பு)",
    plan_sig: "முக்கியத்துவ நிலை",
    plan_versions: "சோதனையில் வடிவங்கள்",
    plan_daily: "ஒரு நாளில் மக்கள் (எல்லா வடிவங்களும் சேர்த்து)",
    plan_per: "ஒவ்வொரு வடிவத்திற்கும் மக்கள்",
    plan_total: "மொத்த மக்கள்",
    plan_days: "தேவைப்படும் நாட்கள்",
    plan_days_val: "{n} நாட்கள்",
    plan_bad: "தற்போதைய விகிதத்தை 0 முதல் 100 வரை நிரப்புங்கள்; புதிய விகிதமும் 0 முதல் 100-க்குள் இருக்கும்படி மாற்றத்தைக் கொடுங்கள்.",
    plan_target: "நீங்கள் {a}% இலிருந்து {b}% வரையான மாற்றத்தைக் கண்டறிய விரும்புகிறீர்கள்.",
    plan_3note: "3 வடிவங்களில் ஒவ்வொரு ஒப்பீடும் கடுமையான நிலை {a} ஐப் பயன்படுத்துகிறது.",
    plan_formula: "சூத்திரம் (இருபக்கச் சோதனை): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², இங்கு p̄ = (p1 + p2) ÷ 2. இங்கே z மதிப்புகள் {za}, {zb}; எனவே n = {raw}, மேல்நோக்கி முழுமையாக்கினால் {n}.",
    plan_note: "சிறிய மாற்றத்திற்கு மிக அதிகமான மக்கள் தேவை: பாதி மாற்றத்தைக் கண்டறிய சுமார் 4 மடங்கு மக்கள்.",
    words_h: "தெரிந்துகொள்ள வேண்டிய சொற்கள்",
    w_conv: "மாற்றம் (கன்வர்ஷன்)",
    d_conv: "நீங்கள் விரும்பும் செயல்: பதில், வாங்குதல், படிவம் நிரப்புதல், கட்டணம் செலுத்துதல், கிளிக்.",
    w_rate: "மாற்ற விகிதம்",
    d_rate: "மாற்றங்கள் ÷ பார்த்தவர்கள். 1,000 பார்வையாளர்களில் 250 வாங்குபவர்கள் = 25%.",
    w_uplift: "உயர்வு",
    d_uplift: "20% இலிருந்து 25% என்பது 5 சதவீதப் புள்ளி உயர்வு, அதாவது 25% ஒப்பீட்டு உயர்வு (5 என்பது 20-இன் கால் பங்கு).",
    w_p: "p-value",
    d_p: "A-வும் B-யும் உண்மையில் ஒன்றே என்றால், அதிர்ஷ்டத்தால் மட்டும் இவ்வளவு பெரிய வேறுபாடு எத்தனை முறை வரும்? சிறிய p-value (எ.கா. 0.01) என்றால் அதிர்ஷ்டம் காரணமாக இருக்க வாய்ப்பு குறைவு.",
    w_sig: "முக்கியத்துவ நிலை",
    d_sig: "சோதனைக்கு முன் தேர்ந்தெடுக்கும் p-value எல்லை, வழக்கமாக 5%. அதற்குக் கீழ் இருந்தால் முடிவு \"முக்கியமானது\".",
    w_ci: "நம்பக வரம்பு",
    d_ci: "தரவுக்குப் பொருந்தும் வேறுபாடுகளின் வரம்பு. அதில் 0 இல்லையெனில் முடிவு முக்கியமானது.",
    w_power: "திறன் (பவர்)",
    d_power: "நீங்கள் திட்டமிட்ட அளவிலான உண்மை மாற்றத்தைச் சோதனை பிடிக்கும் வாய்ப்பு. வழக்கமாக 80%.",
    w_bayes: "B, A-ஐ வெல்லும் வாய்ப்பு",
    d_bayes: "அதே தரவைப் படிக்கும் இன்னொரு வழி (பேயிசியன்): B-இன் உண்மை விகிதம் A-ஐ விட அதிகமாக இருக்கும் வாய்ப்பு எவ்வளவு?",
    w_peek: "எட்டிப் பார்த்தல் (peeking)",
    d_peek: "திரும்பத் திரும்ப முடிவைப் பார்த்து, முக்கியமாகத் தெரிந்தவுடன் நிறுத்துவது. இது தவறான வெற்றிகளை மிகவும் அதிகரிக்கும்.",
    help_title: "பயன்படுத்தும் முறை / யோசனைகள்",
    tip1: "ஒரு எடுத்துக்காட்டைத் தேர்ந்தெடுங்கள், அல்லது ஒவ்வொரு வடிவத்தின் மக்களையும் மாற்றங்களையும் தட்டச்சு செய்யுங்கள். தட்டச்சு செய்யும்போதே முடிவு மாறும்.",
    tip2: "வேலையில்: WhatsApp சலுகையின் இரண்டு வடிவங்களை வாடிக்கையாளர் பட்டியலின் சீரற்ற இரு பாதிகளுக்கு அனுப்பி, பதில்களை எண்ணுங்கள். பட்டியல் எவ்வளவு பெரியதாக இருக்க வேண்டும் என்று முதலில் திட்டமிடுபவரில் பாருங்கள்.",
    tip3: "கடைகள், இணையதளங்கள்: அதே நாட்களில் பேனர் A அல்லது B-ஐ சீரற்ற முறையில் காட்டுங்கள் (இந்த வாரம் A, அடுத்த வாரம் B அல்ல); ஒரு நேரத்தில் ஒன்றை மட்டும் மாற்றுங்கள்.",
    tip4: "வகுப்பில்: பாதி வகுப்புக்கு வீட்டுப்பாட நினைவூட்டல் A, பாதிக்கு B. நேரத்தில் கொடுத்தவர்களை எண்ணி, வேறுபாடு உண்மையானதா என்று சோதியுங்கள். பிறகு நாணயங்களைச் சுண்டி, வெறும் அதிர்ஷ்டம் எத்தனை முறை வேறுபாட்டை உண்டாக்குகிறது என்று பாருங்கள்.",
    tip5: "தொடங்கும் முன் மக்கள் எண்ணிக்கையையும் முக்கியத்துவ நிலையையும் முடிவு செய்யுங்கள்; முடிவு நன்றாகத் தெரிகிறது என்பதற்காக முன்கூட்டியே நிறுத்தாதீர்கள்.",
    sum_row: "{v}: {r} ({n} இல் {c})"
  },
  te: {
    app_title: "A/B టెస్ట్ కాలిక్యులేటర్",
    intro: "మీరు ఒక మెసేజ్, బ్యానర్ లేదా నోటీసు యొక్క రెండు రూపాలను ప్రయత్నించారు. B నిజంగా A కంటే బాగా చేసిందా, లేక అది కేవలం అదృష్టమా? p-value, నమ్మక పరిధి, B గెలిచే అవకాశం చూడండి, ఎంతమంది కావాలో ప్లాన్ చేయండి.",
    ex_label: "ఒక ఉదాహరణ చూడండి:",
    ex_whatsapp: "రెండు WhatsApp మెసేజ్‌లు",
    ex_banner: "దుకాణం బ్యానర్",
    ex_notice: "స్కూల్ నోటీసు రిమైండర్",
    ex_whatsapp_note: "ఒక స్వీట్ షాప్ 1,000 మంది కస్టమర్లకు ఆఫర్ మెసేజ్ A, మరో 1,000 మందికి మెసేజ్ B పంపింది. కన్వర్షన్ = కస్టమర్ ఆర్డర్ కోసం జవాబిచ్చారు.",
    ex_banner_note: "ఒక ఆన్‌లైన్ చీరల దుకాణం వచ్చినవారికి యాదృచ్ఛికంగా (రాండమ్) బ్యానర్ A లేదా B చూపించింది. కన్వర్షన్ = వచ్చినవారు ఏదైనా కొన్నారు.",
    ex_notice_note: "తల్లిదండ్రులకు ఫీజు రిమైండర్ A (సాదా), B (చివరి తేదీ బోల్డ్‌లో) లేదా C (రెండుసార్లు పంపినది) వచ్చింది. కన్వర్షన్ = ఫీజు సమయానికి కట్టారు.",
    data_h: "మీ టెస్ట్ ఫలితాలు",
    col_version: "రూపం",
    col_visitors: "సందర్శకులు (చూసినవారు)",
    col_conv: "కన్వర్షన్‌లు (పని చేసినవారు)",
    col_rate: "కన్వర్షన్ రేటు",
    ver_a: "ప్రస్తుత రూపం",
    ver_b: "కొత్త రూపం",
    ver_c: "మరో కొత్త రూపం",
    add_c: "+ రూపం C జోడించండి",
    remove_c: "రూపం C తీసివేయండి",
    sig_label: "ప్రాముఖ్యత స్థాయి",
    sig_5: "5% (సాధారణం)",
    sig_1: "1% (కఠినం)",
    err_blank: "ప్రతి రూపానికి సందర్శకులు, కన్వర్షన్‌లు నింపండి.",
    err_bad: "1000 లాంటి పూర్ణ సంఖ్యలు రాయండి (దశాంశం లేదా మైనస్ వద్దు).",
    err_zero: "రూపం {v}: సందర్శకులు కనీసం 1 ఉండాలి.",
    err_more: "రూపం {v}: కన్వర్షన్‌లు ({c}) సందర్శకుల ({n}) కంటే ఎక్కువ ఉండకూడదు.",
    copy_result: "ఫలితం కాపీ చేయండి",
    res_h: "ఫలితం",
    res_wait: "ఫలితం చూడటానికి సంఖ్యలు నింపండి.",
    three_note: "3 రూపాలలో B, C రెండింటినీ A తో పోలుస్తాం. తప్పుడు గెలుపులు తక్కువగా ఉండాలంటే ప్రతి పోలిక మరింత కఠిన స్థాయిని దాటాలి: {a}.",
    cmp_h: "{v} ను A తో పోలిక",
    verdict_better: "{v} మెరుగైనది, ఇది అదృష్టం అయ్యే అవకాశం తక్కువ.",
    verdict_worse: "{v} A కంటే అధ్వాన్నం, ఇది అదృష్టం అయ్యే అవకాశం తక్కువ.",
    verdict_unsure: "ఇంకా తగిన ఆధారం లేదు. ఈ తేడా కేవలం అదృష్టం కూడా కావచ్చు.",
    verdict_sig_sub: "p-value {p}, ఇది {a} కంటే తక్కువ.",
    verdict_unsure_sub: "p-value {p}, ఇది {a} కంటే తక్కువ కాదు. ప్లాన్ చేసిన సంఖ్యలో మనుషులు వచ్చేవరకు టెస్ట్ కొనసాగించండి.",
    st_diff: "తేడా ({v} − A)",
    pts_unit: "శాతం పాయింట్లు",
    st_uplift: "సాపేక్ష పెరుగుదల",
    st_p: "p-value",
    p_need: "{a} కంటే తక్కువైతే ప్రాముఖ్యం",
    st_ci: "తేడా యొక్క {c}% నమ్మక పరిధి",
    st_ci_val: "{lo} నుండి {hi}",
    st_beat: "{v} A ను ఓడించే అవకాశం",
    st_beat_sub: "బేయేసియన్ అంచనా",
    ci_note_pos: "మొత్తం పరిధి 0 పైన ఉంది, కాబట్టి {v} దాదాపు ఖచ్చితంగా మెరుగైనది.",
    ci_note_neg: "మొత్తం పరిధి 0 కింద ఉంది, కాబట్టి {v} దాదాపు ఖచ్చితంగా అధ్వాన్నం.",
    ci_note_zero: "పరిధిలో 0 ఉంది, కాబట్టి \"నిజమైన తేడా లేదు\" అనేది కూడా సాధ్యమే.",
    work_h: "లెక్క చూపించు (z-టెస్ట్)",
    work_pool: "A, {v} కలిపిన రేటు: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "ప్రామాణిక దోషం (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = తేడా ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = నిజమైన తేడా లేకపోతే z ఇంత దూరం 0 నుండి (ఏ వైపైనా) వచ్చే అవకాశం = {p}",
    work_ci: "నమ్మక పరిధి = తేడా ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "ఉత్తమమైనది అయ్యే అవకాశం",
    warn_small: "చాలా చిన్న నమూనా: రూపం {v} లో 10 కంటే తక్కువ కన్వర్షన్‌లు లేదా 10 కంటే తక్కువ కన్వర్ట్ కానివారు ఉన్నారు. ఫలితాలు బాగా మారవచ్చు. మరింత డేటా సేకరించండి.",
    warn_split: "అసమాన విభజన: {s}. మీరు మనుషులను సమానంగా పంచాలనుకుంటే, ఇంత పెద్ద తేడా యాదృచ్ఛికంగా రావడం చాలా కష్టం. ఎవరికి ఏ రూపం ఎలా వచ్చిందో తనిఖీ చేయండి.",
    warn_peek: "ప్లానర్ చెప్పిన మనుషుల్లో ({n} ప్రతి రూపానికి) మీ దగ్గర {x}% మాత్రమే ఉన్నారు. ఫలితం బాగుందనిపించగానే ఆపేయడాన్ని \"తొంగి చూడటం\" (peeking) అంటారు; దీనివల్ల చాలా తప్పుడు గెలుపులు వస్తాయి. ప్లాన్ చేసిన సంఖ్య కోసం వేచి ఉండండి.",
    warn_peek_gen: "తొంగి చూడకండి: మొదలుపెట్టే ముందే ఎంతమంది కావాలో నిర్ణయించండి (కింద ప్లానర్), ఆ సంఖ్య చేరాకే ఫలితాన్ని నిర్ణయించండి.",
    chart_h: "నిజమైన రేటు బహుశా ఎక్కడ ఉంది",
    chart_note: "ప్రతి వక్రం ఒక రూపం యొక్క నిజమైన కన్వర్షన్ రేటుకు నమ్మదగిన విలువలను చూపిస్తుంది. వక్రాలు ఒకదానిపై ఒకటి ఎక్కువగా పడితే, టెస్ట్ ఇంకా రూపాల మధ్య తేడా చెప్పలేదు.",
    chart_aria: "ప్రతి రూపం యొక్క సంభావ్య నిజమైన కన్వర్షన్ రేటు వక్రాలు",
    axis_rate: "కన్వర్షన్ రేటు",
    plan_h: "నమూనా పరిమాణం ప్లానర్",
    plan_intro: "టెస్ట్ మొదలుపెట్టే ముందు: ప్రతి రూపాన్ని ఎంతమంది చూడాలి?",
    plan_base: "ప్రస్తుత కన్వర్షన్ రేటు (%)",
    plan_use_a: "A రేటు వాడండి",
    plan_change: "కనుక్కోవాల్సిన అతి చిన్న మార్పు",
    plan_abs: "శాతం పాయింట్లు",
    plan_rel: "ప్రస్తుత రేటులో %",
    plan_power: "పవర్ (నిజమైన మార్పును పట్టుకునే అవకాశం)",
    plan_sig: "ప్రాముఖ్యత స్థాయి",
    plan_versions: "టెస్ట్‌లో రూపాలు",
    plan_daily: "రోజుకు మనుషులు (అన్ని రూపాలు కలిపి)",
    plan_per: "ప్రతి రూపానికి మనుషులు",
    plan_total: "మొత్తం మనుషులు",
    plan_days: "ఎన్ని రోజులు పడుతుంది",
    plan_days_val: "{n} రోజులు",
    plan_bad: "ప్రస్తుత రేటును 0 నుండి 100 మధ్య నింపండి, కొత్త రేటు కూడా 0 నుండి 100 మధ్య ఉండేలా మార్పు ఇవ్వండి.",
    plan_target: "మీరు {a}% నుండి {b}% కి మార్పును కనుక్కోవాలనుకుంటున్నారు.",
    plan_3note: "3 రూపాలలో ప్రతి పోలిక మరింత కఠిన స్థాయి {a} వాడుతుంది.",
    plan_formula: "సూత్రం (రెండు వైపుల టెస్ట్): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², ఇక్కడ p̄ = (p1 + p2) ÷ 2. ఇక్కడ z విలువలు {za}, {zb}, కాబట్టి n = {raw}, పైకి పూర్తి చేస్తే {n}.",
    plan_note: "చిన్న మార్పుకు చాలా ఎక్కువ మంది కావాలి: సగం మార్పును కనుక్కోవడానికి సుమారు 4 రెట్లు మంది.",
    words_h: "తెలుసుకోవాల్సిన పదాలు",
    w_conv: "కన్వర్షన్",
    d_conv: "మీరు కోరుకునే పని: జవాబు, కొనుగోలు, ఫారం నింపడం, ఫీజు కట్టడం, క్లిక్.",
    w_rate: "కన్వర్షన్ రేటు",
    d_rate: "కన్వర్షన్‌లు ÷ చూసినవారు. 1,000 సందర్శకులలో 250 మంది కొనుగోలుదారులు = 25%.",
    w_uplift: "పెరుగుదల",
    d_uplift: "20% నుండి 25% అంటే 5 శాతం పాయింట్ల పెరుగుదల, అంటే 25% సాపేక్ష పెరుగుదల (5 అనేది 20 లో నాలుగో వంతు).",
    w_p: "p-value",
    d_p: "A, B నిజంగా ఒకటే అయితే, కేవలం అదృష్టంతో ఇంత పెద్ద తేడా ఎన్నిసార్లు వస్తుంది? చిన్న p-value (ఉదా. 0.01) అంటే అదృష్టం కారణం అయ్యే అవకాశం తక్కువ.",
    w_sig: "ప్రాముఖ్యత స్థాయి",
    d_sig: "టెస్ట్ ముందు ఎంచుకునే p-value హద్దు, సాధారణంగా 5%. దాని కంటే తక్కువైతే ఫలితాన్ని \"ప్రాముఖ్యమైనది\" అంటాం.",
    w_ci: "నమ్మక పరిధి",
    d_ci: "డేటాకు సరిపోయే తేడాల పరిధి. అందులో 0 లేకపోతే ఫలితం ప్రాముఖ్యమైనది.",
    w_power: "పవర్",
    d_power: "మీరు ప్లాన్ చేసిన పరిమాణంలో నిజమైన మార్పును టెస్ట్ పట్టుకునే అవకాశం. సాధారణంగా 80%.",
    w_bayes: "B, A ను ఓడించే అవకాశం",
    d_bayes: "అదే డేటాను చదివే మరో విధానం (బేయేసియన్): B నిజమైన రేటు A కంటే ఎక్కువ ఉండే అవకాశం ఎంత?",
    w_peek: "తొంగి చూడటం (peeking)",
    d_peek: "మళ్లీ మళ్లీ ఫలితం చూసి, ప్రాముఖ్యంగా కనిపించగానే ఆపేయడం. దీనివల్ల తప్పుడు గెలుపులు బాగా పెరుగుతాయి.",
    help_title: "ఎలా వాడాలి / ఆలోచనలు",
    tip1: "ఒక ఉదాహరణ ఎంచుకోండి, లేదా ప్రతి రూపానికి మనుషులు, కన్వర్షన్‌లు టైప్ చేయండి. టైప్ చేస్తుండగానే ఫలితం మారుతుంది.",
    tip2: "పనిలో: WhatsApp ఆఫర్ యొక్క రెండు రూపాలను కస్టమర్ జాబితాలో యాదృచ్ఛిక రెండు సగాలకు పంపి, జవాబులు లెక్కించండి. జాబితా ఎంత పెద్దదిగా ఉండాలో ముందుగా ప్లానర్‌లో చూడండి.",
    tip3: "దుకాణాలు, వెబ్‌సైట్లు: అవే రోజుల్లో బ్యానర్ A లేదా B ను యాదృచ్ఛికంగా చూపించండి (ఈ వారం A, వచ్చే వారం B కాదు), ఒకసారికి ఒక్కటే మార్చండి.",
    tip4: "తరగతిలో: సగం తరగతికి హోంవర్క్ రిమైండర్ A, సగానికి B. సమయానికి ఇచ్చినవారిని లెక్కించి, తేడా నిజమైనదో కాదో పరీక్షించండి. తర్వాత నాణేలు ఎగరేసి, కేవలం అదృష్టం ఎన్నిసార్లు తేడా తెస్తుందో చూడండి.",
    tip5: "మొదలుపెట్టే ముందే మనుషుల సంఖ్య, ప్రాముఖ్యత స్థాయి నిర్ణయించండి; ఫలితం బాగుందని ముందుగానే ఆపకండి.",
    sum_row: "{v}: {r} ({n} లో {c})"
  },
  kn: {
    app_title: "A/B ಟೆಸ್ಟ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    intro: "ನೀವು ಒಂದು ಮೆಸೇಜ್, ಬ್ಯಾನರ್ ಅಥವಾ ಸೂಚನೆಯ ಎರಡು ರೂಪಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿದಿರಿ. B ನಿಜವಾಗಿಯೂ A ಗಿಂತ ಚೆನ್ನಾಗಿ ಮಾಡಿತೇ, ಅಥವಾ ಅದು ಕೇವಲ ಅದೃಷ್ಟವೇ? p-value, ನಂಬಿಕೆಯ ವ್ಯಾಪ್ತಿ, B ಗೆಲ್ಲುವ ಸಾಧ್ಯತೆ ನೋಡಿ, ಎಷ್ಟು ಜನ ಬೇಕು ಎಂದು ಯೋಜಿಸಿ.",
    ex_label: "ಒಂದು ಉದಾಹರಣೆ ನೋಡಿ:",
    ex_whatsapp: "ಎರಡು WhatsApp ಮೆಸೇಜ್‌ಗಳು",
    ex_banner: "ಅಂಗಡಿಯ ಬ್ಯಾನರ್",
    ex_notice: "ಶಾಲಾ ಸೂಚನೆ ನೆನಪೋಲೆ",
    ex_whatsapp_note: "ಒಂದು ಸಿಹಿ ಅಂಗಡಿ 1,000 ಗ್ರಾಹಕರಿಗೆ ಆಫರ್ ಮೆಸೇಜ್ A ಮತ್ತು ಇನ್ನೊಂದು 1,000 ಜನರಿಗೆ ಮೆಸೇಜ್ B ಕಳುಹಿಸಿತು. ಕನ್ವರ್ಷನ್ = ಗ್ರಾಹಕರು ಆರ್ಡರ್ ಮಾಡಲು ಉತ್ತರಿಸಿದರು.",
    ex_banner_note: "ಒಂದು ಆನ್‌ಲೈನ್ ಸೀರೆ ಅಂಗಡಿ ಬಂದವರಿಗೆ ಯಾದೃಚ್ಛಿಕವಾಗಿ (ರ‍್ಯಾಂಡಮ್) ಬ್ಯಾನರ್ A ಅಥವಾ B ತೋರಿಸಿತು. ಕನ್ವರ್ಷನ್ = ಬಂದವರು ಏನಾದರೂ ಖರೀದಿಸಿದರು.",
    ex_notice_note: "ಪೋಷಕರಿಗೆ ಶುಲ್ಕ ನೆನಪೋಲೆ A (ಸರಳ), B (ಕೊನೆಯ ದಿನಾಂಕ ದಪ್ಪ ಅಕ್ಷರದಲ್ಲಿ) ಅಥವಾ C (ಎರಡು ಬಾರಿ ಕಳುಹಿಸಿದ್ದು) ಬಂತು. ಕನ್ವರ್ಷನ್ = ಶುಲ್ಕ ಸಮಯಕ್ಕೆ ಕಟ್ಟಲಾಯಿತು.",
    data_h: "ನಿಮ್ಮ ಟೆಸ್ಟ್ ಫಲಿತಾಂಶಗಳು",
    col_version: "ರೂಪ",
    col_visitors: "ಭೇಟಿಗಾರರು (ನೋಡಿದವರು)",
    col_conv: "ಕನ್ವರ್ಷನ್‌ಗಳು (ಕೆಲಸ ಮಾಡಿದವರು)",
    col_rate: "ಕನ್ವರ್ಷನ್ ದರ",
    ver_a: "ಈಗಿನ ರೂಪ",
    ver_b: "ಹೊಸ ರೂಪ",
    ver_c: "ಇನ್ನೊಂದು ಹೊಸ ರೂಪ",
    add_c: "+ ರೂಪ C ಸೇರಿಸಿ",
    remove_c: "ರೂಪ C ತೆಗೆಯಿರಿ",
    sig_label: "ಮಹತ್ವದ ಮಟ್ಟ",
    sig_5: "5% (ಸಾಮಾನ್ಯ)",
    sig_1: "1% (ಕಟ್ಟುನಿಟ್ಟು)",
    err_blank: "ಪ್ರತಿ ರೂಪಕ್ಕೂ ಭೇಟಿಗಾರರು ಮತ್ತು ಕನ್ವರ್ಷನ್‌ಗಳನ್ನು ತುಂಬಿ.",
    err_bad: "1000 ನಂತಹ ಪೂರ್ಣ ಸಂಖ್ಯೆಗಳನ್ನು ಬರೆಯಿರಿ (ದಶಮಾಂಶ ಅಥವಾ ಮೈನಸ್ ಬೇಡ).",
    err_zero: "ರೂಪ {v}: ಭೇಟಿಗಾರರು ಕನಿಷ್ಠ 1 ಇರಬೇಕು.",
    err_more: "ರೂಪ {v}: ಕನ್ವರ್ಷನ್‌ಗಳು ({c}) ಭೇಟಿಗಾರರಿಗಿಂತ ({n}) ಹೆಚ್ಚಿರಲು ಸಾಧ್ಯವಿಲ್ಲ.",
    copy_result: "ಫಲಿತಾಂಶ ನಕಲಿಸಿ",
    res_h: "ಫಲಿತಾಂಶ",
    res_wait: "ಫಲಿತಾಂಶ ನೋಡಲು ಸಂಖ್ಯೆಗಳನ್ನು ತುಂಬಿ.",
    three_note: "3 ರೂಪಗಳಲ್ಲಿ B ಮತ್ತು C ಎರಡನ್ನೂ A ಜೊತೆ ಹೋಲಿಸಲಾಗುತ್ತದೆ. ತಪ್ಪು ಗೆಲುವುಗಳು ಕಡಿಮೆ ಇರಲು ಪ್ರತಿ ಹೋಲಿಕೆ ಹೆಚ್ಚು ಕಟ್ಟುನಿಟ್ಟಾದ ಮಟ್ಟ ದಾಟಬೇಕು: {a}.",
    cmp_h: "A ಜೊತೆ {v} ಹೋಲಿಕೆ",
    verdict_better: "{v} ಉತ್ತಮ, ಮತ್ತು ಇದು ಅದೃಷ್ಟವಾಗಿರುವ ಸಾಧ್ಯತೆ ಕಡಿಮೆ.",
    verdict_worse: "{v} A ಗಿಂತ ಕೆಟ್ಟದು, ಮತ್ತು ಇದು ಅದೃಷ್ಟವಾಗಿರುವ ಸಾಧ್ಯತೆ ಕಡಿಮೆ.",
    verdict_unsure: "ಇನ್ನೂ ಸಾಕಷ್ಟು ಪುರಾವೆ ಇಲ್ಲ. ಈ ವ್ಯತ್ಯಾಸ ಕೇವಲ ಅದೃಷ್ಟವೂ ಆಗಿರಬಹುದು.",
    verdict_sig_sub: "p-value {p}, ಇದು {a} ಗಿಂತ ಕಡಿಮೆ.",
    verdict_unsure_sub: "p-value {p}, ಇದು {a} ಗಿಂತ ಕಡಿಮೆ ಇಲ್ಲ. ಯೋಜಿಸಿದ ಸಂಖ್ಯೆಯ ಜನ ತಲುಪುವವರೆಗೆ ಟೆಸ್ಟ್ ಮುಂದುವರಿಸಿ.",
    st_diff: "ವ್ಯತ್ಯಾಸ ({v} − A)",
    pts_unit: "ಶೇಕಡಾ ಅಂಕಗಳು",
    st_uplift: "ಸಾಪೇಕ್ಷ ಏರಿಕೆ",
    st_p: "p-value",
    p_need: "{a} ಗಿಂತ ಕಡಿಮೆ ಇದ್ದರೆ ಮಹತ್ವದ್ದು",
    st_ci: "ವ್ಯತ್ಯಾಸದ {c}% ನಂಬಿಕೆಯ ವ್ಯಾಪ್ತಿ",
    st_ci_val: "{lo} ರಿಂದ {hi}",
    st_beat: "{v} A ಯನ್ನು ಸೋಲಿಸುವ ಸಾಧ್ಯತೆ",
    st_beat_sub: "ಬೇಯೆಸಿಯನ್ ಅಂದಾಜು",
    ci_note_pos: "ಇಡೀ ವ್ಯಾಪ್ತಿ 0 ಕ್ಕಿಂತ ಮೇಲಿದೆ, ಆದ್ದರಿಂದ {v} ಬಹುತೇಕ ಖಚಿತವಾಗಿ ಉತ್ತಮ.",
    ci_note_neg: "ಇಡೀ ವ್ಯಾಪ್ತಿ 0 ಕ್ಕಿಂತ ಕೆಳಗಿದೆ, ಆದ್ದರಿಂದ {v} ಬಹುತೇಕ ಖಚಿತವಾಗಿ ಕೆಟ್ಟದು.",
    ci_note_zero: "ವ್ಯಾಪ್ತಿಯಲ್ಲಿ 0 ಇದೆ, ಆದ್ದರಿಂದ \"ನಿಜವಾದ ವ್ಯತ್ಯಾಸ ಇಲ್ಲ\" ಎಂಬುದೂ ಸಾಧ್ಯ.",
    work_h: "ಲೆಕ್ಕ ತೋರಿಸಿ (z-ಟೆಸ್ಟ್)",
    work_pool: "A ಮತ್ತು {v} ಸೇರಿದ ದರ: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "ಪ್ರಮಾಣಿತ ದೋಷ (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = ವ್ಯತ್ಯಾಸ ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = ನಿಜವಾದ ವ್ಯತ್ಯಾಸ ಇಲ್ಲದಿದ್ದರೆ z ಇಷ್ಟು ದೂರ 0 ಯಿಂದ (ಯಾವುದೇ ಕಡೆ) ಬರುವ ಸಾಧ್ಯತೆ = {p}",
    work_ci: "ನಂಬಿಕೆಯ ವ್ಯಾಪ್ತಿ = ವ್ಯತ್ಯಾಸ ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "ಅತ್ಯುತ್ತಮವಾಗಿರುವ ಸಾಧ್ಯತೆ",
    warn_small: "ತುಂಬಾ ಸಣ್ಣ ಮಾದರಿ: ರೂಪ {v} ನಲ್ಲಿ 10 ಕ್ಕಿಂತ ಕಡಿಮೆ ಕನ್ವರ್ಷನ್‌ಗಳು ಅಥವಾ 10 ಕ್ಕಿಂತ ಕಡಿಮೆ ಕನ್ವರ್ಟ್ ಆಗದವರು ಇದ್ದಾರೆ. ಫಲಿತಾಂಶ ತುಂಬಾ ಏರುಪೇರಾಗಬಹುದು. ಇನ್ನಷ್ಟು ಡೇಟಾ ಸಂಗ್ರಹಿಸಿ.",
    warn_split: "ಅಸಮಾನ ಹಂಚಿಕೆ: {s}. ನೀವು ಜನರನ್ನು ಸಮವಾಗಿ ಹಂಚಲು ಬಯಸಿದ್ದರೆ, ಇಷ್ಟು ದೊಡ್ಡ ಅಂತರ ಆಕಸ್ಮಿಕವಾಗಿ ಬರುವುದು ತುಂಬಾ ಕಷ್ಟ. ಯಾರಿಗೆ ಯಾವ ರೂಪ ಹೇಗೆ ಸಿಕ್ಕಿತು ಪರಿಶೀಲಿಸಿ.",
    warn_peek: "ಯೋಜಕ ಹೇಳುವ ಜನರಲ್ಲಿ ({n} ಪ್ರತಿ ರೂಪಕ್ಕೆ) ನಿಮ್ಮ ಬಳಿ ಕೇವಲ {x}% ಇದೆ. ಫಲಿತಾಂಶ ಚೆನ್ನಾಗಿ ಕಂಡ ಕೂಡಲೇ ನಿಲ್ಲಿಸುವುದನ್ನು \"ಇಣುಕಿ ನೋಡುವುದು\" (peeking) ಎನ್ನುತ್ತಾರೆ; ಇದರಿಂದ ಅನೇಕ ತಪ್ಪು ಗೆಲುವುಗಳು ಬರುತ್ತವೆ. ಯೋಜಿಸಿದ ಸಂಖ್ಯೆಗಾಗಿ ಕಾಯಿರಿ.",
    warn_peek_gen: "ಇಣುಕಬೇಡಿ: ಆರಂಭಿಸುವ ಮೊದಲೇ ಎಷ್ಟು ಜನ ಬೇಕು ಎಂದು ನಿರ್ಧರಿಸಿ (ಕೆಳಗೆ ಯೋಜಕ), ಆ ಸಂಖ್ಯೆ ತಲುಪಿದ ಮೇಲೆಯೇ ಫಲಿತಾಂಶ ತೀರ್ಮಾನಿಸಿ.",
    chart_h: "ನಿಜವಾದ ದರ ಬಹುಶಃ ಎಲ್ಲಿದೆ",
    chart_note: "ಪ್ರತಿ ವಕ್ರರೇಖೆ ಒಂದು ರೂಪದ ನಿಜವಾದ ಕನ್ವರ್ಷನ್ ದರದ ನಂಬಲರ್ಹ ಮೌಲ್ಯಗಳನ್ನು ತೋರಿಸುತ್ತದೆ. ರೇಖೆಗಳು ಒಂದರ ಮೇಲೊಂದು ಹೆಚ್ಚು ಬಿದ್ದರೆ, ಟೆಸ್ಟ್ ಇನ್ನೂ ರೂಪಗಳ ವ್ಯತ್ಯಾಸ ಹೇಳಲಾರದು.",
    chart_aria: "ಪ್ರತಿ ರೂಪದ ಸಂಭಾವ್ಯ ನಿಜವಾದ ಕನ್ವರ್ಷನ್ ದರದ ವಕ್ರರೇಖೆಗಳು",
    axis_rate: "ಕನ್ವರ್ಷನ್ ದರ",
    plan_h: "ಮಾದರಿ ಗಾತ್ರ ಯೋಜಕ",
    plan_intro: "ಟೆಸ್ಟ್ ಆರಂಭಿಸುವ ಮೊದಲು: ಪ್ರತಿ ರೂಪವನ್ನು ಎಷ್ಟು ಜನ ನೋಡಬೇಕು?",
    plan_base: "ಈಗಿನ ಕನ್ವರ್ಷನ್ ದರ (%)",
    plan_use_a: "A ದರ ಬಳಸಿ",
    plan_change: "ಪತ್ತೆಹಚ್ಚಬೇಕಾದ ಅತಿ ಸಣ್ಣ ಬದಲಾವಣೆ",
    plan_abs: "ಶೇಕಡಾ ಅಂಕಗಳು",
    plan_rel: "ಈಗಿನ ದರದ %",
    plan_power: "ಪವರ್ (ನಿಜವಾದ ಬದಲಾವಣೆ ಹಿಡಿಯುವ ಸಾಧ್ಯತೆ)",
    plan_sig: "ಮಹತ್ವದ ಮಟ್ಟ",
    plan_versions: "ಟೆಸ್ಟ್‌ನಲ್ಲಿ ರೂಪಗಳು",
    plan_daily: "ದಿನಕ್ಕೆ ಜನ (ಎಲ್ಲ ರೂಪಗಳು ಸೇರಿ)",
    plan_per: "ಪ್ರತಿ ರೂಪಕ್ಕೆ ಜನ",
    plan_total: "ಒಟ್ಟು ಜನ",
    plan_days: "ಎಷ್ಟು ದಿನ ಬೇಕು",
    plan_days_val: "{n} ದಿನಗಳು",
    plan_bad: "ಈಗಿನ ದರವನ್ನು 0 ಮತ್ತು 100 ರ ನಡುವೆ ತುಂಬಿ, ಹೊಸ ದರವೂ 0 ಮತ್ತು 100 ರ ನಡುವೆ ಇರುವಂತೆ ಬದಲಾವಣೆ ನೀಡಿ.",
    plan_target: "ನೀವು {a}% ರಿಂದ {b}% ವರೆಗಿನ ಬದಲಾವಣೆಯನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಬಯಸುತ್ತೀರಿ.",
    plan_3note: "3 ರೂಪಗಳಲ್ಲಿ ಪ್ರತಿ ಹೋಲಿಕೆ ಹೆಚ್ಚು ಕಟ್ಟುನಿಟ್ಟಾದ ಮಟ್ಟ {a} ಬಳಸುತ್ತದೆ.",
    plan_formula: "ಸೂತ್ರ (ಎರಡೂ ಕಡೆಯ ಟೆಸ್ಟ್): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², ಇಲ್ಲಿ p̄ = (p1 + p2) ÷ 2. ಇಲ್ಲಿ z ಮೌಲ್ಯಗಳು {za} ಮತ್ತು {zb}, ಆದ್ದರಿಂದ n = {raw}, ಮೇಲಕ್ಕೆ ಪೂರ್ಣಗೊಳಿಸಿದರೆ {n}.",
    plan_note: "ಸಣ್ಣ ಬದಲಾವಣೆಗೆ ತುಂಬಾ ಹೆಚ್ಚು ಜನ ಬೇಕು: ಅರ್ಧ ಬದಲಾವಣೆ ಪತ್ತೆಹಚ್ಚಲು ಸುಮಾರು 4 ಪಟ್ಟು ಜನ.",
    words_h: "ತಿಳಿಯಬೇಕಾದ ಪದಗಳು",
    w_conv: "ಕನ್ವರ್ಷನ್",
    d_conv: "ನೀವು ಬಯಸುವ ಕೆಲಸ: ಉತ್ತರ, ಖರೀದಿ, ಫಾರ್ಮ್ ತುಂಬುವುದು, ಶುಲ್ಕ ಕಟ್ಟುವುದು, ಕ್ಲಿಕ್.",
    w_rate: "ಕನ್ವರ್ಷನ್ ದರ",
    d_rate: "ಕನ್ವರ್ಷನ್‌ಗಳು ÷ ನೋಡಿದವರು. 1,000 ಭೇಟಿಗಾರರಲ್ಲಿ 250 ಖರೀದಿದಾರರು = 25%.",
    w_uplift: "ಏರಿಕೆ",
    d_uplift: "20% ರಿಂದ 25% ಎಂದರೆ 5 ಶೇಕಡಾ ಅಂಕಗಳ ಏರಿಕೆ, ಅಂದರೆ 25% ಸಾಪೇಕ್ಷ ಏರಿಕೆ (5 ಎಂಬುದು 20 ರ ಕಾಲು ಭಾಗ).",
    w_p: "p-value",
    d_p: "A ಮತ್ತು B ನಿಜವಾಗಿ ಒಂದೇ ಆಗಿದ್ದರೆ, ಕೇವಲ ಅದೃಷ್ಟದಿಂದ ಇಷ್ಟು ದೊಡ್ಡ ವ್ಯತ್ಯಾಸ ಎಷ್ಟು ಬಾರಿ ಬರುತ್ತದೆ? ಸಣ್ಣ p-value (ಉದಾ. 0.01) ಎಂದರೆ ಅದೃಷ್ಟ ಕಾರಣವಾಗಿರುವ ಸಾಧ್ಯತೆ ಕಡಿಮೆ.",
    w_sig: "ಮಹತ್ವದ ಮಟ್ಟ",
    d_sig: "ಟೆಸ್ಟ್‌ಗೆ ಮೊದಲು ಆಯ್ಕೆ ಮಾಡುವ p-value ಮಿತಿ, ಸಾಮಾನ್ಯವಾಗಿ 5%. ಅದಕ್ಕಿಂತ ಕಡಿಮೆ ಇದ್ದರೆ ಫಲಿತಾಂಶ \"ಮಹತ್ವದ್ದು\".",
    w_ci: "ನಂಬಿಕೆಯ ವ್ಯಾಪ್ತಿ",
    d_ci: "ಡೇಟಾಗೆ ಹೊಂದುವ ವ್ಯತ್ಯಾಸಗಳ ವ್ಯಾಪ್ತಿ. ಅದರಲ್ಲಿ 0 ಇಲ್ಲದಿದ್ದರೆ ಫಲಿತಾಂಶ ಮಹತ್ವದ್ದು.",
    w_power: "ಪವರ್",
    d_power: "ನೀವು ಯೋಜಿಸಿದ ಗಾತ್ರದ ನಿಜವಾದ ಬದಲಾವಣೆಯನ್ನು ಟೆಸ್ಟ್ ಹಿಡಿಯುವ ಸಾಧ್ಯತೆ. ಸಾಮಾನ್ಯವಾಗಿ 80%.",
    w_bayes: "B, A ಯನ್ನು ಸೋಲಿಸುವ ಸಾಧ್ಯತೆ",
    d_bayes: "ಅದೇ ಡೇಟಾವನ್ನು ಓದುವ ಇನ್ನೊಂದು ವಿಧಾನ (ಬೇಯೆಸಿಯನ್): B ಯ ನಿಜವಾದ ದರ A ಗಿಂತ ಹೆಚ್ಚಿರುವ ಸಾಧ್ಯತೆ ಎಷ್ಟು?",
    w_peek: "ಇಣುಕಿ ನೋಡುವುದು (peeking)",
    d_peek: "ಮತ್ತೆ ಮತ್ತೆ ಫಲಿತಾಂಶ ನೋಡಿ, ಮಹತ್ವದ್ದಾಗಿ ಕಂಡ ಕೂಡಲೇ ನಿಲ್ಲಿಸುವುದು. ಇದರಿಂದ ತಪ್ಪು ಗೆಲುವುಗಳು ತುಂಬಾ ಹೆಚ್ಚುತ್ತವೆ.",
    help_title: "ಹೇಗೆ ಬಳಸುವುದು / ಆಲೋಚನೆಗಳು",
    tip1: "ಒಂದು ಉದಾಹರಣೆ ಆರಿಸಿ, ಅಥವಾ ಪ್ರತಿ ರೂಪದ ಜನ ಮತ್ತು ಕನ್ವರ್ಷನ್‌ಗಳನ್ನು ಟೈಪ್ ಮಾಡಿ. ಟೈಪ್ ಮಾಡುತ್ತಿದ್ದಂತೆ ಫಲಿತಾಂಶ ಬದಲಾಗುತ್ತದೆ.",
    tip2: "ಕೆಲಸದಲ್ಲಿ: WhatsApp ಆಫರ್‌ನ ಎರಡು ರೂಪಗಳನ್ನು ಗ್ರಾಹಕರ ಪಟ್ಟಿಯ ಯಾದೃಚ್ಛಿಕ ಎರಡು ಅರ್ಧಗಳಿಗೆ ಕಳುಹಿಸಿ ಉತ್ತರಗಳನ್ನು ಎಣಿಸಿ. ಪಟ್ಟಿ ಎಷ್ಟು ದೊಡ್ಡದಿರಬೇಕು ಎಂದು ಮೊದಲು ಯೋಜಕದಲ್ಲಿ ನೋಡಿ.",
    tip3: "ಅಂಗಡಿ ಮತ್ತು ವೆಬ್‌ಸೈಟ್: ಅದೇ ದಿನಗಳಲ್ಲಿ ಬ್ಯಾನರ್ A ಅಥವಾ B ಯಾದೃಚ್ಛಿಕವಾಗಿ ತೋರಿಸಿ (ಈ ವಾರ A, ಮುಂದಿನ ವಾರ B ಅಲ್ಲ), ಒಮ್ಮೆಗೆ ಒಂದೇ ವಿಷಯ ಬದಲಿಸಿ.",
    tip4: "ತರಗತಿಯಲ್ಲಿ: ಅರ್ಧ ತರಗತಿಗೆ ಮನೆಗೆಲಸದ ನೆನಪೋಲೆ A, ಅರ್ಧಕ್ಕೆ B. ಸಮಯಕ್ಕೆ ಕೊಟ್ಟವರನ್ನು ಎಣಿಸಿ, ವ್ಯತ್ಯಾಸ ನಿಜವೇ ಎಂದು ಪರೀಕ್ಷಿಸಿ. ನಂತರ ನಾಣ್ಯ ಚಿಮ್ಮಿಸಿ, ಕೇವಲ ಅದೃಷ್ಟ ಎಷ್ಟು ಬಾರಿ ವ್ಯತ್ಯಾಸ ತರುತ್ತದೆ ನೋಡಿ.",
    tip5: "ಆರಂಭಿಸುವ ಮೊದಲೇ ಜನರ ಸಂಖ್ಯೆ ಮತ್ತು ಮಹತ್ವದ ಮಟ್ಟ ನಿರ್ಧರಿಸಿ; ಫಲಿತಾಂಶ ಚೆನ್ನಾಗಿದೆ ಎಂದು ಬೇಗ ನಿಲ್ಲಿಸಬೇಡಿ.",
    sum_row: "{v}: {r} ({n} ರಲ್ಲಿ {c})"
  },
  ml: {
    app_title: "A/B ടെസ്റ്റ് കാൽക്കുലേറ്റർ",
    intro: "ഒരു മെസേജ്, ബാനർ അല്ലെങ്കിൽ അറിയിപ്പിന്റെ രണ്ട് രൂപങ്ങൾ നിങ്ങൾ പരീക്ഷിച്ചു. B ശരിക്കും A-യെക്കാൾ നന്നായോ, അതോ വെറും ഭാഗ്യമോ? p-value, വിശ്വാസ പരിധി, B ജയിക്കാനുള്ള സാധ്യത എന്നിവ കാണുക, എത്ര പേർ വേണമെന്ന് പ്ലാൻ ചെയ്യുക.",
    ex_label: "ഒരു ഉദാഹരണം നോക്കൂ:",
    ex_whatsapp: "രണ്ട് WhatsApp മെസേജുകൾ",
    ex_banner: "കടയുടെ ബാനർ",
    ex_notice: "സ്കൂൾ അറിയിപ്പ് ഓർമ്മപ്പെടുത്തൽ",
    ex_whatsapp_note: "ഒരു മധുരപലഹാരക്കട 1,000 ഉപഭോക്താക്കൾക്ക് ഓഫർ മെസേജ് A-യും മറ്റൊരു 1,000 പേർക്ക് മെസേജ് B-യും അയച്ചു. കൺവേർഷൻ = ഉപഭോക്താവ് ഓർഡർ ചെയ്യാൻ മറുപടി നൽകി.",
    ex_banner_note: "ഒരു ഓൺലൈൻ സാരിക്കട സന്ദർശകർക്ക് ക്രമമില്ലാതെ (റാൻഡം) ബാനർ A അല്ലെങ്കിൽ B കാണിച്ചു. കൺവേർഷൻ = സന്ദർശകൻ എന്തെങ്കിലും വാങ്ങി.",
    ex_notice_note: "രക്ഷിതാക്കൾക്ക് ഫീസ് ഓർമ്മപ്പെടുത്തൽ A (സാധാരണ), B (അവസാന തീയതി കട്ടിയക്ഷരത്തിൽ) അല്ലെങ്കിൽ C (രണ്ടുതവണ അയച്ചത്) കിട്ടി. കൺവേർഷൻ = ഫീസ് സമയത്ത് അടച്ചു.",
    data_h: "നിങ്ങളുടെ ടെസ്റ്റ് ഫലങ്ങൾ",
    col_version: "രൂപം",
    col_visitors: "സന്ദർശകർ (കണ്ടവർ)",
    col_conv: "കൺവേർഷനുകൾ (പ്രവൃത്തി ചെയ്തവർ)",
    col_rate: "കൺവേർഷൻ നിരക്ക്",
    ver_a: "ഇപ്പോഴത്തെ രൂപം",
    ver_b: "പുതിയ രൂപം",
    ver_c: "മറ്റൊരു പുതിയ രൂപം",
    add_c: "+ രൂപം C ചേർക്കുക",
    remove_c: "രൂപം C നീക്കുക",
    sig_label: "പ്രാധാന്യ നില",
    sig_5: "5% (സാധാരണ)",
    sig_1: "1% (കർശനം)",
    err_blank: "ഓരോ രൂപത്തിനും സന്ദർശകരും കൺവേർഷനുകളും പൂരിപ്പിക്കുക.",
    err_bad: "1000 പോലുള്ള പൂർണ്ണസംഖ്യകൾ എഴുതുക (ദശാംശമോ മൈനസോ വേണ്ട).",
    err_zero: "രൂപം {v}: സന്ദർശകർ കുറഞ്ഞത് 1 വേണം.",
    err_more: "രൂപം {v}: കൺവേർഷനുകൾ ({c}) സന്ദർശകരെക്കാൾ ({n}) കൂടുതലാകാൻ പാടില്ല.",
    copy_result: "ഫലം കോപ്പി ചെയ്യുക",
    res_h: "ഫലം",
    res_wait: "ഫലം കാണാൻ സംഖ്യകൾ പൂരിപ്പിക്കുക.",
    three_note: "3 രൂപങ്ങളിൽ B-യും C-യും A-യുമായി താരതമ്യം ചെയ്യുന്നു. തെറ്റായ വിജയങ്ങൾ കുറയ്ക്കാൻ ഓരോ താരതമ്യവും കൂടുതൽ കർശനമായ നില കടക്കണം: {a}.",
    cmp_h: "{v}, A-യുമായി താരതമ്യം",
    verdict_better: "{v} മികച്ചതാണ്, ഇത് ഭാഗ്യമാകാനുള്ള സാധ്യത കുറവാണ്.",
    verdict_worse: "{v}, A-യെക്കാൾ മോശമാണ്, ഇത് ഭാഗ്യമാകാനുള്ള സാധ്യത കുറവാണ്.",
    verdict_unsure: "ഇതുവരെ മതിയായ തെളിവില്ല. ഈ വ്യത്യാസം വെറും ഭാഗ്യവുമാകാം.",
    verdict_sig_sub: "p-value {p} ആണ്, ഇത് {a}-യിൽ കുറവാണ്.",
    verdict_unsure_sub: "p-value {p} ആണ്, ഇത് {a}-യിൽ കുറവല്ല. പ്ലാൻ ചെയ്ത എണ്ണം ആളുകൾ എത്തുന്നതുവരെ ടെസ്റ്റ് തുടരുക.",
    st_diff: "വ്യത്യാസം ({v} − A)",
    pts_unit: "ശതമാന പോയിന്റുകൾ",
    st_uplift: "ആപേക്ഷിക വർധന",
    st_p: "p-value",
    p_need: "{a}-യിൽ താഴെയെങ്കിൽ പ്രാധാന്യമുള്ളത്",
    st_ci: "വ്യത്യാസത്തിന്റെ {c}% വിശ്വാസ പരിധി",
    st_ci_val: "{lo} മുതൽ {hi} വരെ",
    st_beat: "{v}, A-യെ തോൽപ്പിക്കാനുള്ള സാധ്യത",
    st_beat_sub: "ബെയ്സിയൻ കണക്ക്",
    ci_note_pos: "മുഴുവൻ പരിധിയും 0-ന് മുകളിലാണ്, അതിനാൽ {v} മിക്കവാറും ഉറപ്പായും മികച്ചതാണ്.",
    ci_note_neg: "മുഴുവൻ പരിധിയും 0-ന് താഴെയാണ്, അതിനാൽ {v} മിക്കവാറും ഉറപ്പായും മോശമാണ്.",
    ci_note_zero: "പരിധിയിൽ 0 ഉണ്ട്, അതിനാൽ \"യഥാർഥ വ്യത്യാസമില്ല\" എന്നതും സാധ്യമാണ്.",
    work_h: "കണക്ക് കാണിക്കുക (z-ടെസ്റ്റ്)",
    work_pool: "A-യുടെയും {v}-യുടെയും ചേർന്ന നിരക്ക്: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "സ്റ്റാൻഡേർഡ് എറർ (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = വ്യത്യാസം ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = യഥാർഥ വ്യത്യാസമില്ലെങ്കിൽ z, 0-ൽ നിന്ന് ഇത്ര ദൂരം (ഏത് വശത്തും) വരാനുള്ള സാധ്യത = {p}",
    work_ci: "വിശ്വാസ പരിധി = വ്യത്യാസം ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "ഏറ്റവും മികച്ചതാകാനുള്ള സാധ്യത",
    warn_small: "വളരെ ചെറിയ സാമ്പിൾ: രൂപം {v}-ൽ 10-ൽ കുറവ് കൺവേർഷനുകളോ 10-ൽ കുറവ് കൺവേർട്ട് ചെയ്യാത്തവരോ ആണ്. ഫലങ്ങൾ ഏറെ മാറാം. കൂടുതൽ ഡേറ്റ ശേഖരിക്കുക.",
    warn_split: "തുല്യമല്ലാത്ത വിഭജനം: {s}. ആളുകളെ തുല്യമായി വിഭജിക്കാനാണ് ഉദ്ദേശിച്ചതെങ്കിൽ, ഇത്ര വലിയ വ്യത്യാസം യാദൃച്ഛികമായി വരുന്നത് വളരെ പ്രയാസമാണ്. ആർക്ക് ഏത് രൂപം എങ്ങനെ കിട്ടിയെന്ന് പരിശോധിക്കുക.",
    warn_peek: "പ്ലാനർ പറയുന്ന ആളുകളിൽ ({n} ഓരോ രൂപത്തിനും) നിങ്ങൾക്ക് {x}% മാത്രമേയുള്ളൂ. ഫലം നന്നായി തോന്നുമ്പോൾ തന്നെ നിർത്തുന്നതിനെ \"എത്തിനോക്കൽ\" (peeking) എന്ന് പറയുന്നു; ഇത് ധാരാളം തെറ്റായ വിജയങ്ങൾ നൽകും. പ്ലാൻ ചെയ്ത എണ്ണത്തിനായി കാത്തിരിക്കുക.",
    warn_peek_gen: "എത്തിനോക്കരുത്: തുടങ്ങും മുമ്പ് എത്ര പേർ വേണമെന്ന് തീരുമാനിക്കുക (താഴെ പ്ലാനർ), ആ എണ്ണം എത്തിയ ശേഷം മാത്രം ഫലം വിലയിരുത്തുക.",
    chart_h: "യഥാർഥ നിരക്ക് ഏകദേശം എവിടെ",
    chart_note: "ഓരോ വക്രവും ഒരു രൂപത്തിന്റെ യഥാർഥ കൺവേർഷൻ നിരക്കിന്റെ വിശ്വസനീയമായ മൂല്യങ്ങൾ കാണിക്കുന്നു. വക്രങ്ങൾ പരസ്പരം ഏറെ കയറിനിൽക്കുന്നുവെങ്കിൽ, ടെസ്റ്റിന് ഇതുവരെ രൂപങ്ങളെ വേർതിരിച്ചറിയാനാവില്ല.",
    chart_aria: "ഓരോ രൂപത്തിന്റെയും സാധ്യതയുള്ള യഥാർഥ കൺവേർഷൻ നിരക്കിന്റെ വക്രങ്ങൾ",
    axis_rate: "കൺവേർഷൻ നിരക്ക്",
    plan_h: "സാമ്പിൾ വലുപ്പ പ്ലാനർ",
    plan_intro: "ടെസ്റ്റ് തുടങ്ങും മുമ്പ്: ഓരോ രൂപവും എത്ര പേർ കാണണം?",
    plan_base: "ഇപ്പോഴത്തെ കൺവേർഷൻ നിരക്ക് (%)",
    plan_use_a: "A-യുടെ നിരക്ക് എടുക്കുക",
    plan_change: "കണ്ടെത്തേണ്ട ഏറ്റവും ചെറിയ മാറ്റം",
    plan_abs: "ശതമാന പോയിന്റുകൾ",
    plan_rel: "ഇപ്പോഴത്തെ നിരക്കിന്റെ %",
    plan_power: "പവർ (യഥാർഥ മാറ്റം പിടിക്കാനുള്ള സാധ്യത)",
    plan_sig: "പ്രാധാന്യ നില",
    plan_versions: "ടെസ്റ്റിലെ രൂപങ്ങൾ",
    plan_daily: "ദിവസേന ആളുകൾ (എല്ലാ രൂപങ്ങളും ചേർത്ത്)",
    plan_per: "ഓരോ രൂപത്തിനും ആളുകൾ",
    plan_total: "ആകെ ആളുകൾ",
    plan_days: "വേണ്ട ദിവസങ്ങൾ",
    plan_days_val: "{n} ദിവസം",
    plan_bad: "ഇപ്പോഴത്തെ നിരക്ക് 0-നും 100-നും ഇടയിൽ നൽകുക, പുതിയ നിരക്കും 0-നും 100-നും ഇടയിൽ വരുന്ന മാറ്റം നൽകുക.",
    plan_target: "നിങ്ങൾ {a}%-ൽ നിന്ന് {b}%-ലേക്കുള്ള മാറ്റം കണ്ടെത്താൻ ആഗ്രഹിക്കുന്നു.",
    plan_3note: "3 രൂപങ്ങളിൽ ഓരോ താരതമ്യവും കൂടുതൽ കർശനമായ നില {a} ഉപയോഗിക്കുന്നു.",
    plan_formula: "സൂത്രവാക്യം (ഇരുവശ ടെസ്റ്റ്): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)², ഇവിടെ p̄ = (p1 + p2) ÷ 2. ഇവിടെ z മൂല്യങ്ങൾ {za}, {zb} ആണ്, അതിനാൽ n = {raw}, മുകളിലേക്ക് പൂർണ്ണമാക്കിയാൽ {n}.",
    plan_note: "ചെറിയ മാറ്റത്തിന് വളരെ കൂടുതൽ ആളുകൾ വേണം: പകുതി മാറ്റം കണ്ടെത്താൻ ഏകദേശം 4 മടങ്ങ് ആളുകൾ.",
    words_h: "അറിയേണ്ട വാക്കുകൾ",
    w_conv: "കൺവേർഷൻ",
    d_conv: "നിങ്ങൾ ആഗ്രഹിക്കുന്ന പ്രവൃത്തി: മറുപടി, വാങ്ങൽ, ഫോം പൂരിപ്പിക്കൽ, ഫീസ് അടയ്ക്കൽ, ക്ലിക്ക്.",
    w_rate: "കൺവേർഷൻ നിരക്ക്",
    d_rate: "കൺവേർഷനുകൾ ÷ കണ്ടവർ. 1,000 സന്ദർശകരിൽ 250 വാങ്ങുന്നവർ = 25%.",
    w_uplift: "വർധന",
    d_uplift: "20%-ൽ നിന്ന് 25% എന്നത് 5 ശതമാന പോയിന്റ് വർധനയാണ്, അതായത് 25% ആപേക്ഷിക വർധന (5 എന്നത് 20-ന്റെ നാലിലൊന്ന്).",
    w_p: "p-value",
    d_p: "A-യും B-യും ശരിക്കും ഒന്നാണെങ്കിൽ, ഭാഗ്യം കൊണ്ടുമാത്രം ഇത്ര വലിയ വ്യത്യാസം എത്ര തവണ വരും? ചെറിയ p-value (ഉദാ. 0.01) എന്നാൽ ഭാഗ്യം കാരണമാകാൻ സാധ്യത കുറവ്.",
    w_sig: "പ്രാധാന്യ നില",
    d_sig: "ടെസ്റ്റിന് മുമ്പ് തിരഞ്ഞെടുക്കുന്ന p-value പരിധി, സാധാരണ 5%. അതിൽ താഴെയെങ്കിൽ ഫലം \"പ്രാധാന്യമുള്ളത്\".",
    w_ci: "വിശ്വാസ പരിധി",
    d_ci: "ഡേറ്റയുമായി യോജിക്കുന്ന വ്യത്യാസങ്ങളുടെ പരിധി. അതിൽ 0 ഇല്ലെങ്കിൽ ഫലം പ്രാധാന്യമുള്ളതാണ്.",
    w_power: "പവർ",
    d_power: "നിങ്ങൾ പ്ലാൻ ചെയ്ത വലുപ്പത്തിലുള്ള യഥാർഥ മാറ്റം ടെസ്റ്റ് പിടിക്കാനുള്ള സാധ്യത. സാധാരണ 80%.",
    w_bayes: "B, A-യെ തോൽപ്പിക്കാനുള്ള സാധ്യത",
    d_bayes: "അതേ ഡേറ്റ വായിക്കാനുള്ള മറ്റൊരു വഴി (ബെയ്സിയൻ): B-യുടെ യഥാർഥ നിരക്ക് A-യുടേതിനെക്കാൾ കൂടുതലാകാനുള്ള സാധ്യത എത്ര?",
    w_peek: "എത്തിനോക്കൽ (peeking)",
    d_peek: "വീണ്ടും വീണ്ടും ഫലം നോക്കി, പ്രാധാന്യമുള്ളതായി തോന്നുമ്പോൾ തന്നെ നിർത്തുന്നത്. ഇത് തെറ്റായ വിജയങ്ങൾ വളരെ കൂട്ടും.",
    help_title: "എങ്ങനെ ഉപയോഗിക്കാം / ആശയങ്ങൾ",
    tip1: "ഒരു ഉദാഹരണം തിരഞ്ഞെടുക്കുക, അല്ലെങ്കിൽ ഓരോ രൂപത്തിന്റെയും ആളുകളും കൺവേർഷനുകളും ടൈപ്പ് ചെയ്യുക. ടൈപ്പ് ചെയ്യുമ്പോൾ തന്നെ ഫലം മാറും.",
    tip2: "ജോലിയിൽ: WhatsApp ഓഫറിന്റെ രണ്ട് രൂപങ്ങൾ ഉപഭോക്തൃ പട്ടികയുടെ ക്രമമില്ലാത്ത രണ്ട് പകുതികൾക്ക് അയച്ച് മറുപടികൾ എണ്ണുക. പട്ടിക എത്ര വലുതാകണമെന്ന് ആദ്യം പ്ലാനറിൽ നോക്കുക.",
    tip3: "കടകളും വെബ്സൈറ്റുകളും: അതേ ദിവസങ്ങളിൽ ബാനർ A അല്ലെങ്കിൽ B ക്രമമില്ലാതെ കാണിക്കുക (ഈ ആഴ്ച A, അടുത്ത ആഴ്ച B എന്നല്ല), ഒരു സമയം ഒരു കാര്യം മാത്രം മാറ്റുക.",
    tip4: "ക്ലാസിൽ: പകുതി ക്ലാസിന് ഹോംവർക്ക് ഓർമ്മപ്പെടുത്തൽ A, പകുതിക്ക് B. സമയത്ത് നൽകിയവരെ എണ്ണി, വ്യത്യാസം യഥാർഥമാണോ എന്ന് പരിശോധിക്കുക. പിന്നെ നാണയം എറിഞ്ഞ്, വെറും ഭാഗ്യം എത്ര തവണ വ്യത്യാസം ഉണ്ടാക്കുന്നുവെന്ന് കാണുക.",
    tip5: "തുടങ്ങും മുമ്പ് ആളുകളുടെ എണ്ണവും പ്രാധാന്യ നിലയും തീരുമാനിക്കുക; ഫലം നന്നായി തോന്നിയെന്നുവെച്ച് നേരത്തെ നിർത്തരുത്.",
    sum_row: "{v}: {r} ({n}-ൽ {c})"
  },
  ur: {
    app_title: "A/B ٹیسٹ کیلکولیٹر",
    intro: "آپ نے کسی میسج، بینر یا نوٹس کی دو شکلیں آزمائیں۔ کیا B واقعی A سے بہتر رہا، یا یہ صرف قسمت تھی؟ p-value، بھروسے کی حد، B کے جیتنے کا امکان دیکھیں، اور طے کریں کہ کتنے لوگ چاہئیں۔",
    ex_label: "ایک مثال آزمائیں:",
    ex_whatsapp: "دو WhatsApp میسج",
    ex_banner: "دکان کا بینر",
    ex_notice: "اسکول نوٹس کی یاد دہانی",
    ex_whatsapp_note: "ایک مٹھائی کی دکان نے 1,000 گاہکوں کو آفر میسج A اور دوسرے 1,000 کو میسج B بھیجا۔ کنورژن = گاہک نے آرڈر کے لیے جواب دیا۔",
    ex_banner_note: "ایک آن لائن ساڑی کی دکان نے آنے والوں کو بلا ترتیب (رینڈم) بینر A یا B دکھایا۔ کنورژن = آنے والے نے کچھ خریدا۔",
    ex_notice_note: "والدین کو فیس کی یاد دہانی A (سادہ)، B (آخری تاریخ موٹے حروف میں) یا C (دو بار بھیجی گئی) ملی۔ کنورژن = فیس وقت پر جمع ہوئی۔",
    data_h: "آپ کے ٹیسٹ کے نتائج",
    col_version: "شکل",
    col_visitors: "وزیٹر (جنہوں نے دیکھا)",
    col_conv: "کنورژن (جنہوں نے کام کیا)",
    col_rate: "کنورژن کی شرح",
    ver_a: "موجودہ شکل",
    ver_b: "نئی شکل",
    ver_c: "ایک اور نئی شکل",
    add_c: "+ شکل C شامل کریں",
    remove_c: "شکل C ہٹائیں",
    sig_label: "اہمیت کی سطح",
    sig_5: "5% (عام)",
    sig_1: "1% (سخت)",
    err_blank: "ہر شکل کے لیے وزیٹر اور کنورژن بھریں۔",
    err_bad: "1000 جیسے پورے عدد لکھیں (اعشاریہ یا منفی نہیں)۔",
    err_zero: "شکل {v}: وزیٹر کم از کم 1 ہونے چاہئیں۔",
    err_more: "شکل {v}: کنورژن ({c}) وزیٹرز ({n}) سے زیادہ نہیں ہو سکتے۔",
    copy_result: "نتیجہ کاپی کریں",
    res_h: "نتیجہ",
    res_wait: "نتیجہ دیکھنے کے لیے اعداد بھریں۔",
    three_note: "3 شکلوں میں B اور C دونوں کا موازنہ A سے ہوتا ہے۔ جھوٹی جیت کم رہے، اس لیے ہر موازنے کو زیادہ سخت سطح پار کرنی ہوگی: {a}۔",
    cmp_h: "{v} کا A سے موازنہ",
    verdict_better: "{v} بہتر ہے، اور اس کے قسمت ہونے کا امکان کم ہے۔",
    verdict_worse: "{v} A سے خراب ہے، اور اس کے قسمت ہونے کا امکان کم ہے۔",
    verdict_unsure: "ابھی کافی ثبوت نہیں ہے۔ یہ فرق صرف قسمت بھی ہو سکتا ہے۔",
    verdict_sig_sub: "p-value {p} ہے، جو {a} سے کم ہے۔",
    verdict_unsure_sub: "p-value {p} ہے، جو {a} سے کم نہیں۔ طے شدہ تعداد میں لوگ پورے ہونے تک ٹیسٹ چلاتے رہیں۔",
    st_diff: "فرق ({v} − A)",
    pts_unit: "فیصد پوائنٹ",
    st_uplift: "نسبتی اضافہ",
    st_p: "p-value",
    p_need: "{a} سے کم ہو تو اہم",
    st_ci: "فرق کی {c}% بھروسے کی حد",
    st_ci_val: "{lo} سے {hi}",
    st_beat: "{v} کے A سے آگے ہونے کا امکان",
    st_beat_sub: "بیزین اندازہ",
    ci_note_pos: "پوری حد 0 سے اوپر ہے، اس لیے {v} تقریباً یقینی طور پر بہتر ہے۔",
    ci_note_neg: "پوری حد 0 سے نیچے ہے، اس لیے {v} تقریباً یقینی طور پر خراب ہے۔",
    ci_note_zero: "حد میں 0 شامل ہے، اس لیے \"کوئی اصل فرق نہیں\" بھی ممکن ہے۔",
    work_h: "حل دیکھیں (z-ٹیسٹ)",
    work_pool: "A اور {v} کی ملی جلی شرح: ({ca} + {cb}) ÷ ({na} + {nb}) = {p}",
    work_se: "معیاری غلطی (SE) = √(p × (1 − p) × (1/{na} + 1/{nb})) = {se}",
    work_z: "z = فرق ÷ SE = {d} ÷ {se} = {z}",
    work_p: "p-value = اگر کوئی اصل فرق نہ ہو تو z کے 0 سے اتنا دور (کسی بھی طرف) آنے کا امکان = {p}",
    work_ci: "بھروسے کی حد = فرق ± {zc} × √(pA(1 − pA)/nA + pB(1 − pB)/nB) = {d} ± {m}",
    st_best: "سب سے بہتر ہونے کا امکان",
    warn_small: "بہت چھوٹا نمونہ: شکل {v} میں 10 سے کم کنورژن یا 10 سے کم بغیر کنورژن ہیں۔ نتائج بہت اوپر نیچے ہو سکتے ہیں۔ مزید ڈیٹا جمع کریں۔",
    warn_split: "تقسیم برابر نہیں: {s}۔ اگر آپ لوگوں کو برابر بانٹنا چاہتے تھے تو اتنا بڑا فرق اتفاق سے آنا بہت مشکل ہے۔ جانچیں کہ کس کو کون سی شکل کیسے ملی۔",
    warn_peek: "پلانر کے بتائے لوگوں ({n} ہر شکل میں) میں سے آپ کے پاس صرف {x}% ہیں۔ نتیجہ اچھا لگتے ہی ٹیسٹ روک دینا \"جھانکنا\" (peeking) کہلاتا ہے، اور اس سے کئی جھوٹی جیتیں ملتی ہیں۔ طے شدہ تعداد کا انتظار کریں۔",
    warn_peek_gen: "جھانکیں نہیں: شروع کرنے سے پہلے طے کریں کہ کتنے لوگ چاہئیں (نیچے پلانر)، اور اتنے لوگ پورے ہونے پر ہی نتیجہ دیکھیں۔",
    chart_h: "اصل شرح شاید کہاں ہے",
    chart_note: "ہر خم کسی شکل کی اصل کنورژن شرح کی قابلِ یقین قیمتیں دکھاتا ہے۔ اگر خم ایک دوسرے پر بہت چڑھے ہوں تو ٹیسٹ ابھی شکلوں میں فرق نہیں بتا سکتا۔",
    chart_aria: "ہر شکل کی ممکنہ اصل کنورژن شرح کے خم",
    axis_rate: "کنورژن کی شرح",
    plan_h: "نمونے کے سائز کا پلانر",
    plan_intro: "ٹیسٹ شروع کرنے سے پہلے: ہر شکل کتنے لوگوں کو دکھانی چاہیے؟",
    plan_base: "ابھی کی کنورژن شرح (%)",
    plan_use_a: "A کی شرح لیں",
    plan_change: "سب سے چھوٹی تبدیلی جو پکڑنی ہے",
    plan_abs: "فیصد پوائنٹ",
    plan_rel: "ابھی کی شرح کا %",
    plan_power: "پاور (اصل تبدیلی پکڑنے کا امکان)",
    plan_sig: "اہمیت کی سطح",
    plan_versions: "ٹیسٹ میں شکلیں",
    plan_daily: "روزانہ لوگ (سب شکلیں ملا کر)",
    plan_per: "ہر شکل کے لیے لوگ",
    plan_total: "کل لوگ",
    plan_days: "کتنے دن لگیں گے",
    plan_days_val: "{n} دن",
    plan_bad: "ابھی کی شرح 0 اور 100 کے بیچ بھریں، اور ایسی تبدیلی دیں کہ نئی شرح بھی 0 اور 100 کے بیچ رہے۔",
    plan_target: "آپ {a}% سے {b}% کی تبدیلی پکڑنا چاہتے ہیں۔",
    plan_3note: "3 شکلوں میں ہر موازنہ زیادہ سخت سطح {a} استعمال کرتا ہے۔",
    plan_formula: "فارمولا (دونوں طرف کا ٹیسٹ): n = [z(1−α/2)·√(2·p̄·(1−p̄)) + z(power)·√(p1(1−p1) + p2(1−p2))]² ÷ (p2 − p1)²، جہاں p̄ = (p1 + p2) ÷ 2۔ یہاں z کی قیمتیں {za} اور {zb} ہیں، تو n = {raw}، اوپر کی طرف پورا کر کے {n}۔",
    plan_note: "چھوٹی تبدیلی کے لیے بہت زیادہ لوگ چاہئیں: آدھی تبدیلی پکڑنے کے لیے تقریباً 4 گنا لوگ۔",
    words_h: "ضروری الفاظ",
    w_conv: "کنورژن",
    d_conv: "جو کام آپ چاہتے ہیں: جواب، خریداری، فارم بھرنا، فیس جمع کرنا، کلک۔",
    w_rate: "کنورژن کی شرح",
    d_rate: "کنورژن ÷ دیکھنے والے لوگ۔ 1,000 وزیٹرز میں 250 خریدار = 25%۔",
    w_uplift: "اضافہ",
    d_uplift: "20% سے 25% ہونا 5 فیصد پوائنٹ کا اضافہ ہے، یعنی 25% نسبتی اضافہ (5، 20 کا ایک چوتھائی ہے)۔",
    w_p: "p-value",
    d_p: "اگر A اور B واقعی ایک جیسے ہوں تو صرف قسمت سے اتنا بڑا فرق کتنی بار آئے گا؟ چھوٹا p-value (جیسے 0.01) یعنی قسمت والی بات مشکل ہے۔",
    w_sig: "اہمیت کی سطح",
    d_sig: "p-value کی حد جو آپ ٹیسٹ سے پہلے چنتے ہیں، عام طور پر 5%۔ اس سے کم ہو تو نتیجہ \"اہم\" کہلاتا ہے۔",
    w_ci: "بھروسے کی حد",
    d_ci: "فرق کی وہ قیمتیں جو ڈیٹا سے میل کھاتی ہیں۔ اگر اس میں 0 نہیں تو نتیجہ اہم ہے۔",
    w_power: "پاور",
    d_power: "یہ امکان کہ آپ کا ٹیسٹ اتنی اصل تبدیلی پکڑ لے جتنی آپ نے سوچی تھی۔ عام طور پر 80%۔",
    w_bayes: "B کے A سے آگے ہونے کا امکان",
    d_bayes: "اسی ڈیٹا کو پڑھنے کا دوسرا طریقہ (بیزین): کتنا امکان ہے کہ B کی اصل شرح A سے زیادہ ہے؟",
    w_peek: "جھانکنا (peeking)",
    d_peek: "بار بار نتیجہ دیکھنا اور اہم لگتے ہی روک دینا۔ اس سے جھوٹی جیتیں بہت بڑھ جاتی ہیں۔",
    help_title: "استعمال کا طریقہ / تجاویز",
    tip1: "کوئی مثال چنیں، یا ہر شکل کے لوگ اور کنورژن لکھیں۔ لکھتے ہی نتیجہ بدلتا ہے۔",
    tip2: "کام پر: WhatsApp آفر کی دو شکلیں گاہکوں کی فہرست کے دو بلا ترتیب آدھے حصوں کو بھیجیں اور جواب گنیں۔ پہلے پلانر میں دیکھیں کہ فہرست کتنی بڑی ہونی چاہیے۔",
    tip3: "دکانیں اور ویب سائٹس: انہی دنوں میں بینر A یا B بلا ترتیب دکھائیں (اس ہفتے A اور اگلے ہفتے B نہیں)، اور ایک وقت میں ایک ہی چیز بدلیں۔",
    tip4: "کلاس میں: آدھی کلاس کو ہوم ورک کی یاد دہانی A ملے، آدھی کو B۔ گنیں کس نے وقت پر جمع کیا اور جانچیں کہ فرق اصل ہے یا نہیں۔ پھر سکے اچھال کر دیکھیں کہ صرف قسمت کتنی بار فرق پیدا کر دیتی ہے۔",
    tip5: "شروع کرنے سے پہلے لوگوں کی تعداد اور اہمیت کی سطح طے کریں، اور نتیجہ اچھا لگنے پر جلدی نہ روکیں۔",
    sum_row: "{v}: {r} ({n} میں سے {c})"
  }
};
