/* Classroom Timer: UI strings for all 12 languages (identical keys everywhere).
   Shared words (reset, full screen, ...) come from EDU.COMMON. */
window.APP_STRINGS = {
  en: {
    app_title: 'Classroom Timer',
    intro: 'Big, clear timers for your class: countdown, stopwatch, Pomodoro and work-mode signs. Students learn to plan their time and always know what is expected.',
    tabs_label: 'Type of timer',
    tab_countdown: 'Countdown', tab_stopwatch: 'Stopwatch', tab_pomodoro: 'Pomodoro', tab_signs: 'Work mode',
    quick_times: 'Quick times', min_short: 'min', min_n: '{n} minutes',
    custom_time: 'Your own time', hours: 'Hours', minutes: 'Minutes', seconds: 'Seconds', set_time: 'Set',
    enter_time: 'Please enter a time greater than zero.',
    add_minute: '+1 min',
    activity_ph: 'What are we doing? (e.g. Silent reading)', activity_label: 'Activity name',
    btn_start: 'Start', btn_pause: 'Pause', btn_resume: 'Resume',
    st_ready: 'Ready', st_running: 'Running', st_paused: 'Paused', ends_at: 'Ends at {time}',
    times_up: "Time's up!", over_by: 'Over by {t}', start_again: 'Start again', exit_fullscreen: 'Exit full screen',
    sound: 'Alarm sound', sound_bell: 'Bell', sound_beeps: 'Beeps', sound_gong: 'Deep gong', sound_off: 'No sound', test_sound: 'Test sound',
    no_audio: 'Sound is not available in this browser.',
    warn_minute: 'Soft beep when 1 minute is left',
    keys_cd: 'Keyboard: <kbd>Space</kbd> start / pause · <kbd>R</kbd> reset · <kbd>F</kbd> full screen',
    lap: 'Lap', lap_n: 'Lap {n}', laps: 'Laps', lap_time: 'Lap time', lap_secs: 'Lap time (seconds)', total_time: 'Total time',
    no_laps: 'Press Lap while the stopwatch runs to save each time: for races, science experiments or reading speed.',
    laps_count: 'Laps: {n}', average: 'Average lap: {t}', fastest: 'Fastest', slowest: 'Slowest', download_csv: 'Download CSV',
    keys_sw: 'Keyboard: <kbd>Space</kbd> start / pause · <kbd>L</kbd> lap · <kbd>R</kbd> reset · <kbd>F</kbd> full screen',
    phase_work: 'Focus time', phase_short: 'Short break', phase_long: 'Long break', session_of: 'Session {n} of {m}', skip: 'Skip',
    plans: 'Ready-made plans', plan_classic: 'Classic · 25 + 5', plan_class: 'One period · 20 + 5', plan_exam: 'Exam study · 50 + 10', plan_young: 'Young learners · 10 + 2',
    po_settings: 'Your own plan', work_len: 'Focus (minutes)', short_len: 'Short break (minutes)', long_len: 'Long break (minutes)', long_every: 'Sessions before a long break',
    auto_next: 'Start the next part automatically',
    po_stats: 'Focus sessions done: {n} · Total focus: {m} min',
    po_what: 'Pomodoro method: work on one task with full focus for a fixed time, then take a short break. After a few sessions, take a longer break.',
    po_work_over: 'Focus time is over. Take a break!', po_break_over: 'Break is over. Back to work!', po_next_note: 'New times will apply from the next part.',
    choose_sign: 'Choose a sign for the class', voice_level: 'Voice level {n}', time_left: 'Time left: {t}',
    print_sign: 'Print this sign', print_all: 'Print all signs',
    keys_sg: 'Keyboard: <kbd>1</kbd>–<kbd>8</kbd> change the sign · <kbd>Space</kbd> start / pause the countdown · <kbd>F</kbd> full screen',
    sign_silent: 'Silent work', sign_silent_d: 'No talking. Do your own work.',
    sign_whisper: 'Whisper', sign_whisper_d: 'Talk very softly, only if you must.',
    sign_partner: 'Partner talk', sign_partner_d: 'Talk quietly with the person next to you.',
    sign_group: 'Group work', sign_group_d: 'Discuss in your group. Use an inside voice.',
    sign_hands: 'Hands up', sign_hands_d: 'Raise your hand and wait for your turn to speak.',
    sign_listen: 'Eyes on me', sign_listen_d: 'Stop, look at the teacher and listen carefully.',
    sign_tidy: 'Tidy up', sign_tidy_d: 'Put your things away and clean your desk.',
    sign_stretch: 'Stretch break', sign_stretch_d: 'Stand up, stretch your arms and take a deep breath.',
    help_title: 'How to use / Ideas for the classroom',
    tip1: 'Tap a quick time (or type your own) and press Start. The ring turns orange in the last minute and red when time is up, with a gentle alarm.',
    tip2: 'Press Full screen to show the timer on a projector or smartboard. Keys: Space = start / pause, R = reset, F = full screen.',
    tip3: 'The timer keeps the correct time even if you switch tabs or the screen sleeps, and the browser tab shows the time left.',
    tip4: 'Classroom activity (Think–Pair–Share): show "Silent work" with a 2-minute countdown for thinking, then "Partner talk" for 3 minutes, then "Hands up" to share answers.',
    tip5: 'Science or PE: use Stopwatch laps to time 10 swings of a pendulum, a 100 m race or reading speed. Download the times as CSV and open them in Excel.',
    tip6: 'Self-study with Pomodoro: 25 minutes of focus + 5 minutes of break. After 4 sessions, take a longer break.'
  },

  hi: {
    app_title: 'कक्षा टाइमर',
    intro: 'कक्षा के लिए बड़े और साफ़ टाइमर: उल्टी गिनती, स्टॉपवॉच, पोमोडोरो और काम के तरीके वाले बोर्ड। बच्चे समय की योजना बनाना सीखते हैं और हमेशा जानते हैं कि अभी क्या करना है।',
    tabs_label: 'टाइमर का प्रकार',
    tab_countdown: 'उल्टी गिनती', tab_stopwatch: 'स्टॉपवॉच', tab_pomodoro: 'पोमोडोरो', tab_signs: 'काम का तरीका',
    quick_times: 'झटपट समय', min_short: 'मिनट', min_n: '{n} मिनट',
    custom_time: 'अपना समय', hours: 'घंटे', minutes: 'मिनट', seconds: 'सेकंड', set_time: 'सेट करें',
    enter_time: 'कृपया शून्य से ज़्यादा समय डालें।',
    add_minute: '+1 मिनट',
    activity_ph: 'अभी क्या कर रहे हैं? (जैसे: चुपचाप पढ़ना)', activity_label: 'गतिविधि का नाम',
    btn_start: 'शुरू करें', btn_pause: 'रोकें', btn_resume: 'फिर से शुरू',
    st_ready: 'तैयार', st_running: 'चल रहा है', st_paused: 'रुका हुआ', ends_at: '{time} पर खत्म',
    times_up: 'समय पूरा!', over_by: '{t} ज़्यादा हो गए', start_again: 'फिर से शुरू करें', exit_fullscreen: 'पूरी स्क्रीन बंद करें',
    sound: 'अलार्म की आवाज़', sound_bell: 'घंटी', sound_beeps: 'बीप', sound_gong: 'गहरा घंटा', sound_off: 'कोई आवाज़ नहीं', test_sound: 'सुनकर देखें',
    no_audio: 'इस ब्राउज़र में आवाज़ नहीं चल सकती।',
    warn_minute: '1 मिनट बचने पर धीमी बीप',
    keys_cd: 'कीबोर्ड: <kbd>Space</kbd> शुरू / रोकें · <kbd>R</kbd> रीसेट · <kbd>F</kbd> पूरी स्क्रीन',
    lap: 'लैप', lap_n: 'लैप {n}', laps: 'लैप्स', lap_time: 'लैप का समय', lap_secs: 'लैप का समय (सेकंड)', total_time: 'कुल समय',
    no_laps: 'स्टॉपवॉच चलते समय ‘लैप’ दबाएँ, हर समय सेव हो जाएगा: दौड़, विज्ञान के प्रयोग या पढ़ने की गति के लिए।',
    laps_count: 'लैप: {n}', average: 'औसत लैप: {t}', fastest: 'सबसे तेज़', slowest: 'सबसे धीमा', download_csv: 'CSV डाउनलोड करें',
    keys_sw: 'कीबोर्ड: <kbd>Space</kbd> शुरू / रोकें · <kbd>L</kbd> लैप · <kbd>R</kbd> रीसेट · <kbd>F</kbd> पूरी स्क्रीन',
    phase_work: 'ध्यान का समय', phase_short: 'छोटा ब्रेक', phase_long: 'लंबा ब्रेक', session_of: 'सत्र {n} ({m} में से)', skip: 'छोड़ें',
    plans: 'तैयार योजनाएँ', plan_classic: 'क्लासिक · 25 + 5', plan_class: 'एक पीरियड · 20 + 5', plan_exam: 'परीक्षा की पढ़ाई · 50 + 10', plan_young: 'छोटे बच्चे · 10 + 2',
    po_settings: 'अपनी योजना', work_len: 'ध्यान (मिनट)', short_len: 'छोटा ब्रेक (मिनट)', long_len: 'लंबा ब्रेक (मिनट)', long_every: 'कितने सत्र बाद लंबा ब्रेक',
    auto_next: 'अगला हिस्सा अपने-आप शुरू करें',
    po_stats: 'पूरे हुए सत्र: {n} · कुल ध्यान: {m} मिनट',
    po_what: 'पोमोडोरो तरीका: तय समय तक एक ही काम पर पूरा ध्यान लगाएँ, फिर छोटा ब्रेक लें। कुछ सत्रों के बाद लंबा ब्रेक लें।',
    po_work_over: 'ध्यान का समय पूरा हुआ। अब ब्रेक लें!', po_break_over: 'ब्रेक खत्म। फिर से काम पर लौटें!', po_next_note: 'नया समय अगले हिस्से से लागू होगा।',
    choose_sign: 'कक्षा के लिए बोर्ड चुनें', voice_level: 'आवाज़ का स्तर {n}', time_left: 'बचा समय: {t}',
    print_sign: 'यह बोर्ड प्रिंट करें', print_all: 'सभी बोर्ड प्रिंट करें',
    keys_sg: 'कीबोर्ड: <kbd>1</kbd>–<kbd>8</kbd> बोर्ड बदलें · <kbd>Space</kbd> उल्टी गिनती शुरू / रोकें · <kbd>F</kbd> पूरी स्क्रीन',
    sign_silent: 'चुपचाप काम', sign_silent_d: 'बात नहीं करनी है। अपना काम खुद करें।',
    sign_whisper: 'धीमी आवाज़', sign_whisper_d: 'ज़रूरत हो तभी, बहुत धीरे बोलें।',
    sign_partner: 'साथी से बात', sign_partner_d: 'बगल में बैठे साथी से धीरे बात करें।',
    sign_group: 'समूह में काम', sign_group_d: 'अपने समूह में चर्चा करें। आवाज़ धीमी रखें।',
    sign_hands: 'हाथ उठाएँ', sign_hands_d: 'हाथ उठाएँ और बोलने के लिए अपनी बारी का इंतज़ार करें।',
    sign_listen: 'मेरी ओर देखें', sign_listen_d: 'रुकें, शिक्षक की ओर देखें और ध्यान से सुनें।',
    sign_tidy: 'सफ़ाई का समय', sign_tidy_d: 'अपना सामान रखें और डेस्क साफ़ करें।',
    sign_stretch: 'थोड़ा व्यायाम', sign_stretch_d: 'खड़े हों, हाथ फैलाएँ और गहरी साँस लें।',
    help_title: 'कैसे इस्तेमाल करें / कक्षा के लिए सुझाव',
    tip1: 'कोई झटपट समय चुनें (या अपना समय लिखें) और ‘शुरू करें’ दबाएँ। आखिरी मिनट में घेरा नारंगी और समय पूरा होने पर लाल हो जाता है, साथ में हल्का अलार्म बजता है।',
    tip2: 'प्रोजेक्टर या स्मार्टबोर्ड पर दिखाने के लिए ‘पूरी स्क्रीन’ दबाएँ। कीबोर्ड: Space = शुरू / रोकें, R = रीसेट, F = पूरी स्क्रीन।',
    tip3: 'दूसरा टैब खोलने या स्क्रीन बंद होने पर भी टाइमर सही समय रखता है, और ब्राउज़र टैब पर बचा हुआ समय दिखता है।',
    tip4: 'कक्षा गतिविधि (सोचो–जोड़ी में बोलो–सबको बताओ): सोचने के लिए 2 मिनट की उल्टी गिनती के साथ ‘चुपचाप काम’ दिखाएँ, फिर 3 मिनट ‘साथी से बात’, फिर जवाब बताने के लिए ‘हाथ उठाएँ’।',
    tip5: 'विज्ञान या खेल: स्टॉपवॉच के लैप से पेंडुलम के 10 झूले, 100 मीटर दौड़ या पढ़ने की गति का समय नापें। समय को CSV में डाउनलोड करके Excel में खोलें।',
    tip6: 'खुद पढ़ाई के लिए पोमोडोरो: 25 मिनट ध्यान + 5 मिनट ब्रेक। 4 सत्रों के बाद लंबा ब्रेक लें।'
  },

  bn: {
    app_title: 'ক্লাসরুম টাইমার',
    intro: 'ক্লাসের জন্য বড় ও পরিষ্কার টাইমার: কাউন্টডাউন, স্টপওয়াচ, পোমোডোরো আর কাজের নিয়মের বোর্ড। ছাত্রছাত্রীরা সময়ের পরিকল্পনা করতে শেখে আর সবসময় জানে এখন কী করতে হবে।',
    tabs_label: 'টাইমারের ধরন',
    tab_countdown: 'কাউন্টডাউন', tab_stopwatch: 'স্টপওয়াচ', tab_pomodoro: 'পোমোডোরো', tab_signs: 'কাজের নিয়ম',
    quick_times: 'ঝটপট সময়', min_short: 'মিনিট', min_n: '{n} মিনিট',
    custom_time: 'নিজের সময়', hours: 'ঘণ্টা', minutes: 'মিনিট', seconds: 'সেকেন্ড', set_time: 'সেট করুন',
    enter_time: 'শূন্যের চেয়ে বেশি সময় লিখুন।',
    add_minute: '+1 মিনিট',
    activity_ph: 'এখন কী করছি? (যেমন: চুপচাপ পড়া)', activity_label: 'কাজের নাম',
    btn_start: 'শুরু করুন', btn_pause: 'থামান', btn_resume: 'আবার শুরু',
    st_ready: 'প্রস্তুত', st_running: 'চলছে', st_paused: 'থেমে আছে', ends_at: '{time}-এ শেষ',
    times_up: 'সময় শেষ!', over_by: '{t} বেশি হয়ে গেছে', start_again: 'আবার শুরু করুন', exit_fullscreen: 'পূর্ণ পর্দা বন্ধ করুন',
    sound: 'অ্যালার্মের শব্দ', sound_bell: 'ঘণ্টা', sound_beeps: 'বিপ', sound_gong: 'গভীর কাঁসর', sound_off: 'কোনো শব্দ নয়', test_sound: 'শুনে দেখুন',
    no_audio: 'এই ব্রাউজারে শব্দ চালানো যাচ্ছে না।',
    warn_minute: '1 মিনিট বাকি থাকলে হালকা বিপ',
    keys_cd: 'কিবোর্ড: <kbd>Space</kbd> শুরু / থামান · <kbd>R</kbd> রিসেট · <kbd>F</kbd> পূর্ণ পর্দা',
    lap: 'ল্যাপ', lap_n: 'ল্যাপ {n}', laps: 'ল্যাপগুলো', lap_time: 'ল্যাপের সময়', lap_secs: 'ল্যাপের সময় (সেকেন্ড)', total_time: 'মোট সময়',
    no_laps: 'স্টপওয়াচ চলার সময় ‘ল্যাপ’ চাপুন, প্রতিটি সময় জমা থাকবে: দৌড়, বিজ্ঞানের পরীক্ষা বা পড়ার গতির জন্য।',
    laps_count: 'ল্যাপ: {n}', average: 'গড় ল্যাপ: {t}', fastest: 'সবচেয়ে দ্রুত', slowest: 'সবচেয়ে ধীর', download_csv: 'CSV ডাউনলোড',
    keys_sw: 'কিবোর্ড: <kbd>Space</kbd> শুরু / থামান · <kbd>L</kbd> ল্যাপ · <kbd>R</kbd> রিসেট · <kbd>F</kbd> পূর্ণ পর্দা',
    phase_work: 'মনোযোগের সময়', phase_short: 'ছোট বিরতি', phase_long: 'লম্বা বিরতি', session_of: '{m}টির মধ্যে {n} নম্বর সেশন', skip: 'বাদ দিন',
    plans: 'তৈরি পরিকল্পনা', plan_classic: 'ক্লাসিক · 25 + 5', plan_class: 'এক পিরিয়ড · 20 + 5', plan_exam: 'পরীক্ষার পড়া · 50 + 10', plan_young: 'ছোটদের জন্য · 10 + 2',
    po_settings: 'নিজের পরিকল্পনা', work_len: 'মনোযোগ (মিনিট)', short_len: 'ছোট বিরতি (মিনিট)', long_len: 'লম্বা বিরতি (মিনিট)', long_every: 'কটি সেশনের পর লম্বা বিরতি',
    auto_next: 'পরের অংশ নিজে থেকেই শুরু হোক',
    po_stats: 'শেষ হওয়া সেশন: {n} · মোট মনোযোগ: {m} মিনিট',
    po_what: 'পোমোডোরো পদ্ধতি: নির্দিষ্ট সময় ধরে একটি কাজেই পুরো মন দিন, তারপর ছোট বিরতি নিন। কয়েকটি সেশনের পরে লম্বা বিরতি নিন।',
    po_work_over: 'মনোযোগের সময় শেষ। এবার বিরতি নিন!', po_break_over: 'বিরতি শেষ। আবার কাজে ফিরুন!', po_next_note: 'নতুন সময় পরের অংশ থেকে চালু হবে।',
    choose_sign: 'ক্লাসের জন্য একটি বোর্ড বেছে নিন', voice_level: 'আওয়াজের মাত্রা {n}', time_left: 'বাকি সময়: {t}',
    print_sign: 'এই বোর্ড প্রিন্ট করুন', print_all: 'সব বোর্ড প্রিন্ট করুন',
    keys_sg: 'কিবোর্ড: <kbd>1</kbd>–<kbd>8</kbd> বোর্ড বদলান · <kbd>Space</kbd> কাউন্টডাউন শুরু / থামান · <kbd>F</kbd> পূর্ণ পর্দা',
    sign_silent: 'চুপচাপ কাজ', sign_silent_d: 'কথা বলা নয়। নিজের কাজ নিজে করো।',
    sign_whisper: 'ফিসফিস করে', sign_whisper_d: 'খুব দরকার হলে তবেই, খুব আস্তে কথা বলো।',
    sign_partner: 'সঙ্গীর সঙ্গে কথা', sign_partner_d: 'পাশের জনের সঙ্গে আস্তে কথা বলো।',
    sign_group: 'দলে কাজ', sign_group_d: 'নিজের দলে আলোচনা করো। আওয়াজ নিচু রাখো।',
    sign_hands: 'হাত তোলো', sign_hands_d: 'হাত তুলে কথা বলার জন্য নিজের পালার অপেক্ষা করো।',
    sign_listen: 'আমার দিকে তাকাও', sign_listen_d: 'থামো, শিক্ষকের দিকে তাকাও আর মন দিয়ে শোনো।',
    sign_tidy: 'গুছিয়ে নাও', sign_tidy_d: 'জিনিসপত্র গুছিয়ে রাখো আর ডেস্ক পরিষ্কার করো।',
    sign_stretch: 'একটু ব্যায়াম', sign_stretch_d: 'উঠে দাঁড়াও, হাত টানটান করো আর গভীর শ্বাস নাও।',
    help_title: 'কীভাবে ব্যবহার করবেন / ক্লাসের জন্য আইডিয়া',
    tip1: 'একটি ঝটপট সময় বাছুন (বা নিজের সময় লিখুন) আর ‘শুরু করুন’ চাপুন। শেষ মিনিটে বৃত্তটি কমলা আর সময় শেষ হলে লাল হয়ে যায়, সঙ্গে হালকা অ্যালার্ম বাজে।',
    tip2: 'প্রজেক্টর বা স্মার্টবোর্ডে দেখাতে ‘পূর্ণ পর্দা’ চাপুন। কিবোর্ড: Space = শুরু / থামান, R = রিসেট, F = পূর্ণ পর্দা।',
    tip3: 'অন্য ট্যাব খুললে বা স্ক্রিন বন্ধ হলেও টাইমার ঠিক সময় রাখে, আর ব্রাউজারের ট্যাবে বাকি সময় দেখা যায়।',
    tip4: 'ক্লাসের কাজ (ভাবো–জোড়ায় বলো–সবাইকে জানাও): ভাবার জন্য 2 মিনিটের কাউন্টডাউনের সঙ্গে ‘চুপচাপ কাজ’ দেখান, তারপর 3 মিনিট ‘সঙ্গীর সঙ্গে কথা’, তারপর উত্তর বলার জন্য ‘হাত তোলো’।',
    tip5: 'বিজ্ঞান বা খেলাধুলা: স্টপওয়াচের ল্যাপ দিয়ে দোলকের 10টি দোলন, 100 মিটার দৌড় বা পড়ার গতি মাপুন। সময়গুলো CSV হিসেবে ডাউনলোড করে Excel-এ খুলুন।',
    tip6: 'নিজে পড়ার জন্য পোমোডোরো: 25 মিনিট মনোযোগ + 5 মিনিট বিরতি। 4টি সেশনের পর লম্বা বিরতি নিন।'
  },

  mr: {
    app_title: 'वर्ग टायमर',
    intro: 'वर्गासाठी मोठे आणि स्पष्ट टायमर: उलटी गणना, स्टॉपवॉच, पोमोडोरो आणि कामाच्या पद्धतीचे फलक. विद्यार्थी वेळेचे नियोजन करायला शिकतात आणि आता काय करायचे ते त्यांना नेहमी कळते.',
    tabs_label: 'टायमरचा प्रकार',
    tab_countdown: 'उलटी गणना', tab_stopwatch: 'स्टॉपवॉच', tab_pomodoro: 'पोमोडोरो', tab_signs: 'कामाची पद्धत',
    quick_times: 'झटपट वेळ', min_short: 'मिनिटे', min_n: '{n} मिनिटे',
    custom_time: 'तुमची वेळ', hours: 'तास', minutes: 'मिनिटे', seconds: 'सेकंद', set_time: 'सेट करा',
    enter_time: 'कृपया शून्यापेक्षा जास्त वेळ लिहा.',
    add_minute: '+1 मिनिट',
    activity_ph: 'आता काय करत आहोत? (उदा. शांत वाचन)', activity_label: 'उपक्रमाचे नाव',
    btn_start: 'सुरू करा', btn_pause: 'थांबवा', btn_resume: 'पुन्हा सुरू करा',
    st_ready: 'तयार', st_running: 'चालू आहे', st_paused: 'थांबवले आहे', ends_at: '{time} ला संपेल',
    times_up: 'वेळ संपली!', over_by: '{t} जास्त झाले', start_again: 'पुन्हा सुरू करा', exit_fullscreen: 'पूर्ण स्क्रीन बंद करा',
    sound: 'अलार्मचा आवाज', sound_bell: 'घंटा', sound_beeps: 'बीप', sound_gong: 'खोल घंटानाद', sound_off: 'आवाज नाही', test_sound: 'ऐकून पाहा',
    no_audio: 'या ब्राउझरमध्ये आवाज वाजू शकत नाही.',
    warn_minute: '1 मिनिट उरल्यावर हलकी बीप',
    keys_cd: 'कीबोर्ड: <kbd>Space</kbd> सुरू / थांबवा · <kbd>R</kbd> रीसेट · <kbd>F</kbd> पूर्ण स्क्रीन',
    lap: 'लॅप', lap_n: 'लॅप {n}', laps: 'लॅप्स', lap_time: 'लॅपची वेळ', lap_secs: 'लॅपची वेळ (सेकंद)', total_time: 'एकूण वेळ',
    no_laps: 'स्टॉपवॉच चालू असताना ‘लॅप’ दाबा, प्रत्येक वेळ जतन होईल: शर्यत, विज्ञानाचे प्रयोग किंवा वाचनाचा वेग मोजण्यासाठी.',
    laps_count: 'लॅप: {n}', average: 'सरासरी लॅप: {t}', fastest: 'सर्वात जलद', slowest: 'सर्वात हळू', download_csv: 'CSV डाउनलोड करा',
    keys_sw: 'कीबोर्ड: <kbd>Space</kbd> सुरू / थांबवा · <kbd>L</kbd> लॅप · <kbd>R</kbd> रीसेट · <kbd>F</kbd> पूर्ण स्क्रीन',
    phase_work: 'एकाग्रतेची वेळ', phase_short: 'छोटी विश्रांती', phase_long: 'मोठी विश्रांती', session_of: '{m} पैकी सत्र {n}', skip: 'वगळा',
    plans: 'तयार योजना', plan_classic: 'क्लासिक · 25 + 5', plan_class: 'एक तासिका · 20 + 5', plan_exam: 'परीक्षेचा अभ्यास · 50 + 10', plan_young: 'लहान मुले · 10 + 2',
    po_settings: 'तुमची योजना', work_len: 'एकाग्रता (मिनिटे)', short_len: 'छोटी विश्रांती (मिनिटे)', long_len: 'मोठी विश्रांती (मिनिटे)', long_every: 'किती सत्रांनंतर मोठी विश्रांती',
    auto_next: 'पुढचा भाग आपोआप सुरू करा',
    po_stats: 'पूर्ण झालेली सत्रे: {n} · एकूण एकाग्रता: {m} मिनिटे',
    po_what: 'पोमोडोरो पद्धत: ठरावीक वेळ एकाच कामावर पूर्ण लक्ष द्या, मग छोटी विश्रांती घ्या. काही सत्रांनंतर मोठी विश्रांती घ्या.',
    po_work_over: 'एकाग्रतेची वेळ संपली. आता विश्रांती घ्या!', po_break_over: 'विश्रांती संपली. पुन्हा कामाला लागा!', po_next_note: 'नवीन वेळ पुढच्या भागापासून लागू होईल.',
    choose_sign: 'वर्गासाठी फलक निवडा', voice_level: 'आवाजाची पातळी {n}', time_left: 'उरलेली वेळ: {t}',
    print_sign: 'हा फलक प्रिंट करा', print_all: 'सर्व फलक प्रिंट करा',
    keys_sg: 'कीबोर्ड: <kbd>1</kbd>–<kbd>8</kbd> फलक बदला · <kbd>Space</kbd> उलटी गणना सुरू / थांबवा · <kbd>F</kbd> पूर्ण स्क्रीन',
    sign_silent: 'शांतपणे काम', sign_silent_d: 'बोलू नका. आपले काम स्वतः करा.',
    sign_whisper: 'हळू आवाज', sign_whisper_d: 'गरज असेल तरच, अगदी हळू बोला.',
    sign_partner: 'जोडीदाराशी बोला', sign_partner_d: 'शेजारी बसलेल्या मित्राशी हळू आवाजात बोला.',
    sign_group: 'गटात काम', sign_group_d: 'आपल्या गटात चर्चा करा. आवाज हळू ठेवा.',
    sign_hands: 'हात वर करा', sign_hands_d: 'हात वर करा आणि बोलण्यासाठी आपल्या पाळीची वाट पाहा.',
    sign_listen: 'माझ्याकडे पाहा', sign_listen_d: 'थांबा, शिक्षकांकडे पाहा आणि लक्षपूर्वक ऐका.',
    sign_tidy: 'आवराआवर', sign_tidy_d: 'आपले सामान जागेवर ठेवा आणि बाक स्वच्छ करा.',
    sign_stretch: 'थोडा व्यायाम', sign_stretch_d: 'उभे राहा, हात ताणा आणि दीर्घ श्वास घ्या.',
    help_title: 'कसे वापरावे / वर्गासाठी कल्पना',
    tip1: 'एखादी झटपट वेळ निवडा (किंवा तुमची वेळ लिहा) आणि ‘सुरू करा’ दाबा. शेवटच्या मिनिटात वर्तुळ केशरी आणि वेळ संपल्यावर लाल होते, सोबत हलका अलार्म वाजतो.',
    tip2: 'प्रोजेक्टर किंवा स्मार्टबोर्डवर दाखवण्यासाठी ‘पूर्ण स्क्रीन’ दाबा. कीबोर्ड: Space = सुरू / थांबवा, R = रीसेट, F = पूर्ण स्क्रीन.',
    tip3: 'दुसरा टॅब उघडला किंवा स्क्रीन बंद झाली तरी टायमर बरोबर वेळ ठेवतो, आणि ब्राउझरच्या टॅबवर उरलेली वेळ दिसते.',
    tip4: 'वर्गातील उपक्रम (विचार करा–जोडीत बोला–सर्वांना सांगा): विचार करण्यासाठी 2 मिनिटांच्या उलट्या गणनेसोबत ‘शांतपणे काम’ दाखवा, मग 3 मिनिटे ‘जोडीदाराशी बोला’, आणि उत्तरे सांगण्यासाठी ‘हात वर करा’.',
    tip5: 'विज्ञान किंवा खेळ: स्टॉपवॉचच्या लॅपने लोलकाचे 10 झोके, 100 मीटर शर्यत किंवा वाचनाचा वेग मोजा. वेळा CSV म्हणून डाउनलोड करून Excel मध्ये उघडा.',
    tip6: 'स्वअभ्यासासाठी पोमोडोरो: 25 मिनिटे एकाग्रता + 5 मिनिटे विश्रांती. 4 सत्रांनंतर मोठी विश्रांती घ्या.'
  },

  gu: {
    app_title: 'વર્ગખંડ ટાઇમર',
    intro: 'વર્ગ માટે મોટા અને સ્પષ્ટ ટાઇમર: કાઉન્ટડાઉન, સ્ટૉપવૉચ, પોમોડોરો અને કામની રીતનાં બોર્ડ. વિદ્યાર્થીઓ સમયનું આયોજન કરતાં શીખે છે અને હંમેશાં જાણે છે કે અત્યારે શું કરવાનું છે.',
    tabs_label: 'ટાઇમરનો પ્રકાર',
    tab_countdown: 'કાઉન્ટડાઉન', tab_stopwatch: 'સ્ટૉપવૉચ', tab_pomodoro: 'પોમોડોરો', tab_signs: 'કામની રીત',
    quick_times: 'ઝટપટ સમય', min_short: 'મિનિટ', min_n: '{n} મિનિટ',
    custom_time: 'તમારો સમય', hours: 'કલાક', minutes: 'મિનિટ', seconds: 'સેકન્ડ', set_time: 'સેટ કરો',
    enter_time: 'કૃપા કરીને શૂન્યથી વધુ સમય લખો.',
    add_minute: '+1 મિનિટ',
    activity_ph: 'અત્યારે શું કરીએ છીએ? (દા.ત. શાંતિથી વાંચન)', activity_label: 'પ્રવૃત્તિનું નામ',
    btn_start: 'શરૂ કરો', btn_pause: 'થોભો', btn_resume: 'ફરી શરૂ કરો',
    st_ready: 'તૈયાર', st_running: 'ચાલુ છે', st_paused: 'થોભાવેલું', ends_at: '{time} વાગ્યે પૂરું',
    times_up: 'સમય પૂરો!', over_by: '{t} વધારે થયા', start_again: 'ફરી શરૂ કરો', exit_fullscreen: 'પૂર્ણ સ્ક્રીન બંધ કરો',
    sound: 'એલાર્મનો અવાજ', sound_bell: 'ઘંટડી', sound_beeps: 'બીપ', sound_gong: 'ઊંડો ઘંટ', sound_off: 'અવાજ નહીં', test_sound: 'સાંભળી જુઓ',
    no_audio: 'આ બ્રાઉઝરમાં અવાજ વાગી શકતો નથી.',
    warn_minute: '1 મિનિટ બાકી હોય ત્યારે હળવી બીપ',
    keys_cd: 'કીબોર્ડ: <kbd>Space</kbd> શરૂ / થોભો · <kbd>R</kbd> રીસેટ · <kbd>F</kbd> પૂર્ણ સ્ક્રીન',
    lap: 'લૅપ', lap_n: 'લૅપ {n}', laps: 'લૅપ્સ', lap_time: 'લૅપનો સમય', lap_secs: 'લૅપનો સમય (સેકન્ડ)', total_time: 'કુલ સમય',
    no_laps: 'સ્ટૉપવૉચ ચાલતી હોય ત્યારે ‘લૅપ’ દબાવો, દરેક સમય સચવાઈ જશે: દોડ, વિજ્ઞાનના પ્રયોગ કે વાંચનની ઝડપ માટે.',
    laps_count: 'લૅપ: {n}', average: 'સરેરાશ લૅપ: {t}', fastest: 'સૌથી ઝડપી', slowest: 'સૌથી ધીમો', download_csv: 'CSV ડાઉનલોડ કરો',
    keys_sw: 'કીબોર્ડ: <kbd>Space</kbd> શરૂ / થોભો · <kbd>L</kbd> લૅપ · <kbd>R</kbd> રીસેટ · <kbd>F</kbd> પૂર્ણ સ્ક્રીન',
    phase_work: 'ધ્યાનનો સમય', phase_short: 'નાનો વિરામ', phase_long: 'લાંબો વિરામ', session_of: '{m} માંથી સત્ર {n}', skip: 'છોડો',
    plans: 'તૈયાર યોજનાઓ', plan_classic: 'ક્લાસિક · 25 + 5', plan_class: 'એક પિરિયડ · 20 + 5', plan_exam: 'પરીક્ષાની તૈયારી · 50 + 10', plan_young: 'નાનાં બાળકો · 10 + 2',
    po_settings: 'તમારી યોજના', work_len: 'ધ્યાન (મિનિટ)', short_len: 'નાનો વિરામ (મિનિટ)', long_len: 'લાંબો વિરામ (મિનિટ)', long_every: 'કેટલાં સત્ર પછી લાંબો વિરામ',
    auto_next: 'આગળનો ભાગ આપમેળે શરૂ કરો',
    po_stats: 'પૂરાં થયેલાં સત્ર: {n} · કુલ ધ્યાન: {m} મિનિટ',
    po_what: 'પોમોડોરો રીત: નક્કી સમય સુધી એક જ કામ પર પૂરું ધ્યાન આપો, પછી નાનો વિરામ લો. થોડાં સત્ર પછી લાંબો વિરામ લો.',
    po_work_over: 'ધ્યાનનો સમય પૂરો. હવે વિરામ લો!', po_break_over: 'વિરામ પૂરો. ફરી કામે લાગો!', po_next_note: 'નવો સમય આગળના ભાગથી લાગુ થશે.',
    choose_sign: 'વર્ગ માટે બોર્ડ પસંદ કરો', voice_level: 'અવાજનું સ્તર {n}', time_left: 'બાકી સમય: {t}',
    print_sign: 'આ બોર્ડ પ્રિન્ટ કરો', print_all: 'બધાં બોર્ડ પ્રિન્ટ કરો',
    keys_sg: 'કીબોર્ડ: <kbd>1</kbd>–<kbd>8</kbd> બોર્ડ બદલો · <kbd>Space</kbd> કાઉન્ટડાઉન શરૂ / થોભો · <kbd>F</kbd> પૂર્ણ સ્ક્રીન',
    sign_silent: 'શાંતિથી કામ', sign_silent_d: 'વાતો નહીં. પોતાનું કામ જાતે કરો.',
    sign_whisper: 'ધીમો અવાજ', sign_whisper_d: 'જરૂર હોય તો જ, બહુ ધીમેથી બોલો.',
    sign_partner: 'જોડીદાર સાથે વાત', sign_partner_d: 'બાજુમાં બેઠેલા મિત્ર સાથે ધીમેથી વાત કરો.',
    sign_group: 'જૂથમાં કામ', sign_group_d: 'તમારા જૂથમાં ચર્ચા કરો. અવાજ ધીમો રાખો.',
    sign_hands: 'હાથ ઊંચો કરો', sign_hands_d: 'હાથ ઊંચો કરો અને બોલવા માટે તમારા વારાની રાહ જુઓ.',
    sign_listen: 'મારી તરફ જુઓ', sign_listen_d: 'અટકો, શિક્ષક તરફ જુઓ અને ધ્યાનથી સાંભળો.',
    sign_tidy: 'સાફસફાઈ', sign_tidy_d: 'તમારો સામાન મૂકી દો અને ડેસ્ક સાફ કરો.',
    sign_stretch: 'થોડી કસરત', sign_stretch_d: 'ઊભા થાઓ, હાથ ખેંચો અને ઊંડો શ્વાસ લો.',
    help_title: 'કેવી રીતે વાપરવું / વર્ગ માટે વિચારો',
    tip1: 'કોઈ ઝટપટ સમય પસંદ કરો (અથવા તમારો સમય લખો) અને ‘શરૂ કરો’ દબાવો. છેલ્લી મિનિટમાં વર્તુળ નારંગી અને સમય પૂરો થાય ત્યારે લાલ થાય છે, સાથે હળવો એલાર્મ વાગે છે.',
    tip2: 'પ્રોજેક્ટર કે સ્માર્ટબોર્ડ પર બતાવવા ‘પૂર્ણ સ્ક્રીન’ દબાવો. કીબોર્ડ: Space = શરૂ / થોભો, R = રીસેટ, F = પૂર્ણ સ્ક્રીન.',
    tip3: 'બીજું ટૅબ ખોલો કે સ્ક્રીન બંધ થાય તો પણ ટાઇમર સાચો સમય રાખે છે, અને બ્રાઉઝરના ટૅબ પર બાકી સમય દેખાય છે.',
    tip4: 'વર્ગ પ્રવૃત્તિ (વિચારો–જોડીમાં બોલો–બધાને કહો): વિચારવા માટે 2 મિનિટના કાઉન્ટડાઉન સાથે ‘શાંતિથી કામ’ બતાવો, પછી 3 મિનિટ ‘જોડીદાર સાથે વાત’, પછી જવાબ કહેવા ‘હાથ ઊંચો કરો’.',
    tip5: 'વિજ્ઞાન કે રમતગમત: સ્ટૉપવૉચના લૅપથી લોલકના 10 ઝૂલા, 100 મીટર દોડ કે વાંચનની ઝડપ માપો. સમય CSV તરીકે ડાઉનલોડ કરીને Excel માં ખોલો.',
    tip6: 'જાતે અભ્યાસ માટે પોમોડોરો: 25 મિનિટ ધ્યાન + 5 મિનિટ વિરામ. 4 સત્ર પછી લાંબો વિરામ લો.'
  },

  pa: {
    app_title: 'ਕਲਾਸ ਟਾਈਮਰ',
    intro: 'ਕਲਾਸ ਲਈ ਵੱਡੇ ਅਤੇ ਸਾਫ਼ ਟਾਈਮਰ: ਕਾਊਂਟਡਾਊਨ, ਸਟੌਪਵਾਚ, ਪੋਮੋਡੋਰੋ ਅਤੇ ਕੰਮ ਦੇ ਢੰਗ ਵਾਲੇ ਬੋਰਡ। ਵਿਦਿਆਰਥੀ ਸਮੇਂ ਦੀ ਯੋਜਨਾ ਬਣਾਉਣਾ ਸਿੱਖਦੇ ਹਨ ਅਤੇ ਹਮੇਸ਼ਾ ਜਾਣਦੇ ਹਨ ਕਿ ਹੁਣ ਕੀ ਕਰਨਾ ਹੈ।',
    tabs_label: 'ਟਾਈਮਰ ਦੀ ਕਿਸਮ',
    tab_countdown: 'ਕਾਊਂਟਡਾਊਨ', tab_stopwatch: 'ਸਟੌਪਵਾਚ', tab_pomodoro: 'ਪੋਮੋਡੋਰੋ', tab_signs: 'ਕੰਮ ਦਾ ਢੰਗ',
    quick_times: 'ਝਟਪਟ ਸਮਾਂ', min_short: 'ਮਿੰਟ', min_n: '{n} ਮਿੰਟ',
    custom_time: 'ਆਪਣਾ ਸਮਾਂ', hours: 'ਘੰਟੇ', minutes: 'ਮਿੰਟ', seconds: 'ਸਕਿੰਟ', set_time: 'ਸੈੱਟ ਕਰੋ',
    enter_time: 'ਕਿਰਪਾ ਕਰਕੇ ਸਿਫ਼ਰ ਤੋਂ ਵੱਧ ਸਮਾਂ ਲਿਖੋ।',
    add_minute: '+1 ਮਿੰਟ',
    activity_ph: 'ਹੁਣ ਕੀ ਕਰ ਰਹੇ ਹਾਂ? (ਜਿਵੇਂ: ਚੁੱਪ ਕਰਕੇ ਪੜ੍ਹਨਾ)', activity_label: 'ਗਤੀਵਿਧੀ ਦਾ ਨਾਂ',
    btn_start: 'ਸ਼ੁਰੂ ਕਰੋ', btn_pause: 'ਰੋਕੋ', btn_resume: 'ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ',
    st_ready: 'ਤਿਆਰ', st_running: 'ਚੱਲ ਰਿਹਾ ਹੈ', st_paused: 'ਰੁਕਿਆ ਹੋਇਆ', ends_at: '{time} ’ਤੇ ਖ਼ਤਮ',
    times_up: 'ਸਮਾਂ ਪੂਰਾ!', over_by: '{t} ਵੱਧ ਹੋ ਗਏ', start_again: 'ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ', exit_fullscreen: 'ਪੂਰੀ ਸਕ੍ਰੀਨ ਬੰਦ ਕਰੋ',
    sound: 'ਅਲਾਰਮ ਦੀ ਆਵਾਜ਼', sound_bell: 'ਘੰਟੀ', sound_beeps: 'ਬੀਪ', sound_gong: 'ਡੂੰਘਾ ਘੰਟਾ', sound_off: 'ਕੋਈ ਆਵਾਜ਼ ਨਹੀਂ', test_sound: 'ਸੁਣ ਕੇ ਦੇਖੋ',
    no_audio: 'ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਆਵਾਜ਼ ਨਹੀਂ ਚੱਲ ਸਕਦੀ।',
    warn_minute: '1 ਮਿੰਟ ਬਾਕੀ ਰਹਿਣ ’ਤੇ ਹਲਕੀ ਬੀਪ',
    keys_cd: 'ਕੀਬੋਰਡ: <kbd>Space</kbd> ਸ਼ੁਰੂ / ਰੋਕੋ · <kbd>R</kbd> ਰੀਸੈੱਟ · <kbd>F</kbd> ਪੂਰੀ ਸਕ੍ਰੀਨ',
    lap: 'ਲੈਪ', lap_n: 'ਲੈਪ {n}', laps: 'ਸਾਰੇ ਲੈਪ', lap_time: 'ਲੈਪ ਦਾ ਸਮਾਂ', lap_secs: 'ਲੈਪ ਦਾ ਸਮਾਂ (ਸਕਿੰਟ)', total_time: 'ਕੁੱਲ ਸਮਾਂ',
    no_laps: 'ਸਟੌਪਵਾਚ ਚੱਲਦੇ ਸਮੇਂ ‘ਲੈਪ’ ਦਬਾਓ, ਹਰ ਸਮਾਂ ਸੰਭਾਲਿਆ ਜਾਵੇਗਾ: ਦੌੜ, ਵਿਗਿਆਨ ਦੇ ਪ੍ਰਯੋਗ ਜਾਂ ਪੜ੍ਹਨ ਦੀ ਰਫ਼ਤਾਰ ਲਈ।',
    laps_count: 'ਲੈਪ: {n}', average: 'ਔਸਤ ਲੈਪ: {t}', fastest: 'ਸਭ ਤੋਂ ਤੇਜ਼', slowest: 'ਸਭ ਤੋਂ ਹੌਲੀ', download_csv: 'CSV ਡਾਊਨਲੋਡ ਕਰੋ',
    keys_sw: 'ਕੀਬੋਰਡ: <kbd>Space</kbd> ਸ਼ੁਰੂ / ਰੋਕੋ · <kbd>L</kbd> ਲੈਪ · <kbd>R</kbd> ਰੀਸੈੱਟ · <kbd>F</kbd> ਪੂਰੀ ਸਕ੍ਰੀਨ',
    phase_work: 'ਧਿਆਨ ਦਾ ਸਮਾਂ', phase_short: 'ਛੋਟੀ ਬ੍ਰੇਕ', phase_long: 'ਲੰਬੀ ਬ੍ਰੇਕ', session_of: '{m} ਵਿੱਚੋਂ ਸੈਸ਼ਨ {n}', skip: 'ਛੱਡੋ',
    plans: 'ਤਿਆਰ ਯੋਜਨਾਵਾਂ', plan_classic: 'ਕਲਾਸਿਕ · 25 + 5', plan_class: 'ਇੱਕ ਪੀਰੀਅਡ · 20 + 5', plan_exam: 'ਇਮਤਿਹਾਨ ਦੀ ਤਿਆਰੀ · 50 + 10', plan_young: 'ਛੋਟੇ ਬੱਚੇ · 10 + 2',
    po_settings: 'ਆਪਣੀ ਯੋਜਨਾ', work_len: 'ਧਿਆਨ (ਮਿੰਟ)', short_len: 'ਛੋਟੀ ਬ੍ਰੇਕ (ਮਿੰਟ)', long_len: 'ਲੰਬੀ ਬ੍ਰੇਕ (ਮਿੰਟ)', long_every: 'ਕਿੰਨੇ ਸੈਸ਼ਨਾਂ ਬਾਅਦ ਲੰਬੀ ਬ੍ਰੇਕ',
    auto_next: 'ਅਗਲਾ ਹਿੱਸਾ ਆਪਣੇ-ਆਪ ਸ਼ੁਰੂ ਕਰੋ',
    po_stats: 'ਪੂਰੇ ਹੋਏ ਸੈਸ਼ਨ: {n} · ਕੁੱਲ ਧਿਆਨ: {m} ਮਿੰਟ',
    po_what: 'ਪੋਮੋਡੋਰੋ ਢੰਗ: ਤੈਅ ਸਮੇਂ ਲਈ ਇੱਕੋ ਕੰਮ ’ਤੇ ਪੂਰਾ ਧਿਆਨ ਦਿਓ, ਫਿਰ ਛੋਟੀ ਬ੍ਰੇਕ ਲਓ। ਕੁਝ ਸੈਸ਼ਨਾਂ ਤੋਂ ਬਾਅਦ ਲੰਬੀ ਬ੍ਰੇਕ ਲਓ।',
    po_work_over: 'ਧਿਆਨ ਦਾ ਸਮਾਂ ਪੂਰਾ। ਹੁਣ ਬ੍ਰੇਕ ਲਓ!', po_break_over: 'ਬ੍ਰੇਕ ਖ਼ਤਮ। ਮੁੜ ਕੰਮ ’ਤੇ ਲੱਗੋ!', po_next_note: 'ਨਵਾਂ ਸਮਾਂ ਅਗਲੇ ਹਿੱਸੇ ਤੋਂ ਲਾਗੂ ਹੋਵੇਗਾ।',
    choose_sign: 'ਕਲਾਸ ਲਈ ਬੋਰਡ ਚੁਣੋ', voice_level: 'ਆਵਾਜ਼ ਦਾ ਪੱਧਰ {n}', time_left: 'ਬਾਕੀ ਸਮਾਂ: {t}',
    print_sign: 'ਇਹ ਬੋਰਡ ਪ੍ਰਿੰਟ ਕਰੋ', print_all: 'ਸਾਰੇ ਬੋਰਡ ਪ੍ਰਿੰਟ ਕਰੋ',
    keys_sg: 'ਕੀਬੋਰਡ: <kbd>1</kbd>–<kbd>8</kbd> ਬੋਰਡ ਬਦਲੋ · <kbd>Space</kbd> ਕਾਊਂਟਡਾਊਨ ਸ਼ੁਰੂ / ਰੋਕੋ · <kbd>F</kbd> ਪੂਰੀ ਸਕ੍ਰੀਨ',
    sign_silent: 'ਚੁੱਪ ਕਰਕੇ ਕੰਮ', sign_silent_d: 'ਗੱਲਾਂ ਨਹੀਂ। ਆਪਣਾ ਕੰਮ ਆਪ ਕਰੋ।',
    sign_whisper: 'ਹੌਲੀ ਆਵਾਜ਼', sign_whisper_d: 'ਲੋੜ ਹੋਵੇ ਤਾਂ ਹੀ, ਬਹੁਤ ਹੌਲੀ ਬੋਲੋ।',
    sign_partner: 'ਸਾਥੀ ਨਾਲ ਗੱਲ', sign_partner_d: 'ਨਾਲ ਬੈਠੇ ਸਾਥੀ ਨਾਲ ਹੌਲੀ ਗੱਲ ਕਰੋ।',
    sign_group: 'ਟੋਲੀ ਵਿੱਚ ਕੰਮ', sign_group_d: 'ਆਪਣੀ ਟੋਲੀ ਵਿੱਚ ਚਰਚਾ ਕਰੋ। ਆਵਾਜ਼ ਹੌਲੀ ਰੱਖੋ।',
    sign_hands: 'ਹੱਥ ਉੱਪਰ ਕਰੋ', sign_hands_d: 'ਹੱਥ ਉੱਪਰ ਕਰੋ ਅਤੇ ਬੋਲਣ ਲਈ ਆਪਣੀ ਵਾਰੀ ਦੀ ਉਡੀਕ ਕਰੋ।',
    sign_listen: 'ਮੇਰੇ ਵੱਲ ਦੇਖੋ', sign_listen_d: 'ਰੁਕੋ, ਅਧਿਆਪਕ ਵੱਲ ਦੇਖੋ ਅਤੇ ਧਿਆਨ ਨਾਲ ਸੁਣੋ।',
    sign_tidy: 'ਸਫ਼ਾਈ ਦਾ ਸਮਾਂ', sign_tidy_d: 'ਆਪਣਾ ਸਮਾਨ ਸੰਭਾਲੋ ਅਤੇ ਡੈਸਕ ਸਾਫ਼ ਕਰੋ।',
    sign_stretch: 'ਥੋੜ੍ਹੀ ਕਸਰਤ', sign_stretch_d: 'ਖੜ੍ਹੇ ਹੋਵੋ, ਬਾਹਾਂ ਖਿੱਚੋ ਅਤੇ ਡੂੰਘਾ ਸਾਹ ਲਓ।',
    help_title: 'ਕਿਵੇਂ ਵਰਤੀਏ / ਕਲਾਸ ਲਈ ਸੁਝਾਅ',
    tip1: 'ਕੋਈ ਝਟਪਟ ਸਮਾਂ ਚੁਣੋ (ਜਾਂ ਆਪਣਾ ਸਮਾਂ ਲਿਖੋ) ਅਤੇ ‘ਸ਼ੁਰੂ ਕਰੋ’ ਦਬਾਓ। ਆਖ਼ਰੀ ਮਿੰਟ ਵਿੱਚ ਘੇਰਾ ਸੰਤਰੀ ਅਤੇ ਸਮਾਂ ਪੂਰਾ ਹੋਣ ’ਤੇ ਲਾਲ ਹੋ ਜਾਂਦਾ ਹੈ, ਨਾਲ ਹਲਕਾ ਅਲਾਰਮ ਵੱਜਦਾ ਹੈ।',
    tip2: 'ਪ੍ਰੋਜੈਕਟਰ ਜਾਂ ਸਮਾਰਟਬੋਰਡ ’ਤੇ ਦਿਖਾਉਣ ਲਈ ‘ਪੂਰੀ ਸਕ੍ਰੀਨ’ ਦਬਾਓ। ਕੀਬੋਰਡ: Space = ਸ਼ੁਰੂ / ਰੋਕੋ, R = ਰੀਸੈੱਟ, F = ਪੂਰੀ ਸਕ੍ਰੀਨ।',
    tip3: 'ਦੂਜੀ ਟੈਬ ਖੋਲ੍ਹਣ ਜਾਂ ਸਕ੍ਰੀਨ ਬੰਦ ਹੋਣ ’ਤੇ ਵੀ ਟਾਈਮਰ ਸਹੀ ਸਮਾਂ ਰੱਖਦਾ ਹੈ, ਅਤੇ ਬ੍ਰਾਊਜ਼ਰ ਟੈਬ ’ਤੇ ਬਾਕੀ ਸਮਾਂ ਦਿਸਦਾ ਹੈ।',
    tip4: 'ਕਲਾਸ ਗਤੀਵਿਧੀ (ਸੋਚੋ–ਜੋੜੀ ਵਿੱਚ ਬੋਲੋ–ਸਭ ਨੂੰ ਦੱਸੋ): ਸੋਚਣ ਲਈ 2 ਮਿੰਟ ਦੇ ਕਾਊਂਟਡਾਊਨ ਨਾਲ ‘ਚੁੱਪ ਕਰਕੇ ਕੰਮ’ ਦਿਖਾਓ, ਫਿਰ 3 ਮਿੰਟ ‘ਸਾਥੀ ਨਾਲ ਗੱਲ’, ਫਿਰ ਜਵਾਬ ਦੱਸਣ ਲਈ ‘ਹੱਥ ਉੱਪਰ ਕਰੋ’।',
    tip5: 'ਵਿਗਿਆਨ ਜਾਂ ਖੇਡਾਂ: ਸਟੌਪਵਾਚ ਦੇ ਲੈਪ ਨਾਲ ਪੈਂਡੂਲਮ ਦੇ 10 ਝੂਟੇ, 100 ਮੀਟਰ ਦੌੜ ਜਾਂ ਪੜ੍ਹਨ ਦੀ ਰਫ਼ਤਾਰ ਮਾਪੋ। ਸਮੇਂ CSV ਵਜੋਂ ਡਾਊਨਲੋਡ ਕਰਕੇ Excel ਵਿੱਚ ਖੋਲ੍ਹੋ।',
    tip6: 'ਆਪ ਪੜ੍ਹਾਈ ਲਈ ਪੋਮੋਡੋਰੋ: 25 ਮਿੰਟ ਧਿਆਨ + 5 ਮਿੰਟ ਬ੍ਰੇਕ। 4 ਸੈਸ਼ਨਾਂ ਤੋਂ ਬਾਅਦ ਲੰਬੀ ਬ੍ਰੇਕ ਲਓ।'
  },

  or: {
    app_title: 'ଶ୍ରେଣୀ ଟାଇମର',
    intro: 'ଶ୍ରେଣୀ ପାଇଁ ବଡ଼ ଓ ସ୍ପଷ୍ଟ ଟାଇମର: କାଉଣ୍ଟଡାଉନ୍, ଷ୍ଟପୱାଚ୍, ପୋମୋଡୋରୋ ଓ କାମ ଢଙ୍ଗର ବୋର୍ଡ। ଛାତ୍ରଛାତ୍ରୀ ସମୟର ଯୋଜନା କରିବା ଶିଖନ୍ତି ଏବଂ ସବୁବେଳେ ଜାଣନ୍ତି ଏବେ କ’ଣ କରିବାକୁ ହେବ।',
    tabs_label: 'ଟାଇମରର ପ୍ରକାର',
    tab_countdown: 'କାଉଣ୍ଟଡାଉନ୍', tab_stopwatch: 'ଷ୍ଟପୱାଚ୍', tab_pomodoro: 'ପୋମୋଡୋରୋ', tab_signs: 'କାମର ଢଙ୍ଗ',
    quick_times: 'ଝଟପଟ ସମୟ', min_short: 'ମିନିଟ୍', min_n: '{n} ମିନିଟ୍',
    custom_time: 'ନିଜ ସମୟ', hours: 'ଘଣ୍ଟା', minutes: 'ମିନିଟ୍', seconds: 'ସେକେଣ୍ଡ', set_time: 'ସେଟ୍ କରନ୍ତୁ',
    enter_time: 'ଦୟାକରି ଶୂନରୁ ଅଧିକ ସମୟ ଲେଖନ୍ତୁ।',
    add_minute: '+1 ମିନିଟ୍',
    activity_ph: 'ଏବେ କ’ଣ କରୁଛୁ? (ଯେପରି: ଚୁପଚାପ ପଢ଼ିବା)', activity_label: 'କାର୍ଯ୍ୟକଳାପର ନାମ',
    btn_start: 'ଆରମ୍ଭ କରନ୍ତୁ', btn_pause: 'ଅଟକାନ୍ତୁ', btn_resume: 'ପୁଣି ଆରମ୍ଭ',
    st_ready: 'ପ୍ରସ୍ତୁତ', st_running: 'ଚାଲୁଛି', st_paused: 'ଅଟକିଛି', ends_at: '{time}ରେ ଶେଷ',
    times_up: 'ସମୟ ସରିଲା!', over_by: '{t} ଅଧିକ ହୋଇଗଲା', start_again: 'ପୁଣି ଆରମ୍ଭ କରନ୍ତୁ', exit_fullscreen: 'ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍ ବନ୍ଦ କରନ୍ତୁ',
    sound: 'ଆଲାର୍ମ ଶବ୍ଦ', sound_bell: 'ଘଣ୍ଟି', sound_beeps: 'ବିପ୍', sound_gong: 'ଗଭୀର ଘଣ୍ଟା', sound_off: 'କୌଣସି ଶବ୍ଦ ନାହିଁ', test_sound: 'ଶୁଣି ଦେଖନ୍ତୁ',
    no_audio: 'ଏହି ବ୍ରାଉଜରରେ ଶବ୍ଦ ବାଜିପାରିବ ନାହିଁ।',
    warn_minute: '1 ମିନିଟ୍ ବାକି ଥିଲେ ହାଲୁକା ବିପ୍',
    keys_cd: 'କିବୋର୍ଡ: <kbd>Space</kbd> ଆରମ୍ଭ / ଅଟକାନ୍ତୁ · <kbd>R</kbd> ରିସେଟ୍ · <kbd>F</kbd> ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍',
    lap: 'ଲ୍ୟାପ୍', lap_n: 'ଲ୍ୟାପ୍ {n}', laps: 'ସବୁ ଲ୍ୟାପ୍', lap_time: 'ଲ୍ୟାପ୍ ସମୟ', lap_secs: 'ଲ୍ୟାପ୍ ସମୟ (ସେକେଣ୍ଡ)', total_time: 'ମୋଟ ସମୟ',
    no_laps: 'ଷ୍ଟପୱାଚ୍ ଚାଲୁଥିବା ବେଳେ ‘ଲ୍ୟାପ୍’ ଦବାନ୍ତୁ, ପ୍ରତିଟି ସମୟ ସଞ୍ଚିତ ହେବ: ଦୌଡ଼, ବିଜ୍ଞାନ ପରୀକ୍ଷଣ କିମ୍ବା ପଢ଼ିବା ବେଗ ପାଇଁ।',
    laps_count: 'ଲ୍ୟାପ୍: {n}', average: 'ହାରାହାରି ଲ୍ୟାପ୍: {t}', fastest: 'ସବୁଠାରୁ ଦ୍ରୁତ', slowest: 'ସବୁଠାରୁ ଧୀର', download_csv: 'CSV ଡାଉନଲୋଡ୍',
    keys_sw: 'କିବୋର୍ଡ: <kbd>Space</kbd> ଆରମ୍ଭ / ଅଟକାନ୍ତୁ · <kbd>L</kbd> ଲ୍ୟାପ୍ · <kbd>R</kbd> ରିସେଟ୍ · <kbd>F</kbd> ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍',
    phase_work: 'ଧ୍ୟାନ ସମୟ', phase_short: 'ଛୋଟ ବିରତି', phase_long: 'ଲମ୍ବା ବିରତି', session_of: '{m}ଟି ମଧ୍ୟରୁ ସେସନ୍ {n}', skip: 'ଛାଡ଼ନ୍ତୁ',
    plans: 'ପ୍ରସ୍ତୁତ ଯୋଜନା', plan_classic: 'କ୍ଲାସିକ୍ · 25 + 5', plan_class: 'ଗୋଟିଏ ପିରିୟଡ୍ · 20 + 5', plan_exam: 'ପରୀକ୍ଷା ପଢ଼ା · 50 + 10', plan_young: 'ଛୋଟ ପିଲା · 10 + 2',
    po_settings: 'ନିଜ ଯୋଜନା', work_len: 'ଧ୍ୟାନ (ମିନିଟ୍)', short_len: 'ଛୋଟ ବିରତି (ମିନିଟ୍)', long_len: 'ଲମ୍ବା ବିରତି (ମିନିଟ୍)', long_every: 'କେତୋଟି ସେସନ୍ ପରେ ଲମ୍ବା ବିରତି',
    auto_next: 'ପରବର୍ତ୍ତୀ ଅଂଶ ନିଜେ ଆରମ୍ଭ ହେଉ',
    po_stats: 'ସରିଥିବା ସେସନ୍: {n} · ମୋଟ ଧ୍ୟାନ: {m} ମିନିଟ୍',
    po_what: 'ପୋମୋଡୋରୋ ପଦ୍ଧତି: ନିର୍ଦ୍ଦିଷ୍ଟ ସମୟ ପାଇଁ ଗୋଟିଏ କାମରେ ପୂରା ଧ୍ୟାନ ଦିଅନ୍ତୁ, ତା’ପରେ ଛୋଟ ବିରତି ନିଅନ୍ତୁ। କିଛି ସେସନ୍ ପରେ ଲମ୍ବା ବିରତି ନିଅନ୍ତୁ।',
    po_work_over: 'ଧ୍ୟାନ ସମୟ ସରିଲା। ଏବେ ବିରତି ନିଅନ୍ତୁ!', po_break_over: 'ବିରତି ସରିଲା। ପୁଣି କାମରେ ଲାଗନ୍ତୁ!', po_next_note: 'ନୂଆ ସମୟ ପରବର୍ତ୍ତୀ ଅଂଶରୁ ଲାଗୁ ହେବ।',
    choose_sign: 'ଶ୍ରେଣୀ ପାଇଁ ଏକ ବୋର୍ଡ ବାଛନ୍ତୁ', voice_level: 'ସ୍ୱର ସ୍ତର {n}', time_left: 'ବାକି ସମୟ: {t}',
    print_sign: 'ଏହି ବୋର୍ଡ ପ୍ରିଣ୍ଟ କରନ୍ତୁ', print_all: 'ସବୁ ବୋର୍ଡ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    keys_sg: 'କିବୋର୍ଡ: <kbd>1</kbd>–<kbd>8</kbd> ବୋର୍ଡ ବଦଳାନ୍ତୁ · <kbd>Space</kbd> କାଉଣ୍ଟଡାଉନ୍ ଆରମ୍ଭ / ଅଟକାନ୍ତୁ · <kbd>F</kbd> ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍',
    sign_silent: 'ଚୁପଚାପ କାମ', sign_silent_d: 'କଥା ହୁଅ ନାହିଁ। ନିଜ କାମ ନିଜେ କର।',
    sign_whisper: 'ଧୀର ସ୍ୱର', sign_whisper_d: 'ଦରକାର ହେଲେ ହିଁ, ବହୁତ ଧୀରେ କୁହ।',
    sign_partner: 'ସାଥୀ ସହ କଥା', sign_partner_d: 'ପାଖରେ ବସିଥିବା ସାଥୀ ସହ ଧୀରେ କଥା ହୁଅ।',
    sign_group: 'ଦଳରେ କାମ', sign_group_d: 'ନିଜ ଦଳରେ ଆଲୋଚନା କର। ସ୍ୱର ଧୀର ରଖ।',
    sign_hands: 'ହାତ ଟେକ', sign_hands_d: 'ହାତ ଟେକ ଏବଂ କହିବା ପାଇଁ ନିଜ ପାଳି ପର୍ଯ୍ୟନ୍ତ ଅପେକ୍ଷା କର।',
    sign_listen: 'ମୋ ଆଡ଼କୁ ଦେଖ', sign_listen_d: 'ଅଟକ, ଶିକ୍ଷକଙ୍କ ଆଡ଼କୁ ଦେଖ ଏବଂ ଧ୍ୟାନ ଦେଇ ଶୁଣ।',
    sign_tidy: 'ସଫା ସୁତୁରା', sign_tidy_d: 'ନିଜ ଜିନିଷ ସଜାଡ଼ି ରଖ ଏବଂ ଡେସ୍କ ସଫା କର।',
    sign_stretch: 'ଟିକେ ବ୍ୟାୟାମ', sign_stretch_d: 'ଠିଆ ହୁଅ, ହାତ ଟାଣ ଏବଂ ଗଭୀର ନିଶ୍ୱାସ ନିଅ।',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ଶ୍ରେଣୀ ପାଇଁ ଧାରଣା',
    tip1: 'ଏକ ଝଟପଟ ସମୟ ବାଛନ୍ତୁ (କିମ୍ବା ନିଜ ସମୟ ଲେଖନ୍ତୁ) ଏବଂ ‘ଆରମ୍ଭ କରନ୍ତୁ’ ଦବାନ୍ତୁ। ଶେଷ ମିନିଟରେ ବୃତ୍ତଟି କମଳା ଏବଂ ସମୟ ସରିଲେ ନାଲି ହୋଇଯାଏ, ସାଙ୍ଗରେ ହାଲୁକା ଆଲାର୍ମ ବାଜେ।',
    tip2: 'ପ୍ରୋଜେକ୍ଟର କିମ୍ବା ସ୍ମାର୍ଟବୋର୍ଡରେ ଦେଖାଇବା ପାଇଁ ‘ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍’ ଦବାନ୍ତୁ। କିବୋର୍ଡ: Space = ଆରମ୍ଭ / ଅଟକାନ୍ତୁ, R = ରିସେଟ୍, F = ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍।',
    tip3: 'ଅନ୍ୟ ଟ୍ୟାବ୍ ଖୋଲିଲେ କିମ୍ବା ସ୍କ୍ରିନ୍ ବନ୍ଦ ହେଲେ ବି ଟାଇମର ଠିକ୍ ସମୟ ରଖେ, ଏବଂ ବ୍ରାଉଜର ଟ୍ୟାବରେ ବାକି ସମୟ ଦେଖାଯାଏ।',
    tip4: 'ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ (ଭାବ–ଯୋଡ଼ିରେ କୁହ–ସମସ୍ତଙ୍କୁ କୁହ): ଭାବିବା ପାଇଁ 2 ମିନିଟ୍ କାଉଣ୍ଟଡାଉନ୍ ସହ ‘ଚୁପଚାପ କାମ’ ଦେଖାନ୍ତୁ, ତା’ପରେ 3 ମିନିଟ୍ ‘ସାଥୀ ସହ କଥା’, ତା’ପରେ ଉତ୍ତର କହିବା ପାଇଁ ‘ହାତ ଟେକ’।',
    tip5: 'ବିଜ୍ଞାନ କିମ୍ବା ଖେଳ: ଷ୍ଟପୱାଚ୍ ଲ୍ୟାପ୍ ଦ୍ୱାରା ଦୋଳକର 10ଟି ଦୋଳନ, 100 ମିଟର ଦୌଡ଼ କିମ୍ବା ପଢ଼ିବା ବେଗ ମାପନ୍ତୁ। ସମୟଗୁଡ଼ିକ CSV ଭାବେ ଡାଉନଲୋଡ୍ କରି Excelରେ ଖୋଲନ୍ତୁ।',
    tip6: 'ନିଜେ ପଢ଼ିବା ପାଇଁ ପୋମୋଡୋରୋ: 25 ମିନିଟ୍ ଧ୍ୟାନ + 5 ମିନିଟ୍ ବିରତି। 4ଟି ସେସନ୍ ପରେ ଲମ୍ବା ବିରତି ନିଅନ୍ତୁ।'
  },

  ta: {
    app_title: 'வகுப்பறை டைமர்',
    intro: 'வகுப்புக்கான பெரிய, தெளிவான டைமர்கள்: கவுண்ட்டவுன், ஸ்டாப்வாட்ச், பொமோடோரோ மற்றும் வேலை முறை அட்டைகள். மாணவர்கள் நேரத்தைத் திட்டமிடக் கற்றுக்கொள்கிறார்கள், இப்போது என்ன செய்ய வேண்டும் என்பதை எப்போதும் அறிகிறார்கள்.',
    tabs_label: 'டைமர் வகை',
    tab_countdown: 'கவுண்ட்டவுன்', tab_stopwatch: 'ஸ்டாப்வாட்ச்', tab_pomodoro: 'பொமோடோரோ', tab_signs: 'வேலை முறை',
    quick_times: 'விரைவு நேரங்கள்', min_short: 'நிமிடம்', min_n: '{n} நிமிடம்',
    custom_time: 'உங்கள் நேரம்', hours: 'மணி', minutes: 'நிமிடம்', seconds: 'விநாடி', set_time: 'அமை',
    enter_time: 'பூஜ்ஜியத்தை விட அதிகமான நேரத்தை உள்ளிடவும்.',
    add_minute: '+1 நிமிடம்',
    activity_ph: 'என்ன செய்கிறோம்? (எ.கா. வாசிப்பு)', activity_label: 'செயல்பாட்டின் பெயர்',
    btn_start: 'தொடங்கு', btn_pause: 'நிறுத்து', btn_resume: 'தொடர்',
    st_ready: 'தயார்', st_running: 'ஓடுகிறது', st_paused: 'நிறுத்தப்பட்டுள்ளது', ends_at: '{time} மணிக்கு முடியும்',
    times_up: 'நேரம் முடிந்தது!', over_by: '{t} கூடுதல் ஆனது', start_again: 'மீண்டும் தொடங்கு', exit_fullscreen: 'முழுத் திரையை மூடு',
    sound: 'அலாரம் ஒலி', sound_bell: 'மணி', sound_beeps: 'பீப்', sound_gong: 'ஆழ்ந்த மணியோசை', sound_off: 'ஒலி வேண்டாம்', test_sound: 'கேட்டுப் பார்',
    no_audio: 'இந்த உலாவியில் ஒலியை இயக்க முடியாது.',
    warn_minute: '1 நிமிடம் மீதமிருக்கும்போது மெல்லிய பீப்',
    keys_cd: 'விசைப்பலகை: <kbd>Space</kbd> தொடங்கு / இடைநிறுத்து · <kbd>R</kbd> மீட்டமை · <kbd>F</kbd> முழுத் திரை',
    lap: 'சுற்று', lap_n: 'சுற்று {n}', laps: 'சுற்றுகள்', lap_time: 'சுற்று நேரம்', lap_secs: 'சுற்று நேரம் (விநாடி)', total_time: 'மொத்த நேரம்',
    no_laps: 'ஸ்டாப்வாட்ச் ஓடும்போது ‘சுற்று’ அழுத்துங்கள், ஒவ்வொரு நேரமும் சேமிக்கப்படும்: ஓட்டப்பந்தயம், அறிவியல் சோதனை அல்லது வாசிப்பு வேகத்திற்கு.',
    laps_count: 'சுற்றுகள்: {n}', average: 'சராசரி சுற்று: {t}', fastest: 'மிக வேகம்', slowest: 'மிக மெதுவு', download_csv: 'CSV பதிவிறக்கு',
    keys_sw: 'விசைப்பலகை: <kbd>Space</kbd> தொடங்கு / இடைநிறுத்து · <kbd>L</kbd> சுற்று · <kbd>R</kbd> மீட்டமை · <kbd>F</kbd> முழுத் திரை',
    phase_work: 'கவன நேரம்', phase_short: 'சிறு இடைவேளை', phase_long: 'நீண்ட இடைவேளை', session_of: 'அமர்வு {n} / {m}', skip: 'தவிர்',
    plans: 'தயாரான திட்டங்கள்', plan_classic: 'வழக்கமானது · 25 + 5', plan_class: 'ஒரு பாடவேளை · 20 + 5', plan_exam: 'தேர்வுப் படிப்பு · 50 + 10', plan_young: 'சிறு குழந்தைகள் · 10 + 2',
    po_settings: 'உங்கள் திட்டம்', work_len: 'கவனம் (நிமிடம்)', short_len: 'சிறு இடைவேளை (நிமிடம்)', long_len: 'நீண்ட இடைவேளை (நிமிடம்)', long_every: 'எத்தனை அமர்வுகளுக்குப் பின் நீண்ட இடைவேளை',
    auto_next: 'அடுத்த பகுதியைத் தானாகத் தொடங்கு',
    po_stats: 'முடிந்த அமர்வுகள்: {n} · மொத்த கவனம்: {m} நிமிடம்',
    po_what: 'பொமோடோரோ முறை: குறிப்பிட்ட நேரம் ஒரே வேலையில் முழுக் கவனம் செலுத்துங்கள், பிறகு சிறு இடைவேளை எடுங்கள். சில அமர்வுகளுக்குப் பின் நீண்ட இடைவேளை எடுங்கள்.',
    po_work_over: 'கவன நேரம் முடிந்தது. இப்போது ஓய்வு எடுங்கள்!', po_break_over: 'இடைவேளை முடிந்தது. மீண்டும் வேலைக்குத் திரும்புங்கள்!', po_next_note: 'புதிய நேரம் அடுத்த பகுதியிலிருந்து பொருந்தும்.',
    choose_sign: 'வகுப்புக்கு ஒரு அட்டையைத் தேர்ந்தெடுங்கள்', voice_level: 'குரல் அளவு {n}', time_left: 'மீதி நேரம்: {t}',
    print_sign: 'இந்த அட்டையை அச்சிடு', print_all: 'எல்லா அட்டைகளையும் அச்சிடு',
    keys_sg: 'விசைப்பலகை: <kbd>1</kbd>–<kbd>8</kbd> அட்டையை மாற்று · <kbd>Space</kbd> கவுண்ட்டவுன் தொடங்கு / இடைநிறுத்து · <kbd>F</kbd> முழுத் திரை',
    sign_silent: 'அமைதியாக வேலை', sign_silent_d: 'பேச வேண்டாம். உன் வேலையை நீயே செய்.',
    sign_whisper: 'மெல்லிய குரல்', sign_whisper_d: 'தேவைப்பட்டால் மட்டும், மிக மெதுவாகப் பேசு.',
    sign_partner: 'இணையுடன் பேச்சு', sign_partner_d: 'அருகில் இருப்பவருடன் மெதுவாகப் பேசு.',
    sign_group: 'குழு வேலை', sign_group_d: 'உன் குழுவில் கலந்துரையாடு. குரலைத் தாழ்த்திப் பேசு.',
    sign_hands: 'கையை உயர்த்து', sign_hands_d: 'கையை உயர்த்தி, பேச உன் முறை வரும்வரை காத்திரு.',
    sign_listen: 'என்னைப் பார்', sign_listen_d: 'நிறுத்து, ஆசிரியரைப் பார், கவனமாகக் கேள்.',
    sign_tidy: 'சுத்தம் செய்', sign_tidy_d: 'உன் பொருட்களை எடுத்து வைத்து மேசையைச் சுத்தம் செய்.',
    sign_stretch: 'சிறு உடற்பயிற்சி', sign_stretch_d: 'எழுந்து நின்று, கைகளை நீட்டி, ஆழ்ந்து மூச்சு விடு.',
    help_title: 'பயன்படுத்துவது எப்படி / வகுப்பறை யோசனைகள்',
    tip1: 'ஒரு விரைவு நேரத்தைத் தொடுங்கள் (அல்லது உங்கள் நேரத்தை உள்ளிடுங்கள்), ‘தொடங்கு’ அழுத்துங்கள். கடைசி நிமிடத்தில் வளையம் ஆரஞ்சு நிறமாகும், நேரம் முடிந்ததும் சிவப்பாகி மென்மையான அலாரம் ஒலிக்கும்.',
    tip2: 'புரொஜெக்டர் அல்லது ஸ்மார்ட்போர்டில் காட்ட ‘முழுத் திரை’ அழுத்துங்கள். விசைகள்: Space = தொடங்கு / இடைநிறுத்து, R = மீட்டமை, F = முழுத் திரை.',
    tip3: 'வேறு டேபுக்குச் சென்றாலும் திரை அணைந்தாலும் டைமர் சரியான நேரத்தையே காட்டும்; உலாவி டேபிலும் மீதி நேரம் தெரியும்.',
    tip4: 'வகுப்புச் செயல்பாடு (சிந்தி–இணையுடன் பேசு–பகிர்): சிந்திக்க 2 நிமிட கவுண்ட்டவுனுடன் ‘அமைதியாக வேலை’ காட்டுங்கள், பிறகு 3 நிமிடம் ‘இணையுடன் பேச்சு’, பிறகு பதில் சொல்ல ‘கையை உயர்த்து’.',
    tip5: 'அறிவியல் அல்லது உடற்கல்வி: ஸ்டாப்வாட்ச் சுற்றுகள் மூலம் ஊசலின் 10 அலைவுகள், 100 மீ ஓட்டம் அல்லது வாசிப்பு வேகத்தை அளவிடுங்கள். நேரங்களை CSV ஆகப் பதிவிறக்கி Excel-இல் திறக்கலாம்.',
    tip6: 'சுயமாகப் படிக்க பொமோடோரோ: 25 நிமிடம் கவனம் + 5 நிமிடம் இடைவேளை. 4 அமர்வுகளுக்குப் பின் நீண்ட இடைவேளை எடுங்கள்.'
  },

  te: {
    app_title: 'తరగతి టైమర్',
    intro: 'తరగతి కోసం పెద్ద, స్పష్టమైన టైమర్లు: కౌంట్‌డౌన్, స్టాప్‌వాచ్, పొమోడోరో, పని విధానం బోర్డులు. విద్యార్థులు సమయాన్ని ప్లాన్ చేయడం నేర్చుకుంటారు, ఇప్పుడు ఏం చేయాలో ఎప్పుడూ తెలుసుకుంటారు.',
    tabs_label: 'టైమర్ రకం',
    tab_countdown: 'కౌంట్‌డౌన్', tab_stopwatch: 'స్టాప్‌వాచ్', tab_pomodoro: 'పొమోడోరో', tab_signs: 'పని విధానం',
    quick_times: 'త్వరిత సమయాలు', min_short: 'నిమి.', min_n: '{n} నిమిషాలు',
    custom_time: 'మీ సమయం', hours: 'గంటలు', minutes: 'నిమిషాలు', seconds: 'సెకన్లు', set_time: 'సెట్ చేయండి',
    enter_time: 'దయచేసి సున్నా కంటే ఎక్కువ సమయం ఇవ్వండి.',
    add_minute: '+1 నిమి.',
    activity_ph: 'ఏం చేస్తున్నాం? (ఉదా. చదవడం)', activity_label: 'కార్యకలాపం పేరు',
    btn_start: 'ప్రారంభించండి', btn_pause: 'ఆపండి', btn_resume: 'కొనసాగించండి',
    st_ready: 'సిద్ధం', st_running: 'నడుస్తోంది', st_paused: 'ఆగి ఉంది', ends_at: '{time}కి ముగుస్తుంది',
    times_up: 'సమయం అయిపోయింది!', over_by: '{t} ఎక్కువైంది', start_again: 'మళ్లీ ప్రారంభించండి', exit_fullscreen: 'పూర్తి స్క్రీన్ మూసివేయండి',
    sound: 'అలారం శబ్దం', sound_bell: 'గంట', sound_beeps: 'బీప్', sound_gong: 'లోతైన గంట', sound_off: 'శబ్దం వద్దు', test_sound: 'విని చూడండి',
    no_audio: 'ఈ బ్రౌజర్‌లో శబ్దం ప్లే కాదు.',
    warn_minute: '1 నిమిషం మిగిలినప్పుడు మెల్లని బీప్',
    keys_cd: 'కీబోర్డ్: <kbd>Space</kbd> ప్రారంభం / ఆపడం · <kbd>R</kbd> రీసెట్ · <kbd>F</kbd> పూర్తి స్క్రీన్',
    lap: 'ల్యాప్', lap_n: 'ల్యాప్ {n}', laps: 'ల్యాప్‌లు', lap_time: 'ల్యాప్ సమయం', lap_secs: 'ల్యాప్ సమయం (సెకన్లు)', total_time: 'మొత్తం సమయం',
    no_laps: 'స్టాప్‌వాచ్ నడుస్తున్నప్పుడు ‘ల్యాప్’ నొక్కండి, ప్రతి సమయం సేవ్ అవుతుంది: పరుగు పందెం, సైన్స్ ప్రయోగాలు లేదా చదివే వేగం కోసం.',
    laps_count: 'ల్యాప్‌లు: {n}', average: 'సగటు ల్యాప్: {t}', fastest: 'అత్యంత వేగం', slowest: 'అత్యంత నెమ్మది', download_csv: 'CSV డౌన్‌లోడ్',
    keys_sw: 'కీబోర్డ్: <kbd>Space</kbd> ప్రారంభం / ఆపడం · <kbd>L</kbd> ల్యాప్ · <kbd>R</kbd> రీసెట్ · <kbd>F</kbd> పూర్తి స్క్రీన్',
    phase_work: 'ఏకాగ్రత సమయం', phase_short: 'చిన్న విరామం', phase_long: 'పెద్ద విరామం', session_of: '{m}లో సెషన్ {n}', skip: 'దాటవేయండి',
    plans: 'సిద్ధంగా ఉన్న ప్లాన్‌లు', plan_classic: 'క్లాసిక్ · 25 + 5', plan_class: 'ఒక పీరియడ్ · 20 + 5', plan_exam: 'పరీక్షల చదువు · 50 + 10', plan_young: 'చిన్న పిల్లలు · 10 + 2',
    po_settings: 'మీ ప్లాన్', work_len: 'ఏకాగ్రత (నిమిషాలు)', short_len: 'చిన్న విరామం (నిమిషాలు)', long_len: 'పెద్ద విరామం (నిమిషాలు)', long_every: 'ఎన్ని సెషన్ల తర్వాత పెద్ద విరామం',
    auto_next: 'తర్వాతి భాగాన్ని దానంతట అదే ప్రారంభించు',
    po_stats: 'పూర్తయిన సెషన్లు: {n} · మొత్తం ఏకాగ్రత: {m} నిమి.',
    po_what: 'పొమోడోరో పద్ధతి: నిర్ణీత సమయం ఒకే పనిపై పూర్తి శ్రద్ధ పెట్టండి, తర్వాత చిన్న విరామం తీసుకోండి. కొన్ని సెషన్ల తర్వాత పెద్ద విరామం తీసుకోండి.',
    po_work_over: 'ఏకాగ్రత సమయం ముగిసింది. ఇప్పుడు విరామం తీసుకోండి!', po_break_over: 'విరామం ముగిసింది. మళ్లీ పనిలోకి!', po_next_note: 'కొత్త సమయం తర్వాతి భాగం నుంచి వర్తిస్తుంది.',
    choose_sign: 'తరగతి కోసం ఒక బోర్డు ఎంచుకోండి', voice_level: 'గొంతు స్థాయి {n}', time_left: 'మిగిలిన సమయం: {t}',
    print_sign: 'ఈ బోర్డు ప్రింట్ చేయండి', print_all: 'అన్ని బోర్డులు ప్రింట్ చేయండి',
    keys_sg: 'కీబోర్డ్: <kbd>1</kbd>–<kbd>8</kbd> బోర్డు మార్చండి · <kbd>Space</kbd> కౌంట్‌డౌన్ ప్రారంభం / ఆపడం · <kbd>F</kbd> పూర్తి స్క్రీన్',
    sign_silent: 'నిశ్శబ్దంగా పని', sign_silent_d: 'మాట్లాడకూడదు. నీ పని నువ్వే చేయి.',
    sign_whisper: 'గుసగుస', sign_whisper_d: 'అవసరమైతేనే, చాలా మెల్లగా మాట్లాడు.',
    sign_partner: 'జతతో మాట', sign_partner_d: 'పక్కన ఉన్నవారితో మెల్లగా మాట్లాడు.',
    sign_group: 'గుంపుగా పని', sign_group_d: 'నీ గుంపులో చర్చించు. గొంతు తగ్గించి మాట్లాడు.',
    sign_hands: 'చేయి ఎత్తు', sign_hands_d: 'చేయి ఎత్తి, మాట్లాడటానికి నీ వంతు వచ్చే వరకు ఆగు.',
    sign_listen: 'నా వైపు చూడు', sign_listen_d: 'ఆగు, టీచర్ వైపు చూడు, శ్రద్ధగా విను.',
    sign_tidy: 'సర్దుకోండి', sign_tidy_d: 'నీ వస్తువులు సర్దుకుని బల్ల శుభ్రం చేయి.',
    sign_stretch: 'కొంచెం వ్యాయామం', sign_stretch_d: 'లేచి నిలబడు, చేతులు చాపు, దీర్ఘంగా శ్వాస తీసుకో.',
    help_title: 'ఎలా వాడాలి / తరగతి కోసం ఆలోచనలు',
    tip1: 'ఒక త్వరిత సమయాన్ని ఎంచుకోండి (లేదా మీ సమయం ఇవ్వండి), ‘ప్రారంభించండి’ నొక్కండి. చివరి నిమిషంలో వలయం నారింజ రంగుకు, సమయం అయిపోగానే ఎరుపుకు మారి మెల్లని అలారం మోగుతుంది.',
    tip2: 'ప్రొజెక్టర్ లేదా స్మార్ట్‌బోర్డ్‌పై చూపడానికి ‘పూర్తి స్క్రీన్’ నొక్కండి. కీలు: Space = ప్రారంభం / ఆపడం, R = రీసెట్, F = పూర్తి స్క్రీన్.',
    tip3: 'వేరే ట్యాబ్‌కు వెళ్లినా, స్క్రీన్ ఆగిపోయినా టైమర్ సరైన సమయాన్నే చూపిస్తుంది; బ్రౌజర్ ట్యాబ్‌లో కూడా మిగిలిన సమయం కనిపిస్తుంది.',
    tip4: 'తరగతి కార్యకలాపం (ఆలోచించు–జతతో చెప్పు–అందరితో పంచుకో): ఆలోచించడానికి 2 నిమిషాల కౌంట్‌డౌన్‌తో ‘నిశ్శబ్దంగా పని’ చూపండి, తర్వాత 3 నిమిషాలు ‘జతతో మాట’, తర్వాత జవాబులు చెప్పడానికి ‘చేయి ఎత్తు’.',
    tip5: 'సైన్స్ లేదా ఆటలు: స్టాప్‌వాచ్ ల్యాప్‌లతో లోలకం 10 డోలనాలు, 100 మీటర్ల పరుగు లేదా చదివే వేగాన్ని కొలవండి. సమయాలను CSVగా డౌన్‌లోడ్ చేసి Excelలో తెరవండి.',
    tip6: 'సొంతంగా చదువుకోవడానికి పొమోడోరో: 25 నిమిషాల ఏకాగ్రత + 5 నిమిషాల విరామం. 4 సెషన్ల తర్వాత పెద్ద విరామం తీసుకోండి.'
  },

  kn: {
    app_title: 'ತರಗತಿ ಟೈಮರ್',
    intro: 'ತರಗತಿಗಾಗಿ ದೊಡ್ಡ, ಸ್ಪಷ್ಟ ಟೈಮರ್‌ಗಳು: ಕೌಂಟ್‌ಡೌನ್, ಸ್ಟಾಪ್‌ವಾಚ್, ಪೊಮೊಡೊರೊ ಮತ್ತು ಕೆಲಸದ ವಿಧಾನ ಫಲಕಗಳು. ವಿದ್ಯಾರ್ಥಿಗಳು ಸಮಯವನ್ನು ಯೋಜಿಸಲು ಕಲಿಯುತ್ತಾರೆ ಮತ್ತು ಈಗ ಏನು ಮಾಡಬೇಕು ಎಂದು ಯಾವಾಗಲೂ ತಿಳಿಯುತ್ತಾರೆ.',
    tabs_label: 'ಟೈಮರ್ ಪ್ರಕಾರ',
    tab_countdown: 'ಕೌಂಟ್‌ಡೌನ್', tab_stopwatch: 'ಸ್ಟಾಪ್‌ವಾಚ್', tab_pomodoro: 'ಪೊಮೊಡೊರೊ', tab_signs: 'ಕೆಲಸದ ವಿಧಾನ',
    quick_times: 'ತ್ವರಿತ ಸಮಯಗಳು', min_short: 'ನಿಮಿಷ', min_n: '{n} ನಿಮಿಷ',
    custom_time: 'ನಿಮ್ಮ ಸಮಯ', hours: 'ಗಂಟೆ', minutes: 'ನಿಮಿಷ', seconds: 'ಸೆಕೆಂಡು', set_time: 'ಹೊಂದಿಸಿ',
    enter_time: 'ದಯವಿಟ್ಟು ಸೊನ್ನೆಗಿಂತ ಹೆಚ್ಚಿನ ಸಮಯ ನಮೂದಿಸಿ.',
    add_minute: '+1 ನಿಮಿಷ',
    activity_ph: 'ಈಗ ಏನು ಮಾಡುತ್ತಿದ್ದೇವೆ? (ಉದಾ. ಮೌನ ಓದು)', activity_label: 'ಚಟುವಟಿಕೆಯ ಹೆಸರು',
    btn_start: 'ಪ್ರಾರಂಭಿಸಿ', btn_pause: 'ನಿಲ್ಲಿಸಿ', btn_resume: 'ಮುಂದುವರಿಸಿ',
    st_ready: 'ಸಿದ್ಧ', st_running: 'ನಡೆಯುತ್ತಿದೆ', st_paused: 'ನಿಲ್ಲಿಸಲಾಗಿದೆ', ends_at: '{time}ಕ್ಕೆ ಮುಗಿಯುತ್ತದೆ',
    times_up: 'ಸಮಯ ಮುಗಿಯಿತು!', over_by: '{t} ಹೆಚ್ಚಾಯಿತು', start_again: 'ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ', exit_fullscreen: 'ಪೂರ್ಣ ಪರದೆ ಮುಚ್ಚಿ',
    sound: 'ಅಲಾರಂ ಧ್ವನಿ', sound_bell: 'ಗಂಟೆ', sound_beeps: 'ಬೀಪ್', sound_gong: 'ಆಳವಾದ ಗಂಟೆ', sound_off: 'ಧ್ವನಿ ಬೇಡ', test_sound: 'ಕೇಳಿ ನೋಡಿ',
    no_audio: 'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಪ್ಲೇ ಆಗುವುದಿಲ್ಲ.',
    warn_minute: '1 ನಿಮಿಷ ಉಳಿದಾಗ ಮೃದು ಬೀಪ್',
    keys_cd: 'ಕೀಬೋರ್ಡ್: <kbd>Space</kbd> ಪ್ರಾರಂಭ / ನಿಲ್ಲಿಸಿ · <kbd>R</kbd> ಮರುಹೊಂದಿಸಿ · <kbd>F</kbd> ಪೂರ್ಣ ಪರದೆ',
    lap: 'ಲ್ಯಾಪ್', lap_n: 'ಲ್ಯಾಪ್ {n}', laps: 'ಲ್ಯಾಪ್‌ಗಳು', lap_time: 'ಲ್ಯಾಪ್ ಸಮಯ', lap_secs: 'ಲ್ಯಾಪ್ ಸಮಯ (ಸೆಕೆಂಡು)', total_time: 'ಒಟ್ಟು ಸಮಯ',
    no_laps: 'ಸ್ಟಾಪ್‌ವಾಚ್ ನಡೆಯುತ್ತಿರುವಾಗ ‘ಲ್ಯಾಪ್’ ಒತ್ತಿ, ಪ್ರತಿ ಸಮಯ ಉಳಿಯುತ್ತದೆ: ಓಟದ ಸ್ಪರ್ಧೆ, ವಿಜ್ಞಾನ ಪ್ರಯೋಗ ಅಥವಾ ಓದುವ ವೇಗಕ್ಕಾಗಿ.',
    laps_count: 'ಲ್ಯಾಪ್‌ಗಳು: {n}', average: 'ಸರಾಸರಿ ಲ್ಯಾಪ್: {t}', fastest: 'ಅತಿ ವೇಗ', slowest: 'ಅತಿ ನಿಧಾನ', download_csv: 'CSV ಡೌನ್‌ಲೋಡ್',
    keys_sw: 'ಕೀಬೋರ್ಡ್: <kbd>Space</kbd> ಪ್ರಾರಂಭ / ನಿಲ್ಲಿಸಿ · <kbd>L</kbd> ಲ್ಯಾಪ್ · <kbd>R</kbd> ಮರುಹೊಂದಿಸಿ · <kbd>F</kbd> ಪೂರ್ಣ ಪರದೆ',
    phase_work: 'ಏಕಾಗ್ರತೆಯ ಸಮಯ', phase_short: 'ಸಣ್ಣ ವಿರಾಮ', phase_long: 'ದೀರ್ಘ ವಿರಾಮ', session_of: '{m}ರಲ್ಲಿ ಅವಧಿ {n}', skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    plans: 'ಸಿದ್ಧ ಯೋಜನೆಗಳು', plan_classic: 'ಕ್ಲಾಸಿಕ್ · 25 + 5', plan_class: 'ಒಂದು ಪೀರಿಯಡ್ · 20 + 5', plan_exam: 'ಪರೀಕ್ಷೆ ಓದು · 50 + 10', plan_young: 'ಚಿಕ್ಕ ಮಕ್ಕಳು · 10 + 2',
    po_settings: 'ನಿಮ್ಮ ಯೋಜನೆ', work_len: 'ಏಕಾಗ್ರತೆ (ನಿಮಿಷ)', short_len: 'ಸಣ್ಣ ವಿರಾಮ (ನಿಮಿಷ)', long_len: 'ದೀರ್ಘ ವಿರಾಮ (ನಿಮಿಷ)', long_every: 'ಎಷ್ಟು ಅವಧಿಗಳ ನಂತರ ದೀರ್ಘ ವಿರಾಮ',
    auto_next: 'ಮುಂದಿನ ಭಾಗವನ್ನು ತಾನಾಗಿಯೇ ಪ್ರಾರಂಭಿಸು',
    po_stats: 'ಮುಗಿದ ಅವಧಿಗಳು: {n} · ಒಟ್ಟು ಏಕಾಗ್ರತೆ: {m} ನಿಮಿಷ',
    po_what: 'ಪೊಮೊಡೊರೊ ವಿಧಾನ: ನಿಗದಿತ ಸಮಯ ಒಂದೇ ಕೆಲಸದ ಮೇಲೆ ಪೂರ್ಣ ಗಮನ ಕೊಡಿ, ನಂತರ ಸಣ್ಣ ವಿರಾಮ ತೆಗೆದುಕೊಳ್ಳಿ. ಕೆಲವು ಅವಧಿಗಳ ನಂತರ ದೀರ್ಘ ವಿರಾಮ ತೆಗೆದುಕೊಳ್ಳಿ.',
    po_work_over: 'ಏಕಾಗ್ರತೆಯ ಸಮಯ ಮುಗಿಯಿತು. ಈಗ ವಿರಾಮ ತೆಗೆದುಕೊಳ್ಳಿ!', po_break_over: 'ವಿರಾಮ ಮುಗಿಯಿತು. ಮತ್ತೆ ಕೆಲಸಕ್ಕೆ ಮರಳಿ!', po_next_note: 'ಹೊಸ ಸಮಯ ಮುಂದಿನ ಭಾಗದಿಂದ ಅನ್ವಯವಾಗುತ್ತದೆ.',
    choose_sign: 'ತರಗತಿಗಾಗಿ ಒಂದು ಫಲಕ ಆರಿಸಿ', voice_level: 'ಧ್ವನಿ ಮಟ್ಟ {n}', time_left: 'ಉಳಿದ ಸಮಯ: {t}',
    print_sign: 'ಈ ಫಲಕ ಮುದ್ರಿಸಿ', print_all: 'ಎಲ್ಲಾ ಫಲಕಗಳನ್ನು ಮುದ್ರಿಸಿ',
    keys_sg: 'ಕೀಬೋರ್ಡ್: <kbd>1</kbd>–<kbd>8</kbd> ಫಲಕ ಬದಲಿಸಿ · <kbd>Space</kbd> ಕೌಂಟ್‌ಡೌನ್ ಪ್ರಾರಂಭ / ನಿಲ್ಲಿಸಿ · <kbd>F</kbd> ಪೂರ್ಣ ಪರದೆ',
    sign_silent: 'ಮೌನವಾಗಿ ಕೆಲಸ', sign_silent_d: 'ಮಾತನಾಡಬೇಡಿ. ನಿಮ್ಮ ಕೆಲಸ ನೀವೇ ಮಾಡಿ.',
    sign_whisper: 'ಪಿಸುಮಾತು', sign_whisper_d: 'ಅಗತ್ಯವಿದ್ದರೆ ಮಾತ್ರ, ತುಂಬಾ ಮೆಲ್ಲಗೆ ಮಾತನಾಡಿ.',
    sign_partner: 'ಜೊತೆಗಾರರೊಂದಿಗೆ ಮಾತು', sign_partner_d: 'ಪಕ್ಕದಲ್ಲಿರುವವರೊಂದಿಗೆ ಮೆಲ್ಲಗೆ ಮಾತನಾಡಿ.',
    sign_group: 'ಗುಂಪು ಕೆಲಸ', sign_group_d: 'ನಿಮ್ಮ ಗುಂಪಿನಲ್ಲಿ ಚರ್ಚಿಸಿ. ಧ್ವನಿ ತಗ್ಗಿಸಿ.',
    sign_hands: 'ಕೈ ಎತ್ತಿ', sign_hands_d: 'ಕೈ ಎತ್ತಿ, ಮಾತನಾಡಲು ನಿಮ್ಮ ಸರದಿಗಾಗಿ ಕಾಯಿರಿ.',
    sign_listen: 'ನನ್ನ ಕಡೆ ನೋಡಿ', sign_listen_d: 'ನಿಲ್ಲಿ, ಶಿಕ್ಷಕರ ಕಡೆ ನೋಡಿ ಮತ್ತು ಗಮನವಿಟ್ಟು ಕೇಳಿ.',
    sign_tidy: 'ಸ್ವಚ್ಛಗೊಳಿಸಿ', sign_tidy_d: 'ನಿಮ್ಮ ವಸ್ತುಗಳನ್ನು ಎತ್ತಿಟ್ಟು ಡೆಸ್ಕ್ ಸ್ವಚ್ಛ ಮಾಡಿ.',
    sign_stretch: 'ಸ್ವಲ್ಪ ವ್ಯಾಯಾಮ', sign_stretch_d: 'ಎದ್ದು ನಿಲ್ಲಿ, ಕೈ ಚಾಚಿ ಮತ್ತು ಆಳವಾಗಿ ಉಸಿರಾಡಿ.',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ / ತರಗತಿಗಾಗಿ ಐಡಿಯಾಗಳು',
    tip1: 'ಒಂದು ತ್ವರಿತ ಸಮಯ ಆರಿಸಿ (ಅಥವಾ ನಿಮ್ಮ ಸಮಯ ನಮೂದಿಸಿ) ಮತ್ತು ‘ಪ್ರಾರಂಭಿಸಿ’ ಒತ್ತಿ. ಕೊನೆಯ ನಿಮಿಷದಲ್ಲಿ ವೃತ್ತ ಕಿತ್ತಳೆ ಬಣ್ಣಕ್ಕೆ, ಸಮಯ ಮುಗಿದಾಗ ಕೆಂಪು ಬಣ್ಣಕ್ಕೆ ತಿರುಗಿ ಮೃದುವಾದ ಅಲಾರಂ ಮೊಳಗುತ್ತದೆ.',
    tip2: 'ಪ್ರೊಜೆಕ್ಟರ್ ಅಥವಾ ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ತೋರಿಸಲು ‘ಪೂರ್ಣ ಪರದೆ’ ಒತ್ತಿ. ಕೀಲಿಗಳು: Space = ಪ್ರಾರಂಭ / ನಿಲ್ಲಿಸಿ, R = ಮರುಹೊಂದಿಸಿ, F = ಪೂರ್ಣ ಪರದೆ.',
    tip3: 'ಬೇರೆ ಟ್ಯಾಬ್‌ಗೆ ಹೋದರೂ ಅಥವಾ ಪರದೆ ಆಫ್ ಆದರೂ ಟೈಮರ್ ಸರಿಯಾದ ಸಮಯವನ್ನೇ ತೋರಿಸುತ್ತದೆ; ಬ್ರೌಸರ್ ಟ್ಯಾಬ್‌ನಲ್ಲೂ ಉಳಿದ ಸಮಯ ಕಾಣುತ್ತದೆ.',
    tip4: 'ತರಗತಿ ಚಟುವಟಿಕೆ (ಯೋಚಿಸು–ಜೊತೆಯಲ್ಲಿ ಹೇಳು–ಎಲ್ಲರೊಂದಿಗೆ ಹಂಚಿಕೋ): ಯೋಚಿಸಲು 2 ನಿಮಿಷದ ಕೌಂಟ್‌ಡೌನ್ ಜೊತೆ ‘ಮೌನವಾಗಿ ಕೆಲಸ’ ತೋರಿಸಿ, ನಂತರ 3 ನಿಮಿಷ ‘ಜೊತೆಗಾರರೊಂದಿಗೆ ಮಾತು’, ನಂತರ ಉತ್ತರ ಹೇಳಲು ‘ಕೈ ಎತ್ತಿ’.',
    tip5: 'ವಿಜ್ಞಾನ ಅಥವಾ ಆಟ: ಸ್ಟಾಪ್‌ವಾಚ್ ಲ್ಯಾಪ್‌ಗಳಿಂದ ಲೋಲಕದ 10 ತೂಗಾಟಗಳು, 100 ಮೀಟರ್ ಓಟ ಅಥವಾ ಓದುವ ವೇಗವನ್ನು ಅಳೆಯಿರಿ. ಸಮಯಗಳನ್ನು CSV ಆಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ Excel ನಲ್ಲಿ ತೆರೆಯಿರಿ.',
    tip6: 'ಸ್ವಂತ ಓದಿಗೆ ಪೊಮೊಡೊರೊ: 25 ನಿಮಿಷ ಏಕಾಗ್ರತೆ + 5 ನಿಮಿಷ ವಿರಾಮ. 4 ಅವಧಿಗಳ ನಂತರ ದೀರ್ಘ ವಿರಾಮ ತೆಗೆದುಕೊಳ್ಳಿ.'
  },

  ml: {
    app_title: 'ക്ലാസ്റൂം ടൈമർ',
    intro: 'ക്ലാസിനായി വലുതും വ്യക്തവുമായ ടൈമറുകൾ: കൗണ്ട്ഡൗൺ, സ്റ്റോപ്പ് വാച്ച്, പൊമോഡോറോ, പ്രവർത്തന രീതി ബോർഡുകൾ. കുട്ടികൾ സമയം ആസൂത്രണം ചെയ്യാൻ പഠിക്കുന്നു, ഇപ്പോൾ എന്താണ് ചെയ്യേണ്ടതെന്ന് എപ്പോഴും അറിയുന്നു.',
    tabs_label: 'ടൈമർ തരം',
    tab_countdown: 'കൗണ്ട്ഡൗൺ', tab_stopwatch: 'സ്റ്റോപ്പ് വാച്ച്', tab_pomodoro: 'പൊമോഡോറോ', tab_signs: 'പ്രവർത്തന രീതി',
    quick_times: 'പെട്ടെന്നുള്ള സമയങ്ങൾ', min_short: 'മിനിറ്റ്', min_n: '{n} മിനിറ്റ്',
    custom_time: 'നിങ്ങളുടെ സമയം', hours: 'മണിക്കൂർ', minutes: 'മിനിറ്റ്', seconds: 'സെക്കൻഡ്', set_time: 'സജ്ജമാക്കുക',
    enter_time: 'ദയവായി പൂജ്യത്തേക്കാൾ കൂടുതൽ സമയം നൽകുക.',
    add_minute: '+1 മിനിറ്റ്',
    activity_ph: 'എന്താണ് ചെയ്യുന്നത്? (ഉദാ. വായന)', activity_label: 'പ്രവർത്തനത്തിന്റെ പേര്',
    btn_start: 'ആരംഭിക്കുക', btn_pause: 'നിർത്തുക', btn_resume: 'തുടരുക',
    st_ready: 'തയ്യാർ', st_running: 'ഓടുന്നു', st_paused: 'നിർത്തിവെച്ചു', ends_at: '{time}-ന് അവസാനിക്കും',
    times_up: 'സമയം കഴിഞ്ഞു!', over_by: '{t} അധികമായി', start_again: 'വീണ്ടും തുടങ്ങുക', exit_fullscreen: 'പൂർണ്ണ സ്ക്രീൻ അടയ്ക്കുക',
    sound: 'അലാറം ശബ്ദം', sound_bell: 'മണി', sound_beeps: 'ബീപ്', sound_gong: 'ആഴമുള്ള മണിനാദം', sound_off: 'ശബ്ദം വേണ്ട', test_sound: 'കേട്ടുനോക്കൂ',
    no_audio: 'ഈ ബ്രൗസറിൽ ശബ്ദം പ്ലേ ചെയ്യാൻ കഴിയില്ല.',
    warn_minute: '1 മിനിറ്റ് ബാക്കിയുള്ളപ്പോൾ മൃദുവായ ബീപ്',
    keys_cd: 'കീബോർഡ്: <kbd>Space</kbd> തുടങ്ങുക / നിർത്തുക · <kbd>R</kbd> റീസെറ്റ് · <kbd>F</kbd> പൂർണ്ണ സ്ക്രീൻ',
    lap: 'ലാപ്', lap_n: 'ലാപ് {n}', laps: 'ലാപ്പുകൾ', lap_time: 'ലാപ് സമയം', lap_secs: 'ലാപ് സമയം (സെക്കൻഡ്)', total_time: 'ആകെ സമയം',
    no_laps: 'സ്റ്റോപ്പ് വാച്ച് ഓടുമ്പോൾ ‘ലാപ്’ അമർത്തുക, ഓരോ സമയവും സേവ് ആകും: ഓട്ടമത്സരം, ശാസ്ത്ര പരീക്ഷണം അല്ലെങ്കിൽ വായനാവേഗം അളക്കാൻ.',
    laps_count: 'ലാപ്പുകൾ: {n}', average: 'ശരാശരി ലാപ്: {t}', fastest: 'ഏറ്റവും വേഗം', slowest: 'ഏറ്റവും പതുക്കെ', download_csv: 'CSV ഡൗൺലോഡ്',
    keys_sw: 'കീബോർഡ്: <kbd>Space</kbd> തുടങ്ങുക / നിർത്തുക · <kbd>L</kbd> ലാപ് · <kbd>R</kbd> റീസെറ്റ് · <kbd>F</kbd> പൂർണ്ണ സ്ക്രീൻ',
    phase_work: 'ശ്രദ്ധാസമയം', phase_short: 'ചെറിയ ഇടവേള', phase_long: 'നീണ്ട ഇടവേള', session_of: '{m}-ൽ സെഷൻ {n}', skip: 'ഒഴിവാക്കുക',
    plans: 'തയ്യാറായ പ്ലാനുകൾ', plan_classic: 'ക്ലാസിക് · 25 + 5', plan_class: 'ഒരു പീരിയഡ് · 20 + 5', plan_exam: 'പരീക്ഷാ പഠനം · 50 + 10', plan_young: 'ചെറിയ കുട്ടികൾ · 10 + 2',
    po_settings: 'നിങ്ങളുടെ പ്ലാൻ', work_len: 'ശ്രദ്ധ (മിനിറ്റ്)', short_len: 'ചെറിയ ഇടവേള (മിനിറ്റ്)', long_len: 'നീണ്ട ഇടവേള (മിനിറ്റ്)', long_every: 'എത്ര സെഷനുകൾക്ക് ശേഷം നീണ്ട ഇടവേള',
    auto_next: 'അടുത്ത ഭാഗം സ്വയം തുടങ്ങട്ടെ',
    po_stats: 'പൂർത്തിയായ സെഷനുകൾ: {n} · ആകെ ശ്രദ്ധ: {m} മിനിറ്റ്',
    po_what: 'പൊമോഡോറോ രീതി: നിശ്ചിത സമയം ഒരു ജോലിയിൽ മുഴുവൻ ശ്രദ്ധ കൊടുക്കുക, പിന്നെ ചെറിയ ഇടവേള എടുക്കുക. കുറച്ച് സെഷനുകൾക്ക് ശേഷം നീണ്ട ഇടവേള എടുക്കുക.',
    po_work_over: 'ശ്രദ്ധാസമയം കഴിഞ്ഞു. ഇനി ഇടവേള എടുക്കൂ!', po_break_over: 'ഇടവേള കഴിഞ്ഞു. വീണ്ടും ജോലിയിലേക്ക്!', po_next_note: 'പുതിയ സമയം അടുത്ത ഭാഗം മുതൽ ബാധകമാകും.',
    choose_sign: 'ക്ലാസിനായി ഒരു ബോർഡ് തിരഞ്ഞെടുക്കുക', voice_level: 'ശബ്ദനില {n}', time_left: 'ബാക്കി സമയം: {t}',
    print_sign: 'ഈ ബോർഡ് പ്രിന്റ് ചെയ്യുക', print_all: 'എല്ലാ ബോർഡുകളും പ്രിന്റ് ചെയ്യുക',
    keys_sg: 'കീബോർഡ്: <kbd>1</kbd>–<kbd>8</kbd> ബോർഡ് മാറ്റുക · <kbd>Space</kbd> കൗണ്ട്ഡൗൺ തുടങ്ങുക / നിർത്തുക · <kbd>F</kbd> പൂർണ്ണ സ്ക്രീൻ',
    sign_silent: 'നിശ്ശബ്ദമായി ജോലി', sign_silent_d: 'സംസാരിക്കരുത്. നിന്റെ ജോലി നീ തന്നെ ചെയ്യൂ.',
    sign_whisper: 'പതിഞ്ഞ ശബ്ദം', sign_whisper_d: 'ആവശ്യമെങ്കിൽ മാത്രം, വളരെ പതുക്കെ സംസാരിക്കൂ.',
    sign_partner: 'കൂട്ടുകാരനോട് സംസാരം', sign_partner_d: 'അടുത്തിരിക്കുന്നയാളോട് പതുക്കെ സംസാരിക്കൂ.',
    sign_group: 'ഗ്രൂപ്പ് ജോലി', sign_group_d: 'നിന്റെ ഗ്രൂപ്പിൽ ചർച്ച ചെയ്യൂ. ശബ്ദം താഴ്ത്തി വെക്കൂ.',
    sign_hands: 'കൈ ഉയർത്തൂ', sign_hands_d: 'കൈ ഉയർത്തി, സംസാരിക്കാൻ നിന്റെ ഊഴം വരെ കാത്തിരിക്കൂ.',
    sign_listen: 'എന്നെ നോക്കൂ', sign_listen_d: 'നിർത്തൂ, അധ്യാപകനെ നോക്കൂ, ശ്രദ്ധിച്ച് കേൾക്കൂ.',
    sign_tidy: 'വൃത്തിയാക്കൂ', sign_tidy_d: 'സാധനങ്ങൾ എടുത്തുവെച്ച് ഡെസ്ക് വൃത്തിയാക്കൂ.',
    sign_stretch: 'ചെറിയ വ്യായാമം', sign_stretch_d: 'എഴുന്നേറ്റു നിൽക്കൂ, കൈകൾ നീട്ടൂ, ആഴത്തിൽ ശ്വസിക്കൂ.',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ക്ലാസിനുള്ള ആശയങ്ങൾ',
    tip1: 'ഒരു പെട്ടെന്നുള്ള സമയം തിരഞ്ഞെടുക്കുക (അല്ലെങ്കിൽ സ്വന്തം സമയം നൽകുക), ‘ആരംഭിക്കുക’ അമർത്തുക. അവസാന മിനിറ്റിൽ വളയം ഓറഞ്ചും സമയം കഴിയുമ്പോൾ ചുവപ്പുമാകും, ഒപ്പം മൃദുവായ അലാറം മുഴങ്ങും.',
    tip2: 'പ്രൊജക്ടറിലോ സ്മാർട്ട്ബോർഡിലോ കാണിക്കാൻ ‘പൂർണ്ണ സ്ക്രീൻ’ അമർത്തുക. കീകൾ: Space = തുടങ്ങുക / നിർത്തുക, R = റീസെറ്റ്, F = പൂർണ്ണ സ്ക്രീൻ.',
    tip3: 'മറ്റൊരു ടാബിലേക്ക് പോയാലും സ്ക്രീൻ ഓഫായാലും ടൈമർ ശരിയായ സമയം തന്നെ കാണിക്കും; ബ്രൗസർ ടാബിലും ബാക്കി സമയം കാണാം.',
    tip4: 'ക്ലാസ് പ്രവർത്തനം (ചിന്തിക്കൂ–ജോടിയായി പറയൂ–എല്ലാവരോടും പങ്കിടൂ): ചിന്തിക്കാൻ 2 മിനിറ്റ് കൗണ്ട്ഡൗണിനൊപ്പം ‘നിശ്ശബ്ദമായി ജോലി’ കാണിക്കുക, പിന്നെ 3 മിനിറ്റ് ‘കൂട്ടുകാരനോട് സംസാരം’, പിന്നെ ഉത്തരം പറയാൻ ‘കൈ ഉയർത്തൂ’.',
    tip5: 'ശാസ്ത്രം അല്ലെങ്കിൽ കായികം: സ്റ്റോപ്പ് വാച്ച് ലാപ്പുകൾ ഉപയോഗിച്ച് പെൻഡുലത്തിന്റെ 10 ആട്ടങ്ങൾ, 100 മീറ്റർ ഓട്ടം അല്ലെങ്കിൽ വായനാവേഗം അളക്കുക. സമയങ്ങൾ CSV ആയി ഡൗൺലോഡ് ചെയ്ത് Excel-ൽ തുറക്കാം.',
    tip6: 'സ്വയം പഠിക്കാൻ പൊമോഡോറോ: 25 മിനിറ്റ് ശ്രദ്ധ + 5 മിനിറ്റ് ഇടവേള. 4 സെഷനുകൾക്ക് ശേഷം നീണ്ട ഇടവേള എടുക്കുക.'
  },

  ur: {
    app_title: 'کلاس روم ٹائمر',
    intro: 'کلاس کے لیے بڑے اور صاف ٹائمر: الٹی گنتی، اسٹاپ واچ، پومودورو اور کام کے طریقے کے بورڈ۔ طلبہ وقت کی منصوبہ بندی سیکھتے ہیں اور ہمیشہ جانتے ہیں کہ ابھی کیا کرنا ہے۔',
    tabs_label: 'ٹائمر کی قسم',
    tab_countdown: 'الٹی گنتی', tab_stopwatch: 'اسٹاپ واچ', tab_pomodoro: 'پومودورو', tab_signs: 'کام کا طریقہ',
    quick_times: 'فوری وقت', min_short: 'منٹ', min_n: '{n} منٹ',
    custom_time: 'اپنا وقت', hours: 'گھنٹے', minutes: 'منٹ', seconds: 'سیکنڈ', set_time: 'سیٹ کریں',
    enter_time: 'براہ کرم صفر سے زیادہ وقت لکھیں۔',
    add_minute: '⁦+1⁩ منٹ',
    activity_ph: 'ابھی کیا کر رہے ہیں؟ (جیسے: خاموش مطالعہ)', activity_label: 'سرگرمی کا نام',
    btn_start: 'شروع کریں', btn_pause: 'روکیں', btn_resume: 'دوبارہ شروع کریں',
    st_ready: 'تیار', st_running: 'چل رہا ہے', st_paused: 'رکا ہوا', ends_at: '{time} پر ختم',
    times_up: 'وقت ختم!', over_by: '{t} زیادہ ہو گئے', start_again: 'دوبارہ شروع کریں', exit_fullscreen: 'پوری اسکرین بند کریں',
    sound: 'الارم کی آواز', sound_bell: 'گھنٹی', sound_beeps: 'بیپ', sound_gong: 'گہری گھنٹی', sound_off: 'کوئی آواز نہیں', test_sound: 'سن کر دیکھیں',
    no_audio: 'اس براؤزر میں آواز نہیں چل سکتی۔',
    warn_minute: '1 منٹ باقی رہنے پر ہلکی بیپ',
    keys_cd: 'کی بورڈ: <kbd>Space</kbd> شروع / روکیں · <kbd>R</kbd> ری سیٹ · <kbd>F</kbd> پوری اسکرین',
    lap: 'لیپ', lap_n: 'لیپ {n}', laps: 'لیپس', lap_time: 'لیپ کا وقت', lap_secs: 'لیپ کا وقت (سیکنڈ)', total_time: 'کل وقت',
    no_laps: 'اسٹاپ واچ چلتے وقت ’لیپ‘ دبائیں، ہر وقت محفوظ ہو جائے گا: دوڑ، سائنس کے تجربے یا پڑھنے کی رفتار کے لیے۔',
    laps_count: 'لیپ: {n}', average: 'اوسط لیپ: {t}', fastest: 'سب سے تیز', slowest: 'سب سے سست', download_csv: 'CSV ڈاؤن لوڈ کریں',
    keys_sw: 'کی بورڈ: <kbd>Space</kbd> شروع / روکیں · <kbd>L</kbd> لیپ · <kbd>R</kbd> ری سیٹ · <kbd>F</kbd> پوری اسکرین',
    phase_work: 'توجہ کا وقت', phase_short: 'چھوٹا وقفہ', phase_long: 'لمبا وقفہ', session_of: '{m} میں سے سیشن {n}', skip: 'چھوڑیں',
    plans: 'تیار منصوبے', plan_classic: 'کلاسک · 25 + 5', plan_class: 'ایک پیریڈ · 20 + 5', plan_exam: 'امتحان کی تیاری · 50 + 10', plan_young: 'چھوٹے بچے · 10 + 2',
    po_settings: 'اپنا منصوبہ', work_len: 'توجہ (منٹ)', short_len: 'چھوٹا وقفہ (منٹ)', long_len: 'لمبا وقفہ (منٹ)', long_every: 'کتنے سیشن کے بعد لمبا وقفہ',
    auto_next: 'اگلا حصہ خود بخود شروع کریں',
    po_stats: 'مکمل سیشن: {n} · کل توجہ: {m} منٹ',
    po_what: 'پومودورو طریقہ: مقررہ وقت تک ایک ہی کام پر پوری توجہ دیں، پھر چھوٹا وقفہ لیں۔ چند سیشن کے بعد لمبا وقفہ لیں۔',
    po_work_over: 'توجہ کا وقت ختم۔ اب وقفہ لیں!', po_break_over: 'وقفہ ختم۔ پھر سے کام پر لگ جائیں!', po_next_note: 'نیا وقت اگلے حصے سے لاگو ہوگا۔',
    choose_sign: 'کلاس کے لیے بورڈ چنیں', voice_level: 'آواز کی سطح {n}', time_left: 'باقی وقت: {t}',
    print_sign: 'یہ بورڈ پرنٹ کریں', print_all: 'سارے بورڈ پرنٹ کریں',
    keys_sg: 'کی بورڈ: <kbd>1</kbd>–<kbd>8</kbd> بورڈ بدلیں · <kbd>Space</kbd> الٹی گنتی شروع / روکیں · <kbd>F</kbd> پوری اسکرین',
    sign_silent: 'خاموشی سے کام', sign_silent_d: 'بات نہیں کرنی۔ اپنا کام خود کریں۔',
    sign_whisper: 'دھیمی آواز', sign_whisper_d: 'ضرورت ہو تبھی، بہت آہستہ بولیں۔',
    sign_partner: 'ساتھی سے بات', sign_partner_d: 'پاس بیٹھے ساتھی سے آہستہ بات کریں۔',
    sign_group: 'گروپ میں کام', sign_group_d: 'اپنے گروپ میں بات چیت کریں۔ آواز دھیمی رکھیں۔',
    sign_hands: 'ہاتھ اٹھائیں', sign_hands_d: 'ہاتھ اٹھائیں اور بولنے کے لیے اپنی باری کا انتظار کریں۔',
    sign_listen: 'میری طرف دیکھیں', sign_listen_d: 'رکیں، استاد کی طرف دیکھیں اور غور سے سنیں۔',
    sign_tidy: 'صفائی کا وقت', sign_tidy_d: 'اپنا سامان سمیٹیں اور ڈیسک صاف کریں۔',
    sign_stretch: 'ہلکی ورزش', sign_stretch_d: 'کھڑے ہوں، بازو پھیلائیں اور گہری سانس لیں۔',
    help_title: 'استعمال کیسے کریں / کلاس کے لیے خیالات',
    tip1: 'کوئی فوری وقت چنیں (یا اپنا وقت لکھیں) اور ’شروع کریں‘ دبائیں۔ آخری منٹ میں دائرہ نارنجی اور وقت ختم ہونے پر سرخ ہو جاتا ہے، ساتھ ہلکا الارم بجتا ہے۔',
    tip2: 'پروجیکٹر یا اسمارٹ بورڈ پر دکھانے کے لیے ’پوری اسکرین‘ دبائیں۔ کی بورڈ: Space = شروع / روکیں، R = ری سیٹ، F = پوری اسکرین۔',
    tip3: 'دوسرا ٹیب کھولنے یا اسکرین بند ہونے پر بھی ٹائمر صحیح وقت رکھتا ہے، اور براؤزر ٹیب پر باقی وقت دکھائی دیتا ہے۔',
    tip4: 'کلاس سرگرمی (سوچیں–جوڑی میں بولیں–سب کو بتائیں): سوچنے کے لیے 2 منٹ کی الٹی گنتی کے ساتھ ’خاموشی سے کام‘ دکھائیں، پھر 3 منٹ ’ساتھی سے بات‘، پھر جواب بتانے کے لیے ’ہاتھ اٹھائیں‘۔',
    tip5: 'سائنس یا کھیل: اسٹاپ واچ کے لیپ سے پنڈولم کے 10 جھولے، 100 میٹر دوڑ یا پڑھنے کی رفتار ناپیں۔ اوقات کو CSV میں ڈاؤن لوڈ کر کے Excel میں کھولیں۔',
    tip6: 'خود پڑھائی کے لیے پومودورو: 25 منٹ توجہ + 5 منٹ وقفہ۔ 4 سیشن کے بعد لمبا وقفہ لیں۔'
  }
};
