/* Prompt Builder: UI strings. Keys must be identical in all 12 languages.
   Shared words (copy, delete, print, fullscreen, saved_local …) come from EDU.COMMON. */
window.APP_STRINGS = window.APP_STRINGS || {};
window.APP_STRINGS.en = {
  app_title: "Prompt Builder",
  intro: "Write clear, complete prompts for any free AI chatbot, and learn what makes a prompt work well.",
  howto_title: "How to use / Ideas for the classroom",
  how1: "Tap a template, or press “Clear form” and start fresh. Replace everything in [square brackets] with your own details.",
  how2: "Fill the six key parts: role, task, context, audience, format and rules. The quality meter shows what is missing.",
  how3: "Choose the language of the answer. Copy the prompt and paste it into any free AI chatbot, such as ChatGPT, Gemini, Copilot or Claude.",
  how4: "Classroom activity: give two groups the same topic. One group writes a one-line prompt, the other uses all six parts. Try both in an AI chatbot and compare the answers. Which is more useful, and why?",
  how5: "Save prompts that work well in Favourites, or share a link with other teachers. Favourites stay only on this device.",
  inside_title: "What happens inside an AI chatbot?",
  inside_text: "An AI chatbot does not know you, your class or your syllabus. It reads your words and predicts a likely helpful answer, one word at a time. A clear role, task, context and format give it better clues, so the answer fits your students. It can still be wrong, so always check.",
  templates_h: "Start from a template",
  templates_hint: "Tap a template to fill the form. It is written in the answer language you choose below.",
  builder_h: "Build your prompt",
  clear_form: "Clear form",
  f_role: "1. Role: who should the AI be?",
  f_role_hint: "Your prompt will begin with “You are …”.",
  ph_role: "e.g. a friendly Class 7 science teacher",
  f_task: "2. Task: what exactly should it do?",
  ph_task: "e.g. Explain evaporation with 3 examples from daily life",
  f_context: "3. Context: what background does the AI need?",
  ph_context: "e.g. Class 7, NCERT Science, a village school with 40 students",
  f_aud: "4. Audience",
  f_fmt: "5. Format of the answer",
  f_tone: "Tone",
  f_len: "Length",
  f_lang: "Language of the answer",
  f_cons: "6. Rules to follow (one per line)",
  ph_cons: "e.g. Use simple words",
  quick_add: "Quick add:",
  f_ex: "Example (optional): show the style you want",
  ph_ex: "Paste a short sample question or answer",
  opt_none: "— Choose —",
  aud_c1_5: "Class 1–5",
  aud_c6_8: "Class 6–8",
  aud_c9_10: "Class 9–10",
  aud_c11_12: "Class 11–12",
  aud_ug: "College students",
  aud_teachers: "Teachers",
  aud_parents: "Parents",
  aud_general: "Everyone (general)",
  fmt_list: "List of points",
  fmt_table: "Table",
  fmt_paragraph: "Paragraphs",
  fmt_quiz: "Quiz (MCQs)",
  fmt_steps: "Step by step",
  fmt_letter: "Letter / notice",
  tone_friendly: "Friendly",
  tone_formal: "Formal",
  tone_encouraging: "Encouraging",
  tone_simple: "Simple and clear",
  tone_fun: "Fun",
  tone_neutral: "Neutral",
  len_vshort: "Very short (about 100 words)",
  len_short: "Short (150–250 words)",
  len_medium: "Medium (300–500 words)",
  len_long: "Detailed",
  opt_ask: "Ask me questions first if something important is missing",
  opt_unsure: "Say “not sure” instead of guessing",
  preview_h: "Your prompt",
  preview_note: "Written in {lang}. The words you typed stay exactly as you typed them.",
  empty_preview: "Write a task or tap a template. Your prompt will appear here.",
  counts: "{c} characters · {w} words",
  copy_prompt: "Copy prompt",
  share_link: "Share link",
  download_txt: "Download .txt",
  fav_name_ph: "Name (optional)",
  fav_name_label: "Name for this prompt",
  save_fav: "Save to favourites",
  quality_h: "Prompt quality",
  q_role: "Role",
  q_task: "Task",
  q_context: "Context",
  q_aud: "Audience",
  q_fmt: "Format",
  q_cons: "Rules",
  tip_role: "Give the AI a role, e.g. “an experienced maths teacher”. It changes the style and depth of the answer.",
  tip_task: "Say exactly what you want, with numbers: “10 MCQs”, “a 40-minute lesson plan”.",
  tip_task_short: "Your task is very short. Add the topic, the class and how many items you need.",
  tip_context: "Add background: class, subject, chapter, and what students already know.",
  tip_aud: "Choose who the answer is for, so the AI uses the right words.",
  tip_fmt: "Choose a format (list, table, quiz…) so the answer is ready to use.",
  tip_cons: "Add one or two rules, like “use Indian examples” or “give an answer key”.",
  tip_brackets: "Fill in the blanks in [square brackets]: {list}",
  all_good: "All six parts are there. Copy the prompt and try it!",
  lvl_0: "Needs work",
  lvl_1: "Good start",
  lvl_2: "Strong prompt",
  lvl_3: "Excellent prompt!",
  pii_warn: "Careful! This looks like personal data: {what}. Remove it before you paste the prompt into an AI chatbot.",
  pii_phone: "a phone number",
  pii_aadhaar: "an Aadhaar-like number",
  pii_email: "an email address",
  safety_h: "Use AI safely",
  safe1: "Never paste personal data: phone numbers, Aadhaar numbers, addresses, or marks with student names.",
  safe2: "Always check facts, dates and answers with your NCERT textbook or another trusted source.",
  safe3: "AI can be wrong or biased. Read every answer before you use it with students.",
  safe4: "Ask the AI for its sources and check them yourself. AI sometimes invents sources.",
  safe5: "Use AI to learn and to plan, not to copy homework. Write your final work in your own words.",
  safe6: "Many AI chatbots are only for users aged 13 or older. Younger students should use them with a teacher or parent.",
  favs_h: "Favourites",
  favs_empty: "No saved prompts yet. Build a prompt and press “Save to favourites”.",
  fav_load: "Load",
  fav_saved: "Saved to favourites",
  fav_loaded: "Prompt loaded",
  tpl_loaded: "Template loaded: {name}",
  tpl_switched: "Template text changed to {lang}",
  shared_loaded: "Prompt opened from a shared link",
  untitled: "My prompt",
  confirm_replace: "Replace what you have typed with this template?",
  confirm_clear: "Clear the whole form?",
  confirm_del: "Delete this saved prompt?",
  nothing_to_copy: "The prompt is empty. Write a task first.",
  saved_count: "{n} saved",
  lang_en: "English",
  lang_hi: "Hindi",
  lang_bn: "Bengali",
  lang_mr: "Marathi",
  lang_gu: "Gujarati",
  lang_pa: "Punjabi",
  lang_or: "Odia",
  lang_ta: "Tamil",
  lang_te: "Telugu",
  lang_kn: "Kannada",
  lang_ml: "Malayalam",
  lang_ur: "Urdu"
};
["hi","bn","mr","gu","pa","or","ta","te","kn","ml","ur"].forEach(function(l){window.APP_STRINGS[l]=window.APP_STRINGS.en;});
