/* Time Zone Meeting Planner: friendly city names for popular IANA time zones, in 12 languages.
   Same keys in every language (window.APP_CONTENT[lang].cities[ianaId] = "City, Country").
   Zones not listed here still work; they are shown with their IANA name. */
window.APP_CONTENT = {
  en: { cities: {
    'Asia/Kolkata': "India",
    'Asia/Dubai': "Dubai, UAE",
    'Asia/Riyadh': "Riyadh, Saudi Arabia",
    'Asia/Qatar': "Doha, Qatar",
    'Asia/Kuwait': "Kuwait City, Kuwait",
    'Asia/Bahrain': "Manama, Bahrain",
    'Asia/Muscat': "Muscat, Oman",
    'Asia/Tehran': "Tehran, Iran",
    'Asia/Jerusalem': "Tel Aviv, Israel",
    'Asia/Karachi': "Karachi, Pakistan",
    'Asia/Kabul': "Kabul, Afghanistan",
    'Asia/Kathmandu': "Kathmandu, Nepal",
    'Asia/Dhaka': "Dhaka, Bangladesh",
    'Asia/Colombo': "Colombo, Sri Lanka",
    'Asia/Thimphu': "Thimphu, Bhutan",
    'Asia/Yangon': "Yangon, Myanmar",
    'Asia/Bangkok': "Bangkok, Thailand",
    'Asia/Jakarta': "Jakarta, Indonesia",
    'Asia/Kuala_Lumpur': "Kuala Lumpur, Malaysia",
    'Asia/Singapore': "Singapore",
    'Asia/Ho_Chi_Minh': "Ho Chi Minh City, Vietnam",
    'Asia/Manila': "Manila, Philippines",
    'Asia/Hong_Kong': "Hong Kong",
    'Asia/Shanghai': "Beijing / Shanghai, China",
    'Asia/Taipei': "Taipei, Taiwan",
    'Asia/Seoul': "Seoul, South Korea",
    'Asia/Tokyo': "Tokyo, Japan",
    'Asia/Tashkent': "Tashkent, Uzbekistan",
    'Asia/Almaty': "Almaty, Kazakhstan",
    'Asia/Baku': "Baku, Azerbaijan",
    'Europe/London': "London, UK",
    'Europe/Dublin': "Dublin, Ireland",
    'Europe/Lisbon': "Lisbon, Portugal",
    'Europe/Madrid': "Madrid, Spain",
    'Europe/Paris': "Paris, France",
    'Europe/Brussels': "Brussels, Belgium",
    'Europe/Amsterdam': "Amsterdam, Netherlands",
    'Europe/Berlin': "Berlin, Germany",
    'Europe/Zurich': "Zurich, Switzerland",
    'Europe/Rome': "Rome, Italy",
    'Europe/Vienna': "Vienna, Austria",
    'Europe/Prague': "Prague, Czechia",
    'Europe/Warsaw': "Warsaw, Poland",
    'Europe/Stockholm': "Stockholm, Sweden",
    'Europe/Oslo': "Oslo, Norway",
    'Europe/Copenhagen': "Copenhagen, Denmark",
    'Europe/Helsinki': "Helsinki, Finland",
    'Europe/Athens': "Athens, Greece",
    'Europe/Istanbul': "Istanbul, Turkey",
    'Europe/Kyiv': "Kyiv, Ukraine",
    'Europe/Moscow': "Moscow, Russia",
    'Africa/Cairo': "Cairo, Egypt",
    'Africa/Nairobi': "Nairobi, Kenya",
    'Africa/Johannesburg': "Johannesburg, South Africa",
    'Africa/Lagos': "Lagos, Nigeria",
    'Africa/Casablanca': "Casablanca, Morocco",
    'Indian/Mauritius': "Port Louis, Mauritius",
    'America/New_York': "New York, USA",
    'America/Toronto': "Toronto, Canada",
    'America/Chicago': "Chicago, USA",
    'America/Denver': "Denver, USA",
    'America/Phoenix': "Phoenix, USA",
    'America/Los_Angeles': "Los Angeles / San Francisco, USA",
    'America/Vancouver': "Vancouver, Canada",
    'America/Anchorage': "Anchorage, USA",
    'Pacific/Honolulu': "Honolulu, Hawaii",
    'America/Mexico_City': "Mexico City, Mexico",
    'America/Bogota': "Bogotá, Colombia",
    'America/Lima': "Lima, Peru",
    'America/Santiago': "Santiago, Chile",
    'America/Sao_Paulo': "São Paulo, Brazil",
    'America/Argentina/Buenos_Aires': "Buenos Aires, Argentina",
    'America/Halifax': "Halifax, Canada",
    'Australia/Perth': "Perth, Australia",
    'Australia/Adelaide': "Adelaide, Australia",
    'Australia/Brisbane': "Brisbane, Australia",
    'Australia/Sydney': "Sydney, Australia",
    'Australia/Melbourne': "Melbourne, Australia",
    'Pacific/Auckland': "Auckland, New Zealand",
    'UTC': "UTC (world standard time)"
  } },
  hi: { cities: {
    'Asia/Kolkata': "भारत",
    'Asia/Dubai': "दुबई, UAE",
    'Asia/Riyadh': "रियाद, सऊदी अरब",
    'Asia/Qatar': "दोहा, क़तर",
    'Asia/Kuwait': "कुवैत सिटी, कुवैत",
    'Asia/Bahrain': "मनामा, बहरीन",
    'Asia/Muscat': "मस्कट, ओमान",
    'Asia/Tehran': "तेहरान, ईरान",
    'Asia/Jerusalem': "तेल अवीव, इज़राइल",
    'Asia/Karachi': "कराची, पाकिस्तान",
    'Asia/Kabul': "काबुल, अफ़ग़ानिस्तान",
    'Asia/Kathmandu': "काठमांडू, नेपाल",
    'Asia/Dhaka': "ढाका, बांग्लादेश",
    'Asia/Colombo': "कोलंबो, श्रीलंका",
    'Asia/Thimphu': "थिम्पू, भूटान",
    'Asia/Yangon': "यांगून, म्यांमार",
    'Asia/Bangkok': "बैंकॉक, थाईलैंड",
    'Asia/Jakarta': "जकार्ता, इंडोनेशिया",
    'Asia/Kuala_Lumpur': "कुआलालंपुर, मलेशिया",
    'Asia/Singapore': "सिंगापुर",
    'Asia/Ho_Chi_Minh': "हो ची मिन्ह सिटी, वियतनाम",
    'Asia/Manila': "मनीला, फ़िलीपींस",
    'Asia/Hong_Kong': "हांगकांग",
    'Asia/Shanghai': "बीजिंग / शांघाई, चीन",
    'Asia/Taipei': "ताइपे, ताइवान",
    'Asia/Seoul': "सियोल, दक्षिण कोरिया",
    'Asia/Tokyo': "टोक्यो, जापान",
    'Asia/Tashkent': "ताशकंद, उज़्बेकिस्तान",
    'Asia/Almaty': "अल्माटी, कज़ाख़स्तान",
    'Asia/Baku': "बाकू, अज़रबैजान",
    'Europe/London': "लंदन, UK",
    'Europe/Dublin': "डबलिन, आयरलैंड",
    'Europe/Lisbon': "लिस्बन, पुर्तगाल",
    'Europe/Madrid': "मैड्रिड, स्पेन",
    'Europe/Paris': "पेरिस, फ़्रांस",
    'Europe/Brussels': "ब्रुसेल्स, बेल्जियम",
    'Europe/Amsterdam': "एम्स्टर्डम, नीदरलैंड",
    'Europe/Berlin': "बर्लिन, जर्मनी",
    'Europe/Zurich': "ज़्यूरिख, स्विट्ज़रलैंड",
    'Europe/Rome': "रोम, इटली",
    'Europe/Vienna': "वियना, ऑस्ट्रिया",
    'Europe/Prague': "प्राग, चेकिया",
    'Europe/Warsaw': "वारसॉ, पोलैंड",
    'Europe/Stockholm': "स्टॉकहोम, स्वीडन",
    'Europe/Oslo': "ओस्लो, नॉर्वे",
    'Europe/Copenhagen': "कोपेनहेगन, डेनमार्क",
    'Europe/Helsinki': "हेलसिंकी, फ़िनलैंड",
    'Europe/Athens': "एथेंस, ग्रीस",
    'Europe/Istanbul': "इस्तांबुल, तुर्की",
    'Europe/Kyiv': "कीव, यूक्रेन",
    'Europe/Moscow': "मॉस्को, रूस",
    'Africa/Cairo': "काहिरा, मिस्र",
    'Africa/Nairobi': "नैरोबी, केन्या",
    'Africa/Johannesburg': "जोहान्सबर्ग, दक्षिण अफ़्रीका",
    'Africa/Lagos': "लागोस, नाइजीरिया",
    'Africa/Casablanca': "कासाब्लांका, मोरक्को",
    'Indian/Mauritius': "पोर्ट लुइस, मॉरीशस",
    'America/New_York': "न्यूयॉर्क, USA",
    'America/Toronto': "टोरंटो, कनाडा",
    'America/Chicago': "शिकागो, USA",
    'America/Denver': "डेनवर, USA",
    'America/Phoenix': "फ़ीनिक्स, USA",
    'America/Los_Angeles': "लॉस एंजेलिस / सैन फ़्रांसिस्को, USA",
    'America/Vancouver': "वैंकूवर, कनाडा",
    'America/Anchorage': "एंकरेज, USA",
    'Pacific/Honolulu': "होनोलुलु, हवाई",
    'America/Mexico_City': "मेक्सिको सिटी, मेक्सिको",
    'America/Bogota': "बोगोटा, कोलंबिया",
    'America/Lima': "लीमा, पेरू",
    'America/Santiago': "सैंटियागो, चिली",
    'America/Sao_Paulo': "साओ पाउलो, ब्राज़ील",
    'America/Argentina/Buenos_Aires': "ब्यूनस आयर्स, अर्जेंटीना",
    'America/Halifax': "हैलिफ़ैक्स, कनाडा",
    'Australia/Perth': "पर्थ, ऑस्ट्रेलिया",
    'Australia/Adelaide': "एडिलेड, ऑस्ट्रेलिया",
    'Australia/Brisbane': "ब्रिस्बेन, ऑस्ट्रेलिया",
    'Australia/Sydney': "सिडनी, ऑस्ट्रेलिया",
    'Australia/Melbourne': "मेलबर्न, ऑस्ट्रेलिया",
    'Pacific/Auckland': "ऑकलैंड, न्यूज़ीलैंड",
    'UTC': "UTC (विश्व मानक समय)"
  } },
  bn: { cities: {
    'Asia/Kolkata': "ভারত",
    'Asia/Dubai': "দুবাই, UAE",
    'Asia/Riyadh': "রিয়াদ, সৌদি আরব",
    'Asia/Qatar': "দোহা, কাতার",
    'Asia/Kuwait': "কুয়েত সিটি, কুয়েত",
    'Asia/Bahrain': "মানামা, বাহরাইন",
    'Asia/Muscat': "মাস্কাট, ওমান",
    'Asia/Tehran': "তেহরান, ইরান",
    'Asia/Jerusalem': "তেল আবিব, ইসরায়েল",
    'Asia/Karachi': "করাচি, পাকিস্তান",
    'Asia/Kabul': "কাবুল, আফগানিস্তান",
    'Asia/Kathmandu': "কাঠমান্ডু, নেপাল",
    'Asia/Dhaka': "ঢাকা, বাংলাদেশ",
    'Asia/Colombo': "কলম্বো, শ্রীলঙ্কা",
    'Asia/Thimphu': "থিম্পু, ভুটান",
    'Asia/Yangon': "ইয়াঙ্গুন, মিয়ানমার",
    'Asia/Bangkok': "ব্যাংকক, থাইল্যান্ড",
    'Asia/Jakarta': "জাকার্তা, ইন্দোনেশিয়া",
    'Asia/Kuala_Lumpur': "কুয়ালালামপুর, মালয়েশিয়া",
    'Asia/Singapore': "সিঙ্গাপুর",
    'Asia/Ho_Chi_Minh': "হো চি মিন সিটি, ভিয়েতনাম",
    'Asia/Manila': "ম্যানিলা, ফিলিপাইন",
    'Asia/Hong_Kong': "হংকং",
    'Asia/Shanghai': "বেইজিং / সাংহাই, চীন",
    'Asia/Taipei': "তাইপেই, তাইওয়ান",
    'Asia/Seoul': "সিউল, দক্ষিণ কোরিয়া",
    'Asia/Tokyo': "টোকিও, জাপান",
    'Asia/Tashkent': "তাশখন্দ, উজবেকিস্তান",
    'Asia/Almaty': "আলমাটি, কাজাখস্তান",
    'Asia/Baku': "বাকু, আজারবাইজান",
    'Europe/London': "লন্ডন, UK",
    'Europe/Dublin': "ডাবলিন, আয়ারল্যান্ড",
    'Europe/Lisbon': "লিসবন, পর্তুগাল",
    'Europe/Madrid': "মাদ্রিদ, স্পেন",
    'Europe/Paris': "প্যারিস, ফ্রান্স",
    'Europe/Brussels': "ব্রাসেলস, বেলজিয়াম",
    'Europe/Amsterdam': "আমস্টারডাম, নেদারল্যান্ডস",
    'Europe/Berlin': "বার্লিন, জার্মানি",
    'Europe/Zurich': "জুরিখ, সুইজারল্যান্ড",
    'Europe/Rome': "রোম, ইতালি",
    'Europe/Vienna': "ভিয়েনা, অস্ট্রিয়া",
    'Europe/Prague': "প্রাগ, চেকিয়া",
    'Europe/Warsaw': "ওয়ারশ, পোল্যান্ড",
    'Europe/Stockholm': "স্টকহোম, সুইডেন",
    'Europe/Oslo': "অসলো, নরওয়ে",
    'Europe/Copenhagen': "কোপেনহেগেন, ডেনমার্ক",
    'Europe/Helsinki': "হেলসিঙ্কি, ফিনল্যান্ড",
    'Europe/Athens': "এথেন্স, গ্রিস",
    'Europe/Istanbul': "ইস্তাম্বুল, তুরস্ক",
    'Europe/Kyiv': "কিয়েভ, ইউক্রেন",
    'Europe/Moscow': "মস্কো, রাশিয়া",
    'Africa/Cairo': "কায়রো, মিশর",
    'Africa/Nairobi': "নাইরোবি, কেনিয়া",
    'Africa/Johannesburg': "জোহানেসবার্গ, দক্ষিণ আফ্রিকা",
    'Africa/Lagos': "লাগোস, নাইজেরিয়া",
    'Africa/Casablanca': "কাসাব্লাঙ্কা, মরক্কো",
    'Indian/Mauritius': "পোর্ট লুইস, মরিশাস",
    'America/New_York': "নিউ ইয়র্ক, USA",
    'America/Toronto': "টরন্টো, কানাডা",
    'America/Chicago': "শিকাগো, USA",
    'America/Denver': "ডেনভার, USA",
    'America/Phoenix': "ফিনিক্স, USA",
    'America/Los_Angeles': "লস অ্যাঞ্জেলেস / সান ফ্রান্সিসকো, USA",
    'America/Vancouver': "ভ্যাঙ্কুভার, কানাডা",
    'America/Anchorage': "অ্যাঙ্কোরেজ, USA",
    'Pacific/Honolulu': "হনলুলু, হাওয়াই",
    'America/Mexico_City': "মেক্সিকো সিটি, মেক্সিকো",
    'America/Bogota': "বোগোতা, কলম্বিয়া",
    'America/Lima': "লিমা, পেরু",
    'America/Santiago': "সান্তিয়াগো, চিলি",
    'America/Sao_Paulo': "সাও পাওলো, ব্রাজিল",
    'America/Argentina/Buenos_Aires': "বুয়েনোস আইরেস, আর্জেন্টিনা",
    'America/Halifax': "হ্যালিফ্যাক্স, কানাডা",
    'Australia/Perth': "পার্থ, অস্ট্রেলিয়া",
    'Australia/Adelaide': "অ্যাডিলেড, অস্ট্রেলিয়া",
    'Australia/Brisbane': "ব্রিসবেন, অস্ট্রেলিয়া",
    'Australia/Sydney': "সিডনি, অস্ট্রেলিয়া",
    'Australia/Melbourne': "মেলবোর্ন, অস্ট্রেলিয়া",
    'Pacific/Auckland': "অকল্যান্ড, নিউজিল্যান্ড",
    'UTC': "UTC (বিশ্ব মান সময়)"
  } },
  mr: { cities: {
    'Asia/Kolkata': "भारत",
    'Asia/Dubai': "दुबई, UAE",
    'Asia/Riyadh': "रियाध, सौदी अरेबिया",
    'Asia/Qatar': "दोहा, कतार",
    'Asia/Kuwait': "कुवेत सिटी, कुवेत",
    'Asia/Bahrain': "मनामा, बहरीन",
    'Asia/Muscat': "मस्कत, ओमान",
    'Asia/Tehran': "तेहरान, इराण",
    'Asia/Jerusalem': "तेल अवीव, इस्रायल",
    'Asia/Karachi': "कराची, पाकिस्तान",
    'Asia/Kabul': "काबूल, अफगाणिस्तान",
    'Asia/Kathmandu': "काठमांडू, नेपाळ",
    'Asia/Dhaka': "ढाका, बांगलादेश",
    'Asia/Colombo': "कोलंबो, श्रीलंका",
    'Asia/Thimphu': "थिंपू, भूतान",
    'Asia/Yangon': "यांगून, म्यानमार",
    'Asia/Bangkok': "बँकॉक, थायलंड",
    'Asia/Jakarta': "जकार्ता, इंडोनेशिया",
    'Asia/Kuala_Lumpur': "क्वालालंपूर, मलेशिया",
    'Asia/Singapore': "सिंगापूर",
    'Asia/Ho_Chi_Minh': "हो ची मिन्ह सिटी, व्हिएतनाम",
    'Asia/Manila': "मनिला, फिलिपिन्स",
    'Asia/Hong_Kong': "हाँगकाँग",
    'Asia/Shanghai': "बीजिंग / शांघाय, चीन",
    'Asia/Taipei': "तैपेई, तैवान",
    'Asia/Seoul': "सोल, दक्षिण कोरिया",
    'Asia/Tokyo': "टोकियो, जपान",
    'Asia/Tashkent': "ताश्कंद, उझबेकिस्तान",
    'Asia/Almaty': "अल्माटी, कझाकस्तान",
    'Asia/Baku': "बाकू, अझरबैजान",
    'Europe/London': "लंडन, UK",
    'Europe/Dublin': "डब्लिन, आयर्लंड",
    'Europe/Lisbon': "लिस्बन, पोर्तुगाल",
    'Europe/Madrid': "माद्रिद, स्पेन",
    'Europe/Paris': "पॅरिस, फ्रान्स",
    'Europe/Brussels': "ब्रुसेल्स, बेल्जियम",
    'Europe/Amsterdam': "ॲमस्टरडॅम, नेदरलँड्स",
    'Europe/Berlin': "बर्लिन, जर्मनी",
    'Europe/Zurich': "झुरिक, स्विट्झर्लंड",
    'Europe/Rome': "रोम, इटली",
    'Europe/Vienna': "व्हिएन्ना, ऑस्ट्रिया",
    'Europe/Prague': "प्राग, चेकिया",
    'Europe/Warsaw': "वॉर्सा, पोलंड",
    'Europe/Stockholm': "स्टॉकहोम, स्वीडन",
    'Europe/Oslo': "ओस्लो, नॉर्वे",
    'Europe/Copenhagen': "कोपनहेगन, डेन्मार्क",
    'Europe/Helsinki': "हेलसिंकी, फिनलंड",
    'Europe/Athens': "अथेन्स, ग्रीस",
    'Europe/Istanbul': "इस्तंबूल, तुर्की",
    'Europe/Kyiv': "कीव, युक्रेन",
    'Europe/Moscow': "मॉस्को, रशिया",
    'Africa/Cairo': "कैरो, इजिप्त",
    'Africa/Nairobi': "नैरोबी, केनिया",
    'Africa/Johannesburg': "जोहान्सबर्ग, दक्षिण आफ्रिका",
    'Africa/Lagos': "लागोस, नायजेरिया",
    'Africa/Casablanca': "कासाब्लांका, मोरोक्को",
    'Indian/Mauritius': "पोर्ट लुई, मॉरिशस",
    'America/New_York': "न्यूयॉर्क, USA",
    'America/Toronto': "टोरंटो, कॅनडा",
    'America/Chicago': "शिकागो, USA",
    'America/Denver': "डेन्व्हर, USA",
    'America/Phoenix': "फिनिक्स, USA",
    'America/Los_Angeles': "लॉस एंजेलिस / सॅन फ्रान्सिस्को, USA",
    'America/Vancouver': "व्हँकुव्हर, कॅनडा",
    'America/Anchorage': "अँकरेज, USA",
    'Pacific/Honolulu': "होनोलुलु, हवाई",
    'America/Mexico_City': "मेक्सिको सिटी, मेक्सिको",
    'America/Bogota': "बोगोटा, कोलंबिया",
    'America/Lima': "लिमा, पेरू",
    'America/Santiago': "सँटियागो, चिली",
    'America/Sao_Paulo': "साओ पाउलो, ब्राझील",
    'America/Argentina/Buenos_Aires': "ब्युनोस आयर्स, अर्जेंटिना",
    'America/Halifax': "हॅलिफॅक्स, कॅनडा",
    'Australia/Perth': "पर्थ, ऑस्ट्रेलिया",
    'Australia/Adelaide': "ॲडलेड, ऑस्ट्रेलिया",
    'Australia/Brisbane': "ब्रिस्बेन, ऑस्ट्रेलिया",
    'Australia/Sydney': "सिडनी, ऑस्ट्रेलिया",
    'Australia/Melbourne': "मेलबर्न, ऑस्ट्रेलिया",
    'Pacific/Auckland': "ऑकलंड, न्यूझीलंड",
    'UTC': "UTC (जागतिक प्रमाण वेळ)"
  } },
  gu: { cities: {
    'Asia/Kolkata': "ભારત",
    'Asia/Dubai': "દુબઈ, UAE",
    'Asia/Riyadh': "રિયાધ, સાઉદી અરેબિયા",
    'Asia/Qatar': "દોહા, કતાર",
    'Asia/Kuwait': "કુવૈત સિટી, કુવૈત",
    'Asia/Bahrain': "મનામા, બહેરીન",
    'Asia/Muscat': "મસ્કત, ઓમાન",
    'Asia/Tehran': "તેહરાન, ઈરાન",
    'Asia/Jerusalem': "તેલ અવીવ, ઇઝરાયેલ",
    'Asia/Karachi': "કરાચી, પાકિસ્તાન",
    'Asia/Kabul': "કાબુલ, અફઘાનિસ્તાન",
    'Asia/Kathmandu': "કાઠમંડુ, નેપાળ",
    'Asia/Dhaka': "ઢાકા, બાંગ્લાદેશ",
    'Asia/Colombo': "કોલંબો, શ્રીલંકા",
    'Asia/Thimphu': "થિમ્પુ, ભૂટાન",
    'Asia/Yangon': "યાંગોન, મ્યાનમાર",
    'Asia/Bangkok': "બેંગકોક, થાઈલેન્ડ",
    'Asia/Jakarta': "જકાર્તા, ઇન્ડોનેશિયા",
    'Asia/Kuala_Lumpur': "કુઆલાલમ્પુર, મલેશિયા",
    'Asia/Singapore': "સિંગાપોર",
    'Asia/Ho_Chi_Minh': "હો ચી મિન્હ સિટી, વિયેતનામ",
    'Asia/Manila': "મનીલા, ફિલિપાઇન્સ",
    'Asia/Hong_Kong': "હોંગકોંગ",
    'Asia/Shanghai': "બેઇજિંગ / શાંઘાઈ, ચીન",
    'Asia/Taipei': "તાઇપેઇ, તાઇવાન",
    'Asia/Seoul': "સિઓલ, દક્ષિણ કોરિયા",
    'Asia/Tokyo': "ટોક્યો, જાપાન",
    'Asia/Tashkent': "તાશ્કંદ, ઉઝબેકિસ્તાન",
    'Asia/Almaty': "અલ્માટી, કઝાકિસ્તાન",
    'Asia/Baku': "બાકુ, અઝરબૈજાન",
    'Europe/London': "લંડન, UK",
    'Europe/Dublin': "ડબલિન, આયર્લેન્ડ",
    'Europe/Lisbon': "લિસ્બન, પોર્ટુગલ",
    'Europe/Madrid': "મેડ્રિડ, સ્પેન",
    'Europe/Paris': "પેરિસ, ફ્રાન્સ",
    'Europe/Brussels': "બ્રસેલ્સ, બેલ્જિયમ",
    'Europe/Amsterdam': "એમ્સ્ટરડેમ, નેધરલેન્ડ્સ",
    'Europe/Berlin': "બર્લિન, જર્મની",
    'Europe/Zurich': "ઝ્યુરિક, સ્વિટ્ઝર્લેન્ડ",
    'Europe/Rome': "રોમ, ઇટાલી",
    'Europe/Vienna': "વિયેના, ઑસ્ટ્રિયા",
    'Europe/Prague': "પ્રાગ, ચેકિયા",
    'Europe/Warsaw': "વૉર્સો, પોલેન્ડ",
    'Europe/Stockholm': "સ્ટોકહોમ, સ્વીડન",
    'Europe/Oslo': "ઓસ્લો, નોર્વે",
    'Europe/Copenhagen': "કોપનહેગન, ડેનમાર્ક",
    'Europe/Helsinki': "હેલસિંકી, ફિનલેન્ડ",
    'Europe/Athens': "એથેન્સ, ગ્રીસ",
    'Europe/Istanbul': "ઇસ્તંબુલ, તુર્કી",
    'Europe/Kyiv': "કીવ, યુક્રેન",
    'Europe/Moscow': "મોસ્કો, રશિયા",
    'Africa/Cairo': "કૈરો, ઇજિપ્ત",
    'Africa/Nairobi': "નૈરોબી, કેન્યા",
    'Africa/Johannesburg': "જોહાનિસબર્ગ, દક્ષિણ આફ્રિકા",
    'Africa/Lagos': "લાગોસ, નાઇજીરિયા",
    'Africa/Casablanca': "કાસાબ્લાન્કા, મોરોક્કો",
    'Indian/Mauritius': "પોર્ટ લુઈ, મોરેશિયસ",
    'America/New_York': "ન્યૂયોર્ક, USA",
    'America/Toronto': "ટોરોન્ટો, કેનેડા",
    'America/Chicago': "શિકાગો, USA",
    'America/Denver': "ડેન્વર, USA",
    'America/Phoenix': "ફિનિક્સ, USA",
    'America/Los_Angeles': "લોસ એન્જલસ / સાન ફ્રાન્સિસ્કો, USA",
    'America/Vancouver': "વાનકુવર, કેનેડા",
    'America/Anchorage': "એન્કરેજ, USA",
    'Pacific/Honolulu': "હોનોલુલુ, હવાઈ",
    'America/Mexico_City': "મેક્સિકો સિટી, મેક્સિકો",
    'America/Bogota': "બોગોટા, કોલંબિયા",
    'America/Lima': "લીમા, પેરુ",
    'America/Santiago': "સેન્ટિયાગો, ચિલી",
    'America/Sao_Paulo': "સાઓ પાઉલો, બ્રાઝિલ",
    'America/Argentina/Buenos_Aires': "બ્યુનોસ એરેસ, આર્જેન્ટિના",
    'America/Halifax': "હેલિફેક્સ, કેનેડા",
    'Australia/Perth': "પર્થ, ઑસ્ટ્રેલિયા",
    'Australia/Adelaide': "એડિલેડ, ઑસ્ટ્રેલિયા",
    'Australia/Brisbane': "બ્રિસ્બેન, ઑસ્ટ્રેલિયા",
    'Australia/Sydney': "સિડની, ઑસ્ટ્રેલિયા",
    'Australia/Melbourne': "મેલબોર્ન, ઑસ્ટ્રેલિયા",
    'Pacific/Auckland': "ઓકલેન્ડ, ન્યૂઝીલેન્ડ",
    'UTC': "UTC (વિશ્વ માનક સમય)"
  } },
  pa: { cities: {
    'Asia/Kolkata': "ਭਾਰਤ",
    'Asia/Dubai': "ਦੁਬਈ, UAE",
    'Asia/Riyadh': "ਰਿਆਧ, ਸਾਊਦੀ ਅਰਬ",
    'Asia/Qatar': "ਦੋਹਾ, ਕਤਰ",
    'Asia/Kuwait': "ਕੁਵੈਤ ਸਿਟੀ, ਕੁਵੈਤ",
    'Asia/Bahrain': "ਮਨਾਮਾ, ਬਹਿਰੀਨ",
    'Asia/Muscat': "ਮਸਕਟ, ਓਮਾਨ",
    'Asia/Tehran': "ਤਹਿਰਾਨ, ਈਰਾਨ",
    'Asia/Jerusalem': "ਤੇਲ ਅਵੀਵ, ਇਜ਼ਰਾਈਲ",
    'Asia/Karachi': "ਕਰਾਚੀ, ਪਾਕਿਸਤਾਨ",
    'Asia/Kabul': "ਕਾਬੁਲ, ਅਫ਼ਗ਼ਾਨਿਸਤਾਨ",
    'Asia/Kathmandu': "ਕਾਠਮੰਡੂ, ਨੇਪਾਲ",
    'Asia/Dhaka': "ਢਾਕਾ, ਬੰਗਲਾਦੇਸ਼",
    'Asia/Colombo': "ਕੋਲੰਬੋ, ਸ੍ਰੀਲੰਕਾ",
    'Asia/Thimphu': "ਥਿੰਫੂ, ਭੂਟਾਨ",
    'Asia/Yangon': "ਯਾਂਗੂਨ, ਮਿਆਂਮਾਰ",
    'Asia/Bangkok': "ਬੈਂਕਾਕ, ਥਾਈਲੈਂਡ",
    'Asia/Jakarta': "ਜਕਾਰਤਾ, ਇੰਡੋਨੇਸ਼ੀਆ",
    'Asia/Kuala_Lumpur': "ਕੁਆਲਾਲੰਪੁਰ, ਮਲੇਸ਼ੀਆ",
    'Asia/Singapore': "ਸਿੰਗਾਪੁਰ",
    'Asia/Ho_Chi_Minh': "ਹੋ ਚੀ ਮਿਨ੍ਹ ਸਿਟੀ, ਵੀਅਤਨਾਮ",
    'Asia/Manila': "ਮਨੀਲਾ, ਫ਼ਿਲੀਪੀਨਜ਼",
    'Asia/Hong_Kong': "ਹਾਂਗਕਾਂਗ",
    'Asia/Shanghai': "ਬੀਜਿੰਗ / ਸ਼ੰਘਾਈ, ਚੀਨ",
    'Asia/Taipei': "ਤਾਈਪੇ, ਤਾਈਵਾਨ",
    'Asia/Seoul': "ਸਿਓਲ, ਦੱਖਣੀ ਕੋਰੀਆ",
    'Asia/Tokyo': "ਟੋਕੀਓ, ਜਾਪਾਨ",
    'Asia/Tashkent': "ਤਾਸ਼ਕੰਦ, ਉਜ਼ਬੇਕਿਸਤਾਨ",
    'Asia/Almaty': "ਅਲਮਾਟੀ, ਕਜ਼ਾਖ਼ਸਤਾਨ",
    'Asia/Baku': "ਬਾਕੂ, ਅਜ਼ਰਬਾਈਜਾਨ",
    'Europe/London': "ਲੰਡਨ, UK",
    'Europe/Dublin': "ਡਬਲਿਨ, ਆਇਰਲੈਂਡ",
    'Europe/Lisbon': "ਲਿਸਬਨ, ਪੁਰਤਗਾਲ",
    'Europe/Madrid': "ਮੈਡ੍ਰਿਡ, ਸਪੇਨ",
    'Europe/Paris': "ਪੈਰਿਸ, ਫ਼ਰਾਂਸ",
    'Europe/Brussels': "ਬ੍ਰਸਲਜ਼, ਬੈਲਜੀਅਮ",
    'Europe/Amsterdam': "ਐਮਸਟਰਡਮ, ਨੀਦਰਲੈਂਡ",
    'Europe/Berlin': "ਬਰਲਿਨ, ਜਰਮਨੀ",
    'Europe/Zurich': "ਜ਼ਿਊਰਿਖ, ਸਵਿਟਜ਼ਰਲੈਂਡ",
    'Europe/Rome': "ਰੋਮ, ਇਟਲੀ",
    'Europe/Vienna': "ਵਿਆਨਾ, ਆਸਟਰੀਆ",
    'Europe/Prague': "ਪ੍ਰਾਗ, ਚੈਕੀਆ",
    'Europe/Warsaw': "ਵਾਰਸਾ, ਪੋਲੈਂਡ",
    'Europe/Stockholm': "ਸਟਾਕਹੋਮ, ਸਵੀਡਨ",
    'Europe/Oslo': "ਓਸਲੋ, ਨਾਰਵੇ",
    'Europe/Copenhagen': "ਕੋਪਨਹੇਗਨ, ਡੈਨਮਾਰਕ",
    'Europe/Helsinki': "ਹੇਲਸਿੰਕੀ, ਫ਼ਿਨਲੈਂਡ",
    'Europe/Athens': "ਏਥਨਜ਼, ਗ੍ਰੀਸ",
    'Europe/Istanbul': "ਇਸਤਾਂਬੁਲ, ਤੁਰਕੀ",
    'Europe/Kyiv': "ਕੀਵ, ਯੂਕਰੇਨ",
    'Europe/Moscow': "ਮਾਸਕੋ, ਰੂਸ",
    'Africa/Cairo': "ਕਾਹਿਰਾ, ਮਿਸਰ",
    'Africa/Nairobi': "ਨੈਰੋਬੀ, ਕੀਨੀਆ",
    'Africa/Johannesburg': "ਜੋਹਾਨਸਬਰਗ, ਦੱਖਣੀ ਅਫ਼ਰੀਕਾ",
    'Africa/Lagos': "ਲਾਗੋਸ, ਨਾਈਜੀਰੀਆ",
    'Africa/Casablanca': "ਕਾਸਾਬਲਾਂਕਾ, ਮੋਰੱਕੋ",
    'Indian/Mauritius': "ਪੋਰਟ ਲੂਈ, ਮਾਰੀਸ਼ਸ",
    'America/New_York': "ਨਿਊਯਾਰਕ, USA",
    'America/Toronto': "ਟੋਰਾਂਟੋ, ਕੈਨੇਡਾ",
    'America/Chicago': "ਸ਼ਿਕਾਗੋ, USA",
    'America/Denver': "ਡੈਨਵਰ, USA",
    'America/Phoenix': "ਫ਼ੀਨਿਕਸ, USA",
    'America/Los_Angeles': "ਲਾਸ ਏਂਜਲਸ / ਸੈਨ ਫ਼ਰਾਂਸਿਸਕੋ, USA",
    'America/Vancouver': "ਵੈਨਕੂਵਰ, ਕੈਨੇਡਾ",
    'America/Anchorage': "ਐਂਕਰੇਜ, USA",
    'Pacific/Honolulu': "ਹੋਨੋਲੂਲੂ, ਹਵਾਈ",
    'America/Mexico_City': "ਮੈਕਸੀਕੋ ਸਿਟੀ, ਮੈਕਸੀਕੋ",
    'America/Bogota': "ਬੋਗੋਟਾ, ਕੋਲੰਬੀਆ",
    'America/Lima': "ਲੀਮਾ, ਪੇਰੂ",
    'America/Santiago': "ਸੈਂਟੀਆਗੋ, ਚਿਲੀ",
    'America/Sao_Paulo': "ਸਾਓ ਪਾਓਲੋ, ਬ੍ਰਾਜ਼ੀਲ",
    'America/Argentina/Buenos_Aires': "ਬਿਊਨਸ ਆਇਰਸ, ਅਰਜਨਟੀਨਾ",
    'America/Halifax': "ਹੈਲੀਫ਼ੈਕਸ, ਕੈਨੇਡਾ",
    'Australia/Perth': "ਪਰਥ, ਆਸਟ੍ਰੇਲੀਆ",
    'Australia/Adelaide': "ਐਡੀਲੇਡ, ਆਸਟ੍ਰੇਲੀਆ",
    'Australia/Brisbane': "ਬ੍ਰਿਸਬੇਨ, ਆਸਟ੍ਰੇਲੀਆ",
    'Australia/Sydney': "ਸਿਡਨੀ, ਆਸਟ੍ਰੇਲੀਆ",
    'Australia/Melbourne': "ਮੈਲਬਰਨ, ਆਸਟ੍ਰੇਲੀਆ",
    'Pacific/Auckland': "ਆਕਲੈਂਡ, ਨਿਊਜ਼ੀਲੈਂਡ",
    'UTC': "UTC (ਵਿਸ਼ਵ ਮਿਆਰੀ ਸਮਾਂ)"
  } },
  or: { cities: {
    'Asia/Kolkata': "ଭାରତ",
    'Asia/Dubai': "ଦୁବାଇ, UAE",
    'Asia/Riyadh': "ରିୟାଦ, ସାଉଦି ଆରବ",
    'Asia/Qatar': "ଦୋହା, କତାର",
    'Asia/Kuwait': "କୁଏତ ସିଟି, କୁଏତ",
    'Asia/Bahrain': "ମାନାମା, ବାହାରିନ",
    'Asia/Muscat': "ମସ୍କାଟ, ଓମାନ",
    'Asia/Tehran': "ତେହେରାନ, ଇରାନ",
    'Asia/Jerusalem': "ତେଲ ଆଭିଭ, ଇସ୍ରାଏଲ",
    'Asia/Karachi': "କରାଚି, ପାକିସ୍ତାନ",
    'Asia/Kabul': "କାବୁଲ, ଆଫଗାନିସ୍ତାନ",
    'Asia/Kathmandu': "କାଠମାଣ୍ଡୁ, ନେପାଳ",
    'Asia/Dhaka': "ଢାକା, ବାଂଲାଦେଶ",
    'Asia/Colombo': "କଲମ୍ବୋ, ଶ୍ରୀଲଙ୍କା",
    'Asia/Thimphu': "ଥିମ୍ପୁ, ଭୁଟାନ",
    'Asia/Yangon': "ୟାଙ୍ଗୁନ, ମିଆଁମାର",
    'Asia/Bangkok': "ବ୍ୟାଙ୍କକ, ଥାଇଲ୍ୟାଣ୍ଡ",
    'Asia/Jakarta': "ଜାକାର୍ତ୍ତା, ଇଣ୍ଡୋନେସିଆ",
    'Asia/Kuala_Lumpur': "କୁଆଲାଲମ୍ପୁର, ମାଲେସିଆ",
    'Asia/Singapore': "ସିଙ୍ଗାପୁର",
    'Asia/Ho_Chi_Minh': "ହୋ ଚି ମିନ ସିଟି, ଭିଏତନାମ",
    'Asia/Manila': "ମନିଲା, ଫିଲିପାଇନ୍ସ",
    'Asia/Hong_Kong': "ହଂକଂ",
    'Asia/Shanghai': "ବେଜିଂ / ସାଂଘାଇ, ଚୀନ",
    'Asia/Taipei': "ତାଇପେଇ, ତାଇୱାନ",
    'Asia/Seoul': "ସିଓଲ, ଦକ୍ଷିଣ କୋରିଆ",
    'Asia/Tokyo': "ଟୋକିଓ, ଜାପାନ",
    'Asia/Tashkent': "ତାସକେଣ୍ଟ, ଉଜବେକିସ୍ତାନ",
    'Asia/Almaty': "ଆଲମାଟି, କାଜାଖସ୍ତାନ",
    'Asia/Baku': "ବାକୁ, ଆଜେରବାଇଜାନ",
    'Europe/London': "ଲଣ୍ଡନ, UK",
    'Europe/Dublin': "ଡବଲିନ, ଆୟାରଲ୍ୟାଣ୍ଡ",
    'Europe/Lisbon': "ଲିସବନ, ପର୍ତ୍ତୁଗାଲ",
    'Europe/Madrid': "ମାଡ୍ରିଡ, ସ୍ପେନ",
    'Europe/Paris': "ପ୍ୟାରିସ, ଫ୍ରାନ୍ସ",
    'Europe/Brussels': "ବ୍ରସେଲ୍ସ, ବେଲଜିୟମ",
    'Europe/Amsterdam': "ଆମଷ୍ଟରଡାମ, ନେଦରଲ୍ୟାଣ୍ଡସ",
    'Europe/Berlin': "ବର୍ଲିନ, ଜର୍ମାନୀ",
    'Europe/Zurich': "ଜୁରିକ, ସ୍ୱିଜରଲ୍ୟାଣ୍ଡ",
    'Europe/Rome': "ରୋମ, ଇଟାଲୀ",
    'Europe/Vienna': "ଭିଏନା, ଅଷ୍ଟ୍ରିଆ",
    'Europe/Prague': "ପ୍ରାଗ, ଚେକିଆ",
    'Europe/Warsaw': "ୱାରସ, ପୋଲାଣ୍ଡ",
    'Europe/Stockholm': "ଷ୍ଟକହୋମ, ସ୍ୱିଡେନ",
    'Europe/Oslo': "ଓସଲୋ, ନରୱେ",
    'Europe/Copenhagen': "କୋପେନହେଗେନ, ଡେନମାର୍କ",
    'Europe/Helsinki': "ହେଲସିଙ୍କି, ଫିନଲ୍ୟାଣ୍ଡ",
    'Europe/Athens': "ଏଥେନ୍ସ, ଗ୍ରୀସ",
    'Europe/Istanbul': "ଇସ୍ତାନବୁଲ, ତୁର୍କୀ",
    'Europe/Kyiv': "କିଭ, ୟୁକ୍ରେନ",
    'Europe/Moscow': "ମସ୍କୋ, ରୁଷିଆ",
    'Africa/Cairo': "କାଇରୋ, ଇଜିପ୍ଟ",
    'Africa/Nairobi': "ନାଇରୋବି, କେନିଆ",
    'Africa/Johannesburg': "ଜୋହାନ୍ସବର୍ଗ, ଦକ୍ଷିଣ ଆଫ୍ରିକା",
    'Africa/Lagos': "ଲାଗୋସ, ନାଇଜେରିଆ",
    'Africa/Casablanca': "କାସାବ୍ଲାଙ୍କା, ମୋରକ୍କୋ",
    'Indian/Mauritius': "ପୋର୍ଟ ଲୁଇ, ମରିସସ",
    'America/New_York': "ନ୍ୟୁୟର୍କ, USA",
    'America/Toronto': "ଟୋରଣ୍ଟୋ, କାନାଡା",
    'America/Chicago': "ଚିକାଗୋ, USA",
    'America/Denver': "ଡେନଭର, USA",
    'America/Phoenix': "ଫିନିକ୍ସ, USA",
    'America/Los_Angeles': "ଲସ ଏଞ୍ଜେଲସ / ସାନ ଫ୍ରାନ୍ସିସ୍କୋ, USA",
    'America/Vancouver': "ଭାନକୁଭର, କାନାଡା",
    'America/Anchorage': "ଆଙ୍କରେଜ, USA",
    'Pacific/Honolulu': "ହୋନୋଲୁଲୁ, ହାୱାଇ",
    'America/Mexico_City': "ମେକ୍ସିକୋ ସିଟି, ମେକ୍ସିକୋ",
    'America/Bogota': "ବୋଗୋଟା, କଲମ୍ବିଆ",
    'America/Lima': "ଲିମା, ପେରୁ",
    'America/Santiago': "ସାଣ୍ଟିଆଗୋ, ଚିଲି",
    'America/Sao_Paulo': "ସାଓ ପାଓଲୋ, ବ୍ରାଜିଲ",
    'America/Argentina/Buenos_Aires': "ବୁଏନସ ଆଇରେସ, ଆର୍ଜେଣ୍ଟିନା",
    'America/Halifax': "ହାଲିଫ୍ୟାକ୍ସ, କାନାଡା",
    'Australia/Perth': "ପର୍ଥ, ଅଷ୍ଟ୍ରେଲିଆ",
    'Australia/Adelaide': "ଆଡିଲେଡ, ଅଷ୍ଟ୍ରେଲିଆ",
    'Australia/Brisbane': "ବ୍ରିସବେନ, ଅଷ୍ଟ୍ରେଲିଆ",
    'Australia/Sydney': "ସିଡନୀ, ଅଷ୍ଟ୍ରେଲିଆ",
    'Australia/Melbourne': "ମେଲବୋର୍ଣ୍ଣ, ଅଷ୍ଟ୍ରେଲିଆ",
    'Pacific/Auckland': "ଅକଲ୍ୟାଣ୍ଡ, ନ୍ୟୁଜିଲ୍ୟାଣ୍ଡ",
    'UTC': "UTC (ବିଶ୍ୱ ମାନକ ସମୟ)"
  } },
  ta: { cities: {
    'Asia/Kolkata': "இந்தியா",
    'Asia/Dubai': "துபாய், UAE",
    'Asia/Riyadh': "ரியாத், சவுதி அரேபியா",
    'Asia/Qatar': "தோஹா, கத்தார்",
    'Asia/Kuwait': "குவைத் சிட்டி, குவைத்",
    'Asia/Bahrain': "மனாமா, பஹ்ரைன்",
    'Asia/Muscat': "மஸ்கட், ஓமன்",
    'Asia/Tehran': "தெஹ்ரான், ஈரான்",
    'Asia/Jerusalem': "டெல் அவீவ், இஸ்ரேல்",
    'Asia/Karachi': "கராச்சி, பாகிஸ்தான்",
    'Asia/Kabul': "காபூல், ஆப்கானிஸ்தான்",
    'Asia/Kathmandu': "காத்மாண்டு, நேபாளம்",
    'Asia/Dhaka': "டாக்கா, வங்காளதேசம்",
    'Asia/Colombo': "கொழும்பு, இலங்கை",
    'Asia/Thimphu': "திம்பு, பூட்டான்",
    'Asia/Yangon': "யாங்கூன், மியான்மர்",
    'Asia/Bangkok': "பாங்காக், தாய்லாந்து",
    'Asia/Jakarta': "ஜகார்த்தா, இந்தோனேசியா",
    'Asia/Kuala_Lumpur': "கோலாலம்பூர், மலேசியா",
    'Asia/Singapore': "சிங்கப்பூர்",
    'Asia/Ho_Chi_Minh': "ஹோ சி மின் சிட்டி, வியட்நாம்",
    'Asia/Manila': "மணிலா, பிலிப்பைன்ஸ்",
    'Asia/Hong_Kong': "ஹாங்காங்",
    'Asia/Shanghai': "பெய்ஜிங் / ஷாங்காய், சீனா",
    'Asia/Taipei': "தைபே, தைவான்",
    'Asia/Seoul': "சியோல், தென் கொரியா",
    'Asia/Tokyo': "டோக்கியோ, ஜப்பான்",
    'Asia/Tashkent': "தாஷ்கண்ட், உஸ்பெகிஸ்தான்",
    'Asia/Almaty': "அல்மாட்டி, கஜகஸ்தான்",
    'Asia/Baku': "பாகு, அசர்பைஜான்",
    'Europe/London': "லண்டன், UK",
    'Europe/Dublin': "டப்ளின், அயர்லாந்து",
    'Europe/Lisbon': "லிஸ்பன், போர்ச்சுகல்",
    'Europe/Madrid': "மாட்ரிட், ஸ்பெயின்",
    'Europe/Paris': "பாரிஸ், பிரான்ஸ்",
    'Europe/Brussels': "பிரஸ்ஸல்ஸ், பெல்ஜியம்",
    'Europe/Amsterdam': "ஆம்ஸ்டர்டாம், நெதர்லாந்து",
    'Europe/Berlin': "பெர்லின், ஜெர்மனி",
    'Europe/Zurich': "சூரிக், சுவிட்சர்லாந்து",
    'Europe/Rome': "ரோம், இத்தாலி",
    'Europe/Vienna': "வியன்னா, ஆஸ்திரியா",
    'Europe/Prague': "பிராக், செக்கியா",
    'Europe/Warsaw': "வார்சா, போலந்து",
    'Europe/Stockholm': "ஸ்டாக்ஹோம், ஸ்வீடன்",
    'Europe/Oslo': "ஒஸ்லோ, நார்வே",
    'Europe/Copenhagen': "கோபன்ஹேகன், டென்மார்க்",
    'Europe/Helsinki': "ஹெல்சின்கி, பின்லாந்து",
    'Europe/Athens': "ஏதென்ஸ், கிரீஸ்",
    'Europe/Istanbul': "இஸ்தான்புல், துருக்கி",
    'Europe/Kyiv': "கீவ், உக்ரைன்",
    'Europe/Moscow': "மாஸ்கோ, ரஷ்யா",
    'Africa/Cairo': "கெய்ரோ, எகிப்து",
    'Africa/Nairobi': "நைரோபி, கென்யா",
    'Africa/Johannesburg': "ஜோகன்னஸ்பர்க், தென்னாப்பிரிக்கா",
    'Africa/Lagos': "லாகோஸ், நைஜீரியா",
    'Africa/Casablanca': "காசாபிளாங்கா, மொராக்கோ",
    'Indian/Mauritius': "போர்ட் லூயிஸ், மொரீஷியஸ்",
    'America/New_York': "நியூயார்க், USA",
    'America/Toronto': "டொராண்டோ, கனடா",
    'America/Chicago': "சிகாகோ, USA",
    'America/Denver': "டென்வர், USA",
    'America/Phoenix': "பீனிக்ஸ், USA",
    'America/Los_Angeles': "லாஸ் ஏஞ்சல்ஸ் / சான் பிரான்சிஸ்கோ, USA",
    'America/Vancouver': "வான்கூவர், கனடா",
    'America/Anchorage': "ஆங்கரேஜ், USA",
    'Pacific/Honolulu': "ஹொனலுலு, ஹவாய்",
    'America/Mexico_City': "மெக்சிகோ சிட்டி, மெக்சிகோ",
    'America/Bogota': "பொகோட்டா, கொலம்பியா",
    'America/Lima': "லிமா, பெரு",
    'America/Santiago': "சாண்டியாகோ, சிலி",
    'America/Sao_Paulo': "சாவோ பாலோ, பிரேசில்",
    'America/Argentina/Buenos_Aires': "புவெனஸ் அயர்ஸ், அர்ஜென்டினா",
    'America/Halifax': "ஹாலிஃபாக்ஸ், கனடா",
    'Australia/Perth': "பெர்த், ஆஸ்திரேலியா",
    'Australia/Adelaide': "அடிலெய்ட், ஆஸ்திரேலியா",
    'Australia/Brisbane': "பிரிஸ்பேன், ஆஸ்திரேலியா",
    'Australia/Sydney': "சிட்னி, ஆஸ்திரேலியா",
    'Australia/Melbourne': "மெல்போர்ன், ஆஸ்திரேலியா",
    'Pacific/Auckland': "ஆக்லாந்து, நியூசிலாந்து",
    'UTC': "UTC (உலக நிலையான நேரம்)"
  } },
  te: { cities: {
    'Asia/Kolkata': "భారతదేశం",
    'Asia/Dubai': "దుబాయ్, UAE",
    'Asia/Riyadh': "రియాద్, సౌదీ అరేబియా",
    'Asia/Qatar': "దోహా, ఖతార్",
    'Asia/Kuwait': "కువైట్ సిటీ, కువైట్",
    'Asia/Bahrain': "మనామా, బహ్రెయిన్",
    'Asia/Muscat': "మస్కట్, ఒమన్",
    'Asia/Tehran': "టెహ్రాన్, ఇరాన్",
    'Asia/Jerusalem': "టెల్ అవీవ్, ఇజ్రాయెల్",
    'Asia/Karachi': "కరాచీ, పాకిస్తాన్",
    'Asia/Kabul': "కాబూల్, ఆఫ్ఘనిస్తాన్",
    'Asia/Kathmandu': "ఖాట్మండు, నేపాల్",
    'Asia/Dhaka': "ఢాకా, బంగ్లాదేశ్",
    'Asia/Colombo': "కొలంబో, శ్రీలంక",
    'Asia/Thimphu': "థింపూ, భూటాన్",
    'Asia/Yangon': "యాంగాన్, మయన్మార్",
    'Asia/Bangkok': "బ్యాంకాక్, థాయిలాండ్",
    'Asia/Jakarta': "జకార్తా, ఇండోనేషియా",
    'Asia/Kuala_Lumpur': "కౌలాలంపూర్, మలేషియా",
    'Asia/Singapore': "సింగపూర్",
    'Asia/Ho_Chi_Minh': "హో చి మిన్ సిటీ, వియత్నాం",
    'Asia/Manila': "మనీలా, ఫిలిప్పీన్స్",
    'Asia/Hong_Kong': "హాంకాంగ్",
    'Asia/Shanghai': "బీజింగ్ / షాంఘై, చైనా",
    'Asia/Taipei': "తైపీ, తైవాన్",
    'Asia/Seoul': "సియోల్, దక్షిణ కొరియా",
    'Asia/Tokyo': "టోక్యో, జపాన్",
    'Asia/Tashkent': "తాష్కెంట్, ఉజ్బెకిస్తాన్",
    'Asia/Almaty': "అల్మాటీ, కజకిస్తాన్",
    'Asia/Baku': "బాకు, అజర్‌బైజాన్",
    'Europe/London': "లండన్, UK",
    'Europe/Dublin': "డబ్లిన్, ఐర్లాండ్",
    'Europe/Lisbon': "లిస్బన్, పోర్చుగల్",
    'Europe/Madrid': "మాడ్రిడ్, స్పెయిన్",
    'Europe/Paris': "పారిస్, ఫ్రాన్స్",
    'Europe/Brussels': "బ్రస్సెల్స్, బెల్జియం",
    'Europe/Amsterdam': "ఆమ్‌స్టర్‌డామ్, నెదర్లాండ్స్",
    'Europe/Berlin': "బెర్లిన్, జర్మనీ",
    'Europe/Zurich': "జ్యూరిచ్, స్విట్జర్లాండ్",
    'Europe/Rome': "రోమ్, ఇటలీ",
    'Europe/Vienna': "వియన్నా, ఆస్ట్రియా",
    'Europe/Prague': "ప్రేగ్, చెకియా",
    'Europe/Warsaw': "వార్సా, పోలాండ్",
    'Europe/Stockholm': "స్టాక్‌హోమ్, స్వీడన్",
    'Europe/Oslo': "ఓస్లో, నార్వే",
    'Europe/Copenhagen': "కోపెన్‌హాగన్, డెన్మార్క్",
    'Europe/Helsinki': "హెల్సింకి, ఫిన్లాండ్",
    'Europe/Athens': "ఏథెన్స్, గ్రీస్",
    'Europe/Istanbul': "ఇస్తాంబుల్, టర్కీ",
    'Europe/Kyiv': "కీవ్, ఉక్రెయిన్",
    'Europe/Moscow': "మాస్కో, రష్యా",
    'Africa/Cairo': "కైరో, ఈజిప్ట్",
    'Africa/Nairobi': "నైరోబి, కెన్యా",
    'Africa/Johannesburg': "జోహన్నెస్‌బర్గ్, దక్షిణాఫ్రికా",
    'Africa/Lagos': "లాగోస్, నైజీరియా",
    'Africa/Casablanca': "కాసాబ్లాంకా, మొరాకో",
    'Indian/Mauritius': "పోర్ట్ లూయిస్, మారిషస్",
    'America/New_York': "న్యూయార్క్, USA",
    'America/Toronto': "టొరంటో, కెనడా",
    'America/Chicago': "చికాగో, USA",
    'America/Denver': "డెన్వర్, USA",
    'America/Phoenix': "ఫీనిక్స్, USA",
    'America/Los_Angeles': "లాస్ ఏంజెలెస్ / శాన్ ఫ్రాన్సిస్కో, USA",
    'America/Vancouver': "వాంకోవర్, కెనడా",
    'America/Anchorage': "యాంకరేజ్, USA",
    'Pacific/Honolulu': "హోనోలులు, హవాయి",
    'America/Mexico_City': "మెక్సికో సిటీ, మెక్సికో",
    'America/Bogota': "బొగోటా, కొలంబియా",
    'America/Lima': "లిమా, పెరూ",
    'America/Santiago': "శాంటియాగో, చిలీ",
    'America/Sao_Paulo': "సావో పాలో, బ్రెజిల్",
    'America/Argentina/Buenos_Aires': "బ్యూనస్ ఎయిర్స్, అర్జెంటీనా",
    'America/Halifax': "హాలిఫాక్స్, కెనడా",
    'Australia/Perth': "పెర్త్, ఆస్ట్రేలియా",
    'Australia/Adelaide': "అడిలైడ్, ఆస్ట్రేలియా",
    'Australia/Brisbane': "బ్రిస్బేన్, ఆస్ట్రేలియా",
    'Australia/Sydney': "సిడ్నీ, ఆస్ట్రేలియా",
    'Australia/Melbourne': "మెల్‌బోర్న్, ఆస్ట్రేలియా",
    'Pacific/Auckland': "ఆక్లాండ్, న్యూజిలాండ్",
    'UTC': "UTC (ప్రపంచ ప్రామాణిక సమయం)"
  } },
  kn: { cities: {
    'Asia/Kolkata': "ಭಾರತ",
    'Asia/Dubai': "ದುಬೈ, UAE",
    'Asia/Riyadh': "ರಿಯಾದ್, ಸೌದಿ ಅರೇಬಿಯಾ",
    'Asia/Qatar': "ದೋಹಾ, ಕತಾರ್",
    'Asia/Kuwait': "ಕುವೈತ್ ಸಿಟಿ, ಕುವೈತ್",
    'Asia/Bahrain': "ಮನಾಮಾ, ಬಹ್ರೇನ್",
    'Asia/Muscat': "ಮಸ್ಕತ್, ಓಮನ್",
    'Asia/Tehran': "ಟೆಹ್ರಾನ್, ಇರಾನ್",
    'Asia/Jerusalem': "ಟೆಲ್ ಅವೀವ್, ಇಸ್ರೇಲ್",
    'Asia/Karachi': "ಕರಾಚಿ, ಪಾಕಿಸ್ತಾನ",
    'Asia/Kabul': "ಕಾಬೂಲ್, ಅಫ್ಘಾನಿಸ್ತಾನ",
    'Asia/Kathmandu': "ಕಠ್ಮಂಡು, ನೇಪಾಳ",
    'Asia/Dhaka': "ಢಾಕಾ, ಬಾಂಗ್ಲಾದೇಶ",
    'Asia/Colombo': "ಕೊಲಂಬೊ, ಶ್ರೀಲಂಕಾ",
    'Asia/Thimphu': "ಥಿಂಪು, ಭೂತಾನ್",
    'Asia/Yangon': "ಯಾಂಗೊನ್, ಮ್ಯಾನ್ಮಾರ್",
    'Asia/Bangkok': "ಬ್ಯಾಂಕಾಕ್, ಥೈಲ್ಯಾಂಡ್",
    'Asia/Jakarta': "ಜಕಾರ್ತಾ, ಇಂಡೋನೇಷ್ಯಾ",
    'Asia/Kuala_Lumpur': "ಕೌಲಾಲಂಪುರ, ಮಲೇಷ್ಯಾ",
    'Asia/Singapore': "ಸಿಂಗಾಪುರ",
    'Asia/Ho_Chi_Minh': "ಹೋ ಚಿ ಮಿನ್ ಸಿಟಿ, ವಿಯೆಟ್ನಾಂ",
    'Asia/Manila': "ಮನಿಲಾ, ಫಿಲಿಪ್ಪೀನ್ಸ್",
    'Asia/Hong_Kong': "ಹಾಂಗ್ ಕಾಂಗ್",
    'Asia/Shanghai': "ಬೀಜಿಂಗ್ / ಶಾಂಘೈ, ಚೀನಾ",
    'Asia/Taipei': "ತೈಪೆ, ತೈವಾನ್",
    'Asia/Seoul': "ಸಿಯೋಲ್, ದಕ್ಷಿಣ ಕೊರಿಯಾ",
    'Asia/Tokyo': "ಟೋಕಿಯೊ, ಜಪಾನ್",
    'Asia/Tashkent': "ತಾಷ್ಕೆಂಟ್, ಉಜ್ಬೇಕಿಸ್ತಾನ್",
    'Asia/Almaty': "ಅಲ್ಮಾಟಿ, ಕಜಕಿಸ್ತಾನ್",
    'Asia/Baku': "ಬಾಕು, ಅಜರ್‌ಬೈಜಾನ್",
    'Europe/London': "ಲಂಡನ್, UK",
    'Europe/Dublin': "ಡಬ್ಲಿನ್, ಐರ್ಲೆಂಡ್",
    'Europe/Lisbon': "ಲಿಸ್ಬನ್, ಪೋರ್ಚುಗಲ್",
    'Europe/Madrid': "ಮ್ಯಾಡ್ರಿಡ್, ಸ್ಪೇನ್",
    'Europe/Paris': "ಪ್ಯಾರಿಸ್, ಫ್ರಾನ್ಸ್",
    'Europe/Brussels': "ಬ್ರಸೆಲ್ಸ್, ಬೆಲ್ಜಿಯಂ",
    'Europe/Amsterdam': "ಆಮ್‌ಸ್ಟರ್‌ಡ್ಯಾಮ್, ನೆದರ್‌ಲ್ಯಾಂಡ್ಸ್",
    'Europe/Berlin': "ಬರ್ಲಿನ್, ಜರ್ಮನಿ",
    'Europe/Zurich': "ಜ್ಯೂರಿಚ್, ಸ್ವಿಟ್ಜರ್ಲೆಂಡ್",
    'Europe/Rome': "ರೋಮ್, ಇಟಲಿ",
    'Europe/Vienna': "ವಿಯೆನ್ನಾ, ಆಸ್ಟ್ರಿಯಾ",
    'Europe/Prague': "ಪ್ರೇಗ್, ಚೆಕಿಯಾ",
    'Europe/Warsaw': "ವಾರ್ಸಾ, ಪೋಲೆಂಡ್",
    'Europe/Stockholm': "ಸ್ಟಾಕ್‌ಹೋಮ್, ಸ್ವೀಡನ್",
    'Europe/Oslo': "ಓಸ್ಲೋ, ನಾರ್ವೆ",
    'Europe/Copenhagen': "ಕೋಪನ್‌ಹೇಗನ್, ಡೆನ್ಮಾರ್ಕ್",
    'Europe/Helsinki': "ಹೆಲ್ಸಿಂಕಿ, ಫಿನ್‌ಲ್ಯಾಂಡ್",
    'Europe/Athens': "ಅಥೆನ್ಸ್, ಗ್ರೀಸ್",
    'Europe/Istanbul': "ಇಸ್ತಾಂಬುಲ್, ಟರ್ಕಿ",
    'Europe/Kyiv': "ಕೀವ್, ಉಕ್ರೇನ್",
    'Europe/Moscow': "ಮಾಸ್ಕೋ, ರಷ್ಯಾ",
    'Africa/Cairo': "ಕೈರೋ, ಈಜಿಪ್ಟ್",
    'Africa/Nairobi': "ನೈರೋಬಿ, ಕೀನ್ಯಾ",
    'Africa/Johannesburg': "ಜೋಹಾನ್ಸ್‌ಬರ್ಗ್, ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ",
    'Africa/Lagos': "ಲಾಗೋಸ್, ನೈಜೀರಿಯಾ",
    'Africa/Casablanca': "ಕಾಸಾಬ್ಲಾಂಕಾ, ಮೊರಾಕೊ",
    'Indian/Mauritius': "ಪೋರ್ಟ್ ಲೂಯಿಸ್, ಮಾರಿಷಸ್",
    'America/New_York': "ನ್ಯೂಯಾರ್ಕ್, USA",
    'America/Toronto': "ಟೊರೊಂಟೊ, ಕೆನಡಾ",
    'America/Chicago': "ಚಿಕಾಗೊ, USA",
    'America/Denver': "ಡೆನ್ವರ್, USA",
    'America/Phoenix': "ಫೀನಿಕ್ಸ್, USA",
    'America/Los_Angeles': "ಲಾಸ್ ಏಂಜಲೀಸ್ / ಸ್ಯಾನ್ ಫ್ರಾನ್ಸಿಸ್ಕೊ, USA",
    'America/Vancouver': "ವ್ಯಾಂಕೋವರ್, ಕೆನಡಾ",
    'America/Anchorage': "ಆಂಕರೇಜ್, USA",
    'Pacific/Honolulu': "ಹೊನೊಲುಲು, ಹವಾಯಿ",
    'America/Mexico_City': "ಮೆಕ್ಸಿಕೊ ಸಿಟಿ, ಮೆಕ್ಸಿಕೊ",
    'America/Bogota': "ಬೊಗೋಟಾ, ಕೊಲಂಬಿಯಾ",
    'America/Lima': "ಲಿಮಾ, ಪೆರು",
    'America/Santiago': "ಸ್ಯಾಂಟಿಯಾಗೊ, ಚಿಲಿ",
    'America/Sao_Paulo': "ಸಾವೊ ಪಾಲೊ, ಬ್ರೆಜಿಲ್",
    'America/Argentina/Buenos_Aires': "ಬ್ಯೂನಸ್ ಐರಿಸ್, ಅರ್ಜೆಂಟೀನಾ",
    'America/Halifax': "ಹ್ಯಾಲಿಫ್ಯಾಕ್ಸ್, ಕೆನಡಾ",
    'Australia/Perth': "ಪರ್ತ್, ಆಸ್ಟ್ರೇಲಿಯಾ",
    'Australia/Adelaide': "ಅಡಿಲೇಡ್, ಆಸ್ಟ್ರೇಲಿಯಾ",
    'Australia/Brisbane': "ಬ್ರಿಸ್ಬೇನ್, ಆಸ್ಟ್ರೇಲಿಯಾ",
    'Australia/Sydney': "ಸಿಡ್ನಿ, ಆಸ್ಟ್ರೇಲಿಯಾ",
    'Australia/Melbourne': "ಮೆಲ್ಬರ್ನ್, ಆಸ್ಟ್ರೇಲಿಯಾ",
    'Pacific/Auckland': "ಆಕ್ಲೆಂಡ್, ನ್ಯೂಜಿಲೆಂಡ್",
    'UTC': "UTC (ವಿಶ್ವ ಪ್ರಮಾಣಿತ ಸಮಯ)"
  } },
  ml: { cities: {
    'Asia/Kolkata': "ഇന്ത്യ",
    'Asia/Dubai': "ദുബായ്, UAE",
    'Asia/Riyadh': "റിയാദ്, സൗദി അറേബ്യ",
    'Asia/Qatar': "ദോഹ, ഖത്തർ",
    'Asia/Kuwait': "കുവൈറ്റ് സിറ്റി, കുവൈറ്റ്",
    'Asia/Bahrain': "മനാമ, ബഹ്റൈൻ",
    'Asia/Muscat': "മസ്കത്ത്, ഒമാൻ",
    'Asia/Tehran': "ടെഹ്റാൻ, ഇറാൻ",
    'Asia/Jerusalem': "ടെൽ അവീവ്, ഇസ്രയേൽ",
    'Asia/Karachi': "കറാച്ചി, പാകിസ്ഥാൻ",
    'Asia/Kabul': "കാബൂൾ, അഫ്ഗാനിസ്ഥാൻ",
    'Asia/Kathmandu': "കാഠ്മണ്ഡു, നേപ്പാൾ",
    'Asia/Dhaka': "ധാക്ക, ബംഗ്ലാദേശ്",
    'Asia/Colombo': "കൊളംബോ, ശ്രീലങ്ക",
    'Asia/Thimphu': "തിംഫു, ഭൂട്ടാൻ",
    'Asia/Yangon': "യാങ്കൂൻ, മ്യാൻമർ",
    'Asia/Bangkok': "ബാങ്കോക്ക്, തായ്‌ലൻഡ്",
    'Asia/Jakarta': "ജക്കാർത്ത, ഇന്തോനേഷ്യ",
    'Asia/Kuala_Lumpur': "ക്വാലാലംപൂർ, മലേഷ്യ",
    'Asia/Singapore': "സിംഗപ്പൂർ",
    'Asia/Ho_Chi_Minh': "ഹോ ചി മിൻ സിറ്റി, വിയറ്റ്നാം",
    'Asia/Manila': "മനില, ഫിലിപ്പീൻസ്",
    'Asia/Hong_Kong': "ഹോങ്കോങ്",
    'Asia/Shanghai': "ബെയ്ജിംഗ് / ഷാങ്ഹായ്, ചൈന",
    'Asia/Taipei': "തായ്‌പേയ്, തായ്‌വാൻ",
    'Asia/Seoul': "സിയോൾ, ദക്ഷിണ കൊറിയ",
    'Asia/Tokyo': "ടോക്കിയോ, ജപ്പാൻ",
    'Asia/Tashkent': "താഷ്കന്റ്, ഉസ്ബെക്കിസ്ഥാൻ",
    'Asia/Almaty': "അൽമാട്ടി, കസാഖ്സ്ഥാൻ",
    'Asia/Baku': "ബാക്കു, അസർബൈജാൻ",
    'Europe/London': "ലണ്ടൻ, UK",
    'Europe/Dublin': "ഡബ്ലിൻ, അയർലൻഡ്",
    'Europe/Lisbon': "ലിസ്ബൻ, പോർച്ചുഗൽ",
    'Europe/Madrid': "മാഡ്രിഡ്, സ്പെയിൻ",
    'Europe/Paris': "പാരീസ്, ഫ്രാൻസ്",
    'Europe/Brussels': "ബ്രസൽസ്, ബെൽജിയം",
    'Europe/Amsterdam': "ആംസ്റ്റർഡാം, നെതർലൻഡ്സ്",
    'Europe/Berlin': "ബെർലിൻ, ജർമനി",
    'Europe/Zurich': "സൂറിച്ച്, സ്വിറ്റ്സർലൻഡ്",
    'Europe/Rome': "റോം, ഇറ്റലി",
    'Europe/Vienna': "വിയന്ന, ഓസ്ട്രിയ",
    'Europe/Prague': "പ്രാഗ്, ചെക്കിയ",
    'Europe/Warsaw': "വാഴ്സോ, പോളണ്ട്",
    'Europe/Stockholm': "സ്റ്റോക്ക്ഹോം, സ്വീഡൻ",
    'Europe/Oslo': "ഓസ്ലോ, നോർവേ",
    'Europe/Copenhagen': "കോപ്പൻഹേഗൻ, ഡെന്മാർക്ക്",
    'Europe/Helsinki': "ഹെൽസിങ്കി, ഫിൻലൻഡ്",
    'Europe/Athens': "ഏഥൻസ്, ഗ്രീസ്",
    'Europe/Istanbul': "ഇസ്താംബുൾ, തുർക്കി",
    'Europe/Kyiv': "കീവ്, ഉക്രെയ്ൻ",
    'Europe/Moscow': "മോസ്കോ, റഷ്യ",
    'Africa/Cairo': "കെയ്റോ, ഈജിപ്ത്",
    'Africa/Nairobi': "നെയ്റോബി, കെനിയ",
    'Africa/Johannesburg': "ജോഹന്നാസ്ബർഗ്, ദക്ഷിണാഫ്രിക്ക",
    'Africa/Lagos': "ലാഗോസ്, നൈജീരിയ",
    'Africa/Casablanca': "കാസാബ്ലാങ്ക, മൊറോക്കോ",
    'Indian/Mauritius': "പോർട്ട് ലൂയിസ്, മൗറീഷ്യസ്",
    'America/New_York': "ന്യൂയോർക്ക്, USA",
    'America/Toronto': "ടൊറന്റോ, കാനഡ",
    'America/Chicago': "ഷിക്കാഗോ, USA",
    'America/Denver': "ഡെൻവർ, USA",
    'America/Phoenix': "ഫീനിക്സ്, USA",
    'America/Los_Angeles': "ലോസ് ആഞ്ചലസ് / സാൻ ഫ്രാൻസിസ്കോ, USA",
    'America/Vancouver': "വാൻകൂവർ, കാനഡ",
    'America/Anchorage': "ആങ്കറേജ്, USA",
    'Pacific/Honolulu': "ഹോണോലുലു, ഹവായ്",
    'America/Mexico_City': "മെക്സിക്കോ സിറ്റി, മെക്സിക്കോ",
    'America/Bogota': "ബൊഗോട്ട, കൊളംബിയ",
    'America/Lima': "ലിമ, പെറു",
    'America/Santiago': "സാന്റിയാഗോ, ചിലി",
    'America/Sao_Paulo': "സാവോ പോളോ, ബ്രസീൽ",
    'America/Argentina/Buenos_Aires': "ബ്യൂണസ് അയേഴ്സ്, അർജന്റീന",
    'America/Halifax': "ഹാലിഫാക്സ്, കാനഡ",
    'Australia/Perth': "പെർത്ത്, ഓസ്ട്രേലിയ",
    'Australia/Adelaide': "അഡ്ലെയ്ഡ്, ഓസ്ട്രേലിയ",
    'Australia/Brisbane': "ബ്രിസ്ബേൻ, ഓസ്ട്രേലിയ",
    'Australia/Sydney': "സിഡ്നി, ഓസ്ട്രേലിയ",
    'Australia/Melbourne': "മെൽബൺ, ഓസ്ട്രേലിയ",
    'Pacific/Auckland': "ഓക്ക്ലൻഡ്, ന്യൂസിലൻഡ്",
    'UTC': "UTC (ലോക മാനക സമയം)"
  } },
  ur: { cities: {
    'Asia/Kolkata': "بھارت",
    'Asia/Dubai': "دبئی، UAE",
    'Asia/Riyadh': "ریاض، سعودی عرب",
    'Asia/Qatar': "دوحہ، قطر",
    'Asia/Kuwait': "کویت سٹی، کویت",
    'Asia/Bahrain': "منامہ، بحرین",
    'Asia/Muscat': "مسقط، عمان",
    'Asia/Tehran': "تہران، ایران",
    'Asia/Jerusalem': "تل ابیب، اسرائیل",
    'Asia/Karachi': "کراچی، پاکستان",
    'Asia/Kabul': "کابل، افغانستان",
    'Asia/Kathmandu': "کھٹمنڈو، نیپال",
    'Asia/Dhaka': "ڈھاکہ، بنگلہ دیش",
    'Asia/Colombo': "کولمبو، سری لنکا",
    'Asia/Thimphu': "تھمپو، بھوٹان",
    'Asia/Yangon': "ینگون، میانمار",
    'Asia/Bangkok': "بنکاک، تھائی لینڈ",
    'Asia/Jakarta': "جکارتہ، انڈونیشیا",
    'Asia/Kuala_Lumpur': "کوالالمپور، ملائیشیا",
    'Asia/Singapore': "سنگاپور",
    'Asia/Ho_Chi_Minh': "ہو چی منہ سٹی، ویتنام",
    'Asia/Manila': "منیلا، فلپائن",
    'Asia/Hong_Kong': "ہانگ کانگ",
    'Asia/Shanghai': "بیجنگ / شنگھائی، چین",
    'Asia/Taipei': "تائپے، تائیوان",
    'Asia/Seoul': "سیول، جنوبی کوریا",
    'Asia/Tokyo': "ٹوکیو، جاپان",
    'Asia/Tashkent': "تاشقند، ازبکستان",
    'Asia/Almaty': "الماتی، قازقستان",
    'Asia/Baku': "باکو، آذربائیجان",
    'Europe/London': "لندن، UK",
    'Europe/Dublin': "ڈبلن، آئرلینڈ",
    'Europe/Lisbon': "لزبن، پرتگال",
    'Europe/Madrid': "میڈرڈ، اسپین",
    'Europe/Paris': "پیرس، فرانس",
    'Europe/Brussels': "برسلز، بیلجیم",
    'Europe/Amsterdam': "ایمسٹرڈیم، نیدرلینڈز",
    'Europe/Berlin': "برلن، جرمنی",
    'Europe/Zurich': "زیورخ، سوئٹزرلینڈ",
    'Europe/Rome': "روم، اٹلی",
    'Europe/Vienna': "ویانا، آسٹریا",
    'Europe/Prague': "پراگ، چیکیا",
    'Europe/Warsaw': "وارسا، پولینڈ",
    'Europe/Stockholm': "اسٹاک ہوم، سویڈن",
    'Europe/Oslo': "اوسلو، ناروے",
    'Europe/Copenhagen': "کوپن ہیگن، ڈنمارک",
    'Europe/Helsinki': "ہیلسنکی، فنلینڈ",
    'Europe/Athens': "ایتھنز، یونان",
    'Europe/Istanbul': "استنبول، ترکی",
    'Europe/Kyiv': "کیف، یوکرین",
    'Europe/Moscow': "ماسکو، روس",
    'Africa/Cairo': "قاہرہ، مصر",
    'Africa/Nairobi': "نیروبی، کینیا",
    'Africa/Johannesburg': "جوہانسبرگ، جنوبی افریقہ",
    'Africa/Lagos': "لاگوس، نائیجیریا",
    'Africa/Casablanca': "کاسابلانکا، مراکش",
    'Indian/Mauritius': "پورٹ لوئس، ماریشس",
    'America/New_York': "نیویارک، USA",
    'America/Toronto': "ٹورنٹو، کینیڈا",
    'America/Chicago': "شکاگو، USA",
    'America/Denver': "ڈینور، USA",
    'America/Phoenix': "فینکس، USA",
    'America/Los_Angeles': "لاس اینجلس / سان فرانسسکو، USA",
    'America/Vancouver': "وینکوور، کینیڈا",
    'America/Anchorage': "اینکریج، USA",
    'Pacific/Honolulu': "ہونولولو، ہوائی",
    'America/Mexico_City': "میکسیکو سٹی، میکسیکو",
    'America/Bogota': "بوگوٹا، کولمبیا",
    'America/Lima': "لیما، پیرو",
    'America/Santiago': "سینٹیاگو، چلی",
    'America/Sao_Paulo': "ساؤ پالو، برازیل",
    'America/Argentina/Buenos_Aires': "بیونس آئرس، ارجنٹائن",
    'America/Halifax': "ہیلیفیکس، کینیڈا",
    'Australia/Perth': "پرتھ، آسٹریلیا",
    'Australia/Adelaide': "ایڈیلیڈ، آسٹریلیا",
    'Australia/Brisbane': "برسبین، آسٹریلیا",
    'Australia/Sydney': "سڈنی، آسٹریلیا",
    'Australia/Melbourne': "میلبورن، آسٹریلیا",
    'Pacific/Auckland': "آکلینڈ، نیوزی لینڈ",
    'UTC': "UTC (عالمی معیاری وقت)"
  } }
};
