/* UI strings for the Neural Network Playground. Keys are identical in all 12 languages. */
window.APP_STRINGS = {
  en: {
    app_title: 'Neural Network Playground',
    intro: 'Watch a tiny neural network learn to separate orange and blue dots. Change its layers, neurons and settings to see how a machine learns from examples.',
    train: 'Train',
    step: 'Step',
    step_title: 'Train for one epoch (one round through all the training points)',
    reset_title: 'Start learning again with new random weights',
    epoch: 'Epoch',
    speed: 'Speed',
    speed_slow: 'Slow',
    speed_normal: 'Normal',
    speed_fast: 'Fast',
    data: 'Data',
    dataset: 'Choose a dataset',
    ds_blobs: 'Two blobs',
    ds_circle: 'Circle',
    ds_xor: 'XOR',
    ds_spiral: 'Spiral',
    ds_draw: 'Draw your own',
    draw_hint: 'Pick a colour, then tap or drag on the picture to add points. All your points are used for training.',
    tool_orange: 'Orange',
    tool_blue: 'Blue',
    tool_erase: 'Eraser',
    clear_points: 'Clear points',
    confirm_clear: 'Remove all the points you drew?',
    too_many: 'You can draw up to {n} points.',
    points_n: 'Points: {n}',
    noise: 'Noise: {n}%',
    noise_hint: 'More noise means messier, mixed-up points.',
    split: 'Training data: {n}%',
    split_hint: 'The other {n}% is kept aside to test the network on points it has never seen.',
    new_data: 'New data',
    show_test: 'Show test points',
    sharp: 'Sharp boundary',
    network: 'Network',
    inputs: 'Inputs (features)',
    inputs_hint: 'Extra inputs give the network extra clues.',
    need_input: 'Keep at least one input.',
    hidden_layers: 'Hidden layers',
    layer_n: 'Layer {n}',
    neurons: 'Neurons',
    add_layer: 'Add a hidden layer',
    remove_layer: 'Remove a hidden layer',
    add_neuron: 'Add a neuron to layer {n}',
    remove_neuron: 'Remove a neuron from layer {n}',
    no_hidden: 'No hidden layer: the whole network is a single neuron.',
    activation: 'Activation',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'Sigmoid',
    act_linear: 'Linear (none)',
    lr: 'Learning rate',
    share_setup: 'Share this setup',
    defaults: 'Restore defaults',
    inside: 'Inside the network',
    inside_hint: 'Each square shows what one neuron "sees" across the picture. Tap a square to see it big.',
    w_pos: 'positive weight',
    w_neg: 'negative weight',
    w_thick: 'Thicker line = stronger weight',
    output: 'Output',
    output_hint: 'Background colour = the network\'s guess for every spot. Darker = more sure.',
    canvas_label: 'Picture of the points and the network\'s guesses',
    canvas_empty: 'Tap here to add points',
    train_loss: 'Training loss',
    test_loss: 'Test loss',
    train_acc: 'Training accuracy',
    test_acc: 'Test accuracy',
    loss_chart: 'Loss over time',
    chart_label: 'Chart of training loss and test loss after each epoch',
    legend_train: 'Training',
    legend_test: 'Test',
    chart_hint: 'Lower is better. If the test line goes up while the training line goes down, the network is overfitting.',
    ins_hint: 'These are this neuron’s weights and bias right now. Watch them change as it learns.',
    ins_prev: 'h₁, h₂… are the neurons of the layer before.',
    ins_input: 'An input has no weights. It just passes its value on to the next layer.',
    col_inputs: 'Inputs',
    col_hidden: 'Hidden {n}',
    col_output: 'Output',
    node_input: 'Input {name}',
    node_hidden: 'Neuron {n} in hidden layer {l}',
    node_output: 'Output neuron',
    preview_input: 'Showing input {name}',
    preview_hidden: 'Showing neuron {n} of hidden layer {l}',
    show_output: 'Show output',
    coach_start: 'Press Train to let the network learn. The background shows its guess for every spot.',
    coach_training: 'Learning… watch the loss go down and the colours settle.',
    coach_paused: 'Paused. Press Step to train one epoch at a time.',
    coach_line: 'With no hidden layer the network can only draw one straight line, and that is not enough here. Add a hidden layer!',
    coach_linear: 'With the Linear activation, even many layers act like one straight line. Try tanh or ReLU.',
    coach_overfit: 'Training loss is low but test loss is high: the network is memorising the training points. This is overfitting.',
    coach_great: 'Learned it! {acc}% of the test points are on the correct side.',
    coach_great_draw: 'Learned it! {acc}% of your points are on the correct side.',
    coach_slow: 'Learning very slowly? The learning rate is tiny, so each step is tiny. Try a bigger one.',
    coach_stuck: 'Stuck? Press Reset to try new random weights, or change the network.',
    coach_explode: 'Oops! The weights blew up because the learning rate is too big. Choose a smaller one.',
    coach_need_points: 'Add some orange and some blue points on the picture.',
    challenges: 'Challenges',
    challenges_intro: 'Guess first, then press Try it and train. Were you right?',
    try_it: 'Try it',
    notice: 'What to notice',
    loaded: 'Challenge {n} is ready. Press Train!',
    print_ws: 'Print worksheet',
    ws_title: 'Worksheet',
    ws_name: 'Name',
    ws_class: 'Class',
    ws_date: 'Date',
    ws_guess: 'My guess:',
    ws_saw: 'What happened, and why:',
    explain: 'What is happening inside?',
    help_title: 'How to use / Ideas for the classroom',
    tip1: 'Press <b>Train</b> (or the <kbd>Space</kbd> key) and watch the colours change as the network learns. <b>Step</b> trains for just one epoch, so you can go slowly.',
    tip2: 'Change the dataset, the number of hidden layers and the neurons. Changing the network starts it again with fresh random weights. <b>Reset</b> does the same.',
    tip3: 'Tap the small squares in <b>Inside the network</b> to see what each neuron has learned. Neurons in later layers mix simple shapes into complex ones.',
    tip4: 'Choose <b>Draw your own</b>, pick a colour and tap on the picture to make your own puzzle. Can you draw one that the network cannot learn?',
    tip5: '<b>Classroom activity:</b> before each challenge, let the class vote: "Will it learn?" Press Train together on the smartboard and discuss why. Print the worksheet to note guesses.',
    tip6: 'Use <b>Full screen</b> on a projector. <b>Share this setup</b> makes a link to send to students. Everything runs on this device and works offline.'
  },
  hi: {
    app_title: 'न्यूरल नेटवर्क खेल-मैदान',
    intro: 'देखिए, एक छोटा-सा न्यूरल नेटवर्क नारंगी और नीले बिंदुओं को अलग करना कैसे सीखता है। इसकी लेयर, न्यूरॉन और सेटिंग बदलकर समझिए कि मशीन उदाहरणों से कैसे सीखती है।',
    train: 'सिखाएँ',
    step: 'एक कदम',
    step_title: 'एक एपॉक के लिए सिखाएँ (सभी ट्रेनिंग बिंदुओं पर एक पूरा चक्कर)',
    reset_title: 'नए रैंडम वेट के साथ फिर से सीखना शुरू करें',
    epoch: 'एपॉक',
    speed: 'रफ़्तार',
    speed_slow: 'धीमी',
    speed_normal: 'सामान्य',
    speed_fast: 'तेज़',
    data: 'डेटा',
    dataset: 'डेटासेट चुनें',
    ds_blobs: 'दो झुंड',
    ds_circle: 'गोला',
    ds_xor: 'XOR',
    ds_spiral: 'सर्पिल',
    ds_draw: 'खुद बनाएँ',
    draw_hint: 'एक रंग चुनें, फिर चित्र पर टैप करें या उँगली घुमाकर बिंदु जोड़ें। आपके सारे बिंदु ट्रेनिंग के लिए इस्तेमाल होते हैं।',
    tool_orange: 'नारंगी',
    tool_blue: 'नीला',
    tool_erase: 'रबर',
    clear_points: 'बिंदु मिटाएँ',
    confirm_clear: 'आपके बनाए सारे बिंदु हटा दें?',
    too_many: 'आप ज़्यादा से ज़्यादा {n} बिंदु बना सकते हैं।',
    points_n: 'बिंदु: {n}',
    noise: 'शोर (नॉइज़): {n}%',
    noise_hint: 'ज़्यादा शोर यानी ज़्यादा बिखरे और मिले-जुले बिंदु।',
    split: 'ट्रेनिंग डेटा: {n}%',
    split_hint: 'बाकी {n}% बिंदु अलग रखे जाते हैं, ताकि नेटवर्क को ऐसे बिंदुओं पर परखा जा सके जो उसने कभी नहीं देखे।',
    new_data: 'नया डेटा',
    show_test: 'टेस्ट बिंदु दिखाएँ',
    sharp: 'साफ़ सीमा-रेखा',
    network: 'नेटवर्क',
    inputs: 'इनपुट (फ़ीचर)',
    inputs_hint: 'ज़्यादा इनपुट से नेटवर्क को ज़्यादा सुराग मिलते हैं।',
    need_input: 'कम से कम एक इनपुट रखना ज़रूरी है।',
    hidden_layers: 'हिडन लेयर',
    layer_n: 'लेयर {n}',
    neurons: 'न्यूरॉन',
    add_layer: 'एक हिडन लेयर जोड़ें',
    remove_layer: 'एक हिडन लेयर हटाएँ',
    add_neuron: 'लेयर {n} में एक न्यूरॉन जोड़ें',
    remove_neuron: 'लेयर {n} से एक न्यूरॉन हटाएँ',
    no_hidden: 'कोई हिडन लेयर नहीं: पूरा नेटवर्क बस एक न्यूरॉन है।',
    activation: 'एक्टिवेशन',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'सिग्मॉइड',
    act_linear: 'लीनियर (कोई नहीं)',
    lr: 'लर्निंग रेट',
    share_setup: 'यह सेटअप शेयर करें',
    defaults: 'शुरुआती सेटिंग वापस लाएँ',
    inside: 'नेटवर्क के अंदर',
    inside_hint: 'हर खाना दिखाता है कि एक न्यूरॉन पूरे चित्र में क्या "देखता" है। बड़ा देखने के लिए किसी खाने पर टैप करें।',
    w_pos: 'पॉज़िटिव वेट',
    w_neg: 'नेगेटिव वेट',
    w_thick: 'मोटी लाइन = ज़्यादा ताक़तवर वेट',
    output: 'आउटपुट',
    output_hint: 'पृष्ठभूमि का रंग = हर जगह के लिए नेटवर्क का अंदाज़ा। गहरा रंग = ज़्यादा पक्का।',
    canvas_label: 'बिंदुओं और नेटवर्क के अंदाज़ों का चित्र',
    canvas_empty: 'बिंदु जोड़ने के लिए यहाँ टैप करें',
    train_loss: 'ट्रेनिंग लॉस',
    test_loss: 'टेस्ट लॉस',
    train_acc: 'ट्रेनिंग सटीकता',
    test_acc: 'टेस्ट सटीकता',
    loss_chart: 'समय के साथ लॉस',
    chart_label: 'हर एपॉक के बाद ट्रेनिंग लॉस और टेस्ट लॉस का चार्ट',
    legend_train: 'ट्रेनिंग',
    legend_test: 'टेस्ट',
    chart_hint: 'जितना कम, उतना अच्छा। अगर ट्रेनिंग वाली लाइन नीचे जाए पर टेस्ट वाली लाइन ऊपर चढ़े, तो नेटवर्क ओवरफ़िटिंग कर रहा है।',
    ins_hint: 'ये इस न्यूरॉन के अभी के वेट और बायस हैं। सीखते समय इन्हें बदलते हुए देखें।',
    ins_prev: 'h₁, h₂… पिछली लेयर के न्यूरॉन हैं।',
    ins_input: 'इनपुट का कोई वेट नहीं होता। वह बस अपनी वैल्यू अगली लेयर को दे देता है।',
    col_inputs: 'इनपुट',
    col_hidden: 'हिडन {n}',
    col_output: 'आउटपुट',
    node_input: 'इनपुट {name}',
    node_hidden: 'हिडन लेयर {l} का न्यूरॉन {n}',
    node_output: 'आउटपुट न्यूरॉन',
    preview_input: 'इनपुट {name} दिख रहा है',
    preview_hidden: 'हिडन लेयर {l} का न्यूरॉन {n} दिख रहा है',
    show_output: 'आउटपुट दिखाएँ',
    coach_start: 'नेटवर्क को सिखाने के लिए "सिखाएँ" दबाएँ। पृष्ठभूमि हर जगह के लिए उसका अंदाज़ा दिखाती है।',
    coach_training: 'सीख रहा है… लॉस को घटते और रंगों को जमते हुए देखें।',
    coach_paused: 'रुका हुआ है। एक-एक एपॉक सिखाने के लिए "एक कदम" दबाएँ।',
    coach_line: 'हिडन लेयर के बिना नेटवर्क सिर्फ़ एक सीधी रेखा खींच सकता है, और यहाँ वह काफ़ी नहीं। एक हिडन लेयर जोड़ें!',
    coach_linear: 'लीनियर एक्टिवेशन के साथ कई लेयर भी एक सीधी रेखा जैसा ही काम करती हैं। tanh या ReLU आज़माएँ।',
    coach_overfit: 'ट्रेनिंग लॉस कम है पर टेस्ट लॉस ज़्यादा: नेटवर्क ट्रेनिंग बिंदुओं को रट रहा है। इसे ओवरफ़िटिंग कहते हैं।',
    coach_great: 'सीख लिया! {acc}% टेस्ट बिंदु सही तरफ़ हैं।',
    coach_great_draw: 'सीख लिया! आपके {acc}% बिंदु सही तरफ़ हैं।',
    coach_slow: 'बहुत धीरे सीख रहा है? लर्निंग रेट बहुत छोटा है, इसलिए हर कदम भी छोटा है। बड़ा रेट आज़माएँ।',
    coach_stuck: 'अटक गया? नए रैंडम वेट के लिए रीसेट दबाएँ, या नेटवर्क बदलें।',
    coach_explode: 'अरे! लर्निंग रेट बहुत बड़ा होने से वेट बेकाबू हो गए। छोटा रेट चुनें।',
    coach_need_points: 'चित्र पर कुछ नारंगी और कुछ नीले बिंदु जोड़ें।',
    challenges: 'चुनौतियाँ',
    challenges_intro: 'पहले अंदाज़ा लगाएँ, फिर "आज़माएँ" दबाकर सिखाएँ। क्या आपका अंदाज़ा सही निकला?',
    try_it: 'आज़माएँ',
    notice: 'किस बात पर ध्यान दें',
    loaded: 'चुनौती {n} तैयार है। "सिखाएँ" दबाएँ!',
    print_ws: 'वर्कशीट प्रिंट करें',
    ws_title: 'वर्कशीट',
    ws_name: 'नाम',
    ws_class: 'कक्षा',
    ws_date: 'तारीख़',
    ws_guess: 'मेरा अंदाज़ा:',
    ws_saw: 'क्या हुआ, और क्यों:',
    explain: 'अंदर क्या हो रहा है?',
    help_title: 'कैसे इस्तेमाल करें / कक्षा के लिए सुझाव',
    tip1: '<b>सिखाएँ</b> (या <kbd>स्पेसबार</kbd>) दबाएँ और नेटवर्क के सीखते समय रंगों को बदलते देखें। <b>एक कदम</b> सिर्फ़ एक एपॉक सिखाता है, ताकि आप धीरे-धीरे चल सकें।',
    tip2: 'डेटासेट, हिडन लेयर की संख्या और न्यूरॉन बदलें। नेटवर्क बदलते ही वह नए रैंडम वेट के साथ फिर से शुरू होता है। <b>रीसेट</b> भी यही करता है।',
    tip3: '<b>नेटवर्क के अंदर</b> वाले छोटे खानों पर टैप करके देखें कि हर न्यूरॉन ने क्या सीखा। आगे की लेयर के न्यूरॉन आसान आकारों को मिलाकर मुश्किल आकार बनाते हैं।',
    tip4: '<b>खुद बनाएँ</b> चुनें, रंग चुनें और चित्र पर टैप करके अपनी पहेली बनाएँ। क्या आप ऐसी पहेली बना सकते हैं जो नेटवर्क न सीख पाए?',
    tip5: '<b>कक्षा गतिविधि:</b> हर चुनौती से पहले पूरी कक्षा वोट करे: "क्या यह सीख पाएगा?" फिर स्मार्टबोर्ड पर साथ में "सिखाएँ" दबाएँ और चर्चा करें कि ऐसा क्यों हुआ। अंदाज़े लिखने के लिए वर्कशीट प्रिंट करें।',
    tip6: 'प्रोजेक्टर पर <b>पूरी स्क्रीन</b> इस्तेमाल करें। <b>यह सेटअप शेयर करें</b> से छात्रों को भेजने के लिए लिंक बनता है। सब कुछ इसी डिवाइस पर चलता है और बिना इंटरनेट भी काम करता है।'
  },
  bn: {
    app_title: 'নিউরাল নেটওয়ার্ক খেলাঘর',
    intro: 'দেখুন, একটি ছোট্ট নিউরাল নেটওয়ার্ক কীভাবে কমলা আর নীল বিন্দু আলাদা করতে শেখে। এর লেয়ার, নিউরন আর সেটিং বদলে বুঝুন মেশিন কীভাবে উদাহরণ থেকে শেখে।',
    train: 'শেখান',
    step: 'এক ধাপ',
    step_title: 'এক এপক শেখান (সব ট্রেনিং বিন্দুর উপর দিয়ে একবার পুরো ঘোরা)',
    reset_title: 'নতুন র‍্যান্ডম ওয়েট নিয়ে আবার শেখা শুরু করুন',
    epoch: 'এপক',
    speed: 'গতি',
    speed_slow: 'ধীর',
    speed_normal: 'সাধারণ',
    speed_fast: 'দ্রুত',
    data: 'ডেটা',
    dataset: 'ডেটাসেট বাছুন',
    ds_blobs: 'দুটি গুচ্ছ',
    ds_circle: 'বৃত্ত',
    ds_xor: 'XOR',
    ds_spiral: 'সর্পিল',
    ds_draw: 'নিজে আঁকুন',
    draw_hint: 'একটি রং বাছুন, তারপর ছবিতে ট্যাপ করুন বা আঙুল টেনে বিন্দু যোগ করুন। আপনার সব বিন্দু ট্রেনিংয়ে ব্যবহার হয়।',
    tool_orange: 'কমলা',
    tool_blue: 'নীল',
    tool_erase: 'ইরেজার',
    clear_points: 'বিন্দু মুছুন',
    confirm_clear: 'আপনার আঁকা সব বিন্দু মুছে ফেলবেন?',
    too_many: 'আপনি সর্বোচ্চ {n}টি বিন্দু আঁকতে পারেন।',
    points_n: 'বিন্দু: {n}',
    noise: 'নয়েজ: {n}%',
    noise_hint: 'বেশি নয়েজ মানে বেশি এলোমেলো, মিশে যাওয়া বিন্দু।',
    split: 'ট্রেনিং ডেটা: {n}%',
    split_hint: 'বাকি {n}% আলাদা রাখা হয়, যাতে নেটওয়ার্ক কখনও দেখেনি এমন বিন্দুতে তাকে পরীক্ষা করা যায়।',
    new_data: 'নতুন ডেটা',
    show_test: 'টেস্ট বিন্দু দেখান',
    sharp: 'স্পষ্ট সীমারেখা',
    network: 'নেটওয়ার্ক',
    inputs: 'ইনপুট (ফিচার)',
    inputs_hint: 'বাড়তি ইনপুট নেটওয়ার্ককে বাড়তি সূত্র দেয়।',
    need_input: 'অন্তত একটি ইনপুট রাখতেই হবে।',
    hidden_layers: 'হিডেন লেয়ার',
    layer_n: 'লেয়ার {n}',
    neurons: 'নিউরন',
    add_layer: 'একটি হিডেন লেয়ার যোগ করুন',
    remove_layer: 'একটি হিডেন লেয়ার সরান',
    add_neuron: 'লেয়ার {n}-এ একটি নিউরন যোগ করুন',
    remove_neuron: 'লেয়ার {n} থেকে একটি নিউরন সরান',
    no_hidden: 'কোনো হিডেন লেয়ার নেই: পুরো নেটওয়ার্কটাই একটি নিউরন।',
    activation: 'অ্যাক্টিভেশন',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'সিগময়েড',
    act_linear: 'লিনিয়ার (কিছু নয়)',
    lr: 'লার্নিং রেট',
    share_setup: 'এই সেটআপ শেয়ার করুন',
    defaults: 'শুরুর সেটিং ফিরিয়ে আনুন',
    inside: 'নেটওয়ার্কের ভেতরে',
    inside_hint: 'প্রতিটি ঘর দেখায় একটি নিউরন পুরো ছবিতে কী "দেখে"। বড় করে দেখতে কোনো ঘরে ট্যাপ করুন।',
    w_pos: 'পজিটিভ ওয়েট',
    w_neg: 'নেগেটিভ ওয়েট',
    w_thick: 'মোটা লাইন = বেশি শক্তিশালী ওয়েট',
    output: 'আউটপুট',
    output_hint: 'পেছনের রং = প্রতিটি জায়গার জন্য নেটওয়ার্কের অনুমান। গাঢ় রং = বেশি নিশ্চিত।',
    canvas_label: 'বিন্দু আর নেটওয়ার্কের অনুমানের ছবি',
    canvas_empty: 'বিন্দু যোগ করতে এখানে ট্যাপ করুন',
    train_loss: 'ট্রেনিং লস',
    test_loss: 'টেস্ট লস',
    train_acc: 'ট্রেনিং নির্ভুলতা',
    test_acc: 'টেস্ট নির্ভুলতা',
    loss_chart: 'সময়ের সাথে লস',
    chart_label: 'প্রতি এপকের পরে ট্রেনিং লস আর টেস্ট লসের চার্ট',
    legend_train: 'ট্রেনিং',
    legend_test: 'টেস্ট',
    chart_hint: 'যত কম, তত ভালো। ট্রেনিং লাইন নামতে থাকলেও টেস্ট লাইন যদি উঠতে থাকে, তাহলে নেটওয়ার্ক ওভারফিটিং করছে।',
    ins_hint: 'এগুলো এই নিউরনের এখনকার ওয়েট আর বায়াস। শেখার সময় এগুলো বদলাতে দেখুন।',
    ins_prev: 'h₁, h₂… হলো আগের লেয়ারের নিউরন।',
    ins_input: 'ইনপুটের কোনো ওয়েট নেই। এটি শুধু নিজের মান পরের লেয়ারে পাঠিয়ে দেয়।',
    col_inputs: 'ইনপুট',
    col_hidden: 'হিডেন {n}',
    col_output: 'আউটপুট',
    node_input: 'ইনপুট {name}',
    node_hidden: 'হিডেন লেয়ার {l}-এর নিউরন {n}',
    node_output: 'আউটপুট নিউরন',
    preview_input: 'ইনপুট {name} দেখানো হচ্ছে',
    preview_hidden: 'হিডেন লেয়ার {l}-এর নিউরন {n} দেখানো হচ্ছে',
    show_output: 'আউটপুট দেখান',
    coach_start: 'নেটওয়ার্ককে শেখাতে "শেখান" চাপুন। পেছনের রং প্রতিটি জায়গার জন্য তার অনুমান দেখায়।',
    coach_training: 'শিখছে… লস কমতে আর রংগুলো থিতু হতে দেখুন।',
    coach_paused: 'থামানো আছে। একবারে এক এপক শেখাতে "এক ধাপ" চাপুন।',
    coach_line: 'হিডেন লেয়ার ছাড়া নেটওয়ার্ক শুধু একটি সরলরেখা আঁকতে পারে, আর এখানে তা যথেষ্ট নয়। একটি হিডেন লেয়ার যোগ করুন!',
    coach_linear: 'লিনিয়ার অ্যাক্টিভেশনে অনেক লেয়ারও একটি সরলরেখার মতোই কাজ করে। tanh বা ReLU চেষ্টা করুন।',
    coach_overfit: 'ট্রেনিং লস কম কিন্তু টেস্ট লস বেশি: নেটওয়ার্ক ট্রেনিং বিন্দুগুলো মুখস্থ করছে। একে ওভারফিটিং বলে।',
    coach_great: 'শিখে গেছে! {acc}% টেস্ট বিন্দু সঠিক দিকে আছে।',
    coach_great_draw: 'শিখে গেছে! আপনার {acc}% বিন্দু সঠিক দিকে আছে।',
    coach_slow: 'খুব ধীরে শিখছে? লার্নিং রেট খুব ছোট, তাই প্রতিটি ধাপও ছোট। বড় রেট চেষ্টা করুন।',
    coach_stuck: 'আটকে গেছে? নতুন র‍্যান্ডম ওয়েটের জন্য রিসেট চাপুন, বা নেটওয়ার্ক বদলান।',
    coach_explode: 'ওহো! লার্নিং রেট খুব বড় বলে ওয়েটগুলো বেসামাল হয়ে গেছে। ছোট রেট বাছুন।',
    coach_need_points: 'ছবিতে কিছু কমলা আর কিছু নীল বিন্দু যোগ করুন।',
    challenges: 'চ্যালেঞ্জ',
    challenges_intro: 'আগে অনুমান করুন, তারপর "চেষ্টা করুন" চেপে শেখান। আপনার অনুমান কি ঠিক হল?',
    try_it: 'চেষ্টা করুন',
    notice: 'কী লক্ষ করবেন',
    loaded: 'চ্যালেঞ্জ {n} তৈরি। "শেখান" চাপুন!',
    print_ws: 'ওয়ার্কশিট প্রিন্ট করুন',
    ws_title: 'ওয়ার্কশিট',
    ws_name: 'নাম',
    ws_class: 'শ্রেণি',
    ws_date: 'তারিখ',
    ws_guess: 'আমার অনুমান:',
    ws_saw: 'কী হল, আর কেন:',
    explain: 'ভেতরে কী হচ্ছে?',
    help_title: 'কীভাবে ব্যবহার করবেন / ক্লাসের জন্য আইডিয়া',
    tip1: '<b>শেখান</b> (বা <kbd>স্পেসবার</kbd>) চাপুন আর নেটওয়ার্ক শেখার সময় রং বদলাতে দেখুন। <b>এক ধাপ</b> শুধু এক এপক শেখায়, তাই ধীরে ধীরে এগোতে পারেন।',
    tip2: 'ডেটাসেট, হিডেন লেয়ারের সংখ্যা আর নিউরন বদলান। নেটওয়ার্ক বদলালেই সেটা নতুন র‍্যান্ডম ওয়েট নিয়ে আবার শুরু হয়। <b>রিসেট</b>-ও একই কাজ করে।',
    tip3: '<b>নেটওয়ার্কের ভেতরে</b> অংশের ছোট ঘরগুলোতে ট্যাপ করে দেখুন প্রতিটি নিউরন কী শিখেছে। পরের লেয়ারের নিউরনরা সহজ আকার মিলিয়ে জটিল আকার বানায়।',
    tip4: '<b>নিজে আঁকুন</b> বাছুন, একটি রং নিন আর ছবিতে ট্যাপ করে নিজের ধাঁধা বানান। এমন ধাঁধা বানাতে পারবেন যা নেটওয়ার্ক শিখতে পারবে না?',
    tip5: '<b>ক্লাসের কাজ:</b> প্রতিটি চ্যালেঞ্জের আগে পুরো ক্লাস ভোট দিক: "এটা কি শিখতে পারবে?" তারপর স্মার্টবোর্ডে একসাথে "শেখান" চাপুন আর কেন এমন হল তা আলোচনা করুন। অনুমান লিখে রাখতে ওয়ার্কশিট প্রিন্ট করুন।',
    tip6: 'প্রজেক্টরে <b>পূর্ণ পর্দা</b> ব্যবহার করুন। <b>এই সেটআপ শেয়ার করুন</b> ছাত্রছাত্রীদের পাঠানোর জন্য একটি লিংক বানায়। সবকিছু এই ডিভাইসেই চলে আর ইন্টারনেট ছাড়াও কাজ করে।'
  },
  mr: {
    app_title: 'न्यूरल नेटवर्क खेळघर',
    intro: 'एक छोटे न्यूरल नेटवर्क नारंगी आणि निळे ठिपके वेगळे करायला कसे शिकते ते पाहा. त्याचे लेयर, न्यूरॉन आणि सेटिंग बदलून मशीन उदाहरणांतून कसे शिकते ते समजून घ्या.',
    train: 'शिकवा',
    step: 'एक पाऊल',
    step_title: 'एका एपॉकसाठी शिकवा (सर्व ट्रेनिंग ठिपक्यांवरून एक पूर्ण फेरी)',
    reset_title: 'नवीन रँडम वेटसह पुन्हा शिकायला सुरुवात करा',
    epoch: 'एपॉक',
    speed: 'वेग',
    speed_slow: 'हळू',
    speed_normal: 'नेहमीचा',
    speed_fast: 'जलद',
    data: 'डेटा',
    dataset: 'डेटासेट निवडा',
    ds_blobs: 'दोन पुंजके',
    ds_circle: 'वर्तुळ',
    ds_xor: 'XOR',
    ds_spiral: 'सर्पिल',
    ds_draw: 'स्वतः काढा',
    draw_hint: 'एक रंग निवडा, मग चित्रावर टॅप करा किंवा बोट फिरवून ठिपके जोडा. तुमचे सगळे ठिपके ट्रेनिंगसाठी वापरले जातात.',
    tool_orange: 'नारंगी',
    tool_blue: 'निळा',
    tool_erase: 'खोडरबर',
    clear_points: 'ठिपके पुसा',
    confirm_clear: 'तुम्ही काढलेले सगळे ठिपके काढून टाकायचे?',
    too_many: 'तुम्ही जास्तीत जास्त {n} ठिपके काढू शकता.',
    points_n: 'ठिपके: {n}',
    noise: 'गोंगाट (नॉइज): {n}%',
    noise_hint: 'जास्त गोंगाट म्हणजे जास्त विस्कळीत, मिसळलेले ठिपके.',
    split: 'ट्रेनिंग डेटा: {n}%',
    split_hint: 'उरलेले {n}% ठिपके बाजूला ठेवले जातात, म्हणजे नेटवर्कने कधीच न पाहिलेल्या ठिपक्यांवर त्याची परीक्षा घेता येते.',
    new_data: 'नवीन डेटा',
    show_test: 'टेस्ट ठिपके दाखवा',
    sharp: 'स्पष्ट सीमारेषा',
    network: 'नेटवर्क',
    inputs: 'इनपुट (फीचर)',
    inputs_hint: 'जास्त इनपुटमुळे नेटवर्कला जास्त सुगावे मिळतात.',
    need_input: 'किमान एक इनपुट ठेवावा लागतो.',
    hidden_layers: 'हिडन लेयर',
    layer_n: 'लेयर {n}',
    neurons: 'न्यूरॉन',
    add_layer: 'एक हिडन लेयर जोडा',
    remove_layer: 'एक हिडन लेयर काढा',
    add_neuron: 'लेयर {n} मध्ये एक न्यूरॉन जोडा',
    remove_neuron: 'लेयर {n} मधून एक न्यूरॉन काढा',
    no_hidden: 'हिडन लेयर नाही: संपूर्ण नेटवर्क फक्त एक न्यूरॉन आहे.',
    activation: 'ॲक्टिव्हेशन',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'सिग्मॉइड',
    act_linear: 'लिनियर (काहीच नाही)',
    lr: 'लर्निंग रेट',
    share_setup: 'हा सेटअप शेअर करा',
    defaults: 'मूळ सेटिंग परत आणा',
    inside: 'नेटवर्कच्या आत',
    inside_hint: 'प्रत्येक चौकोन दाखवतो की एक न्यूरॉन संपूर्ण चित्रात काय "पाहतो". मोठे पाहण्यासाठी चौकोनावर टॅप करा.',
    w_pos: 'पॉझिटिव्ह वेट',
    w_neg: 'निगेटिव्ह वेट',
    w_thick: 'जाड रेषा = जास्त ताकदीचा वेट',
    output: 'आउटपुट',
    output_hint: 'पार्श्वभूमीचा रंग = प्रत्येक जागेसाठी नेटवर्कचा अंदाज. गडद रंग = जास्त खात्री.',
    canvas_label: 'ठिपके आणि नेटवर्कच्या अंदाजांचे चित्र',
    canvas_empty: 'ठिपके जोडण्यासाठी इथे टॅप करा',
    train_loss: 'ट्रेनिंग लॉस',
    test_loss: 'टेस्ट लॉस',
    train_acc: 'ट्रेनिंग अचूकता',
    test_acc: 'टेस्ट अचूकता',
    loss_chart: 'वेळेनुसार लॉस',
    chart_label: 'प्रत्येक एपॉकनंतरच्या ट्रेनिंग लॉस आणि टेस्ट लॉसचा तक्ता',
    legend_train: 'ट्रेनिंग',
    legend_test: 'टेस्ट',
    chart_hint: 'जितका कमी तितका चांगला. ट्रेनिंगची रेषा खाली जात असताना टेस्टची रेषा वर जात असेल, तर नेटवर्क ओव्हरफिटिंग करत आहे.',
    ins_hint: 'हे या न्यूरॉनचे आत्ताचे वेट आणि बायस आहेत. शिकताना ते बदलताना पाहा.',
    ins_prev: 'h₁, h₂… म्हणजे आधीच्या लेयरमधील न्यूरॉन.',
    ins_input: 'इनपुटला वेट नसतो. तो फक्त आपली किंमत पुढच्या लेयरकडे देतो.',
    col_inputs: 'इनपुट',
    col_hidden: 'हिडन {n}',
    col_output: 'आउटपुट',
    node_input: 'इनपुट {name}',
    node_hidden: 'हिडन लेयर {l} मधील न्यूरॉन {n}',
    node_output: 'आउटपुट न्यूरॉन',
    preview_input: 'इनपुट {name} दाखवत आहे',
    preview_hidden: 'हिडन लेयर {l} मधील न्यूरॉन {n} दाखवत आहे',
    show_output: 'आउटपुट दाखवा',
    coach_start: 'नेटवर्कला शिकवण्यासाठी "शिकवा" दाबा. पार्श्वभूमी प्रत्येक जागेसाठी त्याचा अंदाज दाखवते.',
    coach_training: 'शिकत आहे… लॉस कमी होताना आणि रंग स्थिर होताना पाहा.',
    coach_paused: 'थांबवले आहे. एकेक एपॉक शिकवण्यासाठी "एक पाऊल" दाबा.',
    coach_line: 'हिडन लेयरशिवाय नेटवर्क फक्त एक सरळ रेषा काढू शकते, आणि इथे ती पुरेशी नाही. एक हिडन लेयर जोडा!',
    coach_linear: 'लिनियर ॲक्टिव्हेशनमुळे अनेक लेयरसुद्धा एका सरळ रेषेसारखेच वागतात. tanh किंवा ReLU वापरून पाहा.',
    coach_overfit: 'ट्रेनिंग लॉस कमी आहे पण टेस्ट लॉस जास्त: नेटवर्क ट्रेनिंग ठिपके पाठ करत आहे. याला ओव्हरफिटिंग म्हणतात.',
    coach_great: 'शिकले! {acc}% टेस्ट ठिपके योग्य बाजूला आहेत.',
    coach_great_draw: 'शिकले! तुमचे {acc}% ठिपके योग्य बाजूला आहेत.',
    coach_slow: 'खूप हळू शिकत आहे? लर्निंग रेट अगदी लहान आहे, म्हणून प्रत्येक पाऊलही लहान आहे. मोठा रेट वापरून पाहा.',
    coach_stuck: 'अडकले? नवीन रँडम वेटसाठी रीसेट दाबा, किंवा नेटवर्क बदला.',
    coach_explode: 'अरेरे! लर्निंग रेट खूप मोठा असल्याने वेट बेलगाम झाले. लहान रेट निवडा.',
    coach_need_points: 'चित्रावर काही नारंगी आणि काही निळे ठिपके जोडा.',
    challenges: 'आव्हाने',
    challenges_intro: 'आधी अंदाज लावा, मग "करून पाहा" दाबून शिकवा. तुमचा अंदाज बरोबर ठरला का?',
    try_it: 'करून पाहा',
    notice: 'कशाकडे लक्ष द्यायचे',
    loaded: 'आव्हान {n} तयार आहे. "शिकवा" दाबा!',
    print_ws: 'वर्कशीट प्रिंट करा',
    ws_title: 'वर्कशीट',
    ws_name: 'नाव',
    ws_class: 'इयत्ता',
    ws_date: 'तारीख',
    ws_guess: 'माझा अंदाज:',
    ws_saw: 'काय झाले, आणि का:',
    explain: 'आत काय घडत आहे?',
    help_title: 'कसे वापरायचे / वर्गासाठी कल्पना',
    tip1: '<b>शिकवा</b> (किंवा <kbd>स्पेसबार</kbd>) दाबा आणि नेटवर्क शिकत असताना रंग बदलताना पाहा. <b>एक पाऊल</b> फक्त एक एपॉक शिकवते, म्हणजे तुम्ही सावकाश पुढे जाऊ शकता.',
    tip2: 'डेटासेट, हिडन लेयरची संख्या आणि न्यूरॉन बदला. नेटवर्क बदलताच ते नवीन रँडम वेटसह पुन्हा सुरू होते. <b>रीसेट</b> सुद्धा हेच करते.',
    tip3: '<b>नेटवर्कच्या आत</b> मधील छोट्या चौकोनांवर टॅप करून प्रत्येक न्यूरॉनने काय शिकले ते पाहा. पुढच्या लेयरमधील न्यूरॉन साधे आकार एकत्र करून गुंतागुंतीचे आकार बनवतात.',
    tip4: '<b>स्वतः काढा</b> निवडा, रंग निवडा आणि चित्रावर टॅप करून तुमचे स्वतःचे कोडे बनवा. नेटवर्कला शिकता येणार नाही असे कोडे तुम्ही बनवू शकता का?',
    tip5: '<b>वर्गातील उपक्रम:</b> प्रत्येक आव्हानापूर्वी वर्गाला मत द्यायला सांगा: "हे शिकेल का?" मग स्मार्टबोर्डवर सगळे मिळून "शिकवा" दाबा आणि असे का झाले यावर चर्चा करा. अंदाज लिहिण्यासाठी वर्कशीट प्रिंट करा.',
    tip6: 'प्रोजेक्टरवर <b>पूर्ण स्क्रीन</b> वापरा. <b>हा सेटअप शेअर करा</b> ने विद्यार्थ्यांना पाठवण्यासाठी लिंक तयार होते. सगळे याच डिव्हाइसवर चालते आणि इंटरनेटशिवायही काम करते.'
  },
  gu: {
    app_title: 'ન્યુરલ નેટવર્ક રમતઘર',
    intro: 'જુઓ કે એક નાનું ન્યુરલ નેટવર્ક નારંગી અને વાદળી ટપકાં અલગ કરતાં કેવી રીતે શીખે છે. તેના લેયર, ન્યુરોન અને સેટિંગ બદલીને સમજો કે મશીન ઉદાહરણોમાંથી કેવી રીતે શીખે છે.',
    train: 'શીખવો',
    step: 'એક પગલું',
    step_title: 'એક એપોક માટે શીખવો (બધાં ટ્રેનિંગ ટપકાં પર એક પૂરો ફેરો)',
    reset_title: 'નવા રેન્ડમ વેઇટ સાથે ફરી શીખવાનું શરૂ કરો',
    epoch: 'એપોક',
    speed: 'ઝડપ',
    speed_slow: 'ધીમી',
    speed_normal: 'સામાન્ય',
    speed_fast: 'ઝડપી',
    data: 'ડેટા',
    dataset: 'ડેટાસેટ પસંદ કરો',
    ds_blobs: 'બે ઝુંડ',
    ds_circle: 'વર્તુળ',
    ds_xor: 'XOR',
    ds_spiral: 'સર્પાકાર',
    ds_draw: 'જાતે દોરો',
    draw_hint: 'એક રંગ પસંદ કરો, પછી ચિત્ર પર ટૅપ કરો અથવા આંગળી ફેરવીને ટપકાં ઉમેરો. તમારાં બધાં ટપકાં ટ્રેનિંગ માટે વપરાય છે.',
    tool_orange: 'નારંગી',
    tool_blue: 'વાદળી',
    tool_erase: 'રબર',
    clear_points: 'ટપકાં ભૂંસો',
    confirm_clear: 'તમે દોરેલાં બધાં ટપકાં કાઢી નાખવાં છે?',
    too_many: 'તમે વધુમાં વધુ {n} ટપકાં દોરી શકો છો.',
    points_n: 'ટપકાં: {n}',
    noise: 'ઘોંઘાટ (નોઇઝ): {n}%',
    noise_hint: 'વધુ ઘોંઘાટ એટલે વધુ વેરવિખેર, ભળી ગયેલાં ટપકાં.',
    split: 'ટ્રેનિંગ ડેટા: {n}%',
    split_hint: 'બાકીનાં {n}% ટપકાં અલગ રાખવામાં આવે છે, જેથી નેટવર્કે ક્યારેય ન જોયેલાં ટપકાં પર તેની કસોટી થઈ શકે.',
    new_data: 'નવો ડેટા',
    show_test: 'ટેસ્ટ ટપકાં બતાવો',
    sharp: 'સ્પષ્ટ સીમારેખા',
    network: 'નેટવર્ક',
    inputs: 'ઇનપુટ (ફીચર)',
    inputs_hint: 'વધારાના ઇનપુટ નેટવર્કને વધારાની કડીઓ આપે છે.',
    need_input: 'ઓછામાં ઓછો એક ઇનપુટ રાખવો પડશે.',
    hidden_layers: 'હિડન લેયર',
    layer_n: 'લેયર {n}',
    neurons: 'ન્યુરોન',
    add_layer: 'એક હિડન લેયર ઉમેરો',
    remove_layer: 'એક હિડન લેયર કાઢો',
    add_neuron: 'લેયર {n}માં એક ન્યુરોન ઉમેરો',
    remove_neuron: 'લેયર {n}માંથી એક ન્યુરોન કાઢો',
    no_hidden: 'કોઈ હિડન લેયર નથી: આખું નેટવર્ક ફક્ત એક ન્યુરોન છે.',
    activation: 'ઍક્ટિવેશન',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'સિગ્મોઇડ',
    act_linear: 'લિનિયર (કંઈ નહીં)',
    lr: 'લર્નિંગ રેટ',
    share_setup: 'આ સેટઅપ શેર કરો',
    defaults: 'મૂળ સેટિંગ પાછાં લાવો',
    inside: 'નેટવર્કની અંદર',
    inside_hint: 'દરેક ખાનું બતાવે છે કે એક ન્યુરોન આખા ચિત્રમાં શું "જુએ" છે. મોટું જોવા માટે ખાના પર ટૅપ કરો.',
    w_pos: 'પૉઝિટિવ વેઇટ',
    w_neg: 'નેગેટિવ વેઇટ',
    w_thick: 'જાડી રેખા = વધુ મજબૂત વેઇટ',
    output: 'આઉટપુટ',
    output_hint: 'પૃષ્ઠભૂમિનો રંગ = દરેક જગ્યા માટે નેટવર્કનો અંદાજ. ઘેરો રંગ = વધુ ખાતરી.',
    canvas_label: 'ટપકાં અને નેટવર્કના અંદાજનું ચિત્ર',
    canvas_empty: 'ટપકાં ઉમેરવા અહીં ટૅપ કરો',
    train_loss: 'ટ્રેનિંગ લૉસ',
    test_loss: 'ટેસ્ટ લૉસ',
    train_acc: 'ટ્રેનિંગ ચોકસાઈ',
    test_acc: 'ટેસ્ટ ચોકસાઈ',
    loss_chart: 'સમય સાથે લૉસ',
    chart_label: 'દરેક એપોક પછી ટ્રેનિંગ લૉસ અને ટેસ્ટ લૉસનો ચાર્ટ',
    legend_train: 'ટ્રેનિંગ',
    legend_test: 'ટેસ્ટ',
    chart_hint: 'જેટલું ઓછું, એટલું સારું. ટ્રેનિંગની રેખા નીચે જાય પણ ટેસ્ટની રેખા ઉપર ચડે, તો નેટવર્ક ઓવરફિટિંગ કરી રહ્યું છે.',
    ins_hint: 'આ આ ન્યુરોનના અત્યારના વેઇટ અને બાયસ છે. શીખતી વખતે તેમને બદલાતા જુઓ.',
    ins_prev: 'h₁, h₂… એટલે પાછલા લેયરના ન્યુરોન.',
    ins_input: 'ઇનપુટને કોઈ વેઇટ હોતો નથી. તે ફક્ત પોતાની કિંમત પછીના લેયરને આપે છે.',
    col_inputs: 'ઇનપુટ',
    col_hidden: 'હિડન {n}',
    col_output: 'આઉટપુટ',
    node_input: 'ઇનપુટ {name}',
    node_hidden: 'હિડન લેયર {l}નો ન્યુરોન {n}',
    node_output: 'આઉટપુટ ન્યુરોન',
    preview_input: 'ઇનપુટ {name} બતાવી રહ્યા છીએ',
    preview_hidden: 'હિડન લેયર {l}નો ન્યુરોન {n} બતાવી રહ્યા છીએ',
    show_output: 'આઉટપુટ બતાવો',
    coach_start: 'નેટવર્કને શીખવવા "શીખવો" દબાવો. પૃષ્ઠભૂમિ દરેક જગ્યા માટે તેનો અંદાજ બતાવે છે.',
    coach_training: 'શીખી રહ્યું છે… લૉસ ઘટતો અને રંગો સ્થિર થતા જુઓ.',
    coach_paused: 'અટકાવ્યું છે. એક-એક એપોક શીખવવા "એક પગલું" દબાવો.',
    coach_line: 'હિડન લેયર વગર નેટવર્ક ફક્ત એક સીધી રેખા દોરી શકે છે, અને અહીં તે પૂરતી નથી. એક હિડન લેયર ઉમેરો!',
    coach_linear: 'લિનિયર ઍક્ટિવેશન સાથે ઘણા લેયર પણ એક સીધી રેખા જેવું જ કામ કરે છે. tanh કે ReLU અજમાવો.',
    coach_overfit: 'ટ્રેનિંગ લૉસ ઓછો છે પણ ટેસ્ટ લૉસ વધારે: નેટવર્ક ટ્રેનિંગ ટપકાં ગોખી રહ્યું છે. તેને ઓવરફિટિંગ કહેવાય.',
    coach_great: 'શીખી ગયું! {acc}% ટેસ્ટ ટપકાં સાચી બાજુએ છે.',
    coach_great_draw: 'શીખી ગયું! તમારાં {acc}% ટપકાં સાચી બાજુએ છે.',
    coach_slow: 'બહુ ધીમે શીખે છે? લર્નિંગ રેટ ખૂબ નાનો છે, એટલે દરેક પગલું પણ નાનું છે. મોટો રેટ અજમાવો.',
    coach_stuck: 'અટકી ગયું? નવા રેન્ડમ વેઇટ માટે રીસેટ દબાવો, અથવા નેટવર્ક બદલો.',
    coach_explode: 'અરે! લર્નિંગ રેટ બહુ મોટો હોવાથી વેઇટ બેકાબૂ થઈ ગયા. નાનો રેટ પસંદ કરો.',
    coach_need_points: 'ચિત્ર પર થોડાં નારંગી અને થોડાં વાદળી ટપકાં ઉમેરો.',
    challenges: 'પડકારો',
    challenges_intro: 'પહેલાં અંદાજ લગાવો, પછી "અજમાવો" દબાવીને શીખવો. તમારો અંદાજ સાચો પડ્યો?',
    try_it: 'અજમાવો',
    notice: 'શું ધ્યાનમાં લેવું',
    loaded: 'પડકાર {n} તૈયાર છે. "શીખવો" દબાવો!',
    print_ws: 'વર્કશીટ પ્રિન્ટ કરો',
    ws_title: 'વર્કશીટ',
    ws_name: 'નામ',
    ws_class: 'ધોરણ',
    ws_date: 'તારીખ',
    ws_guess: 'મારો અંદાજ:',
    ws_saw: 'શું થયું, અને કેમ:',
    explain: 'અંદર શું થઈ રહ્યું છે?',
    help_title: 'કેવી રીતે વાપરવું / વર્ગખંડ માટે વિચારો',
    tip1: '<b>શીખવો</b> (અથવા <kbd>સ્પેસબાર</kbd>) દબાવો અને નેટવર્ક શીખે તેમ રંગો બદલાતા જુઓ. <b>એક પગલું</b> ફક્ત એક એપોક શીખવે છે, જેથી તમે ધીમે ધીમે આગળ વધી શકો.',
    tip2: 'ડેટાસેટ, હિડન લેયરની સંખ્યા અને ન્યુરોન બદલો. નેટવર્ક બદલતાં જ તે નવા રેન્ડમ વેઇટ સાથે ફરી શરૂ થાય છે. <b>રીસેટ</b> પણ આ જ કરે છે.',
    tip3: '<b>નેટવર્કની અંદર</b> વિભાગનાં નાનાં ખાનાં પર ટૅપ કરીને જુઓ કે દરેક ન્યુરોન શું શીખ્યો. પછીના લેયરના ન્યુરોન સાદા આકારોને જોડીને જટિલ આકાર બનાવે છે.',
    tip4: '<b>જાતે દોરો</b> પસંદ કરો, રંગ પસંદ કરો અને ચિત્ર પર ટૅપ કરીને તમારો પોતાનો કોયડો બનાવો. શું તમે એવો કોયડો બનાવી શકો જે નેટવર્ક શીખી ન શકે?',
    tip5: '<b>વર્ગખંડ પ્રવૃત્તિ:</b> દરેક પડકાર પહેલાં આખો વર્ગ મત આપે: "શું તે શીખી શકશે?" પછી સ્માર્ટબોર્ડ પર સાથે મળીને "શીખવો" દબાવો અને આવું કેમ થયું તેની ચર્ચા કરો. અંદાજ લખવા માટે વર્કશીટ પ્રિન્ટ કરો.',
    tip6: 'પ્રોજેક્ટર પર <b>પૂર્ણ સ્ક્રીન</b> વાપરો. <b>આ સેટઅપ શેર કરો</b> વિદ્યાર્થીઓને મોકલવા માટે લિંક બનાવે છે. બધું આ જ ડિવાઇસ પર ચાલે છે અને ઇન્ટરનેટ વગર પણ કામ કરે છે.'
  },
  pa: {
    app_title: 'ਨਿਊਰਲ ਨੈੱਟਵਰਕ ਖੇਡ-ਮੈਦਾਨ',
    intro: 'ਦੇਖੋ ਕਿ ਇੱਕ ਛੋਟਾ ਜਿਹਾ ਨਿਊਰਲ ਨੈੱਟਵਰਕ ਸੰਤਰੀ ਅਤੇ ਨੀਲੇ ਬਿੰਦੂਆਂ ਨੂੰ ਵੱਖ ਕਰਨਾ ਕਿਵੇਂ ਸਿੱਖਦਾ ਹੈ। ਇਸ ਦੀਆਂ ਲੇਅਰਾਂ, ਨਿਊਰੋਨ ਅਤੇ ਸੈਟਿੰਗਾਂ ਬਦਲ ਕੇ ਸਮਝੋ ਕਿ ਮਸ਼ੀਨ ਉਦਾਹਰਨਾਂ ਤੋਂ ਕਿਵੇਂ ਸਿੱਖਦੀ ਹੈ।',
    train: 'ਸਿਖਾਓ',
    step: 'ਇੱਕ ਕਦਮ',
    step_title: 'ਇੱਕ ਐਪੋਕ ਲਈ ਸਿਖਾਓ (ਸਾਰੇ ਟ੍ਰੇਨਿੰਗ ਬਿੰਦੂਆਂ ਉੱਤੇ ਇੱਕ ਪੂਰਾ ਗੇੜਾ)',
    reset_title: 'ਨਵੇਂ ਰੈਂਡਮ ਵੇਟ ਨਾਲ ਮੁੜ ਸਿੱਖਣਾ ਸ਼ੁਰੂ ਕਰੋ',
    epoch: 'ਐਪੋਕ',
    speed: 'ਰਫ਼ਤਾਰ',
    speed_slow: 'ਹੌਲੀ',
    speed_normal: 'ਆਮ',
    speed_fast: 'ਤੇਜ਼',
    data: 'ਡਾਟਾ',
    dataset: 'ਡਾਟਾਸੈੱਟ ਚੁਣੋ',
    ds_blobs: 'ਦੋ ਝੁੰਡ',
    ds_circle: 'ਗੋਲਾ',
    ds_xor: 'XOR',
    ds_spiral: 'ਚੱਕਰਦਾਰ',
    ds_draw: 'ਆਪ ਬਣਾਓ',
    draw_hint: 'ਇੱਕ ਰੰਗ ਚੁਣੋ, ਫਿਰ ਤਸਵੀਰ ਉੱਤੇ ਟੈਪ ਕਰੋ ਜਾਂ ਉਂਗਲ ਘੁਮਾ ਕੇ ਬਿੰਦੂ ਜੋੜੋ। ਤੁਹਾਡੇ ਸਾਰੇ ਬਿੰਦੂ ਟ੍ਰੇਨਿੰਗ ਲਈ ਵਰਤੇ ਜਾਂਦੇ ਹਨ।',
    tool_orange: 'ਸੰਤਰੀ',
    tool_blue: 'ਨੀਲਾ',
    tool_erase: 'ਰਬੜ',
    clear_points: 'ਬਿੰਦੂ ਮਿਟਾਓ',
    confirm_clear: 'ਤੁਹਾਡੇ ਬਣਾਏ ਸਾਰੇ ਬਿੰਦੂ ਹਟਾ ਦੇਈਏ?',
    too_many: 'ਤੁਸੀਂ ਵੱਧ ਤੋਂ ਵੱਧ {n} ਬਿੰਦੂ ਬਣਾ ਸਕਦੇ ਹੋ।',
    points_n: 'ਬਿੰਦੂ: {n}',
    noise: 'ਸ਼ੋਰ (ਨੌਇਜ਼): {n}%',
    noise_hint: 'ਵੱਧ ਸ਼ੋਰ ਦਾ ਮਤਲਬ ਵੱਧ ਖਿੰਡੇ ਹੋਏ, ਰਲ਼ੇ-ਮਿਲ਼ੇ ਬਿੰਦੂ।',
    split: 'ਟ੍ਰੇਨਿੰਗ ਡਾਟਾ: {n}%',
    split_hint: 'ਬਾਕੀ {n}% ਬਿੰਦੂ ਵੱਖਰੇ ਰੱਖੇ ਜਾਂਦੇ ਹਨ, ਤਾਂ ਜੋ ਨੈੱਟਵਰਕ ਨੂੰ ਉਹਨਾਂ ਬਿੰਦੂਆਂ ਉੱਤੇ ਪਰਖਿਆ ਜਾ ਸਕੇ ਜੋ ਉਸ ਨੇ ਕਦੇ ਨਹੀਂ ਦੇਖੇ।',
    new_data: 'ਨਵਾਂ ਡਾਟਾ',
    show_test: 'ਟੈਸਟ ਬਿੰਦੂ ਦਿਖਾਓ',
    sharp: 'ਸਾਫ਼ ਹੱਦ-ਰੇਖਾ',
    network: 'ਨੈੱਟਵਰਕ',
    inputs: 'ਇਨਪੁਟ (ਫ਼ੀਚਰ)',
    inputs_hint: 'ਵਾਧੂ ਇਨਪੁਟ ਨੈੱਟਵਰਕ ਨੂੰ ਵਾਧੂ ਸੁਰਾਗ ਦਿੰਦੇ ਹਨ।',
    need_input: 'ਘੱਟੋ-ਘੱਟ ਇੱਕ ਇਨਪੁਟ ਰੱਖਣਾ ਜ਼ਰੂਰੀ ਹੈ।',
    hidden_layers: 'ਹਿਡਨ ਲੇਅਰਾਂ',
    layer_n: 'ਲੇਅਰ {n}',
    neurons: 'ਨਿਊਰੋਨ',
    add_layer: 'ਇੱਕ ਹਿਡਨ ਲੇਅਰ ਜੋੜੋ',
    remove_layer: 'ਇੱਕ ਹਿਡਨ ਲੇਅਰ ਹਟਾਓ',
    add_neuron: 'ਲੇਅਰ {n} ਵਿੱਚ ਇੱਕ ਨਿਊਰੋਨ ਜੋੜੋ',
    remove_neuron: 'ਲੇਅਰ {n} ਵਿੱਚੋਂ ਇੱਕ ਨਿਊਰੋਨ ਹਟਾਓ',
    no_hidden: 'ਕੋਈ ਹਿਡਨ ਲੇਅਰ ਨਹੀਂ: ਸਾਰਾ ਨੈੱਟਵਰਕ ਸਿਰਫ਼ ਇੱਕ ਨਿਊਰੋਨ ਹੈ।',
    activation: 'ਐਕਟੀਵੇਸ਼ਨ',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'ਸਿਗਮੌਇਡ',
    act_linear: 'ਲੀਨੀਅਰ (ਕੋਈ ਨਹੀਂ)',
    lr: 'ਲਰਨਿੰਗ ਰੇਟ',
    share_setup: 'ਇਹ ਸੈੱਟਅੱਪ ਸਾਂਝਾ ਕਰੋ',
    defaults: 'ਸ਼ੁਰੂਆਤੀ ਸੈਟਿੰਗਾਂ ਵਾਪਸ ਲਿਆਓ',
    inside: 'ਨੈੱਟਵਰਕ ਦੇ ਅੰਦਰ',
    inside_hint: 'ਹਰ ਖ਼ਾਨਾ ਦਿਖਾਉਂਦਾ ਹੈ ਕਿ ਇੱਕ ਨਿਊਰੋਨ ਪੂਰੀ ਤਸਵੀਰ ਵਿੱਚ ਕੀ "ਦੇਖਦਾ" ਹੈ। ਵੱਡਾ ਦੇਖਣ ਲਈ ਕਿਸੇ ਖ਼ਾਨੇ ਉੱਤੇ ਟੈਪ ਕਰੋ।',
    w_pos: 'ਪੌਜ਼ੀਟਿਵ ਵੇਟ',
    w_neg: 'ਨੈਗੇਟਿਵ ਵੇਟ',
    w_thick: 'ਮੋਟੀ ਲਾਈਨ = ਵੱਧ ਤਾਕਤਵਰ ਵੇਟ',
    output: 'ਆਉਟਪੁਟ',
    output_hint: 'ਪਿਛੋਕੜ ਦਾ ਰੰਗ = ਹਰ ਥਾਂ ਲਈ ਨੈੱਟਵਰਕ ਦਾ ਅੰਦਾਜ਼ਾ। ਗੂੜ੍ਹਾ ਰੰਗ = ਵੱਧ ਪੱਕਾ।',
    canvas_label: 'ਬਿੰਦੂਆਂ ਅਤੇ ਨੈੱਟਵਰਕ ਦੇ ਅੰਦਾਜ਼ਿਆਂ ਦੀ ਤਸਵੀਰ',
    canvas_empty: 'ਬਿੰਦੂ ਜੋੜਨ ਲਈ ਇੱਥੇ ਟੈਪ ਕਰੋ',
    train_loss: 'ਟ੍ਰੇਨਿੰਗ ਲੌਸ',
    test_loss: 'ਟੈਸਟ ਲੌਸ',
    train_acc: 'ਟ੍ਰੇਨਿੰਗ ਸ਼ੁੱਧਤਾ',
    test_acc: 'ਟੈਸਟ ਸ਼ੁੱਧਤਾ',
    loss_chart: 'ਸਮੇਂ ਨਾਲ ਲੌਸ',
    chart_label: 'ਹਰ ਐਪੋਕ ਤੋਂ ਬਾਅਦ ਟ੍ਰੇਨਿੰਗ ਲੌਸ ਅਤੇ ਟੈਸਟ ਲੌਸ ਦਾ ਚਾਰਟ',
    legend_train: 'ਟ੍ਰੇਨਿੰਗ',
    legend_test: 'ਟੈਸਟ',
    chart_hint: 'ਜਿੰਨਾ ਘੱਟ, ਓਨਾ ਵਧੀਆ। ਜੇ ਟ੍ਰੇਨਿੰਗ ਵਾਲੀ ਲਾਈਨ ਹੇਠਾਂ ਜਾਵੇ ਪਰ ਟੈਸਟ ਵਾਲੀ ਲਾਈਨ ਉੱਪਰ ਚੜ੍ਹੇ, ਤਾਂ ਨੈੱਟਵਰਕ ਓਵਰਫ਼ਿਟਿੰਗ ਕਰ ਰਿਹਾ ਹੈ।',
    ins_hint: 'ਇਹ ਇਸ ਨਿਊਰੋਨ ਦੇ ਇਸ ਵੇਲੇ ਦੇ ਵੇਟ ਅਤੇ ਬਾਇਸ ਹਨ। ਸਿੱਖਦੇ ਸਮੇਂ ਇਹਨਾਂ ਨੂੰ ਬਦਲਦੇ ਦੇਖੋ।',
    ins_prev: 'h₁, h₂… ਪਿਛਲੀ ਲੇਅਰ ਦੇ ਨਿਊਰੋਨ ਹਨ।',
    ins_input: 'ਇਨਪੁਟ ਦਾ ਕੋਈ ਵੇਟ ਨਹੀਂ ਹੁੰਦਾ। ਇਹ ਸਿਰਫ਼ ਆਪਣਾ ਮੁੱਲ ਅਗਲੀ ਲੇਅਰ ਨੂੰ ਦੇ ਦਿੰਦਾ ਹੈ।',
    col_inputs: 'ਇਨਪੁਟ',
    col_hidden: 'ਹਿਡਨ {n}',
    col_output: 'ਆਉਟਪੁਟ',
    node_input: 'ਇਨਪੁਟ {name}',
    node_hidden: 'ਹਿਡਨ ਲੇਅਰ {l} ਦਾ ਨਿਊਰੋਨ {n}',
    node_output: 'ਆਉਟਪੁਟ ਨਿਊਰੋਨ',
    preview_input: 'ਇਨਪੁਟ {name} ਦਿਖਾਇਆ ਜਾ ਰਿਹਾ ਹੈ',
    preview_hidden: 'ਹਿਡਨ ਲੇਅਰ {l} ਦਾ ਨਿਊਰੋਨ {n} ਦਿਖਾਇਆ ਜਾ ਰਿਹਾ ਹੈ',
    show_output: 'ਆਉਟਪੁਟ ਦਿਖਾਓ',
    coach_start: 'ਨੈੱਟਵਰਕ ਨੂੰ ਸਿਖਾਉਣ ਲਈ "ਸਿਖਾਓ" ਦਬਾਓ। ਪਿਛੋਕੜ ਹਰ ਥਾਂ ਲਈ ਉਸ ਦਾ ਅੰਦਾਜ਼ਾ ਦਿਖਾਉਂਦਾ ਹੈ।',
    coach_training: 'ਸਿੱਖ ਰਿਹਾ ਹੈ… ਲੌਸ ਘਟਦਾ ਅਤੇ ਰੰਗ ਟਿਕਦੇ ਦੇਖੋ।',
    coach_paused: 'ਰੁਕਿਆ ਹੋਇਆ ਹੈ। ਇੱਕ-ਇੱਕ ਐਪੋਕ ਸਿਖਾਉਣ ਲਈ "ਇੱਕ ਕਦਮ" ਦਬਾਓ।',
    coach_line: 'ਹਿਡਨ ਲੇਅਰ ਤੋਂ ਬਿਨਾਂ ਨੈੱਟਵਰਕ ਸਿਰਫ਼ ਇੱਕ ਸਿੱਧੀ ਲਕੀਰ ਖਿੱਚ ਸਕਦਾ ਹੈ, ਅਤੇ ਇੱਥੇ ਉਹ ਕਾਫ਼ੀ ਨਹੀਂ। ਇੱਕ ਹਿਡਨ ਲੇਅਰ ਜੋੜੋ!',
    coach_linear: 'ਲੀਨੀਅਰ ਐਕਟੀਵੇਸ਼ਨ ਨਾਲ ਕਈ ਲੇਅਰਾਂ ਵੀ ਇੱਕ ਸਿੱਧੀ ਲਕੀਰ ਵਾਂਗ ਹੀ ਕੰਮ ਕਰਦੀਆਂ ਹਨ। tanh ਜਾਂ ReLU ਵਰਤ ਕੇ ਦੇਖੋ।',
    coach_overfit: 'ਟ੍ਰੇਨਿੰਗ ਲੌਸ ਘੱਟ ਹੈ ਪਰ ਟੈਸਟ ਲੌਸ ਵੱਧ: ਨੈੱਟਵਰਕ ਟ੍ਰੇਨਿੰਗ ਬਿੰਦੂਆਂ ਨੂੰ ਰੱਟ ਰਿਹਾ ਹੈ। ਇਸ ਨੂੰ ਓਵਰਫ਼ਿਟਿੰਗ ਕਹਿੰਦੇ ਹਨ।',
    coach_great: 'ਸਿੱਖ ਲਿਆ! {acc}% ਟੈਸਟ ਬਿੰਦੂ ਸਹੀ ਪਾਸੇ ਹਨ।',
    coach_great_draw: 'ਸਿੱਖ ਲਿਆ! ਤੁਹਾਡੇ {acc}% ਬਿੰਦੂ ਸਹੀ ਪਾਸੇ ਹਨ।',
    coach_slow: 'ਬਹੁਤ ਹੌਲੀ ਸਿੱਖ ਰਿਹਾ ਹੈ? ਲਰਨਿੰਗ ਰੇਟ ਬਹੁਤ ਛੋਟਾ ਹੈ, ਇਸ ਲਈ ਹਰ ਕਦਮ ਵੀ ਛੋਟਾ ਹੈ। ਵੱਡਾ ਰੇਟ ਵਰਤ ਕੇ ਦੇਖੋ।',
    coach_stuck: 'ਅਟਕ ਗਿਆ? ਨਵੇਂ ਰੈਂਡਮ ਵੇਟ ਲਈ ਰੀਸੈੱਟ ਦਬਾਓ, ਜਾਂ ਨੈੱਟਵਰਕ ਬਦਲੋ।',
    coach_explode: 'ਓਹੋ! ਲਰਨਿੰਗ ਰੇਟ ਬਹੁਤ ਵੱਡਾ ਹੋਣ ਕਰਕੇ ਵੇਟ ਬੇਕਾਬੂ ਹੋ ਗਏ। ਛੋਟਾ ਰੇਟ ਚੁਣੋ।',
    coach_need_points: 'ਤਸਵੀਰ ਉੱਤੇ ਕੁਝ ਸੰਤਰੀ ਅਤੇ ਕੁਝ ਨੀਲੇ ਬਿੰਦੂ ਜੋੜੋ।',
    challenges: 'ਚੁਣੌਤੀਆਂ',
    challenges_intro: 'ਪਹਿਲਾਂ ਅੰਦਾਜ਼ਾ ਲਾਓ, ਫਿਰ "ਅਜ਼ਮਾਓ" ਦਬਾ ਕੇ ਸਿਖਾਓ। ਕੀ ਤੁਹਾਡਾ ਅੰਦਾਜ਼ਾ ਸਹੀ ਨਿਕਲਿਆ?',
    try_it: 'ਅਜ਼ਮਾਓ',
    notice: 'ਕਿਸ ਗੱਲ ਵੱਲ ਧਿਆਨ ਦਿਓ',
    loaded: 'ਚੁਣੌਤੀ {n} ਤਿਆਰ ਹੈ। "ਸਿਖਾਓ" ਦਬਾਓ!',
    print_ws: 'ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ',
    ws_title: 'ਵਰਕਸ਼ੀਟ',
    ws_name: 'ਨਾਮ',
    ws_class: 'ਜਮਾਤ',
    ws_date: 'ਤਾਰੀਖ਼',
    ws_guess: 'ਮੇਰਾ ਅੰਦਾਜ਼ਾ:',
    ws_saw: 'ਕੀ ਹੋਇਆ, ਅਤੇ ਕਿਉਂ:',
    explain: 'ਅੰਦਰ ਕੀ ਹੋ ਰਿਹਾ ਹੈ?',
    help_title: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ / ਜਮਾਤ ਲਈ ਸੁਝਾਅ',
    tip1: '<b>ਸਿਖਾਓ</b> (ਜਾਂ <kbd>ਸਪੇਸਬਾਰ</kbd>) ਦਬਾਓ ਅਤੇ ਨੈੱਟਵਰਕ ਦੇ ਸਿੱਖਦੇ ਸਮੇਂ ਰੰਗ ਬਦਲਦੇ ਦੇਖੋ। <b>ਇੱਕ ਕਦਮ</b> ਸਿਰਫ਼ ਇੱਕ ਐਪੋਕ ਸਿਖਾਉਂਦਾ ਹੈ, ਤਾਂ ਜੋ ਤੁਸੀਂ ਹੌਲੀ-ਹੌਲੀ ਚੱਲ ਸਕੋ।',
    tip2: 'ਡਾਟਾਸੈੱਟ, ਹਿਡਨ ਲੇਅਰਾਂ ਦੀ ਗਿਣਤੀ ਅਤੇ ਨਿਊਰੋਨ ਬਦਲੋ। ਨੈੱਟਵਰਕ ਬਦਲਦੇ ਹੀ ਉਹ ਨਵੇਂ ਰੈਂਡਮ ਵੇਟ ਨਾਲ ਮੁੜ ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ। <b>ਰੀਸੈੱਟ</b> ਵੀ ਇਹੀ ਕਰਦਾ ਹੈ।',
    tip3: '<b>ਨੈੱਟਵਰਕ ਦੇ ਅੰਦਰ</b> ਵਾਲੇ ਛੋਟੇ ਖ਼ਾਨਿਆਂ ਉੱਤੇ ਟੈਪ ਕਰਕੇ ਦੇਖੋ ਕਿ ਹਰ ਨਿਊਰੋਨ ਨੇ ਕੀ ਸਿੱਖਿਆ। ਅਗਲੀਆਂ ਲੇਅਰਾਂ ਦੇ ਨਿਊਰੋਨ ਸੌਖੀਆਂ ਸ਼ਕਲਾਂ ਨੂੰ ਜੋੜ ਕੇ ਔਖੀਆਂ ਸ਼ਕਲਾਂ ਬਣਾਉਂਦੇ ਹਨ।',
    tip4: '<b>ਆਪ ਬਣਾਓ</b> ਚੁਣੋ, ਰੰਗ ਚੁਣੋ ਅਤੇ ਤਸਵੀਰ ਉੱਤੇ ਟੈਪ ਕਰਕੇ ਆਪਣੀ ਬੁਝਾਰਤ ਬਣਾਓ। ਕੀ ਤੁਸੀਂ ਅਜਿਹੀ ਬੁਝਾਰਤ ਬਣਾ ਸਕਦੇ ਹੋ ਜੋ ਨੈੱਟਵਰਕ ਨਾ ਸਿੱਖ ਸਕੇ?',
    tip5: '<b>ਜਮਾਤ ਲਈ ਗਤੀਵਿਧੀ:</b> ਹਰ ਚੁਣੌਤੀ ਤੋਂ ਪਹਿਲਾਂ ਸਾਰੀ ਜਮਾਤ ਵੋਟ ਪਾਵੇ: "ਕੀ ਇਹ ਸਿੱਖ ਸਕੇਗਾ?" ਫਿਰ ਸਮਾਰਟਬੋਰਡ ਉੱਤੇ ਇਕੱਠੇ "ਸਿਖਾਓ" ਦਬਾਓ ਅਤੇ ਚਰਚਾ ਕਰੋ ਕਿ ਅਜਿਹਾ ਕਿਉਂ ਹੋਇਆ। ਅੰਦਾਜ਼ੇ ਲਿਖਣ ਲਈ ਵਰਕਸ਼ੀਟ ਪ੍ਰਿੰਟ ਕਰੋ।',
    tip6: 'ਪ੍ਰੋਜੈਕਟਰ ਉੱਤੇ <b>ਪੂਰੀ ਸਕ੍ਰੀਨ</b> ਵਰਤੋ। <b>ਇਹ ਸੈੱਟਅੱਪ ਸਾਂਝਾ ਕਰੋ</b> ਨਾਲ ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਭੇਜਣ ਲਈ ਲਿੰਕ ਬਣਦਾ ਹੈ। ਸਭ ਕੁਝ ਇਸੇ ਡਿਵਾਈਸ ਉੱਤੇ ਚੱਲਦਾ ਹੈ ਅਤੇ ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਵੀ ਕੰਮ ਕਰਦਾ ਹੈ।'
  },
  or: {
    app_title: 'ନ୍ୟୁରାଲ ନେଟୱାର୍କ ଖେଳଘର',
    intro: 'ଦେଖନ୍ତୁ, ଏକ ଛୋଟ ନ୍ୟୁରାଲ ନେଟୱାର୍କ କିପରି କମଳା ଓ ନୀଳ ବିନ୍ଦୁକୁ ଅଲଗା କରିବା ଶିଖେ। ଏହାର ଲେୟର, ନ୍ୟୁରନ୍ ଓ ସେଟିଂ ବଦଳାଇ ବୁଝନ୍ତୁ ମେସିନ୍ ଉଦାହରଣରୁ କିପରି ଶିଖେ।',
    train: 'ଶିଖାନ୍ତୁ',
    step: 'ଗୋଟିଏ ପାଦ',
    step_title: 'ଗୋଟିଏ ଏପକ୍ ପାଇଁ ଶିଖାନ୍ତୁ (ସମସ୍ତ ଟ୍ରେନିଂ ବିନ୍ଦୁ ଉପରେ ଗୋଟିଏ ପୂରା ପରିକ୍ରମା)',
    reset_title: 'ନୂଆ ରାଣ୍ଡମ ୱେଟ୍ ସହ ପୁଣି ଶିଖିବା ଆରମ୍ଭ କରନ୍ତୁ',
    epoch: 'ଏପକ୍',
    speed: 'ଗତି',
    speed_slow: 'ଧୀର',
    speed_normal: 'ସାଧାରଣ',
    speed_fast: 'ଦ୍ରୁତ',
    data: 'ଡାଟା',
    dataset: 'ଡାଟାସେଟ୍ ବାଛନ୍ତୁ',
    ds_blobs: 'ଦୁଇଟି ଗୁଚ୍ଛ',
    ds_circle: 'ବୃତ୍ତ',
    ds_xor: 'XOR',
    ds_spiral: 'ସର୍ପିଳ',
    ds_draw: 'ନିଜେ ଆଙ୍କନ୍ତୁ',
    draw_hint: 'ଗୋଟିଏ ରଙ୍ଗ ବାଛନ୍ତୁ, ତା’ପରେ ଚିତ୍ର ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ ବା ଆଙ୍ଗୁଠି ଟାଣି ବିନ୍ଦୁ ଯୋଡ଼ନ୍ତୁ। ଆପଣଙ୍କ ସବୁ ବିନ୍ଦୁ ଟ୍ରେନିଂ ପାଇଁ ବ୍ୟବହାର ହୁଏ।',
    tool_orange: 'କମଳା',
    tool_blue: 'ନୀଳ',
    tool_erase: 'ରବର',
    clear_points: 'ବିନ୍ଦୁ ଲିଭାନ୍ତୁ',
    confirm_clear: 'ଆପଣ ଆଙ୍କିଥିବା ସବୁ ବିନ୍ଦୁ ହଟାଇବେ?',
    too_many: 'ଆପଣ ସର୍ବାଧିକ {n}ଟି ବିନ୍ଦୁ ଆଙ୍କିପାରିବେ।',
    points_n: 'ବିନ୍ଦୁ: {n}',
    noise: 'ନଏଜ୍: {n}%',
    noise_hint: 'ଅଧିକ ନଏଜ୍ ମାନେ ଅଧିକ ଏଲୋମେଲୋ, ମିଶିଯାଇଥିବା ବିନ୍ଦୁ।',
    split: 'ଟ୍ରେନିଂ ଡାଟା: {n}%',
    split_hint: 'ବାକି {n}% ଅଲଗା ରଖାଯାଏ, ଯାହାଫଳରେ ନେଟୱାର୍କ କେବେ ଦେଖିନଥିବା ବିନ୍ଦୁରେ ତାକୁ ପରୀକ୍ଷା କରାଯାଇପାରିବ।',
    new_data: 'ନୂଆ ଡାଟା',
    show_test: 'ଟେଷ୍ଟ ବିନ୍ଦୁ ଦେଖାନ୍ତୁ',
    sharp: 'ସ୍ପଷ୍ଟ ସୀମାରେଖା',
    network: 'ନେଟୱାର୍କ',
    inputs: 'ଇନପୁଟ୍ (ଫିଚର୍)',
    inputs_hint: 'ଅଧିକ ଇନପୁଟ୍ ନେଟୱାର୍କକୁ ଅଧିକ ସୂଚନା ଦିଏ।',
    need_input: 'ଅତି କମରେ ଗୋଟିଏ ଇନପୁଟ୍ ରଖିବା ଦରକାର।',
    hidden_layers: 'ହିଡେନ୍ ଲେୟର',
    layer_n: 'ଲେୟର {n}',
    neurons: 'ନ୍ୟୁରନ୍',
    add_layer: 'ଗୋଟିଏ ହିଡେନ୍ ଲେୟର ଯୋଡ଼ନ୍ତୁ',
    remove_layer: 'ଗୋଟିଏ ହିଡେନ୍ ଲେୟର ହଟାନ୍ତୁ',
    add_neuron: 'ଲେୟର {n}ରେ ଗୋଟିଏ ନ୍ୟୁରନ୍ ଯୋଡ଼ନ୍ତୁ',
    remove_neuron: 'ଲେୟର {n}ରୁ ଗୋଟିଏ ନ୍ୟୁରନ୍ ହଟାନ୍ତୁ',
    no_hidden: 'କୌଣସି ହିଡେନ୍ ଲେୟର ନାହିଁ: ପୂରା ନେଟୱାର୍କ କେବଳ ଗୋଟିଏ ନ୍ୟୁରନ୍।',
    activation: 'ଆକ୍ଟିଭେସନ୍',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'ସିଗ୍‌ମଏଡ୍',
    act_linear: 'ଲିନିଅର୍ (କିଛି ନୁହେଁ)',
    lr: 'ଲର୍ନିଂ ରେଟ୍',
    share_setup: 'ଏହି ସେଟଅପ୍ ସେୟାର୍ କରନ୍ତୁ',
    defaults: 'ଆରମ୍ଭ ସେଟିଂ ଫେରାଇ ଆଣନ୍ତୁ',
    inside: 'ନେଟୱାର୍କ ଭିତରେ',
    inside_hint: 'ପ୍ରତ୍ୟେକ ଘର ଦେଖାଏ ଗୋଟିଏ ନ୍ୟୁରନ୍ ପୂରା ଚିତ୍ରରେ କ’ଣ "ଦେଖେ"। ବଡ଼ କରି ଦେଖିବାକୁ ଘର ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ।',
    w_pos: 'ପଜିଟିଭ୍ ୱେଟ୍',
    w_neg: 'ନେଗେଟିଭ୍ ୱେଟ୍',
    w_thick: 'ମୋଟା ଲାଇନ୍ = ଅଧିକ ଶକ୍ତିଶାଳୀ ୱେଟ୍',
    output: 'ଆଉଟପୁଟ୍',
    output_hint: 'ପଛପଟ ରଙ୍ଗ = ପ୍ରତ୍ୟେକ ସ୍ଥାନ ପାଇଁ ନେଟୱାର୍କର ଅନୁମାନ। ଗାଢ଼ ରଙ୍ଗ = ଅଧିକ ନିଶ୍ଚିତ।',
    canvas_label: 'ବିନ୍ଦୁ ଓ ନେଟୱାର୍କର ଅନୁମାନର ଚିତ୍ର',
    canvas_empty: 'ବିନ୍ଦୁ ଯୋଡ଼ିବାକୁ ଏଠାରେ ଟ୍ୟାପ୍ କରନ୍ତୁ',
    train_loss: 'ଟ୍ରେନିଂ ଲସ୍',
    test_loss: 'ଟେଷ୍ଟ ଲସ୍',
    train_acc: 'ଟ୍ରେନିଂ ସଠିକତା',
    test_acc: 'ଟେଷ୍ଟ ସଠିକତା',
    loss_chart: 'ସମୟ ସହ ଲସ୍',
    chart_label: 'ପ୍ରତ୍ୟେକ ଏପକ୍ ପରେ ଟ୍ରେନିଂ ଲସ୍ ଓ ଟେଷ୍ଟ ଲସ୍‌ର ଚାର୍ଟ',
    legend_train: 'ଟ୍ରେନିଂ',
    legend_test: 'ଟେଷ୍ଟ',
    chart_hint: 'ଯେତେ କମ୍, ସେତେ ଭଲ। ଟ୍ରେନିଂ ଲାଇନ୍ ତଳକୁ ଗଲାବେଳେ ଯଦି ଟେଷ୍ଟ ଲାଇନ୍ ଉପରକୁ ଯାଏ, ତେବେ ନେଟୱାର୍କ ଓଭରଫିଟିଂ କରୁଛି।',
    ins_hint: 'ଏଗୁଡ଼ିକ ଏହି ନ୍ୟୁରନ୍‌ର ବର୍ତ୍ତମାନର ୱେଟ୍ ଓ ବାୟସ୍। ଶିଖିବା ସମୟରେ ଏଗୁଡ଼ିକ ବଦଳିବା ଦେଖନ୍ତୁ।',
    ins_prev: 'h₁, h₂… ହେଉଛନ୍ତି ପୂର୍ବ ଲେୟରର ନ୍ୟୁରନ୍।',
    ins_input: 'ଇନପୁଟ୍‌ର କୌଣସି ୱେଟ୍ ନଥାଏ। ଏହା କେବଳ ନିଜ ମୂଲ୍ୟ ପରବର୍ତ୍ତୀ ଲେୟରକୁ ଦେଇଦିଏ।',
    col_inputs: 'ଇନପୁଟ୍',
    col_hidden: 'ହିଡେନ୍ {n}',
    col_output: 'ଆଉଟପୁଟ୍',
    node_input: 'ଇନପୁଟ୍ {name}',
    node_hidden: 'ହିଡେନ୍ ଲେୟର {l}ର ନ୍ୟୁରନ୍ {n}',
    node_output: 'ଆଉଟପୁଟ୍ ନ୍ୟୁରନ୍',
    preview_input: 'ଇନପୁଟ୍ {name} ଦେଖାଯାଉଛି',
    preview_hidden: 'ହିଡେନ୍ ଲେୟର {l}ର ନ୍ୟୁରନ୍ {n} ଦେଖାଯାଉଛି',
    show_output: 'ଆଉଟପୁଟ୍ ଦେଖାନ୍ତୁ',
    coach_start: 'ନେଟୱାର୍କକୁ ଶିଖାଇବାକୁ "ଶିଖାନ୍ତୁ" ଦବାନ୍ତୁ। ପଛପଟ ପ୍ରତ୍ୟେକ ସ୍ଥାନ ପାଇଁ ତାର ଅନୁମାନ ଦେଖାଏ।',
    coach_training: 'ଶିଖୁଛି… ଲସ୍ କମିବା ଓ ରଙ୍ଗ ସ୍ଥିର ହେବା ଦେଖନ୍ତୁ।',
    coach_paused: 'ବିରତି ଦିଆଯାଇଛି। ଥରକେ ଗୋଟିଏ ଏପକ୍ ଶିଖାଇବାକୁ "ଗୋଟିଏ ପାଦ" ଦବାନ୍ତୁ।',
    coach_line: 'ହିଡେନ୍ ଲେୟର ବିନା ନେଟୱାର୍କ କେବଳ ଗୋଟିଏ ସିଧା ରେଖା ଟାଣିପାରେ, ଏବଂ ଏଠାରେ ତାହା ଯଥେଷ୍ଟ ନୁହେଁ। ଗୋଟିଏ ହିଡେନ୍ ଲେୟର ଯୋଡ଼ନ୍ତୁ!',
    coach_linear: 'ଲିନିଅର୍ ଆକ୍ଟିଭେସନ୍ ସହ ଅନେକ ଲେୟର ବି ଗୋଟିଏ ସିଧା ରେଖା ପରି କାମ କରନ୍ତି। tanh ବା ReLU ଚେଷ୍ଟା କରନ୍ତୁ।',
    coach_overfit: 'ଟ୍ରେନିଂ ଲସ୍ କମ୍ କିନ୍ତୁ ଟେଷ୍ଟ ଲସ୍ ଅଧିକ: ନେଟୱାର୍କ ଟ୍ରେନିଂ ବିନ୍ଦୁଗୁଡ଼ିକୁ ଘୋଷୁଛି। ଏହାକୁ ଓଭରଫିଟିଂ କୁହାଯାଏ।',
    coach_great: 'ଶିଖିଗଲା! {acc}% ଟେଷ୍ଟ ବିନ୍ଦୁ ଠିକ୍ ପଟେ ଅଛି।',
    coach_great_draw: 'ଶିଖିଗଲା! ଆପଣଙ୍କ {acc}% ବିନ୍ଦୁ ଠିକ୍ ପଟେ ଅଛି।',
    coach_slow: 'ବହୁତ ଧୀରେ ଶିଖୁଛି? ଲର୍ନିଂ ରେଟ୍ ବହୁତ ଛୋଟ, ତେଣୁ ପ୍ରତ୍ୟେକ ପାଦ ବି ଛୋଟ। ବଡ଼ ରେଟ୍ ଚେଷ୍ଟା କରନ୍ତୁ।',
    coach_stuck: 'ଅଟକିଗଲା? ନୂଆ ରାଣ୍ଡମ ୱେଟ୍ ପାଇଁ ରିସେଟ୍ ଦବାନ୍ତୁ, ବା ନେଟୱାର୍କ ବଦଳାନ୍ତୁ।',
    coach_explode: 'ଓହୋ! ଲର୍ନିଂ ରେଟ୍ ବହୁତ ବଡ଼ ହେତୁ ୱେଟ୍‌ଗୁଡ଼ିକ ବେକାବୁ ହୋଇଗଲେ। ଛୋଟ ରେଟ୍ ବାଛନ୍ତୁ।',
    coach_need_points: 'ଚିତ୍ର ଉପରେ କିଛି କମଳା ଓ କିଛି ନୀଳ ବିନ୍ଦୁ ଯୋଡ଼ନ୍ତୁ।',
    challenges: 'ଚ୍ୟାଲେଞ୍ଜ',
    challenges_intro: 'ପ୍ରଥମେ ଅନୁମାନ କରନ୍ତୁ, ତା’ପରେ "ଚେଷ୍ଟା କରନ୍ତୁ" ଦବାଇ ଶିଖାନ୍ତୁ। ଆପଣଙ୍କ ଅନୁମାନ ଠିକ୍ ହେଲା କି?',
    try_it: 'ଚେଷ୍ଟା କରନ୍ତୁ',
    notice: 'କ’ଣ ଲକ୍ଷ୍ୟ କରିବେ',
    loaded: 'ଚ୍ୟାଲେଞ୍ଜ {n} ପ୍ରସ୍ତୁତ। "ଶିଖାନ୍ତୁ" ଦବାନ୍ତୁ!',
    print_ws: 'ୱର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    ws_title: 'ୱର୍କସିଟ୍',
    ws_name: 'ନାମ',
    ws_class: 'ଶ୍ରେଣୀ',
    ws_date: 'ତାରିଖ',
    ws_guess: 'ମୋ ଅନୁମାନ:',
    ws_saw: 'କ’ଣ ହେଲା, ଓ କାହିଁକି:',
    explain: 'ଭିତରେ କ’ଣ ହେଉଛି?',
    help_title: 'କିପରି ବ୍ୟବହାର କରିବେ / ଶ୍ରେଣୀ ପାଇଁ ପରାମର୍ଶ',
    tip1: '<b>ଶିଖାନ୍ତୁ</b> (ବା <kbd>ସ୍ପେସବାର୍</kbd>) ଦବାନ୍ତୁ ଏବଂ ନେଟୱାର୍କ ଶିଖିବା ସମୟରେ ରଙ୍ଗ ବଦଳିବା ଦେଖନ୍ତୁ। <b>ଗୋଟିଏ ପାଦ</b> କେବଳ ଗୋଟିଏ ଏପକ୍ ଶିଖାଏ, ଯାହାଫଳରେ ଆପଣ ଧୀରେ ଧୀରେ ଆଗେଇପାରିବେ।',
    tip2: 'ଡାଟାସେଟ୍, ହିଡେନ୍ ଲେୟର ସଂଖ୍ୟା ଓ ନ୍ୟୁରନ୍ ବଦଳାନ୍ତୁ। ନେଟୱାର୍କ ବଦଳିବା ମାତ୍ରେ ଏହା ନୂଆ ରାଣ୍ଡମ ୱେଟ୍ ସହ ପୁଣି ଆରମ୍ଭ ହୁଏ। <b>ରିସେଟ୍</b> ବି ସେହି କାମ କରେ।',
    tip3: '<b>ନେଟୱାର୍କ ଭିତରେ</b> ଅଂଶର ଛୋଟ ଘରଗୁଡ଼ିକରେ ଟ୍ୟାପ୍ କରି ଦେଖନ୍ତୁ ପ୍ରତ୍ୟେକ ନ୍ୟୁରନ୍ କ’ଣ ଶିଖିଛି। ପରବର୍ତ୍ତୀ ଲେୟରର ନ୍ୟୁରନ୍ ସରଳ ଆକାରକୁ ମିଶାଇ ଜଟିଳ ଆକାର ତିଆରି କରନ୍ତି।',
    tip4: '<b>ନିଜେ ଆଙ୍କନ୍ତୁ</b> ବାଛନ୍ତୁ, ରଙ୍ଗ ବାଛନ୍ତୁ ଏବଂ ଚିତ୍ରରେ ଟ୍ୟାପ୍ କରି ନିଜର ପ୍ରହେଳିକା ତିଆରି କରନ୍ତୁ। ଏମିତି ପ୍ରହେଳିକା ତିଆରି କରିପାରିବେ କି ଯାହା ନେଟୱାର୍କ ଶିଖିପାରିବ ନାହିଁ?',
    tip5: '<b>ଶ୍ରେଣୀ କାର୍ଯ୍ୟକଳାପ:</b> ପ୍ରତ୍ୟେକ ଚ୍ୟାଲେଞ୍ଜ ପୂର୍ବରୁ ପୂରା ଶ୍ରେଣୀ ଭୋଟ୍ ଦିଅନ୍ତୁ: "ଏହା ଶିଖିପାରିବ କି?" ତା’ପରେ ସ୍ମାର୍ଟବୋର୍ଡରେ ଏକାଠି "ଶିଖାନ୍ତୁ" ଦବାନ୍ତୁ ଏବଂ ଏମିତି କାହିଁକି ହେଲା ଆଲୋଚନା କରନ୍ତୁ। ଅନୁମାନ ଲେଖିବାକୁ ୱର୍କସିଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ।',
    tip6: 'ପ୍ରୋଜେକ୍ଟରରେ <b>ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍</b> ବ୍ୟବହାର କରନ୍ତୁ। <b>ଏହି ସେଟଅପ୍ ସେୟାର୍ କରନ୍ତୁ</b> ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ପଠାଇବା ପାଇଁ ଲିଙ୍କ୍ ତିଆରି କରେ। ସବୁକିଛି ଏହି ଡିଭାଇସରେ ଚାଲେ ଏବଂ ଇଣ୍ଟରନେଟ୍ ବିନା ବି କାମ କରେ।'
  },
  ta: {
    app_title: 'நியூரல் நெட்வொர்க் விளையாட்டுக் களம்',
    intro: 'ஒரு சிறிய நியூரல் நெட்வொர்க் ஆரஞ்சு, நீலப் புள்ளிகளைப் பிரிக்கக் கற்றுக்கொள்வதைப் பாருங்கள். அதன் லேயர்கள், நியூரான்கள், அமைப்புகளை மாற்றி, ஒரு இயந்திரம் எடுத்துக்காட்டுகளில் இருந்து எப்படிக் கற்கிறது என்று அறியுங்கள்.',
    train: 'கற்பி',
    step: 'ஒரு படி',
    step_title: 'ஒரு எபாக் கற்பி (எல்லா பயிற்சிப் புள்ளிகளையும் ஒருமுறை முழுதாகச் சுற்றுவது)',
    reset_title: 'புதிய சீரற்ற வெயிட்களுடன் மீண்டும் கற்கத் தொடங்கு',
    epoch: 'எபாக்',
    speed: 'வேகம்',
    speed_slow: 'மெதுவாக',
    speed_normal: 'இயல்பு',
    speed_fast: 'வேகமாக',
    data: 'தரவு',
    dataset: 'தரவுத்தொகுப்பைத் தேர்வுசெய்',
    ds_blobs: 'இரண்டு கொத்துகள்',
    ds_circle: 'வட்டம்',
    ds_xor: 'XOR',
    ds_spiral: 'சுருள்',
    ds_draw: 'நீங்களே வரையுங்கள்',
    draw_hint: 'ஒரு நிறத்தைத் தேர்ந்தெடுத்து, படத்தில் தட்டி அல்லது இழுத்துப் புள்ளிகளைச் சேருங்கள். உங்கள் புள்ளிகள் அனைத்தும் பயிற்சிக்குப் பயன்படும்.',
    tool_orange: 'ஆரஞ்சு',
    tool_blue: 'நீலம்',
    tool_erase: 'அழிப்பான்',
    clear_points: 'புள்ளிகளை அழி',
    confirm_clear: 'நீங்கள் வரைந்த எல்லாப் புள்ளிகளையும் நீக்கவா?',
    too_many: 'அதிகபட்சம் {n} புள்ளிகள் வரையலாம்.',
    points_n: 'புள்ளிகள்: {n}',
    noise: 'இரைச்சல்: {n}%',
    noise_hint: 'அதிக இரைச்சல் என்றால் அதிகம் கலைந்த, கலந்த புள்ளிகள்.',
    split: 'பயிற்சித் தரவு: {n}%',
    split_hint: 'மீதமுள்ள {n}% தனியாக வைக்கப்படுகிறது, நெட்வொர்க் இதுவரை பார்க்காத புள்ளிகளில் அதைச் சோதிக்க.',
    new_data: 'புதிய தரவு',
    show_test: 'சோதனைப் புள்ளிகளைக் காட்டு',
    sharp: 'கூர்மையான எல்லை',
    network: 'நெட்வொர்க்',
    inputs: 'உள்ளீடுகள் (அம்சங்கள்)',
    inputs_hint: 'கூடுதல் உள்ளீடுகள் நெட்வொர்க்குக்குக் கூடுதல் துப்புகளைத் தருகின்றன.',
    need_input: 'குறைந்தது ஒரு உள்ளீடாவது இருக்க வேண்டும்.',
    hidden_layers: 'மறைநிலை லேயர்கள்',
    layer_n: 'லேயர் {n}',
    neurons: 'நியூரான்கள்',
    add_layer: 'ஒரு மறைநிலை லேயரைச் சேர்',
    remove_layer: 'ஒரு மறைநிலை லேயரை நீக்கு',
    add_neuron: 'லேயர் {n}-இல் ஒரு நியூரானைச் சேர்',
    remove_neuron: 'லேயர் {n}-இலிருந்து ஒரு நியூரானை நீக்கு',
    no_hidden: 'மறைநிலை லேயர் இல்லை: முழு நெட்வொர்க்கும் ஒரே ஒரு நியூரான்.',
    activation: 'ஆக்டிவேஷன்',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'சிக்மாய்டு',
    act_linear: 'லீனியர் (ஒன்றுமில்லை)',
    lr: 'கற்றல் வீதம்',
    share_setup: 'இந்த அமைப்பைப் பகிர்',
    defaults: 'தொடக்க அமைப்புகளுக்குத் திரும்பு',
    inside: 'நெட்வொர்க்கின் உள்ளே',
    inside_hint: 'ஒவ்வொரு சதுரமும் ஒரு நியூரான் படம் முழுவதும் எதைப் "பார்க்கிறது" என்று காட்டுகிறது. பெரிதாகப் பார்க்க ஒரு சதுரத்தைத் தட்டுங்கள்.',
    w_pos: 'நேர்மறை வெயிட்',
    w_neg: 'எதிர்மறை வெயிட்',
    w_thick: 'தடித்த கோடு = வலுவான வெயிட்',
    output: 'வெளியீடு',
    output_hint: 'பின்னணி நிறம் = ஒவ்வொரு இடத்துக்கும் நெட்வொர்க்கின் ஊகம். அடர் நிறம் = அதிக உறுதி.',
    canvas_label: 'புள்ளிகள் மற்றும் நெட்வொர்க்கின் ஊகங்களின் படம்',
    canvas_empty: 'புள்ளிகளைச் சேர்க்க இங்கே தட்டுங்கள்',
    train_loss: 'பயிற்சி இழப்பு',
    test_loss: 'சோதனை இழப்பு',
    train_acc: 'பயிற்சித் துல்லியம்',
    test_acc: 'சோதனைத் துல்லியம்',
    loss_chart: 'காலப்போக்கில் இழப்பு',
    chart_label: 'ஒவ்வொரு எபாக்குக்குப் பிறகும் பயிற்சி இழப்பு, சோதனை இழப்பு வரைபடம்',
    legend_train: 'பயிற்சி',
    legend_test: 'சோதனை',
    chart_hint: 'குறைவாக இருந்தால் நல்லது. பயிற்சிக் கோடு இறங்கும்போது சோதனைக் கோடு ஏறினால், நெட்வொர்க் ஓவர்ஃபிட்டிங் செய்கிறது.',
    ins_hint: 'இவை இந்த நியூரானின் இப்போதைய வெயிட்களும் பயஸும். கற்கும்போது அவை மாறுவதைப் பாருங்கள்.',
    ins_prev: 'h₁, h₂… என்பவை முந்தைய லேயரின் நியூரான்கள்.',
    ins_input: 'உள்ளீட்டுக்கு வெயிட் இல்லை. அது தன் மதிப்பை அடுத்த லேயருக்குக் கடத்துகிறது, அவ்வளவுதான்.',
    col_inputs: 'உள்ளீடுகள்',
    col_hidden: 'மறைநிலை {n}',
    col_output: 'வெளியீடு',
    node_input: 'உள்ளீடு {name}',
    node_hidden: 'மறைநிலை லேயர் {l}-இன் நியூரான் {n}',
    node_output: 'வெளியீட்டு நியூரான்',
    preview_input: 'உள்ளீடு {name} காட்டப்படுகிறது',
    preview_hidden: 'மறைநிலை லேயர் {l}-இன் நியூரான் {n} காட்டப்படுகிறது',
    show_output: 'வெளியீட்டைக் காட்டு',
    coach_start: 'நெட்வொர்க் கற்க "கற்பி" அழுத்துங்கள். பின்னணி ஒவ்வொரு இடத்துக்கும் அதன் ஊகத்தைக் காட்டுகிறது.',
    coach_training: 'கற்கிறது… இழப்பு குறைவதையும் நிறங்கள் நிலைப்பதையும் பாருங்கள்.',
    coach_paused: 'இடைநிறுத்தப்பட்டது. ஒரு நேரத்தில் ஒரு எபாக் கற்பிக்க "ஒரு படி" அழுத்துங்கள்.',
    coach_line: 'மறைநிலை லேயர் இல்லாமல் நெட்வொர்க் ஒரே ஒரு நேர்கோடு மட்டுமே வரைய முடியும், இங்கே அது போதாது. ஒரு மறைநிலை லேயரைச் சேருங்கள்!',
    coach_linear: 'லீனியர் ஆக்டிவேஷனுடன், பல லேயர்களும் ஒரே நேர்கோடு போலவே செயல்படும். tanh அல்லது ReLU முயற்சி செய்யுங்கள்.',
    coach_overfit: 'பயிற்சி இழப்பு குறைவு, ஆனால் சோதனை இழப்பு அதிகம்: நெட்வொர்க் பயிற்சிப் புள்ளிகளை மனப்பாடம் செய்கிறது. இதுவே ஓவர்ஃபிட்டிங்.',
    coach_great: 'கற்றுக்கொண்டது! {acc}% சோதனைப் புள்ளிகள் சரியான பக்கத்தில் உள்ளன.',
    coach_great_draw: 'கற்றுக்கொண்டது! உங்கள் புள்ளிகளில் {acc}% சரியான பக்கத்தில் உள்ளன.',
    coach_slow: 'மிக மெதுவாகக் கற்கிறதா? கற்றல் வீதம் மிகச் சிறியது, அதனால் ஒவ்வொரு அடியும் சிறியது. பெரிய வீதத்தை முயற்சி செய்யுங்கள்.',
    coach_stuck: 'சிக்கிக்கொண்டதா? புதிய சீரற்ற வெயிட்களுக்கு மீட்டமை அழுத்துங்கள், அல்லது நெட்வொர்க்கை மாற்றுங்கள்.',
    coach_explode: 'அச்சச்சோ! கற்றல் வீதம் மிகப் பெரியதால் வெயிட்கள் கட்டுக்கடங்காமல் போயின. சிறிய வீதத்தைத் தேர்ந்தெடுங்கள்.',
    coach_need_points: 'படத்தில் சில ஆரஞ்சு, சில நீலப் புள்ளிகளைச் சேருங்கள்.',
    challenges: 'சவால்கள்',
    challenges_intro: 'முதலில் ஊகியுங்கள், பிறகு "முயன்று பார்" அழுத்திக் கற்பியுங்கள். உங்கள் ஊகம் சரியா?',
    try_it: 'முயன்று பார்',
    notice: 'கவனிக்க வேண்டியது',
    loaded: 'சவால் {n} தயார். "கற்பி" அழுத்துங்கள்!',
    print_ws: 'பயிற்சித்தாளை அச்சிடு',
    ws_title: 'பயிற்சித்தாள்',
    ws_name: 'பெயர்',
    ws_class: 'வகுப்பு',
    ws_date: 'தேதி',
    ws_guess: 'என் ஊகம்:',
    ws_saw: 'என்ன நடந்தது, ஏன்:',
    explain: 'உள்ளே என்ன நடக்கிறது?',
    help_title: 'பயன்படுத்துவது எப்படி / வகுப்பறைக்கான யோசனைகள்',
    tip1: '<b>கற்பி</b> (அல்லது <kbd>ஸ்பேஸ்பார்</kbd>) அழுத்தி, நெட்வொர்க் கற்கும்போது நிறங்கள் மாறுவதைப் பாருங்கள். <b>ஒரு படி</b> ஒரே ஒரு எபாக் மட்டும் கற்பிக்கும், எனவே மெதுவாகச் செல்லலாம்.',
    tip2: 'தரவுத்தொகுப்பு, மறைநிலை லேயர்களின் எண்ணிக்கை, நியூரான்களை மாற்றுங்கள். நெட்வொர்க்கை மாற்றியதும் அது புதிய சீரற்ற வெயிட்களுடன் மீண்டும் தொடங்கும். <b>மீட்டமை</b> பொத்தானும் இதையே செய்யும்.',
    tip3: '<b>நெட்வொர்க்கின் உள்ளே</b> பகுதியில் உள்ள சிறிய சதுரங்களைத் தட்டி, ஒவ்வொரு நியூரானும் என்ன கற்றது என்று பாருங்கள். பின்வரும் லேயர்களின் நியூரான்கள் எளிய வடிவங்களை இணைத்துச் சிக்கலான வடிவங்களை உருவாக்குகின்றன.',
    tip4: '<b>நீங்களே வரையுங்கள்</b> என்பதைத் தேர்ந்தெடுத்து, ஒரு நிறத்தை எடுத்துப் படத்தில் தட்டி உங்கள் சொந்தப் புதிரை உருவாக்குங்கள். நெட்வொர்க்கால் கற்க முடியாத புதிரை வரைய முடியுமா?',
    tip5: '<b>வகுப்பறைச் செயல்பாடு:</b> ஒவ்வொரு சவாலுக்கும் முன் வகுப்பு வாக்களிக்கட்டும்: "இது கற்றுக்கொள்ளுமா?" பிறகு ஸ்மார்ட்போர்டில் ஒன்றாக "கற்பி" அழுத்தி, ஏன் என்று விவாதியுங்கள். ஊகங்களை எழுத பயிற்சித்தாளை அச்சிடுங்கள்.',
    tip6: 'புரொஜெக்டரில் <b>முழுத் திரை</b> பயன்படுத்துங்கள். <b>இந்த அமைப்பைப் பகிர்</b> மாணவர்களுக்கு அனுப்ப ஒரு இணைப்பை உருவாக்கும். எல்லாமே இந்தச் சாதனத்திலேயே இயங்கும், இணையம் இல்லாமலும் வேலை செய்யும்.'
  },
  te: {
    app_title: 'న్యూరల్ నెట్‌వర్క్ ఆటస్థలం',
    intro: 'ఒక చిన్న న్యూరల్ నెట్‌వర్క్ నారింజ, నీలం చుక్కలను వేరు చేయడం ఎలా నేర్చుకుంటుందో చూడండి. దాని లేయర్లు, న్యూరాన్లు, సెట్టింగ్‌లు మార్చి, యంత్రం ఉదాహరణల నుంచి ఎలా నేర్చుకుంటుందో తెలుసుకోండి.',
    train: 'నేర్పించు',
    step: 'ఒక అడుగు',
    step_title: 'ఒక ఎపాక్ నేర్పించు (అన్ని ట్రైనింగ్ చుక్కల మీదుగా ఒక పూర్తి రౌండ్)',
    reset_title: 'కొత్త యాదృచ్ఛిక వెయిట్‌లతో మళ్ళీ నేర్చుకోవడం మొదలుపెట్టు',
    epoch: 'ఎపాక్',
    speed: 'వేగం',
    speed_slow: 'నెమ్మది',
    speed_normal: 'సాధారణం',
    speed_fast: 'వేగంగా',
    data: 'డేటా',
    dataset: 'డేటాసెట్ ఎంచుకోండి',
    ds_blobs: 'రెండు గుంపులు',
    ds_circle: 'వృత్తం',
    ds_xor: 'XOR',
    ds_spiral: 'సర్పిలం',
    ds_draw: 'మీరే గీయండి',
    draw_hint: 'ఒక రంగు ఎంచుకుని, చిత్రంపై తట్టండి లేదా లాగి చుక్కలు జోడించండి. మీ చుక్కలన్నీ ట్రైనింగ్‌కు వాడబడతాయి.',
    tool_orange: 'నారింజ',
    tool_blue: 'నీలం',
    tool_erase: 'ఎరేజర్',
    clear_points: 'చుక్కలు తుడిచివేయండి',
    confirm_clear: 'మీరు గీసిన చుక్కలన్నీ తీసివేయాలా?',
    too_many: 'మీరు గరిష్ఠంగా {n} చుక్కలు గీయవచ్చు.',
    points_n: 'చుక్కలు: {n}',
    noise: 'నాయిస్: {n}%',
    noise_hint: 'ఎక్కువ నాయిస్ అంటే ఎక్కువ చెల్లాచెదురుగా, కలగలిసిన చుక్కలు.',
    split: 'ట్రైనింగ్ డేటా: {n}%',
    split_hint: 'మిగతా {n}% పక్కన పెట్టబడుతుంది, నెట్‌వర్క్ ఎప్పుడూ చూడని చుక్కలపై దాన్ని పరీక్షించడానికి.',
    new_data: 'కొత్త డేటా',
    show_test: 'టెస్ట్ చుక్కలు చూపించు',
    sharp: 'స్పష్టమైన సరిహద్దు',
    network: 'నెట్‌వర్క్',
    inputs: 'ఇన్‌పుట్‌లు (ఫీచర్లు)',
    inputs_hint: 'అదనపు ఇన్‌పుట్‌లు నెట్‌వర్క్‌కు అదనపు ఆధారాలు ఇస్తాయి.',
    need_input: 'కనీసం ఒక ఇన్‌పుట్ ఉండాలి.',
    hidden_layers: 'హిడెన్ లేయర్లు',
    layer_n: 'లేయర్ {n}',
    neurons: 'న్యూరాన్లు',
    add_layer: 'ఒక హిడెన్ లేయర్ జోడించండి',
    remove_layer: 'ఒక హిడెన్ లేయర్ తీసివేయండి',
    add_neuron: 'లేయర్ {n}కి ఒక న్యూరాన్ జోడించండి',
    remove_neuron: 'లేయర్ {n} నుంచి ఒక న్యూరాన్ తీసివేయండి',
    no_hidden: 'హిడెన్ లేయర్ లేదు: మొత్తం నెట్‌వర్క్ ఒకే ఒక న్యూరాన్.',
    activation: 'యాక్టివేషన్',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'సిగ్మాయిడ్',
    act_linear: 'లీనియర్ (ఏదీ లేదు)',
    lr: 'లెర్నింగ్ రేట్',
    share_setup: 'ఈ సెటప్‌ను షేర్ చేయండి',
    defaults: 'మొదటి సెట్టింగ్‌లు తిరిగి తెండి',
    inside: 'నెట్‌వర్క్ లోపల',
    inside_hint: 'ప్రతి చతురస్రం ఒక న్యూరాన్ చిత్రమంతటా ఏమి "చూస్తుందో" చూపిస్తుంది. పెద్దగా చూడటానికి చతురస్రాన్ని తట్టండి.',
    w_pos: 'పాజిటివ్ వెయిట్',
    w_neg: 'నెగటివ్ వెయిట్',
    w_thick: 'మందమైన గీత = బలమైన వెయిట్',
    output: 'అవుట్‌పుట్',
    output_hint: 'నేపథ్య రంగు = ప్రతి చోటుకూ నెట్‌వర్క్ అంచనా. ముదురు రంగు = ఎక్కువ నమ్మకం.',
    canvas_label: 'చుక్కలు, నెట్‌వర్క్ అంచనాల చిత్రం',
    canvas_empty: 'చుక్కలు జోడించడానికి ఇక్కడ తట్టండి',
    train_loss: 'ట్రైనింగ్ లాస్',
    test_loss: 'టెస్ట్ లాస్',
    train_acc: 'ట్రైనింగ్ ఖచ్చితత్వం',
    test_acc: 'టెస్ట్ ఖచ్చితత్వం',
    loss_chart: 'కాలంతో పాటు లాస్',
    chart_label: 'ప్రతి ఎపాక్ తర్వాత ట్రైనింగ్ లాస్, టెస్ట్ లాస్ చార్ట్',
    legend_train: 'ట్రైనింగ్',
    legend_test: 'టెస్ట్',
    chart_hint: 'ఎంత తక్కువైతే అంత మంచిది. ట్రైనింగ్ గీత కిందికి వెళ్తుంటే టెస్ట్ గీత పైకి వెళ్తే, నెట్‌వర్క్ ఓవర్‌ఫిట్టింగ్ చేస్తోంది.',
    ins_hint: 'ఇవి ఈ న్యూరాన్ ప్రస్తుత వెయిట్‌లు, బయాస్. నేర్చుకునేటప్పుడు అవి మారడం చూడండి.',
    ins_prev: 'h₁, h₂… అంటే ముందటి లేయర్‌లోని న్యూరాన్లు.',
    ins_input: 'ఇన్‌పుట్‌కు వెయిట్‌లు ఉండవు. అది తన విలువను తర్వాతి లేయర్‌కు అందిస్తుంది, అంతే.',
    col_inputs: 'ఇన్‌పుట్‌లు',
    col_hidden: 'హిడెన్ {n}',
    col_output: 'అవుట్‌పుట్',
    node_input: 'ఇన్‌పుట్ {name}',
    node_hidden: 'హిడెన్ లేయర్ {l}లో న్యూరాన్ {n}',
    node_output: 'అవుట్‌పుట్ న్యూరాన్',
    preview_input: 'ఇన్‌పుట్ {name} చూపిస్తోంది',
    preview_hidden: 'హిడెన్ లేయర్ {l}లో న్యూరాన్ {n} చూపిస్తోంది',
    show_output: 'అవుట్‌పుట్ చూపించు',
    coach_start: 'నెట్‌వర్క్ నేర్చుకోవడానికి "నేర్పించు" నొక్కండి. నేపథ్యం ప్రతి చోటుకూ దాని అంచనాను చూపిస్తుంది.',
    coach_training: 'నేర్చుకుంటోంది… లాస్ తగ్గడం, రంగులు స్థిరపడటం చూడండి.',
    coach_paused: 'ఆపబడింది. ఒక్కో ఎపాక్ నేర్పించడానికి "ఒక అడుగు" నొక్కండి.',
    coach_line: 'హిడెన్ లేయర్ లేకుండా నెట్‌వర్క్ ఒకే ఒక సరళరేఖ మాత్రమే గీయగలదు, ఇక్కడ అది సరిపోదు. ఒక హిడెన్ లేయర్ జోడించండి!',
    coach_linear: 'లీనియర్ యాక్టివేషన్‌తో ఎన్ని లేయర్లు ఉన్నా ఒకే సరళరేఖలా పనిచేస్తాయి. tanh లేదా ReLU ప్రయత్నించండి.',
    coach_overfit: 'ట్రైనింగ్ లాస్ తక్కువ, కానీ టెస్ట్ లాస్ ఎక్కువ: నెట్‌వర్క్ ట్రైనింగ్ చుక్కలను బట్టీ పడుతోంది. దీన్నే ఓవర్‌ఫిట్టింగ్ అంటారు.',
    coach_great: 'నేర్చుకుంది! {acc}% టెస్ట్ చుక్కలు సరైన వైపున ఉన్నాయి.',
    coach_great_draw: 'నేర్చుకుంది! మీ చుక్కల్లో {acc}% సరైన వైపున ఉన్నాయి.',
    coach_slow: 'చాలా నెమ్మదిగా నేర్చుకుంటోందా? లెర్నింగ్ రేట్ చాలా చిన్నది, అందుకే ప్రతి అడుగూ చిన్నదే. పెద్ద రేట్ ప్రయత్నించండి.',
    coach_stuck: 'ఇరుక్కుపోయిందా? కొత్త యాదృచ్ఛిక వెయిట్‌ల కోసం రీసెట్ నొక్కండి, లేదా నెట్‌వర్క్ మార్చండి.',
    coach_explode: 'అయ్యో! లెర్నింగ్ రేట్ మరీ పెద్దది కావడంతో వెయిట్‌లు అదుపు తప్పాయి. చిన్న రేట్ ఎంచుకోండి.',
    coach_need_points: 'చిత్రంపై కొన్ని నారింజ, కొన్ని నీలం చుక్కలు జోడించండి.',
    challenges: 'సవాళ్లు',
    challenges_intro: 'ముందు ఊహించండి, తర్వాత "ప్రయత్నించు" నొక్కి నేర్పించండి. మీ ఊహ నిజమైందా?',
    try_it: 'ప్రయత్నించు',
    notice: 'ఏమి గమనించాలి',
    loaded: 'సవాల్ {n} సిద్ధం. "నేర్పించు" నొక్కండి!',
    print_ws: 'వర్క్‌షీట్ ప్రింట్ చేయండి',
    ws_title: 'వర్క్‌షీట్',
    ws_name: 'పేరు',
    ws_class: 'తరగతి',
    ws_date: 'తేదీ',
    ws_guess: 'నా ఊహ:',
    ws_saw: 'ఏమి జరిగింది, ఎందుకు:',
    explain: 'లోపల ఏమి జరుగుతోంది?',
    help_title: 'ఎలా ఉపయోగించాలి / తరగతి గదికి ఆలోచనలు',
    tip1: '<b>నేర్పించు</b> (లేదా <kbd>స్పేస్‌బార్</kbd>) నొక్కి, నెట్‌వర్క్ నేర్చుకుంటున్నప్పుడు రంగులు మారడం చూడండి. <b>ఒక అడుగు</b> ఒకే ఎపాక్ నేర్పిస్తుంది, కాబట్టి నెమ్మదిగా వెళ్ళవచ్చు.',
    tip2: 'డేటాసెట్, హిడెన్ లేయర్ల సంఖ్య, న్యూరాన్లను మార్చండి. నెట్‌వర్క్ మార్చగానే అది కొత్త యాదృచ్ఛిక వెయిట్‌లతో మళ్ళీ మొదలవుతుంది. <b>రీసెట్</b> కూడా అదే చేస్తుంది.',
    tip3: '<b>నెట్‌వర్క్ లోపల</b> భాగంలోని చిన్న చతురస్రాలను తట్టి, ప్రతి న్యూరాన్ ఏమి నేర్చుకుందో చూడండి. తర్వాతి లేయర్లలోని న్యూరాన్లు సరళమైన ఆకారాలను కలిపి క్లిష్టమైన ఆకారాలు చేస్తాయి.',
    tip4: '<b>మీరే గీయండి</b> ఎంచుకుని, ఒక రంగు తీసుకుని చిత్రంపై తట్టి మీ సొంత పజిల్ తయారు చేయండి. నెట్‌వర్క్ నేర్చుకోలేని పజిల్ గీయగలరా?',
    tip5: '<b>తరగతి కార్యకలాపం:</b> ప్రతి సవాల్‌కు ముందు తరగతి ఓటు వేయాలి: "ఇది నేర్చుకుంటుందా?" తర్వాత స్మార్ట్‌బోర్డ్‌పై అందరూ కలిసి "నేర్పించు" నొక్కి, ఎందుకలా జరిగిందో చర్చించండి. ఊహలు రాసుకోవడానికి వర్క్‌షీట్ ప్రింట్ చేయండి.',
    tip6: 'ప్రొజెక్టర్‌పై <b>పూర్తి స్క్రీన్</b> వాడండి. <b>ఈ సెటప్‌ను షేర్ చేయండి</b> విద్యార్థులకు పంపడానికి ఒక లింక్ తయారు చేస్తుంది. అంతా ఈ పరికరంలోనే నడుస్తుంది, ఇంటర్నెట్ లేకున్నా పనిచేస్తుంది.'
  },
  kn: {
    app_title: 'ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್ ಆಟದ ಮೈದಾನ',
    intro: 'ಒಂದು ಚಿಕ್ಕ ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್ ಕಿತ್ತಳೆ ಮತ್ತು ನೀಲಿ ಚುಕ್ಕೆಗಳನ್ನು ಬೇರ್ಪಡಿಸಲು ಹೇಗೆ ಕಲಿಯುತ್ತದೆ ನೋಡಿ. ಅದರ ಲೇಯರ್‌ಗಳು, ನ್ಯೂರಾನ್‌ಗಳು ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಬದಲಿಸಿ, ಯಂತ್ರ ಉದಾಹರಣೆಗಳಿಂದ ಹೇಗೆ ಕಲಿಯುತ್ತದೆ ಎಂದು ತಿಳಿಯಿರಿ.',
    train: 'ಕಲಿಸಿ',
    step: 'ಒಂದು ಹೆಜ್ಜೆ',
    step_title: 'ಒಂದು ಎಪಾಕ್ ಕಲಿಸಿ (ಎಲ್ಲಾ ಟ್ರೈನಿಂಗ್ ಚುಕ್ಕೆಗಳ ಮೇಲೆ ಒಂದು ಪೂರ್ಣ ಸುತ್ತು)',
    reset_title: 'ಹೊಸ ಯಾದೃಚ್ಛಿಕ ವೆಯ್ಟ್‌ಗಳೊಂದಿಗೆ ಮತ್ತೆ ಕಲಿಯಲು ಶುರುಮಾಡಿ',
    epoch: 'ಎಪಾಕ್',
    speed: 'ವೇಗ',
    speed_slow: 'ನಿಧಾನ',
    speed_normal: 'ಸಾಮಾನ್ಯ',
    speed_fast: 'ವೇಗವಾಗಿ',
    data: 'ಡೇಟಾ',
    dataset: 'ಡೇಟಾಸೆಟ್ ಆಯ್ಕೆಮಾಡಿ',
    ds_blobs: 'ಎರಡು ಗುಂಪುಗಳು',
    ds_circle: 'ವೃತ್ತ',
    ds_xor: 'XOR',
    ds_spiral: 'ಸುರುಳಿ',
    ds_draw: 'ನೀವೇ ಬಿಡಿಸಿ',
    draw_hint: 'ಒಂದು ಬಣ್ಣ ಆಯ್ಕೆಮಾಡಿ, ನಂತರ ಚಿತ್ರದ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ ಅಥವಾ ಎಳೆದು ಚುಕ್ಕೆಗಳನ್ನು ಸೇರಿಸಿ. ನಿಮ್ಮ ಎಲ್ಲಾ ಚುಕ್ಕೆಗಳನ್ನು ಟ್ರೈನಿಂಗ್‌ಗೆ ಬಳಸಲಾಗುತ್ತದೆ.',
    tool_orange: 'ಕಿತ್ತಳೆ',
    tool_blue: 'ನೀಲಿ',
    tool_erase: 'ರಬ್ಬರ್',
    clear_points: 'ಚುಕ್ಕೆಗಳನ್ನು ಅಳಿಸಿ',
    confirm_clear: 'ನೀವು ಬಿಡಿಸಿದ ಎಲ್ಲಾ ಚುಕ್ಕೆಗಳನ್ನು ತೆಗೆದುಹಾಕಬೇಕೇ?',
    too_many: 'ನೀವು ಗರಿಷ್ಠ {n} ಚುಕ್ಕೆಗಳನ್ನು ಬಿಡಿಸಬಹುದು.',
    points_n: 'ಚುಕ್ಕೆಗಳು: {n}',
    noise: 'ಗದ್ದಲ (ನಾಯ್ಸ್): {n}%',
    noise_hint: 'ಹೆಚ್ಚು ಗದ್ದಲ ಎಂದರೆ ಹೆಚ್ಚು ಚದುರಿದ, ಬೆರೆತ ಚುಕ್ಕೆಗಳು.',
    split: 'ಟ್ರೈನಿಂಗ್ ಡೇಟಾ: {n}%',
    split_hint: 'ಉಳಿದ {n}% ಅನ್ನು ಬದಿಗಿಡಲಾಗುತ್ತದೆ, ನೆಟ್‌ವರ್ಕ್ ಹಿಂದೆಂದೂ ನೋಡದ ಚುಕ್ಕೆಗಳ ಮೇಲೆ ಅದನ್ನು ಪರೀಕ್ಷಿಸಲು.',
    new_data: 'ಹೊಸ ಡೇಟಾ',
    show_test: 'ಟೆಸ್ಟ್ ಚುಕ್ಕೆಗಳನ್ನು ತೋರಿಸಿ',
    sharp: 'ಸ್ಪಷ್ಟ ಗಡಿರೇಖೆ',
    network: 'ನೆಟ್‌ವರ್ಕ್',
    inputs: 'ಇನ್‌ಪುಟ್‌ಗಳು (ಫೀಚರ್‌ಗಳು)',
    inputs_hint: 'ಹೆಚ್ಚುವರಿ ಇನ್‌ಪುಟ್‌ಗಳು ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಹೆಚ್ಚುವರಿ ಸುಳಿವುಗಳನ್ನು ಕೊಡುತ್ತವೆ.',
    need_input: 'ಕನಿಷ್ಠ ಒಂದು ಇನ್‌ಪುಟ್ ಇರಲೇಬೇಕು.',
    hidden_layers: 'ಹಿಡನ್ ಲೇಯರ್‌ಗಳು',
    layer_n: 'ಲೇಯರ್ {n}',
    neurons: 'ನ್ಯೂರಾನ್‌ಗಳು',
    add_layer: 'ಒಂದು ಹಿಡನ್ ಲೇಯರ್ ಸೇರಿಸಿ',
    remove_layer: 'ಒಂದು ಹಿಡನ್ ಲೇಯರ್ ತೆಗೆಯಿರಿ',
    add_neuron: 'ಲೇಯರ್ {n}ಗೆ ಒಂದು ನ್ಯೂರಾನ್ ಸೇರಿಸಿ',
    remove_neuron: 'ಲೇಯರ್ {n}ರಿಂದ ಒಂದು ನ್ಯೂರಾನ್ ತೆಗೆಯಿರಿ',
    no_hidden: 'ಹಿಡನ್ ಲೇಯರ್ ಇಲ್ಲ: ಇಡೀ ನೆಟ್‌ವರ್ಕ್ ಒಂದೇ ಒಂದು ನ್ಯೂರಾನ್.',
    activation: 'ಆಕ್ಟಿವೇಷನ್',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'ಸಿಗ್ಮಾಯ್ಡ್',
    act_linear: 'ಲೀನಿಯರ್ (ಯಾವುದೂ ಇಲ್ಲ)',
    lr: 'ಲರ್ನಿಂಗ್ ರೇಟ್',
    share_setup: 'ಈ ಸೆಟಪ್ ಹಂಚಿಕೊಳ್ಳಿ',
    defaults: 'ಮೂಲ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಮರಳಿ ತನ್ನಿ',
    inside: 'ನೆಟ್‌ವರ್ಕ್‌ನ ಒಳಗೆ',
    inside_hint: 'ಪ್ರತಿ ಚೌಕವೂ ಒಂದು ನ್ಯೂರಾನ್ ಇಡೀ ಚಿತ್ರದಲ್ಲಿ ಏನನ್ನು "ನೋಡುತ್ತದೆ" ಎಂದು ತೋರಿಸುತ್ತದೆ. ದೊಡ್ಡದಾಗಿ ನೋಡಲು ಚೌಕದ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ.',
    w_pos: 'ಪಾಸಿಟಿವ್ ವೆಯ್ಟ್',
    w_neg: 'ನೆಗೆಟಿವ್ ವೆಯ್ಟ್',
    w_thick: 'ದಪ್ಪ ಗೆರೆ = ಬಲವಾದ ವೆಯ್ಟ್',
    output: 'ಔಟ್‌ಪುಟ್',
    output_hint: 'ಹಿನ್ನೆಲೆ ಬಣ್ಣ = ಪ್ರತಿ ಜಾಗಕ್ಕೂ ನೆಟ್‌ವರ್ಕ್‌ನ ಊಹೆ. ಗಾಢ ಬಣ್ಣ = ಹೆಚ್ಚು ಖಚಿತ.',
    canvas_label: 'ಚುಕ್ಕೆಗಳು ಮತ್ತು ನೆಟ್‌ವರ್ಕ್‌ನ ಊಹೆಗಳ ಚಿತ್ರ',
    canvas_empty: 'ಚುಕ್ಕೆಗಳನ್ನು ಸೇರಿಸಲು ಇಲ್ಲಿ ಟ್ಯಾಪ್ ಮಾಡಿ',
    train_loss: 'ಟ್ರೈನಿಂಗ್ ಲಾಸ್',
    test_loss: 'ಟೆಸ್ಟ್ ಲಾಸ್',
    train_acc: 'ಟ್ರೈನಿಂಗ್ ನಿಖರತೆ',
    test_acc: 'ಟೆಸ್ಟ್ ನಿಖರತೆ',
    loss_chart: 'ಸಮಯದೊಂದಿಗೆ ಲಾಸ್',
    chart_label: 'ಪ್ರತಿ ಎಪಾಕ್ ನಂತರದ ಟ್ರೈನಿಂಗ್ ಲಾಸ್ ಮತ್ತು ಟೆಸ್ಟ್ ಲಾಸ್ ಚಾರ್ಟ್',
    legend_train: 'ಟ್ರೈನಿಂಗ್',
    legend_test: 'ಟೆಸ್ಟ್',
    chart_hint: 'ಕಡಿಮೆ ಇದ್ದಷ್ಟೂ ಒಳ್ಳೆಯದು. ಟ್ರೈನಿಂಗ್ ಗೆರೆ ಕೆಳಗೆ ಹೋಗುತ್ತಿರುವಾಗ ಟೆಸ್ಟ್ ಗೆರೆ ಮೇಲೆ ಹೋದರೆ, ನೆಟ್‌ವರ್ಕ್ ಓವರ್‌ಫಿಟ್ಟಿಂಗ್ ಮಾಡುತ್ತಿದೆ.',
    ins_hint: 'ಇವು ಈ ನ್ಯೂರಾನ್‌ನ ಈಗಿನ ವೆಯ್ಟ್‌ಗಳು ಮತ್ತು ಬಯಾಸ್. ಕಲಿಯುವಾಗ ಅವು ಬದಲಾಗುವುದನ್ನು ನೋಡಿ.',
    ins_prev: 'h₁, h₂… ಎಂದರೆ ಹಿಂದಿನ ಲೇಯರ್‌ನ ನ್ಯೂರಾನ್‌ಗಳು.',
    ins_input: 'ಇನ್‌ಪುಟ್‌ಗೆ ವೆಯ್ಟ್ ಇರುವುದಿಲ್ಲ. ಅದು ತನ್ನ ಮೌಲ್ಯವನ್ನು ಮುಂದಿನ ಲೇಯರ್‌ಗೆ ದಾಟಿಸುತ್ತದೆ ಅಷ್ಟೇ.',
    col_inputs: 'ಇನ್‌ಪುಟ್‌ಗಳು',
    col_hidden: 'ಹಿಡನ್ {n}',
    col_output: 'ಔಟ್‌ಪುಟ್',
    node_input: 'ಇನ್‌ಪುಟ್ {name}',
    node_hidden: 'ಹಿಡನ್ ಲೇಯರ್ {l}ರ ನ್ಯೂರಾನ್ {n}',
    node_output: 'ಔಟ್‌ಪುಟ್ ನ್ಯೂರಾನ್',
    preview_input: 'ಇನ್‌ಪುಟ್ {name} ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    preview_hidden: 'ಹಿಡನ್ ಲೇಯರ್ {l}ರ ನ್ಯೂರಾನ್ {n} ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    show_output: 'ಔಟ್‌ಪುಟ್ ತೋರಿಸಿ',
    coach_start: 'ನೆಟ್‌ವರ್ಕ್ ಕಲಿಯಲು "ಕಲಿಸಿ" ಒತ್ತಿ. ಹಿನ್ನೆಲೆಯು ಪ್ರತಿ ಜಾಗಕ್ಕೂ ಅದರ ಊಹೆಯನ್ನು ತೋರಿಸುತ್ತದೆ.',
    coach_training: 'ಕಲಿಯುತ್ತಿದೆ… ಲಾಸ್ ಇಳಿಯುವುದನ್ನು ಮತ್ತು ಬಣ್ಣಗಳು ನೆಲೆಗೊಳ್ಳುವುದನ್ನು ನೋಡಿ.',
    coach_paused: 'ವಿರಾಮದಲ್ಲಿದೆ. ಒಂದೊಂದೇ ಎಪಾಕ್ ಕಲಿಸಲು "ಒಂದು ಹೆಜ್ಜೆ" ಒತ್ತಿ.',
    coach_line: 'ಹಿಡನ್ ಲೇಯರ್ ಇಲ್ಲದೆ ನೆಟ್‌ವರ್ಕ್ ಒಂದೇ ಒಂದು ನೇರ ಗೆರೆ ಮಾತ್ರ ಎಳೆಯಬಲ್ಲದು, ಇಲ್ಲಿ ಅದು ಸಾಲದು. ಒಂದು ಹಿಡನ್ ಲೇಯರ್ ಸೇರಿಸಿ!',
    coach_linear: 'ಲೀನಿಯರ್ ಆಕ್ಟಿವೇಷನ್‌ನೊಂದಿಗೆ ಅನೇಕ ಲೇಯರ್‌ಗಳೂ ಒಂದೇ ನೇರ ಗೆರೆಯಂತೆ ವರ್ತಿಸುತ್ತವೆ. tanh ಅಥವಾ ReLU ಪ್ರಯತ್ನಿಸಿ.',
    coach_overfit: 'ಟ್ರೈನಿಂಗ್ ಲಾಸ್ ಕಡಿಮೆ, ಆದರೆ ಟೆಸ್ಟ್ ಲಾಸ್ ಹೆಚ್ಚು: ನೆಟ್‌ವರ್ಕ್ ಟ್ರೈನಿಂಗ್ ಚುಕ್ಕೆಗಳನ್ನು ಬಾಯಿಪಾಠ ಮಾಡುತ್ತಿದೆ. ಇದನ್ನೇ ಓವರ್‌ಫಿಟ್ಟಿಂಗ್ ಎನ್ನುತ್ತಾರೆ.',
    coach_great: 'ಕಲಿತುಬಿಟ್ಟಿತು! {acc}% ಟೆಸ್ಟ್ ಚುಕ್ಕೆಗಳು ಸರಿಯಾದ ಬದಿಯಲ್ಲಿವೆ.',
    coach_great_draw: 'ಕಲಿತುಬಿಟ್ಟಿತು! ನಿಮ್ಮ {acc}% ಚುಕ್ಕೆಗಳು ಸರಿಯಾದ ಬದಿಯಲ್ಲಿವೆ.',
    coach_slow: 'ತುಂಬಾ ನಿಧಾನವಾಗಿ ಕಲಿಯುತ್ತಿದೆಯೇ? ಲರ್ನಿಂಗ್ ರೇಟ್ ತುಂಬಾ ಚಿಕ್ಕದು, ಹಾಗಾಗಿ ಪ್ರತಿ ಹೆಜ್ಜೆಯೂ ಚಿಕ್ಕದು. ದೊಡ್ಡ ರೇಟ್ ಪ್ರಯತ್ನಿಸಿ.',
    coach_stuck: 'ಸಿಕ್ಕಿಹಾಕಿಕೊಂಡಿದೆಯೇ? ಹೊಸ ಯಾದೃಚ್ಛಿಕ ವೆಯ್ಟ್‌ಗಳಿಗಾಗಿ ಮರುಹೊಂದಿಸಿ ಒತ್ತಿ, ಅಥವಾ ನೆಟ್‌ವರ್ಕ್ ಬದಲಿಸಿ.',
    coach_explode: 'ಅಯ್ಯೋ! ಲರ್ನಿಂಗ್ ರೇಟ್ ತುಂಬಾ ದೊಡ್ಡದಾದ್ದರಿಂದ ವೆಯ್ಟ್‌ಗಳು ಹತೋಟಿ ತಪ್ಪಿದವು. ಚಿಕ್ಕ ರೇಟ್ ಆಯ್ಕೆಮಾಡಿ.',
    coach_need_points: 'ಚಿತ್ರದ ಮೇಲೆ ಕೆಲವು ಕಿತ್ತಳೆ ಮತ್ತು ಕೆಲವು ನೀಲಿ ಚುಕ್ಕೆಗಳನ್ನು ಸೇರಿಸಿ.',
    challenges: 'ಸವಾಲುಗಳು',
    challenges_intro: 'ಮೊದಲು ಊಹಿಸಿ, ನಂತರ "ಪ್ರಯತ್ನಿಸಿ" ಒತ್ತಿ ಕಲಿಸಿ. ನಿಮ್ಮ ಊಹೆ ಸರಿಯಾಯಿತೇ?',
    try_it: 'ಪ್ರಯತ್ನಿಸಿ',
    notice: 'ಏನನ್ನು ಗಮನಿಸಬೇಕು',
    loaded: 'ಸವಾಲು {n} ಸಿದ್ಧ. "ಕಲಿಸಿ" ಒತ್ತಿ!',
    print_ws: 'ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ',
    ws_title: 'ವರ್ಕ್‌ಶೀಟ್',
    ws_name: 'ಹೆಸರು',
    ws_class: 'ತರಗತಿ',
    ws_date: 'ದಿನಾಂಕ',
    ws_guess: 'ನನ್ನ ಊಹೆ:',
    ws_saw: 'ಏನಾಯಿತು, ಮತ್ತು ಏಕೆ:',
    explain: 'ಒಳಗೆ ಏನು ನಡೆಯುತ್ತಿದೆ?',
    help_title: 'ಬಳಸುವುದು ಹೇಗೆ / ತರಗತಿಗೆ ಉಪಾಯಗಳು',
    tip1: '<b>ಕಲಿಸಿ</b> (ಅಥವಾ <kbd>ಸ್ಪೇಸ್‌ಬಾರ್</kbd>) ಒತ್ತಿ, ನೆಟ್‌ವರ್ಕ್ ಕಲಿಯುವಾಗ ಬಣ್ಣಗಳು ಬದಲಾಗುವುದನ್ನು ನೋಡಿ. <b>ಒಂದು ಹೆಜ್ಜೆ</b> ಒಂದೇ ಎಪಾಕ್ ಕಲಿಸುತ್ತದೆ, ಹಾಗಾಗಿ ನಿಧಾನವಾಗಿ ಸಾಗಬಹುದು.',
    tip2: 'ಡೇಟಾಸೆಟ್, ಹಿಡನ್ ಲೇಯರ್‌ಗಳ ಸಂಖ್ಯೆ ಮತ್ತು ನ್ಯೂರಾನ್‌ಗಳನ್ನು ಬದಲಿಸಿ. ನೆಟ್‌ವರ್ಕ್ ಬದಲಿಸಿದ ಕೂಡಲೇ ಅದು ಹೊಸ ಯಾದೃಚ್ಛಿಕ ವೆಯ್ಟ್‌ಗಳೊಂದಿಗೆ ಮತ್ತೆ ಶುರುವಾಗುತ್ತದೆ. <b>ಮರುಹೊಂದಿಸಿ</b> ಕೂಡ ಅದನ್ನೇ ಮಾಡುತ್ತದೆ.',
    tip3: '<b>ನೆಟ್‌ವರ್ಕ್‌ನ ಒಳಗೆ</b> ಭಾಗದ ಸಣ್ಣ ಚೌಕಗಳನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ, ಪ್ರತಿ ನ್ಯೂರಾನ್ ಏನು ಕಲಿತಿದೆ ಎಂದು ನೋಡಿ. ಮುಂದಿನ ಲೇಯರ್‌ಗಳ ನ್ಯೂರಾನ್‌ಗಳು ಸರಳ ಆಕಾರಗಳನ್ನು ಸೇರಿಸಿ ಸಂಕೀರ್ಣ ಆಕಾರಗಳನ್ನು ಮಾಡುತ್ತವೆ.',
    tip4: '<b>ನೀವೇ ಬಿಡಿಸಿ</b> ಆಯ್ಕೆಮಾಡಿ, ಒಂದು ಬಣ್ಣ ತೆಗೆದುಕೊಂಡು ಚಿತ್ರದ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ ನಿಮ್ಮದೇ ಒಗಟು ರಚಿಸಿ. ನೆಟ್‌ವರ್ಕ್ ಕಲಿಯಲಾಗದ ಒಗಟನ್ನು ಬಿಡಿಸಬಲ್ಲಿರಾ?',
    tip5: '<b>ತರಗತಿ ಚಟುವಟಿಕೆ:</b> ಪ್ರತಿ ಸವಾಲಿಗೂ ಮೊದಲು ತರಗತಿ ಮತ ಹಾಕಲಿ: "ಇದು ಕಲಿಯುತ್ತದೆಯೇ?" ನಂತರ ಸ್ಮಾರ್ಟ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಎಲ್ಲರೂ ಸೇರಿ "ಕಲಿಸಿ" ಒತ್ತಿ, ಏಕೆ ಹಾಗಾಯಿತು ಎಂದು ಚರ್ಚಿಸಿ. ಊಹೆಗಳನ್ನು ಬರೆಯಲು ವರ್ಕ್‌ಶೀಟ್ ಮುದ್ರಿಸಿ.',
    tip6: 'ಪ್ರೊಜೆಕ್ಟರ್‌ನಲ್ಲಿ <b>ಪೂರ್ಣ ಪರದೆ</b> ಬಳಸಿ. <b>ಈ ಸೆಟಪ್ ಹಂಚಿಕೊಳ್ಳಿ</b> ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಕಳುಹಿಸಲು ಒಂದು ಲಿಂಕ್ ಮಾಡುತ್ತದೆ. ಎಲ್ಲವೂ ಇದೇ ಸಾಧನದಲ್ಲಿ ನಡೆಯುತ್ತದೆ ಮತ್ತು ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.'
  },
  ml: {
    app_title: 'ന്യൂറൽ നെറ്റ്‌വർക്ക് കളിസ്ഥലം',
    intro: 'ഒരു ചെറിയ ന്യൂറൽ നെറ്റ്‌വർക്ക് ഓറഞ്ചും നീലയും കുത്തുകളെ വേർതിരിക്കാൻ പഠിക്കുന്നത് കാണൂ. അതിന്റെ ലെയറുകളും ന്യൂറോണുകളും ക്രമീകരണങ്ങളും മാറ്റി, ഒരു യന്ത്രം ഉദാഹരണങ്ങളിൽ നിന്ന് എങ്ങനെ പഠിക്കുന്നുവെന്ന് മനസ്സിലാക്കൂ.',
    train: 'പഠിപ്പിക്കൂ',
    step: 'ഒരു ചുവട്',
    step_title: 'ഒരു എപ്പോക്ക് പഠിപ്പിക്കുക (എല്ലാ ട്രെയിനിങ് കുത്തുകളിലൂടെയും ഒരു മുഴുവൻ റൗണ്ട്)',
    reset_title: 'പുതിയ റാൻഡം വെയ്റ്റുകളോടെ വീണ്ടും പഠനം തുടങ്ങുക',
    epoch: 'എപ്പോക്ക്',
    speed: 'വേഗം',
    speed_slow: 'പതുക്കെ',
    speed_normal: 'സാധാരണ',
    speed_fast: 'വേഗത്തിൽ',
    data: 'ഡാറ്റ',
    dataset: 'ഡാറ്റാസെറ്റ് തിരഞ്ഞെടുക്കുക',
    ds_blobs: 'രണ്ട് കൂട്ടങ്ങൾ',
    ds_circle: 'വൃത്തം',
    ds_xor: 'XOR',
    ds_spiral: 'ചുരുൾ',
    ds_draw: 'സ്വയം വരയ്ക്കൂ',
    draw_hint: 'ഒരു നിറം തിരഞ്ഞെടുക്കുക, എന്നിട്ട് ചിത്രത്തിൽ ടാപ്പ് ചെയ്തോ വലിച്ചോ കുത്തുകൾ ചേർക്കുക. നിങ്ങളുടെ എല്ലാ കുത്തുകളും ട്രെയിനിങ്ങിന് ഉപയോഗിക്കും.',
    tool_orange: 'ഓറഞ്ച്',
    tool_blue: 'നീല',
    tool_erase: 'റബ്ബർ',
    clear_points: 'കുത്തുകൾ മായ്ക്കുക',
    confirm_clear: 'നിങ്ങൾ വരച്ച എല്ലാ കുത്തുകളും നീക്കണോ?',
    too_many: 'പരമാവധി {n} കുത്തുകൾ വരയ്ക്കാം.',
    points_n: 'കുത്തുകൾ: {n}',
    noise: 'നോയ്സ്: {n}%',
    noise_hint: 'കൂടുതൽ നോയ്സ് എന്നാൽ കൂടുതൽ ചിതറിയ, കൂടിക്കലർന്ന കുത്തുകൾ.',
    split: 'ട്രെയിനിങ് ഡാറ്റ: {n}%',
    split_hint: 'ബാക്കി {n}% മാറ്റിവയ്ക്കുന്നു, നെറ്റ്‌വർക്ക് ഇതുവരെ കാണാത്ത കുത്തുകളിൽ അതിനെ പരീക്ഷിക്കാൻ.',
    new_data: 'പുതിയ ഡാറ്റ',
    show_test: 'ടെസ്റ്റ് കുത്തുകൾ കാണിക്കുക',
    sharp: 'വ്യക്തമായ അതിർവര',
    network: 'നെറ്റ്‌വർക്ക്',
    inputs: 'ഇൻപുട്ടുകൾ (ഫീച്ചറുകൾ)',
    inputs_hint: 'അധിക ഇൻപുട്ടുകൾ നെറ്റ്‌വർക്കിന് അധിക സൂചനകൾ നൽകുന്നു.',
    need_input: 'കുറഞ്ഞത് ഒരു ഇൻപുട്ടെങ്കിലും വേണം.',
    hidden_layers: 'ഹിഡൻ ലെയറുകൾ',
    layer_n: 'ലെയർ {n}',
    neurons: 'ന്യൂറോണുകൾ',
    add_layer: 'ഒരു ഹിഡൻ ലെയർ ചേർക്കുക',
    remove_layer: 'ഒരു ഹിഡൻ ലെയർ നീക്കുക',
    add_neuron: 'ലെയർ {n}-ൽ ഒരു ന്യൂറോൺ ചേർക്കുക',
    remove_neuron: 'ലെയർ {n}-ൽ നിന്ന് ഒരു ന്യൂറോൺ നീക്കുക',
    no_hidden: 'ഹിഡൻ ലെയർ ഇല്ല: നെറ്റ്‌വർക്ക് മുഴുവനും ഒരൊറ്റ ന്യൂറോൺ.',
    activation: 'ആക്ടിവേഷൻ',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'സിഗ്മോയ്ഡ്',
    act_linear: 'ലീനിയർ (ഒന്നുമില്ല)',
    lr: 'ലേണിങ് റേറ്റ്',
    share_setup: 'ഈ സെറ്റപ്പ് പങ്കിടുക',
    defaults: 'ആദ്യ ക്രമീകരണങ്ങൾ തിരികെ കൊണ്ടുവരിക',
    inside: 'നെറ്റ്‌വർക്കിനുള്ളിൽ',
    inside_hint: 'ഓരോ ചതുരവും ഒരു ന്യൂറോൺ ചിത്രത്തിലുടനീളം എന്ത് "കാണുന്നു" എന്ന് കാണിക്കുന്നു. വലുതായി കാണാൻ ഒരു ചതുരത്തിൽ ടാപ്പ് ചെയ്യുക.',
    w_pos: 'പോസിറ്റീവ് വെയ്റ്റ്',
    w_neg: 'നെഗറ്റീവ് വെയ്റ്റ്',
    w_thick: 'കട്ടിയുള്ള വര = ശക്തമായ വെയ്റ്റ്',
    output: 'ഔട്ട്‌പുട്ട്',
    output_hint: 'പശ്ചാത്തല നിറം = ഓരോ സ്ഥലത്തിനും നെറ്റ്‌വർക്കിന്റെ ഊഹം. കടും നിറം = കൂടുതൽ ഉറപ്പ്.',
    canvas_label: 'കുത്തുകളുടെയും നെറ്റ്‌വർക്കിന്റെ ഊഹങ്ങളുടെയും ചിത്രം',
    canvas_empty: 'കുത്തുകൾ ചേർക്കാൻ ഇവിടെ ടാപ്പ് ചെയ്യുക',
    train_loss: 'ട്രെയിനിങ് ലോസ്',
    test_loss: 'ടെസ്റ്റ് ലോസ്',
    train_acc: 'ട്രെയിനിങ് കൃത്യത',
    test_acc: 'ടെസ്റ്റ് കൃത്യത',
    loss_chart: 'സമയത്തിനൊപ്പം ലോസ്',
    chart_label: 'ഓരോ എപ്പോക്കിനും ശേഷമുള്ള ട്രെയിനിങ് ലോസിന്റെയും ടെസ്റ്റ് ലോസിന്റെയും ചാർട്ട്',
    legend_train: 'ട്രെയിനിങ്',
    legend_test: 'ടെസ്റ്റ്',
    chart_hint: 'കുറയുന്തോറും നല്ലത്. ട്രെയിനിങ് വര താഴുമ്പോൾ ടെസ്റ്റ് വര കയറുന്നുവെങ്കിൽ, നെറ്റ്‌വർക്ക് ഓവർഫിറ്റിങ് ചെയ്യുകയാണ്.',
    ins_hint: 'ഇവ ഈ ന്യൂറോണിന്റെ ഇപ്പോഴത്തെ വെയ്റ്റുകളും ബയസുമാണ്. പഠിക്കുമ്പോൾ അവ മാറുന്നത് കാണൂ.',
    ins_prev: 'h₁, h₂… എന്നത് മുൻപത്തെ ലെയറിലെ ന്യൂറോണുകളാണ്.',
    ins_input: 'ഇൻപുട്ടിന് വെയ്റ്റുകളില്ല. അത് സ്വന്തം മൂല്യം അടുത്ത ലെയറിലേക്ക് കൈമാറുന്നു, അത്രമാത്രം.',
    col_inputs: 'ഇൻപുട്ടുകൾ',
    col_hidden: 'ഹിഡൻ {n}',
    col_output: 'ഔട്ട്‌പുട്ട്',
    node_input: 'ഇൻപുട്ട് {name}',
    node_hidden: 'ഹിഡൻ ലെയർ {l}-ലെ ന്യൂറോൺ {n}',
    node_output: 'ഔട്ട്‌പുട്ട് ന്യൂറോൺ',
    preview_input: 'ഇൻപുട്ട് {name} കാണിക്കുന്നു',
    preview_hidden: 'ഹിഡൻ ലെയർ {l}-ലെ ന്യൂറോൺ {n} കാണിക്കുന്നു',
    show_output: 'ഔട്ട്‌പുട്ട് കാണിക്കുക',
    coach_start: 'നെറ്റ്‌വർക്ക് പഠിക്കാൻ "പഠിപ്പിക്കൂ" അമർത്തുക. പശ്ചാത്തലം ഓരോ സ്ഥലത്തിനും അതിന്റെ ഊഹം കാണിക്കുന്നു.',
    coach_training: 'പഠിക്കുന്നു… ലോസ് കുറയുന്നതും നിറങ്ങൾ ഉറയ്ക്കുന്നതും കാണൂ.',
    coach_paused: 'നിർത്തിവച്ചിരിക്കുന്നു. ഓരോ എപ്പോക്ക് വീതം പഠിപ്പിക്കാൻ "ഒരു ചുവട്" അമർത്തുക.',
    coach_line: 'ഹിഡൻ ലെയർ ഇല്ലെങ്കിൽ നെറ്റ്‌വർക്കിന് ഒരൊറ്റ നേർരേഖ മാത്രമേ വരയ്ക്കാനാകൂ, ഇവിടെ അത് പോരാ. ഒരു ഹിഡൻ ലെയർ ചേർക്കൂ!',
    coach_linear: 'ലീനിയർ ആക്ടിവേഷനോടെ, എത്ര ലെയറുകളുണ്ടെങ്കിലും ഒരു നേർരേഖ പോലെയേ പ്രവർത്തിക്കൂ. tanh അല്ലെങ്കിൽ ReLU പരീക്ഷിക്കൂ.',
    coach_overfit: 'ട്രെയിനിങ് ലോസ് കുറവ്, പക്ഷേ ടെസ്റ്റ് ലോസ് കൂടുതൽ: നെറ്റ്‌വർക്ക് ട്രെയിനിങ് കുത്തുകൾ കാണാപ്പാഠം പഠിക്കുകയാണ്. ഇതാണ് ഓവർഫിറ്റിങ്.',
    coach_great: 'പഠിച്ചു! {acc}% ടെസ്റ്റ് കുത്തുകളും ശരിയായ വശത്താണ്.',
    coach_great_draw: 'പഠിച്ചു! നിങ്ങളുടെ {acc}% കുത്തുകളും ശരിയായ വശത്താണ്.',
    coach_slow: 'വളരെ പതുക്കെയാണോ പഠിക്കുന്നത്? ലേണിങ് റേറ്റ് വളരെ ചെറുതാണ്, അതുകൊണ്ട് ഓരോ ചുവടും ചെറുതാണ്. വലിയ റേറ്റ് പരീക്ഷിക്കൂ.',
    coach_stuck: 'കുടുങ്ങിയോ? പുതിയ റാൻഡം വെയ്റ്റുകൾക്കായി റീസെറ്റ് അമർത്തുക, അല്ലെങ്കിൽ നെറ്റ്‌വർക്ക് മാറ്റുക.',
    coach_explode: 'അയ്യോ! ലേണിങ് റേറ്റ് വളരെ വലുതായതിനാൽ വെയ്റ്റുകൾ നിയന്ത്രണം വിട്ടു. ചെറിയ റേറ്റ് തിരഞ്ഞെടുക്കൂ.',
    coach_need_points: 'ചിത്രത്തിൽ കുറച്ച് ഓറഞ്ചും കുറച്ച് നീലയും കുത്തുകൾ ചേർക്കൂ.',
    challenges: 'വെല്ലുവിളികൾ',
    challenges_intro: 'ആദ്യം ഊഹിക്കൂ, എന്നിട്ട് "പരീക്ഷിക്കൂ" അമർത്തി പഠിപ്പിക്കൂ. നിങ്ങളുടെ ഊഹം ശരിയായോ?',
    try_it: 'പരീക്ഷിക്കൂ',
    notice: 'എന്ത് ശ്രദ്ധിക്കണം',
    loaded: 'വെല്ലുവിളി {n} തയ്യാർ. "പഠിപ്പിക്കൂ" അമർത്തൂ!',
    print_ws: 'വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യുക',
    ws_title: 'വർക്ക്ഷീറ്റ്',
    ws_name: 'പേര്',
    ws_class: 'ക്ലാസ്',
    ws_date: 'തീയതി',
    ws_guess: 'എന്റെ ഊഹം:',
    ws_saw: 'എന്ത് സംഭവിച്ചു, എന്തുകൊണ്ട്:',
    explain: 'ഉള്ളിൽ എന്താണ് നടക്കുന്നത്?',
    help_title: 'എങ്ങനെ ഉപയോഗിക്കാം / ക്ലാസ് മുറിക്കുള്ള ആശയങ്ങൾ',
    tip1: '<b>പഠിപ്പിക്കൂ</b> (അല്ലെങ്കിൽ <kbd>സ്പേസ്ബാർ</kbd>) അമർത്തി, നെറ്റ്‌വർക്ക് പഠിക്കുമ്പോൾ നിറങ്ങൾ മാറുന്നത് കാണൂ. <b>ഒരു ചുവട്</b> ഒരു എപ്പോക്ക് മാത്രം പഠിപ്പിക്കുന്നു, അതിനാൽ പതുക്കെ മുന്നോട്ട് പോകാം.',
    tip2: 'ഡാറ്റാസെറ്റ്, ഹിഡൻ ലെയറുകളുടെ എണ്ണം, ന്യൂറോണുകൾ എന്നിവ മാറ്റൂ. നെറ്റ്‌വർക്ക് മാറ്റിയാലുടൻ അത് പുതിയ റാൻഡം വെയ്റ്റുകളോടെ വീണ്ടും തുടങ്ങും. <b>റീസെറ്റ്</b> ചെയ്യുന്നതും ഇതുതന്നെ.',
    tip3: '<b>നെറ്റ്‌വർക്കിനുള്ളിൽ</b> എന്ന ഭാഗത്തെ ചെറിയ ചതുരങ്ങളിൽ ടാപ്പ് ചെയ്ത് ഓരോ ന്യൂറോണും എന്ത് പഠിച്ചുവെന്ന് കാണൂ. പിന്നീടുള്ള ലെയറുകളിലെ ന്യൂറോണുകൾ ലളിതമായ ആകൃതികൾ ചേർത്ത് സങ്കീർണമായ ആകൃതികൾ ഉണ്ടാക്കുന്നു.',
    tip4: '<b>സ്വയം വരയ്ക്കൂ</b> തിരഞ്ഞെടുത്ത്, ഒരു നിറമെടുത്ത് ചിത്രത്തിൽ ടാപ്പ് ചെയ്ത് സ്വന്തം പസിൽ ഉണ്ടാക്കൂ. നെറ്റ്‌വർക്കിന് പഠിക്കാൻ കഴിയാത്ത ഒരു പസിൽ വരയ്ക്കാമോ?',
    tip5: '<b>ക്ലാസ് പ്രവർത്തനം:</b> ഓരോ വെല്ലുവിളിക്കും മുമ്പ് ക്ലാസ് വോട്ട് ചെയ്യട്ടെ: "ഇത് പഠിക്കുമോ?" എന്നിട്ട് സ്മാർട്ട്ബോർഡിൽ ഒരുമിച്ച് "പഠിപ്പിക്കൂ" അമർത്തി, എന്തുകൊണ്ട് അങ്ങനെ സംഭവിച്ചുവെന്ന് ചർച്ച ചെയ്യൂ. ഊഹങ്ങൾ എഴുതാൻ വർക്ക്ഷീറ്റ് പ്രിന്റ് ചെയ്യൂ.',
    tip6: 'പ്രൊജക്ടറിൽ <b>പൂർണ്ണ സ്ക്രീൻ</b> ഉപയോഗിക്കൂ. <b>ഈ സെറ്റപ്പ് പങ്കിടുക</b> വിദ്യാർഥികൾക്ക് അയയ്ക്കാൻ ഒരു ലിങ്ക് ഉണ്ടാക്കുന്നു. എല്ലാം ഈ ഉപകരണത്തിൽ തന്നെ പ്രവർത്തിക്കുന്നു, ഇന്റർനെറ്റ് ഇല്ലാതെയും.'
  },
  ur: {
    app_title: 'نیورل نیٹ ورک کھیل کا میدان',
    intro: 'دیکھیں کہ ایک چھوٹا سا نیورل نیٹ ورک نارنجی اور نیلے نقطوں کو الگ کرنا کیسے سیکھتا ہے۔ اس کی لیئر، نیورون اور سیٹنگ بدل کر سمجھیں کہ مشین مثالوں سے کیسے سیکھتی ہے۔',
    train: 'سکھائیں',
    step: 'ایک قدم',
    step_title: 'ایک ایپوک کے لیے سکھائیں (تمام ٹریننگ نقطوں پر ایک پورا چکر)',
    reset_title: 'نئے رینڈم ویٹ کے ساتھ دوبارہ سیکھنا شروع کریں',
    epoch: 'ایپوک',
    speed: 'رفتار',
    speed_slow: 'آہستہ',
    speed_normal: 'عام',
    speed_fast: 'تیز',
    data: 'ڈیٹا',
    dataset: 'ڈیٹا سیٹ چنیں',
    ds_blobs: 'دو جھنڈ',
    ds_circle: 'دائرہ',
    ds_xor: 'XOR',
    ds_spiral: 'مرغولہ',
    ds_draw: 'خود بنائیں',
    draw_hint: 'ایک رنگ چنیں، پھر تصویر پر ٹیپ کریں یا انگلی گھما کر نقطے جوڑیں۔ آپ کے سارے نقطے ٹریننگ کے لیے استعمال ہوتے ہیں۔',
    tool_orange: 'نارنجی',
    tool_blue: 'نیلا',
    tool_erase: 'ربڑ',
    clear_points: 'نقطے مٹائیں',
    confirm_clear: 'آپ کے بنائے ہوئے سارے نقطے ہٹا دیں؟',
    too_many: 'آپ زیادہ سے زیادہ {n} نقطے بنا سکتے ہیں۔',
    points_n: 'نقطے: {n}',
    noise: 'شور (نوائز): {n}%',
    noise_hint: 'زیادہ شور یعنی زیادہ بکھرے ہوئے، ملے جلے نقطے۔',
    split: 'ٹریننگ ڈیٹا: {n}%',
    split_hint: 'باقی {n}% نقطے الگ رکھے جاتے ہیں، تاکہ نیٹ ورک کو ایسے نقطوں پر پرکھا جا سکے جو اس نے کبھی نہیں دیکھے۔',
    new_data: 'نیا ڈیٹا',
    show_test: 'ٹیسٹ نقطے دکھائیں',
    sharp: 'صاف حد بندی',
    network: 'نیٹ ورک',
    inputs: 'ان پٹ (فیچر)',
    inputs_hint: 'زیادہ ان پٹ سے نیٹ ورک کو زیادہ سراغ ملتے ہیں۔',
    need_input: 'کم از کم ایک ان پٹ رکھنا ضروری ہے۔',
    hidden_layers: 'ہڈن لیئر',
    layer_n: 'لیئر {n}',
    neurons: 'نیورون',
    add_layer: 'ایک ہڈن لیئر جوڑیں',
    remove_layer: 'ایک ہڈن لیئر ہٹائیں',
    add_neuron: 'لیئر {n} میں ایک نیورون جوڑیں',
    remove_neuron: 'لیئر {n} سے ایک نیورون ہٹائیں',
    no_hidden: 'کوئی ہڈن لیئر نہیں: پورا نیٹ ورک بس ایک نیورون ہے۔',
    activation: 'ایکٹیویشن',
    act_relu: 'ReLU',
    act_tanh: 'tanh',
    act_sigmoid: 'سگمائیڈ',
    act_linear: 'لینیئر (کوئی نہیں)',
    lr: 'لرننگ ریٹ',
    share_setup: 'یہ سیٹ اپ شیئر کریں',
    defaults: 'ابتدائی سیٹنگ واپس لائیں',
    inside: 'نیٹ ورک کے اندر',
    inside_hint: 'ہر خانہ دکھاتا ہے کہ ایک نیورون پوری تصویر میں کیا "دیکھتا" ہے۔ بڑا دیکھنے کے لیے کسی خانے پر ٹیپ کریں۔',
    w_pos: 'مثبت ویٹ',
    w_neg: 'منفی ویٹ',
    w_thick: 'موٹی لکیر = زیادہ طاقتور ویٹ',
    output: 'آؤٹ پٹ',
    output_hint: 'پس منظر کا رنگ = ہر جگہ کے لیے نیٹ ورک کا اندازہ۔ گہرا رنگ = زیادہ یقین۔',
    canvas_label: 'نقطوں اور نیٹ ورک کے اندازوں کی تصویر',
    canvas_empty: 'نقطے جوڑنے کے لیے یہاں ٹیپ کریں',
    train_loss: 'ٹریننگ لاس',
    test_loss: 'ٹیسٹ لاس',
    train_acc: 'ٹریننگ درستی',
    test_acc: 'ٹیسٹ درستی',
    loss_chart: 'وقت کے ساتھ لاس',
    chart_label: 'ہر ایپوک کے بعد ٹریننگ لاس اور ٹیسٹ لاس کا چارٹ',
    legend_train: 'ٹریننگ',
    legend_test: 'ٹیسٹ',
    chart_hint: 'جتنا کم، اتنا اچھا۔ اگر ٹریننگ کی لکیر نیچے جائے مگر ٹیسٹ کی لکیر اوپر چڑھے، تو نیٹ ورک اوورفٹنگ کر رہا ہے۔',
    ins_hint: 'یہ اس نیورون کے اس وقت کے ویٹ اور بائس ہیں۔ سیکھتے وقت انہیں بدلتے دیکھیں۔',
    ins_prev: 'h₁, h₂… پچھلی لیئر کے نیورون ہیں۔',
    ins_input: 'ان پٹ کا کوئی ویٹ نہیں ہوتا۔ وہ بس اپنی قدر اگلی لیئر کو دے دیتا ہے۔',
    col_inputs: 'ان پٹ',
    col_hidden: 'ہڈن {n}',
    col_output: 'آؤٹ پٹ',
    node_input: 'ان پٹ {name}',
    node_hidden: 'ہڈن لیئر {l} کا نیورون {n}',
    node_output: 'آؤٹ پٹ نیورون',
    preview_input: 'ان پٹ {name} دکھایا جا رہا ہے',
    preview_hidden: 'ہڈن لیئر {l} کا نیورون {n} دکھایا جا رہا ہے',
    show_output: 'آؤٹ پٹ دکھائیں',
    coach_start: 'نیٹ ورک کو سکھانے کے لیے "سکھائیں" دبائیں۔ پس منظر ہر جگہ کے لیے اس کا اندازہ دکھاتا ہے۔',
    coach_training: 'سیکھ رہا ہے… لاس کو گھٹتے اور رنگوں کو جمتے دیکھیں۔',
    coach_paused: 'رکا ہوا ہے۔ ایک ایک ایپوک سکھانے کے لیے "ایک قدم" دبائیں۔',
    coach_line: 'ہڈن لیئر کے بغیر نیٹ ورک صرف ایک سیدھی لکیر کھینچ سکتا ہے، اور یہاں وہ کافی نہیں۔ ایک ہڈن لیئر جوڑیں!',
    coach_linear: 'لینیئر ایکٹیویشن کے ساتھ کئی لیئر بھی ایک سیدھی لکیر جیسا ہی کام کرتی ہیں۔ tanh یا ReLU آزمائیں۔',
    coach_overfit: 'ٹریننگ لاس کم ہے مگر ٹیسٹ لاس زیادہ: نیٹ ورک ٹریننگ نقطوں کو رٹ رہا ہے۔ اسے اوورفٹنگ کہتے ہیں۔',
    coach_great: 'سیکھ لیا! {acc}% ٹیسٹ نقطے صحیح طرف ہیں۔',
    coach_great_draw: 'سیکھ لیا! آپ کے {acc}% نقطے صحیح طرف ہیں۔',
    coach_slow: 'بہت آہستہ سیکھ رہا ہے؟ لرننگ ریٹ بہت چھوٹا ہے، اس لیے ہر قدم بھی چھوٹا ہے۔ بڑا ریٹ آزمائیں۔',
    coach_stuck: 'اٹک گیا؟ نئے رینڈم ویٹ کے لیے ری سیٹ دبائیں، یا نیٹ ورک بدلیں۔',
    coach_explode: 'ارے! لرننگ ریٹ بہت بڑا ہونے سے ویٹ بے قابو ہو گئے۔ چھوٹا ریٹ چنیں۔',
    coach_need_points: 'تصویر پر کچھ نارنجی اور کچھ نیلے نقطے جوڑیں۔',
    challenges: 'چیلنج',
    challenges_intro: 'پہلے اندازہ لگائیں، پھر "آزمائیں" دبا کر سکھائیں۔ کیا آپ کا اندازہ درست نکلا؟',
    try_it: 'آزمائیں',
    notice: 'کس بات پر دھیان دیں',
    loaded: 'چیلنج {n} تیار ہے۔ "سکھائیں" دبائیں!',
    print_ws: 'ورک شیٹ پرنٹ کریں',
    ws_title: 'ورک شیٹ',
    ws_name: 'نام',
    ws_class: 'جماعت',
    ws_date: 'تاریخ',
    ws_guess: 'میرا اندازہ:',
    ws_saw: 'کیا ہوا، اور کیوں:',
    explain: 'اندر کیا ہو رہا ہے؟',
    help_title: 'استعمال کیسے کریں / کلاس کے لیے تجاویز',
    tip1: '<b>سکھائیں</b> (یا <kbd>اسپیس بار</kbd>) دبائیں اور نیٹ ورک کے سیکھتے وقت رنگوں کو بدلتے دیکھیں۔ <b>ایک قدم</b> صرف ایک ایپوک سکھاتا ہے، تاکہ آپ آہستہ آہستہ چل سکیں۔',
    tip2: 'ڈیٹا سیٹ، ہڈن لیئر کی تعداد اور نیورون بدلیں۔ نیٹ ورک بدلتے ہی وہ نئے رینڈم ویٹ کے ساتھ دوبارہ شروع ہوتا ہے۔ <b>ری سیٹ</b> بھی یہی کرتا ہے۔',
    tip3: '<b>نیٹ ورک کے اندر</b> والے چھوٹے خانوں پر ٹیپ کر کے دیکھیں کہ ہر نیورون نے کیا سیکھا۔ آگے کی لیئر کے نیورون آسان شکلوں کو ملا کر مشکل شکلیں بناتے ہیں۔',
    tip4: '<b>خود بنائیں</b> چنیں، رنگ چنیں اور تصویر پر ٹیپ کر کے اپنی پہیلی بنائیں۔ کیا آپ ایسی پہیلی بنا سکتے ہیں جو نیٹ ورک نہ سیکھ پائے؟',
    tip5: '<b>کلاس کی سرگرمی:</b> ہر چیلنج سے پہلے پوری کلاس ووٹ دے: "کیا یہ سیکھ پائے گا؟" پھر اسمارٹ بورڈ پر مل کر "سکھائیں" دبائیں اور بحث کریں کہ ایسا کیوں ہوا۔ اندازے لکھنے کے لیے ورک شیٹ پرنٹ کریں۔',
    tip6: 'پروجیکٹر پر <b>پوری اسکرین</b> استعمال کریں۔ <b>یہ سیٹ اپ شیئر کریں</b> سے طلبہ کو بھیجنے کے لیے لنک بنتا ہے۔ سب کچھ اسی آلے پر چلتا ہے اور انٹرنیٹ کے بغیر بھی کام کرتا ہے۔'
  }
};
