/* Extra English training text for the "English only" tokenizer. Real English tokenizers are
   trained on huge amounts of English text; this small stand-in lets the English-only model
   learn up to 600 merges. It is training data, not UI text. */
window.TOKLAB_EN_EXTRA = [
  "The school day starts with the morning assembly. The students stand in lines, sing the national anthem and listen to the news of the day. Then they go to their classrooms. In the first period the class has mathematics. The teacher writes a problem on the board, and the students try to solve it in their notebooks. Some students find it easy and some find it hard, so they help each other.",
  "In the science class the students learn about the water cycle. The sun heats the water in rivers, lakes and the sea. The water turns into vapour and rises into the sky. High in the sky the vapour cools and forms clouds. When the clouds become heavy, the water falls back to the earth as rain. The rain fills the rivers again, and the cycle goes on and on.",
  "Plants make their own food. They use sunlight, water and air to make food in their green leaves. This is called photosynthesis. Animals cannot make their own food, so they eat plants or other animals. People also need plants for food, for medicine and for the air we breathe. That is why we should plant more trees and take care of them.",
  "India is a large country with many states, many languages and many festivals. People celebrate Diwali, Eid, Christmas, Holi, Pongal, Onam, Baisakhi and many other festivals. During festivals, families meet, cook special food and share sweets with their neighbours. Children wear new clothes and play with their friends. Every festival has its own story and its own songs.",
  "Trains connect the cities and villages of India. Every day millions of people travel by train to go to work, to school or to meet their families. A long train journey is full of sights and sounds. You can see green fields, rivers, mountains and small stations. People talk, share food and make new friends on the way.",
  "Cricket is one of the most popular games in India. Children play cricket in the streets, in the parks and in the school ground. Some children like football, hockey, kabaddi or badminton. Playing games makes our body strong and teaches us to work as a team. It also teaches us to win with grace and to lose with a smile.",
  "Computers and phones help us to learn new things. We can watch videos, read books and talk to people far away. But we must use them in a safe and wise way. We should never share our password with anyone. We should check if a message is true before we share it. We should also take breaks, play outside and spend time with our family.",
  "Artificial intelligence, or AI, is a kind of computer program that can learn from examples. An AI model reads a lot of text, looks at many pictures or listens to many sounds, and finds patterns in them. It can then answer questions, translate languages or recognise faces. But an AI model can also make mistakes, so we must always think for ourselves and check its answers.",
  "A good student asks questions. When you do not understand something, ask your teacher or your friends. Read the lesson again, write notes in your own words and try to explain it to someone else. If you can teach it, you have really learned it. Learning is not a race. Every person learns at their own speed, and every small step is important.",
  "In the evening the family sits together for dinner. Grandmother tells stories from the old days, and grandfather talks about the time when there was no electricity in the village. The children listen with wide eyes. After dinner they finish their homework, read a little and go to bed early, because tomorrow is another day of school.",
  "The library is the quietest room in the school. Its shelves are full of storybooks, comics, dictionaries and books about science, history and geography. Students can borrow two books every week. The librarian keeps a register and writes the name of every book and every student. Before the holidays, many children borrow extra books to read at home.",
  "Our earth moves around the sun. It takes about three hundred and sixty-five days to go around the sun once, and that is one year. The earth also spins like a top. It takes one day to spin once, and that is why we have day and night. The moon goes around the earth, and it takes about one month to go around once.",
  "Clean water is very important for good health. We should drink clean water, wash our hands with soap before eating and keep our homes and streets clean. Many diseases spread through dirty water and dirty hands. When everyone in the village keeps the village clean, everyone stays healthy and happy.",
  "Farmers grow the food that we eat every day. They grow rice, wheat, pulses, vegetables and fruits. Farming is hard work. Farmers wake up early, take care of the soil, water the fields and protect the crops from insects. When the rain comes on time, the harvest is good and the farmers are happy. We should never waste food.",
  "Numbers are everywhere around us. We use numbers to count money, to tell the time, to measure the length of a room and to keep the score in a game. If a pencil costs five rupees and a notebook costs forty rupees, then two pencils and one notebook cost fifty rupees. Mathematics helps us to think clearly and to solve problems step by step.",
  "Every year our school has a science fair. Students make models of volcanoes, solar cookers, water filters and small robots. They explain their models to the visitors and answer their questions. The best part of the fair is not the prize. The best part is that everyone learns something new and feels proud of their work.",
  "Long ago, people wrote on palm leaves, stone and cloth. Later they wrote on paper, and then books were printed by machines. Today we can read books on a phone or a computer. But the idea is the same: people want to share stories, knowledge and ideas with others, so that the next generation can learn from them."
].join('\n');
